LLVM: AArch64LoadStoreOptimizer.cpp File Reference
LLVM API Documentation
AArch64LoadStoreOptimizer.cpp File Reference
#include "AArch64InstrInfo.h"
#include "AArch64Subtarget.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "aarch64-ldst-opt"
Functions
STATISTIC (NumPairCreated, "Number of load/store pair instructions generated")
STATISTIC (NumPostFolded, "Number of post-index updates folded")
STATISTIC (NumPreFolded, "Number of pre-index updates folded")
STATISTIC (NumUnscaledPairCreated, "Number of load/store from unscaled generated")
static bool isUnscaledLdst (unsigned Opc)
static unsigned getMatchingPairOpcode (unsigned Opc)
static unsigned getPreIndexedOpcode (unsigned Opc)
static unsigned getPostIndexedOpcode (unsigned Opc)
static void trackRegDefsUses (MachineInstr *MI, BitVector &ModifiedRegs, BitVector &UsedRegs, const TargetRegisterInfo *TRI)
static bool inBoundsForPair (bool IsUnscaled, int Offset, int OffsetStride)
static int alignTo (int Num, int PowOf2)
static bool isMatchingUpdateInsn (MachineInstr *MI, unsigned BaseReg, int Offset)
Variables
static cl::opt< unsigned > ScanLimit ("aarch64-load-store-scan-limit", cl::init(20), cl::Hidden)
static cl::opt< bool > EnableAArch64UnscaledMemOp ("aarch64-unscaled-mem-op", cl::Hidden, cl::desc("Allow AArch64 unscaled load/store combining"), cl::init(true))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-ldst-opt"
Definition at line 33 of file AArch64LoadStoreOptimizer.cpp.
Function Documentation
alignTo()
int alignTo (int Num, int PowOf2) static
Definition at line 379 of file AArch64LoadStoreOptimizer.cpp.
getMatchingPairOpcode()
unsigned getMatchingPairOpcode (unsigned Opc) static
Definition at line 179 of file AArch64LoadStoreOptimizer.cpp.
References llvm_unreachable.
getPostIndexedOpcode()
unsigned getPostIndexedOpcode (unsigned Opc) static
Definition at line 243 of file AArch64LoadStoreOptimizer.cpp.
References llvm_unreachable.
getPreIndexedOpcode()
unsigned getPreIndexedOpcode (unsigned Opc) static
Definition at line 216 of file AArch64LoadStoreOptimizer.cpp.
References llvm_unreachable.
inBoundsForPair()
bool inBoundsForPair (bool IsUnscaled, int Offset, int OffsetStride) static
Definition at line 362 of file AArch64LoadStoreOptimizer.cpp.
isMatchingUpdateInsn()
bool isMatchingUpdateInsn (MachineInstr * MI, unsigned BaseReg, int Offset) static
Definition at line 607 of file AArch64LoadStoreOptimizer.cpp.
References llvm::AArch64_AM::getShiftValue().
isUnscaledLdst()
bool isUnscaledLdst (unsigned Opc) static
Definition at line 114 of file AArch64LoadStoreOptimizer.cpp.
STATISTIC() [1/4]
STATISTIC (NumPairCreated , "Number of load/store pair instructions generated")
AArch64AllocLoadStoreOpt - Post-register allocation pass to combine load / store instructions to form ldp / stp instructions.
STATISTIC() [2/4]
STATISTIC (NumPostFolded , "Number of post-index updates folded")
STATISTIC() [3/4]
STATISTIC (NumPreFolded , "Number of pre-index updates folded")
STATISTIC() [4/4]
STATISTIC (NumUnscaledPairCreated , "Number of load/store from unscaled generated")
trackRegDefsUses()
void trackRegDefsUses (MachineInstr * MI, BitVector & ModifiedRegs, BitVector & UsedRegs, const TargetRegisterInfo * TRI) static
trackRegDefsUses - Remember what registers the specified instruction uses and modifies.
Definition at line 340 of file AArch64LoadStoreOptimizer.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::getRegMask(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineOperand::isUse(), llvm::MCRegAliasIterator::isValid(), llvm::BitVector::set(), and llvm::BitVector::setBitsNotInMask().
Variable Documentation
EnableAArch64UnscaledMemOp
cl::opt< bool > EnableAArch64UnscaledMemOp("aarch64-unscaled-mem-op", cl::Hidden, cl::desc("Allow AArch64 unscaled load/store combining"), cl::init(true)) ("aarch64-unscaled-mem-op" , cl::Hidden , cl::desc("Allow AArch64 unscaled load/store combining") , cl::init(true)) static
ScanLimit
cl::opt< unsigned > ScanLimit("aarch64-load-store-scan-limit", cl::init(20), cl::Hidden) ("aarch64-load-store-scan-limit" , cl::init(20) , cl::Hidden) static