LLVM: AArch64BranchRelaxation.cpp File Reference
LLVM API Documentation
AArch64BranchRelaxation.cpp File Reference
#include "AArch64.h"
#include "AArch64InstrInfo.h"
#include "AArch64MachineFunctionInfo.h"
#include "AArch64Subtarget.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "aarch64-branch-relax"
Functions
STATISTIC (NumSplit, "Number of basic blocks split")
STATISTIC (NumRelaxed, "Number of conditional branches relaxed")
static bool BBHasFallthrough (MachineBasicBlock *MBB)
static bool isConditionalBranch (unsigned Opc)
static MachineBasicBlock * getDestBlock (MachineInstr *MI)
static unsigned getOppositeConditionOpcode (unsigned Opc)
static unsigned getBranchDisplacementBits (unsigned Opc)
static void invertBccCondition (MachineInstr *MI)
Variables
static cl::opt< bool > BranchRelaxation ("aarch64-branch-relax", cl::Hidden, cl::init(true), cl::desc("Relax out of range conditional branches"))
static cl::opt< unsigned > TBZDisplacementBits ("aarch64-tbz-offset-bits", cl::Hidden, cl::init(14), cl::desc("Restrict range of TB[N]Z instructions (DEBUG)"))
static cl::opt< unsigned > CBZDisplacementBits ("aarch64-cbz-offset-bits", cl::Hidden, cl::init(19), cl::desc("Restrict range of CB[N]Z instructions (DEBUG)"))
static cl::opt< unsigned > BCCDisplacementBits ("aarch64-bcc-offset-bits", cl::Hidden, cl::init(19), cl::desc("Restrict range of Bcc instructions (DEBUG)"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-branch-relax"
Definition at line 27 of file AArch64BranchRelaxation.cpp.
Function Documentation
BBHasFallthrough()
bool BBHasFallthrough (MachineBasicBlock * MBB) static
BBHasFallthrough - Return true if the specified basic block can fallthrough into the block immediately after it.
Definition at line 132 of file AArch64BranchRelaxation.cpp.
References llvm::MachineFunction::end(), llvm::MachineBasicBlock::getParent(), and llvm::MachineBasicBlock::successors().
getBranchDisplacementBits()
unsigned getBranchDisplacementBits (unsigned Opc) static
Definition at line 326 of file AArch64BranchRelaxation.cpp.
References BCCDisplacementBits, CBZDisplacementBits, llvm_unreachable, and TBZDisplacementBits.
getDestBlock()
MachineBasicBlock * getDestBlock (MachineInstr * MI) static
Definition at line 292 of file AArch64BranchRelaxation.cpp.
References llvm_unreachable.
getOppositeConditionOpcode()
unsigned getOppositeConditionOpcode (unsigned Opc) static
Definition at line 310 of file AArch64BranchRelaxation.cpp.
References llvm_unreachable.
invertBccCondition()
void invertBccCondition (MachineInstr * MI) inline static
Definition at line 345 of file AArch64BranchRelaxation.cpp.
References llvm::AArch64CC::getInvertedCondCode().
isConditionalBranch()
bool isConditionalBranch (unsigned Opc) static
Definition at line 275 of file AArch64BranchRelaxation.cpp.
STATISTIC() [1/2]
STATISTIC (NumRelaxed , "Number of conditional branches relaxed")
STATISTIC() [2/2]
STATISTIC (NumSplit , "Number of basic blocks split")
Variable Documentation
BCCDisplacementBits
cl::opt< unsigned > BCCDisplacementBits("aarch64-bcc-offset-bits", cl::Hidden, cl::init(19), cl::desc("Restrict range of Bcc instructions (DEBUG)")) ("aarch64-bcc-offset-bits" , cl::Hidden , cl::init(19) , cl::desc("Restrict range of Bcc instructions (DEBUG)")) static
Referenced by getBranchDisplacementBits().
BranchRelaxation
cl::opt< bool > BranchRelaxation("aarch64-branch-relax", cl::Hidden, cl::init(true), cl::desc("Relax out of range conditional branches")) ("aarch64-branch-relax" , cl::Hidden , cl::init(true) , cl::desc("Relax out of range conditional branches")) static
CBZDisplacementBits
cl::opt< unsigned > CBZDisplacementBits("aarch64-cbz-offset-bits", cl::Hidden, cl::init(19), cl::desc("Restrict range of CB[N]Z instructions (DEBUG)")) ("aarch64-cbz-offset-bits" , cl::Hidden , cl::init(19) , cl::desc("Restrict range of CB[N]Z instructions (DEBUG)")) static
Referenced by getBranchDisplacementBits().
TBZDisplacementBits
cl::opt< unsigned > TBZDisplacementBits("aarch64-tbz-offset-bits", cl::Hidden, cl::init(14), cl::desc("Restrict range of TB[N]Z instructions (DEBUG)")) ("aarch64-tbz-offset-bits" , cl::Hidden , cl::init(14) , cl::desc("Restrict range of TB[N]Z instructions (DEBUG)")) static
Referenced by getBranchDisplacementBits().