LLVM: AArch64TargetMachine.cpp File Reference
LLVM API Documentation
AArch64TargetMachine.cpp File Reference
#include "AArch64.h"
#include "AArch64TargetMachine.h"
#include "AArch64TargetObjectFile.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegAllocRegistry.h"
#include "llvm/IR/Function.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Transforms/Scalar.h"
Functions
void LLVMInitializeAArch64Target ()
static std::unique_ptr< TargetLoweringObjectFile > createTLOF (const Triple &TT)
Variables
static cl::opt< bool > EnableCCMP ("aarch64-ccmp", cl::desc("Enable the CCMP formation pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableMCR ("aarch64-mcr", cl::desc("Enable the machine combiner pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableStPairSuppress ("aarch64-stp-suppress", cl::desc("Suppress STP for AArch64"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableAdvSIMDScalar ("aarch64-simd-scalar", cl::desc("Enable use of AdvSIMD scalar" " integer instructions"), cl::init(false), cl::Hidden)
static cl::opt< bool > EnablePromoteConstant ("aarch64-promote-const", cl::desc("Enable the promote " "constant pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableCollectLOH ("aarch64-collect-loh", cl::desc("Enable the pass that emits the" " linker optimization hints (LOH)"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableDeadRegisterElimination ("aarch64-dead-def-elimination", cl::Hidden, cl::desc("Enable the pass that removes dead" " definitons and replaces stores to" " them with stores to the zero" " register"), cl::init(true))
static cl::opt< bool > EnableLoadStoreOpt ("aarch64-load-store-opt", cl::desc("Enable the load/store pair" " optimization pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableAtomicTidy ("aarch64-atomic-cfg-tidy", cl::Hidden, cl::desc("Run SimplifyCFG after expanding atomic operations" " to make use of cmpxchg flow-based information"), cl::init(true))
static cl::opt< bool > EnableEarlyIfConversion ("aarch64-enable-early-ifcvt", cl::Hidden, cl::desc("Run early if-conversion"), cl::init(true))
static cl::opt< bool > EnableCondOpt ("aarch64-condopt", cl::desc("Enable the condition optimizer pass"), cl::init(true), cl::Hidden)
static cl::opt< bool > EnableA53Fix835769 ("aarch64-fix-cortex-a53-835769", cl::Hidden, cl::desc("Work around Cortex-A53 erratum 835769"), cl::init(false))
static cl::opt< bool > EnableGEPOpt ("aarch64-gep-opt", cl::Hidden, cl::desc("Enable optimizations on complex GEPs"), cl::init(true))
Function Documentation
createTLOF()
std::unique_ptr< TargetLoweringObjectFile > createTLOF (const Triple & TT) static
Definition at line 99 of file AArch64TargetMachine.cpp.
References llvm::Triple::isOSBinFormatMachO(), and llvm::make_unique().
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), llvm::PPCTargetMachine::PPCTargetMachine(), and llvm::X86TargetMachine::X86TargetMachine().
LLVMInitializeAArch64Target()
void LLVMInitializeAArch64Target ()
Definition at line 89 of file AArch64TargetMachine.cpp.
References llvm::TheAArch64beTarget, llvm::TheAArch64leTarget, llvm::TheARM64Target, llvm::X, and Y.
Variable Documentation
EnableA53Fix835769
cl::opt< bool > EnableA53Fix835769("aarch64-fix-cortex-a53-835769", cl::Hidden, cl::desc("Work around Cortex-A53 erratum 835769"), cl::init(false)) ("aarch64-fix-cortex-a53-835769" , cl::Hidden , cl::desc("Work around Cortex-A53 erratum 835769") , cl::init(false)) static
EnableAdvSIMDScalar
cl::opt< bool > EnableAdvSIMDScalar("aarch64-simd-scalar", cl::desc("Enable use of AdvSIMD scalar" " integer instructions"), cl::init(false), cl::Hidden) ("aarch64-simd-scalar" , cl::desc("Enable use of AdvSIMD scalar" " integer instructions") , cl::init(false) , cl::Hidden) static
EnableAtomicTidy
cl::opt< bool > EnableAtomicTidy("aarch64-atomic-cfg-tidy", cl::Hidden, cl::desc("Run SimplifyCFG after expanding atomic operations" " to make use of cmpxchg flow-based information"), cl::init(true)) ("aarch64-atomic-cfg-tidy" , cl::Hidden , cl::desc("Run SimplifyCFG after expanding atomic operations" " to make use of cmpxchg flow-based information") , cl::init(true)) static
EnableCCMP
cl::opt< bool > EnableCCMP("aarch64-ccmp", cl::desc("Enable the CCMP formation pass"), cl::init(true), cl::Hidden) ("aarch64-ccmp" , cl::desc("Enable the CCMP formation pass") , cl::init(true) , cl::Hidden) static
EnableCollectLOH
cl::opt< bool > EnableCollectLOH("aarch64-collect-loh", cl::desc("Enable the pass that emits the" " linker optimization hints (LOH)"), cl::init(true), cl::Hidden) ("aarch64-collect-loh" , cl::desc("Enable the pass that emits the" " linker optimization hints (LOH)") , cl::init(true) , cl::Hidden) static
EnableCondOpt
cl::opt< bool > EnableCondOpt("aarch64-condopt", cl::desc("Enable the condition optimizer pass"), cl::init(true), cl::Hidden) ("aarch64-condopt" , cl::desc("Enable the condition optimizer pass") , cl::init(true) , cl::Hidden) static
EnableDeadRegisterElimination
cl::opt< bool > EnableDeadRegisterElimination("aarch64-dead-def-elimination", cl::Hidden, cl::desc("Enable the pass that removes dead" " definitons and replaces stores to" " them with stores to the zero" " register"), cl::init(true)) ("aarch64-dead-def-elimination" , cl::Hidden , cl::desc("Enable the pass that removes dead" " definitons and replaces stores to" " them with stores to the zero" " register") , cl::init(true)) static
EnableEarlyIfConversion
cl::opt< bool > EnableEarlyIfConversion("aarch64-enable-early-ifcvt", cl::Hidden, cl::desc("Run early if-conversion"), cl::init(true)) ("aarch64-enable-early-ifcvt" , cl::Hidden , cl::desc("Run early if-conversion") , cl::init(true)) static
EnableGEPOpt
cl::opt< bool > EnableGEPOpt("aarch64-gep-opt", cl::Hidden, cl::desc("Enable optimizations on complex GEPs"), cl::init(true)) ("aarch64-gep-opt" , cl::Hidden , cl::desc("Enable optimizations on complex GEPs") , cl::init(true)) static
EnableLoadStoreOpt
cl::opt< bool > EnableLoadStoreOpt("aarch64-load-store-opt", cl::desc("Enable the load/store pair" " optimization pass"), cl::init(true), cl::Hidden) ("aarch64-load-store-opt" , cl::desc("Enable the load/store pair" " optimization pass") , cl::init(true) , cl::Hidden) static
EnableMCR
cl::opt< bool > EnableMCR("aarch64-mcr", cl::desc("Enable the machine combiner pass"), cl::init(true), cl::Hidden) ("aarch64-mcr" , cl::desc("Enable the machine combiner pass") , cl::init(true) , cl::Hidden) static
EnablePromoteConstant
cl::opt< bool > EnablePromoteConstant("aarch64-promote-const", cl::desc("Enable the promote " "constant pass"), cl::init(true), cl::Hidden) ("aarch64-promote-const" , cl::desc("Enable the promote " "constant pass") , cl::init(true) , cl::Hidden) static
EnableStPairSuppress
cl::opt< bool > EnableStPairSuppress("aarch64-stp-suppress", cl::desc("Suppress STP for AArch64"), cl::init(true), cl::Hidden) ("aarch64-stp-suppress" , cl::desc("Suppress STP for AArch64") , cl::init(true) , cl::Hidden) static