LLVM: AMDGPUISelLowering.cpp File Reference
LLVM API Documentation
AMDGPUISelLowering.cpp File Reference
This is the parent TargetLowering class for hardware code gen targets.
#include "AMDGPUISelLowering.h"
#include "AMDGPU.h"
#include "AMDGPUFrameLowering.h"
#include "AMDGPUIntrinsicInfo.h"
#include "AMDGPURegisterInfo.h"
#include "AMDGPUSubtarget.h"
#include "R600MachineFunctionInfo.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "AMDGPUGenCallingConv.inc"
Macros
#define NODE_NAME_CASE(node)
Functions
static bool allocateStack (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState &State)
static bool hasDefinedInitializer (const GlobalValue *GV)
static bool isU24 (SDValue Op, SelectionDAG &DAG)
static bool isI24 (SDValue Op, SelectionDAG &DAG)
static void simplifyI24 (SDValue Op, TargetLowering::DAGCombinerInfo &DCI)
template<typename IntTy>
static SDValue constantFoldBFE (SelectionDAG &DAG, IntTy Src0, uint32_t Offset, uint32_t Width)
static bool usesAllNormalStores (SDNode *LoadVal)
static void computeKnownBitsForMinMax (const SDValue Op0, const SDValue Op1, APInt &KnownZero, APInt &KnownOne, const SelectionDAG &DAG, unsigned Depth)
Detailed Description
This is the parent TargetLowering class for hardware code gen targets.
Definition in file AMDGPUISelLowering.cpp.
Macro Definition Documentation
NODE_NAME_CASE
#define NODE_NAME_CASE (node)
Value:
case AMDGPUISD::node: return #node;
Definition at line 2476 of file AMDGPUISelLowering.cpp.
Referenced by llvm::AMDGPUTargetLowering::getTargetNodeName().
Function Documentation
allocateStack()
bool allocateStack (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState & State) static
Definition at line 74 of file AMDGPUISelLowering.cpp.
References llvm::CCState::addLoc(), llvm::CCState::AllocateStack(), llvm::CCValAssign::getMem(), llvm::ISD::ArgFlagsTy::getOrigAlign(), and llvm::MVT::getStoreSize().
computeKnownBitsForMinMax()
void computeKnownBitsForMinMax (const SDValue Op0, const SDValue Op1, APInt & KnownZero, APInt & KnownOne, const SelectionDAG & DAG, unsigned Depth) static
Definition at line 2586 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::computeKnownBits().
Referenced by llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode().
constantFoldBFE()
template<typename IntTy> SDValue constantFoldBFE (SelectionDAG & DAG, IntTy Src0, uint32_t Offset, uint32_t Width) static
Definition at line 2182 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), and llvm::MVT::i32.
Referenced by llvm::AMDGPUTargetLowering::PerformDAGCombine().
hasDefinedInitializer()
bool hasDefinedInitializer (const GlobalValue * GV) static
Definition at line 736 of file AMDGPUISelLowering.cpp.
References llvm::dyn_cast(), llvm::GlobalVariable::getInitializer(), llvm::GlobalVariable::hasInitializer(), and llvm::isa().
Referenced by llvm::AMDGPUTargetLowering::LowerGlobalAddress().
isI24()
bool isI24 (SDValue Op, SelectionDAG & DAG) static
Definition at line 2158 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::ComputeNumSignBits(), llvm::EVT::getSizeInBits(), and llvm::SDValue::getValueType().
isU24()
bool isU24 (SDValue Op, SelectionDAG & DAG) static
Definition at line 2150 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::computeKnownBits(), llvm::APInt::countLeadingOnes(), llvm::EVT::getSizeInBits(), and llvm::SDValue::getValueType().
simplifyI24()
void simplifyI24 (SDValue Op, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 2168 of file AMDGPUISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::CommitTargetLoweringOpt(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::APInt::getLowBitsSet(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), and llvm::TargetLowering::SimplifyDemandedBits().
Referenced by llvm::AMDGPUTargetLowering::PerformDAGCombine().
usesAllNormalStores()
bool usesAllNormalStores (SDNode * LoadVal) static
Definition at line 2193 of file AMDGPUISelLowering.cpp.
References I, llvm::ISD::isNormalStore(), and llvm::SDNode::use_begin().