LLVM: ARMMCTargetDesc.cpp File Reference
LLVM API Documentation
ARMMCTargetDesc.cpp File Reference
#include "ARMBaseInfo.h"
#include "ARMMCAsmInfo.h"
#include "ARMMCTargetDesc.h"
#include "InstPrinter/ARMInstPrinter.h"
#include "llvm/ADT/Triple.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "ARMGenRegisterInfo.inc"
#include "ARMGenInstrInfo.inc"
#include "ARMGenSubtargetInfo.inc"
Macros
#define GET_REGINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Functions
static bool getMCRDeprecationInfo (MCInst &MI, MCSubtargetInfo &STI, std::string &Info)
static bool getITDeprecationInfo (MCInst &MI, MCSubtargetInfo &STI, std::string &Info)
static bool getARMStoreDeprecationInfo (MCInst &MI, MCSubtargetInfo &STI, std::string &Info)
static bool getARMLoadDeprecationInfo (MCInst &MI, MCSubtargetInfo &STI, std::string &Info)
static MCInstrInfo * createARMMCInstrInfo ()
static MCRegisterInfo * createARMMCRegisterInfo (StringRef Triple)
static MCAsmInfo * createARMMCAsmInfo (const MCRegisterInfo &MRI, StringRef TT)
static MCCodeGenInfo * createARMMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCStreamer * createMCStreamer (const Target &T, StringRef TT, MCContext &Ctx, MCAsmBackend &MAB, raw_ostream &OS, MCCodeEmitter *Emitter, const MCSubtargetInfo &STI, bool RelaxAll)
static MCInstPrinter * createARMMCInstPrinter (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
static MCRelocationInfo * createARMMCRelocationInfo (StringRef TT, MCContext &Ctx)
static MCInstrAnalysis * createARMMCInstrAnalysis (const MCInstrInfo *Info)
void LLVMInitializeARMTargetMC ()
Macro Definition Documentation
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 127 of file ARMMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 31 of file ARMMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 130 of file ARMMCTargetDesc.cpp.
Function Documentation
createARMMCAsmInfo()
MCAsmInfo * createARMMCAsmInfo (const MCRegisterInfo & MRI, StringRef TT) static
Definition at line 266 of file ARMMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::createDefCfa(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSDarwin(), llvm::Triple::isWindowsItaniumEnvironment(), and llvm::Triple::isWindowsMSVCEnvironment().
Referenced by LLVMInitializeARMTargetMC().
createARMMCCodeGenInfo()
MCCodeGenInfo * createARMMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 285 of file ARMMCTargetDesc.cpp.
References llvm::Reloc::Default, llvm::Reloc::DynamicNoPIC, llvm::Triple::isOSDarwin(), llvm::Reloc::PIC_, and llvm::X.
Referenced by LLVMInitializeARMTargetMC().
createARMMCInstPrinter()
MCInstPrinter * createARMMCInstPrinter (const Target & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) static
Definition at line 321 of file ARMMCTargetDesc.cpp.
References T.
Referenced by LLVMInitializeARMTargetMC().
createARMMCInstrAnalysis()
MCInstrAnalysis * createARMMCInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 376 of file ARMMCTargetDesc.cpp.
Referenced by LLVMInitializeARMTargetMC().
createARMMCInstrInfo()
MCInstrInfo * createARMMCInstrInfo () static
Definition at line 254 of file ARMMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeARMTargetMC().
createARMMCRegisterInfo()
MCRegisterInfo * createARMMCRegisterInfo (StringRef Triple) static
Definition at line 260 of file ARMMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeARMTargetMC().
createARMMCRelocationInfo()
MCRelocationInfo * createARMMCRelocationInfo (StringRef TT, MCContext & Ctx) static
Definition at line 332 of file ARMMCTargetDesc.cpp.
References llvm::createARMMachORelocationInfo(), llvm::createMCRelocationInfo(), and llvm::Triple::isOSBinFormatMachO().
Referenced by LLVMInitializeARMTargetMC().
createMCStreamer()
MCStreamer * createMCStreamer (const Target & T, StringRef TT, MCContext & Ctx, MCAsmBackend & MAB, raw_ostream & OS, MCCodeEmitter * Emitter, const MCSubtargetInfo & STI, bool RelaxAll) static
Definition at line 299 of file ARMMCTargetDesc.cpp.
References llvm::Triple::COFF, llvm::createARMELFStreamer(), llvm::createARMWinCOFFStreamer(), llvm::createMachOStreamer(), llvm::Triple::ELF, llvm::Triple::getArch(), llvm::Triple::getObjectFormat(), llvm::Triple::isOSWindows(), llvm_unreachable, llvm::Triple::MachO, RelaxAll(), T, and llvm::Triple::thumb.
getARMLoadDeprecationInfo()
bool getARMLoadDeprecationInfo (MCInst & MI, MCSubtargetInfo & STI, std::string & Info) static
Definition at line 95 of file ARMMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
getARMStoreDeprecationInfo()
bool getARMStoreDeprecationInfo (MCInst & MI, MCSubtargetInfo & STI, std::string & Info) static
Definition at line 78 of file ARMMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
getITDeprecationInfo()
bool getITDeprecationInfo (MCInst & MI, MCSubtargetInfo & STI, std::string & Info) static
Definition at line 66 of file ARMMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
getMCRDeprecationInfo()
bool getMCRDeprecationInfo (MCInst & MI, MCSubtargetInfo & STI, std::string & Info) static
Definition at line 34 of file ARMMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getFeatureBits().
LLVMInitializeARMTargetMC()
void LLVMInitializeARMTargetMC ()
Definition at line 381 of file ARMMCTargetDesc.cpp.
References llvm::createARMBEAsmBackend(), llvm::createARMBEMCCodeEmitter(), llvm::createARMLEAsmBackend(), llvm::createARMLEMCCodeEmitter(), createARMMCAsmInfo(), createARMMCCodeGenInfo(), createARMMCInstPrinter(), createARMMCInstrAnalysis(), createARMMCInstrInfo(), createARMMCRegisterInfo(), createARMMCRelocationInfo(), llvm::ARM_MC::createARMMCSubtargetInfo(), llvm::createARMNullStreamer(), llvm::createMCAsmStreamer(), createMCStreamer(), llvm::createThumbBEAsmBackend(), llvm::createThumbLEAsmBackend(), llvm::TargetRegistry::RegisterAsmStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCCodeGenInfo(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCObjectStreamer(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCRelocationInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullStreamer(), llvm::TheARMBETarget, llvm::TheARMLETarget, llvm::TheThumbBETarget, llvm::TheThumbLETarget, llvm::X, and Y.