LLVM: ARMSubtarget.cpp File Reference
LLVM API Documentation
ARMSubtarget.cpp File Reference
#include "ARMSubtarget.h"
#include "ARMFrameLowering.h"
#include "ARMISelLowering.h"
#include "ARMInstrInfo.h"
#include "ARMMachineFunctionInfo.h"
#include "ARMSelectionDAGInfo.h"
#include "ARMTargetMachine.h"
#include "Thumb1FrameLowering.h"
#include "Thumb1InstrInfo.h"
#include "Thumb2InstrInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "ARMGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "arm-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Enumerations
enum ITMode { DefaultIT , RestrictedIT , NoRestrictedIT }
Functions
static std::string computeDataLayout (ARMSubtarget &ST)
Variables
static cl::opt< bool > ReserveR9 ("arm-reserve-r9", cl::Hidden, cl::desc("Reserve R9, making it unavailable as GPR"))
static cl::opt< bool > ArmUseMOVT ("arm-use-movt", cl::init(true), cl::Hidden)
static cl::opt< bool > UseFusedMulOps ("arm-use-mulops", cl::init(true), cl::Hidden)
static cl::opt< AlignMode > Align (cl::desc("Load/store alignment support"), cl::Hidden, cl::init(DefaultAlign), cl::values(clEnumValN(DefaultAlign, "arm-default-align", "Generate unaligned accesses only on hardware/OS " "combinations that are known to support them"), clEnumValN(StrictAlign, "arm-strict-align", "Disallow all unaligned memory accesses"), clEnumValN(NoStrictAlign, "arm-no-strict-align", "Allow unaligned memory accesses"), clEnumValEnd))
static cl::opt< ITMode > IT (cl::desc("IT block support"), cl::Hidden, cl::init(DefaultIT), cl::ZeroOrMore, cl::values(clEnumValN(DefaultIT, "arm-default-it", "Generate IT block based on arch"), clEnumValN(RestrictedIT, "arm-restrict-it", "Disallow deprecated IT based on ARMv8"), clEnumValN(NoRestrictedIT, "arm-no-restrict-it", "Allow IT blocks based on ARMv7"), clEnumValEnd))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arm-subtarget"
Definition at line 36 of file ARMSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 39 of file ARMSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 38 of file ARMSubtarget.cpp.
Enumeration Type Documentation
ITMode
enum ITMode
Enumerator
DefaultIT
RestrictedIT
NoRestrictedIT
Definition at line 74 of file ARMSubtarget.cpp.
Function Documentation
computeDataLayout()
std::string computeDataLayout (ARMSubtarget & ST) static
Definition at line 91 of file ARMSubtarget.cpp.
References llvm::DataLayout::getManglingComponent().
Referenced by llvm::AMDGPUSubtarget::AMDGPUSubtarget(), llvm::ARMSubtarget::ARMSubtarget(), llvm::MipsSubtarget::MipsSubtarget(), llvm::NVPTXSubtarget::NVPTXSubtarget(), llvm::SparcSubtarget::SparcSubtarget(), and llvm::X86Subtarget::X86Subtarget().
Variable Documentation
Align
cl::opt< AlignMode > Align(cl::desc("Load/store alignment support"), cl::Hidden, cl::init(DefaultAlign), cl::values(clEnumValN(DefaultAlign, "arm-default-align", "Generate unaligned accesses only on hardware/OS " "combinations that are known to support them"), clEnumValN(StrictAlign, "arm-strict-align", "Disallow all unaligned memory accesses"), clEnumValN(NoStrictAlign, "arm-no-strict-align", "Allow unaligned memory accesses"), clEnumValEnd)) (cl::desc("Load/store alignment support") , cl::Hidden , cl::init(DefaultAlign) , cl::values(clEnumValN(DefaultAlign, "arm-default-align", "Generate unaligned accesses only on hardware/OS " "combinations that are known to support them"), clEnumValN(StrictAlign, "arm-strict-align", "Disallow all unaligned memory accesses"), clEnumValN(NoStrictAlign, "arm-no-strict-align", "Allow unaligned memory accesses"), clEnumValEnd)) static
ArmUseMOVT
cl::opt< bool > ArmUseMOVT("arm-use-movt", cl::init(true), cl::Hidden) ("arm-use-movt" , cl::init(true) , cl::Hidden) static
IT
cl::opt< ITMode > IT(cl::desc("IT block support"), cl::Hidden, cl::init(DefaultIT), cl::ZeroOrMore, cl::values(clEnumValN(DefaultIT, "arm-default-it", "Generate IT block based on arch"), clEnumValN(RestrictedIT, "arm-restrict-it", "Disallow deprecated IT based on ARMv8"), clEnumValN(NoRestrictedIT, "arm-no-restrict-it", "Allow IT blocks based on ARMv7"), clEnumValEnd)) (cl::desc("IT block support") , cl::Hidden , cl::init(DefaultIT) , cl::ZeroOrMore , cl::values(clEnumValN(DefaultIT, "arm-default-it", "Generate IT block based on arch"), clEnumValN(RestrictedIT, "arm-restrict-it", "Disallow deprecated IT based on ARMv8"), clEnumValN(NoRestrictedIT, "arm-no-restrict-it", "Allow IT blocks based on ARMv7"), clEnumValEnd)) static
Referenced by FindInitTrampoline(), FoldBitCast(), llvm::MachineBasicBlock::insert(), llvm::ConstantDataSequential::isElementTypeCompatible(), LLVMGetTargetFromName(), llvm::size_type< NodeTy >::remove(), llvm::size_type< NodeTy >::remove(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitCallInst(), and llvm::OptionRegistry::~OptionRegistry().
ReserveR9
cl::opt< bool > ReserveR9("arm-reserve-r9", cl::Hidden, cl::desc("Reserve R9, making it unavailable as GPR")) ("arm-reserve-r9" , cl::Hidden , cl::desc("Reserve R9, making it unavailable as GPR")) static
UseFusedMulOps
cl::opt< bool > UseFusedMulOps("arm-use-mulops", cl::init(true), cl::Hidden) ("arm-use-mulops" , cl::init(true) , cl::Hidden) static