LLVM: BBVectorize.cpp File Reference
LLVM API Documentation
BBVectorize.cpp File Reference
#include "llvm/Transforms/Vectorize.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AliasSetTracker.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
Macros
#define BBV_NAME "bb-vectorize"
#define DEBUG_TYPE BBV_NAME
Functions
STATISTIC (NumFusedOps, "Number of operations fused by bb-vectorize")
Variables
static cl::opt< bool > IgnoreTargetInfo ("bb-vectorize-ignore-target-info", cl::init(false), cl::Hidden, cl::desc("Ignore target information"))
static cl::opt< unsigned > ReqChainDepth ("bb-vectorize-req-chain-depth", cl::init(6), cl::Hidden, cl::desc("The required chain depth for vectorization"))
static cl::opt< bool > UseChainDepthWithTI ("bb-vectorize-use-chain-depth", cl::init(false), cl::Hidden, cl::desc("Use the chain depth requirement with" " target information"))
static cl::opt< unsigned > SearchLimit ("bb-vectorize-search-limit", cl::init(400), cl::Hidden, cl::desc("The maximum search distance for instruction pairs"))
static cl::opt< bool > SplatBreaksChain ("bb-vectorize-splat-breaks-chain", cl::init(false), cl::Hidden, cl::desc("Replicating one element to a pair breaks the chain"))
static cl::opt< unsigned > VectorBits ("bb-vectorize-vector-bits", cl::init(128), cl::Hidden, cl::desc("The size of the native vector registers"))
static cl::opt< unsigned > MaxIter ("bb-vectorize-max-iter", cl::init(0), cl::Hidden, cl::desc("The maximum number of pairing iterations"))
static cl::opt< bool > Pow2LenOnly ("bb-vectorize-pow2-len-only", cl::init(false), cl::Hidden, cl::desc("Don't try to form non-2^n-length vectors"))
static cl::opt< unsigned > MaxInsts ("bb-vectorize-max-instr-per-group", cl::init(500), cl::Hidden, cl::desc("The maximum number of pairable instructions per group"))
static cl::opt< unsigned > MaxPairs ("bb-vectorize-max-pairs-per-group", cl::init(3000), cl::Hidden, cl::desc("The maximum number of candidate instruction pairs per group"))
static cl::opt< unsigned > MaxCandPairsForCycleCheck ("bb-vectorize-max-cycle-check-pairs", cl::init(200), cl::Hidden, cl::desc("The maximum number of candidate pairs with which to use" " a full cycle check"))
static cl::opt< bool > NoBools ("bb-vectorize-no-bools", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize boolean (i1) values"))
static cl::opt< bool > NoInts ("bb-vectorize-no-ints", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize integer values"))
static cl::opt< bool > NoFloats ("bb-vectorize-no-floats", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize floating-point values"))
static cl::opt< bool > NoPointers ("bb-vectorize-no-pointers", cl::init(true), cl::Hidden, cl::desc("Don't try to vectorize pointer values"))
static cl::opt< bool > NoCasts ("bb-vectorize-no-casts", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize casting (conversion) operations"))
static cl::opt< bool > NoMath ("bb-vectorize-no-math", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize floating-point math intrinsics"))
static cl::opt< bool > NoBitManipulation ("bb-vectorize-no-bitmanip", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize BitManipulation intrinsics"))
static cl::opt< bool > NoFMA ("bb-vectorize-no-fma", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize the fused-multiply-add intrinsic"))
static cl::opt< bool > NoSelect ("bb-vectorize-no-select", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize select instructions"))
static cl::opt< bool > NoCmp ("bb-vectorize-no-cmp", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize comparison instructions"))
static cl::opt< bool > NoGEP ("bb-vectorize-no-gep", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize getelementptr instructions"))
static cl::opt< bool > NoMemOps ("bb-vectorize-no-mem-ops", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize loads and stores"))
static cl::opt< bool > AlignedOnly ("bb-vectorize-aligned-only", cl::init(false), cl::Hidden, cl::desc("Only generate aligned loads and stores"))
static cl::opt< bool > NoMemOpBoost ("bb-vectorize-no-mem-op-boost", cl::init(false), cl::Hidden, cl::desc("Don't boost the chain-depth contribution of loads and stores"))
static cl::opt< bool > FastDep ("bb-vectorize-fast-dep", cl::init(false), cl::Hidden, cl::desc("Use a fast instruction dependency analysis"))
static cl::opt< bool > DebugInstructionExamination ("bb-vectorize-debug-instruction-examination", cl::init(false), cl::Hidden, cl::desc("When debugging is enabled, output information on the" " instruction-examination process"))
static cl::opt< bool > DebugCandidateSelection ("bb-vectorize-debug-candidate-selection", cl::init(false), cl::Hidden, cl::desc("When debugging is enabled, output information on the" " candidate-selection process"))
static cl::opt< bool > DebugPairSelection ("bb-vectorize-debug-pair-selection", cl::init(false), cl::Hidden, cl::desc("When debugging is enabled, output information on the" " pair-selection process"))
static cl::opt< bool > DebugCycleCheck ("bb-vectorize-debug-cycle-check", cl::init(false), cl::Hidden, cl::desc("When debugging is enabled, output information on the" " cycle-checking process"))
static cl::opt< bool > PrintAfterEveryPair ("bb-vectorize-debug-print-after-every-pair", cl::init(false), cl::Hidden, cl::desc("When debugging is enabled, dump the basic block after" " every pair is fused"))
static const char bb_vectorize_name [] = "Basic-Block Vectorization"
Macro Definition Documentation
BBV_NAME
#define BBV_NAME "bb-vectorize"
Definition at line 17 of file BBVectorize.cpp.
DEBUG_TYPE
#define DEBUG_TYPE BBV_NAME
Definition at line 52 of file BBVectorize.cpp.
Function Documentation
STATISTIC()
STATISTIC (NumFusedOps , "Number of operations fused by bb-vectorize")
References llvm::PassRegistry::getPassRegistry().
Variable Documentation
AlignedOnly
cl::opt< bool > AlignedOnly("bb-vectorize-aligned-only", cl::init(false), cl::Hidden, cl::desc("Only generate aligned loads and stores")) ("bb-vectorize-aligned-only" , cl::init(false) , cl::Hidden , cl::desc("Only generate aligned loads and stores")) static
bb_vectorize_name
const char bb_vectorize_name[] = "Basic-Block Vectorization" static
Definition at line 3192 of file BBVectorize.cpp.
DebugCandidateSelection
cl::opt< bool > DebugCandidateSelection("bb-vectorize-debug-candidate-selection", cl::init(false), cl::Hidden, cl::desc("When debugging is enabled, output information on the" " candidate-selection process")) ("bb-vectorize-debug-candidate-selection" , cl::init(false) , cl::Hidden , cl::desc("When debugging is enabled, output information on the" " candidate-selection process")) static
DebugCycleCheck
cl::opt< bool > DebugCycleCheck("bb-vectorize-debug-cycle-check", cl::init(false), cl::Hidden, cl::desc("When debugging is enabled, output information on the" " cycle-checking process")) ("bb-vectorize-debug-cycle-check" , cl::init(false) , cl::Hidden , cl::desc("When debugging is enabled, output information on the" " cycle-checking process")) static
DebugInstructionExamination
cl::opt< bool > DebugInstructionExamination("bb-vectorize-debug-instruction-examination", cl::init(false), cl::Hidden, cl::desc("When debugging is enabled, output information on the" " instruction-examination process")) ("bb-vectorize-debug-instruction-examination" , cl::init(false) , cl::Hidden , cl::desc("When debugging is enabled, output information on the" " instruction-examination process")) static
DebugPairSelection
cl::opt< bool > DebugPairSelection("bb-vectorize-debug-pair-selection", cl::init(false), cl::Hidden, cl::desc("When debugging is enabled, output information on the" " pair-selection process")) ("bb-vectorize-debug-pair-selection" , cl::init(false) , cl::Hidden , cl::desc("When debugging is enabled, output information on the" " pair-selection process")) static
FastDep
cl::opt< bool > FastDep("bb-vectorize-fast-dep", cl::init(false), cl::Hidden, cl::desc("Use a fast instruction dependency analysis")) ("bb-vectorize-fast-dep" , cl::init(false) , cl::Hidden , cl::desc("Use a fast instruction dependency analysis")) static
IgnoreTargetInfo
cl::opt< bool > IgnoreTargetInfo("bb-vectorize-ignore-target-info", cl::init(false), cl::Hidden, cl::desc("Ignore target information")) ("bb-vectorize-ignore-target-info" , cl::init(false) , cl::Hidden , cl::desc("Ignore target information")) static
MaxCandPairsForCycleCheck
cl::opt< unsigned > MaxCandPairsForCycleCheck("bb-vectorize-max-cycle-check-pairs", cl::init(200), cl::Hidden, cl::desc("The maximum number of candidate pairs with which to use" " a full cycle check")) ("bb-vectorize-max-cycle-check-pairs" , cl::init(200) , cl::Hidden , cl::desc("The maximum number of candidate pairs with which to use" " a full cycle check")) static
MaxInsts
cl::opt< unsigned > MaxInsts("bb-vectorize-max-instr-per-group", cl::init(500), cl::Hidden, cl::desc("The maximum number of pairable instructions per group")) ("bb-vectorize-max-instr-per-group" , cl::init(500) , cl::Hidden , cl::desc("The maximum number of pairable instructions per group")) static
MaxIter
cl::opt< unsigned > MaxIter("bb-vectorize-max-iter", cl::init(0), cl::Hidden, cl::desc("The maximum number of pairing iterations")) ("bb-vectorize-max-iter" , cl::init(0) , cl::Hidden , cl::desc("The maximum number of pairing iterations")) static
MaxPairs
cl::opt< unsigned > MaxPairs("bb-vectorize-max-pairs-per-group", cl::init(3000), cl::Hidden, cl::desc("The maximum number of candidate instruction pairs per group")) ("bb-vectorize-max-pairs-per-group" , cl::init(3000) , cl::Hidden , cl::desc("The maximum number of candidate instruction pairs per group")) static
NoBitManipulation
cl::opt< bool > NoBitManipulation("bb-vectorize-no-bitmanip", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize BitManipulation intrinsics")) ("bb-vectorize-no-bitmanip" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize BitManipulation intrinsics")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoBools
cl::opt< bool > NoBools("bb-vectorize-no-bools", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize boolean (i1) values")) ("bb-vectorize-no-bools" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize boolean (i1) values")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoCasts
cl::opt< bool > NoCasts("bb-vectorize-no-casts", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize casting (conversion) operations")) ("bb-vectorize-no-casts" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize casting (conversion) operations")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoCmp
cl::opt< bool > NoCmp("bb-vectorize-no-cmp", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize comparison instructions")) ("bb-vectorize-no-cmp" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize comparison instructions")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoFloats
cl::opt< bool > NoFloats("bb-vectorize-no-floats", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize floating-point values")) ("bb-vectorize-no-floats" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize floating-point values")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoFMA
cl::opt< bool > NoFMA("bb-vectorize-no-fma", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize the fused-multiply-add intrinsic")) ("bb-vectorize-no-fma" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize the fused-multiply-add intrinsic")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoGEP
cl::opt< bool > NoGEP("bb-vectorize-no-gep", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize getelementptr instructions")) ("bb-vectorize-no-gep" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize getelementptr instructions")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoInts
cl::opt< bool > NoInts("bb-vectorize-no-ints", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize integer values")) ("bb-vectorize-no-ints" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize integer values")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoMath
cl::opt< bool > NoMath("bb-vectorize-no-math", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize floating-point math intrinsics")) ("bb-vectorize-no-math" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize floating-point math intrinsics")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoMemOpBoost
cl::opt< bool > NoMemOpBoost("bb-vectorize-no-mem-op-boost", cl::init(false), cl::Hidden, cl::desc("Don't boost the chain-depth contribution of loads and stores")) ("bb-vectorize-no-mem-op-boost" , cl::init(false) , cl::Hidden , cl::desc("Don't boost the chain-depth contribution of loads and stores")) static
NoMemOps
cl::opt< bool > NoMemOps("bb-vectorize-no-mem-ops", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize loads and stores")) ("bb-vectorize-no-mem-ops" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize loads and stores")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoPointers
cl::opt< bool > NoPointers("bb-vectorize-no-pointers", cl::init(true), cl::Hidden, cl::desc("Don't try to vectorize pointer values")) ("bb-vectorize-no-pointers" , cl::init(true) , cl::Hidden , cl::desc("Don't try to vectorize pointer values")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
NoSelect
cl::opt< bool > NoSelect("bb-vectorize-no-select", cl::init(false), cl::Hidden, cl::desc("Don't try to vectorize select instructions")) ("bb-vectorize-no-select" , cl::init(false) , cl::Hidden , cl::desc("Don't try to vectorize select instructions")) static
Referenced by llvm::VectorizeConfig::VectorizeConfig().
Pow2LenOnly
cl::opt< bool > Pow2LenOnly("bb-vectorize-pow2-len-only", cl::init(false), cl::Hidden, cl::desc("Don't try to form non-2^n-length vectors")) ("bb-vectorize-pow2-len-only" , cl::init(false) , cl::Hidden , cl::desc("Don't try to form non-2^n-length vectors")) static
PrintAfterEveryPair
cl::opt< bool > PrintAfterEveryPair("bb-vectorize-debug-print-after-every-pair", cl::init(false), cl::Hidden, cl::desc("When debugging is enabled, dump the basic block after" " every pair is fused")) ("bb-vectorize-debug-print-after-every-pair" , cl::init(false) , cl::Hidden , cl::desc("When debugging is enabled, dump the basic block after" " every pair is fused")) static
ReqChainDepth
cl::opt< unsigned > ReqChainDepth("bb-vectorize-req-chain-depth", cl::init(6), cl::Hidden, cl::desc("The required chain depth for vectorization")) ("bb-vectorize-req-chain-depth" , cl::init(6) , cl::Hidden , cl::desc("The required chain depth for vectorization")) static
SearchLimit
cl::opt< unsigned > SearchLimit("bb-vectorize-search-limit", cl::init(400), cl::Hidden, cl::desc("The maximum search distance for instruction pairs")) ("bb-vectorize-search-limit" , cl::init(400) , cl::Hidden , cl::desc("The maximum search distance for instruction pairs")) static
SplatBreaksChain
cl::opt< bool > SplatBreaksChain("bb-vectorize-splat-breaks-chain", cl::init(false), cl::Hidden, cl::desc("Replicating one element to a pair breaks the chain")) ("bb-vectorize-splat-breaks-chain" , cl::init(false) , cl::Hidden , cl::desc("Replicating one element to a pair breaks the chain")) static
UseChainDepthWithTI
cl::opt< bool > UseChainDepthWithTI("bb-vectorize-use-chain-depth", cl::init(false), cl::Hidden, cl::desc("Use the chain depth requirement with" " target information")) ("bb-vectorize-use-chain-depth" , cl::init(false) , cl::Hidden , cl::desc("Use the chain depth requirement with" " target information")) static
VectorBits
cl::opt< unsigned > VectorBits("bb-vectorize-vector-bits", cl::init(128), cl::Hidden, cl::desc("The size of the native vector registers")) ("bb-vectorize-vector-bits" , cl::init(128) , cl::Hidden , cl::desc("The size of the native vector registers")) static