LLVM: BitstreamReader.cpp File Reference
LLVM API Documentation
BitstreamReader.cpp File Reference
#include "llvm/Bitcode/BitstreamReader.h"
Functions
static uint64_t readAbbreviatedField (BitstreamCursor &Cursor, const BitCodeAbbrevOp &Op)
static void skipAbbreviatedField (BitstreamCursor &Cursor, const BitCodeAbbrevOp &Op)
Function Documentation
readAbbreviatedField()
uint64_t readAbbreviatedField (BitstreamCursor & Cursor, const BitCodeAbbrevOp & Op) static
Definition at line 53 of file BitstreamReader.cpp.
References llvm::BitCodeAbbrevOp::Array, llvm::BitCodeAbbrevOp::Blob, llvm::BitCodeAbbrevOp::Char6, llvm::BitCodeAbbrevOp::DecodeChar6(), llvm::BitCodeAbbrevOp::Fixed, llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrevOp::getEncodingData(), llvm::BitCodeAbbrevOp::isLiteral(), llvm_unreachable, llvm::BitstreamCursor::Read(), llvm::BitstreamCursor::ReadVBR64(), and llvm::BitCodeAbbrevOp::VBR.
Referenced by llvm::BitstreamCursor::readRecord().
skipAbbreviatedField()
void skipAbbreviatedField (BitstreamCursor & Cursor, const BitCodeAbbrevOp & Op) static
Definition at line 72 of file BitstreamReader.cpp.
References llvm::BitCodeAbbrevOp::Array, llvm::BitCodeAbbrevOp::Blob, llvm::BitCodeAbbrevOp::Char6, llvm::BitCodeAbbrevOp::Fixed, llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrevOp::getEncodingData(), llvm::BitCodeAbbrevOp::isLiteral(), llvm_unreachable, llvm::BitstreamCursor::Read(), llvm::BitstreamCursor::ReadVBR64(), and llvm::BitCodeAbbrevOp::VBR.
Referenced by llvm::BitstreamCursor::skipRecord().