LLVM: BranchFolding.cpp File Reference
LLVM API Documentation
BranchFolding.cpp File Reference
#include "BranchFolding.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineBranchProbabilityInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "branchfolding"
Functions
STATISTIC (NumDeadBlocks, "Number of dead blocks removed")
STATISTIC (NumBranchOpts, "Number of branches optimized")
STATISTIC (NumTailMerge, "Number of block tails merged")
STATISTIC (NumHoist, "Number of times common instructions are hoisted")
INITIALIZE_PASS (BranchFolderPass, "branch-folder", "Control Flow Optimizer", false, false) bool BranchFolderPass
static unsigned HashMachineInstr (const MachineInstr *MI)
HashMachineInstr - Compute a hash value for MI and its operands.
static unsigned HashEndOfMBB (const MachineBasicBlock *MBB)
HashEndOfMBB - Hash the last instruction in the MBB.
static unsigned ComputeCommonTailLength (MachineBasicBlock *MBB1, MachineBasicBlock *MBB2, MachineBasicBlock::iterator &I1, MachineBasicBlock::iterator &I2)
static unsigned EstimateRuntime (MachineBasicBlock::iterator I, MachineBasicBlock::iterator E)
static void FixTail (MachineBasicBlock *CurMBB, MachineBasicBlock *SuccBB, const TargetInstrInfo *TII)
static unsigned CountTerminators (MachineBasicBlock *MBB, MachineBasicBlock::iterator &I)
static bool ProfitableToMerge (MachineBasicBlock *MBB1, MachineBasicBlock *MBB2, unsigned minCommonTailLength, unsigned &CommonTailLen, MachineBasicBlock::iterator &I1, MachineBasicBlock::iterator &I2, MachineBasicBlock *SuccBB, MachineBasicBlock *PredBB)
static bool IsEmptyBlock (MachineBasicBlock *MBB)
static bool IsBranchOnlyBlock (MachineBasicBlock *MBB)
static bool IsBetterFallthrough (MachineBasicBlock *MBB1, MachineBasicBlock *MBB2)
static DebugLoc getBranchDebugLoc (MachineBasicBlock &MBB)
static MachineBasicBlock * findFalseBlock (MachineBasicBlock *BB, MachineBasicBlock *TrueBB)
static MachineBasicBlock::iterator findHoistingInsertPosAndDeps (MachineBasicBlock *MBB, const TargetInstrInfo *TII, const TargetRegisterInfo *TRI, SmallSet< unsigned, 4 > &Uses, SmallSet< unsigned, 4 > &Defs)
Variables
static cl::opt< cl::boolOrDefault > FlagEnableTailMerge ("enable-tail-merge", cl::init(cl::BOU_UNSET), cl::Hidden)
static cl::opt< unsigned > TailMergeThreshold ("tail-merge-threshold", cl::desc("Max number of predecessors to consider tail merging"), cl::init(150), cl::Hidden)
static cl::opt< unsigned > TailMergeSize ("tail-merge-size", cl::desc("Min number of instructions to consider tail merging"), cl::init(3), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "branchfolding"
Definition at line 42 of file BranchFolding.cpp.
Function Documentation
ComputeCommonTailLength()
unsigned ComputeCommonTailLength (MachineBasicBlock * MBB1, MachineBasicBlock * MBB2, MachineBasicBlock::iterator & I1, MachineBasicBlock::iterator & I2) static
ComputeCommonTailLength - Given two machine basic blocks, compute the number of instructions they actually have in common together at their end. Return iterators for the first shared instruction in each block.
Definition at line 319 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::isDebugValue(), llvm::MachineInstr::isIdenticalTo(), and llvm::MachineInstr::isInlineAsm().
Referenced by ProfitableToMerge().
CountTerminators()
unsigned CountTerminators (MachineBasicBlock * MBB, MachineBasicBlock::iterator & I) static
CountTerminators - Count the number of terminators in the given block and set I to the position of the first non-terminator, if there is one, or MBB->end() otherwise.
Definition at line 532 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), and I.
Referenced by ProfitableToMerge().
EstimateRuntime()
unsigned EstimateRuntime (MachineBasicBlock::iterator I, MachineBasicBlock::iterator E) static
EstimateRuntime - Make a rough estimate for how long it will take to run the specified code.
Definition at line 453 of file BranchFolding.cpp.
References I.
findFalseBlock()
MachineBasicBlock * findFalseBlock (MachineBasicBlock * BB, MachineBasicBlock * TrueBB) static
findFalseBlock - BB has a fallthrough. Find its 'false' successor given its 'true' successor.
Definition at line 1534 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
findHoistingInsertPosAndDeps()
MachineBasicBlock::iterator findHoistingInsertPosAndDeps (MachineBasicBlock * MBB, const TargetInstrInfo * TII, const TargetRegisterInfo * TRI, SmallSet< unsigned, 4 > & Uses, SmallSet< unsigned, 4 > & Defs) static
findHoistingInsertPosAndDeps - Find the location to move common instructions in successors to. The location is usually just before the terminator, however if the terminator is a conditional branch and its previous instruction is the flag setting instruction, the previous instruction is the preferred location. This function also gathers uses and defs of the instructions from the insertion point to the end of the block. The data is used by HoistCommonCodeInSuccs to ensure safety.
Definition at line 1553 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SmallSet< T, N, C >::count(), llvm::SmallSet< T, N, C >::empty(), llvm::MachineBasicBlock::end(), llvm::SmallSet< T, N, C >::erase(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineOperand::isDead(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineInstr::isSafeToMove(), llvm::MachineOperand::isUse(), llvm::MCRegAliasIterator::isValid(), llvm::MCRegisterInfo::DiffListIterator::isValid(), and TII.
FixTail()
void FixTail (MachineBasicBlock * CurMBB, MachineBasicBlock * SuccBB, const TargetInstrInfo * TII) static
Definition at line 473 of file BranchFolding.cpp.
References llvm::SmallVectorBase::empty(), llvm::MachineFunction::end(), llvm::MachineBasicBlock::getParent(), I, and TII.
getBranchDebugLoc()
DebugLoc getBranchDebugLoc (MachineBasicBlock & MBB) static
getBranchDebugLoc - Find and return, if any, the DebugLoc of the branch instructions on the block. Always use the DebugLoc of the first branching instruction found unless its absent, in which case use the DebugLoc of the second if present.
Definition at line 1116 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), and I.
HashEndOfMBB()
unsigned HashEndOfMBB (const MachineBasicBlock * MBB) static
HashEndOfMBB - Hash the last instruction in the MBB.
Definition at line 300 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), HashMachineInstr(), and I.
HashMachineInstr()
unsigned HashMachineInstr (const MachineInstr * MI) static
HashMachineInstr - Compute a hash value for MI and its operands.
Definition at line 267 of file BranchFolding.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineBasicBlock::getNumber(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getType(), llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_FrameIndex, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, and llvm::MachineOperand::MO_Register.
Referenced by HashEndOfMBB().
INITIALIZE_PASS()
INITIALIZE_PASS (BranchFolderPass , "branch-folder" , "Control Flow Optimizer" , false , false)
Definition at line 86 of file BranchFolding.cpp.
References llvm::TargetPassConfig::getEnableTailMerge(), and llvm::BranchFolder::OptimizeFunction().
IsBetterFallthrough()
bool IsBetterFallthrough (MachineBasicBlock * MBB1, MachineBasicBlock * MBB2) static
IsBetterFallthrough - Return true if it would be clearly better to fall-through to MBB1 than to fall through into MBB2. This has to return a strict ordering, returning true for both (MBB1,MBB2) and (MBB2,MBB1) will result in infinite loops.
Definition at line 1088 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::end(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isDebugValue(), IsEmptyBlock(), and llvm::MachineBasicBlock::isSuccessor().
IsBranchOnlyBlock()
bool IsBranchOnlyBlock (MachineBasicBlock * MBB) static
Definition at line 1075 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::isBranch(), and llvm::MachineInstr::isDebugValue().
IsEmptyBlock()
bool IsEmptyBlock (MachineBasicBlock * MBB) static
Definition at line 1062 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::empty(), and llvm::MachineBasicBlock::end().
Referenced by IsBetterFallthrough().
ProfitableToMerge()
bool ProfitableToMerge (MachineBasicBlock * MBB1, MachineBasicBlock * MBB2, unsigned minCommonTailLength, unsigned & CommonTailLen, MachineBasicBlock::iterator & I1, MachineBasicBlock::iterator & I2, MachineBasicBlock * SuccBB, MachineBasicBlock * PredBB) static
ProfitableToMerge - Check if two machine basic blocks have a common tail and decide if it would be profitable to merge those tails. Return the length of the common tail and iterators to the first common instruction in each block.
Definition at line 552 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::back(), llvm::MachineBasicBlock::begin(), ComputeCommonTailLength(), CountTerminators(), llvm::dbgs(), DEBUG, llvm::AttributeSet::FunctionIndex, llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::getParent(), I, llvm::MachineInstr::isBarrier(), llvm::MachineBasicBlock::isLayoutSuccessor(), and llvm::Attribute::OptimizeForSize.
STATISTIC() [1/4]
STATISTIC (NumBranchOpts , "Number of branches optimized")
STATISTIC() [2/4]
STATISTIC (NumDeadBlocks , "Number of dead blocks removed")
STATISTIC() [3/4]
STATISTIC (NumHoist , "Number of times common instructions are hoisted")
STATISTIC() [4/4]
STATISTIC (NumTailMerge , "Number of block tails merged")
Variable Documentation
FlagEnableTailMerge
cl::opt< cl::boolOrDefault > FlagEnableTailMerge("enable-tail-merge", cl::init(cl::BOU_UNSET), cl::Hidden) ("enable-tail-merge" , cl::init(cl::BOU_UNSET) , cl::Hidden) static
Referenced by llvm::BranchFolder::BranchFolder().
TailMergeSize
cl::opt< unsigned > TailMergeSize("tail-merge-size", cl::desc("Min number of instructions to consider tail merging"), cl::init(3), cl::Hidden) ("tail-merge-size" , cl::desc("Min number of instructions to consider tail merging") , cl::init(3) , cl::Hidden) static
TailMergeThreshold
cl::opt< unsigned > TailMergeThreshold("tail-merge-threshold", cl::desc("Max number of predecessors to consider tail merging"), cl::init(150), cl::Hidden) ("tail-merge-threshold" , cl::desc("Max number of predecessors to consider tail merging") , cl::init(150) , cl::Hidden) static