LLVM: BypassSlowDivision.cpp File Reference
LLVM API Documentation
BypassSlowDivision.cpp File Reference
#include "llvm/Transforms/Utils/BypassSlowDivision.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
Classes
struct llvm::DenseMapInfo< DivOpInfo >
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "bypass-slow-division"
Typedefs
typedef DenseMap< DivOpInfo, DivPhiNodes > llvm::DivCacheTy
Functions
static bool insertFastDiv (Function &F, Function::iterator &I, BasicBlock::iterator &J, IntegerType *BypassType, bool UseDivOp, bool UseSignedOp, DivCacheTy &PerBBDivCache)
static bool reuseOrInsertFastDiv (Function &F, Function::iterator &I, BasicBlock::iterator &J, IntegerType *BypassType, bool UseDivOp, bool UseSignedOp, DivCacheTy &PerBBDivCache)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "bypass-slow-division"
Definition at line 26 of file BypassSlowDivision.cpp.
Function Documentation
insertFastDiv()
bool insertFastDiv (Function & F, Function::iterator & I, BasicBlock::iterator & J, IntegerType * BypassType, bool UseDivOp, bool UseSignedOp, DivCacheTy & PerBBDivCache) static
Definition at line 77 of file BypassSlowDivision.cpp.
References llvm::PHINode::addIncoming(), llvm::iplist< NodeTy, Traits >::back(), llvm::BasicBlock::begin(), llvm::BasicBlock::Create(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAnd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCondBr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateExactUDiv(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateOr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreatePHI(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSDiv(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSRem(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateUDiv(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateURem(), llvm::BasicBlock::end(), llvm::Instruction::eraseFromParent(), F, llvm::BasicBlock::getInstList(), llvm::User::getOperand(), llvm::BasicBlock::getParent(), llvm::ConstantInt::getSigned(), llvm::Value::getType(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::isa(), llvm::BasicBlock::moveBefore(), and llvm::Value::replaceAllUsesWith().
Referenced by reuseOrInsertFastDiv().
reuseOrInsertFastDiv()
bool reuseOrInsertFastDiv (Function & F, Function::iterator & I, BasicBlock::iterator & J, IntegerType * BypassType, bool UseDivOp, bool UseSignedOp, DivCacheTy & PerBBDivCache) static
Definition at line 185 of file BypassSlowDivision.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::Instruction::eraseFromParent(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::User::getOperand(), I, and insertFastDiv().
Referenced by llvm::bypassSlowDivision().