LLVM: CFGPrinter.cpp File Reference
LLVM API Documentation
CFGPrinter.cpp File Reference
#include "llvm/Analysis/CFGPrinter.h"
#include "llvm/Pass.h"
#include "llvm/Support/FileSystem.h"
Functions
INITIALIZE_PASS (CFGOnlyViewer, "view-cfg-only", "View CFG of function (with no function bodies)", false, true) namespace
INITIALIZE_PASS (CFGPrinter, "dot-cfg", "Print CFG of function to 'dot' file", false, true) namespace
INITIALIZE_PASS (CFGOnlyPrinter, "dot-cfg-only", "Print CFG of function to 'dot' file (with no function bodies)", false, true) void Function
Function Documentation
INITIALIZE_PASS() [1/3]
INITIALIZE_PASS (CFGOnlyPrinter , "dot-cfg-only" , "Print CFG of function to 'dot' file (with no function bodies)" , false , true)
viewCFG - This function is meant for use from the debugger. You can just say 'call F->viewCFG()' and a ghostview window should pop up from the program, displaying the CFG of the current function. This depends on there being a 'dot' and 'gv' program in your path. viewCFGOnly - This function is meant for use from the debugger. It works just like viewCFG, but it does not include the contents of basic blocks into the nodes, just the label. If you are only interested in the CFG this can make the graph smaller.
Definition at line 136 of file CFGPrinter.cpp.
References getName(), and llvm::ViewGraph().
INITIALIZE_PASS() [2/3]
INITIALIZE_PASS (CFGOnlyViewer , "view-cfg-only" , "View CFG of function (with no function bodies)" , false , true)
Definition at line 69 of file CFGPrinter.cpp.
References llvm::errs(), F, llvm::sys::fs::F_Text, llvm::FunctionPass::FunctionPass(), llvm::Pass::getAnalysisUsage(), llvm::PassRegistry::getPassRegistry(), llvm::initializeCFGPrinterPass(), llvm::Pass::print(), llvm::FunctionPass::runOnFunction(), llvm::AnalysisUsage::setPreservesAll(), and llvm::WriteGraph().
INITIALIZE_PASS() [3/3]
INITIALIZE_PASS (CFGPrinter , "dot-cfg" , "Print CFG of function to 'dot' file" , false , true)
Definition at line 103 of file CFGPrinter.cpp.
References llvm::errs(), F, llvm::sys::fs::F_Text, llvm::FunctionPass::FunctionPass(), llvm::Pass::getAnalysisUsage(), llvm::PassRegistry::getPassRegistry(), llvm::initializeCFGOnlyPrinterPass(), llvm::Pass::print(), llvm::FunctionPass::runOnFunction(), llvm::AnalysisUsage::setPreservesAll(), and llvm::WriteGraph().