LLVM: llvm::Linker Class Reference
LLVM API Documentation
llvm::Linker Class Reference
#include <Linker.h>
Classes
struct IdentifiedStructTypeSet
struct StructTypeKeyInfo
Public Types
typedef DenseSet< StructType *, StructTypeKeyInfo > NonOpaqueStructTypeSet
typedef DenseSet< StructType * > OpaqueStructTypeSet
Public Member Functions
Linker (Module *M, DiagnosticHandlerFunction DiagnosticHandler)
Linker (Module *M)
~Linker ()
Module * getModule () const
void deleteModule ()
bool linkInModule (Module *Src)
Link Src into the composite. The source is destroyed. Returns true on error.
Static Public Member Functions
static bool LinkModules (Module *Dest, Module *Src, DiagnosticHandlerFunction DiagnosticHandler)
static bool LinkModules (Module *Dest, Module *Src)
Detailed Description
This class provides the core functionality of linking in LLVM. It keeps a pointer to the merged module so far. It doesn't take ownership of the module since it is assumed that the user of this class will want to do something with it after the linking.
Definition at line 27 of file llvm/Linker/Linker.h.
Member Typedef Documentation
NonOpaqueStructTypeSet
typedef DenseSet<StructType *, StructTypeKeyInfo> llvm::Linker::NonOpaqueStructTypeSet
Definition at line 46 of file llvm/Linker/Linker.h.
OpaqueStructTypeSet
typedef DenseSet<StructType *> llvm::Linker::OpaqueStructTypeSet
Definition at line 47 of file llvm/Linker/Linker.h.
Constructor & Destructor Documentation
Linker() [1/2]
Linker::Linker (Module * M, DiagnosticHandlerFunction DiagnosticHandler)
Definition at line 1703 of file LinkModules.cpp.
Referenced by LinkModules(), and LinkModules().
Linker() [2/2]
Linker::Linker (Module * M)
Definition at line 1707 of file LinkModules.cpp.
~Linker()
Linker::~Linker ()
Definition at line 1713 of file LinkModules.cpp.
Member Function Documentation
deleteModule()
void Linker::deleteModule ()
Definition at line 1716 of file LinkModules.cpp.
getModule()
Module * llvm::Linker::getModule () const inline
Definition at line 66 of file llvm/Linker/Linker.h.
linkInModule()
bool Linker::linkInModule (Module * Src)
Link Src into the composite. The source is destroyed. Returns true on error.
Definition at line 1721 of file LinkModules.cpp.
Referenced by LinkModules(), and LinkModules().
LinkModules() [1/2]
bool Linker::LinkModules (Module * Dest, Module * Src) static
Definition at line 1742 of file LinkModules.cpp.
References Linker(), and linkInModule().
LinkModules() [2/2]
bool Linker::LinkModules (Module * Dest, Module * Src, DiagnosticHandlerFunction DiagnosticHandler) static
This function links two modules together, with the resulting Dest module modified to be the composite of the two input modules. If an error occurs, true is returned and ErrorMsg (if not null) is set to indicate the problem. Upon failure, the Dest module could be in a modified state, and shouldn't be relied on to be consistent.
Definition at line 1736 of file LinkModules.cpp.
References Linker(), and linkInModule().
Referenced by LLVMLinkModules().
The documentation for this class was generated from the following files:
llvm/Linker/Linker.h
LinkModules.cpp