LLVM: llvm::Optional< T > Class Template Reference
LLVM API Documentation
llvm::Optional< T > Class Template Reference
#include <Optional.h>
Public Types
typedef T value_type
Public Member Functions
Optional (NoneType)
Optional ()
Optional (const T &y)
Optional (const Optional &O)
Optional (T &&y)
Optional (Optional< T > &&O)
Optional & operator= (T &&y)
Optional & operator= (Optional &&O)
void emplace ()
Create a new object by default-constructing it in place.
template<typename T1>
void emplace (T1 &&A1)
Create a new object by constructing it in place with the given arguments.
template<typename T1, typename T2>
void emplace (T1 &&A1, T2 &&A2)
Create a new object by constructing it in place with the given arguments.
template<typename T1, typename T2, typename T3>
void emplace (T1 &&A1, T2 &&A2, T3 &&A3)
Create a new object by constructing it in place with the given arguments.
template<typename T1, typename T2, typename T3, typename T4>
void emplace (T1 &&A1, T2 &&A2, T3 &&A3, T4 &&A4)
Create a new object by constructing it in place with the given arguments.
Optional & operator= (const T &y)
Optional & operator= (const Optional &O)
void reset ()
~Optional ()
const T * getPointer () const
T * getPointer ()
const T & getValue () const LLVM_LVALUE_FUNCTION
T & getValue () LLVM_LVALUE_FUNCTION
LLVM_EXPLICIT operator bool () const
bool hasValue () const
const T * operator-> () const
T * operator-> ()
const T & operator* () const LLVM_LVALUE_FUNCTION
T & operator* () LLVM_LVALUE_FUNCTION
template<typename U>
LLVM_CONSTEXPR T getValueOr (U &&value) const LLVM_LVALUE_FUNCTION
Static Public Member Functions
static Optional create (const T *y)
Detailed Description
template<typename T>
class llvm::Optional< T >
Definition at line 29 of file Optional.h.
Member Typedef Documentation
value_type
template<typename T> typedef T llvm::Optional< T >::value_type
Definition at line 33 of file Optional.h.
Constructor & Destructor Documentation
Optional() [1/6]
template<typename T> llvm::Optional< T >::Optional (NoneType) inline
Definition at line 35 of file Optional.h.
Referenced by create(), operator=(), operator=(), operator=(), operator=(), Optional(), and Optional().
Optional() [2/6]
template<typename T> llvm::Optional< T >::Optional () inline explicit
Definition at line 36 of file Optional.h.
Referenced by create().
Optional() [3/6]
template<typename T> llvm::Optional< T >::Optional (const T & y) inline
Definition at line 37 of file Optional.h.
References T, and true.
Optional() [4/6]
template<typename T> llvm::Optional< T >::Optional (const Optional< T > & O) inline
Definition at line 40 of file Optional.h.
References Optional(), and T.
Optional() [5/6]
template<typename T> llvm::Optional< T >::Optional (T && y) inline
Definition at line 45 of file Optional.h.
References T, and true.
Optional() [6/6]
template<typename T> llvm::Optional< T >::Optional (Optional< T > && O) inline
Definition at line 48 of file Optional.h.
References Optional(), and T.
~Optional()
template<typename T> llvm::Optional< T >::~Optional () inline
Definition at line 162 of file Optional.h.
References reset().
Member Function Documentation
create()
template<typename T> Optional llvm::Optional< T >::create (const T * y) inline static
Definition at line 128 of file Optional.h.
References Optional(), Optional(), and T.
emplace() [1/5]
template<typename T> void llvm::Optional< T >::emplace () inline
Create a new object by default-constructing it in place.
Definition at line 86 of file Optional.h.
References reset(), and T.
emplace() [2/5]
template<typename T> template<typename T1> void llvm::Optional< T >::emplace (T1 && A1) inline
Create a new object by constructing it in place with the given arguments.
Definition at line 94 of file Optional.h.
References reset(), T, and T1.
emplace() [3/5]
template<typename T> template<typename T1, typename T2> void llvm::Optional< T >::emplace (T1 && A1, T2 && A2) inline
Create a new object by constructing it in place with the given arguments.
Definition at line 102 of file Optional.h.
References reset(), T, and T1.
emplace() [4/5]
template<typename T> template<typename T1, typename T2, typename T3> void llvm::Optional< T >::emplace (T1 && A1, T2 && A2, T3 && A3) inline
Create a new object by constructing it in place with the given arguments.
Definition at line 110 of file Optional.h.
References reset(), T, and T1.
emplace() [5/5]
template<typename T> template<typename T1, typename T2, typename T3, typename T4> void llvm::Optional< T >::emplace (T1 && A1, T2 && A2, T3 && A3, T4 && A4) inline
Create a new object by constructing it in place with the given arguments.
Definition at line 119 of file Optional.h.
References reset(), T, and T1.
getPointer() [1/2]
template<typename T> T * llvm::Optional< T >::getPointer () inline
Definition at line 167 of file Optional.h.
References T.
getPointer() [2/2]
template<typename T> const T * llvm::Optional< T >::getPointer () const inline
Definition at line 166 of file Optional.h.
References T.
Referenced by getValue(), getValue(), operator*(), operator*(), operator->(), and operator->().
getValue() [1/2]
template<typename T> const T & llvm::Optional< T >::getValue () const inline
Definition at line 168 of file Optional.h.
References const, getPointer(), LLVM_LVALUE_FUNCTION, and T.
Referenced by llvm::DWARFFormValue::dump(), llvm::sys::Process::FindInEnvPath(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsAddress(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsReference(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsSectionOffset(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsString(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsUnsignedConstant(), llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getUnsignedRange(), and getValueOr().
getValue() [2/2]
template<typename T> T & llvm::Optional< T >::getValue () inline
Definition at line 169 of file Optional.h.
References getPointer(), LLVM_LVALUE_FUNCTION, and T.
getValueOr()
template<typename T> template<typename U> LLVM_CONSTEXPR T llvm::Optional< T >::getValueOr (U && value) const inline
Definition at line 179 of file Optional.h.
References getValue(), hasValue(), LLVM_CONSTEXPR, LLVM_LVALUE_FUNCTION, and T.
hasValue()
template<typename T> bool llvm::Optional< T >::hasValue () const inline
Definition at line 172 of file Optional.h.
Referenced by llvm::DWARFFormValue::dump(), llvm::sys::Process::FindInEnvPath(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsAddress(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsReference(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsSectionOffset(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsString(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsUnsignedConstant(), llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getUnsignedRange(), and getValueOr().
operator bool()
template<typename T> LLVM_EXPLICIT llvm::Optional< T >::operator bool () const inline
Definition at line 171 of file Optional.h.
References LLVM_EXPLICIT.
operator*() [1/2]
template<typename T> const T & llvm::Optional< T >::operator* () const inline
Definition at line 175 of file Optional.h.
References const, getPointer(), LLVM_LVALUE_FUNCTION, and T.
operator*() [2/2]
template<typename T> T & llvm::Optional< T >::operator* () inline
Definition at line 176 of file Optional.h.
References getPointer(), LLVM_LVALUE_FUNCTION, and T.
operator->() [1/2]
template<typename T> T * llvm::Optional< T >::operator-> () inline
Definition at line 174 of file Optional.h.
References getPointer(), and T.
operator->() [2/2]
template<typename T> const T * llvm::Optional< T >::operator-> () const inline
Definition at line 173 of file Optional.h.
References getPointer(), and T.
operator=() [1/4]
template<typename T> Optional & llvm::Optional< T >::operator= (const Optional< T > & O) inline
Definition at line 147 of file Optional.h.
References Optional(), and reset().
operator=() [2/4]
template<typename T> Optional & llvm::Optional< T >::operator= (const T & y) inline
Definition at line 137 of file Optional.h.
References Optional(), and T.
operator=() [3/4]
template<typename T> Optional & llvm::Optional< T >::operator= (Optional< T > && O) inline
Definition at line 63 of file Optional.h.
References Optional(), and reset().
operator=() [4/4]
template<typename T> Optional & llvm::Optional< T >::operator= (T && y) inline
Definition at line 54 of file Optional.h.
References Optional(), and T.
reset()
template<typename T> void llvm::Optional< T >::reset () inline
Definition at line 155 of file Optional.h.
Referenced by emplace(), emplace(), emplace(), emplace(), emplace(), operator=(), operator=(), and ~Optional().
The documentation for this class was generated from the following file:
Optional.h