LLVM: llvm::IntrinsicLowering Class Reference
LLVM API Documentation
llvm::IntrinsicLowering Class Reference
#include <IntrinsicLowering.h>
Public Member Functions
IntrinsicLowering (const DataLayout &DL)
void AddPrototypes (Module &M)
void LowerIntrinsicCall (CallInst *CI)
Static Public Member Functions
static bool LowerToByteSwap (CallInst *CI)
Detailed Description
Definition at line 26 of file IntrinsicLowering.h.
Constructor & Destructor Documentation
IntrinsicLowering()
llvm::IntrinsicLowering::IntrinsicLowering (const DataLayout & DL) inline explicit
Definition at line 32 of file IntrinsicLowering.h.
Member Function Documentation
AddPrototypes()
void IntrinsicLowering::AddPrototypes (Module & M)
AddPrototypes - This method, if called, causes all of the prototypes that might be needed by an intrinsic lowering implementation to be inserted into the module specified.
Definition at line 95 of file IntrinsicLowering.cpp.
References llvm::Module::begin(), llvm::Intrinsic::cos, llvm::Module::end(), EnsureFPIntrinsicsExist(), EnsureFunctionExists(), llvm::Intrinsic::exp, llvm::Intrinsic::exp2, llvm::Module::getContext(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), llvm::Module::getOrInsertFunction(), llvm::Type::getVoidTy(), I, llvm::Intrinsic::log, llvm::Intrinsic::log10, llvm::Intrinsic::log2, llvm::Intrinsic::longjmp, llvm::Intrinsic::memcpy, llvm::Intrinsic::memmove, llvm::Intrinsic::memset, llvm::Intrinsic::pow, llvm::Intrinsic::setjmp, llvm::Intrinsic::siglongjmp, llvm::Intrinsic::sin, and llvm::Intrinsic::sqrt.
LowerIntrinsicCall()
void IntrinsicLowering::LowerIntrinsicCall (CallInst * CI)
LowerIntrinsicCall - This method replaces a call with the LLVM function which should be used to implement the specified intrinsic function call. If an intrinsic function must be implemented by the code generator (such as va_start), this function should print a message and abort.
Otherwise, if an intrinsic function call can be lowered, the code to implement it (often a call to a non-intrinsic function) is inserted after the call instruction and the call is deleted. The caller must be capable of handling this kind of change.
Definition at line 340 of file IntrinsicLowering.cpp.
References llvm::Intrinsic::annotation, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), llvm::Intrinsic::assume, llvm::Intrinsic::bswap, llvm::cast(), llvm::Intrinsic::ceil, llvm::Intrinsic::copysign, llvm::Intrinsic::cos, llvm::IRBuilder< preserveNames, T, Inserter >::CreateAnd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateIntCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateNot(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSub(), llvm::Intrinsic::ctlz, llvm::Intrinsic::ctpop, llvm::Intrinsic::cttz, llvm::Intrinsic::dbg_declare, llvm::Intrinsic::eh_typeid_for, llvm::Instruction::eraseFromParent(), llvm::errs(), llvm::Intrinsic::exp, llvm::Intrinsic::exp2, llvm::Intrinsic::expect, llvm::Intrinsic::floor, llvm::Intrinsic::flt_rounds, llvm::Intrinsic::frameaddress, llvm::ConstantInt::get(), llvm::ConstantPointerNull::get(), llvm::UndefValue::get(), llvm::CallInst::getArgOperand(), llvm::CallInst::getCalledFunction(), llvm::Value::getContext(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Function::getIntrinsicID(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::Type::getVoidTy(), llvm::Intrinsic::invariant_end, llvm::Intrinsic::invariant_start, llvm::Type::isVoidTy(), llvm::Intrinsic::lifetime_end, llvm::Intrinsic::lifetime_start, llvm::Intrinsic::log, llvm::Intrinsic::log10, llvm::Intrinsic::log2, llvm::Intrinsic::longjmp, LowerBSWAP(), LowerCTLZ(), LowerCTPOP(), llvm::Intrinsic::memcpy, llvm::Intrinsic::memmove, llvm::Intrinsic::memset, llvm::Intrinsic::not_intrinsic, llvm::Intrinsic::pcmarker, llvm::Intrinsic::pow, llvm::Intrinsic::prefetch, llvm::Intrinsic::ptr_annotation, llvm::Intrinsic::readcyclecounter, llvm::Value::replaceAllUsesWith(), ReplaceCallWith(), ReplaceFPIntrinsicWithCall(), llvm::report_fatal_error(), llvm::Intrinsic::returnaddress, llvm::Intrinsic::round, llvm::Intrinsic::setjmp, llvm::Value::setName(), llvm::Intrinsic::siglongjmp, llvm::Intrinsic::sigsetjmp, llvm::Intrinsic::sin, llvm::Intrinsic::sqrt, llvm::Intrinsic::stackrestore, llvm::Intrinsic::stacksave, llvm::Intrinsic::trunc, llvm::Value::use_empty(), and llvm::Intrinsic::var_annotation.
LowerToByteSwap()
bool IntrinsicLowering::LowerToByteSwap (CallInst * CI) static
LowerToByteSwap - Replace a call instruction into a call to bswap intrinsic. Return false if it has determined the call is not a simple integer bswap.
Definition at line 580 of file IntrinsicLowering.cpp.
References llvm::Intrinsic::bswap, llvm::CallInst::Create(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::CallInst::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Value::getName(), llvm::CallInst::getNumArgOperands(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::Type::isIntegerTy(), and llvm::Value::replaceAllUsesWith().
Referenced by llvm::ARMTargetLowering::ExpandInlineAsm(), and llvm::X86TargetLowering::ExpandInlineAsm().
The documentation for this class was generated from the following files:
IntrinsicLowering.h
IntrinsicLowering.cpp