LLVM: llvm::SelectionDAGISel Class Reference
LLVM API Documentation
llvm::SelectionDAGISel Class Reference abstract
#include <SelectionDAGISel.h>
Public Types
enum BuiltinOpcodes {
OPC_Scope , OPC_RecordNode , OPC_RecordChild0 , OPC_RecordChild1 ,
OPC_RecordChild2 , OPC_RecordChild3 , OPC_RecordChild4 , OPC_RecordChild5 ,
OPC_RecordChild6 , OPC_RecordChild7 , OPC_RecordMemRef , OPC_CaptureGlueInput ,
OPC_MoveChild , OPC_MoveParent , OPC_CheckSame , OPC_CheckChild0Same ,
OPC_CheckChild1Same , OPC_CheckChild2Same , OPC_CheckChild3Same , OPC_CheckPatternPredicate ,
OPC_CheckPredicate , OPC_CheckOpcode , OPC_SwitchOpcode , OPC_CheckType ,
OPC_SwitchType , OPC_CheckChild0Type , OPC_CheckChild1Type , OPC_CheckChild2Type ,
OPC_CheckChild3Type , OPC_CheckChild4Type , OPC_CheckChild5Type , OPC_CheckChild6Type ,
OPC_CheckChild7Type , OPC_CheckInteger , OPC_CheckChild0Integer , OPC_CheckChild1Integer ,
OPC_CheckChild2Integer , OPC_CheckChild3Integer , OPC_CheckChild4Integer , OPC_CheckCondCode ,
OPC_CheckValueType , OPC_CheckComplexPat , OPC_CheckAndImm , OPC_CheckOrImm ,
OPC_CheckFoldableChainNode , OPC_EmitInteger , OPC_EmitRegister , OPC_EmitRegister2 ,
OPC_EmitConvertToTarget , OPC_EmitMergeInputChains , OPC_EmitMergeInputChains1_0 , OPC_EmitMergeInputChains1_1 ,
OPC_EmitCopyToReg , OPC_EmitNodeXForm , OPC_EmitNode , OPC_MorphNodeTo ,
OPC_MarkGlueResults , OPC_CompleteMatch
}
enum {
OPFL_None = 0 , OPFL_Chain = 1 , OPFL_GlueInput = 2 , OPFL_GlueOutput = 4 ,
OPFL_MemRefs = 8 , OPFL_Variadic0 = 1<<4 , OPFL_Variadic1 = 2<<4 , OPFL_Variadic2 = 3<<4 ,
OPFL_Variadic3 = 4<<4 , OPFL_Variadic4 = 5<<4 , OPFL_Variadic5 = 6<<4 , OPFL_Variadic6 = 7<<4 ,
OPFL_VariadicInfo = OPFL_Variadic6
}
Public Member Functions
SelectionDAGISel (TargetMachine &tm, CodeGenOpt::Level OL=CodeGenOpt::Default)
virtual ~SelectionDAGISel ()
const TargetLowering * getTargetLowering () const
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnMachineFunction (MachineFunction &MF) override
virtual void EmitFunctionEntryCode ()
virtual void PreprocessISelDAG ()
virtual void PostprocessISelDAG ()
virtual SDNode * Select (SDNode *N)=0
Select - Main hook targets implement to select a node.
virtual bool SelectInlineAsmMemoryOperand (const SDValue &Op, char ConstraintCode, std::vector< SDValue > &OutOps)
virtual bool IsProfitableToFold (SDValue N, SDNode *U, SDNode *Root) const
bool CheckAndMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
bool CheckOrMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
virtual bool CheckPatternPredicate (unsigned PredNo) const
virtual bool CheckNodePredicate (SDNode *N, unsigned PredNo) const
virtual bool CheckComplexPattern (SDNode *Root, SDNode *Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > &Result)
virtual SDValue RunSDNodeXForm (SDValue V, unsigned XFormNo)
SDNode * SelectCodeCommon (SDNode *NodeToMatch, const unsigned char *MatcherTable, unsigned TableSize)
virtual bool ComplexPatternFuncMutatesDAG () const
Return true if complex patterns for this target can mutate the DAG.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Member Functions
static bool IsLegalToFold (SDValue N, SDNode *U, SDNode *Root, CodeGenOpt::Level OptLevel, bool IgnoreChains=false)
static int getNumFixedFromVariadicInfo (unsigned Flags)
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes
TargetMachine & TM
const TargetLibraryInfo * LibInfo
FunctionLoweringInfo * FuncInfo
MachineFunction * MF
MachineRegisterInfo * RegInfo
SelectionDAG * CurDAG
SelectionDAGBuilder * SDB
AliasAnalysis * AA
GCFunctionInfo * GFI
CodeGenOpt::Level OptLevel
const TargetInstrInfo * TII
const TargetLowering * TLI
Static Public Attributes
static char ID = 0
Protected Member Functions
void ReplaceUses (SDValue F, SDValue T)
void ReplaceUses (const SDValue *F, const SDValue *T, unsigned Num)
void ReplaceUses (SDNode *F, SDNode *T)
void SelectInlineAsmMemoryOperands (std::vector< SDValue > &Ops)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Protected Attributes
unsigned DAGSize
Detailed Description
SelectionDAGISel - This is the common base class used for SelectionDAG-based pattern-matching instruction selectors.
Definition at line 42 of file SelectionDAGISel.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
OPFL_None
OPFL_Chain
OPFL_GlueInput
OPFL_GlueOutput
OPFL_MemRefs
OPFL_Variadic0
OPFL_Variadic1
OPFL_Variadic2
OPFL_Variadic3
OPFL_Variadic4
OPFL_Variadic5
OPFL_Variadic6
OPFL_VariadicInfo
Definition at line 151 of file SelectionDAGISel.h.
BuiltinOpcodes
enum llvm::SelectionDAGISel::BuiltinOpcodes
Enumerator
OPC_Scope
OPC_RecordNode
OPC_RecordChild0
OPC_RecordChild1
OPC_RecordChild2
OPC_RecordChild3
OPC_RecordChild4
OPC_RecordChild5
OPC_RecordChild6
OPC_RecordChild7
OPC_RecordMemRef
OPC_CaptureGlueInput
OPC_MoveChild
OPC_MoveParent
OPC_CheckSame
OPC_CheckChild0Same
OPC_CheckChild1Same
OPC_CheckChild2Same
OPC_CheckChild3Same
OPC_CheckPatternPredicate
OPC_CheckPredicate
OPC_CheckOpcode
OPC_SwitchOpcode
OPC_CheckType
OPC_SwitchType
OPC_CheckChild0Type
OPC_CheckChild1Type
OPC_CheckChild2Type
OPC_CheckChild3Type
OPC_CheckChild4Type
OPC_CheckChild5Type
OPC_CheckChild6Type
OPC_CheckChild7Type
OPC_CheckInteger
OPC_CheckChild0Integer
OPC_CheckChild1Integer
OPC_CheckChild2Integer
OPC_CheckChild3Integer
OPC_CheckChild4Integer
OPC_CheckCondCode
OPC_CheckValueType
OPC_CheckComplexPat
OPC_CheckAndImm
OPC_CheckOrImm
OPC_CheckFoldableChainNode
OPC_EmitInteger
OPC_EmitRegister
OPC_EmitRegister2
OPC_EmitConvertToTarget
OPC_EmitMergeInputChains
OPC_EmitMergeInputChains1_0
OPC_EmitMergeInputChains1_1
OPC_EmitCopyToReg
OPC_EmitNodeXForm
OPC_EmitNode
OPC_MorphNodeTo
OPC_MarkGlueResults
OPC_CompleteMatch
Definition at line 106 of file SelectionDAGISel.h.
Constructor & Destructor Documentation
SelectionDAGISel()
SelectionDAGISel::SelectionDAGISel (TargetMachine & tm, CodeGenOpt::Level OL = CodeGenOpt::Default) explicit
Definition at line 340 of file SelectionDAGISel.cpp.
References CurDAG, DAGSize, FuncInfo, llvm::PassRegistry::getPassRegistry(), GFI, ID, llvm::initializeAliasAnalysisAnalysisGroup(), llvm::initializeBranchProbabilityInfoPass(), llvm::initializeGCModuleInfoPass(), llvm::initializeTargetLibraryInfoPass(), llvm::MachineFunctionPass::MachineFunctionPass(), OptLevel, SDB, and TM.
Referenced by llvm::MipsDAGToDAGISel::MipsDAGToDAGISel().
~SelectionDAGISel()
SelectionDAGISel::~SelectionDAGISel () virtual
Definition at line 355 of file SelectionDAGISel.cpp.
References CurDAG, FuncInfo, and SDB.
Member Function Documentation
CheckAndMask()
bool SelectionDAGISel::CheckAndMask (SDValue LHS, ConstantSDNode * RHS, int64_t DesiredMaskS) const
CheckAndMask - The isel is trying to match something like (and X, 255). If the dag combiner simplified the 255, we still want to match. RHS is the actual value in the DAG on the RHS of an AND, and DesiredMaskS is the value specified in the .td file (e.g. 255).
Definition at line 1621 of file SelectionDAGISel.cpp.
References CurDAG, llvm::ConstantSDNode::getAPIntValue(), llvm::SDValue::getValueSizeInBits(), and llvm::APInt::intersects().
Referenced by CheckAndImm().
CheckComplexPattern()
virtual bool llvm::SelectionDAGISel::CheckComplexPattern (SDNode * Root, SDNode * Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > & Result) inline virtual
Definition at line 229 of file SelectionDAGISel.h.
References llvm_unreachable, and N.
Referenced by SelectCodeCommon().
CheckNodePredicate()
virtual bool llvm::SelectionDAGISel::CheckNodePredicate (SDNode * N, unsigned PredNo) const inline virtual
CheckNodePredicate - This function is generated by tblgen in the target. It runs node predicate number PredNo and returns true if it succeeds or false if it fails. The number is a private implementation detail to the code tblgen produces.
Definition at line 225 of file SelectionDAGISel.h.
References llvm_unreachable, and N.
Referenced by CheckNodePredicate(), and SelectCodeCommon().
CheckOrMask()
bool SelectionDAGISel::CheckOrMask (SDValue LHS, ConstantSDNode * RHS, int64_t DesiredMaskS) const
CheckOrMask - The isel is trying to match something like (or X, 255). If the dag combiner simplified the 255, we still want to match. RHS is the actual value in the DAG on the RHS of an OR, and DesiredMaskS is the value specified in the .td file (e.g. 255).
Definition at line 1650 of file SelectionDAGISel.cpp.
References CurDAG, llvm::ConstantSDNode::getAPIntValue(), llvm::SDValue::getValueSizeInBits(), and llvm::APInt::intersects().
Referenced by CheckOrImm().
CheckPatternPredicate()
virtual bool llvm::SelectionDAGISel::CheckPatternPredicate (unsigned PredNo) const inline virtual
CheckPatternPredicate - This function is generated by tblgen in the target. It runs the specified pattern predicate and returns true if it succeeds or false if it fails. The number is a private implementation detail to the code tblgen produces.
Definition at line 217 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by CheckPatternPredicate(), and SelectCodeCommon().
ComplexPatternFuncMutatesDAG()
virtual bool llvm::SelectionDAGISel::ComplexPatternFuncMutatesDAG () const inline virtual
Return true if complex patterns for this target can mutate the DAG.
Definition at line 245 of file SelectionDAGISel.h.
Referenced by SelectCodeCommon().
EmitFunctionEntryCode()
virtual void llvm::SelectionDAGISel::EmitFunctionEntryCode () inline virtual
Definition at line 69 of file SelectionDAGISel.h.
getAnalysisUsage()
void SelectionDAGISel::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 361 of file SelectionDAGISel.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::CodeGenOpt::None, OptLevel, and UseMBPI.
getNumFixedFromVariadicInfo()
int llvm::SelectionDAGISel::getNumFixedFromVariadicInfo (unsigned Flags) inline static
getNumFixedFromVariadicInfo - Transform an EmitNode flags word into the number of fixed arity values that should be skipped when copying from the root.
Definition at line 171 of file SelectionDAGISel.h.
References OPFL_VariadicInfo.
Referenced by SelectCodeCommon().
getTargetLowering()
const TargetLowering * llvm::SelectionDAGISel::getTargetLowering () const inline
Definition at line 63 of file SelectionDAGISel.h.
References TLI.
Referenced by llvm::MipsDAGToDAGISel::getGlobalBaseReg().
IsLegalToFold()
bool SelectionDAGISel::IsLegalToFold (SDValue N, SDNode * U, SDNode * Root, CodeGenOpt::Level OptLevel, bool IgnoreChains = false) static
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root. FIXME: This is a static member function because the MSP430/X86 targets, which uses it during isel. This could become a proper member.
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root.
Definition at line 1792 of file SelectionDAGISel.cpp.
References findGlueUse(), findNonImmUse(), llvm::SDNode::getNumValues(), llvm::SDNode::getValueType(), llvm::MVT::Glue, N, llvm::CodeGenOpt::None, and OptLevel.
Referenced by SelectCodeCommon().
IsProfitableToFold()
bool SelectionDAGISel::IsProfitableToFold (SDValue N, SDNode * U, SDNode * Root) const virtual
IsProfitableToFold - Returns true if it's profitable to fold the specific operand node N of U during instruction selection that starts at Root.
Definition at line 1784 of file SelectionDAGISel.cpp.
References N, llvm::CodeGenOpt::None, and OptLevel.
Referenced by SelectCodeCommon().
PostprocessISelDAG()
virtual void llvm::SelectionDAGISel::PostprocessISelDAG () inline virtual
PostprocessISelDAG() - This hook allows the target to hack on the graph right after selection.
Definition at line 77 of file SelectionDAGISel.h.
PreprocessISelDAG()
virtual void llvm::SelectionDAGISel::PreprocessISelDAG () inline virtual
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
Definition at line 73 of file SelectionDAGISel.h.
ReplaceUses() [1/3]
void llvm::SelectionDAGISel::ReplaceUses (const SDValue * F, const SDValue * T, unsigned Num) inline protected
ReplaceUses - replace all uses of the old nodes F with the use of the new nodes T.
Definition at line 189 of file SelectionDAGISel.h.
References CurDAG, F, and T.
ReplaceUses() [2/3]
void llvm::SelectionDAGISel::ReplaceUses (SDNode * F, SDNode * T) inline protected
ReplaceUses - replace all uses of the old node F with the use of the new node T.
Definition at line 195 of file SelectionDAGISel.h.
References CurDAG, F, and T.
ReplaceUses() [3/3]
void llvm::SelectionDAGISel::ReplaceUses (SDValue F, SDValue T) inline protected
ReplaceUses - replace all uses of the old node F with the use of the new node T.
Definition at line 183 of file SelectionDAGISel.h.
References CurDAG, F, and T.
runOnMachineFunction()
bool SelectionDAGISel::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 410 of file SelectionDAGISel.cpp.
References AA, llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::Function::callsFunctionThatReturnsTwice(), llvm::MachineRegisterInfo::constrainRegClass(), CurDAG, llvm::TargetOpcode::DBG_VALUE, llvm::dbgs(), DEBUG, EnableFastISelAbort, EnableFastISelVerbose, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MachineRegisterInfo::freezeReservedRegs(), FuncInfo, llvm::Pass::getAnalysis(), llvm::MachineInstr::getDebugLoc(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::MachineFunction::getFunction(), llvm::Value::getName(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), GFI, llvm::MachineFrameInfo::hasCalls(), llvm::Function::hasFnAttribute(), llvm::Function::hasGC(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::insertAfter(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isDebugValue(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::TargetRegisterInfo::isVirtualRegister(), LibInfo, MF, llvm::CodeGenOpt::None, llvm::Attribute::OptimizeNone, OptLevel, RegInfo, llvm::MachineRegisterInfo::replaceRegWith(), SDB, llvm::MachineFrameInfo::setHasCalls(), SplitCriticalSideEffectEdges(), TII, TLI, TM, UseMBPI, and llvm::TargetRegisterInfo::virtReg2Index().
Referenced by llvm::MipsDAGToDAGISel::runOnMachineFunction().
RunSDNodeXForm()
virtual SDValue llvm::SelectionDAGISel::RunSDNodeXForm (SDValue V, unsigned XFormNo) inline virtual
Definition at line 235 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
Select()
virtual SDNode * llvm::SelectionDAGISel::Select (SDNode * N) pure virtual
Select - Main hook targets implement to select a node.
References N.
SelectCodeCommon()
SDNode * SelectionDAGISel::SelectCodeCommon (SDNode * NodeToMatch, const unsigned char * MatcherTable, unsigned TableSize)
Definition at line 2490 of file SelectionDAGISel.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::ISD::BasicBlock, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::cast(), CheckAndImm(), CheckChildInteger(), CheckChildSame(), CheckChildType(), CheckComplexPattern(), CheckCondCode(), CheckInteger(), CheckNodePredicate(), CheckOpcode(), CheckOrImm(), CheckPatternPredicate(), CheckSame(), CheckType(), CheckValueType(), llvm::SmallVectorImpl< T >::clear(), ComplexPatternFuncMutatesDAG(), llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, CurDAG, llvm::dbgs(), DEBUG, llvm::ISD::DELETED_NODE, llvm::SDNode::dump(), llvm::ISD::EH_LABEL, llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ISD::EntryToken, llvm::SDValue::getNode(), getNumFixedFromVariadicInfo(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SDValue::getValueType(), GetVBR(), llvm::MVT::Glue, HandleMergeInputChains(), llvm::ISD::HANDLENODE, I, llvm::ISD::INLINEASM, llvm::MVT::iPTR, IsLegalToFold(), llvm::SDNode::isMachineOpcode(), IsPredicateKnownToFail(), IsProfitableToFold(), llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, llvm::ISD::MDNODE_SDNODE, MF, N, OPC_CaptureGlueInput, OPC_CheckAndImm, OPC_CheckChild0Integer, OPC_CheckChild0Same, OPC_CheckChild0Type, OPC_CheckChild1Integer, OPC_CheckChild1Same, OPC_CheckChild1Type, OPC_CheckChild2Integer, OPC_CheckChild2Same, OPC_CheckChild2Type, OPC_CheckChild3Integer, OPC_CheckChild3Same, OPC_CheckChild3Type, OPC_CheckChild4Integer, OPC_CheckChild4Type, OPC_CheckChild5Type, OPC_CheckChild6Type, OPC_CheckChild7Type, OPC_CheckComplexPat, OPC_CheckCondCode, OPC_CheckFoldableChainNode, OPC_CheckInteger, OPC_CheckOpcode, OPC_CheckOrImm, OPC_CheckPatternPredicate, OPC_CheckPredicate, OPC_CheckSame, OPC_CheckType, OPC_CheckValueType, OPC_CompleteMatch, OPC_EmitConvertToTarget, OPC_EmitCopyToReg, OPC_EmitInteger, OPC_EmitMergeInputChains, OPC_EmitMergeInputChains1_0, OPC_EmitMergeInputChains1_1, OPC_EmitNode, OPC_EmitNodeXForm, OPC_EmitRegister, OPC_EmitRegister2, OPC_MarkGlueResults, OPC_MorphNodeTo, OPC_MoveChild, OPC_MoveParent, OPC_RecordChild0, OPC_RecordChild1, OPC_RecordChild2, OPC_RecordChild3, OPC_RecordChild4, OPC_RecordChild5, OPC_RecordChild6, OPC_RecordChild7, OPC_RecordMemRef, OPC_RecordNode, OPC_Scope, OPC_SwitchOpcode, OPC_SwitchType, OPFL_Chain, OPFL_GlueInput, OPFL_GlueOutput, OPFL_MemRefs, OPFL_VariadicInfo, OptLevel, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::ISD::READ_REGISTER, llvm::ISD::Register, llvm::ISD::RegisterMask, llvm::SmallVectorImpl< T >::resize(), RunSDNodeXForm(), llvm::SDNode::setNodeId(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::ISD::TargetBlockAddress, llvm::ISD::TargetConstant, llvm::ISD::TargetConstantFP, llvm::ISD::TargetConstantPool, llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetFrameIndex, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, llvm::ISD::TargetJumpTable, TII, TLI, llvm::ISD::TokenFactor, llvm::ISD::UNDEF, llvm::SDNode::use_empty(), and llvm::ISD::WRITE_REGISTER.
SelectInlineAsmMemoryOperand()
virtual bool llvm::SelectionDAGISel::SelectInlineAsmMemoryOperand (const SDValue & Op, char ConstraintCode, std::vector< SDValue > & OutOps) inline virtual
SelectInlineAsmMemoryOperand - Select the specified address as a target addressing mode, according to the specified constraint code. If this does not match or is not implemented, return true. The resultant operands (which will appear in the machine instruction) should be added to the OutOps vector.
Definition at line 87 of file SelectionDAGISel.h.
Referenced by SelectInlineAsmMemoryOperands().
SelectInlineAsmMemoryOperands()
void SelectionDAGISel::SelectInlineAsmMemoryOperands (std::vector< SDValue > & Ops) protected
SelectInlineAsmMemoryOperands - Calls to this are automatically generated by tblgen. Others should not call it.
Definition at line 1683 of file SelectionDAGISel.cpp.
References llvm::cast(), CurDAG, llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MVT::Glue, llvm::MVT::i32, llvm::InlineAsm::isMemKind(), llvm::InlineAsm::Kind_Mem, llvm::InlineAsm::Op_AsmString, llvm::InlineAsm::Op_ExtraInfo, llvm::InlineAsm::Op_FirstOperand, llvm::InlineAsm::Op_InputChain, llvm::InlineAsm::Op_MDNode, llvm::report_fatal_error(), SelectInlineAsmMemoryOperand(), and std::swap().
Member Data Documentation
AA
AliasAnalysis* llvm::SelectionDAGISel::AA
Definition at line 51 of file SelectionDAGISel.h.
Referenced by llvm::createVLIWDAGScheduler(), and runOnMachineFunction().
CurDAG
SelectionDAG* llvm::SelectionDAGISel::CurDAG
Definition at line 49 of file SelectionDAGISel.h.
Referenced by CheckAndMask(), CheckOrMask(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), ReplaceUses(), ReplaceUses(), ReplaceUses(), runOnMachineFunction(), SelectCodeCommon(), SelectInlineAsmMemoryOperands(), SelectionDAGISel(), and ~SelectionDAGISel().
DAGSize
unsigned llvm::SelectionDAGISel::DAGSize protected
DAGSize - Size of DAG being instruction selected.
Definition at line 179 of file SelectionDAGISel.h.
Referenced by SelectionDAGISel().
FuncInfo
FunctionLoweringInfo* llvm::SelectionDAGISel::FuncInfo
Definition at line 46 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction(), SelectionDAGISel(), and ~SelectionDAGISel().
GFI
GCFunctionInfo* llvm::SelectionDAGISel::GFI
Definition at line 52 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction(), and SelectionDAGISel().
ID
char SelectionDAGISel::ID = 0 static
Definition at line 57 of file SelectionDAGISel.h.
Referenced by initializePassOnce(), initializePassOnce(), and SelectionDAGISel().
LibInfo
const TargetLibraryInfo* llvm::SelectionDAGISel::LibInfo
Definition at line 45 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
MF
MachineFunction* llvm::SelectionDAGISel::MF
Definition at line 47 of file SelectionDAGISel.h.
Referenced by llvm::createBURRListDAGScheduler(), llvm::createDAGLinearizer(), llvm::createDefaultScheduler(), llvm::createFastDAGScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createSourceListDAGScheduler(), llvm::createVLIWDAGScheduler(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::MipsDAGToDAGISel::runOnMachineFunction(), runOnMachineFunction(), and SelectCodeCommon().
OptLevel
CodeGenOpt::Level llvm::SelectionDAGISel::OptLevel
Definition at line 53 of file SelectionDAGISel.h.
Referenced by getAnalysisUsage(), IsLegalToFold(), IsProfitableToFold(), runOnMachineFunction(), SelectCodeCommon(), and SelectionDAGISel().
RegInfo
MachineRegisterInfo* llvm::SelectionDAGISel::RegInfo
Definition at line 48 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
SDB
SelectionDAGBuilder* llvm::SelectionDAGISel::SDB
Definition at line 50 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction(), SelectionDAGISel(), and ~SelectionDAGISel().
TII
const TargetInstrInfo* llvm::SelectionDAGISel::TII
Definition at line 54 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction(), and SelectCodeCommon().
TLI
const TargetLowering* llvm::SelectionDAGISel::TLI
Definition at line 55 of file SelectionDAGISel.h.
Referenced by llvm::createDefaultScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), getTargetLowering(), IsPredicateKnownToFail(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), runOnMachineFunction(), and SelectCodeCommon().
TM
TargetMachine& llvm::SelectionDAGISel::TM
Definition at line 44 of file SelectionDAGISel.h.
Referenced by llvm::Mips16DAGToDAGISel::Mips16DAGToDAGISel(), llvm::MipsDAGToDAGISel::MipsDAGToDAGISel(), llvm::MipsSEDAGToDAGISel::MipsSEDAGToDAGISel(), llvm::MipsDAGToDAGISel::runOnMachineFunction(), runOnMachineFunction(), and SelectionDAGISel().
The documentation for this class was generated from the following files:
SelectionDAGISel.h
SelectionDAGBuilder.cpp
SelectionDAGISel.cpp