LLVM: llvm::object::SymbolicFile Class Reference
LLVM API Documentation
llvm::object::SymbolicFile Class Reference abstract
#include <SymbolicFile.h>
Public Types
typedef iterator_range< basic_symbol_iterator > basic_symbol_iterator_range
Public Member Functions
virtual ~SymbolicFile ()
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
virtual void moveSymbolNext (DataRefImpl &Symb) const =0
virtual std::error_code printSymbolName (raw_ostream &OS, DataRefImpl Symb) const =0
virtual uint32_t getSymbolFlags (DataRefImpl Symb) const =0
virtual basic_symbol_iterator symbol_begin_impl () const =0
virtual basic_symbol_iterator symbol_end_impl () const =0
basic_symbol_iterator symbol_begin () const
basic_symbol_iterator symbol_end () const
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isIR () const
bool isLittleEndian () const
Static Public Member Functions
static ErrorOr< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, sys::fs::file_magic Type, LLVMContext *Context)
static ErrorOr< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static ErrorOr< OwningBinary< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_IR , ID_StartObjects ,
ID_COFF , ID_ELF32L , ID_ELF32B , ID_ELF64L ,
ID_ELF64B , ID_MachO32L , ID_MachO32B , ID_MachO64L ,
ID_MachO64B , ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 116 of file SymbolicFile.h.
Member Typedef Documentation
basic_symbol_iterator_range
typedef iterator_range<basic_symbol_iterator> llvm::object::SymbolicFile::basic_symbol_iterator_range
Definition at line 140 of file SymbolicFile.h.
Constructor & Destructor Documentation
~SymbolicFile()
SymbolicFile::~SymbolicFile () virtual
Definition at line 25 of file SymbolicFile.cpp.
SymbolicFile()
SymbolicFile::SymbolicFile (unsigned int Type, MemoryBufferRef Source)
Definition at line 22 of file SymbolicFile.cpp.
Referenced by llvm::object::IRObjectFile::IRObjectFile(), and llvm::object::ObjectFile::ObjectFile().
Member Function Documentation
classof()
bool llvm::object::SymbolicFile::classof (const Binary * v) inline static
Definition at line 157 of file SymbolicFile.h.
References llvm::object::Binary::isSymbolic().
createSymbolicFile() [1/3]
ErrorOr< std::unique_ptr< SymbolicFile > > llvm::object::SymbolicFile::createSymbolicFile (MemoryBufferRef Object) inline static
Definition at line 151 of file SymbolicFile.h.
References createSymbolicFile(), and llvm::sys::fs::file_magic::unknown.
createSymbolicFile() [2/3]
ErrorOr< std::unique_ptr< SymbolicFile > > SymbolicFile::createSymbolicFile (MemoryBufferRef Object, sys::fs::file_magic Type, LLVMContext * Context) static
Definition at line 27 of file SymbolicFile.cpp.
References llvm::sys::fs::file_magic::archive, llvm::sys::fs::file_magic::bitcode, llvm::sys::fs::file_magic::coff_import_library, llvm::sys::fs::file_magic::coff_object, llvm::object::IRObjectFile::create(), llvm::object::ObjectFile::createObjectFile(), llvm::object::Binary::Data, llvm::sys::fs::file_magic::elf, llvm::sys::fs::file_magic::elf_core, llvm::sys::fs::file_magic::elf_executable, llvm::sys::fs::file_magic::elf_relocatable, llvm::sys::fs::file_magic::elf_shared_object, llvm::object::IRObjectFile::findBitcodeInObject(), llvm::ErrorOr< T >::get(), llvm::MemoryBufferRef::getBuffer(), llvm::MemoryBufferRef::getBufferIdentifier(), llvm::sys::fs::identify_magic(), llvm::object::invalid_file_type, llvm_unreachable, llvm::sys::fs::file_magic::macho_bundle, llvm::sys::fs::file_magic::macho_core, llvm::sys::fs::file_magic::macho_dsym_companion, llvm::sys::fs::file_magic::macho_dynamic_linker, llvm::sys::fs::file_magic::macho_dynamically_linked_shared_lib, llvm::sys::fs::file_magic::macho_dynamically_linked_shared_lib_stub, llvm::sys::fs::file_magic::macho_executable, llvm::sys::fs::file_magic::macho_fixed_virtual_memory_shared_lib, llvm::sys::fs::file_magic::macho_object, llvm::sys::fs::file_magic::macho_preload_executable, llvm::sys::fs::file_magic::macho_universal_binary, llvm::sys::fs::file_magic::pecoff_executable, llvm::sys::fs::file_magic::unknown, and llvm::sys::fs::file_magic::windows_resource.
Referenced by llvm::object::createBinary(), and createSymbolicFile().
createSymbolicFile() [3/3]
ErrorOr< OwningBinary< SymbolicFile > > llvm::object::SymbolicFile::createSymbolicFile (StringRef ObjectPath) static
getSymbolFlags()
virtual uint32_t llvm::object::SymbolicFile::getSymbolFlags (DataRefImpl Symb) const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, llvm::object::IRObjectFile, and llvm::object::MachOObjectFile.
moveSymbolNext()
virtual void llvm::object::SymbolicFile::moveSymbolNext (DataRefImpl & Symb) const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, llvm::object::IRObjectFile, and llvm::object::MachOObjectFile.
printSymbolName()
virtual std::error_code llvm::object::SymbolicFile::printSymbolName (raw_ostream & OS, DataRefImpl Symb) const pure virtual
Implemented in llvm::object::IRObjectFile, and llvm::object::ObjectFile.
symbol_begin()
basic_symbol_iterator llvm::object::SymbolicFile::symbol_begin () const inline
Definition at line 134 of file SymbolicFile.h.
References symbol_begin_impl().
Referenced by llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::RuntimeDyldImpl::loadObjectImpl(), printRelocationTargetName(), llvm::object::ObjectFile::symbols(), and symbols().
symbol_begin_impl()
virtual basic_symbol_iterator llvm::object::SymbolicFile::symbol_begin_impl () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, llvm::object::IRObjectFile, and llvm::object::MachOObjectFile.
Referenced by symbol_begin().
symbol_end()
basic_symbol_iterator llvm::object::SymbolicFile::symbol_end () const inline
Definition at line 137 of file SymbolicFile.h.
References symbol_end_impl().
Referenced by llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::object::COFFObjectFile::getRelocationSymbol(), llvm::object::ELFObjectFile< ELFT >::getRelocationSymbol(), llvm::object::MachOObjectFile::getRelocationSymbol(), llvm::RuntimeDyldImpl::loadObjectImpl(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::object::ObjectFile::symbols(), and symbols().
symbol_end_impl()
virtual basic_symbol_iterator llvm::object::SymbolicFile::symbol_end_impl () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, llvm::object::IRObjectFile, and llvm::object::MachOObjectFile.
Referenced by symbol_end().
symbols()
basic_symbol_iterator_range llvm::object::SymbolicFile::symbols () const inline
Definition at line 141 of file SymbolicFile.h.
References symbol_begin(), and symbol_end().
The documentation for this class was generated from the following files:
SymbolicFile.h
SymbolicFile.cpp