LLVM: llvm::InstCombiner Class Reference
LLVM API Documentation
llvm::InstCombiner Class Reference
InstCombiner - The -instcombine pass.
#include <InstCombine.h>
Public Types
typedef IRBuilder< true, TargetFolder, InstCombineIRInserter > BuilderTy
Public Member Functions
InstCombiner ()
bool runOnFunction (Function &F) override
bool DoOneIteration (Function &F, unsigned ItNum)
void getAnalysisUsage (AnalysisUsage &AU) const override
AssumptionCache * getAssumptionCache () const
const DataLayout * getDataLayout () const
DominatorTree * getDominatorTree () const
TargetLibraryInfo * getTargetLibraryInfo () const
Instruction * visitAdd (BinaryOperator &I)
Instruction * visitFAdd (BinaryOperator &I)
Value * OptimizePointerDifference (Value *LHS, Value *RHS, Type *Ty)
Instruction * visitSub (BinaryOperator &I)
Instruction * visitFSub (BinaryOperator &I)
Instruction * visitMul (BinaryOperator &I)
Value * foldFMulConst (Instruction *FMulOrDiv, Constant *C, Instruction *InsertBefore)
Instruction * visitFMul (BinaryOperator &I)
Instruction * visitURem (BinaryOperator &I)
Instruction * visitSRem (BinaryOperator &I)
Instruction * visitFRem (BinaryOperator &I)
bool SimplifyDivRemOfSelect (BinaryOperator &I)
Instruction * commonRemTransforms (BinaryOperator &I)
Instruction * commonIRemTransforms (BinaryOperator &I)
Common integer remainder transforms.
Instruction * commonDivTransforms (BinaryOperator &I)
Instruction * commonIDivTransforms (BinaryOperator &I)
Common integer divide transforms.
Instruction * visitUDiv (BinaryOperator &I)
Instruction * visitSDiv (BinaryOperator &I)
Instruction * visitFDiv (BinaryOperator &I)
Value * simplifyRangeCheck (ICmpInst *Cmp0, ICmpInst *Cmp1, bool Inverted)
Value * FoldAndOfICmps (ICmpInst *LHS, ICmpInst *RHS)
FoldAndOfICmps - Fold (icmp)&(icmp) if possible.
Value * FoldAndOfFCmps (FCmpInst *LHS, FCmpInst *RHS)
Instruction * visitAnd (BinaryOperator &I)
Value * FoldOrOfICmps (ICmpInst *LHS, ICmpInst *RHS, Instruction *CxtI)
FoldOrOfICmps - Fold (icmp)|(icmp) if possible.
Value * FoldOrOfFCmps (FCmpInst *LHS, FCmpInst *RHS)
Instruction * FoldOrWithConstants (BinaryOperator &I, Value *Op, Value *A, Value *B, Value *C)
Instruction * FoldXorWithConstants (BinaryOperator &I, Value *Op, Value *A, Value *B, Value *C)
This helper function folds:
Instruction * visitOr (BinaryOperator &I)
Instruction * visitXor (BinaryOperator &I)
Instruction * visitShl (BinaryOperator &I)
Instruction * visitAShr (BinaryOperator &I)
Instruction * visitLShr (BinaryOperator &I)
Instruction * commonShiftTransforms (BinaryOperator &I)
Instruction * FoldFCmp_IntToFP_Cst (FCmpInst &I, Instruction *LHSI, Constant *RHSC)
FoldFCmp_IntToFP_Cst - Fold fcmp ([us]itofp x, cst) if possible.
Instruction * FoldCmpLoadFromIndexedGlobal (GetElementPtrInst *GEP, GlobalVariable *GV, CmpInst &ICI, ConstantInt *AndCst=nullptr)
Instruction * visitFCmpInst (FCmpInst &I)
Instruction * visitICmpInst (ICmpInst &I)
Instruction * visitICmpInstWithCastAndCast (ICmpInst &ICI)
Instruction * visitICmpInstWithInstAndIntCst (ICmpInst &ICI, Instruction *LHS, ConstantInt *RHS)
Instruction * FoldICmpDivCst (ICmpInst &ICI, BinaryOperator *DivI, ConstantInt *DivRHS)
Instruction * FoldICmpShrCst (ICmpInst &ICI, BinaryOperator *DivI, ConstantInt *DivRHS)
FoldICmpShrCst - Handle "icmp(([al]shr X, cst1), cst2)".
Instruction * FoldICmpCstShrCst (ICmpInst &I, Value *Op, Value *A, ConstantInt *CI1, ConstantInt *CI2)
Instruction * FoldICmpCstShlCst (ICmpInst &I, Value *Op, Value *A, ConstantInt *CI1, ConstantInt *CI2)
Instruction * FoldICmpAddOpCst (Instruction &ICI, Value *X, ConstantInt *CI, ICmpInst::Predicate Pred)
FoldICmpAddOpCst - Fold "icmp pred (X+CI), X".
Instruction * FoldGEPICmp (GEPOperator *GEPLHS, Value *RHS, ICmpInst::Predicate Cond, Instruction &I)
Instruction * FoldShiftByConstant (Value *Op0, Constant *Op1, BinaryOperator &I)
Instruction * commonCastTransforms (CastInst &CI)
Implement the transforms common to all CastInst visitors.
Instruction * commonPointerCastTransforms (CastInst &CI)
Implement the transforms for cast of pointer (bitcast/ptrtoint)
Instruction * visitTrunc (TruncInst &CI)
Instruction * visitZExt (ZExtInst &CI)
Instruction * visitSExt (SExtInst &CI)
Instruction * visitFPTrunc (FPTruncInst &CI)
Instruction * visitFPExt (CastInst &CI)
Instruction * visitFPToUI (FPToUIInst &FI)
Instruction * visitFPToSI (FPToSIInst &FI)
Instruction * visitUIToFP (CastInst &CI)
Instruction * visitSIToFP (CastInst &CI)
Instruction * visitPtrToInt (PtrToIntInst &CI)
Instruction * visitIntToPtr (IntToPtrInst &CI)
Instruction * visitBitCast (BitCastInst &CI)
Instruction * visitAddrSpaceCast (AddrSpaceCastInst &CI)
Instruction * FoldSelectOpOp (SelectInst &SI, Instruction *TI, Instruction *FI)
Instruction * FoldSelectIntoOp (SelectInst &SI, Value *, Value *)
Instruction * FoldSPFofSPF (Instruction *Inner, SelectPatternFlavor SPF1, Value *A, Value *B, Instruction &Outer, SelectPatternFlavor SPF2, Value *C)
Instruction * visitSelectInst (SelectInst &SI)
Instruction * visitSelectInstWithICmp (SelectInst &SI, ICmpInst *ICI)
Instruction * visitCallInst (CallInst &CI)
Instruction * visitInvokeInst (InvokeInst &II)
Instruction * SliceUpIllegalIntegerPHI (PHINode &PN)
Instruction * visitPHINode (PHINode &PN)
Instruction * visitGetElementPtrInst (GetElementPtrInst &GEP)
Instruction * visitAllocaInst (AllocaInst &AI)
Instruction * visitAllocSite (Instruction &FI)
Instruction * visitFree (CallInst &FI)
Instruction * visitLoadInst (LoadInst &LI)
Instruction * visitStoreInst (StoreInst &SI)
Instruction * visitBranchInst (BranchInst &BI)
Instruction * visitSwitchInst (SwitchInst &SI)
Instruction * visitReturnInst (ReturnInst &RI)
Instruction * visitInsertValueInst (InsertValueInst &IV)
Instruction * visitInsertElementInst (InsertElementInst &IE)
Instruction * visitExtractElementInst (ExtractElementInst &EI)
Instruction * visitShuffleVectorInst (ShuffleVectorInst &SVI)
Instruction * visitExtractValueInst (ExtractValueInst &EV)
Instruction * visitLandingPadInst (LandingPadInst &LI)
Instruction * visitInstruction (Instruction &I)
bool dominatesAllUses (const Instruction *DI, const Instruction *UI, const BasicBlock *DB) const
Check that one use is in the same block as the definition and all other uses are in blocks dominated by a given block.
bool replacedSelectWithOperand (SelectInst *SI, const ICmpInst *Icmp, const unsigned SIOpd)
True when a select result is replaced by one of its operands in select-icmp sequence. This will eventually result in the elimination of the select.
Instruction * InsertNewInstBefore (Instruction *New, Instruction &Old)
Instruction * InsertNewInstWith (Instruction *New, Instruction &Old)
Instruction * ReplaceInstUsesWith (Instruction &I, Value *V)
Instruction * CreateOverflowTuple (IntrinsicInst *II, Value *Result, bool Overflow, bool ReUseName=true)
Instruction * EraseInstFromFunction (Instruction &I)
void computeKnownBits (Value *V, APInt &KnownZero, APInt &KnownOne, unsigned Depth=0, Instruction *CxtI=nullptr) const
bool MaskedValueIsZero (Value *V, const APInt &Mask, unsigned Depth=0, Instruction *CxtI=nullptr) const
unsigned ComputeNumSignBits (Value *Op, unsigned Depth=0, Instruction *CxtI=nullptr) const
void ComputeSignBit (Value *V, bool &KnownZero, bool &KnownOne, unsigned Depth=0, Instruction *CxtI=nullptr) const
OverflowResult computeOverflowForUnsignedMul (Value *LHS, Value *RHS, const Instruction *CxtI)
OverflowResult computeOverflowForUnsignedAdd (Value *LHS, Value *RHS, const Instruction *CxtI)
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Member Functions inherited from llvm::InstVisitor< InstCombiner, Instruction * >
void visit (Iterator Start, Iterator End)
void visitModule (Module &M)
void visitFunction (Function &F)
void visitBasicBlock (BasicBlock &BB)
Instruction * visitReturnInst (ReturnInst &I)
Instruction * visitBranchInst (BranchInst &I)
Instruction * visitSwitchInst (SwitchInst &I)
Instruction * visitIndirectBrInst (IndirectBrInst &I)
Instruction * visitResumeInst (ResumeInst &I)
Instruction * visitUnreachableInst (UnreachableInst &I)
Instruction * visitICmpInst (ICmpInst &I)
Instruction * visitFCmpInst (FCmpInst &I)
Instruction * visitAllocaInst (AllocaInst &I)
Instruction * visitLoadInst (LoadInst &I)
Instruction * visitStoreInst (StoreInst &I)
Instruction * visitAtomicCmpXchgInst (AtomicCmpXchgInst &I)
Instruction * visitAtomicRMWInst (AtomicRMWInst &I)
Instruction * visitFenceInst (FenceInst &I)
Instruction * visitGetElementPtrInst (GetElementPtrInst &I)
Instruction * visitPHINode (PHINode &I)
Instruction * visitTruncInst (TruncInst &I)
Instruction * visitZExtInst (ZExtInst &I)
Instruction * visitSExtInst (SExtInst &I)
Instruction * visitFPTruncInst (FPTruncInst &I)
Instruction * visitFPExtInst (FPExtInst &I)
Instruction * visitFPToUIInst (FPToUIInst &I)
Instruction * visitFPToSIInst (FPToSIInst &I)
Instruction * visitUIToFPInst (UIToFPInst &I)
Instruction * visitSIToFPInst (SIToFPInst &I)
Instruction * visitPtrToIntInst (PtrToIntInst &I)
Instruction * visitIntToPtrInst (IntToPtrInst &I)
Instruction * visitBitCastInst (BitCastInst &I)
Instruction * visitAddrSpaceCastInst (AddrSpaceCastInst &I)
Instruction * visitSelectInst (SelectInst &I)
Instruction * visitVAArgInst (VAArgInst &I)
Instruction * visitExtractElementInst (ExtractElementInst &I)
Instruction * visitInsertElementInst (InsertElementInst &I)
Instruction * visitShuffleVectorInst (ShuffleVectorInst &I)
Instruction * visitExtractValueInst (ExtractValueInst &I)
Instruction * visitInsertValueInst (InsertValueInst &I)
Instruction * visitLandingPadInst (LandingPadInst &I)
Instruction * visitDbgDeclareInst (DbgDeclareInst &I)
Instruction * visitDbgValueInst (DbgValueInst &I)
Instruction * visitDbgInfoIntrinsic (DbgInfoIntrinsic &I)
Instruction * visitMemSetInst (MemSetInst &I)
Instruction * visitMemCpyInst (MemCpyInst &I)
Instruction * visitMemMoveInst (MemMoveInst &I)
Instruction * visitMemTransferInst (MemTransferInst &I)
Instruction * visitMemIntrinsic (MemIntrinsic &I)
Instruction * visitVAStartInst (VAStartInst &I)
Instruction * visitVAEndInst (VAEndInst &I)
Instruction * visitVACopyInst (VACopyInst &I)
Instruction * visitIntrinsicInst (IntrinsicInst &I)
Instruction * visitCallInst (CallInst &I)
Instruction * visitInvokeInst (InvokeInst &I)
Instruction * visitCastInst (CastInst &I)
Instruction * visitBinaryOperator (BinaryOperator &I)
Instruction * visitCmpInst (CmpInst &I)
Instruction * visitTerminatorInst (TerminatorInst &I)
Instruction * visitUnaryInstruction (UnaryInstruction &I)
Instruction * visitCallSite (CallSite CS)
void visitInstruction (Instruction &I)
Public Attributes
InstCombineWorklist Worklist
Worklist - All of the instructions that need to be simplified.
BuilderTy * Builder
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
InstCombiner - The -instcombine pass.
Definition at line 96 of file InstCombine.h.
Member Typedef Documentation
BuilderTy
typedef IRBuilder<true, TargetFolder, InstCombineIRInserter> llvm::InstCombiner::BuilderTy
Builder - This is an IRBuilder that automatically inserts new instructions into the worklist when they are created.
Definition at line 113 of file InstCombine.h.
Constructor & Destructor Documentation
InstCombiner()
llvm::InstCombiner::InstCombiner () inline
Definition at line 117 of file InstCombine.h.
References Builder, llvm::FunctionPass::FunctionPass(), llvm::PassRegistry::getPassRegistry(), ID, and llvm::initializeInstCombinerPass().
Referenced by getAnalysisUsage().
Member Function Documentation
commonCastTransforms()
Instruction * InstCombiner::commonCastTransforms (CastInst & CI)
Implement the transforms common to all CastInst visitors.
Definition at line 294 of file InstCombineCasts.cpp.
References llvm::CastInst::Create(), llvm::dyn_cast(), llvm::CastInst::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::isa(), isEliminableCastPair(), and llvm::Type::isIntegerTy().
Referenced by commonDivTransforms(), commonPointerCastTransforms(), visitBitCast(), visitFPExt(), visitFPToSI(), visitFPToUI(), visitFPTrunc(), visitIntToPtr(), visitSExt(), visitSIToFP(), visitTrunc(), visitUIToFP(), and visitZExt().
commonDivTransforms()
Instruction * llvm::InstCombiner::commonDivTransforms (BinaryOperator & I)
References commonCastTransforms(), commonIDivTransforms(), commonPointerCastTransforms(), commonShiftTransforms(), FoldAndOfFCmps(), FoldAndOfICmps(), FoldCmpLoadFromIndexedGlobal(), FoldFCmp_IntToFP_Cst(), FoldGEPICmp(), FoldICmpAddOpCst(), FoldICmpCstShlCst(), FoldICmpCstShrCst(), FoldICmpDivCst(), FoldICmpShrCst(), FoldOrOfFCmps(), FoldOrOfICmps(), FoldOrWithConstants(), FoldSelectIntoOp(), FoldSelectOpOp(), FoldShiftByConstant(), FoldSPFofSPF(), FoldXorWithConstants(), I, simplifyRangeCheck(), SliceUpIllegalIntegerPHI(), visitAddrSpaceCast(), visitAllocaInst(), visitAllocSite(), visitAnd(), visitAShr(), visitBitCast(), visitBranchInst(), visitCallInst(), visitExtractElementInst(), visitExtractValueInst(), visitFCmpInst(), visitFDiv(), visitFPExt(), visitFPToSI(), visitFPToUI(), visitFPTrunc(), visitFree(), visitGetElementPtrInst(), visitICmpInst(), visitICmpInstWithCastAndCast(), visitICmpInstWithInstAndIntCst(), visitInsertElementInst(), visitInsertValueInst(), visitIntToPtr(), visitInvokeInst(), visitLandingPadInst(), visitLoadInst(), visitLShr(), visitOr(), visitPHINode(), visitPtrToInt(), visitReturnInst(), visitSDiv(), visitSelectInst(), visitSelectInstWithICmp(), visitSExt(), visitShl(), visitShuffleVectorInst(), visitSIToFP(), visitStoreInst(), visitSwitchInst(), visitTrunc(), visitUDiv(), visitUIToFP(), visitXor(), visitZExt(), and llvm::X.
commonIDivTransforms()
Instruction * InstCombiner::commonIDivTransforms (BinaryOperator & I)
Common integer divide transforms.
This function implements the transforms common to both integer division instructions (udiv and sdiv). It is called by the visitors to those integer division instructions.
Definition at line 779 of file InstCombineMulDivRem.cpp.
References Builder, llvm::cast(), llvm::BinaryOperator::Create(), llvm::SelectInst::Create(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::APInt::getBitWidth(), llvm::APInt::getLimitedValue(), llvm::APInt::getOneBitSet(), I, llvm::isa(), IsMultiple(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_NSWMul(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_NUWMul(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), MultiplyOverflows(), llvm::BinaryOperator::setHasNoSignedWrap(), llvm::BinaryOperator::setHasNoUnsignedWrap(), llvm::BinaryOperator::setIsExact(), SimplifyDivRemOfSelect(), simplifyValueKnownNonZero(), and llvm::X.
Referenced by commonDivTransforms(), visitSDiv(), and visitUDiv().
commonIRemTransforms()
Instruction * InstCombiner::commonIRemTransforms (BinaryOperator & I)
Common integer remainder transforms.
This function implements the transforms common to both integer remainder instructions (urem and srem). It is called by the visitors to those integer remainder instructions.
Definition at line 1336 of file InstCombineMulDivRem.cpp.
References llvm::dyn_cast(), I, llvm::isa(), SimplifyDivRemOfSelect(), and simplifyValueKnownNonZero().
Referenced by commonRemTransforms(), visitSRem(), and visitURem().
commonPointerCastTransforms()
Instruction * InstCombiner::commonPointerCastTransforms (CastInst & CI)
Implement the transforms for cast of pointer (bitcast/ptrtoint)
Definition at line 1408 of file InstCombineCasts.cpp.
References Builder, llvm::cast(), commonCastTransforms(), llvm::dyn_cast(), llvm::User::getOperand(), llvm::APInt::getSExtValue(), llvm::Value::getType(), llvm::isa(), llvm::User::setOperand(), llvm::Value::takeName(), and Worklist.
Referenced by commonDivTransforms(), visitAddrSpaceCast(), visitBitCast(), and visitPtrToInt().
commonRemTransforms()
Instruction * llvm::InstCombiner::commonRemTransforms (BinaryOperator & I)
References commonIRemTransforms(), and I.
commonShiftTransforms()
Instruction * InstCombiner::commonShiftTransforms (BinaryOperator & I)
Definition at line 24 of file InstCombineShifts.cpp.
References Builder, commonShiftTransforms(), llvm::dyn_cast(), FoldShiftByConstant(), llvm::ConstantInt::get(), I, llvm::isa(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by commonDivTransforms(), commonShiftTransforms(), visitAShr(), visitLShr(), and visitShl().
computeKnownBits()
void llvm::InstCombiner::computeKnownBits (Value * V, APInt & KnownZero, APInt & KnownOne, unsigned Depth = 0, Instruction * CxtI = nullptr) const inline
Definition at line 369 of file InstCombine.h.
References llvm::computeKnownBits().
Referenced by visitCallInst(), visitICmpInstWithInstAndIntCst(), visitReturnInst(), and visitSwitchInst().
ComputeNumSignBits()
unsigned llvm::InstCombiner::ComputeNumSignBits (Value * Op, unsigned Depth = 0, Instruction * CxtI = nullptr) const inline
Definition at line 380 of file InstCombine.h.
References llvm::ComputeNumSignBits().
Referenced by ProcessUGT_ADDCST_ADD(), visitSExt(), and visitShl().
computeOverflowForUnsignedAdd()
OverflowResult llvm::InstCombiner::computeOverflowForUnsignedAdd (Value * LHS, Value * RHS, const Instruction * CxtI) inline
Definition at line 393 of file InstCombine.h.
References llvm::computeOverflowForUnsignedAdd().
Referenced by visitAdd(), and visitCallInst().
computeOverflowForUnsignedMul()
OverflowResult llvm::InstCombiner::computeOverflowForUnsignedMul (Value * LHS, Value * RHS, const Instruction * CxtI) inline
Definition at line 389 of file InstCombine.h.
References llvm::computeOverflowForUnsignedMul().
Referenced by visitCallInst(), and visitMul().
ComputeSignBit()
void llvm::InstCombiner::ComputeSignBit (Value * V, bool & KnownZero, bool & KnownOne, unsigned Depth = 0, Instruction * CxtI = nullptr) const inline
Definition at line 384 of file InstCombine.h.
References llvm::ComputeSignBit().
Referenced by simplifyRangeCheck().
CreateOverflowTuple()
Instruction * llvm::InstCombiner::CreateOverflowTuple (IntrinsicInst * II, Value * Result, bool Overflow, bool ReUseName = true) inline
Creates a result tuple for an overflow intrinsic II with a given Result and a constant Overflow value. If ReUseName is true the Result's name is taken from II.
Definition at line 337 of file InstCombine.h.
References Builder, llvm::cast(), llvm::InsertValueInst::Create(), llvm::ConstantStruct::get(), llvm::UndefValue::get(), llvm::Value::getType(), and llvm::Value::takeName().
Referenced by visitCallInst().
dominatesAllUses()
bool InstCombiner::dominatesAllUses (const Instruction * DI, const Instruction * UI, const BasicBlock * DB) const
Check that one use is in the same block as the definition and all other uses are in blocks dominated by a given block.
Parameters
DI Definition
UI Use
DB Block that must dominate all uses of DI outside the parent block
Returns
true when UI is the only use of DI in the parent block and all other uses of DI are in blocks dominated by DB.
Definition at line 2469 of file InstCombineCompares.cpp.
References llvm::cast(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), and llvm::Value::users().
Referenced by replacedSelectWithOperand().
DoOneIteration()
bool InstCombiner::DoOneIteration (Function & F, unsigned ItNum)
Definition at line 2779 of file InstructionCombining.cpp.
References AddReachableCodeToWorklist(), Builder, llvm::cast(), llvm::ConstantFoldInstruction(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), EraseInstFromFunction(), F, llvm::UndefValue::get(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingBlock(), llvm::BasicBlock::getInstList(), llvm::Instruction::getParent(), llvm::BasicBlock::getSinglePredecessor(), llvm::Value::getType(), I, llvm::iplist< NodeTy, Traits >::insert(), llvm::isa(), llvm::isInstructionTriviallyDead(), llvm::Value::replaceAllUsesWith(), ReplaceInstUsesWith(), llvm::succ_begin(), llvm::succ_end(), TryToSinkInstruction(), llvm::Value::use_empty(), llvm::InstVisitor< InstCombiner, Instruction * >::visit(), and Worklist.
Referenced by runOnFunction().
EraseInstFromFunction()
Instruction * llvm::InstCombiner::EraseInstFromFunction (Instruction & I) inline
Definition at line 352 of file InstCombine.h.
References llvm::dbgs(), DEBUG, llvm::dyn_cast(), I, and Worklist.
Referenced by combineLoadToOperationType(), DoOneIteration(), visitAllocaInst(), visitAllocSite(), visitCallInst(), visitExtractValueInst(), visitFree(), and visitStoreInst().
FoldAndOfFCmps()
Value * InstCombiner::FoldAndOfFCmps (FCmpInst * LHS, FCmpInst * RHS)
FoldAndOfFCmps - Optimize (fcmp)&(fcmp). NOTE: Unlike the rest of instcombine, this returns a Value which should already be inserted into the function.
Definition at line 1146 of file InstCombineAndOrXor.cpp.
References Builder, llvm::dyn_cast(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::ConstantInt::get(), getFCmpCode(), getFCmpValue(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::isa(), llvm::CmpInst::makeCmpResultType(), and std::swap().
Referenced by commonDivTransforms(), and visitAnd().
FoldAndOfICmps()
Value * InstCombiner::FoldAndOfICmps (ICmpInst * LHS, ICmpInst * RHS)
FoldAndOfICmps - Fold (icmp)&(icmp) if possible.
Definition at line 900 of file InstCombineAndOrXor.cpp.
References llvm::Add, llvm::AddOne(), Builder, llvm::dyn_cast(), foldLogOpOfMaskedICmps(), llvm::ConstantInt::get(), llvm::IntegerType::getBitWidth(), llvm::Type::getContext(), llvm::getICmpCode(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::ConstantExpr::getNeg(), getNewICmpValue(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ConstantRange::intersectWith(), llvm::APInt::isAllOnesValue(), llvm::ConstantRange::isEmptySet(), llvm::ICmpInst::isEquality(), llvm::Constant::isNullValue(), llvm::APInt::isPowerOf2(), llvm::CmpInst::isSigned(), llvm::ConstantInt::isZero(), llvm_unreachable, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::CmpInst::makeCmpResultType(), llvm::ConstantRange::makeICmpRegion(), llvm::PatternMatch::match(), N, llvm::PredicatesFoldable(), llvm::APInt::sgt(), simplifyRangeCheck(), llvm::SubOne(), std::swap(), llvm::ICmpInst::swapOperands(), llvm::APInt::ugt(), and llvm::APInt::zext().
Referenced by commonDivTransforms(), and visitAnd().
FoldCmpLoadFromIndexedGlobal()
Instruction * InstCombiner::FoldCmpLoadFromIndexedGlobal (GetElementPtrInst * GEP, GlobalVariable * GV, CmpInst & ICI, ConstantInt * AndCst = nullptr)
FoldCmpLoadFromIndexedGlobal - Called we see this pattern: cmp pred (load (gep GV, ...)), cmpcst where GV is a global variable with a constant initializer. Try to simplify this into some simple computation that does not need the load. For example we can optimize "icmp eq (load (gep "foo", 0, i)), 0" into "icmp eq i, 3".
If AndCst is non-null, then the loaded value is masked with that constant before doing the comparison. This handles cases like "A[i]&4 == 0".
TrueRangeEnd/FalseRangeEnd - In conjunction with First*Element, these define a state machine that triggers for ranges of values that the index is true or false for. This triggers on things like "abbbbc"[i] == 'b'. This is -2 when undefined, -3 when overdefined, and otherwise the last index in the range (inclusive). We use -2 for undefined here because we use relative comparisons and don't want 0-1 to match -1.
Definition at line 229 of file InstCombineCompares.cpp.
References Builder, llvm::cast(), llvm::ConstantFoldCompareInstOperands(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::ConstantInt::get(), llvm::ConstantExpr::getAnd(), llvm::ConstantExpr::getExtractValue(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::Type::getIntegerBitWidth(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getPrimitiveSizeInBits(), llvm::GetElementPtrInst::getType(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::GetElementPtrInst::isInBounds(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and ReplaceInstUsesWith().
Referenced by commonDivTransforms(), visitFCmpInst(), visitICmpInst(), and visitICmpInstWithInstAndIntCst().
FoldFCmp_IntToFP_Cst()
Instruction * InstCombiner::FoldFCmp_IntToFP_Cst (FCmpInst & I, Instruction * LHSI, Constant * RHSC)
FoldFCmp_IntToFP_Cst - Fold fcmp ([us]itofp x, cst) if possible.
Definition at line 3619 of file InstCombineCompares.cpp.
References Builder, llvm::cast(), llvm::APFloat::cmpEqual, llvm::APFloat::cmpGreaterThan, llvm::APFloat::cmpLessThan, llvm::APFloat::compare(), llvm::APFloat::convertFromAPInt(), llvm::APFloat::convertToInteger(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::Type::getFPMantissaWidth(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::User::getOperand(), llvm::APFloat::getSemantics(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::ConstantExpr::getSIToFP(), llvm::Value::getType(), llvm::ConstantExpr::getUIToFP(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::APFloat::isNaN(), llvm::APFloat::isNegative(), llvm::APFloat::isPosZero(), llvm::APFloat::isZero(), llvm_unreachable, P, ReplaceInstUsesWith(), llvm::APFloat::rmNearestTiesToEven, and llvm::APFloat::roundToIntegral().
Referenced by commonDivTransforms(), and visitFCmpInst().
foldFMulConst()
Value * InstCombiner::foldFMulConst (Instruction * FMulOrDiv, Constant * C, Instruction * InsertBefore)
foldFMulConst() is a helper routine of InstCombiner::visitFMul(). The input FMulOrDiv is a FMul/FDiv with one and only one operand being a constant (i.e. isFMulOrFDivWithConstant(FMulOrDiv) == true). This function is to simplify "FMulOrDiv * C" and returns the resulting expression. Note that this function could return NULL in case the constants cannot be folded into a normal floating-point.
Definition at line 475 of file InstCombineMulDivRem.cpp.
References llvm::dyn_cast(), F, llvm::ConstantExpr::getFDiv(), llvm::ConstantExpr::getFMul(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Value::hasOneUse(), InsertNewInstWith(), isFMulOrFDivWithConstant(), isNormalFp(), and llvm::Instruction::setHasUnsafeAlgebra().
Referenced by visitFMul().
FoldGEPICmp()
Instruction * InstCombiner::FoldGEPICmp (GEPOperator * GEPLHS, Value * RHS, ICmpInst::Predicate Cond, Instruction & I)
FoldGEPICmp - Fold comparisons between a GEP instruction and something else. At this point we know that the GEP is on the LHS of the comparison.
Definition at line 614 of file InstCombineCompares.cpp.
References Builder, llvm::dyn_cast(), EvaluateGEPOffsetExpression(), FoldGEPICmp(), llvm::Constant::getNullValue(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::ICmpInst::getSignedPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::GEPOperator::hasAllConstantIndices(), llvm::GEPOperator::hasAllZeroIndices(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::GEPOperator::isInBounds(), llvm::CmpInst::isSigned(), llvm::CmpInst::isTrueWhenEqual(), ReplaceInstUsesWith(), and llvm::Value::stripPointerCasts().
Referenced by commonDivTransforms(), FoldGEPICmp(), and visitICmpInst().
FoldICmpAddOpCst()
Instruction * InstCombiner::FoldICmpAddOpCst (Instruction & ICI, Value * X, ConstantInt * CI, ICmpInst::Predicate Pred)
FoldICmpAddOpCst - Fold "icmp pred (X+CI), X".
Definition at line 750 of file InstCombineCompares.cpp.
References Builder, llvm::ConstantInt::get(), llvm::Constant::getAllOnesValue(), llvm::ConstantExpr::getNeg(), llvm::Type::getPrimitiveSizeInBits(), llvm::APInt::getSignedMaxValue(), llvm::ConstantExpr::getSub(), llvm::ConstantInt::getType(), llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm::X.
Referenced by commonDivTransforms(), and visitICmpInst().
FoldICmpCstShlCst()
Instruction * InstCombiner::FoldICmpCstShlCst (ICmpInst & I, Value * Op, Value * A, ConstantInt * CI1, ConstantInt * CI2)
FoldICmpCstShlCst - Handle "(icmp eq/ne (shl const2, A), const1)" -> (icmp eq/ne A, TrailingZeros(const1) - TrailingZeros(const2)).
Definition at line 1105 of file InstCombineCompares.cpp.
References llvm::APInt::countTrailingZeros(), llvm::ConstantInt::get(), llvm::APInt::getBitWidth(), llvm::CmpInst::getInversePredicate(), llvm::Constant::getNullValue(), llvm::ConstantInt::getValue(), I, ReplaceInstUsesWith(), and llvm::APInt::shl().
Referenced by commonDivTransforms(), and visitICmpInst().
FoldICmpCstShrCst()
Instruction * InstCombiner::FoldICmpCstShrCst (ICmpInst & I, Value * Op, Value * A, ConstantInt * CI1, ConstantInt * CI2)
FoldICmpCstShrCst - Handle "(icmp eq/ne (ashr/lshr const2, A), const1)" -> (icmp eq/ne A, Log2(const2/const1)) -> (icmp eq/ne A, Log2(const2) - Log2(const1)).
Definition at line 1045 of file InstCombineCompares.cpp.
References llvm::APInt::ashr(), llvm::ConstantInt::get(), llvm::CmpInst::getInversePredicate(), llvm::Constant::getNullValue(), llvm::ConstantInt::getValue(), I, llvm::isa(), llvm::APInt::isAllOnesValue(), llvm::APInt::isNegative(), llvm::APInt::logBase2(), llvm::APInt::lshr(), ReplaceInstUsesWith(), and llvm::APInt::sgt().
Referenced by commonDivTransforms(), and visitICmpInst().
FoldICmpDivCst()
Instruction * InstCombiner::FoldICmpDivCst (ICmpInst & ICI, BinaryOperator * DivI, ConstantInt * DivRHS)
FoldICmpDivCst - Fold "icmp pred, ([su]div X, DivRHS), CmpRHS" where DivRHS and CmpRHS are both known to be integer constants.
If the division is known to be exact, then there is no remainder from the divide, so the covered range size is unit, otherwise it is the divisor.
Definition at line 799 of file InstCombineCompares.cpp.
References llvm::AddOne(), AddWithOverflow(), Builder, llvm::cast(), llvm::ConstantExpr::getMul(), llvm::ConstantExpr::getNeg(), getOne(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::ConstantExpr::getSDiv(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantExpr::getUDiv(), llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::Constant::isAllOnesValue(), llvm::ICmpInst::isEquality(), llvm::BinaryOperator::isExact(), llvm::ConstantInt::isNegative(), llvm::ConstantInt::isOne(), llvm::CmpInst::isSigned(), llvm::APInt::isStrictlyPositive(), llvm::ConstantInt::isZero(), llvm_unreachable, ReplaceInstUsesWith(), llvm::User::setOperand(), llvm::SubOne(), SubWithOverflow(), and llvm::X.
Referenced by commonDivTransforms(), FoldICmpShrCst(), and visitICmpInstWithInstAndIntCst().
FoldICmpShrCst()
Instruction * InstCombiner::FoldICmpShrCst (ICmpInst & ICI, BinaryOperator * DivI, ConstantInt * DivRHS)
FoldICmpShrCst - Handle "icmp(([al]shr X, cst1), cst2)".
Definition at line 956 of file InstCombineCompares.cpp.
References llvm::APInt::ashr(), Builder, llvm::cast(), llvm::dyn_cast(), FoldICmpDivCst(), llvm::ConstantInt::get(), llvm::APInt::getBitWidth(), llvm::APInt::getHighBitsSet(), llvm::ConstantInt::getLimitedValue(), llvm::Value::getName(), llvm::APInt::getOneBitSet(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_NE, llvm::ICmpInst::isEquality(), llvm::BinaryOperator::isExact(), llvm::CmpInst::isSigned(), llvm::APInt::lshr(), ReplaceInstUsesWith(), llvm::User::setOperand(), and Worklist.
Referenced by commonDivTransforms(), and visitICmpInstWithInstAndIntCst().
FoldOrOfFCmps()
Value * InstCombiner::FoldOrOfFCmps (FCmpInst * LHS, FCmpInst * RHS)
FoldOrOfFCmps - Optimize (fcmp)|(fcmp). NOTE: Unlike the rest of instcombine, this returns a Value which should already be inserted into the function.
Definition at line 2041 of file InstCombineAndOrXor.cpp.
References Builder, llvm::dyn_cast(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UNO, llvm::ConstantInt::get(), getFCmpCode(), getFCmpValue(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::isa(), llvm::CmpInst::makeCmpResultType(), and std::swap().
Referenced by commonDivTransforms(), and visitOr().
FoldOrOfICmps()
Value * InstCombiner::FoldOrOfICmps (ICmpInst * LHS, ICmpInst * RHS, Instruction * CxtI)
FoldOrOfICmps - Fold (icmp)|(icmp) if possible.
Definition at line 1709 of file InstCombineAndOrXor.cpp.
References llvm::Add, llvm::AddOne(), Builder, llvm::dyn_cast(), foldLogOpOfMaskedICmps(), llvm::ConstantInt::get(), llvm::getICmpCode(), llvm::Value::getName(), llvm::ConstantExpr::getNeg(), getNewICmpValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::ConstantInt::getSigned(), llvm::ConstantExpr::getSub(), llvm::ConstantInt::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::isKnownToBeAPowerOfTwo(), llvm::ConstantInt::isMaxValue(), llvm::APInt::isPowerOf2(), llvm::CmpInst::isSigned(), llvm::ConstantInt::isZero(), llvm_unreachable, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::PredicatesFoldable(), llvm::APInt::sgt(), simplifyRangeCheck(), llvm::SubOne(), std::swap(), llvm::ICmpInst::swapOperands(), llvm::APInt::ugt(), llvm::APInt::ule(), and llvm::APInt::ult().
Referenced by commonDivTransforms(), and visitOr().
FoldOrWithConstants()
Instruction * InstCombiner::FoldOrWithConstants (BinaryOperator & I, Value * Op, Value * A, Value * B, Value * C)
FoldOrWithConstants - This helper function folds:
((A | B) & C1) | (B & C2)
into:
(A & C1) | B
when the XOR of the two constants is "all ones" (-1).
Definition at line 2107 of file InstCombineAndOrXor.cpp.
References Builder, llvm::dyn_cast(), llvm::ConstantInt::getValue(), I, llvm::APInt::isAllOnesValue(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by commonDivTransforms(), and visitOr().
FoldSelectIntoOp()
Instruction * InstCombiner::FoldSelectIntoOp (SelectInst & SI, Value * TrueVal, Value * FalseVal)
FoldSelectIntoOp - Try fold the select into one of the operands to facilitate further optimization.
Definition at line 235 of file InstCombineSelect.cpp.
References Builder, llvm::cast(), llvm::BinaryOperator::Create(), llvm::dyn_cast(), llvm::BinaryOperator::getOpcode(), GetSelectFoldableConstant(), GetSelectFoldableOperands(), llvm::BinaryOperator::hasNoSignedWrap(), llvm::BinaryOperator::hasNoUnsignedWrap(), llvm::isa(), llvm::BinaryOperator::isExact(), isSelect01(), llvm::BinaryOperator::setHasNoSignedWrap(), llvm::BinaryOperator::setHasNoUnsignedWrap(), llvm::BinaryOperator::setIsExact(), and llvm::Value::takeName().
Referenced by commonDivTransforms(), and visitSelectInst().
FoldSelectOpOp()
Instruction * InstCombiner::FoldSelectOpOp (SelectInst & SI, Instruction * TI, Instruction * FI)
FoldSelectOpOp - Here we have (select c, TI, FI), and we know that TI and FI have the same opcode and only one use each. Try to simplify this.
Definition at line 148 of file InstCombineSelect.cpp.
References Builder, llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::dyn_cast(), FoldSelectOpOp(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::isa(), llvm::Instruction::isCast(), llvm::Instruction::isCommutative(), llvm::Type::isVectorTy(), and llvm_unreachable.
Referenced by commonDivTransforms(), FoldSelectOpOp(), and visitSelectInst().
FoldShiftByConstant()
Instruction * InstCombiner::FoldShiftByConstant (Value * Op0, Constant * Op1, BinaryOperator & I)
Definition at line 318 of file InstCombineShifts.cpp.
References Builder, CanEvaluateShifted(), llvm::cast(), llvm::BinaryOperator::Create(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::ConstantExpr::get(), llvm::ConstantInt::get(), llvm::APInt::getHighBitsSet(), llvm::ConstantInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), GetShiftedValue(), llvm::ConstantExpr::getShl(), llvm::ConstantVector::getSplat(), llvm::Value::getType(), llvm::ConstantExpr::getZExt(), llvm::ConstantInt::getZExtValue(), llvm::BinaryOperator::hasNoSignedWrap(), llvm::BinaryOperator::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::BinaryOperator::isExact(), llvm::Instruction::isShift(), llvm::APInt::lshr(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), llvm::BinaryOperator::setHasNoSignedWrap(), llvm::BinaryOperator::setHasNoUnsignedWrap(), llvm::BinaryOperator::setIsExact(), llvm::Value::takeName(), llvm::ConstantInt::uge(), and llvm::X.
Referenced by commonDivTransforms(), and commonShiftTransforms().
FoldSPFofSPF()
Instruction * InstCombiner::FoldSPFofSPF (Instruction * Inner, SelectPatternFlavor SPF1, Value * A, Value * B, Instruction & Outer, SelectPatternFlavor SPF2, Value * C)
FoldSPFofSPF - We have an SPF (e.g. a min or max) of an SPF of the form: SPF2(SPF1(A, B), C)
Definition at line 711 of file InstCombineSelect.cpp.
References Builder, llvm::cast(), llvm::dyn_cast(), ReplaceInstUsesWith(), llvm::User::replaceUsesOfWith(), llvm::APInt::sge(), llvm::APInt::sgt(), llvm::APInt::sle(), llvm::APInt::slt(), llvm::SPF_ABS, llvm::SPF_NABS, llvm::SPF_SMAX, llvm::SPF_SMIN, llvm::SPF_UMAX, llvm::SPF_UMIN, llvm::APInt::uge(), llvm::APInt::ugt(), llvm::APInt::ule(), and llvm::APInt::ult().
Referenced by commonDivTransforms(), and visitSelectInst().
FoldXorWithConstants()
Instruction * InstCombiner::FoldXorWithConstants (BinaryOperator & I, Value * Op, Value * A, Value * B, Value * C)
This helper function folds:
((A | B) & C1) ^ (B & C2)
into:
(A & C1) ^ B
when the XOR of the two constants is "all ones" (-1).
Definition at line 2136 of file InstCombineAndOrXor.cpp.
References Builder, llvm::dyn_cast(), llvm::ConstantInt::getValue(), I, llvm::APInt::isAllOnesValue(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Value(), and llvm::PatternMatch::match().
Referenced by commonDivTransforms(), and visitOr().
getAnalysisUsage()
Combine redundant false void InstCombiner::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 93 of file InstructionCombining.cpp.
References getAnalysisUsage(), and InstCombiner().
Referenced by getAnalysisUsage().
getAssumptionCache()
AssumptionCache * llvm::InstCombiner::getAssumptionCache () const inline
Definition at line 130 of file InstCombine.h.
Referenced by simplifyValueKnownNonZero().
getDataLayout()
const DataLayout * llvm::InstCombiner::getDataLayout () const inline
Definition at line 132 of file InstCombine.h.
Referenced by CollectInsertionElements(), EvaluateGEPOffsetExpression(), GetShiftedValue(), OptimizeIntegerToVectorInsertions(), and OptimizeIntToFloatBitCast().
getDominatorTree()
DominatorTree * llvm::InstCombiner::getDominatorTree () const inline
Definition at line 134 of file InstCombine.h.
Referenced by simplifyValueKnownNonZero().
getTargetLibraryInfo()
TargetLibraryInfo * llvm::InstCombiner::getTargetLibraryInfo () const inline
Definition at line 136 of file InstCombine.h.
Referenced by GetShiftedValue().
InsertNewInstBefore()
Instruction * llvm::InstCombiner::InsertNewInstBefore (Instruction * New, Instruction & Old) inline
Definition at line 296 of file InstCombine.h.
References llvm::BasicBlock::getInstList(), llvm::Instruction::getParent(), llvm::iplist< NodeTy, Traits >::insert(), and Worklist.
Referenced by InsertNewInstWith(), and visitAllocaInst().
InsertNewInstWith()
Instruction * llvm::InstCombiner::InsertNewInstWith (Instruction * New, Instruction & Old) inline
Definition at line 308 of file InstCombine.h.
References llvm::Instruction::getDebugLoc(), InsertNewInstBefore(), and llvm::Instruction::setDebugLoc().
Referenced by foldFMulConst().
MaskedValueIsZero()
bool llvm::InstCombiner::MaskedValueIsZero (Value * V, const APInt & Mask, unsigned Depth = 0, Instruction * CxtI = nullptr) const inline
Definition at line 375 of file InstCombine.h.
References llvm::MaskedValueIsZero().
Referenced by CanEvaluateShifted(), CanEvaluateTruncated(), CanEvaluateZExtd(), visitAnd(), visitAShr(), visitLShr(), visitMul(), visitOr(), visitSDiv(), visitShl(), visitSRem(), visitXor(), and visitZExt().
OptimizePointerDifference()
Value * InstCombiner::OptimizePointerDifference (Value * LHS, Value * RHS, Type * Ty)
Optimize pointer differences into the same array into a size. Consider: &A[10] - &A[0]: we should compile this to "10". LHS/RHS are the pointer operands to the ptrtoint instructions for the LHS/RHS of the subtract.
Definition at line 1437 of file InstCombineAddSub.cpp.
References Builder, llvm::dyn_cast(), llvm::EmitGEPOffset(), and OptimizePointerDifference().
Referenced by OptimizePointerDifference(), and visitSub().
replacedSelectWithOperand()
bool InstCombiner::replacedSelectWithOperand (SelectInst * SI, const ICmpInst * Icmp, const unsigned SIOpd)
True when a select result is replaced by one of its operands in select-icmp sequence. This will eventually result in the elimination of the select.
Parameters
SI Select instruction
Icmp Compare instruction
SIOpd Operand that replaces the select
Notes:
The replacement is global and requires dominator information
The caller is responsible for the actual replacement
Example:
entry: %4 = select i1 %3, C* %0, C* null %5 = icmp eq C* %4, null br i1 %5, label %9, label %7 ... ; <label>:7 ; preds = entry %8 = getelementptr inbounds C* %4, i64 0, i32 0 ...
can be transformed to
%5 = icmp eq C* %0, null %6 = select i1 %3, i1 %5, i1 true br i1 %6, label %9, label %7 ... ; <label>:7 ; preds = entry %8 = getelementptr inbounds C* %0, i64 0, i32 0 // replace by %0!
Similar when the first operand of the select is a constant or/and the compare is for not equal rather than equal.
NOTE: The function is only called when the select and compare constants are equal, the optimization can work only for EQ predicates. This is not a major restriction since a NE compare should be 'normalized' to an equal compare, which usually happens in the combiner and test case select-cmp-br.ll checks for it.
Definition at line 2551 of file InstCombineCompares.cpp.
References dominatesAllUses(), llvm::CmpInst::getPredicate(), llvm::BasicBlock::getUniquePredecessor(), llvm::CmpInst::ICMP_EQ, and isChainSelectCmpBranch().
Referenced by visitICmpInst().
ReplaceInstUsesWith()
Instruction * llvm::InstCombiner::ReplaceInstUsesWith (Instruction & I, Value * V) inline
Definition at line 319 of file InstCombine.h.
References llvm::dbgs(), DEBUG, llvm::UndefValue::get(), I, and Worklist.
Referenced by DoOneIteration(), FoldCmpLoadFromIndexedGlobal(), FoldFCmp_IntToFP_Cst(), FoldGEPICmp(), FoldICmpCstShlCst(), FoldICmpCstShrCst(), FoldICmpDivCst(), FoldICmpShrCst(), FoldShiftByConstant(), FoldSPFofSPF(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), SliceUpIllegalIntegerPHI(), visitAdd(), visitAllocaInst(), visitAllocSite(), visitAnd(), visitAShr(), visitBitCast(), visitCallInst(), visitExtractElementInst(), visitExtractValueInst(), visitFAdd(), visitFCmpInst(), visitFDiv(), visitFMul(), visitFPToSI(), visitFPToUI(), visitFRem(), visitFSub(), visitGetElementPtrInst(), visitICmpInst(), visitICmpInstWithCastAndCast(), visitICmpInstWithInstAndIntCst(), visitInsertElementInst(), visitInsertValueInst(), visitLoadInst(), visitLShr(), visitMul(), visitOr(), visitPHINode(), visitSDiv(), visitSelectInst(), visitSelectInstWithICmp(), visitSExt(), visitShl(), visitShuffleVectorInst(), visitSRem(), visitSub(), visitTrunc(), visitUDiv(), visitURem(), visitXor(), and visitZExt().
runOnFunction()
bool InstCombiner::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Builder - This is an IRBuilder that automatically inserts new instructions into the worklist when they are created.
Implements llvm::FunctionPass.
Definition at line 2969 of file InstructionCombining.cpp.
References Builder, DoOneIteration(), F, llvm::AttributeSet::FunctionIndex, llvm::Pass::getAnalysis(), llvm::Pass::getAnalysisIfAvailable(), llvm::DataLayoutPass::getDataLayout(), llvm::LowerDbgDeclare(), llvm::Attribute::MinSize, llvm::FunctionPass::skipOptnoneFunction(), and Worklist.
SimplifyDivRemOfSelect()
bool InstCombiner::SimplifyDivRemOfSelect (BinaryOperator & I)
SimplifyDivRemOfSelect - Try to fold a divide or remainder of a select instruction.
Definition at line 706 of file InstCombineMulDivRem.cpp.
References Builder, llvm::cast(), llvm::dyn_cast(), llvm::Value::hasOneUse(), I, llvm::isa(), and Worklist.
Referenced by commonIDivTransforms(), commonIRemTransforms(), and visitFRem().
simplifyRangeCheck()
Value * InstCombiner::simplifyRangeCheck (ICmpInst * Cmp0, ICmpInst * Cmp1, bool Inverted)
Try to fold a signed range checked with lower bound 0 to an unsigned icmp. Example: (icmp sge x, 0) & (icmp slt x, n) --> icmp ult x, n If Inverted is true then the check is for the inverted range, e.g. (icmp slt x, 0) | (icmp sgt x, n) --> icmp ugt x, n
Definition at line 847 of file InstCombineAndOrXor.cpp.
References Builder, ComputeSignBit(), llvm::dyn_cast(), llvm::CmpInst::getInversePredicate(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::CmpInst::getSwappedPredicate(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ConstantInt::isMinusOne(), and llvm::ConstantInt::isZero().
Referenced by commonDivTransforms(), FoldAndOfICmps(), and FoldOrOfICmps().
SliceUpIllegalIntegerPHI()
Instruction * InstCombiner::SliceUpIllegalIntegerPHI (PHINode & FirstPhi)
SliceUpIllegalIntegerPHI - This is an integer PHI and we know that it has an illegal type: see if it is only used by trunc or trunc(lshr) operations. If so, we split the PHI into the various pieces being extracted. This sort of thing is introduced when SROA promotes an aggregate to large integer values.
TODO: The user of the trunc may be an bitcast to float/double/vector or an inttoptr. We should produce new PHIs in the right type.
Definition at line 618 of file InstCombinePHI.cpp.
References llvm::PHINode::addIncoming(), llvm::array_pod_sort(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), Builder, llvm::cast(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::PHINode::Create(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), ReplaceInstUsesWith(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Instruction::user_back(), and llvm::Value::users().
Referenced by commonDivTransforms(), and visitPHINode().
visitAdd()
Instruction * InstCombiner::visitAdd (BinaryOperator & I)
Definition at line 1048 of file InstCombineAddSub.cpp.
References llvm::AddOne(), Builder, llvm::cast(), Changed, checkForNegativeOperand(), llvm::computeKnownBits(), computeOverflowForUnsignedAdd(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateNeg(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::ConstantExpr::getAdd(), llvm::APInt::getHighBitsSet(), llvm::Value::getName(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getTrunc(), llvm::ConstantInt::getValue(), llvm::ConstantExpr::getXor(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::APInt::isPowerOf2(), llvm::APInt::isSignBit(), IT, llvm::APInt::logBase2(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::MaskedValueIsZero(), llvm::PatternMatch::match(), N, llvm::NeverOverflows, ReplaceInstUsesWith(), llvm::BinaryOperator::setHasNoSignedWrap(), llvm::BinaryOperator::setHasNoUnsignedWrap(), llvm::SimplifyAddInst(), llvm::SubOne(), visitAdd(), and llvm::X.
Referenced by visitAdd().
visitAddrSpaceCast()
Instruction * InstCombiner::visitAddrSpaceCast (AddrSpaceCastInst & CI)
Definition at line 1888 of file InstCombineCasts.cpp.
References Builder, llvm::cast(), commonPointerCastTransforms(), llvm::dyn_cast(), llvm::PointerType::get(), llvm::VectorType::get(), llvm::PointerType::getAddressSpace(), llvm::SequentialType::getElementType(), llvm::User::getOperand(), llvm::Type::getScalarType(), and llvm::Value::getType().
Referenced by commonDivTransforms().
visitAllocaInst()
Instruction * InstCombiner::visitAllocaInst (AllocaInst & AI)
Definition at line 166 of file InstCombineLoadStoreAlloca.cpp.
References Builder, llvm::cast(), llvm::GetElementPtrInst::CreateInBounds(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), EraseInstFromFunction(), llvm::ArrayType::get(), llvm::ConstantInt::get(), llvm::AllocaInst::getAlignment(), llvm::AllocaInst::getAllocatedType(), llvm::AllocaInst::getArraySize(), llvm::Value::getContext(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getFirstNonPHIOrDbg(), llvm::Type::getInt64Ty(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::getOrEnforceKnownAlignment(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::AllocaInst::getType(), llvm::Value::getType(), InsertNewInstBefore(), llvm::isa(), llvm::AllocaInst::isArrayAllocation(), isOnlyCopiedFromConstantGlobal(), llvm::Type::isSized(), llvm::Instruction::moveBefore(), ReplaceInstUsesWith(), llvm::AllocaInst::setAlignment(), llvm::User::setOperand(), llvm::SmallVectorTemplateCommon< T, typename >::size(), visitAllocaInst(), and visitAllocSite().
Referenced by commonDivTransforms(), and visitAllocaInst().
visitAllocSite()
Instruction * InstCombiner::visitAllocSite (Instruction & FI)
Definition at line 1883 of file InstructionCombining.cpp.
References llvm::cast(), llvm::cast_or_null(), llvm::InvokeInst::Create(), llvm::Intrinsic::donothing, llvm::dyn_cast(), EraseInstFromFunction(), F, llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt1Ty(), I, llvm::isa(), isAllocSiteRemovable(), llvm::ConstantInt::isZero(), llvm::None, llvm::Intrinsic::objectsize, ReplaceInstUsesWith(), and Users.
Referenced by commonDivTransforms(), and visitAllocaInst().
visitAnd()
Instruction * InstCombiner::visitAnd (BinaryOperator & I)
Definition at line 1223 of file InstCombineAndOrXor.cpp.
References Builder, llvm::cast(), Changed, llvm::APInt::countLeadingZeros(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateNot(), llvm::dyn_cast(), dyn_castNotVal(), FoldAndOfFCmps(), FoldAndOfICmps(), llvm::ConstantExpr::getAnd(), llvm::APInt::getBitWidth(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), MaskedValueIsZero(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), llvm::SimplifyAndInst(), std::swap(), llvm::X, and Y.
Referenced by commonDivTransforms().
visitAShr()
Instruction * InstCombiner::visitAShr (BinaryOperator & I)
Definition at line 778 of file InstCombineShifts.cpp.
References commonShiftTransforms(), llvm::dyn_cast(), llvm::APInt::getLowBitsSet(), llvm::APInt::getSignBit(), I, llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), MaskedValueIsZero(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), llvm::SimplifyAShrInst(), and llvm::X.
Referenced by commonDivTransforms().
visitBitCast()
Instruction * InstCombiner::visitBitCast (BitCastInst & CI)
Definition at line 1760 of file InstCombineCasts.cpp.
References Builder, llvm::cast(), commonCastTransforms(), commonPointerCastTransforms(), llvm::CastInst::Create(), llvm::InsertElementInst::Create(), llvm::GetElementPtrInst::CreateInBounds(), llvm::dyn_cast(), llvm::UndefValue::get(), llvm::Value::getContext(), llvm::SequentialType::getElementType(), llvm::Type::getInt32Ty(), llvm::Constant::getNullValue(), llvm::Type::getNumContainedTypes(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), I, llvm::isa(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isPointerTy(), llvm::Type::isVectorTy(), OptimizeIntegerToVectorInsertions(), OptimizeIntToFloatBitCast(), OptimizeVectorResize(), and ReplaceInstUsesWith().
Referenced by commonDivTransforms(), and visitGetElementPtrInst().
visitBranchInst()
Instruction * InstCombiner::visitBranchInst (BranchInst & BI)
Definition at line 2028 of file InstructionCombining.cpp.
References llvm::cast(), llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_ONE, llvm::BranchInst::getCondition(), llvm::CmpInst::getInversePredicate(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULE, llvm::isa(), llvm::PatternMatch::m_Br(), llvm::PatternMatch::m_FCmp(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::BranchInst::setCondition(), llvm::CmpInst::setPredicate(), llvm::BranchInst::swapSuccessors(), Worklist, llvm::X, and Y.
Referenced by commonDivTransforms().
visitCallInst()
Instruction * InstCombiner::visitCallInst (CallInst & CI)
visitCallInst - CallInst simplification. This mostly only handles folding of intrinsic instructions. For normal calls, it allows visitCallSite to do the heavy lifting.
Definition at line 204 of file InstCombineCalls.cpp.
References llvm::Intrinsic::aarch64_neon_smull, llvm::Intrinsic::aarch64_neon_umull, llvm::CallInst::addAttribute(), llvm::AlwaysOverflows, llvm::Intrinsic::AMDGPU_rcp, llvm::Intrinsic::arm_neon_vld1, llvm::Intrinsic::arm_neon_vld2, llvm::Intrinsic::arm_neon_vld2lane, llvm::Intrinsic::arm_neon_vld3, llvm::Intrinsic::arm_neon_vld3lane, llvm::Intrinsic::arm_neon_vld4, llvm::Intrinsic::arm_neon_vld4lane, llvm::Intrinsic::arm_neon_vmulls, llvm::Intrinsic::arm_neon_vmullu, llvm::Intrinsic::arm_neon_vst1, llvm::Intrinsic::arm_neon_vst2, llvm::Intrinsic::arm_neon_vst2lane, llvm::Intrinsic::arm_neon_vst3, llvm::Intrinsic::arm_neon_vst3lane, llvm::Intrinsic::arm_neon_vst4, llvm::Intrinsic::arm_neon_vst4lane, llvm::Intrinsic::assume, llvm::Intrinsic::bswap, Builder, llvm::cast(), Changed, computeKnownBits(), computeOverflowForUnsignedAdd(), computeOverflowForUnsignedMul(), llvm::APInt::countLeadingZeros(), llvm::APInt::countTrailingZeros(), llvm::CastInst::Create(), llvm::SelectInst::Create(), llvm::CastInst::CreateIntegerCast(), CreateOverflowTuple(), llvm::Intrinsic::ctlz, llvm::Intrinsic::cttz, llvm::APFloat::divide(), llvm::CallInst::doesNotThrow(), llvm::Function::doesNotThrow(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), EraseInstFromFunction(), llvm::Intrinsic::experimental_gc_relocate, F, llvm::ConstantAggregateZero::get(), llvm::ConstantDataVector::get(), llvm::ConstantFP::get(), llvm::ConstantInt::get(), llvm::ConstantVector::get(), llvm::MDNode::get(), llvm::UndefValue::get(), llvm::Constant::getAggregateElement(), llvm::CallInst::getArgOperand(), llvm::APInt::getBitsSet(), llvm::CallInst::getCalledValue(), llvm::Value::getContext(), llvm::Intrinsic::getDeclaration(), llvm::APInt::getHighBitsSet(), llvm::Type::getInt32Ty(), llvm::ConstantExpr::getIntegerCast(), llvm::IntrinsicInst::getIntrinsicID(), llvm::getKnownAlignment(), llvm::APInt::getLowBitsSet(), llvm::ConstantExpr::getMul(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::CallInst::getNumArgOperands(), llvm::getObjectSize(), llvm::getOrEnforceKnownAlignment(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Instruction::getParent(), llvm::Type::getPrimitiveSizeInBits(), llvm::APFloat::getSemantics(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::ConstantInt::getZExtValue(), I, llvm::CmpInst::ICMP_NE, llvm::isa(), llvm::APInt::isAllOnesValue(), llvm::isFreeCall(), llvm::ConstantFP::isInfinity(), llvm::isKnownNonNull(), llvm::ConstantFP::isNaN(), llvm::ConstantFP::isNegative(), llvm::Type::isPointerTy(), llvm::isValidAssumeForContext(), IT, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_BSwap(), llvm::PatternMatch::m_FMax(), llvm::PatternMatch::m_FMin(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::makeArrayRef(), llvm::PatternMatch::match(), llvm::Intrinsic::maxnum, llvm::LLVMContext::MD_nonnull, llvm::Intrinsic::memcpy, llvm::Intrinsic::minnum, llvm::NeverOverflows, llvm::None, llvm::Attribute::NonNull, llvm::Intrinsic::objectsize, Operands, llvm::APFloat::opOK, OR, llvm::Intrinsic::powi, llvm::Intrinsic::ppc_altivec_lvx, llvm::Intrinsic::ppc_altivec_lvxl, llvm::Intrinsic::ppc_altivec_stvx, llvm::Intrinsic::ppc_altivec_stvxl, llvm::Intrinsic::ppc_altivec_vperm, llvm::Intrinsic::ppc_vsx_lxvd2x, llvm::Intrinsic::ppc_vsx_lxvw4x, llvm::Intrinsic::ppc_vsx_stxvd2x, llvm::Intrinsic::ppc_vsx_stxvw4x, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), ReplaceInstUsesWith(), llvm::AttributeSet::ReturnIndex, llvm::APFloat::rmNearestTiesToEven, llvm::Intrinsic::sadd_with_overflow, llvm::CallInst::setArgOperand(), llvm::CallInst::setCalledFunction(), llvm::CallInst::setDoesNotThrow(), llvm::Instruction::setMetadata(), llvm::Intrinsic::smul_with_overflow, llvm::Intrinsic::ssub_with_overflow, llvm::Intrinsic::stackrestore, llvm::Intrinsic::stacksave, std::swap(), llvm::Intrinsic::uadd_with_overflow, llvm::Intrinsic::umul_with_overflow, llvm::Value::use_empty(), llvm::Intrinsic::usub_with_overflow, visitFree(), llvm::X, llvm::Intrinsic::x86_avx2_pblendvb, llvm::Intrinsic::x86_avx2_psll_d, llvm::Intrinsic::x86_avx2_psll_q, llvm::Intrinsic::x86_avx2_psll_w, llvm::Intrinsic::x86_avx2_pslli_d, llvm::Intrinsic::x86_avx2_pslli_q, llvm::Intrinsic::x86_avx2_pslli_w, llvm::Intrinsic::x86_avx2_psrl_d, llvm::Intrinsic::x86_avx2_psrl_q, llvm::Intrinsic::x86_avx2_psrl_w, llvm::Intrinsic::x86_avx2_psrli_d, llvm::Intrinsic::x86_avx2_psrli_q, llvm::Intrinsic::x86_avx2_psrli_w, llvm::Intrinsic::x86_avx_blendv_pd_256, llvm::Intrinsic::x86_avx_blendv_ps_256, llvm::Intrinsic::x86_avx_vpermilvar_pd, llvm::Intrinsic::x86_avx_vpermilvar_pd_256, llvm::Intrinsic::x86_avx_vpermilvar_ps, llvm::Intrinsic::x86_avx_vpermilvar_ps_256, llvm::Intrinsic::x86_sse2_cvtsd2si, llvm::Intrinsic::x86_sse2_cvtsd2si64, llvm::Intrinsic::x86_sse2_cvttsd2si, llvm::Intrinsic::x86_sse2_cvttsd2si64, llvm::Intrinsic::x86_sse2_psll_d, llvm::Intrinsic::x86_sse2_psll_q, llvm::Intrinsic::x86_sse2_psll_w, llvm::Intrinsic::x86_sse2_pslli_d, llvm::Intrinsic::x86_sse2_pslli_q, llvm::Intrinsic::x86_sse2_pslli_w, llvm::Intrinsic::x86_sse2_psrl_d, llvm::Intrinsic::x86_sse2_psrl_q, llvm::Intrinsic::x86_sse2_psrl_w, llvm::Intrinsic::x86_sse2_psrli_d, llvm::Intrinsic::x86_sse2_psrli_q, llvm::Intrinsic::x86_sse2_psrli_w, llvm::Intrinsic::x86_sse2_storeu_dq, llvm::Intrinsic::x86_sse2_storeu_pd, llvm::Intrinsic::x86_sse41_blendvpd, llvm::Intrinsic::x86_sse41_blendvps, llvm::Intrinsic::x86_sse41_pblendvb, llvm::Intrinsic::x86_sse41_pmovsxbw, llvm::Intrinsic::x86_sse41_pmovsxdq, llvm::Intrinsic::x86_sse41_pmovsxwd, llvm::Intrinsic::x86_sse41_pmovzxbw, llvm::Intrinsic::x86_sse41_pmovzxdq, llvm::Intrinsic::x86_sse41_pmovzxwd, llvm::Intrinsic::x86_sse4a_insertqi, llvm::Intrinsic::x86_sse_cvtss2si, llvm::Intrinsic::x86_sse_cvtss2si64, llvm::Intrinsic::x86_sse_cvttss2si, llvm::Intrinsic::x86_sse_cvttss2si64, llvm::Intrinsic::x86_sse_storeu_ps, and Y.
Referenced by commonDivTransforms().
visitExtractElementInst()
Instruction * InstCombiner::visitExtractElementInst (ExtractElementInst & EI)
Definition at line 179 of file InstCombineVectorOps.cpp.
References Builder, CheapToScalarize(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::ExtractElementInst::Create(), llvm::SelectInst::Create(), llvm::dyn_cast(), FindScalarElement(), llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::Value::getContext(), llvm::ExtractElementInst::getIndexOperand(), llvm::Type::getInt32Ty(), llvm::Value::getName(), llvm::VectorType::getNumElements(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::ExtractElementInst::getVectorOperandType(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::Type::isVectorTy(), ReplaceInstUsesWith(), llvm::APInt::setBit(), llvm::User::setOperand(), and Worklist.
Referenced by commonDivTransforms().
visitExtractValueInst()
Instruction * InstCombiner::visitExtractValueInst (ExtractValueInst & EV)
Definition at line 2139 of file InstructionCombining.cpp.
References Builder, llvm::ExtractValueInst::Create(), llvm::InsertValueInst::Create(), llvm::dyn_cast(), EraseInstFromFunction(), llvm::UndefValue::get(), llvm::ExtractValueInst::getAggregateOperand(), llvm::ExtractValueInst::getIndices(), llvm::ConstantExpr::getNot(), llvm::ExtractValueInst::getNumIndices(), llvm::ExtractValueInst::hasIndices(), I, llvm::CmpInst::ICMP_UGT, llvm::ExtractValueInst::idx_begin(), llvm::ExtractValueInst::idx_end(), llvm::makeArrayRef(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), ReplaceInstUsesWith(), llvm::Intrinsic::sadd_with_overflow, llvm::ArrayRef< T >::slice(), llvm::Intrinsic::smul_with_overflow, llvm::Intrinsic::ssub_with_overflow, llvm::Intrinsic::uadd_with_overflow, llvm::Intrinsic::umul_with_overflow, and llvm::Intrinsic::usub_with_overflow.
Referenced by commonDivTransforms().
visitFAdd()
Instruction * InstCombiner::visitFAdd (BinaryOperator & I)
Definition at line 1324 of file InstCombineAddSub.cpp.
References Builder, Changed, llvm::Instruction::copyFastMathFlags(), llvm::SelectInst::Create(), llvm::dyn_cast(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getSIToFP(), I, llvm::isa(), llvm::Constant::isNegativeZeroValue(), llvm::PatternMatch::m_AnyZero(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), simplify, llvm::SimplifyFAddInst(), and visitFAdd().
Referenced by visitFAdd().
visitFCmpInst()
Instruction * InstCombiner::visitFCmpInst (FCmpInst & I)
Orders the operands of the compare so that they are listed from most complex to least complex. This puts constants before unary operators, before binary operators.
Definition at line 3849 of file InstCombineCompares.cpp.
References Builder, llvm::cast(), Changed, llvm::APFloat::clearSign(), llvm::APFloat::cmpLessThan, llvm::APFloat::compare(), llvm::dyn_cast(), F, llvm::Intrinsic::fabs, llvm::LibFunc::fabs, llvm::LibFunc::fabsf, llvm::LibFunc::fabsl, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, FoldCmpLoadFromIndexedGlobal(), FoldFCmp_IntToFP_Cst(), llvm::ConstantFP::get(), llvm::CallInst::getArgOperand(), llvm::CallInst::getCalledFunction(), llvm::getComplexity(), llvm::ConstantExpr::getFNeg(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::APFloat::getSmallestNormalized(), llvm::CastInst::getSrcTy(), llvm::Value::getType(), llvm::ConstantFP::getValueAPF(), I, llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEhalf, llvm::APFloat::IEEEquad, llvm::APFloat::IEEEsingle, llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isFP128Ty(), llvm::Type::isHalfTy(), llvm::Type::isPPC_FP128Ty(), llvm::Type::isX86_FP80Ty(), llvm::APFloat::isZero(), llvm_unreachable, llvm::PatternMatch::m_FNeg(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::APFloat::PPCDoubleDouble, ReplaceInstUsesWith(), llvm::APFloat::rmNearestTiesToEven, llvm::SimplifyFCmpInst(), llvm::X, llvm::APFloat::x87DoubleExtended, and Y.
Referenced by commonDivTransforms().
visitFDiv()
Instruction * InstCombiner::visitFDiv (BinaryOperator & I)
Definition at line 1203 of file InstCombineMulDivRem.cpp.
References Builder, llvm::cast(), CvtFDivConstToReciprocal(), llvm::dyn_cast(), llvm::ConstantExpr::getFDiv(), llvm::ConstantExpr::getFMul(), llvm::Value::hasOneUse(), I, llvm::isa(), isNormalFp(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_FDiv(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), llvm::Instruction::setFastMathFlags(), llvm::SimplifyFDivInst(), llvm::X, and Y.
Referenced by commonDivTransforms().
visitFMul()
Instruction * InstCombiner::visitFMul (BinaryOperator & I)
Definition at line 523 of file InstCombineMulDivRem.cpp.
References Builder, llvm::cast(), Changed, llvm::Instruction::copyFastMathFlags(), detectLog2OfHalf(), llvm::dyn_cast(), foldFMulConst(), llvm::Instruction::getFastMathFlags(), llvm::ConstantExpr::getFMul(), llvm::ConstantFP::getNegativeZero(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Value::hasOneUse(), I, llvm::isa(), isFiniteNonZeroFp(), isFMulOrFDivWithConstant(), llvm::BinaryOperator::isFNeg(), isNormalFp(), llvm::PatternMatch::m_FMul(), llvm::PatternMatch::m_SpecificFP(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), llvm::CallInst::setArgOperand(), llvm::SimplifyFMulInst(), llvm::Intrinsic::sqrt, std::swap(), llvm::Value::takeName(), and Y.
visitFPExt()
Instruction * InstCombiner::visitFPExt (CastInst & CI)
Definition at line 1331 of file InstCombineCasts.cpp.
References commonCastTransforms().
Referenced by commonDivTransforms().
visitFPToSI()
Instruction * InstCombiner::visitFPToSI (FPToSIInst & FI)
Definition at line 1355 of file InstCombineCasts.cpp.
References commonCastTransforms(), llvm::dyn_cast(), llvm::Type::getFPMantissaWidth(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::isa(), and ReplaceInstUsesWith().
Referenced by commonDivTransforms().
visitFPToUI()
Instruction * InstCombiner::visitFPToUI (FPToUIInst & FI)
Definition at line 1335 of file InstCombineCasts.cpp.
References commonCastTransforms(), llvm::dyn_cast(), llvm::Type::getFPMantissaWidth(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::isa(), and ReplaceInstUsesWith().
Referenced by commonDivTransforms().
visitFPTrunc()
Instruction * InstCombiner::visitFPTrunc (FPTruncInst & CI)
Definition at line 1180 of file InstCombineCasts.cpp.
References Builder, commonCastTransforms(), llvm::Instruction::copyFastMathFlags(), llvm::BinaryOperator::Create(), llvm::CallInst::Create(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateFNeg(), llvm::CastInst::CreateFPCast(), llvm::dyn_cast(), llvm::Intrinsic::fabs, llvm::CallInst::getArgOperand(), llvm::Intrinsic::getDeclaration(), llvm::Type::getFPMantissaWidth(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::BinaryOperator::isFNeg(), and LookThroughFPExtensions().
Referenced by commonDivTransforms().
visitFree()
Instruction * InstCombiner::visitFree (CallInst & FI)
Definition at line 1979 of file InstructionCombining.cpp.
References Builder, EraseInstFromFunction(), llvm::UndefValue::get(), llvm::CallInst::getArgOperand(), llvm::Value::getContext(), llvm::Type::getInt1PtrTy(), llvm::ConstantInt::getTrue(), I, llvm::isa(), and tryToMoveFreeBeforeNullTest().
Referenced by commonDivTransforms(), and visitCallInst().
visitFRem()
Instruction * InstCombiner::visitFRem (BinaryOperator & I)
Definition at line 1478 of file InstCombineMulDivRem.cpp.
References I, llvm::isa(), ReplaceInstUsesWith(), SimplifyDivRemOfSelect(), and llvm::SimplifyFRemInst().
visitFSub()
Instruction * InstCombiner::visitFSub (BinaryOperator & I)
Definition at line 1692 of file InstCombineAddSub.cpp.
References Builder, llvm::Instruction::copyFastMathFlags(), llvm::BinaryOperator::CreateFNeg(), llvm::dyn_cast(), I, llvm::isa(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), simplify, llvm::SimplifyFSubInst(), and visitFSub().
Referenced by visitFSub().
visitGetElementPtrInst()
Instruction * InstCombiner::visitGetElementPtrInst (GetElementPtrInst & GEP)
See if we can simplify: X = bitcast A* to B* Y = gep X, <...constant indices...> into a gep of the original struct. This is important for SROA and alias analysis of unions. If "A" is also a bitcast, wait for A/X to be merged.
Definition at line 1319 of file InstructionCombining.cpp.
References llvm::GetElementPtrInst::accumulateConstantOffset(), llvm::PHINode::addIncoming(), llvm::SmallVectorImpl< T >::append(), Builder, llvm::cast(), llvm::Instruction::clone(), llvm::CastInst::Create(), llvm::GetElementPtrInst::Create(), llvm::GetElementPtrInst::CreateInBounds(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), F, llvm::gep_type_begin(), llvm::gep_type_end(), llvm::GetElementPtrInst::getAddressSpace(), llvm::PointerType::getAddressSpace(), llvm::Type::getArrayElementType(), llvm::SequentialType::getElementType(), llvm::BasicBlock::getFirstNonPHI(), llvm::PHINode::getIncomingBlock(), llvm::BasicBlock::getInstList(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::GetElementPtrInst::getNumIndices(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::GetElementPtrInst::getPointerAddressSpace(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerElementType(), llvm::GetElementPtrInst::getPointerOperandType(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::APInt::getSExtValue(), llvm::GetElementPtrInst::getType(), llvm::Value::getType(), I, llvm::GetElementPtrInst::idx_begin(), llvm::GetElementPtrInst::idx_end(), llvm::iplist< NodeTy, Traits >::insert(), llvm::isa(), llvm::isAllocationFn(), llvm::Type::isArrayTy(), llvm::GetElementPtrInst::isInBounds(), llvm::Type::isSized(), llvm::Type::isStructTy(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::User::op_begin(), llvm::User::op_end(), llvm::User::operands(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), ReplaceInstUsesWith(), llvm::GetElementPtrInst::setIsInBounds(), llvm::User::setOperand(), shouldMergeGEPs(), llvm::SimplifyGEPInst(), llvm::Value::stripPointerCasts(), llvm::Value::takeName(), visitBitCast(), and Y.
Referenced by commonDivTransforms().
visitICmpInst()
Instruction * InstCombiner::visitICmpInst (ICmpInst & I)
Orders the operands of the compare so that they are listed from most complex to least complex. This puts constants before unary operators, before binary operators.
Definition at line 2575 of file InstCombineCompares.cpp.
References llvm::APInt::abs(), Builder, llvm::cast(), Changed, ComputeSignedMinMaxValuesFromKnownBits(), ComputeUnsignedMinMaxValuesFromKnownBits(), llvm::APInt::countTrailingZeros(), llvm::CmpInst::Create(), llvm::ExtractValueInst::Create(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateNot(), DemandedBitsLHSMask(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), FoldCmpLoadFromIndexedGlobal(), FoldGEPICmp(), FoldICmpAddOpCst(), FoldICmpCstShlCst(), FoldICmpCstShrCst(), llvm::ConstantInt::get(), llvm::APInt::getAllOnesValue(), llvm::Constant::getAllOnesValue(), llvm::ConstantExpr::getBitCast(), llvm::APInt::getBitWidth(), llvm::ConstantInt::getBitWidth(), llvm::getComplexity(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getICmp(), llvm::ConstantInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::ConstantExpr::getNeg(), llvm::ConstantExpr::getNot(), llvm::Constant::getNullValue(), llvm::APInt::getOneBitSet(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::BinaryOperator::hasNoSignedWrap(), llvm::BinaryOperator::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::ICmpInst::isEquality(), llvm::BinaryOperator::isExact(), llvm::Type::isIntegerTy(), llvm::Type::isIntOrIntVectorTy(), llvm::isKnownToBeAPowerOfTwo(), llvm::APInt::isNegative(), llvm::Type::isPointerTy(), llvm::APInt::isPowerOf2(), isSignBitCheck(), llvm::CmpInst::isSigned(), llvm::CmpInst::isUnsigned(), llvm::ConstantInt::isZero(), llvm_unreachable, llvm::APInt::logBase2(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), NC, ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), replacedSelectWithOperand(), ReplaceInstUsesWith(), llvm::SimplifyICmpInst(), llvm::APInt::sle(), llvm::APInt::slt(), std::swap(), swapMayExposeCSEOpportunities(), llvm::APInt::uge(), llvm::APInt::ule(), llvm::APInt::ult(), visitICmpInstWithCastAndCast(), visitICmpInstWithInstAndIntCst(), llvm::X, Y, and llvm::APInt::zext().
Referenced by commonDivTransforms().
visitICmpInstWithCastAndCast()
Instruction * InstCombiner::visitICmpInstWithCastAndCast (ICmpInst & ICI)
visitICmpInstWithCastAndCast - Handle icmp (cast x to y), (cast/cst). We only handle extending casts so far.
Definition at line 1922 of file InstCombineCompares.cpp.
References Builder, llvm::cast(), llvm::BinaryOperator::CreateNot(), llvm::dyn_cast(), llvm::Constant::getAllOnesValue(), llvm::ConstantExpr::getCast(), llvm::Type::getIntegerBitWidth(), llvm::ConstantExpr::getIntToPtr(), llvm::Value::getName(), llvm::CastInst::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::ICmpInst::getUnsignedPredicate(), llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::CmpInst::isSigned(), and ReplaceInstUsesWith().
Referenced by commonDivTransforms(), and visitICmpInst().
visitICmpInstWithInstAndIntCst()
Instruction * InstCombiner::visitICmpInstWithInstAndIntCst (ICmpInst & ICI, Instruction * LHSI, ConstantInt * RHS)
visitICmpInstWithInstAndIntCst - Handle "icmp (instr, intcst)".
Definition at line 1150 of file InstCombineCompares.cpp.
References llvm::AddOne(), llvm::Intrinsic::bswap, Builder, llvm::APInt::byteSwap(), llvm::cast(), computeKnownBits(), llvm::APInt::countTrailingZeros(), llvm::Intrinsic::ctlz, llvm::Intrinsic::ctpop, llvm::Intrinsic::cttz, llvm::dyn_cast(), FoldCmpLoadFromIndexedGlobal(), FoldICmpDivCst(), FoldICmpShrCst(), llvm::ConstantExpr::get(), llvm::ConstantInt::get(), llvm::IntegerType::get(), llvm::APInt::getActiveBits(), llvm::ConstantExpr::getAnd(), llvm::ConstantExpr::getAShr(), getBitWidth(), llvm::APInt::getBitWidth(), llvm::ConstantInt::getBitWidth(), llvm::IntegerType::getBitWidth(), llvm::Value::getContext(), llvm::APInt::getHighBitsSet(), llvm::ConstantInt::getLimitedValue(), llvm::APInt::getLowBitsSet(), llvm::ConstantRange::getLower(), llvm::ConstantExpr::getLShr(), llvm::Value::getName(), llvm::ConstantExpr::getNeg(), llvm::ConstantExpr::getNot(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getNUWShl(), llvm::APInt::getOneBitSet(), llvm::BinaryOperator::getOpcode(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getOr(), llvm::CmpInst::getPredicate(), llvm::Type::getPrimitiveSizeInBits(), llvm::ConstantExpr::getShl(), llvm::ICmpInst::getSignedPredicate(), llvm::ConstantExpr::getSub(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantExpr::getTrunc(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::ICmpInst::getUnsignedPredicate(), llvm::ConstantRange::getUpper(), llvm::ConstantInt::getValue(), llvm::ConstantExpr::getXor(), llvm::ConstantExpr::getZExt(), llvm::ConstantInt::getZExtValue(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::APInt::isAllOnesValue(), llvm::Instruction::isArithmeticShift(), llvm::ICmpInst::isEquality(), llvm::BinaryOperator::isExact(), isHighOnes(), llvm::APInt::isMinValue(), llvm::ConstantInt::isNegative(), llvm::APInt::isNonNegative(), llvm::Constant::isNullValue(), llvm::APInt::isPowerOf2(), llvm::Instruction::isShift(), llvm::APInt::isSignBit(), isSignBitCheck(), llvm::CmpInst::isSigned(), isSignTest(), llvm::CmpInst::isUnsigned(), llvm::ConstantInt::isZero(), llvm::APInt::logBase2(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::ICmpInst::makeConstantRange(), llvm::PatternMatch::match(), P, ReplaceInstUsesWith(), llvm::User::setOperand(), llvm::SubOne(), llvm::ConstantRange::subtract(), llvm::Value::takeName(), llvm::ConstantInt::uge(), Worklist, llvm::X, Y, and llvm::APInt::zext().
Referenced by commonDivTransforms(), and visitICmpInst().
visitInsertElementInst()
Instruction * InstCombiner::visitInsertElementInst (InsertElementInst & IE)
Definition at line 528 of file InstCombineVectorOps.cpp.
References llvm::cast(), CollectShuffleElements(), llvm::dyn_cast(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::APInt::getAllOnesValue(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::isa(), and ReplaceInstUsesWith().
Referenced by commonDivTransforms().
visitInsertValueInst()
Instruction * InstCombiner::visitInsertValueInst (InsertValueInst & I)
Try to find redundant insertvalue instructions, like the following ones: %0 = insertvalue { i8, i32 } undef, i8 x, 0 %1 = insertvalue { i8, i32 } %0, i8 y, 0 Here the second instruction inserts values at the same indices, as the first one, making the first one redundant. It should be transformed to: %0 = insertvalue { i8, i32 } undef, i8 y, 0
Definition at line 500 of file InstCombineVectorOps.cpp.
References llvm::dyn_cast(), I, ReplaceInstUsesWith(), and llvm::Value::user_back().
Referenced by commonDivTransforms().
visitInstruction()
Instruction * llvm::InstCombiner::visitInstruction (Instruction & I) inline
Definition at line 249 of file InstCombine.h.
References I.
visitIntToPtr()
Instruction * InstCombiner::visitIntToPtr (IntToPtrInst & CI)
Definition at line 1383 of file InstCombineCasts.cpp.
References Builder, commonCastTransforms(), llvm::VectorType::get(), llvm::IntToPtrInst::getAddressSpace(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), I, llvm::Type::isVectorTy(), and P.
Referenced by commonDivTransforms().
visitInvokeInst()
Instruction * InstCombiner::visitInvokeInst (InvokeInst & II)
Definition at line 1143 of file InstCombineCalls.cpp.
Referenced by commonDivTransforms().
visitLandingPadInst()
Instruction * InstCombiner::visitLandingPadInst (LandingPadInst & LI)
Definition at line 2333 of file InstructionCombining.cpp.
References llvm::LandingPadInst::addClause(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::cast(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::LandingPadInst::Create(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SmallVectorImpl< T >::erase(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::LandingPadInst::getClause(), llvm::SequentialType::getElementType(), llvm::Constant::getNullValue(), llvm::LandingPadInst::getNumClauses(), llvm::ArrayType::getNumElements(), llvm::User::getOperand(), llvm::LandingPadInst::getPersonalityFn(), llvm::Value::getType(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::LandingPadInst::isCatch(), isCatchAll(), llvm::LandingPadInst::isCleanup(), llvm::LandingPadInst::isFilter(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), RecognizePersonality(), llvm::SmallVectorImpl< T >::reserve(), llvm::LandingPadInst::setCleanup(), shorter_filter(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Constant::stripPointerCasts(), and llvm::Value::stripPointerCasts().
Referenced by commonDivTransforms().
visitLoadInst()
Instruction * InstCombiner::visitLoadInst (LoadInst & LI)
Definition at line 394 of file InstCombineLoadStoreAlloca.cpp.
References Align, Builder, combineLoadToOperationType(), llvm::SelectInst::Create(), llvm::dyn_cast(), llvm::FindAvailableLoadedValue(), llvm::UndefValue::get(), llvm::LoadInst::getAlignment(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::getOrEnforceKnownAlignment(), llvm::Instruction::getParent(), llvm::LoadInst::getPointerAddressSpace(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::isa(), llvm::isSafeToLoadUnconditionally(), llvm::LoadInst::isSimple(), ReplaceInstUsesWith(), llvm::LoadInst::setAlignment(), and llvm::User::setOperand().
Referenced by commonDivTransforms().
visitLShr()
Instruction * InstCombiner::visitLShr (BinaryOperator & I)
Definition at line 734 of file InstCombineShifts.cpp.
References Builder, commonShiftTransforms(), llvm::Intrinsic::ctlz, llvm::Intrinsic::ctpop, llvm::Intrinsic::cttz, llvm::dyn_cast(), llvm::APInt::getLowBitsSet(), llvm::Type::getScalarSizeInBits(), llvm::ConstantInt::getSigned(), llvm::Value::getType(), I, llvm::isPowerOf2_32(), llvm::Log2_32(), MaskedValueIsZero(), ReplaceInstUsesWith(), and llvm::SimplifyLShrInst().
Referenced by commonDivTransforms().
visitMul()
Instruction * InstCombiner::visitMul (BinaryOperator & I)
i1 mul -> i1 and.
Definition at line 168 of file InstCombineMulDivRem.cpp.
References llvm::APInt::abs(), Builder, llvm::cast(), Changed, computeOverflowForUnsignedMul(), llvm::BinaryOperator::CreateNeg(), llvm::dyn_cast(), llvm::ConstantInt::get(), getLogBase2Vector(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getShl(), llvm::Value::getType(), llvm::BinaryOperator::hasNoSignedWrap(), llvm::BinaryOperator::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::APInt::isNegative(), llvm::Constant::isNotMinSignedValue(), llvm::APInt::isPowerOf2(), llvm::APInt::logBase2(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), MaskedValueIsZero(), llvm::PatternMatch::match(), llvm::NeverOverflows, ReplaceInstUsesWith(), llvm::BinaryOperator::setHasNoSignedWrap(), llvm::BinaryOperator::setHasNoUnsignedWrap(), llvm::SimplifyMulInst(), llvm::Sub, llvm::Value::takeName(), llvm::X, and Y.
visitOr()
Instruction * InstCombiner::visitOr (BinaryOperator & I)
Definition at line 2159 of file InstCombineAndOrXor.cpp.
References Builder, llvm::cast(), Changed, llvm::CastInst::Create(), llvm::SelectInst::Create(), llvm::BinaryOperator::CreateNot(), llvm::dyn_cast(), dyn_castNotVal(), FoldOrOfFCmps(), FoldOrOfICmps(), FoldOrWithConstants(), FoldXorWithConstants(), llvm::Value::getName(), llvm::CastInst::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getOr(), llvm::ConstantInt::getSigned(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::Type::isIntOrIntVectorTy(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_LogicalShift(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), MaskedValueIsZero(), llvm::PatternMatch::match(), MatchSelectFromAndOr(), ReplaceInstUsesWith(), llvm::SimplifyOrInst(), std::swap(), llvm::Value::takeName(), llvm::X, and Y.
Referenced by commonDivTransforms().
visitPHINode()
Instruction * InstCombiner::visitPHINode (PHINode & PN)
Definition at line 790 of file InstCombinePHI.cpp.
References llvm::BasicBlock::begin(), llvm::cast(), DeadPHICycle(), llvm::dyn_cast(), llvm::UndefValue::get(), llvm::PHINode::getBasicBlockIndex(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getParent(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::Type::isIntegerTy(), PHIsEqualValue(), ReplaceInstUsesWith(), llvm::PHINode::setIncomingBlock(), llvm::PHINode::setIncomingValue(), llvm::SimplifyInstruction(), SliceUpIllegalIntegerPHI(), and llvm::Instruction::user_back().
Referenced by commonDivTransforms().
visitPtrToInt()
Instruction * InstCombiner::visitPtrToInt (PtrToIntInst & CI)
Definition at line 1467 of file InstCombineCasts.cpp.
References Builder, commonPointerCastTransforms(), llvm::CastInst::CreateIntegerCast(), llvm::VectorType::get(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::PtrToIntInst::getPointerAddressSpace(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::Type::isVectorTy(), and P.
Referenced by commonDivTransforms().
visitReturnInst()
Instruction * InstCombiner::visitReturnInst (ReturnInst & RI)
Definition at line 2008 of file InstructionCombining.cpp.
References computeKnownBits(), llvm::Constant::getIntegerValue(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::Type::isIntegerTy(), and llvm::User::setOperand().
Referenced by commonDivTransforms().
visitSDiv()
Instruction * InstCombiner::visitSDiv (BinaryOperator & I)
Definition at line 1105 of file InstCombineMulDivRem.cpp.
References Builder, commonIDivTransforms(), llvm::BinaryOperator::CreateNeg(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::ConstantExpr::getNeg(), llvm::APInt::getSignBit(), llvm::Value::getType(), I, llvm::isKnownToBeAPowerOfTwo(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_NSWSub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), MaskedValueIsZero(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), llvm::SimplifySDivInst(), and llvm::X.
Referenced by commonDivTransforms().
visitSelectInst()
Instruction * InstCombiner::visitSelectInst (SelectInst & SI)
Definition at line 851 of file InstCombineSelect.cpp.
References Builder, CanSelectOperandBeMappingIntoPredBlock(), llvm::cast(), llvm::SelectInst::Create(), llvm::dyn_cast(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_UNE, foldSelectICmpAnd(), FoldSelectIntoOp(), FoldSelectOpOp(), FoldSPFofSPF(), llvm::APInt::getAllOnesValue(), llvm::Value::getName(), llvm::BinaryOperator::getNotArgument(), llvm::ConstantFP::getValueAPF(), llvm::isa(), llvm::BinaryOperator::isNot(), llvm::CmpInst::isUnordered(), llvm::APFloat::isZero(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::match(), MatchSelectPattern(), ReplaceInstUsesWith(), llvm::Instruction::setFastMathFlags(), llvm::SimplifySelectInst(), std::swap(), and visitSelectInstWithICmp().
Referenced by commonDivTransforms().
visitSelectInstWithICmp()
Instruction * InstCombiner::visitSelectInstWithICmp (SelectInst & SI, ICmpInst * ICI)
visitSelectInstWithICmp - Visit a SelectInst that has an ICmpInst as its first operand.
Definition at line 443 of file InstCombineSelect.cpp.
References Builder, Changed, llvm::dyn_cast(), foldSelectICmpAndOr(), llvm::ConstantInt::get(), llvm::IntegerType::getBitWidth(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getScalarSizeInBits(), llvm::ConstantExpr::getSExt(), llvm::APInt::getSignBit(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::ConstantExpr::getZExt(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::ICmpInst::isEquality(), llvm::CmpInst::isUnsigned(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Power2(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), llvm::Instruction::moveBefore(), ReplaceInstUsesWith(), llvm::User::setOperand(), llvm::CmpInst::setPredicate(), SimplifyWithOpReplaced(), std::swap(), llvm::X, and Y.
Referenced by commonDivTransforms(), and visitSelectInst().
visitSExt()
Instruction * InstCombiner::visitSExt (SExtInst & CI)
Definition at line 1050 of file InstCombineCasts.cpp.
References Builder, CanEvaluateSExtd(), commonCastTransforms(), ComputeNumSignBits(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::Value::getName(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::Value::hasOneUse(), I, llvm::isa(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), and llvm::Instruction::user_back().
Referenced by commonDivTransforms().
visitShl()
Instruction * InstCombiner::visitShl (BinaryOperator & I)
Definition at line 692 of file InstCombineShifts.cpp.
References commonShiftTransforms(), ComputeNumSignBits(), llvm::dyn_cast(), llvm::APInt::getHighBitsSet(), llvm::ConstantExpr::getShl(), I, llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Value(), MaskedValueIsZero(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), and llvm::SimplifyShlInst().
Referenced by commonDivTransforms().
visitShuffleVectorInst()
Instruction * InstCombiner::visitShuffleVectorInst (ShuffleVectorInst & SVI)
Definition at line 856 of file InstCombineVectorOps.cpp.
References CanEvaluateShuffled(), llvm::cast(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::APInt::getAllOnesValue(), llvm::Value::getContext(), llvm::Type::getInt32Ty(), llvm::User::getOperand(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::ShuffleVectorInst::getType(), llvm::Value::getType(), llvm::isa(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), RecognizeIdentityMask(), ReplaceInstUsesWith(), llvm::User::setOperand(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by commonDivTransforms().
visitSIToFP()
Instruction * InstCombiner::visitSIToFP (CastInst & CI)
Definition at line 1379 of file InstCombineCasts.cpp.
References commonCastTransforms().
Referenced by commonDivTransforms().
visitSRem()
Instruction * InstCombiner::visitSRem (BinaryOperator & I)
Definition at line 1403 of file InstCombineMulDivRem.cpp.
References llvm::cast(), commonIRemTransforms(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::ConstantVector::get(), llvm::ConstantExpr::getNeg(), llvm::APInt::getSignBit(), I, llvm::isa(), llvm::PatternMatch::m_APInt(), MaskedValueIsZero(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), llvm::SimplifySRemInst(), Worklist, and Y.
visitStoreInst()
Instruction * InstCombiner::visitStoreInst (StoreInst & SI)
Definition at line 605 of file InstCombineLoadStoreAlloca.cpp.
References combineStoreToValueType(), llvm::dyn_cast(), equivalentAddressValues(), EraseInstFromFunction(), llvm::UndefValue::get(), llvm::getOrEnforceKnownAlignment(), llvm::Value::getType(), llvm::Value::hasOneUse(), llvm::isa(), and Worklist.
Referenced by commonDivTransforms().
visitSub()
Instruction * InstCombiner::visitSub (BinaryOperator & I)
Definition at line 1503 of file InstCombineAddSub.cpp.
References llvm::AddOne(), Builder, llvm::cast(), Changed, llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNot(), llvm::CastInst::CreateSExtOrBitCast(), llvm::CastInst::CreateZExtOrBitCast(), llvm::dyn_cast(), llvm::ConstantExpr::getNeg(), llvm::ConstantExpr::getSub(), llvm::ConstantInt::getValue(), llvm::Value::hasOneUse(), I, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_SExt(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), OptimizePointerDifference(), ReplaceInstUsesWith(), llvm::BinaryOperator::setHasNoSignedWrap(), llvm::SimplifySubInst(), visitSub(), llvm::X, and Y.
Referenced by visitSub().
visitSwitchInst()
Instruction * InstCombiner::visitSwitchInst (SwitchInst & SI)
Definition at line 2076 of file InstructionCombining.cpp.
References Builder, llvm::cast(), computeKnownBits(), llvm::APInt::countLeadingOnes(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::IntegerType::get(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getSub(), llvm::Value::getType(), llvm::ConstantExpr::getZExt(), I, llvm::isa(), and Worklist.
Referenced by commonDivTransforms().
visitTrunc()
Instruction * InstCombiner::visitTrunc (TruncInst & CI)
Definition at line 440 of file InstCombineCasts.cpp.
References Builder, CanEvaluateTruncated(), commonCastTransforms(), llvm::CastInst::CreateIntegerCast(), llvm::dbgs(), DEBUG, llvm::ConstantInt::get(), llvm::Constant::getNullValue(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::Value::hasOneUse(), llvm::CmpInst::ICMP_NE, llvm::isa(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_ZExt(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), and llvm::Value::takeName().
Referenced by commonDivTransforms().
visitUDiv()
Instruction * InstCombiner::visitUDiv (BinaryOperator & I)
Definition at line 1032 of file InstCombineMulDivRem.cpp.
References Builder, llvm::cast(), commonIDivTransforms(), llvm::SelectInst::Create(), llvm::dyn_cast(), dyn_castZExtVal(), llvm::ConstantInt::get(), I, llvm::Instruction::insertBefore(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), llvm::BinaryOperator::setIsExact(), llvm::SimplifyUDivInst(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::APInt::ushl_ov(), visitUDivOperand(), and llvm::X.
Referenced by commonDivTransforms().
visitUIToFP()
Instruction * InstCombiner::visitUIToFP (CastInst & CI)
Definition at line 1375 of file InstCombineCasts.cpp.
References commonCastTransforms().
Referenced by commonDivTransforms().
visitURem()
Instruction * InstCombiner::visitURem (BinaryOperator & I)
Definition at line 1368 of file InstCombineMulDivRem.cpp.
References llvm::Add, Builder, commonIRemTransforms(), llvm::dyn_cast(), dyn_castZExtVal(), llvm::Constant::getAllOnesValue(), I, llvm::isKnownToBeAPowerOfTwo(), llvm::PatternMatch::m_One(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), and llvm::SimplifyURemInst().
visitXor()
Instruction * InstCombiner::visitXor (BinaryOperator & I)
Definition at line 2546 of file InstCombineAndOrXor.cpp.
References Builder, llvm::cast(), Changed, llvm::CastInst::Create(), llvm::CmpInst::Create(), llvm::BinaryOperator::CreateNot(), llvm::dyn_cast(), dyn_castNotVal(), llvm::ConstantInt::get(), llvm::ConstantExpr::getAnd(), llvm::ConstantExpr::getCast(), llvm::getICmpCode(), llvm::ConstantExpr::getNeg(), getNewICmpValue(), llvm::ConstantExpr::getNot(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::ConstantExpr::getOr(), llvm::ConstantExpr::getSub(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::Value::hasOneUse(), I, llvm::isa(), isFreeToInvert(), llvm::Type::isIntegerTy(), llvm::APInt::lshr(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), MaskedValueIsZero(), llvm::PatternMatch::match(), llvm::PredicatesFoldable(), ReplaceInstUsesWith(), llvm::SimplifyXorInst(), std::swap(), llvm::BinaryOperator::swapOperands(), llvm::Value::takeName(), and Worklist.
Referenced by commonDivTransforms().
visitZExt()
Instruction * InstCombiner::visitZExt (ZExtInst & CI)
Definition at line 763 of file InstCombineCasts.cpp.
References Builder, CanEvaluateZExtd(), commonCastTransforms(), llvm::BinaryOperator::Create(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::Value::getName(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::ConstantExpr::getZExt(), llvm::Value::hasOneUse(), llvm::isa(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_OneUse(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), MaskedValueIsZero(), llvm::PatternMatch::match(), ReplaceInstUsesWith(), llvm::Instruction::user_back(), and llvm::X.
Referenced by commonDivTransforms().
Member Data Documentation
Builder
BuilderTy* llvm::InstCombiner::Builder
Definition at line 114 of file InstCombine.h.
Referenced by combineLoadToNewType(), combineStoreToValueType(), commonIDivTransforms(), commonPointerCastTransforms(), commonShiftTransforms(), CreateOverflowTuple(), DoOneIteration(), EvaluateGEPOffsetExpression(), FoldAndOfFCmps(), FoldAndOfICmps(), FoldCmpLoadFromIndexedGlobal(), FoldFCmp_IntToFP_Cst(), FoldGEPICmp(), FoldICmpAddOpCst(), FoldICmpDivCst(), FoldICmpShrCst(), FoldOperationIntoSelectOperand(), FoldOrOfFCmps(), FoldOrOfICmps(), FoldOrWithConstants(), FoldSelectIntoOp(), FoldSelectOpOp(), FoldShiftByConstant(), FoldSPFofSPF(), foldUDivNegCst(), foldUDivShl(), FoldXorWithConstants(), GetShiftedValue(), InstCombiner(), OptimizeIntegerToVectorInsertions(), OptimizeIntToFloatBitCast(), OptimizePointerDifference(), OptimizeVectorResize(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), runOnFunction(), SimplifyDivRemOfSelect(), simplifyRangeCheck(), simplifyValueKnownNonZero(), SliceUpIllegalIntegerPHI(), visitAdd(), visitAddrSpaceCast(), visitAllocaInst(), visitAnd(), visitBitCast(), visitCallInst(), visitExtractElementInst(), visitExtractValueInst(), visitFAdd(), visitFCmpInst(), visitFDiv(), visitFMul(), visitFPTrunc(), visitFree(), visitFSub(), visitGetElementPtrInst(), visitICmpInst(), visitICmpInstWithCastAndCast(), visitICmpInstWithInstAndIntCst(), visitIntToPtr(), visitLoadInst(), visitLShr(), visitMul(), visitOr(), visitPtrToInt(), visitSDiv(), visitSelectInst(), visitSelectInstWithICmp(), visitSExt(), visitSub(), visitSwitchInst(), visitTrunc(), visitUDiv(), visitURem(), visitXor(), and visitZExt().
ID
char InstCombiner::ID = 0 static
Definition at line 116 of file InstCombine.h.
Referenced by InstCombiner().
Worklist
InstCombineWorklist llvm::InstCombiner::Worklist
Worklist - All of the instructions that need to be simplified.
Definition at line 109 of file InstCombine.h.
Referenced by AddReachableCodeToWorklist(), commonPointerCastTransforms(), DoOneIteration(), EraseInstFromFunction(), FoldICmpShrCst(), GetShiftedValue(), InsertNewInstBefore(), ProcessUMulZExtIdiom(), ReplaceInstUsesWith(), runOnFunction(), SimplifyDivRemOfSelect(), visitBranchInst(), visitExtractElementInst(), visitICmpInstWithInstAndIntCst(), visitSRem(), visitStoreInst(), visitSwitchInst(), and visitXor().
The documentation for this class was generated from the following files:
InstCombine.h
InstCombineAddSub.cpp
InstCombineAndOrXor.cpp
InstCombineCalls.cpp
InstCombineCasts.cpp
InstCombineCompares.cpp
InstCombineLoadStoreAlloca.cpp
InstCombineMulDivRem.cpp
InstCombinePHI.cpp
InstCombineSelect.cpp
InstCombineShifts.cpp
InstCombineSimplifyDemanded.cpp
InstCombineVectorOps.cpp
InstructionCombining.cpp