LLVM: llvm::RegionInfo Class Reference
LLVM API Documentation
llvm::RegionInfo Class Reference
#include <RegionInfo.h>
Public Member Functions
RegionInfo ()
virtual ~RegionInfo ()
void updateStatistics (Region *R) final
void recalculate (Function &F, DominatorTree *DT, PostDominatorTree *PDT, DominanceFrontier *DF)
Public Member Functions inherited from llvm::RegionInfoBase< RegionTraits< Function > >
void print (raw_ostream &OS) const
void dump () const
void releaseMemory ()
RegionT * getRegionFor (BlockT *BB) const
Get the smallest region that contains a BasicBlock.
void setRegionFor (BlockT *BB, RegionT *R)
Set the smallest region that surrounds a basic block.
RegionT * operator[] (BlockT *BB) const
A shortcut for getRegionFor().
BlockT * getMaxRegionExit (BlockT *BB) const
Return the exit of the maximal refined region, that starts at a BasicBlock.
RegionT * getCommonRegion (RegionT *A, RegionT *B) const
Find the smallest region that contains two regions.
RegionT * getTopLevelRegion () const
void splitBlock (BlockT *NewBB, BlockT *OldBB)
Update RegionInfo after a basic block was split.
void clearNodeCache ()
Clear the Node Cache for all Regions.
void verifyAnalysis () const
Additional Inherited Members
Static Public Attributes inherited from llvm::RegionInfoBase< RegionTraits< Function > >
static bool VerifyRegionInfo
static RegionT::PrintStyle printStyle
Detailed Description
Definition at line 841 of file RegionInfo.h.
Constructor & Destructor Documentation
RegionInfo()
RegionInfo::RegionInfo () explicit
Definition at line 77 of file RegionInfo.cpp.
~RegionInfo()
RegionInfo::~RegionInfo () virtual
Definition at line 82 of file RegionInfo.cpp.
Member Function Documentation
recalculate()
void RegionInfo::recalculate (Function & F, DominatorTree * DT, PostDominatorTree * PDT, DominanceFrontier * DF)
Definition at line 94 of file RegionInfo.cpp.
References F, and updateStatistics().
updateStatistics()
void RegionInfo::updateStatistics (Region * R) final
Definition at line 86 of file RegionInfo.cpp.
References llvm::RegionBase< Tr >::isSimple().
Referenced by recalculate().
The documentation for this class was generated from the following files:
RegionInfo.h
RegionInfo.cpp