LLVM: llvm::DwarfFile Class Reference
LLVM API Documentation
llvm::DwarfFile Class Reference
#include <DwarfFile.h>
Public Member Functions
DwarfFile (AsmPrinter *AP, DwarfDebug &DD, StringRef Pref, BumpPtrAllocator &DA)
~DwarfFile ()
const SmallVectorImpl< std::unique_ptr< DwarfUnit > > & getUnits ()
unsigned computeSizeAndOffset (DIE &Die, unsigned Offset)
Compute the size and offset of a DIE given an incoming Offset.
void computeSizeAndOffsets ()
Compute the size and offset of all the DIEs.
void assignAbbrevNumber (DIEAbbrev &Abbrev)
Define a unique number for the abbreviation.
void addUnit (std::unique_ptr< DwarfUnit > U)
Add a unit to the list of CUs.
void emitUnits (const MCSymbol *ASectionSym)
Emit all of the units to the section listed with the given abbreviation section.
void emitAbbrevs (const MCSection *)
Emit a set of abbreviations to the specific section.
void emitStrings (const MCSection *StrSection, const MCSection *OffsetSection=nullptr)
Emit all of the strings to the section given.
DwarfStringPool & getStringPool ()
Returns the string pool.
void addScopeVariable (LexicalScope *LS, DbgVariable *Var)
DenseMap< LexicalScope *, SmallVector< DbgVariable *, 8 > > & getScopeVariables ()
DenseMap< const MDNode *, DIE * > & getAbstractSPDies ()
void insertDIE (const MDNode *TypeMD, DIE *Die)
DIE * getDIE (const MDNode *TypeMD)
Detailed Description
Definition at line 36 of file DwarfFile.h.
Constructor & Destructor Documentation
DwarfFile()
llvm::DwarfFile::DwarfFile (AsmPrinter * AP, DwarfDebug & DD, StringRef Pref, BumpPtrAllocator & DA)
Definition at line 20 of file DwarfFile.cpp.
~DwarfFile()
llvm::DwarfFile::~DwarfFile ()
Definition at line 24 of file DwarfFile.cpp.
Member Function Documentation
addScopeVariable()
void llvm::DwarfFile::addScopeVariable (LexicalScope * LS, DbgVariable * Var)
Definition at line 149 of file DwarfFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::DIVariable::getArgNumber(), llvm::DbgVariable::getVariable(), I, llvm::SmallVectorImpl< T >::insert(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
addUnit()
void llvm::DwarfFile::addUnit (std::unique_ptr< DwarfUnit > U)
Add a unit to the list of CUs.
Definition at line 45 of file DwarfFile.cpp.
assignAbbrevNumber()
void llvm::DwarfFile::assignAbbrevNumber (DIEAbbrev & Abbrev)
Define a unique number for the abbreviation.
Definition at line 28 of file DwarfFile.cpp.
References llvm::DIEAbbrev::getNumber(), and llvm::DIEAbbrev::setNumber().
Referenced by computeSizeAndOffset().
computeSizeAndOffset()
unsigned llvm::DwarfFile::computeSizeAndOffset (DIE & Die, unsigned Offset)
Compute the size and offset of a DIE given an incoming Offset.
Definition at line 85 of file DwarfFile.cpp.
References assignAbbrevNumber(), computeSizeAndOffset(), llvm::DIE::getAbbrev(), llvm::DIE::getAbbrevNumber(), llvm::DIE::getChildren(), llvm::DIEAbbrev::getData(), llvm::DIE::getOffset(), llvm::getULEB128Size(), llvm::DIE::getValues(), llvm::DIEAbbrev::hasChildren(), N, llvm::DIE::setOffset(), llvm::DIE::setSize(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by computeSizeAndOffset(), and computeSizeAndOffsets().
computeSizeAndOffsets()
void llvm::DwarfFile::computeSizeAndOffsets ()
Compute the size and offset of all the DIEs.
Definition at line 64 of file DwarfFile.cpp.
References computeSizeAndOffset().
emitAbbrevs()
void llvm::DwarfFile::emitAbbrevs (const MCSection * Section)
Emit a set of abbreviations to the specific section.
Definition at line 123 of file DwarfFile.cpp.
emitStrings()
void llvm::DwarfFile::emitStrings (const MCSection * StrSection, const MCSection * OffsetSection = nullptr)
Emit all of the strings to the section given.
Definition at line 144 of file DwarfFile.cpp.
emitUnits()
void llvm::DwarfFile::emitUnits (const MCSymbol * ASectionSym)
Emit all of the units to the section listed with the given abbreviation section.
Definition at line 51 of file DwarfFile.cpp.
getAbstractSPDies()
DenseMap< const MDNode *, DIE * > & llvm::DwarfFile::getAbstractSPDies () inline
Definition at line 104 of file DwarfFile.h.
getDIE()
DIE * llvm::DwarfFile::getDIE (const MDNode * TypeMD) inline
Definition at line 111 of file DwarfFile.h.
getScopeVariables()
DenseMap< LexicalScope *, SmallVector< DbgVariable *, 8 > > & llvm::DwarfFile::getScopeVariables () inline
Definition at line 100 of file DwarfFile.h.
getStringPool()
DwarfStringPool & llvm::DwarfFile::getStringPool () inline
Returns the string pool.
Definition at line 96 of file DwarfFile.h.
getUnits()
const SmallVectorImpl< std::unique_ptr< DwarfUnit > > & llvm::DwarfFile::getUnits () inline
Definition at line 70 of file DwarfFile.h.
insertDIE()
void llvm::DwarfFile::insertDIE (const MDNode * TypeMD, DIE * Die) inline
Definition at line 108 of file DwarfFile.h.
The documentation for this class was generated from the following files:
DwarfFile.h
DwarfFile.cpp