LLVM: llvm::CGSCCAnalysisManagerFunctionProxy Class Reference
LLVM API Documentation
llvm::CGSCCAnalysisManagerFunctionProxy Class Reference
A function analysis which acts as a proxy for a CGSCC analysis manager.
#include <CGSCCPassManager.h>
Classes
class Result
Result proxy object for ModuleAnalysisManagerFunctionProxy.
Public Member Functions
CGSCCAnalysisManagerFunctionProxy (const CGSCCAnalysisManager &CGAM)
CGSCCAnalysisManagerFunctionProxy (const CGSCCAnalysisManagerFunctionProxy &Arg)
CGSCCAnalysisManagerFunctionProxy (CGSCCAnalysisManagerFunctionProxy &&Arg)
CGSCCAnalysisManagerFunctionProxy & operator= (CGSCCAnalysisManagerFunctionProxy RHS)
Result run (Function &)
Run the analysis pass and create our proxy result object. Nothing to see here, it just forwards the CGAM reference into the result.
Static Public Member Functions
static void * ID ()
static StringRef name ()
Detailed Description
A function analysis which acts as a proxy for a CGSCC analysis manager.
This primarily provides an accessor to a parent CGSCC analysis manager to function passes. Only the const interface of the CGSCC analysis manager is provided to indicate that once inside of a function analysis pass you cannot request a CGSCC analysis to actually run. Instead, the user must rely on the getCachedResult API.
This proxy doesn't manage the invalidation in any way. That is handled by the recursive return path of each layer of the pass manager and the returned PreservedAnalysis set.
Definition at line 360 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
CGSCCAnalysisManagerFunctionProxy() [1/3]
llvm::CGSCCAnalysisManagerFunctionProxy::CGSCCAnalysisManagerFunctionProxy (const CGSCCAnalysisManager & CGAM) inline
Definition at line 388 of file CGSCCPassManager.h.
Referenced by CGSCCAnalysisManagerFunctionProxy(), CGSCCAnalysisManagerFunctionProxy(), and operator=().
CGSCCAnalysisManagerFunctionProxy() [2/3]
llvm::CGSCCAnalysisManagerFunctionProxy::CGSCCAnalysisManagerFunctionProxy (const CGSCCAnalysisManagerFunctionProxy & Arg) inline
Definition at line 392 of file CGSCCPassManager.h.
References CGSCCAnalysisManagerFunctionProxy().
CGSCCAnalysisManagerFunctionProxy() [3/3]
llvm::CGSCCAnalysisManagerFunctionProxy::CGSCCAnalysisManagerFunctionProxy (CGSCCAnalysisManagerFunctionProxy && Arg) inline
Definition at line 395 of file CGSCCPassManager.h.
References CGSCCAnalysisManagerFunctionProxy().
Member Function Documentation
ID()
void * llvm::CGSCCAnalysisManagerFunctionProxy::ID () inline static
Definition at line 384 of file CGSCCPassManager.h.
name()
StringRef llvm::CGSCCAnalysisManagerFunctionProxy::name () inline static
Definition at line 386 of file CGSCCPassManager.h.
operator=()
CGSCCAnalysisManagerFunctionProxy & llvm::CGSCCAnalysisManagerFunctionProxy::operator= (CGSCCAnalysisManagerFunctionProxy RHS) inline
Definition at line 398 of file CGSCCPassManager.h.
References CGSCCAnalysisManagerFunctionProxy(), and std::swap().
run()
Result llvm::CGSCCAnalysisManagerFunctionProxy::run (Function &) inline
Run the analysis pass and create our proxy result object. Nothing to see here, it just forwards the CGAM reference into the result.
Definition at line 406 of file CGSCCPassManager.h.
The documentation for this class was generated from the following files:
CGSCCPassManager.h
CGSCCPassManager.cpp