LLVM: llvm::HexagonTargetLowering Class Reference
LLVM API Documentation
llvm::HexagonTargetLowering Class Reference
#include <HexagonISelLowering.h>
Public Member Functions
HexagonTargetLowering (const TargetMachine &targetmachine)
bool IsEligibleForTailCallOptimization (SDValue Callee, CallingConv::ID CalleeCC, bool isVarArg, bool isCalleeStructRet, bool isCallerStructRet, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, const SmallVectorImpl< ISD::InputArg > &Ins, SelectionDAG &DAG) const
bool isTruncateFree (Type *Ty1, Type *Ty2) const override
bool isTruncateFree (EVT VT1, EVT VT2) const override
bool allowTruncateForTailCall (Type *Ty1, Type *Ty2) const override
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
const char * getTargetNodeName (unsigned Opcode) const override
This method returns the name of a target specific DAG node.
SDValue LowerBR_JT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG &DAG) const
SDValue LowerINLINEASM (SDValue Op, SelectionDAG &DAG) const
SDValue LowerEH_LABEL (SDValue Op, SelectionDAG &DAG) const
SDValue LowerEH_RETURN (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFormalArguments (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, SDLoc dl, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals) const override
SDValue LowerGLOBALADDRESS (SDValue Op, SelectionDAG &DAG) const
SDValue LowerBlockAddress (SDValue Op, SelectionDAG &DAG) const
SDValue LowerCall (TargetLowering::CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals) const override
SDValue LowerCallResult (SDValue Chain, SDValue InFlag, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, SDLoc dl, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals, const SmallVectorImpl< SDValue > &OutVals, SDValue Callee) const
SDValue LowerFRAMEADDR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerATOMIC_FENCE (SDValue Op, SelectionDAG &DAG) const
SDValue LowerRETURNADDR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerReturn (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, SDLoc dl, SelectionDAG &DAG) const override
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *BB) const override
SDValue LowerVASTART (SDValue Op, SelectionDAG &DAG) const
SDValue LowerConstantPool (SDValue Op, SelectionDAG &DAG) const
EVT getSetCCResultType (LLVMContext &C, EVT VT) const override
Return the ValueType of the result of SETCC operations.
bool getPostIndexedAddressParts (SDNode *N, SDNode *Op, SDValue &Base, SDValue &Offset, ISD::MemIndexedMode &AM, SelectionDAG &DAG) const override
std::pair< unsigned, const TargetRegisterClass * > getRegForInlineAsmConstraint (const std::string &Constraint, MVT VT) const override
SDValue LowerINTRINSIC_WO_CHAIN (SDValue Op, SelectionDAG &DAG) const
bool isLegalAddressingMode (const AddrMode &AM, Type *Ty) const override
bool isFPImmLegal (const APFloat &Imm, EVT VT) const override
bool isLegalICmpImmediate (int64_t Imm) const override
Public Member Functions inherited from llvm::TargetLowering
TargetLowering (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
virtual bool getPreIndexedAddressParts (SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
virtual unsigned getJumpTableEncoding () const
virtual const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *, const MachineBasicBlock *, unsigned, MCContext &) const
virtual SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const
Returns relocation base for the given PIC jumptable.
virtual const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const
virtual bool isOffsetFoldingLegal (const GlobalAddressSDNode *GA) const
bool isInTailCallPosition (SelectionDAG &DAG, SDNode *Node, SDValue &Chain) const
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, SDLoc DL) const
std::pair< SDValue, SDValue > makeLibCall (SelectionDAG &DAG, RTLIB::Libcall LC, EVT RetVT, const SDValue *Ops, unsigned NumOps, bool isSigned, SDLoc dl, bool doesNotReturn=false, bool isReturnValueUsed=true) const
Returns a pair of (return value, chain).
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedMask, APInt &KnownZero, APInt &KnownOne, TargetLoweringOpt &TLO, unsigned Depth=0) const
virtual void computeKnownBitsForTargetNode (const SDValue Op, APInt &KnownZero, APInt &KnownOne, const SelectionDAG &DAG, unsigned Depth=0) const
virtual unsigned ComputeNumSignBitsForTargetNode (SDValue Op, const SelectionDAG &DAG, unsigned Depth=0) const
bool isConstTrueVal (const SDNode *N) const
bool isConstFalseVal (const SDNode *N) const
SDValue SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo &DCI, SDLoc dl) const
virtual bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const
virtual SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const
virtual bool isDesirableToCommuteWithShift (const SDNode *N) const
Return true if it is profitable to move a following shift through this.
virtual bool isTypeDesirableForOp (unsigned, EVT VT) const
virtual bool isDesirableToTransformToIntegerOp (unsigned, EVT) const
virtual bool IsDesirableToPromoteOp (SDValue, EVT &) const
std::pair< SDValue, SDValue > LowerCallTo (CallLoweringInfo &CLI) const
virtual void HandleByVal (CCState *, unsigned &, unsigned) const
Target-specific cleanup for formal ByVal parameters.
virtual bool CanLowerReturn (CallingConv::ID, MachineFunction &, bool, const SmallVectorImpl< ISD::OutputArg > &, LLVMContext &) const
virtual bool isUsedByReturnOnly (SDNode *, SDValue &) const
virtual bool mayBeEmittedAsTailCall (CallInst *) const
virtual const char * getClearCacheBuiltinName () const
virtual unsigned getRegisterByName (const char *RegName, EVT VT) const
virtual EVT getTypeForExtArgOrReturn (LLVMContext &Context, EVT VT, ISD::NodeType) const
virtual bool functionArgumentNeedsConsecutiveRegisters (Type *Ty, CallingConv::ID CallConv, bool isVarArg) const
virtual const MCPhysReg * getScratchRegisters (CallingConv::ID CC) const
virtual SDValue prepareVolatileOrAtomicLoad (SDValue Chain, SDLoc DL, SelectionDAG &DAG) const
virtual void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const
virtual void ReplaceNodeResults (SDNode *, SmallVectorImpl< SDValue > &, SelectionDAG &) const
virtual FastISel * createFastISel (FunctionLoweringInfo &, const TargetLibraryInfo *) const
bool verifyReturnAddressArgumentIsConstant (SDValue Op, SelectionDAG &DAG) const
virtual bool ExpandInlineAsm (CallInst *) const
virtual AsmOperandInfoVector ParseConstraints (ImmutableCallSite CS) const
virtual ConstraintWeight getMultipleConstraintMatchWeight (AsmOperandInfo &info, int maIndex) const
virtual ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const
virtual void ComputeConstraintToUse (AsmOperandInfo &OpInfo, SDValue Op, SelectionDAG *DAG=nullptr) const
virtual ConstraintType getConstraintType (const std::string &Constraint) const
Given a constraint, return the type of constraint it is for this target.
virtual const char * LowerXConstraint (EVT ConstraintVT) const
virtual void LowerAsmOperandForConstraint (SDValue Op, std::string &Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const
SDValue BuildExactSDIV (SDValue Op1, SDValue Op2, SDLoc dl, SelectionDAG &DAG) const
Given an exact SDIV by a constant, create a multiplication with the multiplicative inverse of the constant.
SDValue BuildSDIV (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, bool IsAfterLegalization, std::vector< SDNode * > *Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
SDValue BuildUDIV (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, bool IsAfterLegalization, std::vector< SDNode * > *Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
virtual SDValue BuildSDIVPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, std::vector< SDNode * > *Created) const
virtual bool combineRepeatedFPDivisors (unsigned NumUsers) const
virtual SDValue getRsqrtEstimate (SDValue Operand, DAGCombinerInfo &DCI, unsigned &RefinementSteps, bool &UseOneConstNR) const
virtual SDValue getRecipEstimate (SDValue Operand, DAGCombinerInfo &DCI, unsigned &RefinementSteps) const
bool expandMUL (SDNode *N, SDValue &Lo, SDValue &Hi, EVT HiLoVT, SelectionDAG &DAG, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
bool expandFP_TO_SINT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
virtual void AdjustInstrPostInstrSelection (MachineInstr *MI, SDNode *Node) const
virtual bool useLoadStackGuardNode () const
virtual bool shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const
Returns true if arguments should be sign-extended in lib calls.
Public Member Functions inherited from llvm::TargetLoweringBase
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
virtual ~TargetLoweringBase ()
const TargetMachine & getTargetMachine () const
const DataLayout * getDataLayout () const
const TargetLoweringObjectFile & getObjFileLowering () const
bool isBigEndian () const
bool isLittleEndian () const
virtual MVT getPointerTy (uint32_t=0) const
unsigned getPointerSizeInBits (uint32_t AS=0) const
unsigned getPointerTypeSizeInBits (Type *Ty) const
virtual MVT getScalarShiftAmountTy (EVT LHSTy) const
EVT getShiftAmountTy (EVT LHSTy) const
virtual MVT getVectorIdxTy () const
bool isSelectExpensive () const
Return true if the select operation is expensive for this target.
virtual bool isSelectSupported (SelectSupportKind) const
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (EVT VT) const
Return the preferred vector type legalization action.
virtual bool shouldExpandBuildVectorWithShuffles (EVT, unsigned DefinedValues) const
bool isIntDivCheap () const
bool isFsqrtCheap () const
Return true if sqrt(x) is as cheap or cheaper than 1 / rsqrt(x)
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
bool isPow2SDivCheap () const
Return true if pow2 sdiv is cheaper than a chain of sra/srl/add/sra.
bool isJumpExpensive () const
bool isPredictableSelectExpensive () const
virtual bool isLoadBitCastBeneficial (EVT, EVT) const
virtual bool isCheapToSpeculateCttz () const
Return true if it is cheap to speculate a call to intrinsic cttz.
virtual bool isCheapToSpeculateCtlz () const
Return true if it is cheap to speculate a call to intrinsic ctlz.
bool isMaskAndBranchFoldingLegal () const
Return if the target supports combining a chain like:
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
bool hasFloatingPointExceptions () const
Return true if target supports floating point exceptions.
virtual bool enableAggressiveFMAFusion (EVT VT) const
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
BooleanContent getBooleanContents (EVT Type) const
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual Sched::Preference getSchedulingPreference (SDNode *) const
virtual const TargetRegisterClass * getRegClassFor (MVT VT) const
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
virtual uint8_t getRepRegClassCostFor (MVT VT) const
bool isTypeLegal (EVT VT) const
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
LegalizeTypeAction getTypeAction (MVT VT) const
EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
virtual bool getTgtMemIntrinsic (IntrinsicInfo &, const CallInst &, unsigned) const
virtual bool isShuffleMaskLegal (const SmallVectorImpl< int > &, EVT) const
virtual bool canOpTrap (unsigned Op, EVT VT) const
virtual bool isVectorClearMaskLegal (const SmallVectorImpl< int > &, EVT) const
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT) const
bool isOperationLegalOrPromote (unsigned Op, EVT VT) const
bool isOperationExpand (unsigned Op, EVT VT) const
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
EVT getValueType (Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
virtual unsigned getByValTypeAlignment (Type *Ty) const
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
unsigned getNumRegisters (LLVMContext &Context, EVT VT) const
virtual bool ShouldShrinkFPConstant (EVT) const
virtual bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const
bool hasBigEndianPartOrdering (EVT VT) const
bool hasTargetDAGCombine (ISD::NodeType NT) const
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool allowsMisalignedMemoryAccesses (EVT, unsigned AddrSpace=0, unsigned Align=1, bool *=nullptr) const
Determine if the target supports unaligned memory accesses.
virtual EVT getOptimalMemOpType (uint64_t, unsigned, unsigned, bool, bool, bool, MachineFunction &) const
virtual bool isSafeMemOpType (MVT) const
bool usesUnderscoreSetJmp () const
Determine if we should use _setjmp or setjmp to implement llvm.setjmp.
bool usesUnderscoreLongJmp () const
Determine if we should use _longjmp or longjmp to implement llvm.longjmp.
int getMinimumJumpTableEntries () const
unsigned getStackPointerRegisterToSaveRestore () const
unsigned getExceptionPointerRegister () const
unsigned getExceptionSelectorRegister () const
unsigned getJumpBufSize () const
unsigned getJumpBufAlignment () const
unsigned getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
unsigned getMinFunctionAlignment () const
Return the minimum function alignment.
unsigned getPrefFunctionAlignment () const
Return the preferred function alignment.
virtual unsigned getPrefLoopAlignment (MachineLoop *ML=nullptr) const
Return the preferred loop alignment.
bool getInsertFencesForAtomic () const
virtual bool getStackCookieLocation (unsigned &, unsigned &) const
virtual unsigned getMaximalGlobalOffset () const
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast between SrcAS and DestAS is a noop.
virtual bool shouldExpandAtomicStoreInIR (StoreInst *SI) const
virtual bool shouldExpandAtomicLoadInIR (LoadInst *LI) const
virtual bool shouldExpandAtomicRMWInIR (AtomicRMWInst *RMWI) const
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
virtual void resetOperationActions ()
Reset the operation actions based on target options.
virtual bool GetAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value * > &, Type *&) const
virtual int getScalingFactorCost (const AddrMode &AM, Type *Ty) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
virtual bool isLegalAddImmediate (int64_t) const
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
virtual bool isZExtFree (Type *, Type *) const
virtual bool isZExtFree (EVT, EVT) const
virtual bool hasPairedLoad (Type *, unsigned &) const
virtual bool hasPairedLoad (EVT, unsigned &) const
virtual bool isZExtFree (SDValue Val, EVT VT2) const
virtual bool isFPExtFree (EVT VT) const
virtual bool isFNegFree (EVT VT) const
virtual bool isFAbsFree (EVT VT) const
virtual bool isFMAFasterThanFMulAndFAdd (EVT) const
virtual bool isNarrowingProfitable (EVT, EVT) const
virtual bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const
Return true if it is beneficial to convert a load of a constant to just the constant itself. On some targets it might be more efficient to use a combination of arithmetic instructions to materialize the constant instead of loading it from a constant pool.
virtual bool isExtractSubvectorCheap (EVT ResVT, unsigned Index) const
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
LegalizeKind getTypeConversion (LLVMContext &Context, EVT VT) const
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
std::pair< unsigned, MVT > getTypeLegalizationCost (Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
virtual bool hasLoadLinkedStoreConditional () const
virtual Value * emitLoadLinked (IRBuilder<> &Builder, Value *Addr, AtomicOrdering Ord) const
virtual Value * emitStoreConditional (IRBuilder<> &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const
virtual Instruction * emitLeadingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const
virtual Instruction * emitTrailingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const
Public Attributes
const TargetMachine & TM
Additional Inherited Members
Public Types inherited from llvm::TargetLowering
enum ConstraintType {
C_Register , C_RegisterClass , C_Memory , C_Other ,
C_Unknown
}
enum ConstraintWeight {
CW_Invalid = -1 , CW_Okay = 0 , CW_Good = 1 , CW_Better = 2 ,
CW_Best = 3 , CW_SpecificReg = CW_Okay , CW_Register = CW_Good , CW_Memory = CW_Better ,
CW_Constant = CW_Best , CW_Default = CW_Okay
}
typedef std::vector< ArgListEntry > ArgListTy
typedef std::vector< AsmOperandInfo > AsmOperandInfoVector
Public Types inherited from llvm::TargetLoweringBase
enum LegalizeAction { Legal , Promote , Expand , Custom }
enum LegalizeTypeAction {
TypeLegal , TypePromoteInteger , TypeExpandInteger , TypeSoftenFloat ,
TypeExpandFloat , TypeScalarizeVector , TypeSplitVector , TypeWidenVector
}
enum BooleanContent { UndefinedBooleanContent , ZeroOrOneBooleanContent , ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect , ScalarCondVectorVal , VectorMaskSelect }
Enum that describes what type of support for selects the target has.
typedef std::pair< LegalizeTypeAction, EVT > LegalizeKind
Static Public Member Functions inherited from llvm::TargetLoweringBase
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions inherited from llvm::TargetLoweringBase
void initActions ()
Initialize all of the actions to default values.
void setBooleanContents (BooleanContent Ty)
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
void setBooleanVectorContents (BooleanContent Ty)
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setUseUnderscoreSetJmp (bool Val)
void setUseUnderscoreLongJmp (bool Val)
void setMinimumJumpTableEntries (int Val)
void setStackPointerRegisterToSaveRestore (unsigned R)
void setExceptionPointerRegister (unsigned R)
void setExceptionSelectorRegister (unsigned R)
void setSelectIsExpensive (bool isExpensive=true)
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
void setHasExtractBitsInsn (bool hasExtractInsn=true)
void setJumpIsExpensive (bool isExpensive=true)
void setIntDivIsCheap (bool isCheap=true)
void setFsqrtIsCheap (bool isCheap=true)
void setHasFloatingPointExceptions (bool FPExceptions=true)
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void setPow2SDivIsCheap (bool isCheap=true)
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
void clearRegisterClasses ()
Remove all register classes.
void clearOperationActions ()
Remove all operation actions.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (MVT VT) const
void computeRegisterProperties ()
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
void setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action)
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
void setTargetDAGCombine (ISD::NodeType NT)
void setJumpBufSize (unsigned Size)
Set the target's required jmp_buf buffer size (in bytes); default is 200.
void setJumpBufAlignment (unsigned Align)
void setMinFunctionAlignment (unsigned Align)
Set the target's minimum function alignment (in log2(bytes))
void setPrefFunctionAlignment (unsigned Align)
void setPrefLoopAlignment (unsigned Align)
void setMinStackArgumentAlignment (unsigned Align)
Set the minimum stack alignment of an argument (in log2(bytes)).
void setInsertFencesForAtomic (bool fence)
bool isLegalRC (const TargetRegisterClass *RC) const
MachineBasicBlock * emitPatchPoint (MachineInstr *MI, MachineBasicBlock *MBB) const
Protected Attributes inherited from llvm::TargetLoweringBase
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
unsigned MaxStoresPerMemcpy
Specify maximum bytes of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
unsigned MaxStoresPerMemmove
Specify maximum bytes of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
bool PredictableSelectIsExpensive
bool MaskAndBranchFoldingIsLegal
bool EnableExtLdPromotion
Detailed Description
Definition at line 77 of file HexagonISelLowering.h.
Constructor & Destructor Documentation
HexagonTargetLowering()
HexagonTargetLowering::HexagonTargetLowering (const TargetMachine & targetmachine) explicit
Definition at line 1045 of file HexagonISelLowering.cpp.
References llvm::RTLIB::ADD_F32, llvm::RTLIB::ADD_F64, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::ATOMIC_FENCE, llvm::ISD::BlockAddress, llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::ISD::ConstantFP, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::TargetLoweringBase::Custom, llvm::RTLIB::DIV_F32, llvm::RTLIB::DIV_F64, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_RETURN, EmitJumpTables, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::MVT::fp_valuetypes(), llvm::RTLIB::FPEXT_F32_F64, llvm::ISD::FPOW, llvm::RTLIB::FPROUND_F64_F32, llvm::RTLIB::FPTOSINT_F32_I128, llvm::RTLIB::FPTOSINT_F32_I32, llvm::RTLIB::FPTOSINT_F32_I64, llvm::RTLIB::FPTOSINT_F64_I128, llvm::RTLIB::FPTOSINT_F64_I32, llvm::RTLIB::FPTOSINT_F64_I64, llvm::RTLIB::FPTOUINT_F32_I128, llvm::RTLIB::FPTOUINT_F32_I32, llvm::RTLIB::FPTOUINT_F32_I64, llvm::RTLIB::FPTOUINT_F64_I128, llvm::RTLIB::FPTOUINT_F64_I32, llvm::RTLIB::FPTOUINT_F64_I64, llvm::ISD::FREM, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::FSQRT, llvm::HexagonRegisterInfo::getStackRegister(), llvm::ISD::GlobalAddress, llvm::HexagonSubtarget::hasV5TOps(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INLINEASM, llvm::MVT::integer_valuetypes(), llvm::HexagonSubtarget::isSubtargetV2(), llvm::TargetLoweringBase::Legal, llvm::TargetLoweringBase::MaxStoresPerMemcpy, llvm::TargetLoweringBase::MaxStoresPerMemmove, llvm::ISD::MUL, llvm::RTLIB::MUL_F32, llvm::RTLIB::MUL_F64, llvm::RTLIB::O_F32, llvm::RTLIB::O_F64, llvm::RTLIB::OEQ_F32, llvm::RTLIB::OEQ_F64, llvm::RTLIB::OGE_F32, llvm::RTLIB::OGE_F64, llvm::RTLIB::OGT_F32, llvm::RTLIB::OGT_F64, llvm::RTLIB::OLE_F32, llvm::RTLIB::OLE_F64, llvm::RTLIB::OLT_F32, llvm::RTLIB::OLT_F64, llvm::MVT::Other, llvm::ISD::POST_INC, llvm::TargetLoweringBase::Promote, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SDIV, llvm::RTLIB::SDIV_I32, llvm::RTLIB::SDIV_I64, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::TargetLoweringBase::setCondCodeAction(), llvm::TargetLoweringBase::setExceptionPointerRegister(), llvm::TargetLoweringBase::setExceptionSelectorRegister(), llvm::TargetLoweringBase::setIndexedLoadAction(), llvm::TargetLoweringBase::setIndexedStoreAction(), llvm::TargetLoweringBase::setLibcallName(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setMinFunctionAlignment(), llvm::TargetLoweringBase::setMinimumJumpTableEntries(), llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setPrefLoopAlignment(), llvm::TargetLoweringBase::setSchedulingPreference(), llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::ISD::SEXTLOAD, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::RTLIB::SINTTOFP_I128_F32, llvm::RTLIB::SINTTOFP_I128_F64, llvm::RTLIB::SINTTOFP_I32_F32, llvm::RTLIB::SINTTOFP_I32_F64, llvm::RTLIB::SINTTOFP_I64_F32, llvm::RTLIB::SINTTOFP_I64_F64, llvm::ISD::SMUL_LOHI, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::RTLIB::SREM_I32, llvm::RTLIB::SREM_I64, llvm::ISD::SRL_PARTS, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::SUB, llvm::RTLIB::SUB_F32, llvm::RTLIB::SUB_F64, llvm::ISD::SUBC, llvm::ISD::SUBE, TM, llvm::ISD::TRUNCATE, llvm::ISD::UDIV, llvm::RTLIB::UDIV_I32, llvm::RTLIB::UDIV_I64, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::RTLIB::UINTTOFP_I32_F32, llvm::RTLIB::UINTTOFP_I32_F64, llvm::RTLIB::UINTTOFP_I64_F32, llvm::RTLIB::UINTTOFP_I64_F64, llvm::ISD::UMUL_LOHI, llvm::RTLIB::UNE_F32, llvm::RTLIB::UNE_F64, llvm::RTLIB::UO_F32, llvm::RTLIB::UO_F64, llvm::ISD::UREM, llvm::RTLIB::UREM_I32, llvm::RTLIB::UREM_I64, llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VASTART, and llvm::Sched::VLIW.
Member Function Documentation
allowTruncateForTailCall()
bool HexagonTargetLowering::allowTruncateForTailCall (Type * , Type *) const override virtual
Return true if a truncation from Ty1 to Ty2 is permitted when deciding whether a call is in tail position. Typically this means that both results would be assigned to the same register or stack slot, but it could mean the target performs adequate checks of its own before proceeding with the tail call.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1507 of file HexagonISelLowering.cpp.
References llvm::Type::getPrimitiveSizeInBits(), and llvm::Type::isIntegerTy().
EmitInstrWithCustomInserter()
MachineBasicBlock * HexagonTargetLowering::EmitInstrWithCustomInserter (MachineInstr * MI, MachineBasicBlock * MBB) const override virtual
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag. These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow.
Reimplemented from llvm::TargetLowering.
Definition at line 1577 of file HexagonISelLowering.cpp.
References llvm::HexagonMachineFunctionInfo::addAllocaAdjustInst(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), and llvm_unreachable.
getPostIndexedAddressParts()
bool HexagonTargetLowering::getPostIndexedAddressParts (SDNode * N, SDNode * Op, SDValue & Base, SDValue & Offset, ISD::MemIndexedMode & AM, SelectionDAG & DAG) const override virtual
getPostIndexedAddressParts - returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
Reimplemented from llvm::TargetLowering.
Definition at line 652 of file HexagonISelLowering.cpp.
References llvm::dyn_cast(), getIndexedAddressParts(), llvm::SDValue::getNode(), llvm::EVT::getSizeInBits(), llvm::MVT::i64, Is_PostInc_S4_Offset(), N, llvm::ISD::POST_DEC, llvm::ISD::POST_INC, and llvm::ISD::SEXTLOAD.
getRegForInlineAsmConstraint()
std::pair< unsigned, const TargetRegisterClass * > HexagonTargetLowering::getRegForInlineAsmConstraint (const std::string & Constraint, MVT VT) const override virtual
Given a physical register constraint (e.g. {edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer..
Reimplemented from llvm::TargetLowering.
Definition at line 1597 of file HexagonISelLowering.cpp.
References llvm::MVT::f32, llvm::MVT::f64, llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm_unreachable, and llvm::MVT::SimpleTy.
getSetCCResultType()
EVT llvm::HexagonTargetLowering::getSetCCResultType (LLVMContext & Context, EVT VT) const inline override virtual
Return the ValueType of the result of SETCC operations.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 150 of file HexagonISelLowering.h.
References llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::i1, and llvm::EVT::isVector().
getTargetNodeName()
const char * HexagonTargetLowering::getTargetNodeName (unsigned Opcode) const override virtual
This method returns the name of a target specific DAG node.
Reimplemented from llvm::TargetLowering.
Definition at line 1464 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::ADJDYNALLOC, llvm::HexagonISD::BR_JT, llvm::HexagonISD::BRFCC, llvm::HexagonISD::BRICC, llvm::HexagonISD::CALL, llvm::HexagonISD::CMPFCC, llvm::HexagonISD::CMPICC, llvm::HexagonISD::CONST32, llvm::HexagonISD::CONST32_GP, llvm::HexagonISD::CONST32_Int_Real, llvm::HexagonISD::EH_RETURN, llvm::HexagonISD::FTOI, llvm::HexagonISD::Hi, llvm::HexagonISD::ITOF, llvm::HexagonISD::Lo, llvm::HexagonISD::RET_FLAG, llvm::HexagonISD::SELECT_FCC, llvm::HexagonISD::SELECT_ICC, and llvm::HexagonISD::TC_RETURN.
IsEligibleForTailCallOptimization()
bool HexagonTargetLowering::IsEligibleForTailCallOptimization (SDValue Callee, CallingConv::ID CalleeCC, bool isVarArg, bool isCalleeStructRet, bool isCallerStructRet, const SmallVectorImpl< ISD::OutputArg > & Outs, const SmallVectorImpl< SDValue > & OutVals, const SmallVectorImpl< ISD::InputArg > & Ins, SelectionDAG & DAG) const
IsEligibleForTailCallOptimization - Check whether the call is eligible for tail call optimization. Targets which want to do tail call optimization should implement this function.
Definition at line 1666 of file HexagonISelLowering.cpp.
References llvm::dyn_cast(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), and llvm::SelectionDAG::getMachineFunction().
Referenced by LowerCall().
isFPImmLegal()
bool HexagonTargetLowering::isFPImmLegal (const APFloat & Imm, EVT VT) const override virtual
isFPImmLegal - Returns true if the target can instruction select the specified FP immediate natively. If false, the legalizer will materialize the FP immediate as a load from a constant pool.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1626 of file HexagonISelLowering.cpp.
References TM.
isLegalAddressingMode()
bool HexagonTargetLowering::isLegalAddressingMode (const AddrMode & AM, Type * Ty) const override virtual
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type. The type may be VoidTy, in which case only return true if the addressing mode is legal for a load/store of any legal type. TODO: Handle pre/postinc as well.
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1632 of file HexagonISelLowering.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, and llvm::TargetLoweringBase::AddrMode::Scale.
isLegalICmpImmediate()
bool HexagonTargetLowering::isLegalICmpImmediate (int64_t Imm) const override virtual
isLegalICmpImmediate - Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1659 of file HexagonISelLowering.cpp.
isTruncateFree() [1/2]
bool HexagonTargetLowering::isTruncateFree (EVT VT1, EVT VT2) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1499 of file HexagonISelLowering.cpp.
References llvm::EVT::getSimpleVT(), llvm::MVT::i32, llvm::MVT::i64, and llvm::EVT::isSimple().
isTruncateFree() [2/2]
bool HexagonTargetLowering::isTruncateFree (Type * , Type *) const override virtual
Return true if it's free to truncate a value of type Ty1 to type Ty2. e.g. On x86 it's free to truncate a i32 value in register EAX to i16 by referencing its sub-register AX.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1490 of file HexagonISelLowering.cpp.
References llvm::EVT::getEVT(), llvm::EVT::getSimpleVT(), llvm::MVT::i32, llvm::MVT::i64, and llvm::EVT::isSimple().
LowerATOMIC_FENCE()
SDValue HexagonTargetLowering::LowerATOMIC_FENCE (SDValue Op, SelectionDAG & DAG) const
Definition at line 1009 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::BARRIER, llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), and llvm::MVT::Other.
Referenced by LowerOperation().
LowerBlockAddress()
SDValue HexagonTargetLowering::LowerBlockAddress (SDValue Op, SelectionDAG & DAG) const
Definition at line 1034 of file HexagonISelLowering.cpp.
References llvm::cast(), llvm::HexagonISD::CONST32_GP, llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetBlockAddress(), and llvm::MVT::i32.
Referenced by LowerOperation().
LowerBR_JT()
SDValue HexagonTargetLowering::LowerBR_JT (SDValue Op, SelectionDAG & DAG) const
Definition at line 744 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::HexagonISD::BR_JT, llvm::cast(), llvm::BlockAddress::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::SelectionDAG::getConstant(), llvm::JumpTableSDNode::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetJumpTable(), llvm::MVT::i32, llvm::MVT::Other, llvm::MachineBasicBlock::setHasAddressTaken(), llvm::ISD::SHL, and llvm::HexagonISD::WrapperJT.
Referenced by LowerOperation().
LowerCall()
SDValue HexagonTargetLowering::LowerCall (TargetLowering::CallLoweringInfo & CLI, SmallVectorImpl< SDValue > & InVals) const override virtual
LowerCall - Functions arguments are copied from virtual regs to (physical regs)/(stack frame), CALLSEQ_START and CALLSEQ_END are emitted.
Reimplemented from llvm::TargetLowering.
Definition at line 395 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::CCValAssign::AExt, llvm::ISD::ANY_EXTEND, llvm::HexagonISD::CALL, llvm::TargetLowering::CallLoweringInfo::CallConv, llvm::TargetLowering::CallLoweringInfo::Callee, CC_Hexagon(), CC_Hexagon_VarArg(), llvm::TargetLowering::CallLoweringInfo::Chain, CreateCopyOfByValArgument(), llvm::TargetLowering::CallLoweringInfo::DAG, llvm::dbgs(), DEBUG, llvm::TargetLowering::CallLoweringInfo::DL, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::flag_aligned_memcpy, llvm::CCValAssign::Full, G, llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::MachineFunction::getFunction(), llvm::Function::getFunctionType(), llvm::SelectionDAG::getIntPtrConstant(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::FunctionType::getNumParams(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::HexagonRegisterInfo::getStackRegister(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getSubtarget(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::Function::hasStructRetAttr(), llvm::MVT::i32, llvm::TargetLowering::CallLoweringInfo::Ins, IsEligibleForTailCallOptimization(), llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::TargetLowering::CallLoweringInfo::IsVarArg, llvm::Function::isVarArg(), llvm_unreachable, LowerCallResult(), llvm::MVT::Other, llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::HexagonISD::TC_RETURN, llvm::ISD::TokenFactor, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
LowerCallResult()
SDValue HexagonTargetLowering::LowerCallResult (SDValue Chain, SDValue InFlag, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > & Ins, SDLoc dl, SelectionDAG & DAG, SmallVectorImpl< SDValue > & InVals, const SmallVectorImpl< SDValue > & OutVals, SDValue Callee) const
LowerCallResult - Lower the result values of an ISD::CALL into the appropriate copies out of appropriate physical registers. This assumes that Chain/InFlag are the input chain/flag to use, and that TheCall is the call being lowered. Returns a SDNode with the same number of values as the ISD::CALL.
Definition at line 363 of file HexagonISelLowering.cpp.
References llvm::CCState::AnalyzeCallResult(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getValue(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), RetCC_Hexagon(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by LowerCall().
LowerConstantPool()
SDValue HexagonTargetLowering::LowerConstantPool (SDValue Op, SelectionDAG & DAG) const
Definition at line 950 of file HexagonISelLowering.cpp.
References llvm::cast(), llvm::HexagonISD::CONST32, llvm::ConstantPoolSDNode::getAlignment(), llvm::ConstantPoolSDNode::getConstVal(), llvm::ConstantPoolSDNode::getMachineCPVal(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstantPool(), llvm::SDValue::getValueType(), and llvm::ConstantPoolSDNode::isMachineConstantPoolEntry().
Referenced by LowerOperation().
LowerDYNAMIC_STACKALLOC()
SDValue HexagonTargetLowering::LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG & DAG) const
Definition at line 782 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::ADJDYNALLOC, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore(), llvm::HexagonRegisterInfo::getStackRegister(), llvm::SelectionDAG::getSubtarget(), llvm::MVT::i32, llvm::ISD::SUB, and llvm::Sub.
Referenced by LowerOperation().
LowerEH_LABEL()
SDValue llvm::HexagonTargetLowering::LowerEH_LABEL (SDValue Op, SelectionDAG & DAG) const
LowerEH_RETURN()
SDValue HexagonTargetLowering::LowerEH_RETURN (SDValue Op, SelectionDAG & DAG) const
Definition at line 1520 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::HexagonISD::EH_RETURN, llvm::SelectionDAG::getCopyToReg(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getStore(), llvm::MVT::Other, and llvm::HexagonMachineFunctionInfo::setHasEHReturn().
Referenced by LowerOperation().
LowerFormalArguments()
SDValue HexagonTargetLowering::LowerFormalArguments (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::InputArg > & , SDLoc , SelectionDAG & , SmallVectorImpl< SDValue > &) const override virtual
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG. The implementation should fill in the InVals array with legal-type argument values, and return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 827 of file HexagonISelLowering.cpp.
References llvm::MachineRegisterInfo::addLiveIn(), llvm::CCState::AnalyzeFormalArguments(), CC_Hexagon(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SmallVectorBase::empty(), llvm::MVT::f32, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::CCState::getNextStackOffset(), llvm::SelectionDAG::getNode(), llvm::MachineFunction::getRegInfo(), llvm::MVT::getStoreSizeInBits(), HEXAGON_LRFP_SIZE, Hexagon_PointerSize, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::HexagonMachineFunctionInfo::setVarArgsFrameIndex(), and llvm::ISD::TokenFactor.
LowerFRAMEADDR()
SDValue HexagonTargetLowering::LowerFRAMEADDR (SDValue Op, SelectionDAG & DAG) const
Definition at line 991 of file HexagonISelLowering.cpp.
References llvm::cast(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::HexagonRegisterInfo::getFrameRegister(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSubtarget(), llvm::SDValue::getValueType(), and llvm::MachineFrameInfo::setFrameAddressIsTaken().
Referenced by LowerOperation(), and LowerRETURNADDR().
LowerGLOBALADDRESS()
SDValue HexagonTargetLowering::LowerGLOBALADDRESS (SDValue Op, SelectionDAG & DAG) const
Definition at line 1016 of file HexagonISelLowering.cpp.
References llvm::cast(), llvm::HexagonISD::CONST32, llvm::HexagonISD::CONST32_GP, llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getObjFileLowering(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::TargetLoweringBase::getTargetMachine(), and llvm::HexagonTargetObjectFile::IsGlobalInSmallSection().
Referenced by LowerOperation().
LowerINLINEASM()
SDValue HexagonTargetLowering::LowerINLINEASM (SDValue Op, SelectionDAG & DAG) const
Definition at line 687 of file HexagonISelLowering.cpp.
References llvm::cast(), llvm::MachineFunction::getInfo(), llvm::InlineAsm::getKind(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::InlineAsm::getNumOperandRegisters(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::HexagonRegisterInfo::getRARegister(), llvm::SelectionDAG::getSubtarget(), llvm::SDValue::getValueType(), llvm::MVT::Glue, llvm::HexagonMachineFunctionInfo::hasClobberLR(), llvm::ISD::INLINEASM, llvm::InlineAsm::Kind_Clobber, llvm::InlineAsm::Kind_Imm, llvm::InlineAsm::Kind_Mem, llvm::InlineAsm::Kind_RegDef, llvm::InlineAsm::Kind_RegDefEarlyClobber, llvm::InlineAsm::Kind_RegUse, llvm_unreachable, llvm::InlineAsm::Op_FirstOperand, and llvm::HexagonMachineFunctionInfo::setHasClobberLR().
Referenced by LowerOperation().
LowerINTRINSIC_WO_CHAIN()
SDValue HexagonTargetLowering::LowerINTRINSIC_WO_CHAIN (SDValue Op, SelectionDAG & DAG) const
Definition at line 289 of file HexagonISelLowering.cpp.
Referenced by LowerOperation().
LowerOperation()
SDValue HexagonTargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const override virtual
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal. If the target has no operations that require custom lowering, it need not implement this. The default implementation of this aborts.
Reimplemented from llvm::TargetLowering.
Definition at line 1547 of file HexagonISelLowering.cpp.
References llvm::ISD::ATOMIC_FENCE, llvm::ISD::BlockAddress, llvm::ISD::BR_JT, llvm::ISD::ConstantPool, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_RETURN, llvm::ISD::FRAMEADDR, llvm::SDValue::getOpcode(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::INLINEASM, llvm::ISD::INTRINSIC_WO_CHAIN, llvm_unreachable, LowerATOMIC_FENCE(), LowerBlockAddress(), LowerBR_JT(), LowerConstantPool(), LowerDYNAMIC_STACKALLOC(), LowerEH_RETURN(), LowerFRAMEADDR(), LowerGLOBALADDRESS(), LowerINLINEASM(), LowerINTRINSIC_WO_CHAIN(), LowerRETURNADDR(), LowerVASTART(), llvm::ISD::RETURNADDR, llvm::ISD::SELECT, and llvm::ISD::VASTART.
LowerReturn()
SDValue HexagonTargetLowering::LowerReturn (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::OutputArg > & , const SmallVectorImpl< SDValue > & , SDLoc , SelectionDAG &) const override virtual
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG. The implementation should return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 315 of file HexagonISelLowering.cpp.
References llvm::CCState::AnalyzeReturn(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyToReg(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getValue(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::HexagonISD::RET_FLAG, RetCC_Hexagon(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
LowerRETURNADDR()
SDValue HexagonTargetLowering::LowerRETURNADDR (SDValue Op, SelectionDAG & DAG) const
Definition at line 965 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineFunction::addLiveIn(), llvm::cast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MCRegisterInfo::getRARegister(), llvm::TargetLoweringBase::getRegClassFor(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::SelectionDAG::getSubtarget(), llvm::SDValue::getValueType(), llvm::MVT::i32, LowerFRAMEADDR(), llvm::MachineFrameInfo::setReturnAddressIsTaken(), and llvm::TargetLowering::verifyReturnAddressArgumentIsConstant().
Referenced by LowerOperation().
LowerVASTART()
SDValue HexagonTargetLowering::LowerVASTART (SDValue Op, SelectionDAG & DAG) const
Definition at line 937 of file HexagonISelLowering.cpp.
References llvm::cast(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getStore(), llvm::HexagonMachineFunctionInfo::getVarArgsFrameIndex(), and llvm::MVT::i32.
Referenced by LowerOperation().
Member Data Documentation
TM
const TargetMachine& llvm::HexagonTargetLowering::TM
Definition at line 84 of file HexagonISelLowering.h.
Referenced by HexagonTargetLowering(), and isFPImmLegal().
The documentation for this class was generated from the following files:
HexagonISelLowering.h
HexagonISelLowering.cpp