LLVM: llvm::constant_iterator Class Reference
LLVM API Documentation
llvm::constant_iterator Class Reference
#include <ConstantsScanner.h>
Public Member Functions
constant_iterator (const Function *F)
constant_iterator (const Function *F, bool)
bool operator== (const _Self &x) const
bool operator!= (const _Self &x) const
pointer operator* () const
pointer operator-> () const
_Self & operator++ ()
_Self operator++ (int)
bool atEnd () const
Detailed Description
Definition at line 25 of file ConstantsScanner.h.
Constructor & Destructor Documentation
constant_iterator() [1/2]
llvm::constant_iterator::constant_iterator (const Function * F) inline
Definition at line 39 of file ConstantsScanner.h.
References F, llvm::inst_begin(), and llvm::inst_end().
constant_iterator() [2/2]
llvm::constant_iterator::constant_iterator (const Function * F, bool) inline
Definition at line 46 of file ConstantsScanner.h.
References F, and llvm::inst_end().
Member Function Documentation
atEnd()
bool llvm::constant_iterator::atEnd () const inline
Definition at line 80 of file ConstantsScanner.h.
operator!=()
bool llvm::constant_iterator::operator!= (const _Self & x) const inline
Definition at line 52 of file ConstantsScanner.h.
References operator==().
operator*()
pointer llvm::constant_iterator::operator* () const inline
Definition at line 54 of file ConstantsScanner.h.
References llvm::cast().
Referenced by operator->().
operator++() [1/2]
_Self & llvm::constant_iterator::operator++ () inline
Definition at line 60 of file ConstantsScanner.h.
operator++() [2/2]
_Self llvm::constant_iterator::operator++ (int) inline
Definition at line 76 of file ConstantsScanner.h.
operator->()
pointer llvm::constant_iterator::operator-> () const inline
Definition at line 58 of file ConstantsScanner.h.
References operator*().
operator==()
bool llvm::constant_iterator::operator== (const _Self & x) const inline
Definition at line 50 of file ConstantsScanner.h.
Referenced by operator!=().
The documentation for this class was generated from the following file:
ConstantsScanner.h