LLVM: llvm::opt::InputArgList Class Reference
LLVM API Documentation
llvm::opt::InputArgList Class Reference
#include <ArgList.h>
Public Member Functions
InputArgList (const char *const *ArgBegin, const char *const *ArgEnd)
~InputArgList ()
const char * getArgString (unsigned Index) const override
getArgString - Return the input argument string at Index.
unsigned getNumInputArgStrings () const override
Arg Synthesis
unsigned MakeIndex (StringRef String0) const
MakeIndex - Get an index for the given string(s).
unsigned MakeIndex (StringRef String0, StringRef String1) const
const char * MakeArgString (StringRef Str) const override
const char * MakeArgString (const char *Str) const
const char * MakeArgString (std::string Str) const
const char * MakeArgString (const Twine &Str) const
Public Member Functions inherited from llvm::opt::ArgList
void append (Arg *A)
append - Append A to the arg list.
arglist_type & getArgs ()
const arglist_type & getArgs () const
unsigned size () const
bool hasArgNoClaim (OptSpecifier Id) const
bool hasArg (OptSpecifier Id) const
bool hasArg (OptSpecifier Id0, OptSpecifier Id1) const
bool hasArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const
Arg * getLastArgNoClaim (OptSpecifier Id) const
Arg * getLastArgNoClaim (OptSpecifier Id0, OptSpecifier Id1) const
Arg * getLastArg (OptSpecifier Id) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5, OptSpecifier Id6) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5, OptSpecifier Id6, OptSpecifier Id7) const
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
arg_iterator filtered_begin (OptSpecifier Id0=0U, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
arg_iterator filtered_end () const
iterator_range< arg_iterator > filtered (OptSpecifier Id0=0U, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
void eraseArg (OptSpecifier Id)
eraseArg - Remove any option matching Id.
StringRef getLastArgValue (OptSpecifier Id, StringRef Default="") const
getLastArgValue - Return the value of the last argument, or a default.
std::vector< std::string > getAllArgValues (OptSpecifier Id) const
bool hasFlag (OptSpecifier Pos, OptSpecifier Neg, bool Default=true) const
bool hasFlag (OptSpecifier Pos, OptSpecifier PosAlias, OptSpecifier Neg, bool Default=true) const
void AddLastArg (ArgStringList &Output, OptSpecifier Id0) const
AddLastArg - Render only the last argument match Id0, if present.
void AddLastArg (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1) const
void AddAllArgs (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
AddAllArgs - Render all arguments matching the given ids.
void AddAllArgValues (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
void AddAllArgsTranslated (ArgStringList &Output, OptSpecifier Id0, const char *Translation, bool Joined=false) const
void ClaimAllArgs (OptSpecifier Id0) const
void ClaimAllArgs () const
const char * MakeArgString (const char *Str) const
const char * MakeArgString (std::string Str) const
const char * MakeArgString (const Twine &Str) const
const char * GetOrMakeJoinedArgString (unsigned Index, StringRef LHS, StringRef RHS) const
Create an arg string for (LHS + RHS), reusing the string at Index if possible.
Additional Inherited Members
Public Types inherited from llvm::opt::ArgList
typedef SmallVector< Arg *, 16 > arglist_type
typedef arglist_type::iterator iterator
typedef arglist_type::const_iterator const_iterator
typedef arglist_type::reverse_iterator reverse_iterator
typedef arglist_type::const_reverse_iterator const_reverse_iterator
Protected Member Functions inherited from llvm::opt::ArgList
ArgList ()
virtual ~ArgList ()
Detailed Description
Definition at line 299 of file ArgList.h.
Constructor & Destructor Documentation
InputArgList()
InputArgList::InputArgList (const char *const * ArgBegin, const char *const * ArgEnd)
Definition at line 306 of file ArgList.cpp.
~InputArgList()
InputArgList::~InputArgList ()
Definition at line 312 of file ArgList.cpp.
References llvm::opt::ArgList::begin(), and llvm::opt::ArgList::end().
Member Function Documentation
getArgString()
const char * llvm::opt::InputArgList::getArgString (unsigned Index) const inline override virtual
getArgString - Return the input argument string at Index.
Implements llvm::opt::ArgList.
Definition at line 322 of file ArgList.h.
Referenced by MakeArgString(), and llvm::opt::OptTable::ParseArgs().
getNumInputArgStrings()
unsigned llvm::opt::InputArgList::getNumInputArgStrings () const inline override virtual
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
Implements llvm::opt::ArgList.
Definition at line 326 of file ArgList.h.
MakeArgString() [1/4]
const char * llvm::opt::ArgList::MakeArgString (const char * Str) const inline
Definition at line 283 of file ArgList.h.
MakeArgString() [2/4]
const char * ArgList::MakeArgString (const Twine & Str) const
Definition at line 289 of file ArgList.cpp.
MakeArgString() [3/4]
const char * llvm::opt::ArgList::MakeArgString (std::string Str) const inline
Definition at line 286 of file ArgList.h.
MakeArgString() [4/4]
const char * InputArgList::MakeArgString (StringRef Str) const override virtual
MakeArgString - Construct a constant string pointer whose lifetime will match that of the ArgList.
Implements llvm::opt::ArgList.
Definition at line 337 of file ArgList.cpp.
References getArgString(), and MakeIndex().
MakeIndex() [1/2]
unsigned InputArgList::MakeIndex (StringRef String0) const
MakeIndex - Get an index for the given string(s).
Definition at line 318 of file ArgList.cpp.
Referenced by MakeArgString(), and MakeIndex().
MakeIndex() [2/2]
unsigned InputArgList::MakeIndex (StringRef String0, StringRef String1) const
Definition at line 328 of file ArgList.cpp.
References MakeIndex().
The documentation for this class was generated from the following files:
ArgList.h
ArgList.cpp