LLVM: llvm::sampleprof::SampleProfileWriterText Class Reference
LLVM API Documentation
llvm::sampleprof::SampleProfileWriterText Class Reference
Sample-based profile writer (text format).
#include <SampleProfWriter.h>
Public Member Functions
SampleProfileWriterText (StringRef F, std::error_code &EC)
bool write (StringRef FName, const FunctionSamples &S) override
Write samples to a text file.
bool write (const Module &M, StringMap< FunctionSamples > &P)
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
SampleProfileWriter (StringRef Filename, std::error_code &EC, sys::fs::OpenFlags Flags)
virtual ~SampleProfileWriter ()
bool write (const Function &F, const FunctionSamples &S)
Write sample profiles in S for function F.
bool write (const Module &M, StringMap< FunctionSamples > &P)
Write all the sample profiles for all the functions in M.
bool write (StringMap< FunctionSamples > &ProfileMap)
Write all the sample profiles in the given map of samples.
Additional Inherited Members
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (StringRef Filename, SampleProfileFormat Format)
Profile writer factory. Create a new writer based on the value of Format.
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriter
raw_fd_ostream OS
Output stream where to emit the profile to.
Detailed Description
Sample-based profile writer (text format).
Definition at line 84 of file SampleProfWriter.h.
Constructor & Destructor Documentation
SampleProfileWriterText()
llvm::sampleprof::SampleProfileWriterText::SampleProfileWriterText (StringRef F, std::error_code & EC) inline
Definition at line 86 of file SampleProfWriter.h.
References F, and llvm::sampleprof::SampleProfileWriter::SampleProfileWriter().
Member Function Documentation
write() [1/2]
bool llvm::sampleprof::SampleProfileWriterText::write (const Module & M, StringMap< FunctionSamples > & P) inline
Definition at line 90 of file SampleProfWriter.h.
References P, and llvm::sampleprof::SampleProfileWriter::write().
write() [2/2]
bool SampleProfileWriterText::write (StringRef FName, const FunctionSamples & S) override virtual
Write samples to a text file.
Implements llvm::sampleprof::SampleProfileWriter.
Definition at line 33 of file SampleProfWriter.cpp.
References llvm::sampleprof::LineLocation::Discriminator, llvm::sampleprof::FunctionSamples::empty(), llvm::sampleprof::FunctionSamples::getBodySamples(), llvm::sampleprof::SampleRecord::getCallTargets(), llvm::sampleprof::FunctionSamples::getHeadSamples(), llvm::sampleprof::SampleRecord::getSamples(), llvm::sampleprof::FunctionSamples::getTotalSamples(), I, llvm::sampleprof::LineLocation::LineOffset, and llvm::sampleprof::SampleProfileWriter::OS.
The documentation for this class was generated from the following files:
SampleProfWriter.h
SampleProfWriter.cpp