LLVM: llvm::MutableArrayRef< T > Class Template Reference
LLVM API Documentation
llvm::MutableArrayRef< T > Class Template Reference
#include <ArrayRef.h>
Public Types
typedef T * iterator
typedef std::reverse_iterator< iterator > reverse_iterator
Public Types inherited from llvm::ArrayRef< T >
typedef const T * iterator
typedef const T * const_iterator
typedef size_t size_type
typedef std::reverse_iterator< iterator > reverse_iterator
Public Member Functions
MutableArrayRef ()
Construct an empty MutableArrayRef.
MutableArrayRef (NoneType)
Construct an empty MutableArrayRef from None.
MutableArrayRef (T &OneElt)
Construct an MutableArrayRef from a single element.
MutableArrayRef (T *data, size_t length)
Construct an MutableArrayRef from a pointer and length.
MutableArrayRef (T *begin, T *end)
Construct an MutableArrayRef from a range.
MutableArrayRef (SmallVectorImpl< T > &Vec)
Construct an MutableArrayRef from a SmallVector.
MutableArrayRef (std::vector< T > &Vec)
Construct a MutableArrayRef from a std::vector.
template<size_t N>
LLVM_CONSTEXPR MutableArrayRef (T(&Arr)[N])
Construct an MutableArrayRef from a C array.
T * data () const
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
T & front () const
front - Get the first element.
T & back () const
back - Get the last element.
MutableArrayRef< T > slice (unsigned N) const
slice(n) - Chop off the first N elements of the array.
MutableArrayRef< T > slice (unsigned N, unsigned M) const
Operator Overloads
T & operator[] (size_t Index) const
Public Member Functions inherited from llvm::ArrayRef< T >
ArrayRef ()
Construct an empty ArrayRef.
ArrayRef (NoneType)
Construct an empty ArrayRef from None.
ArrayRef (const T &OneElt)
Construct an ArrayRef from a single element.
ArrayRef (const T *data, size_t length)
Construct an ArrayRef from a pointer and length.
ArrayRef (const T *begin, const T *end)
Construct an ArrayRef from a range.
template<typename U>
ArrayRef (const SmallVectorTemplateCommon< T, U > &Vec)
template<typename A>
ArrayRef (const std::vector< T, A > &Vec)
Construct an ArrayRef from a std::vector.
template<size_t N>
LLVM_CONSTEXPR ArrayRef (const T(&Arr)[N])
Construct an ArrayRef from a C array.
template<typename U>
ArrayRef (const ArrayRef< U * > &A, typename std::enable_if< std::is_convertible< U *const *, T const * >::value >::type *=0)
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
empty - Check if the array is empty.
const T * data () const
size_t size () const
size - Get the array size.
const T & front () const
front - Get the first element.
const T & back () const
back - Get the last element.
template<typename Allocator>
ArrayRef< T > copy (Allocator &A)
bool equals (ArrayRef RHS) const
equals - Check for element-wise equality.
ArrayRef< T > slice (unsigned N) const
slice(n) - Chop off the first N elements of the array.
ArrayRef< T > slice (unsigned N, unsigned M) const
ArrayRef< T > drop_back (unsigned N=1) const
const T & operator[] (size_t Index) const
std::vector< T > vec () const
operator std::vector< T > () const
bool equals (TRefOrNothing Arg0=TRefOrNothing(), TRefOrNothing Arg1=TRefOrNothing(), TRefOrNothing Arg2=TRefOrNothing(), TRefOrNothing Arg3=TRefOrNothing(), TRefOrNothing Arg4=TRefOrNothing(), TRefOrNothing Arg5=TRefOrNothing(), TRefOrNothing Arg6=TRefOrNothing(), TRefOrNothing Arg7=TRefOrNothing(), TRefOrNothing Arg8=TRefOrNothing(), TRefOrNothing Arg9=TRefOrNothing(), TRefOrNothing Arg10=TRefOrNothing(), TRefOrNothing Arg11=TRefOrNothing(), TRefOrNothing Arg12=TRefOrNothing(), TRefOrNothing Arg13=TRefOrNothing(), TRefOrNothing Arg14=TRefOrNothing(), TRefOrNothing Arg15=TRefOrNothing())
Predicate for testing that the array equals the exact sequence of arguments.
Detailed Description
template<typename T>
class llvm::MutableArrayRef< T >
MutableArrayRef - Represent a mutable reference to an array (0 or more elements consecutively in memory), i.e. a start pointer and a length. It allows various APIs to take and modify consecutive elements easily and conveniently.
This class does not own the underlying data, it is expected to be used in situations where the data resides in some other buffer, whose lifetime extends past that of the MutableArrayRef. For this reason, it is not in general safe to store a MutableArrayRef.
This is intended to be trivially copyable, so it should be passed by value.
Definition at line 263 of file ArrayRef.h.
Member Typedef Documentation
iterator
template<typename T> typedef T* llvm::MutableArrayRef< T >::iterator
Definition at line 265 of file ArrayRef.h.
reverse_iterator
template<typename T> typedef std::reverse_iterator<iterator> llvm::MutableArrayRef< T >::reverse_iterator
Definition at line 267 of file ArrayRef.h.
Constructor & Destructor Documentation
MutableArrayRef() [1/8]
template<typename T> llvm::MutableArrayRef< T >::MutableArrayRef () inline
Construct an empty MutableArrayRef.
Definition at line 270 of file ArrayRef.h.
References llvm::ArrayRef< T >::ArrayRef(), and T.
Referenced by slice(), and slice().
MutableArrayRef() [2/8]
template<typename T> llvm::MutableArrayRef< T >::MutableArrayRef (NoneType) inline
Construct an empty MutableArrayRef from None.
Definition at line 273 of file ArrayRef.h.
References llvm::ArrayRef< T >::ArrayRef(), and T.
MutableArrayRef() [3/8]
template<typename T> llvm::MutableArrayRef< T >::MutableArrayRef (T & OneElt) inline
Construct an MutableArrayRef from a single element.
Definition at line 276 of file ArrayRef.h.
References llvm::ArrayRef< T >::ArrayRef(), and T.
MutableArrayRef() [4/8]
template<typename T> llvm::MutableArrayRef< T >::MutableArrayRef (T * data, size_t length) inline
Construct an MutableArrayRef from a pointer and length.
Definition at line 279 of file ArrayRef.h.
References llvm::ArrayRef< T >::ArrayRef(), data(), and T.
MutableArrayRef() [5/8]
template<typename T> llvm::MutableArrayRef< T >::MutableArrayRef (T * begin, T * end) inline
Construct an MutableArrayRef from a range.
Definition at line 283 of file ArrayRef.h.
References llvm::ArrayRef< T >::ArrayRef(), begin(), end(), and T.
MutableArrayRef() [6/8]
template<typename T> llvm::MutableArrayRef< T >::MutableArrayRef (SmallVectorImpl< T > & Vec) inline
Construct an MutableArrayRef from a SmallVector.
Definition at line 286 of file ArrayRef.h.
References llvm::ArrayRef< T >::ArrayRef(), and T.
MutableArrayRef() [7/8]
template<typename T> llvm::MutableArrayRef< T >::MutableArrayRef (std::vector< T > & Vec) inline
Construct a MutableArrayRef from a std::vector.
Definition at line 290 of file ArrayRef.h.
References llvm::ArrayRef< T >::ArrayRef(), and T.
MutableArrayRef() [8/8]
template<typename T> template<size_t N> LLVM_CONSTEXPR llvm::MutableArrayRef< T >::MutableArrayRef (T(&) Arr[N]) inline
Construct an MutableArrayRef from a C array.
Definition at line 295 of file ArrayRef.h.
References llvm::ArrayRef< T >::ArrayRef(), LLVM_CONSTEXPR, N, and T.
Member Function Documentation
back()
template<typename T> T & llvm::MutableArrayRef< T >::back () const inline
back - Get the last element.
Definition at line 313 of file ArrayRef.h.
References data(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::size(), and T.
begin()
template<typename T> iterator llvm::MutableArrayRef< T >::begin () const inline
Definition at line 300 of file ArrayRef.h.
References data().
Referenced by FitWeights(), lowerV16I8VectorShuffle(), lowerV8I16SingleInputVectorShuffle(), lowerV8I16VectorShuffle(), MutableArrayRef(), and rend().
data()
template<typename T> T * llvm::MutableArrayRef< T >::data () const inline
Definition at line 298 of file ArrayRef.h.
References llvm::ArrayRef< T >::data(), and T.
Referenced by back(), begin(), end(), front(), MutableArrayRef(), operator[](), slice(), and slice().
end()
template<typename T> iterator llvm::MutableArrayRef< T >::end () const inline
Definition at line 301 of file ArrayRef.h.
References data(), and llvm::ArrayRef< T >::size().
Referenced by FitWeights(), lowerV16I8VectorShuffle(), lowerV8I16SingleInputVectorShuffle(), lowerV8I16VectorShuffle(), MutableArrayRef(), and rbegin().
front()
template<typename T> T & llvm::MutableArrayRef< T >::front () const inline
front - Get the first element.
Definition at line 307 of file ArrayRef.h.
References data(), llvm::ArrayRef< T >::empty(), and T.
operator[]()
template<typename T> T & llvm::MutableArrayRef< T >::operator[] (size_t Index) const inline
Definition at line 334 of file ArrayRef.h.
References data(), llvm::ArrayRef< T >::size(), and T.
rbegin()
template<typename T> reverse_iterator llvm::MutableArrayRef< T >::rbegin () const inline
Definition at line 303 of file ArrayRef.h.
References end().
rend()
template<typename T> reverse_iterator llvm::MutableArrayRef< T >::rend () const inline
Definition at line 304 of file ArrayRef.h.
References begin().
slice() [1/2]
template<typename T> MutableArrayRef< T > llvm::MutableArrayRef< T >::slice (unsigned N) const inline
slice(n) - Chop off the first N elements of the array.
Definition at line 319 of file ArrayRef.h.
References data(), MutableArrayRef(), N, and llvm::ArrayRef< T >::size().
Referenced by lowerV16I8VectorShuffle(), and lowerV8I16SingleInputVectorShuffle().
slice() [2/2]
template<typename T> MutableArrayRef< T > llvm::MutableArrayRef< T >::slice (unsigned N, unsigned M) const inline
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
Definition at line 326 of file ArrayRef.h.
References data(), MutableArrayRef(), N, and llvm::ArrayRef< T >::size().
The documentation for this class was generated from the following file:
ArrayRef.h