LLVM: llvm::TernOpInit Class Reference
LLVM API Documentation
llvm::TernOpInit Class Reference
#include <Record.h>
Public Types
enum TernaryOp { SUBST , FOREACH , IF }
Public Member Functions
OpInit * clone (std::vector< Init * > &Operands) const override
int getNumOperands () const override
Init * getOperand (int i) const override
TernaryOp getOpcode () const
Init * getLHS () const
Init * getMHS () const
Init * getRHS () const
Init * Fold (Record *CurRec, MultiClass *CurMultiClass) const override
bool isComplete () const override
Init * resolveReferences (Record &R, const RecordVal *RV) const override
std::string getAsString () const override
getAsString - Convert this value to a string form.
Public Member Functions inherited from llvm::OpInit
Init * convertInitializerTo (RecTy *Ty) const override
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
Init * getBit (unsigned Bit) const override
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const override
Init * convertInitListSlice (const std::vector< unsigned > &Elements) const override
RecTy * getFieldType (const std::string &FieldName) const override
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static TernOpInit * get (TernaryOp opc, Init *lhs, Init *mhs, Init *rhs, RecTy *Type)
Static Public Member Functions inherited from llvm::OpInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit , IK_FirstTypedInit , IK_BitsInit , IK_DagInit ,
IK_DefInit , IK_FieldInit , IK_IntInit , IK_ListInit ,
IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit , IK_UnOpInit ,
IK_LastOpInit , IK_StringInit , IK_VarInit , IK_VarListElementInit ,
IK_LastTypedInit , IK_UnsetInit , IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::OpInit
OpInit (InitKind K, RecTy *Type)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
TernOpInit - !op (X, Y, Z) - Combine two inits.
Definition at line 991 of file Record.h.
Member Enumeration Documentation
TernaryOp
enum llvm::TernOpInit::TernaryOp
Enumerator
SUBST
FOREACH
IF
Definition at line 993 of file Record.h.
Member Function Documentation
classof()
bool llvm::TernOpInit::classof (const Init * I) inline static
Definition at line 1007 of file Record.h.
References I, and llvm::Init::IK_TernOpInit.
clone()
OpInit * llvm::TernOpInit::clone (std::vector< Init * > & Operands) const inline override virtual
Implements llvm::OpInit.
Definition at line 1015 of file Record.h.
References get(), getOpcode(), llvm::TypedInit::getType(), and Operands.
Fold()
Init * TernOpInit::Fold (Record * CurRec, MultiClass * CurMultiClass) const override virtual
Implements llvm::OpInit.
Definition at line 1162 of file Record.cpp.
References llvm::dyn_cast(), FOREACH, ForeachHelper(), llvm::DefInit::get(), llvm::IntRecTy::get(), llvm::StringInit::get(), llvm::VarInit::get(), llvm::DefInit::getAsString(), llvm::VarInit::getAsString(), llvm::DefInit::getDef(), llvm::VarInit::getName(), getOpcode(), llvm::TypedInit::getType(), llvm::IntInit::getValue(), llvm::StringInit::getValue(), I, IF, and SUBST.
Referenced by resolveReferences().
get()
TernOpInit * TernOpInit::get (TernaryOp opc, Init * lhs, Init * mhs, Init * rhs, RecTy * Type) static
Definition at line 1020 of file Record.cpp.
References I.
Referenced by clone(), and resolveReferences().
getAsString()
std::string TernOpInit::getAsString () const override virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 1271 of file Record.cpp.
References FOREACH, IF, and SUBST.
getLHS()
Init * llvm::TernOpInit::getLHS () const inline
Definition at line 1036 of file Record.h.
Referenced by getOperand().
getMHS()
Init * llvm::TernOpInit::getMHS () const inline
Definition at line 1037 of file Record.h.
Referenced by getOperand().
getNumOperands()
int llvm::TernOpInit::getNumOperands () const inline override virtual
Implements llvm::OpInit.
Definition at line 1022 of file Record.h.
getOpcode()
TernaryOp llvm::TernOpInit::getOpcode () const inline
Definition at line 1035 of file Record.h.
Referenced by clone(), Fold(), and resolveReferences().
getOperand()
Init * llvm::TernOpInit::getOperand (int i) const inline override virtual
Implements llvm::OpInit.
Definition at line 1023 of file Record.h.
References getLHS(), getMHS(), and getRHS().
getRHS()
Init * llvm::TernOpInit::getRHS () const inline
Definition at line 1038 of file Record.h.
Referenced by getOperand().
isComplete()
bool llvm::TernOpInit::isComplete () const inline override virtual
isComplete - This virtual method should be overridden by values that may not be completely specified yet.
Reimplemented from llvm::Init.
Definition at line 1044 of file Record.h.
resolveReferences()
Init * TernOpInit::resolveReferences (Record & R, const RecordVal * RV) const override virtual
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1240 of file Record.cpp.
References llvm::Init::convertInitializerTo(), llvm::dyn_cast(), Fold(), llvm::IntRecTy::get(), get(), getOpcode(), llvm::TypedInit::getType(), I, IF, and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
Record.h
Record.cpp