LLVM: llvm::JumpInstrTableInfo Class Reference
LLVM API Documentation
llvm::JumpInstrTableInfo Class Reference
#include <JumpInstrTableInfo.h>
Public Types
typedef std::pair< Function *, Function * > JumpPair
typedef DenseMap< FunctionType *, std::vector< JumpPair > > JumpTables
Public Member Functions
JumpInstrTableInfo (uint64_t ByteAlign=16)
virtual ~JumpInstrTableInfo ()
const char * getPassName () const override
void insertEntry (FunctionType *TableFunTy, Function *Target, Function *Jump)
Inserts an entry in a table, adding the table if it doesn't exist.
const JumpTables & getTables () const
Gets the tables.
uint64_t entryByteAlignment () const
Gets the alignment in bytes of a jumptable entry.
Public Member Functions inherited from llvm::ImmutablePass
virtual void initializePass ()
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePass (char &pid)
virtual ~ImmutablePass ()
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
This class stores information about jump-instruction tables created by the JumpInstrTables pass (in lib/CodeGen/JumpInstrTables.cpp). Each table is a map from a function type to a vector of pairs. The first element of each pair is the function that has the jumptable annotation. The second element is a function that was declared by JumpInstrTables and used to replace all address-taking sites for the original function.
The information in this pass is used in AsmPrinter (lib/CodeGen/AsmPrinter/AsmPrinter.cpp) to generate the required assembly for the jump-instruction tables.
Definition at line 35 of file JumpInstrTableInfo.h.
Member Typedef Documentation
JumpPair
typedef std::pair<Function *, Function *> llvm::JumpInstrTableInfo::JumpPair
Definition at line 47 of file JumpInstrTableInfo.h.
JumpTables
typedef DenseMap<FunctionType *, std::vector<JumpPair> > llvm::JumpInstrTableInfo::JumpTables
Definition at line 48 of file JumpInstrTableInfo.h.
Constructor & Destructor Documentation
JumpInstrTableInfo()
JumpInstrTableInfo::JumpInstrTableInfo (uint64_t ByteAlign = 16)
The default byte alignment for jump tables is 16, which is large but usually safe.
Definition at line 38 of file JumpInstrTableInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::ImmutablePass::ImmutablePass(), llvm::initializeJumpInstrTableInfoPass(), llvm::isPowerOf2_64(), and llvm::NextPowerOf2().
~JumpInstrTableInfo()
JumpInstrTableInfo::~JumpInstrTableInfo () virtual
Definition at line 50 of file JumpInstrTableInfo.cpp.
Member Function Documentation
entryByteAlignment()
uint64_t llvm::JumpInstrTableInfo::entryByteAlignment () const inline
Gets the alignment in bytes of a jumptable entry.
Definition at line 57 of file JumpInstrTableInfo.h.
Referenced by llvm::AsmPrinter::doFinalization(), and llvm::ForwardControlFlowIntegrity::runOnModule().
getPassName()
const char * llvm::JumpInstrTableInfo::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 43 of file JumpInstrTableInfo.h.
getTables()
const JumpTables & llvm::JumpInstrTableInfo::getTables () const inline
Gets the tables.
Definition at line 54 of file JumpInstrTableInfo.h.
Referenced by llvm::AsmPrinter::doFinalization(), and llvm::ForwardControlFlowIntegrity::runOnModule().
insertEntry()
void JumpInstrTableInfo::insertEntry (FunctionType * TableFunTy, Function * Target, Function * Jump)
Inserts an entry in a table, adding the table if it doesn't exist.
Definition at line 52 of file JumpInstrTableInfo.cpp.
Member Data Documentation
ID
char llvm::JumpInstrTableInfo::ID static
Definition at line 37 of file JumpInstrTableInfo.h.
Referenced by JumpInstrTableInfo().
The documentation for this class was generated from the following files:
JumpInstrTableInfo.h
JumpInstrTableInfo.cpp