LLVM: llvm::yaml::document_iterator Class Reference
LLVM API Documentation
llvm::yaml::document_iterator Class Reference
Iterator abstraction for Documents over a Stream.
#include <YAMLParser.h>
Public Member Functions
document_iterator ()
document_iterator (std::unique_ptr< Document > &D)
bool operator== (const document_iterator &Other)
bool operator!= (const document_iterator &Other)
document_iterator operator++ ()
Document & operator* ()
std::unique_ptr< Document > & operator-> ()
Detailed Description
Iterator abstraction for Documents over a Stream.
Definition at line 518 of file YAMLParser.h.
Constructor & Destructor Documentation
document_iterator() [1/2]
llvm::yaml::document_iterator::document_iterator () inline
Definition at line 520 of file YAMLParser.h.
Referenced by operator!=(), operator++(), and operator==().
document_iterator() [2/2]
llvm::yaml::document_iterator::document_iterator (std::unique_ptr< Document > & D) inline
Definition at line 521 of file YAMLParser.h.
Member Function Documentation
operator!=()
bool llvm::yaml::document_iterator::operator!= (const document_iterator & Other) inline
Definition at line 529 of file YAMLParser.h.
References document_iterator().
operator*()
Document & llvm::yaml::document_iterator::operator* () inline
Definition at line 542 of file YAMLParser.h.
operator++()
document_iterator llvm::yaml::document_iterator::operator++ () inline
Definition at line 531 of file YAMLParser.h.
References document_iterator().
operator->()
std::unique_ptr< Document > & llvm::yaml::document_iterator::operator-> () inline
Definition at line 544 of file YAMLParser.h.
operator==()
bool llvm::yaml::document_iterator::operator== (const document_iterator & Other) inline
Definition at line 523 of file YAMLParser.h.
References document_iterator().
The documentation for this class was generated from the following file:
YAMLParser.h