LLVM: llvm::LazyCallGraphPrinterPass Class Reference
LLVM API Documentation
llvm::LazyCallGraphPrinterPass Class Reference
A pass which prints the call graph to a raw_ostream.
#include <LazyCallGraph.h>
Public Member Functions
LazyCallGraphPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Module &M, ModuleAnalysisManager *AM)
Static Public Member Functions
static StringRef name ()
Detailed Description
A pass which prints the call graph to a raw_ostream.
This is primarily useful for testing the analysis.
Definition at line 561 of file LazyCallGraph.h.
Constructor & Destructor Documentation
LazyCallGraphPrinterPass()
LazyCallGraphPrinterPass::LazyCallGraphPrinterPass (raw_ostream & OS) explicit
Definition at line 685 of file LazyCallGraph.cpp.
Member Function Documentation
name()
StringRef llvm::LazyCallGraphPrinterPass::name () inline static
Definition at line 569 of file LazyCallGraph.h.
run()
PreservedAnalyses LazyCallGraphPrinterPass::run (Module & M, ModuleAnalysisManager * AM)
Definition at line 711 of file LazyCallGraph.cpp.
References llvm::PreservedAnalyses::all(), G, llvm::Module::getModuleIdentifier(), llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::getResult(), llvm::SmallPtrSetImpl< PtrType >::insert(), N, printNodes(), and printSCC().
The documentation for this class was generated from the following files:
LazyCallGraph.h
LazyCallGraph.cpp