LLVM: llvm::object::DiceRef Class Reference
LLVM API Documentation
llvm::object::DiceRef Class Reference
#include <MachO.h>
Public Member Functions
DiceRef ()
DiceRef (DataRefImpl DiceP, const ObjectFile *Owner)
DiceRef.
bool operator== (const DiceRef &Other) const
bool operator< (const DiceRef &Other) const
void moveNext ()
std::error_code getOffset (uint32_t &Result) const
std::error_code getLength (uint16_t &Result) const
std::error_code getKind (uint16_t &Result) const
DataRefImpl getRawDataRefImpl () const
const ObjectFile * getObjectFile () const
Detailed Description
DiceRef - This is a value type class that represents a single data in code entry in the table in a Mach-O object file.
Definition at line 29 of file Object/MachO.h.
Constructor & Destructor Documentation
DiceRef() [1/2]
llvm::object::DiceRef::DiceRef () inline
Definition at line 34 of file Object/MachO.h.
Referenced by operator<(), and operator==().
DiceRef() [2/2]
llvm::object::DiceRef::DiceRef (DataRefImpl DiceP, const ObjectFile * Owner) inline
DiceRef.
Definition at line 446 of file Object/MachO.h.
Member Function Documentation
getKind()
std::error_code llvm::object::DiceRef::getKind (uint16_t & Result) const inline
Definition at line 483 of file Object/MachO.h.
References llvm::object::MachOObjectFile::getDice(), llvm::MachO::data_in_code_entry::kind, and llvm::object::success.
getLength()
std::error_code llvm::object::DiceRef::getLength (uint16_t & Result) const inline
Definition at line 475 of file Object/MachO.h.
References llvm::object::MachOObjectFile::getDice(), llvm::MachO::data_in_code_entry::length, and llvm::object::success.
getObjectFile()
const ObjectFile * llvm::object::DiceRef::getObjectFile () const inline
Definition at line 495 of file Object/MachO.h.
getOffset()
std::error_code llvm::object::DiceRef::getOffset (uint32_t & Result) const inline
Definition at line 467 of file Object/MachO.h.
References llvm::object::MachOObjectFile::getDice(), llvm::MachO::data_in_code_entry::offset, and llvm::object::success.
getRawDataRefImpl()
DataRefImpl llvm::object::DiceRef::getRawDataRefImpl () const inline
Definition at line 491 of file Object/MachO.h.
moveNext()
void llvm::object::DiceRef::moveNext () inline
Definition at line 457 of file Object/MachO.h.
References P.
operator<()
bool llvm::object::DiceRef::operator< (const DiceRef & Other) const inline
Definition at line 453 of file Object/MachO.h.
References DiceRef().
operator==()
bool llvm::object::DiceRef::operator== (const DiceRef & Other) const inline
Definition at line 449 of file Object/MachO.h.
References DiceRef().
The documentation for this class was generated from the following file:
Object/MachO.h