LLVM: llvm::DWARFUnitSectionBase Class Reference
LLVM API Documentation
llvm::DWARFUnitSectionBase Class Reference abstract
#include <DWARFUnit.h>
Public Member Functions
virtual DWARFUnit * getUnitForOffset (uint32_t Offset) const =0
void parse (DWARFContext &C, const DWARFSection &Section)
void parseDWO (DWARFContext &C, const DWARFSection &DWOSection)
Protected Member Functions
virtual void parseImpl (DWARFContext &Context, const DWARFSection &Section, const DWARFDebugAbbrev *DA, StringRef RS, StringRef SS, StringRef SOS, StringRef AOS, bool isLittleEndian)=0
~DWARFUnitSectionBase ()
Detailed Description
Base class for all DWARFUnitSection classes. This provides the functionality common to all unit types.
Definition at line 34 of file DWARFUnit.h.
Constructor & Destructor Documentation
~DWARFUnitSectionBase()
llvm::DWARFUnitSectionBase::~DWARFUnitSectionBase () inline protected
Definition at line 48 of file DWARFUnit.h.
Member Function Documentation
getUnitForOffset()
virtual DWARFUnit * llvm::DWARFUnitSectionBase::getUnitForOffset (uint32_t Offset) const pure virtual
Returns the Unit that contains the given section offset in the same section this Unit originated from.
Implemented in llvm::DWARFUnitSection< UnitType >, llvm::DWARFUnitSection< llvm::DWARFCompileUnit >, llvm::iterator_range< DWARFCompileUnit >, and llvm::iterator_range< DWARFTypeUnit >.
Referenced by findUnitAndExtractFast().
parse()
void DWARFUnitSectionBase::parse (DWARFContext & C, const DWARFSection & Section)
Definition at line 20 of file DWARFUnit.cpp.
References parseImpl().
parseDWO()
void DWARFUnitSectionBase::parseDWO (DWARFContext & C, const DWARFSection & DWOSection)
Definition at line 26 of file DWARFUnit.cpp.
References parseImpl().
parseImpl()
virtual void llvm::DWARFUnitSectionBase::parseImpl (DWARFContext & Context, const DWARFSection & Section, const DWARFDebugAbbrev * DA, StringRef RS, StringRef SS, StringRef SOS, StringRef AOS, bool isLittleEndian) protected pure virtual
Referenced by parse(), and parseDWO().
The documentation for this class was generated from the following files:
DWARFUnit.h
DWARFUnit.cpp