LLVM: llvm::MachineFunction Class Reference
LLVM API Documentation
llvm::MachineFunction Class Reference
#include <MachineFunction.h>
Public Types
typedef BasicBlockListType::iterator iterator
typedef BasicBlockListType::const_iterator const_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
typedef ArrayRecycler< MachineOperand >::Capacity OperandCapacity
Public Member Functions
MachineFunction (const Function *Fn, const TargetMachine &TM, unsigned FunctionNum, MachineModuleInfo &MMI)
~MachineFunction ()
MachineModuleInfo & getMMI () const
MCContext & getContext () const
const Function * getFunction () const
StringRef getName () const
unsigned getFunctionNumber () const
const TargetMachine & getTarget () const
const TargetSubtargetInfo & getSubtarget () const
void setSubtarget (const TargetSubtargetInfo *ST)
MachineRegisterInfo & getRegInfo ()
const MachineRegisterInfo & getRegInfo () const
MachineFrameInfo * getFrameInfo ()
const MachineFrameInfo * getFrameInfo () const
const MachineJumpTableInfo * getJumpTableInfo () const
MachineJumpTableInfo * getJumpTableInfo ()
MachineJumpTableInfo * getOrCreateJumpTableInfo (unsigned JTEntryKind)
MachineConstantPool * getConstantPool ()
const MachineConstantPool * getConstantPool () const
unsigned getAlignment () const
void setAlignment (unsigned A)
void ensureAlignment (unsigned A)
ensureAlignment - Make sure the function is at least 1 << A bytes aligned.
bool exposesReturnsTwice () const
void setExposesReturnsTwice (bool B)
bool hasInlineAsm () const
Returns true if the function contains any inline assembly.
void setHasInlineAsm (bool B)
Set a flag that indicates that the function contains inline assembly.
template<typename Ty>
Ty * getInfo ()
template<typename Ty>
const Ty * getInfo () const
MachineBasicBlock * getBlockNumbered (unsigned N) const
bool shouldSplitStack ()
Should we be emitting segmented stack stuff for the function.
unsigned getNumBlockIDs () const
void RenumberBlocks (MachineBasicBlock *MBBFrom=nullptr)
void print (raw_ostream &OS, SlotIndexes *=nullptr) const
void viewCFG () const
void viewCFGOnly () const
void dump () const
void verify (Pass *p=nullptr, const char *Banner=nullptr) const
unsigned addLiveIn (unsigned PReg, const TargetRegisterClass *RC)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
unsigned size () const
bool empty () const
const MachineBasicBlock & front () const
MachineBasicBlock & front ()
const MachineBasicBlock & back () const
MachineBasicBlock & back ()
void push_back (MachineBasicBlock *MBB)
void push_front (MachineBasicBlock *MBB)
void insert (iterator MBBI, MachineBasicBlock *MBB)
void splice (iterator InsertPt, iterator MBBI)
void splice (iterator InsertPt, iterator MBBI, iterator MBBE)
void remove (iterator MBBI)
void erase (iterator MBBI)
unsigned addToMBBNumbering (MachineBasicBlock *MBB)
Adds the MBB to the internal numbering. Returns the unique number assigned to the MBB.
void removeFromMBBNumbering (unsigned N)
MachineBasicBlock * CreateMachineBasicBlock (const BasicBlock *bb=nullptr)
void DeleteMachineBasicBlock (MachineBasicBlock *MBB)
MachineMemOperand * getMachineMemOperand (MachinePointerInfo PtrInfo, unsigned f, uint64_t s, unsigned base_alignment, const AAMDNodes &AAInfo=AAMDNodes(), const MDNode *Ranges=nullptr)
MachineMemOperand * getMachineMemOperand (const MachineMemOperand *MMO, int64_t Offset, uint64_t Size)
MachineOperand * allocateOperandArray (OperandCapacity Cap)
void deallocateOperandArray (OperandCapacity Cap, MachineOperand *Array)
uint32_t * allocateRegisterMask (unsigned NumRegister)
Allocate and initialize a register mask with NumRegister bits.
MachineInstr::mmo_iterator allocateMemRefsArray (unsigned long Num)
std::pair< MachineInstr::mmo_iterator, MachineInstr::mmo_iterator > extractLoadMemRefs (MachineInstr::mmo_iterator Begin, MachineInstr::mmo_iterator End)
std::pair< MachineInstr::mmo_iterator, MachineInstr::mmo_iterator > extractStoreMemRefs (MachineInstr::mmo_iterator Begin, MachineInstr::mmo_iterator End)
MCSymbol * getJTISymbol (unsigned JTI, MCContext &Ctx, bool isLinkerPrivate=false) const
MCSymbol * getPICBaseSymbol () const
Detailed Description
Definition at line 86 of file MachineFunction.h.
Member Typedef Documentation
const_iterator
typedef BasicBlockListType::const_iterator llvm::MachineFunction::const_iterator
Definition at line 315 of file MachineFunction.h.
const_reverse_iterator
typedef std::reverse_iterator<const_iterator> llvm::MachineFunction::const_reverse_iterator
Definition at line 316 of file MachineFunction.h.
iterator
typedef BasicBlockListType::iterator llvm::MachineFunction::iterator
Definition at line 314 of file MachineFunction.h.
OperandCapacity
typedef ArrayRecycler<MachineOperand>::Capacity llvm::MachineFunction::OperandCapacity
Definition at line 426 of file MachineFunction.h.
reverse_iterator
typedef std::reverse_iterator<iterator> llvm::MachineFunction::reverse_iterator
Definition at line 317 of file MachineFunction.h.
Constructor & Destructor Documentation
MachineFunction()
MachineFunction::MachineFunction (const Function * Fn, const TargetMachine & TM, unsigned FunctionNum, MachineModuleInfo & MMI)
Definition at line 55 of file MachineFunction.cpp.
References F, llvm::AttributeSet::FunctionIndex, getContext(), llvm::Attribute::OptimizeForSize, and llvm::Attribute::StackAlignment.
~MachineFunction()
MachineFunction::~MachineFunction ()
Definition at line 88 of file MachineFunction.cpp.
References begin(), end(), and I.
Member Function Documentation
addLiveIn()
unsigned MachineFunction::addLiveIn (unsigned PReg, const TargetRegisterClass * RC)
addLiveIn - Add the specified physical register as a live-in value and create a corresponding virtual register for it.
Definition at line 438 of file MachineFunction.cpp.
References llvm::MachineRegisterInfo::addLiveIn(), llvm::TargetRegisterClass::contains(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineRegisterInfo::getLiveInVirtReg(), llvm::MachineRegisterInfo::getRegClass(), getRegInfo(), and llvm::TargetRegisterClass::hasSubClassEq().
Referenced by llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), and LowerRETURNADDR().
addToMBBNumbering()
unsigned llvm::MachineFunction::addToMBBNumbering (MachineBasicBlock * MBB) inline
Adds the MBB to the internal numbering. Returns the unique number assigned to the MBB.
Definition at line 369 of file MachineFunction.h.
allocateMemRefsArray()
MachineInstr::mmo_iterator MachineFunction::allocateMemRefsArray (unsigned long Num)
allocateMemRefsArray - Allocate an array to hold MachineMemOperand pointers. This array is owned by the MachineFunction.
Definition at line 258 of file MachineFunction.cpp.
Referenced by llvm::MachineInstr::addMemOperand(), concatenateMemOperands(), extractLoadMemRefs(), and extractStoreMemRefs().
allocateOperandArray()
MachineOperand * llvm::MachineFunction::allocateOperandArray (OperandCapacity Cap) inline
Allocate an array of MachineOperands. This is only intended for use by internal MachineInstr functions.
Definition at line 430 of file MachineFunction.h.
Referenced by llvm::MachineInstr::addOperand().
allocateRegisterMask()
uint32_t * llvm::MachineFunction::allocateRegisterMask (unsigned NumRegister) inline
Allocate and initialize a register mask with NumRegister bits.
Definition at line 442 of file MachineFunction.h.
back() [1/2]
MachineBasicBlock & llvm::MachineFunction::back () inline
Definition at line 341 of file MachineFunction.h.
References llvm::MachineBasicBlock::back().
back() [2/2]
const MachineBasicBlock & llvm::MachineFunction::back () const inline
Definition at line 340 of file MachineFunction.h.
References llvm::MachineBasicBlock::back().
Referenced by llvm::calculateDbgValueHistory().
begin() [1/2]
iterator llvm::MachineFunction::begin () inline
Definition at line 326 of file MachineFunction.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::finalizeBundles(), getBBFallenThrough(), llvm::SIMachineFunctionInfo::getSpilledReg(), llvm::MachineLoop::getTopBlock(), HandleVRSaveUpdate(), llvm::BranchFolder::OptimizeFunction(), PrevCrossBBInst(), RemoveVRSaveCode(), RenumberBlocks(), llvm::PPCFrameLowering::replaceFPWithRealFP(), llvm::Mips16FrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), verifyCTRBranch(), VerifyPHIs(), and ~MachineFunction().
begin() [2/2]
const_iterator llvm::MachineFunction::begin () const inline
Definition at line 327 of file MachineFunction.h.
CreateMachineBasicBlock()
MachineBasicBlock * MachineFunction::CreateMachineBasicBlock (const BasicBlock * bb = nullptr)
CreateMachineInstr - Allocate a new MachineInstr. Use this instead of ‘new MachineInstr’. / MachineInstr *CreateMachineInstr(const MCInstrDesc &MCID, DebugLoc DL, bool NoImp = false);
/ CloneMachineInstr - Create a new MachineInstr which is a copy of the / 'Orig' instruction, identical in all ways except the instruction / has no parent, prev, or next. / / See also TargetInstrInfo::duplicate() for target-specific fixes to cloned / instructions. MachineInstr *CloneMachineInstr(const MachineInstr *Orig);
/ DeleteMachineInstr - Delete the given MachineInstr. / void DeleteMachineInstr(MachineInstr *MI);
/ CreateMachineBasicBlock - Allocate a new MachineBasicBlock. Use this / instead of ‘new MachineBasicBlock’.
CreateMachineInstr - Allocate a new MachineInstr. Use this instead of ‘new MachineInstr’. / MachineInstr * MachineFunction::CreateMachineInstr(const MCInstrDesc &MCID, DebugLoc DL, bool NoImp) { return new (InstructionRecycler.Allocate<MachineInstr>(Allocator)) MachineInstr(*this, MCID, DL, NoImp); }
/ CloneMachineInstr - Create a new MachineInstr which is a copy of the / 'Orig' instruction, identical in all ways except the instruction / has no parent, prev, or next. / MachineInstr * MachineFunction::CloneMachineInstr(const MachineInstr *Orig) { return new (InstructionRecycler.Allocate<MachineInstr>(Allocator)) MachineInstr(*this, *Orig); }
/ DeleteMachineInstr - Delete the given MachineInstr. / / This function also serves as the MachineInstr destructor - the real / ~MachineInstr() destructor must be empty. void MachineFunction::DeleteMachineInstr(MachineInstr *MI) { Strip it for parts. The operand array and the MI object itself are independently recyclable. if (MI->Operands) deallocateOperandArray(MI->CapOperands, MI->Operands); Don't call ~MachineInstr() which must be trivial anyway because ~MachineFunction drops whole lists of MachineInstrs wihout calling their destructors. InstructionRecycler.Deallocate(Allocator, MI); }
/ CreateMachineBasicBlock - Allocate a new MachineBasicBlock. Use this / instead of ‘new MachineBasicBlock’.
Definition at line 218 of file MachineFunction.cpp.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), emitBlockAfter(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), EmitXBegin(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::FunctionLoweringInfo::set(), and llvm::MachineBasicBlock::SplitCriticalEdge().
deallocateOperandArray()
void llvm::MachineFunction::deallocateOperandArray (OperandCapacity Cap, MachineOperand * Array) inline
Dellocate an array of MachineOperands and recycle the memory. This is only intended for use by internal MachineInstr functions. Cap must be the same capacity that was used to allocate the array.
Definition at line 437 of file MachineFunction.h.
Referenced by llvm::MachineInstr::addOperand().
DeleteMachineBasicBlock()
void MachineFunction::DeleteMachineBasicBlock (MachineBasicBlock * MBB)
DeleteMachineBasicBlock - Delete the given MachineBasicBlock.
Definition at line 226 of file MachineFunction.cpp.
References llvm::MachineBasicBlock::getParent().
dump()
void MachineFunction::dump () const
dump - Print the current MachineFunction to cerr, useful for debugger use.
Definition at line 327 of file MachineFunction.cpp.
References llvm::dbgs(), and print().
Referenced by llvm::A57ChainingConstraint::apply().
empty()
bool llvm::MachineFunction::empty () const inline
Definition at line 337 of file MachineFunction.h.
Referenced by RenumberBlocks().
end() [1/2]
iterator llvm::MachineFunction::end () inline
Definition at line 328 of file MachineFunction.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), BBHasFallthrough(), BBHasFallthrough(), canFallThroughTo(), llvm::MSP430FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::finalizeBundles(), FixTail(), llvm::MachineLoop::getBottomBlock(), getNextBlock(), llvm::SIMachineFunctionInfo::getSpilledReg(), HandleVRSaveUpdate(), llvm::SlotIndexes::insertMBBInMaps(), llvm::BranchFolder::OptimizeFunction(), RemoveVRSaveCode(), RenumberBlocks(), llvm::PPCFrameLowering::replaceFPWithRealFP(), llvm::MachineBasicBlock::SplitCriticalEdge(), VerifyPHIs(), and ~MachineFunction().
end() [2/2]
const_iterator llvm::MachineFunction::end () const inline
Definition at line 329 of file MachineFunction.h.
ensureAlignment()
void llvm::MachineFunction::ensureAlignment (unsigned A) inline
ensureAlignment - Make sure the function is at least 1 << A bytes aligned.
Definition at line 218 of file MachineFunction.h.
erase()
void llvm::MachineFunction::erase (iterator MBBI) inline
Definition at line 358 of file MachineFunction.h.
Referenced by llvm::MachineBasicBlock::eraseFromParent().
exposesReturnsTwice()
bool llvm::MachineFunction::exposesReturnsTwice () const inline
exposesReturnsTwice - Returns true if the function calls setjmp or any other similar functions with attribute "returns twice" without having the attribute itself.
Definition at line 225 of file MachineFunction.h.
extractLoadMemRefs()
std::pair< MachineInstr::mmo_iterator, MachineInstr::mmo_iterator > MachineFunction::extractLoadMemRefs (MachineInstr::mmo_iterator Begin, MachineInstr::mmo_iterator End)
extractLoadMemRefs - Allocate an array and populate it with just the load information from the given MachineMemOperand sequence.
Definition at line 263 of file MachineFunction.cpp.
References allocateMemRefsArray(), getMachineMemOperand(), I, and llvm::MachineMemOperand::MOStore.
Referenced by llvm::X86InstrInfo::unfoldMemoryOperand(), and llvm::X86InstrInfo::unfoldMemoryOperand().
extractStoreMemRefs()
std::pair< MachineInstr::mmo_iterator, MachineInstr::mmo_iterator > MachineFunction::extractStoreMemRefs (MachineInstr::mmo_iterator Begin, MachineInstr::mmo_iterator End)
extractStoreMemRefs - Allocate an array and populate it with just the store information from the given MachineMemOperand sequence.
Definition at line 295 of file MachineFunction.cpp.
References allocateMemRefsArray(), getMachineMemOperand(), I, and llvm::MachineMemOperand::MOLoad.
Referenced by llvm::X86InstrInfo::unfoldMemoryOperand(), and llvm::X86InstrInfo::unfoldMemoryOperand().
front() [1/2]
MachineBasicBlock & llvm::MachineFunction::front () inline
Definition at line 339 of file MachineFunction.h.
References llvm::MachineBasicBlock::front().
front() [2/2]
const MachineBasicBlock & llvm::MachineFunction::front () const inline
Definition at line 338 of file MachineFunction.h.
References llvm::MachineBasicBlock::front().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::SparcInstrInfo::getGlobalBaseReg(), and llvm::MachineFrameInfo::getPristineRegs().
getAlignment()
unsigned llvm::MachineFunction::getAlignment () const inline
getAlignment - Return the alignment (log2, not bytes) of the function.
Definition at line 211 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks().
getBlockNumbered()
MachineBasicBlock * llvm::MachineFunction::getBlockNumbered (unsigned N) const inline
getBlockNumbered - MachineBasicBlocks are automatically numbered when they are inserted into the machine function. The block number for a machine basic block can be found by using the MBB::getBlockNumber method, this method provides the inverse mapping.
Definition at line 265 of file MachineFunction.h.
References N.
getConstantPool() [1/2]
MachineConstantPool * llvm::MachineFunction::getConstantPool () inline
getConstantPool - Return the constant pool object for the current function.
Definition at line 206 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), duplicateCPV(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::XCoreInstrInfo::loadImmediate(), and llvm::ARMBaseInstrInfo::produceSameValue().
getConstantPool() [2/2]
const MachineConstantPool * llvm::MachineFunction::getConstantPool () const inline
Definition at line 207 of file MachineFunction.h.
getContext()
MCContext & llvm::MachineFunction::getContext () const inline
Definition at line 156 of file MachineFunction.h.
Referenced by llvm::MachineBasicBlock::getSymbol(), and MachineFunction().
getFrameInfo() [1/2]
MachineFrameInfo * llvm::MachineFunction::getFrameInfo () inline
getFrameInfo - Return the frame info object for the current function. This object contains information about objects allocated on the stack frame of the current function in an abstract way.
Definition at line 188 of file MachineFunction.h.
Referenced by llvm::addFrameReference(), llvm::addFrameReference(), llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::X86TargetLowering::BuildFILD(), CalculateTailCallArgDest(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::X86RegisterInfo::canRealignStack(), llvm::ARMFrameLowering::canSimplifyCallFramePseudos(), llvm::AArch64FrameLowering::canUseRedZone(), llvm::XCoreFunctionInfo::createEHSpillSlot(), llvm::XCoreFunctionInfo::createFPSpillSlot(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::SelectionDAG::CreateStackTemporary(), llvm::SelectionDAG::CreateStackTemporary(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::TargetOptions::DisableFramePointerElim(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::NVPTXRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Spills(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), emitComments(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), estimateStackSize(), llvm::MipsFrameLowering::estimateStackSize(), fixupFuncForFI(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::SystemZFrameLowering::getAllocatedStackSize(), getFRAMEADDR(), getFrameIndexMMO(), llvm::AMDGPUFrameLowering::getFrameIndexOffset(), llvm::HexagonFrameLowering::getFrameIndexOffset(), llvm::SystemZFrameLowering::getFrameIndexOffset(), llvm::TargetFrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffsetFromSP(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), llvm::AMDGPUInstrInfo::getIndirectIndexEnd(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), llvm::MipsInstrInfo::GetMemOperand(), getMemsetStores(), getPrologueDeath(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::SIMachineFunctionInfo::getSpilledReg(), GetTLSADDR(), llvm::AArch64RegisterInfo::hasBasePointer(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::X86RegisterInfo::hasBasePointer(), llvm::AArch64FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::HexagonFrameLowering::hasFP(), llvm::MipsFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::PPCFrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::SystemZFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasReservedCallFrame(), llvm::ARMFrameLowering::hasReservedCallFrame(), llvm::Mips16FrameLowering::hasReservedCallFrame(), llvm::MipsSEFrameLowering::hasReservedCallFrame(), llvm::MSP430FrameLowering::hasReservedCallFrame(), llvm::SparcFrameLowering::hasReservedCallFrame(), llvm::Thumb1FrameLowering::hasReservedCallFrame(), llvm::X86FrameLowering::hasReservedCallFrame(), llvm::SelectionDAG::InferPtrAlignment(), llvm::SelectionDAG::isConsecutiveLoad(), isConsecutiveLSLoc(), llvm::MachineInstr::isInvariantLoad(), llvm::XCoreFunctionInfo::isLargeFrame(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), LowerAsSplatVectorLoad(), llvm::SparcTargetLowering::LowerCall_32(), llvm::TargetLowering::LowerCallTo(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), LowerVASTART(), llvm::SparcTargetLowering::makeAddress(), llvm::Mips16InstrInfo::makeFrame(), llvm::PPCFrameLowering::needsFP(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::X86RegisterInfo::needsStackRealignment(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MSP430FrameLowering::processFunctionBeforeFrameFinalized(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SIRegisterInfo::requiresRegisterScavenging(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), llvm::Mips16InstrInfo::restoreFrame(), llvm::PEI::runOnMachineFunction(), llvm::Mips16FrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::AArch64RegisterInfo::useFPForScavengingIndex(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), and WindowsRequiresStackProbe().
getFrameInfo() [2/2]
const MachineFrameInfo * llvm::MachineFunction::getFrameInfo () const inline
Definition at line 189 of file MachineFunction.h.
getFunction()
const Function * llvm::MachineFunction::getFunction () const inline
getFunction - Return the LLVM function that this machine code represents
Definition at line 160 of file MachineFunction.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::NVPTXTargetLowering::allowFMA(), llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::DwarfDebug::beginFunction(), llvm::WinCodeViewLineTables::beginFunction(), llvm::ARMBaseRegisterInfo::canRealignStack(), llvm::PPCRegisterInfo::canRealignStack(), llvm::X86RegisterInfo::canRealignStack(), llvm::AArch64FrameLowering::canUseRedZone(), checkNumAlignedDPRCS2Regs(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::TargetOptions::DisableFramePointerElim(), duplicateCPV(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::DwarfDebug::endFunction(), llvm::WinCodeViewLineTables::endFunction(), ExpandPowI(), findDeadCallerSavedReg(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), get64BitArgumentXMMs(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::MachineBlockFrequencyInfo::getFunction(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getName(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::AArch64TargetLowering::getOptimalMemOpType(), llvm::ARMTargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86RegisterInfo::getPointerRegClass(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), GetScratchRegister(), llvm::SparcTargetLowering::getSRetArgSize(), HasNestArgument(), hasReturnsTwiceAttr(), llvm::SelectionDAG::init(), llvm::HexagonTargetLowering::IsEligibleForTailCallOptimization(), llvm::TargetLowering::isInTailCallPosition(), llvm::XCoreInstrInfo::loadImmediate(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::AMDGPUTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), LowerInterruptReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), LowerVectorBroadcast(), llvm::PPCFrameLowering::needsFP(), llvm::XCoreRegisterInfo::needsFrameMoves(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::X86RegisterInfo::needsStackRealignment(), PerformOrCombine(), PerformSTORECombine(), performSTORECombine(), printDebugLoc(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), ProfitableToMerge(), llvm::MipsTargetMachine::resetSubtarget(), llvm::PEI::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), shouldSplitStack(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::tryFoldSPUpdateIntoPushPop(), and llvm::ARMSubtarget::useMovt().
getFunctionNumber()
unsigned llvm::MachineFunction::getFunctionNumber () const inline
getFunctionNumber - Return a unique ID for the current function.
Definition at line 168 of file MachineFunction.h.
Referenced by llvm::NVPTXFrameLowering::emitPrologue(), getJTISymbol(), getPICBaseSymbol(), and llvm::MachineBasicBlock::getSymbol().
getInfo() [1/2]
template<typename Ty> Ty * llvm::MachineFunction::getInfo () inline
getInfo - Keep track of various per-function pieces of information for backends that would like to do so.
Definition at line 249 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::SIInstrInfo::calculateLDSSpillAddress(), CalculateTailCallSPDiff(), llvm::ARMBaseRegisterInfo::canRealignStack(), llvm::AArch64FrameLowering::canUseRedZone(), checkNumAlignedDPRCS2Regs(), duplicateCPV(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::SystemZFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::HexagonTargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), estimateRSStackSizeLimit(), fixupFuncForFI(), llvm::X86FrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffsetFromSP(), llvm::SparcInstrInfo::getGlobalBaseReg(), llvm::X86InstrInfo::getGlobalBaseReg(), llvm::MipsTargetLowering::getGlobalReg(), getInfo(), llvm::SIRegisterInfo::getPreloadedValue(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::HexagonFrameLowering::hasFP(), llvm::SystemZFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), hasNonRISpills(), llvm::PPCRegisterInfo::hasReservedSpillSlot(), hasSpills(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::HexagonTargetLowering::LowerEH_RETURN(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerINLINEASM(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::SparcTargetLowering::LowerReturn_32(), LowerToTLSLocalDynamicModel(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), LowerVASTART(), LowerVASTART(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), MustSaveLR(), llvm::PPCFrameLowering::needsFP(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::SparcFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized(), llvm::Thumb2InstrInfo::ReplaceTailWithBranchTo(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), llvm::ARMFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), spillsCR(), spillsVRSAVE(), llvm::PPCInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::R600InstrInfo::usesTextureCache(), and llvm::R600InstrInfo::usesVertexCache().
getInfo() [2/2]
template<typename Ty> const Ty * llvm::MachineFunction::getInfo () const inline
Definition at line 256 of file MachineFunction.h.
References getInfo().
getJTISymbol()
MCSymbol * MachineFunction::getJTISymbol (unsigned JTI, MCContext & Ctx, bool isLinkerPrivate = false) const
getJTISymbol - Return the MCSymbol for the specified non-empty jump table. If isLinkerPrivate is specified, an 'l' label is returned, otherwise a normal 'L' label is returned.
Definition at line 463 of file MachineFunction.cpp.
References llvm::TargetSubtargetInfo::getDataLayout(), getFunctionNumber(), llvm::DataLayout::getLinkerPrivateGlobalPrefix(), llvm::DataLayout::getPrivateGlobalPrefix(), getSubtarget(), Name, and size().
Referenced by llvm::TargetLowering::getPICJumpTableRelocBaseExpr().
getJumpTableInfo() [1/2]
MachineJumpTableInfo * llvm::MachineFunction::getJumpTableInfo () inline
Definition at line 196 of file MachineFunction.h.
getJumpTableInfo() [2/2]
const MachineJumpTableInfo * llvm::MachineFunction::getJumpTableInfo () const inline
getJumpTableInfo - Return the jump table info object for the current function. This object contains information about jump tables in the current function. If the current function has no jump tables, this will return null.
Definition at line 195 of file MachineFunction.h.
Referenced by llvm::ARMBaseInstrInfo::GetInstSizeInBytes(), llvm::HexagonTargetLowering::LowerBR_JT(), and llvm::BranchFolder::OptimizeFunction().
getMachineMemOperand() [1/2]
MachineMemOperand * MachineFunction::getMachineMemOperand (const MachineMemOperand * MMO, int64_t Offset, uint64_t Size)
getMachineMemOperand - Allocate a new MachineMemOperand by copying an existing one, adjusting by an offset and using the given size. MachineMemOperands are owned by the MachineFunction and need not be explicitly deallocated.
Definition at line 242 of file MachineFunction.cpp.
References llvm::MachineMemOperand::getBaseAlignment(), llvm::MachineMemOperand::getFlags(), llvm::MachineMemOperand::getOffset(), llvm::MachineMemOperand::getPseudoValue(), and llvm::MachineMemOperand::getValue().
getMachineMemOperand() [2/2]
MachineMemOperand * MachineFunction::getMachineMemOperand (MachinePointerInfo PtrInfo, unsigned f, uint64_t s, unsigned base_alignment, const AAMDNodes & AAInfo = AAMDNodes(), const MDNode * Ranges = nullptr)
getMachineMemOperand - Allocate a new MachineMemOperand. MachineMemOperands are owned by the MachineFunction and need not be explicitly deallocated.
Definition at line 233 of file MachineFunction.cpp.
References Ranges.
Referenced by llvm::addFrameReference(), llvm::addFrameReference(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLoweringBase::emitPatchPoint(), extractLoadMemRefs(), extractStoreMemRefs(), llvm::TargetInstrInfo::foldMemoryOperand(), getFrameIndexMMO(), llvm::MipsInstrInfo::GetMemOperand(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), NarrowVectorLoadToElement(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), and llvm::XCoreInstrInfo::storeRegToStackSlot().
getMMI()
MachineModuleInfo & llvm::MachineFunction::getMMI () const inline
Definition at line 155 of file MachineFunction.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::MachineInstr::emitError(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), findDeadCallerSavedReg(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86FrameLowering::hasFP(), llvm::XCoreRegisterInfo::needsFrameMoves(), and llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan().
getName()
StringRef MachineFunction::getName () const
getName - Return the name of the corresponding LLVM function.
Definition at line 332 of file MachineFunction.cpp.
References getFunction(), and llvm::Value::getName().
Referenced by llvm::calculateSpillWeightsAndHints(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::MachineBasicBlock::getFullName(), print(), llvm::StackMapLiveness::runOnMachineFunction(), viewCFG(), and viewCFGOnly().
getNumBlockIDs()
unsigned llvm::MachineFunction::getNumBlockIDs () const inline
getNumBlockIDs - Return the number of MBB ID's allocated.
Definition at line 276 of file MachineFunction.h.
getOrCreateJumpTableInfo()
MachineJumpTableInfo * MachineFunction::getOrCreateJumpTableInfo (unsigned EntryKind)
getOrCreateJumpTableInfo - Get the JumpTableInfo for this function, if it does already exist, allocate one.
Definition at line 122 of file MachineFunction.cpp.
getPICBaseSymbol()
MCSymbol * MachineFunction::getPICBaseSymbol () const
getPICBaseSymbol - Return a function-local symbol to represent the PIC base.
Definition at line 479 of file MachineFunction.cpp.
References llvm::TargetSubtargetInfo::getDataLayout(), getFunctionNumber(), llvm::DataLayout::getPrivateGlobalPrefix(), and getSubtarget().
Referenced by llvm::X86TargetLowering::getPICJumpTableRelocBaseExpr(), and GetSymbolRef().
getRegInfo() [1/2]
MachineRegisterInfo & llvm::MachineFunction::getRegInfo () inline
getRegInfo - Return information about the registers currently in use.
Definition at line 181 of file MachineFunction.h.
Referenced by addLiveIn(), llvm::MachineBasicBlock::addLiveIn(), addLiveIn(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::AllocationOrder::AllocationOrder(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::calculateSpillWeightsAndHints(), canCombineWithMUL(), canCompareBeNewValueJump(), llvm::AArch64InstrInfo::canInsertSelect(), llvm::PPCInstrInfo::canInsertSelect(), llvm::X86InstrInfo::canInsertSelect(), llvm::ARMBaseRegisterInfo::canRealignStack(), llvm::X86RegisterInfo::canRealignStack(), checkNumAlignedDPRCS2Regs(), llvm::X86InstrInfo::classifyLEAReg(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::NVPTXInstrInfo::copyPhysReg(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::HexagonInstrInfo::createVR(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::NVPTXFrameLowering::emitPrologue(), emitThumbRegPlusImmInReg(), llvm::RegScavenger::enterBasicBlock(), llvm::MachineInstr::eraseFromParentAndMarkDBGValuesForRemoval(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::findPHICopyInsertPoint(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), forceReg(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), GetCostForDef(), llvm::SparcInstrInfo::getGlobalBaseReg(), llvm::X86InstrInfo::getGlobalBaseReg(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), llvm::PPCInstrInfo::getOperandLatency(), getPrologueDeath(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), GetRegistersForValue(), getRegTy(), llvm::SIMachineFunctionInfo::getSpilledReg(), HandleVRSaveUpdate(), llvm::AArch64InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), isEAXLiveIn(), isPartialRegisterLoad(), llvm::X86InstrInfo::isReallyTriviallyReMaterializable(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::R600TargetLowering::LowerOperation(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), llvm::MachineSSAUpdater::MachineSSAUpdater(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::SIInstrInfo::moveToVALU(), MustSaveLR(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::BranchFolder::OptimizeFunction(), llvm::MachineInstr::print(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::Mips16FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::LiveRangeCalc::reset(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::LiveIntervals::runOnMachineFunction(), llvm::LiveVariables::runOnMachineFunction(), llvm::PEI::runOnMachineFunction(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::SIInstrInfo::splitSMRD(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::tryFoldSPUpdateIntoPushPop(), UpdateOperandRegClass(), llvm::ARMBaseRegisterInfo::UpdateRegAllocHint(), and usesTheStack().
getRegInfo() [2/2]
const MachineRegisterInfo & llvm::MachineFunction::getRegInfo () const inline
Definition at line 182 of file MachineFunction.h.
getSubtarget()
const TargetSubtargetInfo & llvm::MachineFunction::getSubtarget () const inline
getSubtarget - Return the subtarget for which this machine code is being compiled.
Definition at line 176 of file MachineFunction.h.
Referenced by llvm::MachineBasicBlock::addLiveIn(), addSavedGPR(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::MachineBasicBlock::canFallThrough(), checkNumAlignedDPRCS2Regs(), llvm::TargetSchedModel::computeOutputLatency(), llvm::createBURRListDAGScheduler(), llvm::createDefaultScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createSourceListDAGScheduler(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::Mips16FrameLowering::eliminateCallFramePseudoInstr(), llvm::MipsSEFrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::SystemZFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::AArch64FrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitStackProbeCall(), llvm::RegScavenger::enterBasicBlock(), llvm::MachineFrameInfo::estimateStackSize(), llvm::MipsFrameLowering::estimateStackSize(), llvm::ARMFrameLowering::fixTCReturn(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), llvm::XCoreRegisterInfo::getCalleeSavedRegs(), llvm::X86FrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffsetFromSP(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReferenceFromSP(), llvm::AArch64RegisterInfo::getFrameRegister(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::HexagonRegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::MSP430RegisterInfo::getFrameRegister(), llvm::PPCRegisterInfo::getFrameRegister(), llvm::SystemZRegisterInfo::getFrameRegister(), llvm::X86RegisterInfo::getFrameRegister(), llvm::XCoreRegisterInfo::getFrameRegister(), llvm::MSP430InstrInfo::GetInstSizeInBytes(), getJTISymbol(), getMemcpyLoadsAndStores(), getPICBaseSymbol(), llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::ARMBaseRegisterInfo::getRegPressureLimit(), llvm::MipsRegisterInfo::getRegPressureLimit(), llvm::PPCRegisterInfo::getRegPressureLimit(), llvm::X86RegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::getReservedRegs(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::MSP430RegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::SystemZRegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::XCoreRegisterInfo::getReservedRegs(), llvm::TargetInstrInfo::getSPAdjust(), llvm::MipsTargetLowering::HandleByVal(), HandleVRSaveUpdate(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::AArch64FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::RegPressureTracker::init(), llvm::GenericScheduler::initPolicy(), llvm::AArch64RegisterInfo::isReservedReg(), llvm::TargetInstrInfo::isSchedulingBoundary(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::R600TargetLowering::LowerOperation(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), llvm::MachineSSAUpdater::MachineSSAUpdater(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), MIsNeedChainEdge(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::X86RegisterInfo::needsStackRealignment(), llvm::MachineBasicBlock::print(), llvm::MachineFrameInfo::print(), print(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::Mips16FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), replaceFI(), llvm::PPCFrameLowering::replaceFPWithRealFP(), llvm::R600InstrInfo::reserveIndirectRegisters(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::HexagonFrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::XCoreFrameLowering::restoreCalleeSavedRegisters(), restoreCRs(), llvm::LiveStacks::runOnMachineFunction(), llvm::PEI::runOnMachineFunction(), llvm::StackMapLiveness::runOnMachineFunction(), llvm::Mips16RegisterInfo::saveScavengerRegister(), llvm::Thumb1RegisterInfo::saveScavengerRegister(), setCallTargetReg(), llvm::X86MachineFunctionInfo::setRestoreBasePointer(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::HexagonFrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::MachineBasicBlock::SplitCriticalEdge(), and llvm::MachineBasicBlock::updateTerminator().
getTarget()
const TargetMachine & llvm::MachineFunction::getTarget () const inline
getTarget - Return the target machine this machine code is compiled with
Definition at line 172 of file MachineFunction.h.
Referenced by addLiveInRegs(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::NVPTXTargetLowering::allowFMA(), llvm::A57ChainingConstraint::apply(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::canRealignStack(), CC_MipsO32(), checkNumAlignedDPRCS2Regs(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::ARM::createFastISel(), llvm::PPC::createFastISel(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), emitAligningInstructions(), emitComments(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::ARMFrameLowering::emitEpilogue(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitStackProbeCall(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), get64BitArgumentXMMs(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::AMDGPUInstrInfo::getIndirectIndexEnd(), llvm::AArch64InstrInfo::GetInstSizeInBytes(), llvm::ARMBaseInstrInfo::GetInstSizeInBytes(), llvm::MipsInstrInfo::GetInstSizeInBytes(), llvm::MSP430InstrInfo::GetInstSizeInBytes(), llvm::PPCInstrInfo::GetInstSizeInBytes(), llvm::SystemZInstrInfo::getInstSizeInBytes(), llvm::SIMachineFunctionInfo::getMaximumWorkGroupSize(), llvm::MachineFrameInfo::getPristineRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::SIMachineFunctionInfo::getSpilledReg(), llvm::ARMFrameLowering::hasFP(), llvm::MipsFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::SystemZFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), initReachingDef(), llvm::X86InstrInfo::loadRegFromStackSlot(), llvm::X86TargetLowering::LowerCustomJumpTableEntry(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCFrameLowering::needsFP(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::MachineInstr::print(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::X86InstrInfo::storeRegToStackSlot(), and UpdateOperandRegClass().
hasInlineAsm()
bool llvm::MachineFunction::hasInlineAsm () const inline
Returns true if the function contains any inline assembly.
Definition at line 236 of file MachineFunction.h.
insert()
void llvm::MachineFunction::insert (iterator MBBI, MachineBasicBlock * MBB) inline
Definition at line 345 of file MachineFunction.h.
Referenced by emitBlockAfter(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), EmitXBegin(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::SelectionDAGBuilder::FindMergedConditions(), and llvm::MachineBasicBlock::SplitCriticalEdge().
print()
void MachineFunction::print (raw_ostream & OS, SlotIndexes * Indexes = nullptr) const
print - Print out the MachineFunction in a format suitable for debugging to the specified stream.
Definition at line 337 of file MachineFunction.cpp.
References getName(), llvm::TargetSubtargetInfo::getRegisterInfo(), getSubtarget(), and I.
Referenced by dump().
push_back()
void llvm::MachineFunction::push_back (MachineBasicBlock * MBB) inline
Definition at line 343 of file MachineFunction.h.
push_front()
void llvm::MachineFunction::push_front (MachineBasicBlock * MBB) inline
Definition at line 344 of file MachineFunction.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), and llvm::X86FrameLowering::adjustForSegmentedStacks().
rbegin() [1/2]
reverse_iterator llvm::MachineFunction::rbegin () inline
Definition at line 331 of file MachineFunction.h.
rbegin() [2/2]
const_reverse_iterator llvm::MachineFunction::rbegin () const inline
Definition at line 332 of file MachineFunction.h.
remove()
void llvm::MachineFunction::remove (iterator MBBI) inline
Definition at line 355 of file MachineFunction.h.
Referenced by llvm::MachineBasicBlock::removeFromParent().
removeFromMBBNumbering()
void llvm::MachineFunction::removeFromMBBNumbering (unsigned N) inline
removeFromMBBNumbering - Remove the specific machine basic block from our tracker, this is only really to be used by the MachineBasicBlock implementation.
Definition at line 377 of file MachineFunction.h.
References N.
rend() [1/2]
reverse_iterator llvm::MachineFunction::rend () inline
Definition at line 333 of file MachineFunction.h.
rend() [2/2]
const_reverse_iterator llvm::MachineFunction::rend () const inline
Definition at line 334 of file MachineFunction.h.
RenumberBlocks()
void MachineFunction::RenumberBlocks (MachineBasicBlock * MBB = nullptr)
RenumberBlocks - This discards all of the MachineBasicBlock numbers and recomputes them. This guarantees that the MBB numbers are sequential, dense, and match the ordering of the blocks within the function. If a specific MachineBasicBlock is specified, only that block and those after it are renumbered.
Definition at line 141 of file MachineFunction.cpp.
References begin(), empty(), and end().
setAlignment()
void llvm::MachineFunction::setAlignment (unsigned A) inline
setAlignment - Set the alignment (log2, not bytes) of the function.
Definition at line 215 of file MachineFunction.h.
setExposesReturnsTwice()
void llvm::MachineFunction::setExposesReturnsTwice (bool B) inline
setCallsSetJmp - Set a flag that indicates if there's a call to a "returns twice" function.
Definition at line 231 of file MachineFunction.h.
setHasInlineAsm()
void llvm::MachineFunction::setHasInlineAsm (bool B) inline
Set a flag that indicates that the function contains inline assembly.
Definition at line 241 of file MachineFunction.h.
setSubtarget()
void llvm::MachineFunction::setSubtarget (const TargetSubtargetInfo * ST) inline
Definition at line 177 of file MachineFunction.h.
Referenced by llvm::MipsTargetMachine::resetSubtarget().
shouldSplitStack()
bool MachineFunction::shouldSplitStack ()
Should we be emitting segmented stack stuff for the function.
Definition at line 132 of file MachineFunction.cpp.
References getFunction(), and llvm::Function::hasFnAttribute().
Referenced by llvm::X86FrameLowering::emitPrologue().
size()
unsigned llvm::MachineFunction::size () const inline
Definition at line 336 of file MachineFunction.h.
Referenced by getJTISymbol().
splice() [1/2]
void llvm::MachineFunction::splice (iterator InsertPt, iterator MBBI) inline
Definition at line 348 of file MachineFunction.h.
Referenced by llvm::MachineBasicBlock::moveAfter(), and llvm::MachineBasicBlock::moveBefore().
splice() [2/2]
void llvm::MachineFunction::splice (iterator InsertPt, iterator MBBI, iterator MBBE) inline
Definition at line 351 of file MachineFunction.h.
verify()
void MachineFunction::verify (Pass * p = nullptr, const char * Banner = nullptr) const
verify - Run the current MachineFunction through the machine code verifier, useful for debugger use.
Definition at line 274 of file MachineVerifier.cpp.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), and llvm::X86FrameLowering::adjustForSegmentedStacks().
viewCFG()
void MachineFunction::viewCFG () const
viewCFG - This function is meant for use from the debugger. You can just say 'call F->viewCFG()' and a ghostview window should pop up from the program, displaying the CFG of the current function with the code for each basic block inside. This depends on there being a 'dot' and 'gv' program in your path.
Definition at line 416 of file MachineFunction.cpp.
References llvm::errs(), getName(), and llvm::ViewGraph().
viewCFGOnly()
void MachineFunction::viewCFGOnly () const
viewCFGOnly - This function is meant for use from the debugger. It works just like viewCFG, but it does not include the contents of basic blocks into the nodes, just the label. If you are only interested in the CFG this can make the graph smaller.
Definition at line 426 of file MachineFunction.cpp.
References llvm::errs(), getName(), and llvm::ViewGraph().
The documentation for this class was generated from the following files:
MachineFunction.h
MachineFunction.cpp
MachineVerifier.cpp