LLVM: llvm::ilist_iterator< NodeTy > Class Template Reference
LLVM API Documentation
llvm::ilist_iterator< NodeTy > Class Template Reference
#include <ilist.h>
Public Types
typedef ilist_traits< NodeTy > Traits
typedef std::iterator< std::bidirectional_iterator_tag, NodeTy, ptrdiff_t > super
typedef super::value_type value_type
typedef super::difference_type difference_type
typedef super::pointer pointer
typedef super::reference reference
Public Member Functions
ilist_iterator (pointer NP)
ilist_iterator (reference NR)
ilist_iterator ()
template<class node_ty>
ilist_iterator (const ilist_iterator< node_ty > &RHS)
template<class node_ty>
const ilist_iterator & operator= (const ilist_iterator< node_ty > &RHS)
operator pointer () const
reference operator* () const
pointer operator-> () const
bool operator== (const ilist_iterator &RHS) const
bool operator!= (const ilist_iterator &RHS) const
ilist_iterator & operator-- ()
ilist_iterator & operator++ ()
ilist_iterator operator-- (int)
ilist_iterator operator++ (int)
pointer getNodePtrUnchecked () const
Detailed Description
template<typename NodeTy>
class llvm::ilist_iterator< NodeTy >
Definition at line 145 of file ilist.h.
Member Typedef Documentation
difference_type
template<typename NodeTy> typedef super::difference_type llvm::ilist_iterator< NodeTy >::difference_type
Definition at line 154 of file ilist.h.
pointer
template<typename NodeTy> typedef super::pointer llvm::ilist_iterator< NodeTy >::pointer
Definition at line 155 of file ilist.h.
reference
template<typename NodeTy> typedef super::reference llvm::ilist_iterator< NodeTy >::reference
Definition at line 156 of file ilist.h.
super
template<typename NodeTy> typedef std::iterator<std::bidirectional_iterator_tag, NodeTy, ptrdiff_t> llvm::ilist_iterator< NodeTy >::super
Definition at line 151 of file ilist.h.
Traits
template<typename NodeTy> typedef ilist_traits<NodeTy> llvm::ilist_iterator< NodeTy >::Traits
Definition at line 149 of file ilist.h.
value_type
template<typename NodeTy> typedef super::value_type llvm::ilist_iterator< NodeTy >::value_type
Definition at line 153 of file ilist.h.
Constructor & Destructor Documentation
ilist_iterator() [1/4]
template<typename NodeTy> llvm::ilist_iterator< NodeTy >::ilist_iterator (pointer NP) inline
Definition at line 176 of file ilist.h.
ilist_iterator() [2/4]
template<typename NodeTy> llvm::ilist_iterator< NodeTy >::ilist_iterator (reference NR) inline
Definition at line 177 of file ilist.h.
ilist_iterator() [3/4]
template<typename NodeTy> llvm::ilist_iterator< NodeTy >::ilist_iterator () inline
Definition at line 178 of file ilist.h.
ilist_iterator() [4/4]
template<typename NodeTy> template<class node_ty> llvm::ilist_iterator< NodeTy >::ilist_iterator (const ilist_iterator< node_ty > & RHS) inline
Definition at line 183 of file ilist.h.
Member Function Documentation
getNodePtrUnchecked()
template<typename NodeTy> pointer llvm::ilist_iterator< NodeTy >::getNodePtrUnchecked () const inline
Definition at line 234 of file ilist.h.
Referenced by llvm::size_type< NodeTy >::insert(), llvm::operator!=(), llvm::operator!=(), llvm::ilist_iterator< const NodeTy >::operator=(), llvm::operator==(), and llvm::operator==().
operator pointer()
template<typename NodeTy> llvm::ilist_iterator< NodeTy >::operator pointer () const inline
Definition at line 195 of file ilist.h.
operator!=()
template<typename NodeTy> bool llvm::ilist_iterator< NodeTy >::operator!= (const ilist_iterator< NodeTy > & RHS) const inline
Definition at line 208 of file ilist.h.
operator*()
template<typename NodeTy> reference llvm::ilist_iterator< NodeTy >::operator* () const inline
Definition at line 199 of file ilist.h.
Referenced by llvm::ilist_iterator< const NodeTy >::operator->().
operator++() [1/2]
template<typename NodeTy> ilist_iterator & llvm::ilist_iterator< NodeTy >::operator++ () inline
Definition at line 218 of file ilist.h.
operator++() [2/2]
template<typename NodeTy> ilist_iterator llvm::ilist_iterator< NodeTy >::operator++ (int) inline
Definition at line 227 of file ilist.h.
operator--() [1/2]
template<typename NodeTy> ilist_iterator & llvm::ilist_iterator< NodeTy >::operator-- () inline
Definition at line 213 of file ilist.h.
operator--() [2/2]
template<typename NodeTy> ilist_iterator llvm::ilist_iterator< NodeTy >::operator-- (int) inline
Definition at line 222 of file ilist.h.
operator->()
template<typename NodeTy> pointer llvm::ilist_iterator< NodeTy >::operator-> () const inline
Definition at line 202 of file ilist.h.
operator=()
template<typename NodeTy> template<class node_ty> const ilist_iterator & llvm::ilist_iterator< NodeTy >::operator= (const ilist_iterator< node_ty > & RHS) inline
Definition at line 189 of file ilist.h.
operator==()
template<typename NodeTy> bool llvm::ilist_iterator< NodeTy >::operator== (const ilist_iterator< NodeTy > & RHS) const inline
Definition at line 205 of file ilist.h.
The documentation for this class was generated from the following file:
ilist.h