LLVM: llvm::NVPTXRegisterInfo Class Reference
LLVM API Documentation
llvm::NVPTXRegisterInfo Class Reference
#include <NVPTXRegisterInfo.h>
Public Member Functions
NVPTXRegisterInfo (const NVPTXSubtarget &st)
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF=nullptr) const override
NVPTX Callee Saved Registers.
BitVector getReservedRegs (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
unsigned getFrameRegister (const MachineFunction &MF) const override
ManagedStringPool * getStrPool () const
const char * getName (unsigned RegNo) const
Detailed Description
Definition at line 30 of file NVPTXRegisterInfo.h.
Constructor & Destructor Documentation
NVPTXRegisterInfo()
NVPTXRegisterInfo::NVPTXRegisterInfo (const NVPTXSubtarget & st)
Definition at line 74 of file NVPTXRegisterInfo.cpp.
References is64Bit().
Member Function Documentation
eliminateFrameIndex()
void NVPTXRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 92 of file NVPTXRegisterInfo.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::getObjectOffset().
getCalleeSavedRegs()
const MCPhysReg * NVPTXRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = nullptr) const override
NVPTX Callee Saved Registers.
Definition at line 82 of file NVPTXRegisterInfo.cpp.
getFrameRegister()
unsigned NVPTXRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 109 of file NVPTXRegisterInfo.cpp.
getName()
const char * llvm::NVPTXRegisterInfo::getName (unsigned RegNo) const inline
Definition at line 59 of file NVPTXRegisterInfo.h.
References llvm::ManagedStringPool::getManagedString(), and getStrPool().
getReservedRegs()
BitVector NVPTXRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 87 of file NVPTXRegisterInfo.cpp.
getStrPool()
ManagedStringPool * llvm::NVPTXRegisterInfo::getStrPool () const inline
Definition at line 55 of file NVPTXRegisterInfo.h.
Referenced by getName().
The documentation for this class was generated from the following files:
NVPTXRegisterInfo.h
NVPTXRegisterInfo.cpp