LLVM: llvm::MCRegUnitRootIterator Class Reference
LLVM API Documentation
llvm::MCRegUnitRootIterator Class Reference
MCRegUnitRootIterator enumerates the root registers of a register unit.
#include <MCRegisterInfo.h>
Public Member Functions
MCRegUnitRootIterator ()
MCRegUnitRootIterator (unsigned RegUnit, const MCRegisterInfo *MCRI)
unsigned operator* () const
Dereference to get the current root register.
bool isValid () const
Check if the iterator is at the end of the list.
void operator++ ()
Preincrement to move to the next root register.
Detailed Description
MCRegUnitRootIterator enumerates the root registers of a register unit.
Definition at line 598 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
MCRegUnitRootIterator() [1/2]
llvm::MCRegUnitRootIterator::MCRegUnitRootIterator () inline
Definition at line 602 of file MCRegisterInfo.h.
MCRegUnitRootIterator() [2/2]
llvm::MCRegUnitRootIterator::MCRegUnitRootIterator (unsigned RegUnit, const MCRegisterInfo * MCRI) inline
Definition at line 603 of file MCRegisterInfo.h.
Member Function Documentation
isValid()
bool llvm::MCRegUnitRootIterator::isValid () const inline
Check if the iterator is at the end of the list.
Definition at line 615 of file MCRegisterInfo.h.
Referenced by llvm::MCRegAliasIterator::MCRegAliasIterator(), operator++(), and llvm::PrintRegUnit::print().
operator*()
unsigned llvm::MCRegUnitRootIterator::operator* () const inline
Dereference to get the current root register.
Definition at line 610 of file MCRegisterInfo.h.
operator++()
void llvm::MCRegUnitRootIterator::operator++ () inline
Preincrement to move to the next root register.
Definition at line 620 of file MCRegisterInfo.h.
References isValid().
The documentation for this class was generated from the following file:
MCRegisterInfo.h