LLVM: llvm::MipsCCState Class Reference
LLVM API Documentation
llvm::MipsCCState Class Reference
#include <MipsCCState.h>
Public Types
enum SpecialCallingConvType { Mips16RetHelperConv , NoSpecialCallingConv }
Public Member Functions
MipsCCState (CallingConv::ID CC, bool isVarArg, MachineFunction &MF, SmallVectorImpl< CCValAssign > &locs, LLVMContext &C, SpecialCallingConvType SpecialCC=NoSpecialCallingConv)
void AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn, std::vector< TargetLowering::ArgListEntry > &FuncArgs, const SDNode *CallNode)
void AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn) LLVM_DELETED_FUNCTION
void AnalyzeCallOperands (const SmallVectorImpl< MVT > &Outs, SmallVectorImpl< ISD::ArgFlagsTy > &Flags, CCAssignFn Fn) LLVM_DELETED_FUNCTION
void AnalyzeFormalArguments (const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn Fn)
void AnalyzeCallResult (const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn Fn, const TargetLowering::CallLoweringInfo &CLI)
void AnalyzeReturn (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn)
bool CheckReturn (const SmallVectorImpl< ISD::OutputArg > &ArgsFlags, CCAssignFn Fn)
bool WasOriginalArgF128 (unsigned ValNo)
bool WasOriginalArgFloat (unsigned ValNo)
bool IsCallOperandFixed (unsigned ValNo)
SpecialCallingConvType getSpecialCallingConv ()
Public Member Functions inherited from llvm::CCState
CCState (CallingConv::ID CC, bool isVarArg, MachineFunction &MF, SmallVectorImpl< CCValAssign > &locs, LLVMContext &C)
void addLoc (const CCValAssign &V)
LLVMContext & getContext () const
MachineFunction & getMachineFunction () const
CallingConv::ID getCallingConv () const
bool isVarArg () const
unsigned getNextStackOffset () const
bool isAllocated (unsigned Reg) const
void AnalyzeFormalArguments (const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn Fn)
void AnalyzeReturn (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn)
bool CheckReturn (const SmallVectorImpl< ISD::OutputArg > &ArgsFlags, CCAssignFn Fn)
void AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > &Outs, CCAssignFn Fn)
void AnalyzeCallOperands (SmallVectorImpl< MVT > &ArgVTs, SmallVectorImpl< ISD::ArgFlagsTy > &Flags, CCAssignFn Fn)
void AnalyzeCallResult (const SmallVectorImpl< ISD::InputArg > &Ins, CCAssignFn Fn)
void AnalyzeCallResult (MVT VT, CCAssignFn Fn)
unsigned getFirstUnallocated (const MCPhysReg *Regs, unsigned NumRegs) const
unsigned AllocateReg (unsigned Reg)
unsigned AllocateReg (unsigned Reg, unsigned ShadowReg)
Version of AllocateReg with extra register to be shadowed.
unsigned AllocateReg (const MCPhysReg *Regs, unsigned NumRegs)
unsigned AllocateRegBlock (ArrayRef< uint16_t > Regs, unsigned RegsRequired)
unsigned AllocateReg (const MCPhysReg *Regs, const MCPhysReg *ShadowRegs, unsigned NumRegs)
Version of AllocateReg with list of registers to be shadowed.
unsigned AllocateStack (unsigned Size, unsigned Align)
unsigned AllocateStack (unsigned Size, unsigned Align, unsigned ShadowReg)
Version of AllocateStack with extra register to be shadowed.
unsigned AllocateStack (unsigned Size, unsigned Align, const MCPhysReg *ShadowRegs, unsigned NumShadowRegs)
void HandleByVal (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, int MinSize, int MinAlign, ISD::ArgFlagsTy ArgFlags)
unsigned getInRegsParamsCount () const
unsigned getInRegsParamsProcessed () const
void getInRegsParamInfo (unsigned InRegsParamRecordIndex, unsigned &BeginReg, unsigned &EndReg) const
void addInRegsParamInfo (unsigned RegBegin, unsigned RegEnd)
bool nextInRegsParam ()
void clearByValRegsInfo ()
void rewindByValRegsInfo ()
ParmContext getCallOrPrologue () const
SmallVectorImpl< llvm::CCValAssign > & getPendingLocs ()
void getRemainingRegParmsForType (SmallVectorImpl< MCPhysReg > &Regs, MVT VT, CCAssignFn Fn)
void analyzeMustTailForwardedRegisters (SmallVectorImpl< ForwardedRegister > &Forwards, ArrayRef< MVT > RegParmTypes, CCAssignFn Fn)
Static Public Member Functions
static SpecialCallingConvType getSpecialCallingConvForCallee (const SDNode *Callee, const MipsSubtarget &Subtarget)
Determine the SpecialCallingConvType for the given callee.
Additional Inherited Members
Protected Attributes inherited from llvm::CCState
ParmContext CallOrPrologue
Detailed Description
Definition at line 21 of file MipsCCState.h.
Member Enumeration Documentation
SpecialCallingConvType
enum llvm::MipsCCState::SpecialCallingConvType
Enumerator
Mips16RetHelperConv
NoSpecialCallingConv
Definition at line 23 of file MipsCCState.h.
Constructor & Destructor Documentation
MipsCCState()
llvm::MipsCCState::MipsCCState (CallingConv::ID CC, bool isVarArg, MachineFunction & MF, SmallVectorImpl< CCValAssign > & locs, LLVMContext & C, SpecialCallingConvType SpecialCC = NoSpecialCallingConv) inline
Definition at line 67 of file MipsCCState.h.
References llvm::CCState::CCState(), llvm::CCState::isVarArg(), and NoSpecialCallingConv.
Member Function Documentation
AnalyzeCallOperands() [1/3]
void llvm::MipsCCState::AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > & Outs, CCAssignFn Fn)
References LLVM_DELETED_FUNCTION.
AnalyzeCallOperands() [2/3]
void llvm::MipsCCState::AnalyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > & Outs, CCAssignFn Fn, std::vector< TargetLowering::ArgListEntry > & FuncArgs, const SDNode * CallNode) inline
Definition at line 73 of file MipsCCState.h.
References llvm::CCState::AnalyzeCallOperands().
AnalyzeCallOperands() [3/3]
void llvm::MipsCCState::AnalyzeCallOperands (const SmallVectorImpl< MVT > & Outs, SmallVectorImpl< ISD::ArgFlagsTy > & Flags, CCAssignFn Fn)
References LLVM_DELETED_FUNCTION.
AnalyzeCallResult()
void llvm::MipsCCState::AnalyzeCallResult (const SmallVectorImpl< ISD::InputArg > & Ins, CCAssignFn Fn, const TargetLowering::CallLoweringInfo & CLI) inline
Definition at line 101 of file MipsCCState.h.
References llvm::CCState::AnalyzeCallResult().
AnalyzeFormalArguments()
void llvm::MipsCCState::AnalyzeFormalArguments (const SmallVectorImpl< ISD::InputArg > & Ins, CCAssignFn Fn) inline
Definition at line 93 of file MipsCCState.h.
References llvm::CCState::AnalyzeFormalArguments().
AnalyzeReturn()
void llvm::MipsCCState::AnalyzeReturn (const SmallVectorImpl< ISD::OutputArg > & Outs, CCAssignFn Fn) inline
Definition at line 110 of file MipsCCState.h.
References llvm::CCState::AnalyzeReturn().
CheckReturn()
bool llvm::MipsCCState::CheckReturn (const SmallVectorImpl< ISD::OutputArg > & ArgsFlags, CCAssignFn Fn) inline
Definition at line 118 of file MipsCCState.h.
References llvm::CCState::CheckReturn().
getSpecialCallingConv()
SpecialCallingConvType llvm::MipsCCState::getSpecialCallingConv () inline
Definition at line 132 of file MipsCCState.h.
getSpecialCallingConvForCallee()
MipsCCState::SpecialCallingConvType MipsCCState::getSpecialCallingConvForCallee (const SDNode * Callee, const MipsSubtarget & Subtarget) static
Determine the SpecialCallingConvType for the given callee.
Definition at line 64 of file MipsCCState.cpp.
References llvm::dyn_cast(), F, G, llvm::MipsSubtarget::inMips16HardFloat(), Mips16RetHelperConv, and NoSpecialCallingConv.
IsCallOperandFixed()
bool llvm::MipsCCState::IsCallOperandFixed (unsigned ValNo) inline
Definition at line 131 of file MipsCCState.h.
WasOriginalArgF128()
bool llvm::MipsCCState::WasOriginalArgF128 (unsigned ValNo) inline
Definition at line 127 of file MipsCCState.h.
WasOriginalArgFloat()
bool llvm::MipsCCState::WasOriginalArgFloat (unsigned ValNo) inline
Definition at line 128 of file MipsCCState.h.
The documentation for this class was generated from the following files:
MipsCCState.h
MipsCCState.cpp