LLVM: llvm::CGSCCAnalysisManagerFunctionProxy::Result Class Reference
LLVM API Documentation
llvm::CGSCCAnalysisManagerFunctionProxy::Result Class Reference
Result proxy object for ModuleAnalysisManagerFunctionProxy.
#include <CGSCCPassManager.h>
Public Member Functions
Result (const CGSCCAnalysisManager &CGAM)
Result (const Result &Arg)
Result (Result &&Arg)
Result & operator= (Result RHS)
const CGSCCAnalysisManager & getManager () const
bool invalidate (Function &)
Handle invalidation by ignoring it, this pass is immutable.
Detailed Description
Result proxy object for ModuleAnalysisManagerFunctionProxy.
Definition at line 363 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
Result() [1/3]
llvm::CGSCCAnalysisManagerFunctionProxy::Result::Result (const CGSCCAnalysisManager & CGAM) inline explicit
Definition at line 365 of file CGSCCPassManager.h.
Referenced by operator=(), Result(), and Result().
Result() [2/3]
llvm::CGSCCAnalysisManagerFunctionProxy::Result::Result (const Result & Arg) inline
Definition at line 368 of file CGSCCPassManager.h.
References Result().
Result() [3/3]
llvm::CGSCCAnalysisManagerFunctionProxy::Result::Result (Result && Arg) inline
Definition at line 369 of file CGSCCPassManager.h.
References Result().
Member Function Documentation
getManager()
const CGSCCAnalysisManager & llvm::CGSCCAnalysisManagerFunctionProxy::Result::getManager () const inline
Definition at line 375 of file CGSCCPassManager.h.
invalidate()
bool llvm::CGSCCAnalysisManagerFunctionProxy::Result::invalidate (Function &) inline
Handle invalidation by ignoring it, this pass is immutable.
Definition at line 378 of file CGSCCPassManager.h.
operator=()
Result & llvm::CGSCCAnalysisManagerFunctionProxy::Result::operator= (Result RHS) inline
Definition at line 370 of file CGSCCPassManager.h.
References Result(), and std::swap().
The documentation for this class was generated from the following file:
CGSCCPassManager.h