LLVM: llvm::ConstMIOperands Class Reference
LLVM API Documentation
llvm::ConstMIOperands Class Reference
#include <MachineInstrBundle.h>
Public Member Functions
ConstMIOperands (const MachineInstr *MI)
const MachineOperand & operator* () const
const MachineOperand * operator-> () const
Public Member Functions inherited from llvm::MachineOperandIteratorBase
bool isValid () const
isValid - Returns true until all the operands have been visited.
void operator++ ()
Preincrement. Move to the next operand.
unsigned getOperandNo () const
VirtRegInfo analyzeVirtReg (unsigned Reg, SmallVectorImpl< std::pair< MachineInstr *, unsigned > > *Ops=nullptr)
PhysRegInfo analyzePhysReg (unsigned Reg, const TargetRegisterInfo *TRI)
Additional Inherited Members
Protected Member Functions inherited from llvm::MachineOperandIteratorBase
MachineOperandIteratorBase (MachineInstr *MI, bool WholeBundle)
MachineOperand & deref () const
Detailed Description
ConstMIOperands - Iterate over operands of a single const instruction.
Definition at line 221 of file MachineInstrBundle.h.
Constructor & Destructor Documentation
ConstMIOperands()
llvm::ConstMIOperands::ConstMIOperands (const MachineInstr * MI) inline
Definition at line 223 of file MachineInstrBundle.h.
References llvm::MachineOperandIteratorBase::MachineOperandIteratorBase().
Member Function Documentation
operator*()
const MachineOperand & llvm::ConstMIOperands::operator* () const inline
Definition at line 225 of file MachineInstrBundle.h.
References llvm::MachineOperandIteratorBase::deref().
operator->()
const MachineOperand * llvm::ConstMIOperands::operator-> () const inline
Definition at line 226 of file MachineInstrBundle.h.
References llvm::MachineOperandIteratorBase::deref().
The documentation for this class was generated from the following file:
MachineInstrBundle.h