LLVM: llvm::ARMSelectionDAGInfo Class Reference
LLVM API Documentation
llvm::ARMSelectionDAGInfo Class Reference
#include <ARMSelectionDAGInfo.h>
Public Member Functions
ARMSelectionDAGInfo (const DataLayout &DL)
~ARMSelectionDAGInfo ()
SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override
SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const override
Public Member Functions inherited from llvm::TargetSelectionDAGInfo
TargetSelectionDAGInfo (const DataLayout *DL)
virtual ~TargetSelectionDAGInfo ()
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
Additional Inherited Members
Protected Member Functions inherited from llvm::TargetSelectionDAGInfo
const DataLayout * getDataLayout () const
Detailed Description
Definition at line 38 of file ARMSelectionDAGInfo.h.
Constructor & Destructor Documentation
ARMSelectionDAGInfo()
ARMSelectionDAGInfo::ARMSelectionDAGInfo (const DataLayout & DL) explicit
Definition at line 21 of file ARMSelectionDAGInfo.cpp.
~ARMSelectionDAGInfo()
ARMSelectionDAGInfo::~ARMSelectionDAGInfo ()
Definition at line 24 of file ARMSelectionDAGInfo.cpp.
Member Function Documentation
EmitTargetCodeForMemcpy()
SDValue ARMSelectionDAGInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override virtual
EmitTargetCodeForMemcpy - Emit target-specific code that performs a memcpy. This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 28 of file ARMSelectionDAGInfo.cpp.
References llvm::ISD::ADD, Align, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getLoad(), llvm::ARMSubtarget::getMaxInlineSizeThreshold(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getStore(), llvm::TargetMachine::getSubtarget(), llvm::SelectionDAG::getTarget(), llvm::MachinePointerInfo::getWithOffset(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::ARMSubtarget::isThumb1Only(), Loads, llvm::makeArrayRef(), llvm::MVT::Other, and llvm::ISD::TokenFactor.
EmitTargetCodeForMemset()
SDValue ARMSelectionDAGInfo::EmitTargetCodeForMemset (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const override virtual
EmitTargetCodeForMemset - Emit target-specific code that performs a memset. This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 147 of file ARMSelectionDAGInfo.cpp.
References Align, llvm::EVT::bitsGT(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getExternalSymbol(), llvm::Type::getInt32Ty(), llvm::DataLayout::getIntPtrType(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetMachine::getSubtarget(), llvm::SelectionDAG::getTarget(), llvm::SDValue::getValueType(), llvm::Type::getVoidTy(), llvm::MVT::i32, llvm::ARMSubtarget::isAAPCS_ABI(), llvm::TargetLowering::ArgListEntry::isSExt, llvm::ARMSubtarget::isTargetMachO(), llvm::ARMSubtarget::isTargetWindows(), llvm::TargetLowering::LowerCallTo(), llvm::RTLIB::MEMSET, llvm::TargetLowering::ArgListEntry::Node, llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), llvm::ISD::TRUNCATE, llvm::TargetLowering::ArgListEntry::Ty, and llvm::ISD::ZERO_EXTEND.
The documentation for this class was generated from the following files:
ARMSelectionDAGInfo.h
ARMSelectionDAGInfo.cpp