LLVM: llvm::BitcodeDiagnosticInfo Class Reference
LLVM API Documentation
llvm::BitcodeDiagnosticInfo Class Reference
#include <ReaderWriter.h>
Public Member Functions
BitcodeDiagnosticInfo (std::error_code EC, DiagnosticSeverity Severity, const Twine &Msg)
void print (DiagnosticPrinter &DP) const override
std::error_code getError () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Definition at line 151 of file ReaderWriter.h.
Constructor & Destructor Documentation
BitcodeDiagnosticInfo()
BitcodeDiagnosticInfo::BitcodeDiagnosticInfo (std::error_code EC, DiagnosticSeverity Severity, const Twine & Msg)
Definition at line 37 of file BitcodeReader.cpp.
References llvm::DiagnosticInfo::DiagnosticInfo(), and llvm::DK_Bitcode.
Member Function Documentation
classof()
bool llvm::BitcodeDiagnosticInfo::classof (const DiagnosticInfo * DI) inline static
Definition at line 161 of file ReaderWriter.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_Bitcode, and llvm::DiagnosticInfo::getKind().
getError()
std::error_code llvm::BitcodeDiagnosticInfo::getError () const inline
Definition at line 159 of file ReaderWriter.h.
print()
void BitcodeDiagnosticInfo::print (DiagnosticPrinter & DP) const override virtual
Print using the given DP a user-friendly message. This is the default message that will be printed to the user. It is used when the frontend does not directly take advantage of the information contained in fields of the subclasses. The printed message must not end with '.' nor start with a severity keyword.
Implements llvm::DiagnosticInfo.
Definition at line 42 of file BitcodeReader.cpp.
The documentation for this class was generated from the following files:
ReaderWriter.h
BitcodeReader.cpp