LLVM: llvm::RecordRecTy Class Reference
LLVM API Documentation
llvm::RecordRecTy Class Reference
#include <Record.h>
Public Member Functions
Record * getRecord () const
Init * convertValue (UnsetInit *UI) override
Init * convertValue (BitInit *BI) override
Init * convertValue (BitsInit *BI) override
Init * convertValue (IntInit *II) override
Init * convertValue (StringInit *SI) override
Init * convertValue (ListInit *LI) override
Init * convertValue (VarBitInit *VB) override
Init * convertValue (UnOpInit *UI) override
Init * convertValue (BinOpInit *UI) override
Init * convertValue (TernOpInit *UI) override
Init * convertValue (DefInit *DI) override
Init * convertValue (DagInit *DI) override
Init * convertValue (TypedInit *VI) override
Init * convertValue (VarInit *VI) override
Init * convertValue (FieldInit *FI) override
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
bool baseClassOf (const RecTy *) const override
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static RecordRecTy * get (Record *R)
Friends
class Record
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
RecordRecTy - '[classname]' - Represent an instance of a class, such as: (R32 X = EAX).
Definition at line 371 of file Record.h.
Member Function Documentation
baseClassOf()
bool RecordRecTy::baseClassOf (const RecTy * RHS) const override virtual
Reimplemented from llvm::RecTy.
Definition at line 371 of file Record.cpp.
References llvm::dyn_cast(), and llvm::RecTy::RecTy().
classof()
bool llvm::RecordRecTy::classof (const RecTy * RT) inline static
Definition at line 377 of file Record.h.
References llvm::RecTy::getRecTyKind(), llvm::RecTy::RecordRecTyKind, and llvm::RecTy::RecTy().
convertValue() [1/15]
Init * llvm::RecordRecTy::convertValue (BinOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 393 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [2/15]
Init * llvm::RecordRecTy::convertValue (BitInit * BI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 386 of file Record.h.
convertValue() [3/15]
Init * llvm::RecordRecTy::convertValue (BitsInit * BI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 387 of file Record.h.
convertValue() [4/15]
Init * llvm::RecordRecTy::convertValue (DagInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 396 of file Record.h.
convertValue() [5/15]
Init * RecordRecTy::convertValue (DefInit * DI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 355 of file Record.cpp.
References llvm::DefInit::getDef(), and llvm::Record::isSubClassOf().
convertValue() [6/15]
Init * llvm::RecordRecTy::convertValue (FieldInit * FI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 399 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [7/15]
Init * llvm::RecordRecTy::convertValue (IntInit * II) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 388 of file Record.h.
convertValue() [8/15]
Init * llvm::RecordRecTy::convertValue (ListInit * LI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 390 of file Record.h.
convertValue() [9/15]
Init * llvm::RecordRecTy::convertValue (StringInit * SI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 389 of file Record.h.
convertValue() [10/15]
Init * llvm::RecordRecTy::convertValue (TernOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 394 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [11/15]
Init * RecordRecTy::convertValue (TypedInit * VI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 362 of file Record.cpp.
References llvm::dyn_cast(), getRecord(), and llvm::TypedInit::getType().
convertValue() [12/15]
Init * llvm::RecordRecTy::convertValue (UnOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 392 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [13/15]
Init * llvm::RecordRecTy::convertValue (UnsetInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 385 of file Record.h.
convertValue() [14/15]
Init * llvm::RecordRecTy::convertValue (VarBitInit * VB) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 391 of file Record.h.
convertValue() [15/15]
Init * llvm::RecordRecTy::convertValue (VarInit * VI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 398 of file Record.h.
References llvm::RecTy::convertValue(), and VI.
get()
RecordRecTy * RecordRecTy::get (Record * R) static
Definition at line 347 of file Record.cpp.
References llvm::dyn_cast(), llvm::Record::getDefInit(), llvm::TypedInit::getType(), and Record.
Referenced by llvm::resolveTypes().
getAsString()
std::string RecordRecTy::getAsString () const override virtual
Implements llvm::RecTy.
Definition at line 351 of file Record.cpp.
getRecord()
Record * llvm::RecordRecTy::getRecord () const inline
Definition at line 383 of file Record.h.
References Record.
Referenced by convertValue().
typeIsConvertibleTo()
bool llvm::RecordRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline override virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 403 of file Record.h.
References llvm::RecTy::baseClassOf(), and llvm::RecTy::RecTy().
Friends And Related Symbol Documentation
Record
friend class Record friend
Definition at line 374 of file Record.h.
References Record.
Referenced by get(), getRecord(), and Record.
The documentation for this class was generated from the following files:
Record.h
Record.cpp