LLVM: llvm::X86FrameLowering Class Reference
LLVM API Documentation
llvm::X86FrameLowering Class Reference
#include <X86FrameLowering.h>
Public Member Functions
X86FrameLowering (StackDirection D, unsigned StackAl, int LAO)
void emitCalleeSavedFrameMoves (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL) const
void emitPrologue (MachineFunction &MF) const override
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
void adjustForSegmentedStacks (MachineFunction &MF) const override
void adjustForHiPEPrologue (MachineFunction &MF) const override
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS=nullptr) const override
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const override
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
bool hasFP (const MachineFunction &MF) const override
bool hasReservedCallFrame (const MachineFunction &MF) const override
int getFrameIndexOffset (const MachineFunction &MF, int FI) const override
int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const override
int getFrameIndexOffsetFromSP (const MachineFunction &MF, int FI) const
int getFrameIndexReferenceFromSP (const MachineFunction &MF, int FI, unsigned &FrameReg) const override
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
unsigned getStackAlignment () const
unsigned getTransientStackAlignment () const
bool isStackRealignable () const
int getOffsetOfLocalArea () const
virtual bool isFPCloseToIncomingSP () const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
virtual bool targetHandlesStackFrameRounding () const
virtual void adjustForFrameAllocatePrologue (MachineFunction &MF) const
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
Static Public Member Functions
static void emitStackProbeCall (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL)
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Detailed Description
Definition at line 25 of file X86FrameLowering.h.
Constructor & Destructor Documentation
X86FrameLowering()
llvm::X86FrameLowering::X86FrameLowering (StackDirection D, unsigned StackAl, int LAO) inline explicit
Definition at line 27 of file X86FrameLowering.h.
References llvm::TargetFrameLowering::StackGrowsDown, and llvm::TargetFrameLowering::TargetFrameLowering().
Member Function Documentation
adjustForHiPEPrologue()
void X86FrameLowering::adjustForHiPEPrologue (MachineFunction & MF) const override virtual
Erlang programs may need a special prologue to handle the stack size they might need at runtime. That is because Erlang/OTP does not implement a C stack but uses a custom implementation of hybrid stack/heap architecture. (for more information see Eric Stenman's Ph.D. thesis: http://publications.uu.se/uu/fulltext/nbn_se_uu_diva-2688.pdf)
CheckStack: temp0 = sp - MaxStack if(temp0 < SP_LIMIT(P)) goto IncStack else goto OldStart OldStart: ... IncStack: call inc_stack # doubles the stack space temp0 = sp - MaxStack if(temp0 < SP_LIMIT(P)) goto IncStack else goto OldStart
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1752 of file X86FrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::addRegOffset(), llvm::MachineBasicBlock::addSuccessor(), llvm::Function::arg_size(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::dyn_cast(), llvm::MachineFunction::end(), F, llvm::MachineFunction::front(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getRegInfo(), GetScratchRegister(), llvm::X86RegisterInfo::getSlotSize(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasCalls(), I, llvm::X86Subtarget::is64Bit(), llvm::MachineOperand::isGlobal(), llvm::MachineRegisterInfo::isLiveIn(), llvm::X86Subtarget::isTarget64BitLP64(), llvm::X86Subtarget::isTargetLinux(), llvm::MachineBasicBlock::livein_begin(), llvm::MachineBasicBlock::livein_end(), llvm::StringRef::npos, llvm::MachineFunction::push_front(), TII, and llvm::MachineFunction::verify().
adjustForSegmentedStacks()
void X86FrameLowering::adjustForSegmentedStacks (MachineFunction & MF) const override virtual
Adjust the prologue to have the function use segmented stacks. This works by adding a check even before the "normal" function prologue.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1502 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineFunction::front(), llvm::X86MachineFunctionInfo::getArgumentStackSize(), llvm::TargetMachine::getCodeModel(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MachineFunction::getRegInfo(), GetScratchRegister(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), HasNestArgument(), llvm::X86Subtarget::is64Bit(), llvm::MachineRegisterInfo::isLiveIn(), llvm::X86Subtarget::isTarget64BitLP64(), llvm::X86Subtarget::isTargetDarwin(), llvm::X86Subtarget::isTargetDragonFly(), llvm::X86Subtarget::isTargetFreeBSD(), llvm::X86Subtarget::isTargetLinux(), llvm::X86Subtarget::isTargetWin32(), llvm::X86Subtarget::isTargetWin64(), llvm::Function::isVarArg(), llvm::RegState::Kill, kSplitStackAvailable, llvm::CodeModel::Large, llvm::MachineBasicBlock::livein_begin(), llvm::MachineBasicBlock::livein_end(), llvm::MachineFunction::push_front(), llvm::report_fatal_error(), llvm::MachineRegisterInfo::setPhysRegUsed(), llvm::MachineModuleInfo::setUsesMorestackAddr(), TII, and llvm::MachineFunction::verify().
assignCalleeSavedSpillSlots()
bool X86FrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const override virtual
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic. If implemented, assignCalleeSavedSpillSlots() should assign frame slots to all CSI entries and return true. If this method returns false, spill slots will be assigned using generic implementation. assignCalleeSavedSpillSlots() may add, delete or rearrange elements of CSI.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1272 of file X86FrameLowering.cpp.
References contains(), llvm::MachineFrameInfo::CreateFixedSpillStackObject(), llvm::MachineFrameInfo::ensureMaxAlignment(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), llvm::X86RegisterInfo::getFrameRegister(), llvm::MachineFunction::getInfo(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::TargetRegisterClass::getSize(), llvm::X86RegisterInfo::getSlotSize(), llvm::MachineFunction::getSubtarget(), llvm::X86MachineFunctionInfo::getTCReturnAddrDelta(), hasFP(), llvm::TargetRegisterInfo::regsOverlap(), and llvm::X86MachineFunctionInfo::setCalleeSavedFrameSize().
eliminateCallFramePseudoInstr()
void X86FrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them). It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1979 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineBasicBlock::erase(), getADDriOpcode(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::TargetFrameLowering::getStackAlignment(), llvm::X86RegisterInfo::getStackRegister(), getSUBriOpcode(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::TargetMachine::getSubtargetImpl(), llvm::MachineFunction::getTarget(), hasReservedCallFrame(), I, llvm::MachineBasicBlock::insert(), llvm::X86Subtarget::isTarget64BitLP64(), llvm::MachineOperand::setIsDead(), and TII.
emitCalleeSavedFrameMoves()
void X86FrameLowering::emitCalleeSavedFrameMoves (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL) const
Definition at line 333 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineModuleInfo::addFrameInst(), llvm::BuildMI(), llvm::TargetOpcode::CFI_INSTRUCTION, llvm::MCCFIInstruction::createOffset(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineModuleInfo::getContext(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineBasicBlock::getParent(), llvm::MCContext::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), I, and TII.
Referenced by emitPrologue().
emitEpilogue()
void X86FrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 924 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::addRegOffset(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineInstr::copyImplicitOps(), emitSPUpdate(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), ForceStackAlign, FramePtr, llvm::X86MachineFunctionInfo::getCalleeSavedFrameSize(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), getLEArOpcode(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), llvm::MachineOperand::getTargetFlags(), llvm::X86MachineFunctionInfo::getTCReturnAddrDelta(), llvm::getX86SubSuperRegister(), llvm::MachineFrameInfo::hasCalls(), hasFP(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MVT::i64, llvm::X86Subtarget::is64Bit(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::isMem(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isSymbol(), llvm::X86Subtarget::isTarget64BitILP32(), llvm::X86Subtarget::isTarget64BitLP64(), llvm::X86Subtarget::isTargetNaCl64(), llvm::MachineInstr::isTerminator(), llvm::RegState::Kill, llvm_unreachable, mergeSPUpdates(), mergeSPUpdatesUp(), llvm::Function::needsUnwindTableEntry(), TII, llvm::X86Subtarget::useLeaForSP(), and llvm::MCAsmInfo::usesWindowsCFI().
emitPrologue()
void X86FrameLowering::emitPrologue (MachineFunction & MF) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
emitPrologue - Push callee-saved registers onto the stack, which automatically adjust the stack pointer. Adjust the stack pointer to allocate space for local variables. Also emit labels used by the exception handler to generate the exception handling frames.
Implements llvm::TargetFrameLowering.
Definition at line 523 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineModuleInfo::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::addRegOffset(), llvm::MachineFrameInfo::adjustsStack(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::TargetOpcode::CFI_INSTRUCTION, contains(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createOffset(), emitCalleeSavedFrameMoves(), emitSPUpdate(), emitStackProbeCall(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), ForceStackAlign, FramePtr, llvm::MachineInstr::FrameSetup, llvm::MachineFunction::front(), llvm::AttributeSet::FunctionIndex, getANDriOpcode(), llvm::StringRef::getAsInteger(), llvm::Function::getAttributes(), llvm::X86RegisterInfo::getBaseRegister(), llvm::X86MachineFunctionInfo::getCalleeSavedFrameSize(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineInstr::getFlag(), llvm::Function::getFnAttribute(), getFrameIndexOffset(), llvm::MachineFunction::getFrameInfo(), llvm::X86RegisterInfo::getFrameRegister(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getMMI(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::X86MachineFunctionInfo::getRestoreBasePointer(), llvm::X86MachineFunctionInfo::getRestoreBasePointerOffset(), llvm::X86RegisterInfo::getSlotSize(), llvm::TargetFrameLowering::getStackAlignment(), llvm::X86RegisterInfo::getStackRegister(), llvm::MachineFrameInfo::getStackSize(), getSUBriOpcode(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::X86MachineFunctionInfo::getTCReturnAddrDelta(), llvm::Attribute::getValueAsString(), llvm::getX86SubSuperRegister(), llvm::AttributeSet::hasAttribute(), llvm::X86RegisterInfo::hasBasePointer(), llvm::MachineFrameInfo::hasCalls(), llvm::MachineModuleInfo::hasDebugInfo(), llvm::Function::hasFnAttribute(), hasFP(), llvm::MachineFrameInfo::hasVarSizedObjects(), I, llvm::MVT::i64, llvm::MachineBasicBlock::insert(), llvm::X86Subtarget::is64Bit(), isEAXLiveIn(), llvm::X86Subtarget::isOSWindows(), llvm::X86Subtarget::isTarget64BitILP32(), llvm::X86Subtarget::isTarget64BitLP64(), llvm::X86Subtarget::isTargetMachO(), llvm::X86Subtarget::isTargetNaCl64(), llvm::X86Subtarget::isTargetWin64(), llvm::RegState::Kill, mergeSPUpdates(), mergeSPUpdatesDown(), llvm::X86RegisterInfo::needsStackRealignment(), llvm::Function::needsUnwindTableEntry(), llvm::Attribute::NoRedZone, llvm::X86MachineFunctionInfo::setCalleeSavedFrameSize(), llvm::MachineInstr::setFlag(), llvm::MachineInstrBuilder::setMIFlag(), llvm::MachineFrameInfo::setOffsetAdjustment(), llvm::MachineFrameInfo::setStackSize(), llvm::MachineFunction::shouldSplitStack(), TII, llvm::X86Subtarget::useLeaForSP(), usesTheStack(), and llvm::MCAsmInfo::usesWindowsCFI().
emitStackProbeCall()
void X86FrameLowering::emitStackProbeCall (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL) static
Emit a call to the target's stack probe function. This is required for all large stack allocations on Windows. The caller is required to materialize the number of bytes to probe in RAX/EAX.
Definition at line 378 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::RegState::Define, llvm::TargetMachine::getCodeModel(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::RegState::Implicit, llvm::X86Subtarget::is64Bit(), llvm::X86Subtarget::isTargetCygMing(), llvm::CodeModel::Large, and TII.
Referenced by emitPrologue().
getFrameIndexOffset()
int X86FrameLowering::getFrameIndexOffset (const MachineFunction & MF, int FI) const override virtual
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index.
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index. This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1140 of file X86FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::X86RegisterInfo::getSlotSize(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::X86MachineFunctionInfo::getTCReturnAddrDelta(), llvm::X86RegisterInfo::hasBasePointer(), hasFP(), and llvm::X86RegisterInfo::needsStackRealignment().
Referenced by emitPrologue(), and getFrameIndexReference().
getFrameIndexOffsetFromSP()
int X86FrameLowering::getFrameIndexOffsetFromSP (const MachineFunction & MF, int FI) const
Definition at line 1200 of file X86FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), and llvm::X86RegisterInfo::hasBasePointer().
Referenced by getFrameIndexReferenceFromSP().
getFrameIndexReference()
int X86FrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, unsigned & FrameReg) const override virtual
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location. The offset is returned directly, and the base register is returned via FrameReg.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1183 of file X86FrameLowering.cpp.
References llvm::X86RegisterInfo::getBaseRegister(), getFrameIndexOffset(), llvm::X86RegisterInfo::getFrameRegister(), llvm::X86RegisterInfo::getStackRegister(), llvm::MachineFunction::getSubtarget(), llvm::X86RegisterInfo::hasBasePointer(), and llvm::X86RegisterInfo::needsStackRealignment().
getFrameIndexReferenceFromSP()
int X86FrameLowering::getFrameIndexReferenceFromSP (const MachineFunction & MF, int FI, unsigned & FrameReg) const override virtual
Same as above, except that the 'base register' will always be RSP, not RBP on x86. This is used exclusively for lowering STATEPOINT nodes. TODO: This should really be a parameterizable choice.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1261 of file X86FrameLowering.cpp.
References getFrameIndexOffsetFromSP(), llvm::X86RegisterInfo::getStackRegister(), llvm::MachineFunction::getSubtarget(), and llvm::X86RegisterInfo::hasBasePointer().
hasFP()
bool X86FrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register. This is true if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 47 of file X86FrameLowering.cpp.
References llvm::MachineModuleInfo::callsEHReturn(), llvm::MachineModuleInfo::callsUnwindInit(), llvm::TargetOptions::DisableFramePointerElim(), llvm::X86MachineFunctionInfo::getForceFramePointer(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getMMI(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasInlineAsmWithSPAdjust(), llvm::MachineFrameInfo::hasPatchPoint(), llvm::MachineFrameInfo::hasStackMap(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), llvm::TargetRegisterInfo::needsStackRealignment(), and llvm::TargetMachine::Options.
Referenced by assignCalleeSavedSpillSlots(), emitEpilogue(), emitPrologue(), and getFrameIndexOffset().
hasReservedCallFrame()
bool X86FrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function. This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 40 of file X86FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by eliminateCallFramePseudoInstr().
processFunctionBeforeCalleeSavedScan()
void X86FrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1420 of file X86FrameLowering.cpp.
References llvm::MachineFrameInfo::CreateFixedObject(), llvm::X86RegisterInfo::getBaseRegister(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::X86RegisterInfo::getSlotSize(), llvm::MachineFunction::getSubtarget(), llvm::X86MachineFunctionInfo::getTCReturnAddrDelta(), llvm::X86RegisterInfo::hasBasePointer(), and llvm::MachineRegisterInfo::setPhysRegUsed().
restoreCalleeSavedRegisters()
bool X86FrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1382 of file X86FrameLowering.cpp.
References llvm::BuildMI(), contains(), llvm::MachineBasicBlock::findDebugLoc(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::X86Subtarget::is64Bit(), and TII.
spillCalleeSavedRegisters()
bool X86FrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1337 of file X86FrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MachineInstr::FrameSetup, llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::X86Subtarget::is64Bit(), llvm::RegState::Kill, llvm::MachineInstrBuilder::setMIFlag(), and TII.
The documentation for this class was generated from the following files:
X86FrameLowering.h
X86FrameLowering.cpp