LLVM: llvm::InvokeInst Class Reference
LLVM API Documentation
llvm::InvokeInst Class Reference
#include <Instructions.h>
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
unsigned getNumArgOperands () const
Value * getArgOperand (unsigned i) const
void setArgOperand (unsigned i, Value *v)
iterator_range< op_iterator > arg_operands ()
arg_operands - iteration adapter for range-for loops.
iterator_range< const_op_iterator > arg_operands () const
arg_operands - iteration adapter for range-for loops.
const Use & getArgOperandUse (unsigned i) const
Wrappers for getting the Use of a invoke argument.
Use & getArgOperandUse (unsigned i)
CallingConv::ID getCallingConv () const
void setCallingConv (CallingConv::ID CC)
const AttributeSet & getAttributes () const
void setAttributes (const AttributeSet &Attrs)
void addAttribute (unsigned i, Attribute::AttrKind attr)
addAttribute - adds the attribute to the list of attributes.
void removeAttribute (unsigned i, Attribute attr)
removeAttribute - removes the attribute from the list of attributes.
bool hasFnAttr (Attribute::AttrKind A) const
Determine whether this call has the given attribute.
bool paramHasAttr (unsigned i, Attribute::AttrKind A) const
Determine whether the call or the callee has the given attributes.
unsigned getParamAlignment (unsigned i) const
Extract the alignment for a call or parameter (0=unknown).
uint64_t getDereferenceableBytes (unsigned i) const
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
bool isNoBuiltin () const
Return true if the call should not be treated as a call to a builtin.
bool isNoInline () const
Return true if the call should not be inlined.
void setIsNoInline ()
bool doesNotAccessMemory () const
Determine if the call does not access memory.
void setDoesNotAccessMemory ()
bool onlyReadsMemory () const
Determine if the call does not access or only reads memory.
void setOnlyReadsMemory ()
bool doesNotReturn () const
Determine if the call cannot return.
void setDoesNotReturn ()
bool doesNotThrow () const
Determine if the call cannot unwind.
void setDoesNotThrow ()
bool cannotDuplicate () const
Determine if the invoke cannot be duplicated.
void setCannotDuplicate ()
bool hasStructRetAttr () const
Determine if the call returns a structure through first pointer argument.
bool hasByValArgument () const
Determine if any call argument is an aggregate passed by value.
Function * getCalledFunction () const
const Value * getCalledValue () const
Value * getCalledValue ()
void setCalledFunction (Value *Fn)
setCalledFunction - Set the function called.
BasicBlock * getNormalDest () const
BasicBlock * getUnwindDest () const
void setNormalDest (BasicBlock *B)
void setUnwindDest (BasicBlock *B)
LandingPadInst * getLandingPadInst () const
BasicBlock * getSuccessor (unsigned i) const
void setSuccessor (unsigned idx, BasicBlock *NewSucc)
unsigned getNumSuccessors () const
Public Member Functions inherited from llvm::TerminatorInst
unsigned getNumSuccessors () const
Return the number of successors that this terminator has.
BasicBlock * getSuccessor (unsigned idx) const
Return the specified successor.
void setSuccessor (unsigned idx, BasicBlock *B)
Update the specified successor to point at the provided block.
Public Member Functions inherited from llvm::Instruction
~Instruction ()
Instruction * user_back ()
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const DataLayout * getDataLayout () const
void removeFromParent ()
void eraseFromParent ()
void insertBefore (Instruction *InsertPos)
void insertAfter (Instruction *InsertPos)
void moveBefore (Instruction *MovePos)
unsigned getOpcode () const
getOpcode() returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isBinaryOp () const
bool isShift ()
bool isCast () const
bool isLogicalShift () const
bool isArithmeticShift () const
isArithmeticShift - Return true if this is an arithmetic shift right.
bool hasMetadata () const
bool hasMetadataOtherThanDebugLoc () const
MDNode * getMetadata (unsigned KindID) const
MDNode * getMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void getAAMetadata (AAMDNodes &N, bool Merge=false) const
void setMetadata (unsigned KindID, MDNode *Node)
void setMetadata (StringRef Kind, MDNode *Node)
void dropUnknownMetadata (ArrayRef< unsigned > KnownIDs)
Drop unknown metadata. Passes are required to drop metadata they don't understand. This is a convenience method for passes to do so.
void dropUnknownMetadata ()
void dropUnknownMetadata (unsigned ID1)
void dropUnknownMetadata (unsigned ID1, unsigned ID2)
void setAAMetadata (const AAMDNodes &N)
void setDebugLoc (const DebugLoc &Loc)
setDebugLoc - Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
getDebugLoc - Return the debug location for this node as a DebugLoc.
void setHasUnsafeAlgebra (bool B)
void setHasNoNaNs (bool B)
void setHasNoInfs (bool B)
void setHasNoSignedZeros (bool B)
void setHasAllowReciprocal (bool B)
void setFastMathFlags (FastMathFlags FMF)
void copyFastMathFlags (FastMathFlags FMF)
bool hasUnsafeAlgebra () const
Determine whether the unsafe-algebra flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
FastMathFlags getFastMathFlags () const
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool isAtomic () const
bool mayThrow () const
bool mayReturn () const
bool mayHaveSideEffects () const
Instruction * clone () const
bool isIdenticalTo (const Instruction *I) const
bool isIdenticalToWhenDefined (const Instruction *I) const
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
Determine if one instruction is the same operation as another.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Public Member Functions inherited from llvm::ilist_node< Instruction >
Instruction * getPrevNode ()
Get the previous node, or 0 for the list head.
Instruction * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static InvokeInst * Create (Value *Func, BasicBlock *IfNormal, BasicBlock *IfException, ArrayRef< Value * > Args, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static InvokeInst * Create (Value *Func, BasicBlock *IfNormal, BasicBlock *IfException, ArrayRef< Value * > Args, const Twine &NameStr, BasicBlock *InsertAtEnd)
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::TerminatorInst
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isBinaryOp (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isAssociative (unsigned op)
static bool isCommutative (unsigned op)
static bool isIdempotent (unsigned op)
static bool isNilpotent (unsigned op)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
InvokeInst * clone_impl () const override
Protected Member Functions inherited from llvm::TerminatorInst
TerminatorInst (Type *Ty, Instruction::TermOps iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
TerminatorInst (Type *Ty, Instruction::TermOps iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
~TerminatorInst ()
Protected Member Functions inherited from llvm::Instruction
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< Instruction >
ilist_node ()
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0 , CompareUsingScalarTypes = 1<<1 }
enum TermOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum OtherOps
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range< op_iterator > op_range
typedef iterator_range< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal , BasicBlockVal , FunctionVal , GlobalAliasVal ,
GlobalVariableVal , UndefValueVal , BlockAddressVal , ConstantExprVal ,
ConstantAggregateZeroVal , ConstantDataArrayVal , ConstantDataVectorVal , ConstantIntVal ,
ConstantFPVal , ConstantArrayVal , ConstantStructVal , ConstantVectorVal ,
ConstantPointerNullVal , MetadataAsValueVal , InlineAsmVal , InstructionVal ,
ConstantFirstVal = FunctionVal , ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl< const User > const_user_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Detailed Description
InvokeInst - Invoke instruction. The SubclassData field is used to hold the calling convention of the call.
Definition at line 2971 of file Instructions.h.
Member Function Documentation
addAttribute()
void InvokeInst::addAttribute (unsigned i, Attribute::AttrKind attr)
addAttribute - adds the attribute to the list of attributes.
Definition at line 594 of file Instructions.cpp.
References llvm::AttributeSet::addAttribute(), getAttributes(), llvm::Value::getContext(), and setAttributes().
Referenced by setCannotDuplicate(), setDoesNotAccessMemory(), setDoesNotReturn(), setDoesNotThrow(), setIsNoInline(), and setOnlyReadsMemory().
arg_operands() [1/2]
iterator_range< op_iterator > llvm::InvokeInst::arg_operands () inline
arg_operands - iteration adapter for range-for loops.
Definition at line 3023 of file Instructions.h.
References llvm::User::op_begin(), and llvm::User::op_end().
arg_operands() [2/2]
iterator_range< const_op_iterator > llvm::InvokeInst::arg_operands () const inline
arg_operands - iteration adapter for range-for loops.
Definition at line 3028 of file Instructions.h.
References llvm::User::op_begin(), and llvm::User::op_end().
cannotDuplicate()
bool llvm::InvokeInst::cannotDuplicate () const inline
Determine if the invoke cannot be duplicated.
Definition at line 3124 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::NoDuplicate.
classof() [1/2]
bool llvm::InvokeInst::classof (const Instruction * I) inline static
Definition at line 3189 of file Instructions.h.
References I.
Referenced by classof().
classof() [2/2]
bool llvm::InvokeInst::classof (const Value * V) inline static
Definition at line 3192 of file Instructions.h.
References llvm::cast(), classof(), and llvm::isa().
clone_impl()
InvokeInst * InvokeInst::clone_impl () const override protected virtual
Implements llvm::Instruction.
Definition at line 3798 of file Instructions.cpp.
References llvm::User::getNumOperands().
Create() [1/2]
InvokeInst * llvm::InvokeInst::Create (Value * Func, BasicBlock * IfNormal, BasicBlock * IfException, ArrayRef< Value * > Args, const Twine & NameStr, BasicBlock * InsertAtEnd) inline static
Definition at line 3001 of file Instructions.h.
References llvm::ArrayRef< T >::size().
Create() [2/2]
InvokeInst * llvm::InvokeInst::Create (Value * Func, BasicBlock * IfNormal, BasicBlock * IfException, ArrayRef< Value * > Args, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) inline static
Definition at line 2993 of file Instructions.h.
References llvm::ArrayRef< T >::size().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateInvoke(), llvm::IRBuilder< true, TargetFolder >::CreateInvoke(), llvm::IRBuilder< true, TargetFolder >::CreateInvoke(), llvm::IRBuilder< true, TargetFolder >::CreateInvoke3(), HandleCallsInBlockInlinedThroughInvoke(), and llvm::InstCombiner::visitAllocSite().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::InvokeInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
doesNotAccessMemory()
bool llvm::InvokeInst::doesNotAccessMemory () const inline
Determine if the call does not access memory.
Definition at line 3096 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::ReadNone.
Referenced by onlyReadsMemory().
doesNotReturn()
bool llvm::InvokeInst::doesNotReturn () const inline
Determine if the call cannot return.
Definition at line 3112 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::NoReturn.
doesNotThrow()
bool llvm::InvokeInst::doesNotThrow () const inline
Determine if the call cannot unwind.
Definition at line 3118 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::NoUnwind.
getArgOperand()
Value * llvm::InvokeInst::getArgOperand (unsigned i) const inline
getArgOperand/setArgOperand - Return/set the i-th invoke argument.
Definition at line 3019 of file Instructions.h.
References llvm::User::getOperand().
getArgOperandUse() [1/2]
Use & llvm::InvokeInst::getArgOperandUse (unsigned i) inline
Definition at line 3034 of file Instructions.h.
References llvm::User::getOperandUse().
getArgOperandUse() [2/2]
const Use & llvm::InvokeInst::getArgOperandUse (unsigned i) const inline
Wrappers for getting the Use of a invoke argument.
Definition at line 3033 of file Instructions.h.
References llvm::User::getOperandUse().
getAttributes()
const AttributeSet & llvm::InvokeInst::getAttributes () const inline
getAttributes - Return the parameter attributes for this invoke.
Definition at line 3047 of file Instructions.h.
Referenced by addAttribute(), changeToCall(), removeAttribute(), and WriteInstruction().
getCalledFunction()
Function * llvm::InvokeInst::getCalledFunction () const inline
getCalledFunction - Return the function called, or null if this is an indirect function invocation.
Definition at line 3144 of file Instructions.h.
References llvm::dyn_cast(), and llvm::User::Op().
Referenced by paramHasAttr().
getCalledValue() [1/2]
Value * llvm::InvokeInst::getCalledValue () inline
Definition at line 3151 of file Instructions.h.
References llvm::User::Op().
getCalledValue() [2/2]
const Value * llvm::InvokeInst::getCalledValue () const inline
getCalledValue - Get a pointer to the function that is invoked by this instruction
Definition at line 3150 of file Instructions.h.
References llvm::User::Op().
Referenced by changeToCall(), and WriteInstruction().
getCallingConv()
CallingConv::ID llvm::InvokeInst::getCallingConv () const inline
getCallingConv/setCallingConv - Get or set the calling convention of this function call.
Definition at line 3038 of file Instructions.h.
References llvm::Instruction::getSubclassDataFromInstruction().
Referenced by changeToCall(), and WriteInstruction().
getDereferenceableBytes()
uint64_t llvm::InvokeInst::getDereferenceableBytes (unsigned i) const inline
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
Definition at line 3076 of file Instructions.h.
getLandingPadInst()
LandingPadInst * InvokeInst::getLandingPadInst () const
getLandingPadInst - Get the landingpad instruction from the landing pad block (the unwind destination).
Definition at line 608 of file Instructions.cpp.
References llvm::cast(), and getUnwindDest().
Referenced by HandleInlinedInvoke().
getNormalDest()
BasicBlock * llvm::InvokeInst::getNormalDest () const inline
Definition at line 3159 of file Instructions.h.
References llvm::cast(), and llvm::User::Op().
Referenced by changeToCall(), llvm::DemoteRegToStack(), llvm::DominatorTree::dominates(), getSuccessor(), llvm::InlineFunction(), and WriteInstruction().
getNumArgOperands()
unsigned llvm::InvokeInst::getNumArgOperands () const inline
getNumArgOperands - Return the number of invoke arguments.
Definition at line 3015 of file Instructions.h.
References llvm::User::getNumOperands().
getNumSuccessors()
unsigned llvm::InvokeInst::getNumSuccessors () const inline
Definition at line 3186 of file Instructions.h.
getParamAlignment()
unsigned llvm::InvokeInst::getParamAlignment (unsigned i) const inline
Extract the alignment for a call or parameter (0=unknown).
Definition at line 3070 of file Instructions.h.
getSuccessor()
BasicBlock * llvm::InvokeInst::getSuccessor (unsigned i) const inline
Definition at line 3176 of file Instructions.h.
References getNormalDest(), and getUnwindDest().
getUnwindDest()
BasicBlock * llvm::InvokeInst::getUnwindDest () const inline
Definition at line 3162 of file Instructions.h.
References llvm::cast(), and llvm::User::Op().
Referenced by changeToCall(), getLandingPadInst(), getSuccessor(), HandleInlinedInvoke(), llvm::InlineFunction(), and WriteInstruction().
hasByValArgument()
bool llvm::InvokeInst::hasByValArgument () const inline
Determine if any call argument is an aggregate passed by value.
Definition at line 3137 of file Instructions.h.
References llvm::Attribute::ByVal.
hasFnAttr()
bool llvm::InvokeInst::hasFnAttr (Attribute::AttrKind A) const inline
Determine whether this call has the given attribute.
Definition at line 3060 of file Instructions.h.
References llvm::Attribute::NoBuiltin.
Referenced by cannotDuplicate(), doesNotAccessMemory(), doesNotReturn(), doesNotThrow(), isNoInline(), and onlyReadsMemory().
hasStructRetAttr()
bool llvm::InvokeInst::hasStructRetAttr () const inline
Determine if the call returns a structure through first pointer argument.
Definition at line 3131 of file Instructions.h.
References paramHasAttr(), and llvm::Attribute::StructRet.
isNoBuiltin()
bool llvm::InvokeInst::isNoBuiltin () const inline
Return true if the call should not be treated as a call to a builtin.
Definition at line 3082 of file Instructions.h.
References llvm::Attribute::Builtin, and llvm::Attribute::NoBuiltin.
isNoInline()
bool llvm::InvokeInst::isNoInline () const inline
Return true if the call should not be inlined.
Definition at line 3090 of file Instructions.h.
References hasFnAttr(), and llvm::Attribute::NoInline.
onlyReadsMemory()
bool llvm::InvokeInst::onlyReadsMemory () const inline
Determine if the call does not access or only reads memory.
Definition at line 3104 of file Instructions.h.
References doesNotAccessMemory(), hasFnAttr(), and llvm::Attribute::ReadOnly.
paramHasAttr()
bool InvokeInst::paramHasAttr (unsigned i, Attribute::AttrKind A) const
Determine whether the call or the callee has the given attributes.
Definition at line 586 of file Instructions.cpp.
References F, and getCalledFunction().
Referenced by hasStructRetAttr().
removeAttribute()
void InvokeInst::removeAttribute (unsigned i, Attribute attr)
removeAttribute - removes the attribute from the list of attributes.
Definition at line 600 of file Instructions.cpp.
References getAttributes(), llvm::Value::getContext(), llvm::AttributeSet::removeAttributes(), and setAttributes().
setArgOperand()
void llvm::InvokeInst::setArgOperand (unsigned i, Value * v) inline
Definition at line 3020 of file Instructions.h.
References llvm::User::setOperand().
setAttributes()
void llvm::InvokeInst::setAttributes (const AttributeSet & Attrs) inline
setAttributes - Set the parameter attributes for this invoke.
Definition at line 3051 of file Instructions.h.
Referenced by addAttribute(), HandleCallsInBlockInlinedThroughInvoke(), and removeAttribute().
setCalledFunction()
void llvm::InvokeInst::setCalledFunction (Value * Fn) inline
setCalledFunction - Set the function called.
Definition at line 3154 of file Instructions.h.
References llvm::User::Op().
setCallingConv()
void llvm::InvokeInst::setCallingConv (CallingConv::ID CC) inline
Definition at line 3041 of file Instructions.h.
Referenced by HandleCallsInBlockInlinedThroughInvoke().
setCannotDuplicate()
void llvm::InvokeInst::setCannotDuplicate () inline
Definition at line 3125 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::NoDuplicate.
setDoesNotAccessMemory()
void llvm::InvokeInst::setDoesNotAccessMemory () inline
Definition at line 3099 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::ReadNone.
setDoesNotReturn()
void llvm::InvokeInst::setDoesNotReturn () inline
Definition at line 3113 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::NoReturn.
setDoesNotThrow()
void llvm::InvokeInst::setDoesNotThrow () inline
Definition at line 3119 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::NoUnwind.
setIsNoInline()
void llvm::InvokeInst::setIsNoInline () inline
Definition at line 3091 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::NoInline.
setNormalDest()
void llvm::InvokeInst::setNormalDest (BasicBlock * B) inline
Definition at line 3165 of file Instructions.h.
References llvm::User::Op().
setOnlyReadsMemory()
void llvm::InvokeInst::setOnlyReadsMemory () inline
Definition at line 3107 of file Instructions.h.
References addAttribute(), llvm::AttributeSet::FunctionIndex, and llvm::Attribute::ReadOnly.
setSuccessor()
void llvm::InvokeInst::setSuccessor (unsigned idx, BasicBlock * NewSucc) inline
Definition at line 3181 of file Instructions.h.
References llvm::User::Op().
setUnwindDest()
void llvm::InvokeInst::setUnwindDest (BasicBlock * B) inline
Definition at line 3168 of file Instructions.h.
References llvm::User::Op().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp