LLVM: llvm::NVPTXFloatMCExpr Class Reference
LLVM API Documentation
llvm::NVPTXFloatMCExpr Class Reference
#include <NVPTXMCExpr.h>
Public Types
enum VariantKind { VK_NVPTX_None , VK_NVPTX_SINGLE_PREC_FLOAT , VK_NVPTX_DOUBLE_PREC_FLOAT }
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary , Constant , SymbolRef , Unary ,
Target
}
Public Member Functions
void PrintImpl (raw_ostream &OS) const override
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
const MCSection * FindAssociatedSection () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Accessors
VariantKind getKind () const
getOpcode - Get the kind of this expression.
APFloat getAPFloat () const
getSubExpr - Get the child of this expression.
Public Member Functions inherited from llvm::MCExpr
ExprKind getKind () const
void print (raw_ostream &OS) const
void dump () const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
bool EvaluateAsAbsolute (int64_t &Res) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
int64_t evaluateKnownAbsolute (const MCAsmLayout &Layout) const
bool EvaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
bool EvaluateAsValue (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
const MCSection * FindAssociatedSection () const
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const NVPTXFloatMCExpr * Create (VariantKind Kind, APFloat Flt, MCContext &Ctx)
static const NVPTXFloatMCExpr * CreateConstantFPSingle (APFloat Flt, MCContext &Ctx)
static const NVPTXFloatMCExpr * CreateConstantFPDouble (APFloat Flt, MCContext &Ctx)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind _Kind)
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet, bool ForceVarExpansion) const
Detailed Description
Definition at line 20 of file NVPTXMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::NVPTXFloatMCExpr::VariantKind
Enumerator
VK_NVPTX_None
VK_NVPTX_SINGLE_PREC_FLOAT
VK_NVPTX_DOUBLE_PREC_FLOAT
Definition at line 22 of file NVPTXMCExpr.h.
Member Function Documentation
classof()
bool llvm::NVPTXFloatMCExpr::classof (const MCExpr * E) inline static
Definition at line 78 of file NVPTXMCExpr.h.
References llvm::MCExpr::getKind(), and llvm::MCExpr::Target.
Create()
const NVPTXFloatMCExpr * NVPTXFloatMCExpr::Create (VariantKind Kind, APFloat Flt, MCContext & Ctx) static
Definition at line 19 of file NVPTXMCExpr.cpp.
Referenced by CreateConstantFPDouble(), and CreateConstantFPSingle().
CreateConstantFPDouble()
const NVPTXFloatMCExpr * llvm::NVPTXFloatMCExpr::CreateConstantFPDouble (APFloat Flt, MCContext & Ctx) inline static
Definition at line 47 of file NVPTXMCExpr.h.
References Create(), and VK_NVPTX_DOUBLE_PREC_FLOAT.
CreateConstantFPSingle()
const NVPTXFloatMCExpr * llvm::NVPTXFloatMCExpr::CreateConstantFPSingle (APFloat Flt, MCContext & Ctx) inline static
Definition at line 42 of file NVPTXMCExpr.h.
References Create(), and VK_NVPTX_SINGLE_PREC_FLOAT.
EvaluateAsRelocatableImpl()
bool llvm::NVPTXFloatMCExpr::EvaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 65 of file NVPTXMCExpr.h.
FindAssociatedSection()
const MCSection * llvm::NVPTXFloatMCExpr::FindAssociatedSection () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 71 of file NVPTXMCExpr.h.
fixELFSymbolsInTLSFixups()
void llvm::NVPTXFloatMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 76 of file NVPTXMCExpr.h.
getAPFloat()
APFloat llvm::NVPTXFloatMCExpr::getAPFloat () const inline
getSubExpr - Get the child of this expression.
Definition at line 60 of file NVPTXMCExpr.h.
Referenced by PrintImpl().
getKind()
VariantKind llvm::NVPTXFloatMCExpr::getKind () const inline
getOpcode - Get the kind of this expression.
Definition at line 57 of file NVPTXMCExpr.h.
PrintImpl()
void NVPTXFloatMCExpr::PrintImpl (raw_ostream & OS) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 23 of file NVPTXMCExpr.cpp.
References llvm::APFloat::bitcastToAPInt(), llvm::APFloat::convert(), getAPFloat(), llvm::APInt::getZExtValue(), llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEsingle, llvm_unreachable, llvm::APFloat::rmNearestTiesToEven, llvm::utohexstr(), VK_NVPTX_DOUBLE_PREC_FLOAT, and VK_NVPTX_SINGLE_PREC_FLOAT.
visitUsedExpr()
void llvm::NVPTXFloatMCExpr::visitUsedExpr (MCStreamer & Streamer) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 70 of file NVPTXMCExpr.h.
The documentation for this class was generated from the following files:
NVPTXMCExpr.h
NVPTXMCExpr.cpp