LLVM: llvm::DIEExpr Class Reference
LLVM API Documentation
llvm::DIEExpr Class Reference
DIEExpr - An expression DIE.
#include <DIE.h>
Public Member Functions
DIEExpr (const MCExpr *E)
void EmitValue (AsmPrinter *AP, dwarf::Form Form) const override
const MCExpr * getValue () const
unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const override
void print (raw_ostream &O) const override
Public Member Functions inherited from llvm::DIEValue
Type getType () const
void dump () const
Static Public Member Functions
static bool classof (const DIEValue *E)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum Type {
isInteger , isString , isExpr , isLabel ,
isDelta , isEntry , isTypeSignature , isBlock ,
isLoc , isLocList
}
Protected Member Functions inherited from llvm::DIEValue
DIEValue (Type T)
virtual ~DIEValue ()
Protected Attributes inherited from llvm::DIEValue
Type Ty
Detailed Description
DIEExpr - An expression DIE.
Definition at line 297 of file DIE.h.
Constructor & Destructor Documentation
DIEExpr()
llvm::DIEExpr::DIEExpr (const MCExpr * E) inline explicit
Definition at line 301 of file DIE.h.
References llvm::DIEValue::DIEValue(), and llvm::DIEValue::isExpr.
Member Function Documentation
classof()
bool llvm::DIEExpr::classof (const DIEValue * E) inline static
Definition at line 316 of file DIE.h.
References llvm::DIEValue::DIEValue(), llvm::DIEValue::getType(), and llvm::DIEValue::isExpr.
EmitValue()
void DIEExpr::EmitValue (AsmPrinter * AP, dwarf::Form Form) const override virtual
EmitValue - Emit expression value.
Implements llvm::DIEValue.
Definition at line 275 of file DIE.cpp.
References llvm::MCStreamer::EmitValue(), llvm::AsmPrinter::OutStreamer, and SizeOf().
getValue()
const MCExpr * llvm::DIEExpr::getValue () const inline
getValue - Get MCExpr.
Definition at line 309 of file DIE.h.
print()
void DIEExpr::print (raw_ostream & O) const override virtual
Implements llvm::DIEValue.
Definition at line 289 of file DIE.cpp.
SizeOf()
unsigned DIEExpr::SizeOf (AsmPrinter * AP, dwarf::Form Form) const override virtual
SizeOf - Determine size of expression value in bytes.
Implements llvm::DIEValue.
Definition at line 281 of file DIE.cpp.
References llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_sec_offset, llvm::dwarf::DW_FORM_strp, llvm::AsmPrinter::getDataLayout(), and llvm::DataLayout::getPointerSize().
Referenced by EmitValue().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp