LLVM: llvm::PrintVRegOrUnit Class Reference
LLVM API Documentation
llvm::PrintVRegOrUnit Class Reference
#include <TargetRegisterInfo.h>
Public Member Functions
PrintVRegOrUnit (unsigned VRegOrUnit, const TargetRegisterInfo *tri)
void print (raw_ostream &) const
Additional Inherited Members
Protected Member Functions inherited from llvm::PrintRegUnit
PrintRegUnit (unsigned unit, const TargetRegisterInfo *tri)
void print (raw_ostream &) const
Protected Attributes inherited from llvm::PrintRegUnit
const TargetRegisterInfo * TRI
unsigned Unit
Detailed Description
PrintVRegOrUnit - It is often convenient to track virtual registers and physical register units in the same list.
Definition at line 975 of file TargetRegisterInfo.h.
Constructor & Destructor Documentation
PrintVRegOrUnit()
llvm::PrintVRegOrUnit::PrintVRegOrUnit (unsigned VRegOrUnit, const TargetRegisterInfo * tri) inline
Definition at line 977 of file TargetRegisterInfo.h.
References llvm::PrintRegUnit::PrintRegUnit().
Member Function Documentation
print()
void PrintVRegOrUnit::print (raw_ostream & OS) const
Definition at line 77 of file TargetRegisterInfo.cpp.
References llvm::PrintRegUnit::print(), llvm::PrintRegUnit::TRI, llvm::PrintRegUnit::Unit, and llvm::TargetRegisterInfo::virtReg2Index().
Referenced by llvm::operator<<().
The documentation for this class was generated from the following files:
TargetRegisterInfo.h
TargetRegisterInfo.cpp