LLVM: llvm::cl::opt_storage< DataType, ExternalStorage, isClass > Class Template Reference
LLVM API Documentation
llvm::cl::opt_storage< DataType, ExternalStorage, isClass > Class Template Reference
#include <CommandLine.h>
Public Member Functions
opt_storage ()
bool setLocation (Option &O, DataType &L)
template<class T>
void setValue (const T &V, bool initial=false)
DataType & getValue ()
const DataType & getValue () const
operator DataType () const
const OptionValue< DataType > & getDefault () const
Detailed Description
template<class DataType, bool ExternalStorage, bool isClass>
class llvm::cl::opt_storage< DataType, ExternalStorage, isClass >
Definition at line 1031 of file CommandLine.h.
Constructor & Destructor Documentation
opt_storage()
template<class DataType, bool ExternalStorage, bool isClass> llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::opt_storage () inline
Definition at line 1042 of file CommandLine.h.
Member Function Documentation
getDefault()
template<class DataType, bool ExternalStorage, bool isClass> const OptionValue< DataType > & llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::getDefault () const inline
Definition at line 1070 of file CommandLine.h.
getValue() [1/2]
template<class DataType, bool ExternalStorage, bool isClass> DataType & llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::getValue () inline
Definition at line 1059 of file CommandLine.h.
Referenced by operator DataType(), and llvm::cl::opt_storage< DataType, false, false >::operator DataType().
getValue() [2/2]
template<class DataType, bool ExternalStorage, bool isClass> const DataType & llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::getValue () const inline
Definition at line 1063 of file CommandLine.h.
operator DataType()
template<class DataType, bool ExternalStorage, bool isClass> llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::operator DataType () const inline
Definition at line 1068 of file CommandLine.h.
References getValue().
setLocation()
template<class DataType, bool ExternalStorage, bool isClass> bool llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::setLocation (Option & O, DataType & L) inline
Definition at line 1044 of file CommandLine.h.
References llvm::cl::Option::error().
setValue()
template<class DataType, bool ExternalStorage, bool isClass> template<class T> void llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::setValue (const T & V, bool initial = false) inline
Definition at line 1052 of file CommandLine.h.
References T.
The documentation for this class was generated from the following file:
CommandLine.h