LLVM: llvm::StructLayout Class Reference
LLVM API Documentation
llvm::StructLayout Class Reference
#include <DataLayout.h>
Public Member Functions
uint64_t getSizeInBytes () const
uint64_t getSizeInBits () const
unsigned getAlignment () const
unsigned getElementContainingOffset (uint64_t Offset) const
Given a valid byte offset into the structure, returns the structure index that contains it.
uint64_t getElementOffset (unsigned Idx) const
uint64_t getElementOffsetInBits (unsigned Idx) const
Friends
class DataLayout
Detailed Description
Used to lazily calculate structure layout information for a target machine, based on the DataLayout structure.
Definition at line 467 of file DataLayout.h.
Member Function Documentation
getAlignment()
unsigned llvm::StructLayout::getAlignment () const inline
Definition at line 477 of file DataLayout.h.
getElementContainingOffset()
unsigned StructLayout::getElementContainingOffset (uint64_t Offset) const
Given a valid byte offset into the structure, returns the structure index that contains it.
getElementContainingOffset - Given a valid offset into the structure, return the structure index that contains it.
Definition at line 79 of file DataLayout.cpp.
Referenced by getNaturalGEPRecursively(), getTypePartition(), LLVMElementAtOffset(), ReadDataFromGlobal(), stripAggregateTypeWrapping(), and SymbolicallyEvaluateGEP().
getElementOffset()
uint64_t llvm::StructLayout::getElementOffset (unsigned Idx) const inline
Definition at line 483 of file DataLayout.h.
Referenced by llvm::GEPOperator::accumulateConstantOffset(), computeKnownBits(), llvm::ComputeValueVTs(), DecomposeGEPExpression(), llvm::EmitGEPOffset(), emitGlobalConstantStruct(), EvaluateGEPOffsetExpression(), getElementOffsetInBits(), llvm::DataLayout::getIndexedOffset(), getNaturalGEPRecursively(), GetOffsetFromIndex(), getTypePartition(), llvm::ExecutionEngine::InitializeMemory(), isGEPKnownNonNull(), LLVMOffsetOfElement(), ReadDataFromGlobal(), SRAGlobal(), and SymbolicallyEvaluateGEP().
getElementOffsetInBits()
uint64_t llvm::StructLayout::getElementOffsetInBits (unsigned Idx) const inline
Definition at line 488 of file DataLayout.h.
References getElementOffset().
Referenced by HasPadding().
getSizeInBits()
uint64_t llvm::StructLayout::getSizeInBits () const inline
Definition at line 475 of file DataLayout.h.
Referenced by llvm::DataLayout::getTypeSizeInBits().
getSizeInBytes()
uint64_t llvm::StructLayout::getSizeInBytes () const inline
Definition at line 473 of file DataLayout.h.
Referenced by computeArraySize(), emitGlobalConstantStruct(), getNaturalGEPRecursively(), getTypePartition(), PerformHeapAllocSRoA(), SymbolicallyEvaluateGEP(), and TryToOptimizeStoreOfMallocToGlobal().
Friends And Related Symbol Documentation
DataLayout
friend class DataLayout friend
Definition at line 493 of file DataLayout.h.
References DataLayout.
Referenced by DataLayout.
The documentation for this class was generated from the following files:
DataLayout.h
DataLayout.cpp