LLVM: llvm::BitcodeReaderValueList Class Reference
LLVM API Documentation
llvm::BitcodeReaderValueList Class Reference
#include <BitcodeReader.h>
Public Member Functions
BitcodeReaderValueList (LLVMContext &C)
~BitcodeReaderValueList ()
unsigned size () const
void resize (unsigned N)
void push_back (Value *V)
void clear ()
Value * operator[] (unsigned i) const
Value * back () const
void pop_back ()
bool empty () const
void shrinkTo (unsigned N)
Constant * getConstantFwdRef (unsigned Idx, Type *Ty)
Value * getValueFwdRef (unsigned Idx, Type *Ty)
void AssignValue (Value *V, unsigned Idx)
void ResolveConstantForwardRefs ()
Detailed Description
Definition at line 40 of file BitcodeReader.h.
Constructor & Destructor Documentation
BitcodeReaderValueList()
llvm::BitcodeReaderValueList::BitcodeReaderValueList (LLVMContext & C) inline
Definition at line 54 of file BitcodeReader.h.
~BitcodeReaderValueList()
llvm::BitcodeReaderValueList::~BitcodeReaderValueList () inline
Definition at line 55 of file BitcodeReader.h.
Member Function Documentation
AssignValue()
void BitcodeReaderValueList::AssignValue (Value * V, unsigned Idx)
Definition at line 367 of file BitcodeReader.cpp.
References llvm::dyn_cast(), push_back(), resize(), and size().
back()
Value * llvm::BitcodeReaderValueList::back () const inline
Definition at line 76 of file BitcodeReader.h.
clear()
void llvm::BitcodeReaderValueList::clear () inline
Definition at line 66 of file BitcodeReader.h.
empty()
bool llvm::BitcodeReaderValueList::empty () const inline
Definition at line 78 of file BitcodeReader.h.
getConstantFwdRef()
Constant * BitcodeReaderValueList::getConstantFwdRef (unsigned Idx, Type * Ty)
Definition at line 396 of file BitcodeReader.cpp.
References llvm::cast(), resize(), and size().
getValueFwdRef()
Value * BitcodeReaderValueList::getValueFwdRef (unsigned Idx, Type * Ty)
Definition at line 412 of file BitcodeReader.cpp.
References resize(), and size().
operator[]()
Value * llvm::BitcodeReaderValueList::operator[] (unsigned i) const inline
Definition at line 71 of file BitcodeReader.h.
Referenced by ResolveConstantForwardRefs().
pop_back()
void llvm::BitcodeReaderValueList::pop_back () inline
Definition at line 77 of file BitcodeReader.h.
push_back()
void llvm::BitcodeReaderValueList::push_back (Value * V) inline
Definition at line 62 of file BitcodeReader.h.
Referenced by AssignValue().
resize()
void llvm::BitcodeReaderValueList::resize (unsigned N) inline
Definition at line 61 of file BitcodeReader.h.
References N.
Referenced by AssignValue(), getConstantFwdRef(), and getValueFwdRef().
ResolveConstantForwardRefs()
void BitcodeReaderValueList::ResolveConstantForwardRefs ()
ResolveConstantForwardRefs - Once all constants are read, this method bulk resolves any forward references.
ResolveConstantForwardRefs - Once all constants are read, this method bulk resolves any forward references. The idea behind this is that we sometimes get constants (such as large arrays) which reference many forward ref constants. Replacing each of these causes a lot of thrashing when building/reuniquing the constant. Instead of doing this, we look at all the uses and rewrite all the place holders at once for any constant that uses a placeholder.
Definition at line 437 of file BitcodeReader.cpp.
References llvm::cast(), llvm::SmallVectorImpl< T >::clear(), llvm::Constant::destroyConstant(), llvm::dyn_cast(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), I, llvm::isa(), llvm::User::op_begin(), llvm::User::op_end(), operator[](), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::Value::use_empty(), and llvm::Value::user_begin().
shrinkTo()
void llvm::BitcodeReaderValueList::shrinkTo (unsigned N) inline
Definition at line 79 of file BitcodeReader.h.
References N, and size().
size()
unsigned llvm::BitcodeReaderValueList::size () const inline
Definition at line 60 of file BitcodeReader.h.
Referenced by AssignValue(), getConstantFwdRef(), getValueFwdRef(), and shrinkTo().
The documentation for this class was generated from the following files:
BitcodeReader.h
BitcodeReader.cpp