LLVM: llvm::PBQP::Graph< SolverT >::NodeItr Class Reference
LLVM API Documentation
llvm::PBQP::Graph< SolverT >::NodeItr Class Reference
#include <Graph.h>
Public Types
typedef std::forward_iterator_tag iterator_category
typedef NodeId value_type
typedef int difference_type
typedef NodeId * pointer
typedef NodeId & reference
Public Member Functions
NodeItr (NodeId CurNId, const Graph &G)
bool operator== (const NodeItr &O) const
bool operator!= (const NodeItr &O) const
NodeItr & operator++ ()
NodeId operator* () const
Detailed Description
template<typename SolverT>
class llvm::PBQP::Graph< SolverT >::NodeItr
Definition at line 245 of file Graph.h.
Member Typedef Documentation
difference_type
template<typename SolverT> typedef int llvm::PBQP::Graph< SolverT >::NodeItr::difference_type
Definition at line 249 of file Graph.h.
iterator_category
template<typename SolverT> typedef std::forward_iterator_tag llvm::PBQP::Graph< SolverT >::NodeItr::iterator_category
Definition at line 247 of file Graph.h.
pointer
template<typename SolverT> typedef NodeId* llvm::PBQP::Graph< SolverT >::NodeItr::pointer
Definition at line 250 of file Graph.h.
reference
template<typename SolverT> typedef NodeId& llvm::PBQP::Graph< SolverT >::NodeItr::reference
Definition at line 251 of file Graph.h.
value_type
template<typename SolverT> typedef NodeId llvm::PBQP::Graph< SolverT >::NodeItr::value_type
Definition at line 248 of file Graph.h.
Constructor & Destructor Documentation
NodeItr()
template<typename SolverT> llvm::PBQP::Graph< SolverT >::NodeItr::NodeItr (NodeId CurNId, const Graph & G) inline
Definition at line 253 of file Graph.h.
References G.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
operator!=()
template<typename SolverT> bool llvm::PBQP::Graph< SolverT >::NodeItr::operator!= (const NodeItr & O) const inline
Definition at line 259 of file Graph.h.
References NodeItr().
operator*()
template<typename SolverT> NodeId llvm::PBQP::Graph< SolverT >::NodeItr::operator* () const inline
Definition at line 261 of file Graph.h.
operator++()
template<typename SolverT> NodeItr & llvm::PBQP::Graph< SolverT >::NodeItr::operator++ () inline
Definition at line 260 of file Graph.h.
References NodeItr().
operator==()
template<typename SolverT> bool llvm::PBQP::Graph< SolverT >::NodeItr::operator== (const NodeItr & O) const inline
Definition at line 258 of file Graph.h.
References NodeItr().
The documentation for this class was generated from the following file:
Graph.h