LLVM: llvm::DwarfCompileUnit Class Reference
LLVM API Documentation
llvm::DwarfCompileUnit Class Reference
#include <DwarfCompileUnit.h>
Public Member Functions
DwarfCompileUnit (unsigned UID, DICompileUnit Node, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU)
DwarfCompileUnit * getSkeleton () const
void initStmtList (MCSymbol *DwarfLineSectionSym)
void applyStmtList (DIE &D)
Apply the DW_AT_stmt_list from this compile unit to the specified DIE.
DIE * getOrCreateGlobalVariableDIE (DIGlobalVariable GV)
getOrCreateGlobalVariableDIE - get or create global variable DIE.
void addLabelAddress (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label)
void addLocalLabelAddress (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label)
void addSectionDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
addSectionDelta - Add a label delta attribute data and value.
DwarfCompileUnit & getCU () override
unsigned getOrCreateSourceID (StringRef FileName, StringRef DirName) override
void addRange (RangeSpan Range)
addRange - Add an address range to the list of ranges for this unit.
void attachLowHighPC (DIE &D, const MCSymbol *Begin, const MCSymbol *End)
void addSectionLabel (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Label, const MCSymbol *Sec)
DIE & updateSubprogramScopeDIE (DISubprogram SP)
Find DIE for the given subprogram and attach appropriate DW_AT_low_pc and DW_AT_high_pc attributes. If there are global variables in this scope then create and insert DIEs for these variables.
void constructScopeDIE (LexicalScope *Scope, SmallVectorImpl< std::unique_ptr< DIE > > &FinalChildren)
void addScopeRangeList (DIE &ScopeDIE, SmallVector< RangeSpan, 2 > Range)
A helper function to construct a RangeSpanList for a given lexical scope.
void attachRangesOrLowHighPC (DIE &D, SmallVector< RangeSpan, 2 > Ranges)
void attachRangesOrLowHighPC (DIE &D, const SmallVectorImpl< InsnRange > &Ranges)
std::unique_ptr< DIE > constructInlinedScopeDIE (LexicalScope *Scope)
This scope represents inlined body of a function. Construct DIE to represent this concrete inlined copy of the function.
std::unique_ptr< DIE > constructLexicalScopeDIE (LexicalScope *Scope)
Construct new DW_TAG_lexical_block for this scope and attach DW_AT_low_pc/DW_AT_high_pc labels.
std::unique_ptr< DIE > constructVariableDIE (DbgVariable &DV, bool Abstract=false)
constructVariableDIE - Construct a DIE for the given DbgVariable.
std::unique_ptr< DIE > constructVariableDIE (DbgVariable &DV, const LexicalScope &Scope, DIE *&ObjectPointer)
DIE * createScopeChildrenDIE (LexicalScope *Scope, SmallVectorImpl< std::unique_ptr< DIE > > &Children, unsigned *ChildScopeCount=nullptr)
A helper function to create children of a Scope DIE.
void constructSubprogramScopeDIE (LexicalScope *Scope)
Construct a DIE for this subprogram scope.
DIE * createAndAddScopeChildren (LexicalScope *Scope, DIE &ScopeDIE)
void constructAbstractSubprogramScopeDIE (LexicalScope *Scope)
std::unique_ptr< DIE > constructImportedEntityDIE (const DIImportedEntity &Module)
Construct import_module DIE.
void finishSubprogramDefinition (DISubprogram SP)
void collectDeadVariables (DISubprogram SP)
void setSkeleton (DwarfCompileUnit &Skel)
Set the skeleton unit associated with this unit.
MCSymbol * getSectionSym () const
void initSection (const MCSection *Section, MCSymbol *SectionSym)
unsigned getLength ()
void emitHeader (const MCSymbol *ASectionSym) const override
Emit the header for this unit, not including the initial length field.
MCSymbol * getLabelBegin () const
void addGlobalName (StringRef Name, DIE &Die, DIScope Context) override
Add a new global name to the compile unit.
void addGlobalType (DIType Ty, const DIE &Die, DIScope Context) override
Add a new global type to the compile unit.
const StringMap< const DIE * > & getGlobalNames () const
const StringMap< const DIE * > & getGlobalTypes () const
void addVariableAddress (const DbgVariable &DV, DIE &Die, MachineLocation Location)
void addAddress (DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location, bool Indirect=false)
Add an address attribute to a die based on the location provided.
void addComplexAddress (const DbgVariable &DV, DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
void addLocationList (DIE &Die, dwarf::Attribute Attribute, unsigned Index)
Add a Dwarf loclistptr attribute data and value.
void applyVariableAttributes (const DbgVariable &Var, DIE &VariableDie)
void addExpr (DIELoc &Die, dwarf::Form Form, const MCExpr *Expr)
Add a Dwarf expression attribute data and value.
void applySubprogramAttributesToDefinition (DISubprogram SP, DIE &SPDie)
const SmallVectorImpl< RangeSpanList > & getRangeLists () const
getRangeLists - Get the vector of range lists.
const SmallVectorImpl< RangeSpan > & getRanges () const
getRanges - Get the list of ranges for this unit.
SmallVector< RangeSpan, 2 > takeRanges ()
void setBaseAddress (const MCSymbol *Base)
const MCSymbol * getBaseAddress () const
Public Member Functions inherited from llvm::DwarfUnit
virtual ~DwarfUnit ()
~Unit - Destructor for compile unit.
const MCSection * getSection () const
AsmPrinter * getAsmPrinter () const
unsigned getUniqueID () const
uint16_t getLanguage () const
DICompileUnit getCUNode () const
DIE & getUnitDie ()
unsigned getDebugInfoOffset () const
void setDebugInfoOffset (unsigned DbgInfoOff)
bool hasContent () const
hasContent - Return true if this compile unit has something to write out.
std::string getParentContextString (DIScope Context) const
void addAccelNamespace (StringRef Name, const DIE &Die)
addAccelNamespace - Add a new name to the namespace accelerator table.
DIE * getDIE (DIDescriptor D) const
DIELoc * getDIELoc ()
getDIELoc - Returns a fresh newly allocated DIELoc.
void insertDIE (DIDescriptor Desc, DIE *D)
void addFlag (DIE &Die, dwarf::Attribute Attribute)
addFlag - Add a flag that is true to the DIE.
void addUInt (DIE &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, uint64_t Integer)
addUInt - Add an unsigned integer attribute data and value.
void addUInt (DIE &Block, dwarf::Form Form, uint64_t Integer)
void addSInt (DIE &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, int64_t Integer)
addSInt - Add an signed integer attribute data and value.
void addSInt (DIELoc &Die, Optional< dwarf::Form > Form, int64_t Integer)
void addString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
addString - Add a string attribute data and value.
void addLabel (DIE &Die, dwarf::Attribute Attribute, dwarf::Form Form, const MCSymbol *Label)
addLabel - Add a Dwarf label attribute data and value.
void addLabel (DIELoc &Die, dwarf::Form Form, const MCSymbol *Label)
void addSectionOffset (DIE &Die, dwarf::Attribute Attribute, uint64_t Integer)
void addOpAddress (DIELoc &Die, const MCSymbol *Label)
void addLabelDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
addLabelDelta - Add a label delta attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIE &Entry)
addDIEEntry - Add a DIE attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIEEntry *Entry)
addDIEEntry - Add a DIE attribute data and value.
void addDIETypeSignature (DIE &Die, const DwarfTypeUnit &Type)
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIELoc *Block)
addBlock - Add block data.
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIEBlock *Block)
addBlock - Add block data.
void addSourceLine (DIE &Die, unsigned Line, StringRef File, StringRef Directory)
void addSourceLine (DIE &Die, DIVariable V)
void addSourceLine (DIE &Die, DIGlobalVariable G)
void addSourceLine (DIE &Die, DISubprogram SP)
void addSourceLine (DIE &Die, DIType Ty)
void addSourceLine (DIE &Die, DINameSpace NS)
void addSourceLine (DIE &Die, DIObjCProperty Ty)
void addConstantValue (DIE &Die, const MachineOperand &MO, DIType Ty)
addConstantValue - Add constant value entry in variable DIE.
void addConstantValue (DIE &Die, const ConstantInt *CI, DIType Ty)
addConstantValue - Add constant value entry in variable DIE.
void addConstantValue (DIE &Die, const APInt &Val, DIType Ty)
void addConstantValue (DIE &Die, const APInt &Val, bool Unsigned)
void addConstantValue (DIE &Die, bool Unsigned, uint64_t Val)
void addConstantFPValue (DIE &Die, const MachineOperand &MO)
addConstantFPValue - Add constant value entry in variable DIE.
void addConstantFPValue (DIE &Die, const ConstantFP *CFP)
addConstantFPValue - Add constant value entry in variable DIE.
void addTemplateParams (DIE &Buffer, DIArray TParams)
addTemplateParams - Add template parameters in buffer.
bool addRegisterOpPiece (DIELoc &TheDie, unsigned Reg, unsigned SizeInBits=0, unsigned OffsetInBits=0)
Add register operand.
bool addRegisterOffset (DIELoc &TheDie, unsigned Reg, int64_t Offset)
Add register offset.
void addBlockByrefAddress (const DbgVariable &DV, DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
void addType (DIE &Entity, DIType Ty, dwarf::Attribute Attribute=dwarf::DW_AT_type)
addType - Add a new type attribute to the specified entity.
DIE * getOrCreateNameSpace (DINameSpace NS)
getOrCreateNameSpace - Create a DIE for DINameSpace.
DIE * getOrCreateSubprogramDIE (DISubprogram SP, bool Minimal=false)
getOrCreateSubprogramDIE - Create new DIE using SP.
void applySubprogramAttributes (DISubprogram SP, DIE &SPDie, bool Minimal=false)
DIE * getOrCreateTypeDIE (const MDNode *N)
DIE * createTypeDIE (DICompositeType Ty)
getOrCreateContextDIE - Get context owner's DIE.
DIE * getOrCreateContextDIE (DIScope Context)
getOrCreateContextDIE - Get context owner's DIE.
void constructContainingTypeDIEs ()
void constructSubprogramArguments (DIE &Buffer, DITypeArray Args)
constructSubprogramArguments - Construct function argument DIEs.
DIE & createAndAddDIE (unsigned Tag, DIE &Parent, DIDescriptor N=DIDescriptor())
virtual unsigned getHeaderSize () const
void constructTypeDIE (DIE &Buffer, DICompositeType CTy)
constructTypeDIE - Construct type DIE from DICompositeType.
Additional Inherited Members
Protected Member Functions inherited from llvm::DwarfUnit
DwarfUnit (unsigned UID, dwarf::Tag, DICompileUnit CU, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU)
Unit - Unit constructor.
void initSection (const MCSection *Section)
void addLocalString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
Add a string attribute data and value.
void addIndexedString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
bool applySubprogramDefinitionAttributes (DISubprogram SP, DIE &SPDie)
DIE * getOrCreateStaticMemberDIE (DIDerivedType DT)
getOrCreateStaticMemberDIE - Create new static data member DIE.
template<typename T>
T resolve (DIRef< T > Ref) const
Protected Attributes inherited from llvm::DwarfUnit
unsigned UniqueID
UniqueID - a numeric ID unique among all CUs in the module.
DICompileUnit CUNode
Node - MDNode for the compile unit.
DIE UnitDie
Unit debug information entry.
unsigned DebugInfoOffset
Offset of the UnitDie from beginning of debug info section.
AsmPrinter * Asm
Asm - Target of Dwarf emission.
DwarfDebug * DD
DwarfFile * DU
DIE * IndexTyDie
IndexTyDie - An anonymous type for index type. Owned by UnitDie.
DenseMap< const MDNode *, DIE * > MDNodeToDieMap
DenseMap< const MDNode *, DIEEntry * > MDNodeToDIEEntryMap
std::vector< DIEBlock * > DIEBlocks
DIEBlocks - A list of all the DIEBlocks in use.
std::vector< DIELoc * > DIELocs
DIELocs - A list of all the DIELocs in use.
DenseMap< DIE *, const MDNode * > ContainingTypeMap
BumpPtrAllocator DIEValueAllocator
DIEInteger * DIEIntegerOne
const MCSection * Section
The section this unit will be emitted in.
Detailed Description
Definition at line 31 of file DwarfCompileUnit.h.
Constructor & Destructor Documentation
DwarfCompileUnit()
llvm::DwarfCompileUnit::DwarfCompileUnit (unsigned UID, DICompileUnit Node, AsmPrinter * A, DwarfDebug * DW, DwarfFile * DWU)
Definition at line 18 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DwarfUnit(), llvm::DwarfUnit::getUnitDie(), and llvm::DwarfUnit::insertDIE().
Referenced by getCU(), getSkeleton(), and setSkeleton().
Member Function Documentation
addAddress()
void llvm::DwarfCompileUnit::addAddress (DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location, bool Indirect = false)
Add an address attribute to a die based on the location provided.
Definition at line 745 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addBlock(), llvm::DwarfUnit::addRegisterOffset(), llvm::DwarfUnit::addRegisterOpPiece(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::DIEValueAllocator, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_OP_deref, llvm::MachineLocation::getOffset(), llvm::MachineLocation::getReg(), and llvm::MachineLocation::isReg().
Referenced by addVariableAddress(), and updateSubprogramScopeDIE().
addComplexAddress()
void llvm::DwarfCompileUnit::addComplexAddress (const DbgVariable & DV, DIE & Die, dwarf::Attribute Attribute, const MachineLocation & Location)
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable (navigating the extra location information encoded in the type) based on the starting location. Add the DWARF information to the die.
Start with the address based on the location provided, and generate the DWARF information necessary to find the actual variable given the extra address information encoded in the DbgVariable, starting from the starting location. Add the DWARF information to the die.
Definition at line 770 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addBlock(), llvm::DwarfExpression::AddExpression(), llvm::DwarfExpression::AddMachineRegExpression(), llvm::DwarfExpression::AddMachineRegIndirect(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DIEValueAllocator, llvm::dwarf::DW_OP_deref, llvm::DIEDwarfExpression::EmitOp(), llvm::DbgVariable::getExpression(), llvm::MachineLocation::getOffset(), llvm::MachineLocation::getReg(), llvm::DbgVariable::getVariable(), and llvm::DIVariable::isIndirect().
Referenced by addVariableAddress().
addExpr()
void llvm::DwarfCompileUnit::addExpr (DIELoc & Die, dwarf::Form Form, const MCExpr * Expr)
Add a Dwarf expression attribute data and value.
Definition at line 814 of file DwarfCompileUnit.cpp.
References llvm::DIE::addValue(), and llvm::DwarfUnit::DIEValueAllocator.
Referenced by getOrCreateGlobalVariableDIE().
addGlobalName()
void llvm::DwarfCompileUnit::addGlobalName (StringRef Name, DIE & Die, DIScope Context) override virtual
Add a new global name to the compile unit.
addGlobalName - Add a new global name to the compile unit.
Reimplemented from llvm::DwarfUnit.
Definition at line 714 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::getParentContextString(), and Name.
Referenced by applySubprogramAttributesToDefinition(), and getOrCreateGlobalVariableDIE().
addGlobalType()
void llvm::DwarfCompileUnit::addGlobalType (DIType Ty, const DIE & Die, DIScope Context) override virtual
Add a new global type to the compile unit.
Add a new global type to the unit.
Reimplemented from llvm::DwarfUnit.
Definition at line 723 of file DwarfCompileUnit.cpp.
References llvm::DIType::getName(), llvm::DwarfUnit::getParentContextString(), and llvm::StringRef::str().
addLabelAddress()
void llvm::DwarfCompileUnit::addLabelAddress (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label)
addLabelAddress - Add a dwarf label attribute data and value using either DW_FORM_addr or DW_FORM_GNU_addr_index.
addLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr or DW_FORM_GNU_addr_index.
Definition at line 29 of file DwarfCompileUnit.cpp.
References addLocalLabelAddress(), llvm::DIE::addValue(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, and llvm::dwarf::DW_FORM_GNU_addr_index.
Referenced by attachLowHighPC().
addLocalLabelAddress()
void llvm::DwarfCompileUnit::addLocalLabelAddress (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label)
addLocalLabelAddress - Add a dwarf label attribute data and value using DW_FORM_addr only.
Definition at line 48 of file DwarfCompileUnit.cpp.
References llvm::DIE::addValue(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, and llvm::dwarf::DW_FORM_addr.
Referenced by addLabelAddress().
addLocationList()
void llvm::DwarfCompileUnit::addLocationList (DIE & Die, dwarf::Attribute Attribute, unsigned Index)
Add a Dwarf loclistptr attribute data and value.
Definition at line 794 of file DwarfCompileUnit.cpp.
References llvm::DIE::addValue(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::dwarf::DW_FORM_data4, and llvm::dwarf::DW_FORM_sec_offset.
addRange()
void llvm::DwarfCompileUnit::addRange (RangeSpan Range)
addRange - Add an address range to the list of ranges for this unit.
Definition at line 217 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::DD, llvm::RangeSpan::getEnd(), and llvm::MCSymbol::getSection().
Referenced by llvm::DwarfDebug::endFunction().
addScopeRangeList()
void llvm::DwarfCompileUnit::addScopeRangeList (DIE & ScopeDIE, SmallVector< RangeSpan, 2 > Range)
A helper function to construct a RangeSpanList for a given lexical scope.
Definition at line 380 of file DwarfCompileUnit.cpp.
References addSectionDelta(), addSectionLabel(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DD, and llvm::dwarf::DW_AT_ranges.
Referenced by attachRangesOrLowHighPC().
addSectionDelta()
void llvm::DwarfCompileUnit::addSectionDelta (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Hi, const MCSymbol * Lo)
addSectionDelta - Add a label delta attribute data and value.
Definition at line 372 of file DwarfCompileUnit.cpp.
References llvm::DIE::addValue(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::dwarf::DW_FORM_data4, and llvm::dwarf::DW_FORM_sec_offset.
Referenced by addScopeRangeList(), and addSectionLabel().
addSectionLabel()
void llvm::DwarfCompileUnit::addSectionLabel (DIE & Die, dwarf::Attribute Attribute, const MCSymbol * Label, const MCSymbol * Sec)
addSectionLabel - Add a Dwarf section label attribute data and value.
Definition at line 234 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addLabel(), addSectionDelta(), llvm::DwarfUnit::Asm, llvm::DwarfUnit::DD, llvm::dwarf::DW_FORM_data4, and llvm::dwarf::DW_FORM_sec_offset.
Referenced by addScopeRangeList(), and initStmtList().
addVariableAddress()
void llvm::DwarfCompileUnit::addVariableAddress (const DbgVariable & DV, DIE & Die, MachineLocation Location)
Add DW_AT_location attribute for a DbgVariable based on provided MachineLocation.
addVariableAddress - Add DW_AT_location attribute for a DbgVariable based on provided MachineLocation.
Definition at line 733 of file DwarfCompileUnit.cpp.
References addAddress(), llvm::DwarfUnit::addBlockByrefAddress(), addComplexAddress(), llvm::dwarf::DW_AT_location, llvm::DbgVariable::getVariable(), llvm::DbgVariable::isBlockByrefVariable(), llvm::DIVariable::isIndirect(), and llvm::DbgVariable::variableHasComplexAddress().
applyStmtList()
void llvm::DwarfCompileUnit::applyStmtList (DIE & D)
Apply the DW_AT_stmt_list from this compile unit to the specified DIE.
Definition at line 262 of file DwarfCompileUnit.cpp.
References llvm::DIE::addValue(), llvm::dwarf::DW_AT_stmt_list, and llvm::DwarfUnit::UnitDie.
applySubprogramAttributesToDefinition()
void llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition (DISubprogram SP, DIE & SPDie)
Definition at line 820 of file DwarfCompileUnit.cpp.
References addGlobalName(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DISubprogram::getContext(), llvm::DISubprogram::getFunctionDeclaration(), and llvm::DwarfUnit::resolve().
Referenced by constructAbstractSubprogramScopeDIE(), and finishSubprogramDefinition().
applyVariableAttributes()
void llvm::DwarfCompileUnit::applyVariableAttributes (const DbgVariable & Var, DIE & VariableDie)
Definition at line 802 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addFlag(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addType(), llvm::dwarf::DW_AT_artificial, llvm::dwarf::DW_AT_name, llvm::DbgVariable::getName(), llvm::DbgVariable::getType(), llvm::DbgVariable::getVariable(), llvm::DbgVariable::isArtificial(), and Name.
Referenced by collectDeadVariables().
attachLowHighPC()
void llvm::DwarfCompileUnit::attachLowHighPC (DIE & D, const MCSymbol * Begin, const MCSymbol * End)
Definition at line 268 of file DwarfCompileUnit.cpp.
References addLabelAddress(), llvm::DwarfUnit::addLabelDelta(), llvm::DwarfUnit::DD, llvm::dwarf::DW_AT_high_pc, llvm::dwarf::DW_AT_low_pc, and llvm::MCSymbol::isDefined().
Referenced by attachRangesOrLowHighPC(), and updateSubprogramScopeDIE().
attachRangesOrLowHighPC() [1/2]
void llvm::DwarfCompileUnit::attachRangesOrLowHighPC (DIE & D, const SmallVectorImpl< InsnRange > & Ranges)
Definition at line 412 of file DwarfCompileUnit.cpp.
References attachRangesOrLowHighPC(), llvm::DwarfUnit::DD, and Ranges.
attachRangesOrLowHighPC() [2/2]
void llvm::DwarfCompileUnit::attachRangesOrLowHighPC (DIE & D, SmallVector< RangeSpan, 2 > Ranges)
Definition at line 403 of file DwarfCompileUnit.cpp.
References addScopeRangeList(), attachLowHighPC(), and Ranges.
Referenced by attachRangesOrLowHighPC(), constructInlinedScopeDIE(), and constructLexicalScopeDIE().
collectDeadVariables()
void llvm::DwarfCompileUnit::collectDeadVariables (DISubprogram SP)
Definition at line 683 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), applyVariableAttributes(), constructVariableDIE(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DU, llvm::DwarfUnit::getDIE(), llvm::DITypedArray< T >::getElement(), llvm::DITypedArray< T >::getNumElements(), and llvm::DIDescriptor::isVariable().
constructAbstractSubprogramScopeDIE()
void llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE (LexicalScope * Scope)
Definition at line 603 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addUInt(), applySubprogramAttributesToDefinition(), llvm::DwarfUnit::createAndAddDIE(), createAndAddScopeChildren(), llvm::DwarfUnit::DU, llvm::dwarf::DW_AT_inline, llvm::dwarf::DW_AT_object_pointer, llvm::dwarf::DW_INL_inlined, llvm::dwarf::DW_TAG_subprogram, llvm::DISubprogram::getFunctionDeclaration(), llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::LexicalScope::getScopeNode(), llvm::DwarfUnit::getUnitDie(), llvm::None, and llvm::DwarfUnit::resolve().
constructImportedEntityDIE()
std::unique_ptr< DIE > llvm::DwarfCompileUnit::constructImportedEntityDIE (const DIImportedEntity & Module)
Construct import_module DIE.
Definition at line 637 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::dwarf::DW_AT_import, llvm::dwarf::DW_AT_name, llvm::Module::getContext(), llvm::DwarfUnit::getDIE(), llvm::Module::getName(), getOrCreateGlobalVariableDIE(), llvm::DwarfUnit::getOrCreateNameSpace(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DwarfUnit::insertDIE(), llvm::DIDescriptor::isGlobalVariable(), llvm::DIDescriptor::isNameSpace(), llvm::DIDescriptor::isSubprogram(), llvm::DIDescriptor::isType(), llvm::make_unique(), Name, and llvm::DwarfUnit::resolve().
Referenced by constructScopeDIE().
constructInlinedScopeDIE()
std::unique_ptr< DIE > llvm::DwarfCompileUnit::constructInlinedScopeDIE (LexicalScope * Scope)
This scope represents inlined body of a function. Construct DIE to represent this concrete inlined copy of the function.
Definition at line 425 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), llvm::DwarfUnit::addUInt(), attachRangesOrLowHighPC(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DU, llvm::dwarf::DW_AT_abstract_origin, llvm::dwarf::DW_AT_call_file, llvm::dwarf::DW_AT_call_line, llvm::dwarf::DW_TAG_inlined_subroutine, llvm::DILocation::getDirectory(), llvm::getDISubprogram(), llvm::DILocation::getFilename(), llvm::LexicalScope::getInlinedAt(), llvm::DILocation::getLineNumber(), getOrCreateSourceID(), llvm::LexicalScope::getRanges(), llvm::LexicalScope::getScopeNode(), llvm::make_unique(), and llvm::None.
Referenced by constructScopeDIE().
constructLexicalScopeDIE()
std::unique_ptr< DIE > llvm::DwarfCompileUnit::constructLexicalScopeDIE (LexicalScope * Scope)
Construct new DW_TAG_lexical_block for this scope and attach DW_AT_low_pc/DW_AT_high_pc labels.
Definition at line 455 of file DwarfCompileUnit.cpp.
References attachRangesOrLowHighPC(), llvm::DwarfUnit::DD, llvm::dwarf::DW_TAG_lexical_block, llvm::LexicalScope::getRanges(), llvm::LexicalScope::isAbstractScope(), and llvm::make_unique().
Referenced by constructScopeDIE().
constructScopeDIE()
void llvm::DwarfCompileUnit::constructScopeDIE (LexicalScope * Scope, SmallVectorImpl< std::unique_ptr< DIE > > & FinalChildren)
Definition at line 310 of file DwarfCompileUnit.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), constructImportedEntityDIE(), constructInlinedScopeDIE(), constructLexicalScopeDIE(), createScopeChildrenDIE(), llvm::DwarfUnit::DD, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::LexicalScope::getInlinedAt(), llvm::LexicalScope::getParent(), llvm::LexicalScope::getScopeNode(), I, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by createScopeChildrenDIE().
constructSubprogramScopeDIE()
void llvm::DwarfCompileUnit::constructSubprogramScopeDIE (LexicalScope * Scope)
Construct a DIE for this subprogram scope.
Definition at line 559 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), llvm::DwarfUnit::addDIEEntry(), createAndAddScopeChildren(), llvm::DwarfUnit::DD, llvm::dwarf::DW_AT_object_pointer, llvm::dwarf::DW_TAG_unspecified_parameters, llvm::DITypedArray< T >::getElement(), llvm::LexicalScope::getInlinedAt(), llvm::DITypedArray< T >::getNumElements(), llvm::LexicalScope::getScopeNode(), llvm::LexicalScope::isAbstractScope(), llvm::make_unique(), llvm::Sub, and updateSubprogramScopeDIE().
Referenced by llvm::DwarfDebug::endFunction().
constructVariableDIE() [1/2]
std::unique_ptr< DIE > llvm::DwarfCompileUnit::constructVariableDIE (DbgVariable & DV, bool Abstract = false)
constructVariableDIE - Construct a DIE for the given DbgVariable.
Definition at line 469 of file DwarfCompileUnit.cpp.
References llvm::DbgVariable::setDIE().
Referenced by collectDeadVariables(), constructVariableDIE(), and createScopeChildrenDIE().
constructVariableDIE() [2/2]
std::unique_ptr< DIE > llvm::DwarfCompileUnit::constructVariableDIE (DbgVariable & DV, const LexicalScope & Scope, DIE *& ObjectPointer)
Definition at line 532 of file DwarfCompileUnit.cpp.
References constructVariableDIE(), llvm::LexicalScope::isAbstractScope(), and llvm::DbgVariable::isObjectPointer().
createAndAddScopeChildren()
DIE * llvm::DwarfCompileUnit::createAndAddScopeChildren (LexicalScope * Scope, DIE & ScopeDIE)
Definition at line 589 of file DwarfCompileUnit.cpp.
References llvm::DIE::addChild(), createScopeChildrenDIE(), and I.
Referenced by constructAbstractSubprogramScopeDIE(), and constructSubprogramScopeDIE().
createScopeChildrenDIE()
DIE * llvm::DwarfCompileUnit::createScopeChildrenDIE (LexicalScope * Scope, SmallVectorImpl< std::unique_ptr< DIE > > & Children, unsigned * ChildScopeCount = nullptr)
A helper function to create children of a Scope DIE.
Definition at line 540 of file DwarfCompileUnit.cpp.
References constructScopeDIE(), constructVariableDIE(), llvm::DwarfUnit::DU, and llvm::LexicalScope::getChildren().
Referenced by constructScopeDIE(), and createAndAddScopeChildren().
emitHeader()
void llvm::DwarfCompileUnit::emitHeader (const MCSymbol * ASectionSym) const override virtual
Emit the header for this unit, not including the initial length field.
Reimplemented from llvm::DwarfUnit.
Definition at line 705 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::Asm, and llvm::DwarfUnit::emitHeader().
finishSubprogramDefinition()
void llvm::DwarfCompileUnit::finishSubprogramDefinition (DISubprogram SP)
Definition at line 666 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addDIEEntry(), applySubprogramAttributesToDefinition(), llvm::DwarfUnit::DU, llvm::dwarf::DW_AT_abstract_origin, llvm::DwarfUnit::getDIE(), and llvm::DwarfUnit::getOrCreateSubprogramDIE().
getBaseAddress()
const MCSymbol * llvm::DwarfCompileUnit::getBaseAddress () const inline
Definition at line 245 of file DwarfCompileUnit.h.
getCU()
DwarfCompileUnit & llvm::DwarfCompileUnit::getCU () inline override virtual
Implements llvm::DwarfUnit.
Definition at line 101 of file DwarfCompileUnit.h.
References DwarfCompileUnit().
getGlobalNames()
const StringMap< const DIE * > & llvm::DwarfCompileUnit::getGlobalNames () const inline
Definition at line 207 of file DwarfCompileUnit.h.
getGlobalTypes()
const StringMap< const DIE * > & llvm::DwarfCompileUnit::getGlobalTypes () const inline
Definition at line 208 of file DwarfCompileUnit.h.
getLabelBegin()
MCSymbol * llvm::DwarfCompileUnit::getLabelBegin () const inline
Definition at line 196 of file DwarfCompileUnit.h.
References llvm::DwarfUnit::Section.
getLength()
unsigned llvm::DwarfCompileUnit::getLength () inline
Definition at line 189 of file DwarfCompileUnit.h.
References llvm::DwarfUnit::getHeaderSize(), and llvm::DwarfUnit::UnitDie.
getOrCreateGlobalVariableDIE()
DIE * llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE (DIGlobalVariable GV)
getOrCreateGlobalVariableDIE - get or create global variable DIE.
Definition at line 99 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::addBlock(), llvm::DwarfUnit::addConstantValue(), llvm::DwarfUnit::addDIEEntry(), addExpr(), llvm::DwarfUnit::addFlag(), addGlobalName(), llvm::DwarfUnit::addOpAddress(), llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::addString(), llvm::DwarfUnit::addType(), llvm::DwarfUnit::addUInt(), llvm::DwarfUnit::Asm, llvm::cast(), llvm::DwarfUnit::createAndAddDIE(), llvm::DwarfUnit::DD, llvm::DwarfUnit::DIEValueAllocator, llvm::dwarf::DW_AT_declaration, llvm::dwarf::DW_AT_external, llvm::dwarf::DW_AT_linkage_name, llvm::dwarf::DW_AT_location, llvm::dwarf::DW_AT_MIPS_linkage_name, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_AT_specification, llvm::dwarf::DW_FORM_data1, llvm::dwarf::DW_FORM_udata, llvm::dwarf::DW_OP_const4u, llvm::dwarf::DW_OP_const8u, llvm::dwarf::DW_OP_constu, llvm::dwarf::DW_OP_GNU_const_index, llvm::dwarf::DW_OP_GNU_push_tls_address, llvm::dwarf::DW_OP_plus, llvm::dyn_cast_or_null(), llvm::DIGlobalVariable::getConstant(), llvm::DIGlobalVariable::getContext(), llvm::DwarfUnit::getDIE(), llvm::DIGlobalVariable::getDisplayName(), llvm::DIGlobalVariable::getGlobal(), llvm::DIGlobalVariable::getLinkageName(), llvm::getMergedGlobalExpr(), llvm::DIGlobalVariable::getName(), llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::GlobalValue::getRealLinkageName(), llvm::DIGlobalVariable::getStaticDataMemberDeclaration(), llvm::DIDescriptor::getTag(), llvm::DIGlobalVariable::getType(), llvm::Value::getType(), llvm::DIGlobalVariable::isDefinition(), llvm::DIDescriptor::isGlobalVariable(), llvm::DIGlobalVariable::isLocalToUnit(), llvm::GlobalValue::isThreadLocal(), llvm::LinkageName, and llvm::DwarfUnit::resolve().
Referenced by constructImportedEntityDIE().
getOrCreateSourceID()
unsigned llvm::DwarfCompileUnit::getOrCreateSourceID (StringRef File, StringRef Directory) override virtual
Look up the source ID with the given directory and source file names. If none currently exists, create a new ID and insert it in the line table.
Implements llvm::DwarfUnit.
Definition at line 59 of file DwarfCompileUnit.cpp.
References llvm::DwarfUnit::Asm, and llvm::DwarfUnit::getUniqueID().
Referenced by constructInlinedScopeDIE().
getRangeLists()
const SmallVectorImpl< RangeSpanList > & llvm::DwarfCompileUnit::getRangeLists () const inline
getRangeLists - Get the vector of range lists.
Definition at line 236 of file DwarfCompileUnit.h.
getRanges()
const SmallVectorImpl< RangeSpan > & llvm::DwarfCompileUnit::getRanges () const inline
getRanges - Get the list of ranges for this unit.
Definition at line 241 of file DwarfCompileUnit.h.
getSectionSym()
MCSymbol * llvm::DwarfCompileUnit::getSectionSym () const inline
Definition at line 171 of file DwarfCompileUnit.h.
References llvm::DwarfUnit::Section.
getSkeleton()
DwarfCompileUnit * llvm::DwarfCompileUnit::getSkeleton () const inline
Definition at line 75 of file DwarfCompileUnit.h.
References DwarfCompileUnit().
Referenced by llvm::DwarfDebug::endFunction().
initSection()
void llvm::DwarfCompileUnit::initSection (const MCSection * Section, MCSymbol * SectionSym) inline
Pass in the SectionSym even though we could recreate it in every compile unit (type units will have actually distinct symbols once they're in comdat sections).
Definition at line 179 of file DwarfCompileUnit.h.
References llvm::DwarfUnit::Asm, llvm::DwarfUnit::getUniqueID(), llvm::DwarfUnit::initSection(), and llvm::DwarfUnit::Section.
initStmtList()
void llvm::DwarfCompileUnit::initStmtList (MCSymbol * DwarfLineSectionSym)
Definition at line 246 of file DwarfCompileUnit.cpp.
References addSectionLabel(), llvm::DwarfUnit::Asm, llvm::dwarf::DW_AT_stmt_list, llvm::DwarfUnit::getUniqueID(), and llvm::DwarfUnit::UnitDie.
setBaseAddress()
void llvm::DwarfCompileUnit::setBaseAddress (const MCSymbol * Base) inline
Definition at line 244 of file DwarfCompileUnit.h.
setSkeleton()
void llvm::DwarfCompileUnit::setSkeleton (DwarfCompileUnit & Skel) inline
Set the skeleton unit associated with this unit.
Definition at line 169 of file DwarfCompileUnit.h.
References DwarfCompileUnit().
takeRanges()
SmallVector< RangeSpan, 2 > llvm::DwarfCompileUnit::takeRanges () inline
Definition at line 242 of file DwarfCompileUnit.h.
updateSubprogramScopeDIE()
DIE & llvm::DwarfCompileUnit::updateSubprogramScopeDIE (DISubprogram SP)
Find DIE for the given subprogram and attach appropriate DW_AT_low_pc and DW_AT_high_pc attributes. If there are global variables in this scope then create and insert DIEs for these variables.
Definition at line 285 of file DwarfCompileUnit.cpp.
References addAddress(), llvm::DwarfUnit::addFlag(), llvm::DwarfUnit::Asm, attachLowHighPC(), llvm::DwarfUnit::DD, llvm::dwarf::DW_AT_APPLE_omit_frame_ptr, llvm::dwarf::DW_AT_frame_base, llvm::TargetRegisterInfo::getFrameRegister(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::MachineLocation::getReg(), and llvm::TargetRegisterInfo::isPhysicalRegister().
Referenced by constructSubprogramScopeDIE().
The documentation for this class was generated from the following files:
DwarfCompileUnit.h
DwarfCompileUnit.cpp