LLVM: llvm::MetadataTracking Class Reference
LLVM API Documentation
llvm::MetadataTracking Class Reference
API for tracking metadata references through RAUW and deletion.
#include <MetadataTracking.h>
Public Types
typedef PointerUnion< MetadataAsValue *, Metadata * > OwnerTy
Static Public Member Functions
static bool track (Metadata *&MD)
Track the reference to metadata.
static bool track (void *Ref, Metadata &MD, Metadata &Owner)
Track the reference to metadata for Metadata.
static bool track (void *Ref, Metadata &MD, MetadataAsValue &Owner)
Track the reference to metadata for MetadataAsValue.
static void untrack (Metadata *&MD)
Stop tracking a reference to metadata.
static void untrack (void *Ref, Metadata &MD)
static bool retrack (Metadata *&MD, Metadata *&New)
Move tracking from one reference to another.
static bool retrack (void *Ref, Metadata &MD, void *New)
static bool isReplaceable (const Metadata &MD)
Check whether metadata is replaceable.
Detailed Description
API for tracking metadata references through RAUW and deletion.
Shared API for updating Metadata pointers in subclasses that support RAUW.
This API is not meant to be used directly. See TrackingMDRef for a user-friendly tracking reference.
Definition at line 33 of file MetadataTracking.h.
Member Typedef Documentation
OwnerTy
typedef PointerUnion<MetadataAsValue *, Metadata *> llvm::MetadataTracking::OwnerTy
Definition at line 88 of file MetadataTracking.h.
Member Function Documentation
isReplaceable()
bool MetadataTracking::isReplaceable (const Metadata & MD) static
Check whether metadata is replaceable.
Definition at line 56 of file MetadataTracking.cpp.
Referenced by llvm::TrackingMDRef::hasTrivialDestructor().
retrack() [1/2]
bool llvm::MetadataTracking::retrack (Metadata *& MD, Metadata *& New) inline static
Move tracking from one reference to another.
Semantically equivalent to untrack(MD) followed by track(New), except that ownership callbacks are maintained.
Note: it is an error if *MD does not equal New.
Returns
true iff tracking is supported by MD.
Definition at line 80 of file MetadataTracking.h.
References retrack().
Referenced by retrack().
retrack() [2/2]
bool MetadataTracking::retrack (void * Ref, Metadata & MD, void * New) static
Definition at line 45 of file MetadataTracking.cpp.
track() [1/3]
bool llvm::MetadataTracking::track (Metadata *& MD) inline static
Track the reference to metadata.
Register MD with *MD, if the subclass supports tracking. If *MD gets RAUW'ed, MD will be updated to the new address. If *MD gets deleted, MD will be set to nullptr.
If tracking isn't supported, *MD will not change.
Returns
true iff tracking is supported by MD.
Definition at line 44 of file MetadataTracking.h.
References track().
Referenced by track(), track(), and track().
track() [2/3]
bool llvm::MetadataTracking::track (void * Ref, Metadata & MD, Metadata & Owner) inline static
Track the reference to metadata for Metadata.
As track(Metadata*&), but with support for calling back to Owner to tell it that its operand changed. This could trigger Owner being re-uniqued.
Definition at line 53 of file MetadataTracking.h.
References track().
track() [3/3]
bool llvm::MetadataTracking::track (void * Ref, Metadata & MD, MetadataAsValue & Owner) inline static
Track the reference to metadata for MetadataAsValue.
As track(Metadata*&), but with support for calling back to Owner to tell it that its operand changed. This could trigger Owner being re-uniqued.
Definition at line 62 of file MetadataTracking.h.
References track().
untrack() [1/2]
void llvm::MetadataTracking::untrack (Metadata *& MD) inline static
Stop tracking a reference to metadata.
Stops *MD from tracking MD.
Definition at line 69 of file MetadataTracking.h.
References untrack().
Referenced by untrack().
untrack() [2/2]
void MetadataTracking::untrack (void * Ref, Metadata & MD) static
Definition at line 39 of file MetadataTracking.cpp.
The documentation for this class was generated from the following files:
MetadataTracking.h
MetadataTracking.cpp