LLVM: llvm::DIDerivedType Class Reference
LLVM API Documentation
llvm::DIDerivedType Class Reference
A simple derived type.
#include <DebugInfo.h>
Public Member Functions
DIDerivedType (const MDNode *N=nullptr)
DITypeRef getTypeDerivedFrom () const
MDNode * getObjCProperty () const
Return property node, if this ivar is associated with one.
DITypeRef getClassType () const
Constant * getConstant () const
bool Verify () const
Public Member Functions inherited from llvm::DIType
DIType (const MDNode *N=nullptr)
operator DITypeRef () const
bool Verify () const
DIScopeRef getContext () const
StringRef getName () const
unsigned getLineNumber () const
uint64_t getSizeInBits () const
uint64_t getAlignInBits () const
uint64_t getOffsetInBits () const
unsigned getFlags () const
bool isPrivate () const
bool isProtected () const
bool isPublic () const
bool isForwardDecl () const
bool isAppleBlockExtension () const
bool isBlockByrefStruct () const
bool isVirtual () const
bool isArtificial () const
bool isObjectPointer () const
bool isObjcClassComplete () const
bool isVector () const
bool isStaticMember () const
bool isLValueReference () const
bool isRValueReference () const
bool isValid () const
Public Member Functions inherited from llvm::DIScope
DIScope (const MDNode *N=nullptr)
DIScopeRef getContext () const
Get the parent scope.
StringRef getName () const
Get the scope name.
StringRef getFilename () const
StringRef getDirectory () const
DIScopeRef getRef () const
Generate a reference to this DIScope.
Public Member Functions inherited from llvm::DIDescriptor
DIDescriptor (const MDNode *N=nullptr)
bool Verify () const
MDNode * get () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
StringRef getHeader () const
size_t getNumHeaderFields () const
StringRef getHeaderField (unsigned Index) const
template<class T>
T getHeaderFieldAs (unsigned Index) const
uint16_t getTag () const
bool isDerivedType () const
bool isCompositeType () const
bool isSubroutineType () const
bool isBasicType () const
bool isVariable () const
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
bool isCompileUnit () const
bool isNameSpace () const
bool isLexicalBlockFile () const
bool isLexicalBlock () const
bool isSubrange () const
bool isEnumerator () const
bool isType () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
bool isImportedEntity () const
bool isExpression () const
void print (raw_ostream &OS) const
void dump () const
void replaceAllUsesWith (LLVMContext &VMContext, DIDescriptor D)
Replace all uses of debug info referenced by this descriptor.
void replaceAllUsesWith (MDNode *D)
Friends
class DIDescriptor
Additional Inherited Members
Public Types inherited from llvm::DIDescriptor
enum {
FlagAccessibility = 1 << 0 | 1 << 1 , FlagPrivate = 1 , FlagProtected = 2 , FlagPublic = 3 ,
FlagFwdDecl = 1 << 2 , FlagAppleBlock = 1 << 3 , FlagBlockByrefStruct = 1 << 4 , FlagVirtual = 1 << 5 ,
FlagArtificial = 1 << 6 , FlagExplicit = 1 << 7 , FlagPrototyped = 1 << 8 , FlagObjcClassComplete = 1 << 9 ,
FlagObjectPointer = 1 << 10 , FlagVector = 1 << 11 , FlagStaticMember = 1 << 12 , FlagIndirectVariable = 1 << 13 ,
FlagLValueReference = 1 << 14 , FlagRValueReference = 1 << 15
}
Accessibility flags.
Protected Member Functions inherited from llvm::DIType
void printInternal (raw_ostream &OS) const
Protected Member Functions inherited from llvm::DIScope
void printInternal (raw_ostream &OS) const
Protected Member Functions inherited from llvm::DIDescriptor
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy>
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
template<>
DITypeRef getFieldAs (unsigned Elt) const
Protected Attributes inherited from llvm::DIDescriptor
const MDNode * DbgNode
Detailed Description
A simple derived type.
Like a const qualified type, a typedef, a pointer or reference, et cetera. Or, a data member of a class/struct/union.
Definition at line 468 of file DebugInfo.h.
Constructor & Destructor Documentation
DIDerivedType()
llvm::DIDerivedType::DIDerivedType (const MDNode * N = nullptr) inline explicit
Definition at line 473 of file DebugInfo.h.
References llvm::DIType::DIType(), and N.
Referenced by llvm::DICompositeType::DICompositeType().
Member Function Documentation
getClassType()
DITypeRef llvm::DIDerivedType::getClassType () const inline
Definition at line 480 of file DebugInfo.h.
References llvm::dwarf::DW_TAG_ptr_to_member_type, llvm::DIDescriptor::getFieldAs(), and llvm::DIDescriptor::getTag().
getConstant()
Constant * llvm::DIDerivedType::getConstant () const inline
Definition at line 485 of file DebugInfo.h.
References llvm::dwarf::DW_TAG_member, llvm::DIDescriptor::getConstantField(), llvm::DIDescriptor::getTag(), and llvm::DIType::isStaticMember().
Referenced by llvm::DwarfUnit::getOrCreateStaticMemberDIE().
getObjCProperty()
MDNode * DIDerivedType::getObjCProperty () const
Return property node, if this ivar is associated with one.
Definition at line 648 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, and getNodeField().
getTypeDerivedFrom()
DITypeRef llvm::DIDerivedType::getTypeDerivedFrom () const inline
Definition at line 475 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
Referenced by llvm::DwarfUnit::addBlockByrefAddress(), llvm::DwarfUnit::constructTypeDIE(), getBaseTypeSize(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::DIVariable::getSizeInBits(), llvm::DbgVariable::getType(), and isUnsignedDIType().
Verify()
bool DIDerivedType::Verify () const
Definition at line 461 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, llvm::dwarf::DW_TAG_ptr_to_member_type, fieldIsTypeRef(), llvm::DIDescriptor::getNumHeaderFields(), llvm::DIDescriptor::getTag(), and llvm::DIDescriptor::isDerivedType().
Referenced by llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::DIDescriptor::Verify(), and llvm::DIType::Verify().
Friends And Related Symbol Documentation
DIDescriptor
friend class DIDescriptor friend
Definition at line 469 of file DebugInfo.h.
References DIDescriptor.
Referenced by DIDescriptor.
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp