LLVM: llvm::cl::alias Class Reference
LLVM API Documentation
llvm::cl::alias Class Reference
#include <CommandLine.h>
Public Member Functions
void setAliasFor (Option &O)
template<class M0t>
alias (const M0t &M0)
template<class M0t, class M1t>
alias (const M0t &M0, const M1t &M1)
template<class M0t, class M1t, class M2t>
alias (const M0t &M0, const M1t &M1, const M2t &M2)
template<class M0t, class M1t, class M2t, class M3t>
alias (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3)
Public Member Functions inherited from llvm::cl::Option
enum NumOccurrencesFlag getNumOccurrencesFlag () const
enum ValueExpected getValueExpectedFlag () const
enum OptionHidden getOptionHiddenFlag () const
enum FormattingFlags getFormattingFlag () const
unsigned getMiscFlags () const
unsigned getPosition () const
unsigned getNumAdditionalVals () const
bool hasArgStr () const
void setArgStr (const char *S)
void setDescription (const char *S)
void setValueStr (const char *S)
void setNumOccurrencesFlag (enum NumOccurrencesFlag Val)
void setValueExpectedFlag (enum ValueExpected Val)
void setHiddenFlag (enum OptionHidden Val)
void setFormattingFlag (enum FormattingFlags V)
void setMiscFlag (enum MiscFlags M)
void setPosition (unsigned pos)
void setCategory (OptionCategory &C)
void addArgument ()
void removeArgument ()
Option * getNextRegisteredOption () const
virtual void getExtraOptionNames (SmallVectorImpl< const char * > &)
bool error (const Twine &Message, StringRef ArgName=StringRef())
int getNumOccurrences () const
virtual ~Option ()
Additional Inherited Members
Public Attributes inherited from llvm::cl::Option
const char * ArgStr
const char * HelpStr
const char * ValueStr
OptionCategory * Category
Protected Member Functions inherited from llvm::cl::Option
Option (enum NumOccurrencesFlag OccurrencesFlag, enum OptionHidden Hidden)
void setNumAdditionalVals (unsigned n)
Detailed Description
Definition at line 1691 of file CommandLine.h.
Constructor & Destructor Documentation
alias() [1/4]
template<class M0t> llvm::cl::alias::alias (const M0t & M0) inline explicit
Definition at line 1730 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::Hidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
alias() [2/4]
template<class M0t, class M1t> llvm::cl::alias::alias (const M0t & M0, const M1t & M1) inline
Definition at line 1737 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::Hidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
alias() [3/4]
template<class M0t, class M1t, class M2t> llvm::cl::alias::alias (const M0t & M0, const M1t & M1, const M2t & M2) inline
Definition at line 1745 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::Hidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
alias() [4/4]
template<class M0t, class M1t, class M2t, class M3t> llvm::cl::alias::alias (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3) inline
Definition at line 1754 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::Hidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
Member Function Documentation
setAliasFor()
void llvm::cl::alias::setAliasFor (Option & O) inline
Definition at line 1722 of file CommandLine.h.
References llvm::cl::Option::error(), and llvm::cl::Option::Option().
The documentation for this class was generated from the following files:
CommandLine.h
CommandLine.cpp