LLVM: llvm::DbgValueHistoryMap Class Reference
LLVM API Documentation
llvm::DbgValueHistoryMap Class Reference
#include <DbgValueHistoryCalculator.h>
Public Types
typedef std::pair< const MachineInstr *, const MachineInstr * > InstrRange
typedef SmallVector< InstrRange, 4 > InstrRanges
typedef MapVector< const MDNode *, InstrRanges > InstrRangesMap
Public Member Functions
void startInstrRange (const MDNode *Var, const MachineInstr &MI)
void endInstrRange (const MDNode *Var, const MachineInstr &MI)
unsigned getRegisterForVar (const MDNode *Var) const
bool empty () const
void clear ()
InstrRangesMap::const_iterator begin () const
InstrRangesMap::const_iterator end () const
Detailed Description
Definition at line 25 of file DbgValueHistoryCalculator.h.
Member Typedef Documentation
InstrRange
typedef std::pair<const MachineInstr *, const MachineInstr *> llvm::DbgValueHistoryMap::InstrRange
Definition at line 32 of file DbgValueHistoryCalculator.h.
InstrRanges
typedef SmallVector<InstrRange, 4> llvm::DbgValueHistoryMap::InstrRanges
Definition at line 33 of file DbgValueHistoryCalculator.h.
InstrRangesMap
typedef MapVector<const MDNode *, InstrRanges> llvm::DbgValueHistoryMap::InstrRangesMap
Definition at line 34 of file DbgValueHistoryCalculator.h.
Member Function Documentation
begin()
InstrRangesMap::const_iterator llvm::DbgValueHistoryMap::begin () const inline
Definition at line 47 of file DbgValueHistoryCalculator.h.
clear()
void llvm::DbgValueHistoryMap::clear () inline
Definition at line 46 of file DbgValueHistoryCalculator.h.
empty()
bool llvm::DbgValueHistoryMap::empty () const inline
Definition at line 45 of file DbgValueHistoryCalculator.h.
end()
InstrRangesMap::const_iterator llvm::DbgValueHistoryMap::end () const inline
Definition at line 48 of file DbgValueHistoryCalculator.h.
endInstrRange()
void DbgValueHistoryMap::endInstrRange (const MDNode * Var, const MachineInstr & MI)
Definition at line 50 of file DbgValueHistoryCalculator.cpp.
References Ranges.
Referenced by clobberRegisterUses().
getRegisterForVar()
unsigned DbgValueHistoryMap::getRegisterForVar (const MDNode * Var) const
Definition at line 61 of file DbgValueHistoryCalculator.cpp.
References I, isDescribedByReg(), and Ranges.
Referenced by llvm::calculateDbgValueHistory().
startInstrRange()
void DbgValueHistoryMap::startInstrRange (const MDNode * Var, const MachineInstr & MI)
Definition at line 35 of file DbgValueHistoryCalculator.cpp.
References llvm::dbgs(), DEBUG, and Ranges.
Referenced by llvm::calculateDbgValueHistory().
The documentation for this class was generated from the following files:
DbgValueHistoryCalculator.h
DbgValueHistoryCalculator.cpp