LLVM: llvm::TargetLowering Class Reference
LLVM API Documentation
llvm::TargetLowering Class Reference
#include <TargetLowering.h>
Classes
struct ArgListEntry
struct AsmOperandInfo
This contains information for each constraint that we are lowering.
struct CallLoweringInfo
struct DAGCombinerInfo
struct TargetLoweringOpt
Public Types
enum ConstraintType {
C_Register , C_RegisterClass , C_Memory , C_Other ,
C_Unknown
}
enum ConstraintWeight {
CW_Invalid = -1 , CW_Okay = 0 , CW_Good = 1 , CW_Better = 2 ,
CW_Best = 3 , CW_SpecificReg = CW_Okay , CW_Register = CW_Good , CW_Memory = CW_Better ,
CW_Constant = CW_Best , CW_Default = CW_Okay
}
typedef std::vector< ArgListEntry > ArgListTy
typedef std::vector< AsmOperandInfo > AsmOperandInfoVector
Public Types inherited from llvm::TargetLoweringBase
enum LegalizeAction { Legal , Promote , Expand , Custom }
enum LegalizeTypeAction {
TypeLegal , TypePromoteInteger , TypeExpandInteger , TypeSoftenFloat ,
TypeExpandFloat , TypeScalarizeVector , TypeSplitVector , TypeWidenVector
}
enum BooleanContent { UndefinedBooleanContent , ZeroOrOneBooleanContent , ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect , ScalarCondVectorVal , VectorMaskSelect }
Enum that describes what type of support for selects the target has.
typedef std::pair< LegalizeTypeAction, EVT > LegalizeKind
Public Member Functions
TargetLowering (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
virtual bool getPreIndexedAddressParts (SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
virtual bool getPostIndexedAddressParts (SDNode *, SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
virtual unsigned getJumpTableEncoding () const
virtual const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *, const MachineBasicBlock *, unsigned, MCContext &) const
virtual SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const
Returns relocation base for the given PIC jumptable.
virtual const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const
virtual bool isOffsetFoldingLegal (const GlobalAddressSDNode *GA) const
bool isInTailCallPosition (SelectionDAG &DAG, SDNode *Node, SDValue &Chain) const
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, SDLoc DL) const
std::pair< SDValue, SDValue > makeLibCall (SelectionDAG &DAG, RTLIB::Libcall LC, EVT RetVT, const SDValue *Ops, unsigned NumOps, bool isSigned, SDLoc dl, bool doesNotReturn=false, bool isReturnValueUsed=true) const
Returns a pair of (return value, chain).
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedMask, APInt &KnownZero, APInt &KnownOne, TargetLoweringOpt &TLO, unsigned Depth=0) const
virtual void computeKnownBitsForTargetNode (const SDValue Op, APInt &KnownZero, APInt &KnownOne, const SelectionDAG &DAG, unsigned Depth=0) const
virtual unsigned ComputeNumSignBitsForTargetNode (SDValue Op, const SelectionDAG &DAG, unsigned Depth=0) const
bool isConstTrueVal (const SDNode *N) const
bool isConstFalseVal (const SDNode *N) const
SDValue SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo &DCI, SDLoc dl) const
virtual bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const
virtual SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const
virtual bool isDesirableToCommuteWithShift (const SDNode *N) const
Return true if it is profitable to move a following shift through this.
virtual bool isTypeDesirableForOp (unsigned, EVT VT) const
virtual bool isDesirableToTransformToIntegerOp (unsigned, EVT) const
virtual bool IsDesirableToPromoteOp (SDValue, EVT &) const
virtual SDValue LowerFormalArguments (SDValue, CallingConv::ID, bool, const SmallVectorImpl< ISD::InputArg > &, SDLoc, SelectionDAG &, SmallVectorImpl< SDValue > &) const
std::pair< SDValue, SDValue > LowerCallTo (CallLoweringInfo &CLI) const
virtual SDValue LowerCall (CallLoweringInfo &, SmallVectorImpl< SDValue > &) const
virtual void HandleByVal (CCState *, unsigned &, unsigned) const
Target-specific cleanup for formal ByVal parameters.
virtual bool CanLowerReturn (CallingConv::ID, MachineFunction &, bool, const SmallVectorImpl< ISD::OutputArg > &, LLVMContext &) const
virtual SDValue LowerReturn (SDValue, CallingConv::ID, bool, const SmallVectorImpl< ISD::OutputArg > &, const SmallVectorImpl< SDValue > &, SDLoc, SelectionDAG &) const
virtual bool isUsedByReturnOnly (SDNode *, SDValue &) const
virtual bool mayBeEmittedAsTailCall (CallInst *) const
virtual const char * getClearCacheBuiltinName () const
virtual unsigned getRegisterByName (const char *RegName, EVT VT) const
virtual EVT getTypeForExtArgOrReturn (LLVMContext &Context, EVT VT, ISD::NodeType) const
virtual bool functionArgumentNeedsConsecutiveRegisters (Type *Ty, CallingConv::ID CallConv, bool isVarArg) const
virtual const MCPhysReg * getScratchRegisters (CallingConv::ID CC) const
virtual SDValue prepareVolatileOrAtomicLoad (SDValue Chain, SDLoc DL, SelectionDAG &DAG) const
virtual void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const
virtual SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const
virtual void ReplaceNodeResults (SDNode *, SmallVectorImpl< SDValue > &, SelectionDAG &) const
virtual const char * getTargetNodeName (unsigned Opcode) const
This method returns the name of a target specific DAG node.
virtual FastISel * createFastISel (FunctionLoweringInfo &, const TargetLibraryInfo *) const
bool verifyReturnAddressArgumentIsConstant (SDValue Op, SelectionDAG &DAG) const
virtual bool ExpandInlineAsm (CallInst *) const
virtual AsmOperandInfoVector ParseConstraints (ImmutableCallSite CS) const
virtual ConstraintWeight getMultipleConstraintMatchWeight (AsmOperandInfo &info, int maIndex) const
virtual ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const
virtual void ComputeConstraintToUse (AsmOperandInfo &OpInfo, SDValue Op, SelectionDAG *DAG=nullptr) const
virtual ConstraintType getConstraintType (const std::string &Constraint) const
Given a constraint, return the type of constraint it is for this target.
virtual std::pair< unsigned, const TargetRegisterClass * > getRegForInlineAsmConstraint (const std::string &Constraint, MVT VT) const
virtual const char * LowerXConstraint (EVT ConstraintVT) const
virtual void LowerAsmOperandForConstraint (SDValue Op, std::string &Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const
SDValue BuildExactSDIV (SDValue Op1, SDValue Op2, SDLoc dl, SelectionDAG &DAG) const
Given an exact SDIV by a constant, create a multiplication with the multiplicative inverse of the constant.
SDValue BuildSDIV (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, bool IsAfterLegalization, std::vector< SDNode * > *Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
SDValue BuildUDIV (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, bool IsAfterLegalization, std::vector< SDNode * > *Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
virtual SDValue BuildSDIVPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, std::vector< SDNode * > *Created) const
virtual bool combineRepeatedFPDivisors (unsigned NumUsers) const
virtual SDValue getRsqrtEstimate (SDValue Operand, DAGCombinerInfo &DCI, unsigned &RefinementSteps, bool &UseOneConstNR) const
virtual SDValue getRecipEstimate (SDValue Operand, DAGCombinerInfo &DCI, unsigned &RefinementSteps) const
bool expandMUL (SDNode *N, SDValue &Lo, SDValue &Hi, EVT HiLoVT, SelectionDAG &DAG, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
bool expandFP_TO_SINT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
virtual MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *MBB) const
virtual void AdjustInstrPostInstrSelection (MachineInstr *MI, SDNode *Node) const
virtual bool useLoadStackGuardNode () const
virtual bool shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const
Returns true if arguments should be sign-extended in lib calls.
Public Member Functions inherited from llvm::TargetLoweringBase
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
virtual ~TargetLoweringBase ()
const TargetMachine & getTargetMachine () const
const DataLayout * getDataLayout () const
const TargetLoweringObjectFile & getObjFileLowering () const
bool isBigEndian () const
bool isLittleEndian () const
virtual MVT getPointerTy (uint32_t=0) const
unsigned getPointerSizeInBits (uint32_t AS=0) const
unsigned getPointerTypeSizeInBits (Type *Ty) const
virtual MVT getScalarShiftAmountTy (EVT LHSTy) const
EVT getShiftAmountTy (EVT LHSTy) const
virtual MVT getVectorIdxTy () const
bool isSelectExpensive () const
Return true if the select operation is expensive for this target.
virtual bool isSelectSupported (SelectSupportKind) const
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (EVT VT) const
Return the preferred vector type legalization action.
virtual bool shouldExpandBuildVectorWithShuffles (EVT, unsigned DefinedValues) const
bool isIntDivCheap () const
bool isFsqrtCheap () const
Return true if sqrt(x) is as cheap or cheaper than 1 / rsqrt(x)
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
bool isPow2SDivCheap () const
Return true if pow2 sdiv is cheaper than a chain of sra/srl/add/sra.
bool isJumpExpensive () const
bool isPredictableSelectExpensive () const
virtual bool isLoadBitCastBeneficial (EVT, EVT) const
virtual bool isCheapToSpeculateCttz () const
Return true if it is cheap to speculate a call to intrinsic cttz.
virtual bool isCheapToSpeculateCtlz () const
Return true if it is cheap to speculate a call to intrinsic ctlz.
bool isMaskAndBranchFoldingLegal () const
Return if the target supports combining a chain like:
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
bool hasFloatingPointExceptions () const
Return true if target supports floating point exceptions.
virtual bool enableAggressiveFMAFusion (EVT VT) const
virtual EVT getSetCCResultType (LLVMContext &Context, EVT VT) const
Return the ValueType of the result of SETCC operations.
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
BooleanContent getBooleanContents (EVT Type) const
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual Sched::Preference getSchedulingPreference (SDNode *) const
virtual const TargetRegisterClass * getRegClassFor (MVT VT) const
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
virtual uint8_t getRepRegClassCostFor (MVT VT) const
bool isTypeLegal (EVT VT) const
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
LegalizeTypeAction getTypeAction (MVT VT) const
EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
virtual bool getTgtMemIntrinsic (IntrinsicInfo &, const CallInst &, unsigned) const
virtual bool isFPImmLegal (const APFloat &, EVT) const
virtual bool isShuffleMaskLegal (const SmallVectorImpl< int > &, EVT) const
virtual bool canOpTrap (unsigned Op, EVT VT) const
virtual bool isVectorClearMaskLegal (const SmallVectorImpl< int > &, EVT) const
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT) const
bool isOperationLegalOrPromote (unsigned Op, EVT VT) const
bool isOperationExpand (unsigned Op, EVT VT) const
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
EVT getValueType (Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
virtual unsigned getByValTypeAlignment (Type *Ty) const
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
unsigned getNumRegisters (LLVMContext &Context, EVT VT) const
virtual bool ShouldShrinkFPConstant (EVT) const
virtual bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const
bool hasBigEndianPartOrdering (EVT VT) const
bool hasTargetDAGCombine (ISD::NodeType NT) const
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool allowsMisalignedMemoryAccesses (EVT, unsigned AddrSpace=0, unsigned Align=1, bool *=nullptr) const
Determine if the target supports unaligned memory accesses.
virtual EVT getOptimalMemOpType (uint64_t, unsigned, unsigned, bool, bool, bool, MachineFunction &) const
virtual bool isSafeMemOpType (MVT) const
bool usesUnderscoreSetJmp () const
Determine if we should use _setjmp or setjmp to implement llvm.setjmp.
bool usesUnderscoreLongJmp () const
Determine if we should use _longjmp or longjmp to implement llvm.longjmp.
int getMinimumJumpTableEntries () const
unsigned getStackPointerRegisterToSaveRestore () const
unsigned getExceptionPointerRegister () const
unsigned getExceptionSelectorRegister () const
unsigned getJumpBufSize () const
unsigned getJumpBufAlignment () const
unsigned getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
unsigned getMinFunctionAlignment () const
Return the minimum function alignment.
unsigned getPrefFunctionAlignment () const
Return the preferred function alignment.
virtual unsigned getPrefLoopAlignment (MachineLoop *ML=nullptr) const
Return the preferred loop alignment.
bool getInsertFencesForAtomic () const
virtual bool getStackCookieLocation (unsigned &, unsigned &) const
virtual unsigned getMaximalGlobalOffset () const
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast between SrcAS and DestAS is a noop.
virtual bool shouldExpandAtomicStoreInIR (StoreInst *SI) const
virtual bool shouldExpandAtomicLoadInIR (LoadInst *LI) const
virtual bool shouldExpandAtomicRMWInIR (AtomicRMWInst *RMWI) const
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
virtual void resetOperationActions ()
Reset the operation actions based on target options.
virtual bool GetAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value * > &, Type *&) const
virtual bool isLegalAddressingMode (const AddrMode &AM, Type *Ty) const
virtual int getScalingFactorCost (const AddrMode &AM, Type *Ty) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
virtual bool isLegalICmpImmediate (int64_t) const
virtual bool isLegalAddImmediate (int64_t) const
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
virtual bool isTruncateFree (Type *, Type *) const
virtual bool allowTruncateForTailCall (Type *, Type *) const
virtual bool isTruncateFree (EVT, EVT) const
virtual bool isZExtFree (Type *, Type *) const
virtual bool isZExtFree (EVT, EVT) const
virtual bool hasPairedLoad (Type *, unsigned &) const
virtual bool hasPairedLoad (EVT, unsigned &) const
virtual bool isZExtFree (SDValue Val, EVT VT2) const
virtual bool isFPExtFree (EVT VT) const
virtual bool isFNegFree (EVT VT) const
virtual bool isFAbsFree (EVT VT) const
virtual bool isFMAFasterThanFMulAndFAdd (EVT) const
virtual bool isNarrowingProfitable (EVT, EVT) const
virtual bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const
Return true if it is beneficial to convert a load of a constant to just the constant itself. On some targets it might be more efficient to use a combination of arithmetic instructions to materialize the constant instead of loading it from a constant pool.
virtual bool isExtractSubvectorCheap (EVT ResVT, unsigned Index) const
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
LegalizeKind getTypeConversion (LLVMContext &Context, EVT VT) const
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
std::pair< unsigned, MVT > getTypeLegalizationCost (Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
virtual bool hasLoadLinkedStoreConditional () const
virtual Value * emitLoadLinked (IRBuilder<> &Builder, Value *Addr, AtomicOrdering Ord) const
virtual Value * emitStoreConditional (IRBuilder<> &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const
virtual Instruction * emitLeadingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const
virtual Instruction * emitTrailingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const
Additional Inherited Members
Static Public Member Functions inherited from llvm::TargetLoweringBase
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions inherited from llvm::TargetLoweringBase
void initActions ()
Initialize all of the actions to default values.
void setBooleanContents (BooleanContent Ty)
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
void setBooleanVectorContents (BooleanContent Ty)
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setUseUnderscoreSetJmp (bool Val)
void setUseUnderscoreLongJmp (bool Val)
void setMinimumJumpTableEntries (int Val)
void setStackPointerRegisterToSaveRestore (unsigned R)
void setExceptionPointerRegister (unsigned R)
void setExceptionSelectorRegister (unsigned R)
void setSelectIsExpensive (bool isExpensive=true)
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
void setHasExtractBitsInsn (bool hasExtractInsn=true)
void setJumpIsExpensive (bool isExpensive=true)
void setIntDivIsCheap (bool isCheap=true)
void setFsqrtIsCheap (bool isCheap=true)
void setHasFloatingPointExceptions (bool FPExceptions=true)
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void setPow2SDivIsCheap (bool isCheap=true)
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
void clearRegisterClasses ()
Remove all register classes.
void clearOperationActions ()
Remove all operation actions.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (MVT VT) const
void computeRegisterProperties ()
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
void setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action)
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
void setTargetDAGCombine (ISD::NodeType NT)
void setJumpBufSize (unsigned Size)
Set the target's required jmp_buf buffer size (in bytes); default is 200.
void setJumpBufAlignment (unsigned Align)
void setMinFunctionAlignment (unsigned Align)
Set the target's minimum function alignment (in log2(bytes))
void setPrefFunctionAlignment (unsigned Align)
void setPrefLoopAlignment (unsigned Align)
void setMinStackArgumentAlignment (unsigned Align)
Set the minimum stack alignment of an argument (in log2(bytes)).
void setInsertFencesForAtomic (bool fence)
bool isLegalRC (const TargetRegisterClass *RC) const
MachineBasicBlock * emitPatchPoint (MachineInstr *MI, MachineBasicBlock *MBB) const
Protected Attributes inherited from llvm::TargetLoweringBase
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
unsigned MaxStoresPerMemcpy
Specify maximum bytes of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
unsigned MaxStoresPerMemmove
Specify maximum bytes of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
bool PredictableSelectIsExpensive
bool MaskAndBranchFoldingIsLegal
bool EnableExtLdPromotion
Detailed Description
This class defines information used to lower LLVM code to legal SelectionDAG operators that the target instruction selector can accept natively.
This class also defines callbacks that targets must implement to lower target-specific constructs to SelectionDAG operators.
Definition at line 2021 of file TargetLowering.h.
Member Typedef Documentation
ArgListTy
typedef std::vector<ArgListEntry> llvm::TargetLowering::ArgListTy
Definition at line 2287 of file TargetLowering.h.
AsmOperandInfoVector
typedef std::vector<AsmOperandInfo> llvm::TargetLowering::AsmOperandInfoVector
Definition at line 2650 of file TargetLowering.h.
Member Enumeration Documentation
ConstraintType
enum llvm::TargetLowering::ConstraintType
Enumerator
C_Register
C_RegisterClass
C_Memory
C_Other
C_Unknown
Definition at line 2592 of file TargetLowering.h.
ConstraintWeight
enum llvm::TargetLowering::ConstraintWeight
Enumerator
CW_Invalid
CW_Okay
CW_Good
CW_Better
CW_Best
CW_SpecificReg
CW_Register
CW_Memory
CW_Constant
CW_Default
Definition at line 2600 of file TargetLowering.h.
Constructor & Destructor Documentation
TargetLowering()
TargetLowering::TargetLowering (const TargetMachine & TM) explicit
NOTE: The TargetMachine owns TLOF.
Definition at line 39 of file TargetLowering.cpp.
Member Function Documentation
AdjustInstrPostInstrSelection()
void TargetLowering::AdjustInstrPostInstrSelection (MachineInstr * MI, SDNode * Node) const virtual
This method should be implemented by targets that mark instructions with the 'hasPostISelHook' flag. These instructions must be adjusted after instruction selection by target hooks. e.g. To fill in optional defs for ARM 's' setting instructions.
Reimplemented in llvm::ARMTargetLowering, and llvm::SITargetLowering.
Definition at line 329 of file SelectionDAGISel.cpp.
BuildExactSDIV()
SDValue TargetLowering::BuildExactSDIV (SDValue Op1, SDValue Op2, SDLoc dl, SelectionDAG & DAG) const
Given an exact SDIV by a constant, create a multiplication with the multiplicative inverse of the constant.
Definition at line 2633 of file TargetLowering.cpp.
References llvm::APInt::ashr(), llvm::cast(), llvm::APInt::countTrailingZeros(), llvm::APInt::getBitWidth(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::SDValue::getValueType(), llvm::ISD::MUL, and llvm::ISD::SRA.
BuildSDIV()
SDValue TargetLowering::BuildSDIV (SDNode * N, const APInt & Divisor, SelectionDAG & DAG, bool IsAfterLegalization, std::vector< SDNode * > * Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
Definition at line 2662 of file TargetLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarSizeInBits(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::APInt::isNegative(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::APInt::isStrictlyPositive(), llvm::TargetLoweringBase::isTypeLegal(), llvm::APInt::ms::m, llvm::APInt::magic(), llvm::ISD::MULHS, N, llvm::APInt::ms::s, llvm::ISD::SMUL_LOHI, llvm::ISD::SRA, llvm::ISD::SRL, and llvm::ISD::SUB.
BuildSDIVPow2()
virtual SDValue llvm::TargetLowering::BuildSDIVPow2 (SDNode * N, const APInt & Divisor, SelectionDAG & DAG, std::vector< SDNode * > * Created) const inline virtual
Reimplemented in llvm::PPCTargetLowering.
Definition at line 2714 of file TargetLowering.h.
References N.
BuildUDIV()
SDValue TargetLowering::BuildUDIV (SDNode * N, const APInt & Divisor, SelectionDAG & DAG, bool IsAfterLegalization, std::vector< SDNode * > * Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
Definition at line 2719 of file TargetLowering.cpp.
References llvm::APInt::mu::a, llvm::ISD::ADD, llvm::APInt::countTrailingZeros(), llvm::APInt::getBitWidth(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::TargetLoweringBase::isTypeLegal(), llvm::APInt::lshr(), llvm::APInt::mu::m, llvm::APInt::magicu(), llvm::ISD::MULHU, N, llvm::APInt::mu::s, llvm::ISD::SRL, llvm::ISD::SUB, and llvm::ISD::UMUL_LOHI.
CanLowerReturn()
virtual bool llvm::TargetLowering::CanLowerReturn (CallingConv::ID , MachineFunction & , bool , const SmallVectorImpl< ISD::OutputArg > & , LLVMContext &) const inline virtual
This hook should be implemented to check whether the return values described by the Outs array can fit into the return registers. If false is returned, an sret-demotion is performed.
Definition at line 2438 of file TargetLowering.h.
Referenced by LowerCallTo().
combineRepeatedFPDivisors()
virtual bool llvm::TargetLowering::combineRepeatedFPDivisors (unsigned NumUsers) const inline virtual
Indicate whether this target prefers to combine the given number of FDIVs with the same divisor.
Definition at line 2722 of file TargetLowering.h.
ComputeConstraintToUse()
void TargetLowering::ComputeConstraintToUse (AsmOperandInfo & OpInfo, SDValue Op, SelectionDAG * DAG = nullptr) const virtual
Determines the constraint code and constraint type to use for the specific AsmOperandInfo, setting OpInfo.ConstraintCode and OpInfo.ConstraintType. If the actual operand being passed in is available, it can be passed in as Op, otherwise an empty SDValue can be passed.
ComputeConstraintToUse - Determines the constraint code and constraint type to use for the specific AsmOperandInfo, setting OpInfo.ConstraintCode and OpInfo.ConstraintType.
Definition at line 2598 of file TargetLowering.cpp.
References llvm::TargetLowering::AsmOperandInfo::CallOperandVal, ChooseConstraint(), llvm::InlineAsm::ConstraintInfo::Codes, llvm::TargetLowering::AsmOperandInfo::ConstraintCode, llvm::TargetLowering::AsmOperandInfo::ConstraintType, llvm::TargetLowering::AsmOperandInfo::ConstraintVT, getConstraintType(), llvm::isa(), and LowerXConstraint().
computeKnownBitsForTargetNode()
void TargetLowering::computeKnownBitsForTargetNode (const SDValue Op, APInt & KnownZero, APInt & KnownOne, const SelectionDAG & DAG, unsigned Depth = 0) const virtual
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
computeKnownBitsForTargetNode - Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::PPCTargetLowering, llvm::SparcTargetLowering, and llvm::X86TargetLowering.
Definition at line 1088 of file TargetLowering.cpp.
References llvm::ISD::BUILTIN_OP_END, llvm::APInt::getBitWidth(), llvm::SDValue::getOpcode(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, and llvm::ISD::INTRINSIC_WO_CHAIN.
ComputeNumSignBitsForTargetNode()
unsigned TargetLowering::ComputeNumSignBitsForTargetNode (SDValue Op, const SelectionDAG & DAG, unsigned Depth = 0) const virtual
This method can be implemented by targets that want to expose additional information about sign bits to the DAG Combiner.
ComputeNumSignBitsForTargetNode - This method can be implemented by targets that want to expose additional information about sign bits to the DAG Combiner.
Reimplemented in llvm::AMDGPUTargetLowering, and llvm::X86TargetLowering.
Definition at line 1105 of file TargetLowering.cpp.
References llvm::ISD::BUILTIN_OP_END, llvm::SDValue::getOpcode(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, and llvm::ISD::INTRINSIC_WO_CHAIN.
createFastISel()
virtual FastISel * llvm::TargetLowering::createFastISel (FunctionLoweringInfo & , const TargetLibraryInfo *) const inline virtual
This method returns a target specific FastISel object, or null if the target does not support "fast" ISel.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::MipsTargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 2571 of file TargetLowering.h.
Referenced by llvm::MipsTargetLowering::createFastISel().
EmitInstrWithCustomInserter()
MachineBasicBlock * TargetLowering::EmitInstrWithCustomInserter (MachineInstr * MI, MachineBasicBlock * MBB) const virtual
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag. These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::Mips16TargetLowering, llvm::MipsSETargetLowering, llvm::MipsTargetLowering, llvm::MSP430TargetLowering, llvm::PPCTargetLowering, llvm::R600TargetLowering, llvm::SITargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 319 of file SelectionDAGISel.cpp.
References llvm::dbgs(), and llvm_unreachable.
Referenced by llvm::R600TargetLowering::EmitInstrWithCustomInserter(), and llvm::SITargetLowering::EmitInstrWithCustomInserter().
expandFP_TO_SINT()
bool TargetLowering::expandFP_TO_SINT (SDNode * N, SDValue & Result, SelectionDAG & DAG) const
Expand float(f32) to SINT(i64) conversion
Parameters
N Node to expand
Result output after conversion
Returns
True, if the expansion was successful, false otherwise
Definition at line 2901 of file TargetLowering.cpp.
References llvm::ISD::AND, llvm::ISD::BITCAST, llvm::MVT::f32, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSelectCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::APInt::getSignBit(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::MVT::i64, llvm::ISD::OR, llvm::ISD::SETGT, llvm::ISD::SETLT, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, and llvm::ISD::XOR.
Referenced by llvm::R600TargetLowering::ReplaceNodeResults().
ExpandInlineAsm()
virtual bool llvm::TargetLowering::ExpandInlineAsm (CallInst *) const inline virtual
This hook allows the target to expand an inline asm call to be explicit llvm code if it wants to. This is useful for turning simple inline asms into LLVM intrinsics, which gives the compiler more information about the behavior of the code.
Reimplemented in llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 2588 of file TargetLowering.h.
expandMUL()
bool TargetLowering::expandMUL (SDNode * N, SDValue & Lo, SDValue & Hi, EVT HiLoVT, SelectionDAG & DAG, SDValue LL = SDValue(), SDValue LH = SDValue(), SDValue RL = SDValue(), SDValue RH = SDValue()) const
Expand a MUL into two nodes. One that computes the high bits of the result and one that computes the low bits.
Parameters
HiLoVT The value type to use for the Lo and Hi nodes.
LL Low bits of the LHS of the MUL. You can use this parameter if you want to control how low bits are extracted from the LHS.
LH High bits of the LHS of the MUL. See LL for meaning.
RL Low bits of the RHS of the MUL. See LL for meaning
RH High bits of the RHS of the MUL. See LL for meaning.
Returns
true if the node has been expanded. false if it has not
Definition at line 2798 of file TargetLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::ComputeNumSignBits(), llvm::SelectionDAG::getConstant(), llvm::APInt::getHighBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, N, llvm::ISD::SMUL_LOHI, llvm::ISD::SRL, llvm::ISD::TRUNCATE, and llvm::ISD::UMUL_LOHI.
functionArgumentNeedsConsecutiveRegisters()
virtual bool llvm::TargetLowering::functionArgumentNeedsConsecutiveRegisters (Type * Ty, CallingConv::ID CallConv, bool isVarArg) const inline virtual
For some targets, an LLVM struct type must be broken down into multiple simple types, but the calling convention specifies that the entire struct must be passed in a block of consecutive registers.
Reimplemented in llvm::ARMTargetLowering, and llvm::PPCTargetLowering.
Definition at line 2504 of file TargetLowering.h.
Referenced by LowerCallTo().
getClearCacheBuiltinName()
virtual const char * llvm::TargetLowering::getClearCacheBuiltinName () const inline virtual
Return the builtin name for the __builtin___clear_cache intrinsic Default is to invoke the clear cache library call
Reimplemented in llvm::X86TargetLowering.
Definition at line 2477 of file TargetLowering.h.
getConstraintType()
TargetLowering::ConstraintType TargetLowering::getConstraintType (const std::string & Constraint) const virtual
Given a constraint, return the type of constraint it is for this target.
Reimplemented in llvm::ARMTargetLowering, llvm::MSP430TargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 2066 of file TargetLowering.cpp.
References C_Memory, C_Other, C_Register, C_RegisterClass, and C_Unknown.
Referenced by ChooseConstraint(), ComputeConstraintToUse(), llvm::ARMTargetLowering::getConstraintType(), llvm::MSP430TargetLowering::getConstraintType(), llvm::NVPTXTargetLowering::getConstraintType(), llvm::PPCTargetLowering::getConstraintType(), llvm::SparcTargetLowering::getConstraintType(), llvm::SystemZTargetLowering::getConstraintType(), llvm::X86TargetLowering::getConstraintType(), and llvm::hasInlineAsmMemConstraint().
getJumpTableEncoding()
unsigned TargetLowering::getJumpTableEncoding () const virtual
Return the entry encoding for a jump table in the current function. The returned value is a member of the MachineJumpTableInfo::JTEntryKind enum.
getJumpTableEncoding - Return the entry encoding for a jump table in the current function. The returned value is a member of the MachineJumpTableInfo::JTEntryKind enum.
Reimplemented in llvm::ARMTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 223 of file TargetLowering.cpp.
References llvm::MachineJumpTableInfo::EK_BlockAddress, llvm::MachineJumpTableInfo::EK_GPRel32BlockAddress, llvm::MachineJumpTableInfo::EK_LabelDifference32, llvm::TargetLoweringBase::getTargetMachine(), and llvm::Reloc::PIC_.
Referenced by llvm::X86TargetLowering::getJumpTableEncoding(), and getPICJumpTableRelocBase().
getMultipleConstraintMatchWeight()
TargetLowering::ConstraintWeight TargetLowering::getMultipleConstraintMatchWeight (AsmOperandInfo & info, int maIndex) const virtual
Examine constraint type and operand type and determine a weight value. The operand object must already have been set up with the operand type.
Examine constraint type and operand type and determine a weight value. This object must already have been set up with the operand type and the current alternative constraint selected.
Definition at line 2458 of file TargetLowering.cpp.
References llvm::c_str(), CW_Invalid, getSingleConstraintMatchWeight(), and info.
Referenced by ParseConstraints().
getPICJumpTableRelocBase()
SDValue TargetLowering::getPICJumpTableRelocBase (SDValue Table, SelectionDAG & DAG) const virtual
Returns relocation base for the given PIC jumptable.
Reimplemented in llvm::X86TargetLowering.
Definition at line 236 of file TargetLowering.cpp.
References llvm::MachineJumpTableInfo::EK_GPRel32BlockAddress, llvm::MachineJumpTableInfo::EK_GPRel64BlockAddress, llvm::SelectionDAG::getGLOBAL_OFFSET_TABLE(), getJumpTableEncoding(), and llvm::TargetLoweringBase::getPointerTy().
getPICJumpTableRelocBaseExpr()
const MCExpr * TargetLowering::getPICJumpTableRelocBaseExpr (const MachineFunction * MF, unsigned JTI, MCContext & Ctx) const virtual
This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
getPICJumpTableRelocBaseExpr - This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
Reimplemented in llvm::X86TargetLowering.
Definition at line 252 of file TargetLowering.cpp.
References llvm::MCSymbolRefExpr::Create(), and llvm::MachineFunction::getJTISymbol().
Referenced by llvm::AsmPrinter::EmitJumpTableInfo(), and llvm::X86TargetLowering::getPICJumpTableRelocBaseExpr().
getPostIndexedAddressParts()
virtual bool llvm::TargetLowering::getPostIndexedAddressParts (SDNode * , SDNode * , SDValue & , SDValue & , ISD::MemIndexedMode & , SelectionDAG &) const inline virtual
Returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
Reimplemented in llvm::ARMTargetLowering, and llvm::HexagonTargetLowering.
Definition at line 2042 of file TargetLowering.h.
getPreIndexedAddressParts()
virtual bool llvm::TargetLowering::getPreIndexedAddressParts (SDNode * , SDValue & , SDValue & , ISD::MemIndexedMode & , SelectionDAG &) const inline virtual
Returns true by value, base pointer and offset pointer and addressing mode by reference if the node's address can be legally represented as pre-indexed load / store address.
Reimplemented in llvm::ARMTargetLowering, and llvm::PPCTargetLowering.
Definition at line 2032 of file TargetLowering.h.
getRecipEstimate()
virtual SDValue llvm::TargetLowering::getRecipEstimate (SDValue Operand, DAGCombinerInfo & DCI, unsigned & RefinementSteps) const inline virtual
Return a reciprocal estimate value for the input operand. The RefinementSteps output is the number of Newton-Raphson refinement iterations required to generate a sufficient (though not necessarily IEEE-754 compliant) estimate for the value type. A target may choose to implement its own refinement within this function. If that's true, then return '0' as the number of RefinementSteps to avoid any further refinement of the estimate. An empty SDValue return means no estimate sequence can be created.
Reimplemented in llvm::AMDGPUTargetLowering.
Definition at line 2754 of file TargetLowering.h.
getRegForInlineAsmConstraint()
std::pair< unsigned, const TargetRegisterClass * > TargetLowering::getRegForInlineAsmConstraint (const std::string & Constraint, MVT VT) const virtual
Given a physical register constraint (e.g. {edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer..
Reimplemented in llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::MSP430TargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 2184 of file TargetLowering.cpp.
References llvm::TargetRegisterClass::begin(), llvm::TargetRegisterClass::end(), llvm::StringRef::equals_lower(), llvm::MCRegisterInfo::getName(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetLoweringBase::getTargetMachine(), llvm::TargetRegisterClass::hasType(), I, llvm::TargetLoweringBase::isLegalRC(), llvm::TargetRegisterInfo::regclass_begin(), and llvm::TargetRegisterInfo::regclass_end().
Referenced by llvm::ARMTargetLowering::getRegForInlineAsmConstraint(), llvm::HexagonTargetLowering::getRegForInlineAsmConstraint(), llvm::MSP430TargetLowering::getRegForInlineAsmConstraint(), llvm::NVPTXTargetLowering::getRegForInlineAsmConstraint(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::SparcTargetLowering::getRegForInlineAsmConstraint(), llvm::SystemZTargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), GetRegistersForValue(), and ParseConstraints().
getRegisterByName()
virtual unsigned llvm::TargetLowering::getRegisterByName (const char * RegName, EVT VT) const inline virtual
Return the register ID of the name passed in. Used by named register global variables extension. There is no target-independent behaviour so the default action is to bail.
Reimplemented in llvm::MipsTargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 2484 of file TargetLowering.h.
References llvm::report_fatal_error().
getRsqrtEstimate()
virtual SDValue llvm::TargetLowering::getRsqrtEstimate (SDValue Operand, DAGCombinerInfo & DCI, unsigned & RefinementSteps, bool & UseOneConstNR) const inline virtual
Hooks for building estimates in place of slower divisions and square roots. Return a reciprocal square root estimate value for the input operand. The RefinementSteps output is the number of Newton-Raphson refinement iterations required to generate a sufficient (though not necessarily IEEE-754 compliant) estimate for the value type. The boolean UseOneConstNR output is used to select a Newton-Raphson algorithm implementation that uses one constant or two constants. A target may choose to implement its own refinement within this function. If that's true, then return '0' as the number of RefinementSteps to avoid any further refinement of the estimate. An empty SDValue return means no estimate sequence can be created.
Reimplemented in llvm::AMDGPUTargetLowering.
Definition at line 2739 of file TargetLowering.h.
getScratchRegisters()
virtual const MCPhysReg * llvm::TargetLowering::getScratchRegisters (CallingConv::ID CC) const inline virtual
Returns a 0 terminated array of registers that can be safely used as scratch registers.
Reimplemented in llvm::AArch64TargetLowering, and llvm::PPCTargetLowering.
Definition at line 2511 of file TargetLowering.h.
getSingleConstraintMatchWeight()
TargetLowering::ConstraintWeight TargetLowering::getSingleConstraintMatchWeight (AsmOperandInfo & info, const char * constraint) const virtual
Examine constraint string and operand type and determine a weight value. The operand object must already have been set up with the operand type.
Examine constraint type and operand type and determine a weight value. This object must already have been set up with the operand type and the current alternative constraint selected.
Reimplemented in llvm::ARMTargetLowering, llvm::PPCTargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 2482 of file TargetLowering.cpp.
References CW_Constant, CW_Default, CW_Invalid, CW_Memory, CW_Register, llvm::Value::getType(), info, llvm::isa(), and llvm::Type::isIntegerTy().
Referenced by getMultipleConstraintMatchWeight(), llvm::ARMTargetLowering::getSingleConstraintMatchWeight(), llvm::PPCTargetLowering::getSingleConstraintMatchWeight(), llvm::SparcTargetLowering::getSingleConstraintMatchWeight(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), and llvm::X86TargetLowering::getSingleConstraintMatchWeight().
getTargetNodeName()
const char * TargetLowering::getTargetNodeName (unsigned Opcode) const virtual
This method returns the name of a target specific DAG node.
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::MipsTargetLowering, llvm::MSP430TargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 42 of file TargetLowering.cpp.
Referenced by llvm::SDNode::getOperationName().
getTypeForExtArgOrReturn()
virtual EVT llvm::TargetLowering::getTypeForExtArgOrReturn (LLVMContext & Context, EVT VT, ISD::NodeType) const inline virtual
Return the type that should be used to zero or sign extend a zeroext/signext integer argument or return value. FIXME: Most C calling convention requires the return type to be promoted, but this is not true all the time, e.g. i1 on x86-64. It is also not necessary for non-C calling conventions. The frontend should handle this and include all of the necessary information.
Definition at line 2494 of file TargetLowering.h.
References llvm::EVT::bitsLT(), llvm::TargetLoweringBase::getRegisterType(), and llvm::MVT::i32.
HandleByVal()
virtual void llvm::TargetLowering::HandleByVal (CCState * , unsigned & , unsigned) const inline virtual
Target-specific cleanup for formal ByVal parameters.
Reimplemented in llvm::MipsTargetLowering.
Definition at line 2433 of file TargetLowering.h.
isConstFalseVal()
bool TargetLowering::isConstFalseVal (const SDNode * N) const
Return if the N is a constant or constant vector equal to the false value from getBooleanContents().
Definition at line 1180 of file TargetLowering.cpp.
References llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), llvm::TargetLoweringBase::getBooleanContents(), llvm::BuildVectorSDNode::getConstantSplatNode(), llvm::ConstantSDNode::isNullValue(), N, llvm::BitVector::none(), and llvm::TargetLoweringBase::UndefinedBooleanContent.
isConstTrueVal()
bool TargetLowering::isConstTrueVal (const SDNode * N) const
Return if the N is a constant or constant vector equal to the true value from getBooleanContents().
Definition at line 1150 of file TargetLowering.cpp.
References llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), llvm::TargetLoweringBase::getBooleanContents(), llvm::BuildVectorSDNode::getConstantSplatNode(), llvm::ConstantSDNode::isAllOnesValue(), llvm::ConstantSDNode::isOne(), llvm_unreachable, N, llvm::BitVector::none(), llvm::TargetLoweringBase::UndefinedBooleanContent, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
isDesirableToCommuteWithShift()
virtual bool llvm::TargetLowering::isDesirableToCommuteWithShift (const SDNode * N) const inline virtual
Return true if it is profitable to move a following shift through this.
Reimplemented in llvm::AArch64TargetLowering.
Definition at line 2221 of file TargetLowering.h.
References N.
IsDesirableToPromoteOp()
virtual bool llvm::TargetLowering::IsDesirableToPromoteOp (SDValue , EVT &) const inline virtual
This method query the target whether it is beneficial for dag combiner to promote the specified node. If true, it should return the desired promotion type by reference.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2245 of file TargetLowering.h.
isDesirableToTransformToIntegerOp()
virtual bool llvm::TargetLowering::isDesirableToTransformToIntegerOp (unsigned , EVT) const inline virtual
Return true if it is profitable for dag combiner to transform a floating point op of specified opcode to a equivalent op of an integer type. e.g. f32 load -> i32 load can be profitable on ARM.
Reimplemented in llvm::ARMTargetLowering.
Definition at line 2237 of file TargetLowering.h.
isGAPlusOffset()
bool TargetLowering::isGAPlusOffset (SDNode * N, const GlobalValue *& GA, int64_t & Offset) const virtual
Returns true (and the GlobalValue and the offset) if the node is a GlobalAddress + offset.
isGAPlusOffset - Returns true (and the GlobalValue and the offset) if the node is a GlobalAddress + offset.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2023 of file TargetLowering.cpp.
References llvm::ISD::ADD, llvm::cast(), llvm::dyn_cast(), llvm::GlobalAddressSDNode::getGlobal(), llvm::SDValue::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::isa(), isGAPlusOffset(), and N.
Referenced by isConsecutiveLSLoc(), isGAPlusOffset(), and llvm::X86TargetLowering::isGAPlusOffset().
isInTailCallPosition()
bool TargetLowering::isInTailCallPosition (SelectionDAG & DAG, SDNode * Node, SDValue & Chain) const
Check whether a given call node is in tail position within its function. If so, it sets Chain to the input chain of the tail call.
Definition at line 48 of file TargetLowering.cpp.
References F, llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::AttributeSet::hasAttribute(), isUsedByReturnOnly(), llvm::Attribute::NoAlias, llvm::AttributeSet::ReturnIndex, llvm::Attribute::SExt, and llvm::Attribute::ZExt.
isOffsetFoldingLegal()
bool TargetLowering::isOffsetFoldingLegal (const GlobalAddressSDNode * GA) const virtual
Return true if folding a constant offset with the given GlobalAddress is legal. It is frequently not legal in PIC relocation models.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::PPCTargetLowering, and llvm::SparcTargetLowering.
Definition at line 259 of file TargetLowering.cpp.
References llvm::Reloc::DynamicNoPIC, llvm::GlobalAddressSDNode::getGlobal(), llvm::TargetLoweringBase::getTargetMachine(), llvm::GlobalValue::isDeclaration(), llvm::GlobalValue::isWeakForLinker(), and llvm::Reloc::Static.
isTypeDesirableForOp()
virtual bool llvm::TargetLowering::isTypeDesirableForOp (unsigned , EVT VT) const inline virtual
Return true if the target has native support for the specified value type and it is 'desirable' to use the type for the given node type. e.g. On x86 i16 is legal, but undesirable since i16 instruction encodings are longer and some i16 instructions are slow.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2229 of file TargetLowering.h.
References llvm::TargetLoweringBase::isTypeLegal().
Referenced by SimplifyDemandedBits(), and SimplifySetCC().
isUsedByReturnOnly()
virtual bool llvm::TargetLowering::isUsedByReturnOnly (SDNode * , SDValue &) const inline virtual
Return true if result of the specified node is used by a return node only. It also compute and return the input chain for the tail call.
This is used to determine whether it is possible to codegen a libcall as tail call at legalization time.
Definition at line 2464 of file TargetLowering.h.
Referenced by isInTailCallPosition().
LowerAsmOperandForConstraint()
void TargetLowering::LowerAsmOperandForConstraint (SDValue Op, std::string & Constraint, std::vector< SDValue > & Ops, SelectionDAG & DAG) const virtual
Lower the specified operand into the Ops vector. If it is invalid, don't add anything to Ops.
LowerAsmOperandForConstraint - Lower the specified operand into the Ops vector. If it is invalid, don't add anything to Ops.
Reimplemented in llvm::ARMTargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 2119 of file TargetLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::BasicBlock, llvm::dyn_cast(), llvm::GlobalAddressSDNode::getGlobal(), llvm::GlobalAddressSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValueType(), and llvm::MVT::i64.
Referenced by ChooseConstraint(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::NVPTXTargetLowering::LowerAsmOperandForConstraint(), llvm::PPCTargetLowering::LowerAsmOperandForConstraint(), llvm::SparcTargetLowering::LowerAsmOperandForConstraint(), llvm::SystemZTargetLowering::LowerAsmOperandForConstraint(), and llvm::X86TargetLowering::LowerAsmOperandForConstraint().
LowerCall()
virtual SDValue llvm::TargetLowering::LowerCall (CallLoweringInfo & , SmallVectorImpl< SDValue > &) const inline virtual
This hook must be implemented to lower calls into the the specified DAG. The outgoing arguments to the call are described by the Outs array, and the values to be returned by the call are described by the Ins array. The implementation should fill in the InVals array with legal-type return values from the call, and return the resulting token chain value.
Reimplemented in llvm::AMDGPUTargetLowering, llvm::HexagonTargetLowering, llvm::NVPTXTargetLowering, llvm::SparcTargetLowering, and llvm::SystemZTargetLowering.
Definition at line 2427 of file TargetLowering.h.
References llvm_unreachable.
Referenced by LowerCallTo().
LowerCallTo()
std::pair< SDValue, SDValue > TargetLowering::LowerCallTo (TargetLowering::CallLoweringInfo & CLI) const
This function lowers an abstract call to a function into an actual call. This returns a pair of operands. The first element is the return value for the function (if RetTy is not VoidTy). The second element is the outgoing token chain. It calls LowerCall to do the actual lowering.
TargetLowering::LowerCallTo - This is the default LowerCallTo implementation, which just calls LowerCall. FIXME: When all targets are migrated to using LowerCall, this hook should be integrated into SDISel.
Definition at line 7311 of file SelectionDAGBuilder.cpp.
References llvm::ISD::ADD, llvm::Add, Align, llvm::TargetLowering::ArgListEntry::Alignment, llvm::ISD::ANY_EXTEND, llvm::ISD::InputArg::ArgVT, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::TargetLowering::CallLoweringInfo::CallConv, CanLowerReturn(), llvm::cast(), llvm::TargetLowering::CallLoweringInfo::Chain, llvm::ComputeValueVTs(), llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetLowering::CallLoweringInfo::CS, llvm::TargetLowering::CallLoweringInfo::DAG, DEBUG, llvm::ISD::DELETED_NODE, llvm::TargetLowering::CallLoweringInfo::DL, llvm::SmallVectorBase::empty(), llvm::ISD::InputArg::Flags, llvm::ISD::OutputArg::Flags, functionArgumentNeedsConsecutiveRegisters(), llvm::TargetLowering::CallLoweringInfo::getArgs(), llvm::TargetLoweringBase::getByValTypeAlignment(), llvm::SelectionDAG::getConstant(), llvm::Type::getContext(), getCopyFromParts(), getCopyToParts(), llvm::TargetLoweringBase::getDataLayout(), llvm::SequentialType::getElementType(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegisterType(), getReturnAttrs(), llvm::GetReturnInfo(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), llvm::EVT::getTypeForEVT(), llvm::PointerType::getUnqual(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::Type::getVoidTy(), llvm::SelectionDAG::getVTList(), I, llvm::TargetLowering::CallLoweringInfo::Ins, llvm::TargetLowering::ArgListEntry::isByVal, llvm::TargetLowering::CallLoweringInfo::IsInReg, llvm::TargetLowering::ArgListEntry::isInReg, llvm::TargetLowering::ArgListEntry::isNest, llvm::TargetLowering::ArgListEntry::isReturned, llvm::TargetLowering::CallLoweringInfo::IsReturnValueUsed, llvm::TargetLowering::ArgListEntry::isSExt, llvm::TargetLowering::ArgListEntry::isSRet, llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::TargetLowering::CallLoweringInfo::IsVarArg, llvm::EVT::isVector(), llvm::TargetLowering::ArgListEntry::isZExt, LowerCall(), llvm::ISD::MERGE_VALUES, llvm::TargetLowering::ArgListEntry::Node, llvm::TargetLowering::CallLoweringInfo::NumFixedArgs, llvm::MVT::Other, llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::TargetLowering::CallLoweringInfo::RetSExt, llvm::TargetLowering::CallLoweringInfo::RetTy, llvm::TargetLowering::CallLoweringInfo::RetZExt, llvm::ISD::ArgFlagsTy::setInReg(), llvm::ISD::ArgFlagsTy::setOrigAlign(), llvm::SelectionDAG::setRoot(), llvm::ISD::ArgFlagsTy::setSExt(), llvm::ISD::ArgFlagsTy::setSplit(), llvm::ISD::ArgFlagsTy::setZExt(), llvm::ISD::SIGN_EXTEND, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::ISD::TokenFactor, llvm::TargetLowering::ArgListEntry::Ty, llvm::ISD::InputArg::Used, llvm::ISD::InputArg::VT, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerFSINCOS(), and makeLibCall().
LowerCustomJumpTableEntry()
virtual const MCExpr * llvm::TargetLowering::LowerCustomJumpTableEntry (const MachineJumpTableInfo * , const MachineBasicBlock * , unsigned , MCContext &) const inline virtual
Reimplemented in llvm::X86TargetLowering.
Definition at line 2055 of file TargetLowering.h.
References llvm_unreachable.
LowerFormalArguments()
virtual SDValue llvm::TargetLowering::LowerFormalArguments (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::InputArg > & , SDLoc , SelectionDAG & , SmallVectorImpl< SDValue > &) const inline virtual
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG. The implementation should fill in the InVals array with legal-type argument values, and return the resulting token chain value.
Reimplemented in llvm::HexagonTargetLowering, llvm::NVPTXTargetLowering, llvm::R600TargetLowering, llvm::SITargetLowering, llvm::SparcTargetLowering, and llvm::SystemZTargetLowering.
Definition at line 2260 of file TargetLowering.h.
References llvm_unreachable.
LowerOperation()
SDValue TargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const virtual
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal. If the target has no operations that require custom lowering, it need not implement this. The default implementation of this aborts.
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::MipsSETargetLowering, llvm::MipsTargetLowering, llvm::MSP430TargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::R600TargetLowering, llvm::SITargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 7582 of file SelectionDAGBuilder.cpp.
References llvm_unreachable.
Referenced by LowerOperationWrapper().
LowerOperationWrapper()
void TargetLowering::LowerOperationWrapper (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) const virtual
This callback is invoked by the type legalizer to legalize nodes with an illegal operand type but legal result types. It replaces the LowerOperation callback in the type Legalizer. The reason we can not do away with LowerOperation entirely is that LegalizeDAG isn't yet ready to use this callback.
TODO: Consider merging with ReplaceNodeResults.
The target places new result values for the node in Results (their number and types must exactly match those of the original return values of the node), or leaves Results empty, which indicates that the node is not to be custom lowered after all. The default implementation calls LowerOperation.
Reimplemented in llvm::MipsTargetLowering.
Definition at line 7574 of file SelectionDAGBuilder.cpp.
References llvm::SDValue::getNode(), LowerOperation(), N, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
LowerReturn()
virtual SDValue llvm::TargetLowering::LowerReturn (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::OutputArg > & , const SmallVectorImpl< SDValue > & , SDLoc , SelectionDAG &) const inline virtual
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG. The implementation should return the resulting token chain value.
Reimplemented in llvm::AMDGPUTargetLowering, llvm::HexagonTargetLowering, llvm::NVPTXTargetLowering, llvm::SparcTargetLowering, and llvm::SystemZTargetLowering.
Definition at line 2451 of file TargetLowering.h.
References llvm_unreachable.
LowerXConstraint()
const char * TargetLowering::LowerXConstraint (EVT ConstraintVT) const virtual
Try to replace an X constraint, which matches anything, with another that has more specific requirements based on the type of the corresponding operand. This returns null if there is no replacement to make.
LowerXConstraint - try to replace an X constraint, which matches anything, with another that has more specific requirements based on the type of the corresponding operand.
Reimplemented in llvm::X86TargetLowering.
Definition at line 2109 of file TargetLowering.cpp.
References llvm::EVT::isFloatingPoint(), and llvm::EVT::isInteger().
Referenced by ComputeConstraintToUse(), and llvm::X86TargetLowering::LowerXConstraint().
makeLibCall()
std::pair< SDValue, SDValue > TargetLowering::makeLibCall (SelectionDAG & DAG, RTLIB::Libcall LC, EVT RetVT, const SDValue * Ops, unsigned NumOps, bool isSigned, SDLoc dl, bool doesNotReturn = false, bool isReturnValueUsed = true) const
Returns a pair of (return value, chain).
Generate a libcall taking the given operands as arguments and returning a result of type RetVT.
Definition at line 86 of file TargetLowering.cpp.
References llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getExternalSymbol(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::TargetLowering::ArgListEntry::isSExt, llvm::TargetLowering::ArgListEntry::isZExt, LowerCallTo(), llvm::TargetLowering::ArgListEntry::Node, llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), llvm::TargetLowering::CallLoweringInfo::setNoReturn(), llvm::TargetLowering::CallLoweringInfo::setSExtResult(), llvm::TargetLowering::CallLoweringInfo::setZExtResult(), shouldSignExtendTypeInLibCall(), and llvm::TargetLowering::ArgListEntry::Ty.
Referenced by LowerUMULO_SMULO(), softenSetCCOperands(), and llvm::SelectionDAGBuilder::visitSPDescriptorFailure().
mayBeEmittedAsTailCall()
virtual bool llvm::TargetLowering::mayBeEmittedAsTailCall (CallInst *) const inline virtual
Return true if the target may be able emit the call instruction as a tail call. This is used by optimization passes to determine if it's profitable to duplicate return instructions to enable tailcall optimization.
Reimplemented in llvm::SystemZTargetLowering.
Definition at line 2471 of file TargetLowering.h.
ParseConstraints()
TargetLowering::AsmOperandInfoVector TargetLowering::ParseConstraints (ImmutableCallSite CS) const virtual
Split up the constraint string from the inline assembly value into the specific constraints and their prefixes, and also tie in the associated operand values. If this returns an empty vector, and if the constraint string itself isn't empty, there was an error parsing.
ParseConstraints - Split up the constraint string from the inline assembly value into the specific constraints and their prefixes, and also tie in the associated operand values. If this returns an empty vector, and if the constraint string itself isn't empty, there was an error parsing.
ConstraintOperands - Information about all of the constraints.
Definition at line 2252 of file TargetLowering.cpp.
References llvm::TargetLowering::AsmOperandInfo::CallOperandVal, llvm::cast(), llvm::TargetLowering::AsmOperandInfo::ConstraintCode, llvm::TargetLowering::AsmOperandInfo::ConstraintVT, llvm::dyn_cast(), llvm::IntegerType::get(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), llvm::Type::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::SequentialType::getElementType(), llvm::MVT::getIntegerVT(), getMultipleConstraintMatchWeight(), llvm::DataLayout::getPointerSizeInBits(), getRegForInlineAsmConstraint(), llvm::TargetLoweringBase::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), llvm::MVT::getVT(), llvm::InlineAsm::ConstraintInfo::hasMatchingInput(), llvm::InlineAsm::isClobber, llvm::InlineAsm::ConstraintInfo::isIndirect, llvm::InlineAsm::isInput, llvm::MVT::isInteger(), llvm::InlineAsm::isOutput, llvm::Type::isSingleValueType(), llvm::Type::isSized(), llvm::Type::isVoidTy(), llvm::InlineAsm::ConstraintInfo::MatchingInput, llvm::InlineAsm::ConstraintInfo::multipleAlternatives, llvm::MVT::Other, llvm::InlineAsm::ParseConstraints(), llvm::report_fatal_error(), llvm::InlineAsm::ConstraintInfo::selectAlternative(), and llvm::InlineAsm::ConstraintInfo::Type.
PerformDAGCombine()
SDValue TargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const virtual
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::MipsSETargetLowering, llvm::MipsTargetLowering, llvm::PPCTargetLowering, llvm::R600TargetLowering, llvm::SITargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 2054 of file TargetLowering.cpp.
References N.
prepareVolatileOrAtomicLoad()
virtual SDValue llvm::TargetLowering::prepareVolatileOrAtomicLoad (SDValue Chain, SDLoc DL, SelectionDAG & DAG) const inline virtual
This callback is used to prepare for a volatile or atomic load. It takes a chain node as input and returns the chain for the load itself.
Having a callback like this is necessary for targets like SystemZ, which allows a CPU to reuse the result of a previous load indefinitely, even if a cache-coherent store is performed by another CPU. The default implementation does nothing.
Reimplemented in llvm::SystemZTargetLowering.
Definition at line 2522 of file TargetLowering.h.
ReplaceNodeResults()
virtual void llvm::TargetLowering::ReplaceNodeResults (SDNode * , SmallVectorImpl< SDValue > & , SelectionDAG &) const inline virtual
This callback is invoked when a node result type is illegal for the target, and the operation was registered to use 'custom' lowering for that result type. The target places new result values for the node in Results (their number and types must exactly match those of the original return values of the node), or leaves Results empty, which indicates that the node is not to be custom lowered after all.
If the target has no operations that require custom lowering, it need not implement this. The default implementation aborts.
Reimplemented in llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::MipsTargetLowering, llvm::PPCTargetLowering, llvm::R600TargetLowering, llvm::SparcTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 2560 of file TargetLowering.h.
References llvm_unreachable.
shouldSignExtendTypeInLibCall()
virtual bool llvm::TargetLowering::shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const inline virtual
Returns true if arguments should be sign-extended in lib calls.
Definition at line 2811 of file TargetLowering.h.
Referenced by makeLibCall().
SimplifyDemandedBits()
bool TargetLowering::SimplifyDemandedBits (SDValue Op, const APInt & DemandedMask, APInt & KnownZero, APInt & KnownOne, TargetLoweringOpt & TLO, unsigned Depth = 0) const
Look at Op. At this point, we know that only the DemandedMask bits of the result of Op are ever used downstream. If we can use this information to simplify Op, create a new simplified DAG node and return true, returning the original and new nodes in Old and New. Otherwise, analyze the expression and return a mask of KnownOne and KnownZero bits for the expression (used to simplify the caller). The KnownZero/One bits may only be accurate for those bits in the DemandedMask.
SimplifyDemandedBits - Look at Op. At this point, we know that only the DemandedMask bits of the result of Op are ever used downstream. If we can use this information to simplify Op, create a new simplified DAG node and return true, returning the original and new nodes in Old and New. Otherwise, analyze the expression and return a mask of KnownOne and KnownZero bits for the expression (used to simplify the caller). The KnownZero/One bits may only be accurate for those bits in the DemandedMask.
Definition at line 373 of file TargetLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::AssertZext, llvm::ISD::BITCAST, llvm::ISD::BUILD_PAIR, llvm::cast(), llvm::TargetLowering::TargetLoweringOpt::CombineTo(), llvm::SelectionDAG::computeKnownBits(), llvm::ISD::Constant, llvm::TargetLowering::TargetLoweringOpt::DAG, llvm::dyn_cast(), llvm::ISD::FGETSIGN, llvm::APInt::getAllOnesValue(), llvm::APInt::getBitsSet(), llvm::APInt::getBitWidth(), llvm::SelectionDAG::getConstant(), llvm::APInt::getHiBits(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLoBits(), llvm::APInt::getLowBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getOperand(), llvm::EVT::getScalarSizeInBits(), llvm::EVT::getScalarType(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::APInt::getSignBit(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNode::hasOneUse(), llvm::SDValue::hasOneUse(), llvm::MVT::i32, llvm::APInt::intersects(), llvm::isa(), llvm::APInt::isAllOnesValue(), llvm::EVT::isFloatingPoint(), llvm::isIntN(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::EVT::isSimple(), isTypeDesirableForOp(), llvm::EVT::isVector(), llvm::TargetLowering::TargetLoweringOpt::LegalOperations(), llvm::TargetLowering::TargetLoweringOpt::LegalTypes(), llvm::APInt::lshr(), llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SHL, llvm::APInt::shl(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedConstant(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, SimplifyDemandedBits(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UNDEF, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::APInt::zext().
Referenced by PerformBTCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), PerformSELECTCombine(), SimplifyDemandedBits(), and simplifyI24().
SimplifySetCC()
SDValue TargetLowering::SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo & DCI, SDLoc dl) const
Try to simplify a setcc built with the specified operands and cc. If it is unable to simplify it, return a null SDValue.
SimplifySetCC - Try to simplify a setcc built with the specified operands and cc. If it is unable to simplify it, return a null SDValue.
Definition at line 1207 of file TargetLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::AssertZext, llvm::EVT::bitsGT(), llvm::EVT::bitsLE(), llvm::EVT::bitsLT(), llvm::cast(), llvm::ISD::Constant, llvm::APInt::countTrailingOnes(), llvm::APInt::countTrailingZeros(), llvm::ISD::CTLZ, llvm::ISD::CTPOP, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), llvm::SelectionDAG::FoldSetCC(), llvm::APInt::getActiveBits(), llvm::MemSDNode::getAlignment(), llvm::APInt::getAllOnesValue(), llvm::LoadSDNode::getBasePtr(), llvm::APInt::getBitWidth(), llvm::TargetLoweringBase::getBooleanContents(), llvm::SelectionDAG::getBoolExtOrTrunc(), llvm::MemSDNode::getChain(), llvm::TargetLoweringBase::getCondCodeAction(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::LoadSDNode::getExtensionType(), llvm::APInt::getHighBitsSet(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::APInt::getLowBitsSet(), llvm::APInt::getMaxValue(), llvm::MemSDNode::getMemoryVT(), llvm::APInt::getMinSignedBits(), llvm::APInt::getMinValue(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::APInt::getNumSignBits(), llvm::SDNode::getOpcode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getSetCC(), llvm::ISD::getSetCCInverse(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::ISD::getSetCCSwappedOperands(), llvm::APInt::getSExtValue(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::ISD::getUnorderedFlavor(), llvm::SDValue::getValueSizeInBits(), llvm::SDNode::getValueType(), llvm::SDValue::getValueType(), llvm::MachinePointerInfo::getWithOffset(), llvm::SDNode::hasOneUse(), llvm::SDValue::hasOneUse(), llvm::MVT::i1, llvm::APInt::intersects(), llvm::isa(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm::TargetLowering::DAGCombinerInfo::isCalledByLegalizer(), llvm::SelectionDAG::isCommutativeBinOp(), llvm::TargetLoweringBase::isCondCodeLegal(), llvm::EVT::isInteger(), llvm::TargetLoweringBase::isLegalICmpImmediate(), llvm::TargetLoweringBase::isLittleEndian(), llvm::APInt::isNegative(), llvm::APInt::isNonNegative(), llvm::TargetLoweringBase::isOperationLegal(), llvm::APInt::isPowerOf2(), llvm::EVT::isRound(), llvm::ISD::isSignedIntSetCC(), llvm::ISD::isTrueWhenEqual(), isTypeDesirableForOp(), llvm::TargetLoweringBase::isTypeLegal(), llvm::LSBaseSDNode::isUnindexed(), llvm::MemSDNode::isVolatile(), llvm::TargetLoweringBase::Legal, llvm_unreachable, llvm::Log2_32(), llvm::Log2_32_Ceil(), llvm::APInt::logBase2(), llvm::APInt::lshr(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::MinAlign(), llvm::ISD::NON_EXTLOAD, llvm::ISD::OR, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETFALSE, llvm::ISD::SETFALSE2, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETTRUE, llvm::ISD::SETTRUE2, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, Signed, llvm::ISD::SRL, llvm::ISD::SUB, llvm::Sub, llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::TargetLoweringBase::UndefinedBooleanContent, ValueHasExactlyOneBitSet(), llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, and llvm::ISD::ZEXTLOAD.
softenSetCCOperands()
void TargetLowering::softenSetCCOperands (SelectionDAG & DAG, EVT VT, SDValue & NewLHS, SDValue & NewRHS, ISD::CondCode & CCCode, SDLoc dl) const
SoftenSetCCOperands - Soften the operands of a comparison. This code is shared among BR_CC, SELECT_CC, and SETCC handlers.
Definition at line 118 of file TargetLowering.cpp.
References llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::TargetLoweringBase::getCmpLibcallCC(), llvm::TargetLoweringBase::getCmpLibcallReturnType(), llvm::SelectionDAG::getCondCode(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::SDValue::getValueType(), llvm_unreachable, makeLibCall(), llvm::RTLIB::O_F128, llvm::RTLIB::O_F32, llvm::RTLIB::O_F64, llvm::RTLIB::OEQ_F128, llvm::RTLIB::OEQ_F32, llvm::RTLIB::OEQ_F64, llvm::RTLIB::OGE_F128, llvm::RTLIB::OGE_F32, llvm::RTLIB::OGE_F64, llvm::RTLIB::OGT_F128, llvm::RTLIB::OGT_F32, llvm::RTLIB::OGT_F64, llvm::RTLIB::OLE_F128, llvm::RTLIB::OLE_F32, llvm::RTLIB::OLE_F64, llvm::RTLIB::OLT_F128, llvm::RTLIB::OLT_F32, llvm::RTLIB::OLT_F64, llvm::ISD::OR, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::RTLIB::UNE_F128, llvm::RTLIB::UNE_F32, llvm::RTLIB::UNE_F64, llvm::RTLIB::UNKNOWN_LIBCALL, llvm::RTLIB::UO_F128, llvm::RTLIB::UO_F32, and llvm::RTLIB::UO_F64.
useLoadStackGuardNode()
virtual bool llvm::TargetLowering::useLoadStackGuardNode () const inline virtual
If this function returns true, SelectionDAGBuilder emits a LOAD_STACK_GUARD node when it is lowering Intrinsic::stackprotector.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 2806 of file TargetLowering.h.
Referenced by llvm::SelectionDAGBuilder::visitSPDescriptorParent().
verifyReturnAddressArgumentIsConstant()
bool TargetLowering::verifyReturnAddressArgumentIsConstant (SDValue Op, SelectionDAG & DAG) const
Definition at line 2783 of file TargetLowering.cpp.
References llvm::LLVMContext::emitError(), llvm::SelectionDAG::getContext(), llvm::SDValue::getOperand(), and llvm::isa().
Referenced by llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), and LowerRETURNADDR().
The documentation for this class was generated from the following files:
TargetLowering.h
SelectionDAGBuilder.cpp
SelectionDAGISel.cpp
TargetLowering.cpp