LLVM: llvm::OnDiskIterableChainedHashTable< Info >::key_iterator Class Reference
LLVM API Documentation
llvm::OnDiskIterableChainedHashTable< Info >::key_iterator Class Reference
Iterates over all of the keys in the table.
#include <OnDiskHashTable.h>
Public Types
typedef external_key_type value_type
Public Member Functions
key_iterator (const unsigned char *const Ptr, offset_type NumEntries, Info *InfoObj)
key_iterator ()
key_iterator & operator++ ()
key_iterator operator++ (int)
value_type operator* () const
Friends
bool operator== (const key_iterator &X, const key_iterator &Y)
bool operator!= (const key_iterator &X, const key_iterator &Y)
Detailed Description
template<typename Info>
class llvm::OnDiskIterableChainedHashTable< Info >::key_iterator
Iterates over all of the keys in the table.
Definition at line 394 of file OnDiskHashTable.h.
Member Typedef Documentation
value_type
template<typename Info> typedef external_key_type llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::value_type
Definition at line 401 of file OnDiskHashTable.h.
Constructor & Destructor Documentation
key_iterator() [1/2]
template<typename Info> llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::key_iterator (const unsigned char *const Ptr, offset_type NumEntries, Info * InfoObj) inline
Definition at line 403 of file OnDiskHashTable.h.
Referenced by operator!=, operator++(), operator++(), and operator==.
key_iterator() [2/2]
template<typename Info> llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::key_iterator () inline
Definition at line 407 of file OnDiskHashTable.h.
Member Function Documentation
operator*()
template<typename Info> value_type llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::operator* () const inline
Definition at line 441 of file OnDiskHashTable.h.
operator++() [1/2]
template<typename Info> key_iterator & llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::operator++ () inline
Definition at line 418 of file OnDiskHashTable.h.
References key_iterator(), and llvm::support::endian::readNext().
operator++() [2/2]
template<typename Info> key_iterator llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::operator++ (int) inline
Definition at line 437 of file OnDiskHashTable.h.
References key_iterator().
Friends And Related Symbol Documentation
operator!=
template<typename Info> bool operator!= (const key_iterator & X, const key_iterator & Y) friend
Definition at line 414 of file OnDiskHashTable.h.
References key_iterator(), llvm::X, and Y.
operator==
template<typename Info> bool operator== (const key_iterator & X, const key_iterator & Y) friend
Definition at line 411 of file OnDiskHashTable.h.
References key_iterator(), llvm::X, and Y.
The documentation for this class was generated from the following file:
OnDiskHashTable.h