LLVM: llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator Class Reference
LLVM API Documentation
llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator Class Reference
#include <DenseSet.h>
Public Types
typedef MapTy::const_iterator::difference_type difference_type
typedef ValueT value_type
typedef value_type * pointer
typedef value_type & reference
typedef std::forward_iterator_tag iterator_category
Public Member Functions
ConstIterator (const typename MapTy::const_iterator &i)
const ValueT & operator* ()
const ValueT * operator-> ()
ConstIterator & operator++ ()
bool operator== (const ConstIterator &X) const
bool operator!= (const ConstIterator &X) const
Friends
class DenseSet
Detailed Description
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>>
class llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator
Definition at line 99 of file DenseSet.h.
Member Typedef Documentation
difference_type
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef MapTy::const_iterator::difference_type llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::difference_type
Definition at line 103 of file DenseSet.h.
iterator_category
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef std::forward_iterator_tag llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::iterator_category
Definition at line 107 of file DenseSet.h.
pointer
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef value_type* llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::pointer
Definition at line 105 of file DenseSet.h.
reference
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef value_type& llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::reference
Definition at line 106 of file DenseSet.h.
value_type
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef ValueT llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::value_type
Definition at line 104 of file DenseSet.h.
Constructor & Destructor Documentation
ConstIterator()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::ConstIterator (const typename MapTy::const_iterator & i) inline
Definition at line 109 of file DenseSet.h.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
operator!=()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> bool llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::operator!= (const ConstIterator & X) const inline
Definition at line 116 of file DenseSet.h.
References ConstIterator(), and llvm::X.
operator*()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> const ValueT & llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::operator* () inline
Definition at line 111 of file DenseSet.h.
operator++()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> ConstIterator & llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::operator++ () inline
Definition at line 114 of file DenseSet.h.
References ConstIterator().
operator->()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> const ValueT * llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::operator-> () inline
Definition at line 112 of file DenseSet.h.
operator==()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> bool llvm::DenseSet< ValueT, ValueInfoT >::ConstIterator::operator== (const ConstIterator & X) const inline
Definition at line 115 of file DenseSet.h.
References ConstIterator(), and llvm::X.
Friends And Related Symbol Documentation
DenseSet
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> friend class DenseSet friend
Definition at line 101 of file DenseSet.h.
References DenseSet.
Referenced by DenseSet.
The documentation for this class was generated from the following file:
DenseSet.h