LLVM: llvm::coverage::FunctionRecordIterator Class Reference
LLVM API Documentation
llvm::coverage::FunctionRecordIterator Class Reference
Iterator over Functions, optionally filtered to a single file.
#include <CoverageMapping.h>
Public Member Functions
FunctionRecordIterator (ArrayRef< FunctionRecord > Records_, StringRef Filename="")
FunctionRecordIterator ()
bool operator== (const FunctionRecordIterator &RHS) const
const FunctionRecord & operator* () const
FunctionRecordIterator & operator++ ()
Public Member Functions inherited from llvm::iterator_facade_base< FunctionRecordIterator, std::forward_iterator_tag, FunctionRecord >
FunctionRecordIterator operator+ (std::ptrdiff_t n) const
FunctionRecordIterator operator- (std::ptrdiff_t n) const
FunctionRecordIterator & operator++ ()
FunctionRecordIterator & operator-- ()
bool operator!= (const FunctionRecordIterator &RHS) const
bool operator> (const FunctionRecordIterator &RHS) const
bool operator<= (const FunctionRecordIterator &RHS) const
bool operator>= (const FunctionRecordIterator &RHS) const
FunctionRecord * operator-> () const
FunctionRecord & operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Protected Types inherited from llvm::iterator_facade_base< FunctionRecordIterator, std::forward_iterator_tag, FunctionRecord >
enum
Detailed Description
Iterator over Functions, optionally filtered to a single file.
Definition at line 245 of file CoverageMapping.h.
Constructor & Destructor Documentation
FunctionRecordIterator() [1/2]
llvm::coverage::FunctionRecordIterator::FunctionRecordIterator (ArrayRef< FunctionRecord > Records_, StringRef Filename = "") inline
Definition at line 256 of file CoverageMapping.h.
Referenced by operator++(), and operator==().
FunctionRecordIterator() [2/2]
llvm::coverage::FunctionRecordIterator::FunctionRecordIterator () inline
Definition at line 262 of file CoverageMapping.h.
Member Function Documentation
operator*()
const FunctionRecord & llvm::coverage::FunctionRecordIterator::operator* () const inline
Definition at line 268 of file CoverageMapping.h.
operator++()
FunctionRecordIterator & llvm::coverage::FunctionRecordIterator::operator++ () inline
Definition at line 270 of file CoverageMapping.h.
References FunctionRecordIterator().
operator==()
bool llvm::coverage::FunctionRecordIterator::operator== (const FunctionRecordIterator & RHS) const inline
Definition at line 264 of file CoverageMapping.h.
References FunctionRecordIterator().
The documentation for this class was generated from the following files:
CoverageMapping.h
CoverageMapping.cpp