LLVM: llvm::CallbackVH Class Reference
LLVM API Documentation
llvm::CallbackVH Class Reference
Value handle with callbacks on RAUW and destruction.
#include <ValueHandle.h>
Public Member Functions
CallbackVH ()
CallbackVH (Value *P)
operator Value * () const
virtual void deleted ()
Callback for Value destruction.
virtual void allUsesReplacedWith (Value *)
Callback for Value RAUW.
Public Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (HandleBaseKind Kind)
ValueHandleBase (HandleBaseKind Kind, Value *V)
ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase &RHS)
~ValueHandleBase ()
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
Value * operator-> () const
Value & operator* () const
Protected Member Functions
CallbackVH (const CallbackVH &RHS)
virtual ~CallbackVH ()
void setValPtr (Value *P)
Protected Member Functions inherited from llvm::ValueHandleBase
Value * getValPtr () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::ValueHandleBase
static void ValueIsDeleted (Value *V)
static void ValueIsRAUWd (Value *Old, Value *New)
Protected Types inherited from llvm::ValueHandleBase
enum HandleBaseKind { Assert , Callback , Tracking , Weak }
This indicates what sub class the handle actually is.
Static Protected Member Functions inherited from llvm::ValueHandleBase
static bool isValid (Value *V)
Detailed Description
Value handle with callbacks on RAUW and destruction.
This is a value handle that allows subclasses to define callbacks that run when the underlying Value has RAUW called on it or is destroyed. This class can be used as the key of a map, as long as the user takes it out of the map before calling setValPtr() (since the map has to rearrange itself when the pointer changes). Unlike ValueHandleBase, this class has a vtable and a virtual destructor.
Definition at line 342 of file ValueHandle.h.
Constructor & Destructor Documentation
CallbackVH() [1/3]
llvm::CallbackVH::CallbackVH (const CallbackVH & RHS) inline protected
Definition at line 345 of file ValueHandle.h.
References llvm::ValueHandleBase::Callback, and CallbackVH().
Referenced by CallbackVH(), llvm::IVStrideUse::IVStrideUse(), llvm::MMIAddrLabelMapCallbackPtr::MMIAddrLabelMapCallbackPtr(), and llvm::SCEVUnknown::ScalarEvolution.
~CallbackVH()
virtual llvm::CallbackVH::~CallbackVH () inline protected virtual
Definition at line 348 of file ValueHandle.h.
CallbackVH() [2/3]
llvm::CallbackVH::CallbackVH () inline
Definition at line 355 of file ValueHandle.h.
References llvm::ValueHandleBase::Callback.
CallbackVH() [3/3]
llvm::CallbackVH::CallbackVH (Value * P) inline
Definition at line 356 of file ValueHandle.h.
References llvm::ValueHandleBase::Callback, P, and llvm::ValueHandleBase::Value.
Member Function Documentation
allUsesReplacedWith()
virtual void llvm::CallbackVH::allUsesReplacedWith (Value *) inline virtual
Callback for Value RAUW.
Called when this->getValPtr()->replaceAllUsesWith(new_value) is called, before any of the uses have actually been replaced. If WeakVH were implemented as a CallbackVH, it would use this method to call setValPtr(new_value). AssertingVH would do nothing in this method.
Reimplemented in llvm::MMIAddrLabelMapCallbackPtr, and llvm::ValueMapCallbackVH< KeyT, ValueT, Config >.
Definition at line 380 of file ValueHandle.h.
References llvm::ValueHandleBase::Value.
deleted()
virtual void llvm::CallbackVH::deleted () inline virtual
Callback for Value destruction.
Called when this->getValPtr() is destroyed, inside ~Value(), so you may call any non-virtual Value method on getValPtr(), but no subclass methods. If WeakVH were implemented as a CallbackVH, it would use this method to call setValPtr(NULL). AssertingVH would use this method to cause an assertion failure.
All implementations must remove the reference from this object to the Value that's being destroyed.
Reimplemented in llvm::MMIAddrLabelMapCallbackPtr, and llvm::ValueMapCallbackVH< KeyT, ValueT, Config >.
Definition at line 372 of file ValueHandle.h.
References setValPtr().
operator Value *()
llvm::CallbackVH::operator Value * () const inline
Definition at line 358 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr(), and llvm::ValueHandleBase::Value.
setValPtr()
void llvm::CallbackVH::setValPtr (Value * P) inline protected
Definition at line 350 of file ValueHandle.h.
References llvm::ValueHandleBase::operator=(), P, and llvm::ValueHandleBase::Value.
Referenced by deleted(), and llvm::IVStrideUse::setUser().
The documentation for this class was generated from the following files:
ValueHandle.h
Value.cpp