LLVM: llvm::ImmutableListFactory< T > Class Template Reference
LLVM API Documentation
llvm::ImmutableListFactory< T > Class Template Reference
#include <ImmutableList.h>
Public Member Functions
ImmutableListFactory ()
ImmutableListFactory (BumpPtrAllocator &Alloc)
~ImmutableListFactory ()
ImmutableList< T > concat (const T &Head, ImmutableList< T > Tail)
ImmutableList< T > add (const T &D, ImmutableList< T > L)
ImmutableList< T > getEmptyList () const
ImmutableList< T > create (const T &X)
Detailed Description
template<typename T>
class llvm::ImmutableListFactory< T >
Definition at line 140 of file ImmutableList.h.
Constructor & Destructor Documentation
ImmutableListFactory() [1/2]
template<typename T> llvm::ImmutableListFactory< T >::ImmutableListFactory () inline
Definition at line 156 of file ImmutableList.h.
ImmutableListFactory() [2/2]
template<typename T> llvm::ImmutableListFactory< T >::ImmutableListFactory (BumpPtrAllocator & Alloc) inline
Definition at line 159 of file ImmutableList.h.
~ImmutableListFactory()
template<typename T> llvm::ImmutableListFactory< T >::~ImmutableListFactory () inline
Definition at line 162 of file ImmutableList.h.
Member Function Documentation
add()
template<typename T> ImmutableList< T > llvm::ImmutableListFactory< T >::add (const T & D, ImmutableList< T > L) inline
Definition at line 188 of file ImmutableList.h.
References concat(), and T.
concat()
template<typename T> ImmutableList< T > llvm::ImmutableListFactory< T >::concat (const T & Head, ImmutableList< T > Tail) inline
Definition at line 166 of file ImmutableList.h.
References llvm::ImmutableListImpl< T >::Profile(), llvm::Registry< T, U >::Head, llvm::Registry< T, U >::Tail, and T.
Referenced by add().
create()
template<typename T> ImmutableList< T > llvm::ImmutableListFactory< T >::create (const T & X) inline
Definition at line 196 of file ImmutableList.h.
References getEmptyList(), T, and llvm::X.
getEmptyList()
template<typename T> ImmutableList< T > llvm::ImmutableListFactory< T >::getEmptyList () const inline
Definition at line 192 of file ImmutableList.h.
Referenced by create().
The documentation for this class was generated from the following file:
ImmutableList.h