LLVM: llvm::sys::fs::directory_entry Class Reference
LLVM API Documentation
llvm::sys::fs::directory_entry Class Reference
#include <FileSystem.h>
Public Member Functions
directory_entry (const Twine &path, file_status st=file_status())
directory_entry ()
void assign (const Twine &path, file_status st=file_status())
void replace_filename (const Twine &filename, file_status st=file_status())
const std::string & path () const
std::error_code status (file_status &result) const
bool operator== (const directory_entry &rhs) const
bool operator!= (const directory_entry &rhs) const
bool operator< (const directory_entry &rhs) const
bool operator<= (const directory_entry &rhs) const
bool operator> (const directory_entry &rhs) const
bool operator>= (const directory_entry &rhs) const
Detailed Description
directory_entry - A single entry in a directory. Caches the status either from the result of the iteration syscall, or the first time status is called.
Definition at line 677 of file FileSystem.h.
Constructor & Destructor Documentation
directory_entry() [1/2]
llvm::sys::fs::directory_entry::directory_entry (const Twine & path, file_status st = file_status()) inline explicit
Definition at line 682 of file FileSystem.h.
References path().
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
directory_entry() [2/2]
llvm::sys::fs::directory_entry::directory_entry () inline
Definition at line 686 of file FileSystem.h.
Member Function Documentation
assign()
void llvm::sys::fs::directory_entry::assign (const Twine & path, file_status st = file_status()) inline
Definition at line 688 of file FileSystem.h.
References path().
operator!=()
bool llvm::sys::fs::directory_entry::operator!= (const directory_entry & rhs) const inline
Definition at line 699 of file FileSystem.h.
References directory_entry().
operator<()
bool llvm::sys::fs::directory_entry::operator< (const directory_entry & rhs) const
References directory_entry().
operator<=()
bool llvm::sys::fs::directory_entry::operator<= (const directory_entry & rhs) const
References directory_entry().
operator==()
bool llvm::sys::fs::directory_entry::operator== (const directory_entry & rhs) const inline
Definition at line 698 of file FileSystem.h.
References directory_entry().
operator>()
bool llvm::sys::fs::directory_entry::operator> (const directory_entry & rhs) const
References directory_entry().
operator>=()
bool llvm::sys::fs::directory_entry::operator>= (const directory_entry & rhs) const
References directory_entry().
path()
const std::string & llvm::sys::fs::directory_entry::path () const inline
Definition at line 695 of file FileSystem.h.
Referenced by assign(), directory_entry(), llvm::sys::fs::directory_iterator::directory_iterator(), and replace_filename().
replace_filename()
void llvm::sys::fs::directory_entry::replace_filename (const Twine & filename, file_status st = file_status())
Definition at line 899 of file Path.cpp.
References llvm::sys::path::append(), path(), and llvm::sys::path::remove_filename().
status()
std::error_code llvm::sys::fs::directory_entry::status (file_status & result) const
Definition at line 1070 of file Path.cpp.
References llvm::sys::fs::status().
The documentation for this class was generated from the following files:
FileSystem.h
Path.cpp