LLVM: llvm::MachineBranchProbabilityInfo Class Reference
LLVM API Documentation
llvm::MachineBranchProbabilityInfo Class Reference
#include <MachineBranchProbabilityInfo.h>
Public Member Functions
MachineBranchProbabilityInfo ()
void getAnalysisUsage (AnalysisUsage &AU) const override
uint32_t getEdgeWeight (const MachineBasicBlock *Src, const MachineBasicBlock *Dst) const
uint32_t getEdgeWeight (const MachineBasicBlock *Src, MachineBasicBlock::const_succ_iterator Dst) const
uint32_t getSumForBlock (const MachineBasicBlock *MBB, uint32_t &Scale) const
bool isEdgeHot (const MachineBasicBlock *Src, const MachineBasicBlock *Dst) const
MachineBasicBlock * getHotSucc (MachineBasicBlock *MBB) const
BranchProbability getEdgeProbability (const MachineBasicBlock *Src, const MachineBasicBlock *Dst) const
raw_ostream & printEdgeProbability (raw_ostream &OS, const MachineBasicBlock *Src, const MachineBasicBlock *Dst) const
Public Member Functions inherited from llvm::ImmutablePass
virtual void initializePass ()
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePass (char &pid)
virtual ~ImmutablePass ()
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 24 of file MachineBranchProbabilityInfo.h.
Constructor & Destructor Documentation
MachineBranchProbabilityInfo()
llvm::MachineBranchProbabilityInfo::MachineBranchProbabilityInfo () inline
Definition at line 38 of file MachineBranchProbabilityInfo.h.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::ImmutablePass::ImmutablePass(), and llvm::initializeMachineBranchProbabilityInfoPass().
Member Function Documentation
getAnalysisUsage()
void llvm::MachineBranchProbabilityInfo::getAnalysisUsage (AnalysisUsage &) const inline override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 43 of file MachineBranchProbabilityInfo.h.
References llvm::AnalysisUsage::setPreservesAll().
getEdgeProbability()
BranchProbability MachineBranchProbabilityInfo::getEdgeProbability (const MachineBasicBlock * Src, const MachineBasicBlock * Dst) const
Definition at line 107 of file MachineBranchProbabilityInfo.cpp.
References getEdgeWeight(), getSumForBlock(), and N.
Referenced by llvm::HexagonInstrInfo::getDotNewPredJumpOp(), getHotSucc(), getNewValueJumpOpcode(), isEdgeHot(), and printEdgeProbability().
getEdgeWeight() [1/2]
uint32_t MachineBranchProbabilityInfo::getEdgeWeight (const MachineBasicBlock * Src, const MachineBasicBlock * Dst) const
Definition at line 72 of file MachineBranchProbabilityInfo.cpp.
References getEdgeWeight(), llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
Referenced by getEdgeProbability(), getEdgeWeight(), getHotSucc(), getSumForBlock(), and ScaleWeights().
getEdgeWeight() [2/2]
uint32_t MachineBranchProbabilityInfo::getEdgeWeight (const MachineBasicBlock * Src, MachineBasicBlock::const_succ_iterator Dst) const
Definition at line 63 of file MachineBranchProbabilityInfo.cpp.
getHotSucc()
MachineBasicBlock * MachineBranchProbabilityInfo::getHotSucc (MachineBasicBlock * MBB) const
Definition at line 89 of file MachineBranchProbabilityInfo.cpp.
References getEdgeProbability(), getEdgeWeight(), I, llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
getSumForBlock()
uint32_t MachineBranchProbabilityInfo::getSumForBlock (const MachineBasicBlock * MBB, uint32_t & Scale) const
Definition at line 31 of file MachineBranchProbabilityInfo.cpp.
References getEdgeWeight(), I, llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), and llvm::MachineBasicBlock::succ_size().
Referenced by getEdgeProbability().
isEdgeHot()
bool MachineBranchProbabilityInfo::isEdgeHot (const MachineBasicBlock * Src, const MachineBasicBlock * Dst) const
Definition at line 81 of file MachineBranchProbabilityInfo.cpp.
References getEdgeProbability().
Referenced by printEdgeProbability().
printEdgeProbability()
raw_ostream & MachineBranchProbabilityInfo::printEdgeProbability (raw_ostream & OS, const MachineBasicBlock * Src, const MachineBasicBlock * Dst) const
Definition at line 116 of file MachineBranchProbabilityInfo.cpp.
References getEdgeProbability(), llvm::MachineBasicBlock::getNumber(), and isEdgeHot().
Member Data Documentation
ID
machine branch Machine Branch Probability true char MachineBranchProbabilityInfo::ID = 0 static
Definition at line 36 of file MachineBranchProbabilityInfo.h.
Referenced by MachineBranchProbabilityInfo().
The documentation for this class was generated from the following files:
MachineBranchProbabilityInfo.h
MachineBranchProbabilityInfo.cpp