LLVM: llvm::MCSectionData Class Reference
LLVM API Documentation
llvm::MCSectionData Class Reference
#include <MCAssembler.h>
Public Types
enum BundleLockStateType { NotBundleLocked , BundleLocked , BundleLockedAlignToEnd }
Express the state of bundle locked groups while emitting code.
typedef iplist< MCFragment > FragmentListType
typedef FragmentListType::const_iterator const_iterator
typedef FragmentListType::iterator iterator
typedef FragmentListType::const_reverse_iterator const_reverse_iterator
typedef FragmentListType::reverse_iterator reverse_iterator
Public Member Functions
MCSectionData ()
MCSectionData (const MCSection &Section, MCAssembler *A=nullptr)
const MCSection & getSection () const
unsigned getAlignment () const
void setAlignment (unsigned Value)
bool hasInstructions () const
void setHasInstructions (bool Value)
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
Fragment Access
const FragmentListType & getFragmentList () const
FragmentListType & getFragmentList ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t size () const
bool empty () const
iterator getSubsectionInsertionPoint (unsigned Subsection)
bool isBundleLocked () const
BundleLockStateType getBundleLockState () const
void setBundleLockState (BundleLockStateType NewState)
bool isBundleGroupBeforeFirstInst () const
void setBundleGroupBeforeFirstInst (bool IsFirst)
void dump ()
Public Member Functions inherited from llvm::ilist_node< MCSectionData >
MCSectionData * getPrevNode ()
Get the previous node, or 0 for the list head.
MCSectionData * getNextNode ()
Get the next node, or 0 for the list tail.
Friends
class MCAsmLayout
Additional Inherited Members
Protected Member Functions inherited from llvm::ilist_node< MCSectionData >
ilist_node ()
Detailed Description
Definition at line 562 of file MCAssembler.h.
Member Typedef Documentation
const_iterator
typedef FragmentListType::const_iterator llvm::MCSectionData::const_iterator
Definition at line 571 of file MCAssembler.h.
const_reverse_iterator
typedef FragmentListType::const_reverse_iterator llvm::MCSectionData::const_reverse_iterator
Definition at line 574 of file MCAssembler.h.
FragmentListType
typedef iplist<MCFragment> llvm::MCSectionData::FragmentListType
Definition at line 569 of file MCAssembler.h.
iterator
typedef FragmentListType::iterator llvm::MCSectionData::iterator
Definition at line 572 of file MCAssembler.h.
reverse_iterator
typedef FragmentListType::reverse_iterator llvm::MCSectionData::reverse_iterator
Definition at line 575 of file MCAssembler.h.
Member Enumeration Documentation
BundleLockStateType
enum llvm::MCSectionData::BundleLockStateType
Express the state of bundle locked groups while emitting code.
Enumerator
NotBundleLocked
BundleLocked
BundleLockedAlignToEnd
Definition at line 578 of file MCAssembler.h.
Constructor & Destructor Documentation
MCSectionData() [1/2]
MCSectionData::MCSectionData ()
Definition at line 289 of file MCAssembler.cpp.
MCSectionData() [2/2]
MCSectionData::MCSectionData (const MCSection & Section, MCAssembler * A = nullptr)
Definition at line 291 of file MCAssembler.cpp.
References NotBundleLocked.
Member Function Documentation
begin() [1/2]
iterator llvm::MCSectionData::begin () inline
Definition at line 646 of file MCAssembler.h.
Referenced by dump(), llvm::MCAssembler::Finish(), and llvm::MCAssembler::writeSectionData().
begin() [2/2]
const_iterator llvm::MCSectionData::begin () const inline
Definition at line 647 of file MCAssembler.h.
dump()
void MCSectionData::dump ()
Definition at line 1248 of file MCAssembler.cpp.
References begin(), end(), llvm::errs(), and getAlignment().
empty()
bool llvm::MCSectionData::empty () const inline
Definition at line 660 of file MCAssembler.h.
end() [1/2]
iterator llvm::MCSectionData::end () inline
Definition at line 649 of file MCAssembler.h.
Referenced by dump(), llvm::MCAssembler::Finish(), getSubsectionInsertionPoint(), and llvm::MCAssembler::writeSectionData().
end() [2/2]
const_iterator llvm::MCSectionData::end () const inline
Definition at line 650 of file MCAssembler.h.
getAlignment()
unsigned llvm::MCSectionData::getAlignment () const inline
Definition at line 628 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::computeSectionAddresses(), dump(), llvm::MipsTargetELFStreamer::finish(), llvm::MCELFStreamer::Flush(), llvm::MachObjectWriter::getPaddingSize(), and llvm::MachObjectWriter::WriteSection().
getBundleLockState()
BundleLockStateType llvm::MCSectionData::getBundleLockState () const inline
Definition at line 668 of file MCAssembler.h.
getFragmentList() [1/2]
FragmentListType & llvm::MCSectionData::getFragmentList () inline
Definition at line 644 of file MCAssembler.h.
getFragmentList() [2/2]
const FragmentListType & llvm::MCSectionData::getFragmentList () const inline
Definition at line 643 of file MCAssembler.h.
Referenced by CompressDebugSection(), llvm::MCAsmLayout::getSectionAddressSize(), and getSubsectionInsertionPoint().
getLayoutOrder()
unsigned llvm::MCSectionData::getLayoutOrder () const inline
Definition at line 637 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::getPaddingSize().
getOrdinal()
unsigned llvm::MCSectionData::getOrdinal () const inline
Definition at line 634 of file MCAssembler.h.
getSection()
const MCSection & llvm::MCSectionData::getSection () const inline
Definition at line 626 of file MCAssembler.h.
Referenced by llvm::MCAssembler::getAtom(), llvm::MachObjectWriter::getPaddingSize(), llvm::MCAsmLayout::getSectionFileSize(), llvm::MachObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), llvm::MachObjectWriter::WriteObject(), llvm::MachObjectWriter::WriteSection(), and llvm::MCAssembler::writeSectionData().
getSubsectionInsertionPoint()
MCSectionData::iterator MCSectionData::getSubsectionInsertionPoint (unsigned Subsection)
Definition at line 305 of file MCAssembler.cpp.
References end(), F, getFragmentList(), and llvm::iplist< NodeTy, Traits >::insert().
hasInstructions()
bool llvm::MCSectionData::hasInstructions () const inline
Definition at line 631 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::mayHaveInstructions(), and llvm::MachObjectWriter::WriteSection().
isBundleGroupBeforeFirstInst()
bool llvm::MCSectionData::isBundleGroupBeforeFirstInst () const inline
Definition at line 674 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitBundleUnlock().
isBundleLocked()
bool llvm::MCSectionData::isBundleLocked () const inline
Definition at line 664 of file MCAssembler.h.
References NotBundleLocked.
Referenced by llvm::MCELFStreamer::ChangeSection(), llvm::MCELFStreamer::EmitBundleLock(), llvm::MCELFStreamer::EmitBundleUnlock(), and llvm::MCObjectStreamer::EmitInstruction().
rbegin() [1/2]
reverse_iterator llvm::MCSectionData::rbegin () inline
Definition at line 652 of file MCAssembler.h.
rbegin() [2/2]
const_reverse_iterator llvm::MCSectionData::rbegin () const inline
Definition at line 653 of file MCAssembler.h.
rend() [1/2]
reverse_iterator llvm::MCSectionData::rend () inline
Definition at line 655 of file MCAssembler.h.
rend() [2/2]
const_reverse_iterator llvm::MCSectionData::rend () const inline
Definition at line 656 of file MCAssembler.h.
setAlignment()
void llvm::MCSectionData::setAlignment (unsigned Value) inline
Definition at line 629 of file MCAssembler.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::MipsRegInfoRecord::EmitMipsOptionRecord(), llvm::MCObjectStreamer::EmitValueToAlignment(), llvm::MipsTargetELFStreamer::finish(), and llvm::MCELFStreamer::Flush().
setBundleGroupBeforeFirstInst()
void llvm::MCSectionData::setBundleGroupBeforeFirstInst (bool IsFirst) inline
Definition at line 678 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitBundleLock().
setBundleLockState()
void MCSectionData::setBundleLockState (BundleLockStateType NewState)
Definition at line 334 of file MCAssembler.cpp.
References BundleLockedAlignToEnd, NotBundleLocked, and llvm::report_fatal_error().
Referenced by llvm::MCELFStreamer::EmitBundleLock(), and llvm::MCELFStreamer::EmitBundleUnlock().
setHasInstructions()
void llvm::MCSectionData::setHasInstructions (bool Value) inline
Definition at line 632 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitInstruction().
setLayoutOrder()
void llvm::MCSectionData::setLayoutOrder (unsigned Value) inline
Definition at line 638 of file MCAssembler.h.
Referenced by llvm::MCAssembler::Finish().
setOrdinal()
void llvm::MCSectionData::setOrdinal (unsigned Value) inline
Definition at line 635 of file MCAssembler.h.
size()
size_t llvm::MCSectionData::size () const inline
Definition at line 658 of file MCAssembler.h.
Friends And Related Symbol Documentation
MCAsmLayout
friend class MCAsmLayout friend
Definition at line 563 of file MCAssembler.h.
References LLVM_DELETED_FUNCTION, and MCAsmLayout.
Referenced by MCAsmLayout.
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp