LLVM: llvm::FunctionAnalysisManagerCGSCCProxy::Result Class Reference
LLVM API Documentation
llvm::FunctionAnalysisManagerCGSCCProxy::Result Class Reference
#include <CGSCCPassManager.h>
Public Member Functions
Result (FunctionAnalysisManager &FAM)
Result (const Result &Arg)
Result (Result &&Arg)
Result & operator= (Result RHS)
~Result ()
FunctionAnalysisManager & getManager ()
Accessor for the FunctionAnalysisManager.
bool invalidate (LazyCallGraph::SCC &C, const PreservedAnalyses &PA)
Handler for invalidation of the SCC.
Detailed Description
Definition at line 280 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
Result() [1/3]
llvm::FunctionAnalysisManagerCGSCCProxy::Result::Result (FunctionAnalysisManager & FAM) inline explicit
Definition at line 282 of file CGSCCPassManager.h.
Referenced by operator=(), Result(), and Result().
Result() [2/3]
llvm::FunctionAnalysisManagerCGSCCProxy::Result::Result (const Result & Arg) inline
Definition at line 285 of file CGSCCPassManager.h.
References Result().
Result() [3/3]
llvm::FunctionAnalysisManagerCGSCCProxy::Result::Result (Result && Arg) inline
Definition at line 286 of file CGSCCPassManager.h.
References Result().
~Result()
FunctionAnalysisManagerCGSCCProxy::Result::~Result ()
Definition at line 53 of file CGSCCPassManager.cpp.
Member Function Documentation
getManager()
FunctionAnalysisManager & llvm::FunctionAnalysisManagerCGSCCProxy::Result::getManager () inline
Accessor for the FunctionAnalysisManager.
Definition at line 294 of file CGSCCPassManager.h.
invalidate()
bool FunctionAnalysisManagerCGSCCProxy::Result::invalidate (LazyCallGraph::SCC & C, const PreservedAnalyses & PA)
Handler for invalidation of the SCC.
If this analysis itself is preserved, then we assume that the set of Function objects in the SCC hasn't changed and thus we don't need to invalidate all cached data associated with a Function* in the FunctionAnalysisManager.
Regardless of whether this analysis is marked as preserved, all of the analyses in the FunctionAnalysisManager are potentially invalidated based on the set of preserved analyses.
Definition at line 59 of file CGSCCPassManager.cpp.
References llvm::FunctionAnalysisManagerCGSCCProxy::ID(), and llvm::PreservedAnalyses::preserved().
operator=()
Result & llvm::FunctionAnalysisManagerCGSCCProxy::Result::operator= (Result RHS) inline
Definition at line 287 of file CGSCCPassManager.h.
References Result(), and std::swap().
The documentation for this class was generated from the following files:
CGSCCPassManager.h
CGSCCPassManager.cpp