LLVM: llvm::InstCombineIRInserter Class Reference
LLVM API Documentation
llvm::InstCombineIRInserter Class Reference
#include <InstCombine.h>
Public Member Functions
InstCombineIRInserter (InstCombineWorklist &WL, AssumptionCache *AC)
void InsertHelper (Instruction *I, const Twine &Name, BasicBlock *BB, BasicBlock::iterator InsertPt) const
Additional Inherited Members
Protected Member Functions inherited from llvm::IRBuilderDefaultInserter< true >
void InsertHelper (Instruction *I, const Twine &Name, BasicBlock *BB, BasicBlock::iterator InsertPt) const
Detailed Description
InstCombineIRInserter - This is an IRBuilder insertion helper that works just like the normal insertion helper, but also adds any new instructions to the instcombine worklist.
Definition at line 75 of file InstCombine.h.
Constructor & Destructor Documentation
InstCombineIRInserter()
llvm::InstCombineIRInserter::InstCombineIRInserter (InstCombineWorklist & WL, AssumptionCache * AC) inline
Definition at line 81 of file InstCombine.h.
Member Function Documentation
InsertHelper()
void llvm::InstCombineIRInserter::InsertHelper (Instruction * I, const Twine & Name, BasicBlock * BB, BasicBlock::iterator InsertPt) const inline
Definition at line 84 of file InstCombine.h.
References llvm::cast(), I, llvm::IRBuilderDefaultInserter< preserveNames >::InsertHelper(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::match(), and Name.
The documentation for this class was generated from the following file:
InstCombine.h