LLVM: llvm::Registry< T, U >::iterator Class Reference
LLVM API Documentation
llvm::Registry< T, U >::iterator Class Reference
#include <Registry.h>
Public Member Functions
iterator (const node *N)
bool operator== (const iterator &That) const
bool operator!= (const iterator &That) const
iterator & operator++ ()
const entry & operator* () const
const entry * operator-> () const
Detailed Description
template<typename T, typename U = RegistryTraits<T>>
class llvm::Registry< T, U >::iterator
Iterators for registry entries.
Definition at line 107 of file Registry.h.
Constructor & Destructor Documentation
iterator()
template<typename T, typename U = RegistryTraits<T>> llvm::Registry< T, U >::iterator::iterator (const node * N) inline explicit
Definition at line 111 of file Registry.h.
References N.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
operator!=()
template<typename T, typename U = RegistryTraits<T>> bool llvm::Registry< T, U >::iterator::operator!= (const iterator & That) const inline
Definition at line 114 of file Registry.h.
References iterator().
operator*()
template<typename T, typename U = RegistryTraits<T>> const entry & llvm::Registry< T, U >::iterator::operator* () const inline
Definition at line 116 of file Registry.h.
operator++()
template<typename T, typename U = RegistryTraits<T>> iterator & llvm::Registry< T, U >::iterator::operator++ () inline
Definition at line 115 of file Registry.h.
References iterator().
operator->()
template<typename T, typename U = RegistryTraits<T>> const entry * llvm::Registry< T, U >::iterator::operator-> () const inline
Definition at line 117 of file Registry.h.
operator==()
template<typename T, typename U = RegistryTraits<T>> bool llvm::Registry< T, U >::iterator::operator== (const iterator & That) const inline
Definition at line 113 of file Registry.h.
References iterator().
The documentation for this class was generated from the following file:
Registry.h