LLVM: llvm::DWARFDebugAbbrev Class Reference
LLVM API Documentation
llvm::DWARFDebugAbbrev Class Reference
#include <DWARFDebugAbbrev.h>
Public Member Functions
DWARFDebugAbbrev ()
const DWARFAbbreviationDeclarationSet * getAbbreviationDeclarationSet (uint64_t CUAbbrOffset) const
void dump (raw_ostream &OS) const
void extract (DataExtractor Data)
Detailed Description
Definition at line 41 of file DWARFDebugAbbrev.h.
Constructor & Destructor Documentation
DWARFDebugAbbrev()
DWARFDebugAbbrev::DWARFDebugAbbrev ()
Definition at line 67 of file DWARFDebugAbbrev.cpp.
References clear().
Member Function Documentation
dump()
void DWARFDebugAbbrev::dump (raw_ostream & OS) const
Definition at line 89 of file DWARFDebugAbbrev.cpp.
References llvm::format(), and I.
Referenced by llvm::DWARFContext::dump().
extract()
void DWARFDebugAbbrev::extract (DataExtractor Data)
Definition at line 76 of file DWARFDebugAbbrev.cpp.
References clear(), llvm::DWARFAbbreviationDeclarationSet::extract(), and llvm::DataExtractor::isValidOffset().
getAbbreviationDeclarationSet()
const DWARFAbbreviationDeclarationSet * DWARFDebugAbbrev::getAbbreviationDeclarationSet (uint64_t CUAbbrOffset) const
Definition at line 102 of file DWARFDebugAbbrev.cpp.
The documentation for this class was generated from the following files:
DWARFDebugAbbrev.h
DWARFDebugAbbrev.cpp