LLVM: llvm::HexagonInstrInfo Class Reference
LLVM API Documentation
llvm::HexagonInstrInfo Class Reference
#include <HexagonInstrInfo.h>
Public Member Functions
HexagonInstrInfo (HexagonSubtarget &ST)
const HexagonRegisterInfo & getRegisterInfo () const
unsigned isLoadFromStackSlot (const MachineInstr *MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr *MI, int &FrameIndex) const override
bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
unsigned RemoveBranch (MachineBasicBlock &MBB) const override
unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const override
bool analyzeCompare (const MachineInstr *MI, unsigned &SrcReg, unsigned &SrcReg2, int &Mask, int &Value) const override
For a comparison instruction, return the source registers in SrcReg and SrcReg2 if having two register operands, and the value it compares against in CmpValue. Return true if the comparison instruction can be analyzed.
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void storeRegToAddr (MachineFunction &MF, unsigned SrcReg, bool isKill, SmallVectorImpl< MachineOperand > &Addr, const TargetRegisterClass *RC, SmallVectorImpl< MachineInstr * > &NewMIs) const
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromAddr (MachineFunction &MF, unsigned DestReg, SmallVectorImpl< MachineOperand > &Addr, const TargetRegisterClass *RC, SmallVectorImpl< MachineInstr * > &NewMIs) const
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, int FrameIndex) const override
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, MachineInstr *LoadMI) const override
unsigned createVR (MachineFunction *MF, MVT VT) const
bool isBranch (const MachineInstr *MI) const
bool isPredicable (MachineInstr *MI) const override
bool PredicateInstruction (MachineInstr *MI, const SmallVectorImpl< MachineOperand > &Cond) const override
bool isProfitableToIfCvt (MachineBasicBlock &MBB, unsigned NumCycles, unsigned ExtraPredCycles, const BranchProbability &Probability) const override
bool isProfitableToIfCvt (MachineBasicBlock &TMBB, unsigned NumTCycles, unsigned ExtraTCycles, MachineBasicBlock &FMBB, unsigned NumFCycles, unsigned ExtraFCycles, const BranchProbability &Probability) const override
bool isPredicated (const MachineInstr *MI) const override
bool isPredicated (unsigned Opcode) const
bool isPredicatedTrue (const MachineInstr *MI) const
bool isPredicatedTrue (unsigned Opcode) const
bool isPredicatedNew (const MachineInstr *MI) const
bool isPredicatedNew (unsigned Opcode) const
bool DefinesPredicate (MachineInstr *MI, std::vector< MachineOperand > &Pred) const override
bool SubsumesPredicate (const SmallVectorImpl< MachineOperand > &Pred1, const SmallVectorImpl< MachineOperand > &Pred2) const override
bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
bool isProfitableToDupForIfCvt (MachineBasicBlock &MBB, unsigned NumCycles, const BranchProbability &Probability) const override
DFAPacketizer * CreateTargetScheduleState (const TargetSubtargetInfo &STI) const override
bool isSchedulingBoundary (const MachineInstr *MI, const MachineBasicBlock *MBB, const MachineFunction &MF) const override
bool isValidOffset (const int Opcode, const int Offset) const
bool isValidAutoIncImm (const EVT VT, const int Offset) const
bool isMemOp (const MachineInstr *MI) const
bool isSpillPredRegOp (const MachineInstr *MI) const
bool isU6_3Immediate (const int value) const
bool isU6_2Immediate (const int value) const
bool isU6_1Immediate (const int value) const
bool isU6_0Immediate (const int value) const
bool isS4_3Immediate (const int value) const
bool isS4_2Immediate (const int value) const
bool isS4_1Immediate (const int value) const
bool isS4_0Immediate (const int value) const
bool isS12_Immediate (const int value) const
bool isU6_Immediate (const int value) const
bool isS8_Immediate (const int value) const
bool isS6_Immediate (const int value) const
bool isSaveCalleeSavedRegsCall (const MachineInstr *MI) const
bool isConditionalTransfer (const MachineInstr *MI) const
bool isConditionalALU32 (const MachineInstr *MI) const
bool isConditionalLoad (const MachineInstr *MI) const
bool isConditionalStore (const MachineInstr *MI) const
bool isNewValueInst (const MachineInstr *MI) const
bool isNewValue (const MachineInstr *MI) const
bool isDotNewInst (const MachineInstr *MI) const
int GetDotOldOp (const int opc) const
int GetDotNewOp (const MachineInstr *MI) const
int GetDotNewPredOp (MachineInstr *MI, const MachineBranchProbabilityInfo *MBPI) const
bool mayBeNewStore (const MachineInstr *MI) const
bool isDeallocRet (const MachineInstr *MI) const
unsigned getInvertedPredicatedOpcode (const int Opc) const
bool isExtendable (const MachineInstr *MI) const
bool isExtended (const MachineInstr *MI) const
bool isPostIncrement (const MachineInstr *MI) const
bool isNewValueStore (const MachineInstr *MI) const
bool isNewValueStore (unsigned Opcode) const
bool isNewValueJump (const MachineInstr *MI) const
bool isNewValueJumpCandidate (const MachineInstr *MI) const
void immediateExtend (MachineInstr *MI) const
bool isConstExtended (MachineInstr *MI) const
int getDotNewPredJumpOp (MachineInstr *MI, const MachineBranchProbabilityInfo *MBPI) const
unsigned getAddrMode (const MachineInstr *MI) const
bool isOperandExtended (const MachineInstr *MI, unsigned short OperandNum) const
unsigned short getCExtOpNum (const MachineInstr *MI) const
int getMinValue (const MachineInstr *MI) const
int getMaxValue (const MachineInstr *MI) const
bool NonExtEquivalentExists (const MachineInstr *MI) const
short getNonExtOpcode (const MachineInstr *MI) const
bool PredOpcodeHasJMP_c (Opcode_t Opcode) const
bool PredOpcodeHasNot (Opcode_t Opcode) const
Detailed Description
Definition at line 30 of file HexagonInstrInfo.h.
Constructor & Destructor Documentation
HexagonInstrInfo()
HexagonInstrInfo::HexagonInstrInfo (HexagonSubtarget & ST) explicit
Definition at line 64 of file HexagonInstrInfo.cpp.
Member Function Documentation
AnalyzeBranch()
bool HexagonInstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Definition at line 175 of file HexagonInstrInfo.cpp.
References llvm::MachineOperand::CreateImm(), llvm::dbgs(), DEBUG, llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), I, llvm::MachineBasicBlock::instr_begin(), llvm::MachineBasicBlock::instr_end(), llvm::MachineBasicBlock::isLayoutSuccessor(), PredOpcodeHasJMP_c(), PredOpcodeHasNot(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by InsertBranch().
analyzeCompare()
bool HexagonInstrInfo::analyzeCompare (const MachineInstr * MI, unsigned & SrcReg, unsigned & SrcReg2, int & Mask, int & Value) const override
For a comparison instruction, return the source registers in SrcReg and SrcReg2 if having two register operands, and the value it compares against in CmpValue. Return true if the comparison instruction can be analyzed.
Definition at line 342 of file HexagonInstrInfo.cpp.
copyPhysReg()
void HexagonInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
Definition at line 416 of file HexagonInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::getKillRegState(), I, and llvm_unreachable.
CreateTargetScheduleState()
DFAPacketizer * HexagonInstrInfo::CreateTargetScheduleState (const TargetSubtargetInfo & STI) const override
Definition at line 1630 of file HexagonInstrInfo.cpp.
References llvm::TargetSubtargetInfo::getInstrItineraryData().
createVR()
unsigned HexagonInstrInfo::createVR (MachineFunction * MF, MVT VT) const
Definition at line 566 of file HexagonInstrInfo.cpp.
References llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MVT::f32, llvm::MVT::f64, llvm::MachineFunction::getRegInfo(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, and llvm_unreachable.
DefinesPredicate()
bool HexagonInstrInfo::DefinesPredicate (MachineInstr * MI, std::vector< MachineOperand > & Pred) const override
Definition at line 1026 of file HexagonInstrInfo.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), and llvm::MachineOperand::isReg().
foldMemoryOperandImpl() [1/2]
MachineInstr * HexagonInstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, const SmallVectorImpl< unsigned > & Ops, int FrameIndex) const override
Definition at line 558 of file HexagonInstrInfo.cpp.
foldMemoryOperandImpl() [2/2]
MachineInstr * llvm::HexagonInstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, const SmallVectorImpl< unsigned > & Ops, MachineInstr * LoadMI) const inline override
Definition at line 110 of file HexagonInstrInfo.h.
getAddrMode()
unsigned HexagonInstrInfo::getAddrMode (const MachineInstr * MI) const
Definition at line 1609 of file HexagonInstrInfo.cpp.
References llvm::HexagonII::AddrModeMask, llvm::HexagonII::AddrModePos, and F.
Referenced by getNonExtOpcode(), isPostIncrement(), and NonExtEquivalentExists().
getCExtOpNum()
unsigned short HexagonInstrInfo::getCExtOpNum (const MachineInstr * MI) const
Definition at line 1744 of file HexagonInstrInfo.cpp.
References llvm::HexagonII::ExtendableOpMask, llvm::HexagonII::ExtendableOpPos, and F.
Referenced by immediateExtend(), and isConstExtended().
GetDotNewOp()
int HexagonInstrInfo::GetDotNewOp (const MachineInstr * MI) const
Definition at line 1544 of file HexagonInstrInfo.cpp.
References llvm_unreachable.
getDotNewPredJumpOp()
int HexagonInstrInfo::getDotNewPredJumpOp (MachineInstr * MI, const MachineBranchProbabilityInfo * MBPI) const
Definition at line 1706 of file HexagonInstrInfo.cpp.
References llvm::MachineBranchProbabilityInfo::getEdgeProbability(), llvm::MachineOperand::getMBB(), and llvm_unreachable.
Referenced by GetDotNewPredOp().
GetDotNewPredOp()
int HexagonInstrInfo::GetDotNewPredOp (MachineInstr * MI, const MachineBranchProbabilityInfo * MBPI) const
Definition at line 1572 of file HexagonInstrInfo.cpp.
References getDotNewPredJumpOp(), and llvm_unreachable.
GetDotOldOp()
int HexagonInstrInfo::GetDotOldOp (const int opc) const
Definition at line 1528 of file HexagonInstrInfo.cpp.
References isNewValueStore(), isPredicated(), and isPredicatedNew().
getInvertedPredicatedOpcode()
unsigned HexagonInstrInfo::getInvertedPredicatedOpcode (const int Opc) const
Definition at line 723 of file HexagonInstrInfo.cpp.
References isPredicatedTrue(), and llvm_unreachable.
getMaxValue()
int HexagonInstrInfo::getMaxValue (const MachineInstr * MI) const
Definition at line 1764 of file HexagonInstrInfo.cpp.
References llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, llvm::HexagonII::ExtentSignedMask, llvm::HexagonII::ExtentSignedPos, and F.
Referenced by isConstExtended().
getMinValue()
int HexagonInstrInfo::getMinValue (const MachineInstr * MI) const
Definition at line 1750 of file HexagonInstrInfo.cpp.
References llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, llvm::HexagonII::ExtentSignedMask, llvm::HexagonII::ExtentSignedPos, and F.
Referenced by isConstExtended().
getNonExtOpcode()
short HexagonInstrInfo::getNonExtOpcode (const MachineInstr * MI) const
Definition at line 1813 of file HexagonInstrInfo.cpp.
References llvm::HexagonII::Absolute, llvm::HexagonII::BaseImmOffset, and getAddrMode().
getRegisterInfo()
const HexagonRegisterInfo & llvm::HexagonInstrInfo::getRegisterInfo () const inline
getRegisterInfo - TargetInstrInfo is a superset of MRegister info. As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 43 of file HexagonInstrInfo.h.
Referenced by isConditionalLoad(), isConditionalStore(), and mayBeNewStore().
immediateExtend()
void HexagonInstrInfo::immediateExtend (MachineInstr * MI) const
immediateExtend - Changes the instruction in place to one using an immediate extender.
Definition at line 1617 of file HexagonInstrInfo.cpp.
References llvm::MachineOperand::addTargetFlag(), getCExtOpNum(), llvm::HexagonII::HMOTF_ConstExtended, isConstExtended(), isExtendable(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isMBB().
InsertBranch()
unsigned HexagonInstrInfo::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, const SmallVectorImpl< MachineOperand > & Cond, DebugLoc DL) const override
Definition at line 122 of file HexagonInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), AnalyzeBranch(), llvm::BuildMI(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::getFirstTerminator(), getReg(), InsertBranch(), isPredicated(), RemoveBranch(), and ReverseBranchCondition().
Referenced by InsertBranch().
isBranch()
bool HexagonInstrInfo::isBranch (const MachineInstr * MI) const
Definition at line 624 of file HexagonInstrInfo.cpp.
Referenced by isNewValueJump().
isConditionalALU32()
bool HexagonInstrInfo::isConditionalALU32 (const MachineInstr * MI) const
Definition at line 1279 of file HexagonInstrInfo.cpp.
isConditionalLoad()
bool HexagonInstrInfo::isConditionalLoad (const MachineInstr * MI) const
Definition at line 1335 of file HexagonInstrInfo.cpp.
References getRegisterInfo(), llvm::HexagonSubtarget::hasV4TOps(), and llvm::HexagonRegisterInfo::Subtarget.
isConditionalStore()
bool HexagonInstrInfo::isConditionalStore (const MachineInstr * MI) const
Definition at line 1417 of file HexagonInstrInfo.cpp.
References getRegisterInfo(), llvm::HexagonSubtarget::hasV4TOps(), and llvm::HexagonRegisterInfo::Subtarget.
isConditionalTransfer()
bool HexagonInstrInfo::isConditionalTransfer (const MachineInstr * MI) const
Definition at line 1263 of file HexagonInstrInfo.cpp.
isConstExtended()
bool HexagonInstrInfo::isConstExtended (MachineInstr * MI) const
Definition at line 1655 of file HexagonInstrInfo.cpp.
References llvm::HexagonII::ExtendableMask, llvm::HexagonII::ExtendablePos, llvm::HexagonII::ExtendedMask, llvm::HexagonII::ExtendedPos, F, getCExtOpNum(), llvm::MachineOperand::getImm(), getMaxValue(), getMinValue(), llvm::MachineOperand::getTargetFlags(), llvm::HexagonII::HMOTF_ConstExtended, isExtendable(), isExtended(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isMBB(), and llvm::MachineOperand::isSymbol().
Referenced by immediateExtend().
isDeallocRet()
bool HexagonInstrInfo::isDeallocRet (const MachineInstr * MI) const
Definition at line 1072 of file HexagonInstrInfo.cpp.
isDotNewInst()
bool HexagonInstrInfo::isDotNewInst (const MachineInstr * MI) const
Definition at line 1514 of file HexagonInstrInfo.cpp.
References isNewValueInst(), isPredicated(), and isPredicatedNew().
isExtendable()
bool HexagonInstrInfo::isExtendable (const MachineInstr * MI) const
Definition at line 584 of file HexagonInstrInfo.cpp.
References llvm::HexagonII::ExtendableMask, llvm::HexagonII::ExtendablePos, F, and llvm::MCInstrDesc::TSFlags.
Referenced by immediateExtend(), and isConstExtended().
isExtended()
bool HexagonInstrInfo::isExtended (const MachineInstr * MI) const
Definition at line 609 of file HexagonInstrInfo.cpp.
References llvm::HexagonII::ExtendedMask, llvm::HexagonII::ExtendedPos, F, llvm::HexagonII::HMOTF_ConstExtended, and I.
Referenced by isConstExtended().
isLoadFromStackSlot()
unsigned HexagonInstrInfo::isLoadFromStackSlot (const MachineInstr * MI, int & FrameIndex) const override
isLoadFromStackSlot - If the specified machine instruction is a direct load from a stack slot, return the virtual or physical register number of the destination along with the FrameIndex of the loaded stack slot. If not, return 0. This predicate must return 0 if the instruction has any side effects other than loading from the stack slot.
Definition at line 75 of file HexagonInstrInfo.cpp.
isMemOp()
bool HexagonInstrInfo::isMemOp (const MachineInstr * MI) const
Definition at line 1203 of file HexagonInstrInfo.cpp.
isNewValue()
bool HexagonInstrInfo::isNewValue (const MachineInstr * MI) const
Definition at line 1507 of file HexagonInstrInfo.cpp.
References F, llvm::HexagonII::NewValueMask, and llvm::HexagonII::NewValuePos.
Referenced by isNewValueJump().
isNewValueInst()
bool HexagonInstrInfo::isNewValueInst (const MachineInstr * MI) const
Definition at line 628 of file HexagonInstrInfo.cpp.
References isNewValueJump(), and isNewValueStore().
Referenced by isDotNewInst().
isNewValueJump()
bool HexagonInstrInfo::isNewValueJump (const MachineInstr * MI) const
Definition at line 1497 of file HexagonInstrInfo.cpp.
References isBranch(), and isNewValue().
Referenced by isNewValueInst().
isNewValueJumpCandidate()
bool HexagonInstrInfo::isNewValueJumpCandidate (const MachineInstr * MI) const
Definition at line 1250 of file HexagonInstrInfo.cpp.
isNewValueStore() [1/2]
bool HexagonInstrInfo::isNewValueStore (const MachineInstr * MI) const
Definition at line 746 of file HexagonInstrInfo.cpp.
References F, llvm::HexagonII::NVStoreMask, and llvm::HexagonII::NVStorePos.
Referenced by GetDotOldOp(), and isNewValueInst().
isNewValueStore() [2/2]
bool HexagonInstrInfo::isNewValueStore (unsigned Opcode) const
Definition at line 752 of file HexagonInstrInfo.cpp.
References F, llvm::HexagonII::NVStoreMask, and llvm::HexagonII::NVStorePos.
isOperandExtended()
bool HexagonInstrInfo::isOperandExtended (const MachineInstr * MI, unsigned short OperandNum) const
Definition at line 1731 of file HexagonInstrInfo.cpp.
References llvm::HexagonII::ExtendableOpMask, llvm::HexagonII::ExtendableOpPos, and F.
isPostIncrement()
bool HexagonInstrInfo::isPostIncrement (const MachineInstr * MI) const
Definition at line 1503 of file HexagonInstrInfo.cpp.
References getAddrMode(), and llvm::HexagonII::PostInc.
Referenced by GetPostIncrementOperand().
isPredicable()
bool HexagonInstrInfo::isPredicable (MachineInstr * MI) const override
Definition at line 642 of file HexagonInstrInfo.cpp.
References llvm::isInt(), llvm::isInt< 8 >(), llvm::isShiftedInt(), llvm::isShiftedUInt(), and llvm::isUInt().
Referenced by PredicateInstruction().
isPredicated() [1/2]
bool HexagonInstrInfo::isPredicated (const MachineInstr * MI) const override
Definition at line 972 of file HexagonInstrInfo.cpp.
References F, llvm::HexagonII::PredicatedMask, and llvm::HexagonII::PredicatedPos.
Referenced by GetDotOldOp(), getPredicatedRegister(), getPredicateSense(), InsertBranch(), isDotNewInst(), isPredicatedNew(), isPredicatedNew(), and isPredicatedTrue().
isPredicated() [2/2]
bool HexagonInstrInfo::isPredicated (unsigned Opcode) const
Definition at line 978 of file HexagonInstrInfo.cpp.
References F, llvm::HexagonII::PredicatedMask, and llvm::HexagonII::PredicatedPos.
isPredicatedNew() [1/2]
bool HexagonInstrInfo::isPredicatedNew (const MachineInstr * MI) const
Definition at line 1001 of file HexagonInstrInfo.cpp.
References F, isPredicated(), llvm::HexagonII::PredicatedNewMask, and llvm::HexagonII::PredicatedNewPos.
Referenced by GetDotOldOp(), and isDotNewInst().
isPredicatedNew() [2/2]
bool HexagonInstrInfo::isPredicatedNew (unsigned Opcode) const
Definition at line 1008 of file HexagonInstrInfo.cpp.
References F, isPredicated(), llvm::HexagonII::PredicatedNewMask, and llvm::HexagonII::PredicatedNewPos.
isPredicatedTrue() [1/2]
bool HexagonInstrInfo::isPredicatedTrue (const MachineInstr * MI) const
Definition at line 984 of file HexagonInstrInfo.cpp.
References F, isPredicated(), llvm::HexagonII::PredicatedFalseMask, and llvm::HexagonII::PredicatedFalsePos.
Referenced by getInvertedPredicatedOpcode(), and getPredicateSense().
isPredicatedTrue() [2/2]
bool HexagonInstrInfo::isPredicatedTrue (unsigned Opcode) const
Definition at line 992 of file HexagonInstrInfo.cpp.
References F, llvm::HexagonII::PredicatedFalseMask, llvm::HexagonII::PredicatedFalsePos, llvm::HexagonII::PredicatedMask, and llvm::HexagonII::PredicatedPos.
isProfitableToDupForIfCvt()
bool HexagonInstrInfo::isProfitableToDupForIfCvt (MachineBasicBlock & MBB, unsigned NumCycles, const BranchProbability & Probability) const override
Definition at line 1066 of file HexagonInstrInfo.cpp.
isProfitableToIfCvt() [1/2]
bool HexagonInstrInfo::isProfitableToIfCvt (MachineBasicBlock & MBB, unsigned NumCycles, unsigned ExtraPredCycles, const BranchProbability & Probability) const override
Definition at line 945 of file HexagonInstrInfo.cpp.
isProfitableToIfCvt() [2/2]
bool HexagonInstrInfo::isProfitableToIfCvt (MachineBasicBlock & TMBB, unsigned NumTCycles, unsigned ExtraTCycles, MachineBasicBlock & FMBB, unsigned NumFCycles, unsigned ExtraFCycles, const BranchProbability & Probability) const override
Definition at line 955 of file HexagonInstrInfo.cpp.
isS12_Immediate()
bool llvm::HexagonInstrInfo::isS12_Immediate (const int value) const
isS4_0Immediate()
bool llvm::HexagonInstrInfo::isS4_0Immediate (const int value) const
isS4_1Immediate()
bool llvm::HexagonInstrInfo::isS4_1Immediate (const int value) const
isS4_2Immediate()
bool llvm::HexagonInstrInfo::isS4_2Immediate (const int value) const
isS4_3Immediate()
bool llvm::HexagonInstrInfo::isS4_3Immediate (const int value) const
isS6_Immediate()
bool llvm::HexagonInstrInfo::isS6_Immediate (const int value) const
isS8_Immediate()
bool llvm::HexagonInstrInfo::isS8_Immediate (const int value) const
isSaveCalleeSavedRegsCall()
bool HexagonInstrInfo::isSaveCalleeSavedRegsCall (const MachineInstr * MI) const
Definition at line 638 of file HexagonInstrInfo.cpp.
isSchedulingBoundary()
bool HexagonInstrInfo::isSchedulingBoundary (const MachineInstr * MI, const MachineBasicBlock * MBB, const MachineFunction & MF) const override
Definition at line 1636 of file HexagonInstrInfo.cpp.
isSpillPredRegOp()
bool HexagonInstrInfo::isSpillPredRegOp (const MachineInstr * MI) const
Definition at line 1240 of file HexagonInstrInfo.cpp.
isStoreToStackSlot()
unsigned HexagonInstrInfo::isStoreToStackSlot (const MachineInstr * MI, int & FrameIndex) const override
isStoreToStackSlot - If the specified machine instruction is a direct store to a stack slot, return the virtual or physical register number of the source reg along with the FrameIndex of the loaded stack slot. If not, return 0. This predicate must return 0 if the instruction has any side effects other than storing to the stack slot.
Definition at line 102 of file HexagonInstrInfo.cpp.
isU6_0Immediate()
bool llvm::HexagonInstrInfo::isU6_0Immediate (const int value) const
isU6_1Immediate()
bool llvm::HexagonInstrInfo::isU6_1Immediate (const int value) const
isU6_2Immediate()
bool llvm::HexagonInstrInfo::isU6_2Immediate (const int value) const
isU6_3Immediate()
bool llvm::HexagonInstrInfo::isU6_3Immediate (const int value) const
isU6_Immediate()
bool llvm::HexagonInstrInfo::isU6_Immediate (const int value) const
isValidAutoIncImm()
bool HexagonInstrInfo::isValidAutoIncImm (const EVT VT, const int Offset) const
Definition at line 1177 of file HexagonInstrInfo.cpp.
References Hexagon_MEMB_AUTOINC_MAX, Hexagon_MEMB_AUTOINC_MIN, Hexagon_MEMD_AUTOINC_MAX, Hexagon_MEMD_AUTOINC_MIN, Hexagon_MEMH_AUTOINC_MAX, Hexagon_MEMH_AUTOINC_MIN, Hexagon_MEMW_AUTOINC_MAX, Hexagon_MEMW_AUTOINC_MIN, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, and llvm_unreachable.
isValidOffset()
bool HexagonInstrInfo::isValidOffset (const int Opcode, const int Offset) const
Definition at line 1087 of file HexagonInstrInfo.cpp.
References Hexagon_ADDI_OFFSET_MAX, Hexagon_ADDI_OFFSET_MIN, Hexagon_MEMB_OFFSET_MAX, Hexagon_MEMB_OFFSET_MIN, Hexagon_MEMD_OFFSET_MAX, Hexagon_MEMD_OFFSET_MIN, Hexagon_MEMH_OFFSET_MAX, Hexagon_MEMH_OFFSET_MIN, Hexagon_MEMW_OFFSET_MAX, Hexagon_MEMW_OFFSET_MIN, llvm::isUInt(), and llvm_unreachable.
loadRegFromAddr()
void HexagonInstrInfo::loadRegFromAddr (MachineFunction & MF, unsigned DestReg, SmallVectorImpl< MachineOperand > & Addr, const TargetRegisterClass * RC, SmallVectorImpl< MachineInstr * > & NewMIs) const
Definition at line 550 of file HexagonInstrInfo.cpp.
References llvm_unreachable.
loadRegFromStackSlot()
void HexagonInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 519 of file HexagonInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), Align, llvm::BuildMI(), llvm::MachineBasicBlock::findDebugLoc(), llvm::PseudoSourceValue::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), I, llvm_unreachable, and llvm::MachineMemOperand::MOLoad.
mayBeNewStore()
bool HexagonInstrInfo::mayBeNewStore (const MachineInstr * MI) const
Definition at line 1016 of file HexagonInstrInfo.cpp.
References F, getRegisterInfo(), llvm::HexagonSubtarget::hasV4TOps(), llvm::HexagonII::mayNVStoreMask, llvm::HexagonII::mayNVStorePos, and llvm::HexagonRegisterInfo::Subtarget.
NonExtEquivalentExists()
bool HexagonInstrInfo::NonExtEquivalentExists (const MachineInstr * MI) const
Definition at line 1779 of file HexagonInstrInfo.cpp.
References llvm::HexagonII::Absolute, llvm::HexagonII::BaseImmOffset, and getAddrMode().
PredicateInstruction()
bool HexagonInstrInfo::PredicateInstruction (MachineInstr * MI, const SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 794 of file HexagonInstrInfo.cpp.
References llvm::MachineRegisterInfo::clearKillFlags(), llvm::SmallVectorBase::empty(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDebug(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isKill(), isPredicable(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), and llvm_unreachable.
PredOpcodeHasJMP_c()
bool HexagonInstrInfo::PredOpcodeHasJMP_c (Opcode_t Opcode) const
Definition at line 1835 of file HexagonInstrInfo.cpp.
Referenced by AnalyzeBranch().
PredOpcodeHasNot()
bool HexagonInstrInfo::PredOpcodeHasNot (Opcode_t Opcode) const
Definition at line 1844 of file HexagonInstrInfo.cpp.
Referenced by AnalyzeBranch().
RemoveBranch()
unsigned HexagonInstrInfo::RemoveBranch (MachineBasicBlock & MBB) const override
Definition at line 310 of file HexagonInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), and I.
Referenced by InsertBranch().
ReverseBranchCondition()
bool HexagonInstrInfo::ReverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 1055 of file HexagonInstrInfo.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MachineOperand::CreateImm(), llvm::SmallVectorBase::empty(), llvm::SmallVectorImpl< T >::erase(), and llvm::SmallVectorImpl< T >::insert().
Referenced by InsertBranch().
storeRegToAddr()
void HexagonInstrInfo::storeRegToAddr (MachineFunction & MF, unsigned SrcReg, bool isKill, SmallVectorImpl< MachineOperand > & Addr, const TargetRegisterClass * RC, SmallVectorImpl< MachineInstr * > & NewMIs) const
Definition at line 508 of file HexagonInstrInfo.cpp.
References llvm_unreachable.
storeRegToStackSlot()
void HexagonInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 472 of file HexagonInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), Align, llvm::BuildMI(), llvm::MachineBasicBlock::findDebugLoc(), llvm::PseudoSourceValue::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), I, llvm_unreachable, and llvm::MachineMemOperand::MOStore.
SubsumesPredicate()
bool HexagonInstrInfo::SubsumesPredicate (const SmallVectorImpl< MachineOperand > & Pred1, const SmallVectorImpl< MachineOperand > & Pred2) const override
Definition at line 1043 of file HexagonInstrInfo.cpp.
The documentation for this class was generated from the following files:
HexagonInstrInfo.h
HexagonInstrInfo.cpp