LLVM: llvm::BitRecTy Class Reference
LLVM API Documentation
llvm::BitRecTy Class Reference
#include <Record.h>
Public Member Functions
Init * convertValue (UnsetInit *UI) override
Init * convertValue (BitInit *BI) override
Init * convertValue (BitsInit *BI) override
Init * convertValue (IntInit *II) override
Init * convertValue (StringInit *SI) override
Init * convertValue (ListInit *LI) override
Init * convertValue (VarBitInit *VB) override
Init * convertValue (DefInit *DI) override
Init * convertValue (DagInit *DI) override
Init * convertValue (UnOpInit *UI) override
Init * convertValue (BinOpInit *UI) override
Init * convertValue (TernOpInit *UI) override
Init * convertValue (TypedInit *TI) override
Init * convertValue (VarInit *VI) override
Init * convertValue (FieldInit *FI) override
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
bool baseClassOf (const RecTy *) const override
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static BitRecTy * get ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
BitRecTy - 'bit' - Represent a single bit
Definition at line 142 of file Record.h.
Member Function Documentation
baseClassOf()
bool BitRecTy::baseClassOf (const RecTy * RHS) const override virtual
Reimplemented from llvm::RecTy.
Definition at line 135 of file Record.cpp.
References llvm::RecTy::baseClassOf(), llvm::dyn_cast(), llvm::RecTy::getRecTyKind(), llvm::RecTy::IntRecTyKind, and llvm::RecTy::RecTy().
classof()
bool llvm::BitRecTy::classof (const RecTy * RT) inline static
Definition at line 147 of file Record.h.
References llvm::RecTy::BitRecTyKind, llvm::RecTy::getRecTyKind(), and llvm::RecTy::RecTy().
convertValue() [1/15]
Init * llvm::BitRecTy::convertValue (BinOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 163 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [2/15]
Init * llvm::BitRecTy::convertValue (BitInit * BI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 154 of file Record.h.
convertValue() [3/15]
Init * BitRecTy::convertValue (BitsInit * BI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 103 of file Record.cpp.
References llvm::BitsInit::getBit(), and llvm::BitsInit::getNumBits().
convertValue() [4/15]
Init * llvm::BitRecTy::convertValue (DagInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 161 of file Record.h.
convertValue() [5/15]
Init * llvm::BitRecTy::convertValue (DefInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 160 of file Record.h.
convertValue() [6/15]
Init * llvm::BitRecTy::convertValue (FieldInit * FI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 167 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [7/15]
Init * BitRecTy::convertValue (IntInit * II) override virtual
Reimplemented from llvm::RecTy.
Definition at line 108 of file Record.cpp.
References llvm::BitInit::get(), and llvm::IntInit::getValue().
convertValue() [8/15]
Init * llvm::BitRecTy::convertValue (ListInit * LI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 158 of file Record.h.
convertValue() [9/15]
Init * llvm::BitRecTy::convertValue (StringInit * SI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 157 of file Record.h.
convertValue() [10/15]
Init * llvm::BitRecTy::convertValue (TernOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 164 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [11/15]
Init * BitRecTy::convertValue (TypedInit * TI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 115 of file Record.cpp.
References llvm::dyn_cast(), get(), llvm::TernOpInit::IF, llvm::isa(), llvm::RecTy::RecTy(), and VI.
convertValue() [12/15]
Init * llvm::BitRecTy::convertValue (UnOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 162 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [13/15]
Init * llvm::BitRecTy::convertValue (UnsetInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 153 of file Record.h.
convertValue() [14/15]
Init * llvm::BitRecTy::convertValue (VarBitInit * VB) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 159 of file Record.h.
convertValue() [15/15]
Init * llvm::BitRecTy::convertValue (VarInit * VI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 166 of file Record.h.
References llvm::RecTy::convertValue(), and VI.
get()
BitRecTy * llvm::BitRecTy::get () inline static
Definition at line 151 of file Record.h.
Referenced by convertValue(), llvm::FieldInit::getBit(), llvm::OpInit::getBit(), llvm::VarInit::getBit(), and llvm::VarListElementInit::getBit().
getAsString()
std::string llvm::BitRecTy::getAsString () const inline override virtual
Implements llvm::RecTy.
Definition at line 169 of file Record.h.
typeIsConvertibleTo()
bool llvm::BitRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline override virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 171 of file Record.h.
References llvm::RecTy::baseClassOf(), and llvm::RecTy::RecTy().
The documentation for this class was generated from the following files:
Record.h
Record.cpp