LLVM: llvm::IRBuilderBase::InsertPoint Class Reference
LLVM API Documentation
llvm::IRBuilderBase::InsertPoint Class Reference
InsertPoint - A saved insertion point.
#include <IRBuilder.h>
Public Member Functions
InsertPoint ()
Creates a new insertion point which doesn't point to anything.
InsertPoint (BasicBlock *InsertBlock, BasicBlock::iterator InsertPoint)
Creates a new insertion point at the given location.
bool isSet () const
Returns true if this insert point is set.
llvm::BasicBlock * getBlock () const
llvm::BasicBlock::iterator getPoint () const
Detailed Description
InsertPoint - A saved insertion point.
Definition at line 137 of file IRBuilder.h.
Constructor & Destructor Documentation
InsertPoint() [1/2]
llvm::IRBuilderBase::InsertPoint::InsertPoint () inline
Creates a new insertion point which doesn't point to anything.
Definition at line 143 of file IRBuilder.h.
Referenced by InsertPoint().
InsertPoint() [2/2]
llvm::IRBuilderBase::InsertPoint::InsertPoint (BasicBlock * InsertBlock, BasicBlock::iterator InsertPoint) inline
Creates a new insertion point at the given location.
Definition at line 146 of file IRBuilder.h.
References InsertPoint().
Member Function Documentation
getBlock()
llvm::BasicBlock * llvm::IRBuilderBase::InsertPoint::getBlock () const inline
Definition at line 152 of file IRBuilder.h.
Referenced by llvm::IRBuilderBase::restoreIP().
getPoint()
llvm::BasicBlock::iterator llvm::IRBuilderBase::InsertPoint::getPoint () const inline
Definition at line 153 of file IRBuilder.h.
Referenced by llvm::IRBuilderBase::restoreIP().
isSet()
bool llvm::IRBuilderBase::InsertPoint::isSet () const inline
Returns true if this insert point is set.
Definition at line 150 of file IRBuilder.h.
Referenced by llvm::IRBuilderBase::restoreIP().
The documentation for this class was generated from the following file:
IRBuilder.h