LLVM: llvm::DWARFAcceleratorTable Class Reference
LLVM API Documentation
llvm::DWARFAcceleratorTable Class Reference
#include <DWARFAcceleratorTable.h>
Public Member Functions
DWARFAcceleratorTable (DataExtractor AccelSection, DataExtractor StringSection, const RelocAddrMap &Relocs)
bool extract ()
void dump (raw_ostream &OS) const
Detailed Description
Definition at line 17 of file DWARFAcceleratorTable.h.
Constructor & Destructor Documentation
DWARFAcceleratorTable()
llvm::DWARFAcceleratorTable::DWARFAcceleratorTable (DataExtractor AccelSection, DataExtractor StringSection, const RelocAddrMap & Relocs) inline
Definition at line 41 of file DWARFAcceleratorTable.h.
Member Function Documentation
dump()
void llvm::DWARFAcceleratorTable::dump (raw_ostream & OS) const
Definition at line 49 of file DWARFAcceleratorTable.cpp.
References llvm::dwarf::AtomTypeString(), llvm::format(), llvm::dwarf::FormEncodingString(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by dumpAccelSection().
extract()
bool llvm::DWARFAcceleratorTable::extract ()
Definition at line 17 of file DWARFAcceleratorTable.cpp.
Referenced by dumpAccelSection().
The documentation for this class was generated from the following files:
DWARFAcceleratorTable.h
DWARFAcceleratorTable.cpp