LLVM: llvm::BuildVectorSDNode Class Reference
LLVM API Documentation
llvm::BuildVectorSDNode Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
bool isConstantSplat (APInt &SplatValue, APInt &SplatUndef, unsigned &SplatBitSize, bool &HasAnyUndefs, unsigned MinSplatBits=0, bool isBigEndian=false) const
SDValue getSplatValue (BitVector *UndefElements=nullptr) const
Returns the splatted value or a null value if this is not a splat.
ConstantSDNode * getConstantSplatNode (BitVector *UndefElements=nullptr) const
Returns the splatted constant or null if this is not a constant splat.
ConstantFPSDNode * getConstantFPSplatNode (BitVector *UndefElements=nullptr) const
Returns the splatted constant FP or null if this is not a constant FP splat.
bool isConstant () const
Public Member Functions inherited from llvm::SDNode
unsigned getOpcode () const
bool isTargetOpcode () const
bool isTargetMemoryOpcode () const
bool isMemIntrinsic () const
bool isMachineOpcode () const
unsigned getMachineOpcode () const
bool getHasDebugValue () const
getHasDebugValue - get this bit.
void setHasDebugValue (bool b)
setHasDebugValue - set this bit.
bool use_empty () const
bool hasOneUse () const
size_t use_size () const
int getNodeId () const
void setNodeId (int Id)
setNodeId - Set unique node id.
unsigned getIROrder () const
void setIROrder (unsigned Order)
const DebugLoc getDebugLoc () const
getDebugLoc - Return the source location info.
void setDebugLoc (const DebugLoc dl)
use_iterator use_begin () const
iterator_range< use_iterator > uses ()
iterator_range< use_iterator > uses () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
bool hasAnyUseOfValue (unsigned Value) const
bool isOnlyUserOf (SDNode *N) const
bool isOperandOf (SDNode *N) const
bool isPredecessorOf (const SDNode *N) const
bool hasPredecessor (const SDNode *N) const
bool hasPredecessorHelper (const SDNode *N, SmallPtrSetImpl< const SDNode * > &Visited, SmallVectorImpl< const SDNode * > &Worklist) const
unsigned getNumOperands () const
uint64_t getConstantOperandVal (unsigned Num) const
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< SDUse > ops () const
SDVTList getVTList () const
SDNode * getGluedNode () const
const SDNode * getGluedMachineNode () const
SDNode * getGluedUser () const
unsigned getNumValues () const
EVT getValueType (unsigned ResNo) const
MVT getSimpleValueType (unsigned ResNo) const
unsigned getValueSizeInBits (unsigned ResNo) const
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=nullptr) const
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printr (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printrFull (raw_ostream &O, const SelectionDAG *G=nullptr) const
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=nullptr, unsigned depth=100) const
void dump () const
dump - Dump this node, for debugging.
void dumpr () const
dumpr - Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
void dumpr (const SelectionDAG *G) const
void dumprFull (const SelectionDAG *G=nullptr) const
void dumprWithDepth (const SelectionDAG *G=nullptr, unsigned depth=100) const
void Profile (FoldingSetNodeID &ID) const
void addUse (SDUse &U)
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node< SDNode >
SDNode * getPrevNode ()
Get the previous node, or 0 for the list head.
SDNode * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::SDNode
static use_iterator use_end ()
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Additional Inherited Members
Public Types inherited from llvm::SDNode
typedef SDUse * op_iterator
typedef const EVT * value_iterator
Protected Member Functions inherited from llvm::SDNode
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs, ArrayRef< SDValue > Ops)
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs)
void InitOperands (SDUse *Ops, const SDValue &Op0)
InitOperands - Initialize the operands list of this with 1 operand.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1)
InitOperands - Initialize the operands list of this with 2 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2)
InitOperands - Initialize the operands list of this with 3 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2, const SDValue &Op3)
InitOperands - Initialize the operands list of this with 4 operands.
void InitOperands (SDUse *Ops, const SDValue *Vals, unsigned N)
InitOperands - Initialize the operands list of this with N operands.
void DropOperands ()
Protected Member Functions inherited from llvm::ilist_node< SDNode >
ilist_node ()
Static Protected Member Functions inherited from llvm::SDNode
static SDVTList getSDVTList (EVT VT)
Protected Attributes inherited from llvm::SDNode
uint16_t SubclassData: 14
Detailed Description
BuildVectorSDNode - A "pseudo-class" with methods for operating on BUILD_VECTORs.
Definition at line 1613 of file SelectionDAGNodes.h.
Member Function Documentation
classof()
bool llvm::BuildVectorSDNode::classof (const SDNode * N) inline static
Definition at line 1655 of file SelectionDAGNodes.h.
References llvm::ISD::BUILD_VECTOR, N, and llvm::SDNode::SDNode().
getConstantFPSplatNode()
ConstantFPSDNode * BuildVectorSDNode::getConstantFPSplatNode (BitVector * UndefElements = nullptr) const
Returns the splatted constant FP or null if this is not a constant FP splat.
If passed a non-null UndefElements bitvector, it will resize it to match the vector width and set the bits where elements are undef.
Definition at line 6789 of file SelectionDAG.cpp.
References llvm::dyn_cast_or_null(), and getSplatValue().
getConstantSplatNode()
ConstantSDNode * BuildVectorSDNode::getConstantSplatNode (BitVector * UndefElements = nullptr) const
Returns the splatted constant or null if this is not a constant splat.
If passed a non-null UndefElements bitvector, it will resize it to match the vector width and set the bits where elements are undef.
Definition at line 6783 of file SelectionDAG.cpp.
References llvm::dyn_cast_or_null(), and getSplatValue().
Referenced by llvm::TargetLowering::isConstFalseVal(), and llvm::TargetLowering::isConstTrueVal().
getSplatValue()
SDValue BuildVectorSDNode::getSplatValue (BitVector * UndefElements = nullptr) const
Returns the splatted value or a null value if this is not a splat.
If passed a non-null UndefElements bitvector, it will resize it to match the vector width and set the bits where elements are undef.
Definition at line 6755 of file SelectionDAG.cpp.
References llvm::BitVector::clear(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::BitVector::resize(), and llvm::ISD::UNDEF.
Referenced by getConstantFPSplatNode(), and getConstantSplatNode().
isConstant()
bool BuildVectorSDNode::isConstant () const
Definition at line 6794 of file SelectionDAG.cpp.
References llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), and llvm::ISD::UNDEF.
Referenced by isConstantBuildVectorOrConstantInt().
isConstantSplat()
bool BuildVectorSDNode::isConstantSplat (APInt & SplatValue, APInt & SplatUndef, unsigned & SplatBitSize, bool & HasAnyUndefs, unsigned MinSplatBits = 0, bool isBigEndian = false) const
isConstantSplat - Check if this is a constant splat, and if so, find the smallest element size that splats the vector. If MinSplatBits is nonzero, the element size must be at least that large. Note that the splat element may be the entire vector (i.e., a one element vector). Returns the splat element value in SplatValue. Any undefined bits in that value are zero, and the corresponding bits in the SplatUndef mask are set. The SplatBitSize value is set to the splat element size in bits. HasAnyUndefs is set to true if any bits in the vector are undefined. isBigEndian describes the endianness of the target.
Definition at line 6689 of file SelectionDAG.cpp.
References llvm::dyn_cast(), llvm::APInt::getBitsSet(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::isVector(), llvm::APInt::lshr(), llvm::APInt::trunc(), llvm::ISD::UNDEF, and llvm::APInt::zextOrTrunc().
Referenced by getVShiftImm(), getVShiftImm(), llvm::PPC::isAllNegativeZeroVector(), isVectorAllOnes(), isVSplat(), PerformANDCombine(), performDSPShiftCombine(), PerformORCombine(), resolveBuildVector(), and tryCombineShiftImm().
The documentation for this class was generated from the following files:
SelectionDAGNodes.h
SelectionDAG.cpp