LLVM: llvm::MachineRegisterInfo Class Reference
LLVM API Documentation
llvm::MachineRegisterInfo Class Reference
#include <MachineRegisterInfo.h>
Classes
class defusechain_instr_iterator
class defusechain_iterator
class Delegate
Public Types
typedef defusechain_iterator< true, true, false, true, false, false > reg_iterator
typedef defusechain_instr_iterator< true, true, false, false, true, false > reg_instr_iterator
typedef defusechain_instr_iterator< true, true, false, false, false, true > reg_bundle_iterator
typedef defusechain_iterator< true, true, true, true, false, false > reg_nodbg_iterator
typedef defusechain_instr_iterator< true, true, true, false, true, false > reg_instr_nodbg_iterator
typedef defusechain_instr_iterator< true, true, true, false, false, true > reg_bundle_nodbg_iterator
typedef defusechain_iterator< false, true, false, true, false, false > def_iterator
def_iterator/def_begin/def_end - Walk all defs of the specified register.
typedef defusechain_instr_iterator< false, true, false, false, true, false > def_instr_iterator
typedef defusechain_instr_iterator< false, true, false, false, false, true > def_bundle_iterator
typedef defusechain_iterator< true, false, false, true, false, false > use_iterator
use_iterator/use_begin/use_end - Walk all uses of the specified register.
typedef defusechain_instr_iterator< true, false, false, false, true, false > use_instr_iterator
typedef defusechain_instr_iterator< true, false, false, false, false, true > use_bundle_iterator
typedef defusechain_iterator< true, false, true, true, false, false > use_nodbg_iterator
typedef defusechain_instr_iterator< true, false, true, false, true, false > use_instr_nodbg_iterator
typedef defusechain_instr_iterator< true, false, true, false, false, true > use_bundle_nodbg_iterator
typedef std::vector< std::pair< unsigned, unsigned > >::const_iterator livein_iterator
Public Member Functions
MachineRegisterInfo (const MachineFunction *MF)
const TargetRegisterInfo * getTargetRegisterInfo () const
void resetDelegate (Delegate *delegate)
void setDelegate (Delegate *delegate)
bool isSSA () const
void leaveSSA ()
bool tracksLiveness () const
void invalidateLiveness ()
bool tracksSubRegLiveness () const
void enableSubRegLiveness (bool Enable=true)
void addRegOperandToUseList (MachineOperand *MO)
Add MO to the linked list of operands for its register.
void removeRegOperandFromUseList (MachineOperand *MO)
Remove MO from its use-def list.
void moveOperands (MachineOperand *Dst, MachineOperand *Src, unsigned NumOps)
void verifyUseList (unsigned Reg) const
Verify the sanity of the use list for Reg.
void verifyUseLists () const
Verify the use list of all registers.
reg_iterator reg_begin (unsigned RegNo) const
iterator_range< reg_iterator > reg_operands (unsigned Reg) const
reg_instr_iterator reg_instr_begin (unsigned RegNo) const
iterator_range< reg_instr_iterator > reg_instructions (unsigned Reg) const
reg_bundle_iterator reg_bundle_begin (unsigned RegNo) const
iterator_range< reg_bundle_iterator > reg_bundles (unsigned Reg) const
bool reg_empty (unsigned RegNo) const
reg_nodbg_iterator reg_nodbg_begin (unsigned RegNo) const
iterator_range< reg_nodbg_iterator > reg_nodbg_operands (unsigned Reg) const
reg_instr_nodbg_iterator reg_instr_nodbg_begin (unsigned RegNo) const
iterator_range< reg_instr_nodbg_iterator > reg_nodbg_instructions (unsigned Reg) const
reg_bundle_nodbg_iterator reg_bundle_nodbg_begin (unsigned RegNo) const
iterator_range< reg_bundle_nodbg_iterator > reg_nodbg_bundles (unsigned Reg) const
bool reg_nodbg_empty (unsigned RegNo) const
def_iterator def_begin (unsigned RegNo) const
iterator_range< def_iterator > def_operands (unsigned Reg) const
def_instr_iterator def_instr_begin (unsigned RegNo) const
iterator_range< def_instr_iterator > def_instructions (unsigned Reg) const
def_bundle_iterator def_bundle_begin (unsigned RegNo) const
iterator_range< def_bundle_iterator > def_bundles (unsigned Reg) const
bool def_empty (unsigned RegNo) const
bool hasOneDef (unsigned RegNo) const
use_iterator use_begin (unsigned RegNo) const
iterator_range< use_iterator > use_operands (unsigned Reg) const
use_instr_iterator use_instr_begin (unsigned RegNo) const
iterator_range< use_instr_iterator > use_instructions (unsigned Reg) const
use_bundle_iterator use_bundle_begin (unsigned RegNo) const
iterator_range< use_bundle_iterator > use_bundles (unsigned Reg) const
bool use_empty (unsigned RegNo) const
bool hasOneUse (unsigned RegNo) const
use_nodbg_iterator use_nodbg_begin (unsigned RegNo) const
iterator_range< use_nodbg_iterator > use_nodbg_operands (unsigned Reg) const
use_instr_nodbg_iterator use_instr_nodbg_begin (unsigned RegNo) const
iterator_range< use_instr_nodbg_iterator > use_nodbg_instructions (unsigned Reg) const
use_bundle_nodbg_iterator use_bundle_nodbg_begin (unsigned RegNo) const
iterator_range< use_bundle_nodbg_iterator > use_nodbg_bundles (unsigned Reg) const
bool use_nodbg_empty (unsigned RegNo) const
bool hasOneNonDBGUse (unsigned RegNo) const
void replaceRegWith (unsigned FromReg, unsigned ToReg)
MachineInstr * getVRegDef (unsigned Reg) const
MachineInstr * getUniqueVRegDef (unsigned Reg) const
void clearKillFlags (unsigned Reg) const
void dumpUses (unsigned RegNo) const
bool isConstantPhysReg (unsigned PhysReg, const MachineFunction &MF) const
PSetIterator getPressureSets (unsigned RegUnit) const
const TargetRegisterClass * getRegClass (unsigned Reg) const
void setRegClass (unsigned Reg, const TargetRegisterClass *RC)
const TargetRegisterClass * constrainRegClass (unsigned Reg, const TargetRegisterClass *RC, unsigned MinNumRegs=0)
bool recomputeRegClass (unsigned Reg, const TargetMachine &)
unsigned createVirtualRegister (const TargetRegisterClass *RegClass)
unsigned getNumVirtRegs () const
void clearVirtRegs ()
clearVirtRegs - Remove all virtual registers (after physreg assignment).
void setRegAllocationHint (unsigned Reg, unsigned Type, unsigned PrefReg)
std::pair< unsigned, unsigned > getRegAllocationHint (unsigned Reg) const
unsigned getSimpleHint (unsigned Reg) const
void markUsesInDebugValueAsUndef (unsigned Reg) const
bool isPhysRegUsed (unsigned Reg) const
void setRegUnitUsed (unsigned RegUnit)
void setPhysRegUsed (unsigned Reg)
void addPhysRegsUsedFromRegMask (const uint32_t *RegMask)
void setPhysRegUnused (unsigned Reg)
void freezeReservedRegs (const MachineFunction &)
bool reservedRegsFrozen () const
bool canReserveReg (unsigned PhysReg) const
const BitVector & getReservedRegs () const
bool isReserved (unsigned PhysReg) const
bool isAllocatable (unsigned PhysReg) const
void addLiveIn (unsigned Reg, unsigned vreg=0)
livein_iterator livein_begin () const
livein_iterator livein_end () const
bool livein_empty () const
bool isLiveIn (unsigned Reg) const
unsigned getLiveInPhysReg (unsigned VReg) const
unsigned getLiveInVirtReg (unsigned PReg) const
void EmitLiveInCopies (MachineBasicBlock *EntryMBB, const TargetRegisterInfo &TRI, const TargetInstrInfo &TII)
unsigned getMaxLaneMaskForVReg (unsigned Reg) const
Static Public Member Functions
static reg_iterator reg_end ()
static reg_instr_iterator reg_instr_end ()
static reg_bundle_iterator reg_bundle_end ()
static reg_nodbg_iterator reg_nodbg_end ()
static reg_instr_nodbg_iterator reg_instr_nodbg_end ()
static reg_bundle_nodbg_iterator reg_bundle_nodbg_end ()
static def_iterator def_end ()
static def_instr_iterator def_instr_end ()
static def_bundle_iterator def_bundle_end ()
static use_iterator use_end ()
static use_instr_iterator use_instr_end ()
static use_bundle_iterator use_bundle_end ()
static use_nodbg_iterator use_nodbg_end ()
static use_instr_nodbg_iterator use_instr_nodbg_end ()
static use_bundle_nodbg_iterator use_bundle_nodbg_end ()
Friends
template<bool, bool, bool, bool, bool, bool>
class defusechain_iterator
template<bool, bool, bool, bool, bool, bool>
class defusechain_instr_iterator
Detailed Description
MachineRegisterInfo - Keep track of information for virtual and physical registers, including vreg register classes, use/def chains for registers, etc.
Definition at line 32 of file MachineRegisterInfo.h.
Member Typedef Documentation
def_bundle_iterator
typedef defusechain_instr_iterator<false,true,false,false,false,true> llvm::MachineRegisterInfo::def_bundle_iterator
def_bundle_iterator/def_bundle_begin/def_bundle_end - Walk all defs of the specified register, stepping by bundle.
Definition at line 369 of file MachineRegisterInfo.h.
def_instr_iterator
typedef defusechain_instr_iterator<false,true,false,false,true,false> llvm::MachineRegisterInfo::def_instr_iterator
def_instr_iterator/def_instr_begin/def_instr_end - Walk all defs of the specified register, stepping by MachineInst.
Definition at line 352 of file MachineRegisterInfo.h.
def_iterator
typedef defusechain_iterator<false,true,false,true,false,false> llvm::MachineRegisterInfo::def_iterator
def_iterator/def_begin/def_end - Walk all defs of the specified register.
Definition at line 339 of file MachineRegisterInfo.h.
livein_iterator
typedef std::vector<std::pair<unsigned,unsigned>>::const_iterator llvm::MachineRegisterInfo::livein_iterator
Definition at line 759 of file MachineRegisterInfo.h.
reg_bundle_iterator
typedef defusechain_instr_iterator<true,true,false,false,false,true> llvm::MachineRegisterInfo::reg_bundle_iterator
reg_bundle_iterator/reg_bundle_begin/reg_bundle_end - Walk all defs and uses of the specified register, stepping by bundle.
Definition at line 261 of file MachineRegisterInfo.h.
reg_bundle_nodbg_iterator
typedef defusechain_instr_iterator<true,true,true,false,false,true> llvm::MachineRegisterInfo::reg_bundle_nodbg_iterator
reg_bundle_nodbg_iterator/reg_bundle_nodbg_begin/reg_bundle_nodbg_end - Walk all defs and uses of the specified register, stepping by bundle, skipping those marked as Debug.
Definition at line 317 of file MachineRegisterInfo.h.
reg_instr_iterator
typedef defusechain_instr_iterator<true,true,false,false,true,false> llvm::MachineRegisterInfo::reg_instr_iterator
reg_instr_iterator/reg_instr_begin/reg_instr_end - Walk all defs and uses of the specified register, stepping by MachineInstr.
Definition at line 244 of file MachineRegisterInfo.h.
reg_instr_nodbg_iterator
typedef defusechain_instr_iterator<true,true,true,false,true,false> llvm::MachineRegisterInfo::reg_instr_nodbg_iterator
reg_instr_nodbg_iterator/reg_instr_nodbg_begin/reg_instr_nodbg_end - Walk all defs and uses of the specified register, stepping by MachineInstr, skipping those marked as Debug.
Definition at line 299 of file MachineRegisterInfo.h.
reg_iterator
typedef defusechain_iterator<true,true,false,true,false,false> llvm::MachineRegisterInfo::reg_iterator
reg_iterator/reg_begin/reg_end - Walk all defs and uses of the specified register.
Definition at line 231 of file MachineRegisterInfo.h.
reg_nodbg_iterator
typedef defusechain_iterator<true,true,true,true,false,false> llvm::MachineRegisterInfo::reg_nodbg_iterator
reg_nodbg_iterator/reg_nodbg_begin/reg_nodbg_end - Walk all defs and uses of the specified register, skipping those marked as Debug.
Definition at line 281 of file MachineRegisterInfo.h.
use_bundle_iterator
typedef defusechain_instr_iterator<true,false,false,false,false,true> llvm::MachineRegisterInfo::use_bundle_iterator
use_bundle_iterator/use_bundle_begin/use_bundle_end - Walk all uses of the specified register, stepping by bundle.
Definition at line 427 of file MachineRegisterInfo.h.
use_bundle_nodbg_iterator
typedef defusechain_instr_iterator<true,false,true,false,false,true> llvm::MachineRegisterInfo::use_bundle_nodbg_iterator
use_bundle_nodbg_iterator/use_bundle_nodbg_begin/use_bundle_nodbg_end - Walk all uses of the specified register, stepping by bundle, skipping those marked as Debug.
Definition at line 492 of file MachineRegisterInfo.h.
use_instr_iterator
typedef defusechain_instr_iterator<true,false,false,false,true,false> llvm::MachineRegisterInfo::use_instr_iterator
use_instr_iterator/use_instr_begin/use_instr_end - Walk all uses of the specified register, stepping by MachineInstr.
Definition at line 410 of file MachineRegisterInfo.h.
use_instr_nodbg_iterator
typedef defusechain_instr_iterator<true,false,true,false,true,false> llvm::MachineRegisterInfo::use_instr_nodbg_iterator
use_instr_nodbg_iterator/use_instr_nodbg_begin/use_instr_nodbg_end - Walk all uses of the specified register, stepping by MachineInstr, skipping those marked as Debug.
Definition at line 474 of file MachineRegisterInfo.h.
use_iterator
typedef defusechain_iterator<true,false,false,true,false,false> llvm::MachineRegisterInfo::use_iterator
use_iterator/use_begin/use_end - Walk all uses of the specified register.
Definition at line 397 of file MachineRegisterInfo.h.
use_nodbg_iterator
typedef defusechain_iterator<true,false,true,true,false,false> llvm::MachineRegisterInfo::use_nodbg_iterator
use_nodbg_iterator/use_nodbg_begin/use_nodbg_end - Walk all uses of the specified register, skipping those marked as Debug.
Definition at line 456 of file MachineRegisterInfo.h.
Constructor & Destructor Documentation
MachineRegisterInfo()
MachineRegisterInfo::MachineRegisterInfo (const MachineFunction * MF) explicit
Definition at line 26 of file MachineRegisterInfo.cpp.
References getTargetRegisterInfo(), and true.
Member Function Documentation
addLiveIn()
void llvm::MachineRegisterInfo::addLiveIn (unsigned Reg, unsigned vreg = 0) inline
addLiveIn - Add the specified register as a live-in. Note that it is an error to add the same register to the same set more than once.
Definition at line 752 of file MachineRegisterInfo.h.
Referenced by addLiveIn(), llvm::MachineFunction::addLiveIn(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), and llvm::R600TargetLowering::LowerOperation().
addPhysRegsUsedFromRegMask()
void llvm::MachineRegisterInfo::addPhysRegsUsedFromRegMask (const uint32_t * RegMask) inline
addPhysRegsUsedFromRegMask - Mark any registers not in RegMask as used. This corresponds to the bit mask attached to register mask operands.
Definition at line 673 of file MachineRegisterInfo.h.
addRegOperandToUseList()
void MachineRegisterInfo::addRegOperandToUseList (MachineOperand * MO)
Add MO to the linked list of operands for its register.
Definition at line 169 of file MachineRegisterInfo.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), llvm::MachineOperand::Next, llvm::MachineOperand::Prev, llvm::MachineOperand::Reg, and llvm::Registry< T, U >::Head.
Referenced by llvm::MachineInstr::addOperand(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineOperand::setIsDef(), and llvm::MachineOperand::setReg().
canReserveReg()
bool llvm::MachineRegisterInfo::canReserveReg (unsigned PhysReg) const inline
canReserveReg - Returns true if PhysReg can be used as a reserved register. Any register can be reserved before freezeReservedRegs() is called.
Definition at line 712 of file MachineRegisterInfo.h.
References reservedRegsFrozen().
Referenced by llvm::ARMBaseRegisterInfo::canRealignStack(), and llvm::X86RegisterInfo::canRealignStack().
clearKillFlags()
void MachineRegisterInfo::clearKillFlags (unsigned Reg) const
clearKillFlags - Iterate over all the uses of the given register and clear the kill flag from the MachineOperand. This function is used by optimization passes which extend register lifetimes and need only preserve conservative kill flag information.
Definition at line 334 of file MachineRegisterInfo.cpp.
References use_operands().
Referenced by llvm::AArch64InstrInfo::insertSelect(), and llvm::HexagonInstrInfo::PredicateInstruction().
clearVirtRegs()
void MachineRegisterInfo::clearVirtRegs ()
clearVirtRegs - Remove all virtual registers (after physreg assignment).
Definition at line 108 of file MachineRegisterInfo.cpp.
References getNumVirtRegs(), llvm::TargetRegisterInfo::index2VirtReg(), llvm_unreachable, and verifyUseList().
Referenced by llvm::PEI::runOnMachineFunction().
constrainRegClass()
const TargetRegisterClass * MachineRegisterInfo::constrainRegClass (unsigned Reg, const TargetRegisterClass * RC, unsigned MinNumRegs = 0)
constrainRegClass - Constrain the register class of the specified virtual register to be a common subclass of RC and the current register class, but only if the new class has at least MinNumRegs registers. Return the new register class, or NULL if no such class exists. This should only be used when the constraint is known to be trivial, like GR32 -> GR32_NOSP. Beware of increasing register pressure.
Definition at line 47 of file MachineRegisterInfo.cpp.
References llvm::TargetRegisterInfo::getCommonSubClass(), llvm::TargetRegisterClass::getNumRegs(), getRegClass(), getTargetRegisterInfo(), and setRegClass().
Referenced by llvm::MachineBasicBlock::addLiveIn(), llvm::X86InstrInfo::classifyLEAReg(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), genMadd(), genMaddR(), llvm::AArch64InstrInfo::insertSelect(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), and UpdateOperandRegClass().
createVirtualRegister()
unsigned MachineRegisterInfo::createVirtualRegister (const TargetRegisterClass * RegClass)
createVirtualRegister - Create and return a new virtual register in the function with the specified register class.
Definition at line 92 of file MachineRegisterInfo.cpp.
References getNumVirtRegs(), llvm::TargetRegisterInfo::index2VirtReg(), and llvm::TargetRegisterClass::isAllocatable().
Referenced by addLiveIn(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::addLiveIn(), llvm::X86InstrInfo::classifyLEAReg(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), llvm::HexagonInstrInfo::createVR(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitThumbRegPlusImmInReg(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::ARMBaseInstrInfo::FoldImmediate(), forceReg(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::SparcInstrInfo::getGlobalBaseReg(), llvm::X86InstrInfo::getGlobalBaseReg(), GetRegistersForValue(), InsertNewDef(), llvm::PPCInstrInfo::insertSelect(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), llvm::SIInstrInfo::moveSMRDToVALU(), llvm::SIInstrInfo::moveToVALU(), and llvm::SIInstrInfo::splitSMRD().
def_begin()
def_iterator llvm::MachineRegisterInfo::def_begin (unsigned RegNo) const inline
Definition at line 340 of file MachineRegisterInfo.h.
Referenced by def_empty(), def_operands(), hasOneDef(), isKilled(), and MustSaveLR().
def_bundle_begin()
def_bundle_iterator llvm::MachineRegisterInfo::def_bundle_begin (unsigned RegNo) const inline
Definition at line 370 of file MachineRegisterInfo.h.
Referenced by def_bundles().
def_bundle_end()
def_bundle_iterator llvm::MachineRegisterInfo::def_bundle_end () inline static
Definition at line 373 of file MachineRegisterInfo.h.
Referenced by def_bundles().
def_bundles()
iterator_range< def_bundle_iterator > llvm::MachineRegisterInfo::def_bundles (unsigned Reg) const inline
Definition at line 377 of file MachineRegisterInfo.h.
References def_bundle_begin(), and def_bundle_end().
def_empty()
bool llvm::MachineRegisterInfo::def_empty (unsigned RegNo) const inline
def_empty - Return true if there are no instructions defining the specified register (it may be live-in).
Definition at line 384 of file MachineRegisterInfo.h.
References def_begin(), and def_end().
Referenced by getUniqueVRegDef(), and isConstantPhysReg().
def_end()
def_iterator llvm::MachineRegisterInfo::def_end () inline static
Definition at line 343 of file MachineRegisterInfo.h.
Referenced by def_empty(), def_operands(), hasOneDef(), isKilled(), and MustSaveLR().
def_instr_begin()
def_instr_iterator llvm::MachineRegisterInfo::def_instr_begin (unsigned RegNo) const inline
Definition at line 353 of file MachineRegisterInfo.h.
Referenced by def_instructions(), getUniqueVRegDef(), getVRegDef(), and regIsPICBase().
def_instr_end()
def_instr_iterator llvm::MachineRegisterInfo::def_instr_end () inline static
Definition at line 356 of file MachineRegisterInfo.h.
Referenced by def_instructions(), getUniqueVRegDef(), getVRegDef(), and regIsPICBase().
def_instructions()
iterator_range< def_instr_iterator > llvm::MachineRegisterInfo::def_instructions (unsigned Reg) const inline
Definition at line 361 of file MachineRegisterInfo.h.
References def_instr_begin(), and def_instr_end().
Referenced by isImplicitlyDefined().
def_operands()
iterator_range< def_iterator > llvm::MachineRegisterInfo::def_operands (unsigned Reg) const inline
Definition at line 345 of file MachineRegisterInfo.h.
References def_begin(), and def_end().
dumpUses()
void MachineRegisterInfo::dumpUses (unsigned RegNo) const
Definition at line 405 of file MachineRegisterInfo.cpp.
References I, and use_instructions().
EmitLiveInCopies()
void MachineRegisterInfo::EmitLiveInCopies (MachineBasicBlock * EntryMBB, const TargetRegisterInfo & TRI, const TargetInstrInfo & TII)
EmitLiveInCopies - Emit copies to initialize livein virtual registers into the given entry block.
Definition at line 367 of file MachineRegisterInfo.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::TargetOpcode::COPY, TII, and use_empty().
enableSubRegLiveness()
void llvm::MachineRegisterInfo::enableSubRegLiveness (bool Enable = true) inline
Definition at line 187 of file MachineRegisterInfo.h.
freezeReservedRegs()
void MachineRegisterInfo::freezeReservedRegs (const MachineFunction & MF)
freezeReservedRegs - Called by the register allocator to freeze the set of reserved registers before allocation begins.
Definition at line 411 of file MachineRegisterInfo.cpp.
References llvm::TargetRegisterInfo::getReservedRegs(), and getTargetRegisterInfo().
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
getLiveInPhysReg()
unsigned MachineRegisterInfo::getLiveInPhysReg (unsigned VReg) const
getLiveInPhysReg - If VReg is a live-in virtual register, return the corresponding live-in physical register.
Definition at line 348 of file MachineRegisterInfo.cpp.
References I, livein_begin(), and livein_end().
getLiveInVirtReg()
unsigned MachineRegisterInfo::getLiveInVirtReg (unsigned PReg) const
getLiveInVirtReg - If PReg is a live-in physical register, return the corresponding live-in physical register.
Definition at line 357 of file MachineRegisterInfo.cpp.
References I, livein_begin(), and livein_end().
Referenced by llvm::MachineFunction::addLiveIn(), and llvm::AMDGPUTargetLowering::CreateLiveInRegister().
getMaxLaneMaskForVReg()
unsigned MachineRegisterInfo::getMaxLaneMaskForVReg (unsigned Reg) const
Returns a mask covering all bits that can appear in lane masks of subregisters of the virtual register Reg.
Definition at line 396 of file MachineRegisterInfo.cpp.
References llvm::TargetRegisterClass::getLaneMask(), getRegClass(), and llvm::TargetRegisterInfo::isVirtualRegister().
Referenced by llvm::LiveInterval::verify().
getNumVirtRegs()
unsigned llvm::MachineRegisterInfo::getNumVirtRegs () const inline
getNumVirtRegs - Return the number of virtual registers created.
Definition at line 605 of file MachineRegisterInfo.h.
Referenced by llvm::calculateSpillWeightsAndHints(), clearVirtRegs(), createVirtualRegister(), llvm::PEI::runOnMachineFunction(), llvm::MachineBasicBlock::SplitCriticalEdge(), and verifyUseLists().
getPressureSets()
PSetIterator llvm::MachineRegisterInfo::getPressureSets (unsigned RegUnit) const inline
Get an iterator over the pressure sets affected by the given physical or virtual register. If RegUnit is physical, it must be a register unit (from MCRegUnitIterator).
Definition at line 1022 of file MachineRegisterInfo.h.
Referenced by llvm::PressureDiff::addPressureChange().
getRegAllocationHint()
std::pair< unsigned, unsigned > llvm::MachineRegisterInfo::getRegAllocationHint (unsigned Reg) const inline
getRegAllocationHint - Return the register allocation hint for the specified virtual register.
Definition at line 620 of file MachineRegisterInfo.h.
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), getSimpleHint(), and llvm::ARMBaseRegisterInfo::UpdateRegAllocHint().
getRegClass()
const TargetRegisterClass * llvm::MachineRegisterInfo::getRegClass (unsigned Reg) const inline
getRegClass - Return the register class of the specified virtual register.
Definition at line 569 of file MachineRegisterInfo.h.
Referenced by llvm::MachineFunction::addLiveIn(), llvm::AllocationOrder::AllocationOrder(), canFoldCopy(), canFoldIntoCSel(), llvm::AArch64InstrInfo::canInsertSelect(), llvm::PPCInstrInfo::canInsertSelect(), llvm::X86InstrInfo::canInsertSelect(), constrainRegClass(), llvm::SystemZInstrInfo::convertToThreeAddress(), copyHint(), llvm::NVPTXInstrInfo::copyPhysReg(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), GetCostForDef(), getMaxLaneMaskForVReg(), llvm::PPCInstrInfo::getOperandLatency(), llvm::SIInstrInfo::getOpRegClass(), getRegTy(), hasVGPROperands(), llvm::PPCInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), isFPR64(), isGPR64(), llvm::SIInstrInfo::isOperandLegal(), isPartialRegisterLoad(), isVGPR(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::moveToVALU(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::MachineInstr::print(), llvm::PSetIterator::PSetIterator(), recomputeRegClass(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::CoalescerPair::setRegisters(), UpdateOperandRegClass(), and llvm::SIInstrInfo::usesConstantBus().
getReservedRegs()
const BitVector & llvm::MachineRegisterInfo::getReservedRegs () const inline
getReservedRegs - Returns a reference to the frozen set of reserved registers. This method should always be preferred to calling TRI::getReservedRegs() when possible.
Definition at line 719 of file MachineRegisterInfo.h.
References reservedRegsFrozen().
Referenced by isReserved().
getSimpleHint()
unsigned llvm::MachineRegisterInfo::getSimpleHint (unsigned Reg) const inline
getSimpleHint - Return the preferred register allocation hint, or 0 if a standard simple hint (Type == 0) is not set.
Definition at line 626 of file MachineRegisterInfo.h.
References getRegAllocationHint(), and Hint().
getTargetRegisterInfo()
const TargetRegisterInfo * llvm::MachineRegisterInfo::getTargetRegisterInfo () const inline
Definition at line 131 of file MachineRegisterInfo.h.
Referenced by constrainRegClass(), freezeReservedRegs(), isAllocatable(), isConstantPhysReg(), isPhysRegUsed(), MachineRegisterInfo(), llvm::MachineInstr::print(), llvm::PSetIterator::PSetIterator(), recomputeRegClass(), replaceRegWith(), setPhysRegUnused(), setPhysRegUsed(), llvm::ARMBaseRegisterInfo::shouldCoalesce(), llvm::tryFoldSPUpdateIntoPushPop(), verifyUseList(), and verifyUseLists().
getUniqueVRegDef()
MachineInstr * MachineRegisterInfo::getUniqueVRegDef (unsigned Reg) const
getUniqueVRegDef - Return the unique machine instr that defines the specified virtual register or null if none is found. If there are multiple definitions or no definition, return null.
Definition at line 315 of file MachineRegisterInfo.cpp.
References def_empty(), def_instr_begin(), def_instr_end(), and I.
Referenced by canCombineWithMUL(), foldImmediates(), genMadd(), genMaddR(), getDef(), llvm::AArch64InstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), and llvm::X86InstrInfo::optimizeCompareInstr().
getVRegDef()
MachineInstr * MachineRegisterInfo::getVRegDef (unsigned Reg) const
getVRegDef - Return the machine instr that defines the specified virtual register or null if none is found. This assumes that the code is in SSA form, so there should only be one definition.
Definition at line 304 of file MachineRegisterInfo.cpp.
References def_instr_begin(), def_instr_end(), and I.
Referenced by canCompareBeNewValueJump(), canFoldIntoCSel(), canFoldIntoMOVCC(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), MatchingStackOffset(), MatchingStackOffset(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::X86InstrInfo::optimizeLoadInstr(), llvm::ARMBaseInstrInfo::produceSameValue(), removeCopies(), and llvm::SSAUpdaterTraits< MachineSSAUpdater >::ValueIsPHI().
hasOneDef()
bool llvm::MachineRegisterInfo::hasOneDef (unsigned RegNo) const inline
hasOneDef - Return true if there is exactly one instruction defining the specified register.
Definition at line 388 of file MachineRegisterInfo.h.
References def_begin(), and def_end().
hasOneNonDBGUse()
bool MachineRegisterInfo::hasOneNonDBGUse (unsigned RegNo) const
hasOneNonDBGUse - Return true if there is exactly one non-Debug instruction using the specified register.
Definition at line 323 of file MachineRegisterInfo.cpp.
References use_nodbg_begin(), and use_nodbg_end().
Referenced by canCombineWithMUL(), canFoldIntoMOVCC(), findOnlyInterestingUse(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::PPCInstrInfo::FoldImmediate(), and isOperandKill().
hasOneUse()
bool llvm::MachineRegisterInfo::hasOneUse (unsigned RegNo) const inline
hasOneUse - Return true if there is exactly one instruction using the specified register.
Definition at line 446 of file MachineRegisterInfo.h.
References use_begin(), and use_end().
Referenced by isKilled().
invalidateLiveness()
void llvm::MachineRegisterInfo::invalidateLiveness () inline
invalidateLiveness - Indicates that register liveness is no longer being tracked accurately.
This should be called by late passes that invalidate the liveness information.
Definition at line 183 of file MachineRegisterInfo.h.
Referenced by llvm::BranchFolder::OptimizeFunction().
isAllocatable()
bool llvm::MachineRegisterInfo::isAllocatable (unsigned PhysReg) const inline
isAllocatable - Returns true when PhysReg belongs to an allocatable register class and it hasn't been reserved.
Allocatable registers may show up in the allocation order of some virtual register, so a register allocator needs to track its liveness and availability.
Definition at line 741 of file MachineRegisterInfo.h.
References getTargetRegisterInfo(), llvm::TargetRegisterInfo::isInAllocatableClass(), and isReserved().
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), and isConstantPhysReg().
isConstantPhysReg()
bool MachineRegisterInfo::isConstantPhysReg (unsigned PhysReg, const MachineFunction & MF) const
isConstantPhysReg - Returns true if PhysReg is unallocatable and constant throughout the function. It is safe to move instructions that read such a physreg.
Definition at line 417 of file MachineRegisterInfo.cpp.
References def_empty(), getTargetRegisterInfo(), isAllocatable(), llvm::TargetRegisterInfo::isPhysicalRegister(), and llvm::MCRegAliasIterator::isValid().
isLiveIn()
bool MachineRegisterInfo::isLiveIn (unsigned Reg) const
Definition at line 339 of file MachineRegisterInfo.cpp.
References I, livein_begin(), and livein_end().
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::AMDGPUTargetLowering::CreateLiveInRegister(), getPrologueDeath(), and llvm::Thumb1FrameLowering::spillCalleeSavedRegisters().
isPhysRegUsed()
bool llvm::MachineRegisterInfo::isPhysRegUsed (unsigned Reg) const inline
isPhysRegUsed - Return true if the specified register is used in this function. Also check for clobbered aliases and registers clobbered by function calls with register mask operands.
This only works after register allocation. It is primarily used by PrologEpilogInserter to determine which callee-saved registers need spilling.
Definition at line 647 of file MachineRegisterInfo.h.
References getTargetRegisterInfo(), and llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by checkNumAlignedDPRCS2Regs(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::SIRegisterInfo::findUnusedRegister(), HandleVRSaveUpdate(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), and verifyLeafProcRegUse().
isReserved()
bool llvm::MachineRegisterInfo::isReserved (unsigned PhysReg) const inline
isReserved - Returns true when PhysReg is a reserved register.
Reserved registers may belong to an allocatable register class, but the target has explicitly requested that they are not used.
Definition at line 731 of file MachineRegisterInfo.h.
References getReservedRegs(), and llvm::BitVector::test().
Referenced by llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), isAllocatable(), and llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan().
isSSA()
bool llvm::MachineRegisterInfo::isSSA () const inline
Definition at line 163 of file MachineRegisterInfo.h.
Referenced by foldImmediates().
leaveSSA()
void llvm::MachineRegisterInfo::leaveSSA () inline
Definition at line 166 of file MachineRegisterInfo.h.
livein_begin()
livein_iterator llvm::MachineRegisterInfo::livein_begin () const inline
Definition at line 760 of file MachineRegisterInfo.h.
Referenced by checkFnHasLiveInYmm(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), getLiveInPhysReg(), getLiveInVirtReg(), HandleVRSaveUpdate(), isEAXLiveIn(), and isLiveIn().
livein_empty()
bool llvm::MachineRegisterInfo::livein_empty () const inline
Definition at line 762 of file MachineRegisterInfo.h.
Referenced by llvm::AMDGPUInstrInfo::getIndirectIndexBegin().
livein_end()
livein_iterator llvm::MachineRegisterInfo::livein_end () const inline
Definition at line 761 of file MachineRegisterInfo.h.
Referenced by checkFnHasLiveInYmm(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), getLiveInPhysReg(), getLiveInVirtReg(), HandleVRSaveUpdate(), isEAXLiveIn(), and isLiveIn().
markUsesInDebugValueAsUndef()
void MachineRegisterInfo::markUsesInDebugValueAsUndef (unsigned Reg) const
markUsesInDebugValueAsUndef - Mark every DBG_VALUE referencing the specified register as undefined which causes the DBG_VALUE to be deleted during LiveDebugVariables analysis.
Definition at line 433 of file MachineRegisterInfo.cpp.
References llvm::MachineInstr::getOperand(), I, llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::setReg(), use_instr_begin(), and use_instr_end().
Referenced by llvm::MachineInstr::eraseFromParentAndMarkDBGValuesForRemoval().
moveOperands()
void MachineRegisterInfo::moveOperands (MachineOperand * Dst, MachineOperand * Src, unsigned NumOps)
Move NumOps operands from Src to Dst, updating use-def lists as needed.
The Dst range is assumed to be uninitialized memory. (Or it may contain operands that won't be destroyed, which is OK because the MO destructor is trivial anyway).
The Src and Dst ranges may overlap.
Definition at line 237 of file MachineRegisterInfo.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), llvm::MachineOperand::Next, llvm::MachineOperand::Prev, llvm::MachineOperand::Reg, and llvm::Registry< T, U >::Head.
Referenced by moveOperands().
recomputeRegClass()
bool MachineRegisterInfo::recomputeRegClass (unsigned Reg, const TargetMachine & TM)
recomputeRegClass - Try to find a legal super-class of Reg's register class that still satisfies the constraints from the instructions using Reg. Returns true if Reg was upgraded.
This method can be used after constraints have been removed from a virtual register, for example after removing instructions or splitting the live range.
Definition at line 64 of file MachineRegisterInfo.cpp.
References llvm::TargetRegisterInfo::getLargestLegalSuperClass(), getRegClass(), getTargetRegisterInfo(), reg_nodbg_operands(), setRegClass(), and TII.
reg_begin()
reg_iterator llvm::MachineRegisterInfo::reg_begin (unsigned RegNo) const inline
Definition at line 232 of file MachineRegisterInfo.h.
Referenced by llvm::ConnectedVNInfoEqClasses::Distribute(), reg_empty(), reg_operands(), and replaceRegWith().
reg_bundle_begin()
reg_bundle_iterator llvm::MachineRegisterInfo::reg_bundle_begin (unsigned RegNo) const inline
Definition at line 262 of file MachineRegisterInfo.h.
Referenced by reg_bundles().
reg_bundle_end()
reg_bundle_iterator llvm::MachineRegisterInfo::reg_bundle_end () inline static
Definition at line 265 of file MachineRegisterInfo.h.
Referenced by reg_bundles().
reg_bundle_nodbg_begin()
reg_bundle_nodbg_iterator llvm::MachineRegisterInfo::reg_bundle_nodbg_begin (unsigned RegNo) const inline
Definition at line 318 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_bundles().
reg_bundle_nodbg_end()
reg_bundle_nodbg_iterator llvm::MachineRegisterInfo::reg_bundle_nodbg_end () inline static
Definition at line 321 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_bundles().
reg_bundles()
iterator_range< reg_bundle_iterator > llvm::MachineRegisterInfo::reg_bundles (unsigned Reg) const inline
Definition at line 269 of file MachineRegisterInfo.h.
References reg_bundle_begin(), and reg_bundle_end().
reg_empty()
bool llvm::MachineRegisterInfo::reg_empty (unsigned RegNo) const inline
reg_empty - Return true if there are no instructions using or defining the specified register (it may be live-in).
Definition at line 276 of file MachineRegisterInfo.h.
References reg_begin(), and reg_end().
reg_end()
reg_iterator llvm::MachineRegisterInfo::reg_end () inline static
Definition at line 235 of file MachineRegisterInfo.h.
Referenced by llvm::ConnectedVNInfoEqClasses::Distribute(), reg_empty(), reg_operands(), and replaceRegWith().
reg_instr_begin()
reg_instr_iterator llvm::MachineRegisterInfo::reg_instr_begin (unsigned RegNo) const inline
Definition at line 245 of file MachineRegisterInfo.h.
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), reg_instructions(), and usesTheStack().
reg_instr_end()
reg_instr_iterator llvm::MachineRegisterInfo::reg_instr_end () inline static
Definition at line 248 of file MachineRegisterInfo.h.
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), reg_instructions(), and usesTheStack().
reg_instr_nodbg_begin()
reg_instr_nodbg_iterator llvm::MachineRegisterInfo::reg_instr_nodbg_begin (unsigned RegNo) const inline
Definition at line 300 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_instructions().
reg_instr_nodbg_end()
reg_instr_nodbg_iterator llvm::MachineRegisterInfo::reg_instr_nodbg_end () inline static
Definition at line 303 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_instructions().
reg_instructions()
iterator_range< reg_instr_iterator > llvm::MachineRegisterInfo::reg_instructions (unsigned Reg) const inline
Definition at line 253 of file MachineRegisterInfo.h.
References reg_instr_begin(), and reg_instr_end().
Referenced by llvm::findPHICopyInsertPoint().
reg_nodbg_begin()
reg_nodbg_iterator llvm::MachineRegisterInfo::reg_nodbg_begin (unsigned RegNo) const inline
Definition at line 282 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_empty(), and reg_nodbg_operands().
reg_nodbg_bundles()
iterator_range< reg_bundle_nodbg_iterator > llvm::MachineRegisterInfo::reg_nodbg_bundles (unsigned Reg) const inline
Definition at line 326 of file MachineRegisterInfo.h.
References reg_bundle_nodbg_begin(), and reg_bundle_nodbg_end().
reg_nodbg_empty()
bool llvm::MachineRegisterInfo::reg_nodbg_empty (unsigned RegNo) const inline
reg_nodbg_empty - Return true if the only instructions using or defining Reg are Debug instructions.
Definition at line 333 of file MachineRegisterInfo.h.
References reg_nodbg_begin(), and reg_nodbg_end().
Referenced by llvm::calculateSpillWeightsAndHints().
reg_nodbg_end()
reg_nodbg_iterator llvm::MachineRegisterInfo::reg_nodbg_end () inline static
Definition at line 285 of file MachineRegisterInfo.h.
Referenced by reg_nodbg_empty(), and reg_nodbg_operands().
reg_nodbg_instructions()
iterator_range< reg_instr_nodbg_iterator > llvm::MachineRegisterInfo::reg_nodbg_instructions (unsigned Reg) const inline
Definition at line 308 of file MachineRegisterInfo.h.
References reg_instr_nodbg_begin(), and reg_instr_nodbg_end().
reg_nodbg_operands()
iterator_range< reg_nodbg_iterator > llvm::MachineRegisterInfo::reg_nodbg_operands (unsigned Reg) const inline
Definition at line 290 of file MachineRegisterInfo.h.
References reg_nodbg_begin(), and reg_nodbg_end().
Referenced by recomputeRegClass().
reg_operands()
iterator_range< reg_iterator > llvm::MachineRegisterInfo::reg_operands (unsigned Reg) const inline
Definition at line 237 of file MachineRegisterInfo.h.
References reg_begin(), and reg_end().
Referenced by verifyUseList().
removeRegOperandFromUseList()
void MachineRegisterInfo::removeRegOperandFromUseList (MachineOperand * MO)
Remove MO from its use-def list.
Definition at line 208 of file MachineRegisterInfo.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::Next, llvm::MachineOperand::Prev, llvm::MachineOperand::Reg, and llvm::Registry< T, U >::Head.
Referenced by llvm::MachineOperand::ChangeToRegister(), llvm::MachineInstr::RemoveOperand(), llvm::MachineOperand::setIsDef(), and llvm::MachineOperand::setReg().
replaceRegWith()
void MachineRegisterInfo::replaceRegWith (unsigned FromReg, unsigned ToReg)
replaceRegWith - Replace all instances of FromReg with ToReg in the machine function. This is like llvm-level X->replaceAllUsesWith(Y), except that it also changes any definitions of the register as well.
Note that it is usually necessary to first constrain ToReg's register class to match the FromReg constraints using:
constrainRegClass(ToReg, getRegClass(FromReg))
That function will return NULL if the virtual registers have incompatible constraints.
Note that if ToReg is a physical register the function will replace and apply sub registers to ToReg in order to obtain a final/proper physical register.
replaceRegWith - Replace all instances of FromReg with ToReg in the machine function. This is like llvm-level X->replaceAllUsesWith(Y), except that it also changes any definitions of the register as well. If ToReg is a physical register we apply the sub register to obtain the final/proper physical register.
Definition at line 284 of file MachineRegisterInfo.cpp.
References getTargetRegisterInfo(), I, llvm::TargetRegisterInfo::isPhysicalRegister(), reg_begin(), reg_end(), llvm::MachineOperand::setReg(), and llvm::MachineOperand::substPhysReg().
Referenced by llvm::SIInstrInfo::moveSMRDToVALU(), llvm::SIInstrInfo::moveToVALU(), and llvm::SelectionDAGISel::runOnMachineFunction().
reservedRegsFrozen()
bool llvm::MachineRegisterInfo::reservedRegsFrozen () const inline
reservedRegsFrozen - Returns true after freezeReservedRegs() was called to ensure the set of reserved registers stays constant.
Definition at line 705 of file MachineRegisterInfo.h.
Referenced by canReserveReg(), and getReservedRegs().
resetDelegate()
void llvm::MachineRegisterInfo::resetDelegate (Delegate * delegate) inline
Definition at line 135 of file MachineRegisterInfo.h.
setDelegate()
void llvm::MachineRegisterInfo::setDelegate (Delegate * delegate) inline
Definition at line 144 of file MachineRegisterInfo.h.
setPhysRegUnused()
void llvm::MachineRegisterInfo::setPhysRegUnused (unsigned Reg) inline
setPhysRegUnused - Mark the specified register unused in this function. This should only be called during and after register allocation.
Definition at line 679 of file MachineRegisterInfo.h.
References getTargetRegisterInfo(), and llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan().
setPhysRegUsed()
void llvm::MachineRegisterInfo::setPhysRegUsed (unsigned Reg) inline
setPhysRegUsed - Mark the specified register used in this function. This should only be called during and after register allocation.
Definition at line 665 of file MachineRegisterInfo.h.
References getTargetRegisterInfo(), and llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), checkNumAlignedDPRCS2Regs(), llvm::SIMachineFunctionInfo::getSpilledReg(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::Mips16FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan().
setRegAllocationHint()
void llvm::MachineRegisterInfo::setRegAllocationHint (unsigned Reg, unsigned Type, unsigned PrefReg) inline
setRegAllocationHint - Specify a register allocation hint for the specified virtual register.
Definition at line 612 of file MachineRegisterInfo.h.
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), and llvm::ARMBaseRegisterInfo::UpdateRegAllocHint().
setRegClass()
void MachineRegisterInfo::setRegClass (unsigned Reg, const TargetRegisterClass * RC)
setRegClass - Set the register class of the specified virtual register.
Definition at line 41 of file MachineRegisterInfo.cpp.
References llvm::TargetRegisterClass::isAllocatable().
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), constrainRegClass(), and recomputeRegClass().
setRegUnitUsed()
void llvm::MachineRegisterInfo::setRegUnitUsed (unsigned RegUnit) inline
Mark the specified register unit as used in this function. This should only be called during and after register allocation.
Definition at line 659 of file MachineRegisterInfo.h.
tracksLiveness()
bool llvm::MachineRegisterInfo::tracksLiveness () const inline
tracksLiveness - Returns true when tracking register liveness accurately.
While this flag is true, register liveness information in basic block live-in lists and machine instruction operands is accurate. This means it can be used to change the code in ways that affect the values in registers, for example by the register scavenger.
When this flag is false, liveness is no longer reliable.
Definition at line 176 of file MachineRegisterInfo.h.
Referenced by llvm::BranchFolder::OptimizeFunction().
tracksSubRegLiveness()
bool llvm::MachineRegisterInfo::tracksSubRegLiveness () const inline
Definition at line 185 of file MachineRegisterInfo.h.
use_begin()
use_iterator llvm::MachineRegisterInfo::use_begin (unsigned RegNo) const inline
Definition at line 398 of file MachineRegisterInfo.h.
Referenced by hasOneUse(), llvm::SIInstrInfo::moveToVALU(), use_empty(), and use_operands().
use_bundle_begin()
use_bundle_iterator llvm::MachineRegisterInfo::use_bundle_begin (unsigned RegNo) const inline
Definition at line 428 of file MachineRegisterInfo.h.
Referenced by use_bundles().
use_bundle_end()
use_bundle_iterator llvm::MachineRegisterInfo::use_bundle_end () inline static
Definition at line 431 of file MachineRegisterInfo.h.
Referenced by use_bundles().
use_bundle_nodbg_begin()
use_bundle_nodbg_iterator llvm::MachineRegisterInfo::use_bundle_nodbg_begin (unsigned RegNo) const inline
Definition at line 493 of file MachineRegisterInfo.h.
Referenced by use_nodbg_bundles().
use_bundle_nodbg_end()
use_bundle_nodbg_iterator llvm::MachineRegisterInfo::use_bundle_nodbg_end () inline static
Definition at line 496 of file MachineRegisterInfo.h.
Referenced by use_nodbg_bundles().
use_bundles()
iterator_range< use_bundle_iterator > llvm::MachineRegisterInfo::use_bundles (unsigned Reg) const inline
Definition at line 435 of file MachineRegisterInfo.h.
References use_bundle_begin(), and use_bundle_end().
use_empty()
bool llvm::MachineRegisterInfo::use_empty (unsigned RegNo) const inline
use_empty - Return true if there are no instructions using the specified register.
Definition at line 442 of file MachineRegisterInfo.h.
References use_begin(), and use_end().
Referenced by llvm::R600TargetLowering::EmitInstrWithCustomInserter(), EmitLiveInCopies(), foldImmediates(), and llvm::MachineInstr::print().
use_end()
use_iterator llvm::MachineRegisterInfo::use_end () inline static
Definition at line 401 of file MachineRegisterInfo.h.
Referenced by hasOneUse(), llvm::SIInstrInfo::moveToVALU(), use_empty(), and use_operands().
use_instr_begin()
use_instr_iterator llvm::MachineRegisterInfo::use_instr_begin (unsigned RegNo) const inline
Definition at line 411 of file MachineRegisterInfo.h.
Referenced by markUsesInDebugValueAsUndef(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), and use_instructions().
use_instr_end()
use_instr_iterator llvm::MachineRegisterInfo::use_instr_end () inline static
Definition at line 414 of file MachineRegisterInfo.h.
Referenced by markUsesInDebugValueAsUndef(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), and use_instructions().
use_instr_nodbg_begin()
use_instr_nodbg_iterator llvm::MachineRegisterInfo::use_instr_nodbg_begin (unsigned RegNo) const inline
Definition at line 475 of file MachineRegisterInfo.h.
Referenced by findOnlyInterestingUse(), findUseBetween(), and use_nodbg_instructions().
use_instr_nodbg_end()
use_instr_nodbg_iterator llvm::MachineRegisterInfo::use_instr_nodbg_end () inline static
Definition at line 478 of file MachineRegisterInfo.h.
Referenced by findUseBetween(), and use_nodbg_instructions().
use_instructions()
iterator_range< use_instr_iterator > llvm::MachineRegisterInfo::use_instructions (unsigned Reg) const inline
Definition at line 419 of file MachineRegisterInfo.h.
References use_instr_begin(), and use_instr_end().
Referenced by dumpUses(), and isDefLiveOut().
use_nodbg_begin()
use_nodbg_iterator llvm::MachineRegisterInfo::use_nodbg_begin (unsigned RegNo) const inline
Definition at line 457 of file MachineRegisterInfo.h.
Referenced by hasOneNonDBGUse(), use_nodbg_empty(), and use_nodbg_operands().
use_nodbg_bundles()
iterator_range< use_bundle_nodbg_iterator > llvm::MachineRegisterInfo::use_nodbg_bundles (unsigned Reg) const inline
Definition at line 501 of file MachineRegisterInfo.h.
References use_bundle_nodbg_begin(), and use_bundle_nodbg_end().
use_nodbg_empty()
bool llvm::MachineRegisterInfo::use_nodbg_empty (unsigned RegNo) const inline
use_nodbg_empty - Return true if there are no non-Debug instructions using the specified register.
Definition at line 508 of file MachineRegisterInfo.h.
References use_nodbg_begin(), and use_nodbg_end().
Referenced by eraseIfDead(), llvm::AArch64InstrInfo::optimizeCompareInstr(), and llvm::X86InstrInfo::optimizeCompareInstr().
use_nodbg_end()
use_nodbg_iterator llvm::MachineRegisterInfo::use_nodbg_end () inline static
Definition at line 460 of file MachineRegisterInfo.h.
Referenced by hasOneNonDBGUse(), use_nodbg_empty(), and use_nodbg_operands().
use_nodbg_instructions()
iterator_range< use_instr_nodbg_iterator > llvm::MachineRegisterInfo::use_nodbg_instructions (unsigned Reg) const inline
Definition at line 483 of file MachineRegisterInfo.h.
References use_instr_nodbg_begin(), and use_instr_nodbg_end().
use_nodbg_operands()
iterator_range< use_nodbg_iterator > llvm::MachineRegisterInfo::use_nodbg_operands (unsigned Reg) const inline
Definition at line 465 of file MachineRegisterInfo.h.
References use_nodbg_begin(), and use_nodbg_end().
use_operands()
iterator_range< use_iterator > llvm::MachineRegisterInfo::use_operands (unsigned Reg) const inline
Definition at line 403 of file MachineRegisterInfo.h.
References use_begin(), and use_end().
Referenced by clearKillFlags().
verifyUseList()
void MachineRegisterInfo::verifyUseList (unsigned Reg) const
Verify the sanity of the use list for Reg.
Definition at line 121 of file MachineRegisterInfo.cpp.
References llvm::errs(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), getTargetRegisterInfo(), llvm::MachineOperand::isReg(), and reg_operands().
Referenced by clearVirtRegs(), and verifyUseLists().
verifyUseLists()
void MachineRegisterInfo::verifyUseLists () const
Verify the use list of all registers.
Definition at line 159 of file MachineRegisterInfo.cpp.
References getNumVirtRegs(), getTargetRegisterInfo(), llvm::TargetRegisterInfo::index2VirtReg(), and verifyUseList().
Friends And Related Symbol Documentation
defusechain_instr_iterator
template<bool, bool, bool, bool, bool, bool> friend class defusechain_instr_iterator friend
Definition at line 224 of file MachineRegisterInfo.h.
defusechain_iterator
template<bool, bool, bool, bool, bool, bool> friend class defusechain_iterator friend
Definition at line 222 of file MachineRegisterInfo.h.
The documentation for this class was generated from the following files:
MachineRegisterInfo.h
MachineRegisterInfo.cpp