LLVM: llvm::AssertingVH< ValueTy > Class Template Reference
LLVM API Documentation
llvm::AssertingVH< ValueTy > Class Template Reference
Value handle that asserts if the Value is deleted.
#include <ValueHandle.h>
Public Member Functions
AssertingVH ()
AssertingVH (ValueTy *P)
AssertingVH (const AssertingVH &RHS)
operator ValueTy * () const
ValueTy * operator= (ValueTy *RHS)
ValueTy * operator= (const AssertingVH< ValueTy > &RHS)
ValueTy * operator-> () const
ValueTy & operator* () const
Public Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (HandleBaseKind Kind)
ValueHandleBase (HandleBaseKind Kind, Value *V)
ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase &RHS)
~ValueHandleBase ()
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
Value * operator-> () const
Value & operator* () const
Friends
struct DenseMapInfo< AssertingVH< ValueTy > >
Additional Inherited Members
Static Public Member Functions inherited from llvm::ValueHandleBase
static void ValueIsDeleted (Value *V)
static void ValueIsRAUWd (Value *Old, Value *New)
Protected Types inherited from llvm::ValueHandleBase
enum HandleBaseKind { Assert , Callback , Tracking , Weak }
This indicates what sub class the handle actually is.
Protected Member Functions inherited from llvm::ValueHandleBase
Value * getValPtr () const
Static Protected Member Functions inherited from llvm::ValueHandleBase
static bool isValid (Value *V)
Detailed Description
template<typename ValueTy>
class llvm::AssertingVH< ValueTy >
Value handle that asserts if the Value is deleted.
This is a Value Handle that points to a value and asserts out if the value is destroyed while the handle is still live. This is very useful for catching dangling pointer bugs and other things which can be non-obvious. One particularly useful place to use this is as the Key of a map. Dangling pointer bugs often lead to really subtle bugs that only occur if another object happens to get allocated to the same address as the old one. Using an AssertingVH ensures that an assert is triggered as soon as the bad delete occurs.
Note that an AssertingVH handle does not follow values across RAUW operations. This means that RAUW's need to explicitly update the AssertingVH's as it moves. This is required because in non-assert mode this class turns into a trivial wrapper around a pointer.
Definition at line 185 of file ValueHandle.h.
Constructor & Destructor Documentation
AssertingVH() [1/3]
template<typename ValueTy> llvm::AssertingVH< ValueTy >::AssertingVH () inline
Definition at line 209 of file ValueHandle.h.
References llvm::ValueHandleBase::Assert.
Referenced by AssertingVH(), and operator=().
AssertingVH() [2/3]
template<typename ValueTy> llvm::AssertingVH< ValueTy >::AssertingVH (ValueTy * P) inline
Definition at line 210 of file ValueHandle.h.
References llvm::ValueHandleBase::Assert, and P.
AssertingVH() [3/3]
template<typename ValueTy> llvm::AssertingVH< ValueTy >::AssertingVH (const AssertingVH< ValueTy > & RHS) inline
Definition at line 211 of file ValueHandle.h.
References llvm::ValueHandleBase::Assert, and AssertingVH().
Member Function Documentation
operator ValueTy *()
template<typename ValueTy> llvm::AssertingVH< ValueTy >::operator ValueTy * () const inline
Definition at line 217 of file ValueHandle.h.
operator*()
template<typename ValueTy> ValueTy & llvm::AssertingVH< ValueTy >::operator* () const inline
Definition at line 231 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr().
operator->()
template<typename ValueTy> ValueTy * llvm::AssertingVH< ValueTy >::operator-> () const inline
Definition at line 230 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr().
operator=() [1/2]
template<typename ValueTy> ValueTy * llvm::AssertingVH< ValueTy >::operator= (const AssertingVH< ValueTy > & RHS) inline
Definition at line 225 of file ValueHandle.h.
References AssertingVH(), and llvm::ValueHandleBase::getValPtr().
operator=() [2/2]
template<typename ValueTy> ValueTy * llvm::AssertingVH< ValueTy >::operator= (ValueTy * RHS) inline
Definition at line 221 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr().
Friends And Related Symbol Documentation
DenseMapInfo< AssertingVH< ValueTy > >
template<typename ValueTy> friend struct DenseMapInfo< AssertingVH< ValueTy > > friend
Definition at line 164 of file ValueHandle.h.
The documentation for this class was generated from the following file:
ValueHandle.h