LLVM: llvm::LLVMDisasmContext Class Reference
LLVM API Documentation
llvm::LLVMDisasmContext Class Reference
#include <Disassembler.h>
Public Member Functions
LLVMDisasmContext (std::string tripleName, void *disInfo, int tagType, LLVMOpInfoCallback getOpInfo, LLVMSymbolLookupCallback symbolLookUp, const Target *theTarget, const MCAsmInfo *mAI, const MCRegisterInfo *mRI, const MCSubtargetInfo *mSI, const MCInstrInfo *mII, llvm::MCContext *ctx, const MCDisassembler *disAsm, MCInstPrinter *iP)
const std::string & getTripleName () const
void * getDisInfo () const
int getTagType () const
LLVMOpInfoCallback getGetOpInfo () const
LLVMSymbolLookupCallback getSymbolLookupCallback () const
const Target * getTarget () const
const MCDisassembler * getDisAsm () const
const MCAsmInfo * getAsmInfo () const
const MCInstrInfo * getInstrInfo () const
const MCRegisterInfo * getRegisterInfo () const
const MCSubtargetInfo * getSubtargetInfo () const
MCInstPrinter * getIP ()
void setIP (MCInstPrinter *NewIP)
uint64_t getOptions () const
void addOptions (uint64_t Options)
StringRef getCPU () const
void setCPU (const char *CPU)
Public Attributes
SmallString< 128 > CommentsToEmit
raw_svector_ostream CommentStream
Detailed Description
Definition at line 38 of file lib/MC/MCDisassembler/Disassembler.h.
Constructor & Destructor Documentation
LLVMDisasmContext()
llvm::LLVMDisasmContext::LLVMDisasmContext (std::string tripleName, void * disInfo, int tagType, LLVMOpInfoCallback getOpInfo, LLVMSymbolLookupCallback symbolLookUp, const Target * theTarget, const MCAsmInfo * mAI, const MCRegisterInfo * mRI, const MCSubtargetInfo * mSI, const MCInstrInfo * mII, llvm::MCContext * ctx, const MCDisassembler * disAsm, MCInstPrinter * iP) inline
Definition at line 85 of file lib/MC/MCDisassembler/Disassembler.h.
References CommentsToEmit, and CommentStream.
Member Function Documentation
addOptions()
void llvm::LLVMDisasmContext::addOptions (uint64_t Options) inline
Definition at line 122 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by LLVMSetDisasmOptions().
getAsmInfo()
const MCAsmInfo * llvm::LLVMDisasmContext::getAsmInfo () const inline
Definition at line 115 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by emitComments(), and LLVMSetDisasmOptions().
getCPU()
StringRef llvm::LLVMDisasmContext::getCPU () const inline
Definition at line 123 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by getItineraryLatency().
getDisAsm()
const MCDisassembler * llvm::LLVMDisasmContext::getDisAsm () const inline
Definition at line 114 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by LLVMDisasmInstruction().
getDisInfo()
void * llvm::LLVMDisasmContext::getDisInfo () const inline
Definition at line 107 of file lib/MC/MCDisassembler/Disassembler.h.
getGetOpInfo()
LLVMOpInfoCallback llvm::LLVMDisasmContext::getGetOpInfo () const inline
Definition at line 109 of file lib/MC/MCDisassembler/Disassembler.h.
getInstrInfo()
const MCInstrInfo * llvm::LLVMDisasmContext::getInstrInfo () const inline
Definition at line 116 of file lib/MC/MCDisassembler/Disassembler.h.
References llvm::MCInstrInfo::get().
Referenced by getItineraryLatency(), getLatency(), and LLVMSetDisasmOptions().
getIP()
MCInstPrinter * llvm::LLVMDisasmContext::getIP () inline
Definition at line 119 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by LLVMDisasmInstruction(), and LLVMSetDisasmOptions().
getOptions()
uint64_t llvm::LLVMDisasmContext::getOptions () const inline
Definition at line 121 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by LLVMDisasmInstruction().
getRegisterInfo()
const MCRegisterInfo * llvm::LLVMDisasmContext::getRegisterInfo () const inline
Definition at line 117 of file lib/MC/MCDisassembler/Disassembler.h.
References llvm::MCRegisterInfo::get().
Referenced by LLVMSetDisasmOptions().
getSubtargetInfo()
const MCSubtargetInfo * llvm::LLVMDisasmContext::getSubtargetInfo () const inline
Definition at line 118 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by getItineraryLatency(), getLatency(), and LLVMSetDisasmOptions().
getSymbolLookupCallback()
LLVMSymbolLookupCallback llvm::LLVMDisasmContext::getSymbolLookupCallback () const inline
Definition at line 110 of file lib/MC/MCDisassembler/Disassembler.h.
getTagType()
int llvm::LLVMDisasmContext::getTagType () const inline
Definition at line 108 of file lib/MC/MCDisassembler/Disassembler.h.
getTarget()
const Target * llvm::LLVMDisasmContext::getTarget () const inline
Definition at line 113 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by LLVMSetDisasmOptions().
getTripleName()
const std::string & llvm::LLVMDisasmContext::getTripleName () const inline
Definition at line 106 of file lib/MC/MCDisassembler/Disassembler.h.
setCPU()
void llvm::LLVMDisasmContext::setCPU (const char * CPU) inline
Definition at line 124 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by LLVMCreateDisasmCPUFeatures().
setIP()
void llvm::LLVMDisasmContext::setIP (MCInstPrinter * NewIP) inline
Definition at line 120 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by LLVMSetDisasmOptions().
Member Data Documentation
CommentsToEmit
SmallString<128> llvm::LLVMDisasmContext::CommentsToEmit
Definition at line 82 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by emitComments(), and LLVMDisasmContext().
CommentStream
raw_svector_ostream llvm::LLVMDisasmContext::CommentStream
Definition at line 83 of file lib/MC/MCDisassembler/Disassembler.h.
Referenced by emitComments(), emitLatency(), LLVMDisasmContext(), and LLVMSetDisasmOptions().
The documentation for this class was generated from the following file:
lib/MC/MCDisassembler/Disassembler.h