LLVM: llvm::ArrayRef< T > Class Template Reference
LLVM API Documentation
llvm::ArrayRef< T > Class Template Reference
#include <ArrayRef.h>
Public Types
typedef const T * iterator
typedef const T * const_iterator
typedef size_t size_type
typedef std::reverse_iterator< iterator > reverse_iterator
Public Member Functions
Constructors
ArrayRef ()
Construct an empty ArrayRef.
ArrayRef (NoneType)
Construct an empty ArrayRef from None.
ArrayRef (const T &OneElt)
Construct an ArrayRef from a single element.
ArrayRef (const T *data, size_t length)
Construct an ArrayRef from a pointer and length.
ArrayRef (const T *begin, const T *end)
Construct an ArrayRef from a range.
template<typename U>
ArrayRef (const SmallVectorTemplateCommon< T, U > &Vec)
template<typename A>
ArrayRef (const std::vector< T, A > &Vec)
Construct an ArrayRef from a std::vector.
template<size_t N>
LLVM_CONSTEXPR ArrayRef (const T(&Arr)[N])
Construct an ArrayRef from a C array.
template<typename U>
ArrayRef (const ArrayRef< U * > &A, typename std::enable_if< std::is_convertible< U *const *, T const * >::value >::type *=0)
Simple Operations
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
empty - Check if the array is empty.
const T * data () const
size_t size () const
size - Get the array size.
const T & front () const
front - Get the first element.
const T & back () const
back - Get the last element.
template<typename Allocator>
ArrayRef< T > copy (Allocator &A)
bool equals (ArrayRef RHS) const
equals - Check for element-wise equality.
ArrayRef< T > slice (unsigned N) const
slice(n) - Chop off the first N elements of the array.
ArrayRef< T > slice (unsigned N, unsigned M) const
ArrayRef< T > drop_back (unsigned N=1) const
Operator Overloads
const T & operator[] (size_t Index) const
Expensive Operations
std::vector< T > vec () const
Conversion operators
operator std::vector< T > () const
Convenience methods
bool equals (TRefOrNothing Arg0=TRefOrNothing(), TRefOrNothing Arg1=TRefOrNothing(), TRefOrNothing Arg2=TRefOrNothing(), TRefOrNothing Arg3=TRefOrNothing(), TRefOrNothing Arg4=TRefOrNothing(), TRefOrNothing Arg5=TRefOrNothing(), TRefOrNothing Arg6=TRefOrNothing(), TRefOrNothing Arg7=TRefOrNothing(), TRefOrNothing Arg8=TRefOrNothing(), TRefOrNothing Arg9=TRefOrNothing(), TRefOrNothing Arg10=TRefOrNothing(), TRefOrNothing Arg11=TRefOrNothing(), TRefOrNothing Arg12=TRefOrNothing(), TRefOrNothing Arg13=TRefOrNothing(), TRefOrNothing Arg14=TRefOrNothing(), TRefOrNothing Arg15=TRefOrNothing())
Predicate for testing that the array equals the exact sequence of arguments.
Detailed Description
template<typename T>
class llvm::ArrayRef< T >
ArrayRef - Represent a constant reference to an array (0 or more elements consecutively in memory), i.e. a start pointer and a length. It allows various APIs to take consecutive elements easily and conveniently.
This class does not own the underlying data, it is expected to be used in situations where the data resides in some other buffer, whose lifetime extends past that of the ArrayRef. For this reason, it is not in general safe to store an ArrayRef.
This is intended to be trivially copyable, so it should be passed by value.
Definition at line 32 of file ArrayRef.h.
Member Typedef Documentation
const_iterator
template<typename T> typedef const T* llvm::ArrayRef< T >::const_iterator
Definition at line 35 of file ArrayRef.h.
iterator
template<typename T> typedef const T* llvm::ArrayRef< T >::iterator
Definition at line 34 of file ArrayRef.h.
reverse_iterator
template<typename T> typedef std::reverse_iterator<iterator> llvm::ArrayRef< T >::reverse_iterator
Definition at line 38 of file ArrayRef.h.
size_type
template<typename T> typedef size_t llvm::ArrayRef< T >::size_type
Definition at line 36 of file ArrayRef.h.
Constructor & Destructor Documentation
ArrayRef() [1/9]
template<typename T> llvm::ArrayRef< T >::ArrayRef () inline
Construct an empty ArrayRef.
Definition at line 65 of file ArrayRef.h.
Referenced by llvm::iterator< Attribute >::copy(), llvm::MutableArrayRef< T >::MutableArrayRef(), llvm::MutableArrayRef< T >::MutableArrayRef(), llvm::MutableArrayRef< T >::MutableArrayRef(), llvm::MutableArrayRef< T >::MutableArrayRef(), llvm::MutableArrayRef< T >::MutableArrayRef(), llvm::MutableArrayRef< T >::MutableArrayRef(), llvm::MutableArrayRef< T >::MutableArrayRef(), llvm::MutableArrayRef< T >::MutableArrayRef(), llvm::iterator< Attribute >::slice(), and llvm::iterator< Attribute >::slice().
ArrayRef() [2/9]
template<typename T> llvm::ArrayRef< T >::ArrayRef (NoneType) inline
Construct an empty ArrayRef from None.
Definition at line 68 of file ArrayRef.h.
ArrayRef() [3/9]
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T & OneElt) inline
Construct an ArrayRef from a single element.
Definition at line 71 of file ArrayRef.h.
ArrayRef() [4/9]
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T * data, size_t length) inline
Construct an ArrayRef from a pointer and length.
Definition at line 75 of file ArrayRef.h.
ArrayRef() [5/9]
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T * begin, const T * end) inline
Construct an ArrayRef from a range.
Definition at line 79 of file ArrayRef.h.
ArrayRef() [6/9]
template<typename T> template<typename U> llvm::ArrayRef< T >::ArrayRef (const SmallVectorTemplateCommon< T, U > & Vec) inline
Construct an ArrayRef from a SmallVector. This is templated in order to avoid instantiating SmallVectorTemplateCommon<T> whenever we copy-construct an ArrayRef.
Definition at line 86 of file ArrayRef.h.
ArrayRef() [7/9]
template<typename T> template<typename A> llvm::ArrayRef< T >::ArrayRef (const std::vector< T, A > & Vec) inline
Construct an ArrayRef from a std::vector.
Definition at line 92 of file ArrayRef.h.
ArrayRef() [8/9]
template<typename T> template<size_t N> LLVM_CONSTEXPR llvm::ArrayRef< T >::ArrayRef (const T(&) Arr[N]) inline
Construct an ArrayRef from a C array.
Definition at line 97 of file ArrayRef.h.
ArrayRef() [9/9]
template<typename T> template<typename U> llvm::ArrayRef< T >::ArrayRef (const ArrayRef< U * > & A, typename std::enable_if< std::is_convertible< U *const *, T const * >::value >::type * = 0) inline
Construct an ArrayRef<const T*> from ArrayRef<T*>. This uses SFINAE to ensure that only ArrayRefs of pointers can be converted.
Definition at line 110 of file ArrayRef.h.
Member Function Documentation
back()
template<typename T> const T & llvm::ArrayRef< T >::back () const inline
back - Get the last element.
Definition at line 140 of file ArrayRef.h.
Referenced by llvm::ConstantFoldInstOperands().
begin()
template<typename T> iterator llvm::ArrayRef< T >::begin () const inline
Definition at line 119 of file ArrayRef.h.
Referenced by llvm::SpillPlacement::addConstraints(), llvm::SpillPlacement::addLinks(), llvm::SpillPlacement::addPrefSpill(), llvm::DebugLocEntry::addValues(), llvm::AttributeSet::begin(), buildExtractionBlockSet(), buildFixItLine(), BuildSubAggregate(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::SchedDFSResult::compute(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::ComputeLinearIndex(), ConstantFoldGetElementPtrImpl(), containsReg(), llvm::convertUTF16ToUTF8String(), llvm::iterator< Attribute >::copy(), llvm::IRBuilderBase::CreateGCStatepoint(), llvm::discoverAndMapSubloop(), llvm::Instruction::dropUnknownMetadata(), llvm::DwarfDebug::emitLocPieces(), llvm::TargetLoweringObjectFileCOFF::emitModuleFlags(), llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::iterator< Attribute >::equals(), llvm::FindInsertedValue(), llvm::SchedBoundary::findMaxLatency(), llvm::AttributeSetNode::get(), getINSERTPS(), llvm::SelectionDAG::getNode(), getNoopInput(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::SelectionDAG::getVTList(), llvm::RegPressureTracker::initLiveThru(), llvm::ScheduleDAGMI::initQueues(), isEXTMask(), isHorizontalBinOp(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV8I16SingleInputVectorShuffle(), LowerVECTOR_SHUFFLEv8i8(), lowerVectorShuffle(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleWithSHUFPS(), ProfileBitsInit(), ProfileDagInit(), ProfileListInit(), ReadWideAPInt(), llvm::iterator< Attribute >::rend(), llvm::MachineModuleInfo::setCallSiteLandingPad(), llvm::PMTopLevelManager::setLastUser(), llvm::MachineInstr::setPhysRegsDeadExcept(), llvm::SimplifyCall(), llvm::SelectionDAG::TransferDbgValues(), UpdateAnalysisInformation(), and UpdatePHINodes().
copy()
template<typename T> template<typename Allocator> ArrayRef< T > llvm::ArrayRef< T >::copy (Allocator & A) inline
Definition at line 146 of file ArrayRef.h.
data()
template<typename T> const T * llvm::ArrayRef< T >::data () const inline
Definition at line 128 of file ArrayRef.h.
Referenced by llvm::MutableArrayRef< T >::data(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::SelectionDAG::getAtomic(), llvm::ConstantExpr::getGetElementPtr(), llvm::SelectionDAG::getMachineNode(), llvm::object::COFFObjectFile::getSectionContents(), llvm::object::MachOObjectFile::getSectionFinalSegmentName(), llvm::object::MachOObjectFile::getSectionName(), llvm::SelectionDAG::getVectorShuffle(), llvm::MipsTargetLowering::HandleByVal(), llvm::SelectionDAG::MorphNodeTo(), llvm::StructType::setBody(), llvm::iterator< Attribute >::slice(), llvm::iterator< Attribute >::slice(), SymbolicallyEvaluateGEP(), and llvm::MD5::update().
drop_back()
template<typename T> ArrayRef< T > llvm::ArrayRef< T >::drop_back (unsigned N = 1) const inline
Definition at line 179 of file ArrayRef.h.
empty()
template<typename T> bool llvm::ArrayRef< T >::empty () const inline
empty - Check if the array is empty.
Definition at line 126 of file ArrayRef.h.
Referenced by llvm::SpillPlacement::addLinks(), llvm::iterator< Attribute >::back(), llvm::MutableArrayRef< T >::back(), buildFixItLine(), combineX86ShuffleChain(), computeExcessPressureDelta(), llvm::ConstantFoldExtractValueInstruction(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInsertValueInstruction(), llvm::convertUTF16ToUTF8String(), llvm::StructType::create(), llvm::StructType::create(), llvm::FindInsertedValue(), llvm::iterator< Attribute >::front(), llvm::MutableArrayRef< T >::front(), llvm::AttributeSet::get(), llvm::AttributeSetNode::get(), llvm::SubtargetFeatures::getFeatureBits(), getIndexedTypeInternal(), llvm::Intrinsic::getName(), getOrSelfReference(), llvm::Intrinsic::getType(), isInBoundsIndices(), lowerV8I16BasicBlendVectorShuffle(), lowerV8I16SingleInputVectorShuffle(), llvm::yaml::BinaryRef::operator==, llvm::PrintMessage(), and llvm::PromoteMemToReg().
end()
template<typename T> iterator llvm::ArrayRef< T >::end () const inline
Definition at line 120 of file ArrayRef.h.
Referenced by llvm::SpillPlacement::addConstraints(), llvm::SpillPlacement::addLinks(), llvm::SpillPlacement::addPrefSpill(), llvm::DebugLocEntry::addValues(), buildExtractionBlockSet(), buildFixItLine(), BuildSubAggregate(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::SchedDFSResult::compute(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::ComputeLinearIndex(), ConstantFoldGetElementPtrImpl(), containsReg(), llvm::convertUTF16ToUTF8String(), llvm::iterator< Attribute >::copy(), llvm::IRBuilderBase::CreateGCStatepoint(), llvm::discoverAndMapSubloop(), llvm::Instruction::dropUnknownMetadata(), llvm::DwarfDebug::emitLocPieces(), llvm::TargetLoweringObjectFileCOFF::emitModuleFlags(), llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::AttributeSet::end(), llvm::iterator< Attribute >::equals(), llvm::FindInsertedValue(), llvm::SchedBoundary::findMaxLatency(), llvm::AttributeSetNode::get(), getINSERTPS(), llvm::SelectionDAG::getNode(), getNoopInput(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::SelectionDAG::getVTList(), llvm::RegPressureTracker::initLiveThru(), llvm::ScheduleDAGMI::initQueues(), isEXTMask(), isHorizontalBinOp(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV8I16SingleInputVectorShuffle(), LowerVECTOR_SHUFFLEv8i8(), lowerVectorShuffle(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleWithSHUFPS(), ProfileBitsInit(), ProfileDagInit(), ProfileListInit(), llvm::iterator< Attribute >::rbegin(), ReadWideAPInt(), llvm::MachineModuleInfo::setCallSiteLandingPad(), llvm::PMTopLevelManager::setLastUser(), llvm::MachineInstr::setPhysRegsDeadExcept(), llvm::SimplifyCall(), llvm::SelectionDAG::TransferDbgValues(), UpdateAnalysisInformation(), and UpdatePHINodes().
equals() [1/2]
template<typename T> bool llvm::ArrayRef< T >::equals (ArrayRef< T > RHS) const inline
equals - Check for element-wise equality.
Definition at line 153 of file ArrayRef.h.
Referenced by combineX86ShuffleChain(), and llvm::operator==().
equals() [2/2]
template<typename T> bool llvm::ArrayRef< T >::equals (TRefOrNothing Arg0 = TRefOrNothing(), TRefOrNothing Arg1 = TRefOrNothing(), TRefOrNothing Arg2 = TRefOrNothing(), TRefOrNothing Arg3 = TRefOrNothing(), TRefOrNothing Arg4 = TRefOrNothing(), TRefOrNothing Arg5 = TRefOrNothing(), TRefOrNothing Arg6 = TRefOrNothing(), TRefOrNothing Arg7 = TRefOrNothing(), TRefOrNothing Arg8 = TRefOrNothing(), TRefOrNothing Arg9 = TRefOrNothing(), TRefOrNothing Arg10 = TRefOrNothing(), TRefOrNothing Arg11 = TRefOrNothing(), TRefOrNothing Arg12 = TRefOrNothing(), TRefOrNothing Arg13 = TRefOrNothing(), TRefOrNothing Arg14 = TRefOrNothing(), TRefOrNothing Arg15 = TRefOrNothing()) inline
Predicate for testing that the array equals the exact sequence of arguments.
Will return false if the size is not equal to the exact number of arguments given or if the array elements don't equal the argument elements in order. Currently supports up to 16 arguments, but can easily be extended.
Definition at line 217 of file ArrayRef.h.
front()
template<typename T> const T & llvm::ArrayRef< T >::front () const inline
front - Get the first element.
Definition at line 134 of file ArrayRef.h.
Referenced by DecodeFixedType(), and llvm::PrintMessage().
operator std::vector< T >()
template<typename T> llvm::ArrayRef< T >::operator std::vector< T > () const inline
Definition at line 202 of file ArrayRef.h.
operator[]()
template<typename T> const T & llvm::ArrayRef< T >::operator[] (size_t Index) const inline
Definition at line 187 of file ArrayRef.h.
rbegin()
template<typename T> reverse_iterator llvm::ArrayRef< T >::rbegin () const inline
Definition at line 122 of file ArrayRef.h.
Referenced by getNoopInput(), and llvm::ScheduleDAGMI::initQueues().
rend()
template<typename T> reverse_iterator llvm::ArrayRef< T >::rend () const inline
Definition at line 123 of file ArrayRef.h.
Referenced by getNoopInput(), and llvm::ScheduleDAGMI::initQueues().
size()
template<typename T> size_t llvm::ArrayRef< T >::size () const inline
size - Get the array size.
Definition at line 131 of file ArrayRef.h.
Referenced by llvm::MachineModuleInfo::addCatchTypeInfo(), llvm::MachineModuleInfo::addFilterTypeInfo(), llvm::RegPressureTracker::addLiveRegs(), llvm::CCState::AllocateRegBlock(), llvm::MutableArrayRef< T >::back(), llvm::yaml::BinaryRef::binary_size(), BuildNew(), CanEvaluateShuffled(), canLowerByDroppingEvenElements(), canWidenShuffleElements(), CastGEPIndices(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), llvm::ComputeEditDistance(), computeExcessPressureDelta(), computeMaxPressureDelta(), computeZeroableShuffleElements(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInstOperands(), llvm::ConstantFoldLoadThroughGEPIndices(), llvm::convertUTF16ToUTF8String(), llvm::AArch64InstrInfo::copyPhysRegTuple(), llvm::CallInst::Create(), llvm::CallInst::Create(), llvm::GetElementPtrConstantExpr::Create(), llvm::GetElementPtrInst::Create(), llvm::GetElementPtrInst::Create(), llvm::InvokeInst::Create(), llvm::InvokeInst::Create(), llvm::MDBuilder::createBranchWeights(), llvm::IRBuilderBase::CreateGCStatepoint(), llvm::IRBuilder< true, TargetFolder >::CreateGEP(), llvm::IRBuilder< true, TargetFolder >::CreateInBoundsGEP(), createPHIsForSplitLoopExit(), llvm::MDBuilder::createTBAAStructNode(), DecodeIITType(), llvm::DecodePSHUFBMask(), llvm::RegPressureTracker::decreaseRegPressure(), llvm::iterator< Attribute >::drop_back(), llvm::dumpRegSetPressure(), llvm::LiveRangeEdit::eliminateDeadDefs(), llvm::MCDwarfFrameEmitter::Emit(), llvm::MCDwarfLineTableHeader::Emit(), llvm::MutableArrayRef< T >::end(), llvm::iterator< Attribute >::equals(), llvm::object::MachOObjectFile::exports(), llvm::LiveIntervals::extendToIndices(), llvm::DWARFDebugInfoEntryMinimal::extractFast(), llvm::FindInsertedValue(), llvm::AttributeSet::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::FunctionType::get(), llvm::MDNodeFwdDecl::get(), getAllocatableSetForRC(), llvm::SelectionDAG::getAtomic(), llvm::MDTuple::getDistinct(), llvm::SubtargetFeatures::getFeatureBits(), llvm::IndexedInstrProfReader::getFunctionCounts(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getGetElementPtr(), llvm::DataLayout::getIndexedOffset(), getIndexedTypeInternal(), llvm::AArch64Disassembler::getInstruction(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMergeValues(), llvm::Intrinsic::getName(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), getNoopInput(), llvm::DIBuilder::getOrCreateTypeArray(), getOrSelfReference(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::MachineTraceMetrics::Trace::getResourceDepth(), llvm::MachineTraceMetrics::Trace::getResourceLength(), llvm::object::COFFObjectFile::getSectionContents(), llvm::RegPressureTracker::getUpwardPressureDelta(), getV4X86ShuffleImm8ForMask(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::getVTList(), llvm::ConstantExpr::getWithOperands(), llvm::MipsTargetLowering::HandleByVal(), llvm::hasUTF16ByteOrderMark(), llvm::RegPressureTracker::increaseRegPressure(), is128BitLaneCrossingShuffleMask(), is128BitLaneRepeatedShuffleMask(), isInBoundsIndices(), isINSMask(), isNoopShuffleMask(), isReverseMask(), isShuffleMaskInputInPlace(), isSingleInputShuffleMask(), isVTBLMask(), lowerV16F32VectorShuffle(), lowerV16I16VectorShuffle(), lowerV16I32VectorShuffle(), lowerV16I8VectorShuffle(), lowerV2F64VectorShuffle(), lowerV2I64VectorShuffle(), lowerV32I16VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV4I64VectorShuffle(), lowerV64I8VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8F64VectorShuffle(), lowerV8I16BasicBlendVectorShuffle(), lowerV8I16SingleInputVectorShuffle(), lowerV8I16VectorShuffle(), lowerV8I32VectorShuffle(), lowerV8I64VectorShuffle(), lowerVectorShuffleAsBlend(), lowerVectorShuffleAsBroadcast(), lowerVectorShuffleAsByteRotate(), lowerVectorShuffleAsByteShift(), lowerVectorShuffleAsDecomposedShuffleBlend(), lowerVectorShuffleAsElementInsertion(), lowerVectorShuffleAsInsertPS(), lowerVectorShuffleAsLanePermuteAndBlend(), lowerVectorShuffleAsSplitOrBlend(), lowerVectorShuffleAsZeroOrAnyExtend(), lowerVectorShuffleByMerging128BitLanes(), llvm::MDNode::MDNode(), llvm::SelectionDAG::MorphNodeTo(), llvm::MutableArrayRef< T >::operator[](), parseCond(), parseCond(), llvm::PrintMessage(), ProcessSDDbgValues(), llvm::AttributeSetNode::Profile(), ProfileBitsInit(), ProfileListInit(), readInstruction16(), readInstruction16(), readInstruction32(), readInstruction32(), readInstruction32(), llvm::IndexedInstrProfReader::readNextRecord(), ReadWideAPInt(), regionReader(), llvm::LiveIntervals::repairIntervalsInRange(), llvm::SDNode::SDNode(), llvm::StructType::setBody(), shouldLowerAsInterleaving(), SimplifyGEPInst(), llvm::iterator< Attribute >::slice(), llvm::iterator< Attribute >::slice(), llvm::MutableArrayRef< T >::slice(), llvm::MutableArrayRef< T >::slice(), splitAndLowerVectorShuffle(), llvm::SplitBlockPredecessors(), llvm::SplitLandingPadPredecessors(), SymbolicallyEvaluateGEP(), llvm::MD5::update(), llvm::SelectionDAG::UpdateNodeOperands(), UpdatePHINodes(), llvm::ScheduleDAGMILive::updatePressureDiffs(), and llvm::WriteConstantInternal().
slice() [1/2]
template<typename T> ArrayRef< T > llvm::ArrayRef< T >::slice (unsigned N) const inline
slice(n) - Chop off the first N elements of the array.
Definition at line 166 of file ArrayRef.h.
Referenced by BuildNew(), CastGEPIndices(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantFoldInstOperands(), createReplacementInstr(), DecodeFixedType(), llvm::iterator< Attribute >::drop_back(), llvm::FindInsertedValue(), llvm::ConstantExpr::getAsInstruction(), llvm::IndexedInstrProfReader::getFunctionCounts(), llvm::ConstantExpr::getWithOperands(), llvm::IndexedInstrProfReader::readNextRecord(), llvm::LiveRangeEdit::regs(), SimplifyGEPInst(), splitAndLowerVectorShuffle(), and llvm::InstCombiner::visitExtractValueInst().
slice() [2/2]
template<typename T> ArrayRef< T > llvm::ArrayRef< T >::slice (unsigned N, unsigned M) const inline
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
Definition at line 173 of file ArrayRef.h.
vec()
template<typename T> std::vector< T > llvm::ArrayRef< T >::vec () const inline
Definition at line 195 of file ArrayRef.h.
The documentation for this class was generated from the following file:
ArrayRef.h