LLVM: llvm::LexicalScope Class Reference
LLVM API Documentation
llvm::LexicalScope Class Reference
#include <LexicalScopes.h>
Public Member Functions
LexicalScope (LexicalScope *P, const MDNode *D, const MDNode *I, bool A)
LexicalScope * getParent () const
const MDNode * getDesc () const
const MDNode * getInlinedAt () const
const MDNode * getScopeNode () const
bool isAbstractScope () const
SmallVectorImpl< LexicalScope * > & getChildren ()
SmallVectorImpl< InsnRange > & getRanges ()
void addChild (LexicalScope *S)
addChild - Add a child scope.
void openInsnRange (const MachineInstr *MI)
openInsnRange - This scope covers instruction range starting from MI.
void extendInsnRange (const MachineInstr *MI)
void closeInsnRange (LexicalScope *NewScope=nullptr)
bool dominates (const LexicalScope *S) const
dominates - Return true if current scope dominates given lexical scope.
unsigned getDFSOut () const
void setDFSOut (unsigned O)
unsigned getDFSIn () const
void setDFSIn (unsigned I)
void dump (unsigned Indent=0) const
dump - print lexical scope.
Detailed Description
LexicalScope - This class is used to track scope information.
Definition at line 45 of file LexicalScopes.h.
Constructor & Destructor Documentation
LexicalScope()
llvm::LexicalScope::LexicalScope (LexicalScope * P, const MDNode * D, const MDNode * I, bool A) inline
Definition at line 48 of file LexicalScopes.h.
References I, llvm::MDNode::isResolved(), LexicalScope(), and P.
Referenced by addChild(), closeInsnRange(), dominates(), getParent(), and LexicalScope().
Member Function Documentation
addChild()
void llvm::LexicalScope::addChild (LexicalScope * S) inline
addChild - Add a child scope.
Definition at line 67 of file LexicalScopes.h.
References LexicalScope().
closeInsnRange()
void llvm::LexicalScope::closeInsnRange (LexicalScope * NewScope = nullptr) inline
closeInsnRange - Create a range based on FirstInsn and LastInsn collected until now. This is used when a new scope is encountered while walking machine instructions.
Definition at line 90 of file LexicalScopes.h.
References LexicalScope().
dominates()
bool llvm::LexicalScope::dominates (const LexicalScope * S) const inline
dominates - Return true if current scope dominates given lexical scope.
Definition at line 102 of file LexicalScopes.h.
References getDFSIn(), getDFSOut(), and LexicalScope().
Referenced by llvm::LexicalScopes::dominates().
dump()
void LexicalScope::dump (unsigned Indent = 0) const
dump - print lexical scope.
dump - Print data structures.
Definition at line 339 of file LexicalScopes.cpp.
References llvm::dbgs(), llvm::raw_ostream::indent(), and N.
extendInsnRange()
void llvm::LexicalScope::extendInsnRange (const MachineInstr * MI) inline
extendInsnRange - Extend the current instruction range covered by this scope.
Definition at line 80 of file LexicalScopes.h.
getChildren()
SmallVectorImpl< LexicalScope * > & llvm::LexicalScope::getChildren () inline
Definition at line 63 of file LexicalScopes.h.
Referenced by llvm::DwarfCompileUnit::createScopeChildrenDIE().
getDesc()
const MDNode * llvm::LexicalScope::getDesc () const inline
Definition at line 59 of file LexicalScopes.h.
getDFSIn()
unsigned llvm::LexicalScope::getDFSIn () const inline
Definition at line 113 of file LexicalScopes.h.
Referenced by dominates().
getDFSOut()
unsigned llvm::LexicalScope::getDFSOut () const inline
Definition at line 111 of file LexicalScopes.h.
Referenced by dominates().
getInlinedAt()
const MDNode * llvm::LexicalScope::getInlinedAt () const inline
Definition at line 60 of file LexicalScopes.h.
Referenced by llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructScopeDIE(), and llvm::DwarfCompileUnit::constructSubprogramScopeDIE().
getParent()
LexicalScope * llvm::LexicalScope::getParent () const inline
Definition at line 58 of file LexicalScopes.h.
References LexicalScope().
Referenced by llvm::DwarfCompileUnit::constructScopeDIE().
getRanges()
SmallVectorImpl< InsnRange > & llvm::LexicalScope::getRanges () inline
Definition at line 64 of file LexicalScopes.h.
Referenced by llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructLexicalScopeDIE(), llvm::LexicalScopes::getMachineBasicBlocks(), and llvm::DwarfDebug::isLexicalScopeDIENull().
getScopeNode()
const MDNode * llvm::LexicalScope::getScopeNode () const inline
Definition at line 61 of file LexicalScopes.h.
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfCompileUnit::constructScopeDIE(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), and llvm::DwarfDebug::endFunction().
isAbstractScope()
bool llvm::LexicalScope::isAbstractScope () const inline
Definition at line 62 of file LexicalScopes.h.
Referenced by llvm::DwarfCompileUnit::constructLexicalScopeDIE(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructVariableDIE(), and llvm::DwarfDebug::isLexicalScopeDIENull().
openInsnRange()
void llvm::LexicalScope::openInsnRange (const MachineInstr * MI) inline
openInsnRange - This scope covers instruction range starting from MI.
Definition at line 70 of file LexicalScopes.h.
setDFSIn()
void llvm::LexicalScope::setDFSIn (unsigned I) inline
Definition at line 114 of file LexicalScopes.h.
References I.
setDFSOut()
void llvm::LexicalScope::setDFSOut (unsigned O) inline
Definition at line 112 of file LexicalScopes.h.
The documentation for this class was generated from the following files:
LexicalScopes.h
LexicalScopes.cpp