LLVM: llvm::MDOperand Class Reference
LLVM API Documentation
llvm::MDOperand Class Reference
Tracking metadata reference owned by Metadata.
#include <Metadata.h>
Public Member Functions
MDOperand ()
~MDOperand ()
Metadata * get () const
operator Metadata * () const
Metadata * operator-> () const
Metadata & operator* () const
void reset ()
void reset (Metadata *MD, Metadata *Owner)
Detailed Description
Tracking metadata reference owned by Metadata.
Similar to TrackingMDRef, but it's expected to be owned by an instance of Metadata, which has the option of registering itself for callbacks to re-unique itself.
In particular, this is used by MDNode.
Definition at line 530 of file Metadata.h.
Constructor & Destructor Documentation
MDOperand()
llvm::MDOperand::MDOperand () inline
Definition at line 539 of file Metadata.h.
~MDOperand()
llvm::MDOperand::~MDOperand () inline
Definition at line 540 of file Metadata.h.
Member Function Documentation
get()
Metadata * llvm::MDOperand::get () const inline
Definition at line 542 of file Metadata.h.
Referenced by llvm::simplify_type< const MDOperand >::getSimplifiedValue(), llvm::simplify_type< MDOperand >::getSimplifiedValue(), operator Metadata *(), operator*(), and operator->().
operator Metadata *()
llvm::MDOperand::operator Metadata * () const inline
Definition at line 543 of file Metadata.h.
References get().
operator*()
Metadata & llvm::MDOperand::operator* () const inline
Definition at line 545 of file Metadata.h.
References get().
operator->()
Metadata * llvm::MDOperand::operator-> () const inline
Definition at line 544 of file Metadata.h.
References get().
reset() [1/2]
void llvm::MDOperand::reset () inline
Definition at line 547 of file Metadata.h.
Referenced by llvm::MDNode::setOperand().
reset() [2/2]
void llvm::MDOperand::reset (Metadata * MD, Metadata * Owner) inline
Definition at line 551 of file Metadata.h.
The documentation for this class was generated from the following file:
Metadata.h