LLVM: llvm::SystemZInstrInfo Class Reference
LLVM API Documentation
llvm::SystemZInstrInfo Class Reference
#include <SystemZInstrInfo.h>
Public Member Functions
SystemZInstrInfo (SystemZSubtarget &STI)
unsigned isLoadFromStackSlot (const MachineInstr *MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr *MI, int &FrameIndex) const override
bool isStackSlotCopy (const MachineInstr *MI, int &DestFrameIndex, int &SrcFrameIndex) const override
bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
unsigned RemoveBranch (MachineBasicBlock &MBB) const override
unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const override
bool analyzeCompare (const MachineInstr *MI, unsigned &SrcReg, unsigned &SrcReg2, int &Mask, int &Value) const override
bool optimizeCompareInstr (MachineInstr *CmpInstr, unsigned SrcReg, unsigned SrcReg2, int Mask, int Value, const MachineRegisterInfo *MRI) const override
bool isPredicable (MachineInstr *MI) const override
bool isProfitableToIfCvt (MachineBasicBlock &MBB, unsigned NumCycles, unsigned ExtraPredCycles, const BranchProbability &Probability) const override
bool isProfitableToIfCvt (MachineBasicBlock &TMBB, unsigned NumCyclesT, unsigned ExtraPredCyclesT, MachineBasicBlock &FMBB, unsigned NumCyclesF, unsigned ExtraPredCyclesF, const BranchProbability &Probability) const override
bool PredicateInstruction (MachineInstr *MI, const SmallVectorImpl< MachineOperand > &Pred) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIdx, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
MachineInstr * convertToThreeAddress (MachineFunction::iterator &MFI, MachineBasicBlock::iterator &MBBI, LiveVariables *LV) const override
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, int FrameIndex) const override
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, MachineInstr *LoadMI) const override
bool expandPostRAPseudo (MachineBasicBlock::iterator MBBI) const override
bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
const SystemZRegisterInfo & getRegisterInfo () const
uint64_t getInstSizeInBytes (const MachineInstr *MI) const
SystemZII::Branch getBranchInfo (const MachineInstr *MI) const
void getLoadStoreOpcodes (const TargetRegisterClass *RC, unsigned &LoadOpcode, unsigned &StoreOpcode) const
unsigned getOpcodeForOffset (unsigned Opcode, int64_t Offset) const
unsigned getLoadAndTest (unsigned Opcode) const
bool isRxSBGMask (uint64_t Mask, unsigned BitSize, unsigned &Start, unsigned &End) const
unsigned getCompareAndBranch (unsigned Opcode, const MachineInstr *MI=nullptr) const
void loadImmediate (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned Reg, uint64_t Value) const
Detailed Description
Definition at line 114 of file SystemZInstrInfo.h.
Constructor & Destructor Documentation
SystemZInstrInfo()
SystemZInstrInfo::SystemZInstrInfo (SystemZSubtarget & STI) explicit
Definition at line 43 of file SystemZInstrInfo.cpp.
Member Function Documentation
AnalyzeBranch()
bool SystemZInstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Definition at line 241 of file SystemZInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SystemZII::BranchNormal, llvm::SystemZ::CCMASK_ANY, llvm::SmallVectorImpl< T >::clear(), llvm::MachineOperand::CreateImm(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), getBranchInfo(), I, llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
analyzeCompare()
bool SystemZInstrInfo::analyzeCompare (const MachineInstr * MI, unsigned & SrcReg, unsigned & SrcReg2, int & Mask, int & Value) const override
Definition at line 399 of file SystemZInstrInfo.cpp.
convertToThreeAddress()
MachineInstr * SystemZInstrInfo::convertToThreeAddress (MachineFunction::iterator & MFI, MachineBasicBlock::iterator & MBBI, LiveVariables * LV) const override
Definition at line 674 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), allOnes(), llvm::BuildMI(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::TargetRegisterClass::contains(), finishConvertToThreeAddress(), llvm::getKillRegState(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::getSubReg(), I, interpretAndImmediate(), llvm::MachineOperand::isKill(), isRxSBGMask(), and llvm::TargetRegisterInfo::isVirtualRegister().
copyPhysReg()
void SystemZInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
Definition at line 553 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), copyPhysReg(), llvm::getKillRegState(), and llvm_unreachable.
Referenced by copyPhysReg().
expandPostRAPseudo()
bool SystemZInstrInfo::expandPostRAPseudo (MachineBasicBlock::iterator MBBI) const override
Definition at line 872 of file SystemZInstrInfo.cpp.
References isHighReg().
foldMemoryOperandImpl() [1/2]
MachineInstr * SystemZInstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, const SmallVectorImpl< unsigned > & Ops, int FrameIndex) const override
Definition at line 747 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::SystemZII::getAccessSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineMemOperand::getSize(), llvm::TargetRegisterClass::getSize(), llvm::SystemZII::HasIndex, I, llvm::isInt(), isSimpleBD12Move(), llvm::MachineMemOperand::isVolatile(), llvm::SystemZII::SimpleBDXLoad, llvm::SystemZII::SimpleBDXStore, llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::MCInstrDesc::TSFlags.
foldMemoryOperandImpl() [2/2]
MachineInstr * SystemZInstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, const SmallVectorImpl< unsigned > & Ops, MachineInstr * LoadMI) const override
Definition at line 865 of file SystemZInstrInfo.cpp.
getBranchInfo()
SystemZII::Branch SystemZInstrInfo::getBranchInfo (const MachineInstr * MI) const
Definition at line 1041 of file SystemZInstrInfo.cpp.
References llvm::SystemZII::BranchC, llvm::SystemZII::BranchCG, llvm::SystemZII::BranchCL, llvm::SystemZII::BranchCLG, llvm::SystemZII::BranchCT, llvm::SystemZII::BranchCTG, llvm::SystemZII::BranchNormal, llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_ICMP, and llvm_unreachable.
Referenced by AnalyzeBranch(), and RemoveBranch().
getCompareAndBranch()
unsigned SystemZInstrInfo::getCompareAndBranch (unsigned Opcode, const MachineInstr * MI = nullptr) const
Definition at line 1206 of file SystemZInstrInfo.cpp.
References llvm::isInt< 8 >(), and llvm::isUInt< 8 >().
getInstSizeInBytes()
uint64_t SystemZInstrInfo::getInstSizeInBytes (const MachineInstr * MI) const
Definition at line 1031 of file SystemZInstrInfo.cpp.
References llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getTarget(), and llvm::TargetOpcode::INLINEASM.
getLoadAndTest()
unsigned SystemZInstrInfo::getLoadAndTest (unsigned Opcode) const
Definition at line 1148 of file SystemZInstrInfo.cpp.
getLoadStoreOpcodes()
void SystemZInstrInfo::getLoadStoreOpcodes (const TargetRegisterClass * RC, unsigned & LoadOpcode, unsigned & StoreOpcode) const
Definition at line 1088 of file SystemZInstrInfo.cpp.
References llvm_unreachable.
Referenced by loadRegFromStackSlot(), and storeRegToStackSlot().
getOpcodeForOffset()
unsigned SystemZInstrInfo::getOpcodeForOffset (unsigned Opcode, int64_t Offset) const
Definition at line 1121 of file SystemZInstrInfo.cpp.
References llvm::SystemZII::Has20BitOffset, llvm::SystemZII::Is128Bit, llvm::isInt(), and llvm::isUInt().
getRegisterInfo()
const SystemZRegisterInfo & llvm::SystemZInstrInfo::getRegisterInfo () const inline
Definition at line 196 of file SystemZInstrInfo.h.
InsertBranch()
unsigned SystemZInstrInfo::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, const SmallVectorImpl< MachineOperand > & Cond, DebugLoc DL) const override
Definition at line 363 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::BuildMI(), llvm::SmallVectorBase::empty(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
isLoadFromStackSlot()
unsigned SystemZInstrInfo::isLoadFromStackSlot (const MachineInstr * MI, int & FrameIndex) const override
Definition at line 206 of file SystemZInstrInfo.cpp.
References isSimpleMove(), and llvm::SystemZII::SimpleBDXLoad.
isPredicable()
bool SystemZInstrInfo::isPredicable (MachineInstr * MI) const override
Definition at line 506 of file SystemZInstrInfo.cpp.
References getConditionalMove().
isProfitableToIfCvt() [1/2]
bool SystemZInstrInfo::isProfitableToIfCvt (MachineBasicBlock & MBB, unsigned NumCycles, unsigned ExtraPredCycles, const BranchProbability & Probability) const override
Definition at line 514 of file SystemZInstrInfo.cpp.
isProfitableToIfCvt() [2/2]
bool SystemZInstrInfo::isProfitableToIfCvt (MachineBasicBlock & TMBB, unsigned NumCyclesT, unsigned ExtraPredCyclesT, MachineBasicBlock & FMBB, unsigned NumCyclesF, unsigned ExtraPredCyclesF, const BranchProbability & Probability) const override
Definition at line 522 of file SystemZInstrInfo.cpp.
isRxSBGMask()
bool SystemZInstrInfo::isRxSBGMask (uint64_t Mask, unsigned BitSize, unsigned & Start, unsigned & End) const
Definition at line 1178 of file SystemZInstrInfo.cpp.
References allOnes(), and isStringOfOnes().
Referenced by convertToThreeAddress().
isStackSlotCopy()
bool SystemZInstrInfo::isStackSlotCopy (const MachineInstr * MI, int & DestFrameIndex, int & SrcFrameIndex) const override
Definition at line 216 of file SystemZInstrInfo.cpp.
References llvm::MachineFrameInfo::getObjectSize().
isStoreToStackSlot()
unsigned SystemZInstrInfo::isStoreToStackSlot (const MachineInstr * MI, int & FrameIndex) const override
Definition at line 211 of file SystemZInstrInfo.cpp.
References isSimpleMove(), and llvm::SystemZII::SimpleBDXStore.
loadImmediate()
void SystemZInstrInfo::loadImmediate (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned Reg, uint64_t Value) const
Definition at line 1230 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDebugLoc(), llvm::SystemZ::isImmLH(), llvm::SystemZ::isImmLL(), and llvm::isInt().
loadRegFromStackSlot()
void SystemZInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIdx, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 606 of file SystemZInstrInfo.cpp.
References llvm::addFrameReference(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDebugLoc(), and getLoadStoreOpcodes().
optimizeCompareInstr()
bool SystemZInstrInfo::optimizeCompareInstr (MachineInstr * CmpInstr, unsigned SrcReg, unsigned SrcReg2, int Mask, int Value, const MachineRegisterInfo * MRI) const override
Definition at line 483 of file SystemZInstrInfo.cpp.
References llvm::SystemZII::IsLogical, and removeIPMBasedCompare().
PredicateInstruction()
bool SystemZInstrInfo::PredicateInstruction (MachineInstr * MI, const SmallVectorImpl< MachineOperand > & Pred) const override
Definition at line 532 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), getConditionalMove(), llvm::RegState::Implicit, and llvm::SmallVectorTemplateCommon< T, typename >::size().
RemoveBranch()
unsigned SystemZInstrInfo::RemoveBranch (MachineBasicBlock & MBB) const override
Definition at line 333 of file SystemZInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), getBranchInfo(), and I.
ReverseBranchCondition()
bool SystemZInstrInfo::ReverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 355 of file SystemZInstrInfo.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
storeRegToStackSlot()
void SystemZInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 589 of file SystemZInstrInfo.cpp.
References llvm::addFrameReference(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDebugLoc(), llvm::getKillRegState(), and getLoadStoreOpcodes().
The documentation for this class was generated from the following files:
SystemZInstrInfo.h
SystemZInstrInfo.cpp