LLVM: llvm::WinEH::UnwindEmitter Class Reference
LLVM API Documentation
llvm::WinEH::UnwindEmitter Class Reference abstract
#include <MCWinEH.h>
Public Member Functions
virtual ~UnwindEmitter ()
virtual void Emit (MCStreamer &Streamer) const =0
virtual void EmitUnwindInfo (MCStreamer &Streamer, FrameInfo *FI) const =0
Static Public Member Functions
static const MCSection * getPDataSection (const MCSymbol *Function, MCContext &Context)
static const MCSection * getXDataSection (const MCSymbol *Function, MCContext &Context)
Detailed Description
Definition at line 66 of file MCWinEH.h.
Constructor & Destructor Documentation
~UnwindEmitter()
virtual llvm::WinEH::UnwindEmitter::~UnwindEmitter () inline virtual
Definition at line 73 of file MCWinEH.h.
Member Function Documentation
Emit()
virtual void llvm::WinEH::UnwindEmitter::Emit (MCStreamer & Streamer) const pure virtual
Implemented in llvm::Win64EH::UnwindEmitter.
EmitUnwindInfo()
virtual void llvm::WinEH::UnwindEmitter::EmitUnwindInfo (MCStreamer & Streamer, FrameInfo * FI) const pure virtual
Implemented in llvm::Win64EH::UnwindEmitter.
getPDataSection()
const MCSection * llvm::WinEH::UnwindEmitter::getPDataSection (const MCSymbol * Function, MCContext & Context) static
Definition at line 61 of file MCWinEH.cpp.
References llvm::cast(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getPDataSection(), and llvm::WinEH::getUnwindInfoSection().
Referenced by llvm::Win64EH::UnwindEmitter::Emit().
getXDataSection()
const MCSection * llvm::WinEH::UnwindEmitter::getXDataSection (const MCSymbol * Function, MCContext & Context) static
Definition at line 68 of file MCWinEH.cpp.
References llvm::cast(), llvm::MCContext::getObjectFileInfo(), llvm::WinEH::getUnwindInfoSection(), and llvm::MCObjectFileInfo::getXDataSection().
Referenced by llvm::Win64EH::UnwindEmitter::Emit(), and llvm::Win64EH::UnwindEmitter::EmitUnwindInfo().
The documentation for this class was generated from the following files:
MCWinEH.h
MCWinEH.cpp