LLVM: llvm::X86AsmInstrumentation Class Reference
LLVM API Documentation
llvm::X86AsmInstrumentation Class Reference
#include <X86AsmInstrumentation.h>
Public Member Functions
virtual ~X86AsmInstrumentation ()
void SetInitialFrameRegister (unsigned RegNo)
virtual void InstrumentAndEmitInstruction (const MCInst &Inst, SmallVectorImpl< std::unique_ptr< MCParsedAsmOperand > > &Operands, MCContext &Ctx, const MCInstrInfo &MII, MCStreamer &Out)
Protected Member Functions
X86AsmInstrumentation (const MCSubtargetInfo &STI)
unsigned GetFrameRegGeneric (const MCContext &Ctx, MCStreamer &Out)
void EmitInstruction (MCStreamer &Out, const MCInst &Inst)
Protected Attributes
const MCSubtargetInfo & STI
unsigned InitialFrameReg
Friends
X86AsmInstrumentation * CreateX86AsmInstrumentation (const MCTargetOptions &MCOptions, const MCContext &Ctx, const MCSubtargetInfo &STI)
Detailed Description
Definition at line 33 of file X86AsmInstrumentation.h.
Constructor & Destructor Documentation
~X86AsmInstrumentation()
llvm::X86AsmInstrumentation::~X86AsmInstrumentation () virtual
Definition at line 1037 of file X86AsmInstrumentation.cpp.
X86AsmInstrumentation()
llvm::X86AsmInstrumentation::X86AsmInstrumentation (const MCSubtargetInfo & STI) protected
Definition at line 1034 of file X86AsmInstrumentation.cpp.
References InitialFrameReg, and STI.
Referenced by CreateX86AsmInstrumentation.
Member Function Documentation
EmitInstruction()
void llvm::X86AsmInstrumentation::EmitInstruction (MCStreamer & Out, const MCInst & Inst) protected
Definition at line 1045 of file X86AsmInstrumentation.cpp.
References llvm::MCStreamer::EmitInstruction(), and STI.
Referenced by InstrumentAndEmitInstruction().
GetFrameRegGeneric()
unsigned llvm::X86AsmInstrumentation::GetFrameRegGeneric (const MCContext & Ctx, MCStreamer & Out) protected
Definition at line 1050 of file X86AsmInstrumentation.cpp.
References llvm::MCDwarfFrameInfo::CurrentCfaRegister, llvm::MCDwarfFrameInfo::End, llvm::MCStreamer::getDwarfFrameInfos(), llvm::MCRegisterInfo::getLLVMRegNum(), llvm::MCStreamer::getNumFrameInfos(), and InitialFrameReg.
InstrumentAndEmitInstruction()
void llvm::X86AsmInstrumentation::InstrumentAndEmitInstruction (const MCInst & Inst, SmallVectorImpl< std::unique_ptr< MCParsedAsmOperand > > & Operands, MCContext & Ctx, const MCInstrInfo & MII, MCStreamer & Out) virtual
Definition at line 1039 of file X86AsmInstrumentation.cpp.
References EmitInstruction(), and Operands.
SetInitialFrameRegister()
void llvm::X86AsmInstrumentation::SetInitialFrameRegister (unsigned RegNo) inline
Definition at line 38 of file X86AsmInstrumentation.h.
References InitialFrameReg.
Friends And Related Symbol Documentation
CreateX86AsmInstrumentation
X86AsmInstrumentation * CreateX86AsmInstrumentation (const MCTargetOptions & MCOptions, const MCContext & Ctx, const MCSubtargetInfo & STI) friend
Definition at line 1070 of file X86AsmInstrumentation.cpp.
References llvm::MCTargetOptions::SanitizeAddress, STI, T, and X86AsmInstrumentation().
Member Data Documentation
InitialFrameReg
unsigned llvm::X86AsmInstrumentation::InitialFrameReg protected
Definition at line 61 of file X86AsmInstrumentation.h.
Referenced by GetFrameRegGeneric(), SetInitialFrameRegister(), and X86AsmInstrumentation().
STI
const MCSubtargetInfo& llvm::X86AsmInstrumentation::STI protected
Definition at line 59 of file X86AsmInstrumentation.h.
Referenced by CreateX86AsmInstrumentation, EmitInstruction(), and X86AsmInstrumentation().
The documentation for this class was generated from the following files:
X86AsmInstrumentation.h
X86AsmInstrumentation.cpp