LLVM: llvm::StringMapConstIterator< ValueTy > Class Template Reference
LLVM API Documentation
llvm::StringMapConstIterator< ValueTy > Class Template Reference
#include <StringMap.h>
Public Types
typedef StringMapEntry< ValueTy > value_type
Public Member Functions
StringMapConstIterator ()
StringMapConstIterator (StringMapEntryBase **Bucket, bool NoAdvance=false)
const value_type & operator* () const
const value_type * operator-> () const
bool operator== (const StringMapConstIterator &RHS) const
bool operator!= (const StringMapConstIterator &RHS) const
StringMapConstIterator & operator++ ()
StringMapConstIterator operator++ (int)
Protected Attributes
StringMapEntryBase ** Ptr
Detailed Description
template<typename ValueTy>
class llvm::StringMapConstIterator< ValueTy >
Definition at line 390 of file StringMap.h.
Member Typedef Documentation
value_type
template<typename ValueTy> typedef StringMapEntry<ValueTy> llvm::StringMapConstIterator< ValueTy >::value_type
Definition at line 394 of file StringMap.h.
Constructor & Destructor Documentation
StringMapConstIterator() [1/2]
template<typename ValueTy> llvm::StringMapConstIterator< ValueTy >::StringMapConstIterator () inline
Definition at line 396 of file StringMap.h.
References Ptr.
Referenced by operator!=(), operator++(), operator++(), operator==(), and llvm::StringMapIterator< ValueTy >::StringMapIterator().
StringMapConstIterator() [2/2]
template<typename ValueTy> llvm::StringMapConstIterator< ValueTy >::StringMapConstIterator (StringMapEntryBase ** Bucket, bool NoAdvance = false) inline explicit
Definition at line 398 of file StringMap.h.
References Ptr.
Member Function Documentation
operator!=()
template<typename ValueTy> bool llvm::StringMapConstIterator< ValueTy >::operator!= (const StringMapConstIterator< ValueTy > & RHS) const inline
Definition at line 414 of file StringMap.h.
References Ptr, and StringMapConstIterator().
operator*()
template<typename ValueTy> const value_type & llvm::StringMapConstIterator< ValueTy >::operator* () const inline
Definition at line 404 of file StringMap.h.
operator++() [1/2]
template<typename ValueTy> StringMapConstIterator & llvm::StringMapConstIterator< ValueTy >::operator++ () inline
Definition at line 418 of file StringMap.h.
References Ptr, and StringMapConstIterator().
operator++() [2/2]
template<typename ValueTy> StringMapConstIterator llvm::StringMapConstIterator< ValueTy >::operator++ (int) inline
Definition at line 423 of file StringMap.h.
References StringMapConstIterator().
operator->()
template<typename ValueTy> const value_type * llvm::StringMapConstIterator< ValueTy >::operator-> () const inline
Definition at line 407 of file StringMap.h.
operator==()
template<typename ValueTy> bool llvm::StringMapConstIterator< ValueTy >::operator== (const StringMapConstIterator< ValueTy > & RHS) const inline
Definition at line 411 of file StringMap.h.
References Ptr, and StringMapConstIterator().
Member Data Documentation
Ptr
template<typename ValueTy> StringMapEntryBase** llvm::StringMapConstIterator< ValueTy >::Ptr protected
Definition at line 392 of file StringMap.h.
Referenced by operator!=(), operator++(), operator==(), StringMapConstIterator(), and StringMapConstIterator().
The documentation for this class was generated from the following file:
StringMap.h