LLVM: llvm::PointerUnion4< PT1, PT2, PT3, PT4 > Class Template Reference
LLVM API Documentation
llvm::PointerUnion4< PT1, PT2, PT3, PT4 > Class Template Reference
#include <PointerUnion.h>
Public Types
typedef PointerUnion< PT1, PT2 > InnerUnion1
typedef PointerUnion< PT3, PT4 > InnerUnion2
typedef PointerUnion< InnerUnion1, InnerUnion2 > ValTy
Public Member Functions
PointerUnion4 ()
PointerUnion4 (PT1 V)
PointerUnion4 (PT2 V)
PointerUnion4 (PT3 V)
PointerUnion4 (PT4 V)
bool isNull () const
LLVM_EXPLICIT operator bool () const
template<typename T>
int is () const
is<T>() return true if the Union currently holds the type matching T.
template<typename T>
T get () const
template<typename T>
T dyn_cast () const
const PointerUnion4 & operator= (std::nullptr_t)
Assignment from nullptr which just clears the union.
const PointerUnion4 & operator= (const PT1 &RHS)
const PointerUnion4 & operator= (const PT2 &RHS)
const PointerUnion4 & operator= (const PT3 &RHS)
const PointerUnion4 & operator= (const PT4 &RHS)
void * getOpaqueValue () const
Static Public Member Functions
static PointerUnion4 getFromOpaqueValue (void *VP)
Detailed Description
template<typename PT1, typename PT2, typename PT3, typename PT4>
class llvm::PointerUnion4< PT1, PT2, PT3, PT4 >
PointerUnion4 - This is a pointer union of four pointer types. See documentation for PointerUnion for usage.
Definition at line 362 of file PointerUnion.h.
Member Typedef Documentation
InnerUnion1
template<typename PT1, typename PT2, typename PT3, typename PT4> typedef PointerUnion<PT1, PT2> llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::InnerUnion1
Definition at line 364 of file PointerUnion.h.
InnerUnion2
template<typename PT1, typename PT2, typename PT3, typename PT4> typedef PointerUnion<PT3, PT4> llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::InnerUnion2
Definition at line 365 of file PointerUnion.h.
ValTy
template<typename PT1, typename PT2, typename PT3, typename PT4> typedef PointerUnion<InnerUnion1, InnerUnion2> llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::ValTy
Definition at line 366 of file PointerUnion.h.
Constructor & Destructor Documentation
PointerUnion4() [1/5]
template<typename PT1, typename PT2, typename PT3, typename PT4> llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::PointerUnion4 () inline
Definition at line 370 of file PointerUnion.h.
Referenced by getFromOpaqueValue(), operator=(), operator=(), operator=(), operator=(), and operator=().
PointerUnion4() [2/5]
template<typename PT1, typename PT2, typename PT3, typename PT4> llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::PointerUnion4 (PT1 V) inline
Definition at line 372 of file PointerUnion.h.
PointerUnion4() [3/5]
template<typename PT1, typename PT2, typename PT3, typename PT4> llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::PointerUnion4 (PT2 V) inline
Definition at line 375 of file PointerUnion.h.
PointerUnion4() [4/5]
template<typename PT1, typename PT2, typename PT3, typename PT4> llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::PointerUnion4 (PT3 V) inline
Definition at line 378 of file PointerUnion.h.
PointerUnion4() [5/5]
template<typename PT1, typename PT2, typename PT3, typename PT4> llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::PointerUnion4 (PT4 V) inline
Definition at line 381 of file PointerUnion.h.
Member Function Documentation
dyn_cast()
template<typename PT1, typename PT2, typename PT3, typename PT4> template<typename T> T llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::dyn_cast () const inline
dyn_cast<T>() - If the current value is of the specified pointer type, return it, otherwise return null.
Definition at line 418 of file PointerUnion.h.
References get(), is(), and T.
get()
template<typename PT1, typename PT2, typename PT3, typename PT4> template<typename T> T llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::get () const inline
get<T>() - Return the value of the specified pointer type. If the specified pointer type is incorrect, assert.
Definition at line 405 of file PointerUnion.h.
References get(), is(), and T.
Referenced by dyn_cast(), get(), and is().
getFromOpaqueValue()
template<typename PT1, typename PT2, typename PT3, typename PT4> PointerUnion4 llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::getFromOpaqueValue (void * VP) inline static
Definition at line 449 of file PointerUnion.h.
References llvm::PointerUnion< InnerUnion1, InnerUnion2 >::getFromOpaqueValue(), and PointerUnion4().
Referenced by llvm::PointerLikeTypeTraits< PointerUnion4< PT1, PT2, PT3, PT4 > >::getFromVoidPointer().
getOpaqueValue()
template<typename PT1, typename PT2, typename PT3, typename PT4> void * llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::getOpaqueValue () const inline
Definition at line 448 of file PointerUnion.h.
is()
template<typename PT1, typename PT2, typename PT3, typename PT4> template<typename T> int llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::is () const inline
is<T>() return true if the Union currently holds the type matching T.
Definition at line 392 of file PointerUnion.h.
References get(), is(), and T.
Referenced by dyn_cast(), get(), and is().
isNull()
template<typename PT1, typename PT2, typename PT3, typename PT4> bool llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::isNull () const inline
isNull - Return true if the pointer held in the union is null, regardless of which type it is.
Definition at line 387 of file PointerUnion.h.
Referenced by operator bool().
operator bool()
template<typename PT1, typename PT2, typename PT3, typename PT4> LLVM_EXPLICIT llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::operator bool () const inline
Definition at line 388 of file PointerUnion.h.
References isNull(), and LLVM_EXPLICIT.
operator=() [1/5]
template<typename PT1, typename PT2, typename PT3, typename PT4> const PointerUnion4 & llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::operator= (const PT1 & RHS) inline
Assignment operators - Allow assigning into this union from either pointer type, setting the discriminator to remember what it came from.
Definition at line 431 of file PointerUnion.h.
References PointerUnion4().
operator=() [2/5]
template<typename PT1, typename PT2, typename PT3, typename PT4> const PointerUnion4 & llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::operator= (const PT2 & RHS) inline
Definition at line 435 of file PointerUnion.h.
References PointerUnion4().
operator=() [3/5]
template<typename PT1, typename PT2, typename PT3, typename PT4> const PointerUnion4 & llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::operator= (const PT3 & RHS) inline
Definition at line 439 of file PointerUnion.h.
References PointerUnion4().
operator=() [4/5]
template<typename PT1, typename PT2, typename PT3, typename PT4> const PointerUnion4 & llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::operator= (const PT4 & RHS) inline
Definition at line 443 of file PointerUnion.h.
References PointerUnion4().
operator=() [5/5]
template<typename PT1, typename PT2, typename PT3, typename PT4> const PointerUnion4 & llvm::PointerUnion4< PT1, PT2, PT3, PT4 >::operator= (std::nullptr_t) inline
Assignment from nullptr which just clears the union.
Definition at line 424 of file PointerUnion.h.
References PointerUnion4().
The documentation for this class was generated from the following file:
PointerUnion.h