LLVM: llvm::DIHeaderFieldIterator Class Reference
LLVM API Documentation
llvm::DIHeaderFieldIterator Class Reference
#include <DebugInfo.h>
Public Member Functions
DIHeaderFieldIterator ()
DIHeaderFieldIterator (StringRef Header)
StringRef operator* () const
const StringRef * operator-> () const
DIHeaderFieldIterator & operator++ ()
DIHeaderFieldIterator operator++ (int)
bool operator== (const DIHeaderFieldIterator &X) const
bool operator!= (const DIHeaderFieldIterator &X) const
StringRef getHeader () const
StringRef getCurrent () const
StringRef getPrefix () const
StringRef getSuffix () const
Detailed Description
Definition at line 61 of file DebugInfo.h.
Constructor & Destructor Documentation
DIHeaderFieldIterator() [1/2]
llvm::DIHeaderFieldIterator::DIHeaderFieldIterator () inline
Definition at line 68 of file DebugInfo.h.
Referenced by operator!=(), operator++(), operator++(), and operator==().
DIHeaderFieldIterator() [2/2]
llvm::DIHeaderFieldIterator::DIHeaderFieldIterator (StringRef Header) inline
Definition at line 69 of file DebugInfo.h.
Member Function Documentation
getCurrent()
StringRef llvm::DIHeaderFieldIterator::getCurrent () const inline
Definition at line 90 of file DebugInfo.h.
getHeader()
StringRef llvm::DIHeaderFieldIterator::getHeader () const inline
Definition at line 89 of file DebugInfo.h.
getPrefix()
StringRef llvm::DIHeaderFieldIterator::getPrefix () const inline
Definition at line 91 of file DebugInfo.h.
getSuffix()
StringRef llvm::DIHeaderFieldIterator::getSuffix () const inline
Definition at line 96 of file DebugInfo.h.
References llvm::StringRef::npos.
operator!=()
bool llvm::DIHeaderFieldIterator::operator!= (const DIHeaderFieldIterator & X) const inline
Definition at line 85 of file DebugInfo.h.
References DIHeaderFieldIterator(), and llvm::X.
operator*()
StringRef llvm::DIHeaderFieldIterator::operator* () const inline
Definition at line 71 of file DebugInfo.h.
operator++() [1/2]
DIHeaderFieldIterator & llvm::DIHeaderFieldIterator::operator++ () inline
Definition at line 73 of file DebugInfo.h.
References DIHeaderFieldIterator().
operator++() [2/2]
DIHeaderFieldIterator llvm::DIHeaderFieldIterator::operator++ (int) inline
Definition at line 77 of file DebugInfo.h.
References DIHeaderFieldIterator(), and llvm::X.
operator->()
const StringRef * llvm::DIHeaderFieldIterator::operator-> () const inline
Definition at line 72 of file DebugInfo.h.
operator==()
bool llvm::DIHeaderFieldIterator::operator== (const DIHeaderFieldIterator & X) const inline
Definition at line 82 of file DebugInfo.h.
References DIHeaderFieldIterator(), and llvm::X.
The documentation for this class was generated from the following file:
DebugInfo.h