LLVM: llvm::LiveStacks Class Reference
LLVM API Documentation
llvm::LiveStacks Class Reference
#include <LiveStackAnalysis.h>
Public Types
typedef SS2IntervalMap::iterator iterator
typedef SS2IntervalMap::const_iterator const_iterator
Public Member Functions
LiveStacks ()
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
unsigned getNumIntervals () const
LiveInterval & getOrCreateInterval (int Slot, const TargetRegisterClass *RC)
LiveInterval & getInterval (int Slot)
const LiveInterval & getInterval (int Slot) const
bool hasInterval (int Slot) const
const TargetRegisterClass * getIntervalRegClass (int Slot) const
VNInfo::Allocator & getVNInfoAllocator ()
void getAnalysisUsage (AnalysisUsage &AU) const override
void releaseMemory () override
bool runOnMachineFunction (MachineFunction &) override
runOnMachineFunction - pass entry point
void print (raw_ostream &O, const Module *=nullptr) const override
print - Implement the dump method.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 27 of file LiveStackAnalysis.h.
Member Typedef Documentation
const_iterator
typedef SS2IntervalMap::const_iterator llvm::LiveStacks::const_iterator
Definition at line 49 of file LiveStackAnalysis.h.
iterator
typedef SS2IntervalMap::iterator llvm::LiveStacks::iterator
Definition at line 48 of file LiveStackAnalysis.h.
Constructor & Destructor Documentation
LiveStacks()
llvm::LiveStacks::LiveStacks () inline
Definition at line 44 of file LiveStackAnalysis.h.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::initializeLiveStacksPass(), and llvm::MachineFunctionPass::MachineFunctionPass().
Referenced by getAnalysisUsage().
Member Function Documentation
begin() [1/2]
iterator llvm::LiveStacks::begin () inline
Definition at line 52 of file LiveStackAnalysis.h.
begin() [2/2]
const_iterator llvm::LiveStacks::begin () const inline
Definition at line 50 of file LiveStackAnalysis.h.
Referenced by print().
end() [1/2]
iterator llvm::LiveStacks::end () inline
Definition at line 53 of file LiveStackAnalysis.h.
end() [2/2]
const_iterator llvm::LiveStacks::end () const inline
Definition at line 51 of file LiveStackAnalysis.h.
Referenced by print().
getAnalysisUsage()
void LiveStacks::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 38 of file LiveStackAnalysis.cpp.
References getAnalysisUsage(), llvm::MachineFunctionPass::getAnalysisUsage(), and LiveStacks().
Referenced by getAnalysisUsage().
getInterval() [1/2]
LiveInterval & llvm::LiveStacks::getInterval (int Slot) inline
Definition at line 59 of file LiveStackAnalysis.h.
References I.
getInterval() [2/2]
const LiveInterval & llvm::LiveStacks::getInterval (int Slot) const inline
Definition at line 66 of file LiveStackAnalysis.h.
References I.
getIntervalRegClass()
const TargetRegisterClass * llvm::LiveStacks::getIntervalRegClass (int Slot) const inline
Definition at line 77 of file LiveStackAnalysis.h.
References I.
Referenced by print().
getNumIntervals()
unsigned llvm::LiveStacks::getNumIntervals () const inline
Definition at line 55 of file LiveStackAnalysis.h.
getOrCreateInterval()
LiveInterval & LiveStacks::getOrCreateInterval (int Slot, const TargetRegisterClass * RC)
Definition at line 60 of file LiveStackAnalysis.cpp.
References I, and llvm::TargetRegisterInfo::index2StackSlot().
getVNInfoAllocator()
VNInfo::Allocator & llvm::LiveStacks::getVNInfoAllocator () inline
Definition at line 86 of file LiveStackAnalysis.h.
hasInterval()
bool llvm::LiveStacks::hasInterval (int Slot) const inline
Definition at line 73 of file LiveStackAnalysis.h.
print()
void LiveStacks::print (raw_ostream & O, const Module * = nullptr) const override virtual
print - Implement the dump method.
Reimplemented from llvm::Pass.
Definition at line 76 of file LiveStackAnalysis.cpp.
References begin(), end(), getIntervalRegClass(), and I.
releaseMemory()
void LiveStacks::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 45 of file LiveStackAnalysis.cpp.
runOnMachineFunction()
bool LiveStacks::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - pass entry point
Implements llvm::MachineFunctionPass.
Definition at line 52 of file LiveStackAnalysis.cpp.
References llvm::TargetSubtargetInfo::getRegisterInfo(), and llvm::MachineFunction::getSubtarget().
Member Data Documentation
ID
char LiveStacks::ID = 0 static
Definition at line 43 of file LiveStackAnalysis.h.
Referenced by LiveStacks().
The documentation for this class was generated from the following files:
LiveStackAnalysis.h
LiveStackAnalysis.cpp