LLVM: llvm::IRBuilderBase::InsertPointGuard Class Reference
LLVM API Documentation
llvm::IRBuilderBase::InsertPointGuard Class Reference
#include <IRBuilder.h>
Public Member Functions
InsertPointGuard (IRBuilderBase &B)
~InsertPointGuard ()
Detailed Description
Definition at line 197 of file IRBuilder.h.
Constructor & Destructor Documentation
InsertPointGuard()
llvm::IRBuilderBase::InsertPointGuard::InsertPointGuard (IRBuilderBase & B) inline
Definition at line 207 of file IRBuilder.h.
References llvm::IRBuilderBase::getCurrentDebugLocation(), llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::GetInsertPoint(), and llvm::IRBuilderBase::IRBuilderBase().
~InsertPointGuard()
llvm::IRBuilderBase::InsertPointGuard::~InsertPointGuard () inline
Definition at line 211 of file IRBuilder.h.
The documentation for this class was generated from the following file:
IRBuilder.h