LLVM: llvm::OutputBuffer Class Reference
LLVM API Documentation
llvm::OutputBuffer Class Reference
#include <OutputBuffer.h>
Public Member Functions
OutputBuffer (std::vector< unsigned char > &Out, bool is64bit, bool le)
void align (unsigned Boundary)
void outbyte (unsigned char X)
void outhalf (unsigned short X)
void outword (unsigned X)
void outxword (uint64_t X)
void outaddr32 (unsigned X)
void outaddr64 (uint64_t X)
void outaddr (uint64_t X)
void outstring (const std::string &S, unsigned Length)
void fixhalf (unsigned short X, unsigned Offset)
void fixword (unsigned X, unsigned Offset)
void fixxword (uint64_t X, unsigned Offset)
void fixaddr (uint64_t X, unsigned Offset)
unsigned char & operator[] (unsigned Index)
const unsigned char & operator[] (unsigned Index) const
Detailed Description
Definition at line 23 of file OutputBuffer.h.
Constructor & Destructor Documentation
OutputBuffer()
llvm::OutputBuffer::OutputBuffer (std::vector< unsigned char > & Out, bool is64bit, bool le) inline
Definition at line 31 of file OutputBuffer.h.
Member Function Documentation
align()
void llvm::OutputBuffer::align (unsigned Boundary) inline
Definition at line 37 of file OutputBuffer.h.
fixaddr()
void llvm::OutputBuffer::fixaddr (uint64_t X, unsigned Offset) inline
Definition at line 149 of file OutputBuffer.h.
References fixword(), fixxword(), and llvm::X.
fixhalf()
void llvm::OutputBuffer::fixhalf (unsigned short X, unsigned Offset) inline
Definition at line 126 of file OutputBuffer.h.
References P, and llvm::X.
fixword()
void llvm::OutputBuffer::fixword (unsigned X, unsigned Offset) inline
Definition at line 131 of file OutputBuffer.h.
References P, and llvm::X.
Referenced by fixaddr().
fixxword()
void llvm::OutputBuffer::fixxword (uint64_t X, unsigned Offset) inline
Definition at line 138 of file OutputBuffer.h.
References P, and llvm::X.
Referenced by fixaddr().
operator[]() [1/2]
unsigned char & llvm::OutputBuffer::operator[] (unsigned Index) inline
Definition at line 156 of file OutputBuffer.h.
operator[]() [2/2]
const unsigned char & llvm::OutputBuffer::operator[] (unsigned Index) const inline
Definition at line 159 of file OutputBuffer.h.
outaddr()
void llvm::OutputBuffer::outaddr (uint64_t X) inline
Definition at line 104 of file OutputBuffer.h.
References outword(), outxword(), and llvm::X.
outaddr32()
void llvm::OutputBuffer::outaddr32 (unsigned X) inline
Definition at line 98 of file OutputBuffer.h.
References outword(), and llvm::X.
outaddr64()
void llvm::OutputBuffer::outaddr64 (uint64_t X) inline
Definition at line 101 of file OutputBuffer.h.
References outxword(), and llvm::X.
outbyte()
void llvm::OutputBuffer::outbyte (unsigned char X) inline
Definition at line 52 of file OutputBuffer.h.
References llvm::X.
Referenced by outstring().
outhalf()
void llvm::OutputBuffer::outhalf (unsigned short X) inline
Definition at line 55 of file OutputBuffer.h.
References llvm::X.
outstring()
void llvm::OutputBuffer::outstring (const std::string & S, unsigned Length) inline
Definition at line 110 of file OutputBuffer.h.
References outbyte().
outword()
void llvm::OutputBuffer::outword (unsigned X) inline
Definition at line 64 of file OutputBuffer.h.
References llvm::X.
Referenced by outaddr(), and outaddr32().
outxword()
void llvm::OutputBuffer::outxword (uint64_t X) inline
Definition at line 77 of file OutputBuffer.h.
References llvm::X.
Referenced by outaddr(), and outaddr64().
The documentation for this class was generated from the following file:
OutputBuffer.h