LLVM: llvm::LazyValueInfo Class Reference
LLVM API Documentation
llvm::LazyValueInfo Class Reference
This pass computes, caches, and vends lazy value constraint information.
#include <LazyValueInfo.h>
Public Types
enum Tristate { Unknown = -1 , False = 0 , True = 1 }
This is used to return true/false/dunno results.
Public Member Functions
LazyValueInfo ()
~LazyValueInfo ()
Tristate getPredicateOnEdge (unsigned Pred, Value *V, Constant *C, BasicBlock *FromBB, BasicBlock *ToBB, Instruction *CxtI=nullptr)
Tristate getPredicateAt (unsigned Pred, Value *V, Constant *C, Instruction *CxtI)
Constant * getConstant (Value *V, BasicBlock *BB, Instruction *CxtI=nullptr)
Constant * getConstantOnEdge (Value *V, BasicBlock *FromBB, BasicBlock *ToBB, Instruction *CxtI=nullptr)
void threadEdge (BasicBlock *PredBB, BasicBlock *OldSucc, BasicBlock *NewSucc)
void eraseBlock (BasicBlock *BB)
Inform the analysis cache that we have erased a block.
void getAnalysisUsage (AnalysisUsage &AU) const override
void releaseMemory () override
bool runOnFunction (Function &F) override
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
This pass computes, caches, and vends lazy value constraint information.
Definition at line 30 of file LazyValueInfo.h.
Member Enumeration Documentation
Tristate
enum llvm::LazyValueInfo::Tristate
This is used to return true/false/dunno results.
Enumerator
Unknown
False
True
Definition at line 46 of file LazyValueInfo.h.
Constructor & Destructor Documentation
LazyValueInfo()
llvm::LazyValueInfo::LazyValueInfo () inline
Definition at line 40 of file LazyValueInfo.h.
References llvm::FunctionPass::FunctionPass(), llvm::PassRegistry::getPassRegistry(), ID, and llvm::initializeLazyValueInfoPass().
~LazyValueInfo()
llvm::LazyValueInfo::~LazyValueInfo () inline
Definition at line 43 of file LazyValueInfo.h.
Member Function Documentation
eraseBlock()
void LazyValueInfo::eraseBlock (BasicBlock * BB)
Inform the analysis cache that we have erased a block.
Definition at line 1273 of file LazyValueInfo.cpp.
References getCache().
getAnalysisUsage()
void LazyValueInfo::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 1133 of file LazyValueInfo.cpp.
References llvm::AnalysisUsage::addRequired(), and llvm::AnalysisUsage::setPreservesAll().
getConstant()
Constant * LazyValueInfo::getConstant (Value * V, BasicBlock * BB, Instruction * CxtI = nullptr)
Determine whether the specified value is known to be a constant at the end of the specified block. Return null if not.
Definition at line 1147 of file LazyValueInfo.cpp.
References llvm::ConstantInt::get(), getCache(), and llvm::ConstantRange::getSingleElement().
getConstantOnEdge()
Constant * LazyValueInfo::getConstantOnEdge (Value * V, BasicBlock * FromBB, BasicBlock * ToBB, Instruction * CxtI = nullptr)
Determine whether the specified value is known to be a constant on the specified edge. Return null if not.
Definition at line 1164 of file LazyValueInfo.cpp.
References llvm::ConstantInt::get(), getCache(), and llvm::ConstantRange::getSingleElement().
getPredicateAt()
LazyValueInfo::Tristate LazyValueInfo::getPredicateAt (unsigned Pred, Value * V, Constant * C, Instruction * CxtI)
Determine whether the specified value comparison with a constant is known to be true or false at the specified instruction (from an assume intrinsic). Pred is a CmpInst predicate.
Definition at line 1260 of file LazyValueInfo.cpp.
References getCache(), and getPredicateResult().
getPredicateOnEdge()
LazyValueInfo::Tristate LazyValueInfo::getPredicateOnEdge (unsigned Pred, Value * V, Constant * C, BasicBlock * FromBB, BasicBlock * ToBB, Instruction * CxtI = nullptr)
Determine whether the specified value comparison with a constant is known to be true or false on the specified CFG edge. Pred is a CmpInst predicate.
Definition at line 1250 of file LazyValueInfo.cpp.
References getCache(), and getPredicateResult().
releaseMemory()
void LazyValueInfo::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 1139 of file LazyValueInfo.cpp.
References getCache().
runOnFunction()
bool LazyValueInfo::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 1114 of file LazyValueInfo.cpp.
References F, llvm::Pass::getAnalysis(), llvm::Pass::getAnalysisIfAvailable(), getCache(), llvm::DataLayoutPass::getDataLayout(), and llvm::DominatorTreeWrapperPass::getDomTree().
threadEdge()
void LazyValueInfo::threadEdge (BasicBlock * PredBB, BasicBlock * OldSucc, BasicBlock * NewSucc)
Inform the analysis cache that we have threaded an edge from PredBB to OldSucc to be from PredBB to NewSucc instead.
Definition at line 1267 of file LazyValueInfo.cpp.
References getCache().
Member Data Documentation
ID
char LazyValueInfo::ID = 0 static
Definition at line 39 of file LazyValueInfo.h.
Referenced by LazyValueInfo().
The documentation for this class was generated from the following files:
LazyValueInfo.h
LazyValueInfo.cpp