LLVM: llvm::FoldingSetImpl Class Reference
LLVM API Documentation
llvm::FoldingSetImpl Class Reference abstract
#include <FoldingSet.h>
Classes
class Node
Public Member Functions
FoldingSetImpl (unsigned Log2InitSize=6)
virtual ~FoldingSetImpl ()
void clear ()
clear - Remove all nodes from the folding set.
bool RemoveNode (Node *N)
Node * GetOrInsertNode (Node *N)
Node * FindNodeOrInsertPos (const FoldingSetNodeID &ID, void *&InsertPos)
void InsertNode (Node *N, void *InsertPos)
void InsertNode (Node *N)
unsigned size () const
size - Returns the number of nodes in the folding set.
bool empty () const
empty - Returns true if there are no nodes in the folding set.
Protected Member Functions
virtual void GetNodeProfile (Node *N, FoldingSetNodeID &ID) const =0
virtual bool NodeEquals (Node *N, const FoldingSetNodeID &ID, unsigned IDHash, FoldingSetNodeID &TempID) const =0
virtual unsigned ComputeNodeHash (Node *N, FoldingSetNodeID &TempID) const =0
Protected Attributes
void ** Buckets
unsigned NumBuckets
unsigned NumNodes
Detailed Description
FoldingSetImpl - Implements the folding set functionality. The main structure is an array of buckets. Each bucket is indexed by the hash of the nodes it contains. The bucket itself points to the nodes contained in the bucket via a singly linked list. The last node in the list points back to the bucket to facilitate node removal.
Definition at line 111 of file FoldingSet.h.
Constructor & Destructor Documentation
FoldingSetImpl()
FoldingSetImpl::FoldingSetImpl (unsigned Log2InitSize = 6) explicit
Definition at line 225 of file FoldingSet.cpp.
References AllocateBuckets(), Buckets, NumBuckets, and NumNodes.
Referenced by llvm::ContextualFoldingSet< T, Ctx >::ContextualFoldingSet(), and llvm::FoldingSet< ListTy >::FoldingSet().
~FoldingSetImpl()
FoldingSetImpl::~FoldingSetImpl () virtual
Definition at line 232 of file FoldingSet.cpp.
References Buckets.
Member Function Documentation
clear()
void FoldingSetImpl::clear ()
clear - Remove all nodes from the folding set.
Definition at line 235 of file FoldingSet.cpp.
References Buckets, NumBuckets, and NumNodes.
ComputeNodeHash()
virtual unsigned llvm::FoldingSetImpl::ComputeNodeHash (Node * N, FoldingSetNodeID & TempID) const protected pure virtual
ComputeNodeHash - Instantiations of the FoldingSet template implement this function to compute a hash value for the given node.
References N.
Referenced by InsertNode().
empty()
bool llvm::FoldingSetImpl::empty () const inline
empty - Returns true if there are no nodes in the folding set.
Definition at line 181 of file FoldingSet.h.
References NumNodes.
FindNodeOrInsertPos()
FoldingSetImpl::Node * FoldingSetImpl::FindNodeOrInsertPos (const FoldingSetNodeID & ID, void *& InsertPos)
FindNodeOrInsertPos - Look up the node specified by ID. If it exists, return it. If not, return the insertion token that will make insertion faster.
Definition at line 282 of file FoldingSet.cpp.
References Buckets, llvm::FoldingSetNodeID::clear(), GetBucketFor(), GetNextPtr(), NodeEquals(), and NumBuckets.
Referenced by llvm::ContextualFoldingSet< T, Ctx >::FindNodeOrInsertPos(), llvm::FoldingSet< ListTy >::FindNodeOrInsertPos(), and GetOrInsertNode().
GetNodeProfile()
virtual void llvm::FoldingSetImpl::GetNodeProfile (Node * N, FoldingSetNodeID & ID) const protected pure virtual
GetNodeProfile - Instantiations of the FoldingSet template implement this function to gather data bits for the given node.
References N.
Referenced by GetOrInsertNode().
GetOrInsertNode()
FoldingSetImpl::Node * FoldingSetImpl::GetOrInsertNode (FoldingSetImpl::Node * N)
GetOrInsertNode - If there is an existing simple Node exactly equal to the specified node, return it. Otherwise, insert 'N' and return it instead.
GetOrInsertNode - If there is an existing simple Node exactly equal to the specified node, return it. Otherwise, insert 'N' and it instead.
Definition at line 377 of file FoldingSet.cpp.
References FindNodeOrInsertPos(), GetNodeProfile(), InsertNode(), and N.
Referenced by llvm::ContextualFoldingSet< T, Ctx >::GetOrInsertNode(), llvm::FoldingSet< ListTy >::GetOrInsertNode(), and InsertNode().
InsertNode() [1/2]
void llvm::FoldingSetImpl::InsertNode (Node * N) inline
InsertNode - Insert the specified node into the folding set, knowing that it is not already in the folding set.
Definition at line 171 of file FoldingSet.h.
References GetOrInsertNode(), and N.
InsertNode() [2/2]
void FoldingSetImpl::InsertNode (Node * N, void * InsertPos)
InsertNode - Insert the specified node into the folding set, knowing that it is not already in the folding set. InsertPos must be obtained from FindNodeOrInsertPos.
InsertNode - Insert the specified node into the folding set, knowing that it is not already in the map. InsertPos must be obtained from FindNodeOrInsertPos.
The insert position is actually a bucket pointer.
Definition at line 307 of file FoldingSet.cpp.
References Buckets, ComputeNodeHash(), GetBucketFor(), N, NumBuckets, and NumNodes.
Referenced by GetOrInsertNode().
NodeEquals()
virtual bool llvm::FoldingSetImpl::NodeEquals (Node * N, const FoldingSetNodeID & ID, unsigned IDHash, FoldingSetNodeID & TempID) const protected pure virtual
NodeEquals - Instantiations of the FoldingSet template implement this function to compare the given node with the given ID.
References N.
Referenced by FindNodeOrInsertPos().
RemoveNode()
bool FoldingSetImpl::RemoveNode (Node * N)
RemoveNode - Remove a node from the folding set, returning true if one was removed or false if the node was not in the folding set.
Definition at line 336 of file FoldingSet.cpp.
References GetBucketPtr(), GetNextPtr(), N, and NumNodes.
size()
unsigned llvm::FoldingSetImpl::size () const inline
size - Returns the number of nodes in the folding set.
Definition at line 178 of file FoldingSet.h.
References NumNodes.
Member Data Documentation
Buckets
void** llvm::FoldingSetImpl::Buckets protected
Buckets - Array of bucket chains.
Definition at line 115 of file FoldingSet.h.
Referenced by llvm::ContextualFoldingSet< T, Ctx >::begin(), llvm::ContextualFoldingSet< T, Ctx >::begin(), llvm::FoldingSet< ListTy >::begin(), llvm::FoldingSet< ListTy >::begin(), llvm::ContextualFoldingSet< T, Ctx >::bucket_begin(), llvm::FoldingSet< ListTy >::bucket_begin(), llvm::ContextualFoldingSet< T, Ctx >::bucket_end(), llvm::FoldingSet< ListTy >::bucket_end(), clear(), llvm::ContextualFoldingSet< T, Ctx >::end(), llvm::ContextualFoldingSet< T, Ctx >::end(), llvm::FoldingSet< ListTy >::end(), llvm::FoldingSet< ListTy >::end(), FindNodeOrInsertPos(), FoldingSetImpl(), InsertNode(), and ~FoldingSetImpl().
NumBuckets
unsigned llvm::FoldingSetImpl::NumBuckets protected
NumBuckets - Length of the Buckets array. Always a power of 2.
Definition at line 119 of file FoldingSet.h.
Referenced by llvm::ContextualFoldingSet< T, Ctx >::bucket_begin(), llvm::FoldingSet< ListTy >::bucket_begin(), llvm::ContextualFoldingSet< T, Ctx >::bucket_end(), llvm::FoldingSet< ListTy >::bucket_end(), clear(), llvm::ContextualFoldingSet< T, Ctx >::end(), llvm::ContextualFoldingSet< T, Ctx >::end(), llvm::FoldingSet< ListTy >::end(), llvm::FoldingSet< ListTy >::end(), FindNodeOrInsertPos(), FoldingSetImpl(), and InsertNode().
NumNodes
unsigned llvm::FoldingSetImpl::NumNodes protected
NumNodes - Number of nodes in the folding set. Growth occurs when NumNodes is greater than twice the number of buckets.
Definition at line 123 of file FoldingSet.h.
Referenced by clear(), empty(), FoldingSetImpl(), InsertNode(), RemoveNode(), and size().
The documentation for this class was generated from the following files:
FoldingSet.h
FoldingSet.cpp