LLVM: llvm::opt::ArgList Class Reference
LLVM API Documentation
llvm::opt::ArgList Class Reference abstract
#include <ArgList.h>
Public Types
typedef SmallVector< Arg *, 16 > arglist_type
typedef arglist_type::iterator iterator
typedef arglist_type::const_iterator const_iterator
typedef arglist_type::reverse_iterator reverse_iterator
typedef arglist_type::const_reverse_iterator const_reverse_iterator
Public Member Functions
Arg Access
void append (Arg *A)
append - Append A to the arg list.
arglist_type & getArgs ()
const arglist_type & getArgs () const
unsigned size () const
bool hasArgNoClaim (OptSpecifier Id) const
bool hasArg (OptSpecifier Id) const
bool hasArg (OptSpecifier Id0, OptSpecifier Id1) const
bool hasArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const
Arg * getLastArgNoClaim (OptSpecifier Id) const
Arg * getLastArgNoClaim (OptSpecifier Id0, OptSpecifier Id1) const
Arg * getLastArg (OptSpecifier Id) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5, OptSpecifier Id6) const
Arg * getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5, OptSpecifier Id6, OptSpecifier Id7) const
virtual const char * getArgString (unsigned Index) const =0
getArgString - Return the input argument string at Index.
virtual unsigned getNumInputArgStrings () const =0
Arg Iteration
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
arg_iterator filtered_begin (OptSpecifier Id0=0U, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
arg_iterator filtered_end () const
iterator_range< arg_iterator > filtered (OptSpecifier Id0=0U, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
Arg Removal
void eraseArg (OptSpecifier Id)
eraseArg - Remove any option matching Id.
Argument Lookup Utilities
StringRef getLastArgValue (OptSpecifier Id, StringRef Default="") const
getLastArgValue - Return the value of the last argument, or a default.
std::vector< std::string > getAllArgValues (OptSpecifier Id) const
Translation Utilities
bool hasFlag (OptSpecifier Pos, OptSpecifier Neg, bool Default=true) const
bool hasFlag (OptSpecifier Pos, OptSpecifier PosAlias, OptSpecifier Neg, bool Default=true) const
void AddLastArg (ArgStringList &Output, OptSpecifier Id0) const
AddLastArg - Render only the last argument match Id0, if present.
void AddLastArg (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1) const
void AddAllArgs (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
AddAllArgs - Render all arguments matching the given ids.
void AddAllArgValues (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
void AddAllArgsTranslated (ArgStringList &Output, OptSpecifier Id0, const char *Translation, bool Joined=false) const
void ClaimAllArgs (OptSpecifier Id0) const
void ClaimAllArgs () const
Arg Synthesis
virtual const char * MakeArgString (StringRef Str) const =0
const char * MakeArgString (const char *Str) const
const char * MakeArgString (std::string Str) const
const char * MakeArgString (const Twine &Str) const
const char * GetOrMakeJoinedArgString (unsigned Index, StringRef LHS, StringRef RHS) const
Create an arg string for (LHS + RHS), reusing the string at Index if possible.
Protected Member Functions
ArgList ()
virtual ~ArgList ()
Detailed Description
ArgList - Ordered collection of driver arguments.
The ArgList class manages a list of Arg instances as well as auxiliary data and convenience methods to allow Tools to quickly check for the presence of Arg instances for a particular Option and to iterate over groups of arguments.
Definition at line 92 of file ArgList.h.
Member Typedef Documentation
arglist_type
typedef SmallVector<Arg*, 16> llvm::opt::ArgList::arglist_type
Definition at line 98 of file ArgList.h.
const_iterator
typedef arglist_type::const_iterator llvm::opt::ArgList::const_iterator
Definition at line 100 of file ArgList.h.
const_reverse_iterator
typedef arglist_type::const_reverse_iterator llvm::opt::ArgList::const_reverse_iterator
Definition at line 102 of file ArgList.h.
iterator
typedef arglist_type::iterator llvm::opt::ArgList::iterator
Definition at line 99 of file ArgList.h.
reverse_iterator
typedef arglist_type::reverse_iterator llvm::opt::ArgList::reverse_iterator
Definition at line 101 of file ArgList.h.
Constructor & Destructor Documentation
ArgList()
llvm::opt::ArgList::ArgList () inline protected
Definition at line 111 of file ArgList.h.
~ArgList()
ArgList::~ArgList () protected virtual
Definition at line 36 of file ArgList.cpp.
Member Function Documentation
AddAllArgs()
void ArgList::AddAllArgs (ArgStringList & Output, OptSpecifier Id0, OptSpecifier Id1 = 0U, OptSpecifier Id2 = 0U) const
AddAllArgs - Render all arguments matching the given ids.
Definition at line 244 of file ArgList.cpp.
References llvm::opt::Arg::claim(), filtered(), and llvm::opt::Arg::render().
AddAllArgsTranslated()
void ArgList::AddAllArgsTranslated (ArgStringList & Output, OptSpecifier Id0, const char * Translation, bool Joined = false) const
AddAllArgsTranslated - Render all the arguments matching the given ids, but forced to separate args and using the provided name instead of the first option value.
Parameters
Joined - If true, render the argument as joined with the option specifier.
Definition at line 261 of file ArgList.cpp.
References llvm::opt::Arg::claim(), filtered(), llvm::opt::Arg::getValue(), MakeArgString(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
AddAllArgValues()
void ArgList::AddAllArgValues (ArgStringList & Output, OptSpecifier Id0, OptSpecifier Id1 = 0U, OptSpecifier Id2 = 0U) const
AddAllArgValues - Render the argument values of all arguments matching the given ids.
Definition at line 252 of file ArgList.cpp.
References llvm::opt::Arg::claim(), filtered(), llvm::opt::Arg::getNumValues(), llvm::opt::Arg::getValue(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by getAllArgValues().
AddLastArg() [1/2]
void ArgList::AddLastArg (ArgStringList & Output, OptSpecifier Id0) const
AddLastArg - Render only the last argument match Id0, if present.
Definition at line 229 of file ArgList.cpp.
References getLastArg().
AddLastArg() [2/2]
void ArgList::AddLastArg (ArgStringList & Output, OptSpecifier Id0, OptSpecifier Id1) const
Definition at line 236 of file ArgList.cpp.
References getLastArg().
append()
void ArgList::append (Arg * A)
append - Append A to the arg list.
Definition at line 39 of file ArgList.cpp.
Referenced by llvm::opt::DerivedArgList::AddFlagArg(), llvm::opt::DerivedArgList::AddJoinedArg(), llvm::opt::DerivedArgList::AddPositionalArg(), llvm::opt::DerivedArgList::AddSeparateArg(), and llvm::opt::OptTable::ParseArgs().
begin() [1/2]
iterator llvm::opt::ArgList::begin () inline
Definition at line 133 of file ArgList.h.
Referenced by ClaimAllArgs(), eraseArg(), getLastArg(), getLastArg(), getLastArg(), getLastArg(), getLastArg(), getLastArg(), getLastArg(), getLastArg(), and llvm::opt::InputArgList::~InputArgList().
begin() [2/2]
const_iterator llvm::opt::ArgList::begin () const inline
Definition at line 139 of file ArgList.h.
ClaimAllArgs() [1/2]
void ArgList::ClaimAllArgs () const
ClaimAllArgs - Claim all arguments.
Definition at line 282 of file ArgList.cpp.
References begin(), and end().
ClaimAllArgs() [2/2]
void ArgList::ClaimAllArgs (OptSpecifier Id0) const
ClaimAllArgs - Claim all arguments which match the given option id.
Definition at line 277 of file ArgList.cpp.
References llvm::opt::Arg::claim(), and filtered().
end() [1/2]
iterator llvm::opt::ArgList::end () inline
Definition at line 134 of file ArgList.h.
Referenced by ClaimAllArgs(), eraseArg(), getLastArg(), getLastArg(), getLastArg(), getLastArg(), getLastArg(), getLastArg(), getLastArg(), getLastArg(), and llvm::opt::InputArgList::~InputArgList().
end() [2/2]
const_iterator llvm::opt::ArgList::end () const inline
Definition at line 140 of file ArgList.h.
eraseArg()
void ArgList::eraseArg (OptSpecifier Id)
eraseArg - Remove any option matching Id.
Definition at line 43 of file ArgList.cpp.
References begin(), and end().
filtered()
iterator_range< arg_iterator > llvm::opt::ArgList::filtered (OptSpecifier Id0 = 0U, OptSpecifier Id1 = 0U, OptSpecifier Id2 = 0U) const inline
Definition at line 153 of file ArgList.h.
References filtered_begin(), filtered_end(), and llvm::make_range().
Referenced by AddAllArgs(), AddAllArgsTranslated(), AddAllArgValues(), and ClaimAllArgs().
filtered_begin()
arg_iterator llvm::opt::ArgList::filtered_begin (OptSpecifier Id0 = 0U, OptSpecifier Id1 = 0U, OptSpecifier Id2 = 0U) const inline
Definition at line 145 of file ArgList.h.
Referenced by filtered().
filtered_end()
arg_iterator llvm::opt::ArgList::filtered_end () const inline
Definition at line 149 of file ArgList.h.
Referenced by filtered().
getAllArgValues()
std::vector< std::string > ArgList::getAllArgValues (OptSpecifier Id) const
getAllArgValues - Get the values of all instances of the given argument as strings.
Definition at line 223 of file ArgList.cpp.
References AddAllArgValues(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
getArgs() [1/2]
arglist_type & llvm::opt::ArgList::getArgs () inline
Definition at line 124 of file ArgList.h.
getArgs() [2/2]
const arglist_type & llvm::opt::ArgList::getArgs () const inline
Definition at line 125 of file ArgList.h.
getArgString()
virtual const char * llvm::opt::ArgList::getArgString (unsigned Index) const pure virtual
getArgString - Return the input argument string at Index.
Implemented in llvm::opt::DerivedArgList, and llvm::opt::InputArgList.
Referenced by llvm::opt::Option::accept(), GetOrMakeJoinedArgString(), and llvm::opt::OptTable::ParseOneArg().
getLastArg() [1/8]
Arg * ArgList::getLastArg (OptSpecifier Id) const
Definition at line 66 of file ArgList.cpp.
References begin(), llvm::opt::Arg::claim(), and end().
Referenced by AddLastArg(), AddLastArg(), getLastArgValue(), hasArg(), hasArg(), hasArg(), hasFlag(), and hasFlag().
getLastArg() [2/8]
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1) const
Definition at line 78 of file ArgList.cpp.
References begin(), llvm::opt::Arg::claim(), and end().
getLastArg() [3/8]
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const
Definition at line 92 of file ArgList.cpp.
References begin(), llvm::opt::Arg::claim(), and end().
getLastArg() [4/8]
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3) const
Definition at line 107 of file ArgList.cpp.
References begin(), llvm::opt::Arg::claim(), and end().
getLastArg() [5/8]
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4) const
Definition at line 123 of file ArgList.cpp.
References begin(), llvm::opt::Arg::claim(), and end().
getLastArg() [6/8]
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5) const
Definition at line 141 of file ArgList.cpp.
References begin(), llvm::opt::Arg::claim(), and end().
getLastArg() [7/8]
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5, OptSpecifier Id6) const
Definition at line 160 of file ArgList.cpp.
References begin(), llvm::opt::Arg::claim(), and end().
getLastArg() [8/8]
Arg * ArgList::getLastArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2, OptSpecifier Id3, OptSpecifier Id4, OptSpecifier Id5, OptSpecifier Id6, OptSpecifier Id7) const
Definition at line 181 of file ArgList.cpp.
References begin(), llvm::opt::Arg::claim(), and end().
getLastArgNoClaim() [1/2]
Arg * ArgList::getLastArgNoClaim (OptSpecifier Id) const
getLastArg - Return the last argument matching Id, or null.
Claim Whether the argument should be claimed, if it exists.
Definition at line 49 of file ArgList.cpp.
References rbegin(), and rend().
Referenced by hasArgNoClaim().
getLastArgNoClaim() [2/2]
Arg * ArgList::getLastArgNoClaim (OptSpecifier Id0, OptSpecifier Id1) const
Definition at line 57 of file ArgList.cpp.
References rbegin(), and rend().
getLastArgValue()
StringRef ArgList::getLastArgValue (OptSpecifier Id, StringRef Default = "") const
getLastArgValue - Return the value of the last argument, or a default.
Definition at line 216 of file ArgList.cpp.
References Default, and getLastArg().
getNumInputArgStrings()
virtual unsigned llvm::opt::ArgList::getNumInputArgStrings () const pure virtual
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
Implemented in llvm::opt::DerivedArgList, and llvm::opt::InputArgList.
References Default.
Referenced by llvm::opt::Option::accept().
GetOrMakeJoinedArgString()
const char * ArgList::GetOrMakeJoinedArgString (unsigned Index, StringRef LHS, StringRef RHS) const
Create an arg string for (LHS + RHS), reusing the string at Index if possible.
Definition at line 293 of file ArgList.cpp.
References llvm::StringRef::data(), llvm::StringRef::endswith(), getArgString(), MakeArgString(), llvm::StringRef::size(), and llvm::StringRef::startswith().
Referenced by llvm::opt::Arg::render().
hasArg() [1/3]
bool llvm::opt::ArgList::hasArg (OptSpecifier Id) const inline
Definition at line 176 of file ArgList.h.
References getLastArg().
hasArg() [2/3]
bool llvm::opt::ArgList::hasArg (OptSpecifier Id0, OptSpecifier Id1) const inline
Definition at line 179 of file ArgList.h.
References getLastArg().
hasArg() [3/3]
bool llvm::opt::ArgList::hasArg (OptSpecifier Id0, OptSpecifier Id1, OptSpecifier Id2) const inline
Definition at line 182 of file ArgList.h.
References getLastArg().
hasArgNoClaim()
bool llvm::opt::ArgList::hasArgNoClaim (OptSpecifier Id) const inline
hasArg - Does the arg list contain any option matching Id.
Claim Whether the argument should be claimed, if it exists.
Definition at line 173 of file ArgList.h.
References getLastArgNoClaim().
hasFlag() [1/2]
bool ArgList::hasFlag (OptSpecifier Pos, OptSpecifier Neg, bool Default = true) const
hasFlag - Given an option Pos and its negative form Neg, return true if the option is present, false if the negation is present, and Default if neither option is given. If both the option and its negation are present, the last one wins.
Definition at line 203 of file ArgList.cpp.
References Default, and getLastArg().
hasFlag() [2/2]
bool ArgList::hasFlag (OptSpecifier Pos, OptSpecifier PosAlias, OptSpecifier Neg, bool Default = true) const
hasFlag - Given an option Pos, an alias PosAlias and its negative form Neg, return true if the option or its alias is present, false if the negation is present, and Default if none of the options are given. If multiple options are present, the last one wins.
Definition at line 209 of file ArgList.cpp.
References Default, and getLastArg().
MakeArgString() [1/4]
const char * llvm::opt::ArgList::MakeArgString (const char * Str) const inline
Definition at line 283 of file ArgList.h.
References MakeArgString().
MakeArgString() [2/4]
const char * ArgList::MakeArgString (const Twine & Str) const
Definition at line 288 of file ArgList.cpp.
MakeArgString() [3/4]
const char * llvm::opt::ArgList::MakeArgString (std::string Str) const inline
Definition at line 286 of file ArgList.h.
References MakeArgString().
MakeArgString() [4/4]
virtual const char * llvm::opt::ArgList::MakeArgString (StringRef Str) const pure virtual
MakeArgString - Construct a constant string pointer whose lifetime will match that of the ArgList.
Implemented in llvm::opt::DerivedArgList, and llvm::opt::InputArgList.
Referenced by llvm::opt::Option::accept(), AddAllArgsTranslated(), GetOrMakeJoinedArgString(), MakeArgString(), MakeArgString(), and llvm::opt::Arg::render().
rbegin() [1/2]
reverse_iterator llvm::opt::ArgList::rbegin () inline
Definition at line 136 of file ArgList.h.
Referenced by getLastArgNoClaim(), and getLastArgNoClaim().
rbegin() [2/2]
const_reverse_iterator llvm::opt::ArgList::rbegin () const inline
Definition at line 142 of file ArgList.h.
rend() [1/2]
reverse_iterator llvm::opt::ArgList::rend () inline
Definition at line 137 of file ArgList.h.
Referenced by getLastArgNoClaim(), and getLastArgNoClaim().
rend() [2/2]
const_reverse_iterator llvm::opt::ArgList::rend () const inline
Definition at line 143 of file ArgList.h.
size()
unsigned llvm::opt::ArgList::size () const inline
Definition at line 127 of file ArgList.h.
The documentation for this class was generated from the following files:
ArgList.h
ArgList.cpp