LLVM: llvm::GCOVFile Class Reference
LLVM API Documentation
llvm::GCOVFile Class Reference
#include <GCOV.h>
Public Member Functions
GCOVFile ()
bool readGCNO (GCOVBuffer &Buffer)
readGCNO - Read GCNO buffer.
bool readGCDA (GCOVBuffer &Buffer)
uint32_t getChecksum () const
void dump () const
dump - Dump GCOVFile content to dbgs() for debugging purposes.
void collectLineCounts (FileInfo &FI)
Detailed Description
GCOVFile - Collects coverage information for one pair of coverage file (.gcno and .gcda).
Definition at line 233 of file GCOV.h.
Constructor & Destructor Documentation
GCOVFile()
llvm::GCOVFile::GCOVFile () inline
Definition at line 235 of file GCOV.h.
Member Function Documentation
collectLineCounts()
void GCOVFile::collectLineCounts (FileInfo & FI)
collectLineCounts - Collect line counts. This must be used after reading .gcno and .gcda files.
Definition at line 101 of file GCOV.cpp.
References llvm::FileInfo::setProgramCount(), and llvm::FileInfo::setRunCount().
dump()
void GCOVFile::dump () const
dump - Dump GCOVFile content to dbgs() for debugging purposes.
Definition at line 94 of file GCOV.cpp.
getChecksum()
uint32_t llvm::GCOVFile::getChecksum () const inline
Definition at line 239 of file GCOV.h.
readGCDA()
bool GCOVFile::readGCDA (GCOVBuffer & Buffer)
readGCDA - Read GCDA buffer. It is required that readGCDA() can only be called after readGCNO().
Definition at line 49 of file GCOV.cpp.
References llvm::GCOVBuffer::advanceCursor(), llvm::errs(), llvm::GCOVBuffer::readFunctionTag(), readGCDA(), llvm::GCOVBuffer::readGCDAFormat(), llvm::GCOVBuffer::readGCOVVersion(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readObjectTag(), and llvm::GCOVBuffer::readProgramTag().
Referenced by readGCDA().
readGCNO()
bool GCOVFile::readGCNO (GCOVBuffer & Buffer)
readGCNO - Read GCNO buffer.
Definition at line 30 of file GCOV.cpp.
References llvm::make_unique(), llvm::GCOVBuffer::readFunctionTag(), llvm::GCOVBuffer::readGCNOFormat(), llvm::GCOVBuffer::readGCOVVersion(), and llvm::GCOVBuffer::readInt().
The documentation for this class was generated from the following files:
GCOV.h
GCOV.cpp