LLVM: llvm::InstrProfIterator Class Reference
LLVM API Documentation
llvm::InstrProfIterator Class Reference
A file format agnostic iterator over profiling data.
#include <InstrProfReader.h>
Public Member Functions
InstrProfIterator ()
InstrProfIterator (InstrProfReader *Reader)
InstrProfIterator & operator++ ()
bool operator== (const InstrProfIterator &RHS)
bool operator!= (const InstrProfIterator &RHS)
InstrProfRecord & operator* ()
InstrProfRecord * operator-> ()
Detailed Description
A file format agnostic iterator over profiling data.
Definition at line 43 of file InstrProfReader.h.
Constructor & Destructor Documentation
InstrProfIterator() [1/2]
llvm::InstrProfIterator::InstrProfIterator () inline
Definition at line 50 of file InstrProfReader.h.
Referenced by operator!=(), operator++(), and operator==().
InstrProfIterator() [2/2]
llvm::InstrProfIterator::InstrProfIterator (InstrProfReader * Reader) inline
Definition at line 51 of file InstrProfReader.h.
Member Function Documentation
operator!=()
bool llvm::InstrProfIterator::operator!= (const InstrProfIterator & RHS) inline
Definition at line 55 of file InstrProfReader.h.
References InstrProfIterator().
operator*()
InstrProfRecord & llvm::InstrProfIterator::operator* () inline
Definition at line 56 of file InstrProfReader.h.
operator++()
InstrProfIterator & llvm::InstrProfIterator::operator++ () inline
Definition at line 53 of file InstrProfReader.h.
References InstrProfIterator().
operator->()
InstrProfRecord * llvm::InstrProfIterator::operator-> () inline
Definition at line 57 of file InstrProfReader.h.
operator==()
bool llvm::InstrProfIterator::operator== (const InstrProfIterator & RHS) inline
Definition at line 54 of file InstrProfReader.h.
References InstrProfIterator().
The documentation for this class was generated from the following files:
InstrProfReader.h
InstrProfReader.cpp