LLVM: llvm::ConstMIBundleOperands Class Reference
LLVM API Documentation
llvm::ConstMIBundleOperands Class Reference
#include <MachineInstrBundle.h>
Public Member Functions
ConstMIBundleOperands (const MachineInstr *MI)
const MachineOperand & operator* () const
const MachineOperand * operator-> () const
Public Member Functions inherited from llvm::MachineOperandIteratorBase
bool isValid () const
isValid - Returns true until all the operands have been visited.
void operator++ ()
Preincrement. Move to the next operand.
unsigned getOperandNo () const
VirtRegInfo analyzeVirtReg (unsigned Reg, SmallVectorImpl< std::pair< MachineInstr *, unsigned > > *Ops=nullptr)
PhysRegInfo analyzePhysReg (unsigned Reg, const TargetRegisterInfo *TRI)
Additional Inherited Members
Protected Member Functions inherited from llvm::MachineOperandIteratorBase
MachineOperandIteratorBase (MachineInstr *MI, bool WholeBundle)
MachineOperand & deref () const
Detailed Description
ConstMIBundleOperands - Iterate over all operands in a const bundle of machine instructions.
Definition at line 242 of file MachineInstrBundle.h.
Constructor & Destructor Documentation
ConstMIBundleOperands()
llvm::ConstMIBundleOperands::ConstMIBundleOperands (const MachineInstr * MI) inline
Definition at line 244 of file MachineInstrBundle.h.
References llvm::MachineOperandIteratorBase::MachineOperandIteratorBase(), and true.
Member Function Documentation
operator*()
const MachineOperand & llvm::ConstMIBundleOperands::operator* () const inline
Definition at line 246 of file MachineInstrBundle.h.
References llvm::MachineOperandIteratorBase::deref().
operator->()
const MachineOperand * llvm::ConstMIBundleOperands::operator-> () const inline
Definition at line 247 of file MachineInstrBundle.h.
References llvm::MachineOperandIteratorBase::deref().
The documentation for this class was generated from the following file:
MachineInstrBundle.h