LLVM: llvm::SDValue Class Reference
LLVM API Documentation
llvm::SDValue Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
SDValue ()
SDValue (SDNode *node, unsigned resno)
unsigned getResNo () const
get the index which selects a specific result in the SDNode
SDNode * getNode () const
get the SDNode which holds the desired result
void setNode (SDNode *N)
set the SDNode
SDNode * operator-> () const
bool operator== (const SDValue &O) const
bool operator!= (const SDValue &O) const
bool operator< (const SDValue &O) const
LLVM_EXPLICIT operator bool () const
SDValue getValue (unsigned R) const
bool isOperandOf (SDNode *N) const
EVT getValueType () const
MVT getSimpleValueType () const
Return the simple ValueType of the referenced return value.
unsigned getValueSizeInBits () const
unsigned getScalarValueSizeInBits () const
unsigned getOpcode () const
unsigned getNumOperands () const
const SDValue & getOperand (unsigned i) const
uint64_t getConstantOperandVal (unsigned i) const
bool isTargetMemoryOpcode () const
bool isTargetOpcode () const
bool isMachineOpcode () const
unsigned getMachineOpcode () const
const DebugLoc getDebugLoc () const
void dump () const
void dumpr () const
bool reachesChainWithoutSideEffects (SDValue Dest, unsigned Depth=2) const
bool use_empty () const
bool hasOneUse () const
Friends
struct DenseMapInfo< SDValue >
Detailed Description
SDValue - Unlike LLVM values, Selection DAG nodes may return multiple values as the result of a computation. Many nodes return multiple values, from loads (which define a token and a return value) to ADDC (which returns a result and a carry value), to calls (which may return an arbitrary number of values).
As such, each use of a SelectionDAG computation must indicate the node that computes it as well as which return value to use from that node. This pair of information is represented with the SDValue value type.
Definition at line 119 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
SDValue() [1/2]
llvm::SDValue::SDValue () inline
Definition at line 125 of file SelectionDAGNodes.h.
Referenced by getOperand(), getValue(), operator!=(), operator<(), operator==(), and reachesChainWithoutSideEffects().
SDValue() [2/2]
llvm::SDValue::SDValue (SDNode * node, unsigned resno) inline
Definition at line 908 of file SelectionDAGNodes.h.
Member Function Documentation
dump()
void llvm::SDValue::dump () const inline
Definition at line 951 of file SelectionDAGNodes.h.
References llvm::DebugLoc::dump().
dumpr()
void llvm::SDValue::dumpr () const inline
Definition at line 954 of file SelectionDAGNodes.h.
getConstantOperandVal()
uint64_t llvm::SDValue::getConstantOperandVal (unsigned i) const inline
Definition at line 927 of file SelectionDAGNodes.h.
Referenced by checkBoolTestSetCCCombine(), CMPEQCombine(), FoldMaskAndShiftToExtract(), FoldMaskAndShiftToScale(), FoldMaskedShiftToScaledMask(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::InferPtrAlignment(), LowerAsSplatVectorLoad(), LowerFRAMEADDR(), LowerRETURNADDR(), OptimizeConditionalInDecrement(), and PeepholePPC64ZExtGather().
getDebugLoc()
const DebugLoc llvm::SDValue::getDebugLoc () const inline
Definition at line 948 of file SelectionDAGNodes.h.
getMachineOpcode()
unsigned llvm::SDValue::getMachineOpcode () const inline
Definition at line 939 of file SelectionDAGNodes.h.
Referenced by FoldOperand(), and PeepholePPC64ZExtGather().
getNode()
SDNode * llvm::SDValue::getNode () const inline
get the SDNode which holds the desired result
Definition at line 132 of file SelectionDAGNodes.h.
Referenced by AddCombineTo64bitMLAL(), AddCombineToVPADDL(), AddGlue(), buildFromShuffleMostly(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::BuildUDIV(), canChangeToInt(), CanFoldXORWithAllOnes(), ChangeVSETULTtoVSETULE(), checkBoolTestSetCCCombine(), llvm::checkForCycles(), checkHighLaneIndex(), checkV64LaneV128(), ChooseConstraint(), CombineBaseUpdate(), combineRedundantHalfShuffle(), combineSelectAndUse(), combineSelectAndUseCommutative(), CombineVLDDUP(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), llvm::SelectionDAG::computeKnownBits(), computeZeroableShuffleElements(), ConvertSelectToConcatVector(), EltsFromConsecutiveLoads(), EmitVectorComparison(), expandIndex(), llvm::TargetLowering::expandMUL(), ExpandPowI(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendUsesToFormExtLoad(), FoldOperand(), llvm::SelectionDAG::FoldSetCC(), llvm::PPC::get_VSPLTI_elt(), getAArch64Cmp(), getBuildPairElt(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getCopyToReg(), llvm::DOTGraphTraits< SelectionDAG * >::getEdgeAttributes(), llvm::SDNode::getGluedNode(), llvm::DenseMapInfo< SDValue >::getHashValue(), getINSERTPS(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), getNumOfConsecutiveZeros(), llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::getPostIndexedAddressParts(), llvm::ARMTargetLowering::getPreIndexedAddressParts(), llvm::PPCTargetLowering::getPreIndexedAddressParts(), getShuffleScalarElt(), llvm::simplify_type< const SDValue >::getSimplifiedValue(), llvm::simplify_type< SDValue >::getSimplifiedValue(), getTargetShuffleMask(), getTargetVShiftByConstNode(), getUsefulBits(), getUsefulBitsFromAndWithImmediate(), getUsefulBitsFromBFM(), getUsefulBitsFromOrWithShiftedReg(), getUsefulBitsFromUBFM(), llvm::SelectionDAGBuilder::getValueImpl(), getVShiftImm(), getVShiftImm(), getVZextMovL(), llvm::SDNode::hasPredecessorHelper(), llvm::SelectionDAG::InferPtrAlignment(), InsertDAGNode(), isBitfieldExtractOpFromAnd(), isBitfieldPositioningOp(), isBLACompatibleAddress(), isBSwapHWordElement(), isCalleeLoad(), llvm::SelectionDAG::isConsecutiveLoad(), isConsecutiveLSLoc(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), isFloatingPointZero(), isFloatingPointZero(), llvm::TargetLowering::isGAPlusOffset(), isHorizontalBinOp(), isIntS16Immediate(), isIntS16Immediate(), isLoadIncOrDecStore(), isNaturalMemoryOperand(), isX86LogicalCmp(), isZeroShuffle(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDC_ADDE_SUBC_SUBE(), LowerANY_EXTEND(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::PPCTargetLowering::LowerAsmOperandForConstraint(), llvm::SparcTargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), LowerATOMIC_STORE(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), LowerCTPOP(), lowerDSPIntr(), LowerExtendedLoad(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerF128Load(), LowerF128Store(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerINSERT_SUBVECTOR(), LowerINTRINSIC_W_CHAIN(), LowerINTRINSIC_WO_CHAIN(), LowerLOAD_SUB(), lowerMSABinaryBitImmIntr(), LowerMUL(), LowerMUL(), llvm::AMDGPUTargetLowering::LowerOperation(), llvm::ARMTargetLowering::LowerOperation(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::XCoreTargetLowering::LowerOperation(), llvm::TargetLowering::LowerOperationWrapper(), LowerREADCYCLECOUNTER(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerScalarVariableShift(), LowerShift(), llvm::MSP430TargetLowering::LowerShifts(), llvm::AMDGPUTargetLowering::LowerSTORE(), LowerVAARG(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_256(), LowerVECTOR_SHUFFLEv32i8(), LowerVECTOR_SHUFFLEv8i16(), LowerVectorAllZeroTest(), LowerVectorBroadcast(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), lowerVSELECTtoBLENDI(), LowerVSETCC(), LowerVSETCC(), LowerXALUO(), LowerZERO_EXTEND(), MayFoldIntoStore(), MayFoldLoad(), MoveBelowOrigChain(), NormalizeVectorShuffle(), PeepholePPC64ZExtGather(), PerformADDCombine(), PerformADDCombine(), PerformADDCombineWithOperands(), PerformADDCombineWithOperands(), performAddSubLongCombine(), PerformANDCombine(), PerformANDCombine(), PerformAndCombine(), PerformARMBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), performCONDCombine(), llvm::MipsSETargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), performExtendCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformInsertEltCombine(), performIntegerAbsCombine(), performIntegerAbsCombine(), PerformINTRINSIC_WO_CHAINCombine(), performIntToFpCombine(), PerformISDSETCCCombine(), performNEONPostLDSTCombine(), PerformORCombine(), PerformOrCombine(), performORCombine(), performORCombine(), performPostLD1Combine(), PerformSELECTCombine(), PerformSETCCCombine(), PerformSExtCombine(), PerformShuffleCombine(), PerformShuffleCombine256(), PerformSIGN_EXTEND_INREGCombine(), PerformSINT_TO_FPCombine(), PerformSTORECombine(), PerformSTORECombine(), PerformSUBCombine(), PerformVDIVCombine(), PerformVMOVDRRCombine(), PerformVMOVRRDCombine(), PerformXORCombine(), PerformXorCombine(), performXORCombine(), PerformZExtCombine(), PrepareCall(), llvm::SDNode::print(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), ReplaceINTRINSIC_W_CHAIN(), llvm::AMDGPUTargetLowering::ReplaceNodeResults(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), reservePreviousStackSlotForValue(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::SelectionDAGISel::SelectCodeCommon(), selectMADD(), selectMSUB(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), spillIncomingStatepointValue(), llvm::SelectionDAG::TransferDbgValues(), transformVSELECTtoBlendVECTOR_SHUFFLE(), TranslateX86CC(), tryCombineLongOpWithDup(), tryToFoldExtendOfConstant(), useDivRem(), useSinCos(), ValueHasExactlyOneBitSet(), and XFormVExtractWithShuffleIntoLoad().
getNumOperands()
unsigned llvm::SDValue::getNumOperands () const inline
Definition at line 921 of file SelectionDAGNodes.h.
Referenced by buildFromShuffleMostly(), llvm::InstrEmitter::EmitDbgValue(), llvm::SelectionDAG::getNode(), LowerAVXCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerCONCAT_VECTORS(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerShiftParts(), LowerVECTOR_SHUFFLE(), MoveBelowOrigChain(), partitionShuffleOfConcats(), PerformVECTOR_SHUFFLECombine(), reachesChainWithoutSideEffects(), and llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp().
getOpcode()
unsigned llvm::SDValue::getOpcode () const inline
Definition at line 915 of file SelectionDAGNodes.h.
Referenced by AddCombineToVPADDL(), adjustForTestUnderMask(), buildFromShuffleMostly(), CanFoldXORWithAllOnes(), checkBoolTestSetCCCombine(), checkHighLaneIndex(), CMPEQCombine(), combineRedundantDWordShuffle(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), CompactSwizzlableVector(), llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::PPCTargetLowering::computeKnownBitsForTargetNode(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::TargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::AMDGPUTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), computeZeroableShuffleElements(), ConvertSelectToConcatVector(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), createFPCmp(), EltsFromConsecutiveLoads(), EmitCMP(), emitComparison(), ExtractSubVector(), FindBaseOffset(), FoldMaskAndShiftToExtract(), FoldMaskAndShiftToScale(), FoldMaskedShiftToScaledMask(), getAArch64XALUOOp(), getARMIndexedAddressParts(), getAtomicLoadArithTargetConstant(), getBuildPairElt(), llvm::SelectionDAGBuilder::getControlRoot(), getGatherNode(), llvm::SelectionDAG::getLoad(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), GetNegatedExpression(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), getNumOfConsecutiveZeros(), getScalarMaskingNode(), llvm::BuildVectorSDNode::getSplatValue(), getTargetVShiftNode(), getTruncatedArgReg(), getVectorMaskingNode(), llvm::SelectionDAG::getVectorShuffle(), getVShiftImm(), getVShiftImm(), getVZextMovL(), InferPointerInfo(), InferPointerInfo(), InsertSubVector(), isAbsolute(), isADDADDMUL(), isAndOrOfSetCCs(), llvm::SelectionDAG::isBaseWithConstantOffset(), isBSwapHWordElement(), llvm::ISD::isBuildVectorOfConstantSDNodes(), llvm::SelectionDAG::isConsecutiveLoad(), isConsecutiveLSLoc(), llvm::BuildVectorSDNode::isConstant(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), isFloatingPointZero(), isFunctionGlobalAddress(), isHorizontalBinOp(), isHorizontalBinOp(), llvm::SelectionDAG::isKnownNeverZero(), isMemSrcFromString(), IsMulWideOperandDemotable(), isNegatibleForFree(), isSetCC(), isSetCCOrZExtSetCC(), isXor1OfSetCC(), isZeroShuffle(), llvm::AArch64TargetLowering::isZExtFree(), llvm::ARMTargetLowering::isZExtFree(), llvm::X86TargetLowering::isZExtFree(), llvm::XCoreTargetLowering::isZExtFree(), LookThroughSetCC(), Lower256IntArith(), Lower256IntVSETCC(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDC_ADDE_SUBC_SUBE(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), LowerAVXExtend(), LowerBuildVectorv4x32(), LowerCONCAT_VECTORS(), lowerDSPIntr(), LowerF128Load(), LowerF128Store(), LowerFABSorFNEG(), LowerFNEGorFABS(), lowerFP_TO_SINT_STORE(), llvm::AArch64TargetLowering::LowerOperation(), llvm::AMDGPUTargetLowering::LowerOperation(), llvm::ARMTargetLowering::LowerOperation(), llvm::HexagonTargetLowering::LowerOperation(), llvm::MipsSETargetLowering::LowerOperation(), llvm::MipsTargetLowering::LowerOperation(), llvm::MSP430TargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerOperation(), llvm::PPCTargetLowering::LowerOperation(), llvm::R600TargetLowering::LowerOperation(), llvm::SITargetLowering::LowerOperation(), llvm::SparcTargetLowering::LowerOperation(), llvm::SystemZTargetLowering::LowerOperation(), llvm::X86TargetLowering::LowerOperation(), llvm::XCoreTargetLowering::LowerOperation(), LowerScalarImmediateShift(), LowerScalarVariableShift(), llvm::MSP430TargetLowering::LowerSETCC(), LowerShift(), LowerShiftParts(), llvm::MSP430TargetLowering::LowerShifts(), LowerUMULO_SMULO(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLEv8i16(), LowerVectorAllZeroTest(), LowerVectorBroadcast(), LowerVectorFP_TO_INT(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), LowerVectorINT_TO_FP(), lowerVectorShuffle(), LowerXALUO(), LowerXOR(), matchAddSub(), MatchingStackOffset(), MatchingStackOffset(), MatchRotateHalf(), matchRotateSub(), NormalizeBuildVector(), OptimizeConditionalInDecrement(), PerformADDCombineWithOperands(), performAddSubLongCombine(), PerformANDCombine(), PerformAndCombine(), performANDCombine(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), performBRCONDCombine(), PerformBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), PerformCMOVCombine(), performCONDCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::SystemZTargetLowering::PerformDAGCombine(), PerformExtendCombine(), PerformFMACombine(), performIntegerAbsCombine(), performIntegerAbsCombine(), PerformISDSETCCCombine(), PerformMLOADCombine(), PerformORCombine(), PerformOrCombine(), performORCombine(), PerformSELECTCombine(), performSELECTCombine(), performSelectCombine(), PerformSETCCCombine(), PerformSExtCombine(), PerformShiftCombine(), PerformSHLCombine(), PerformShuffleCombine(), PerformShuffleCombine256(), PerformSIGN_EXTEND_INREGCombine(), PerformSINT_TO_FPCombine(), PerformSubCombine(), PerformTargetShuffleCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), PerformVMOVDRRCombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), performVSELECTCombine(), performVSelectCombine(), PerformVZEXT_MOVLCombine(), performVZEXTCombine(), PerformZExtCombine(), reachesChainWithoutSideEffects(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReorganizeVector(), replaceSplatVectorStore(), llvm::PPCTargetLowering::SelectAddressRegImm(), selectMADD(), selectMSUB(), llvm::X86TargetLowering::shouldReduceLoadWidth(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedConstant(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), transformVSELECTtoBlendVECTOR_SHUFFLE(), tryCombineCRC32(), tryCombineFixedPointConvert(), tryCombineToBSL(), tryLowerToSLI(), ValueHasExactlyOneBitSet(), WidenMaskArithmetic(), and XFormVExtractWithShuffleIntoLoad().
getOperand()
const SDValue & llvm::SDValue::getOperand (unsigned i) const inline
Definition at line 924 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand(), and SDValue().
Referenced by adjustForTestUnderMask(), llvm::X86TargetLowering::BuildFILD(), buildFromShuffleMostly(), CanFoldXORWithAllOnes(), checkBoolTestSetCCCombine(), checkHighLaneIndex(), combineRedundantDWordShuffle(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), CompactSwizzlableVector(), llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::PPCTargetLowering::computeKnownBitsForTargetNode(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::AMDGPUTargetLowering::ComputeNumSignBitsForTargetNode(), computeZeroableShuffleElements(), ConvertSelectToConcatVector(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), createCMovFP(), createFPCmp(), emitComparison(), FindBaseOffset(), FoldMaskAndShiftToExtract(), FoldMaskAndShiftToScale(), FoldMaskedShiftToScaledMask(), FoldOperand(), GenerateTBL(), getAArch64XALUOOp(), getAltivecCompareInfo(), getAtomicLoadArithTargetConstant(), getBuildPairElt(), getMOVHighToLow(), getMOVLowToHigh(), getMOVLP(), GetNegatedExpression(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), getShuffleScalarElt(), getTargetVShiftNode(), getTruncatedArgReg(), getUsefulBitsFromAndWithImmediate(), getUsefulBitsFromBFM(), getUsefulBitsFromOrWithShiftedReg(), getUsefulBitsFromUBFM(), getVShiftImm(), getVShiftImm(), getVZextMovL(), InferPointerInfo(), llvm::SelectionDAG::InferPtrAlignment(), isAbsolute(), isADDADDMUL(), isAndOrOfSetCCs(), llvm::SelectionDAG::isBaseWithConstantOffset(), isBitfieldExtractOpFromAnd(), isBitfieldPositioningOp(), isBSwapHWordElement(), llvm::SelectionDAG::isConsecutiveLoad(), isConsecutiveLSLoc(), isConstVecPow2(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), isFloatingPointZero(), isFloatingPointZero(), isHorizontalBinOp(), isHorizontalBinOp(), llvm::SelectionDAG::isKnownNeverZero(), isLoadIncOrDecStore(), isMemSrcFromString(), IsMulWideOperandDemotable(), isNegatibleForFree(), isSetCC(), isTruncWithZeroHighBitsInput(), isXor1OfSetCC(), isZeroShuffle(), LookThroughSetCC(), Lower256IntArith(), Lower256IntVSETCC(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDC_ADDE_SUBC_SUBE(), LowerADJUST_TRAMPOLINE(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), LowerAsSplatVectorLoad(), llvm::HexagonTargetLowering::LowerATOMIC_FENCE(), LowerATOMIC_FENCE(), LowerATOMIC_FENCE(), LowerAVXCONCAT_VECTORS(), LowerBITCAST(), LowerBITCAST(), llvm::MSP430TargetLowering::LowerBR_CC(), LowerBR_CC(), llvm::HexagonTargetLowering::LowerBR_JT(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), LowerBuildVectorv8i16(), LowerCMP_SWAP(), LowerCONCAT_VECTORS(), LowerCTLZ(), LowerCTLZ_ZERO_UNDEF(), LowerCTPOP(), LowerCTTZ(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerDYNAMIC_STACKALLOC(), llvm::HexagonTargetLowering::LowerEH_RETURN(), LowerEXTRACT_SUBVECTOR(), LowerEXTRACT_VECTOR_ELT(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerF128_FPEXTEND(), LowerF128_FPROUND(), llvm::SparcTargetLowering::LowerF128Op(), LowerF64Op(), LowerFABSorFNEG(), LowerFCOPYSIGN(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), LowerFGETSIGN(), LowerFNEGorFABS(), LowerFP_EXTEND(), LowerFP_TO_SINT(), lowerFP_TO_SINT_STORE(), LowerFP_TO_UINT(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), LowerFSINCOS(), LowerINSERT_VECTOR_ELT(), LowerINTRINSIC_W_CHAIN(), LowerINTRINSIC_WO_CHAIN(), llvm::AMDGPUTargetLowering::LowerIntrinsicIABS(), llvm::AMDGPUTargetLowering::LowerIntrinsicLRP(), LowerIntVSETCC_AVX512(), llvm::AMDGPUTargetLowering::LowerLOAD(), LowerMUL(), LowerMUL(), LowerMUL(), LowerMUL_LOHI(), llvm::R600TargetLowering::LowerOperation(), LowerPREFETCH(), LowerPREFETCH(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerReverse_VECTOR_SHUFFLEv16i8_v8i16(), LowerSCALAR_TO_VECTOR(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerSDIV(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::MSP430TargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerShift(), LowerShiftParts(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), LowerSINT_TO_FP(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP(), LowerUMULO_SMULO(), LowerVACOPY(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::MSP430TargetLowering::LowerVASTART(), LowerVASTART(), LowerVASTART(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLEv8i16(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorBroadcast(), LowerVectorFP_TO_INT(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), LowerVectorINT_TO_FP(), LowerVectorIntExtend(), lowerVectorShuffle(), lowerVectorShuffleAsBroadcast(), lowerVSELECTtoBLENDI(), LowerVSETCC(), LowerVSETCC(), LowerXOR(), LowerZERO_EXTEND(), matchAddSub(), MatchingStackOffset(), MatchingStackOffset(), matchIntegerMINMAX(), MatchRotateHalf(), matchRotateSub(), MoveBelowOrigChain(), NormalizeBuildVector(), NormalizeVectorShuffle(), OptimizeConditionalInDecrement(), partitionShuffleOfConcats(), PeepholePPC64ZExtGather(), PerformADDCombineWithOperands(), performAddSubLongCombine(), PerformAndCombine(), performANDCombine(), PerformBFICombine(), performBRCONDCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), PerformCMOVCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::SystemZTargetLowering::PerformDAGCombine(), PerformExtendCombine(), PerformFMACombine(), performIntegerAbsCombine(), performIntegerAbsCombine(), PerformINTRINSIC_WO_CHAINCombine(), PerformISDSETCCCombine(), PerformORCombine(), PerformOrCombine(), performORCombine(), PerformSELECTCombine(), performSELECTCombine(), performSelectCombine(), PerformSETCCCombine(), PerformSExtCombine(), PerformShiftCombine(), PerformSHLCombine(), PerformShuffleCombine(), PerformShuffleCombine256(), PerformSIGN_EXTEND_INREGCombine(), PerformSTORECombine(), PerformSubCombine(), PerformTargetShuffleCombine(), PerformVDIVCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), PerformVMOVDRRCombine(), PerformVMOVRRDCombine(), performVSELECTCombine(), performVSelectCombine(), PerformVZEXT_MOVLCombine(), performVZEXTCombine(), PerformZExtCombine(), reachesChainWithoutSideEffects(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReorganizeVector(), replaceSplatVectorStore(), llvm::X86TargetLowering::shouldReduceLoadWidth(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedConstant(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), transformVSELECTtoBlendVECTOR_SHUFFLE(), tryCombineCRC32(), tryCombineFixedPointConvert(), tryFormConcatFromShuffle(), tryLowerToSLI(), llvm::TargetLowering::verifyReturnAddressArgumentIsConstant(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), and XFormVExtractWithShuffleIntoLoad().
getResNo()
unsigned llvm::SDValue::getResNo () const inline
get the index which selects a specific result in the SDNode
Definition at line 129 of file SelectionDAGNodes.h.
Referenced by checkBoolTestSetCCCombine(), CombineBaseUpdate(), llvm::SelectionDAG::computeKnownBits(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::SelectionDAG::ComputeNumSignBits(), ExtendUsesToFormExtLoad(), getBuildPairElt(), llvm::DenseMapInfo< SDValue >::getHashValue(), isLoadIncOrDecStore(), isX86LogicalCmp(), PerformEXTRACT_VECTOR_ELTCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformSETCCCombine(), PerformSExtCombine(), PerformVMOVDRRCombine(), PerformZExtCombine(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), llvm::ResourcePriorityQueue::scheduledNode(), selectMADD(), selectMSUB(), and llvm::SelectionDAG::TransferDbgValues().
getScalarValueSizeInBits()
unsigned llvm::SDValue::getScalarValueSizeInBits () const inline
Definition at line 174 of file SelectionDAGNodes.h.
References llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), and getValueType().
getSimpleValueType()
MVT llvm::SDValue::getSimpleValueType () const inline
Return the simple ValueType of the referenced return value.
Definition at line 164 of file SelectionDAGNodes.h.
References llvm::EVT::getSimpleVT(), and getValueType().
Referenced by buildFromShuffleMostly(), ChangeVSETULTtoVSETULE(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), getGatherNode(), getMOVDDup(), getMOVHighToLow(), getMOVLowToHigh(), getMOVLP(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), getPrefetchNode(), getPSHUFB(), getScatterNode(), getTargetVShiftByConstNode(), getTargetVShiftNode(), getUnderlyingExtractedFromVec(), isHorizontalBinOp(), Lower256IntArith(), Lower256IntVSETCC(), LowerADD(), LowerAVXCONCAT_VECTORS(), LowerBITCAST(), LowerBuildVectorv4x32(), LowerCMP_SWAP(), LowerCONCAT_VECTORS(), LowerCTLZ(), LowerCTLZ_ZERO_UNDEF(), LowerCTTZ(), LowerExtendedLoad(), LowerEXTRACT_SUBVECTOR(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerFABSorFNEG(), LowerFCOPYSIGN(), LowerFGETSIGN(), LowerFP_EXTEND(), LowerINTRINSIC_WO_CHAIN(), LowerIntVSETCC_AVX512(), LowerMUL(), LowerSCALAR_TO_VECTOR(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerShift(), LowerShiftParts(), LowerSUB(), lowerV16F32VectorShuffle(), lowerV16I16VectorShuffle(), lowerV16I32VectorShuffle(), lowerV16I8VectorShuffle(), lowerV2F64VectorShuffle(), lowerV2I64VectorShuffle(), lowerV32I16VectorShuffle(), lowerV32I8VectorShuffle(), lowerV4F32VectorShuffle(), lowerV4F64VectorShuffle(), lowerV4I32VectorShuffle(), lowerV4I64VectorShuffle(), lowerV64I8VectorShuffle(), lowerV8F32VectorShuffle(), lowerV8F64VectorShuffle(), lowerV8I16BasicBlendVectorShuffle(), lowerV8I16VectorShuffle(), lowerV8I32VectorShuffle(), lowerV8I64VectorShuffle(), LowerVectorBroadcast(), LowerVectorIntExtend(), lowerVectorShuffle(), lowerVectorShuffleAsInsertPS(), lowerVSELECTtoBLENDI(), LowerVSETCC(), LowerZERO_EXTEND(), NarrowVectorLoadToElement(), NormalizeVectorShuffle(), llvm::R600TargetLowering::PerformDAGCombine(), PerformVCVTCombine(), PerformVDIVCombine(), performVZEXTCombine(), llvm::TargetLowering::SimplifySetCC(), and splitAndLowerVectorShuffle().
getValue()
SDValue llvm::SDValue::getValue (unsigned R) const inline
Definition at line 152 of file SelectionDAGNodes.h.
References SDValue().
Referenced by llvm::X86TargetLowering::BuildFILD(), emitComparison(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), ExpandBITCAST(), llvm::TargetLowering::expandMUL(), llvm::PPCTargetLowering::expandVSXStoreForLE(), GeneratePerfectShuffle(), getAArch64XALUOOp(), getBoundedStrlen(), getMemCmpLoad(), llvm::MipsTargetLowering::getOpndList(), getReadPerformanceCounter(), getReadTimeStampCounter(), GetTLSADDR(), isCalleeLoad(), LowerATOMIC_STORE(), llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), LowerCMP_SWAP(), LowerCTLZ(), LowerCTTZ(), LowerExtendedLoad(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), llvm::AMDGPUTargetLowering::LowerLOAD(), llvm::MipsTargetLowering::LowerOperationWrapper(), llvm::HexagonTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), LowerToTLSGeneralDynamicModel32(), LowerToTLSLocalDynamicModel(), LowerVAARG(), LowerVECTOR_SHUFFLE(), llvm::PPCTargetLowering::PerformDAGCombine(), performDivRemCombine(), PerformLOADCombine(), PerformMLOADCombine(), PerformSExtCombine(), PerformSINT_TO_FPCombine(), PerformSTORECombine(), PerformSTORECombine(), performSTORECombine(), PerformVMOVRRDCombine(), PerformZExtCombine(), PrepareCall(), PrepareTailCall(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), replaceSplatVectorStore(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::SelectionDAGBuilder::visitJumpTable().
getValueSizeInBits()
unsigned llvm::SDValue::getValueSizeInBits () const inline
getValueSizeInBits - Returns the size of the value in bits.
Definition at line 170 of file SelectionDAGNodes.h.
References llvm::EVT::getSizeInBits(), and getValueType().
Referenced by llvm::SelectionDAGISel::CheckAndMask(), llvm::SelectionDAGISel::CheckOrMask(), GetRegistersForValue(), isTruncateOf(), isTruncWithZeroHighBitsInput(), lowerFCOPYSIGN64(), lowerFP_TO_SINT_STORE(), PerformBTCombine(), ShrinkLoadReplaceStoreWithStore(), and llvm::TargetLowering::SimplifySetCC().
getValueType()
EVT llvm::SDValue::getValueType () const inline
getValueType - Return the ValueType of the referenced return value.
Definition at line 918 of file SelectionDAGNodes.h.
Referenced by AddCombineTo64bitMLAL(), AddCombineToVPADDL(), adjustForTestUnderMask(), llvm::TargetLowering::BuildExactSDIV(), llvm::X86TargetLowering::BuildFILD(), buildFromShuffleMostly(), BuildIntrinsicOp(), BuildIntrinsicOp(), BuildIntrinsicOp(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), CalculateTailCallArgDest(), canChangeToInt(), CMPEQCombine(), combineRedundantDWordShuffle(), CompactSwizzlableVector(), llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), countOperands(), createCMovFP(), createFPCmp(), createLoadLR(), createStoreLR(), emitCLC(), EmitCMP(), emitComparison(), emitMemMem(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrlen(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen(), EmitVectorComparison(), ExpandBITCAST(), expandExp(), expandExp2(), expandf64Toi32(), llvm::TargetLowering::expandFP_TO_SINT(), ExpandHorizontalBinOp(), expandLog(), expandLog10(), expandLog2(), expandPow(), ExpandPowI(), ExpandUnalignedLoad(), ExpandUnalignedStore(), llvm::PPCTargetLowering::expandVSXStoreForLE(), ExtendUsesToFormExtLoad(), Extract128BitVector(), Extract256BitVector(), ExtractSubVector(), llvm::SelectionDAG::ExtractVectorElements(), findChainOperand(), llvm::SelectionDAG::FoldSetCC(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), GeneratePerfectShuffle(), GenerateTBL(), getAArch64Cmp(), getAArch64XALUOOp(), getAbsolute(), llvm::SelectionDAG::getAnyExtendVectorInReg(), llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getAtomicCmpSwap(), llvm::SelectionDAG::getAtomicCmpSwap(), llvm::SelectionDAG::getBoolExtOrTrunc(), getBoundedStrlen(), getCopyFromParts(), getCopyFromPartsVector(), getCopyToParts(), getCopyToPartsVector(), llvm::DOTGraphTraits< SelectionDAG * >::getEdgeAttributes(), llvm::SelectionDAG::getExtLoad(), llvm::SelectionDAG::getExtLoad(), getFRAMEADDR(), getGatherNode(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedStore(), getLeftShift(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMaskedStore(), getMemBasePlusOffset(), llvm::SelectionDAG::getMemset(), GetNegatedExpression(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), getNumOperandsNoGlue(), llvm::AMDGPUTargetLowering::getRecipEstimate(), llvm::AMDGPUTargetLowering::getRsqrtEstimate(), getScalarMaskingNode(), getScalarValueSizeInBits(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSelectCC(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SelectionDAG::getShiftAmountOperand(), llvm::SelectionDAG::getSignExtendVectorInReg(), getSimpleValueType(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getStore(), getTargetShuffleMask(), llvm::SelectionDAG::getTruncStore(), getUsefulBits(), getValueSizeInBits(), getVectorMaskingNode(), llvm::SelectionDAG::getVectorShuffle(), getVShift(), getVZextMovL(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::SelectionDAG::getZeroExtendVectorInReg(), llvm::SelectionDAG::getZExtOrTrunc(), HandleMergeInputChains(), Insert128BitVector(), Insert256BitVector(), InsertSubVector(), isBitfieldPositioningOp(), isConditionalZeroOrAllOnes(), isConstVecPow2(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), isI24(), IsMulWideOperandDemotable(), isNegatibleForFree(), isTruncateOf(), isU24(), llvm::AArch64TargetLowering::isZExtFree(), llvm::AMDGPUTargetLowering::isZExtFree(), llvm::ARMTargetLowering::isZExtFree(), llvm::MSP430TargetLowering::isZExtFree(), llvm::TargetLoweringBase::isZExtFree(), llvm::X86TargetLowering::isZExtFree(), llvm::XCoreTargetLowering::isZExtFree(), llvm::SITargetLowering::legalizeTargetIndependentNode(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDC_ADDE_SUBC_SUBE(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::SparcTargetLowering::LowerAsmOperandForConstraint(), llvm::SystemZTargetLowering::LowerAsmOperandForConstraint(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), LowerAsSplatVectorLoad(), LowerBITCAST(), llvm::MSP430TargetLowering::LowerBR_CC(), LowerBR_CC(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::TargetLowering::LowerCallTo(), LowerCONCAT_VECTORS(), llvm::HexagonTargetLowering::LowerConstantPool(), LowerConstantPool(), LowerCTPOP(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), lowerDSPIntr(), LowerExtendedLoad(), LowerEXTRACT_VECTOR_ELT(), LowerF128_FPEXTEND(), LowerF128_FPROUND(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Compare(), LowerF128Load(), llvm::SparcTargetLowering::LowerF128Op(), LowerF128Store(), LowerF64Op(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), LowerFNEGorFABS(), llvm::SITargetLowering::LowerFormalArguments(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), LowerFSINCOS(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerINTRINSIC_W_CHAIN(), LowerINTRINSIC_WO_CHAIN(), llvm::AMDGPUTargetLowering::LowerIntrinsicIABS(), llvm::AMDGPUTargetLowering::LowerIntrinsicLRP(), LowerIntVSETCC_AVX512(), LowerLabelRef(), llvm::AMDGPUTargetLowering::LowerLOAD(), llvm::MipsTargetLowering::lowerLOAD(), LowerMUL(), LowerMUL(), LowerMUL_LOHI(), llvm::R600TargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), LowerReverse_VECTOR_SHUFFLEv16i8_v8i16(), LowerSCALAR_TO_VECTOR(), LowerScalarVariableShift(), LowerSDIV(), llvm::AMDGPUTargetLowering::LowerSDIVREM(), llvm::MSP430TargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), llvm::MSP430TargetLowering::LowerSETCC(), llvm::MSP430TargetLowering::LowerShifts(), llvm::MSP430TargetLowering::LowerSIGN_EXTEND(), LowerSINT_TO_FP(), LowerUDIV(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), LowerUINT_TO_FP(), LowerUMULO_SMULO(), LowerVAARG(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLEv16i8(), LowerVectorAllZeroTest(), LowerVectorBroadcast(), LowerVectorFP_TO_INT(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), LowerVectorINT_TO_FP(), LowerVSETCC(), LowerVSETCC(), LowerXALUO(), LowerXOR(), LowerZERO_EXTEND_AVX512(), llvm::SparcTargetLowering::makeHiLoPair(), llvm::TargetLowering::makeLibCall(), MatchingStackOffset(), MatchingStackOffset(), NarrowVector(), NarrowVector(), NormalizeBuildVector(), WidenVector::operator()(), OptimizeConditionalInDecrement(), partitionShuffleOfConcats(), PerformADDCombineWithOperands(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), performBRCONDCombine(), PerformCMOVCombine(), performConcatVectorsCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SystemZTargetLowering::PerformDAGCombine(), PerformExtendCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformINTRINSIC_WO_CHAINCombine(), PerformISDSETCCCombine(), PerformLOADCombine(), PerformMLOADCombine(), PerformMSTORECombine(), PerformOrCombine(), PerformSELECTCombine(), performSELECTCombine(), performSelectCombine(), performSetccAddFolding(), PerformSETCCCombine(), PerformSExtCombine(), PerformSHLCombine(), PerformShuffleCombine(), PerformSIGN_EXTEND_INREGCombine(), PerformSTORECombine(), PerformSTORECombine(), performSTORECombine(), PerformSubCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), performVSelectCombine(), PerformVZEXT_MOVLCombine(), PerformZExtCombine(), PrepareCall(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReorganizeVector(), ReplaceBITCASTResults(), llvm::R600TargetLowering::ReplaceNodeResults(), replaceSplatVectorStore(), reservePreviousStackSlotForValue(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), selectCCOpsAreFMaxCompatible(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedConstant(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), llvm::SelectionDAG::SignBitIsZero(), llvm::TargetLowering::SimplifyDemandedBits(), simplifyI24(), llvm::TargetLowering::SimplifySetCC(), simplifyShuffleOperandRecursively(), llvm::TargetLowering::softenSetCCOperands(), spillIncomingStatepointValue(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), TranslateX86CC(), tryCombineFixedPointConvert(), tryCombineLongOpWithDup(), tryFormConcatFromShuffle(), llvm::SelectionDAG::UnrollVectorOp(), ValueHasExactlyOneBitSet(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::SelectionDAGBuilder::visitSwitchCase(), WidenVector(), llvm::SparcTargetLowering::withTargetFlags(), and XFormVExtractWithShuffleIntoLoad().
hasOneUse()
bool llvm::SDValue::hasOneUse () const inline
hasOneUse - Return true if there is exactly one node using value ResNo of Node.
Definition at line 945 of file SelectionDAGNodes.h.
Referenced by combineX86ShufflesRecursively(), FoldMaskAndShiftToExtract(), FoldMaskAndShiftToScale(), FoldMaskedShiftToScaledMask(), getAtomicLoadArithTargetConstant(), GetNegatedExpression(), isADDADDMUL(), isAndOrOfSetCCs(), isCalleeLoad(), isNegatibleForFree(), isXor1OfSetCC(), LowerEXTRACT_VECTOR_ELT_SSE4(), llvm::MSP430TargetLowering::LowerSETCC(), LowerVectorBroadcast(), MayFoldIntoStore(), MayFoldLoad(), OptimizeConditionalInDecrement(), PerformBTCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::SystemZTargetLowering::PerformDAGCombine(), PerformEXTRACT_VECTOR_ELTCombine(), performIntToFpCombine(), PerformISDSETCCCombine(), PerformORCombine(), PerformOrCombine(), PerformSETCCCombine(), PerformShuffleCombine(), PerformSINT_TO_FPCombine(), PerformSTORECombine(), PerformTargetShuffleCombine(), PerformZExtCombine(), selectMADD(), selectMSUB(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), and XFormVExtractWithShuffleIntoLoad().
isMachineOpcode()
bool llvm::SDValue::isMachineOpcode () const inline
Definition at line 936 of file SelectionDAGNodes.h.
Referenced by FoldOperand(), and PeepholePPC64ZExtGather().
isOperandOf()
bool SDValue::isOperandOf (SDNode * N) const
isOperand - Return true if this node is an operand of N.
Definition at line 6376 of file SelectionDAG.cpp.
References N.
Referenced by isCalleeLoad().
isTargetMemoryOpcode()
bool llvm::SDValue::isTargetMemoryOpcode () const inline
Definition at line 933 of file SelectionDAGNodes.h.
isTargetOpcode()
bool llvm::SDValue::isTargetOpcode () const inline
Definition at line 930 of file SelectionDAGNodes.h.
operator bool()
LLVM_EXPLICIT llvm::SDValue::operator bool () const inline
Definition at line 148 of file SelectionDAGNodes.h.
References LLVM_EXPLICIT.
operator!=()
bool llvm::SDValue::operator!= (const SDValue & O) const inline
Definition at line 142 of file SelectionDAGNodes.h.
References operator==(), and SDValue().
operator->()
SDNode * llvm::SDValue::operator-> () const inline
Definition at line 137 of file SelectionDAGNodes.h.
operator<()
bool llvm::SDValue::operator< (const SDValue & O) const inline
Definition at line 145 of file SelectionDAGNodes.h.
References SDValue().
operator==()
bool llvm::SDValue::operator== (const SDValue & O) const inline
Definition at line 139 of file SelectionDAGNodes.h.
References SDValue().
Referenced by operator!=().
reachesChainWithoutSideEffects()
bool SDValue::reachesChainWithoutSideEffects (SDValue Dest, unsigned Depth = 2) const
reachesChainWithoutSideEffects - Return true if this operand (which must be a chain) reaches the specified operand without crossing any side-effecting instructions. In practice, this looks through token factors and non-volatile loads. In order to remain efficient, this only looks a couple of nodes in, it does not do an exhaustive search.
reachesChainWithoutSideEffects - Return true if this operand (which must be a chain) reaches the specified operand without crossing any side-effecting instructions on any chain path. In practice, this looks through token factors and non-volatile loads. In order to remain efficient, this only looks a couple of nodes in, it does not do an exhaustive search.
Definition at line 6395 of file SelectionDAG.cpp.
References llvm::dyn_cast(), getNumOperands(), getOpcode(), getOperand(), reachesChainWithoutSideEffects(), SDValue(), and llvm::ISD::TokenFactor.
Referenced by reachesChainWithoutSideEffects().
setNode()
void llvm::SDValue::setNode (SDNode * N) inline
set the SDNode
Definition at line 135 of file SelectionDAGNodes.h.
References N.
Referenced by PrepareCall().
use_empty()
bool llvm::SDValue::use_empty () const inline
use_empty - Return true if there are no nodes using value ResNo of Node.
Definition at line 942 of file SelectionDAGNodes.h.
Friends And Related Symbol Documentation
DenseMapInfo< SDValue >
friend struct DenseMapInfo< SDValue > friend
Definition at line 105 of file SelectionDAGNodes.h.
References N.
The documentation for this class was generated from the following files:
SelectionDAGNodes.h
SelectionDAG.cpp