LLVM: llvm::MCFragment Class Reference
LLVM API Documentation
llvm::MCFragment Class Reference
#include <MCAssembler.h>
Public Types
enum FragmentType {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Relaxable , FT_Org , FT_Dwarf , FT_DwarfFrame ,
FT_LEB
}
Public Member Functions
MCFragment ()
virtual ~MCFragment ()
FragmentType getKind () const
MCSectionData * getParent () const
void setParent (MCSectionData *Value)
MCSymbolData * getAtom () const
void setAtom (MCSymbolData *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
virtual bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
virtual bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
virtual void setAlignToBundleEnd (bool V)
virtual uint8_t getBundlePadding () const
Get the padding size that must be inserted before this fragment. Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
virtual void setBundlePadding (uint8_t N)
Set the padding size for this fragment. By default it's a no-op, and only some fragments have a meaningful implementation.
void dump ()
Public Member Functions inherited from llvm::ilist_node< MCFragment >
MCFragment * getPrevNode ()
Get the previous node, or 0 for the list head.
MCFragment * getNextNode ()
Get the next node, or 0 for the list tail.
Protected Member Functions
MCFragment (FragmentType _Kind, MCSectionData *_Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node< MCFragment >
ilist_node ()
Friends
class MCAsmLayout
Detailed Description
Definition at line 46 of file MCAssembler.h.
Member Enumeration Documentation
FragmentType
enum llvm::MCFragment::FragmentType
Enumerator
FT_Align
FT_Data
FT_CompactEncodedInst
FT_Fill
FT_Relaxable
FT_Org
FT_Dwarf
FT_DwarfFrame
FT_LEB
Definition at line 53 of file MCAssembler.h.
Constructor & Destructor Documentation
MCFragment() [1/2]
MCFragment::MCFragment (FragmentType _Kind, MCSectionData * _Parent = nullptr) protected
Definition at line 270 of file MCAssembler.cpp.
MCFragment() [2/2]
MCFragment::MCFragment ()
Definition at line 264 of file MCAssembler.cpp.
~MCFragment()
MCFragment::~MCFragment () virtual
Definition at line 267 of file MCAssembler.cpp.
Member Function Documentation
alignToBundleEnd()
virtual bool llvm::MCFragment::alignToBundleEnd () const inline virtual
Should this fragment be placed at the end of an aligned bundle?
Reimplemented in llvm::MCCompactEncodedInstFragment, and llvm::MCDataFragment.
Definition at line 113 of file MCAssembler.h.
dump()
void MCFragment::dump ()
Definition at line 1137 of file MCAssembler.cpp.
References llvm::cast(), llvm::errs(), F, llvm::MCDataFragment::fixup_begin(), llvm::MCDataFragment::fixup_end(), FT_Align, FT_CompactEncodedInst, FT_Data, FT_Dwarf, FT_DwarfFrame, FT_Fill, FT_LEB, FT_Org, FT_Relaxable, llvm::MCDwarfCallFrameFragment::getAddrDelta(), llvm::MCDwarfLineAddrFragment::getAddrDelta(), llvm::MCAlignFragment::getAlignment(), getBundlePadding(), llvm::MCCompactEncodedInstFragment::getContents(), llvm::MCDataFragment::getContents(), getKind(), llvm::MCDwarfLineAddrFragment::getLineDelta(), llvm::MCAlignFragment::getMaxBytesToEmit(), llvm::MCOrgFragment::getOffset(), llvm::MCFillFragment::getSize(), llvm::MCAlignFragment::getValue(), llvm::MCFillFragment::getValue(), llvm::MCLEBFragment::getValue(), llvm::MCOrgFragment::getValue(), llvm::MCAlignFragment::getValueSize(), llvm::MCFillFragment::getValueSize(), llvm::MCAlignFragment::hasEmitNops(), hasInstructions(), llvm::hexdigit(), llvm::MCLEBFragment::isSigned(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
getAtom()
MCSymbolData * llvm::MCFragment::getAtom () const inline
Definition at line 102 of file MCAssembler.h.
Referenced by llvm::MCAssembler::getAtom(), and llvm::MachObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl().
getBundlePadding()
virtual uint8_t llvm::MCFragment::getBundlePadding () const inline virtual
Get the padding size that must be inserted before this fragment. Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
Reimplemented in llvm::MCEncodedFragment.
Definition at line 121 of file MCAssembler.h.
Referenced by dump().
getKind()
FragmentType llvm::MCFragment::getKind () const inline
Definition at line 97 of file MCAssembler.h.
Referenced by dump().
getLayoutOrder()
unsigned llvm::MCFragment::getLayoutOrder () const inline
Definition at line 105 of file MCAssembler.h.
getParent()
MCSectionData * llvm::MCFragment::getParent () const inline
Definition at line 99 of file MCAssembler.h.
Referenced by AttemptToFoldSymbolOffsetDifference(), llvm::MCAssembler::getAtom(), llvm::MachObjectWriter::getFragmentAddress(), llvm::MachObjectWriter::getSymbolAddress(), llvm::MachObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), and llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl().
hasInstructions()
virtual bool llvm::MCFragment::hasInstructions () const inline virtual
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
Reimplemented in llvm::MCCompactEncodedInstFragment, llvm::MCDataFragment, and llvm::MCRelaxableFragment.
Definition at line 110 of file MCAssembler.h.
Referenced by dump().
setAlignToBundleEnd()
virtual void llvm::MCFragment::setAlignToBundleEnd (bool V) inline virtual
Reimplemented in llvm::MCCompactEncodedInstFragment, and llvm::MCDataFragment.
Definition at line 114 of file MCAssembler.h.
setAtom()
void llvm::MCFragment::setAtom (MCSymbolData * Value) inline
Definition at line 103 of file MCAssembler.h.
setBundlePadding()
virtual void llvm::MCFragment::setBundlePadding (uint8_t N) inline virtual
Set the padding size for this fragment. By default it's a no-op, and only some fragments have a meaningful implementation.
Reimplemented in llvm::MCEncodedFragment.
Definition at line 127 of file MCAssembler.h.
References N.
setLayoutOrder()
void llvm::MCFragment::setLayoutOrder (unsigned Value) inline
Definition at line 106 of file MCAssembler.h.
setParent()
void llvm::MCFragment::setParent (MCSectionData * Value) inline
Definition at line 100 of file MCAssembler.h.
Friends And Related Symbol Documentation
MCAsmLayout
friend class MCAsmLayout friend
Definition at line 47 of file MCAssembler.h.
References LLVM_DELETED_FUNCTION, and MCAsmLayout.
Referenced by MCAsmLayout.
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp