LLVM: llvm::FortifiedLibCallSimplifier Class Reference
LLVM API Documentation
llvm::FortifiedLibCallSimplifier Class Reference
This class implements simplifications for calls to fortified library functions (__st*cpy_chk, __memcpy_chk, __memmove_chk, __memset_chk), to, when possible, replace them with their non-checking counterparts. Other optimizations can also be done, but it's possible to disable them and only simplify needless use of the checking versions (when the object size is unknown) by passing true for OnlyLowerUnknownSize.
#include <SimplifyLibCalls.h>
Public Member Functions
FortifiedLibCallSimplifier (const DataLayout *DL, const TargetLibraryInfo *TLI, bool OnlyLowerUnknownSize=false)
Value * optimizeCall (CallInst *CI)
Take the given call instruction and return a more optimal value to replace the instruction with or 0 if a more optimal form can't be found. The call must not be an indirect call.
Detailed Description
This class implements simplifications for calls to fortified library functions (__st*cpy_chk, __memcpy_chk, __memmove_chk, __memset_chk), to, when possible, replace them with their non-checking counterparts. Other optimizations can also be done, but it's possible to disable them and only simplify needless use of the checking versions (when the object size is unknown) by passing true for OnlyLowerUnknownSize.
Definition at line 37 of file SimplifyLibCalls.h.
Constructor & Destructor Documentation
FortifiedLibCallSimplifier()
FortifiedLibCallSimplifier::FortifiedLibCallSimplifier (const DataLayout * DL, const TargetLibraryInfo * TLI, bool OnlyLowerUnknownSize = false)
Definition at line 2327 of file SimplifyLibCalls.cpp.
Member Function Documentation
optimizeCall()
Value * FortifiedLibCallSimplifier::optimizeCall (CallInst * CI)
Take the given call instruction and return a more optimal value to replace the instruction with or 0 if a more optimal form can't be found. The call must not be an indirect call.
Definition at line 2290 of file SimplifyLibCalls.cpp.
References llvm::CallingConv::C, FuncName, llvm::CallInst::getCalledFunction(), llvm::CallInst::getCallingConv(), llvm::Value::getName(), ignoreCallingConv(), llvm::CallInst::isNoBuiltin(), llvm::LibFunc::memcpy_chk, llvm::LibFunc::memmove_chk, llvm::LibFunc::memset_chk, llvm::LibFunc::stpcpy_chk, llvm::LibFunc::stpncpy_chk, llvm::LibFunc::strcpy_chk, and llvm::LibFunc::strncpy_chk.
The documentation for this class was generated from the following files:
SimplifyLibCalls.h
SimplifyLibCalls.cpp