LLVM: llvm::coverage::CounterMappingContext Class Reference
LLVM API Documentation
llvm::coverage::CounterMappingContext Class Reference
A Counter mapping context is used to connect the counters, expressions and the obtained counter values.
#include <CoverageMapping.h>
Public Member Functions
CounterMappingContext (ArrayRef< CounterExpression > Expressions, ArrayRef< uint64_t > CounterValues=ArrayRef< uint64_t >())
void dump (const Counter &C, llvm::raw_ostream &OS) const
void dump (const Counter &C) const
ErrorOr< int64_t > evaluate (const Counter &C) const
Return the number of times that a region of code associated with this counter was executed.
Detailed Description
A Counter mapping context is used to connect the counters, expressions and the obtained counter values.
Definition at line 210 of file CoverageMapping.h.
Constructor & Destructor Documentation
CounterMappingContext()
llvm::coverage::CounterMappingContext::CounterMappingContext (ArrayRef< CounterExpression > Expressions, ArrayRef< uint64_t > CounterValues = ArrayRef<uint64_t>()) inline
Definition at line 215 of file CoverageMapping.h.
Member Function Documentation
dump() [1/2]
void llvm::coverage::CounterMappingContext::dump (const Counter & C) const inline
Definition at line 220 of file CoverageMapping.h.
References dump(), and llvm::outs().
Referenced by dump().
dump() [2/2]
void CounterMappingContext::dump (const Counter & C, llvm::raw_ostream & OS) const
Definition at line 119 of file CoverageMapping.cpp.
References llvm::coverage::Counter::CounterValueReference, dump(), evaluate(), llvm::coverage::Counter::Expression, llvm::coverage::CounterExpression::Subtract, and llvm::coverage::Counter::Zero.
Referenced by dump().
evaluate()
ErrorOr< int64_t > CounterMappingContext::evaluate (const Counter & C) const
Return the number of times that a region of code associated with this counter was executed.
Definition at line 148 of file CoverageMapping.cpp.
References llvm::coverage::Counter::CounterValueReference, evaluate(), llvm::coverage::Counter::Expression, llvm_unreachable, llvm::coverage::CounterExpression::Subtract, and llvm::coverage::Counter::Zero.
Referenced by dump(), and evaluate().
The documentation for this class was generated from the following files:
CoverageMapping.h
CoverageMapping.cpp