LLVM: llvm::DominatorBase< NodeT > Class Template Reference
LLVM API Documentation
llvm::DominatorBase< NodeT > Class Template Reference
Base class that other, more interesting dominator analyses inherit from.
#include <GenericDomTree.h>
Public Member Functions
const std::vector< NodeT * > & getRoots () const
bool isPostDominator () const
Protected Member Functions
DominatorBase (bool isPostDom)
DominatorBase (DominatorBase &&Arg)
DominatorBase & operator= (DominatorBase &&RHS)
Protected Attributes
std::vector< NodeT * > Roots
bool IsPostDominators
Detailed Description
template<class NodeT>
class llvm::DominatorBase< NodeT >
Base class that other, more interesting dominator analyses inherit from.
Definition at line 34 of file GenericDomTree.h.
Constructor & Destructor Documentation
DominatorBase() [1/2]
template<class NodeT> llvm::DominatorBase< NodeT >::DominatorBase (bool isPostDom) inline explicit protected
Definition at line 38 of file GenericDomTree.h.
References IsPostDominators, and Roots.
Referenced by DominatorBase(), llvm::DominatorTreeBase< BlockT >::DominatorTreeBase(), llvm::DominatorTreeBase< BlockT >::DominatorTreeBase(), operator=(), and llvm::DominatorTreeBase< BlockT >::operator=().
DominatorBase() [2/2]
template<class NodeT> llvm::DominatorBase< NodeT >::DominatorBase (DominatorBase< NodeT > && Arg) inline protected
Definition at line 40 of file GenericDomTree.h.
References DominatorBase(), IsPostDominators, and Roots.
Member Function Documentation
getRoots()
template<class NodeT> const std::vector< NodeT * > & llvm::DominatorBase< NodeT >::getRoots () const inline
getRoots - Return the root blocks of the current CFG. This may include multiple blocks if we are computing post dominators. For forward dominators, this will always be a single block (the entry node).
Definition at line 57 of file GenericDomTree.h.
References Roots.
Referenced by llvm::ForwardDominanceFrontierBase< BlockT >::analyze().
isPostDominator()
template<class NodeT> bool llvm::DominatorBase< NodeT >::isPostDominator () const inline
isPostDominator - Returns true if analysis based of postdoms
Definition at line 61 of file GenericDomTree.h.
References IsPostDominators.
Referenced by llvm::DominatorTreeBase< BlockT >::findNearestCommonDominator(), llvm::DominatorTreeBase< BlockT >::isReachableFromEntry(), and llvm::DominatorTreeBase< BlockT >::print().
operator=()
template<class NodeT> DominatorBase & llvm::DominatorBase< NodeT >::operator= (DominatorBase< NodeT > && RHS) inline protected
Definition at line 45 of file GenericDomTree.h.
References DominatorBase(), IsPostDominators, and Roots.
Referenced by llvm::DominatorTreeBase< BlockT >::operator=().
Member Data Documentation
IsPostDominators
template<class NodeT> bool llvm::DominatorBase< NodeT >::IsPostDominators protected
Definition at line 37 of file GenericDomTree.h.
Referenced by DominatorBase(), DominatorBase(), isPostDominator(), operator=(), llvm::DominatorTreeBase< BlockT >::recalculate(), and llvm::DominatorTreeBase< BlockT >::splitBlock().
Roots
template<class NodeT> std::vector<NodeT *> llvm::DominatorBase< NodeT >::Roots protected
Definition at line 36 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::addRoot(), llvm::DominatorTreeBase< BlockT >::addRoot(), llvm::DominatorTreeBase< BlockT >::DFSPass, DominatorBase(), DominatorBase(), llvm::DominatorTreeBase< BlockT >::getRoot(), getRoots(), operator=(), llvm::DominatorTreeBase< BlockT >::recalculate(), and llvm::DominatorTreeBase< BlockT >::reset().
The documentation for this class was generated from the following file:
GenericDomTree.h