LLVM: llvm::ModuleAnalysisManagerCGSCCProxy::Result Class Reference
LLVM API Documentation
llvm::ModuleAnalysisManagerCGSCCProxy::Result Class Reference
Result proxy object for ModuleAnalysisManagerCGSCCProxy.
#include <CGSCCPassManager.h>
Public Member Functions
Result (const ModuleAnalysisManager &MAM)
Result (const Result &Arg)
Result (Result &&Arg)
Result & operator= (Result RHS)
const ModuleAnalysisManager & getManager () const
bool invalidate (LazyCallGraph::SCC &)
Handle invalidation by ignoring it, this pass is immutable.
Detailed Description
Result proxy object for ModuleAnalysisManagerCGSCCProxy.
Definition at line 136 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
Result() [1/3]
llvm::ModuleAnalysisManagerCGSCCProxy::Result::Result (const ModuleAnalysisManager & MAM) inline explicit
Definition at line 138 of file CGSCCPassManager.h.
Referenced by operator=(), Result(), and Result().
Result() [2/3]
llvm::ModuleAnalysisManagerCGSCCProxy::Result::Result (const Result & Arg) inline
Definition at line 141 of file CGSCCPassManager.h.
References Result().
Result() [3/3]
llvm::ModuleAnalysisManagerCGSCCProxy::Result::Result (Result && Arg) inline
Definition at line 142 of file CGSCCPassManager.h.
References Result().
Member Function Documentation
getManager()
const ModuleAnalysisManager & llvm::ModuleAnalysisManagerCGSCCProxy::Result::getManager () const inline
Definition at line 148 of file CGSCCPassManager.h.
invalidate()
bool llvm::ModuleAnalysisManagerCGSCCProxy::Result::invalidate (LazyCallGraph::SCC &) inline
Handle invalidation by ignoring it, this pass is immutable.
Definition at line 151 of file CGSCCPassManager.h.
operator=()
Result & llvm::ModuleAnalysisManagerCGSCCProxy::Result::operator= (Result RHS) inline
Definition at line 143 of file CGSCCPassManager.h.
References Result(), and std::swap().
The documentation for this class was generated from the following file:
CGSCCPassManager.h