LLVM: llvm::BinaryConstantExpr Class Reference
LLVM API Documentation
llvm::BinaryConstantExpr Class Reference
#include <ConstantsContext.h>
Public Member Functions
void * operator new (size_t s)
BinaryConstantExpr (unsigned Opcode, Constant *C1, Constant *C2, unsigned Flags)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Public Member Functions inherited from llvm::ConstantExpr
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Transparently provide more efficient getOperand methods.
bool isCast () const
Return true if this is a convert constant expression.
bool isCompare () const
Return true if this is a compare constant expression.
bool hasIndices () const
Return true if this is an insertvalue or extractvalue expression, and the getIndices() method may be used.
bool isGEPWithNoNotionalOverIndexing () const
Return true if this is a getelementptr expression and all the index operands are compile-time known integers within the corresponding notional static array extents. Note that this is not equivalant to, a subset of, or a superset of the "inbounds" property.
unsigned getOpcode () const
getOpcode - Return the opcode at the root of this constant expression
unsigned getPredicate () const
ArrayRef< unsigned > getIndices () const
const char * getOpcodeName () const
getOpcodeName - Return a string representation for an opcode.
Constant * getWithOperandReplaced (unsigned OpNo, Constant *Op) const
Constant * getWithOperands (ArrayRef< Constant * > Ops) const
Constant * getWithOperands (ArrayRef< Constant * > Ops, Type *Ty, bool OnlyIfReduced=false) const
Get the current expression with the operands replaced.
Instruction * getAsInstruction ()
void destroyConstant () override
void replaceUsesOfWithOnConstant (Value *From, Value *To, Use *U) override
Public Member Functions inherited from llvm::Constant
bool isNullValue () const
bool isOneValue () const
Returns true if the value is one.
bool isAllOnesValue () const
bool isNegativeZeroValue () const
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool canTrap () const
bool isThreadDependent () const
isThreadDependent - Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
PossibleRelocationsTy getRelocationInfo () const
Constant * getAggregateElement (unsigned Elt) const
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
const APInt & getUniqueInteger () const
void removeDeadConstantUsers () const
Constant * stripPointerCasts ()
const Constant * stripPointerCasts () const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Additional Inherited Members
Public Types inherited from llvm::Constant
enum PossibleRelocationsTy { NoRelocation = 0 , LocalRelocation = 1 , GlobalRelocations = 2 }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range< op_iterator > op_range
typedef iterator_range< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal , BasicBlockVal , FunctionVal , GlobalAliasVal ,
GlobalVariableVal , UndefValueVal , BlockAddressVal , ConstantExprVal ,
ConstantAggregateZeroVal , ConstantDataArrayVal , ConstantDataVectorVal , ConstantIntVal ,
ConstantFPVal , ConstantArrayVal , ConstantStructVal , ConstantVectorVal ,
ConstantPointerNullVal , MetadataAsValueVal , InlineAsmVal , InstructionVal ,
ConstantFirstVal = FunctionVal , ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl< const User > const_user_iterator
Static Public Member Functions inherited from llvm::ConstantExpr
static Constant * getAlignOf (Type *Ty)
static Constant * getSizeOf (Type *Ty)
static Constant * getOffsetOf (StructType *STy, unsigned FieldNo)
static Constant * getOffsetOf (Type *Ty, Constant *FieldNo)
static Constant * getNeg (Constant *C, bool HasNUW=false, bool HasNSW=false)
static Constant * getFNeg (Constant *C)
static Constant * getNot (Constant *C)
static Constant * getAdd (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getFAdd (Constant *C1, Constant *C2)
static Constant * getSub (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getFSub (Constant *C1, Constant *C2)
static Constant * getMul (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getFMul (Constant *C1, Constant *C2)
static Constant * getUDiv (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getSDiv (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getFDiv (Constant *C1, Constant *C2)
static Constant * getURem (Constant *C1, Constant *C2)
static Constant * getSRem (Constant *C1, Constant *C2)
static Constant * getFRem (Constant *C1, Constant *C2)
static Constant * getAnd (Constant *C1, Constant *C2)
static Constant * getOr (Constant *C1, Constant *C2)
static Constant * getXor (Constant *C1, Constant *C2)
static Constant * getShl (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getLShr (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getAShr (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getTrunc (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getSExt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getZExt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPTrunc (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPExtend (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getUIToFP (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getSIToFP (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPToUI (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPToSI (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getPtrToInt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getIntToPtr (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getBitCast (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getAddrSpaceCast (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getNSWNeg (Constant *C)
static Constant * getNUWNeg (Constant *C)
static Constant * getNSWAdd (Constant *C1, Constant *C2)
static Constant * getNUWAdd (Constant *C1, Constant *C2)
static Constant * getNSWSub (Constant *C1, Constant *C2)
static Constant * getNUWSub (Constant *C1, Constant *C2)
static Constant * getNSWMul (Constant *C1, Constant *C2)
static Constant * getNUWMul (Constant *C1, Constant *C2)
static Constant * getNSWShl (Constant *C1, Constant *C2)
static Constant * getNUWShl (Constant *C1, Constant *C2)
static Constant * getExactSDiv (Constant *C1, Constant *C2)
static Constant * getExactUDiv (Constant *C1, Constant *C2)
static Constant * getExactAShr (Constant *C1, Constant *C2)
static Constant * getExactLShr (Constant *C1, Constant *C2)
static Constant * getBinOpIdentity (unsigned Opcode, Type *Ty)
static Constant * getBinOpAbsorber (unsigned Opcode, Type *Ty)
static Constant * getCast (unsigned ops, Constant *C, Type *Ty, bool OnlyIfReduced=false)
Convenience function for getting a Cast operation.
static Constant * getZExtOrBitCast (Constant *C, Type *Ty)
static Constant * getSExtOrBitCast (Constant *C, Type *Ty)
static Constant * getTruncOrBitCast (Constant *C, Type *Ty)
static Constant * getPointerCast (Constant *C, Type *Ty)
Create a BitCast, AddrSpaceCast, or a PtrToInt cast constant expression.
static Constant * getPointerBitCastOrAddrSpaceCast (Constant *C, Type *Ty)
Create a BitCast or AddrSpaceCast for a pointer type depending on the address space.
static Constant * getIntegerCast (Constant *C, Type *Ty, bool isSigned)
Create a ZExt, Bitcast or Trunc for integer -> integer casts.
static Constant * getFPCast (Constant *C, Type *Ty)
Create a FPExt, Bitcast or FPTrunc for fp -> fp casts.
static Constant * getSelect (Constant *C, Constant *V1, Constant *V2, Type *OnlyIfReducedTy=nullptr)
static Constant * get (unsigned Opcode, Constant *C1, Constant *C2, unsigned Flags=0, Type *OnlyIfReducedTy=nullptr)
static Constant * getCompare (unsigned short pred, Constant *C1, Constant *C2, bool OnlyIfReduced=false)
Return an ICmp or FCmp comparison operator constant expression.
static Constant * getICmp (unsigned short pred, Constant *LHS, Constant *RHS, bool OnlyIfReduced=false)
static Constant * getFCmp (unsigned short pred, Constant *LHS, Constant *RHS, bool OnlyIfReduced=false)
static Constant * getGetElementPtr (Constant *C, ArrayRef< Constant * > IdxList, bool InBounds=false, Type *OnlyIfReducedTy=nullptr)
static Constant * getGetElementPtr (Constant *C, Constant *Idx, bool InBounds=false, Type *OnlyIfReducedTy=nullptr)
static Constant * getGetElementPtr (Constant *C, ArrayRef< Value * > IdxList, bool InBounds=false, Type *OnlyIfReducedTy=nullptr)
static Constant * getInBoundsGetElementPtr (Constant *C, ArrayRef< Constant * > IdxList)
static Constant * getInBoundsGetElementPtr (Constant *C, Constant *Idx)
static Constant * getInBoundsGetElementPtr (Constant *C, ArrayRef< Value * > IdxList)
static Constant * getExtractElement (Constant *Vec, Constant *Idx, Type *OnlyIfReducedTy=nullptr)
static Constant * getInsertElement (Constant *Vec, Constant *Elt, Constant *Idx, Type *OnlyIfReducedTy=nullptr)
static Constant * getShuffleVector (Constant *V1, Constant *V2, Constant *Mask, Type *OnlyIfReducedTy=nullptr)
static Constant * getExtractValue (Constant *Agg, ArrayRef< unsigned > Idxs, Type *OnlyIfReducedTy=nullptr)
static Constant * getInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > Idxs, Type *OnlyIfReducedTy=nullptr)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
static Constant * getAllOnesValue (Type *Ty)
Get the all ones value.
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Protected Member Functions inherited from llvm::ConstantExpr
ConstantExpr (Type *ty, unsigned Opcode, Use *Ops, unsigned NumOps)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
void destroyConstantImpl ()
void replaceUsesOfWithOnConstantImpl (Constant *Replacement)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Detailed Description
BinaryConstantExpr - This class is private to Constants.cpp, and is used behind the scenes to implement binary constant exprs.
Definition at line 52 of file ConstantsContext.h.
Constructor & Destructor Documentation
BinaryConstantExpr()
llvm::BinaryConstantExpr::BinaryConstantExpr (unsigned Opcode, Constant * C1, Constant * C2, unsigned Flags) inline
Definition at line 60 of file ConstantsContext.h.
References llvm::ConstantExpr::ConstantExpr(), llvm::Value::getType(), llvm::User::Op(), and llvm::Value::SubclassOptionalData.
Member Function Documentation
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::BinaryConstantExpr::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
operator new()
void * llvm::BinaryConstantExpr::operator new (size_t s) inline
Definition at line 57 of file ConstantsContext.h.
The documentation for this class was generated from the following files:
ConstantsContext.h
LLVMContextImpl.cpp