LLVM: llvm::SDVTListNode Class Reference
LLVM API Documentation
llvm::SDVTListNode Class Reference
#include <SelectionDAG.h>
Public Member Functions
SDVTListNode (const FoldingSetNodeIDRef ID, const EVT *VT, unsigned int Num)
SDVTList getSDVTList ()
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Friends
struct FoldingSetTrait< SDVTListNode >
Detailed Description
Definition at line 42 of file SelectionDAG.h.
Constructor & Destructor Documentation
SDVTListNode()
llvm::SDVTListNode::SDVTListNode (const FoldingSetNodeIDRef ID, const EVT * VT, unsigned int Num) inline
Definition at line 54 of file SelectionDAG.h.
Member Function Documentation
getSDVTList()
SDVTList llvm::SDVTListNode::getSDVTList () inline
Definition at line 58 of file SelectionDAG.h.
Referenced by llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::getVTList(), and llvm::SelectionDAG::getVTList().
Friends And Related Symbol Documentation
FoldingSetTrait< SDVTListNode >
friend struct FoldingSetTrait< SDVTListNode > friend
Definition at line 160 of file SelectionDAG.h.
The documentation for this class was generated from the following file:
SelectionDAG.h