LLVM: llvm::SystemZFrameLowering Class Reference
LLVM API Documentation
llvm::SystemZFrameLowering Class Reference
#include <SystemZFrameLowering.h>
Public Member Functions
SystemZFrameLowering ()
bool isFPCloseToIncomingSP () const override
const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const override
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS) const override
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBII, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS) const override
void emitPrologue (MachineFunction &MF) const override
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool hasFP (const MachineFunction &MF) const override
int getFrameIndexOffset (const MachineFunction &MF, int FI) const override
bool hasReservedCallFrame (const MachineFunction &MF) const override
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
uint64_t getAllocatedStackSize (const MachineFunction &MF) const
unsigned getRegSpillOffset (unsigned Reg) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
unsigned getStackAlignment () const
unsigned getTransientStackAlignment () const
bool isStackRealignable () const
int getOffsetOfLocalArea () const
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
virtual bool targetHandlesStackFrameRounding () const
virtual void adjustForSegmentedStacks (MachineFunction &MF) const
virtual void adjustForHiPEPrologue (MachineFunction &MF) const
virtual void adjustForFrameAllocatePrologue (MachineFunction &MF) const
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
virtual int getFrameIndexReferenceFromSP (const MachineFunction &MF, int FI, unsigned &FrameReg) const
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Detailed Description
Definition at line 20 of file SystemZFrameLowering.h.
Constructor & Destructor Documentation
SystemZFrameLowering()
SystemZFrameLowering::SystemZFrameLowering ()
Definition at line 49 of file SystemZFrameLowering.cpp.
References llvm::array_lengthof(), I, llvm::TargetFrameLowering::StackGrowsDown, and llvm::TargetFrameLowering::TargetFrameLowering().
Member Function Documentation
eliminateCallFramePseudoInstr()
void SystemZFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them). It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 500 of file SystemZFrameLowering.cpp.
References llvm::MachineBasicBlock::erase(), hasReservedCallFrame(), and llvm_unreachable.
emitEpilogue()
void SystemZFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 409 of file SystemZFrameLowering.cpp.
References llvm::MachineOperand::ChangeToImmediate(), emitIncrement(), getAllocatedStackSize(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::SystemZMachineFunctionInfo::getLowSavedGPR(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineInstr::isReturn(), llvm_unreachable, and llvm::MachineInstr::setDesc().
emitPrologue()
void SystemZFrameLowering::emitPrologue (MachineFunction & MF) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 312 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineModuleInfo::addFrameInst(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::SystemZMC::CFAOffsetFromInitialSP, llvm::TargetOpcode::CFI_INSTRUCTION, contains(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createOffset(), emitIncrement(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineFunction::front(), llvm::DebugLoc::get(), getAllocatedStackSize(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineModuleInfo::getContext(), llvm::MachineInstr::getDebugLoc(), llvm::MCRegisterInfo::getDwarfRegNum(), getFrameIndexOffset(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::SystemZMachineFunctionInfo::getLowSavedGPR(), llvm::MachineFunction::getMMI(), llvm::MachineInstr::getOpcode(), llvm::MCContext::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), hasFP(), I, llvm_unreachable, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
getAllocatedStackSize()
uint64_t SystemZFrameLowering::getAllocatedStackSize (const MachineFunction & MF) const
Definition at line 475 of file SystemZFrameLowering.cpp.
References llvm::SystemZMC::CallFrameSize, llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFrameInfo::hasCalls(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by emitEpilogue(), emitPrologue(), and getFrameIndexOffset().
getCalleeSavedSpillSlots()
const TargetFrameLowering::SpillSlot * SystemZFrameLowering::getCalleeSavedSpillSlots (unsigned & NumEntries) const override virtual
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
Each entry in this array contains a <register,offset> pair, indicating the fixed offset from the incoming stack pointer that each register should be spilled at. If a register is not listed here, the code generator is allowed to spill it anywhere it chooses.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 59 of file SystemZFrameLowering.cpp.
References llvm::array_lengthof().
getFrameIndexOffset()
int SystemZFrameLowering::getFrameIndexOffset (const MachineFunction & MF, int FI) const override virtual
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index.
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index. This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 456 of file SystemZFrameLowering.cpp.
References getAllocatedStackSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getOffsetAdjustment(), and llvm::TargetFrameLowering::getOffsetOfLocalArea().
Referenced by emitPrologue().
getRegSpillOffset()
unsigned llvm::SystemZFrameLowering::getRegSpillOffset (unsigned Reg) const inline
Definition at line 58 of file SystemZFrameLowering.h.
hasFP()
bool SystemZFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register. For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 450 of file SystemZFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::SystemZMachineFunctionInfo::getManipulatesSP(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasVarSizedObjects(), and llvm::TargetMachine::Options.
Referenced by emitPrologue(), processFunctionBeforeCalleeSavedScan(), and restoreCalleeSavedRegisters().
hasReservedCallFrame()
bool SystemZFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function. This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 492 of file SystemZFrameLowering.cpp.
Referenced by eliminateCallFramePseudoInstr().
isFPCloseToIncomingSP()
bool llvm::SystemZFrameLowering::isFPCloseToIncomingSP () const inline override virtual
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 27 of file SystemZFrameLowering.h.
processFunctionBeforeCalleeSavedScan()
void SystemZFrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS) const override virtual
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 64 of file SystemZFrameLowering.cpp.
References llvm::SystemZ::ArgGPRs, contains(), llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::SystemZMachineFunctionInfo::getVarArgsFirstGPR(), llvm::MachineFrameInfo::hasCalls(), hasFP(), I, llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::Function::isVarArg(), llvm::SystemZ::NumArgGPRs, and llvm::MachineRegisterInfo::setPhysRegUsed().
processFunctionBeforeFrameFinalized()
void SystemZFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized. Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 267 of file SystemZFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::SystemZMC::CallFrameSize, llvm::MachineFrameInfo::CreateStackObject(), llvm::MachineFrameInfo::estimateStackSize(), llvm::MachineFunction::getFrameInfo(), and llvm::isUInt().
restoreCalleeSavedRegisters()
bool SystemZFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 212 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::RegState::Define, llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDebugLoc(), llvm::SystemZMachineFunctionInfo::getHighSavedGPR(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::SystemZMachineFunctionInfo::getLowSavedGPR(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), hasFP(), I, llvm::RegState::ImplicitDefine, and TII.
spillCalleeSavedRegisters()
bool SystemZFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 123 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), addSavedGPR(), llvm::SystemZ::ArgGPRs, llvm::BuildMI(), contains(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::SystemZMachineFunctionInfo::getVarArgsFirstGPR(), I, llvm::Function::isVarArg(), llvm::SystemZ::NumArgGPRs, llvm::SystemZMachineFunctionInfo::setHighSavedGPR(), llvm::SystemZMachineFunctionInfo::setLowSavedGPR(), and TII.
The documentation for this class was generated from the following files:
SystemZFrameLowering.h
SystemZFrameLowering.cpp