LLVM: llvm::TargetMachine Class Reference
LLVM API Documentation
llvm::TargetMachine Class Reference
#include <TargetMachine.h>
Public Types
enum CodeGenFileType { CGFT_AssemblyFile , CGFT_ObjectFile , CGFT_Null }
Public Member Functions
virtual ~TargetMachine ()
const Target & getTarget () const
StringRef getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
virtual const TargetSubtargetInfo * getSubtargetImpl () const
virtual const TargetSubtargetInfo * getSubtargetImpl (const Function &) const
virtual TargetLoweringObjectFile * getObjFileLowering () const
template<typename STC>
const STC & getSubtarget () const
template<typename STC>
const STC & getSubtarget (const Function *) const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
CodeModel::Model getCodeModel () const
TLSModel::Model getTLSModel (const GlobalValue *GV) const
CodeGenOpt::Level getOptLevel () const
void setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
void setFastISel (bool Enable)
bool shouldPrintMachineCode () const
bool getAsmVerbosityDefault () const
void setAsmVerbosityDefault (bool)
bool getDataSections () const
bool getFunctionSections () const
void setDataSections (bool)
setDataSections - Set if the data are emit into separate sections.
void setFunctionSections (bool)
virtual void addAnalysisPasses (PassManagerBase &)
Register analysis passes for this target with a pass manager.
virtual bool addPassesToEmitFile (PassManagerBase &, formatted_raw_ostream &, CodeGenFileType, bool=true, AnalysisID=nullptr, AnalysisID=nullptr)
virtual bool addPassesToEmitMC (PassManagerBase &, MCContext *&, raw_ostream &, bool=true)
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV, Mangler &Mang) const
Public Attributes
TargetOptions Options
Protected Member Functions
TargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes
const Target & TheTarget
TheTarget - The Target that this machine was created for.
std::string TargetTriple
std::string TargetCPU
std::string TargetFS
MCCodeGenInfo * CodeGenInfo
const MCAsmInfo * AsmInfo
unsigned RequireStructuredCFG: 1
Detailed Description
TargetMachine - Primary interface to the complete machine description for the target machine. All target-specific information should be accessible through this interface.
Definition at line 61 of file llvm/Target/TargetMachine.h.
Member Enumeration Documentation
CodeGenFileType
enum llvm::TargetMachine::CodeGenFileType
CodeGenFileType - These enums are meant to be passed into addPassesToEmitFile to indicate what type of file to emit, and returned by it to indicate what type of file could actually be made.
Enumerator
CGFT_AssemblyFile
CGFT_ObjectFile
CGFT_Null
Definition at line 191 of file llvm/Target/TargetMachine.h.
Constructor & Destructor Documentation
TargetMachine()
TargetMachine::TargetMachine (const Target & T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions & Options) protected
Definition at line 37 of file TargetMachine.cpp.
References AsmInfo, CodeGenInfo, Options, RequireStructuredCFG, TargetCPU, TargetFS, TargetTriple, and TheTarget.
~TargetMachine()
TargetMachine::~TargetMachine () virtual
Definition at line 46 of file TargetMachine.cpp.
References AsmInfo, and CodeGenInfo.
Member Function Documentation
addAnalysisPasses()
virtual void llvm::TargetMachine::addAnalysisPasses (PassManagerBase &) inline virtual
Register analysis passes for this target with a pass manager.
Reimplemented in llvm::AArch64TargetMachine, llvm::AMDGPUTargetMachine, llvm::ARMBaseTargetMachine, llvm::LLVMTargetMachine, llvm::MipsTargetMachine, llvm::NVPTXTargetMachine, llvm::PPCTargetMachine, llvm::X86TargetMachine, and llvm::XCoreTargetMachine.
Definition at line 186 of file llvm/Target/TargetMachine.h.
addPassesToEmitFile()
virtual bool llvm::TargetMachine::addPassesToEmitFile (PassManagerBase & , formatted_raw_ostream & , CodeGenFileType , bool = true, AnalysisID = nullptr, AnalysisID = nullptr) inline virtual
addPassesToEmitFile - Add passes to the specified pass manager to get the specified file emitted. Typically this will involve several steps of code generation. This method should return true if emission of this file type is not supported, or false on success.
Reimplemented in llvm::CPPTargetMachine, and llvm::LLVMTargetMachine.
Definition at line 201 of file llvm/Target/TargetMachine.h.
addPassesToEmitMC()
virtual bool llvm::TargetMachine::addPassesToEmitMC (PassManagerBase & , MCContext *& , raw_ostream & , bool = true) inline virtual
addPassesToEmitMC - Add passes to the specified pass manager to get machine code emitted with the MCJIT. This method returns true if machine code is not supported. It fills the MCContext Ctx pointer which can be used to build custom MCStreamer.
Reimplemented in llvm::LLVMTargetMachine, and llvm::NVPTXTargetMachine.
Definition at line 215 of file llvm/Target/TargetMachine.h.
getAsmVerbosityDefault()
bool TargetMachine::getAsmVerbosityDefault () const
getAsmVerbosityDefault - Returns the default value of asm verbosity.
Definition at line 149 of file TargetMachine.cpp.
References Options.
getCodeModel()
CodeModel::Model TargetMachine::getCodeModel () const
getCodeModel - Returns the code model. The choices are small, kernel, medium, large, and target default.
Definition at line 82 of file TargetMachine.cpp.
References CodeGenInfo, and llvm::CodeModel::Default.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::emitStackProbeCall(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86TargetLowering::isLegalAddressingMode(), and IsSmallObject().
getDataSections()
bool TargetMachine::getDataSections () const
getDataSections - Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
Definition at line 161 of file TargetMachine.cpp.
References Options.
getFunctionSections()
bool TargetMachine::getFunctionSections () const
getFunctionSections - Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
Definition at line 157 of file TargetMachine.cpp.
References Options.
getIntrinsicInfo()
virtual const TargetIntrinsicInfo * llvm::TargetMachine::getIntrinsicInfo () const inline virtual
getIntrinsicInfo - If intrinsic information is available, return it. If not, return null.
Reimplemented in llvm::AMDGPUTargetMachine.
Definition at line 132 of file llvm/Target/TargetMachine.h.
getMCAsmInfo()
const MCAsmInfo * llvm::TargetMachine::getMCAsmInfo () const inline
getMCAsmInfo - Return target specific asm information.
Definition at line 127 of file llvm/Target/TargetMachine.h.
References AsmInfo.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), llvm::AArch64InstrInfo::GetInstSizeInBytes(), llvm::ARMBaseInstrInfo::GetInstSizeInBytes(), llvm::MipsInstrInfo::GetInstSizeInBytes(), llvm::MSP430InstrInfo::GetInstSizeInBytes(), llvm::PPCInstrInfo::GetInstSizeInBytes(), and llvm::SystemZInstrInfo::getInstSizeInBytes().
getNameWithPrefix()
void TargetMachine::getNameWithPrefix (SmallVectorImpl< char > & Name, const GlobalValue * GV, Mangler & Mang, bool MayAlwaysUsePrivate = false) const
Definition at line 186 of file TargetMachine.cpp.
References AsmInfo, canUsePrivateLabel(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::Mangler::getNameWithPrefix(), llvm::TargetLoweringBase::getObjFileLowering(), getSubtargetImpl(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::GlobalValue::hasPrivateLinkage(), Name, and llvm::TargetLoweringObjectFile::SectionForGlobal().
Referenced by getSymbol().
getObjFileLowering()
virtual TargetLoweringObjectFile * llvm::TargetMachine::getObjFileLowering () const inline virtual
Reimplemented in llvm::AArch64TargetMachine, llvm::AMDGPUTargetMachine, llvm::ARMBaseTargetMachine, llvm::HexagonTargetMachine, llvm::MipsTargetMachine, llvm::MSP430TargetMachine, llvm::NVPTXTargetMachine, llvm::PPCTargetMachine, llvm::SparcTargetMachine, llvm::SystemZTargetMachine, llvm::X86TargetMachine, and llvm::XCoreTargetMachine.
Definition at line 106 of file llvm/Target/TargetMachine.h.
getOptLevel()
CodeGenOpt::Level TargetMachine::getOptLevel () const
getOptLevel - Returns the optimization level: None, Less, Default, or Aggressive.
Definition at line 138 of file TargetMachine.cpp.
References CodeGenInfo, and llvm::CodeGenOpt::Default.
Referenced by llvm::HexagonFrameLowering::emitEpilogue().
getRelocationModel()
Reloc::Model TargetMachine::getRelocationModel () const
getRelocationModel - Returns the code generation relocation model. The choices are static, PIC, and dynamic-no-pic, and target default.
Definition at line 74 of file TargetMachine.cpp.
References CodeGenInfo, and llvm::Reloc::Default.
Referenced by llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitPrologue(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::PPCRegisterInfo::getReservedRegs(), getTLSModel(), llvm::X86TargetLowering::isLegalAddressingMode(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::X86TargetLowering::LowerCustomJumpTableEntry(), PrepareCall(), and llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan().
getSubtarget() [1/2]
template<typename STC> const STC & llvm::TargetMachine::getSubtarget () const inline
getSubtarget - This method returns a pointer to the specified type of TargetSubtargetInfo. In debug builds, it verifies that the object being returned is of the correct type.
Definition at line 113 of file llvm/Target/TargetMachine.h.
References getSubtargetImpl().
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::SIInstrInfo::calculateLDSSpillAddress(), CC_MipsO32(), checkNumAlignedDPRCS2Regs(), llvm::Thumb1InstrInfo::copyPhysReg(), createPPCAsmPrinterPass(), llvm::PPCInstrInfo::CreateTargetPostRAHazardRecognizer(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), emitAligningInstructions(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitStackProbeCall(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SIMachineFunctionInfo::getMaximumWorkGroupSize(), getTargetVShiftNode(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), and llvm::X86FrameLowering::spillCalleeSavedRegisters().
getSubtarget() [2/2]
template<typename STC> const STC & llvm::TargetMachine::getSubtarget (const Function *) const inline
Definition at line 116 of file llvm/Target/TargetMachine.h.
References getSubtargetImpl().
getSubtargetImpl() [1/2]
virtual const TargetSubtargetInfo * llvm::TargetMachine::getSubtargetImpl () const inline virtual
getSubtargetImpl - virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented in llvm::AArch64TargetMachine, llvm::AMDGPUTargetMachine, llvm::ARMBaseTargetMachine, llvm::CPPTargetMachine, llvm::HexagonTargetMachine, llvm::MipsTargetMachine, llvm::MSP430TargetMachine, llvm::NVPTXTargetMachine, llvm::PPCTargetMachine, llvm::SparcTargetMachine, llvm::SystemZTargetMachine, llvm::X86TargetMachine, and llvm::XCoreTargetMachine.
Definition at line 100 of file llvm/Target/TargetMachine.h.
Referenced by addLiveInRegs(), llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::SITargetLowering::analyzeImmediate(), llvm::A57ChainingConstraint::apply(), llvm::SITargetLowering::buildScratchRSRC(), llvm::ARMBaseRegisterInfo::canRealignStack(), checkNumAlignedDPRCS2Regs(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::PPCTargetLowering::EmitAtomicBinary(), emitDebugValueComment(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitF128CSEL(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), emitKill(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::SparcTargetLowering::expandSelectCC(), llvm::TargetLoweringBase::findRepresentativeClass(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::AMDGPUInstrInfo::getIndirectIndexEnd(), getNameWithPrefix(), llvm::MipsTargetLowering::getOpndList(), llvm::PPCTargetLowering::getPrefLoopAlignment(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::ARMTargetLowering::getSchedulingPreference(), getSubtarget(), getSubtarget(), getSubtargetImpl(), getSymbol(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::PPC::isVSLDOIShuffleMask(), llvm::SystemZTargetLowering::LowerCall(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::SITargetLowering::PostISelFolding(), llvm::SITargetLowering::shouldConvertConstantLoadToIntImm(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getSubtargetImpl() [2/2]
virtual const TargetSubtargetInfo * llvm::TargetMachine::getSubtargetImpl (const Function &) const inline virtual
Reimplemented in llvm::AArch64TargetMachine, llvm::ARMBaseTargetMachine, llvm::MipsTargetMachine, llvm::PPCTargetMachine, and llvm::X86TargetMachine.
Definition at line 103 of file llvm/Target/TargetMachine.h.
References getSubtargetImpl().
getSymbol()
MCSymbol * TargetMachine::getSymbol (const GlobalValue * GV, Mangler & Mang) const
Definition at line 203 of file TargetMachine.cpp.
References llvm::TargetLoweringObjectFile::getContext(), getNameWithPrefix(), llvm::TargetLoweringBase::getObjFileLowering(), llvm::MCContext::GetOrCreateSymbol(), getSubtargetImpl(), llvm::TargetSubtargetInfo::getTargetLowering(), and llvm::SmallString< InternalLen >::str().
getTarget()
const Target & llvm::TargetMachine::getTarget () const inline
Definition at line 92 of file llvm/Target/TargetMachine.h.
References TheTarget.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
getTargetCPU()
StringRef llvm::TargetMachine::getTargetCPU () const inline
Definition at line 95 of file llvm/Target/TargetMachine.h.
References TargetCPU.
getTargetFeatureString()
StringRef llvm::TargetMachine::getTargetFeatureString () const inline
Definition at line 96 of file llvm/Target/TargetMachine.h.
References TargetFS.
getTargetTriple()
StringRef llvm::TargetMachine::getTargetTriple () const inline
Definition at line 94 of file llvm/Target/TargetMachine.h.
References TargetTriple.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::PPCTargetMachine::PPCTargetMachine(), and llvm::X86TargetMachine::X86TargetMachine().
getTLSModel()
TLSModel::Model TargetMachine::getTLSModel (const GlobalValue * GV) const
getTLSModel - Returns the TLS model which should be used for the given global variable.
Definition at line 106 of file TargetMachine.cpp.
References llvm::TLSModel::GeneralDynamic, getRelocationModel(), getSelectedTLSModel(), llvm::GlobalValue::hasHiddenVisibility(), llvm::GlobalValue::hasLocalLinkage(), llvm::TLSModel::InitialExec, llvm::GlobalValue::isDeclaration(), llvm::TLSModel::LocalDynamic, llvm::TLSModel::LocalExec, Options, and llvm::Reloc::PIC_.
Referenced by llvm::SparcTargetLowering::LowerGlobalTLSAddress().
requiresStructuredCFG()
bool llvm::TargetMachine::requiresStructuredCFG () const inline
Definition at line 136 of file llvm/Target/TargetMachine.h.
References RequireStructuredCFG.
Referenced by llvm::MachineBasicBlock::SplitCriticalEdge().
resetTargetOptions()
void TargetMachine::resetTargetOptions (const Function & F) const
Reset the target options based on the function's attributes.
Definition at line 52 of file TargetMachine.cpp.
References DisableTailCalls(), F, Options, RESET_OPTION, and llvm::Attribute::SanitizeAddress.
Referenced by llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), and llvm::X86TargetMachine::getSubtargetImpl().
setAsmVerbosityDefault()
void TargetMachine::setAsmVerbosityDefault (bool V)
setAsmVerbosityDefault - Set the default value of asm verbosity. Default is false.
Definition at line 153 of file TargetMachine.cpp.
References Options.
setDataSections()
void TargetMachine::setDataSections (bool V)
setDataSections - Set if the data are emit into separate sections.
Definition at line 169 of file TargetMachine.cpp.
References Options.
setFastISel()
void llvm::TargetMachine::setFastISel (bool Enable) inline
Definition at line 158 of file llvm/Target/TargetMachine.h.
References Options.
setFunctionSections()
void TargetMachine::setFunctionSections (bool V)
setFunctionSections - Set if the functions are emit into separate sections.
Definition at line 165 of file TargetMachine.cpp.
References Options.
setOptLevel()
void TargetMachine::setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
Definition at line 144 of file TargetMachine.cpp.
References CodeGenInfo.
setRequiresStructuredCFG()
void llvm::TargetMachine::setRequiresStructuredCFG (bool Value) inline
Definition at line 137 of file llvm/Target/TargetMachine.h.
References RequireStructuredCFG.
Referenced by llvm::AMDGPUTargetMachine::AMDGPUTargetMachine().
shouldPrintMachineCode()
bool llvm::TargetMachine::shouldPrintMachineCode () const inline
Definition at line 160 of file llvm/Target/TargetMachine.h.
References Options.
Member Data Documentation
AsmInfo
const MCAsmInfo* llvm::TargetMachine::AsmInfo protected
AsmInfo - Contains target specific asm information.
Definition at line 83 of file llvm/Target/TargetMachine.h.
Referenced by getMCAsmInfo(), getNameWithPrefix(), llvm::LLVMTargetMachine::initAsmInfo(), TargetMachine(), and ~TargetMachine().
CodeGenInfo
MCCodeGenInfo* llvm::TargetMachine::CodeGenInfo protected
CodeGenInfo - Low level target information such as relocation model. Non-const to allow resetting optimization level per-function.
Definition at line 79 of file llvm/Target/TargetMachine.h.
Referenced by getCodeModel(), getOptLevel(), getRelocationModel(), llvm::LLVMTargetMachine::LLVMTargetMachine(), setOptLevel(), TargetMachine(), and ~TargetMachine().
Options
TargetOptions llvm::TargetMachine::Options mutable
Definition at line 88 of file llvm/Target/TargetMachine.h.
Referenced by llvm::AArch64beTargetMachine::AArch64beTargetMachine(), llvm::AArch64leTargetMachine::AArch64leTargetMachine(), llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::NVPTXTargetLowering::allowFMA(), llvm::AMDGPUTargetMachine::AMDGPUTargetMachine(), llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), llvm::ARMBETargetMachine::ARMBETargetMachine(), llvm::ARMLETargetMachine::ARMLETargetMachine(), llvm::ARMTargetMachine::ARMTargetMachine(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::CPPTargetMachine::CPPTargetMachine(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::emitEpilogue(), llvm::GCNTargetMachine::GCNTargetMachine(), get64BitArgumentXMMs(), getAsmVerbosityDefault(), getDataSections(), getFunctionSections(), GetNegatedExpression(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), getTLSModel(), llvm::ARMFrameLowering::hasFP(), llvm::MipsFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::SystemZFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), llvm::HexagonTargetMachine::HexagonTargetMachine(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::LLVMTargetMachine::LLVMTargetMachine(), llvm::MipsebTargetMachine::MipsebTargetMachine(), llvm::MipselTargetMachine::MipselTargetMachine(), llvm::MipsTargetMachine::MipsTargetMachine(), llvm::MSP430TargetMachine::MSP430TargetMachine(), llvm::PPCFrameLowering::needsFP(), llvm::NVPTXTargetMachine::NVPTXTargetMachine(), llvm::NVPTXTargetMachine32::NVPTXTargetMachine32(), llvm::NVPTXTargetMachine64::NVPTXTargetMachine64(), PerformFMinFMaxCombine(), PerformSELECT_CCCombine(), PerformSELECTCombine(), PerformSTORECombine(), llvm::PPC32TargetMachine::PPC32TargetMachine(), llvm::PPC64TargetMachine::PPC64TargetMachine(), llvm::PPCTargetMachine::PPCTargetMachine(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), resetTargetOptions(), setAsmVerbosityDefault(), setDataSections(), setFastISel(), setFunctionSections(), shouldPrintMachineCode(), llvm::SparcTargetMachine::SparcTargetMachine(), llvm::SparcV8TargetMachine::SparcV8TargetMachine(), llvm::SparcV9TargetMachine::SparcV9TargetMachine(), llvm::SystemZTargetMachine::SystemZTargetMachine(), TargetMachine(), llvm::ThumbBETargetMachine::ThumbBETargetMachine(), llvm::ThumbLETargetMachine::ThumbLETargetMachine(), llvm::ThumbTargetMachine::ThumbTargetMachine(), llvm::X86TargetMachine::X86TargetMachine(), and llvm::XCoreTargetMachine::XCoreTargetMachine().
RequireStructuredCFG
unsigned llvm::TargetMachine::RequireStructuredCFG protected
Definition at line 85 of file llvm/Target/TargetMachine.h.
Referenced by requiresStructuredCFG(), setRequiresStructuredCFG(), and TargetMachine().
TargetCPU
std::string llvm::TargetMachine::TargetCPU protected
Definition at line 74 of file llvm/Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), getTargetCPU(), and TargetMachine().
TargetFS
std::string llvm::TargetMachine::TargetFS protected
Definition at line 75 of file llvm/Target/TargetMachine.h.
Referenced by llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), getTargetFeatureString(), llvm::PPCTargetMachine::PPCTargetMachine(), and TargetMachine().
TargetTriple
std::string llvm::TargetMachine::TargetTriple protected
TargetTriple, TargetCPU, TargetFS - Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
Definition at line 73 of file llvm/Target/TargetMachine.h.
Referenced by llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), getTargetTriple(), and TargetMachine().
TheTarget
const Target& llvm::TargetMachine::TheTarget protected
TheTarget - The Target that this machine was created for.
Definition at line 69 of file llvm/Target/TargetMachine.h.
Referenced by getTarget(), llvm::LLVMTargetMachine::initAsmInfo(), and TargetMachine().
The documentation for this class was generated from the following files:
llvm/Target/TargetMachine.h
TargetMachine.cpp