LLVM: llvm::SystemZConstantPoolValue Class Reference
LLVM API Documentation
llvm::SystemZConstantPoolValue Class Reference
#include <SystemZConstantPoolValue.h>
Public Member Functions
unsigned getRelocationInfo () const override
int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
const GlobalValue * getGlobalValue () const
SystemZCP::SystemZCPModifier getModifier () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()
Type * getType () const
Static Public Member Functions
static SystemZConstantPoolValue * Create (const GlobalValue *GV, SystemZCP::SystemZCPModifier Modifier)
Protected Member Functions
SystemZConstantPoolValue (const GlobalValue *GV, SystemZCP::SystemZCPModifier Modifier)
Detailed Description
A SystemZ-specific constant pool value. At present, the only defined constant pool values are offsets of thread-local variables (written x@NTPOFF).
Definition at line 29 of file SystemZConstantPoolValue.h.
Constructor & Destructor Documentation
SystemZConstantPoolValue()
SystemZConstantPoolValue::SystemZConstantPoolValue (const GlobalValue * GV, SystemZCP::SystemZCPModifier Modifier) protected
Definition at line 18 of file SystemZConstantPoolValue.cpp.
References llvm::MachineConstantPoolValue::getType(), and llvm::MachineConstantPoolValue::MachineConstantPoolValue().
Referenced by Create(), and getExistingMachineCPValue().
Member Function Documentation
addSelectionDAGCSEId()
void SystemZConstantPoolValue::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 55 of file SystemZConstantPoolValue.cpp.
Create()
SystemZConstantPoolValue * SystemZConstantPoolValue::Create (const GlobalValue * GV, SystemZCP::SystemZCPModifier Modifier) static
Definition at line 24 of file SystemZConstantPoolValue.cpp.
References SystemZConstantPoolValue().
getExistingMachineCPValue()
int SystemZConstantPoolValue::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 39 of file SystemZConstantPoolValue.cpp.
References llvm::MachineConstantPool::getConstants(), I, and SystemZConstantPoolValue().
getGlobalValue()
const GlobalValue * llvm::SystemZConstantPoolValue::getGlobalValue () const inline
Definition at line 49 of file SystemZConstantPoolValue.h.
getModifier()
SystemZCP::SystemZCPModifier llvm::SystemZConstantPoolValue::getModifier () const inline
Definition at line 50 of file SystemZConstantPoolValue.h.
getRelocationInfo()
unsigned SystemZConstantPoolValue::getRelocationInfo () const override virtual
getRelocationInfo - This method classifies the entry according to whether or not it may generate a relocation entry. This must be conservative, so if it might codegen to a relocatable entry, it should say so. The return values are the same as Constant::getRelocationInfo().
Implements llvm::MachineConstantPoolValue.
Definition at line 29 of file SystemZConstantPoolValue.cpp.
References llvm_unreachable, and llvm::SystemZCP::NTPOFF.
print()
void SystemZConstantPoolValue::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 60 of file SystemZConstantPoolValue.cpp.
The documentation for this class was generated from the following files:
SystemZConstantPoolValue.h
SystemZConstantPoolValue.cpp