LLVM: llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy > Class Template Reference
LLVM API Documentation
llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy > Class Template Reference
#include <MachineBasicBlock.h>
Public Member Functions
bundle_iterator (IterTy mii)
bundle_iterator (Ty &mi)
bundle_iterator (Ty *mi)
template<class OtherTy, class OtherIterTy>
bundle_iterator (const bundle_iterator< OtherTy, OtherIterTy > &I)
bundle_iterator ()
Ty & operator* () const
Ty * operator-> () const
operator Ty * () const
bool operator== (const bundle_iterator &x) const
bool operator!= (const bundle_iterator &x) const
bundle_iterator & operator-- ()
bundle_iterator & operator++ ()
bundle_iterator operator-- (int)
bundle_iterator operator++ (int)
IterTy getInstrIterator () const
Detailed Description
template<typename Ty, typename IterTy>
class llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >
bundle_iterator - MachineBasicBlock iterator that automatically skips over MIs that are inside bundles (i.e. walk top level MIs only).
Definition at line 144 of file MachineBasicBlock.h.
Constructor & Destructor Documentation
bundle_iterator() [1/5]
template<typename Ty, typename IterTy> llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::bundle_iterator (IterTy mii) inline
Definition at line 149 of file MachineBasicBlock.h.
bundle_iterator() [2/5]
template<typename Ty, typename IterTy> llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::bundle_iterator (Ty & mi) inline
Definition at line 151 of file MachineBasicBlock.h.
bundle_iterator() [3/5]
template<typename Ty, typename IterTy> llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::bundle_iterator (Ty * mi) inline
Definition at line 155 of file MachineBasicBlock.h.
bundle_iterator() [4/5]
template<typename Ty, typename IterTy> template<class OtherTy, class OtherIterTy> llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::bundle_iterator (const bundle_iterator< OtherTy, OtherIterTy > & I) inline
Definition at line 161 of file MachineBasicBlock.h.
bundle_iterator() [5/5]
template<typename Ty, typename IterTy> llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::bundle_iterator () inline
Definition at line 163 of file MachineBasicBlock.h.
Member Function Documentation
getInstrIterator()
template<typename Ty, typename IterTy> IterTy llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::getInstrIterator () const inline
Definition at line 200 of file MachineBasicBlock.h.
Referenced by llvm::MachineBasicBlock::erase(), llvm::MachineBasicBlock::findDebugLoc(), and llvm::MachineBasicBlock::splice().
operator Ty *()
template<typename Ty, typename IterTy> llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::operator Ty * () const inline
Definition at line 168 of file MachineBasicBlock.h.
operator!=()
template<typename Ty, typename IterTy> bool llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::operator!= (const bundle_iterator< Ty, IterTy > & x) const inline
Definition at line 173 of file MachineBasicBlock.h.
operator*()
template<typename Ty, typename IterTy> Ty & llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::operator* () const inline
Definition at line 165 of file MachineBasicBlock.h.
Referenced by llvm::MachineBasicBlock::bundle_iterator< MachineInstr, instr_iterator >::operator->().
operator++() [1/2]
template<typename Ty, typename IterTy> bundle_iterator & llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::operator++ () inline
Definition at line 183 of file MachineBasicBlock.h.
operator++() [2/2]
template<typename Ty, typename IterTy> bundle_iterator llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::operator++ (int) inline
Definition at line 194 of file MachineBasicBlock.h.
operator--() [1/2]
template<typename Ty, typename IterTy> bundle_iterator & llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::operator-- () inline
Definition at line 178 of file MachineBasicBlock.h.
operator--() [2/2]
template<typename Ty, typename IterTy> bundle_iterator llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::operator-- (int) inline
Definition at line 189 of file MachineBasicBlock.h.
operator->()
template<typename Ty, typename IterTy> Ty * llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::operator-> () const inline
Definition at line 166 of file MachineBasicBlock.h.
operator==()
template<typename Ty, typename IterTy> bool llvm::MachineBasicBlock::bundle_iterator< Ty, IterTy >::operator== (const bundle_iterator< Ty, IterTy > & x) const inline
Definition at line 170 of file MachineBasicBlock.h.
Referenced by llvm::MachineBasicBlock::bundle_iterator< MachineInstr, instr_iterator >::operator!=().
The documentation for this class was generated from the following file:
MachineBasicBlock.h