LLVM: llvm::IRBuilder< preserveNames, T, Inserter > Class Template Reference
LLVM API Documentation
llvm::IRBuilder< preserveNames, T, Inserter > Class Template Reference
This provides a uniform API for creating instructions and inserting them into a basic block: either at the end of a BasicBlock, or at a specific iterator location in a block.
#include <IRBuilder.h>
Public Member Functions
IRBuilder (LLVMContext &C, const T &F, const Inserter &I=Inserter(), MDNode *FPMathTag=nullptr)
IRBuilder (LLVMContext &C, MDNode *FPMathTag=nullptr)
IRBuilder (BasicBlock *TheBB, const T &F, MDNode *FPMathTag=nullptr)
IRBuilder (BasicBlock *TheBB, MDNode *FPMathTag=nullptr)
IRBuilder (Instruction *IP, MDNode *FPMathTag=nullptr)
IRBuilder (Use &U, MDNode *FPMathTag=nullptr)
IRBuilder (BasicBlock *TheBB, BasicBlock::iterator IP, const T &F, MDNode *FPMathTag=nullptr)
IRBuilder (BasicBlock *TheBB, BasicBlock::iterator IP, MDNode *FPMathTag=nullptr)
const T & getFolder ()
Get the constant folder being used.
bool isNamePreserving () const
Return true if this builder is configured to actually add the requested names to IR created through it.
template<typename InstTy>
InstTy * Insert (InstTy *I, const Twine &Name="") const
Insert and return the specified instruction.
Constant * Insert (Constant *C, const Twine &="") const
No-op overload to handle constants.
ReturnInst * CreateRetVoid ()
Create a 'ret void' instruction.
ReturnInst * CreateRet (Value *V)
Create a 'ret <val>' instruction.
ReturnInst * CreateAggregateRet (Value *const *retVals, unsigned N)
Create a sequence of N insertvalue instructions, with one Value from the retVals array each, that build a aggregate return value one value at a time, and a ret instruction to return the resulting aggregate value.
BranchInst * CreateBr (BasicBlock *Dest)
Create an unconditional 'br label X' instruction.
BranchInst * CreateCondBr (Value *Cond, BasicBlock *True, BasicBlock *False, MDNode *BranchWeights=nullptr)
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
SwitchInst * CreateSwitch (Value *V, BasicBlock *Dest, unsigned NumCases=10, MDNode *BranchWeights=nullptr)
Create a switch instruction with the specified value, default dest, and with a hint for the number of cases that will be added (for efficient allocation).
IndirectBrInst * CreateIndirectBr (Value *Addr, unsigned NumDests=10)
Create an indirect branch instruction with the specified address operand, with an optional hint for the number of destinations that will be added (for efficient allocation).
InvokeInst * CreateInvoke (Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, const Twine &Name="")
InvokeInst * CreateInvoke (Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, Value *Arg1, const Twine &Name="")
InvokeInst * CreateInvoke3 (Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, Value *Arg1, Value *Arg2, Value *Arg3, const Twine &Name="")
InvokeInst * CreateInvoke (Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args, const Twine &Name="")
Create an invoke instruction.
ResumeInst * CreateResume (Value *Exn)
UnreachableInst * CreateUnreachable ()
Value * CreateAdd (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWAdd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWAdd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFAdd (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateSub (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWSub (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWSub (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFSub (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateMul (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWMul (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWMul (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFMul (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateUDiv (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateExactUDiv (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSDiv (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateExactSDiv (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFDiv (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateURem (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSRem (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFRem (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateShl (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateShl (Value *LHS, const APInt &RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateShl (Value *LHS, uint64_t RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateLShr (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateLShr (Value *LHS, const APInt &RHS, const Twine &Name="", bool isExact=false)
Value * CreateLShr (Value *LHS, uint64_t RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, const APInt &RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, uint64_t RHS, const Twine &Name="", bool isExact=false)
Value * CreateAnd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateAnd (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateAnd (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateOr (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateOr (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateOr (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateXor (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateXor (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateXor (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateNeg (Value *V, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWNeg (Value *V, const Twine &Name="")
Value * CreateNUWNeg (Value *V, const Twine &Name="")
Value * CreateFNeg (Value *V, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateNot (Value *V, const Twine &Name="")
AllocaInst * CreateAlloca (Type *Ty, Value *ArraySize=nullptr, const Twine &Name="")
LoadInst * CreateLoad (Value *Ptr, const char *Name)
LoadInst * CreateLoad (Value *Ptr, const Twine &Name="")
LoadInst * CreateLoad (Value *Ptr, bool isVolatile, const Twine &Name="")
StoreInst * CreateStore (Value *Val, Value *Ptr, bool isVolatile=false)
LoadInst * CreateAlignedLoad (Value *Ptr, unsigned Align, const char *Name)
LoadInst * CreateAlignedLoad (Value *Ptr, unsigned Align, const Twine &Name="")
LoadInst * CreateAlignedLoad (Value *Ptr, unsigned Align, bool isVolatile, const Twine &Name="")
StoreInst * CreateAlignedStore (Value *Val, Value *Ptr, unsigned Align, bool isVolatile=false)
FenceInst * CreateFence (AtomicOrdering Ordering, SynchronizationScope SynchScope=CrossThread, const Twine &Name="")
AtomicCmpXchgInst * CreateAtomicCmpXchg (Value *Ptr, Value *Cmp, Value *New, AtomicOrdering SuccessOrdering, AtomicOrdering FailureOrdering, SynchronizationScope SynchScope=CrossThread)
AtomicRMWInst * CreateAtomicRMW (AtomicRMWInst::BinOp Op, Value *Ptr, Value *Val, AtomicOrdering Ordering, SynchronizationScope SynchScope=CrossThread)
Value * CreateGEP (Value *Ptr, ArrayRef< Value * > IdxList, const Twine &Name="")
Value * CreateInBoundsGEP (Value *Ptr, ArrayRef< Value * > IdxList, const Twine &Name="")
Value * CreateGEP (Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateInBoundsGEP (Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateConstGEP1_32 (Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_32 (Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstGEP2_32 (Value *Ptr, unsigned Idx0, unsigned Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_32 (Value *Ptr, unsigned Idx0, unsigned Idx1, const Twine &Name="")
Value * CreateConstGEP1_64 (Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_64 (Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstGEP2_64 (Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_64 (Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateStructGEP (Value *Ptr, unsigned Idx, const Twine &Name="")
Value * CreateGlobalStringPtr (StringRef Str, const Twine &Name="")
Same as CreateGlobalString, but return a pointer with "i8*" type instead of a pointer to array of i8.
Value * CreateTrunc (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExtOrTrunc (Value *V, Type *DestTy, const Twine &Name="")
Create a ZExt or Trunc from the integer value V to DestTy. Return the value untouched if the type of V is already DestTy.
Value * CreateSExtOrTrunc (Value *V, Type *DestTy, const Twine &Name="")
Create a SExt or Trunc from the integer value V to DestTy. Return the value untouched if the type of V is already DestTy.
Value * CreateFPToUI (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPToSI (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateUIToFP (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSIToFP (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPTrunc (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePtrToInt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateIntToPtr (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateAddrSpaceCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExtOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSExtOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateTruncOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateCast (Instruction::CastOps Op, Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePointerCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePointerBitCastOrAddrSpaceCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateIntCast (Value *V, Type *DestTy, bool isSigned, const Twine &Name="")
Value * CreateBitOrPointerCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateICmpEQ (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpNE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpUGT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpUGE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpULT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpULE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSGT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSGE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSLT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSLE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpOEQ (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpOGT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpOGE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpOLT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpOLE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpONE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpORD (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpUNO (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpUEQ (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpUGT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpUGE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpULT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpULE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpUNE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmp (CmpInst::Predicate P, Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmp (CmpInst::Predicate P, Value *LHS, Value *RHS, const Twine &Name="")
PHINode * CreatePHI (Type *Ty, unsigned NumReservedValues, const Twine &Name="")
CallInst * CreateCall (Value *Callee, const Twine &Name="")
CallInst * CreateCall (Value *Callee, Value *Arg, const Twine &Name="")
CallInst * CreateCall2 (Value *Callee, Value *Arg1, Value *Arg2, const Twine &Name="")
CallInst * CreateCall3 (Value *Callee, Value *Arg1, Value *Arg2, Value *Arg3, const Twine &Name="")
CallInst * CreateCall4 (Value *Callee, Value *Arg1, Value *Arg2, Value *Arg3, Value *Arg4, const Twine &Name="")
CallInst * CreateCall5 (Value *Callee, Value *Arg1, Value *Arg2, Value *Arg3, Value *Arg4, Value *Arg5, const Twine &Name="")
CallInst * CreateCall (Value *Callee, ArrayRef< Value * > Args, const Twine &Name="")
Value * CreateSelect (Value *C, Value *True, Value *False, const Twine &Name="")
VAArgInst * CreateVAArg (Value *List, Type *Ty, const Twine &Name="")
Value * CreateExtractElement (Value *Vec, Value *Idx, const Twine &Name="")
Value * CreateInsertElement (Value *Vec, Value *NewElt, Value *Idx, const Twine &Name="")
Value * CreateShuffleVector (Value *V1, Value *V2, Value *Mask, const Twine &Name="")
Value * CreateExtractValue (Value *Agg, ArrayRef< unsigned > Idxs, const Twine &Name="")
Value * CreateInsertValue (Value *Agg, Value *Val, ArrayRef< unsigned > Idxs, const Twine &Name="")
LandingPadInst * CreateLandingPad (Type *Ty, Value *PersFn, unsigned NumClauses, const Twine &Name="")
Value * CreateIsNull (Value *Arg, const Twine &Name="")
Return an i1 value testing if Arg is null.
Value * CreateIsNotNull (Value *Arg, const Twine &Name="")
Return an i1 value testing if Arg is not null.
Value * CreatePtrDiff (Value *LHS, Value *RHS, const Twine &Name="")
Return the i64 difference between two pointer values, dividing out the size of the pointed-to objects.
Value * CreateVectorSplat (unsigned NumElts, Value *V, const Twine &Name="")
Return a vector value that contains.
Value * CreateExtractInteger (const DataLayout &DL, Value *From, IntegerType *ExtractedTy, uint64_t Offset, const Twine &Name)
Return a value that has been extracted from a larger integer type.
CallInst * CreateAlignmentAssumption (const DataLayout &DL, Value *PtrValue, unsigned Alignment, Value *OffsetValue=nullptr)
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
Public Member Functions inherited from llvm::IRBuilderBase
IRBuilderBase (LLVMContext &context, MDNode *FPMathTag=nullptr)
void ClearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
BasicBlock * GetInsertBlock () const
BasicBlock::iterator GetInsertPoint () const
LLVMContext & getContext () const
void SetInsertPoint (BasicBlock *TheBB)
This specifies that created instructions should be appended to the end of the specified block.
void SetInsertPoint (Instruction *I)
This specifies that created instructions should be inserted before the specified instruction.
void SetInsertPoint (BasicBlock *TheBB, BasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
void SetInsertPoint (Use &U)
Find the nearest point that dominates this use, and specify that created instructions should be inserted at this point.
void SetCurrentDebugLocation (const DebugLoc &L)
Set location information used by debugging information.
DebugLoc getCurrentDebugLocation () const
Get location information used by debugging information.
void SetInstDebugLocation (Instruction *I) const
If this builder has a current debug location, set it on the specified instruction.
Type * getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
InsertPoint saveIP () const
Returns the current insert point.
InsertPoint saveAndClearIP ()
Returns the current insert point, clearing it in the process.
void restoreIP (InsertPoint IP)
Sets the current insert point to a previously-saved location.
MDNode * getDefaultFPMathTag () const
Get the floating point math metadata being used.
FastMathFlags getFastMathFlags () const
Get the flags to be applied to created floating point ops.
void clearFastMathFlags ()
Clear the fast-math flags.
void SetDefaultFPMathTag (MDNode *FPMathTag)
Set the floating point math metadata to be used.
void SetFastMathFlags (FastMathFlags NewFMF)
Set the fast-math flags to be used with generated fp-math operators.
Value * CreateGlobalString (StringRef Str, const Twine &Name="")
Make a new global variable with initializer type i8*.
ConstantInt * getInt1 (bool V)
Get a constant value representing either true or false.
ConstantInt * getTrue ()
Get the constant value for i1 true.
ConstantInt * getFalse ()
Get the constant value for i1 false.
ConstantInt * getInt8 (uint8_t C)
Get a constant 8-bit value.
ConstantInt * getInt16 (uint16_t C)
Get a constant 16-bit value.
ConstantInt * getInt32 (uint32_t C)
Get a constant 32-bit value.
ConstantInt * getInt64 (uint64_t C)
Get a constant 64-bit value.
ConstantInt * getIntN (unsigned N, uint64_t C)
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
ConstantInt * getInt (const APInt &AI)
Get a constant integer value.
IntegerType * getInt1Ty ()
Fetch the type representing a single bit.
IntegerType * getInt8Ty ()
Fetch the type representing an 8-bit integer.
IntegerType * getInt16Ty ()
Fetch the type representing a 16-bit integer.
IntegerType * getInt32Ty ()
Fetch the type representing a 32-bit integer.
IntegerType * getInt64Ty ()
Fetch the type representing a 64-bit integer.
IntegerType * getIntNTy (unsigned N)
Fetch the type representing an N-bit integer.
Type * getHalfTy ()
Fetch the type representing a 16-bit floating point value.
Type * getFloatTy ()
Fetch the type representing a 32-bit floating point value.
Type * getDoubleTy ()
Fetch the type representing a 64-bit floating point value.
Type * getVoidTy ()
Fetch the type representing void.
PointerType * getInt8PtrTy (unsigned AddrSpace=0)
Fetch the type representing a pointer to an 8-bit integer value.
IntegerType * getIntPtrTy (const DataLayout *DL, unsigned AddrSpace=0)
Fetch the type representing a pointer to an integer value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memset to the specified pointer and the specified value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemCpy (Value *Dst, Value *Src, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memcpy between the specified pointers.
CallInst * CreateMemCpy (Value *Dst, Value *Src, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemMove (Value *Dst, Value *Src, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memmove between the specified pointers.
CallInst * CreateMemMove (Value *Dst, Value *Src, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateLifetimeStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.start intrinsic.
CallInst * CreateLifetimeEnd (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.end intrinsic.
CallInst * CreateMaskedLoad (Value *Ptr, unsigned Align, Value *Mask, Value *PassThru=0, const Twine &Name="")
Create a call to Masked Load intrinsic.
CallInst * CreateMaskedStore (Value *Val, Value *Ptr, unsigned Align, Value *Mask)
Create a call to Masked Store intrinsic.
CallInst * CreateAssumption (Value *Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
CallInst * CreateGCStatepoint (Value *ActualCallee, ArrayRef< Value * > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCResult (Instruction *Statepoint, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
CallInst * CreateGCRelocate (Instruction *Statepoint, int BaseOffset, int DerivedOffset, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
Additional Inherited Members
Protected Member Functions inherited from llvm::IRBuilderDefaultInserter< preserveNames >
void InsertHelper (Instruction *I, const Twine &Name, BasicBlock *BB, BasicBlock::iterator InsertPt) const
Protected Attributes inherited from llvm::IRBuilderBase
BasicBlock * BB
BasicBlock::iterator InsertPt
LLVMContext & Context
MDNode * DefaultFPMathTag
FastMathFlags FMF
Detailed Description
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>>
class llvm::IRBuilder< preserveNames, T, Inserter >
This provides a uniform API for creating instructions and inserting them into a basic block: either at the end of a BasicBlock, or at a specific iterator location in a block.
Note that the builder does not expose the full generality of LLVM instructions. For access to extra instruction properties, use the mutators (e.g. setVolatile) on the instructions after they have been created. Convenience state exists to specify fast-math flags and fp-math tags.
The first template argument handles whether or not to preserve names in the final instruction output. This defaults to on. The second template argument specifies a class to use for creating constants. This defaults to creating minimally folded constants. The third template argument allows clients to specify custom insertion hooks that are called on every newly created insertion.
Definition at line 493 of file IRBuilder.h.
Constructor & Destructor Documentation
IRBuilder() [1/8]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> llvm::IRBuilder< preserveNames, T, Inserter >::IRBuilder (LLVMContext & C, const T & F, const Inserter & I = Inserter(), MDNode * FPMathTag = nullptr) inline
Definition at line 496 of file IRBuilder.h.
IRBuilder() [2/8]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> llvm::IRBuilder< preserveNames, T, Inserter >::IRBuilder (LLVMContext & C, MDNode * FPMathTag = nullptr) inline explicit
Definition at line 501 of file IRBuilder.h.
IRBuilder() [3/8]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> llvm::IRBuilder< preserveNames, T, Inserter >::IRBuilder (BasicBlock * TheBB, const T & F, MDNode * FPMathTag = nullptr) inline explicit
Definition at line 505 of file IRBuilder.h.
IRBuilder() [4/8]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> llvm::IRBuilder< preserveNames, T, Inserter >::IRBuilder (BasicBlock * TheBB, MDNode * FPMathTag = nullptr) inline explicit
Definition at line 510 of file IRBuilder.h.
IRBuilder() [5/8]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> llvm::IRBuilder< preserveNames, T, Inserter >::IRBuilder (Instruction * IP, MDNode * FPMathTag = nullptr) inline explicit
Definition at line 515 of file IRBuilder.h.
IRBuilder() [6/8]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> llvm::IRBuilder< preserveNames, T, Inserter >::IRBuilder (Use & U, MDNode * FPMathTag = nullptr) inline explicit
Definition at line 521 of file IRBuilder.h.
IRBuilder() [7/8]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> llvm::IRBuilder< preserveNames, T, Inserter >::IRBuilder (BasicBlock * TheBB, BasicBlock::iterator IP, const T & F, MDNode * FPMathTag = nullptr) inline
Definition at line 527 of file IRBuilder.h.
IRBuilder() [8/8]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> llvm::IRBuilder< preserveNames, T, Inserter >::IRBuilder (BasicBlock * TheBB, BasicBlock::iterator IP, MDNode * FPMathTag = nullptr) inline
Definition at line 533 of file IRBuilder.h.
Member Function Documentation
CreateAdd()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAdd (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 687 of file IRBuilder.h.
Referenced by convertMemSetToLoop(), convertTransferToLoop(), llvm::IRBuilder< true, TargetFolder >::CreateNSWAdd(), llvm::IRBuilder< true, TargetFolder >::CreateNUWAdd(), EvaluateGEPOffsetExpression(), foldSelectICmpAnd(), foldUDivShl(), generateUnsignedDivisionCode(), LowerAtomicRMWInst(), LowerCTPOP(), performAtomicOp(), and TurnSwitchRangeIntoICmp().
CreateAddrSpaceCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAddrSpaceCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1217 of file IRBuilder.h.
CreateAggregateRet()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> ReturnInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAggregateRet (Value *const * retVals, unsigned N) inline
Create a sequence of N insertvalue instructions, with one Value from the retVals array each, that build a aggregate return value one value at a time, and a ret instruction to return the resulting aggregate value.
This is a convenience function for code that uses aggregate return values as a vehicle for having multiple return values.
Definition at line 591 of file IRBuilder.h.
CreateAlignedLoad() [1/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> LoadInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAlignedLoad (Value * Ptr, unsigned Align, bool isVolatile, const Twine & Name = "") inline
Definition at line 982 of file IRBuilder.h.
CreateAlignedLoad() [2/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> LoadInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAlignedLoad (Value * Ptr, unsigned Align, const char * Name) inline
Definition at line 971 of file IRBuilder.h.
Referenced by combineLoadToNewType().
CreateAlignedLoad() [3/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> LoadInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAlignedLoad (Value * Ptr, unsigned Align, const Twine & Name = "") inline
Definition at line 976 of file IRBuilder.h.
CreateAlignedStore()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> StoreInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAlignedStore (Value * Val, Value * Ptr, unsigned Align, bool isVolatile = false) inline
Definition at line 988 of file IRBuilder.h.
Referenced by combineStoreToValueType().
CreateAlignmentAssumption()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> CallInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAlignmentAssumption (const DataLayout & DL, Value * PtrValue, unsigned Alignment, Value * OffsetValue = nullptr) inline
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
An optional offset can be provided, and if it is provided, the offset must be subtracted from the provided pointer to get the pointer with the specified alignment.
Definition at line 1585 of file IRBuilder.h.
Referenced by AddAlignmentAssumptions().
CreateAlloca()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> AllocaInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAlloca (Type * Ty, Value * ArraySize = nullptr, const Twine & Name = "") inline
Definition at line 950 of file IRBuilder.h.
Referenced by CreatePrologue().
CreateAnd() [1/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAnd (Value * LHS, const APInt & RHS, const Twine & Name = "") inline
Definition at line 870 of file IRBuilder.h.
CreateAnd() [2/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAnd (Value * LHS, uint64_t RHS, const Twine & Name = "") inline
Definition at line 873 of file IRBuilder.h.
CreateAnd() [3/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAnd (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 861 of file IRBuilder.h.
Referenced by checkForNegativeOperand(), llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption(), llvm::IRBuilder< true, TargetFolder >::CreateAnd(), llvm::IRBuilder< true, TargetFolder >::CreateAnd(), foldLogOpOfMaskedICmps(), generateUnsignedDivisionCode(), GetShiftedValue(), insertFastDiv(), LowerAtomicRMWInst(), LowerBSWAP(), LowerCTPOP(), llvm::IntrinsicLowering::LowerIntrinsicCall(), performAtomicOp(), ProcessUMulZExtIdiom(), and llvm::UnrollRuntimeLoopProlog().
CreateAShr() [1/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAShr (Value * LHS, const APInt & RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 852 of file IRBuilder.h.
CreateAShr() [2/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAShr (Value * LHS, uint64_t RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 856 of file IRBuilder.h.
CreateAShr() [3/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAShr (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 843 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAShr(), llvm::IRBuilder< true, TargetFolder >::CreateAShr(), generateSignedDivisionCode(), generateSignedRemainderCode(), and generateUnsignedDivisionCode().
CreateAtomicCmpXchg()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> AtomicCmpXchgInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAtomicCmpXchg (Value * Ptr, Value * Cmp, Value * New, AtomicOrdering SuccessOrdering, AtomicOrdering FailureOrdering, SynchronizationScope SynchScope = CrossThread) inline
Definition at line 1000 of file IRBuilder.h.
CreateAtomicRMW()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> AtomicRMWInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateAtomicRMW (AtomicRMWInst::BinOp Op, Value * Ptr, Value * Val, AtomicOrdering Ordering, SynchronizationScope SynchScope = CrossThread) inline
Definition at line 1007 of file IRBuilder.h.
CreateBinOp()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateBinOp (Instruction::BinaryOps Opc, Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 906 of file IRBuilder.h.
Referenced by CreateBinOpAsGiven(), createReplacementInstr(), llvm::FoldBranchToCommonDest(), FoldOperationIntoSelectOperand(), and tryFactorization().
CreateBitCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1213 of file IRBuilder.h.
Referenced by llvm::CastToCStr(), combineLoadToNewType(), combineStoreToValueType(), convertMemSetToLoop(), convertTransferToLoop(), llvm::IRBuilder< true, TargetFolder >::CreateBitOrPointerCast(), createCast(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), GetLoadValueForLoad(), GetStoreValueForLoad(), llvm::InlineFunction(), OptimizeIntToFloatBitCast(), OptimizeVectorResize(), ScalarizeMaskedLoad(), ScalarizeMaskedStore(), tryPromoteAllocaToVector(), and llvm::UpgradeIntrinsicCall().
CreateBitOrPointerCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitOrPointerCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1285 of file IRBuilder.h.
CreateBr()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> BranchInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateBr (BasicBlock * Dest) inline
Create an unconditional 'br label X' instruction.
Definition at line 599 of file IRBuilder.h.
Referenced by llvm::ConstantFoldTerminator(), FoldTwoEntryPHINode(), generateUnsignedDivisionCode(), insertFastDiv(), RemoveSwitchAfterSelectConversion(), removeUndefIntroducingPredecessor(), SimplifyTerminatorOnSelect(), SwitchToLookupTable(), and TryToSimplifyUncondBranchWithICmpInIt().
CreateCall() [1/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> CallInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall (Value * Callee, ArrayRef< Value * > Args, const Twine & Name = "") inline
Definition at line 1439 of file IRBuilder.h.
CreateCall() [2/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> CallInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall (Value * Callee, const Twine & Name = "") inline
Definition at line 1412 of file IRBuilder.h.
Referenced by callIntrinsic(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::EmitStrLen(), llvm::EmitUnaryFloatFnCall(), llvm::InlineFunction(), insertSinCosCall(), llvm::ARMTargetLowering::makeDMB(), ReplaceCallWith(), and llvm::UpgradeIntrinsicCall().
CreateCall() [3/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> CallInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall (Value * Callee, Value * Arg, const Twine & Name = "") inline
Definition at line 1415 of file IRBuilder.h.
CreateCall2()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> CallInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall2 (Value * Callee, Value * Arg1, Value * Arg2, const Twine & Name = "") inline
Definition at line 1418 of file IRBuilder.h.
Referenced by CreatePrologue(), llvm::EmitBinaryFloatFnCall(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrNLen(), GenerateARCBBEntranceAnnotation(), GenerateARCBBTerminatorAnnotation(), generateUnsignedDivisionCode(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), and llvm::UpgradeIntrinsicCall().
CreateCall3()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> CallInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall3 (Value * Callee, Value * Arg1, Value * Arg2, Value * Arg3, const Twine & Name = "") inline
Definition at line 1423 of file IRBuilder.h.
Referenced by llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), and llvm::UpgradeIntrinsicCall().
CreateCall4()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> CallInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall4 (Value * Callee, Value * Arg1, Value * Arg2, Value * Arg3, Value * Arg4, const Twine & Name = "") inline
Definition at line 1428 of file IRBuilder.h.
Referenced by llvm::EmitFWrite(), llvm::EmitMemCpyChk(), and llvm::UpgradeIntrinsicCall().
CreateCall5()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> CallInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall5 (Value * Callee, Value * Arg1, Value * Arg2, Value * Arg3, Value * Arg4, Value * Arg5, const Twine & Name = "") inline
Definition at line 1433 of file IRBuilder.h.
CreateCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateCast (Instruction::CastOps Op, Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1245 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAddrSpaceCast(), llvm::IRBuilder< true, TargetFolder >::CreateBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateFPExt(), llvm::IRBuilder< true, TargetFolder >::CreateFPToSI(), llvm::IRBuilder< true, TargetFolder >::CreateFPToUI(), llvm::IRBuilder< true, TargetFolder >::CreateFPTrunc(), llvm::IRBuilder< true, TargetFolder >::CreateIntToPtr(), llvm::IRBuilder< true, TargetFolder >::CreatePtrToInt(), createReplacementInstr(), llvm::IRBuilder< true, TargetFolder >::CreateSExt(), llvm::IRBuilder< true, TargetFolder >::CreateSIToFP(), llvm::IRBuilder< true, TargetFolder >::CreateTrunc(), llvm::IRBuilder< true, TargetFolder >::CreateUIToFP(), llvm::IRBuilder< true, TargetFolder >::CreateZExt(), FoldOperationIntoSelectOperand(), and insertFastDiv().
CreateCondBr()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> BranchInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateCondBr (Value * Cond, BasicBlock * True, BasicBlock * False, MDNode * BranchWeights = nullptr) inline
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
Definition at line 605 of file IRBuilder.h.
Referenced by llvm::ConstantFoldTerminator(), convertMemSetToLoop(), convertTransferToLoop(), generateUnsignedDivisionCode(), insertFastDiv(), SimplifyBranchOnICmpChain(), SimplifyTerminatorOnSelect(), SwitchToLookupTable(), and TurnSwitchRangeIntoICmp().
CreateConstGEP1_32()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstGEP1_32 (Value * Ptr, unsigned Idx0, const Twine & Name = "") inline
Definition at line 1050 of file IRBuilder.h.
CreateConstGEP1_64()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstGEP1_64 (Value * Ptr, uint64_t Idx0, const Twine & Name = "") inline
Definition at line 1091 of file IRBuilder.h.
CreateConstGEP2_32()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstGEP2_32 (Value * Ptr, unsigned Idx0, unsigned Idx1, const Twine & Name = "") inline
Definition at line 1067 of file IRBuilder.h.
CreateConstGEP2_64()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstGEP2_64 (Value * Ptr, uint64_t Idx0, uint64_t Idx1, const Twine & Name = "") inline
Definition at line 1108 of file IRBuilder.h.
CreateConstInBoundsGEP1_32()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstInBoundsGEP1_32 (Value * Ptr, unsigned Idx0, const Twine & Name = "") inline
Definition at line 1058 of file IRBuilder.h.
CreateConstInBoundsGEP1_64()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstInBoundsGEP1_64 (Value * Ptr, uint64_t Idx0, const Twine & Name = "") inline
Definition at line 1099 of file IRBuilder.h.
CreateConstInBoundsGEP2_32()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstInBoundsGEP2_32 (Value * Ptr, unsigned Idx0, unsigned Idx1, const Twine & Name = "") inline
Definition at line 1079 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateStructGEP().
CreateConstInBoundsGEP2_64()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstInBoundsGEP2_64 (Value * Ptr, uint64_t Idx0, uint64_t Idx1, const Twine & Name = "") inline
Definition at line 1120 of file IRBuilder.h.
CreateExactSDiv()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateExactSDiv (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 774 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreatePtrDiff().
CreateExactUDiv()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateExactUDiv (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 762 of file IRBuilder.h.
Referenced by insertFastDiv().
CreateExtractElement()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateExtractElement (Value * Vec, Value * Idx, const Twine & Name = "") inline
Definition at line 1457 of file IRBuilder.h.
Referenced by insertSinCosCall(), ScalarizeMaskedLoad(), ScalarizeMaskedStore(), and tryPromoteAllocaToVector().
CreateExtractInteger()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateExtractInteger (const DataLayout & DL, Value * From, IntegerType * ExtractedTy, uint64_t Offset, const Twine & Name) inline
Return a value that has been extracted from a larger integer type.
Definition at line 1556 of file IRBuilder.h.
CreateExtractValue()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateExtractValue (Value * Agg, ArrayRef< unsigned > Idxs, const Twine & Name = "") inline
Definition at line 1483 of file IRBuilder.h.
Referenced by createCast(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), insertSinCosCall(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), and ProcessUMulZExtIdiom().
CreateFAdd()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFAdd (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 701 of file IRBuilder.h.
CreateFCmp()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmp (CmpInst::Predicate P, Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1395 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateFCmpOEQ(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpOGE(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpOGT(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpOLE(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpOLT(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpONE(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpORD(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpUEQ(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpUGE(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpUGT(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpULE(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpULT(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpUNE(), llvm::IRBuilder< true, TargetFolder >::CreateFCmpUNO(), createMinMaxOp(), and getFCmpValue().
CreateFCmpOEQ()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpOEQ (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1345 of file IRBuilder.h.
CreateFCmpOGE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpOGE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1351 of file IRBuilder.h.
CreateFCmpOGT()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpOGT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1348 of file IRBuilder.h.
CreateFCmpOLE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpOLE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1357 of file IRBuilder.h.
CreateFCmpOLT()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpOLT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1354 of file IRBuilder.h.
CreateFCmpONE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpONE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1360 of file IRBuilder.h.
CreateFCmpORD()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpORD (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1363 of file IRBuilder.h.
CreateFCmpUEQ()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpUEQ (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1369 of file IRBuilder.h.
CreateFCmpUGE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpUGE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1375 of file IRBuilder.h.
CreateFCmpUGT()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpUGT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1372 of file IRBuilder.h.
CreateFCmpULE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpULE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1381 of file IRBuilder.h.
CreateFCmpULT()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpULT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1378 of file IRBuilder.h.
CreateFCmpUNE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpUNE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1384 of file IRBuilder.h.
CreateFCmpUNO()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmpUNO (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1366 of file IRBuilder.h.
CreateFDiv()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFDiv (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 777 of file IRBuilder.h.
CreateFence()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> FenceInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFence (AtomicOrdering Ordering, SynchronizationScope SynchScope = CrossThread, const Twine & Name = "") inline
Definition at line 994 of file IRBuilder.h.
Referenced by llvm::TargetLoweringBase::emitLeadingFence(), and llvm::TargetLoweringBase::emitTrailingFence().
CreateFMul()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFMul (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 745 of file IRBuilder.h.
Referenced by buildMultiplyTree().
CreateFNeg()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFNeg (Value * V, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 933 of file IRBuilder.h.
CreateFPCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFPCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1302 of file IRBuilder.h.
CreateFPExt()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFPExt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1202 of file IRBuilder.h.
CreateFPToSI()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFPToSI (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1189 of file IRBuilder.h.
CreateFPToUI()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFPToUI (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1186 of file IRBuilder.h.
CreateFPTrunc()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFPTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1198 of file IRBuilder.h.
CreateFRem()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFRem (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 797 of file IRBuilder.h.
CreateFSub()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateFSub (Value * LHS, Value * RHS, const Twine & Name = "", MDNode * FPMathTag = nullptr) inline
Definition at line 723 of file IRBuilder.h.
CreateGEP() [1/2]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateGEP (Value * Ptr, ArrayRef< Value * > IdxList, const Twine & Name = "") inline
Definition at line 1012 of file IRBuilder.h.
Referenced by convertMemSetToLoop(), convertTransferToLoop(), and genLoopLimit().
CreateGEP() [2/2]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateGEP (Value * Ptr, Value * Idx, const Twine & Name = "") inline
Definition at line 1038 of file IRBuilder.h.
CreateGlobalStringPtr()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateGlobalStringPtr (StringRef Str, const Twine & Name = "") inline
Same as CreateGlobalString, but return a pointer with "i8*" type instead of a pointer to array of i8.
Definition at line 1138 of file IRBuilder.h.
Referenced by GenerateARCBBEntranceAnnotation(), and GenerateARCBBTerminatorAnnotation().
CreateICmp()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmp (CmpInst::Predicate P, Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1388 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateICmpEQ(), llvm::IRBuilder< true, TargetFolder >::CreateICmpNE(), llvm::IRBuilder< true, TargetFolder >::CreateICmpSGE(), llvm::IRBuilder< true, TargetFolder >::CreateICmpSGT(), llvm::IRBuilder< true, TargetFolder >::CreateICmpSLE(), llvm::IRBuilder< true, TargetFolder >::CreateICmpSLT(), llvm::IRBuilder< true, TargetFolder >::CreateICmpUGE(), llvm::IRBuilder< true, TargetFolder >::CreateICmpUGT(), llvm::IRBuilder< true, TargetFolder >::CreateICmpULE(), llvm::IRBuilder< true, TargetFolder >::CreateICmpULT(), createMinMaxOp(), foldLogOpOfMaskedICmps(), FoldOperationIntoSelectOperand(), getNewICmpValue(), ScalarizeMaskedLoad(), and ScalarizeMaskedStore().
CreateICmpEQ()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpEQ (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1314 of file IRBuilder.h.
Referenced by llvm::ConstantFoldTerminator(), ConvertTwoCaseSwitch(), llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption(), llvm::IRBuilder< true, TargetFolder >::CreateIsNull(), generateUnsignedDivisionCode(), insertFastDiv(), LowerAtomicCmpXchgInst(), and llvm::UpgradeIntrinsicCall().
CreateICmpNE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpNE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1317 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateIsNotNull().
CreateICmpSGE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpSGE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1335 of file IRBuilder.h.
CreateICmpSGT()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpSGT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1332 of file IRBuilder.h.
Referenced by performAtomicOp(), and llvm::UpgradeIntrinsicCall().
CreateICmpSLE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpSLE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1341 of file IRBuilder.h.
Referenced by performAtomicOp().
CreateICmpSLT()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpSLT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1338 of file IRBuilder.h.
Referenced by LowerAtomicRMWInst().
CreateICmpUGE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpUGE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1323 of file IRBuilder.h.
CreateICmpUGT()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpUGT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1320 of file IRBuilder.h.
Referenced by generateUnsignedDivisionCode(), and performAtomicOp().
CreateICmpULE()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpULE (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1329 of file IRBuilder.h.
Referenced by performAtomicOp().
CreateICmpULT()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpULT (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 1326 of file IRBuilder.h.
Referenced by convertMemSetToLoop(), convertTransferToLoop(), foldUDivNegCst(), LowerAtomicRMWInst(), SwitchToLookupTable(), and TurnSwitchRangeIntoICmp().
CreateInBoundsGEP() [1/2]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateInBoundsGEP (Value * Ptr, ArrayRef< Value * > IdxList, const Twine & Name = "") inline
Definition at line 1025 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateGlobalStringPtr(), createReplacementInstr(), ScalarizeMaskedLoad(), and ScalarizeMaskedStore().
CreateInBoundsGEP() [2/2]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateInBoundsGEP (Value * Ptr, Value * Idx, const Twine & Name = "") inline
Definition at line 1044 of file IRBuilder.h.
CreateIndirectBr()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> IndirectBrInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateIndirectBr (Value * Addr, unsigned NumDests = 10) inline
Create an indirect branch instruction with the specified address operand, with an optional hint for the number of destinations that will be added (for efficient allocation).
Definition at line 623 of file IRBuilder.h.
CreateInsertElement()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateInsertElement (Value * Vec, Value * NewElt, Value * Idx, const Twine & Name = "") inline
Definition at line 1465 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateVectorSplat(), OptimizeIntegerToVectorInsertions(), ScalarizeMaskedLoad(), tryPromoteAllocaToVector(), and llvm::UpgradeIntrinsicCall().
CreateInsertValue()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateInsertValue (Value * Agg, Value * Val, ArrayRef< unsigned > Idxs, const Twine & Name = "") inline
Definition at line 1491 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAggregateRet(), createCast(), and LowerAtomicCmpXchgInst().
CreateIntCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateIntCast (Value * V, Type * DestTy, bool isSigned, const Twine & Name = "") inline
Definition at line 1276 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption(), llvm::EmitFPutC(), llvm::EmitPutChar(), EvaluateGEPOffsetExpression(), and llvm::IntrinsicLowering::LowerIntrinsicCall().
CreateIntToPtr()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateIntToPtr (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1209 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateBitOrPointerCast(), and createCast().
CreateInvoke() [1/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> InvokeInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateInvoke (Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, ArrayRef< Value * > Args, const Twine & Name = "") inline
Create an invoke instruction.
Definition at line 647 of file IRBuilder.h.
CreateInvoke() [2/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> InvokeInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateInvoke (Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, const Twine & Name = "") inline
Definition at line 627 of file IRBuilder.h.
CreateInvoke() [3/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> InvokeInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateInvoke (Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, Value * Arg1, const Twine & Name = "") inline
Definition at line 632 of file IRBuilder.h.
CreateInvoke3()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> InvokeInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateInvoke3 (Value * Callee, BasicBlock * NormalDest, BasicBlock * UnwindDest, Value * Arg1, Value * Arg2, Value * Arg3, const Twine & Name = "") inline
Definition at line 638 of file IRBuilder.h.
CreateIsNotNull()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateIsNotNull (Value * Arg, const Twine & Name = "") inline
Return an i1 value testing if Arg is not null.
Definition at line 1516 of file IRBuilder.h.
Referenced by CloneLoopBlocks(), and llvm::UnrollRuntimeLoopProlog().
CreateIsNull()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateIsNull (Value * Arg, const Twine & Name = "") inline
Return an i1 value testing if Arg is null.
Definition at line 1510 of file IRBuilder.h.
CreateLandingPad()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> LandingPadInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateLandingPad (Type * Ty, Value * PersFn, unsigned NumClauses, const Twine & Name = "") inline
Definition at line 1500 of file IRBuilder.h.
CreateLoad() [1/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> LoadInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateLoad (Value * Ptr, bool isVolatile, const Twine & Name = "") inline
Definition at line 962 of file IRBuilder.h.
CreateLoad() [2/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> LoadInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateLoad (Value * Ptr, const char * Name) inline
Definition at line 956 of file IRBuilder.h.
Referenced by convertTransferToLoop(), llvm::IRBuilder< true, TargetFolder >::CreateAlignedLoad(), llvm::IRBuilder< true, TargetFolder >::CreateAlignedLoad(), llvm::IRBuilder< true, TargetFolder >::CreateAlignedLoad(), CreatePrologue(), GetLoadValueForLoad(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), ScalarizeMaskedLoad(), tryPromoteAllocaToVector(), tryToMakeAllocaBePromotable(), and llvm::UpgradeIntrinsicCall().
CreateLoad() [3/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> LoadInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateLoad (Value * Ptr, const Twine & Name = "") inline
Definition at line 959 of file IRBuilder.h.
CreateLShr() [1/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateLShr (Value * LHS, const APInt & RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 834 of file IRBuilder.h.
CreateLShr() [2/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateLShr (Value * LHS, uint64_t RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 838 of file IRBuilder.h.
CreateLShr() [3/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateLShr (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 825 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateExtractInteger(), llvm::IRBuilder< true, TargetFolder >::CreateLShr(), llvm::IRBuilder< true, TargetFolder >::CreateLShr(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), foldSelectICmpAnd(), foldSelectICmpAndOr(), generateUnsignedDivisionCode(), GetLoadValueForLoad(), GetShiftedValue(), GetStoreValueForLoad(), LowerBSWAP(), LowerCTLZ(), LowerCTPOP(), and SwitchToLookupTable().
CreateMul()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateMul (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 731 of file IRBuilder.h.
Referenced by buildMultiplyTree(), llvm::IRBuilder< true, TargetFolder >::CreateNSWMul(), llvm::IRBuilder< true, TargetFolder >::CreateNUWMul(), and generatedUnsignedRemainderCode().
CreateNeg()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateNeg (Value * V, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 918 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateNSWNeg(), and llvm::IRBuilder< true, TargetFolder >::CreateNUWNeg().
CreateNot()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateNot (Value * V, const Twine & Name = "") inline
Definition at line 940 of file IRBuilder.h.
Referenced by llvm::FoldBranchToCommonDest(), LowerAtomicRMWInst(), LowerCTLZ(), llvm::IntrinsicLowering::LowerIntrinsicCall(), performAtomicOp(), and SimplifyCondBranchToCondBranch().
CreateNSWAdd()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateNSWAdd (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 695 of file IRBuilder.h.
CreateNSWMul()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateNSWMul (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 739 of file IRBuilder.h.
CreateNSWNeg()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateNSWNeg (Value * V, const Twine & Name = "") inline
Definition at line 927 of file IRBuilder.h.
CreateNSWSub()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateNSWSub (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 717 of file IRBuilder.h.
CreateNUWAdd()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateNUWAdd (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 698 of file IRBuilder.h.
CreateNUWMul()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateNUWMul (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 742 of file IRBuilder.h.
CreateNUWNeg()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateNUWNeg (Value * V, const Twine & Name = "") inline
Definition at line 930 of file IRBuilder.h.
CreateNUWSub()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateNUWSub (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 720 of file IRBuilder.h.
CreateOr() [1/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateOr (Value * LHS, const APInt & RHS, const Twine & Name = "") inline
Definition at line 886 of file IRBuilder.h.
CreateOr() [2/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateOr (Value * LHS, uint64_t RHS, const Twine & Name = "") inline
Definition at line 889 of file IRBuilder.h.
CreateOr() [3/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateOr (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 877 of file IRBuilder.h.
Referenced by checkForNegativeOperand(), llvm::IRBuilder< true, TargetFolder >::CreateOr(), llvm::IRBuilder< true, TargetFolder >::CreateOr(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), foldLogOpOfMaskedICmps(), foldSelectICmpAndOr(), generateUnsignedDivisionCode(), GetMemInstValueForLoad(), insertFastDiv(), LowerAtomicRMWInst(), LowerBSWAP(), LowerCTLZ(), performAtomicOp(), and SimplifyCondBranchToCondBranch().
CreatePHI()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> PHINode * llvm::IRBuilder< preserveNames, T, Inserter >::CreatePHI (Type * Ty, unsigned NumReservedValues, const Twine & Name = "") inline
Definition at line 1407 of file IRBuilder.h.
Referenced by convertMemSetToLoop(), convertTransferToLoop(), generateUnsignedDivisionCode(), insertFastDiv(), and ScalarizeMaskedLoad().
CreatePointerBitCastOrAddrSpaceCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreatePointerBitCastOrAddrSpaceCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1262 of file IRBuilder.h.
CreatePointerCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreatePointerCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1253 of file IRBuilder.h.
CreatePtrDiff()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreatePtrDiff (Value * LHS, Value * RHS, const Twine & Name = "") inline
Return the i64 difference between two pointer values, dividing out the size of the pointed-to objects.
This is intended to implement C-style pointer subtraction. As such, the pointers must be appropriately aligned for their element types and pointing into the same object.
Definition at line 1527 of file IRBuilder.h.
CreatePtrToInt()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreatePtrToInt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1205 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption(), llvm::IRBuilder< true, TargetFolder >::CreateBitOrPointerCast(), createCast(), llvm::IRBuilder< true, TargetFolder >::CreatePtrDiff(), GetStoreValueForLoad(), and SimplifyBranchOnICmpChain().
CreateResume()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> ResumeInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateResume (Value * Exn) inline
Definition at line 654 of file IRBuilder.h.
CreateRet()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> ReturnInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateRet (Value * V) inline
Create a 'ret <val>' instruction.
Definition at line 580 of file IRBuilder.h.
Referenced by llvm::InlineFunction(), SimplifyCondBranchToTwoReturns(), and SwitchToLookupTable().
CreateRetVoid()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> ReturnInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateRetVoid () inline
Create a 'ret void' instruction.
Definition at line 575 of file IRBuilder.h.
Referenced by SimplifyCondBranchToTwoReturns().
CreateSDiv()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateSDiv (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 765 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateExactSDiv(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), and insertFastDiv().
CreateSelect()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateSelect (Value * C, Value * True, Value * False, const Twine & Name = "") inline
Definition at line 1444 of file IRBuilder.h.
Referenced by ConvertTwoCaseSwitch(), createMinMaxOp(), FoldTwoEntryPHINode(), generateUnsignedDivisionCode(), HoistThenElseCodeToIf(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), performAtomicOp(), ScalarizeMaskedLoad(), SimplifyCondBranchToCondBranch(), SimplifyCondBranchToTwoReturns(), SpeculativelyExecuteBB(), and tryToMakeAllocaBePromotable().
CreateSExt()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateSExt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1155 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateSExtOrTrunc(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), and llvm::UpgradeIntrinsicCall().
CreateSExtOrBitCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateSExtOrBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1229 of file IRBuilder.h.
CreateSExtOrTrunc()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateSExtOrTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Create a SExt or Trunc from the integer value V to DestTy. Return the value untouched if the type of V is already DestTy.
Definition at line 1174 of file IRBuilder.h.
CreateShl() [1/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateShl (Value * LHS, const APInt & RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 814 of file IRBuilder.h.
CreateShl() [2/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateShl (Value * LHS, uint64_t RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 819 of file IRBuilder.h.
CreateShl() [3/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateShl (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 806 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateShl(), llvm::IRBuilder< true, TargetFolder >::CreateShl(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), foldSelectICmpAnd(), foldSelectICmpAndOr(), generateUnsignedDivisionCode(), GetMemInstValueForLoad(), GetShiftedValue(), LowerBSWAP(), and simplifyValueKnownNonZero().
CreateShuffleVector()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateShuffleVector (Value * V1, Value * V2, Value * Mask, const Twine & Name = "") inline
Definition at line 1474 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateVectorSplat(), and llvm::UpgradeIntrinsicCall().
CreateSIToFP()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateSIToFP (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1195 of file IRBuilder.h.
CreateSRem()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateSRem (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 791 of file IRBuilder.h.
Referenced by llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), and insertFastDiv().
CreateStore()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> StoreInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateStore (Value * Val, Value * Ptr, bool isVolatile = false) inline
Definition at line 965 of file IRBuilder.h.
Referenced by convertMemSetToLoop(), convertTransferToLoop(), llvm::IRBuilder< true, TargetFolder >::CreateAlignedStore(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), ScalarizeMaskedStore(), tryPromoteAllocaToVector(), and llvm::UpgradeIntrinsicCall().
CreateStructGEP()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateStructGEP (Value * Ptr, unsigned Idx, const Twine & Name = "") inline
Definition at line 1132 of file IRBuilder.h.
CreateSub()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateSub (Value * LHS, Value * RHS, const Twine & Name = "", bool HasNUW = false, bool HasNSW = false) inline
Definition at line 709 of file IRBuilder.h.
Referenced by checkForNegativeOperand(), CloneLoopBlocks(), llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption(), llvm::IRBuilder< true, TargetFolder >::CreateNSWSub(), llvm::IRBuilder< true, TargetFolder >::CreateNUWSub(), llvm::IRBuilder< true, TargetFolder >::CreatePtrDiff(), generatedUnsignedRemainderCode(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), LowerAtomicRMWInst(), llvm::IntrinsicLowering::LowerIntrinsicCall(), performAtomicOp(), simplifyValueKnownNonZero(), and SwitchToLookupTable().
CreateSwitch()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> SwitchInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateSwitch (Value * V, BasicBlock * Dest, unsigned NumCases = 10, MDNode * BranchWeights = nullptr) inline
Create a switch instruction with the specified value, default dest, and with a hint for the number of cases that will be added (for efficient allocation).
Definition at line 614 of file IRBuilder.h.
Referenced by SimplifyBranchOnICmpChain().
CreateTrunc()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1149 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateExtractInteger(), llvm::IRBuilder< true, TargetFolder >::CreateSExtOrTrunc(), llvm::IRBuilder< true, TargetFolder >::CreateZExtOrTrunc(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), EvaluateGEPOffsetExpression(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), GetLoadValueForLoad(), GetStoreValueForLoad(), ProcessUGT_ADDCST_ADD(), SwitchToLookupTable(), truncateIVUse(), and llvm::UpgradeIntrinsicCall().
CreateTruncOrBitCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateTruncOrBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1237 of file IRBuilder.h.
Referenced by llvm::AArch64TargetLowering::emitLoadLinked(), and llvm::ARMTargetLowering::emitLoadLinked().
CreateUDiv()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateUDiv (Value * LHS, Value * RHS, const Twine & Name = "", bool isExact = false) inline
Definition at line 753 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateExactUDiv(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), generatedUnsignedRemainderCode(), generateSignedDivisionCode(), and insertFastDiv().
CreateUIToFP()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateUIToFP (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1192 of file IRBuilder.h.
CreateUnreachable()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> UnreachableInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateUnreachable () inline
Definition at line 658 of file IRBuilder.h.
Referenced by removeUndefIntroducingPredecessor().
CreateURem()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateURem (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 785 of file IRBuilder.h.
Referenced by llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), generateSignedRemainderCode(), and insertFastDiv().
CreateVAArg()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> VAArgInst * llvm::IRBuilder< preserveNames, T, Inserter >::CreateVAArg (Value * List, Type * Ty, const Twine & Name = "") inline
Definition at line 1453 of file IRBuilder.h.
CreateVectorSplat()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateVectorSplat (unsigned NumElts, Value * V, const Twine & Name = "") inline
Return a vector value that contains.
V broadcasted to NumElts elements.
Definition at line 1541 of file IRBuilder.h.
CreateXor() [1/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateXor (Value * LHS, const APInt & RHS, const Twine & Name = "") inline
Definition at line 899 of file IRBuilder.h.
CreateXor() [2/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateXor (Value * LHS, uint64_t RHS, const Twine & Name = "") inline
Definition at line 902 of file IRBuilder.h.
CreateXor() [3/3]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateXor (Value * LHS, Value * RHS, const Twine & Name = "") inline
Definition at line 893 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateXor(), llvm::IRBuilder< true, TargetFolder >::CreateXor(), foldSelectICmpAnd(), foldSelectICmpAndOr(), generateSignedDivisionCode(), generateSignedRemainderCode(), LowerAtomicRMWInst(), and performAtomicOp().
CreateZExt()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateZExt (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1152 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateZExtOrTrunc(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), foldUDivShl(), GetMemInstValueForLoad(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), and llvm::UpgradeIntrinsicCall().
CreateZExtOrBitCast()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateZExtOrBitCast (Value * V, Type * DestTy, const Twine & Name = "") inline
Definition at line 1221 of file IRBuilder.h.
Referenced by llvm::AArch64TargetLowering::emitStoreConditional(), and llvm::ARMTargetLowering::emitStoreConditional().
CreateZExtOrTrunc()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Value * llvm::IRBuilder< preserveNames, T, Inserter >::CreateZExtOrTrunc (Value * V, Type * DestTy, const Twine & Name = "") inline
Create a ZExt or Trunc from the integer value V to DestTy. Return the value untouched if the type of V is already DestTy.
Definition at line 1160 of file IRBuilder.h.
Referenced by foldSelectICmpAnd(), foldSelectICmpAndOr(), and SwitchToLookupTable().
getFolder()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> const T & llvm::IRBuilder< preserveNames, T, Inserter >::getFolder () inline
Get the constant folder being used.
Definition at line 540 of file IRBuilder.h.
Insert() [1/2]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> Constant * llvm::IRBuilder< preserveNames, T, Inserter >::Insert (Constant * C, const Twine & = "") const inline
No-op overload to handle constants.
Definition at line 555 of file IRBuilder.h.
Insert() [2/2]
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> template<typename InstTy> InstTy * llvm::IRBuilder< preserveNames, T, Inserter >::Insert (InstTy * I, const Twine & Name = "") const inline
Insert and return the specified instruction.
Definition at line 548 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAdd(), llvm::IRBuilder< true, TargetFolder >::CreateAggregateRet(), llvm::IRBuilder< true, TargetFolder >::CreateAlloca(), llvm::IRBuilder< true, TargetFolder >::CreateAnd(), llvm::IRBuilder< true, TargetFolder >::CreateAShr(), llvm::IRBuilder< true, TargetFolder >::CreateAtomicCmpXchg(), llvm::IRBuilder< true, TargetFolder >::CreateAtomicRMW(), llvm::IRBuilder< true, TargetFolder >::CreateBinOp(), llvm::IRBuilder< true, TargetFolder >::CreateBr(), llvm::IRBuilder< true, TargetFolder >::CreateCall(), llvm::IRBuilder< true, TargetFolder >::CreateCall(), llvm::IRBuilder< true, TargetFolder >::CreateCall(), llvm::IRBuilder< true, TargetFolder >::CreateCall2(), llvm::IRBuilder< true, TargetFolder >::CreateCall3(), llvm::IRBuilder< true, TargetFolder >::CreateCall4(), llvm::IRBuilder< true, TargetFolder >::CreateCall5(), llvm::IRBuilder< true, TargetFolder >::CreateCast(), llvm::IRBuilder< true, TargetFolder >::CreateCondBr(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP1_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP1_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP2_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP2_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP2_64(), llvm::IRBuilder< true, TargetFolder >::CreateExtractElement(), llvm::IRBuilder< true, TargetFolder >::CreateExtractValue(), llvm::IRBuilder< true, TargetFolder >::CreateFAdd(), llvm::IRBuilder< true, TargetFolder >::CreateFCmp(), llvm::IRBuilder< true, TargetFolder >::CreateFDiv(), llvm::IRBuilder< true, TargetFolder >::CreateFence(), llvm::IRBuilder< true, TargetFolder >::CreateFMul(), llvm::IRBuilder< true, TargetFolder >::CreateFNeg(), llvm::IRBuilder< true, TargetFolder >::CreateFPCast(), llvm::IRBuilder< true, TargetFolder >::CreateFRem(), llvm::IRBuilder< true, TargetFolder >::CreateFSub(), llvm::IRBuilder< true, TargetFolder >::CreateGEP(), llvm::IRBuilder< true, TargetFolder >::CreateGEP(), llvm::IRBuilder< true, TargetFolder >::CreateICmp(), llvm::IRBuilder< true, TargetFolder >::CreateInBoundsGEP(), llvm::IRBuilder< true, TargetFolder >::CreateInBoundsGEP(), llvm::IRBuilder< true, TargetFolder >::CreateIndirectBr(), llvm::IRBuilder< true, TargetFolder >::CreateInsertElement(), llvm::IRBuilder< true, TargetFolder >::CreateInsertValue(), llvm::IRBuilder< true, TargetFolder >::CreateIntCast(), llvm::IRBuilder< true, TargetFolder >::CreateInvoke(), llvm::IRBuilder< true, TargetFolder >::CreateInvoke(), llvm::IRBuilder< true, TargetFolder >::CreateInvoke(), llvm::IRBuilder< true, TargetFolder >::CreateInvoke3(), llvm::IRBuilder< true, TargetFolder >::CreateLandingPad(), llvm::IRBuilder< true, TargetFolder >::CreateLoad(), llvm::IRBuilder< true, TargetFolder >::CreateLoad(), llvm::IRBuilder< true, TargetFolder >::CreateLoad(), llvm::IRBuilder< true, TargetFolder >::CreateLShr(), llvm::IRBuilder< true, TargetFolder >::CreateMul(), llvm::IRBuilder< true, TargetFolder >::CreateNeg(), llvm::IRBuilder< true, TargetFolder >::CreateNot(), llvm::IRBuilder< true, TargetFolder >::CreateOr(), llvm::IRBuilder< true, TargetFolder >::CreatePHI(), llvm::IRBuilder< true, TargetFolder >::CreatePointerBitCastOrAddrSpaceCast(), llvm::IRBuilder< true, TargetFolder >::CreatePointerCast(), llvm::IRBuilder< true, TargetFolder >::CreateResume(), llvm::IRBuilder< true, TargetFolder >::CreateRet(), llvm::IRBuilder< true, TargetFolder >::CreateRetVoid(), llvm::IRBuilder< true, TargetFolder >::CreateSDiv(), llvm::IRBuilder< true, TargetFolder >::CreateSelect(), llvm::IRBuilder< true, TargetFolder >::CreateSExtOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateShl(), llvm::IRBuilder< true, TargetFolder >::CreateShuffleVector(), llvm::IRBuilder< true, TargetFolder >::CreateSRem(), llvm::IRBuilder< true, TargetFolder >::CreateStore(), llvm::IRBuilder< true, TargetFolder >::CreateSub(), llvm::IRBuilder< true, TargetFolder >::CreateSwitch(), llvm::IRBuilder< true, TargetFolder >::CreateTruncOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateUDiv(), llvm::IRBuilder< true, TargetFolder >::CreateUnreachable(), llvm::IRBuilder< true, TargetFolder >::CreateURem(), llvm::IRBuilder< true, TargetFolder >::CreateVAArg(), llvm::IRBuilder< true, TargetFolder >::CreateXor(), and llvm::IRBuilder< true, TargetFolder >::CreateZExtOrBitCast().
isNamePreserving()
template<bool preserveNames = true, typename T = ConstantFolder, typename Inserter = IRBuilderDefaultInserter<preserveNames>> bool llvm::IRBuilder< preserveNames, T, Inserter >::isNamePreserving () const inline
Return true if this builder is configured to actually add the requested names to IR created through it.
Definition at line 544 of file IRBuilder.h.
The documentation for this class was generated from the following file:
IRBuilder.h