LLVM: llvm::XCoreFrameLowering Class Reference
LLVM API Documentation
llvm::XCoreFrameLowering Class Reference
#include <XCoreFrameLowering.h>
Public Member Functions
XCoreFrameLowering (const XCoreSubtarget &STI)
void emitPrologue (MachineFunction &MF) const override
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
bool hasFP (const MachineFunction &MF) const override
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS=nullptr) const override
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const override
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
unsigned getStackAlignment () const
unsigned getTransientStackAlignment () const
bool isStackRealignable () const
int getOffsetOfLocalArea () const
virtual bool isFPCloseToIncomingSP () const
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
virtual bool targetHandlesStackFrameRounding () const
virtual void adjustForSegmentedStacks (MachineFunction &MF) const
virtual void adjustForHiPEPrologue (MachineFunction &MF) const
virtual void adjustForFrameAllocatePrologue (MachineFunction &MF) const
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
virtual int getFrameIndexOffset (const MachineFunction &MF, int FI) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
virtual int getFrameIndexReferenceFromSP (const MachineFunction &MF, int FI, unsigned &FrameReg) const
Static Public Member Functions
static int stackSlotSize ()
Stack slot size (4 bytes)
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Detailed Description
Definition at line 24 of file XCoreFrameLowering.h.
Constructor & Destructor Documentation
XCoreFrameLowering()
XCoreFrameLowering::XCoreFrameLowering (const XCoreSubtarget & STI)
Definition at line 213 of file XCoreFrameLowering.cpp.
References llvm::TargetFrameLowering::StackGrowsDown, and llvm::TargetFrameLowering::TargetFrameLowering().
Member Function Documentation
eliminateCallFramePseudoInstr()
void XCoreFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them). It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 480 of file XCoreFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), Align, llvm::BuildMI(), llvm::MachineBasicBlock::erase(), llvm::errs(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasReservedCallFrame(), I, llvm::MachineBasicBlock::insert(), isImmU16(), isImmU6(), llvm_unreachable, and TII.
emitEpilogue()
void XCoreFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 340 of file XCoreFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::erase(), FramePtr, llvm::MachineInstr::getDebugLoc(), GetEHSpillList(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::XCoreFunctionInfo::getLRSpillSlot(), llvm::MachineInstr::getNumOperands(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), GetSpillList(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), hasFP(), llvm::XCoreFunctionInfo::hasLRSpillSlot(), IfNeededLDAWSP(), isImmU6(), RestoreSpillList(), and TII.
emitPrologue()
void XCoreFrameLowering::emitPrologue (MachineFunction & MF) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 223 of file XCoreFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstr::addRegisterKilled(), llvm::MachineBasicBlock::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::BuildMI(), EmitCfiOffset(), EmitDefCfaOffset(), EmitDefCfaRegister(), llvm::SmallVectorTemplateCommon< T, typename >::end(), FramePtr, llvm::MachineFunction::front(), llvm::Function::getAttributes(), llvm::MachineModuleInfo::getContext(), llvm::MCRegisterInfo::getDwarfRegNum(), GetEHSpillList(), llvm::CalleeSavedInfo::getFrameIdx(), getFrameIndexMMO(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::XCoreFunctionInfo::getLRSpillSlot(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFunction::getMMI(), llvm::MachineFrameInfo::getObjectOffset(), llvm::CalleeSavedInfo::getReg(), llvm::MCContext::getRegisterInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::XCoreFunctionInfo::getSpillLabels(), GetSpillList(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::AttributeSet::hasAttrSomewhere(), llvm::XCoreFunctionInfo::hasEHSpillSlot(), hasFP(), llvm::XCoreFunctionInfo::hasLRSpillSlot(), IfNeededExtSP(), isImmU6(), llvm::RegState::Kill, MaxImmU16, llvm::MachineMemOperand::MOStore, llvm::XCoreRegisterInfo::needsFrameMoves(), llvm::Attribute::Nest, llvm::report_fatal_error(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and TII.
hasFP()
bool XCoreFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register. For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 218 of file XCoreFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasVarSizedObjects(), and llvm::TargetMachine::Options.
Referenced by emitEpilogue(), emitPrologue(), processFunctionBeforeCalleeSavedScan(), processFunctionBeforeFrameFinalized(), restoreCalleeSavedRegisters(), and spillCalleeSavedRegisters().
processFunctionBeforeCalleeSavedScan()
void XCoreFrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 530 of file XCoreFrameLowering.cpp.
References llvm::MachineModuleInfo::callsEHReturn(), llvm::MachineModuleInfo::callsUnwindInit(), llvm::XCoreFunctionInfo::createEHSpillSlot(), llvm::XCoreFunctionInfo::createFPSpillSlot(), llvm::XCoreFunctionInfo::createLRSpillSlot(), llvm::MachineFrameInfo::estimateStackSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getMMI(), llvm::MachineFunction::getRegInfo(), hasFP(), llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::Function::isVarArg(), and llvm::MachineRegisterInfo::setPhysRegUnused().
processFunctionBeforeFrameFinalized()
void XCoreFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized. Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 565 of file XCoreFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetRegisterClass::getSize(), hasFP(), and llvm::XCoreFunctionInfo::isLargeFrame().
restoreCalleeSavedRegisters()
bool XCoreFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 445 of file XCoreFrameLowering.cpp.
References llvm::MachineBasicBlock::begin(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), hasFP(), and TII.
spillCalleeSavedRegisters()
bool XCoreFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 409 of file XCoreFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::XCoreFunctionInfo::getSpillLabels(), llvm::MachineFunction::getSubtarget(), hasFP(), llvm::XCoreRegisterInfo::needsFrameMoves(), and TII.
stackSlotSize()
int llvm::XCoreFrameLowering::stackSlotSize () inline static
Stack slot size (4 bytes)
Definition at line 56 of file XCoreFrameLowering.h.
The documentation for this class was generated from the following files:
XCoreFrameLowering.h
XCoreFrameLowering.cpp