LLVM: llvm::cl::list< DataType, Storage, ParserClass > Class Template Reference
LLVM API Documentation
llvm::cl::list< DataType, Storage, ParserClass > Class Template Reference
#include <CommandLine.h>
Public Member Functions
ParserClass & getParser ()
unsigned getPosition (unsigned optnum) const
void setNumAdditionalVals (unsigned n)
template<class M0t>
list (const M0t &M0)
template<class M0t, class M1t>
list (const M0t &M0, const M1t &M1)
template<class M0t, class M1t, class M2t>
list (const M0t &M0, const M1t &M1, const M2t &M2)
template<class M0t, class M1t, class M2t, class M3t>
list (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3)
template<class M0t, class M1t, class M2t, class M3t, class M4t>
list (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4)
template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t>
list (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4, const M5t &M5)
template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t>
list (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4, const M5t &M5, const M6t &M6)
template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t, class M7t>
list (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4, const M5t &M5, const M6t &M6, const M7t &M7)
Public Member Functions inherited from llvm::cl::Option
enum NumOccurrencesFlag getNumOccurrencesFlag () const
enum ValueExpected getValueExpectedFlag () const
enum OptionHidden getOptionHiddenFlag () const
enum FormattingFlags getFormattingFlag () const
unsigned getMiscFlags () const
unsigned getPosition () const
unsigned getNumAdditionalVals () const
bool hasArgStr () const
void setArgStr (const char *S)
void setDescription (const char *S)
void setValueStr (const char *S)
void setNumOccurrencesFlag (enum NumOccurrencesFlag Val)
void setValueExpectedFlag (enum ValueExpected Val)
void setHiddenFlag (enum OptionHidden Val)
void setFormattingFlag (enum FormattingFlags V)
void setMiscFlag (enum MiscFlags M)
void setPosition (unsigned pos)
void setCategory (OptionCategory &C)
void addArgument ()
void removeArgument ()
Option * getNextRegisteredOption () const
virtual bool addOccurrence (unsigned pos, StringRef ArgName, StringRef Value, bool MultiArg=false)
bool error (const Twine &Message, StringRef ArgName=StringRef())
int getNumOccurrences () const
virtual ~Option ()
Public Member Functions inherited from llvm::cl::list_storage< DataType, bool >
template<class T>
void addValue (const T &V)
list_storage ()
bool setLocation (Option &O, bool &L)
Additional Inherited Members
Public Attributes inherited from llvm::cl::Option
const char * ArgStr
const char * HelpStr
const char * ValueStr
OptionCategory * Category
Protected Member Functions inherited from llvm::cl::Option
Option (enum NumOccurrencesFlag OccurrencesFlag, enum OptionHidden Hidden)
void setNumAdditionalVals (unsigned n)
Detailed Description
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>>
class llvm::cl::list< DataType, Storage, ParserClass >
Definition at line 1326 of file CommandLine.h.
Constructor & Destructor Documentation
list() [1/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t> llvm::cl::list< DataType, Storage, ParserClass >::list (const M0t & M0) inline explicit
Definition at line 1379 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
list() [2/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t> llvm::cl::list< DataType, Storage, ParserClass >::list (const M0t & M0, const M1t & M1) inline
Definition at line 1386 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
list() [3/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t> llvm::cl::list< DataType, Storage, ParserClass >::list (const M0t & M0, const M1t & M1, const M2t & M2) inline
Definition at line 1394 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
list() [4/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t> llvm::cl::list< DataType, Storage, ParserClass >::list (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3) inline
Definition at line 1403 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
list() [5/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t> llvm::cl::list< DataType, Storage, ParserClass >::list (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4) inline
Definition at line 1413 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
list() [6/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t> llvm::cl::list< DataType, Storage, ParserClass >::list (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4, const M5t & M5) inline
Definition at line 1425 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
list() [7/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t> llvm::cl::list< DataType, Storage, ParserClass >::list (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4, const M5t & M5, const M6t & M6) inline
Definition at line 1439 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
list() [8/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t, class M7t> llvm::cl::list< DataType, Storage, ParserClass >::list (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4, const M5t & M5, const M6t & M6, const M7t & M7) inline
Definition at line 1454 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
Member Function Documentation
getParser()
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> ParserClass & llvm::cl::list< DataType, Storage, ParserClass >::getParser () inline
Definition at line 1368 of file CommandLine.h.
getPosition()
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> unsigned llvm::cl::list< DataType, Storage, ParserClass >::getPosition (unsigned optnum) const inline
Definition at line 1370 of file CommandLine.h.
setNumAdditionalVals()
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> void llvm::cl::list< DataType, Storage, ParserClass >::setNumAdditionalVals (unsigned n) inline
Definition at line 1375 of file CommandLine.h.
References llvm::cl::Option::setNumAdditionalVals().
Referenced by llvm::cl::multi_val::apply().
The documentation for this class was generated from the following file:
CommandLine.h