LLVM: llvm::MipsMCExpr Class Reference
LLVM API Documentation
llvm::MipsMCExpr Class Reference
#include <MipsMCExpr.h>
Public Types
enum VariantKind {
VK_Mips_None , VK_Mips_LO , VK_Mips_HI , VK_Mips_HIGHER ,
VK_Mips_HIGHEST
}
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary , Constant , SymbolRef , Unary ,
Target
}
Public Member Functions
VariantKind getKind () const
getOpcode - Get the kind of this expression.
const MCExpr * getSubExpr () const
getSubExpr - Get the child of this expression.
void PrintImpl (raw_ostream &OS) const override
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
const MCSection * FindAssociatedSection () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Public Member Functions inherited from llvm::MCExpr
ExprKind getKind () const
void print (raw_ostream &OS) const
void dump () const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
bool EvaluateAsAbsolute (int64_t &Res) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
int64_t evaluateKnownAbsolute (const MCAsmLayout &Layout) const
bool EvaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
bool EvaluateAsValue (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
const MCSection * FindAssociatedSection () const
Static Public Member Functions
static bool isSupportedBinaryExpr (MCSymbolRefExpr::VariantKind VK, const MCBinaryExpr *BE)
static const MipsMCExpr * Create (MCSymbolRefExpr::VariantKind VK, const MCExpr *Expr, MCContext &Ctx)
static bool classof (const MCExpr *E)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind _Kind)
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet, bool ForceVarExpansion) const
Detailed Description
Definition at line 19 of file MipsMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::MipsMCExpr::VariantKind
Enumerator
VK_Mips_None
VK_Mips_LO
VK_Mips_HI
VK_Mips_HIGHER
VK_Mips_HIGHEST
Definition at line 21 of file MipsMCExpr.h.
Member Function Documentation
classof()
bool llvm::MipsMCExpr::classof (const MCExpr * E) inline static
Definition at line 61 of file MipsMCExpr.h.
References llvm::MCExpr::getKind(), and llvm::MCExpr::Target.
Create()
const MipsMCExpr * MipsMCExpr::Create (MCSymbolRefExpr::VariantKind VK, const MCExpr * Expr, MCContext & Ctx) static
Definition at line 44 of file MipsMCExpr.cpp.
References llvm_unreachable, llvm::MCSymbolRefExpr::VK_Mips_ABS_HI, llvm::MCSymbolRefExpr::VK_Mips_ABS_LO, VK_Mips_HI, llvm::MCSymbolRefExpr::VK_Mips_HIGHER, VK_Mips_HIGHER, llvm::MCSymbolRefExpr::VK_Mips_HIGHEST, VK_Mips_HIGHEST, and VK_Mips_LO.
EvaluateAsRelocatableImpl()
bool MipsMCExpr::EvaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 82 of file MipsMCExpr.cpp.
References llvm::MCExpr::EvaluateAsRelocatable(), and getSubExpr().
FindAssociatedSection()
const MCSection * llvm::MipsMCExpr::FindAssociatedSection () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 54 of file MipsMCExpr.h.
References llvm::MCExpr::FindAssociatedSection(), and getSubExpr().
fixELFSymbolsInTLSFixups()
void llvm::MipsMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 59 of file MipsMCExpr.h.
getKind()
VariantKind llvm::MipsMCExpr::getKind () const inline
getOpcode - Get the kind of this expression.
Definition at line 44 of file MipsMCExpr.h.
getSubExpr()
const MCExpr * llvm::MipsMCExpr::getSubExpr () const inline
getSubExpr - Get the child of this expression.
Definition at line 47 of file MipsMCExpr.h.
Referenced by EvaluateAsRelocatableImpl(), FindAssociatedSection(), and visitUsedExpr().
isSupportedBinaryExpr()
bool MipsMCExpr::isSupportedBinaryExpr (MCSymbolRefExpr::VariantKind VK, const MCBinaryExpr * BE) static
Definition at line 20 of file MipsMCExpr.cpp.
References llvm::cast(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::isa(), llvm::MCSymbolRefExpr::VK_Mips_ABS_HI, llvm::MCSymbolRefExpr::VK_Mips_ABS_LO, llvm::MCSymbolRefExpr::VK_Mips_HIGHER, and llvm::MCSymbolRefExpr::VK_Mips_HIGHEST.
PrintImpl()
void MipsMCExpr::PrintImpl (raw_ostream & OS) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 67 of file MipsMCExpr.cpp.
References llvm_unreachable, VK_Mips_HI, VK_Mips_HIGHER, VK_Mips_HIGHEST, and VK_Mips_LO.
visitUsedExpr()
void MipsMCExpr::visitUsedExpr (MCStreamer & Streamer) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 88 of file MipsMCExpr.cpp.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
MipsMCExpr.h
MipsMCExpr.cpp