LLVM: llvm::DwarfTypeUnit Class Reference
LLVM API Documentation
llvm::DwarfTypeUnit Class Reference
#include <DwarfUnit.h>
Public Member Functions
DwarfTypeUnit (unsigned UID, DwarfCompileUnit &CU, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU, MCDwarfDwoLineTable *SplitLineTable=nullptr)
void setTypeSignature (uint64_t Signature)
uint64_t getTypeSignature () const
void setType (const DIE *Ty)
void emitHeader (const MCSymbol *ASectionSym) const override
Emit the header for this unit, not including the initial length field.
unsigned getHeaderSize () const override
DwarfCompileUnit & getCU () override
void initSection (const MCSection *Section)
Public Member Functions inherited from llvm::DwarfUnit
virtual ~DwarfUnit ()
~Unit - Destructor for compile unit.
const MCSection * getSection () const
AsmPrinter * getAsmPrinter () const
unsigned getUniqueID () const
uint16_t getLanguage () const
DICompileUnit getCUNode () const
DIE & getUnitDie ()
unsigned getDebugInfoOffset () const
void setDebugInfoOffset (unsigned DbgInfoOff)
bool hasContent () const
hasContent - Return true if this compile unit has something to write out.
std::string getParentContextString (DIScope Context) const
virtual void addGlobalName (StringRef Name, DIE &Die, DIScope Context)
Add a new global name to the compile unit.
virtual void addGlobalType (DIType Ty, const DIE &Die, DIScope Context)
Add a new global type to the compile unit.
void addAccelNamespace (StringRef Name, const DIE &Die)
addAccelNamespace - Add a new name to the namespace accelerator table.
DIE * getDIE (DIDescriptor D) const
DIELoc * getDIELoc ()
getDIELoc - Returns a fresh newly allocated DIELoc.
void insertDIE (DIDescriptor Desc, DIE *D)
void addFlag (DIE &Die, dwarf::Attribute Attribute)
addFlag - Add a flag that is true to the DIE.
void addUInt (DIE &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, uint64_t Integer)
addUInt - Add an unsigned integer attribute data and value.
void addUInt (DIE &Block, dwarf::Form Form, uint64_t Integer)
void addSInt (DIE &Die, dwarf::Attribute Attribute, Optional< dwarf::Form > Form, int64_t Integer)
addSInt - Add an signed integer attribute data and value.
void addSInt (DIELoc &Die, Optional< dwarf::Form > Form, int64_t Integer)
void addString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
addString - Add a string attribute data and value.
void addLabel (DIE &Die, dwarf::Attribute Attribute, dwarf::Form Form, const MCSymbol *Label)
addLabel - Add a Dwarf label attribute data and value.
void addLabel (DIELoc &Die, dwarf::Form Form, const MCSymbol *Label)
void addSectionOffset (DIE &Die, dwarf::Attribute Attribute, uint64_t Integer)
void addOpAddress (DIELoc &Die, const MCSymbol *Label)
void addLabelDelta (DIE &Die, dwarf::Attribute Attribute, const MCSymbol *Hi, const MCSymbol *Lo)
addLabelDelta - Add a label delta attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIE &Entry)
addDIEEntry - Add a DIE attribute data and value.
void addDIEEntry (DIE &Die, dwarf::Attribute Attribute, DIEEntry *Entry)
addDIEEntry - Add a DIE attribute data and value.
void addDIETypeSignature (DIE &Die, const DwarfTypeUnit &Type)
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIELoc *Block)
addBlock - Add block data.
void addBlock (DIE &Die, dwarf::Attribute Attribute, DIEBlock *Block)
addBlock - Add block data.
void addSourceLine (DIE &Die, unsigned Line, StringRef File, StringRef Directory)
void addSourceLine (DIE &Die, DIVariable V)
void addSourceLine (DIE &Die, DIGlobalVariable G)
void addSourceLine (DIE &Die, DISubprogram SP)
void addSourceLine (DIE &Die, DIType Ty)
void addSourceLine (DIE &Die, DINameSpace NS)
void addSourceLine (DIE &Die, DIObjCProperty Ty)
void addConstantValue (DIE &Die, const MachineOperand &MO, DIType Ty)
addConstantValue - Add constant value entry in variable DIE.
void addConstantValue (DIE &Die, const ConstantInt *CI, DIType Ty)
addConstantValue - Add constant value entry in variable DIE.
void addConstantValue (DIE &Die, const APInt &Val, DIType Ty)
void addConstantValue (DIE &Die, const APInt &Val, bool Unsigned)
void addConstantValue (DIE &Die, bool Unsigned, uint64_t Val)
void addConstantFPValue (DIE &Die, const MachineOperand &MO)
addConstantFPValue - Add constant value entry in variable DIE.
void addConstantFPValue (DIE &Die, const ConstantFP *CFP)
addConstantFPValue - Add constant value entry in variable DIE.
void addTemplateParams (DIE &Buffer, DIArray TParams)
addTemplateParams - Add template parameters in buffer.
bool addRegisterOpPiece (DIELoc &TheDie, unsigned Reg, unsigned SizeInBits=0, unsigned OffsetInBits=0)
Add register operand.
bool addRegisterOffset (DIELoc &TheDie, unsigned Reg, int64_t Offset)
Add register offset.
void addBlockByrefAddress (const DbgVariable &DV, DIE &Die, dwarf::Attribute Attribute, const MachineLocation &Location)
void addType (DIE &Entity, DIType Ty, dwarf::Attribute Attribute=dwarf::DW_AT_type)
addType - Add a new type attribute to the specified entity.
DIE * getOrCreateNameSpace (DINameSpace NS)
getOrCreateNameSpace - Create a DIE for DINameSpace.
DIE * getOrCreateSubprogramDIE (DISubprogram SP, bool Minimal=false)
getOrCreateSubprogramDIE - Create new DIE using SP.
void applySubprogramAttributes (DISubprogram SP, DIE &SPDie, bool Minimal=false)
DIE * getOrCreateTypeDIE (const MDNode *N)
DIE * createTypeDIE (DICompositeType Ty)
getOrCreateContextDIE - Get context owner's DIE.
DIE * getOrCreateContextDIE (DIScope Context)
getOrCreateContextDIE - Get context owner's DIE.
void constructContainingTypeDIEs ()
void constructSubprogramArguments (DIE &Buffer, DITypeArray Args)
constructSubprogramArguments - Construct function argument DIEs.
DIE & createAndAddDIE (unsigned Tag, DIE &Parent, DIDescriptor N=DIDescriptor())
void constructTypeDIE (DIE &Buffer, DICompositeType CTy)
constructTypeDIE - Construct type DIE from DICompositeType.
Additional Inherited Members
Protected Member Functions inherited from llvm::DwarfUnit
DwarfUnit (unsigned UID, dwarf::Tag, DICompileUnit CU, AsmPrinter *A, DwarfDebug *DW, DwarfFile *DWU)
Unit - Unit constructor.
void initSection (const MCSection *Section)
void addLocalString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
Add a string attribute data and value.
void addIndexedString (DIE &Die, dwarf::Attribute Attribute, StringRef Str)
bool applySubprogramDefinitionAttributes (DISubprogram SP, DIE &SPDie)
DIE * getOrCreateStaticMemberDIE (DIDerivedType DT)
getOrCreateStaticMemberDIE - Create new static data member DIE.
template<typename T>
T resolve (DIRef< T > Ref) const
Protected Attributes inherited from llvm::DwarfUnit
unsigned UniqueID
UniqueID - a numeric ID unique among all CUs in the module.
DICompileUnit CUNode
Node - MDNode for the compile unit.
DIE UnitDie
Unit debug information entry.
unsigned DebugInfoOffset
Offset of the UnitDie from beginning of debug info section.
AsmPrinter * Asm
Asm - Target of Dwarf emission.
DwarfDebug * DD
DwarfFile * DU
DIE * IndexTyDie
IndexTyDie - An anonymous type for index type. Owned by UnitDie.
DenseMap< const MDNode *, DIE * > MDNodeToDieMap
DenseMap< const MDNode *, DIEEntry * > MDNodeToDIEEntryMap
std::vector< DIEBlock * > DIEBlocks
DIEBlocks - A list of all the DIEBlocks in use.
std::vector< DIELoc * > DIELocs
DIELocs - A list of all the DIELocs in use.
DenseMap< DIE *, const MDNode * > ContainingTypeMap
BumpPtrAllocator DIEValueAllocator
DIEInteger * DIEIntegerOne
const MCSection * Section
The section this unit will be emitted in.
Detailed Description
Definition at line 407 of file DwarfUnit.h.
Constructor & Destructor Documentation
DwarfTypeUnit()
DwarfTypeUnit::DwarfTypeUnit (unsigned UID, DwarfCompileUnit & CU, AsmPrinter * A, DwarfDebug * DW, DwarfFile * DWU, MCDwarfDwoLineTable * SplitLineTable = nullptr)
Definition at line 70 of file DwarfUnit.cpp.
References llvm::DwarfUnit::addSectionOffset(), llvm::dwarf::DW_AT_stmt_list, llvm::DwarfUnit::DwarfUnit(), llvm::DwarfUnit::getCUNode(), and llvm::DwarfUnit::UnitDie.
Member Function Documentation
emitHeader()
void DwarfTypeUnit::emitHeader (const MCSymbol * ASectionSym) const override virtual
Emit the header for this unit, not including the initial length field.
Reimplemented from llvm::DwarfUnit.
Definition at line 1599 of file DwarfUnit.cpp.
References llvm::DwarfUnit::Asm, and llvm::DwarfUnit::emitHeader().
getCU()
DwarfCompileUnit & llvm::DwarfTypeUnit::getCU () inline override virtual
Implements llvm::DwarfUnit.
Definition at line 432 of file DwarfUnit.h.
getHeaderSize()
unsigned llvm::DwarfTypeUnit::getHeaderSize () const inline override virtual
Compute the size of a header for this unit, not including the initial length field.
Reimplemented from llvm::DwarfUnit.
Definition at line 427 of file DwarfUnit.h.
References llvm::DwarfUnit::getHeaderSize().
getTypeSignature()
uint64_t llvm::DwarfTypeUnit::getTypeSignature () const inline
Definition at line 422 of file DwarfUnit.h.
initSection()
void DwarfUnit::initSection (const MCSection * Section)
Definition at line 123 of file DwarfUnit.cpp.
References llvm::dwarf::DW_LANG_Ada83, llvm::dwarf::DW_LANG_Ada95, llvm::dwarf::DW_LANG_Cobol74, llvm::dwarf::DW_LANG_Cobol85, llvm::dwarf::DW_LANG_Modula2, llvm::dwarf::DW_LANG_Pascal83, llvm::dwarf::DW_LANG_PLI, and llvm::dwarf::DWARF_VERSION.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
setType()
void llvm::DwarfTypeUnit::setType (const DIE * Ty) inline
Definition at line 423 of file DwarfUnit.h.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
setTypeSignature()
void llvm::DwarfTypeUnit::setTypeSignature (uint64_t Signature) inline
Definition at line 421 of file DwarfUnit.h.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
The documentation for this class was generated from the following files:
DwarfUnit.h
DwarfUnit.cpp