LLVM: llvm::cl::opt< DataType, ExternalStorage, ParserClass > Class Template Reference
LLVM API Documentation
llvm::cl::opt< DataType, ExternalStorage, ParserClass > Class Template Reference
#include <CommandLine.h>
Public Member Functions
void setInitialValue (const DataType &V)
ParserClass & getParser ()
template<class T>
DataType & operator= (const T &Val)
template<class M0t>
opt (const M0t &M0)
template<class M0t, class M1t>
opt (const M0t &M0, const M1t &M1)
template<class M0t, class M1t, class M2t>
opt (const M0t &M0, const M1t &M1, const M2t &M2)
template<class M0t, class M1t, class M2t, class M3t>
opt (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3)
template<class M0t, class M1t, class M2t, class M3t, class M4t>
opt (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4)
template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t>
opt (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4, const M5t &M5)
template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t>
opt (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4, const M5t &M5, const M6t &M6)
template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t, class M7t>
opt (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4, const M5t &M5, const M6t &M6, const M7t &M7)
Public Member Functions inherited from llvm::cl::Option
enum NumOccurrencesFlag getNumOccurrencesFlag () const
enum ValueExpected getValueExpectedFlag () const
enum OptionHidden getOptionHiddenFlag () const
enum FormattingFlags getFormattingFlag () const
unsigned getMiscFlags () const
unsigned getPosition () const
unsigned getNumAdditionalVals () const
bool hasArgStr () const
void setArgStr (const char *S)
void setDescription (const char *S)
void setValueStr (const char *S)
void setNumOccurrencesFlag (enum NumOccurrencesFlag Val)
void setValueExpectedFlag (enum ValueExpected Val)
void setHiddenFlag (enum OptionHidden Val)
void setFormattingFlag (enum FormattingFlags V)
void setMiscFlag (enum MiscFlags M)
void setPosition (unsigned pos)
void setCategory (OptionCategory &C)
void addArgument ()
void removeArgument ()
Option * getNextRegisteredOption () const
virtual bool addOccurrence (unsigned pos, StringRef ArgName, StringRef Value, bool MultiArg=false)
bool error (const Twine &Message, StringRef ArgName=StringRef())
int getNumOccurrences () const
virtual ~Option ()
Public Member Functions inherited from llvm::cl::opt_storage< DataType, false, std::is_class< DataType >::value >
opt_storage ()
bool setLocation (Option &O, DataType &L)
void setValue (const T &V, bool initial=false)
DataType & getValue ()
operator DataType () const
const OptionValue< DataType > & getDefault () const
Additional Inherited Members
Public Attributes inherited from llvm::cl::Option
const char * ArgStr
const char * HelpStr
const char * ValueStr
OptionCategory * Category
Protected Member Functions inherited from llvm::cl::Option
Option (enum NumOccurrencesFlag OccurrencesFlag, enum OptionHidden Hidden)
void setNumAdditionalVals (unsigned n)
Detailed Description
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>>
class llvm::cl::opt< DataType, ExternalStorage, ParserClass >
Definition at line 1128 of file CommandLine.h.
Constructor & Destructor Documentation
opt() [1/8]
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class M0t> llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt (const M0t & M0) inline explicit
Definition at line 1185 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
opt() [2/8]
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class M0t, class M1t> llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt (const M0t & M0, const M1t & M1) inline
Definition at line 1193 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
opt() [3/8]
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t> llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt (const M0t & M0, const M1t & M1, const M2t & M2) inline
Definition at line 1202 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
opt() [4/8]
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t> llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3) inline
Definition at line 1211 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
opt() [5/8]
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t> llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4) inline
Definition at line 1221 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
opt() [6/8]
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t> llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4, const M5t & M5) inline
Definition at line 1232 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
opt() [7/8]
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t> llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4, const M5t & M5, const M6t & M6) inline
Definition at line 1246 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
opt() [8/8]
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t, class M7t> llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4, const M5t & M5, const M6t & M6, const M7t & M7) inline
Definition at line 1261 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::Optional.
Member Function Documentation
getParser()
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> ParserClass & llvm::cl::opt< DataType, ExternalStorage, ParserClass >::getParser () inline
Definition at line 1176 of file CommandLine.h.
operator=()
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> template<class T> DataType & llvm::cl::opt< DataType, ExternalStorage, ParserClass >::operator= (const T & Val) inline
Definition at line 1178 of file CommandLine.h.
References llvm::cl::opt_storage< DataType, false, std::is_class< DataType >::value >::getValue(), llvm::cl::opt_storage< DataType, false, std::is_class< DataType >::value >::setValue(), and T.
setInitialValue()
template<class DataType, bool ExternalStorage = false, class ParserClass = parser<DataType>> void llvm::cl::opt< DataType, ExternalStorage, ParserClass >::setInitialValue (const DataType & V) inline
Definition at line 1174 of file CommandLine.h.
References llvm::cl::opt_storage< DataType, false, std::is_class< DataType >::value >::setValue().
The documentation for this class was generated from the following file:
CommandLine.h