LLVM: llvm::RecTy Class Reference
LLVM API Documentation
llvm::RecTy Class Reference abstract
#include <Record.h>
Public Types
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Public Member Functions
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
virtual std::string getAsString () const =0
void print (raw_ostream &OS) const
void dump () const
virtual bool typeIsConvertibleTo (const RecTy *RHS) const =0
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
virtual Init * convertValue (UnsetInit *UI)
virtual Init * convertValue (BitInit *BI)
virtual Init * convertValue (BitsInit *BI)
virtual Init * convertValue (IntInit *II)
virtual Init * convertValue (StringInit *SI)
virtual Init * convertValue (ListInit *LI)
virtual Init * convertValue (UnOpInit *UI)
virtual Init * convertValue (BinOpInit *UI)
virtual Init * convertValue (TernOpInit *UI)
virtual Init * convertValue (VarBitInit *VB)
virtual Init * convertValue (DefInit *DI)
virtual Init * convertValue (DagInit *DI)
virtual Init * convertValue (TypedInit *TI)
virtual Init * convertValue (VarInit *VI)
virtual Init * convertValue (FieldInit *FI)
virtual bool baseClassOf (const RecTy *) const
Detailed Description
Definition at line 69 of file Record.h.
Member Enumeration Documentation
RecTyKind
enum llvm::RecTy::RecTyKind
Subclass discriminator (for dyn_cast<> et al.)
Enumerator
BitRecTyKind
BitsRecTyKind
IntRecTyKind
StringRecTyKind
ListRecTyKind
DagRecTyKind
RecordRecTyKind
Definition at line 72 of file Record.h.
Constructor & Destructor Documentation
RecTy()
llvm::RecTy::RecTy (RecTyKind K) inline
Definition at line 90 of file Record.h.
Referenced by llvm::BitRecTy::baseClassOf(), llvm::BitsRecTy::baseClassOf(), llvm::IntRecTy::baseClassOf(), llvm::ListRecTy::baseClassOf(), llvm::RecordRecTy::baseClassOf(), baseClassOf(), llvm::BitRecTy::classof(), llvm::BitsRecTy::classof(), llvm::DagRecTy::classof(), llvm::IntRecTy::classof(), llvm::ListRecTy::classof(), llvm::RecordRecTy::classof(), llvm::StringRecTy::classof(), llvm::BitRecTy::convertValue(), llvm::ListRecTy::get(), llvm::ListRecTy::getElementType(), llvm::BitRecTy::typeIsConvertibleTo(), llvm::BitsRecTy::typeIsConvertibleTo(), llvm::DagRecTy::typeIsConvertibleTo(), llvm::IntRecTy::typeIsConvertibleTo(), llvm::ListRecTy::typeIsConvertibleTo(), llvm::RecordRecTy::typeIsConvertibleTo(), typeIsConvertibleTo(), and llvm::StringRecTy::typeIsConvertibleTo().
~RecTy()
virtual llvm::RecTy::~RecTy () inline virtual
Definition at line 91 of file Record.h.
Member Function Documentation
baseClassOf()
bool RecTy::baseClassOf (const RecTy * RHS) const virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::IntRecTy, llvm::ListRecTy, and llvm::RecordRecTy.
Definition at line 98 of file Record.cpp.
References getRecTyKind(), and RecTy().
Referenced by llvm::BitRecTy::baseClassOf(), llvm::BitsRecTy::baseClassOf(), llvm::BitRecTy::typeIsConvertibleTo(), llvm::BitsRecTy::typeIsConvertibleTo(), llvm::DagRecTy::typeIsConvertibleTo(), llvm::IntRecTy::typeIsConvertibleTo(), llvm::ListRecTy::typeIsConvertibleTo(), llvm::RecordRecTy::typeIsConvertibleTo(), and llvm::StringRecTy::typeIsConvertibleTo().
convertValue() [1/15]
virtual Init * llvm::RecTy::convertValue (BinOpInit * UI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 114 of file Record.h.
References convertValue().
convertValue() [2/15]
virtual Init * llvm::RecTy::convertValue (BitInit * BI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 106 of file Record.h.
convertValue() [3/15]
virtual Init * llvm::RecTy::convertValue (BitsInit * BI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 107 of file Record.h.
convertValue() [4/15]
virtual Init * llvm::RecTy::convertValue (DagInit * DI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 122 of file Record.h.
convertValue() [5/15]
virtual Init * llvm::RecTy::convertValue (DefInit * DI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 121 of file Record.h.
convertValue() [6/15]
virtual Init * llvm::RecTy::convertValue (FieldInit * FI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 127 of file Record.h.
References convertValue().
convertValue() [7/15]
virtual Init * llvm::RecTy::convertValue (IntInit * II) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 108 of file Record.h.
convertValue() [8/15]
virtual Init * llvm::RecTy::convertValue (ListInit * LI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 110 of file Record.h.
convertValue() [9/15]
virtual Init * llvm::RecTy::convertValue (StringInit * SI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 109 of file Record.h.
convertValue() [10/15]
virtual Init * llvm::RecTy::convertValue (TernOpInit * UI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 117 of file Record.h.
References convertValue().
convertValue() [11/15]
virtual Init * llvm::RecTy::convertValue (TypedInit * TI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 123 of file Record.h.
convertValue() [12/15]
virtual Init * llvm::RecTy::convertValue (UnOpInit * UI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 111 of file Record.h.
References convertValue().
convertValue() [13/15]
virtual Init * llvm::RecTy::convertValue (UnsetInit * UI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 105 of file Record.h.
Referenced by llvm::BitInit::convertInitializerTo(), llvm::UnsetInit::convertInitializerTo(), llvm::VarBitInit::convertInitializerTo(), llvm::BitRecTy::convertValue(), llvm::BitRecTy::convertValue(), llvm::BitRecTy::convertValue(), llvm::BitRecTy::convertValue(), llvm::BitRecTy::convertValue(), llvm::BitsRecTy::convertValue(), llvm::BitsRecTy::convertValue(), llvm::BitsRecTy::convertValue(), llvm::BitsRecTy::convertValue(), llvm::BitsRecTy::convertValue(), llvm::DagRecTy::convertValue(), llvm::DagRecTy::convertValue(), llvm::DagRecTy::convertValue(), llvm::IntRecTy::convertValue(), llvm::IntRecTy::convertValue(), llvm::IntRecTy::convertValue(), llvm::IntRecTy::convertValue(), llvm::IntRecTy::convertValue(), llvm::ListRecTy::convertValue(), llvm::ListRecTy::convertValue(), llvm::ListRecTy::convertValue(), llvm::ListRecTy::convertValue(), llvm::ListRecTy::convertValue(), llvm::RecordRecTy::convertValue(), llvm::RecordRecTy::convertValue(), llvm::RecordRecTy::convertValue(), llvm::RecordRecTy::convertValue(), llvm::RecordRecTy::convertValue(), convertValue(), convertValue(), convertValue(), convertValue(), convertValue(), llvm::StringRecTy::convertValue(), llvm::StringRecTy::convertValue(), and llvm::StringRecTy::convertValue().
convertValue() [14/15]
virtual Init * llvm::RecTy::convertValue (VarBitInit * VB) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 120 of file Record.h.
convertValue() [15/15]
virtual Init * llvm::RecTy::convertValue (VarInit * VI) inline virtual
Reimplemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Definition at line 124 of file Record.h.
References convertValue(), and VI.
dump()
void RecTy::dump () const
Definition at line 90 of file Record.cpp.
References llvm::errs(), and print().
getAsString()
virtual std::string llvm::RecTy::getAsString () const pure virtual
Implemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
Referenced by EvaluateOperation(), llvm::UnOpInit::getAsString(), and print().
getListTy()
ListRecTy * RecTy::getListTy ()
getListTy - Returns the type representing list<this>.
Definition at line 92 of file Record.cpp.
getRecTyKind()
RecTyKind llvm::RecTy::getRecTyKind () const inline
Definition at line 88 of file Record.h.
Referenced by llvm::BitRecTy::baseClassOf(), llvm::BitsRecTy::baseClassOf(), llvm::IntRecTy::baseClassOf(), baseClassOf(), llvm::BitRecTy::classof(), llvm::BitsRecTy::classof(), llvm::DagRecTy::classof(), llvm::IntRecTy::classof(), llvm::ListRecTy::classof(), llvm::RecordRecTy::classof(), and llvm::StringRecTy::classof().
print()
void llvm::RecTy::print (raw_ostream & OS) const inline
Definition at line 94 of file Record.h.
References getAsString().
Referenced by dump(), and llvm::operator<<().
typeIsConvertibleTo()
virtual bool llvm::RecTy::typeIsConvertibleTo (const RecTy * RHS) const pure virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implemented in llvm::BitRecTy, llvm::BitsRecTy, llvm::DagRecTy, llvm::IntRecTy, llvm::ListRecTy, llvm::RecordRecTy, and llvm::StringRecTy.
References RecTy().
Referenced by llvm::DagRecTy::convertValue(), and llvm::IntRecTy::convertValue().
The documentation for this class was generated from the following files:
Record.h
Record.cpp