LLVM: llvm::DIDescriptor Class Reference
LLVM API Documentation
llvm::DIDescriptor Class Reference
A thin wraper around MDNode to access encoded debug info.
#include <DebugInfo.h>
Public Types
enum {
FlagAccessibility = 1 << 0 | 1 << 1 , FlagPrivate = 1 , FlagProtected = 2 , FlagPublic = 3 ,
FlagFwdDecl = 1 << 2 , FlagAppleBlock = 1 << 3 , FlagBlockByrefStruct = 1 << 4 , FlagVirtual = 1 << 5 ,
FlagArtificial = 1 << 6 , FlagExplicit = 1 << 7 , FlagPrototyped = 1 << 8 , FlagObjcClassComplete = 1 << 9 ,
FlagObjectPointer = 1 << 10 , FlagVector = 1 << 11 , FlagStaticMember = 1 << 12 , FlagIndirectVariable = 1 << 13 ,
FlagLValueReference = 1 << 14 , FlagRValueReference = 1 << 15
}
Accessibility flags.
Public Member Functions
DIDescriptor (const MDNode *N=nullptr)
bool Verify () const
MDNode * get () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
StringRef getHeader () const
size_t getNumHeaderFields () const
StringRef getHeaderField (unsigned Index) const
template<class T>
T getHeaderFieldAs (unsigned Index) const
uint16_t getTag () const
bool isDerivedType () const
bool isCompositeType () const
bool isSubroutineType () const
bool isBasicType () const
bool isVariable () const
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
bool isCompileUnit () const
bool isNameSpace () const
bool isLexicalBlockFile () const
bool isLexicalBlock () const
bool isSubrange () const
bool isEnumerator () const
bool isType () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
bool isImportedEntity () const
bool isExpression () const
void print (raw_ostream &OS) const
void dump () const
void replaceAllUsesWith (LLVMContext &VMContext, DIDescriptor D)
Replace all uses of debug info referenced by this descriptor.
void replaceAllUsesWith (MDNode *D)
Protected Member Functions
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy>
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
template<>
DITypeRef getFieldAs (unsigned Elt) const
Protected Attributes
const MDNode * DbgNode
Friends
template<typename T>
class DIRef
Detailed Description
A thin wraper around MDNode to access encoded debug info.
This should not be stored in a container, because the underlying MDNode may change in certain situations.
Definition at line 114 of file DebugInfo.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Accessibility flags.
The three accessibility flags are mutually exclusive and rolled together in the first two bits.
Enumerator
FlagAccessibility
FlagPrivate
FlagProtected
FlagPublic
FlagFwdDecl
FlagAppleBlock
FlagBlockByrefStruct
FlagVirtual
FlagArtificial
FlagExplicit
FlagPrototyped
FlagObjcClassComplete
FlagObjectPointer
FlagVector
FlagStaticMember
FlagIndirectVariable
FlagLValueReference
FlagRValueReference
Definition at line 124 of file DebugInfo.h.
Constructor & Destructor Documentation
DIDescriptor()
llvm::DIDescriptor::DIDescriptor (const MDNode * N = nullptr) inline explicit
Definition at line 167 of file DebugInfo.h.
References DbgNode, and N.
Referenced by llvm::DILocation::DILocation(), llvm::DITemplateTypeParameter::DITemplateTypeParameter(), llvm::DITemplateValueParameter::DITemplateValueParameter(), llvm::DITypedArray< DIDescriptor >::DITypedArray(), getDescriptorField(), operator!=(), operator==(), and replaceAllUsesWith().
Member Function Documentation
dump()
void DIDescriptor::dump () const
Definition at line 1187 of file DebugInfo.cpp.
References llvm::dbgs(), and print().
get()
MDNode * llvm::DIDescriptor::get () const inline
Definition at line 171 of file DebugInfo.h.
References DbgNode.
Referenced by createImportedModule(), operator MDNode *(), and operator->().
getConstantField()
Constant * DIDescriptor::getConstantField (unsigned Elt) const protected
Definition at line 100 of file DebugInfo.cpp.
References DbgNode, and llvm::dyn_cast_or_null().
Referenced by llvm::DIDerivedType::getConstant(), llvm::DIGlobalVariable::getConstant(), getFunctionField(), getGlobalVariableField(), getInt64Field(), and getUInt64Field().
getDescriptorField()
DIDescriptor DIDescriptor::getDescriptorField (unsigned Elt) const protected
Definition at line 91 of file DebugInfo.cpp.
References DbgNode, DIDescriptor(), and getNodeField().
Referenced by getFieldAs().
getFieldAs() [1/5]
template<typename DescTy> DescTy llvm::DIDescriptor::getFieldAs (unsigned Elt) const inline protected
Definition at line 157 of file DebugInfo.h.
References getDescriptorField().
Referenced by llvm::DIDerivedType::getClassType(), llvm::DICompositeType::getContainingType(), llvm::DISubprogram::getContainingType(), llvm::DIGlobalVariable::getContext(), llvm::DIImportedEntity::getContext(), llvm::DILexicalBlock::getContext(), llvm::DINameSpace::getContext(), llvm::DISubprogram::getContext(), llvm::DITemplateTypeParameter::getContext(), llvm::DITemplateValueParameter::getContext(), llvm::DIType::getContext(), llvm::DIVariable::getContext(), llvm::DIGlobalVariable::getDirectory(), llvm::DITemplateTypeParameter::getDirectory(), llvm::DITemplateValueParameter::getDirectory(), llvm::DITypedArray< DIDescriptor >::getElement(), llvm::DICompositeType::getElements(), llvm::DIImportedEntity::getEntity(), llvm::DIObjCProperty::getFile(), llvm::DIVariable::getFile(), llvm::DIGlobalVariable::getFilename(), llvm::DITemplateTypeParameter::getFilename(), llvm::DITemplateValueParameter::getFilename(), llvm::DISubprogram::getFunctionDeclaration(), llvm::DILexicalBlockFile::getScope(), llvm::DIGlobalVariable::getStaticDataMemberDeclaration(), llvm::DICompositeType::getTemplateParams(), llvm::DISubprogram::getTemplateParams(), llvm::DIGlobalVariable::getType(), llvm::DIObjCProperty::getType(), llvm::DISubprogram::getType(), llvm::DITemplateTypeParameter::getType(), llvm::DITemplateValueParameter::getType(), llvm::DIVariable::getType(), llvm::DISubroutineType::getTypeArray(), and llvm::DIDerivedType::getTypeDerivedFrom().
getFieldAs() [2/5]
template<> DIScopeRef llvm::DIDescriptor::getFieldAs (unsigned Elt) const protected
Handle fields that are references to DIScopes.
getFieldAs() [3/5]
template<> DITypeRef llvm::DIDescriptor::getFieldAs (unsigned Elt) const protected
Handle fields that are references to DITypes.
getFieldAs() [4/5]
template<> DIScopeRef llvm::DIDescriptor::getFieldAs (unsigned Elt) const protected
Definition at line 1456 of file DebugInfo.cpp.
References llvm::cast_or_null(), DbgNode, and getField().
getFieldAs() [5/5]
template<> DITypeRef llvm::DIDescriptor::getFieldAs (unsigned Elt) const protected
Definition at line 1459 of file DebugInfo.cpp.
References llvm::cast_or_null(), DbgNode, and getField().
getFunctionField()
Function * DIDescriptor::getFunctionField (unsigned Elt) const protected
Definition at line 111 of file DebugInfo.cpp.
References llvm::dyn_cast_or_null(), and getConstantField().
Referenced by llvm::DISubprogram::getFunction().
getGlobalVariableField()
GlobalVariable * DIDescriptor::getGlobalVariableField (unsigned Elt) const protected
Definition at line 96 of file DebugInfo.cpp.
References llvm::dyn_cast_or_null(), and getConstantField().
Referenced by llvm::DIGlobalVariable::getGlobal().
getHeader()
StringRef llvm::DIDescriptor::getHeader () const inline
Definition at line 185 of file DebugInfo.h.
References getStringField().
Referenced by createTypeWithFlags(), getHeaderField(), and getNumHeaderFields().
getHeaderField()
StringRef llvm::DIDescriptor::getHeaderField (unsigned Index) const inline
Definition at line 194 of file DebugInfo.h.
References getHeader(), and I.
Referenced by llvm::DIGlobalVariable::getDisplayName(), llvm::DISubprogram::getDisplayName(), llvm::DICompileUnit::getFlags(), getHeaderFieldAs(), llvm::DIGlobalVariable::getLinkageName(), llvm::DISubprogram::getLinkageName(), llvm::DIEnumerator::getName(), llvm::DIGlobalVariable::getName(), llvm::DIImportedEntity::getName(), llvm::DINameSpace::getName(), llvm::DISubprogram::getName(), llvm::DITemplateTypeParameter::getName(), llvm::DITemplateValueParameter::getName(), llvm::DIType::getName(), llvm::DIVariable::getName(), llvm::DIObjCProperty::getObjCPropertyGetterName(), llvm::DIObjCProperty::getObjCPropertyName(), llvm::DIObjCProperty::getObjCPropertySetterName(), llvm::DICompileUnit::getProducer(), and llvm::DICompileUnit::getSplitDebugFilename().
getHeaderFieldAs()
template<class T> T llvm::DIDescriptor::getHeaderFieldAs (unsigned Index) const inline
Definition at line 203 of file DebugInfo.h.
References getHeaderField(), and T.
Referenced by llvm::DIType::getAlignInBits(), llvm::DIVariable::getArgNumber(), llvm::DIObjCProperty::getAttributes(), llvm::DILexicalBlock::getColumnNumber(), llvm::DITemplateTypeParameter::getColumnNumber(), llvm::DITemplateValueParameter::getColumnNumber(), llvm::DISubrange::getCount(), llvm::DILexicalBlockFile::getDiscriminator(), llvm::DIExpression::getElement(), llvm::DICompileUnit::getEmissionKind(), llvm::DIBasicType::getEncoding(), llvm::DIEnumerator::getEnumValue(), llvm::DISubprogram::getFlags(), llvm::DIType::getFlags(), llvm::DICompileUnit::getLanguage(), llvm::DIGlobalVariable::getLineNumber(), llvm::DIImportedEntity::getLineNumber(), llvm::DILexicalBlock::getLineNumber(), llvm::DINameSpace::getLineNumber(), llvm::DIObjCProperty::getLineNumber(), llvm::DISubprogram::getLineNumber(), llvm::DITemplateTypeParameter::getLineNumber(), llvm::DITemplateValueParameter::getLineNumber(), llvm::DIType::getLineNumber(), llvm::DIVariable::getLineNumber(), llvm::DISubrange::getLo(), llvm::DIType::getOffsetInBits(), llvm::DICompositeType::getRunTimeLang(), llvm::DICompileUnit::getRunTimeVersion(), llvm::DISubprogram::getScopeLineNumber(), llvm::DIType::getSizeInBits(), getTag(), llvm::DISubprogram::getVirtualIndex(), llvm::DISubprogram::getVirtuality(), llvm::DIVariable::isArtificial(), llvm::DIGlobalVariable::isDefinition(), llvm::DISubprogram::isDefinition(), llvm::DIVariable::isIndirect(), llvm::DIGlobalVariable::isLocalToUnit(), llvm::DISubprogram::isLocalToUnit(), llvm::DIVariable::isObjectPointer(), llvm::DICompileUnit::isOptimized(), and llvm::DISubprogram::isOptimized().
getInt64Field()
int64_t DIDescriptor::getInt64Field (unsigned Elt) const protected
Definition at line 83 of file DebugInfo.cpp.
References llvm::dyn_cast(), and getConstantField().
getNumHeaderFields()
size_t llvm::DIDescriptor::getNumHeaderFields () const inline
Definition at line 189 of file DebugInfo.h.
References getHeader().
Referenced by llvm::DIExpression::getElement(), llvm::DIExpression::getNumElements(), isLexicalBlock(), isLexicalBlockFile(), llvm::DIBasicType::Verify(), llvm::DICompileUnit::Verify(), llvm::DICompositeType::Verify(), llvm::DIDerivedType::Verify(), llvm::DIEnumerator::Verify(), llvm::DIGlobalVariable::Verify(), llvm::DIImportedEntity::Verify(), llvm::DILexicalBlock::Verify(), llvm::DILexicalBlockFile::Verify(), llvm::DINameSpace::Verify(), llvm::DIObjCProperty::Verify(), llvm::DISubprogram::Verify(), llvm::DISubrange::Verify(), llvm::DITemplateTypeParameter::Verify(), llvm::DITemplateValueParameter::Verify(), and llvm::DIVariable::Verify().
getStringField()
StringRef DIDescriptor::getStringField (unsigned Elt) const protected
Definition at line 71 of file DebugInfo.cpp.
References DbgNode.
Referenced by getHeader().
getTag()
uint16_t llvm::DIDescriptor::getTag () const inline
Definition at line 210 of file DebugInfo.h.
References getHeaderFieldAs().
Referenced by llvm::DwarfUnit::addBlockByrefAddress(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DwarfDebug::beginFunction(), llvm::DwarfUnit::constructTypeDIE(), createFunctionHelper(), llvm::DIBuilder::createMethod(), llvm::DwarfUnit::createTypeDIE(), getBaseTypeSize(), llvm::DIDerivedType::getClassType(), llvm::DIDerivedType::getConstant(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DbgVariable::getType(), isBasicType(), isCompileUnit(), isCompositeType(), isDerivedType(), isEnumerator(), isExpression(), isFile(), isGlobalVariable(), isImportedEntity(), isLexicalBlock(), isLexicalBlockFile(), isNameSpace(), isObjCProperty(), isScope(), isSubprogram(), isSubrange(), isSubroutineType(), isTemplateTypeParameter(), isTemplateValueParameter(), isUnsignedDIType(), isVariable(), print(), llvm::DIType::printInternal(), llvm::DIDerivedType::Verify(), llvm::DIType::Verify(), and llvm::WriteMDNodeComment().
getUInt64Field()
uint64_t DIDescriptor::getUInt64Field (unsigned Elt) const protected
Definition at line 75 of file DebugInfo.cpp.
References llvm::dyn_cast(), and getConstantField().
Referenced by getUnsignedField().
getUnsignedField()
unsigned llvm::DIDescriptor::getUnsignedField (unsigned Elt) const inline protected
Definition at line 150 of file DebugInfo.h.
References getUInt64Field().
isBasicType()
bool DIDescriptor::isBasicType () const
Definition at line 172 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_base_type, llvm::dwarf::DW_TAG_unspecified_type, and getTag().
Referenced by llvm::DwarfUnit::getOrCreateTypeDIE(), isType(), isUnsignedDIType(), print(), llvm::DIType::printInternal(), llvm::DIBasicType::Verify(), and llvm::DIType::Verify().
isCompileUnit()
bool DIDescriptor::isCompileUnit () const
Definition at line 273 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_compile_unit, and getTag().
Referenced by llvm::DIScope::getContext(), llvm::DIScope::getName(), llvm::DwarfUnit::getParentContextString(), print(), and llvm::DICompileUnit::Verify().
isCompositeType()
bool DIDescriptor::isCompositeType () const
Definition at line 206 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_array_type, llvm::dwarf::DW_TAG_class_type, llvm::dwarf::DW_TAG_enumeration_type, llvm::dwarf::DW_TAG_structure_type, llvm::dwarf::DW_TAG_subroutine_type, llvm::dwarf::DW_TAG_union_type, and getTag().
Referenced by llvm::DIBuilder::createClassType(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createReplaceableForwardDecl(), llvm::DIBuilder::createStructType(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DIScope::getRef(), isDerivedType(), isType(), print(), llvm::DICompositeType::Verify(), and llvm::DIType::Verify().
isDerivedType()
bool DIDescriptor::isDerivedType () const
Definition at line 184 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_const_type, llvm::dwarf::DW_TAG_friend, llvm::dwarf::DW_TAG_inheritance, llvm::dwarf::DW_TAG_member, llvm::dwarf::DW_TAG_pointer_type, llvm::dwarf::DW_TAG_ptr_to_member_type, llvm::dwarf::DW_TAG_reference_type, llvm::dwarf::DW_TAG_restrict_type, llvm::dwarf::DW_TAG_rvalue_reference_type, llvm::dwarf::DW_TAG_typedef, llvm::dwarf::DW_TAG_volatile_type, getTag(), and isCompositeType().
Referenced by llvm::DwarfUnit::constructTypeDIE(), getBaseTypeSize(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DIVariable::getSizeInBits(), isType(), isUnsignedDIType(), print(), llvm::DIDerivedType::Verify(), and llvm::DIType::Verify().
isEnumerator()
bool DIDescriptor::isEnumerator () const
Definition at line 302 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_enumerator, and getTag().
Referenced by print(), and llvm::DIEnumerator::Verify().
isExpression()
bool DIDescriptor::isExpression () const
Definition at line 315 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_expression, and getTag().
Referenced by print(), and llvm::DIExpression::Verify().
isFile()
bool DIDescriptor::isFile () const
Definition at line 277 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_file_type, and getTag().
Referenced by llvm::DIScope::getContext(), llvm::DIScope::getName(), llvm::DwarfUnit::getOrCreateContextDIE(), print(), and llvm::DIFile::Verify().
isGlobalVariable()
bool DIDescriptor::isGlobalVariable () const
Definition at line 242 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_constant, llvm::dwarf::DW_TAG_variable, and getTag().
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), print(), and llvm::DIGlobalVariable::Verify().
isImportedEntity()
bool DIDescriptor::isImportedEntity () const
Definition at line 310 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_imported_declaration, llvm::dwarf::DW_TAG_imported_module, and getTag().
Referenced by llvm::DIImportedEntity::Verify().
isLexicalBlock()
bool DIDescriptor::isLexicalBlock () const
Definition at line 290 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_lexical_block, getNumHeaderFields(), and getTag().
Referenced by llvm::DIScope::getContext(), llvm::getDISubprogram(), llvm::DIScope::getName(), llvm::LexicalScopes::getOrCreateAbstractScope(), and llvm::DILexicalBlock::Verify().
isLexicalBlockFile()
bool DIDescriptor::isLexicalBlockFile () const
Definition at line 285 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_lexical_block, getNumHeaderFields(), and getTag().
Referenced by llvm::LexicalScopes::findLexicalScope(), llvm::DIScope::getContext(), llvm::DILocation::getDiscriminator(), llvm::getDISubprogram(), llvm::DIScope::getName(), llvm::LexicalScopes::getOrCreateAbstractScope(), llvm::DILexicalBlockFile::Verify(), and llvm::DISubprogram::Verify().
isNameSpace()
bool DIDescriptor::isNameSpace () const
Definition at line 281 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_namespace, and getTag().
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DIScope::getContext(), llvm::DIScope::getName(), llvm::DwarfUnit::getOrCreateContextDIE(), print(), llvm::DebugInfoFinder::processModule(), and llvm::DINameSpace::Verify().
isObjCProperty()
bool DIDescriptor::isObjCProperty () const
Definition at line 306 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_APPLE_property, and getTag().
Referenced by llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::constructTypeDIE(), print(), and llvm::DIObjCProperty::Verify().
isScope()
bool DIDescriptor::isScope () const
Definition at line 247 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_compile_unit, llvm::dwarf::DW_TAG_file_type, llvm::dwarf::DW_TAG_lexical_block, llvm::dwarf::DW_TAG_namespace, llvm::dwarf::DW_TAG_subprogram, getTag(), and isType().
Referenced by llvm::DIBuilder::createClassType(), llvm::DIBuilder::createLocalVariable(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::DebugLoc::print(), print(), llvm::SDNode::print_details(), and printDebugLoc().
isSubprogram()
bool DIDescriptor::isSubprogram () const
Definition at line 238 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_subprogram, and getTag().
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DwarfUnit::constructTypeDIE(), createFunctionHelper(), llvm::DIBuilder::createMethod(), llvm::DILexicalBlockFile::getContext(), llvm::DIScope::getContext(), llvm::getDISubprogram(), llvm::DIScope::getName(), llvm::LexicalScopes::getOrCreateAbstractScope(), llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DIVariable::isInlinedFnArgument(), isShareableAcrossCUs(), llvm::DwarfDebug::isSubprogramContext(), print(), llvm::DebugInfoFinder::processModule(), and llvm::DISubprogram::Verify().
isSubrange()
bool DIDescriptor::isSubrange () const
Definition at line 298 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_subrange_type, and getTag().
Referenced by print(), and llvm::DISubrange::Verify().
isSubroutineType()
bool DIDescriptor::isSubroutineType () const
Definition at line 168 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_subroutine_type, and getTag().
Referenced by llvm::DICompositeType::getElements().
isTemplateTypeParameter()
bool DIDescriptor::isTemplateTypeParameter () const
Definition at line 263 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_template_type_parameter, and getTag().
Referenced by llvm::DwarfUnit::addTemplateParams(), and llvm::DITemplateTypeParameter::Verify().
isTemplateValueParameter()
bool DIDescriptor::isTemplateValueParameter () const
Definition at line 267 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_GNU_template_parameter_pack, llvm::dwarf::DW_TAG_GNU_template_template_param, llvm::dwarf::DW_TAG_template_value_parameter, and getTag().
Referenced by llvm::DwarfUnit::addTemplateParams(), and llvm::DITemplateValueParameter::Verify().
isType()
bool DIDescriptor::isType () const
Definition at line 234 of file DebugInfo.cpp.
References isBasicType(), isCompositeType(), and isDerivedType().
Referenced by llvm::DwarfUnit::addSourceLine(), llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createFriend(), llvm::DIBuilder::createImportedDeclaration(), llvm::DIBuilder::createInheritance(), llvm::DIScope::getContext(), llvm::DIScope::getName(), llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DwarfUnit::getOrCreateTypeDIE(), isScope(), isShareableAcrossCUs(), llvm::DwarfDebug::isSubprogramContext(), isTypeRef(), llvm::DIType::isValid(), llvm::DIType::operator DITypeRef(), llvm::DebugInfoFinder::processModule(), llvm::DIRef< T >::resolve(), and llvm::DIType::Verify().
isVariable()
bool DIDescriptor::isVariable () const
Definition at line 222 of file DebugInfo.cpp.
References DbgNode, llvm::dwarf::DW_TAG_arg_variable, llvm::dwarf::DW_TAG_auto_variable, and getTag().
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfCompileUnit::collectDeadVariables(), llvm::ConvertDebugDeclareToDebugValue(), llvm::ConvertDebugDeclareToDebugValue(), llvm::DIBuilder::createLocalVariable(), llvm::DwarfDebug::endFunction(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDeclare(), llvm::DIBuilder::insertDeclare(), print(), llvm::MachineInstr::print(), llvm::DebugInfoFinder::processDeclare(), llvm::DebugInfoFinder::processValue(), llvm::replaceDbgDeclareForAlloca(), llvm::FastISel::selectIntrinsicCall(), llvm::FunctionLoweringInfo::set(), and llvm::DIVariable::Verify().
operator bool()
LLVM_EXPLICIT llvm::DIDescriptor::operator bool () const inline
Definition at line 180 of file DebugInfo.h.
References DbgNode, and LLVM_EXPLICIT.
operator MDNode *()
llvm::DIDescriptor::operator MDNode * () const inline
Definition at line 172 of file DebugInfo.h.
References get().
operator!=()
bool llvm::DIDescriptor::operator!= (DIDescriptor Other) const inline
Definition at line 183 of file DebugInfo.h.
References DIDescriptor(), and operator==().
operator->()
MDNode * llvm::DIDescriptor::operator-> () const inline
Definition at line 173 of file DebugInfo.h.
References get().
operator==()
bool llvm::DIDescriptor::operator== (DIDescriptor Other) const inline
Definition at line 182 of file DebugInfo.h.
References DbgNode, and DIDescriptor().
Referenced by operator!=().
print()
void DIDescriptor::print (raw_ostream & OS) const
Definition at line 1192 of file DebugInfo.cpp.
References DbgNode, getTag(), isBasicType(), isCompileUnit(), isCompositeType(), isDerivedType(), isEnumerator(), isExpression(), isFile(), isGlobalVariable(), isNameSpace(), isObjCProperty(), isScope(), isSubprogram(), isSubrange(), isVariable(), llvm::DIScope::printInternal(), llvm::DIType::printInternal(), and llvm::dwarf::TagString().
Referenced by dump(), and llvm::WriteMDNodeComment().
replaceAllUsesWith() [1/2]
void DIDescriptor::replaceAllUsesWith (LLVMContext & VMContext, DIDescriptor D)
Replace all uses of debug info referenced by this descriptor.
Definition at line 323 of file DebugInfo.cpp.
References llvm::cast(), DbgNode, llvm::MDNode::deleteTemporary(), DIDescriptor(), llvm::MDNode::get(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::DIBuilder::finalize().
replaceAllUsesWith() [2/2]
void DIDescriptor::replaceAllUsesWith (MDNode * D)
Definition at line 346 of file DebugInfo.cpp.
References llvm::cast(), DbgNode, and llvm::MDNode::deleteTemporary().
replaceFunctionField()
void DIDescriptor::replaceFunctionField (unsigned Elt, Function * F) protected
Definition at line 115 of file DebugInfo.cpp.
References DbgNode, F, llvm::ConstantAsMetadata::get(), and llvm::MDNode::replaceOperandWith().
Referenced by llvm::DISubprogram::replaceFunction().
Verify()
bool DIDescriptor::Verify () const
Definition at line 39 of file DebugInfo.cpp.
References DbgNode, llvm::DIBasicType::Verify(), llvm::DICompileUnit::Verify(), llvm::DICompositeType::Verify(), llvm::DIDerivedType::Verify(), llvm::DIEnumerator::Verify(), llvm::DIExpression::Verify(), llvm::DIFile::Verify(), llvm::DIGlobalVariable::Verify(), llvm::DIImportedEntity::Verify(), llvm::DILexicalBlock::Verify(), llvm::DILexicalBlockFile::Verify(), llvm::DINameSpace::Verify(), llvm::DIObjCProperty::Verify(), llvm::DISubprogram::Verify(), llvm::DISubrange::Verify(), llvm::DITemplateTypeParameter::Verify(), llvm::DITemplateValueParameter::Verify(), and llvm::DIVariable::Verify().
Referenced by llvm::WriteMDNodeComment().
Friends And Related Symbol Documentation
DIRef
template<typename T> friend class DIRef friend
Definition at line 117 of file DebugInfo.h.
References DIRef.
Referenced by DIRef.
Member Data Documentation
DbgNode
const MDNode* llvm::DIDescriptor::DbgNode protected
Definition at line 147 of file DebugInfo.h.
Referenced by llvm::DILocation::copyWithNewScope(), DIDescriptor(), get(), llvm::DILocation::getColumnNumber(), getConstantField(), llvm::DIScope::getContext(), getDescriptorField(), llvm::DIScope::getDirectory(), llvm::DILocation::getDiscriminator(), llvm::DICompileUnit::getEnumTypes(), getFieldAs(), llvm::DIScope::getFilename(), llvm::DIFile::getFileNode(), llvm::DICompileUnit::getGlobalVariables(), llvm::DICompositeType::getIdentifier(), llvm::DICompileUnit::getImportedEntities(), llvm::DIVariable::getInlinedAt(), llvm::DILocation::getLineNumber(), llvm::DIScope::getName(), llvm::DIExpression::getNumElements(), llvm::DITypedArray< DIDescriptor >::getNumElements(), llvm::DIDerivedType::getObjCProperty(), llvm::DILocation::getOrigLocation(), llvm::DIScope::getRef(), llvm::DICompileUnit::getRetainedTypes(), llvm::DILocation::getScope(), getStringField(), llvm::DICompileUnit::getSubprograms(), llvm::DITemplateValueParameter::getValue(), llvm::DISubprogram::getVariables(), llvm::DISubprogram::getVariablesNodes(), isBasicType(), isCompileUnit(), isCompositeType(), isDerivedType(), isEnumerator(), isExpression(), isFile(), isGlobalVariable(), isImportedEntity(), isLexicalBlock(), isLexicalBlockFile(), isNameSpace(), isObjCProperty(), isScope(), isSubprogram(), isSubrange(), isSubroutineType(), isTemplateTypeParameter(), isTemplateValueParameter(), llvm::DIType::isValid(), isVariable(), operator bool(), operator==(), print(), llvm::DIVariable::printExtendedName(), llvm::DIType::printInternal(), replaceAllUsesWith(), replaceAllUsesWith(), replaceFunctionField(), llvm::DICompileUnit::replaceGlobalVariables(), llvm::DICompileUnit::replaceSubprograms(), llvm::DIBasicType::Verify(), llvm::DICompileUnit::Verify(), llvm::DICompositeType::Verify(), llvm::DIDerivedType::Verify(), Verify(), llvm::DIEnumerator::Verify(), llvm::DIExpression::Verify(), llvm::DIFile::Verify(), llvm::DIGlobalVariable::Verify(), llvm::DIImportedEntity::Verify(), llvm::DILexicalBlock::Verify(), llvm::DILexicalBlockFile::Verify(), llvm::DILocation::Verify(), llvm::DINameSpace::Verify(), llvm::DIObjCProperty::Verify(), llvm::DISubprogram::Verify(), llvm::DISubrange::Verify(), llvm::DITemplateTypeParameter::Verify(), llvm::DITemplateValueParameter::Verify(), llvm::DIType::Verify(), and llvm::DIVariable::Verify().
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp