LLVM: llvm::DIContext Class Reference
LLVM API Documentation
llvm::DIContext Class Reference abstract
#include <DIContext.h>
Public Types
enum DIContextKind { CK_DWARF }
Public Member Functions
DIContextKind getKind () const
DIContext (DIContextKind K)
virtual ~DIContext ()
virtual void dump (raw_ostream &OS, DIDumpType DumpType=DIDT_All)=0
virtual DILineInfo getLineInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DILineInfoTable getLineInfoForAddressRange (uint64_t Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DIInliningInfo getInliningInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
Static Public Member Functions
static DIContext * getDWARFContext (const object::ObjectFile &Obj)
getDWARFContext - get a context for binary DWARF data.
Detailed Description
Definition at line 123 of file DIContext.h.
Member Enumeration Documentation
DIContextKind
enum llvm::DIContext::DIContextKind
Enumerator
CK_DWARF
Definition at line 125 of file DIContext.h.
Constructor & Destructor Documentation
DIContext()
llvm::DIContext::DIContext (DIContextKind K) inline
Definition at line 130 of file DIContext.h.
Referenced by llvm::DWARFContext::classof(), llvm::DWARFContext::DWARFContext(), and getDWARFContext().
~DIContext()
DIContext::~DIContext () virtual
Definition at line 14 of file DIContext.cpp.
Member Function Documentation
dump()
virtual void llvm::DIContext::dump (raw_ostream & OS, DIDumpType DumpType = DIDT_All) pure virtual
Implemented in llvm::DWARFContext.
References llvm::DIDT_All.
getDWARFContext()
DIContext * DIContext::getDWARFContext (const object::ObjectFile & Obj) static
getDWARFContext - get a context for binary DWARF data.
Definition at line 16 of file DIContext.cpp.
References DIContext().
getInliningInfoForAddress()
virtual DIInliningInfo llvm::DIContext::getInliningInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::DWARFContext.
getKind()
DIContextKind llvm::DIContext::getKind () const inline
Definition at line 128 of file DIContext.h.
Referenced by llvm::DWARFContext::classof().
getLineInfoForAddress()
virtual DILineInfo llvm::DIContext::getLineInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::DWARFContext.
getLineInfoForAddressRange()
virtual DILineInfoTable llvm::DIContext::getLineInfoForAddressRange (uint64_t Address, uint64_t Size, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::DWARFContext.
The documentation for this class was generated from the following files:
DIContext.h
DIContext.cpp