LLVM: llvm::coverage::CoverageMappingWriter Class Reference
LLVM API Documentation
llvm::coverage::CoverageMappingWriter Class Reference
Writer for instrumentation based coverage mapping data.
#include <CoverageMappingWriter.h>
Public Member Functions
CoverageMappingWriter (ArrayRef< unsigned > VirtualFileMapping, ArrayRef< CounterExpression > Expressions, MutableArrayRef< CounterMappingRegion > MappingRegions)
CoverageMappingWriter (ArrayRef< CounterExpression > Expressions, MutableArrayRef< CounterMappingRegion > MappingRegions)
void write (raw_ostream &OS)
Write encoded coverage mapping data to the given output stream.
Detailed Description
Writer for instrumentation based coverage mapping data.
Definition at line 40 of file CoverageMappingWriter.h.
Constructor & Destructor Documentation
CoverageMappingWriter() [1/2]
llvm::coverage::CoverageMappingWriter::CoverageMappingWriter (ArrayRef< unsigned > VirtualFileMapping, ArrayRef< CounterExpression > Expressions, MutableArrayRef< CounterMappingRegion > MappingRegions) inline
Definition at line 46 of file CoverageMappingWriter.h.
CoverageMappingWriter() [2/2]
llvm::coverage::CoverageMappingWriter::CoverageMappingWriter (ArrayRef< CounterExpression > Expressions, MutableArrayRef< CounterMappingRegion > MappingRegions) inline
Definition at line 52 of file CoverageMappingWriter.h.
Member Function Documentation
write()
void CoverageMappingWriter::write (raw_ostream & OS)
Write encoded coverage mapping data to the given output stream.
Definition at line 109 of file CoverageMappingWriter.cpp.
References llvm::coverage::CounterMappingRegion::CodeRegion, llvm::encodeULEB128(), llvm::coverage::Counter::EncodingCounterTagAndExpansionRegionTagBits, llvm::coverage::CounterMappingRegion::EncodingHasCodeBeforeBits, llvm::coverage::Counter::EncodingTagBits, llvm::coverage::CounterMappingRegion::ExpansionRegion, I, llvm::coverage::Counter::isZero(), llvm::coverage::CounterMappingRegion::SkippedRegion, and writeCounter().
The documentation for this class was generated from the following files:
CoverageMappingWriter.h
CoverageMappingWriter.cpp