LLVM: llvm::MCObjectWriter Class Reference
LLVM API Documentation
llvm::MCObjectWriter Class Reference abstract
#include <MCObjectWriter.h>
Public Member Functions
virtual ~MCObjectWriter ()
virtual void reset ()
lifetime management
bool isLittleEndian () const
raw_ostream & getStream ()
High-Level API
virtual void ExecutePostLayoutBinding (MCAssembler &Asm, const MCAsmLayout &Layout)=0
Perform any late binding of symbols (for example, to assign symbol indices for use when generating relocations).
virtual void RecordRelocation (const MCAssembler &Asm, const MCAsmLayout &Layout, const MCFragment *Fragment, const MCFixup &Fixup, MCValue Target, bool &IsPCRel, uint64_t &FixedValue)=0
Record a relocation entry.
bool IsSymbolRefDifferenceFullyResolved (const MCAssembler &Asm, const MCSymbolRefExpr *A, const MCSymbolRefExpr *B, bool InSet) const
Check whether the difference (A - B) between two symbol references is fully resolved.
virtual bool IsSymbolRefDifferenceFullyResolvedImpl (const MCAssembler &Asm, const MCSymbolData &DataA, const MCFragment &FB, bool InSet, bool IsPCRel) const
virtual void WriteObject (MCAssembler &Asm, const MCAsmLayout &Layout)=0
Write the object file.
Binary Output
void Write8 (uint8_t Value)
void WriteLE16 (uint16_t Value)
void WriteLE32 (uint32_t Value)
void WriteLE64 (uint64_t Value)
void WriteBE16 (uint16_t Value)
void WriteBE32 (uint32_t Value)
void WriteBE64 (uint64_t Value)
void Write16 (uint16_t Value)
void Write32 (uint32_t Value)
void Write64 (uint64_t Value)
void WriteZeros (unsigned N)
void WriteBytes (const SmallVectorImpl< char > &ByteVec, unsigned ZeroFillSize=0)
void WriteBytes (StringRef Str, unsigned ZeroFillSize=0)
Protected Member Functions
MCObjectWriter (raw_ostream &_OS, bool _IsLittleEndian)
Protected Attributes
raw_ostream & OS
unsigned IsLittleEndian: 1
Detailed Description
MCObjectWriter - Defines the object file and target independent interfaces used by the assembler backend to write native file format object files.
The object writer contains a few callbacks used by the assembler to allow the object writer to modify the assembler data structures at appropriate points. Once assembly is complete, the object writer is given the MCAssembler instance, which contains all the symbol and section data which should be emitted as part of WriteObject().
The object writer also contains a number of helper methods for writing binary data to the output stream.
Definition at line 39 of file MCObjectWriter.h.
Constructor & Destructor Documentation
MCObjectWriter()
llvm::MCObjectWriter::MCObjectWriter (raw_ostream & _OS, bool _IsLittleEndian) inline protected
Definition at line 49 of file MCObjectWriter.h.
References IsLittleEndian, and OS.
~MCObjectWriter()
MCObjectWriter::~MCObjectWriter () virtual
Definition at line 17 of file MCObjectWriter.cpp.
Member Function Documentation
ExecutePostLayoutBinding()
virtual void llvm::MCObjectWriter::ExecutePostLayoutBinding (MCAssembler & Asm, const MCAsmLayout & Layout) pure virtual
Perform any late binding of symbols (for example, to assign symbol indices for use when generating relocations).
This routine is called by the assembler after layout and relaxation is complete.
Implemented in llvm::MachObjectWriter.
Referenced by llvm::MCAssembler::Finish().
getStream()
raw_ostream & llvm::MCObjectWriter::getStream () inline
Definition at line 60 of file MCObjectWriter.h.
References OS.
Referenced by llvm::MCLOHDirective::Emit(), writeFragment(), and llvm::MCAssembler::writeSectionData().
isLittleEndian()
bool llvm::MCObjectWriter::isLittleEndian () const inline
Definition at line 58 of file MCObjectWriter.h.
References IsLittleEndian.
IsSymbolRefDifferenceFullyResolved()
bool MCObjectWriter::IsSymbolRefDifferenceFullyResolved (const MCAssembler & Asm, const MCSymbolRefExpr * A, const MCSymbolRefExpr * B, bool InSet) const
Check whether the difference (A - B) between two symbol references is fully resolved.
Clients are not required to answer precisely and may conservatively return false, even when a difference is fully resolved.
Definition at line 21 of file MCObjectWriter.cpp.
References llvm::MCSymbol::AliasedSymbol(), llvm::MCSymbolData::getFragment(), llvm::MCSymbolRefExpr::getKind(), llvm::MCSymbolRefExpr::getSymbol(), IsSymbolRefDifferenceFullyResolvedImpl(), llvm::MCSymbol::isUndefined(), and llvm::MCSymbolRefExpr::VK_None.
IsSymbolRefDifferenceFullyResolvedImpl()
bool MCObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl (const MCAssembler & Asm, const MCSymbolData & DataA, const MCFragment & FB, bool InSet, bool IsPCRel) const virtual
Reimplemented in llvm::MachObjectWriter.
Definition at line 47 of file MCObjectWriter.cpp.
References llvm::MCSymbol::AliasedSymbol(), llvm::MCFragment::getParent(), llvm::MCSectionData::getSection(), llvm::MCSymbol::getSection(), and llvm::MCSymbolData::getSymbol().
Referenced by IsSymbolRefDifferenceFullyResolved().
RecordRelocation()
virtual void llvm::MCObjectWriter::RecordRelocation (const MCAssembler & Asm, const MCAsmLayout & Layout, const MCFragment * Fragment, const MCFixup & Fixup, MCValue Target, bool & IsPCRel, uint64_t & FixedValue) pure virtual
Record a relocation entry.
This routine is called by the assembler after layout and relaxation, and post layout binding. The implementation is responsible for storing information about the relocation so that it can be emitted during WriteObject().
Implemented in llvm::MachObjectWriter.
reset()
virtual void llvm::MCObjectWriter::reset () inline virtual
lifetime management
Reimplemented in llvm::MachObjectWriter.
Definition at line 56 of file MCObjectWriter.h.
Referenced by llvm::MachObjectWriter::reset(), and llvm::MCAssembler::reset().
Write16()
void llvm::MCObjectWriter::Write16 (uint16_t Value) inline
Definition at line 150 of file MCObjectWriter.h.
References IsLittleEndian, WriteBE16(), and WriteLE16().
Referenced by writeFragment(), llvm::MachObjectWriter::WriteNlist(), and llvm::MachObjectWriter::WriteObject().
Write32()
void llvm::MCObjectWriter::Write32 (uint32_t Value) inline
Definition at line 157 of file MCObjectWriter.h.
References IsLittleEndian, WriteBE32(), and WriteLE32().
Referenced by llvm::MachObjectWriter::WriteDysymtabLoadCommand(), writeFragment(), llvm::MachObjectWriter::WriteHeader(), llvm::MachObjectWriter::WriteLinkeditLoadCommand(), llvm::MachObjectWriter::WriteLinkerOptionsLoadCommand(), llvm::MachObjectWriter::WriteNlist(), llvm::MipsAsmBackend::writeNopData(), llvm::MachObjectWriter::WriteObject(), llvm::MachObjectWriter::WriteSection(), llvm::MachObjectWriter::WriteSegmentLoadCommand(), and llvm::MachObjectWriter::WriteSymtabLoadCommand().
Write64()
void llvm::MCObjectWriter::Write64 (uint64_t Value) inline
Definition at line 164 of file MCObjectWriter.h.
References IsLittleEndian, WriteBE64(), and WriteLE64().
Referenced by writeFragment(), llvm::MachObjectWriter::WriteNlist(), llvm::MachObjectWriter::WriteSection(), and llvm::MachObjectWriter::WriteSegmentLoadCommand().
Write8()
void llvm::MCObjectWriter::Write8 (uint8_t Value) inline
Definition at line 116 of file MCObjectWriter.h.
References OS.
Referenced by WriteBE16(), writeFragment(), WriteLE16(), llvm::MachObjectWriter::WriteNlist(), llvm::MipsAsmBackend::writeNopData(), and llvm::MachObjectWriter::WriteObject().
WriteBE16()
void llvm::MCObjectWriter::WriteBE16 (uint16_t Value) inline
Definition at line 135 of file MCObjectWriter.h.
References Write8().
Referenced by Write16(), and WriteBE32().
WriteBE32()
void llvm::MCObjectWriter::WriteBE32 (uint32_t Value) inline
Definition at line 140 of file MCObjectWriter.h.
References WriteBE16().
Referenced by Write32(), and WriteBE64().
WriteBE64()
void llvm::MCObjectWriter::WriteBE64 (uint64_t Value) inline
Definition at line 145 of file MCObjectWriter.h.
References WriteBE32().
Referenced by Write64().
WriteBytes() [1/2]
void llvm::MCObjectWriter::WriteBytes (const SmallVectorImpl< char > & ByteVec, unsigned ZeroFillSize = 0) inline
Definition at line 180 of file MCObjectWriter.h.
References llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and WriteBytes().
Referenced by WriteBytes(), writeFragment(), writeFragmentContents(), llvm::MachObjectWriter::WriteLinkerOptionsLoadCommand(), llvm::MachObjectWriter::WriteObject(), llvm::MachObjectWriter::WriteSection(), and llvm::MachObjectWriter::WriteSegmentLoadCommand().
WriteBytes() [2/2]
void llvm::MCObjectWriter::WriteBytes (StringRef Str, unsigned ZeroFillSize = 0) inline
Definition at line 184 of file MCObjectWriter.h.
References OS, llvm::StringRef::size(), and WriteZeros().
WriteLE16()
void llvm::MCObjectWriter::WriteLE16 (uint16_t Value) inline
Definition at line 120 of file MCObjectWriter.h.
References Write8().
Referenced by Write16(), and WriteLE32().
WriteLE32()
void llvm::MCObjectWriter::WriteLE32 (uint32_t Value) inline
Definition at line 125 of file MCObjectWriter.h.
References WriteLE16().
Referenced by Write32(), and WriteLE64().
WriteLE64()
void llvm::MCObjectWriter::WriteLE64 (uint64_t Value) inline
Definition at line 130 of file MCObjectWriter.h.
References WriteLE32().
Referenced by Write64().
WriteObject()
virtual void llvm::MCObjectWriter::WriteObject (MCAssembler & Asm, const MCAsmLayout & Layout) pure virtual
Write the object file.
This routine is called by the assembler after layout and relaxation is complete, fixups have been evaluated and applied, and relocations generated.
Implemented in llvm::MachObjectWriter.
Referenced by llvm::MCAssembler::Finish().
WriteZeros()
void llvm::MCObjectWriter::WriteZeros (unsigned N) inline
Definition at line 171 of file MCObjectWriter.h.
References N, and OS.
Referenced by WriteBytes(), and llvm::MachObjectWriter::WriteObject().
Member Data Documentation
IsLittleEndian
unsigned llvm::MCObjectWriter::IsLittleEndian protected
Definition at line 46 of file MCObjectWriter.h.
Referenced by isLittleEndian(), MCObjectWriter(), Write16(), Write32(), and Write64().
OS
raw_ostream& llvm::MCObjectWriter::OS protected
Definition at line 44 of file MCObjectWriter.h.
Referenced by getStream(), MCObjectWriter(), Write8(), WriteBytes(), llvm::MachObjectWriter::WriteDysymtabLoadCommand(), llvm::MachObjectWriter::WriteHeader(), llvm::MachObjectWriter::WriteLinkeditLoadCommand(), llvm::MachObjectWriter::WriteLinkerOptionsLoadCommand(), llvm::MachObjectWriter::WriteObject(), llvm::MachObjectWriter::WriteSection(), llvm::MachObjectWriter::WriteSegmentLoadCommand(), llvm::MachObjectWriter::WriteSymtabLoadCommand(), and WriteZeros().
The documentation for this class was generated from the following files:
MCObjectWriter.h
MCObjectWriter.cpp