LLVM: llvm::IntRecTy Class Reference
LLVM API Documentation
llvm::IntRecTy Class Reference
#include <Record.h>
Public Member Functions
Init * convertValue (UnsetInit *UI) override
Init * convertValue (BitInit *BI) override
Init * convertValue (BitsInit *BI) override
Init * convertValue (IntInit *II) override
Init * convertValue (StringInit *SI) override
Init * convertValue (ListInit *LI) override
Init * convertValue (VarBitInit *VB) override
Init * convertValue (DefInit *DI) override
Init * convertValue (DagInit *DI) override
Init * convertValue (UnOpInit *UI) override
Init * convertValue (BinOpInit *UI) override
Init * convertValue (TernOpInit *UI) override
Init * convertValue (TypedInit *TI) override
Init * convertValue (VarInit *VI) override
Init * convertValue (FieldInit *FI) override
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
bool baseClassOf (const RecTy *) const override
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static IntRecTy * get ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
IntRecTy - 'int' - Represent an integer value of no particular size
Definition at line 218 of file Record.h.
Member Function Documentation
baseClassOf()
bool IntRecTy::baseClassOf (const RecTy * RHS) const override virtual
Reimplemented from llvm::RecTy.
Definition at line 246 of file Record.cpp.
References llvm::RecTy::BitRecTyKind, llvm::RecTy::BitsRecTyKind, llvm::RecTy::getRecTyKind(), llvm::RecTy::IntRecTyKind, and llvm::RecTy::RecTy().
classof()
bool llvm::IntRecTy::classof (const RecTy * RT) inline static
Definition at line 223 of file Record.h.
References llvm::RecTy::getRecTyKind(), llvm::RecTy::IntRecTyKind, and llvm::RecTy::RecTy().
convertValue() [1/15]
Init * llvm::IntRecTy::convertValue (BinOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 239 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [2/15]
Init * IntRecTy::convertValue (BitInit * BI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 225 of file Record.cpp.
References llvm::IntInit::get(), and llvm::BitInit::getValue().
convertValue() [3/15]
Init * IntRecTy::convertValue (BitsInit * BI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 229 of file Record.cpp.
References llvm::dyn_cast(), llvm::IntInit::get(), llvm::BitsInit::getBit(), and llvm::BitsInit::getNumBits().
convertValue() [4/15]
Init * llvm::IntRecTy::convertValue (DagInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 237 of file Record.h.
convertValue() [5/15]
Init * llvm::IntRecTy::convertValue (DefInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 236 of file Record.h.
convertValue() [6/15]
Init * llvm::IntRecTy::convertValue (FieldInit * FI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 243 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [7/15]
Init * llvm::IntRecTy::convertValue (IntInit * II) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 232 of file Record.h.
convertValue() [8/15]
Init * llvm::IntRecTy::convertValue (ListInit * LI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 234 of file Record.h.
convertValue() [9/15]
Init * llvm::IntRecTy::convertValue (StringInit * SI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 233 of file Record.h.
convertValue() [10/15]
Init * llvm::IntRecTy::convertValue (TernOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 240 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [11/15]
Init * IntRecTy::convertValue (TypedInit * TI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 240 of file Record.cpp.
References llvm::TypedInit::getType(), and llvm::RecTy::typeIsConvertibleTo().
convertValue() [12/15]
Init * llvm::IntRecTy::convertValue (UnOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 238 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [13/15]
Init * llvm::IntRecTy::convertValue (UnsetInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 229 of file Record.h.
convertValue() [14/15]
Init * llvm::IntRecTy::convertValue (VarBitInit * VB) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 235 of file Record.h.
convertValue() [15/15]
Init * llvm::IntRecTy::convertValue (VarInit * VI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 242 of file Record.h.
References llvm::RecTy::convertValue(), and VI.
get()
IntRecTy * llvm::IntRecTy::get () inline static
Definition at line 227 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), and llvm::TernOpInit::resolveReferences().
getAsString()
std::string llvm::IntRecTy::getAsString () const inline override virtual
Implements llvm::RecTy.
Definition at line 245 of file Record.h.
typeIsConvertibleTo()
bool llvm::IntRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline override virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 247 of file Record.h.
References llvm::RecTy::baseClassOf(), and llvm::RecTy::RecTy().
The documentation for this class was generated from the following files:
Record.h
Record.cpp