LLVM: llvm::RuntimeDyldMachOARM Class Reference
LLVM API Documentation
llvm::RuntimeDyldMachOARM Class Reference
#include <RuntimeDyldMachOARM.h>
Public Types
typedef uint32_t TargetPtrT
Public Member Functions
RuntimeDyldMachOARM (RTDyldMemoryManager *MM)
unsigned getMaxStubSize () override
unsigned getStubAlignment () override
int64_t decodeAddend (const RelocationEntry &RE) const
relocation_iterator processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile &BaseObjT, ObjSectionToIDMap &ObjSectionToID, StubMap &Stubs) override
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
void resolveRelocation (const RelocationEntry &RE, uint64_t Value) override
A object file specific relocation resolver.
void finalizeSection (const ObjectFile &Obj, unsigned SectionID, const SectionRef &Section)
Public Member Functions inherited from llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOARM >
RuntimeDyldMachOCRTPBase (RTDyldMemoryManager *mm)
void finalizeLoad (const ObjectFile &Obj, ObjSectionToIDMap &SectionMap) override
void registerEHFrames () override
Public Member Functions inherited from llvm::RuntimeDyldMachO
std::unique_ptr< RuntimeDyld::LoadedObjectInfo > loadObject (const object::ObjectFile &O) override
SectionEntry & getSection (unsigned SectionID)
bool isCompatibleFile (const object::ObjectFile &Obj) const override
Public Member Functions inherited from llvm::RuntimeDyldImpl
RuntimeDyldImpl (RTDyldMemoryManager *mm)
virtual ~RuntimeDyldImpl ()
void setProcessAllSections (bool ProcessAllSections)
void setRuntimeDyldChecker (RuntimeDyldCheckerImpl *Checker)
uint8_t * getSymbolAddress (StringRef Name) const
uint64_t getSymbolLoadAddress (StringRef Name) const
void resolveRelocations ()
void reassignSectionAddress (unsigned SectionID, uint64_t Addr)
void mapSectionAddress (const void *LocalAddress, uint64_t TargetAddress)
bool hasError ()
void clearError ()
StringRef getErrorString ()
virtual void deregisterEHFrames ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::RuntimeDyldMachO
static std::unique_ptr< RuntimeDyldMachO > create (Triple::ArchType Arch, RTDyldMemoryManager *mm)
Create a RuntimeDyldMachO instance for the given target architecture.
Protected Types inherited from llvm::RuntimeDyldImpl
typedef SmallVector< SectionEntry, 64 > SectionList
typedef unsigned SID
typedef std::map< SectionRef, unsigned > ObjSectionToIDMap
typedef std::pair< unsigned, uintptr_t > SymbolLoc
typedef StringMap< SymbolLoc > SymbolTableMap
typedef std::pair< unsigned, unsigned > CommonSymbolInfo
typedef std::map< SymbolRef, CommonSymbolInfo > CommonSymbolMap
typedef SmallVector< RelocationEntry, 64 > RelocationList
typedef std::map< RelocationValueRef, uintptr_t > StubMap
Protected Member Functions inherited from llvm::RuntimeDyldMachO
RuntimeDyldMachO (RTDyldMemoryManager *mm)
int64_t memcpyAddend (const RelocationEntry &RE) const
RelocationEntry getRelocationEntry (unsigned SectionID, const ObjectFile &BaseTObj, const relocation_iterator &RI) const
RelocationValueRef getRelocationValueRef (const ObjectFile &BaseTObj, const relocation_iterator &RI, const RelocationEntry &RE, ObjSectionToIDMap &ObjSectionToID)
void makeValueAddendPCRel (RelocationValueRef &Value, const ObjectFile &BaseTObj, const relocation_iterator &RI, unsigned OffsetToNextPC)
Make the RelocationValueRef addend PC-relative.
void dumpRelocationToResolve (const RelocationEntry &RE, uint64_t Value) const
Dump information about the relocation entry (RE) and resolved value.
void populateIndirectSymbolPointersSection (const MachOObjectFile &Obj, const SectionRef &PTSection, unsigned PTSectionID)
Protected Member Functions inherited from llvm::RuntimeDyldImpl
bool Error (const Twine &Msg)
uint64_t getSectionLoadAddress (unsigned SectionID) const
uint8_t * getSectionAddress (unsigned SectionID) const
void writeInt16BE (uint8_t *Addr, uint16_t Value)
void writeInt32BE (uint8_t *Addr, uint32_t Value)
void writeInt64BE (uint8_t *Addr, uint64_t Value)
uint64_t readBytesUnaligned (uint8_t *Src, unsigned Size) const
Endian-aware read Read the least significant Size bytes from Src.
void writeBytesUnaligned (uint64_t Value, uint8_t *Dst, unsigned Size) const
void emitCommonSymbols (const ObjectFile &Obj, const CommonSymbolMap &CommonSymbols, uint64_t TotalSize, SymbolTableMap &SymbolTable)
Given the common symbols discovered in the object file, emit a new section for them and update the symbol mappings in the object and symbol table.
unsigned emitSection (const ObjectFile &Obj, const SectionRef &Section, bool IsCode)
Emits section data from the object file to the MemoryManager.
unsigned findOrEmitSection (const ObjectFile &Obj, const SectionRef &Section, bool IsCode, ObjSectionToIDMap &LocalSections)
Find Section in LocalSections. If the secton is not found - emit it and store in LocalSections.
void addRelocationForSection (const RelocationEntry &RE, unsigned SectionID)
void addRelocationForSymbol (const RelocationEntry &RE, StringRef SymbolName)
uint8_t * createStubFunction (uint8_t *Addr, unsigned AbiVariant=0)
Emits long jump instruction to Addr.
void resolveRelocationList (const RelocationList &Relocs, uint64_t Value)
Resolves relocations from Relocs list with address from Value.
void resolveExternalSymbols ()
Resolve relocations to external symbols.
virtual void updateGOTEntries (StringRef Name, uint64_t Addr)
Update GOT entries for external symbols.
void computeTotalAllocSize (const ObjectFile &Obj, uint64_t &CodeSize, uint64_t &DataSizeRO, uint64_t &DataSizeRW)
unsigned computeSectionStubBufSize (const ObjectFile &Obj, const SectionRef &Section)
std::pair< unsigned, unsigned > loadObjectImpl (const object::ObjectFile &Obj)
Static Protected Member Functions inherited from llvm::RuntimeDyldMachO
static section_iterator getSectionByAddress (const MachOObjectFile &Obj, uint64_t Addr)
Protected Attributes inherited from llvm::RuntimeDyldMachO
SmallVector< EHFrameRelatedSections, 2 > UnregisteredEHFrameSections
Protected Attributes inherited from llvm::RuntimeDyldImpl
RTDyldMemoryManager * MemMgr
RuntimeDyldCheckerImpl * Checker
SectionList Sections
SymbolTableMap GlobalSymbolTable
DenseMap< unsigned, RelocationList > Relocations
StringMap< RelocationList > ExternalSymbolRelocations
Triple::ArchType Arch
bool IsTargetLittleEndian
bool ProcessAllSections
sys::Mutex lock
bool HasError
std::string ErrorStr
Detailed Description
Definition at line 19 of file RuntimeDyldMachOARM.h.
Member Typedef Documentation
TargetPtrT
typedef uint32_t llvm::RuntimeDyldMachOARM::TargetPtrT
Definition at line 26 of file RuntimeDyldMachOARM.h.
Constructor & Destructor Documentation
RuntimeDyldMachOARM()
llvm::RuntimeDyldMachOARM::RuntimeDyldMachOARM (RTDyldMemoryManager * MM) inline
Definition at line 28 of file RuntimeDyldMachOARM.h.
References llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOARM >::RuntimeDyldMachOCRTPBase().
Member Function Documentation
decodeAddend()
int64_t llvm::RuntimeDyldMachOARM::decodeAddend (const RelocationEntry & RE) const inline
Definition at line 34 of file RuntimeDyldMachOARM.h.
References llvm::MachO::ARM_RELOC_BR24, llvm::RuntimeDyldMachO::memcpyAddend(), llvm::RelocationEntry::Offset, llvm::RuntimeDyldImpl::readBytesUnaligned(), llvm::RelocationEntry::RelType, llvm::RelocationEntry::SectionID, llvm::RuntimeDyldImpl::Sections, and llvm::SignExtend32().
Referenced by processRelocationRef().
finalizeSection()
void llvm::RuntimeDyldMachOARM::finalizeSection (const ObjectFile & Obj, unsigned SectionID, const SectionRef & Section) inline
Definition at line 158 of file RuntimeDyldMachOARM.h.
References llvm::cast(), Name, and llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection().
getMaxStubSize()
unsigned llvm::RuntimeDyldMachOARM::getMaxStubSize () inline override virtual
Implements llvm::RuntimeDyldImpl.
Definition at line 30 of file RuntimeDyldMachOARM.h.
getStubAlignment()
unsigned llvm::RuntimeDyldMachOARM::getStubAlignment () inline override virtual
Implements llvm::RuntimeDyldImpl.
Definition at line 32 of file RuntimeDyldMachOARM.h.
processRelocationRef()
relocation_iterator llvm::RuntimeDyldMachOARM::processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile & Obj, ObjSectionToIDMap & ObjSectionToID, StubMap & Stubs) inline override virtual
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
Returns
Iterator to the next relocation that needs to be parsed.
Implements llvm::RuntimeDyldImpl.
Definition at line 51 of file RuntimeDyldMachOARM.h.
References llvm::RelocationEntry::Addend, llvm::RuntimeDyldImpl::addRelocationForSection(), llvm::RuntimeDyldImpl::addRelocationForSymbol(), llvm::MachO::ARM_RELOC_BR24, llvm::MachO::ARM_RELOC_HALF_SECTDIFF, decodeAddend(), llvm::object::MachOObjectFile::getAnyRelocationType(), llvm::object::RelocationRef::getRawDataRefImpl(), llvm::object::MachOObjectFile::getRelocation(), llvm::RuntimeDyldMachO::getRelocationEntry(), llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::RelocationEntry::IsPCRel, llvm::object::MachOObjectFile::isRelocationScattered(), llvm::RuntimeDyldMachO::makeValueAddendPCRel(), and llvm::RelocationEntry::RelType.
resolveRelocation()
void llvm::RuntimeDyldMachOARM::resolveRelocation (const RelocationEntry & RE, uint64_t Value) inline override virtual
A object file specific relocation resolver.
Parameters
RE The relocation to be resolved
Value Target symbol address to apply the relocation action
Implements llvm::RuntimeDyldImpl.
Definition at line 90 of file RuntimeDyldMachOARM.h.
References llvm::RelocationEntry::Addend, llvm::MachO::ARM_RELOC_BR24, llvm::MachO::ARM_RELOC_HALF, llvm::MachO::ARM_RELOC_HALF_SECTDIFF, llvm::MachO::ARM_RELOC_LOCAL_SECTDIFF, llvm::MachO::ARM_RELOC_PAIR, llvm::MachO::ARM_RELOC_PB_LA_PTR, llvm::MachO::ARM_RELOC_SECTDIFF, llvm::MachO::ARM_RELOC_VANILLA, llvm::MachO::ARM_THUMB_32BIT_BRANCH, llvm::MachO::ARM_THUMB_RELOC_BR22, DEBUG, llvm::RuntimeDyldMachO::dumpRelocationToResolve(), llvm::RuntimeDyldImpl::Error(), llvm::RelocationEntry::IsPCRel, llvm_unreachable, llvm::RelocationEntry::Offset, llvm::RuntimeDyldImpl::readBytesUnaligned(), llvm::RelocationEntry::RelType, llvm::RelocationEntry::SectionPair::SectionA, llvm::RelocationEntry::SectionPair::SectionB, llvm::RelocationEntry::SectionID, llvm::RelocationEntry::Sections, llvm::RuntimeDyldImpl::Sections, llvm::RelocationEntry::Size, and llvm::RuntimeDyldImpl::writeBytesUnaligned().
The documentation for this class was generated from the following file:
RuntimeDyldMachOARM.h