LLVM: llvm::FunctionAnalysisManagerModuleProxy::Result Class Reference
LLVM API Documentation
llvm::FunctionAnalysisManagerModuleProxy::Result Class Reference
The result proxy object for the FunctionAnalysisManagerModuleProxy.
#include <PassManager.h>
Public Member Functions
Result (FunctionAnalysisManager &FAM)
Result (const Result &Arg)
Result (Result &&Arg)
Result & operator= (Result RHS)
~Result ()
FunctionAnalysisManager & getManager ()
Accessor for the FunctionAnalysisManager.
bool invalidate (Module &M, const PreservedAnalyses &PA)
Handler for invalidation of the module.
Detailed Description
The result proxy object for the FunctionAnalysisManagerModuleProxy.
See its documentation for more information.
Definition at line 637 of file IR/PassManager.h.
Constructor & Destructor Documentation
Result() [1/3]
llvm::FunctionAnalysisManagerModuleProxy::Result::Result (FunctionAnalysisManager & FAM) inline explicit
Definition at line 639 of file IR/PassManager.h.
Referenced by operator=(), Result(), and Result().
Result() [2/3]
llvm::FunctionAnalysisManagerModuleProxy::Result::Result (const Result & Arg) inline
Definition at line 642 of file IR/PassManager.h.
References Result().
Result() [3/3]
llvm::FunctionAnalysisManagerModuleProxy::Result::Result (Result && Arg) inline
Definition at line 643 of file IR/PassManager.h.
References Result().
~Result()
FunctionAnalysisManagerModuleProxy::Result::~Result ()
Definition at line 24 of file PassManager.cpp.
Member Function Documentation
getManager()
FunctionAnalysisManager & llvm::FunctionAnalysisManagerModuleProxy::Result::getManager () inline
Accessor for the FunctionAnalysisManager.
Definition at line 651 of file IR/PassManager.h.
invalidate()
bool FunctionAnalysisManagerModuleProxy::Result::invalidate (Module & M, const PreservedAnalyses & PA)
Handler for invalidation of the module.
If this analysis itself is preserved, then we assume that the set of Function objects in the Module hasn't changed and thus we don't need to invalidate all cached data associated with a Function* in the FunctionAnalysisManager.
Regardless of whether this analysis is marked as preserved, all of the analyses in the FunctionAnalysisManager are potentially invalidated based on the set of preserved analyses.
Definition at line 30 of file PassManager.cpp.
References llvm::FunctionAnalysisManagerModuleProxy::ID(), and llvm::PreservedAnalyses::preserved().
operator=()
Result & llvm::FunctionAnalysisManagerModuleProxy::Result::operator= (Result RHS) inline
Definition at line 644 of file IR/PassManager.h.
References Result(), and std::swap().
The documentation for this class was generated from the following files:
IR/PassManager.h
PassManager.cpp