LLVM: llvm::IntInit Class Reference
LLVM API Documentation
llvm::IntInit Class Reference
#include <Record.h>
Public Member Functions
int64_t getValue () const
Init * convertInitializerTo (RecTy *Ty) const override
Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const override
std::string getAsString () const override
getAsString - Convert this value to a string form.
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
Init * getBit (unsigned Bit) const override
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const override
Init * convertInitListSlice (const std::vector< unsigned > &Elements) const override
RecTy * getFieldType (const std::string &FieldName) const override
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * resolveReferences (Record &R, const RecordVal *RV) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static IntInit * get (int64_t V)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit , IK_FirstTypedInit , IK_BitsInit , IK_DagInit ,
IK_DefInit , IK_FieldInit , IK_IntInit , IK_ListInit ,
IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit , IK_UnOpInit ,
IK_LastOpInit , IK_StringInit , IK_VarInit , IK_VarListElementInit ,
IK_LastTypedInit , IK_UnsetInit , IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
IntInit - 7 - Represent an initialization by a literal integer value.
Definition at line 710 of file Record.h.
Member Function Documentation
classof()
bool llvm::IntInit::classof (const Init * I) inline static
Definition at line 720 of file Record.h.
References I, and llvm::Init::IK_IntInit.
convertInitializerBitRange()
Init * IntInit::convertInitializerBitRange (const std::vector< unsigned > & Bits) const override virtual
convertInitializerBitRange - This method is used to implement the bitrange selection operator. Given an initializer, it selects the specified bits out, returning them as a new init of bits type. If it is not legal to use the bit subscript operator on this initializer, return null.
Reimplemented from llvm::Init.
Definition at line 601 of file Record.cpp.
References llvm::BitInit::get(), and llvm::BitsInit::get().
convertInitializerTo()
Init * llvm::IntInit::convertInitializerTo (RecTy * Ty) const inline override virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 727 of file Record.h.
get()
IntInit * IntInit::get (int64_t V) static
Definition at line 588 of file Record.cpp.
References I.
Referenced by llvm::IntRecTy::convertValue(), llvm::IntRecTy::convertValue(), llvm::BinOpInit::Fold(), and llvm::UnOpInit::Fold().
getAsString()
std::string IntInit::getAsString () const override virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 596 of file Record.cpp.
References llvm::itostr().
getBit()
Init * llvm::IntInit::getBit (unsigned Bit) const inline override virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 743 of file Record.h.
References llvm::BitInit::get().
getValue()
int64_t llvm::IntInit::getValue () const inline
Definition at line 725 of file Record.h.
Referenced by llvm::BitRecTy::convertValue(), llvm::BitsRecTy::convertValue(), llvm::BinOpInit::Fold(), and llvm::TernOpInit::Fold().
resolveListElementReference()
Init * llvm::IntInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const inline override virtual
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences. If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 738 of file Record.h.
References llvm_unreachable.
The documentation for this class was generated from the following files:
Record.h
Record.cpp