LLVM: llvm::AArch64AppleInstPrinter Class Reference
LLVM API Documentation
llvm::AArch64AppleInstPrinter Class Reference
#include <AArch64InstPrinter.h>
Public Member Functions
AArch64AppleInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot) override
void printInstruction (const MCInst *MI, raw_ostream &O) override
bool printAliasInstr (const MCInst *MI, raw_ostream &O) override
void printCustomAliasOperand (const MCInst *MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream &O) override
StringRef getRegName (unsigned RegNo) const override
Public Member Functions inherited from llvm::AArch64InstPrinter
AArch64InstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot) override
void printRegName (raw_ostream &OS, unsigned RegNo) const override
printRegName - Print the assembler register name.
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
setCommentStream - Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
uint64_t getAvailableFeatures () const
void setAvailableFeatures (uint64_t Value)
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
StringRef markup (StringRef a, StringRef b) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
HexStyle::Style getPrintHexStyleHex () const
void setPrintImmHex (HexStyle::Style Value)
format_object1< int64_t > formatImm (const int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object1< int64_t > formatDec (const int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object1< int64_t > formatHex (const int64_t Value) const
format_object1< uint64_t > formatHex (const uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo, unsigned AltIdx=AArch64::NoRegAltName)
Static Public Member Functions inherited from llvm::AArch64InstPrinter
static const char * getRegisterName (unsigned RegNo, unsigned AltIdx=AArch64::NoRegAltName)
Additional Inherited Members
Protected Member Functions inherited from llvm::AArch64InstPrinter
bool printSysAlias (const MCInst *MI, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printHexImm (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printPostIncOperand (const MCInst *MI, unsigned OpNo, unsigned Imm, raw_ostream &O)
template<int Amount>
void printPostIncOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printVRegOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSysCROperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printAddSubImm (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printLogicalImm32 (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printLogicalImm64 (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printShifter (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printShiftedRegister (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printExtendedRegister (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printArithExtend (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMemExtend (const MCInst *MI, unsigned OpNum, raw_ostream &O, char SrcRegKind, unsigned Width)
template<char SrcRegKind, unsigned Width>
void printMemExtend (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printCondCode (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printInverseCondCode (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAlignedLabel (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printUImm12Offset (const MCInst *MI, unsigned OpNum, unsigned Scale, raw_ostream &O)
void printAMIndexedWB (const MCInst *MI, unsigned OpNum, unsigned Scale, raw_ostream &O)
template<int Scale>
void printUImm12Offset (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<int BitWidth>
void printAMIndexedWB (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAMNoIndex (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<int Scale>
void printImmScale (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printPrefetchOp (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printFPImmOperand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorList (const MCInst *MI, unsigned OpNum, raw_ostream &O, StringRef LayoutSuffix)
void printImplicitlyTypedVectorList (const MCInst *MI, unsigned OpNum, raw_ostream &O)
template<unsigned NumLanes, char LaneKind>
void printTypedVectorList (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printVectorIndex (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printAdrpLabel (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printBarrierOption (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMSRSystemRegister (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printMRSSystemRegister (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printSystemPStateField (const MCInst *MI, unsigned OpNum, raw_ostream &O)
void printSIMDType10Operand (const MCInst *MI, unsigned OpNum, raw_ostream &O)
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
uint64_t AvailableFeatures
The current set of available features.
bool UseMarkup
True if we are printing marked up assembly.
bool PrintImmHex
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 121 of file AArch64InstPrinter.h.
Constructor & Destructor Documentation
AArch64AppleInstPrinter()
AArch64AppleInstPrinter::AArch64AppleInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI)
Definition at line 44 of file AArch64InstPrinter.cpp.
References llvm::AArch64InstPrinter::AArch64InstPrinter(), llvm::MCInstPrinter::MAI, llvm::MCInstPrinter::MII, and llvm::MCInstPrinter::MRI.
Member Function Documentation
getRegisterName()
const char * llvm::AArch64AppleInstPrinter::getRegisterName (unsigned RegNo, unsigned AltIdx = AArch64::NoRegAltName) static
Referenced by getRegName(), and printInst().
getRegName()
StringRef llvm::AArch64AppleInstPrinter::getRegName (unsigned RegNo) const inline override virtual
Reimplemented from llvm::AArch64InstPrinter.
Definition at line 133 of file AArch64InstPrinter.h.
References getRegisterName().
printAliasInstr()
bool llvm::AArch64AppleInstPrinter::printAliasInstr (const MCInst * MI, raw_ostream & O) override virtual
Reimplemented from llvm::AArch64InstPrinter.
printCustomAliasOperand()
void llvm::AArch64AppleInstPrinter::printCustomAliasOperand (const MCInst * MI, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream & O) override virtual
Reimplemented from llvm::AArch64InstPrinter.
printInst()
void AArch64AppleInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot) override virtual
printInst - Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 616 of file AArch64InstPrinter.cpp.
References getLdStNInstrDesc(), getRegisterName(), isTblTbxInstruction(), llvm::MCInstPrinter::printAnnotation(), llvm::AArch64InstPrinter::printInst(), and llvm::AArch64InstPrinter::printVectorList().
printInstruction()
void llvm::AArch64AppleInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O) override virtual
Reimplemented from llvm::AArch64InstPrinter.
The documentation for this class was generated from the following files:
AArch64InstPrinter.h
AArch64InstPrinter.cpp