LLVM: llvm::CGSCCAnalysisManagerModuleProxy Class Reference
LLVM API Documentation
llvm::CGSCCAnalysisManagerModuleProxy Class Reference
A module analysis which acts as a proxy for a CGSCC analysis manager.
#include <CGSCCPassManager.h>
Classes
class Result
Public Member Functions
CGSCCAnalysisManagerModuleProxy (CGSCCAnalysisManager &CGAM)
CGSCCAnalysisManagerModuleProxy (const CGSCCAnalysisManagerModuleProxy &Arg)
CGSCCAnalysisManagerModuleProxy (CGSCCAnalysisManagerModuleProxy &&Arg)
CGSCCAnalysisManagerModuleProxy & operator= (CGSCCAnalysisManagerModuleProxy RHS)
Result run (Module &M)
Run the analysis pass and create our proxy result object.
Static Public Member Functions
static void * ID ()
static StringRef name ()
Detailed Description
A module analysis which acts as a proxy for a CGSCC analysis manager.
This primarily proxies invalidation information from the module analysis manager and module pass manager to a CGSCC analysis manager. You should never use a CGSCC analysis manager from within (transitively) a module pass manager unless your parent module pass has received a proxy result object for it.
Definition at line 52 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
CGSCCAnalysisManagerModuleProxy() [1/3]
llvm::CGSCCAnalysisManagerModuleProxy::CGSCCAnalysisManagerModuleProxy (CGSCCAnalysisManager & CGAM) inline explicit
Definition at line 90 of file CGSCCPassManager.h.
Referenced by CGSCCAnalysisManagerModuleProxy(), CGSCCAnalysisManagerModuleProxy(), and operator=().
CGSCCAnalysisManagerModuleProxy() [2/3]
llvm::CGSCCAnalysisManagerModuleProxy::CGSCCAnalysisManagerModuleProxy (const CGSCCAnalysisManagerModuleProxy & Arg) inline
Definition at line 94 of file CGSCCPassManager.h.
References CGSCCAnalysisManagerModuleProxy().
CGSCCAnalysisManagerModuleProxy() [3/3]
llvm::CGSCCAnalysisManagerModuleProxy::CGSCCAnalysisManagerModuleProxy (CGSCCAnalysisManagerModuleProxy && Arg) inline
Definition at line 96 of file CGSCCPassManager.h.
References CGSCCAnalysisManagerModuleProxy().
Member Function Documentation
ID()
void * llvm::CGSCCAnalysisManagerModuleProxy::ID () inline static
Definition at line 86 of file CGSCCPassManager.h.
Referenced by llvm::CGSCCAnalysisManagerModuleProxy::Result::invalidate().
name()
StringRef llvm::CGSCCAnalysisManagerModuleProxy::name () inline static
Definition at line 88 of file CGSCCPassManager.h.
operator=()
CGSCCAnalysisManagerModuleProxy & llvm::CGSCCAnalysisManagerModuleProxy::operator= (CGSCCAnalysisManagerModuleProxy RHS) inline
Definition at line 99 of file CGSCCPassManager.h.
References CGSCCAnalysisManagerModuleProxy(), and std::swap().
run()
CGSCCAnalysisManagerModuleProxy::Result CGSCCAnalysisManagerModuleProxy::run (Module & M)
Run the analysis pass and create our proxy result object.
This doesn't do any interesting work, it is primarily used to insert our proxy result object into the module analysis cache so that we can proxy invalidation to the CGSCC analysis manager.
In debug builds, it will also assert that the analysis manager is empty as no queries should arrive at the CGSCC analysis manager prior to this analysis being requested.
Definition at line 19 of file CGSCCPassManager.cpp.
The documentation for this class was generated from the following files:
CGSCCPassManager.h
CGSCCPassManager.cpp