LLVM: llvm::FunctionAnalysisManagerModuleProxy Class Reference
LLVM API Documentation
llvm::FunctionAnalysisManagerModuleProxy Class Reference
A module analysis which acts as a proxy for a function analysis manager.
#include <PassManager.h>
Classes
class Result
The result proxy object for the FunctionAnalysisManagerModuleProxy.
Public Member Functions
FunctionAnalysisManagerModuleProxy (FunctionAnalysisManager &FAM)
FunctionAnalysisManagerModuleProxy (const FunctionAnalysisManagerModuleProxy &Arg)
FunctionAnalysisManagerModuleProxy (FunctionAnalysisManagerModuleProxy &&Arg)
FunctionAnalysisManagerModuleProxy & operator= (FunctionAnalysisManagerModuleProxy RHS)
Result run (Module &M)
Run the analysis pass and create our proxy result object.
Static Public Member Functions
static void * ID ()
static StringRef name ()
Detailed Description
A module analysis which acts as a proxy for a function analysis manager.
This primarily proxies invalidation information from the module analysis manager and module pass manager to a function analysis manager. You should never use a function analysis manager from within (transitively) a module pass manager unless your parent module pass has received a proxy result object for it.
Definition at line 593 of file IR/PassManager.h.
Constructor & Destructor Documentation
FunctionAnalysisManagerModuleProxy() [1/3]
llvm::FunctionAnalysisManagerModuleProxy::FunctionAnalysisManagerModuleProxy (FunctionAnalysisManager & FAM) inline explicit
Definition at line 601 of file IR/PassManager.h.
Referenced by FunctionAnalysisManagerModuleProxy(), FunctionAnalysisManagerModuleProxy(), and operator=().
FunctionAnalysisManagerModuleProxy() [2/3]
llvm::FunctionAnalysisManagerModuleProxy::FunctionAnalysisManagerModuleProxy (const FunctionAnalysisManagerModuleProxy & Arg) inline
Definition at line 605 of file IR/PassManager.h.
References FunctionAnalysisManagerModuleProxy().
FunctionAnalysisManagerModuleProxy() [3/3]
llvm::FunctionAnalysisManagerModuleProxy::FunctionAnalysisManagerModuleProxy (FunctionAnalysisManagerModuleProxy && Arg) inline
Definition at line 608 of file IR/PassManager.h.
References FunctionAnalysisManagerModuleProxy().
Member Function Documentation
ID()
void * llvm::FunctionAnalysisManagerModuleProxy::ID () inline static
Definition at line 597 of file IR/PassManager.h.
Referenced by llvm::FunctionAnalysisManagerModuleProxy::Result::invalidate().
name()
StringRef llvm::FunctionAnalysisManagerModuleProxy::name () inline static
Definition at line 599 of file IR/PassManager.h.
operator=()
FunctionAnalysisManagerModuleProxy & llvm::FunctionAnalysisManagerModuleProxy::operator= (FunctionAnalysisManagerModuleProxy RHS) inline
Definition at line 611 of file IR/PassManager.h.
References FunctionAnalysisManagerModuleProxy(), and std::swap().
run()
FunctionAnalysisManagerModuleProxy::Result FunctionAnalysisManagerModuleProxy::run (Module & M)
Run the analysis pass and create our proxy result object.
This doesn't do any interesting work, it is primarily used to insert our proxy result object into the module analysis cache so that we can proxy invalidation to the function analysis manager.
In debug builds, it will also assert that the analysis manager is empty as no queries should arrive at the function analysis manager prior to this analysis being requested.
Definition at line 19 of file PassManager.cpp.
The documentation for this class was generated from the following files:
IR/PassManager.h
PassManager.cpp