LLVM: llvm::MCSectionCOFF Class Reference
LLVM API Documentation
llvm::MCSectionCOFF Class Reference
MCSectionCOFF - This represents a section on Windows.
#include <MCSectionCOFF.h>
Public Member Functions
bool ShouldOmitSectionDirective (StringRef Name, const MCAsmInfo &MAI) const
StringRef getSectionName () const
std::string getLabelBeginName () const override
std::string getLabelEndName () const override
unsigned getCharacteristics () const
MCSymbol * getCOMDATSymbol () const
int getSelection () const
void setSelection (int Selection) const
void PrintSwitchToSection (const MCAsmInfo &MAI, raw_ostream &OS, const MCExpr *Subsection) const override
bool UseCodeAlign () const override
bool isVirtualSection () const override
Public Member Functions inherited from llvm::MCSection
virtual ~MCSection ()
SectionKind getKind () const
SectionVariant getVariant () const
virtual bool isBaseAddressKnownZero () const
Static Public Member Functions
static bool classof (const MCSection *S)
Friends
class MCContext
Additional Inherited Members
Public Types inherited from llvm::MCSection
enum SectionVariant { SV_COFF = 0 , SV_ELF , SV_MachO }
Protected Member Functions inherited from llvm::MCSection
MCSection (SectionVariant V, SectionKind K)
Protected Attributes inherited from llvm::MCSection
SectionVariant Variant
SectionKind Kind
Detailed Description
MCSectionCOFF - This represents a section on Windows.
Definition at line 25 of file MCSectionCOFF.h.
Member Function Documentation
classof()
bool llvm::MCSectionCOFF::classof (const MCSection * S) inline static
Definition at line 80 of file MCSectionCOFF.h.
References llvm::MCSection::getVariant(), and llvm::MCSection::SV_COFF.
getCharacteristics()
unsigned llvm::MCSectionCOFF::getCharacteristics () const inline
Definition at line 69 of file MCSectionCOFF.h.
Referenced by llvm::MCContext::getAssociativeCOFFSection(), llvm::WinEH::getUnwindInfoSection(), isVirtualSection(), and PrintSwitchToSection().
getCOMDATSymbol()
MCSymbol * llvm::MCSectionCOFF::getCOMDATSymbol () const inline
Definition at line 70 of file MCSectionCOFF.h.
Referenced by llvm::WinEH::getUnwindInfoSection().
getLabelBeginName()
std::string llvm::MCSectionCOFF::getLabelBeginName () const inline override virtual
Implements llvm::MCSection.
Definition at line 63 of file MCSectionCOFF.h.
getLabelEndName()
std::string llvm::MCSectionCOFF::getLabelEndName () const inline override virtual
Implements llvm::MCSection.
Definition at line 66 of file MCSectionCOFF.h.
getSectionName()
StringRef llvm::MCSectionCOFF::getSectionName () const inline
Definition at line 62 of file MCSectionCOFF.h.
Referenced by llvm::MCContext::getAssociativeCOFFSection(), and PrintSwitchToSection().
getSelection()
int llvm::MCSectionCOFF::getSelection () const inline
Definition at line 71 of file MCSectionCOFF.h.
isVirtualSection()
bool MCSectionCOFF::isVirtualSection () const override virtual
isVirtualSection - Check whether this section is "virtual", that is has no actual object file contents.
Implements llvm::MCSection.
Definition at line 106 of file MCSectionCOFF.cpp.
References getCharacteristics(), and llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA.
PrintSwitchToSection()
void MCSectionCOFF::PrintSwitchToSection (const MCAsmInfo & MAI, raw_ostream & OS, const MCExpr * Subsection) const override virtual
Implements llvm::MCSection.
Definition at line 39 of file MCSectionCOFF.cpp.
References getCharacteristics(), getSectionName(), llvm::COFF::IMAGE_COMDAT_SELECT_ANY, llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, llvm::COFF::IMAGE_COMDAT_SELECT_EXACT_MATCH, llvm::COFF::IMAGE_COMDAT_SELECT_LARGEST, llvm::COFF::IMAGE_COMDAT_SELECT_NEWEST, llvm::COFF::IMAGE_COMDAT_SELECT_NODUPLICATES, llvm::COFF::IMAGE_COMDAT_SELECT_SAME_SIZE, llvm::COFF::IMAGE_SCN_CNT_INITIALIZED_DATA, llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA, llvm::COFF::IMAGE_SCN_LNK_COMDAT, llvm::COFF::IMAGE_SCN_LNK_REMOVE, llvm::COFF::IMAGE_SCN_MEM_EXECUTE, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_SHARED, llvm::COFF::IMAGE_SCN_MEM_WRITE, and ShouldOmitSectionDirective().
setSelection()
void MCSectionCOFF::setSelection (int Selection) const
Definition at line 33 of file MCSectionCOFF.cpp.
References llvm::COFF::IMAGE_SCN_LNK_COMDAT.
ShouldOmitSectionDirective()
bool MCSectionCOFF::ShouldOmitSectionDirective (StringRef Name, const MCAsmInfo & MAI) const
ShouldOmitSectionDirective - Decides whether a '.section' directive should be printed before the section name
Definition at line 21 of file MCSectionCOFF.cpp.
References Name.
Referenced by PrintSwitchToSection().
UseCodeAlign()
bool MCSectionCOFF::UseCodeAlign () const override virtual
Implements llvm::MCSection.
Definition at line 102 of file MCSectionCOFF.cpp.
References llvm::MCSection::getKind(), and llvm::SectionKind::isText().
Friends And Related Symbol Documentation
MCContext
friend class MCContext friend
Definition at line 46 of file MCSectionCOFF.h.
References MCContext, and llvm::MCSection::SV_COFF.
Referenced by MCContext.
The documentation for this class was generated from the following files:
MCSectionCOFF.h
MCSectionCOFF.cpp