LLVM: llvm::PassManagerBuilder Class Reference
LLVM API Documentation
llvm::PassManagerBuilder Class Reference
#include <PassManagerBuilder.h>
Public Types
enum ExtensionPointTy {
EP_EarlyAsPossible , EP_ModuleOptimizerEarly , EP_LoopOptimizerEnd , EP_ScalarOptimizerLate ,
EP_OptimizerLast , EP_EnabledOnOptLevel0 , EP_Peephole
}
typedef void(* ExtensionFn) (const PassManagerBuilder &Builder, PassManagerBase &PM)
Public Member Functions
PassManagerBuilder ()
~PassManagerBuilder ()
void addExtension (ExtensionPointTy Ty, ExtensionFn Fn)
void populateFunctionPassManager (FunctionPassManager &FPM)
void populateModulePassManager (PassManagerBase &MPM)
populateModulePassManager - This sets up the primary pass manager.
void populateLTOPassManager (PassManagerBase &PM, TargetMachine *TM=nullptr)
Static Public Member Functions
static void addGlobalExtension (ExtensionPointTy Ty, ExtensionFn Fn)
Public Attributes
unsigned OptLevel
unsigned SizeLevel
TargetLibraryInfo * LibraryInfo
Pass * Inliner
bool DisableTailCalls
bool DisableUnitAtATime
bool DisableUnrollLoops
bool BBVectorize
bool SLPVectorize
bool LoopVectorize
bool RerollLoops
bool LoadCombine
bool DisableGVNLoadPRE
bool VerifyInput
bool VerifyOutput
bool StripDebug
bool MergeFunctions
Detailed Description
PassManagerBuilder - This class is used to set up a standard optimization sequence for languages like C and C++, allowing some APIs to customize the pass sequence in various ways. A simple example of using it would be:
PassManagerBuilder Builder; Builder.OptLevel = 2; Builder.populateFunctionPassManager(FPM); Builder.populateModulePassManager(MPM);
In addition to setting up the basic passes, PassManagerBuilder allows frontends to vend a plugin API, where plugins are allowed to add extensions to the default pass manager. They do this by specifying where in the pass pipeline they want to be added, along with a callback function that adds the pass(es). For example, a plugin that wanted to add a loop optimization could do something like this:
static void addMyLoopPass(const PMBuilder &Builder, PassManagerBase &PM) { if (Builder.getOptLevel() > 2 && Builder.getOptSizeLevel() == 0) PM.add(createMyAwesomePass()); } ... Builder.addExtension(PassManagerBuilder::EP_LoopOptimizerEnd, addMyLoopPass); ...
Definition at line 57 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Member Typedef Documentation
ExtensionFn
typedef void(* llvm::PassManagerBuilder::ExtensionFn) (const PassManagerBuilder &Builder, PassManagerBase &PM)
Extensions are passed the builder itself (so they can see how it is configured) as well as the pass manager to add stuff to.
Definition at line 61 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Member Enumeration Documentation
ExtensionPointTy
enum llvm::PassManagerBuilder::ExtensionPointTy
Enumerator
EP_EarlyAsPossible
EP_EarlyAsPossible - This extension point allows adding passes before any other transformations, allowing them to see the code as it is coming out of the frontend.
EP_ModuleOptimizerEarly
EP_ModuleOptimizerEarly - This extension point allows adding passes just before the main module-level optimization passes.
EP_LoopOptimizerEnd
EP_LoopOptimizerEnd - This extension point allows adding loop passes to the end of the loop optimizer.
EP_ScalarOptimizerLate
EP_ScalarOptimizerLate - This extension point allows adding optimization passes after most of the main optimizations, but before the last cleanup-ish optimizations.
EP_OptimizerLast
EP_OptimizerLast – This extension point allows adding passes that run after everything else.
EP_EnabledOnOptLevel0
EP_EnabledOnOptLevel0 - This extension point allows adding passes that should not be disabled by O0 optimization level. The passes will be inserted after the inlining pass.
EP_Peephole
EP_Peephole - This extension point allows adding passes that perform peephole optimizations similar to the instruction combiner. These passes will be inserted after each instance of the instruction combiner pass.
Definition at line 63 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Constructor & Destructor Documentation
PassManagerBuilder()
PassManagerBuilder::PassManagerBuilder ()
Definition at line 81 of file PassManagerBuilder.cpp.
References BBVectorize, DisableGVNLoadPRE, DisableTailCalls, DisableUnitAtATime, DisableUnrollLoops, Inliner, LibraryInfo, LoadCombine, LoopVectorize, MergeFunctions, OptLevel, RerollLoops, RunBBVectorization, RunLoadCombine, RunLoopRerolling, RunLoopVectorization, RunSLPVectorization, SizeLevel, SLPVectorize, StripDebug, VerifyInput, and VerifyOutput.
~PassManagerBuilder()
PassManagerBuilder::~PassManagerBuilder ()
Definition at line 101 of file PassManagerBuilder.cpp.
References Inliner, and LibraryInfo.
Member Function Documentation
addExtension()
void PassManagerBuilder::addExtension (ExtensionPointTy Ty, ExtensionFn Fn)
Definition at line 116 of file PassManagerBuilder.cpp.
addGlobalExtension()
void PassManagerBuilder::addGlobalExtension (PassManagerBuilder::ExtensionPointTy Ty, PassManagerBuilder::ExtensionFn Fn) static
Adds an extension that will be used by all PassManagerBuilder instances. This is intended to be used by plugins, to register a set of optimisations to run automatically.
Definition at line 110 of file PassManagerBuilder.cpp.
References GlobalExtensions.
Referenced by llvm::RegisterStandardPasses::RegisterStandardPasses().
populateFunctionPassManager()
void PassManagerBuilder::populateFunctionPassManager (FunctionPassManager & FPM)
populateFunctionPassManager - This fills in the function pass manager, which is expected to be run on each function immediately as it is generated. The idea is to reduce the size of the IR in memory.
Definition at line 142 of file PassManagerBuilder.cpp.
References llvm::legacy::FunctionPassManager::add(), llvm::createCFGSimplificationPass(), llvm::createEarlyCSEPass(), llvm::createLowerExpectIntrinsicPass(), llvm::createScalarReplAggregatesPass(), llvm::createSROAPass(), EP_EarlyAsPossible, LibraryInfo, OptLevel, and UseNewSROA.
Referenced by LLVMPassManagerBuilderPopulateFunctionPassManager().
populateLTOPassManager()
void PassManagerBuilder::populateLTOPassManager (PassManagerBase & PM, TargetMachine * TM = nullptr)
Definition at line 480 of file PassManagerBuilder.cpp.
References llvm::legacy::PassManagerBase::add(), llvm::createDebugInfoVerifierPass(), llvm::createStripSymbolsPass(), llvm::createVerifierPass(), LibraryInfo, OptLevel, StripDebug, VerifyInput, and VerifyOutput.
Referenced by LLVMPassManagerBuilderPopulateLTOPassManager().
populateModulePassManager()
void PassManagerBuilder::populateModulePassManager (PassManagerBase & MPM)
populateModulePassManager - This sets up the primary pass manager.
Definition at line 161 of file PassManagerBuilder.cpp.
References llvm::legacy::PassManagerBase::add(), BBVectorize, llvm::createAggressiveDCEPass(), llvm::createAlignmentFromAssumptionsPass(), llvm::createArgumentPromotionPass(), llvm::createBarrierNoopPass(), llvm::createBBVectorizePass(), llvm::createCFGSimplificationPass(), llvm::createConstantMergePass(), llvm::createCorrelatedValuePropagationPass(), llvm::createDeadArgEliminationPass(), llvm::createDeadStoreEliminationPass(), llvm::createEarlyCSEPass(), llvm::createFunctionAttrsPass(), llvm::createGlobalDCEPass(), llvm::createGlobalOptimizerPass(), llvm::createGVNPass(), llvm::createIndVarSimplifyPass(), llvm::createInstructionCombiningPass(), llvm::createIPSCCPPass(), llvm::createJumpThreadingPass(), llvm::createLICMPass(), llvm::createLoadCombinePass(), llvm::createLoopDeletionPass(), llvm::createLoopIdiomPass(), llvm::createLoopRerollPass(), llvm::createLoopRotatePass(), llvm::createLoopUnrollPass(), llvm::createLoopUnswitchPass(), llvm::createLoopVectorizePass(), llvm::createMemCpyOptPass(), llvm::createMergedLoadStoreMotionPass(), llvm::createMergeFunctionsPass(), llvm::createPruneEHPass(), llvm::createReassociatePass(), llvm::createScalarReplAggregatesPass(), llvm::createSCCPPass(), llvm::createSimpleLoopUnrollPass(), llvm::createSLPVectorizerPass(), llvm::createSROAPass(), llvm::createStripDeadPrototypesPass(), llvm::createTailCallEliminationPass(), DisableGVNLoadPRE, DisableTailCalls, DisableUnitAtATime, DisableUnrollLoops, EnableMLSM, EP_EnabledOnOptLevel0, EP_LoopOptimizerEnd, EP_ModuleOptimizerEarly, EP_OptimizerLast, EP_Peephole, EP_ScalarOptimizerLate, ExtraVectorizerPasses, GlobalExtensions, Inliner, LibraryInfo, LoadCombine, LoopVectorize, MergeFunctions, OptLevel, RerollLoops, RunSLPAfterLoopVectorization, SizeLevel, SLPVectorize, UseGVNAfterVectorization, and UseNewSROA.
Referenced by LLVMPassManagerBuilderPopulateModulePassManager().
Member Data Documentation
BBVectorize
bool llvm::PassManagerBuilder::BBVectorize
Definition at line 117 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateModulePassManager().
DisableGVNLoadPRE
bool llvm::PassManagerBuilder::DisableGVNLoadPRE
Definition at line 122 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateModulePassManager().
DisableTailCalls
bool llvm::PassManagerBuilder::DisableTailCalls
Definition at line 114 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateModulePassManager().
DisableUnitAtATime
bool llvm::PassManagerBuilder::DisableUnitAtATime
Definition at line 115 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by LLVMPassManagerBuilderSetDisableUnitAtATime(), PassManagerBuilder(), and populateModulePassManager().
DisableUnrollLoops
bool llvm::PassManagerBuilder::DisableUnrollLoops
Definition at line 116 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by LLVMPassManagerBuilderSetDisableUnrollLoops(), PassManagerBuilder(), and populateModulePassManager().
Inliner
Pass* llvm::PassManagerBuilder::Inliner
Inliner - Specifies the inliner to use. If this is non-null, it is added to the per-module passes.
Definition at line 112 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by LLVMPassManagerBuilderPopulateLTOPassManager(), LLVMPassManagerBuilderUseInlinerWithThreshold(), PassManagerBuilder(), populateModulePassManager(), and ~PassManagerBuilder().
LibraryInfo
TargetLibraryInfo* llvm::PassManagerBuilder::LibraryInfo
LibraryInfo - Specifies information about the runtime library for the optimizer. If this is non-null, it is added to both the function and per-module pass pipeline.
Definition at line 108 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), populateFunctionPassManager(), populateLTOPassManager(), populateModulePassManager(), and ~PassManagerBuilder().
LoadCombine
bool llvm::PassManagerBuilder::LoadCombine
Definition at line 121 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateModulePassManager().
LoopVectorize
bool llvm::PassManagerBuilder::LoopVectorize
Definition at line 119 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateModulePassManager().
MergeFunctions
bool llvm::PassManagerBuilder::MergeFunctions
Definition at line 126 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateModulePassManager().
OptLevel
unsigned llvm::PassManagerBuilder::OptLevel
The Optimization Level - Specify the basic optimization level. 0 = -O0, 1 = -O1, 2 = -O2, 3 = -O3
Definition at line 99 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by LLVMPassManagerBuilderSetOptLevel(), PassManagerBuilder(), populateFunctionPassManager(), populateLTOPassManager(), and populateModulePassManager().
RerollLoops
bool llvm::PassManagerBuilder::RerollLoops
Definition at line 120 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateModulePassManager().
SizeLevel
unsigned llvm::PassManagerBuilder::SizeLevel
SizeLevel - How much we're optimizing for size. 0 = none, 1 = -Os, 2 = -Oz
Definition at line 103 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by LLVMPassManagerBuilderSetSizeLevel(), PassManagerBuilder(), and populateModulePassManager().
SLPVectorize
bool llvm::PassManagerBuilder::SLPVectorize
Definition at line 118 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateModulePassManager().
StripDebug
bool llvm::PassManagerBuilder::StripDebug
Definition at line 125 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateLTOPassManager().
VerifyInput
bool llvm::PassManagerBuilder::VerifyInput
Definition at line 123 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateLTOPassManager().
VerifyOutput
bool llvm::PassManagerBuilder::VerifyOutput
Definition at line 124 of file llvm/Transforms/IPO/PassManagerBuilder.h.
Referenced by PassManagerBuilder(), and populateLTOPassManager().
The documentation for this class was generated from the following files:
llvm/Transforms/IPO/PassManagerBuilder.h
PassManagerBuilder.cpp