LLVM: llvm::format_object_base Class Reference
LLVM API Documentation
llvm::format_object_base Class Reference abstract
#include <Format.h>
Public Member Functions
format_object_base (const char *fmt)
unsigned print (char *Buffer, unsigned BufferSize) const
Protected Member Functions
~format_object_base ()
virtual void home ()
virtual int snprint (char *Buffer, unsigned BufferSize) const =0
Call snprintf() for this object, on the given buffer and size.
Protected Attributes
const char * Fmt
Detailed Description
This is a helper class used for handling formatted output. It is the abstract base class of a templated derived class.
Definition at line 43 of file Format.h.
Constructor & Destructor Documentation
~format_object_base()
llvm::format_object_base::~format_object_base () inline protected
Definition at line 46 of file Format.h.
format_object_base()
llvm::format_object_base::format_object_base (const char * fmt) inline
Definition at line 53 of file Format.h.
References Fmt.
Referenced by llvm::format_object1< T >::format_object1(), llvm::format_object2< T1, T2 >::format_object2(), llvm::format_object3< T1, T2, T3 >::format_object3(), llvm::format_object4< T1, T2, T3, T4 >::format_object4(), llvm::format_object5< T1, T2, T3, T4, T5 >::format_object5(), and llvm::format_object6< T1, T2, T3, T4, T5, T6 >::format_object6().
Member Function Documentation
home()
void format_object_base::home () protected virtual
Definition at line 480 of file raw_ostream.cpp.
print()
unsigned llvm::format_object_base::print (char * Buffer, unsigned BufferSize) const inline
Format the object into the specified buffer. On success, this returns the length of the formatted string. If the buffer is too small, this returns a length to retry with, which will be larger than BufferSize.
Definition at line 58 of file Format.h.
References N, and snprint().
Referenced by llvm::raw_ostream::operator<<().
snprint()
virtual int llvm::format_object_base::snprint (char * Buffer, unsigned BufferSize) const protected pure virtual
Call snprintf() for this object, on the given buffer and size.
Implemented in llvm::format_object1< T >, llvm::format_object2< T1, T2 >, llvm::format_object3< T1, T2, T3 >, llvm::format_object4< T1, T2, T3, T4 >, llvm::format_object5< T1, T2, T3, T4, T5 >, and llvm::format_object6< T1, T2, T3, T4, T5, T6 >.
Referenced by print().
Member Data Documentation
Fmt
const char* llvm::format_object_base::Fmt protected
Definition at line 45 of file Format.h.
Referenced by llvm::format_object6< T1, T2, T3, T4, T5, T6 >::format_object6(), format_object_base(), llvm::format_object1< T >::snprint(), llvm::format_object2< T1, T2 >::snprint(), llvm::format_object3< T1, T2, T3 >::snprint(), llvm::format_object4< T1, T2, T3, T4 >::snprint(), llvm::format_object5< T1, T2, T3, T4, T5 >::snprint(), and llvm::format_object6< T1, T2, T3, T4, T5, T6 >::snprint().
The documentation for this class was generated from the following files:
Format.h
raw_ostream.cpp