LLVM: llvm::BitcodeReaderMDValueList Class Reference
LLVM API Documentation
llvm::BitcodeReaderMDValueList Class Reference
#include <BitcodeReader.h>
Public Member Functions
BitcodeReaderMDValueList (LLVMContext &C)
unsigned size () const
void resize (unsigned N)
void push_back (Metadata *MD)
void clear ()
Metadata * back () const
void pop_back ()
bool empty () const
Metadata * operator[] (unsigned i) const
void shrinkTo (unsigned N)
Metadata * getValueFwdRef (unsigned Idx)
void AssignValue (Metadata *MD, unsigned Idx)
void tryToResolveCycles ()
Detailed Description
Definition at line 99 of file BitcodeReader.h.
Constructor & Destructor Documentation
BitcodeReaderMDValueList()
llvm::BitcodeReaderMDValueList::BitcodeReaderMDValueList (LLVMContext & C) inline
Definition at line 108 of file BitcodeReader.h.
Member Function Documentation
AssignValue()
void BitcodeReaderMDValueList::AssignValue (Metadata * MD, unsigned Idx)
Definition at line 512 of file BitcodeReader.cpp.
References llvm::cast(), llvm::MDNode::deleteTemporary(), llvm::TrackingMDRef::get(), push_back(), llvm::MDNodeFwdDecl::replaceAllUsesWith(), llvm::TrackingMDRef::reset(), resize(), and size().
back()
Metadata * llvm::BitcodeReaderMDValueList::back () const inline
Definition at line 116 of file BitcodeReader.h.
clear()
void llvm::BitcodeReaderMDValueList::clear () inline
Definition at line 115 of file BitcodeReader.h.
empty()
bool llvm::BitcodeReaderMDValueList::empty () const inline
Definition at line 118 of file BitcodeReader.h.
getValueFwdRef()
Metadata * BitcodeReaderMDValueList::getValueFwdRef (unsigned Idx)
Definition at line 534 of file BitcodeReader.cpp.
References llvm::MDNode::getTemporary(), llvm::None, resize(), and size().
operator[]()
Metadata * llvm::BitcodeReaderMDValueList::operator[] (unsigned i) const inline
Definition at line 120 of file BitcodeReader.h.
pop_back()
void llvm::BitcodeReaderMDValueList::pop_back () inline
Definition at line 117 of file BitcodeReader.h.
push_back()
void llvm::BitcodeReaderMDValueList::push_back (Metadata * MD) inline
Definition at line 114 of file BitcodeReader.h.
Referenced by AssignValue().
resize()
void llvm::BitcodeReaderMDValueList::resize (unsigned N) inline
Definition at line 113 of file BitcodeReader.h.
References N.
Referenced by AssignValue(), and getValueFwdRef().
shrinkTo()
void llvm::BitcodeReaderMDValueList::shrinkTo (unsigned N) inline
Definition at line 125 of file BitcodeReader.h.
References N, and size().
size()
unsigned llvm::BitcodeReaderMDValueList::size () const inline
Definition at line 112 of file BitcodeReader.h.
Referenced by AssignValue(), getValueFwdRef(), and shrinkTo().
tryToResolveCycles()
void BitcodeReaderMDValueList::tryToResolveCycles ()
Definition at line 557 of file BitcodeReader.cpp.
References llvm::dyn_cast_or_null(), I, llvm::isa(), and N.
The documentation for this class was generated from the following files:
BitcodeReader.h
BitcodeReader.cpp