LLVM: llvm::AMDGPUSubtarget Class Reference
LLVM API Documentation
llvm::AMDGPUSubtarget Class Reference
#include <AMDGPUSubtarget.h>
Public Types
enum Generation {
R600 = 0 , R700 , EVERGREEN , NORTHERN_ISLANDS ,
SOUTHERN_ISLANDS , SEA_ISLANDS , VOLCANIC_ISLANDS
}
enum { FIXED_SGPR_COUNT_FOR_INIT_BUG = 80 }
Public Member Functions
AMDGPUSubtarget (StringRef TT, StringRef CPU, StringRef FS, TargetMachine &TM)
AMDGPUSubtarget & initializeSubtargetDependencies (StringRef GPU, StringRef FS)
const AMDGPUFrameLowering * getFrameLowering () const override
const AMDGPUInstrInfo * getInstrInfo () const override
const AMDGPURegisterInfo * getRegisterInfo () const override
AMDGPUTargetLowering * getTargetLowering () const override
const DataLayout * getDataLayout () const override
const InstrItineraryData * getInstrItineraryData () const override
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool is64bit () const
bool hasVertexCache () const
short getTexVTXClauseSize () const
Generation getGeneration () const
bool hasHWFP64 () const
bool hasCaymanISA () const
bool hasFP32Denormals () const
bool hasFP64Denormals () const
bool hasFlatAddressSpace () const
bool hasBFE () const
bool hasBFI () const
bool hasBFM () const
bool hasBCNT (unsigned Size) const
bool hasMulU24 () const
bool hasMulI24 () const
bool hasFFBL () const
bool hasFFBH () const
bool IsIRStructurizerEnabled () const
bool isPromoteAllocaEnabled () const
bool isIfCvtEnabled () const
bool loadStoreOptEnabled () const
unsigned getWavefrontSize () const
unsigned getStackEntrySize () const
bool hasCFAluBug () const
int getLocalMemorySize () const
bool hasSGPRInitBug () const
int getLDSBankCount () const
unsigned getAmdKernelCodeChipID () const
bool enableMachineScheduler () const override
void overrideSchedPolicy (MachineSchedPolicy &Policy, MachineInstr *begin, MachineInstr *end, unsigned NumRegionInstrs) const override
bool isTargetELF () const
StringRef getDeviceName () const
bool dumpCode () const
bool r600ALUEncoding () const
bool isAmdHsaOS () const
bool isVGPRSpillingEnabled (const SIMachineFunctionInfo *MFI) const
unsigned getMaxWavesPerCU () const
Detailed Description
Definition at line 35 of file AMDGPUSubtarget.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
FIXED_SGPR_COUNT_FOR_INIT_BUG
Definition at line 48 of file AMDGPUSubtarget.h.
Generation
enum llvm::AMDGPUSubtarget::Generation
Enumerator
R600
R700
EVERGREEN
NORTHERN_ISLANDS
SOUTHERN_ISLANDS
SEA_ISLANDS
VOLCANIC_ISLANDS
Definition at line 38 of file AMDGPUSubtarget.h.
Constructor & Destructor Documentation
AMDGPUSubtarget()
AMDGPUSubtarget::AMDGPUSubtarget (StringRef TT, StringRef CPU, StringRef FS, TargetMachine & TM)
Definition at line 74 of file AMDGPUSubtarget.cpp.
References AMDGPUSubtarget(), computeDataLayout(), getGeneration(), initializeSubtargetDependencies(), NORTHERN_ISLANDS, R600, and true.
Referenced by AMDGPUSubtarget().
Member Function Documentation
dumpCode()
bool llvm::AMDGPUSubtarget::dumpCode () const inline
Definition at line 239 of file AMDGPUSubtarget.h.
Referenced by llvm::AMDGPUAsmPrinter::AMDGPUAsmPrinter(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
enableMachineScheduler()
bool llvm::AMDGPUSubtarget::enableMachineScheduler () const inline override
Definition at line 222 of file AMDGPUSubtarget.h.
References getGeneration(), and NORTHERN_ISLANDS.
getAmdKernelCodeChipID()
unsigned AMDGPUSubtarget::getAmdKernelCodeChipID () const
Definition at line 114 of file AMDGPUSubtarget.cpp.
References getGeneration(), llvm_unreachable, and SEA_ISLANDS.
getDataLayout()
const DataLayout * llvm::AMDGPUSubtarget::getDataLayout () const inline override
Definition at line 99 of file AMDGPUSubtarget.h.
getDeviceName()
StringRef llvm::AMDGPUSubtarget::getDeviceName () const inline
Definition at line 235 of file AMDGPUSubtarget.h.
getFrameLowering()
const AMDGPUFrameLowering * llvm::AMDGPUSubtarget::getFrameLowering () const inline override
Definition at line 87 of file AMDGPUSubtarget.h.
getGeneration()
Generation llvm::AMDGPUSubtarget::getGeneration () const inline
Definition at line 118 of file AMDGPUSubtarget.h.
Referenced by AMDGPUSubtarget(), enableMachineScheduler(), getAmdKernelCodeChipID(), getMaxWavesPerCU(), getStackEntrySize(), hasBCNT(), hasBFE(), hasBFI(), hasCFAluBug(), hasFFBH(), hasFFBL(), hasMulI24(), hasMulU24(), initializeSubtargetDependencies(), overrideSchedPolicy(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
getInstrInfo()
const AMDGPUInstrInfo * llvm::AMDGPUSubtarget::getInstrInfo () const inline override
Definition at line 90 of file AMDGPUSubtarget.h.
getInstrItineraryData()
const InstrItineraryData * llvm::AMDGPUSubtarget::getInstrItineraryData () const inline override
Definition at line 100 of file AMDGPUSubtarget.h.
getLDSBankCount()
int llvm::AMDGPUSubtarget::getLDSBankCount () const inline
Definition at line 216 of file AMDGPUSubtarget.h.
getLocalMemorySize()
int llvm::AMDGPUSubtarget::getLocalMemorySize () const inline
Definition at line 208 of file AMDGPUSubtarget.h.
getMaxWavesPerCU()
unsigned llvm::AMDGPUSubtarget::getMaxWavesPerCU () const inline
Definition at line 250 of file AMDGPUSubtarget.h.
References getGeneration(), llvm_unreachable, and SOUTHERN_ISLANDS.
getRegisterInfo()
const AMDGPURegisterInfo * llvm::AMDGPUSubtarget::getRegisterInfo () const inline override
Definition at line 93 of file AMDGPUSubtarget.h.
getStackEntrySize()
unsigned AMDGPUSubtarget::getStackEntrySize () const
Definition at line 100 of file AMDGPUSubtarget.cpp.
References getGeneration(), getWavefrontSize(), hasCaymanISA(), llvm_unreachable, and NORTHERN_ISLANDS.
getTargetLowering()
AMDGPUTargetLowering * llvm::AMDGPUSubtarget::getTargetLowering () const inline override
Definition at line 96 of file AMDGPUSubtarget.h.
getTexVTXClauseSize()
short llvm::AMDGPUSubtarget::getTexVTXClauseSize () const inline
Definition at line 114 of file AMDGPUSubtarget.h.
getWavefrontSize()
unsigned llvm::AMDGPUSubtarget::getWavefrontSize () const inline
Definition at line 197 of file AMDGPUSubtarget.h.
Referenced by getStackEntrySize().
hasBCNT()
bool llvm::AMDGPUSubtarget::hasBCNT (unsigned Size) const inline
Definition at line 154 of file AMDGPUSubtarget.h.
References EVERGREEN, getGeneration(), and SOUTHERN_ISLANDS.
hasBFE()
bool llvm::AMDGPUSubtarget::hasBFE () const inline
Definition at line 142 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
Referenced by hasBFM().
hasBFI()
bool llvm::AMDGPUSubtarget::hasBFI () const inline
Definition at line 146 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
hasBFM()
bool llvm::AMDGPUSubtarget::hasBFM () const inline
Definition at line 150 of file AMDGPUSubtarget.h.
References hasBFE().
hasCaymanISA()
bool llvm::AMDGPUSubtarget::hasCaymanISA () const inline
Definition at line 126 of file AMDGPUSubtarget.h.
Referenced by getStackEntrySize(), and hasMulI24().
hasCFAluBug()
bool llvm::AMDGPUSubtarget::hasCFAluBug () const inline
Definition at line 203 of file AMDGPUSubtarget.h.
References getGeneration(), and NORTHERN_ISLANDS.
hasFFBH()
bool llvm::AMDGPUSubtarget::hasFFBH () const inline
Definition at line 177 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
hasFFBL()
bool llvm::AMDGPUSubtarget::hasFFBL () const inline
Definition at line 173 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
hasFlatAddressSpace()
bool llvm::AMDGPUSubtarget::hasFlatAddressSpace () const inline
Definition at line 138 of file AMDGPUSubtarget.h.
hasFP32Denormals()
bool llvm::AMDGPUSubtarget::hasFP32Denormals () const inline
Definition at line 130 of file AMDGPUSubtarget.h.
hasFP64Denormals()
bool llvm::AMDGPUSubtarget::hasFP64Denormals () const inline
Definition at line 134 of file AMDGPUSubtarget.h.
hasHWFP64()
bool llvm::AMDGPUSubtarget::hasHWFP64 () const inline
Definition at line 122 of file AMDGPUSubtarget.h.
hasMulI24()
bool llvm::AMDGPUSubtarget::hasMulI24 () const inline
Definition at line 168 of file AMDGPUSubtarget.h.
References getGeneration(), hasCaymanISA(), and SOUTHERN_ISLANDS.
hasMulU24()
bool llvm::AMDGPUSubtarget::hasMulU24 () const inline
Definition at line 164 of file AMDGPUSubtarget.h.
References EVERGREEN, and getGeneration().
hasSGPRInitBug()
bool llvm::AMDGPUSubtarget::hasSGPRInitBug () const inline
Definition at line 212 of file AMDGPUSubtarget.h.
hasVertexCache()
bool llvm::AMDGPUSubtarget::hasVertexCache () const inline
Definition at line 110 of file AMDGPUSubtarget.h.
initializeSubtargetDependencies()
AMDGPUSubtarget & AMDGPUSubtarget::initializeSubtargetDependencies (StringRef GPU, StringRef FS)
Definition at line 49 of file AMDGPUSubtarget.cpp.
References getGeneration(), NORTHERN_ISLANDS, and ParseSubtargetFeatures().
Referenced by AMDGPUSubtarget().
is64bit()
bool llvm::AMDGPUSubtarget::is64bit () const inline
Definition at line 106 of file AMDGPUSubtarget.h.
isAmdHsaOS()
bool llvm::AMDGPUSubtarget::isAmdHsaOS () const inline
Definition at line 245 of file AMDGPUSubtarget.h.
References llvm::Triple::AMDHSA.
Referenced by llvm::AMDGPUAsmPrinter::runOnMachineFunction().
isIfCvtEnabled()
bool llvm::AMDGPUSubtarget::isIfCvtEnabled () const inline
Definition at line 189 of file AMDGPUSubtarget.h.
IsIRStructurizerEnabled()
bool llvm::AMDGPUSubtarget::IsIRStructurizerEnabled () const inline
Definition at line 181 of file AMDGPUSubtarget.h.
isPromoteAllocaEnabled()
bool llvm::AMDGPUSubtarget::isPromoteAllocaEnabled () const inline
Definition at line 185 of file AMDGPUSubtarget.h.
isTargetELF()
bool llvm::AMDGPUSubtarget::isTargetELF () const inline
Definition at line 231 of file AMDGPUSubtarget.h.
isVGPRSpillingEnabled()
bool AMDGPUSubtarget::isVGPRSpillingEnabled (const SIMachineFunctionInfo * MFI) const
Definition at line 121 of file AMDGPUSubtarget.cpp.
References ShaderType::COMPUTE, and llvm::AMDGPUMachineFunction::getShaderType().
loadStoreOptEnabled()
bool llvm::AMDGPUSubtarget::loadStoreOptEnabled () const inline
Definition at line 193 of file AMDGPUSubtarget.h.
overrideSchedPolicy()
void AMDGPUSubtarget::overrideSchedPolicy (MachineSchedPolicy & Policy, MachineInstr * begin, MachineInstr * end, unsigned NumRegionInstrs) const override
Definition at line 126 of file AMDGPUSubtarget.cpp.
References getGeneration(), llvm::MachineSchedPolicy::OnlyBottomUp, llvm::MachineSchedPolicy::OnlyTopDown, llvm::MachineSchedPolicy::ShouldTrackPressure, and SOUTHERN_ISLANDS.
ParseSubtargetFeatures()
void llvm::AMDGPUSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
Referenced by initializeSubtargetDependencies().
r600ALUEncoding()
bool llvm::AMDGPUSubtarget::r600ALUEncoding () const inline
Definition at line 242 of file AMDGPUSubtarget.h.
The documentation for this class was generated from the following files:
AMDGPUSubtarget.h
AMDGPUSubtarget.cpp