LLVM: llvm::DIELabel Class Reference
LLVM API Documentation
llvm::DIELabel Class Reference
DIELabel - A label DIE.
#include <DIE.h>
Public Member Functions
DIELabel (const MCSymbol *L)
void EmitValue (AsmPrinter *AP, dwarf::Form Form) const override
const MCSymbol * getValue () const
unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const override
void print (raw_ostream &O) const override
Public Member Functions inherited from llvm::DIEValue
Type getType () const
void dump () const
Static Public Member Functions
static bool classof (const DIEValue *L)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum Type {
isInteger , isString , isExpr , isLabel ,
isDelta , isEntry , isTypeSignature , isBlock ,
isLoc , isLocList
}
Protected Member Functions inherited from llvm::DIEValue
DIEValue (Type T)
virtual ~DIEValue ()
Protected Attributes inherited from llvm::DIEValue
Type Ty
Detailed Description
DIELabel - A label DIE.
Definition at line 326 of file DIE.h.
Constructor & Destructor Documentation
DIELabel()
llvm::DIELabel::DIELabel (const MCSymbol * L) inline explicit
Definition at line 330 of file DIE.h.
References llvm::DIEValue::DIEValue(), and llvm::DIEValue::isLabel.
Member Function Documentation
classof()
bool llvm::DIELabel::classof (const DIEValue * L) inline static
Definition at line 345 of file DIE.h.
References llvm::DIEValue::DIEValue(), llvm::DIEValue::getType(), and llvm::DIEValue::isLabel.
EmitValue()
void DIELabel::EmitValue (AsmPrinter * AP, dwarf::Form Form) const override virtual
EmitValue - Emit label value.
Implements llvm::DIEValue.
Definition at line 301 of file DIE.cpp.
References llvm::dwarf::DW_FORM_ref_addr, llvm::dwarf::DW_FORM_sec_offset, llvm::dwarf::DW_FORM_strp, llvm::AsmPrinter::EmitLabelReference(), and SizeOf().
getValue()
const MCSymbol * llvm::DIELabel::getValue () const inline
getValue - Get MCSymbol.
Definition at line 338 of file DIE.h.
print()
void DIELabel::print (raw_ostream & O) const override virtual
Implements llvm::DIEValue.
Definition at line 318 of file DIE.cpp.
SizeOf()
unsigned DIELabel::SizeOf (AsmPrinter * AP, dwarf::Form Form) const override virtual
SizeOf - Determine size of label value in bytes.
Implements llvm::DIEValue.
Definition at line 310 of file DIE.cpp.
References llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_sec_offset, llvm::dwarf::DW_FORM_strp, llvm::AsmPrinter::getDataLayout(), and llvm::DataLayout::getPointerSize().
Referenced by EmitValue().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp