LLVM: llvm::LoopPass Class Reference
LLVM API Documentation
llvm::LoopPass Class Reference abstract
#include <LoopPass.h>
Public Member Functions
LoopPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
virtual bool runOnLoop (Loop *L, LPPassManager &LPM)=0
virtual bool doInitialization (Loop *L, LPPassManager &LPM)
virtual bool doFinalization ()
void preparePassManager (PMStack &PMS) override
Check if available pass managers are suitable for this pass or not.
void assignPassManager (PMStack &PMS, PassManagerType PMT) override
Assign pass manager to manage this pass.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
virtual void cloneBasicBlockAnalysis (BasicBlock *F, BasicBlock *T, Loop *L)
virtual void deleteAnalysisValue (Value *V, Loop *L)
deleteAnalysisValue - Delete analysis info associated with value V.
virtual void deleteAnalysisLoop (Loop *L)
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Protected Member Functions
bool skipOptnoneFunction (const Loop *L) const
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 29 of file LoopPass.h.
Constructor & Destructor Documentation
LoopPass()
llvm::LoopPass::LoopPass (char & pid) inline explicit
Definition at line 31 of file LoopPass.h.
References llvm::PT_Loop.
Referenced by llvm::IVUsers::IVUsers().
Member Function Documentation
assignPassManager()
void LoopPass::assignPassManager (PMStack & PMS, PassManagerType PMT) override virtual
Assign pass manager to manage this pass.
Reimplemented from llvm::Pass.
Definition at line 353 of file LoopPass.cpp.
References llvm::PMDataManager::add(), llvm::PMTopLevelManager::addIndirectPassManager(), llvm::PMStack::empty(), llvm::LPPassManager::getAsPass(), llvm::PMDataManager::getPassManagerType(), llvm::PMDataManager::getTopLevelManager(), P, llvm::PMT_LoopPassManager, llvm::PMStack::pop(), llvm::PMDataManager::populateInheritedAnalysis(), llvm::PMStack::push(), llvm::PMTopLevelManager::schedulePass(), and llvm::PMStack::top().
cloneBasicBlockAnalysis()
virtual void llvm::LoopPass::cloneBasicBlockAnalysis (BasicBlock * F, BasicBlock * T, Loop * L) inline virtual
SimpleAnalysis - Provides simple interface to update analysis info maintained by various passes. Note, if required this interface can be extracted into a separate abstract class but it would require additional use of multiple inheritance in Pass class hierarchy, something we are trying to avoid. Each loop pass can override these simple analysis hooks to update desired analysis information. cloneBasicBlockAnalysis - Clone analysis info associated with basic block.
Definition at line 80 of file LoopPass.h.
References F, and T.
Referenced by llvm::LPPassManager::cloneBasicBlockSimpleAnalysis().
createPrinterPass()
Pass * LoopPass::createPrinterPass (raw_ostream & O, const std::string & Banner) const override virtual
getPrinterPass - Get a pass to print the function corresponding to a Loop.
Implements llvm::Pass.
Definition at line 326 of file LoopPass.cpp.
deleteAnalysisLoop()
virtual void llvm::LoopPass::deleteAnalysisLoop (Loop * L) inline virtual
Delete analysis info associated with Loop L. Called to notify a Pass that a loop has been deleted and any associated analysis values can be deleted.
Definition at line 88 of file LoopPass.h.
Referenced by llvm::LPPassManager::deleteSimpleAnalysisLoop().
deleteAnalysisValue()
virtual void llvm::LoopPass::deleteAnalysisValue (Value * V, Loop * L) inline virtual
deleteAnalysisValue - Delete analysis info associated with value V.
Definition at line 83 of file LoopPass.h.
Referenced by llvm::LPPassManager::deleteSimpleAnalysisValue().
doFinalization() [1/2]
virtual bool llvm::LoopPass::doFinalization () inline virtual
Definition at line 52 of file LoopPass.h.
doFinalization() [2/2]
virtual bool llvm::Pass::doFinalization (Module &) inline virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::Pass.
Definition at line 116 of file Pass.h.
doInitialization() [1/2]
virtual bool llvm::LoopPass::doInitialization (Loop * L, LPPassManager & LPM) inline virtual
Definition at line 46 of file LoopPass.h.
doInitialization() [2/2]
virtual bool llvm::Pass::doInitialization (Module &) inline virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 111 of file Pass.h.
getPotentialPassManagerType()
PassManagerType llvm::LoopPass::getPotentialPassManagerType () const inline override virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented from llvm::Pass.
Definition at line 66 of file LoopPass.h.
References llvm::PMT_LoopPassManager.
preparePassManager()
void LoopPass::preparePassManager (PMStack &) override virtual
Check if available pass managers are suitable for this pass or not.
Reimplemented from llvm::Pass.
Definition at line 337 of file LoopPass.cpp.
References llvm::PMStack::empty(), llvm::PMDataManager::getPassManagerType(), llvm::PMT_LoopPassManager, llvm::PMStack::pop(), llvm::PMDataManager::preserveHigherLevelAnalysis(), and llvm::PMStack::top().
runOnLoop()
virtual bool llvm::LoopPass::runOnLoop (Loop * L, LPPassManager & LPM) pure virtual
References llvm::Pass::doFinalization(), and llvm::Pass::doInitialization().
skipOptnoneFunction()
bool LoopPass::skipOptnoneFunction (const Loop * L) const protected
skipOptnoneFunction - Containing function has Attribute::OptimizeNone and most transformation passes should skip it.
Definition at line 390 of file LoopPass.cpp.
References llvm::dbgs(), DEBUG, F, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getParent(), llvm::Pass::getPassName(), and llvm::Attribute::OptimizeNone.
The documentation for this class was generated from the following files:
LoopPass.h
LoopPass.cpp