LLVM: llvm::MCAlignFragment Class Reference
LLVM API Documentation
llvm::MCAlignFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCAlignFragment (unsigned _Alignment, int64_t _Value, unsigned _ValueSize, unsigned _MaxBytesToEmit, MCSectionData *SD=nullptr)
Accessors
unsigned getAlignment () const
int64_t getValue () const
unsigned getValueSize () const
unsigned getMaxBytesToEmit () const
bool hasEmitNops () const
void setEmitNops (bool Value)
Public Member Functions inherited from llvm::MCFragment
MCFragment ()
virtual ~MCFragment ()
FragmentType getKind () const
MCSectionData * getParent () const
void setParent (MCSectionData *Value)
MCSymbolData * getAtom () const
void setAtom (MCSymbolData *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
virtual bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
virtual bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
virtual void setAlignToBundleEnd (bool V)
virtual uint8_t getBundlePadding () const
Get the padding size that must be inserted before this fragment. Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
virtual void setBundlePadding (uint8_t N)
Set the padding size for this fragment. By default it's a no-op, and only some fragments have a meaningful implementation.
void dump ()
Public Member Functions inherited from llvm::ilist_node< MCFragment >
MCFragment * getPrevNode ()
Get the previous node, or 0 for the list head.
MCFragment * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Relaxable , FT_Org , FT_Dwarf , FT_DwarfFrame ,
FT_LEB
}
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType _Kind, MCSectionData *_Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node< MCFragment >
ilist_node ()
Detailed Description
Definition at line 344 of file MCAssembler.h.
Constructor & Destructor Documentation
MCAlignFragment()
llvm::MCAlignFragment::MCAlignFragment (unsigned _Alignment, int64_t _Value, unsigned _ValueSize, unsigned _MaxBytesToEmit, MCSectionData * SD = nullptr) inline
Definition at line 366 of file MCAssembler.h.
References llvm::MCFragment::FT_Align.
Member Function Documentation
classof()
bool llvm::MCAlignFragment::classof (const MCFragment * F) inline static
Definition at line 388 of file MCAssembler.h.
References F, and llvm::MCFragment::FT_Align.
getAlignment()
unsigned llvm::MCAlignFragment::getAlignment () const inline
Definition at line 375 of file MCAssembler.h.
Referenced by llvm::MCAssembler::computeFragmentSize(), and llvm::MCFragment::dump().
getMaxBytesToEmit()
unsigned llvm::MCAlignFragment::getMaxBytesToEmit () const inline
Definition at line 381 of file MCAssembler.h.
Referenced by llvm::MCAssembler::computeFragmentSize(), and llvm::MCFragment::dump().
getValue()
int64_t llvm::MCAlignFragment::getValue () const inline
Definition at line 377 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), and writeFragment().
getValueSize()
unsigned llvm::MCAlignFragment::getValueSize () const inline
Definition at line 379 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), and writeFragment().
hasEmitNops()
bool llvm::MCAlignFragment::hasEmitNops () const inline
Definition at line 383 of file MCAssembler.h.
Referenced by llvm::MCAssembler::computeFragmentSize(), llvm::MCFragment::dump(), and writeFragment().
setEmitNops()
void llvm::MCAlignFragment::setEmitNops (bool Value) inline
Definition at line 384 of file MCAssembler.h.
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp