LLVM: llvm::SmallPtrSetImplBase Class Reference
LLVM API Documentation
llvm::SmallPtrSetImplBase Class Reference
#include <SmallPtrSet.h>
Public Types
typedef unsigned size_type
Public Member Functions
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
size_type size () const
void clear ()
Protected Member Functions
SmallPtrSetImplBase (const void **SmallStorage, const SmallPtrSetImplBase &that)
SmallPtrSetImplBase (const void **SmallStorage, unsigned SmallSize, SmallPtrSetImplBase &&that)
SmallPtrSetImplBase (const void **SmallStorage, unsigned SmallSize)
~SmallPtrSetImplBase ()
std::pair< const void *const *, bool > insert_imp (const void *Ptr)
bool erase_imp (const void *Ptr)
bool count_imp (const void *Ptr) const
void swap (SmallPtrSetImplBase &RHS)
void CopyFrom (const SmallPtrSetImplBase &RHS)
void MoveFrom (unsigned SmallSize, SmallPtrSetImplBase &&RHS)
Static Protected Member Functions
static void * getTombstoneMarker ()
static void * getEmptyMarker ()
Protected Attributes
const void ** SmallArray
SmallArray - Points to a fixed size set of buckets, used in 'small mode'.
const void ** CurArray
unsigned CurArraySize
CurArraySize - The allocated size of CurArray, always a power of two.
unsigned NumElements
unsigned NumTombstones
Friends
class SmallPtrSetIteratorImpl
Detailed Description
SmallPtrSetImplBase - This is the common code shared among all the SmallPtrSet<>'s, which is almost everything. SmallPtrSet has two modes, one for small and one for large sets.
Small sets use an array of pointers allocated in the SmallPtrSet object, which is treated as a simple array of pointers. When a pointer is added to the set, the array is scanned to see if the element already exists, if not the element is 'pushed back' onto the array. If we run out of space in the array, we grow into the 'large set' case. SmallSet should be used when the sets are often small. In this case, no memory allocation is used, and only light-weight and cache-efficient scanning is used.
Large sets use a classic exponentially-probed hash table. Empty buckets are represented with an illegal pointer value (-1) to allow null pointers to be inserted. Tombstones are represented with another illegal pointer value (-2), to allow deletion. The hash table is resized when the table is 3/4 or more. When this happens, the table is doubled in size.
Definition at line 49 of file SmallPtrSet.h.
Member Typedef Documentation
size_type
typedef unsigned llvm::SmallPtrSetImplBase::size_type
Definition at line 77 of file SmallPtrSet.h.
Constructor & Destructor Documentation
SmallPtrSetImplBase() [1/3]
SmallPtrSetImplBase::SmallPtrSetImplBase (const void ** SmallStorage, const SmallPtrSetImplBase & that) protected
Definition at line 168 of file SmallPtrSet.cpp.
References CurArray, CurArraySize, NumElements, NumTombstones, SmallArray, and SmallPtrSetImplBase().
Referenced by CopyFrom(), MoveFrom(), llvm::SmallPtrSetImpl< PtrType >::SmallPtrSetImpl(), llvm::SmallPtrSetImpl< PtrType >::SmallPtrSetImpl(), llvm::SmallPtrSetImpl< PtrType >::SmallPtrSetImpl(), SmallPtrSetImplBase(), SmallPtrSetImplBase(), and swap().
SmallPtrSetImplBase() [2/3]
SmallPtrSetImplBase::SmallPtrSetImplBase (const void ** SmallStorage, unsigned SmallSize, SmallPtrSetImplBase && that) protected
Definition at line 191 of file SmallPtrSet.cpp.
References CurArray, CurArraySize, NumElements, NumTombstones, SmallArray, and SmallPtrSetImplBase().
SmallPtrSetImplBase() [3/3]
llvm::SmallPtrSetImplBase::SmallPtrSetImplBase (const void ** SmallStorage, unsigned SmallSize) inline explicit protected
Definition at line 68 of file SmallPtrSet.h.
References clear(), CurArray, CurArraySize, and SmallArray.
~SmallPtrSetImplBase()
SmallPtrSetImplBase::~SmallPtrSetImplBase () protected
Definition at line 334 of file SmallPtrSet.cpp.
References CurArray.
Member Function Documentation
clear()
void llvm::SmallPtrSetImplBase::clear () inline
Definition at line 81 of file SmallPtrSet.h.
References CurArray, CurArraySize, NumElements, and NumTombstones.
Referenced by AllGlobalLoadUsesSimpleEnoughForHeapSRA(), ComputePostOrders(), determineMissingVNIs(), llvm::LexicalScopes::getMachineBasicBlocks(), and SmallPtrSetImplBase().
CopyFrom()
void SmallPtrSetImplBase::CopyFrom (const SmallPtrSetImplBase & RHS) protected
CopyFrom - implement operator= from a smallptrset that has the same pointer type, but may have a different small size.
Definition at line 220 of file SmallPtrSet.cpp.
References CurArray, CurArraySize, NumElements, NumTombstones, SmallArray, and SmallPtrSetImplBase().
Referenced by llvm::SmallPtrSet< const Value *, 8 >::operator=().
count_imp()
bool llvm::SmallPtrSetImplBase::count_imp (const void * Ptr) const inline protected
Definition at line 112 of file SmallPtrSet.h.
References NumElements, and SmallArray.
Referenced by llvm::SmallPtrSetImpl< PtrType >::count().
empty()
bool LLVM_ATTRIBUTE_UNUSED_RESULT llvm::SmallPtrSetImplBase::empty () const inline
Definition at line 78 of file SmallPtrSet.h.
References LLVM_ATTRIBUTE_UNUSED_RESULT, and size().
Referenced by llvm::findPHICopyInsertPoint(), llvm::SDNode::hasPredecessorHelper(), and llvm::SelectionDAG::MorphNodeTo().
erase_imp()
bool SmallPtrSetImplBase::erase_imp (const void * Ptr) protected
erase_imp - If the set contains the specified pointer, remove it and return true, otherwise return false. This is hidden from the client so that the derived class can check that the right type of pointer is passed in.
Definition at line 76 of file SmallPtrSet.cpp.
References getEmptyMarker(), getTombstoneMarker(), NumElements, NumTombstones, and SmallArray.
Referenced by llvm::SmallPtrSetImpl< PtrType >::erase().
getEmptyMarker()
void * llvm::SmallPtrSetImplBase::getEmptyMarker () inline static protected
Definition at line 95 of file SmallPtrSet.h.
Referenced by llvm::SmallPtrSetIteratorImpl::AdvanceIfNotValid(), and erase_imp().
getTombstoneMarker()
void * llvm::SmallPtrSetImplBase::getTombstoneMarker () inline static protected
Definition at line 94 of file SmallPtrSet.h.
Referenced by llvm::SmallPtrSetIteratorImpl::AdvanceIfNotValid(), erase_imp(), and insert_imp().
insert_imp()
std::pair< const void *const *, bool > SmallPtrSetImplBase::insert_imp (const void * Ptr) protected
insert_imp - This returns true if the pointer was new to the set, false if it was already in the set. This is hidden from the client so that the derived class can check that the right type of pointer is passed in.
Definition at line 38 of file SmallPtrSet.cpp.
References CurArraySize, getTombstoneMarker(), NumElements, NumTombstones, and SmallArray.
Referenced by llvm::SmallPtrSetImpl< PtrType >::insert().
MoveFrom()
void SmallPtrSetImplBase::MoveFrom (unsigned SmallSize, SmallPtrSetImplBase && RHS) protected
Definition at line 256 of file SmallPtrSet.cpp.
References CurArray, CurArraySize, NumElements, NumTombstones, SmallArray, and SmallPtrSetImplBase().
Referenced by llvm::SmallPtrSet< const Value *, 8 >::operator=().
size()
size_type llvm::SmallPtrSetImplBase::size () const inline
Definition at line 79 of file SmallPtrSet.h.
References NumElements.
Referenced by DeadPHICycle(), empty(), llvm::CodeExtractor::extractCodeRegion(), llvm::findPHICopyInsertPoint(), FindPredecessorRetainWithSafePath(), HasSafePathToPredecessorCall(), PHIsEqualValue(), and llvm::removeUnreachableBlocks().
swap()
void SmallPtrSetImplBase::swap (SmallPtrSetImplBase & RHS) protected
swap - Swaps the elements of two sets. Note: This method assumes that both sets have the same small size.
Definition at line 284 of file SmallPtrSet.cpp.
References CurArray, CurArraySize, NumElements, NumTombstones, SmallArray, SmallPtrSetImplBase(), and std::swap().
Referenced by llvm::SmallPtrSet< const Value *, 8 >::swap().
Friends And Related Symbol Documentation
SmallPtrSetIteratorImpl
friend class SmallPtrSetIteratorImpl friend
Definition at line 50 of file SmallPtrSet.h.
References SmallPtrSetIteratorImpl.
Referenced by SmallPtrSetIteratorImpl.
Member Data Documentation
CurArray
const void** llvm::SmallPtrSetImplBase::CurArray protected
CurArray - This is the current set of buckets. If equal to SmallArray, then the set is in 'small mode'.
Definition at line 56 of file SmallPtrSet.h.
Referenced by llvm::SmallPtrSetImpl< PtrType >::begin(), clear(), CopyFrom(), llvm::SmallPtrSetImpl< PtrType >::end(), llvm::SmallPtrSetImpl< PtrType >::insert(), MoveFrom(), SmallPtrSetImplBase(), SmallPtrSetImplBase(), SmallPtrSetImplBase(), swap(), and ~SmallPtrSetImplBase().
CurArraySize
unsigned llvm::SmallPtrSetImplBase::CurArraySize protected
CurArraySize - The allocated size of CurArray, always a power of two.
Definition at line 58 of file SmallPtrSet.h.
Referenced by llvm::SmallPtrSetImpl< PtrType >::begin(), clear(), CopyFrom(), llvm::SmallPtrSetImpl< PtrType >::end(), llvm::SmallPtrSetImpl< PtrType >::insert(), insert_imp(), MoveFrom(), SmallPtrSetImplBase(), SmallPtrSetImplBase(), SmallPtrSetImplBase(), and swap().
NumElements
unsigned llvm::SmallPtrSetImplBase::NumElements protected
Definition at line 61 of file SmallPtrSet.h.
Referenced by clear(), CopyFrom(), count_imp(), erase_imp(), insert_imp(), MoveFrom(), size(), SmallPtrSetImplBase(), SmallPtrSetImplBase(), and swap().
NumTombstones
unsigned llvm::SmallPtrSetImplBase::NumTombstones protected
Definition at line 62 of file SmallPtrSet.h.
Referenced by clear(), CopyFrom(), erase_imp(), insert_imp(), MoveFrom(), SmallPtrSetImplBase(), SmallPtrSetImplBase(), and swap().
SmallArray
const void** llvm::SmallPtrSetImplBase::SmallArray protected
SmallArray - Points to a fixed size set of buckets, used in 'small mode'.
Definition at line 53 of file SmallPtrSet.h.
Referenced by CopyFrom(), count_imp(), erase_imp(), insert_imp(), MoveFrom(), SmallPtrSetImplBase(), SmallPtrSetImplBase(), SmallPtrSetImplBase(), and swap().
The documentation for this class was generated from the following files:
SmallPtrSet.h
SmallPtrSet.cpp