LLVM: llvm::FunctionPass Class Reference
LLVM API Documentation
llvm::FunctionPass Class Reference abstract
#include <Pass.h>
Public Member Functions
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Protected Member Functions
bool skipOptnoneFunction (const Function &F) const
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
FunctionPass class - This class is used to implement most global optimizations. Optimizations should subclass this class if they meet the following constraints:
Optimizations are organized globally, i.e., a function at a time
Optimizing a function does not cause the addition or removal of any functions in the module
Definition at line 294 of file Pass.h.
Constructor & Destructor Documentation
FunctionPass()
llvm::FunctionPass::FunctionPass (char & pid) inline explicit
Definition at line 296 of file Pass.h.
References llvm::PT_Function.
Referenced by llvm::BlockFrequencyInfo::BlockFrequencyInfo(), llvm::BranchProbabilityInfo::BranchProbabilityInfo(), llvm::DependenceAnalysis::DependenceAnalysis(), llvm::DominanceFrontier::DominanceFrontier(), llvm::DominatorTreeWrapperPass::DominatorTreeWrapperPass(), llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::DOTGraphTraitsPrinter(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::DOTGraphTraitsViewer(), llvm::FunctionTargetTransformInfo::FunctionTargetTransformInfo(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::InstCombiner::InstCombiner(), llvm::IntervalPartition::IntervalPartition(), llvm::IntervalPartition::IntervalPartition(), llvm::LazyValueInfo::LazyValueInfo(), llvm::LibCallAliasAnalysis::LibCallAliasAnalysis(), llvm::LibCallAliasAnalysis::LibCallAliasAnalysis(), llvm::LoopInfo::LoopInfo(), llvm::LPPassManager::LPPassManager(), llvm::MachineFunctionAnalysis::MachineFunctionAnalysis(), llvm::MachineFunctionPass::MachineFunctionPass(), llvm::MemoryDependenceAnalysis::MemoryDependenceAnalysis(), llvm::NVPTXAllocaHoisting::NVPTXAllocaHoisting(), llvm::NVPTXLowerAggrCopies::NVPTXLowerAggrCopies(), NVPTXLowerStructArgs::NVPTXLowerStructArgs(), llvm::PostDominatorTree::PostDominatorTree(), llvm::RegionInfoPass::RegionInfoPass(), llvm::RGPassManager::RGPassManager(), llvm::ScalarEvolution::ScalarEvolution(), llvm::StackProtector::StackProtector(), llvm::StackProtector::StackProtector(), and llvm::UnifyFunctionExitNodes::UnifyFunctionExitNodes().
Member Function Documentation
assignPassManager()
void FunctionPass::assignPassManager (PMStack & PMS, PassManagerType PreferredType) override virtual
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
Reimplemented from llvm::Pass.
Definition at line 1854 of file LegacyPassManager.cpp.
References llvm::PMDataManager::add(), llvm::PMTopLevelManager::addIndirectPassManager(), llvm::ModulePass::assignPassManager(), llvm::PMStack::empty(), llvm::PMDataManager::getPassManagerType(), llvm::PMDataManager::getTopLevelManager(), llvm::PMT_FunctionPassManager, llvm::PMStack::pop(), llvm::PMDataManager::populateInheritedAnalysis(), llvm::PMStack::push(), and llvm::PMStack::top().
createPrinterPass()
Pass * FunctionPass::createPrinterPass (raw_ostream & O, const std::string & Banner) const override virtual
createPrinterPass - Get a function printer pass.
Implements llvm::Pass.
Definition at line 134 of file Pass.cpp.
References llvm::createPrintFunctionPass().
getPotentialPassManagerType()
PassManagerType FunctionPass::getPotentialPassManagerType () const override virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented from llvm::Pass.
Definition at line 139 of file Pass.cpp.
References llvm::PMT_FunctionPassManager.
runOnFunction()
virtual bool llvm::FunctionPass::runOnFunction (Function & F) pure virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implemented in llvm::BlockFrequencyInfo, llvm::BranchProbabilityInfo, llvm::DependenceAnalysis, llvm::DominanceFrontier, llvm::DominatorTreeWrapperPass, llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >, llvm::FunctionTargetTransformInfo, llvm::InstCombiner, llvm::IntervalPartition, llvm::LazyValueInfo, llvm::LibCallAliasAnalysis, llvm::LoopInfo, llvm::LPPassManager, llvm::MemoryDependenceAnalysis, llvm::NVPTXAllocaHoisting, llvm::NVPTXLowerAggrCopies, llvm::PostDominatorTree, llvm::RegionInfoPass, llvm::RGPassManager, llvm::ScalarEvolution, llvm::StackProtector, and llvm::UnifyFunctionExitNodes.
References F, and T.
Referenced by INITIALIZE_PASS(), INITIALIZE_PASS(), and llvm::FPPassManager::runOnFunction().
skipOptnoneFunction()
bool FunctionPass::skipOptnoneFunction (const Function & F) const protected
skipOptnoneFunction - This function has Attribute::OptimizeNone and most transformation passes should skip it.
Definition at line 143 of file Pass.cpp.
References llvm::dbgs(), DEBUG, F, llvm::Pass::getPassName(), and llvm::Attribute::OptimizeNone.
Referenced by llvm::InstCombiner::runOnFunction().
The documentation for this class was generated from the following files:
Pass.h
LegacyPassManager.cpp
Pass.cpp