LLVM: llvm::FunctionTargetTransformInfo Class Reference
LLVM API Documentation
llvm::FunctionTargetTransformInfo Class Reference final
#include <FunctionTargetTransformInfo.h>
Public Member Functions
FunctionTargetTransformInfo ()
void getAnalysisUsage (AnalysisUsage &AU) const override
void releaseMemory () override
bool runOnFunction (Function &F) override
void getUnrollingPreferences (Loop *L, TargetTransformInfo::UnrollingPreferences &UP) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 23 of file FunctionTargetTransformInfo.h.
Constructor & Destructor Documentation
FunctionTargetTransformInfo()
FunctionTargetTransformInfo::FunctionTargetTransformInfo ()
Definition at line 34 of file FunctionTargetTransformInfo.cpp.
References llvm::FunctionPass::FunctionPass(), llvm::PassRegistry::getPassRegistry(), ID, and llvm::initializeFunctionTargetTransformInfoPass().
Member Function Documentation
getAnalysisUsage()
void FunctionTargetTransformInfo::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 39 of file FunctionTargetTransformInfo.cpp.
References llvm::AnalysisUsage::addRequired(), and llvm::AnalysisUsage::setPreservesAll().
getUnrollingPreferences()
void llvm::FunctionTargetTransformInfo::getUnrollingPreferences (Loop * L, TargetTransformInfo::UnrollingPreferences & UP) const inline
Definition at line 43 of file FunctionTargetTransformInfo.h.
releaseMemory()
void FunctionTargetTransformInfo::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 44 of file FunctionTargetTransformInfo.cpp.
runOnFunction()
bool FunctionTargetTransformInfo::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 46 of file FunctionTargetTransformInfo.cpp.
References F, and llvm::Pass::getAnalysis().
Member Data Documentation
ID
char FunctionTargetTransformInfo::ID = 0 static
Definition at line 33 of file FunctionTargetTransformInfo.h.
Referenced by FunctionTargetTransformInfo().
The documentation for this class was generated from the following files:
FunctionTargetTransformInfo.h
FunctionTargetTransformInfo.cpp