LLVM: llvm::object::ObjectFile Class Reference
LLVM API Documentation
llvm::object::ObjectFile Class Reference abstract
#include <ObjectFile.h>
Public Types
typedef iterator_range< symbol_iterator > symbol_iterator_range
typedef iterator_range< section_iterator > section_iterator_range
Public Types inherited from llvm::object::SymbolicFile
typedef iterator_range< basic_symbol_iterator > basic_symbol_iterator_range
Public Member Functions
symbol_iterator_range symbols () const
virtual section_iterator section_begin () const =0
virtual section_iterator section_end () const =0
section_iterator_range sections () const
virtual uint8_t getBytesInAddress () const =0
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const =0
virtual unsigned getArch () const =0
virtual std::error_code getPlatformFlags (unsigned &Result) const
Returns platform-specific object flags, if any.
virtual bool isRelocatableObject () const =0
True if this is a relocatable object (.o/.obj).
Public Member Functions inherited from llvm::object::SymbolicFile
virtual ~SymbolicFile ()
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
virtual void moveSymbolNext (DataRefImpl &Symb) const =0
virtual uint32_t getSymbolFlags (DataRefImpl Symb) const =0
virtual basic_symbol_iterator symbol_begin_impl () const =0
virtual basic_symbol_iterator symbol_end_impl () const =0
basic_symbol_iterator symbol_begin () const
basic_symbol_iterator symbol_end () const
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isIR () const
bool isLittleEndian () const
Static Public Member Functions
static ErrorOr< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
Create ObjectFile from path.
static ErrorOr< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, sys::fs::file_magic Type)
static ErrorOr< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static ErrorOr< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static ErrorOr< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object)
static ErrorOr< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static ErrorOr< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, sys::fs::file_magic Type, LLVMContext *Context)
static ErrorOr< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static ErrorOr< OwningBinary< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Protected Member Functions
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
virtual std::error_code getSymbolName (DataRefImpl Symb, StringRef &Res) const =0
std::error_code printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual std::error_code getSymbolAddress (DataRefImpl Symb, uint64_t &Res) const =0
virtual std::error_code getSymbolAlignment (DataRefImpl Symb, uint32_t &Res) const
virtual std::error_code getSymbolSize (DataRefImpl Symb, uint64_t &Res) const =0
virtual std::error_code getSymbolType (DataRefImpl Symb, SymbolRef::Type &Res) const =0
virtual std::error_code getSymbolSection (DataRefImpl Symb, section_iterator &Res) const =0
virtual std::error_code getSymbolOther (DataRefImpl Symb, uint8_t &Res) const
virtual void moveSectionNext (DataRefImpl &Sec) const =0
virtual std::error_code getSectionName (DataRefImpl Sec, StringRef &Res) const =0
virtual uint64_t getSectionAddress (DataRefImpl Sec) const =0
virtual uint64_t getSectionSize (DataRefImpl Sec) const =0
virtual std::error_code getSectionContents (DataRefImpl Sec, StringRef &Res) const =0
virtual uint64_t getSectionAlignment (DataRefImpl Sec) const =0
virtual bool isSectionText (DataRefImpl Sec) const =0
virtual bool isSectionData (DataRefImpl Sec) const =0
virtual bool isSectionBSS (DataRefImpl Sec) const =0
virtual bool isSectionVirtual (DataRefImpl Sec) const =0
virtual bool sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb) const =0
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const =0
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const =0
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
virtual void moveRelocationNext (DataRefImpl &Rel) const =0
virtual std::error_code getRelocationAddress (DataRefImpl Rel, uint64_t &Res) const =0
virtual std::error_code getRelocationOffset (DataRefImpl Rel, uint64_t &Res) const =0
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const =0
virtual std::error_code getRelocationType (DataRefImpl Rel, uint64_t &Res) const =0
virtual std::error_code getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
virtual std::error_code getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
virtual std::error_code getRelocationHidden (DataRefImpl Rel, bool &Result) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Friends
class SymbolRef
class SectionRef
class RelocationRef
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_IR , ID_StartObjects ,
ID_COFF , ID_ELF32L , ID_ELF32B , ID_ELF64L ,
ID_ELF64B , ID_MachO32L , ID_MachO32B , ID_MachO64L ,
ID_MachO64B , ID_EndObjects
}
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
ObjectFile - This class is the base class for all object file types. Concrete instances of this object are created by createObjectFile, which figures out which type to create.
Definition at line 181 of file ObjectFile.h.
Member Typedef Documentation
section_iterator_range
typedef iterator_range<section_iterator> llvm::object::ObjectFile::section_iterator_range
Definition at line 273 of file ObjectFile.h.
symbol_iterator_range
typedef iterator_range<symbol_iterator> llvm::object::ObjectFile::symbol_iterator_range
Definition at line 265 of file ObjectFile.h.
Constructor & Destructor Documentation
ObjectFile()
ObjectFile::ObjectFile (unsigned int Type, MemoryBufferRef Source) protected
Definition at line 28 of file ObjectFile.cpp.
References llvm::object::SymbolicFile::SymbolicFile().
Member Function Documentation
base()
const uint8_t * llvm::object::ObjectFile::base () const inline protected
Definition at line 189 of file ObjectFile.h.
References llvm::object::Binary::Data.
Referenced by llvm::object::COFFObjectFile::COFFObjectFile(), llvm::object::COFFObjectFile::getDOSHeader(), llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::COFFObjectFile::getSectionContents(), llvm::object::ELFObjectFile< ELFT >::getSectionContents(), llvm::object::COFFObjectFile::getSymbolAuxData(), llvm::object::COFFObjectFile::section_rel_begin(), and llvm::object::COFFObjectFile::section_rel_end().
classof()
bool llvm::object::ObjectFile::classof (const Binary * v) inline static
Definition at line 309 of file ObjectFile.h.
References llvm::object::Binary::isObject().
createCOFFObjectFile()
ErrorOr< std::unique_ptr< COFFObjectFile > > ObjectFile::createCOFFObjectFile (MemoryBufferRef Object) static
Definition at line 1451 of file COFFObjectFile.cpp.
Referenced by createObjectFile().
createELFObjectFile()
ErrorOr< std::unique_ptr< ObjectFile > > llvm::ObjectFile::createELFObjectFile (MemoryBufferRef Object) static
Definition at line 24 of file ELFObjectFile.cpp.
References llvm::countTrailingZeros(), llvm::ELF::ELFCLASS32, llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, llvm::ELF::ELFDATA2MSB, llvm::MemoryBufferRef::getBuffer(), llvm::MemoryBufferRef::getBufferStart(), llvm::object::getElfArchType(), llvm_unreachable, and llvm::object::parse_failed.
Referenced by createObjectFile().
createMachOObjectFile()
ErrorOr< std::unique_ptr< MachOObjectFile > > ObjectFile::createMachOObjectFile (MemoryBufferRef Object) static
Definition at line 2548 of file MachOObjectFile.cpp.
References llvm::MemoryBufferRef::getBuffer(), Magic, llvm::object::parse_failed, and llvm::StringRef::slice().
Referenced by createObjectFile(), and llvm::object::MachOUniversalBinary::ObjectForArch::getAsObjectFile().
createObjectFile() [1/3]
ErrorOr< std::unique_ptr< ObjectFile > > llvm::object::ObjectFile::createObjectFile (MemoryBufferRef Object) inline static
Definition at line 304 of file ObjectFile.h.
References createObjectFile(), and llvm::sys::fs::file_magic::unknown.
createObjectFile() [2/3]
ErrorOr< std::unique_ptr< ObjectFile > > ObjectFile::createObjectFile (MemoryBufferRef Object, sys::fs::file_magic Type) static
Definition at line 51 of file ObjectFile.cpp.
References llvm::sys::fs::file_magic::archive, llvm::sys::fs::file_magic::bitcode, llvm::sys::fs::file_magic::coff_import_library, llvm::sys::fs::file_magic::coff_object, createCOFFObjectFile(), createELFObjectFile(), createMachOObjectFile(), llvm::object::Binary::Data, llvm::sys::fs::file_magic::elf, llvm::sys::fs::file_magic::elf_core, llvm::sys::fs::file_magic::elf_executable, llvm::sys::fs::file_magic::elf_relocatable, llvm::sys::fs::file_magic::elf_shared_object, llvm::MemoryBufferRef::getBuffer(), llvm::sys::fs::identify_magic(), llvm::object::invalid_file_type, llvm_unreachable, llvm::sys::fs::file_magic::macho_bundle, llvm::sys::fs::file_magic::macho_core, llvm::sys::fs::file_magic::macho_dsym_companion, llvm::sys::fs::file_magic::macho_dynamic_linker, llvm::sys::fs::file_magic::macho_dynamically_linked_shared_lib, llvm::sys::fs::file_magic::macho_dynamically_linked_shared_lib_stub, llvm::sys::fs::file_magic::macho_executable, llvm::sys::fs::file_magic::macho_fixed_virtual_memory_shared_lib, llvm::sys::fs::file_magic::macho_object, llvm::sys::fs::file_magic::macho_preload_executable, llvm::sys::fs::file_magic::macho_universal_binary, llvm::sys::fs::file_magic::pecoff_executable, llvm::sys::fs::file_magic::unknown, and llvm::sys::fs::file_magic::windows_resource.
createObjectFile() [3/3]
ErrorOr< OwningBinary< ObjectFile > > ObjectFile::createObjectFile (StringRef ObjectPath) static
Create ObjectFile from path.
Returns
Pointer to ObjectFile subclass to handle this type of object.
Parameters
ObjectPath The path to the object file. ObjectPath.isObject must return true.
Definition at line 89 of file ObjectFile.cpp.
References createObjectFile(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), and llvm::MemoryBuffer::getFile().
Referenced by createObjectFile(), createObjectFile(), llvm::object::SymbolicFile::createSymbolicFile(), llvm::object::IRObjectFile::findBitcodeInMemBuffer(), llvm::MCJIT::generateCodeForModule(), LLVMCreateObjectFile(), and llvm::coverage::ObjectFileCoverageMappingReader::ObjectFileCoverageMappingReader().
getArch()
virtual unsigned llvm::object::ObjectFile::getArch () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
Referenced by llvm::RuntimeDyld::loadObject(), and llvm::RuntimeDyldImpl::loadObjectImpl().
getBytesInAddress()
virtual uint8_t llvm::object::ObjectFile::getBytesInAddress () const pure virtual
The number of bytes used to represent an address in this object file format.
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
Referenced by llvm::coverage::ObjectFileCoverageMappingReader::readHeader().
getFileFormatName()
virtual StringRef llvm::object::ObjectFile::getFileFormatName () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getPlatformFlags()
virtual std::error_code llvm::object::ObjectFile::getPlatformFlags (unsigned & Result) const inline virtual
Returns platform-specific object flags, if any.
Reimplemented in llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, and llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >.
Definition at line 286 of file ObjectFile.h.
References llvm::object::invalid_file_type.
Referenced by llvm::RuntimeDyldELF::processRelocationRef().
getRelocatedSection()
section_iterator ObjectFile::getRelocatedSection (DataRefImpl Sec) const protected virtual
Reimplemented in llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, and llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >.
Definition at line 46 of file ObjectFile.cpp.
References SectionRef.
getRelocationAddress()
virtual std::error_code llvm::object::ObjectFile::getRelocationAddress (DataRefImpl Rel, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getRelocationHidden()
virtual std::error_code llvm::object::ObjectFile::getRelocationHidden (DataRefImpl Rel, bool & Result) const inline protected virtual
Reimplemented in llvm::object::MachOObjectFile.
Definition at line 258 of file ObjectFile.h.
References llvm::object::success.
getRelocationOffset()
virtual std::error_code llvm::object::ObjectFile::getRelocationOffset (DataRefImpl Rel, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getRelocationSymbol()
virtual symbol_iterator llvm::object::ObjectFile::getRelocationSymbol (DataRefImpl Rel) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getRelocationType()
virtual std::error_code llvm::object::ObjectFile::getRelocationType (DataRefImpl Rel, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getRelocationTypeName()
virtual std::error_code llvm::object::ObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getRelocationValueString()
virtual std::error_code llvm::object::ObjectFile::getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > & Result) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getSectionAddress()
virtual uint64_t llvm::object::ObjectFile::getSectionAddress (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getSectionAlignment()
virtual uint64_t llvm::object::ObjectFile::getSectionAlignment (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getSectionContents()
virtual std::error_code llvm::object::ObjectFile::getSectionContents (DataRefImpl Sec, StringRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getSectionName()
virtual std::error_code llvm::object::ObjectFile::getSectionName (DataRefImpl Sec, StringRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getSectionSize()
virtual uint64_t llvm::object::ObjectFile::getSectionSize (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
getSymbolAddress()
virtual std::error_code llvm::object::ObjectFile::getSymbolAddress (DataRefImpl Symb, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::SymbolRef::getAddress().
getSymbolAlignment()
std::error_code ObjectFile::getSymbolAlignment (DataRefImpl Symb, uint32_t & Res) const protected virtual
Reimplemented in llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
Definition at line 40 of file ObjectFile.cpp.
References llvm::object::success.
Referenced by llvm::object::SymbolRef::getAlignment().
getSymbolName()
virtual std::error_code llvm::object::ObjectFile::getSymbolName (DataRefImpl Symb, StringRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::SymbolRef::getName(), and printSymbolName().
getSymbolOther()
virtual std::error_code llvm::object::ObjectFile::getSymbolOther (DataRefImpl Symb, uint8_t & Res) const inline protected virtual
Reimplemented in llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, and llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >.
Definition at line 216 of file ObjectFile.h.
References llvm::object::invalid_file_type.
Referenced by llvm::object::SymbolRef::getOther().
getSymbolSection()
virtual std::error_code llvm::object::ObjectFile::getSymbolSection (DataRefImpl Symb, section_iterator & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::SymbolRef::getSection().
getSymbolSize()
virtual std::error_code llvm::object::ObjectFile::getSymbolSize (DataRefImpl Symb, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::SymbolRef::getSize().
getSymbolType()
virtual std::error_code llvm::object::ObjectFile::getSymbolType (DataRefImpl Symb, SymbolRef::Type & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::SymbolRef::getType().
isRelocatableObject()
virtual bool llvm::object::ObjectFile::isRelocatableObject () const pure virtual
True if this is a relocatable object (.o/.obj).
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
isSectionBSS()
virtual bool llvm::object::ObjectFile::isSectionBSS (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
isSectionData()
virtual bool llvm::object::ObjectFile::isSectionData (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
isSectionText()
virtual bool llvm::object::ObjectFile::isSectionText (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
isSectionVirtual()
virtual bool llvm::object::ObjectFile::isSectionVirtual (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
moveRelocationNext()
virtual void llvm::object::ObjectFile::moveRelocationNext (DataRefImpl & Rel) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
moveSectionNext()
virtual void llvm::object::ObjectFile::moveSectionNext (DataRefImpl & Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
printSymbolName()
std::error_code ObjectFile::printSymbolName (raw_ostream & OS, DataRefImpl Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 31 of file ObjectFile.cpp.
References getSymbolName(), Name, and llvm::object::success.
section_begin()
virtual section_iterator llvm::object::ObjectFile::section_begin () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
Referenced by llvm::RuntimeDyldImpl::computeSectionStubBufSize(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::getOffset(), llvm::RuntimeDyldImpl::loadObjectImpl(), and sections().
section_end()
virtual section_iterator llvm::object::ObjectFile::section_end () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
Referenced by llvm::RuntimeDyldImpl::computeSectionStubBufSize(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::DWARFContextInMemory::DWARFContextInMemory(), llvm::getOffset(), llvm::RuntimeDyldImpl::loadObjectImpl(), llvm::RuntimeDyldELF::processRelocationRef(), and sections().
section_rel_begin()
virtual relocation_iterator llvm::object::ObjectFile::section_rel_begin (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
section_rel_end()
virtual relocation_iterator llvm::object::ObjectFile::section_rel_end (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
sectionContainsSymbol()
virtual bool llvm::object::ObjectFile::sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, llvm::object::ELFObjectFile< ELFType< support::big, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::big, 2, true > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >, llvm::object::ELFObjectFile< ELFType< support::little, 2, true > >, and llvm::object::MachOObjectFile.
sections()
section_iterator_range llvm::object::ObjectFile::sections () const inline
Definition at line 274 of file ObjectFile.h.
References section_begin(), and section_end().
Referenced by llvm::DWARFContextInMemory::DWARFContextInMemory(), llvm::RuntimeDyldMachOCRTPBase< Impl >::finalizeLoad(), llvm::object::IRObjectFile::findBitcodeInObject(), llvm::object::COFFObjectFile::getRvaPtr(), printRelocationTargetName(), and llvm::coverage::ObjectFileCoverageMappingReader::readHeader().
symbols()
symbol_iterator_range llvm::object::ObjectFile::symbols () const inline
Definition at line 266 of file ObjectFile.h.
References llvm::object::SymbolicFile::symbol_begin(), and llvm::object::SymbolicFile::symbol_end().
Referenced by llvm::object::COFFObjectFile::getSymbolSize(), llvm::object::MachOObjectFile::getSymbolSize(), and printRelocationTargetName().
Friends And Related Symbol Documentation
RelocationRef
friend class RelocationRef friend
Definition at line 243 of file ObjectFile.h.
References RelocationRef.
Referenced by llvm::object::COFFObjectFile::getCOFFRelocation(), RelocationRef, llvm::object::COFFObjectFile::section_rel_begin(), llvm::object::MachOObjectFile::section_rel_begin(), llvm::object::COFFObjectFile::section_rel_end(), and llvm::object::MachOObjectFile::section_rel_end().
SectionRef
friend class SectionRef friend
Definition at line 222 of file ObjectFile.h.
References SectionRef.
Referenced by llvm::object::COFFObjectFile::getCOFFSection(), getRelocatedSection(), llvm::object::MachOObjectFile::getRelocationSection(), llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::ELFObjectFileBase::getSectionFlags(), llvm::object::ELFObjectFileBase::getSectionType(), llvm::object::MachOObjectFile::getSectionType(), llvm::object::COFFObjectFile::getSymbolSection(), llvm::object::MachOObjectFile::getSymbolSection(), llvm::object::COFFObjectFile::section_begin(), llvm::object::MachOObjectFile::section_begin(), llvm::object::COFFObjectFile::section_end(), llvm::object::MachOObjectFile::section_end(), and SectionRef.
SymbolRef
friend class SymbolRef friend
Definition at line 201 of file ObjectFile.h.
References SymbolRef.
Referenced by llvm::object::COFFObjectFile::getCOFFSymbol(), llvm::object::COFFObjectFile::getRelocationSymbol(), llvm::object::MachOObjectFile::getRelocationSymbol(), llvm::object::MachOObjectFile::getSymbolByIndex(), llvm::object::MachOObjectFile::getSymbolSize(), llvm::object::ELFObjectFileBase::getSymbolVersion(), llvm::object::COFFObjectFile::symbol_begin_impl(), llvm::object::COFFObjectFile::symbol_end_impl(), llvm::object::MachOObjectFile::symbol_end_impl(), and SymbolRef.
The documentation for this class was generated from the following files:
ObjectFile.h
COFFObjectFile.cpp
ELFObjectFile.cpp
MachOObjectFile.cpp
ObjectFile.cpp