LLVM: llvm::MipsELFStreamer Class Reference
LLVM API Documentation
llvm::MipsELFStreamer Class Reference
#include <MipsELFStreamer.h>
Public Member Functions
MipsELFStreamer (MCContext &Context, MCAsmBackend &MAB, raw_ostream &OS, MCCodeEmitter *Emitter, const MCSubtargetInfo &STI)
void EmitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI) override
void EmitLabel (MCSymbol *Symbol) override
void SwitchSection (const MCSection *Section, const MCExpr *Subsection=nullptr) override
void EmitValueImpl (const MCExpr *Value, unsigned Size, const SMLoc &Loc) override
void EmitMipsOptionRecords ()
Emits all the option records stored up until the point it's called.
Public Member Functions inherited from llvm::MCELFStreamer
MCELFStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &OS, MCCodeEmitter *Emitter)
MCELFStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &OS, MCCodeEmitter *Emitter, MCAssembler *Assembler)
virtual ~MCELFStreamer ()
void reset () override
state management
void InitSections (bool NoExecStack) override
Create the default sections and set the initial one.
void ChangeSection (const MCSection *Section, const MCExpr *Subsection) override
void EmitAssemblerFlag (MCAssemblerFlag Flag) override
EmitAssemblerFlag - Note in the output the specified Flag.
void EmitThumbFunc (MCSymbol *Func) override
void EmitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
bool EmitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute) override
EmitSymbolAttribute - Add the given Attribute to Symbol.
void EmitSymbolDesc (MCSymbol *Symbol, unsigned DescValue) override
void EmitCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
void BeginCOFFSymbolDef (const MCSymbol *Symbol) override
void EmitCOFFSymbolStorageClass (int StorageClass) override
void EmitCOFFSymbolType (int Type) override
void EndCOFFSymbolDef () override
EndCOFFSymbolDef - Marks the end of the symbol definition.
void EmitELFSize (MCSymbol *Symbol, const MCExpr *Value) override
void EmitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
void EmitZerofill (const MCSection *Section, MCSymbol *Symbol=nullptr, uint64_t Size=0, unsigned ByteAlignment=0) override
void EmitTBSSSymbol (const MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment=0) override
void EmitFileDirective (StringRef Filename) override
void EmitIdent (StringRef IdentString) override
void EmitValueToAlignment (unsigned, int64_t, unsigned, unsigned) override
void Flush () override
Flush - Causes any cached state to be written out.
void FinishImpl () override
FinishImpl - Streamer specific finalization.
void EmitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section. The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
void EmitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void EmitBundleUnlock () override
Ends a bundle-locked group.
Public Member Functions inherited from llvm::MCObjectStreamer
void reset () override
state management
bool isIntegratedAssemblerRequired () const override
Object streamers require the integrated assembler.
MCSymbolData & getOrCreateSymbolData (const MCSymbol *Symbol)
void EmitFrames (MCAsmBackend *MAB)
void EmitCFISections (bool EH, bool Debug) override
void visitUsedSymbol (const MCSymbol &Sym) override
MCAssembler & getAssembler ()
void EmitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
void EmitULEB128Value (const MCExpr *Value) override
void EmitSLEB128Value (const MCExpr *Value) override
void EmitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
void ChangeSection (const MCSection *Section, const MCExpr *Subsection) override
void EmitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section. The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
void EmitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void EmitBundleUnlock () override
Ends a bundle-locked group.
void EmitBytes (StringRef Data) override
void EmitValueToAlignment (unsigned ByteAlignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0) override
void EmitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit=0) override
bool EmitValueToOffset (const MCExpr *Offset, unsigned char Value) override
void EmitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) override
EmitDwarfLocDirective - This implements the DWARF2.
void EmitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol *LastLabel, const MCSymbol *Label, unsigned PointerSize)
void EmitDwarfAdvanceFrameAddr (const MCSymbol *LastLabel, const MCSymbol *Label)
void EmitGPRel32Value (const MCExpr *Value) override
void EmitGPRel64Value (const MCExpr *Value) override
void EmitFill (uint64_t NumBytes, uint8_t FillValue) override
void EmitZeros (uint64_t NumBytes) override
Emit NumBytes worth of zeros. This function properly handles data in virtual sections.
void FinishImpl () override
FinishImpl - Streamer specific finalization.
bool mayHaveInstructions () const override
Public Member Functions inherited from llvm::MCStreamer
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
void setTargetStreamer (MCTargetStreamer *TS)
MCContext & getContext () const
MCTargetStreamer * getTargetStreamer ()
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
unsigned getNumWinFrameInfos ()
ArrayRef< WinEH::FrameInfo * > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
virtual unsigned EmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, unsigned CUID=0)
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
void EmitCFIStartProc (bool IsSimple)
void EmitCFIEndProc ()
virtual void EmitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void EmitCFIDefCfaOffset (int64_t Offset)
virtual void EmitCFIDefCfaRegister (int64_t Register)
virtual void EmitCFIOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFIRememberState ()
virtual void EmitCFIRestoreState ()
virtual void EmitCFISameValue (int64_t Register)
virtual void EmitCFIRestore (int64_t Register)
virtual void EmitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void EmitCFIEscape (StringRef Values)
virtual void EmitCFISignalFrame ()
virtual void EmitCFIUndefined (int64_t Register)
virtual void EmitCFIRegister (int64_t Register1, int64_t Register2)
virtual void EmitCFIWindowSave ()
virtual void EmitWinCFIStartProc (const MCSymbol *Symbol)
virtual void EmitWinCFIEndProc ()
virtual void EmitWinCFIStartChained ()
virtual void EmitWinCFIEndChained ()
virtual void EmitWinCFIPushReg (unsigned Register)
virtual void EmitWinCFISetFrame (unsigned Register, unsigned Offset)
virtual void EmitWinCFIAllocStack (unsigned Size)
virtual void EmitWinCFISaveReg (unsigned Register, unsigned Offset)
virtual void EmitWinCFISaveXMM (unsigned Register, unsigned Offset)
virtual void EmitWinCFIPushFrame (bool Code)
virtual void EmitWinCFIEndProlog ()
virtual void EmitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except)
virtual void EmitWinEHHandlerData ()
void EmitRawText (const Twine &String)
void Finish ()
Finish - Finish emission of machine code.
virtual bool isVerboseAsm () const
virtual bool hasRawTextSupport () const
virtual void AddComment (const Twine &T)
virtual raw_ostream & GetCommentOS ()
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
virtual void AddBlankLine ()
AddBlankLine - Emit a blank line to a .s file to pretty it up.
MCSectionSubPair getCurrentSection () const
MCSectionSubPair getPreviousSection () const
unsigned GetSymbolOrder (const MCSymbol *Sym) const
void PushSection ()
bool PopSection ()
bool SubSection (const MCExpr *Subsection)
void SwitchSectionNoChange (const MCSection *Section, const MCExpr *Subsection=nullptr)
void AssignSection (MCSymbol *Symbol, const MCSection *Section)
virtual void EmitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void EmitLinkerOptions (ArrayRef< std::string > Kind)
virtual void EmitDataRegion (MCDataRegionType Kind)
EmitDataRegion - Note in the output the specified region Kind.
virtual void EmitVersionMin (MCVersionMinType, unsigned Major, unsigned Minor, unsigned Update)
EmitVersionMin - Specify the MachO minimum deployment target version.
virtual void EmitCOFFSectionIndex (MCSymbol const *Symbol)
virtual void EmitCOFFSecRel32 (MCSymbol const *Symbol)
virtual void EmitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
void EmitValue (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc())
virtual void EmitIntValue (uint64_t Value, unsigned Size)
void EmitULEB128IntValue (uint64_t Value, unsigned Padding=0)
void EmitSLEB128IntValue (int64_t Value)
void EmitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCObjectStreamer
MCObjectStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter)
MCObjectStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter, MCAssembler *_Assembler)
~MCObjectStreamer ()
MCSectionData * getCurrentSectionData () const
MCFragment * getCurrentFragment () const
void insert (MCFragment *F)
MCDataFragment * getOrCreateDataFragment ()
Protected Member Functions inherited from llvm::MCStreamer
MCStreamer (MCContext &Ctx)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void EmitWindowsUnwindTables ()
virtual void EmitRawTextImpl (StringRef String)
Detailed Description
Definition at line 29 of file MipsELFStreamer.h.
Constructor & Destructor Documentation
MipsELFStreamer()
llvm::MipsELFStreamer::MipsELFStreamer (MCContext & Context, MCAsmBackend & MAB, raw_ostream & OS, MCCodeEmitter * Emitter, const MCSubtargetInfo & STI) inline
Definition at line 36 of file MipsELFStreamer.h.
References llvm::MCELFStreamer::MCELFStreamer().
Member Function Documentation
EmitInstruction()
void MipsELFStreamer::EmitInstruction (const MCInst & Inst, const MCSubtargetInfo & STI) override virtual
Overriding this function allows us to add arbitrary behaviour before the Inst is actually emitted. For example, we can inspect the operands and gather sufficient information that allows us to reason about the register usage for the translation unit.
Reimplemented from llvm::MCObjectStreamer.
Definition at line 18 of file MipsELFStreamer.cpp.
References llvm::MCObjectStreamer::EmitInstruction(), llvm::MCStreamer::getContext(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCObjectStreamer::getOrCreateSymbolData(), llvm::MCOperand::getReg(), llvm::MCStreamer::getTargetStreamer(), llvm::MipsTargetELFStreamer::isMicroMipsEnabled(), llvm::MCOperand::isReg(), llvm::MCELF::setOther(), and llvm::ELF::STO_MIPS_MICROMIPS.
EmitLabel()
void MipsELFStreamer::EmitLabel (MCSymbol * Symbol) override virtual
Overriding this function allows us to record all labels that should be marked as microMIPS. Based on this data marking is done in EmitInstruction.
Reimplemented from llvm::MCELFStreamer.
Definition at line 50 of file MipsELFStreamer.cpp.
References llvm::MCELFStreamer::EmitLabel().
EmitMipsOptionRecords()
void MipsELFStreamer::EmitMipsOptionRecords ()
Emits all the option records stored up until the point it's called.
Definition at line 67 of file MipsELFStreamer.cpp.
References I.
Referenced by llvm::MipsTargetELFStreamer::finish().
EmitValueImpl()
void MipsELFStreamer::EmitValueImpl (const MCExpr * Value, unsigned Size, const SMLoc & Loc) override virtual
Overriding this function allows us to dismiss all labels that are candidates for marking as microMIPS when .word directive is emitted.
Reimplemented from llvm::MCELFStreamer.
Definition at line 61 of file MipsELFStreamer.cpp.
References llvm::MCELFStreamer::EmitValueImpl().
SwitchSection()
void MipsELFStreamer::SwitchSection (const MCSection * Section, const MCExpr * Subsection = nullptr) override virtual
Overriding this function allows us to dismiss all labels that are candidates for marking as microMIPS when .section directive is processed.
Reimplemented from llvm::MCStreamer.
Definition at line 55 of file MipsELFStreamer.cpp.
References llvm::MCStreamer::SwitchSection().
The documentation for this class was generated from the following files:
MipsELFStreamer.h
MipsELFStreamer.cpp