LLVM: llvm::coverage::RawCoverageReader Class Reference
LLVM API Documentation
llvm::coverage::RawCoverageReader Class Reference
Base class for the raw coverage mapping and filenames data readers.
#include <CoverageMappingReader.h>
Protected Member Functions
std::error_code error (std::error_code EC)
Return the error code.
std::error_code success ()
Clear the current error code and return a successful one.
RawCoverageReader (StringRef Data)
std::error_code readULEB128 (uint64_t &Result)
std::error_code readIntMax (uint64_t &Result, uint64_t MaxPlus1)
std::error_code readSize (uint64_t &Result)
std::error_code readString (StringRef &Result)
Protected Attributes
StringRef Data
Detailed Description
Base class for the raw coverage mapping and filenames data readers.
Definition at line 71 of file CoverageMappingReader.h.
Constructor & Destructor Documentation
RawCoverageReader()
llvm::coverage::RawCoverageReader::RawCoverageReader (StringRef Data) inline protected
Definition at line 81 of file CoverageMappingReader.h.
References Data.
Referenced by llvm::coverage::RawCoverageFilenamesReader::RawCoverageFilenamesReader(), and llvm::coverage::RawCoverageMappingReader::RawCoverageMappingReader().
Member Function Documentation
error()
std::error_code llvm::coverage::RawCoverageReader::error (std::error_code EC) inline protected
Return the error code.
Definition at line 76 of file CoverageMappingReader.h.
Referenced by readIntMax(), readSize(), readULEB128(), and success().
readIntMax()
std::error_code RawCoverageReader::readIntMax (uint64_t & Result, uint64_t MaxPlus1) protected
Definition at line 45 of file CoverageMappingReader.cpp.
References error(), llvm::malformed, readULEB128(), and success().
Referenced by llvm::coverage::RawCoverageMappingReader::read().
readSize()
std::error_code RawCoverageReader::readSize (uint64_t & Result) protected
Definition at line 54 of file CoverageMappingReader.cpp.
References Data, error(), llvm::malformed, readULEB128(), and success().
Referenced by llvm::coverage::RawCoverageFilenamesReader::read(), llvm::coverage::RawCoverageMappingReader::read(), and readString().
readString()
std::error_code RawCoverageReader::readString (StringRef & Result) protected
Definition at line 63 of file CoverageMappingReader.cpp.
References Data, readSize(), and success().
Referenced by llvm::coverage::RawCoverageFilenamesReader::read().
readULEB128()
std::error_code RawCoverageReader::readULEB128 (uint64_t & Result) protected
Definition at line 34 of file CoverageMappingReader.cpp.
References Data, llvm::decodeULEB128(), error(), llvm::malformed, N, success(), and llvm::truncated.
Referenced by readIntMax(), and readSize().
success()
std::error_code llvm::coverage::RawCoverageReader::success () inline protected
Clear the current error code and return a successful one.
Definition at line 79 of file CoverageMappingReader.h.
References error(), and llvm::success.
Referenced by llvm::coverage::RawCoverageFilenamesReader::read(), llvm::coverage::RawCoverageMappingReader::read(), readIntMax(), readSize(), readString(), and readULEB128().
Member Data Documentation
Data
StringRef llvm::coverage::RawCoverageReader::Data protected
Definition at line 73 of file CoverageMappingReader.h.
Referenced by llvm::coverage::RawCoverageFilenamesReader::RawCoverageFilenamesReader(), RawCoverageReader(), readSize(), readString(), and readULEB128().
The documentation for this class was generated from the following files:
CoverageMappingReader.h
CoverageMappingReader.cpp