LLVM: llvm::EquivalenceClasses< ElemTy >::member_iterator Class Reference
LLVM API Documentation
llvm::EquivalenceClasses< ElemTy >::member_iterator Class Reference
#include <EquivalenceClasses.h>
Public Types
typedef size_t size_type
typedef super::pointer pointer
typedef super::reference reference
Public Member Functions
member_iterator ()
member_iterator (const ECValue *N)
reference operator* () const
reference operator-> () const
member_iterator & operator++ ()
member_iterator operator++ (int)
bool operator== (const member_iterator &RHS) const
bool operator!= (const member_iterator &RHS) const
Friends
class EquivalenceClasses
Detailed Description
template<class ElemTy>
class llvm::EquivalenceClasses< ElemTy >::member_iterator
Definition at line 239 of file EquivalenceClasses.h.
Member Typedef Documentation
pointer
template<class ElemTy> typedef super::pointer llvm::EquivalenceClasses< ElemTy >::member_iterator::pointer
Definition at line 247 of file EquivalenceClasses.h.
reference
template<class ElemTy> typedef super::reference llvm::EquivalenceClasses< ElemTy >::member_iterator::reference
Definition at line 248 of file EquivalenceClasses.h.
size_type
template<class ElemTy> typedef size_t llvm::EquivalenceClasses< ElemTy >::member_iterator::size_type
Definition at line 246 of file EquivalenceClasses.h.
Constructor & Destructor Documentation
member_iterator() [1/2]
template<class ElemTy> llvm::EquivalenceClasses< ElemTy >::member_iterator::member_iterator () inline explicit
Definition at line 250 of file EquivalenceClasses.h.
Referenced by operator!=(), operator++(), operator++(), and operator==().
member_iterator() [2/2]
template<class ElemTy> llvm::EquivalenceClasses< ElemTy >::member_iterator::member_iterator (const ECValue * N) inline explicit
Definition at line 251 of file EquivalenceClasses.h.
References N.
Member Function Documentation
operator!=()
template<class ElemTy> bool llvm::EquivalenceClasses< ElemTy >::member_iterator::operator!= (const member_iterator & RHS) const inline
Definition at line 274 of file EquivalenceClasses.h.
References member_iterator().
operator*()
template<class ElemTy> reference llvm::EquivalenceClasses< ElemTy >::member_iterator::operator* () const inline
Definition at line 253 of file EquivalenceClasses.h.
Referenced by operator->().
operator++() [1/2]
template<class ElemTy> member_iterator & llvm::EquivalenceClasses< ElemTy >::member_iterator::operator++ () inline
Definition at line 259 of file EquivalenceClasses.h.
References member_iterator().
operator++() [2/2]
template<class ElemTy> member_iterator llvm::EquivalenceClasses< ElemTy >::member_iterator::operator++ (int) inline
Definition at line 265 of file EquivalenceClasses.h.
References member_iterator().
operator->()
template<class ElemTy> reference llvm::EquivalenceClasses< ElemTy >::member_iterator::operator-> () const inline
Definition at line 257 of file EquivalenceClasses.h.
References operator*().
operator==()
template<class ElemTy> bool llvm::EquivalenceClasses< ElemTy >::member_iterator::operator== (const member_iterator & RHS) const inline
Definition at line 271 of file EquivalenceClasses.h.
References member_iterator().
Friends And Related Symbol Documentation
EquivalenceClasses
template<class ElemTy> friend class EquivalenceClasses friend
Definition at line 244 of file EquivalenceClasses.h.
References EquivalenceClasses.
Referenced by EquivalenceClasses.
The documentation for this class was generated from the following file:
EquivalenceClasses.h