LLVM: llvm::Mips16InstrInfo Class Reference
LLVM API Documentation
llvm::Mips16InstrInfo Class Reference
#include <Mips16InstrInfo.h>
Public Member Functions
Mips16InstrInfo (const MipsSubtarget &STI)
const MipsRegisterInfo & getRegisterInfo () const override
unsigned isLoadFromStackSlot (const MachineInstr *MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr *MI, int &FrameIndex) const override
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
void storeRegToStack (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, int64_t Offset) const override
void loadRegFromStack (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, int64_t Offset) const override
bool expandPostRAPseudo (MachineBasicBlock::iterator MI) const override
unsigned getOppositeBranchOpc (unsigned Opc) const override
void makeFrame (unsigned SP, int64_t FrameSize, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const
void restoreFrame (unsigned SP, int64_t FrameSize, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const
void adjustStackPtr (unsigned SP, int64_t Amount, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const
Adjust SP by Amount bytes.
unsigned loadImmediate (unsigned FrameReg, int64_t Imm, MachineBasicBlock &MBB, MachineBasicBlock::iterator II, DebugLoc DL, unsigned &NewImm) const
Emit a series of instructions to load an immediate.
const MCInstrDesc & AddiuSpImm (int64_t Imm) const
void BuildAddiuSpImm (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, int64_t Imm) const
unsigned getInlineAsmLength (const char *Str, const MCAsmInfo &MAI) const override
Public Member Functions inherited from llvm::MipsInstrInfo
MipsInstrInfo (const MipsSubtarget &STI, unsigned UncondBrOpc)
bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
Branch Analysis.
unsigned RemoveBranch (MachineBasicBlock &MBB) const override
unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const override
bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
BranchType AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify, SmallVectorImpl< MachineInstr * > &BranchInstrs) const
void insertNoop (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
Insert nop instruction when hazard condition is found.
unsigned GetInstSizeInBytes (const MachineInstr *MI) const
Return the number of bytes of code the specified instruction may be.
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
MachineInstrBuilder genInstrWithNewOpc (unsigned NewOpc, MachineBasicBlock::iterator I) const
Static Public Member Functions
static bool validImmediate (unsigned Opcode, unsigned Reg, int64_t Amount)
static bool validSpImm8 (int offset)
Static Public Member Functions inherited from llvm::MipsInstrInfo
static const MipsInstrInfo * create (MipsSubtarget &STI)
Additional Inherited Members
Public Types inherited from llvm::MipsInstrInfo
enum BranchType {
BT_None , BT_NoBranch , BT_Uncond , BT_Cond ,
BT_CondUncond , BT_Indirect
}
Protected Member Functions inherited from llvm::MipsInstrInfo
bool isZeroImm (const MachineOperand &op) const
MachineMemOperand * GetMemOperand (MachineBasicBlock &MBB, int FI, unsigned Flag) const
Protected Attributes inherited from llvm::MipsInstrInfo
const MipsSubtarget & Subtarget
unsigned UncondBrOpc
Detailed Description
Definition at line 22 of file Mips16InstrInfo.h.
Constructor & Destructor Documentation
Mips16InstrInfo()
Mips16InstrInfo::Mips16InstrInfo (const MipsSubtarget & STI) explicit
Definition at line 34 of file Mips16InstrInfo.cpp.
References llvm::MipsInstrInfo::MipsInstrInfo().
Member Function Documentation
AddiuSpImm()
const MCInstrDesc & Mips16InstrInfo::AddiuSpImm (int64_t Imm) const
Definition at line 440 of file Mips16InstrInfo.cpp.
References validSpImm8().
Referenced by BuildAddiuSpImm().
adjustStackPtr()
void Mips16InstrInfo::adjustStackPtr (unsigned SP, int64_t Amount, MachineBasicBlock & MBB, MachineBasicBlock::iterator I) const
Adjust SP by Amount bytes.
Definition at line 293 of file Mips16InstrInfo.cpp.
References BuildAddiuSpImm(), I, and llvm::isInt().
BuildAddiuSpImm()
void Mips16InstrInfo::BuildAddiuSpImm (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, int64_t Imm) const
Definition at line 447 of file Mips16InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), AddiuSpImm(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), and I.
Referenced by adjustStackPtr(), makeFrame(), and restoreFrame().
copyPhysReg()
void Mips16InstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
Definition at line 61 of file Mips16InstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), llvm::RegState::Define, llvm::getKillRegState(), and I.
Referenced by loadImmediate().
expandPostRAPseudo()
bool Mips16InstrInfo::expandPostRAPseudo (MachineBasicBlock::iterator MI) const override
Definition at line 129 of file Mips16InstrInfo.cpp.
References llvm::MachineBasicBlock::erase().
getInlineAsmLength()
unsigned Mips16InstrInfo::getInlineAsmLength (const char * Str, const MCAsmInfo & MAI) const override
Measure the specified inline asm to determine an approximation of its length. Comments (which run till the next SeparatorString or newline) do not count as an instruction. Any other non-whitespace text is considered an instruction, with multiple instructions separated by SeparatorString or newlines. Variable-length instructions are not handled here; this function may be overloaded in the target code to do that. We implement the special case of the .space directive taking only an integer argument, which is the size in bytes. This is used for creating inline code spacing for testing purposes using inline assembly.
Definition at line 491 of file Mips16InstrInfo.cpp.
References llvm::dbgs(), DEBUG, llvm::MCAsmInfo::getCommentString(), llvm::MCAsmInfo::getMaxInstLength(), and llvm::MCAsmInfo::getSeparatorString().
getOppositeBranchOpc()
unsigned Mips16InstrInfo::getOppositeBranchOpc (unsigned Opc) const override virtual
GetOppositeBranchOpc - Return the inverse of the specified opcode, e.g. turning BEQ to BNE.
Implements llvm::MipsInstrInfo.
Definition at line 145 of file Mips16InstrInfo.cpp.
References llvm_unreachable.
getRegisterInfo()
const MipsRegisterInfo & Mips16InstrInfo::getRegisterInfo () const override virtual
getRegisterInfo - TargetInstrInfo is a superset of MRegister info. As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Implements llvm::MipsInstrInfo.
Definition at line 37 of file Mips16InstrInfo.cpp.
isLoadFromStackSlot()
unsigned Mips16InstrInfo::isLoadFromStackSlot (const MachineInstr * MI, int & FrameIndex) const override
isLoadFromStackSlot - If the specified machine instruction is a direct load from a stack slot, return the virtual or physical register number of the destination along with the FrameIndex of the loaded stack slot. If not, return 0. This predicate must return 0 if the instruction has any side effects other than loading from the stack slot.
Definition at line 46 of file Mips16InstrInfo.cpp.
isStoreToStackSlot()
unsigned Mips16InstrInfo::isStoreToStackSlot (const MachineInstr * MI, int & FrameIndex) const override
isStoreToStackSlot - If the specified machine instruction is a direct store to a stack slot, return the virtual or physical register number of the source reg along with the FrameIndex of the loaded stack slot. If not, return 0. This predicate must return 0 if the instruction has any side effects other than storing to the stack slot.
Definition at line 56 of file Mips16InstrInfo.cpp.
loadImmediate()
unsigned Mips16InstrInfo::loadImmediate (unsigned FrameReg, int64_t Imm, MachineBasicBlock & MBB, MachineBasicBlock::iterator II, DebugLoc DL, unsigned & NewImm) const
Emit a series of instructions to load an immediate.
This function generates the sequence of instructions needed to get the result of adding register REG and immediate IMM.
Definition at line 307 of file Mips16InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), copyPhysReg(), llvm::RegScavenger::enterBasicBlock(), llvm::BitVector::find_first(), llvm::RegScavenger::forward(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::RegScavenger::getRegsAvailable(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::RegState::Kill, and llvm::BitVector::reset().
loadRegFromStack()
void Mips16InstrInfo::loadRegFromStack (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, int64_t Offset) const override virtual
Implements llvm::MipsInstrInfo.
Definition at line 111 of file Mips16InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MipsInstrInfo::GetMemOperand(), I, and llvm::MachineMemOperand::MOLoad.
makeFrame()
void Mips16InstrInfo::makeFrame (unsigned SP, int64_t FrameSize, MachineBasicBlock & MBB, MachineBasicBlock::iterator I) const
Definition at line 196 of file Mips16InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), addSaveRestoreRegs(), BuildAddiuSpImm(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineBasicBlock::getParent(), I, llvm::isInt(), and llvm::isUInt().
restoreFrame()
void Mips16InstrInfo::restoreFrame (unsigned SP, int64_t FrameSize, MachineBasicBlock & MBB, MachineBasicBlock::iterator I) const
Definition at line 226 of file Mips16InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), addSaveRestoreRegs(), BuildAddiuSpImm(), llvm::BuildMI(), llvm::RegState::Define, llvm::MachineBasicBlock::end(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineBasicBlock::getParent(), I, llvm::isInt(), and llvm::isUInt().
storeRegToStack()
void Mips16InstrInfo::storeRegToStack (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, int64_t Offset) const override virtual
Implements llvm::MipsInstrInfo.
Definition at line 93 of file Mips16InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::getKillRegState(), llvm::MipsInstrInfo::GetMemOperand(), I, and llvm::MachineMemOperand::MOStore.
validImmediate()
bool Mips16InstrInfo::validImmediate (unsigned Opcode, unsigned Reg, int64_t Amount) static
Definition at line 457 of file Mips16InstrInfo.cpp.
References llvm::isInt(), llvm::isInt< 16 >(), and llvm_unreachable.
validSpImm8()
bool llvm::Mips16InstrInfo::validSpImm8 (int offset) inline static
Definition at line 93 of file Mips16InstrInfo.h.
References llvm::isInt().
Referenced by AddiuSpImm().
The documentation for this class was generated from the following files:
Mips16InstrInfo.h
Mips16InstrInfo.cpp