LLVM: llvm::DIBuilder Class Reference
LLVM API Documentation
llvm::DIBuilder Class Reference
#include <DIBuilder.h>
Public Types
enum DebugEmissionKind { FullDebug =1 , LineTablesOnly }
Public Member Functions
DIBuilder (Module &M, bool AllowUnresolved=true)
Construct a builder for a module.
void finalize ()
finalize - Construct any deferred debug info descriptors.
DICompileUnit createCompileUnit (unsigned Lang, StringRef File, StringRef Dir, StringRef Producer, bool isOptimized, StringRef Flags, unsigned RV, StringRef SplitName=StringRef(), DebugEmissionKind Kind=FullDebug, bool EmitDebugInfo=true)
DIFile createFile (StringRef Filename, StringRef Directory)
DIEnumerator createEnumerator (StringRef Name, int64_t Val)
createEnumerator - Create a single enumerator value.
DIBasicType createUnspecifiedType (StringRef Name)
Create a DWARF unspecified type.
DIBasicType createNullPtrType ()
Create C++11 nullptr type.
DIBasicType createBasicType (StringRef Name, uint64_t SizeInBits, uint64_t AlignInBits, unsigned Encoding)
DIDerivedType createQualifiedType (unsigned Tag, DIType FromTy)
DIDerivedType createPointerType (DIType PointeeTy, uint64_t SizeInBits, uint64_t AlignInBits=0, StringRef Name=StringRef())
DIDerivedType createMemberPointerType (DIType PointeeTy, DIType Class, uint64_t SizeInBits, uint64_t AlignInBits=0)
Create debugging information entry for a pointer to member.
DIDerivedType createReferenceType (unsigned Tag, DIType RTy)
DIDerivedType createTypedef (DIType Ty, StringRef Name, DIFile File, unsigned LineNo, DIDescriptor Context)
DIDerivedType createFriend (DIType Ty, DIType FriendTy)
createFriend - Create debugging information entry for a 'friend'.
DIDerivedType createInheritance (DIType Ty, DIType BaseTy, uint64_t BaseOffset, unsigned Flags)
DIDerivedType createMemberType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNo, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, DIType Ty)
DIDerivedType createStaticMemberType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNo, DIType Ty, unsigned Flags, llvm::Constant *Val)
DIDerivedType createObjCIVar (StringRef Name, DIFile File, unsigned LineNo, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, DIType Ty, MDNode *PropertyNode)
DIObjCProperty createObjCProperty (StringRef Name, DIFile File, unsigned LineNumber, StringRef GetterName, StringRef SetterName, unsigned PropertyAttributes, DIType Ty)
DICompositeType createClassType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNumber, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, DIType DerivedFrom, DIArray Elements, DIType VTableHolder=DIType(), MDNode *TemplateParms=nullptr, StringRef UniqueIdentifier=StringRef())
DICompositeType createStructType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNumber, uint64_t SizeInBits, uint64_t AlignInBits, unsigned Flags, DIType DerivedFrom, DIArray Elements, unsigned RunTimeLang=0, DIType VTableHolder=DIType(), StringRef UniqueIdentifier=StringRef())
DICompositeType createUnionType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNumber, uint64_t SizeInBits, uint64_t AlignInBits, unsigned Flags, DIArray Elements, unsigned RunTimeLang=0, StringRef UniqueIdentifier=StringRef())
DITemplateTypeParameter createTemplateTypeParameter (DIDescriptor Scope, StringRef Name, DIType Ty, MDNode *File=nullptr, unsigned LineNo=0, unsigned ColumnNo=0)
DITemplateValueParameter createTemplateValueParameter (DIDescriptor Scope, StringRef Name, DIType Ty, Constant *Val, MDNode *File=nullptr, unsigned LineNo=0, unsigned ColumnNo=0)
DITemplateValueParameter createTemplateTemplateParameter (DIDescriptor Scope, StringRef Name, DIType Ty, StringRef Val, MDNode *File=nullptr, unsigned LineNo=0, unsigned ColumnNo=0)
Create debugging information for a template template parameter.
DITemplateValueParameter createTemplateParameterPack (DIDescriptor Scope, StringRef Name, DIType Ty, DIArray Val, MDNode *File=nullptr, unsigned LineNo=0, unsigned ColumnNo=0)
Create debugging information for a template parameter pack.
DICompositeType createArrayType (uint64_t Size, uint64_t AlignInBits, DIType Ty, DIArray Subscripts)
DICompositeType createVectorType (uint64_t Size, uint64_t AlignInBits, DIType Ty, DIArray Subscripts)
DICompositeType createEnumerationType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNumber, uint64_t SizeInBits, uint64_t AlignInBits, DIArray Elements, DIType UnderlyingType, StringRef UniqueIdentifier=StringRef())
DISubroutineType createSubroutineType (DIFile File, DITypeArray ParameterTypes, unsigned Flags=0)
DIType createArtificialType (DIType Ty)
createArtificialType - Create a new DIType with "artificial" flag set.
DIType createObjectPointerType (DIType Ty)
DICompositeType createForwardDecl (unsigned Tag, StringRef Name, DIDescriptor Scope, DIFile F, unsigned Line, unsigned RuntimeLang=0, uint64_t SizeInBits=0, uint64_t AlignInBits=0, StringRef UniqueIdentifier=StringRef())
Create a permanent forward-declared type.
DICompositeType createReplaceableForwardDecl (unsigned Tag, StringRef Name, DIDescriptor Scope, DIFile F, unsigned Line, unsigned RuntimeLang=0, uint64_t SizeInBits=0, uint64_t AlignInBits=0, StringRef UniqueIdentifier=StringRef())
Create a temporary forward-declared type.
void retainType (DIType T)
DIBasicType createUnspecifiedParameter ()
DIArray getOrCreateArray (ArrayRef< Metadata * > Elements)
getOrCreateArray - Get a DIArray, create one if required.
DITypeArray getOrCreateTypeArray (ArrayRef< Metadata * > Elements)
getOrCreateTypeArray - Get a DITypeArray, create one if required.
DISubrange getOrCreateSubrange (int64_t Lo, int64_t Count)
DIGlobalVariable createGlobalVariable (DIDescriptor Context, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DITypeRef Ty, bool isLocalToUnit, llvm::Constant *Val, MDNode *Decl=nullptr)
DIGlobalVariable createTempGlobalVariableFwdDecl (DIDescriptor Context, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DITypeRef Ty, bool isLocalToUnit, llvm::Constant *Val, MDNode *Decl=nullptr)
DIVariable createLocalVariable (unsigned Tag, DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNo, DITypeRef Ty, bool AlwaysPreserve=false, unsigned Flags=0, unsigned ArgNo=0)
DIExpression createExpression (ArrayRef< int64_t > Addr=None)
DIExpression createPieceExpression (unsigned OffsetInBytes, unsigned SizeInBytes)
DISubprogram createFunction (DIDescriptor Scope, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DICompositeType Ty, bool isLocalToUnit, bool isDefinition, unsigned ScopeLine, unsigned Flags=0, bool isOptimized=false, Function *Fn=nullptr, MDNode *TParam=nullptr, MDNode *Decl=nullptr)
DISubprogram createTempFunctionFwdDecl (DIDescriptor Scope, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DICompositeType Ty, bool isLocalToUnit, bool isDefinition, unsigned ScopeLine, unsigned Flags=0, bool isOptimized=false, Function *Fn=nullptr, MDNode *TParam=nullptr, MDNode *Decl=nullptr)
DISubprogram createFunction (DIScopeRef Scope, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DICompositeType Ty, bool isLocalToUnit, bool isDefinition, unsigned ScopeLine, unsigned Flags=0, bool isOptimized=false, Function *Fn=nullptr, MDNode *TParam=nullptr, MDNode *Decl=nullptr)
DISubprogram createMethod (DIDescriptor Scope, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DICompositeType Ty, bool isLocalToUnit, bool isDefinition, unsigned Virtuality=0, unsigned VTableIndex=0, DIType VTableHolder=DIType(), unsigned Flags=0, bool isOptimized=false, Function *Fn=nullptr, MDNode *TParam=nullptr)
DINameSpace createNameSpace (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNo)
DILexicalBlockFile createLexicalBlockFile (DIDescriptor Scope, DIFile File, unsigned Discriminator=0)
DILexicalBlock createLexicalBlock (DIDescriptor Scope, DIFile File, unsigned Line, unsigned Col)
DIImportedEntity createImportedModule (DIScope Context, DINameSpace NS, unsigned Line)
Create a descriptor for an imported module.
DIImportedEntity createImportedModule (DIScope Context, DIImportedEntity NS, unsigned Line)
Create a descriptor for an imported module.
DIImportedEntity createImportedDeclaration (DIScope Context, DIDescriptor Decl, unsigned Line, StringRef Name=StringRef())
Create a descriptor for an imported function.
DIImportedEntity createImportedDeclaration (DIScope Context, DIImportedEntity NS, unsigned Line, StringRef Name=StringRef())
Instruction * insertDeclare (llvm::Value *Storage, DIVariable VarInfo, DIExpression Expr, BasicBlock *InsertAtEnd)
Instruction * insertDeclare (llvm::Value *Storage, DIVariable VarInfo, DIExpression Expr, Instruction *InsertBefore)
Instruction * insertDbgValueIntrinsic (llvm::Value *Val, uint64_t Offset, DIVariable VarInfo, DIExpression Expr, BasicBlock *InsertAtEnd)
Instruction * insertDbgValueIntrinsic (llvm::Value *Val, uint64_t Offset, DIVariable VarInfo, DIExpression Expr, Instruction *InsertBefore)
void replaceVTableHolder (DICompositeType &T, DICompositeType VTableHolder)
Replace the vtable holder in the given composite type.
void replaceArrays (DICompositeType &T, DIArray Elements, DIArray TParems=DIArray())
Replace arrays on a composite type.
Detailed Description
Definition at line 56 of file DIBuilder.h.
Member Enumeration Documentation
DebugEmissionKind
enum llvm::DIBuilder::DebugEmissionKind
Enumerator
FullDebug
LineTablesOnly
Definition at line 97 of file DIBuilder.h.
Constructor & Destructor Documentation
DIBuilder()
DIBuilder::DIBuilder (Module & M, bool AllowUnresolved = true) explicit
Construct a builder for a module.
If AllowUnresolved, collect unresolved nodes attached to the module in order to resolve cycles during finalize().
Definition at line 51 of file DIBuilder.cpp.
Member Function Documentation
createArrayType()
DICompositeType DIBuilder::createArrayType (uint64_t Size, uint64_t AlignInBits, DIType Ty, DIArray Subscripts)
createArrayType - Create debugging information entry for an array.
Parameters
Size Array size.
AlignInBits Alignment.
Ty Element type.
Subscripts Subscripts.
Definition at line 695 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_array_type, llvm::MDNode::get(), and llvm::DIScope::getRef().
createArtificialType()
DIType DIBuilder::createArtificialType (DIType Ty)
createArtificialType - Create a new DIType with "artificial" flag set.
Definition at line 764 of file DIBuilder.cpp.
References createTypeWithFlags(), llvm::DIDescriptor::FlagArtificial, and llvm::DIType::isArtificial().
createBasicType()
DIBasicType DIBuilder::createBasicType (StringRef Name, uint64_t SizeInBits, uint64_t AlignInBits, unsigned Encoding)
createBasicType - Create debugging information entry for a basic type.
Parameters
Name Type name.
SizeInBits Size of the type.
AlignInBits Type alignment.
Encoding DWARF encoding code, e.g. dwarf::DW_ATE_float.
Definition at line 277 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_base_type, llvm::MDNode::get(), and Name.
createClassType()
DICompositeType DIBuilder::createClassType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNumber, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, DIType DerivedFrom, DIArray Elements, DIType VTableHolder = DIType(), MDNode * TemplateParms = nullptr, StringRef UniqueIdentifier = StringRef())
createClassType - Create debugging information entry for a class.
Parameters
Scope Scope in which this class is defined.
Name class name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
OffsetInBits Member offset.
Flags Flags to encode member attribute, e.g. private
Elements class members.
VTableHolder Debug info of the base class that contains vtable for this type. This is used in DW_AT_containing_type. See DWARF documentation for more info.
TemplateParms Template type parameters.
UniqueIdentifier A unique identifier for the class.
Definition at line 553 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_class_type, llvm::StringRef::empty(), llvm::MDNode::get(), llvm::MDString::get(), getNonCompileUnitScope(), llvm::DIScope::getRef(), llvm::DIDescriptor::isCompositeType(), llvm::DIDescriptor::isScope(), llvm::DIDescriptor::isType(), Name, and retainType().
createCompileUnit()
DICompileUnit DIBuilder::createCompileUnit (unsigned Lang, StringRef File, StringRef Dir, StringRef Producer, bool isOptimized, StringRef Flags, unsigned RV, StringRef SplitName = StringRef(), DebugEmissionKind Kind = FullDebug, bool EmitDebugInfo = true)
createCompileUnit - A CompileUnit provides an anchor for all debugging information generated during this instance of compilation.
Parameters
Lang Source programming language, eg. dwarf::DW_LANG_C99
File File name
Dir Directory
Producer Identify the producer of debugging information and code. Usually this is a compiler version string.
isOptimized A boolean flag which indicates whether optimization is ON or not.
Flags This string lists command line options. This string is directly embedded in debug info output which may be used by a tool analyzing generated debugging information.
RV This indicates runtime version for languages like Objective-C.
SplitName The name of the file that we'll split debug info out into.
Kind The kind of debug information to generate.
EmitDebugInfo A boolean flag which indicates whether debug information should be written to the final output or not. When this is false, debug information annotations will be present in the IL but they are not written to the final assembly or object file. This supports tracking source location information in the back end without actually changing the output (e.g., when using optimization remarks).
Definition at line 136 of file DIBuilder.cpp.
References llvm::NamedMDNode::addOperand(), createFilePathPair(), llvm::dwarf::DW_LANG_C89, llvm::dwarf::DW_LANG_lo_user, llvm::dwarf::DW_TAG_base_type, llvm::dwarf::DW_TAG_compile_unit, llvm::StringRef::empty(), llvm::MDNode::get(), and llvm::MDNode::getTemporary().
createEnumerationType()
DICompositeType DIBuilder::createEnumerationType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNumber, uint64_t SizeInBits, uint64_t AlignInBits, DIArray Elements, DIType UnderlyingType, StringRef UniqueIdentifier = StringRef())
createEnumerationType - Create debugging information entry for an enumeration.
Parameters
Scope Scope in which this enumeration is defined.
Name Union name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
Elements Enumeration elements.
UnderlyingType Underlying type of a C++11/ObjC fixed enum.
UniqueIdentifier A unique identifier for the enum.
Definition at line 669 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_enumeration_type, llvm::StringRef::empty(), llvm::MDNode::get(), llvm::MDString::get(), getNonCompileUnitScope(), llvm::DIScope::getRef(), Name, and retainType().
createEnumerator()
DIEnumerator DIBuilder::createEnumerator (StringRef Name, int64_t Val)
createEnumerator - Create a single enumerator value.
Definition at line 243 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_enumerator, llvm::MDNode::get(), and Name.
createExpression()
DIExpression DIBuilder::createExpression (ArrayRef< int64_t > Addr = None)
createExpression - Create a new descriptor for the specified variable which has a complex address expression for its address.
Parameters
Addr An array of complex address operations.
Definition at line 944 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_expression, llvm::MDNode::get(), and I.
Referenced by createPieceExpression(), getExpression(), and llvm::replaceDbgDeclareForAlloca().
createFile()
DIFile DIBuilder::createFile (StringRef Filename, StringRef Directory)
createFile - Create a file descriptor to hold debugging information for a file.
Definition at line 236 of file DIBuilder.cpp.
References createFilePathPair(), llvm::dwarf::DW_TAG_file_type, and llvm::MDNode::get().
createForwardDecl()
DICompositeType DIBuilder::createForwardDecl (unsigned Tag, StringRef Name, DIDescriptor Scope, DIFile F, unsigned Line, unsigned RuntimeLang = 0, uint64_t SizeInBits = 0, uint64_t AlignInBits = 0, StringRef UniqueIdentifier = StringRef())
Create a permanent forward-declared type.
Definition at line 784 of file DIBuilder.cpp.
References llvm::StringRef::empty(), F, llvm::DIDescriptor::FlagFwdDecl, llvm::MDNode::get(), llvm::MDString::get(), getNonCompileUnitScope(), llvm::DIScope::getRef(), llvm::DIDescriptor::isCompositeType(), Name, and retainType().
createFriend()
DIDerivedType DIBuilder::createFriend (DIType Ty, DIType FriendTy)
createFriend - Create debugging information entry for a 'friend'.
Definition at line 384 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_friend, llvm::MDNode::get(), llvm::DIScope::getRef(), and llvm::DIDescriptor::isType().
createFunction() [1/2]
DISubprogram DIBuilder::createFunction (DIDescriptor Scope, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DICompositeType Ty, bool isLocalToUnit, bool isDefinition, unsigned ScopeLine, unsigned Flags = 0, bool isOptimized = false, Function * Fn = nullptr, MDNode * TParam = nullptr, MDNode * Decl = nullptr)
createFunction - Create a new descriptor for the specified subprogram. See comments in DISubprogram for descriptions of these fields.
Parameters
Scope Function scope.
Name Function name.
LinkageName Mangled function name.
File File where this variable is defined.
LineNo Line number.
Ty Function type.
isLocalToUnit True if this function is not externally visible.
isDefinition True if this is a function definition.
ScopeLine Set to the beginning of the scope this starts
Flags e.g. is this function prototyped or not. These flags are used to emit dwarf attributes.
isOptimized True if optimization is ON.
Fn llvm::Function pointer.
TParam Function template parameters.
Definition at line 1005 of file DIBuilder.cpp.
References createFunctionHelper(), llvm::MDNode::get(), llvm::MDNode::getTemporary(), llvm::LinkageName, Name, and llvm::None.
Referenced by createFunction().
createFunction() [2/2]
DISubprogram DIBuilder::createFunction (DIScopeRef Scope, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DICompositeType Ty, bool isLocalToUnit, bool isDefinition, unsigned ScopeLine, unsigned Flags = 0, bool isOptimized = false, Function * Fn = nullptr, MDNode * TParam = nullptr, MDNode * Decl = nullptr)
FIXME: this is added for dragonegg. Once we update dragonegg to call resolve function, this will be removed.
Definition at line 958 of file DIBuilder.cpp.
References createFunction(), llvm::LinkageName, Name, and llvm::DIRef< T >::resolve().
createGlobalVariable()
DIGlobalVariable DIBuilder::createGlobalVariable (DIDescriptor Context, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DITypeRef Ty, bool isLocalToUnit, llvm::Constant * Val, MDNode * Decl = nullptr)
createGlobalVariable - Create a new descriptor for the specified variable.
Parameters
Context Variable scope.
Name Name of the variable.
LinkageName Mangled name of the variable.
File File where this variable is defined.
LineNo Line number.
Ty Variable Type.
isLocalToUnit Boolean flag indicate whether this variable is externally visible or not.
Val llvm::Value of the variable.
Decl Reference to the corresponding declaration.
Definition at line 891 of file DIBuilder.cpp.
References createGlobalVariableHelper(), F, llvm::MDNode::get(), llvm::LinkageName, and Name.
createImportedDeclaration() [1/2]
DIImportedEntity DIBuilder::createImportedDeclaration (DIScope Context, DIDescriptor Decl, unsigned Line, StringRef Name = StringRef())
Create a descriptor for an imported function.
Parameters
Context The scope this module is imported into
Decl The declaration (or definition) of a function, type, or variable
Line Line number
Definition at line 217 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_imported_declaration, llvm::DIScope::getRef(), llvm::DIDescriptor::isType(), and Name.
createImportedDeclaration() [2/2]
DIImportedEntity DIBuilder::createImportedDeclaration (DIScope Context, DIImportedEntity NS, unsigned Line, StringRef Name = StringRef())
Definition at line 229 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_imported_declaration, and Name.
createImportedModule() [1/2]
DIImportedEntity DIBuilder::createImportedModule (DIScope Context, DIImportedEntity NS, unsigned Line)
Create a descriptor for an imported module.
Parameters
Context The scope this module is imported into
NS An aliased namespace
Line Line number
Definition at line 210 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_imported_module.
createImportedModule() [2/2]
DIImportedEntity DIBuilder::createImportedModule (DIScope Context, DINameSpace NS, unsigned Line)
Create a descriptor for an imported module.
Parameters
Context The scope this module is imported into
NS The namespace being imported here
Line Line number
Definition at line 203 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_imported_module.
createInheritance()
DIDerivedType DIBuilder::createInheritance (DIType Ty, DIType BaseTy, uint64_t BaseOffset, unsigned Flags)
createInheritance - Create debugging information entry to establish inheritance relationship between two types.
Parameters
Ty Original type.
BaseTy Base type. Ty is inherits from base.
BaseOffset Base offset.
Flags Flags to describe inheritance attribute, e.g. private
Definition at line 400 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_inheritance, llvm::MDNode::get(), llvm::DIScope::getRef(), and llvm::DIDescriptor::isType().
createLexicalBlock()
DILexicalBlock DIBuilder::createLexicalBlock (DIDescriptor Scope, DIFile File, unsigned Line, unsigned Col)
createLexicalBlock - This creates a descriptor for a lexical block with the specified parent context.
Parameters
Scope Parent lexical scope.
File Source file.
Line Line number.
Col Column number.
Definition at line 1107 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_lexical_block, llvm::MDNode::get(), getNonCompileUnitScope(), and llvm::DILexicalBlock::Verify().
createLexicalBlockFile()
DILexicalBlockFile DIBuilder::createLexicalBlockFile (DIDescriptor Scope, DIFile File, unsigned Discriminator = 0)
createLexicalBlockFile - This creates a descriptor for a lexical block with a new file attached. This merely extends the existing lexical block as it crosses a file.
Parameters
Scope Lexical block.
File Source file.
Discriminator DWARF path discriminator value.
Definition at line 1093 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_lexical_block, llvm::MDNode::get(), and llvm::DILexicalBlockFile::Verify().
createLocalVariable()
DIVariable DIBuilder::createLocalVariable (unsigned Tag, DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNo, DITypeRef Ty, bool AlwaysPreserve = false, unsigned Flags = 0, unsigned ArgNo = 0)
createLocalVariable - Create a new descriptor for the specified local variable.
Parameters
Tag Dwarf TAG. Usually DW_TAG_auto_variable or DW_TAG_arg_variable.
Scope Variable scope.
Name Variable name.
File File where this variable is defined.
LineNo Line number.
Ty Variable Type
AlwaysPreserve Boolean. Set to true if debug info for this variable should be preserved in optimized build.
Flags Flags, e.g. artificial variable.
ArgNo If this variable is an argument then this argument's number. 1 indicates 1st argument.
Definition at line 915 of file DIBuilder.cpp.
References llvm::MDNode::get(), llvm::getDISubprogram(), getNonCompileUnitScope(), llvm::DIDescriptor::isScope(), llvm::DIDescriptor::isVariable(), and Name.
createMemberPointerType()
DIDerivedType DIBuilder::createMemberPointerType (DIType PointeeTy, DIType Class, uint64_t SizeInBits, uint64_t AlignInBits = 0)
Create debugging information entry for a pointer to member.
Parameters
PointeeTy Type pointed to by this pointer.
SizeInBits Size.
AlignInBits Alignment. (optional)
Class Type for which this pointer points to members of.
Definition at line 333 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_ptr_to_member_type, llvm::MDNode::get(), and llvm::DIScope::getRef().
createMemberType()
DIDerivedType DIBuilder::createMemberType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNo, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, DIType Ty)
createMemberType - Create debugging information entry for a member.
Parameters
Scope Member scope.
Name Member name.
File File where this member is defined.
LineNo Line number.
SizeInBits Member size.
AlignInBits Member alignment.
OffsetInBits Member offset.
Flags Flags to encode member attribute, e.g. private
Ty Parent type.
Definition at line 417 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_member, llvm::MDNode::get(), getNonCompileUnitScope(), llvm::DIScope::getRef(), and Name.
createMethod()
DISubprogram DIBuilder::createMethod (DIDescriptor Scope, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DICompositeType Ty, bool isLocalToUnit, bool isDefinition, unsigned Virtuality = 0, unsigned VTableIndex = 0, DIType VTableHolder = DIType(), unsigned Flags = 0, bool isOptimized = false, Function * Fn = nullptr, MDNode * TParam = nullptr)
createMethod - Create a new descriptor for the specified C++ method. See comments in DISubprogram for descriptions of these fields.
Parameters
Scope Function scope.
Name Function name.
LinkageName Mangled function name.
File File where this variable is defined.
LineNo Line number.
Ty Function type.
isLocalToUnit True if this function is not externally visible..
isDefinition True if this is a function definition.
Virtuality Attributes describing virtualness. e.g. pure virtual function.
VTableIndex Index no of this method in virtual table.
VTableHolder Type that holds vtable.
Flags e.g. is this function prototyped or not. This flags are used to emit dwarf attributes.
isOptimized True if optimization is ON.
Fn llvm::Function pointer.
TParam Function template parameters.
Definition at line 1042 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_subprogram, llvm::dwarf::DW_TAG_subroutine_type, F, llvm::MDNode::get(), getConstantOrNull(), getNonCompileUnitScope(), llvm::DIScope::getRef(), llvm::DIDescriptor::getTag(), llvm::DIDescriptor::isSubprogram(), llvm::LinkageName, and Name.
createNameSpace()
DINameSpace DIBuilder::createNameSpace (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNo)
createNameSpace - This creates new descriptor for a namespace with the specified parent scope.
Parameters
Scope Namespace scope
Name Name of this namespace
File Source file
LineNo Line number
Definition at line 1080 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_namespace, llvm::MDNode::get(), getNonCompileUnitScope(), Name, and llvm::DINameSpace::Verify().
createNullPtrType()
DIBasicType DIBuilder::createNullPtrType ()
Create C++11 nullptr type.
Definition at line 272 of file DIBuilder.cpp.
References createUnspecifiedType().
createObjCIVar()
DIDerivedType DIBuilder::createObjCIVar (StringRef Name, DIFile File, unsigned LineNo, uint64_t SizeInBits, uint64_t AlignInBits, uint64_t OffsetInBits, unsigned Flags, DIType Ty, MDNode * PropertyNode)
createObjCIVar - Create debugging information entry for Objective-C instance variable.
Parameters
Name Member name.
File File where this member is defined.
LineNo Line number.
SizeInBits Member size.
AlignInBits Member alignment.
OffsetInBits Member offset.
Flags Flags to encode member attribute, e.g. private
Ty Parent type.
PropertyNode Property associated with this ivar.
Definition at line 465 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_member, llvm::MDNode::get(), getNonCompileUnitScope(), and Name.
createObjCProperty()
DIObjCProperty DIBuilder::createObjCProperty (StringRef Name, DIFile File, unsigned LineNumber, StringRef GetterName, StringRef SetterName, unsigned PropertyAttributes, DIType Ty)
createObjCProperty - Create debugging information entry for Objective-C property.
Parameters
Name Property name.
File File where this property is defined.
LineNumber Line number.
GetterName Name of the Objective C property getter selector.
SetterName Name of the Objective C property setter selector.
PropertyAttributes Objective C property attributes.
Ty Type.
Definition at line 486 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_APPLE_property, llvm::MDNode::get(), and Name.
createObjectPointerType()
DIType DIBuilder::createObjectPointerType (DIType Ty)
createObjectPointerType - Create a new DIType with the "object pointer" flag set.
Definition at line 770 of file DIBuilder.cpp.
References createTypeWithFlags(), llvm::DIDescriptor::FlagArtificial, llvm::DIDescriptor::FlagObjectPointer, and llvm::DIType::isObjectPointer().
createPieceExpression()
DIExpression DIBuilder::createPieceExpression (unsigned OffsetInBytes, unsigned SizeInBytes)
createPieceExpression - Create a descriptor to describe one part of aggregate variable that is fragmented across multiple Values.
Parameters
OffsetInBytes Offset of the piece in bytes.
SizeInBytes Size of the piece in bytes.
Definition at line 952 of file DIBuilder.cpp.
References createExpression(), and llvm::dwarf::DW_OP_piece.
createPointerType()
DIDerivedType DIBuilder::createPointerType (DIType PointeeTy, uint64_t SizeInBits, uint64_t AlignInBits = 0, StringRef Name = StringRef())
createPointerType - Create debugging information entry for a pointer.
Parameters
PointeeTy Type pointed by this pointer.
SizeInBits Size.
AlignInBits Alignment. (optional)
Name Pointer type name. (optional)
Definition at line 315 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_pointer_type, llvm::MDNode::get(), llvm::DIScope::getRef(), and Name.
createQualifiedType()
DIDerivedType DIBuilder::createQualifiedType (unsigned Tag, DIType FromTy)
createQualifiedType - Create debugging information entry for a qualified type, e.g. 'const int'.
Parameters
Tag Tag identifing type, e.g. dwarf::TAG_volatile_type
FromTy Base Type.
Definition at line 298 of file DIBuilder.cpp.
References llvm::MDNode::get(), and llvm::DIScope::getRef().
createReferenceType()
DIDerivedType DIBuilder::createReferenceType (unsigned Tag, DIType RTy)
createReferenceType - Create debugging information entry for a c++ style reference or rvalue reference type.
Definition at line 350 of file DIBuilder.cpp.
References llvm::MDNode::get().
createReplaceableForwardDecl()
DICompositeType DIBuilder::createReplaceableForwardDecl (unsigned Tag, StringRef Name, DIDescriptor Scope, DIFile F, unsigned Line, unsigned RuntimeLang = 0, uint64_t SizeInBits = 0, uint64_t AlignInBits = 0, StringRef UniqueIdentifier = StringRef())
Create a temporary forward-declared type.
Definition at line 813 of file DIBuilder.cpp.
References llvm::StringRef::empty(), F, llvm::DIDescriptor::FlagFwdDecl, llvm::MDString::get(), getNonCompileUnitScope(), llvm::DIScope::getRef(), llvm::MDNode::getTemporary(), llvm::DIDescriptor::isCompositeType(), Name, and retainType().
createStaticMemberType()
DIDerivedType DIBuilder::createStaticMemberType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNo, DIType Ty, unsigned Flags, llvm::Constant * Val)
createStaticMemberType - Create debugging information entry for a C++ static data member.
Parameters
Scope Member scope.
Name Member name.
File File where this member is declared.
LineNo Line number.
Ty Type of the static member.
Flags Flags to encode member attribute, e.g. private.
Val Const initializer of the member.
Definition at line 444 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_member, llvm::DIDescriptor::FlagStaticMember, llvm::MDNode::get(), getConstantOrNull(), getNonCompileUnitScope(), llvm::DIScope::getRef(), and Name.
createStructType()
DICompositeType DIBuilder::createStructType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNumber, uint64_t SizeInBits, uint64_t AlignInBits, unsigned Flags, DIType DerivedFrom, DIArray Elements, unsigned RunTimeLang = 0, DIType VTableHolder = DIType(), StringRef UniqueIdentifier = StringRef())
createStructType - Create debugging information entry for a struct.
Parameters
Scope Scope in which this struct is defined.
Name Struct name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
Flags Flags to encode member attribute, e.g. private
Elements Struct elements.
RunTimeLang Optional parameter, Objective-C runtime version.
UniqueIdentifier A unique identifier for the struct.
Definition at line 588 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_structure_type, llvm::StringRef::empty(), llvm::MDNode::get(), llvm::MDString::get(), getNonCompileUnitScope(), llvm::DIScope::getRef(), llvm::DIDescriptor::isCompositeType(), Name, and retainType().
createSubroutineType()
DISubroutineType DIBuilder::createSubroutineType (DIFile File, DITypeArray ParameterTypes, unsigned Flags = 0)
createSubroutineType - Create subroutine type.
Parameters
File File in which this subroutine is defined.
ParameterTypes An array of subroutine parameter types. This includes return type at 0th index.
Flags E.g.: LValueReference. These flags are used to emit dwarf attributes.
Definition at line 649 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_subroutine_type, and llvm::MDNode::get().
createTempFunctionFwdDecl()
DISubprogram DIBuilder::createTempFunctionFwdDecl (DIDescriptor Scope, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DICompositeType Ty, bool isLocalToUnit, bool isDefinition, unsigned ScopeLine, unsigned Flags = 0, bool isOptimized = false, Function * Fn = nullptr, MDNode * TParam = nullptr, MDNode * Decl = nullptr)
createTempFunctionFwdDecl - Identical to createFunction, except that the resulting DbgNode is meant to be RAUWed.
Definition at line 1027 of file DIBuilder.cpp.
References createFunctionHelper(), llvm::MDNode::getTemporary(), llvm::LinkageName, and Name.
createTempGlobalVariableFwdDecl()
DIGlobalVariable DIBuilder::createTempGlobalVariableFwdDecl (DIDescriptor Context, StringRef Name, StringRef LinkageName, DIFile File, unsigned LineNo, DITypeRef Ty, bool isLocalToUnit, llvm::Constant * Val, MDNode * Decl = nullptr)
createTempGlobalVariableFwdDecl - Identical to createGlobalVariable except that the resulting DbgNode is temporary and meant to be RAUWed.
Definition at line 904 of file DIBuilder.cpp.
References createGlobalVariableHelper(), F, llvm::MDNode::getTemporary(), llvm::LinkageName, and Name.
createTemplateParameterPack()
DITemplateValueParameter DIBuilder::createTemplateParameterPack (DIDescriptor Scope, StringRef Name, DIType Ty, DIArray Val, MDNode * File = nullptr, unsigned LineNo = 0, unsigned ColumnNo = 0)
Create debugging information for a template parameter pack.
Parameters
Scope Scope in which this type is defined.
Name Value parameter name.
Ty Parameter type.
Val An array of types in the pack.
File File where this type parameter is defined.
LineNo Line number.
ColumnNo Column Number.
Definition at line 544 of file DIBuilder.cpp.
References createTemplateValueParameterHelper(), llvm::dwarf::DW_TAG_GNU_template_parameter_pack, and Name.
createTemplateTemplateParameter()
DITemplateValueParameter DIBuilder::createTemplateTemplateParameter (DIDescriptor Scope, StringRef Name, DIType Ty, StringRef Val, MDNode * File = nullptr, unsigned LineNo = 0, unsigned ColumnNo = 0)
Create debugging information for a template template parameter.
Parameters
Scope Scope in which this type is defined.
Name Value parameter name.
Ty Parameter type.
Val The fully qualified name of the template.
File File where this type parameter is defined.
LineNo Line number.
ColumnNo Column Number.
Definition at line 534 of file DIBuilder.cpp.
References createTemplateValueParameterHelper(), llvm::dwarf::DW_TAG_GNU_template_template_param, llvm::MDString::get(), and Name.
createTemplateTypeParameter()
DITemplateTypeParameter DIBuilder::createTemplateTypeParameter (DIDescriptor Scope, StringRef Name, DIType Ty, MDNode * File = nullptr, unsigned LineNo = 0, unsigned ColumnNo = 0)
createTemplateTypeParameter - Create debugging information for template type parameter.
Parameters
Scope Scope in which this type is defined.
Name Type parameter name.
Ty Parameter type.
File File where this type parameter is defined.
LineNo Line number.
ColumnNo Column Number.
Definition at line 501 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_template_type_parameter, llvm::MDNode::get(), getNonCompileUnitScope(), llvm::DIScope::getRef(), and Name.
createTemplateValueParameter()
DITemplateValueParameter DIBuilder::createTemplateValueParameter (DIDescriptor Scope, StringRef Name, DIType Ty, Constant * Val, MDNode * File = nullptr, unsigned LineNo = 0, unsigned ColumnNo = 0)
createTemplateValueParameter - Create debugging information for template value parameter.
Parameters
Scope Scope in which this type is defined.
Name Value parameter name.
Ty Parameter type.
Val Constant parameter value.
File File where this type parameter is defined.
LineNo Line number.
ColumnNo Column Number.
Definition at line 525 of file DIBuilder.cpp.
References createTemplateValueParameterHelper(), llvm::dwarf::DW_TAG_template_value_parameter, getConstantOrNull(), and Name.
createTypedef()
DIDerivedType DIBuilder::createTypedef (DIType Ty, StringRef Name, DIFile File, unsigned LineNo, DIDescriptor Context)
createTypedef - Create debugging information entry for a typedef.
Parameters
Ty Original type.
Name Typedef name.
File File where this type is defined.
LineNo Line number.
Context The surrounding context for the typedef.
Definition at line 367 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_typedef, llvm::MDNode::get(), getNonCompileUnitScope(), llvm::DIScope::getRef(), and Name.
createUnionType()
DICompositeType DIBuilder::createUnionType (DIDescriptor Scope, StringRef Name, DIFile File, unsigned LineNumber, uint64_t SizeInBits, uint64_t AlignInBits, unsigned Flags, DIArray Elements, unsigned RunTimeLang = 0, StringRef UniqueIdentifier = StringRef())
createUnionType - Create debugging information entry for an union.
Parameters
Scope Scope in which this union is defined.
Name Union name.
File File where this member is defined.
LineNumber Line number.
SizeInBits Member size.
AlignInBits Member alignment.
Flags Flags to encode member attribute, e.g. private
Elements Union elements.
RunTimeLang Optional parameter, Objective-C runtime version.
UniqueIdentifier A unique identifier for the union.
Definition at line 621 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_union_type, llvm::StringRef::empty(), llvm::MDNode::get(), llvm::MDString::get(), getNonCompileUnitScope(), llvm::DIScope::getRef(), Name, and retainType().
createUnspecifiedParameter()
DIBasicType DIBuilder::createUnspecifiedParameter ()
createUnspecifiedParameter - Create unspecified parameter type for a subroutine type.
Definition at line 779 of file DIBuilder.cpp.
createUnspecifiedType()
DIBasicType DIBuilder::createUnspecifiedType (StringRef Name)
Create a DWARF unspecified type.
Definition at line 252 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_unspecified_type, llvm::MDNode::get(), and Name.
Referenced by createNullPtrType().
createVectorType()
DICompositeType DIBuilder::createVectorType (uint64_t Size, uint64_t AlignInBits, DIType Ty, DIArray Subscripts)
createVectorType - Create debugging information entry for a vector type.
Parameters
Size Array size.
AlignInBits Alignment.
Ty Element type.
Subscripts Subscripts.
Definition at line 716 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_array_type, llvm::DIDescriptor::FlagVector, llvm::MDNode::get(), and llvm::DIScope::getRef().
finalize()
void DIBuilder::finalize ()
finalize - Construct any deferred debug info descriptors.
Definition at line 72 of file DIBuilder.cpp.
References llvm::cast(), llvm::DITypedArray< T >::getElement(), llvm::DITypedArray< T >::getNumElements(), getOrCreateArray(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), N, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::DIDescriptor::replaceAllUsesWith().
getOrCreateArray()
DIArray DIBuilder::getOrCreateArray (ArrayRef< Metadata * > Elements)
getOrCreateArray - Get a DIArray, create one if required.
Definition at line 841 of file DIBuilder.cpp.
References llvm::MDNode::get().
Referenced by finalize().
getOrCreateSubrange()
DISubrange DIBuilder::getOrCreateSubrange (int64_t Lo, int64_t Count)
getOrCreateSubrange - Create a descriptor for a value range. This implicitly uniques the values returned.
Definition at line 856 of file DIBuilder.cpp.
References llvm::dwarf::DW_TAG_subrange_type, and llvm::MDNode::get().
getOrCreateTypeArray()
DITypeArray DIBuilder::getOrCreateTypeArray (ArrayRef< Metadata * > Elements)
getOrCreateTypeArray - Get a DITypeArray, create one if required.
Definition at line 845 of file DIBuilder.cpp.
References llvm::cast(), llvm::MDNode::get(), llvm::isa(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::ArrayRef< T >::size().
insertDbgValueIntrinsic() [1/2]
Instruction * DIBuilder::insertDbgValueIntrinsic (llvm::Value * Val, uint64_t Offset, DIVariable VarInfo, DIExpression Expr, BasicBlock * InsertAtEnd)
insertDbgValueIntrinsic - Insert a new llvm.dbg.value intrinsic call.
Parameters
Val llvm::Value of the variable
Offset Offset
VarInfo Variable's debug info descriptor.
Expr A complex location expression.
InsertAtEnd Location for the new intrinsic.
Definition at line 1192 of file DIBuilder.cpp.
References llvm::CallInst::Create(), llvm::Intrinsic::dbg_value, llvm::ConstantInt::get(), llvm::MetadataAsValue::get(), getDbgIntrinsicValueImpl(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt64Ty(), and llvm::DIDescriptor::isVariable().
Referenced by llvm::ConvertDebugDeclareToDebugValue(), llvm::ConvertDebugDeclareToDebugValue(), and llvm::LowerDbgDeclare().
insertDbgValueIntrinsic() [2/2]
Instruction * DIBuilder::insertDbgValueIntrinsic (llvm::Value * Val, uint64_t Offset, DIVariable VarInfo, DIExpression Expr, Instruction * InsertBefore)
insertDbgValueIntrinsic - Insert a new llvm.dbg.value intrinsic call.
Parameters
Val llvm::Value of the variable
Offset Offset
VarInfo Variable's debug info descriptor.
Expr A complex location expression.
InsertBefore Location for the new intrinsic.
Definition at line 1173 of file DIBuilder.cpp.
References llvm::CallInst::Create(), llvm::Intrinsic::dbg_value, llvm::ConstantInt::get(), llvm::MetadataAsValue::get(), getDbgIntrinsicValueImpl(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt64Ty(), and llvm::DIDescriptor::isVariable().
insertDeclare() [1/2]
Instruction * DIBuilder::insertDeclare (llvm::Value * Storage, DIVariable VarInfo, DIExpression Expr, BasicBlock * InsertAtEnd)
insertDeclare - Insert a new llvm.dbg.declare intrinsic call.
Parameters
Storage llvm::Value of the variable
VarInfo Variable's debug info descriptor.
Expr A complex location expression.
InsertAtEnd Location for the new intrinsic.
Definition at line 1151 of file DIBuilder.cpp.
References llvm::CallInst::Create(), llvm::Intrinsic::dbg_declare, llvm::MetadataAsValue::get(), getDbgIntrinsicValueImpl(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getTerminator(), and llvm::DIDescriptor::isVariable().
Referenced by llvm::replaceDbgDeclareForAlloca().
insertDeclare() [2/2]
Instruction * DIBuilder::insertDeclare (llvm::Value * Storage, DIVariable VarInfo, DIExpression Expr, Instruction * InsertBefore)
insertDeclare - Insert a new llvm.dbg.declare intrinsic call.
Parameters
Storage llvm::Value of the variable
VarInfo Variable's debug info descriptor.
Expr A complex location expression.
InsertBefore Location for the new intrinsic.
Definition at line 1135 of file DIBuilder.cpp.
References llvm::CallInst::Create(), llvm::Intrinsic::dbg_declare, llvm::MetadataAsValue::get(), getDbgIntrinsicValueImpl(), llvm::Intrinsic::getDeclaration(), and llvm::DIDescriptor::isVariable().
replaceArrays()
void DIBuilder::replaceArrays (DICompositeType & T, DIArray Elements, DIArray TParems = DIArray())
Replace arrays on a composite type.
If T is resolved, but the arrays aren't – which can happen if T has a self-reference – DIBuilder needs to track the array to resolve cycles.
Definition at line 1226 of file DIBuilder.cpp.
replaceVTableHolder()
void DIBuilder::replaceVTableHolder (DICompositeType & T, DICompositeType VTableHolder)
Replace the vtable holder in the given composite type.
If this creates a self reference, it may orphan some unresolved cycles in the operands of T, so DIBuilder needs to track that.
Definition at line 1211 of file DIBuilder.cpp.
References llvm::dyn_cast_or_null(), and N.
retainType()
void DIBuilder::retainType (DIType T)
retainType - Retain DIType in a module even if it is not referenced through debug info anchors.
Definition at line 777 of file DIBuilder.cpp.
Referenced by createClassType(), createEnumerationType(), createForwardDecl(), createReplaceableForwardDecl(), createStructType(), and createUnionType().
The documentation for this class was generated from the following files:
DIBuilder.h
DIBuilder.cpp