LLVM: llvm::LibCallInfo Class Reference
LLVM API Documentation
llvm::LibCallInfo Class Reference abstract
#include <LibCallSemantics.h>
Public Member Functions
LibCallInfo ()
virtual ~LibCallInfo ()
const LibCallLocationInfo & getLocationInfo (unsigned LocID) const
getLocationInfo - Return information about the specified LocationID.
const LibCallFunctionInfo * getFunctionInfo (const Function *F) const
virtual unsigned getLocationInfo (const LibCallLocationInfo *&Array) const
virtual const LibCallFunctionInfo * getFunctionInfoArray () const =0
Detailed Description
LibCallInfo - Abstract interface to query about library call information. Instances of this class return known information about some set of libcalls.
Definition at line 127 of file LibCallSemantics.h.
Constructor & Destructor Documentation
LibCallInfo()
llvm::LibCallInfo::LibCallInfo () inline
Definition at line 133 of file LibCallSemantics.h.
~LibCallInfo()
LibCallInfo::~LibCallInfo () virtual
Definition at line 27 of file LibCallSemantics.cpp.
References getMap().
Member Function Documentation
getFunctionInfo()
const LibCallFunctionInfo * LibCallInfo::getFunctionInfo (const Function * F) const
getFunctionInfo - Return the LibCallFunctionInfo object corresponding to the specified function if we have it. If not, return null.
Return the LibCallFunctionInfo object corresponding to the specified function if we have it. If not, return null.
If this is the first time we are querying for this info, lazily construct the StringMap to index it.
Definition at line 44 of file LibCallSemantics.cpp.
References F, getFunctionInfoArray(), getMap(), llvm::StringMap< ValueTy, AllocatorTy >::lookup(), and llvm::LibCallFunctionInfo::Name.
getFunctionInfoArray()
virtual const LibCallFunctionInfo * llvm::LibCallInfo::getFunctionInfoArray () const pure virtual
getFunctionInfoArray - Return an array of descriptors that describe the set of libcalls represented by this LibCallInfo object. This array is terminated by an entry with a NULL name.
Referenced by getFunctionInfo().
getLocationInfo() [1/2]
virtual unsigned llvm::LibCallInfo::getLocationInfo (const LibCallLocationInfo *& Array) const inline virtual
getLocationInfo - Return descriptors for the locations referenced by this set of libcalls.
Definition at line 155 of file LibCallSemantics.h.
getLocationInfo() [2/2]
const LibCallLocationInfo & LibCallInfo::getLocationInfo (unsigned LocID) const
getLocationInfo - Return information about the specified LocationID.
Definition at line 31 of file LibCallSemantics.cpp.
References getLocationInfo().
Referenced by getLocationInfo().
The documentation for this class was generated from the following files:
LibCallSemantics.h
LibCallSemantics.cpp