LLVM: llvm::object::Binary Class Reference
LLVM API Documentation
llvm::object::Binary Class Reference
#include <Binary.h>
Public Member Functions
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isIR () const
bool isLittleEndian () const
Protected Types
enum {
ID_Archive , ID_MachOUniversalBinary , ID_IR , ID_StartObjects ,
ID_COFF , ID_ELF32L , ID_ELF32B , ID_ELF64L ,
ID_ELF64B , ID_MachO32L , ID_MachO32B , ID_MachO64L ,
ID_MachO64B , ID_EndObjects
}
Protected Member Functions
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes
MemoryBufferRef Data
Detailed Description
Definition at line 29 of file Binary.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
ID_Archive
ID_MachOUniversalBinary
ID_IR
ID_StartObjects
ID_COFF
ID_ELF32L
ID_ELF32B
ID_ELF64L
ID_ELF64B
ID_MachO32L
ID_MachO32B
ID_MachO64L
ID_MachO64B
ID_EndObjects
Definition at line 41 of file Binary.h.
Constructor & Destructor Documentation
Binary()
Binary::Binary (unsigned int Type, MemoryBufferRef Source) protected
Definition at line 30 of file Binary.cpp.
References Data.
~Binary()
Binary::~Binary () virtual
Definition at line 28 of file Binary.cpp.
Member Function Documentation
getData()
StringRef Binary::getData () const
Definition at line 33 of file Binary.cpp.
References Data.
Referenced by getPtr(), llvm::object::MachOObjectFile::getSectionContents(), llvm::object::MachOObjectFile::getStringTableData(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), and llvm::object::MachOObjectFile::ReadULEB128s().
getELFType()
unsigned int llvm::object::Binary::getELFType (bool isLE, bool is64Bits) inline static protected
Definition at line 63 of file Binary.h.
References ID_ELF32B, ID_ELF32L, ID_ELF64B, and ID_ELF64L.
Referenced by llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >::classof(), and llvm::object::ELFObjectFile< ELFT >::ELFObjectFile().
getFileName()
StringRef Binary::getFileName () const
Definition at line 35 of file Binary.cpp.
References Data.
Referenced by llvm::RuntimeDyldImpl::emitSection(), llvm::object::IRObjectFile::findBitcodeInObject(), and llvm::RuntimeDyldImpl::loadObjectImpl().
getMachOType()
unsigned int llvm::object::Binary::getMachOType (bool isLE, bool is64Bits) inline static protected
Definition at line 70 of file Binary.h.
References ID_MachO32B, ID_MachO32L, ID_MachO64B, and ID_MachO64L.
Referenced by llvm::object::MachOObjectFile::is64Bit(), and llvm::object::MachOObjectFile::MachOObjectFile().
getMemoryBufferRef()
MemoryBufferRef Binary::getMemoryBufferRef () const
Definition at line 37 of file Binary.cpp.
References Data.
Referenced by llvm::object::Archive::Child::getAsBinary().
getType()
unsigned int llvm::object::Binary::getType () const inline
Definition at line 85 of file Binary.h.
Referenced by llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >::classof(), and llvm::object::MachOObjectFile::is64Bit().
isArchive()
bool llvm::object::Binary::isArchive () const inline
Definition at line 96 of file Binary.h.
References ID_Archive.
Referenced by llvm::object::Archive::classof().
isCOFF()
bool llvm::object::Binary::isCOFF () const inline
Definition at line 112 of file Binary.h.
References ID_COFF.
Referenced by llvm::object::COFFObjectFile::classof().
isELF()
bool llvm::object::Binary::isELF () const inline
Definition at line 104 of file Binary.h.
References ID_ELF32L, and ID_ELF64B.
Referenced by llvm::object::ELFObjectFileBase::classof(), llvm::RuntimeDyldELF::isCompatibleFile(), and llvm::RuntimeDyld::loadObject().
isIR()
bool llvm::object::Binary::isIR () const inline
Definition at line 116 of file Binary.h.
References ID_IR.
Referenced by llvm::object::IRObjectFile::classof(), and isSymbolic().
isLittleEndian()
bool llvm::object::Binary::isLittleEndian () const inline
Definition at line 120 of file Binary.h.
References ID_ELF32B, ID_ELF64B, ID_MachO32B, and ID_MachO64B.
Referenced by llvm::object::MachOObjectFile::getPlainRelocationExternal(), getPlainRelocationLength(), getPlainRelocationPCRel(), llvm::object::MachOObjectFile::getPlainRelocationSymbolNum(), getPlainRelocationType(), getStruct(), and llvm::RuntimeDyldImpl::loadObjectImpl().
isMachO()
bool llvm::object::Binary::isMachO () const inline
Definition at line 108 of file Binary.h.
References ID_MachO32L, and ID_MachO64B.
Referenced by llvm::object::MachOObjectFile::classof(), llvm::RuntimeDyldMachO::isCompatibleFile(), and llvm::RuntimeDyld::loadObject().
isMachOUniversalBinary()
bool llvm::object::Binary::isMachOUniversalBinary () const inline
Definition at line 100 of file Binary.h.
References ID_MachOUniversalBinary.
isObject()
bool llvm::object::Binary::isObject () const inline
Definition at line 88 of file Binary.h.
References ID_EndObjects, and ID_StartObjects.
Referenced by llvm::object::ObjectFile::classof(), and isSymbolic().
isSymbolic()
bool llvm::object::Binary::isSymbolic () const inline
Definition at line 92 of file Binary.h.
References isIR(), and isObject().
Referenced by llvm::object::SymbolicFile::classof().
Member Data Documentation
Data
MemoryBufferRef llvm::object::Binary::Data protected
Definition at line 37 of file Binary.h.
Referenced by llvm::object::Archive::Archive(), llvm::object::ObjectFile::base(), Binary(), llvm::object::Archive::child_begin(), llvm::object::COFFObjectFile::COFFObjectFile(), llvm::object::ObjectFile::createObjectFile(), llvm::object::SymbolicFile::createSymbolicFile(), llvm::object::ELFObjectFile< ELFT >::ELFObjectFile(), getData(), getFileName(), getMemoryBufferRef(), llvm::object::COFFObjectFile::getRelocationOffset(), llvm::object::COFFObjectFile::getSectionContents(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::object::COFFObjectFile::section_rel_begin(), and llvm::object::COFFObjectFile::section_rel_end().
The documentation for this class was generated from the following files:
Binary.h
Binary.cpp