LLVM: llvm::Target Class Reference
LLVM API Documentation
llvm::Target Class Reference
#include <TargetRegistry.h>
Public Types
typedef bool(* ArchMatchFnTy) (Triple::ArchType Arch)
typedef MCAsmInfo *(* MCAsmInfoCtorFnTy) (const MCRegisterInfo &MRI, StringRef TT)
typedef MCCodeGenInfo *(* MCCodeGenInfoCtorFnTy) (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
typedef MCInstrInfo *(* MCInstrInfoCtorFnTy) (void)
typedef MCInstrAnalysis *(* MCInstrAnalysisCtorFnTy) (const MCInstrInfo *Info)
typedef MCRegisterInfo *(* MCRegInfoCtorFnTy) (StringRef TT)
typedef MCSubtargetInfo *(* MCSubtargetInfoCtorFnTy) (StringRef TT, StringRef CPU, StringRef Features)
typedef TargetMachine *(* TargetMachineCtorTy) (const Target &T, StringRef TT, StringRef CPU, StringRef Features, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
typedef AsmPrinter *(* AsmPrinterCtorTy) (TargetMachine &TM, MCStreamer &Streamer)
typedef MCAsmBackend *(* MCAsmBackendCtorTy) (const Target &T, const MCRegisterInfo &MRI, StringRef TT, StringRef CPU)
typedef MCTargetAsmParser *(* MCAsmParserCtorTy) (MCSubtargetInfo &STI, MCAsmParser &P, const MCInstrInfo &MII, const MCTargetOptions &Options)
typedef MCDisassembler *(* MCDisassemblerCtorTy) (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
typedef MCInstPrinter *(* MCInstPrinterCtorTy) (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
typedef MCCodeEmitter *(* MCCodeEmitterCtorTy) (const MCInstrInfo &II, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI, MCContext &Ctx)
typedef MCStreamer *(* MCObjectStreamerCtorTy) (const Target &T, StringRef TT, MCContext &Ctx, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter, const MCSubtargetInfo &STI, bool RelaxAll)
typedef MCStreamer *(* AsmStreamerCtorTy) (MCContext &Ctx, formatted_raw_ostream &OS, bool isVerboseAsm, bool useDwarfDirectory, MCInstPrinter *InstPrint, MCCodeEmitter *CE, MCAsmBackend *TAB, bool ShowInst)
typedef MCStreamer *(* NullStreamerCtorTy) (MCContext &Ctx)
typedef MCRelocationInfo *(* MCRelocationInfoCtorTy) (StringRef TT, MCContext &Ctx)
typedef MCSymbolizer *(* MCSymbolizerCtorTy) (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, MCRelocationInfo *RelInfo)
Public Member Functions
Target ()
Target Information
const Target * getNext () const
const char * getName () const
getName - Get the target name.
const char * getShortDescription () const
getShortDescription - Get a short description of the target.
Feature Predicates
bool hasJIT () const
hasJIT - Check if this targets supports the just-in-time compilation.
bool hasTargetMachine () const
hasTargetMachine - Check if this target supports code generation.
bool hasMCAsmBackend () const
hasMCAsmBackend - Check if this target supports .o generation.
Feature Constructors
MCAsmInfo * createMCAsmInfo (const MCRegisterInfo &MRI, StringRef Triple) const
MCCodeGenInfo * createMCCodeGenInfo (StringRef Triple, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) const
MCInstrInfo * createMCInstrInfo () const
MCInstrAnalysis * createMCInstrAnalysis (const MCInstrInfo *Info) const
MCRegisterInfo * createMCRegInfo (StringRef Triple) const
MCSubtargetInfo * createMCSubtargetInfo (StringRef Triple, StringRef CPU, StringRef Features) const
TargetMachine * createTargetMachine (StringRef Triple, StringRef CPU, StringRef Features, const TargetOptions &Options, Reloc::Model RM=Reloc::Default, CodeModel::Model CM=CodeModel::Default, CodeGenOpt::Level OL=CodeGenOpt::Default) const
MCAsmBackend * createMCAsmBackend (const MCRegisterInfo &MRI, StringRef Triple, StringRef CPU) const
MCTargetAsmParser * createMCAsmParser (MCSubtargetInfo &STI, MCAsmParser &Parser, const MCInstrInfo &MII, const MCTargetOptions &Options) const
AsmPrinter * createAsmPrinter (TargetMachine &TM, MCStreamer &Streamer) const
MCDisassembler * createMCDisassembler (const MCSubtargetInfo &STI, MCContext &Ctx) const
MCInstPrinter * createMCInstPrinter (unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI) const
MCCodeEmitter * createMCCodeEmitter (const MCInstrInfo &II, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI, MCContext &Ctx) const
createMCCodeEmitter - Create a target specific code emitter.
MCStreamer * createMCObjectStreamer (StringRef TT, MCContext &Ctx, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter, const MCSubtargetInfo &STI, bool RelaxAll) const
MCStreamer * createAsmStreamer (MCContext &Ctx, formatted_raw_ostream &OS, bool isVerboseAsm, bool useDwarfDirectory, MCInstPrinter *InstPrint, MCCodeEmitter *CE, MCAsmBackend *TAB, bool ShowInst) const
createAsmStreamer - Create a target specific MCStreamer.
MCStreamer * createNullStreamer (MCContext &Ctx) const
MCRelocationInfo * createMCRelocationInfo (StringRef TT, MCContext &Ctx) const
MCSymbolizer * createMCSymbolizer (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, MCRelocationInfo *RelInfo) const
Friends
struct TargetRegistry
Detailed Description
Target - Wrapper for Target specific information.
For registration purposes, this is a POD type so that targets can be registered without the use of static constructors.
Targets should implement a single global instance of this class (which will be zero initialized), and pass that instance to the TargetRegistry as part of their initialization.
Definition at line 76 of file TargetRegistry.h.
Member Typedef Documentation
ArchMatchFnTy
typedef bool(* llvm::Target::ArchMatchFnTy) (Triple::ArchType Arch)
Definition at line 80 of file TargetRegistry.h.
AsmPrinterCtorTy
typedef AsmPrinter *(* llvm::Target::AsmPrinterCtorTy) (TargetMachine &TM, MCStreamer &Streamer)
Definition at line 102 of file TargetRegistry.h.
AsmStreamerCtorTy
typedef MCStreamer *(* llvm::Target::AsmStreamerCtorTy) (MCContext &Ctx, formatted_raw_ostream &OS, bool isVerboseAsm, bool useDwarfDirectory, MCInstPrinter *InstPrint, MCCodeEmitter *CE, MCAsmBackend *TAB, bool ShowInst)
Definition at line 130 of file TargetRegistry.h.
MCAsmBackendCtorTy
typedef MCAsmBackend *(* llvm::Target::MCAsmBackendCtorTy) (const Target &T, const MCRegisterInfo &MRI, StringRef TT, StringRef CPU)
Definition at line 104 of file TargetRegistry.h.
MCAsmInfoCtorFnTy
typedef MCAsmInfo *(* llvm::Target::MCAsmInfoCtorFnTy) (const MCRegisterInfo &MRI, StringRef TT)
Definition at line 82 of file TargetRegistry.h.
MCAsmParserCtorTy
typedef MCTargetAsmParser *(* llvm::Target::MCAsmParserCtorTy) (MCSubtargetInfo &STI, MCAsmParser &P, const MCInstrInfo &MII, const MCTargetOptions &Options)
Definition at line 108 of file TargetRegistry.h.
MCCodeEmitterCtorTy
typedef MCCodeEmitter *(* llvm::Target::MCCodeEmitterCtorTy) (const MCInstrInfo &II, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI, MCContext &Ctx)
Definition at line 122 of file TargetRegistry.h.
MCCodeGenInfoCtorFnTy
typedef MCCodeGenInfo *(* llvm::Target::MCCodeGenInfoCtorFnTy) (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
Definition at line 84 of file TargetRegistry.h.
MCDisassemblerCtorTy
typedef MCDisassembler *(* llvm::Target::MCDisassemblerCtorTy) (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
Definition at line 113 of file TargetRegistry.h.
MCInstPrinterCtorTy
typedef MCInstPrinter *(* llvm::Target::MCInstPrinterCtorTy) (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
Definition at line 116 of file TargetRegistry.h.
MCInstrAnalysisCtorFnTy
typedef MCInstrAnalysis *(* llvm::Target::MCInstrAnalysisCtorFnTy) (const MCInstrInfo *Info)
Definition at line 89 of file TargetRegistry.h.
MCInstrInfoCtorFnTy
typedef MCInstrInfo *(* llvm::Target::MCInstrInfoCtorFnTy) (void)
Definition at line 88 of file TargetRegistry.h.
MCObjectStreamerCtorTy
typedef MCStreamer *(* llvm::Target::MCObjectStreamerCtorTy) (const Target &T, StringRef TT, MCContext &Ctx, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter, const MCSubtargetInfo &STI, bool RelaxAll)
Definition at line 126 of file TargetRegistry.h.
MCRegInfoCtorFnTy
typedef MCRegisterInfo *(* llvm::Target::MCRegInfoCtorFnTy) (StringRef TT)
Definition at line 90 of file TargetRegistry.h.
MCRelocationInfoCtorTy
typedef MCRelocationInfo *(* llvm::Target::MCRelocationInfoCtorTy) (StringRef TT, MCContext &Ctx)
Definition at line 139 of file TargetRegistry.h.
MCSubtargetInfoCtorFnTy
typedef MCSubtargetInfo *(* llvm::Target::MCSubtargetInfoCtorFnTy) (StringRef TT, StringRef CPU, StringRef Features)
Definition at line 91 of file TargetRegistry.h.
MCSymbolizerCtorTy
typedef MCSymbolizer *(* llvm::Target::MCSymbolizerCtorTy) (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, MCRelocationInfo *RelInfo)
Definition at line 141 of file TargetRegistry.h.
NullStreamerCtorTy
typedef MCStreamer *(* llvm::Target::NullStreamerCtorTy) (MCContext &Ctx)
Definition at line 138 of file TargetRegistry.h.
TargetMachineCtorTy
typedef TargetMachine *(* llvm::Target::TargetMachineCtorTy) (const Target &T, StringRef TT, StringRef CPU, StringRef Features, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
Definition at line 94 of file TargetRegistry.h.
Constructor & Destructor Documentation
Target()
llvm::Target::Target () inline
Definition at line 238 of file TargetRegistry.h.
Referenced by getNext().
Member Function Documentation
createAsmPrinter()
AsmPrinter * llvm::Target::createAsmPrinter (TargetMachine & TM, MCStreamer & Streamer) const inline
createAsmPrinter - Create a target specific assembly printer pass. This takes ownership of the MCStreamer object.
Definition at line 379 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
createAsmStreamer()
MCStreamer * llvm::Target::createAsmStreamer (MCContext & Ctx, formatted_raw_ostream & OS, bool isVerboseAsm, bool useDwarfDirectory, MCInstPrinter * InstPrint, MCCodeEmitter * CE, MCAsmBackend * TAB, bool ShowInst) const inline
createAsmStreamer - Create a target specific MCStreamer.
Definition at line 433 of file TargetRegistry.h.
References llvm::createAsmStreamer().
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile().
createMCAsmBackend()
MCAsmBackend * llvm::Target::createMCAsmBackend (const MCRegisterInfo & MRI, StringRef Triple, StringRef CPU) const inline
createMCAsmBackend - Create a target specific assembly parser.
Parameters
Triple The target triple string.
Definition at line 356 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
createMCAsmInfo()
MCAsmInfo * llvm::Target::createMCAsmInfo (const MCRegisterInfo & MRI, StringRef Triple) const inline
createMCAsmInfo - Create a MCAsmInfo implementation for the specified target triple.
Parameters
Triple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
Definition at line 278 of file TargetRegistry.h.
Referenced by LLVMCreateDisasmCPUFeatures().
createMCAsmParser()
MCTargetAsmParser * llvm::Target::createMCAsmParser (MCSubtargetInfo & STI, MCAsmParser & Parser, const MCInstrInfo & MII, const MCTargetOptions & Options) const inline
createMCAsmParser - Create a target specific assembly parser.
Parameters
Parser The target independent parser implementation to use for parsing and lexing.
Definition at line 367 of file TargetRegistry.h.
createMCCodeEmitter()
MCCodeEmitter * llvm::Target::createMCCodeEmitter (const MCInstrInfo & II, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI, MCContext & Ctx) const inline
createMCCodeEmitter - Create a target specific code emitter.
Definition at line 404 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
createMCCodeGenInfo()
MCCodeGenInfo * llvm::Target::createMCCodeGenInfo (StringRef Triple, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) const inline
createMCCodeGenInfo - Create a MCCodeGenInfo implementation.
Definition at line 287 of file TargetRegistry.h.
createMCDisassembler()
MCDisassembler * llvm::Target::createMCDisassembler (const MCSubtargetInfo & STI, MCContext & Ctx) const inline
Definition at line 385 of file TargetRegistry.h.
Referenced by LLVMCreateDisasmCPUFeatures().
createMCInstPrinter()
MCInstPrinter * llvm::Target::createMCInstPrinter (unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) const inline
Definition at line 392 of file TargetRegistry.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), LLVMCreateDisasmCPUFeatures(), and LLVMSetDisasmOptions().
createMCInstrAnalysis()
MCInstrAnalysis * llvm::Target::createMCInstrAnalysis (const MCInstrInfo * Info) const inline
createMCInstrAnalysis - Create a MCInstrAnalysis implementation.
Definition at line 305 of file TargetRegistry.h.
createMCInstrInfo()
MCInstrInfo * llvm::Target::createMCInstrInfo () const inline
createMCInstrInfo - Create a MCInstrInfo implementation.
Definition at line 297 of file TargetRegistry.h.
Referenced by LLVMCreateDisasmCPUFeatures().
createMCObjectStreamer()
MCStreamer * llvm::Target::createMCObjectStreamer (StringRef TT, MCContext & Ctx, MCAsmBackend & TAB, raw_ostream & _OS, MCCodeEmitter * _Emitter, const MCSubtargetInfo & STI, bool RelaxAll) const inline
createMCObjectStreamer - Create a target specific MCStreamer.
Parameters
TT The target triple.
Ctx The target context.
TAB The target assembler backend object. Takes ownership.
_OS The stream object.
_Emitter The target independent assembler object.Takes ownership.
RelaxAll Relax all fixups?
Definition at line 421 of file TargetRegistry.h.
References RelaxAll().
createMCRegInfo()
MCRegisterInfo * llvm::Target::createMCRegInfo (StringRef Triple) const inline
createMCRegInfo - Create a MCRegisterInfo implementation.
Definition at line 313 of file TargetRegistry.h.
Referenced by LLVMCreateDisasmCPUFeatures().
createMCRelocationInfo()
MCRelocationInfo * llvm::Target::createMCRelocationInfo (StringRef TT, MCContext & Ctx) const inline
createMCRelocationInfo - Create a target specific MCRelocationInfo.
Parameters
TT The target triple.
Ctx The target context.
Definition at line 459 of file TargetRegistry.h.
References llvm::createMCRelocationInfo().
Referenced by LLVMCreateDisasmCPUFeatures().
createMCSubtargetInfo()
MCSubtargetInfo * llvm::Target::createMCSubtargetInfo (StringRef Triple, StringRef CPU, StringRef Features) const inline
createMCSubtargetInfo - Create a MCSubtargetInfo implementation.
Parameters
Triple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
CPU This specifies the name of the target CPU.
Features This specifies the string representation of the additional target features.
Definition at line 328 of file TargetRegistry.h.
References Features.
Referenced by LLVMCreateDisasmCPUFeatures().
createMCSymbolizer()
MCSymbolizer * llvm::Target::createMCSymbolizer (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void * DisInfo, MCContext * Ctx, MCRelocationInfo * RelInfo) const inline
createMCSymbolizer - Create a target specific MCSymbolizer.
Parameters
TT The target triple.
GetOpInfo The function to get the symbolic information for operands.
SymbolLookUp The function to lookup a symbol name.
DisInfo The pointer to the block of symbolic information for above call back.
Ctx The target context.
RelInfo The relocation information for this target. Takes ownership.
Definition at line 476 of file TargetRegistry.h.
References llvm::createMCSymbolizer().
Referenced by LLVMCreateDisasmCPUFeatures().
createNullStreamer()
MCStreamer * llvm::Target::createNullStreamer (MCContext & Ctx) const inline
Definition at line 448 of file TargetRegistry.h.
References llvm::createNullStreamer().
createTargetMachine()
TargetMachine * llvm::Target::createTargetMachine (StringRef Triple, StringRef CPU, StringRef Features, const TargetOptions & Options, Reloc::Model RM = Reloc::Default, CodeModel::Model CM = CodeModel::Default, CodeGenOpt::Level OL = CodeGenOpt::Default) const inline
createTargetMachine - Create a target specific machine implementation for the specified Triple.
Parameters
Triple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
Definition at line 342 of file TargetRegistry.h.
References llvm::CodeGenOpt::Default, llvm::CodeModel::Default, llvm::Reloc::Default, and Features.
Referenced by llvm::EngineBuilder::selectTarget().
getName()
const char * llvm::Target::getName () const inline
getName - Get the target name.
Definition at line 249 of file TargetRegistry.h.
Referenced by llvm::MachObjectWriter::getSymbolAddress().
getNext()
const Target * llvm::Target::getNext () const inline
Definition at line 246 of file TargetRegistry.h.
References Target().
getShortDescription()
const char * llvm::Target::getShortDescription () const inline
getShortDescription - Get a short description of the target.
Definition at line 252 of file TargetRegistry.h.
hasJIT()
bool llvm::Target::hasJIT () const inline
hasJIT - Check if this targets supports the just-in-time compilation.
Definition at line 259 of file TargetRegistry.h.
hasMCAsmBackend()
bool llvm::Target::hasMCAsmBackend () const inline
hasMCAsmBackend - Check if this target supports .o generation.
Definition at line 265 of file TargetRegistry.h.
hasTargetMachine()
bool llvm::Target::hasTargetMachine () const inline
hasTargetMachine - Check if this target supports code generation.
Definition at line 262 of file TargetRegistry.h.
Friends And Related Symbol Documentation
TargetRegistry
friend struct TargetRegistry friend
Definition at line 78 of file TargetRegistry.h.
References TargetRegistry.
Referenced by TargetRegistry.
The documentation for this class was generated from the following file:
TargetRegistry.h