LLVM: llvm::CallGraphSCCPass Class Reference
LLVM API Documentation
llvm::CallGraphSCCPass Class Reference abstract
#include <CallGraphSCCPass.h>
Public Member Functions
CallGraphSCCPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
virtual bool doInitialization (CallGraph &CG)
virtual bool runOnSCC (CallGraphSCC &SCC)=0
virtual bool doFinalization (CallGraph &CG)
void assignPassManager (PMStack &PMS, PassManagerType PMT) override
Assign pass manager to manager this pass.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
void getAnalysisUsage (AnalysisUsage &Info) const override
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 34 of file CallGraphSCCPass.h.
Constructor & Destructor Documentation
CallGraphSCCPass()
llvm::CallGraphSCCPass::CallGraphSCCPass (char & pid) inline explicit
Definition at line 36 of file CallGraphSCCPass.h.
References llvm::PT_CallGraphSCC.
Referenced by llvm::InlineCostAnalysis::InlineCostAnalysis(), llvm::Inliner::Inliner(), and llvm::Inliner::Inliner().
Member Function Documentation
assignPassManager()
void CallGraphSCCPass::assignPassManager (PMStack & PMS, PassManagerType PMT) override virtual
Assign pass manager to manager this pass.
Assign pass manager to manage this pass.
Reimplemented from llvm::Pass.
Definition at line 545 of file CallGraphSCCPass.cpp.
References llvm::PMTopLevelManager::addIndirectPassManager(), llvm::PMStack::empty(), llvm::PMDataManager::getPassManagerType(), llvm::PMDataManager::getTopLevelManager(), P, llvm::PMT_CallGraphPassManager, llvm::PMStack::pop(), llvm::PMStack::push(), llvm::PMTopLevelManager::schedulePass(), and llvm::PMStack::top().
createPrinterPass()
Pass * CallGraphSCCPass::createPrinterPass (raw_ostream & O, const std::string & Banner) const override virtual
createPrinterPass - Get a pass that prints the Module corresponding to a CallGraph.
Implements llvm::Pass.
Definition at line 626 of file CallGraphSCCPass.cpp.
doFinalization() [1/2]
virtual bool llvm::CallGraphSCCPass::doFinalization (CallGraph & CG) inline virtual
doFinalization - This method is called after the SCC's of the program has been processed, allowing the pass to do final cleanup as necessary.
Reimplemented in llvm::Inliner.
Definition at line 64 of file CallGraphSCCPass.h.
doFinalization() [2/2]
virtual bool llvm::Pass::doFinalization (Module &) inline virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::Pass.
Reimplemented in llvm::Inliner.
Definition at line 116 of file Pass.h.
doInitialization() [1/2]
virtual bool llvm::CallGraphSCCPass::doInitialization (CallGraph & CG) inline virtual
doInitialization - This method is called before the SCC's of the program has been processed, allowing the pass to do initialization as necessary.
Definition at line 48 of file CallGraphSCCPass.h.
doInitialization() [2/2]
virtual bool llvm::Pass::doInitialization (Module &) inline virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 111 of file Pass.h.
getAnalysisUsage()
void CallGraphSCCPass::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - For this class, we declare that we require and preserve the call graph. If the derived class implements this method, it should always explicitly call the implementation here.
Reimplemented from llvm::Pass.
Reimplemented in llvm::InlineCostAnalysis, and llvm::Inliner.
Definition at line 584 of file CallGraphSCCPass.cpp.
References llvm::AnalysisUsage::addPreserved(), and llvm::AnalysisUsage::addRequired().
Referenced by llvm::InlineCostAnalysis::getAnalysisUsage(), and llvm::Inliner::getAnalysisUsage().
getPotentialPassManagerType()
PassManagerType llvm::CallGraphSCCPass::getPotentialPassManagerType () const inline override virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented from llvm::Pass.
Definition at line 72 of file CallGraphSCCPass.h.
References llvm::PMT_CallGraphPassManager.
runOnSCC()
virtual bool llvm::CallGraphSCCPass::runOnSCC (CallGraphSCC & SCC) pure virtual
runOnSCC - This method should be implemented by the subclass to perform whatever action is necessary for the specified SCC. Note that non-recursive (or only self-recursive) functions will have an SCC size of 1, where recursive portions of the call graph will have SCC size > 1.
SCC passes that add or delete functions to the SCC are required to update the SCC list, otherwise stale pointers may be dereferenced.
Implemented in llvm::InlineCostAnalysis, and llvm::Inliner.
The documentation for this class was generated from the following files:
CallGraphSCCPass.h
CallGraphSCCPass.cpp