LLVM: llvm::coverage::CoverageMappingIterator Class Reference
LLVM API Documentation
llvm::coverage::CoverageMappingIterator Class Reference
A file format agnostic iterator over coverage mapping data.
#include <CoverageMappingReader.h>
Public Member Functions
CoverageMappingIterator ()
CoverageMappingIterator (ObjectFileCoverageMappingReader *Reader)
CoverageMappingIterator & operator++ ()
bool operator== (const CoverageMappingIterator &RHS)
bool operator!= (const CoverageMappingIterator &RHS)
CoverageMappingRecord & operator* ()
CoverageMappingRecord * operator-> ()
Detailed Description
A file format agnostic iterator over coverage mapping data.
Definition at line 42 of file CoverageMappingReader.h.
Constructor & Destructor Documentation
CoverageMappingIterator() [1/2]
llvm::coverage::CoverageMappingIterator::CoverageMappingIterator () inline
Definition at line 50 of file CoverageMappingReader.h.
Referenced by operator!=(), operator++(), and operator==().
CoverageMappingIterator() [2/2]
llvm::coverage::CoverageMappingIterator::CoverageMappingIterator (ObjectFileCoverageMappingReader * Reader) inline
Definition at line 51 of file CoverageMappingReader.h.
Member Function Documentation
operator!=()
bool llvm::coverage::CoverageMappingIterator::operator!= (const CoverageMappingIterator & RHS) inline
Definition at line 63 of file CoverageMappingReader.h.
References CoverageMappingIterator().
operator*()
CoverageMappingRecord & llvm::coverage::CoverageMappingIterator::operator* () inline
Definition at line 66 of file CoverageMappingReader.h.
operator++()
CoverageMappingIterator & llvm::coverage::CoverageMappingIterator::operator++ () inline
Definition at line 56 of file CoverageMappingReader.h.
References CoverageMappingIterator().
operator->()
CoverageMappingRecord * llvm::coverage::CoverageMappingIterator::operator-> () inline
Definition at line 67 of file CoverageMappingReader.h.
operator==()
bool llvm::coverage::CoverageMappingIterator::operator== (const CoverageMappingIterator & RHS) inline
Definition at line 60 of file CoverageMappingReader.h.
References CoverageMappingIterator().
The documentation for this class was generated from the following files:
CoverageMappingReader.h
CoverageMappingReader.cpp