LLVM: llvm::DIEValue Class Reference
LLVM API Documentation
llvm::DIEValue Class Reference abstract
#include <DIE.h>
Public Types
enum Type {
isInteger , isString , isExpr , isLabel ,
isDelta , isEntry , isTypeSignature , isBlock ,
isLoc , isLocList
}
Public Member Functions
Type getType () const
virtual void EmitValue (AsmPrinter *AP, dwarf::Form Form) const =0
virtual unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const =0
virtual void print (raw_ostream &O) const =0
void dump () const
Protected Member Functions
DIEValue (Type T)
virtual ~DIEValue ()
Protected Attributes
Type Ty
Detailed Description
DIEValue - A debug information entry value. Some of these roughly correlate to DWARF attribute classes.
Definition at line 202 of file DIE.h.
Member Enumeration Documentation
Type
enum llvm::DIEValue::Type
Enumerator
isInteger
isString
isExpr
isLabel
isDelta
isEntry
isTypeSignature
isBlock
isLoc
isLocList
Definition at line 206 of file DIE.h.
Constructor & Destructor Documentation
DIEValue()
llvm::DIEValue::DIEValue (Type T) inline explicit protected
Definition at line 224 of file DIE.h.
References T, and Ty.
Referenced by llvm::DIEBlock::classof(), llvm::DIEDelta::classof(), llvm::DIEEntry::classof(), llvm::DIEExpr::classof(), llvm::DIEInteger::classof(), llvm::DIELabel::classof(), llvm::DIELoc::classof(), llvm::DIELocList::classof(), llvm::DIEString::classof(), llvm::DIETypeSignature::classof(), llvm::DIEBlock::DIEBlock(), llvm::DIEDelta::DIEDelta(), llvm::DIEEntry::DIEEntry(), llvm::DIEExpr::DIEExpr(), llvm::DIEInteger::DIEInteger(), llvm::DIELabel::DIELabel(), llvm::DIELoc::DIELoc(), llvm::DIELocList::DIELocList(), llvm::DIEString::DIEString(), and llvm::DIETypeSignature::DIETypeSignature().
~DIEValue()
virtual llvm::DIEValue::~DIEValue () inline protected virtual
Definition at line 225 of file DIE.h.
Member Function Documentation
dump()
void DIEValue::dump () const
Definition at line 196 of file DIE.cpp.
References llvm::dbgs(), and print().
EmitValue()
virtual void llvm::DIEValue::EmitValue (AsmPrinter * AP, dwarf::Form Form) const pure virtual
EmitValue - Emit value via the Dwarf writer.
Implemented in llvm::DIEBlock, llvm::DIEDelta, llvm::DIEEntry, llvm::DIEExpr, llvm::DIEInteger, llvm::DIELabel, llvm::DIELoc, llvm::DIELocList, llvm::DIEString, and llvm::DIETypeSignature.
getType()
Type llvm::DIEValue::getType () const inline
Definition at line 229 of file DIE.h.
References Ty.
Referenced by llvm::DIEBlock::classof(), llvm::DIEDelta::classof(), llvm::DIEEntry::classof(), llvm::DIEExpr::classof(), llvm::DIELabel::classof(), llvm::DIELoc::classof(), llvm::DIELocList::classof(), llvm::DIEString::classof(), and llvm::DIETypeSignature::classof().
print()
virtual void llvm::DIEValue::print (raw_ostream & O) const pure virtual
Implemented in llvm::DIEBlock, llvm::DIEDelta, llvm::DIEEntry, llvm::DIEExpr, llvm::DIEInteger, llvm::DIELabel, llvm::DIELoc, llvm::DIELocList, llvm::DIEString, and llvm::DIETypeSignature.
Referenced by dump().
SizeOf()
virtual unsigned llvm::DIEValue::SizeOf (AsmPrinter * AP, dwarf::Form Form) const pure virtual
SizeOf - Return the size of a value in bytes.
Implemented in llvm::DIEBlock, llvm::DIEDelta, llvm::DIEEntry, llvm::DIEExpr, llvm::DIEInteger, llvm::DIELabel, llvm::DIELoc, llvm::DIELocList, llvm::DIEString, and llvm::DIETypeSignature.
Member Data Documentation
Ty
Type llvm::DIEValue::Ty protected
Ty - Type of data stored in the value.
Definition at line 222 of file DIE.h.
Referenced by DIEValue(), and getType().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp