LLVM: llvm::ARMSubtarget Class Reference
LLVM API Documentation
llvm::ARMSubtarget Class Reference
#include <ARMSubtarget.h>
Public Member Functions
ARMSubtarget (const std::string &TT, const std::string &CPU, const std::string &FS, const ARMBaseTargetMachine &TM, bool IsLittle)
unsigned getMaxInlineSizeThreshold () const
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ARMSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
const DataLayout * getDataLayout () const override
const ARMSelectionDAGInfo * getSelectionDAGInfo () const override
const ARMBaseInstrInfo * getInstrInfo () const override
const ARMTargetLowering * getTargetLowering () const override
const ARMFrameLowering * getFrameLowering () const override
const ARMBaseRegisterInfo * getRegisterInfo () const override
void computeIssueWidth ()
bool hasV4TOps () const
bool hasV5TOps () const
bool hasV5TEOps () const
bool hasV6Ops () const
bool hasV6MOps () const
bool hasV6T2Ops () const
bool hasV7Ops () const
bool hasV8Ops () const
bool isCortexA5 () const
bool isCortexA7 () const
bool isCortexA8 () const
bool isCortexA9 () const
bool isCortexA15 () const
bool isSwift () const
bool isCortexM3 () const
bool isLikeA9 () const
bool isCortexR5 () const
bool isKrait () const
bool hasARMOps () const
bool hasVFP2 () const
bool hasVFP3 () const
bool hasVFP4 () const
bool hasFPARMv8 () const
bool hasNEON () const
bool hasCrypto () const
bool hasCRC () const
bool hasVirtualization () const
bool useNEONForSinglePrecisionFP () const
bool hasDivide () const
bool hasDivideInARMMode () const
bool hasT2ExtractPack () const
bool hasDataBarrier () const
bool hasAnyDataBarrier () const
bool useMulOps () const
bool useFPVMLx () const
bool hasVMLxForwarding () const
bool isFPBrccSlow () const
bool isFPOnlySP () const
bool hasPerfMon () const
bool hasTrustZone () const
bool hasZeroCycleZeroing () const
bool prefers32BitThumb () const
bool avoidCPSRPartialUpdate () const
bool avoidMOVsShifterOperand () const
bool hasRAS () const
bool hasMPExtension () const
bool hasThumb2DSP () const
bool useNaClTrap () const
bool hasFP16 () const
bool hasD16 () const
const Triple & getTargetTriple () const
bool isTargetDarwin () const
bool isTargetIOS () const
bool isTargetLinux () const
bool isTargetNaCl () const
bool isTargetNetBSD () const
bool isTargetWindows () const
bool isTargetCOFF () const
bool isTargetELF () const
bool isTargetMachO () const
bool isTargetAEABI () const
bool isTargetEHABICompatible () const
bool isTargetHardFloat () const
bool isTargetAndroid () const
bool isAPCS_ABI () const
bool isAAPCS_ABI () const
bool isThumb () const
bool isThumb1Only () const
bool isThumb2 () const
bool hasThumb2 () const
bool isMClass () const
bool isRClass () const
bool isAClass () const
bool isV6M () const
bool isR9Reserved () const
bool useMovt (const MachineFunction &MF) const
bool supportsTailCall () const
bool allowsUnalignedMem () const
bool restrictIT () const
const std::string & getCPUString () const
bool isLittle () const
unsigned getMispredictionPenalty () const
bool hasSinCos () const
bool enablePostMachineScheduler () const override
True for some subtargets at > -O0.
bool enableAtomicExpand () const override
const InstrItineraryData * getInstrItineraryData () const override
unsigned getStackAlignment () const
bool GVIsIndirectSymbol (const GlobalValue *GV, Reloc::Model RelocM) const
GVIsIndirectSymbol - true if the GV will be accessed via an indirect symbol.
Protected Types
enum ARMProcFamilyEnum {
Others , CortexA5 , CortexA7 , CortexA8 ,
CortexA9 , CortexA12 , CortexA15 , CortexA17 ,
CortexR5 , Swift , CortexA53 , CortexA57 ,
Krait
}
enum ARMProcClassEnum { None , AClass , RClass , MClass }
Protected Attributes
ARMProcFamilyEnum ARMProcFamily
ARMProcFamily - ARM processor family: Cortex-A8, Cortex-A9, and others.
ARMProcClassEnum ARMProcClass
ARMProcClass - ARM processor class: None, AClass, RClass or MClass.
bool HasV4TOps
bool HasV5TOps
bool HasV5TEOps
bool HasV6Ops
bool HasV6MOps
bool HasV6T2Ops
bool HasV7Ops
bool HasV8Ops
bool HasVFPv2
bool HasVFPv3
bool HasVFPv4
bool HasFPARMv8
bool HasNEON
bool UseNEONForSinglePrecisionFP
bool UseMulOps
bool SlowFPVMLx
bool HasVMLxForwarding
bool SlowFPBrcc
SlowFPBrcc - True if floating point compare + branch is slow.
bool InThumbMode
InThumbMode - True if compiling for Thumb, false for ARM.
bool HasThumb2
HasThumb2 - True if Thumb2 instructions are supported.
bool NoARM
NoARM - True if subtarget does not support ARM mode execution.
bool IsR9Reserved
IsR9Reserved - True if R9 is a not available as general purpose register.
bool UseMovt
bool SupportsTailCall
bool HasFP16
bool HasD16
bool HasHardwareDivide
HasHardwareDivide - True if subtarget supports [su]div.
bool HasHardwareDivideInARM
HasHardwareDivideInARM - True if subtarget supports [su]div in ARM mode.
bool HasT2ExtractPack
bool HasDataBarrier
bool Pref32BitThumb
bool AvoidCPSRPartialUpdate
bool AvoidMOVsShifterOperand
bool HasRAS
bool HasMPExtension
bool HasVirtualization
bool FPOnlySP
bool HasPerfMon
bool HasTrustZone
HasTrustZone - if true, processor supports TrustZone security extensions.
bool HasCrypto
HasCrypto - if true, processor supports Cryptography extensions.
bool HasCRC
HasCRC - if true, processor supports CRC instructions.
bool HasZeroCycleZeroing
bool AllowsUnalignedMem
bool RestrictIT
bool Thumb2DSP
bool UseNaClTrap
NaCl TRAP instruction is generated instead of the regular TRAP.
bool UnsafeFPMath
Target machine allowed unsafe FP math (such as use of NEON fp)
unsigned stackAlignment
std::string CPUString
CPUString - String name of used CPU.
bool IsLittle
IsLittle - The target is Little Endian.
Triple TargetTriple
TargetTriple - What processor and OS we're targeting.
MCSchedModel SchedModel
SchedModel - Processor specific instruction costs.
InstrItineraryData InstrItins
Selected instruction itineraries (one entry per itinerary class.)
const TargetOptions & Options
Options passed via command line that could influence the target.
const ARMBaseTargetMachine & TM
Detailed Description
Definition at line 42 of file ARMSubtarget.h.
Member Enumeration Documentation
ARMProcClassEnum
enum llvm::ARMSubtarget::ARMProcClassEnum protected
Enumerator
None
AClass
RClass
MClass
Definition at line 48 of file ARMSubtarget.h.
ARMProcFamilyEnum
enum llvm::ARMSubtarget::ARMProcFamilyEnum protected
Enumerator
Others
CortexA5
CortexA7
CortexA8
CortexA9
CortexA12
CortexA15
CortexA17
CortexR5
Swift
CortexA53
CortexA57
Krait
Definition at line 44 of file ARMSubtarget.h.
Constructor & Destructor Documentation
ARMSubtarget()
ARMSubtarget::ARMSubtarget (const std::string & TT, const std::string & CPU, const std::string & FS, const ARMBaseTargetMachine & TM, bool IsLittle)
This constructor initializes the data members to match that of the specified triple.
Definition at line 150 of file ARMSubtarget.cpp.
References ARMProcClass, ARMProcFamily, computeDataLayout(), CPUString, initializeSubtargetDependencies(), IsLittle, isThumb(), isThumb1Only(), None, Options, Others, stackAlignment, TargetTriple, and TM.
Referenced by initializeSubtargetDependencies(), and ParseSubtargetFeatures().
Member Function Documentation
allowsUnalignedMem()
bool llvm::ARMSubtarget::allowsUnalignedMem () const inline
Definition at line 409 of file ARMSubtarget.h.
References AllowsUnalignedMem.
avoidCPSRPartialUpdate()
bool llvm::ARMSubtarget::avoidCPSRPartialUpdate () const inline
Definition at line 331 of file ARMSubtarget.h.
References AvoidCPSRPartialUpdate.
avoidMOVsShifterOperand()
bool llvm::ARMSubtarget::avoidMOVsShifterOperand () const inline
Definition at line 332 of file ARMSubtarget.h.
References AvoidMOVsShifterOperand.
computeIssueWidth()
void llvm::ARMSubtarget::computeIssueWidth ()
enableAtomicExpand()
bool ARMSubtarget::enableAtomicExpand () const override
Definition at line 384 of file ARMSubtarget.cpp.
References hasAnyDataBarrier(), and isThumb1Only().
enablePostMachineScheduler()
bool ARMSubtarget::enablePostMachineScheduler () const override
True for some subtargets at > -O0.
Definition at line 380 of file ARMSubtarget.cpp.
References hasThumb2(), and isThumb().
getCPUString()
const std::string & llvm::ARMSubtarget::getCPUString () const inline
Definition at line 413 of file ARMSubtarget.h.
References CPUString.
getDataLayout()
const DataLayout * llvm::ARMSubtarget::getDataLayout () const inline override
Definition at line 251 of file ARMSubtarget.h.
getFrameLowering()
const ARMFrameLowering * llvm::ARMSubtarget::getFrameLowering () const inline override
Definition at line 261 of file ARMSubtarget.h.
getInstrInfo()
const ARMBaseInstrInfo * llvm::ARMSubtarget::getInstrInfo () const inline override
Definition at line 255 of file ARMSubtarget.h.
getInstrItineraryData()
const InstrItineraryData * llvm::ARMSubtarget::getInstrItineraryData () const inline override
getInstrItins - Return the instruction itineraries based on subtarget selection.
Definition at line 431 of file ARMSubtarget.h.
References InstrItins.
getMaxInlineSizeThreshold()
unsigned llvm::ARMSubtarget::getMaxInlineSizeThreshold () const inline
getMaxInlineSizeThreshold - Returns the maximum memset / memcpy size that still makes it profitable to inline the call.
Definition at line 240 of file ARMSubtarget.h.
Referenced by llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy().
getMispredictionPenalty()
unsigned ARMSubtarget::getMispredictionPenalty () const
Definition at line 371 of file ARMSubtarget.cpp.
References SchedModel.
getRegisterInfo()
const ARMBaseRegisterInfo * llvm::ARMSubtarget::getRegisterInfo () const inline override
Definition at line 264 of file ARMSubtarget.h.
getSelectionDAGInfo()
const ARMSelectionDAGInfo * llvm::ARMSubtarget::getSelectionDAGInfo () const inline override
Definition at line 252 of file ARMSubtarget.h.
getStackAlignment()
unsigned llvm::ARMSubtarget::getStackAlignment () const inline
getStackAlignment - Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
Definition at line 438 of file ARMSubtarget.h.
References stackAlignment.
getTargetLowering()
const ARMTargetLowering * llvm::ARMSubtarget::getTargetLowering () const inline override
Definition at line 258 of file ARMSubtarget.h.
getTargetTriple()
const Triple & llvm::ARMSubtarget::getTargetTriple () const inline
Definition at line 341 of file ARMSubtarget.h.
References TargetTriple.
Referenced by hasSinCos().
GVIsIndirectSymbol()
bool ARMSubtarget::GVIsIndirectSymbol (const GlobalValue * GV, Reloc::Model RelocM) const
GVIsIndirectSymbol - true if the GV will be accessed via an indirect symbol.
GVIsIndirectSymbol - true if the GV will be accessed via an indirect symbol.
Definition at line 324 of file ARMSubtarget.cpp.
References llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasHiddenVisibility(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::isDeclarationForLinker(), isTargetMachO(), llvm::GlobalValue::isWeakForLinker(), llvm::Reloc::PIC_, and llvm::Reloc::Static.
hasAnyDataBarrier()
bool llvm::ARMSubtarget::hasAnyDataBarrier () const inline
Definition at line 319 of file ARMSubtarget.h.
References HasDataBarrier, hasV6Ops(), and isThumb().
Referenced by enableAtomicExpand().
hasARMOps()
bool llvm::ARMSubtarget::hasARMOps () const inline
Definition at line 302 of file ARMSubtarget.h.
References NoARM.
hasCRC()
bool llvm::ARMSubtarget::hasCRC () const inline
Definition at line 310 of file ARMSubtarget.h.
References HasCRC.
hasCrypto()
bool llvm::ARMSubtarget::hasCrypto () const inline
Definition at line 309 of file ARMSubtarget.h.
References HasCrypto.
hasD16()
bool llvm::ARMSubtarget::hasD16 () const inline
Definition at line 339 of file ARMSubtarget.h.
References HasD16.
hasDataBarrier()
bool llvm::ARMSubtarget::hasDataBarrier () const inline
Definition at line 318 of file ARMSubtarget.h.
References HasDataBarrier.
Referenced by LowerATOMIC_FENCE().
hasDivide()
bool llvm::ARMSubtarget::hasDivide () const inline
Definition at line 315 of file ARMSubtarget.h.
References HasHardwareDivide.
hasDivideInARMMode()
bool llvm::ARMSubtarget::hasDivideInARMMode () const inline
Definition at line 316 of file ARMSubtarget.h.
References HasHardwareDivideInARM.
hasFP16()
bool llvm::ARMSubtarget::hasFP16 () const inline
Definition at line 338 of file ARMSubtarget.h.
References HasFP16.
hasFPARMv8()
bool llvm::ARMSubtarget::hasFPARMv8 () const inline
Definition at line 307 of file ARMSubtarget.h.
References HasFPARMv8.
hasMPExtension()
bool llvm::ARMSubtarget::hasMPExtension () const inline
Definition at line 334 of file ARMSubtarget.h.
References HasMPExtension.
Referenced by LowerPREFETCH().
hasNEON()
bool llvm::ARMSubtarget::hasNEON () const inline
Definition at line 308 of file ARMSubtarget.h.
References HasNEON.
Referenced by AddCombineToVPADDL(), checkNumAlignedDPRCS2Regs(), PerformORCombine(), PerformVCVTCombine(), PerformVDIVCombine(), and useNEONForSinglePrecisionFP().
hasPerfMon()
bool llvm::ARMSubtarget::hasPerfMon () const inline
Definition at line 327 of file ARMSubtarget.h.
References HasPerfMon.
Referenced by ReplaceREADCYCLECOUNTER().
hasRAS()
bool llvm::ARMSubtarget::hasRAS () const inline
Definition at line 333 of file ARMSubtarget.h.
References HasRAS.
hasSinCos()
bool ARMSubtarget::hasSinCos () const
This function returns true if the target has sincos() routine in its compiler runtime or math libraries.
Definition at line 375 of file ARMSubtarget.cpp.
References getTargetTriple(), llvm::Triple::isiOS(), and llvm::Triple::isOSVersionLT().
hasT2ExtractPack()
bool llvm::ARMSubtarget::hasT2ExtractPack () const inline
Definition at line 317 of file ARMSubtarget.h.
References HasT2ExtractPack.
Referenced by PerformORCombine().
hasThumb2()
bool llvm::ARMSubtarget::hasThumb2 () const inline
Definition at line 394 of file ARMSubtarget.h.
References HasThumb2.
Referenced by enablePostMachineScheduler().
hasThumb2DSP()
bool llvm::ARMSubtarget::hasThumb2DSP () const inline
Definition at line 335 of file ARMSubtarget.h.
References Thumb2DSP.
Referenced by getArchForCPU().
hasTrustZone()
bool llvm::ARMSubtarget::hasTrustZone () const inline
Definition at line 328 of file ARMSubtarget.h.
References HasTrustZone.
hasV4TOps()
bool llvm::ARMSubtarget::hasV4TOps () const inline
Definition at line 282 of file ARMSubtarget.h.
References HasV4TOps.
Referenced by getArchForCPU().
hasV5TEOps()
bool llvm::ARMSubtarget::hasV5TEOps () const inline
Definition at line 284 of file ARMSubtarget.h.
References HasV5TEOps.
Referenced by getArchForCPU(), and LowerPREFETCH().
hasV5TOps()
bool llvm::ARMSubtarget::hasV5TOps () const inline
Definition at line 283 of file ARMSubtarget.h.
References HasV5TOps.
Referenced by getArchForCPU().
hasV6MOps()
bool llvm::ARMSubtarget::hasV6MOps () const inline
Definition at line 286 of file ARMSubtarget.h.
References HasV6MOps.
Referenced by getArchForCPU().
hasV6Ops()
bool llvm::ARMSubtarget::hasV6Ops () const inline
Definition at line 285 of file ARMSubtarget.h.
References HasV6Ops.
Referenced by llvm::Thumb1InstrInfo::copyPhysReg(), getArchForCPU(), hasAnyDataBarrier(), and LowerATOMIC_FENCE().
hasV6T2Ops()
bool llvm::ARMSubtarget::hasV6T2Ops () const inline
Definition at line 287 of file ARMSubtarget.h.
References HasV6T2Ops.
Referenced by emitAligningInstructions(), getArchForCPU(), and PerformORCombine().
hasV7Ops()
bool llvm::ARMSubtarget::hasV7Ops () const inline
Definition at line 288 of file ARMSubtarget.h.
References HasV7Ops.
Referenced by emitAligningInstructions(), getArchForCPU(), and LowerPREFETCH().
hasV8Ops()
bool llvm::ARMSubtarget::hasV8Ops () const inline
Definition at line 289 of file ARMSubtarget.h.
References HasV8Ops.
Referenced by getArchForCPU().
hasVFP2()
bool llvm::ARMSubtarget::hasVFP2 () const inline
Definition at line 304 of file ARMSubtarget.h.
References HasVFPv2.
Referenced by isLegalAddressImmediate(), and isLegalT2AddressImmediate().
hasVFP3()
bool llvm::ARMSubtarget::hasVFP3 () const inline
Definition at line 305 of file ARMSubtarget.h.
References HasVFPv3.
hasVFP4()
bool llvm::ARMSubtarget::hasVFP4 () const inline
Definition at line 306 of file ARMSubtarget.h.
References HasVFPv4.
hasVirtualization()
bool llvm::ARMSubtarget::hasVirtualization () const inline
Definition at line 311 of file ARMSubtarget.h.
References HasVirtualization.
hasVMLxForwarding()
bool llvm::ARMSubtarget::hasVMLxForwarding () const inline
Definition at line 324 of file ARMSubtarget.h.
References HasVMLxForwarding.
Referenced by PerformVMULCombine().
hasZeroCycleZeroing()
bool llvm::ARMSubtarget::hasZeroCycleZeroing () const inline
Definition at line 329 of file ARMSubtarget.h.
References HasZeroCycleZeroing.
initializeSubtargetDependencies()
ARMSubtarget & ARMSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
initializeSubtargetDependencies - Initializes using a CPU and feature string so that we can use initializer lists for subtarget initialization.
Definition at line 143 of file ARMSubtarget.cpp.
References ARMSubtarget().
Referenced by ARMSubtarget().
isAAPCS_ABI()
bool ARMSubtarget::isAAPCS_ABI () const
Definition at line 317 of file ARMSubtarget.cpp.
References llvm::ARMBaseTargetMachine::ARM_ABI_AAPCS, llvm::ARMBaseTargetMachine::ARM_ABI_UNKNOWN, and TM.
Referenced by llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset().
isAClass()
bool llvm::ARMSubtarget::isAClass () const inline
Definition at line 397 of file ARMSubtarget.h.
References AClass, and ARMProcClass.
isAPCS_ABI()
bool ARMSubtarget::isAPCS_ABI () const
Definition at line 313 of file ARMSubtarget.cpp.
References llvm::ARMBaseTargetMachine::ARM_ABI_APCS, llvm::ARMBaseTargetMachine::ARM_ABI_UNKNOWN, and TM.
isCortexA15()
bool llvm::ARMSubtarget::isCortexA15 () const inline
Definition at line 295 of file ARMSubtarget.h.
References ARMProcFamily, and CortexA15.
Referenced by isLikeA9().
isCortexA5()
bool llvm::ARMSubtarget::isCortexA5 () const inline
Definition at line 291 of file ARMSubtarget.h.
References ARMProcFamily, and CortexA5.
isCortexA7()
bool llvm::ARMSubtarget::isCortexA7 () const inline
Definition at line 292 of file ARMSubtarget.h.
References ARMProcFamily, and CortexA7.
Referenced by adjustDefLatency().
isCortexA8()
bool llvm::ARMSubtarget::isCortexA8 () const inline
Definition at line 293 of file ARMSubtarget.h.
References ARMProcFamily, and CortexA8.
Referenced by adjustDefLatency().
isCortexA9()
bool llvm::ARMSubtarget::isCortexA9 () const inline
Definition at line 294 of file ARMSubtarget.h.
References ARMProcFamily, and CortexA9.
Referenced by isLikeA9().
isCortexM3()
bool llvm::ARMSubtarget::isCortexM3 () const inline
Definition at line 297 of file ARMSubtarget.h.
References CPUString.
isCortexR5()
bool llvm::ARMSubtarget::isCortexR5 () const inline
Definition at line 299 of file ARMSubtarget.h.
References ARMProcFamily, and CortexR5.
isFPBrccSlow()
bool llvm::ARMSubtarget::isFPBrccSlow () const inline
Definition at line 325 of file ARMSubtarget.h.
References SlowFPBrcc.
Referenced by canChangeToInt().
isFPOnlySP()
bool llvm::ARMSubtarget::isFPOnlySP () const inline
Definition at line 326 of file ARMSubtarget.h.
References FPOnlySP.
Referenced by PerformVMOVRRDCombine().
isKrait()
bool llvm::ARMSubtarget::isKrait () const inline
Definition at line 300 of file ARMSubtarget.h.
References ARMProcFamily, and Krait.
Referenced by isLikeA9().
isLikeA9()
bool llvm::ARMSubtarget::isLikeA9 () const inline
Definition at line 298 of file ARMSubtarget.h.
References isCortexA15(), isCortexA9(), and isKrait().
Referenced by adjustDefLatency().
isLittle()
bool llvm::ARMSubtarget::isLittle () const inline
Definition at line 415 of file ARMSubtarget.h.
References IsLittle.
isMClass()
bool llvm::ARMSubtarget::isMClass () const inline
Definition at line 395 of file ARMSubtarget.h.
References ARMProcClass, and MClass.
Referenced by getArchForCPU(), isV6M(), and LowerATOMIC_FENCE().
isR9Reserved()
bool llvm::ARMSubtarget::isR9Reserved () const inline
Definition at line 403 of file ARMSubtarget.h.
References IsR9Reserved.
isRClass()
bool llvm::ARMSubtarget::isRClass () const inline
Definition at line 396 of file ARMSubtarget.h.
References ARMProcClass, and RClass.
isSwift()
bool llvm::ARMSubtarget::isSwift () const inline
Definition at line 296 of file ARMSubtarget.h.
References ARMProcFamily, and Swift.
Referenced by adjustDefLatency(), and LowerATOMIC_FENCE().
isTargetAEABI()
bool llvm::ARMSubtarget::isTargetAEABI () const inline
Definition at line 361 of file ARMSubtarget.h.
References llvm::Triple::EABI, llvm::Triple::EABIHF, isTargetDarwin(), isTargetWindows(), and TargetTriple.
isTargetAndroid()
bool llvm::ARMSubtarget::isTargetAndroid () const inline
Definition at line 384 of file ARMSubtarget.h.
References llvm::Triple::Android, and TargetTriple.
isTargetCOFF()
bool llvm::ARMSubtarget::isTargetCOFF () const inline
Definition at line 350 of file ARMSubtarget.h.
References TargetTriple.
isTargetDarwin()
bool llvm::ARMSubtarget::isTargetDarwin () const inline
Definition at line 343 of file ARMSubtarget.h.
References TargetTriple.
Referenced by isTargetAEABI(), and isTargetEHABICompatible().
isTargetEHABICompatible()
bool llvm::ARMSubtarget::isTargetEHABICompatible () const inline
Definition at line 369 of file ARMSubtarget.h.
References llvm::Triple::Android, llvm::Triple::EABI, llvm::Triple::EABIHF, llvm::Triple::GNUEABI, llvm::Triple::GNUEABIHF, isTargetDarwin(), isTargetWindows(), and TargetTriple.
isTargetELF()
bool llvm::ARMSubtarget::isTargetELF () const inline
Definition at line 351 of file ARMSubtarget.h.
References TargetTriple.
isTargetHardFloat()
bool llvm::ARMSubtarget::isTargetHardFloat () const inline
Definition at line 378 of file ARMSubtarget.h.
References llvm::Triple::EABIHF, llvm::Triple::GNUEABIHF, isTargetWindows(), and TargetTriple.
isTargetIOS()
bool llvm::ARMSubtarget::isTargetIOS () const inline
Definition at line 344 of file ARMSubtarget.h.
References TargetTriple.
isTargetLinux()
bool llvm::ARMSubtarget::isTargetLinux () const inline
Definition at line 345 of file ARMSubtarget.h.
References TargetTriple.
Referenced by llvm::ARM::createFastISel().
isTargetMachO()
bool llvm::ARMSubtarget::isTargetMachO () const inline
Definition at line 352 of file ARMSubtarget.h.
References TargetTriple.
Referenced by llvm::ARM::createFastISel(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), and GVIsIndirectSymbol().
isTargetNaCl()
bool llvm::ARMSubtarget::isTargetNaCl () const inline
Definition at line 346 of file ARMSubtarget.h.
References TargetTriple.
Referenced by llvm::ARM::createFastISel().
isTargetNetBSD()
bool llvm::ARMSubtarget::isTargetNetBSD () const inline
Definition at line 347 of file ARMSubtarget.h.
References TargetTriple.
isTargetWindows()
bool llvm::ARMSubtarget::isTargetWindows () const inline
Definition at line 348 of file ARMSubtarget.h.
References TargetTriple.
Referenced by llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), isTargetAEABI(), isTargetEHABICompatible(), isTargetHardFloat(), and useMovt().
isThumb()
bool llvm::ARMSubtarget::isThumb () const inline
Definition at line 391 of file ARMSubtarget.h.
References InThumbMode.
Referenced by ARMSubtarget(), llvm::ARM::createFastISel(), enablePostMachineScheduler(), hasAnyDataBarrier(), LowerATOMIC_FENCE(), and LowerPREFETCH().
isThumb1Only()
bool llvm::ARMSubtarget::isThumb1Only () const inline
Definition at line 392 of file ARMSubtarget.h.
References HasThumb2, and InThumbMode.
Referenced by AddCombineTo64bitMLAL(), ARMSubtarget(), llvm::ARM::createFastISel(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), enableAtomicExpand(), isLegalAddressImmediate(), isV6M(), LowerPREFETCH(), PerformANDCombine(), PerformMULCombine(), PerformORCombine(), and PerformXORCombine().
isThumb2()
bool llvm::ARMSubtarget::isThumb2 () const inline
Definition at line 393 of file ARMSubtarget.h.
References HasThumb2, and InThumbMode.
Referenced by isLegalAddressImmediate(), and LowerPREFETCH().
isV6M()
bool llvm::ARMSubtarget::isV6M () const inline
Definition at line 399 of file ARMSubtarget.h.
References isMClass(), and isThumb1Only().
ParseSubtargetFeatures()
void llvm::ARMSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
References ARMSubtarget().
prefers32BitThumb()
bool llvm::ARMSubtarget::prefers32BitThumb () const inline
Definition at line 330 of file ARMSubtarget.h.
References Pref32BitThumb.
restrictIT()
bool llvm::ARMSubtarget::restrictIT () const inline
Definition at line 411 of file ARMSubtarget.h.
References RestrictIT.
supportsTailCall()
bool llvm::ARMSubtarget::supportsTailCall () const inline
Definition at line 407 of file ARMSubtarget.h.
References SupportsTailCall.
useFPVMLx()
bool llvm::ARMSubtarget::useFPVMLx () const inline
Definition at line 323 of file ARMSubtarget.h.
References SlowFPVMLx.
useMovt()
bool ARMSubtarget::useMovt (const MachineFunction & MF) const
Definition at line 388 of file ARMSubtarget.cpp.
References llvm::AttributeSet::FunctionIndex, llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::AttributeSet::hasAttribute(), isTargetWindows(), llvm::Attribute::MinSize, and UseMovt.
useMulOps()
bool llvm::ARMSubtarget::useMulOps () const inline
Definition at line 322 of file ARMSubtarget.h.
References UseMulOps.
useNaClTrap()
bool llvm::ARMSubtarget::useNaClTrap () const inline
Definition at line 336 of file ARMSubtarget.h.
References UseNaClTrap.
useNEONForSinglePrecisionFP()
bool llvm::ARMSubtarget::useNEONForSinglePrecisionFP () const inline
Definition at line 312 of file ARMSubtarget.h.
References hasNEON(), and UseNEONForSinglePrecisionFP.
Member Data Documentation
AllowsUnalignedMem
bool llvm::ARMSubtarget::AllowsUnalignedMem protected
AllowsUnalignedMem - If true, the subtarget allows unaligned memory accesses for some types. For details, see ARMTargetLowering::allowsMisalignedMemoryAccesses().
Definition at line 191 of file ARMSubtarget.h.
Referenced by allowsUnalignedMem().
ARMProcClass
ARMProcClassEnum llvm::ARMSubtarget::ARMProcClass protected
ARMProcClass - ARM processor class: None, AClass, RClass or MClass.
Definition at line 56 of file ARMSubtarget.h.
Referenced by ARMSubtarget(), isAClass(), isMClass(), and isRClass().
ARMProcFamily
ARMProcFamilyEnum llvm::ARMSubtarget::ARMProcFamily protected
ARMProcFamily - ARM processor family: Cortex-A8, Cortex-A9, and others.
Definition at line 53 of file ARMSubtarget.h.
Referenced by ARMSubtarget(), isCortexA15(), isCortexA5(), isCortexA7(), isCortexA8(), isCortexA9(), isCortexR5(), isKrait(), and isSwift().
AvoidCPSRPartialUpdate
bool llvm::ARMSubtarget::AvoidCPSRPartialUpdate protected
AvoidCPSRPartialUpdate - If true, codegen would avoid using instructions that partially update CPSR and add false dependency on the previous CPSR setting instruction.
Definition at line 148 of file ARMSubtarget.h.
Referenced by avoidCPSRPartialUpdate().
AvoidMOVsShifterOperand
bool llvm::ARMSubtarget::AvoidMOVsShifterOperand protected
AvoidMOVsShifterOperand - If true, codegen should avoid using flag setting movs with shifter operand (i.e. asr, lsl, lsr).
Definition at line 152 of file ARMSubtarget.h.
Referenced by avoidMOVsShifterOperand().
CPUString
std::string llvm::ARMSubtarget::CPUString protected
CPUString - String name of used CPU.
Definition at line 212 of file ARMSubtarget.h.
Referenced by ARMSubtarget(), getCPUString(), and isCortexM3().
FPOnlySP
bool llvm::ARMSubtarget::FPOnlySP protected
FPOnlySP - If true, the floating point unit only supports single precision.
Definition at line 168 of file ARMSubtarget.h.
Referenced by isFPOnlySP().
HasCRC
bool llvm::ARMSubtarget::HasCRC protected
HasCRC - if true, processor supports CRC instructions.
Definition at line 182 of file ARMSubtarget.h.
Referenced by hasCRC().
HasCrypto
bool llvm::ARMSubtarget::HasCrypto protected
HasCrypto - if true, processor supports Cryptography extensions.
Definition at line 179 of file ARMSubtarget.h.
Referenced by hasCrypto().
HasD16
bool llvm::ARMSubtarget::HasD16 protected
HasD16 - True if subtarget is limited to 16 double precision FP registers for VFPv3.
Definition at line 125 of file ARMSubtarget.h.
Referenced by hasD16().
HasDataBarrier
bool llvm::ARMSubtarget::HasDataBarrier protected
HasDataBarrier - True if the subtarget supports DMB / DSB data barrier instructions.
Definition at line 139 of file ARMSubtarget.h.
Referenced by hasAnyDataBarrier(), and hasDataBarrier().
HasFP16
bool llvm::ARMSubtarget::HasFP16 protected
HasFP16 - True if subtarget supports half-precision FP (We support VFP+HF only so far)
Definition at line 121 of file ARMSubtarget.h.
Referenced by hasFP16().
HasFPARMv8
bool llvm::ARMSubtarget::HasFPARMv8 protected
Definition at line 75 of file ARMSubtarget.h.
Referenced by hasFPARMv8().
HasHardwareDivide
bool llvm::ARMSubtarget::HasHardwareDivide protected
HasHardwareDivide - True if subtarget supports [su]div.
Definition at line 128 of file ARMSubtarget.h.
Referenced by hasDivide().
HasHardwareDivideInARM
bool llvm::ARMSubtarget::HasHardwareDivideInARM protected
HasHardwareDivideInARM - True if subtarget supports [su]div in ARM mode.
Definition at line 131 of file ARMSubtarget.h.
Referenced by hasDivideInARMMode().
HasMPExtension
bool llvm::ARMSubtarget::HasMPExtension protected
HasMPExtension - True if the subtarget supports Multiprocessing extension (ARMv7 only).
Definition at line 160 of file ARMSubtarget.h.
Referenced by hasMPExtension().
HasNEON
bool llvm::ARMSubtarget::HasNEON protected
Definition at line 76 of file ARMSubtarget.h.
Referenced by hasNEON().
HasPerfMon
bool llvm::ARMSubtarget::HasPerfMon protected
If true, the processor supports the Performance Monitor Extensions. These include a generic cycle-counter as well as more fine-grained (often implementation-specific) events.
Definition at line 173 of file ARMSubtarget.h.
Referenced by hasPerfMon().
HasRAS
bool llvm::ARMSubtarget::HasRAS protected
HasRAS - Some processors perform return stack prediction. CodeGen should avoid issue "normal" call instructions to callees which do not return.
Definition at line 156 of file ARMSubtarget.h.
Referenced by hasRAS().
HasT2ExtractPack
bool llvm::ARMSubtarget::HasT2ExtractPack protected
HasT2ExtractPack - True if subtarget supports thumb2 extract/pack instructions.
Definition at line 135 of file ARMSubtarget.h.
Referenced by hasT2ExtractPack().
HasThumb2
bool llvm::ARMSubtarget::HasThumb2 protected
HasThumb2 - True if Thumb2 instructions are supported.
Definition at line 102 of file ARMSubtarget.h.
Referenced by hasThumb2(), isThumb1Only(), and isThumb2().
HasTrustZone
bool llvm::ARMSubtarget::HasTrustZone protected
HasTrustZone - if true, processor supports TrustZone security extensions.
Definition at line 176 of file ARMSubtarget.h.
Referenced by hasTrustZone().
HasV4TOps
bool llvm::ARMSubtarget::HasV4TOps protected
HasV4TOps, HasV5TOps, HasV5TEOps, HasV6Ops, HasV6MOps, HasV6T2Ops, HasV7Ops, HasV8Ops - Specify whether target support specific ARM ISA variants.
Definition at line 61 of file ARMSubtarget.h.
Referenced by hasV4TOps().
HasV5TEOps
bool llvm::ARMSubtarget::HasV5TEOps protected
Definition at line 63 of file ARMSubtarget.h.
Referenced by hasV5TEOps().
HasV5TOps
bool llvm::ARMSubtarget::HasV5TOps protected
Definition at line 62 of file ARMSubtarget.h.
Referenced by hasV5TOps().
HasV6MOps
bool llvm::ARMSubtarget::HasV6MOps protected
Definition at line 65 of file ARMSubtarget.h.
Referenced by hasV6MOps().
HasV6Ops
bool llvm::ARMSubtarget::HasV6Ops protected
Definition at line 64 of file ARMSubtarget.h.
Referenced by hasV6Ops().
HasV6T2Ops
bool llvm::ARMSubtarget::HasV6T2Ops protected
Definition at line 66 of file ARMSubtarget.h.
Referenced by hasV6T2Ops().
HasV7Ops
bool llvm::ARMSubtarget::HasV7Ops protected
Definition at line 67 of file ARMSubtarget.h.
Referenced by hasV7Ops().
HasV8Ops
bool llvm::ARMSubtarget::HasV8Ops protected
Definition at line 68 of file ARMSubtarget.h.
Referenced by hasV8Ops().
HasVFPv2
bool llvm::ARMSubtarget::HasVFPv2 protected
HasVFPv2, HasVFPv3, HasVFPv4, HasFPARMv8, HasNEON - Specify what floating point ISAs are supported.
Definition at line 72 of file ARMSubtarget.h.
Referenced by hasVFP2().
HasVFPv3
bool llvm::ARMSubtarget::HasVFPv3 protected
Definition at line 73 of file ARMSubtarget.h.
Referenced by hasVFP3().
HasVFPv4
bool llvm::ARMSubtarget::HasVFPv4 protected
Definition at line 74 of file ARMSubtarget.h.
Referenced by hasVFP4().
HasVirtualization
bool llvm::ARMSubtarget::HasVirtualization protected
HasVirtualization - True if the subtarget supports the Virtualization extension.
Definition at line 164 of file ARMSubtarget.h.
Referenced by hasVirtualization().
HasVMLxForwarding
bool llvm::ARMSubtarget::HasVMLxForwarding protected
HasVMLxForwarding - If true, NEON has special multiplier accumulator forwarding to allow mul + mla being issued back to back.
Definition at line 93 of file ARMSubtarget.h.
Referenced by hasVMLxForwarding().
HasZeroCycleZeroing
bool llvm::ARMSubtarget::HasZeroCycleZeroing protected
If true, the instructions "vmov.i32 d0, #0" and "vmov.i32 q0, #0" are particularly effective at zeroing a VFP register.
Definition at line 186 of file ARMSubtarget.h.
Referenced by hasZeroCycleZeroing().
InstrItins
InstrItineraryData llvm::ARMSubtarget::InstrItins protected
Selected instruction itineraries (one entry per itinerary class.)
Definition at line 224 of file ARMSubtarget.h.
Referenced by getInstrItineraryData().
InThumbMode
bool llvm::ARMSubtarget::InThumbMode protected
InThumbMode - True if compiling for Thumb, false for ARM.
Definition at line 99 of file ARMSubtarget.h.
Referenced by isThumb(), isThumb1Only(), and isThumb2().
IsLittle
bool llvm::ARMSubtarget::IsLittle protected
IsLittle - The target is Little Endian.
Definition at line 215 of file ARMSubtarget.h.
Referenced by ARMSubtarget(), and isLittle().
IsR9Reserved
bool llvm::ARMSubtarget::IsR9Reserved protected
IsR9Reserved - True if R9 is a not available as general purpose register.
Definition at line 108 of file ARMSubtarget.h.
Referenced by isR9Reserved().
NoARM
bool llvm::ARMSubtarget::NoARM protected
NoARM - True if subtarget does not support ARM mode execution.
Definition at line 105 of file ARMSubtarget.h.
Referenced by hasARMOps().
Options
const TargetOptions& llvm::ARMSubtarget::Options protected
Options passed via command line that could influence the target.
Definition at line 227 of file ARMSubtarget.h.
Referenced by ARMSubtarget().
Pref32BitThumb
bool llvm::ARMSubtarget::Pref32BitThumb protected
Pref32BitThumb - If true, codegen would prefer 32-bit Thumb instructions over 16-bit ones.
Definition at line 143 of file ARMSubtarget.h.
Referenced by prefers32BitThumb().
RestrictIT
bool llvm::ARMSubtarget::RestrictIT protected
RestrictIT - If true, the subtarget disallows generation of deprecated IT blocks to conform to ARMv8 rule.
Definition at line 195 of file ARMSubtarget.h.
Referenced by restrictIT().
SchedModel
MCSchedModel llvm::ARMSubtarget::SchedModel protected
SchedModel - Processor specific instruction costs.
Definition at line 221 of file ARMSubtarget.h.
Referenced by getMispredictionPenalty().
SlowFPBrcc
bool llvm::ARMSubtarget::SlowFPBrcc protected
SlowFPBrcc - True if floating point compare + branch is slow.
Definition at line 96 of file ARMSubtarget.h.
Referenced by isFPBrccSlow().
SlowFPVMLx
bool llvm::ARMSubtarget::SlowFPVMLx protected
SlowFPVMLx - If the VFP2 / NEON instructions are available, indicates whether the FP VML[AS] instructions are slow (if so, don't use them).
Definition at line 89 of file ARMSubtarget.h.
Referenced by useFPVMLx().
stackAlignment
unsigned llvm::ARMSubtarget::stackAlignment protected
stackAlignment - The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
Definition at line 209 of file ARMSubtarget.h.
Referenced by ARMSubtarget(), and getStackAlignment().
SupportsTailCall
bool llvm::ARMSubtarget::SupportsTailCall protected
SupportsTailCall - True if the OS supports tail call. The dynamic linker must be able to synthesize call stubs for interworking between ARM and Thumb.
Definition at line 117 of file ARMSubtarget.h.
Referenced by supportsTailCall().
TargetTriple
Triple llvm::ARMSubtarget::TargetTriple protected
TargetTriple - What processor and OS we're targeting.
Definition at line 218 of file ARMSubtarget.h.
Referenced by ARMSubtarget(), getTargetTriple(), isTargetAEABI(), isTargetAndroid(), isTargetCOFF(), isTargetDarwin(), isTargetEHABICompatible(), isTargetELF(), isTargetHardFloat(), isTargetIOS(), isTargetLinux(), isTargetMachO(), isTargetNaCl(), isTargetNetBSD(), and isTargetWindows().
Thumb2DSP
bool llvm::ARMSubtarget::Thumb2DSP protected
Thumb2DSP - If true, the subtarget supports the v7 DSP (saturating arith and such) instructions in Thumb2 code.
Definition at line 199 of file ARMSubtarget.h.
Referenced by hasThumb2DSP().
TM
const ARMBaseTargetMachine& llvm::ARMSubtarget::TM protected
Definition at line 229 of file ARMSubtarget.h.
Referenced by ARMSubtarget(), isAAPCS_ABI(), and isAPCS_ABI().
UnsafeFPMath
bool llvm::ARMSubtarget::UnsafeFPMath protected
Target machine allowed unsafe FP math (such as use of NEON fp)
Definition at line 205 of file ARMSubtarget.h.
UseMovt
bool llvm::ARMSubtarget::UseMovt protected
UseMovt - True if MOVT / MOVW pairs are used for materialization of 32-bit imms (including global addresses).
Definition at line 112 of file ARMSubtarget.h.
Referenced by useMovt().
UseMulOps
bool llvm::ARMSubtarget::UseMulOps protected
UseMulOps - True if non-microcoded fused integer multiply-add and multiply-subtract instructions should be used.
Definition at line 85 of file ARMSubtarget.h.
Referenced by useMulOps().
UseNaClTrap
bool llvm::ARMSubtarget::UseNaClTrap protected
NaCl TRAP instruction is generated instead of the regular TRAP.
Definition at line 202 of file ARMSubtarget.h.
Referenced by useNaClTrap().
UseNEONForSinglePrecisionFP
bool llvm::ARMSubtarget::UseNEONForSinglePrecisionFP protected
UseNEONForSinglePrecisionFP - if the NEONFP attribute has been specified. Use the method useNEONForSinglePrecisionFP() to determine if NEON should actually be used.
Definition at line 81 of file ARMSubtarget.h.
Referenced by useNEONForSinglePrecisionFP().
The documentation for this class was generated from the following files:
ARMSubtarget.h
ARMSubtarget.cpp