LLVM: llvm::StratifiedSets< T > Class Template Reference
LLVM API Documentation
llvm::StratifiedSets< T > Class Template Reference
#include <StratifiedSets.h>
Public Member Functions
StratifiedSets ()
StratifiedSets (DenseMap< T, StratifiedInfo > Map, std::vector< StratifiedLink > Links)
StratifiedSets (StratifiedSets< T > &&Other)
StratifiedSets & operator= (StratifiedSets< T > &&Other)
Optional< StratifiedInfo > find (const T &Elem) const
const StratifiedLink & getLink (StratifiedIndex Index) const
Detailed Description
template<typename T>
class llvm::StratifiedSets< T >
Definition at line 96 of file StratifiedSets.h.
Constructor & Destructor Documentation
StratifiedSets() [1/3]
template<typename T> llvm::StratifiedSets< T >::StratifiedSets () inline
Definition at line 98 of file StratifiedSets.h.
Referenced by operator=(), and StratifiedSets().
StratifiedSets() [2/3]
template<typename T> llvm::StratifiedSets< T >::StratifiedSets (DenseMap< T, StratifiedInfo > Map, std::vector< StratifiedLink > Links) inline
Definition at line 100 of file StratifiedSets.h.
StratifiedSets() [3/3]
template<typename T> llvm::StratifiedSets< T >::StratifiedSets (StratifiedSets< T > && Other) inline
Definition at line 104 of file StratifiedSets.h.
References StratifiedSets().
Member Function Documentation
find()
template<typename T> Optional< StratifiedInfo > llvm::StratifiedSets< T >::find (const T & Elem) const inline
Definition at line 112 of file StratifiedSets.h.
References T.
getLink()
template<typename T> const StratifiedLink & llvm::StratifiedSets< T >::getLink (StratifiedIndex Index) const inline
Definition at line 120 of file StratifiedSets.h.
operator=()
template<typename T> StratifiedSets & llvm::StratifiedSets< T >::operator= (StratifiedSets< T > && Other) inline
Definition at line 106 of file StratifiedSets.h.
References StratifiedSets().
The documentation for this class was generated from the following file:
StratifiedSets.h