LLVM: llvm::AArch64FunctionInfo Class Reference
LLVM API Documentation
llvm::AArch64FunctionInfo Class Reference
#include <AArch64MachineFunctionInfo.h>
Classes
class MILOHDirective
Public Types
typedef SmallPtrSet< const MachineInstr *, 16 > SetOfInstructions
typedef MILOHDirective::LOHArgs MILOHArgs
typedef SmallVector< MILOHDirective, 32 > MILOHContainer
Public Member Functions
AArch64FunctionInfo ()
AArch64FunctionInfo (MachineFunction &MF)
unsigned getBytesInStackArgArea () const
void setBytesInStackArgArea (unsigned bytes)
unsigned getArgumentStackToRestore () const
void setArgumentStackToRestore (unsigned bytes)
bool hasStackFrame () const
void setHasStackFrame (bool s)
void setLocalStackSize (unsigned Size)
unsigned getLocalStackSize () const
void incNumLocalDynamicTLSAccesses ()
unsigned getNumLocalDynamicTLSAccesses () const
int getVarArgsStackIndex () const
void setVarArgsStackIndex (int Index)
int getVarArgsGPRIndex () const
void setVarArgsGPRIndex (int Index)
unsigned getVarArgsGPRSize () const
void setVarArgsGPRSize (unsigned Size)
int getVarArgsFPRIndex () const
void setVarArgsFPRIndex (int Index)
unsigned getVarArgsFPRSize () const
void setVarArgsFPRSize (unsigned Size)
const SetOfInstructions & getLOHRelated () const
const MILOHContainer & getLOHContainer () const
void addLOHDirective (MCLOHType Kind, const MILOHArgs &Args)
Add a LOH directive of this Kind and this Args.
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty>
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
AArch64FunctionInfo - This class is derived from MachineFunctionInfo and contains private AArch64-specific information for each MachineFunction.
Definition at line 26 of file AArch64MachineFunctionInfo.h.
Member Typedef Documentation
MILOHArgs
typedef MILOHDirective::LOHArgs llvm::AArch64FunctionInfo::MILOHArgs
Definition at line 145 of file AArch64MachineFunctionInfo.h.
MILOHContainer
typedef SmallVector<MILOHDirective, 32> llvm::AArch64FunctionInfo::MILOHContainer
Definition at line 146 of file AArch64MachineFunctionInfo.h.
SetOfInstructions
typedef SmallPtrSet<const MachineInstr *, 16> llvm::AArch64FunctionInfo::SetOfInstructions
Definition at line 122 of file AArch64MachineFunctionInfo.h.
Constructor & Destructor Documentation
AArch64FunctionInfo() [1/2]
llvm::AArch64FunctionInfo::AArch64FunctionInfo () inline
Definition at line 76 of file AArch64MachineFunctionInfo.h.
AArch64FunctionInfo() [2/2]
llvm::AArch64FunctionInfo::AArch64FunctionInfo (MachineFunction & MF) inline explicit
Definition at line 81 of file AArch64MachineFunctionInfo.h.
Member Function Documentation
addLOHDirective()
void llvm::AArch64FunctionInfo::addLOHDirective (MCLOHType Kind, const MILOHArgs & Args) inline
Add a LOH directive of this Kind and this Args.
Definition at line 151 of file AArch64MachineFunctionInfo.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by computeADRP(), computeOthers(), and registerADRCandidate().
getArgumentStackToRestore()
unsigned llvm::AArch64FunctionInfo::getArgumentStackToRestore () const inline
Definition at line 91 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitEpilogue().
getBytesInStackArgArea()
unsigned llvm::AArch64FunctionInfo::getBytesInStackArgArea () const inline
Definition at line 88 of file AArch64MachineFunctionInfo.h.
getLocalStackSize()
unsigned llvm::AArch64FunctionInfo::getLocalStackSize () const inline
Definition at line 100 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::canUseRedZone(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
getLOHContainer()
const MILOHContainer & llvm::AArch64FunctionInfo::getLOHContainer () const inline
Definition at line 148 of file AArch64MachineFunctionInfo.h.
getLOHRelated()
const SetOfInstructions & llvm::AArch64FunctionInfo::getLOHRelated () const inline
Definition at line 124 of file AArch64MachineFunctionInfo.h.
getNumLocalDynamicTLSAccesses()
unsigned llvm::AArch64FunctionInfo::getNumLocalDynamicTLSAccesses () const inline
Definition at line 103 of file AArch64MachineFunctionInfo.h.
getVarArgsFPRIndex()
int llvm::AArch64FunctionInfo::getVarArgsFPRIndex () const inline
Definition at line 116 of file AArch64MachineFunctionInfo.h.
getVarArgsFPRSize()
unsigned llvm::AArch64FunctionInfo::getVarArgsFPRSize () const inline
Definition at line 119 of file AArch64MachineFunctionInfo.h.
getVarArgsGPRIndex()
int llvm::AArch64FunctionInfo::getVarArgsGPRIndex () const inline
Definition at line 110 of file AArch64MachineFunctionInfo.h.
getVarArgsGPRSize()
unsigned llvm::AArch64FunctionInfo::getVarArgsGPRSize () const inline
Definition at line 113 of file AArch64MachineFunctionInfo.h.
getVarArgsStackIndex()
int llvm::AArch64FunctionInfo::getVarArgsStackIndex () const inline
Definition at line 107 of file AArch64MachineFunctionInfo.h.
hasStackFrame()
bool llvm::AArch64FunctionInfo::hasStackFrame () const inline
Definition at line 96 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitPrologue(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
incNumLocalDynamicTLSAccesses()
void llvm::AArch64FunctionInfo::incNumLocalDynamicTLSAccesses () inline
Definition at line 102 of file AArch64MachineFunctionInfo.h.
setArgumentStackToRestore()
void llvm::AArch64FunctionInfo::setArgumentStackToRestore (unsigned bytes) inline
Definition at line 92 of file AArch64MachineFunctionInfo.h.
setBytesInStackArgArea()
void llvm::AArch64FunctionInfo::setBytesInStackArgArea (unsigned bytes) inline
Definition at line 89 of file AArch64MachineFunctionInfo.h.
setHasStackFrame()
void llvm::AArch64FunctionInfo::setHasStackFrame (bool s) inline
Definition at line 97 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan().
setLocalStackSize()
void llvm::AArch64FunctionInfo::setLocalStackSize (unsigned Size) inline
Definition at line 99 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitPrologue().
setVarArgsFPRIndex()
void llvm::AArch64FunctionInfo::setVarArgsFPRIndex (int Index) inline
Definition at line 117 of file AArch64MachineFunctionInfo.h.
setVarArgsFPRSize()
void llvm::AArch64FunctionInfo::setVarArgsFPRSize (unsigned Size) inline
Definition at line 120 of file AArch64MachineFunctionInfo.h.
setVarArgsGPRIndex()
void llvm::AArch64FunctionInfo::setVarArgsGPRIndex (int Index) inline
Definition at line 111 of file AArch64MachineFunctionInfo.h.
setVarArgsGPRSize()
void llvm::AArch64FunctionInfo::setVarArgsGPRSize (unsigned Size) inline
Definition at line 114 of file AArch64MachineFunctionInfo.h.
setVarArgsStackIndex()
void llvm::AArch64FunctionInfo::setVarArgsStackIndex (int Index) inline
Definition at line 108 of file AArch64MachineFunctionInfo.h.
The documentation for this class was generated from the following file:
AArch64MachineFunctionInfo.h