LLVM: llvm::DenseSet< ValueT, ValueInfoT >::Iterator Class Reference
LLVM API Documentation
llvm::DenseSet< ValueT, ValueInfoT >::Iterator Class Reference
#include <DenseSet.h>
Public Types
typedef MapTy::iterator::difference_type difference_type
typedef ValueT value_type
typedef value_type * pointer
typedef value_type & reference
typedef std::forward_iterator_tag iterator_category
Public Member Functions
Iterator (const typename MapTy::iterator &i)
ValueT & operator* ()
ValueT * operator-> ()
Iterator & operator++ ()
bool operator== (const Iterator &X) const
bool operator!= (const Iterator &X) const
Friends
class DenseSet
Detailed Description
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>>
class llvm::DenseSet< ValueT, ValueInfoT >::Iterator
Definition at line 79 of file DenseSet.h.
Member Typedef Documentation
difference_type
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef MapTy::iterator::difference_type llvm::DenseSet< ValueT, ValueInfoT >::Iterator::difference_type
Definition at line 83 of file DenseSet.h.
iterator_category
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef std::forward_iterator_tag llvm::DenseSet< ValueT, ValueInfoT >::Iterator::iterator_category
Definition at line 87 of file DenseSet.h.
pointer
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef value_type* llvm::DenseSet< ValueT, ValueInfoT >::Iterator::pointer
Definition at line 85 of file DenseSet.h.
reference
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef value_type& llvm::DenseSet< ValueT, ValueInfoT >::Iterator::reference
Definition at line 86 of file DenseSet.h.
value_type
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef ValueT llvm::DenseSet< ValueT, ValueInfoT >::Iterator::value_type
Definition at line 84 of file DenseSet.h.
Constructor & Destructor Documentation
Iterator()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> llvm::DenseSet< ValueT, ValueInfoT >::Iterator::Iterator (const typename MapTy::iterator & i) inline
Definition at line 89 of file DenseSet.h.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
operator!=()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> bool llvm::DenseSet< ValueT, ValueInfoT >::Iterator::operator!= (const Iterator & X) const inline
Definition at line 96 of file DenseSet.h.
References Iterator(), and llvm::X.
operator*()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> ValueT & llvm::DenseSet< ValueT, ValueInfoT >::Iterator::operator* () inline
Definition at line 91 of file DenseSet.h.
operator++()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> Iterator & llvm::DenseSet< ValueT, ValueInfoT >::Iterator::operator++ () inline
Definition at line 94 of file DenseSet.h.
References Iterator().
operator->()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> ValueT * llvm::DenseSet< ValueT, ValueInfoT >::Iterator::operator-> () inline
Definition at line 92 of file DenseSet.h.
operator==()
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> bool llvm::DenseSet< ValueT, ValueInfoT >::Iterator::operator== (const Iterator & X) const inline
Definition at line 95 of file DenseSet.h.
References Iterator(), and llvm::X.
Friends And Related Symbol Documentation
DenseSet
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> friend class DenseSet friend
Definition at line 81 of file DenseSet.h.
References DenseSet.
Referenced by DenseSet.
The documentation for this class was generated from the following file:
DenseSet.h