LLVM: llvm::DiagnosticInfoStackSize Class Reference
LLVM API Documentation
llvm::DiagnosticInfoStackSize Class Reference
#include <DiagnosticInfo.h>
Public Member Functions
DiagnosticInfoStackSize (const Function &Fn, unsigned StackSize, DiagnosticSeverity Severity=DS_Warning)
const Function & getFunction () const
unsigned getStackSize () const
void print (DiagnosticPrinter &DP) const override
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for stack size reporting. This is basically a function and a size.
Definition at line 154 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoStackSize()
llvm::DiagnosticInfoStackSize::DiagnosticInfoStackSize (const Function & Fn, unsigned StackSize, DiagnosticSeverity Severity = DS_Warning) inline
The function that is concerned by this stack size diagnostic. The computed stack size.
Definition at line 164 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_StackSize, and llvm::DS_Warning.
Member Function Documentation
classof()
bool llvm::DiagnosticInfoStackSize::classof (const DiagnosticInfo * DI) inline static
Definition at line 174 of file DiagnosticInfo.h.
References llvm::DiagnosticInfo::DiagnosticInfo(), llvm::DK_StackSize, and llvm::DiagnosticInfo::getKind().
getFunction()
const Function & llvm::DiagnosticInfoStackSize::getFunction () const inline
Definition at line 168 of file DiagnosticInfo.h.
Referenced by print().
getStackSize()
unsigned llvm::DiagnosticInfoStackSize::getStackSize () const inline
Definition at line 169 of file DiagnosticInfo.h.
Referenced by print().
print()
void DiagnosticInfoStackSize::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 113 of file DiagnosticInfo.cpp.
References getFunction(), and getStackSize().
The documentation for this class was generated from the following files:
DiagnosticInfo.h
DiagnosticInfo.cpp