LLVM: llvm::MCELF Class Reference
LLVM API Documentation
llvm::MCELF Class Reference
#include <MCELF.h>
Static Public Member Functions
static void SetBinding (MCSymbolData &SD, unsigned Binding)
static unsigned GetBinding (const MCSymbolData &SD)
static void SetType (MCSymbolData &SD, unsigned Type)
static unsigned GetType (const MCSymbolData &SD)
static void SetVisibility (MCSymbolData &SD, unsigned Visibility)
static unsigned GetVisibility (const MCSymbolData &SD)
static void setOther (MCSymbolData &SD, unsigned Other)
static unsigned getOther (const MCSymbolData &SD)
Detailed Description
Definition at line 23 of file MCELF.h.
Member Function Documentation
GetBinding()
unsigned llvm::MCELF::GetBinding (const MCSymbolData & SD) static
Definition at line 29 of file MCELF.cpp.
References llvm::ELF_STB_Shift, llvm::MCSymbolData::getFlags(), llvm::ELF::STB_GLOBAL, llvm::ELF::STB_LOCAL, and llvm::ELF::STB_WEAK.
Referenced by llvm::MCELFStreamer::EmitCommonSymbol().
getOther()
unsigned llvm::MCELF::getOther (const MCSymbolData & SD) static
Definition at line 79 of file MCELF.cpp.
References llvm::ELF_STO_Shift, and llvm::MCSymbolData::getFlags().
Referenced by llvm::MipsTargetELFStreamer::emitAssignment().
GetType()
unsigned llvm::MCELF::GetType (const MCSymbolData & SD) static
Definition at line 46 of file MCELF.cpp.
References llvm::ELF_STT_Shift, llvm::MCSymbolData::getFlags(), llvm::ELF::STT_COMMON, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, and llvm::ELF::STT_TLS.
Referenced by llvm::MipsTargetELFStreamer::emitAssignment(), llvm::MipsTargetELFStreamer::emitLabel(), and llvm::MCELFStreamer::EmitSymbolAttribute().
GetVisibility()
unsigned llvm::MCELF::GetVisibility (const MCSymbolData & SD) static
Definition at line 64 of file MCELF.cpp.
References llvm::ELF_STV_Shift, llvm::MCSymbolData::getFlags(), llvm::ELF::STV_DEFAULT, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_INTERNAL, and llvm::ELF::STV_PROTECTED.
SetBinding()
void llvm::MCELF::SetBinding (MCSymbolData & SD, unsigned Binding) static
Definition at line 22 of file MCELF.cpp.
References llvm::ELF_STB_Shift, llvm::MCSymbolData::getFlags(), llvm::MCSymbolData::setFlags(), llvm::ELF::STB_GLOBAL, llvm::ELF::STB_LOCAL, and llvm::ELF::STB_WEAK.
Referenced by llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCELFStreamer::EmitLocalCommonSymbol(), and llvm::MCELFStreamer::EmitSymbolAttribute().
setOther()
void llvm::MCELF::setOther (MCSymbolData & SD, unsigned Other) static
Definition at line 74 of file MCELF.cpp.
References llvm::ELF_STO_Shift, llvm::MCSymbolData::getFlags(), and llvm::MCSymbolData::setFlags().
Referenced by llvm::MipsTargetELFStreamer::emitAssignment(), llvm::MipsELFStreamer::EmitInstruction(), and llvm::MipsTargetELFStreamer::emitLabel().
SetType()
void llvm::MCELF::SetType (MCSymbolData & SD, unsigned Type) static
Definition at line 36 of file MCELF.cpp.
References llvm::ELF_STT_Shift, llvm::MCSymbolData::getFlags(), llvm::MCSymbolData::setFlags(), llvm::ELF::STT_COMMON, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, and llvm::ELF::STT_TLS.
Referenced by llvm::MCELFStreamer::ChangeSection(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCELFStreamer::EmitLabel(), llvm::MCELFStreamer::EmitSymbolAttribute(), fixELFSymbolsInTLSFixupsImpl(), and fixELFSymbolsInTLSFixupsImpl().
SetVisibility()
void llvm::MCELF::SetVisibility (MCSymbolData & SD, unsigned Visibility) static
Definition at line 56 of file MCELF.cpp.
References llvm::ELF_STV_Shift, llvm::MCSymbolData::getFlags(), llvm::MCSymbolData::setFlags(), llvm::ELF::STV_DEFAULT, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_INTERNAL, and llvm::ELF::STV_PROTECTED.
Referenced by llvm::MCELFStreamer::EmitSymbolAttribute().
The documentation for this class was generated from the following files:
MCELF.h
MCELF.cpp