LLVM: llvm::LLParser Class Reference
LLVM API Documentation
llvm::LLParser Class Reference
#include <LLParser.h>
Public Types
typedef LLLexer::LocTy LocTy
Public Member Functions
LLParser (StringRef F, SourceMgr &SM, SMDiagnostic &Err, Module *m)
bool Run ()
Run: module ::= toplevelentity*.
LLVMContext & getContext ()
Detailed Description
Definition at line 108 of file LLParser.h.
Member Typedef Documentation
LocTy
typedef LLLexer::LocTy llvm::LLParser::LocTy
Definition at line 110 of file LLParser.h.
Constructor & Destructor Documentation
LLParser()
llvm::LLParser::LLParser (StringRef F, SourceMgr & SM, SMDiagnostic & Err, Module * m) inline
Definition at line 163 of file LLParser.h.
References F, and getContext().
Member Function Documentation
getContext()
LLVMContext & llvm::LLParser::getContext () inline
Definition at line 168 of file LLParser.h.
Referenced by LLParser().
Run()
bool LLParser::Run ()
Run: module ::= toplevelentity*.
Definition at line 39 of file LLParser.cpp.
Referenced by llvm::parseAssemblyInto().
The documentation for this class was generated from the following files:
LLParser.h
LLParser.cpp