LLVM: llvm::jitprofiling::FilenameCache Class Reference
LLVM API Documentation
llvm::jitprofiling::FilenameCache Class Reference
#include <EventListenerCommon.h>
Public Member Functions
const char * getFilename (MDNode *Scope)
const char * getFullPath (MDNode *Scope)
Detailed Description
Definition at line 27 of file EventListenerCommon.h.
Member Function Documentation
getFilename()
const char * llvm::jitprofiling::FilenameCache::getFilename (MDNode * Scope) inline
Definition at line 34 of file EventListenerCommon.h.
References llvm::DIScope::getFilename(), and llvm::MDNode::isResolved().
getFullPath()
const char * llvm::jitprofiling::FilenameCache::getFullPath (MDNode * Scope) inline
Definition at line 44 of file EventListenerCommon.h.
References llvm::sys::path::append(), llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), llvm::MDNode::isResolved(), P, and llvm::SmallString< InternalLen >::str().
The documentation for this class was generated from the following file:
EventListenerCommon.h