LLVM: llvm::TargetSubtargetInfo Class Reference
LLVM API Documentation
llvm::TargetSubtargetInfo Class Reference
#include <TargetSubtargetInfo.h>
Public Types
enum AntiDepBreakMode { ANTIDEP_NONE , ANTIDEP_CRITICAL , ANTIDEP_ALL }
typedef SmallVectorImpl< const TargetRegisterClass * > RegClassVector
Public Member Functions
virtual ~TargetSubtargetInfo ()
virtual const TargetInstrInfo * getInstrInfo () const
virtual const TargetFrameLowering * getFrameLowering () const
virtual const TargetLowering * getTargetLowering () const
virtual const TargetSelectionDAGInfo * getSelectionDAGInfo () const
virtual const DataLayout * getDataLayout () const
virtual const TargetRegisterInfo * getRegisterInfo () const
virtual const InstrItineraryData * getInstrItineraryData () const
virtual unsigned resolveSchedClass (unsigned SchedClass, const MachineInstr *MI, const TargetSchedModel *SchedModel) const
bool useMachineScheduler () const
Temporary API to test migration to MI scheduler.
virtual bool enableMachineScheduler () const
True if the subtarget should run MachineScheduler after aggressive coalescing.
virtual bool enablePostMachineScheduler () const
True if the subtarget should run PostMachineScheduler.
virtual bool enableAtomicExpand () const
True if the subtarget should run the atomic expansion pass.
virtual void overrideSchedPolicy (MachineSchedPolicy &Policy, MachineInstr *begin, MachineInstr *end, unsigned NumRegionInstrs) const
Override generic scheduling policy within a region.
virtual void adjustSchedDependency (SUnit *def, SUnit *use, SDep &dep) const
virtual AntiDepBreakMode getAntiDepBreakMode () const
virtual void getCriticalPathRCs (RegClassVector &CriticalPathRCs) const
virtual CodeGenOpt::Level getOptLevelToEnablePostRAScheduler () const
virtual bool enableRALocalReassignment (CodeGenOpt::Level OptLevel) const
True if the subtarget should run the local reassignment heuristic of the register allocator. This heuristic may be compile time intensive, OptLevel provides a finer grain to tune the register allocator.
virtual bool useAA () const
Enable use of alias analysis during code generation (during MI scheduling, DAGCombine, etc.).
virtual bool enableEarlyIfConversion () const
Enable the use of the early if conversion pass.
virtual std::unique_ptr< PBQPRAConstraint > getCustomPBQPConstraints () const
Return PBQPConstraint(s) for the target.
virtual bool enableSubRegLiveness () const
Enable tracking of subregister liveness in register allocator.
Public Member Functions inherited from llvm::MCSubtargetInfo
void InitMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS, ArrayRef< SubtargetFeatureKV > PF, ArrayRef< SubtargetFeatureKV > PD, const SubtargetInfoKV *ProcSched, const MCWriteProcResEntry *WPR, const MCWriteLatencyEntry *WL, const MCReadAdvanceEntry *RA, const InstrStage *IS, const unsigned *OC, const unsigned *FP)
StringRef getTargetTriple () const
getTargetTriple - Return the target triple string.
uint64_t getFeatureBits () const
void setFeatureBits (uint64_t FeatureBits_)
void InitMCProcessorInfo (StringRef CPU, StringRef FS)
void InitCPUSchedModel (StringRef CPU)
InitCPUSchedModel - Recompute scheduling model based on CPU.
uint64_t ToggleFeature (uint64_t FB)
uint64_t ToggleFeature (StringRef FS)
MCSchedModel getSchedModelForCPU (StringRef CPU) const
const MCSchedModel & getSchedModel () const
const MCWriteProcResEntry * getWriteProcResBegin (const MCSchedClassDesc *SC) const
const MCWriteProcResEntry * getWriteProcResEnd (const MCSchedClassDesc *SC) const
const MCWriteLatencyEntry * getWriteLatencyEntry (const MCSchedClassDesc *SC, unsigned DefIdx) const
int getReadAdvanceCycles (const MCSchedClassDesc *SC, unsigned UseIdx, unsigned WriteResID) const
InstrItineraryData getInstrItineraryForCPU (StringRef CPU) const
void initInstrItins (InstrItineraryData &InstrItins) const
Initialize an InstrItineraryData instance.
bool isCPUStringValid (StringRef CPU)
Check whether the CPU string is valid.
Protected Member Functions
TargetSubtargetInfo ()
Detailed Description
TargetSubtargetInfo - Generic base class for all target subtargets. All Target-specific options that control code generation and printing should be exposed through a TargetSubtargetInfo-derived class.
Definition at line 44 of file TargetSubtargetInfo.h.
Member Typedef Documentation
RegClassVector
typedef SmallVectorImpl<const TargetRegisterClass*> llvm::TargetSubtargetInfo::RegClassVector
Definition at line 53 of file TargetSubtargetInfo.h.
Member Enumeration Documentation
AntiDepBreakMode
enum llvm::TargetSubtargetInfo::AntiDepBreakMode
Enumerator
ANTIDEP_NONE
ANTIDEP_CRITICAL
ANTIDEP_ALL
Definition at line 52 of file TargetSubtargetInfo.h.
Constructor & Destructor Documentation
TargetSubtargetInfo()
TargetSubtargetInfo::TargetSubtargetInfo () protected
Definition at line 22 of file TargetSubtargetInfo.cpp.
~TargetSubtargetInfo()
TargetSubtargetInfo::~TargetSubtargetInfo () virtual
Definition at line 24 of file TargetSubtargetInfo.cpp.
Member Function Documentation
adjustSchedDependency()
virtual void llvm::TargetSubtargetInfo::adjustSchedDependency (SUnit * def, SUnit * use, SDep & dep) const inline virtual
Definition at line 130 of file TargetSubtargetInfo.h.
enableAtomicExpand()
bool TargetSubtargetInfo::enableAtomicExpand () const virtual
True if the subtarget should run the atomic expansion pass.
Definition at line 42 of file TargetSubtargetInfo.cpp.
enableEarlyIfConversion()
virtual bool llvm::TargetSubtargetInfo::enableEarlyIfConversion () const inline virtual
Enable the use of the early if conversion pass.
Definition at line 163 of file TargetSubtargetInfo.h.
enableMachineScheduler()
bool TargetSubtargetInfo::enableMachineScheduler () const virtual
True if the subtarget should run MachineScheduler after aggressive coalescing.
This currently replaces the SelectionDAG scheduler with the "source" order scheduler. It does not yet disable the postRA scheduler.
Definition at line 46 of file TargetSubtargetInfo.cpp.
Referenced by useMachineScheduler().
enablePostMachineScheduler()
bool TargetSubtargetInfo::enablePostMachineScheduler () const virtual
True if the subtarget should run PostMachineScheduler.
This only takes effect if the target has configured the PostMachineScheduler pass to run, or if the global cl::opt flag, MISchedPostRA, is set.
Definition at line 55 of file TargetSubtargetInfo.cpp.
References llvm::MCSubtargetInfo::getSchedModel(), and llvm::MCSchedModel::PostRAScheduler.
enableRALocalReassignment()
bool TargetSubtargetInfo::enableRALocalReassignment (CodeGenOpt::Level OptLevel) const virtual
True if the subtarget should run the local reassignment heuristic of the register allocator. This heuristic may be compile time intensive, OptLevel provides a finer grain to tune the register allocator.
Definition at line 50 of file TargetSubtargetInfo.cpp.
enableSubRegLiveness()
virtual bool llvm::TargetSubtargetInfo::enableSubRegLiveness () const inline virtual
Enable tracking of subregister liveness in register allocator.
Definition at line 173 of file TargetSubtargetInfo.h.
getAntiDepBreakMode()
virtual AntiDepBreakMode llvm::TargetSubtargetInfo::getAntiDepBreakMode () const inline virtual
Definition at line 135 of file TargetSubtargetInfo.h.
References ANTIDEP_NONE.
getCriticalPathRCs()
virtual void llvm::TargetSubtargetInfo::getCriticalPathRCs (RegClassVector & CriticalPathRCs) const inline virtual
Definition at line 142 of file TargetSubtargetInfo.h.
References llvm::SmallVectorImpl< T >::clear().
getCustomPBQPConstraints()
virtual std::unique_ptr< PBQPRAConstraint > llvm::TargetSubtargetInfo::getCustomPBQPConstraints () const inline virtual
Return PBQPConstraint(s) for the target.
Override to provide custom PBQP constraints.
Definition at line 168 of file TargetSubtargetInfo.h.
getDataLayout()
virtual const DataLayout * llvm::TargetSubtargetInfo::getDataLayout () const inline virtual
Definition at line 74 of file TargetSubtargetInfo.h.
Referenced by llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), llvm::AArch64FrameLowering::emitPrologue(), llvm::MachineFunction::getJTISymbol(), llvm::MachineFunction::getPICBaseSymbol(), llvm::PPC::getVSPLTImmediate(), llvm::PPC::isVMRGHShuffleMask(), llvm::PPC::isVMRGLShuffleMask(), llvm::PPC::isVPKUHUMShuffleMask(), llvm::PPC::isVPKUWUMShuffleMask(), llvm::PPC::isVSLDOIShuffleMask(), and llvm::AMDGPUTargetLowering::LowerGlobalAddress().
getFrameLowering()
virtual const TargetFrameLowering * llvm::TargetSubtargetInfo::getFrameLowering () const inline virtual
Definition at line 67 of file TargetSubtargetInfo.h.
Referenced by llvm::ARMBaseRegisterInfo::canRealignStack(), checkNumAlignedDPRCS2Regs(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), emitDebugValueComment(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MachineFrameInfo::estimateStackSize(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), llvm::XCoreRegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getFrameRegister(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::HexagonRegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::MSP430RegisterInfo::getFrameRegister(), llvm::PPCRegisterInfo::getFrameRegister(), llvm::SystemZRegisterInfo::getFrameRegister(), llvm::X86RegisterInfo::getFrameRegister(), llvm::XCoreRegisterInfo::getFrameRegister(), llvm::AMDGPUInstrInfo::getIndirectIndexEnd(), llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::ARMBaseRegisterInfo::getRegPressureLimit(), llvm::MipsRegisterInfo::getRegPressureLimit(), llvm::PPCRegisterInfo::getRegPressureLimit(), llvm::X86RegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::getReservedRegs(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::MSP430RegisterInfo::getReservedRegs(), llvm::SystemZRegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::XCoreRegisterInfo::getReservedRegs(), llvm::TargetInstrInfo::getSPAdjust(), llvm::MipsTargetLowering::HandleByVal(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::AArch64RegisterInfo::isReservedReg(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::X86RegisterInfo::needsStackRealignment(), llvm::MachineFrameInfo::print(), and llvm::PEI::runOnMachineFunction().
getInstrInfo()
virtual const TargetInstrInfo * llvm::TargetSubtargetInfo::getInstrInfo () const inline virtual
Definition at line 66 of file TargetSubtargetInfo.h.
Referenced by llvm::MachineBasicBlock::addLiveIn(), llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::SITargetLowering::analyzeImmediate(), llvm::SITargetLowering::buildScratchRSRC(), llvm::MachineBasicBlock::canFallThrough(), llvm::createBURRListDAGScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createSourceListDAGScheduler(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::AArch64FrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::X86FrameLowering::emitStackProbeCall(), llvm::RegScavenger::enterBasicBlock(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::SparcTargetLowering::expandSelectCC(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::MSP430InstrInfo::GetInstSizeInBytes(), llvm::ARMTargetLowering::getSchedulingPreference(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), MIsNeedChainEdge(), llvm::SITargetLowering::PostISelFolding(), replaceFI(), llvm::PPCRegisterInfo::resolveFrameIndex(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::HexagonFrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::XCoreFrameLowering::restoreCalleeSavedRegisters(), llvm::Mips16RegisterInfo::saveScavengerRegister(), llvm::Thumb1RegisterInfo::saveScavengerRegister(), setCallTargetReg(), llvm::SITargetLowering::shouldConvertConstantLoadToIntImm(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::HexagonFrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::MachineBasicBlock::updateTerminator(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getInstrItineraryData()
virtual const InstrItineraryData * llvm::TargetSubtargetInfo::getInstrItineraryData () const inline virtual
getInstrItineraryData - Returns instruction itinerary data for the target or specific subtarget.
Definition at line 85 of file TargetSubtargetInfo.h.
Referenced by llvm::HexagonInstrInfo::CreateTargetScheduleState(), and llvm::R600InstrInfo::CreateTargetScheduleState().
getOptLevelToEnablePostRAScheduler()
virtual CodeGenOpt::Level llvm::TargetSubtargetInfo::getOptLevelToEnablePostRAScheduler () const inline virtual
Definition at line 148 of file TargetSubtargetInfo.h.
References llvm::CodeGenOpt::Default.
getRegisterInfo()
virtual const TargetRegisterInfo * llvm::TargetSubtargetInfo::getRegisterInfo () const inline virtual
getRegisterInfo - If register information is available, return it. If not, return null. This is kept separate from RegInfo until RegInfo has details of graph coloring register allocation removed from it.
Definition at line 80 of file TargetSubtargetInfo.h.
Referenced by addLiveInRegs(), llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), addSavedGPR(), llvm::A57ChainingConstraint::apply(), llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::TargetSchedModel::computeOutputLatency(), llvm::createBURRListDAGScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createSourceListDAGScheduler(), emitDebugValueComment(), llvm::ARMFrameLowering::emitEpilogue(), emitKill(), llvm::XCoreFrameLowering::emitPrologue(), llvm::RegScavenger::enterBasicBlock(), llvm::MachineFrameInfo::estimateStackSize(), llvm::MipsFrameLowering::estimateStackSize(), llvm::TargetLoweringBase::findRepresentativeClass(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::TargetFrameLowering::getFrameIndexReference(), getMemcpyLoadsAndStores(), llvm::MipsTargetLowering::getOpndList(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLowering::getRegForInlineAsmConstraint(), HandleVRSaveUpdate(), llvm::AArch64FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::RegPressureTracker::init(), llvm::TargetInstrInfo::isSchedulingBoundary(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::MachineBasicBlock::print(), llvm::MachineFunction::print(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::LiveStacks::runOnMachineFunction(), llvm::PEI::runOnMachineFunction(), llvm::StackMapLiveness::runOnMachineFunction(), and llvm::MachineBasicBlock::SplitCriticalEdge().
getSelectionDAGInfo()
virtual const TargetSelectionDAGInfo * llvm::TargetSubtargetInfo::getSelectionDAGInfo () const inline virtual
Definition at line 71 of file TargetSubtargetInfo.h.
Referenced by llvm::SelectionDAG::init().
getTargetLowering()
virtual const TargetLowering * llvm::TargetSubtargetInfo::getTargetLowering () const inline virtual
Definition at line 70 of file TargetSubtargetInfo.h.
Referenced by llvm::XCoreFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::TargetMachine::getNameWithPrefix(), llvm::TargetMachine::getSymbol(), llvm::SelectionDAG::init(), llvm::GenericScheduler::initPolicy(), llvm::TargetInstrInfo::isSchedulingBoundary(), and llvm::NVPTXTargetLowering::LowerFormalArguments().
overrideSchedPolicy()
virtual void llvm::TargetSubtargetInfo::overrideSchedPolicy (MachineSchedPolicy & Policy, MachineInstr * begin, MachineInstr * end, unsigned NumRegionInstrs) const inline virtual
Override generic scheduling policy within a region.
This is a convenient way for targets that don't provide any custom scheduling heuristics (no custom MachineSchedStrategy) to make changes to the generic scheduling policy.
Definition at line 123 of file TargetSubtargetInfo.h.
Referenced by llvm::GenericScheduler::initPolicy().
resolveSchedClass()
virtual unsigned llvm::TargetSubtargetInfo::resolveSchedClass (unsigned SchedClass, const MachineInstr * MI, const TargetSchedModel * SchedModel) const inline virtual
Resolve a SchedClass at runtime, where SchedClass identifies an MCSchedClassDesc with the isVariant property. This may return the ID of another variant SchedClass, but repeated invocation must quickly terminate in a nonvariant SchedClass.
Definition at line 93 of file TargetSubtargetInfo.h.
useAA()
bool TargetSubtargetInfo::useAA () const virtual
Enable use of alias analysis during code generation (during MI scheduling, DAGCombine, etc.).
Definition at line 59 of file TargetSubtargetInfo.cpp.
useMachineScheduler()
bool TargetSubtargetInfo::useMachineScheduler () const
Temporary API to test migration to MI scheduler.
Definition at line 36 of file TargetSubtargetInfo.cpp.
References BenchMachineSched, and enableMachineScheduler().
The documentation for this class was generated from the following files:
TargetSubtargetInfo.h
TargetSubtargetInfo.cpp