LLVM: llvm::DiagnosticInfo Class Reference
LLVM API Documentation
llvm::DiagnosticInfo Class Reference abstract
This is the base abstract class for diagnostic reporting in the backend. The print method must be overloaded by the subclasses to print a user-friendly message in the client of the backend (let us call it a frontend).
#include <DiagnosticInfo.h>
Public Member Functions
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()
int getKind () const
DiagnosticSeverity getSeverity () const
virtual void print (DiagnosticPrinter &DP) const =0
Detailed Description
This is the base abstract class for diagnostic reporting in the backend. The print method must be overloaded by the subclasses to print a user-friendly message in the client of the backend (let us call it a frontend).
Definition at line 76 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfo()
llvm::DiagnosticInfo::DiagnosticInfo (int Kind, DiagnosticSeverity Severity) inline
Definition at line 84 of file DiagnosticInfo.h.
Referenced by llvm::BitcodeDiagnosticInfo::BitcodeDiagnosticInfo(), llvm::BitcodeDiagnosticInfo::classof(), llvm::DiagnosticInfoDebugMetadataVersion::classof(), llvm::DiagnosticInfoInlineAsm::classof(), llvm::DiagnosticInfoOptimizationBase::classof(), llvm::DiagnosticInfoSampleProfile::classof(), llvm::DiagnosticInfoStackSize::classof(), llvm::DiagnosticInfoDebugMetadataVersion::DiagnosticInfoDebugMetadataVersion(), llvm::DiagnosticInfoInlineAsm::DiagnosticInfoInlineAsm(), llvm::DiagnosticInfoInlineAsm::DiagnosticInfoInlineAsm(), llvm::DiagnosticInfoInlineAsm::DiagnosticInfoInlineAsm(), llvm::DiagnosticInfoOptimizationBase::DiagnosticInfoOptimizationBase(), llvm::DiagnosticInfoSampleProfile::DiagnosticInfoSampleProfile(), llvm::DiagnosticInfoSampleProfile::DiagnosticInfoSampleProfile(), llvm::DiagnosticInfoSampleProfile::DiagnosticInfoSampleProfile(), and llvm::DiagnosticInfoStackSize::DiagnosticInfoStackSize().
~DiagnosticInfo()
virtual llvm::DiagnosticInfo::~DiagnosticInfo () inline virtual
Definition at line 87 of file DiagnosticInfo.h.
Member Function Documentation
getKind()
int llvm::DiagnosticInfo::getKind () const inline
Definition at line 89 of file DiagnosticInfo.h.
Referenced by llvm::BitcodeDiagnosticInfo::classof(), llvm::DiagnosticInfoDebugMetadataVersion::classof(), llvm::DiagnosticInfoInlineAsm::classof(), llvm::DiagnosticInfoOptimizationBase::classof(), llvm::DiagnosticInfoOptimizationFailure::classof(), llvm::DiagnosticInfoOptimizationRemark::classof(), llvm::DiagnosticInfoOptimizationRemarkAnalysis::classof(), llvm::DiagnosticInfoOptimizationRemarkMissed::classof(), llvm::DiagnosticInfoSampleProfile::classof(), llvm::DiagnosticInfoStackSize::classof(), and isDiagnosticEnabled().
getSeverity()
DiagnosticSeverity llvm::DiagnosticInfo::getSeverity () const inline
Definition at line 90 of file DiagnosticInfo.h.
Referenced by llvm::LLVMContext::diagnose(), and llvm::DiagnosticInfoOptimizationFailure::isEnabled().
print()
virtual void llvm::DiagnosticInfo::print (DiagnosticPrinter & DP) const pure virtual
Print using the given DP a user-friendly message. This is the default message that will be printed to the user. It is used when the frontend does not directly take advantage of the information contained in fields of the subclasses. The printed message must not end with '.' nor start with a severity keyword.
Implemented in llvm::BitcodeDiagnosticInfo, llvm::DiagnosticInfoDebugMetadataVersion, llvm::DiagnosticInfoInlineAsm, llvm::DiagnosticInfoOptimizationBase, llvm::DiagnosticInfoSampleProfile, and llvm::DiagnosticInfoStackSize.
Referenced by llvm::LLVMContext::diagnose(), LLVMLinkModules(), and LLVMParseBitcodeInContext().
The documentation for this class was generated from the following file:
DiagnosticInfo.h