LLVM: llvm::MCRelaxableFragment Class Reference
LLVM API Documentation
llvm::MCRelaxableFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCRelaxableFragment (const MCInst &_Inst, const MCSubtargetInfo &_STI, MCSectionData *SD=nullptr)
SmallVectorImpl< char > & getContents () override
const SmallVectorImpl< char > & getContents () const override
const MCInst & getInst () const
void setInst (const MCInst &Value)
const MCSubtargetInfo & getSubtargetInfo ()
SmallVectorImpl< MCFixup > & getFixups () override
const SmallVectorImpl< MCFixup > & getFixups () const override
bool hasInstructions () const override
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
fixup_iterator fixup_begin () override
const_fixup_iterator fixup_begin () const override
fixup_iterator fixup_end () override
const_fixup_iterator fixup_end () const override
Public Member Functions inherited from llvm::MCEncodedFragmentWithFixups
MCEncodedFragmentWithFixups (MCFragment::FragmentType FType, MCSectionData *SD=nullptr)
virtual ~MCEncodedFragmentWithFixups ()
Public Member Functions inherited from llvm::MCEncodedFragment
MCEncodedFragment (MCFragment::FragmentType FType, MCSectionData *SD=nullptr)
virtual ~MCEncodedFragment ()
uint8_t getBundlePadding () const override
Get the padding size that must be inserted before this fragment. Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
void setBundlePadding (uint8_t N) override
Set the padding size for this fragment. By default it's a no-op, and only some fragments have a meaningful implementation.
Public Member Functions inherited from llvm::MCFragment
MCFragment ()
virtual ~MCFragment ()
FragmentType getKind () const
MCSectionData * getParent () const
void setParent (MCSectionData *Value)
MCSymbolData * getAtom () const
void setAtom (MCSymbolData *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
virtual bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
virtual void setAlignToBundleEnd (bool V)
void dump ()
Public Member Functions inherited from llvm::ilist_node< MCFragment >
MCFragment * getPrevNode ()
Get the previous node, or 0 for the list head.
MCFragment * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const MCFragment *F)
Static Public Member Functions inherited from llvm::MCEncodedFragmentWithFixups
static bool classof (const MCFragment *F)
Static Public Member Functions inherited from llvm::MCEncodedFragment
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCEncodedFragmentWithFixups
typedef SmallVectorImpl< MCFixup >::const_iterator const_fixup_iterator
typedef SmallVectorImpl< MCFixup >::iterator fixup_iterator
Public Types inherited from llvm::MCFragment
enum FragmentType {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Relaxable , FT_Org , FT_Dwarf , FT_DwarfFrame ,
FT_LEB
}
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType _Kind, MCSectionData *_Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node< MCFragment >
ilist_node ()
Detailed Description
A relaxable fragment holds on to its MCInst, since it may need to be relaxed during the assembler layout and relaxation stage.
Definition at line 291 of file MCAssembler.h.
Constructor & Destructor Documentation
MCRelaxableFragment()
llvm::MCRelaxableFragment::MCRelaxableFragment (const MCInst & _Inst, const MCSubtargetInfo & _STI, MCSectionData * SD = nullptr) inline
Definition at line 309 of file MCAssembler.h.
References llvm::MCFragment::FT_Relaxable, and llvm::MCEncodedFragmentWithFixups::MCEncodedFragmentWithFixups().
Member Function Documentation
classof()
bool llvm::MCRelaxableFragment::classof (const MCFragment * F) inline static
Definition at line 339 of file MCAssembler.h.
References F, and llvm::MCFragment::FT_Relaxable.
fixup_begin() [1/2]
const_fixup_iterator llvm::MCRelaxableFragment::fixup_begin () const inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 334 of file MCAssembler.h.
fixup_begin() [2/2]
fixup_iterator llvm::MCRelaxableFragment::fixup_begin () inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 333 of file MCAssembler.h.
fixup_end() [1/2]
const_fixup_iterator llvm::MCRelaxableFragment::fixup_end () const inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 337 of file MCAssembler.h.
fixup_end() [2/2]
fixup_iterator llvm::MCRelaxableFragment::fixup_end () inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 336 of file MCAssembler.h.
getContents() [1/2]
const SmallVectorImpl< char > & llvm::MCRelaxableFragment::getContents () const inline override virtual
Implements llvm::MCEncodedFragment.
Definition at line 316 of file MCAssembler.h.
getContents() [2/2]
SmallVectorImpl< char > & llvm::MCRelaxableFragment::getContents () inline override virtual
Implements llvm::MCEncodedFragment.
Definition at line 315 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitInstToFragment().
getFixups() [1/2]
const SmallVectorImpl< MCFixup > & llvm::MCRelaxableFragment::getFixups () const inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 327 of file MCAssembler.h.
getFixups() [2/2]
SmallVectorImpl< MCFixup > & llvm::MCRelaxableFragment::getFixups () inline override virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 323 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitInstToFragment().
getInst()
const MCInst & llvm::MCRelaxableFragment::getInst () const inline
Definition at line 318 of file MCAssembler.h.
getSubtargetInfo()
const MCSubtargetInfo & llvm::MCRelaxableFragment::getSubtargetInfo () inline
Definition at line 321 of file MCAssembler.h.
hasInstructions()
bool llvm::MCRelaxableFragment::hasInstructions () const inline override virtual
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
Reimplemented from llvm::MCFragment.
Definition at line 331 of file MCAssembler.h.
setInst()
void llvm::MCRelaxableFragment::setInst (const MCInst & Value) inline
Definition at line 319 of file MCAssembler.h.
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp