LLVM: llvm::object::Archive::Child Class Reference
LLVM API Documentation
llvm::object::Archive::Child Class Reference
#include <Archive.h>
Public Member Functions
Child (const Archive *Parent, const char *Start)
bool operator== (const Child &other) const
bool operator< (const Child &other) const
Child getNext () const
ErrorOr< StringRef > getName () const
StringRef getRawName () const
sys::TimeValue getLastModified () const
unsigned getUID () const
unsigned getGID () const
sys::fs::perms getAccessMode () const
uint64_t getSize () const
StringRef getBuffer () const
ErrorOr< MemoryBufferRef > getMemoryBufferRef () const
ErrorOr< std::unique_ptr< Binary > > getAsBinary (LLVMContext *Context=nullptr) const
Detailed Description
Definition at line 51 of file Archive.h.
Constructor & Destructor Documentation
Child()
Archive::Child::Child (const Archive * Parent, const char * Start)
Definition at line 83 of file Archive.cpp.
References llvm::object::Archive::Archive(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::ArchiveMemberHeader::getSize(), and Name.
Referenced by getNext(), operator<(), and operator==().
Member Function Documentation
getAccessMode()
sys::fs::perms llvm::object::Archive::Child::getAccessMode () const inline
Definition at line 83 of file Archive.h.
getAsBinary()
ErrorOr< std::unique_ptr< Binary > > Archive::Child::getAsBinary (LLVMContext * Context = nullptr) const
Definition at line 181 of file Archive.cpp.
References llvm::object::createBinary(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), and llvm::object::Binary::getMemoryBufferRef().
Referenced by llvm::MCJIT::getSymbolAddress().
getBuffer()
StringRef llvm::object::Archive::Child::getBuffer () const inline
Definition at line 89 of file Archive.h.
References getSize().
Referenced by getMemoryBufferRef().
getGID()
unsigned llvm::object::Archive::Child::getGID () const inline
Definition at line 82 of file Archive.h.
getLastModified()
sys::TimeValue llvm::object::Archive::Child::getLastModified () const inline
Definition at line 78 of file Archive.h.
getMemoryBufferRef()
ErrorOr< MemoryBufferRef > Archive::Child::getMemoryBufferRef () const
Definition at line 172 of file Archive.cpp.
References llvm::ErrorOr< T >::get(), getBuffer(), llvm::ErrorOr< T >::getError(), getName(), and Name.
getName()
ErrorOr< StringRef > Archive::Child::getName () const
Definition at line 128 of file Archive.cpp.
References llvm::StringRef::find(), llvm::StringRef::getAsInteger(), getRawName(), llvm::object::Archive::K_GNU, llvm_unreachable, llvm::object::parse_failed, llvm::StringRef::rtrim(), llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
getNext()
Archive::Child Archive::Child::getNext () const
Definition at line 113 of file Archive.cpp.
References Child().
getRawName()
StringRef llvm::object::Archive::Child::getRawName () const inline
Definition at line 77 of file Archive.h.
Referenced by getName().
getSize()
uint64_t Archive::Child::getSize () const
Returns
the size of the archive member without the header or padding.
Definition at line 107 of file Archive.cpp.
Referenced by getBuffer().
getUID()
unsigned llvm::object::Archive::Child::getUID () const inline
Definition at line 81 of file Archive.h.
operator<()
bool llvm::object::Archive::Child::operator< (const Child & other) const inline
Definition at line 70 of file Archive.h.
References llvm::StringRef::begin(), and Child().
operator==()
bool llvm::object::Archive::Child::operator== (const Child & other) const inline
Definition at line 65 of file Archive.h.
References llvm::StringRef::begin(), and Child().
The documentation for this class was generated from the following files:
Archive.h
Archive.cpp