LLVM: llvm::yaml::Input Class Reference
LLVM API Documentation
llvm::yaml::Input Class Reference
#include <YAMLTraits.h>
Public Member Functions
Input (StringRef InputContent, void *Ctxt=nullptr, SourceMgr::DiagHandlerTy DiagHandler=nullptr, void *DiagHandlerCtxt=nullptr)
~Input ()
std::error_code error ()
bool setCurrentDocument ()
bool nextDocument ()
Public Member Functions inherited from llvm::yaml::IO
IO (void *Ctxt=nullptr)
virtual ~IO ()
template<typename T>
void enumCase (T &Val, const char *Str, const T ConstVal)
template<typename T>
void enumCase (T &Val, const char *Str, const uint32_t ConstVal)
template<typename T>
void bitSetCase (T &Val, const char *Str, const T ConstVal)
template<typename T>
void bitSetCase (T &Val, const char *Str, const uint32_t ConstVal)
template<typename T>
void maskedBitSetCase (T &Val, const char *Str, T ConstVal, T Mask)
template<typename T>
void maskedBitSetCase (T &Val, const char *Str, uint32_t ConstVal, uint32_t Mask)
void * getContext ()
void setContext (void *)
template<typename T>
void mapRequired (const char *Key, T &Val)
template<typename T>
std::enable_if< has_SequenceTraits< T >::value, void >::type mapOptional (const char *Key, T &Val)
template<typename T>
void mapOptional (const char *Key, Optional< T > &Val)
template<typename T>
std::enable_if<!has_SequenceTraits< T >::value, void >::type mapOptional (const char *Key, T &Val)
template<typename T>
void mapOptional (const char *Key, T &Val, const T &Default)
Detailed Description
The Input class is used to parse a yaml document into in-memory structs and vectors.
It works by using YAMLParser to do a syntax parse of the entire yaml document, then the Input class builds a graph of HNodes which wraps each yaml Node. The extra layer is buffering. The low level yaml parser only lets you look at each node once. The buffering layer lets you search and interate multiple times. This is necessary because the mapRequired() method calls may not be in the same order as the keys in the document.
Definition at line 871 of file YAMLTraits.h.
Constructor & Destructor Documentation
Input()
Input::Input (StringRef InputContent, void * Ctxt = nullptr, SourceMgr::DiagHandlerTy DiagHandler = nullptr, void * DiagHandlerCtxt = nullptr)
Definition at line 45 of file YAMLTraits.cpp.
References llvm::yaml::IO::IO().
~Input()
Input::~Input ()
Definition at line 57 of file YAMLTraits.cpp.
Member Function Documentation
error()
std::error_code Input::error ()
Definition at line 60 of file YAMLTraits.cpp.
Referenced by llvm::yaml::operator>>().
nextDocument()
bool Input::nextDocument ()
Definition at line 94 of file YAMLTraits.cpp.
Referenced by llvm::yaml::operator>>().
setCurrentDocument()
bool Input::setCurrentDocument ()
Definition at line 73 of file YAMLTraits.cpp.
References llvm::invalid_argument, llvm::isa(), llvm::make_error_code(), N, and setCurrentDocument().
Referenced by llvm::yaml::operator>>(), llvm::yaml::operator>>(), llvm::yaml::operator>>(), and setCurrentDocument().
The documentation for this class was generated from the following files:
YAMLTraits.h
YAMLTraits.cpp