LLVM: llvm::sampleprof::SampleRecord Class Reference
LLVM API Documentation
llvm::sampleprof::SampleRecord Class Reference
Representation of a single sample record.
#include <SampleProf.h>
Public Types
typedef StringMap< unsigned > CallTargetMap
Public Member Functions
SampleRecord ()
void addSamples (unsigned S)
Increment the number of samples for this record by S.
void addCalledTarget (StringRef F, unsigned S)
Add called function F with samples S.
bool hasCalls () const
Return true if this sample record contains function calls.
unsigned getSamples () const
const CallTargetMap & getCallTargets () const
void merge (const SampleRecord &Other)
Merge the samples in Other into this record.
Detailed Description
Representation of a single sample record.
A sample record is represented by a positive integer value, which indicates how frequently was the associated line location executed.
Additionally, if the associated location contains a function call, the record will hold a list of all the possible called targets. For direct calls, this will be the exact function being invoked. For indirect calls (function pointers, virtual table dispatch), this will be a list of one or more functions.
Definition at line 113 of file SampleProf.h.
Member Typedef Documentation
CallTargetMap
typedef StringMap<unsigned> llvm::sampleprof::SampleRecord::CallTargetMap
Definition at line 115 of file SampleProf.h.
Constructor & Destructor Documentation
SampleRecord()
llvm::sampleprof::SampleRecord::SampleRecord () inline
Definition at line 117 of file SampleProf.h.
Referenced by merge().
Member Function Documentation
addCalledTarget()
void llvm::sampleprof::SampleRecord::addCalledTarget (StringRef F, unsigned S) inline
Add called function F with samples S.
Sample counts accumulate using saturating arithmetic, to avoid wrapping around unsigned integers.
Definition at line 134 of file SampleProf.h.
References F.
Referenced by merge().
addSamples()
void llvm::sampleprof::SampleRecord::addSamples (unsigned S) inline
Increment the number of samples for this record by S.
Sample counts accumulate using saturating arithmetic, to avoid wrapping around unsigned integers.
Definition at line 123 of file SampleProf.h.
Referenced by merge().
getCallTargets()
const CallTargetMap & llvm::sampleprof::SampleRecord::getCallTargets () const inline
Definition at line 146 of file SampleProf.h.
Referenced by merge(), llvm::sampleprof::FunctionSamples::print(), llvm::sampleprof::SampleProfileWriterBinary::write(), and llvm::sampleprof::SampleProfileWriterText::write().
getSamples()
unsigned llvm::sampleprof::SampleRecord::getSamples () const inline
Definition at line 145 of file SampleProf.h.
Referenced by merge(), llvm::sampleprof::FunctionSamples::print(), llvm::sampleprof::FunctionSamples::samplesAt(), llvm::sampleprof::SampleProfileWriterBinary::write(), and llvm::sampleprof::SampleProfileWriterText::write().
hasCalls()
bool llvm::sampleprof::SampleRecord::hasCalls () const inline
Return true if this sample record contains function calls.
Definition at line 143 of file SampleProf.h.
Referenced by llvm::sampleprof::FunctionSamples::print().
merge()
void llvm::sampleprof::SampleRecord::merge (const SampleRecord & Other) inline
Merge the samples in Other into this record.
Definition at line 149 of file SampleProf.h.
References addCalledTarget(), addSamples(), getCallTargets(), getSamples(), I, and SampleRecord().
Referenced by llvm::sampleprof::FunctionSamples::merge().
The documentation for this class was generated from the following file:
SampleProf.h