LLVM: llvm::MipsTargetAsmStreamer Class Reference
LLVM API Documentation
llvm::MipsTargetAsmStreamer Class Reference
#include <MipsTargetStreamer.h>
Public Member Functions
MipsTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS)
void emitDirectiveSetMicroMips () override
void emitDirectiveSetNoMicroMips () override
void emitDirectiveSetMips16 () override
void emitDirectiveSetNoMips16 () override
void emitDirectiveSetReorder () override
void emitDirectiveSetNoReorder () override
void emitDirectiveSetMacro () override
void emitDirectiveSetNoMacro () override
void emitDirectiveSetMsa () override
void emitDirectiveSetNoMsa () override
void emitDirectiveSetAt () override
void emitDirectiveSetNoAt () override
void emitDirectiveEnd (StringRef Name) override
void emitDirectiveEnt (const MCSymbol &Symbol) override
void emitDirectiveAbiCalls () override
void emitDirectiveNaN2008 () override
void emitDirectiveNaNLegacy () override
void emitDirectiveOptionPic0 () override
void emitDirectiveOptionPic2 () override
void emitFrame (unsigned StackReg, unsigned StackSize, unsigned ReturnReg) override
void emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) override
void emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) override
void emitDirectiveSetArch (StringRef Arch) override
void emitDirectiveSetMips0 () override
void emitDirectiveSetMips1 () override
void emitDirectiveSetMips2 () override
void emitDirectiveSetMips3 () override
void emitDirectiveSetMips4 () override
void emitDirectiveSetMips5 () override
void emitDirectiveSetMips32 () override
void emitDirectiveSetMips32R2 () override
void emitDirectiveSetMips32R6 () override
void emitDirectiveSetMips64 () override
void emitDirectiveSetMips64R2 () override
void emitDirectiveSetMips64R6 () override
void emitDirectiveSetDsp () override
void emitDirectiveSetNoDsp () override
void emitDirectiveSetPop () override
void emitDirectiveSetPush () override
void emitDirectiveCpLoad (unsigned RegNo) override
void emitDirectiveCpsetup (unsigned RegNo, int RegOrOffset, const MCSymbol &Sym, bool IsReg) override
void emitDirectiveModuleFP (MipsABIFlagsSection::FpABIKind Value, bool Is32BitABI) override
void emitDirectiveModuleOddSPReg (bool Enabled, bool IsO32ABI) override
void emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value) override
void emitMipsAbiFlags () override
Public Member Functions inherited from llvm::MipsTargetStreamer
MipsTargetStreamer (MCStreamer &S)
void emitDirectiveModuleFP ()
void forbidModuleDirective ()
bool isModuleDirectiveAllowed ()
template<class PredicateLibrary>
void updateABIInfo (const PredicateLibrary &P)
MipsABIFlagsSection & getABIFlagsSection ()
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
const MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MipsTargetStreamer
MipsABIFlagsSection ABIFlagsSection
bool GPRInfoSet
unsigned GPRBitMask
int GPROffset
bool FPRInfoSet
unsigned FPRBitMask
int FPROffset
bool FrameInfoSet
int FrameOffset
unsigned FrameReg
unsigned ReturnReg
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 124 of file MipsTargetStreamer.h.
Constructor & Destructor Documentation
MipsTargetAsmStreamer()
MipsTargetAsmStreamer::MipsTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & OS)
Definition at line 88 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::MipsTargetStreamer().
Member Function Documentation
emitDirectiveAbiCalls()
void MipsTargetAsmStreamer::emitDirectiveAbiCalls () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 160 of file MipsTargetStreamer.cpp.
emitDirectiveCpLoad()
void MipsTargetAsmStreamer::emitDirectiveCpLoad (unsigned RegNo) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 281 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MipsInstPrinter::getRegisterName(), and llvm::StringRef::lower().
emitDirectiveCpsetup()
void MipsTargetAsmStreamer::emitDirectiveCpsetup (unsigned RegNo, int RegOrOffset, const MCSymbol & Sym, bool IsReg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 287 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MCSymbol::getName(), llvm::MipsInstPrinter::getRegisterName(), and llvm::StringRef::lower().
emitDirectiveEnd()
void MipsTargetAsmStreamer::emitDirectiveEnd (StringRef Name) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 152 of file MipsTargetStreamer.cpp.
References Name.
emitDirectiveEnt()
void MipsTargetAsmStreamer::emitDirectiveEnt (const MCSymbol & Symbol) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 156 of file MipsTargetStreamer.cpp.
emitDirectiveModuleFP()
void MipsTargetAsmStreamer::emitDirectiveModuleFP (MipsABIFlagsSection::FpABIKind Value, bool Is32BitABI) override virtual
Emit a '.module fp=value' directive using the given values. Updates the .MIPS.abiflags section
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 306 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABIFlagsSection, and llvm::MipsTargetStreamer::emitDirectiveModuleFP().
emitDirectiveModuleOddSPReg()
void MipsTargetAsmStreamer::emitDirectiveModuleOddSPReg (bool Enabled, bool IsO32ABI) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 326 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveModuleOddSPReg(), and Enabled.
emitDirectiveNaN2008()
void MipsTargetAsmStreamer::emitDirectiveNaN2008 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 162 of file MipsTargetStreamer.cpp.
emitDirectiveNaNLegacy()
void MipsTargetAsmStreamer::emitDirectiveNaNLegacy () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 164 of file MipsTargetStreamer.cpp.
emitDirectiveOptionPic0()
void MipsTargetAsmStreamer::emitDirectiveOptionPic0 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 168 of file MipsTargetStreamer.cpp.
emitDirectiveOptionPic2()
void MipsTargetAsmStreamer::emitDirectiveOptionPic2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 172 of file MipsTargetStreamer.cpp.
emitDirectiveSetArch()
void MipsTargetAsmStreamer::emitDirectiveSetArch (StringRef Arch) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 184 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetArch().
emitDirectiveSetAt()
void MipsTargetAsmStreamer::emitDirectiveSetAt () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 142 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetAt().
emitDirectiveSetDsp()
void MipsTargetAsmStreamer::emitDirectiveSetDsp () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 246 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetDsp().
emitDirectiveSetFp()
void MipsTargetAsmStreamer::emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 315 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABIFlagsSection.
emitDirectiveSetMacro()
void MipsTargetAsmStreamer::emitDirectiveSetMacro () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 122 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMacro().
emitDirectiveSetMicroMips()
void MipsTargetAsmStreamer::emitDirectiveSetMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 92 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetMips0()
void MipsTargetAsmStreamer::emitDirectiveSetMips0 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 189 of file MipsTargetStreamer.cpp.
emitDirectiveSetMips1()
void MipsTargetAsmStreamer::emitDirectiveSetMips1 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 191 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips1().
emitDirectiveSetMips16()
void MipsTargetAsmStreamer::emitDirectiveSetMips16 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 102 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetMips2()
void MipsTargetAsmStreamer::emitDirectiveSetMips2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 196 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips2().
emitDirectiveSetMips3()
void MipsTargetAsmStreamer::emitDirectiveSetMips3 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 201 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips3().
emitDirectiveSetMips32()
void MipsTargetAsmStreamer::emitDirectiveSetMips32 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 216 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips32().
emitDirectiveSetMips32R2()
void MipsTargetAsmStreamer::emitDirectiveSetMips32R2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 221 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips32R2().
emitDirectiveSetMips32R6()
void MipsTargetAsmStreamer::emitDirectiveSetMips32R6 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 226 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips32R6().
emitDirectiveSetMips4()
void MipsTargetAsmStreamer::emitDirectiveSetMips4 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 206 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips4().
emitDirectiveSetMips5()
void MipsTargetAsmStreamer::emitDirectiveSetMips5 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 211 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips5().
emitDirectiveSetMips64()
void MipsTargetAsmStreamer::emitDirectiveSetMips64 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 231 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips64().
emitDirectiveSetMips64R2()
void MipsTargetAsmStreamer::emitDirectiveSetMips64R2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 236 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips64R2().
emitDirectiveSetMips64R6()
void MipsTargetAsmStreamer::emitDirectiveSetMips64R6 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 241 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMips64R6().
emitDirectiveSetMsa()
void MipsTargetAsmStreamer::emitDirectiveSetMsa () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 132 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetMsa().
emitDirectiveSetNoAt()
void MipsTargetAsmStreamer::emitDirectiveSetNoAt () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 147 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoAt().
emitDirectiveSetNoDsp()
void MipsTargetAsmStreamer::emitDirectiveSetNoDsp () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 251 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoDsp().
emitDirectiveSetNoMacro()
void MipsTargetAsmStreamer::emitDirectiveSetNoMacro () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 127 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoMacro().
emitDirectiveSetNoMicroMips()
void MipsTargetAsmStreamer::emitDirectiveSetNoMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 97 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetNoMips16()
void MipsTargetAsmStreamer::emitDirectiveSetNoMips16 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 107 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoMips16().
emitDirectiveSetNoMsa()
void MipsTargetAsmStreamer::emitDirectiveSetNoMsa () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 137 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetNoMsa().
emitDirectiveSetNoReorder()
void MipsTargetAsmStreamer::emitDirectiveSetNoReorder () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 117 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetPop()
void MipsTargetAsmStreamer::emitDirectiveSetPop () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 256 of file MipsTargetStreamer.cpp.
emitDirectiveSetPush()
void MipsTargetAsmStreamer::emitDirectiveSetPush () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 258 of file MipsTargetStreamer.cpp.
emitDirectiveSetReorder()
void MipsTargetAsmStreamer::emitDirectiveSetReorder () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 112 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::emitDirectiveSetReorder().
emitFMask()
void MipsTargetAsmStreamer::emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 274 of file MipsTargetStreamer.cpp.
References printHex32().
emitFrame()
void MipsTargetAsmStreamer::emitFrame (unsigned StackReg, unsigned StackSize, unsigned ReturnReg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 176 of file MipsTargetStreamer.cpp.
References llvm::MipsInstPrinter::getRegisterName(), llvm::StringRef::lower(), and llvm::MipsTargetStreamer::ReturnReg.
emitMask()
void MipsTargetAsmStreamer::emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 267 of file MipsTargetStreamer.cpp.
References printHex32().
emitMipsAbiFlags()
void MipsTargetAsmStreamer::emitMipsAbiFlags () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 322 of file MipsTargetStreamer.cpp.
The documentation for this class was generated from the following files:
MipsTargetStreamer.h
MipsTargetStreamer.cpp