LLVM: llvm::RuntimeDyldImpl Class Reference
LLVM API Documentation
llvm::RuntimeDyldImpl Class Reference abstract
#include <RuntimeDyldImpl.h>
Public Member Functions
RuntimeDyldImpl (RTDyldMemoryManager *mm)
virtual ~RuntimeDyldImpl ()
void setProcessAllSections (bool ProcessAllSections)
void setRuntimeDyldChecker (RuntimeDyldCheckerImpl *Checker)
virtual std::unique_ptr< RuntimeDyld::LoadedObjectInfo > loadObject (const object::ObjectFile &Obj)=0
uint8_t * getSymbolAddress (StringRef Name) const
uint64_t getSymbolLoadAddress (StringRef Name) const
void resolveRelocations ()
void reassignSectionAddress (unsigned SectionID, uint64_t Addr)
void mapSectionAddress (const void *LocalAddress, uint64_t TargetAddress)
bool hasError ()
void clearError ()
StringRef getErrorString ()
virtual bool isCompatibleFile (const ObjectFile &Obj) const =0
virtual void registerEHFrames ()
virtual void deregisterEHFrames ()
virtual void finalizeLoad (const ObjectFile &ObjImg, ObjSectionToIDMap &SectionMap)
Protected Types
typedef SmallVector< SectionEntry, 64 > SectionList
typedef unsigned SID
typedef std::map< SectionRef, unsigned > ObjSectionToIDMap
typedef std::pair< unsigned, uintptr_t > SymbolLoc
typedef StringMap< SymbolLoc > SymbolTableMap
typedef std::pair< unsigned, unsigned > CommonSymbolInfo
typedef std::map< SymbolRef, CommonSymbolInfo > CommonSymbolMap
typedef SmallVector< RelocationEntry, 64 > RelocationList
typedef std::map< RelocationValueRef, uintptr_t > StubMap
Protected Member Functions
virtual unsigned getMaxStubSize ()=0
virtual unsigned getStubAlignment ()=0
bool Error (const Twine &Msg)
uint64_t getSectionLoadAddress (unsigned SectionID) const
uint8_t * getSectionAddress (unsigned SectionID) const
void writeInt16BE (uint8_t *Addr, uint16_t Value)
void writeInt32BE (uint8_t *Addr, uint32_t Value)
void writeInt64BE (uint8_t *Addr, uint64_t Value)
uint64_t readBytesUnaligned (uint8_t *Src, unsigned Size) const
Endian-aware read Read the least significant Size bytes from Src.
void writeBytesUnaligned (uint64_t Value, uint8_t *Dst, unsigned Size) const
void emitCommonSymbols (const ObjectFile &Obj, const CommonSymbolMap &CommonSymbols, uint64_t TotalSize, SymbolTableMap &SymbolTable)
Given the common symbols discovered in the object file, emit a new section for them and update the symbol mappings in the object and symbol table.
unsigned emitSection (const ObjectFile &Obj, const SectionRef &Section, bool IsCode)
Emits section data from the object file to the MemoryManager.
unsigned findOrEmitSection (const ObjectFile &Obj, const SectionRef &Section, bool IsCode, ObjSectionToIDMap &LocalSections)
Find Section in LocalSections. If the secton is not found - emit it and store in LocalSections.
void addRelocationForSection (const RelocationEntry &RE, unsigned SectionID)
void addRelocationForSymbol (const RelocationEntry &RE, StringRef SymbolName)
uint8_t * createStubFunction (uint8_t *Addr, unsigned AbiVariant=0)
Emits long jump instruction to Addr.
void resolveRelocationList (const RelocationList &Relocs, uint64_t Value)
Resolves relocations from Relocs list with address from Value.
virtual void resolveRelocation (const RelocationEntry &RE, uint64_t Value)=0
A object file specific relocation resolver.
virtual relocation_iterator processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile &Obj, ObjSectionToIDMap &ObjSectionToID, StubMap &Stubs)=0
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
void resolveExternalSymbols ()
Resolve relocations to external symbols.
virtual void updateGOTEntries (StringRef Name, uint64_t Addr)
Update GOT entries for external symbols.
void computeTotalAllocSize (const ObjectFile &Obj, uint64_t &CodeSize, uint64_t &DataSizeRO, uint64_t &DataSizeRW)
unsigned computeSectionStubBufSize (const ObjectFile &Obj, const SectionRef &Section)
std::pair< unsigned, unsigned > loadObjectImpl (const object::ObjectFile &Obj)
Protected Attributes
RTDyldMemoryManager * MemMgr
RuntimeDyldCheckerImpl * Checker
SectionList Sections
SymbolTableMap GlobalSymbolTable
DenseMap< unsigned, RelocationList > Relocations
StringMap< RelocationList > ExternalSymbolRelocations
Triple::ArchType Arch
bool IsTargetLittleEndian
bool ProcessAllSections
sys::Mutex lock
bool HasError
std::string ErrorStr
Friends
class RuntimeDyld::LoadedObjectInfo
class RuntimeDyldCheckerImpl
Detailed Description
Definition at line 159 of file RuntimeDyldImpl.h.
Member Typedef Documentation
CommonSymbolInfo
typedef std::pair<unsigned, unsigned> llvm::RuntimeDyldImpl::CommonSymbolInfo protected
Definition at line 188 of file RuntimeDyldImpl.h.
CommonSymbolMap
typedef std::map<SymbolRef, CommonSymbolInfo> llvm::RuntimeDyldImpl::CommonSymbolMap protected
Definition at line 190 of file RuntimeDyldImpl.h.
ObjSectionToIDMap
typedef std::map<SectionRef, unsigned> llvm::RuntimeDyldImpl::ObjSectionToIDMap protected
Definition at line 179 of file RuntimeDyldImpl.h.
RelocationList
typedef SmallVector<RelocationEntry, 64> llvm::RuntimeDyldImpl::RelocationList protected
Definition at line 197 of file RuntimeDyldImpl.h.
SectionList
typedef SmallVector<SectionEntry, 64> llvm::RuntimeDyldImpl::SectionList protected
Definition at line 171 of file RuntimeDyldImpl.h.
SID
typedef unsigned llvm::RuntimeDyldImpl::SID protected
Definition at line 174 of file RuntimeDyldImpl.h.
StubMap
typedef std::map<RelocationValueRef, uintptr_t> llvm::RuntimeDyldImpl::StubMap protected
Definition at line 209 of file RuntimeDyldImpl.h.
SymbolLoc
typedef std::pair<unsigned, uintptr_t> llvm::RuntimeDyldImpl::SymbolLoc protected
Definition at line 183 of file RuntimeDyldImpl.h.
SymbolTableMap
typedef StringMap<SymbolLoc> llvm::RuntimeDyldImpl::SymbolTableMap protected
Definition at line 184 of file RuntimeDyldImpl.h.
Constructor & Destructor Documentation
RuntimeDyldImpl()
llvm::RuntimeDyldImpl::RuntimeDyldImpl (RTDyldMemoryManager * mm) inline
Definition at line 357 of file RuntimeDyldImpl.h.
References Checker, HasError, MemMgr, and ProcessAllSections.
Referenced by llvm::RuntimeDyldELF::RuntimeDyldELF(), and llvm::RuntimeDyldMachO::RuntimeDyldMachO().
~RuntimeDyldImpl()
RuntimeDyldImpl::~RuntimeDyldImpl () virtual
Definition at line 29 of file RuntimeDyld.cpp.
Member Function Documentation
addRelocationForSection()
void llvm::RuntimeDyldImpl::addRelocationForSection (const RelocationEntry & RE, unsigned SectionID) protected
Definition at line 582 of file RuntimeDyld.cpp.
References Relocations.
Referenced by llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), and llvm::RuntimeDyldMachOX86_64::processRelocationRef().
addRelocationForSymbol()
void llvm::RuntimeDyldImpl::addRelocationForSymbol (const RelocationEntry & RE, StringRef SymbolName) protected
Definition at line 587 of file RuntimeDyld.cpp.
References llvm::RelocationEntry::Addend, ExternalSymbolRelocations, GlobalSymbolTable, Relocations, and llvm::StringMapEntry< ValueTy >::second.
Referenced by llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), and llvm::RuntimeDyldMachOX86_64::processRelocationRef().
clearError()
void llvm::RuntimeDyldImpl::clearError () inline
Definition at line 404 of file RuntimeDyldImpl.h.
References HasError.
computeSectionStubBufSize()
unsigned llvm::RuntimeDyldImpl::computeSectionStubBufSize (const ObjectFile & Obj, const SectionRef & Section) protected
Definition at line 379 of file RuntimeDyld.cpp.
References getMaxStubSize(), getStubAlignment(), llvm::object::ObjectFile::section_begin(), and llvm::object::ObjectFile::section_end().
Referenced by computeTotalAllocSize(), and emitSection().
computeTotalAllocSize()
void llvm::RuntimeDyldImpl::computeTotalAllocSize (const ObjectFile & Obj, uint64_t & CodeSize, uint64_t & DataSizeRO, uint64_t & DataSizeRW) protected
Definition at line 296 of file RuntimeDyld.cpp.
References Check(), llvm::computeAllocationSizeForSections(), computeSectionStubBufSize(), I, llvm::isReadOnlyData(), llvm::isRequiredForExecution(), Name, llvm::object::ObjectFile::section_begin(), llvm::object::ObjectFile::section_end(), llvm::object::BasicSymbolRef::SF_Common, llvm::object::SymbolicFile::symbol_begin(), and llvm::object::SymbolicFile::symbol_end().
Referenced by loadObjectImpl().
createStubFunction()
uint8_t * llvm::RuntimeDyldImpl::createStubFunction (uint8_t * Addr, unsigned AbiVariant = 0) protected
Emits long jump instruction to Addr.
Returns
Pointer to the memory area for emitting target address.
Definition at line 603 of file RuntimeDyld.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_be, Arch, llvm::Triple::arm, llvm::Triple::armeb, llvm::Triple::mips, llvm::Triple::mipsel, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::Triple::systemz, writeBytesUnaligned(), writeInt16BE(), writeInt32BE(), llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by llvm::RuntimeDyldELF::processRelocationRef().
deregisterEHFrames()
void llvm::RuntimeDyldImpl::deregisterEHFrames () virtual
Reimplemented in llvm::RuntimeDyldELF.
Definition at line 38 of file RuntimeDyld.cpp.
emitCommonSymbols()
void llvm::RuntimeDyldImpl::emitCommonSymbols (const ObjectFile & Obj, const CommonSymbolMap & CommonSymbols, uint64_t TotalSize, SymbolTableMap & SymbolTable) protected
Given the common symbols discovered in the object file, emit a new section for them and update the symbol mappings in the object and symbol table.
Definition at line 444 of file RuntimeDyld.cpp.
References Align, llvm::dbgs(), DEBUG, llvm::format(), MemMgr, Name, llvm::OffsetToAlignment(), llvm::report_fatal_error(), and Sections.
Referenced by loadObjectImpl().
emitSection()
unsigned llvm::RuntimeDyldImpl::emitSection (const ObjectFile & Obj, const SectionRef & Section, bool IsCode) protected
Emits section data from the object file to the MemoryManager.
Parameters
IsCode if it's true then allocateCodeSection() will be used for emits, else allocateDataSection() will be used.
Returns
SectionID.
Definition at line 482 of file RuntimeDyld.cpp.
References Check(), Checker, computeSectionStubBufSize(), llvm::StringRef::data(), llvm::dbgs(), DEBUG, llvm::format(), llvm::object::Binary::getFileName(), llvm::isReadOnlyData(), llvm::isRequiredForExecution(), llvm::isZeroInit(), MemMgr, Name, llvm::report_fatal_error(), and Sections.
Referenced by findOrEmitSection().
Error()
bool llvm::RuntimeDyldImpl::Error (const Twine & Msg) inline protected
Definition at line 237 of file RuntimeDyldImpl.h.
References ErrorStr, HasError, and llvm::Twine::str().
Referenced by llvm::RuntimeDyldMachOARM::resolveRelocation(), llvm::RuntimeDyldMachOI386::resolveRelocation(), and llvm::RuntimeDyldMachOX86_64::resolveRelocation().
finalizeLoad()
virtual void llvm::RuntimeDyldImpl::finalizeLoad (const ObjectFile & ObjImg, ObjSectionToIDMap & SectionMap) inline virtual
Reimplemented in llvm::RuntimeDyldELF, llvm::RuntimeDyldMachOCRTPBase< Impl >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOAArch64 >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOARM >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOI386 >, and llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOX86_64 >.
Definition at line 415 of file RuntimeDyldImpl.h.
Referenced by loadObjectImpl().
findOrEmitSection()
unsigned llvm::RuntimeDyldImpl::findOrEmitSection (const ObjectFile & Obj, const SectionRef & Section, bool IsCode, ObjSectionToIDMap & LocalSections) protected
Find Section in LocalSections. If the secton is not found - emit it and store in LocalSections.
Parameters
IsCode if it's true then allocateCodeSection() will be used for emmits, else allocateDataSection() will be used.
Returns
SectionID.
Definition at line 566 of file RuntimeDyld.cpp.
References emitSection().
Referenced by llvm::RuntimeDyldMachOCRTPBase< Impl >::finalizeLoad(), llvm::RuntimeDyldMachO::getRelocationValueRef(), loadObjectImpl(), and llvm::RuntimeDyldELF::processRelocationRef().
getErrorString()
StringRef llvm::RuntimeDyldImpl::getErrorString () inline
Definition at line 407 of file RuntimeDyldImpl.h.
References ErrorStr.
getMaxStubSize()
virtual unsigned llvm::RuntimeDyldImpl::getMaxStubSize () protected pure virtual
Implemented in llvm::RuntimeDyldMachOAArch64, llvm::RuntimeDyldMachOARM, llvm::RuntimeDyldMachOI386, and llvm::RuntimeDyldMachOX86_64.
Referenced by computeSectionStubBufSize(), and llvm::RuntimeDyldELF::processRelocationRef().
getSectionAddress()
uint8_t * llvm::RuntimeDyldImpl::getSectionAddress (unsigned SectionID) const inline protected
Definition at line 247 of file RuntimeDyldImpl.h.
References Sections.
Referenced by getSymbolAddress().
getSectionLoadAddress()
uint64_t llvm::RuntimeDyldImpl::getSectionLoadAddress (unsigned SectionID) const inline protected
Definition at line 243 of file RuntimeDyldImpl.h.
References Sections.
Referenced by getSymbolLoadAddress(), and resolveExternalSymbols().
getStubAlignment()
virtual unsigned llvm::RuntimeDyldImpl::getStubAlignment () protected pure virtual
Implemented in llvm::RuntimeDyldMachOAArch64, llvm::RuntimeDyldMachOARM, llvm::RuntimeDyldMachOI386, and llvm::RuntimeDyldMachOX86_64.
Referenced by computeSectionStubBufSize(), and llvm::RuntimeDyldELF::processRelocationRef().
getSymbolAddress()
uint8_t * llvm::RuntimeDyldImpl::getSymbolAddress (StringRef Name) const inline
Definition at line 374 of file RuntimeDyldImpl.h.
References getSectionAddress(), GlobalSymbolTable, Name, and llvm::StringMapEntry< ValueTy >::second.
getSymbolLoadAddress()
uint64_t llvm::RuntimeDyldImpl::getSymbolLoadAddress (StringRef Name) const inline
Definition at line 384 of file RuntimeDyldImpl.h.
References getSectionLoadAddress(), GlobalSymbolTable, Name, and llvm::StringMapEntry< ValueTy >::second.
hasError()
bool llvm::RuntimeDyldImpl::hasError () inline
Definition at line 401 of file RuntimeDyldImpl.h.
References HasError.
isCompatibleFile()
virtual bool llvm::RuntimeDyldImpl::isCompatibleFile (const ObjectFile & Obj) const pure virtual
Implemented in llvm::RuntimeDyldELF, and llvm::RuntimeDyldMachO.
loadObject()
virtual std::unique_ptr< RuntimeDyld::LoadedObjectInfo > llvm::RuntimeDyldImpl::loadObject (const object::ObjectFile & Obj) pure virtual
Implemented in llvm::RuntimeDyldELF, and llvm::RuntimeDyldMachO.
loadObjectImpl()
std::pair< unsigned, unsigned > llvm::RuntimeDyldImpl::loadObjectImpl (const object::ObjectFile & Obj) protected
Definition at line 139 of file RuntimeDyld.cpp.
References Align, Arch, Check(), Checker, computeTotalAllocSize(), llvm::dbgs(), DEBUG, emitCommonSymbols(), finalizeLoad(), findOrEmitSection(), llvm::format(), llvm::object::ObjectFile::getArch(), llvm::object::Binary::getFileName(), llvm::getOffset(), GlobalSymbolTable, I, llvm::object::Binary::isLittleEndian(), IsTargetLittleEndian, llvm::object::SectionRef::isText(), lock, MemMgr, Name, ProcessAllSections, processRelocationRef(), llvm::object::ObjectFile::section_begin(), llvm::object::ObjectFile::section_end(), Sections, llvm::object::BasicSymbolRef::SF_Common, llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Unknown, llvm::object::SymbolicFile::symbol_begin(), and llvm::object::SymbolicFile::symbol_end().
Referenced by llvm::RuntimeDyldELF::loadObject(), and llvm::RuntimeDyldMachO::loadObject().
mapSectionAddress()
void llvm::RuntimeDyldImpl::mapSectionAddress (const void * LocalAddress, uint64_t TargetAddress)
Definition at line 101 of file RuntimeDyld.cpp.
References llvm_unreachable, lock, reassignSectionAddress(), and Sections.
processRelocationRef()
virtual relocation_iterator llvm::RuntimeDyldImpl::processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile & Obj, ObjSectionToIDMap & ObjSectionToID, StubMap & Stubs) protected pure virtual
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
Returns
Iterator to the next relocation that needs to be parsed.
Implemented in llvm::RuntimeDyldELF, llvm::RuntimeDyldMachOAArch64, llvm::RuntimeDyldMachOARM, llvm::RuntimeDyldMachOI386, and llvm::RuntimeDyldMachOX86_64.
Referenced by loadObjectImpl().
readBytesUnaligned()
uint64_t llvm::RuntimeDyldImpl::readBytesUnaligned (uint8_t * Src, unsigned Size) const protected
Endian-aware read Read the least significant Size bytes from Src.
Definition at line 414 of file RuntimeDyld.cpp.
References IsTargetLittleEndian.
Referenced by llvm::RuntimeDyldMachOARM::decodeAddend(), llvm::RuntimeDyldMachO::memcpyAddend(), and llvm::RuntimeDyldMachOARM::resolveRelocation().
reassignSectionAddress()
void llvm::RuntimeDyldImpl::reassignSectionAddress (unsigned SectionID, uint64_t Addr)
Definition at line 681 of file RuntimeDyld.cpp.
References llvm::dbgs(), DEBUG, llvm::format(), Name, and Sections.
Referenced by mapSectionAddress().
registerEHFrames()
void llvm::RuntimeDyldImpl::registerEHFrames () virtual
Reimplemented in llvm::RuntimeDyldELF, llvm::RuntimeDyldMachOCRTPBase< Impl >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOAArch64 >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOARM >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOI386 >, and llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOX86_64 >.
Definition at line 36 of file RuntimeDyld.cpp.
resolveExternalSymbols()
void llvm::RuntimeDyldImpl::resolveExternalSymbols () protected
Resolve relocations to external symbols.
Definition at line 711 of file RuntimeDyld.cpp.
References llvm::dbgs(), DEBUG, ExternalSymbolRelocations, llvm::format(), getSectionLoadAddress(), GlobalSymbolTable, MemMgr, Name, llvm::report_fatal_error(), resolveRelocationList(), llvm::StringMapEntry< ValueTy >::second, and updateGOTEntries().
Referenced by resolveRelocations().
resolveRelocation()
virtual void llvm::RuntimeDyldImpl::resolveRelocation (const RelocationEntry & RE, uint64_t Value) protected pure virtual
A object file specific relocation resolver.
Parameters
RE The relocation to be resolved
Value Target symbol address to apply the relocation action
Implemented in llvm::RuntimeDyldELF, llvm::RuntimeDyldMachOAArch64, llvm::RuntimeDyldMachOARM, llvm::RuntimeDyldMachOI386, and llvm::RuntimeDyldMachOX86_64.
Referenced by resolveRelocationList().
resolveRelocationList()
void llvm::RuntimeDyldImpl::resolveRelocationList (const RelocationList & Relocs, uint64_t Value) protected
Resolves relocations from Relocs list with address from Value.
Definition at line 700 of file RuntimeDyld.cpp.
References resolveRelocation(), llvm::RelocationEntry::SectionID, Sections, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by resolveExternalSymbols(), and resolveRelocations().
resolveRelocations()
void llvm::RuntimeDyldImpl::resolveRelocations ()
Definition at line 79 of file RuntimeDyld.cpp.
References llvm::dbgs(), DEBUG, llvm::dumpSectionMemory(), llvm::format(), lock, Relocations, resolveExternalSymbols(), resolveRelocationList(), and Sections.
setProcessAllSections()
void llvm::RuntimeDyldImpl::setProcessAllSections (bool ProcessAllSections) inline
Definition at line 363 of file RuntimeDyldImpl.h.
References ProcessAllSections.
setRuntimeDyldChecker()
void llvm::RuntimeDyldImpl::setRuntimeDyldChecker (RuntimeDyldCheckerImpl * Checker) inline
Definition at line 367 of file RuntimeDyldImpl.h.
References Checker, and RuntimeDyldCheckerImpl.
updateGOTEntries()
virtual void llvm::RuntimeDyldImpl::updateGOTEntries (StringRef Name, uint64_t Addr) inline protected virtual
Update GOT entries for external symbols.
Definition at line 342 of file RuntimeDyldImpl.h.
References Name.
Referenced by resolveExternalSymbols().
writeBytesUnaligned()
void llvm::RuntimeDyldImpl::writeBytesUnaligned (uint64_t Value, uint8_t * Dst, unsigned Size) const protected
Endian-aware write. Write the least significant Size bytes from Value to Dst.
Definition at line 428 of file RuntimeDyld.cpp.
References IsTargetLittleEndian.
Referenced by createStubFunction(), llvm::RuntimeDyldMachOARM::resolveRelocation(), llvm::RuntimeDyldMachOI386::resolveRelocation(), and llvm::RuntimeDyldMachOX86_64::resolveRelocation().
writeInt16BE()
void llvm::RuntimeDyldImpl::writeInt16BE (uint8_t * Addr, uint16_t Value) inline protected
Definition at line 251 of file RuntimeDyldImpl.h.
References IsTargetLittleEndian, and llvm::sys::swapByteOrder().
Referenced by createStubFunction().
writeInt32BE()
void llvm::RuntimeDyldImpl::writeInt32BE (uint8_t * Addr, uint32_t Value) inline protected
Definition at line 258 of file RuntimeDyldImpl.h.
References IsTargetLittleEndian, and llvm::sys::swapByteOrder().
Referenced by createStubFunction(), and llvm::RuntimeDyldELF::processRelocationRef().
writeInt64BE()
void llvm::RuntimeDyldImpl::writeInt64BE (uint8_t * Addr, uint64_t Value) inline protected
Definition at line 267 of file RuntimeDyldImpl.h.
References IsTargetLittleEndian, and llvm::sys::swapByteOrder().
Friends And Related Symbol Documentation
RuntimeDyld::LoadedObjectInfo
friend class RuntimeDyld::LoadedObjectInfo friend
Definition at line 160 of file RuntimeDyldImpl.h.
RuntimeDyldCheckerImpl
friend class RuntimeDyldCheckerImpl friend
Definition at line 161 of file RuntimeDyldImpl.h.
References RuntimeDyldCheckerImpl.
Referenced by RuntimeDyldCheckerImpl, and setRuntimeDyldChecker().
Member Data Documentation
Arch
Triple::ArchType llvm::RuntimeDyldImpl::Arch protected
Definition at line 211 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldMachO::create(), createStubFunction(), loadObjectImpl(), and llvm::RuntimeDyldELF::processRelocationRef().
Checker
RuntimeDyldCheckerImpl* llvm::RuntimeDyldImpl::Checker protected
Definition at line 167 of file RuntimeDyldImpl.h.
Referenced by emitSection(), loadObjectImpl(), RuntimeDyldImpl(), and setRuntimeDyldChecker().
ErrorStr
std::string llvm::RuntimeDyldImpl::ErrorStr protected
Definition at line 234 of file RuntimeDyldImpl.h.
Referenced by Error(), and getErrorString().
ExternalSymbolRelocations
StringMap<RelocationList> llvm::RuntimeDyldImpl::ExternalSymbolRelocations protected
Definition at line 206 of file RuntimeDyldImpl.h.
Referenced by addRelocationForSymbol(), and resolveExternalSymbols().
GlobalSymbolTable
SymbolTableMap llvm::RuntimeDyldImpl::GlobalSymbolTable protected
Definition at line 185 of file RuntimeDyldImpl.h.
Referenced by addRelocationForSymbol(), llvm::RuntimeDyldMachO::getRelocationValueRef(), getSymbolAddress(), getSymbolLoadAddress(), loadObjectImpl(), llvm::RuntimeDyldELF::processRelocationRef(), and resolveExternalSymbols().
HasError
bool llvm::RuntimeDyldImpl::HasError protected
Definition at line 233 of file RuntimeDyldImpl.h.
Referenced by clearError(), Error(), hasError(), and RuntimeDyldImpl().
IsTargetLittleEndian
bool llvm::RuntimeDyldImpl::IsTargetLittleEndian protected
Definition at line 212 of file RuntimeDyldImpl.h.
Referenced by loadObjectImpl(), llvm::RuntimeDyldELF::processRelocationRef(), readBytesUnaligned(), writeBytesUnaligned(), writeInt16BE(), writeInt32BE(), and writeInt64BE().
lock
sys::Mutex llvm::RuntimeDyldImpl::lock protected
Definition at line 228 of file RuntimeDyldImpl.h.
Referenced by loadObjectImpl(), mapSectionAddress(), and resolveRelocations().
MemMgr
RTDyldMemoryManager* llvm::RuntimeDyldImpl::MemMgr protected
Definition at line 164 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldELF::deregisterEHFrames(), emitCommonSymbols(), emitSection(), llvm::RuntimeDyldELF::finalizeLoad(), loadObjectImpl(), llvm::RuntimeDyldELF::registerEHFrames(), llvm::RuntimeDyldMachOCRTPBase< Impl >::registerEHFrames(), resolveExternalSymbols(), and RuntimeDyldImpl().
ProcessAllSections
bool llvm::RuntimeDyldImpl::ProcessAllSections protected
Definition at line 216 of file RuntimeDyldImpl.h.
Referenced by loadObjectImpl(), RuntimeDyldImpl(), and setProcessAllSections().
Relocations
DenseMap<unsigned, RelocationList> llvm::RuntimeDyldImpl::Relocations protected
Definition at line 201 of file RuntimeDyldImpl.h.
Referenced by addRelocationForSection(), addRelocationForSymbol(), and resolveRelocations().
Sections
SectionList llvm::RuntimeDyldImpl::Sections protected
Definition at line 172 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldMachOAArch64::decodeAddend(), llvm::RuntimeDyldMachOARM::decodeAddend(), llvm::RuntimeDyldELF::deregisterEHFrames(), llvm::RuntimeDyldMachO::dumpRelocationToResolve(), emitCommonSymbols(), emitSection(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldMachO::getSection(), getSectionAddress(), getSectionLoadAddress(), loadObjectImpl(), mapSectionAddress(), llvm::RuntimeDyldMachO::memcpyAddend(), llvm::RuntimeDyldELF::processRelocationRef(), reassignSectionAddress(), llvm::RuntimeDyldELF::registerEHFrames(), llvm::RuntimeDyldMachOCRTPBase< Impl >::registerEHFrames(), llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOAArch64 >::registerEHFrames(), llvm::RuntimeDyldELF::resolveRelocation(), llvm::RuntimeDyldMachOAArch64::resolveRelocation(), llvm::RuntimeDyldMachOARM::resolveRelocation(), llvm::RuntimeDyldMachOI386::resolveRelocation(), llvm::RuntimeDyldMachOX86_64::resolveRelocation(), resolveRelocationList(), and resolveRelocations().
The documentation for this class was generated from the following files:
RuntimeDyldImpl.h
RuntimeDyld.cpp