LLVM: llvm::SIMachineFunctionInfo Class Reference
LLVM API Documentation
llvm::SIMachineFunctionInfo Class Reference
#include <SIMachineFunctionInfo.h>
Classes
struct SpilledReg
Public Member Functions
SIMachineFunctionInfo (const MachineFunction &MF)
SpilledReg getSpilledReg (MachineFunction *MF, unsigned FrameIndex, unsigned SubIdx)
bool hasCalculatedTID () const
unsigned getTIDReg () const
void setTIDReg (unsigned Reg)
bool hasSpilledVGPRs () const
void setHasSpilledVGPRs (bool Spill=true)
unsigned getMaximumWorkGroupSize (const MachineFunction &MF) const
Public Member Functions inherited from llvm::AMDGPUMachineFunction
AMDGPUMachineFunction (const MachineFunction &MF)
unsigned getShaderType () const
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Public Attributes
unsigned PSInputAddr
unsigned NumUserSGPRs
std::map< unsigned, unsigned > LaneVGPRs
unsigned LDSWaveSpillSize
unsigned ScratchOffsetReg
Public Attributes inherited from llvm::AMDGPUMachineFunction
std::map< const GlobalValue *, unsigned > LocalMemoryObjects
unsigned LDSSize
Number of bytes in the LDS that are being used.
unsigned ABIArgOffset
Start of implicit kernel args.
unsigned ScratchSize
bool IsKernel
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty>
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
This class keeps track of the SPI_SP_INPUT_ADDR config register, which tells the hardware which interpolation parameters to load.
Definition at line 28 of file SIMachineFunctionInfo.h.
Constructor & Destructor Documentation
SIMachineFunctionInfo()
SIMachineFunctionInfo::SIMachineFunctionInfo (const MachineFunction & MF)
Definition at line 29 of file SIMachineFunctionInfo.cpp.
References llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), LDSWaveSpillSize, NumUserSGPRs, and PSInputAddr.
Member Function Documentation
getMaximumWorkGroupSize()
unsigned SIMachineFunctionInfo::getMaximumWorkGroupSize (const MachineFunction & MF) const
Definition at line 71 of file SIMachineFunctionInfo.cpp.
References ShaderType::COMPUTE, llvm::AMDGPUMachineFunction::getShaderType(), llvm::TargetMachine::getSubtarget(), and llvm::MachineFunction::getTarget().
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress().
getSpilledReg()
SIMachineFunctionInfo::SpilledReg SIMachineFunctionInfo::getSpilledReg (MachineFunction * MF, unsigned FrameIndex, unsigned SubIdx)
Definition at line 37 of file SIMachineFunctionInfo.cpp.
References llvm::MachineFunction::begin(), llvm::MachineFunction::end(), llvm::SIRegisterInfo::findUnusedRegister(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getTarget(), llvm::SIMachineFunctionInfo::SpilledReg::Lane, LaneVGPRs, llvm::MachineRegisterInfo::setPhysRegUsed(), and llvm::SIMachineFunctionInfo::SpilledReg::VGPR.
Referenced by llvm::SIRegisterInfo::eliminateFrameIndex().
getTIDReg()
unsigned llvm::SIMachineFunctionInfo::getTIDReg () const inline
Definition at line 55 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress().
hasCalculatedTID()
bool llvm::SIMachineFunctionInfo::hasCalculatedTID () const inline
Definition at line 54 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress().
hasSpilledVGPRs()
bool llvm::SIMachineFunctionInfo::hasSpilledVGPRs () const inline
Definition at line 57 of file SIMachineFunctionInfo.h.
setHasSpilledVGPRs()
void llvm::SIMachineFunctionInfo::setHasSpilledVGPRs (bool Spill = true) inline
Definition at line 58 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIInstrInfo::storeRegToStackSlot().
setTIDReg()
void llvm::SIMachineFunctionInfo::setTIDReg (unsigned Reg) inline
Definition at line 56 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress().
Member Data Documentation
LaneVGPRs
std::map<unsigned, unsigned> llvm::SIMachineFunctionInfo::LaneVGPRs
Definition at line 51 of file SIMachineFunctionInfo.h.
Referenced by getSpilledReg().
LDSWaveSpillSize
unsigned llvm::SIMachineFunctionInfo::LDSWaveSpillSize
Definition at line 52 of file SIMachineFunctionInfo.h.
Referenced by SIMachineFunctionInfo().
NumUserSGPRs
unsigned llvm::SIMachineFunctionInfo::NumUserSGPRs
Definition at line 50 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::getPreloadedValue(), and SIMachineFunctionInfo().
PSInputAddr
unsigned llvm::SIMachineFunctionInfo::PSInputAddr
Definition at line 49 of file SIMachineFunctionInfo.h.
Referenced by SIMachineFunctionInfo().
ScratchOffsetReg
unsigned llvm::SIMachineFunctionInfo::ScratchOffsetReg
Definition at line 53 of file SIMachineFunctionInfo.h.
Referenced by llvm::SIRegisterInfo::getPreloadedValue().
The documentation for this class was generated from the following files:
SIMachineFunctionInfo.h
SIMachineFunctionInfo.cpp