LLVM: llvm::AttrBuilder Class Reference
LLVM API Documentation
llvm::AttrBuilder Class Reference
This class is used in conjunction with the Attribute::get method to create an Attribute object. The object itself is uniquified. The Builder's value, however, is not. So this can be used as a quick way to test for equality, presence of attributes, etc.
#include <Attributes.h>
Public Types
typedef std::pair< std::string, std::string > td_type
typedef std::map< std::string, std::string >::iterator td_iterator
typedef std::map< std::string, std::string >::const_iterator td_const_iterator
typedef llvm::iterator_range< td_iterator > td_range
typedef llvm::iterator_range< td_const_iterator > td_const_range
Public Member Functions
AttrBuilder ()
AttrBuilder (uint64_t Val)
AttrBuilder (const Attribute &A)
AttrBuilder (AttributeSet AS, unsigned Idx)
void clear ()
AttrBuilder & addAttribute (Attribute::AttrKind Val)
Add an attribute to the builder.
AttrBuilder & addAttribute (Attribute A)
Add the Attribute object to the builder.
AttrBuilder & addAttribute (StringRef A, StringRef V=StringRef())
Add the target-dependent attribute to the builder.
AttrBuilder & removeAttribute (Attribute::AttrKind Val)
Remove an attribute from the builder.
AttrBuilder & removeAttributes (AttributeSet A, uint64_t Index)
Remove the attributes from the builder.
AttrBuilder & removeAttribute (StringRef A)
Remove the target-dependent attribute to the builder.
AttrBuilder & merge (const AttrBuilder &B)
Add the attributes from the builder.
bool contains (Attribute::AttrKind A) const
Return true if the builder has the specified attribute.
bool contains (StringRef A) const
Return true if the builder has the specified target-dependent attribute.
bool hasAttributes () const
Return true if the builder has IR-level attributes.
bool hasAttributes (AttributeSet A, uint64_t Index) const
Return true if the builder has any attribute that's in the specified attribute.
bool hasAlignmentAttr () const
Return true if the builder has an alignment attribute.
uint64_t getAlignment () const
Retrieve the alignment attribute, if it exists.
uint64_t getStackAlignment () const
Retrieve the stack alignment attribute, if it exists.
uint64_t getDereferenceableBytes () const
Retrieve the number of dereferenceable bytes, if the dereferenceable attribute exists (zero is returned otherwise).
AttrBuilder & addAlignmentAttr (unsigned Align)
This turns an int alignment (which must be a power of 2) into the form used internally in Attribute.
AttrBuilder & addStackAlignmentAttr (unsigned Align)
This turns an int stack alignment (which must be a power of 2) into the form used internally in Attribute.
AttrBuilder & addDereferenceableAttr (uint64_t Bytes)
This turns the number of dereferenceable bytes into the form used internally in Attribute.
bool empty () const
Return true if the builder contains no target-independent attributes.
td_iterator td_begin ()
td_iterator td_end ()
td_const_iterator td_begin () const
td_const_iterator td_end () const
td_range td_attrs ()
td_const_range td_attrs () const
bool td_empty () const
bool operator== (const AttrBuilder &B)
bool operator!= (const AttrBuilder &B)
AttrBuilder & addRawValue (uint64_t Val)
Add the raw value to the internal representation.
Detailed Description
This class is used in conjunction with the Attribute::get method to create an Attribute object. The object itself is uniquified. The Builder's value, however, is not. So this can be used as a quick way to test for equality, presence of attributes, etc.
Definition at line 403 of file Attributes.h.
Member Typedef Documentation
td_const_iterator
typedef std::map<std::string,std::string>::const_iterator llvm::AttrBuilder::td_const_iterator
Definition at line 493 of file Attributes.h.
td_const_range
typedef llvm::iterator_range<td_const_iterator> llvm::AttrBuilder::td_const_range
Definition at line 495 of file Attributes.h.
td_iterator
typedef std::map<std::string,std::string>::iterator llvm::AttrBuilder::td_iterator
Definition at line 492 of file Attributes.h.
td_range
typedef llvm::iterator_range<td_iterator> llvm::AttrBuilder::td_range
Definition at line 494 of file Attributes.h.
td_type
typedef std::pair<std::string, std::string> llvm::AttrBuilder::td_type
Definition at line 491 of file Attributes.h.
Constructor & Destructor Documentation
AttrBuilder() [1/4]
llvm::AttrBuilder::AttrBuilder () inline
Definition at line 410 of file Attributes.h.
Referenced by addAlignmentAttr(), addAttribute(), addAttribute(), addAttribute(), addDereferenceableAttr(), addRawValue(), addStackAlignmentAttr(), merge(), operator!=(), operator==(), removeAttribute(), removeAttribute(), and removeAttributes().
AttrBuilder() [2/4]
llvm::AttrBuilder::AttrBuilder (uint64_t Val) inline explicit
Definition at line 411 of file Attributes.h.
References addRawValue().
AttrBuilder() [3/4]
llvm::AttrBuilder::AttrBuilder (const Attribute & A) inline
Definition at line 415 of file Attributes.h.
References addAttribute().
AttrBuilder() [4/4]
AttrBuilder::AttrBuilder (AttributeSet AS, unsigned Idx)
Definition at line 1006 of file Attributes.cpp.
References llvm::AttributeSetImpl::getNumAttributes(), and I.
Member Function Documentation
addAlignmentAttr()
AttrBuilder & AttrBuilder::addAlignmentAttr (unsigned Align)
This turns an int alignment (which must be a power of 2) into the form used internally in Attribute.
Definition at line 1114 of file Attributes.cpp.
References Align, llvm::Attribute::Alignment, AttrBuilder(), and llvm::isPowerOf2_32().
Referenced by decodeLLVMAttributesForBitcode(), getParameterABIAttributes(), LLVMSetInstrParamAlignment(), and LLVMSetParamAlignment().
addAttribute() [1/3]
AttrBuilder & AttrBuilder::addAttribute (Attribute A)
Add the Attribute object to the builder.
Definition at line 1036 of file Attributes.cpp.
References addAttribute(), llvm::Attribute::Alignment, AttrBuilder(), llvm::Attribute::Dereferenceable, llvm::Attribute::getAlignment(), llvm::Attribute::getDereferenceableBytes(), llvm::Attribute::getKindAsEnum(), llvm::Attribute::getKindAsString(), llvm::Attribute::getStackAlignment(), llvm::Attribute::getValueAsString(), llvm::Attribute::isStringAttribute(), and llvm::Attribute::StackAlignment.
addAttribute() [2/3]
AttrBuilder & AttrBuilder::addAttribute (Attribute::AttrKind Val)
Add an attribute to the builder.
Definition at line 1027 of file Attributes.cpp.
References llvm::Attribute::Alignment, AttrBuilder(), llvm::Attribute::Dereferenceable, llvm::Attribute::EndAttrKinds, and llvm::Attribute::StackAlignment.
Referenced by addAttribute(), llvm::AttributeSet::addAttribute(), llvm::AttributeSet::addAttribute(), llvm::AttributeSet::addAttributes(), AdjustCallerSSPLevel(), AttrBuilder(), getParameterABIAttributes(), LLVMAddTargetDependentFunctionAttr(), and llvm::AttributeFuncs::typeIncompatible().
addAttribute() [3/3]
AttrBuilder & AttrBuilder::addAttribute (StringRef A, StringRef V = StringRef())
Add the target-dependent attribute to the builder.
Definition at line 1054 of file Attributes.cpp.
References AttrBuilder().
addDereferenceableAttr()
AttrBuilder & AttrBuilder::addDereferenceableAttr (uint64_t Bytes)
This turns the number of dereferenceable bytes into the form used internally in Attribute.
Definition at line 1137 of file Attributes.cpp.
References AttrBuilder(), and llvm::Attribute::Dereferenceable.
Referenced by llvm::AttributeFuncs::typeIncompatible().
addRawValue()
AttrBuilder & AttrBuilder::addRawValue (uint64_t Val)
Add the raw value to the internal representation.
Definition at line 1215 of file Attributes.cpp.
References llvm::Attribute::Alignment, AttrBuilder(), llvm::Attribute::Dereferenceable, llvm::Attribute::EndAttrKinds, llvm::AttributeImpl::getAttrMask(), I, llvm::Attribute::None, and llvm::Attribute::StackAlignment.
Referenced by AttrBuilder(), and decodeLLVMAttributesForBitcode().
addStackAlignmentAttr()
AttrBuilder & AttrBuilder::addStackAlignmentAttr (unsigned Align)
This turns an int stack alignment (which must be a power of 2) into the form used internally in Attribute.
Definition at line 1125 of file Attributes.cpp.
References Align, AttrBuilder(), llvm::isPowerOf2_32(), and llvm::Attribute::StackAlignment.
clear()
void AttrBuilder::clear ()
Definition at line 1022 of file Attributes.cpp.
contains() [1/2]
bool llvm::AttrBuilder::contains (Attribute::AttrKind A) const inline
Return true if the builder has the specified attribute.
Definition at line 445 of file Attributes.h.
References llvm::Attribute::EndAttrKinds.
Referenced by llvm::AttributeSet::get(), and llvm::returnTypeIsEligibleForTailCall().
contains() [2/2]
bool AttrBuilder::contains (StringRef A) const
Return true if the builder has the specified target-dependent attribute.
Definition at line 1165 of file Attributes.cpp.
empty()
bool llvm::AttrBuilder::empty () const inline
Return true if the builder contains no target-independent attributes.
Definition at line 488 of file Attributes.h.
getAlignment()
uint64_t llvm::AttrBuilder::getAlignment () const inline
Retrieve the alignment attribute, if it exists.
Definition at line 465 of file Attributes.h.
Referenced by llvm::AttributeSet::get().
getDereferenceableBytes()
uint64_t llvm::AttrBuilder::getDereferenceableBytes () const inline
Retrieve the number of dereferenceable bytes, if the dereferenceable attribute exists (zero is returned otherwise).
Definition at line 472 of file Attributes.h.
Referenced by llvm::AttributeSet::get().
getStackAlignment()
uint64_t llvm::AttrBuilder::getStackAlignment () const inline
Retrieve the stack alignment attribute, if it exists.
Definition at line 468 of file Attributes.h.
Referenced by llvm::AttributeSet::get().
hasAlignmentAttr()
bool AttrBuilder::hasAlignmentAttr () const
Return true if the builder has an alignment attribute.
Definition at line 1198 of file Attributes.cpp.
hasAttributes() [1/2]
bool AttrBuilder::hasAttributes () const
Return true if the builder has IR-level attributes.
Definition at line 1169 of file Attributes.cpp.
Referenced by llvm::AttributeSet::get().
hasAttributes() [2/2]
bool AttrBuilder::hasAttributes (AttributeSet A, uint64_t Index) const
Return true if the builder has any attribute that's in the specified attribute.
Definition at line 1173 of file Attributes.cpp.
References llvm::Attribute::getKindAsString(), I, llvm::Attribute::isEnumAttribute(), llvm::Attribute::isIntAttribute(), and llvm::Attribute::isStringAttribute().
merge()
AttrBuilder & AttrBuilder::merge (const AttrBuilder & B)
Add the attributes from the builder.
Definition at line 1145 of file Attributes.cpp.
References AttrBuilder(), and I.
operator!=()
bool llvm::AttrBuilder::operator!= (const AttrBuilder & B) inline
Definition at line 511 of file Attributes.h.
References AttrBuilder().
operator==()
bool AttrBuilder::operator== (const AttrBuilder & B)
Definition at line 1202 of file Attributes.cpp.
References AttrBuilder(), and I.
removeAttribute() [1/2]
AttrBuilder & AttrBuilder::removeAttribute (Attribute::AttrKind Val)
Remove an attribute from the builder.
Definition at line 1059 of file Attributes.cpp.
References llvm::Attribute::Alignment, AttrBuilder(), llvm::Attribute::Dereferenceable, llvm::Attribute::EndAttrKinds, and llvm::Attribute::StackAlignment.
Referenced by llvm::returnTypeIsEligibleForTailCall().
removeAttribute() [2/2]
AttrBuilder & AttrBuilder::removeAttribute (StringRef A)
Remove the target-dependent attribute to the builder.
Definition at line 1107 of file Attributes.cpp.
References AttrBuilder(), and I.
removeAttributes()
AttrBuilder & AttrBuilder::removeAttributes (AttributeSet A, uint64_t Index)
Remove the attributes from the builder.
Definition at line 1073 of file Attributes.cpp.
References llvm::Attribute::Alignment, AttrBuilder(), llvm::Attribute::Dereferenceable, llvm::Attribute::getKindAsString(), I, llvm::Attribute::isEnumAttribute(), llvm::Attribute::isIntAttribute(), llvm::Attribute::isStringAttribute(), and llvm::Attribute::StackAlignment.
Referenced by llvm::AttributeSet::removeAttributes().
td_attrs() [1/2]
td_range llvm::AttrBuilder::td_attrs () inline
Definition at line 503 of file Attributes.h.
References td_begin(), and td_end().
Referenced by llvm::AttributeSet::get().
td_attrs() [2/2]
td_const_range llvm::AttrBuilder::td_attrs () const inline
Definition at line 504 of file Attributes.h.
References td_begin(), and td_end().
td_begin() [1/2]
td_iterator llvm::AttrBuilder::td_begin () inline
Definition at line 497 of file Attributes.h.
Referenced by td_attrs(), and td_attrs().
td_begin() [2/2]
td_const_iterator llvm::AttrBuilder::td_begin () const inline
Definition at line 500 of file Attributes.h.
td_empty()
bool llvm::AttrBuilder::td_empty () const inline
Definition at line 508 of file Attributes.h.
td_end() [1/2]
td_iterator llvm::AttrBuilder::td_end () inline
Definition at line 498 of file Attributes.h.
Referenced by td_attrs(), and td_attrs().
td_end() [2/2]
td_const_iterator llvm::AttrBuilder::td_end () const inline
Definition at line 501 of file Attributes.h.
The documentation for this class was generated from the following files:
Attributes.h
Attributes.cpp