LLVM: llvm::DIEEntry Class Reference
LLVM API Documentation
llvm::DIEEntry Class Reference
#include <DIE.h>
Public Member Functions
DIEEntry (DIE &E)
DIE & getEntry () const
void EmitValue (AsmPrinter *AP, dwarf::Form Form) const override
unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const override
void print (raw_ostream &O) const override
Public Member Functions inherited from llvm::DIEValue
Type getType () const
void dump () const
Static Public Member Functions
static unsigned getRefAddrSize (AsmPrinter *AP)
Returns size of a ref_addr entry.
static bool classof (const DIEValue *E)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum Type {
isInteger , isString , isExpr , isLabel ,
isDelta , isEntry , isTypeSignature , isBlock ,
isLoc , isLocList
}
Protected Member Functions inherited from llvm::DIEValue
DIEValue (Type T)
virtual ~DIEValue ()
Protected Attributes inherited from llvm::DIEValue
Type Ty
Detailed Description
DIEEntry - A pointer to another debug information entry. An instance of this class can also be used as a proxy for a debug information entry not yet defined (ie. types.)
Definition at line 413 of file DIE.h.
Constructor & Destructor Documentation
DIEEntry()
llvm::DIEEntry::DIEEntry (DIE & E) inline explicit
Definition at line 417 of file DIE.h.
References llvm::DIEValue::DIEValue(), and llvm::DIEValue::isEntry.
Member Function Documentation
classof()
bool llvm::DIEEntry::classof (const DIEValue * E) inline static
Definition at line 437 of file DIE.h.
References llvm::DIEValue::DIEValue(), llvm::DIEValue::getType(), and llvm::DIEValue::isEntry.
EmitValue()
void DIEEntry::EmitValue (AsmPrinter * AP, dwarf::Form Form) const override virtual
EmitValue - Emit debug information entry offset.
Implements llvm::DIEValue.
Definition at line 400 of file DIE.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm::dwarf::DW_FORM_ref_addr, llvm::AsmPrinter::EmitInt32(), emitLabelOffsetDifference(), llvm::AsmPrinter::EmitLabelPlusOffset(), llvm::AsmPrinter::getDwarfDebug(), getRefAddrSize(), llvm::DwarfDebug::lookupUnit(), llvm::AsmPrinter::MAI, llvm::AsmPrinter::OutStreamer, and llvm::DwarfDebug::useSplitDwarf().
getEntry()
DIE & llvm::DIEEntry::getEntry () const inline
Definition at line 420 of file DIE.h.
Referenced by llvm::DwarfUnit::addDIEEntry().
getRefAddrSize()
unsigned DIEEntry::getRefAddrSize (AsmPrinter * AP) static
Returns size of a ref_addr entry.
Definition at line 423 of file DIE.cpp.
References llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::getDwarfDebug(), llvm::DwarfDebug::getDwarfVersion(), and llvm::DataLayout::getPointerSize().
Referenced by EmitValue(), and SizeOf().
print()
void DIEEntry::print (raw_ostream & O) const override virtual
Implements llvm::DIEValue.
Definition at line 436 of file DIE.cpp.
References llvm::format().
SizeOf()
unsigned llvm::DIEEntry::SizeOf (AsmPrinter * AP, dwarf::Form Form) const inline override virtual
SizeOf - Determine size of debug information entry in bytes.
Implements llvm::DIEValue.
Definition at line 428 of file DIE.h.
References llvm::dwarf::DW_FORM_ref_addr, and getRefAddrSize().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp