LLVM: llvm::MipsABIInfo Class Reference
LLVM API Documentation
llvm::MipsABIInfo Class Reference
#include <MipsABIInfo.h>
Public Types
enum class ABI {
Unknown , O32 , N32 , N64 ,
EABI
}
Public Member Functions
MipsABIInfo (ABI ThisABI)
bool IsKnown () const
bool IsO32 () const
bool IsN32 () const
bool IsN64 () const
bool IsEABI () const
ABI GetEnumValue () const
const ArrayRef< MCPhysReg > GetByValArgRegs () const
The registers to use for byval arguments.
const ArrayRef< MCPhysReg > GetVarArgRegs () const
The registers to use for the variable argument list.
unsigned GetCalleeAllocdArgSizeInBytes (CallingConv::ID CC) const
bool operator< (const MipsABIInfo Other) const
Static Public Member Functions
static MipsABIInfo Unknown ()
static MipsABIInfo O32 ()
static MipsABIInfo N32 ()
static MipsABIInfo N64 ()
static MipsABIInfo EABI ()
Protected Attributes
ABI ThisABI
Detailed Description
Definition at line 19 of file MipsABIInfo.h.
Member Enumeration Documentation
ABI
enum class llvm::MipsABIInfo::ABI strong
Enumerator
Unknown
O32
N32
N64
EABI
Definition at line 21 of file MipsABIInfo.h.
Constructor & Destructor Documentation
MipsABIInfo()
llvm::MipsABIInfo::MipsABIInfo (ABI ThisABI) inline
Definition at line 27 of file MipsABIInfo.h.
References ThisABI.
Referenced by EABI(), N32(), N64(), O32(), operator<(), and Unknown().
Member Function Documentation
EABI()
MipsABIInfo llvm::MipsABIInfo::EABI () inline static
Definition at line 33 of file MipsABIInfo.h.
References EABI, and MipsABIInfo().
GetByValArgRegs()
const ArrayRef< MCPhysReg > MipsABIInfo::GetByValArgRegs () const
The registers to use for byval arguments.
Definition at line 23 of file MipsABIInfo.cpp.
References IsN32(), IsN64(), IsO32(), llvm_unreachable, and llvm::makeArrayRef().
GetCalleeAllocdArgSizeInBytes()
unsigned MipsABIInfo::GetCalleeAllocdArgSizeInBytes (CallingConv::ID CC) const
Obtain the size of the area allocated by the callee for arguments. CallingConv::FastCall affects the value for O32.
Definition at line 39 of file MipsABIInfo.cpp.
References llvm::CallingConv::Fast, IsEABI(), IsN32(), IsN64(), IsO32(), and llvm_unreachable.
GetEnumValue()
ABI llvm::MipsABIInfo::GetEnumValue () const inline
Definition at line 40 of file MipsABIInfo.h.
References ThisABI.
Referenced by operator<().
GetVarArgRegs()
const ArrayRef< MCPhysReg > MipsABIInfo::GetVarArgRegs () const
The registers to use for the variable argument list.
Definition at line 31 of file MipsABIInfo.cpp.
References IsN32(), IsN64(), IsO32(), llvm_unreachable, and llvm::makeArrayRef().
IsEABI()
bool llvm::MipsABIInfo::IsEABI () const inline
Definition at line 39 of file MipsABIInfo.h.
References EABI, and ThisABI.
Referenced by GetCalleeAllocdArgSizeInBytes().
IsKnown()
bool llvm::MipsABIInfo::IsKnown () const inline
Definition at line 35 of file MipsABIInfo.h.
References ThisABI, and Unknown.
IsN32()
bool llvm::MipsABIInfo::IsN32 () const inline
Definition at line 37 of file MipsABIInfo.h.
References N32, and ThisABI.
Referenced by GetByValArgRegs(), GetCalleeAllocdArgSizeInBytes(), and GetVarArgRegs().
IsN64()
bool llvm::MipsABIInfo::IsN64 () const inline
Definition at line 38 of file MipsABIInfo.h.
References N64, and ThisABI.
Referenced by GetByValArgRegs(), GetCalleeAllocdArgSizeInBytes(), and GetVarArgRegs().
IsO32()
bool llvm::MipsABIInfo::IsO32 () const inline
Definition at line 36 of file MipsABIInfo.h.
References O32, and ThisABI.
Referenced by GetByValArgRegs(), GetCalleeAllocdArgSizeInBytes(), and GetVarArgRegs().
N32()
MipsABIInfo llvm::MipsABIInfo::N32 () inline static
Definition at line 31 of file MipsABIInfo.h.
References MipsABIInfo(), and N32.
N64()
MipsABIInfo llvm::MipsABIInfo::N64 () inline static
Definition at line 32 of file MipsABIInfo.h.
References MipsABIInfo(), and N64.
O32()
MipsABIInfo llvm::MipsABIInfo::O32 () inline static
Definition at line 30 of file MipsABIInfo.h.
References MipsABIInfo(), and O32.
operator<()
bool llvm::MipsABIInfo::operator< (const MipsABIInfo Other) const inline
Ordering of ABI's MipsGenSubtargetInfo.inc will use this to resolve conflicts when given multiple ABI options.
Definition at line 55 of file MipsABIInfo.h.
References GetEnumValue(), MipsABIInfo(), and ThisABI.
Unknown()
MipsABIInfo llvm::MipsABIInfo::Unknown () inline static
Definition at line 29 of file MipsABIInfo.h.
References MipsABIInfo(), and Unknown.
Member Data Documentation
ThisABI
ABI llvm::MipsABIInfo::ThisABI protected
Definition at line 24 of file MipsABIInfo.h.
Referenced by GetEnumValue(), IsEABI(), IsKnown(), IsN32(), IsN64(), IsO32(), MipsABIInfo(), and operator<().
The documentation for this class was generated from the following files:
MipsABIInfo.h
MipsABIInfo.cpp