LLVM: llvm::PMStack Class Reference
LLVM API Documentation
llvm::PMStack Class Reference
#include <LegacyPassManagers.h>
Public Types
typedef std::vector< PMDataManager * >::const_reverse_iterator iterator
Public Member Functions
iterator begin () const
iterator end () const
void pop ()
PMDataManager * top () const
void push (PMDataManager *PM)
bool empty () const
void dump () const
Detailed Description
PMStack - This class implements a stack data structure of PMDataManager pointers.
Top level pass managers (see PassManager.cpp) maintain active Pass Managers using PMStack. Each Pass implements assignPassManager() to connect itself with appropriate manager. assignPassManager() walks PMStack to find suitable manager.
Definition at line 144 of file LegacyPassManagers.h.
Member Typedef Documentation
iterator
typedef std::vector<PMDataManager*>::const_reverse_iterator llvm::PMStack::iterator
Definition at line 146 of file LegacyPassManagers.h.
Member Function Documentation
begin()
iterator llvm::PMStack::begin () const inline
Definition at line 147 of file LegacyPassManagers.h.
Referenced by llvm::PMDataManager::populateInheritedAnalysis().
dump()
void PMStack::dump () const
Definition at line 1825 of file LegacyPassManager.cpp.
References llvm::dbgs(), and I.
empty()
bool llvm::PMStack::empty () const inline
Definition at line 153 of file LegacyPassManagers.h.
Referenced by llvm::BasicBlockPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::LoopPass::assignPassManager(), llvm::ModulePass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::LoopPass::preparePassManager(), llvm::RegionPass::preparePassManager(), and push().
end()
iterator llvm::PMStack::end () const inline
Definition at line 148 of file LegacyPassManagers.h.
Referenced by llvm::PMDataManager::populateInheritedAnalysis().
pop()
void PMStack::pop ()
Definition at line 1792 of file LegacyPassManager.cpp.
References llvm::PMDataManager::initializeAnalysisInfo(), and top().
Referenced by llvm::CallGraphSCCPass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::LoopPass::assignPassManager(), llvm::ModulePass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::LoopPass::preparePassManager(), and llvm::RegionPass::preparePassManager().
push()
void PMStack::push (PMDataManager * PM)
Definition at line 1801 of file LegacyPassManager.cpp.
References llvm::PMTopLevelManager::addIndirectPassManager(), empty(), llvm::PMDataManager::getDepth(), llvm::PMDataManager::getPassManagerType(), llvm::PMT_FunctionPassManager, llvm::PMT_ModulePassManager, llvm::PMDataManager::setDepth(), llvm::PMDataManager::setTopLevelManager(), and top().
Referenced by llvm::BasicBlockPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::LoopPass::assignPassManager(), and llvm::RegionPass::assignPassManager().
top()
PMDataManager * llvm::PMStack::top () const inline
Definition at line 151 of file LegacyPassManagers.h.
Referenced by llvm::BasicBlockPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::LoopPass::assignPassManager(), llvm::ModulePass::assignPassManager(), llvm::RegionPass::assignPassManager(), pop(), llvm::LoopPass::preparePassManager(), llvm::RegionPass::preparePassManager(), and push().
The documentation for this class was generated from the following files:
LegacyPassManagers.h
LegacyPassManager.cpp