LLVM: llvm::SmallVectorTemplateBase< T, isPodLike > Class Template Reference
LLVM API Documentation
llvm::SmallVectorTemplateBase< T, isPodLike > Class Template Reference
#include <SmallVector.h>
Inherits llvm::SmallVectorTemplateCommon< T, typename >.
Inherited by llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >, llvm::const_iterator<>, llvm::iterator< SDep >, llvm::const_iterator< SDep >, llvm::iterator<>, llvm::SmallVectorImpl< std::unique_ptr< UnitType > >, llvm::const_iterator< DICompileUnit >, llvm::const_iterator< DISubprogram >, llvm::const_iterator< DIGlobalVariable >, llvm::const_iterator< DIType >, llvm::const_iterator< DIScope >, llvm::const_iterator<>, llvm::iterator<>, llvm::const_iterator< MCFixup >, llvm::iterator< MCFixup >, llvm::iterator< MCOperand >, llvm::const_iterator< MCOperand >, llvm::SmallVectorImpl< MCSymbol * >, llvm::SmallVectorImpl< MCLOHDirective >, llvm::SmallVectorImpl< std::unique_ptr< MCParsedAsmOperand > >, llvm::const_iterator<>, llvm::const_iterator<>, llvm::SmallVectorImpl< const TargetRegisterClass * >, llvm::SmallVectorImpl< BBInfo * >, llvm::iterator< InstructionAndIdx >, llvm::iterator<>, llvm::iterator<>, llvm::SmallVectorImpl< const MachineInstr * >, llvm::iterator<>, llvm::const_iterator<>, llvm::iterator<>, llvm::const_iterator<>, llvm::const_iterator< IVInc >, llvm::iterator< Slice >, and llvm::const_iterator< Slice >.
Public Member Functions
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
void emplace_back ()
template<typename T1>
void emplace_back (T1 &&A1)
template<typename T1, typename T2>
void emplace_back (T1 &&A1, T2 &&A2)
template<typename T1, typename T2, typename T3>
void emplace_back (T1 &&A1, T2 &&A2, T3 &&A3)
template<typename T1, typename T2, typename T3, typename T4>
void emplace_back (T1 &&A1, T2 &&A2, T3 &&A3, T4 &&A4)
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
size_type max_size () const
size_t capacity () const
Return the total number of elements in the currently allocated buffer.
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase
size_t size_in_bytes () const
This returns size()*sizeof(T).
size_t capacity_in_bytes () const
capacity_in_bytes - This returns capacity()*sizeof(T).
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
Protected Member Functions
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSizeInBytes, size_t TSize)
bool isSmall () const
void resetToSmall ()
Put this vector in a state of being small.
void setEnd (T *P)
iterator capacity_ptr ()
const_iterator capacity_ptr () const
Protected Member Functions inherited from llvm::SmallVectorBase
SmallVectorBase (void *FirstEl, size_t Size)
void grow_pod (void *FirstEl, size_t MinSizeInBytes, size_t TSize)
Static Protected Member Functions
static void destroy_range (T *S, T *E)
template<typename It1, typename It2>
static It2 move (It1 I, It1 E, It2 Dest)
template<typename It1, typename It2>
static It2 move_backward (It1 I, It1 E, It2 Dest)
template<typename It1, typename It2>
static void uninitialized_move (It1 I, It1 E, It2 Dest)
template<typename It1, typename It2>
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Additional Inherited Members
Public Types inherited from llvm::SmallVectorTemplateCommon< T, typename >
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
Protected Attributes inherited from llvm::SmallVectorBase
void * BeginX
void * EndX
void * CapacityX
Detailed Description
template<typename T, bool isPodLike>
class llvm::SmallVectorTemplateBase< T, isPodLike >
SmallVectorTemplateBase<isPodLike = false> - This is where we put method implementations that are designed to work with non-POD-like T's.
Definition at line 168 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorTemplateBase()
template<typename T, bool isPodLike> llvm::SmallVectorTemplateBase< T, isPodLike >::SmallVectorTemplateBase (size_t Size) inline protected
Definition at line 170 of file SmallVector.h.
Referenced by llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::SmallVectorImpl().
Member Function Documentation
destroy_range()
template<typename T, bool isPodLike> void llvm::SmallVectorTemplateBase< T, isPodLike >::destroy_range (T * S, T * E) inline static protected
Definition at line 172 of file SmallVector.h.
Referenced by llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::clear(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::erase(), grow(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::resize(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::resize(), llvm::SmallVectorImpl< T >::swap(), and llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::~SmallVectorImpl().
emplace_back() [1/5]
template<typename T, bool isPodLike> void llvm::SmallVectorTemplateBase< T, isPodLike >::emplace_back () inline
Definition at line 257 of file SmallVector.h.
Referenced by createImportedModule().
emplace_back() [2/5]
template<typename T, bool isPodLike> template<typename T1> void llvm::SmallVectorTemplateBase< T, isPodLike >::emplace_back (T1 && A1) inline
Definition at line 260 of file SmallVector.h.
emplace_back() [3/5]
template<typename T, bool isPodLike> template<typename T1, typename T2> void llvm::SmallVectorTemplateBase< T, isPodLike >::emplace_back (T1 && A1, T2 && A2) inline
Definition at line 263 of file SmallVector.h.
emplace_back() [4/5]
template<typename T, bool isPodLike> template<typename T1, typename T2, typename T3> void llvm::SmallVectorTemplateBase< T, isPodLike >::emplace_back (T1 && A1, T2 && A2, T3 && A3) inline
Definition at line 269 of file SmallVector.h.
emplace_back() [5/5]
template<typename T, bool isPodLike> template<typename T1, typename T2, typename T3, typename T4> void llvm::SmallVectorTemplateBase< T, isPodLike >::emplace_back (T1 && A1, T2 && A2, T3 && A3, T4 && A4) inline
Definition at line 277 of file SmallVector.h.
grow()
template<typename T, bool isPodLike> void llvm::SmallVectorTemplateBase< T, isPodLike >::grow (size_t MinSize = 0) protected
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory. Guarantees space for at least one more element, or MinSize more elements if specified.
Definition at line 288 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::BeginX, llvm::SmallVectorTemplateCommon< T, typename >::capacity(), llvm::SmallVectorBase::CapacityX, destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateCommon< T, typename >::isSmall(), llvm::NextPowerOf2(), llvm::SmallVectorTemplateCommon< T, typename >::setEnd(), llvm::SmallVectorTemplateCommon< T, typename >::size(), T, and uninitialized_move().
Referenced by llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::append(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::append(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::assign(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::reserve(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::resize(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::resize(), and llvm::SmallVectorImpl< T >::swap().
move()
template<typename T, bool isPodLike> template<typename It1, typename It2> It2 llvm::SmallVectorTemplateBase< T, isPodLike >::move (It1 I, It1 E, It2 Dest) inline static protected
Use move-assignment to move the range [I, E) onto the objects starting with "Dest". This is just <memory>'s std::move, but not all stdlibs actually provide that.
Definition at line 183 of file SmallVector.h.
Referenced by llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::erase(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::erase(), and llvm::SmallVectorImpl< T >::operator=().
move_backward()
template<typename T, bool isPodLike> template<typename It1, typename It2> It2 llvm::SmallVectorTemplateBase< T, isPodLike >::move_backward (It1 I, It1 E, It2 Dest) inline static protected
Use move-assignment to move the range [I, E) onto the objects ending at "Dest", moving objects in reverse order. This is just <algorithm>'s std::move_backward, but not all stdlibs actually provide that.
Definition at line 194 of file SmallVector.h.
Referenced by llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), and llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert().
pop_back()
template<typename T, bool isPodLike> void llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back () inline
Definition at line 235 of file SmallVector.h.
Referenced by llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), advanceToNextLeafType(), llvm::MipsInstrInfo::AnalyzeBranch(), llvm::A57ChainingConstraint::apply(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), BuildSubAggregate(), llvm::c_str(), ComputePostOrders(), llvm::ConstantFoldTerminator(), createUniqueEntity(), llvm::ScheduleDAGSDNodes::dumpNode(), EliminateDeadSwitchCases(), EmitAddTreeOfValues(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::erase(), llvm::DominatorTreeBase< BlockT >::Eval, extendSegmentsToUses(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::Intrinsic::getType(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::pop_back_val(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::Inliner::runOnSCC(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::SplitCriticalEdge(), llvm::Twine::toNullTerminatedStringRef(), and llvm::DominatorTreeBase< BlockT >::updateDFSNumbers().
push_back() [1/2]
template<typename T, bool isPodLike> void llvm::SmallVectorTemplateBase< T, isPodLike >::push_back (const T & Elt) inline
Definition at line 221 of file SmallVector.h.
Referenced by llvm::PMDataManager::add(), AddAliasScopeMetadata(), llvm::opt::ArgList::AddAllArgsTranslated(), llvm::opt::ArgList::AddAllArgValues(), llvm::AttributeSet::addAttributes(), addBlockAndPredsToSet(), AddCombineTo64bitMLAL(), AddCombineToVPADDL(), llvm::SchedDFSImpl::addConnection(), AddGlue(), llvm::LiveIntervals::addKillFlags(), llvm::AddLandingPadInfo(), AddOperand(), addRange(), AddReachableCodeToWorklist(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::DwarfFile::addScopeVariable(), addStackMapLiveVars(), advanceToNextLeafType(), llvm::StatepointLoweringState::allocateStackSlot(), llvm::LoopInfoBase< BlockT, LoopT >::Analyze(), llvm::ARMBaseInstrInfo::AnalyzeBranch(), llvm::HexagonInstrInfo::AnalyzeBranch(), llvm::MipsInstrInfo::AnalyzeBranch(), llvm::MSP430InstrInfo::AnalyzeBranch(), llvm::NVPTXInstrInfo::AnalyzeBranch(), llvm::PPCInstrInfo::AnalyzeBranch(), llvm::R600InstrInfo::AnalyzeBranch(), llvm::SparcInstrInfo::AnalyzeBranch(), llvm::SystemZInstrInfo::AnalyzeBranch(), llvm::X86InstrInfo::AnalyzeBranch(), llvm::XCoreInstrInfo::AnalyzeBranch(), llvm::CCState::analyzeMustTailForwardedRegisters(), llvm::ARMBaseInstrInfo::analyzeSelect(), llvm::sys::path::append(), appendToGlobalArray(), llvm::A57ChainingConstraint::apply(), AreAnyUnderlyingObjectsAnAlloca(), BitCastConstantVector(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildFromShuffleMostly(), buildGraphFrom(), buildSetsFrom(), BuildSubAggregate(), llvm::c_str(), CalculateTailCallArgDest(), canWidenShuffleElements(), CastGEPIndices(), llvm::CC_ARM_AAPCS_Custom_HA(), ChangeVSETULTtoVSETULE(), CheckForLiveRegDef(), CheckForLiveRegDef(), CheckForLiveRegDefMasked(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), llvm::cleanseInlinedVariable(), CloneAliasScopeMetadata(), llvm::CloneAndPruneFunctionInto(), llvm::CloneFunctionInto(), CloneLoopBlocks(), cloneMDTuple(), CloneNodeWithValues(), CollectAddOperandsWithScales(), collectDebugValues(), llvm::CodeMetrics::collectEphemeralValues(), llvm::CodeMetrics::collectEphemeralValues(), llvm::PMTopLevelManager::collectLastUses(), llvm::PMDataManager::collectRequiredAnalysis(), CollectShuffleElements(), CollectSingleShuffleElements(), CollectSubexprs(), CombineBaseUpdate(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), completeEphemeralValues(), llvm::SCEVAddRecExpr::computeAccessFunctions(), llvm::EHStreamer::computeActionsTable(), computeADRP(), llvm::EHStreamer::computeCallSiteTable(), computeOthers(), ComputePostOrders(), ComputePTXValueVTs(), llvm::ComputeValueVTs(), llvm::ConstantAggrKeyType< ConstantArray >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), ConstantFold(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), ConstantFoldConstantExpressionImpl(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantFoldInstruction(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::ConstantFoldTerminator(), ConstHasGlobalValuePredicate(), llvm::LiveInterval::constructMainRangeFromSubranges(), llvm::DwarfCompileUnit::constructScopeDIE(), containsConstantSomewhere(), llvm::StructType::create(), llvm::MDBuilder::createAnonymousAARoot(), llvm::createInlinedVariable(), createTypeWithFlags(), createUniqueEntity(), llvm::DecodeBLENDMask(), DecodeIITType(), llvm::DecodeINSERTPSMask(), llvm::DecodeMOVHLPSMask(), llvm::DecodeMOVLHPSMask(), llvm::DecodeMOVSHDUPMask(), llvm::DecodeMOVSLDUPMask(), llvm::DecodePALIGNRMask(), llvm::DecodePSHUFBMask(), llvm::DecodePSHUFBMask(), llvm::DecodePSHUFHWMask(), llvm::DecodePSHUFLWMask(), llvm::DecodePSHUFMask(), llvm::DecodePSLLDQMask(), llvm::DecodePSRLDQMask(), llvm::DecodeSHUFPMask(), llvm::DecodeUNPCKHMask(), llvm::DecodeUNPCKLMask(), llvm::DecodeVPERM2X128Mask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMMask(), DecomposeGEPExpression(), DeleteDeadInstruction(), deleteDeadInstruction(), llvm::DeleteDeadPHIs(), DeleteTriviallyDeadInstructions(), determinePointerReadAttrs(), llvm::DominatorTreeBase< BlockT >::DFSPass, llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::BlockFrequencyInfoImplBase::distributeMass(), DoInitialMatch(), llvm::DWARFAcceleratorTable::dump(), llvm::ScheduleDAGSDNodes::dumpNode(), llvm::LiveRangeEdit::eliminateDeadDefs(), EliminateDeadSwitchCases(), llvm::AsmPrinter::EmitConstantPool(), EmitDarwinBCHeaderAndTrailer(), llvm::EHStreamer::emitExceptionTable(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::SystemZFrameLowering::emitPrologue(), llvm::ScheduleDAGSDNodes::EmitSchedule(), emitSignedInt64(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), encodeUTF8(), enqueueUsersInWorklist(), llvm::DominatorTreeBase< BlockT >::Eval, EvaluateStoreInto(), ExpandBVWithShuffles(), ExpandUnalignedLoad(), ExpandUnalignedStore(), extendSegmentsToUses(), ExtendUsesToFormExtLoad(), extractVector(), llvm::SelectionDAG::ExtractVectorElements(), llvm::DIBuilder::finalize(), llvm::StringTableBuilder::finalize(), llvm::MCJIT::finalizeObject(), llvm::ScalarEvolution::findArrayDimensions(), findArrayDimensionsRec(), findCallees(), findConsecutiveLoad(), llvm::objcarc::FindDependencies(), llvm::FindFunctionBackedges(), llvm::SlotIndexes::findLiveInMBBs(), FindMostPopularDest(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::FindPredecessorBlocks(), llvm::SSAUpdaterTraits< SSAUpdater >::FindPredecessorBlocks(), llvm::ScheduleDAGMI::findRootsAndBiasEdges(), FindSingleUseMultiplyFactors(), llvm::MachineInstr::findTiedOperandIdx(), FindUnconditionalPreds(), llvm::SplitEditor::finish(), firstRealType(), FoldBitCast(), FoldBitCast(), llvm::FoldBranchToCommonDest(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ScalarEvolution::forgetValue(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), GenerateTBL(), genMadd(), genMaddR(), llvm::AttributeSet::get(), llvm::AttributeSet::get(), llvm::ConstantStruct::get(), llvm::StructType::get(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAnyExtendExpr(), getArrayElements(), llvm::ConstantExpr::getAsInstruction(), llvm::ScalarEvolution::getBlockDisposition(), GetBranchWeights(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCommutedVectorShuffle(), llvm::SelectionDAG::getConstant(), getCopyToPartsVector(), getDataDeps(), llvm::DominatorTreeBase< BlockT >::getDescendants(), GetEHSpillList(), getExactSDiv(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::LoopBase< BlockT, LoopT >::getExitEdges(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::cl::generic_parser_base::getExtraOptionNames(), llvm::X86AddressMode::getFullAddress(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::MachineInstrExpressionTrait::getHashValue(), getIncomingStatepointGCValues(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::DWARFContext::getLineInfoForAddressRange(), getLogBase2Vector(), llvm::ScalarEvolution::getLoopDisposition(), llvm::LoopBase< BlockT, LoopT >::getLoopLatches(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::SelectionDAG::getMergeValues(), llvm::SourceMgr::GetMessage(), llvm::MDNode::getMostGenericAliasScope(), llvm::MDNode::getMostGenericRange(), llvm::MDNode::getMostGenericTBAA(), getMOVL(), llvm::ScalarEvolution::getMulExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::ScalarEvolution::getMulExpr(), getNaturalGEPRecursively(), getNaturalGEPWithOffset(), getNaturalGEPWithType(), llvm::SelectionDAG::getNode(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), llvm::MipsTargetLowering::getOpndList(), GetOptionInfo(), llvm::DIBuilder::getOrCreateTypeArray(), llvm::AMDGPUTargetLowering::getOriginalFunctionArgs(), llvm::DwarfUnit::getParentContextString(), getPHIDeps(), getPossibleTargets(), llvm::PredIteratorCache::GetPreds(), getPreStartForSignExtend(), getPSHUFB(), getReadPerformanceCounter(), getReadTimeStampCounter(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), GetRegistersForValue(), llvm::TargetInstrInfo::getRegSequenceInputs(), llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs(), llvm::CCState::getRemainingRegParmsForType(), getReturnAttrs(), getReturnAttrs(), llvm::GetReturnInfo(), llvm::ScalarEvolution::getSCEVAtScope(), llvm::ShuffleVectorInst::getShuffleMask(), getShuffleVectorZeroOrUndef(), llvm::ScalarEvolution::getSMaxExpr(), GetSpillList(), llvm::R600InstrInfo::getSrcs(), llvm::SelectionDAG::getStackArgumentTokenFactor(), llvm::ConstantDataArray::getString(), getTargetShuffleMask(), getTargetVShiftByConstNode(), getTargetVShiftNode(), llvm::Intrinsic::getType(), llvm::ScalarEvolution::getUMaxExpr(), llvm::GetUnderlyingObjects(), getUnderlyingObjects(), getUnderlyingObjectsForInstr(), llvm::Loop::getUniqueExitBlocks(), getUnpackh(), getUnpackl(), llvm::yaml::ScalarNode::getValue(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::SelectionDAG::getVectorShuffle(), llvm::ConstantExpr::getWithOperandReplaced(), HandleMergeInputChains(), llvm::AArch64InstrInfo::hasPattern(), llvm::SDNode::hasPredecessorHelper(), llvm::SCEVExpander::hoistIVInc(), llvm::ValueEnumerator::incorporateFunction(), llvm::InlineFunction(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::LazyCallGraph::SCC::insertIncomingEdge(), llvm::InsertPreheaderForLoop(), insertVector(), llvm::MDNode::intersect(), llvm::MachineTraceMetrics::Ensemble::invalidate(), isAllocSiteRemovable(), llvm::LazyCallGraph::SCC::isDescendantOf(), isEphemeralValueOf(), isLeakCheckerRoot(), llvm::LiveVariables::isLiveOut(), isLoadIncOrDecStore(), isOnlyCopiedFromConstantGlobal(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachable(), isProfitableToFoldUnconditional(), IsStoredObjCPointer(), IsValueFullyAvailableInBlock(), isVectorPromotionViable(), llvm::LazyCallGraph::LazyCallGraph(), llvm::SITargetLowering::legalizeTargetIndependentNode(), LinearizeExprTree(), LLVMMDNodeInContext(), llvm::X86InstrInfo::loadRegFromAddr(), LookupNearestOption(), LowerAsSplatVectorLoad(), LowerBITCAST(), llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::LowerDbgDeclare(), lowerDSPIntr(), LowerExtendedLoad(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), lowerIncomingStatepointValue(), LowerINTRINSIC_W_CHAIN(), LowerMemOpCallTo(), llvm::R600TargetLowering::LowerOperation(), llvm::MipsTargetLowering::LowerOperationWrapper(), llvm::TargetLowering::LowerOperationWrapper(), llvm::HexagonTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), llvm::MSP430TargetLowering::LowerSELECT_CC(), llvm::MSP430TargetLowering::LowerSETCC(), LowerShift(), lowerStatepointMetaArgs(), llvm::AMDGPUTargetLowering::LowerUDIVREM64(), lowerV8I16BasicBlendVectorShuffle(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE_256(), lowerVECTOR_SHUFFLE_VSHF(), LowerVECTOR_SHUFFLEv16i8(), LowerVECTOR_SHUFFLEv8i16(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllZeroTest(), lowerVectorShuffleAsLanePermuteAndBlend(), mangleCoveragePath(), llvm::MapValue(), markAliveBlocks(), llvm::Regex::match(), llvm::SelectionDAG::MorphNodeTo(), MoveBelowOrigChain(), llvm::SIInstrInfo::moveToVALU(), llvm::Triple::normalize(), NormalizeBuildVector(), OptimizeAwayTrappingUsesOfValue(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeLoadInstr(), OptimizeVectorResize(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLocDWO::parse(), parseBackslash(), llvm::cl::ParseCommandLineOptions(), parseCondBranch(), llvm::cl::ParseEnvironmentOptions(), ParseFunctionArgs(), partitionShuffleOfConcats(), PerformBUILD_VECTORCombine(), llvm::SITargetLowering::PerformDAGCombine(), PerformEXTRACT_VECTOR_ELTCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), PerformShuffleCombine(), PerformSTORECombine(), PerformSTORECombine(), PerformVECTOR_SHUFFLECombine(), llvm::PointerMayBeCaptured(), PrepareCall(), llvm::MachineInstr::print(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), processInstruction(), promoteSingleBlockAlloca(), llvm::LiveIntervals::pruneValue(), PushDefUseChildren(), PushLoopPHIs(), RegisterOperands::pushRegUnits(), pushValue(), PushValueAndType(), llvm::coverage::RawCoverageMappingReader::read(), llvm::BitstreamCursor::readRecord(), llvm::MachineInstr::readsWritesVirtualRegister(), llvm::object::MachOObjectFile::ReadULEB128s(), llvm::RegPressureTracker::recede(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), registerADRCandidate(), llvm::AttributeSet::removeAttributes(), removeConstantFactors(), llvm::Inliner::removeDeadFunctions(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::SelectionDAG::RemoveDeadNodes(), removeDuplicatesGCPtrs(), llvm::MemoryDependenceAnalysis::removeInstruction(), RemoveUnusedGlue(), llvm::opt::Arg::render(), llvm::opt::Arg::renderAsInput(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), ReplaceBITCASTResults(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::replaceDbgDeclareForAlloca(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::AMDGPUTargetLowering::ReplaceNodeResults(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::XCoreTargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::ConstantVector::replaceUsesOfWithOnConstant(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), RewriteAsNarrowerShuffle(), RewriteHeapSROALoadUser(), RewriteIntelBracExpression(), rewriteLoopExitBlock(), rewriteNonInstructionUses(), llvm::LoadAndStorePromoter::run(), llvm::NVPTXLowerAggrCopies::runOnFunction(), llvm::Inliner::runOnSCC(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), separateNestedLoop(), llvm::StructType::setBody(), llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), llvm::PMTopLevelManager::setLastUser(), SetLoopAlreadyUnrolled(), llvm::StructType::setName(), setUsedInitializer(), llvm::LiveIntervals::shrinkToUses(), llvm::LiveIntervals::shrinkToUses(), SimplifyAddOperands(), SimplifyCall(), SimplifyCondBranchToCondBranch(), llvm::simplifyLoop(), simplifyOneLoop(), simplifyShuffleOperandRecursively(), SimplifyWithOpReplaced(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SplitAddRecs(), splitAndLowerVectorShuffle(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), llvm::SplitString(), SRAGlobal(), llvm::LivePhysRegs::stepForward(), llvm::X86InstrInfo::storeRegToAddr(), StoreTailCallArgumentsToStackSlot(), SwitchToLookupTable(), SymbolicallyEvaluateGEP(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::Twine::toNullTerminatedStringRef(), llvm::APFloat::toString(), llvm::APInt::toString(), trackCyclesUnderDistinct(), TrackDefUses(), llvm::SelectionDAG::TransferDbgValues(), llvm::tryFoldSPUpdateIntoPushPop(), tryToFoldExtendOfConstant(), TryToSimplifyUncondBranchWithICmpInIt(), TurnSwitchRangeIntoICmp(), llvm::IntEqClasses::uncompress(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::SelectionDAG::UnrollVectorOp(), llvm::DominatorTreeBase< BlockT >::updateDFSNumbers(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), llvm::UpgradeIntrinsicCall(), verifyCTRBranch(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractValueInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitShuffleVectorInst(), visitUDivOperand(), WalkChainUsers(), writeComdats(), WriteFunction(), WriteInstruction(), WriteModule(), WriteModuleInfo(), WriteStringRecord(), WriteTypeTable(), WriteValueSymbolTable(), and llvm::LLVMContextImpl::~LLVMContextImpl().
push_back() [2/2]
template<typename T, bool isPodLike> void llvm::SmallVectorTemplateBase< T, isPodLike >::push_back (T && Elt) inline
Definition at line 228 of file SmallVector.h.
uninitialized_copy()
template<typename T, bool isPodLike> template<typename It1, typename It2> void llvm::SmallVectorTemplateBase< T, isPodLike >::uninitialized_copy (It1 I, It1 E, It2 Dest) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 211 of file SmallVector.h.
Referenced by llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::swap(), and llvm::SmallVectorTemplateBase< T, true >::uninitialized_move().
uninitialized_move()
template<typename T, bool isPodLike> template<typename It1, typename It2> void llvm::SmallVectorTemplateBase< T, isPodLike >::uninitialized_move (It1 I, It1 E, It2 Dest) inline static protected
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 203 of file SmallVector.h.
Referenced by grow(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), and llvm::SmallVectorImpl< T >::operator=().
The documentation for this class was generated from the following file:
SmallVector.h