LLVM: llvm::TableGenStringKey Class Reference
LLVM API Documentation
llvm::TableGenStringKey Class Reference
Public Member Functions
TableGenStringKey (const std::string &str)
TableGenStringKey (const char *str)
const std::string & str () const
Friends
hash_code hash_value (const TableGenStringKey &Value)
Detailed Description
TableGenStringKey - This is a wrapper for std::string suitable for using as a key to a DenseMap. Because there isn't a particularly good way to indicate tombstone or empty keys for strings, we want to wrap std::string to indicate that this is a "special" string not expected to take on certain values (those of the tombstone and empty keys). This makes things a little safer as it clarifies that DenseMap is really not appropriate for general strings.
Definition at line 43 of file Record.cpp.
Constructor & Destructor Documentation
TableGenStringKey() [1/2]
llvm::TableGenStringKey::TableGenStringKey (const std::string & str) inline
Definition at line 45 of file Record.cpp.
References str().
Referenced by hash_value.
TableGenStringKey() [2/2]
llvm::TableGenStringKey::TableGenStringKey (const char * str) inline
Definition at line 46 of file Record.cpp.
References str().
Member Function Documentation
str()
const std::string & llvm::TableGenStringKey::str () const inline
Definition at line 48 of file Record.cpp.
Referenced by llvm::DenseMapInfo< TableGenStringKey >::isEqual(), TableGenStringKey(), and TableGenStringKey().
Friends And Related Symbol Documentation
hash_value
hash_code hash_value (const TableGenStringKey & Value) friend
Definition at line 50 of file Record.cpp.
References llvm::hash_value(), hash_value, and TableGenStringKey().
Referenced by hash_value.
The documentation for this class was generated from the following file:
Record.cpp