LLVM: llvm::FoldingSetBucketIteratorImpl Class Reference
LLVM API Documentation
llvm::FoldingSetBucketIteratorImpl Class Reference
#include <FoldingSet.h>
Public Member Functions
bool operator== (const FoldingSetBucketIteratorImpl &RHS) const
bool operator!= (const FoldingSetBucketIteratorImpl &RHS) const
Protected Member Functions
FoldingSetBucketIteratorImpl (void **Bucket)
FoldingSetBucketIteratorImpl (void **Bucket, bool)
void advance ()
Protected Attributes
void * Ptr
Detailed Description
FoldingSetBucketIteratorImpl - This is the common bucket iterator support shared by all folding sets, which knows how to walk a particular bucket of a folding set hash table.
Definition at line 685 of file FoldingSet.h.
Constructor & Destructor Documentation
FoldingSetBucketIteratorImpl() [1/2]
FoldingSetBucketIteratorImpl::FoldingSetBucketIteratorImpl (void ** Bucket) explicit protected
Definition at line 422 of file FoldingSet.cpp.
References GetNextPtr(), and Ptr.
Referenced by llvm::FoldingSetBucketIterator< T >::FoldingSetBucketIterator(), llvm::FoldingSetBucketIterator< T >::FoldingSetBucketIterator(), operator!=(), and operator==().
FoldingSetBucketIteratorImpl() [2/2]
llvm::FoldingSetBucketIteratorImpl::FoldingSetBucketIteratorImpl (void ** Bucket, bool) inline protected
Definition at line 691 of file FoldingSet.h.
References Ptr.
Member Function Documentation
advance()
void llvm::FoldingSetBucketIteratorImpl::advance () inline protected
Definition at line 694 of file FoldingSet.h.
References Ptr.
Referenced by llvm::FoldingSetBucketIterator< T >::operator++().
operator!=()
bool llvm::FoldingSetBucketIteratorImpl::operator!= (const FoldingSetBucketIteratorImpl & RHS) const inline
Definition at line 704 of file FoldingSet.h.
References FoldingSetBucketIteratorImpl(), and Ptr.
operator==()
bool llvm::FoldingSetBucketIteratorImpl::operator== (const FoldingSetBucketIteratorImpl & RHS) const inline
Definition at line 701 of file FoldingSet.h.
References FoldingSetBucketIteratorImpl(), and Ptr.
Member Data Documentation
Ptr
void* llvm::FoldingSetBucketIteratorImpl::Ptr protected
Definition at line 687 of file FoldingSet.h.
Referenced by advance(), FoldingSetBucketIteratorImpl(), FoldingSetBucketIteratorImpl(), operator!=(), llvm::FoldingSetBucketIterator< T >::operator*(), llvm::FoldingSetBucketIterator< T >::operator->(), and operator==().
The documentation for this class was generated from the following files:
FoldingSet.h
FoldingSet.cpp