LLVM: llvm::MCSymbolRefExpr Class Reference
LLVM API Documentation
llvm::MCSymbolRefExpr Class Reference
#include <MCExpr.h>
Public Types
enum VariantKind {
VK_None , VK_Invalid , VK_GOT , VK_GOTOFF ,
VK_GOTPCREL , VK_GOTTPOFF , VK_INDNTPOFF , VK_NTPOFF ,
VK_GOTNTPOFF , VK_PLT , VK_TLSGD , VK_TLSLD ,
VK_TLSLDM , VK_TPOFF , VK_DTPOFF , VK_TLVP ,
VK_TLVPPAGE , VK_TLVPPAGEOFF , VK_PAGE , VK_PAGEOFF ,
VK_GOTPAGE , VK_GOTPAGEOFF , VK_SECREL , VK_WEAKREF ,
VK_ARM_NONE , VK_ARM_TARGET1 , VK_ARM_TARGET2 , VK_ARM_PREL31 ,
VK_ARM_SBREL , VK_ARM_TLSLDO , VK_ARM_TLSCALL , VK_ARM_TLSDESC ,
VK_ARM_TLSDESCSEQ , VK_PPC_LO , VK_PPC_HI , VK_PPC_HA ,
VK_PPC_HIGHER , VK_PPC_HIGHERA , VK_PPC_HIGHEST , VK_PPC_HIGHESTA ,
VK_PPC_GOT_LO , VK_PPC_GOT_HI , VK_PPC_GOT_HA , VK_PPC_TOCBASE ,
VK_PPC_TOC , VK_PPC_TOC_LO , VK_PPC_TOC_HI , VK_PPC_TOC_HA ,
VK_PPC_DTPMOD , VK_PPC_TPREL , VK_PPC_TPREL_LO , VK_PPC_TPREL_HI ,
VK_PPC_TPREL_HA , VK_PPC_TPREL_HIGHER , VK_PPC_TPREL_HIGHERA , VK_PPC_TPREL_HIGHEST ,
VK_PPC_TPREL_HIGHESTA , VK_PPC_DTPREL , VK_PPC_DTPREL_LO , VK_PPC_DTPREL_HI ,
VK_PPC_DTPREL_HA , VK_PPC_DTPREL_HIGHER , VK_PPC_DTPREL_HIGHERA , VK_PPC_DTPREL_HIGHEST ,
VK_PPC_DTPREL_HIGHESTA , VK_PPC_GOT_TPREL , VK_PPC_GOT_TPREL_LO , VK_PPC_GOT_TPREL_HI ,
VK_PPC_GOT_TPREL_HA , VK_PPC_GOT_DTPREL , VK_PPC_GOT_DTPREL_LO , VK_PPC_GOT_DTPREL_HI ,
VK_PPC_GOT_DTPREL_HA , VK_PPC_TLS , VK_PPC_GOT_TLSGD , VK_PPC_GOT_TLSGD_LO ,
VK_PPC_GOT_TLSGD_HI , VK_PPC_GOT_TLSGD_HA , VK_PPC_TLSGD , VK_PPC_GOT_TLSLD ,
VK_PPC_GOT_TLSLD_LO , VK_PPC_GOT_TLSLD_HI , VK_PPC_GOT_TLSLD_HA , VK_PPC_TLSLD ,
VK_PPC_LOCAL , VK_Mips_GPREL , VK_Mips_GOT_CALL , VK_Mips_GOT16 ,
VK_Mips_GOT , VK_Mips_ABS_HI , VK_Mips_ABS_LO , VK_Mips_TLSGD ,
VK_Mips_TLSLDM , VK_Mips_DTPREL_HI , VK_Mips_DTPREL_LO , VK_Mips_GOTTPREL ,
VK_Mips_TPREL_HI , VK_Mips_TPREL_LO , VK_Mips_GPOFF_HI , VK_Mips_GPOFF_LO ,
VK_Mips_GOT_DISP , VK_Mips_GOT_PAGE , VK_Mips_GOT_OFST , VK_Mips_HIGHER ,
VK_Mips_HIGHEST , VK_Mips_GOT_HI16 , VK_Mips_GOT_LO16 , VK_Mips_CALL_HI16 ,
VK_Mips_CALL_LO16 , VK_Mips_PCREL_HI16 , VK_Mips_PCREL_LO16 , VK_COFF_IMGREL32
}
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary , Constant , SymbolRef , Unary ,
Target
}
Public Member Functions
Accessors
const MCSymbol & getSymbol () const
VariantKind getKind () const
void printVariantKind (raw_ostream &OS) const
bool hasSubsectionsViaSymbols () const
Public Member Functions inherited from llvm::MCExpr
ExprKind getKind () const
void print (raw_ostream &OS) const
void dump () const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
bool EvaluateAsAbsolute (int64_t &Res) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
int64_t evaluateKnownAbsolute (const MCAsmLayout &Layout) const
bool EvaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
bool EvaluateAsValue (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
const MCSection * FindAssociatedSection () const
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const MCSymbolRefExpr * Create (const MCSymbol *Symbol, MCContext &Ctx)
static const MCSymbolRefExpr * Create (const MCSymbol *Symbol, VariantKind Kind, MCContext &Ctx)
static const MCSymbolRefExpr * Create (StringRef Name, VariantKind Kind, MCContext &Ctx)
Static Utility Functions
static StringRef getVariantKindName (VariantKind Kind)
static VariantKind getVariantKindForName (StringRef Name)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind _Kind)
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet, bool ForceVarExpansion) const
Detailed Description
MCSymbolRefExpr - Represent a reference to a symbol from inside an expression.
A symbol reference in an expression may be a use of a label, a use of an assembler variable (defined constant), or constitute an implicit definition of the symbol as external.
Definition at line 164 of file MCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::MCSymbolRefExpr::VariantKind
Enumerator
VK_None
VK_Invalid
VK_GOT
VK_GOTOFF
VK_GOTPCREL
VK_GOTTPOFF
VK_INDNTPOFF
VK_NTPOFF
VK_GOTNTPOFF
VK_PLT
VK_TLSGD
VK_TLSLD
VK_TLSLDM
VK_TPOFF
VK_DTPOFF
VK_TLVP
VK_TLVPPAGE
VK_TLVPPAGEOFF
VK_PAGE
VK_PAGEOFF
VK_GOTPAGE
VK_GOTPAGEOFF
VK_SECREL
VK_WEAKREF
VK_ARM_NONE
VK_ARM_TARGET1
VK_ARM_TARGET2
VK_ARM_PREL31
VK_ARM_SBREL
VK_ARM_TLSLDO
VK_ARM_TLSCALL
VK_ARM_TLSDESC
VK_ARM_TLSDESCSEQ
VK_PPC_LO
VK_PPC_HI
VK_PPC_HA
VK_PPC_HIGHER
VK_PPC_HIGHERA
VK_PPC_HIGHEST
VK_PPC_HIGHESTA
VK_PPC_GOT_LO
VK_PPC_GOT_HI
VK_PPC_GOT_HA
VK_PPC_TOCBASE
VK_PPC_TOC
VK_PPC_TOC_LO
VK_PPC_TOC_HI
VK_PPC_TOC_HA
VK_PPC_DTPMOD
VK_PPC_TPREL
VK_PPC_TPREL_LO
VK_PPC_TPREL_HI
VK_PPC_TPREL_HA
VK_PPC_TPREL_HIGHER
VK_PPC_TPREL_HIGHERA
VK_PPC_TPREL_HIGHEST
VK_PPC_TPREL_HIGHESTA
VK_PPC_DTPREL
VK_PPC_DTPREL_LO
VK_PPC_DTPREL_HI
VK_PPC_DTPREL_HA
VK_PPC_DTPREL_HIGHER
VK_PPC_DTPREL_HIGHERA
VK_PPC_DTPREL_HIGHEST
VK_PPC_DTPREL_HIGHESTA
VK_PPC_GOT_TPREL
VK_PPC_GOT_TPREL_LO
VK_PPC_GOT_TPREL_HI
VK_PPC_GOT_TPREL_HA
VK_PPC_GOT_DTPREL
VK_PPC_GOT_DTPREL_LO
VK_PPC_GOT_DTPREL_HI
VK_PPC_GOT_DTPREL_HA
VK_PPC_TLS
VK_PPC_GOT_TLSGD
VK_PPC_GOT_TLSGD_LO
VK_PPC_GOT_TLSGD_HI
VK_PPC_GOT_TLSGD_HA
VK_PPC_TLSGD
VK_PPC_GOT_TLSLD
VK_PPC_GOT_TLSLD_LO
VK_PPC_GOT_TLSLD_HI
VK_PPC_GOT_TLSLD_HA
VK_PPC_TLSLD
VK_PPC_LOCAL
VK_Mips_GPREL
VK_Mips_GOT_CALL
VK_Mips_GOT16
VK_Mips_GOT
VK_Mips_ABS_HI
VK_Mips_ABS_LO
VK_Mips_TLSGD
VK_Mips_TLSLDM
VK_Mips_DTPREL_HI
VK_Mips_DTPREL_LO
VK_Mips_GOTTPREL
VK_Mips_TPREL_HI
VK_Mips_TPREL_LO
VK_Mips_GPOFF_HI
VK_Mips_GPOFF_LO
VK_Mips_GOT_DISP
VK_Mips_GOT_PAGE
VK_Mips_GOT_OFST
VK_Mips_HIGHER
VK_Mips_HIGHEST
VK_Mips_GOT_HI16
VK_Mips_GOT_LO16
VK_Mips_CALL_HI16
VK_Mips_CALL_LO16
VK_Mips_PCREL_HI16
VK_Mips_PCREL_LO16
VK_COFF_IMGREL32
Definition at line 166 of file MCExpr.h.
Member Function Documentation
classof()
bool llvm::MCSymbolRefExpr::classof (const MCExpr * E) inline static
Definition at line 337 of file MCExpr.h.
References llvm::MCExpr::getKind(), and llvm::MCExpr::SymbolRef.
Create() [1/3]
const MCSymbolRefExpr * llvm::MCSymbolRefExpr::Create (const MCSymbol * Symbol, MCContext & Ctx) inline static
Definition at line 306 of file MCExpr.h.
References Create(), and VK_None.
Referenced by llvm::ConstantPool::addEntry(), llvm::DwarfCFIException::beginFunction(), buildSymbolDiff(), Create(), Create(), createPCXRelExprOp(), createSparcMCOperand(), llvm::AsmPrinter::doFinalization(), llvm::AddressPool::emit(), llvm::EmitAbsDifference(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::AsmPrinter::EmitFunctionBody(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), EmitGenDwarfRanges(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJump2Table(), llvm::ARMAsmPrinter::EmitJumpTable(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::EmitLabelDiff(), llvm::AsmPrinter::EmitLabelDifference(), emitLabelOffsetDifference(), llvm::AsmPrinter::EmitLabelPlusOffset(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), emitNonLazySymbolPointer(), emitNonLazySymbolPointer(), llvm::EmitRuntimeFunction(), llvm::EmitSymbolRefWithOfs(), llvm::MCStreamer::EmitSymbolValue(), llvm::EmitUnwindInfo(), llvm::MCObjectStreamer::EmitValueToOffset(), llvm::MCELFStreamer::EmitWeakReference(), llvm::ARMAsmPrinter::EmitXXStructor(), llvm::PPCMCExpr::EvaluateAsRelocatableImpl(), forceExpAbs(), llvm::ARMElfTargetObjectFile::getDebugThreadLocalSymbol(), llvm::TargetLoweringObjectFile::getDebugThreadLocalSymbol(), llvm::SystemZMCInstLower::getExpr(), llvm::MCAsmInfo::getExprForFDESymbol(), llvm::SparcELFMCAsmInfo::getExprForFDESymbol(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::SparcELFMCAsmInfo::getExprForPersonalitySymbol(), llvm::X86_64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::TargetLowering::getPICJumpTableRelocBaseExpr(), llvm::X86TargetLowering::getPICJumpTableRelocBaseExpr(), GetSymbolRef(), GetSymbolRef(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::HexagonLowerToMC(), llvm::MSP430MCInstLower::Lower(), llvm::AMDGPUMCInstLower::lower(), llvm::AsmPrinter::lowerConstant(), llvm::X86TargetLowering::LowerCustomJumpTableEntry(), llvm::AArch64MCInstLower::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), llvm::MSP430MCInstLower::LowerSymbolOperand(), LowerSymbolOperand(), llvm::AArch64MCInstLower::lowerSymbolOperandDarwin(), llvm::AArch64MCInstLower::lowerSymbolOperandELF(), MakeStartMinusEndExpr(), llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::MCExternalSymbolizer::tryAddingSymbolicOperand().
Create() [2/3]
const MCSymbolRefExpr * MCSymbolRefExpr::Create (const MCSymbol * Symbol, VariantKind Kind, MCContext & Ctx) static
Definition at line 158 of file MCExpr.cpp.
Create() [3/3]
const MCSymbolRefExpr * MCSymbolRefExpr::Create (StringRef Name, VariantKind Kind, MCContext & Ctx) static
Definition at line 164 of file MCExpr.cpp.
References Create(), and Name.
getKind()
VariantKind llvm::MCSymbolRefExpr::getKind () const inline
Definition at line 321 of file MCExpr.h.
Referenced by llvm::MCExpr::EvaluateAsRelocatableImpl(), llvm::PPCMCExpr::EvaluateAsRelocatableImpl(), llvm::MCValue::getAccessVariant(), getWeakRef(), HasSecRelSymbolRef(), llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolved(), llvm::MCAssembler::isThumbFunc(), llvm::MCExpr::print(), printExpr(), printExpr(), llvm::PPCInstPrinter::printTLSCall(), and printVariantKind().
getSymbol()
const MCSymbol & llvm::MCSymbolRefExpr::getSymbol () const inline
Definition at line 319 of file MCExpr.h.
Referenced by llvm::MCSymbol::AliasedSymbol(), AttemptToFoldSymbolOffsetDifference(), llvm::MCExpr::EvaluateAsRelocatableImpl(), llvm::PPCMCExpr::EvaluateAsRelocatableImpl(), EvaluateCRExpr(), llvm::MCExpr::FindAssociatedSection(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), llvm::MCAsmLayout::getBaseSymbol(), getSymbolOffsetImpl(), getWeakRef(), hasGOTReference(), llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolved(), llvm::MCAssembler::isThumbFunc(), llvm::MCExpr::print(), printExpr(), printExpr(), llvm::PPCInstPrinter::printTLSCall(), and StartsWithGlobalOffsetTable().
getVariantKindForName()
MCSymbolRefExpr::VariantKind MCSymbolRefExpr::getVariantKindForName (StringRef Name) static
Definition at line 289 of file MCExpr.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), Name, VK_ARM_NONE, VK_ARM_PREL31, VK_ARM_SBREL, VK_ARM_TARGET1, VK_ARM_TARGET2, VK_ARM_TLSCALL, VK_ARM_TLSDESC, VK_ARM_TLSLDO, VK_COFF_IMGREL32, VK_DTPOFF, VK_GOT, VK_GOTNTPOFF, VK_GOTOFF, VK_GOTPAGE, VK_GOTPAGEOFF, VK_GOTPCREL, VK_GOTTPOFF, VK_INDNTPOFF, VK_Invalid, VK_NTPOFF, VK_PAGE, VK_PAGEOFF, VK_PLT, VK_PPC_DTPMOD, VK_PPC_DTPREL, VK_PPC_DTPREL_HA, VK_PPC_DTPREL_HI, VK_PPC_DTPREL_HIGHER, VK_PPC_DTPREL_HIGHERA, VK_PPC_DTPREL_HIGHEST, VK_PPC_DTPREL_HIGHESTA, VK_PPC_DTPREL_LO, VK_PPC_GOT_DTPREL, VK_PPC_GOT_DTPREL_HA, VK_PPC_GOT_DTPREL_HI, VK_PPC_GOT_DTPREL_LO, VK_PPC_GOT_HA, VK_PPC_GOT_HI, VK_PPC_GOT_LO, VK_PPC_GOT_TLSGD, VK_PPC_GOT_TLSGD_HA, VK_PPC_GOT_TLSGD_HI, VK_PPC_GOT_TLSGD_LO, VK_PPC_GOT_TLSLD, VK_PPC_GOT_TLSLD_HA, VK_PPC_GOT_TLSLD_HI, VK_PPC_GOT_TLSLD_LO, VK_PPC_GOT_TPREL, VK_PPC_GOT_TPREL_HA, VK_PPC_GOT_TPREL_HI, VK_PPC_GOT_TPREL_LO, VK_PPC_HA, VK_PPC_HI, VK_PPC_HIGHER, VK_PPC_HIGHERA, VK_PPC_HIGHEST, VK_PPC_HIGHESTA, VK_PPC_LO, VK_PPC_LOCAL, VK_PPC_TLS, VK_PPC_TOC, VK_PPC_TOC_HA, VK_PPC_TOC_HI, VK_PPC_TOC_LO, VK_PPC_TOCBASE, VK_PPC_TPREL, VK_PPC_TPREL_HA, VK_PPC_TPREL_HI, VK_PPC_TPREL_HIGHER, VK_PPC_TPREL_HIGHERA, VK_PPC_TPREL_HIGHEST, VK_PPC_TPREL_HIGHESTA, VK_PPC_TPREL_LO, VK_SECREL, VK_TLSGD, VK_TLSLD, VK_TLSLDM, VK_TLVP, VK_TLVPPAGE, VK_TLVPPAGEOFF, and VK_TPOFF.
getVariantKindName()
StringRef MCSymbolRefExpr::getVariantKindName (VariantKind Kind) static
Definition at line 169 of file MCExpr.cpp.
References llvm_unreachable, VK_ARM_NONE, VK_ARM_PREL31, VK_ARM_SBREL, VK_ARM_TARGET1, VK_ARM_TARGET2, VK_ARM_TLSCALL, VK_ARM_TLSDESC, VK_ARM_TLSDESCSEQ, VK_ARM_TLSLDO, VK_COFF_IMGREL32, VK_DTPOFF, VK_GOT, VK_GOTNTPOFF, VK_GOTOFF, VK_GOTPAGE, VK_GOTPAGEOFF, VK_GOTPCREL, VK_GOTTPOFF, VK_INDNTPOFF, VK_Invalid, VK_Mips_ABS_HI, VK_Mips_ABS_LO, VK_Mips_CALL_HI16, VK_Mips_CALL_LO16, VK_Mips_DTPREL_HI, VK_Mips_DTPREL_LO, VK_Mips_GOT, VK_Mips_GOT16, VK_Mips_GOT_CALL, VK_Mips_GOT_DISP, VK_Mips_GOT_HI16, VK_Mips_GOT_LO16, VK_Mips_GOT_OFST, VK_Mips_GOT_PAGE, VK_Mips_GOTTPREL, VK_Mips_GPOFF_HI, VK_Mips_GPOFF_LO, VK_Mips_GPREL, VK_Mips_HIGHER, VK_Mips_HIGHEST, VK_Mips_PCREL_HI16, VK_Mips_PCREL_LO16, VK_Mips_TLSGD, VK_Mips_TLSLDM, VK_Mips_TPREL_HI, VK_Mips_TPREL_LO, VK_None, VK_NTPOFF, VK_PAGE, VK_PAGEOFF, VK_PLT, VK_PPC_DTPMOD, VK_PPC_DTPREL, VK_PPC_DTPREL_HA, VK_PPC_DTPREL_HI, VK_PPC_DTPREL_HIGHER, VK_PPC_DTPREL_HIGHERA, VK_PPC_DTPREL_HIGHEST, VK_PPC_DTPREL_HIGHESTA, VK_PPC_DTPREL_LO, VK_PPC_GOT_DTPREL, VK_PPC_GOT_DTPREL_HA, VK_PPC_GOT_DTPREL_HI, VK_PPC_GOT_DTPREL_LO, VK_PPC_GOT_HA, VK_PPC_GOT_HI, VK_PPC_GOT_LO, VK_PPC_GOT_TLSGD, VK_PPC_GOT_TLSGD_HA, VK_PPC_GOT_TLSGD_HI, VK_PPC_GOT_TLSGD_LO, VK_PPC_GOT_TLSLD, VK_PPC_GOT_TLSLD_HA, VK_PPC_GOT_TLSLD_HI, VK_PPC_GOT_TLSLD_LO, VK_PPC_GOT_TPREL, VK_PPC_GOT_TPREL_HA, VK_PPC_GOT_TPREL_HI, VK_PPC_GOT_TPREL_LO, VK_PPC_HA, VK_PPC_HI, VK_PPC_HIGHER, VK_PPC_HIGHERA, VK_PPC_HIGHEST, VK_PPC_HIGHESTA, VK_PPC_LO, VK_PPC_LOCAL, VK_PPC_TLS, VK_PPC_TLSGD, VK_PPC_TLSLD, VK_PPC_TOC, VK_PPC_TOC_HA, VK_PPC_TOC_HI, VK_PPC_TOC_LO, VK_PPC_TOCBASE, VK_PPC_TPREL, VK_PPC_TPREL_HA, VK_PPC_TPREL_HI, VK_PPC_TPREL_HIGHER, VK_PPC_TPREL_HIGHERA, VK_PPC_TPREL_HIGHEST, VK_PPC_TPREL_HIGHESTA, VK_PPC_TPREL_LO, VK_SECREL, VK_TLSGD, VK_TLSLD, VK_TLSLDM, VK_TLVP, VK_TLVPPAGE, VK_TLVPPAGEOFF, VK_TPOFF, and VK_WEAKREF.
Referenced by llvm::PPCInstPrinter::printTLSCall(), and printVariantKind().
hasSubsectionsViaSymbols()
bool llvm::MCSymbolRefExpr::hasSubsectionsViaSymbols () const inline
Definition at line 325 of file MCExpr.h.
Referenced by llvm::MCExpr::EvaluateAsRelocatableImpl().
printVariantKind()
void MCSymbolRefExpr::printVariantKind (raw_ostream & OS) const
Definition at line 375 of file MCExpr.cpp.
References getKind(), and getVariantKindName().
Referenced by llvm::MCExpr::print().
The documentation for this class was generated from the following files:
MCExpr.h
MCExpr.cpp