LLVM: llvm::PBQP::Graph< SolverT >::EdgeItr Class Reference
LLVM API Documentation
llvm::PBQP::Graph< SolverT >::EdgeItr Class Reference
#include <Graph.h>
Public Member Functions
EdgeItr (EdgeId CurEId, const Graph &G)
bool operator== (const EdgeItr &O) const
bool operator!= (const EdgeItr &O) const
EdgeItr & operator++ ()
EdgeId operator* () const
Detailed Description
template<typename SolverT>
class llvm::PBQP::Graph< SolverT >::EdgeItr
Definition at line 277 of file Graph.h.
Constructor & Destructor Documentation
EdgeItr()
template<typename SolverT> llvm::PBQP::Graph< SolverT >::EdgeItr::EdgeItr (EdgeId CurEId, const Graph & G) inline
Definition at line 279 of file Graph.h.
References G.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
operator!=()
template<typename SolverT> bool llvm::PBQP::Graph< SolverT >::EdgeItr::operator!= (const EdgeItr & O) const inline
Definition at line 285 of file Graph.h.
References EdgeItr().
operator*()
template<typename SolverT> EdgeId llvm::PBQP::Graph< SolverT >::EdgeItr::operator* () const inline
Definition at line 287 of file Graph.h.
operator++()
template<typename SolverT> EdgeItr & llvm::PBQP::Graph< SolverT >::EdgeItr::operator++ () inline
Definition at line 286 of file Graph.h.
References EdgeItr().
operator==()
template<typename SolverT> bool llvm::PBQP::Graph< SolverT >::EdgeItr::operator== (const EdgeItr & O) const inline
Definition at line 284 of file Graph.h.
References EdgeItr().
The documentation for this class was generated from the following file:
Graph.h