LLVM: llvm::TargetLoweringObjectFile Class Reference
LLVM API Documentation
llvm::TargetLoweringObjectFile Class Reference abstract
#include <TargetLoweringObjectFile.h>
Public Member Functions
MCContext & getContext () const
TargetLoweringObjectFile ()
virtual ~TargetLoweringObjectFile ()
virtual void Initialize (MCContext &ctx, const TargetMachine &TM)
virtual void emitPersonalityValue (MCStreamer &Streamer, const TargetMachine &TM, const MCSymbol *Sym) const
virtual StringRef getDepLibFromLinkerOpt (StringRef LinkerOption) const
virtual void emitModuleFlags (MCStreamer &Streamer, ArrayRef< Module::ModuleFlagEntry > Flags, Mangler &Mang, const TargetMachine &TM) const
Emit the module flags that the platform cares about.
virtual const MCSection * getSectionForConstant (SectionKind Kind, const Constant *C) const
const MCSection * SectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const
const MCSection * SectionForGlobal (const GlobalValue *GV, Mangler &Mang, const TargetMachine &TM) const
virtual const MCSection * getExplicitSectionGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const =0
virtual const MCSection * getSpecialCasedSectionGlobals (const GlobalValue *GV, SectionKind Kind, Mangler &Mang) const
Allow the target to completely override section assignment of a global.
virtual const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix, Mangler &Mang, const TargetMachine &TM) const
virtual MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI) const
const MCExpr * getTTypeReference (const MCSymbolRefExpr *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual const MCSection * getStaticCtorSection (unsigned Priority, const MCSymbol *KeySym) const
virtual const MCSection * getStaticDtorSection (unsigned Priority, const MCSymbol *KeySym) const
virtual const MCExpr * getDebugThreadLocalSymbol (const MCSymbol *Sym) const
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
virtual const MCExpr * getExecutableRelativeSymbol (const ConstantExpr *CE, Mangler &Mang, const TargetMachine &TM) const
Public Member Functions inherited from llvm::MCObjectFileInfo
void InitMCObjectFileInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, MCContext &ctx)
bool getSupportsWeakOmittedEHFrame () const
bool getSupportsCompactUnwindWithoutEHFrame () const
bool getCommDirectiveSupportsAlignment () const
unsigned getPersonalityEncoding () const
unsigned getLSDAEncoding () const
unsigned getFDEEncoding () const
unsigned getTTypeEncoding () const
unsigned getCompactUnwindDwarfEHFrameOnly () const
const MCSection * getTextSection () const
const MCSection * getDataSection () const
const MCSection * getBSSSection () const
const MCSection * getLSDASection () const
const MCSection * getCompactUnwindSection () const
const MCSection * getDwarfAbbrevSection () const
const MCSection * getDwarfInfoSection () const
const MCSection * getDwarfLineSection () const
const MCSection * getDwarfFrameSection () const
const MCSection * getDwarfPubNamesSection () const
const MCSection * getDwarfPubTypesSection () const
const MCSection * getDwarfGnuPubNamesSection () const
const MCSection * getDwarfGnuPubTypesSection () const
const MCSection * getDwarfDebugInlineSection () const
const MCSection * getDwarfStrSection () const
const MCSection * getDwarfLocSection () const
const MCSection * getDwarfARangesSection () const
const MCSection * getDwarfRangesSection () const
const MCSection * getDwarfMacroInfoSection () const
const MCSection * getDwarfAccelNamesSection () const
const MCSection * getDwarfAccelObjCSection () const
const MCSection * getDwarfAccelNamespaceSection () const
const MCSection * getDwarfAccelTypesSection () const
const MCSection * getDwarfInfoDWOSection () const
const MCSection * getDwarfTypesSection (uint64_t Hash) const
const MCSection * getDwarfTypesDWOSection () const
const MCSection * getDwarfAbbrevDWOSection () const
const MCSection * getDwarfStrDWOSection () const
const MCSection * getDwarfLineDWOSection () const
const MCSection * getDwarfLocDWOSection () const
const MCSection * getDwarfStrOffDWOSection () const
const MCSection * getDwarfAddrSection () const
const MCSection * getCOFFDebugSymbolsSection () const
const MCSection * getTLSExtraDataSection () const
const MCSection * getTLSDataSection () const
const MCSection * getTLSBSSSection () const
const MCSection * getStackMapSection () const
const MCSection * getDataRelSection () const
const MCSection * getDataRelLocalSection () const
const MCSection * getDataRelROSection () const
const MCSection * getDataRelROLocalSection () const
const MCSection * getMergeableConst4Section () const
const MCSection * getMergeableConst8Section () const
const MCSection * getMergeableConst16Section () const
const MCSection * getTLSTLVSection () const
const MCSection * getTLSThreadInitSection () const
const MCSection * getCStringSection () const
const MCSection * getUStringSection () const
const MCSection * getTextCoalSection () const
const MCSection * getConstTextCoalSection () const
const MCSection * getConstDataSection () const
const MCSection * getDataCoalSection () const
const MCSection * getDataCommonSection () const
const MCSection * getDataBSSSection () const
const MCSection * getFourByteConstantSection () const
const MCSection * getEightByteConstantSection () const
const MCSection * getSixteenByteConstantSection () const
const MCSection * getLazySymbolPointerSection () const
const MCSection * getNonLazySymbolPointerSection () const
const MCSection * getDrectveSection () const
const MCSection * getPDataSection () const
const MCSection * getXDataSection () const
const MCSection * getEHFrameSection ()
Environment getObjectFileType () const
Reloc::Model getRelocM () const
const Triple & getTargetTriple () const
Static Public Member Functions
static SectionKind getKindForGlobal (const GlobalValue *GV, const TargetMachine &TM)
Protected Member Functions
virtual const MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const =0
Additional Inherited Members
Public Types inherited from llvm::MCObjectFileInfo
enum Environment { IsMachO , IsELF , IsCOFF }
Protected Attributes inherited from llvm::MCObjectFileInfo
bool CommDirectiveSupportsAlignment
bool SupportsWeakOmittedEHFrame
bool SupportsCompactUnwindWithoutEHFrame
unsigned PersonalityEncoding
unsigned LSDAEncoding
unsigned FDECFIEncoding
unsigned TTypeEncoding
unsigned EHSectionType
Section flags for eh_frame.
unsigned EHSectionFlags
unsigned CompactUnwindDwarfEHFrameOnly
const MCSection * TextSection
const MCSection * DataSection
const MCSection * BSSSection
BSSSection - Section that is default initialized to zero.
const MCSection * ReadOnlySection
const MCSection * StaticCtorSection
const MCSection * StaticDtorSection
const MCSection * LSDASection
const MCSection * CompactUnwindSection
const MCSection * DwarfAbbrevSection
const MCSection * DwarfInfoSection
const MCSection * DwarfLineSection
const MCSection * DwarfFrameSection
const MCSection * DwarfPubTypesSection
const MCSection * DwarfDebugInlineSection
const MCSection * DwarfStrSection
const MCSection * DwarfLocSection
const MCSection * DwarfARangesSection
const MCSection * DwarfRangesSection
const MCSection * DwarfMacroInfoSection
const MCSection * DwarfPubNamesSection
const MCSection * DwarfAccelNamesSection
const MCSection * DwarfAccelObjCSection
const MCSection * DwarfAccelNamespaceSection
const MCSection * DwarfAccelTypesSection
const MCSection * DwarfInfoDWOSection
These are used for the Fission separate debug information files.
const MCSection * DwarfTypesDWOSection
const MCSection * DwarfAbbrevDWOSection
const MCSection * DwarfStrDWOSection
const MCSection * DwarfLineDWOSection
const MCSection * DwarfLocDWOSection
const MCSection * DwarfStrOffDWOSection
const MCSection * DwarfAddrSection
const MCSection * DwarfGnuPubNamesSection
Sections for newer gnu pubnames and pubtypes.
const MCSection * DwarfGnuPubTypesSection
const MCSection * COFFDebugSymbolsSection
const MCSection * TLSExtraDataSection
const MCSection * TLSDataSection
const MCSection * TLSBSSSection
const MCSection * StackMapSection
StackMap section.
const MCSection * EHFrameSection
const MCSection * DataRelSection
const MCSection * DataRelLocalSection
const MCSection * DataRelROSection
const MCSection * DataRelROLocalSection
const MCSection * MergeableConst4Section
const MCSection * MergeableConst8Section
const MCSection * MergeableConst16Section
const MCSection * TLSTLVSection
const MCSection * TLSThreadInitSection
const MCSection * CStringSection
const MCSection * UStringSection
const MCSection * TextCoalSection
const MCSection * ConstTextCoalSection
const MCSection * ConstDataSection
const MCSection * DataCoalSection
const MCSection * DataCommonSection
const MCSection * DataBSSSection
const MCSection * FourByteConstantSection
const MCSection * EightByteConstantSection
const MCSection * SixteenByteConstantSection
const MCSection * LazySymbolPointerSection
const MCSection * NonLazySymbolPointerSection
const MCSection * DrectveSection
const MCSection * PDataSection
const MCSection * XDataSection
Detailed Description
Definition at line 36 of file TargetLoweringObjectFile.h.
Constructor & Destructor Documentation
TargetLoweringObjectFile()
llvm::TargetLoweringObjectFile::TargetLoweringObjectFile () inline
Definition at line 47 of file TargetLoweringObjectFile.h.
~TargetLoweringObjectFile()
TargetLoweringObjectFile::~TargetLoweringObjectFile () virtual
Definition at line 51 of file TargetLoweringObjectFile.cpp.
Member Function Documentation
emitModuleFlags()
virtual void llvm::TargetLoweringObjectFile::emitModuleFlags (MCStreamer & Streamer, ArrayRef< Module::ModuleFlagEntry > Flags, Mangler & Mang, const TargetMachine & TM) const inline virtual
Emit the module flags that the platform cares about.
Reimplemented in llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileMachO.
Definition at line 67 of file TargetLoweringObjectFile.h.
Referenced by llvm::AsmPrinter::doFinalization().
emitPersonalityValue()
void TargetLoweringObjectFile::emitPersonalityValue (MCStreamer & Streamer, const TargetMachine & TM, const MCSymbol * Sym) const virtual
Reimplemented in llvm::TargetLoweringObjectFileELF.
Definition at line 122 of file TargetLoweringObjectFile.cpp.
Referenced by llvm::DwarfCFIException::endModule().
getCFIPersonalitySymbol()
MCSymbol * TargetLoweringObjectFile::getCFIPersonalitySymbol (const GlobalValue * GV, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI) const virtual
Reimplemented in llvm::AArch64_MachoTargetObjectFile, llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, and llvm::X86_64MachoTargetObjectFile.
Definition at line 116 of file TargetLoweringObjectFile.cpp.
Referenced by llvm::DwarfCFIException::beginFunction(), and llvm::Win64Exception::beginFunction().
getContext()
MCContext & llvm::TargetLoweringObjectFile::getContext () const inline
Definition at line 45 of file TargetLoweringObjectFile.h.
Referenced by llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::TargetLoweringObjectFileELF::getCFIPersonalitySymbol(), llvm::ARMElfTargetObjectFile::getDebugThreadLocalSymbol(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getStaticCtorSection(), llvm::TargetLoweringObjectFileELF::getStaticCtorSection(), llvm::TargetLoweringObjectFileCOFF::getStaticDtorSection(), llvm::TargetLoweringObjectFileELF::getStaticDtorSection(), llvm::TargetMachine::getSymbol(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference(), getTTypeReference(), llvm::ARMElfTargetObjectFile::Initialize(), llvm::HexagonTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileELF::InitializeELF(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
getDebugThreadLocalSymbol()
const MCExpr * TargetLoweringObjectFile::getDebugThreadLocalSymbol (const MCSymbol * Sym) const virtual
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
Reimplemented in llvm::ARMElfTargetObjectFile.
Definition at line 318 of file TargetLoweringObjectFile.cpp.
References llvm::MCSymbolRefExpr::Create().
getDepLibFromLinkerOpt()
virtual StringRef llvm::TargetLoweringObjectFile::getDepLibFromLinkerOpt (StringRef LinkerOption) const inline virtual
Extract the dependent library name from a linker option string. Returns StringRef() if the option does not specify a library.
Reimplemented in llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileMachO.
Definition at line 62 of file TargetLoweringObjectFile.h.
getExecutableRelativeSymbol()
virtual const MCExpr * llvm::TargetLoweringObjectFile::getExecutableRelativeSymbol (const ConstantExpr * CE, Mangler & Mang, const TargetMachine & TM) const inline virtual
Definition at line 149 of file TargetLoweringObjectFile.h.
getExplicitSectionGlobal()
virtual const MCSection * llvm::TargetLoweringObjectFile::getExplicitSectionGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const pure virtual
Targets should implement this method to assign a section to globals with an explicit section specfied. The implementation of this method can assume that GV->hasSection() is true.
Implemented in llvm::NVPTXTargetObjectFile, llvm::TargetLoweringObjectFileCOFF, llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, and llvm::XCoreTargetObjectFile.
Referenced by SectionForGlobal().
getKindForGlobal()
SectionKind TargetLoweringObjectFile::getKindForGlobal (const GlobalValue * GV, const TargetMachine & TM) static
Classify the specified global variable into a set of target independent categories embodied in SectionKind.
getKindForGlobal - This is a top-level target-independent classifier for a global variable. Given an global variable and information from TM, it classifies the global in a variety of ways that make various target implementations simpler. The target implementation is free to ignore this extra info of course.
Definition at line 133 of file TargetLoweringObjectFile.cpp.
References llvm::dyn_cast(), llvm::SectionKind::getBSS(), llvm::SectionKind::getBSSExtern(), llvm::SectionKind::getBSSLocal(), llvm::SectionKind::getCommon(), llvm::SectionKind::getDataNoRel(), llvm::SectionKind::getDataRel(), llvm::SectionKind::getDataRelLocal(), llvm::GlobalVariable::getInitializer(), llvm::SectionKind::getMergeable1ByteCString(), llvm::SectionKind::getMergeable2ByteCString(), llvm::SectionKind::getMergeable4ByteCString(), llvm::SectionKind::getMergeableConst(), llvm::SectionKind::getMergeableConst16(), llvm::SectionKind::getMergeableConst4(), llvm::SectionKind::getMergeableConst8(), llvm::SectionKind::getReadOnly(), llvm::SectionKind::getReadOnlyWithRel(), llvm::SectionKind::getReadOnlyWithRelLocal(), llvm::SectionKind::getText(), llvm::SectionKind::getThreadBSS(), llvm::SectionKind::getThreadData(), llvm::Constant::GlobalRelocations, llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::hasUnnamedAddr(), llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isDeclaration(), IsNullTerminatedString(), isSuitableForBSS(), llvm::GlobalValue::isThreadLocal(), llvm_unreachable, llvm::Constant::LocalRelocation, llvm::Constant::NoRelocation, and llvm::Reloc::Static.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::TargetMachine::getNameWithPrefix(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), and SectionForGlobal().
getSectionForConstant()
const MCSection * TargetLoweringObjectFile::getSectionForConstant (SectionKind Kind, const Constant * C) const virtual
Given a constant with the SectionKind, return a section that it should be placed in.
getSectionForConstant - Given a mergable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented in llvm::MipsTargetObjectFile, llvm::NVPTXTargetObjectFile, llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, and llvm::XCoreTargetObjectFile.
Definition at line 277 of file TargetLoweringObjectFile.cpp.
References llvm::MCObjectFileInfo::DataSection, and llvm::MCObjectFileInfo::ReadOnlySection.
Referenced by llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::EmitConstantPool(), and llvm::AsmPrinter::EmitJumpTableInfo().
getSpecialCasedSectionGlobals()
virtual const MCSection * llvm::TargetLoweringObjectFile::getSpecialCasedSectionGlobals (const GlobalValue * GV, SectionKind Kind, Mangler & Mang) const inline virtual
Allow the target to completely override section assignment of a global.
Definition at line 105 of file TargetLoweringObjectFile.h.
getStaticCtorSection()
virtual const MCSection * llvm::TargetLoweringObjectFile::getStaticCtorSection (unsigned Priority, const MCSymbol * KeySym) const inline virtual
Reimplemented in llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileELF.
Definition at line 134 of file TargetLoweringObjectFile.h.
References llvm::MCObjectFileInfo::StaticCtorSection.
getStaticDtorSection()
virtual const MCSection * llvm::TargetLoweringObjectFile::getStaticDtorSection (unsigned Priority, const MCSymbol * KeySym) const inline virtual
Reimplemented in llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileELF.
Definition at line 139 of file TargetLoweringObjectFile.h.
References llvm::MCObjectFileInfo::StaticDtorSection.
getSymbolWithGlobalValueBase()
MCSymbol * TargetLoweringObjectFile::getSymbolWithGlobalValueBase (const GlobalValue * GV, StringRef Suffix, Mangler & Mang, const TargetMachine & TM) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
Definition at line 104 of file TargetLoweringObjectFile.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::StringRef::begin(), llvm::StringRef::empty(), llvm::StringRef::end(), and llvm::SmallString< InternalLen >::str().
Referenced by llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::AsmPrinter::getSymbolWithGlobalValueBase(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
getTTypeGlobalReference()
const MCExpr * TargetLoweringObjectFile::getTTypeGlobalReference (const GlobalValue * GV, unsigned Encoding, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI, MCStreamer & Streamer) const virtual
Return an MCExpr to use for a reference to the specified global variable from exception handling information.
getTTypeGlobalReference - Return an MCExpr to use for a reference to the specified global variable from exception handling information.
Reimplemented in llvm::AArch64_MachoTargetObjectFile, llvm::ARMElfTargetObjectFile, llvm::SparcELFTargetObjectFile, llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, and llvm::X86_64MachoTargetObjectFile.
Definition at line 288 of file TargetLoweringObjectFile.cpp.
References llvm::MCSymbolRefExpr::Create(), getContext(), and getTTypeReference().
Referenced by llvm::AsmPrinter::EmitTTypeReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
getTTypeReference()
const MCExpr * TargetLoweringObjectFile::getTTypeReference (const MCSymbolRefExpr * Sym, unsigned Encoding, MCStreamer & Streamer) const
Definition at line 298 of file TargetLoweringObjectFile.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateSub(), llvm::MCContext::CreateTempSymbol(), llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_pcrel, llvm::MCStreamer::EmitLabel(), getContext(), and llvm::report_fatal_error().
Referenced by getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
Initialize()
void TargetLoweringObjectFile::Initialize (MCContext & ctx, const TargetMachine & TM) virtual
This method must be called before any actual lowering is done. This specifies the current context for codegen, and gives the lowering implementations a chance to set up their default sections.
Initialize - this method must be called before any actual lowering is done. This specifies the current context for codegen, and gives the lowering implementations a chance to set up their default sections.
Reimplemented in llvm::ARMElfTargetObjectFile, llvm::HexagonTargetObjectFile, llvm::MipsTargetObjectFile, llvm::NVPTXTargetObjectFile, and llvm::XCoreTargetObjectFile.
Definition at line 43 of file TargetLoweringObjectFile.cpp.
References llvm::MCObjectFileInfo::InitMCObjectFileInfo().
Referenced by llvm::ARMElfTargetObjectFile::Initialize(), llvm::HexagonTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::XCoreTargetObjectFile::Initialize().
SectionForGlobal() [1/2]
const MCSection * llvm::TargetLoweringObjectFile::SectionForGlobal (const GlobalValue * GV, Mangler & Mang, const TargetMachine & TM) const inline
This method computes the appropriate section to emit the specified global variable or function definition. This should not be passed external (or available externally) globals.
Definition at line 91 of file TargetLoweringObjectFile.h.
References getKindForGlobal(), and SectionForGlobal().
SectionForGlobal() [2/2]
const MCSection * TargetLoweringObjectFile::SectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const
This method computes the appropriate section to emit the specified global variable or function definition. This should not be passed external (or available externally) globals.
SectionForGlobal - This method computes the appropriate section to emit the specified global variable or function definition. This should not be passed external (or available externally) globals.
Definition at line 261 of file TargetLoweringObjectFile.cpp.
References getExplicitSectionGlobal(), llvm::GlobalValue::hasSection(), and SelectSectionForGlobal().
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::TargetMachine::getNameWithPrefix(), and SectionForGlobal().
SelectSectionForGlobal()
virtual const MCSection * llvm::TargetLoweringObjectFile::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const protected pure virtual
Implemented in llvm::HexagonTargetObjectFile, llvm::MipsTargetObjectFile, llvm::NVPTXTargetObjectFile, llvm::TargetLoweringObjectFileCOFF, llvm::TargetLoweringObjectFileELF, llvm::TargetLoweringObjectFileMachO, and llvm::XCoreTargetObjectFile.
Referenced by SectionForGlobal().
The documentation for this class was generated from the following files:
TargetLoweringObjectFile.h
TargetLoweringObjectFile.cpp