LLVM: llvm::HexagonMachineFunctionInfo Class Reference
LLVM API Documentation
llvm::HexagonMachineFunctionInfo Class Reference
Hexagon target-specific information for each MachineFunction.
#include <HexagonMachineFunctionInfo.h>
Public Member Functions
HexagonMachineFunctionInfo ()
HexagonMachineFunctionInfo (MachineFunction &MF)
unsigned getSRetReturnReg () const
void setSRetReturnReg (unsigned Reg)
void addAllocaAdjustInst (MachineInstr *MI)
const std::vector< MachineInstr * > & getAllocaAdjustInsts ()
void setVarArgsFrameIndex (int v)
int getVarArgsFrameIndex ()
void setStartPacket (MachineInstr *MI)
void setEndPacket (MachineInstr *MI)
bool isStartPacket (const MachineInstr *MI) const
bool isEndPacket (const MachineInstr *MI) const
void setHasClobberLR (bool v)
bool hasClobberLR () const
bool hasEHReturn () const
void setHasEHReturn (bool H=true)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty>
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
Hexagon target-specific information for each MachineFunction.
Definition at line 25 of file HexagonMachineFunctionInfo.h.
Constructor & Destructor Documentation
HexagonMachineFunctionInfo() [1/2]
llvm::HexagonMachineFunctionInfo::HexagonMachineFunctionInfo () inline
Definition at line 38 of file HexagonMachineFunctionInfo.h.
HexagonMachineFunctionInfo() [2/2]
llvm::HexagonMachineFunctionInfo::HexagonMachineFunctionInfo (MachineFunction & MF) inline
Definition at line 41 of file HexagonMachineFunctionInfo.h.
Member Function Documentation
addAllocaAdjustInst()
void llvm::HexagonMachineFunctionInfo::addAllocaAdjustInst (MachineInstr * MI) inline
Definition at line 48 of file HexagonMachineFunctionInfo.h.
Referenced by llvm::HexagonTargetLowering::EmitInstrWithCustomInserter().
getAllocaAdjustInsts()
const std::vector< MachineInstr * > & llvm::HexagonMachineFunctionInfo::getAllocaAdjustInsts () inline
Definition at line 51 of file HexagonMachineFunctionInfo.h.
Referenced by llvm::HexagonFrameLowering::emitPrologue().
getSRetReturnReg()
unsigned llvm::HexagonMachineFunctionInfo::getSRetReturnReg () const inline
Definition at line 45 of file HexagonMachineFunctionInfo.h.
getVarArgsFrameIndex()
int llvm::HexagonMachineFunctionInfo::getVarArgsFrameIndex () inline
Definition at line 56 of file HexagonMachineFunctionInfo.h.
Referenced by llvm::HexagonTargetLowering::LowerVASTART().
hasClobberLR()
bool llvm::HexagonMachineFunctionInfo::hasClobberLR () const inline
Definition at line 73 of file HexagonMachineFunctionInfo.h.
Referenced by llvm::HexagonFrameLowering::hasFP(), and llvm::HexagonTargetLowering::LowerINLINEASM().
hasEHReturn()
bool llvm::HexagonMachineFunctionInfo::hasEHReturn () const inline
Definition at line 75 of file HexagonMachineFunctionInfo.h.
isEndPacket()
bool llvm::HexagonMachineFunctionInfo::isEndPacket (const MachineInstr * MI) const inline
Definition at line 68 of file HexagonMachineFunctionInfo.h.
References llvm::Hexagon::EndPacket.
isStartPacket()
bool llvm::HexagonMachineFunctionInfo::isStartPacket (const MachineInstr * MI) const inline
Definition at line 64 of file HexagonMachineFunctionInfo.h.
References llvm::Hexagon::StartPacket.
setEndPacket()
void llvm::HexagonMachineFunctionInfo::setEndPacket (MachineInstr * MI) inline
Definition at line 61 of file HexagonMachineFunctionInfo.h.
References llvm::Hexagon::EndPacket.
setHasClobberLR()
void llvm::HexagonMachineFunctionInfo::setHasClobberLR (bool v) inline
Definition at line 72 of file HexagonMachineFunctionInfo.h.
Referenced by llvm::HexagonTargetLowering::LowerINLINEASM().
setHasEHReturn()
void llvm::HexagonMachineFunctionInfo::setHasEHReturn (bool H = true) inline
Definition at line 76 of file HexagonMachineFunctionInfo.h.
References H.
Referenced by llvm::HexagonTargetLowering::LowerEH_RETURN().
setSRetReturnReg()
void llvm::HexagonMachineFunctionInfo::setSRetReturnReg (unsigned Reg) inline
Definition at line 46 of file HexagonMachineFunctionInfo.h.
setStartPacket()
void llvm::HexagonMachineFunctionInfo::setStartPacket (MachineInstr * MI) inline
Definition at line 58 of file HexagonMachineFunctionInfo.h.
References llvm::Hexagon::StartPacket.
setVarArgsFrameIndex()
void llvm::HexagonMachineFunctionInfo::setVarArgsFrameIndex (int v) inline
Definition at line 55 of file HexagonMachineFunctionInfo.h.
Referenced by llvm::HexagonTargetLowering::LowerFormalArguments().
The documentation for this class was generated from the following files:
HexagonMachineFunctionInfo.h
HexagonMachineFunctionInfo.cpp