LLVM: llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator Class Reference
LLVM API Documentation
llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator Class Reference
Public Member Functions
PHI_iterator (PHINode *P)
PHI_iterator (PHINode *P, bool)
PHI_iterator & operator++ ()
bool operator== (const PHI_iterator &x) const
bool operator!= (const PHI_iterator &x) const
Value * getIncomingValue ()
BasicBlock * getIncomingBlock ()
Detailed Description
Definition at line 217 of file SSAUpdater.cpp.
Constructor & Destructor Documentation
PHI_iterator() [1/2]
llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::PHI_iterator (PHINode * P) inline explicit
Definition at line 223 of file SSAUpdater.cpp.
References P.
Referenced by operator!=(), operator++(), and operator==().
PHI_iterator() [2/2]
llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::PHI_iterator (PHINode * P, bool) inline
Definition at line 225 of file SSAUpdater.cpp.
References P.
Member Function Documentation
getIncomingBlock()
BasicBlock * llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::getIncomingBlock () inline
Definition at line 232 of file SSAUpdater.cpp.
getIncomingValue()
Value * llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::getIncomingValue () inline
Definition at line 231 of file SSAUpdater.cpp.
operator!=()
bool llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::operator!= (const PHI_iterator & x) const inline
Definition at line 230 of file SSAUpdater.cpp.
References llvm::operator==(), and PHI_iterator().
operator++()
PHI_iterator & llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::operator++ () inline
Definition at line 228 of file SSAUpdater.cpp.
References PHI_iterator().
operator==()
bool llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator::operator== (const PHI_iterator & x) const inline
Definition at line 229 of file SSAUpdater.cpp.
References PHI_iterator().
The documentation for this class was generated from the following file:
SSAUpdater.cpp