LLVM: llvm::TGParser Class Reference
LLVM API Documentation
llvm::TGParser Class Reference
#include <TGParser.h>
Public Member Functions
TGParser (SourceMgr &SrcMgr, RecordKeeper &records)
bool ParseFile ()
bool Error (SMLoc L, const Twine &Msg) const
bool TokError (const Twine &Msg) const
const TGLexer::DependenciesMapTy & getDependencies () const
Detailed Description
Definition at line 55 of file TGParser.h.
Constructor & Destructor Documentation
TGParser()
llvm::TGParser::TGParser (SourceMgr & SrcMgr, RecordKeeper & records) inline
Definition at line 87 of file TGParser.h.
References llvm::SrcMgr.
Member Function Documentation
Error()
bool llvm::TGParser::Error (SMLoc L, const Twine & Msg) const inline
Definition at line 94 of file TGParser.h.
References llvm::PrintError().
Referenced by TokError().
getDependencies()
const TGLexer::DependenciesMapTy & llvm::TGParser::getDependencies () const inline
Definition at line 101 of file TGParser.h.
Referenced by createDependencyFile().
ParseFile()
bool TGParser::ParseFile ()
ParseFile - Main entrypoint for parsing a tblgen file. These parser routines return true on error, or false on success.
Definition at line 2682 of file TGParser.cpp.
References llvm::tgtok::Eof, and TokError().
Referenced by llvm::TableGenMain().
TokError()
bool llvm::TGParser::TokError (const Twine & Msg) const inline
Definition at line 98 of file TGParser.h.
References Error().
Referenced by ParseFile().
The documentation for this class was generated from the following files:
TGParser.h
TGParser.cpp