LLVM: llvm::ObjectMemoryBuffer Class Reference
LLVM API Documentation
llvm::ObjectMemoryBuffer Class Reference
#include <ObjectBuffer.h>
Public Member Functions
template<unsigned N>
ObjectMemoryBuffer (SmallVector< char, N > SV)
template<unsigned N>
ObjectMemoryBuffer (SmallVector< char, N > SV, StringRef Name)
const char * getBufferIdentifier () const override
BufferKind getBufferKind () const override
Public Member Functions inherited from llvm::MemoryBuffer
virtual ~MemoryBuffer ()
const char * getBufferStart () const
const char * getBufferEnd () const
size_t getBufferSize () const
StringRef getBuffer () const
MemoryBufferRef getMemBufferRef () const
Additional Inherited Members
Public Types inherited from llvm::MemoryBuffer
enum BufferKind { MemoryBuffer_Malloc , MemoryBuffer_MMap }
The kind of memory backing used to support the MemoryBuffer.
Static Public Member Functions inherited from llvm::MemoryBuffer
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFile (const Twine &Filename, int64_t FileSize=-1, bool RequiresNullTerminator=true, bool IsVolatileSize=false)
static ErrorOr< std::unique_ptr< MemoryBuffer > > getOpenFileSlice (int FD, const Twine &Filename, uint64_t MapSize, int64_t Offset)
static ErrorOr< std::unique_ptr< MemoryBuffer > > getOpenFile (int FD, const Twine &Filename, uint64_t FileSize, bool RequiresNullTerminator=true, bool IsVolatileSize=false)
static std::unique_ptr< MemoryBuffer > getMemBuffer (StringRef InputData, StringRef BufferName="", bool RequiresNullTerminator=true)
static std::unique_ptr< MemoryBuffer > getMemBuffer (MemoryBufferRef Ref, bool RequiresNullTerminator=true)
static std::unique_ptr< MemoryBuffer > getMemBufferCopy (StringRef InputData, const Twine &BufferName="")
static std::unique_ptr< MemoryBuffer > getNewMemBuffer (size_t Size, StringRef BufferName="")
static std::unique_ptr< MemoryBuffer > getNewUninitMemBuffer (size_t Size, const Twine &BufferName="")
static ErrorOr< std::unique_ptr< MemoryBuffer > > getSTDIN ()
Read all of stdin into a file buffer, and return it.
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFileOrSTDIN (const Twine &Filename, int64_t FileSize=-1)
static ErrorOr< std::unique_ptr< MemoryBuffer > > getFileSlice (const Twine &Filename, uint64_t MapSize, uint64_t Offset)
Map a subrange of the the specified file as a MemoryBuffer.
Protected Member Functions inherited from llvm::MemoryBuffer
MemoryBuffer ()
void init (const char *BufStart, const char *BufEnd, bool RequiresNullTerminator)
Detailed Description
Definition at line 24 of file ObjectBuffer.h.
Constructor & Destructor Documentation
ObjectMemoryBuffer() [1/2]
template<unsigned N> llvm::ObjectMemoryBuffer::ObjectMemoryBuffer (SmallVector< char, N > SV) inline
Definition at line 27 of file ObjectBuffer.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::MemoryBuffer::init().
ObjectMemoryBuffer() [2/2]
template<unsigned N> llvm::ObjectMemoryBuffer::ObjectMemoryBuffer (SmallVector< char, N > SV, StringRef Name) inline
Definition at line 33 of file ObjectBuffer.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MemoryBuffer::init(), and Name.
Member Function Documentation
getBufferIdentifier()
const char * llvm::ObjectMemoryBuffer::getBufferIdentifier () const inline override virtual
Return an identifier for this buffer, typically the filename it was read from.
Reimplemented from llvm::MemoryBuffer.
Definition at line 37 of file ObjectBuffer.h.
getBufferKind()
BufferKind llvm::ObjectMemoryBuffer::getBufferKind () const inline override virtual
Return information on the memory mechanism used to support the MemoryBuffer.
Implements llvm::MemoryBuffer.
Definition at line 39 of file ObjectBuffer.h.
References llvm::MemoryBuffer::MemoryBuffer_Malloc.
The documentation for this class was generated from the following file:
ObjectBuffer.h