LLVM: llvm::FunctionAnalysisManagerCGSCCProxy Class Reference
LLVM API Documentation
llvm::FunctionAnalysisManagerCGSCCProxy Class Reference
A CGSCC analysis which acts as a proxy for a function analysis manager.
#include <CGSCCPassManager.h>
Classes
class Result
Public Member Functions
FunctionAnalysisManagerCGSCCProxy (FunctionAnalysisManager &FAM)
FunctionAnalysisManagerCGSCCProxy (const FunctionAnalysisManagerCGSCCProxy &Arg)
FunctionAnalysisManagerCGSCCProxy (FunctionAnalysisManagerCGSCCProxy &&Arg)
FunctionAnalysisManagerCGSCCProxy & operator= (FunctionAnalysisManagerCGSCCProxy RHS)
Result run (LazyCallGraph::SCC &C)
Run the analysis pass and create our proxy result object.
Static Public Member Functions
static void * ID ()
static StringRef name ()
Detailed Description
A CGSCC analysis which acts as a proxy for a function analysis manager.
This primarily proxies invalidation information from the CGSCC analysis manager and CGSCC pass manager to a function analysis manager. You should never use a function analysis manager from within (transitively) a CGSCC pass manager unless your parent CGSCC pass has received a proxy result object for it.
Definition at line 278 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
FunctionAnalysisManagerCGSCCProxy() [1/3]
llvm::FunctionAnalysisManagerCGSCCProxy::FunctionAnalysisManagerCGSCCProxy (FunctionAnalysisManager & FAM) inline explicit
Definition at line 316 of file CGSCCPassManager.h.
Referenced by FunctionAnalysisManagerCGSCCProxy(), FunctionAnalysisManagerCGSCCProxy(), and operator=().
FunctionAnalysisManagerCGSCCProxy() [2/3]
llvm::FunctionAnalysisManagerCGSCCProxy::FunctionAnalysisManagerCGSCCProxy (const FunctionAnalysisManagerCGSCCProxy & Arg) inline
Definition at line 320 of file CGSCCPassManager.h.
References FunctionAnalysisManagerCGSCCProxy().
FunctionAnalysisManagerCGSCCProxy() [3/3]
llvm::FunctionAnalysisManagerCGSCCProxy::FunctionAnalysisManagerCGSCCProxy (FunctionAnalysisManagerCGSCCProxy && Arg) inline
Definition at line 323 of file CGSCCPassManager.h.
References FunctionAnalysisManagerCGSCCProxy().
Member Function Documentation
ID()
void * llvm::FunctionAnalysisManagerCGSCCProxy::ID () inline static
Definition at line 312 of file CGSCCPassManager.h.
Referenced by llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate().
name()
StringRef llvm::FunctionAnalysisManagerCGSCCProxy::name () inline static
Definition at line 314 of file CGSCCPassManager.h.
operator=()
FunctionAnalysisManagerCGSCCProxy & llvm::FunctionAnalysisManagerCGSCCProxy::operator= (FunctionAnalysisManagerCGSCCProxy RHS) inline
Definition at line 326 of file CGSCCPassManager.h.
References FunctionAnalysisManagerCGSCCProxy(), and std::swap().
run()
FunctionAnalysisManagerCGSCCProxy::Result FunctionAnalysisManagerCGSCCProxy::run (LazyCallGraph::SCC & C)
Run the analysis pass and create our proxy result object.
This doesn't do any interesting work, it is primarily used to insert our proxy result object into the module analysis cache so that we can proxy invalidation to the function analysis manager.
In debug builds, it will also assert that the analysis manager is empty as no queries should arrive at the function analysis manager prior to this analysis being requested.
Definition at line 48 of file CGSCCPassManager.cpp.
The documentation for this class was generated from the following files:
CGSCCPassManager.h
CGSCCPassManager.cpp