LLVM: llvm::DWARFContextInMemory Class Reference
LLVM API Documentation
llvm::DWARFContextInMemory Class Reference
#include <DWARFContext.h>
Public Member Functions
DWARFContextInMemory (const object::ObjectFile &Obj)
bool isLittleEndian () const override
uint8_t getAddressSize () const override
const DWARFSection & getInfoSection () override
const TypeSectionMap & getTypesSections () override
StringRef getAbbrevSection () override
const DWARFSection & getLocSection () override
StringRef getARangeSection () override
StringRef getDebugFrameSection () override
const DWARFSection & getLineSection () override
StringRef getStringSection () override
StringRef getRangeSection () override
StringRef getPubNamesSection () override
StringRef getPubTypesSection () override
StringRef getGnuPubNamesSection () override
StringRef getGnuPubTypesSection () override
const DWARFSection & getAppleNamesSection () override
const DWARFSection & getAppleTypesSection () override
const DWARFSection & getAppleNamespacesSection () override
const DWARFSection & getAppleObjCSection () override
const DWARFSection & getInfoDWOSection () override
const TypeSectionMap & getTypesDWOSections () override
StringRef getAbbrevDWOSection () override
const DWARFSection & getLineDWOSection () override
const DWARFSection & getLocDWOSection () override
StringRef getStringDWOSection () override
StringRef getStringOffsetDWOSection () override
StringRef getRangeDWOSection () override
StringRef getAddrSection () override
Public Member Functions inherited from llvm::DWARFContext
DWARFContext ()
void dump (raw_ostream &OS, DIDumpType DumpType=DIDT_All) override
cu_iterator_range compile_units ()
Get compile units in this context.
tu_section_iterator_range type_unit_sections ()
Get type units in this context.
cu_iterator_range dwo_compile_units ()
Get compile units in the DWO context.
tu_section_iterator_range dwo_type_unit_sections ()
Get type units in the DWO context.
unsigned getNumCompileUnits ()
Get the number of compile units in this context.
unsigned getNumTypeUnits ()
Get the number of compile units in this context.
unsigned getNumDWOCompileUnits ()
Get the number of compile units in the DWO context.
unsigned getNumDWOTypeUnits ()
Get the number of compile units in the DWO context.
DWARFCompileUnit * getCompileUnitAtIndex (unsigned index)
Get the compile unit at the specified index for this compile unit.
DWARFCompileUnit * getDWOCompileUnitAtIndex (unsigned index)
Get the compile unit at the specified index for the DWO compile units.
const DWARFDebugAbbrev * getDebugAbbrev ()
Get a pointer to the parsed DebugAbbrev object.
const DWARFDebugLoc * getDebugLoc ()
Get a pointer to the parsed DebugLoc object.
const DWARFDebugAbbrev * getDebugAbbrevDWO ()
Get a pointer to the parsed dwo abbreviations object.
const DWARFDebugLocDWO * getDebugLocDWO ()
Get a pointer to the parsed DebugLoc object.
const DWARFDebugAranges * getDebugAranges ()
Get a pointer to the parsed DebugAranges object.
const DWARFDebugFrame * getDebugFrame ()
Get a pointer to the parsed frame information object.
const DWARFDebugLine::LineTable * getLineTableForUnit (DWARFUnit *cu)
Get a pointer to a parsed line table corresponding to a compile unit.
DILineInfo getLineInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DILineInfoTable getLineInfoForAddressRange (uint64_t Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DIInliningInfo getInliningInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
Public Member Functions inherited from llvm::DIContext
DIContextKind getKind () const
DIContext (DIContextKind K)
virtual ~DIContext ()
Additional Inherited Members
Public Types inherited from llvm::DWARFContext
typedef DWARFUnitSection< DWARFCompileUnit >::iterator_range cu_iterator_range
typedef DWARFUnitSection< DWARFTypeUnit >::iterator_range tu_iterator_range
typedef iterator_range< std::vector< DWARFUnitSection< DWARFTypeUnit > >::iterator > tu_section_iterator_range
typedef MapVector< object::SectionRef, DWARFSection, std::map< object::SectionRef, unsigned > > TypeSectionMap
Public Types inherited from llvm::DIContext
enum DIContextKind { CK_DWARF }
Static Public Member Functions inherited from llvm::DWARFContext
static bool classof (const DIContext *DICtx)
static bool isSupportedVersion (unsigned version)
Static Public Member Functions inherited from llvm::DIContext
static DIContext * getDWARFContext (const object::ObjectFile &Obj)
getDWARFContext - get a context for binary DWARF data.
Detailed Description
DWARFContextInMemory is the simplest possible implementation of a DWARFContext. It assumes all content is available in memory and stores pointers to it.
Definition at line 215 of file DWARFContext.h.
Constructor & Destructor Documentation
DWARFContextInMemory()
DWARFContextInMemory::DWARFContextInMemory (const object::ObjectFile & Obj)
Definition at line 540 of file DWARFContext.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::object::SectionRef::getName(), if(), isLittleEndian(), llvm::object::ObjectFile::section_end(), and llvm::object::ObjectFile::sections().
Member Function Documentation
getAbbrevDWOSection()
StringRef llvm::DWARFContextInMemory::getAbbrevDWOSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 277 of file DWARFContext.h.
getAbbrevSection()
StringRef llvm::DWARFContextInMemory::getAbbrevSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 256 of file DWARFContext.h.
getAddressSize()
uint8_t llvm::DWARFContextInMemory::getAddressSize () const inline override virtual
Implements llvm::DWARFContext.
Definition at line 253 of file DWARFContext.h.
getAddrSection()
StringRef llvm::DWARFContextInMemory::getAddrSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 285 of file DWARFContext.h.
getAppleNamespacesSection()
const DWARFSection & llvm::DWARFContextInMemory::getAppleNamespacesSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 269 of file DWARFContext.h.
getAppleNamesSection()
const DWARFSection & llvm::DWARFContextInMemory::getAppleNamesSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 267 of file DWARFContext.h.
getAppleObjCSection()
const DWARFSection & llvm::DWARFContextInMemory::getAppleObjCSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 270 of file DWARFContext.h.
getAppleTypesSection()
const DWARFSection & llvm::DWARFContextInMemory::getAppleTypesSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 268 of file DWARFContext.h.
getARangeSection()
StringRef llvm::DWARFContextInMemory::getARangeSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 258 of file DWARFContext.h.
getDebugFrameSection()
StringRef llvm::DWARFContextInMemory::getDebugFrameSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 259 of file DWARFContext.h.
getGnuPubNamesSection()
StringRef llvm::DWARFContextInMemory::getGnuPubNamesSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 265 of file DWARFContext.h.
getGnuPubTypesSection()
StringRef llvm::DWARFContextInMemory::getGnuPubTypesSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 266 of file DWARFContext.h.
getInfoDWOSection()
const DWARFSection & llvm::DWARFContextInMemory::getInfoDWOSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 273 of file DWARFContext.h.
getInfoSection()
const DWARFSection & llvm::DWARFContextInMemory::getInfoSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 254 of file DWARFContext.h.
getLineDWOSection()
const DWARFSection & llvm::DWARFContextInMemory::getLineDWOSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 278 of file DWARFContext.h.
getLineSection()
const DWARFSection & llvm::DWARFContextInMemory::getLineSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 260 of file DWARFContext.h.
getLocDWOSection()
const DWARFSection & llvm::DWARFContextInMemory::getLocDWOSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 279 of file DWARFContext.h.
getLocSection()
const DWARFSection & llvm::DWARFContextInMemory::getLocSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 257 of file DWARFContext.h.
getPubNamesSection()
StringRef llvm::DWARFContextInMemory::getPubNamesSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 263 of file DWARFContext.h.
getPubTypesSection()
StringRef llvm::DWARFContextInMemory::getPubTypesSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 264 of file DWARFContext.h.
getRangeDWOSection()
StringRef llvm::DWARFContextInMemory::getRangeDWOSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 284 of file DWARFContext.h.
getRangeSection()
StringRef llvm::DWARFContextInMemory::getRangeSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 262 of file DWARFContext.h.
getStringDWOSection()
StringRef llvm::DWARFContextInMemory::getStringDWOSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 280 of file DWARFContext.h.
getStringOffsetDWOSection()
StringRef llvm::DWARFContextInMemory::getStringOffsetDWOSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 281 of file DWARFContext.h.
getStringSection()
StringRef llvm::DWARFContextInMemory::getStringSection () inline override virtual
Implements llvm::DWARFContext.
Definition at line 261 of file DWARFContext.h.
getTypesDWOSections()
const TypeSectionMap & llvm::DWARFContextInMemory::getTypesDWOSections () inline override virtual
Implements llvm::DWARFContext.
Definition at line 274 of file DWARFContext.h.
getTypesSections()
const TypeSectionMap & llvm::DWARFContextInMemory::getTypesSections () inline override virtual
Implements llvm::DWARFContext.
Definition at line 255 of file DWARFContext.h.
isLittleEndian()
bool llvm::DWARFContextInMemory::isLittleEndian () const inline override virtual
Implements llvm::DWARFContext.
Definition at line 252 of file DWARFContext.h.
Referenced by DWARFContextInMemory().
The documentation for this class was generated from the following files:
DWARFContext.h
DWARFContext.cpp