LLVM: llvm::DWARFDebugAranges Class Reference
LLVM API Documentation
llvm::DWARFDebugAranges Class Reference
#include <DWARFDebugAranges.h>
Public Member Functions
void generate (DWARFContext *CTX)
uint32_t findAddress (uint64_t Address) const
Detailed Description
Definition at line 21 of file DWARFDebugAranges.h.
Member Function Documentation
findAddress()
uint32_t DWARFDebugAranges::findAddress (uint64_t Address) const
Definition at line 112 of file DWARFDebugAranges.cpp.
References llvm::sys::path::const_iterator::begin.
generate()
void DWARFDebugAranges::generate (DWARFContext * CTX)
Definition at line 38 of file DWARFDebugAranges.cpp.
References clear(), llvm::DWARFContext::compile_units(), extract, llvm::DWARFContext::getARangeSection(), and llvm::DWARFContext::isLittleEndian().
Referenced by llvm::DWARFContext::getDebugAranges().
The documentation for this class was generated from the following files:
DWARFDebugAranges.h
DWARFDebugAranges.cpp