LLVM: llvm::HexagonMCInst Class Reference
LLVM API Documentation
llvm::HexagonMCInst Class Reference
#include <HexagonMCInst.h>
Public Member Functions
HexagonMCInst ()
HexagonMCInst (const MCInstrDesc &mcid)
void setPacketBegin (bool Y)
bool isPacketBegin () const
void setPacketEnd (bool Y)
bool isPacketEnd () const
void resetPacket ()
unsigned getUnits (const HexagonTargetMachine *TM) const
unsigned getType () const
MCInstrDesc const & getDesc () const
bool isCanon () const
bool isPrefix () const
bool isSolo () const
bool isConstExtended () const
unsigned short getCExtOpNum (void) const
bool isNewValue () const
bool hasNewValue () const
const MCOperand & getNewValue () const
unsigned getBitCount (void) const
Public Member Functions inherited from llvm::MCInst
MCInst ()
void setOpcode (unsigned Op)
unsigned getOpcode () const
void setLoc (SMLoc loc)
SMLoc getLoc () const
const MCOperand & getOperand (unsigned i) const
MCOperand & getOperand (unsigned i)
unsigned getNumOperands () const
void addOperand (const MCOperand &Op)
void clear ()
size_t size ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator insert (iterator I, const MCOperand &Op)
void print (raw_ostream &OS, const MCAsmInfo *MAI) const
void dump () const
void dump_pretty (raw_ostream &OS, const MCAsmInfo *MAI=nullptr, const MCInstPrinter *Printer=nullptr, StringRef Separator=" ") const
Dump the MCInst as prettily as possible using the additional MC structures, if given. Operators are separated by the Separator string.
Static Public Member Functions
static void AppendImplicitOperands (MCInst &MCI)
static std::bitset< 16 > GetImplicitBits (MCInst const &MCI)
static void SetImplicitBits (MCInst &MCI, std::bitset< 16 > Bits)
static void SanityCheckImplicitOperands (MCInst const &MCI)
Static Public Attributes
static const size_t packetBeginIndex = 0
static const size_t packetEndIndex = 1
Additional Inherited Members
Public Types inherited from llvm::MCInst
typedef SmallVectorImpl< MCOperand >::iterator iterator
typedef SmallVectorImpl< MCOperand >::const_iterator const_iterator
Detailed Description
Definition at line 25 of file HexagonMCInst.h.
Constructor & Destructor Documentation
HexagonMCInst() [1/2]
HexagonMCInst::HexagonMCInst () explicit
Definition at line 23 of file HexagonMCInst.cpp.
References llvm::MCInst::MCInst().
HexagonMCInst() [2/2]
HexagonMCInst::HexagonMCInst (const MCInstrDesc & mcid)
Definition at line 24 of file HexagonMCInst.cpp.
References llvm::MCInst::MCInst().
Member Function Documentation
AppendImplicitOperands()
void HexagonMCInst::AppendImplicitOperands (MCInst & MCI) static
Definition at line 26 of file HexagonMCInst.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateInst(), and llvm::MCInst::MCInst().
Referenced by llvm::HexagonAsmPrinter::EmitInstruction().
getBitCount()
unsigned HexagonMCInst::getBitCount (void) const
Definition at line 179 of file HexagonMCInst.cpp.
References llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, F, getDesc(), and llvm::MCInstrDesc::TSFlags.
getCExtOpNum()
unsigned short HexagonMCInst::getCExtOpNum (void) const
Definition at line 185 of file HexagonMCInst.cpp.
References llvm::HexagonII::ExtendableOpMask, llvm::HexagonII::ExtendableOpPos, F, getDesc(), and llvm::MCInstrDesc::TSFlags.
Referenced by isConstExtended().
getDesc()
MCInstrDesc const & HexagonMCInst::getDesc () const
Definition at line 80 of file HexagonMCInst.cpp.
References llvm::MCInst::getOpcode().
Referenced by llvm::HexagonMCCodeEmitter::EncodeInstruction(), getBitCount(), getCExtOpNum(), getNewValue(), getType(), hasNewValue(), isCanon(), isNewValue(), and isSolo().
GetImplicitBits()
std::bitset< 16 > HexagonMCInst::GetImplicitBits (MCInst const & MCI) static
Definition at line 31 of file HexagonMCInst.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCInst::MCInst(), and SanityCheckImplicitOperands().
Referenced by isPacketBegin(), isPacketEnd(), setPacketBegin(), and setPacketEnd().
getNewValue()
const MCOperand & HexagonMCInst::getNewValue () const
Definition at line 119 of file HexagonMCInst.cpp.
References F, getDesc(), llvm::MCInst::getOperand(), hasNewValue(), isNewValue(), llvm::MCOperand::isReg(), llvm::HexagonII::NewValueOpMask, llvm::HexagonII::NewValueOpPos, and llvm::MCInstrDesc::TSFlags.
getType()
unsigned HexagonMCInst::getType () const
Definition at line 83 of file HexagonMCInst.cpp.
References F, getDesc(), llvm::MCInstrDesc::TSFlags, llvm::HexagonII::TypeMask, and llvm::HexagonII::TypePos.
Referenced by isCanon(), and isPrefix().
getUnits()
unsigned HexagonMCInst::getUnits (const HexagonTargetMachine * TM) const
Definition at line 70 of file HexagonMCInst.cpp.
References llvm::InstrItineraryData::beginStage(), and llvm::InstrStage::getUnits().
hasNewValue()
bool HexagonMCInst::hasNewValue () const
Definition at line 113 of file HexagonMCInst.cpp.
References F, getDesc(), llvm::HexagonII::hasNewValueMask, llvm::HexagonII::hasNewValuePos, and llvm::MCInstrDesc::TSFlags.
Referenced by getNewValue().
isCanon()
bool HexagonMCInst::isCanon () const
Definition at line 90 of file HexagonMCInst.cpp.
References getDesc(), getType(), isPrefix(), and llvm::HexagonII::TypeENDLOOP.
isConstExtended()
bool HexagonMCInst::isConstExtended (void) const
Definition at line 137 of file HexagonMCInst.cpp.
References getCExtOpNum(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), and llvm::MCOperand::isImm().
isNewValue()
bool HexagonMCInst::isNewValue () const
Definition at line 107 of file HexagonMCInst.cpp.
References F, getDesc(), llvm::HexagonII::NewValueMask, llvm::HexagonII::NewValuePos, and llvm::MCInstrDesc::TSFlags.
Referenced by getNewValue().
isPacketBegin()
bool HexagonMCInst::isPacketBegin () const
Definition at line 48 of file HexagonMCInst.cpp.
References GetImplicitBits(), and packetBeginIndex.
isPacketEnd()
bool HexagonMCInst::isPacketEnd () const
Definition at line 59 of file HexagonMCInst.cpp.
References GetImplicitBits(), and packetEndIndex.
isPrefix()
bool HexagonMCInst::isPrefix () const
Definition at line 96 of file HexagonMCInst.cpp.
References getType(), and llvm::HexagonII::TypePREFIX.
Referenced by isCanon().
isSolo()
bool HexagonMCInst::isSolo () const
Definition at line 101 of file HexagonMCInst.cpp.
References F, getDesc(), llvm::HexagonII::SoloMask, llvm::HexagonII::SoloPos, and llvm::MCInstrDesc::TSFlags.
resetPacket()
void HexagonMCInst::resetPacket ()
Definition at line 64 of file HexagonMCInst.cpp.
References setPacketBegin(), and setPacketEnd().
SanityCheckImplicitOperands()
void llvm::HexagonMCInst::SanityCheckImplicitOperands (MCInst const & MCI) inline static
Definition at line 37 of file HexagonMCInst.h.
References llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), llvm::MCOperand::isInst(), and llvm::MCInst::MCInst().
Referenced by GetImplicitBits(), and SetImplicitBits().
SetImplicitBits()
void HexagonMCInst::SetImplicitBits (MCInst & MCI, std::bitset< 16 > Bits) static
Definition at line 37 of file HexagonMCInst.cpp.
References llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCInst::MCInst(), SanityCheckImplicitOperands(), and llvm::MCOperand::setImm().
Referenced by setPacketBegin(), and setPacketEnd().
setPacketBegin()
void HexagonMCInst::setPacketBegin (bool Y)
Definition at line 42 of file HexagonMCInst.cpp.
References GetImplicitBits(), packetBeginIndex, and SetImplicitBits().
Referenced by llvm::HexagonAsmPrinter::EmitInstruction(), llvm::HexagonInstPrinter::printInst(), and resetPacket().
setPacketEnd()
void HexagonMCInst::setPacketEnd (bool Y)
Definition at line 53 of file HexagonMCInst.cpp.
References GetImplicitBits(), packetEndIndex, and SetImplicitBits().
Referenced by llvm::HexagonAsmPrinter::EmitInstruction(), and resetPacket().
Member Data Documentation
packetBeginIndex
const size_t llvm::HexagonMCInst::packetBeginIndex = 0 static
Definition at line 47 of file HexagonMCInst.h.
Referenced by isPacketBegin(), and setPacketBegin().
packetEndIndex
const size_t llvm::HexagonMCInst::packetEndIndex = 1 static
Definition at line 50 of file HexagonMCInst.h.
Referenced by isPacketEnd(), and setPacketEnd().
The documentation for this class was generated from the following files:
HexagonMCInst.h
HexagonMCInst.cpp