LLVM: llvm::ListRecTy Class Reference
LLVM API Documentation
llvm::ListRecTy Class Reference
#include <Record.h>
Public Member Functions
RecTy * getElementType () const
Init * convertValue (UnsetInit *UI) override
Init * convertValue (BitInit *BI) override
Init * convertValue (BitsInit *BI) override
Init * convertValue (IntInit *II) override
Init * convertValue (StringInit *SI) override
Init * convertValue (ListInit *LI) override
Init * convertValue (VarBitInit *VB) override
Init * convertValue (DefInit *DI) override
Init * convertValue (DagInit *DI) override
Init * convertValue (UnOpInit *UI) override
Init * convertValue (BinOpInit *UI) override
Init * convertValue (TernOpInit *UI) override
Init * convertValue (TypedInit *TI) override
Init * convertValue (VarInit *VI) override
Init * convertValue (FieldInit *FI) override
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
bool baseClassOf (const RecTy *) const override
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static ListRecTy * get (RecTy *T)
Friends
ListRecTy * RecTy::getListTy ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
ListRecTy - 'list<Ty>' - Represent a list of values, all of which must be of the specified type.
Definition at line 294 of file Record.h.
Member Function Documentation
baseClassOf()
bool ListRecTy::baseClassOf (const RecTy * RHS) const override virtual
Reimplemented from llvm::RecTy.
Definition at line 312 of file Record.cpp.
References llvm::dyn_cast(), and llvm::RecTy::RecTy().
classof()
bool llvm::ListRecTy::classof (const RecTy * RT) inline static
Definition at line 300 of file Record.h.
References llvm::RecTy::getRecTyKind(), llvm::RecTy::ListRecTyKind, and llvm::RecTy::RecTy().
convertValue() [1/15]
Init * llvm::ListRecTy::convertValue (BinOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 317 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [2/15]
Init * llvm::ListRecTy::convertValue (BitInit * BI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 308 of file Record.h.
convertValue() [3/15]
Init * llvm::ListRecTy::convertValue (BitsInit * BI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 309 of file Record.h.
convertValue() [4/15]
Init * llvm::ListRecTy::convertValue (DagInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 315 of file Record.h.
convertValue() [5/15]
Init * llvm::ListRecTy::convertValue (DefInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 314 of file Record.h.
convertValue() [6/15]
Init * llvm::ListRecTy::convertValue (FieldInit * FI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 321 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [7/15]
Init * llvm::ListRecTy::convertValue (IntInit * II) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 310 of file Record.h.
convertValue() [8/15]
Init * ListRecTy::convertValue (ListInit * LI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 287 of file Record.cpp.
References llvm::Init::convertInitializerTo(), llvm::ListInit::get(), llvm::ListInit::getElement(), llvm::ListInit::getSize(), llvm::TypedInit::getType(), and llvm::isa().
convertValue() [9/15]
Init * llvm::ListRecTy::convertValue (StringInit * SI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 311 of file Record.h.
convertValue() [10/15]
Init * llvm::ListRecTy::convertValue (TernOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 318 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [11/15]
Init * ListRecTy::convertValue (TypedInit * TI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 304 of file Record.cpp.
References llvm::dyn_cast(), getElementType(), and llvm::TypedInit::getType().
convertValue() [12/15]
Init * llvm::ListRecTy::convertValue (UnOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 316 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [13/15]
Init * llvm::ListRecTy::convertValue (UnsetInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 307 of file Record.h.
convertValue() [14/15]
Init * llvm::ListRecTy::convertValue (VarBitInit * VB) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 313 of file Record.h.
convertValue() [15/15]
Init * llvm::ListRecTy::convertValue (VarInit * VI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 320 of file Record.h.
References llvm::RecTy::convertValue(), and VI.
get()
ListRecTy * llvm::ListRecTy::get (RecTy * T) inline static
Definition at line 304 of file Record.h.
References llvm::RecTy::RecTy(), and T.
getAsString()
std::string ListRecTy::getAsString () const override virtual
Implements llvm::RecTy.
Definition at line 283 of file Record.cpp.
References llvm::Init::getAsString().
getElementType()
RecTy * llvm::ListRecTy::getElementType () const inline
Definition at line 305 of file Record.h.
References llvm::RecTy::RecTy().
Referenced by convertValue(), llvm::BinOpInit::Fold(), and llvm::ListInit::Profile().
typeIsConvertibleTo()
bool llvm::ListRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline override virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 325 of file Record.h.
References llvm::RecTy::baseClassOf(), and llvm::RecTy::RecTy().
Friends And Related Symbol Documentation
RecTy::getListTy
ListRecTy * RecTy::getListTy () friend
The documentation for this class was generated from the following files:
Record.h
Record.cpp