LLVM: llvm::sys::fs::UniqueID Class Reference
LLVM API Documentation
llvm::sys::fs::UniqueID Class Reference
#include <FileSystem.h>
Public Member Functions
UniqueID ()
UniqueID (uint64_t Device, uint64_t File)
bool operator== (const UniqueID &Other) const
bool operator!= (const UniqueID &Other) const
bool operator< (const UniqueID &Other) const
uint64_t getDevice () const
uint64_t getFile () const
Detailed Description
Definition at line 118 of file FileSystem.h.
Constructor & Destructor Documentation
UniqueID() [1/2]
llvm::sys::fs::UniqueID::UniqueID () inline
Definition at line 123 of file FileSystem.h.
Referenced by operator!=(), operator<(), and operator==().
UniqueID() [2/2]
llvm::sys::fs::UniqueID::UniqueID (uint64_t Device, uint64_t File) inline
Definition at line 124 of file FileSystem.h.
Member Function Documentation
getDevice()
uint64_t llvm::sys::fs::UniqueID::getDevice () const inline
Definition at line 132 of file FileSystem.h.
getFile()
uint64_t llvm::sys::fs::UniqueID::getFile () const inline
Definition at line 133 of file FileSystem.h.
operator!=()
bool llvm::sys::fs::UniqueID::operator!= (const UniqueID & Other) const inline
Definition at line 128 of file FileSystem.h.
References UniqueID().
operator<()
bool llvm::sys::fs::UniqueID::operator< (const UniqueID & Other) const inline
Definition at line 129 of file FileSystem.h.
References UniqueID().
operator==()
bool llvm::sys::fs::UniqueID::operator== (const UniqueID & Other) const inline
Definition at line 125 of file FileSystem.h.
References UniqueID().
The documentation for this class was generated from the following file:
FileSystem.h