LLVM: llvm::DIELocList Class Reference
LLVM API Documentation
llvm::DIELocList Class Reference
#include <DIE.h>
Public Member Functions
DIELocList (size_t I)
size_t getValue () const
getValue - Grab the current index out.
void EmitValue (AsmPrinter *AP, dwarf::Form Form) const override
unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const override
void print (raw_ostream &O) const override
Public Member Functions inherited from llvm::DIEValue
Type getType () const
void dump () const
Static Public Member Functions
static bool classof (const DIEValue *E)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum Type {
isInteger , isString , isExpr , isLabel ,
isDelta , isEntry , isTypeSignature , isBlock ,
isLoc , isLocList
}
Protected Member Functions inherited from llvm::DIEValue
DIEValue (Type T)
virtual ~DIEValue ()
Protected Attributes inherited from llvm::DIEValue
Type Ty
Detailed Description
DIELocList - Represents a pointer to a location list in the debug_loc section.
Definition at line 559 of file DIE.h.
Constructor & Destructor Documentation
DIELocList()
llvm::DIELocList::DIELocList (size_t I) inline
Definition at line 564 of file DIE.h.
References llvm::DIEValue::DIEValue(), I, and llvm::DIEValue::isLocList.
Member Function Documentation
classof()
bool llvm::DIELocList::classof (const DIEValue * E) inline static
Definition at line 578 of file DIE.h.
References llvm::DIEValue::DIEValue(), llvm::DIEValue::getType(), and llvm::DIEValue::isLocList.
EmitValue()
void DIELocList::EmitValue (AsmPrinter * AP, dwarf::Form Form) const override virtual
EmitValue - Emit location data.
EmitValue - Emit label value.
Implements llvm::DIEValue.
Definition at line 577 of file DIE.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm::AsmPrinter::EmitLabelDifference(), llvm::AsmPrinter::EmitSectionOffset(), llvm::DwarfDebug::getDebugLocEntries(), llvm::DwarfDebug::getDebugLocSym(), llvm::AsmPrinter::getDwarfDebug(), llvm::AsmPrinter::MAI, and llvm::DwarfDebug::useSplitDwarf().
getValue()
size_t llvm::DIELocList::getValue () const inline
getValue - Grab the current index out.
Definition at line 567 of file DIE.h.
print()
void DIELocList::print (raw_ostream & O) const override virtual
Implements llvm::DIEValue.
Definition at line 588 of file DIE.cpp.
SizeOf()
unsigned DIELocList::SizeOf (AsmPrinter * AP, dwarf::Form Form) const override virtual
SizeOf - Determine size of location data in bytes.
Implements llvm::DIEValue.
Definition at line 567 of file DIE.cpp.
References llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_sec_offset, llvm::AsmPrinter::getDataLayout(), and llvm::DataLayout::getPointerSize().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp