LLVM: llvm::PBQP::RegAlloc::AllowedRegVector Class Reference
LLVM API Documentation
llvm::PBQP::RegAlloc::AllowedRegVector Class Reference
Holds a vector of the allowed physical regs for a vreg.
#include <RegAllocPBQP.h>
Public Member Functions
AllowedRegVector ()
AllowedRegVector (const std::vector< unsigned > &OptVec)
AllowedRegVector (const AllowedRegVector &Other)
AllowedRegVector (AllowedRegVector &&Other)
AllowedRegVector & operator= (const AllowedRegVector &Other)
AllowedRegVector & operator= (AllowedRegVector &&Other)
unsigned size () const
unsigned operator[] (size_t I) const
bool operator== (const AllowedRegVector &Other) const
bool operator!= (const AllowedRegVector &Other) const
Friends
hash_code hash_value (const AllowedRegVector &OptRegs)
Detailed Description
Holds a vector of the allowed physical regs for a vreg.
Definition at line 77 of file RegAllocPBQP.h.
Constructor & Destructor Documentation
AllowedRegVector() [1/4]
llvm::PBQP::RegAlloc::AllowedRegVector::AllowedRegVector () inline
Definition at line 81 of file RegAllocPBQP.h.
Referenced by AllowedRegVector(), AllowedRegVector(), hash_value, operator!=(), operator=(), operator=(), and operator==().
AllowedRegVector() [2/4]
llvm::PBQP::RegAlloc::AllowedRegVector::AllowedRegVector (const std::vector< unsigned > & OptVec) inline
Definition at line 83 of file RegAllocPBQP.h.
References size().
AllowedRegVector() [3/4]
llvm::PBQP::RegAlloc::AllowedRegVector::AllowedRegVector (const AllowedRegVector & Other) inline
Definition at line 88 of file RegAllocPBQP.h.
References AllowedRegVector().
AllowedRegVector() [4/4]
llvm::PBQP::RegAlloc::AllowedRegVector::AllowedRegVector (AllowedRegVector && Other) inline
Definition at line 93 of file RegAllocPBQP.h.
References AllowedRegVector().
Member Function Documentation
operator!=()
bool llvm::PBQP::RegAlloc::AllowedRegVector::operator!= (const AllowedRegVector & Other) const inline
Definition at line 118 of file RegAllocPBQP.h.
References AllowedRegVector().
operator=() [1/2]
AllowedRegVector & llvm::PBQP::RegAlloc::AllowedRegVector::operator= (AllowedRegVector && Other) inline
Definition at line 103 of file RegAllocPBQP.h.
References AllowedRegVector().
operator=() [2/2]
AllowedRegVector & llvm::PBQP::RegAlloc::AllowedRegVector::operator= (const AllowedRegVector & Other) inline
Definition at line 96 of file RegAllocPBQP.h.
References AllowedRegVector().
operator==()
bool llvm::PBQP::RegAlloc::AllowedRegVector::operator== (const AllowedRegVector & Other) const inline
Definition at line 112 of file RegAllocPBQP.h.
References AllowedRegVector().
operator[]()
unsigned llvm::PBQP::RegAlloc::AllowedRegVector::operator[] (size_t I) const inline
Definition at line 110 of file RegAllocPBQP.h.
References I.
size()
unsigned llvm::PBQP::RegAlloc::AllowedRegVector::size () const inline
Definition at line 109 of file RegAllocPBQP.h.
Referenced by AllowedRegVector().
Friends And Related Symbol Documentation
hash_value
hash_code hash_value (const AllowedRegVector & OptRegs) friend
Definition at line 127 of file RegAllocPBQP.h.
References AllowedRegVector(), llvm::hash_combine(), and llvm::hash_combine_range().
The documentation for this class was generated from the following file:
RegAllocPBQP.h