LLVM: llvm::SymbolRewriter::ExplicitRewriteDescriptor< DT, ValueType, Get > Class Template Reference
LLVM API Documentation
llvm::SymbolRewriter::ExplicitRewriteDescriptor< DT, ValueType, Get > Class Template Reference
Public Member Functions
ExplicitRewriteDescriptor (StringRef S, StringRef T, const bool Naked)
bool performOnModule (Module &M) override
Public Member Functions inherited from llvm::SymbolRewriter::RewriteDescriptor
virtual ~RewriteDescriptor ()
Type getType () const
Public Member Functions inherited from llvm::ilist_node< RewriteDescriptor >
RewriteDescriptor * getPrevNode ()
Get the previous node, or 0 for the list head.
RewriteDescriptor * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const RewriteDescriptor *RD)
Public Attributes
const std::string Source
const std::string Target
Additional Inherited Members
Public Types inherited from llvm::SymbolRewriter::RewriteDescriptor
enum class Type { Invalid , Function , GlobalVariable , NamedAlias }
Protected Member Functions inherited from llvm::SymbolRewriter::RewriteDescriptor
RewriteDescriptor (Type T)
Protected Member Functions inherited from llvm::ilist_node< RewriteDescriptor >
ilist_node ()
Detailed Description
template<RewriteDescriptor::Type DT, typename ValueType, ValueType *(llvm::Module::*)(StringRef) const Get>
class llvm::SymbolRewriter::ExplicitRewriteDescriptor< DT, ValueType, Get >
Definition at line 97 of file SymbolRewriter.cpp.
Constructor & Destructor Documentation
ExplicitRewriteDescriptor()
template<RewriteDescriptor::Type DT, typename ValueType, ValueType *(llvm::Module::*)(StringRef) const Get> llvm::SymbolRewriter::ExplicitRewriteDescriptor< DT, ValueType, Get >::ExplicitRewriteDescriptor (StringRef S, StringRef T, const bool Naked) inline
Definition at line 102 of file SymbolRewriter.cpp.
Member Function Documentation
classof()
template<RewriteDescriptor::Type DT, typename ValueType, ValueType *(llvm::Module::*)(StringRef) const Get> bool llvm::SymbolRewriter::ExplicitRewriteDescriptor< DT, ValueType, Get >::classof (const RewriteDescriptor * RD) inline static
Definition at line 108 of file SymbolRewriter.cpp.
performOnModule()
template<RewriteDescriptor::Type DT, typename ValueType, ValueType *(llvm::Module::*)(StringRef) const Get> bool llvm::SymbolRewriter::ExplicitRewriteDescriptor< DT, ValueType, Get >::performOnModule (Module & M) override virtual
Implements llvm::SymbolRewriter::RewriteDescriptor.
Definition at line 115 of file SymbolRewriter.cpp.
References Changed, llvm::dyn_cast(), llvm::SymbolRewriter::rewriteComdat(), Source, and Target.
Member Data Documentation
Source
template<RewriteDescriptor::Type DT, typename ValueType, ValueType *(llvm::Module::*)(StringRef) const Get> const std::string llvm::SymbolRewriter::ExplicitRewriteDescriptor< DT, ValueType, Get >::Source
Definition at line 99 of file SymbolRewriter.cpp.
Referenced by performOnModule().
Target
template<RewriteDescriptor::Type DT, typename ValueType, ValueType *(llvm::Module::*)(StringRef) const Get> const std::string llvm::SymbolRewriter::ExplicitRewriteDescriptor< DT, ValueType, Get >::Target
Definition at line 100 of file SymbolRewriter.cpp.
Referenced by performOnModule().
The documentation for this class was generated from the following file:
SymbolRewriter.cpp