LLVM: llvm::User Class Reference
LLVM API Documentation
llvm::User Class Reference
#include <User.h>
Classes
struct value_op_iterator
Iterator for directly iterating over the operand Values.
Public Types
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range< op_iterator > op_range
typedef iterator_range< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal , BasicBlockVal , FunctionVal , GlobalAliasVal ,
GlobalVariableVal , UndefValueVal , BlockAddressVal , ConstantExprVal ,
ConstantAggregateZeroVal , ConstantDataArrayVal , ConstantDataVectorVal , ConstantIntVal ,
ConstantFPVal , ConstantArrayVal , ConstantStructVal , ConstantVectorVal ,
ConstantPointerNullVal , MetadataAsValueVal , InlineAsmVal , InstructionVal ,
ConstantFirstVal = FunctionVal , ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl< const User > const_user_iterator
Public Member Functions
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Static Public Member Functions
static bool classof (const Value *V)
Protected Member Functions
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Protected Attributes
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Friends
template<unsigned>
struct HungoffOperandTraits
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Detailed Description
Definition at line 35 of file User.h.
Member Typedef Documentation
const_op_iterator
typedef const Use* llvm::User::const_op_iterator
Definition at line 115 of file User.h.
const_op_range
typedef iterator_range<const_op_iterator> llvm::User::const_op_range
Definition at line 117 of file User.h.
op_iterator
typedef Use* llvm::User::op_iterator
Definition at line 114 of file User.h.
op_range
typedef iterator_range<op_iterator> llvm::User::op_range
Definition at line 116 of file User.h.
Constructor & Destructor Documentation
User()
llvm::User::User (Type * ty, unsigned vty, Use * OpList, unsigned NumOps) inline protected
Definition at line 51 of file User.h.
References llvm::Value::NumOperands, and OperandList.
~User()
llvm::User::~User () inline
Definition at line 63 of file User.h.
References llvm::Value::NumOperands, OperandList, and llvm::Use::zap().
Member Function Documentation
allocHungoffUses()
Use * llvm::User::allocHungoffUses (unsigned N) const protected
Definition at line 42 of file User.cpp.
References llvm::Use::initTags(), and N.
classof()
bool llvm::User::classof (const Value * V) inline static
Definition at line 171 of file User.h.
References llvm::isa().
dropAllReferences()
void llvm::User::dropAllReferences () inline
Drop all references to operands.
This function is in charge of "letting go" of all objects that this User refers to. This allows one to 'delete' a whole class at a time, even though there may be circular references... First all references are dropped, and all use counts go to zero. Then everything is deleted for real. Note that no operations are valid on an object that has "dropped all references", except operator delete.
Definition at line 159 of file User.h.
References operands().
Referenced by llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), and llvm::expandRemainderUpTo64Bits().
dropHungoffUses()
void llvm::User::dropHungoffUses () inline protected
Definition at line 56 of file User.h.
References llvm::Value::NumOperands, OperandList, and llvm::Use::zap().
Referenced by llvm::IndirectBrInst::~IndirectBrInst(), llvm::LandingPadInst::~LandingPadInst(), llvm::PHINode::~PHINode(), and llvm::SwitchInst::~SwitchInst().
getNumOperands()
unsigned llvm::User::getNumOperands () const inline
Definition at line 109 of file User.h.
References llvm::Value::NumOperands.
Referenced by llvm::LandingPadInst::addClause(), llvm::MachineModuleInfo::AnalyzeModule(), llvm::PHINode::block_end(), llvm::PHINode::block_end(), llvm::BranchInst::clone_impl(), llvm::CallInst::clone_impl(), llvm::GetElementPtrInst::clone_impl(), llvm::InvokeInst::clone_impl(), llvm::ReturnInst::clone_impl(), DeleteDeadInstruction(), deleteDeadInstruction(), emitGlobalConstantArray(), emitGlobalConstantStruct(), EvaluateGEPOffsetExpression(), evaluateICmpRelation(), EvaluateStoreInto(), FindUsedValues(), findUsedValues(), findUsedValues(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), llvm::InstCombiner::FoldGEPICmp(), llvm::InstCombiner::FoldSelectOpOp(), GEPToVectorIndex(), llvm::ConstantExpr::getAsInstruction(), llvm::PHINode::getBasicBlockIndex(), getGEPInductionOperand(), llvm::SCEVExpander::getIVIncOperand(), getLoopPhiForCounter(), llvm::CallInst::getNumArgOperands(), llvm::InvokeInst::getNumArgOperands(), llvm::SwitchInst::getNumCases(), llvm::LandingPadInst::getNumClauses(), llvm::IndirectBrInst::getNumDestinations(), llvm::PHINode::getNumIncomingValues(), llvm::GEPOperator::getNumIndices(), llvm::GetElementPtrInst::getNumIndices(), llvm::IndirectBrInst::getNumSuccessors(), llvm::SwitchInst::getNumSuccessors(), GetOffsetFromIndex(), llvm::Constant::getRelocationInfo(), llvm::ReturnInst::getReturnValue(), llvm::ConstantVector::getSplatValue(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getWithOperands(), llvm::GetElementPtrInst::hasAllConstantIndices(), llvm::GetElementPtrInst::hasAllZeroIndices(), llvm::GEPOperator::hasIndices(), llvm::GetElementPtrInst::hasIndices(), llvm::BranchInst::isConditional(), llvm::Instruction::isIdenticalToWhenDefined(), isLikelyComplexAddressComputation(), IsPointerOffset(), isSafeSROAElementUse(), llvm::isSafeToSpeculativelyExecute(), llvm::Instruction::isSameOperationAs(), llvm::BranchInst::isUnconditional(), llvm::VariadicOperandTraits< SubClass, MINARITY >::op_begin(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::SwitchInst::removeCase(), llvm::IndirectBrInst::removeDestination(), llvm::PHINode::removeIncomingValue(), replaceUsesOfWith(), llvm::Constant::replaceUsesOfWithOnConstant(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::ConstantVector::replaceUsesOfWithOnConstant(), llvm::GlobalVariable::replaceUsesOfWithOnConstant(), llvm::DAGTypeLegalizer::run(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), SimplifyCondBranchToTwoReturns(), SinkThenElseCodeToEnd(), SRAGlobal(), stripGetElementPtr(), upgradeGlobalArray(), ValueIsOnlyUsedLocallyOrStoredToOneGlobal(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::InstCombiner::visitReturnInst().
getOperand()
Value * llvm::User::getOperand (unsigned i) const inline
Definition at line 89 of file User.h.
References llvm::Value::NumOperands, and OperandList.
Referenced by llvm::AliasSetTracker::add(), llvm::AliasSetTracker::add(), AddReachableCodeToWorklist(), llvm::MachineModuleInfo::AnalyzeModule(), CanPHITrans(), CheckForPhysRegDependency(), llvm::AddrSpaceCastInst::clone_impl(), llvm::AllocaInst::clone_impl(), llvm::AtomicCmpXchgInst::clone_impl(), llvm::AtomicRMWInst::clone_impl(), llvm::BitCastInst::clone_impl(), llvm::ExtractElementInst::clone_impl(), llvm::FPExtInst::clone_impl(), llvm::FPToSIInst::clone_impl(), llvm::FPToUIInst::clone_impl(), llvm::FPTruncInst::clone_impl(), llvm::InsertElementInst::clone_impl(), llvm::IntToPtrInst::clone_impl(), llvm::LoadInst::clone_impl(), llvm::PtrToIntInst::clone_impl(), llvm::SelectInst::clone_impl(), llvm::SExtInst::clone_impl(), llvm::ShuffleVectorInst::clone_impl(), llvm::SIToFPInst::clone_impl(), llvm::StoreInst::clone_impl(), llvm::TruncInst::clone_impl(), llvm::UIToFPInst::clone_impl(), llvm::VAArgInst::clone_impl(), llvm::ZExtInst::clone_impl(), CollectShuffleElements(), CollectSingleShuffleElements(), CombineBaseUpdate(), CombineVLDDUP(), llvm::InstCombiner::commonCastTransforms(), llvm::InstCombiner::commonPointerCastTransforms(), computeKnownBits(), llvm::ConstantFoldCompareInstruction(), ConstantFoldLoadInst(), llvm::ConstantFoldSelectInstruction(), llvm::ConvertDebugDeclareToDebugValue(), ConvertShiftToMul(), llvm::DecodeVPERMILPMask(), DecomposeGEPExpression(), DeleteDeadInstruction(), deleteDeadInstruction(), emitGlobalConstantArray(), emitGlobalConstantStruct(), emitGlobalConstantVector(), llvm::X86AsmPrinter::EmitInstruction(), EvaluateGEPOffsetExpression(), evaluateICmpRelation(), EvaluateStoreInto(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), ExtendUsesToFormExtLoad(), ExtractEquivalentCondition(), llvm::FCmpInst::FCmpInst(), llvm::FCmpInst::FCmpInst(), llvm::FCmpInst::FCmpInst(), FindInitTrampoline(), FindInitTrampolineFromAlloca(), llvm::SelectionDAGBuilder::FindMergedConditions(), FindSingleUseMultiplyFactors(), FindUsedValues(), findUsedValues(), findUsedValues(), llvm::InstCombiner::FoldAndOfFCmps(), llvm::InstCombiner::FoldAndOfICmps(), llvm::FoldBranchToCommonDest(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), foldConstantCastPair(), llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::InstCombiner::foldFMulConst(), llvm::InstCombiner::FoldGEPICmp(), llvm::InstCombiner::FoldICmpDivCst(), llvm::InstCombiner::FoldICmpShrCst(), foldLogOpOfMaskedICmpsHelper(), llvm::InstCombiner::FoldOrOfFCmps(), llvm::InstCombiner::FoldOrOfICmps(), foldSelectICmpAnd(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldSelectOpOp(), llvm::InstCombiner::FoldShiftByConstant(), foldUDivShl(), llvm::gep_type_begin(), llvm::gep_type_begin(), GEPToVectorIndex(), llvm::IndirectBrInst::getAddress(), llvm::IndirectBrInst::getAddress(), llvm::ExtractValueInst::getAggregateOperand(), llvm::ExtractValueInst::getAggregateOperand(), llvm::InsertValueInst::getAggregateOperand(), llvm::InsertValueInst::getAggregateOperand(), llvm::GlobalAlias::getAliasee(), llvm::CallInst::getArgOperand(), llvm::InvokeInst::getArgOperand(), llvm::AllocaInst::getArraySize(), llvm::AllocaInst::getArraySize(), getBinOpsForFactorization(), getCommonReturnValue(), llvm::AtomicCmpXchgInst::getCompareOperand(), llvm::AtomicCmpXchgInst::getCompareOperand(), llvm::SwitchInst::getCondition(), llvm::ExecutionEngine::getConstantValue(), llvm::SwitchInst::getDefaultDest(), getGEPInductionOperand(), llvm::PHINode::getIncomingValue(), llvm::InsertValueInst::getInsertedValueOperand(), llvm::InsertValueInst::getInsertedValueOperand(), llvm::SCEVExpander::getIVIncOperand(), getLoopPhiForCounter(), llvm::ShuffleVectorInst::getMask(), llvm::AtomicCmpXchgInst::getNewValOperand(), llvm::AtomicCmpXchgInst::getNewValOperand(), llvm::BinaryOperator::getNotArgument(), GetOffsetFromIndex(), llvm::LandingPadInst::getPersonalityFn(), llvm::AtomicCmpXchgInst::getPointerOperand(), llvm::AtomicCmpXchgInst::getPointerOperand(), llvm::AtomicRMWInst::getPointerOperand(), llvm::AtomicRMWInst::getPointerOperand(), llvm::GEPOperator::getPointerOperand(), llvm::GEPOperator::getPointerOperand(), llvm::GetElementPtrInst::getPointerOperand(), llvm::GetElementPtrInst::getPointerOperand(), llvm::LoadInst::getPointerOperand(), llvm::LoadInst::getPointerOperand(), llvm::PtrToIntInst::getPointerOperand(), llvm::PtrToIntInst::getPointerOperand(), llvm::PtrToIntOperator::getPointerOperand(), llvm::PtrToIntOperator::getPointerOperand(), llvm::StoreInst::getPointerOperand(), llvm::StoreInst::getPointerOperand(), llvm::VAArgInst::getPointerOperand(), llvm::VAArgInst::getPointerOperand(), llvm::Constant::getRelocationInfo(), llvm::ReturnInst::getReturnValue(), GetShiftedValue(), getShuffleAndOtherOprd(), llvm::ConstantVector::getSplatValue(), llvm::CastInst::getSrcTy(), llvm::IndirectBrInst::getSuccessor(), llvm::SwitchInst::getSuccessor(), llvm::AtomicRMWInst::getValOperand(), llvm::AtomicRMWInst::getValOperand(), getValueFromFromCondition(), llvm::StoreInst::getValueOperand(), llvm::StoreInst::getValueOperand(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getWithOperands(), llvm::GetElementPtrInst::hasAllConstantIndices(), llvm::GetElementPtrInst::hasAllZeroIndices(), hoistBeforePos(), llvm::BinaryOperator::init(), insertFastDiv(), isAllocSiteRemovable(), llvm::AllocaInst::isArrayAllocation(), isEliminableCastPair(), isExtractBitsCandidateUse(), isHighCostExpansion(), llvm::CastInst::isIntegerCast(), isLikelyComplexAddressComputation(), llvm::CastInst::isLosslessCast(), llvm::CastInst::isNoopCast(), llvm::CastInst::isNoopCast(), IsPointerOffset(), isProfitableToFoldUnconditional(), isSafeAndProfitableToSinkLoad(), isSafeSROAElementUse(), isSafeToEliminateVarargsCast(), llvm::isSafeToSpeculativelyExecute(), isSameCompare(), llvm::Instruction::isSameOperationAs(), llvm::FastISel::lowerCallTo(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerNegateToMultiply(), matchPairwiseReduction(), matchPairwiseReductionAtLevel(), MatchSelectPattern(), matchVectorSplittingReduction(), needsLFTR(), OptimizeAwayTrappingUsesOfLoads(), OptimizeCmpExpression(), llvm::FastISel::optimizeCmpPredicate(), OptimizeExtractBits(), OptimizeIntegerToVectorInsertions(), OptimizeIntToFloatBitCast(), OptimizeNoopCopyExpression(), llvm::PPCTargetLowering::PerformDAGCombine(), performNEONPostLDSTCombine(), performPostLD1Combine(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), llvm::AliasSetTracker::remove(), llvm::AliasSetTracker::remove(), replaceUsesOfWith(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::ConstantVector::replaceUsesOfWithOnConstant(), llvm::GlobalVariable::replaceUsesOfWithOnConstant(), reuseOrInsertFastDiv(), reuseTableCompare(), rewriteSingleStoreAlloca(), llvm::NVPTXLowerAggrCopies::runOnFunction(), llvm::UnifyFunctionExitNodes::runOnFunction(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), llvm::FastISel::selectExtractValue(), SimplifyAndOfICmps(), SimplifyAssociativeBinOp(), SimplifyICmpInst(), SimplifyOrOfICmps(), llvm::InstCombiner::simplifyRangeCheck(), SinkCast(), SinkShiftAndTruncate(), SinkThenElseCodeToEnd(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SRAGlobal(), stripGetElementPtr(), swapMayExposeCSEOpportunities(), tryPromoteAllocaToVector(), TryToShrinkGlobalToBoolean(), TryToSimplifyUncondBranchWithICmpInIt(), useDivRem(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFPToSI(), llvm::InstCombiner::visitFPToUI(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithCastAndCast(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitIntToPtr(), visitIVCast(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPtrToInt(), llvm::InstCombiner::visitReturnInst(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
getOperandUse() [1/2]
Use & llvm::User::getOperandUse (unsigned i) inline
Definition at line 104 of file User.h.
References llvm::Value::NumOperands, and OperandList.
getOperandUse() [2/2]
const Use & llvm::User::getOperandUse (unsigned i) const inline
Definition at line 100 of file User.h.
References llvm::Value::NumOperands, and OperandList.
Referenced by llvm::CallInst::getArgOperandUse(), llvm::CallInst::getArgOperandUse(), llvm::InvokeInst::getArgOperandUse(), llvm::InvokeInst::getArgOperandUse(), and processInstruction().
Op() [1/2]
template<int Idx> Use & llvm::User::Op () inline protected
Definition at line 82 of file User.h.
References OpFrom().
Referenced by llvm::BinaryConstantExpr::BinaryConstantExpr(), llvm::BinaryOperator::BinaryOperator(), llvm::BinaryOperator::BinaryOperator(), llvm::BinaryOperator::clone_impl(), llvm::FCmpInst::clone_impl(), llvm::ICmpInst::clone_impl(), llvm::CmpInst::CmpInst(), llvm::CmpInst::CmpInst(), llvm::CompareConstantExpr::CompareConstantExpr(), llvm::BinaryOperator::Create(), llvm::BinaryOperator::Create(), llvm::CmpInst::Create(), llvm::CmpInst::Create(), llvm::BinaryOperator::CreateFNeg(), llvm::BinaryOperator::CreateFNeg(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNot(), llvm::BinaryOperator::CreateNot(), llvm::BinaryOperator::CreateNSWNeg(), llvm::BinaryOperator::CreateNSWNeg(), llvm::BinaryOperator::CreateNUWNeg(), llvm::BinaryOperator::CreateNUWNeg(), llvm::BinaryOperator::DECLARE_TRANSPARENT_OPERAND_ACCESSORS(), llvm::ExtractElementConstantExpr::ExtractElementConstantExpr(), llvm::ExtractValueConstantExpr::ExtractValueConstantExpr(), llvm::BlockAddress::getBasicBlock(), llvm::CallInst::getCalledFunction(), llvm::InvokeInst::getCalledFunction(), llvm::CallInst::getCalledValue(), llvm::CallInst::getCalledValue(), llvm::InvokeInst::getCalledValue(), llvm::InvokeInst::getCalledValue(), llvm::BranchInst::getCondition(), llvm::SelectInst::getCondition(), llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::SelectInst::getFalseValue(), llvm::BlockAddress::getFunction(), llvm::ExtractElementInst::getIndexOperand(), llvm::ExtractElementInst::getIndexOperand(), llvm::GlobalVariable::getInitializer(), llvm::GlobalVariable::getInitializer(), llvm::InvokeInst::getNormalDest(), llvm::BranchInst::getSuccessor(), llvm::SelectInst::getTrueValue(), llvm::SelectInst::getTrueValue(), llvm::InvokeInst::getUnwindDest(), llvm::ResumeInst::getValue(), llvm::ExtractElementInst::getVectorOperand(), llvm::ExtractElementInst::getVectorOperand(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::GlobalVariable::GlobalVariable(), llvm::GlobalVariable::GlobalVariable(), llvm::InsertElementConstantExpr::InsertElementConstantExpr(), llvm::InsertValueConstantExpr::InsertValueConstantExpr(), llvm::CallInst::isInlineAsm(), llvm::ShuffleVectorInst::isValidOperands(), llvm::PHINode::removeIncomingValue(), llvm::BlockAddress::replaceUsesOfWithOnConstant(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::SelectConstantExpr::SelectConstantExpr(), llvm::CallInst::setCalledFunction(), llvm::InvokeInst::setCalledFunction(), llvm::BranchInst::setCondition(), llvm::GlobalVariable::setInitializer(), llvm::InvokeInst::setNormalDest(), llvm::BranchInst::setSuccessor(), llvm::InvokeInst::setSuccessor(), llvm::InvokeInst::setUnwindDest(), llvm::ShuffleVectorConstantExpr::ShuffleVectorConstantExpr(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::BinaryOperator::swapOperands(), llvm::FCmpInst::swapOperands(), llvm::ICmpInst::swapOperands(), llvm::BranchInst::swapSuccessors(), llvm::UnaryConstantExpr::UnaryConstantExpr(), llvm::UnaryInstruction::UnaryInstruction(), and llvm::UnaryInstruction::UnaryInstruction().
Op() [2/2]
template<int Idx> const Use & llvm::User::Op () const inline protected
Definition at line 85 of file User.h.
References OpFrom().
op_begin() [1/2]
op_iterator llvm::User::op_begin () inline
Definition at line 119 of file User.h.
References OperandList.
Referenced by llvm::AddLandingPadInfo(), AddReachableCodeToWorklist(), llvm::CallInst::arg_operands(), llvm::CallInst::arg_operands(), llvm::InvokeInst::arg_operands(), llvm::InvokeInst::arg_operands(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), llvm::AtomicRMWInst::AtomicRMWInst(), llvm::AtomicRMWInst::AtomicRMWInst(), llvm::BinaryOperator::BinaryOperator(), llvm::BinaryOperator::BinaryOperator(), llvm::PHINode::block_begin(), llvm::PHINode::block_begin(), callHasFloatingPointArgument(), llvm::objcarc::CanUse(), changeToCall(), llvm::CmpInst::CmpInst(), llvm::CmpInst::CmpInst(), llvm::ConstantArray::ConstantArray(), llvm::ConstantStruct::ConstantStruct(), llvm::ConstantVector::ConstantVector(), DecomposeGEPExpression(), llvm::EmitGEPOffset(), llvm::FoldReturnIntoUncondBranch(), llvm::gep_type_begin(), llvm::gep_type_begin(), llvm::ConstantExpr::getAsInstruction(), getConstantEvolvingPHIOperands(), llvm::PHINode::getIncomingBlock(), llvm::SCEVExpander::getIVIncOperand(), llvm::Use::getOperandNo(), llvm::GlobalVariable::GlobalVariable(), llvm::GlobalVariable::GlobalVariable(), llvm::GEPOperator::idx_begin(), llvm::GEPOperator::idx_begin(), llvm::GetElementPtrInst::idx_begin(), llvm::GetElementPtrInst::idx_begin(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), llvm::Instruction::isIdenticalToWhenDefined(), operands(), operands(), llvm::PHINode::removeIncomingValue(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), value_op_begin(), and llvm::InstCombiner::visitGetElementPtrInst().
op_begin() [2/2]
const_op_iterator llvm::User::op_begin () const inline
Definition at line 120 of file User.h.
References OperandList.
op_end() [1/2]
op_iterator llvm::User::op_end () inline
Definition at line 121 of file User.h.
References llvm::Value::NumOperands, and OperandList.
Referenced by llvm::AddLandingPadInfo(), AddReachableCodeToWorklist(), llvm::CallInst::arg_operands(), llvm::CallInst::arg_operands(), llvm::InvokeInst::arg_operands(), llvm::InvokeInst::arg_operands(), callHasFloatingPointArgument(), llvm::objcarc::CanUse(), changeToCall(), llvm::ConstantArray::ConstantArray(), llvm::ConstantStruct::ConstantStruct(), llvm::ConstantVector::ConstantVector(), DecomposeGEPExpression(), llvm::EmitGEPOffset(), llvm::FoldReturnIntoUncondBranch(), llvm::gep_type_end(), llvm::gep_type_end(), llvm::ConstantExpr::getAsInstruction(), getConstantEvolvingPHIOperands(), llvm::SCEVExpander::getIVIncOperand(), llvm::GEPOperator::idx_end(), llvm::GEPOperator::idx_end(), llvm::GetElementPtrInst::idx_end(), llvm::GetElementPtrInst::idx_end(), llvm::Instruction::isIdenticalToWhenDefined(), operands(), operands(), llvm::PHINode::removeIncomingValue(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), value_op_end(), and llvm::InstCombiner::visitGetElementPtrInst().
op_end() [2/2]
const_op_iterator llvm::User::op_end () const inline
Definition at line 122 of file User.h.
References llvm::Value::NumOperands, and OperandList.
operand_values()
iterator_range< value_op_iterator > llvm::User::operand_values () inline
Definition at line 147 of file User.h.
References value_op_begin(), and value_op_end().
operands() [1/2]
op_range llvm::User::operands () inline
Definition at line 123 of file User.h.
References op_begin(), and op_end().
Referenced by llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), llvm::AtomicRMWInst::AtomicRMWInst(), llvm::AtomicRMWInst::AtomicRMWInst(), llvm::BinaryOperator::BinaryOperator(), llvm::BinaryOperator::BinaryOperator(), llvm::CmpInst::CmpInst(), llvm::CmpInst::CmpInst(), contains(), dropAllReferences(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), upgradeGlobalArray(), and llvm::InstCombiner::visitGetElementPtrInst().
operands() [2/2]
const_op_range llvm::User::operands () const inline
Definition at line 126 of file User.h.
References op_begin(), and op_end().
operator delete() [1/3]
void llvm::User::operator delete (void * , unsigned) inline
Placement delete - required by std, but never called.
Definition at line 69 of file User.h.
References llvm_unreachable.
operator delete() [2/3]
void llvm::User::operator delete (void * , unsigned , bool) inline
Placement delete - required by std, but never called.
Definition at line 73 of file User.h.
References llvm_unreachable.
operator delete() [3/3]
void llvm::User::operator delete (void * Usr)
Free memory allocated for User and Use objects.
Definition at line 71 of file User.cpp.
References llvm::Value::NumOperands.
operator new()
void * llvm::User::operator new (size_t s, unsigned Us) protected
Definition at line 56 of file User.cpp.
References llvm::Use::initTags(), llvm::Value::NumOperands, and OperandList.
OpFrom()
template<int Idx, typename U> Use & llvm::User::OpFrom (const U * that) inline static protected
Definition at line 77 of file User.h.
Referenced by Op(), and Op().
replaceUsesOfWith()
void llvm::User::replaceUsesOfWith (Value * From, Value * To)
Replace uses of one Value with another.
Replaces all references to the "From" definition with references to the "To" definition.
Definition at line 23 of file User.cpp.
References getNumOperands(), getOperand(), llvm::isa(), and setOperand().
Referenced by llvm::InstCombiner::FoldSPFofSPF(), OptimizeGlobalAddressOfMalloc(), and truncateIVUse().
setOperand()
void llvm::User::setOperand (unsigned i, Value * Val) inline
Definition at line 93 of file User.h.
References llvm::isa(), llvm::Value::NumOperands, and OperandList.
Referenced by llvm::InstCombiner::commonPointerCastTransforms(), ConvertShiftToMul(), DeleteDeadInstruction(), deleteDeadInstruction(), llvm::InstCombiner::FoldICmpDivCst(), llvm::InstCombiner::FoldICmpShrCst(), llvm::FoldReturnIntoUncondBranch(), GetShiftedValue(), llvm::InlineFunction(), LowerNegateToMultiply(), mergeEmptyReturnBlocks(), ProcessUMulZExtIdiom(), replaceUsesOfWith(), llvm::BlockAddress::replaceUsesOfWithOnConstant(), llvm::GlobalVariable::replaceUsesOfWithOnConstant(), llvm::IndirectBrInst::setAddress(), llvm::GlobalAlias::setAliasee(), llvm::CallInst::setArgOperand(), llvm::InvokeInst::setArgOperand(), llvm::SwitchInst::setCondition(), llvm::SwitchInst::setDefaultDest(), llvm::PHINode::setIncomingValue(), llvm::Function::setPrefixData(), llvm::Function::setPrologueData(), llvm::IndirectBrInst::setSuccessor(), llvm::SwitchInst::setSuccessor(), SinkThenElseCodeToEnd(), SpeculativelyExecuteBB(), TryToSimplifyUncondBranchWithICmpInIt(), updateOperand(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitReturnInst(), llvm::InstCombiner::visitSelectInstWithICmp(), and llvm::InstCombiner::visitShuffleVectorInst().
value_op_begin()
value_op_iterator llvm::User::value_op_begin () inline
Definition at line 141 of file User.h.
References op_begin().
Referenced by operand_values().
value_op_end()
value_op_iterator llvm::User::value_op_end () inline
Definition at line 144 of file User.h.
References op_end().
Referenced by operand_values().
Friends And Related Symbol Documentation
HungoffOperandTraits
template<unsigned> friend struct HungoffOperandTraits friend
Definition at line 39 of file User.h.
References HungoffOperandTraits.
Referenced by HungoffOperandTraits.
Member Data Documentation
OperandList
Use* llvm::User::OperandList protected
This is a pointer to the array of Uses for this User.
For nodes of fixed arity (e.g. a binary operator) this array will live prefixed to some derived class instance. For nodes of resizable variable arity (e.g. PHINodes, SwitchInst etc.), this memory will be dynamically allocated and should be destroyed by the classes' virtual dtor.
Definition at line 48 of file User.h.
Referenced by llvm::LandingPadInst::addClause(), llvm::IndirectBrInst::addDestination(), dropHungoffUses(), llvm::LandingPadInst::getClause(), getOperand(), getOperandUse(), getOperandUse(), llvm::LandingPadInst::isCatch(), llvm::LandingPadInst::isFilter(), op_begin(), op_begin(), op_end(), op_end(), operator new(), llvm::SwitchInst::removeCase(), llvm::IndirectBrInst::removeDestination(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::ConstantVector::replaceUsesOfWithOnConstant(), setOperand(), User(), and ~User().
The documentation for this class was generated from the following files:
User.h
User.cpp