LLVM: llvm::FastMathFlags Class Reference
LLVM API Documentation
llvm::FastMathFlags Class Reference
Convenience struct for specifying and reasoning about fast-math flags.
#include <Operator.h>
Public Types
enum {
UnsafeAlgebra = (1 << 0) , NoNaNs = (1 << 1) , NoInfs = (1 << 2) , NoSignedZeros = (1 << 3) ,
AllowReciprocal = (1 << 4)
}
Public Member Functions
FastMathFlags ()
bool any ()
Whether any flag is set.
void clear ()
Set all the flags to false.
bool noNaNs ()
Flag queries.
bool noInfs ()
bool noSignedZeros ()
bool allowReciprocal ()
bool unsafeAlgebra ()
void setNoNaNs ()
Flag setters.
void setNoInfs ()
void setNoSignedZeros ()
void setAllowReciprocal ()
void setUnsafeAlgebra ()
void operator&= (const FastMathFlags &OtherFlags)
Friends
class FPMathOperator
Detailed Description
Convenience struct for specifying and reasoning about fast-math flags.
Definition at line 165 of file Operator.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
UnsafeAlgebra
NoNaNs
NoInfs
NoSignedZeros
AllowReciprocal
Definition at line 172 of file Operator.h.
Constructor & Destructor Documentation
FastMathFlags()
llvm::FastMathFlags::FastMathFlags () inline
Definition at line 180 of file Operator.h.
Member Function Documentation
allowReciprocal()
bool llvm::FastMathFlags::allowReciprocal () inline
Definition at line 193 of file Operator.h.
References AllowReciprocal.
any()
bool llvm::FastMathFlags::any () inline
Whether any flag is set.
Definition at line 184 of file Operator.h.
clear()
void llvm::FastMathFlags::clear () inline
Set all the flags to false.
Definition at line 187 of file Operator.h.
noInfs()
bool llvm::FastMathFlags::noInfs () inline
Definition at line 191 of file Operator.h.
References NoInfs.
Referenced by SimplifyFAddInst(), and SimplifyFSubInst().
noNaNs()
bool llvm::FastMathFlags::noNaNs () inline
Flag queries.
Definition at line 190 of file Operator.h.
References NoNaNs.
Referenced by SimplifyFAddInst(), SimplifyFMulInst(), and SimplifyFSubInst().
noSignedZeros()
bool llvm::FastMathFlags::noSignedZeros () inline
Definition at line 192 of file Operator.h.
References NoSignedZeros.
Referenced by SimplifyFAddInst(), SimplifyFMulInst(), and SimplifyFSubInst().
operator&=()
void llvm::FastMathFlags::operator&= (const FastMathFlags & OtherFlags) inline
Definition at line 209 of file Operator.h.
setAllowReciprocal()
void llvm::FastMathFlags::setAllowReciprocal () inline
Definition at line 200 of file Operator.h.
References AllowReciprocal.
Referenced by setUnsafeAlgebra().
setNoInfs()
void llvm::FastMathFlags::setNoInfs () inline
Definition at line 198 of file Operator.h.
References NoInfs.
Referenced by setUnsafeAlgebra().
setNoNaNs()
void llvm::FastMathFlags::setNoNaNs () inline
Flag setters.
Definition at line 197 of file Operator.h.
References NoNaNs.
Referenced by setUnsafeAlgebra().
setNoSignedZeros()
void llvm::FastMathFlags::setNoSignedZeros () inline
Definition at line 199 of file Operator.h.
References NoSignedZeros.
Referenced by setUnsafeAlgebra().
setUnsafeAlgebra()
void llvm::FastMathFlags::setUnsafeAlgebra () inline
Definition at line 201 of file Operator.h.
References setAllowReciprocal(), setNoInfs(), setNoNaNs(), setNoSignedZeros(), and UnsafeAlgebra.
unsafeAlgebra()
bool llvm::FastMathFlags::unsafeAlgebra () inline
Definition at line 194 of file Operator.h.
References UnsafeAlgebra.
Friends And Related Symbol Documentation
FPMathOperator
friend class FPMathOperator friend
Definition at line 167 of file Operator.h.
References F, and FPMathOperator.
Referenced by FPMathOperator.
The documentation for this class was generated from the following file:
Operator.h