LLVM: llvm::MachineLoop Class Reference
LLVM API Documentation
llvm::MachineLoop Class Reference
#include <MachineLoopInfo.h>
Public Member Functions
MachineLoop ()
MachineBasicBlock * getTopBlock ()
MachineBasicBlock * getBottomBlock ()
void dump () const
Public Member Functions inherited from llvm::LoopBase< MachineBasicBlock, MachineLoop >
~LoopBase ()
unsigned getLoopDepth () const
MachineBasicBlock * getHeader () const
MachineLoop * getParentLoop () const
void setParentLoop (MachineLoop *L)
setParentLoop is a raw interface for bypassing addChildLoop.
bool contains (const MachineLoop *L) const
const std::vector< MachineLoop * > & getSubLoops () const
std::vector< MachineLoop * > & getSubLoopsVector ()
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
const std::vector< MachineBasicBlock * > & getBlocks () const
block_iterator block_begin () const
block_iterator block_end () const
unsigned getNumBlocks () const
getNumBlocks - Get the number of blocks in this loop in constant time.
bool isLoopExiting (const MachineBasicBlock *BB) const
unsigned getNumBackEdges () const
void getExitingBlocks (SmallVectorImpl< MachineBasicBlock * > &ExitingBlocks) const
MachineBasicBlock * getExitingBlock () const
void getExitBlocks (SmallVectorImpl< MachineBasicBlock * > &ExitBlocks) const
MachineBasicBlock * getExitBlock () const
void getExitEdges (SmallVectorImpl< Edge > &ExitEdges) const
getExitEdges - Return all pairs of (inside_block,outside_block).
MachineBasicBlock * getLoopPreheader () const
MachineBasicBlock * getLoopPredecessor () const
MachineBasicBlock * getLoopLatch () const
void getLoopLatches (SmallVectorImpl< MachineBasicBlock * > &LoopLatches) const
void addBasicBlockToLoop (MachineBasicBlock *NewBB, LoopInfoBase< MachineBasicBlock, MachineLoop > &LI)
void replaceChildLoopWith (MachineLoop *OldChild, MachineLoop *NewChild)
void addChildLoop (MachineLoop *NewChild)
MachineLoop * removeChildLoop (iterator I)
void addBlockEntry (MachineBasicBlock *BB)
void reverseBlock (unsigned from)
reverseBlocks - interface to reverse Blocks[from, end of loop] in this loop
void reserveBlocks (unsigned size)
reserveBlocks- interface to do reserve() for Blocks
void moveToHeader (MachineBasicBlock *BB)
void removeBlockFromLoop (MachineBasicBlock *BB)
void verifyLoop () const
verifyLoop - Verify loop structure
void verifyLoopNest (DenseSet< const MachineLoop * > *Loops) const
verifyLoop - Verify loop structure of this loop and all nested loops.
void print (raw_ostream &OS, unsigned Depth=0) const
Friends
class LoopInfoBase< MachineBasicBlock, MachineLoop >
Additional Inherited Members
Public Types inherited from llvm::LoopBase< MachineBasicBlock, MachineLoop >
typedef std::vector< MachineLoop * >::const_iterator iterator
typedef std::vector< MachineLoop * >::const_reverse_iterator reverse_iterator
typedef std::vector< MachineBasicBlock * >::const_iterator block_iterator
typedef std::pair< const MachineBasicBlock *, const MachineBasicBlock * > Edge
Edge type.
Detailed Description
Definition at line 45 of file MachineLoopInfo.h.
Constructor & Destructor Documentation
MachineLoop()
llvm::MachineLoop::MachineLoop ()
References getBottomBlock(), and getTopBlock().
Referenced by LoopInfoBase< MachineBasicBlock, MachineLoop >.
Member Function Documentation
dump()
void MachineLoop::dump () const
Definition at line 78 of file MachineLoopInfo.cpp.
References llvm::dbgs(), and llvm::LoopBase< MachineBasicBlock, MachineLoop >::print().
getBottomBlock()
MachineBasicBlock * MachineLoop::getBottomBlock ()
getBottomBlock - Return the "bottom" block in the loop, which is the last block in the linear layout, ignoring any parts of the loop not contiguous with the part the contains the header.
Definition at line 63 of file MachineLoopInfo.cpp.
References llvm::LoopBase< MachineBasicBlock, MachineLoop >::contains(), llvm::MachineFunction::end(), llvm::LoopBase< MachineBasicBlock, MachineLoop >::getHeader(), and llvm::MachineBasicBlock::getParent().
Referenced by MachineLoop().
getTopBlock()
MachineBasicBlock * MachineLoop::getTopBlock ()
getTopBlock - Return the "top" block in the loop, which is the first block in the linear layout, ignoring any parts of the loop not contiguous with the part the contains the header.
Definition at line 49 of file MachineLoopInfo.cpp.
References llvm::MachineFunction::begin(), llvm::LoopBase< MachineBasicBlock, MachineLoop >::contains(), llvm::LoopBase< MachineBasicBlock, MachineLoop >::getHeader(), and llvm::MachineBasicBlock::getParent().
Referenced by MachineLoop().
Friends And Related Symbol Documentation
LoopInfoBase< MachineBasicBlock, MachineLoop >
friend class LoopInfoBase< MachineBasicBlock, MachineLoop > friend
Definition at line 59 of file MachineLoopInfo.h.
References MachineLoop().
The documentation for this class was generated from the following files:
MachineLoopInfo.h
MachineLoopInfo.cpp