LLVM: llvm::SparcTargetStreamer Class Reference
LLVM API Documentation
llvm::SparcTargetStreamer Class Reference abstract
#include <SparcTargetStreamer.h>
Public Member Functions
SparcTargetStreamer (MCStreamer &S)
virtual void emitSparcRegisterIgnore (unsigned reg)=0
Emit ".register <reg>, #ignore".
virtual void emitSparcRegisterScratch (unsigned reg)=0
Emit ".register <reg>, #scratch".
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
const MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 17 of file SparcTargetStreamer.h.
Constructor & Destructor Documentation
SparcTargetStreamer()
SparcTargetStreamer::SparcTargetStreamer (MCStreamer & S)
Definition at line 21 of file SparcTargetStreamer.cpp.
References llvm::MCTargetStreamer::MCTargetStreamer().
Referenced by llvm::SparcTargetAsmStreamer::SparcTargetAsmStreamer(), and llvm::SparcTargetELFStreamer::SparcTargetELFStreamer().
Member Function Documentation
emitSparcRegisterIgnore()
virtual void llvm::SparcTargetStreamer::emitSparcRegisterIgnore (unsigned reg) pure virtual
Emit ".register <reg>, #ignore".
Implemented in llvm::SparcTargetAsmStreamer, and llvm::SparcTargetELFStreamer.
emitSparcRegisterScratch()
virtual void llvm::SparcTargetStreamer::emitSparcRegisterScratch (unsigned reg) pure virtual
Emit ".register <reg>, #scratch".
Implemented in llvm::SparcTargetAsmStreamer, and llvm::SparcTargetELFStreamer.
The documentation for this class was generated from the following files:
SparcTargetStreamer.h
SparcTargetStreamer.cpp