LLVM: llvm::GlobalAlias Class Reference
LLVM API Documentation
llvm::GlobalAlias Class Reference
#include <GlobalAlias.h>
Public Member Functions
void * operator new (size_t s)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Provide fast operand accessors.
void removeFromParent () override
void eraseFromParent () override
void setAliasee (Constant *Aliasee)
These methods retrive and set alias target.
const Constant * getAliasee () const
Constant * getAliasee ()
const GlobalObject * getBaseObject () const
GlobalObject * getBaseObject ()
const GlobalObject * getBaseObject (const DataLayout &DL, APInt &Offset) const
GlobalObject * getBaseObject (const DataLayout &DL, APInt &Offset)
Public Member Functions inherited from llvm::GlobalValue
~GlobalValue ()
unsigned getAlignment () const
bool hasUnnamedAddr () const
void setUnnamedAddr (bool Val)
bool hasComdat () const
Comdat * getComdat ()
const Comdat * getComdat () const
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
bool isThreadLocal () const
If the value is "Thread Local", its value isn't shared by the threads.
void setThreadLocal (bool Val)
void setThreadLocalMode (ThreadLocalMode Val)
ThreadLocalMode getThreadLocalMode () const
DLLStorageClassTypes getDLLStorageClass () const
bool hasDLLImportStorageClass () const
bool hasDLLExportStorageClass () const
void setDLLStorageClass (DLLStorageClassTypes C)
bool hasSection () const
const char * getSection () const
PointerType * getType () const
Global values are always pointers.
bool hasExternalLinkage () const
bool hasAvailableExternallyLinkage () const
bool hasLinkOnceLinkage () const
bool hasLinkOnceODRLinkage () const
bool hasWeakLinkage () const
bool hasWeakAnyLinkage () const
bool hasWeakODRLinkage () const
bool hasAppendingLinkage () const
bool hasInternalLinkage () const
bool hasPrivateLinkage () const
bool hasLocalLinkage () const
bool hasExternalWeakLinkage () const
bool hasCommonLinkage () const
void setLinkage (LinkageTypes LT)
LinkageTypes getLinkage () const
bool isDiscardableIfUnused () const
bool mayBeOverridden () const
bool isWeakForLinker () const
virtual void copyAttributesFrom (const GlobalValue *Src)
void destroyConstant () override
Override from Constant class.
bool isDeclaration () const
bool isDeclarationForLinker () const
Module * getParent ()
Get the module that this global value is contained inside of...
const Module * getParent () const
const DataLayout * getDataLayout () const
bool isMaterializable () const
bool isDematerializable () const
std::error_code materialize ()
void Dematerialize ()
Public Member Functions inherited from llvm::Constant
bool isNullValue () const
bool isOneValue () const
Returns true if the value is one.
bool isAllOnesValue () const
bool isNegativeZeroValue () const
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool canTrap () const
bool isThreadDependent () const
isThreadDependent - Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
PossibleRelocationsTy getRelocationInfo () const
Constant * getAggregateElement (unsigned Elt) const
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
const APInt & getUniqueInteger () const
virtual void replaceUsesOfWithOnConstant (Value *, Value *, Use *)
void removeDeadConstantUsers () const
Constant * stripPointerCasts ()
const Constant * stripPointerCasts () const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Public Member Functions inherited from llvm::ilist_node< GlobalAlias >
GlobalAlias * getPrevNode ()
Get the previous node, or 0 for the list head.
GlobalAlias * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static GlobalAlias * create (Type *Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine &Name, Constant *Aliasee, Module *Parent)
static GlobalAlias * create (Type *Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine &Name, Module *Parent)
static GlobalAlias * create (Type *Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine &Name, GlobalValue *Aliasee)
static GlobalAlias * create (LinkageTypes Linkage, const Twine &Name, GlobalValue *Aliasee)
static GlobalAlias * create (const Twine &Name, GlobalValue *Aliasee)
static bool isValidLinkage (LinkageTypes L)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::GlobalValue
static LinkageTypes getLinkOnceLinkage (bool ODR)
static LinkageTypes getWeakLinkage (bool ODR)
static bool isExternalLinkage (LinkageTypes Linkage)
static bool isAvailableExternallyLinkage (LinkageTypes Linkage)
static bool isLinkOnceODRLinkage (LinkageTypes Linkage)
static bool isLinkOnceLinkage (LinkageTypes Linkage)
static bool isWeakAnyLinkage (LinkageTypes Linkage)
static bool isWeakODRLinkage (LinkageTypes Linkage)
static bool isWeakLinkage (LinkageTypes Linkage)
static bool isAppendingLinkage (LinkageTypes Linkage)
static bool isInternalLinkage (LinkageTypes Linkage)
static bool isPrivateLinkage (LinkageTypes Linkage)
static bool isLocalLinkage (LinkageTypes Linkage)
static bool isExternalWeakLinkage (LinkageTypes Linkage)
static bool isCommonLinkage (LinkageTypes Linkage)
static bool isDiscardableIfUnused (LinkageTypes Linkage)
static bool mayBeOverridden (LinkageTypes Linkage)
static bool isWeakForLinker (LinkageTypes Linkage)
static StringRef getRealLinkageName (StringRef Name)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
static Constant * getAllOnesValue (Type *Ty)
Get the all ones value.
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Friends
class SymbolTableListTraits< GlobalAlias, Module >
Additional Inherited Members
Public Types inherited from llvm::GlobalValue
enum LinkageTypes {
ExternalLinkage = 0 , AvailableExternallyLinkage , LinkOnceAnyLinkage , LinkOnceODRLinkage ,
WeakAnyLinkage , WeakODRLinkage , AppendingLinkage , InternalLinkage ,
PrivateLinkage , ExternalWeakLinkage , CommonLinkage
}
An enumeration for the kinds of linkage for global values.
enum VisibilityTypes { DefaultVisibility = 0 , HiddenVisibility , ProtectedVisibility }
An enumeration for the kinds of visibility of global values.
enum DLLStorageClassTypes { DefaultStorageClass = 0 , DLLImportStorageClass = 1 , DLLExportStorageClass = 2 }
Storage classes of global values for PE targets.
enum ThreadLocalMode {
NotThreadLocal = 0 , GeneralDynamicTLSModel , LocalDynamicTLSModel , InitialExecTLSModel ,
LocalExecTLSModel
}
Public Types inherited from llvm::Constant
enum PossibleRelocationsTy { NoRelocation = 0 , LocalRelocation = 1 , GlobalRelocations = 2 }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range< op_iterator > op_range
typedef iterator_range< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal , BasicBlockVal , FunctionVal , GlobalAliasVal ,
GlobalVariableVal , UndefValueVal , BlockAddressVal , ConstantExprVal ,
ConstantAggregateZeroVal , ConstantDataArrayVal , ConstantDataVectorVal , ConstantIntVal ,
ConstantFPVal , ConstantArrayVal , ConstantStructVal , ConstantVectorVal ,
ConstantPointerNullVal , MetadataAsValueVal , InlineAsmVal , InstructionVal ,
ConstantFirstVal = FunctionVal , ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl< const User > const_user_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Protected Member Functions inherited from llvm::GlobalValue
GlobalValue (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name)
unsigned getGlobalValueSubClassData () const
void setGlobalValueSubClassData (unsigned V)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
void destroyConstantImpl ()
void replaceUsesOfWithOnConstantImpl (Constant *Replacement)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< GlobalAlias >
ilist_node ()
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::GlobalValue
LinkageTypes Linkage: 5
unsigned Visibility: 2
unsigned UnnamedAddr: 1
unsigned DllStorageClass: 2
unsigned ThreadLocal: 3
Module * Parent
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Static Protected Attributes inherited from llvm::GlobalValue
static const unsigned GlobalValueSubClassDataBits = 19
Detailed Description
Definition at line 29 of file GlobalAlias.h.
Member Function Documentation
classof()
bool llvm::GlobalAlias::classof (const Value * V) inline static
Definition at line 111 of file GlobalAlias.h.
References llvm::Value::GlobalAliasVal.
create() [1/5]
GlobalAlias * GlobalAlias::create (const Twine & Name, GlobalValue * Aliasee) static
Definition at line 284 of file Globals.cpp.
References create(), llvm::GlobalValue::getLinkage(), and Name.
create() [2/5]
GlobalAlias * GlobalAlias::create (LinkageTypes Linkage, const Twine & Name, GlobalValue * Aliasee) static
Definition at line 277 of file Globals.cpp.
References create(), llvm::PointerType::getAddressSpace(), llvm::SequentialType::getElementType(), llvm::GlobalValue::getType(), and Name.
create() [3/5]
GlobalAlias * GlobalAlias::create (Type * Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine & Name, Constant * Aliasee, Module * Parent) static
If a parent module is specified, the alias is automatically inserted into the end of the specified module's alias list.
Definition at line 259 of file Globals.cpp.
References Name.
Referenced by llvm::CloneModule(), copyGlobalAliasProto(), create(), create(), create(), create(), INITIALIZE_TM_PASS(), and LLVMAddAlias().
create() [4/5]
GlobalAlias * GlobalAlias::create (Type * Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine & Name, GlobalValue * Aliasee) static
Definition at line 271 of file Globals.cpp.
References create(), llvm::GlobalValue::getParent(), llvm::GlobalValue::Linkage, and Name.
create() [5/5]
GlobalAlias * GlobalAlias::create (Type * Ty, unsigned AddressSpace, LinkageTypes Linkage, const Twine & Name, Module * Parent) static
Definition at line 265 of file Globals.cpp.
References create(), llvm::GlobalValue::Linkage, Name, and llvm::GlobalValue::Parent.
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::GlobalAlias::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Provide fast operand accessors.
eraseFromParent()
void GlobalAlias::eraseFromParent () override virtual
eraseFromParent - This method unlinks 'this' from the containing module and deletes it.
Implements llvm::GlobalValue.
Definition at line 296 of file Globals.cpp.
References llvm::iplist< NodeTy, Traits >::erase(), llvm::Module::getAliasList(), and llvm::GlobalValue::getParent().
getAliasee() [1/2]
Constant * llvm::GlobalAlias::getAliasee () inline
Definition at line 86 of file GlobalAlias.h.
References llvm::User::getOperand().
getAliasee() [2/2]
const Constant * llvm::GlobalAlias::getAliasee () const inline
Definition at line 83 of file GlobalAlias.h.
References getAliasee().
Referenced by getAliasee(), getBaseObject(), getBaseObject(), hasUsesToReplace(), llvm::AssemblyWriter::printAlias(), and llvm::ObjectSizeOffsetVisitor::visitGlobalAlias().
getBaseObject() [1/4]
GlobalObject * llvm::GlobalAlias::getBaseObject () inline
Definition at line 93 of file GlobalAlias.h.
References llvm::dyn_cast(), getAliasee(), and llvm::Value::stripInBoundsOffsets().
getBaseObject() [2/4]
const GlobalObject * llvm::GlobalAlias::getBaseObject () const inline
Definition at line 90 of file GlobalAlias.h.
References getBaseObject().
Referenced by getBaseObject(), and getBaseObject().
getBaseObject() [3/4]
GlobalObject * llvm::GlobalAlias::getBaseObject (const DataLayout & DL, APInt & Offset) inline
Definition at line 100 of file GlobalAlias.h.
References llvm::dyn_cast(), getAliasee(), and llvm::Value::stripAndAccumulateInBoundsConstantOffsets().
getBaseObject() [4/4]
const GlobalObject * llvm::GlobalAlias::getBaseObject (const DataLayout & DL, APInt & Offset) const inline
Definition at line 97 of file GlobalAlias.h.
References getBaseObject().
isValidLinkage()
bool llvm::GlobalAlias::isValidLinkage (LinkageTypes L) inline static
Definition at line 105 of file GlobalAlias.h.
References llvm::GlobalValue::isExternalLinkage(), llvm::GlobalValue::isLinkOnceLinkage(), llvm::GlobalValue::isLocalLinkage(), and llvm::GlobalValue::isWeakLinkage().
operator new()
void * llvm::GlobalAlias::operator new (size_t s) inline
Definition at line 41 of file GlobalAlias.h.
removeFromParent()
void GlobalAlias::removeFromParent () override virtual
removeFromParent - This method unlinks 'this' from the containing module, but does not delete it.
Implements llvm::GlobalValue.
Definition at line 292 of file Globals.cpp.
References llvm::Module::getAliasList(), llvm::GlobalValue::getParent(), and llvm::iplist< NodeTy, Traits >::remove().
setAliasee()
void GlobalAlias::setAliasee (Constant * Aliasee)
These methods retrive and set alias target.
Definition at line 300 of file Globals.cpp.
References llvm::GlobalValue::getType(), llvm::Value::getType(), and llvm::User::setOperand().
Referenced by llvm::CloneModule().
Friends And Related Symbol Documentation
SymbolTableListTraits< GlobalAlias, Module >
friend class SymbolTableListTraits< GlobalAlias, Module > friend
Definition at line 1 of file GlobalAlias.h.
The documentation for this class was generated from the following files:
GlobalAlias.h
Globals.cpp