LLVM: llvm::IntervalPartition Class Reference
LLVM API Documentation
llvm::IntervalPartition Class Reference
#include <IntervalPartition.h>
Public Member Functions
IntervalPartition ()
bool runOnFunction (Function &F) override
IntervalPartition (IntervalPartition &I, bool)
void print (raw_ostream &O, const Module *=nullptr) const override
Interval * getRootInterval ()
bool isDegeneratePartition ()
Interval * getBlockInterval (BasicBlock *BB)
void getAnalysisUsage (AnalysisUsage &AU) const override
const std::vector< Interval * > & getIntervals () const
void releaseMemory () override
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 40 of file IntervalPartition.h.
Constructor & Destructor Documentation
IntervalPartition() [1/2]
llvm::IntervalPartition::IntervalPartition () inline
Definition at line 51 of file IntervalPartition.h.
References llvm::FunctionPass::FunctionPass(), llvm::PassRegistry::getPassRegistry(), ID, and llvm::initializeIntervalPartitionPass().
Referenced by IntervalPartition().
IntervalPartition() [2/2]
IntervalPartition::IntervalPartition (IntervalPartition & I, bool)
Definition at line 93 of file IntervalPartition.cpp.
References llvm::FunctionPass::FunctionPass(), getRootInterval(), I, ID, IntervalPartition(), llvm::intervals_begin(), and llvm::intervals_end().
Member Function Documentation
getAnalysisUsage()
void llvm::IntervalPartition::getAnalysisUsage (AnalysisUsage &) const inline override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 84 of file IntervalPartition.h.
References llvm::AnalysisUsage::setPreservesAll().
getBlockInterval()
Interval * llvm::IntervalPartition::getBlockInterval (BasicBlock * BB) inline
Definition at line 78 of file IntervalPartition.h.
References I.
Referenced by llvm::getSourceGraphNode().
getIntervals()
const std::vector< Interval * > & llvm::IntervalPartition::getIntervals () const inline
Definition at line 89 of file IntervalPartition.h.
getRootInterval()
Interval * llvm::IntervalPartition::getRootInterval () inline
Definition at line 69 of file IntervalPartition.h.
Referenced by llvm::IntervalIterator< BasicBlock, Function >::IntervalIterator(), and IntervalPartition().
isDegeneratePartition()
bool llvm::IntervalPartition::isDegeneratePartition () inline
Definition at line 73 of file IntervalPartition.h.
print()
void IntervalPartition::print (raw_ostream & O, const Module * M = nullptr) const override virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 35 of file IntervalPartition.cpp.
releaseMemory()
void llvm::IntervalPartition::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
References I.
runOnFunction()
bool IntervalPartition::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 68 of file IntervalPartition.cpp.
References F, I, llvm::intervals_begin(), and llvm::intervals_end().
Member Data Documentation
ID
char IntervalPartition::ID = 0 static
Definition at line 49 of file IntervalPartition.h.
Referenced by IntervalPartition(), and IntervalPartition().
The documentation for this class was generated from the following files:
IntervalPartition.h
IntervalPartition.cpp