LLVM: llvm::MCInst Class Reference
LLVM API Documentation
llvm::MCInst Class Reference
#include <MCInst.h>
Public Types
typedef SmallVectorImpl< MCOperand >::iterator iterator
typedef SmallVectorImpl< MCOperand >::const_iterator const_iterator
Public Member Functions
MCInst ()
void setOpcode (unsigned Op)
unsigned getOpcode () const
void setLoc (SMLoc loc)
SMLoc getLoc () const
const MCOperand & getOperand (unsigned i) const
MCOperand & getOperand (unsigned i)
unsigned getNumOperands () const
void addOperand (const MCOperand &Op)
void clear ()
size_t size ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator insert (iterator I, const MCOperand &Op)
void print (raw_ostream &OS, const MCAsmInfo *MAI) const
void dump () const
void dump_pretty (raw_ostream &OS, const MCAsmInfo *MAI=nullptr, const MCInstPrinter *Printer=nullptr, StringRef Separator=" ") const
Dump the MCInst as prettily as possible using the additional MC structures, if given. Operators are separated by the Separator string.
Detailed Description
MCInst - Instances of this class represent a single low-level machine instruction.
Definition at line 150 of file MCInst.h.
Member Typedef Documentation
const_iterator
typedef SmallVectorImpl<MCOperand>::const_iterator llvm::MCInst::const_iterator
Definition at line 175 of file MCInst.h.
iterator
typedef SmallVectorImpl<MCOperand>::iterator llvm::MCInst::iterator
Definition at line 174 of file MCInst.h.
Constructor & Destructor Documentation
MCInst()
llvm::MCInst::MCInst () inline
Definition at line 155 of file MCInst.h.
Referenced by llvm::HexagonMCInst::AppendImplicitOperands(), llvm::HexagonMCInst::GetImplicitBits(), llvm::HexagonMCInst::HexagonMCInst(), llvm::HexagonMCInst::HexagonMCInst(), llvm::HexagonMCInst::SanityCheckImplicitOperands(), and llvm::HexagonMCInst::SetImplicitBits().
Member Function Documentation
addOperand()
void llvm::MCInst::addOperand (const MCOperand & Op) inline
Definition at line 167 of file MCInst.h.
Referenced by llvm::X86Operand::addAbsMemOperands(), llvm::X86Operand::addDstIdxOperands(), llvm::X86Operand::addExpr(), llvm::X86Operand::addGR32orGR64Operands(), llvm::X86Operand::addMemOffsOperands(), llvm::X86Operand::addMemOperands(), addNegOperand(), llvm::X86Operand::addRegOperands(), llvm::X86Operand::addSrcIdxOperands(), llvm::HexagonMCInst::AppendImplicitOperands(), convertToSExti8(), Decode2RImmInstruction(), Decode2RUSInstruction(), Decode3RImmInstruction(), DecodeACC64DSPRegisterClass(), DecodeAddiur2Simm7(), DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeAddrMode5Operand(), DecodeAddrMode6Operand(), DecodeAddrModeImm12Operand(), DecodeAddSubERegInstruction(), DecodeAdrInstruction(), DecodeAFGR64RegisterClass(), DecodeANDI16Imm(), DecodeArmMOVTWInstruction(), DecodeBankedReg(), DecodeBaseAddSubImm(), decodeBDAddr12Operand(), decodeBDAddr20Operand(), decodeBDLAddr12Len8Operand(), decodeBDXAddr12Operand(), decodeBDXAddr20Operand(), DecodeBitfieldMaskOperand(), DecodeBitpOperand(), DecodeBranchImmInstruction(), DecodeBranchTarget(), DecodeBranchTarget21(), DecodeBranchTarget26(), DecodeBranchTarget7MM(), DecodeBranchTargetMM(), DecodeCacheOp(), DecodeCacheOpMM(), DecodeCacheOpR6(), DecodeCCOutOperand(), DecodeCCRRegisterClass(), DecodeCOP2RegisterClass(), DecodeCopMemInstruction(), DecodeCoprocessor(), DecodeCPSInstruction(), decodeCRBitMOperand(), DecodeCtrRegsRegisterClass(), DecodeDDDDRegisterClass(), DecodeDDDRegisterClass(), DecodeDDRegisterClass(), DecodeDFPRegsRegisterClass(), DecodeDPairRegisterClass(), DecodeDPairSpacedRegisterClass(), DecodeDPRRegisterClass(), DecodeExtSize(), DecodeFCCRegisterClass(), DecodeFCCRegsRegisterClass(), DecodeFGR32RegisterClass(), DecodeFGR64RegisterClass(), DecodeFGRCCRegisterClass(), DecodeFixedPointScaleImm32(), DecodeFixedPointScaleImm64(), DecodeFMem(), DecodeFMem2(), DecodeFMem3(), DecodeFMemCop2R6(), DecodeFMOVLaneInstruction(), DecodeFPR128RegisterClass(), DecodeFPR16RegisterClass(), DecodeFPR32RegisterClass(), DecodeFPR64RegisterClass(), DecodeFPR8RegisterClass(), DecodeFPRegsRegisterClass(), DecodeGPR32RegisterClass(), DecodeGPR32RegisterClass(), DecodeGPR32spRegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64RegisterClass(), DecodeGPR64spRegisterClass(), DecodeGPRMM16RegisterClass(), DecodeGPRMM16ZeroRegisterClass(), DecodeGPRPairRegisterClass(), DecodeGPRRegisterClass(), DecodeGPRwithAPSRRegisterClass(), DecodeGRRegsRegisterClass(), DecodeHI32DSPRegisterClass(), DecodeHWRegsRegisterClass(), DecodeI64RegsRegisterClass(), DecodeInsSize(), DecodeInstSyncBarrierOption(), DecodeIntRegsRegisterClass(), DecodeIntRegsRegisterClass(), DecodeIT(), DecodeJumpTarget(), DecodeJumpTargetMM(), DecodeL2RUSInstruction(), DecodeLiSimm7(), DecodeLO32DSPRegisterClass(), DecodeLogicalImmInstruction(), DecodeLSAImm(), DecodeMem(), DecodeMemBarrierOption(), DecodeMemExtend(), DecodeMemMMImm12(), DecodeMemMMImm16(), DecodeMemMMImm4(), DecodeMemMMSPImm5Lsl2(), DecodeMemMultipleWritebackInstruction(), decodeMemRIOperands(), decodeMemRIXOperands(), DecodeModImmInstruction(), DecodeModImmTiedInstruction(), DecodeModRegsRegisterClass(), DecodeMoveImmInstruction(), DecodeMRRC2(), DecodeMRSSystemRegister(), DecodeMSA128BRegisterClass(), DecodeMSA128DRegisterClass(), DecodeMSA128HRegisterClass(), DecodeMSA128Mem(), DecodeMSA128WRegisterClass(), DecodeMSACtrlRegisterClass(), DecodeMSRMask(), DecodeMSRSystemRegister(), DecodeNegImmOperand(), DecodeNEONModImmInstruction(), DecodePairLdStInstruction(), decodePCDBLOperand(), DecodePCRelLabel19(), DecodePostIdxReg(), DecodePredicateOperand(), DecodePredRegsRegisterClass(), DecodeQFPRegsRegisterClass(), DecodeQPRRegisterClass(), DecodeQQQQRegisterClass(), DecodeQQQRegisterClass(), DecodeQQRegisterClass(), DecodeRegisterClass(), decodeRegisterClass(), decodeRegisterClass(), DecodeRegListOperand(), DecodeRegListOperand16(), DecodeRFEInstruction(), DecodeRRegsRegisterClass(), DecodeRUSInstruction(), DecodeShiftRight16Imm(), DecodeShiftRight32Imm(), DecodeShiftRight64Imm(), DecodeShiftRight8Imm(), DecodeSignedLdStInstruction(), DecodeSimm16(), DecodeSimm18Lsl3(), DecodeSimm19Lsl2(), DecodeSimm4(), DecodeSimm9SP(), decodeSImmOperand(), decodeSImmOperand(), DecodeSORegImmOperand(), DecodeSORegMemOperand(), DecodeSORegRegOperand(), DecodeSpecial3LlSc(), DecodeSPRRegisterClass(), DecodeSyncI(), DecodeSystemPStateInstruction(), DecodeT2AddrModeImm0_1020s4(), DecodeT2AddrModeImm12(), DecodeT2AddrModeSOReg(), DecodeT2Adr(), DecodeT2BInstruction(), DecodeT2BROperand(), DecodeT2CPSInstruction(), DecodeT2Imm8(), DecodeT2Imm8S4(), DecodeT2LoadLabel(), DecodeT2MOVTWInstruction(), DecodeT2ShifterImmOperand(), DecodeT2SOImm(), DecodetcGPRRegisterClass(), DecodeTestAndBranch(), DecodeThreeAddrSRegInstruction(), DecodeThumbAddrModeIS(), DecodeThumbAddrModePC(), DecodeThumbAddrModeSP(), DecodeThumbAddSpecialReg(), DecodeThumbAddSPImm(), DecodeThumbAddSPReg(), DecodeThumbBCCTargetOperand(), DecodeThumbBLTargetOperand(), DecodeThumbBLXOffset(), DecodeThumbBROperand(), DecodeThumbCmpBROperand(), DecodeThumbCPS(), DecodeUImm5lsl2(), DecodeUImm6Lsl2(), decodeUImmOperand(), decodeUImmOperand(), DecodeUnconditionalBranch(), DecodeUnsignedLdStInstruction(), DecodeVCVTD(), DecodeVCVTQ(), DecodeVecShiftLImm(), DecodeVecShiftRImm(), DecodeVectorRegisterClass(), DecodeVLD1DupInstruction(), DecodeVLD1LN(), DecodeVLD2DupInstruction(), DecodeVLD2LN(), DecodeVLD3DupInstruction(), DecodeVLD3LN(), DecodeVLD4DupInstruction(), DecodeVLD4LN(), DecodeVLDInstruction(), DecodeVSHLMaxInstruction(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), DecodeVSTInstruction(), EmitBinary(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::ARMAsmPrinter::EmitInstruction(), EmitSETHI(), llvm::AArch64InstrInfo::getNoopForMachoTarget(), llvm::ARMInstrInfo::getNoopForMachoTarget(), llvm::Thumb1InstrInfo::getNoopForMachoTarget(), llvm::Thumb2InstrInfo::getNoopForMachoTarget(), llvm::HexagonLowerToMC(), llvm::AArch64MCInstLower::Lower(), llvm::MipsMCInstLower::Lower(), llvm::MSP430MCInstLower::Lower(), llvm::XCoreMCInstLower::Lower(), llvm::AMDGPUMCInstLower::lower(), llvm::SystemZMCInstLower::lower(), llvm::LowerARMMachineInstrToMCInst(), llvm::LowerPPCMachineInstrToMCInst(), llvm::LowerSparcMachineInstrToMCInst(), LowerSTATEPOINT(), llvm::ARMInstPrinter::printInst(), SimplifyShortImmForm(), SimplifyShortMoveForm(), translateDstIndex(), translateFPRegister(), translateImmediate(), translateMaskRegister(), translateRegister(), translateRMMemory(), and translateSrcIndex().
begin() [1/2]
iterator llvm::MCInst::begin () inline
Definition at line 176 of file MCInst.h.
Referenced by decodeMemRIOperands(), and decodeMemRIXOperands().
begin() [2/2]
const_iterator llvm::MCInst::begin () const inline
Definition at line 177 of file MCInst.h.
clear()
void llvm::MCInst::clear () inline
Definition at line 171 of file MCInst.h.
Referenced by DecodeL5RInstructionFail(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), and llvm::MipsTargetELFStreamer::emitDirectiveCpsetup().
dump()
void MCInst::dump () const
Definition at line 68 of file MCInst.cpp.
References llvm::dbgs(), and print().
dump_pretty()
void MCInst::dump_pretty (raw_ostream & OS, const MCAsmInfo * MAI = nullptr, const MCInstPrinter * Printer = nullptr, StringRef Separator = " ") const
Dump the MCInst as prettily as possible using the additional MC structures, if given. Operators are separated by the Separator string.
Definition at line 51 of file MCInst.cpp.
References getNumOperands(), getOpcode(), getOperand(), and llvm::MCOperand::print().
end() [1/2]
iterator llvm::MCInst::end () inline
Definition at line 178 of file MCInst.h.
Referenced by DecodeRegListOperand().
end() [2/2]
const_iterator llvm::MCInst::end () const inline
Definition at line 179 of file MCInst.h.
getLoc()
SMLoc llvm::MCInst::getLoc () const inline
Definition at line 161 of file MCInst.h.
getNumOperands()
unsigned llvm::MCInst::getNumOperands () const inline
Definition at line 165 of file MCInst.h.
Referenced by checkLowRegisterList(), dump_pretty(), llvm::MCStreamer::EmitInstruction(), llvm::MipsELFStreamer::EmitInstruction(), llvm::MCInstrAnalysis::evaluateBranch(), llvm::HexagonMCInst::GetImplicitBits(), getItineraryLatency(), listContainsReg(), LowerDextDins(), LowerLargeShift(), print(), llvm::HexagonMCInst::SanityCheckImplicitOperands(), llvm::HexagonMCInst::SetImplicitBits(), SimplifyShortImmForm(), and SimplifyShortMoveForm().
getOpcode()
unsigned llvm::MCInst::getOpcode () const inline
Definition at line 158 of file MCInst.h.
Referenced by DecodeAddrMode2IdxInstruction(), DecodeAddrMode3Instruction(), DecodeAddSubERegInstruction(), DecodeArmMOVTWInstruction(), DecodeCopMemInstruction(), DecodeExclusiveLdStInstruction(), DecodeLogicalImmInstruction(), DecodeMem(), DecodeMemMMImm12(), DecodeMemMMImm4(), DecodeMemMultipleWritebackInstruction(), decodeMemRIOperands(), decodeMemRIXOperands(), DecodeModImmInstruction(), DecodeMoveImmInstruction(), DecodeMSA128Mem(), DecodeMSRMask(), DecodeNEONModImmInstruction(), DecodePairLdStInstruction(), DecodePCRelLabel19(), DecodePredicateOperand(), DecodeRegListOperand(), DecodeSignedLdStInstruction(), DecodeSpecial3LlSc(), DecodeT2AddrModeImm12(), DecodeT2AddrModeImm8(), DecodeT2AddrModeSOReg(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodeT2LoadT(), DecodeT2MOVTWInstruction(), DecodeTBLInstruction(), DecodeThreeAddrSRegInstruction(), DecodeThumbAddSpecialReg(), DecodeThumbAddSPReg(), DecodeUnsignedLdStInstruction(), DecodeVLD1DupInstruction(), DecodeVLD2DupInstruction(), DecodeVLDInstruction(), DecodeVSTInstruction(), dump_pretty(), llvm::AsmPrinter::EmitFunctionBody(), llvm::MCInstrAnalysis::evaluateBranch(), llvm::HexagonMCInst::getDesc(), getItineraryLatency(), getLatency(), instIsBreakpoint(), llvm::MCInstrAnalysis::isBranch(), llvm::MCInstrAnalysis::isCall(), llvm::MCInstrAnalysis::isConditionalBranch(), llvm::MCInstrAnalysis::isIndirectBranch(), llvm::MCInstrAnalysis::isReturn(), llvm::MCInstrAnalysis::isTerminator(), llvm::MCInstrAnalysis::isUnconditionalBranch(), LowerDextDins(), LowerLargeShift(), print(), SimplifyMOVSX(), translateImmediate(), translateInstruction(), and translateRMMemory().
getOperand() [1/2]
MCOperand & llvm::MCInst::getOperand (unsigned i) inline
Definition at line 164 of file MCInst.h.
getOperand() [2/2]
const MCOperand & llvm::MCInst::getOperand (unsigned i) const inline
Definition at line 163 of file MCInst.h.
Referenced by checkLowRegisterList(), convert16i16to16ri8(), convert32i32to32ri8(), convert64i32to64ri8(), convertToSExti8(), DecodeInsSize(), DecodeMoveImmInstruction(), DecodeRegListOperand(), dump_pretty(), llvm::MCStreamer::EmitInstruction(), llvm::MipsELFStreamer::EmitInstruction(), llvm::MCInstrAnalysis::evaluateBranch(), llvm::HexagonMCInst::GetImplicitBits(), llvm::HexagonMCInst::getNewValue(), llvm::HexagonMCInst::isConstExtended(), listContainsReg(), LowerDextDins(), LowerLargeShift(), print(), llvm::HexagonMCInst::SanityCheckImplicitOperands(), llvm::HexagonMCInst::SetImplicitBits(), SimplifyMOVSX(), SimplifyShortImmForm(), and SimplifyShortMoveForm().
insert()
iterator llvm::MCInst::insert (iterator I, const MCOperand & Op) inline
Definition at line 180 of file MCInst.h.
References I.
Referenced by decodeMemRIOperands(), and decodeMemRIXOperands().
print()
void MCInst::print (raw_ostream & OS, const MCAsmInfo * MAI) const
Definition at line 42 of file MCInst.cpp.
References getNumOperands(), getOpcode(), getOperand(), and llvm::MCOperand::print().
Referenced by dump().
setLoc()
void llvm::MCInst::setLoc (SMLoc loc) inline
Definition at line 160 of file MCInst.h.
setOpcode()
void llvm::MCInst::setOpcode (unsigned Op) inline
Definition at line 157 of file MCInst.h.
Referenced by convertToSExti8(), Decode2OpInstructionFail(), DecodeBranchImmInstruction(), DecodeCPSInstruction(), DecodeL2OpInstructionFail(), DecodeL5RInstructionFail(), DecodeMemMultipleWritebackInstruction(), DecodeT2CPSInstruction(), DecodeT2LdStPre(), DecodeT2LoadImm12(), DecodeT2LoadImm8(), DecodeT2LoadLabel(), DecodeT2LoadShift(), DecodeT2LoadT(), DecodeThumb2BCCInstruction(), DecodeVCVTD(), DecodeVCVTQ(), EmitBinary(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::ARMAsmPrinter::EmitInstruction(), EmitSETHI(), llvm::AArch64InstrInfo::getNoopForMachoTarget(), llvm::ARMInstrInfo::getNoopForMachoTarget(), llvm::PPCInstrInfo::getNoopForMachoTarget(), llvm::Thumb1InstrInfo::getNoopForMachoTarget(), llvm::Thumb2InstrInfo::getNoopForMachoTarget(), llvm::X86InstrInfo::getNoopForMachoTarget(), llvm::HexagonLowerToMC(), llvm::AArch64MCInstLower::Lower(), llvm::MipsMCInstLower::Lower(), llvm::MSP430MCInstLower::Lower(), llvm::XCoreMCInstLower::Lower(), llvm::AMDGPUMCInstLower::lower(), llvm::SystemZMCInstLower::lower(), llvm::LowerARMMachineInstrToMCInst(), LowerDextDins(), LowerLargeShift(), llvm::LowerPPCMachineInstrToMCInst(), llvm::LowerSparcMachineInstrToMCInst(), LowerSTATEPOINT(), llvm::ARMInstPrinter::printInst(), llvm::HexagonInstPrinter::printInst(), SimplifyMOVSX(), SimplifyShortImmForm(), SimplifyShortMoveForm(), translateImmediate(), and translateInstruction().
size()
size_t llvm::MCInst::size () inline
Definition at line 172 of file MCInst.h.
The documentation for this class was generated from the following files:
MCInst.h
MCInst.cpp