LLVM: llvm::InlineCostAnalysis Class Reference
LLVM API Documentation
llvm::InlineCostAnalysis Class Reference
Cost analyzer used by inliner.
#include <InlineCost.h>
Public Member Functions
InlineCostAnalysis ()
~InlineCostAnalysis ()
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnSCC (CallGraphSCC &SCC) override
InlineCost getInlineCost (CallSite CS, int Threshold)
Get an InlineCost object representing the cost of inlining this callsite.
InlineCost getInlineCost (CallSite CS, Function *Callee, int Threshold)
Get an InlineCost with the callee explicitly specified. This allows you to calculate the cost of inlining a function via a pointer. This behaves exactly as the version with no explicit callee parameter in all other respects.
bool isInlineViable (Function &Callee)
Minimal filter to detect invalid constructs for inlining.
Public Member Functions inherited from llvm::CallGraphSCCPass
CallGraphSCCPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
virtual bool doInitialization (CallGraph &CG)
virtual bool doFinalization (CallGraph &CG)
void assignPassManager (PMStack &PMS, PassManagerType PMT) override
Assign pass manager to manager this pass.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Cost analyzer used by inliner.
Definition at line 102 of file InlineCost.h.
Constructor & Destructor Documentation
InlineCostAnalysis()
InlineCostAnalysis::InlineCostAnalysis ()
Definition at line 1242 of file InlineCost.cpp.
References llvm::CallGraphSCCPass::CallGraphSCCPass(), ID, and InlineCostAnalysis().
Referenced by InlineCostAnalysis().
~InlineCostAnalysis()
InlineCostAnalysis::~InlineCostAnalysis ()
Definition at line 1244 of file InlineCost.cpp.
Member Function Documentation
getAnalysisUsage()
void InlineCostAnalysis::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - For this class, we declare that we require and preserve the call graph. If the derived class implements this method, it should always explicitly call the implementation here.
Reimplemented from llvm::CallGraphSCCPass.
Definition at line 1246 of file InlineCost.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::CallGraphSCCPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getInlineCost() [1/2]
InlineCost InlineCostAnalysis::getInlineCost (CallSite CS, Function * Callee, int Threshold)
Get an InlineCost with the callee explicitly specified. This allows you to calculate the cost of inlining a function via a pointer. This behaves exactly as the version with no explicit callee parameter in all other respects.
Definition at line 1279 of file InlineCost.cpp.
References llvm::Attribute::AlwaysInline, llvm::dbgs(), DEBUG, functionsHaveCompatibleAttributes(), llvm::InlineCost::get(), llvm::InlineCost::getAlways(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCaller(), llvm::GlobalValue::getDataLayout(), llvm::Value::getName(), llvm::InlineCost::getNever(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::hasFnAttr(), llvm::Function::hasFnAttribute(), isInlineViable(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isNoInline(), llvm::GlobalValue::mayBeOverridden(), llvm::Attribute::NoInline, llvm::Attribute::OptimizeNone, and Threshold.
getInlineCost() [2/2]
InlineCost InlineCostAnalysis::getInlineCost (CallSite CS, int Threshold)
Get an InlineCost object representing the cost of inlining this callsite.
Note that threshold is passed into this function. Only costs below the threshold are computed with any accuracy. The threshold can be used to bound the computation necessary to determine whether the cost is sufficiently low to warrant inlining.
Also note that calling this function dynamically computes the cost of inlining the callsite. It is an expensive, heavyweight call.
Definition at line 1259 of file InlineCost.cpp.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction(), getInlineCost(), and Threshold.
Referenced by getInlineCost().
isInlineViable()
bool InlineCostAnalysis::isInlineViable (Function & Callee)
Minimal filter to detect invalid constructs for inlining.
Definition at line 1327 of file InlineCost.cpp.
References llvm::cast(), F, llvm::AttributeSet::FunctionIndex, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::isa(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCall(), and llvm::Attribute::ReturnsTwice.
Referenced by getInlineCost().
runOnSCC()
bool InlineCostAnalysis::runOnSCC (CallGraphSCC & SCC) override virtual
runOnSCC - This method should be implemented by the subclass to perform whatever action is necessary for the specified SCC. Note that non-recursive (or only self-recursive) functions will have an SCC size of 1, where recursive portions of the call graph will have SCC size > 1.
SCC passes that add or delete functions to the SCC are required to update the SCC list, otherwise stale pointers may be dereferenced.
Implements llvm::CallGraphSCCPass.
Definition at line 1253 of file InlineCost.cpp.
References llvm::Pass::getAnalysis().
Member Data Documentation
ID
Inline Cost true char InlineCostAnalysis::ID = 0 inline static
Definition at line 107 of file InlineCost.h.
Referenced by InlineCostAnalysis().
The documentation for this class was generated from the following files:
InlineCost.h
InlineCost.cpp