LLVM: llvm::MipsInstrInfo Class Reference
LLVM API Documentation
llvm::MipsInstrInfo Class Reference abstract
#include <MipsInstrInfo.h>
Public Types
enum BranchType {
BT_None , BT_NoBranch , BT_Uncond , BT_Cond ,
BT_CondUncond , BT_Indirect
}
Public Member Functions
MipsInstrInfo (const MipsSubtarget &STI, unsigned UncondBrOpc)
bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const override
Branch Analysis.
unsigned RemoveBranch (MachineBasicBlock &MBB) const override
unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const override
bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
BranchType AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify, SmallVectorImpl< MachineInstr * > &BranchInstrs) const
void insertNoop (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
Insert nop instruction when hazard condition is found.
virtual const MipsRegisterInfo & getRegisterInfo () const =0
virtual unsigned getOppositeBranchOpc (unsigned Opc) const =0
unsigned GetInstSizeInBytes (const MachineInstr *MI) const
Return the number of bytes of code the specified instruction may be.
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
virtual void storeRegToStack (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, int64_t Offset) const =0
virtual void loadRegFromStack (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, int64_t Offset) const =0
MachineInstrBuilder genInstrWithNewOpc (unsigned NewOpc, MachineBasicBlock::iterator I) const
Static Public Member Functions
static const MipsInstrInfo * create (MipsSubtarget &STI)
Protected Member Functions
bool isZeroImm (const MachineOperand &op) const
MachineMemOperand * GetMemOperand (MachineBasicBlock &MBB, int FI, unsigned Flag) const
Protected Attributes
const MipsSubtarget & Subtarget
unsigned UncondBrOpc
Detailed Description
Definition at line 33 of file MipsInstrInfo.h.
Member Enumeration Documentation
BranchType
enum llvm::MipsInstrInfo::BranchType
Enumerator
BT_None
BT_NoBranch
BT_Uncond
BT_Cond
BT_CondUncond
BT_Indirect
Definition at line 40 of file MipsInstrInfo.h.
Constructor & Destructor Documentation
MipsInstrInfo()
MipsInstrInfo::MipsInstrInfo (const MipsSubtarget & STI, unsigned UncondBrOpc) explicit
Definition at line 33 of file MipsInstrInfo.cpp.
References Subtarget, and UncondBrOpc.
Referenced by create(), llvm::Mips16InstrInfo::Mips16InstrInfo(), and llvm::MipsSEInstrInfo::MipsSEInstrInfo().
Member Function Documentation
AnalyzeBranch() [1/2]
bool MipsInstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const override
Branch Analysis.
Definition at line 86 of file MipsInstrInfo.cpp.
References AnalyzeBranch(), BT_Indirect, and BT_None.
Referenced by AnalyzeBranch().
AnalyzeBranch() [2/2]
MipsInstrInfo::BranchType MipsInstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify, SmallVectorImpl< MachineInstr * > & BranchInstrs) const
Definition at line 178 of file MipsInstrInfo.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), BT_Cond, BT_CondUncond, BT_Indirect, BT_NoBranch, BT_None, BT_Uncond, llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), I, llvm::SmallVectorImpl< T >::insert(), llvm::MachineInstr::isIndirectBranch(), llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::MachineBasicBlock::rbegin(), llvm::MachineBasicBlock::rend(), and UncondBrOpc.
create()
const MipsInstrInfo * MipsInstrInfo::create (MipsSubtarget & STI) static
Definition at line 37 of file MipsInstrInfo.cpp.
References llvm::createMips16InstrInfo(), llvm::createMipsSEInstrInfo(), llvm::MipsSubtarget::inMips16Mode(), and MipsInstrInfo().
genInstrWithNewOpc()
MachineInstrBuilder MipsInstrInfo::genInstrWithNewOpc (unsigned NewOpc, MachineBasicBlock::iterator I) const
Create an instruction which has the same operands and memory operands as MI but has a new opcode.
Definition at line 279 of file MipsInstrInfo.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::BuildMI(), I, and llvm::MachineInstrBuilder::setMemRefs().
GetInstSizeInBytes()
unsigned MipsInstrInfo::GetInstSizeInBytes (const MachineInstr * MI) const
Return the number of bytes of code the specified instruction may be.
Definition at line 262 of file MipsInstrInfo.cpp.
References llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getTarget(), and llvm::TargetOpcode::INLINEASM.
GetMemOperand()
MachineMemOperand * MipsInstrInfo::GetMemOperand (MachineBasicBlock & MBB, int FI, unsigned Flag) const protected
Definition at line 57 of file MipsInstrInfo.cpp.
References Align, llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), and llvm::MachineBasicBlock::getParent().
Referenced by llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::Mips16InstrInfo::storeRegToStack(), and llvm::MipsSEInstrInfo::storeRegToStack().
getOppositeBranchOpc()
virtual unsigned llvm::MipsInstrInfo::getOppositeBranchOpc (unsigned Opc) const pure virtual
Implemented in llvm::Mips16InstrInfo, and llvm::MipsSEInstrInfo.
Referenced by ReverseBranchCondition().
getRegisterInfo()
virtual const MipsRegisterInfo & llvm::MipsInstrInfo::getRegisterInfo () const pure virtual
getRegisterInfo - TargetInstrInfo is a superset of MRegister info. As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Implemented in llvm::Mips16InstrInfo, and llvm::MipsSEInstrInfo.
InsertBranch()
unsigned MipsInstrInfo::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, const SmallVectorImpl< MachineOperand > & Cond, DebugLoc DL) const override
Definition at line 116 of file MipsInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::BuildMI(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and UncondBrOpc.
insertNoop()
void MipsInstrInfo::insertNoop (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override
Insert nop instruction when hazard condition is found.
insertNoop - If data hazard condition is found insert the target nop instruction.
Definition at line 50 of file MipsInstrInfo.cpp.
References llvm::BuildMI().
isZeroImm()
bool MipsInstrInfo::isZeroImm (const MachineOperand & op) const protected
Definition at line 44 of file MipsInstrInfo.cpp.
References llvm::MachineOperand::getImm(), and llvm::MachineOperand::isImm().
Referenced by llvm::MipsSEInstrInfo::isLoadFromStackSlot(), and llvm::MipsSEInstrInfo::isStoreToStackSlot().
loadRegFromStack()
virtual void llvm::MipsInstrInfo::loadRegFromStack (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, int64_t Offset) const pure virtual
Implemented in llvm::Mips16InstrInfo, and llvm::MipsSEInstrInfo.
References I.
Referenced by loadRegFromStackSlot().
loadRegFromStackSlot()
void llvm::MipsInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const inline override
Definition at line 98 of file MipsInstrInfo.h.
References loadRegFromStack().
RemoveBranch()
unsigned MipsInstrInfo::RemoveBranch (MachineBasicBlock & MBB) const override
Definition at line 146 of file MipsInstrInfo.cpp.
References llvm::MachineBasicBlock::erase(), I, llvm::MachineBasicBlock::rbegin(), and llvm::MachineBasicBlock::rend().
ReverseBranchCondition()
bool MipsInstrInfo::ReverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
ReverseBranchCondition - Return the inverse opcode of the specified Branch instruction.
Definition at line 170 of file MipsInstrInfo.cpp.
References getOppositeBranchOpc(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
storeRegToStack()
virtual void llvm::MipsInstrInfo::storeRegToStack (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, int64_t Offset) const pure virtual
Implemented in llvm::Mips16InstrInfo, and llvm::MipsSEInstrInfo.
Referenced by storeRegToStackSlot().
storeRegToStackSlot()
void llvm::MipsInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const inline override
Definition at line 90 of file MipsInstrInfo.h.
References storeRegToStack().
Member Data Documentation
Subtarget
const MipsSubtarget& llvm::MipsInstrInfo::Subtarget protected
Definition at line 36 of file MipsInstrInfo.h.
Referenced by llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::expandPostRAPseudo(), llvm::MipsSEInstrInfo::loadImmediate(), and MipsInstrInfo().
UncondBrOpc
unsigned llvm::MipsInstrInfo::UncondBrOpc protected
Definition at line 37 of file MipsInstrInfo.h.
Referenced by AnalyzeBranch(), InsertBranch(), and MipsInstrInfo().
The documentation for this class was generated from the following files:
MipsInstrInfo.h
MipsInstrInfo.cpp