LLVM: llvm::DependenceAnalysis Class Reference
LLVM API Documentation
llvm::DependenceAnalysis Class Reference
#include <DependenceAnalysis.h>
Public Member Functions
std::unique_ptr< Dependence > depends (Instruction *Src, Instruction *Dst, bool PossiblyLoopIndependent)
const SCEV * getSplitIteration (const Dependence &Dep, unsigned Level)
DependenceAnalysis ()
bool runOnFunction (Function &F) override
void releaseMemory () override
void getAnalysisUsage (AnalysisUsage &) const override
void print (raw_ostream &, const Module *=nullptr) const override
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
DependenceAnalysis - This class is the main dependence-analysis driver.
Definition at line 280 of file DependenceAnalysis.h.
Constructor & Destructor Documentation
DependenceAnalysis()
llvm::DependenceAnalysis::DependenceAnalysis () inline
Definition at line 924 of file DependenceAnalysis.h.
References llvm::FunctionPass::FunctionPass(), llvm::PassRegistry::getPassRegistry(), ID, and llvm::initializeDependenceAnalysisPass().
Member Function Documentation
depends()
std::unique_ptr< Dependence > DependenceAnalysis::depends (Instruction * Src, Instruction * Dst, bool PossiblyLoopIndependent)
depends - Tests for a dependence between the Src and Dst instructions. Returns NULL if no dependence; otherwise, returns a Dependence (or a FullDependence) with as much information as can be gleaned. The flag PossiblyLoopIndependent should be set by the caller if it appears that control flow can reach from Src to Dst without traversing a loop back edge.
Definition at line 3298 of file DependenceAnalysis.cpp.
References llvm::SmallBitVector::any(), Changed, llvm::SmallBitVector::count(), llvm::dbgs(), DEBUG, Delinearize, llvm::Dependence::DVEntry::Direction, dumpSmallBitVector(), llvm::dyn_cast(), llvm::Dependence::DVEntry::EQ, llvm::SmallBitVector::find_first(), llvm::SmallBitVector::find_next(), llvm::FullDependence::getDirection(), llvm::Instruction::getParent(), getPointerOperand(), llvm::GEPOperator::getPointerOperand(), llvm::GEPOperator::getPointerOperandType(), llvm::GEPOperator::idx_begin(), llvm::GEPOperator::idx_end(), isLoadOrStore(), llvm_unreachable, Loops, llvm::make_unique(), llvm::AliasAnalysis::MayAlias, llvm::Instruction::mayReadFromMemory(), llvm::Instruction::mayWriteToMemory(), llvm::AliasAnalysis::MustAlias, llvm::AliasAnalysis::NoAlias, llvm::Dependence::DVEntry::NONE, P, llvm::AliasAnalysis::PartialAlias, llvm::SmallBitVector::reset(), llvm::SmallVectorImpl< T >::resize(), llvm::Dependence::DVEntry::Scalar, llvm::SmallBitVector::set(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and underlyingObjectsAlias().
Referenced by dumpExampleDependence().
getAnalysisUsage()
void DependenceAnalysis::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 144 of file DependenceAnalysis.cpp.
References llvm::AnalysisUsage::addRequiredTransitive(), and llvm::AnalysisUsage::setPreservesAll().
getSplitIteration()
const SCEV * DependenceAnalysis::getSplitIteration (const Dependence & Dep, unsigned Level)
getSplitIteration - Give a dependence that's splittable at some particular level, return the iteration that should be used to split the loop.
Generally, the dependence analyzer will be used to build a dependence graph for a function (basically a map from instructions to dependences). Looking for cycles in the graph shows us loops that cannot be trivially vectorized/parallelized.
We can try to improve the situation by examining all the dependences that make up the cycle, looking for ones we can break. Sometimes, peeling the first or last iteration of a loop will break dependences, and there are flags for those possibilities. Sometimes, splitting a loop at some other iteration will do the trick, and we've got a flag for that case. Rather than waste the space to record the exact iteration (since we rarely know), we provide a method that calculates the iteration. It's a drag that it must work from scratch, but wonderful in that it's possible.
Here's an example:
for (i = 0; i < 10; i++) A[i] = ... ... = A[11 - i]
There's a loop-carried flow dependence from the store to the load, found by the weak-crossing SIV test. The dependence will have a flag, indicating that the dependence can be broken by splitting the loop. Calling getSplitIteration will return 5. Splitting the loop breaks the dependence, like so:
for (i = 0; i <= 5; i++) A[i] = ... ... = A[11 - i] for (i = 6; i < 10; i++) A[i] = ... ... = A[11 - i]
breaks the dependence and allows us to vectorize/parallelize both loops.
Definition at line 3750 of file DependenceAnalysis.cpp.
References llvm::SmallBitVector::any(), Changed, llvm::SmallBitVector::count(), llvm::dbgs(), DEBUG, Delinearize, llvm::dyn_cast(), llvm::SmallBitVector::find_first(), llvm::SmallBitVector::find_next(), llvm::Dependence::getDst(), llvm::Instruction::getParent(), getPointerOperand(), llvm::GEPOperator::getPointerOperand(), llvm::GEPOperator::getPointerOperandType(), llvm::Dependence::getSrc(), llvm::GEPOperator::idx_begin(), llvm::GEPOperator::idx_end(), isLoadOrStore(), llvm::Dependence::isSplitable(), llvm_unreachable, Loops, llvm::Instruction::mayReadFromMemory(), llvm::Instruction::mayWriteToMemory(), llvm::AliasAnalysis::MustAlias, P, llvm::SmallBitVector::reset(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallBitVector::set(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and underlyingObjectsAlias().
Referenced by dumpExampleDependence().
print()
void DependenceAnalysis::print (raw_ostream & O, const Module * M = nullptr) const override virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 185 of file DependenceAnalysis.cpp.
References dumpExampleDependence().
releaseMemory()
void DependenceAnalysis::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 140 of file DependenceAnalysis.cpp.
runOnFunction()
bool DependenceAnalysis::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 131 of file DependenceAnalysis.cpp.
References llvm::Pass::getAnalysis().
Member Data Documentation
ID
Dependence true char DependenceAnalysis::ID = 0 static
Definition at line 923 of file DependenceAnalysis.h.
Referenced by DependenceAnalysis().
The documentation for this class was generated from the following files:
DependenceAnalysis.h
DependenceAnalysis.cpp