LLVM: llvm::DIEString Class Reference
LLVM API Documentation
llvm::DIEString Class Reference
#include <DIE.h>
Public Member Functions
DIEString (const DIEValue *Acc, StringRef S)
StringRef getString () const
getString - Grab the string out of the object.
void EmitValue (AsmPrinter *AP, dwarf::Form Form) const override
unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const override
void print (raw_ostream &O) const override
Public Member Functions inherited from llvm::DIEValue
Type getType () const
void dump () const
Static Public Member Functions
static bool classof (const DIEValue *D)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum Type {
isInteger , isString , isExpr , isLabel ,
isDelta , isEntry , isTypeSignature , isBlock ,
isLoc , isLocList
}
Protected Member Functions inherited from llvm::DIEValue
DIEValue (Type T)
virtual ~DIEValue ()
Protected Attributes inherited from llvm::DIEValue
Type Ty
Detailed Description
DIEString - A container for string values.
Definition at line 382 of file DIE.h.
Constructor & Destructor Documentation
DIEString()
llvm::DIEString::DIEString (const DIEValue * Acc, StringRef S) inline
Definition at line 387 of file DIE.h.
References llvm::DIEValue::DIEValue(), and llvm::DIEValue::isString.
Member Function Documentation
classof()
bool llvm::DIEString::classof (const DIEValue * D) inline static
Definition at line 402 of file DIE.h.
References llvm::DIEValue::DIEValue(), llvm::DIEValue::getType(), and llvm::DIEValue::isString.
EmitValue()
void DIEString::EmitValue (AsmPrinter * AP, dwarf::Form Form) const override virtual
EmitValue - Emit delta value.
EmitValue - Emit string value.
Implements llvm::DIEValue.
Definition at line 354 of file DIE.cpp.
getString()
StringRef llvm::DIEString::getString () const inline
getString - Grab the string out of the object.
Definition at line 391 of file DIE.h.
Referenced by getDIEStringAttr().
print()
void DIEString::print (raw_ostream & O) const override virtual
Implements llvm::DIEValue.
Definition at line 365 of file DIE.cpp.
SizeOf()
unsigned DIEString::SizeOf (AsmPrinter * AP, dwarf::Form Form) const override virtual
SizeOf - Determine size of delta value in bytes.
Implements llvm::DIEValue.
Definition at line 360 of file DIE.cpp.
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp