LLVM: llvm::coverage::RawCoverageFilenamesReader Class Reference
LLVM API Documentation
llvm::coverage::RawCoverageFilenamesReader Class Reference
Reader for the raw coverage filenames.
#include <CoverageMappingReader.h>
Public Member Functions
RawCoverageFilenamesReader (StringRef Data, std::vector< StringRef > &Filenames)
std::error_code read ()
Additional Inherited Members
Protected Member Functions inherited from llvm::coverage::RawCoverageReader
std::error_code error (std::error_code EC)
Return the error code.
std::error_code success ()
Clear the current error code and return a successful one.
RawCoverageReader (StringRef Data)
std::error_code readULEB128 (uint64_t &Result)
std::error_code readIntMax (uint64_t &Result, uint64_t MaxPlus1)
std::error_code readSize (uint64_t &Result)
std::error_code readString (StringRef &Result)
Protected Attributes inherited from llvm::coverage::RawCoverageReader
StringRef Data
Detailed Description
Reader for the raw coverage filenames.
Definition at line 90 of file CoverageMappingReader.h.
Constructor & Destructor Documentation
RawCoverageFilenamesReader()
llvm::coverage::RawCoverageFilenamesReader::RawCoverageFilenamesReader (StringRef Data, std::vector< StringRef > & Filenames) inline
Definition at line 99 of file CoverageMappingReader.h.
References llvm::coverage::RawCoverageReader::Data, and llvm::coverage::RawCoverageReader::RawCoverageReader().
Member Function Documentation
read()
std::error_code RawCoverageFilenamesReader::read ()
Definition at line 72 of file CoverageMappingReader.cpp.
References I, llvm::coverage::RawCoverageReader::readSize(), llvm::coverage::RawCoverageReader::readString(), and llvm::coverage::RawCoverageReader::success().
Referenced by readCoverageMappingData().
The documentation for this class was generated from the following files:
CoverageMappingReader.h
CoverageMappingReader.cpp