LLVM: llvm::BitsRecTy Class Reference
LLVM API Documentation
llvm::BitsRecTy Class Reference
#include <Record.h>
Public Member Functions
unsigned getNumBits () const
Init * convertValue (UnsetInit *UI) override
Init * convertValue (BitInit *UI) override
Init * convertValue (BitsInit *BI) override
Init * convertValue (IntInit *II) override
Init * convertValue (StringInit *SI) override
Init * convertValue (ListInit *LI) override
Init * convertValue (VarBitInit *VB) override
Init * convertValue (DefInit *DI) override
Init * convertValue (DagInit *DI) override
Init * convertValue (UnOpInit *UI) override
Init * convertValue (BinOpInit *UI) override
Init * convertValue (TernOpInit *UI) override
Init * convertValue (TypedInit *TI) override
Init * convertValue (VarInit *VI) override
Init * convertValue (FieldInit *FI) override
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
bool baseClassOf (const RecTy *) const override
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static BitsRecTy * get (unsigned Sz)
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
BitsRecTy - 'bits<n>' - Represent a fixed number of bits
Definition at line 179 of file Record.h.
Member Function Documentation
baseClassOf()
bool BitsRecTy::baseClassOf (const RecTy * RHS) const override virtual
Reimplemented from llvm::RecTy.
Definition at line 218 of file Record.cpp.
References llvm::RecTy::baseClassOf(), llvm::RecTy::BitRecTyKind, llvm::cast(), llvm::RecTy::getRecTyKind(), llvm::RecTy::IntRecTyKind, and llvm::RecTy::RecTy().
classof()
bool llvm::BitsRecTy::classof (const RecTy * RT) inline static
Definition at line 184 of file Record.h.
References llvm::RecTy::BitsRecTyKind, llvm::RecTy::getRecTyKind(), and llvm::RecTy::RecTy().
convertValue() [1/15]
Init * llvm::BitsRecTy::convertValue (BinOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 202 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [2/15]
Init * BitsRecTy::convertValue (BitInit * UI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 166 of file Record.cpp.
References llvm::BitsInit::get().
convertValue() [3/15]
Init * BitsRecTy::convertValue (BitsInit * BI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 196 of file Record.cpp.
References llvm::BitsInit::getNumBits().
convertValue() [4/15]
Init * llvm::BitsRecTy::convertValue (DagInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 200 of file Record.h.
convertValue() [5/15]
Init * llvm::BitsRecTy::convertValue (DefInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 199 of file Record.h.
convertValue() [6/15]
Init * llvm::BitsRecTy::convertValue (FieldInit * FI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 206 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [7/15]
Init * BitsRecTy::convertValue (IntInit * II) override virtual
convertValue from Int initializer to bits type: Split the integer up into the appropriate bits.
Reimplemented from llvm::RecTy.
Definition at line 182 of file Record.cpp.
References canFitInBitfield(), llvm::BitInit::get(), llvm::BitsInit::get(), and llvm::IntInit::getValue().
convertValue() [8/15]
Init * llvm::BitsRecTy::convertValue (ListInit * LI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 197 of file Record.h.
convertValue() [9/15]
Init * llvm::BitsRecTy::convertValue (StringInit * SI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 196 of file Record.h.
convertValue() [10/15]
Init * llvm::BitsRecTy::convertValue (TernOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 203 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [11/15]
Init * BitsRecTy::convertValue (TypedInit * TI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 203 of file Record.cpp.
References llvm::BitsInit::get(), llvm::VarBitInit::get(), llvm::isa(), and VI.
convertValue() [12/15]
Init * llvm::BitsRecTy::convertValue (UnOpInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 201 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [13/15]
Init * BitsRecTy::convertValue (UnsetInit * UI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 157 of file Record.cpp.
References llvm::BitsInit::get(), and llvm::UnsetInit::get().
convertValue() [14/15]
Init * llvm::BitsRecTy::convertValue (VarBitInit * VB) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 198 of file Record.h.
convertValue() [15/15]
Init * llvm::BitsRecTy::convertValue (VarInit * VI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 205 of file Record.h.
References llvm::RecTy::convertValue(), and VI.
get()
BitsRecTy * BitsRecTy::get (unsigned Sz) static
Definition at line 143 of file Record.cpp.
getAsString()
std::string BitsRecTy::getAsString () const override virtual
Implements llvm::RecTy.
Definition at line 153 of file Record.cpp.
References llvm::utostr().
getNumBits()
unsigned llvm::BitsRecTy::getNumBits () const inline
Definition at line 190 of file Record.h.
typeIsConvertibleTo()
bool llvm::BitsRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline override virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 210 of file Record.h.
References llvm::RecTy::baseClassOf(), and llvm::RecTy::RecTy().
The documentation for this class was generated from the following files:
Record.h
Record.cpp