LLVM: llvm::DIObjCProperty Class Reference
LLVM API Documentation
llvm::DIObjCProperty Class Reference
#include <DebugInfo.h>
Public Member Functions
DIObjCProperty (const MDNode *N)
StringRef getObjCPropertyName () const
DIFile getFile () const
unsigned getLineNumber () const
StringRef getObjCPropertyGetterName () const
StringRef getObjCPropertySetterName () const
unsigned getAttributes () const
bool isReadOnlyObjCProperty () const
bool isReadWriteObjCProperty () const
bool isAssignObjCProperty () const
bool isRetainObjCProperty () const
bool isCopyObjCProperty () const
bool isNonAtomicObjCProperty () const
DIType getType () const
Get the type.
bool Verify () const
Public Member Functions inherited from llvm::DIDescriptor
DIDescriptor (const MDNode *N=nullptr)
bool Verify () const
MDNode * get () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
StringRef getHeader () const
size_t getNumHeaderFields () const
StringRef getHeaderField (unsigned Index) const
template<class T>
T getHeaderFieldAs (unsigned Index) const
uint16_t getTag () const
bool isDerivedType () const
bool isCompositeType () const
bool isSubroutineType () const
bool isBasicType () const
bool isVariable () const
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
bool isCompileUnit () const
bool isNameSpace () const
bool isLexicalBlockFile () const
bool isLexicalBlock () const
bool isSubrange () const
bool isEnumerator () const
bool isType () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
bool isImportedEntity () const
bool isExpression () const
void print (raw_ostream &OS) const
void dump () const
void replaceAllUsesWith (LLVMContext &VMContext, DIDescriptor D)
Replace all uses of debug info referenced by this descriptor.
void replaceAllUsesWith (MDNode *D)
Friends
class DIDescriptor
Additional Inherited Members
Public Types inherited from llvm::DIDescriptor
enum {
FlagAccessibility = 1 << 0 | 1 << 1 , FlagPrivate = 1 , FlagProtected = 2 , FlagPublic = 3 ,
FlagFwdDecl = 1 << 2 , FlagAppleBlock = 1 << 3 , FlagBlockByrefStruct = 1 << 4 , FlagVirtual = 1 << 5 ,
FlagArtificial = 1 << 6 , FlagExplicit = 1 << 7 , FlagPrototyped = 1 << 8 , FlagObjcClassComplete = 1 << 9 ,
FlagObjectPointer = 1 << 10 , FlagVector = 1 << 11 , FlagStaticMember = 1 << 12 , FlagIndirectVariable = 1 << 13 ,
FlagLValueReference = 1 << 14 , FlagRValueReference = 1 << 15
}
Accessibility flags.
Protected Member Functions inherited from llvm::DIDescriptor
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy>
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
template<>
DITypeRef getFieldAs (unsigned Elt) const
Protected Attributes inherited from llvm::DIDescriptor
const MDNode * DbgNode
Detailed Description
Definition at line 933 of file DebugInfo.h.
Constructor & Destructor Documentation
DIObjCProperty()
llvm::DIObjCProperty::DIObjCProperty (const MDNode * N) inline explicit
Definition at line 938 of file DebugInfo.h.
References DIDescriptor, and N.
Member Function Documentation
getAttributes()
unsigned llvm::DIObjCProperty::getAttributes () const inline
Definition at line 946 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
Referenced by isAssignObjCProperty(), isCopyObjCProperty(), isNonAtomicObjCProperty(), isReadOnlyObjCProperty(), isReadWriteObjCProperty(), and isRetainObjCProperty().
getFile()
DIFile llvm::DIObjCProperty::getFile () const inline
Definition at line 941 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
Referenced by llvm::DwarfUnit::addSourceLine().
getLineNumber()
unsigned llvm::DIObjCProperty::getLineNumber () const inline
Definition at line 942 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
Referenced by llvm::DwarfUnit::addSourceLine().
getObjCPropertyGetterName()
StringRef llvm::DIObjCProperty::getObjCPropertyGetterName () const inline
Definition at line 944 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
Referenced by llvm::DwarfUnit::constructTypeDIE().
getObjCPropertyName()
StringRef llvm::DIObjCProperty::getObjCPropertyName () const inline
Definition at line 940 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
Referenced by llvm::DwarfUnit::constructTypeDIE().
getObjCPropertySetterName()
StringRef llvm::DIObjCProperty::getObjCPropertySetterName () const inline
Definition at line 945 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
Referenced by llvm::DwarfUnit::constructTypeDIE().
getType()
DIType llvm::DIObjCProperty::getType () const inline
Get the type.
Note
Objective-C doesn't have an ODR, so there is no benefit in storing the type as a DITypeRef here.
Definition at line 970 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isAssignObjCProperty()
bool llvm::DIObjCProperty::isAssignObjCProperty () const inline
Definition at line 953 of file DebugInfo.h.
References llvm::dwarf::DW_APPLE_PROPERTY_assign, and getAttributes().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isCopyObjCProperty()
bool llvm::DIObjCProperty::isCopyObjCProperty () const inline
Definition at line 959 of file DebugInfo.h.
References llvm::dwarf::DW_APPLE_PROPERTY_copy, and getAttributes().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isNonAtomicObjCProperty()
bool llvm::DIObjCProperty::isNonAtomicObjCProperty () const inline
Definition at line 962 of file DebugInfo.h.
References llvm::dwarf::DW_APPLE_PROPERTY_nonatomic, and getAttributes().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isReadOnlyObjCProperty()
bool llvm::DIObjCProperty::isReadOnlyObjCProperty () const inline
Definition at line 947 of file DebugInfo.h.
References llvm::dwarf::DW_APPLE_PROPERTY_readonly, and getAttributes().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isReadWriteObjCProperty()
bool llvm::DIObjCProperty::isReadWriteObjCProperty () const inline
Definition at line 950 of file DebugInfo.h.
References llvm::dwarf::DW_APPLE_PROPERTY_readwrite, and getAttributes().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isRetainObjCProperty()
bool llvm::DIObjCProperty::isRetainObjCProperty () const inline
Definition at line 956 of file DebugInfo.h.
References llvm::dwarf::DW_APPLE_PROPERTY_retain, and getAttributes().
Referenced by llvm::DwarfUnit::constructTypeDIE().
Verify()
bool DIObjCProperty::Verify () const
Definition at line 366 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, llvm::DIDescriptor::getNumHeaderFields(), and llvm::DIDescriptor::isObjCProperty().
Referenced by llvm::DIDescriptor::Verify().
Friends And Related Symbol Documentation
DIDescriptor
friend class DIDescriptor friend
Definition at line 934 of file DebugInfo.h.
References DIDescriptor.
Referenced by DIDescriptor, and DIObjCProperty().
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp