LLVM: llvm::MachineFunctionPass Class Reference
LLVM API Documentation
llvm::MachineFunctionPass Class Reference abstract
#include <MachineFunctionPass.h>
Protected Member Functions
MachineFunctionPass (char &ID)
virtual bool runOnMachineFunction (MachineFunction &MF)=0
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Additional Inherited Members
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
MachineFunctionPass - This class adapts the FunctionPass interface to allow convenient creation of passes that operate on the MachineFunction representation. Instead of overriding runOnFunction, subclasses override runOnMachineFunction.
Definition at line 32 of file MachineFunctionPass.h.
Constructor & Destructor Documentation
MachineFunctionPass()
llvm::MachineFunctionPass::MachineFunctionPass (char & ID) inline explicit protected
Definition at line 34 of file MachineFunctionPass.h.
References llvm::FunctionPass::FunctionPass().
Referenced by llvm::AsmPrinter::AsmPrinter(), llvm::EdgeBundles::EdgeBundles(), llvm::LiveDebugVariables::LiveDebugVariables(), llvm::LiveIntervals::LiveIntervals(), llvm::LiveRegMatrix::LiveRegMatrix(), llvm::LiveStacks::LiveStacks(), llvm::LiveVariables::LiveVariables(), llvm::MachineBlockFrequencyInfo::MachineBlockFrequencyInfo(), llvm::MachineDominanceFrontier::MachineDominanceFrontier(), llvm::MachineDominatorTree::MachineDominatorTree(), llvm::MachineLoopInfo::MachineLoopInfo(), llvm::MachineRegionInfoPass::MachineRegionInfoPass(), llvm::MachineTraceMetrics::MachineTraceMetrics(), llvm::MipsModuleDAGToDAGISel::MipsModuleDAGToDAGISel(), llvm::PEI::PEI(), llvm::SelectionDAGISel::SelectionDAGISel(), llvm::SlotIndexes::SlotIndexes(), llvm::SpillPlacement::SpillPlacement(), and llvm::VirtRegMap::VirtRegMap().
Member Function Documentation
getAnalysisUsage()
void MachineFunctionPass::getAnalysisUsage (AnalysisUsage & AU) const override protected virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::Pass.
Reimplemented in llvm::MachineLoopInfo, llvm::MachinePostDominatorTree, llvm::MachineRegionInfoPass, llvm::MachineTraceMetrics, llvm::PEI, llvm::SelectionDAGISel, llvm::SlotIndexes, llvm::StackMapLiveness, and llvm::VirtRegMap.
Definition at line 44 of file MachineFunctionPass.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), and llvm::Pass::getAnalysisUsage().
Referenced by llvm::AsmPrinter::getAnalysisUsage(), llvm::LiveIntervals::getAnalysisUsage(), llvm::LiveStacks::getAnalysisUsage(), llvm::LiveVariables::getAnalysisUsage(), llvm::MachineBlockFrequencyInfo::getAnalysisUsage(), llvm::MachineDominanceFrontier::getAnalysisUsage(), llvm::MachineLoopInfo::getAnalysisUsage(), llvm::MachinePostDominatorTree::getAnalysisUsage(), llvm::MachineTraceMetrics::getAnalysisUsage(), llvm::PEI::getAnalysisUsage(), llvm::SelectionDAGISel::getAnalysisUsage(), llvm::SlotIndexes::getAnalysisUsage(), and llvm::VirtRegMap::getAnalysisUsage().
runOnMachineFunction()
virtual bool llvm::MachineFunctionPass::runOnMachineFunction (MachineFunction & MF) protected pure virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implemented in llvm::AMDGPUAsmPrinter, llvm::ARMAsmPrinter, llvm::AsmPrinter, llvm::LiveIntervals, llvm::LiveStacks, llvm::LiveVariables, llvm::MachineBlockFrequencyInfo, llvm::MachineDominanceFrontier, llvm::MachineDominatorTree, llvm::MachineLoopInfo, llvm::MachinePostDominatorTree, llvm::MachineRegionInfoPass, llvm::MachineTraceMetrics, llvm::MipsAsmPrinter, llvm::MipsDAGToDAGISel, llvm::MipsModuleDAGToDAGISel, llvm::PEI, llvm::SelectionDAGISel, llvm::SlotIndexes, llvm::StackMapLiveness, llvm::VirtRegMap, and llvm::X86AsmPrinter.
References F.
The documentation for this class was generated from the following files:
MachineFunctionPass.h
MachineFunctionPass.cpp