LLVM: llvm::MCObjectStreamer Class Reference
LLVM API Documentation
llvm::MCObjectStreamer Class Reference abstract
Streaming object file generation interface.
#include <MCObjectStreamer.h>
Public Member Functions
void reset () override
state management
bool isIntegratedAssemblerRequired () const override
Object streamers require the integrated assembler.
MCSymbolData & getOrCreateSymbolData (const MCSymbol *Symbol)
void EmitFrames (MCAsmBackend *MAB)
void EmitCFISections (bool EH, bool Debug) override
void visitUsedSymbol (const MCSymbol &Sym) override
MCAssembler & getAssembler ()
MCStreamer Interface
void EmitLabel (MCSymbol *Symbol) override
void EmitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
void EmitValueImpl (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc()) override
void EmitULEB128Value (const MCExpr *Value) override
void EmitSLEB128Value (const MCExpr *Value) override
void EmitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
void ChangeSection (const MCSection *Section, const MCExpr *Subsection) override
void EmitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI) override
virtual void EmitInstToFragment (const MCInst &Inst, const MCSubtargetInfo &)
Emit an instruction to a special fragment, because this instruction can change its size during relaxation.
void EmitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section. The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
void EmitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void EmitBundleUnlock () override
Ends a bundle-locked group.
void EmitBytes (StringRef Data) override
void EmitValueToAlignment (unsigned ByteAlignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0) override
void EmitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit=0) override
bool EmitValueToOffset (const MCExpr *Offset, unsigned char Value) override
void EmitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) override
EmitDwarfLocDirective - This implements the DWARF2.
void EmitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol *LastLabel, const MCSymbol *Label, unsigned PointerSize)
void EmitDwarfAdvanceFrameAddr (const MCSymbol *LastLabel, const MCSymbol *Label)
void EmitGPRel32Value (const MCExpr *Value) override
void EmitGPRel64Value (const MCExpr *Value) override
void EmitFill (uint64_t NumBytes, uint8_t FillValue) override
void EmitZeros (uint64_t NumBytes) override
Emit NumBytes worth of zeros. This function properly handles data in virtual sections.
void FinishImpl () override
FinishImpl - Streamer specific finalization.
bool mayHaveInstructions () const override
Public Member Functions inherited from llvm::MCStreamer
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
void setTargetStreamer (MCTargetStreamer *TS)
MCContext & getContext () const
MCTargetStreamer * getTargetStreamer ()
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
unsigned getNumWinFrameInfos ()
ArrayRef< WinEH::FrameInfo * > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
virtual void EmitFileDirective (StringRef Filename)
virtual void EmitIdent (StringRef IdentString)
virtual unsigned EmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, unsigned CUID=0)
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
void EmitCFIStartProc (bool IsSimple)
void EmitCFIEndProc ()
virtual void EmitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void EmitCFIDefCfaOffset (int64_t Offset)
virtual void EmitCFIDefCfaRegister (int64_t Register)
virtual void EmitCFIOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFIRememberState ()
virtual void EmitCFIRestoreState ()
virtual void EmitCFISameValue (int64_t Register)
virtual void EmitCFIRestore (int64_t Register)
virtual void EmitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void EmitCFIEscape (StringRef Values)
virtual void EmitCFISignalFrame ()
virtual void EmitCFIUndefined (int64_t Register)
virtual void EmitCFIRegister (int64_t Register1, int64_t Register2)
virtual void EmitCFIWindowSave ()
virtual void EmitWinCFIStartProc (const MCSymbol *Symbol)
virtual void EmitWinCFIEndProc ()
virtual void EmitWinCFIStartChained ()
virtual void EmitWinCFIEndChained ()
virtual void EmitWinCFIPushReg (unsigned Register)
virtual void EmitWinCFISetFrame (unsigned Register, unsigned Offset)
virtual void EmitWinCFIAllocStack (unsigned Size)
virtual void EmitWinCFISaveReg (unsigned Register, unsigned Offset)
virtual void EmitWinCFISaveXMM (unsigned Register, unsigned Offset)
virtual void EmitWinCFIPushFrame (bool Code)
virtual void EmitWinCFIEndProlog ()
virtual void EmitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except)
virtual void EmitWinEHHandlerData ()
void EmitRawText (const Twine &String)
virtual void Flush ()
Flush - Causes any cached state to be written out.
void Finish ()
Finish - Finish emission of machine code.
virtual bool isVerboseAsm () const
virtual bool hasRawTextSupport () const
virtual void AddComment (const Twine &T)
virtual raw_ostream & GetCommentOS ()
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
virtual void AddBlankLine ()
AddBlankLine - Emit a blank line to a .s file to pretty it up.
MCSectionSubPair getCurrentSection () const
MCSectionSubPair getPreviousSection () const
unsigned GetSymbolOrder (const MCSymbol *Sym) const
void PushSection ()
bool PopSection ()
bool SubSection (const MCExpr *Subsection)
virtual void SwitchSection (const MCSection *Section, const MCExpr *Subsection=nullptr)
void SwitchSectionNoChange (const MCSection *Section, const MCExpr *Subsection=nullptr)
virtual void InitSections (bool NoExecStack)
Create the default sections and set the initial one.
void AssignSection (MCSymbol *Symbol, const MCSection *Section)
virtual void EmitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void EmitAssemblerFlag (MCAssemblerFlag Flag)
EmitAssemblerFlag - Note in the output the specified Flag.
virtual void EmitLinkerOptions (ArrayRef< std::string > Kind)
virtual void EmitDataRegion (MCDataRegionType Kind)
EmitDataRegion - Note in the output the specified region Kind.
virtual void EmitVersionMin (MCVersionMinType, unsigned Major, unsigned Minor, unsigned Update)
EmitVersionMin - Specify the MachO minimum deployment target version.
virtual void EmitThumbFunc (MCSymbol *Func)
virtual bool EmitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute)=0
EmitSymbolAttribute - Add the given Attribute to Symbol.
virtual void EmitSymbolDesc (MCSymbol *Symbol, unsigned DescValue)
virtual void BeginCOFFSymbolDef (const MCSymbol *Symbol)
virtual void EmitCOFFSymbolStorageClass (int StorageClass)
virtual void EmitCOFFSymbolType (int Type)
virtual void EndCOFFSymbolDef ()
EndCOFFSymbolDef - Marks the end of the symbol definition.
virtual void EmitCOFFSectionIndex (MCSymbol const *Symbol)
virtual void EmitCOFFSecRel32 (MCSymbol const *Symbol)
virtual void EmitELFSize (MCSymbol *Symbol, const MCExpr *Value)
virtual void EmitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
virtual void EmitCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment)=0
virtual void EmitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment)
virtual void EmitZerofill (const MCSection *Section, MCSymbol *Symbol=nullptr, uint64_t Size=0, unsigned ByteAlignment=0)=0
virtual void EmitTBSSSymbol (const MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment=0)
void EmitValue (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc())
virtual void EmitIntValue (uint64_t Value, unsigned Size)
void EmitULEB128IntValue (uint64_t Value, unsigned Padding=0)
void EmitSLEB128IntValue (int64_t Value)
void EmitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
Protected Member Functions
MCObjectStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter)
MCObjectStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &_OS, MCCodeEmitter *_Emitter, MCAssembler *_Assembler)
~MCObjectStreamer ()
MCSectionData * getCurrentSectionData () const
MCFragment * getCurrentFragment () const
void insert (MCFragment *F)
MCDataFragment * getOrCreateDataFragment ()
Protected Member Functions inherited from llvm::MCStreamer
MCStreamer (MCContext &Ctx)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void EmitWindowsUnwindTables ()
virtual void EmitRawTextImpl (StringRef String)
Detailed Description
Streaming object file generation interface.
This class provides an implementation of the MCStreamer interface which is suitable for use with the assembler backend. Specific object file formats are expected to subclass this interface to implement directives specific to that file format or custom semantics expected by the object writer implementation.
Definition at line 35 of file MCObjectStreamer.h.
Constructor & Destructor Documentation
MCObjectStreamer() [1/2]
MCObjectStreamer::MCObjectStreamer (MCContext & Context, MCAsmBackend & TAB, raw_ostream & _OS, MCCodeEmitter * _Emitter) protected
Definition at line 25 of file MCObjectStreamer.cpp.
References true.
Referenced by llvm::MCELFStreamer::MCELFStreamer(), llvm::MCELFStreamer::MCELFStreamer(), and llvm::MCWinCOFFStreamer::MCWinCOFFStreamer().
MCObjectStreamer() [2/2]
MCObjectStreamer::MCObjectStreamer (MCContext & Context, MCAsmBackend & TAB, raw_ostream & _OS, MCCodeEmitter * _Emitter, MCAssembler * _Assembler) protected
Definition at line 32 of file MCObjectStreamer.cpp.
References true.
~MCObjectStreamer()
MCObjectStreamer::~MCObjectStreamer () protected
Definition at line 38 of file MCObjectStreamer.cpp.
Member Function Documentation
ChangeSection()
void MCObjectStreamer::ChangeSection (const MCSection * , const MCExpr *) override virtual
ChangeSection - Update streamer for a new active section.
This is called by PopSection and SwitchSection, if the current section changes.
Reimplemented from llvm::MCStreamer.
Definition at line 182 of file MCObjectStreamer.cpp.
References getAssembler(), llvm::MCAssembler::getOrCreateSectionData(), and llvm::report_fatal_error().
Referenced by llvm::MCELFStreamer::ChangeSection().
EmitAssignment()
void MCObjectStreamer::EmitAssignment (MCSymbol * Symbol, const MCExpr * Value) override virtual
EmitAssignment - Emit an assignment of Value to Symbol.
This corresponds to an assembler statement such as: symbol = value
The assignment generates no code, but has the side effect of binding the value in the current context. For the assembly streamer, this prints the binding into the .s file.
Parameters
Symbol - The symbol being assigned to.
Value - The value for the symbol.
Reimplemented from llvm::MCStreamer.
Definition at line 199 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitAssignment(), getAssembler(), and llvm::MCAssembler::getOrCreateSymbolData().
EmitBundleAlignMode()
void MCObjectStreamer::EmitBundleAlignMode (unsigned AlignPow2) override virtual
Set the bundle alignment mode from now on in the section. The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
Reimplemented from llvm::MCStreamer.
Definition at line 261 of file MCObjectStreamer.cpp.
References BundlingNotImplementedMsg, and llvm_unreachable.
EmitBundleLock()
void MCObjectStreamer::EmitBundleLock (bool AlignToEnd) override virtual
The following instructions are a bundle-locked group.
Parameters
AlignToEnd - If true, the bundle-locked group will be aligned to the end of a bundle.
Reimplemented from llvm::MCStreamer.
Definition at line 265 of file MCObjectStreamer.cpp.
References BundlingNotImplementedMsg, and llvm_unreachable.
EmitBundleUnlock()
void MCObjectStreamer::EmitBundleUnlock () override virtual
Ends a bundle-locked group.
Reimplemented from llvm::MCStreamer.
Definition at line 269 of file MCObjectStreamer.cpp.
References BundlingNotImplementedMsg, and llvm_unreachable.
EmitBytes()
void MCObjectStreamer::EmitBytes (StringRef Data) override virtual
EmitBytes - Emit the bytes in Data into the output.
This is used to implement assembler directives such as .byte, .ascii, etc.
Reimplemented from llvm::MCStreamer.
Definition at line 337 of file MCObjectStreamer.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::StringRef::end(), llvm::MCDataFragment::getContents(), llvm::MCStreamer::getCurrentSection(), getOrCreateDataFragment(), and llvm::MCLineEntry::Make().
Referenced by llvm::MCDwarfFrameEmitter::EmitAdvanceLoc(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), and llvm::MCELFStreamer::EmitIdent().
EmitCFISections()
void MCObjectStreamer::EmitCFISections (bool EH, bool Debug) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 106 of file MCObjectStreamer.cpp.
References Debug, and llvm::MCStreamer::EmitCFISections().
EmitCodeAlignment()
void MCObjectStreamer::EmitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit = 0) override virtual
EmitCodeAlignment - Emit nops until the byte alignment ByteAlignment is reached.
This used to align code where the alignment bytes may be executed. This can emit different bytes for different sizes to optimize execution.
Parameters
ByteAlignment - The alignment to reach. This must be a power of two on some targets.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented from llvm::MCStreamer.
Definition at line 355 of file MCObjectStreamer.cpp.
References llvm::cast(), EmitValueToAlignment(), and getCurrentFragment().
Referenced by llvm::MCELFStreamer::InitSections(), and llvm::MCWinCOFFStreamer::InitSections().
EmitDwarfAdvanceFrameAddr()
void MCObjectStreamer::EmitDwarfAdvanceFrameAddr (const MCSymbol * LastLabel, const MCSymbol * Label)
Definition at line 326 of file MCObjectStreamer.cpp.
References buildSymbolDiff(), llvm::MCDwarfFrameEmitter::EmitAdvanceLoc(), getAssembler(), and insert().
EmitDwarfAdvanceLineAddr()
void MCObjectStreamer::EmitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol * LastLabel, const MCSymbol * Label, unsigned PointerSize)
Definition at line 309 of file MCObjectStreamer.cpp.
References buildSymbolDiff(), llvm::MCDwarfLineAddr::Emit(), emitDwarfSetLineAddr(), getAssembler(), and insert().
Referenced by EmitDwarfLineTable().
EmitDwarfLocDirective()
void MCObjectStreamer::EmitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) override virtual
EmitDwarfLocDirective - This implements the DWARF2.
Reimplemented from llvm::MCStreamer.
Definition at line 273 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitDwarfLocDirective(), llvm::MCStreamer::getCurrentSection(), and llvm::MCLineEntry::Make().
EmitFill()
void MCObjectStreamer::EmitFill (uint64_t NumBytes, uint8_t FillValue) override virtual
EmitFill - Emit NumBytes bytes worth of the value specified by FillValue. This implements directives such as '.space'.
Reimplemented from llvm::MCStreamer.
Definition at line 401 of file MCObjectStreamer.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::MCDataFragment::getContents(), and getOrCreateDataFragment().
Referenced by EmitValueToOffset().
EmitFrames()
void MCObjectStreamer::EmitFrames (MCAsmBackend * MAB)
Definition at line 71 of file MCObjectStreamer.cpp.
References llvm::MCDwarfFrameEmitter::Emit(), and llvm::MCStreamer::getNumFrameInfos().
Referenced by llvm::MCELFStreamer::FinishImpl().
EmitGPRel32Value()
void MCObjectStreamer::EmitGPRel32Value (const MCExpr * Value) override virtual
EmitGPRel32Value - Emit the expression Value into the output as a gprel32 (32-bit GP relative) value.
This is used to implement assembler directives such as .gprel32 on targets that support them.
Reimplemented from llvm::MCStreamer.
Definition at line 384 of file MCObjectStreamer.cpp.
References llvm::MCFixup::Create(), llvm::FK_GPRel_4, llvm::MCDataFragment::getContents(), llvm::MCDataFragment::getFixups(), getOrCreateDataFragment(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
EmitGPRel64Value()
void MCObjectStreamer::EmitGPRel64Value (const MCExpr * Value) override virtual
EmitGPRel64Value - Emit the expression Value into the output as a gprel64 (64-bit GP relative) value.
This is used to implement assembler directives such as .gpdword on targets that support them.
Reimplemented from llvm::MCStreamer.
Definition at line 393 of file MCObjectStreamer.cpp.
References llvm::MCFixup::Create(), llvm::FK_GPRel_4, llvm::MCDataFragment::getContents(), llvm::MCDataFragment::getFixups(), getOrCreateDataFragment(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
EmitInstruction()
void MCObjectStreamer::EmitInstruction (const MCInst & Inst, const MCSubtargetInfo & STI) override virtual
EmitInstruction - Emit the given Instruction into the current section.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 204 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitInstruction(), EmitInstToFragment(), getAssembler(), llvm::MCAssembler::getBackend(), llvm::MCStreamer::getCurrentSection(), getCurrentSectionData(), llvm::MCSectionData::isBundleLocked(), llvm::MCLineEntry::Make(), llvm::MCAsmBackend::relaxInstruction(), and llvm::MCSectionData::setHasInstructions().
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), and llvm::MipsELFStreamer::EmitInstruction().
EmitInstToFragment()
void MCObjectStreamer::EmitInstToFragment (const MCInst & Inst, const MCSubtargetInfo & STI) virtual
Emit an instruction to a special fragment, because this instruction can change its size during relaxation.
Definition at line 241 of file MCObjectStreamer.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::MCCodeEmitter::EncodeInstruction(), llvm::raw_ostream::flush(), getAssembler(), llvm::MCRelaxableFragment::getContents(), llvm::MCAssembler::getEmitter(), llvm::MCRelaxableFragment::getFixups(), and insert().
Referenced by EmitInstruction().
EmitLabel()
void MCObjectStreamer::EmitLabel (MCSymbol * Symbol) override virtual
EmitLabel - Emit a label for Symbol into the current section.
This corresponds to an assembler statement such as: foo:
Parameters
Symbol - The symbol to emit. A given symbol should only be emitted as a label once, and symbols emitted as a label should never be used in an assignment.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MCWinCOFFStreamer, and llvm::MipsELFStreamer.
Definition at line 142 of file MCObjectStreamer.cpp.
References llvm::dyn_cast_or_null(), llvm::MCStreamer::EmitLabel(), F, getAssembler(), getCurrentFragment(), llvm::MCSymbolData::getFragment(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCSymbolData::setFragment(), and llvm::MCSymbolData::setOffset().
Referenced by llvm::MCDwarfFrameEmitter::Emit(), llvm::MCDwarfLineTable::EmitCU(), EmitDwarfLineTable(), llvm::MCELFStreamer::EmitLabel(), llvm::MCWinCOFFStreamer::EmitLabel(), EmitValueToOffset(), and llvm::MCLineEntry::Make().
EmitSLEB128Value()
void MCObjectStreamer::EmitSLEB128Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 168 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitSLEB128IntValue(), getAssembler(), and insert().
EmitULEB128Value()
void MCObjectStreamer::EmitULEB128Value (const MCExpr * Value) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 159 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::EmitULEB128IntValue(), getAssembler(), and insert().
EmitValueImpl()
void MCObjectStreamer::EmitValueImpl (const MCExpr * Value, unsigned Size, const SMLoc & Loc = SMLoc()) override virtual
EmitValue - Emit the expression Value into the output as a native integer of the given Size bytes.
This is used to implement assembler directives such as .word, .quad, etc.
Parameters
Value - The value to emit.
Size - The size of the integer (in bytes) to emit. This must match a native machine width.
Loc - The location of the expression for error reporting.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 112 of file MCObjectStreamer.cpp.
References llvm::MCFixup::Create(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitValueImpl(), getAssembler(), llvm::MCDataFragment::getContents(), llvm::MCStreamer::getCurrentSection(), llvm::MCDataFragment::getFixups(), llvm::MCFixup::getKindForSize(), getOrCreateDataFragment(), llvm::MCLineEntry::Make(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::MCELFStreamer::EmitValueImpl().
EmitValueToAlignment()
void MCObjectStreamer::EmitValueToAlignment (unsigned ByteAlignment, int64_t Value = 0, unsigned ValueSize = 1, unsigned MaxBytesToEmit = 0) override virtual
EmitValueToAlignment - Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
If the number of bytes need to emit for the alignment is not a multiple of ValueSize, then the contents of the emitted fill bytes is undefined.
This used to implement the .align assembler directive.
Parameters
ByteAlignment - The alignment to reach. This must be a power of two on some targets.
Value - The value to use when filling bytes.
ValueSize - The size of the integer (in bytes) to emit for Value. This must match a native machine width.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented from llvm::MCStreamer.
Definition at line 342 of file MCObjectStreamer.cpp.
References getCurrentSectionData(), insert(), and llvm::MCSectionData::setAlignment().
Referenced by llvm::MCDwarfFrameEmitter::Emit(), EmitCodeAlignment(), and llvm::MCELFStreamer::EmitValueToAlignment().
EmitValueToOffset()
bool MCObjectStreamer::EmitValueToOffset (const MCExpr * Offset, unsigned char Value) override virtual
EmitValueToOffset - Emit some number of copies of Value until the byte offset Offset is reached.
This is used to implement assembler directives such as .org.
Parameters
Offset - The offset to reach. This may be an expression, but the expression must be associated with the current section.
Value - The value to use when filling bytes.
Returns
false on success, true if the offset was invalid.
Reimplemented from llvm::MCStreamer.
Definition at line 361 of file MCObjectStreamer.cpp.
References llvm::MCBinaryExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCContext::CreateTempSymbol(), EmitFill(), EmitLabel(), getAssembler(), llvm::MCStreamer::getContext(), insert(), llvm::MCBinaryExpr::Sub, and llvm::MCSymbolRefExpr::VK_None.
EmitWeakReference()
void MCObjectStreamer::EmitWeakReference (MCSymbol * Alias, const MCSymbol * Symbol) override virtual
EmitWeakReference - Emit an weak reference from Alias to Symbol.
This corresponds to an assembler statement such as: .weakref alias, symbol
Parameters
Alias - The alias that is being created.
Symbol - The symbol being aliased.
Reimplemented from llvm::MCStreamer.
Definition at line 177 of file MCObjectStreamer.cpp.
References llvm::report_fatal_error().
EmitZeros()
void MCObjectStreamer::EmitZeros (uint64_t NumBytes) override virtual
Emit NumBytes worth of zeros. This function properly handles data in virtual sections.
The implementation in this class just redirects to EmitFill.
Reimplemented from llvm::MCStreamer.
Definition at line 407 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::getCurrentSection(), insert(), and llvm::MCSection::isVirtualSection().
FinishImpl()
void MCObjectStreamer::FinishImpl () override virtual
FinishImpl - Streamer specific finalization.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 414 of file MCObjectStreamer.cpp.
References llvm::MCDwarfLineTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCAssembler::Finish(), getAssembler(), and llvm::MCStreamer::getContext().
Referenced by llvm::MCELFStreamer::FinishImpl(), and llvm::MCWinCOFFStreamer::FinishImpl().
getAssembler()
MCAssembler & llvm::MCObjectStreamer::getAssembler () inline
Definition at line 91 of file MCObjectStreamer.h.
Referenced by llvm::MCELFStreamer::ChangeSection(), ChangeSection(), llvm::createELFStreamer(), llvm::MCELFStreamer::EmitAssemblerFlag(), EmitAssignment(), llvm::MCELFStreamer::EmitBundleAlignMode(), llvm::MCELFStreamer::EmitBundleLock(), llvm::MCELFStreamer::EmitBundleUnlock(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolStorageClass(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolType(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MipsTargetELFStreamer::emitDirectiveAbiCalls(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitDirectiveNaN2008(), llvm::MipsTargetELFStreamer::emitDirectiveNaNLegacy(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic0(), llvm::MipsTargetELFStreamer::emitDirectiveOptionPic2(), llvm::MipsTargetELFStreamer::emitDirectiveSetMicroMips(), llvm::MipsTargetELFStreamer::emitDirectiveSetMips16(), llvm::MipsTargetELFStreamer::emitDirectiveSetNoReorder(), EmitDwarfAdvanceFrameAddr(), EmitDwarfAdvanceLineAddr(), llvm::MCELFStreamer::EmitELFSize(), llvm::MCELFStreamer::EmitFileDirective(), llvm::MCWinCOFFStreamer::EmitFileDirective(), llvm::MipsTargetELFStreamer::emitFrame(), llvm::MCELFStreamer::EmitIdent(), llvm::AMDGPUAsmPrinter::EmitInstruction(), EmitInstruction(), llvm::MCWinCOFFStreamer::EmitInstToData(), EmitInstToFragment(), llvm::MCELFStreamer::EmitLabel(), EmitLabel(), llvm::MCELFStreamer::EmitLocalCommonSymbol(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), EmitSLEB128Value(), llvm::MCELFStreamer::EmitSymbolAttribute(), llvm::MCWinCOFFStreamer::EmitSymbolAttribute(), EmitULEB128Value(), EmitValueImpl(), EmitValueToOffset(), llvm::MCELFStreamer::EmitWeakReference(), llvm::MipsTargetELFStreamer::finish(), FinishImpl(), llvm::MCELFStreamer::Flush(), getOrCreateSymbolData(), and llvm::MipsTargetELFStreamer::MipsTargetELFStreamer().
getCurrentFragment()
MCFragment * MCObjectStreamer::getCurrentFragment () const protected
Definition at line 82 of file MCObjectStreamer.cpp.
References getCurrentSectionData().
Referenced by EmitCodeAlignment(), EmitLabel(), and getOrCreateDataFragment().
getCurrentSectionData()
MCSectionData * llvm::MCObjectStreamer::getCurrentSectionData () const inline protected
Definition at line 72 of file MCObjectStreamer.h.
Referenced by llvm::MCELFStreamer::ChangeSection(), llvm::MCELFStreamer::EmitBundleLock(), llvm::MCELFStreamer::EmitBundleUnlock(), EmitInstruction(), llvm::MCELFStreamer::EmitSymbolAttribute(), llvm::MCELFStreamer::EmitValueImpl(), llvm::MCELFStreamer::EmitValueToAlignment(), EmitValueToAlignment(), getCurrentFragment(), and mayHaveInstructions().
getOrCreateDataFragment()
MCDataFragment * MCObjectStreamer::getOrCreateDataFragment () protected
Get a data fragment to write into, creating a new one if the current fragment is not a data fragment.
Definition at line 91 of file MCObjectStreamer.cpp.
References llvm::dyn_cast_or_null(), F, getCurrentFragment(), and insert().
Referenced by EmitBytes(), llvm::MCWinCOFFStreamer::EmitCOFFSecRel32(), llvm::MCWinCOFFStreamer::EmitCOFFSectionIndex(), EmitFill(), EmitGPRel32Value(), EmitGPRel64Value(), llvm::MCWinCOFFStreamer::EmitInstToData(), and EmitValueImpl().
getOrCreateSymbolData()
MCSymbolData & llvm::MCObjectStreamer::getOrCreateSymbolData (const MCSymbol * Symbol) inline
Definition at line 65 of file MCObjectStreamer.h.
References getAssembler(), and llvm::MCAssembler::getOrCreateSymbolData().
Referenced by llvm::MipsTargetELFStreamer::emitAssignment(), llvm::MipsELFStreamer::EmitInstruction(), and llvm::MipsTargetELFStreamer::emitLabel().
insert()
void llvm::MCObjectStreamer::insert (MCFragment * F) inline protected
Definition at line 78 of file MCObjectStreamer.h.
References F.
Referenced by EmitDwarfAdvanceFrameAddr(), EmitDwarfAdvanceLineAddr(), EmitInstToFragment(), EmitSLEB128Value(), EmitULEB128Value(), EmitValueToAlignment(), EmitValueToOffset(), EmitZeros(), and getOrCreateDataFragment().
isIntegratedAssemblerRequired()
bool llvm::MCObjectStreamer::isIntegratedAssemblerRequired () const inline override virtual
Object streamers require the integrated assembler.
Reimplemented from llvm::MCStreamer.
Definition at line 63 of file MCObjectStreamer.h.
mayHaveInstructions()
bool llvm::MCObjectStreamer::mayHaveInstructions () const inline override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 136 of file MCObjectStreamer.h.
References getCurrentSectionData(), and llvm::MCSectionData::hasInstructions().
reset()
void MCObjectStreamer::reset () override virtual
state management
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MCWinCOFFStreamer.
Definition at line 60 of file MCObjectStreamer.cpp.
References llvm::MCStreamer::reset().
Referenced by llvm::MCELFStreamer::reset(), and llvm::MCWinCOFFStreamer::reset().
visitUsedSymbol()
void MCObjectStreamer::visitUsedSymbol (const MCSymbol & Sym) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 102 of file MCObjectStreamer.cpp.
The documentation for this class was generated from the following files:
MCObjectStreamer.h
MCObjectStreamer.cpp