LLVM: llvm::LibCallSimplifier Class Reference
LLVM API Documentation
llvm::LibCallSimplifier Class Reference
#include <SimplifyLibCalls.h>
Public Member Functions
LibCallSimplifier (const DataLayout *TD, const TargetLibraryInfo *TLI)
Value * optimizeCall (CallInst *CI)
virtual void replaceAllUsesWith (Instruction *I, Value *With) const
Protected Member Functions
~LibCallSimplifier ()
Detailed Description
LibCallSimplifier - This class implements a collection of optimizations that replace well formed calls to library functions with a more optimal form. For example, replacing 'printf("Hello!")' with 'puts("Hello!")'.
Definition at line 71 of file SimplifyLibCalls.h.
Constructor & Destructor Documentation
~LibCallSimplifier()
llvm::LibCallSimplifier::~LibCallSimplifier () inline protected
Definition at line 79 of file SimplifyLibCalls.h.
LibCallSimplifier()
LibCallSimplifier::LibCallSimplifier (const DataLayout * TD, const TargetLibraryInfo * TLI)
Definition at line 2091 of file SimplifyLibCalls.cpp.
Member Function Documentation
optimizeCall()
Value * LibCallSimplifier::optimizeCall (CallInst * CI)
optimizeCall - Take the given call instruction and return a more optimal value to replace the instruction with or 0 if a more optimal form can't be found. Note that the returned value may be equal to the instruction being optimized. In this case all other instructions that use the given instruction were modified and the given instruction is dead. The call must not be an indirect call.
Definition at line 1924 of file SimplifyLibCalls.cpp.
References llvm::LibFunc::abs, llvm::LibFunc::acos, llvm::LibFunc::acosh, llvm::LibFunc::asin, llvm::LibFunc::asinh, llvm::LibFunc::atan, llvm::LibFunc::atanh, llvm::CallingConv::C, llvm::LibFunc::cbrt, llvm::LibFunc::ceil, llvm::LibFunc::copysign, llvm::LibFunc::cos, llvm::LibFunc::cosf, llvm::LibFunc::cosh, llvm::LibFunc::cosl, llvm::LibFunc::cospi, llvm::LibFunc::cospif, llvm::dyn_cast(), EnableUnsafeFPShrink, llvm::Instruction::eraseFromParent(), llvm::LibFunc::exp, llvm::LibFunc::exp10, llvm::Intrinsic::exp2, llvm::LibFunc::exp2, llvm::LibFunc::exp2f, llvm::LibFunc::exp2l, llvm::LibFunc::expm1, llvm::Intrinsic::fabs, llvm::LibFunc::fabs, llvm::LibFunc::fabsf, llvm::LibFunc::fabsl, llvm::LibFunc::ffs, llvm::LibFunc::ffsl, llvm::LibFunc::ffsll, llvm::LibFunc::fiprintf, llvm::LibFunc::floor, llvm::LibFunc::fmax, llvm::LibFunc::fmin, llvm::LibFunc::fprintf, llvm::LibFunc::fputc, llvm::LibFunc::fputs, FuncName, llvm::LibFunc::fwrite, llvm::CallInst::getCalledFunction(), llvm::CallInst::getCallingConv(), llvm::Function::getFnAttribute(), llvm::Value::getName(), llvm::Attribute::getValueAsString(), llvm::Function::hasFnAttribute(), ignoreCallingConv(), llvm::LibFunc::isascii, llvm::LibFunc::isdigit, llvm::CallInst::isNoBuiltin(), llvm::LibFunc::labs, llvm::LibFunc::llabs, llvm::LibFunc::log, llvm::LibFunc::log10, llvm::LibFunc::log1p, llvm::LibFunc::log2, llvm::LibFunc::logb, llvm::LibFunc::nearbyint, llvm::LibFunc::perror, llvm::Intrinsic::pow, llvm::LibFunc::pow, llvm::LibFunc::powf, llvm::LibFunc::powl, llvm::LibFunc::printf, llvm::LibFunc::puts, llvm::Value::replaceAllUsesWith(), llvm::LibFunc::rint, llvm::LibFunc::round, llvm::LibFunc::sin, llvm::LibFunc::sinh, llvm::LibFunc::sinpi, llvm::LibFunc::sinpif, llvm::LibFunc::sprintf, llvm::Intrinsic::sqrt, llvm::LibFunc::sqrt, llvm::LibFunc::sqrtf, llvm::LibFunc::sqrtl, llvm::LibFunc::tan, llvm::LibFunc::tanh, llvm::LibFunc::toascii, llvm::LibFunc::trunc, and llvm::LibFunc::vfprintf.
replaceAllUsesWith()
void LibCallSimplifier::replaceAllUsesWith (Instruction * I, Value * With) const virtual
replaceAllUsesWith - This method is used when the library call simplifier needs to replace instructions other than the library call being modified.
Definition at line 2099 of file SimplifyLibCalls.cpp.
References I.
The documentation for this class was generated from the following files:
SimplifyLibCalls.h
SimplifyLibCalls.cpp