LLVM: llvm::SequentialType Class Reference
LLVM API Documentation
llvm::SequentialType Class Reference
#include <DerivedTypes.h>
Public Member Functions
Type * getElementType () const
Public Member Functions inherited from llvm::CompositeType
Type * getTypeAtIndex (const Value *V)
Type * getTypeAtIndex (unsigned Idx)
bool indexValid (const Value *V) const
bool indexValid (unsigned Idx) const
Public Member Functions inherited from llvm::Type
void print (raw_ostream &O) const
void dump () const
LLVMContext & getContext () const
getContext - Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
bool isVoidTy () const
isVoidTy - Return true if this is 'void'.
bool isHalfTy () const
isHalfTy - Return true if this is 'half', a 16-bit IEEE fp type.
bool isFloatTy () const
isFloatTy - Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
isDoubleTy - Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
isX86_FP80Ty - Return true if this is x86 long double.
bool isFP128Ty () const
isFP128Ty - Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
isPPC_FP128Ty - Return true if this is powerpc long double.
bool isFloatingPointTy () const
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
isX86_MMXTy - Return true if this is X86 MMX.
bool isFPOrFPVectorTy () const
bool isLabelTy () const
isLabelTy - Return true if this is 'label'.
bool isMetadataTy () const
isMetadataTy - Return true if this is 'metadata'.
bool isIntegerTy () const
bool isIntegerTy (unsigned Bitwidth) const
isIntegerTy - Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
bool isFunctionTy () const
bool isStructTy () const
bool isArrayTy () const
bool isPointerTy () const
bool isPtrOrPtrVectorTy () const
bool isVectorTy () const
bool canLosslesslyBitCastTo (Type *Ty) const
Determine if this type could be losslessly bitcast to Ty.
bool isEmptyTy () const
bool isFirstClassType () const
bool isSingleValueType () const
bool isAggregateType () const
bool isSized (SmallPtrSetImpl< const Type * > *Visited=nullptr) const
unsigned getPrimitiveSizeInBits () const LLVM_READONLY
unsigned getScalarSizeInBits () const LLVM_READONLY
int getFPMantissaWidth () const
const Type * getScalarType () const LLVM_READONLY
Type * getScalarType () LLVM_READONLY
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
ArrayRef< Type * > subtypes () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
unsigned getNumContainedTypes () const
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
Type * getSequentialElementType () const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
unsigned getVectorNumElements () const
Type * getVectorElementType () const
Type * getPointerElementType () const
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0)
Static Public Member Functions
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::CompositeType
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Type
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
getPrimitiveType - Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static PointerType * getHalfPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getDoublePtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_FP80PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getPPC_FP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_MMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getIntNPtrTy (LLVMContext &C, unsigned N, unsigned AS=0)
static PointerType * getInt1PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt8PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt16PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt32PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt64PtrTy (LLVMContext &C, unsigned AS=0)
Protected Member Functions
SequentialType (TypeID TID, Type *ElType)
Protected Member Functions inherited from llvm::CompositeType
CompositeType (LLVMContext &C, TypeID tid)
Protected Member Functions inherited from llvm::Type
Type (LLVMContext &C, TypeID tid)
~Type ()
void setTypeID (TypeID ID)
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Additional Inherited Members
Public Types inherited from llvm::Type
enum TypeID {
VoidTyID = 0 , HalfTyID , FloatTyID , DoubleTyID ,
X86_FP80TyID , FP128TyID , PPC_FP128TyID , LabelTyID ,
MetadataTyID , X86_MMXTyID , IntegerTyID , FunctionTyID ,
StructTyID , ArrayTyID , PointerTyID , VectorTyID
}
typedef Type *const * subtype_iterator
typedef std::reverse_iterator< subtype_iterator > subtype_reverse_iterator
Protected Attributes inherited from llvm::Type
unsigned NumContainedTys
Type *const * ContainedTys
Detailed Description
SequentialType - This is the superclass of the array, pointer and vector type classes. All of these represent "arrays" in memory. The array type represents a specifically sized array, pointer types are unsized/unknown size arrays, vector types represent specifically sized arrays that allow for use of SIMD instructions. SequentialType holds the common features of all, which stem from the fact that all three lay their components out in memory identically.
Definition at line 309 of file DerivedTypes.h.
Constructor & Destructor Documentation
SequentialType()
llvm::SequentialType::SequentialType (TypeID TID, Type * ElType) inline protected
Definition at line 315 of file DerivedTypes.h.
References llvm::CompositeType::CompositeType(), llvm::Type::ContainedTys, llvm::Type::getContext(), and llvm::Type::NumContainedTys.
Member Function Documentation
classof()
bool llvm::SequentialType::classof (const Type * T) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 325 of file DerivedTypes.h.
References llvm::Type::ArrayTyID, llvm::Type::PointerTyID, T, and llvm::Type::VectorTyID.
getElementType()
Type * llvm::SequentialType::getElementType () const inline
Definition at line 322 of file DerivedTypes.h.
References llvm::Type::ContainedTys.
Referenced by appendToGlobalArray(), BitCastConstantVector(), computeKnownBits(), llvm::ConstantArray::ConstantArray(), llvm::ConstantFoldCastInstruction(), ConstantFoldGetElementPtrImpl(), ConstantFoldVectorCall(), llvm::ConstantVector::ConstantVector(), copyGlobalVariableProto(), llvm::GlobalAlias::create(), llvm::IRBuilderBase::CreateGCStatepoint(), llvm::IRBuilder< true, TargetFolder >::CreatePtrDiff(), emitGlobalConstantDataSequential(), emitGlobalConstantVector(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::ExecutionEngine::EmitGlobalVariable(), FindScalarElement(), fixupFPReturnAndCall(), FoldBitCast(), FoldReinterpretLoadFromConstPtr(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::AllocaInst::getAllocatedType(), llvm::VectorType::getBitWidth(), llvm::getConstantStringInfo(), llvm::ExecutionEngine::getConstantValue(), llvm::VectorType::getDoubleElementsVectorType(), llvm::ConstantDataSequential::getElementType(), llvm::EVT::getEVT(), llvm::VectorType::getExtendedElementVectorType(), llvm::VectorType::getHalfElementsVectorType(), GetHeapSROAValue(), getIndexedTypeInternal(), llvm::VectorType::getInteger(), llvm::getMallocAllocatedType(), getNaturalGEPWithOffset(), getOpenCLAlignment(), llvm::DataLayout::getPreferredAlignment(), llvm::NVPTXTargetLowering::getPrototype(), llvm::SparcTargetLowering::getSRetArgSize(), getStrideFromPointer(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::VectorType::getTruncatedElementVectorType(), llvm::DataLayout::getTypeSizeInBits(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::TargetLoweringBase::getValueType(), llvm::MVT::getVT(), HandleByValArgument(), HasPadding(), INITIALIZE_PASS(), isArray(), llvm::Type::isEmptyTy(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl(), isHomogeneousAggregate(), llvm::isImageOrSamplerVal(), isLeakCheckerRoot(), llvm::isSafeToLoadUnconditionally(), isStridedPtr(), llvm::ShuffleVectorInst::isValidOperands(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), isZero(), llvm::ExecutionEngine::LoadValueFromMemory(), llvm::NVPTXTargetLowering::LowerCall(), llvm::FastISel::lowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::FastISel::lowerCallTo(), llvm::FastISel::lowerCallTo(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), OptimizeGlobalAddressOfMalloc(), OptimizeIntegerToVectorInsertions(), OptimizeIntToFloatBitCast(), OptimizeVectorResize(), llvm::TargetLowering::ParseConstraints(), PerformHeapAllocSRoA(), llvm::TypePrinting::print(), llvm::AssemblyWriter::printGlobal(), llvm::AssemblyWriter::printInstruction(), SimplifyGEPInst(), StripPtrCastKeepAS(), TryToShrinkGlobalToBoolean(), upgradeGlobalArray(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::ObjectSizeOffsetVisitor::visitArgument(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::ObjectSizeOffsetVisitor::visitGlobalVariable(), llvm::InstCombiner::visitLandingPadInst(), WriteInstruction(), and WriteTypeTable().
The documentation for this class was generated from the following file:
DerivedTypes.h