LLVM: llvm::MMIAddrLabelMapCallbackPtr Class Reference
LLVM API Documentation
llvm::MMIAddrLabelMapCallbackPtr Class Reference
Public Member Functions
MMIAddrLabelMapCallbackPtr ()
MMIAddrLabelMapCallbackPtr (Value *V)
void setPtr (BasicBlock *BB)
void setMap (MMIAddrLabelMap *map)
void deleted () override
Callback for Value destruction.
void allUsesReplacedWith (Value *V2) override
Callback for Value RAUW.
Detailed Description
Definition at line 36 of file MachineModuleInfo.cpp.
Constructor & Destructor Documentation
MMIAddrLabelMapCallbackPtr() [1/2]
llvm::MMIAddrLabelMapCallbackPtr::MMIAddrLabelMapCallbackPtr () inline
Definition at line 39 of file MachineModuleInfo.cpp.
MMIAddrLabelMapCallbackPtr() [2/2]
llvm::MMIAddrLabelMapCallbackPtr::MMIAddrLabelMapCallbackPtr (Value * V) inline
Definition at line 40 of file MachineModuleInfo.cpp.
References llvm::CallbackVH::CallbackVH().
Member Function Documentation
allUsesReplacedWith()
void MMIAddrLabelMapCallbackPtr::allUsesReplacedWith (Value *) override virtual
Callback for Value RAUW.
Called when this->getValPtr()->replaceAllUsesWith(new_value) is called, before any of the uses have actually been replaced. If WeakVH were implemented as a CallbackVH, it would use this method to call setValPtr(new_value). AssertingVH would do nothing in this method.
Reimplemented from llvm::CallbackVH.
Definition at line 246 of file MachineModuleInfo.cpp.
References llvm::cast(), and llvm::ValueHandleBase::getValPtr().
deleted()
void MMIAddrLabelMapCallbackPtr::deleted () override virtual
Callback for Value destruction.
Called when this->getValPtr() is destroyed, inside ~Value(), so you may call any non-virtual Value method on getValPtr(), but no subclass methods. If WeakVH were implemented as a CallbackVH, it would use this method to call setValPtr(NULL). AssertingVH would use this method to cause an assertion failure.
All implementations must remove the reference from this object to the Value that's being destroyed.
Reimplemented from llvm::CallbackVH.
Definition at line 242 of file MachineModuleInfo.cpp.
References llvm::cast(), and llvm::ValueHandleBase::getValPtr().
setMap()
void llvm::MMIAddrLabelMapCallbackPtr::setMap (MMIAddrLabelMap * map) inline
Definition at line 46 of file MachineModuleInfo.cpp.
setPtr()
void llvm::MMIAddrLabelMapCallbackPtr::setPtr (BasicBlock * BB) inline
Definition at line 42 of file MachineModuleInfo.cpp.
References llvm::ValueHandleBase::operator=().
The documentation for this class was generated from the following file:
MachineModuleInfo.cpp