LLVM: llvm::sampleprof::SampleProfileReaderBinary Class Reference
LLVM API Documentation
llvm::sampleprof::SampleProfileReaderBinary Class Reference
#include <SampleProfReader.h>
Public Member Functions
SampleProfileReaderBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext &C)
std::error_code readHeader () override
Read and validate the file header.
std::error_code read () override
Read sample profiles from the associated file.
Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
SampleProfileReader (std::unique_ptr< MemoryBuffer > B, LLVMContext &C)
virtual ~SampleProfileReader ()
void dumpFunctionProfile (StringRef FName, raw_ostream &OS=dbgs())
Print the profile for FName on stream OS.
void dump (raw_ostream &OS=dbgs())
Print all the profiles on stream OS.
FunctionSamples * getSamplesFor (const Function &F)
Return the samples collected for function F.
StringMap< FunctionSamples > & getProfiles ()
Return all the profiles.
void reportParseError (int64_t LineNumber, Twine Msg) const
Report a parse error message.
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &Buffer)
Return true if Buffer is in the format supported by this class.
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (StringRef Filename, LLVMContext &C)
Create a sample profile reader appropriate to the file format.
Protected Member Functions
template<typename T>
ErrorOr< T > readNumber ()
Read a numeric value of type T from the profile.
ErrorOr< StringRef > readString ()
Read a string from the profile.
bool at_eof () const
Return true if we've reached the end of file.
Protected Attributes
const uint8_t * Data
Points to the current location in the buffer.
const uint8_t * End
Points to the end of the buffer.
Protected Attributes inherited from llvm::sampleprof::SampleProfileReader
StringMap< FunctionSamples > Profiles
Map every function to its associated profile.
LLVMContext & Ctx
LLVM context used to emit diagnostics.
std::unique_ptr< MemoryBuffer > Buffer
Memory buffer holding the profile file.
Detailed Description
Definition at line 125 of file SampleProfReader.h.
Constructor & Destructor Documentation
SampleProfileReaderBinary()
llvm::sampleprof::SampleProfileReaderBinary::SampleProfileReaderBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext & C) inline
Definition at line 127 of file SampleProfReader.h.
References Data, End, and llvm::sampleprof::SampleProfileReader::SampleProfileReader().
Member Function Documentation
at_eof()
bool llvm::sampleprof::SampleProfileReaderBinary::at_eof () const inline protected
Return true if we've reached the end of file.
Definition at line 157 of file SampleProfReader.h.
References Data, and End.
Referenced by read().
hasFormat()
bool SampleProfileReaderBinary::hasFormat (const MemoryBuffer & Buffer) static
Return true if Buffer is in the format supported by this class.
Definition at line 349 of file SampleProfReader.cpp.
References llvm::sampleprof::SampleProfileReader::Buffer, Data, llvm::decodeULEB128(), Magic, and llvm::sampleprof::SPMagic().
Referenced by llvm::sampleprof::SampleProfileReader::create().
read()
std::error_code SampleProfileReaderBinary::read () override virtual
Read sample profiles from the associated file.
Implements llvm::sampleprof::SampleProfileReader.
Definition at line 267 of file SampleProfReader.cpp.
References llvm::sampleprof::FunctionSamples::addBodySamples(), llvm::sampleprof::FunctionSamples::addCalledTargetSamples(), llvm::sampleprof::FunctionSamples::addHeadSamples(), llvm::sampleprof::FunctionSamples::addTotalSamples(), at_eof(), I, llvm::sampleprof::SampleProfileReader::Profiles, readNumber(), readString(), and llvm::success.
readHeader()
std::error_code SampleProfileReaderBinary::readHeader () override virtual
Read and validate the file header.
Implements llvm::sampleprof::SampleProfileReader.
Definition at line 328 of file SampleProfReader.cpp.
References llvm::bad_magic, llvm::sampleprof::SampleProfileReader::Buffer, Data, End, Magic, readNumber(), llvm::sampleprof::SPMagic(), llvm::sampleprof::SPVersion(), llvm::success, and llvm::unsupported_version.
readNumber()
template<typename T> ErrorOr< T > SampleProfileReaderBinary::readNumber () protected
Read a numeric value of type T from the profile.
If an error occurs during decoding, a diagnostic message is emitted and EC is set.
Returns
the read value.
Definition at line 233 of file SampleProfReader.cpp.
References Data, llvm::decodeULEB128(), End, llvm::malformed, llvm::sampleprof::SampleProfileReader::reportParseError(), llvm::success, and llvm::truncated.
Referenced by read(), and readHeader().
readString()
ErrorOr< StringRef > SampleProfileReaderBinary::readString () protected
Read a string from the profile.
If an error occurs during decoding, a diagnostic message is emitted and EC is set.
Returns
the read value.
Definition at line 254 of file SampleProfReader.cpp.
References Data, End, llvm::sampleprof::SampleProfileReader::reportParseError(), llvm::StringRef::size(), and llvm::truncated.
Referenced by read().
Member Data Documentation
Data
const uint8_t* llvm::sampleprof::SampleProfileReaderBinary::Data protected
Points to the current location in the buffer.
Definition at line 160 of file SampleProfReader.h.
Referenced by at_eof(), hasFormat(), readHeader(), readNumber(), readString(), and SampleProfileReaderBinary().
End
const uint8_t* llvm::sampleprof::SampleProfileReaderBinary::End protected
Points to the end of the buffer.
Definition at line 163 of file SampleProfReader.h.
Referenced by at_eof(), readHeader(), readNumber(), readString(), and SampleProfileReaderBinary().
The documentation for this class was generated from the following files:
SampleProfReader.h
SampleProfReader.cpp