LLVM: llvm::TrackingVH< ValueTy > Class Template Reference
LLVM API Documentation
llvm::TrackingVH< ValueTy > Class Template Reference
Value handle that tracks a Value across RAUW.
#include <ValueHandle.h>
Public Member Functions
TrackingVH ()
TrackingVH (ValueTy *P)
TrackingVH (const TrackingVH &RHS)
operator ValueTy * () const
ValueTy * operator= (ValueTy *RHS)
ValueTy * operator= (const TrackingVH< ValueTy > &RHS)
ValueTy * operator-> () const
ValueTy & operator* () const
Public Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (HandleBaseKind Kind)
ValueHandleBase (HandleBaseKind Kind, Value *V)
ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase &RHS)
~ValueHandleBase ()
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
Value * operator-> () const
Value & operator* () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::ValueHandleBase
static void ValueIsDeleted (Value *V)
static void ValueIsRAUWd (Value *Old, Value *New)
Protected Types inherited from llvm::ValueHandleBase
enum HandleBaseKind { Assert , Callback , Tracking , Weak }
This indicates what sub class the handle actually is.
Protected Member Functions inherited from llvm::ValueHandleBase
Value * getValPtr () const
Static Protected Member Functions inherited from llvm::ValueHandleBase
static bool isValid (Value *V)
Detailed Description
template<typename ValueTy>
class llvm::TrackingVH< ValueTy >
Value handle that tracks a Value across RAUW.
TrackingVH is designed for situations where a client needs to hold a handle to a Value (or subclass) across some operations which may move that value, but should never destroy it or replace it with some unacceptable type.
It is an error to do anything with a TrackingVH whose value has been destroyed, except to destruct it.
It is an error to attempt to replace a value with one of a type which is incompatible with any of its outstanding TrackingVHs.
Definition at line 278 of file ValueHandle.h.
Constructor & Destructor Documentation
TrackingVH() [1/3]
template<typename ValueTy> llvm::TrackingVH< ValueTy >::TrackingVH () inline
Definition at line 313 of file ValueHandle.h.
References llvm::ValueHandleBase::Tracking.
Referenced by operator=(), and TrackingVH().
TrackingVH() [2/3]
template<typename ValueTy> llvm::TrackingVH< ValueTy >::TrackingVH (ValueTy * P) inline
Definition at line 314 of file ValueHandle.h.
References P, and llvm::ValueHandleBase::Tracking.
TrackingVH() [3/3]
template<typename ValueTy> llvm::TrackingVH< ValueTy >::TrackingVH (const TrackingVH< ValueTy > & RHS) inline
Definition at line 315 of file ValueHandle.h.
References llvm::ValueHandleBase::Tracking, and TrackingVH().
Member Function Documentation
operator ValueTy *()
template<typename ValueTy> llvm::TrackingVH< ValueTy >::operator ValueTy * () const inline
Definition at line 317 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr().
operator*()
template<typename ValueTy> ValueTy & llvm::TrackingVH< ValueTy >::operator* () const inline
Definition at line 331 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr().
operator->()
template<typename ValueTy> ValueTy * llvm::TrackingVH< ValueTy >::operator-> () const inline
Definition at line 330 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr().
operator=() [1/2]
template<typename ValueTy> ValueTy * llvm::TrackingVH< ValueTy >::operator= (const TrackingVH< ValueTy > & RHS) inline
Definition at line 325 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr(), and TrackingVH().
operator=() [2/2]
template<typename ValueTy> ValueTy * llvm::TrackingVH< ValueTy >::operator= (ValueTy * RHS) inline
Definition at line 321 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr().
The documentation for this class was generated from the following file:
ValueHandle.h