LLVM: llvm::BitInit Class Reference
LLVM API Documentation
llvm::BitInit Class Reference
#include <Record.h>
Public Member Functions
bool getValue () const
Init * convertInitializerTo (RecTy *Ty) const override
Init * getBit (unsigned Bit) const override
std::string getAsString () const override
getAsString - Convert this value to a string form.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const
virtual Init * convertInitListSlice (const std::vector< unsigned > &Elements) const
virtual RecTy * getFieldType (const std::string &FieldName) const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * resolveReferences (Record &R, const RecordVal *RV) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static BitInit * get (bool V)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit , IK_FirstTypedInit , IK_BitsInit , IK_DagInit ,
IK_DefInit , IK_FieldInit , IK_IntInit , IK_ListInit ,
IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit , IK_UnOpInit ,
IK_LastOpInit , IK_StringInit , IK_VarInit , IK_VarListElementInit ,
IK_LastTypedInit , IK_UnsetInit , IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
BitInit - true/false - Represent a concrete initializer for a bit.
Definition at line 623 of file Record.h.
Member Function Documentation
classof()
bool llvm::BitInit::classof (const Init * I) inline static
Definition at line 632 of file Record.h.
References I, and llvm::Init::IK_BitInit.
convertInitializerTo()
Init * llvm::BitInit::convertInitializerTo (RecTy * Ty) const inline override virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 639 of file Record.h.
References llvm::RecTy::convertValue().
get()
BitInit * BitInit::get (bool V) static
Definition at line 453 of file Record.cpp.
Referenced by llvm::IntInit::convertInitializerBitRange(), llvm::BitRecTy::convertValue(), llvm::BitsRecTy::convertValue(), and llvm::IntInit::getBit().
getAsString()
std::string llvm::BitInit::getAsString () const inline override virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 648 of file Record.h.
getBit()
Init * llvm::BitInit::getBit (unsigned Bit) const inline override virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 643 of file Record.h.
getValue()
bool llvm::BitInit::getValue () const inline
Definition at line 637 of file Record.h.
Referenced by llvm::IntRecTy::convertValue().
The documentation for this class was generated from the following files:
Record.h
Record.cpp