LLVM: llvm::PackedVector< T, BitNum, BitVectorTy > Class Template Reference
LLVM API Documentation
llvm::PackedVector< T, BitNum, BitVectorTy > Class Template Reference
Store a vector of values using a specific number of bits for each value. Both signed and unsigned types can be used, e.g.
#include <PackedVector.h>
Classes
class reference
Public Member Functions
PackedVector ()
PackedVector (unsigned size)
bool empty () const
unsigned size () const
void clear ()
void resize (unsigned N)
void reserve (unsigned N)
PackedVector & reset ()
void push_back (T val)
reference operator[] (unsigned Idx)
T operator[] (unsigned Idx) const
bool operator== (const PackedVector &RHS) const
bool operator!= (const PackedVector &RHS) const
const PackedVector & operator= (const PackedVector &RHS)
PackedVector & operator|= (const PackedVector &RHS)
void swap (PackedVector &RHS)
Detailed Description
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector>
class llvm::PackedVector< T, BitNum, BitVectorTy >
Store a vector of values using a specific number of bits for each value. Both signed and unsigned types can be used, e.g.
PackedVector<signed, 2> vec;
will create a vector accepting values -2, -1, 0, 1. Any other value will hit an assertion.
Definition at line 75 of file PackedVector.h.
Constructor & Destructor Documentation
PackedVector() [1/2]
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> llvm::PackedVector< T, BitNum, BitVectorTy >::PackedVector () inline
Definition at line 99 of file PackedVector.h.
Referenced by operator!=(), operator=(), operator==(), operator|=(), llvm::PackedVector< T, BitNum, BitVectorTy >::reference::reference(), reset(), and swap().
PackedVector() [2/2]
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> llvm::PackedVector< T, BitNum, BitVectorTy >::PackedVector (unsigned size) inline explicit
Definition at line 100 of file PackedVector.h.
References size().
Member Function Documentation
clear()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> void llvm::PackedVector< T, BitNum, BitVectorTy >::clear () inline
Definition at line 106 of file PackedVector.h.
empty()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> bool llvm::PackedVector< T, BitNum, BitVectorTy >::empty () const inline
Definition at line 102 of file PackedVector.h.
operator!=()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> bool llvm::PackedVector< T, BitNum, BitVectorTy >::operator!= (const PackedVector< T, BitNum, BitVectorTy > & RHS) const inline
Definition at line 134 of file PackedVector.h.
References PackedVector().
operator=()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> const PackedVector & llvm::PackedVector< T, BitNum, BitVectorTy >::operator= (const PackedVector< T, BitNum, BitVectorTy > & RHS) inline
Definition at line 138 of file PackedVector.h.
References PackedVector().
operator==()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> bool llvm::PackedVector< T, BitNum, BitVectorTy >::operator== (const PackedVector< T, BitNum, BitVectorTy > & RHS) const inline
Definition at line 130 of file PackedVector.h.
References PackedVector().
operator[]() [1/2]
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> reference llvm::PackedVector< T, BitNum, BitVectorTy >::operator[] (unsigned Idx) inline
Definition at line 122 of file PackedVector.h.
operator[]() [2/2]
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> T llvm::PackedVector< T, BitNum, BitVectorTy >::operator[] (unsigned Idx) const inline
Definition at line 126 of file PackedVector.h.
References T.
operator|=()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> PackedVector & llvm::PackedVector< T, BitNum, BitVectorTy >::operator|= (const PackedVector< T, BitNum, BitVectorTy > & RHS) inline
Definition at line 143 of file PackedVector.h.
References PackedVector().
push_back()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> void llvm::PackedVector< T, BitNum, BitVectorTy >::push_back (T val) inline
Definition at line 117 of file PackedVector.h.
References resize(), size(), and T.
reserve()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> void llvm::PackedVector< T, BitNum, BitVectorTy >::reserve (unsigned N) inline
Definition at line 110 of file PackedVector.h.
References N.
reset()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> PackedVector & llvm::PackedVector< T, BitNum, BitVectorTy >::reset () inline
Definition at line 112 of file PackedVector.h.
References PackedVector(), and reset().
Referenced by reset().
resize()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> void llvm::PackedVector< T, BitNum, BitVectorTy >::resize (unsigned N) inline
Definition at line 108 of file PackedVector.h.
References N.
Referenced by push_back().
size()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> unsigned llvm::PackedVector< T, BitNum, BitVectorTy >::size () const inline
Definition at line 104 of file PackedVector.h.
Referenced by PackedVector(), and push_back().
swap()
template<typename T, unsigned BitNum, typename BitVectorTy = BitVector> void llvm::PackedVector< T, BitNum, BitVectorTy >::swap (PackedVector< T, BitNum, BitVectorTy > & RHS) inline
Definition at line 148 of file PackedVector.h.
References PackedVector().
The documentation for this class was generated from the following file:
PackedVector.h