LLVM: llvm::XCoreFunctionInfo Class Reference
LLVM API Documentation
llvm::XCoreFunctionInfo Class Reference
#include <XCoreMachineFunctionInfo.h>
Public Member Functions
XCoreFunctionInfo ()
XCoreFunctionInfo (MachineFunction &MF)
~XCoreFunctionInfo ()
void setVarArgsFrameIndex (int off)
int getVarArgsFrameIndex () const
int createLRSpillSlot (MachineFunction &MF)
bool hasLRSpillSlot ()
int getLRSpillSlot () const
int createFPSpillSlot (MachineFunction &MF)
bool hasFPSpillSlot ()
int getFPSpillSlot () const
const int * createEHSpillSlot (MachineFunction &MF)
bool hasEHSpillSlot ()
const int * getEHSpillSlot () const
void setReturnStackOffset (unsigned value)
unsigned getReturnStackOffset () const
bool isLargeFrame (const MachineFunction &MF) const
std::vector< std::pair< MachineBasicBlock::iterator, CalleeSavedInfo > > & getSpillLabels ()
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty>
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
XCoreFunctionInfo - This class is derived from MachineFunction private XCore target-specific information for each MachineFunction.
Definition at line 28 of file XCoreMachineFunctionInfo.h.
Constructor & Destructor Documentation
XCoreFunctionInfo() [1/2]
llvm::XCoreFunctionInfo::XCoreFunctionInfo () inline
Definition at line 44 of file XCoreMachineFunctionInfo.h.
XCoreFunctionInfo() [2/2]
llvm::XCoreFunctionInfo::XCoreFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 52 of file XCoreMachineFunctionInfo.h.
~XCoreFunctionInfo()
llvm::XCoreFunctionInfo::~XCoreFunctionInfo () inline
Definition at line 60 of file XCoreMachineFunctionInfo.h.
Member Function Documentation
createEHSpillSlot()
const int * XCoreFunctionInfo::createEHSpillSlot (MachineFunction & MF)
Definition at line 61 of file XCoreMachineFunctionInfo.cpp.
References llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), and llvm::TargetRegisterClass::getSize().
Referenced by llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan().
createFPSpillSlot()
int XCoreFunctionInfo::createFPSpillSlot (MachineFunction & MF)
Definition at line 50 of file XCoreMachineFunctionInfo.cpp.
References llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), and llvm::TargetRegisterClass::getSize().
Referenced by llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan().
createLRSpillSlot()
int XCoreFunctionInfo::createLRSpillSlot (MachineFunction & MF)
Definition at line 34 of file XCoreMachineFunctionInfo.cpp.
References llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::TargetRegisterClass::getSize(), and llvm::Function::isVarArg().
Referenced by llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan().
getEHSpillSlot()
const int * llvm::XCoreFunctionInfo::getEHSpillSlot () const inline
Definition at line 81 of file XCoreMachineFunctionInfo.h.
Referenced by GetEHSpillList().
getFPSpillSlot()
int llvm::XCoreFunctionInfo::getFPSpillSlot () const inline
Definition at line 74 of file XCoreMachineFunctionInfo.h.
Referenced by GetSpillList().
getLRSpillSlot()
int llvm::XCoreFunctionInfo::getLRSpillSlot () const inline
Definition at line 67 of file XCoreMachineFunctionInfo.h.
Referenced by llvm::XCoreFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitPrologue(), and GetSpillList().
getReturnStackOffset()
unsigned llvm::XCoreFunctionInfo::getReturnStackOffset () const inline
Definition at line 92 of file XCoreMachineFunctionInfo.h.
getSpillLabels()
std::vector< std::pair< MachineBasicBlock::iterator, CalleeSavedInfo > > & llvm::XCoreFunctionInfo::getSpillLabels () inline
Definition at line 100 of file XCoreMachineFunctionInfo.h.
Referenced by llvm::XCoreFrameLowering::emitPrologue(), and llvm::XCoreFrameLowering::spillCalleeSavedRegisters().
getVarArgsFrameIndex()
int llvm::XCoreFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 63 of file XCoreMachineFunctionInfo.h.
hasEHSpillSlot()
bool llvm::XCoreFunctionInfo::hasEHSpillSlot () inline
Definition at line 80 of file XCoreMachineFunctionInfo.h.
Referenced by llvm::XCoreFrameLowering::emitPrologue(), and GetEHSpillList().
hasFPSpillSlot()
bool llvm::XCoreFunctionInfo::hasFPSpillSlot () inline
Definition at line 73 of file XCoreMachineFunctionInfo.h.
hasLRSpillSlot()
bool llvm::XCoreFunctionInfo::hasLRSpillSlot () inline
Definition at line 66 of file XCoreMachineFunctionInfo.h.
Referenced by llvm::XCoreFrameLowering::emitEpilogue(), and llvm::XCoreFrameLowering::emitPrologue().
isLargeFrame()
bool XCoreFunctionInfo::isLargeFrame (const MachineFunction & MF) const
Definition at line 18 of file XCoreMachineFunctionInfo.cpp.
References llvm::MachineFrameInfo::estimateStackSize(), and llvm::MachineFunction::getFrameInfo().
Referenced by llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized().
setReturnStackOffset()
void llvm::XCoreFunctionInfo::setReturnStackOffset (unsigned value) inline
Definition at line 86 of file XCoreMachineFunctionInfo.h.
setVarArgsFrameIndex()
void llvm::XCoreFunctionInfo::setVarArgsFrameIndex (int off) inline
Definition at line 62 of file XCoreMachineFunctionInfo.h.
The documentation for this class was generated from the following files:
XCoreMachineFunctionInfo.h
XCoreMachineFunctionInfo.cpp