LLVM: llvm::Regex Class Reference
LLVM API Documentation
llvm::Regex Class Reference
#include <Regex.h>
Public Types
enum { NoFlags =0 , IgnoreCase =1 , Newline =2 , BasicRegex =4 }
Public Member Functions
Regex (StringRef Regex, unsigned Flags=NoFlags)
Compiles the given regular expression Regex.
Regex (const Regex &) LLVM_DELETED_FUNCTION
Regex & operator= (Regex regex)
Regex (Regex &&regex)
~Regex ()
bool isValid (std::string &Error)
unsigned getNumMatches () const
bool match (StringRef String, SmallVectorImpl< StringRef > *Matches=nullptr)
std::string sub (StringRef Repl, StringRef String, std::string *Error=nullptr)
Static Public Member Functions
static bool isLiteralERE (StringRef Str)
If this function returns true, ^Str$ is an extended regular expression that matches Str and only Str.
static std::string escape (StringRef String)
Turn String into a regex by escaping its special characters.
Detailed Description
Definition at line 29 of file Regex.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NoFlags
IgnoreCase
Compile for matching that ignores upper/lower case distinctions.
Newline
Compile for newline-sensitive matching. With this flag '[^' bracket expressions and '.' never match newline. A ^ anchor matches the null string after any newline in the string in addition to its normal function, and the $ anchor matches the null string before any newline in the string in addition to its normal function.
BasicRegex
By default, the POSIX extended regular expression (ERE) syntax is assumed. Pass this flag to turn on basic regular expressions (BRE) instead.
Definition at line 31 of file Regex.h.
Constructor & Destructor Documentation
Regex() [1/3]
Regex::Regex (StringRef Regex, unsigned Flags = NoFlags)
Compiles the given regular expression Regex.
Definition at line 22 of file Regex.cpp.
References BasicRegex, llvm::StringRef::data(), llvm::StringRef::end(), IgnoreCase, llvm_regcomp(), Newline, REG_EXTENDED, REG_ICASE, REG_NEWLINE, and REG_PEND.
Referenced by operator=(), Regex(), and Regex().
Regex() [2/3]
llvm::Regex::Regex (const Regex &)
References LLVM_DELETED_FUNCTION, and Regex().
Regex() [3/3]
llvm::Regex::Regex (Regex && regex) inline
Definition at line 55 of file Regex.h.
References Regex().
~Regex()
Regex::~Regex ()
Definition at line 35 of file Regex.cpp.
References llvm_regfree().
Member Function Documentation
escape()
std::string Regex::escape (StringRef String) static
Turn String into a regex by escaping its special characters.
Definition at line 184 of file Regex.cpp.
References RegexMetachars.
getNumMatches()
unsigned Regex::getNumMatches () const
getNumMatches - In a valid regex, return the number of parenthesized matches it contains. The number filled in by match will include this many entries plus one for the whole regex (as element 0).
getNumMatches - In a valid regex, return the number of parenthesized matches it contains.
Definition at line 55 of file Regex.cpp.
isLiteralERE()
bool Regex::isLiteralERE (StringRef Str) static
If this function returns true, ^Str$ is an extended regular expression that matches Str and only Str.
Definition at line 177 of file Regex.cpp.
References llvm::StringRef::find_first_of(), llvm::StringRef::npos, and RegexMetachars.
isValid()
bool Regex::isValid (std::string & Error)
isValid - returns the error encountered during regex compilation, or matching, if any.
Definition at line 42 of file Regex.cpp.
References Error(), and llvm_regerror().
match()
bool Regex::match (StringRef String, SmallVectorImpl< StringRef > * Matches = nullptr)
matches - Match the regex against a given String.
Parameters
Matches - If given, on a successful match this will be filled in with references to the matched group expressions (inside String), the first group is always the entire pattern.
This returns true on a successful match.
Definition at line 59 of file Regex.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm_regexec(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), REG_NOMATCH, REG_STARTEND, and llvm::SmallVectorImpl< T >::resize().
Referenced by llvm::AArch64SysReg::SysRegMapper::fromString(), llvm::yaml::isNumber(), llvm::sampleprof::SampleProfileReaderText::read(), and sub().
operator=()
Regex & llvm::Regex::operator= (Regex regex) inline
Definition at line 50 of file Regex.h.
References Regex(), and std::swap().
sub()
std::string Regex::sub (StringRef Repl, StringRef String, std::string * Error = nullptr)
sub - Return the result of replacing the first match of the regex in String with the Repl string. Backreferences like "\0" in the replacement string are replaced with the appropriate match substring.
Note that the replacement string has backslash escaping performed on it. Invalid backreferences are ignored (replaced by empty strings).
Parameters
Error If non-null, any errors in the substitution (invalid backreferences, trailing backslashes) will be recorded as a non-empty string.
Definition at line 98 of file Regex.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::StringRef::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), Error(), llvm::StringRef::find_first_not_of(), llvm::StringRef::getAsInteger(), match(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::StringRef::size(), llvm::StringRef::slice(), Split(), llvm::StringRef::split(), llvm::StringRef::str(), and llvm::StringRef::substr().
Referenced by llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator >::performOnModule(), and llvm::sampleprof::SampleProfileReaderText::read().
The documentation for this class was generated from the following files:
Regex.h
Regex.cpp