LLVM: llvm::DominanceFrontier Class Reference
LLVM API Documentation
llvm::DominanceFrontier Class Reference
#include <DominanceFrontier.h>
Public Types
typedef DominatorTreeBase< BasicBlock > DomTreeT
typedef DomTreeNodeBase< BasicBlock > DomTreeNodeT
typedef DominanceFrontierBase< BasicBlock >::DomSetType DomSetType
typedef DominanceFrontierBase< BasicBlock >::iterator iterator
typedef DominanceFrontierBase< BasicBlock >::const_iterator const_iterator
Public Member Functions
DominanceFrontier ()
ForwardDominanceFrontierBase< BasicBlock > & getBase ()
const std::vector< BasicBlock * > & getRoots () const
BasicBlock * getRoot () const
bool isPostDominator () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator find (BasicBlock *B)
const_iterator find (BasicBlock *B) const
iterator addBasicBlock (BasicBlock *BB, const DomSetType &frontier)
void removeBlock (BasicBlock *BB)
void addToFrontier (iterator I, BasicBlock *Node)
void removeFromFrontier (iterator I, BasicBlock *Node)
bool compareDomSet (DomSetType &DS1, const DomSetType &DS2) const
bool compare (DominanceFrontierBase< BasicBlock > &Other) const
void releaseMemory () override
bool runOnFunction (Function &) override
void getAnalysisUsage (AnalysisUsage &AU) const override
void print (raw_ostream &OS, const Module *=nullptr) const override
void dump () const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 136 of file DominanceFrontier.h.
Member Typedef Documentation
const_iterator
typedef DominanceFrontierBase<BasicBlock>::const_iterator llvm::DominanceFrontier::const_iterator
Definition at line 144 of file DominanceFrontier.h.
DomSetType
typedef DominanceFrontierBase<BasicBlock>::DomSetType llvm::DominanceFrontier::DomSetType
Definition at line 142 of file DominanceFrontier.h.
DomTreeNodeT
typedef DomTreeNodeBase<BasicBlock> llvm::DominanceFrontier::DomTreeNodeT
Definition at line 141 of file DominanceFrontier.h.
DomTreeT
typedef DominatorTreeBase<BasicBlock> llvm::DominanceFrontier::DomTreeT
Definition at line 140 of file DominanceFrontier.h.
iterator
typedef DominanceFrontierBase<BasicBlock>::iterator llvm::DominanceFrontier::iterator
Definition at line 143 of file DominanceFrontier.h.
Constructor & Destructor Documentation
DominanceFrontier()
Dominance Frontier true DominanceFrontier::DominanceFrontier ()
Definition at line 28 of file DominanceFrontier.cpp.
References DominanceFrontier(), llvm::FunctionPass::FunctionPass(), llvm::PassRegistry::getPassRegistry(), ID, and llvm::initializeDominanceFrontierPass().
Referenced by DominanceFrontier().
Member Function Documentation
addBasicBlock()
iterator llvm::DominanceFrontier::addBasicBlock (BasicBlock * BB, const DomSetType & frontier) inline
Definition at line 172 of file DominanceFrontier.h.
addToFrontier()
void llvm::DominanceFrontier::addToFrontier (iterator I, BasicBlock * Node) inline
Definition at line 178 of file DominanceFrontier.h.
References I.
begin() [1/2]
iterator llvm::DominanceFrontier::begin () inline
Definition at line 160 of file DominanceFrontier.h.
begin() [2/2]
const_iterator llvm::DominanceFrontier::begin () const inline
Definition at line 162 of file DominanceFrontier.h.
compare()
bool llvm::DominanceFrontier::compare (DominanceFrontierBase< BasicBlock > & Other) const inline
Definition at line 190 of file DominanceFrontier.h.
compareDomSet()
bool llvm::DominanceFrontier::compareDomSet (DomSetType & DS1, const DomSetType & DS2) const inline
Definition at line 186 of file DominanceFrontier.h.
dump()
void DominanceFrontier::dump () const
Definition at line 54 of file DominanceFrontier.cpp.
References llvm::dbgs(), and print().
end() [1/2]
iterator llvm::DominanceFrontier::end () inline
Definition at line 164 of file DominanceFrontier.h.
end() [2/2]
const_iterator llvm::DominanceFrontier::end () const inline
Definition at line 166 of file DominanceFrontier.h.
find() [1/2]
iterator llvm::DominanceFrontier::find (BasicBlock * B) inline
Definition at line 168 of file DominanceFrontier.h.
find() [2/2]
const_iterator llvm::DominanceFrontier::find (BasicBlock * B) const inline
Definition at line 170 of file DominanceFrontier.h.
getAnalysisUsage()
void DominanceFrontier::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 44 of file DominanceFrontier.cpp.
References llvm::AnalysisUsage::addRequired(), and llvm::AnalysisUsage::setPreservesAll().
getBase()
ForwardDominanceFrontierBase< BasicBlock > & llvm::DominanceFrontier::getBase () inline
Definition at line 150 of file DominanceFrontier.h.
getRoot()
BasicBlock * llvm::DominanceFrontier::getRoot () const inline
Definition at line 156 of file DominanceFrontier.h.
getRoots()
const std::vector< BasicBlock * > & llvm::DominanceFrontier::getRoots () const inline
Definition at line 152 of file DominanceFrontier.h.
isPostDominator()
bool llvm::DominanceFrontier::isPostDominator () const inline
Definition at line 158 of file DominanceFrontier.h.
print()
void DominanceFrontier::print (raw_ostream & O, const Module * M = nullptr) const override virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 49 of file DominanceFrontier.cpp.
References llvm::DominatorTreeWrapperPass::print().
Referenced by dump(), llvm::MachineRegionInfoPass::print(), and llvm::RegionInfoPass::print().
releaseMemory()
void DominanceFrontier::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 34 of file DominanceFrontier.cpp.
Referenced by runOnFunction().
removeBlock()
void llvm::DominanceFrontier::removeBlock (BasicBlock * BB) inline
Definition at line 176 of file DominanceFrontier.h.
removeFromFrontier()
void llvm::DominanceFrontier::removeFromFrontier (iterator I, BasicBlock * Node) inline
Definition at line 182 of file DominanceFrontier.h.
References I.
runOnFunction()
bool DominanceFrontier::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 38 of file DominanceFrontier.cpp.
References llvm::Pass::getAnalysis(), and releaseMemory().
Member Data Documentation
ID
char DominanceFrontier::ID = 0 static
Definition at line 146 of file DominanceFrontier.h.
Referenced by DominanceFrontier().
The documentation for this class was generated from the following files:
DominanceFrontier.h
DominanceFrontier.cpp