LLVM: llvm::ScheduleDAGMI Class Reference
LLVM API Documentation
llvm::ScheduleDAGMI Class Reference
#include <MachineScheduler.h>
Public Member Functions
ScheduleDAGMI (MachineSchedContext *C, std::unique_ptr< MachineSchedStrategy > S, bool IsPostRA)
~ScheduleDAGMI () override
virtual bool hasVRegLiveness () const
Return true if this DAG supports VReg liveness and RegPressure.
void addMutation (std::unique_ptr< ScheduleDAGMutation > Mutation)
bool canAddEdge (SUnit *SuccSU, SUnit *PredSU)
True if an edge can be added from PredSU to SuccSU without creating a cycle.
bool addEdge (SUnit *SuccSU, const SDep &PredDep)
Add a DAG edge to the given SU with the given predecessor dependence data.
MachineBasicBlock::iterator top () const
MachineBasicBlock::iterator bottom () const
void enterRegion (MachineBasicBlock *bb, MachineBasicBlock::iterator begin, MachineBasicBlock::iterator end, unsigned regioninstrs) override
void schedule () override
void moveInstruction (MachineInstr *MI, MachineBasicBlock::iterator InsertPos)
const SUnit * getNextClusterPred () const
const SUnit * getNextClusterSucc () const
void viewGraph (const Twine &Name, const Twine &Title) override
void viewGraph () override
Out-of-line implementation with no arguments is handy for gdb.
Public Member Functions inherited from llvm::ScheduleDAGInstrs
ScheduleDAGInstrs (MachineFunction &mf, const MachineLoopInfo *mli, bool IsPostRAFlag, bool RemoveKillFlags=false, LiveIntervals *LIS=nullptr)
virtual ~ScheduleDAGInstrs ()
bool isPostRA () const
LiveIntervals * getLIS () const
Expose LiveIntervals for use in DAG mutators and such.
const TargetSchedModel * getSchedModel () const
Get the machine model for instruction scheduling.
const MCSchedClassDesc * getSchedClass (SUnit *SU) const
Resolve and cache a resolved scheduling class for an SUnit.
MachineBasicBlock::iterator begin () const
begin - Return an iterator to the top of the current scheduling region.
MachineBasicBlock::iterator end () const
end - Return an iterator to the bottom of the current scheduling region.
SUnit * newSUnit (MachineInstr *MI)
newSUnit - Creates a new SUnit and return a ptr to it.
SUnit * getSUnit (MachineInstr *MI) const
getSUnit - Return an existing SUnit for this MI, or NULL.
virtual void startBlock (MachineBasicBlock *BB)
startBlock - Prepare to perform scheduling in the given block.
virtual void finishBlock ()
finishBlock - Clean up after scheduling in the given block.
virtual void exitRegion ()
Notify that the scheduler has finished scheduling the current region.
void buildSchedGraph (AliasAnalysis *AA, RegPressureTracker *RPTracker=nullptr, PressureDiffs *PDiffs=nullptr)
void addSchedBarrierDeps ()
virtual void finalizeSchedule ()
void dumpNode (const SUnit *SU) const override
std::string getGraphNodeLabel (const SUnit *SU) const override
Return a label for a DAG node that points to an instruction.
std::string getDAGName () const override
Return a label for the region of code covered by the DAG.
void fixupKills (MachineBasicBlock *MBB)
Fix register kill flags that scheduling has made invalid.
Public Member Functions inherited from llvm::ScheduleDAG
ScheduleDAG (MachineFunction &mf)
virtual ~ScheduleDAG ()
void clearDAG ()
clearDAG - clear the DAG state (between regions).
const MCInstrDesc * getInstrDesc (const SUnit *SU) const
virtual void addCustomGraphFeatures (GraphWriter< ScheduleDAG * > &) const
unsigned VerifyScheduledDAG (bool isBottomUp)
Protected Member Functions
void postprocessDAG ()
Apply each ScheduleDAGMutation step in order.
void initQueues (ArrayRef< SUnit * > TopRoots, ArrayRef< SUnit * > BotRoots)
Release ExitSU predecessors and setup scheduler queues.
void updateQueues (SUnit *SU, bool IsTopNode)
Update scheduler DAG and queues after scheduling an instruction.
void placeDebugValues ()
Reinsert debug_values recorded in ScheduleDAGInstrs::DbgValues.
void dumpSchedule () const
dump the scheduled Sequence.
bool checkSchedLimit ()
void findRootsAndBiasEdges (SmallVectorImpl< SUnit * > &TopRoots, SmallVectorImpl< SUnit * > &BotRoots)
void releaseSucc (SUnit *SU, SDep *SuccEdge)
void releaseSuccessors (SUnit *SU)
releaseSuccessors - Call releaseSucc on each of SU's successors.
void releasePred (SUnit *SU, SDep *PredEdge)
void releasePredecessors (SUnit *SU)
releasePredecessors - Call releasePred on each of SU's predecessors.
Protected Member Functions inherited from llvm::ScheduleDAGInstrs
void initSUnits ()
void addPhysRegDataDeps (SUnit *SU, unsigned OperIdx)
void addPhysRegDeps (SUnit *SU, unsigned OperIdx)
void addVRegDefDeps (SUnit *SU, unsigned OperIdx)
void addVRegUseDeps (SUnit *SU, unsigned OperIdx)
void startBlockForKills (MachineBasicBlock *BB)
PostRA helper for rewriting kill flags.
bool toggleKillFlag (MachineInstr *MI, MachineOperand &MO)
Toggle a register operand kill flag.
Protected Attributes
AliasAnalysis * AA
std::unique_ptr< MachineSchedStrategy > SchedImpl
ScheduleDAGTopologicalSort Topo
std::vector< std::unique_ptr< ScheduleDAGMutation > > Mutations
Ordered list of DAG postprocessing steps.
MachineBasicBlock::iterator CurrentTop
The top of the unscheduled zone.
MachineBasicBlock::iterator CurrentBottom
The bottom of the unscheduled zone.
const SUnit * NextClusterPred
Record the next node in a scheduled cluster.
const SUnit * NextClusterSucc
unsigned NumInstrsScheduled
Protected Attributes inherited from llvm::ScheduleDAGInstrs
const MachineLoopInfo * MLI
const MachineFrameInfo * MFI
LiveIntervals * LIS
Live Intervals provides reaching defs in preRA scheduling.
TargetSchedModel SchedModel
TargetSchedModel provides an interface to the machine model.
bool IsPostRA
isPostRA flag indicates vregs cannot be present.
bool RemoveKillFlags
bool CanHandleTerminators
MachineBasicBlock * BB
The block in which to insert instructions.
MachineBasicBlock::iterator RegionBegin
The beginning of the range to be scheduled.
MachineBasicBlock::iterator RegionEnd
The end of the range to be scheduled.
unsigned NumRegionInstrs
Instructions in this region (distance(RegionBegin, RegionEnd)).
DenseMap< MachineInstr *, SUnit * > MISUnitMap
VReg2UseMap VRegUses
Reg2SUnitsMap Defs
Reg2SUnitsMap Uses
VReg2SUnitMap VRegDefs
Track the last instruction in this region defining each virtual register.
std::vector< SUnit * > PendingLoads
DbgValueVector DbgValues
MachineInstr * FirstDbgValue
BitVector LiveRegs
Set of live physical registers for updating kill flags.
Additional Inherited Members
Public Attributes inherited from llvm::ScheduleDAG
const TargetMachine & TM
const TargetInstrInfo * TII
const TargetRegisterInfo * TRI
MachineFunction & MF
MachineRegisterInfo & MRI
std::vector< SUnit > SUnits
SUnit EntrySU
SUnit ExitSU
bool StressSched
Protected Types inherited from llvm::ScheduleDAGInstrs
typedef std::vector< std::pair< MachineInstr *, MachineInstr * > > DbgValueVector
Detailed Description
ScheduleDAGMI is an implementation of ScheduleDAGInstrs that simply schedules machine instructions according to the given MachineSchedStrategy without much extra book-keeping. This is the common functionality between PreRA and PostRA MachineScheduler.
Definition at line 222 of file MachineScheduler.h.
Constructor & Destructor Documentation
ScheduleDAGMI()
llvm::ScheduleDAGMI::ScheduleDAGMI (MachineSchedContext * C, std::unique_ptr< MachineSchedStrategy > S, bool IsPostRA) inline
Definition at line 250 of file MachineScheduler.h.
References AA, CurrentBottom, CurrentTop, llvm::ScheduleDAG::ExitSU, llvm::ScheduleDAGInstrs::IsPostRA, llvm::ScheduleDAGInstrs::LIS, llvm::ScheduleDAG::MF, llvm::ScheduleDAGInstrs::MLI, NextClusterPred, NextClusterSucc, NumInstrsScheduled, SchedImpl, llvm::ScheduleDAGInstrs::ScheduleDAGInstrs(), llvm::ScheduleDAG::SUnits, and Topo.
Referenced by llvm::ScheduleDAGMILive::ScheduleDAGMILive().
~ScheduleDAGMI()
ScheduleDAGMI::~ScheduleDAGMI () override
Definition at line 506 of file MachineScheduler.cpp.
Member Function Documentation
addEdge()
bool ScheduleDAGMI::addEdge (SUnit * SuccSU, const SDep & PredDep)
Add a DAG edge to the given SU with the given predecessor dependence data.
Returns
true if the edge may be added without creating a cycle OR if an equivalent edge already existed (false indicates failure).
Definition at line 513 of file MachineScheduler.cpp.
References llvm::SUnit::addPred(), llvm::ScheduleDAG::ExitSU, llvm::SDep::getSUnit(), llvm::SDep::isArtificial(), and Topo.
addMutation()
void llvm::ScheduleDAGMI::addMutation (std::unique_ptr< ScheduleDAGMutation > Mutation) inline
Add a postprocessing step to the DAG builder. Mutations are applied in the order that they are added after normal DAG building and before MachineSchedStrategy initialization.
ScheduleDAGMI takes ownership of the Mutation object.
Definition at line 272 of file MachineScheduler.h.
References Mutation, and Mutations.
Referenced by createGenericSchedLive().
bottom()
MachineBasicBlock::iterator llvm::ScheduleDAGMI::bottom () const inline
Definition at line 288 of file MachineScheduler.h.
References CurrentBottom.
canAddEdge()
bool ScheduleDAGMI::canAddEdge (SUnit * SuccSU, SUnit * PredSU)
True if an edge can be added from PredSU to SuccSU without creating a cycle.
Definition at line 509 of file MachineScheduler.cpp.
References llvm::ScheduleDAG::ExitSU, and Topo.
checkSchedLimit()
bool ScheduleDAGMI::checkSchedLimit () protected
Definition at line 638 of file MachineScheduler.cpp.
References CurrentBottom, CurrentTop, MISchedCutoff, and NumInstrsScheduled.
Referenced by schedule(), llvm::ScheduleDAGMILive::schedule(), and llvm::VLIWMachineScheduler::schedule().
dumpSchedule()
void ScheduleDAGMI::dumpSchedule () const protected
dump the scheduled Sequence.
Definition at line 816 of file MachineScheduler.cpp.
References llvm::ScheduleDAGInstrs::begin(), llvm::dbgs(), llvm::ScheduleDAGInstrs::end(), and llvm::ScheduleDAGInstrs::getSUnit().
Referenced by schedule(), and llvm::ScheduleDAGMILive::schedule().
enterRegion()
void ScheduleDAGMI::enterRegion (MachineBasicBlock * bb, MachineBasicBlock::iterator begin, MachineBasicBlock::iterator end, unsigned regioninstrs) override virtual
Implement the ScheduleDAGInstrs interface for handling the next scheduling region. This covers all instructions in a block, while schedule() may only cover a subset.
enterRegion - Called back from MachineScheduler::runOnMachineFunction after crossing a scheduling boundary. [begin, end) includes all instructions in the region, including the boundary itself and single-instruction regions that don't get scheduled.
Reimplemented from llvm::ScheduleDAGInstrs.
Reimplemented in llvm::ScheduleDAGMILive.
Definition at line 608 of file MachineScheduler.cpp.
References llvm::ScheduleDAGInstrs::begin(), llvm::ScheduleDAGInstrs::end(), llvm::ScheduleDAGInstrs::enterRegion(), and SchedImpl.
Referenced by llvm::ScheduleDAGMILive::enterRegion().
findRootsAndBiasEdges()
void ScheduleDAGMI::findRootsAndBiasEdges (SmallVectorImpl< SUnit * > & TopRoots, SmallVectorImpl< SUnit * > & BotRoots) protected
Definition at line 729 of file MachineScheduler.cpp.
References llvm::SUnit::biasCriticalPath(), llvm::ScheduleDAG::ExitSU, I, llvm::SUnit::isBoundaryNode(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::ScheduleDAG::SUnits.
Referenced by schedule(), llvm::ScheduleDAGMILive::schedule(), and llvm::VLIWMachineScheduler::schedule().
getNextClusterPred()
const SUnit * llvm::ScheduleDAGMI::getNextClusterPred () const inline
Definition at line 306 of file MachineScheduler.h.
References NextClusterPred.
getNextClusterSucc()
const SUnit * llvm::ScheduleDAGMI::getNextClusterSucc () const inline
Definition at line 308 of file MachineScheduler.h.
References NextClusterSucc.
hasVRegLiveness()
virtual bool llvm::ScheduleDAGMI::hasVRegLiveness () const inline virtual
Return true if this DAG supports VReg liveness and RegPressure.
Reimplemented in llvm::ScheduleDAGMILive.
Definition at line 265 of file MachineScheduler.h.
Referenced by llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeAttributes(), llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeLabel(), llvm::GenericScheduler::initialize(), and llvm::R600SchedStrategy::initialize().
initQueues()
void ScheduleDAGMI::initQueues (ArrayRef< SUnit * > TopRoots, ArrayRef< SUnit * > BotRoots) protected
Release ExitSU predecessors and setup scheduler queues.
Identify DAG roots and setup scheduler queues.
Definition at line 751 of file MachineScheduler.cpp.
References llvm::ArrayRef< T >::begin(), CurrentBottom, CurrentTop, llvm::ArrayRef< T >::end(), llvm::ScheduleDAG::EntrySU, llvm::ScheduleDAG::ExitSU, I, NextClusterPred, NextClusterSucc, nextIfDebug(), llvm::ArrayRef< T >::rbegin(), llvm::ScheduleDAGInstrs::RegionBegin, llvm::ScheduleDAGInstrs::RegionEnd, releasePredecessors(), releaseSuccessors(), llvm::ArrayRef< T >::rend(), and SchedImpl.
Referenced by schedule(), llvm::ScheduleDAGMILive::schedule(), and llvm::VLIWMachineScheduler::schedule().
moveInstruction()
void ScheduleDAGMI::moveInstruction (MachineInstr * MI, MachineBasicBlock::iterator InsertPos)
Change the position of an instruction within the basic block and update live ranges and region boundary iterators.
This is normally called from the main scheduler loop but may also be invoked by the scheduling strategy to perform additional code motion.
Definition at line 620 of file MachineScheduler.cpp.
References llvm::ScheduleDAGInstrs::BB, llvm::ScheduleDAGInstrs::LIS, and llvm::ScheduleDAGInstrs::RegionBegin.
Referenced by schedule(), and llvm::ScheduleDAGMILive::scheduleMI().
placeDebugValues()
void ScheduleDAGMI::placeDebugValues () protected
Reinsert debug_values recorded in ScheduleDAGInstrs::DbgValues.
Reinsert any remaining debug_values, just like the PostRA scheduler.
Definition at line 793 of file MachineScheduler.cpp.
References llvm::ScheduleDAGInstrs::BB, llvm::ScheduleDAGInstrs::DbgValues, llvm::ScheduleDAGInstrs::FirstDbgValue, P, llvm::ScheduleDAGInstrs::RegionBegin, and llvm::ScheduleDAGInstrs::RegionEnd.
Referenced by schedule(), llvm::ScheduleDAGMILive::schedule(), and llvm::VLIWMachineScheduler::schedule().
postprocessDAG()
void ScheduleDAGMI::postprocessDAG () protected
Apply each ScheduleDAGMutation step in order.
Apply each ScheduleDAGMutation step in order. This allows different instances of ScheduleDAGMI to perform custom DAG postprocessing.
Definition at line 723 of file MachineScheduler.cpp.
References Mutations.
Referenced by schedule(), and llvm::ScheduleDAGMILive::schedule().
releasePred()
void ScheduleDAGMI::releasePred (SUnit * SU, SDep * PredEdge) protected
ReleasePred - Decrement the NumSuccsLeft count of a predecessor. When NumSuccsLeft reaches zero, release the predecessor node.
FIXME: Adjust PredSU height based on MinLatency.
Definition at line 569 of file MachineScheduler.cpp.
References llvm::SUnit::BotReadyCycle, llvm::dbgs(), llvm::SUnit::dump(), llvm::ScheduleDAG::EntrySU, llvm::SDep::getLatency(), llvm::SDep::getSUnit(), llvm::SDep::isCluster(), llvm::SDep::isWeak(), llvm_unreachable, NextClusterPred, llvm::SUnit::NumSuccsLeft, SchedImpl, and llvm::SUnit::WeakSuccsLeft.
Referenced by releasePredecessors().
releasePredecessors()
void ScheduleDAGMI::releasePredecessors (SUnit * SU) protected
releasePredecessors - Call releasePred on each of SU's predecessors.
Definition at line 597 of file MachineScheduler.cpp.
References I, llvm::SUnit::Preds, and releasePred().
Referenced by initQueues(), and updateQueues().
releaseSucc()
void ScheduleDAGMI::releaseSucc (SUnit * SU, SDep * SuccEdge) protected
ReleaseSucc - Decrement the NumPredsLeft count of a successor. When NumPredsLeft reaches zero, release the successor node.
FIXME: Adjust SuccSU height based on MinLatency.
Definition at line 530 of file MachineScheduler.cpp.
References llvm::dbgs(), llvm::SUnit::dump(), llvm::ScheduleDAG::ExitSU, llvm::SDep::getLatency(), llvm::SDep::getSUnit(), llvm::SDep::isCluster(), llvm::SDep::isWeak(), llvm_unreachable, NextClusterSucc, llvm::SUnit::NumPredsLeft, SchedImpl, llvm::SUnit::TopReadyCycle, and llvm::SUnit::WeakPredsLeft.
Referenced by releaseSuccessors().
releaseSuccessors()
void ScheduleDAGMI::releaseSuccessors (SUnit * SU) protected
releaseSuccessors - Call releaseSucc on each of SU's successors.
Definition at line 558 of file MachineScheduler.cpp.
References I, releaseSucc(), and llvm::SUnit::Succs.
Referenced by initQueues(), and updateQueues().
schedule()
void ScheduleDAGMI::schedule () override virtual
Implement ScheduleDAGInstrs interface for scheduling a sequence of reorderable instructions.
Per-region scheduling driver, called back from MachineScheduler::runOnMachineFunction. This is a simplified driver that does not consider liveness or register pressure. It is useful for PostRA scheduling and potentially other custom schedulers.
Implements llvm::ScheduleDAGInstrs.
Reimplemented in llvm::ScheduleDAGMILive, and llvm::VLIWMachineScheduler.
Definition at line 653 of file MachineScheduler.cpp.
References AA, llvm::ScheduleDAGInstrs::begin(), llvm::ScheduleDAGInstrs::buildSchedGraph(), checkSchedLimit(), CurrentBottom, CurrentTop, llvm::dbgs(), DEBUG, dumpSchedule(), findRootsAndBiasEdges(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getParent(), initQueues(), moveInstruction(), nextIfDebug(), placeDebugValues(), postprocessDAG(), priorNonDebug(), SchedImpl, llvm::ScheduleDAG::SUnits, Topo, updateQueues(), viewGraph(), and ViewMISchedDAGs.
top()
MachineBasicBlock::iterator llvm::ScheduleDAGMI::top () const inline
Definition at line 287 of file MachineScheduler.h.
References CurrentTop.
updateQueues()
void ScheduleDAGMI::updateQueues (SUnit * SU, bool IsTopNode) protected
Update scheduler DAG and queues after scheduling an instruction.
Update scheduler queues after scheduling an instruction.
Definition at line 782 of file MachineScheduler.cpp.
References llvm::SUnit::isScheduled, releasePredecessors(), and releaseSuccessors().
Referenced by schedule(), llvm::ScheduleDAGMILive::schedule(), and llvm::VLIWMachineScheduler::schedule().
viewGraph() [1/2]
void ScheduleDAGMI::viewGraph () override virtual
Out-of-line implementation with no arguments is handy for gdb.
Reimplemented from llvm::ScheduleDAG.
Definition at line 3309 of file MachineScheduler.cpp.
References llvm::ScheduleDAGInstrs::getDAGName(), and viewGraph().
Referenced by schedule(), and llvm::ScheduleDAGMILive::schedule().
viewGraph() [2/2]
void ScheduleDAGMI::viewGraph (const Twine & Name, const Twine & Title) override virtual
viewGraph - Pop up a ghostview window with the reachable parts of the DAG rendered using 'dot'.
Reimplemented from llvm::ScheduleDAG.
Definition at line 3299 of file MachineScheduler.cpp.
References llvm::errs(), Name, and llvm::ViewGraph().
Referenced by viewGraph().
Member Data Documentation
AA
AliasAnalysis* llvm::ScheduleDAGMI::AA protected
Definition at line 224 of file MachineScheduler.h.
Referenced by llvm::ScheduleDAGMILive::buildDAGWithRegPressure(), schedule(), and ScheduleDAGMI().
CurrentBottom
MachineBasicBlock::iterator llvm::ScheduleDAGMI::CurrentBottom protected
The bottom of the unscheduled zone.
Definition at line 238 of file MachineScheduler.h.
Referenced by bottom(), checkSchedLimit(), initQueues(), schedule(), llvm::ScheduleDAGMILive::schedule(), llvm::VLIWMachineScheduler::schedule(), ScheduleDAGMI(), and llvm::ScheduleDAGMILive::scheduleMI().
CurrentTop
MachineBasicBlock::iterator llvm::ScheduleDAGMI::CurrentTop protected
The top of the unscheduled zone.
Definition at line 235 of file MachineScheduler.h.
Referenced by checkSchedLimit(), initQueues(), schedule(), llvm::ScheduleDAGMILive::schedule(), llvm::VLIWMachineScheduler::schedule(), ScheduleDAGMI(), llvm::ScheduleDAGMILive::scheduleMI(), and top().
Mutations
std::vector<std::unique_ptr<ScheduleDAGMutation> > llvm::ScheduleDAGMI::Mutations protected
Ordered list of DAG postprocessing steps.
Definition at line 232 of file MachineScheduler.h.
Referenced by addMutation(), and postprocessDAG().
NextClusterPred
const SUnit* llvm::ScheduleDAGMI::NextClusterPred protected
Record the next node in a scheduled cluster.
Definition at line 241 of file MachineScheduler.h.
Referenced by getNextClusterPred(), initQueues(), releasePred(), and ScheduleDAGMI().
NextClusterSucc
const SUnit* llvm::ScheduleDAGMI::NextClusterSucc protected
Definition at line 242 of file MachineScheduler.h.
Referenced by getNextClusterSucc(), initQueues(), releaseSucc(), and ScheduleDAGMI().
NumInstrsScheduled
unsigned llvm::ScheduleDAGMI::NumInstrsScheduled protected
The number of instructions scheduled so far. Used to cut off the scheduler at the point determined by misched-cutoff.
Definition at line 247 of file MachineScheduler.h.
Referenced by checkSchedLimit(), and ScheduleDAGMI().
SchedImpl
std::unique_ptr<MachineSchedStrategy> llvm::ScheduleDAGMI::SchedImpl protected
Definition at line 225 of file MachineScheduler.h.
Referenced by enterRegion(), llvm::ScheduleDAGMILive::enterRegion(), initQueues(), releasePred(), releaseSucc(), schedule(), llvm::ScheduleDAGMILive::schedule(), llvm::VLIWMachineScheduler::schedule(), and ScheduleDAGMI().
Topo
ScheduleDAGTopologicalSort llvm::ScheduleDAGMI::Topo protected
Topo - A topological ordering for SUnits which permits fast IsReachable and similar queries.
Definition at line 229 of file MachineScheduler.h.
Referenced by addEdge(), canAddEdge(), schedule(), llvm::ScheduleDAGMILive::schedule(), and ScheduleDAGMI().
The documentation for this class was generated from the following files:
MachineScheduler.h
MachineScheduler.cpp