LLVM: llvm::SparseSolver Class Reference
LLVM API Documentation
llvm::SparseSolver Class Reference
#include <SparsePropagation.h>
Public Member Functions
SparseSolver (AbstractLatticeFunction *Lattice)
~SparseSolver ()
void Solve (Function &F)
void Print (Function &F, raw_ostream &OS) const
LatticeVal getLatticeState (Value *V) const
LatticeVal getOrInitValueState (Value *V)
bool isEdgeFeasible (BasicBlock *From, BasicBlock *To, bool AggressiveUndef=false)
bool isBlockExecutable (BasicBlock *BB) const
Detailed Description
SparseSolver - This class is a general purpose solver for Sparse Conditional Propagation with a programmable lattice function.
Definition at line 115 of file SparsePropagation.h.
Constructor & Destructor Documentation
SparseSolver()
llvm::SparseSolver::SparseSolver (AbstractLatticeFunction * Lattice) inline explicit
Definition at line 137 of file SparsePropagation.h.
~SparseSolver()
llvm::SparseSolver::~SparseSolver () inline
Definition at line 139 of file SparsePropagation.h.
Member Function Documentation
getLatticeState()
LatticeVal llvm::SparseSolver::getLatticeState (Value * V) const inline
getLatticeState - Return the LatticeVal object that corresponds to the value. If an value is not in the map, it is returned as untracked, unlike the getOrInitValueState method.
Definition at line 152 of file SparsePropagation.h.
References I.
Referenced by Print().
getOrInitValueState()
SparseSolver::LatticeVal SparseSolver::getOrInitValueState (Value * V)
getOrInitValueState - Return the LatticeVal object that corresponds to the value, initializing the value's state if it hasn't been entered into the map yet. This function is necessary because not all values should start out in the underdefined state... Arguments should be overdefined, and constants should be marked as constants.
Definition at line 53 of file SparsePropagation.cpp.
References llvm::dyn_cast(), I, and llvm::isa().
isBlockExecutable()
bool llvm::SparseSolver::isBlockExecutable (BasicBlock * BB) const inline
isBlockExecutable - Return true if there are any known feasible edges into the basic block. This is generally only useful when querying the lattice.
Definition at line 176 of file SparsePropagation.h.
isEdgeFeasible()
bool SparseSolver::isEdgeFeasible (BasicBlock * From, BasicBlock * To, bool AggressiveUndef = false)
isEdgeFeasible - Return true if the control flow edge from the 'From' basic block to the 'To' basic block is currently feasible. If AggressiveUndef is true, then this treats values with unknown lattice values as undefined. This is generally only useful when solving the lattice, not when querying it.
isEdgeFeasible - Return true if the control flow edge from the 'From' basic block to the 'To' basic block is currently feasible...
Definition at line 205 of file SparsePropagation.cpp.
References llvm::TerminatorInst::getNumSuccessors(), llvm::TerminatorInst::getSuccessor(), and llvm::BasicBlock::getTerminator().
Print()
void SparseSolver::Print (Function & F, raw_ostream & OS) const
Definition at line 329 of file SparsePropagation.cpp.
References llvm::BasicBlock::begin(), llvm::BasicBlock::end(), F, getLatticeState(), llvm::Value::getName(), llvm::Value::hasName(), and I.
Solve()
void SparseSolver::Solve (Function & F)
Solve - Solve for constants and executable blocks.
Definition at line 293 of file SparsePropagation.cpp.
References llvm::BasicBlock::back(), llvm::BasicBlock::begin(), llvm::cast(), llvm::dbgs(), DEBUG, llvm::BasicBlock::end(), F, llvm::Instruction::getParent(), and I.
The documentation for this class was generated from the following files:
SparsePropagation.h
SparsePropagation.cpp