LLVM: llvm::DIRef< T > Class Template Reference
LLVM API Documentation
llvm::DIRef< T > Class Template Reference
Represents reference to a DIDescriptor.
#include <DebugInfo.h>
Public Member Functions
T resolve (const DITypeIdentifierMap &Map) const
StringRef getName () const
operator Metadata * () const
Friends
class DIType
template<typename DescTy>
DescTy DIDescriptor::getFieldAs (unsigned Elt) const
DIScopeRef DIScope::getContext () const
DIScopeRef DIScope::getRef () const
Detailed Description
template<typename T>
class llvm::DIRef< T >
Represents reference to a DIDescriptor.
Abstracts over direct and identifier-based metadata references.
Definition at line 328 of file DebugInfo.h.
Member Function Documentation
getName()
template<typename T> StringRef llvm::DIRef< T >::getName () const
Definition at line 364 of file DebugInfo.h.
References llvm::cast(), llvm::dyn_cast(), llvm::MDString::getString(), and T.
operator Metadata *()
template<typename T> llvm::DIRef< T >::operator Metadata * () const inline
Definition at line 344 of file DebugInfo.h.
resolve()
template<typename T> T llvm::DIRef< T >::resolve (const DITypeIdentifierMap & Map) const
Definition at line 348 of file DebugInfo.h.
References llvm::cast(), llvm::dyn_cast(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::DIDescriptor::isType(), and T.
Referenced by llvm::DIBuilder::createFunction(), llvm::DIVariable::getSizeInBits(), llvm::DebugInfoFinder::processModule(), and llvm::DwarfDebug::resolve().
Friends And Related Symbol Documentation
DIDescriptor::getFieldAs
template<typename T> template<typename DescTy> DescTy DIDescriptor::getFieldAs (unsigned Elt) const friend
DIScope::getContext
template<typename T> DIScopeRef DIScope::getContext () const friend
DIScope::getRef
template<typename T> DIScopeRef DIScope::getRef () const friend
DIType
template<typename T> friend class DIType friend
Definition at line 333 of file DebugInfo.h.
The documentation for this class was generated from the following file:
DebugInfo.h