LLVM: llvm::MCTargetStreamer Class Reference
LLVM API Documentation
llvm::MCTargetStreamer Class Reference
#include <MCStreamer.h>
Public Member Functions
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
const MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void finish ()
Protected Attributes
MCStreamer & Streamer
Detailed Description
Target specific streamer interface. This is used so that targets can implement support for target specific assembly directives.
If target foo wants to use this, it should implement 3 classes:
FooTargetStreamer : public MCTargetStreamer
FooTargetAsmStreamer : public FooTargetStreamer
FooTargetELFStreamer : public FooTargetStreamer
FooTargetStreamer should have a pure virtual method for each directive. For example, for a ".bar symbol_name" directive, it should have virtual emitBar(const MCSymbol &Symbol) = 0;
The FooTargetAsmStreamer and FooTargetELFStreamer classes implement the method. The assembly streamer just prints ".bar symbol_name". The object streamer does whatever is needed to implement .bar in the object file.
In the assembly printer and parser the target streamer can be used by calling getTargetStreamer and casting it to FooTargetStreamer:
MCTargetStreamer &TS = OutStreamer.getTargetStreamer(); FooTargetStreamer &ATS = static_cast<FooTargetStreamer &>(TS);
The base classes FooTargetAsmStreamer and FooTargetELFStreamer should never be treated differently. Callers should always talk to a FooTargetStreamer.
Definition at line 72 of file MCStreamer.h.
Constructor & Destructor Documentation
MCTargetStreamer()
MCTargetStreamer::MCTargetStreamer (MCStreamer & S)
Definition at line 30 of file MCStreamer.cpp.
References llvm::MCStreamer::setTargetStreamer(), and Streamer.
Referenced by llvm::AArch64TargetStreamer::AArch64TargetStreamer(), llvm::ARMTargetStreamer::ARMTargetStreamer(), llvm::MipsTargetStreamer::MipsTargetStreamer(), llvm::PPCTargetStreamer::PPCTargetStreamer(), llvm::SparcTargetStreamer::SparcTargetStreamer(), and llvm::XCoreTargetStreamer::XCoreTargetStreamer().
~MCTargetStreamer()
MCTargetStreamer::~MCTargetStreamer () virtual
Definition at line 28 of file MCStreamer.cpp.
Member Function Documentation
emitAssignment()
void MCTargetStreamer::emitAssignment (MCSymbol * Symbol, const MCExpr * Value) virtual
Reimplemented in llvm::MipsTargetELFStreamer.
Definition at line 38 of file MCStreamer.cpp.
Referenced by llvm::MCStreamer::EmitAssignment().
emitLabel()
void MCTargetStreamer::emitLabel (MCSymbol * Symbol) virtual
Reimplemented in llvm::MipsTargetELFStreamer.
Definition at line 34 of file MCStreamer.cpp.
Referenced by llvm::MCStreamer::EmitLabel().
finish()
void MCTargetStreamer::finish () virtual
Reimplemented in llvm::AArch64TargetStreamer, llvm::ARMTargetStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 36 of file MCStreamer.cpp.
Referenced by llvm::MCStreamer::Finish().
getStreamer()
const MCStreamer & llvm::MCTargetStreamer::getStreamer () inline
Definition at line 80 of file MCStreamer.h.
References Streamer.
Member Data Documentation
Streamer
MCStreamer& llvm::MCTargetStreamer::Streamer protected
Definition at line 74 of file MCStreamer.h.
Referenced by llvm::AArch64TargetStreamer::addConstantPoolEntry(), llvm::ARMTargetStreamer::addConstantPoolEntry(), llvm::AArch64TargetStreamer::emitCurrentConstantPool(), llvm::ARMTargetStreamer::emitCurrentConstantPool(), llvm::AArch64TargetStreamer::finish(), llvm::ARMTargetStreamer::finish(), llvm::MipsTargetELFStreamer::finish(), getStreamer(), llvm::MipsTargetELFStreamer::getStreamer(), llvm::SparcTargetELFStreamer::getStreamer(), and MCTargetStreamer().
The documentation for this class was generated from the following files:
MCStreamer.h
MCStreamer.cpp