LLVM: llvm::sys::ThreadLocalImpl Class Reference
LLVM API Documentation
llvm::sys::ThreadLocalImpl Class Reference
#include <ThreadLocal.h>
Public Member Functions
ThreadLocalImpl ()
virtual ~ThreadLocalImpl ()
void setInstance (const void *d)
void * getInstance ()
void removeInstance ()
Detailed Description
Definition at line 25 of file ThreadLocal.h.
Constructor & Destructor Documentation
ThreadLocalImpl()
llvm::sys::ThreadLocalImpl::ThreadLocalImpl ()
Referenced by llvm::sys::ThreadLocal< T >::ThreadLocal().
~ThreadLocalImpl()
virtual llvm::sys::ThreadLocalImpl::~ThreadLocalImpl () virtual
Member Function Documentation
getInstance()
void * llvm::sys::ThreadLocalImpl::getInstance ()
Referenced by llvm::sys::ThreadLocal< T >::get().
removeInstance()
void llvm::sys::ThreadLocalImpl::removeInstance ()
Referenced by llvm::sys::ThreadLocal< T >::erase().
setInstance()
void llvm::sys::ThreadLocalImpl::setInstance (const void * d)
Referenced by llvm::sys::ThreadLocal< T >::set().
Member Data Documentation
align_data
ThreadLocalDataTy llvm::sys::ThreadLocalImpl::align_data
Definition at line 33 of file ThreadLocal.h.
data
char llvm::sys::ThreadLocalImpl::data[sizeof(ThreadLocalDataTy)]
Definition at line 32 of file ThreadLocal.h.
The documentation for this class was generated from the following file:
ThreadLocal.h