LLVM: llvm::MCLEBFragment Class Reference
LLVM API Documentation
llvm::MCLEBFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCLEBFragment (const MCExpr &Value_, bool IsSigned_, MCSectionData *SD=nullptr)
Accessors
const MCExpr & getValue () const
bool isSigned () const
SmallString< 8 > & getContents ()
const SmallString< 8 > & getContents () const
Public Member Functions inherited from llvm::MCFragment
MCFragment ()
virtual ~MCFragment ()
FragmentType getKind () const
MCSectionData * getParent () const
void setParent (MCSectionData *Value)
MCSymbolData * getAtom () const
void setAtom (MCSymbolData *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
virtual bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
virtual bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
virtual void setAlignToBundleEnd (bool V)
virtual uint8_t getBundlePadding () const
Get the padding size that must be inserted before this fragment. Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
virtual void setBundlePadding (uint8_t N)
Set the padding size for this fragment. By default it's a no-op, and only some fragments have a meaningful implementation.
void dump ()
Public Member Functions inherited from llvm::ilist_node< MCFragment >
MCFragment * getPrevNode ()
Get the previous node, or 0 for the list head.
MCFragment * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Relaxable , FT_Org , FT_Dwarf , FT_DwarfFrame ,
FT_LEB
}
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType _Kind, MCSectionData *_Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node< MCFragment >
ilist_node ()
Detailed Description
Definition at line 460 of file MCAssembler.h.
Constructor & Destructor Documentation
MCLEBFragment()
llvm::MCLEBFragment::MCLEBFragment (const MCExpr & Value_, bool IsSigned_, MCSectionData * SD = nullptr) inline
Definition at line 471 of file MCAssembler.h.
References llvm::MCFragment::FT_LEB.
Member Function Documentation
classof()
bool llvm::MCLEBFragment::classof (const MCFragment * F) inline static
Definition at line 488 of file MCAssembler.h.
References F, and llvm::MCFragment::FT_LEB.
getContents() [1/2]
SmallString< 8 > & llvm::MCLEBFragment::getContents () inline
Definition at line 483 of file MCAssembler.h.
Referenced by writeFragment().
getContents() [2/2]
const SmallString< 8 > & llvm::MCLEBFragment::getContents () const inline
Definition at line 484 of file MCAssembler.h.
getValue()
const MCExpr & llvm::MCLEBFragment::getValue () const inline
Definition at line 479 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump().
isSigned()
bool llvm::MCLEBFragment::isSigned () const inline
Definition at line 481 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump().
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp