LLVM: llvm::MachineSchedRegistry Class Reference
LLVM API Documentation
llvm::MachineSchedRegistry Class Reference
#include <MachineScheduler.h>
Public Types
typedef ScheduleDAGInstrs *(* ScheduleDAGCtor) (MachineSchedContext *)
typedef ScheduleDAGCtor FunctionPassCtor
Public Member Functions
MachineSchedRegistry (const char *N, const char *D, ScheduleDAGCtor C)
~MachineSchedRegistry ()
MachineSchedRegistry * getNext () const
Public Member Functions inherited from llvm::MachinePassRegistryNode
MachinePassRegistryNode (const char *N, const char *D, MachinePassCtor C)
MachinePassRegistryNode * getNext () const
MachinePassRegistryNode ** getNextAddress ()
const char * getName () const
const char * getDescription () const
MachinePassCtor getCtor () const
void setNext (MachinePassRegistryNode *N)
Static Public Member Functions
static MachineSchedRegistry * getList ()
static void setListener (MachinePassRegistryListener *L)
Static Public Attributes
static MachinePassRegistry Registry
Detailed Description
MachineSchedRegistry provides a selection of available machine instruction schedulers.
Definition at line 117 of file MachineScheduler.h.
Member Typedef Documentation
FunctionPassCtor
typedef ScheduleDAGCtor llvm::MachineSchedRegistry::FunctionPassCtor
Definition at line 122 of file MachineScheduler.h.
ScheduleDAGCtor
typedef ScheduleDAGInstrs *(* llvm::MachineSchedRegistry::ScheduleDAGCtor) (MachineSchedContext *)
Definition at line 119 of file MachineScheduler.h.
Constructor & Destructor Documentation
MachineSchedRegistry()
llvm::MachineSchedRegistry::MachineSchedRegistry (const char * N, const char * D, ScheduleDAGCtor C) inline
Definition at line 126 of file MachineScheduler.h.
References llvm::MachinePassRegistryNode::MachinePassRegistryNode(), N, and Registry.
Referenced by getList(), and getNext().
~MachineSchedRegistry()
llvm::MachineSchedRegistry::~MachineSchedRegistry () inline
Definition at line 130 of file MachineScheduler.h.
References Registry.
Member Function Documentation
getList()
MachineSchedRegistry * llvm::MachineSchedRegistry::getList () inline static
Definition at line 137 of file MachineScheduler.h.
References MachineSchedRegistry(), and Registry.
getNext()
MachineSchedRegistry * llvm::MachineSchedRegistry::getNext () const inline
Definition at line 134 of file MachineScheduler.h.
References llvm::MachinePassRegistryNode::getNext(), and MachineSchedRegistry().
setListener()
void llvm::MachineSchedRegistry::setListener (MachinePassRegistryListener * L) inline static
Definition at line 140 of file MachineScheduler.h.
References Registry.
Member Data Documentation
Registry
MachinePassRegistry MachineSchedRegistry::Registry static
Definition at line 124 of file MachineScheduler.h.
Referenced by getList(), MachineSchedRegistry(), setListener(), and ~MachineSchedRegistry().
The documentation for this class was generated from the following files:
MachineScheduler.h
MachineScheduler.cpp