LLVM: llvm::SmallVectorBase Class Reference
LLVM API Documentation
llvm::SmallVectorBase Class Reference
This is all the non-templated stuff common to all SmallVectors.
#include <SmallVector.h>
Inherited by llvm::SmallVectorTemplateCommon< std::unique_ptr< UnitType > >, llvm::SmallVectorTemplateCommon< llvm::cl::parser::OptionInfo >, llvm::SmallVectorTemplateCommon< std::pair< KeyT, ValueT > >, llvm::SmallVectorTemplateCommon< char >, llvm::SmallVectorTemplateCommon< unsigned >, llvm::SmallVectorTemplateCommon< const llvm::MachineInstr * >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::MCSymbol * > >, llvm::SmallVectorTemplateCommon< uint8_t >, llvm::SmallVectorTemplateCommon< MCPhysReg >, llvm::SmallVectorTemplateCommon< FreeList * >, llvm::SmallVectorTemplateCommon< HandlerInfo >, llvm::SmallVectorTemplateCommon< const llvm::Comdat * >, llvm::SmallVectorTemplateCommon< llvm::WeakVH >, llvm::SmallVectorTemplateCommon< llvm::BitCodeAbbrevOp >, llvm::SmallVectorTemplateCommon< llvm::Instruction * >, llvm::SmallVectorTemplateCommon< Block >, llvm::SmallVectorTemplateCommon< void * >, llvm::SmallVectorTemplateCommon< std::pair< void *, size_t > >, llvm::SmallVectorTemplateCommon< llvm::CCValAssign >, llvm::SmallVectorTemplateCommon< uint32_t >, llvm::SmallVectorTemplateCommon< ByValInfo >, llvm::SmallVectorTemplateCommon< llvm::BasicBlock * >, llvm::SmallVectorTemplateCommon< llvm::SDNode * >, llvm::SmallVectorTemplateCommon< llvm::Metadata * >, llvm::SmallVectorTemplateCommon< llvm::TypedTrackingMDRef< MDNode > >, llvm::SmallVectorTemplateCommon< llvm::DIEValue * >, llvm::SmallVectorTemplateCommon< llvm::DIEAbbrevData >, llvm::SmallVectorTemplateCommon< llvm::DILineInfo >, llvm::SmallVectorTemplateCommon< std::pair< AtomType, Form > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::DWARFCompileUnit > >, llvm::SmallVectorTemplateCommon< llvm::SmallString< 32 > >, llvm::SmallVectorTemplateCommon< llvm::DWARFDebugInfoEntryMinimal >, llvm::SmallVectorTemplateCommon< unsigned char >, llvm::SmallVectorTemplateCommon< Entry >, llvm::SmallVectorTemplateCommon< llvm::LayoutAlignElem >, llvm::SmallVectorTemplateCommon< llvm::DICompileUnit >, llvm::SmallVectorTemplateCommon< llvm::DISubprogram >, llvm::SmallVectorTemplateCommon< llvm::DIGlobalVariable >, llvm::SmallVectorTemplateCommon< llvm::DIType >, llvm::SmallVectorTemplateCommon< llvm::DIScope >, llvm::SmallVectorTemplateCommon< llvm::DebugLocEntry::Value >, llvm::SmallVectorTemplateCommon< llvm::DebugLocEntry >, llvm::SmallVectorTemplateCommon< llvm::DwarfAccelTable::Atom >, llvm::SmallVectorTemplateCommon< llvm::RangeSpanList >, llvm::SmallVectorTemplateCommon< llvm::RangeSpan >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::DbgVariable > >, llvm::SmallVectorTemplateCommon< llvm::DebugLocList >, llvm::SmallVectorTemplateCommon< std::pair< std::unique_ptr< llvm::DwarfTypeUnit >, llvm::DICompositeType > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::DwarfUnit > >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< unsigned, 8 > >, llvm::SmallVectorTemplateCommon< std::string >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::Module > >, llvm::SmallVectorTemplateCommon< llvm::Value * >, llvm::SmallVectorTemplateCommon< llvm::ISD::ArgFlagsTy >, llvm::SmallVectorTemplateCommon< llvm::ISD::InputArg >, llvm::SmallVectorTemplateCommon< llvm::MachineInstr * >, llvm::SmallVectorTemplateCommon< llvm::GCOVEdge * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCOVFunction > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCOVBlock > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCOVEdge > >, llvm::SmallVectorTemplateCommon< uintptr_t >, llvm::SmallVectorTemplateCommon< llvm::AllocaInst * >, llvm::SmallVectorTemplateCommon< RegUnitInfo >, llvm::SmallVectorTemplateCommon< BlockInterference >, llvm::SmallVectorTemplateCommon< llvm::MCSymbol * >, llvm::SmallVectorTemplateCommon< llvm::LazyCallGraph::SCC * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::iterator > >, llvm::SmallVectorTemplateCommon< llvm::Function * >, llvm::SmallVectorTemplateCommon< llvm::LazyCallGraph::Node * >, llvm::SmallVectorTemplateCommon< std::pair< bool, llvm::StringRef > >, llvm::SmallVectorTemplateCommon< llvm::LexicalScope * >, llvm::SmallVectorTemplateCommon< InsnRange >, llvm::SmallVectorTemplateCommon< llvm::LiveInterval * >, llvm::SmallVectorTemplateCommon< llvm::SlotIndex >, llvm::SmallVectorTemplateCommon< const uint32_t * >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, unsigned > >, llvm::SmallVectorTemplateCommon< llvm::LiveRange * >, llvm::SmallVectorTemplateCommon< LiveInBlock >, llvm::SmallVectorTemplateCommon< llvm::LiveRange::Segment >, llvm::SmallVectorTemplateCommon< llvm::MCSectionData * >, llvm::SmallVectorTemplateCommon< llvm::MCFixup >, llvm::SmallVectorTemplateCommon< llvm::MCDwarfFile >, llvm::SmallVectorTemplateCommon< llvm::MCOperand >, llvm::SmallVectorTemplateCommon< llvm::object::OwningBinary< llvm::object::Archive > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::MemoryBuffer > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::object::ObjectFile > >, llvm::SmallVectorTemplateCommon< llvm::MCLOHDirective >, llvm::SmallVectorTemplateCommon< llvm::MCSymbolData * >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::MCFragment * > >, llvm::SmallVectorTemplateCommon< std::pair< MCSectionSubPair, MCSectionSubPair > >, llvm::SmallVectorTemplateCommon< CriticalEdge >, llvm::SmallVectorTemplateCommon< llvm::MachineBasicBlock * >, llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >, llvm::SmallVectorTemplateCommon< llvm::MachineTraceMetrics::FixedBlockInfo >, llvm::SmallVectorTemplateCommon< llvm::MachineTraceMetrics::TraceBlockInfo >, llvm::SmallVectorTemplateCommon< llvm::MachineTraceMetrics::LiveInReg >, llvm::SmallVectorTemplateCommon< std::string * >, llvm::SmallVectorTemplateCommon< bool >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::MipsOptionRecord > >, llvm::SmallVectorTemplateCommon< const llvm::Value * >, llvm::SmallVectorTemplateCommon< llvm::Pass * >, llvm::SmallVectorTemplateCommon< llvm::PMDataManager * >, llvm::SmallVectorTemplateCommon< llvm::ImmutablePass * >, llvm::SmallVectorTemplateCommon< llvm::SUnit * >, llvm::SmallVectorTemplateCommon< llvm::AsmRewrite >, llvm::SmallVectorTemplateCommon< std::pair< AnalysisID, llvm::IdentifyingPassPtr > >, llvm::SmallVectorTemplateCommon< llvm::SMLoc >, llvm::SmallVectorTemplateCommon< ScavengedInfo >, llvm::SmallVectorTemplateCommon< std::pair< SID, llvm::SmallVector< RelocationValueRef, 2 > > >, llvm::SmallVectorTemplateCommon< SID >, llvm::SmallVectorTemplateCommon< llvm::RuntimeDyldMachO::EHFrameRelatedSections >, llvm::SmallVectorTemplateCommon< const llvm::SCEV * >, llvm::SmallVectorTemplateCommon< llvm::SDDbgValue * >, llvm::SmallVectorTemplateCommon< llvm::SMFixIt >, llvm::SmallVectorTemplateCommon< llvm::PHINode * >, llvm::SmallVectorTemplateCommon< PhiT * >, llvm::SmallVectorTemplateCommon< llvm::SDep >, llvm::SmallVectorTemplateCommon< RootData >, llvm::SmallVectorTemplateCommon< TreeData >, llvm::SmallVectorTemplateCommon< llvm::sys::MemoryBlock >, llvm::SmallVectorTemplateCommon< llvm::SDValue >, llvm::SmallVectorTemplateCommon< std::pair< llvm::SlotIndex, llvm::SlotIndex > >, llvm::SmallVectorTemplateCommon< IdxMBBPair >, llvm::SmallVectorTemplateCommon< llvm::BlockFrequency >, llvm::SmallVectorTemplateCommon< llvm::SplitAnalysis::BlockInfo >, llvm::SmallVectorTemplateCommon< const llvm::CallInst * >, llvm::SmallVectorTemplateCommon< llvm::ISD::OutputArg >, llvm::SmallVectorTemplateCommon< const llvm::LocalAsMetadata * >, llvm::SmallVectorTemplateCommon< const llvm::Function * >, llvm::SmallVectorTemplateCommon< llvm::StringRef >, llvm::SmallVectorTemplateCommon< llvm::ForwardedRegister >, llvm::SmallVectorTemplateCommon< std::pair< const char *, std::pair< int, const char * > > >, llvm::SmallVectorTemplateCommon< llvm::detail::PtrUseVisitorBase::UseToVisit >, llvm::SmallVectorTemplateCommon< VersionMapEntry >, llvm::SmallVectorTemplateCommon< NodeState >, llvm::SmallVectorTemplateCommon< const char * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::opt::Arg > >, llvm::SmallVectorTemplateCommon< llvm::opt::Arg * >, llvm::SmallVectorTemplateCommon< InState >, llvm::SmallVectorTemplateCommon< int >, llvm::SmallVectorTemplateCommon< SimpleKey >, and llvm::SmallVectorTemplateCommon< T, typename >.
Public Member Functions
size_t size_in_bytes () const
This returns size()*sizeof(T).
size_t capacity_in_bytes () const
capacity_in_bytes - This returns capacity()*sizeof(T).
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
Protected Member Functions
SmallVectorBase (void *FirstEl, size_t Size)
void grow_pod (void *FirstEl, size_t MinSizeInBytes, size_t TSize)
Protected Attributes
void * BeginX
void * EndX
void * CapacityX
Detailed Description
This is all the non-templated stuff common to all SmallVectors.
Definition at line 33 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorBase()
llvm::SmallVectorBase::SmallVectorBase (void * FirstEl, size_t Size) inline protected
Definition at line 38 of file SmallVector.h.
References BeginX, CapacityX, and EndX.
Referenced by llvm::SmallVectorTemplateCommon< T, typename >::SmallVectorTemplateCommon().
Member Function Documentation
capacity_in_bytes()
size_t llvm::SmallVectorBase::capacity_in_bytes () const inline
capacity_in_bytes - This returns capacity()*sizeof(T).
Definition at line 52 of file SmallVector.h.
References BeginX, and CapacityX.
Referenced by grow_pod().
empty()
bool LLVM_ATTRIBUTE_UNUSED_RESULT llvm::SmallVectorBase::empty () const inline
Definition at line 56 of file SmallVector.h.
References BeginX, EndX, and LLVM_ATTRIBUTE_UNUSED_RESULT.
Referenced by llvm::PMDataManager::add(), AddAliasScopeMetadata(), addBlockAndPredsToSet(), addRange(), AddReachableCodeToWorklist(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), advanceToNextLeafType(), llvm::LoopInfoBase< BlockT, LoopT >::Analyze(), llvm::ARMBaseInstrInfo::AnalyzeBranch(), llvm::MSP430InstrInfo::AnalyzeBranch(), llvm::SparcInstrInfo::AnalyzeBranch(), llvm::SystemZInstrInfo::AnalyzeBranch(), llvm::X86InstrInfo::AnalyzeBranch(), llvm::A57ChainingConstraint::apply(), AreAnyUnderlyingObjectsAnAlloca(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildGEP(), buildGraphFrom(), buildMultiplyTree(), llvm::ScheduleDAGInstrs::buildSchedGraph(), buildSetsFrom(), callIsStructReturn(), llvm::MachineBasicBlock::canFallThrough(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), CleanupConstantGlobalUsers(), CloneAliasScopeMetadata(), completeEphemeralValues(), llvm::SCEVAddRecExpr::computeAccessFunctions(), ComputePostOrders(), llvm::ConstantAggrKeyType< ConstantArray >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), ConstantFoldGetElementPtrImpl(), ConstHasGlobalValuePredicate(), containsConstantSomewhere(), CrashHandler(), DeleteDeadInstruction(), deleteDeadInstruction(), DeleteTriviallyDeadInstructions(), llvm::SCEVAddRecExpr::delinearize(), determinePointerReadAttrs(), llvm::AsmPrinter::doFinalization(), llvm::ScheduleDAGSDNodes::dumpNode(), EliminateDeadSwitchCases(), llvm::EmitAnyX86InstComments(), llvm::PPCFrameLowering::emitEpilogue(), llvm::X86AsmPrinter::EmitInstruction(), llvm::PPCFrameLowering::emitPrologue(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::DominatorTreeBase< BlockT >::Eval, extendSegmentsToUses(), llvm::ScalarEvolution::findArrayDimensions(), findCallees(), findConsecutiveLoad(), llvm::objcarc::FindDependencies(), llvm::FindFunctionBackedges(), FindMostPopularDest(), firstRealType(), FixTail(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), llvm::formLCSSA(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::ScalarEvolution::getAddExpr(), llvm::DominatorTreeBase< BlockT >::getDescendants(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::ScalarEvolution::getMulExpr(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::object::ELFObjectFile< ELFT >::getRelocationValueString(), llvm::ScalarEvolution::getSMaxExpr(), getTargetShuffleMask(), llvm::Intrinsic::getType(), llvm::ScalarEvolution::getUMaxExpr(), llvm::GetUnderlyingObjects(), getUnderlyingObjects(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::SDNode::hasPredecessorHelper(), llvm::InlineFunction(), llvm::AArch64InstrInfo::InsertBranch(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::HexagonInstrInfo::InsertBranch(), llvm::MipsInstrInfo::InsertBranch(), llvm::MSP430InstrInfo::InsertBranch(), llvm::NVPTXInstrInfo::InsertBranch(), llvm::PPCInstrInfo::InsertBranch(), llvm::R600InstrInfo::InsertBranch(), llvm::SparcInstrInfo::InsertBranch(), llvm::SystemZInstrInfo::InsertBranch(), llvm::X86InstrInfo::InsertBranch(), llvm::XCoreInstrInfo::InsertBranch(), llvm::LazyCallGraph::SCC::insertIncomingEdge(), llvm::MachineTraceMetrics::Ensemble::invalidate(), isAllocSiteRemovable(), llvm::LazyCallGraph::SCC::isDescendantOf(), isEphemeralValueOf(), isLeakCheckerRoot(), isOnlyCopiedFromConstantGlobal(), llvm::isPotentiallyReachable(), isPotentiallyReachableInner(), IsStoredObjCPointer(), llvm::MCContext::isValidDwarfFileNumber(), IsValueFullyAvailableInBlock(), isVectorPromotionViable(), LinearizeExprTree(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::LowerDbgDeclare(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::SystemZTargetLowering::LowerReturn(), llvm::MapMetadata(), markAliveBlocks(), llvm::SIInstrInfo::moveToVALU(), nextRealType(), llvm::BranchFolder::OptimizeFunction(), llvm::cl::ParseCommandLineOptions(), llvm::PointerMayBeCaptured(), llvm::HexagonInstrInfo::PredicateInstruction(), PrepareTailCall(), llvm::MachineInstr::print(), llvm::AssemblyWriter::printInstruction(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), processInstruction(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::Inliner::removeDeadFunctions(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::PMDataManager::removeDeadPasses(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::LazyCallGraph::SCC::removeIntraSCCEdge(), replaceConstantExprOp(), llvm::HexagonInstrInfo::ReverseBranchCondition(), rewriteLoopExitBlock(), rewriteNonInstructionUses(), llvm::Inliner::runOnSCC(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), SimplifyAddOperands(), llvm::simplifyLoop(), simplifyOneLoop(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::const_iterator< T, N >::SmallVector(), SplitAddRecs(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), SymbolicallyEvaluateGEP(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::APFloat::toString(), llvm::UnrollLoop(), llvm::DominatorTreeBase< BlockT >::updateDFSNumbers(), llvm::MachineBasicBlock::updateTerminator(), llvm::PHITransAddr::Verify(), verifyCTRBranch(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitLandingPadInst(), WriteMetadataAttachment(), and WriteModuleMetadataStore().
grow_pod()
void SmallVectorBase::grow_pod (void * FirstEl, size_t MinSizeInBytes, size_t TSize) protected
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
grow_pod - This is an implementation of the grow() method which only works on POD-like datatypes and is out of line to reduce code duplication.
Definition at line 19 of file SmallVector.cpp.
References BeginX, capacity_in_bytes(), CapacityX, EndX, and size_in_bytes().
Referenced by llvm::SmallVectorTemplateCommon< T, typename >::grow_pod().
size_in_bytes()
size_t llvm::SmallVectorBase::size_in_bytes () const inline
This returns size()*sizeof(T).
Definition at line 47 of file SmallVector.h.
References BeginX, and EndX.
Referenced by grow_pod().
Member Data Documentation
BeginX
void* llvm::SmallVectorBase::BeginX protected
Definition at line 35 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), capacity_in_bytes(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::clear(), empty(), llvm::SmallVectorTemplateBase< T, isPodLike >::grow(), grow_pod(), llvm::SmallVectorTemplateCommon< T, typename >::isSmall(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorTemplateCommon< T, typename >::resetToSmall(), size_in_bytes(), SmallVectorBase(), and llvm::SmallVectorImpl< T >::swap().
CapacityX
void * llvm::SmallVectorBase::CapacityX protected
Definition at line 35 of file SmallVector.h.
Referenced by capacity_in_bytes(), llvm::SmallVectorTemplateCommon< T, typename >::capacity_ptr(), llvm::SmallVectorTemplateCommon< T, typename >::capacity_ptr(), llvm::SmallVectorTemplateBase< T, isPodLike >::grow(), grow_pod(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::resetToSmall(), SmallVectorBase(), and llvm::SmallVectorImpl< T >::swap().
EndX
void * llvm::SmallVectorBase::EndX protected
Definition at line 35 of file SmallVector.h.
Referenced by llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::clear(), empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), grow_pod(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::insert(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::resetToSmall(), llvm::SmallVectorTemplateCommon< T, typename >::setEnd(), size_in_bytes(), SmallVectorBase(), and llvm::SmallVectorImpl< T >::swap().
The documentation for this class was generated from the following files:
SmallVector.h
SmallVector.cpp