LLVM: llvm::MachineInstrBuilder Class Reference
LLVM API Documentation
llvm::MachineInstrBuilder Class Reference
#include <MachineInstrBuilder.h>
Public Member Functions
MachineInstrBuilder ()
MachineInstrBuilder (MachineFunction &F, MachineInstr *I)
operator MachineInstr * () const
MachineInstr * operator-> () const
operator MachineBasicBlock::iterator () const
MachineInstr * getInstr () const
const MachineInstrBuilder & addReg (unsigned RegNo, unsigned flags=0, unsigned SubReg=0) const
const MachineInstrBuilder & addImm (int64_t Val) const
const MachineInstrBuilder & addCImm (const ConstantInt *Val) const
const MachineInstrBuilder & addFPImm (const ConstantFP *Val) const
const MachineInstrBuilder & addMBB (MachineBasicBlock *MBB, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addFrameIndex (int Idx) const
const MachineInstrBuilder & addConstantPoolIndex (unsigned Idx, int Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addTargetIndex (unsigned Idx, int64_t Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addJumpTableIndex (unsigned Idx, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addGlobalAddress (const GlobalValue *GV, int64_t Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addExternalSymbol (const char *FnName, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addBlockAddress (const BlockAddress *BA, int64_t Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addRegMask (const uint32_t *Mask) const
const MachineInstrBuilder & addMemOperand (MachineMemOperand *MMO) const
const MachineInstrBuilder & setMemRefs (MachineInstr::mmo_iterator b, MachineInstr::mmo_iterator e) const
const MachineInstrBuilder & addOperand (const MachineOperand &MO) const
const MachineInstrBuilder & addMetadata (const MDNode *MD) const
const MachineInstrBuilder & addCFIIndex (unsigned CFIIndex) const
const MachineInstrBuilder & addSym (MCSymbol *Sym) const
const MachineInstrBuilder & setMIFlags (unsigned Flags) const
const MachineInstrBuilder & setMIFlag (MachineInstr::MIFlag Flag) const
const MachineInstrBuilder & addDisp (const MachineOperand &Disp, int64_t off, unsigned char TargetFlags=0) const
const MachineInstrBuilder & copyImplicitOps (const MachineInstr *OtherMI)
Copy all the implicit operands from OtherMI onto this one.
Detailed Description
Definition at line 45 of file MachineInstrBuilder.h.
Constructor & Destructor Documentation
MachineInstrBuilder() [1/2]
llvm::MachineInstrBuilder::MachineInstrBuilder () inline
Definition at line 49 of file MachineInstrBuilder.h.
Referenced by addBlockAddress(), addCFIIndex(), addCImm(), addConstantPoolIndex(), addDisp(), addExternalSymbol(), addFPImm(), addFrameIndex(), addGlobalAddress(), addImm(), addJumpTableIndex(), addMBB(), addMemOperand(), addMetadata(), addOperand(), addReg(), addRegMask(), addSym(), addTargetIndex(), copyImplicitOps(), setMemRefs(), setMIFlag(), and setMIFlags().
MachineInstrBuilder() [2/2]
llvm::MachineInstrBuilder::MachineInstrBuilder (MachineFunction & F, MachineInstr * I) inline
Create a MachineInstrBuilder for manipulating an existing instruction. F must be the machine function that was used to allocate I.
Definition at line 53 of file MachineInstrBuilder.h.
References F, and I.
Member Function Documentation
addBlockAddress()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addBlockAddress (const BlockAddress * BA, int64_t Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 146 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateBA(), and MachineInstrBuilder().
addCFIIndex()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addCFIIndex (unsigned CFIIndex) const inline
Definition at line 182 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateCFIIndex(), and MachineInstrBuilder().
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), EmitCfiOffset(), EmitDefCfaOffset(), EmitDefCfaRegister(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), and llvm::X86FrameLowering::emitPrologue().
addCImm()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addCImm (const ConstantInt * Val) const inline
Definition at line 92 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateCImm(), and MachineInstrBuilder().
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::FastISel::selectIntrinsicCall().
addConstantPoolIndex()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addConstantPoolIndex (unsigned Idx, int Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 113 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateCPI(), and MachineInstrBuilder().
Referenced by llvm::addConstantPoolReference(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::XCoreInstrInfo::loadImmediate(), and llvm::ARMBaseInstrInfo::reMaterialize().
addDisp()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addDisp (const MachineOperand & Disp, int64_t off, unsigned char TargetFlags = 0) const inline
Definition at line 203 of file MachineInstrBuilder.h.
References addGlobalAddress(), addImm(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm_unreachable, MachineInstrBuilder(), llvm::MachineOperand::MO_GlobalAddress, and llvm::MachineOperand::MO_Immediate.
addExternalSymbol()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addExternalSymbol (const char * FnName, unsigned char TargetFlags = 0) const inline
Definition at line 140 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateES(), and MachineInstrBuilder().
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::emitEpilogue(), emitGPDisp(), llvm::ARMFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitStackProbeCall(), llvm::ARMFrameLowering::fixTCReturn(), and llvm::FastISel::selectCall().
addFPImm()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addFPImm (const ConstantFP * Val) const inline
Definition at line 97 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateFPImm(), and MachineInstrBuilder().
Referenced by llvm::InstrEmitter::EmitDbgValue(), llvm::FastISel::fastEmitInst_rf(), and llvm::FastISel::selectIntrinsicCall().
addFrameIndex()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addFrameIndex (int Idx) const inline
Definition at line 108 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateFI(), and MachineInstrBuilder().
Referenced by llvm::addFrameReference(), llvm::addFrameReference(), llvm::addFrameReference(), llvm::addFullAddress(), emitAlignedDPRCS2Restores(), llvm::InstrEmitter::EmitDbgValue(), llvm::AArch64InstrInfo::emitFrameIndexDebugValue(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), and llvm::XCoreInstrInfo::storeRegToStackSlot().
addGlobalAddress()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addGlobalAddress (const GlobalValue * GV, int64_t Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 133 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateGA(), and MachineInstrBuilder().
Referenced by addDisp(), llvm::addFullAddress(), llvm::X86FrameLowering::emitEpilogue(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::AArch64InstrInfo::expandPostRAPseudo(), and llvm::ARMFrameLowering::fixTCReturn().
addImm()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addImm (int64_t Val) const inline
addImm - Add a new immediate operand.
Definition at line 87 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateImm(), and MachineInstrBuilder().
Referenced by llvm::addConstantPoolReference(), llvm::AddDefaultPred(), llvm::addDirectMem(), addDisp(), llvm::addFrameReference(), llvm::addFrameReference(), llvm::addFullAddress(), llvm::addOffset(), llvm::addRegReg(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::SparcInstrInfo::AnalyzeBranch(), llvm::Mips16InstrInfo::BuildAddiuSpImm(), llvm::R600InstrInfo::buildDefaultInstruction(), llvm::SIInstrInfo::buildIndirectRead(), llvm::SIInstrInfo::buildIndirectWrite(), llvm::BuildMI(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::PPCInstrInfo::commuteInstruction(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::XCoreInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyToCPSR(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::emitARMRegPlusImmediate(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::InstrEmitter::EmitDbgValue(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::ARMFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AArch64InstrInfo::emitFrameIndexDebugValue(), llvm::emitFrameOffset(), emitIncrement(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::TargetLoweringBase::emitPatchPoint(), emitPostLd(), emitPostSt(), llvm::ARMFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSPUpdate(), llvm::emitT2RegPlusImmediate(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), EmitXBegin(), llvm::SparcTargetLowering::expandAtomicRMW(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), llvm::FastISel::fastEmitInst_i(), llvm::FastISel::fastEmitInst_ii(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rri(), llvm::FastISel::fastEmitInst_rrii(), llvm::ARMFrameLowering::fixTCReturn(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), forceReg(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), HandleVRSaveUpdate(), IfNeededExtSP(), IfNeededLDAWSP(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::MSP430InstrInfo::InsertBranch(), llvm::PPCInstrInfo::InsertBranch(), llvm::SparcInstrInfo::InsertBranch(), llvm::SystemZInstrInfo::InsertBranch(), insertDivByZeroTrap(), InsertFPImmInst(), InsertLDR_STR(), insertNopBeforeInstruction(), llvm::SIInstrInfo::insertNOPs(), llvm::AArch64InstrInfo::insertSelect(), InsertSPConstInst(), InsertSPImmInst(), llvm::SIInstrInfo::legalizeOperands(), llvm::Mips16InstrInfo::loadImmediate(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), llvm::XCoreInstrInfo::loadImmediate(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::Mips16InstrInfo::makeFrame(), MakeM0Inst(), llvm::AArch64RegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::SIInstrInfo::moveSMRDToVALU(), llvm::AArch64InstrInfo::optimizeCondBranch(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::ARMBaseInstrInfo::reMaterialize(), llvm::X86InstrInfo::reMaterialize(), replaceFI(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::Mips16InstrInfo::restoreFrame(), RestoreSpillList(), llvm::FastISel::selectCall(), llvm::FastISel::selectIntrinsicCall(), llvm::FastISel::selectStackmap(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::SIInstrInfo::splitSMRD(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), tryOrrMovk(), trySequenceOfOnes(), and tryToreplicateChunks().
addJumpTableIndex()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addJumpTableIndex (unsigned Idx, unsigned char TargetFlags = 0) const inline
Definition at line 127 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateJTI(), and MachineInstrBuilder().
addMBB()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addMBB (MachineBasicBlock * MBB, unsigned char TargetFlags = 0) const inline
Definition at line 102 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateMBB(), and MachineInstrBuilder().
Referenced by llvm::SSAUpdaterTraits< MachineSSAUpdater >::AddPHIOperand(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::SparcInstrInfo::AnalyzeBranch(), llvm::X86InstrInfo::AnalyzeBranch(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::MSP430TargetLowering::EmitShiftInstr(), EmitXBegin(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::SparcTargetLowering::expandSelectCC(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::AArch64InstrInfo::InsertBranch(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::HexagonInstrInfo::InsertBranch(), llvm::MipsInstrInfo::InsertBranch(), llvm::MSP430InstrInfo::InsertBranch(), llvm::NVPTXInstrInfo::InsertBranch(), llvm::PPCInstrInfo::InsertBranch(), llvm::R600InstrInfo::InsertBranch(), llvm::SparcInstrInfo::InsertBranch(), llvm::SystemZInstrInfo::InsertBranch(), llvm::X86InstrInfo::InsertBranch(), llvm::XCoreInstrInfo::InsertBranch(), llvm::AArch64InstrInfo::optimizeCondBranch(), and llvm::PPCInstrInfo::PredicateInstruction().
addMemOperand()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addMemOperand (MachineMemOperand * MMO) const inline
Definition at line 158 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addMemOperand(), and MachineInstrBuilder().
Referenced by llvm::addFrameReference(), llvm::addFrameReference(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreFrameLowering::emitPrologue(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), InsertFPConstInst(), InsertFPImmInst(), InsertSPConstInst(), InsertSPImmInst(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), RestoreSpillList(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), and llvm::XCoreInstrInfo::storeRegToStackSlot().
addMetadata()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addMetadata (const MDNode * MD) const inline
Definition at line 175 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateMetadata(), and MachineInstrBuilder().
Referenced by llvm::BuildMI(), llvm::InstrEmitter::EmitDbgValue(), llvm::AArch64InstrInfo::emitFrameIndexDebugValue(), and llvm::FastISel::selectIntrinsicCall().
addOperand()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addOperand (const MachineOperand & MO) const inline
Definition at line 170 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and MachineInstrBuilder().
Referenced by llvm::SIInstrInfo::buildIndirectRead(), llvm::SIInstrInfo::buildIndirectWrite(), llvm::X86InstrInfo::classifyLEAReg(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::X86FrameLowering::emitEpilogue(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), EmitMonitor(), llvm::TargetLoweringBase::emitPatchPoint(), EmitPCMPSTRI(), EmitPCMPSTRM(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), forceReg(), FuseInst(), FuseTwoAddrInst(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), llvm::MipsInstrInfo::genInstrWithNewOpc(), llvm::PPCInstrInfo::InsertBranch(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::X86InstrInfo::loadRegFromAddr(), MakeM0Inst(), llvm::SIInstrInfo::moveToVALU(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::X86InstrInfo::reMaterialize(), llvm::FastISel::selectIntrinsicCall(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), llvm::SIInstrInfo::splitSMRD(), llvm::X86InstrInfo::storeRegToAddr(), transferImpOps(), llvm::tryFoldSPUpdateIntoPushPop(), tryOrrMovk(), trySequenceOfOnes(), tryToreplicateChunks(), and llvm::X86InstrInfo::unfoldMemoryOperand().
addReg()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addReg (unsigned RegNo, unsigned flags = 0, unsigned SubReg = 0) const inline
addReg - Add a new virtual register operand...
Definition at line 68 of file MachineInstrBuilder.h.
References llvm::MachineOperand::CreateReg(), llvm::RegState::Dead, llvm::RegState::Debug, llvm::RegState::Define, llvm::RegState::EarlyClobber, llvm::RegState::Implicit, llvm::RegState::InternalRead, llvm::RegState::Kill, MachineInstrBuilder(), and llvm::RegState::Undef.
Referenced by llvm::addConstantPoolReference(), llvm::AddDefaultCC(), llvm::AddDefaultPred(), llvm::AddDefaultT1CC(), llvm::addDirectMem(), llvm::ARMBaseInstrInfo::AddDReg(), llvm::addFrameReference(), llvm::addFullAddress(), llvm::MachineBasicBlock::addLiveIn(), llvm::AddNoT1CC(), llvm::addOffset(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::AddPHIOperand(), llvm::addRegOffset(), llvm::addRegReg(), addSavedGPR(), addSaveRestoreRegs(), AddSubReg(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::X86InstrInfo::breakPartialRegDependency(), llvm::R600InstrInfo::buildDefaultInstruction(), llvm::SIInstrInfo::buildIndirectRead(), llvm::SIInstrInfo::buildIndirectWrite(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::BuildMI(), llvm::SIInstrInfo::buildMovInstr(), llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::X86InstrInfo::classifyLEAReg(), llvm::PPCInstrInfo::commuteInstruction(), llvm::FastISel::constrainOperandRegClass(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::Mips16InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::MSP430InstrInfo::copyPhysReg(), llvm::NVPTXInstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), llvm::R600InstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::SparcInstrInfo::copyPhysReg(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::Thumb1InstrInfo::copyPhysReg(), llvm::X86InstrInfo::copyPhysReg(), llvm::XCoreInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyToCPSR(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), emitAligningInstructions(), llvm::emitARMRegPlusImmediate(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::InstrEmitter::EmitDbgValue(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::ARMFrameLowering::emitEpilogue(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::emitFrameOffset(), emitGPDisp(), emitIncrement(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MachineRegisterInfo::EmitLiveInCopies(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), EmitMonitor(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), EmitPCMPSTRI(), EmitPCMPSTRM(), emitPostLd(), emitPostSt(), llvm::ARMFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::NVPTXFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSPUpdate(), llvm::X86FrameLowering::emitStackProbeCall(), llvm::emitT2RegPlusImmediate(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), EmitXBegin(), Expand2AddrUndef(), llvm::SparcTargetLowering::expandAtomicRMW(), expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::SparcTargetLowering::expandSelectCC(), llvm::FastISel::fastEmitInst_extractsubreg(), llvm::FastISel::fastEmitInst_i(), llvm::FastISel::fastEmitInst_ii(), llvm::FastISel::fastEmitInst_r(), llvm::FastISel::fastEmitInst_rf(), llvm::FastISel::fastEmitInst_ri(), llvm::FastISel::fastEmitInst_rii(), llvm::FastISel::fastEmitInst_rr(), llvm::FastISel::fastEmitInst_rri(), llvm::FastISel::fastEmitInst_rrii(), llvm::FastISel::fastEmitInst_rrr(), llvm::ARMFrameLowering::fixTCReturn(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), forceReg(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), genMadd(), genMaddR(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), HandleVRSaveUpdate(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::HexagonInstrInfo::InsertBranch(), llvm::NVPTXInstrInfo::InsertBranch(), llvm::R600InstrInfo::InsertBranch(), llvm::XCoreInstrInfo::InsertBranch(), insertCopy(), insertDivByZeroTrap(), InsertFPConstInst(), InsertFPImmInst(), InsertLDR_STR(), llvm::AArch64InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), InsertSPConstInst(), InsertSPImmInst(), llvm::SIInstrInfo::legalizeOperands(), llvm::Mips16InstrInfo::loadImmediate(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::PPCRegisterInfo::lowerCRBitRestore(), llvm::PPCRegisterInfo::lowerCRBitSpilling(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), llvm::Mips16InstrInfo::makeFrame(), llvm::SIInstrInfo::moveSMRDToVALU(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::R600InstrInfo::PredicateInstruction(), llvm::SystemZInstrInfo::PredicateInstruction(), replaceFI(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), restoreCRs(), llvm::Mips16InstrInfo::restoreFrame(), llvm::Thumb1RegisterInfo::saveScavengerRegister(), llvm::FastISel::selectBitCast(), llvm::FastISel::selectIntrinsicCall(), setCallTargetReg(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::SIInstrInfo::splitSMRD(), llvm::X86InstrInfo::storeRegToAddr(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::ScheduleDAGInstrs::toggleKillFlag(), tryOrrMovk(), trySequenceOfOnes(), tryToreplicateChunks(), llvm::X86InstrInfo::unfoldMemoryOperand(), and UpdatePredRedefs().
addRegMask()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addRegMask (const uint32_t * Mask) const inline
Definition at line 153 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateRegMask(), and MachineInstrBuilder().
Referenced by llvm::PPCTargetLowering::emitEHSjLjSetJmp().
addSym()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addSym (MCSymbol * Sym) const inline
Definition at line 187 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateMCSymbol(), and MachineInstrBuilder().
addTargetIndex()
const MachineInstrBuilder & llvm::MachineInstrBuilder::addTargetIndex (unsigned Idx, int64_t Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 120 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateTargetIndex(), and MachineInstrBuilder().
Referenced by llvm::SIInstrInfo::expandPostRAPseudo().
copyImplicitOps()
const MachineInstrBuilder & llvm::MachineInstrBuilder::copyImplicitOps (const MachineInstr * OtherMI) inline
Copy all the implicit operands from OtherMI onto this one.
Definition at line 225 of file MachineInstrBuilder.h.
References llvm::MachineInstr::copyImplicitOps(), and MachineInstrBuilder().
Referenced by llvm::Thumb1FrameLowering::emitEpilogue(), and llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters().
getInstr()
MachineInstr * llvm::MachineInstrBuilder::getInstr () const inline
If conversion operators fail, use this method to get the MachineInstr explicitly.
Definition at line 63 of file MachineInstrBuilder.h.
Referenced by expandLoadStackGuard(), and llvm::XCoreInstrInfo::loadImmediate().
operator MachineBasicBlock::iterator()
llvm::MachineInstrBuilder::operator MachineBasicBlock::iterator () const inline
Definition at line 59 of file MachineInstrBuilder.h.
operator MachineInstr *()
llvm::MachineInstrBuilder::operator MachineInstr * () const inline
Allow automatic conversion to the machine instruction we are working on.
Definition at line 57 of file MachineInstrBuilder.h.
operator->()
MachineInstr * llvm::MachineInstrBuilder::operator-> () const inline
Definition at line 58 of file MachineInstrBuilder.h.
setMemRefs()
const MachineInstrBuilder & llvm::MachineInstrBuilder::setMemRefs (MachineInstr::mmo_iterator b, MachineInstr::mmo_iterator e) const inline
Definition at line 163 of file MachineInstrBuilder.h.
References MachineInstrBuilder(), and llvm::MachineInstr::setMemRefs().
Referenced by llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::MipsInstrInfo::genInstrWithNewOpc(), llvm::X86InstrInfo::loadRegFromAddr(), and llvm::X86InstrInfo::storeRegToAddr().
setMIFlag()
const MachineInstrBuilder & llvm::MachineInstrBuilder::setMIFlag (MachineInstr::MIFlag Flag) const inline
Definition at line 197 of file MachineInstrBuilder.h.
References MachineInstrBuilder(), and llvm::MachineInstr::setFlag().
Referenced by llvm::emitFrameOffset(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), and llvm::X86FrameLowering::spillCalleeSavedRegisters().
setMIFlags()
const MachineInstrBuilder & llvm::MachineInstrBuilder::setMIFlags (unsigned Flags) const inline
Definition at line 192 of file MachineInstrBuilder.h.
References MachineInstrBuilder(), and llvm::MachineInstr::setFlags().
Referenced by llvm::emitARMRegPlusImmediate(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::emitT2RegPlusImmediate(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), and llvm::Thumb1FrameLowering::spillCalleeSavedRegisters().
The documentation for this class was generated from the following file:
MachineInstrBuilder.h