LLVM: llvm::cl::Option Class Reference
LLVM API Documentation
llvm::cl::Option Class Reference abstract
#include <CommandLine.h>
Public Member Functions
enum NumOccurrencesFlag getNumOccurrencesFlag () const
enum ValueExpected getValueExpectedFlag () const
enum OptionHidden getOptionHiddenFlag () const
enum FormattingFlags getFormattingFlag () const
unsigned getMiscFlags () const
unsigned getPosition () const
unsigned getNumAdditionalVals () const
bool hasArgStr () const
void setArgStr (const char *S)
void setDescription (const char *S)
void setValueStr (const char *S)
void setNumOccurrencesFlag (enum NumOccurrencesFlag Val)
void setValueExpectedFlag (enum ValueExpected Val)
void setHiddenFlag (enum OptionHidden Val)
void setFormattingFlag (enum FormattingFlags V)
void setMiscFlag (enum MiscFlags M)
void setPosition (unsigned pos)
void setCategory (OptionCategory &C)
void addArgument ()
void removeArgument ()
Option * getNextRegisteredOption () const
virtual size_t getOptionWidth () const =0
virtual void printOptionInfo (size_t GlobalWidth) const =0
virtual void printOptionValue (size_t GlobalWidth, bool Force) const =0
virtual void getExtraOptionNames (SmallVectorImpl< const char * > &)
virtual bool addOccurrence (unsigned pos, StringRef ArgName, StringRef Value, bool MultiArg=false)
bool error (const Twine &Message, StringRef ArgName=StringRef())
int getNumOccurrences () const
virtual ~Option ()
Public Attributes
const char * ArgStr
const char * HelpStr
const char * ValueStr
OptionCategory * Category
Protected Member Functions
Option (enum NumOccurrencesFlag OccurrencesFlag, enum OptionHidden Hidden)
void setNumAdditionalVals (unsigned n)
Friends
class alias
Detailed Description
Definition at line 165 of file CommandLine.h.
Constructor & Destructor Documentation
Option()
llvm::cl::Option::Option (enum NumOccurrencesFlag OccurrencesFlag, enum OptionHidden Hidden) inline explicit protected
Definition at line 236 of file CommandLine.h.
References ArgStr, Category, llvm::cl::GeneralCategory, HelpStr, llvm::cl::Hidden, llvm::cl::NormalFormatting, and ValueStr.
Referenced by llvm::cl::alias::alias(), llvm::cl::alias::alias(), llvm::cl::alias::alias(), llvm::cl::alias::alias(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), getNextRegisteredOption(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), removeArgument(), and llvm::cl::alias::setAliasFor().
~Option()
virtual llvm::cl::Option::~Option () inline virtual
Definition at line 280 of file CommandLine.h.
Member Function Documentation
addArgument()
void Option::addArgument ()
Definition at line 107 of file CommandLine.cpp.
References llvm::cl::MarkOptionsChanged(), and RegisteredOptionList.
addOccurrence()
bool Option::addOccurrence (unsigned pos, StringRef ArgName, StringRef Value, bool MultiArg = false) virtual
Definition at line 1104 of file CommandLine.cpp.
References llvm::cl::ConsumeAfter, error(), getNumOccurrencesFlag(), llvm::cl::OneOrMore, llvm::cl::Optional, llvm::cl::Required, and llvm::cl::ZeroOrMore.
Referenced by CommaSeparateAndAddOccurrence().
error()
bool Option::error (const Twine & Message, StringRef ArgName = StringRef())
Definition at line 1092 of file CommandLine.cpp.
References ArgStr, llvm::StringRef::data(), llvm::StringRef::empty(), llvm::errs(), HelpStr, and ProgramName.
Referenced by addOccurrence(), llvm::cl::parser< DataType >::parse(), llvm::cl::ParseCommandLineOptions(), parseDouble(), ProvideOption(), llvm::cl::alias::setAliasFor(), llvm::cl::bits_storage< DataType, StorageClass >::setLocation(), llvm::cl::list_storage< DataType, StorageClass >::setLocation(), and llvm::cl::opt_storage< DataType, ExternalStorage, isClass >::setLocation().
getExtraOptionNames()
virtual void llvm::cl::Option::getExtraOptionNames (SmallVectorImpl< const char * > &) inline virtual
Definition at line 268 of file CommandLine.h.
Referenced by LookupNearestOption().
getFormattingFlag()
enum FormattingFlags llvm::cl::Option::getFormattingFlag () const inline
Definition at line 211 of file CommandLine.h.
Referenced by HandlePrefixedOrGroupedOption(), isGrouping(), isPrefixedOrGrouping(), and llvm::cl::ParseCommandLineOptions().
getMiscFlags()
unsigned llvm::cl::Option::getMiscFlags () const inline
Definition at line 214 of file CommandLine.h.
Referenced by CommaSeparateAndAddOccurrence(), and llvm::cl::ParseCommandLineOptions().
getNextRegisteredOption()
Option * llvm::cl::Option::getNextRegisteredOption () const inline
Definition at line 256 of file CommandLine.h.
References Option().
getNumAdditionalVals()
unsigned llvm::cl::Option::getNumAdditionalVals () const inline
Definition at line 216 of file CommandLine.h.
Referenced by ProvideOption().
getNumOccurrences()
int llvm::cl::Option::getNumOccurrences () const inline
Definition at line 279 of file CommandLine.h.
getNumOccurrencesFlag()
enum NumOccurrencesFlag llvm::cl::Option::getNumOccurrencesFlag () const inline
Definition at line 202 of file CommandLine.h.
Referenced by addOccurrence(), EatsUnboundedNumberOfValues(), and RequiresValue().
getOptionHiddenFlag()
enum OptionHidden llvm::cl::Option::getOptionHiddenFlag () const inline
Definition at line 208 of file CommandLine.h.
getOptionWidth()
virtual size_t llvm::cl::Option::getOptionWidth () const pure virtual
getPosition()
unsigned llvm::cl::Option::getPosition () const inline
Definition at line 215 of file CommandLine.h.
getValueExpectedFlag()
enum ValueExpected llvm::cl::Option::getValueExpectedFlag () const inline
Definition at line 205 of file CommandLine.h.
Referenced by HandlePrefixedOrGroupedOption(), LookupNearestOption(), and ProvideOption().
hasArgStr()
bool llvm::cl::Option::hasArgStr () const inline
Definition at line 219 of file CommandLine.h.
References ArgStr.
Referenced by llvm::cl::generic_parser_base::getOptionWidth(), llvm::cl::generic_parser_base::initialize(), and llvm::cl::generic_parser_base::printOptionInfo().
printOptionInfo()
virtual void llvm::cl::Option::printOptionInfo (size_t GlobalWidth) const pure virtual
printOptionValue()
virtual void llvm::cl::Option::printOptionValue (size_t GlobalWidth, bool Force) const pure virtual
removeArgument()
void Option::removeArgument ()
Unregisters this option from the CommandLine system.
This option must have been the last option registered. For testing purposes only.
Definition at line 115 of file CommandLine.cpp.
References llvm::cl::MarkOptionsChanged(), Option(), and RegisteredOptionList.
setArgStr()
void llvm::cl::Option::setArgStr (const char * S) inline
Definition at line 224 of file CommandLine.h.
References ArgStr.
setCategory()
void llvm::cl::Option::setCategory (OptionCategory & C) inline
Definition at line 233 of file CommandLine.h.
References Category.
setDescription()
void llvm::cl::Option::setDescription (const char * S) inline
Definition at line 225 of file CommandLine.h.
References HelpStr.
Referenced by llvm::cl::desc::apply().
setFormattingFlag()
void llvm::cl::Option::setFormattingFlag (enum FormattingFlags V) inline
Definition at line 230 of file CommandLine.h.
Referenced by llvm::cl::applicator< FormattingFlags >::opt().
setHiddenFlag()
void llvm::cl::Option::setHiddenFlag (enum OptionHidden Val) inline
Definition at line 229 of file CommandLine.h.
Referenced by llvm::cl::applicator< OptionHidden >::opt().
setMiscFlag()
void llvm::cl::Option::setMiscFlag (enum MiscFlags M) inline
Definition at line 231 of file CommandLine.h.
Referenced by llvm::cl::applicator< MiscFlags >::opt().
setNumAdditionalVals()
void llvm::cl::Option::setNumAdditionalVals (unsigned n) inline protected
Definition at line 243 of file CommandLine.h.
Referenced by llvm::cl::list< DataType, Storage, ParserClass >::setNumAdditionalVals().
setNumOccurrencesFlag()
void llvm::cl::Option::setNumOccurrencesFlag (enum NumOccurrencesFlag Val) inline
Definition at line 227 of file CommandLine.h.
Referenced by llvm::cl::applicator< NumOccurrencesFlag >::opt().
setPosition()
void llvm::cl::Option::setPosition (unsigned pos) inline
Definition at line 232 of file CommandLine.h.
setValueExpectedFlag()
void llvm::cl::Option::setValueExpectedFlag (enum ValueExpected Val) inline
Definition at line 228 of file CommandLine.h.
Referenced by llvm::cl::applicator< ValueExpected >::opt().
setValueStr()
void llvm::cl::Option::setValueStr (const char * S) inline
Definition at line 226 of file CommandLine.h.
References ValueStr.
Referenced by llvm::cl::value_desc::apply().
Friends And Related Symbol Documentation
alias
friend class alias friend
Definition at line 166 of file CommandLine.h.
References alias, and llvm::cl::ValueOptional.
Referenced by alias.
Member Data Documentation
ArgStr
const char* llvm::cl::Option::ArgStr
Definition at line 197 of file CommandLine.h.
Referenced by error(), llvm::cl::basic_parser_impl::getOptionWidth(), llvm::cl::generic_parser_base::getOptionWidth(), hasArgStr(), LookupNearestOption(), Option(), llvm::cl::ParseCommandLineOptions(), llvm::cl::generic_parser_base::printGenericOptionDiff(), llvm::cl::basic_parser_impl::printOptionInfo(), llvm::cl::generic_parser_base::printOptionInfo(), llvm::cl::basic_parser_impl::printOptionName(), ProvidePositionalOption(), and setArgStr().
Category
OptionCategory* llvm::cl::Option::Category
Definition at line 200 of file CommandLine.h.
Referenced by Option(), and setCategory().
HelpStr
const char* llvm::cl::Option::HelpStr
Definition at line 198 of file CommandLine.h.
Referenced by error(), Option(), llvm::cl::basic_parser_impl::printOptionInfo(), llvm::cl::generic_parser_base::printOptionInfo(), and setDescription().
ValueStr
const char* llvm::cl::Option::ValueStr
Definition at line 199 of file CommandLine.h.
Referenced by getValueStr(), Option(), and setValueStr().
The documentation for this class was generated from the following files:
CommandLine.h
CommandLine.cpp