LLVM: llvm::DiagnosticInfoOptimizationRemark Class Reference
LLVM API Documentation
llvm::DiagnosticInfoOptimizationRemark Class Reference
Diagnostic information for applied optimization remarks.
#include <DiagnosticInfo.h>
Public Member Functions
DiagnosticInfoOptimizationRemark (const char *PassName, const Function &Fn, const DebugLoc &DLoc, const Twine &Msg)
bool isEnabled () const override
Public Member Functions inherited from llvm::DiagnosticInfoOptimizationBase
DiagnosticInfoOptimizationBase (enum DiagnosticKind Kind, enum DiagnosticSeverity Severity, const char *PassName, const Function &Fn, const DebugLoc &DLoc, const Twine &Msg)
void print (DiagnosticPrinter &DP) const override
bool isLocationAvailable () const
Return true if location information is available for this diagnostic.
const std::string getLocationStr () const
void getLocation (StringRef *Filename, unsigned *Line, unsigned *Column) const
const char * getPassName () const
const Function & getFunction () const
const DebugLoc & getDebugLoc () const
const Twine & getMsg () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Static Public Member Functions inherited from llvm::DiagnosticInfoOptimizationBase
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for applied optimization remarks.
Definition at line 312 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoOptimizationRemark()
llvm::DiagnosticInfoOptimizationRemark::DiagnosticInfoOptimizationRemark (const char * PassName, const Function & Fn, const DebugLoc & DLoc, const Twine & Msg) inline
PassName is the name of the pass emitting this diagnostic. If this name matches the regular expression given in -Rpass=, then the diagnostic will be emitted. Fn is the function where the diagnostic is being emitted. DLoc is the location information to use in the diagnostic. If line table information is available, the diagnostic will include the source code location. Msg is the message to show. Note that this class does not copy this message, so this reference must be valid for the whole life time of the diagnostic.
Definition at line 322 of file DiagnosticInfo.h.
References llvm::DiagnosticInfoOptimizationBase::DiagnosticInfoOptimizationBase(), llvm::DK_OptimizationRemark, and llvm::DS_Remark.
Member Function Documentation
classof()
bool llvm::DiagnosticInfoOptimizationRemark::classof (const DiagnosticInfo * DI) inline static
Definition at line 327 of file DiagnosticInfo.h.
References llvm::DK_OptimizationRemark, and llvm::DiagnosticInfo::getKind().
isEnabled()
bool DiagnosticInfoOptimizationRemark::isEnabled () const override virtual
See also
DiagnosticInfoOptimizationBase::isEnabled.
Implements llvm::DiagnosticInfoOptimizationBase.
Definition at line 157 of file DiagnosticInfo.cpp.
References llvm::DiagnosticInfoOptimizationBase::getPassName().
The documentation for this class was generated from the following files:
DiagnosticInfo.h
DiagnosticInfo.cpp