LLVM: llvm::MachineRegionNode Class Reference
LLVM API Documentation
llvm::MachineRegionNode Class Reference
#include <MachineRegionInfo.h>
Public Member Functions
MachineRegionNode (MachineRegion *Parent, MachineBasicBlock *Entry, bool isSubRegion=false)
~MachineRegionNode ()
bool operator== (const MachineRegion &RN) const
Public Member Functions inherited from llvm::RegionNodeBase< RegionTraits< MachineFunction > >
BasicBlock * getNodeAs () const
Region * getNodeAs () const
MachineBasicBlock * getNodeAs () const
MachineRegion * getNodeAs () const
RegionT * getParent () const
Get the parent Region of this RegionNode.
BlockT * getEntry () const
Get the entry BasicBlock of this RegionNode.
bool isSubRegion () const
Is this RegionNode a subregion?
Additional Inherited Members
Public Types inherited from llvm::RegionNodeBase< RegionTraits< MachineFunction > >
typedef RegionTraits< MachineFunction >::BlockT BlockT
typedef RegionTraits< MachineFunction >::RegionT RegionT
Detailed Description
Definition at line 51 of file MachineRegionInfo.h.
Constructor & Destructor Documentation
MachineRegionNode()
llvm::MachineRegionNode::MachineRegionNode (MachineRegion * Parent, MachineBasicBlock * Entry, bool isSubRegion = false) inline
Definition at line 53 of file MachineRegionInfo.h.
References llvm::RegionNodeBase< RegionTraits< MachineFunction > >::isSubRegion().
Referenced by operator==().
~MachineRegionNode()
llvm::MachineRegionNode::~MachineRegionNode () inline
Definition at line 60 of file MachineRegionInfo.h.
Member Function Documentation
operator==()
bool llvm::MachineRegionNode::operator== (const MachineRegion & RN) const inline
Definition at line 62 of file MachineRegionInfo.h.
References MachineRegionNode().
The documentation for this class was generated from the following file:
MachineRegionInfo.h