LLVM: llvm::object::IRObjectFile Class Reference
LLVM API Documentation
llvm::object::IRObjectFile Class Reference
#include <IRObjectFile.h>
Public Member Functions
IRObjectFile (MemoryBufferRef Object, std::unique_ptr< Module > M)
~IRObjectFile ()
void moveSymbolNext (DataRefImpl &Symb) const override
std::error_code printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
uint32_t getSymbolFlags (DataRefImpl Symb) const override
GlobalValue * getSymbolGV (DataRefImpl Symb)
const GlobalValue * getSymbolGV (DataRefImpl Symb) const
basic_symbol_iterator symbol_begin_impl () const override
basic_symbol_iterator symbol_end_impl () const override
const Module & getModule () const
Module & getModule ()
std::unique_ptr< Module > takeModule ()
Public Member Functions inherited from llvm::object::SymbolicFile
virtual ~SymbolicFile ()
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
basic_symbol_iterator symbol_begin () const
basic_symbol_iterator symbol_end () const
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isIR () const
bool isLittleEndian () const
Static Public Member Functions
static bool classof (const Binary *v)
static ErrorOr< MemoryBufferRef > findBitcodeInObject (const ObjectFile &Obj)
Finds and returns bitcode embedded in the given object file, or an error code if not found.
static ErrorOr< MemoryBufferRef > findBitcodeInMemBuffer (MemoryBufferRef Object)
Finds and returns bitcode in the given memory buffer (which may be either a bitcode file or a native object file with embedded bitcode), or an error code if not found.
static ErrorOr< std::unique_ptr< IRObjectFile > > create (MemoryBufferRef Object, LLVMContext &Context)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static ErrorOr< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, sys::fs::file_magic Type, LLVMContext *Context)
static ErrorOr< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static ErrorOr< OwningBinary< SymbolicFile > > createSymbolicFile (StringRef ObjectPath)
static bool classof (const Binary *v)
Additional Inherited Members
Public Types inherited from llvm::object::SymbolicFile
typedef iterator_range< basic_symbol_iterator > basic_symbol_iterator_range
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_IR , ID_StartObjects ,
ID_COFF , ID_ELF32L , ID_ELF32B , ID_ELF64L ,
ID_ELF64B , ID_MachO32L , ID_MachO32B , ID_MachO64L ,
ID_MachO64B , ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 27 of file IRObjectFile.h.
Constructor & Destructor Documentation
IRObjectFile()
IRObjectFile::IRObjectFile (MemoryBufferRef Object, std::unique_ptr< Module > M)
Definition at line 36 of file IRObjectFile.cpp.
References llvm::createMCAsmParser(), llvm::CodeModel::Default, llvm::Reloc::Default, llvm::RecordStreamer::Defined, llvm::RecordStreamer::DefinedGlobal, llvm::MemoryBuffer::getMemBuffer(), llvm::RecordStreamer::Global, llvm::object::Binary::ID_IR, if(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), llvm_unreachable, llvm::TargetRegistry::lookupTarget(), llvm::RecordStreamer::NeverSeen, llvm::DataLayout::reset(), llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_None, llvm::object::BasicSymbolRef::SF_Undefined, llvm::SrcMgr, llvm::object::SymbolicFile::SymbolicFile(), and llvm::RecordStreamer::Used.
Referenced by getModule(), and getSymbolGV().
~IRObjectFile()
IRObjectFile::~IRObjectFile ()
Definition at line 116 of file IRObjectFile.cpp.
Member Function Documentation
classof()
bool llvm::object::IRObjectFile::classof (const Binary * v) inline static
Definition at line 54 of file IRObjectFile.h.
References llvm::object::Binary::isIR().
create()
ErrorOr< std::unique_ptr< IRObjectFile > > llvm::object::IRObjectFile::create (MemoryBufferRef Object, LLVMContext & Context) static
Definition at line 295 of file IRObjectFile.cpp.
References findBitcodeInMemBuffer(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::getLazyBitcodeModule(), llvm::MemoryBuffer::getMemBuffer(), and llvm::make_unique().
Referenced by llvm::object::SymbolicFile::createSymbolicFile().
findBitcodeInMemBuffer()
ErrorOr< MemoryBufferRef > IRObjectFile::findBitcodeInMemBuffer (MemoryBufferRef Object) static
Finds and returns bitcode in the given memory buffer (which may be either a bitcode file or a native object file with embedded bitcode), or an error code if not found.
Definition at line 275 of file IRObjectFile.cpp.
References llvm::sys::fs::file_magic::bitcode, llvm::sys::fs::file_magic::coff_object, llvm::object::ObjectFile::createObjectFile(), llvm::sys::fs::file_magic::elf_relocatable, findBitcodeInObject(), llvm::ErrorOr< T >::get(), llvm::MemoryBufferRef::getBuffer(), llvm::ErrorOr< T >::getError(), llvm::sys::fs::identify_magic(), llvm::object::invalid_file_type, and llvm::sys::fs::file_magic::macho_object.
Referenced by create(), llvm::LTOModule::isBitcodeFile(), llvm::LTOModule::isBitcodeFile(), llvm::LTOModule::isBitcodeForTarget(), and parseBitcodeFileImpl().
findBitcodeInObject()
ErrorOr< MemoryBufferRef > IRObjectFile::findBitcodeInObject (const ObjectFile & Obj) static
Finds and returns bitcode embedded in the given object file, or an error code if not found.
Definition at line 259 of file IRObjectFile.cpp.
References llvm::object::bitcode_section_not_found, llvm::object::Binary::getFileName(), and llvm::object::ObjectFile::sections().
Referenced by llvm::object::SymbolicFile::createSymbolicFile(), and findBitcodeInMemBuffer().
getModule() [1/2]
Module & llvm::object::IRObjectFile::getModule () inline
Definition at line 49 of file IRObjectFile.h.
getModule() [2/2]
const Module & llvm::object::IRObjectFile::getModule () const inline
Definition at line 46 of file IRObjectFile.h.
References getModule(), and IRObjectFile().
Referenced by getModule().
getSymbolFlags()
uint32_t IRObjectFile::getSymbolFlags (DataRefImpl Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 209 of file IRObjectFile.cpp.
References llvm::dyn_cast(), getAsmSymIndex(), getGV(), llvm::Value::getName(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasLinkOnceLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::hasPrivateLinkage(), llvm::GlobalValue::hasWeakLinkage(), llvm::GlobalValue::isDeclarationForLinker(), llvm::object::BasicSymbolRef::SF_Common, llvm::object::BasicSymbolRef::SF_FormatSpecific, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_None, llvm::object::BasicSymbolRef::SF_Undefined, llvm::object::BasicSymbolRef::SF_Weak, and llvm::StringRef::startswith().
getSymbolGV() [1/2]
GlobalValue * IRObjectFile::getSymbolGV (DataRefImpl Symb)
Definition at line 240 of file IRObjectFile.cpp.
References getGV().
Referenced by getSymbolGV().
getSymbolGV() [2/2]
const GlobalValue * llvm::object::IRObjectFile::getSymbolGV (DataRefImpl Symb) const inline
Definition at line 40 of file IRObjectFile.h.
References getSymbolGV(), and IRObjectFile().
moveSymbolNext()
void IRObjectFile::moveSymbolNext (DataRefImpl & Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 154 of file IRObjectFile.cpp.
References getAsmSymIndex(), getGV(), llvm_unreachable, llvm::object::DataRefImpl::p, and skipEmpty().
printSymbolName()
std::error_code IRObjectFile::printSymbolName (raw_ostream & OS, DataRefImpl Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 191 of file IRObjectFile.cpp.
References getAsmSymIndex(), getGV(), llvm::Value::getName(), and llvm::object::success.
symbol_begin_impl()
basic_symbol_iterator IRObjectFile::symbol_begin_impl () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 244 of file IRObjectFile.cpp.
References I, and skipEmpty().
symbol_end_impl()
basic_symbol_iterator IRObjectFile::symbol_end_impl () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 251 of file IRObjectFile.cpp.
takeModule()
std::unique_ptr< Module > IRObjectFile::takeModule ()
Definition at line 242 of file IRObjectFile.cpp.
The documentation for this class was generated from the following files:
IRObjectFile.h
IRObjectFile.cpp