LLVM: llvm::CallGraphWrapperPass Class Reference
LLVM API Documentation
llvm::CallGraphWrapperPass Class Reference
The ModulePass which wraps up a CallGraph and the logic to build it.
#include <CallGraph.h>
Public Types
typedef CallGraph::iterator iterator
typedef CallGraph::const_iterator const_iterator
Public Member Functions
CallGraphWrapperPass ()
virtual ~CallGraphWrapperPass ()
const CallGraph & getCallGraph () const
The internal CallGraph around which the rest of this interface is wrapped.
CallGraph & getCallGraph ()
Module & getModule () const
Returns the module the call graph corresponds to.
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const CallGraphNode * operator[] (const Function *F) const
Returns the call graph node for the provided function.
CallGraphNode * operator[] (const Function *F)
Returns the call graph node for the provided function.
CallGraphNode * getExternalCallingNode () const
Returns the CallGraphNode which is used to represent undetermined calls into the callgraph.
CallGraphNode * getCallsExternalNode () const
Function * removeFunctionFromModule (CallGraphNode *CGN)
Unlink the function from this module, returning it.
CallGraphNode * getOrInsertFunction (const Function *F)
Similar to operator[], but this will insert a new CallGraphNode for F if one does not already exist.
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnModule (Module &M) override
void releaseMemory () override
void print (raw_ostream &o, const Module *) const override
void dump () const
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
The ModulePass which wraps up a CallGraph and the logic to build it.
This class exposes both the interface to the call graph container and the module pass which runs over a module of IR and produces the call graph. The call graph interface is entirelly a wrapper around a CallGraph object which is stored internally for each module.
Definition at line 314 of file CallGraph.h.
Member Typedef Documentation
const_iterator
typedef CallGraph::const_iterator llvm::CallGraphWrapperPass::const_iterator
Definition at line 329 of file CallGraph.h.
iterator
typedef CallGraph::iterator llvm::CallGraphWrapperPass::iterator
Definition at line 328 of file CallGraph.h.
Constructor & Destructor Documentation
CallGraphWrapperPass()
CallGraphWrapperPass::CallGraphWrapperPass ()
Definition at line 249 of file CallGraph.cpp.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::initializeCallGraphWrapperPassPass(), and llvm::ModulePass::ModulePass().
~CallGraphWrapperPass()
CallGraphWrapperPass::~CallGraphWrapperPass () virtual
Definition at line 253 of file CallGraph.cpp.
Member Function Documentation
begin() [1/2]
iterator llvm::CallGraphWrapperPass::begin () inline
Definition at line 334 of file CallGraph.h.
begin() [2/2]
const_iterator llvm::CallGraphWrapperPass::begin () const inline
Definition at line 336 of file CallGraph.h.
dump()
void CallGraphWrapperPass::dump () const
Definition at line 283 of file CallGraph.cpp.
References llvm::dbgs(), and print().
end() [1/2]
iterator llvm::CallGraphWrapperPass::end () inline
Definition at line 335 of file CallGraph.h.
end() [2/2]
const_iterator llvm::CallGraphWrapperPass::end () const inline
Definition at line 337 of file CallGraph.h.
getAnalysisUsage()
void CallGraphWrapperPass::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 255 of file CallGraph.cpp.
References llvm::AnalysisUsage::setPreservesAll().
getCallGraph() [1/2]
CallGraph & llvm::CallGraphWrapperPass::getCallGraph () inline
Definition at line 326 of file CallGraph.h.
getCallGraph() [2/2]
const CallGraph & llvm::CallGraphWrapperPass::getCallGraph () const inline
The internal CallGraph around which the rest of this interface is wrapped.
Definition at line 325 of file CallGraph.h.
getCallsExternalNode()
CallGraphNode * llvm::CallGraphWrapperPass::getCallsExternalNode () const inline
Definition at line 353 of file CallGraph.h.
getExternalCallingNode()
CallGraphNode * llvm::CallGraphWrapperPass::getExternalCallingNode () const inline
Returns the CallGraphNode which is used to represent undetermined calls into the callgraph.
Definition at line 349 of file CallGraph.h.
getModule()
Module & llvm::CallGraphWrapperPass::getModule () const inline
Returns the module the call graph corresponds to.
Definition at line 332 of file CallGraph.h.
getOrInsertFunction()
CallGraphNode * llvm::CallGraphWrapperPass::getOrInsertFunction (const Function * F) inline
Similar to operator[], but this will insert a new CallGraphNode for F if one does not already exist.
Definition at line 374 of file CallGraph.h.
References F.
operator[]() [1/2]
CallGraphNode * llvm::CallGraphWrapperPass::operator[] (const Function * F) inline
Returns the call graph node for the provided function.
Definition at line 345 of file CallGraph.h.
References F.
operator[]() [2/2]
const CallGraphNode * llvm::CallGraphWrapperPass::operator[] (const Function * F) const inline
Returns the call graph node for the provided function.
Definition at line 340 of file CallGraph.h.
References F.
print()
void CallGraphWrapperPass::print (raw_ostream & O, const Module * M) const override virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 272 of file CallGraph.cpp.
Referenced by dump().
releaseMemory()
void llvm::CallGraphWrapperPass::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
removeFunctionFromModule()
Function * llvm::CallGraphWrapperPass::removeFunctionFromModule (CallGraphNode * CGN) inline
Unlink the function from this module, returning it.
Because this removes the function from the module, the call graph node is destroyed. This is only valid if the function does not call any other functions (ie, there are no edges in it's CGN). The easiest way to do this is to dropAllReferences before calling this.
Definition at line 368 of file CallGraph.h.
runOnModule()
bool CallGraphWrapperPass::runOnModule (Module & M) override virtual
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
Implements llvm::ModulePass.
Definition at line 259 of file CallGraph.cpp.
Member Data Documentation
ID
char llvm::CallGraphWrapperPass::ID static
Definition at line 318 of file CallGraph.h.
Referenced by CallGraphWrapperPass().
The documentation for this class was generated from the following files:
CallGraph.h
CallGraph.cpp