LLVM: llvm::coverage::RawCoverageMappingReader Class Reference
LLVM API Documentation
llvm::coverage::RawCoverageMappingReader Class Reference
Reader for the raw coverage mapping data.
#include <CoverageMappingReader.h>
Public Member Functions
RawCoverageMappingReader (StringRef FunctionName, StringRef MappingData, ArrayRef< StringRef > TranslationUnitFilenames, std::vector< StringRef > &Filenames, std::vector< CounterExpression > &Expressions, std::vector< CounterMappingRegion > &MappingRegions)
std::error_code read (CoverageMappingRecord &Record)
Additional Inherited Members
Protected Member Functions inherited from llvm::coverage::RawCoverageReader
std::error_code error (std::error_code EC)
Return the error code.
std::error_code success ()
Clear the current error code and return a successful one.
RawCoverageReader (StringRef Data)
std::error_code readULEB128 (uint64_t &Result)
std::error_code readIntMax (uint64_t &Result, uint64_t MaxPlus1)
std::error_code readSize (uint64_t &Result)
std::error_code readString (StringRef &Result)
Protected Attributes inherited from llvm::coverage::RawCoverageReader
StringRef Data
Detailed Description
Reader for the raw coverage mapping data.
Definition at line 106 of file CoverageMappingReader.h.
Constructor & Destructor Documentation
RawCoverageMappingReader()
llvm::coverage::RawCoverageMappingReader::RawCoverageMappingReader (StringRef FunctionName, StringRef MappingData, ArrayRef< StringRef > TranslationUnitFilenames, std::vector< StringRef > & Filenames, std::vector< CounterExpression > & Expressions, std::vector< CounterMappingRegion > & MappingRegions) inline
Definition at line 119 of file CoverageMappingReader.h.
References llvm::coverage::RawCoverageReader::RawCoverageReader().
Member Function Documentation
read()
std::error_code RawCoverageMappingReader::read (CoverageMappingRecord & Record)
Definition at line 224 of file CoverageMappingReader.cpp.
References llvm::coverage::CounterMappingRegion::ExpansionRegion, I, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::coverage::RawCoverageReader::readIntMax(), llvm::coverage::RawCoverageReader::readSize(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::coverage::CounterExpression::Subtract, and llvm::coverage::RawCoverageReader::success().
Referenced by llvm::coverage::ObjectFileCoverageMappingReader::readNextRecord().
The documentation for this class was generated from the following files:
CoverageMappingReader.h
CoverageMappingReader.cpp