LLVM: llvm::PrintRegUnit Class Reference
LLVM API Documentation
llvm::PrintRegUnit Class Reference
#include <TargetRegisterInfo.h>
Public Member Functions
PrintRegUnit (unsigned unit, const TargetRegisterInfo *tri)
void print (raw_ostream &) const
Protected Attributes
const TargetRegisterInfo * TRI
unsigned Unit
Detailed Description
PrintRegUnit - Helper class for printing register units on a raw_ostream.
Register units are named after their root registers:
AL - Single root. FP0~ST7 - Dual roots.
Usage: OS << PrintRegUnit(Unit, TRI) << '
';
Definition at line 958 of file TargetRegisterInfo.h.
Constructor & Destructor Documentation
PrintRegUnit()
llvm::PrintRegUnit::PrintRegUnit (unsigned unit, const TargetRegisterInfo * tri) inline
Definition at line 963 of file TargetRegisterInfo.h.
References TRI, and Unit.
Referenced by llvm::PrintVRegOrUnit::PrintVRegOrUnit().
Member Function Documentation
print()
void PrintRegUnit::print (raw_ostream & OS) const
Definition at line 56 of file TargetRegisterInfo.cpp.
References llvm::MCRegUnitRootIterator::isValid(), TRI, and Unit.
Referenced by llvm::operator<<(), and llvm::PrintVRegOrUnit::print().
Member Data Documentation
TRI
const TargetRegisterInfo* llvm::PrintRegUnit::TRI protected
Definition at line 960 of file TargetRegisterInfo.h.
Referenced by print(), llvm::PrintVRegOrUnit::print(), and PrintRegUnit().
Unit
unsigned llvm::PrintRegUnit::Unit protected
Definition at line 961 of file TargetRegisterInfo.h.
Referenced by print(), llvm::PrintVRegOrUnit::print(), and PrintRegUnit().
The documentation for this class was generated from the following files:
TargetRegisterInfo.h
TargetRegisterInfo.cpp