LLVM: llvm::DebugLoc Class Reference
LLVM API Documentation
llvm::DebugLoc Class Reference
#include <DebugLoc.h>
Public Member Functions
DebugLoc ()
DebugLoc (DebugLoc &&X)
DebugLoc (const DebugLoc &X)
DebugLoc & operator= (DebugLoc &&X)
DebugLoc & operator= (const DebugLoc &X)
bool hasTrivialDestructor () const
Check whether this has a trivial destructor.
bool isUnknown () const
isUnknown - Return true if this is an unknown location.
unsigned getLine () const
unsigned getCol () const
MDNode * getScope () const
MDNode * getScope (const LLVMContext &) const
MDNode * getInlinedAt () const
MDNode * getInlinedAt (const LLVMContext &) const
void getScopeAndInlinedAt (MDNode *&Scope, MDNode *&IA) const
getScopeAndInlinedAt - Return both the Scope and the InlinedAt values.
void getScopeAndInlinedAt (MDNode *&Scope, MDNode *&IA, const LLVMContext &) const
MDNode * getScopeNode () const
getScopeNode - Get MDNode for DebugLoc's scope, or null if invalid.
MDNode * getScopeNode (const LLVMContext &) const
DebugLoc getFnDebugLoc () const
DebugLoc getFnDebugLoc (const LLVMContext &) const
MDNode * getAsMDNode () const
MDNode * getAsMDNode (LLVMContext &) const
bool operator== (const DebugLoc &DL) const
bool operator!= (const DebugLoc &DL) const
void dump () const
void dump (const LLVMContext &) const
void print (raw_ostream &OS) const
prints source location /path/to/file.exe:line:col @[inlined at]
void print (const LLVMContext &, raw_ostream &OS) const
Static Public Member Functions
static DebugLoc get (unsigned Line, unsigned Col, MDNode *Scope, MDNode *InlinedAt=nullptr)
static DebugLoc getFromDILocation (MDNode *N)
getFromDILocation - Translate the DILocation quad into a DebugLoc.
static DebugLoc getFromDILexicalBlock (MDNode *N)
getFromDILexicalBlock - Translate the DILexicalBlock into a DebugLoc.
Detailed Description
DebugLoc - Debug location id. This is carried by Instruction, SDNode, and MachineInstr to compactly encode file/line/scope information for an operation.
Definition at line 30 of file DebugLoc.h.
Constructor & Destructor Documentation
DebugLoc() [1/3]
llvm::DebugLoc::DebugLoc () inline
Definition at line 34 of file DebugLoc.h.
Referenced by DebugLoc(), DebugLoc(), dump(), get(), getFnDebugLoc(), getFnDebugLoc(), getFromDILexicalBlock(), getFromDILocation(), operator!=(), operator=(), operator=(), operator==(), and print().
DebugLoc() [2/3]
llvm::DebugLoc::DebugLoc (DebugLoc && X) inline
Definition at line 35 of file DebugLoc.h.
References DebugLoc(), and llvm::X.
DebugLoc() [3/3]
llvm::DebugLoc::DebugLoc (const DebugLoc & X) inline
Definition at line 36 of file DebugLoc.h.
References DebugLoc(), and llvm::X.
Member Function Documentation
dump() [1/2]
void DebugLoc::dump () const
Definition at line 85 of file DebugLoc.cpp.
References llvm::dbgs(), DebugLoc(), dump(), getCol(), getFromDILocation(), getInlinedAt(), getLine(), and isUnknown().
Referenced by dump(), and llvm::SDValue::dump().
dump() [2/2]
void llvm::DebugLoc::dump (const LLVMContext &) const inline
Definition at line 103 of file DebugLoc.h.
References dump().
Referenced by dump().
get()
DebugLoc DebugLoc::get (unsigned Line, unsigned Col, MDNode * Scope, MDNode * InlinedAt = nullptr) static
get - Get a new DebugLoc that corresponds to the specified line/col scope/inline location.
Definition at line 50 of file DebugLoc.cpp.
References DebugLoc(), llvm::MDLocation::get(), llvm::MDNode::getContext(), and getFromDILocation().
Referenced by llvm::InstrEmitter::EmitDbgValue(), llvm::SystemZFrameLowering::emitPrologue(), getFnDebugLoc(), getFromDILexicalBlock(), and updateInlinedAtInfo().
getAsMDNode() [1/2]
MDNode * DebugLoc::getAsMDNode () const
getAsMDNode - This method converts the compressed DebugLoc node into a DILocation compatible MDNode.
getAsMDNode - This method converts the compressed DebugLoc node into a DILocation-compatible MDNode.
Definition at line 67 of file DebugLoc.cpp.
Referenced by updateInlinedAtInfo().
getAsMDNode() [2/2]
MDNode * llvm::DebugLoc::getAsMDNode (LLVMContext &) const inline
Definition at line 97 of file DebugLoc.h.
References getAsMDNode().
Referenced by getAsMDNode().
getCol()
unsigned DebugLoc::getCol () const
Definition at line 21 of file DebugLoc.cpp.
References llvm::DILocation::getColumnNumber().
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginInstruction(), dump(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), print(), llvm::SDNode::print_details(), printDebugLoc(), updateInlinedAtInfo(), and WriteFunction().
getFnDebugLoc() [1/2]
DebugLoc DebugLoc::getFnDebugLoc () const
Definition at line 41 of file DebugLoc.cpp.
References DebugLoc(), get(), llvm::getDISubprogram(), and getScopeNode().
Referenced by llvm::DwarfDebug::beginFunction(), llvm::WinCodeViewLineTables::beginFunction(), and getFnDebugLoc().
getFnDebugLoc() [2/2]
DebugLoc llvm::DebugLoc::getFnDebugLoc (const LLVMContext &) const inline
Definition at line 90 of file DebugLoc.h.
References DebugLoc(), and getFnDebugLoc().
getFromDILexicalBlock()
DebugLoc DebugLoc::getFromDILexicalBlock (MDNode * N) static
getFromDILexicalBlock - Translate the DILexicalBlock into a DebugLoc.
Definition at line 77 of file DebugLoc.cpp.
References DebugLoc(), get(), llvm::DILexicalBlock::getColumnNumber(), llvm::DILexicalBlock::getContext(), llvm::DILexicalBlock::getLineNumber(), and N.
Referenced by llvm::DISubprogram::Verify().
getFromDILocation()
DebugLoc DebugLoc::getFromDILocation (MDNode * N) static
getFromDILocation - Translate the DILocation quad into a DebugLoc.
Definition at line 70 of file DebugLoc.cpp.
References DebugLoc(), and N.
Referenced by dump(), get(), getScopeNode(), LLVMSetCurrentDebugLocation(), print(), llvm::MachineInstr::print(), printDebugLoc(), llvm::DIVariable::printExtendedName(), llvm::Instruction::setMetadata(), updateInlinedAtInfo(), and llvm::DISubprogram::Verify().
getInlinedAt() [1/2]
MDNode * DebugLoc::getInlinedAt () const
getInlinedAt - This returns the InlinedAt pointer for this DebugLoc, or null if invalid or not present.
Definition at line 25 of file DebugLoc.cpp.
References llvm::DILocation::getOrigLocation().
Referenced by dump(), getScopeAndInlinedAt(), getScopeNode(), print(), printDebugLoc(), updateInlinedAtInfo(), and llvm::DISubprogram::Verify().
getInlinedAt() [2/2]
MDNode * llvm::DebugLoc::getInlinedAt (const LLVMContext &) const inline
Definition at line 74 of file DebugLoc.h.
References getInlinedAt().
Referenced by getInlinedAt().
getLine()
unsigned DebugLoc::getLine () const
Definition at line 20 of file DebugLoc.cpp.
References llvm::DILocation::getLineNumber().
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginInstruction(), dump(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), functionHasLines(), print(), llvm::SDNode::print_details(), printDebugLoc(), updateInlinedAtInfo(), and WriteFunction().
getScope() [1/2]
MDNode * DebugLoc::getScope () const
getScope - This returns the scope pointer for this DebugLoc, or null if invalid.
Definition at line 23 of file DebugLoc.cpp.
References llvm::DILocation::getScope().
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginInstruction(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), getScopeAndInlinedAt(), getScopeNode(), print(), llvm::SDNode::print_details(), printDebugLoc(), updateInlinedAtInfo(), and llvm::DISubprogram::Verify().
getScope() [2/2]
MDNode * llvm::DebugLoc::getScope (const LLVMContext &) const inline
Definition at line 69 of file DebugLoc.h.
References getScope().
Referenced by getScope().
getScopeAndInlinedAt() [1/2]
void DebugLoc::getScopeAndInlinedAt (MDNode *& Scope, MDNode *& IA) const
getScopeAndInlinedAt - Return both the Scope and the InlinedAt values.
Return both the Scope and the InlinedAt values.
Definition at line 30 of file DebugLoc.cpp.
References getInlinedAt(), and getScope().
Referenced by llvm::LexicalScopes::findInlinedScope(), llvm::LexicalScopes::findLexicalScope(), getScopeAndInlinedAt(), llvm::DISubprogram::Verify(), and WriteFunction().
getScopeAndInlinedAt() [2/2]
void llvm::DebugLoc::getScopeAndInlinedAt (MDNode *& Scope, MDNode *& IA, const LLVMContext &) const inline
Definition at line 78 of file DebugLoc.h.
References getScopeAndInlinedAt().
getScopeNode() [1/2]
MDNode * DebugLoc::getScopeNode () const
getScopeNode - Get MDNode for DebugLoc's scope, or null if invalid.
Definition at line 35 of file DebugLoc.cpp.
References getFromDILocation(), getInlinedAt(), getScope(), and getScopeNode().
Referenced by llvm::getDISubprogram(), getFnDebugLoc(), and getScopeNode().
getScopeNode() [2/2]
MDNode * llvm::DebugLoc::getScopeNode (const LLVMContext &) const inline
Definition at line 85 of file DebugLoc.h.
References getScopeNode().
Referenced by getScopeNode().
hasTrivialDestructor()
bool llvm::DebugLoc::hasTrivialDestructor () const inline
Check whether this has a trivial destructor.
Definition at line 47 of file DebugLoc.h.
isUnknown()
bool llvm::DebugLoc::isUnknown () const inline
isUnknown - Return true if this is an unknown location.
Definition at line 61 of file DebugLoc.h.
Referenced by llvm::WinCodeViewLineTables::beginFunction(), llvm::DwarfDebug::beginInstruction(), llvm::WinCodeViewLineTables::beginInstruction(), llvm::LexicalScopes::dominates(), dump(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), fixupLineNumbers(), functionHasLines(), llvm::Loop::getStartLoc(), llvm::MachineInstr::isIdenticalTo(), llvm::DiagnosticInfoOptimizationBase::isLocationAvailable(), print(), llvm::MachineInstr::print(), llvm::SDNode::print_details(), printDebugLoc(), llvm::DIVariable::printExtendedName(), llvm::DISubprogram::Verify(), and WriteFunction().
operator!=()
bool llvm::DebugLoc::operator!= (const DebugLoc & DL) const inline
Definition at line 100 of file DebugLoc.h.
References DebugLoc().
operator=() [1/2]
DebugLoc & llvm::DebugLoc::operator= (const DebugLoc & X) inline
Definition at line 41 of file DebugLoc.h.
References DebugLoc(), and llvm::X.
operator=() [2/2]
DebugLoc & llvm::DebugLoc::operator= (DebugLoc && X) inline
Definition at line 37 of file DebugLoc.h.
References DebugLoc(), and llvm::X.
operator==()
bool llvm::DebugLoc::operator== (const DebugLoc & DL) const inline
Definition at line 99 of file DebugLoc.h.
References DebugLoc().
print() [1/2]
void llvm::DebugLoc::print (const LLVMContext & , raw_ostream & OS) const inline
Definition at line 106 of file DebugLoc.h.
References print().
Referenced by print().
print() [2/2]
void DebugLoc::print (raw_ostream & OS) const
prints source location /path/to/file.exe:line:col @[inlined at]
Definition at line 101 of file DebugLoc.cpp.
References DebugLoc(), getCol(), llvm::DIScope::getFilename(), getFromDILocation(), getInlinedAt(), getLine(), getScope(), llvm::DIDescriptor::isScope(), isUnknown(), and print().
Referenced by print(), and printDebugLoc().
The documentation for this class was generated from the following files:
DebugLoc.h
DebugLoc.cpp