LLVM: llvm::RecordStreamer Class Reference
LLVM API Documentation
llvm::RecordStreamer Class Reference
#include <RecordStreamer.h>
Public Types
enum State {
NeverSeen , Global , Defined , DefinedGlobal ,
Used
}
typedef StringMap< State >::const_iterator const_iterator
Public Member Functions
const_iterator begin ()
const_iterator end ()
RecordStreamer (MCContext &Context)
void EmitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI) override
void EmitLabel (MCSymbol *Symbol) override
void EmitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
bool EmitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute) override
EmitSymbolAttribute - Add the given Attribute to Symbol.
void EmitZerofill (const MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
void EmitCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
Public Member Functions inherited from llvm::MCStreamer
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
void setTargetStreamer (MCTargetStreamer *TS)
virtual void reset ()
MCContext & getContext () const
MCTargetStreamer * getTargetStreamer ()
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
unsigned getNumWinFrameInfos ()
ArrayRef< WinEH::FrameInfo * > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
virtual void EmitFileDirective (StringRef Filename)
virtual void EmitIdent (StringRef IdentString)
virtual unsigned EmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, unsigned CUID=0)
virtual void EmitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName)
EmitDwarfLocDirective - This implements the DWARF2.
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
virtual void EmitCFISections (bool EH, bool Debug)
void EmitCFIStartProc (bool IsSimple)
void EmitCFIEndProc ()
virtual void EmitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void EmitCFIDefCfaOffset (int64_t Offset)
virtual void EmitCFIDefCfaRegister (int64_t Register)
virtual void EmitCFIOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void EmitCFIRememberState ()
virtual void EmitCFIRestoreState ()
virtual void EmitCFISameValue (int64_t Register)
virtual void EmitCFIRestore (int64_t Register)
virtual void EmitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void EmitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void EmitCFIEscape (StringRef Values)
virtual void EmitCFISignalFrame ()
virtual void EmitCFIUndefined (int64_t Register)
virtual void EmitCFIRegister (int64_t Register1, int64_t Register2)
virtual void EmitCFIWindowSave ()
virtual void EmitWinCFIStartProc (const MCSymbol *Symbol)
virtual void EmitWinCFIEndProc ()
virtual void EmitWinCFIStartChained ()
virtual void EmitWinCFIEndChained ()
virtual void EmitWinCFIPushReg (unsigned Register)
virtual void EmitWinCFISetFrame (unsigned Register, unsigned Offset)
virtual void EmitWinCFIAllocStack (unsigned Size)
virtual void EmitWinCFISaveReg (unsigned Register, unsigned Offset)
virtual void EmitWinCFISaveXMM (unsigned Register, unsigned Offset)
virtual void EmitWinCFIPushFrame (bool Code)
virtual void EmitWinCFIEndProlog ()
virtual void EmitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except)
virtual void EmitWinEHHandlerData ()
virtual void EmitBundleAlignMode (unsigned AlignPow2)
Set the bundle alignment mode from now on in the section. The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
virtual void EmitBundleLock (bool AlignToEnd)
The following instructions are a bundle-locked group.
virtual void EmitBundleUnlock ()
Ends a bundle-locked group.
void EmitRawText (const Twine &String)
virtual void Flush ()
Flush - Causes any cached state to be written out.
virtual void FinishImpl ()
FinishImpl - Streamer specific finalization.
void Finish ()
Finish - Finish emission of machine code.
virtual bool mayHaveInstructions () const
virtual bool isVerboseAsm () const
virtual bool hasRawTextSupport () const
virtual bool isIntegratedAssemblerRequired () const
virtual void AddComment (const Twine &T)
virtual raw_ostream & GetCommentOS ()
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
virtual void AddBlankLine ()
AddBlankLine - Emit a blank line to a .s file to pretty it up.
MCSectionSubPair getCurrentSection () const
MCSectionSubPair getPreviousSection () const
unsigned GetSymbolOrder (const MCSymbol *Sym) const
virtual void ChangeSection (const MCSection *, const MCExpr *)
void PushSection ()
bool PopSection ()
bool SubSection (const MCExpr *Subsection)
virtual void SwitchSection (const MCSection *Section, const MCExpr *Subsection=nullptr)
void SwitchSectionNoChange (const MCSection *Section, const MCExpr *Subsection=nullptr)
virtual void InitSections (bool NoExecStack)
Create the default sections and set the initial one.
void AssignSection (MCSymbol *Symbol, const MCSection *Section)
virtual void EmitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void EmitAssemblerFlag (MCAssemblerFlag Flag)
EmitAssemblerFlag - Note in the output the specified Flag.
virtual void EmitLinkerOptions (ArrayRef< std::string > Kind)
virtual void EmitDataRegion (MCDataRegionType Kind)
EmitDataRegion - Note in the output the specified region Kind.
virtual void EmitVersionMin (MCVersionMinType, unsigned Major, unsigned Minor, unsigned Update)
EmitVersionMin - Specify the MachO minimum deployment target version.
virtual void EmitThumbFunc (MCSymbol *Func)
virtual void EmitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol)
virtual void EmitSymbolDesc (MCSymbol *Symbol, unsigned DescValue)
virtual void BeginCOFFSymbolDef (const MCSymbol *Symbol)
virtual void EmitCOFFSymbolStorageClass (int StorageClass)
virtual void EmitCOFFSymbolType (int Type)
virtual void EndCOFFSymbolDef ()
EndCOFFSymbolDef - Marks the end of the symbol definition.
virtual void EmitCOFFSectionIndex (MCSymbol const *Symbol)
virtual void EmitCOFFSecRel32 (MCSymbol const *Symbol)
virtual void EmitELFSize (MCSymbol *Symbol, const MCExpr *Value)
virtual void EmitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
virtual void EmitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment)
virtual void EmitTBSSSymbol (const MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment=0)
virtual void EmitBytes (StringRef Data)
virtual void EmitValueImpl (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc())
void EmitValue (const MCExpr *Value, unsigned Size, const SMLoc &Loc=SMLoc())
virtual void EmitIntValue (uint64_t Value, unsigned Size)
virtual void EmitULEB128Value (const MCExpr *Value)
virtual void EmitSLEB128Value (const MCExpr *Value)
void EmitULEB128IntValue (uint64_t Value, unsigned Padding=0)
void EmitSLEB128IntValue (int64_t Value)
void EmitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
virtual void EmitGPRel64Value (const MCExpr *Value)
virtual void EmitGPRel32Value (const MCExpr *Value)
virtual void EmitFill (uint64_t NumBytes, uint8_t FillValue)
virtual void EmitZeros (uint64_t NumBytes)
Emit NumBytes worth of zeros. This function properly handles data in virtual sections.
virtual void EmitValueToAlignment (unsigned ByteAlignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0)
virtual void EmitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit=0)
virtual bool EmitValueToOffset (const MCExpr *Offset, unsigned char Value=0)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCStreamer
MCStreamer (MCContext &Ctx)
virtual void EmitCFIStartProcImpl (MCDwarfFrameInfo &Frame)
virtual void EmitCFIEndProcImpl (MCDwarfFrameInfo &CurFrame)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void EmitWindowsUnwindTables ()
virtual void EmitRawTextImpl (StringRef String)
Detailed Description
Definition at line 16 of file RecordStreamer.h.
Member Typedef Documentation
const_iterator
typedef StringMap<State>::const_iterator llvm::RecordStreamer::const_iterator
Definition at line 28 of file RecordStreamer.h.
Member Enumeration Documentation
State
enum llvm::RecordStreamer::State
Enumerator
NeverSeen
Global
Defined
DefinedGlobal
Used
Definition at line 18 of file RecordStreamer.h.
Constructor & Destructor Documentation
RecordStreamer()
RecordStreamer::RecordStreamer (MCContext & Context)
Definition at line 68 of file RecordStreamer.cpp.
Member Function Documentation
begin()
RecordStreamer::const_iterator RecordStreamer::begin ()
Definition at line 62 of file RecordStreamer.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
EmitAssignment()
void RecordStreamer::EmitAssignment (MCSymbol * Symbol, const MCExpr * Value) override virtual
EmitAssignment - Emit an assignment of Value to Symbol.
This corresponds to an assembler statement such as: symbol = value
The assignment generates no code, but has the side effect of binding the value in the current context. For the assembly streamer, this prints the binding into the .s file.
Parameters
Symbol - The symbol being assigned to.
Value - The value for the symbol.
Reimplemented from llvm::MCStreamer.
Definition at line 80 of file RecordStreamer.cpp.
References llvm::MCStreamer::EmitAssignment().
EmitCommonSymbol()
void RecordStreamer::EmitCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
EmitCommonSymbol - Emit a common symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the symbol if non-zero. This must be a power of 2.
Implements llvm::MCStreamer.
Definition at line 97 of file RecordStreamer.cpp.
EmitInstruction()
void RecordStreamer::EmitInstruction (const MCInst & Inst, const MCSubtargetInfo & STI) override virtual
EmitInstruction - Emit the given Instruction into the current section.
Reimplemented from llvm::MCStreamer.
Definition at line 70 of file RecordStreamer.cpp.
References llvm::MCStreamer::EmitInstruction().
EmitLabel()
void RecordStreamer::EmitLabel (MCSymbol * Symbol) override virtual
EmitLabel - Emit a label for Symbol into the current section.
This corresponds to an assembler statement such as: foo:
Parameters
Symbol - The symbol to emit. A given symbol should only be emitted as a label once, and symbols emitted as a label should never be used in an assignment.
Reimplemented from llvm::MCStreamer.
Definition at line 75 of file RecordStreamer.cpp.
References llvm::MCStreamer::EmitLabel().
EmitSymbolAttribute()
bool RecordStreamer::EmitSymbolAttribute (MCSymbol * Symbol, MCSymbolAttr Attribute) override virtual
EmitSymbolAttribute - Add the given Attribute to Symbol.
Implements llvm::MCStreamer.
Definition at line 85 of file RecordStreamer.cpp.
References llvm::MCSA_Global.
EmitZerofill()
void RecordStreamer::EmitZerofill (const MCSection * Section, MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
EmitZerofill - Emit the zerofill section and an optional symbol.
Parameters
Section - The zerofill section to create and or to put the symbol
Symbol - The zerofill symbol to emit, if non-NULL.
Size - The size of the zerofill symbol.
ByteAlignment - The alignment of the zerofill symbol if non-zero. This must be a power of 2 on some targets.
Implements llvm::MCStreamer.
Definition at line 92 of file RecordStreamer.cpp.
end()
RecordStreamer::const_iterator RecordStreamer::end ()
Definition at line 66 of file RecordStreamer.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
The documentation for this class was generated from the following files:
RecordStreamer.h
RecordStreamer.cpp