LLVM: llvm::DIEAbbrev Class Reference
LLVM API Documentation
llvm::DIEAbbrev Class Reference
#include <DIE.h>
Public Member Functions
DIEAbbrev (dwarf::Tag T, bool C)
dwarf::Tag getTag () const
unsigned getNumber () const
bool hasChildren () const
const SmallVectorImpl< DIEAbbrevData > & getData () const
void setChildrenFlag (bool hasChild)
void setNumber (unsigned N)
void AddAttribute (dwarf::Attribute Attribute, dwarf::Form Form)
void Profile (FoldingSetNodeID &ID) const
void Emit (AsmPrinter *AP) const
void print (raw_ostream &O)
void dump ()
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Detailed Description
DIEAbbrev - Dwarf abbreviation, describes the organization of a debug information object.
Definition at line 56 of file DIE.h.
Constructor & Destructor Documentation
DIEAbbrev()
llvm::DIEAbbrev::DIEAbbrev (dwarf::Tag T, bool C) inline
Definition at line 76 of file DIE.h.
References T.
Member Function Documentation
AddAttribute()
void llvm::DIEAbbrev::AddAttribute (dwarf::Attribute Attribute, dwarf::Form Form) inline
AddAttribute - Adds another set of attribute information to the abbreviation.
Definition at line 88 of file DIE.h.
dump()
void DIEAbbrev::dump ()
Definition at line 106 of file DIE.cpp.
References llvm::dbgs(), and print().
Emit()
void DIEAbbrev::Emit (AsmPrinter * AP) const
Emit - Print the abbreviation using the specified asm printer.
Definition at line 63 of file DIE.cpp.
References llvm::dwarf::AttributeString(), llvm::dwarf::ChildrenString(), llvm::AsmPrinter::EmitULEB128(), llvm::dwarf::FormEncodingString(), llvm::DIEAbbrevData::getAttribute(), llvm::DIEAbbrevData::getForm(), N, and llvm::dwarf::TagString().
getData()
const SmallVectorImpl< DIEAbbrevData > & llvm::DIEAbbrev::getData () const inline
Definition at line 82 of file DIE.h.
Referenced by llvm::DwarfFile::computeSizeAndOffset(), llvm::DwarfDebug::emitDIE(), llvm::DIE::findAttribute(), and getDIEStringAttr().
getNumber()
unsigned llvm::DIEAbbrev::getNumber () const inline
Definition at line 80 of file DIE.h.
Referenced by llvm::DwarfFile::assignAbbrevNumber(), and llvm::DwarfDebug::emitDIE().
getTag()
dwarf::Tag llvm::DIEAbbrev::getTag () const inline
Definition at line 79 of file DIE.h.
Referenced by llvm::DwarfDebug::emitDIE().
hasChildren()
bool llvm::DIEAbbrev::hasChildren () const inline
Definition at line 81 of file DIE.h.
Referenced by llvm::DwarfFile::computeSizeAndOffset(), and llvm::DwarfDebug::emitDIE().
print()
void DIEAbbrev::print (raw_ostream & O)
Definition at line 89 of file DIE.cpp.
References llvm::dwarf::AttributeString(), llvm::dwarf::ChildrenString(), llvm::format(), llvm::dwarf::FormEncodingString(), N, and llvm::dwarf::TagString().
Referenced by dump().
Profile()
void DIEAbbrev::Profile (FoldingSetNodeID & ID) const
Profile - Used to gather unique data for the abbreviation folding set.
Definition at line 52 of file DIE.cpp.
References N.
setChildrenFlag()
void llvm::DIEAbbrev::setChildrenFlag (bool hasChild) inline
Definition at line 83 of file DIE.h.
setNumber()
void llvm::DIEAbbrev::setNumber (unsigned N) inline
Definition at line 84 of file DIE.h.
References N.
Referenced by llvm::DwarfFile::assignAbbrevNumber().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp