LLVM: llvm::Loop Class Reference
LLVM API Documentation
llvm::Loop Class Reference
#include <LoopInfo.h>
Public Member Functions
Loop ()
bool isLoopInvariant (Value *V) const
bool hasLoopInvariantOperands (Instruction *I) const
bool makeLoopInvariant (Value *V, bool &Changed, Instruction *InsertPt=nullptr) const
bool makeLoopInvariant (Instruction *I, bool &Changed, Instruction *InsertPt=nullptr) const
PHINode * getCanonicalInductionVariable () const
bool isLCSSAForm (DominatorTree &DT) const
isLCSSAForm - Return true if the Loop is in LCSSA form
bool isLoopSimplifyForm () const
bool isSafeToClone () const
isSafeToClone - Return true if the loop body is safe to clone in practice.
bool isAnnotatedParallel () const
MDNode * getLoopID () const
void setLoopID (MDNode *LoopID) const
bool hasDedicatedExits () const
void getUniqueExitBlocks (SmallVectorImpl< BasicBlock * > &ExitBlocks) const
BasicBlock * getUniqueExitBlock () const
void dump () const
DebugLoc getStartLoc () const
Return the debug location of the start of this loop. This looks for a BB terminating instruction with a known debug location by looking at the preheader and header blocks. If it cannot find a terminating instruction with location information, it returns an unknown location.
Public Member Functions inherited from llvm::LoopBase< BasicBlock, Loop >
~LoopBase ()
unsigned getLoopDepth () const
BasicBlock * getHeader () const
Loop * getParentLoop () const
void setParentLoop (Loop *L)
setParentLoop is a raw interface for bypassing addChildLoop.
bool contains (const Loop *L) const
const std::vector< Loop * > & getSubLoops () const
std::vector< Loop * > & getSubLoopsVector ()
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
const std::vector< BasicBlock * > & getBlocks () const
block_iterator block_begin () const
block_iterator block_end () const
unsigned getNumBlocks () const
getNumBlocks - Get the number of blocks in this loop in constant time.
bool isLoopExiting (const BasicBlock *BB) const
unsigned getNumBackEdges () const
void getExitingBlocks (SmallVectorImpl< BasicBlock * > &ExitingBlocks) const
BasicBlock * getExitingBlock () const
void getExitBlocks (SmallVectorImpl< BasicBlock * > &ExitBlocks) const
BasicBlock * getExitBlock () const
void getExitEdges (SmallVectorImpl< Edge > &ExitEdges) const
getExitEdges - Return all pairs of (inside_block,outside_block).
BasicBlock * getLoopPreheader () const
BasicBlock * getLoopPredecessor () const
BasicBlock * getLoopLatch () const
void getLoopLatches (SmallVectorImpl< BasicBlock * > &LoopLatches) const
void addBasicBlockToLoop (BasicBlock *NewBB, LoopInfoBase< BasicBlock, Loop > &LI)
void replaceChildLoopWith (Loop *OldChild, Loop *NewChild)
void addChildLoop (Loop *NewChild)
Loop * removeChildLoop (iterator I)
void addBlockEntry (BasicBlock *BB)
void reverseBlock (unsigned from)
reverseBlocks - interface to reverse Blocks[from, end of loop] in this loop
void reserveBlocks (unsigned size)
reserveBlocks- interface to do reserve() for Blocks
void moveToHeader (BasicBlock *BB)
void removeBlockFromLoop (BasicBlock *BB)
void verifyLoop () const
verifyLoop - Verify loop structure
void verifyLoopNest (DenseSet< const Loop * > *Loops) const
verifyLoop - Verify loop structure of this loop and all nested loops.
void print (raw_ostream &OS, unsigned Depth=0) const
Friends
class LoopInfoBase< BasicBlock, Loop >
Additional Inherited Members
Public Types inherited from llvm::LoopBase< BasicBlock, Loop >
typedef std::vector< Loop * >::const_iterator iterator
typedef std::vector< Loop * >::const_reverse_iterator reverse_iterator
typedef std::vector< BasicBlock * >::const_iterator block_iterator
typedef std::pair< const BasicBlock *, const BasicBlock * > Edge
Edge type.
Detailed Description
Definition at line 353 of file LoopInfo.h.
Constructor & Destructor Documentation
Loop()
llvm::Loop::Loop () inline
Definition at line 355 of file LoopInfo.h.
Referenced by isLoopInvariant().
Member Function Documentation
dump()
void Loop::dump () const
Definition at line 411 of file LoopInfo.cpp.
References llvm::dbgs(), and llvm::LoopBase< BasicBlock, Loop >::print().
getCanonicalInductionVariable()
PHINode * Loop::getCanonicalInductionVariable () const
getCanonicalInductionVariable - Check to see if the loop has a canonical induction variable: an integer recurrence that starts at 0 and increments by one each time through the loop. If so, return the phi node that corresponds to it.
The IndVarSimplify pass transforms loops to have a canonical induction variable.
Definition at line 142 of file LoopInfo.cpp.
References llvm::cast(), llvm::LoopBase< BasicBlock, Loop >::contains(), llvm::dyn_cast(), llvm::LoopBase< BasicBlock, Loop >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), H, I, llvm::isa(), llvm::pred_begin(), llvm::pred_end(), and std::swap().
getLoopID()
MDNode * Loop::getLoopID () const
Return the llvm.loop loop id metadata node for this loop if it is present.
If this loop contains the same llvm.loop metadata on each branch to the header then the node is returned. If any latch instruction does not contain llvm.loop or or if multiple latches contain different nodes then 0 is returned.
Definition at line 235 of file LoopInfo.cpp.
References llvm::LoopBase< BasicBlock, Loop >::block_begin(), llvm::LoopBase< BasicBlock, Loop >::block_end(), llvm::LoopBase< BasicBlock, Loop >::getHeader(), llvm::LoopBase< BasicBlock, Loop >::getLoopLatch(), llvm::Instruction::getMetadata(), llvm::MDNode::getNumOperands(), llvm::TerminatorInst::getNumSuccessors(), llvm::MDNode::getOperand(), llvm::TerminatorInst::getSuccessor(), llvm::BasicBlock::getTerminator(), H, I, isLoopSimplifyForm(), and LoopMDName.
Referenced by CloneLoopBlocks(), GetUnrollMetadata(), isAnnotatedParallel(), and SetLoopAlreadyUnrolled().
getStartLoc()
DebugLoc llvm::Loop::getStartLoc () const inline
Return the debug location of the start of this loop. This looks for a BB terminating instruction with a known debug location by looking at the preheader and header blocks. If it cannot find a terminating instruction with location information, it returns an unknown location.
Definition at line 461 of file LoopInfo.h.
References llvm::Instruction::getDebugLoc(), llvm::LoopBase< BasicBlock, Loop >::getHeader(), llvm::LoopBase< BasicBlock, Loop >::getLoopPreheader(), llvm::BasicBlock::getTerminator(), and llvm::DebugLoc::isUnknown().
Referenced by llvm::UnrollLoop().
getUniqueExitBlock()
BasicBlock * Loop::getUniqueExitBlock () const
getUniqueExitBlock - If getUniqueExitBlocks would return exactly one block, return that block. Otherwise return null.
Definition at line 402 of file LoopInfo.cpp.
References getUniqueExitBlocks(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by ConnectProlog(), and llvm::UnrollRuntimeLoopProlog().
getUniqueExitBlocks()
void Loop::getUniqueExitBlocks (SmallVectorImpl< BasicBlock * > & ExitBlocks) const
getUniqueExitBlocks - Return all unique successor blocks of this loop. These are the blocks outside of the current loop which are branched to. This assumes that loop exits are in canonical form.
Definition at line 354 of file LoopInfo.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::LoopBase< BasicBlock, Loop >::block_begin(), llvm::LoopBase< BasicBlock, Loop >::block_end(), llvm::SmallVectorImpl< T >::clear(), llvm::LoopBase< BasicBlock, Loop >::contains(), llvm::SmallVectorTemplateCommon< T, typename >::end(), hasDedicatedExits(), I, llvm::pred_begin(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::succ_begin(), and llvm::succ_end().
Referenced by getUniqueExitBlock().
hasDedicatedExits()
bool Loop::hasDedicatedExits () const
hasDedicatedExits - Return true if no exit block for the loop has a predecessor that is outside the loop.
Definition at line 335 of file LoopInfo.cpp.
References llvm::LoopBase< BasicBlock, Loop >::contains(), llvm::LoopBase< BasicBlock, Loop >::getExitBlocks(), llvm::pred_begin(), llvm::pred_end(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by getUniqueExitBlocks(), and isLoopSimplifyForm().
hasLoopInvariantOperands()
bool Loop::hasLoopInvariantOperands (Instruction * I) const
hasLoopInvariantOperands - Return true if all the operands of the specified instruction are loop invariant.
Definition at line 70 of file LoopInfo.cpp.
References I, and isLoopInvariant().
isAnnotatedParallel()
bool Loop::isAnnotatedParallel () const
Returns true if the loop is annotated parallel.
A parallel loop can be assumed to not contain any dependencies between iterations by the compiler. That is, any loop-carried dependency checking can be skipped completely when parallelizing the loop on the target machine. Thus, if the parallel loop information originates from the programmer, e.g. via the OpenMP parallel for pragma, it is the programmer's responsibility to ensure there are no loop-carried dependencies. The final execution order of the instructions across iterations is not guaranteed, thus, the end result might or might not implement actual concurrent execution of instructions across multiple iterations.
Definition at line 289 of file LoopInfo.cpp.
References llvm::LoopBase< BasicBlock, Loop >::block_begin(), llvm::LoopBase< BasicBlock, Loop >::block_end(), getLoopID(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), and llvm::LLVMContext::MD_mem_parallel_loop_access.
isLCSSAForm()
bool Loop::isLCSSAForm (DominatorTree & DT) const
isLCSSAForm - Return true if the Loop is in LCSSA form
Definition at line 179 of file LoopInfo.cpp.
References llvm::BasicBlock::begin(), llvm::LoopBase< BasicBlock, Loop >::block_begin(), llvm::LoopBase< BasicBlock, Loop >::block_end(), llvm::cast(), llvm::LoopBase< BasicBlock, Loop >::contains(), llvm::dyn_cast(), llvm::BasicBlock::end(), llvm::Instruction::getParent(), I, llvm::DominatorTree::isReachableFromEntry(), and P.
Referenced by llvm::formLCSSA().
isLoopInvariant()
bool Loop::isLoopInvariant (Value * V) const
isLoopInvariant - Return true if the specified value is loop invariant
Definition at line 62 of file LoopInfo.cpp.
References contains(), llvm::dyn_cast(), I, isLoopInvariant(), and Loop().
Referenced by getStrideFromPointer(), hasLoopInvariantOperands(), isLoopInvariant(), and makeLoopInvariant().
isLoopSimplifyForm()
bool Loop::isLoopSimplifyForm () const
isLoopSimplifyForm - Return true if the Loop is in the form that the LoopSimplify form transforms loops to, which is sometimes called normal form.
Definition at line 206 of file LoopInfo.cpp.
References llvm::LoopBase< BasicBlock, Loop >::getLoopLatch(), llvm::LoopBase< BasicBlock, Loop >::getLoopPreheader(), and hasDedicatedExits().
Referenced by getLoopID(), isSimplifiedLoopNest(), setLoopID(), and llvm::UnrollRuntimeLoopProlog().
isSafeToClone()
bool Loop::isSafeToClone () const
isSafeToClone - Return true if the loop body is safe to clone in practice.
isSafeToClone - Return true if the loop body is safe to clone in practice. Routines that reform the loop CFG and split edges often fail on indirectbr.
Definition at line 214 of file LoopInfo.cpp.
References llvm::LoopBase< BasicBlock, Loop >::block_begin(), llvm::LoopBase< BasicBlock, Loop >::block_end(), llvm::dyn_cast(), I, and llvm::isa().
Referenced by llvm::UnrollLoop().
makeLoopInvariant() [1/2]
bool Loop::makeLoopInvariant (Instruction * I, bool & Changed, Instruction * InsertPt = nullptr) const
makeLoopInvariant - If the given instruction is inside of the loop and it can be hoisted, do so to make it trivially loop-invariant. Return true if the instruction after any hoisting is loop invariant. This function can be used as a slightly more aggressive replacement for isLoopInvariant.
If InsertPt is specified, it is the point to hoist instructions to. If null, the terminator of the loop preheader is used.
Definition at line 103 of file LoopInfo.cpp.
References Changed, llvm::LoopBase< BasicBlock, Loop >::getLoopPreheader(), llvm::BasicBlock::getTerminator(), I, llvm::isa(), isLoopInvariant(), llvm::isSafeToSpeculativelyExecute(), and makeLoopInvariant().
makeLoopInvariant() [2/2]
bool Loop::makeLoopInvariant (Value * V, bool & Changed, Instruction * InsertPt = nullptr) const
makeLoopInvariant - If the given value is an instruction inside of the loop and it can be hoisted, do so to make it trivially loop-invariant. Return true if the value after any hoisting is loop invariant. This function can be used as a slightly more aggressive replacement for isLoopInvariant.
If InsertPt is specified, it is the point to hoist instructions to. If null, the terminator of the loop preheader is used.
makeLoopInvariant - If the given value is an instruciton inside of the loop and it can be hoisted, do so to make it trivially loop-invariant. Return true if the value after any hoisting is loop invariant. This function can be used as a slightly more aggressive replacement for isLoopInvariant.
If InsertPt is specified, it is the point to hoist instructions to. If null, the terminator of the loop preheader is used.
Definition at line 87 of file LoopInfo.cpp.
References Changed, llvm::dyn_cast(), I, and makeLoopInvariant().
Referenced by FindLIVLoopCondition(), makeLoopInvariant(), makeLoopInvariant(), and simplifyOneLoop().
setLoopID()
void Loop::setLoopID (MDNode * LoopID) const
Set the llvm.loop loop id metadata for this loop.
The LoopID metadata node will be added to each terminator instruction in the loop that branches to the loop header.
The LoopID metadata node should have one or more operands and the first operand should should be the node itself.
Definition at line 269 of file LoopInfo.cpp.
References llvm::LoopBase< BasicBlock, Loop >::block_begin(), llvm::LoopBase< BasicBlock, Loop >::block_end(), llvm::LoopBase< BasicBlock, Loop >::getHeader(), llvm::LoopBase< BasicBlock, Loop >::getLoopLatch(), llvm::MDNode::getNumOperands(), llvm::TerminatorInst::getNumSuccessors(), llvm::MDNode::getOperand(), llvm::TerminatorInst::getSuccessor(), llvm::BasicBlock::getTerminator(), H, I, isLoopSimplifyForm(), LoopMDName, and llvm::Instruction::setMetadata().
Referenced by CloneLoopBlocks(), and SetLoopAlreadyUnrolled().
Friends And Related Symbol Documentation
LoopInfoBase< BasicBlock, Loop >
friend class LoopInfoBase< BasicBlock, Loop > friend
Definition at line 461 of file LoopInfo.h.
The documentation for this class was generated from the following files:
LoopInfo.h
LoopInfo.cpp