LLVM: llvm::JumpInstrTables Class Reference
LLVM API Documentation
llvm::JumpInstrTables Class Reference
#include <JumpInstrTables.h>
Public Member Functions
JumpInstrTables ()
JumpInstrTables (JumpTable::JumpTableType JTT)
virtual ~JumpInstrTables ()
bool runOnModule (Module &M) override
const char * getPassName () const override
void getAnalysisUsage (AnalysisUsage &AU) const override
Function * insertEntry (Module &M, Function *Target)
bool hasTable (FunctionType *FunTy)
Checks to see if there is already a table for the given FunctionType.
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Member Functions
static FunctionType * transformType (JumpTable::JumpTableType JTT, FunctionType *FunTy)
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Static Public Attributes
static char ID = 0
Detailed Description
A class to manage a set of jump tables indexed on function type. It looks at each function in the module to find all the functions that have the jumptable attribute set. For each such function, it creates a new jump-instruction-table function and stores the mapping in the ImmutablePass JumpInstrTableInfo.
These special functions get lowered in AsmPrinter to assembly of the form:
///   .globl f
///   .type f,@function
///   .align 8,0x90
/// f:
///   jmp f_orig@PLT
///
Support for an architecture depends on three functions in TargetInstrInfo: getUnconditionalBranch, getTrap, and getJumpInstrTableEntryBound. AsmPrinter uses these to generate the appropriate instructions for the jump statement (an unconditional branch) and for padding to make the table have a size that is a power of two. This padding uses a trap instruction to ensure that calls to this area halt the program. The default implementations of these functions call llvm_unreachable, except for getJumpInstrTableEntryBound, which returns 0 by default.
Definition at line 50 of file JumpInstrTables.h.
Constructor & Destructor Documentation
JumpInstrTables() [1/2]
JumpInstrTables::JumpInstrTables ()
Definition at line 145 of file JumpInstrTables.cpp.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::initializeJumpInstrTablesPass(), and llvm::ModulePass::ModulePass().
JumpInstrTables() [2/2]
JumpInstrTables::JumpInstrTables (JumpTable::JumpTableType JTT)
Definition at line 151 of file JumpInstrTables.cpp.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::initializeJumpInstrTablesPass(), and llvm::ModulePass::ModulePass().
~JumpInstrTables()
JumpInstrTables::~JumpInstrTables () virtual
Definition at line 156 of file JumpInstrTables.cpp.
Member Function Documentation
getAnalysisUsage()
void JumpInstrTables::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 158 of file JumpInstrTables.cpp.
References llvm::AnalysisUsage::addRequired().
getPassName()
const char * llvm::JumpInstrTables::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 58 of file JumpInstrTables.h.
hasTable()
bool JumpInstrTables::hasTable (FunctionType * FunTy)
Checks to see if there is already a table for the given FunctionType.
Definition at line 191 of file JumpInstrTables.cpp.
References transformType().
insertEntry()
Function * JumpInstrTables::insertEntry (Module & M, Function * Target)
Creates a jump-instruction table function for the Target and adds it to the tables.
Definition at line 162 of file JumpInstrTables.cpp.
References llvm::Function::Create(), llvm::GlobalValue::ExternalLinkage, llvm::GlobalObject::setSection(), and transformType().
Referenced by runOnModule().
runOnModule()
bool JumpInstrTables::runOnModule (Module & M) override virtual
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
Implements llvm::ModulePass.
Definition at line 252 of file JumpInstrTables.cpp.
References llvm::Module::aliases(), llvm::dyn_cast(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Pass::getAnalysis(), insertEntry(), and llvm::Attribute::JumpTable.
transformType()
FunctionType * JumpInstrTables::transformType (JumpTable::JumpTableType JTT, FunctionType * FunTy) static
Maps the function into a subset of function types, depending on the jump-instruction table style selected from JumpTableTypes in JumpInstrTables.cpp. The choice of mapping determines the number of jump-instruction tables generated by this pass. E.g., the simplest mapping converts every function type into void f(); so, all functions end up in a single table.
Definition at line 196 of file JumpInstrTables.cpp.
References llvm::JumpTable::Arity, llvm::JumpTable::Full, llvm::FunctionType::get(), llvm::Type::getContext(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), llvm::FunctionType::getNumParams(), llvm::Type::getVoidTy(), llvm::isa(), llvm::FunctionType::isVarArg(), llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), llvm::JumpTable::Simplified, and llvm::JumpTable::Single.
Referenced by hasTable(), and insertEntry().
Member Data Documentation
ID
char JumpInstrTables::ID = 0 static
Definition at line 52 of file JumpInstrTables.h.
Referenced by JumpInstrTables(), and JumpInstrTables().
The documentation for this class was generated from the following files:
JumpInstrTables.h
JumpInstrTables.cpp