LLVM: llvm::AArch64InstrInfo Class Reference
LLVM API Documentation
llvm::AArch64InstrInfo Class Reference
#include <AArch64InstrInfo.h>
Public Member Functions
AArch64InstrInfo (const AArch64Subtarget &STI)
const AArch64RegisterInfo & getRegisterInfo () const
unsigned GetInstSizeInBytes (const MachineInstr *MI) const
bool isAsCheapAsAMove (const MachineInstr *MI) const override
bool isCoalescableExtInstr (const MachineInstr &MI, unsigned &SrcReg, unsigned &DstReg, unsigned &SubIdx) const override
bool areMemAccessesTriviallyDisjoint (MachineInstr *MIa, MachineInstr *MIb, AliasAnalysis *AA=nullptr) const override
unsigned isLoadFromStackSlot (const MachineInstr *MI, int &FrameIndex) const override
unsigned isStoreToStackSlot (const MachineInstr *MI, int &FrameIndex) const override
bool hasShiftedReg (const MachineInstr *MI) const
Return true if this is this instruction has a non-zero immediate.
bool hasExtendedReg (const MachineInstr *MI) const
Return true if this is this instruction has a non-zero immediate.
bool isGPRZero (const MachineInstr *MI) const
Does this instruction set its full destination register to zero?
bool isGPRCopy (const MachineInstr *MI) const
Does this instruction rename a GPR without modifying bits?
bool isFPRCopy (const MachineInstr *MI) const
Does this instruction rename an FPR without modifying bits?
bool isScaledAddr (const MachineInstr *MI) const
bool isLdStPairSuppressed (const MachineInstr *MI) const
Check all MachineMemOperands for a hint to suppress pairing.
void suppressLdStPair (MachineInstr *MI) const
Hint that pairing the given load or store is unprofitable.
bool getLdStBaseRegImmOfs (MachineInstr *LdSt, unsigned &BaseReg, unsigned &Offset, const TargetRegisterInfo *TRI) const override
bool getLdStBaseRegImmOfsWidth (MachineInstr *LdSt, unsigned &BaseReg, int &Offset, int &Width, const TargetRegisterInfo *TRI) const
bool enableClusterLoads () const override
bool shouldClusterLoads (MachineInstr *FirstLdSt, MachineInstr *SecondLdSt, unsigned NumLoads) const override
bool shouldScheduleAdjacent (MachineInstr *First, MachineInstr *Second) const override
MachineInstr * emitFrameIndexDebugValue (MachineFunction &MF, int FrameIx, uint64_t Offset, const MDNode *Var, const MDNode *Expr, DebugLoc DL) const
void copyPhysRegTuple (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc, unsigned Opcode, llvm::ArrayRef< unsigned > Indices) const
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const override
MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, int FrameIndex) const override
bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify=false) const override
unsigned RemoveBranch (MachineBasicBlock &MBB) const override
unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const override
bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const override
bool canInsertSelect (const MachineBasicBlock &, const SmallVectorImpl< MachineOperand > &Cond, unsigned, unsigned, int &, int &, int &) const override
void insertSelect (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DstReg, const SmallVectorImpl< MachineOperand > &Cond, unsigned TrueReg, unsigned FalseReg) const override
void getNoopForMachoTarget (MCInst &NopInst) const override
bool analyzeCompare (const MachineInstr *MI, unsigned &SrcReg, unsigned &SrcReg2, int &CmpMask, int &CmpValue) const override
bool optimizeCompareInstr (MachineInstr *CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo *MRI) const override
bool optimizeCondBranch (MachineInstr *MI) const override
Replace csincr-branch sequence by simple conditional branch.
bool hasPattern (MachineInstr &Root, SmallVectorImpl< MachineCombinerPattern::MC_PATTERN > &Pattern) const override
void genAlternativeCodeSequence (MachineInstr &Root, MachineCombinerPattern::MC_PATTERN P, SmallVectorImpl< MachineInstr * > &InsInstrs, SmallVectorImpl< MachineInstr * > &DelInstrs, DenseMap< unsigned, unsigned > &InstrIdxForVirtReg) const override
bool useMachineCombiner () const override
useMachineCombiner - AArch64 supports MachineCombiner
bool expandPostRAPseudo (MachineBasicBlock::iterator MI) const override
virtual MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, MachineInstr *LoadMI) const
Detailed Description
Definition at line 30 of file AArch64InstrInfo.h.
Constructor & Destructor Documentation
AArch64InstrInfo()
AArch64InstrInfo::AArch64InstrInfo (const AArch64Subtarget & STI) explicit
Definition at line 32 of file AArch64InstrInfo.cpp.
Member Function Documentation
AnalyzeBranch()
bool AArch64InstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify = false) const override
Definition at line 93 of file AArch64InstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), I, llvm::isCondBranchOpcode(), llvm::isIndirectBranchOpcode(), llvm::isUncondBranchOpcode(), and parseCondBranch().
analyzeCompare()
bool AArch64InstrInfo::analyzeCompare (const MachineInstr * MI, unsigned & SrcReg, unsigned & SrcReg2, int & CmpMask, int & CmpValue) const override
analyzeCompare - For a comparison instruction, return the source registers in SrcReg and SrcReg2, and the value it compares against in CmpValue. Return true if the comparison instruction can be analyzed.
Definition at line 650 of file AArch64InstrInfo.cpp.
References llvm::AArch64_AM::decodeLogicalImmediate().
areMemAccessesTriviallyDisjoint()
bool AArch64InstrInfo::areMemAccessesTriviallyDisjoint (MachineInstr * MIa, MachineInstr * MIb, AliasAnalysis * AA = nullptr) const override
Definition at line 612 of file AArch64InstrInfo.cpp.
References getLdStBaseRegImmOfsWidth(), getRegisterInfo(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::MachineInstr::hasUnmodeledSideEffects(), llvm::MachineInstr::mayLoad(), and llvm::MachineInstr::mayStore().
canInsertSelect()
bool AArch64InstrInfo::canInsertSelect (const MachineBasicBlock & MBB, const SmallVectorImpl< MachineOperand > & Cond, unsigned TrueReg, unsigned FalseReg, int & CondCycles, int & TrueCycles, int & FalseCycles) const override
Definition at line 371 of file AArch64InstrInfo.cpp.
References canFoldIntoCSel(), llvm::MachineBasicBlock::getParent(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
copyPhysReg()
void AArch64InstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const override
Definition at line 1537 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), contains(), copyPhysRegTuple(), llvm::RegState::Define, llvm::getKillRegState(), llvm::TargetRegisterInfo::getMatchingSuperReg(), getRegisterInfo(), llvm::AArch64_AM::getShifterImm(), I, llvm::RegState::Implicit, llvm_unreachable, llvm::AArch64_AM::LSL, llvm::AArch64SysReg::NZCV, and llvm::RegState::Undef.
copyPhysRegTuple()
void AArch64InstrInfo::copyPhysRegTuple (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc, unsigned Opcode, llvm::ArrayRef< unsigned > Indices) const
Definition at line 1511 of file AArch64InstrInfo.cpp.
References AddSubReg(), llvm::BuildMI(), llvm::RegState::Define, forwardCopyWillClobberTuple(), llvm::MCRegisterInfo::getEncodingValue(), llvm::getKillRegState(), getRegisterInfo(), I, and llvm::ArrayRef< T >::size().
Referenced by copyPhysReg().
emitFrameIndexDebugValue()
MachineInstr * AArch64InstrInfo::emitFrameIndexDebugValue (MachineFunction & MF, int FrameIx, uint64_t Offset, const MDNode * Var, const MDNode * Expr, DebugLoc DL) const
Definition at line 1480 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMetadata(), and llvm::BuildMI().
enableClusterLoads()
bool llvm::AArch64InstrInfo::enableClusterLoads () const inline override
Definition at line 101 of file AArch64InstrInfo.h.
expandPostRAPseudo()
bool AArch64InstrInfo::expandPostRAPseudo (MachineBasicBlock::iterator MI) const override
Definition at line 986 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::cast(), llvm::MachineBasicBlock::erase(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getTarget(), llvm::RegState::Kill, llvm::CodeModel::Large, llvm::TargetOpcode::LOAD_STACK_GUARD, llvm::AArch64II::MO_G0, llvm::AArch64II::MO_G1, llvm::AArch64II::MO_G2, llvm::AArch64II::MO_G3, llvm::AArch64II::MO_GOT, llvm::AArch64II::MO_NC, llvm::AArch64II::MO_PAGE, and llvm::AArch64II::MO_PAGEOFF.
foldMemoryOperandImpl() [1/2]
MachineInstr * AArch64InstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, const SmallVectorImpl< unsigned > & Ops, int FrameIndex) const override
Definition at line 2073 of file AArch64InstrInfo.cpp.
References llvm::MachineRegisterInfo::constrainRegClass(), llvm::MachineFunction::getRegInfo(), and llvm::TargetRegisterInfo::isVirtualRegister().
foldMemoryOperandImpl() [2/2]
virtual MachineInstr * llvm::TargetInstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, const SmallVectorImpl< unsigned > & Ops, MachineInstr * LoadMI) const inline
foldMemoryOperandImpl - Target-dependent implementation for foldMemoryOperand. Target-independent code in foldMemoryOperand will take care of adding a MachineMemOperand to the newly created instruction.
Definition at line 736 of file TargetInstrInfo.h.
genAlternativeCodeSequence()
void AArch64InstrInfo::genAlternativeCodeSequence (MachineInstr & Root, MachineCombinerPattern::MC_PATTERN Pattern, SmallVectorImpl< MachineInstr * > & InsInstrs, SmallVectorImpl< MachineInstr * > & DelInstrs, DenseMap< unsigned, unsigned > & InstrIdxForVirtReg) const override
genAlternativeCodeSequence - when hasPattern() finds a pattern this function generates the instructions that could replace the original code sequence
Definition at line 2677 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), genMadd(), genMaddR(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MachineOperand::isImm(), llvm::MachineCombinerPattern::MC_MULADDW_OP1, llvm::MachineCombinerPattern::MC_MULADDW_OP2, llvm::MachineCombinerPattern::MC_MULADDWI_OP1, llvm::MachineCombinerPattern::MC_MULADDX_OP1, llvm::MachineCombinerPattern::MC_MULADDX_OP2, llvm::MachineCombinerPattern::MC_MULADDXI_OP1, llvm::MachineCombinerPattern::MC_MULSUBW_OP1, llvm::MachineCombinerPattern::MC_MULSUBW_OP2, llvm::MachineCombinerPattern::MC_MULSUBWI_OP1, llvm::MachineCombinerPattern::MC_MULSUBX_OP1, llvm::MachineCombinerPattern::MC_MULSUBX_OP2, llvm::MachineCombinerPattern::MC_MULSUBXI_OP1, llvm::AArch64_AM::processLogicalImmediate(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and TII.
GetInstSizeInBytes()
unsigned AArch64InstrInfo::GetInstSizeInBytes (const MachineInstr * MI) const
GetInstSize - Return the number of bytes of code the specified instruction may be. This returns the maximum number of bytes.
Definition at line 38 of file AArch64InstrInfo.cpp.
References llvm::TargetOpcode::DBG_VALUE, llvm::TargetOpcode::EH_LABEL, llvm::TargetMachine::getMCAsmInfo(), llvm::MCInstrDesc::getOpcode(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getTarget(), llvm::TargetOpcode::IMPLICIT_DEF, llvm::TargetOpcode::KILL, and llvm_unreachable.
getLdStBaseRegImmOfs()
bool AArch64InstrInfo::getLdStBaseRegImmOfs (MachineInstr * LdSt, unsigned & BaseReg, unsigned & Offset, const TargetRegisterInfo * TRI) const override
Definition at line 1316 of file AArch64InstrInfo.cpp.
References llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isReg().
getLdStBaseRegImmOfsWidth()
bool AArch64InstrInfo::getLdStBaseRegImmOfsWidth (MachineInstr * LdSt, unsigned & BaseReg, int & Offset, int & Width, const TargetRegisterInfo * TRI) const
Definition at line 1342 of file AArch64InstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isReg().
Referenced by areMemAccessesTriviallyDisjoint().
getNoopForMachoTarget()
void AArch64InstrInfo::getNoopForMachoTarget (MCInst & NopInst) const override
Definition at line 2368 of file AArch64InstrInfo.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), and llvm::MCInst::setOpcode().
getRegisterInfo()
const AArch64RegisterInfo & llvm::AArch64InstrInfo::getRegisterInfo () const inline
getRegisterInfo - TargetInstrInfo is a superset of MRegister info. As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 46 of file AArch64InstrInfo.h.
Referenced by areMemAccessesTriviallyDisjoint(), copyPhysReg(), copyPhysRegTuple(), llvm::AArch64Subtarget::getRegisterInfo(), optimizeCompareInstr(), and optimizeCondBranch().
hasExtendedReg()
bool AArch64InstrInfo::hasExtendedReg (const MachineInstr * MI) const
Return true if this is this instruction has a non-zero immediate.
Returns true if there is an extendable register and that the extending value is non-zero.
Definition at line 1082 of file AArch64InstrInfo.cpp.
hasPattern()
bool AArch64InstrInfo::hasPattern (MachineInstr & Root, SmallVectorImpl< MachineCombinerPattern::MC_PATTERN > & Pattern) const override
hasPattern - return true when there is potentially a faster code sequence for an instruction chain ending in <Root>. All potential patterns are listed in the <Pattern> array.
hasPattern - return true when there is potentially a faster code sequence for an instruction chain ending in Root. All potential patterns are listed in the Pattern vector. Pattern should be sorted in priority order since the pattern evaluator stops checking as soon as it finds a faster sequence.
Definition at line 2472 of file AArch64InstrInfo.cpp.
References canCombineWithMUL(), convertFlagSettingOpcode(), llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), isCombineInstrCandidate(), isCombineInstrSettingFlag(), llvm::MachineOperand::isReg(), llvm::MachineCombinerPattern::MC_MULADDW_OP1, llvm::MachineCombinerPattern::MC_MULADDW_OP2, llvm::MachineCombinerPattern::MC_MULADDWI_OP1, llvm::MachineCombinerPattern::MC_MULADDX_OP1, llvm::MachineCombinerPattern::MC_MULADDX_OP2, llvm::MachineCombinerPattern::MC_MULADDXI_OP1, llvm::MachineCombinerPattern::MC_MULSUBW_OP1, llvm::MachineCombinerPattern::MC_MULSUBW_OP2, llvm::MachineCombinerPattern::MC_MULSUBWI_OP1, llvm::MachineCombinerPattern::MC_MULSUBX_OP1, llvm::MachineCombinerPattern::MC_MULSUBX_OP2, llvm::MachineCombinerPattern::MC_MULSUBXI_OP1, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
hasShiftedReg()
bool AArch64InstrInfo::hasShiftedReg (const MachineInstr * MI) const
Return true if this is this instruction has a non-zero immediate.
Returns true if there is a shiftable register and that the shift value is non-zero.
Definition at line 1036 of file AArch64InstrInfo.cpp.
InsertBranch()
unsigned AArch64InstrInfo::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, const SmallVectorImpl< MachineOperand > & Cond, DebugLoc DL) const override
Definition at line 273 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::BuildMI(), and llvm::SmallVectorBase::empty().
insertSelect()
void AArch64InstrInfo::insertSelect (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DstReg, const SmallVectorImpl< MachineOperand > & Cond, unsigned TrueReg, unsigned FalseReg) const override
Definition at line 412 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), canFoldIntoCSel(), llvm::MachineRegisterInfo::clearKillFlags(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::AArch64_AM::encodeLogicalImmediate(), llvm::AArch64CC::EQ, llvm::AArch64CC::getInvertedCondCode(), llvm::MachineBasicBlock::getParent(), getReg(), llvm::MachineFunction::getRegInfo(), I, llvm_unreachable, llvm::AArch64CC::NE, and llvm::SmallVectorTemplateCommon< T, typename >::size().
isAsCheapAsAMove()
bool AArch64InstrInfo::isAsCheapAsAMove (const MachineInstr * MI) const override
Definition at line 548 of file AArch64InstrInfo.cpp.
References llvm_unreachable.
isCoalescableExtInstr()
bool AArch64InstrInfo::isCoalescableExtInstr (const MachineInstr & MI, unsigned & SrcReg, unsigned & DstReg, unsigned & SubIdx) const override
Definition at line 591 of file AArch64InstrInfo.cpp.
isFPRCopy()
bool AArch64InstrInfo::isFPRCopy (const MachineInstr * MI) const
Does this instruction rename an FPR without modifying bits?
Definition at line 1164 of file AArch64InstrInfo.cpp.
References contains(), and llvm::TargetOpcode::COPY.
isGPRCopy()
bool AArch64InstrInfo::isGPRCopy (const MachineInstr * MI) const
Does this instruction rename a GPR without modifying bits?
Definition at line 1134 of file AArch64InstrInfo.cpp.
References contains(), and llvm::TargetOpcode::COPY.
isGPRZero()
bool AArch64InstrInfo::isGPRZero (const MachineInstr * MI) const
Does this instruction set its full destination register to zero?
Definition at line 1110 of file AArch64InstrInfo.cpp.
References llvm::TargetOpcode::COPY.
isLdStPairSuppressed()
bool AArch64InstrInfo::isLdStPairSuppressed (const MachineInstr * MI) const
Check all MachineMemOperands for a hint to suppress pairing.
Return true if pairing the given load or store is hinted to be unprofitable.
Definition at line 1292 of file AArch64InstrInfo.cpp.
References llvm::MachineMemOperand::MOTargetNumBits, and llvm::MachineMemOperand::MOTargetStartBit.
isLoadFromStackSlot()
unsigned AArch64InstrInfo::isLoadFromStackSlot (const MachineInstr * MI, int & FrameIndex) const override
Definition at line 1185 of file AArch64InstrInfo.cpp.
isScaledAddr()
bool AArch64InstrInfo::isScaledAddr (const MachineInstr * MI) const
Return true if this is load/store scales or extends its register offset. This refers to scaling a dynamic index as opposed to scaled immediates. MI should be a memory op that allows scaled addressing.
Definition at line 1233 of file AArch64InstrInfo.cpp.
References llvm::AArch64_AM::getMemDoShift(), llvm::AArch64_AM::getMemExtendType(), and llvm::AArch64_AM::UXTX.
isStoreToStackSlot()
unsigned AArch64InstrInfo::isStoreToStackSlot (const MachineInstr * MI, int & FrameIndex) const override
Definition at line 1208 of file AArch64InstrInfo.cpp.
loadRegFromStackSlot()
void AArch64InstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 1917 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addReg(), Align, llvm::BuildMI(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDebugLoc(), llvm::getDefRegState(), llvm::PseudoSourceValue::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterClass::getSize(), llvm::TargetRegisterInfo::isVirtualRegister(), and llvm::MachineMemOperand::MOLoad.
optimizeCompareInstr()
bool AArch64InstrInfo::optimizeCompareInstr (MachineInstr * CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo * MRI) const override
optimizeCompareInstr - Convert the instruction supplying the argument to the comparison into one that sets the zero bit in the flags register.
Definition at line 827 of file AArch64InstrInfo.cpp.
References llvm::MachineOperand::clobbersPhysReg(), convertFlagSettingOpcode(), llvm::MachineInstr::definesRegister(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::AArch64CC::GE, llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), getRegisterInfo(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::AArch64CC::GT, I, llvm::MachineOperand::isDef(), llvm::MachineBasicBlock::isLiveIn(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::AArch64CC::LE, llvm::AArch64CC::LT, modifiesConditionCode(), llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), llvm::MachineBasicBlock::successors(), UpdateOperandRegClass(), llvm::MachineRegisterInfo::use_nodbg_empty(), llvm::AArch64CC::VC, and llvm::AArch64CC::VS.
optimizeCondBranch()
bool AArch64InstrInfo::optimizeCondBranch (MachineInstr * MI) const override
Replace csincr-branch sequence by simple conditional branch.
Examples: 1. csinc w9, wzr, wzr, <condition code> tbnz w9, #0, 0x44 to b.<inverted condition code>
2. csinc w9, wzr, wzr, <condition code> tbz w9, #0, 0x44 to b.<condition code>
Parameters
MI Conditional Branch
Returns
True when the simple conditional branch is generated
Definition at line 2885 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::BuildMI(), llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::MachineOperand::getImm(), llvm::AArch64CC::getInvertedCondCode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), getRegisterInfo(), llvm::MachineRegisterInfo::getVRegDef(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm_unreachable, and modifiesConditionCode().
RemoveBranch()
unsigned AArch64InstrInfo::RemoveBranch (MachineBasicBlock & MBB) const override
Definition at line 226 of file AArch64InstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), I, llvm::isCondBranchOpcode(), and llvm::isUncondBranchOpcode().
ReverseBranchCondition()
bool AArch64InstrInfo::ReverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const override
Definition at line 185 of file AArch64InstrInfo.cpp.
References llvm::AArch64CC::getInvertedCondCode(), and llvm_unreachable.
shouldClusterLoads()
bool AArch64InstrInfo::shouldClusterLoads (MachineInstr * FirstLdSt, MachineInstr * SecondLdSt, unsigned NumLoads) const override
Detect opportunities for ldp/stp formation.
Only called for LdSt for which getLdStBaseRegImmOfs returns true.
Definition at line 1441 of file AArch64InstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), and llvm::MachineInstr::getOperand().
shouldScheduleAdjacent()
bool AArch64InstrInfo::shouldScheduleAdjacent (MachineInstr * First, MachineInstr * Second) const override
Definition at line 1459 of file AArch64InstrInfo.cpp.
References llvm::MachineInstr::getOpcode().
storeRegToStackSlot()
void AArch64InstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const override
Definition at line 1819 of file AArch64InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addReg(), Align, llvm::BuildMI(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDebugLoc(), llvm::PseudoSourceValue::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterClass::getSize(), llvm::TargetRegisterInfo::isVirtualRegister(), and llvm::MachineMemOperand::MOStore.
suppressLdStPair()
void AArch64InstrInfo::suppressLdStPair (MachineInstr * MI) const
Hint that pairing the given load or store is unprofitable.
Set a flag on the first MachineMemOperand to suppress pairing.
Definition at line 1305 of file AArch64InstrInfo.cpp.
References llvm::MachineMemOperand::MOTargetNumBits, and llvm::MachineMemOperand::MOTargetStartBit.
useMachineCombiner()
bool AArch64InstrInfo::useMachineCombiner () const override
useMachineCombiner - AArch64 supports MachineCombiner
useMachineCombiner - return true when a target supports MachineCombiner
Definition at line 2373 of file AArch64InstrInfo.cpp.
The documentation for this class was generated from the following files:
AArch64InstrInfo.h
AArch64InstrInfo.cpp