LLVM: llvm::VerifierPass Class Reference
LLVM API Documentation
llvm::VerifierPass Class Reference
#include <Verifier.h>
Public Member Functions
VerifierPass (bool FatalErrors=true)
PreservedAnalyses run (Module &M)
PreservedAnalyses run (Function &F)
Static Public Member Functions
static StringRef name ()
Detailed Description
Definition at line 74 of file Verifier.h.
Constructor & Destructor Documentation
VerifierPass()
llvm::VerifierPass::VerifierPass (bool FatalErrors = true) inline explicit
Definition at line 78 of file Verifier.h.
Member Function Documentation
name()
StringRef llvm::VerifierPass::name () inline static
Definition at line 83 of file Verifier.h.
run() [1/2]
PreservedAnalyses VerifierPass::run (Function & F)
Definition at line 2960 of file Verifier.cpp.
References llvm::PreservedAnalyses::all(), llvm::dbgs(), F, llvm::report_fatal_error(), and llvm::verifyFunction().
run() [2/2]
PreservedAnalyses VerifierPass::run (Module & M)
Definition at line 2953 of file Verifier.cpp.
References llvm::PreservedAnalyses::all(), llvm::dbgs(), llvm::report_fatal_error(), and llvm::verifyModule().
The documentation for this class was generated from the following files:
Verifier.h
Verifier.cpp