LLVM: llvm::DWARFDebugInfoEntryMinimal Class Reference
LLVM API Documentation
llvm::DWARFDebugInfoEntryMinimal Class Reference
DWARFDebugInfoEntryMinimal - A DIE with only the minimum required data.
#include <DWARFDebugInfoEntry.h>
Public Member Functions
DWARFDebugInfoEntryMinimal ()
void dump (raw_ostream &OS, DWARFUnit *u, unsigned recurseDepth, unsigned indent=0) const
void dumpAttribute (raw_ostream &OS, DWARFUnit *u, uint32_t *offset_ptr, uint16_t attr, uint16_t form, unsigned indent=0) const
bool extractFast (const DWARFUnit *U, uint32_t *OffsetPtr)
uint32_t getTag () const
bool isNULL () const
bool isSubprogramDIE () const
Returns true if DIE represents a subprogram (not inlined).
bool isSubroutineDIE () const
uint32_t getOffset () const
bool hasChildren () const
const DWARFDebugInfoEntryMinimal * getSibling () const
const DWARFDebugInfoEntryMinimal * getFirstChild () const
void setSibling (const DWARFDebugInfoEntryMinimal *Sibling)
const DWARFAbbreviationDeclaration * getAbbreviationDeclarationPtr () const
bool getAttributeValue (const DWARFUnit *U, const uint16_t Attr, DWARFFormValue &FormValue) const
const char * getAttributeValueAsString (const DWARFUnit *U, const uint16_t Attr, const char *FailValue) const
uint64_t getAttributeValueAsAddress (const DWARFUnit *U, const uint16_t Attr, uint64_t FailValue) const
uint64_t getAttributeValueAsUnsignedConstant (const DWARFUnit *U, const uint16_t Attr, uint64_t FailValue) const
uint64_t getAttributeValueAsReference (const DWARFUnit *U, const uint16_t Attr, uint64_t FailValue) const
uint64_t getAttributeValueAsSectionOffset (const DWARFUnit *U, const uint16_t Attr, uint64_t FailValue) const
uint64_t getRangesBaseAttribute (const DWARFUnit *U, uint64_t FailValue) const
bool getLowAndHighPC (const DWARFUnit *U, uint64_t &LowPC, uint64_t &HighPC) const
DWARFAddressRangesVector getAddressRanges (const DWARFUnit *U) const
void collectChildrenAddressRanges (const DWARFUnit *U, DWARFAddressRangesVector &Ranges) const
bool addressRangeContainsAddress (const DWARFUnit *U, const uint64_t Address) const
const char * getSubroutineName (const DWARFUnit *U, DINameKind Kind) const
const char * getName (const DWARFUnit *U, DINameKind Kind) const
void getCallerFrame (const DWARFUnit *U, uint32_t &CallFile, uint32_t &CallLine, uint32_t &CallColumn) const
DWARFDebugInfoEntryInlinedChain getInlinedChainForAddress (const DWARFUnit *U, const uint64_t Address) const
Detailed Description
DWARFDebugInfoEntryMinimal - A DIE with only the minimum required data.
Definition at line 29 of file DWARFDebugInfoEntry.h.
Constructor & Destructor Documentation
DWARFDebugInfoEntryMinimal()
llvm::DWARFDebugInfoEntryMinimal::DWARFDebugInfoEntryMinimal () inline
Definition at line 38 of file DWARFDebugInfoEntry.h.
Referenced by collectChildrenAddressRanges(), dump(), dumpAttribute(), getFirstChild(), getInlinedChainForAddress(), getName(), getSibling(), and setSibling().
Member Function Documentation
addressRangeContainsAddress()
bool DWARFDebugInfoEntryMinimal::addressRangeContainsAddress (const DWARFUnit * U, const uint64_t Address) const
Definition at line 366 of file DWARFDebugInfoEntry.cpp.
References getAddressRanges().
Referenced by getInlinedChainForAddress().
collectChildrenAddressRanges()
void DWARFDebugInfoEntryMinimal::collectChildrenAddressRanges (const DWARFUnit * U, DWARFAddressRangesVector & Ranges) const
Definition at line 350 of file DWARFDebugInfoEntry.cpp.
References collectChildrenAddressRanges(), DWARFDebugInfoEntryMinimal(), getAddressRanges(), getFirstChild(), getSibling(), isNULL(), isSubprogramDIE(), and Ranges.
Referenced by collectChildrenAddressRanges().
dump()
void DWARFDebugInfoEntryMinimal::dump (raw_ostream & OS, DWARFUnit * u, unsigned recurseDepth, unsigned indent = 0) const
Definition at line 36 of file DWARFDebugInfoEntry.cpp.
References llvm::dwarf::syntax::Address, dump(), dumpAttribute(), DWARFDebugInfoEntryMinimal(), llvm::format(), llvm::dwarf::syntax::WithColor::get(), llvm::DWARFUnit::getDebugInfoExtractor(), getFirstChild(), getSibling(), getTag(), llvm::DataExtractor::getULEB128(), llvm::raw_ostream::indent(), llvm::DataExtractor::isValidOffset(), llvm::dwarf::syntax::Tag, and llvm::dwarf::TagString().
Referenced by dump().
dumpAttribute()
void DWARFDebugInfoEntryMinimal::dumpAttribute (raw_ostream & OS, DWARFUnit * u, uint32_t * offset_ptr, uint16_t attr, uint16_t form, unsigned indent = 0) const
Definition at line 111 of file DWARFDebugInfoEntry.cpp.
References llvm::dwarf::syntax::Attribute, llvm::dwarf::AttributeString(), llvm::dwarf::AttributeValueString(), llvm::DWARFFormValue::dump(), dumpApplePropertyAttribute(), dumpRanges(), llvm::dwarf::DW_AT_abstract_origin, llvm::dwarf::DW_AT_APPLE_property_attribute, llvm::dwarf::DW_AT_call_file, llvm::dwarf::DW_AT_call_line, llvm::dwarf::DW_AT_decl_file, llvm::dwarf::DW_AT_decl_line, llvm::dwarf::DW_AT_ranges, llvm::dwarf::DW_AT_specification, llvm::dwarf::DW_FORM_ref_sig8, DWARFDebugInfoEntryMinimal(), llvm::dwarf::syntax::Enumerator, llvm::DWARFFormValue::extractValue(), findUnitAndExtractFast(), llvm::format(), llvm::dwarf::FormEncodingString(), llvm::dwarf::syntax::WithColor::get(), llvm::DWARFUnit::getAddressByteSize(), getAddressRanges(), llvm::DWARFFormValue::getAsReference(), llvm::DWARFFormValue::getAsUnsignedConstant(), llvm::DWARFUnit::getCompilationDir(), llvm::DWARFUnit::getContext(), llvm::DWARFUnit::getDebugInfoExtractor(), llvm::DWARFFormValue::getForm(), llvm::DWARFContext::getLineTableForUnit(), llvm::raw_ostream::indent(), llvm::LinkageName, Name, and llvm::dwarf::syntax::String.
Referenced by dump().
extractFast()
bool DWARFDebugInfoEntryMinimal::extractFast (const DWARFUnit * U, uint32_t * OffsetPtr)
Extracts a debug info entry, which is a child of a given unit, starting at a given offset. If DIE can't be extracted, returns false and doesn't change OffsetPtr.
Definition at line 183 of file DWARFDebugInfoEntry.cpp.
References llvm::DWARFFormValue::getFixedFormSizes(), llvm::DataExtractor::getULEB128(), llvm::DataExtractor::isValidOffset(), llvm::ArrayRef< T >::size(), and llvm::DWARFFormValue::skipValue().
getAbbreviationDeclarationPtr()
const DWARFAbbreviationDeclaration * llvm::DWARFDebugInfoEntryMinimal::getAbbreviationDeclarationPtr () const inline
Definition at line 85 of file DWARFDebugInfoEntry.h.
getAddressRanges()
DWARFAddressRangesVector DWARFDebugInfoEntryMinimal::getAddressRanges (const DWARFUnit * U) const
Definition at line 331 of file DWARFDebugInfoEntry.cpp.
References llvm::dwarf::DW_AT_ranges, llvm::DWARFDebugRangeList::getAbsoluteRanges(), getAttributeValueAsSectionOffset(), getLowAndHighPC(), and isNULL().
Referenced by addressRangeContainsAddress(), llvm::DWARFUnit::collectAddressRanges(), collectChildrenAddressRanges(), and dumpAttribute().
getAttributeValue()
bool DWARFDebugInfoEntryMinimal::getAttributeValue (const DWARFUnit * U, const uint16_t Attr, DWARFFormValue & FormValue) const
Definition at line 233 of file DWARFDebugInfoEntry.cpp.
References llvm::DWARFFormValue::extractValue(), getOffset(), llvm::DataExtractor::getULEB128(), and llvm::DWARFFormValue::skipValue().
Referenced by getAttributeValueAsAddress(), getAttributeValueAsReference(), getAttributeValueAsSectionOffset(), getAttributeValueAsString(), and getAttributeValueAsUnsignedConstant().
getAttributeValueAsAddress()
uint64_t DWARFDebugInfoEntryMinimal::getAttributeValueAsAddress (const DWARFUnit * U, const uint16_t Attr, uint64_t FailValue) const
Definition at line 267 of file DWARFDebugInfoEntry.cpp.
References llvm::DWARFFormValue::getAsAddress(), getAttributeValue(), llvm::Optional< T >::getValue(), and llvm::Optional< T >::hasValue().
Referenced by getLowAndHighPC().
getAttributeValueAsReference()
uint64_t DWARFDebugInfoEntryMinimal::getAttributeValueAsReference (const DWARFUnit * U, const uint16_t Attr, uint64_t FailValue) const
Definition at line 285 of file DWARFDebugInfoEntry.cpp.
References llvm::DWARFFormValue::getAsReference(), getAttributeValue(), llvm::Optional< T >::getValue(), and llvm::Optional< T >::hasValue().
Referenced by getName().
getAttributeValueAsSectionOffset()
uint64_t DWARFDebugInfoEntryMinimal::getAttributeValueAsSectionOffset (const DWARFUnit * U, const uint16_t Attr, uint64_t FailValue) const
Definition at line 294 of file DWARFDebugInfoEntry.cpp.
References llvm::DWARFFormValue::getAsSectionOffset(), getAttributeValue(), llvm::Optional< T >::getValue(), and llvm::Optional< T >::hasValue().
Referenced by getAddressRanges(), llvm::DWARFContext::getLineTableForUnit(), and getRangesBaseAttribute().
getAttributeValueAsString()
const char * DWARFDebugInfoEntryMinimal::getAttributeValueAsString (const DWARFUnit * U, const uint16_t Attr, const char * FailValue) const
Definition at line 258 of file DWARFDebugInfoEntry.cpp.
References llvm::DWARFFormValue::getAsCString(), getAttributeValue(), llvm::Optional< T >::getValue(), and llvm::Optional< T >::hasValue().
Referenced by getName().
getAttributeValueAsUnsignedConstant()
uint64_t DWARFDebugInfoEntryMinimal::getAttributeValueAsUnsignedConstant (const DWARFUnit * U, const uint16_t Attr, uint64_t FailValue) const
Definition at line 276 of file DWARFDebugInfoEntry.cpp.
References llvm::DWARFFormValue::getAsUnsignedConstant(), getAttributeValue(), llvm::Optional< T >::getValue(), and llvm::Optional< T >::hasValue().
Referenced by getCallerFrame(), and getLowAndHighPC().
getCallerFrame()
void DWARFDebugInfoEntryMinimal::getCallerFrame (const DWARFUnit * U, uint32_t & CallFile, uint32_t & CallLine, uint32_t & CallColumn) const
Retrieves values of DW_AT_call_file, DW_AT_call_line and DW_AT_call_column from DIE (or zeroes if they are missing).
Definition at line 423 of file DWARFDebugInfoEntry.cpp.
References llvm::dwarf::DW_AT_call_column, llvm::dwarf::DW_AT_call_file, llvm::dwarf::DW_AT_call_line, and getAttributeValueAsUnsignedConstant().
Referenced by llvm::DWARFContext::getInliningInfoForAddress().
getFirstChild()
const DWARFDebugInfoEntryMinimal * llvm::DWARFDebugInfoEntryMinimal::getFirstChild () const inline
Definition at line 72 of file DWARFDebugInfoEntry.h.
References DWARFDebugInfoEntryMinimal(), and hasChildren().
Referenced by collectChildrenAddressRanges(), and dump().
getInlinedChainForAddress()
DWARFDebugInfoEntryInlinedChain DWARFDebugInfoEntryMinimal::getInlinedChainForAddress (const DWARFUnit * U, const uint64_t Address) const
Get inlined chain for a given address, rooted at the current DIE. Returns empty chain if address is not contained in address range of current DIE.
Definition at line 433 of file DWARFDebugInfoEntry.cpp.
References addressRangeContainsAddress(), llvm::DWARFDebugInfoEntryInlinedChain::DIEs, DWARFDebugInfoEntryMinimal(), getSibling(), isNULL(), and llvm::DWARFDebugInfoEntryInlinedChain::U.
Referenced by llvm::DWARFUnit::getInlinedChainForAddress().
getLowAndHighPC()
bool DWARFDebugInfoEntryMinimal::getLowAndHighPC (const DWARFUnit * U, uint64_t & LowPC, uint64_t & HighPC) const
Retrieves DW_AT_low_pc and DW_AT_high_pc from CU. Returns true if both attributes are present.
Definition at line 313 of file DWARFDebugInfoEntry.cpp.
References llvm::dwarf::DW_AT_high_pc, llvm::dwarf::DW_AT_low_pc, getAttributeValueAsAddress(), and getAttributeValueAsUnsignedConstant().
Referenced by getAddressRanges().
getName()
const char * DWARFDebugInfoEntryMinimal::getName (const DWARFUnit * U, DINameKind Kind) const
Return the DIE name resolving DW_AT_sepcification or DW_AT_abstract_origin references if necessary. Returns null if no name is found.
Definition at line 384 of file DWARFDebugInfoEntry.cpp.
References llvm::dwarf::DW_AT_abstract_origin, llvm::dwarf::DW_AT_linkage_name, llvm::dwarf::DW_AT_MIPS_linkage_name, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_AT_specification, DWARFDebugInfoEntryMinimal(), findUnitAndExtractFast(), getAttributeValueAsReference(), getAttributeValueAsString(), getName(), llvm::LinkageName, and llvm::None.
Referenced by getName(), and getSubroutineName().
getOffset()
uint32_t llvm::DWARFDebugInfoEntryMinimal::getOffset () const inline
Definition at line 60 of file DWARFDebugInfoEntry.h.
Referenced by getAttributeValue().
getRangesBaseAttribute()
uint64_t DWARFDebugInfoEntryMinimal::getRangesBaseAttribute (const DWARFUnit * U, uint64_t FailValue) const
Definition at line 304 of file DWARFDebugInfoEntry.cpp.
References llvm::dwarf::DW_AT_GNU_ranges_base, llvm::dwarf::DW_AT_ranges_base, and getAttributeValueAsSectionOffset().
getSibling()
const DWARFDebugInfoEntryMinimal * llvm::DWARFDebugInfoEntryMinimal::getSibling () const inline
Definition at line 65 of file DWARFDebugInfoEntry.h.
References DWARFDebugInfoEntryMinimal().
Referenced by collectChildrenAddressRanges(), dump(), and getInlinedChainForAddress().
getSubroutineName()
const char * DWARFDebugInfoEntryMinimal::getSubroutineName (const DWARFUnit * U, DINameKind Kind) const
If a DIE represents a subprogram (or inlined subroutine), returns its mangled name (or short name, if mangled is missing). This name may be fetched from specification or abstract origin for this subprogram. Returns null if no name is found.
Definition at line 376 of file DWARFDebugInfoEntry.cpp.
References getName(), and isSubroutineDIE().
Referenced by getFunctionNameForAddress(), and llvm::DWARFContext::getInliningInfoForAddress().
getTag()
uint32_t llvm::DWARFDebugInfoEntryMinimal::getTag () const inline
Definition at line 51 of file DWARFDebugInfoEntry.h.
Referenced by dump(), isSubprogramDIE(), and isSubroutineDIE().
hasChildren()
bool llvm::DWARFDebugInfoEntryMinimal::hasChildren () const inline
Definition at line 61 of file DWARFDebugInfoEntry.h.
References isNULL().
Referenced by getFirstChild().
isNULL()
bool llvm::DWARFDebugInfoEntryMinimal::isNULL () const inline
Definition at line 52 of file DWARFDebugInfoEntry.h.
Referenced by collectChildrenAddressRanges(), getAddressRanges(), getInlinedChainForAddress(), and hasChildren().
isSubprogramDIE()
bool DWARFDebugInfoEntryMinimal::isSubprogramDIE () const
Returns true if DIE represents a subprogram (not inlined).
Definition at line 223 of file DWARFDebugInfoEntry.cpp.
References llvm::dwarf::DW_TAG_subprogram, and getTag().
Referenced by collectChildrenAddressRanges().
isSubroutineDIE()
bool DWARFDebugInfoEntryMinimal::isSubroutineDIE () const
Returns true if DIE represents a subprogram or an inlined subroutine.
Definition at line 227 of file DWARFDebugInfoEntry.cpp.
References llvm::dwarf::DW_TAG_inlined_subroutine, llvm::dwarf::DW_TAG_subprogram, and getTag().
Referenced by getSubroutineName().
setSibling()
void llvm::DWARFDebugInfoEntryMinimal::setSibling (const DWARFDebugInfoEntryMinimal * Sibling) inline
Definition at line 76 of file DWARFDebugInfoEntry.h.
References DWARFDebugInfoEntryMinimal().
The documentation for this class was generated from the following files:
DWARFDebugInfoEntry.h
DWARFDebugInfoEntry.cpp