LLVM: llvm::APSInt Class Reference
LLVM API Documentation
llvm::APSInt Class Reference
#include <APSInt.h>
Public Member Functions
APSInt ()
Default constructor that creates an uninitialized APInt.
APSInt (uint32_t BitWidth, bool isUnsigned=true)
APSInt (APInt I, bool isUnsigned=true)
APSInt & operator= (APInt RHS)
APSInt & operator= (uint64_t RHS)
bool isSigned () const
bool isUnsigned () const
void setIsUnsigned (bool Val)
void setIsSigned (bool Val)
void toString (SmallVectorImpl< char > &Str, unsigned Radix=10) const
toString - Append this APSInt to the specified SmallString.
std::string toString (unsigned Radix) const
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT trunc (uint32_t width) const
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT extend (uint32_t width) const
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT extOrTrunc (uint32_t width) const
const APSInt & operator%= (const APSInt &RHS)
const APSInt & operator/= (const APSInt &RHS)
APSInt operator% (const APSInt &RHS) const
APSInt operator/ (const APSInt &RHS) const
APSInt operator>> (unsigned Amt) const
APSInt & operator>>= (unsigned Amt)
bool operator< (const APSInt &RHS) const
bool operator> (const APSInt &RHS) const
bool operator<= (const APSInt &RHS) const
bool operator>= (const APSInt &RHS) const
bool operator== (const APSInt &RHS) const
bool operator== (int64_t RHS) const
bool operator!= (const APSInt &RHS) const
bool operator!= (int64_t RHS) const
APSInt operator<< (unsigned Bits) const
APSInt & operator<<= (unsigned Amt)
APSInt & operator++ ()
APSInt & operator-- ()
APSInt operator++ (int)
APSInt operator-- (int)
APSInt operator- () const
APSInt & operator+= (const APSInt &RHS)
APSInt & operator-= (const APSInt &RHS)
APSInt & operator*= (const APSInt &RHS)
APSInt & operator&= (const APSInt &RHS)
APSInt & operator|= (const APSInt &RHS)
APSInt & operator^= (const APSInt &RHS)
APSInt operator& (const APSInt &RHS) const
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT And (const APSInt &RHS) const
APSInt operator| (const APSInt &RHS) const
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT Or (const APSInt &RHS) const
APSInt operator^ (const APSInt &RHS) const
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT Xor (const APSInt &RHS) const
APSInt operator* (const APSInt &RHS) const
APSInt operator+ (const APSInt &RHS) const
APSInt operator- (const APSInt &RHS) const
APSInt operator~ () const
void Profile (FoldingSetNodeID &ID) const
void toString (SmallVectorImpl< char > &Str, unsigned Radix, bool Signed, bool formatAsCLiteral=false) const
std::string toString (unsigned Radix, bool Signed) const
Return the APInt as a std::string.
Public Member Functions inherited from llvm::APInt
APInt (unsigned numBits, uint64_t val, bool isSigned=false)
Create a new APInt of numBits width, initialized as val.
APInt (unsigned numBits, ArrayRef< uint64_t > bigVal)
Construct an APInt of numBits width, initialized as bigVal[].
APInt (unsigned numBits, unsigned numWords, const uint64_t bigVal[])
APInt (unsigned numBits, StringRef str, uint8_t radix)
Construct an APInt from a string representation.
APInt (const APInt &that)
Copy Constructor.
APInt (APInt &&that)
Move Constructor.
~APInt ()
Destructor.
APInt ()
Default constructor that creates an uninitialized APInt.
bool needsCleanup () const
Returns whether this instance allocated memory.
void Profile (FoldingSetNodeID &id) const
Profile - This method 'profiles' an APInt for use with FoldingSet.
bool isNegative () const
Determine sign of this APInt.
bool isNonNegative () const
Determine if this APInt Value is non-negative (>= 0)
bool isStrictlyPositive () const
Determine if this APInt Value is positive.
bool isAllOnesValue () const
Determine if all bits are set.
bool isMaxValue () const
Determine if this is the largest unsigned value.
bool isMaxSignedValue () const
Determine if this is the largest signed value.
bool isMinValue () const
Determine if this is the smallest unsigned value.
bool isMinSignedValue () const
Determine if this is the smallest signed value.
bool isIntN (unsigned N) const
Check if this APInt has an N-bits unsigned integer value.
bool isSignedIntN (unsigned N) const
Check if this APInt has an N-bits signed integer value.
bool isPowerOf2 () const
Check if this APInt's value is a power of two greater than zero.
bool isSignBit () const
Check if the APInt's value is returned by getSignBit.
bool getBoolValue () const
Convert APInt to a boolean value.
uint64_t getLimitedValue (uint64_t Limit=~0ULL) const
const APInt operator++ (int)
Postfix increment operator.
APInt & operator++ ()
Prefix increment operator.
const APInt operator-- (int)
Postfix decrement operator.
APInt & operator-- ()
Prefix decrement operator.
APInt operator~ () const
Unary bitwise complement operator.
APInt operator- () const
Unary negation operator.
bool operator! () const
Logical negation operator.
APInt & operator= (const APInt &RHS)
Copy assignment operator.
APInt & operator= (APInt &&that)
Move assignment operator.
APInt & operator= (uint64_t RHS)
Assignment operator.
APInt & operator&= (const APInt &RHS)
Bitwise AND assignment operator.
APInt & operator|= (const APInt &RHS)
Bitwise OR assignment operator.
APInt & operator|= (uint64_t RHS)
Bitwise OR assignment operator.
APInt & operator^= (const APInt &RHS)
Bitwise XOR assignment operator.
APInt & operator*= (const APInt &RHS)
Multiplication assignment operator.
APInt & operator+= (const APInt &RHS)
Addition assignment operator.
APInt & operator-= (const APInt &RHS)
Subtraction assignment operator.
APInt & operator<<= (unsigned shiftAmt)
Left-shift assignment function.
bool operator== (const APInt &RHS) const
Equality operator.
bool operator== (uint64_t Val) const
Equality operator.
bool eq (const APInt &RHS) const
Equality comparison.
bool operator!= (const APInt &RHS) const
Inequality operator.
bool operator!= (uint64_t Val) const
Inequality operator.
bool ne (const APInt &RHS) const
Inequality comparison.
bool ult (const APInt &RHS) const
Unsigned less than comparison.
bool ult (uint64_t RHS) const
Unsigned less than comparison.
bool slt (const APInt &RHS) const
Signed less than comparison.
bool slt (uint64_t RHS) const
Signed less than comparison.
bool ule (const APInt &RHS) const
Unsigned less or equal comparison.
bool ule (uint64_t RHS) const
Unsigned less or equal comparison.
bool sle (const APInt &RHS) const
Signed less or equal comparison.
bool sle (uint64_t RHS) const
Signed less or equal comparison.
bool ugt (const APInt &RHS) const
Unsigned greather than comparison.
bool ugt (uint64_t RHS) const
Unsigned greater than comparison.
bool sgt (const APInt &RHS) const
Signed greather than comparison.
bool sgt (uint64_t RHS) const
Signed greater than comparison.
bool uge (const APInt &RHS) const
Unsigned greater or equal comparison.
bool uge (uint64_t RHS) const
Unsigned greater or equal comparison.
bool sge (const APInt &RHS) const
Signed greather or equal comparison.
bool sge (uint64_t RHS) const
Signed greater or equal comparison.
bool intersects (const APInt &RHS) const
APInt LLVM_ATTRIBUTE_UNUSED_RESULT trunc (unsigned width) const
Truncate to new width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT sext (unsigned width) const
Sign extend to a new width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT zext (unsigned width) const
Zero extend to a new width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT sextOrTrunc (unsigned width) const
Sign extend or truncate to width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT zextOrTrunc (unsigned width) const
Zero extend or truncate to width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT sextOrSelf (unsigned width) const
Sign extend or truncate to width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT zextOrSelf (unsigned width) const
Zero extend or truncate to width.
void setAllBits ()
Set every bit to 1.
void setBit (unsigned bitPosition)
Set a given bit to 1.
void clearAllBits ()
Set every bit to 0.
void clearBit (unsigned bitPosition)
Set a given bit to 0.
void flipAllBits ()
Toggle every bit to its opposite value.
void flipBit (unsigned bitPosition)
Toggles a given bit to its opposite value.
unsigned logBase2 () const
unsigned ceilLogBase2 () const
unsigned nearestLogBase2 () const
int32_t exactLogBase2 () const
APInt LLVM_ATTRIBUTE_UNUSED_RESULT sqrt () const
Compute the square root.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT abs () const
Get the absolute value;.
APInt multiplicativeInverse (const APInt &modulo) const
ms magic () const
mu magicu (unsigned LeadingZeros=0) const
APInt getHiBits (unsigned numBits) const
Compute an APInt containing numBits highbits from this APInt.
APInt getLoBits (unsigned numBits) const
Compute an APInt containing numBits lowbits from this APInt.
const uint64_t * getRawData () const
APInt operator& (const APInt &RHS) const
Bitwise AND operator.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT And (const APInt &RHS) const
APInt operator| (const APInt &RHS) const
Bitwise OR operator.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT Or (const APInt &RHS) const
Bitwise OR function.
APInt operator^ (const APInt &RHS) const
Bitwise XOR operator.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT Xor (const APInt &RHS) const
Bitwise XOR function.
APInt operator* (const APInt &RHS) const
Multiplication operator.
APInt operator+ (const APInt &RHS) const
Addition operator.
APInt operator+ (uint64_t RHS) const
APInt operator- (const APInt &RHS) const
Subtraction operator.
APInt operator- (uint64_t RHS) const
APInt operator<< (unsigned Bits) const
Left logical shift operator.
APInt operator<< (const APInt &Bits) const
Left logical shift operator.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT ashr (unsigned shiftAmt) const
Arithmetic right-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT lshr (unsigned shiftAmt) const
Logical right-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT shl (unsigned shiftAmt) const
Left-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT rotl (unsigned rotateAmt) const
Rotate left by rotateAmt.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT rotr (unsigned rotateAmt) const
Rotate right by rotateAmt.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT ashr (const APInt &shiftAmt) const
Arithmetic right-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT lshr (const APInt &shiftAmt) const
Logical right-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT shl (const APInt &shiftAmt) const
Left-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT rotl (const APInt &rotateAmt) const
Rotate left by rotateAmt.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT rotr (const APInt &rotateAmt) const
Rotate right by rotateAmt.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT udiv (const APInt &RHS) const
Unsigned division operation.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT sdiv (const APInt &RHS) const
Signed division function for APInt.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT urem (const APInt &RHS) const
Unsigned remainder operation.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT srem (const APInt &RHS) const
Function for signed remainder operation.
APInt sadd_ov (const APInt &RHS, bool &Overflow) const
APInt uadd_ov (const APInt &RHS, bool &Overflow) const
APInt ssub_ov (const APInt &RHS, bool &Overflow) const
APInt usub_ov (const APInt &RHS, bool &Overflow) const
APInt sdiv_ov (const APInt &RHS, bool &Overflow) const
APInt smul_ov (const APInt &RHS, bool &Overflow) const
APInt umul_ov (const APInt &RHS, bool &Overflow) const
APInt sshl_ov (const APInt &Amt, bool &Overflow) const
APInt ushl_ov (const APInt &Amt, bool &Overflow) const
bool operator[] (unsigned bitPosition) const
Array-indexing support.
unsigned getBitWidth () const
Return the number of bits in the APInt.
unsigned getNumWords () const
Get the number of words.
unsigned getActiveBits () const
Compute the number of active bits in the value.
unsigned getActiveWords () const
Compute the number of active words in the value of this APInt.
unsigned getMinSignedBits () const
Get the minimum bit size for this signed APInt.
uint64_t getZExtValue () const
Get zero extended value.
int64_t getSExtValue () const
Get sign extended value.
unsigned countLeadingZeros () const
The APInt version of the countLeadingZeros functions in MathExtras.h.
unsigned countLeadingOnes () const
Count the number of leading one bits.
unsigned getNumSignBits () const
unsigned countTrailingZeros () const
Count the number of trailing zero bits.
unsigned countTrailingOnes () const
Count the number of trailing one bits.
unsigned countPopulation () const
Count the number of bits set.
void print (raw_ostream &OS, bool isSigned) const
void toString (SmallVectorImpl< char > &Str, unsigned Radix, bool Signed, bool formatAsCLiteral=false) const
void toStringUnsigned (SmallVectorImpl< char > &Str, unsigned Radix=10) const
void toStringSigned (SmallVectorImpl< char > &Str, unsigned Radix=10) const
std::string toString (unsigned Radix, bool Signed) const
Return the APInt as a std::string.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT byteSwap () const
double roundToDouble (bool isSigned) const
Converts this APInt to a double value.
double roundToDouble () const
Converts this unsigned APInt to a double value.
double signedRoundToDouble () const
Converts this signed APInt to a double value.
double bitsToDouble () const
Converts APInt bits to a double.
float bitsToFloat () const
Converts APInt bits to a double.
void dump () const
debug method
Static Public Member Functions
static APSInt getMaxValue (uint32_t numBits, bool Unsigned)
static APSInt getMinValue (uint32_t numBits, bool Unsigned)
static bool isSameValue (const APSInt &I1, const APSInt &I2)
Determine if two APSInts have the same value, zero- or sign-extending as needed.
static APInt getMaxValue (unsigned numBits)
Gets maximum unsigned value of APInt for specific bit width.
static APInt getSignedMaxValue (unsigned numBits)
Gets maximum signed value of APInt for a specific bit width.
static APInt getMinValue (unsigned numBits)
Gets minimum unsigned value of APInt for a specific bit width.
static APInt getSignedMinValue (unsigned numBits)
Gets minimum signed value of APInt for a specific bit width.
static APInt getSignBit (unsigned BitWidth)
Get the SignBit for a specific bit width.
static APInt getAllOnesValue (unsigned numBits)
Get the all-ones value.
static APInt getNullValue (unsigned numBits)
Get the '0' value.
static APInt getOneBitSet (unsigned numBits, unsigned BitNo)
Return an APInt with exactly one bit set in the result.
static APInt getBitsSet (unsigned numBits, unsigned loBit, unsigned hiBit)
Get a value with a block of bits set.
static APInt getHighBitsSet (unsigned numBits, unsigned hiBitsSet)
Get a value with high bits set.
static APInt getLowBitsSet (unsigned numBits, unsigned loBitsSet)
Get a value with low bits set.
static APInt getSplat (unsigned NewLen, const APInt &V)
Return a value containing V broadcasted over NewLen bits.
static bool isSameValue (const APInt &I1, const APInt &I2)
Determine if two APInts have the same value, after zero-extending one of them (if needed!) to ensure that the bit-widths match.
static void udivrem (const APInt &LHS, const APInt &RHS, APInt &Quotient, APInt &Remainder)
Dual division/remainder interface.
static void sdivrem (const APInt &LHS, const APInt &RHS, APInt &Quotient, APInt &Remainder)
static unsigned getNumWords (unsigned BitWidth)
Get the number of words.
static unsigned getBitsNeeded (StringRef str, uint8_t radix)
Get bits required for string value.
static APInt LLVM_ATTRIBUTE_UNUSED_RESULT doubleToBits (double V)
Converts a double to APInt bits.
static APInt LLVM_ATTRIBUTE_UNUSED_RESULT floatToBits (float V)
Converts a float to APInt bits.
static void tcSet (integerPart *, integerPart, unsigned int)
static void tcAssign (integerPart *, const integerPart *, unsigned int)
Assign one bignum to another.
static bool tcIsZero (const integerPart *, unsigned int)
Returns true if a bignum is zero, false otherwise.
static int tcExtractBit (const integerPart *, unsigned int bit)
Extract the given bit of a bignum; returns 0 or 1. Zero-based.
static void tcExtract (integerPart *, unsigned int dstCount, const integerPart *, unsigned int srcBits, unsigned int srcLSB)
static void tcSetBit (integerPart *, unsigned int bit)
Set the given bit of a bignum. Zero-based.
static void tcClearBit (integerPart *, unsigned int bit)
Clear the given bit of a bignum. Zero-based.
static unsigned int tcLSB (const integerPart *, unsigned int)
static unsigned int tcMSB (const integerPart *parts, unsigned int n)
static void tcNegate (integerPart *, unsigned int)
Negate a bignum in-place.
static integerPart tcAdd (integerPart *, const integerPart *, integerPart carry, unsigned)
DST += RHS + CARRY where CARRY is zero or one. Returns the carry flag.
static integerPart tcSubtract (integerPart *, const integerPart *, integerPart carry, unsigned)
DST -= RHS + CARRY where CARRY is zero or one. Returns the carry flag.
static int tcMultiplyPart (integerPart *dst, const integerPart *src, integerPart multiplier, integerPart carry, unsigned int srcParts, unsigned int dstParts, bool add)
static int tcMultiply (integerPart *, const integerPart *, const integerPart *, unsigned)
static unsigned int tcFullMultiply (integerPart *, const integerPart *, const integerPart *, unsigned, unsigned)
static int tcDivide (integerPart *lhs, const integerPart *rhs, integerPart *remainder, integerPart *scratch, unsigned int parts)
static void tcShiftLeft (integerPart *, unsigned int parts, unsigned int count)
static void tcShiftRight (integerPart *, unsigned int parts, unsigned int count)
static void tcAnd (integerPart *, const integerPart *, unsigned int)
The obvious AND, OR and XOR and complement operations.
static void tcOr (integerPart *, const integerPart *, unsigned int)
static void tcXor (integerPart *, const integerPart *, unsigned int)
static void tcComplement (integerPart *, unsigned int)
static int tcCompare (const integerPart *, const integerPart *, unsigned int)
Comparison (unsigned) of two bignums.
static integerPart tcIncrement (integerPart *, unsigned int)
Increment a bignum in-place. Return the carry flag.
static integerPart tcDecrement (integerPart *, unsigned int)
Decrement a bignum in-place. Return the borrow flag.
static void tcSetLeastSignificantBits (integerPart *, unsigned int, unsigned int bits)
Set the least significant BITS and clear the rest.
Detailed Description
Definition at line 22 of file APSInt.h.
Constructor & Destructor Documentation
APSInt() [1/3]
llvm::APSInt::APSInt () inline explicit
Default constructor that creates an uninitialized APInt.
Definition at line 26 of file APSInt.h.
Referenced by And(), extend(), extOrTrunc(), getMaxValue(), getMinValue(), isSameValue(), operator!=(), operator%(), operator%=(), operator&(), operator&=(), operator*(), operator*=(), operator+(), operator++(), operator++(), operator+=(), operator-(), operator-(), operator--(), operator--(), operator-=(), operator/(), operator/=(), operator<(), operator<<(), operator<<=(), operator<=(), operator=(), operator=(), operator==(), operator==(), operator>(), operator>=(), operator>>(), operator>>=(), operator^(), operator^=(), operator|(), operator|=(), operator~(), Or(), trunc(), and Xor().
APSInt() [2/3]
llvm::APSInt::APSInt (uint32_t BitWidth, bool isUnsigned = true) inline explicit
APSInt ctor - Create an APSInt with the specified width, default to unsigned.
Definition at line 30 of file APSInt.h.
References isUnsigned().
APSInt() [3/3]
llvm::APSInt::APSInt (APInt I, bool isUnsigned = true) inline explicit
Definition at line 33 of file APSInt.h.
References I, and isUnsigned().
Member Function Documentation
And()
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APSInt::And (const APSInt & RHS) const inline
Definition at line 209 of file APSInt.h.
References APSInt(), LLVM_ATTRIBUTE_UNUSED_RESULT, and operator&().
extend()
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APSInt::extend (uint32_t width) const inline
Definition at line 69 of file APSInt.h.
References APSInt(), LLVM_ATTRIBUTE_UNUSED_RESULT, llvm::APInt::sext(), and llvm::APInt::zext().
Referenced by isSameValue().
extOrTrunc()
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APSInt::extOrTrunc (uint32_t width) const inline
Definition at line 76 of file APSInt.h.
References APSInt(), LLVM_ATTRIBUTE_UNUSED_RESULT, llvm::APInt::sextOrTrunc(), and llvm::APInt::zextOrTrunc().
getMaxValue()
APSInt llvm::APSInt::getMaxValue (uint32_t numBits, bool Unsigned) inline static
getMaxValue - Return the APSInt representing the maximum integer value with the given bit width and signedness.
Definition at line 248 of file APSInt.h.
References APSInt(), llvm::APInt::getMaxValue(), llvm::APInt::getSignedMaxValue(), and Unsigned.
getMinValue()
APSInt llvm::APSInt::getMinValue (uint32_t numBits, bool Unsigned) inline static
getMinValue - Return the APSInt representing the minimum integer value with the given bit width and signedness.
Definition at line 255 of file APSInt.h.
References APSInt(), llvm::APInt::getMinValue(), llvm::APInt::getSignedMinValue(), and Unsigned.
isSameValue()
bool llvm::APSInt::isSameValue (const APSInt & I1, const APSInt & I2) inline static
Determine if two APSInts have the same value, zero- or sign-extending as needed.
Definition at line 262 of file APSInt.h.
References APSInt(), llvm::APInt::eq(), extend(), llvm::APInt::getBitWidth(), llvm::APInt::isNegative(), isSameValue(), and isSigned().
Referenced by isSameValue(), and operator==().
isSigned()
bool llvm::APSInt::isSigned () const inline
Definition at line 49 of file APSInt.h.
Referenced by llvm::APFloat::convertToInteger(), isSameValue(), toString(), and toString().
isUnsigned()
bool llvm::APSInt::isUnsigned () const inline
Definition at line 50 of file APSInt.h.
Referenced by APSInt(), and APSInt().
operator!=() [1/2]
bool llvm::APSInt::operator!= (const APSInt & RHS) const inline
Definition at line 139 of file APSInt.h.
References APSInt().
operator!=() [2/2]
bool llvm::APSInt::operator!= (int64_t RHS) const inline
Definition at line 142 of file APSInt.h.
operator%()
APSInt llvm::APSInt::operator% (const APSInt & RHS) const inline
Definition at line 99 of file APSInt.h.
References APSInt(), llvm::APInt::srem(), and llvm::APInt::urem().
operator%=()
const APSInt & llvm::APSInt::operator%= (const APSInt & RHS) inline
Definition at line 83 of file APSInt.h.
References APSInt(), llvm::APInt::srem(), and llvm::APInt::urem().
operator&()
APSInt llvm::APSInt::operator& (const APSInt & RHS) const inline
Definition at line 205 of file APSInt.h.
References APSInt().
Referenced by And().
operator&=()
APSInt & llvm::APSInt::operator&= (const APSInt & RHS) inline
Definition at line 189 of file APSInt.h.
References APSInt().
operator*()
APSInt llvm::APSInt::operator* (const APSInt & RHS) const inline
Definition at line 230 of file APSInt.h.
References APSInt().
operator*=()
APSInt & llvm::APSInt::operator*= (const APSInt & RHS) inline
Definition at line 184 of file APSInt.h.
References APSInt().
operator+()
APSInt llvm::APSInt::operator+ (const APSInt & RHS) const inline
Definition at line 234 of file APSInt.h.
References APSInt().
operator++() [1/2]
APSInt & llvm::APSInt::operator++ () inline
Definition at line 157 of file APSInt.h.
References APSInt().
operator++() [2/2]
APSInt llvm::APSInt::operator++ (int) inline
Definition at line 165 of file APSInt.h.
References APSInt().
operator+=()
APSInt & llvm::APSInt::operator+= (const APSInt & RHS) inline
Definition at line 174 of file APSInt.h.
References APSInt().
operator-() [1/2]
APSInt llvm::APSInt::operator- () const inline
Definition at line 171 of file APSInt.h.
References APSInt().
operator-() [2/2]
APSInt llvm::APSInt::operator- (const APSInt & RHS) const inline
Definition at line 238 of file APSInt.h.
References APSInt().
operator--() [1/2]
APSInt & llvm::APSInt::operator-- () inline
Definition at line 161 of file APSInt.h.
References APSInt().
operator--() [2/2]
APSInt llvm::APSInt::operator-- (int) inline
Definition at line 168 of file APSInt.h.
References APSInt().
operator-=()
APSInt & llvm::APSInt::operator-= (const APSInt & RHS) inline
Definition at line 179 of file APSInt.h.
References APSInt().
operator/()
APSInt llvm::APSInt::operator/ (const APSInt & RHS) const inline
Definition at line 103 of file APSInt.h.
References APSInt(), llvm::APInt::sdiv(), and llvm::APInt::udiv().
operator/=()
const APSInt & llvm::APSInt::operator/= (const APSInt & RHS) inline
Definition at line 91 of file APSInt.h.
References APSInt(), llvm::APInt::sdiv(), and llvm::APInt::udiv().
operator<()
bool llvm::APSInt::operator< (const APSInt & RHS) const inline
Definition at line 116 of file APSInt.h.
References APSInt(), llvm::APInt::slt(), and llvm::APInt::ult().
operator<<()
APSInt llvm::APSInt::operator<< (unsigned Bits) const inline
Definition at line 149 of file APSInt.h.
References APSInt().
operator<<=()
APSInt & llvm::APSInt::operator<<= (unsigned Amt) inline
Definition at line 152 of file APSInt.h.
References APSInt().
operator<=()
bool llvm::APSInt::operator<= (const APSInt & RHS) const inline
Definition at line 124 of file APSInt.h.
References APSInt(), llvm::APInt::sle(), and llvm::APInt::ule().
operator=() [1/2]
APSInt & llvm::APSInt::operator= (APInt RHS) inline
Definition at line 36 of file APSInt.h.
References APSInt(), and llvm::APInt::operator=().
operator=() [2/2]
APSInt & llvm::APSInt::operator= (uint64_t RHS) inline
Definition at line 42 of file APSInt.h.
References APSInt(), and llvm::APInt::operator=().
operator==() [1/2]
bool llvm::APSInt::operator== (const APSInt & RHS) const inline
Definition at line 132 of file APSInt.h.
References APSInt(), and llvm::APInt::eq().
operator==() [2/2]
bool llvm::APSInt::operator== (int64_t RHS) const inline
Definition at line 136 of file APSInt.h.
References llvm::APInt::APInt(), APSInt(), and isSameValue().
operator>()
bool llvm::APSInt::operator> (const APSInt & RHS) const inline
Definition at line 120 of file APSInt.h.
References APSInt(), llvm::APInt::sgt(), and llvm::APInt::ugt().
operator>=()
bool llvm::APSInt::operator>= (const APSInt & RHS) const inline
Definition at line 128 of file APSInt.h.
References APSInt(), llvm::APInt::sge(), and llvm::APInt::uge().
operator>>()
APSInt llvm::APSInt::operator>> (unsigned Amt) const inline
Definition at line 108 of file APSInt.h.
References APSInt(), llvm::APInt::ashr(), and llvm::APInt::lshr().
operator>>=()
APSInt & llvm::APSInt::operator>>= (unsigned Amt) inline
Definition at line 111 of file APSInt.h.
References APSInt().
operator^()
APSInt llvm::APSInt::operator^ (const APSInt & RHS) const inline
Definition at line 222 of file APSInt.h.
References APSInt().
Referenced by Xor().
operator^=()
APSInt & llvm::APSInt::operator^= (const APSInt & RHS) inline
Definition at line 199 of file APSInt.h.
References APSInt().
operator|()
APSInt llvm::APSInt::operator| (const APSInt & RHS) const inline
Definition at line 213 of file APSInt.h.
References APSInt().
Referenced by Or().
operator|=()
APSInt & llvm::APSInt::operator|= (const APSInt & RHS) inline
Definition at line 194 of file APSInt.h.
References APSInt().
operator~()
APSInt llvm::APSInt::operator~ () const inline
Definition at line 242 of file APSInt.h.
References APSInt().
Or()
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APSInt::Or (const APSInt & RHS) const inline
Definition at line 217 of file APSInt.h.
References APSInt(), LLVM_ATTRIBUTE_UNUSED_RESULT, and operator|().
Profile()
void APSInt::Profile (FoldingSetNodeID & ID) const
Profile - Used to insert APSInt objects, or objects that contain APSInt objects, into FoldingSets.
Definition at line 20 of file APSInt.cpp.
References llvm::APInt::Profile().
setIsSigned()
void llvm::APSInt::setIsSigned (bool Val) inline
Definition at line 52 of file APSInt.h.
setIsUnsigned()
void llvm::APSInt::setIsUnsigned (bool Val) inline
Definition at line 51 of file APSInt.h.
toString() [1/4]
void APInt::toString (SmallVectorImpl< char > & Str, unsigned Radix, bool Signed, bool formatAsCLiteral = false) const
Converts an APInt to a string and append it to Str. Str is commonly a SmallString.
Definition at line 1416 of file APInt.cpp.
toString() [2/4]
void llvm::APSInt::toString (SmallVectorImpl< char > & Str, unsigned Radix = 10) const inline
toString - Append this APSInt to the specified SmallString.
Definition at line 55 of file APSInt.h.
References isSigned(), and llvm::APInt::toString().
toString() [3/4]
std::string llvm::APSInt::toString (unsigned Radix) const inline
toString - Converts an APInt to a std::string. This is an inefficient method; you should prefer passing in a SmallString instead.
Definition at line 60 of file APSInt.h.
References isSigned(), and llvm::APInt::toString().
toString() [4/4]
std::string APInt::toString (unsigned Radix = 10, bool Signed = true) const
Return the APInt as a std::string.
Note that this is an inefficient method. It is better to pass in a SmallVector/SmallString to the methods above to avoid thrashing the heap for the string.
toString - This returns the APInt as a std::string. Note that this is an inefficient method. It is better to pass in a SmallVector/SmallString to the methods above.
Definition at line 1436 of file APInt.cpp.
trunc()
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APSInt::trunc (uint32_t width) const inline
Definition at line 65 of file APSInt.h.
References APSInt(), LLVM_ATTRIBUTE_UNUSED_RESULT, and llvm::APInt::trunc().
Xor()
APSInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APSInt::Xor (const APSInt & RHS) const inline
Definition at line 226 of file APSInt.h.
References APSInt(), LLVM_ATTRIBUTE_UNUSED_RESULT, and operator^().
The documentation for this class was generated from the following files:
APSInt.h
APSInt.cpp