LLVM: llvm::DagRecTy Class Reference
LLVM API Documentation
llvm::DagRecTy Class Reference
#include <Record.h>
Public Member Functions
Init * convertValue (UnsetInit *UI) override
Init * convertValue (BitInit *BI) override
Init * convertValue (BitsInit *BI) override
Init * convertValue (IntInit *II) override
Init * convertValue (StringInit *SI) override
Init * convertValue (ListInit *LI) override
Init * convertValue (VarBitInit *VB) override
Init * convertValue (DefInit *DI) override
Init * convertValue (UnOpInit *BO) override
Init * convertValue (BinOpInit *BO) override
Init * convertValue (TernOpInit *BO) override
Init * convertValue (DagInit *CI) override
Init * convertValue (TypedInit *TI) override
Init * convertValue (VarInit *VI) override
Init * convertValue (FieldInit *FI) override
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
virtual bool baseClassOf (const RecTy *) const
Static Public Member Functions
static bool classof (const RecTy *RT)
static DagRecTy * get ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
DagRecTy - 'dag' - Represent a dag fragment
Definition at line 334 of file Record.h.
Member Function Documentation
classof()
bool llvm::DagRecTy::classof (const RecTy * RT) inline static
Definition at line 339 of file Record.h.
References llvm::RecTy::DagRecTyKind, llvm::RecTy::getRecTyKind(), and llvm::RecTy::RecTy().
convertValue() [1/15]
Init * DagRecTy::convertValue (BinOpInit * BO) override virtual
Reimplemented from llvm::RecTy.
Definition at line 335 of file Record.cpp.
References llvm::BinOpInit::CONCAT, llvm::Init::convertInitializerTo(), llvm::BinOpInit::get(), llvm::BinOpInit::getLHS(), llvm::BinOpInit::getOpcode(), and llvm::BinOpInit::getRHS().
convertValue() [2/15]
Init * llvm::DagRecTy::convertValue (BitInit * BI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 346 of file Record.h.
convertValue() [3/15]
Init * llvm::DagRecTy::convertValue (BitsInit * BI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 347 of file Record.h.
convertValue() [4/15]
Init * llvm::DagRecTy::convertValue (DagInit * CI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 356 of file Record.h.
convertValue() [5/15]
Init * llvm::DagRecTy::convertValue (DefInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 352 of file Record.h.
convertValue() [6/15]
Init * llvm::DagRecTy::convertValue (FieldInit * FI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 359 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [7/15]
Init * llvm::DagRecTy::convertValue (IntInit * II) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 348 of file Record.h.
convertValue() [8/15]
Init * llvm::DagRecTy::convertValue (ListInit * LI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 350 of file Record.h.
convertValue() [9/15]
Init * llvm::DagRecTy::convertValue (StringInit * SI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 349 of file Record.h.
convertValue() [10/15]
Init * llvm::DagRecTy::convertValue (TernOpInit * BO) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 355 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [11/15]
Init * DagRecTy::convertValue (TypedInit * TI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 318 of file Record.cpp.
References llvm::TypedInit::getType(), and llvm::RecTy::typeIsConvertibleTo().
convertValue() [12/15]
Init * DagRecTy::convertValue (UnOpInit * BO) override virtual
Reimplemented from llvm::RecTy.
Definition at line 324 of file Record.cpp.
References llvm::UnOpInit::CAST, llvm::Init::convertInitializerTo(), llvm::UnOpInit::get(), llvm::UnOpInit::getOpcode(), and llvm::UnOpInit::getOperand().
convertValue() [13/15]
Init * llvm::DagRecTy::convertValue (UnsetInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 345 of file Record.h.
convertValue() [14/15]
Init * llvm::DagRecTy::convertValue (VarBitInit * VB) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 351 of file Record.h.
convertValue() [15/15]
Init * llvm::DagRecTy::convertValue (VarInit * VI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 358 of file Record.h.
References llvm::RecTy::convertValue(), and VI.
get()
DagRecTy * llvm::DagRecTy::get () inline static
Definition at line 343 of file Record.h.
getAsString()
std::string llvm::DagRecTy::getAsString () const inline override virtual
Implements llvm::RecTy.
Definition at line 361 of file Record.h.
typeIsConvertibleTo()
bool llvm::DagRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline override virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 363 of file Record.h.
References llvm::RecTy::baseClassOf(), and llvm::RecTy::RecTy().
The documentation for this class was generated from the following files:
Record.h
Record.cpp