LLVM: llvm::PPCMCExpr Class Reference
LLVM API Documentation
llvm::PPCMCExpr Class Reference
#include <PPCMCExpr.h>
Public Types
enum VariantKind {
VK_PPC_None , VK_PPC_LO , VK_PPC_HI , VK_PPC_HA ,
VK_PPC_HIGHER , VK_PPC_HIGHERA , VK_PPC_HIGHEST , VK_PPC_HIGHESTA
}
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary , Constant , SymbolRef , Unary ,
Target
}
Public Member Functions
void PrintImpl (raw_ostream &OS) const override
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
const MCSection * FindAssociatedSection () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
bool EvaluateAsConstant (int64_t &Res) const
Accessors
VariantKind getKind () const
getOpcode - Get the kind of this expression.
const MCExpr * getSubExpr () const
getSubExpr - Get the child of this expression.
bool isDarwinSyntax () const
isDarwinSyntax - True if expression is to be printed using Darwin syntax.
Public Member Functions inherited from llvm::MCExpr
ExprKind getKind () const
void print (raw_ostream &OS) const
void dump () const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
bool EvaluateAsAbsolute (int64_t &Res) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
int64_t evaluateKnownAbsolute (const MCAsmLayout &Layout) const
bool EvaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
bool EvaluateAsValue (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
const MCSection * FindAssociatedSection () const
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const PPCMCExpr * Create (VariantKind Kind, const MCExpr *Expr, bool isDarwin, MCContext &Ctx)
static const PPCMCExpr * CreateLo (const MCExpr *Expr, bool isDarwin, MCContext &Ctx)
static const PPCMCExpr * CreateHi (const MCExpr *Expr, bool isDarwin, MCContext &Ctx)
static const PPCMCExpr * CreateHa (const MCExpr *Expr, bool isDarwin, MCContext &Ctx)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind _Kind)
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet, bool ForceVarExpansion) const
Detailed Description
Definition at line 19 of file PPCMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::PPCMCExpr::VariantKind
Enumerator
VK_PPC_None
VK_PPC_LO
VK_PPC_HI
VK_PPC_HA
VK_PPC_HIGHER
VK_PPC_HIGHERA
VK_PPC_HIGHEST
VK_PPC_HIGHESTA
Definition at line 21 of file PPCMCExpr.h.
Member Function Documentation
classof()
bool llvm::PPCMCExpr::classof (const MCExpr * E) inline static
Definition at line 95 of file PPCMCExpr.h.
References llvm::MCExpr::getKind(), and llvm::MCExpr::Target.
Create()
const PPCMCExpr * PPCMCExpr::Create (VariantKind Kind, const MCExpr * Expr, bool isDarwin, MCContext & Ctx) static
Definition at line 22 of file PPCMCExpr.cpp.
Referenced by CreateHa(), CreateHi(), and CreateLo().
CreateHa()
const PPCMCExpr * llvm::PPCMCExpr::CreateHa (const MCExpr * Expr, bool isDarwin, MCContext & Ctx) inline static
Definition at line 60 of file PPCMCExpr.h.
References Create(), and VK_PPC_HA.
Referenced by GetSymbolRef().
CreateHi()
const PPCMCExpr * llvm::PPCMCExpr::CreateHi (const MCExpr * Expr, bool isDarwin, MCContext & Ctx) inline static
Definition at line 55 of file PPCMCExpr.h.
References Create(), and VK_PPC_HI.
CreateLo()
const PPCMCExpr * llvm::PPCMCExpr::CreateLo (const MCExpr * Expr, bool isDarwin, MCContext & Ctx) inline static
Definition at line 50 of file PPCMCExpr.h.
References Create(), and VK_PPC_LO.
Referenced by GetSymbolRef().
EvaluateAsConstant()
bool PPCMCExpr::EvaluateAsConstant (int64_t & Res) const
Definition at line 56 of file PPCMCExpr.cpp.
References llvm::MCExpr::EvaluateAsRelocatable(), and getSubExpr().
EvaluateAsRelocatableImpl()
bool PPCMCExpr::EvaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 93 of file PPCMCExpr.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCExpr::EvaluateAsRelocatable(), llvm::PPC::fixup_ppc_half16, llvm::MCValue::get(), llvm::MCAsmLayout::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCFixup::getKind(), llvm::MCSymbolRefExpr::getKind(), getSubExpr(), llvm::MCSymbolRefExpr::getSymbol(), llvm_unreachable, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_PPC_HA, VK_PPC_HA, llvm::MCSymbolRefExpr::VK_PPC_HI, VK_PPC_HI, llvm::MCSymbolRefExpr::VK_PPC_HIGHER, VK_PPC_HIGHER, llvm::MCSymbolRefExpr::VK_PPC_HIGHERA, VK_PPC_HIGHERA, llvm::MCSymbolRefExpr::VK_PPC_HIGHEST, VK_PPC_HIGHEST, llvm::MCSymbolRefExpr::VK_PPC_HIGHESTA, VK_PPC_HIGHESTA, llvm::MCSymbolRefExpr::VK_PPC_LO, and VK_PPC_LO.
FindAssociatedSection()
const MCSection * llvm::PPCMCExpr::FindAssociatedSection () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 86 of file PPCMCExpr.h.
References llvm::MCExpr::FindAssociatedSection(), and getSubExpr().
fixELFSymbolsInTLSFixups()
void llvm::PPCMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 91 of file PPCMCExpr.h.
getKind()
VariantKind llvm::PPCMCExpr::getKind () const inline
getOpcode - Get the kind of this expression.
Definition at line 70 of file PPCMCExpr.h.
getSubExpr()
const MCExpr * llvm::PPCMCExpr::getSubExpr () const inline
getSubExpr - Get the child of this expression.
Definition at line 73 of file PPCMCExpr.h.
Referenced by EvaluateAsConstant(), EvaluateAsRelocatableImpl(), FindAssociatedSection(), PrintImpl(), and visitUsedExpr().
isDarwinSyntax()
bool llvm::PPCMCExpr::isDarwinSyntax () const inline
isDarwinSyntax - True if expression is to be printed using Darwin syntax.
Definition at line 76 of file PPCMCExpr.h.
Referenced by PrintImpl().
PrintImpl()
void PPCMCExpr::PrintImpl (raw_ostream & OS) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 27 of file PPCMCExpr.cpp.
References getSubExpr(), isDarwinSyntax(), llvm_unreachable, llvm::MCExpr::print(), VK_PPC_HA, VK_PPC_HI, VK_PPC_HIGHER, VK_PPC_HIGHERA, VK_PPC_HIGHEST, VK_PPC_HIGHESTA, and VK_PPC_LO.
visitUsedExpr()
void PPCMCExpr::visitUsedExpr (MCStreamer & Streamer) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 148 of file PPCMCExpr.cpp.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
PPCMCExpr.h
PPCMCExpr.cpp