LLVM: llvm::OnDiskChainedHashTable< Info >::iterator Class Reference
LLVM API Documentation
llvm::OnDiskChainedHashTable< Info >::iterator Class Reference
#include <OnDiskHashTable.h>
Public Member Functions
iterator ()
iterator (const internal_key_type K, const unsigned char *D, offset_type L, Info *InfoObj)
data_type operator* () const
bool operator== (const iterator &X) const
bool operator!= (const iterator &X) const
Detailed Description
template<typename Info>
class llvm::OnDiskChainedHashTable< Info >::iterator
Definition at line 268 of file OnDiskHashTable.h.
Constructor & Destructor Documentation
iterator() [1/2]
template<typename Info> llvm::OnDiskChainedHashTable< Info >::iterator::iterator () inline
Definition at line 275 of file OnDiskHashTable.h.
Referenced by operator!=(), and operator==().
iterator() [2/2]
template<typename Info> llvm::OnDiskChainedHashTable< Info >::iterator::iterator (const internal_key_type K, const unsigned char * D, offset_type L, Info * InfoObj) inline
Definition at line 276 of file OnDiskHashTable.h.
Member Function Documentation
operator!=()
template<typename Info> bool llvm::OnDiskChainedHashTable< Info >::iterator::operator!= (const iterator & X) const inline
Definition at line 282 of file OnDiskHashTable.h.
References iterator(), and llvm::X.
operator*()
template<typename Info> data_type llvm::OnDiskChainedHashTable< Info >::iterator::operator* () const inline
Definition at line 280 of file OnDiskHashTable.h.
operator==()
template<typename Info> bool llvm::OnDiskChainedHashTable< Info >::iterator::operator== (const iterator & X) const inline
Definition at line 281 of file OnDiskHashTable.h.
References iterator(), and llvm::X.
The documentation for this class was generated from the following file:
OnDiskHashTable.h