LLVM: llvm::MachineLocation Class Reference
LLVM API Documentation
llvm::MachineLocation Class Reference
#include <MachineLocation.h>
Public Types
enum : uint32_t { VirtualFP = ~0U }
Public Member Functions
MachineLocation ()
MachineLocation (unsigned R)
Create a direct register location.
MachineLocation (unsigned R, int O)
Create a register-indirect location with an offset.
bool operator== (const MachineLocation &Other) const
bool isIndirect () const
bool isReg () const
unsigned getReg () const
int getOffset () const
void setIsRegister (bool Is)
void setRegister (unsigned R)
void setOffset (int O)
void set (unsigned R)
Make this location a direct register location.
void set (unsigned R, int O)
Make this location a register-indirect+offset location.
void dump ()
Detailed Description
Definition at line 25 of file MachineLocation.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint32_t
Enumerator
VirtualFP
Definition at line 31 of file MachineLocation.h.
Constructor & Destructor Documentation
MachineLocation() [1/3]
llvm::MachineLocation::MachineLocation () inline
Definition at line 36 of file MachineLocation.h.
Referenced by operator==().
MachineLocation() [2/3]
llvm::MachineLocation::MachineLocation (unsigned R) inline explicit
Create a direct register location.
Definition at line 39 of file MachineLocation.h.
References true.
MachineLocation() [3/3]
llvm::MachineLocation::MachineLocation (unsigned R, int O) inline
Create a register-indirect location with an offset.
Definition at line 42 of file MachineLocation.h.
Member Function Documentation
dump()
void llvm::MachineLocation::dump ()
getOffset()
int llvm::MachineLocation::getOffset () const inline
Definition at line 55 of file MachineLocation.h.
Referenced by llvm::DwarfCompileUnit::addAddress(), llvm::DwarfUnit::addBlockByrefAddress(), llvm::DwarfCompileUnit::addComplexAddress(), llvm::DwarfDebug::emitDebugLocValue(), and llvm::AsmPrinter::EmitDwarfRegOp().
getReg()
unsigned llvm::MachineLocation::getReg () const inline
Definition at line 54 of file MachineLocation.h.
Referenced by llvm::DwarfCompileUnit::addAddress(), llvm::DwarfUnit::addBlockByrefAddress(), llvm::DwarfCompileUnit::addComplexAddress(), llvm::DwarfDebug::emitDebugLocValue(), llvm::AsmPrinter::EmitDwarfRegOp(), llvm::AsmPrinter::EmitDwarfRegOpPiece(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
isIndirect()
bool llvm::MachineLocation::isIndirect () const inline
Returns
true iff this is a register-indirect location.
Definition at line 52 of file MachineLocation.h.
Referenced by llvm::AsmPrinter::EmitDwarfRegOp().
isReg()
bool llvm::MachineLocation::isReg () const inline
Definition at line 53 of file MachineLocation.h.
Referenced by llvm::DwarfCompileUnit::addAddress(), llvm::DwarfUnit::addBlockByrefAddress(), and llvm::AsmPrinter::EmitDwarfRegOpPiece().
operator==()
bool llvm::MachineLocation::operator== (const MachineLocation & Other) const inline
Definition at line 45 of file MachineLocation.h.
References MachineLocation().
set() [1/2]
void llvm::MachineLocation::set (unsigned R) inline
Make this location a direct register location.
Definition at line 60 of file MachineLocation.h.
Referenced by getDebugLocValue().
set() [2/2]
void llvm::MachineLocation::set (unsigned R, int O) inline
Make this location a register-indirect+offset location.
Definition at line 66 of file MachineLocation.h.
setIsRegister()
void llvm::MachineLocation::setIsRegister (bool Is) inline
Definition at line 56 of file MachineLocation.h.
setOffset()
void llvm::MachineLocation::setOffset (int O) inline
Definition at line 58 of file MachineLocation.h.
setRegister()
void llvm::MachineLocation::setRegister (unsigned R) inline
Definition at line 57 of file MachineLocation.h.
The documentation for this class was generated from the following file:
MachineLocation.h