LLVM: llvm::SUnitIterator Class Reference
LLVM API Documentation
llvm::SUnitIterator Class Reference
#include <ScheduleDAG.h>
Public Member Functions
bool operator== (const SUnitIterator &x) const
bool operator!= (const SUnitIterator &x) const
const SUnitIterator & operator= (const SUnitIterator &I)
pointer operator* () const
pointer operator-> () const
SUnitIterator & operator++ ()
SUnitIterator operator++ (int)
unsigned getOperand () const
const SUnit * getNode () const
bool isCtrlDep () const
isCtrlDep - Test if this is not an SDep::Data dependence.
bool isArtificialDep () const
const SDep & getSDep () const
Static Public Member Functions
static SUnitIterator begin (SUnit *N)
static SUnitIterator end (SUnit *N)
Detailed Description
Definition at line 619 of file ScheduleDAG.h.
Member Function Documentation
begin()
SUnitIterator llvm::SUnitIterator::begin (SUnit * N) inline static
Definition at line 650 of file ScheduleDAG.h.
References N.
Referenced by llvm::GraphTraits< SUnit * >::child_begin().
end()
SUnitIterator llvm::SUnitIterator::end (SUnit * N) inline static
Definition at line 651 of file ScheduleDAG.h.
References N.
Referenced by llvm::GraphTraits< SUnit * >::child_end().
getNode()
const SUnit * llvm::SUnitIterator::getNode () const inline
Definition at line 656 of file ScheduleDAG.h.
getOperand()
unsigned llvm::SUnitIterator::getOperand () const inline
Definition at line 655 of file ScheduleDAG.h.
getSDep()
const SDep & llvm::SUnitIterator::getSDep () const inline
Definition at line 664 of file ScheduleDAG.h.
Referenced by isArtificialDep(), and isCtrlDep().
isArtificialDep()
bool llvm::SUnitIterator::isArtificialDep () const inline
Definition at line 661 of file ScheduleDAG.h.
References getSDep(), and llvm::SDep::isArtificial().
Referenced by llvm::DOTGraphTraits< ScheduleDAG * >::getEdgeAttributes(), and llvm::DOTGraphTraits< ScheduleDAGMI * >::getEdgeAttributes().
isCtrlDep()
bool llvm::SUnitIterator::isCtrlDep () const inline
isCtrlDep - Test if this is not an SDep::Data dependence.
Definition at line 658 of file ScheduleDAG.h.
References getSDep(), and llvm::SDep::isCtrl().
Referenced by llvm::DOTGraphTraits< ScheduleDAG * >::getEdgeAttributes(), and llvm::DOTGraphTraits< ScheduleDAGMI * >::getEdgeAttributes().
operator!=()
bool llvm::SUnitIterator::operator!= (const SUnitIterator & x) const inline
Definition at line 629 of file ScheduleDAG.h.
References operator==().
operator*()
pointer llvm::SUnitIterator::operator* () const inline
Definition at line 637 of file ScheduleDAG.h.
Referenced by operator->().
operator++() [1/2]
SUnitIterator & llvm::SUnitIterator::operator++ () inline
Definition at line 642 of file ScheduleDAG.h.
operator++() [2/2]
SUnitIterator llvm::SUnitIterator::operator++ (int) inline
Definition at line 646 of file ScheduleDAG.h.
operator->()
pointer llvm::SUnitIterator::operator-> () const inline
Definition at line 640 of file ScheduleDAG.h.
References operator*().
operator=()
const SUnitIterator & llvm::SUnitIterator::operator= (const SUnitIterator & I) inline
Definition at line 631 of file ScheduleDAG.h.
References I.
operator==()
bool llvm::SUnitIterator::operator== (const SUnitIterator & x) const inline
Definition at line 626 of file ScheduleDAG.h.
Referenced by operator!=().
The documentation for this class was generated from the following file:
ScheduleDAG.h