LLVM: llvm::object::RelocationRef Class Reference
LLVM API Documentation
llvm::object::RelocationRef Class Reference
#include <ObjectFile.h>
Public Member Functions
RelocationRef ()
RelocationRef (DataRefImpl RelocationP, const ObjectFile *Owner)
RelocationRef.
bool operator== (const RelocationRef &Other) const
void moveNext ()
std::error_code getAddress (uint64_t &Result) const
std::error_code getOffset (uint64_t &Result) const
symbol_iterator getSymbol () const
std::error_code getType (uint64_t &Result) const
std::error_code getHidden (bool &Result) const
Indicates whether this relocation should hidden when listing relocations, usually because it is the trailing part of a multipart relocation that will be printed as part of the leading relocation.
std::error_code getTypeName (SmallVectorImpl< char > &Result) const
Get a string that represents the type of this relocation.
std::error_code getValueString (SmallVectorImpl< char > &Result) const
Get a string that represents the calculation of the value of this relocation.
DataRefImpl getRawDataRefImpl () const
const ObjectFile * getObjectFile () const
Detailed Description
RelocationRef - This is a value type class that represents a single relocation in the list of relocations in the object file.
Definition at line 38 of file ObjectFile.h.
Constructor & Destructor Documentation
RelocationRef() [1/2]
llvm::object::RelocationRef::RelocationRef () inline
Definition at line 43 of file ObjectFile.h.
Referenced by operator==().
RelocationRef() [2/2]
llvm::object::RelocationRef::RelocationRef (DataRefImpl RelocationP, const ObjectFile * Owner) inline
RelocationRef.
Definition at line 445 of file ObjectFile.h.
Member Function Documentation
getAddress()
std::error_code llvm::object::RelocationRef::getAddress (uint64_t & Result) const inline
Definition at line 458 of file ObjectFile.h.
Referenced by llvm::RuntimeDyldMachO::makeValueAddendPCRel().
getHidden()
std::error_code llvm::object::RelocationRef::getHidden (bool & Result) const inline
Indicates whether this relocation should hidden when listing relocations, usually because it is the trailing part of a multipart relocation that will be printed as part of the leading relocation.
Definition at line 484 of file ObjectFile.h.
getObjectFile()
const ObjectFile * llvm::object::RelocationRef::getObjectFile () const inline
Definition at line 492 of file ObjectFile.h.
Referenced by llvm::object::getELFRelocationAddend().
getOffset()
std::error_code llvm::object::RelocationRef::getOffset (uint64_t & Result) const inline
Definition at line 462 of file ObjectFile.h.
Referenced by llvm::RuntimeDyldMachO::getRelocationEntry(), and llvm::RuntimeDyldELF::processRelocationRef().
getRawDataRefImpl()
DataRefImpl llvm::object::RelocationRef::getRawDataRefImpl () const inline
Definition at line 488 of file ObjectFile.h.
Referenced by llvm::object::getELFRelocationAddend(), llvm::RuntimeDyldMachO::getRelocationEntry(), llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::RuntimeDyldMachO::makeValueAddendPCRel(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), and llvm::RuntimeDyldMachOX86_64::processRelocationRef().
getSymbol()
symbol_iterator llvm::object::RelocationRef::getSymbol () const inline
Definition at line 466 of file ObjectFile.h.
Referenced by llvm::RuntimeDyldMachO::getRelocationValueRef(), and llvm::RuntimeDyldELF::processRelocationRef().
getType()
std::error_code llvm::object::RelocationRef::getType (uint64_t & Result) const inline
Definition at line 470 of file ObjectFile.h.
Referenced by llvm::RuntimeDyldELF::processRelocationRef().
getTypeName()
std::error_code llvm::object::RelocationRef::getTypeName (SmallVectorImpl< char > & Result) const inline
Get a string that represents the type of this relocation.
This is for display purposes only.
Definition at line 475 of file ObjectFile.h.
getValueString()
std::error_code llvm::object::RelocationRef::getValueString (SmallVectorImpl< char > & Result) const inline
Get a string that represents the calculation of the value of this relocation.
This is for display purposes only.
Definition at line 480 of file ObjectFile.h.
moveNext()
void llvm::object::RelocationRef::moveNext () inline
Definition at line 454 of file ObjectFile.h.
operator==()
bool llvm::object::RelocationRef::operator== (const RelocationRef & Other) const inline
Definition at line 450 of file ObjectFile.h.
References RelocationRef().
The documentation for this class was generated from the following file:
ObjectFile.h