LLVM: llvm::Mips16HardFloat Class Reference
LLVM API Documentation
llvm::Mips16HardFloat Class Reference
#include <Mips16HardFloat.h>
Public Member Functions
Mips16HardFloat (MipsTargetMachine &TM_)
const char * getPassName () const override
bool runOnModule (Module &M) override
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Protected Attributes
const MipsTargetMachine & TM
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 27 of file Mips16HardFloat.h.
Constructor & Destructor Documentation
Mips16HardFloat()
llvm::Mips16HardFloat::Mips16HardFloat (MipsTargetMachine & TM_) inline
Definition at line 31 of file Mips16HardFloat.h.
References ID, llvm::ModulePass::ModulePass(), and TM.
Member Function Documentation
getPassName()
const char * llvm::Mips16HardFloat::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 33 of file Mips16HardFloat.h.
runOnModule()
bool llvm::Mips16HardFloat::runOnModule (Module & M) override virtual
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
Implements llvm::ModulePass.
Definition at line 512 of file Mips16HardFloat.cpp.
References llvm::Module::begin(), createFPFnStub(), DEBUG, llvm::Module::end(), llvm::errs(), F, fixupFPReturnAndCall(), NoSig, removeUseSoftFloat(), TM, and whichFPParamVariantNeeded().
Member Data Documentation
ID
char llvm::Mips16HardFloat::ID = 0 static
Definition at line 29 of file Mips16HardFloat.h.
Referenced by Mips16HardFloat().
TM
const MipsTargetMachine& llvm::Mips16HardFloat::TM protected
Definition at line 37 of file Mips16HardFloat.h.
Referenced by Mips16HardFloat(), and runOnModule().
The documentation for this class was generated from the following files:
Mips16HardFloat.h
Mips16HardFloat.cpp