LLVM: llvm::cl::parser< DataType > Class Template Reference
LLVM API Documentation
llvm::cl::parser< DataType > Class Template Reference
#include <CommandLine.h>
Classes
class OptionInfo
Public Types
typedef DataType parser_data_type
Public Member Functions
unsigned getNumOptions () const override
const char * getOption (unsigned N) const override
const char * getDescription (unsigned N) const override
const GenericOptionValue & getOptionValue (unsigned N) const override
bool parse (Option &O, StringRef ArgName, StringRef Arg, DataType &V)
template<class DT>
void addLiteralOption (const char *Name, const DT &V, const char *HelpStr)
void removeLiteralOption (const char *Name)
Public Member Functions inherited from llvm::cl::generic_parser_base
virtual ~generic_parser_base ()
virtual size_t getOptionWidth (const Option &O) const
virtual void printOptionInfo (const Option &O, size_t GlobalWidth) const
void printGenericOptionDiff (const Option &O, const GenericOptionValue &V, const GenericOptionValue &Default, size_t GlobalWidth) const
template<class AnyOptionValue>
void printOptionDiff (const Option &O, const AnyOptionValue &V, const AnyOptionValue &Default, size_t GlobalWidth) const
void initialize (Option &O)
void getExtraOptionNames (SmallVectorImpl< const char * > &OptionNames)
enum ValueExpected getValueExpectedFlagDefault () const
unsigned findOption (const char *Name)
Protected Attributes
SmallVector< OptionInfo, 8 > Values
Protected Attributes inherited from llvm::cl::generic_parser_base
bool hasArgStr
Detailed Description
template<class DataType>
class llvm::cl::parser< DataType >
Definition at line 621 of file CommandLine.h.
Member Typedef Documentation
parser_data_type
template<class DataType> typedef DataType llvm::cl::parser< DataType >::parser_data_type
Definition at line 632 of file CommandLine.h.
Member Function Documentation
addLiteralOption()
template<class DataType> template<class DT> void llvm::cl::parser< DataType >::addLiteralOption (const char * Name, const DT & V, const char * HelpStr) inline
addLiteralOption - Add an entry to the mapping table.
Definition at line 666 of file CommandLine.h.
References llvm::cl::generic_parser_base::findOption(), llvm::cl::MarkOptionsChanged(), Name, Values, and llvm::X.
Referenced by llvm::RegistryParser< T, U >::registered().
getDescription()
template<class DataType> const char * llvm::cl::parser< DataType >::getDescription (unsigned N) const inline override virtual
Implements llvm::cl::generic_parser_base.
Definition at line 637 of file CommandLine.h.
References N, and Values.
getNumOptions()
template<class DataType> unsigned llvm::cl::parser< DataType >::getNumOptions () const inline override virtual
Implements llvm::cl::generic_parser_base.
Definition at line 635 of file CommandLine.h.
References Values.
getOption()
template<class DataType> const char * llvm::cl::parser< DataType >::getOption (unsigned N) const inline override virtual
Implements llvm::cl::generic_parser_base.
Definition at line 636 of file CommandLine.h.
References N, and Values.
getOptionValue()
template<class DataType> const GenericOptionValue & llvm::cl::parser< DataType >::getOptionValue (unsigned N) const inline override virtual
Implements llvm::cl::generic_parser_base.
Definition at line 642 of file CommandLine.h.
References N, and Values.
parse()
template<class DataType> bool parser::parse (Option & O, StringRef ArgName, StringRef Arg, DataType & V) inline
Definition at line 647 of file CommandLine.h.
References llvm::cl::Option::error(), llvm::cl::generic_parser_base::hasArgStr, Name, and Values.
removeLiteralOption()
template<class DataType> void llvm::cl::parser< DataType >::removeLiteralOption (const char * Name) inline
removeLiteralOption - Remove the specified option.
Definition at line 675 of file CommandLine.h.
References llvm::cl::generic_parser_base::findOption(), N, Name, and Values.
Member Data Documentation
Values
template<class DataType> SmallVector<OptionInfo, 8> llvm::cl::parser< DataType >::Values protected
Definition at line 629 of file CommandLine.h.
Referenced by addLiteralOption(), getDescription(), getNumOptions(), getOption(), getOptionValue(), parse(), llvm::PassNameParser::printOptionInfo(), and removeLiteralOption().
The documentation for this class was generated from the following files:
CommandLine.h
CommandLine.cpp