LLVM: llvm::ManagedStatic< C > Class Template Reference
LLVM API Documentation
llvm::ManagedStatic< C > Class Template Reference
#include <ManagedStatic.h>
Public Member Functions
C & operator* ()
C * operator-> ()
const C & operator* () const
const C * operator-> () const
Public Member Functions inherited from llvm::ManagedStaticBase
bool isConstructed () const
isConstructed - Return true if this object has not been created yet.
void destroy () const
Additional Inherited Members
Protected Member Functions inherited from llvm::ManagedStaticBase
void RegisterManagedStatic (void *(*creator)(), void(*deleter)(void *)) const
Protected Attributes inherited from llvm::ManagedStaticBase
void * Ptr
void(* DeleterFn)(void *)
const ManagedStaticBase * Next
Detailed Description
template<class C>
class llvm::ManagedStatic< C >
ManagedStatic - This transparently changes the behavior of global statics to be lazily constructed on demand (good for reducing startup times of dynamic libraries that link in LLVM components) and for making destruction be explicit through the llvm_shutdown() function call.
Definition at line 61 of file ManagedStatic.h.
Member Function Documentation
operator*() [1/2]
template<class C> C & llvm::ManagedStatic< C >::operator* () inline
Definition at line 65 of file ManagedStatic.h.
References llvm::object_deleter< T >::call(), llvm::llvm_is_multithreaded(), llvm::sys::MemoryFence(), llvm::object_creator(), llvm::ManagedStaticBase::Ptr, llvm::ManagedStaticBase::RegisterManagedStatic(), and TsanHappensAfter.
operator*() [2/2]
template<class C> const C & llvm::ManagedStatic< C >::operator* () const inline
Definition at line 81 of file ManagedStatic.h.
References llvm::object_deleter< T >::call(), llvm::llvm_is_multithreaded(), llvm::sys::MemoryFence(), llvm::object_creator(), llvm::ManagedStaticBase::Ptr, llvm::ManagedStaticBase::RegisterManagedStatic(), and TsanHappensAfter.
operator->() [1/2]
template<class C> C * llvm::ManagedStatic< C >::operator-> () inline
Definition at line 73 of file ManagedStatic.h.
References llvm::object_deleter< T >::call(), llvm::llvm_is_multithreaded(), llvm::sys::MemoryFence(), llvm::object_creator(), llvm::ManagedStaticBase::Ptr, llvm::ManagedStaticBase::RegisterManagedStatic(), and TsanHappensAfter.
operator->() [2/2]
template<class C> const C * llvm::ManagedStatic< C >::operator-> () const inline
Definition at line 89 of file ManagedStatic.h.
References llvm::object_deleter< T >::call(), llvm::llvm_is_multithreaded(), llvm::sys::MemoryFence(), llvm::object_creator(), llvm::ManagedStaticBase::Ptr, llvm::ManagedStaticBase::RegisterManagedStatic(), and TsanHappensAfter.
The documentation for this class was generated from the following file:
ManagedStatic.h