LLVM: llvm::tool_output_file Class Reference
LLVM API Documentation
llvm::tool_output_file Class Reference
#include <ToolOutputFile.h>
Public Member Functions
tool_output_file (StringRef Filename, std::error_code &EC, sys::fs::OpenFlags Flags)
tool_output_file (StringRef Filename, int FD)
raw_fd_ostream & os ()
os - Return the contained raw_fd_ostream.
void keep ()
Detailed Description
tool_output_file - This class contains a raw_fd_ostream and adds a few extra features commonly needed for compiler-like tool output files:
The file is automatically deleted if the process is killed.
The file is automatically deleted when the tool_output_file object is destroyed unless the client calls keep().
Definition at line 26 of file ToolOutputFile.h.
Constructor & Destructor Documentation
tool_output_file() [1/2]
tool_output_file::tool_output_file (StringRef Filename, std::error_code & EC, sys::fs::OpenFlags Flags)
This constructor's arguments are passed to to raw_fd_ostream's constructor.
Definition at line 37 of file ToolOutputFile.cpp.
tool_output_file() [2/2]
tool_output_file::tool_output_file (StringRef Filename, int FD)
Definition at line 45 of file ToolOutputFile.cpp.
References true.
Member Function Documentation
keep()
void llvm::tool_output_file::keep () inline
keep - Indicate that the tool's job wrt this output file has been successful and the file should not be deleted.
Definition at line 59 of file ToolOutputFile.h.
Referenced by llvm::LTOCodeGenerator::compile_to_file(), createDependencyFile(), llvm::TableGenMain(), and llvm::LTOCodeGenerator::writeMergedModules().
os()
raw_fd_ostream & llvm::tool_output_file::os () inline
os - Return the contained raw_fd_ostream.
Definition at line 55 of file ToolOutputFile.h.
Referenced by llvm::LTOCodeGenerator::compile_to_file(), createDependencyFile(), llvm::TableGenMain(), and llvm::LTOCodeGenerator::writeMergedModules().
The documentation for this class was generated from the following files:
ToolOutputFile.h
ToolOutputFile.cpp