LLVM: llvm::MachinePassRegistryNode Class Reference
LLVM API Documentation
llvm::MachinePassRegistryNode Class Reference
#include <MachinePassRegistry.h>
Public Member Functions
MachinePassRegistryNode (const char *N, const char *D, MachinePassCtor C)
MachinePassRegistryNode * getNext () const
MachinePassRegistryNode ** getNextAddress ()
const char * getName () const
const char * getDescription () const
MachinePassCtor getCtor () const
void setNext (MachinePassRegistryNode *N)
Detailed Description
MachinePassRegistryNode - Machine pass node stored in registration list.
Definition at line 50 of file MachinePassRegistry.h.
Constructor & Destructor Documentation
MachinePassRegistryNode()
llvm::MachinePassRegistryNode::MachinePassRegistryNode (const char * N, const char * D, MachinePassCtor C) inline
Definition at line 61 of file MachinePassRegistry.h.
References N.
Referenced by getNext(), getNextAddress(), llvm::MachineSchedRegistry::MachineSchedRegistry(), llvm::RegisterRegAlloc::RegisterRegAlloc(), llvm::RegisterScheduler::RegisterScheduler(), and setNext().
Member Function Documentation
getCtor()
MachinePassCtor llvm::MachinePassRegistryNode::getCtor () const inline
Definition at line 73 of file MachinePassRegistry.h.
Referenced by llvm::MachinePassRegistry::Add().
getDescription()
const char * llvm::MachinePassRegistryNode::getDescription () const inline
Definition at line 72 of file MachinePassRegistry.h.
Referenced by llvm::MachinePassRegistry::Add().
getName()
const char * llvm::MachinePassRegistryNode::getName () const inline
Definition at line 71 of file MachinePassRegistry.h.
Referenced by llvm::MachinePassRegistry::Add(), and llvm::MachinePassRegistry::Remove().
getNext()
MachinePassRegistryNode * llvm::MachinePassRegistryNode::getNext () const inline
Definition at line 69 of file MachinePassRegistry.h.
References MachinePassRegistryNode().
Referenced by llvm::MachineSchedRegistry::getNext(), llvm::RegisterRegAlloc::getNext(), llvm::RegisterScheduler::getNext(), and llvm::MachinePassRegistry::setDefault().
getNextAddress()
MachinePassRegistryNode ** llvm::MachinePassRegistryNode::getNextAddress () inline
Definition at line 70 of file MachinePassRegistry.h.
References MachinePassRegistryNode().
setNext()
void llvm::MachinePassRegistryNode::setNext (MachinePassRegistryNode * N) inline
Definition at line 74 of file MachinePassRegistry.h.
References MachinePassRegistryNode(), and N.
Referenced by llvm::MachinePassRegistry::Add().
The documentation for this class was generated from the following file:
MachinePassRegistry.h