LLVM: llvm::opt::arg_iterator Class Reference
LLVM API Documentation
llvm::opt::arg_iterator Class Reference
arg_iterator - Iterates through arguments stored inside an ArgList.
#include <ArgList.h>
Public Types
typedef Arg *const * value_type
typedef Arg *const & reference
typedef Arg *const * pointer
typedef std::forward_iterator_tag iterator_category
typedef std::ptrdiff_t difference_type
Public Member Functions
arg_iterator (SmallVectorImpl< Arg * >::const_iterator it, const ArgList &_Args, OptSpecifier _Id0=0U, OptSpecifier _Id1=0U, OptSpecifier _Id2=0U)
operator const Arg * ()
reference operator* () const
pointer operator-> () const
arg_iterator & operator++ ()
arg_iterator operator++ (int)
Friends
bool operator== (arg_iterator LHS, arg_iterator RHS)
bool operator!= (arg_iterator LHS, arg_iterator RHS)
Detailed Description
arg_iterator - Iterates through arguments stored inside an ArgList.
Definition at line 29 of file ArgList.h.
Member Typedef Documentation
difference_type
typedef std::ptrdiff_t llvm::opt::arg_iterator::difference_type
Definition at line 53 of file ArgList.h.
iterator_category
typedef std::forward_iterator_tag llvm::opt::arg_iterator::iterator_category
Definition at line 52 of file ArgList.h.
pointer
typedef Arg* const* llvm::opt::arg_iterator::pointer
Definition at line 51 of file ArgList.h.
reference
typedef Arg* const& llvm::opt::arg_iterator::reference
Definition at line 50 of file ArgList.h.
value_type
typedef Arg* const* llvm::opt::arg_iterator::value_type
Definition at line 49 of file ArgList.h.
Constructor & Destructor Documentation
arg_iterator()
llvm::opt::arg_iterator::arg_iterator (SmallVectorImpl< Arg * >::const_iterator it, const ArgList & _Args, OptSpecifier _Id0 = 0U, OptSpecifier _Id1 = 0U, OptSpecifier _Id2 = 0U) inline
Definition at line 55 of file ArgList.h.
Referenced by operator!=, operator++(), operator++(), and operator==.
Member Function Documentation
operator const Arg *()
llvm::opt::arg_iterator::operator const Arg * () inline
Definition at line 62 of file ArgList.h.
operator*()
reference llvm::opt::arg_iterator::operator* () const inline
Definition at line 63 of file ArgList.h.
operator++() [1/2]
arg_iterator & llvm::opt::arg_iterator::operator++ () inline
Definition at line 66 of file ArgList.h.
References arg_iterator().
operator++() [2/2]
arg_iterator llvm::opt::arg_iterator::operator++ (int) inline
Definition at line 72 of file ArgList.h.
References arg_iterator().
operator->()
pointer llvm::opt::arg_iterator::operator-> () const inline
Definition at line 64 of file ArgList.h.
Friends And Related Symbol Documentation
operator!=
bool operator!= (arg_iterator LHS, arg_iterator RHS) friend
Definition at line 81 of file ArgList.h.
References arg_iterator().
operator==
bool operator== (arg_iterator LHS, arg_iterator RHS) friend
Definition at line 78 of file ArgList.h.
References arg_iterator().
The documentation for this class was generated from the following files:
ArgList.h
ArgList.cpp