LLVM: llvm::OpInit Class Reference
LLVM API Documentation
llvm::OpInit Class Reference abstract
#include <Record.h>
Public Member Functions
virtual OpInit * clone (std::vector< Init * > &Operands) const =0
virtual int getNumOperands () const =0
virtual Init * getOperand (int i) const =0
virtual Init * Fold (Record *CurRec, MultiClass *CurMultiClass) const =0
Init * convertInitializerTo (RecTy *Ty) const override
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
Init * getBit (unsigned Bit) const override
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const override
Init * convertInitListSlice (const std::vector< unsigned > &Elements) const override
RecTy * getFieldType (const std::string &FieldName) const override
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsString () const =0
getAsString - Convert this value to a string form.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * resolveReferences (Record &R, const RecordVal *RV) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Protected Member Functions
OpInit (InitKind K, RecTy *Type)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit , IK_FirstTypedInit , IK_BitsInit , IK_DagInit ,
IK_DefInit , IK_FieldInit , IK_IntInit , IK_ListInit ,
IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit , IK_UnOpInit ,
IK_LastOpInit , IK_StringInit , IK_VarInit , IK_VarListElementInit ,
IK_LastTypedInit , IK_UnsetInit , IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Detailed Description
OpInit - Base class for operators
Definition at line 857 of file Record.h.
Constructor & Destructor Documentation
OpInit()
llvm::OpInit::OpInit (InitKind K, RecTy * Type) inline explicit protected
Definition at line 862 of file Record.h.
Member Function Documentation
classof()
bool llvm::OpInit::classof (const Init * I) inline static
Definition at line 865 of file Record.h.
References I, llvm::Init::IK_FirstOpInit, and llvm::Init::IK_LastOpInit.
clone()
virtual OpInit * llvm::OpInit::clone (std::vector< Init * > & Operands) const pure virtual
Implemented in llvm::BinOpInit, llvm::TernOpInit, and llvm::UnOpInit.
References Operands.
Referenced by EvaluateOperation(), and ForeachHelper().
convertInitializerTo()
Init * llvm::OpInit::convertInitializerTo (RecTy * Ty) const inline override virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 879 of file Record.h.
Fold()
virtual Init * llvm::OpInit::Fold (Record * CurRec, MultiClass * CurMultiClass) const pure virtual
Implemented in llvm::BinOpInit, llvm::TernOpInit, and llvm::UnOpInit.
Referenced by EvaluateOperation(), ForeachHelper(), and resolveListElementReference().
getBit()
Init * OpInit::getBit (unsigned Bit) const override virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 747 of file Record.cpp.
References llvm::BitRecTy::get(), llvm::VarBitInit::get(), and llvm::TypedInit::getType().
getNumOperands()
virtual int llvm::OpInit::getNumOperands () const pure virtual
Implemented in llvm::BinOpInit, llvm::TernOpInit, and llvm::UnOpInit.
Referenced by EvaluateOperation(), and ForeachHelper().
getOperand()
virtual Init * llvm::OpInit::getOperand (int i) const pure virtual
Implemented in llvm::BinOpInit, llvm::TernOpInit, and llvm::UnOpInit.
Referenced by EvaluateOperation(), and ForeachHelper().
resolveListElementReference()
Init * OpInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const override virtual
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences. If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 725 of file Record.cpp.
References llvm::dyn_cast(), Fold(), llvm::VarListElementInit::get(), llvm::TypedInit::resolveListElementReference(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
Record.h
Record.cpp