LLVM: llvm::MachineDominanceFrontier Class Reference
LLVM API Documentation
llvm::MachineDominanceFrontier Class Reference
#include <MachineDominanceFrontier.h>
Public Types
typedef DominatorTreeBase< MachineBasicBlock > DomTreeT
typedef DomTreeNodeBase< MachineBasicBlock > DomTreeNodeT
typedef DominanceFrontierBase< MachineBasicBlock >::DomSetType DomSetType
typedef DominanceFrontierBase< MachineBasicBlock >::iterator iterator
typedef DominanceFrontierBase< MachineBasicBlock >::const_iterator const_iterator
Public Member Functions
void operator= (const MachineDominanceFrontier &) LLVM_DELETED_FUNCTION
MachineDominanceFrontier (const MachineDominanceFrontier &) LLVM_DELETED_FUNCTION
MachineDominanceFrontier ()
DominanceFrontierBase< MachineBasicBlock > & getBase ()
const std::vector< MachineBasicBlock * > & getRoots () const
MachineBasicBlock * getRoot () const
bool isPostDominator () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator find (MachineBasicBlock *B)
const_iterator find (MachineBasicBlock *B) const
iterator addBasicBlock (MachineBasicBlock *BB, const DomSetType &frontier)
void removeBlock (MachineBasicBlock *BB)
void addToFrontier (iterator I, MachineBasicBlock *Node)
void removeFromFrontier (iterator I, MachineBasicBlock *Node)
bool compareDomSet (DomSetType &DS1, const DomSetType &DS2) const
bool compare (DominanceFrontierBase< MachineBasicBlock > &Other) const
bool runOnMachineFunction (MachineFunction &F) override
void releaseMemory () override
void getAnalysisUsage (AnalysisUsage &AU) const override
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 20 of file MachineDominanceFrontier.h.
Member Typedef Documentation
const_iterator
typedef DominanceFrontierBase<MachineBasicBlock>::const_iterator llvm::MachineDominanceFrontier::const_iterator
Definition at line 27 of file MachineDominanceFrontier.h.
DomSetType
typedef DominanceFrontierBase<MachineBasicBlock>::DomSetType llvm::MachineDominanceFrontier::DomSetType
Definition at line 25 of file MachineDominanceFrontier.h.
DomTreeNodeT
typedef DomTreeNodeBase<MachineBasicBlock> llvm::MachineDominanceFrontier::DomTreeNodeT
Definition at line 24 of file MachineDominanceFrontier.h.
DomTreeT
typedef DominatorTreeBase<MachineBasicBlock> llvm::MachineDominanceFrontier::DomTreeT
Definition at line 23 of file MachineDominanceFrontier.h.
iterator
typedef DominanceFrontierBase<MachineBasicBlock>::iterator llvm::MachineDominanceFrontier::iterator
Definition at line 26 of file MachineDominanceFrontier.h.
Constructor & Destructor Documentation
MachineDominanceFrontier() [1/2]
llvm::MachineDominanceFrontier::MachineDominanceFrontier (const MachineDominanceFrontier &)
References LLVM_DELETED_FUNCTION, and MachineDominanceFrontier().
Referenced by MachineDominanceFrontier(), MachineDominanceFrontier(), and operator=().
MachineDominanceFrontier() [2/2]
machine Machine Dominance Frontier true MachineDominanceFrontier::MachineDominanceFrontier ()
Definition at line 32 of file MachineDominanceFrontier.cpp.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::initializeMachineDominanceFrontierPass(), MachineDominanceFrontier(), and llvm::MachineFunctionPass::MachineFunctionPass().
Member Function Documentation
addBasicBlock()
iterator llvm::MachineDominanceFrontier::addBasicBlock (MachineBasicBlock * BB, const DomSetType & frontier) inline
Definition at line 76 of file MachineDominanceFrontier.h.
addToFrontier()
void llvm::MachineDominanceFrontier::addToFrontier (iterator I, MachineBasicBlock * Node) inline
Definition at line 84 of file MachineDominanceFrontier.h.
References I.
begin() [1/2]
iterator llvm::MachineDominanceFrontier::begin () inline
Definition at line 52 of file MachineDominanceFrontier.h.
begin() [2/2]
const_iterator llvm::MachineDominanceFrontier::begin () const inline
Definition at line 56 of file MachineDominanceFrontier.h.
compare()
bool llvm::MachineDominanceFrontier::compare (DominanceFrontierBase< MachineBasicBlock > & Other) const inline
Definition at line 96 of file MachineDominanceFrontier.h.
compareDomSet()
bool llvm::MachineDominanceFrontier::compareDomSet (DomSetType & DS1, const DomSetType & DS2) const inline
Definition at line 92 of file MachineDominanceFrontier.h.
end() [1/2]
iterator llvm::MachineDominanceFrontier::end () inline
Definition at line 60 of file MachineDominanceFrontier.h.
end() [2/2]
const_iterator llvm::MachineDominanceFrontier::end () const inline
Definition at line 64 of file MachineDominanceFrontier.h.
find() [1/2]
iterator llvm::MachineDominanceFrontier::find (MachineBasicBlock * B) inline
Definition at line 68 of file MachineDominanceFrontier.h.
find() [2/2]
const_iterator llvm::MachineDominanceFrontier::find (MachineBasicBlock * B) const inline
Definition at line 72 of file MachineDominanceFrontier.h.
getAnalysisUsage()
void MachineDominanceFrontier::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 50 of file MachineDominanceFrontier.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getBase()
DominanceFrontierBase< MachineBasicBlock > & llvm::MachineDominanceFrontier::getBase () inline
Definition at line 36 of file MachineDominanceFrontier.h.
Referenced by runOnMachineFunction().
getRoot()
MachineBasicBlock * llvm::MachineDominanceFrontier::getRoot () const inline
Definition at line 44 of file MachineDominanceFrontier.h.
getRoots()
const std::vector< MachineBasicBlock * > & llvm::MachineDominanceFrontier::getRoots () const inline
Definition at line 40 of file MachineDominanceFrontier.h.
isPostDominator()
bool llvm::MachineDominanceFrontier::isPostDominator () const inline
Definition at line 48 of file MachineDominanceFrontier.h.
operator=()
void llvm::MachineDominanceFrontier::operator= (const MachineDominanceFrontier &)
References LLVM_DELETED_FUNCTION, and MachineDominanceFrontier().
releaseMemory()
void MachineDominanceFrontier::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 46 of file MachineDominanceFrontier.cpp.
Referenced by runOnMachineFunction().
removeBlock()
void llvm::MachineDominanceFrontier::removeBlock (MachineBasicBlock * BB) inline
Definition at line 80 of file MachineDominanceFrontier.h.
removeFromFrontier()
void llvm::MachineDominanceFrontier::removeFromFrontier (iterator I, MachineBasicBlock * Node) inline
Definition at line 88 of file MachineDominanceFrontier.h.
References I.
runOnMachineFunction()
bool MachineDominanceFrontier::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 40 of file MachineDominanceFrontier.cpp.
References llvm::Pass::getAnalysis(), getBase(), and releaseMemory().
Member Data Documentation
ID
char MachineDominanceFrontier::ID = 0 static
Definition at line 32 of file MachineDominanceFrontier.h.
Referenced by MachineDominanceFrontier().
The documentation for this class was generated from the following files:
MachineDominanceFrontier.h
MachineDominanceFrontier.cpp