LLVM: llvm::object::Archive::child_iterator Class Reference
LLVM API Documentation
llvm::object::Archive::child_iterator Class Reference
#include <Archive.h>
Public Member Functions
child_iterator ()
child_iterator (const Child &c)
const Child * operator-> () const
const Child & operator* () const
bool operator== (const child_iterator &other) const
bool operator!= (const child_iterator &other) const
bool operator< (const child_iterator &other) const
child_iterator & operator++ ()
Detailed Description
Definition at line 99 of file Archive.h.
Constructor & Destructor Documentation
child_iterator() [1/2]
llvm::object::Archive::child_iterator::child_iterator () inline
Definition at line 103 of file Archive.h.
Referenced by operator!=(), operator++(), operator<(), and operator==().
child_iterator() [2/2]
llvm::object::Archive::child_iterator::child_iterator (const Child & c) inline
Definition at line 104 of file Archive.h.
Member Function Documentation
operator!=()
bool llvm::object::Archive::child_iterator::operator!= (const child_iterator & other) const inline
Definition at line 112 of file Archive.h.
References child_iterator().
operator*()
const Child & llvm::object::Archive::child_iterator::operator* () const inline
Definition at line 106 of file Archive.h.
operator++()
child_iterator & llvm::object::Archive::child_iterator::operator++ () inline
Definition at line 120 of file Archive.h.
References child_iterator().
operator->()
const Child * llvm::object::Archive::child_iterator::operator-> () const inline
Definition at line 105 of file Archive.h.
operator<()
bool llvm::object::Archive::child_iterator::operator< (const child_iterator & other) const inline
Definition at line 116 of file Archive.h.
References child_iterator().
operator==()
bool llvm::object::Archive::child_iterator::operator== (const child_iterator & other) const inline
Definition at line 108 of file Archive.h.
References child_iterator().
The documentation for this class was generated from the following file:
Archive.h