LLVM: llvm::MaskedStoreSDNode Class Reference
LLVM API Documentation
llvm::MaskedStoreSDNode Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
MaskedStoreSDNode (unsigned Order, DebugLoc dl, SDValue *Operands, unsigned numOperands, SDVTList VTs, bool isTrunc, EVT MemVT, MachineMemOperand *MMO)
bool isTruncatingStore () const
const SDValue & getValue () const
Public Member Functions inherited from llvm::MaskedLoadStoreSDNode
MaskedLoadStoreSDNode (ISD::NodeType NodeTy, unsigned Order, DebugLoc dl, SDValue *Operands, unsigned numOperands, SDVTList VTs, EVT MemVT, MachineMemOperand *MMO)
const SDValue & getBasePtr () const
const SDValue & getMask () const
Public Member Functions inherited from llvm::MemSDNode
MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, EVT MemoryVT, MachineMemOperand *MMO)
MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, ArrayRef< SDValue > Ops, EVT MemoryVT, MachineMemOperand *MMO)
bool readMem () const
bool writeMem () const
unsigned getOriginalAlignment () const
Returns alignment and volatility of the memory access.
unsigned getAlignment () const
unsigned getRawSubclassData () const
bool isVolatile () const
bool isNonTemporal () const
bool isInvariant () const
AtomicOrdering getOrdering () const
SynchronizationScope getSynchScope () const
int64_t getSrcValueOffset () const
AAMDNodes getAAInfo () const
Returns the AA info that describes the dereference.
const MDNode * getRanges () const
Returns the Ranges that describes the dereference.
EVT getMemoryVT () const
getMemoryVT - Return the type of the in-memory value.
MachineMemOperand * getMemOperand () const
const MachinePointerInfo & getPointerInfo () const
unsigned getAddressSpace () const
getAddressSpace - Return the address space for the associated pointer
void refineAlignment (const MachineMemOperand *NewMMO)
const SDValue & getChain () const
const SDValue & getBasePtr () const
Public Member Functions inherited from llvm::SDNode
unsigned getOpcode () const
bool isTargetOpcode () const
bool isTargetMemoryOpcode () const
bool isMemIntrinsic () const
bool isMachineOpcode () const
unsigned getMachineOpcode () const
bool getHasDebugValue () const
getHasDebugValue - get this bit.
void setHasDebugValue (bool b)
setHasDebugValue - set this bit.
bool use_empty () const
bool hasOneUse () const
size_t use_size () const
int getNodeId () const
void setNodeId (int Id)
setNodeId - Set unique node id.
unsigned getIROrder () const
void setIROrder (unsigned Order)
const DebugLoc getDebugLoc () const
getDebugLoc - Return the source location info.
void setDebugLoc (const DebugLoc dl)
use_iterator use_begin () const
iterator_range< use_iterator > uses ()
iterator_range< use_iterator > uses () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
bool hasAnyUseOfValue (unsigned Value) const
bool isOnlyUserOf (SDNode *N) const
bool isOperandOf (SDNode *N) const
bool isPredecessorOf (const SDNode *N) const
bool hasPredecessor (const SDNode *N) const
bool hasPredecessorHelper (const SDNode *N, SmallPtrSetImpl< const SDNode * > &Visited, SmallVectorImpl< const SDNode * > &Worklist) const
unsigned getNumOperands () const
uint64_t getConstantOperandVal (unsigned Num) const
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< SDUse > ops () const
SDVTList getVTList () const
SDNode * getGluedNode () const
const SDNode * getGluedMachineNode () const
SDNode * getGluedUser () const
unsigned getNumValues () const
EVT getValueType (unsigned ResNo) const
MVT getSimpleValueType (unsigned ResNo) const
unsigned getValueSizeInBits (unsigned ResNo) const
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=nullptr) const
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printr (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printrFull (raw_ostream &O, const SelectionDAG *G=nullptr) const
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=nullptr, unsigned depth=100) const
void dump () const
dump - Dump this node, for debugging.
void dumpr () const
dumpr - Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
void dumpr (const SelectionDAG *G) const
void dumprFull (const SelectionDAG *G=nullptr) const
void dumprWithDepth (const SelectionDAG *G=nullptr, unsigned depth=100) const
void Profile (FoldingSetNodeID &ID) const
void addUse (SDUse &U)
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node< SDNode >
SDNode * getPrevNode ()
Get the previous node, or 0 for the list head.
SDNode * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::MaskedLoadStoreSDNode
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::MemSDNode
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::SDNode
static use_iterator use_end ()
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Friends
class SelectionDAG
Additional Inherited Members
Public Types inherited from llvm::SDNode
typedef SDUse * op_iterator
typedef const EVT * value_iterator
Protected Member Functions inherited from llvm::SDNode
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs, ArrayRef< SDValue > Ops)
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs)
void InitOperands (SDUse *Ops, const SDValue &Op0)
InitOperands - Initialize the operands list of this with 1 operand.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1)
InitOperands - Initialize the operands list of this with 2 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2)
InitOperands - Initialize the operands list of this with 3 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2, const SDValue &Op3)
InitOperands - Initialize the operands list of this with 4 operands.
void InitOperands (SDUse *Ops, const SDValue *Vals, unsigned N)
InitOperands - Initialize the operands list of this with N operands.
void DropOperands ()
Protected Member Functions inherited from llvm::ilist_node< SDNode >
ilist_node ()
Static Protected Member Functions inherited from llvm::SDNode
static SDVTList getSDVTList (EVT VT)
Protected Attributes inherited from llvm::MemSDNode
MachineMemOperand * MMO
MMO - Memory reference information.
Protected Attributes inherited from llvm::SDNode
uint16_t SubclassData: 14
Detailed Description
MaskedStoreSDNode - This class is used to represent an MSTORE node
Definition at line 1992 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
MaskedStoreSDNode()
llvm::MaskedStoreSDNode::MaskedStoreSDNode (unsigned Order, DebugLoc dl, SDValue * Operands, unsigned numOperands, SDVTList VTs, bool isTrunc, EVT MemVT, MachineMemOperand * MMO) inline
Definition at line 1996 of file SelectionDAGNodes.h.
References llvm::MaskedLoadStoreSDNode::MaskedLoadStoreSDNode(), llvm::MemSDNode::MMO, Operands, and llvm::SDNode::SubclassData.
Member Function Documentation
classof()
bool llvm::MaskedStoreSDNode::classof (const SDNode * N) inline static
Definition at line 2010 of file SelectionDAGNodes.h.
References llvm::ISD::MSTORE, and N.
getValue()
const SDValue & llvm::MaskedStoreSDNode::getValue () const inline
Definition at line 2008 of file SelectionDAGNodes.h.
References llvm::SDNode::getOperand().
Referenced by PerformMSTORECombine().
isTruncatingStore()
bool llvm::MaskedStoreSDNode::isTruncatingStore () const inline
isTruncatingStore - Return true if the op does a truncation before store. For integers this is the same as doing a TRUNCATE and storing the result. For floats, it is the same as doing an FP_ROUND and storing the result.
Definition at line 2006 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
Referenced by PerformMSTORECombine().
Friends And Related Symbol Documentation
SelectionDAG
friend class SelectionDAG friend
Definition at line 1995 of file SelectionDAGNodes.h.
References SelectionDAG.
Referenced by SelectionDAG.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h