LLVM: llvm::MipsMCCodeEmitter Class Reference
LLVM API Documentation
llvm::MipsMCCodeEmitter Class Reference
#include <MipsMCCodeEmitter.h>
Public Member Functions
MipsMCCodeEmitter (const MCInstrInfo &mcii, MCContext &Ctx_, bool IsLittle)
~MipsMCCodeEmitter ()
void EmitByte (unsigned char C, raw_ostream &OS) const
void EmitInstruction (uint64_t Val, unsigned Size, const MCSubtargetInfo &STI, raw_ostream &OS) const
void EncodeInstruction (const MCInst &MI, raw_ostream &OS, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const override
uint64_t getBinaryCodeForInstr (const MCInst &MI, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getJumpTargetOpValue (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getJumpTargetOpValueMM (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getUImm5Lsl2Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getSImm3Lsa2Value (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getUImm6Lsl2Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getSImm9AddiuspValue (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getBranchTargetOpValue (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getBranchTarget7OpValueMM (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getBranchTargetOpValueMM (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getBranchTarget21OpValue (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getBranchTarget26OpValue (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getJumpOffset16OpValue (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMachineOpValue (const MCInst &MI, const MCOperand &MO, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMSAMemEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMemEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMemEncodingMMImm4 (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMemEncodingMMImm4Lsl1 (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMemEncodingMMImm4Lsl2 (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMemEncodingMMSPImm5Lsl2 (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMemEncodingMMImm12 (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMemEncodingMMImm4sp (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getSizeExtEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getSizeInsEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getLSAImmEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getSimm19Lsl2Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getSimm18Lsl3Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getUImm3Mod8Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getUImm4AndValue (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getRegisterPairOpValue (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getExprOpValue (const MCExpr *Expr, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getRegisterListOpValue (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getRegisterListOpValue16 (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
Public Member Functions inherited from llvm::MCCodeEmitter
virtual ~MCCodeEmitter ()
virtual void reset ()
Lifetime management.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter ()
Detailed Description
Definition at line 33 of file MipsMCCodeEmitter.h.
Constructor & Destructor Documentation
MipsMCCodeEmitter()
llvm::MipsMCCodeEmitter::MipsMCCodeEmitter (const MCInstrInfo & mcii, MCContext & Ctx_, bool IsLittle) inline
Definition at line 43 of file MipsMCCodeEmitter.h.
~MipsMCCodeEmitter()
llvm::MipsMCCodeEmitter::~MipsMCCodeEmitter () inline
Definition at line 46 of file MipsMCCodeEmitter.h.
Member Function Documentation
EmitByte()
void MipsMCCodeEmitter::EmitByte (unsigned char C, raw_ostream & OS) const
Definition at line 120 of file MipsMCCodeEmitter.cpp.
EmitInstruction()
void MipsMCCodeEmitter::EmitInstruction (uint64_t Val, unsigned Size, const MCSubtargetInfo & STI, raw_ostream & OS) const
Definition at line 124 of file MipsMCCodeEmitter.cpp.
EncodeInstruction()
void MipsMCCodeEmitter::EncodeInstruction (const MCInst & MI, raw_ostream & OS, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const override virtual
EncodeInstruction - Emit the instruction. Size the instruction with Desc.getSize().
Implements llvm::MCCodeEmitter.
Definition at line 144 of file MipsMCCodeEmitter.cpp.
References EncodeInstruction().
Referenced by EncodeInstruction().
getBinaryCodeForInstr()
uint64_t llvm::MipsMCCodeEmitter::getBinaryCodeForInstr (const MCInst & MI, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getBranchTarget21OpValue()
unsigned MipsMCCodeEmitter::getBranchTarget21OpValue (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getBranchTarget21OpValue - Return binary encoding of the branch target operand. If the machine operand requires relocation, record the relocation and return zero.
Definition at line 271 of file MipsMCCodeEmitter.cpp.
References getBranchTarget21OpValue().
Referenced by getBranchTarget21OpValue().
getBranchTarget26OpValue()
unsigned MipsMCCodeEmitter::getBranchTarget26OpValue (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getBranchTarget26OpValue - Return binary encoding of the branch target operand. If the machine operand requires relocation, record the relocation and return zero.
Definition at line 293 of file MipsMCCodeEmitter.cpp.
References getBranchTarget26OpValue().
Referenced by getBranchTarget26OpValue().
getBranchTarget7OpValueMM()
unsigned MipsMCCodeEmitter::getBranchTarget7OpValueMM (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getBranchTarget7OpValueMM - Return binary encoding of the microMIPS branch target operand. If the machine operand requires relocation, record the relocation and return zero.
Definition at line 226 of file MipsMCCodeEmitter.cpp.
References getBranchTargetOpValueMM().
getBranchTargetOpValue()
unsigned MipsMCCodeEmitter::getBranchTargetOpValue (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getBranchTargetOpValue - Return binary encoding of the branch target operand. If the machine operand requires relocation, record the relocation and return zero.
Definition at line 204 of file MipsMCCodeEmitter.cpp.
References getBranchTargetOpValue().
Referenced by getBranchTargetOpValue().
getBranchTargetOpValueMM()
unsigned MipsMCCodeEmitter::getBranchTargetOpValueMM (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getBranchTargetOpValue - Return binary encoding of the microMIPS branch target operand. If the machine operand requires relocation, record the relocation and return zero.
Definition at line 248 of file MipsMCCodeEmitter.cpp.
References getBranchTargetOpValueMM().
Referenced by getBranchTarget7OpValueMM(), and getBranchTargetOpValueMM().
getExprOpValue()
unsigned MipsMCCodeEmitter::getExprOpValue (const MCExpr * Expr, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 431 of file MipsMCCodeEmitter.cpp.
References llvm::Unknown.
getJumpOffset16OpValue()
unsigned MipsMCCodeEmitter::getJumpOffset16OpValue (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getJumpOffset16OpValue - Return binary encoding of the jump target operand. If the machine operand requires relocation, record the relocation and return zero.
Definition at line 315 of file MipsMCCodeEmitter.cpp.
References getJumpOffset16OpValue().
Referenced by getJumpOffset16OpValue().
getJumpTargetOpValue()
unsigned MipsMCCodeEmitter::getJumpTargetOpValue (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getJumpTargetOpValue - Return binary encoding of the jump target operand. If the machine operand requires relocation, record the relocation and return zero.
Definition at line 334 of file MipsMCCodeEmitter.cpp.
References getJumpTargetOpValue().
Referenced by getJumpTargetOpValue().
getJumpTargetOpValueMM()
unsigned MipsMCCodeEmitter::getJumpTargetOpValueMM (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 352 of file MipsMCCodeEmitter.cpp.
References getJumpTargetOpValueMM().
Referenced by getJumpTargetOpValueMM().
getLSAImmEncoding()
unsigned MipsMCCodeEmitter::getLSAImmEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 787 of file MipsMCCodeEmitter.cpp.
getMachineOpValue()
unsigned MipsMCCodeEmitter::getMachineOpValue (const MCInst & MI, const MCOperand & MO, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getMachineOpValue - Return binary encoding of operand. If the machine operand requires relocation, record the relocation and return zero.
Definition at line 583 of file MipsMCCodeEmitter.cpp.
getMemEncoding()
unsigned MipsMCCodeEmitter::getMemEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getMemEncoding - Return binary encoding of memory related operand. If the offset operand requires relocation, record the relocation.
Definition at line 649 of file MipsMCCodeEmitter.cpp.
getMemEncodingMMImm12()
unsigned MipsMCCodeEmitter::getMemEncodingMMImm12 (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 716 of file MipsMCCodeEmitter.cpp.
getMemEncodingMMImm4()
unsigned MipsMCCodeEmitter::getMemEncodingMMImm4 (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 660 of file MipsMCCodeEmitter.cpp.
getMemEncodingMMImm4Lsl1()
unsigned MipsMCCodeEmitter::getMemEncodingMMImm4Lsl1 (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 674 of file MipsMCCodeEmitter.cpp.
getMemEncodingMMImm4Lsl2()
unsigned MipsMCCodeEmitter::getMemEncodingMMImm4Lsl2 (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 688 of file MipsMCCodeEmitter.cpp.
getMemEncodingMMImm4sp()
unsigned MipsMCCodeEmitter::getMemEncodingMMImm4sp (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 739 of file MipsMCCodeEmitter.cpp.
getMemEncodingMMSPImm5Lsl2()
unsigned MipsMCCodeEmitter::getMemEncodingMMSPImm5Lsl2 (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 702 of file MipsMCCodeEmitter.cpp.
getMSAMemEncoding()
unsigned MipsMCCodeEmitter::getMSAMemEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getMSAMemEncoding - Return binary encoding of memory operand for LD/ST instructions.
Definition at line 605 of file MipsMCCodeEmitter.cpp.
getRegisterListOpValue()
unsigned MipsMCCodeEmitter::getRegisterListOpValue (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 875 of file MipsMCCodeEmitter.cpp.
getRegisterListOpValue16()
unsigned MipsMCCodeEmitter::getRegisterListOpValue16 (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 895 of file MipsMCCodeEmitter.cpp.
getRegisterPairOpValue()
unsigned MipsMCCodeEmitter::getRegisterPairOpValue (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 902 of file MipsMCCodeEmitter.cpp.
getSimm18Lsl3Encoding()
unsigned MipsMCCodeEmitter::getSimm18Lsl3Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 817 of file MipsMCCodeEmitter.cpp.
getSimm19Lsl2Encoding()
unsigned MipsMCCodeEmitter::getSimm19Lsl2Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 796 of file MipsMCCodeEmitter.cpp.
References getSimm19Lsl2Encoding().
Referenced by getSimm19Lsl2Encoding().
getSImm3Lsa2Value()
unsigned MipsMCCodeEmitter::getSImm3Lsa2Value (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 389 of file MipsMCCodeEmitter.cpp.
getSImm9AddiuspValue()
unsigned MipsMCCodeEmitter::getSImm9AddiuspValue (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 417 of file MipsMCCodeEmitter.cpp.
getSizeExtEncoding()
unsigned MipsMCCodeEmitter::getSizeExtEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 764 of file MipsMCCodeEmitter.cpp.
getSizeInsEncoding()
unsigned MipsMCCodeEmitter::getSizeInsEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 775 of file MipsMCCodeEmitter.cpp.
getUImm3Mod8Encoding()
unsigned MipsMCCodeEmitter::getUImm3Mod8Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 838 of file MipsMCCodeEmitter.cpp.
getUImm4AndValue()
unsigned MipsMCCodeEmitter::getUImm4AndValue (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 847 of file MipsMCCodeEmitter.cpp.
getUImm5Lsl2Encoding()
unsigned MipsMCCodeEmitter::getUImm5Lsl2Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 370 of file MipsMCCodeEmitter.cpp.
References getUImm5Lsl2Encoding().
Referenced by getUImm5Lsl2Encoding().
getUImm6Lsl2Encoding()
unsigned MipsMCCodeEmitter::getUImm6Lsl2Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 403 of file MipsMCCodeEmitter.cpp.
The documentation for this class was generated from the following files:
MipsMCCodeEmitter.h
MipsMCCodeEmitter.cpp