LLVM: llvm::MSP430Subtarget Class Reference
LLVM API Documentation
llvm::MSP430Subtarget Class Reference
#include <MSP430Subtarget.h>
Public Member Functions
MSP430Subtarget (const std::string &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
MSP430Subtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
const TargetFrameLowering * getFrameLowering () const override
const MSP430InstrInfo * getInstrInfo () const override
const DataLayout * getDataLayout () const override
const TargetRegisterInfo * getRegisterInfo () const override
const MSP430TargetLowering * getTargetLowering () const override
const MSP430SelectionDAGInfo * getSelectionDAGInfo () const override
Detailed Description
Definition at line 32 of file MSP430Subtarget.h.
Constructor & Destructor Documentation
MSP430Subtarget()
MSP430Subtarget::MSP430Subtarget (const std::string & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 33 of file MSP430Subtarget.cpp.
References initializeSubtargetDependencies().
Referenced by initializeSubtargetDependencies().
Member Function Documentation
getDataLayout()
const DataLayout * llvm::MSP430Subtarget::getDataLayout () const inline override
Definition at line 58 of file MSP430Subtarget.h.
getFrameLowering()
const TargetFrameLowering * llvm::MSP430Subtarget::getFrameLowering () const inline override
Definition at line 54 of file MSP430Subtarget.h.
getInstrInfo()
const MSP430InstrInfo * llvm::MSP430Subtarget::getInstrInfo () const inline override
Definition at line 57 of file MSP430Subtarget.h.
getRegisterInfo()
const TargetRegisterInfo * llvm::MSP430Subtarget::getRegisterInfo () const inline override
Definition at line 59 of file MSP430Subtarget.h.
getSelectionDAGInfo()
const MSP430SelectionDAGInfo * llvm::MSP430Subtarget::getSelectionDAGInfo () const inline override
Definition at line 65 of file MSP430Subtarget.h.
getTargetLowering()
const MSP430TargetLowering * llvm::MSP430Subtarget::getTargetLowering () const inline override
Definition at line 62 of file MSP430Subtarget.h.
initializeSubtargetDependencies()
MSP430Subtarget & MSP430Subtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 28 of file MSP430Subtarget.cpp.
References MSP430Subtarget(), and ParseSubtargetFeatures().
Referenced by MSP430Subtarget().
ParseSubtargetFeatures()
void llvm::MSP430Subtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
Referenced by initializeSubtargetDependencies().
The documentation for this class was generated from the following files:
MSP430Subtarget.h
MSP430Subtarget.cpp