LLVM: llvm::CGSCCAnalysisManagerModuleProxy::Result Class Reference
LLVM API Documentation
llvm::CGSCCAnalysisManagerModuleProxy::Result Class Reference
#include <CGSCCPassManager.h>
Public Member Functions
Result (CGSCCAnalysisManager &CGAM)
Result (const Result &Arg)
Result (Result &&Arg)
Result & operator= (Result RHS)
~Result ()
CGSCCAnalysisManager & getManager ()
Accessor for the CGSCCAnalysisManager.
bool invalidate (Module &M, const PreservedAnalyses &PA)
Handler for invalidation of the module.
Detailed Description
Definition at line 54 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
Result() [1/3]
llvm::CGSCCAnalysisManagerModuleProxy::Result::Result (CGSCCAnalysisManager & CGAM) inline explicit
Definition at line 56 of file CGSCCPassManager.h.
Referenced by operator=(), Result(), and Result().
Result() [2/3]
llvm::CGSCCAnalysisManagerModuleProxy::Result::Result (const Result & Arg) inline
Definition at line 59 of file CGSCCPassManager.h.
References Result().
Result() [3/3]
llvm::CGSCCAnalysisManagerModuleProxy::Result::Result (Result && Arg) inline
Definition at line 60 of file CGSCCPassManager.h.
References Result().
~Result()
CGSCCAnalysisManagerModuleProxy::Result::~Result ()
Definition at line 24 of file CGSCCPassManager.cpp.
Member Function Documentation
getManager()
CGSCCAnalysisManager & llvm::CGSCCAnalysisManagerModuleProxy::Result::getManager () inline
Accessor for the CGSCCAnalysisManager.
Definition at line 68 of file CGSCCPassManager.h.
invalidate()
bool CGSCCAnalysisManagerModuleProxy::Result::invalidate (Module & M, const PreservedAnalyses & PA)
Handler for invalidation of the module.
If this analysis itself is preserved, then we assume that the call graph of the module hasn't changed and thus we don't need to invalidate all cached data associated with a SCC* in the CGSCCAnalysisManager.
Regardless of whether this analysis is marked as preserved, all of the analyses in the CGSCCAnalysisManager are potentially invalidated based on the set of preserved analyses.
Definition at line 30 of file CGSCCPassManager.cpp.
References llvm::CGSCCAnalysisManagerModuleProxy::ID(), and llvm::PreservedAnalyses::preserved().
operator=()
Result & llvm::CGSCCAnalysisManagerModuleProxy::Result::operator= (Result RHS) inline
Definition at line 61 of file CGSCCPassManager.h.
References Result(), and std::swap().
The documentation for this class was generated from the following files:
CGSCCPassManager.h
CGSCCPassManager.cpp