LLVM: llvm::XCoreSelectionDAGInfo Class Reference
LLVM API Documentation
llvm::XCoreSelectionDAGInfo Class Reference
#include <XCoreSelectionDAGInfo.h>
Public Member Functions
XCoreSelectionDAGInfo (const DataLayout &DL)
~XCoreSelectionDAGInfo ()
SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override
Public Member Functions inherited from llvm::TargetSelectionDAGInfo
TargetSelectionDAGInfo (const DataLayout *DL)
virtual ~TargetSelectionDAGInfo ()
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
virtual SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
Additional Inherited Members
Protected Member Functions inherited from llvm::TargetSelectionDAGInfo
const DataLayout * getDataLayout () const
Detailed Description
Definition at line 23 of file XCoreSelectionDAGInfo.h.
Constructor & Destructor Documentation
XCoreSelectionDAGInfo()
XCoreSelectionDAGInfo::XCoreSelectionDAGInfo (const DataLayout & DL) explicit
Definition at line 19 of file XCoreSelectionDAGInfo.cpp.
~XCoreSelectionDAGInfo()
XCoreSelectionDAGInfo::~XCoreSelectionDAGInfo ()
Definition at line 22 of file XCoreSelectionDAGInfo.cpp.
Member Function Documentation
EmitTargetCodeForMemcpy()
SDValue XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override virtual
EmitTargetCodeForMemcpy - Emit target-specific code that performs a memcpy. This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 25 of file XCoreSelectionDAGInfo.cpp.
References Align, llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getExternalSymbol(), llvm::DataLayout::getIntPtrType(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::SDValue::getValueType(), llvm::Type::getVoidTy(), llvm::TargetLowering::LowerCallTo(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::RTLIB::MEMCPY, llvm::TargetLowering::ArgListEntry::Node, llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), and llvm::TargetLowering::ArgListEntry::Ty.
The documentation for this class was generated from the following files:
XCoreSelectionDAGInfo.h
XCoreSelectionDAGInfo.cpp