LLVM: llvm::DWARFContext Class Reference
LLVM API Documentation
llvm::DWARFContext Class Reference abstract
#include <DWARFContext.h>
Public Types
typedef DWARFUnitSection< DWARFCompileUnit >::iterator_range cu_iterator_range
typedef DWARFUnitSection< DWARFTypeUnit >::iterator_range tu_iterator_range
typedef iterator_range< std::vector< DWARFUnitSection< DWARFTypeUnit > >::iterator > tu_section_iterator_range
typedef MapVector< object::SectionRef, DWARFSection, std::map< object::SectionRef, unsigned > > TypeSectionMap
Public Types inherited from llvm::DIContext
enum DIContextKind { CK_DWARF }
Public Member Functions
DWARFContext ()
void dump (raw_ostream &OS, DIDumpType DumpType=DIDT_All) override
cu_iterator_range compile_units ()
Get compile units in this context.
tu_section_iterator_range type_unit_sections ()
Get type units in this context.
cu_iterator_range dwo_compile_units ()
Get compile units in the DWO context.
tu_section_iterator_range dwo_type_unit_sections ()
Get type units in the DWO context.
unsigned getNumCompileUnits ()
Get the number of compile units in this context.
unsigned getNumTypeUnits ()
Get the number of compile units in this context.
unsigned getNumDWOCompileUnits ()
Get the number of compile units in the DWO context.
unsigned getNumDWOTypeUnits ()
Get the number of compile units in the DWO context.
DWARFCompileUnit * getCompileUnitAtIndex (unsigned index)
Get the compile unit at the specified index for this compile unit.
DWARFCompileUnit * getDWOCompileUnitAtIndex (unsigned index)
Get the compile unit at the specified index for the DWO compile units.
const DWARFDebugAbbrev * getDebugAbbrev ()
Get a pointer to the parsed DebugAbbrev object.
const DWARFDebugLoc * getDebugLoc ()
Get a pointer to the parsed DebugLoc object.
const DWARFDebugAbbrev * getDebugAbbrevDWO ()
Get a pointer to the parsed dwo abbreviations object.
const DWARFDebugLocDWO * getDebugLocDWO ()
Get a pointer to the parsed DebugLoc object.
const DWARFDebugAranges * getDebugAranges ()
Get a pointer to the parsed DebugAranges object.
const DWARFDebugFrame * getDebugFrame ()
Get a pointer to the parsed frame information object.
const DWARFDebugLine::LineTable * getLineTableForUnit (DWARFUnit *cu)
Get a pointer to a parsed line table corresponding to a compile unit.
DILineInfo getLineInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DILineInfoTable getLineInfoForAddressRange (uint64_t Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DIInliningInfo getInliningInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
virtual bool isLittleEndian () const =0
virtual uint8_t getAddressSize () const =0
virtual const DWARFSection & getInfoSection ()=0
virtual const TypeSectionMap & getTypesSections ()=0
virtual StringRef getAbbrevSection ()=0
virtual const DWARFSection & getLocSection ()=0
virtual StringRef getARangeSection ()=0
virtual StringRef getDebugFrameSection ()=0
virtual const DWARFSection & getLineSection ()=0
virtual StringRef getStringSection ()=0
virtual StringRef getRangeSection ()=0
virtual StringRef getPubNamesSection ()=0
virtual StringRef getPubTypesSection ()=0
virtual StringRef getGnuPubNamesSection ()=0
virtual StringRef getGnuPubTypesSection ()=0
virtual const DWARFSection & getInfoDWOSection ()=0
virtual const TypeSectionMap & getTypesDWOSections ()=0
virtual StringRef getAbbrevDWOSection ()=0
virtual const DWARFSection & getLineDWOSection ()=0
virtual const DWARFSection & getLocDWOSection ()=0
virtual StringRef getStringDWOSection ()=0
virtual StringRef getStringOffsetDWOSection ()=0
virtual StringRef getRangeDWOSection ()=0
virtual StringRef getAddrSection ()=0
virtual const DWARFSection & getAppleNamesSection ()=0
virtual const DWARFSection & getAppleTypesSection ()=0
virtual const DWARFSection & getAppleNamespacesSection ()=0
virtual const DWARFSection & getAppleObjCSection ()=0
Public Member Functions inherited from llvm::DIContext
DIContextKind getKind () const
DIContext (DIContextKind K)
virtual ~DIContext ()
Static Public Member Functions
static bool classof (const DIContext *DICtx)
static bool isSupportedVersion (unsigned version)
Static Public Member Functions inherited from llvm::DIContext
static DIContext * getDWARFContext (const object::ObjectFile &Obj)
getDWARFContext - get a context for binary DWARF data.
Detailed Description
DWARFContext This data structure is the top level entity that deals with dwarf debug information parsing. The actual data is supplied through pure virtual methods that a concrete implementation provides.
Definition at line 32 of file DWARFContext.h.
Member Typedef Documentation
cu_iterator_range
typedef DWARFUnitSection<DWARFCompileUnit>::iterator_range llvm::DWARFContext::cu_iterator_range
Definition at line 75 of file DWARFContext.h.
tu_iterator_range
typedef DWARFUnitSection<DWARFTypeUnit>::iterator_range llvm::DWARFContext::tu_iterator_range
Definition at line 76 of file DWARFContext.h.
tu_section_iterator_range
typedef iterator_range<std::vector<DWARFUnitSection<DWARFTypeUnit> >::iterator> llvm::DWARFContext::tu_section_iterator_range
Definition at line 77 of file DWARFContext.h.
TypeSectionMap
typedef MapVector<object::SectionRef, DWARFSection, std::map<object::SectionRef, unsigned> > llvm::DWARFContext::TypeSectionMap
Definition at line 171 of file DWARFContext.h.
Constructor & Destructor Documentation
DWARFContext()
llvm::DWARFContext::DWARFContext () inline
Definition at line 67 of file DWARFContext.h.
References llvm::DIContext::CK_DWARF, and llvm::DIContext::DIContext().
Member Function Documentation
classof()
bool llvm::DWARFContext::classof (const DIContext * DICtx) inline static
Definition at line 69 of file DWARFContext.h.
References llvm::DIContext::CK_DWARF, llvm::DIContext::DIContext(), and llvm::DIContext::getKind().
compile_units()
cu_iterator_range llvm::DWARFContext::compile_units () inline
Get compile units in this context.
Definition at line 80 of file DWARFContext.h.
Referenced by dump(), and llvm::DWARFDebugAranges::generate().
dump()
void DWARFContext::dump (raw_ostream & OS, DIDumpType DumpType = DIDT_All) override virtual
Implements llvm::DIContext.
Definition at line 74 of file DWARFContext.cpp.
References llvm::DWARFDebugLine::LineTable::clear(), compile_units(), llvm::DIDT_Abbrev, llvm::DIDT_AbbrevDwo, llvm::DIDT_All, llvm::DIDT_AppleNames, llvm::DIDT_AppleNamespaces, llvm::DIDT_AppleObjC, llvm::DIDT_AppleTypes, llvm::DIDT_Aranges, llvm::DIDT_Frames, llvm::DIDT_GnuPubnames, llvm::DIDT_GnuPubtypes, llvm::DIDT_Info, llvm::DIDT_InfoDwo, llvm::DIDT_Line, llvm::DIDT_LineDwo, llvm::DIDT_Loc, llvm::DIDT_LocDwo, llvm::DIDT_Pubnames, llvm::DIDT_Pubtypes, llvm::DIDT_Ranges, llvm::DIDT_Str, llvm::DIDT_StrDwo, llvm::DIDT_StrOffsetsDwo, llvm::DIDT_Types, llvm::DIDT_TypesDwo, llvm::DWARFDebugAbbrev::dump(), llvm::DWARFDebugArangeSet::dump(), llvm::DWARFDebugFrame::dump(), llvm::DWARFDebugLine::LineTable::dump(), llvm::DWARFDebugLoc::dump(), llvm::DWARFDebugLocDWO::dump(), llvm::DWARFDebugRangeList::dump(), dumpAccelSection(), dumpPubSection(), llvm::dwarf::DW_AT_stmt_list, dwo_compile_units(), dwo_type_unit_sections(), llvm::DWARFDebugArangeSet::extract(), llvm::DWARFDebugRangeList::extract(), llvm::format(), getAppleNamespacesSection(), getAppleNamesSection(), getAppleObjCSection(), getAppleTypesSection(), getARangeSection(), llvm::DataExtractor::getCStr(), getDebugAbbrev(), getDebugAbbrevDWO(), getDebugFrame(), getDebugLoc(), getDebugLocDWO(), getGnuPubNamesSection(), getGnuPubTypesSection(), getLineDWOSection(), getLineSection(), getNumDWOCompileUnits(), getNumDWOTypeUnits(), getNumTypeUnits(), getPubNamesSection(), getPubTypesSection(), getRangeSection(), getStringDWOSection(), getStringOffsetDWOSection(), getStringSection(), llvm::DataExtractor::getU32(), isLittleEndian(), llvm::DWARFDebugLine::LineTable::parse(), llvm::DWARFDebugLine::Prologue::parse(), llvm::DWARFDebugLine::LineTable::Prologue, llvm::StringRef::size(), and type_unit_sections().
dwo_compile_units()
cu_iterator_range llvm::DWARFContext::dwo_compile_units () inline
Get compile units in the DWO context.
Definition at line 92 of file DWARFContext.h.
Referenced by dump().
dwo_type_unit_sections()
tu_section_iterator_range llvm::DWARFContext::dwo_type_unit_sections () inline
Get type units in the DWO context.
Definition at line 98 of file DWARFContext.h.
Referenced by dump().
getAbbrevDWOSection()
virtual StringRef llvm::DWARFContext::getAbbrevDWOSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by getDebugAbbrevDWO().
getAbbrevSection()
virtual StringRef llvm::DWARFContext::getAbbrevSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by getDebugAbbrev().
getAddressSize()
virtual uint8_t llvm::DWARFContext::getAddressSize () const pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by getDebugFrame().
getAddrSection()
virtual StringRef llvm::DWARFContext::getAddrSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
getAppleNamespacesSection()
virtual const DWARFSection & llvm::DWARFContext::getAppleNamespacesSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getAppleNamesSection()
virtual const DWARFSection & llvm::DWARFContext::getAppleNamesSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getAppleObjCSection()
virtual const DWARFSection & llvm::DWARFContext::getAppleObjCSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getAppleTypesSection()
virtual const DWARFSection & llvm::DWARFContext::getAppleTypesSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getARangeSection()
virtual StringRef llvm::DWARFContext::getARangeSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump(), and llvm::DWARFDebugAranges::generate().
getCompileUnitAtIndex()
DWARFCompileUnit * llvm::DWARFContext::getCompileUnitAtIndex (unsigned index) inline
Get the compile unit at the specified index for this compile unit.
Definition at line 128 of file DWARFContext.h.
Referenced by getDebugLoc().
getDebugAbbrev()
const DWARFDebugAbbrev * DWARFContext::getDebugAbbrev ()
Get a pointer to the parsed DebugAbbrev object.
Definition at line 251 of file DWARFContext.cpp.
References getAbbrevSection(), and isLittleEndian().
Referenced by dump().
getDebugAbbrevDWO()
const DWARFDebugAbbrev * DWARFContext::getDebugAbbrevDWO ()
Get a pointer to the parsed dwo abbreviations object.
Definition at line 262 of file DWARFContext.cpp.
References getAbbrevDWOSection(), and isLittleEndian().
Referenced by dump().
getDebugAranges()
const DWARFDebugAranges * DWARFContext::getDebugAranges ()
Get a pointer to the parsed DebugAranges object.
Definition at line 294 of file DWARFContext.cpp.
References llvm::DWARFDebugAranges::generate().
getDebugFrame()
const DWARFDebugFrame * DWARFContext::getDebugFrame ()
Get a pointer to the parsed frame information object.
Definition at line 303 of file DWARFContext.cpp.
References getAddressSize(), getDebugFrameSection(), and isLittleEndian().
Referenced by dump().
getDebugFrameSection()
virtual StringRef llvm::DWARFContext::getDebugFrameSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by getDebugFrame().
getDebugLoc()
const DWARFDebugLoc * DWARFContext::getDebugLoc ()
Get a pointer to the parsed DebugLoc object.
Definition at line 272 of file DWARFContext.cpp.
References getCompileUnitAtIndex(), getLocSection(), getNumCompileUnits(), and isLittleEndian().
Referenced by dump().
getDebugLocDWO()
const DWARFDebugLocDWO * DWARFContext::getDebugLocDWO ()
Get a pointer to the parsed DebugLoc object.
Definition at line 284 of file DWARFContext.cpp.
References getLocDWOSection(), and isLittleEndian().
Referenced by dump().
getDWOCompileUnitAtIndex()
DWARFCompileUnit * llvm::DWARFContext::getDWOCompileUnitAtIndex (unsigned index) inline
Get the compile unit at the specified index for the DWO compile units.
Definition at line 134 of file DWARFContext.h.
getGnuPubNamesSection()
virtual StringRef llvm::DWARFContext::getGnuPubNamesSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getGnuPubTypesSection()
virtual StringRef llvm::DWARFContext::getGnuPubTypesSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getInfoDWOSection()
virtual const DWARFSection & llvm::DWARFContext::getInfoDWOSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
getInfoSection()
virtual const DWARFSection & llvm::DWARFContext::getInfoSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
getInliningInfoForAddress()
DIInliningInfo DWARFContext::getInliningInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 462 of file DWARFContext.cpp.
References llvm::DIInliningInfo::addFrame(), llvm::DILineInfo::Column, llvm::DWARFDebugInfoEntryInlinedChain::DIEs, llvm::DILineInfo::FileName, llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, llvm::DWARFDebugInfoEntryMinimal::getCallerFrame(), llvm::DWARFDebugLine::LineTable::getFileLineInfoForAddress(), llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), getLineTableForUnit(), llvm::DWARFDebugInfoEntryMinimal::getSubroutineName(), llvm::DILineInfo::Line, Name, and llvm::DWARFDebugInfoEntryInlinedChain::U.
getLineDWOSection()
virtual const DWARFSection & llvm::DWARFContext::getLineDWOSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getLineInfoForAddress()
DILineInfo DWARFContext::getLineInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 403 of file DWARFContext.cpp.
References llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, getFunctionNameForAddress(), and getLineTableForUnit().
getLineInfoForAddressRange()
DILineInfoTable DWARFContext::getLineInfoForAddressRange (uint64_t Address, uint64_t Size, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 420 of file DWARFContext.cpp.
References llvm::DWARFDebugLine::Row::Address, llvm::DILineInfo::Column, llvm::DWARFDebugLine::Row::Column, llvm::DWARFDebugLine::Row::File, llvm::DILineInfo::FileName, llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), getFunctionNameForAddress(), getLineTableForUnit(), llvm::DILineInfo::Line, llvm::DWARFDebugLine::Row::Line, llvm::DWARFDebugLine::LineTable::lookupAddressRange(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::DWARFDebugLine::LineTable::Rows.
getLineSection()
virtual const DWARFSection & llvm::DWARFContext::getLineSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump(), and getLineTableForUnit().
getLineTableForUnit()
const DWARFLineTable * DWARFContext::getLineTableForUnit (DWARFUnit * cu)
Get a pointer to a parsed line table corresponding to a compile unit.
Definition at line 324 of file DWARFContext.cpp.
References llvm::dwarf::DW_AT_stmt_list, llvm::DWARFUnit::getAddressByteSize(), llvm::DWARFDebugInfoEntryMinimal::getAttributeValueAsSectionOffset(), llvm::DWARFUnit::getCompileUnitDIE(), getLineSection(), and isLittleEndian().
Referenced by llvm::DWARFDebugInfoEntryMinimal::dumpAttribute(), getInliningInfoForAddress(), getLineInfoForAddress(), and getLineInfoForAddressRange().
getLocDWOSection()
virtual const DWARFSection & llvm::DWARFContext::getLocDWOSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by getDebugLocDWO().
getLocSection()
virtual const DWARFSection & llvm::DWARFContext::getLocSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by getDebugLoc().
getNumCompileUnits()
unsigned llvm::DWARFContext::getNumCompileUnits () inline
Get the number of compile units in this context.
Definition at line 104 of file DWARFContext.h.
Referenced by getDebugLoc().
getNumDWOCompileUnits()
unsigned llvm::DWARFContext::getNumDWOCompileUnits () inline
Get the number of compile units in the DWO context.
Definition at line 116 of file DWARFContext.h.
Referenced by dump().
getNumDWOTypeUnits()
unsigned llvm::DWARFContext::getNumDWOTypeUnits () inline
Get the number of compile units in the DWO context.
Definition at line 122 of file DWARFContext.h.
Referenced by dump().
getNumTypeUnits()
unsigned llvm::DWARFContext::getNumTypeUnits () inline
Get the number of compile units in this context.
Definition at line 110 of file DWARFContext.h.
Referenced by dump().
getPubNamesSection()
virtual StringRef llvm::DWARFContext::getPubNamesSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getPubTypesSection()
virtual StringRef llvm::DWARFContext::getPubTypesSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getRangeDWOSection()
virtual StringRef llvm::DWARFContext::getRangeDWOSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
getRangeSection()
virtual StringRef llvm::DWARFContext::getRangeSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getStringDWOSection()
virtual StringRef llvm::DWARFContext::getStringDWOSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getStringOffsetDWOSection()
virtual StringRef llvm::DWARFContext::getStringOffsetDWOSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getStringSection()
virtual StringRef llvm::DWARFContext::getStringSection () pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump().
getTypesDWOSections()
virtual const TypeSectionMap & llvm::DWARFContext::getTypesDWOSections () pure virtual
Implemented in llvm::DWARFContextInMemory.
getTypesSections()
virtual const TypeSectionMap & llvm::DWARFContext::getTypesSections () pure virtual
Implemented in llvm::DWARFContextInMemory.
isLittleEndian()
virtual bool llvm::DWARFContext::isLittleEndian () const pure virtual
Implemented in llvm::DWARFContextInMemory.
Referenced by dump(), llvm::DWARFDebugAranges::generate(), getDebugAbbrev(), getDebugAbbrevDWO(), getDebugFrame(), getDebugLoc(), getDebugLocDWO(), and getLineTableForUnit().
isSupportedVersion()
bool llvm::DWARFContext::isSupportedVersion (unsigned version) inline static
Definition at line 200 of file DWARFContext.h.
Referenced by llvm::DWARFUnit::extractImpl().
type_unit_sections()
tu_section_iterator_range llvm::DWARFContext::type_unit_sections () inline
Get type units in this context.
Definition at line 86 of file DWARFContext.h.
Referenced by dump().
The documentation for this class was generated from the following files:
DWARFContext.h
DWARFContext.cpp