LLVM: llvm::VarInit Class Reference
LLVM API Documentation
llvm::VarInit Class Reference
#include <Record.h>
Public Member Functions
Init * convertInitializerTo (RecTy *Ty) const override
const std::string & getName () const
Init * getNameInit () const
std::string getNameInitAsString () const
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
RecTy * getFieldType (const std::string &FieldName) const override
Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const override
Init * resolveReferences (Record &R, const RecordVal *RV) const override
Init * getBit (unsigned Bit) const override
std::string getAsString () const override
getAsString - Convert this value to a string form.
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const override
Init * convertInitListSlice (const std::vector< unsigned > &Elements) const override
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static VarInit * get (const std::string &VN, RecTy *T)
static VarInit * get (Init *VN, RecTy *T)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit , IK_FirstTypedInit , IK_BitsInit , IK_DagInit ,
IK_DefInit , IK_FieldInit , IK_IntInit , IK_ListInit ,
IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit , IK_UnOpInit ,
IK_LastOpInit , IK_StringInit , IK_VarInit , IK_VarListElementInit ,
IK_LastTypedInit , IK_UnsetInit , IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
VarInit - 'Opcode' - Represent a reference to an entire variable object.
Definition at line 1053 of file Record.h.
Member Function Documentation
classof()
bool llvm::VarInit::classof (const Init * I) inline static
Definition at line 1065 of file Record.h.
References I, and llvm::Init::IK_VarInit.
convertInitializerTo()
Init * llvm::VarInit::convertInitializerTo (RecTy * Ty) const inline override virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 1071 of file Record.h.
get() [1/2]
VarInit * VarInit::get (const std::string & VN, RecTy * T) static
Definition at line 1322 of file Record.cpp.
References llvm::StringInit::get(), and get().
Referenced by llvm::TernOpInit::Fold(), llvm::UnOpInit::Fold(), and get().
get() [2/2]
VarInit * VarInit::get (Init * VN, RecTy * T) static
Definition at line 1327 of file Record.cpp.
References I.
getAsString()
std::string llvm::VarInit::getAsString () const inline override virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 1097 of file Record.h.
References getName().
Referenced by llvm::TernOpInit::Fold().
getBit()
Init * VarInit::getBit (unsigned Bit) const override virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1344 of file Record.cpp.
References llvm::BitRecTy::get(), llvm::VarBitInit::get(), and llvm::TypedInit::getType().
getFieldInit()
Init * VarInit::getFieldInit (Record & R, const RecordVal * RV, const std::string & FieldName) const override virtual
getFieldInit - This method complements getFieldType to return the initializer for the specified field. If getFieldType returns non-null this method should return non-null, otherwise it returns null.
Reimplemented from llvm::Init.
Definition at line 1384 of file Record.cpp.
References llvm::Init::getFieldInit(), llvm::TypedInit::getType(), llvm::Record::getValue(), I, and llvm::isa().
getFieldType()
RecTy * VarInit::getFieldType (const std::string & FieldName) const override virtual
getFieldType - This method is used to implement the FieldInit class. Implementors of this method should return the type of the named field if they are of record type.
Reimplemented from llvm::TypedInit.
Definition at line 1377 of file Record.cpp.
References llvm::dyn_cast(), llvm::TypedInit::getType(), and llvm::RecordVal::getValue().
getName()
const std::string & VarInit::getName () const
Definition at line 1338 of file Record.cpp.
References llvm::dyn_cast(), getNameInit(), and llvm::StringInit::getValue().
Referenced by llvm::TernOpInit::Fold(), and getAsString().
getNameInit()
Init * llvm::VarInit::getNameInit () const inline
Definition at line 1076 of file Record.h.
Referenced by getName(), getNameInitAsString(), and resolveListElementReference().
getNameInitAsString()
std::string llvm::VarInit::getNameInitAsString () const inline
Definition at line 1077 of file Record.h.
References llvm::Init::getAsUnquotedString(), and getNameInit().
resolveListElementReference()
Init * VarInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const override virtual
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences. If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 1350 of file Record.cpp.
References llvm::dyn_cast(), llvm::VarListElementInit::get(), llvm::ListInit::getElement(), llvm::RecordVal::getNameInit(), getNameInit(), llvm::ListInit::getSize(), llvm::Record::getValue(), llvm::RecordVal::getValue(), llvm::isa(), llvm::Record::isTemplateArg(), and VI.
resolveReferences()
Init * VarInit::resolveReferences (Record & R, const RecordVal * RV) const override virtual
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time they expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1405 of file Record.cpp.
References llvm::Record::getValue(), and llvm::isa().
The documentation for this class was generated from the following files:
Record.h
Record.cpp