LLVM: llvm::cl::OptionValueCopy< DataType > Class Template Reference
LLVM API Documentation
llvm::cl::OptionValueCopy< DataType > Class Template Reference
#include <CommandLine.h>
Public Member Functions
OptionValueCopy ()
bool hasValue () const
const DataType & getValue () const
void setValue (const DataType &V)
bool compare (const DataType &V) const
bool compare (const GenericOptionValue &V) const override
Public Member Functions inherited from llvm::cl::GenericOptionValue
virtual ~GenericOptionValue ()
Detailed Description
template<class DataType>
class llvm::cl::OptionValueCopy< DataType >
Definition at line 378 of file CommandLine.h.
Constructor & Destructor Documentation
OptionValueCopy()
template<class DataType> llvm::cl::OptionValueCopy< DataType >::OptionValueCopy () inline
Definition at line 383 of file CommandLine.h.
Referenced by compare().
Member Function Documentation
compare() [1/2]
template<class DataType> bool llvm::cl::OptionValueCopy< DataType >::compare (const DataType & V) const inline
Definition at line 397 of file CommandLine.h.
Referenced by compare().
compare() [2/2]
template<class DataType> bool llvm::cl::OptionValueCopy< DataType >::compare (const GenericOptionValue & V) const inline override virtual
Implements llvm::cl::GenericOptionValue.
Definition at line 399 of file CommandLine.h.
References compare(), and OptionValueCopy().
getValue()
template<class DataType> const DataType & llvm::cl::OptionValueCopy< DataType >::getValue () const inline
Definition at line 387 of file CommandLine.h.
hasValue()
template<class DataType> bool llvm::cl::OptionValueCopy< DataType >::hasValue () const inline
Definition at line 385 of file CommandLine.h.
setValue()
template<class DataType> void llvm::cl::OptionValueCopy< DataType >::setValue (const DataType & V) inline
Definition at line 392 of file CommandLine.h.
The documentation for this class was generated from the following file:
CommandLine.h