LLVM: RegisterOperands Class Reference
LLVM API Documentation
RegisterOperands Class Reference
Public Member Functions
RegisterOperands (const TargetRegisterInfo *tri, const MachineRegisterInfo *mri, bool ID=false)
void collect (const MachineOperand &MO)
Push this operand's register onto the correct vector.
Public Attributes
SmallVector< unsigned, 8 > Uses
SmallVector< unsigned, 8 > Defs
SmallVector< unsigned, 8 > DeadDefs
Protected Member Functions
void pushRegUnits (unsigned Reg, SmallVectorImpl< unsigned > &RegUnits)
Detailed Description
Collect this instruction's unique uses and defs into SmallVectors for processing defs and uses in order.
FIXME: always ignore tied opers
Definition at line 311 of file RegisterPressure.cpp.
Constructor & Destructor Documentation
RegisterOperands()
RegisterOperands::RegisterOperands (const TargetRegisterInfo * tri, const MachineRegisterInfo * mri, bool ID = false) inline
Definition at line 321 of file RegisterPressure.cpp.
Member Function Documentation
collect()
void RegisterOperands::collect (const MachineOperand & MO) inline
Push this operand's register onto the correct vector.
Definition at line 326 of file RegisterPressure.cpp.
References DeadDefs, Defs, llvm::MachineOperand::getReg(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), pushRegUnits(), llvm::MachineOperand::readsReg(), and Uses.
Referenced by collectOperands().
pushRegUnits()
void RegisterOperands::pushRegUnits (unsigned Reg, SmallVectorImpl< unsigned > & RegUnits) inline protected
Definition at line 342 of file RegisterPressure.cpp.
References containsReg(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by collect().
Member Data Documentation
DeadDefs
SmallVector<unsigned, 8> RegisterOperands::DeadDefs
Definition at line 319 of file RegisterPressure.cpp.
Referenced by llvm::RegPressureTracker::advance(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), collect(), collectOperands(), and llvm::RegPressureTracker::recede().
Defs
SmallVector<unsigned, 8> RegisterOperands::Defs
Definition at line 318 of file RegisterPressure.cpp.
Referenced by llvm::RegPressureTracker::advance(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), collect(), collectOperands(), collectPDiff(), and llvm::RegPressureTracker::recede().
Uses
SmallVector<unsigned, 8> RegisterOperands::Uses
Definition at line 317 of file RegisterPressure.cpp.
Referenced by llvm::RegPressureTracker::advance(), llvm::RegPressureTracker::bumpDownwardPressure(), llvm::RegPressureTracker::bumpUpwardPressure(), collect(), collectPDiff(), and llvm::RegPressureTracker::recede().
The documentation for this class was generated from the following file:
RegisterPressure.cpp