LLVM: llvm::BitCodeAbbrev Class Reference
LLVM API Documentation
llvm::BitCodeAbbrev Class Reference
#include <BitCodes.h>
Public Member Functions
unsigned getNumOperandInfos () const
const BitCodeAbbrevOp & getOperandInfo (unsigned N) const
void Add (const BitCodeAbbrevOp &OpInfo)
Public Member Functions inherited from llvm::RefCountedBase< BitCodeAbbrev >
RefCountedBase ()
void Retain () const
void Release () const
Friends
class RefCountedBase< BitCodeAbbrev >
Detailed Description
BitCodeAbbrev - This class represents an abbreviation record. An abbreviation allows a complex record that has redundancy to be stored in a specialized format instead of the fully-general, fully-vbr, format.
Definition at line 165 of file BitCodes.h.
Member Function Documentation
Add()
void llvm::BitCodeAbbrev::Add (const BitCodeAbbrevOp & OpInfo) inline
Definition at line 179 of file BitCodes.h.
Referenced by llvm::BitstreamCursor::ReadAbbrevRecord(), WriteBlockInfo(), WriteConstants(), WriteModuleInfo(), WriteModuleMetadata(), and WriteTypeTable().
getNumOperandInfos()
unsigned llvm::BitCodeAbbrev::getNumOperandInfos () const inline
Definition at line 172 of file BitCodes.h.
Referenced by llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().
getOperandInfo()
const BitCodeAbbrevOp & llvm::BitCodeAbbrev::getOperandInfo (unsigned N) const inline
Definition at line 175 of file BitCodes.h.
References N.
Referenced by llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().
Friends And Related Symbol Documentation
RefCountedBase< BitCodeAbbrev >
friend class RefCountedBase< BitCodeAbbrev > friend
Definition at line 167 of file BitCodes.h.
The documentation for this class was generated from the following file:
BitCodes.h