LLVM: llvm::IRBuilderBase Class Reference
LLVM API Documentation
llvm::IRBuilderBase Class Reference
Common base class shared among various IRBuilders.
#include <IRBuilder.h>
Classes
class FastMathFlagGuard
class InsertPoint
InsertPoint - A saved insertion point.
class InsertPointGuard
Public Member Functions
IRBuilderBase (LLVMContext &context, MDNode *FPMathTag=nullptr)
void ClearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
BasicBlock * GetInsertBlock () const
BasicBlock::iterator GetInsertPoint () const
LLVMContext & getContext () const
void SetInsertPoint (BasicBlock *TheBB)
This specifies that created instructions should be appended to the end of the specified block.
void SetInsertPoint (Instruction *I)
This specifies that created instructions should be inserted before the specified instruction.
void SetInsertPoint (BasicBlock *TheBB, BasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
void SetInsertPoint (Use &U)
Find the nearest point that dominates this use, and specify that created instructions should be inserted at this point.
void SetCurrentDebugLocation (const DebugLoc &L)
Set location information used by debugging information.
DebugLoc getCurrentDebugLocation () const
Get location information used by debugging information.
void SetInstDebugLocation (Instruction *I) const
If this builder has a current debug location, set it on the specified instruction.
Type * getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
InsertPoint saveIP () const
Returns the current insert point.
InsertPoint saveAndClearIP ()
Returns the current insert point, clearing it in the process.
void restoreIP (InsertPoint IP)
Sets the current insert point to a previously-saved location.
MDNode * getDefaultFPMathTag () const
Get the floating point math metadata being used.
FastMathFlags getFastMathFlags () const
Get the flags to be applied to created floating point ops.
void clearFastMathFlags ()
Clear the fast-math flags.
void SetDefaultFPMathTag (MDNode *FPMathTag)
Set the floating point math metadata to be used.
void SetFastMathFlags (FastMathFlags NewFMF)
Set the fast-math flags to be used with generated fp-math operators.
Value * CreateGlobalString (StringRef Str, const Twine &Name="")
Make a new global variable with initializer type i8*.
ConstantInt * getInt1 (bool V)
Get a constant value representing either true or false.
ConstantInt * getTrue ()
Get the constant value for i1 true.
ConstantInt * getFalse ()
Get the constant value for i1 false.
ConstantInt * getInt8 (uint8_t C)
Get a constant 8-bit value.
ConstantInt * getInt16 (uint16_t C)
Get a constant 16-bit value.
ConstantInt * getInt32 (uint32_t C)
Get a constant 32-bit value.
ConstantInt * getInt64 (uint64_t C)
Get a constant 64-bit value.
ConstantInt * getIntN (unsigned N, uint64_t C)
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
ConstantInt * getInt (const APInt &AI)
Get a constant integer value.
IntegerType * getInt1Ty ()
Fetch the type representing a single bit.
IntegerType * getInt8Ty ()
Fetch the type representing an 8-bit integer.
IntegerType * getInt16Ty ()
Fetch the type representing a 16-bit integer.
IntegerType * getInt32Ty ()
Fetch the type representing a 32-bit integer.
IntegerType * getInt64Ty ()
Fetch the type representing a 64-bit integer.
IntegerType * getIntNTy (unsigned N)
Fetch the type representing an N-bit integer.
Type * getHalfTy ()
Fetch the type representing a 16-bit floating point value.
Type * getFloatTy ()
Fetch the type representing a 32-bit floating point value.
Type * getDoubleTy ()
Fetch the type representing a 64-bit floating point value.
Type * getVoidTy ()
Fetch the type representing void.
PointerType * getInt8PtrTy (unsigned AddrSpace=0)
Fetch the type representing a pointer to an 8-bit integer value.
IntegerType * getIntPtrTy (const DataLayout *DL, unsigned AddrSpace=0)
Fetch the type representing a pointer to an integer value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memset to the specified pointer and the specified value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemCpy (Value *Dst, Value *Src, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memcpy between the specified pointers.
CallInst * CreateMemCpy (Value *Dst, Value *Src, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemMove (Value *Dst, Value *Src, uint64_t Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memmove between the specified pointers.
CallInst * CreateMemMove (Value *Dst, Value *Src, Value *Size, unsigned Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateLifetimeStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.start intrinsic.
CallInst * CreateLifetimeEnd (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.end intrinsic.
CallInst * CreateMaskedLoad (Value *Ptr, unsigned Align, Value *Mask, Value *PassThru=0, const Twine &Name="")
Create a call to Masked Load intrinsic.
CallInst * CreateMaskedStore (Value *Val, Value *Ptr, unsigned Align, Value *Mask)
Create a call to Masked Store intrinsic.
CallInst * CreateAssumption (Value *Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
CallInst * CreateGCStatepoint (Value *ActualCallee, ArrayRef< Value * > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCResult (Instruction *Statepoint, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
CallInst * CreateGCRelocate (Instruction *Statepoint, int BaseOffset, int DerivedOffset, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
Protected Attributes
BasicBlock * BB
BasicBlock::iterator InsertPt
LLVMContext & Context
MDNode * DefaultFPMathTag
FastMathFlags FMF
Detailed Description
Common base class shared among various IRBuilders.
Definition at line 50 of file IRBuilder.h.
Constructor & Destructor Documentation
IRBuilderBase()
llvm::IRBuilderBase::IRBuilderBase (LLVMContext & context, MDNode * FPMathTag = nullptr) inline
Definition at line 61 of file IRBuilder.h.
References ClearInsertionPoint(), Context, DefaultFPMathTag, and FMF.
Referenced by llvm::IRBuilderBase::FastMathFlagGuard::FastMathFlagGuard(), llvm::IRBuilderBase::InsertPointGuard::InsertPointGuard(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), and llvm::IRBuilder< true, TargetFolder >::IRBuilder().
Member Function Documentation
clearFastMathFlags()
void llvm::IRBuilderBase::clearFastMathFlags () inline
Clear the fast-math flags.
Definition at line 183 of file IRBuilder.h.
References FMF.
ClearInsertionPoint()
void llvm::IRBuilderBase::ClearInsertionPoint () inline
Clear the insertion point: created instructions will not be inserted into a block.
Definition at line 72 of file IRBuilder.h.
References BB, and InsertPt.
Referenced by IRBuilderBase(), restoreIP(), and saveAndClearIP().
CreateAssumption()
CallInst * IRBuilderBase::CreateAssumption (Value * Cond)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
Definition at line 177 of file IRBuilder.cpp.
References llvm::Intrinsic::assume, BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1Ty(), and llvm::Value::getType().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption().
CreateGCRelocate()
CallInst * IRBuilderBase::CreateGCRelocate (Instruction * Statepoint, int BaseOffset, int DerivedOffset, Type * ResultType, const Twine & Name = "")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
Definition at line 284 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::experimental_gc_relocate, llvm::Intrinsic::getDeclaration(), getInt32(), and Name.
CreateGCResult()
CallInst * IRBuilderBase::CreateGCResult (Instruction * Statepoint, Type * ResultType, const Twine & Name = "")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
Definition at line 263 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::experimental_gc_result_float, llvm::Intrinsic::experimental_gc_result_int, llvm::Intrinsic::experimental_gc_result_ptr, llvm::Intrinsic::getDeclaration(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm_unreachable, and Name.
CreateGCStatepoint()
CallInst * IRBuilderBase::CreateGCStatepoint (Value * ActualCallee, ArrayRef< Value * > CallArgs, ArrayRef< Value * > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine & Name = "")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
Definition at line 233 of file IRBuilder.cpp.
References BB, llvm::ArrayRef< T >::begin(), llvm::cast(), createCallHelper(), llvm::ArrayRef< T >::end(), llvm::Intrinsic::experimental_gc_statepoint, llvm::Intrinsic::getDeclaration(), llvm::SequentialType::getElementType(), getInt32(), llvm::Value::getType(), llvm::isa(), Name, and llvm::ArrayRef< T >::size().
CreateGlobalString()
Value * IRBuilderBase::CreateGlobalString (StringRef Str, const Twine & Name = "")
Make a new global variable with initializer type i8*.
Make a new global variable with an initializer that has array of i8 type filled in with the null terminated string value specified. The new global variable will be marked mergable with any others of the same contents. If Name is specified, it is the name of the global variable created.
CreateGlobalString - Make a new global variable with an initializer that has array of i8 type filled in with the nul terminated string value specified. If Name is specified, it is the name of the global variable created.
Definition at line 26 of file IRBuilder.cpp.
References BB, Context, llvm::ConstantDataArray::getString(), llvm::Value::getType(), Name, llvm::GlobalValue::PrivateLinkage, llvm::Value::setName(), and llvm::GlobalValue::setUnnamedAddr().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateGlobalStringPtr().
CreateLifetimeEnd()
CallInst * IRBuilderBase::CreateLifetimeEnd (Value * Ptr, ConstantInt * Size = nullptr)
Create a lifetime.end intrinsic.
If the pointer isn't i8* it will be converted.
Definition at line 162 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt64(), getInt64Ty(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::isa(), and llvm::Intrinsic::lifetime_end.
Referenced by llvm::InlineFunction().
CreateLifetimeStart()
CallInst * IRBuilderBase::CreateLifetimeStart (Value * Ptr, ConstantInt * Size = nullptr)
Create a lifetime.start intrinsic.
If the pointer isn't i8* it will be converted.
Definition at line 147 of file IRBuilder.cpp.
References BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt64(), getInt64Ty(), llvm::ConstantInt::getType(), llvm::Value::getType(), llvm::isa(), and llvm::Intrinsic::lifetime_start.
Referenced by llvm::InlineFunction().
CreateMaskedLoad()
CallInst * IRBuilderBase::CreateMaskedLoad (Value * Ptr, unsigned Align, Value * Mask, Value * PassThru = 0, const Twine & Name = "")
Create a call to Masked Load intrinsic.
Create a call to a Masked Load intrinsic. Ptr - the base pointer for the load Align - alignment of the source location Mask - an vector of booleans which indicates what vector lanes should be accessed in memory PassThru - a pass-through value that is used to fill the masked-off lanes of the result Name - name of the result variable
Definition at line 195 of file IRBuilder.cpp.
References Align, llvm::cast(), llvm::UndefValue::get(), getInt32(), llvm::Value::getType(), llvm::Type::isPointerTy(), llvm::Type::isVectorTy(), llvm::Intrinsic::masked_load, and Name.
CreateMaskedStore()
CallInst * IRBuilderBase::CreateMaskedStore (Value * Val, Value * Ptr, unsigned Align, Value * Mask)
Create a call to Masked Store intrinsic.
Create a call to a Masked Store intrinsic. Val - the data to be stored, Ptr - the base pointer for the store Align - alignment of the destination location Mask - an vector of booleans which indicates what vector lanes should be accessed in memory
Definition at line 214 of file IRBuilder.cpp.
References Align, getInt32(), llvm::Value::getType(), and llvm::Intrinsic::masked_store.
CreateMemCpy() [1/2]
CallInst * llvm::IRBuilderBase::CreateMemCpy (Value * Dst, Value * Src, uint64_t Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert a memcpy between the specified pointers.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 388 of file IRBuilder.h.
References Align, CreateMemCpy(), and getInt64().
Referenced by CreateMemCpy(), and HandleByValArgumentInit().
CreateMemCpy() [2/2]
CallInst * IRBuilderBase::CreateMemCpy (Value * Dst, Value * Src, Value * Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * TBAAStructTag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 89 of file IRBuilder.cpp.
References Align, BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), getInt32(), llvm::Value::getType(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, llvm::LLVMContext::MD_tbaa_struct, llvm::Intrinsic::memcpy, and llvm::Instruction::setMetadata().
CreateMemMove() [1/2]
CallInst * llvm::IRBuilderBase::CreateMemMove (Value * Dst, Value * Src, uint64_t Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert a memmove between the specified pointers.
If the pointers aren't i8*, they will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 409 of file IRBuilder.h.
References Align, CreateMemMove(), and getInt64().
Referenced by CreateMemMove().
CreateMemMove() [2/2]
CallInst * IRBuilderBase::CreateMemMove (Value * Dst, Value * Src, Value * Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 120 of file IRBuilder.cpp.
References Align, BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), getInt32(), llvm::Value::getType(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, llvm::Intrinsic::memmove, and llvm::Instruction::setMetadata().
CreateMemSet() [1/2]
CallInst * llvm::IRBuilderBase::CreateMemSet (Value * Ptr, Value * Val, uint64_t Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr) inline
Create and insert a memset to the specified pointer and the specified value.
If the pointer isn't an i8*, it will be converted. If a TBAA tag is specified, it will be added to the instruction. Likewise with alias.scope and noalias tags.
Definition at line 370 of file IRBuilder.h.
References Align, CreateMemSet(), and getInt64().
Referenced by CreateMemSet().
CreateMemSet() [2/2]
CallInst * IRBuilderBase::CreateMemSet (Value * Ptr, Value * Val, Value * Size, unsigned Align, bool isVolatile = false, MDNode * TBAATag = nullptr, MDNode * ScopeTag = nullptr, MDNode * NoAliasTag = nullptr)
Definition at line 64 of file IRBuilder.cpp.
References Align, BB, createCallHelper(), llvm::Intrinsic::getDeclaration(), getInt1(), getInt32(), llvm::Value::getType(), llvm::LLVMContext::MD_alias_scope, llvm::LLVMContext::MD_noalias, llvm::LLVMContext::MD_tbaa, llvm::Intrinsic::memset, and llvm::Instruction::setMetadata().
getContext()
LLVMContext & llvm::IRBuilderBase::getContext () const inline
Definition at line 79 of file IRBuilder.h.
References Context.
Referenced by foldSelectICmpAnd(), generateUnsignedDivisionCode(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), and llvm::IRBuilder< true, TargetFolder >::IRBuilder().
getCurrentDebugLocation()
DebugLoc llvm::IRBuilderBase::getCurrentDebugLocation () const inline
Get location information used by debugging information.
Definition at line 123 of file IRBuilder.h.
Referenced by llvm::IRBuilderBase::InsertPointGuard::InsertPointGuard().
getCurrentFunctionReturnType()
Type * IRBuilderBase::getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
Definition at line 37 of file IRBuilder.cpp.
References BB.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAggregateRet().
getDefaultFPMathTag()
MDNode * llvm::IRBuilderBase::getDefaultFPMathTag () const inline
Get the floating point math metadata being used.
Definition at line 177 of file IRBuilder.h.
References DefaultFPMathTag.
getDoubleTy()
Type * llvm::IRBuilderBase::getDoubleTy () inline
Fetch the type representing a 64-bit floating point value.
Definition at line 341 of file IRBuilder.h.
References Context, and llvm::Type::getDoubleTy().
getFalse()
ConstantInt * llvm::IRBuilderBase::getFalse () inline
Get the constant value for i1 false.
Definition at line 261 of file IRBuilder.h.
References Context, and llvm::ConstantInt::getFalse().
Referenced by llvm::UpgradeIntrinsicCall().
getFastMathFlags()
FastMathFlags llvm::IRBuilderBase::getFastMathFlags () const inline
Get the flags to be applied to created floating point ops.
Definition at line 180 of file IRBuilder.h.
References FMF.
getFloatTy()
Type * llvm::IRBuilderBase::getFloatTy () inline
Fetch the type representing a 32-bit floating point value.
Definition at line 336 of file IRBuilder.h.
References Context, and llvm::Type::getFloatTy().
getHalfTy()
Type * llvm::IRBuilderBase::getHalfTy () inline
Fetch the type representing a 16-bit floating point value.
Definition at line 331 of file IRBuilder.h.
References Context, and llvm::Type::getHalfTy().
GetInsertBlock()
BasicBlock * llvm::IRBuilderBase::GetInsertBlock () const inline
Definition at line 77 of file IRBuilder.h.
References BB.
Referenced by callIntrinsic(), createCallHelper(), llvm::EmitBinaryFloatFnCall(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), llvm::EmitUnaryFloatFnCall(), generateUnsignedDivisionCode(), llvm::IRBuilderBase::InsertPointGuard::InsertPointGuard(), insertSinCosCall(), llvm::ARMTargetLowering::makeDMB(), saveAndClearIP(), and saveIP().
GetInsertPoint()
BasicBlock::iterator llvm::IRBuilderBase::GetInsertPoint () const inline
Definition at line 78 of file IRBuilder.h.
References InsertPt.
Referenced by createCallHelper(), llvm::expandDivision(), llvm::expandRemainder(), generateUnsignedDivisionCode(), llvm::IRBuilderBase::InsertPointGuard::InsertPointGuard(), saveAndClearIP(), and saveIP().
getInt()
ConstantInt * llvm::IRBuilderBase::getInt (const APInt & AI) inline
Get a constant integer value.
Definition at line 292 of file IRBuilder.h.
References Context, and llvm::ConstantInt::get().
getInt1()
ConstantInt * llvm::IRBuilderBase::getInt1 (bool V) inline
Get a constant value representing either true or false.
Definition at line 251 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getInt1Ty().
Referenced by CreateMemCpy(), CreateMemMove(), and CreateMemSet().
getInt16()
ConstantInt * llvm::IRBuilderBase::getInt16 (uint16_t C) inline
Get a constant 16-bit value.
Definition at line 271 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getInt16Ty().
getInt16Ty()
IntegerType * llvm::IRBuilderBase::getInt16Ty () inline
Fetch the type representing a 16-bit integer.
Definition at line 311 of file IRBuilder.h.
References Context, and llvm::Type::getInt16Ty().
Referenced by getInt16().
getInt1Ty()
IntegerType * llvm::IRBuilderBase::getInt1Ty () inline
Fetch the type representing a single bit.
Definition at line 301 of file IRBuilder.h.
References Context, and llvm::Type::getInt1Ty().
Referenced by CreateAssumption(), and getInt1().
getInt32()
ConstantInt * llvm::IRBuilderBase::getInt32 (uint32_t C) inline
Get a constant 32-bit value.
Definition at line 276 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getInt32Ty().
Referenced by appendToGlobalArray(), CreateGCRelocate(), CreateGCStatepoint(), CreateMaskedLoad(), CreateMaskedStore(), CreateMemCpy(), CreateMemMove(), CreateMemSet(), createOrdering(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), llvm::ARMTargetLowering::makeDMB(), OptimizeIntegerToVectorInsertions(), OptimizeIntToFloatBitCast(), ScalarizeMaskedLoad(), ScalarizeMaskedStore(), and llvm::UpgradeIntrinsicCall().
getInt32Ty()
IntegerType * llvm::IRBuilderBase::getInt32Ty () inline
Fetch the type representing a 32-bit integer.
Definition at line 316 of file IRBuilder.h.
References Context, and llvm::Type::getInt32Ty().
Referenced by appendToGlobalArray(), llvm::IRBuilder< true, TargetFolder >::CreateVectorSplat(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::EmitStrChr(), llvm::EmitStrNCmp(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainderUpTo32Bits(), getInt32(), and insertSinCosCall().
getInt64()
ConstantInt * llvm::IRBuilderBase::getInt64 (uint64_t C) inline
Get a constant 64-bit value.
Definition at line 281 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getInt64Ty().
Referenced by CreateLifetimeEnd(), CreateLifetimeStart(), CreateMemCpy(), CreateMemMove(), CreateMemSet(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), and HandleByValArgumentInit().
getInt64Ty()
IntegerType * llvm::IRBuilderBase::getInt64Ty () inline
Fetch the type representing a 64-bit integer.
Definition at line 321 of file IRBuilder.h.
References Context, and llvm::Type::getInt64Ty().
Referenced by CreateLifetimeEnd(), CreateLifetimeStart(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainderUpTo64Bits(), and getInt64().
getInt8()
ConstantInt * llvm::IRBuilderBase::getInt8 (uint8_t C) inline
Get a constant 8-bit value.
Definition at line 266 of file IRBuilder.h.
References llvm::ConstantInt::get(), and getInt8Ty().
Referenced by llvm::UpgradeIntrinsicCall().
getInt8PtrTy()
PointerType * llvm::IRBuilderBase::getInt8PtrTy (unsigned AddrSpace = 0) inline
Fetch the type representing a pointer to an 8-bit integer value.
Definition at line 351 of file IRBuilder.h.
References Context, and llvm::Type::getInt8PtrTy().
Referenced by appendToGlobalArray(), llvm::CastToCStr(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutS(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), and llvm::EmitStrNLen().
getInt8Ty()
IntegerType * llvm::IRBuilderBase::getInt8Ty () inline
Fetch the type representing an 8-bit integer.
Definition at line 306 of file IRBuilder.h.
References Context, and llvm::Type::getInt8Ty().
Referenced by getInt8().
getIntN()
ConstantInt * llvm::IRBuilderBase::getIntN (unsigned N, uint64_t C) inline
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
Definition at line 287 of file IRBuilder.h.
References llvm::ConstantInt::get(), getIntNTy(), and N.
getIntNTy()
IntegerType * llvm::IRBuilderBase::getIntNTy (unsigned N) inline
Fetch the type representing an N-bit integer.
Definition at line 326 of file IRBuilder.h.
References Context, llvm::Type::getIntNTy(), and N.
Referenced by getIntN().
getIntPtrTy()
IntegerType * llvm::IRBuilderBase::getIntPtrTy (const DataLayout * DL, unsigned AddrSpace = 0) inline
Fetch the type representing a pointer to an integer value.
Definition at line 356 of file IRBuilder.h.
References Context, and llvm::DataLayout::getIntPtrType().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption().
getTrue()
ConstantInt * llvm::IRBuilderBase::getTrue () inline
Get the constant value for i1 true.
Definition at line 256 of file IRBuilder.h.
References Context, and llvm::ConstantInt::getTrue().
Referenced by generateUnsignedDivisionCode().
getVoidTy()
Type * llvm::IRBuilderBase::getVoidTy () inline
Fetch the type representing void.
Definition at line 346 of file IRBuilder.h.
References Context, and llvm::Type::getVoidTy().
Referenced by appendToGlobalArray().
restoreIP()
void llvm::IRBuilderBase::restoreIP (InsertPoint IP) inline
Sets the current insert point to a previously-saved location.
Definition at line 169 of file IRBuilder.h.
References ClearInsertionPoint(), llvm::IRBuilderBase::InsertPoint::getBlock(), llvm::IRBuilderBase::InsertPoint::getPoint(), llvm::IRBuilderBase::InsertPoint::isSet(), and SetInsertPoint().
saveAndClearIP()
InsertPoint llvm::IRBuilderBase::saveAndClearIP () inline
Returns the current insert point, clearing it in the process.
Definition at line 162 of file IRBuilder.h.
References ClearInsertionPoint(), GetInsertBlock(), and GetInsertPoint().
saveIP()
InsertPoint llvm::IRBuilderBase::saveIP () const inline
Returns the current insert point.
Definition at line 157 of file IRBuilder.h.
References GetInsertBlock(), and GetInsertPoint().
SetCurrentDebugLocation()
void llvm::IRBuilderBase::SetCurrentDebugLocation (const DebugLoc & L) inline
Set location information used by debugging information.
Definition at line 118 of file IRBuilder.h.
Referenced by GetLoadValueForLoad(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), ScalarizeMaskedLoad(), ScalarizeMaskedStore(), SetInsertPoint(), SimplifyTerminatorOnSelect(), and TryToSimplifyUncondBranchWithICmpInIt().
SetDefaultFPMathTag()
void llvm::IRBuilderBase::SetDefaultFPMathTag (MDNode * FPMathTag) inline
Set the floating point math metadata to be used.
Definition at line 186 of file IRBuilder.h.
References DefaultFPMathTag.
SetFastMathFlags()
void llvm::IRBuilderBase::SetFastMathFlags (FastMathFlags NewFMF) inline
Set the fast-math flags to be used with generated fp-math operators.
Definition at line 189 of file IRBuilder.h.
References FMF.
SetInsertPoint() [1/4]
void llvm::IRBuilderBase::SetInsertPoint (BasicBlock * TheBB) inline
This specifies that created instructions should be appended to the end of the specified block.
Definition at line 83 of file IRBuilder.h.
References BB, and InsertPt.
Referenced by FoldTwoEntryPHINode(), generatedUnsignedRemainderCode(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), insertSinCosCall(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), restoreIP(), ScalarizeMaskedLoad(), ScalarizeMaskedStore(), SetInsertPoint(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToTwoReturns(), SwitchToLookupTable(), SwitchToSelect(), TryToSimplifyUncondBranchWithICmpInIt(), and llvm::UpgradeIntrinsicCall().
SetInsertPoint() [2/4]
void llvm::IRBuilderBase::SetInsertPoint (BasicBlock * TheBB, BasicBlock::iterator IP) inline
This specifies that created instructions should be inserted at the specified point.
Definition at line 99 of file IRBuilder.h.
References BB, and InsertPt.
SetInsertPoint() [3/4]
void llvm::IRBuilderBase::SetInsertPoint (Instruction * I) inline
This specifies that created instructions should be inserted before the specified instruction.
Definition at line 90 of file IRBuilder.h.
References BB, I, InsertPt, and SetCurrentDebugLocation().
SetInsertPoint() [4/4]
void llvm::IRBuilderBase::SetInsertPoint (Use & U) inline
Find the nearest point that dominates this use, and specify that created instructions should be inserted at this point.
Definition at line 106 of file IRBuilder.h.
References llvm::cast(), llvm::dyn_cast(), llvm::BasicBlock::getTerminator(), and SetInsertPoint().
SetInstDebugLocation()
void llvm::IRBuilderBase::SetInstDebugLocation (Instruction * I) const inline
If this builder has a current debug location, set it on the specified instruction.
Definition at line 127 of file IRBuilder.h.
References I.
Referenced by createCallHelper(), and llvm::IRBuilder< true, TargetFolder >::Insert().
Member Data Documentation
BB
BasicBlock* llvm::IRBuilderBase::BB protected
Definition at line 53 of file IRBuilder.h.
Referenced by ClearInsertionPoint(), CreateAssumption(), CreateGCRelocate(), CreateGCResult(), CreateGCStatepoint(), CreateGlobalString(), CreateLifetimeEnd(), CreateLifetimeStart(), CreateMemCpy(), CreateMemMove(), CreateMemSet(), getCurrentFunctionReturnType(), GetInsertBlock(), llvm::IRBuilder< true, TargetFolder >::Insert(), SetInsertPoint(), SetInsertPoint(), and SetInsertPoint().
Context
LLVMContext& llvm::IRBuilderBase::Context protected
Definition at line 55 of file IRBuilder.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateAggregateRet(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP1_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP1_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP2_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP2_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP2_64(), llvm::IRBuilder< true, TargetFolder >::CreateFence(), CreateGlobalString(), llvm::IRBuilder< true, TargetFolder >::CreateGlobalStringPtr(), llvm::IRBuilder< true, TargetFolder >::CreatePtrDiff(), llvm::IRBuilder< true, TargetFolder >::CreateRet(), llvm::IRBuilder< true, TargetFolder >::CreateRetVoid(), llvm::IRBuilder< true, TargetFolder >::CreateUnreachable(), getContext(), getDoubleTy(), getFalse(), getFloatTy(), getHalfTy(), getInt(), getInt16Ty(), getInt1Ty(), getInt32Ty(), getInt64Ty(), getInt8PtrTy(), getInt8Ty(), getIntNTy(), getIntPtrTy(), getTrue(), getVoidTy(), and IRBuilderBase().
DefaultFPMathTag
MDNode* llvm::IRBuilderBase::DefaultFPMathTag protected
Definition at line 57 of file IRBuilder.h.
Referenced by llvm::IRBuilderBase::FastMathFlagGuard::FastMathFlagGuard(), getDefaultFPMathTag(), IRBuilderBase(), and SetDefaultFPMathTag().
FMF
FastMathFlags llvm::IRBuilderBase::FMF protected
Definition at line 58 of file IRBuilder.h.
Referenced by clearFastMathFlags(), llvm::IRBuilder< true, TargetFolder >::CreateBinOp(), llvm::IRBuilder< true, TargetFolder >::CreateFAdd(), llvm::IRBuilder< true, TargetFolder >::CreateFDiv(), llvm::IRBuilder< true, TargetFolder >::CreateFMul(), llvm::IRBuilder< true, TargetFolder >::CreateFNeg(), llvm::IRBuilder< true, TargetFolder >::CreateFRem(), llvm::IRBuilder< true, TargetFolder >::CreateFSub(), getFastMathFlags(), IRBuilderBase(), and SetFastMathFlags().
InsertPt
BasicBlock::iterator llvm::IRBuilderBase::InsertPt protected
Definition at line 54 of file IRBuilder.h.
Referenced by ClearInsertionPoint(), GetInsertPoint(), llvm::IRBuilder< true, TargetFolder >::Insert(), SetInsertPoint(), SetInsertPoint(), and SetInsertPoint().
The documentation for this class was generated from the following files:
IRBuilder.h
IRBuilder.cpp