LLVM: llvm::DataLayoutPass Class Reference
LLVM API Documentation
llvm::DataLayoutPass Class Reference
#include <DataLayout.h>
Public Member Functions
DataLayoutPass ()
This has to exist, because this is a pass, but it should never be used.
~DataLayoutPass ()
const DataLayout & getDataLayout () const
bool doFinalization (Module &M) override
bool doInitialization (Module &M) override
Public Member Functions inherited from llvm::ImmutablePass
virtual void initializePass ()
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePass (char &pid)
virtual ~ImmutablePass ()
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 449 of file DataLayout.h.
Constructor & Destructor Documentation
DataLayoutPass()
DataLayoutPass::DataLayoutPass ()
This has to exist, because this is a pass, but it should never be used.
Definition at line 821 of file DataLayout.cpp.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::ImmutablePass::ImmutablePass(), and llvm::initializeDataLayoutPassPass().
~DataLayoutPass()
DataLayoutPass::~DataLayoutPass ()
Definition at line 825 of file DataLayout.cpp.
Member Function Documentation
doFinalization()
bool DataLayoutPass::doFinalization (Module &) override virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::Pass.
Definition at line 832 of file DataLayout.cpp.
doInitialization()
bool DataLayoutPass::doInitialization (Module &) override virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 827 of file DataLayout.cpp.
getDataLayout()
const DataLayout & llvm::DataLayoutPass::getDataLayout () const inline
Definition at line 457 of file DataLayout.h.
Referenced by llvm::AliasAnalysis::InitializeAliasAnalysis(), llvm::InstCombiner::runOnFunction(), llvm::LazyValueInfo::runOnFunction(), llvm::MemoryDependenceAnalysis::runOnFunction(), llvm::ScalarEvolution::runOnFunction(), llvm::Inliner::runOnSCC(), and llvm::UnrollLoop().
Member Data Documentation
ID
char DataLayoutPass::ID = 0 static
Definition at line 459 of file DataLayout.h.
Referenced by DataLayoutPass().
The documentation for this class was generated from the following files:
DataLayout.h
DataLayout.cpp