LLVM: llvm::HexagonMCCodeEmitter Class Reference
LLVM API Documentation
llvm::HexagonMCCodeEmitter Class Reference
#include <HexagonMCCodeEmitter.h>
Public Member Functions
HexagonMCCodeEmitter (MCInstrInfo const &aMII, MCSubtargetInfo const &aMST, MCContext &aMCT)
MCSubtargetInfo const & getSubtargetInfo () const
void EncodeInstruction (MCInst const &MI, raw_ostream &OS, SmallVectorImpl< MCFixup > &Fixups, MCSubtargetInfo const &STI) const override
uint64_t getBinaryCodeForInstr (MCInst const &MI, SmallVectorImpl< MCFixup > &Fixups, MCSubtargetInfo const &STI) const
unsigned getMachineOpValue (MCInst const &MI, MCOperand const &MO, SmallVectorImpl< MCFixup > &Fixups, MCSubtargetInfo const &STI) const
Return binary encoding of operand.
Public Member Functions inherited from llvm::MCCodeEmitter
virtual ~MCCodeEmitter ()
virtual void reset ()
Lifetime management.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter ()
Detailed Description
Definition at line 28 of file HexagonMCCodeEmitter.h.
Constructor & Destructor Documentation
HexagonMCCodeEmitter()
HexagonMCCodeEmitter::HexagonMCCodeEmitter (MCInstrInfo const & aMII, MCSubtargetInfo const & aMST, MCContext & aMCT)
Definition at line 51 of file HexagonMCCodeEmitter.cpp.
Referenced by getBinaryCodeForInstr().
Member Function Documentation
EncodeInstruction()
void HexagonMCCodeEmitter::EncodeInstruction (MCInst const & Inst, raw_ostream & OS, SmallVectorImpl< MCFixup > & Fixups, MCSubtargetInfo const & STI) const override virtual
EncodeInstruction - Encode the given Inst to bytes on the output stream OS.
Implements llvm::MCCodeEmitter.
Definition at line 56 of file HexagonMCCodeEmitter.cpp.
References getBinaryCodeForInstr(), llvm::HexagonMCInst::getDesc(), and llvm::MCInstrDesc::getSize().
getBinaryCodeForInstr()
uint64_t llvm::HexagonMCCodeEmitter::getBinaryCodeForInstr (MCInst const & MI, SmallVectorImpl< MCFixup > & Fixups, MCSubtargetInfo const & STI) const
References HexagonMCCodeEmitter(), and LLVM_DELETED_FUNCTION.
Referenced by EncodeInstruction().
getMachineOpValue()
unsigned HexagonMCCodeEmitter::getMachineOpValue (MCInst const & MI, MCOperand const & MO, SmallVectorImpl< MCFixup > & Fixups, MCSubtargetInfo const & STI) const
Return binary encoding of operand.
Definition at line 67 of file HexagonMCCodeEmitter.cpp.
References llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm_unreachable.
getSubtargetInfo()
MCSubtargetInfo const & HexagonMCCodeEmitter::getSubtargetInfo () const
Definition at line 77 of file HexagonMCCodeEmitter.cpp.
The documentation for this class was generated from the following files:
HexagonMCCodeEmitter.h
HexagonMCCodeEmitter.cpp