LLVM: llvm::ModuleAnalysisManagerFunctionProxy::Result Class Reference
LLVM API Documentation
llvm::ModuleAnalysisManagerFunctionProxy::Result Class Reference
Result proxy object for ModuleAnalysisManagerFunctionProxy.
#include <PassManager.h>
Public Member Functions
Result (const ModuleAnalysisManager &MAM)
Result (const Result &Arg)
Result (Result &&Arg)
Result & operator= (Result RHS)
const ModuleAnalysisManager & getManager () const
bool invalidate (Function &)
Handle invalidation by ignoring it, this pass is immutable.
Detailed Description
Result proxy object for ModuleAnalysisManagerFunctionProxy.
Definition at line 684 of file IR/PassManager.h.
Constructor & Destructor Documentation
Result() [1/3]
llvm::ModuleAnalysisManagerFunctionProxy::Result::Result (const ModuleAnalysisManager & MAM) inline explicit
Definition at line 686 of file IR/PassManager.h.
Referenced by operator=(), Result(), and Result().
Result() [2/3]
llvm::ModuleAnalysisManagerFunctionProxy::Result::Result (const Result & Arg) inline
Definition at line 689 of file IR/PassManager.h.
References Result().
Result() [3/3]
llvm::ModuleAnalysisManagerFunctionProxy::Result::Result (Result && Arg) inline
Definition at line 690 of file IR/PassManager.h.
References Result().
Member Function Documentation
getManager()
const ModuleAnalysisManager & llvm::ModuleAnalysisManagerFunctionProxy::Result::getManager () const inline
Definition at line 696 of file IR/PassManager.h.
invalidate()
bool llvm::ModuleAnalysisManagerFunctionProxy::Result::invalidate (Function &) inline
Handle invalidation by ignoring it, this pass is immutable.
Definition at line 699 of file IR/PassManager.h.
operator=()
Result & llvm::ModuleAnalysisManagerFunctionProxy::Result::operator= (Result RHS) inline
Definition at line 691 of file IR/PassManager.h.
References Result(), and std::swap().
The documentation for this class was generated from the following file:
IR/PassManager.h