LLVM: llvm::MCSymbolData Class Reference
LLVM API Documentation
llvm::MCSymbolData Class Reference
#include <MCAssembler.h>
Public Member Functions
MCSymbolData ()
MCSymbolData (const MCSymbol &_Symbol, MCFragment *_Fragment, uint64_t _Offset, MCAssembler *A=nullptr)
void dump () const
Accessors
const MCSymbol & getSymbol () const
MCFragment * getFragment () const
void setFragment (MCFragment *Value)
uint64_t getOffset () const
void setOffset (uint64_t Value)
Symbol Attributes
bool isExternal () const
void setExternal (bool Value)
bool isPrivateExtern () const
void setPrivateExtern (bool Value)
bool isCommon () const
isCommon - Is this a 'common' symbol.
void setCommon (uint64_t Size, unsigned Align)
uint64_t getCommonSize () const
getCommonSize - Return the size of a 'common' symbol.
void setSize (const MCExpr *SS)
const MCExpr * getSize () const
unsigned getCommonAlignment () const
getCommonAlignment - Return the alignment of a 'common' symbol.
uint32_t getFlags () const
getFlags - Get the (implementation defined) symbol flags.
void setFlags (uint32_t Value)
setFlags - Set the (implementation defined) symbol flags.
void modifyFlags (uint32_t Value, uint32_t Mask)
modifyFlags - Modify the flags via a mask
uint64_t getIndex () const
getIndex - Get the (implementation defined) index.
void setIndex (uint64_t Value)
setIndex - Set the (implementation defined) index.
Public Member Functions inherited from llvm::ilist_node< MCSymbolData >
MCSymbolData * getPrevNode ()
Get the previous node, or 0 for the list head.
MCSymbolData * getNextNode ()
Get the next node, or 0 for the list tail.
Additional Inherited Members
Protected Member Functions inherited from llvm::ilist_node< MCSymbolData >
ilist_node ()
Detailed Description
Definition at line 688 of file MCAssembler.h.
Constructor & Destructor Documentation
MCSymbolData() [1/2]
MCSymbolData::MCSymbolData ()
Definition at line 355 of file MCAssembler.cpp.
MCSymbolData() [2/2]
MCSymbolData::MCSymbolData (const MCSymbol & _Symbol, MCFragment * _Fragment, uint64_t _Offset, MCAssembler * A = nullptr)
Definition at line 357 of file MCAssembler.cpp.
References Offset.
Member Function Documentation
dump()
void MCSymbolData::dump () const
Definition at line 1261 of file MCAssembler.cpp.
References llvm::errs(), getCommonAlignment(), getCommonSize(), getFlags(), getFragment(), getIndex(), getOffset(), getSymbol(), isCommon(), isExternal(), and isPrivateExtern().
getCommonAlignment()
unsigned llvm::MCSymbolData::getCommonAlignment () const inline
getCommonAlignment - Return the alignment of a 'common' symbol.
Definition at line 787 of file MCAssembler.h.
References isCommon().
Referenced by dump(), and llvm::MachObjectWriter::WriteNlist().
getCommonSize()
uint64_t llvm::MCSymbolData::getCommonSize () const inline
getCommonSize - Return the size of a 'common' symbol.
Definition at line 772 of file MCAssembler.h.
References CommonSize, and isCommon().
Referenced by dump(), getSymbolValue(), and llvm::MachObjectWriter::WriteNlist().
getFlags()
uint32_t llvm::MCSymbolData::getFlags () const inline
getFlags - Get the (implementation defined) symbol flags.
Definition at line 793 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::BindIndirectSymbols(), llvm::MachObjectWriter::doesSymbolRequireExternRelocation(), dump(), llvm::MCELF::GetBinding(), llvm::MCELF::getOther(), llvm::MCELF::GetType(), llvm::MCELF::GetVisibility(), llvm::MCELF::SetBinding(), llvm::MCELF::setOther(), llvm::MCELF::SetType(), llvm::MCELF::SetVisibility(), and llvm::MachObjectWriter::WriteNlist().
getFragment()
MCFragment * llvm::MCSymbolData::getFragment () const inline
Definition at line 732 of file MCAssembler.h.
Referenced by AttemptToFoldSymbolOffsetDifference(), dump(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCAssembler::getAtom(), getLabelOffset(), llvm::MachObjectWriter::getSymbolAddress(), and llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolved().
getIndex()
uint64_t llvm::MCSymbolData::getIndex () const inline
getIndex - Get the (implementation defined) index.
Definition at line 804 of file MCAssembler.h.
Referenced by dump().
getOffset()
uint64_t llvm::MCSymbolData::getOffset () const inline
Definition at line 735 of file MCAssembler.h.
References isCommon(), and Offset.
Referenced by AttemptToFoldSymbolOffsetDifference(), dump(), getLabelOffset(), and setCommon().
getSize()
const MCExpr * llvm::MCSymbolData::getSize () const inline
Definition at line 781 of file MCAssembler.h.
getSymbol()
const MCSymbol & llvm::MCSymbolData::getSymbol () const inline
Definition at line 730 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::doesSymbolRequireExternRelocation(), dump(), llvm::MCELFStreamer::Flush(), llvm::MCAssembler::getAtom(), getLabelOffset(), llvm::MachObjectWriter::getSymbolAddress(), getSymbolOffsetImpl(), llvm::MachObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), and llvm::MachObjectWriter::WriteNlist().
isCommon()
bool llvm::MCSymbolData::isCommon () const inline
isCommon - Is this a 'common' symbol.
Definition at line 759 of file MCAssembler.h.
Referenced by dump(), getCommonAlignment(), getCommonSize(), getOffset(), getSymbolValue(), setOffset(), and llvm::MachObjectWriter::WriteNlist().
isExternal()
bool llvm::MCSymbolData::isExternal () const inline
Definition at line 748 of file MCAssembler.h.
Referenced by dump(), getSymbolValue(), and llvm::MachObjectWriter::WriteNlist().
isPrivateExtern()
bool llvm::MCSymbolData::isPrivateExtern () const inline
Definition at line 753 of file MCAssembler.h.
Referenced by dump(), and llvm::MachObjectWriter::WriteNlist().
modifyFlags()
void llvm::MCSymbolData::modifyFlags (uint32_t Value, uint32_t Mask) inline
modifyFlags - Modify the flags via a mask
Definition at line 799 of file MCAssembler.h.
Referenced by llvm::MCWinCOFFStreamer::EmitCOFFSymbolStorageClass(), llvm::MCWinCOFFStreamer::EmitCOFFSymbolType(), and llvm::MCWinCOFFStreamer::EmitSymbolAttribute().
setCommon()
void llvm::MCSymbolData::setCommon (uint64_t Size, unsigned Align) inline
setCommon - Mark this symbol as being 'common'.
Parameters
Size - The size of the symbol.
Align - The alignment of the symbol.
Definition at line 765 of file MCAssembler.h.
References Align, CommonSize, and getOffset().
Referenced by llvm::MCELFStreamer::EmitCommonSymbol(), and llvm::MCWinCOFFStreamer::EmitCommonSymbol().
setExternal()
void llvm::MCSymbolData::setExternal (bool Value) inline
Definition at line 749 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCWinCOFFStreamer::EmitCommonSymbol(), llvm::MCELFStreamer::EmitLocalCommonSymbol(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), llvm::MCELFStreamer::EmitSymbolAttribute(), and llvm::MCWinCOFFStreamer::EmitSymbolAttribute().
setFlags()
void llvm::MCSymbolData::setFlags (uint32_t Value) inline
setFlags - Set the (implementation defined) symbol flags.
Definition at line 796 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::BindIndirectSymbols(), llvm::MCELF::SetBinding(), llvm::MCELF::setOther(), llvm::MCELF::SetType(), and llvm::MCELF::SetVisibility().
setFragment()
void llvm::MCSymbolData::setFragment (MCFragment * Value) inline
Definition at line 733 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitLabel(), llvm::MCWinCOFFStreamer::EmitLocalCommonSymbol(), and llvm::MCELFStreamer::Flush().
setIndex()
void llvm::MCSymbolData::setIndex (uint64_t Value) inline
setIndex - Set the (implementation defined) index.
Definition at line 807 of file MCAssembler.h.
setOffset()
void llvm::MCSymbolData::setOffset (uint64_t Value) inline
Definition at line 739 of file MCAssembler.h.
References isCommon(), and Offset.
Referenced by llvm::MCObjectStreamer::EmitLabel().
setPrivateExtern()
void llvm::MCSymbolData::setPrivateExtern (bool Value) inline
Definition at line 754 of file MCAssembler.h.
setSize()
void llvm::MCSymbolData::setSize (const MCExpr * SS) inline
Definition at line 777 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitCommonSymbol(), and llvm::MCELFStreamer::EmitELFSize().
Member Data Documentation
CommonSize
uint64_t llvm::MCSymbolData::CommonSize
CommonSize - The size of the symbol, if it is 'common'.
Definition at line 702 of file MCAssembler.h.
Referenced by getCommonSize(), and setCommon().
Offset
uint64_t llvm::MCSymbolData::Offset
Offset - The offset to apply to the fragment address to form this symbol's value.
Definition at line 699 of file MCAssembler.h.
Referenced by getOffset(), MCSymbolData(), and setOffset().
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp