LLVM: llvm::DominatorTree Class Reference
LLVM API Documentation
llvm::DominatorTree Class Reference
Concrete subclass of DominatorTreeBase that is used to compute a normal dominator tree.
#include <Dominators.h>
Public Types
typedef DominatorTreeBase< BasicBlock > Base
Public Member Functions
DominatorTree ()
DominatorTree (DominatorTree &&Arg)
DominatorTree & operator= (DominatorTree &&RHS)
bool compare (const DominatorTree &Other) const
Returns false if the other dominator tree matches this dominator tree.
bool dominates (const Instruction *Def, const Use &U) const
Return true if Def dominates a use in User.
bool dominates (const Instruction *Def, const Instruction *User) const
bool dominates (const Instruction *Def, const BasicBlock *BB) const
bool dominates (const BasicBlockEdge &BBE, const Use &U) const
bool dominates (const BasicBlockEdge &BBE, const BasicBlock *BB) const
bool isReachableFromEntry (const Use &U) const
Provide an overload for a Use.
void verifyDomTree () const
Verify the correctness of the domtree by re-computing it.
bool dominates (const DomTreeNodeBase< BasicBlock > *A, const DomTreeNodeBase< BasicBlock > *B) const
bool dominates (const BasicBlock *A, const BasicBlock *B) const
bool isReachableFromEntry (const BasicBlock *A) const
bool isReachableFromEntry (const DomTreeNodeBase< BasicBlock > *A) const
Public Member Functions inherited from llvm::DominatorTreeBase< BasicBlock >
DominatorTreeBase (bool isPostDom)
~DominatorTreeBase ()
DominatorTreeBase (DominatorTreeBase &&Arg)
DominatorTreeBase & operator= (DominatorTreeBase &&RHS)
bool compare (const DominatorTreeBase &Other) const
void releaseMemory ()
DomTreeNodeBase< BasicBlock > * getNode (BasicBlock *BB) const
DomTreeNodeBase< BasicBlock > * operator[] (BasicBlock *BB) const
DomTreeNodeBase< BasicBlock > * getRootNode ()
const DomTreeNodeBase< BasicBlock > * getRootNode () const
void getDescendants (BasicBlock *R, SmallVectorImpl< BasicBlock * > &Result) const
Get all nodes dominated by R, including R itself.
bool properlyDominates (const DomTreeNodeBase< BasicBlock > *A, const DomTreeNodeBase< BasicBlock > *B) const
bool properlyDominates (const BasicBlock *A, const BasicBlock *B) const
bool isReachableFromEntry (const BasicBlock *A) const
bool isReachableFromEntry (const DomTreeNodeBase< BasicBlock > *A) const
bool dominates (const DomTreeNodeBase< BasicBlock > *A, const DomTreeNodeBase< BasicBlock > *B) const
bool dominates (const BasicBlock *A, const BasicBlock *B) const
BasicBlock * getRoot () const
BasicBlock * findNearestCommonDominator (BasicBlock *A, BasicBlock *B)
const BasicBlock * findNearestCommonDominator (const BasicBlock *A, const BasicBlock *B)
DomTreeNodeBase< BasicBlock > * addNewBlock (BasicBlock *BB, BasicBlock *DomBB)
void changeImmediateDominator (DomTreeNodeBase< BasicBlock > *N, DomTreeNodeBase< BasicBlock > *NewIDom)
void changeImmediateDominator (BasicBlock *BB, BasicBlock *NewBB)
void eraseNode (BasicBlock *BB)
void removeNode (BasicBlock *BB)
void splitBlock (BasicBlock *NewBB)
void print (raw_ostream &o) const
void recalculate (FT &F)
recalculate - compute a dominator tree for the given function
Public Member Functions inherited from llvm::DominatorBase< NodeT >
const std::vector< NodeT * > & getRoots () const
bool isPostDominator () const
Additional Inherited Members
Protected Types inherited from llvm::DominatorTreeBase< BasicBlock >
typedef DenseMap< BasicBlock *, DomTreeNodeBase< BasicBlock > * > DomTreeNodeMapType
Protected Member Functions inherited from llvm::DominatorTreeBase< BasicBlock >
void reset ()
void Split (DominatorTreeBase< typename GraphT::NodeType > &DT, typename GraphT::NodeType *NewBB)
void updateDFSNumbers () const
DomTreeNodeBase< BasicBlock > * getNodeForBlock (BasicBlock *BB)
BasicBlock * getIDom (BasicBlock *BB) const
void addRoot (BasicBlock *BB)
void addRoot (MachineBasicBlock *MBB)
Protected Member Functions inherited from llvm::DominatorBase< NodeT >
DominatorBase (bool isPostDom)
DominatorBase (DominatorBase &&Arg)
DominatorBase & operator= (DominatorBase &&RHS)
Protected Attributes inherited from llvm::DominatorTreeBase< BasicBlock >
DomTreeNodeMapType DomTreeNodes
DomTreeNodeBase< BasicBlock > * RootNode
bool DFSInfoValid
unsigned int SlowQueries
DenseMap< BasicBlock *, BasicBlock * > IDoms
std::vector< BasicBlock * > Vertex
DenseMap< BasicBlock *, InfoRec > Info
Protected Attributes inherited from llvm::DominatorBase< NodeT >
std::vector< NodeT * > Roots
bool IsPostDominators
Detailed Description
Concrete subclass of DominatorTreeBase that is used to compute a normal dominator tree.
Definition at line 71 of file Dominators.h.
Member Typedef Documentation
Base
typedef DominatorTreeBase<BasicBlock> llvm::DominatorTree::Base
Definition at line 73 of file Dominators.h.
Constructor & Destructor Documentation
DominatorTree() [1/2]
llvm::DominatorTree::DominatorTree () inline
Definition at line 75 of file Dominators.h.
Referenced by compare(), DominatorTree(), operator=(), and verifyDomTree().
DominatorTree() [2/2]
llvm::DominatorTree::DominatorTree (DominatorTree && Arg) inline
Definition at line 77 of file Dominators.h.
References DominatorTree().
Member Function Documentation
compare()
bool llvm::DominatorTree::compare (const DominatorTree & Other) const inline
Returns false if the other dominator tree matches this dominator tree.
Definition at line 86 of file Dominators.h.
References llvm::DominatorTreeBase< BasicBlock >::compare(), DominatorTree(), llvm::DomTreeNodeBase< NodeT >::getBlock(), llvm::DominatorTreeBase< NodeT >::getRootNode(), and llvm::DominatorTreeBase< BasicBlock >::getRootNode().
Referenced by verifyDomTree().
dominates() [1/7]
bool llvm::DominatorTreeBase< BasicBlock >::dominates (const BasicBlock * A, const BasicBlock * B) const
dominates() [2/7]
bool DominatorTree::dominates (const BasicBlockEdge & BBE, const BasicBlock * BB) const
Definition at line 144 of file Dominators.cpp.
References dominates(), llvm::BasicBlockEdge::getEnd(), llvm::BasicBlock::getSinglePredecessor(), llvm::BasicBlockEdge::getStart(), llvm::BasicBlockEdge::isSingleEdge(), llvm::pred_begin(), and llvm::pred_end().
dominates() [3/7]
bool DominatorTree::dominates (const BasicBlockEdge & BBE, const Use & U) const
Definition at line 195 of file Dominators.cpp.
References llvm::cast(), dominates(), llvm::dyn_cast(), llvm::BasicBlockEdge::getEnd(), llvm::PHINode::getIncomingBlock(), llvm::Instruction::getParent(), llvm::BasicBlockEdge::getStart(), and llvm::BasicBlockEdge::isSingleEdge().
dominates() [4/7]
bool llvm::DominatorTreeBase< BasicBlock >::dominates (const DomTreeNodeBase< BasicBlock > * A, const DomTreeNodeBase< BasicBlock > * B) const inline
dominates - Returns true iff A dominates B. Note that this is not a constant time operation!
Definition at line 435 of file GenericDomTree.h.
dominates() [5/7]
bool DominatorTree::dominates (const Instruction * Def, const BasicBlock * BB) const
Definition at line 118 of file Dominators.cpp.
References dominates(), llvm::dyn_cast(), llvm::InvokeInst::getNormalDest(), and isReachableFromEntry().
dominates() [6/7]
bool DominatorTree::dominates (const Instruction * Def, const Instruction * User) const
Definition at line 81 of file Dominators.cpp.
References llvm::BasicBlock::begin(), dominates(), I, llvm::isa(), and isReachableFromEntry().
dominates() [7/7]
bool DominatorTree::dominates (const Instruction * Def, const Use & U) const
Return true if Def dominates a use in User.
This performs the special checks necessary if Def and User are in the same basic block. Note that Def doesn't dominate a use in Def itself!
Definition at line 218 of file Dominators.cpp.
References llvm::BasicBlock::begin(), llvm::cast(), dominates(), llvm::dyn_cast(), llvm::Instruction::getParent(), I, llvm::isa(), and isReachableFromEntry().
Referenced by blockDominatesAnExit(), dominates(), dominates(), dominates(), dominates(), dominates(), getInsertPointForUses(), hoistBeforePos(), isPotentiallyReachableInner(), isValidAssumeForContext(), IVUseShouldUsePostIncValue(), llvm::PHITransAddr::PHITranslateValue(), PickMostRelevantLoop(), processInstruction(), rewriteSingleStoreAlloca(), separateNestedLoop(), and ValueDominatesPHI().
isReachableFromEntry() [1/3]
bool llvm::DominatorTreeBase< BasicBlock >::isReachableFromEntry (const BasicBlock * A) const inline
isReachableFromEntry - Return true if A is dominated by the entry block of the function containing it.
Definition at line 424 of file GenericDomTree.h.
isReachableFromEntry() [2/3]
bool llvm::DominatorTreeBase< BasicBlock >::isReachableFromEntry (const DomTreeNodeBase< BasicBlock > * A) const inline
Definition at line 430 of file GenericDomTree.h.
isReachableFromEntry() [3/3]
bool DominatorTree::isReachableFromEntry (const Use & U) const
Provide an overload for a Use.
Definition at line 269 of file Dominators.cpp.
References llvm::dyn_cast(), I, and isReachableFromEntry().
Referenced by dominates(), dominates(), dominates(), FindUnconditionalPreds(), llvm::Loop::isLCSSAForm(), isPotentiallyReachableInner(), isReachableFromEntry(), and ValueDominatesPHI().
operator=()
DominatorTree & llvm::DominatorTree::operator= (DominatorTree && RHS) inline
Definition at line 79 of file Dominators.h.
References DominatorTree().
verifyDomTree()
void DominatorTree::verifyDomTree () const
Verify the correctness of the domtree by re-computing it.
This should only be used for debugging as it aborts the program if the verification fails.
Definition at line 284 of file Dominators.cpp.
References compare(), DominatorTree(), llvm::errs(), F, llvm::BasicBlock::getParent(), llvm::DominatorTreeBase< BasicBlock >::getRoot(), llvm::DominatorTreeBase< NodeT >::print(), llvm::DominatorTreeBase< BasicBlock >::print(), llvm::DominatorTreeBase< NodeT >::recalculate(), and VerifyDomInfo.
The documentation for this class was generated from the following files:
Dominators.h
Dominators.cpp