LLVM: llvm::SymbolRewriter::RewriteMapParser Class Reference
LLVM API Documentation
llvm::SymbolRewriter::RewriteMapParser Class Reference
#include <SymbolRewriter.h>
Public Member Functions
RewriteMapParser ()
~RewriteMapParser ()
bool parse (const std::string &MapFile, RewriteDescriptorList *Descriptors)
Detailed Description
Definition at line 91 of file SymbolRewriter.h.
Constructor & Destructor Documentation
RewriteMapParser()
llvm::SymbolRewriter::RewriteMapParser::RewriteMapParser () inline
Definition at line 93 of file SymbolRewriter.h.
~RewriteMapParser()
llvm::SymbolRewriter::RewriteMapParser::~RewriteMapParser () inline
Definition at line 94 of file SymbolRewriter.h.
Member Function Documentation
parse()
bool llvm::SymbolRewriter::RewriteMapParser::parse (const std::string & MapFile, RewriteDescriptorList * Descriptors)
Definition at line 230 of file SymbolRewriter.cpp.
References llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), parse(), and llvm::report_fatal_error().
Referenced by parse().
The documentation for this class was generated from the following files:
SymbolRewriter.h
SymbolRewriter.cpp