LLVM: llvm::sys::fs::recursive_directory_iterator Class Reference
LLVM API Documentation
llvm::sys::fs::recursive_directory_iterator Class Reference
#include <FileSystem.h>
Public Member Functions
recursive_directory_iterator ()
recursive_directory_iterator (const Twine &path, std::error_code &ec)
recursive_directory_iterator & increment (std::error_code &ec)
const directory_entry & operator* () const
const directory_entry * operator-> () const
int level () const
Gets the current level. Starting path is at level 0.
bool no_push_request () const
Returns true if no_push has been called for this directory_entry.
void pop ()
Goes up one level if Level > 0.
void no_push ()
Does not go down into the current directory_entry.
bool operator== (const recursive_directory_iterator &RHS) const
bool operator!= (const recursive_directory_iterator &RHS) const
Detailed Description
recursive_directory_iterator - Same as directory_iterator except for it recurses down into child directories.
Definition at line 792 of file FileSystem.h.
Constructor & Destructor Documentation
recursive_directory_iterator() [1/2]
llvm::sys::fs::recursive_directory_iterator::recursive_directory_iterator () inline
Definition at line 796 of file FileSystem.h.
Referenced by increment(), operator!=(), and operator==().
recursive_directory_iterator() [2/2]
llvm::sys::fs::recursive_directory_iterator::recursive_directory_iterator (const Twine & path, std::error_code & ec) inline explicit
Definition at line 797 of file FileSystem.h.
Member Function Documentation
increment()
recursive_directory_iterator & llvm::sys::fs::recursive_directory_iterator::increment (std::error_code & ec) inline
Definition at line 804 of file FileSystem.h.
References llvm::sys::fs::is_directory(), and recursive_directory_iterator().
level()
int llvm::sys::fs::recursive_directory_iterator::level () const inline
Gets the current level. Starting path is at level 0.
Definition at line 841 of file FileSystem.h.
no_push()
void llvm::sys::fs::recursive_directory_iterator::no_push () inline
Does not go down into the current directory_entry.
Definition at line 868 of file FileSystem.h.
no_push_request()
bool llvm::sys::fs::recursive_directory_iterator::no_push_request () const inline
Returns true if no_push has been called for this directory_entry.
Definition at line 844 of file FileSystem.h.
operator!=()
bool llvm::sys::fs::recursive_directory_iterator::operator!= (const recursive_directory_iterator & RHS) const inline
Definition at line 874 of file FileSystem.h.
References recursive_directory_iterator().
operator*()
const directory_entry & llvm::sys::fs::recursive_directory_iterator::operator* () const inline
Definition at line 836 of file FileSystem.h.
operator->()
const directory_entry * llvm::sys::fs::recursive_directory_iterator::operator-> () const inline
Definition at line 837 of file FileSystem.h.
operator==()
bool llvm::sys::fs::recursive_directory_iterator::operator== (const recursive_directory_iterator & RHS) const inline
Definition at line 870 of file FileSystem.h.
References recursive_directory_iterator().
pop()
void llvm::sys::fs::recursive_directory_iterator::pop () inline
Goes up one level if Level > 0.
Definition at line 848 of file FileSystem.h.
References llvm::report_fatal_error().
The documentation for this class was generated from the following file:
FileSystem.h