LLVM: llvm::DwarfCFIException Class Reference
LLVM API Documentation
llvm::DwarfCFIException Class Reference
#include <DwarfException.h>
Public Member Functions
DwarfCFIException (AsmPrinter *A)
virtual ~DwarfCFIException ()
void endModule () override
void beginFunction (const MachineFunction *MF) override
void endFunction (const MachineFunction *) override
endFunction - Gather and emit post-function exception information.
Public Member Functions inherited from llvm::EHStreamer
EHStreamer (AsmPrinter *A)
virtual ~EHStreamer ()
void endModule () override
Emit all exception information that should come after the content.
void beginFunction (const MachineFunction *MF) override
void endFunction (const MachineFunction *) override
Gather and emit post-function exception information.
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g. common symbols), this tracks that size.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
Additional Inherited Members
Protected Types inherited from llvm::EHStreamer
typedef DenseMap< MCSymbol *, PadRange > RangeMapType
Protected Member Functions inherited from llvm::EHStreamer
unsigned computeActionsTable (const SmallVectorImpl< const LandingPadInfo * > &LPs, SmallVectorImpl< ActionEntry > &Actions, SmallVectorImpl< unsigned > &FirstActions)
bool callToNoUnwindFunction (const MachineInstr *MI)
void computeCallSiteTable (SmallVectorImpl< CallSiteEntry > &CallSites, const SmallVectorImpl< const LandingPadInfo * > &LPs, const SmallVectorImpl< unsigned > &FirstActions)
void emitExceptionTable ()
virtual void emitTypeInfos (unsigned TTypeEncoding)
Static Protected Member Functions inherited from llvm::EHStreamer
static unsigned sharedTypeIDs (const LandingPadInfo *L, const LandingPadInfo *R)
How many leading type ids two landing pads have in common.
Protected Attributes inherited from llvm::EHStreamer
AsmPrinter * Asm
Target of directive emission.
MachineModuleInfo * MMI
Collected machine module information.
Detailed Description
Definition at line 24 of file DwarfException.h.
Constructor & Destructor Documentation
DwarfCFIException()
DwarfCFIException::DwarfCFIException (AsmPrinter * A)
Definition at line 42 of file DwarfCFIException.cpp.
References llvm::EHStreamer::EHStreamer().
~DwarfCFIException()
DwarfCFIException::~DwarfCFIException () virtual
Definition at line 46 of file DwarfCFIException.cpp.
Member Function Documentation
beginFunction()
void DwarfCFIException::beginFunction (const MachineFunction * MF) override virtual
beginFunction - Gather pre-function exception information. Assumes being emitted immediately after the function entry point.
beginFunction - Gather pre-function exception information. Assumes it's being emitted immediately after the function entry point.
Implements llvm::AsmPrinterHandler.
Definition at line 76 of file DwarfCFIException.cpp.
References llvm::EHStreamer::Asm, llvm::AsmPrinter::CFI_M_Debug, llvm::AsmPrinter::CFI_M_EH, llvm::AsmPrinter::CFI_M_None, llvm::MCSymbolRefExpr::Create(), llvm::dwarf::DW_EH_PE_omit, llvm::TargetLoweringObjectFile::getCFIPersonalitySymbol(), llvm::MCObjectFileInfo::getLSDAEncoding(), llvm::MCObjectFileInfo::getPersonalityEncoding(), and llvm::EHStreamer::MMI.
endFunction()
void DwarfCFIException::endFunction (const MachineFunction *) override virtual
endFunction - Gather and emit post-function exception information.
endFunction - Gather and emit post-function exception information.
Implements llvm::AsmPrinterHandler.
Definition at line 138 of file DwarfCFIException.cpp.
References llvm::EHStreamer::Asm, llvm::EHStreamer::emitExceptionTable(), and llvm::EHStreamer::MMI.
endModule()
void DwarfCFIException::endModule () override virtual
endModule - Emit all exception information that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 50 of file DwarfCFIException.cpp.
References llvm::EHStreamer::Asm, llvm::AsmPrinter::CFI_M_Debug, llvm::dwarf::DW_EH_PE_indirect, llvm::TargetLoweringObjectFile::emitPersonalityValue(), llvm::MCObjectFileInfo::getPersonalityEncoding(), and llvm::EHStreamer::MMI.
The documentation for this class was generated from the following files:
DwarfException.h
DwarfCFIException.cpp