LLVM: llvm::PBQP::RegAlloc::NodeMetadata Class Reference
LLVM API Documentation
llvm::PBQP::RegAlloc::NodeMetadata Class Reference
Holds solver state and other metadata relevant to each PBQP RA node.
#include <RegAllocPBQP.h>
Public Types
enum ReductionState { Unprocessed , OptimallyReducible , ConservativelyAllocatable , NotProvablyAllocatable }
typedef RegAlloc::AllowedRegVector AllowedRegVector
Public Member Functions
NodeMetadata ()
NodeMetadata (const NodeMetadata &Other)
NodeMetadata (NodeMetadata &&Other)
NodeMetadata & operator= (const NodeMetadata &Other)
NodeMetadata & operator= (NodeMetadata &&Other)
void setVReg (unsigned VReg)
unsigned getVReg () const
void setAllowedRegs (GraphMetadata::AllowedRegVecRef AllowedRegs)
const AllowedRegVector & getAllowedRegs () const
void setup (const Vector &Costs)
ReductionState getReductionState () const
void setReductionState (ReductionState RS)
void handleAddEdge (const MatrixMetadata &MD, bool Transpose)
void handleRemoveEdge (const MatrixMetadata &MD, bool Transpose)
bool isConservativelyAllocatable () const
Detailed Description
Holds solver state and other metadata relevant to each PBQP RA node.
Definition at line 176 of file RegAllocPBQP.h.
Member Typedef Documentation
AllowedRegVector
typedef RegAlloc::AllowedRegVector llvm::PBQP::RegAlloc::NodeMetadata::AllowedRegVector
Definition at line 178 of file RegAllocPBQP.h.
Member Enumeration Documentation
ReductionState
enum llvm::PBQP::RegAlloc::NodeMetadata::ReductionState
Enumerator
Unprocessed
OptimallyReducible
ConservativelyAllocatable
NotProvablyAllocatable
Definition at line 180 of file RegAllocPBQP.h.
Constructor & Destructor Documentation
NodeMetadata() [1/3]
llvm::PBQP::RegAlloc::NodeMetadata::NodeMetadata () inline
Definition at line 185 of file RegAllocPBQP.h.
References Unprocessed.
Referenced by NodeMetadata(), NodeMetadata(), operator=(), and operator=().
NodeMetadata() [2/3]
llvm::PBQP::RegAlloc::NodeMetadata::NodeMetadata (const NodeMetadata & Other) inline
Definition at line 191 of file RegAllocPBQP.h.
References NodeMetadata().
NodeMetadata() [3/3]
llvm::PBQP::RegAlloc::NodeMetadata::NodeMetadata (NodeMetadata && Other) inline
Definition at line 203 of file RegAllocPBQP.h.
References NodeMetadata().
Member Function Documentation
getAllowedRegs()
const AllowedRegVector & llvm::PBQP::RegAlloc::NodeMetadata::getAllowedRegs () const inline
Definition at line 240 of file RegAllocPBQP.h.
getReductionState()
ReductionState llvm::PBQP::RegAlloc::NodeMetadata::getReductionState () const inline
Definition at line 247 of file RegAllocPBQP.h.
Referenced by llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleDisconnectEdge().
getVReg()
unsigned llvm::PBQP::RegAlloc::NodeMetadata::getVReg () const inline
Definition at line 235 of file RegAllocPBQP.h.
handleAddEdge()
void llvm::PBQP::RegAlloc::NodeMetadata::handleAddEdge (const MatrixMetadata & MD, bool Transpose) inline
Definition at line 250 of file RegAllocPBQP.h.
References llvm::PBQP::RegAlloc::MatrixMetadata::getUnsafeCols(), llvm::PBQP::RegAlloc::MatrixMetadata::getUnsafeRows(), llvm::PBQP::RegAlloc::MatrixMetadata::getWorstCol(), and llvm::PBQP::RegAlloc::MatrixMetadata::getWorstRow().
Referenced by llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleReconnectEdge(), and llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleSetEdgeCosts().
handleRemoveEdge()
void llvm::PBQP::RegAlloc::NodeMetadata::handleRemoveEdge (const MatrixMetadata & MD, bool Transpose) inline
Definition at line 258 of file RegAllocPBQP.h.
References llvm::PBQP::RegAlloc::MatrixMetadata::getUnsafeCols(), llvm::PBQP::RegAlloc::MatrixMetadata::getUnsafeRows(), llvm::PBQP::RegAlloc::MatrixMetadata::getWorstCol(), and llvm::PBQP::RegAlloc::MatrixMetadata::getWorstRow().
Referenced by llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleDisconnectEdge().
isConservativelyAllocatable()
bool llvm::PBQP::RegAlloc::NodeMetadata::isConservativelyAllocatable () const inline
Definition at line 266 of file RegAllocPBQP.h.
Referenced by llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleDisconnectEdge().
operator=() [1/2]
NodeMetadata & llvm::PBQP::RegAlloc::NodeMetadata::operator= (const NodeMetadata & Other) inline
Definition at line 210 of file RegAllocPBQP.h.
References NodeMetadata().
operator=() [2/2]
NodeMetadata & llvm::PBQP::RegAlloc::NodeMetadata::operator= (NodeMetadata && Other) inline
Definition at line 224 of file RegAllocPBQP.h.
References NodeMetadata().
setAllowedRegs()
void llvm::PBQP::RegAlloc::NodeMetadata::setAllowedRegs (GraphMetadata::AllowedRegVecRef AllowedRegs) inline
Definition at line 237 of file RegAllocPBQP.h.
setReductionState()
void llvm::PBQP::RegAlloc::NodeMetadata::setReductionState (ReductionState RS) inline
Definition at line 248 of file RegAllocPBQP.h.
setup()
void llvm::PBQP::RegAlloc::NodeMetadata::setup (const Vector & Costs) inline
Definition at line 242 of file RegAllocPBQP.h.
References llvm::PBQP::Vector::getLength().
setVReg()
void llvm::PBQP::RegAlloc::NodeMetadata::setVReg (unsigned VReg) inline
Definition at line 234 of file RegAllocPBQP.h.
The documentation for this class was generated from the following file:
RegAllocPBQP.h