LLVM: llvm::cl::bits< DataType, Storage, ParserClass > Class Template Reference
LLVM API Documentation
llvm::cl::bits< DataType, Storage, ParserClass > Class Template Reference
#include <CommandLine.h>
Public Member Functions
ParserClass & getParser ()
unsigned getPosition (unsigned optnum) const
template<class M0t>
bits (const M0t &M0)
template<class M0t, class M1t>
bits (const M0t &M0, const M1t &M1)
template<class M0t, class M1t, class M2t>
bits (const M0t &M0, const M1t &M1, const M2t &M2)
template<class M0t, class M1t, class M2t, class M3t>
bits (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3)
template<class M0t, class M1t, class M2t, class M3t, class M4t>
bits (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4)
template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t>
bits (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4, const M5t &M5)
template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t>
bits (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4, const M5t &M5, const M6t &M6)
template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t, class M7t>
bits (const M0t &M0, const M1t &M1, const M2t &M2, const M3t &M3, const M4t &M4, const M5t &M5, const M6t &M6, const M7t &M7)
Public Member Functions inherited from llvm::cl::Option
enum NumOccurrencesFlag getNumOccurrencesFlag () const
enum ValueExpected getValueExpectedFlag () const
enum OptionHidden getOptionHiddenFlag () const
enum FormattingFlags getFormattingFlag () const
unsigned getMiscFlags () const
unsigned getPosition () const
unsigned getNumAdditionalVals () const
bool hasArgStr () const
void setArgStr (const char *S)
void setDescription (const char *S)
void setValueStr (const char *S)
void setNumOccurrencesFlag (enum NumOccurrencesFlag Val)
void setValueExpectedFlag (enum ValueExpected Val)
void setHiddenFlag (enum OptionHidden Val)
void setFormattingFlag (enum FormattingFlags V)
void setMiscFlag (enum MiscFlags M)
void setPosition (unsigned pos)
void setCategory (OptionCategory &C)
void addArgument ()
void removeArgument ()
Option * getNextRegisteredOption () const
virtual bool addOccurrence (unsigned pos, StringRef ArgName, StringRef Value, bool MultiArg=false)
bool error (const Twine &Message, StringRef ArgName=StringRef())
int getNumOccurrences () const
virtual ~Option ()
Public Member Functions inherited from llvm::cl::bits_storage< DataType, bool >
template<class T>
void addValue (const T &V)
unsigned getBits ()
template<class T>
bool isSet (const T &V)
bits_storage ()
bool setLocation (Option &O, unsigned &L)
Additional Inherited Members
Public Attributes inherited from llvm::cl::Option
const char * ArgStr
const char * HelpStr
const char * ValueStr
OptionCategory * Category
Protected Member Functions inherited from llvm::cl::Option
Option (enum NumOccurrencesFlag OccurrencesFlag, enum OptionHidden Hidden)
void setNumAdditionalVals (unsigned n)
Detailed Description
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>>
class llvm::cl::bits< DataType, Storage, ParserClass >
Definition at line 1546 of file CommandLine.h.
Constructor & Destructor Documentation
bits() [1/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t> llvm::cl::bits< DataType, Storage, ParserClass >::bits (const M0t & M0) inline explicit
Definition at line 1597 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
bits() [2/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t> llvm::cl::bits< DataType, Storage, ParserClass >::bits (const M0t & M0, const M1t & M1) inline
Definition at line 1604 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
bits() [3/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t> llvm::cl::bits< DataType, Storage, ParserClass >::bits (const M0t & M0, const M1t & M1, const M2t & M2) inline
Definition at line 1612 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
bits() [4/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t> llvm::cl::bits< DataType, Storage, ParserClass >::bits (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3) inline
Definition at line 1621 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
bits() [5/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t> llvm::cl::bits< DataType, Storage, ParserClass >::bits (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4) inline
Definition at line 1631 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
bits() [6/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t> llvm::cl::bits< DataType, Storage, ParserClass >::bits (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4, const M5t & M5) inline
Definition at line 1643 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
bits() [7/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t> llvm::cl::bits< DataType, Storage, ParserClass >::bits (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4, const M5t & M5, const M6t & M6) inline
Definition at line 1657 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
bits() [8/8]
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> template<class M0t, class M1t, class M2t, class M3t, class M4t, class M5t, class M6t, class M7t> llvm::cl::bits< DataType, Storage, ParserClass >::bits (const M0t & M0, const M1t & M1, const M2t & M2, const M3t & M3, const M4t & M4, const M5t & M5, const M6t & M6, const M7t & M7) inline
Definition at line 1672 of file CommandLine.h.
References llvm::cl::apply(), llvm::cl::NotHidden, llvm::cl::Option::Option(), and llvm::cl::ZeroOrMore.
Member Function Documentation
getParser()
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> ParserClass & llvm::cl::bits< DataType, Storage, ParserClass >::getParser () inline
Definition at line 1588 of file CommandLine.h.
getPosition()
template<class DataType, class Storage = bool, class ParserClass = parser<DataType>> unsigned llvm::cl::bits< DataType, Storage, ParserClass >::getPosition (unsigned optnum) const inline
Definition at line 1590 of file CommandLine.h.
The documentation for this class was generated from the following file:
CommandLine.h