LLVM: llvm::DIEDwarfExpression Class Reference
LLVM API Documentation
llvm::DIEDwarfExpression Class Reference
DwarfExpression implementation for singular DW_AT_location.
#include <DwarfExpression.h>
Public Member Functions
DIEDwarfExpression (const AsmPrinter &AP, DwarfUnit &DU, DIELoc &DIE)
void EmitOp (uint8_t Op, const char *Comment=nullptr) override
Output a dwarf operand and an optional assembler comment.
void EmitSigned (int Value) override
Emit a raw signed value.
void EmitUnsigned (unsigned Value) override
Emit a raw unsigned value.
bool isFrameRegister (unsigned MachineReg) override
Public Member Functions inherited from llvm::DwarfExpression
DwarfExpression (const AsmPrinter &AP)
virtual ~DwarfExpression ()
void AddReg (int DwarfReg, const char *Comment=nullptr)
Emit a dwarf register operation.
void AddRegIndirect (int DwarfReg, int Offset, bool Deref=false)
Emit an (double-)indirect dwarf register operation.
void AddOpPiece (unsigned SizeInBits, unsigned OffsetInBits=0)
void AddShr (unsigned ShiftBy)
Emit a shift-right dwarf expression.
bool AddMachineRegIndirect (unsigned MachineReg, int Offset=0)
bool AddMachineRegPiece (unsigned MachineReg, unsigned PieceSizeInBits=0, unsigned PieceOffsetInBits=0)
Emit a partial DWARF register operation.
void AddSignedConstant (int Value)
Emit a signed constant.
void AddUnsignedConstant (unsigned Value)
Emit an unsigned constant.
bool AddMachineRegExpression (DIExpression Expr, unsigned MachineReg, unsigned PieceOffsetInBits=0)
void AddExpression (DIExpression Expr, unsigned PieceOffsetInBits=0, unsigned I=0)
Additional Inherited Members
Protected Member Functions inherited from llvm::DwarfExpression
const TargetRegisterInfo * getTRI () const
unsigned getDwarfVersion () const
Protected Attributes inherited from llvm::DwarfExpression
const AsmPrinter & AP
Detailed Description
DwarfExpression implementation for singular DW_AT_location.
Definition at line 118 of file DwarfExpression.h.
Constructor & Destructor Documentation
DIEDwarfExpression()
llvm::DIEDwarfExpression::DIEDwarfExpression (const AsmPrinter & AP, DwarfUnit & DU, DIELoc & DIE) inline
Definition at line 123 of file DwarfExpression.h.
References llvm::DwarfExpression::AP, and llvm::DwarfExpression::DwarfExpression().
Member Function Documentation
EmitOp()
void DIEDwarfExpression::EmitOp (uint8_t Op, const char * Comment = nullptr) override virtual
Output a dwarf operand and an optional assembler comment.
Implements llvm::DwarfExpression.
Definition at line 46 of file DwarfUnit.cpp.
References llvm::dwarf::DW_FORM_data1.
Referenced by llvm::DwarfCompileUnit::addComplexAddress().
EmitSigned()
void DIEDwarfExpression::EmitSigned (int Value) override virtual
Emit a raw signed value.
Implements llvm::DwarfExpression.
Definition at line 49 of file DwarfUnit.cpp.
References llvm::dwarf::DW_FORM_sdata.
EmitUnsigned()
void DIEDwarfExpression::EmitUnsigned (unsigned Value) override virtual
Emit a raw unsigned value.
Implements llvm::DwarfExpression.
Definition at line 52 of file DwarfUnit.cpp.
References llvm::dwarf::DW_FORM_udata.
isFrameRegister()
bool DIEDwarfExpression::isFrameRegister (unsigned MachineReg) override virtual
Return whether the given machine register is the frame register in the current function.
Implements llvm::DwarfExpression.
Definition at line 55 of file DwarfUnit.cpp.
References llvm::DwarfExpression::AP, llvm::TargetRegisterInfo::getFrameRegister(), and llvm::DwarfExpression::getTRI().
The documentation for this class was generated from the following files:
DwarfExpression.h
DwarfUnit.cpp