LLVM: llvm::X86SelectionDAGInfo Class Reference
LLVM API Documentation
llvm::X86SelectionDAGInfo Class Reference
#include <X86SelectionDAGInfo.h>
Public Member Functions
X86SelectionDAGInfo (const DataLayout &DL)
~X86SelectionDAGInfo ()
SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const override
SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override
Public Member Functions inherited from llvm::TargetSelectionDAGInfo
TargetSelectionDAGInfo (const DataLayout *DL)
virtual ~TargetSelectionDAGInfo ()
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
Additional Inherited Members
Protected Member Functions inherited from llvm::TargetSelectionDAGInfo
const DataLayout * getDataLayout () const
Detailed Description
Definition at line 25 of file X86SelectionDAGInfo.h.
Constructor & Destructor Documentation
X86SelectionDAGInfo()
X86SelectionDAGInfo::X86SelectionDAGInfo (const DataLayout & DL) explicit
Definition at line 27 of file X86SelectionDAGInfo.cpp.
~X86SelectionDAGInfo()
X86SelectionDAGInfo::~X86SelectionDAGInfo ()
Definition at line 30 of file X86SelectionDAGInfo.cpp.
Member Function Documentation
EmitTargetCodeForMemcpy()
SDValue X86SelectionDAGInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override virtual
EmitTargetCodeForMemcpy - Emit target-specific code that performs a memcpy. This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
If not DWORD aligned, it is more efficient to call the library. However if calling the library is not allowed (AlwaysInline), then soldier on as the code generated here is better than the long load-store sequence we would otherwise get.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 203 of file X86SelectionDAGInfo.cpp.
References llvm::ISD::ADD, Align, llvm::dyn_cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getIntPtrConstant(), llvm::X86Subtarget::getMaxInlineSizeThreshold(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getNode(), llvm::MVT::getSizeInBits(), llvm::TargetMachine::getSubtarget(), llvm::SelectionDAG::getTarget(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MachinePointerInfo::getWithOffset(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::X86ISD::REP_MOVS, and llvm::ISD::TokenFactor.
EmitTargetCodeForMemset()
SDValue X86SelectionDAGInfo::EmitTargetCodeForMemset (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const override virtual
EmitTargetCodeForMemset - Emit target-specific code that performs a memset. This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 53 of file X86SelectionDAGInfo.cpp.
References llvm::ISD::ADD, Align, llvm::ISD::AND, llvm::EVT::bitsGT(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::MachinePointerInfo::getAddrSpace(), llvm::X86Subtarget::getBZeroEntry(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyToReg(), llvm::TargetSelectionDAGInfo::getDataLayout(), llvm::SelectionDAG::getExternalSymbol(), llvm::SelectionDAG::getIntPtrConstant(), llvm::DataLayout::getIntPtrType(), llvm::X86Subtarget::getMaxInlineSizeThreshold(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getSizeInBits(), llvm::TargetMachine::getSubtarget(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::Type::getVoidTy(), llvm::SelectionDAG::getVTList(), llvm::MachinePointerInfo::getWithOffset(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86Subtarget::is64Bit(), llvm::TargetLowering::LowerCallTo(), llvm::TargetLowering::ArgListEntry::Node, llvm::MVT::Other, llvm::X86ISD::REP_STOS, llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), and llvm::TargetLowering::ArgListEntry::Ty.
The documentation for this class was generated from the following files:
X86SelectionDAGInfo.h
X86SelectionDAGInfo.cpp