LLVM: llvm::SparcSubtarget Class Reference
LLVM API Documentation
llvm::SparcSubtarget Class Reference
#include <SparcSubtarget.h>
Public Member Functions
SparcSubtarget (const std::string &TT, const std::string &CPU, const std::string &FS, TargetMachine &TM, bool is64bit)
const SparcInstrInfo * getInstrInfo () const override
const TargetFrameLowering * getFrameLowering () const override
const SparcRegisterInfo * getRegisterInfo () const override
const SparcTargetLowering * getTargetLowering () const override
const SparcSelectionDAGInfo * getSelectionDAGInfo () const override
const DataLayout * getDataLayout () const override
bool isV9 () const
bool isVIS () const
bool isVIS2 () const
bool isVIS3 () const
bool useDeprecatedV8Instructions () const
bool hasHardQuad () const
bool usePopc () const
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
SparcSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
bool is64Bit () const
int64_t getStackPointerBias () const
int getAdjustedFrameSize (int stackSize) const
Detailed Description
Definition at line 32 of file SparcSubtarget.h.
Constructor & Destructor Documentation
SparcSubtarget()
SparcSubtarget::SparcSubtarget (const std::string & TT, const std::string & CPU, const std::string & FS, TargetMachine & TM, bool is64bit)
Definition at line 78 of file SparcSubtarget.cpp.
References computeDataLayout(), initializeSubtargetDependencies(), and is64Bit().
Referenced by initializeSubtargetDependencies(), and ParseSubtargetFeatures().
Member Function Documentation
getAdjustedFrameSize()
int SparcSubtarget::getAdjustedFrameSize (int stackSize) const
Given a actual stack size as determined by FrameInfo, this function returns adjusted framesize which includes space for register window spills and arguments.
Definition at line 85 of file SparcSubtarget.cpp.
References is64Bit(), and llvm::RoundUpToAlignment().
getDataLayout()
const DataLayout * llvm::SparcSubtarget::getDataLayout () const inline override
Definition at line 63 of file SparcSubtarget.h.
getFrameLowering()
const TargetFrameLowering * llvm::SparcSubtarget::getFrameLowering () const inline override
Definition at line 51 of file SparcSubtarget.h.
getInstrInfo()
const SparcInstrInfo * llvm::SparcSubtarget::getInstrInfo () const inline override
Definition at line 50 of file SparcSubtarget.h.
getRegisterInfo()
const SparcRegisterInfo * llvm::SparcSubtarget::getRegisterInfo () const inline override
Definition at line 54 of file SparcSubtarget.h.
getSelectionDAGInfo()
const SparcSelectionDAGInfo * llvm::SparcSubtarget::getSelectionDAGInfo () const inline override
Definition at line 60 of file SparcSubtarget.h.
getStackPointerBias()
int64_t llvm::SparcSubtarget::getStackPointerBias () const inline
The 64-bit ABI uses biased stack and frame pointers, so the stack frame of the current function is the area from [sp+BIAS] to [fp+BIAS].
Definition at line 82 of file SparcSubtarget.h.
References is64Bit().
Referenced by getFRAMEADDR(), and LowerDYNAMIC_STACKALLOC().
getTargetLowering()
const SparcTargetLowering * llvm::SparcSubtarget::getTargetLowering () const inline override
Definition at line 57 of file SparcSubtarget.h.
hasHardQuad()
bool llvm::SparcSubtarget::hasHardQuad () const inline
Definition at line 70 of file SparcSubtarget.h.
initializeSubtargetDependencies()
SparcSubtarget & SparcSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 55 of file SparcSubtarget.cpp.
References ParseSubtargetFeatures(), and SparcSubtarget().
Referenced by SparcSubtarget().
is64Bit()
bool llvm::SparcSubtarget::is64Bit () const inline
Definition at line 78 of file SparcSubtarget.h.
Referenced by getAdjustedFrameSize(), getFRAMEADDR(), getStackPointerBias(), LowerDYNAMIC_STACKALLOC(), LowerRETURNADDR(), and SparcSubtarget().
isV9()
bool llvm::SparcSubtarget::isV9 () const inline
Definition at line 65 of file SparcSubtarget.h.
isVIS()
bool llvm::SparcSubtarget::isVIS () const inline
Definition at line 66 of file SparcSubtarget.h.
isVIS2()
bool llvm::SparcSubtarget::isVIS2 () const inline
Definition at line 67 of file SparcSubtarget.h.
isVIS3()
bool llvm::SparcSubtarget::isVIS3 () const inline
Definition at line 68 of file SparcSubtarget.h.
ParseSubtargetFeatures()
void llvm::SparcSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
References SparcSubtarget().
Referenced by initializeSubtargetDependencies().
useDeprecatedV8Instructions()
bool llvm::SparcSubtarget::useDeprecatedV8Instructions () const inline
Definition at line 69 of file SparcSubtarget.h.
usePopc()
bool llvm::SparcSubtarget::usePopc () const inline
Definition at line 71 of file SparcSubtarget.h.
The documentation for this class was generated from the following files:
SparcSubtarget.h
SparcSubtarget.cpp