LLVM: llvm::DagInit Class Reference
LLVM API Documentation
llvm::DagInit Class Reference
#include <Record.h>
Public Types
typedef std::vector< Init * >::const_iterator const_arg_iterator
typedef std::vector< std::string >::const_iterator const_name_iterator
Public Member Functions
void Profile (FoldingSetNodeID &ID) const
Init * convertInitializerTo (RecTy *Ty) const override
Init * getOperator () const
const std::string & getName () const
unsigned getNumArgs () const
Init * getArg (unsigned Num) const
const std::string & getArgName (unsigned Num) const
Init * resolveReferences (Record &R, const RecordVal *RV) const override
std::string getAsString () const override
getAsString - Convert this value to a string form.
const_arg_iterator arg_begin () const
const_arg_iterator arg_end () const
size_t arg_size () const
bool arg_empty () const
const_name_iterator name_begin () const
const_name_iterator name_end () const
size_t name_size () const
bool name_empty () const
Init * getBit (unsigned Bit) const override
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const override
Init * convertInitListSlice (const std::vector< unsigned > &Elements) const override
RecTy * getFieldType (const std::string &FieldName) const override
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static DagInit * get (Init *V, const std::string &VN, ArrayRef< Init * > ArgRange, ArrayRef< std::string > NameRange)
static DagInit * get (Init *V, const std::string &VN, const std::vector< std::pair< Init *, std::string > > &args)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit , IK_FirstTypedInit , IK_BitsInit , IK_DagInit ,
IK_DefInit , IK_FieldInit , IK_IntInit , IK_ListInit ,
IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit , IK_UnOpInit ,
IK_LastOpInit , IK_StringInit , IK_VarInit , IK_VarListElementInit ,
IK_LastTypedInit , IK_UnsetInit , IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
DagInit - (v a, b) - Represent a DAG tree value. DAG inits are required to have at least one value then a (possibly empty) list of arguments. Each argument can have a name associated with it.
Definition at line 1266 of file Record.h.
Member Typedef Documentation
const_arg_iterator
typedef std::vector<Init*>::const_iterator llvm::DagInit::const_arg_iterator
Definition at line 1317 of file Record.h.
const_name_iterator
typedef std::vector<std::string>::const_iterator llvm::DagInit::const_name_iterator
Definition at line 1318 of file Record.h.
Member Function Documentation
arg_begin()
const_arg_iterator llvm::DagInit::arg_begin () const inline
Definition at line 1320 of file Record.h.
arg_empty()
bool llvm::DagInit::arg_empty () const inline
Definition at line 1324 of file Record.h.
arg_end()
const_arg_iterator llvm::DagInit::arg_end () const inline
Definition at line 1321 of file Record.h.
arg_size()
size_t llvm::DagInit::arg_size () const inline
Definition at line 1323 of file Record.h.
classof()
bool llvm::DagInit::classof (const Init * I) inline static
Definition at line 1283 of file Record.h.
References I, and llvm::Init::IK_DagInit.
convertInitializerTo()
Init * llvm::DagInit::convertInitializerTo (RecTy * Ty) const inline override virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 1295 of file Record.h.
get() [1/2]
DagInit * DagInit::get (Init * V, const std::string & VN, ArrayRef< Init * > ArgRange, ArrayRef< std::string > NameRange) static
Definition at line 1572 of file Record.cpp.
References I, and ProfileDagInit().
Referenced by llvm::BinOpInit::Fold(), ForeachHelper(), get(), and resolveReferences().
get() [2/2]
DagInit * DagInit::get (Init * V, const std::string & VN, const std::vector< std::pair< Init *, std::string > > & args) static
Definition at line 1592 of file Record.cpp.
References get().
getArg()
Init * llvm::DagInit::getArg (unsigned Num) const inline
Definition at line 1304 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), and ForeachHelper().
getArgName()
const std::string & llvm::DagInit::getArgName (unsigned Num) const inline
Definition at line 1308 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), and ForeachHelper().
getAsString()
std::string DagInit::getAsString () const override virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 1628 of file Record.cpp.
getBit()
Init * llvm::DagInit::getBit (unsigned Bit) const inline override virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1332 of file Record.h.
References llvm_unreachable.
getName()
const std::string & llvm::DagInit::getName () const inline
Definition at line 1301 of file Record.h.
getNumArgs()
unsigned llvm::DagInit::getNumArgs () const inline
Definition at line 1303 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), and ForeachHelper().
getOperator()
Init * llvm::DagInit::getOperator () const inline
Definition at line 1299 of file Record.h.
Referenced by llvm::SetTheory::evaluate(), llvm::BinOpInit::Fold(), and ForeachHelper().
name_begin()
const_name_iterator llvm::DagInit::name_begin () const inline
Definition at line 1326 of file Record.h.
name_empty()
bool llvm::DagInit::name_empty () const inline
Definition at line 1330 of file Record.h.
name_end()
const_name_iterator llvm::DagInit::name_end () const inline
Definition at line 1327 of file Record.h.
name_size()
size_t llvm::DagInit::name_size () const inline
Definition at line 1329 of file Record.h.
Profile()
void DagInit::Profile (FoldingSetNodeID & ID) const
Definition at line 1610 of file Record.cpp.
References ProfileDagInit().
resolveListElementReference()
Init * llvm::DagInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const inline override virtual
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences. If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 1336 of file Record.h.
References llvm_unreachable.
resolveReferences()
Init * DagInit::resolveReferences (Record & R, const RecordVal * RV) const override virtual
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1614 of file Record.cpp.
References get(), resolveReferences(), and llvm::Init::resolveReferences().
Referenced by resolveReferences().
The documentation for this class was generated from the following files:
Record.h
Record.cpp