LLVM: llvm::MCValue Class Reference
LLVM API Documentation
llvm::MCValue Class Reference
#include <MCValue.h>
Public Member Functions
int64_t getConstant () const
const MCSymbolRefExpr * getSymA () const
const MCSymbolRefExpr * getSymB () const
uint32_t getRefKind () const
bool isAbsolute () const
isAbsolute - Is this an absolute (as opposed to relocatable) value.
void print (raw_ostream &OS, const MCAsmInfo *MAI) const
print - Print the value to the stream OS.
void dump () const
dump - Print the value to stderr.
MCSymbolRefExpr::VariantKind getAccessVariant () const
Static Public Member Functions
static MCValue get (const MCSymbolRefExpr *SymA, const MCSymbolRefExpr *SymB=nullptr, int64_t Val=0, uint32_t RefKind=0)
static MCValue get (int64_t Val)
Detailed Description
MCValue - This represents an "assembler immediate". In its most general form, this can hold ":Kind:(SymbolA - SymbolB + imm64)". Not all targets supports relocations of this general form, but we need to represent this anyway.
In general both SymbolA and SymbolB will also have a modifier analogous to the top-level Kind. Current targets are not expected to make use of both though. The choice comes down to whether relocation modifiers apply to the closest symbol or the whole expression.
In the general form, SymbolB can only be defined if SymbolA is, and both must be in the same (non-external) section. The latter constraint is not enforced, since a symbol's section may not be known at construction.
Note that this class must remain a simple POD value class, because we need it to live in unions etc.
Definition at line 43 of file MCValue.h.
Member Function Documentation
dump()
void MCValue::dump () const
dump - Print the value to stderr.
Definition at line 41 of file MCValue.cpp.
References llvm::dbgs(), and print().
get() [1/2]
MCValue llvm::MCValue::get (const MCSymbolRefExpr * SymA, const MCSymbolRefExpr * SymB = nullptr, int64_t Val = 0, uint32_t RefKind = 0) inline static
Definition at line 65 of file MCValue.h.
Referenced by llvm::AArch64MCExpr::EvaluateAsRelocatableImpl(), llvm::MCExpr::EvaluateAsRelocatableImpl(), llvm::PPCMCExpr::EvaluateAsRelocatableImpl(), and EvaluateSymbolicAdd().
get() [2/2]
MCValue llvm::MCValue::get (int64_t Val) inline static
Definition at line 77 of file MCValue.h.
getAccessVariant()
MCSymbolRefExpr::VariantKind MCValue::getAccessVariant () const
Definition at line 46 of file MCValue.cpp.
References llvm::MCSymbolRefExpr::getKind(), getSymA(), getSymB(), llvm_unreachable, llvm::MCSymbolRefExpr::VK_None, and llvm::MCSymbolRefExpr::VK_WEAKREF.
getConstant()
int64_t llvm::MCValue::getConstant () const inline
Definition at line 49 of file MCValue.h.
Referenced by llvm::AArch64MCExpr::EvaluateAsRelocatableImpl(), llvm::MCExpr::EvaluateAsRelocatableImpl(), EvaluateSymbolicAdd(), and print().
getRefKind()
uint32_t llvm::MCValue::getRefKind () const inline
Definition at line 52 of file MCValue.h.
Referenced by print().
getSymA()
const MCSymbolRefExpr * llvm::MCValue::getSymA () const inline
Definition at line 50 of file MCValue.h.
Referenced by llvm::AArch64MCExpr::EvaluateAsRelocatableImpl(), llvm::MCExpr::EvaluateAsRelocatableImpl(), EvaluateSymbolicAdd(), getAccessVariant(), and print().
getSymB()
const MCSymbolRefExpr * llvm::MCValue::getSymB () const inline
Definition at line 51 of file MCValue.h.
Referenced by llvm::AArch64MCExpr::EvaluateAsRelocatableImpl(), llvm::MCExpr::EvaluateAsRelocatableImpl(), EvaluateSymbolicAdd(), getAccessVariant(), and print().
isAbsolute()
bool llvm::MCValue::isAbsolute () const inline
isAbsolute - Is this an absolute (as opposed to relocatable) value.
Definition at line 55 of file MCValue.h.
Referenced by llvm::MCExpr::EvaluateAsRelocatableImpl(), and print().
print()
void MCValue::print (raw_ostream & OS, const MCAsmInfo * MAI) const
print - Print the value to the stream OS.
Definition at line 18 of file MCValue.cpp.
References getConstant(), getRefKind(), getSymA(), getSymB(), isAbsolute(), and llvm::MCExpr::print().
Referenced by dump().
The documentation for this class was generated from the following files:
MCValue.h
MCValue.cpp