LLVM: llvm::TargetLoweringBase Class Reference
LLVM API Documentation
llvm::TargetLoweringBase Class Reference
#include <TargetLowering.h>
Classes
struct AddrMode
struct IntrinsicInfo
class ValueTypeActionImpl
Public Types
enum LegalizeAction { Legal , Promote , Expand , Custom }
enum LegalizeTypeAction {
TypeLegal , TypePromoteInteger , TypeExpandInteger , TypeSoftenFloat ,
TypeExpandFloat , TypeScalarizeVector , TypeSplitVector , TypeWidenVector
}
enum BooleanContent { UndefinedBooleanContent , ZeroOrOneBooleanContent , ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect , ScalarCondVectorVal , VectorMaskSelect }
Enum that describes what type of support for selects the target has.
typedef std::pair< LegalizeTypeAction, EVT > LegalizeKind
Public Member Functions
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
virtual ~TargetLoweringBase ()
const TargetMachine & getTargetMachine () const
const DataLayout * getDataLayout () const
const TargetLoweringObjectFile & getObjFileLowering () const
bool isBigEndian () const
bool isLittleEndian () const
virtual MVT getPointerTy (uint32_t=0) const
unsigned getPointerSizeInBits (uint32_t AS=0) const
unsigned getPointerTypeSizeInBits (Type *Ty) const
virtual MVT getScalarShiftAmountTy (EVT LHSTy) const
EVT getShiftAmountTy (EVT LHSTy) const
virtual MVT getVectorIdxTy () const
bool isSelectExpensive () const
Return true if the select operation is expensive for this target.
virtual bool isSelectSupported (SelectSupportKind) const
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (EVT VT) const
Return the preferred vector type legalization action.
virtual bool shouldExpandBuildVectorWithShuffles (EVT, unsigned DefinedValues) const
bool isIntDivCheap () const
bool isFsqrtCheap () const
Return true if sqrt(x) is as cheap or cheaper than 1 / rsqrt(x)
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
bool isPow2SDivCheap () const
Return true if pow2 sdiv is cheaper than a chain of sra/srl/add/sra.
bool isJumpExpensive () const
bool isPredictableSelectExpensive () const
virtual bool isLoadBitCastBeneficial (EVT, EVT) const
virtual bool isCheapToSpeculateCttz () const
Return true if it is cheap to speculate a call to intrinsic cttz.
virtual bool isCheapToSpeculateCtlz () const
Return true if it is cheap to speculate a call to intrinsic ctlz.
bool isMaskAndBranchFoldingLegal () const
Return if the target supports combining a chain like:
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
bool hasFloatingPointExceptions () const
Return true if target supports floating point exceptions.
virtual bool enableAggressiveFMAFusion (EVT VT) const
virtual EVT getSetCCResultType (LLVMContext &Context, EVT VT) const
Return the ValueType of the result of SETCC operations.
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
BooleanContent getBooleanContents (EVT Type) const
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual Sched::Preference getSchedulingPreference (SDNode *) const
virtual const TargetRegisterClass * getRegClassFor (MVT VT) const
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
virtual uint8_t getRepRegClassCostFor (MVT VT) const
bool isTypeLegal (EVT VT) const
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
LegalizeTypeAction getTypeAction (MVT VT) const
EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
virtual bool getTgtMemIntrinsic (IntrinsicInfo &, const CallInst &, unsigned) const
virtual bool isFPImmLegal (const APFloat &, EVT) const
virtual bool isShuffleMaskLegal (const SmallVectorImpl< int > &, EVT) const
virtual bool canOpTrap (unsigned Op, EVT VT) const
virtual bool isVectorClearMaskLegal (const SmallVectorImpl< int > &, EVT) const
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT) const
bool isOperationLegalOrPromote (unsigned Op, EVT VT) const
bool isOperationExpand (unsigned Op, EVT VT) const
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
EVT getValueType (Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
virtual unsigned getByValTypeAlignment (Type *Ty) const
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
unsigned getNumRegisters (LLVMContext &Context, EVT VT) const
virtual bool ShouldShrinkFPConstant (EVT) const
virtual bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const
bool hasBigEndianPartOrdering (EVT VT) const
bool hasTargetDAGCombine (ISD::NodeType NT) const
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool allowsMisalignedMemoryAccesses (EVT, unsigned AddrSpace=0, unsigned Align=1, bool *=nullptr) const
Determine if the target supports unaligned memory accesses.
virtual EVT getOptimalMemOpType (uint64_t, unsigned, unsigned, bool, bool, bool, MachineFunction &) const
virtual bool isSafeMemOpType (MVT) const
bool usesUnderscoreSetJmp () const
Determine if we should use _setjmp or setjmp to implement llvm.setjmp.
bool usesUnderscoreLongJmp () const
Determine if we should use _longjmp or longjmp to implement llvm.longjmp.
int getMinimumJumpTableEntries () const
unsigned getStackPointerRegisterToSaveRestore () const
unsigned getExceptionPointerRegister () const
unsigned getExceptionSelectorRegister () const
unsigned getJumpBufSize () const
unsigned getJumpBufAlignment () const
unsigned getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
unsigned getMinFunctionAlignment () const
Return the minimum function alignment.
unsigned getPrefFunctionAlignment () const
Return the preferred function alignment.
virtual unsigned getPrefLoopAlignment (MachineLoop *ML=nullptr) const
Return the preferred loop alignment.
bool getInsertFencesForAtomic () const
virtual bool getStackCookieLocation (unsigned &, unsigned &) const
virtual unsigned getMaximalGlobalOffset () const
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast between SrcAS and DestAS is a noop.
virtual bool shouldExpandAtomicStoreInIR (StoreInst *SI) const
virtual bool shouldExpandAtomicLoadInIR (LoadInst *LI) const
virtual bool shouldExpandAtomicRMWInIR (AtomicRMWInst *RMWI) const
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
virtual void resetOperationActions ()
Reset the operation actions based on target options.
virtual bool GetAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value * > &, Type *&) const
virtual bool isLegalAddressingMode (const AddrMode &AM, Type *Ty) const
virtual int getScalingFactorCost (const AddrMode &AM, Type *Ty) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
virtual bool isLegalICmpImmediate (int64_t) const
virtual bool isLegalAddImmediate (int64_t) const
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
virtual bool isTruncateFree (Type *, Type *) const
virtual bool allowTruncateForTailCall (Type *, Type *) const
virtual bool isTruncateFree (EVT, EVT) const
virtual bool isZExtFree (Type *, Type *) const
virtual bool isZExtFree (EVT, EVT) const
virtual bool hasPairedLoad (Type *, unsigned &) const
virtual bool hasPairedLoad (EVT, unsigned &) const
virtual bool isZExtFree (SDValue Val, EVT VT2) const
virtual bool isFPExtFree (EVT VT) const
virtual bool isFNegFree (EVT VT) const
virtual bool isFAbsFree (EVT VT) const
virtual bool isFMAFasterThanFMulAndFAdd (EVT) const
virtual bool isNarrowingProfitable (EVT, EVT) const
virtual bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const
Return true if it is beneficial to convert a load of a constant to just the constant itself. On some targets it might be more efficient to use a combination of arithmetic instructions to materialize the constant instead of loading it from a constant pool.
virtual bool isExtractSubvectorCheap (EVT ResVT, unsigned Index) const
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
LegalizeKind getTypeConversion (LLVMContext &Context, EVT VT) const
Helpers for TargetTransformInfo implementations
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
std::pair< unsigned, MVT > getTypeLegalizationCost (Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
Helpers for atomic expansion.
virtual bool hasLoadLinkedStoreConditional () const
virtual Value * emitLoadLinked (IRBuilder<> &Builder, Value *Addr, AtomicOrdering Ord) const
virtual Value * emitStoreConditional (IRBuilder<> &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const
virtual Instruction * emitLeadingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const
virtual Instruction * emitTrailingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const
Static Public Member Functions
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions
void initActions ()
Initialize all of the actions to default values.
void setBooleanContents (BooleanContent Ty)
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
void setBooleanVectorContents (BooleanContent Ty)
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setUseUnderscoreSetJmp (bool Val)
void setUseUnderscoreLongJmp (bool Val)
void setMinimumJumpTableEntries (int Val)
void setStackPointerRegisterToSaveRestore (unsigned R)
void setExceptionPointerRegister (unsigned R)
void setExceptionSelectorRegister (unsigned R)
void setSelectIsExpensive (bool isExpensive=true)
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
void setHasExtractBitsInsn (bool hasExtractInsn=true)
void setJumpIsExpensive (bool isExpensive=true)
void setIntDivIsCheap (bool isCheap=true)
void setFsqrtIsCheap (bool isCheap=true)
void setHasFloatingPointExceptions (bool FPExceptions=true)
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void setPow2SDivIsCheap (bool isCheap=true)
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
void clearRegisterClasses ()
Remove all register classes.
void clearOperationActions ()
Remove all operation actions.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (MVT VT) const
void computeRegisterProperties ()
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
void setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action)
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
void setTargetDAGCombine (ISD::NodeType NT)
void setJumpBufSize (unsigned Size)
Set the target's required jmp_buf buffer size (in bytes); default is 200.
void setJumpBufAlignment (unsigned Align)
void setMinFunctionAlignment (unsigned Align)
Set the target's minimum function alignment (in log2(bytes))
void setPrefFunctionAlignment (unsigned Align)
void setPrefLoopAlignment (unsigned Align)
void setMinStackArgumentAlignment (unsigned Align)
Set the minimum stack alignment of an argument (in log2(bytes)).
void setInsertFencesForAtomic (bool fence)
bool isLegalRC (const TargetRegisterClass *RC) const
MachineBasicBlock * emitPatchPoint (MachineInstr *MI, MachineBasicBlock *MBB) const
Protected Attributes
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
unsigned MaxStoresPerMemcpy
Specify maximum bytes of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
unsigned MaxStoresPerMemmove
Specify maximum bytes of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
bool PredictableSelectIsExpensive
bool MaskAndBranchFoldingIsLegal
bool EnableExtLdPromotion
Detailed Description
This base class for TargetLowering contains the SelectionDAG-independent parts that can be used from the rest of CodeGen.
Definition at line 79 of file TargetLowering.h.
Member Typedef Documentation
LegalizeKind
typedef std::pair<LegalizeTypeAction, EVT> llvm::TargetLoweringBase::LegalizeKind
LegalizeKind holds the legalization kind that needs to happen to EVT in order to type-legalize it.
Definition at line 108 of file TargetLowering.h.
Member Enumeration Documentation
BooleanContent
enum llvm::TargetLoweringBase::BooleanContent
Enum that describes how the target represents true/false values.
Enumerator
UndefinedBooleanContent
ZeroOrOneBooleanContent
ZeroOrNegativeOneBooleanContent
Definition at line 111 of file TargetLowering.h.
LegalizeAction
enum llvm::TargetLoweringBase::LegalizeAction
This enum indicates whether operations are valid for a target, and if not, what action should be used to make them valid.
Enumerator
Legal
Promote
Expand
Custom
Definition at line 86 of file TargetLowering.h.
LegalizeTypeAction
enum llvm::TargetLoweringBase::LegalizeTypeAction
This enum indicates whether a types are legal for a target, and if not, what action should be used to make them valid.
Enumerator
TypeLegal
TypePromoteInteger
TypeExpandInteger
TypeSoftenFloat
TypeExpandFloat
TypeScalarizeVector
TypeSplitVector
TypeWidenVector
Definition at line 95 of file TargetLowering.h.
SelectSupportKind
enum llvm::TargetLoweringBase::SelectSupportKind
Enum that describes what type of support for selects the target has.
Enumerator
ScalarValSelect
ScalarCondVectorVal
VectorMaskSelect
Definition at line 118 of file TargetLowering.h.
Constructor & Destructor Documentation
TargetLoweringBase()
TargetLoweringBase::TargetLoweringBase (const TargetMachine & TM) explicit
NOTE: The TargetMachine owns TLOF.
Definition at line 698 of file TargetLoweringBase.cpp.
References EnableExtLdPromotion, getDataLayout(), llvm::Sched::ILP, initActions(), InitCmpLibcallCCs(), InitLibcallCallingConvs(), InitLibcallNames(), MaskAndBranchFoldingIsLegal, MaxStoresPerMemcpy, MaxStoresPerMemcpyOptSize, MaxStoresPerMemmove, MaxStoresPerMemmoveOptSize, MaxStoresPerMemset, MaxStoresPerMemsetOptSize, PredictableSelectIsExpensive, and UndefinedBooleanContent.
~TargetLoweringBase()
virtual llvm::TargetLoweringBase::~TargetLoweringBase () inline virtual
Definition at line 143 of file TargetLowering.h.
Member Function Documentation
addBypassSlowDiv()
void llvm::TargetLoweringBase::addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth) inline protected
Tells the code generator which bitwidths to bypass.
Definition at line 1203 of file TargetLowering.h.
Referenced by llvm::X86TargetLowering::resetOperationActions().
AddPromotedToType()
void llvm::TargetLoweringBase::AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT) inline protected
If Opc/OrigVT is specified as being promoted, the promotion code defaults to trying a larger integer/fp until it can find one that works. If that default is insufficient, this method can be used by the target to override the default.
Definition at line 1311 of file TargetLowering.h.
References llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), and llvm::SITargetLowering::SITargetLowering().
addRegisterClass()
void llvm::TargetLoweringBase::addRegisterClass (MVT VT, const TargetRegisterClass * RC) inline protected
Add the specified register class as an available regclass for the specified value type. This indicates the selector can handle values of that class natively.
Definition at line 1214 of file TargetLowering.h.
References llvm::array_lengthof(), and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::MipsSETargetLowering::addMSAFloatType(), llvm::MipsSETargetLowering::addMSAIntType(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::Mips16TargetLowering::Mips16TargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SITargetLowering::SITargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
allowsMisalignedMemoryAccesses()
virtual bool llvm::TargetLoweringBase::allowsMisalignedMemoryAccesses (EVT , unsigned AddrSpace = 0, unsigned Align = 1, bool * = nullptr) const inline virtual
Determine if the target supports unaligned memory accesses.
This function returns true if the target allows unaligned memory accesses of the specified type in the given address space. If true, it also returns whether the unaligned memory access is "fast" in the last argument by reference. This is used, for example, in situations where an array copy/move/set is converted to a sequence of store operations. Its use helps to ensure that such replacements don't generate code that causes an alignment error (trap) on the target machine.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::Mips16TargetLowering, llvm::MipsSETargetLowering, llvm::PPCTargetLowering, llvm::SITargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 841 of file TargetLowering.h.
References Align.
Referenced by FindOptimalMemOpLowering().
allowTruncateForTailCall()
virtual bool llvm::TargetLoweringBase::allowTruncateForTailCall (Type * , Type *) const inline virtual
Return true if a truncation from Ty1 to Ty2 is permitted when deciding whether a call is in tail position. Typically this means that both results would be assigned to the same register or stack slot, but it could mean the target performs adequate checks of its own before proceeding with the tail call.
Reimplemented in llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 1450 of file TargetLowering.h.
Referenced by getNoopInput().
canCombineStoreAndExtract()
virtual bool llvm::TargetLoweringBase::canCombineStoreAndExtract (Type * VectorTy, Value * Idx, unsigned & Cost) const inline virtual
Return true if the target can combine store(extractelement VectorTy, Idx). Cost[out] gives the cost of that transformation when this is true.
Reimplemented in llvm::ARMTargetLowering.
Definition at line 291 of file TargetLowering.h.
canOpTrap()
bool TargetLoweringBase::canOpTrap (unsigned Op, EVT VT) const virtual
Returns true if the operation can trap for the value type.
VT must be a legal type. By default, we optimistically assume most operations don't trap except for divide and remainder.
canOpTrap - Returns true if the operation can trap for the value type. VT must be a legal type.
Definition at line 882 of file TargetLoweringBase.cpp.
References llvm::ISD::FDIV, llvm::ISD::FREM, isTypeLegal(), llvm::ISD::SDIV, llvm::ISD::SREM, llvm::ISD::UDIV, and llvm::ISD::UREM.
clearOperationActions()
void llvm::TargetLoweringBase::clearOperationActions () inline protected
Remove all operation actions.
Definition at line 1228 of file TargetLowering.h.
clearRegisterClasses()
void llvm::TargetLoweringBase::clearRegisterClasses () inline protected
Remove all register classes.
Definition at line 1221 of file TargetLowering.h.
References llvm::MVT::LAST_VALUETYPE.
computeRegisterProperties()
void TargetLoweringBase::computeRegisterProperties () protected
Once all of the register classes are added, this allows us to compute derived properties we expose.
computeRegisterProperties - Once all of the register classes are added, this allows us to compute derived properties we expose.
Definition at line 1044 of file TargetLoweringBase.cpp.
References llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, findRepresentativeClass(), llvm::MVT::FIRST_VECTOR_VALUETYPE, llvm::MVT::getPow2VectorType(), getPreferredVectorAction(), llvm::MVT::getScalarType(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), getVectorTypeBreakdownMVT(), llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::isInteger(), isTypeLegal(), llvm::MVT::isVoid, llvm::MVT::LAST_INTEGER_VALUETYPE, llvm::MVT::LAST_VALUETYPE, llvm::MVT::LAST_VECTOR_VALUETYPE, llvm_unreachable, llvm::MVT::MAX_ALLOWED_VALUETYPE, llvm::MVT::Other, llvm::MVT::ppcf128, TypeExpandFloat, TypeExpandInteger, TypePromoteInteger, TypeScalarizeVector, TypeSoftenFloat, TypeSplitVector, and TypeWidenVector.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::Mips16TargetLowering::Mips16TargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SITargetLowering::SITargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
emitLeadingFence()
virtual Instruction * llvm::TargetLoweringBase::emitLeadingFence (IRBuilder<> & Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const inline virtual
Inserts in the IR a target-specific intrinsic specifying a fence. It is called by AtomicExpandPass before expanding an AtomicRMW/AtomicCmpXchg/AtomicStore/AtomicLoad. RMW and CmpXchg set both IsStore and IsLoad to true. This function should either return a nullptr, or a pointer to an IR-level Instruction*. Even complex fence sequences can be represented by a single Instruction* through an intrinsic to be lowered later. Backends with !getInsertFencesForAtomic() should keep a no-op here. Backends should override this method to produce target-specific intrinsic for their fences. FIXME: Please note that the default implementation here in terms of IR-level fences exists for historical/compatibility reasons and is unsound ! Fences cannot, in general, be used to restore sequential consistency. For example, consider the following example: atomic<int> x = y = 0; int r1, r2, r3, r4; Thread 0: x.store(1); Thread 1: y.store(1); Thread 2: r1 = x.load(); r2 = y.load(); Thread 3: r3 = y.load(); r4 = x.load(); r1 = r3 = 1 and r2 = r4 = 0 is impossible as long as the accesses are all seq_cst. But if they are lowered to monotonic accesses, no amount of IR-level fences can prevent it.
Reimplemented in llvm::ARMTargetLowering, and llvm::PPCTargetLowering.
Definition at line 1034 of file TargetLowering.h.
References llvm::IRBuilder< preserveNames, T, Inserter >::CreateFence(), getInsertFencesForAtomic(), and llvm::isAtLeastRelease().
emitLoadLinked()
virtual Value * llvm::TargetLoweringBase::emitLoadLinked (IRBuilder<> & Builder, Value * Addr, AtomicOrdering Ord) const inline virtual
Perform a load-linked operation on Addr, returning a "Value *" with the corresponding pointee type. This may entail some non-trivial operations to truncate or reconstruct types that will be illegal in the backend. See ARMISelLowering for an example implementation.
Reimplemented in llvm::AArch64TargetLowering, and llvm::ARMTargetLowering.
Definition at line 992 of file TargetLowering.h.
References llvm_unreachable.
emitPatchPoint()
MachineBasicBlock * TargetLoweringBase::emitPatchPoint (MachineInstr * MI, MachineBasicBlock * MBB) const protected
Replace/modify any TargetFrameIndex operands with a targte-dependent sequence of memory operands that is recognized by PrologEpilogInserter.
Definition at line 959 of file TargetLoweringBase.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addMemOperand(), llvm::MachineInstrBuilder::addOperand(), llvm::BuildMI(), llvm::StackMaps::DirectMemRefOp, llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineInstr::getNumOperands(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineBasicBlock::insert(), llvm::MachineOperand::isFI(), llvm::MachineInstr::mayLoad(), llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, llvm::MachineMemOperand::MOVolatile, llvm::MachineInstr::setMemRefs(), and llvm::TargetOpcode::STATEPOINT.
Referenced by llvm::AArch64TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), and llvm::X86TargetLowering::EmitInstrWithCustomInserter().
emitStoreConditional()
virtual Value * llvm::TargetLoweringBase::emitStoreConditional (IRBuilder<> & Builder, Value * Val, Value * Addr, AtomicOrdering Ord) const inline virtual
Perform a store-conditional operation to Addr. Return the status of the store. This should be 0 if the store succeeded, non-zero otherwise.
Reimplemented in llvm::AArch64TargetLowering, and llvm::ARMTargetLowering.
Definition at line 999 of file TargetLowering.h.
References llvm_unreachable.
emitTrailingFence()
virtual Instruction * llvm::TargetLoweringBase::emitTrailingFence (IRBuilder<> & Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const inline virtual
Reimplemented in llvm::ARMTargetLowering, and llvm::PPCTargetLowering.
Definition at line 1045 of file TargetLowering.h.
References llvm::IRBuilder< preserveNames, T, Inserter >::CreateFence(), getInsertFencesForAtomic(), and llvm::isAtLeastAcquire().
enableAggressiveFMAFusion()
virtual bool llvm::TargetLoweringBase::enableAggressiveFMAFusion (EVT VT) const inline virtual
Return true if target always beneficiates from combining into FMA for a given value type. This must typically return false on targets where FMA takes more cycles to execute than FADD.
Reimplemented in llvm::NVPTXTargetLowering, and llvm::PPCTargetLowering.
Definition at line 304 of file TargetLowering.h.
enableExtLdPromotion()
bool llvm::TargetLoweringBase::enableExtLdPromotion () const inline
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
Definition at line 286 of file TargetLowering.h.
References EnableExtLdPromotion.
findRepresentativeClass()
std::pair< const TargetRegisterClass *, uint8_t > TargetLoweringBase::findRepresentativeClass (MVT VT) const protected virtual
Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
findRepresentativeClass - Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
Reimplemented in llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 1016 of file TargetLoweringBase.cpp.
References llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::TargetRegisterInfo::getNumRegClasses(), llvm::TargetRegisterInfo::getRegClass(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetRegisterClass::getSize(), llvm::TargetMachine::getSubtargetImpl(), getTargetMachine(), isLegalRC(), llvm::SuperRegClassIterator::isValid(), llvm::BitVector::setBitsInMask(), and llvm::MVT::SimpleTy.
Referenced by computeRegisterProperties(), llvm::ARMTargetLowering::findRepresentativeClass(), and llvm::X86TargetLowering::findRepresentativeClass().
GetAddrModeArguments()
virtual bool llvm::TargetLoweringBase::GetAddrModeArguments (IntrinsicInst * , SmallVectorImpl< Value * > & , Type *&) const inline virtual
CodeGenPrepare sinks address calculations into the same BB as Load/Store instructions reading the address. This allows as much computation as possible to be done in the address mode for that operand. This hook lets targets also pass back when this should be done on intrinsics which load/store.
Definition at line 1375 of file TargetLowering.h.
getBooleanContents() [1/2]
BooleanContent llvm::TargetLoweringBase::getBooleanContents (bool isVec, bool isFloat) const inline
For targets without i1 registers, this gives the nature of the high-bits of boolean values held in types wider than i1.
"Boolean values" are special true/false values produced by nodes like SETCC and consumed (as the condition) by nodes like SELECT and BRCOND. Not to be confused with general values promoted from i1. Some cpus distinguish between vectors of boolean and scalars; the isVec parameter selects between the two kinds. For example on X86 a scalar boolean should be zero extended from i1, while the elements of a vector of booleans should be sign extended from i1.
Some cpus also treat floating point types the same way as they treat vectors instead of the way they treat scalars.
Definition at line 330 of file TargetLowering.h.
Referenced by getBooleanContents(), llvm::TargetLowering::isConstFalseVal(), llvm::TargetLowering::isConstTrueVal(), and llvm::TargetLowering::SimplifySetCC().
getBooleanContents() [2/2]
BooleanContent llvm::TargetLoweringBase::getBooleanContents (EVT Type) const inline
Definition at line 336 of file TargetLowering.h.
References getBooleanContents().
getBypassSlowDivWidths()
const DenseMap< unsigned int, unsigned int > & llvm::TargetLoweringBase::getBypassSlowDivWidths () const inline
Returns map of slow types for division or remainder with corresponding fast types
Definition at line 230 of file TargetLowering.h.
getByValTypeAlignment()
unsigned TargetLoweringBase::getByValTypeAlignment (Type * Ty) const virtual
Return the desired alignment for ByVal or InAlloca aggregate function arguments in the caller parameter area. This is the actual alignment, not its logarithm.
getByValTypeAlignment - Return the desired alignment for ByVal aggregate function arguments in the caller parameter area. This is the actual alignment, not its logarithm.
Reimplemented in llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 1368 of file TargetLoweringBase.cpp.
Referenced by llvm::TargetLowering::LowerCallTo().
getCmpLibcallCC()
ISD::CondCode llvm::TargetLoweringBase::getCmpLibcallCC (RTLIB::Libcall Call) const inline
Get the CondCode that's to be used to test the result of the comparison libcall against zero.
Definition at line 1593 of file TargetLowering.h.
References llvm::Call.
Referenced by llvm::TargetLowering::softenSetCCOperands().
getCmpLibcallReturnType()
MVT::SimpleValueType TargetLoweringBase::getCmpLibcallReturnType () const virtual
Return the ValueType for comparison libcalls. Comparions libcalls include floating point comparion calls, and Ordered/Unordered check calls on floating point numbers.
Definition at line 1237 of file TargetLoweringBase.cpp.
References llvm::MVT::i32.
Referenced by llvm::TargetLowering::softenSetCCOperands().
getCondCodeAction()
LegalizeAction llvm::TargetLoweringBase::getCondCodeAction (ISD::CondCode CC, MVT VT) const inline
Return how the condition code should be treated: either it is legal, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 639 of file TargetLowering.h.
References llvm::array_lengthof(), Promote, and llvm::MVT::SimpleTy.
Referenced by isCondCodeLegal(), and llvm::TargetLowering::SimplifySetCC().
getDataLayout()
const DataLayout * llvm::TargetLoweringBase::getDataLayout () const inline
Definition at line 151 of file TargetLowering.h.
Referenced by llvm::ComputeValueVTs(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), FindOptimalMemOpLowering(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::NVPTXTargetLowering::getPrototype(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::SparcTargetLowering::getSRetArgSize(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), INITIALIZE_TM_PASS(), llvm::AArch64TargetLowering::isLegalAddressingMode(), IsSmallObject(), llvm::AMDGPUTargetLowering::isZExtFree(), llvm::NVPTXTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::MSP430TargetLowering::LowerRETURNADDR(), llvm::TargetLowering::ParseConstraints(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::TargetLowering::SimplifySetCC(), TargetLoweringBase(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::X86TargetLowering::X86TargetLowering(), and XFormVExtractWithShuffleIntoLoad().
getExceptionPointerRegister()
unsigned llvm::TargetLoweringBase::getExceptionPointerRegister () const inline
If a physical register, this returns the register that receives the exception address on entry to a landing pad.
Definition at line 901 of file TargetLowering.h.
Referenced by GetEHSpillList().
getExceptionSelectorRegister()
unsigned llvm::TargetLoweringBase::getExceptionSelectorRegister () const inline
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
Definition at line 907 of file TargetLowering.h.
Referenced by GetEHSpillList().
getExtendForContent()
ISD::NodeType llvm::TargetLoweringBase::getExtendForContent (BooleanContent Content) inline static
Definition at line 126 of file TargetLowering.h.
References llvm::ISD::ANY_EXTEND, llvm_unreachable, llvm::ISD::SIGN_EXTEND, UndefinedBooleanContent, llvm::ISD::ZERO_EXTEND, ZeroOrNegativeOneBooleanContent, and ZeroOrOneBooleanContent.
getIndexedLoadAction()
LegalizeAction llvm::TargetLoweringBase::getIndexedLoadAction (unsigned IdxMode, MVT VT) const inline
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 603 of file TargetLowering.h.
References llvm::MVT::isValid(), llvm::ISD::LAST_INDEXED_MODE, and llvm::MVT::SimpleTy.
Referenced by isIndexedLoadLegal().
getIndexedStoreAction()
LegalizeAction llvm::TargetLoweringBase::getIndexedStoreAction (unsigned IdxMode, MVT VT) const inline
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 621 of file TargetLowering.h.
References llvm::MVT::isValid(), llvm::ISD::LAST_INDEXED_MODE, and llvm::MVT::SimpleTy.
Referenced by isIndexedStoreLegal().
getInsertFencesForAtomic()
bool llvm::TargetLoweringBase::getInsertFencesForAtomic () const inline
Return whether the DAG builder should automatically insert fences and reduce ordering for atomics.
Definition at line 945 of file TargetLowering.h.
Referenced by llvm::ARMTargetLowering::emitLeadingFence(), emitLeadingFence(), llvm::ARMTargetLowering::emitTrailingFence(), and emitTrailingFence().
getJumpBufAlignment()
unsigned llvm::TargetLoweringBase::getJumpBufAlignment () const inline
Returns the target's jmp_buf alignment in bytes (if never set, the default is 0)
Definition at line 919 of file TargetLowering.h.
getJumpBufSize()
unsigned llvm::TargetLoweringBase::getJumpBufSize () const inline
Returns the target's jmp_buf size in bytes (if never set, the default is 200)
Definition at line 913 of file TargetLowering.h.
getLibcallCallingConv()
CallingConv::ID llvm::TargetLoweringBase::getLibcallCallingConv (RTLIB::Libcall Call) const inline
Get the CallingConv that should be used for the specified libcall.
Definition at line 1603 of file TargetLowering.h.
References llvm::Call.
Referenced by llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), and llvm::TargetLowering::makeLibCall().
getLibcallName()
const char * llvm::TargetLoweringBase::getLibcallName (RTLIB::Libcall Call) const inline
Get the libcall routine name for the specified libcall.
Definition at line 1581 of file TargetLowering.h.
References llvm::Call.
Referenced by accumulateAndSortLibcalls(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), isDivRemLibcallAvailable(), isSinCosLibcallAvailable(), LowerF128_FPEXTEND(), LowerF128_FPROUND(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), llvm::SparcTargetLowering::LowerOperation(), LowerSINT_TO_FP(), LowerUINT_TO_FP(), llvm::TargetLowering::makeLibCall(), and llvm::SparcTargetLowering::ReplaceNodeResults().
getLoadExtAction()
LegalizeAction llvm::TargetLoweringBase::getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const inline
Return how this load with extension should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 565 of file TargetLowering.h.
References Expand, llvm::EVT::getSimpleVT(), llvm::EVT::isExtended(), llvm::ISD::LAST_LOADEXT_TYPE, llvm::MVT::LAST_VALUETYPE, and llvm::MVT::SimpleTy.
Referenced by isLoadExtLegal().
getMaximalGlobalOffset()
virtual unsigned llvm::TargetLoweringBase::getMaximalGlobalOffset () const inline virtual
Returns the maximal possible offset which can be used for loads / stores from the global.
Reimplemented in llvm::AArch64TargetLowering, and llvm::ARMTargetLowering.
Definition at line 959 of file TargetLowering.h.
Referenced by INITIALIZE_TM_PASS().
getMaxStoresPerMemcpy()
unsigned llvm::TargetLoweringBase::getMaxStoresPerMemcpy (bool OptSize) const inline
Get maximum # of store operations permitted for llvm.memcpy.
This function returns the maximum number of store operations permitted to replace a call to llvm.memcpy. The value is set by the target at the performance threshold for such a replacement. If OptSize is true, return the limit for functions that have OptSize attribute.
Definition at line 818 of file TargetLowering.h.
References MaxStoresPerMemcpy, and MaxStoresPerMemcpyOptSize.
Referenced by getMemcpyLoadsAndStores().
getMaxStoresPerMemmove()
unsigned llvm::TargetLoweringBase::getMaxStoresPerMemmove (bool OptSize) const inline
Get maximum # of store operations permitted for llvm.memmove.
This function returns the maximum number of store operations permitted to replace a call to llvm.memmove. The value is set by the target at the performance threshold for such a replacement. If OptSize is true, return the limit for functions that have OptSize attribute.
Definition at line 828 of file TargetLowering.h.
References MaxStoresPerMemmove, and MaxStoresPerMemmoveOptSize.
Referenced by getMemmoveLoadsAndStores().
getMaxStoresPerMemset()
unsigned llvm::TargetLoweringBase::getMaxStoresPerMemset (bool OptSize) const inline
Get maximum # of store operations permitted for llvm.memset.
This function returns the maximum number of store operations permitted to replace a call to llvm.memset. The value is set by the target at the performance threshold for such a replacement. If OptSize is true, return the limit for functions that have OptSize attribute.
Definition at line 808 of file TargetLowering.h.
References MaxStoresPerMemset, and MaxStoresPerMemsetOptSize.
Referenced by getMemsetStores().
getMinFunctionAlignment()
unsigned llvm::TargetLoweringBase::getMinFunctionAlignment () const inline
Return the minimum function alignment.
Definition at line 929 of file TargetLowering.h.
getMinimumJumpTableEntries()
int llvm::TargetLoweringBase::getMinimumJumpTableEntries () const inline
Return integer threshold on number of blocks to use jump tables rather than if sequence.
Definition at line 889 of file TargetLowering.h.
getMinStackArgumentAlignment()
unsigned llvm::TargetLoweringBase::getMinStackArgumentAlignment () const inline
Return the minimum stack alignment of an argument.
Definition at line 924 of file TargetLowering.h.
getNumRegisters()
unsigned llvm::TargetLoweringBase::getNumRegisters (LLVMContext & Context, EVT VT) const inline
Return the number of registers that this ValueType will eventually require.
This is one for any types promoted to live in larger registers, but may be more than one for types (like i64) that are split into pieces. For types like i140, which are first promoted then expanded, it is the number of registers needed to hold all the bits of the original type. For an i140 on a 32 bit machine this means 5 registers.
Definition at line 753 of file TargetLowering.h.
References llvm::array_lengthof(), getRegisterType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), getVectorTypeBreakdown(), llvm::EVT::isInteger(), llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm_unreachable, and llvm::MVT::SimpleTy.
Referenced by GetRegistersForValue(), llvm::GetReturnInfo(), llvm::TargetLowering::LowerCallTo(), and llvm::NVPTXTargetLowering::LowerFormalArguments().
getObjFileLowering()
const TargetLoweringObjectFile & llvm::TargetLoweringBase::getObjFileLowering () const inline
Definition at line 152 of file TargetLowering.h.
Referenced by llvm::TargetMachine::getNameWithPrefix(), llvm::TargetMachine::getSymbol(), and llvm::HexagonTargetLowering::LowerGLOBALADDRESS().
getOperationAction()
LegalizeAction llvm::TargetLoweringBase::getOperationAction (unsigned Op, EVT VT) const inline
Return how this operation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 522 of file TargetLowering.h.
References llvm::array_lengthof(), Custom, Expand, llvm::EVT::getSimpleVT(), I, llvm::EVT::isExtended(), and llvm::MVT::SimpleTy.
Referenced by getTypeToPromoteTo(), isOperationExpand(), isOperationLegal(), isOperationLegalOrCustom(), and isOperationLegalOrPromote().
getOptimalMemOpType()
virtual EVT llvm::TargetLoweringBase::getOptimalMemOpType (uint64_t , unsigned , unsigned , bool , bool , bool , MachineFunction &) const inline virtual
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
If DstAlign is zero that means it's safe to destination alignment can satisfy any constraint. Similarly if SrcAlign is zero it means there isn't a need to check it against alignment requirement, probably because the source does not need to be loaded. If 'IsMemset' is true, that means it's expanding a memset. If 'ZeroMemset' is true, that means it's a memset of zero. 'MemcpyStrSrc' indicates whether the memcpy source is constant so it does not need to be loaded. It returns EVT::Other if the type should be determined using generic target-independent logic.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::PPCTargetLowering, llvm::SITargetLowering, and llvm::X86TargetLowering.
Definition at line 859 of file TargetLowering.h.
References llvm::MVT::Other.
Referenced by FindOptimalMemOpLowering().
getPointerSizeInBits()
unsigned TargetLoweringBase::getPointerSizeInBits (uint32_t AS = 0) const
Definition at line 860 of file TargetLoweringBase.cpp.
Referenced by getPointerTy(), and getPointerTypeSizeInBits().
getPointerTy()
MVT TargetLoweringBase::getPointerTy (uint32_t AS = 0) const virtual
Return the pointer type for the given address space, defaults to the pointer type from the data layout. FIXME: The default needs to be removed once all the code is updated.
Definition at line 856 of file TargetLoweringBase.cpp.
References llvm::MVT::getIntegerVT(), and getPointerSizeInBits().
Referenced by AddCombineToVPADDL(), addStackMapLiveVars(), llvm::X86TargetLowering::BuildFILD(), CheckType(), CheckValueType(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), expandExp(), expandExp2(), expandPow(), ExpandUnalignedLoad(), ExpandUnalignedStore(), FindOptimalMemOpLowering(), getCopyFromParts(), GetExponent(), getNoopInput(), llvm::TargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), llvm::NVPTXTargetLowering::getPrototype(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::ARMTargetLowering::getSetCCResultType(), getSetCCResultType(), llvm::NVPTXTargetLowering::getTgtMemIntrinsic(), llvm::SelectionDAGBuilder::getValueImpl(), getValueType(), getVectorIdxTy(), isBLACompatibleAddress(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::MSP430TargetLowering::LowerBlockAddress(), llvm::HexagonTargetLowering::LowerBR_JT(), llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), llvm::HexagonTargetLowering::LowerEH_RETURN(), LowerExtendedLoad(), llvm::MSP430TargetLowering::LowerExternalSymbol(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerFABSorFNEG(), LowerFCOPYSIGN(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerFSINCOS(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::MSP430TargetLowering::LowerGlobalAddress(), llvm::NVPTXTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), lowerIncomingStatepointValue(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerMemOpCallTo(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::MSP430TargetLowering::LowerRETURNADDR(), LowerRETURNADDR(), LowerSIGN_EXTEND_AVX512(), llvm::MSP430TargetLowering::LowerVASTART(), LowerVASTART(), LowerVASTART(), LowerVectorBroadcast(), LowerZERO_EXTEND_AVX512(), llvm::SparcTargetLowering::makeAddress(), llvm::TargetLowering::makeLibCall(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformLOADCombine(), PerformSTORECombine(), PerformSTORECombine(), PrepareCall(), llvm::X86TargetLowering::resetOperationActions(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::TargetLowering::SimplifySetCC(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getPointerTypeSizeInBits()
unsigned TargetLoweringBase::getPointerTypeSizeInBits (Type * Ty) const
Definition at line 864 of file TargetLoweringBase.cpp.
References llvm::Type::getPointerAddressSpace(), getPointerSizeInBits(), and llvm::Type::isPointerTy().
getPreferredVectorAction()
virtual TargetLoweringBase::LegalizeTypeAction llvm::TargetLoweringBase::getPreferredVectorAction (EVT VT) const inline virtual
Return the preferred vector type legalization action.
Reimplemented in llvm::AArch64TargetLowering, llvm::NVPTXTargetLowering, llvm::SITargetLowering, and llvm::X86TargetLowering.
Definition at line 193 of file TargetLowering.h.
References llvm::EVT::getVectorNumElements(), TypePromoteInteger, and TypeScalarizeVector.
Referenced by computeRegisterProperties(), llvm::AArch64TargetLowering::getPreferredVectorAction(), llvm::NVPTXTargetLowering::getPreferredVectorAction(), llvm::SITargetLowering::getPreferredVectorAction(), and llvm::X86TargetLowering::getPreferredVectorAction().
getPrefFunctionAlignment()
unsigned llvm::TargetLoweringBase::getPrefFunctionAlignment () const inline
Return the preferred function alignment.
Definition at line 934 of file TargetLowering.h.
getPrefLoopAlignment()
virtual unsigned llvm::TargetLoweringBase::getPrefLoopAlignment (MachineLoop * ML = nullptr) const inline virtual
Return the preferred loop alignment.
Reimplemented in llvm::PPCTargetLowering.
Definition at line 939 of file TargetLowering.h.
Referenced by llvm::PPCTargetLowering::getPrefLoopAlignment().
getRegClassFor()
virtual const TargetRegisterClass * llvm::TargetLoweringBase::getRegClassFor (MVT VT) const inline virtual
Return the register class that should be used for the specified value type.
Reimplemented in llvm::ARMTargetLowering.
Definition at line 354 of file TargetLowering.h.
References llvm::MVT::SimpleTy.
Referenced by llvm::CCState::analyzeMustTailForwardedRegisters(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::ARMTargetLowering::getRegClassFor(), llvm::GenericScheduler::initPolicy(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::HexagonTargetLowering::LowerRETURNADDR(), and LowerRETURNADDR().
getRegisterType() [1/2]
MVT llvm::TargetLoweringBase::getRegisterType (LLVMContext & Context, EVT VT) const inline
Return the type of registers that this ValueType will eventually require.
Definition at line 725 of file TargetLowering.h.
References llvm::array_lengthof(), getRegisterType(), llvm::EVT::getSimpleVT(), getTypeToTransformTo(), getVectorTypeBreakdown(), llvm::EVT::isInteger(), llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm_unreachable, and llvm::MVT::SimpleTy.
getRegisterType() [2/2]
MVT llvm::TargetLoweringBase::getRegisterType (MVT VT) const inline
Return the type of registers that this ValueType will eventually require.
Definition at line 719 of file TargetLowering.h.
References llvm::array_lengthof(), and llvm::MVT::SimpleTy.
Referenced by ExpandUnalignedLoad(), ExpandUnalignedStore(), getNumRegisters(), getRegisterType(), llvm::GetReturnInfo(), llvm::TargetLowering::getTypeForExtArgOrReturn(), getVectorTypeBreakdown(), getVectorTypeBreakdownMVT(), and llvm::TargetLowering::LowerCallTo().
getRepRegClassCostFor()
virtual uint8_t llvm::TargetLoweringBase::getRepRegClassCostFor (MVT VT) const inline virtual
Return the cost of the 'representative' register class for the specified value type.
Definition at line 374 of file TargetLowering.h.
References llvm::MVT::SimpleTy.
Referenced by GetCostForDef().
getRepRegClassFor()
virtual const TargetRegisterClass * llvm::TargetLoweringBase::getRepRegClassFor (MVT VT) const inline virtual
Return the 'representative' register class for the specified value type.
The 'representative' register class is the largest legal super-reg register class for the register class of the value type. For example, on i386 the rep register class for i8, i16, and i32 are GR32; while the rep register class is GR64 on x86_64.
Reimplemented in llvm::MipsSETargetLowering.
Definition at line 367 of file TargetLowering.h.
References llvm::MVT::SimpleTy.
Referenced by GetCostForDef(), and llvm::MipsSETargetLowering::getRepRegClassFor().
getScalarShiftAmountTy()
MVT TargetLoweringBase::getScalarShiftAmountTy (EVT LHSTy) const virtual
Reimplemented in llvm::AArch64TargetLowering, llvm::MipsTargetLowering, llvm::MSP430TargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::SITargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 869 of file TargetLoweringBase.cpp.
References llvm::MVT::getIntegerVT().
Referenced by getShiftAmountTy(), getVShift(), and lowerVectorShuffleAsElementInsertion().
getScalingFactorCost()
virtual int llvm::TargetLoweringBase::getScalingFactorCost (const AddrMode & AM, Type * Ty) const inline virtual
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
If the AM is supported, the return value must be >= 0. If the AM is not supported, it returns a negative value. TODO: Handle pre/postinc as well.
Reimplemented in llvm::AArch64TargetLowering, and llvm::X86TargetLowering.
Definition at line 1410 of file TargetLowering.h.
References isLegalAddressingMode().
getSchedulingPreference() [1/2]
Sched::Preference llvm::TargetLoweringBase::getSchedulingPreference () const inline
Return target scheduling preference.
Definition at line 341 of file TargetLowering.h.
Referenced by llvm::createDefaultScheduler(), llvm::PPCTargetLowering::getSchedulingPreference(), and llvm::ScheduleDAGSDNodes::newSUnit().
getSchedulingPreference() [2/2]
virtual Sched::Preference llvm::TargetLoweringBase::getSchedulingPreference (SDNode *) const inline virtual
Some scheduler, e.g. hybrid, can switch to different scheduling heuristics for different nodes. This function returns the preference (or none) for the given node.
Reimplemented in llvm::ARMTargetLowering, and llvm::PPCTargetLowering.
Definition at line 348 of file TargetLowering.h.
References llvm::Sched::None.
getSetCCResultType()
EVT TargetLoweringBase::getSetCCResultType (LLVMContext & Context, EVT VT) const virtual
Return the ValueType of the result of SETCC operations.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::MipsTargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::R600TargetLowering, llvm::SITargetLowering, llvm::SparcTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 1232 of file TargetLoweringBase.cpp.
References getPointerTy(), llvm::EVT::isVector(), and llvm::MVT::SimpleTy.
Referenced by llvm::AMDGPUTargetLowering::LowerDIVREM24(), PerformSELECTCombine(), llvm::TargetLowering::SimplifySetCC(), llvm::TargetLowering::softenSetCCOperands(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::SelectionDAGBuilder::visitJumpTableHeader(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getShiftAmountTy()
EVT TargetLoweringBase::getShiftAmountTy (EVT LHSTy) const
Definition at line 873 of file TargetLoweringBase.cpp.
References getScalarShiftAmountTy(), llvm::EVT::isInteger(), and llvm::EVT::isVector().
Referenced by llvm::TargetLowering::BuildExactSDIV(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), llvm::TargetLowering::expandFP_TO_SINT(), llvm::TargetLowering::expandMUL(), ExpandUnalignedLoad(), ExpandUnalignedStore(), LowerMUL_LOHI(), LowerVECTOR_SHUFFLEv16i8(), PerformEXTRACT_VECTOR_ELTCombine(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifySetCC().
getSimpleValueType()
MVT llvm::TargetLoweringBase::getSimpleValueType (Type * Ty, bool AllowUnknown = false) const inline
Return the MVT corresponding to this LLVM type. See getValueType.
Definition at line 709 of file TargetLowering.h.
References llvm::EVT::getSimpleVT(), and getValueType().
Referenced by llvm::TargetLowering::ParseConstraints().
getStackCookieLocation()
virtual bool llvm::TargetLoweringBase::getStackCookieLocation (unsigned & , unsigned &) const inline virtual
Return true if the target stores stack protector cookies at a fixed offset in some non-standard address space, and populates the address space and offset as appropriate.
Reimplemented in llvm::X86TargetLowering.
Definition at line 952 of file TargetLowering.h.
Referenced by CreatePrologue().
getStackPointerRegisterToSaveRestore()
unsigned llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore () const inline
If a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
Definition at line 895 of file TargetLowering.h.
Referenced by llvm::TargetInstrInfo::isSchedulingBoundary(), and llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC().
getTargetMachine()
const TargetMachine & llvm::TargetLoweringBase::getTargetMachine () const inline
Definition at line 150 of file TargetLowering.h.
Referenced by llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::SITargetLowering::analyzeImmediate(), llvm::SITargetLowering::buildScratchRSRC(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::SparcTargetLowering::expandAtomicRMW(), llvm::SparcTargetLowering::expandSelectCC(), findRepresentativeClass(), llvm::TargetLowering::getJumpTableEncoding(), llvm::X86TargetLowering::getJumpTableEncoding(), llvm::MipsTargetLowering::getOpndList(), llvm::PPCTargetLowering::getPrefLoopAlignment(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::ARMTargetLowering::getSchedulingPreference(), llvm::X86TargetLowering::getStackCookieLocation(), llvm::X86TargetLowering::isLegalAddressingMode(), llvm::TargetLowering::isOffsetFoldingLegal(), IsSmallObject(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::makeAddress(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PostISelFolding(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::resetOperationActions(), llvm::SITargetLowering::shouldConvertConstantLoadToIntImm(), and llvm::SITargetLowering::wrapAddr64Rsrc().
getTgtMemIntrinsic()
virtual bool llvm::TargetLoweringBase::getTgtMemIntrinsic (IntrinsicInfo & , const CallInst & , unsigned) const inline virtual
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory). If this is the case, it returns true and store the intrinsic information into the IntrinsicInfo that was passed to the function.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::NVPTXTargetLowering, and llvm::PPCTargetLowering.
Definition at line 484 of file TargetLowering.h.
getTruncStoreAction()
LegalizeAction llvm::TargetLoweringBase::getTruncStoreAction (EVT ValVT, EVT MemVT) const inline
Return how this store with truncation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
Definition at line 583 of file TargetLowering.h.
References Expand, llvm::EVT::getSimpleVT(), llvm::EVT::isExtended(), llvm::MVT::LAST_VALUETYPE, and llvm::MVT::SimpleTy.
Referenced by isTruncStoreLegal().
getTypeAction() [1/2]
LegalizeTypeAction llvm::TargetLoweringBase::getTypeAction (LLVMContext & Context, EVT VT) const inline
Return how we should legalize values of this type, either it is already legal (return 'Legal') or we need to promote it to a larger type (return 'Promote'), or we need to expand it into multiple registers of smaller integer type (return 'Expand'). 'Custom' is not an option.
Definition at line 415 of file TargetLowering.h.
References getTypeConversion().
Referenced by getTypeToExpandTo(), getVectorTypeBreakdown(), and OptimizeNoopCopyExpression().
getTypeAction() [2/2]
LegalizeTypeAction llvm::TargetLoweringBase::getTypeAction (MVT VT) const inline
Definition at line 418 of file TargetLowering.h.
getTypeConversion()
LegalizeKind llvm::TargetLoweringBase::getTypeConversion (LLVMContext & Context, EVT VT) const inline
Definition at line 1788 of file TargetLowering.h.
References llvm::array_lengthof(), llvm::EVT::getIntegerVT(), llvm::EVT::getPow2VectorType(), llvm::EVT::getRoundIntegerType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), getTypeConversion(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::MVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MVT::getVectorVT(), llvm::EVT::isInteger(), llvm::EVT::isPow2VectorType(), llvm::isPowerOf2_32(), llvm::EVT::isSimple(), llvm::EVT::isVector(), llvm::NextPowerOf2(), llvm::MVT::SimpleTy, TypeExpandInteger, TypeLegal, TypePromoteInteger, TypeScalarizeVector, TypeSoftenFloat, TypeSplitVector, and TypeWidenVector.
Referenced by getTypeAction(), getTypeConversion(), getTypeLegalizationCost(), and getTypeToTransformTo().
getTypeLegalizationCost()
std::pair< unsigned, MVT > TargetLoweringBase::getTypeLegalizationCost (Type * Ty) const
Estimate the cost of type-legalization and the legalized type.
Definition at line 1448 of file TargetLoweringBase.cpp.
References llvm::Type::getContext(), llvm::EVT::getSimpleVT(), getTypeConversion(), getValueType(), TypeExpandInteger, TypeLegal, and TypeSplitVector.
getTypeToExpandTo()
EVT llvm::TargetLoweringBase::getTypeToExpandTo (LLVMContext & Context, EVT VT) const inline
For types supported by the target, this is an identity function. For types that must be expanded (i.e. integer types that are larger than the largest integer register or illegal floating point types), this returns the largest legal type it will be expanded to.
Definition at line 436 of file TargetLowering.h.
References getTypeAction(), getTypeToTransformTo(), llvm::EVT::isVector(), llvm_unreachable, TypeExpandInteger, and TypeLegal.
getTypeToPromoteTo()
MVT llvm::TargetLoweringBase::getTypeToPromoteTo (unsigned Op, MVT VT) const inline
If the action for this operation is to promote, this method returns the ValueType to promote to.
Definition at line 661 of file TargetLowering.h.
References getOperationAction(), llvm::MVT::isFloatingPoint(), llvm::MVT::isInteger(), isTypeLegal(), llvm::MVT::isVoid, Promote, and llvm::MVT::SimpleTy.
getTypeToTransformTo()
EVT llvm::TargetLoweringBase::getTypeToTransformTo (LLVMContext & Context, EVT VT) const inline
For types supported by the target, this is an identity function. For types that must be promoted to larger types, this returns the larger type to promote to. For integer types that are larger than the largest integer register, this contains one step in the expansion to get to the smaller register. For illegal floating point types, this returns the integer type to transform to.
Definition at line 428 of file TargetLowering.h.
References getTypeConversion().
Referenced by getMemcpyLoadsAndStores(), getRegisterType(), getTypeToExpandTo(), getVectorTypeBreakdown(), and OptimizeNoopCopyExpression().
getValueType()
EVT llvm::TargetLoweringBase::getValueType (Type * Ty, bool AllowUnknown = false) const inline
Return the EVT corresponding to this LLVM type. This is fixed by the LLVM operations except for the pointer size. If AllowUnknown is true, this will return MVT::Other for types with no EVT counterpart (e.g. structs), otherwise it will assert.
Definition at line 688 of file TargetLowering.h.
References llvm::cast(), llvm::dyn_cast(), llvm::Type::getContext(), llvm::SequentialType::getElementType(), llvm::EVT::getEVT(), llvm::VectorType::getNumElements(), getPointerTy(), llvm::EVT::getVectorVT(), and llvm::Type::isVectorTy().
Referenced by llvm::ComputeValueVTs(), llvm::NVPTXTargetLowering::getPrototype(), getSimpleValueType(), llvm::NVPTXTargetLowering::getTgtMemIntrinsic(), getTypeLegalizationCost(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::ARMTargetLowering::isLegalAddressingMode(), llvm::NVPTXTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::TargetLowering::makeLibCall(), OptimizeExtractBits(), OptimizeNoopCopyExpression(), llvm::X86TargetLowering::ReplaceNodeResults(), and SinkShiftAndTruncate().
getValueTypeActions()
const ValueTypeActionImpl & llvm::TargetLoweringBase::getValueTypeActions () const inline
Definition at line 407 of file TargetLowering.h.
getVectorIdxTy()
virtual MVT llvm::TargetLoweringBase::getVectorIdxTy () const inline virtual
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR
Reimplemented in llvm::AMDGPUTargetLowering.
Definition at line 172 of file TargetLowering.h.
References getPointerTy().
Referenced by BuildVectorFromScalar(), getCopyFromPartsVector(), getCopyToPartsVector(), and PerformEXTRACT_VECTOR_ELTCombine().
getVectorTypeBreakdown()
unsigned TargetLoweringBase::getVectorTypeBreakdown (LLVMContext & Context, EVT VT, EVT & IntermediateVT, unsigned & NumIntermediates, MVT & RegisterVT) const
Vector types are broken down into some number of legal first class types. For example, EVT::v8f32 maps to 2 EVT::v4f32 with Altivec or SSE1, or 8 promoted EVT::f64 values with the X86 FP stack. Similarly, EVT::v2i64 turns into 4 EVT::i32 values with both PPC and X86.
This method returns the number of registers needed, and the VT for each register. It also returns the VT and quantity of the intermediate values before they are promoted/expanded.
getVectorTypeBreakdown - Vector types are broken down into some number of legal first class types. For example, MVT::v8f32 maps to 2 MVT::v4f32 with Altivec or SSE1, or 8 promoted MVT::f64 values with the X86 FP stack. Similarly, MVT::v2i64 turns into 4 MVT::i32 values with both PPC and X86.
This method returns the number of registers needed, and the VT for each register. It also returns the VT and quantity of the intermediate values before they are promoted/expanded.
Definition at line 1250 of file TargetLoweringBase.cpp.
References getRegisterType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::MVT::getSizeInBits(), getTypeAction(), getTypeToTransformTo(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::isPowerOf2_32(), isTypeLegal(), llvm::NextPowerOf2(), TypePromoteInteger, and TypeWidenVector.
Referenced by getCopyFromPartsVector(), getCopyToPartsVector(), getNumRegisters(), and getRegisterType().
hasBigEndianPartOrdering()
bool llvm::TargetLoweringBase::hasBigEndianPartOrdering (EVT VT) const inline
When splitting a value of the specified type into parts, does the Lo or Hi part come first? This usually follows the endianness, except for ppcf128, where the Hi part always comes first.
Definition at line 791 of file TargetLowering.h.
References isBigEndian(), and llvm::MVT::ppcf128.
Referenced by getCopyFromParts().
hasExtractBitsInsn()
bool llvm::TargetLoweringBase::hasExtractBitsInsn () const inline
Return true if the target has BitExtract instructions.
Definition at line 189 of file TargetLowering.h.
hasFloatingPointExceptions()
bool llvm::TargetLoweringBase::hasFloatingPointExceptions () const inline
Return true if target supports floating point exceptions.
Definition at line 297 of file TargetLowering.h.
hasLoadLinkedStoreConditional()
virtual bool llvm::TargetLoweringBase::hasLoadLinkedStoreConditional () const inline virtual
True if AtomicExpandPass should use emitLoadLinked/emitStoreConditional and expand AtomicCmpXchgInst.
Reimplemented in llvm::AArch64TargetLowering, and llvm::ARMTargetLowering.
Definition at line 986 of file TargetLowering.h.
hasMultipleConditionRegisters()
bool llvm::TargetLoweringBase::hasMultipleConditionRegisters () const inline
Return true if multiple condition registers are available.
Definition at line 184 of file TargetLowering.h.
hasPairedLoad() [1/2]
virtual bool llvm::TargetLoweringBase::hasPairedLoad (EVT , unsigned &) const inline virtual
Reimplemented in llvm::AArch64TargetLowering.
Definition at line 1500 of file TargetLowering.h.
hasPairedLoad() [2/2]
virtual bool llvm::TargetLoweringBase::hasPairedLoad (Type * , unsigned &) const inline virtual
Return true if the target supplies and combines to a paired load two loaded values of type LoadedType next to each other in memory. RequiredAlignment gives the minimal alignment constraints that must be met to be able to select this paired load.
This information is not used to generate actual paired loads, but it is used to generate a sequence of loads that is easier to combine into a paired load. For instance, something like this: a = load i64* addr b = trunc i64 a to i32 c = lshr i64 a, 32 d = trunc i64 c to i32 will be optimized into: b = load i32* addr1 d = load i32* addr2 Where addr1 = addr2 +/- sizeof(i32).
In other words, unless the target performs a post-isel load combining, this information should not be provided because it will generate more loads.
Reimplemented in llvm::AArch64TargetLowering.
Definition at line 1495 of file TargetLowering.h.
Referenced by adjustCostForPairing().
hasTargetDAGCombine()
bool llvm::TargetLoweringBase::hasTargetDAGCombine (ISD::NodeType NT) const inline
If true, the target has custom DAG combine transformations that it can perform for the specified node.
Definition at line 797 of file TargetLowering.h.
References llvm::array_lengthof().
initActions()
void TargetLoweringBase::initActions () protected
Initialize all of the actions to default values.
Definition at line 741 of file TargetLoweringBase.cpp.
References llvm::MVT::all_valuetypes(), llvm::ISD::ANY_EXTEND_VECTOR_INREG, llvm::array_lengthof(), llvm::ISD::ATOMIC_CMP_SWAP_WITH_SUCCESS, llvm::ISD::CONCAT_VECTORS, llvm::ISD::ConstantFP, llvm::ISD::DEBUGTRAP, Expand, llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FGETSIGN, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FNEARBYINT, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FTRUNC, llvm::ISD::LAST_INDEXED_MODE, llvm::MVT::LAST_VALUETYPE, llvm::MVT::Other, llvm::ISD::PRE_INC, llvm::ISD::PREFETCH, setIndexedLoadAction(), setIndexedStoreAction(), setOperationAction(), llvm::ISD::SIGN_EXTEND_VECTOR_INREG, llvm::ISD::TRAP, and llvm::ISD::ZERO_EXTEND_VECTOR_INREG.
Referenced by llvm::X86TargetLowering::resetOperationActions(), and TargetLoweringBase().
InstructionOpcodeToISD()
int TargetLoweringBase::InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
Definition at line 1376 of file TargetLoweringBase.cpp.
References llvm::ISD::ADD, llvm::Add, llvm::ISD::ADDRSPACECAST, llvm::ISD::AND, llvm::ISD::BITCAST, llvm::Call, llvm::ISD::EXTRACT_VECTOR_ELT, ExtractElement(), llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FREM, llvm::ISD::FSUB, llvm::ISD::INSERT_VECTOR_ELT, llvm_unreachable, llvm::ISD::LOAD, llvm::ISD::MERGE_VALUES, llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::SDIV, llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::SUB, llvm::Sub, llvm::ISD::TRUNCATE, llvm::ISD::UDIV, llvm::ISD::UINT_TO_FP, llvm::ISD::UREM, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by SinkShiftAndTruncate().
isBigEndian()
bool llvm::TargetLoweringBase::isBigEndian () const inline
Definition at line 156 of file TargetLowering.h.
Referenced by ExpandBITCAST(), getCopyFromParts(), getCopyToParts(), hasBigEndianPartOrdering(), isExtendedBUILD_VECTOR(), isNEONModifiedImm(), PerformSTORECombine(), PerformVMOVRRDCombine(), and SkipExtensionForVMULL().
isCheapToSpeculateCtlz()
virtual bool llvm::TargetLoweringBase::isCheapToSpeculateCtlz () const inline virtual
Return true if it is cheap to speculate a call to intrinsic ctlz.
Reimplemented in llvm::AMDGPUTargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 264 of file TargetLowering.h.
isCheapToSpeculateCttz()
virtual bool llvm::TargetLoweringBase::isCheapToSpeculateCttz () const inline virtual
Return true if it is cheap to speculate a call to intrinsic cttz.
Reimplemented in llvm::AMDGPUTargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 259 of file TargetLowering.h.
isCondCodeLegal()
bool llvm::TargetLoweringBase::isCondCodeLegal (ISD::CondCode CC, MVT VT) const inline
Return true if the specified condition code is legal on this target.
Definition at line 652 of file TargetLowering.h.
References Custom, getCondCodeAction(), and Legal.
Referenced by llvm::R600TargetLowering::PerformDAGCombine(), and llvm::TargetLowering::SimplifySetCC().
isExtractSubvectorCheap()
virtual bool llvm::TargetLoweringBase::isExtractSubvectorCheap (EVT ResVT, unsigned Index) const inline virtual
Return true if EXTRACT_SUBVECTOR is cheap for this result type with this index. This is needed because EXTRACT_SUBVECTOR usually has custom lowering that depends on the index of the first element, and only the target knows which lowering is cheap.
Reimplemented in llvm::X86TargetLowering.
Definition at line 1567 of file TargetLowering.h.
isFAbsFree()
virtual bool llvm::TargetLoweringBase::isFAbsFree (EVT VT) const inline virtual
Return true if an fabs operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
Reimplemented in llvm::AMDGPUTargetLowering.
Definition at line 1529 of file TargetLowering.h.
References llvm::EVT::isFloatingPoint().
isFMAFasterThanFMulAndFAdd()
virtual bool llvm::TargetLoweringBase::isFMAFasterThanFMulAndFAdd (EVT) const inline virtual
Return true if an FMA operation is faster than a pair of fmul and fadd instructions. fmuladd intrinsics will be expanded to FMAs when this method returns true, otherwise fmuladd is expanded to fmul + fadd.
NOTE: This may be called before legalization on types for which FMAs are not legal, but should return true if those types will eventually legalize to types that support FMAs. After legalization, it will only be called on types that support FMAs (via Legal or Custom actions)
Reimplemented in llvm::AArch64TargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::SITargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 1542 of file TargetLowering.h.
isFNegFree()
virtual bool llvm::TargetLoweringBase::isFNegFree (EVT VT) const inline virtual
Return true if an fneg operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
Reimplemented in llvm::AMDGPUTargetLowering.
Definition at line 1522 of file TargetLowering.h.
References llvm::EVT::isFloatingPoint().
isFPExtFree()
virtual bool llvm::TargetLoweringBase::isFPExtFree (EVT VT) const inline virtual
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
Reimplemented in llvm::PPCTargetLowering.
Definition at line 1515 of file TargetLowering.h.
References llvm::EVT::isFloatingPoint().
isFPImmLegal()
virtual bool llvm::TargetLoweringBase::isFPImmLegal (const APFloat & , EVT) const inline virtual
Returns true if the target can instruction select the specified FP immediate natively. If false, the legalizer will materialize the FP immediate as a load from a constant pool.
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 492 of file TargetLowering.h.
isFsqrtCheap()
bool llvm::TargetLoweringBase::isFsqrtCheap () const inline
Return true if sqrt(x) is as cheap or cheaper than 1 / rsqrt(x)
Definition at line 221 of file TargetLowering.h.
isIndexedLoadLegal()
bool llvm::TargetLoweringBase::isIndexedLoadLegal (unsigned IdxMode, EVT VT) const inline
Return true if the specified indexed load is legal on this target.
Definition at line 611 of file TargetLowering.h.
References Custom, getIndexedLoadAction(), llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), and Legal.
isIndexedStoreLegal()
bool llvm::TargetLoweringBase::isIndexedStoreLegal (unsigned IdxMode, EVT VT) const inline
Return true if the specified indexed load is legal on this target.
Definition at line 629 of file TargetLowering.h.
References Custom, getIndexedStoreAction(), llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), and Legal.
isIntDivCheap()
bool llvm::TargetLoweringBase::isIntDivCheap () const inline
Return true if integer divide is usually cheaper than a sequence of several shifts, adds, and multiplies for this target.
Definition at line 218 of file TargetLowering.h.
isJumpExpensive()
bool llvm::TargetLoweringBase::isJumpExpensive () const inline
Return true if Flow Control is an expensive operation that should be avoided.
Definition at line 239 of file TargetLowering.h.
isLegalAddImmediate()
virtual bool llvm::TargetLoweringBase::isLegalAddImmediate (int64_t) const inline virtual
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register with the immediate without having to materialize the immediate into a register.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 1426 of file TargetLowering.h.
isLegalAddressingMode()
bool TargetLoweringBase::isLegalAddressingMode (const AddrMode & AM, Type * Ty) const virtual
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
The type may be VoidTy, in which case only return true if the addressing mode is legal for a load/store of any legal type. TODO: Handle pre/postinc as well.
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::NVPTXTargetLowering, llvm::PPCTargetLowering, llvm::SITargetLowering, llvm::SystemZTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 1476 of file TargetLoweringBase.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::TargetLoweringBase::AddrMode::HasBaseReg, and llvm::TargetLoweringBase::AddrMode::Scale.
Referenced by canFoldInAddressingMode(), and getScalingFactorCost().
isLegalICmpImmediate()
virtual bool llvm::TargetLoweringBase::isLegalICmpImmediate (int64_t) const inline virtual
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::HexagonTargetLowering, llvm::PPCTargetLowering, and llvm::X86TargetLowering.
Definition at line 1419 of file TargetLowering.h.
Referenced by llvm::TargetLowering::SimplifySetCC().
isLegalRC()
bool TargetLoweringBase::isLegalRC (const TargetRegisterClass * RC) const protected
Return true if the value types that can be represented by the specified register class are all legal.
isLegalRC - Return true if the value types that can be represented by the specified register class are all legal.
Definition at line 947 of file TargetLoweringBase.cpp.
References I, isTypeLegal(), llvm::TargetRegisterClass::vt_begin(), and llvm::TargetRegisterClass::vt_end().
Referenced by findRepresentativeClass(), and llvm::TargetLowering::getRegForInlineAsmConstraint().
isLittleEndian()
bool llvm::TargetLoweringBase::isLittleEndian () const inline
Definition at line 157 of file TargetLowering.h.
Referenced by llvm::ARMTargetLowering::allowsMisalignedMemoryAccesses(), ExpandUnalignedLoad(), ExpandUnalignedStore(), getMemsetStringVal(), llvm::PPCTargetLowering::PerformDAGCombine(), ShrinkLoadReplaceStoreWithStore(), and llvm::TargetLowering::SimplifySetCC().
isLoadBitCastBeneficial()
virtual bool llvm::TargetLoweringBase::isLoadBitCastBeneficial (EVT , EVT) const inline virtual
isLoadBitCastBeneficial() - Return true if the following transform is beneficial. fold (conv (load x)) -> (load (conv*)x) On architectures that don't natively support some vector loads efficiently, casting the load to a smaller vector of larger types and loading is more efficient, however, this can be undone by optimizations in dag combiner.
Reimplemented in llvm::AMDGPUTargetLowering.
Definition at line 254 of file TargetLowering.h.
isLoadExtLegal()
bool llvm::TargetLoweringBase::isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const inline
Return true if the specified load with extension is legal on this target.
Definition at line 575 of file TargetLowering.h.
References getLoadExtAction(), llvm::EVT::isSimple(), and Legal.
isMaskAndBranchFoldingLegal()
bool llvm::TargetLoweringBase::isMaskAndBranchFoldingLegal () const inline
Return if the target supports combining a chain like:
%andResult = and %val1, #imm-with-one-bit-set;
%icmpResult = icmp %andResult, 0
br i1 %icmpResult, label %dest1, label %dest2
into a single machine instruction of a form like:
brOnBitSet %register, #bitNumber, dest
Definition at line 279 of file TargetLowering.h.
References MaskAndBranchFoldingIsLegal.
isNarrowingProfitable()
virtual bool llvm::TargetLoweringBase::isNarrowingProfitable (EVT , EVT) const inline virtual
Return true if it's profitable to narrow operations of type VT1 to VT2. e.g. on x86, it's profitable to narrow from i32 to i8 but not from i32 to i16.
Reimplemented in llvm::AMDGPUTargetLowering, and llvm::X86TargetLowering.
Definition at line 1549 of file TargetLowering.h.
isNoopAddrSpaceCast()
virtual bool llvm::TargetLoweringBase::isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const inline virtual
Returns true if a cast between SrcAS and DestAS is a noop.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, and llvm::X86TargetLowering.
Definition at line 964 of file TargetLowering.h.
isOperationExpand()
bool llvm::TargetLoweringBase::isOperationExpand (unsigned Op, EVT VT) const inline
Return true if the specified operation is illegal on this target or unlikely to be made legal with custom lowering. This is used to help guide high-level lowering decisions.
Definition at line 552 of file TargetLowering.h.
References Expand, getOperationAction(), and isTypeLegal().
isOperationLegal()
bool llvm::TargetLoweringBase::isOperationLegal (unsigned Op, EVT VT) const inline
Return true if the specified operation is legal on this target.
Definition at line 557 of file TargetLowering.h.
References getOperationAction(), isTypeLegal(), Legal, and llvm::MVT::Other.
Referenced by llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), combineMinNumMaxNum(), EltsFromConsecutiveLoads(), llvm::R600TargetLowering::PerformDAGCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformShuffleCombine(), llvm::TargetLowering::SimplifySetCC(), and tryFoldToZero().
isOperationLegalOrCustom()
bool llvm::TargetLoweringBase::isOperationLegalOrCustom (unsigned Op, EVT VT) const inline
Return true if the specified operation is legal on this target or can be made legal with custom lowering. This is used to help guide high-level lowering decisions.
Definition at line 534 of file TargetLowering.h.
References Custom, getOperationAction(), isTypeLegal(), Legal, and llvm::MVT::Other.
Referenced by areJTsAllowed(), buildFromShuffleMostly(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), llvm::TargetLowering::expandMUL(), FindOptimalMemOpLowering(), llvm::X86TargetLowering::isExtractSubvectorCheap(), isNegatibleForFree(), LowerExtendedLoad(), PerformSELECTCombine(), llvm::TargetLowering::SimplifyDemandedBits(), SinkShiftAndTruncate(), and XFormVExtractWithShuffleIntoLoad().
isOperationLegalOrPromote()
bool llvm::TargetLoweringBase::isOperationLegalOrPromote (unsigned Op, EVT VT) const inline
Return true if the specified operation is legal on this target or can be made legal using promotion. This is used to help guide high-level lowering decisions.
Definition at line 543 of file TargetLowering.h.
References getOperationAction(), isTypeLegal(), Legal, llvm::MVT::Other, and Promote.
Referenced by WidenMaskArithmetic().
isPow2SDivCheap()
bool llvm::TargetLoweringBase::isPow2SDivCheap () const inline
Return true if pow2 sdiv is cheaper than a chain of sra/srl/add/sra.
Definition at line 235 of file TargetLowering.h.
isPredictableSelectExpensive()
bool llvm::TargetLoweringBase::isPredictableSelectExpensive () const inline
Return true if selects are only cheaper than branches if the branch is unlikely to be predicted right.
Definition at line 243 of file TargetLowering.h.
References PredictableSelectIsExpensive.
isSafeMemOpType()
virtual bool llvm::TargetLoweringBase::isSafeMemOpType (MVT) const inline virtual
Returns true if it's safe to use load / store of the specified type to expand memcpy / memset inline.
This is mostly true for all types except for some special cases. For example, on X86 targets without SSE2 f64 load / store are done with fldl / fstpl which also does type conversion. Note the specified type doesn't have to be legal as the hook is used before type legalization.
Reimplemented in llvm::X86TargetLowering.
Definition at line 875 of file TargetLowering.h.
Referenced by FindOptimalMemOpLowering().
isSelectExpensive()
bool llvm::TargetLoweringBase::isSelectExpensive () const inline
Return true if the select operation is expensive for this target.
Definition at line 177 of file TargetLowering.h.
isSelectSupported()
virtual bool llvm::TargetLoweringBase::isSelectSupported (SelectSupportKind) const inline virtual
Reimplemented in llvm::AMDGPUTargetLowering, and llvm::ARMTargetLowering.
Definition at line 179 of file TargetLowering.h.
isShuffleMaskLegal()
virtual bool llvm::TargetLoweringBase::isShuffleMaskLegal (const SmallVectorImpl< int > & , EVT) const inline virtual
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks. By default, if a target supports the VECTOR_SHUFFLE node, all mask values are assumed to be legal.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::MipsSETargetLowering, llvm::SITargetLowering, and llvm::X86TargetLowering.
Definition at line 500 of file TargetLowering.h.
Referenced by ExpandBVWithShuffles(), and transformVSELECTtoBlendVECTOR_SHUFFLE().
isSlowDivBypassed()
bool llvm::TargetLoweringBase::isSlowDivBypassed () const inline
Returns true if target has indicated at least one type should be bypassed.
Definition at line 226 of file TargetLowering.h.
isTruncateFree() [1/2]
virtual bool llvm::TargetLoweringBase::isTruncateFree (EVT , EVT) const inline virtual
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::HexagonTargetLowering, llvm::MSP430TargetLowering, llvm::PPCTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 1454 of file TargetLowering.h.
isTruncateFree() [2/2]
virtual bool llvm::TargetLoweringBase::isTruncateFree (Type * , Type *) const inline virtual
Return true if it's free to truncate a value of type Ty1 to type Ty2. e.g. On x86 it's free to truncate a i32 value in register EAX to i16 by referencing its sub-register AX.
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::HexagonTargetLowering, llvm::MSP430TargetLowering, llvm::PPCTargetLowering, llvm::SystemZTargetLowering, and llvm::X86TargetLowering.
Definition at line 1441 of file TargetLowering.h.
Referenced by ExtendUsesToFormExtLoad(), getMemsetStores(), and llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp().
isTruncStoreLegal()
bool llvm::TargetLoweringBase::isTruncStoreLegal (EVT ValVT, EVT MemVT) const inline
Return true if the specified store with truncation is legal on this target.
Definition at line 594 of file TargetLowering.h.
References llvm::EVT::getSimpleVT(), getTruncStoreAction(), llvm::EVT::isSimple(), isTypeLegal(), and Legal.
isTypeLegal()
bool llvm::TargetLoweringBase::isTypeLegal (EVT VT) const inline
Return true if the target has native support for the specified value type. This means that it has a register that directly holds it without promotions or expansions.
Definition at line 381 of file TargetLowering.h.
References llvm::array_lengthof(), llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), and llvm::MVT::SimpleTy.
Referenced by llvm::ARMTargetLowering::allowTruncateForTailCall(), llvm::X86TargetLowering::allowTruncateForTailCall(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), canOpTrap(), computeRegisterProperties(), EltsFromConsecutiveLoads(), ExpandBITCAST(), ExpandUnalignedLoad(), ExpandUnalignedStore(), FindMemType(), FindOptimalMemOpLowering(), getCopyFromPartsVector(), getCopyToParts(), getTypeToPromoteTo(), getVectorTypeBreakdown(), getVectorTypeBreakdownMVT(), llvm::GenericScheduler::initPolicy(), isLegalRC(), isNoopBitcast(), isOperationExpand(), isOperationLegal(), isOperationLegalOrCustom(), isOperationLegalOrPromote(), llvm::X86TargetLowering::isShuffleMaskLegal(), isTruncStoreLegal(), llvm::TargetLowering::isTypeDesirableForOp(), llvm::X86TargetLowering::isTypeDesirableForOp(), llvm::NVPTXTargetLowering::isTypeSupportedInIntrinsic(), LowerADDC_ADDE_SUBC_SUBE(), LowerADDC_ADDE_SUBC_SUBE(), LowerATOMIC_STORE(), LowerExtendedLoad(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), LowerSINT_TO_FP(), LowerUINT_TO_FP(), LowerVectorIntExtend(), lowerVectorShuffle(), LowerXALUO(), OptimizeExtractBits(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), PerformExtendCombine(), performExtendCombine(), PerformFMACombine(), PerformMLOADCombine(), PerformMSTORECombine(), PerformORCombine(), performORCombine(), PerformSELECTCombine(), PerformShiftCombine(), PerformShuffleCombine(), PerformSTORECombine(), PerformSTORECombine(), PerformVECTOR_SHUFFLECombine(), PerformXORCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::TargetLowering::SimplifySetCC(), llvm::SystemZTargetLowering::SystemZTargetLowering(), tryToFoldExtendOfConstant(), and llvm::SelectionDAGBuilder::visitBitTestHeader().
isVectorClearMaskLegal()
virtual bool llvm::TargetLoweringBase::isVectorClearMaskLegal (const SmallVectorImpl< int > & , EVT) const inline virtual
Similar to isShuffleMaskLegal. This is used by Targets can use this to indicate if there is a suitable VECTOR_SHUFFLE that can be used to replace a VAND with a constant pool entry.
Reimplemented in llvm::X86TargetLowering.
Definition at line 514 of file TargetLowering.h.
isVectorShiftByScalarCheap()
virtual bool llvm::TargetLoweringBase::isVectorShiftByScalarCheap (Type * Ty) const inline virtual
Return true if it's significantly cheaper to shift a vector by a uniform scalar than by an amount which will vary across each lane. On x86, for example, there is a "psllw" instruction for the former case, but no simple instruction for a general "a << b" operation on vectors.
Reimplemented in llvm::X86TargetLowering.
Definition at line 1434 of file TargetLowering.h.
isZExtFree() [1/3]
virtual bool llvm::TargetLoweringBase::isZExtFree (EVT , EVT) const inline virtual
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::MSP430TargetLowering, and llvm::X86TargetLowering.
Definition at line 1470 of file TargetLowering.h.
isZExtFree() [2/3]
virtual bool llvm::TargetLoweringBase::isZExtFree (SDValue Val, EVT VT2) const inline virtual
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::ARMTargetLowering, llvm::MSP430TargetLowering, llvm::PPCTargetLowering, llvm::X86TargetLowering, and llvm::XCoreTargetLowering.
Definition at line 1508 of file TargetLowering.h.
References llvm::SDValue::getValueType(), and isZExtFree().
isZExtFree() [3/3]
virtual bool llvm::TargetLoweringBase::isZExtFree (Type * , Type *) const inline virtual
Return true if any actual instruction that defines a value of type Ty1 implicitly zero-extends the value to Ty2 in the result register.
This does not necessarily include registers defined in unknown ways, such as incoming arguments, or copies from unknown virtual registers. Also, if isTruncateFree(Ty2, Ty1) is true, this does not necessarily apply to truncate instructions. e.g. on x86-64, all instructions that define 32-bit values implicit zero-extend the result out to 64 bits.
Reimplemented in llvm::AArch64TargetLowering, llvm::AMDGPUTargetLowering, llvm::MSP430TargetLowering, and llvm::X86TargetLowering.
Definition at line 1466 of file TargetLowering.h.
Referenced by hasSameExtUse(), llvm::PPCTargetLowering::isZExtFree(), isZExtFree(), and llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp().
lowerIdempotentRMWIntoFencedLoad()
virtual LoadInst * llvm::TargetLoweringBase::lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst * RMWI) const inline virtual
On some platforms, an AtomicRMW that never actually modifies the value (such as fetch_add of 0) can be turned into a fence followed by an atomic load. This may sound useless, but it makes it possible for the processor to keep the cacheline shared, dramatically improving performance. And such idempotent RMWs are useful for implementing some kinds of locks, see for example (justification + benchmarks): http://www.hpl.hp.com/techreports/2012/HPL-2012-68.pdf This method tries doing that transformation, returning the atomic load if it succeeds, and nullptr otherwise. If shouldExpandAtomicLoadInIR returns true on that load, it will undergo another round of expansion.
Definition at line 1085 of file TargetLowering.h.
resetOperationActions()
virtual void llvm::TargetLoweringBase::resetOperationActions () inline virtual
Reset the operation actions based on target options.
Reimplemented in llvm::X86TargetLowering.
Definition at line 1094 of file TargetLowering.h.
setBooleanContents() [1/2]
void llvm::TargetLoweringBase::setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy) inline protected
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type. See getBooleanContents.
Definition at line 1106 of file TargetLowering.h.
setBooleanContents() [2/2]
void llvm::TargetLoweringBase::setBooleanContents (BooleanContent Ty) inline protected
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type. See getBooleanContents.
Definition at line 1099 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setBooleanVectorContents()
void llvm::TargetLoweringBase::setBooleanVectorContents (BooleanContent Ty) inline protected
Specify how the target extends the result of a vector boolean value from a vector of i1 to a wider type. See getBooleanContents.
Definition at line 1113 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setCmpLibcallCC()
void llvm::TargetLoweringBase::setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC) inline
Override the default CondCode to be used to test the result of the comparison libcall against zero.
Definition at line 1587 of file TargetLowering.h.
References llvm::Call.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
setCondCodeAction()
void llvm::TargetLoweringBase::setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action) inline protected
Indicate that the specified condition code is or isn't supported on the target and indicate what to do about it.
The lower 5 bits of the SimpleTy index into Nth 2bit set from the 32-bit value and the upper 27 bits index into the second dimension of the array to select what 32-bit value to use.
Definition at line 1295 of file TargetLowering.h.
References llvm::array_lengthof(), llvm::MVT::isValid(), and llvm::MVT::SimpleTy.
Referenced by llvm::MipsSETargetLowering::addMSAFloatType(), llvm::MipsSETargetLowering::addMSAIntType(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), and llvm::X86TargetLowering::resetOperationActions().
setExceptionPointerRegister()
void llvm::TargetLoweringBase::setExceptionPointerRegister (unsigned R) inline protected
If set to a physical register, this sets the register that receives the exception address on entry to a landing pad.
Definition at line 1148 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setExceptionSelectorRegister()
void llvm::TargetLoweringBase::setExceptionSelectorRegister (unsigned R) inline protected
If set to a physical register, this sets the register that receives the exception typeid on entry to a landing pad.
Definition at line 1154 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setFsqrtIsCheap()
void llvm::TargetLoweringBase::setFsqrtIsCheap (bool isCheap = true) inline protected
Tells the code generator that fsqrt is cheap, and should not be replaced with an alternative sequence of instructions.
Definition at line 1194 of file TargetLowering.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering().
setHasExtractBitsInsn()
void llvm::TargetLoweringBase::setHasExtractBitsInsn (bool hasExtractInsn = true) inline protected
Tells the code generator that the target has BitExtract instructions. The code generator will aggressively sink "shift"s into the blocks of their users if the users will generate "and" instructions which can be combined with "shift" to BitExtract instructions.
Definition at line 1177 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering().
setHasFloatingPointExceptions()
void llvm::TargetLoweringBase::setHasFloatingPointExceptions (bool FPExceptions = true) inline protected
Tells the code generator that this target supports floating point exceptions and cares about preserving floating point exception behavior.
Definition at line 1198 of file TargetLowering.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering().
setHasMultipleConditionRegisters()
void llvm::TargetLoweringBase::setHasMultipleConditionRegisters (bool hasManyRegs = true) inline protected
Tells the code generator that the target has multiple (allocatable) condition registers that can be used to store the results of comparisons for use by selects and conditional branches. With multiple condition registers, the code generator will not aggressively sink comparisons into the blocks of their users.
Definition at line 1169 of file TargetLowering.h.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
setIndexedLoadAction()
void llvm::TargetLoweringBase::setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action) inline protected
Indicate that the specified indexed load does or does not work with the specified type and indicate what to do abort it.
NOTE: All indexed mode loads are initialized to Expand in TargetLowering.cpp
Definition at line 1270 of file TargetLowering.h.
References llvm::MVT::isValid(), llvm::ISD::LAST_INDEXED_MODE, and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), initActions(), llvm::MSP430TargetLowering::MSP430TargetLowering(), and llvm::PPCTargetLowering::PPCTargetLowering().
setIndexedStoreAction()
void llvm::TargetLoweringBase::setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action) inline protected
Indicate that the specified indexed store does or does not work with the specified type and indicate what to do about it.
NOTE: All indexed mode stores are initialized to Expand in TargetLowering.cpp
Definition at line 1284 of file TargetLowering.h.
References llvm::MVT::isValid(), llvm::ISD::LAST_INDEXED_MODE, and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), initActions(), and llvm::PPCTargetLowering::PPCTargetLowering().
setInsertFencesForAtomic()
void llvm::TargetLoweringBase::setInsertFencesForAtomic (bool fence) inline protected
Set if the DAG builder should automatically insert fences and reduce the order of atomic memory operations to Monotonic.
Definition at line 1361 of file TargetLowering.h.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setIntDivIsCheap()
void llvm::TargetLoweringBase::setIntDivIsCheap (bool isCheap = true) inline protected
Tells the code generator that integer divide is expensive, and if possible, should be replaced by an alternate sequence of instructions not containing an integer divide.
Definition at line 1190 of file TargetLowering.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setJumpBufAlignment()
void llvm::TargetLoweringBase::setJumpBufAlignment (unsigned Align) inline protected
Set the target's required jmp_buf buffer alignment (in bytes); default is 0
Definition at line 1330 of file TargetLowering.h.
References Align.
setJumpBufSize()
void llvm::TargetLoweringBase::setJumpBufSize (unsigned Size) inline protected
Set the target's required jmp_buf buffer size (in bytes); default is 200.
Definition at line 1324 of file TargetLowering.h.
setJumpIsExpensive()
void llvm::TargetLoweringBase::setJumpIsExpensive (bool isExpensive = true) inline protected
Tells the code generator not to expand sequence of operations into a separate sequences that increases the amount of flow control.
Definition at line 1183 of file TargetLowering.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), and llvm::NVPTXTargetLowering::NVPTXTargetLowering().
setLibcallCallingConv()
void llvm::TargetLoweringBase::setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC) inline
Set the CallingConv that should be used for the specified libcall.
Definition at line 1598 of file TargetLowering.h.
References llvm::Call.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), and llvm::X86TargetLowering::resetOperationActions().
setLibcallName()
void llvm::TargetLoweringBase::setLibcallName (RTLIB::Libcall Call, const char * Name) inline
Rename the default libcall routine name for the specified libcall.
Definition at line 1576 of file TargetLowering.h.
References llvm::Call, and Name.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), and llvm::SparcTargetLowering::SparcTargetLowering().
setLoadExtAction()
void llvm::TargetLoweringBase::setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action) inline protected
Indicate that the specified load with extension does not work with the specified type and indicate what to do about it.
Definition at line 1250 of file TargetLowering.h.
References llvm::MVT::isValid(), llvm::ISD::LAST_LOADEXT_TYPE, and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SITargetLowering::SITargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setMinFunctionAlignment()
void llvm::TargetLoweringBase::setMinFunctionAlignment (unsigned Align) inline protected
Set the target's minimum function alignment (in log2(bytes))
Definition at line 1335 of file TargetLowering.h.
References Align.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setMinimumJumpTableEntries()
void llvm::TargetLoweringBase::setMinimumJumpTableEntries (int Val) inline protected
Indicate the number of blocks to generate jump tables rather than if sequence.
Definition at line 1136 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering().
setMinStackArgumentAlignment()
void llvm::TargetLoweringBase::setMinStackArgumentAlignment (unsigned Align) inline protected
Set the minimum stack alignment of an argument (in log2(bytes)).
Definition at line 1355 of file TargetLowering.h.
References Align.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), and llvm::PPCTargetLowering::PPCTargetLowering().
setOperationAction()
void llvm::TargetLoweringBase::setOperationAction (unsigned Op, MVT VT, LegalizeAction Action) inline protected
Indicate that the specified operation does not work with the specified type and indicate what to do about it.
Definition at line 1242 of file TargetLowering.h.
References llvm::array_lengthof(), and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::MipsSETargetLowering::addMSAFloatType(), llvm::MipsSETargetLowering::addMSAIntType(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), initActions(), llvm::Mips16TargetLowering::Mips16TargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SITargetLowering::SITargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setPow2SDivIsCheap()
void llvm::TargetLoweringBase::setPow2SDivIsCheap (bool isCheap = true) inline protected
Tells the code generator that it shouldn't generate sra/srl/add/sra for a signed divide by power of two; let the target handle it.
Definition at line 1209 of file TargetLowering.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering().
setPrefFunctionAlignment()
void llvm::TargetLoweringBase::setPrefFunctionAlignment (unsigned Align) inline protected
Set the target's preferred function alignment. This should be set if there is a performance benefit to higher-than-minimum alignment (in log2(bytes))
Definition at line 1342 of file TargetLowering.h.
References Align.
Referenced by llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setPrefLoopAlignment()
void llvm::TargetLoweringBase::setPrefLoopAlignment (unsigned Align) inline protected
Set the target's preferred loop alignment. Default alignment is zero, it means the target does not care about loop alignment. The alignment is specified in log2(bytes). The target may also override getPrefLoopAlignment to provide per-loop values.
Definition at line 1350 of file TargetLowering.h.
References Align.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), and llvm::X86TargetLowering::resetOperationActions().
setSchedulingPreference()
void llvm::TargetLoweringBase::setSchedulingPreference (Sched::Preference Pref) inline protected
Specify the target scheduling preference.
Definition at line 1118 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SITargetLowering::SITargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setSelectIsExpensive()
void llvm::TargetLoweringBase::setSelectIsExpensive (bool isExpensive = true) inline protected
Tells the code generator not to expand operations into sequences that use the select operations if possible.
Definition at line 1160 of file TargetLowering.h.
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering().
setStackPointerRegisterToSaveRestore()
void llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore (unsigned R) inline protected
If set to a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
Definition at line 1142 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setTargetDAGCombine()
void llvm::TargetLoweringBase::setTargetDAGCombine (ISD::NodeType NT) inline protected
Targets should invoke this method for each target independent node that they want to provide a custom DAG combiner for by implementing the PerformDAGCombine virtual method.
Definition at line 1318 of file TargetLowering.h.
References llvm::array_lengthof().
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SITargetLowering::SITargetLowering(), llvm::SystemZTargetLowering::SystemZTargetLowering(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
setTruncStoreAction()
void llvm::TargetLoweringBase::setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action) inline protected
Indicate that the specified truncating store does not work with the specified type and indicate what to do about it.
Definition at line 1259 of file TargetLowering.h.
References llvm::MVT::isValid(), and llvm::MVT::SimpleTy.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::MSP430TargetLowering::MSP430TargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::R600TargetLowering::R600TargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SITargetLowering::SITargetLowering(), llvm::SparcTargetLowering::SparcTargetLowering(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
setUseUnderscoreLongJmp()
void llvm::TargetLoweringBase::setUseUnderscoreLongJmp (bool Val) inline protected
Indicate whether this target prefers to use _longjmp to implement llvm.longjmp or the version without _. Defaults to false.
Definition at line 1130 of file TargetLowering.h.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering(), and llvm::X86TargetLowering::resetOperationActions().
setUseUnderscoreSetJmp()
void llvm::TargetLoweringBase::setUseUnderscoreSetJmp (bool Val) inline protected
Indicate whether this target prefers to use _setjmp to implement llvm.setjmp or the version without _. Defaults to false.
Definition at line 1124 of file TargetLowering.h.
Referenced by llvm::PPCTargetLowering::PPCTargetLowering(), and llvm::X86TargetLowering::resetOperationActions().
shouldConvertConstantLoadToIntImm()
virtual bool llvm::TargetLoweringBase::shouldConvertConstantLoadToIntImm (const APInt & Imm, Type * Ty) const inline virtual
Return true if it is beneficial to convert a load of a constant to just the constant itself. On some targets it might be more efficient to use a combination of arithmetic instructions to materialize the constant instead of loading it from a constant pool.
Reimplemented in llvm::AArch64TargetLowering, llvm::ARMTargetLowering, llvm::PPCTargetLowering, llvm::SITargetLowering, and llvm::X86TargetLowering.
Definition at line 1558 of file TargetLowering.h.
Referenced by getMemsetStringVal().
shouldExpandAtomicLoadInIR()
virtual bool llvm::TargetLoweringBase::shouldExpandAtomicLoadInIR (LoadInst * LI) const inline virtual
Returns true if the given (atomic) load should be expanded by the IR-level AtomicExpand pass into a load-linked instruction (through emitLoadLinked()).
Reimplemented in llvm::AArch64TargetLowering, and llvm::ARMTargetLowering.
Definition at line 1066 of file TargetLowering.h.
shouldExpandAtomicRMWInIR()
virtual bool llvm::TargetLoweringBase::shouldExpandAtomicRMWInIR (AtomicRMWInst * RMWI) const inline virtual
Returns true if the given AtomicRMW should be expanded by the IR-level AtomicExpand pass into a loop using LoadLinked/StoreConditional.
Reimplemented in llvm::AArch64TargetLowering, and llvm::ARMTargetLowering.
Definition at line 1070 of file TargetLowering.h.
shouldExpandAtomicStoreInIR()
virtual bool llvm::TargetLoweringBase::shouldExpandAtomicStoreInIR (StoreInst * SI) const inline virtual
Returns true if the given (atomic) store should be expanded by the IR-level AtomicExpand pass into an "atomic xchg" which ignores its input.
Reimplemented in llvm::AArch64TargetLowering, and llvm::ARMTargetLowering.
Definition at line 1059 of file TargetLowering.h.
shouldExpandBuildVectorWithShuffles()
virtual bool llvm::TargetLoweringBase::shouldExpandBuildVectorWithShuffles (EVT , unsigned DefinedValues) const inline virtual
Reimplemented in llvm::PPCTargetLowering.
Definition at line 211 of file TargetLowering.h.
Referenced by llvm::PPCTargetLowering::shouldExpandBuildVectorWithShuffles().
shouldReduceLoadWidth()
virtual bool llvm::TargetLoweringBase::shouldReduceLoadWidth (SDNode * Load, ISD::LoadExtType ExtTy, EVT NewVT) const inline virtual
Reimplemented in llvm::AMDGPUTargetLowering, and llvm::X86TargetLowering.
Definition at line 782 of file TargetLowering.h.
ShouldShrinkFPConstant()
virtual bool llvm::TargetLoweringBase::ShouldShrinkFPConstant (EVT) const inline virtual
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
Reimplemented in llvm::AMDGPUTargetLowering, llvm::SparcTargetLowering, and llvm::X86TargetLowering.
Definition at line 776 of file TargetLowering.h.
usesUnderscoreLongJmp()
bool llvm::TargetLoweringBase::usesUnderscoreLongJmp () const inline
Determine if we should use _longjmp or longjmp to implement llvm.longjmp.
Definition at line 883 of file TargetLowering.h.
usesUnderscoreSetJmp()
bool llvm::TargetLoweringBase::usesUnderscoreSetJmp () const inline
Determine if we should use _setjmp or setjmp to implement llvm.setjmp.
Definition at line 878 of file TargetLowering.h.
Member Data Documentation
EnableExtLdPromotion
bool llvm::TargetLoweringBase::EnableExtLdPromotion protected
See also
enableExtLdPromotion.
Definition at line 2004 of file TargetLowering.h.
Referenced by enableExtLdPromotion(), llvm::X86TargetLowering::resetOperationActions(), and TargetLoweringBase().
MaskAndBranchFoldingIsLegal
bool llvm::TargetLoweringBase::MaskAndBranchFoldingIsLegal protected
MaskAndBranchFoldingIsLegal - Indicates if the target supports folding a mask of a single bit, a compare, and a branch into a single instruction.
Definition at line 2001 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), isMaskAndBranchFoldingLegal(), and TargetLoweringBase().
MaxStoresPerMemcpy
unsigned llvm::TargetLoweringBase::MaxStoresPerMemcpy protected
Specify maximum bytes of store instructions per memcpy call.
When lowering @llvm.memcpy this field specifies the maximum number of store operations that may be substituted for a call to memcpy. Targets must set this value based on the cost threshold for that target. Targets should assume that the memcpy will be done using as many of the largest store operations first, followed by smaller ones, if necessary, per alignment restrictions. For example, storing 7 bytes on a 32-bit machine with 32-bit alignment would result in one 4-byte store, a one 2-byte store and one 1-byte store. This only applies to copying a constant array of constant size.
Definition at line 1973 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), getMaxStoresPerMemcpy(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SystemZTargetLowering::SystemZTargetLowering(), TargetLoweringBase(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
MaxStoresPerMemcpyOptSize
unsigned llvm::TargetLoweringBase::MaxStoresPerMemcpyOptSize protected
Maximum number of store operations that may be substituted for a call to memcpy, used for functions with OptSize attribute.
Definition at line 1977 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), getMaxStoresPerMemcpy(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SystemZTargetLowering::SystemZTargetLowering(), TargetLoweringBase(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
MaxStoresPerMemmove
unsigned llvm::TargetLoweringBase::MaxStoresPerMemmove protected
Specify maximum bytes of store instructions per memmove call.
When lowering @llvm.memmove this field specifies the maximum number of store instructions that may be substituted for a call to memmove. Targets must set this value based on the cost threshold for that target. Targets should assume that the memmove will be done using as many of the largest store operations first, followed by smaller ones, if necessary, per alignment restrictions. For example, moving 9 bytes on a 32-bit machine with 8-bit alignment would result in nine 1-byte stores. This only applies to copying a constant array of constant size.
Definition at line 1989 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), getMaxStoresPerMemmove(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), TargetLoweringBase(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
MaxStoresPerMemmoveOptSize
unsigned llvm::TargetLoweringBase::MaxStoresPerMemmoveOptSize protected
Maximum number of store instructions that may be substituted for a call to memmove, used for functions with OpSize attribute.
Definition at line 1993 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), getMaxStoresPerMemmove(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), TargetLoweringBase(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
MaxStoresPerMemset
unsigned llvm::TargetLoweringBase::MaxStoresPerMemset protected
Specify maximum number of store instructions per memset call.
When lowering @llvm.memset this field specifies the maximum number of store operations that may be substituted for the call to memset. Targets must set this value based on the cost threshold for that target. Targets should assume that the memset will be done using as many of the largest store operations first, followed by smaller ones, if necessary, per alignment restrictions. For example, storing 9 bytes on a 32-bit machine with 16-bit alignment would result in four 2-byte stores and one 1-byte store. This only applies to setting a constant array of a constant size.
Definition at line 1956 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), getMaxStoresPerMemset(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SystemZTargetLowering::SystemZTargetLowering(), TargetLoweringBase(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
MaxStoresPerMemsetOptSize
unsigned llvm::TargetLoweringBase::MaxStoresPerMemsetOptSize protected
Maximum number of stores operations that may be substituted for the call to memset, used for functions with OptSize attribute.
Definition at line 1960 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), getMaxStoresPerMemset(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::X86TargetLowering::resetOperationActions(), llvm::SystemZTargetLowering::SystemZTargetLowering(), TargetLoweringBase(), and llvm::XCoreTargetLowering::XCoreTargetLowering().
PredictableSelectIsExpensive
bool llvm::TargetLoweringBase::PredictableSelectIsExpensive protected
Tells the code generator that select is more expensive than a branch if the branch is usually predicted right.
Definition at line 1997 of file TargetLowering.h.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AMDGPUTargetLowering::AMDGPUTargetLowering(), llvm::ARMTargetLowering::ARMTargetLowering(), isPredictableSelectExpensive(), llvm::X86TargetLowering::resetOperationActions(), and TargetLoweringBase().
The documentation for this class was generated from the following files:
TargetLowering.h
TargetLoweringBase.cpp