LLVM: llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT > Class Template Reference
LLVM API Documentation
llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT > Class Template Reference
A CRTP base used to implement analysis managers.
#include <PassManager.h>
Public Member Functions
template<typename PassT>
PassT::Result & getResult (IRUnitT &IR)
Get the result of an analysis pass for this module.
template<typename PassT>
PassT::Result * getCachedResult (IRUnitT &IR) const
Get the cached result of an analysis pass for this module.
template<typename PassT>
void registerPass (PassT Pass)
Register an analysis pass with the manager.
template<typename PassT>
void invalidate (IRUnitT &IR)
Invalidate a specific analysis pass for an IR module.
PreservedAnalyses invalidate (IRUnitT &IR, PreservedAnalyses PA)
Invalidate analyses cached for an IR unit.
Protected Types
typedef detail::AnalysisResultConcept< IRUnitT > ResultConceptT
typedef detail::AnalysisPassConcept< IRUnitT > PassConceptT
Protected Member Functions
AnalysisManagerBase ()
AnalysisManagerBase (AnalysisManagerBase &&Arg)
AnalysisManagerBase & operator= (AnalysisManagerBase &&RHS)
PassConceptT & lookupPass (void *PassID)
Lookup a registered analysis pass.
const PassConceptT & lookupPass (void *PassID) const
Lookup a registered analysis pass.
Detailed Description
template<typename DerivedT, typename IRUnitT>
class llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >
A CRTP base used to implement analysis managers.
This class template serves as the boiler plate of an analysis manager. Any analysis manager can be implemented on top of this base class. Any implementation will be required to provide specific hooks:
getResultImpl
getCachedResultImpl
invalidateImpl
The details of the call pattern are within.
Note that there is also a generic analysis manager template which implements the above required functions along with common datastructures used for managing analyses. This base class is factored so that if you need to customize the handling of a specific IR unit, you can do so without replicating all of the boilerplate.
Definition at line 278 of file IR/PassManager.h.
Member Typedef Documentation
PassConceptT
template<typename DerivedT, typename IRUnitT> typedef detail::AnalysisPassConcept<IRUnitT> llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::PassConceptT protected
Definition at line 290 of file IR/PassManager.h.
ResultConceptT
template<typename DerivedT, typename IRUnitT> typedef detail::AnalysisResultConcept<IRUnitT> llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::ResultConceptT protected
Definition at line 289 of file IR/PassManager.h.
Constructor & Destructor Documentation
AnalysisManagerBase() [1/2]
template<typename DerivedT, typename IRUnitT> llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::AnalysisManagerBase () inline protected
Definition at line 297 of file IR/PassManager.h.
AnalysisManagerBase() [2/2]
template<typename DerivedT, typename IRUnitT> llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::AnalysisManagerBase (AnalysisManagerBase< DerivedT, IRUnitT > && Arg) inline protected
Definition at line 298 of file IR/PassManager.h.
Member Function Documentation
getCachedResult()
template<typename DerivedT, typename IRUnitT> template<typename PassT> PassT::Result * llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::getCachedResult (IRUnitT & IR) const inline
Get the cached result of an analysis pass for this module.
This method never runs the analysis.
Returns
null if there is no cached result.
Definition at line 327 of file IR/PassManager.h.
getResult()
template<typename DerivedT, typename IRUnitT> template<typename PassT> PassT::Result & llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::getResult (IRUnitT & IR) inline
Get the result of an analysis pass for this module.
If there is not a valid cached result in the manager already, this will re-run the analysis to produce a valid result.
Definition at line 310 of file IR/PassManager.h.
Referenced by llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::run(), llvm::DominatorTreePrinterPass::run(), llvm::DominatorTreeVerifierPass::run(), llvm::LazyCallGraphPrinterPass::run(), llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::run(), and llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::run().
invalidate() [1/2]
template<typename DerivedT, typename IRUnitT> template<typename PassT> void llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::invalidate (IRUnitT & IR) inline
Invalidate a specific analysis pass for an IR module.
Note that the analysis result can disregard invalidation.
Definition at line 356 of file IR/PassManager.h.
Referenced by llvm::CGSCCToFunctionPassAdaptor< FunctionPassT >::run(), llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::run(), and llvm::ModuleToPostOrderCGSCCPassAdaptor< CGSCCPassT >::run().
invalidate() [2/2]
template<typename DerivedT, typename IRUnitT> PreservedAnalyses llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::invalidate (IRUnitT & IR, PreservedAnalyses PA) inline
Invalidate analyses cached for an IR unit.
Walk through all of the analyses pertaining to this unit of IR and invalidate them unless they are preserved by the PreservedAnalyses set. We accept the PreservedAnalyses set by value and update it with each analyis pass which has been successfully invalidated and thus can be preserved going forward. The updated set is returned.
Definition at line 369 of file IR/PassManager.h.
lookupPass() [1/2]
template<typename DerivedT, typename IRUnitT> PassConceptT & llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::lookupPass (void * PassID) inline protected
Lookup a registered analysis pass.
Definition at line 375 of file IR/PassManager.h.
lookupPass() [2/2]
template<typename DerivedT, typename IRUnitT> const PassConceptT & llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::lookupPass (void * PassID) const inline protected
Lookup a registered analysis pass.
Definition at line 383 of file IR/PassManager.h.
operator=()
template<typename DerivedT, typename IRUnitT> AnalysisManagerBase & llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::operator= (AnalysisManagerBase< DerivedT, IRUnitT > && RHS) inline protected
Definition at line 300 of file IR/PassManager.h.
registerPass()
template<typename DerivedT, typename IRUnitT> template<typename PassT> void llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::registerPass (PassT Pass) inline
Register an analysis pass with the manager.
This provides an initialized and set-up analysis pass to the analysis manager. Whomever is setting up analysis passes must use this to populate the manager with all of the analysis passes available.
Definition at line 346 of file IR/PassManager.h.
The documentation for this class was generated from the following file:
IR/PassManager.h