LLVM: llvm::SpecialCaseList Class Reference
LLVM API Documentation
llvm::SpecialCaseList Class Reference
#include <SpecialCaseList.h>
Classes
struct Entry
Public Member Functions
~SpecialCaseList ()
bool inSection (StringRef Section, StringRef Query, StringRef Category=StringRef()) const
Static Public Member Functions
static std::unique_ptr< SpecialCaseList > create (StringRef Path, std::string &Error)
static std::unique_ptr< SpecialCaseList > create (const MemoryBuffer *MB, std::string &Error)
static std::unique_ptr< SpecialCaseList > createOrDie (StringRef Path)
Detailed Description
Definition at line 58 of file SpecialCaseList.h.
Constructor & Destructor Documentation
~SpecialCaseList()
llvm::SpecialCaseList::~SpecialCaseList ()
Definition at line 146 of file SpecialCaseList.cpp.
Member Function Documentation
create() [1/2]
std::unique_ptr< SpecialCaseList > llvm::SpecialCaseList::create (const MemoryBuffer * MB, std::string & Error) static
Parses the special case list from a memory buffer. On failure, returns 0 and writes an error message to string.
Definition at line 64 of file SpecialCaseList.cpp.
References Error().
create() [2/2]
std::unique_ptr< SpecialCaseList > llvm::SpecialCaseList::create (StringRef Path, std::string & Error) static
Parses the special case list from a file. If Path is empty, returns an empty special case list. On failure, returns 0 and writes an error message to string.
Definition at line 51 of file SpecialCaseList.cpp.
References create(), llvm::StringRef::empty(), Error(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), and llvm::MemoryBuffer::getFile().
Referenced by create(), and createOrDie().
createOrDie()
std::unique_ptr< SpecialCaseList > llvm::SpecialCaseList::createOrDie (StringRef Path) static
Parses the special case list from a file. On failure, reports a fatal error.
Definition at line 72 of file SpecialCaseList.cpp.
References create(), Error(), and llvm::report_fatal_error().
inSection()
bool llvm::SpecialCaseList::inSection (StringRef Section, StringRef Query, StringRef Category = StringRef()) const
Returns true, if special case list contains a line
@Section:<E>=@Category
and @Query satisfies a wildcard expression <E>.
Definition at line 148 of file SpecialCaseList.cpp.
References llvm::StringMapEntry< ValueTy >::getValue(), and I.
The documentation for this class was generated from the following files:
SpecialCaseList.h
SpecialCaseList.cpp