LLVM: llvm::ContextualFoldingSet< T, Ctx > Class Template Reference
LLVM API Documentation
llvm::ContextualFoldingSet< T, Ctx > Class Template Reference
#include <FoldingSet.h>
Public Types
typedef FoldingSetIterator< T > iterator
typedef FoldingSetIterator< const T > const_iterator
typedef FoldingSetBucketIterator< T > bucket_iterator
Public Member Functions
ContextualFoldingSet (Ctx Context, unsigned Log2InitSize=6)
Ctx getContext () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bucket_iterator bucket_begin (unsigned hash)
bucket_iterator bucket_end (unsigned hash)
T * GetOrInsertNode (Node *N)
T * FindNodeOrInsertPos (const FoldingSetNodeID &ID, void *&InsertPos)
Public Member Functions inherited from llvm::FoldingSetImpl
FoldingSetImpl (unsigned Log2InitSize=6)
virtual ~FoldingSetImpl ()
void clear ()
clear - Remove all nodes from the folding set.
bool RemoveNode (Node *N)
Node * GetOrInsertNode (Node *N)
Node * FindNodeOrInsertPos (const FoldingSetNodeID &ID, void *&InsertPos)
void InsertNode (Node *N, void *InsertPos)
void InsertNode (Node *N)
unsigned size () const
size - Returns the number of nodes in the folding set.
bool empty () const
empty - Returns true if there are no nodes in the folding set.
Additional Inherited Members
Protected Attributes inherited from llvm::FoldingSetImpl
void ** Buckets
unsigned NumBuckets
unsigned NumNodes
Detailed Description
template<class T, class Ctx>
class llvm::ContextualFoldingSet< T, Ctx >
ContextualFoldingSet - This template class is a further refinement of FoldingSet which provides a context argument when calling Profile on its nodes. Currently, that argument is fixed at initialization time.
T must be a subclass of FoldingSetNode and implement a Profile function with signature void Profile(llvm::FoldingSetNodeID &, Ctx);
Definition at line 465 of file FoldingSet.h.
Member Typedef Documentation
bucket_iterator
template<class T, class Ctx> typedef FoldingSetBucketIterator<T> llvm::ContextualFoldingSet< T, Ctx >::bucket_iterator
Definition at line 509 of file FoldingSet.h.
const_iterator
template<class T, class Ctx> typedef FoldingSetIterator<const T> llvm::ContextualFoldingSet< T, Ctx >::const_iterator
Definition at line 505 of file FoldingSet.h.
iterator
template<class T, class Ctx> typedef FoldingSetIterator<T> llvm::ContextualFoldingSet< T, Ctx >::iterator
Definition at line 501 of file FoldingSet.h.
Constructor & Destructor Documentation
ContextualFoldingSet()
template<class T, class Ctx> llvm::ContextualFoldingSet< T, Ctx >::ContextualFoldingSet (Ctx Context, unsigned Log2InitSize = 6) inline explicit
Definition at line 494 of file FoldingSet.h.
References llvm::FoldingSetImpl::FoldingSetImpl().
Member Function Documentation
begin() [1/2]
template<class T, class Ctx> iterator llvm::ContextualFoldingSet< T, Ctx >::begin () inline
Definition at line 502 of file FoldingSet.h.
References llvm::FoldingSetImpl::Buckets.
begin() [2/2]
template<class T, class Ctx> const_iterator llvm::ContextualFoldingSet< T, Ctx >::begin () const inline
Definition at line 506 of file FoldingSet.h.
References llvm::FoldingSetImpl::Buckets.
bucket_begin()
template<class T, class Ctx> bucket_iterator llvm::ContextualFoldingSet< T, Ctx >::bucket_begin (unsigned hash) inline
Definition at line 511 of file FoldingSet.h.
References llvm::FoldingSetImpl::Buckets, and llvm::FoldingSetImpl::NumBuckets.
bucket_end()
template<class T, class Ctx> bucket_iterator llvm::ContextualFoldingSet< T, Ctx >::bucket_end (unsigned hash) inline
Definition at line 515 of file FoldingSet.h.
References llvm::FoldingSetImpl::Buckets, and llvm::FoldingSetImpl::NumBuckets.
end() [1/2]
template<class T, class Ctx> iterator llvm::ContextualFoldingSet< T, Ctx >::end () inline
Definition at line 503 of file FoldingSet.h.
References llvm::FoldingSetImpl::Buckets, and llvm::FoldingSetImpl::NumBuckets.
end() [2/2]
template<class T, class Ctx> const_iterator llvm::ContextualFoldingSet< T, Ctx >::end () const inline
Definition at line 507 of file FoldingSet.h.
References llvm::FoldingSetImpl::Buckets, and llvm::FoldingSetImpl::NumBuckets.
FindNodeOrInsertPos()
template<class T, class Ctx> T * llvm::ContextualFoldingSet< T, Ctx >::FindNodeOrInsertPos (const FoldingSetNodeID & ID, void *& InsertPos) inline
FindNodeOrInsertPos - Look up the node specified by ID. If it exists, return it. If not, return the insertion token that will make insertion faster.
Definition at line 529 of file FoldingSet.h.
References llvm::FoldingSetImpl::FindNodeOrInsertPos(), and T.
getContext()
template<class T, class Ctx> Ctx llvm::ContextualFoldingSet< T, Ctx >::getContext () const inline
Definition at line 498 of file FoldingSet.h.
GetOrInsertNode()
template<class T, class Ctx> T * llvm::ContextualFoldingSet< T, Ctx >::GetOrInsertNode (Node * N) inline
GetOrInsertNode - If there is an existing simple Node exactly equal to the specified node, return it. Otherwise, insert 'N' and return it instead.
Definition at line 522 of file FoldingSet.h.
References llvm::FoldingSetImpl::GetOrInsertNode(), N, and T.
The documentation for this class was generated from the following file:
FoldingSet.h