LLVM: llvm::NVPTXSubtarget Class Reference
LLVM API Documentation
llvm::NVPTXSubtarget Class Reference
#include <NVPTXSubtarget.h>
Public Member Functions
NVPTXSubtarget (const std::string &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM, bool is64Bit)
const TargetFrameLowering * getFrameLowering () const override
const NVPTXInstrInfo * getInstrInfo () const override
const DataLayout * getDataLayout () const override
const NVPTXRegisterInfo * getRegisterInfo () const override
const NVPTXTargetLowering * getTargetLowering () const override
const TargetSelectionDAGInfo * getSelectionDAGInfo () const override
bool hasBrkPt () const
bool hasAtomRedG32 () const
bool hasAtomRedS32 () const
bool hasAtomRedG64 () const
bool hasAtomRedS64 () const
bool hasAtomRedGen32 () const
bool hasAtomRedGen64 () const
bool hasAtomAddF32 () const
bool hasVote () const
bool hasDouble () const
bool reqPTX20 () const
bool hasF32FTZ () const
bool hasFMAF32 () const
bool hasFMAF64 () const
bool hasLDG () const
bool hasLDU () const
bool hasGenericLdSt () const
bool hasHWROT32 () const
bool hasSWROT32 () const
bool hasROT32 () const
bool hasROT64 () const
bool hasImageHandles () const
bool is64Bit () const
unsigned int getSmVersion () const
NVPTX::DrvInterface getDrvInterface () const
std::string getTargetName () const
unsigned getPTXVersion () const
NVPTXSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
Detailed Description
Definition at line 32 of file NVPTXSubtarget.h.
Constructor & Destructor Documentation
NVPTXSubtarget()
NVPTXSubtarget::NVPTXSubtarget (const std::string & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM, bool is64Bit)
This constructor initializes the data members to match that of the specified module.
Definition at line 56 of file NVPTXSubtarget.cpp.
References computeDataLayout(), const, llvm::NVPTX::CUDA, initializeSubtargetDependencies(), is64Bit(), llvm::NVPTX::NVCL, llvm::Triple::NVCL, and T.
Referenced by initializeSubtargetDependencies().
Member Function Documentation
getDataLayout()
const DataLayout * llvm::NVPTXSubtarget::getDataLayout () const inline override
Definition at line 64 of file NVPTXSubtarget.h.
getDrvInterface()
NVPTX::DrvInterface llvm::NVPTXSubtarget::getDrvInterface () const inline
Definition at line 111 of file NVPTXSubtarget.h.
Referenced by hasImageHandles().
getFrameLowering()
const TargetFrameLowering * llvm::NVPTXSubtarget::getFrameLowering () const inline override
Definition at line 60 of file NVPTXSubtarget.h.
getInstrInfo()
const NVPTXInstrInfo * llvm::NVPTXSubtarget::getInstrInfo () const inline override
Definition at line 63 of file NVPTXSubtarget.h.
getPTXVersion()
unsigned llvm::NVPTXSubtarget::getPTXVersion () const inline
Definition at line 114 of file NVPTXSubtarget.h.
getRegisterInfo()
const NVPTXRegisterInfo * llvm::NVPTXSubtarget::getRegisterInfo () const inline override
Definition at line 65 of file NVPTXSubtarget.h.
getSelectionDAGInfo()
const TargetSelectionDAGInfo * llvm::NVPTXSubtarget::getSelectionDAGInfo () const inline override
Definition at line 71 of file NVPTXSubtarget.h.
getSmVersion()
unsigned int llvm::NVPTXSubtarget::getSmVersion () const inline
Definition at line 110 of file NVPTXSubtarget.h.
getTargetLowering()
const NVPTXTargetLowering * llvm::NVPTXSubtarget::getTargetLowering () const inline override
Definition at line 68 of file NVPTXSubtarget.h.
getTargetName()
std::string llvm::NVPTXSubtarget::getTargetName () const inline
Definition at line 112 of file NVPTXSubtarget.h.
hasAtomAddF32()
bool llvm::NVPTXSubtarget::hasAtomAddF32 () const inline
Definition at line 82 of file NVPTXSubtarget.h.
hasAtomRedG32()
bool llvm::NVPTXSubtarget::hasAtomRedG32 () const inline
Definition at line 76 of file NVPTXSubtarget.h.
hasAtomRedG64()
bool llvm::NVPTXSubtarget::hasAtomRedG64 () const inline
Definition at line 78 of file NVPTXSubtarget.h.
hasAtomRedGen32()
bool llvm::NVPTXSubtarget::hasAtomRedGen32 () const inline
Definition at line 80 of file NVPTXSubtarget.h.
hasAtomRedGen64()
bool llvm::NVPTXSubtarget::hasAtomRedGen64 () const inline
Definition at line 81 of file NVPTXSubtarget.h.
hasAtomRedS32()
bool llvm::NVPTXSubtarget::hasAtomRedS32 () const inline
Definition at line 77 of file NVPTXSubtarget.h.
hasAtomRedS64()
bool llvm::NVPTXSubtarget::hasAtomRedS64 () const inline
Definition at line 79 of file NVPTXSubtarget.h.
hasBrkPt()
bool llvm::NVPTXSubtarget::hasBrkPt () const inline
Definition at line 75 of file NVPTXSubtarget.h.
hasDouble()
bool llvm::NVPTXSubtarget::hasDouble () const inline
Definition at line 84 of file NVPTXSubtarget.h.
hasF32FTZ()
bool llvm::NVPTXSubtarget::hasF32FTZ () const inline
Definition at line 86 of file NVPTXSubtarget.h.
hasFMAF32()
bool llvm::NVPTXSubtarget::hasFMAF32 () const inline
Definition at line 87 of file NVPTXSubtarget.h.
hasFMAF64()
bool llvm::NVPTXSubtarget::hasFMAF64 () const inline
Definition at line 88 of file NVPTXSubtarget.h.
hasGenericLdSt()
bool llvm::NVPTXSubtarget::hasGenericLdSt () const inline
Definition at line 91 of file NVPTXSubtarget.h.
hasHWROT32()
bool llvm::NVPTXSubtarget::hasHWROT32 () const inline
Definition at line 92 of file NVPTXSubtarget.h.
Referenced by hasROT32().
hasImageHandles()
bool llvm::NVPTXSubtarget::hasImageHandles () const inline
Definition at line 99 of file NVPTXSubtarget.h.
References llvm::NVPTX::CUDA, and getDrvInterface().
hasLDG()
bool llvm::NVPTXSubtarget::hasLDG () const inline
Definition at line 89 of file NVPTXSubtarget.h.
hasLDU()
bool llvm::NVPTXSubtarget::hasLDU () const inline
Definition at line 90 of file NVPTXSubtarget.h.
hasROT32()
bool llvm::NVPTXSubtarget::hasROT32 () const inline
Definition at line 96 of file NVPTXSubtarget.h.
References hasHWROT32(), and hasSWROT32().
hasROT64()
bool llvm::NVPTXSubtarget::hasROT64 () const inline
Definition at line 97 of file NVPTXSubtarget.h.
hasSWROT32()
bool llvm::NVPTXSubtarget::hasSWROT32 () const inline
Definition at line 93 of file NVPTXSubtarget.h.
Referenced by hasROT32().
hasVote()
bool llvm::NVPTXSubtarget::hasVote () const inline
Definition at line 83 of file NVPTXSubtarget.h.
initializeSubtargetDependencies()
NVPTXSubtarget & NVPTXSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 39 of file NVPTXSubtarget.cpp.
References llvm::StringRef::empty(), llvm_unreachable, NVPTXSubtarget(), ParseSubtargetFeatures(), and llvm::StringRef::size().
Referenced by NVPTXSubtarget().
is64Bit()
bool llvm::NVPTXSubtarget::is64Bit () const inline
Definition at line 108 of file NVPTXSubtarget.h.
Referenced by NVPTXSubtarget().
ParseSubtargetFeatures()
void llvm::NVPTXSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
Referenced by initializeSubtargetDependencies().
reqPTX20()
bool llvm::NVPTXSubtarget::reqPTX20 () const inline
Definition at line 85 of file NVPTXSubtarget.h.
The documentation for this class was generated from the following files:
NVPTXSubtarget.h
NVPTXSubtarget.cpp