LLVM: llvm::DwarfExpression Class Reference
LLVM API Documentation
llvm::DwarfExpression Class Reference abstract
#include <DwarfExpression.h>
Public Member Functions
DwarfExpression (const AsmPrinter &AP)
virtual ~DwarfExpression ()
virtual void EmitOp (uint8_t Op, const char *Comment=nullptr)=0
Output a dwarf operand and an optional assembler comment.
virtual void EmitSigned (int Value)=0
Emit a raw signed value.
virtual void EmitUnsigned (unsigned Value)=0
Emit a raw unsigned value.
virtual bool isFrameRegister (unsigned MachineReg)=0
void AddReg (int DwarfReg, const char *Comment=nullptr)
Emit a dwarf register operation.
void AddRegIndirect (int DwarfReg, int Offset, bool Deref=false)
Emit an (double-)indirect dwarf register operation.
void AddOpPiece (unsigned SizeInBits, unsigned OffsetInBits=0)
void AddShr (unsigned ShiftBy)
Emit a shift-right dwarf expression.
bool AddMachineRegIndirect (unsigned MachineReg, int Offset=0)
bool AddMachineRegPiece (unsigned MachineReg, unsigned PieceSizeInBits=0, unsigned PieceOffsetInBits=0)
Emit a partial DWARF register operation.
void AddSignedConstant (int Value)
Emit a signed constant.
void AddUnsignedConstant (unsigned Value)
Emit an unsigned constant.
bool AddMachineRegExpression (DIExpression Expr, unsigned MachineReg, unsigned PieceOffsetInBits=0)
void AddExpression (DIExpression Expr, unsigned PieceOffsetInBits=0, unsigned I=0)
Protected Member Functions
const TargetRegisterInfo * getTRI () const
unsigned getDwarfVersion () const
Protected Attributes
const AsmPrinter & AP
Detailed Description
Base class containing the logic for constructing DWARF expressions independently of whether they are emitted into a DIE or into a .debug_loc entry.
Definition at line 31 of file DwarfExpression.h.
Constructor & Destructor Documentation
DwarfExpression()
llvm::DwarfExpression::DwarfExpression (const AsmPrinter & AP) inline
Definition at line 39 of file DwarfExpression.h.
References AP.
Referenced by llvm::DebugLocDwarfExpression::DebugLocDwarfExpression(), and llvm::DIEDwarfExpression::DIEDwarfExpression().
~DwarfExpression()
virtual llvm::DwarfExpression::~DwarfExpression () inline virtual
Definition at line 40 of file DwarfExpression.h.
Member Function Documentation
AddExpression()
void DwarfExpression::AddExpression (DIExpression Expr, unsigned PieceOffsetInBits = 0, unsigned I = 0)
Emit a the operations in a DIExpression, starting from element I.
Parameters
PieceOffsetInBits If this is one piece out of a fragmented location, this is the offset of the piece inside the entire variable.
Definition at line 237 of file DwarfExpression.cpp.
References AddOpPiece(), llvm::dwarf::DW_OP_deref, llvm::dwarf::DW_OP_piece, llvm::dwarf::DW_OP_plus, llvm::dwarf::DW_OP_plus_uconst, EmitOp(), EmitUnsigned(), llvm::DIExpression::getElement(), llvm::DIExpression::getNumElements(), getOffsetOrZero(), I, llvm_unreachable, and N.
Referenced by llvm::DwarfCompileUnit::addComplexAddress(), AddMachineRegExpression(), and llvm::DwarfDebug::emitDebugLocValue().
AddMachineRegExpression()
bool DwarfExpression::AddMachineRegExpression (DIExpression Expr, unsigned MachineReg, unsigned PieceOffsetInBits = 0)
Emit an entire DIExpression on top of a machine register location.
Parameters
PieceOffsetInBits If this is one piece out of a fragmented location, this is the offset of the piece inside the entire variable.
Returns
false if no DWARF register exists for MachineReg.
Definition at line 200 of file DwarfExpression.cpp.
References AddExpression(), AddMachineRegIndirect(), AddMachineRegPiece(), llvm::dwarf::DW_OP_deref, llvm::dwarf::DW_OP_piece, llvm::dwarf::DW_OP_plus, llvm::DIExpression::getElement(), llvm::DIExpression::getNumElements(), getOffsetOrZero(), I, and N.
Referenced by llvm::DwarfCompileUnit::addComplexAddress(), and llvm::DwarfDebug::emitDebugLocValue().
AddMachineRegIndirect()
bool DwarfExpression::AddMachineRegIndirect (unsigned MachineReg, int Offset = 0)
Emit an indirect dwarf register operation for the given machine register.
Returns
false if no DWARF register exists for MachineReg.
Definition at line 76 of file DwarfExpression.cpp.
References AddRegIndirect(), llvm::dwarf::DW_OP_fbreg, EmitOp(), EmitSigned(), llvm::MCRegisterInfo::getDwarfRegNum(), getTRI(), and isFrameRegister().
Referenced by llvm::DwarfCompileUnit::addComplexAddress(), AddMachineRegExpression(), llvm::DwarfUnit::addRegisterOffset(), and llvm::DwarfDebug::emitDebugLocValue().
AddMachineRegPiece()
bool DwarfExpression::AddMachineRegPiece (unsigned MachineReg, unsigned PieceSizeInBits = 0, unsigned PieceOffsetInBits = 0)
Emit a partial DWARF register operation.
Parameters
MachineReg the register
PieceSizeInBits size and
PieceOffsetInBits offset of the piece in bits, if this is one piece of an aggregate value.
If size and offset is zero an operation for the entire register is emitted: Some targets do not provide a DWARF register number for every register. If this is the case, this function will attempt to emit a DWARF register by emitting a piece of a super-register or by piecing together multiple subregisters that alias the register.
Returns
false if no DWARF register exists for MachineReg.
Definition at line 91 of file DwarfExpression.cpp.
References AddOpPiece(), AddReg(), AddShr(), llvm::SmallBitVector::any(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::TargetRegisterClass::getSize(), llvm::MCRegisterInfo::getSubRegIdxOffset(), llvm::MCRegisterInfo::getSubRegIdxSize(), llvm::MCRegisterInfo::getSubRegIndex(), getTRI(), llvm::MCRegisterInfo::DiffListIterator::isValid(), and llvm::SmallBitVector::set().
Referenced by AddMachineRegExpression(), llvm::DwarfUnit::addRegisterOpPiece(), llvm::AsmPrinter::EmitDwarfRegOp(), and llvm::AsmPrinter::EmitDwarfRegOpPiece().
AddOpPiece()
void DwarfExpression::AddOpPiece (unsigned SizeInBits, unsigned OffsetInBits = 0)
Emit a dwarf register operation for describing
a small value occupying only part of a register or
a register representing only part of a value.
Definition at line 56 of file DwarfExpression.cpp.
References llvm::dwarf::DW_OP_bit_piece, llvm::dwarf::DW_OP_piece, EmitOp(), and EmitUnsigned().
Referenced by AddExpression(), AddMachineRegPiece(), and llvm::AsmPrinter::EmitDwarfOpPiece().
AddReg()
void DwarfExpression::AddReg (int DwarfReg, const char * Comment = nullptr)
Emit a dwarf register operation.
Definition at line 33 of file DwarfExpression.cpp.
References llvm::dwarf::DW_OP_reg0, llvm::dwarf::DW_OP_regx, EmitOp(), and EmitUnsigned().
Referenced by AddMachineRegPiece(), and llvm::AsmPrinter::EmitDwarfRegOp().
AddRegIndirect()
void DwarfExpression::AddRegIndirect (int DwarfReg, int Offset, bool Deref = false)
Emit an (double-)indirect dwarf register operation.
Definition at line 43 of file DwarfExpression.cpp.
References llvm::dwarf::DW_OP_breg0, llvm::dwarf::DW_OP_bregx, llvm::dwarf::DW_OP_deref, EmitOp(), EmitSigned(), and EmitUnsigned().
Referenced by AddMachineRegIndirect(), and llvm::AsmPrinter::EmitDwarfRegOp().
AddShr()
void DwarfExpression::AddShr (unsigned ShiftBy)
Emit a shift-right dwarf expression.
Definition at line 70 of file DwarfExpression.cpp.
References llvm::dwarf::DW_OP_constu, llvm::dwarf::DW_OP_shr, EmitOp(), and EmitUnsigned().
Referenced by AddMachineRegPiece().
AddSignedConstant()
void DwarfExpression::AddSignedConstant (int Value)
Emit a signed constant.
Definition at line 167 of file DwarfExpression.cpp.
References llvm::dwarf::DW_OP_consts, llvm::dwarf::DW_OP_stack_value, EmitOp(), EmitSigned(), and getDwarfVersion().
Referenced by llvm::DwarfDebug::emitDebugLocValue().
AddUnsignedConstant()
void DwarfExpression::AddUnsignedConstant (unsigned Value)
Emit an unsigned constant.
Definition at line 184 of file DwarfExpression.cpp.
References llvm::dwarf::DW_OP_constu, llvm::dwarf::DW_OP_stack_value, EmitOp(), EmitUnsigned(), and getDwarfVersion().
Referenced by llvm::DwarfDebug::emitDebugLocValue().
EmitOp()
virtual void llvm::DwarfExpression::EmitOp (uint8_t Op, const char * Comment = nullptr) pure virtual
Output a dwarf operand and an optional assembler comment.
Implemented in llvm::DebugLocDwarfExpression, and llvm::DIEDwarfExpression.
Referenced by AddExpression(), AddMachineRegIndirect(), AddOpPiece(), AddReg(), AddRegIndirect(), AddShr(), AddSignedConstant(), and AddUnsignedConstant().
EmitSigned()
virtual void llvm::DwarfExpression::EmitSigned (int Value) pure virtual
Emit a raw signed value.
Implemented in llvm::DebugLocDwarfExpression, and llvm::DIEDwarfExpression.
Referenced by AddMachineRegIndirect(), AddRegIndirect(), and AddSignedConstant().
EmitUnsigned()
virtual void llvm::DwarfExpression::EmitUnsigned (unsigned Value) pure virtual
Emit a raw unsigned value.
Implemented in llvm::DebugLocDwarfExpression, and llvm::DIEDwarfExpression.
Referenced by AddExpression(), AddOpPiece(), AddReg(), AddRegIndirect(), AddShr(), and AddUnsignedConstant().
getDwarfVersion()
unsigned DwarfExpression::getDwarfVersion () const protected
Definition at line 29 of file DwarfExpression.cpp.
References AP.
Referenced by AddSignedConstant(), and AddUnsignedConstant().
getTRI()
const TargetRegisterInfo * DwarfExpression::getTRI () const protected
Definition at line 25 of file DwarfExpression.cpp.
References AP.
Referenced by AddMachineRegIndirect(), AddMachineRegPiece(), and llvm::DIEDwarfExpression::isFrameRegister().
isFrameRegister()
virtual bool llvm::DwarfExpression::isFrameRegister (unsigned MachineReg) pure virtual
Return whether the given machine register is the frame register in the current function.
Implemented in llvm::DebugLocDwarfExpression, and llvm::DIEDwarfExpression.
References I.
Referenced by AddMachineRegIndirect().
Member Data Documentation
AP
const AsmPrinter& llvm::DwarfExpression::AP protected
Definition at line 33 of file DwarfExpression.h.
Referenced by llvm::DebugLocDwarfExpression::DebugLocDwarfExpression(), llvm::DIEDwarfExpression::DIEDwarfExpression(), DwarfExpression(), getDwarfVersion(), getTRI(), and llvm::DIEDwarfExpression::isFrameRegister().
The documentation for this class was generated from the following files:
DwarfExpression.h
DwarfExpression.cpp