LLVM: llvm::yaml::MappingNode Class Reference
LLVM API Documentation
llvm::yaml::MappingNode Class Reference
Represents a YAML map created from either a block map for a flow map.
#include <YAMLParser.h>
Public Types
enum MappingType { MT_Block , MT_Flow , MT_Inline }
typedef basic_collection_iterator< MappingNode, KeyValueNode > iterator
Public Types inherited from llvm::yaml::Node
enum NodeKind {
NK_Null , NK_Scalar , NK_KeyValue , NK_Mapping ,
NK_Sequence , NK_Alias
}
Public Member Functions
MappingNode (std::unique_ptr< Document > &D, StringRef Anchor, StringRef Tag, MappingType MT)
iterator begin ()
iterator end ()
void skip () override
Public Member Functions inherited from llvm::yaml::Node
Node (unsigned int Type, std::unique_ptr< Document > &, StringRef Anchor, StringRef Tag)
StringRef getAnchor () const
Get the value of the anchor attached to this node. If it does not have one, getAnchor().size() will be 0.
StringRef getRawTag () const
Get the tag as it was written in the document. This does not perform tag resolution.
std::string getVerbatimTag () const
Get the verbatium tag for a given Node. This performs tag resoluton and substitution.
SMRange getSourceRange () const
void setSourceRange (SMRange SR)
Token & peekNext ()
Token getNext ()
Node * parseBlockNode ()
BumpPtrAllocator & getAllocator ()
void setError (const Twine &Message, Token &Location) const
bool failed () const
unsigned int getType () const
void * operator new (size_t Size, BumpPtrAllocator &Alloc, size_t Alignment=16) throw ()
void operator delete (void *Ptr, BumpPtrAllocator &Alloc, size_t Size) throw ()
Static Public Member Functions
static bool classof (const Node *N)
Friends
class basic_collection_iterator< MappingNode, KeyValueNode >
template<class T>
T::iterator yaml::begin (T &)
template<class T>
void yaml::skip (T &)
Additional Inherited Members
Protected Member Functions inherited from llvm::yaml::Node
void operator delete (void *) throw ()
virtual ~Node ()
Protected Attributes inherited from llvm::yaml::Node
std::unique_ptr< Document > & Doc
SMRange SourceRange
Detailed Description
Represents a YAML map created from either a block map for a flow map.
This parses the YAML stream as increment() is called.
Example: Name: _main Scope: Global
Definition at line 343 of file YAMLParser.h.
Member Typedef Documentation
iterator
typedef basic_collection_iterator<MappingNode, KeyValueNode> llvm::yaml::MappingNode::iterator
Definition at line 359 of file YAMLParser.h.
Member Enumeration Documentation
MappingType
enum llvm::yaml::MappingNode::MappingType
Enumerator
MT_Block
MT_Flow
MT_Inline
An inline mapping node is used for "[key: value]".
Definition at line 347 of file YAMLParser.h.
Constructor & Destructor Documentation
MappingNode()
llvm::yaml::MappingNode::MappingNode (std::unique_ptr< Document > & D, StringRef Anchor, StringRef Tag, MappingType MT) inline
Definition at line 353 of file YAMLParser.h.
Member Function Documentation
begin()
iterator llvm::yaml::MappingNode::begin () inline
Definition at line 363 of file YAMLParser.h.
References llvm::yaml::begin().
classof()
bool llvm::yaml::MappingNode::classof (const Node * N) inline static
Definition at line 369 of file YAMLParser.h.
References N, llvm::yaml::Node::NK_Mapping, and llvm::yaml::Node::Node().
end()
iterator llvm::yaml::MappingNode::end () inline
Definition at line 365 of file YAMLParser.h.
skip()
void llvm::yaml::MappingNode::skip () inline override virtual
Reimplemented from llvm::yaml::Node.
Definition at line 367 of file YAMLParser.h.
References llvm::yaml::skip().
Friends And Related Symbol Documentation
basic_collection_iterator< MappingNode, KeyValueNode >
friend class basic_collection_iterator< MappingNode, KeyValueNode > friend
Definition at line 353 of file YAMLParser.h.
References llvm::yaml::Node::NK_Mapping, llvm::yaml::Node::Node(), and true.
yaml::begin
template<class T> T::iterator yaml::begin (T &) friend
References T.
yaml::skip
template<class T> void yaml::skip (T &) friend
References T.
The documentation for this class was generated from the following files:
YAMLParser.h
YAMLParser.cpp