LLVM: llvm::ilist_node< NodeTy > Class Template Reference
LLVM API Documentation
llvm::ilist_node< NodeTy > Class Template Reference
#include <ilist_node.h>
Public Member Functions
Adjacent Node Accessors
NodeTy * getPrevNode ()
Get the previous node, or 0 for the list head.
const NodeTy * getPrevNode () const
Get the previous node, or 0 for the list head.
NodeTy * getNextNode ()
Get the next node, or 0 for the list tail.
const NodeTy * getNextNode () const
Get the next node, or 0 for the list tail.
Protected Member Functions
ilist_node ()
Friends
struct ilist_nextprev_traits< NodeTy >
struct ilist_traits< NodeTy >
Detailed Description
template<typename NodeTy>
class llvm::ilist_node< NodeTy >
ilist_node - Base class that provides next/prev services for nodes that use ilist_nextprev_traits or ilist_default_traits.
Definition at line 43 of file ilist_node.h.
Constructor & Destructor Documentation
ilist_node()
template<typename NodeTy> llvm::ilist_node< NodeTy >::ilist_node () inline protected
Definition at line 51 of file ilist_node.h.
Member Function Documentation
getNextNode() [1/2]
template<typename NodeTy> NodeTy * llvm::ilist_node< NodeTy >::getNextNode () inline
Get the next node, or 0 for the list tail.
Definition at line 80 of file ilist_node.h.
Referenced by llvm::SCEVExpander::replaceCongruentIVs().
getNextNode() [2/2]
template<typename NodeTy> const NodeTy * llvm::ilist_node< NodeTy >::getNextNode () const inline
Get the next node, or 0 for the list tail.
Definition at line 91 of file ilist_node.h.
getPrevNode() [1/2]
template<typename NodeTy> NodeTy * llvm::ilist_node< NodeTy >::getPrevNode () inline
Get the previous node, or 0 for the list head.
Definition at line 58 of file ilist_node.h.
References llvm::ilist_half_node< NodeTy >::getPrev().
Referenced by llvm::BasicBlock::getTerminatingMustTailCall(), and PrevCrossBBInst().
getPrevNode() [2/2]
template<typename NodeTy> const NodeTy * llvm::ilist_node< NodeTy >::getPrevNode () const inline
Get the previous node, or 0 for the list head.
Definition at line 69 of file ilist_node.h.
References llvm::ilist_half_node< NodeTy >::getPrev().
Friends And Related Symbol Documentation
ilist_nextprev_traits< NodeTy >
template<typename NodeTy> friend struct ilist_nextprev_traits< NodeTy > friend
Definition at line 33 of file ilist_node.h.
ilist_traits< NodeTy >
template<typename NodeTy> friend struct ilist_traits< NodeTy > friend
Definition at line 33 of file ilist_node.h.
The documentation for this class was generated from the following file:
ilist_node.h