LLVM: llvm::SCEVNAryExpr Class Reference
LLVM API Documentation
llvm::SCEVNAryExpr Class Reference
#include <ScalarEvolutionExpressions.h>
Public Types
typedef const SCEV *const * op_iterator
typedef iterator_range< op_iterator > op_range
Public Types inherited from llvm::SCEV
enum NoWrapFlags {
FlagAnyWrap = 0 , FlagNW = (1 << 0) , FlagNUW = (1 << 1) , FlagNSW = (1 << 2) ,
NoWrapMask = (1 << 3) -1
}
Public Member Functions
size_t getNumOperands () const
const SCEV * getOperand (unsigned i) const
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
Type * getType () const
NoWrapFlags getNoWrapFlags (NoWrapFlags Mask=NoWrapMask) const
Public Member Functions inherited from llvm::SCEV
SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy)
unsigned getSCEVType () const
Type * getType () const
bool isZero () const
bool isOne () const
bool isAllOnesValue () const
bool isNonConstantNegative () const
void print (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
SCEVNAryExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const *O, size_t N)
Protected Attributes
const SCEV *const * Operands
size_t NumOperands
Protected Attributes inherited from llvm::SCEV
unsigned short SubclassData
Detailed Description
SCEVNAryExpr - This node is a base class providing common functionality for n'ary operators.
Definition at line 134 of file ScalarEvolutionExpressions.h.
Member Typedef Documentation
op_iterator
typedef const SCEV* const* llvm::SCEVNAryExpr::op_iterator
Definition at line 154 of file ScalarEvolutionExpressions.h.
op_range
typedef iterator_range<op_iterator> llvm::SCEVNAryExpr::op_range
Definition at line 155 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVNAryExpr()
llvm::SCEVNAryExpr::SCEVNAryExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const * O, size_t N) inline protected
Definition at line 143 of file ScalarEvolutionExpressions.h.
References N, NumOperands, Operands, and T.
Referenced by llvm::SCEVAddRecExpr::ScalarEvolution, and llvm::SCEVCommutativeExpr::SCEVCommutativeExpr().
Member Function Documentation
classof()
bool llvm::SCEVNAryExpr::classof (const SCEV * S) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 169 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), llvm::scAddExpr, llvm::scAddRecExpr, llvm::scMulExpr, llvm::scSMaxExpr, and llvm::scUMaxExpr.
getNoWrapFlags()
NoWrapFlags llvm::SCEVNAryExpr::getNoWrapFlags (NoWrapFlags Mask = NoWrapMask) const inline
Definition at line 164 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::NoWrapMask, and llvm::SCEV::SubclassData.
Referenced by llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForSignExtend(), isStridedPtr(), llvm::SCEV::print(), llvm::SCEVApplyRewriter::visitAddRecExpr(), and llvm::SCEVParameterRewriter::visitAddRecExpr().
getNumOperands()
size_t llvm::SCEVNAryExpr::getNumOperands () const inline
Definition at line 148 of file ScalarEvolutionExpressions.h.
References NumOperands.
Referenced by BuildConstantFromSCEV(), CollectAddOperandsWithScales(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getAddExpr(), getConstantPart(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForSignExtend(), llvm::SCEVAddExpr::getType(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::SCEVAddRecExpr::isAffine(), isMulSExtable(), llvm::SCEVAddRecExpr::isQuadratic(), MatchNotExpr(), llvm::SCEV::print(), SolveQuadraticEquation(), llvm::SCEVApplyRewriter::visitAddExpr(), llvm::SCEVParameterRewriter::visitAddExpr(), llvm::SCEVApplyRewriter::visitAddRecExpr(), llvm::SCEVParameterRewriter::visitAddRecExpr(), llvm::SCEVApplyRewriter::visitMulExpr(), llvm::SCEVParameterRewriter::visitMulExpr(), llvm::SCEVApplyRewriter::visitSMaxExpr(), llvm::SCEVParameterRewriter::visitSMaxExpr(), llvm::SCEVApplyRewriter::visitUMaxExpr(), and llvm::SCEVParameterRewriter::visitUMaxExpr().
getOperand()
const SCEV * llvm::SCEVNAryExpr::getOperand (unsigned i) const inline
Definition at line 149 of file ScalarEvolutionExpressions.h.
References NumOperands, and Operands.
Referenced by BuildConstantFromSCEV(), CollectAddOperandsWithScales(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getAddExpr(), getConstantPart(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEVAddExpr::getType(), getType(), llvm::ScalarEvolution::getUDivExactExpr(), llvm::SCEV::isNonConstantNegative(), MatchNotExpr(), llvm::SCEV::print(), SolveQuadraticEquation(), llvm::SCEVApplyRewriter::visitAddExpr(), llvm::SCEVParameterRewriter::visitAddExpr(), llvm::SCEVApplyRewriter::visitAddRecExpr(), llvm::SCEVParameterRewriter::visitAddRecExpr(), llvm::SCEVApplyRewriter::visitMulExpr(), llvm::SCEVParameterRewriter::visitMulExpr(), llvm::SCEVApplyRewriter::visitSMaxExpr(), llvm::SCEVParameterRewriter::visitSMaxExpr(), llvm::SCEVApplyRewriter::visitUMaxExpr(), and llvm::SCEVParameterRewriter::visitUMaxExpr().
getType()
Type * llvm::SCEVNAryExpr::getType () const inline
Definition at line 162 of file ScalarEvolutionExpressions.h.
References getOperand(), and llvm::SCEV::getType().
Referenced by canBeCheaplyTransformed(), CollectSubexprs(), llvm::SCEVAddRecExpr::evaluateAtIteration(), FindLoopCounter(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPreStartForSignExtend(), isAddRecSExtable(), isExistingPhi(), and isMulSExtable().
op_begin()
op_iterator llvm::SCEVNAryExpr::op_begin () const inline
Definition at line 156 of file ScalarEvolutionExpressions.h.
References Operands.
Referenced by CollectAddOperandsWithScales(), llvm::ScalarEvolution::getAddExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::ScalarEvolution::getUDivExactExpr(), operands(), llvm::SCEV::print(), and llvm::SCEVTraversal< SV >::visitAll().
op_end()
op_iterator llvm::SCEVNAryExpr::op_end () const inline
Definition at line 157 of file ScalarEvolutionExpressions.h.
References NumOperands, and Operands.
Referenced by CollectAddOperandsWithScales(), llvm::ScalarEvolution::getAddExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::ScalarEvolution::getUDivExactExpr(), operands(), llvm::SCEV::print(), and llvm::SCEVTraversal< SV >::visitAll().
operands()
op_range llvm::SCEVNAryExpr::operands () const inline
Definition at line 158 of file ScalarEvolutionExpressions.h.
References llvm::make_range(), op_begin(), and op_end().
Referenced by getPreStartForSignExtend().
Member Data Documentation
NumOperands
size_t llvm::SCEVNAryExpr::NumOperands protected
Definition at line 141 of file ScalarEvolutionExpressions.h.
Referenced by getNumOperands(), getOperand(), op_end(), and SCEVNAryExpr().
Operands
const SCEV* const* llvm::SCEVNAryExpr::Operands protected
Definition at line 140 of file ScalarEvolutionExpressions.h.
Referenced by llvm::SCEVAddRecExpr::getNumIterationsInRange(), getOperand(), llvm::SCEVAddRecExpr::getStart(), op_begin(), op_end(), and SCEVNAryExpr().
The documentation for this class was generated from the following file:
ScalarEvolutionExpressions.h