LLVM: llvm::po_iterator< GraphT, SetType, ExtStorage, GT > Class Template Reference
LLVM API Documentation
llvm::po_iterator< GraphT, SetType, ExtStorage, GT > Class Template Reference
#include <PostOrderIterator.h>
Public Types
typedef super::pointer pointer
typedef po_iterator< GraphT, SetType, ExtStorage, GT > _Self
Public Member Functions
bool operator== (const _Self &x) const
bool operator!= (const _Self &x) const
pointer operator* () const
NodeType * operator-> () const
_Self & operator++ ()
_Self operator++ (int)
Public Member Functions inherited from llvm::po_iterator_storage< SetType, External >
template<typename NodeType>
bool insertEdge (NodeType *From, NodeType *To)
template<typename NodeType>
void finishPostorder (NodeType *BB)
Static Public Member Functions
static _Self begin (GraphT G)
static _Self end (GraphT G)
static _Self begin (GraphT G, SetType &S)
static _Self end (GraphT G, SetType &S)
Detailed Description
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>>
class llvm::po_iterator< GraphT, SetType, ExtStorage, GT >
Definition at line 92 of file PostOrderIterator.h.
Member Typedef Documentation
_Self
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> typedef po_iterator<GraphT, SetType, ExtStorage, GT> llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::_Self
Definition at line 134 of file PostOrderIterator.h.
pointer
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> typedef super::pointer llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::pointer
Definition at line 133 of file PostOrderIterator.h.
Member Function Documentation
begin() [1/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::begin (GraphT G) inline static
Definition at line 137 of file PostOrderIterator.h.
Referenced by llvm::ipo_begin(), llvm::ipo_ext_begin(), llvm::po_begin(), and llvm::po_ext_begin().
begin() [2/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::begin (GraphT G, SetType & S) inline static
Definition at line 140 of file PostOrderIterator.h.
end() [1/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::end (GraphT G) inline static
Definition at line 138 of file PostOrderIterator.h.
Referenced by llvm::ipo_end(), llvm::ipo_ext_end(), llvm::po_end(), and llvm::po_ext_end().
end() [2/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::end (GraphT G, SetType & S) inline static
Definition at line 143 of file PostOrderIterator.h.
operator!=()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator!= (const _Self & x) const inline
Definition at line 148 of file PostOrderIterator.h.
operator*()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> pointer llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator* () const inline
Definition at line 150 of file PostOrderIterator.h.
Referenced by operator->().
operator++() [1/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self & llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator++ () inline
Definition at line 160 of file PostOrderIterator.h.
operator++() [2/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator++ (int) inline
Definition at line 168 of file PostOrderIterator.h.
operator->()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> NodeType * llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator-> () const inline
Definition at line 158 of file PostOrderIterator.h.
operator==()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator== (const _Self & x) const inline
Definition at line 145 of file PostOrderIterator.h.
Referenced by operator!=().
The documentation for this class was generated from the following file:
PostOrderIterator.h