LLVM: llvm::AttributeSetNode Class Reference
LLVM API Documentation
llvm::AttributeSetNode Class Reference
This class represents a group of attributes that apply to one element: function, return type, or parameter.
#include <AttributeImpl.h>
Public Types
typedef const Attribute * iterator
Public Member Functions
bool hasAttribute (Attribute::AttrKind Kind) const
bool hasAttribute (StringRef Kind) const
bool hasAttributes () const
Attribute getAttribute (Attribute::AttrKind Kind) const
Attribute getAttribute (StringRef Kind) const
unsigned getAlignment () const
unsigned getStackAlignment () const
uint64_t getDereferenceableBytes () const
std::string getAsString (bool InAttrGrp) const
iterator begin () const
iterator end () const
void Profile (FoldingSetNodeID &ID) const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static AttributeSetNode * get (LLVMContext &C, ArrayRef< Attribute > Attrs)
static void Profile (FoldingSetNodeID &ID, ArrayRef< Attribute > AttrList)
Detailed Description
This class represents a group of attributes that apply to one element: function, return type, or parameter.
Definition at line 144 of file AttributeImpl.h.
Member Typedef Documentation
iterator
typedef const Attribute* llvm::AttributeSetNode::iterator
Definition at line 171 of file AttributeImpl.h.
Member Function Documentation
begin()
iterator llvm::AttributeSetNode::begin () const inline
Definition at line 172 of file AttributeImpl.h.
Referenced by end(), getAlignment(), getAsString(), getAttribute(), getAttribute(), getDereferenceableBytes(), getStackAlignment(), hasAttribute(), hasAttribute(), Profile(), and llvm::AttributeSetImpl::Raw().
end()
iterator llvm::AttributeSetNode::end () const inline
Definition at line 173 of file AttributeImpl.h.
References begin().
Referenced by getAlignment(), getAsString(), getAttribute(), getAttribute(), getDereferenceableBytes(), getStackAlignment(), hasAttribute(), hasAttribute(), Profile(), and llvm::AttributeSetImpl::Raw().
get()
AttributeSetNode * AttributeSetNode::get (LLVMContext & C, ArrayRef< Attribute > Attrs) static
Definition at line 439 of file Attributes.cpp.
References llvm::array_pod_sort(), llvm::LLVMContextImpl::AttrsSetNodes, llvm::ArrayRef< T >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, and llvm::SmallVectorTemplateCommon< T, typename >::size().
getAlignment()
unsigned AttributeSetNode::getAlignment () const
Definition at line 501 of file Attributes.cpp.
References llvm::Attribute::Alignment, begin(), end(), and I.
Referenced by llvm::AttributeSet::getParamAlignment(), and llvm::AttributeSetImpl::Raw().
getAsString()
std::string AttributeSetNode::getAsString (bool InAttrGrp) const
Definition at line 522 of file Attributes.cpp.
References begin(), end(), and I.
Referenced by llvm::AttributeSet::getAsString().
getAttribute() [1/2]
Attribute AttributeSetNode::getAttribute (Attribute::AttrKind Kind) const
Definition at line 487 of file Attributes.cpp.
References begin(), end(), and I.
Referenced by llvm::AttributeSet::getAttribute(), and llvm::AttributeSet::getAttribute().
getAttribute() [2/2]
Attribute AttributeSetNode::getAttribute (StringRef Kind) const
Definition at line 494 of file Attributes.cpp.
References begin(), end(), and I.
getDereferenceableBytes()
uint64_t AttributeSetNode::getDereferenceableBytes () const
Definition at line 515 of file Attributes.cpp.
References begin(), llvm::Attribute::Dereferenceable, end(), and I.
Referenced by llvm::AttributeSet::getDereferenceableBytes().
getStackAlignment()
unsigned AttributeSetNode::getStackAlignment () const
Definition at line 508 of file Attributes.cpp.
References begin(), end(), I, and llvm::Attribute::StackAlignment.
Referenced by llvm::AttributeSet::getStackAlignment(), and llvm::AttributeSetImpl::Raw().
hasAttribute() [1/2]
bool AttributeSetNode::hasAttribute (Attribute::AttrKind Kind) const
Definition at line 473 of file Attributes.cpp.
References begin(), end(), and I.
Referenced by llvm::AttributeSet::hasAttribute(), and llvm::AttributeSet::hasAttribute().
hasAttribute() [2/2]
bool AttributeSetNode::hasAttribute (StringRef Kind) const
Definition at line 480 of file Attributes.cpp.
References begin(), end(), and I.
hasAttributes()
bool llvm::AttributeSetNode::hasAttributes () const inline
Definition at line 161 of file AttributeImpl.h.
Referenced by llvm::AttributeSet::hasAttributes().
Profile() [1/2]
void llvm::AttributeSetNode::Profile (FoldingSetNodeID & ID) const inline
Definition at line 175 of file AttributeImpl.h.
References begin(), end(), llvm::makeArrayRef(), and Profile().
Referenced by Profile().
Profile() [2/2]
void llvm::AttributeSetNode::Profile (FoldingSetNodeID & ID, ArrayRef< Attribute > AttrList) inline static
Definition at line 178 of file AttributeImpl.h.
References I, and llvm::ArrayRef< T >::size().
The documentation for this class was generated from the following files:
AttributeImpl.h
Attributes.cpp