LLVM: llvm::StringInit Class Reference
LLVM API Documentation
llvm::StringInit Class Reference
#include <Record.h>
Public Member Functions
const std::string & getValue () const
Init * convertInitializerTo (RecTy *Ty) const override
std::string getAsString () const override
getAsString - Convert this value to a string form.
std::string getAsUnquotedString () const override
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
Init * getBit (unsigned Bit) const override
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const override
Init * convertInitListSlice (const std::vector< unsigned > &Elements) const override
RecTy * getFieldType (const std::string &FieldName) const override
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
void dump () const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * resolveReferences (Record &R, const RecordVal *RV) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static StringInit * get (StringRef)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit , IK_FirstTypedInit , IK_BitsInit , IK_DagInit ,
IK_DefInit , IK_FieldInit , IK_IntInit , IK_ListInit ,
IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit , IK_UnOpInit ,
IK_LastOpInit , IK_StringInit , IK_VarInit , IK_VarListElementInit ,
IK_LastTypedInit , IK_UnsetInit , IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
StringInit - "foo" - Represent an initialization by a string value.
Definition at line 750 of file Record.h.
Member Function Documentation
classof()
bool llvm::StringInit::classof (const Init * I) inline static
Definition at line 761 of file Record.h.
References I, and llvm::Init::IK_StringInit.
convertInitializerTo()
Init * llvm::StringInit::convertInitializerTo (RecTy * Ty) const inline override virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 768 of file Record.h.
get()
StringInit * StringInit::get (StringRef V) static
Definition at line 615 of file Record.cpp.
References I.
Referenced by llvm::Record::addTemplateArg(), llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), llvm::UnOpInit::Fold(), llvm::VarInit::get(), llvm::Record::getValue(), llvm::Record::getValue(), llvm::Record::isTemplateArg(), llvm::QualifyName(), llvm::QualifyName(), llvm::Record::removeValue(), and llvm::Record::setName().
getAsString()
std::string llvm::StringInit::getAsString () const inline override virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 772 of file Record.h.
getAsUnquotedString()
std::string llvm::StringInit::getAsUnquotedString () const inline override virtual
getAsUnquotedString - Convert this value to a string form, without adding quote markers. This primaruly affects StringInits where we will not surround the string value with quotes.
Reimplemented from llvm::Init.
Definition at line 773 of file Record.h.
getBit()
Init * llvm::StringInit::getBit (unsigned Bit) const inline override virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 783 of file Record.h.
References llvm_unreachable.
getValue()
const std::string & llvm::StringInit::getValue () const inline
Definition at line 766 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), llvm::Record::getName(), llvm::RecordVal::getName(), and llvm::VarInit::getName().
resolveListElementReference()
Init * llvm::StringInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const inline override virtual
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences. If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 778 of file Record.h.
References llvm_unreachable.
The documentation for this class was generated from the following files:
Record.h
Record.cpp