LLVM: llvm::BasicBlockPass Class Reference
LLVM API Documentation
llvm::BasicBlockPass Class Reference abstract
#include <Pass.h>
Public Member Functions
BasicBlockPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a basic block printer pass.
virtual bool doInitialization (Function &)
virtual bool runOnBasicBlock (BasicBlock &BB)=0
virtual bool doFinalization (Function &)
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Protected Member Functions
bool skipOptnoneFunction (const BasicBlock &BB) const
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
BasicBlockPass class - This class is used to implement most local optimizations. Optimizations should subclass this class if they meet the following constraints:
Optimizations are local, operating on either a basic block or instruction at a time.
Optimizations do not modify the CFG of the contained function, or any other basic block in the function.
Optimizations conform to all of the constraints of FunctionPasses.
Definition at line 330 of file Pass.h.
Constructor & Destructor Documentation
BasicBlockPass()
llvm::BasicBlockPass::BasicBlockPass (char & pid) inline explicit
Definition at line 332 of file Pass.h.
References llvm::PT_BasicBlock.
Member Function Documentation
assignPassManager()
void BasicBlockPass::assignPassManager (PMStack & PMS, PassManagerType PreferredType) override virtual
Find appropriate Basic Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
Reimplemented from llvm::Pass.
Definition at line 1895 of file LegacyPassManager.cpp.
References llvm::PMTopLevelManager::addIndirectPassManager(), llvm::PMStack::empty(), llvm::PMDataManager::getPassManagerType(), llvm::PMDataManager::getTopLevelManager(), llvm::PMT_BasicBlockPassManager, llvm::PMStack::push(), and llvm::PMStack::top().
createPrinterPass()
Pass * BasicBlockPass::createPrinterPass (raw_ostream & O, const std::string & Banner) const override virtual
createPrinterPass - Get a basic block printer pass.
Implements llvm::Pass.
Definition at line 156 of file Pass.cpp.
References llvm::createPrintBasicBlockPass().
doFinalization() [1/2]
bool BasicBlockPass::doFinalization (Function &) virtual
doFinalization - Virtual method overriden by BasicBlockPass subclasses to do any post processing needed after all passes have run.
Definition at line 166 of file Pass.cpp.
doFinalization() [2/2]
virtual bool llvm::Pass::doFinalization (Module &) inline virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::Pass.
Definition at line 116 of file Pass.h.
doInitialization() [1/2]
bool BasicBlockPass::doInitialization (Function &) virtual
doInitialization - Virtual method overridden by BasicBlockPass subclasses to do any necessary per-function initialization.
Definition at line 161 of file Pass.cpp.
doInitialization() [2/2]
virtual bool llvm::Pass::doInitialization (Module &) inline virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 111 of file Pass.h.
getPotentialPassManagerType()
PassManagerType BasicBlockPass::getPotentialPassManagerType () const override virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented from llvm::Pass.
Definition at line 183 of file Pass.cpp.
References llvm::PMT_BasicBlockPassManager.
runOnBasicBlock()
virtual bool llvm::BasicBlockPass::runOnBasicBlock (BasicBlock & BB) pure virtual
runOnBasicBlock - Virtual method overriden by subclasses to do the per-basicblock processing of the pass.
References T.
skipOptnoneFunction()
bool BasicBlockPass::skipOptnoneFunction (const BasicBlock & BB) const protected
skipOptnoneFunction - Containing function has Attribute::OptimizeNone and most transformation passes should skip it.
Definition at line 171 of file Pass.cpp.
References llvm::dbgs(), DEBUG, F, llvm::BasicBlock::getParent(), llvm::Pass::getPassName(), and llvm::Attribute::OptimizeNone.
The documentation for this class was generated from the following files:
Pass.h
LegacyPassManager.cpp
Pass.cpp