LLVM: llvm::DominatorTreeBase< NodeT > Class Template Reference
LLVM API Documentation
llvm::DominatorTreeBase< NodeT > Class Template Reference
Core dominator tree base class.
#include <GenericDomTree.h>
Classes
struct InfoRec
Public Member Functions
DominatorTreeBase (bool isPostDom)
~DominatorTreeBase ()
DominatorTreeBase (DominatorTreeBase &&Arg)
DominatorTreeBase & operator= (DominatorTreeBase &&RHS)
bool compare (const DominatorTreeBase &Other) const
void releaseMemory ()
DomTreeNodeBase< NodeT > * getNode (NodeT *BB) const
DomTreeNodeBase< NodeT > * operator[] (NodeT *BB) const
DomTreeNodeBase< NodeT > * getRootNode ()
const DomTreeNodeBase< NodeT > * getRootNode () const
void getDescendants (NodeT *R, SmallVectorImpl< NodeT * > &Result) const
Get all nodes dominated by R, including R itself.
bool properlyDominates (const DomTreeNodeBase< NodeT > *A, const DomTreeNodeBase< NodeT > *B) const
bool properlyDominates (const NodeT *A, const NodeT *B) const
bool isReachableFromEntry (const NodeT *A) const
bool isReachableFromEntry (const DomTreeNodeBase< NodeT > *A) const
bool dominates (const DomTreeNodeBase< NodeT > *A, const DomTreeNodeBase< NodeT > *B) const
bool dominates (const NodeT *A, const NodeT *B) const
NodeT * getRoot () const
NodeT * findNearestCommonDominator (NodeT *A, NodeT *B)
const NodeT * findNearestCommonDominator (const NodeT *A, const NodeT *B)
DomTreeNodeBase< NodeT > * addNewBlock (NodeT *BB, NodeT *DomBB)
void changeImmediateDominator (DomTreeNodeBase< NodeT > *N, DomTreeNodeBase< NodeT > *NewIDom)
void changeImmediateDominator (NodeT *BB, NodeT *NewBB)
void eraseNode (NodeT *BB)
void removeNode (NodeT *BB)
void splitBlock (NodeT *NewBB)
void print (raw_ostream &o) const
template<class FT>
void recalculate (FT &F)
recalculate - compute a dominator tree for the given function
Public Member Functions inherited from llvm::DominatorBase< NodeT >
const std::vector< NodeT * > & getRoots () const
bool isPostDominator () const
Protected Types
typedef DenseMap< NodeT *, DomTreeNodeBase< NodeT > * > DomTreeNodeMapType
Protected Member Functions
void reset ()
template<class N, class GraphT>
void Split (DominatorTreeBase< typename GraphT::NodeType > &DT, typename GraphT::NodeType *NewBB)
void updateDFSNumbers () const
DomTreeNodeBase< NodeT > * getNodeForBlock (NodeT *BB)
NodeT * getIDom (NodeT *BB) const
void addRoot (NodeT *BB)
void addRoot (MachineBasicBlock *MBB)
Protected Member Functions inherited from llvm::DominatorBase< NodeT >
DominatorBase (bool isPostDom)
DominatorBase (DominatorBase &&Arg)
DominatorBase & operator= (DominatorBase &&RHS)
Protected Attributes
DomTreeNodeMapType DomTreeNodes
DomTreeNodeBase< NodeT > * RootNode
bool DFSInfoValid
unsigned int SlowQueries
DenseMap< NodeT *, NodeT * > IDoms
std::vector< NodeT * > Vertex
DenseMap< NodeT *, InfoRec > Info
Protected Attributes inherited from llvm::DominatorBase< NodeT >
std::vector< NodeT * > Roots
bool IsPostDominators
Friends
template<class GraphT>
GraphT::NodeType * Eval (DominatorTreeBase< typename GraphT::NodeType > &DT, typename GraphT::NodeType *V, unsigned LastLinked)
template<class GraphT>
unsigned DFSPass (DominatorTreeBase< typename GraphT::NodeType > &DT, typename GraphT::NodeType *V, unsigned N)
template<class FuncT, class N>
void Calculate (DominatorTreeBase< typename GraphTraits< N >::NodeType > &DT, FuncT &F)
Detailed Description
template<class NodeT>
class llvm::DominatorTreeBase< NodeT >
Core dominator tree base class.
This class is a generic template over graph nodes. It is instantiated for various graphs in the LLVM IR or in the code generator.
Definition at line 184 of file GenericDomTree.h.
Member Typedef Documentation
DomTreeNodeMapType
template<class NodeT> typedef DenseMap<NodeT *, DomTreeNodeBase<NodeT> *> llvm::DominatorTreeBase< NodeT >::DomTreeNodeMapType protected
Definition at line 213 of file GenericDomTree.h.
Constructor & Destructor Documentation
DominatorTreeBase() [1/2]
template<class NodeT> llvm::DominatorTreeBase< NodeT >::DominatorTreeBase (bool isPostDom) inline explicit
Definition at line 315 of file GenericDomTree.h.
~DominatorTreeBase()
template<class NodeT> llvm::DominatorTreeBase< NodeT >::~DominatorTreeBase () inline
Definition at line 317 of file GenericDomTree.h.
DominatorTreeBase() [2/2]
template<class NodeT> llvm::DominatorTreeBase< NodeT >::DominatorTreeBase (DominatorTreeBase< NodeT > && Arg) inline
Definition at line 319 of file GenericDomTree.h.
Member Function Documentation
addNewBlock()
template<class NodeT> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT >::addNewBlock (NodeT * BB, NodeT * DomBB) inline
addNewBlock - Add a new node to the dominator tree information. This creates a new node as a child of DomBB dominator node,linking it into the children list of the immediate dominator.
Definition at line 553 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::Split(), llvm::SplitBlock(), and llvm::SplitBlockAndInsertIfThen().
addRoot() [1/2]
void llvm::DominatorTreeBase< MachineBasicBlock >::addRoot (MachineBasicBlock * MBB) inline protected
Definition at line 28 of file MachineDominators.h.
addRoot() [2/2]
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::addRoot (NodeT * BB) inline protected
Definition at line 712 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::recalculate().
changeImmediateDominator() [1/2]
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::changeImmediateDominator (DomTreeNodeBase< NodeT > * N, DomTreeNodeBase< NodeT > * NewIDom) inline
changeImmediateDominator - This method is used to update the dominator tree information when a node's immediate dominator changes.
Definition at line 565 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::changeImmediateDominator(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), simplifyOneLoop(), llvm::DominatorTreeBase< BlockT >::Split(), llvm::SplitBlock(), and llvm::SplitBlockAndInsertIfThen().
changeImmediateDominator() [2/2]
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::changeImmediateDominator (NodeT * BB, NodeT * NewBB) inline
Definition at line 572 of file GenericDomTree.h.
compare()
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::compare (const DominatorTreeBase< NodeT > & Other) const inline
compare - Return false if the other dominator tree base matches this dominator tree base. Otherwise return true.
Definition at line 345 of file GenericDomTree.h.
dominates() [1/2]
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::dominates (const DomTreeNodeBase< NodeT > * A, const DomTreeNodeBase< NodeT > * B) const inline
dominates - Returns true iff A dominates B. Note that this is not a constant time operation!
Definition at line 435 of file GenericDomTree.h.
Referenced by llvm::LoopInfoBase< BlockT, LoopT >::Analyze(), dominates(), llvm::DominatorTreeBase< BlockT >::findNearestCommonDominator(), properlyDominates(), llvm::DominatorTreeBase< BlockT >::properlyDominates(), and llvm::DominatorTreeBase< BlockT >::Split().
dominates() [2/2]
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::dominates (const NodeT * A, const NodeT * B) const
Definition at line 751 of file GenericDomTree.h.
References dominates(), and getNode().
eraseNode()
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::eraseNode (NodeT * BB) inline
eraseNode - Removes a node from the dominator tree. Block must not dominate any other blocks. Removes node from its immediate dominator's children list. Deletes dominator node associated with basic block BB.
Definition at line 579 of file GenericDomTree.h.
Referenced by llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), and simplifyOneLoop().
findNearestCommonDominator() [1/2]
template<class NodeT> const NodeT * llvm::DominatorTreeBase< NodeT >::findNearestCommonDominator (const NodeT * A, const NodeT * B) inline
Definition at line 539 of file GenericDomTree.h.
findNearestCommonDominator() [2/2]
template<class NodeT> NodeT * llvm::DominatorTreeBase< NodeT >::findNearestCommonDominator (NodeT * A, NodeT * B) inline
findNearestCommonDominator - Find nearest common dominator basic block for basic block A and B. If there is no such block then return NULL.
Definition at line 480 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::findNearestCommonDominator(), getInsertPointForUses(), and llvm::DominatorTreeBase< BlockT >::Split().
getDescendants()
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::getDescendants (NodeT * R, SmallVectorImpl< NodeT * > & Result) const inline
Get all nodes dominated by R, including R itself.
Definition at line 393 of file GenericDomTree.h.
getIDom()
template<class NodeT> NodeT * llvm::DominatorTreeBase< NodeT >::getIDom (NodeT * BB) const inline protected
Definition at line 710 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::getNodeForBlock().
getNode()
template<class NodeT> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT >::getNode (NodeT * BB) const inline
getNode - return the (Post)DominatorTree node for the specified basic block. This is the same as using operator[] on this class.
Definition at line 376 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::addNewBlock(), blockDominatesAnExit(), llvm::DominatorTreeBase< BlockT >::changeImmediateDominator(), dominates(), llvm::DominatorTreeBase< BlockT >::eraseNode(), llvm::DominatorTreeBase< BlockT >::findNearestCommonDominator(), llvm::DominatorTreeBase< BlockT >::getDescendants(), llvm::DominatorTreeBase< BlockT >::getNodeForBlock(), llvm::DominatorTreeBase< BlockT >::isReachableFromEntry(), isSimplifiedLoopNest(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::DominatorTreeBase< BlockT >::operator[](), processInstruction(), properlyDominates(), llvm::DominatorTreeBase< BlockT >::removeNode(), simplifyOneLoop(), llvm::DominatorTreeBase< BlockT >::Split(), llvm::SplitBlock(), and llvm::SplitBlockAndInsertIfThen().
getNodeForBlock()
template<class NodeT> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT >::getNodeForBlock (NodeT * BB) inline protected
Definition at line 693 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::getNodeForBlock().
getRoot()
template<class NodeT> NodeT * llvm::DominatorTreeBase< NodeT >::getRoot () const inline
Definition at line 473 of file GenericDomTree.h.
getRootNode() [1/2]
template<class NodeT> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT >::getRootNode () inline
getRootNode - This returns the entry node for the CFG of the function. If this tree represents the post-dominance relations for a function, however, this root may be a node with the block == NULL. This is the case when there are multiple exit nodes from a particular function. Consumers of post-dominance information must be capable of dealing with this possibility.
Definition at line 389 of file GenericDomTree.h.
Referenced by llvm::LoopInfoBase< BlockT, LoopT >::Analyze(), llvm::DominatorTree::compare(), llvm::GraphTraits< DominatorTree * >::getEntryNode(), llvm::DominatorTreeBase< BlockT >::print(), and llvm::DominatorTreeBase< BlockT >::updateDFSNumbers().
getRootNode() [2/2]
template<class NodeT> const DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT >::getRootNode () const inline
Definition at line 390 of file GenericDomTree.h.
isReachableFromEntry() [1/2]
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::isReachableFromEntry (const DomTreeNodeBase< NodeT > * A) const inline
Definition at line 430 of file GenericDomTree.h.
isReachableFromEntry() [2/2]
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::isReachableFromEntry (const NodeT * A) const inline
isReachableFromEntry - Return true if A is dominated by the entry block of the function containing it.
Definition at line 424 of file GenericDomTree.h.
Referenced by llvm::LoopInfoBase< BlockT, LoopT >::Analyze(), llvm::discoverAndMapSubloop(), llvm::DominatorTreeBase< BlockT >::dominates(), llvm::DominatorTreeBase< BlockT >::isReachableFromEntry(), and llvm::DominatorTreeBase< BlockT >::Split().
operator=()
template<class NodeT> DominatorTreeBase & llvm::DominatorTreeBase< NodeT >::operator= (DominatorTreeBase< NodeT > && RHS) inline
Definition at line 329 of file GenericDomTree.h.
operator[]()
template<class NodeT> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT >::operator[] (NodeT * BB) const inline
Definition at line 380 of file GenericDomTree.h.
print()
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::print (raw_ostream & o) const inline
print - Convert to human readable form
Definition at line 619 of file GenericDomTree.h.
Referenced by llvm::DominatorTree::verifyDomTree().
properlyDominates() [1/2]
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::properlyDominates (const DomTreeNodeBase< NodeT > * A, const DomTreeNodeBase< NodeT > * B) const inline
properlyDominates - Returns true iff A dominates B and A != B. Note that this is not a constant time operation!
Definition at line 411 of file GenericDomTree.h.
Referenced by llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), and isLoopInvariant().
properlyDominates() [2/2]
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::properlyDominates (const NodeT * A, const NodeT * B) const
Definition at line 762 of file GenericDomTree.h.
References dominates(), and getNode().
recalculate()
template<class NodeT> template<class FT> void llvm::DominatorTreeBase< NodeT >::recalculate (FT & F) inline
recalculate - compute a dominator tree for the given function
Definition at line 716 of file GenericDomTree.h.
Referenced by AddAliasScopeMetadata(), AddAlignmentAssumptions(), llvm::DominatorTreeAnalysis::run(), llvm::UnrollLoop(), and llvm::DominatorTree::verifyDomTree().
releaseMemory()
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::releaseMemory () inline
Definition at line 371 of file GenericDomTree.h.
removeNode()
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::removeNode (NodeT * BB) inline
removeNode - Removes a node from the dominator tree. Block must not dominate any other blocks. Invalidates any node pointing to removed block.
Definition at line 602 of file GenericDomTree.h.
reset()
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::reset () inline protected
Definition at line 237 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::recalculate(), llvm::DominatorTreeBase< BlockT >::releaseMemory(), llvm::MemoryDependenceAnalysis::runOnFunction(), and llvm::DominatorTreeBase< BlockT >::~DominatorTreeBase().
Split()
template<class NodeT> template<class N, class GraphT> void llvm::DominatorTreeBase< NodeT >::Split (DominatorTreeBase< typename GraphT::NodeType > & DT, typename GraphT::NodeType * NewBB) inline protected
Definition at line 252 of file GenericDomTree.h.
splitBlock()
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::splitBlock (NodeT * NewBB) inline
splitBlock - BB is split and now it has one successor. Update dominator tree to reflect this change.
Definition at line 609 of file GenericDomTree.h.
Referenced by insertUniqueBackedgeBlock().
updateDFSNumbers()
template<class NodeT> void llvm::DominatorTreeBase< NodeT >::updateDFSNumbers () const inline protected
updateDFSNumbers - Assign In and Out numbers to the nodes while walking dominator tree in dfs order.
Definition at line 650 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::dominates().
Friends And Related Symbol Documentation
Calculate
template<class NodeT> template<class FuncT, class N> void Calculate (DominatorTreeBase< typename GraphTraits< N >::NodeType > & DT, FuncT & F) friend
Referenced by llvm::DominatorTreeBase< BlockT >::recalculate().
DFSPass
template<class NodeT> template<class GraphT> unsigned DFSPass (DominatorTreeBase< typename GraphT::NodeType > & DT, typename GraphT::NodeType * V, unsigned N) friend
Definition at line 34 of file GenericDomTreeConstruction.h.
Eval
template<class NodeT> template<class GraphT> GraphT::NodeType * Eval (DominatorTreeBase< typename GraphT::NodeType > & DT, typename GraphT::NodeType * V, unsigned LastLinked) friend
Definition at line 108 of file GenericDomTreeConstruction.h.
Member Data Documentation
DFSInfoValid
template<class NodeT> bool llvm::DominatorTreeBase< NodeT >::DFSInfoValid mutable protected
Definition at line 217 of file GenericDomTree.h.
DomTreeNodes
template<class NodeT> DomTreeNodeMapType llvm::DominatorTreeBase< NodeT >::DomTreeNodes protected
Definition at line 214 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::compare().
IDoms
template<class NodeT> DenseMap<NodeT *, NodeT *> llvm::DominatorTreeBase< NodeT >::IDoms protected
Definition at line 229 of file GenericDomTree.h.
Info
template<class NodeT> DenseMap<NodeT *, InfoRec> llvm::DominatorTreeBase< NodeT >::Info protected
Definition at line 235 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::DFSPass, and llvm::DominatorTreeBase< BlockT >::Eval.
RootNode
template<class NodeT> DomTreeNodeBase<NodeT>* llvm::DominatorTreeBase< NodeT >::RootNode protected
Definition at line 215 of file GenericDomTree.h.
SlowQueries
template<class NodeT> unsigned int llvm::DominatorTreeBase< NodeT >::SlowQueries mutable protected
Definition at line 218 of file GenericDomTree.h.
Vertex
template<class NodeT> std::vector<NodeT *> llvm::DominatorTreeBase< NodeT >::Vertex protected
Definition at line 232 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< BlockT >::DFSPass, and llvm::DominatorTreeBase< BlockT >::Eval.
The documentation for this class was generated from the following files:
LoopInfo.h
GenericDomTree.h