LLVM: llvm::StringMapEntryBase Class Reference
LLVM API Documentation
llvm::StringMapEntryBase Class Reference
StringMapEntryBase - Shared base class of StringMapEntry instances.
#include <StringMap.h>
Public Member Functions
StringMapEntryBase (unsigned Len)
unsigned getKeyLength () const
Detailed Description
StringMapEntryBase - Shared base class of StringMapEntry instances.
Definition at line 31 of file StringMap.h.
Constructor & Destructor Documentation
StringMapEntryBase()
llvm::StringMapEntryBase::StringMapEntryBase (unsigned Len) inline explicit
Definition at line 34 of file StringMap.h.
Referenced by llvm::StringMapEntry< Value * >::StringMapEntry(), and llvm::StringMapEntry< Value * >::StringMapEntry().
Member Function Documentation
getKeyLength()
unsigned llvm::StringMapEntryBase::getKeyLength () const inline
Definition at line 36 of file StringMap.h.
Referenced by llvm::StringMapEntry< Value * >::Destroy(), llvm::StringMapImpl::FindKey(), llvm::StringMapEntry< Value * >::first(), llvm::TargetIntrinsicInfo::getIntrinsicID(), llvm::StringMapEntry< Value * >::getKey(), and llvm::StringMapImpl::LookupBucketFor().
The documentation for this class was generated from the following file:
StringMap.h