LLVM: llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT > Class Template Reference
LLVM API Documentation
llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT > Class Template Reference
#include <DenseMap.h>
Public Member Functions
SmallDenseMap (unsigned NumInitBuckets=0)
SmallDenseMap (const SmallDenseMap &other)
SmallDenseMap (SmallDenseMap &&other)
template<typename InputIt>
SmallDenseMap (const InputIt &I, const InputIt &E)
~SmallDenseMap ()
void swap (SmallDenseMap &RHS)
SmallDenseMap & operator= (const SmallDenseMap &other)
SmallDenseMap & operator= (SmallDenseMap &&other)
void copyFrom (const SmallDenseMap &other)
void init (unsigned InitBuckets)
void grow (unsigned AtLeast)
void shrink_and_clear ()
Public Member Functions inherited from llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
unsigned size () const
void resize (size_type Size)
Grow the densemap so that it has at least Size buckets. Does not shrink.
void clear ()
size_type count (const KeyT &Val) const
Return 1 if the specified key is in the map, 0 otherwise.
iterator find (const KeyT &Val)
const_iterator find (const KeyT &Val) const
template<class LookupKeyT>
iterator find_as (const LookupKeyT &Val)
template<class LookupKeyT>
const_iterator find_as (const LookupKeyT &Val) const
ValueT lookup (const KeyT &Val) const
std::pair< iterator, bool > insert (const std::pair< KeyT, ValueT > &KV)
std::pair< iterator, bool > insert (std::pair< KeyT, ValueT > &&KV)
template<typename InputIt>
void insert (InputIt I, InputIt E)
insert - Range insertion of pairs.
bool erase (const KeyT &Val)
void erase (iterator I)
value_type & FindAndConstruct (const KeyT &Key)
ValueT & operator[] (const KeyT &Key)
value_type & FindAndConstruct (KeyT &&Key)
ValueT & operator[] (KeyT &&Key)
bool isPointerIntoBucketsArray (const void *Ptr) const
const void * getPointerIntoBucketsArray () const
size_t getMemorySize () const
Friends
class DenseMapBase< SmallDenseMap, KeyT, ValueT, KeyInfoT, BucketT >
Additional Inherited Members
Public Types inherited from llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
typedef unsigned size_type
typedef KeyT key_type
typedef ValueT mapped_type
typedef BucketT value_type
typedef DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT > iterator
typedef DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT, true > const_iterator
Protected Member Functions inherited from llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
DenseMapBase ()
void destroyAll ()
void initEmpty ()
void moveFromOldBuckets (BucketT *OldBucketsBegin, BucketT *OldBucketsEnd)
template<typename OtherBaseT>
void copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT, BucketT > &other)
void swap (DenseMapBase &RHS)
Static Protected Member Functions inherited from llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
static unsigned getHashValue (const KeyT &Val)
template<typename LookupKeyT>
static unsigned getHashValue (const LookupKeyT &Val)
static const KeyT getEmptyKey ()
static const KeyT getTombstoneKey ()
Detailed Description
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>>
class llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >
Definition at line 695 of file DenseMap.h.
Constructor & Destructor Documentation
SmallDenseMap() [1/4]
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::SmallDenseMap (unsigned NumInitBuckets = 0) inline explicit
Definition at line 718 of file DenseMap.h.
SmallDenseMap() [2/4]
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::SmallDenseMap (const SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT > & other) inline
Definition at line 722 of file DenseMap.h.
SmallDenseMap() [3/4]
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::SmallDenseMap (SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT > && other) inline
Definition at line 727 of file DenseMap.h.
SmallDenseMap() [4/4]
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> template<typename InputIt> llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::SmallDenseMap (const InputIt & I, const InputIt & E) inline
Definition at line 733 of file DenseMap.h.
~SmallDenseMap()
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::~SmallDenseMap () inline
Definition at line 738 of file DenseMap.h.
Member Function Documentation
copyFrom()
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> void llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::copyFrom (const SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT > & other) inline
Definition at line 829 of file DenseMap.h.
Referenced by llvm::SmallDenseMap< uint64_t, std::vector< uint64_t >, 1 >::operator=(), and llvm::SmallDenseMap< uint64_t, std::vector< uint64_t >, 1 >::SmallDenseMap().
grow()
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> void llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::grow (unsigned AtLeast) inline
Definition at line 849 of file DenseMap.h.
init()
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> void llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::init (unsigned InitBuckets) inline
Definition at line 840 of file DenseMap.h.
Referenced by llvm::SmallDenseMap< uint64_t, std::vector< uint64_t >, 1 >::operator=(), llvm::SmallDenseMap< uint64_t, std::vector< uint64_t >, 1 >::shrink_and_clear(), llvm::SmallDenseMap< uint64_t, std::vector< uint64_t >, 1 >::SmallDenseMap(), llvm::SmallDenseMap< uint64_t, std::vector< uint64_t >, 1 >::SmallDenseMap(), llvm::SmallDenseMap< uint64_t, std::vector< uint64_t >, 1 >::SmallDenseMap(), and llvm::SmallDenseMap< uint64_t, std::vector< uint64_t >, 1 >::SmallDenseMap().
operator=() [1/2]
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> SmallDenseMap & llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::operator= (const SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT > & other) inline
Definition at line 815 of file DenseMap.h.
operator=() [2/2]
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> SmallDenseMap & llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::operator= (SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT > && other) inline
Definition at line 821 of file DenseMap.h.
shrink_and_clear()
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> void llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::shrink_and_clear () inline
Definition at line 901 of file DenseMap.h.
swap()
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> void llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::swap (SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT > & RHS) inline
Definition at line 743 of file DenseMap.h.
Referenced by llvm::SmallDenseMap< uint64_t, std::vector< uint64_t >, 1 >::operator=(), and llvm::SmallDenseMap< uint64_t, std::vector< uint64_t >, 1 >::SmallDenseMap().
Friends And Related Symbol Documentation
DenseMapBase< SmallDenseMap, KeyT, ValueT, KeyInfoT, BucketT >
template<typename KeyT, typename ValueT, unsigned InlineBuckets = 4, typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = detail::DenseMapPair<KeyT, ValueT>> friend class DenseMapBase< SmallDenseMap, KeyT, ValueT, KeyInfoT, BucketT > friend
Definition at line 701 of file DenseMap.h.
The documentation for this class was generated from the following file:
DenseMap.h