LLVM: llvm::RegisterPassParser< RegistryClass > Class Template Reference
LLVM API Documentation
llvm::RegisterPassParser< RegistryClass > Class Template Reference
#include <MachinePassRegistry.h>
Public Member Functions
RegisterPassParser ()
~RegisterPassParser ()
void initialize (cl::Option &O)
void NotifyAdd (const char *N, MachinePassCtor C, const char *D) override
void NotifyRemove (const char *N) override
Public Member Functions inherited from llvm::MachinePassRegistryListener
MachinePassRegistryListener ()
virtual ~MachinePassRegistryListener ()
Public Member Functions inherited from llvm::cl::parser< RegistryClass::FunctionPassCtor >
unsigned getNumOptions () const override
const char * getOption (unsigned N) const override
const char * getDescription (unsigned N) const override
const GenericOptionValue & getOptionValue (unsigned N) const override
bool parse (Option &O, StringRef ArgName, StringRef Arg, RegistryClass::FunctionPassCtor &V)
void addLiteralOption (const char *Name, const DT &V, const char *HelpStr)
void removeLiteralOption (const char *Name)
Public Member Functions inherited from llvm::cl::generic_parser_base
virtual ~generic_parser_base ()
virtual size_t getOptionWidth (const Option &O) const
virtual void printOptionInfo (const Option &O, size_t GlobalWidth) const
void printGenericOptionDiff (const Option &O, const GenericOptionValue &V, const GenericOptionValue &Default, size_t GlobalWidth) const
template<class AnyOptionValue>
void printOptionDiff (const Option &O, const AnyOptionValue &V, const AnyOptionValue &Default, size_t GlobalWidth) const
void initialize (Option &O)
void getExtraOptionNames (SmallVectorImpl< const char * > &OptionNames)
enum ValueExpected getValueExpectedFlagDefault () const
unsigned findOption (const char *Name)
Additional Inherited Members
Public Types inherited from llvm::cl::parser< RegistryClass::FunctionPassCtor >
typedef RegistryClass::FunctionPassCtor parser_data_type
Protected Attributes inherited from llvm::cl::parser< RegistryClass::FunctionPassCtor >
SmallVector< OptionInfo, 8 > Values
Protected Attributes inherited from llvm::cl::generic_parser_base
bool hasArgStr
Detailed Description
template<class RegistryClass>
class llvm::RegisterPassParser< RegistryClass >
RegisterPassParser class - Handle the addition of new machine passes.
Definition at line 122 of file MachinePassRegistry.h.
Constructor & Destructor Documentation
RegisterPassParser()
template<class RegistryClass> llvm::RegisterPassParser< RegistryClass >::RegisterPassParser () inline
Definition at line 125 of file MachinePassRegistry.h.
~RegisterPassParser()
template<class RegistryClass> llvm::RegisterPassParser< RegistryClass >::~RegisterPassParser () inline
Definition at line 126 of file MachinePassRegistry.h.
Member Function Documentation
initialize()
template<class RegistryClass> void llvm::RegisterPassParser< RegistryClass >::initialize (cl::Option & O) inline
Definition at line 128 of file MachinePassRegistry.h.
References llvm::cl::parser< RegistryClass::FunctionPassCtor >::addLiteralOption(), and llvm::cl::generic_parser_base::initialize().
NotifyAdd()
template<class RegistryClass> void llvm::RegisterPassParser< RegistryClass >::NotifyAdd (const char * N, MachinePassCtor C, const char * D) inline override virtual
Implements llvm::MachinePassRegistryListener.
Definition at line 145 of file MachinePassRegistry.h.
References llvm::cl::parser< RegistryClass::FunctionPassCtor >::addLiteralOption(), and N.
NotifyRemove()
template<class RegistryClass> void llvm::RegisterPassParser< RegistryClass >::NotifyRemove (const char * N) inline override virtual
Implements llvm::MachinePassRegistryListener.
Definition at line 148 of file MachinePassRegistry.h.
References N, and llvm::cl::parser< RegistryClass::FunctionPassCtor >::removeLiteralOption().
The documentation for this class was generated from the following file:
MachinePassRegistry.h