LLVM: llvm::DISubprogram Class Reference
LLVM API Documentation
llvm::DISubprogram Class Reference
This is a wrapper for a subprogram (e.g. a function).
#include <DebugInfo.h>
Public Member Functions
DISubprogram (const MDNode *N=nullptr)
StringRef getName () const
StringRef getDisplayName () const
StringRef getLinkageName () const
unsigned getLineNumber () const
unsigned isLocalToUnit () const
Check if this is local (like 'static' in C).
unsigned isDefinition () const
unsigned getVirtuality () const
unsigned getVirtualIndex () const
unsigned getFlags () const
unsigned isOptimized () const
unsigned getScopeLineNumber () const
Get the beginning of the scope of the function (not the name).
DIScopeRef getContext () const
DISubroutineType getType () const
DITypeRef getContainingType () const
bool Verify () const
bool describes (const Function *F)
Check if this provides debugging information for the function F.
Function * getFunction () const
void replaceFunction (Function *F)
DIArray getTemplateParams () const
DISubprogram getFunctionDeclaration () const
MDNode * getVariablesNodes () const
DIArray getVariables () const
unsigned isArtificial () const
bool isPrivate () const
Check for the "private" access specifier.
bool isProtected () const
Check for the "protected" access specifier.
bool isPublic () const
Check for the "public" access specifier.
bool isExplicit () const
Check for "explicit".
bool isPrototyped () const
Check if this is prototyped.
unsigned isLValueReference () const
Check if this is reference-qualified.
unsigned isRValueReference () const
Check if this is rvalue-reference-qualified.
Public Member Functions inherited from llvm::DIScope
DIScope (const MDNode *N=nullptr)
DIScopeRef getContext () const
Get the parent scope.
StringRef getName () const
Get the scope name.
StringRef getFilename () const
StringRef getDirectory () const
DIScopeRef getRef () const
Generate a reference to this DIScope.
Public Member Functions inherited from llvm::DIDescriptor
DIDescriptor (const MDNode *N=nullptr)
bool Verify () const
MDNode * get () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
StringRef getHeader () const
size_t getNumHeaderFields () const
StringRef getHeaderField (unsigned Index) const
template<class T>
T getHeaderFieldAs (unsigned Index) const
uint16_t getTag () const
bool isDerivedType () const
bool isCompositeType () const
bool isSubroutineType () const
bool isBasicType () const
bool isVariable () const
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
bool isCompileUnit () const
bool isNameSpace () const
bool isLexicalBlockFile () const
bool isLexicalBlock () const
bool isSubrange () const
bool isEnumerator () const
bool isType () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
bool isImportedEntity () const
bool isExpression () const
void print (raw_ostream &OS) const
void dump () const
void replaceAllUsesWith (LLVMContext &VMContext, DIDescriptor D)
Replace all uses of debug info referenced by this descriptor.
void replaceAllUsesWith (MDNode *D)
Friends
class DIDescriptor
Additional Inherited Members
Public Types inherited from llvm::DIDescriptor
enum {
FlagAccessibility = 1 << 0 | 1 << 1 , FlagPrivate = 1 , FlagProtected = 2 , FlagPublic = 3 ,
FlagFwdDecl = 1 << 2 , FlagAppleBlock = 1 << 3 , FlagBlockByrefStruct = 1 << 4 , FlagVirtual = 1 << 5 ,
FlagArtificial = 1 << 6 , FlagExplicit = 1 << 7 , FlagPrototyped = 1 << 8 , FlagObjcClassComplete = 1 << 9 ,
FlagObjectPointer = 1 << 10 , FlagVector = 1 << 11 , FlagStaticMember = 1 << 12 , FlagIndirectVariable = 1 << 13 ,
FlagLValueReference = 1 << 14 , FlagRValueReference = 1 << 15
}
Accessibility flags.
Protected Member Functions inherited from llvm::DIScope
void printInternal (raw_ostream &OS) const
Protected Member Functions inherited from llvm::DIDescriptor
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy>
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
template<>
DITypeRef getFieldAs (unsigned Elt) const
Protected Attributes inherited from llvm::DIDescriptor
const MDNode * DbgNode
Detailed Description
This is a wrapper for a subprogram (e.g. a function).
Definition at line 597 of file DebugInfo.h.
Constructor & Destructor Documentation
DISubprogram()
llvm::DISubprogram::DISubprogram (const MDNode * N = nullptr) inline explicit
Definition at line 602 of file DebugInfo.h.
References llvm::DIScope::DIScope(), and N.
Referenced by getFunctionDeclaration(), and Verify().
Member Function Documentation
describes()
bool DISubprogram::describes (const Function * F)
Check if this provides debugging information for the function F.
Definition at line 710 of file DebugInfo.cpp.
References F, getFunction(), getLinkageName(), getName(), and Name.
Referenced by llvm::getDISubprogram(), llvm::DIVariable::isInlinedFnArgument(), and Verify().
getContainingType()
DITypeRef llvm::DISubprogram::getContainingType () const inline
Definition at line 626 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
getContext()
DIScopeRef llvm::DISubprogram::getContext () const inline
Definition at line 623 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
Referenced by llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition().
getDisplayName()
StringRef llvm::DISubprogram::getDisplayName () const inline
Definition at line 605 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
Referenced by emitDebugValueComment().
getFlags()
unsigned llvm::DISubprogram::getFlags () const inline
Definition at line 616 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
Referenced by isArtificial(), isExplicit(), isLValueReference(), isPrivate(), isProtected(), isPrototyped(), isPublic(), and isRValueReference().
getFunction()
Function * llvm::DISubprogram::getFunction () const inline
Definition at line 633 of file DebugInfo.h.
References llvm::DIDescriptor::getFunctionField().
Referenced by describes(), and Verify().
getFunctionDeclaration()
DISubprogram llvm::DISubprogram::getFunctionDeclaration () const inline
Definition at line 636 of file DebugInfo.h.
References DISubprogram(), and llvm::DIDescriptor::getFieldAs().
Referenced by llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), llvm::DwarfUnit::applySubprogramDefinitionAttributes(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), and llvm::DwarfUnit::getOrCreateSubprogramDIE().
getLineNumber()
unsigned llvm::DISubprogram::getLineNumber () const inline
Definition at line 607 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
getLinkageName()
StringRef llvm::DISubprogram::getLinkageName () const inline
Definition at line 606 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
Referenced by describes().
getName()
StringRef llvm::DISubprogram::getName () const inline
Definition at line 604 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
Referenced by describes(), and llvm::DIScope::getName().
getScopeLineNumber()
unsigned llvm::DISubprogram::getScopeLineNumber () const inline
Get the beginning of the scope of the function (not the name).
Definition at line 621 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
getTemplateParams()
DIArray llvm::DISubprogram::getTemplateParams () const inline
Definition at line 635 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
getType()
DISubroutineType llvm::DISubprogram::getType () const inline
Definition at line 624 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
getVariables()
DIArray DISubprogram::getVariables () const
Definition at line 726 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, and getNodeField().
getVariablesNodes()
MDNode * DISubprogram::getVariablesNodes () const
Definition at line 722 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, and getNodeField().
getVirtualIndex()
unsigned llvm::DISubprogram::getVirtualIndex () const inline
Definition at line 614 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
getVirtuality()
unsigned llvm::DISubprogram::getVirtuality () const inline
Definition at line 613 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
isArtificial()
unsigned llvm::DISubprogram::isArtificial () const inline
Definition at line 642 of file DebugInfo.h.
References llvm::DIDescriptor::FlagArtificial, and getFlags().
isDefinition()
unsigned llvm::DISubprogram::isDefinition () const inline
Definition at line 611 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
isExplicit()
bool llvm::DISubprogram::isExplicit () const inline
Check for "explicit".
Definition at line 656 of file DebugInfo.h.
References llvm::DIDescriptor::FlagExplicit, and getFlags().
isLocalToUnit()
unsigned llvm::DISubprogram::isLocalToUnit () const inline
Check if this is local (like 'static' in C).
Definition at line 610 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
isLValueReference()
unsigned llvm::DISubprogram::isLValueReference () const inline
Check if this is reference-qualified.
Return true if this subprogram is a C++11 reference-qualified non-static member function (void foo() &).
Definition at line 664 of file DebugInfo.h.
References llvm::DIDescriptor::FlagLValueReference, and getFlags().
Referenced by Verify().
isOptimized()
unsigned llvm::DISubprogram::isOptimized () const inline
Definition at line 618 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
isPrivate()
bool llvm::DISubprogram::isPrivate () const inline
Check for the "private" access specifier.
Definition at line 644 of file DebugInfo.h.
References llvm::DIDescriptor::FlagAccessibility, llvm::DIDescriptor::FlagPrivate, and getFlags().
isProtected()
bool llvm::DISubprogram::isProtected () const inline
Check for the "protected" access specifier.
Definition at line 648 of file DebugInfo.h.
References llvm::DIDescriptor::FlagAccessibility, llvm::DIDescriptor::FlagProtected, and getFlags().
isPrototyped()
bool llvm::DISubprogram::isPrototyped () const inline
Check if this is prototyped.
Definition at line 658 of file DebugInfo.h.
References llvm::DIDescriptor::FlagPrototyped, and getFlags().
isPublic()
bool llvm::DISubprogram::isPublic () const inline
Check for the "public" access specifier.
Definition at line 652 of file DebugInfo.h.
References llvm::DIDescriptor::FlagAccessibility, llvm::DIDescriptor::FlagPublic, and getFlags().
isRValueReference()
unsigned llvm::DISubprogram::isRValueReference () const inline
Check if this is rvalue-reference-qualified.
Return true if this subprogram is a C++11 rvalue-reference-qualified non-static member function (void foo() &&).
Definition at line 672 of file DebugInfo.h.
References llvm::DIDescriptor::FlagRValueReference, and getFlags().
Referenced by Verify().
replaceFunction()
void llvm::DISubprogram::replaceFunction (Function * F) inline
Definition at line 634 of file DebugInfo.h.
References F, and llvm::DIDescriptor::replaceFunctionField().
Verify()
bool DISubprogram::Verify () const
Definition at line 496 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, describes(), DIDescriptor, DISubprogram(), F, fieldIsMDNode(), fieldIsScopeRef(), fieldIsTypeRef(), llvm::DebugLoc::getFromDILexicalBlock(), llvm::DebugLoc::getFromDILocation(), getFunction(), llvm::DebugLoc::getInlinedAt(), llvm::DIDescriptor::getNumHeaderFields(), llvm::DebugLoc::getScope(), llvm::DILexicalBlockFile::getScope(), llvm::DebugLoc::getScopeAndInlinedAt(), I, llvm::DIDescriptor::isLexicalBlockFile(), isLValueReference(), isRValueReference(), llvm::DIDescriptor::isSubprogram(), and llvm::DebugLoc::isUnknown().
Referenced by llvm::DIDescriptor::Verify().
Friends And Related Symbol Documentation
DIDescriptor
friend class DIDescriptor friend
Definition at line 598 of file DebugInfo.h.
References DIDescriptor.
Referenced by DIDescriptor, and Verify().
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp