LLVM: llvm::AssemblerConstantPools Class Reference
LLVM API Documentation
llvm::AssemblerConstantPools Class Reference
#include <ConstantPools.h>
Public Member Functions
AssemblerConstantPools ()
~AssemblerConstantPools ()
void emitAll (MCStreamer &Streamer)
void emitForCurrentSection (MCStreamer &Streamer)
const MCExpr * addEntry (MCStreamer &Streamer, const MCExpr *Expr, unsigned Size)
Detailed Description
Definition at line 61 of file ConstantPools.h.
Constructor & Destructor Documentation
AssemblerConstantPools()
llvm::AssemblerConstantPools::AssemblerConstantPools () inline
Definition at line 80 of file ConstantPools.h.
~AssemblerConstantPools()
llvm::AssemblerConstantPools::~AssemblerConstantPools () inline
Definition at line 81 of file ConstantPools.h.
Member Function Documentation
addEntry()
const MCExpr * AssemblerConstantPools::addEntry (MCStreamer & Streamer, const MCExpr * Expr, unsigned Size)
Definition at line 92 of file ConstantPools.cpp.
References llvm::MCStreamer::getContext(), and llvm::MCStreamer::getCurrentSection().
emitAll()
void AssemblerConstantPools::emitAll (MCStreamer & Streamer)
Definition at line 73 of file ConstantPools.cpp.
References emitConstantPool().
emitForCurrentSection()
void AssemblerConstantPools::emitForCurrentSection (MCStreamer & Streamer)
Definition at line 85 of file ConstantPools.cpp.
References emitConstantPool(), and llvm::MCStreamer::getCurrentSection().
The documentation for this class was generated from the following files:
ConstantPools.h
ConstantPools.cpp