LLVM: llvm::GlobalVariable Class Reference
LLVM API Documentation
llvm::GlobalVariable Class Reference
#include <GlobalVariable.h>
Public Member Functions
void * operator new (size_t s)
GlobalVariable (Type *Ty, bool isConstant, LinkageTypes Linkage, Constant *Initializer=nullptr, const Twine &Name="", ThreadLocalMode=NotThreadLocal, unsigned AddressSpace=0, bool isExternallyInitialized=false)
GlobalVariable (Module &M, Type *Ty, bool isConstant, LinkageTypes Linkage, Constant *Initializer, const Twine &Name="", GlobalVariable *InsertBefore=nullptr, ThreadLocalMode=NotThreadLocal, unsigned AddressSpace=0, bool isExternallyInitialized=false)
~GlobalVariable ()
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
bool hasInitializer () const
bool hasDefinitiveInitializer () const
bool hasUniqueInitializer () const
const Constant * getInitializer () const
Constant * getInitializer ()
void setInitializer (Constant *InitVal)
bool isConstant () const
void setConstant (bool Val)
bool isExternallyInitialized () const
void setExternallyInitialized (bool Val)
void copyAttributesFrom (const GlobalValue *Src) override
void removeFromParent () override
void eraseFromParent () override
void replaceUsesOfWithOnConstant (Value *From, Value *To, Use *U) override
Public Member Functions inherited from llvm::GlobalObject
unsigned getAlignment () const
void setAlignment (unsigned Align)
unsigned getGlobalObjectSubClassData () const
void setGlobalObjectSubClassData (unsigned Val)
bool hasSection () const
const char * getSection () const
void setSection (StringRef S)
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
void setComdat (Comdat *C)
Public Member Functions inherited from llvm::GlobalValue
~GlobalValue ()
unsigned getAlignment () const
bool hasUnnamedAddr () const
void setUnnamedAddr (bool Val)
bool hasComdat () const
Comdat * getComdat ()
const Comdat * getComdat () const
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
bool isThreadLocal () const
If the value is "Thread Local", its value isn't shared by the threads.
void setThreadLocal (bool Val)
void setThreadLocalMode (ThreadLocalMode Val)
ThreadLocalMode getThreadLocalMode () const
DLLStorageClassTypes getDLLStorageClass () const
bool hasDLLImportStorageClass () const
bool hasDLLExportStorageClass () const
void setDLLStorageClass (DLLStorageClassTypes C)
bool hasSection () const
const char * getSection () const
PointerType * getType () const
Global values are always pointers.
bool hasExternalLinkage () const
bool hasAvailableExternallyLinkage () const
bool hasLinkOnceLinkage () const
bool hasLinkOnceODRLinkage () const
bool hasWeakLinkage () const
bool hasWeakAnyLinkage () const
bool hasWeakODRLinkage () const
bool hasAppendingLinkage () const
bool hasInternalLinkage () const
bool hasPrivateLinkage () const
bool hasLocalLinkage () const
bool hasExternalWeakLinkage () const
bool hasCommonLinkage () const
void setLinkage (LinkageTypes LT)
LinkageTypes getLinkage () const
bool isDiscardableIfUnused () const
bool mayBeOverridden () const
bool isWeakForLinker () const
void destroyConstant () override
Override from Constant class.
bool isDeclaration () const
bool isDeclarationForLinker () const
Module * getParent ()
Get the module that this global value is contained inside of...
const Module * getParent () const
const DataLayout * getDataLayout () const
bool isMaterializable () const
bool isDematerializable () const
std::error_code materialize ()
void Dematerialize ()
Public Member Functions inherited from llvm::Constant
bool isNullValue () const
bool isOneValue () const
Returns true if the value is one.
bool isAllOnesValue () const
bool isNegativeZeroValue () const
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool canTrap () const
bool isThreadDependent () const
isThreadDependent - Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
PossibleRelocationsTy getRelocationInfo () const
Constant * getAggregateElement (unsigned Elt) const
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
const APInt & getUniqueInteger () const
void removeDeadConstantUsers () const
Constant * stripPointerCasts ()
const Constant * stripPointerCasts () const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Public Member Functions inherited from llvm::ilist_node< GlobalVariable >
GlobalVariable * getPrevNode ()
Get the previous node, or 0 for the list head.
GlobalVariable * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::GlobalObject
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::GlobalValue
static LinkageTypes getLinkOnceLinkage (bool ODR)
static LinkageTypes getWeakLinkage (bool ODR)
static bool isExternalLinkage (LinkageTypes Linkage)
static bool isAvailableExternallyLinkage (LinkageTypes Linkage)
static bool isLinkOnceODRLinkage (LinkageTypes Linkage)
static bool isLinkOnceLinkage (LinkageTypes Linkage)
static bool isWeakAnyLinkage (LinkageTypes Linkage)
static bool isWeakODRLinkage (LinkageTypes Linkage)
static bool isWeakLinkage (LinkageTypes Linkage)
static bool isAppendingLinkage (LinkageTypes Linkage)
static bool isInternalLinkage (LinkageTypes Linkage)
static bool isPrivateLinkage (LinkageTypes Linkage)
static bool isLocalLinkage (LinkageTypes Linkage)
static bool isExternalWeakLinkage (LinkageTypes Linkage)
static bool isCommonLinkage (LinkageTypes Linkage)
static bool isDiscardableIfUnused (LinkageTypes Linkage)
static bool mayBeOverridden (LinkageTypes Linkage)
static bool isWeakForLinker (LinkageTypes Linkage)
static StringRef getRealLinkageName (StringRef Name)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
static Constant * getAllOnesValue (Type *Ty)
Get the all ones value.
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Friends
class SymbolTableListTraits< GlobalVariable, Module >
Additional Inherited Members
Public Types inherited from llvm::GlobalValue
enum LinkageTypes {
ExternalLinkage = 0 , AvailableExternallyLinkage , LinkOnceAnyLinkage , LinkOnceODRLinkage ,
WeakAnyLinkage , WeakODRLinkage , AppendingLinkage , InternalLinkage ,
PrivateLinkage , ExternalWeakLinkage , CommonLinkage
}
An enumeration for the kinds of linkage for global values.
enum VisibilityTypes { DefaultVisibility = 0 , HiddenVisibility , ProtectedVisibility }
An enumeration for the kinds of visibility of global values.
enum DLLStorageClassTypes { DefaultStorageClass = 0 , DLLImportStorageClass = 1 , DLLExportStorageClass = 2 }
Storage classes of global values for PE targets.
enum ThreadLocalMode {
NotThreadLocal = 0 , GeneralDynamicTLSModel , LocalDynamicTLSModel , InitialExecTLSModel ,
LocalExecTLSModel
}
Public Types inherited from llvm::Constant
enum PossibleRelocationsTy { NoRelocation = 0 , LocalRelocation = 1 , GlobalRelocations = 2 }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range< op_iterator > op_range
typedef iterator_range< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal , BasicBlockVal , FunctionVal , GlobalAliasVal ,
GlobalVariableVal , UndefValueVal , BlockAddressVal , ConstantExprVal ,
ConstantAggregateZeroVal , ConstantDataArrayVal , ConstantDataVectorVal , ConstantIntVal ,
ConstantFPVal , ConstantArrayVal , ConstantStructVal , ConstantVectorVal ,
ConstantPointerNullVal , MetadataAsValueVal , InlineAsmVal , InstructionVal ,
ConstantFirstVal = FunctionVal , ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl< const User > const_user_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Protected Member Functions inherited from llvm::GlobalObject
GlobalObject (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name)
Protected Member Functions inherited from llvm::GlobalValue
GlobalValue (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name)
unsigned getGlobalValueSubClassData () const
void setGlobalValueSubClassData (unsigned V)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
void destroyConstantImpl ()
void replaceUsesOfWithOnConstantImpl (Constant *Replacement)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< GlobalVariable >
ilist_node ()
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::GlobalObject
std::string Section
Comdat * ObjComdat
Protected Attributes inherited from llvm::GlobalValue
LinkageTypes Linkage: 5
unsigned Visibility: 2
unsigned UnnamedAddr: 1
unsigned DllStorageClass: 2
unsigned ThreadLocal: 3
Module * Parent
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Static Protected Attributes inherited from llvm::GlobalObject
static const unsigned AlignmentBits = 5
static const unsigned GlobalObjectSubClassDataBits
Static Protected Attributes inherited from llvm::GlobalValue
static const unsigned GlobalValueSubClassDataBits = 19
Detailed Description
Definition at line 35 of file GlobalVariable.h.
Constructor & Destructor Documentation
GlobalVariable() [1/2]
GlobalVariable::GlobalVariable (Type * Ty, bool isConstant, LinkageTypes Linkage, Constant * Initializer = nullptr, const Twine & Name = "", ThreadLocalMode TLMode = NotThreadLocal, unsigned AddressSpace = 0, bool isExternallyInitialized = false)
GlobalVariable ctor - If a parent module is specified, the global is automatically inserted into the end of the specified modules global list.
Definition at line 146 of file Globals.cpp.
References llvm::Value::getType(), llvm::Value::GlobalVariableVal, isExternallyInitialized(), Name, llvm::User::Op(), llvm::User::op_begin(), and llvm::GlobalValue::setThreadLocalMode().
GlobalVariable() [2/2]
GlobalVariable::GlobalVariable (Module & M, Type * Ty, bool isConstant, LinkageTypes Linkage, Constant * Initializer, const Twine & Name = "", GlobalVariable * InsertBefore = nullptr, ThreadLocalMode TLMode = NotThreadLocal, unsigned AddressSpace = 0, bool isExternallyInitialized = false)
GlobalVariable ctor - This creates a global and inserts it before the specified other global.
Definition at line 163 of file Globals.cpp.
References llvm::Module::getGlobalList(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::Value::GlobalVariableVal, llvm::iplist< NodeTy, Traits >::insert(), isExternallyInitialized(), Name, llvm::User::Op(), llvm::User::op_begin(), llvm::iplist< NodeTy, Traits >::push_back(), and llvm::GlobalValue::setThreadLocalMode().
~GlobalVariable()
llvm::GlobalVariable::~GlobalVariable () inline
Definition at line 69 of file GlobalVariable.h.
References llvm::Value::NumOperands.
Member Function Documentation
classof()
bool llvm::GlobalVariable::classof (const Value * V) inline static
Definition at line 173 of file GlobalVariable.h.
References llvm::Value::GlobalVariableVal.
copyAttributesFrom()
void GlobalVariable::copyAttributesFrom (const GlobalValue * Src) override virtual
copyAttributesFrom - copy all additional attributes (those not needed to create a GlobalVariable) from the GlobalVariable Src to this one.
Reimplemented from llvm::GlobalObject.
Definition at line 235 of file Globals.cpp.
References llvm::cast(), llvm::GlobalObject::copyAttributesFrom(), llvm::GlobalValue::getThreadLocalMode(), llvm::isa(), isExternallyInitialized(), setExternallyInitialized(), and llvm::GlobalValue::setThreadLocalMode().
Referenced by llvm::CloneModule(), and upgradeGlobalArray().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::GlobalVariable::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
eraseFromParent()
void GlobalVariable::eraseFromParent () override virtual
eraseFromParent - This method unlinks 'this' from the containing module and deletes it.
Implements llvm::GlobalValue.
Definition at line 194 of file Globals.cpp.
References llvm::iplist< NodeTy, Traits >::erase(), llvm::Module::getGlobalList(), and llvm::GlobalValue::getParent().
Referenced by OptimizeAwayTrappingUsesOfLoads(), OptimizeGlobalAddressOfMalloc(), PerformHeapAllocSRoA(), TryToShrinkGlobalToBoolean(), and upgradeGlobalArray().
getInitializer() [1/2]
Constant * llvm::GlobalVariable::getInitializer () inline
Definition at line 131 of file GlobalVariable.h.
References llvm::Use::get(), hasInitializer(), and llvm::User::Op().
getInitializer() [2/2]
const Constant * llvm::GlobalVariable::getInitializer () const inline
getInitializer - Return the initializer for this global variable. It is illegal to call this method if the global is external, because we cannot tell what the value is initialized to!
Definition at line 127 of file GlobalVariable.h.
References llvm::Use::get(), hasInitializer(), and llvm::User::Op().
Referenced by llvm::MachineModuleInfo::AnalyzeModule(), llvm::collectUsedGlobalVariables(), CommitValueTo(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::ExecutionEngine::EmitGlobalVariable(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::ExtractTypeInfo(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), FoldReinterpretLoadFromConstPtr(), llvm::getConstantStringInfo(), llvm::TargetLoweringObjectFile::getKindForGlobal(), getVarName(), hasDefinedInitializer(), isSimpleEnoughPointerToCommit(), isSuitableForBSS(), LLVMGetInitializer(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), OptimizeOnceStoredGlobal(), llvm::AssemblyWriter::printGlobal(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), SRAGlobal(), TryToShrinkGlobalToBoolean(), and upgradeGlobalArray().
hasDefinitiveInitializer()
bool llvm::GlobalVariable::hasDefinitiveInitializer () const inline
hasDefinitiveInitializer - Whether the global variable has an initializer, and any other instances of the global (this can happen due to weak linkage) are guaranteed to have the same initializer.
Note that if you want to transform a global, you must use hasUniqueInitializer() instead, because of the *_odr linkage type.
Example:
= global SomeType* null - Initializer is both definitive and unique.
= global weak SomeType* null - Initializer is neither definitive nor unique.
= global weak_odr SomeType* null - Initializer is definitive, but not unique.
Definition at line 96 of file GlobalVariable.h.
References hasInitializer(), isExternallyInitialized(), and llvm::GlobalValue::mayBeOverridden().
Referenced by FoldReinterpretLoadFromConstPtr(), llvm::getConstantStringInfo(), and llvm::ObjectSizeOffsetVisitor::visitGlobalVariable().
hasInitializer()
bool llvm::GlobalVariable::hasInitializer () const inline
Definitions have initializers, declarations don't.
Definition at line 78 of file GlobalVariable.h.
References llvm::GlobalValue::isDeclaration().
Referenced by llvm::MachineModuleInfo::AnalyzeModule(), llvm::collectUsedGlobalVariables(), CommitValueTo(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::ExtractTypeInfo(), getInitializer(), getInitializer(), llvm::DataLayout::getPreferredAlignment(), hasDefinedInitializer(), hasDefinitiveInitializer(), hasUniqueInitializer(), LLVMGetInitializer(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::AssemblyWriter::printGlobal(), and setInitializer().
hasUniqueInitializer()
bool llvm::GlobalVariable::hasUniqueInitializer () const inline
hasUniqueInitializer - Whether the global variable has an initializer, and any changes made to the initializer will turn up in the final executable.
Definition at line 108 of file GlobalVariable.h.
References hasInitializer(), isExternallyInitialized(), and llvm::GlobalValue::isWeakForLinker().
Referenced by isSimpleEnoughPointerToCommit().
isConstant()
bool llvm::GlobalVariable::isConstant () const inline
If the value is a global constant, its value is immutable throughout the runtime execution of the program. Assigning a value into the constant leads to undefined behavior.
Definition at line 144 of file GlobalVariable.h.
Referenced by AnalyzeLoadFromClobberingMemInst(), CleanupPointerRootUsers(), copyGlobalVariableProto(), FoldReinterpretLoadFromConstPtr(), llvm::getConstantStringInfo(), llvm::TargetLoweringObjectFile::getKindForGlobal(), isSuitableForBSS(), llvm::AssemblyWriter::printGlobal(), SRAGlobal(), and upgradeGlobalArray().
isExternallyInitialized()
bool llvm::GlobalVariable::isExternallyInitialized () const inline
Definition at line 147 of file GlobalVariable.h.
Referenced by copyAttributesFrom(), GlobalVariable(), GlobalVariable(), hasDefinitiveInitializer(), hasUniqueInitializer(), llvm::AssemblyWriter::printGlobal(), and upgradeGlobalArray().
operator new()
void * llvm::GlobalVariable::operator new (size_t s) inline
Definition at line 51 of file GlobalVariable.h.
removeFromParent()
void GlobalVariable::removeFromParent () override virtual
removeFromParent - This method unlinks 'this' from the containing module, but does not delete it.
Implements llvm::GlobalValue.
Definition at line 190 of file Globals.cpp.
References llvm::Module::getGlobalList(), llvm::GlobalValue::getParent(), and llvm::iplist< NodeTy, Traits >::remove().
replaceUsesOfWithOnConstant()
void GlobalVariable::replaceUsesOfWithOnConstant (Value * From, Value * To, Use * U) override virtual
Override Constant's implementation of this method so we can replace constant initializers.
Reimplemented from llvm::Constant.
Definition at line 198 of file Globals.cpp.
References llvm::cast(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::isa(), and llvm::User::setOperand().
setConstant()
void llvm::GlobalVariable::setConstant (bool Val) inline
Definition at line 145 of file GlobalVariable.h.
Referenced by EvaluateStaticConstructor().
setExternallyInitialized()
void llvm::GlobalVariable::setExternallyInitialized (bool Val) inline
Definition at line 150 of file GlobalVariable.h.
Referenced by copyAttributesFrom().
setInitializer()
void GlobalVariable::setInitializer (Constant * InitVal)
setInitializer - Sets the initializer for this global variable, removing any existing initializer if InitVal==NULL. If this GV has type T*, the initializer must have type T.
Definition at line 218 of file Globals.cpp.
References llvm::GlobalValue::getType(), llvm::Value::getType(), hasInitializer(), llvm::Value::NumOperands, llvm::User::Op(), and llvm::Use::set().
Referenced by llvm::CloneModule(), and CommitValueTo().
Friends And Related Symbol Documentation
SymbolTableListTraits< GlobalVariable, Module >
friend class SymbolTableListTraits< GlobalVariable, Module > friend
Definition at line 1 of file GlobalVariable.h.
The documentation for this class was generated from the following files:
GlobalVariable.h
Globals.cpp