LLVM: llvm::DWARFAbbreviationDeclaration Class Reference
LLVM API Documentation
llvm::DWARFAbbreviationDeclaration Class Reference
#include <DWARFAbbreviationDeclaration.h>
Public Types
typedef iterator_range< AttributeSpecVector::const_iterator > attr_iterator_range
Public Member Functions
DWARFAbbreviationDeclaration ()
uint32_t getCode () const
uint32_t getTag () const
bool hasChildren () const
attr_iterator_range attributes () const
uint16_t getFormByIndex (uint32_t idx) const
uint32_t findAttributeIndex (uint16_t attr) const
bool extract (DataExtractor Data, uint32_t *OffsetPtr)
void dump (raw_ostream &OS) const
Detailed Description
Definition at line 20 of file DWARFAbbreviationDeclaration.h.
Member Typedef Documentation
attr_iterator_range
typedef iterator_range<AttributeSpecVector::const_iterator> llvm::DWARFAbbreviationDeclaration::attr_iterator_range
Definition at line 40 of file DWARFAbbreviationDeclaration.h.
Constructor & Destructor Documentation
DWARFAbbreviationDeclaration()
DWARFAbbreviationDeclaration::DWARFAbbreviationDeclaration ()
Definition at line 24 of file DWARFAbbreviationDeclaration.cpp.
References clear().
Member Function Documentation
attributes()
attr_iterator_range llvm::DWARFAbbreviationDeclaration::attributes () const inline
Definition at line 42 of file DWARFAbbreviationDeclaration.h.
dump()
void DWARFAbbreviationDeclaration::dump (raw_ostream & OS) const
Definition at line 64 of file DWARFAbbreviationDeclaration.cpp.
References llvm::dwarf::AttributeString(), llvm::format(), llvm::dwarf::FormEncodingString(), getCode(), getTag(), hasChildren(), and llvm::dwarf::TagString().
extract()
bool DWARFAbbreviationDeclaration::extract (DataExtractor Data, uint32_t * OffsetPtr)
Definition at line 29 of file DWARFAbbreviationDeclaration.cpp.
References clear(), llvm::dwarf::DW_CHILDREN_yes, llvm::DataExtractor::getU8(), and llvm::DataExtractor::getULEB128().
Referenced by llvm::DWARFAbbreviationDeclarationSet::extract().
findAttributeIndex()
uint32_t DWARFAbbreviationDeclaration::findAttributeIndex (uint16_t attr) const
Definition at line 91 of file DWARFAbbreviationDeclaration.cpp.
getCode()
uint32_t llvm::DWARFAbbreviationDeclaration::getCode () const inline
Definition at line 35 of file DWARFAbbreviationDeclaration.h.
Referenced by dump(), and llvm::DWARFAbbreviationDeclarationSet::extract().
getFormByIndex()
uint16_t llvm::DWARFAbbreviationDeclaration::getFormByIndex (uint32_t idx) const inline
Definition at line 46 of file DWARFAbbreviationDeclaration.h.
getTag()
uint32_t llvm::DWARFAbbreviationDeclaration::getTag () const inline
Definition at line 36 of file DWARFAbbreviationDeclaration.h.
Referenced by dump().
hasChildren()
bool llvm::DWARFAbbreviationDeclaration::hasChildren () const inline
Definition at line 37 of file DWARFAbbreviationDeclaration.h.
Referenced by dump().
The documentation for this class was generated from the following files:
DWARFAbbreviationDeclaration.h
DWARFAbbreviationDeclaration.cpp