LLVM: llvm::BinOpInit Class Reference
LLVM API Documentation
llvm::BinOpInit Class Reference
#include <Record.h>
Public Types
enum BinaryOp {
ADD , AND , SHL , SRA ,
SRL , LISTCONCAT , STRCONCAT , CONCAT ,
EQ
}
Public Member Functions
OpInit * clone (std::vector< Init * > &Operands) const override
int getNumOperands () const override
Init * getOperand (int i) const override
BinaryOp getOpcode () const
Init * getLHS () const
Init * getRHS () const
Init * Fold (Record *CurRec, MultiClass *CurMultiClass) const override
Init * resolveReferences (Record &R, const RecordVal *RV) const override
std::string getAsString () const override
getAsString - Convert this value to a string form.
Public Member Functions inherited from llvm::OpInit
Init * convertInitializerTo (RecTy *Ty) const override
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
Init * getBit (unsigned Bit) const override
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const override
Init * convertInitListSlice (const std::vector< unsigned > &Elements) const override
RecTy * getFieldType (const std::string &FieldName) const override
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static BinOpInit * get (BinaryOp opc, Init *lhs, Init *rhs, RecTy *Type)
Static Public Member Functions inherited from llvm::OpInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit , IK_FirstTypedInit , IK_BitsInit , IK_DagInit ,
IK_DefInit , IK_FieldInit , IK_IntInit , IK_ListInit ,
IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit , IK_UnOpInit ,
IK_LastOpInit , IK_StringInit , IK_VarInit , IK_VarListElementInit ,
IK_LastTypedInit , IK_UnsetInit , IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::OpInit
OpInit (InitKind K, RecTy *Type)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
BinOpInit - !op (X, Y) - Combine two inits.
Definition at line 938 of file Record.h.
Member Enumeration Documentation
BinaryOp
enum llvm::BinOpInit::BinaryOp
Enumerator
ADD
AND
SHL
SRA
SRL
LISTCONCAT
STRCONCAT
CONCAT
EQ
Definition at line 940 of file Record.h.
Member Function Documentation
classof()
bool llvm::BinOpInit::classof (const Init * I) inline static
Definition at line 953 of file Record.h.
References I, and llvm::Init::IK_BinOpInit.
clone()
OpInit * llvm::BinOpInit::clone (std::vector< Init * > & Operands) const inline override virtual
Implements llvm::OpInit.
Definition at line 960 of file Record.h.
References get(), getOpcode(), llvm::TypedInit::getType(), and Operands.
Fold()
Init * BinOpInit::Fold (Record * CurRec, MultiClass * CurMultiClass) const override virtual
Implements llvm::OpInit.
Definition at line 904 of file Record.cpp.
References ADD, AND, llvm::ListInit::begin(), CONCAT, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::ListInit::end(), EQ, llvm::DagInit::get(), llvm::IntInit::get(), llvm::IntRecTy::get(), llvm::ListInit::get(), llvm::StringInit::get(), llvm::DagInit::getArg(), llvm::DagInit::getArgName(), llvm::DefInit::getDef(), llvm::ListRecTy::getElementType(), llvm::DagInit::getNumArgs(), getOpcode(), llvm::DagInit::getOperator(), llvm::TypedInit::getType(), llvm::IntInit::getValue(), llvm::StringInit::getValue(), LISTCONCAT, llvm_unreachable, llvm::PrintFatalError(), SHL, SRA, SRL, and STRCONCAT.
Referenced by llvm::QualifyName(), and resolveReferences().
get()
BinOpInit * BinOpInit::get (BinaryOp opc, Init * lhs, Init * rhs, RecTy * Type) static
Definition at line 887 of file Record.cpp.
References I.
Referenced by clone(), llvm::DagRecTy::convertValue(), llvm::StringRecTy::convertValue(), llvm::QualifyName(), and resolveReferences().
getAsString()
std::string BinOpInit::getAsString () const override virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 1004 of file Record.cpp.
References ADD, AND, CONCAT, EQ, LISTCONCAT, SHL, SRA, SRL, and STRCONCAT.
getLHS()
Init * llvm::BinOpInit::getLHS () const inline
Definition at line 977 of file Record.h.
Referenced by llvm::DagRecTy::convertValue(), llvm::StringRecTy::convertValue(), and getOperand().
getNumOperands()
int llvm::BinOpInit::getNumOperands () const inline override virtual
Implements llvm::OpInit.
Definition at line 966 of file Record.h.
getOpcode()
BinaryOp llvm::BinOpInit::getOpcode () const inline
Definition at line 976 of file Record.h.
Referenced by clone(), llvm::DagRecTy::convertValue(), llvm::StringRecTy::convertValue(), Fold(), and resolveReferences().
getOperand()
Init * llvm::BinOpInit::getOperand (int i) const inline override virtual
Implements llvm::OpInit.
Definition at line 967 of file Record.h.
References getLHS(), and getRHS().
getRHS()
Init * llvm::BinOpInit::getRHS () const inline
Definition at line 978 of file Record.h.
Referenced by llvm::DagRecTy::convertValue(), llvm::StringRecTy::convertValue(), and getOperand().
resolveReferences()
Init * BinOpInit::resolveReferences (Record & R, const RecordVal * RV) const override virtual
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 995 of file Record.cpp.
References Fold(), get(), getOpcode(), llvm::TypedInit::getType(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
Record.h
Record.cpp