LLVM: llvm::AMDGPUMachineFunction Class Reference
LLVM API Documentation
llvm::AMDGPUMachineFunction Class Reference
#include <AMDGPUMachineFunction.h>
Public Member Functions
AMDGPUMachineFunction (const MachineFunction &MF)
unsigned getShaderType () const
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Public Attributes
std::map< const GlobalValue *, unsigned > LocalMemoryObjects
unsigned LDSSize
Number of bytes in the LDS that are being used.
unsigned ABIArgOffset
Start of implicit kernel args.
unsigned ScratchSize
bool IsKernel
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename Ty>
static Ty * create (BumpPtrAllocator &Allocator, MachineFunction &MF)
Factory function: default behavior is to call new using the supplied allocator.
Detailed Description
Definition at line 21 of file AMDGPUMachineFunction.h.
Constructor & Destructor Documentation
AMDGPUMachineFunction()
AMDGPUMachineFunction::AMDGPUMachineFunction (const MachineFunction & MF)
Definition at line 12 of file AMDGPUMachineFunction.cpp.
References llvm::AttributeSet::FunctionIndex, llvm::AttributeSet::getAttribute(), llvm::MachineFunction::getFunction(), IsKernel, LDSSize, ScratchSize, ShaderTypeAttribute, and true.
Referenced by llvm::R600MachineFunctionInfo::R600MachineFunctionInfo(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
Member Function Documentation
getShaderType()
unsigned llvm::AMDGPUMachineFunction::getShaderType () const inline
Definition at line 36 of file AMDGPUMachineFunction.h.
Referenced by llvm::SIInstrInfo::calculateLDSSpillAddress(), llvm::SIMachineFunctionInfo::getMaximumWorkGroupSize(), llvm::SIRegisterInfo::getPreloadedValue(), llvm::AMDGPUSubtarget::isVGPRSpillingEnabled(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::R600InstrInfo::usesTextureCache(), and llvm::R600InstrInfo::usesVertexCache().
Member Data Documentation
ABIArgOffset
unsigned llvm::AMDGPUMachineFunction::ABIArgOffset
Start of implicit kernel args.
Definition at line 34 of file AMDGPUMachineFunction.h.
Referenced by llvm::R600TargetLowering::LowerFormalArguments(), and llvm::R600TargetLowering::LowerOperation().
IsKernel
bool llvm::AMDGPUMachineFunction::IsKernel
Definition at line 41 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction().
LDSSize
unsigned llvm::AMDGPUMachineFunction::LDSSize
Number of bytes in the LDS that are being used.
Definition at line 31 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction(), llvm::SIInstrInfo::calculateLDSSpillAddress(), and llvm::AMDGPUTargetLowering::LowerGlobalAddress().
LocalMemoryObjects
std::map<const GlobalValue *, unsigned> llvm::AMDGPUMachineFunction::LocalMemoryObjects
A map to keep track of local memory objects and their offsets within the local memory space.
Definition at line 29 of file AMDGPUMachineFunction.h.
Referenced by llvm::AMDGPUTargetLowering::LowerGlobalAddress().
ScratchSize
unsigned llvm::AMDGPUMachineFunction::ScratchSize
Definition at line 40 of file AMDGPUMachineFunction.h.
Referenced by AMDGPUMachineFunction().
The documentation for this class was generated from the following files:
AMDGPUMachineFunction.h
AMDGPUMachineFunction.cpp