LLVM: llvm::PBQP::Vector Class Reference
LLVM API Documentation
llvm::PBQP::Vector Class Reference
PBQP Vector class.
#include <Math.h>
Public Member Functions
Vector (unsigned Length)
Construct a PBQP vector of the given size.
Vector (unsigned Length, PBQPNum InitVal)
Construct a PBQP vector with initializer.
Vector (const Vector &V)
Copy construct a PBQP vector.
Vector (Vector &&V)
Move construct a PBQP vector.
~Vector ()
Destroy this vector, return its memory.
Vector & operator= (const Vector &V)
Copy-assignment operator.
Vector & operator= (Vector &&V)
Move-assignment operator.
bool operator== (const Vector &V) const
Comparison operator.
unsigned getLength () const
Return the length of the vector.
PBQPNum & operator[] (unsigned Index)
Element access.
const PBQPNum & operator[] (unsigned Index) const
Const element access.
Vector & operator+= (const Vector &V)
Add another vector to this one.
Vector & operator-= (const Vector &V)
Subtract another vector from this one.
unsigned minIndex () const
Returns the index of the minimum value in this vector.
Friends
hash_code hash_value (const Vector &V)
Return a hash_value for the given vector.
Detailed Description
PBQP Vector class.
Definition at line 24 of file Math.h.
Constructor & Destructor Documentation
Vector() [1/4]
llvm::PBQP::Vector::Vector (unsigned Length) inline explicit
Construct a PBQP vector of the given size.
Definition at line 29 of file Math.h.
Referenced by hash_value, llvm::PBQP::MDVector< Metadata >::MDVector(), llvm::PBQP::MDVector< Metadata >::MDVector(), operator+=(), operator-=(), operator=(), operator=(), operator==(), Vector(), and Vector().
Vector() [2/4]
llvm::PBQP::Vector::Vector (unsigned Length, PBQPNum InitVal) inline
Construct a PBQP vector with initializer.
Definition at line 36 of file Math.h.
Vector() [3/4]
llvm::PBQP::Vector::Vector (const Vector & V) inline
Copy construct a PBQP vector.
Definition at line 45 of file Math.h.
References Vector().
Vector() [4/4]
llvm::PBQP::Vector::Vector (Vector && V) inline
Move construct a PBQP vector.
Definition at line 53 of file Math.h.
References Vector().
~Vector()
llvm::PBQP::Vector::~Vector () inline
Destroy this vector, return its memory.
Definition at line 60 of file Math.h.
Member Function Documentation
getLength()
unsigned llvm::PBQP::Vector::getLength () const inline
Return the length of the vector.
Definition at line 95 of file Math.h.
Referenced by llvm::PBQP::applyR2(), and llvm::PBQP::RegAlloc::NodeMetadata::setup().
minIndex()
unsigned llvm::PBQP::Vector::minIndex () const inline
Returns the index of the minimum value in this vector.
Definition at line 131 of file Math.h.
operator+=()
Vector & llvm::PBQP::Vector::operator+= (const Vector & V) inline
Add another vector to this one.
Definition at line 115 of file Math.h.
References Vector().
operator-=()
Vector & llvm::PBQP::Vector::operator-= (const Vector & V) inline
Subtract another vector from this one.
Definition at line 123 of file Math.h.
References Vector().
operator=() [1/2]
Vector & llvm::PBQP::Vector::operator= (const Vector & V) inline
Copy-assignment operator.
Definition at line 66 of file Math.h.
References Vector().
operator=() [2/2]
Vector & llvm::PBQP::Vector::operator= (Vector && V) inline
Move-assignment operator.
Definition at line 77 of file Math.h.
References Vector().
operator==()
bool llvm::PBQP::Vector::operator== (const Vector & V) const inline
Comparison operator.
Definition at line 87 of file Math.h.
References Vector().
operator[]() [1/2]
PBQPNum & llvm::PBQP::Vector::operator[] (unsigned Index) inline
Element access.
Definition at line 101 of file Math.h.
operator[]() [2/2]
const PBQPNum & llvm::PBQP::Vector::operator[] (unsigned Index) const inline
Const element access.
Definition at line 108 of file Math.h.
Friends And Related Symbol Documentation
hash_value
hash_code hash_value (const Vector & V) friend
Return a hash_value for the given vector.
Definition at line 142 of file Math.h.
References llvm::hash_combine(), llvm::hash_combine_range(), and Vector().
The documentation for this class was generated from the following file:
Math.h