LLVM: llvm::yaml::SequenceNode Class Reference
LLVM API Documentation
llvm::yaml::SequenceNode Class Reference
Represents a YAML sequence created from either a block sequence for a flow sequence.
#include <YAMLParser.h>
Public Types
enum SequenceType { ST_Block , ST_Flow , ST_Indentless }
typedef basic_collection_iterator< SequenceNode, Node > iterator
Public Types inherited from llvm::yaml::Node
enum NodeKind {
NK_Null , NK_Scalar , NK_KeyValue , NK_Mapping ,
NK_Sequence , NK_Alias
}
Public Member Functions
SequenceNode (std::unique_ptr< Document > &D, StringRef Anchor, StringRef Tag, SequenceType ST)
void increment ()
iterator begin ()
iterator end ()
void skip () override
Public Member Functions inherited from llvm::yaml::Node
Node (unsigned int Type, std::unique_ptr< Document > &, StringRef Anchor, StringRef Tag)
StringRef getAnchor () const
Get the value of the anchor attached to this node. If it does not have one, getAnchor().size() will be 0.
StringRef getRawTag () const
Get the tag as it was written in the document. This does not perform tag resolution.
std::string getVerbatimTag () const
Get the verbatium tag for a given Node. This performs tag resoluton and substitution.
SMRange getSourceRange () const
void setSourceRange (SMRange SR)
Token & peekNext ()
Token getNext ()
Node * parseBlockNode ()
BumpPtrAllocator & getAllocator ()
void setError (const Twine &Message, Token &Location) const
bool failed () const
unsigned int getType () const
void * operator new (size_t Size, BumpPtrAllocator &Alloc, size_t Alignment=16) throw ()
void operator delete (void *Ptr, BumpPtrAllocator &Alloc, size_t Size) throw ()
Static Public Member Functions
static bool classof (const Node *N)
Friends
class basic_collection_iterator< SequenceNode, Node >
template<class T>
T::iterator yaml::begin (T &)
template<class T>
void yaml::skip (T &)
Additional Inherited Members
Protected Member Functions inherited from llvm::yaml::Node
void operator delete (void *) throw ()
virtual ~Node ()
Protected Attributes inherited from llvm::yaml::Node
std::unique_ptr< Document > & Doc
SMRange SourceRange
Detailed Description
Represents a YAML sequence created from either a block sequence for a flow sequence.
This parses the YAML stream as increment() is called.
Example:
Hello
World
Definition at line 390 of file YAMLParser.h.
Member Typedef Documentation
iterator
typedef basic_collection_iterator<SequenceNode, Node> llvm::yaml::SequenceNode::iterator
Definition at line 415 of file YAMLParser.h.
Member Enumeration Documentation
SequenceType
enum llvm::yaml::SequenceNode::SequenceType
Enumerator
ST_Block
ST_Flow
ST_Indentless
Definition at line 394 of file YAMLParser.h.
Constructor & Destructor Documentation
SequenceNode()
llvm::yaml::SequenceNode::SequenceNode (std::unique_ptr< Document > & D, StringRef Anchor, StringRef Tag, SequenceType ST) inline
Definition at line 407 of file YAMLParser.h.
Member Function Documentation
begin()
iterator llvm::yaml::SequenceNode::begin () inline
Definition at line 421 of file YAMLParser.h.
References llvm::yaml::begin().
classof()
bool llvm::yaml::SequenceNode::classof (const Node * N) inline static
Definition at line 427 of file YAMLParser.h.
References N, llvm::yaml::Node::NK_Sequence, and llvm::yaml::Node::Node().
end()
iterator llvm::yaml::SequenceNode::end () inline
Definition at line 423 of file YAMLParser.h.
increment()
void SequenceNode::increment ()
Definition at line 1926 of file YAMLParser.cpp.
References llvm::yaml::Node::failed(), llvm::yaml::Node::getNext(), increment(), llvm::yaml::Node::parseBlockNode(), llvm::yaml::Node::peekNext(), llvm::yaml::Node::setError(), ST_Block, ST_Flow, ST_Indentless, llvm::yaml::Token::TK_BlockEnd, llvm::yaml::Token::TK_BlockEntry, llvm::yaml::Token::TK_DocumentEnd, llvm::yaml::Token::TK_DocumentStart, llvm::yaml::Token::TK_Error, llvm::yaml::Token::TK_FlowEntry, llvm::yaml::Token::TK_FlowSequenceEnd, and llvm::yaml::Token::TK_StreamEnd.
Referenced by increment().
skip()
void llvm::yaml::SequenceNode::skip () inline override virtual
Reimplemented from llvm::yaml::Node.
Definition at line 425 of file YAMLParser.h.
References llvm::yaml::skip().
Friends And Related Symbol Documentation
basic_collection_iterator< SequenceNode, Node >
friend class basic_collection_iterator< SequenceNode, Node > friend
Definition at line 407 of file YAMLParser.h.
References llvm::yaml::Node::NK_Sequence, llvm::yaml::Node::Node(), and true.
yaml::begin
template<class T> T::iterator yaml::begin (T &) friend
References T.
yaml::skip
template<class T> void yaml::skip (T &) friend
References T.
The documentation for this class was generated from the following files:
YAMLParser.h
YAMLParser.cpp