LLVM: llvm::IntelJITEventsWrapper Class Reference
LLVM API Documentation
llvm::IntelJITEventsWrapper Class Reference
#include <IntelJITEventsWrapper.h>
Public Member Functions
bool isAmplifierRunning ()
IntelJITEventsWrapper ()
IntelJITEventsWrapper (NotifyEventPtr NotifyEventImpl, RegisterCallbackExPtr RegisterCallbackExImpl, IsProfilingActivePtr IsProfilingActiveImpl, FinalizeThreadPtr FinalizeThreadImpl, FinalizeProcessPtr FinalizeProcessImpl, GetNewMethodIDPtr GetNewMethodIDImpl)
int iJIT_NotifyEvent (iJIT_JVM_EVENT EventType, void *EventSpecificData)
void iJIT_RegisterCallbackEx (void *UserData, iJIT_ModeChangedEx NewModeCallBackFuncEx)
iJIT_IsProfilingActiveFlags iJIT_IsProfilingActive (void)
unsigned int iJIT_GetNewMethodID (void)
Detailed Description
Definition at line 25 of file IntelJITEventsWrapper.h.
Constructor & Destructor Documentation
IntelJITEventsWrapper() [1/2]
llvm::IntelJITEventsWrapper::IntelJITEventsWrapper () inline
Definition at line 45 of file IntelJITEventsWrapper.h.
References iJIT_GetNewMethodID(), iJIT_IsProfilingActive(), iJIT_NotifyEvent(), and iJIT_RegisterCallbackEx().
IntelJITEventsWrapper() [2/2]
llvm::IntelJITEventsWrapper::IntelJITEventsWrapper (NotifyEventPtr NotifyEventImpl, RegisterCallbackExPtr RegisterCallbackExImpl, IsProfilingActivePtr IsProfilingActiveImpl, FinalizeThreadPtr FinalizeThreadImpl, FinalizeProcessPtr FinalizeProcessImpl, GetNewMethodIDPtr GetNewMethodIDImpl) inline
Definition at line 52 of file IntelJITEventsWrapper.h.
Member Function Documentation
iJIT_GetNewMethodID()
unsigned int llvm::IntelJITEventsWrapper::iJIT_GetNewMethodID (void) inline
Definition at line 87 of file IntelJITEventsWrapper.h.
Referenced by IntelJITEventsWrapper().
iJIT_IsProfilingActive()
iJIT_IsProfilingActiveFlags llvm::IntelJITEventsWrapper::iJIT_IsProfilingActive (void) inline
Definition at line 80 of file IntelJITEventsWrapper.h.
References iJIT_NOTHING_RUNNING.
Referenced by IntelJITEventsWrapper(), and isAmplifierRunning().
iJIT_NotifyEvent()
int llvm::IntelJITEventsWrapper::iJIT_NotifyEvent (iJIT_JVM_EVENT EventType, void * EventSpecificData) inline
Definition at line 66 of file IntelJITEventsWrapper.h.
Referenced by IntelJITEventsWrapper().
iJIT_RegisterCallbackEx()
void llvm::IntelJITEventsWrapper::iJIT_RegisterCallbackEx (void * UserData, iJIT_ModeChangedEx NewModeCallBackFuncEx) inline
Definition at line 73 of file IntelJITEventsWrapper.h.
Referenced by IntelJITEventsWrapper().
isAmplifierRunning()
bool llvm::IntelJITEventsWrapper::isAmplifierRunning () inline
Definition at line 41 of file IntelJITEventsWrapper.h.
References iJIT_IsProfilingActive(), and iJIT_SAMPLING_ON.
The documentation for this class was generated from the following file:
IntelJITEventsWrapper.h