LLVM: llvm::ModuleToFunctionPassAdaptor< FunctionPassT > Class Template Reference
LLVM API Documentation
llvm::ModuleToFunctionPassAdaptor< FunctionPassT > Class Template Reference
Trivial adaptor that maps from a module to its functions.
#include <PassManager.h>
Public Member Functions
ModuleToFunctionPassAdaptor (FunctionPassT Pass)
ModuleToFunctionPassAdaptor (const ModuleToFunctionPassAdaptor &Arg)
ModuleToFunctionPassAdaptor (ModuleToFunctionPassAdaptor &&Arg)
ModuleToFunctionPassAdaptor & operator= (ModuleToFunctionPassAdaptor RHS)
PreservedAnalyses run (Module &M, ModuleAnalysisManager *AM)
Runs the function pass across every function in the module.
Static Public Member Functions
static StringRef name ()
Friends
void swap (ModuleToFunctionPassAdaptor &LHS, ModuleToFunctionPassAdaptor &RHS)
Detailed Description
template<typename FunctionPassT>
class llvm::ModuleToFunctionPassAdaptor< FunctionPassT >
Trivial adaptor that maps from a module to its functions.
Designed to allow composition of a FunctionPass(Manager) and a ModulePassManager. Note that if this pass is constructed with a pointer to a ModuleAnalysisManager it will run the FunctionAnalysisManagerModuleProxy analysis prior to running the function pass over the module to enable a FunctionAnalysisManager to be used within this run safely.
Function passes run within this adaptor can rely on having exclusive access to the function they are run over. They should not read or modify any other functions! Other threads or systems may be manipulating other functions in the module, and so their state should never be relied on. FIXME: Make the above true for all of LLVM's actual passes, some still violate this principle.
Function passes can also read the module containing the function, but they should not modify that module outside of the use lists of various globals. For example, a function pass is not permitted to add functions to the module. FIXME: Make the above true for all of LLVM's actual passes, some still violate this principle.
Definition at line 757 of file IR/PassManager.h.
Constructor & Destructor Documentation
ModuleToFunctionPassAdaptor() [1/3]
template<typename FunctionPassT> llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::ModuleToFunctionPassAdaptor (FunctionPassT Pass) inline explicit
Definition at line 759 of file IR/PassManager.h.
Referenced by ModuleToFunctionPassAdaptor(), ModuleToFunctionPassAdaptor(), operator=(), and swap.
ModuleToFunctionPassAdaptor() [2/3]
template<typename FunctionPassT> llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::ModuleToFunctionPassAdaptor (const ModuleToFunctionPassAdaptor< FunctionPassT > & Arg) inline
Definition at line 763 of file IR/PassManager.h.
References ModuleToFunctionPassAdaptor().
ModuleToFunctionPassAdaptor() [3/3]
template<typename FunctionPassT> llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::ModuleToFunctionPassAdaptor (ModuleToFunctionPassAdaptor< FunctionPassT > && Arg) inline
Definition at line 765 of file IR/PassManager.h.
References ModuleToFunctionPassAdaptor().
Member Function Documentation
name()
template<typename FunctionPassT> StringRef llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::name () inline static
Definition at line 809 of file IR/PassManager.h.
operator=()
template<typename FunctionPassT> ModuleToFunctionPassAdaptor & llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::operator= (ModuleToFunctionPassAdaptor< FunctionPassT > RHS) inline
Definition at line 772 of file IR/PassManager.h.
References ModuleToFunctionPassAdaptor(), and swap.
run()
template<typename FunctionPassT> PreservedAnalyses llvm::ModuleToFunctionPassAdaptor< FunctionPassT >::run (Module & M, ModuleAnalysisManager * AM) inline
Runs the function pass across every function in the module.
Definition at line 778 of file IR/PassManager.h.
References llvm::PreservedAnalyses::all(), llvm::Module::begin(), llvm::Module::end(), llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::getResult(), I, llvm::PreservedAnalyses::intersect(), llvm::detail::AnalysisManagerBase< DerivedT, IRUnitT >::invalidate(), and llvm::PreservedAnalyses::preserve().
Friends And Related Symbol Documentation
swap
template<typename FunctionPassT> void swap (ModuleToFunctionPassAdaptor< FunctionPassT > & LHS, ModuleToFunctionPassAdaptor< FunctionPassT > & RHS) friend
Definition at line 767 of file IR/PassManager.h.
References ModuleToFunctionPassAdaptor(), swap, and std::swap().
Referenced by operator=(), and swap.
The documentation for this class was generated from the following file:
IR/PassManager.h