LLVM: llvm::df_iterator< GraphT, SetType, ExtStorage, GT > Class Template Reference
LLVM API Documentation
llvm::df_iterator< GraphT, SetType, ExtStorage, GT > Class Template Reference
#include <DepthFirstIterator.h>
Public Types
typedef super::pointer pointer
typedef df_iterator< GraphT, SetType, ExtStorage, GT > _Self
Public Member Functions
bool operator== (const _Self &x) const
bool operator!= (const _Self &x) const
pointer operator* () const
NodeType * operator-> () const
_Self & operator++ ()
_Self & skipChildren ()
_Self operator++ (int)
bool nodeVisited (NodeType *Node) const
unsigned getPathLength () const
NodeType * getPath (unsigned n) const
Static Public Member Functions
static _Self begin (const GraphT &G)
static _Self end (const GraphT &G)
static _Self begin (const GraphT &G, SetType &S)
static _Self end (const GraphT &G, SetType &S)
Additional Inherited Members
Public Attributes inherited from llvm::df_iterator_storage< SetType, External >
SetType Visited
Detailed Description
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>>
class llvm::df_iterator< GraphT, SetType, ExtStorage, GT >
Definition at line 66 of file DepthFirstIterator.h.
Member Typedef Documentation
_Self
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> typedef df_iterator<GraphT, SetType, ExtStorage, GT> llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::_Self
Definition at line 132 of file DepthFirstIterator.h.
pointer
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> typedef super::pointer llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::pointer
Definition at line 131 of file DepthFirstIterator.h.
Member Function Documentation
begin() [1/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::begin (const GraphT & G) inline static
Definition at line 135 of file DepthFirstIterator.h.
Referenced by llvm::df_begin(), llvm::df_ext_begin(), llvm::idf_begin(), and llvm::idf_ext_begin().
begin() [2/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::begin (const GraphT & G, SetType & S) inline static
Definition at line 141 of file DepthFirstIterator.h.
end() [1/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::end (const GraphT & G) inline static
Definition at line 138 of file DepthFirstIterator.h.
Referenced by llvm::df_end(), llvm::df_ext_end(), llvm::idf_end(), and llvm::idf_ext_end().
end() [2/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::end (const GraphT & G, SetType & S) inline static
Definition at line 144 of file DepthFirstIterator.h.
getPath()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> NodeType * llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::getPath (unsigned n) const inline
getPath - Return the n'th node in the path from the entry node to the current node.
Definition at line 193 of file DepthFirstIterator.h.
getPathLength()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> unsigned llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::getPathLength () const inline
getPathLength - Return the length of the path from the entry node to the current node, counting both nodes.
Definition at line 189 of file DepthFirstIterator.h.
nodeVisited()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::nodeVisited (NodeType * Node) const inline
Definition at line 183 of file DepthFirstIterator.h.
operator!=()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator!= (const _Self & x) const inline
Definition at line 149 of file DepthFirstIterator.h.
operator*()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> pointer llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator* () const inline
Definition at line 151 of file DepthFirstIterator.h.
Referenced by llvm::RegionBase< Tr >::block_iterator_wrapper< false >::operator*(), and operator->().
operator++() [1/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self & llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator++ () inline
Definition at line 161 of file DepthFirstIterator.h.
operator++() [2/2]
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator++ (int) inline
Definition at line 175 of file DepthFirstIterator.h.
operator->()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> NodeType * llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator-> () const inline
Definition at line 159 of file DepthFirstIterator.h.
operator==()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> bool llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::operator== (const _Self & x) const inline
Definition at line 146 of file DepthFirstIterator.h.
Referenced by operator!=().
skipChildren()
template<class GraphT, class SetType = llvm::SmallPtrSet<typename GraphTraits<GraphT>::NodeType*, 8>, bool ExtStorage = false, class GT = GraphTraits<GraphT>> _Self & llvm::df_iterator< GraphT, SetType, ExtStorage, GT >::skipChildren () inline
Definition at line 168 of file DepthFirstIterator.h.
The documentation for this class was generated from the following file:
DepthFirstIterator.h