LLVM: llvm::SparcFrameLowering Class Reference
LLVM API Documentation
llvm::SparcFrameLowering Class Reference
#include <SparcFrameLowering.h>
Public Member Functions
SparcFrameLowering (const SparcSubtarget &ST)
void emitPrologue (MachineFunction &MF) const override
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
bool hasReservedCallFrame (const MachineFunction &MF) const override
bool hasFP (const MachineFunction &MF) const override
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS=nullptr) const override
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
unsigned getStackAlignment () const
unsigned getTransientStackAlignment () const
bool isStackRealignable () const
int getOffsetOfLocalArea () const
virtual bool isFPCloseToIncomingSP () const
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
virtual bool targetHandlesStackFrameRounding () const
virtual void adjustForSegmentedStacks (MachineFunction &MF) const
virtual void adjustForHiPEPrologue (MachineFunction &MF) const
virtual void adjustForFrameAllocatePrologue (MachineFunction &MF) const
virtual bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
virtual int getFrameIndexOffset (const MachineFunction &MF, int FI) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
virtual int getFrameIndexReferenceFromSP (const MachineFunction &MF, int FI, unsigned &FrameReg) const
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Detailed Description
Definition at line 23 of file SparcFrameLowering.h.
Constructor & Destructor Documentation
SparcFrameLowering()
SparcFrameLowering::SparcFrameLowering (const SparcSubtarget & ST) explicit
Definition at line 36 of file SparcFrameLowering.cpp.
References is64Bit(), llvm::TargetFrameLowering::StackGrowsDown, and llvm::TargetFrameLowering::TargetFrameLowering().
Member Function Documentation
eliminateCallFramePseudoInstr()
void SparcFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them). It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 135 of file SparcFrameLowering.cpp.
References llvm::MachineBasicBlock::erase(), hasReservedCallFrame(), and I.
emitEpilogue()
void SparcFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 151 of file SparcFrameLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::SparcMachineFunctionInfo::isLeafProc(), and TII.
emitPrologue()
void SparcFrameLowering::emitPrologue (MachineFunction & MF) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 85 of file SparcFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineModuleInfo::addFrameInst(), llvm::BuildMI(), llvm::TargetOpcode::CFI_INSTRUCTION, llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createRegister(), llvm::MCCFIInstruction::createWindowSave(), llvm::MachineFunction::front(), llvm::MachineModuleInfo::getContext(), llvm::MachineInstr::getDebugLoc(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getMMI(), llvm::MCContext::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::SparcMachineFunctionInfo::isLeafProc(), and TII.
hasFP()
bool SparcFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register. For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 184 of file SparcFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), and llvm::TargetMachine::Options.
hasReservedCallFrame()
bool SparcFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function. This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 176 of file SparcFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by eliminateCallFramePseudoInstr().
processFunctionBeforeCalleeSavedScan()
void SparcFrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 252 of file SparcFrameLowering.cpp.
References DisableLeafProc, llvm::MachineFunction::getInfo(), and llvm::SparcMachineFunctionInfo::setLeafProc().
The documentation for this class was generated from the following files:
SparcFrameLowering.h
SparcFrameLowering.cpp