LLVM: llvm::DIImportedEntity Class Reference
LLVM API Documentation
llvm::DIImportedEntity Class Reference
An imported module (C++ using directive or similar).
#include <DebugInfo.h>
Public Member Functions
DIImportedEntity (const MDNode *N)
DIScope getContext () const
DIScopeRef getEntity () const
unsigned getLineNumber () const
StringRef getName () const
bool Verify () const
Public Member Functions inherited from llvm::DIDescriptor
DIDescriptor (const MDNode *N=nullptr)
bool Verify () const
MDNode * get () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
StringRef getHeader () const
size_t getNumHeaderFields () const
StringRef getHeaderField (unsigned Index) const
template<class T>
T getHeaderFieldAs (unsigned Index) const
uint16_t getTag () const
bool isDerivedType () const
bool isCompositeType () const
bool isSubroutineType () const
bool isBasicType () const
bool isVariable () const
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
bool isCompileUnit () const
bool isNameSpace () const
bool isLexicalBlockFile () const
bool isLexicalBlock () const
bool isSubrange () const
bool isEnumerator () const
bool isType () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
bool isImportedEntity () const
bool isExpression () const
void print (raw_ostream &OS) const
void dump () const
void replaceAllUsesWith (LLVMContext &VMContext, DIDescriptor D)
Replace all uses of debug info referenced by this descriptor.
void replaceAllUsesWith (MDNode *D)
Friends
class DIDescriptor
Additional Inherited Members
Public Types inherited from llvm::DIDescriptor
enum {
FlagAccessibility = 1 << 0 | 1 << 1 , FlagPrivate = 1 , FlagProtected = 2 , FlagPublic = 3 ,
FlagFwdDecl = 1 << 2 , FlagAppleBlock = 1 << 3 , FlagBlockByrefStruct = 1 << 4 , FlagVirtual = 1 << 5 ,
FlagArtificial = 1 << 6 , FlagExplicit = 1 << 7 , FlagPrototyped = 1 << 8 , FlagObjcClassComplete = 1 << 9 ,
FlagObjectPointer = 1 << 10 , FlagVector = 1 << 11 , FlagStaticMember = 1 << 12 , FlagIndirectVariable = 1 << 13 ,
FlagLValueReference = 1 << 14 , FlagRValueReference = 1 << 15
}
Accessibility flags.
Protected Member Functions inherited from llvm::DIDescriptor
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy>
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
template<>
DITypeRef getFieldAs (unsigned Elt) const
Protected Attributes inherited from llvm::DIDescriptor
const MDNode * DbgNode
Detailed Description
An imported module (C++ using directive or similar).
Definition at line 976 of file DebugInfo.h.
Constructor & Destructor Documentation
DIImportedEntity()
llvm::DIImportedEntity::DIImportedEntity (const MDNode * N) inline explicit
Definition at line 981 of file DebugInfo.h.
References DIDescriptor, and N.
Member Function Documentation
getContext()
DIScope llvm::DIImportedEntity::getContext () const inline
Definition at line 982 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
Referenced by llvm::DwarfDebug::beginModule().
getEntity()
DIScopeRef llvm::DIImportedEntity::getEntity () const inline
Definition at line 983 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
Referenced by llvm::DebugInfoFinder::processModule().
getLineNumber()
unsigned llvm::DIImportedEntity::getLineNumber () const inline
Definition at line 984 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
getName()
StringRef llvm::DIImportedEntity::getName () const inline
Definition at line 985 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
Verify()
bool DIImportedEntity::Verify () const
Definition at line 643 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, llvm::DIDescriptor::getNumHeaderFields(), and llvm::DIDescriptor::isImportedEntity().
Referenced by createImportedModule(), and llvm::DIDescriptor::Verify().
Friends And Related Symbol Documentation
DIDescriptor
friend class DIDescriptor friend
Definition at line 977 of file DebugInfo.h.
References DIDescriptor.
Referenced by DIDescriptor, and DIImportedEntity().
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp