LLVM: llvm::AArch64SelectionDAGInfo Class Reference
LLVM API Documentation
llvm::AArch64SelectionDAGInfo Class Reference
#include <AArch64SelectionDAGInfo.h>
Public Member Functions
AArch64SelectionDAGInfo (const DataLayout *DL)
~AArch64SelectionDAGInfo ()
SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const override
Public Member Functions inherited from llvm::TargetSelectionDAGInfo
TargetSelectionDAGInfo (const DataLayout *DL)
virtual ~TargetSelectionDAGInfo ()
virtual SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
Additional Inherited Members
Protected Member Functions inherited from llvm::TargetSelectionDAGInfo
const DataLayout * getDataLayout () const
Detailed Description
Definition at line 21 of file AArch64SelectionDAGInfo.h.
Constructor & Destructor Documentation
AArch64SelectionDAGInfo()
AArch64SelectionDAGInfo::AArch64SelectionDAGInfo (const DataLayout * DL) explicit
Definition at line 19 of file AArch64SelectionDAGInfo.cpp.
~AArch64SelectionDAGInfo()
AArch64SelectionDAGInfo::~AArch64SelectionDAGInfo ()
Definition at line 22 of file AArch64SelectionDAGInfo.cpp.
Member Function Documentation
EmitTargetCodeForMemset()
SDValue AArch64SelectionDAGInfo::EmitTargetCodeForMemset (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const override virtual
EmitTargetCodeForMemset - Emit target-specific code that performs a memset. This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 24 of file AArch64SelectionDAGInfo.cpp.
References Align, llvm::CallingConv::C, llvm::dyn_cast(), llvm::SelectionDAG::getContext(), llvm::TargetSelectionDAGInfo::getDataLayout(), llvm::SelectionDAG::getExternalSymbol(), llvm::DataLayout::getIntPtrType(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetMachine::getSubtarget(), llvm::SelectionDAG::getTarget(), llvm::Type::getVoidTy(), llvm::ConstantSDNode::getZExtValue(), llvm::TargetLowering::LowerCallTo(), llvm::TargetLowering::ArgListEntry::Node, llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setChain(), llvm::TargetLowering::CallLoweringInfo::setDebugLoc(), llvm::TargetLowering::CallLoweringInfo::setDiscardResult(), and llvm::TargetLowering::ArgListEntry::Ty.
The documentation for this class was generated from the following files:
AArch64SelectionDAGInfo.h
AArch64SelectionDAGInfo.cpp