LLVM: llvm::PPCTargetLowering Class Reference
LLVM API Documentation
llvm::PPCTargetLowering Class Reference
#include <PPCISelLowering.h>
Public Member Functions
PPCTargetLowering (const PPCTargetMachine &TM)
const char * getTargetNodeName (unsigned Opcode) const override
MVT getScalarShiftAmountTy (EVT LHSTy) const override
bool isCheapToSpeculateCttz () const override
Return true if it is cheap to speculate a call to intrinsic cttz.
bool isCheapToSpeculateCtlz () const override
Return true if it is cheap to speculate a call to intrinsic ctlz.
EVT getSetCCResultType (LLVMContext &Context, EVT VT) const override
getSetCCResultType - Return the ISD::SETCC ValueType
bool enableAggressiveFMAFusion (EVT VT) const override
bool getPreIndexedAddressParts (SDNode *N, SDValue &Base, SDValue &Offset, ISD::MemIndexedMode &AM, SelectionDAG &DAG) const override
bool SelectAddressRegReg (SDValue N, SDValue &Base, SDValue &Index, SelectionDAG &DAG) const
bool SelectAddressRegImm (SDValue N, SDValue &Disp, SDValue &Base, SelectionDAG &DAG, bool Aligned) const
bool SelectAddressRegRegOnly (SDValue N, SDValue &Base, SDValue &Index, SelectionDAG &DAG) const
Sched::Preference getSchedulingPreference (SDNode *N) const override
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
void ReplaceNodeResults (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
SDValue expandVSXLoadForLE (SDNode *N, DAGCombinerInfo &DCI) const
SDValue expandVSXStoreForLE (SDNode *N, DAGCombinerInfo &DCI) const
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
SDValue BuildSDIVPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, std::vector< SDNode * > *Created) const override
unsigned getRegisterByName (const char *RegName, EVT VT) const override
void computeKnownBitsForTargetNode (const SDValue Op, APInt &KnownZero, APInt &KnownOne, const SelectionDAG &DAG, unsigned Depth=0) const override
unsigned getPrefLoopAlignment (MachineLoop *ML) const override
Return the preferred loop alignment.
Instruction * emitLeadingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const override
Instruction * emitTrailingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const override
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *MBB) const override
MachineBasicBlock * EmitAtomicBinary (MachineInstr *MI, MachineBasicBlock *MBB, bool is64Bit, unsigned BinOpcode) const
MachineBasicBlock * EmitPartwordAtomicBinary (MachineInstr *MI, MachineBasicBlock *MBB, bool is8bit, unsigned Opcode) const
MachineBasicBlock * emitEHSjLjSetJmp (MachineInstr *MI, MachineBasicBlock *MBB) const
MachineBasicBlock * emitEHSjLjLongJmp (MachineInstr *MI, MachineBasicBlock *MBB) const
ConstraintType getConstraintType (const std::string &Constraint) const override
ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const override
std::pair< unsigned, const TargetRegisterClass * > getRegForInlineAsmConstraint (const std::string &Constraint, MVT VT) const override
unsigned getByValTypeAlignment (Type *Ty) const override
void LowerAsmOperandForConstraint (SDValue Op, std::string &Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const override
bool isLegalAddressingMode (const AddrMode &AM, Type *Ty) const override
bool isLegalICmpImmediate (int64_t Imm) const override
bool isLegalAddImmediate (int64_t Imm) const override
bool isTruncateFree (Type *Ty1, Type *Ty2) const override
bool isTruncateFree (EVT VT1, EVT VT2) const override
bool isZExtFree (SDValue Val, EVT VT2) const override
bool isFPExtFree (EVT VT) const override
bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const override
Returns true if it is beneficial to convert a load of a constant to just the constant itself.
bool isOffsetFoldingLegal (const GlobalAddressSDNode *GA) const override
bool getTgtMemIntrinsic (IntrinsicInfo &Info, const CallInst &I, unsigned Intrinsic) const override
EVT getOptimalMemOpType (uint64_t Size, unsigned DstAlign, unsigned SrcAlign, bool IsMemset, bool ZeroMemset, bool MemcpyStrSrc, MachineFunction &MF) const override
bool allowsMisalignedMemoryAccesses (EVT VT, unsigned AddrSpace, unsigned Align=1, bool *Fast=nullptr) const override
bool isFMAFasterThanFMulAndFAdd (EVT VT) const override
const MCPhysReg * getScratchRegisters (CallingConv::ID CC) const override
bool shouldExpandBuildVectorWithShuffles (EVT VT, unsigned DefinedValues) const override
FastISel * createFastISel (FunctionLoweringInfo &FuncInfo, const TargetLibraryInfo *LibInfo) const override
bool functionArgumentNeedsConsecutiveRegisters (Type *Ty, CallingConv::ID CallConv, bool isVarArg) const override
Returns true if an argument of type Ty needs to be passed in a contiguous block of registers in calling convention CallConv.
Public Member Functions inherited from llvm::TargetLowering
TargetLowering (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
virtual bool getPostIndexedAddressParts (SDNode *, SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
virtual unsigned getJumpTableEncoding () const
virtual const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *, const MachineBasicBlock *, unsigned, MCContext &) const
virtual SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const
Returns relocation base for the given PIC jumptable.
virtual const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const
bool isInTailCallPosition (SelectionDAG &DAG, SDNode *Node, SDValue &Chain) const
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, SDLoc DL) const
std::pair< SDValue, SDValue > makeLibCall (SelectionDAG &DAG, RTLIB::Libcall LC, EVT RetVT, const SDValue *Ops, unsigned NumOps, bool isSigned, SDLoc dl, bool doesNotReturn=false, bool isReturnValueUsed=true) const
Returns a pair of (return value, chain).
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedMask, APInt &KnownZero, APInt &KnownOne, TargetLoweringOpt &TLO, unsigned Depth=0) const
virtual unsigned ComputeNumSignBitsForTargetNode (SDValue Op, const SelectionDAG &DAG, unsigned Depth=0) const
bool isConstTrueVal (const SDNode *N) const
bool isConstFalseVal (const SDNode *N) const
SDValue SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo &DCI, SDLoc dl) const
virtual bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const
virtual bool isDesirableToCommuteWithShift (const SDNode *N) const
Return true if it is profitable to move a following shift through this.
virtual bool isTypeDesirableForOp (unsigned, EVT VT) const
virtual bool isDesirableToTransformToIntegerOp (unsigned, EVT) const
virtual bool IsDesirableToPromoteOp (SDValue, EVT &) const
std::pair< SDValue, SDValue > LowerCallTo (CallLoweringInfo &CLI) const
virtual void HandleByVal (CCState *, unsigned &, unsigned) const
Target-specific cleanup for formal ByVal parameters.
virtual bool isUsedByReturnOnly (SDNode *, SDValue &) const
virtual bool mayBeEmittedAsTailCall (CallInst *) const
virtual const char * getClearCacheBuiltinName () const
virtual EVT getTypeForExtArgOrReturn (LLVMContext &Context, EVT VT, ISD::NodeType) const
virtual SDValue prepareVolatileOrAtomicLoad (SDValue Chain, SDLoc DL, SelectionDAG &DAG) const
virtual void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const
bool verifyReturnAddressArgumentIsConstant (SDValue Op, SelectionDAG &DAG) const
virtual bool ExpandInlineAsm (CallInst *) const
virtual AsmOperandInfoVector ParseConstraints (ImmutableCallSite CS) const
virtual ConstraintWeight getMultipleConstraintMatchWeight (AsmOperandInfo &info, int maIndex) const
virtual void ComputeConstraintToUse (AsmOperandInfo &OpInfo, SDValue Op, SelectionDAG *DAG=nullptr) const
virtual const char * LowerXConstraint (EVT ConstraintVT) const
SDValue BuildExactSDIV (SDValue Op1, SDValue Op2, SDLoc dl, SelectionDAG &DAG) const
Given an exact SDIV by a constant, create a multiplication with the multiplicative inverse of the constant.
SDValue BuildSDIV (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, bool IsAfterLegalization, std::vector< SDNode * > *Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
SDValue BuildUDIV (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, bool IsAfterLegalization, std::vector< SDNode * > *Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
bool expandMUL (SDNode *N, SDValue &Lo, SDValue &Hi, EVT HiLoVT, SelectionDAG &DAG, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
bool expandFP_TO_SINT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
virtual void AdjustInstrPostInstrSelection (MachineInstr *MI, SDNode *Node) const
virtual bool useLoadStackGuardNode () const
virtual bool shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const
Returns true if arguments should be sign-extended in lib calls.
Public Member Functions inherited from llvm::TargetLoweringBase
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
virtual ~TargetLoweringBase ()
const TargetMachine & getTargetMachine () const
const DataLayout * getDataLayout () const
const TargetLoweringObjectFile & getObjFileLowering () const
bool isBigEndian () const
bool isLittleEndian () const
virtual MVT getPointerTy (uint32_t=0) const
unsigned getPointerSizeInBits (uint32_t AS=0) const
unsigned getPointerTypeSizeInBits (Type *Ty) const
EVT getShiftAmountTy (EVT LHSTy) const
virtual MVT getVectorIdxTy () const
bool isSelectExpensive () const
Return true if the select operation is expensive for this target.
virtual bool isSelectSupported (SelectSupportKind) const
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (EVT VT) const
Return the preferred vector type legalization action.
bool isIntDivCheap () const
bool isFsqrtCheap () const
Return true if sqrt(x) is as cheap or cheaper than 1 / rsqrt(x)
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
bool isPow2SDivCheap () const
Return true if pow2 sdiv is cheaper than a chain of sra/srl/add/sra.
bool isJumpExpensive () const
bool isPredictableSelectExpensive () const
virtual bool isLoadBitCastBeneficial (EVT, EVT) const
bool isMaskAndBranchFoldingLegal () const
Return if the target supports combining a chain like:
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
bool hasFloatingPointExceptions () const
Return true if target supports floating point exceptions.
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
BooleanContent getBooleanContents (EVT Type) const
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual const TargetRegisterClass * getRegClassFor (MVT VT) const
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
virtual uint8_t getRepRegClassCostFor (MVT VT) const
bool isTypeLegal (EVT VT) const
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
LegalizeTypeAction getTypeAction (MVT VT) const
EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
virtual bool isFPImmLegal (const APFloat &, EVT) const
virtual bool isShuffleMaskLegal (const SmallVectorImpl< int > &, EVT) const
virtual bool canOpTrap (unsigned Op, EVT VT) const
virtual bool isVectorClearMaskLegal (const SmallVectorImpl< int > &, EVT) const
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT) const
bool isOperationLegalOrPromote (unsigned Op, EVT VT) const
bool isOperationExpand (unsigned Op, EVT VT) const
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
EVT getValueType (Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
unsigned getNumRegisters (LLVMContext &Context, EVT VT) const
virtual bool ShouldShrinkFPConstant (EVT) const
virtual bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const
bool hasBigEndianPartOrdering (EVT VT) const
bool hasTargetDAGCombine (ISD::NodeType NT) const
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool isSafeMemOpType (MVT) const
bool usesUnderscoreSetJmp () const
Determine if we should use _setjmp or setjmp to implement llvm.setjmp.
bool usesUnderscoreLongJmp () const
Determine if we should use _longjmp or longjmp to implement llvm.longjmp.
int getMinimumJumpTableEntries () const
unsigned getStackPointerRegisterToSaveRestore () const
unsigned getExceptionPointerRegister () const
unsigned getExceptionSelectorRegister () const
unsigned getJumpBufSize () const
unsigned getJumpBufAlignment () const
unsigned getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
unsigned getMinFunctionAlignment () const
Return the minimum function alignment.
unsigned getPrefFunctionAlignment () const
Return the preferred function alignment.
bool getInsertFencesForAtomic () const
virtual bool getStackCookieLocation (unsigned &, unsigned &) const
virtual unsigned getMaximalGlobalOffset () const
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast between SrcAS and DestAS is a noop.
virtual bool shouldExpandAtomicStoreInIR (StoreInst *SI) const
virtual bool shouldExpandAtomicLoadInIR (LoadInst *LI) const
virtual bool shouldExpandAtomicRMWInIR (AtomicRMWInst *RMWI) const
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
virtual void resetOperationActions ()
Reset the operation actions based on target options.
virtual bool GetAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value * > &, Type *&) const
virtual int getScalingFactorCost (const AddrMode &AM, Type *Ty) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
virtual bool allowTruncateForTailCall (Type *, Type *) const
virtual bool isZExtFree (Type *, Type *) const
virtual bool isZExtFree (EVT, EVT) const
virtual bool hasPairedLoad (Type *, unsigned &) const
virtual bool hasPairedLoad (EVT, unsigned &) const
virtual bool isFNegFree (EVT VT) const
virtual bool isFAbsFree (EVT VT) const
virtual bool isNarrowingProfitable (EVT, EVT) const
virtual bool isExtractSubvectorCheap (EVT ResVT, unsigned Index) const
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
LegalizeKind getTypeConversion (LLVMContext &Context, EVT VT) const
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
std::pair< unsigned, MVT > getTypeLegalizationCost (Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
virtual bool hasLoadLinkedStoreConditional () const
virtual Value * emitLoadLinked (IRBuilder<> &Builder, Value *Addr, AtomicOrdering Ord) const
virtual Value * emitStoreConditional (IRBuilder<> &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const
Additional Inherited Members
Public Types inherited from llvm::TargetLowering
enum ConstraintType {
C_Register , C_RegisterClass , C_Memory , C_Other ,
C_Unknown
}
enum ConstraintWeight {
CW_Invalid = -1 , CW_Okay = 0 , CW_Good = 1 , CW_Better = 2 ,
CW_Best = 3 , CW_SpecificReg = CW_Okay , CW_Register = CW_Good , CW_Memory = CW_Better ,
CW_Constant = CW_Best , CW_Default = CW_Okay
}
typedef std::vector< ArgListEntry > ArgListTy
typedef std::vector< AsmOperandInfo > AsmOperandInfoVector
Public Types inherited from llvm::TargetLoweringBase
enum LegalizeAction { Legal , Promote , Expand , Custom }
enum LegalizeTypeAction {
TypeLegal , TypePromoteInteger , TypeExpandInteger , TypeSoftenFloat ,
TypeExpandFloat , TypeScalarizeVector , TypeSplitVector , TypeWidenVector
}
enum BooleanContent { UndefinedBooleanContent , ZeroOrOneBooleanContent , ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect , ScalarCondVectorVal , VectorMaskSelect }
Enum that describes what type of support for selects the target has.
typedef std::pair< LegalizeTypeAction, EVT > LegalizeKind
Static Public Member Functions inherited from llvm::TargetLoweringBase
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions inherited from llvm::TargetLoweringBase
void initActions ()
Initialize all of the actions to default values.
void setBooleanContents (BooleanContent Ty)
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
void setBooleanVectorContents (BooleanContent Ty)
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setUseUnderscoreSetJmp (bool Val)
void setUseUnderscoreLongJmp (bool Val)
void setMinimumJumpTableEntries (int Val)
void setStackPointerRegisterToSaveRestore (unsigned R)
void setExceptionPointerRegister (unsigned R)
void setExceptionSelectorRegister (unsigned R)
void setSelectIsExpensive (bool isExpensive=true)
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
void setHasExtractBitsInsn (bool hasExtractInsn=true)
void setJumpIsExpensive (bool isExpensive=true)
void setIntDivIsCheap (bool isCheap=true)
void setFsqrtIsCheap (bool isCheap=true)
void setHasFloatingPointExceptions (bool FPExceptions=true)
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void setPow2SDivIsCheap (bool isCheap=true)
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
void clearRegisterClasses ()
Remove all register classes.
void clearOperationActions ()
Remove all operation actions.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (MVT VT) const
void computeRegisterProperties ()
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
void setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action)
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
void setTargetDAGCombine (ISD::NodeType NT)
void setJumpBufSize (unsigned Size)
Set the target's required jmp_buf buffer size (in bytes); default is 200.
void setJumpBufAlignment (unsigned Align)
void setMinFunctionAlignment (unsigned Align)
Set the target's minimum function alignment (in log2(bytes))
void setPrefFunctionAlignment (unsigned Align)
void setPrefLoopAlignment (unsigned Align)
void setMinStackArgumentAlignment (unsigned Align)
Set the minimum stack alignment of an argument (in log2(bytes)).
void setInsertFencesForAtomic (bool fence)
bool isLegalRC (const TargetRegisterClass *RC) const
MachineBasicBlock * emitPatchPoint (MachineInstr *MI, MachineBasicBlock *MBB) const
Protected Attributes inherited from llvm::TargetLoweringBase
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
unsigned MaxStoresPerMemcpy
Specify maximum bytes of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
unsigned MaxStoresPerMemmove
Specify maximum bytes of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
bool PredictableSelectIsExpensive
bool MaskAndBranchFoldingIsLegal
bool EnableExtLdPromotion
Detailed Description
Definition at line 378 of file PPCISelLowering.h.
Constructor & Destructor Documentation
PPCTargetLowering()
PPCTargetLowering::PPCTargetLowering (const PPCTargetMachine & TM) explicit
Definition at line 60 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLoweringBase::AddPromotedToType(), llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::ADJUST_TRAMPOLINE, llvm::ISD::AND, ANDIGlueBug, llvm::ISD::ANY_EXTEND, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_STORE, llvm::ISD::BITCAST, llvm::ISD::BlockAddress, llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BRCOND, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::ISD::ConstantPool, llvm::RTLIB::COS_PPCF128, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::TargetLoweringBase::Custom, llvm::PPC::DIR_970, llvm::PPC::DIR_A2, llvm::PPC::DIR_E500mc, llvm::PPC::DIR_E5500, llvm::PPC::DIR_PWR4, llvm::PPC::DIR_PWR5, llvm::PPC::DIR_PWR5X, llvm::PPC::DIR_PWR6, llvm::PPC::DIR_PWR6X, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_SJLJ_LONGJMP, llvm::ISD::EH_SJLJ_SETJMP, llvm::RTLIB::EXP2_PPCF128, llvm::RTLIB::EXP_PPCF128, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FLT_ROUNDS_, llvm::ISD::FMA, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP_ROUND_INREG, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::FSQRT, llvm::ISD::FTRUNC, llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::Sched::Hybrid, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INIT_TRAMPOLINE, llvm::ISD::INSERT_VECTOR_ELT, llvm::MVT::integer_valuetypes(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::JumpTable, llvm::TargetLoweringBase::Legal, llvm::ISD::LOAD, llvm::RTLIB::LOG10_PPCF128, llvm::RTLIB::LOG2_PPCF128, llvm::RTLIB::LOG_PPCF128, llvm::TargetLoweringBase::MaxStoresPerMemcpy, llvm::TargetLoweringBase::MaxStoresPerMemcpyOptSize, llvm::TargetLoweringBase::MaxStoresPerMemmove, llvm::TargetLoweringBase::MaxStoresPerMemmoveOptSize, llvm::TargetLoweringBase::MaxStoresPerMemset, llvm::TargetLoweringBase::MaxStoresPerMemsetOptSize, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::ISD::OR, llvm::MVT::Other, llvm::RTLIB::POW_PPCF128, llvm::MVT::ppcf128, llvm::ISD::PRE_INC, llvm::ISD::PREFETCH, llvm::TargetLoweringBase::Promote, llvm::ISD::READCYCLECOUNTER, llvm::RTLIB::REM_PPCF128, llvm::ISD::ROTR, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::TargetLoweringBase::setBooleanContents(), llvm::TargetLoweringBase::setBooleanVectorContents(), llvm::ISD::SETCC, llvm::TargetLoweringBase::setCondCodeAction(), llvm::TargetLoweringBase::setExceptionPointerRegister(), llvm::TargetLoweringBase::setExceptionSelectorRegister(), llvm::TargetLoweringBase::setHasMultipleConditionRegisters(), llvm::TargetLoweringBase::setIndexedLoadAction(), llvm::TargetLoweringBase::setIndexedStoreAction(), llvm::TargetLoweringBase::setInsertFencesForAtomic(), llvm::TargetLoweringBase::setLibcallName(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setMinFunctionAlignment(), llvm::TargetLoweringBase::setMinStackArgumentAlignment(), llvm::ISD::SETO, llvm::ISD::SETOGE, llvm::ISD::SETOLE, llvm::ISD::SETONE, llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setPrefFunctionAlignment(), llvm::TargetLoweringBase::setPrefLoopAlignment(), llvm::TargetLoweringBase::setSchedulingPreference(), llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SETUEQ, llvm::ISD::SETUGT, llvm::ISD::SETULT, llvm::ISD::SETUO, llvm::TargetLoweringBase::setUseUnderscoreLongJmp(), llvm::TargetLoweringBase::setUseUnderscoreSetJmp(), llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::RTLIB::SHL_I128, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::RTLIB::SIN_PPCF128, llvm::ISD::SINT_TO_FP, llvm::ISD::SMUL_LOHI, llvm::Sched::Source, llvm::RTLIB::SQRT_PPCF128, llvm::ISD::SRA, llvm::RTLIB::SRA_I128, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::ISD::SRL, llvm::RTLIB::SRL_I128, llvm::ISD::SRL_PARTS, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::TRAP, llvm::ISD::TRUNCATE, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMUL_LOHI, llvm::ISD::UREM, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VASTART, llvm::ISD::VECTOR_SHUFFLE, llvm::MVT::vector_valuetypes(), llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, and llvm::ISD::ZEXTLOAD.
Member Function Documentation
allowsMisalignedMemoryAccesses()
bool PPCTargetLowering::allowsMisalignedMemoryAccesses (EVT VT, unsigned AddrSpace, unsigned Align = 1, bool * Fast = nullptr) const override virtual
Is unaligned memory access allowed for the given type, and is it fast relative to software emulation.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9857 of file PPCISelLowering.cpp.
References DisablePPCUnaligned, llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), llvm::MVT::isVector(), llvm::MVT::ppcf128, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, and llvm::MVT::v4i32.
BuildSDIVPow2()
SDValue PPCTargetLowering::BuildSDIVPow2 (SDNode * N, const APInt & Divisor, SelectionDAG & DAG, std::vector< SDNode * > * Created) const override virtual
Reimplemented from llvm::TargetLowering.
Definition at line 9224 of file PPCISelLowering.cpp.
References llvm::countTrailingZeros(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::MVT::i64, llvm::APInt::isPowerOf2(), N, llvm::PPCISD::SRA_ADDZE, and llvm::ISD::SUB.
computeKnownBitsForTargetNode()
void PPCTargetLowering::computeKnownBitsForTargetNode (const SDValue Op, APInt & KnownZero, APInt & KnownOne, const SelectionDAG & DAG, unsigned Depth = 0) const override virtual
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
computeKnownBitsForTargetNode - Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
Reimplemented from llvm::TargetLowering.
Definition at line 9259 of file PPCISelLowering.cpp.
References llvm::cast(), llvm::APInt::getBitWidth(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MVT::i16, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::PPCISD::LBRX, llvm::Intrinsic::ppc_altivec_vcmpbfp_p, llvm::Intrinsic::ppc_altivec_vcmpeqfp_p, llvm::Intrinsic::ppc_altivec_vcmpequb_p, llvm::Intrinsic::ppc_altivec_vcmpequh_p, llvm::Intrinsic::ppc_altivec_vcmpequw_p, llvm::Intrinsic::ppc_altivec_vcmpgefp_p, llvm::Intrinsic::ppc_altivec_vcmpgtfp_p, llvm::Intrinsic::ppc_altivec_vcmpgtsb_p, llvm::Intrinsic::ppc_altivec_vcmpgtsh_p, llvm::Intrinsic::ppc_altivec_vcmpgtsw_p, llvm::Intrinsic::ppc_altivec_vcmpgtub_p, llvm::Intrinsic::ppc_altivec_vcmpgtuh_p, and llvm::Intrinsic::ppc_altivec_vcmpgtuw_p.
createFastISel()
FastISel * PPCTargetLowering::createFastISel (FunctionLoweringInfo & FuncInfo, const TargetLibraryInfo * LibInfo) const override virtual
createFastISel - This method returns a target-specific FastISel object, or null if the target does not support "fast" instruction selection.
Reimplemented from llvm::TargetLowering.
Definition at line 9940 of file PPCISelLowering.cpp.
References llvm::PPC::createFastISel().
EmitAtomicBinary()
MachineBasicBlock * PPCTargetLowering::EmitAtomicBinary (MachineInstr * MI, MachineBasicBlock * MBB, bool is64Bit, unsigned BinOpcode) const
Definition at line 6822 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineBasicBlock::end(), F, llvm::MachineBasicBlock::getBasicBlock(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetLoweringBase::getTargetMachine(), llvm::PPC::PRED_NE, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by EmitInstrWithCustomInserter().
emitEHSjLjLongJmp()
MachineBasicBlock * PPCTargetLowering::emitEHSjLjLongJmp (MachineInstr * MI, MachineBasicBlock * MBB) const
Definition at line 7161 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRelocationModel(), llvm::MVT::getStoreSize(), llvm::TargetMachine::getSubtargetImpl(), llvm::MachineFunction::getTarget(), llvm::TargetLoweringBase::getTargetMachine(), llvm::MVT::i32, llvm::MVT::i64, llvm::Reloc::PIC_, llvm::MachineInstrBuilder::setMemRefs(), and TII.
Referenced by EmitInstrWithCustomInserter().
emitEHSjLjSetJmp()
llvm::MachineBasicBlock * PPCTargetLowering::emitEHSjLjSetJmp (MachineInstr * MI, MachineBasicBlock * MBB) const
Definition at line 7012 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addRegMask(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineBasicBlock::end(), llvm::AttributeSet::FunctionIndex, llvm::Function::getAttributes(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::PPCRegisterInfo::getNoPreservedMask(), llvm::MachineBasicBlock::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::MVT::getStoreSize(), llvm::TargetMachine::getSubtarget(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetLoweringBase::getTargetMachine(), llvm::AttributeSet::hasAttribute(), llvm::TargetRegisterClass::hasType(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::MachineFunction::insert(), llvm::Attribute::Naked, llvm::MachineInstrBuilder::setMemRefs(), llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by EmitInstrWithCustomInserter().
EmitInstrWithCustomInserter()
MachineBasicBlock * PPCTargetLowering::EmitInstrWithCustomInserter (MachineInstr * MI, MachineBasicBlock * MBB) const override virtual
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag. These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow.
Reimplemented from llvm::TargetLowering.
Definition at line 7267 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::TargetOpcode::COPY, llvm::MachineOperand::CreateImm(), llvm::MachineRegisterInfo::createVirtualRegister(), EmitAtomicBinary(), emitEHSjLjLongJmp(), emitEHSjLjSetJmp(), EmitPartwordAtomicBinary(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::MachineBasicBlock::end(), F, llvm::MachineBasicBlock::getBasicBlock(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetLoweringBase::getTargetMachine(), llvm_unreachable, llvm::TargetOpcode::PATCHPOINT, llvm::PPC::PRED_BIT_SET, llvm::PPC::PRED_NE, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::MachineBasicBlock::splice(), llvm::TargetOpcode::STACKMAP, TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
emitLeadingFence()
Instruction * PPCTargetLowering::emitLeadingFence (IRBuilder<> & Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const override virtual
Inserts in the IR a target-specific intrinsic specifying a fence. It is called by AtomicExpandPass before expanding an AtomicRMW/AtomicCmpXchg/AtomicStore/AtomicLoad. RMW and CmpXchg set both IsStore and IsLoad to true. This function should either return a nullptr, or a pointer to an IR-level Instruction*. Even complex fence sequences can be represented by a single Instruction* through an intrinsic to be lowered later. Backends with !getInsertFencesForAtomic() should keep a no-op here. Backends should override this method to produce target-specific intrinsic for their fences. FIXME: Please note that the default implementation here in terms of IR-level fences exists for historical/compatibility reasons and is unsound ! Fences cannot, in general, be used to restore sequential consistency. For example, consider the following example: atomic<int> x = y = 0; int r1, r2, r3, r4; Thread 0: x.store(1); Thread 1: y.store(1); Thread 2: r1 = x.load(); r2 = y.load(); Thread 3: r3 = y.load(); r4 = x.load(); r1 = r3 = 1 and r2 = r4 = 0 is impossible as long as the accesses are all seq_cst. But if they are lowered to monotonic accesses, no amount of IR-level fences can prevent it.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 6797 of file PPCISelLowering.cpp.
References callIntrinsic(), llvm::isAtLeastRelease(), llvm::Intrinsic::ppc_lwsync, llvm::Intrinsic::ppc_sync, and llvm::SequentiallyConsistent.
EmitPartwordAtomicBinary()
MachineBasicBlock * PPCTargetLowering::EmitPartwordAtomicBinary (MachineInstr * MI, MachineBasicBlock * MBB, bool is8bit, unsigned Opcode) const
Definition at line 6882 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineBasicBlock::end(), F, llvm::MachineBasicBlock::getBasicBlock(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetLoweringBase::getTargetMachine(), llvm::PPC::PRED_NE, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by EmitInstrWithCustomInserter().
emitTrailingFence()
Instruction * PPCTargetLowering::emitTrailingFence (IRBuilder<> & Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 6808 of file PPCISelLowering.cpp.
References callIntrinsic(), llvm::isAtLeastAcquire(), and llvm::Intrinsic::ppc_lwsync.
enableAggressiveFMAFusion()
bool PPCTargetLowering::enableAggressiveFMAFusion (EVT VT) const override virtual
Return true if target always beneficiates from combining into FMA for a given value type. This must typically return false on targets where FMA takes more cycles to execute than FADD.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 846 of file PPCISelLowering.cpp.
References llvm::EVT::isFloatingPoint().
expandVSXLoadForLE()
SDValue PPCTargetLowering::expandVSXLoadForLE (SDNode * N, DAGCombinerInfo & DCI) const
Definition at line 8625 of file PPCISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::cast(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::MemSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MachineMemOperand::getSize(), llvm::SelectionDAG::getVTList(), llvm::ISD::INTRINSIC_W_CHAIN, llvm_unreachable, llvm::ISD::LOAD, llvm::PPCISD::LXVD2X, N, llvm::MVT::Other, and llvm::PPCISD::XXSWAPD.
Referenced by PerformDAGCombine().
expandVSXStoreForLE()
SDValue PPCTargetLowering::expandVSXStoreForLE (SDNode * N, DAGCombinerInfo & DCI) const
Definition at line 8672 of file PPCISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::cast(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::MemSDNode::getChain(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getSimpleVT(), llvm::MachineMemOperand::getSize(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::ISD::INTRINSIC_VOID, llvm_unreachable, N, llvm::MVT::Other, llvm::ISD::STORE, llvm::PPCISD::STXVD2X, and llvm::PPCISD::XXSWAPD.
Referenced by PerformDAGCombine().
functionArgumentNeedsConsecutiveRegisters()
bool llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters (Type * Ty, CallingConv::ID CallConv, bool isVarArg) const inline override virtual
Returns true if an argument of type Ty needs to be passed in a contiguous block of registers in calling convention CallConv.
Reimplemented from llvm::TargetLowering.
Definition at line 587 of file PPCISelLowering.h.
References llvm::Type::isArrayTy().
getByValTypeAlignment()
unsigned PPCTargetLowering::getByValTypeAlignment (Type * Ty) const override virtual
getByValTypeAlignment - Return the desired alignment for ByVal aggregate function arguments in the caller parameter area. This is the actual alignment, not its logarithm.
getByValTypeAlignment - Return the desired alignment for ByVal aggregate function arguments in the caller parameter area.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 752 of file PPCISelLowering.cpp.
References Align, and getMaxByValAlign().
getConstraintType()
PPCTargetLowering::ConstraintType PPCTargetLowering::getConstraintType (const std::string & Constraint) const override virtual
getConstraintType - Given a constraint, return the type of constraint it is for this target.
Reimplemented from llvm::TargetLowering.
Definition at line 9334 of file PPCISelLowering.cpp.
References llvm::TargetLowering::C_Memory, llvm::TargetLowering::C_RegisterClass, and llvm::TargetLowering::getConstraintType().
getOptimalMemOpType()
EVT PPCTargetLowering::getOptimalMemOpType (uint64_t Size, unsigned DstAlign, unsigned SrcAlign, bool IsMemset, bool ZeroMemset, bool MemcpyStrSrc, MachineFunction & MF) const override virtual
getOptimalMemOpType - Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering. If DstAlign is zero that means it's safe to destination alignment can satisfy any constraint. Similarly if SrcAlign is zero it means there isn't a need to check it against alignment requirement, probably because the source does not need to be loaded. If 'IsMemset' is true, that means it's expanding a memset. If 'ZeroMemset' is true, that means it's a memset of zero. 'MemcpyStrSrc' indicates whether the memcpy source is constant so it does not need to be loaded. It returns EVT::Other if the type should be determined using generic target-independent logic.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9784 of file PPCISelLowering.cpp.
References llvm::MVT::i32, and llvm::MVT::i64.
getPrefLoopAlignment()
unsigned PPCTargetLowering::getPrefLoopAlignment (MachineLoop * ML) const override virtual
Return the preferred loop alignment.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9296 of file PPCISelLowering.cpp.
References llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::PPC::DIR_970, llvm::PPC::DIR_PWR4, llvm::PPC::DIR_PWR5, llvm::PPC::DIR_PWR5X, llvm::PPC::DIR_PWR6, llvm::PPC::DIR_PWR6X, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::TargetLoweringBase::getPrefLoopAlignment(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetLoweringBase::getTargetMachine(), I, and TII.
getPreIndexedAddressParts()
bool PPCTargetLowering::getPreIndexedAddressParts (SDNode * N, SDValue & Base, SDValue & Offset, ISD::MemIndexedMode & AM, SelectionDAG & DAG) const override virtual
getPreIndexedAddressParts - returns true by value, base pointer and offset pointer and addressing mode by reference if the node's address can be legally represented as pre-indexed load / store address.
Reimplemented from llvm::TargetLowering.
Definition at line 1466 of file PPCISelLowering.cpp.
References llvm::cast(), DisablePPCPreinc, llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::MVT::i32, llvm::MVT::i64, llvm::isa(), llvm::SDNode::isPredecessorOf(), llvm::EVT::isVector(), N, llvm::ISD::PRE_INC, SelectAddressRegImm(), SelectAddressRegReg(), llvm::ISD::SEXTLOAD, and std::swap().
getRegForInlineAsmConstraint()
std::pair< unsigned, const TargetRegisterClass * > PPCTargetLowering::getRegForInlineAsmConstraint (const std::string & Constraint, MVT VT) const override virtual
Given a physical register constraint (e.g. {edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer..
Reimplemented from llvm::TargetLowering.
Definition at line 9418 of file PPCISelLowering.cpp.
References llvm::MVT::f32, llvm::MVT::f64, llvm::TargetRegisterInfo::getMatchingSuperReg(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetLoweringBase::getTargetMachine(), llvm::MVT::i32, and llvm::MVT::i64.
getRegisterByName()
unsigned PPCTargetLowering::getRegisterByName (const char * RegName, EVT VT) const override virtual
Return the register ID of the name passed in. Used by named register global variables extension. There is no target-independent behaviour so the default action is to bail.
Reimplemented from llvm::TargetLowering.
Definition at line 9659 of file PPCISelLowering.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::MVT::i32, llvm::MVT::i64, is64Bit(), and llvm::report_fatal_error().
getScalarShiftAmountTy()
MVT llvm::PPCTargetLowering::getScalarShiftAmountTy (EVT LHSTy) const inline override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 388 of file PPCISelLowering.h.
References llvm::MVT::i32.
getSchedulingPreference()
Sched::Preference PPCTargetLowering::getSchedulingPreference (SDNode *) const override virtual
Some scheduler, e.g. hybrid, can switch to different scheduling heuristics for different nodes. This function returns the preference (or none) for the given node.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9931 of file PPCISelLowering.cpp.
References DisableILPPref, llvm::TargetLoweringBase::getSchedulingPreference(), llvm::Sched::ILP, and N.
getScratchRegisters()
const MCPhysReg * PPCTargetLowering::getScratchRegisters (CallingConv::ID CC) const override virtual
Returns a 0 terminated array of registers that can be safely used as scratch registers.
Reimplemented from llvm::TargetLowering.
Definition at line 9910 of file PPCISelLowering.cpp.
getSetCCResultType()
EVT PPCTargetLowering::getSetCCResultType (LLVMContext & Context, EVT VT) const override virtual
getSetCCResultType - Return the ISD::SETCC ValueType
Reimplemented from llvm::TargetLoweringBase.
Definition at line 840 of file PPCISelLowering.cpp.
References llvm::EVT::changeVectorElementTypeToInteger(), llvm::MVT::i1, llvm::MVT::i32, and llvm::EVT::isVector().
Referenced by ReplaceNodeResults().
getSingleConstraintMatchWeight()
TargetLowering::ConstraintWeight PPCTargetLowering::getSingleConstraintMatchWeight (AsmOperandInfo & info, const char * constraint) const override virtual
Examine constraint string and operand type and determine a weight value. The operand object must already have been set up with the operand type.
Examine constraint type and operand type and determine a weight value. This object must already have been set up with the operand type and the current alternative constraint selected.
Reimplemented from llvm::TargetLowering.
Definition at line 9366 of file PPCISelLowering.cpp.
References llvm::TargetLowering::CW_Default, llvm::TargetLowering::CW_Invalid, llvm::TargetLowering::CW_Memory, llvm::TargetLowering::CW_Register, llvm::TargetLowering::getSingleConstraintMatchWeight(), llvm::Value::getType(), and info.
getTargetNodeName()
const char * PPCTargetLowering::getTargetNodeName (unsigned Opcode) const override virtual
getTargetNodeName() - This method returns the name of a target specific DAG node.
Reimplemented from llvm::TargetLowering.
Definition at line 765 of file PPCISelLowering.cpp.
References llvm::PPCISD::ADD_TLS, llvm::PPCISD::ADDI_DTPREL_L, llvm::PPCISD::ADDI_TLSGD_L, llvm::PPCISD::ADDI_TLSLD_L, llvm::PPCISD::ADDI_TOC_L, llvm::PPCISD::ADDIS_DTPREL_HA, llvm::PPCISD::ADDIS_GOT_TPREL_HA, llvm::PPCISD::ADDIS_TLSGD_HA, llvm::PPCISD::ADDIS_TLSLD_HA, llvm::PPCISD::ADDIS_TOC_HA, llvm::PPCISD::BCTRL, llvm::PPCISD::BCTRL_LOAD_TOC, llvm::PPCISD::BDNZ, llvm::PPCISD::BDZ, llvm::PPCISD::CALL, llvm::PPCISD::CALL_NOP, llvm::PPCISD::CALL_NOP_TLS, llvm::PPCISD::CALL_TLS, llvm::PPCISD::CMPB, llvm::PPCISD::COND_BRANCH, llvm::PPCISD::CR6SET, llvm::PPCISD::CR6UNSET, llvm::PPCISD::DYNALLOC, llvm::PPCISD::EH_SJLJ_LONGJMP, llvm::PPCISD::EH_SJLJ_SETJMP, llvm::PPCISD::FADDRTZ, llvm::PPCISD::FCFID, llvm::PPCISD::FCFIDS, llvm::PPCISD::FCFIDU, llvm::PPCISD::FCFIDUS, llvm::PPCISD::FCTIDUZ, llvm::PPCISD::FCTIDZ, llvm::PPCISD::FCTIWUZ, llvm::PPCISD::FCTIWZ, llvm::PPCISD::FRE, llvm::PPCISD::FRSQRTE, llvm::PPCISD::FSEL, llvm::PPCISD::GlobalBaseReg, llvm::PPCISD::Hi, llvm::PPCISD::LARX, llvm::PPCISD::LBRX, llvm::PPCISD::LD_GOT_TPREL_L, llvm::PPCISD::LD_TOC_L, llvm::PPCISD::LFIWAX, llvm::PPCISD::LFIWZX, llvm::PPCISD::Lo, llvm::PPCISD::LOAD, llvm::PPCISD::LOAD_TOC, llvm::PPCISD::MFFS, llvm::PPCISD::MFOCRF, llvm::PPCISD::MTCTR, llvm::PPCISD::PPC32_GOT, llvm::PPCISD::READ_TIME_BASE, llvm::PPCISD::RET_FLAG, llvm::PPCISD::SC, llvm::PPCISD::SHL, llvm::PPCISD::SRA, llvm::PPCISD::SRL, llvm::PPCISD::STBRX, llvm::PPCISD::STCX, llvm::PPCISD::STFIWX, llvm::PPCISD::TC_RETURN, llvm::PPCISD::TOC_ENTRY, llvm::PPCISD::VADD_SPLAT, llvm::PPCISD::VCMP, llvm::PPCISD::VCMPo, llvm::PPCISD::VMADDFP, llvm::PPCISD::VNMSUBFP, and llvm::PPCISD::VPERM.
getTgtMemIntrinsic()
bool PPCTargetLowering::getTgtMemIntrinsic (IntrinsicInfo & , const CallInst & , unsigned) const override virtual
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory). If this is the case, it returns true and store the intrinsic information into the IntrinsicInfo that was passed to the function.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9687 of file PPCISelLowering.cpp.
References llvm::EVT::getStoreSize(), I, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::Intrinsic::ppc_altivec_lvebx, llvm::Intrinsic::ppc_altivec_lvehx, llvm::Intrinsic::ppc_altivec_lvewx, llvm::Intrinsic::ppc_altivec_lvx, llvm::Intrinsic::ppc_altivec_lvxl, llvm::Intrinsic::ppc_altivec_stvebx, llvm::Intrinsic::ppc_altivec_stvehx, llvm::Intrinsic::ppc_altivec_stvewx, llvm::Intrinsic::ppc_altivec_stvx, llvm::Intrinsic::ppc_altivec_stvxl, llvm::Intrinsic::ppc_vsx_lxvd2x, llvm::Intrinsic::ppc_vsx_lxvw4x, llvm::Intrinsic::ppc_vsx_stxvd2x, llvm::Intrinsic::ppc_vsx_stxvw4x, llvm::MVT::v2f64, and llvm::MVT::v4i32.
isCheapToSpeculateCtlz()
bool llvm::PPCTargetLowering::isCheapToSpeculateCtlz () const inline override virtual
Return true if it is cheap to speculate a call to intrinsic ctlz.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 394 of file PPCISelLowering.h.
isCheapToSpeculateCttz()
bool llvm::PPCTargetLowering::isCheapToSpeculateCttz () const inline override virtual
Return true if it is cheap to speculate a call to intrinsic cttz.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 390 of file PPCISelLowering.h.
isFMAFasterThanFMulAndFAdd()
bool PPCTargetLowering::isFMAFasterThanFMulAndFAdd (EVT VT) const override virtual
isFMAFasterThanFMulAndFAdd - Return true if an FMA operation is faster than a pair of fmul and fadd instructions. fmuladd intrinsics will be expanded to FMAs when this method returns true, otherwise fmuladd is expanded to fmul + fadd.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9892 of file PPCISelLowering.cpp.
References llvm::MVT::f32, llvm::MVT::f64, llvm::EVT::getScalarType(), llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), and llvm::MVT::SimpleTy.
isFPExtFree()
bool PPCTargetLowering::isFPExtFree (EVT VT) const override virtual
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9844 of file PPCISelLowering.cpp.
References llvm::EVT::isFloatingPoint().
isLegalAddImmediate()
bool PPCTargetLowering::isLegalAddImmediate (int64_t Imm) const override virtual
isLegalAddImmediate - Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register and the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9853 of file PPCISelLowering.cpp.
References llvm::isInt< 16 >(), and llvm::isUInt< 16 >().
isLegalAddressingMode()
bool PPCTargetLowering::isLegalAddressingMode (const AddrMode & AM, Type * Ty) const override virtual
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9556 of file PPCISelLowering.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::TargetLoweringBase::AddrMode::HasBaseReg, and llvm::TargetLoweringBase::AddrMode::Scale.
isLegalICmpImmediate()
bool PPCTargetLowering::isLegalICmpImmediate (int64_t Imm) const override virtual
isLegalICmpImmediate - Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9849 of file PPCISelLowering.cpp.
References llvm::isInt< 16 >(), and llvm::isUInt< 16 >().
isOffsetFoldingLegal()
bool PPCTargetLowering::isOffsetFoldingLegal (const GlobalAddressSDNode * GA) const override virtual
Return true if folding a constant offset with the given GlobalAddress is legal. It is frequently not legal in PIC relocation models.
Reimplemented from llvm::TargetLowering.
Definition at line 9682 of file PPCISelLowering.cpp.
isTruncateFree() [1/2]
bool PPCTargetLowering::isTruncateFree (EVT VT1, EVT VT2) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9816 of file PPCISelLowering.cpp.
References llvm::EVT::getSizeInBits(), and llvm::EVT::isInteger().
isTruncateFree() [2/2]
bool PPCTargetLowering::isTruncateFree (Type * Ty1, Type * Ty2) const override virtual
isTruncateFree - Return true if it's free to truncate a value of type Ty1 to type Ty2. e.g. On PPC it's free to truncate a i64 value in register X1 to i32 by referencing its sub-register R1.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9808 of file PPCISelLowering.cpp.
References llvm::Type::getPrimitiveSizeInBits(), and llvm::Type::isIntegerTy().
isZExtFree()
bool PPCTargetLowering::isZExtFree (SDValue Val, EVT VT2) const override virtual
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9824 of file PPCISelLowering.cpp.
References llvm::dyn_cast(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::TargetLoweringBase::isZExtFree(), llvm::ISD::NON_EXTLOAD, and llvm::ISD::ZEXTLOAD.
LowerAsmOperandForConstraint()
void PPCTargetLowering::LowerAsmOperandForConstraint (SDValue Op, std::string & Constraint, std::vector< SDValue > & Ops, SelectionDAG & DAG) const override virtual
LowerAsmOperandForConstraint - Lower the specified operand into the Ops vector. If it is invalid, don't add anything to Ops.
Reimplemented from llvm::TargetLowering.
Definition at line 9481 of file PPCISelLowering.cpp.
References llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::ConstantSDNode::getSExtValue(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i64, llvm::isInt(), llvm::isPowerOf2_64(), llvm::isShiftedInt(), llvm::isShiftedUInt(), llvm::isUInt(), llvm_unreachable, and llvm::TargetLowering::LowerAsmOperandForConstraint().
LowerOperation()
SDValue PPCTargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const override virtual
LowerOperation - Provide custom lowering hooks for some operations.
Reimplemented from llvm::TargetLowering.
Definition at line 6648 of file PPCISelLowering.cpp.
References llvm::ISD::ADJUST_TRAMPOLINE, llvm::ISD::BlockAddress, llvm::ISD::BUILD_VECTOR, llvm::ISD::ConstantPool, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_SJLJ_LONGJMP, llvm::ISD::EH_SJLJ_SETJMP, llvm::ISD::FLT_ROUNDS_, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FRAMEADDR, llvm::SDValue::getOpcode(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::INIT_TRAMPOLINE, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::JumpTable, llvm_unreachable, llvm::ISD::LOAD, llvm::ISD::MUL, llvm::ISD::RETURNADDR, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SRA_PARTS, llvm::ISD::SRL_PARTS, llvm::ISD::STACKRESTORE, llvm::ISD::STORE, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VASTART, and llvm::ISD::VECTOR_SHUFFLE.
PerformDAGCombine()
SDValue PPCTargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const override virtual
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::TargetLowering.
Definition at line 8722 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::Add, llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::PPCISD::BDNZ, llvm::PPCISD::BDZ, llvm::ISD::BITCAST, llvm::ISD::BR, llvm::ISD::BR_CC, llvm::ISD::BRCOND, llvm::ISD::BSWAP, BuildIntrinsicOp(), llvm::cast(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::PPCISD::COND_BRANCH, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), expandVSXLoadForLE(), expandVSXStoreForLE(), llvm::MVT::f32, llvm::MVT::f64, llvm::PPCISD::FCTIWZ, findConsecutiveLoad(), llvm::ISD::FP_EXTEND, llvm::ISD::FP_TO_SINT, llvm::DataLayout::getABITypeAlignment(), llvm::APInt::getAllOnesValue(), getAltivecCompareInfo(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::User::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::User::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::PPCSubtarget::hasAltivec(), llvm::PPCSubtarget::hasLDBRX(), llvm::SDNode::hasNUsesOfValue(), llvm::SDNode::hasOneUse(), llvm::PPCSubtarget::hasP8Vector(), llvm::PPCSubtarget::hasSTFIWX(), llvm::PPCSubtarget::hasVSX(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::isa(), llvm::PPCSubtarget::isLittleEndian(), llvm::TargetLoweringBase::isLittleEndian(), llvm::ISD::isNON_EXTLoad(), llvm::PPCSubtarget::isPPC64(), llvm::EVT::isSimple(), llvm::EVT::isVector(), isZero(), llvm::PPCISD::LBRX, llvm::ISD::LOAD, llvm::SelectionDAG::MaskedValueIsZero(), llvm::PPCISD::MFOCRF, N, llvm::MVT::Other, llvm::Intrinsic::ppc_altivec_lvsl, llvm::Intrinsic::ppc_altivec_lvsr, llvm::Intrinsic::ppc_altivec_lvx, llvm::Intrinsic::ppc_altivec_vperm, llvm::Intrinsic::ppc_is_decremented_ctr_nonzero, llvm::Intrinsic::ppc_vsx_lxvd2x, llvm::Intrinsic::ppc_vsx_lxvw4x, llvm::Intrinsic::ppc_vsx_stxvd2x, llvm::Intrinsic::ppc_vsx_stxvw4x, llvm::MVT::ppcf128, llvm::PPC::PRED_EQ, llvm::PPC::PRED_GE, llvm::PPC::PRED_LT, llvm::PPC::PRED_NE, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::PPCISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SINT_TO_FP, llvm::PPCISD::SRA, llvm::PPCISD::SRL, llvm::PPCISD::STBRX, llvm::PPCISD::STFIWX, llvm::ISD::STORE, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::PPCISD::VCMP, llvm::PPCISD::VCMPo, and llvm::ISD::ZERO_EXTEND.
ReplaceNodeResults()
void PPCTargetLowering::ReplaceNodeResults (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) const override virtual
ReplaceNodeResults - Replace the results of node with an illegal result type with new values built out of custom code.
Reimplemented from llvm::TargetLowering.
Definition at line 6708 of file PPCISelLowering.cpp.
References llvm::ISD::BUILD_PAIR, llvm::cast(), llvm::ISD::EXTRACT_ELEMENT, llvm::MVT::f64, llvm::PPCISD::FADDRTZ, llvm::ISD::FP_ROUND_INREG, llvm::ISD::FP_TO_SINT, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), getSetCCResultType(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::MVT::i1, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INTRINSIC_W_CHAIN, llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm_unreachable, N, llvm::MVT::Other, llvm::Intrinsic::ppc_is_decremented_ctr_nonzero, llvm::MVT::ppcf128, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::PPCISD::READ_TIME_BASE, llvm::ISD::READCYCLECOUNTER, and llvm::ISD::VAARG.
SelectAddressRegImm()
bool PPCTargetLowering::SelectAddressRegImm (SDValue N, SDValue & Disp, SDValue & Base, SelectionDAG & DAG, bool Aligned) const
SelectAddressRegImm - Returns true if the address N can be represented by a base register plus a signed 16-bit displacement [r+imm], and if it is not better represented as reg+reg. If Aligned is true, only accept displacements suitable for STD and friends, i.e. multiples of 4.
Returns true if the address N can be represented by a base register plus a signed 16-bit displacement [r+imm], and if it is not better represented as reg+reg. If Aligned is true, only accept displacements suitable for STD and friends, i.e. multiples of 4.
Definition at line 1340 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::cast(), llvm::SelectionDAG::computeKnownBits(), llvm::dyn_cast(), fixupFuncForFI(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getOpcode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::SDNode::getValueType(), llvm::APInt::getZExtValue(), llvm::MVT::i32, isIntS16Immediate(), llvm::PPCISD::Lo, N, llvm::ISD::OR, SelectAddressRegReg(), llvm::ISD::TargetConstantPool, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, and llvm::ISD::TargetJumpTable.
Referenced by getPreIndexedAddressParts().
SelectAddressRegReg()
bool PPCTargetLowering::SelectAddressRegReg (SDValue N, SDValue & Base, SDValue & Index, SelectionDAG & DAG) const
SelectAddressRegReg - Given the specified addressed, check to see if it can be represented as an indexed [r+r] operation. Returns false if it can be more efficiently represented with [r+imm].
Definition at line 1255 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::computeKnownBits(), llvm::APInt::getBoolValue(), isIntS16Immediate(), llvm::PPCISD::Lo, N, and llvm::ISD::OR.
Referenced by getPreIndexedAddressParts(), SelectAddressRegImm(), and SelectAddressRegRegOnly().
SelectAddressRegRegOnly()
bool PPCTargetLowering::SelectAddressRegRegOnly (SDValue N, SDValue & Base, SDValue & Index, SelectionDAG & DAG) const
SelectAddressRegRegOnly - Given the specified addressed, force it to be represented as an indexed [r+r] operation.
Definition at line 1438 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::getRegister(), N, and SelectAddressRegReg().
shouldConvertConstantLoadToIntImm()
bool PPCTargetLowering::shouldConvertConstantLoadToIntImm (const APInt & Imm, Type * Ty) const override virtual
Returns true if it is beneficial to convert a load of a constant to just the constant itself.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9798 of file PPCISelLowering.cpp.
References llvm::Type::getPrimitiveSizeInBits(), and llvm::Type::isIntegerTy().
shouldExpandBuildVectorWithShuffles()
bool PPCTargetLowering::shouldExpandBuildVectorWithShuffles (EVT VT, unsigned DefinedValues) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 9923 of file PPCISelLowering.cpp.
References llvm::TargetLoweringBase::shouldExpandBuildVectorWithShuffles(), and llvm::MVT::v2i64.
The documentation for this class was generated from the following files:
PPCISelLowering.h
PPCISelLowering.cpp