LLVM: llvm::APInt Class Reference
LLVM API Documentation
llvm::APInt Class Reference
Class for arbitrary precision integers.
#include <APInt.h>
Classes
struct ms
Magic data for optimising signed division by a constant.
struct mu
Magic data for optimising unsigned division by a constant.
Public Member Functions
Constructors
APInt (unsigned numBits, uint64_t val, bool isSigned=false)
Create a new APInt of numBits width, initialized as val.
APInt (unsigned numBits, ArrayRef< uint64_t > bigVal)
Construct an APInt of numBits width, initialized as bigVal[].
APInt (unsigned numBits, unsigned numWords, const uint64_t bigVal[])
APInt (unsigned numBits, StringRef str, uint8_t radix)
Construct an APInt from a string representation.
APInt (const APInt &that)
Copy Constructor.
APInt (APInt &&that)
Move Constructor.
~APInt ()
Destructor.
APInt ()
Default constructor that creates an uninitialized APInt.
bool needsCleanup () const
Returns whether this instance allocated memory.
void Profile (FoldingSetNodeID &id) const
Profile - This method 'profiles' an APInt for use with FoldingSet.
Value Tests
bool isNegative () const
Determine sign of this APInt.
bool isNonNegative () const
Determine if this APInt Value is non-negative (>= 0)
bool isStrictlyPositive () const
Determine if this APInt Value is positive.
bool isAllOnesValue () const
Determine if all bits are set.
bool isMaxValue () const
Determine if this is the largest unsigned value.
bool isMaxSignedValue () const
Determine if this is the largest signed value.
bool isMinValue () const
Determine if this is the smallest unsigned value.
bool isMinSignedValue () const
Determine if this is the smallest signed value.
bool isIntN (unsigned N) const
Check if this APInt has an N-bits unsigned integer value.
bool isSignedIntN (unsigned N) const
Check if this APInt has an N-bits signed integer value.
bool isPowerOf2 () const
Check if this APInt's value is a power of two greater than zero.
bool isSignBit () const
Check if the APInt's value is returned by getSignBit.
bool getBoolValue () const
Convert APInt to a boolean value.
uint64_t getLimitedValue (uint64_t Limit=~0ULL) const
Unary Operators
const APInt operator++ (int)
Postfix increment operator.
APInt & operator++ ()
Prefix increment operator.
const APInt operator-- (int)
Postfix decrement operator.
APInt & operator-- ()
Prefix decrement operator.
APInt operator~ () const
Unary bitwise complement operator.
APInt operator- () const
Unary negation operator.
bool operator! () const
Logical negation operator.
Assignment Operators
APInt & operator= (const APInt &RHS)
Copy assignment operator.
APInt & operator= (APInt &&that)
Move assignment operator.
APInt & operator= (uint64_t RHS)
Assignment operator.
APInt & operator&= (const APInt &RHS)
Bitwise AND assignment operator.
APInt & operator|= (const APInt &RHS)
Bitwise OR assignment operator.
APInt & operator|= (uint64_t RHS)
Bitwise OR assignment operator.
APInt & operator^= (const APInt &RHS)
Bitwise XOR assignment operator.
APInt & operator*= (const APInt &RHS)
Multiplication assignment operator.
APInt & operator+= (const APInt &RHS)
Addition assignment operator.
APInt & operator-= (const APInt &RHS)
Subtraction assignment operator.
APInt & operator<<= (unsigned shiftAmt)
Left-shift assignment function.
Comparison Operators
bool operator== (const APInt &RHS) const
Equality operator.
bool operator== (uint64_t Val) const
Equality operator.
bool eq (const APInt &RHS) const
Equality comparison.
bool operator!= (const APInt &RHS) const
Inequality operator.
bool operator!= (uint64_t Val) const
Inequality operator.
bool ne (const APInt &RHS) const
Inequality comparison.
bool ult (const APInt &RHS) const
Unsigned less than comparison.
bool ult (uint64_t RHS) const
Unsigned less than comparison.
bool slt (const APInt &RHS) const
Signed less than comparison.
bool slt (uint64_t RHS) const
Signed less than comparison.
bool ule (const APInt &RHS) const
Unsigned less or equal comparison.
bool ule (uint64_t RHS) const
Unsigned less or equal comparison.
bool sle (const APInt &RHS) const
Signed less or equal comparison.
bool sle (uint64_t RHS) const
Signed less or equal comparison.
bool ugt (const APInt &RHS) const
Unsigned greather than comparison.
bool ugt (uint64_t RHS) const
Unsigned greater than comparison.
bool sgt (const APInt &RHS) const
Signed greather than comparison.
bool sgt (uint64_t RHS) const
Signed greater than comparison.
bool uge (const APInt &RHS) const
Unsigned greater or equal comparison.
bool uge (uint64_t RHS) const
Unsigned greater or equal comparison.
bool sge (const APInt &RHS) const
Signed greather or equal comparison.
bool sge (uint64_t RHS) const
Signed greater or equal comparison.
bool intersects (const APInt &RHS) const
Resizing Operators
APInt LLVM_ATTRIBUTE_UNUSED_RESULT trunc (unsigned width) const
Truncate to new width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT sext (unsigned width) const
Sign extend to a new width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT zext (unsigned width) const
Zero extend to a new width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT sextOrTrunc (unsigned width) const
Sign extend or truncate to width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT zextOrTrunc (unsigned width) const
Zero extend or truncate to width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT sextOrSelf (unsigned width) const
Sign extend or truncate to width.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT zextOrSelf (unsigned width) const
Zero extend or truncate to width.
Bit Manipulation Operators
void setAllBits ()
Set every bit to 1.
void setBit (unsigned bitPosition)
Set a given bit to 1.
void clearAllBits ()
Set every bit to 0.
void clearBit (unsigned bitPosition)
Set a given bit to 0.
void flipAllBits ()
Toggle every bit to its opposite value.
void flipBit (unsigned bitPosition)
Toggles a given bit to its opposite value.
Mathematics Operations
unsigned logBase2 () const
unsigned ceilLogBase2 () const
unsigned nearestLogBase2 () const
int32_t exactLogBase2 () const
APInt LLVM_ATTRIBUTE_UNUSED_RESULT sqrt () const
Compute the square root.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT abs () const
Get the absolute value;.
APInt multiplicativeInverse (const APInt &modulo) const
Support for division by constant
ms magic () const
mu magicu (unsigned LeadingZeros=0) const
Friends
struct DenseMapAPIntKeyInfo
Value Generators
hash_code hash_value (const APInt &Arg)
Overload to compute a hash_code for an APInt value.
APInt getHiBits (unsigned numBits) const
Compute an APInt containing numBits highbits from this APInt.
APInt getLoBits (unsigned numBits) const
Compute an APInt containing numBits lowbits from this APInt.
const uint64_t * getRawData () const
static APInt getMaxValue (unsigned numBits)
Gets maximum unsigned value of APInt for specific bit width.
static APInt getSignedMaxValue (unsigned numBits)
Gets maximum signed value of APInt for a specific bit width.
static APInt getMinValue (unsigned numBits)
Gets minimum unsigned value of APInt for a specific bit width.
static APInt getSignedMinValue (unsigned numBits)
Gets minimum signed value of APInt for a specific bit width.
static APInt getSignBit (unsigned BitWidth)
Get the SignBit for a specific bit width.
static APInt getAllOnesValue (unsigned numBits)
Get the all-ones value.
static APInt getNullValue (unsigned numBits)
Get the '0' value.
static APInt getOneBitSet (unsigned numBits, unsigned BitNo)
Return an APInt with exactly one bit set in the result.
static APInt getBitsSet (unsigned numBits, unsigned loBit, unsigned hiBit)
Get a value with a block of bits set.
static APInt getHighBitsSet (unsigned numBits, unsigned hiBitsSet)
Get a value with high bits set.
static APInt getLowBitsSet (unsigned numBits, unsigned loBitsSet)
Get a value with low bits set.
static APInt getSplat (unsigned NewLen, const APInt &V)
Return a value containing V broadcasted over NewLen bits.
static bool isSameValue (const APInt &I1, const APInt &I2)
Determine if two APInts have the same value, after zero-extending one of them (if needed!) to ensure that the bit-widths match.
Binary Operators
APInt operator& (const APInt &RHS) const
Bitwise AND operator.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT And (const APInt &RHS) const
APInt operator| (const APInt &RHS) const
Bitwise OR operator.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT Or (const APInt &RHS) const
Bitwise OR function.
APInt operator^ (const APInt &RHS) const
Bitwise XOR operator.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT Xor (const APInt &RHS) const
Bitwise XOR function.
APInt operator* (const APInt &RHS) const
Multiplication operator.
APInt operator+ (const APInt &RHS) const
Addition operator.
APInt operator+ (uint64_t RHS) const
APInt operator- (const APInt &RHS) const
Subtraction operator.
APInt operator- (uint64_t RHS) const
APInt operator<< (unsigned Bits) const
Left logical shift operator.
APInt operator<< (const APInt &Bits) const
Left logical shift operator.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT ashr (unsigned shiftAmt) const
Arithmetic right-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT lshr (unsigned shiftAmt) const
Logical right-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT shl (unsigned shiftAmt) const
Left-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT rotl (unsigned rotateAmt) const
Rotate left by rotateAmt.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT rotr (unsigned rotateAmt) const
Rotate right by rotateAmt.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT ashr (const APInt &shiftAmt) const
Arithmetic right-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT lshr (const APInt &shiftAmt) const
Logical right-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT shl (const APInt &shiftAmt) const
Left-shift function.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT rotl (const APInt &rotateAmt) const
Rotate left by rotateAmt.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT rotr (const APInt &rotateAmt) const
Rotate right by rotateAmt.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT udiv (const APInt &RHS) const
Unsigned division operation.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT sdiv (const APInt &RHS) const
Signed division function for APInt.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT urem (const APInt &RHS) const
Unsigned remainder operation.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT srem (const APInt &RHS) const
Function for signed remainder operation.
APInt sadd_ov (const APInt &RHS, bool &Overflow) const
APInt uadd_ov (const APInt &RHS, bool &Overflow) const
APInt ssub_ov (const APInt &RHS, bool &Overflow) const
APInt usub_ov (const APInt &RHS, bool &Overflow) const
APInt sdiv_ov (const APInt &RHS, bool &Overflow) const
APInt smul_ov (const APInt &RHS, bool &Overflow) const
APInt umul_ov (const APInt &RHS, bool &Overflow) const
APInt sshl_ov (const APInt &Amt, bool &Overflow) const
APInt ushl_ov (const APInt &Amt, bool &Overflow) const
bool operator[] (unsigned bitPosition) const
Array-indexing support.
static void udivrem (const APInt &LHS, const APInt &RHS, APInt &Quotient, APInt &Remainder)
Dual division/remainder interface.
static void sdivrem (const APInt &LHS, const APInt &RHS, APInt &Quotient, APInt &Remainder)
Value Characterization Functions
unsigned getBitWidth () const
Return the number of bits in the APInt.
unsigned getNumWords () const
Get the number of words.
unsigned getActiveBits () const
Compute the number of active bits in the value.
unsigned getActiveWords () const
Compute the number of active words in the value of this APInt.
unsigned getMinSignedBits () const
Get the minimum bit size for this signed APInt.
uint64_t getZExtValue () const
Get zero extended value.
int64_t getSExtValue () const
Get sign extended value.
unsigned countLeadingZeros () const
The APInt version of the countLeadingZeros functions in MathExtras.h.
unsigned countLeadingOnes () const
Count the number of leading one bits.
unsigned getNumSignBits () const
unsigned countTrailingZeros () const
Count the number of trailing zero bits.
unsigned countTrailingOnes () const
Count the number of trailing one bits.
unsigned countPopulation () const
Count the number of bits set.
static unsigned getNumWords (unsigned BitWidth)
Get the number of words.
static unsigned getBitsNeeded (StringRef str, uint8_t radix)
Get bits required for string value.
Conversion Functions
void print (raw_ostream &OS, bool isSigned) const
void toString (SmallVectorImpl< char > &Str, unsigned Radix, bool Signed, bool formatAsCLiteral=false) const
void toStringUnsigned (SmallVectorImpl< char > &Str, unsigned Radix=10) const
void toStringSigned (SmallVectorImpl< char > &Str, unsigned Radix=10) const
std::string toString (unsigned Radix, bool Signed) const
Return the APInt as a std::string.
APInt LLVM_ATTRIBUTE_UNUSED_RESULT byteSwap () const
double roundToDouble (bool isSigned) const
Converts this APInt to a double value.
double roundToDouble () const
Converts this unsigned APInt to a double value.
double signedRoundToDouble () const
Converts this signed APInt to a double value.
double bitsToDouble () const
Converts APInt bits to a double.
float bitsToFloat () const
Converts APInt bits to a double.
static APInt LLVM_ATTRIBUTE_UNUSED_RESULT doubleToBits (double V)
Converts a double to APInt bits.
static APInt LLVM_ATTRIBUTE_UNUSED_RESULT floatToBits (float V)
Converts a float to APInt bits.
Building-block Operations for APInt and APFloat
void dump () const
debug method
static void tcSet (integerPart *, integerPart, unsigned int)
static void tcAssign (integerPart *, const integerPart *, unsigned int)
Assign one bignum to another.
static bool tcIsZero (const integerPart *, unsigned int)
Returns true if a bignum is zero, false otherwise.
static int tcExtractBit (const integerPart *, unsigned int bit)
Extract the given bit of a bignum; returns 0 or 1. Zero-based.
static void tcExtract (integerPart *, unsigned int dstCount, const integerPart *, unsigned int srcBits, unsigned int srcLSB)
static void tcSetBit (integerPart *, unsigned int bit)
Set the given bit of a bignum. Zero-based.
static void tcClearBit (integerPart *, unsigned int bit)
Clear the given bit of a bignum. Zero-based.
static unsigned int tcLSB (const integerPart *, unsigned int)
static unsigned int tcMSB (const integerPart *parts, unsigned int n)
static void tcNegate (integerPart *, unsigned int)
Negate a bignum in-place.
static integerPart tcAdd (integerPart *, const integerPart *, integerPart carry, unsigned)
DST += RHS + CARRY where CARRY is zero or one. Returns the carry flag.
static integerPart tcSubtract (integerPart *, const integerPart *, integerPart carry, unsigned)
DST -= RHS + CARRY where CARRY is zero or one. Returns the carry flag.
static int tcMultiplyPart (integerPart *dst, const integerPart *src, integerPart multiplier, integerPart carry, unsigned int srcParts, unsigned int dstParts, bool add)
static int tcMultiply (integerPart *, const integerPart *, const integerPart *, unsigned)
static unsigned int tcFullMultiply (integerPart *, const integerPart *, const integerPart *, unsigned, unsigned)
static int tcDivide (integerPart *lhs, const integerPart *rhs, integerPart *remainder, integerPart *scratch, unsigned int parts)
static void tcShiftLeft (integerPart *, unsigned int parts, unsigned int count)
static void tcShiftRight (integerPart *, unsigned int parts, unsigned int count)
static void tcAnd (integerPart *, const integerPart *, unsigned int)
The obvious AND, OR and XOR and complement operations.
static void tcOr (integerPart *, const integerPart *, unsigned int)
static void tcXor (integerPart *, const integerPart *, unsigned int)
static void tcComplement (integerPart *, unsigned int)
static int tcCompare (const integerPart *, const integerPart *, unsigned int)
Comparison (unsigned) of two bignums.
static integerPart tcIncrement (integerPart *, unsigned int)
Increment a bignum in-place. Return the carry flag.
static integerPart tcDecrement (integerPart *, unsigned int)
Decrement a bignum in-place. Return the borrow flag.
static void tcSetLeastSignificantBits (integerPart *, unsigned int, unsigned int bits)
Set the least significant BITS and clear the rest.
Detailed Description
Class for arbitrary precision integers.
APInt is a functional replacement for common case unsigned integer type like "unsigned", "unsigned long" or "uint64_t", but also allows non-byte-width integer sizes and large integer value types such as 3-bits, 15-bits, or more than 64-bits of precision. APInt provides a variety of arithmetic operators and methods to manipulate integer values of any bit-width. It supports both the typical integer arithmetic and comparison operations as well as bitwise manipulation.
The class has several invariants worth noting:
All bit, byte, and word positions are zero-based.
Once the bit width is set, it doesn't change except by the Truncate, SignExtend, or ZeroExtend operations.
All binary operators must be on APInt instances of the same bit width. Attempting to use these operators on instances with different bit widths will yield an assertion.
The value is stored canonically as an unsigned value. For operations where it makes a difference, there are both signed and unsigned variants of the operation. For example, sdiv and udiv. However, because the bit widths must be the same, operations such as Mul and Add produce the same results regardless of whether the values are interpreted as signed or not.
In general, the class tries to follow the style of computation that LLVM uses in its IR. This simplifies its use for LLVM.
Definition at line 75 of file APInt.h.
Constructor & Destructor Documentation
APInt() [1/7]
llvm::APInt::APInt (unsigned numBits, uint64_t val, bool isSigned = false) inline
Create a new APInt of numBits width, initialized as val.
If isSigned is true then val is treated as if it were a signed value (i.e. as an int64_t) and the appropriate sign extension to the bit width will be done. Otherwise, no sign extension occurs (high order bits beyond the range of val are zero filled).
Parameters
numBits the bit width of the constructed APInt
val the initial value of the APInt
isSigned how to treat signedness of val
Definition at line 238 of file APInt.h.
References VAL.
APInt() [2/7]
APInt::APInt (unsigned numBits, ArrayRef< uint64_t > bigVal)
Construct an APInt of numBits width, initialized as bigVal[].
Note that bigVal.size() can be smaller or larger than the corresponding bit width but any extraneous bits will be dropped.
Parameters
numBits the bit width of the constructed APInt
bigVal a sequence of words to form the initial value of the APInt
Definition at line 107 of file APInt.cpp.
References VAL.
APInt() [3/7]
APInt::APInt (unsigned numBits, unsigned numWords, const uint64_t bigVal[])
Equivalent to APInt(numBits, ArrayRef<uint64_t>(bigVal, numWords)), but deprecated because this constructor is prone to ambiguity with the APInt(unsigned, uint64_t, bool) constructor.
If this overload is ever deleted, care should be taken to prevent calls from being incorrectly captured by the APInt(unsigned, uint64_t, bool) constructor.
Definition at line 112 of file APInt.cpp.
References llvm::makeArrayRef(), and VAL.
APInt() [4/7]
APInt::APInt (unsigned numBits, StringRef str, uint8_t radix)
Construct an APInt from a string representation.
This constructor interprets the string str in the given radix. The interpretation stops when the first character that is not suitable for the radix is encountered, or the end of the string. Acceptable radix values are 2, 8, 10, 16, and 36. It is an error for the value implied by the string to require more bits than numBits.
Parameters
numBits the bit width of the constructed APInt
str the string to be interpreted
radix the radix to use for the conversion
Definition at line 117 of file APInt.cpp.
References VAL.
APInt() [5/7]
llvm::APInt::APInt (const APInt & that) inline
Copy Constructor.
Simply makes *this a copy of that.
Definition at line 281 of file APInt.h.
References VAL.
APInt() [6/7]
llvm::APInt::APInt (APInt && that) inline
Move Constructor.
Definition at line 289 of file APInt.h.
References VAL.
~APInt()
llvm::APInt::~APInt () inline
Destructor.
Definition at line 294 of file APInt.h.
References needsCleanup(), and pVal.
APInt() [7/7]
llvm::APInt::APInt () inline explicit
Default constructor that creates an uninitialized APInt.
This is useful for object deserialization (pair this with the static method Read).
Definition at line 303 of file APInt.h.
Referenced by ashr(), byteSwap(), doubleToBits(), floatToBits(), getAllOnesValue(), getHighBitsSet(), getLowBitsSet(), getMinValue(), getNullValue(), lshr(), multiplicativeInverse(), operator&(), operator*(), operator+(), operator+(), operator-(), operator-(), operator-(), llvm::APSInt::operator==(), operator^(), operator|(), sext(), sge(), sgt(), shl(), sle(), slt(), sqrt(), sshl_ov(), trunc(), udiv(), udivrem(), uge(), ugt(), ule(), ult(), urem(), ushl_ov(), and zext().
Member Function Documentation
abs()
APInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APInt::abs () const inline
Get the absolute value;.
If *this is < 0 then return -(*this), otherwise *this;
Definition at line 1559 of file APInt.h.
References isNegative(), and LLVM_ATTRIBUTE_UNUSED_RESULT.
Referenced by computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), findGCD(), gcd(), SimplifyICmpInst(), llvm::InstCombiner::visitICmpInst(), and llvm::InstCombiner::visitMul().
And()
APInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APInt::And (const APInt & RHS) const inline
Definition at line 776 of file APInt.h.
References LLVM_ATTRIBUTE_UNUSED_RESULT, and operator&().
ashr() [1/2]
APInt APInt::ashr (const APInt & shiftAmt) const
Arithmetic right-shift function.
Arithmetic right-shift this APInt by shiftAmt.
Definition at line 1037 of file APInt.cpp.
References ashr(), and getLimitedValue().
ashr() [2/2]
APInt APInt::ashr (unsigned shiftAmt) const
Arithmetic right-shift function.
Arithmetic right-shift this APInt by shiftAmt.
Definition at line 1043 of file APInt.cpp.
References APInt(), getNumWords(), isNegative(), pVal, and VAL.
Referenced by ashr(), llvm::APIntOps::ashr(), llvm::TargetLowering::BuildExactSDIV(), llvm::ConstantFoldBinaryInstruction(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::InstCombiner::FoldICmpCstShrCst(), llvm::InstCombiner::FoldICmpShrCst(), llvm::SelectionDAG::getNode(), llvm::APSInt::operator>>(), SimplifyICmpInst(), and llvm::Interpreter::visitAShr().
bitsToDouble()
double llvm::APInt::bitsToDouble () const inline
Converts APInt bits to a double.
The conversion does not do a translation from integer to double, it just re-interprets the bits as a double. Note that it is valid to do this on any bit width. Exactly 64 bits will be translated.
Definition at line 1455 of file APInt.h.
References I, pVal, T, and VAL.
Referenced by llvm::APFloat::convertToDouble(), and llvm::ExecutionEngine::getConstantValue().
bitsToFloat()
float llvm::APInt::bitsToFloat () const inline
Converts APInt bits to a double.
The conversion does not do a translation from integer to float, it just re-interprets the bits as a float. Note that it is valid to do this on any bit width. Exactly 32 bits will be translated.
Definition at line 1469 of file APInt.h.
References F, I, pVal, T, and VAL.
Referenced by llvm::APFloat::convertToFloat(), and llvm::ExecutionEngine::getConstantValue().
byteSwap()
APInt APInt::byteSwap () const
Returns
a byte-swapped representation of this APInt Value.
Definition at line 782 of file APInt.cpp.
References APInt(), llvm::ByteSwap_16(), llvm::ByteSwap_32(), llvm::ByteSwap_64(), getNumWords(), I, lshrNear(), N, pVal, and VAL.
Referenced by llvm::APIntOps::byteSwap(), llvm::SelectionDAG::getNode(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
ceilLogBase2()
unsigned llvm::APInt::ceilLogBase2 () const inline
Returns
the ceil log base 2 of this APInt.
Definition at line 1512 of file APInt.h.
References countLeadingZeros().
clearAllBits()
void llvm::APInt::clearAllBits () inline
Set every bit to 0.
Definition at line 1227 of file APInt.h.
References getNumWords(), pVal, and VAL.
Referenced by computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromAssume(), computeKnownBitsMul(), getUsefulBitsFromOrWithShiftedReg(), and operator*=().
clearBit()
void APInt::clearBit (unsigned bitPosition)
Set a given bit to 0.
Set the given bit to 0 whose position is given as "bitPosition".
Definition at line 597 of file APInt.cpp.
References pVal, and VAL.
Referenced by checkRippleForAdd(), ComputeSignedMinMaxValuesFromKnownBits(), flipBit(), and getSignedMaxValue().
countLeadingOnes()
unsigned APInt::countLeadingOnes () const
Count the number of leading one bits.
This function is an APInt version of the countLeadingOnes_{32,64} functions in MathExtras.h. It counts the number of ones from the most significant bit to the first zero bit.
Returns
0 if the high order bit is not set, otherwise returns the number of 1 bits from the most significant to the least
Definition at line 714 of file APInt.cpp.
References llvm::CountLeadingOnes_64(), getNumWords(), pVal, and VAL.
Referenced by computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsMul(), llvm::computeOverflowForUnsignedMul(), getMinSignedBits(), getNumSignBits(), isU24(), SimplifyICmpInst(), sshl_ov(), and llvm::InstCombiner::visitSwitchInst().
countLeadingZeros()
unsigned llvm::APInt::countLeadingZeros () const inline
The APInt version of the countLeadingZeros functions in MathExtras.h.
It counts the number of zeros from the most significant bit to the first one bit.
Returns
BitWidth if the value is zero, otherwise returns the number of zeros from the most significant bit to the first one bits.
Definition at line 1349 of file APInt.h.
References llvm::countLeadingZeros(), and VAL.
Referenced by areUsedBitsDense(), ceilLogBase2(), checkRippleForAdd(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), ComputeNumSignBits(), llvm::SelectionDAG::ComputeNumSignBits(), getActiveBits(), llvm::SelectionDAG::getNode(), getNumSignBits(), isBitfieldInsertOpFromOr(), logBase2(), ProcessUMulZExtIdiom(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), SimplifyICmpInst(), sshl_ov(), ushl_ov(), llvm::InstCombiner::visitAnd(), and llvm::InstCombiner::visitCallInst().
countPopulation()
unsigned llvm::APInt::countPopulation () const inline
Count the number of bits set.
This function is an APInt version of the countPopulation_{32,64} functions in MathExtras.h. It counts the number of 1 bits in the APInt value.
Returns
0 if the value is zero, otherwise returns the number of set bits.
Definition at line 1403 of file APInt.h.
References llvm::CountPopulation_64(), and VAL.
Referenced by checkRippleForAdd(), llvm::SelectionDAG::getNode(), isMaxSignedValue(), and ValueHasExactlyOneBitSet().
countTrailingOnes()
unsigned llvm::APInt::countTrailingOnes () const inline
Count the number of trailing one bits.
This function is an APInt version of the countTrailingOnes_{32,64} functions in MathExtras.h. It counts the number of ones from the least significant bit to the first zero bit.
Returns
BitWidth if the value is all ones, otherwise returns the number of ones from the least significant bit to the first zero bit.
Definition at line 1391 of file APInt.h.
References llvm::CountTrailingOnes_64(), and VAL.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsMul(), DemandedBitsLHSMask(), isWordAligned(), and llvm::TargetLowering::SimplifySetCC().
countTrailingZeros()
unsigned APInt::countTrailingZeros () const
Count the number of trailing zero bits.
This function is an APInt version of the countTrailingZeros_{32,64} functions in MathExtras.h. It counts the number of zeros from the least significant bit to the first set bit.
Returns
BitWidth if the value is zero, otherwise returns the number of zeros from the least significant bit to the first one bit.
Definition at line 741 of file APInt.cpp.
References llvm::countTrailingZeros(), getNumWords(), pVal, and VAL.
Referenced by areUsedBitsDense(), llvm::TargetLowering::BuildExactSDIV(), llvm::TargetLowering::BuildUDIV(), checkForNegativeOperand(), DemandedBitsLHSMask(), llvm::InstCombiner::FoldICmpCstShlCst(), llvm::SelectionDAG::getNode(), isBitfieldInsertOpFromOr(), ProcessUGT_ADDCST_ADD(), SimplifyICmpInst(), llvm::TargetLowering::SimplifySetCC(), SolveLinEquationWithOverflow(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInst(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
doubleToBits()
APInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APInt::doubleToBits (double V) inline static
Converts a double to APInt bits.
The conversion does not do a translation from double to integer, it just re-interprets the bits of the double.
Definition at line 1482 of file APInt.h.
References APInt(), I, LLVM_ATTRIBUTE_UNUSED_RESULT, and T.
Referenced by llvm::APFloat::APFloat(), and llvm::ExecutionEngine::getConstantValue().
dump()
void APInt::dump () const
debug method
Definition at line 2294 of file APInt.cpp.
References llvm::dbgs(), llvm::SmallString< InternalLen >::str(), toStringSigned(), and toStringUnsigned().
eq()
bool llvm::APInt::eq (const APInt & RHS) const inline
Equality comparison.
Compares this APInt with RHS for the validity of the equality relationship.
Returns
true if *this == Val
Definition at line 997 of file APInt.h.
Referenced by llvm::APSInt::isSameValue(), llvm::APSInt::operator==(), ProcessUMulZExtIdiom(), sgt(), sle(), ugt(), and ule().
exactLogBase2()
int32_t llvm::APInt::exactLogBase2 () const inline
Returns
the log base 2 of this APInt if its an exact power of two, -1 otherwise
Definition at line 1547 of file APInt.h.
References isPowerOf2(), and logBase2().
flipAllBits()
void llvm::APInt::flipAllBits () inline
Toggle every bit to its opposite value.
Definition at line 1240 of file APInt.h.
References getNumWords(), pVal, and VAL.
Referenced by getUsefulBits(), getUsefulBitsFromOrWithShiftedReg(), operator~(), slt(), and toString().
flipBit()
void APInt::flipBit (unsigned bitPosition)
Toggles a given bit to its opposite value.
Toggle every bit to its opposite value.
Toggle a given bit to its opposite value whose position is given as "bitPosition".
Toggle a given bit to its opposite value whose position is given as "bitPosition".
Toggles a given bit to its opposite value.
Definition at line 609 of file APInt.cpp.
References clearBit(), and setBit().
floatToBits()
APInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APInt::floatToBits (float V) inline static
Converts a float to APInt bits.
The conversion does not do a translation from float to integer, it just re-interprets the bits of the float.
Definition at line 1495 of file APInt.h.
References APInt(), F, I, LLVM_ATTRIBUTE_UNUSED_RESULT, and T.
Referenced by llvm::APFloat::APFloat(), and llvm::ExecutionEngine::getConstantValue().
getActiveBits()
unsigned llvm::APInt::getActiveBits () const inline
Compute the number of active bits in the value.
This function returns the number of active bits which is defined as the bit width minus the number of leading zeros. This is used in several computations to see how "wide" the value is.
Definition at line 1285 of file APInt.h.
References countLeadingZeros().
Referenced by areUsedBitsDense(), getActiveWords(), getLimitedValue(), getMinSignedBits(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), getZExtValue(), isDereferenceablePointer(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), isIndexInRangeOfSequentialType(), isIntN(), operator*=(), roundToDouble(), llvm::TargetLowering::SimplifySetCC(), sqrt(), udiv(), udivrem(), ult(), urem(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
getActiveWords()
unsigned llvm::APInt::getActiveWords () const inline
Compute the number of active words in the value of this APInt.
This is used in conjunction with getActiveData to extract the raw value of the APInt.
Definition at line 1291 of file APInt.h.
References getActiveBits().
getAllOnesValue()
APInt llvm::APInt::getAllOnesValue (unsigned numBits) inline static
Get the all-ones value.
Returns
the all-ones value for an APInt of the specified bit-width.
Definition at line 449 of file APInt.h.
References APInt().
Referenced by computeKnownBits(), DemandedBitsLHSMask(), llvm::APFloat::getAllOnesValue(), llvm::Constant::getAllOnesValue(), getHighBitsSet(), llvm::SelectionDAG::getLogicalNOT(), getLowBitsSet(), llvm::IntegerType::getMask(), getMaxValue(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), getSignedMaxValue(), isConditionalZeroOrAllOnes(), LowerSIGN_EXTEND_AVX512(), magicu(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::TargetLowering::SimplifyDemandedBits(), SimplifyICmpInst(), llvm::TargetLowering::SimplifySetCC(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitSelectInst(), llvm::InstCombiner::visitShuffleVectorInst(), and WidenMaskArithmetic().
getBitsNeeded()
unsigned APInt::getBitsNeeded (StringRef str, uint8_t radix) static
Get bits required for string value.
This method determines how many bits are required to hold the APInt equivalent of the string given by str.
Definition at line 615 of file APInt.cpp.
References llvm::StringRef::begin(), llvm::StringRef::empty(), isNegative(), logBase2(), and llvm::StringRef::size().
getBitsSet()
APInt llvm::APInt::getBitsSet (unsigned numBits, unsigned loBit, unsigned hiBit) inline static
Get a value with a block of bits set.
Constructs an APInt value that has a contiguous range of bits set. The bits from loBit (inclusive) to hiBit (exclusive) will be set. All other bits will be zero. For example, with parameters(32, 0, 16) you would get 0x0000FFFF. If hiBit is less than loBit then the set bits "wrap". For example, with parameters (32, 28, 4), you would get 0xF000000F.
Parameters
numBits the intended bit width of the result
loBit the index of the lowest bit set.
hiBit the index of the highest bit set.
Returns
An APInt value with the requested bits set.
Definition at line 494 of file APInt.h.
References getHighBitsSet(), getLowBitsSet(), and shl().
Referenced by llvm::SelectionDAG::computeKnownBits(), isBitfieldInsertOpFromOr(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::InstCombiner::visitCallInst().
getBitWidth()
unsigned llvm::APInt::getBitWidth () const inline
Return the number of bits in the APInt.
Definition at line 1261 of file APInt.h.
Referenced by llvm::GEPOperator::accumulateConstantOffset(), llvm::DwarfUnit::addConstantFPValue(), llvm::DwarfUnit::addConstantValue(), APIntToHexString(), llvm::TargetLowering::BuildExactSDIV(), llvm::TargetLowering::BuildUDIV(), checkRippleForAdd(), llvm::InstCombiner::commonIDivTransforms(), computeKnownBits(), computeKnownBitsAddSub(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::PPCTargetLowering::computeKnownBitsForTargetNode(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::TargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsMul(), llvm::ComputeMultiple(), ComputeNumSignBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), ComputeRange(), ComputeSignedMinMaxValuesFromKnownBits(), ComputeUnsignedMinMaxValuesFromKnownBits(), llvm::ConstantFoldBinaryInstruction(), llvm::APFloat::convertToInteger(), emitGlobalConstantFP(), llvm::InstCombiner::FoldICmpCstShlCst(), llvm::InstCombiner::FoldICmpShrCst(), gcd(), getAdjustedPtr(), llvm::StringRef::getAsInteger(), llvm::ExecutionEngine::getConstantValue(), GetLinearExpression(), llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), getNaturalGEPRecursively(), getNaturalGEPWithOffset(), llvm::SelectionDAG::getNode(), getShiftAmount(), getStrideFromPointer(), getUsefulBits(), getUsefulBitsFromAndWithImmediate(), getUsefulBitsFromBFM(), getUsefulBitsFromBitfieldMoveOpd(), IncorporateWeight(), isBitfieldInsertOpFromOr(), llvm::isBytewiseValue(), llvm::Value::isDereferenceablePointer(), llvm::DenseMapAPIntKeyInfo::isEqual(), llvm::SIInstrInfo::isInlineConstant(), isLikelyComplexAddressComputation(), llvm::APIntOps::isMask(), IsMultiple(), isSameValue(), llvm::APSInt::isSameValue(), isStridedPtr(), magicu(), MaskedValueIsZero(), operator&(), operator[](), operator|(), PerformORCombine(), performORCombine(), ProcessUMulZExtIdiom(), sge(), sgt(), ShrinkDemandedConstant(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), sle(), slt(), SolveLinEquationWithOverflow(), SolveQuadraticEquation(), sshl_ov(), llvm::Value::stripAndAccumulateInBoundsConstantOffsets(), llvm::ConstantRange::subtract(), toString(), udivrem(), uge(), ugt(), ule(), ult(), ushl_ov(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), and llvm::WriteConstantInternal().
getBoolValue()
bool llvm::APInt::getBoolValue () const inline
Convert APInt to a boolean value.
This converts the APInt to a boolean value as a test against zero.
Definition at line 403 of file APInt.h.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::Value::isDereferenceablePointer(), isKnownToBeAPowerOfTwo(), nearestLogBase2(), llvm::PPCTargetLowering::SelectAddressRegReg(), SimplifyAndOfICmps(), and SimplifyOrOfICmps().
getHiBits()
APInt APInt::getHiBits (unsigned numBits) const
Compute an APInt containing numBits highbits from this APInt.
HiBits - This function returns the high "numBits" bits of this APInt.
Get an APInt with the same BitWidth as this APInt, just zero mask the low bits and right shift to the least significant bit.
Returns
the high "numBits" bits of this APInt.
Definition at line 676 of file APInt.cpp.
References llvm::APIntOps::lshr().
Referenced by llvm::SIInstrInfo::expandPostRAPseudo(), and llvm::TargetLowering::SimplifyDemandedBits().
getHighBitsSet()
APInt llvm::APInt::getHighBitsSet (unsigned numBits, unsigned hiBitsSet) inline static
Get a value with high bits set.
Constructs an APInt value that has the top hiBitsSet bits set.
Parameters
numBits the bitwidth of the result
hiBitsSet the number of high-order bits set in the result.
Definition at line 509 of file APInt.h.
References APInt(), getAllOnesValue(), and shl().
Referenced by CanEvaluateShifted(), CanEvaluateTruncated(), CanEvaluateZExtd(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsAddSub(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsMul(), llvm::TargetLowering::expandMUL(), llvm::InstCombiner::FoldICmpShrCst(), FoldMaskAndShiftToScale(), llvm::InstCombiner::FoldShiftByConstant(), getBitsSet(), GetShiftedValue(), isTruncWithZeroHighBitsInput(), LowerFCOPYSIGN(), PerformSELECTCombine(), PerformShiftCombine(), llvm::ConstantRange::signExtend(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitShl(), and llvm::InstCombiner::visitZExt().
getLimitedValue()
uint64_t llvm::APInt::getLimitedValue (uint64_t Limit = ~0ULL) const inline
If this value is smaller than the specified limit, return it, otherwise return the limit value. This causes the value to saturate to the limit.
Definition at line 407 of file APInt.h.
References getActiveBits(), and getZExtValue().
Referenced by APIntToHexString(), ashr(), llvm::InstCombiner::commonIDivTransforms(), llvm::ComputeMultiple(), GetLinearExpression(), lshr(), rotl(), rotr(), shl(), and SwitchToLookupTable().
getLoBits()
APInt APInt::getLoBits (unsigned numBits) const
Compute an APInt containing numBits lowbits from this APInt.
LoBits - This function returns the low "numBits" bits of this APInt.
Get an APInt with the same BitWidth as this APInt, just zero mask the high bits.
Returns
the low "numBits" bits of this APInt.
Definition at line 681 of file APInt.cpp.
References llvm::APIntOps::lshr(), and llvm::APIntOps::shl().
Referenced by llvm::SIInstrInfo::expandPostRAPseudo(), getTargetShuffleMask(), matchRotateSub(), and llvm::TargetLowering::SimplifyDemandedBits().
getLowBitsSet()
APInt llvm::APInt::getLowBitsSet (unsigned numBits, unsigned loBitsSet) inline static
Get a value with low bits set.
Constructs an APInt value that has the bottom loBitsSet bits set.
Parameters
numBits the bitwidth of the result
loBitsSet the number of low-order bits set in the result.
Definition at line 527 of file APInt.h.
References APInt(), getAllOnesValue(), and lshr().
Referenced by CanEvaluateShifted(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsMul(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldInstOperands(), DemandedBitsLHSMask(), llvm::InstCombiner::FoldAndOfICmps(), llvm::InstCombiner::FoldShiftByConstant(), getBitsSet(), GetShiftedValue(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::APIntOps::isMask(), LowerFCOPYSIGN(), PerformBTCombine(), ProcessUGT_ADDCST_ADD(), llvm::ConstantRange::signExtend(), llvm::TargetLowering::SimplifyDemandedBits(), simplifyI24(), llvm::TargetLowering::SimplifySetCC(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitLShr(), and llvm::InstCombiner::visitZExt().
getMaxValue()
APInt llvm::APInt::getMaxValue (unsigned numBits) inline static
Gets maximum unsigned value of APInt for specific bit width.
Definition at line 417 of file APInt.h.
References getAllOnesValue().
Referenced by llvm::ConstantRange::ConstantRange(), llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::APSInt::getMaxValue(), llvm::ConstantRange::getUnsignedMax(), llvm::ScalarEvolution::getUnsignedRange(), llvm::ScalarEvolution::getZeroExtendExpr(), ProcessUMulZExtIdiom(), llvm::TargetLowering::SimplifySetCC(), and llvm::ConstantRange::truncate().
getMinSignedBits()
unsigned llvm::APInt::getMinSignedBits () const inline
Get the minimum bit size for this signed APInt.
Computes the minimum bit width for this APInt while considering it to be a signed (and probably negative) value. If the value is not negative, this function returns the same value as getActiveBits()+1. Otherwise, it returns the smallest bit width that will retain the negative value. For example, -1 can be written as 0b1 or 0xFFFFFFFFFF. 0b1 is shorter and so for -1, this function will always return 1.
Definition at line 1304 of file APInt.h.
References countLeadingOnes(), getActiveBits(), and isNegative().
Referenced by canFoldIVIncExpr(), getSExtValue(), isSignedIntN(), and llvm::TargetLowering::SimplifySetCC().
getMinValue()
APInt llvm::APInt::getMinValue (unsigned numBits) inline static
Gets minimum unsigned value of APInt for a specific bit width.
Definition at line 429 of file APInt.h.
References APInt().
Referenced by llvm::ConstantRange::ConstantRange(), llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::APSInt::getMinValue(), llvm::ConstantRange::getUnsignedMin(), llvm::ScalarEvolution::getUnsignedRange(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::ICmpInst::makeConstantRange(), llvm::ConstantRange::makeICmpRegion(), and llvm::TargetLowering::SimplifySetCC().
getNullValue()
APInt llvm::APInt::getNullValue (unsigned numBits) inline static
Get the '0' value.
Returns
the '0' value for an APInt of the specified bit-width.
Definition at line 456 of file APInt.h.
References APInt().
Referenced by llvm::ConstantRange::binaryAnd(), llvm::ConstantRange::binaryOr(), llvm::ObjectSizeOffsetVisitor::compute(), llvm::ConstantFoldCastInstruction(), llvm::SelectionDAG::getNode(), llvm::Constant::getNullValue(), llvm::ConstantRange::makeICmpRegion(), and stripAndComputeConstantOffsets().
getNumSignBits()
unsigned llvm::APInt::getNumSignBits () const inline
Computes the number of leading bits of this APInt that are equal to its sign bit.
Definition at line 1369 of file APInt.h.
References countLeadingOnes(), countLeadingZeros(), and isNegative().
Referenced by llvm::SelectionDAG::ComputeNumSignBits(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), and llvm::TargetLowering::SimplifySetCC().
getNumWords() [1/2]
unsigned llvm::APInt::getNumWords () const inline
Get the number of words.
Here one word's bitwidth equals to that of uint64_t.
Returns
the number of words to hold the integer value of this APInt.
Definition at line 1268 of file APInt.h.
References getNumWords().
Referenced by ashr(), byteSwap(), clearAllBits(), llvm::APFloat::convertFromAPInt(), llvm::APFloat::convertToInteger(), countLeadingOnes(), countTrailingZeros(), emitGlobalConstantFP(), flipAllBits(), getNumWords(), llvm::hash_value(), lshr(), operator!(), operator&=(), operator*=(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator=(), operator^=(), operator|=(), Profile(), setAllBits(), sext(), toString(), trunc(), and zext().
getNumWords() [2/2]
unsigned llvm::APInt::getNumWords (unsigned BitWidth) inline static
Get the number of words.
NOTE Here one word's bitwidth equals to that of uint64_t.
Returns
the number of words to hold the integer value with a given bit width.
Definition at line 1276 of file APInt.h.
getOneBitSet()
APInt llvm::APInt::getOneBitSet (unsigned numBits, unsigned BitNo) inline static
Return an APInt with exactly one bit set in the result.
Definition at line 475 of file APInt.h.
References setBit().
Referenced by BinomialCoefficient(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::FoldICmpShrCst(), IncorporateWeight(), ProcessUMulZExtIdiom(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), and llvm::ConstantRange::zeroExtend().
getRawData()
const uint64_t * llvm::APInt::getRawData () const inline
This function returns a pointer to the internal storage of the APInt. This is useful for writing out the APInt in binary form without any conversions.
Definition at line 569 of file APInt.h.
References pVal, and VAL.
Referenced by llvm::DwarfUnit::addConstantFPValue(), llvm::DwarfUnit::addConstantValue(), llvm::APFloat::convertFromAPInt(), llvm::APFloat::convertFromZeroExtendedInteger(), emitGlobalConstantFP(), emitGlobalConstantLargeInt(), llvm::HexagonLowerToMC(), sext(), llvm::ExecutionEngine::StoreValueToMemory(), toString(), trunc(), llvm::WriteConstantInternal(), WriteConstants(), and zext().
getSExtValue()
int64_t llvm::APInt::getSExtValue () const inline
Get sign extended value.
This method attempts to return the value of this APInt as a sign extended int64_t. The bit width must be <= 64 or the value must fit within an int64_t. Otherwise an assertion will result.
Definition at line 1327 of file APInt.h.
References getMinSignedBits(), pVal, and VAL.
Referenced by llvm::DwarfUnit::addConstantValue(), llvm::InstCombiner::commonPointerCastTransforms(), DecomposeGEPExpression(), llvm::ExecutionEngine::getConstantValue(), llvm::GetPointerBaseWithConstantOffset(), getStrideFromPointer(), getVShiftImm(), getVShiftImm(), llvm::SIInstrInfo::isInlineConstant(), isLikelyComplexAddressComputation(), isStridedPtr(), LLVMGenericValueToInt(), llvm::AsmPrinter::lowerConstant(), llvm::AArch64TargetLowering::shouldConvertConstantLoadToIntImm(), llvm::TargetLowering::SimplifySetCC(), toString(), tryCombineShiftImm(), and llvm::InstCombiner::visitGetElementPtrInst().
getSignBit()
APInt llvm::APInt::getSignBit (unsigned BitWidth) inline static
Get the SignBit for a specific bit width.
This is just a wrapper function of getSignedMinValue(), and it helps code readability when we want to get a SignBit.
Definition at line 442 of file APInt.h.
References getSignedMinValue().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsAddSub(), computeKnownBitsFromAssume(), decomposeBitTestICmp(), DemandedBitsLHSMask(), llvm::TargetLowering::expandFP_TO_SINT(), LowerFABSorFNEG(), LowerVSETCC(), llvm::SelectionDAG::SignBitIsZero(), llvm::TargetLowering::SimplifyDemandedBits(), SimplifySelectInst(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSelectInstWithICmp(), and llvm::InstCombiner::visitSRem().
getSignedMaxValue()
APInt llvm::APInt::getSignedMaxValue (unsigned numBits) inline static
Gets maximum signed value of APInt for a specific bit width.
Definition at line 422 of file APInt.h.
References clearBit(), and getAllOnesValue().
Referenced by llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::InstCombiner::FoldICmpAddOpCst(), llvm::APSInt::getMaxValue(), getOverflowLimitForStep(), llvm::ConstantRange::getSignedMax(), llvm::ScalarEvolution::getSignedRange(), isKnownNonZero(), llvm::ConstantRange::isSignWrappedSet(), LowerFABSorFNEG(), magicu(), SimplifyICmpInst(), and llvm::TargetLowering::SimplifySetCC().
getSignedMinValue()
APInt llvm::APInt::getSignedMinValue (unsigned numBits) inline static
Gets minimum signed value of APInt for a specific bit width.
Definition at line 432 of file APInt.h.
References setBit().
Referenced by BinomialCoefficient(), llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::APSInt::getMinValue(), getOverflowLimitForStep(), getSignBit(), llvm::ConstantRange::getSignedMin(), llvm::ScalarEvolution::getSignedRange(), llvm::ConstantRange::isSignWrappedSet(), magicu(), llvm::ICmpInst::makeConstantRange(), llvm::ConstantRange::makeICmpRegion(), SimplifyICmpInst(), and llvm::TargetLowering::SimplifySetCC().
getSplat()
APInt llvm::APInt::getSplat (unsigned NewLen, const APInt & V) inline static
Return a value containing V broadcasted over NewLen bits.
Definition at line 541 of file APInt.h.
References I.
Referenced by getMemsetValue(), and LowerCTPOP().
getZExtValue()
uint64_t llvm::APInt::getZExtValue () const inline
Get zero extended value.
This method attempts to return the value of this APInt as a zero extended uint64_t. The bitwidth must be <= 64 or the value must fit within a uint64_t. Otherwise an assertion will result.
Definition at line 1315 of file APInt.h.
References getActiveBits(), pVal, and VAL.
Referenced by llvm::DwarfUnit::addConstantValue(), ComputeNumSignBits(), llvm::ConstantFoldTerminator(), llvm::Interpreter::exitCalled(), llvm::SIInstrInfo::expandPostRAPseudo(), ExtractBranchMetadata(), FoldOperand(), FoldReinterpretLoadFromConstPtr(), GetBranchWeights(), llvm::ExecutionEngine::getConstantValue(), llvm::AArch64_AM::getFP32Imm(), llvm::ARM_AM::getFP32Imm(), llvm::AArch64_AM::getFP64Imm(), llvm::ARM_AM::getFP64Imm(), getLimitedValue(), getNaturalGEPRecursively(), getTargetShuffleMask(), IncorporateWeight(), isEXTMask(), llvm::SIInstrInfo::isInlineConstant(), LLVMGenericValueToInt(), LowerShift(), NormalizeBuildVector(), PerformANDCombine(), performDSPShiftCombine(), PerformINTRINSIC_WO_CHAINCombine(), PerformORCombine(), llvm::NVPTXFloatMCExpr::PrintImpl(), llvm::ExecutionEngine::runFunctionAsMain(), llvm::PPCTargetLowering::SelectAddressRegImm(), SymbolicallyEvaluateGEP(), llvm::APFloat::toString(), toString(), tryToFoldExtendOfConstant(), llvm::Interpreter::visitAShr(), llvm::Interpreter::visitExtractElementInst(), llvm::Interpreter::visitInsertElementInst(), llvm::Interpreter::visitLShr(), llvm::Interpreter::visitShl(), and llvm::WriteConstantInternal().
intersects()
bool llvm::APInt::intersects (const APInt & RHS) const inline
This operation tests if there are any pairs of corresponding bits between this APInt and RHS that are both set.
Definition at line 1153 of file APInt.h.
Referenced by llvm::SelectionDAGISel::CheckAndMask(), llvm::SelectionDAGISel::CheckOrMask(), llvm::SelectionDAG::computeKnownBits(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifySetCC().
isAllOnesValue()
bool llvm::APInt::isAllOnesValue () const inline
Determine if all bits are set.
This checks to see if the value has all bits of the APInt are set or not.
Definition at line 339 of file APInt.h.
References VAL.
Referenced by areUsedBitsDense(), llvm::ConstantRange::binaryAnd(), computeKnownBitsFromAssume(), createAndInstr(), llvm::InstCombiner::FoldAndOfICmps(), llvm::InstCombiner::FoldICmpCstShrCst(), llvm::InstCombiner::FoldOrWithConstants(), llvm::InstCombiner::FoldXorWithConstants(), getExactSDiv(), isMaxValue(), isVectorAllOnes(), MatchNotExpr(), performORCombine(), sdiv_ov(), llvm::TargetLowering::SimplifyDemandedBits(), SimplifyICmpInst(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
isIntN()
bool llvm::APInt::isIntN (unsigned N) const inline
Check if this APInt has an N-bits unsigned integer value.
Definition at line 375 of file APInt.h.
References getActiveBits(), and N.
Referenced by AreMulWideOperandsDemotable(), and llvm::APIntOps::isIntN().
isMaxSignedValue()
bool llvm::APInt::isMaxSignedValue () const inline
Determine if this is the largest signed value.
This checks to see if the value of this APInt is the maximum signed value for the APInt's bit width.
Definition at line 355 of file APInt.h.
References countPopulation(), isNegative(), and VAL.
Referenced by llvm::ScalarEvolution::getSignedRange(), llvm::ConstantRange::makeICmpRegion(), and llvm::ScalarEvolution::SimplifyICmpOperands().
isMaxValue()
bool llvm::APInt::isMaxValue () const inline
Determine if this is the largest unsigned value.
This checks to see if the value of this APInt is the maximum unsigned value for the APInt's bit width.
Definition at line 349 of file APInt.h.
References isAllOnesValue().
Referenced by llvm::ScalarEvolution::getUnsignedRange(), llvm::ConstantRange::makeICmpRegion(), and llvm::ScalarEvolution::SimplifyICmpOperands().
isMinSignedValue()
bool llvm::APInt::isMinSignedValue () const inline
Determine if this is the smallest signed value.
This checks to see if the value of this APInt is the minimum signed value for the APInt's bit width.
Definition at line 370 of file APInt.h.
References isNegative(), isPowerOf2(), and VAL.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ScalarEvolution::getSignedRange(), isSignBit(), llvm::ConstantRange::makeICmpRegion(), sdiv_ov(), and llvm::ScalarEvolution::SimplifyICmpOperands().
isMinValue()
bool llvm::APInt::isMinValue () const inline
Determine if this is the smallest unsigned value.
This checks to see if the value of this APInt is the minimum unsigned value for the APInt's bit width.
Definition at line 364 of file APInt.h.
Referenced by llvm::ScalarEvolution::getUnsignedRange(), IncorporateWeight(), IsMultiple(), LinearizeExprTree(), llvm::ConstantRange::makeICmpRegion(), llvm::ScalarEvolution::SimplifyICmpOperands(), SolveQuadraticEquation(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
isNegative()
bool llvm::APInt::isNegative () const inline
Determine sign of this APInt.
This tests the high bit of this APInt to determine if it is set.
Returns
true if this APInt is negative, false otherwise
Definition at line 321 of file APInt.h.
Referenced by abs(), ashr(), llvm::TargetLowering::BuildSDIV(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsAddSub(), computeKnownBitsFromAssume(), computeKnownBitsMul(), ComputeNumSignBits(), llvm::SelectionDAG::ComputeNumSignBits(), computePointerICmp(), ComputeSignedMinMaxValuesFromKnownBits(), llvm::APFloat::convertFromAPInt(), llvm::InstCombiner::FoldICmpCstShrCst(), FoldReinterpretLoadFromConstPtr(), getBitsNeeded(), getMinSignedBits(), getNumSignBits(), llvm::ScalarEvolution::isKnownNegative(), llvm::ScalarEvolution::isKnownNonNegative(), isMaxSignedValue(), isMinSignedValue(), isNonNegative(), llvm::APSInt::isSameValue(), multiplicativeInverse(), sdiv(), sdivrem(), ShrinkDemandedConstant(), llvm::TargetLowering::SimplifySetCC(), slt(), SolveQuadraticEquation(), srem(), toString(), llvm::InstCombiner::visitICmpInst(), and llvm::InstCombiner::visitMul().
isNonNegative()
bool llvm::APInt::isNonNegative () const inline
Determine if this APInt Value is non-negative (>= 0)
This tests the high bit of the APInt to determine if it is unset.
Definition at line 326 of file APInt.h.
References isNegative().
Referenced by computeKnownBits(), llvm::Value::isDereferenceablePointer(), isStrictlyPositive(), sadd_ov(), llvm::TargetLowering::SimplifySetCC(), sshl_ov(), ssub_ov(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
isPowerOf2()
bool llvm::APInt::isPowerOf2 () const inline
Check if this APInt's value is a power of two greater than zero.
Returns
true if the argument APInt value is a power of two > 0.
Definition at line 389 of file APInt.h.
References llvm::isPowerOf2_64(), and VAL.
Referenced by llvm::PPCTargetLowering::BuildSDIVPow2(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), exactLogBase2(), llvm::InstCombiner::FoldAndOfICmps(), llvm::InstCombiner::FoldOrOfICmps(), foldSelectICmpAnd(), getLogBase2Vector(), llvm::ScalarEvolution::getSignExtendExpr(), getTypeOfMaskedICmp(), isMinSignedValue(), performMulCombine(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), SimplifyICmpInst(), llvm::TargetLowering::SimplifySetCC(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), and llvm::InstCombiner::visitMul().
isSameValue()
bool llvm::APInt::isSameValue (const APInt & I1, const APInt & I2) inline static
Determine if two APInts have the same value, after zero-extending one of them (if needed!) to ensure that the bit-widths match.
Definition at line 553 of file APInt.h.
References getBitWidth(), and zext().
isSignBit()
bool llvm::APInt::isSignBit () const inline
Check if the APInt's value is returned by getSignBit.
Returns
true if this is the value returned by getSignBit.
Definition at line 398 of file APInt.h.
References isMinSignedValue().
Referenced by isSignBitCheck(), SimplifyICmpInst(), llvm::InstCombiner::visitAdd(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
isSignedIntN()
bool llvm::APInt::isSignedIntN (unsigned N) const inline
Check if this APInt has an N-bits signed integer value.
Definition at line 381 of file APInt.h.
References getMinSignedBits(), and N.
Referenced by AreMulWideOperandsDemotable(), and llvm::APIntOps::isSignedIntN().
isStrictlyPositive()
bool llvm::APInt::isStrictlyPositive () const inline
Determine if this APInt Value is positive.
This tests if the value of this APInt is positive (> 0). Note that 0 is not a positive value.
Returns
true if this APInt is positive.
Definition at line 334 of file APInt.h.
References isNonNegative().
Referenced by llvm::TargetLowering::BuildSDIV(), llvm::InstCombiner::FoldICmpDivCst(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::ScalarEvolution::isKnownNonPositive(), llvm::ScalarEvolution::isKnownPositive(), SimplifyAndOfICmps(), and SimplifyOrOfICmps().
logBase2()
unsigned llvm::APInt::logBase2 () const inline
Returns
the floor log base 2 of this APInt.
Definition at line 1509 of file APInt.h.
References countLeadingZeros().
Referenced by exactLogBase2(), llvm::InstCombiner::FoldICmpCstShrCst(), foldSelectICmpAnd(), foldSelectICmpAndOr(), foldUDivShl(), getBitsNeeded(), getLogBase2Vector(), isEXTMask(), llvm::APIntOps::logBase2(), nearestLogBase2(), performMulCombine(), ProcessUMulZExtIdiom(), llvm::TargetLowering::SimplifySetCC(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), and llvm::InstCombiner::visitMul().
lshr() [1/2]
APInt APInt::lshr (const APInt & shiftAmt) const
Logical right-shift function.
Logical right-shift this APInt by shiftAmt.
Definition at line 1128 of file APInt.cpp.
References getLimitedValue(), and lshr().
lshr() [2/2]
APInt APInt::lshr (unsigned shiftAmt) const
Logical right-shift function.
Logical right-shift this APInt by shiftAmt.
Definition at line 1134 of file APInt.cpp.
References APInt(), getNumWords(), lshrNear(), pVal, and VAL.
Referenced by areUsedBitsDense(), llvm::TargetLowering::BuildUDIV(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromAssume(), llvm::ConstantFoldBinaryInstruction(), emitGlobalConstantLargeInt(), ExtractConstantBytes(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::InstCombiner::FoldICmpCstShrCst(), llvm::InstCombiner::FoldICmpShrCst(), llvm::InstCombiner::FoldShiftByConstant(), llvm::SelectionDAG::getConstant(), llvm::AArch64_AM::getFP32Imm(), llvm::ARM_AM::getFP32Imm(), llvm::AArch64_AM::getFP64Imm(), llvm::ARM_AM::getFP64Imm(), getLowBitsSet(), getTargetShuffleMask(), getUsefulBitsFromBitfieldMoveOpd(), getUsefulBitsFromOrWithShiftedReg(), llvm::isBytewiseValue(), llvm::BuildVectorSDNode::isConstantSplat(), lowerMSABinaryBitImmIntr(), lshr(), llvm::APIntOps::lshr(), llvm::ConstantRange::lshr(), magicu(), llvm::APSInt::operator>>(), rotl(), rotr(), llvm::TargetLowering::SimplifyDemandedBits(), SimplifyICmpInst(), llvm::TargetLowering::SimplifySetCC(), SolveLinEquationWithOverflow(), toString(), llvm::Interpreter::visitLShr(), and llvm::InstCombiner::visitXor().
magic()
APInt::ms APInt::magic () const
Calculate the magic numbers required to implement a signed integer division by a constant as a sequence of multiplies, adds and shifts. Requires that the divisor not be 0, 1, or -1. Taken from "Hacker's Delight", Henry S. Warren, Jr., chapter 10.
Definition at line 1414 of file APInt.cpp.
Referenced by llvm::TargetLowering::BuildSDIV().
magicu()
APInt::mu APInt::magicu (unsigned LeadingZeros = 0) const
Calculate the magic numbers required to implement an unsigned integer division by a constant as a sequence of multiplies, adds and shifts. Requires that the divisor not be 0. Taken from "Hacker's Delight", Henry S. Warren, Jr., chapter 10. LeadingZeros can be used to simplify the calculation if the upper bits of the divided value are known zero.
Definition at line 1458 of file APInt.cpp.
References llvm::APInt::mu::a, allOnes(), getAllOnesValue(), getBitWidth(), getSignedMaxValue(), getSignedMinValue(), lshr(), llvm::APInt::mu::m, llvm::APInt::mu::s, udiv(), uge(), ult(), and urem().
Referenced by llvm::TargetLowering::BuildUDIV().
multiplicativeInverse()
APInt APInt::multiplicativeInverse (const APInt & modulo) const
Returns
the multiplicative inverse for a given modulo.
Computes the multiplicative inverse of this APInt for a given modulo. The iterative extended Euclidean algorithm is used to solve for this value, however we simplify it to speed up calculating only the inverse, and take advantage of div+rem calculations. We also use some tricks to avoid copying (potentially large) APInts around.
Definition at line 1371 of file APInt.cpp.
References APInt(), isNegative(), udivrem(), and ult().
Referenced by BinomialCoefficient(), and SolveLinEquationWithOverflow().
ne()
bool llvm::APInt::ne (const APInt & RHS) const inline
Inequality comparison.
Compares this APInt with RHS for the validity of the inequality relationship.
Returns
true if *this != Val
Definition at line 1021 of file APInt.h.
nearestLogBase2()
unsigned llvm::APInt::nearestLogBase2 () const inline
Returns
the nearest log base 2 of this APInt. Ties round up.
NOTE: When we have a BitWidth of 1, we define:
log2(0) = UINT32_MAX log2(1) = 0
to get around any mathematical concerns resulting from referencing 2 in a space where 2 does no exist.
Definition at line 1525 of file APInt.h.
References getBoolValue(), logBase2(), and VAL.
needsCleanup()
bool llvm::APInt::needsCleanup () const inline
Returns whether this instance allocated memory.
Definition at line 306 of file APInt.h.
Referenced by ~APInt().
operator!()
bool llvm::APInt::operator! () const inline
Logical negation operator.
Performs logical negation operation on this APInt.
Returns
true if *this is zero, false otherwise.
Definition at line 630 of file APInt.h.
References getNumWords(), pVal, and VAL.
operator!=() [1/2]
bool llvm::APInt::operator!= (const APInt & RHS) const inline
Inequality operator.
Compares this APInt with RHS for the validity of the inequality relationship.
Returns
true if *this != Val
Definition at line 1005 of file APInt.h.
operator!=() [2/2]
bool llvm::APInt::operator!= (uint64_t Val) const inline
Inequality operator.
Compares this APInt with a uint64_t for the validity of the inequality relationship.
Returns
true if *this != Val
Definition at line 1013 of file APInt.h.
operator&()
APInt llvm::APInt::operator& (const APInt & RHS) const inline
Bitwise AND operator.
Performs a bitwise AND operation on *this and RHS.
Returns
An APInt value representing the bitwise AND of *this and RHS.
Definition at line 770 of file APInt.h.
References APInt(), getBitWidth(), and VAL.
Referenced by And().
operator&=()
APInt & APInt::operator&= (const APInt & RHS)
Bitwise AND assignment operator.
Performs a bitwise AND operation on this APInt and RHS. The result is assigned to *this.
Returns
*this after ANDing with RHS.
Definition at line 398 of file APInt.cpp.
References getNumWords(), pVal, and VAL.
operator*()
APInt APInt::operator* (const APInt & RHS) const
Multiplication operator.
Multiplies this APInt by RHS and returns the result.
Definition at line 463 of file APInt.cpp.
References APInt(), and VAL.
operator*=()
APInt & APInt::operator*= (const APInt & RHS)
Multiplication assignment operator.
Multiplies this APInt by RHS and assigns the result to *this.
Returns
*this
Definition at line 356 of file APInt.cpp.
References clearAllBits(), getActiveBits(), getMemory(), getNumWords(), mul(), pVal, and VAL.
operator+() [1/2]
APInt APInt::operator+ (const APInt & RHS) const
Addition operator.
Adds RHS to this APInt and returns the result.
Definition at line 472 of file APInt.cpp.
References add(), APInt(), getNumWords(), pVal, and VAL.
operator+() [2/2]
APInt llvm::APInt::operator+ (uint64_t RHS) const inline
Definition at line 833 of file APInt.h.
References APInt().
operator++() [1/2]
APInt & APInt::operator++ ()
Prefix increment operator.
Prefix increment operator. Increments the APInt by one.
Returns
*this incremented by one
Definition at line 197 of file APInt.cpp.
References add_1(), getNumWords(), pVal, and VAL.
operator++() [2/2]
const APInt llvm::APInt::operator++ (int) inline
Postfix increment operator.
Returns
a new APInt value representing *this incremented by one
Definition at line 582 of file APInt.h.
operator+=()
APInt & APInt::operator+= (const APInt & RHS)
Addition assignment operator.
Adds RHS to *this and assigns the result to *this.
Returns
*this
Adds the RHS APint to this APInt.
Returns
this, after addition of RHS.
Definition at line 252 of file APInt.cpp.
References add(), getNumWords(), pVal, and VAL.
operator-() [1/3]
APInt llvm::APInt::operator- () const inline
Unary negation operator.
Negates *this using two's complement logic.
Returns
An APInt value representing the negation of *this.
Definition at line 623 of file APInt.h.
References APInt().
operator-() [2/3]
APInt APInt::operator- (const APInt & RHS) const
Subtraction operator.
Subtracts RHS from this APInt and returns the result.
Definition at line 482 of file APInt.cpp.
References APInt(), getNumWords(), pVal, sub(), and VAL.
operator-() [3/3]
APInt llvm::APInt::operator- (uint64_t RHS) const inline
Definition at line 839 of file APInt.h.
References APInt().
operator--() [1/2]
APInt & APInt::operator-- ()
Prefix decrement operator.
Prefix decrement operator. Decrements the APInt by one.
Returns
*this decremented by one.
Definition at line 226 of file APInt.cpp.
References getNumWords(), pVal, sub_1(), and VAL.
operator--() [2/2]
const APInt llvm::APInt::operator-- (int) inline
Postfix decrement operator.
Returns
a new APInt representing *this decremented by one.
Definition at line 596 of file APInt.h.
operator-=()
APInt & APInt::operator-= (const APInt & RHS)
Subtraction assignment operator.
Subtracts RHS from *this and assigns the result to *this.
Returns
*this
Subtracts the RHS APInt from this APInt
Returns
this, after subtraction
Definition at line 279 of file APInt.cpp.
References getNumWords(), pVal, sub(), and VAL.
operator<<() [1/2]
APInt llvm::APInt::operator<< (const APInt & Bits) const inline
Left logical shift operator.
Shifts this APInt left by Bits and returns the result.
Definition at line 849 of file APInt.h.
References shl().
operator<<() [2/2]
APInt llvm::APInt::operator<< (unsigned Bits) const inline
Left logical shift operator.
Shifts this APInt left by Bits and returns the result.
Definition at line 844 of file APInt.h.
References shl().
operator<<=()
APInt & llvm::APInt::operator<<= (unsigned shiftAmt) inline
Left-shift assignment function.
Shifts *this left by shiftAmt and assigns the result to *this.
Returns
*this after shifting left by shiftAmt
Definition at line 756 of file APInt.h.
References shl().
operator=() [1/3]
APInt & llvm::APInt::operator= (APInt && that) inline
Move assignment operator.
Definition at line 659 of file APInt.h.
References pVal, and VAL.
operator=() [2/3]
APInt & llvm::APInt::operator= (const APInt & RHS) inline
Copy assignment operator.
Returns
*this after assignment of RHS.
Definition at line 647 of file APInt.h.
References VAL.
Referenced by llvm::APSInt::operator=(), and llvm::APSInt::operator=().
operator=() [3/3]
APInt & APInt::operator= (uint64_t RHS)
Assignment operator.
The RHS value is assigned to *this. If the significant bits in RHS exceed the bit width, the excess bits are truncated. If the bit width is larger than 64, the value is zero filled in the unspecified high order bits.
Returns
*this after assignment of RHS value.
Definition at line 155 of file APInt.cpp.
References getNumWords(), pVal, and VAL.
operator==() [1/2]
bool llvm::APInt::operator== (const APInt & RHS) const inline
Equality operator.
Compares this APInt with RHS for the validity of the equality relationship.
Definition at line 972 of file APInt.h.
References VAL.
operator==() [2/2]
bool llvm::APInt::operator== (uint64_t Val) const inline
Equality operator.
Compares this APInt with a uint64_t for the validity of the equality relationship.
Returns
true if *this == Val
Definition at line 985 of file APInt.h.
References VAL.
operator[]()
bool llvm::APInt::operator[] (unsigned bitPosition) const inline
Array-indexing support.
Returns
the bit value at bitPosition
Definition at line 957 of file APInt.h.
References getBitWidth(), pVal, and VAL.
operator^()
APInt llvm::APInt::operator^ (const APInt & RHS) const inline
Bitwise XOR operator.
Performs a bitwise XOR operation on *this and RHS.
Returns
An APInt value representing the bitwise XOR of *this and RHS.
Definition at line 807 of file APInt.h.
References APInt(), and VAL.
Referenced by Xor().
operator^=()
APInt & APInt::operator^= (const APInt & RHS)
Bitwise XOR assignment operator.
Performs a bitwise XOR operation on this APInt and RHS. The result is assigned to *this.
Returns
*this after XORing with RHS.
Definition at line 422 of file APInt.cpp.
References getNumWords(), pVal, and VAL.
operator|()
APInt llvm::APInt::operator| (const APInt & RHS) const inline
Bitwise OR operator.
Performs a bitwise OR operation on *this and RHS.
Returns
An APInt value representing the bitwise OR of *this and RHS.
Definition at line 785 of file APInt.h.
References APInt(), getBitWidth(), and VAL.
Referenced by Or().
operator|=() [1/2]
APInt & APInt::operator|= (const APInt & RHS)
Bitwise OR assignment operator.
Performs a bitwise OR operation on this APInt and RHS. The result is assigned *this;
Returns
*this after ORing with RHS.
Definition at line 410 of file APInt.cpp.
References getNumWords(), pVal, and VAL.
operator|=() [2/2]
APInt & llvm::APInt::operator|= (uint64_t RHS) inline
Bitwise OR assignment operator.
Performs a bitwise OR operation on this APInt and RHS. RHS is logically zero-extended or truncated to match the bit-width of the LHS.
Definition at line 712 of file APInt.h.
References pVal, and VAL.
operator~()
APInt llvm::APInt::operator~ () const inline
Unary bitwise complement operator.
Performs a bitwise complement operation on this APInt.
Returns
an APInt that is the bitwise complement of *this
Definition at line 612 of file APInt.h.
References flipAllBits().
Or()
APInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APInt::Or (const APInt & RHS) const inline
Bitwise OR function.
Performs a bitwise or on *this and RHS. This is implemented bny simply calling operator|.
Returns
An APInt value representing the bitwise OR of *this and RHS.
Definition at line 798 of file APInt.h.
References LLVM_ATTRIBUTE_UNUSED_RESULT, and operator|().
print()
void APInt::print (raw_ostream & OS, bool isSigned) const
Definition at line 2302 of file APInt.cpp.
References llvm::SmallString< InternalLen >::str(), and toString().
Referenced by llvm::MachineOperand::print().
Profile()
void APInt::Profile (FoldingSetNodeID & id) const
Profile - This method 'profiles' an APInt for use with FoldingSet.
Used to insert APInt objects, or objects that contain APInt objects, into FoldingSets.
Definition at line 166 of file APInt.cpp.
References getNumWords(), pVal, and VAL.
Referenced by llvm::APSInt::Profile().
rotl() [1/2]
APInt APInt::rotl (const APInt & rotateAmt) const
Rotate left by rotateAmt.
Definition at line 1259 of file APInt.cpp.
References getLimitedValue(), and rotl().
rotl() [2/2]
APInt APInt::rotl (unsigned rotateAmt) const
Rotate left by rotateAmt.
Definition at line 1263 of file APInt.cpp.
References lshr(), and shl().
Referenced by llvm::SelectionDAG::FoldConstantArithmetic(), and rotl().
rotr() [1/2]
APInt APInt::rotr (const APInt & rotateAmt) const
Rotate right by rotateAmt.
Definition at line 1270 of file APInt.cpp.
References getLimitedValue(), and rotr().
rotr() [2/2]
APInt APInt::rotr (unsigned rotateAmt) const
Rotate right by rotateAmt.
Definition at line 1274 of file APInt.cpp.
References lshr(), and shl().
Referenced by llvm::SelectionDAG::FoldConstantArithmetic(), and rotr().
roundToDouble() [1/2]
double llvm::APInt::roundToDouble () const inline
Converts this unsigned APInt to a double value.
Definition at line 1445 of file APInt.h.
References roundToDouble().
Referenced by roundToDouble(), and signedRoundToDouble().
roundToDouble() [2/2]
double APInt::roundToDouble (bool isSigned) const
Converts this APInt to a double value.
RoundToDouble - This function converts this APInt to a double.
The layout for double is as following (IEEE Standard 754):
Sign Exponent Fraction Bias
1[63] 11[62-52] 52[51-00] 1023
Definition at line 863 of file APInt.cpp.
References getActiveBits(), I, pVal, and sext().
Referenced by llvm::ExecutionEngine::getConstantValue(), and llvm::APIntOps::RoundAPIntToDouble().
sadd_ov()
APInt APInt::sadd_ov (const APInt & RHS, bool & Overflow) const
Definition at line 2027 of file APInt.cpp.
References isNonNegative().
Referenced by ConstantFoldScalarCall(), and MaintainNoSignedWrap().
sdiv()
APInt APInt::sdiv (const APInt & RHS) const
Signed division function for APInt.
Signed divide this APInt by APInt RHS.
Definition at line 1898 of file APInt.cpp.
References isNegative(), and udiv().
Referenced by llvm::ConstantFoldBinaryInstruction(), findGCD(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::ExecutionEngine::getConstantValue(), getExactSDiv(), getNaturalGEPRecursively(), getNaturalGEPWithOffset(), llvm::APSInt::operator/(), llvm::APSInt::operator/=(), llvm::APIntOps::sdiv(), sdiv_ov(), SimplifyICmpInst(), smul_ov(), and llvm::Interpreter::visitBinaryOperator().
sdiv_ov()
APInt APInt::sdiv_ov (const APInt & RHS, bool & Overflow) const
Definition at line 2053 of file APInt.cpp.
References isAllOnesValue(), isMinSignedValue(), and sdiv().
sdivrem()
void APInt::sdivrem (const APInt & LHS, const APInt & RHS, APInt & Quotient, APInt & Remainder) static
Definition at line 2009 of file APInt.cpp.
References isNegative(), and udivrem().
Referenced by ceilingOfQuotient(), findGCD(), floorOfQuotient(), and IsMultiple().
setAllBits()
void llvm::APInt::setAllBits () inline
Set every bit to 1.
Definition at line 1209 of file APInt.h.
References getNumWords(), pVal, and VAL.
Referenced by computeKnownBits(), and computeKnownBitsFromAssume().
setBit()
void APInt::setBit (unsigned bitPosition)
Set a given bit to 1.
Set the given bit to 1 whose position is given as "bitPosition".
Definition at line 588 of file APInt.cpp.
References pVal, and VAL.
Referenced by computeKnownBits(), computeKnownBitsAddSub(), computeKnownBitsMul(), llvm::ComputeMultiple(), ComputeSignedMinMaxValuesFromKnownBits(), flipBit(), getOneBitSet(), llvm::ConstantRange::getSetSize(), getSignedMinValue(), SolveLinEquationWithOverflow(), llvm::ConstantRange::truncate(), and llvm::InstCombiner::visitExtractElementInst().
sext()
APInt APInt::sext (unsigned width) const
Sign extend to a new width.
This operation sign extends the APInt to a new width. If the high order bit is set, the fill on the left will be done with 1 bits, otherwise zero. It is an error to specify a width that is less than or equal to the current width.
Definition at line 947 of file APInt.cpp.
References APInt(), getMemory(), getNumWords(), getRawData(), pVal, and VAL.
Referenced by ComputeRange(), llvm::APSInt::extend(), llvm::ExecutionEngine::getConstantValue(), GetLinearExpression(), roundToDouble(), sextOrSelf(), and sextOrTrunc().
sextOrSelf()
APInt APInt::sextOrSelf (unsigned width) const
Sign extend or truncate to width.
Make this APInt have the bit width given by width. The value is sign extended, or left alone to make it that width.
Definition at line 1029 of file APInt.cpp.
References sext().
sextOrTrunc()
APInt APInt::sextOrTrunc (unsigned width) const
Sign extend or truncate to width.
Make this APInt have the bit width given by width. The value is sign extended, truncated, or left alone to make it that width.
Definition at line 1015 of file APInt.cpp.
References sext(), and trunc().
Referenced by llvm::GEPOperator::accumulateConstantOffset(), llvm::APSInt::extOrTrunc(), and llvm::SelectionDAG::getNode().
sge() [1/2]
bool llvm::APInt::sge (const APInt & RHS) const inline
Signed greather or equal comparison.
Regards both *this and RHS as signed quantities and compares them for validity of the greater-or-equal relationship.
Returns
true if *this >= RHS when both are considered signed.
Definition at line 1141 of file APInt.h.
References slt().
Referenced by llvm::ConstantFoldCompareInstruction(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombiner::FoldSPFofSPF(), llvm::APSInt::operator>=(), and TryMULWIDECombine().
sge() [2/2]
bool llvm::APInt::sge (uint64_t RHS) const inline
Signed greater or equal comparison.
Regards both *this as a signed quantity and compares it with RHS for the validity of the greater-or-equal relationship.
Returns
true if *this >= RHS when considered signed.
Definition at line 1149 of file APInt.h.
References APInt(), getBitWidth(), and sge().
Referenced by sge().
sgt() [1/2]
bool llvm::APInt::sgt (const APInt & RHS) const inline
Signed greather than comparison.
Regards both *this and RHS as signed quantities and compares them for the validity of the greater-than relationship.
Returns
true if *this > RHS when both are considered signed.
Definition at line 1109 of file APInt.h.
References eq(), and slt().
Referenced by ceilingOfQuotient(), llvm::ConstantFoldCompareInstruction(), floorOfQuotient(), llvm::InstCombiner::FoldAndOfICmps(), llvm::InstCombiner::FoldICmpCstShrCst(), llvm::InstCombiner::FoldOrOfICmps(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombiner::FoldSPFofSPF(), HasAddOverflow(), HasSubOverflow(), llvm::APSInt::operator>(), SimplifyICmpInst(), and SwitchToLookupTable().
sgt() [2/2]
bool llvm::APInt::sgt (uint64_t RHS) const inline
Signed greater than comparison.
Regards both *this as a signed quantity and compares it with RHS for the validity of the greater-than relationship.
Returns
true if *this > RHS when considered signed.
Definition at line 1117 of file APInt.h.
References APInt(), getBitWidth(), and sgt().
Referenced by sgt().
shl() [1/2]
APInt APInt::shl (const APInt & shiftAmt) const
Left-shift function.
Left-shift this APInt by shiftAmt.
Definition at line 1198 of file APInt.cpp.
References getLimitedValue(), and shl().
shl() [2/2]
APInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APInt::shl (unsigned shiftAmt) const inline
Left-shift function.
Left-shift this APInt by shiftAmt.
Definition at line 864 of file APInt.h.
References APInt(), LLVM_ATTRIBUTE_UNUSED_RESULT, and VAL.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::InstCombiner::FoldICmpCstShlCst(), getBitsSet(), getHighBitsSet(), getUsefulBitsFromBFM(), getUsefulBitsFromBitfieldMoveOpd(), getUsefulBitsFromOrWithShiftedReg(), insertInteger(), LowerShift(), operator<<(), operator<<(), operator<<=(), PerformSHLCombine(), rotl(), rotr(), llvm::APIntOps::RoundDoubleToAPInt(), shl(), llvm::APIntOps::shl(), llvm::ConstantRange::shl(), llvm::TargetLowering::SimplifyDemandedBits(), SimplifyICmpInst(), sqrt(), and llvm::Interpreter::visitShl().
signedRoundToDouble()
double llvm::APInt::signedRoundToDouble () const inline
Converts this signed APInt to a double value.
Definition at line 1448 of file APInt.h.
References roundToDouble().
Referenced by llvm::ExecutionEngine::getConstantValue(), llvm::APIntOps::RoundSignedAPIntToDouble(), and llvm::APIntOps::RoundSignedAPIntToFloat().
sle() [1/2]
bool llvm::APInt::sle (const APInt & RHS) const inline
Signed less or equal comparison.
Regards both *this and RHS as signed quantities and compares them for validity of the less-or-equal relationship.
Returns
true if *this <= RHS when both are considered signed.
Definition at line 1077 of file APInt.h.
References eq(), and slt().
Referenced by llvm::ConstantFoldCompareInstruction(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombiner::FoldSPFofSPF(), llvm::APSInt::operator<=(), and llvm::InstCombiner::visitICmpInst().
sle() [2/2]
bool llvm::APInt::sle (uint64_t RHS) const inline
Signed less or equal comparison.
Regards both *this as a signed quantity and compares it with RHS for the validity of the less-or-equal relationship.
Returns
true if *this <= RHS when considered signed.
Definition at line 1085 of file APInt.h.
References APInt(), getBitWidth(), and sle().
Referenced by sle().
slt() [1/2]
bool APInt::slt (const APInt & RHS) const
Signed less than comparison.
Regards both *this and RHS as signed quantities and compares them for validity of the less-than relationship.
Returns
true if *this < RHS when both are considered signed.
Definition at line 552 of file APInt.cpp.
References flipAllBits(), isNegative(), ugt(), ult(), and VAL.
Referenced by ceilingOfQuotient(), llvm::ConstantFoldCompareInstruction(), findGCD(), floorOfQuotient(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombiner::FoldSPFofSPF(), llvm::MDNode::getMostGenericRange(), HasAddOverflow(), HasSubOverflow(), llvm::APSInt::operator<(), sge(), sgt(), sle(), SwitchToLookupTable(), TryMULWIDECombine(), and llvm::InstCombiner::visitICmpInst().
slt() [2/2]
bool llvm::APInt::slt (uint64_t RHS) const inline
Signed less than comparison.
Regards both *this as a signed quantity and compares it with RHS for the validity of the less-than relationship.
Returns
true if *this < RHS when considered signed.
Definition at line 1053 of file APInt.h.
References APInt(), getBitWidth(), and slt().
Referenced by slt().
smul_ov()
APInt APInt::smul_ov (const APInt & RHS, bool & Overflow) const
Definition at line 2059 of file APInt.cpp.
References sdiv().
Referenced by ConstantFoldScalarCall(), and MultiplyOverflows().
sqrt()
APInt APInt::sqrt () const
Compute the square root.
Definition at line 1288 of file APInt.cpp.
References APInt(), getActiveBits(), pVal, shl(), sqrt(), udiv(), ule(), ult(), and VAL.
Referenced by SolveQuadraticEquation(), and sqrt().
srem()
APInt APInt::srem (const APInt & RHS) const
Function for signed remainder operation.
Signed remainder operation on APInt.
Definition at line 1946 of file APInt.cpp.
References isNegative(), and urem().
Referenced by llvm::ConstantFoldBinaryInstruction(), findGCD(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::ExecutionEngine::getConstantValue(), getExactSDiv(), isRemainderZero(), llvm::APSInt::operator%(), llvm::APSInt::operator%=(), llvm::APIntOps::srem(), and llvm::Interpreter::visitBinaryOperator().
sshl_ov()
APInt APInt::sshl_ov (const APInt & Amt, bool & Overflow) const
Definition at line 2079 of file APInt.cpp.
References APInt(), countLeadingOnes(), countLeadingZeros(), getBitWidth(), isNonNegative(), and uge().
ssub_ov()
APInt APInt::ssub_ov (const APInt & RHS, bool & Overflow) const
Definition at line 2040 of file APInt.cpp.
References isNonNegative().
Referenced by ConstantFoldScalarCall(), and MaintainNoSignedWrap().
tcAdd()
integerPart APInt::tcAdd (integerPart * , const integerPart * , integerPart carry, unsigned) static
DST += RHS + CARRY where CARRY is zero or one. Returns the carry flag.
Definition at line 2496 of file APInt.cpp.
tcAnd()
void APInt::tcAnd (integerPart * dst, const integerPart * rhs, unsigned int parts) static
The obvious AND, OR and XOR and complement operations.
Definition at line 2827 of file APInt.cpp.
tcAssign()
void APInt::tcAssign (integerPart * dst, const integerPart * src, unsigned int parts) static
Assign one bignum to another.
Definition at line 2375 of file APInt.cpp.
Referenced by llvm::APFloat::convert(), llvm::APFloat::convertFromSignExtendedInteger(), powerOf5(), tcDivide(), and tcExtract().
tcClearBit()
void APInt::tcClearBit (integerPart * parts, unsigned int bit) static
Clear the given bit of a bignum. Zero-based.
Definition at line 2413 of file APInt.cpp.
References llvm::integerPartWidth.
tcCompare()
int APInt::tcCompare (const integerPart * lhs, const integerPart * rhs, unsigned int parts) static
Comparison (unsigned) of two bignums.
Definition at line 2867 of file APInt.cpp.
Referenced by tcDivide().
tcComplement()
void APInt::tcComplement (integerPart * dst, unsigned int parts) static
Definition at line 2857 of file APInt.cpp.
Referenced by tcNegate().
tcDecrement()
integerPart APInt::tcDecrement (integerPart * dst, unsigned int parts) static
Decrement a bignum in-place. Return the borrow flag.
Definition at line 2899 of file APInt.cpp.
Referenced by llvm::APFloat::next().
tcDivide()
int APInt::tcDivide (integerPart * lhs, const integerPart * rhs, integerPart * remainder, integerPart * scratch, unsigned int parts) static
If RHS is zero LHS and REMAINDER are left unchanged, return one. Otherwise set LHS to LHS / RHS with the fractional part discarded, set REMAINDER to the remainder, return zero. i.e.
OLD_LHS = RHS * LHS + REMAINDER
SCRATCH is a bignum of the same size as the operands and result for use by the routine; its contents need not be initialized and are destroyed. LHS, REMAINDER and SCRATCH must be distinct.
Definition at line 2714 of file APInt.cpp.
References llvm::integerPartWidth, tcAssign(), tcCompare(), tcMSB(), tcSet(), tcShiftLeft(), tcShiftRight(), and tcSubtract().
tcExtract()
void APInt::tcExtract (integerPart * dst, unsigned int dstCount, const integerPart * src, unsigned int srcBits, unsigned int srcLSB) static
Copy the bit vector of width srcBITS from SRC, starting at bit srcLSB, to DST, of dstCOUNT parts, such that the bit srcLSB becomes the least significant bit of DST. All high bits above srcBITS in DST are zero-filled.
Definition at line 2462 of file APInt.cpp.
References llvm::integerPartWidth, tcAssign(), and tcShiftRight().
tcExtractBit()
int APInt::tcExtractBit (const integerPart * parts, unsigned int bit) static
Extract the given bit of a bignum; returns 0 or 1. Zero-based.
Definition at line 2398 of file APInt.cpp.
References llvm::integerPartWidth.
Referenced by llvm::APFloat::convertFromSignExtendedInteger(), llvm::APFloat::convertFromZeroExtendedInteger(), llvm::APFloat::isDenormal(), llvm::APFloat::isSignaling(), and lostFractionThroughTruncation().
tcFullMultiply()
unsigned int APInt::tcFullMultiply (integerPart * , const integerPart * , const integerPart * , unsigned , unsigned) static
DST = LHS * RHS, where DST has width the sum of the widths of the operands. No overflow occurs. DST must be disjoint from both operands. Returns the number of parts required to hold the result.
Definition at line 2680 of file APInt.cpp.
References tcFullMultiply(), tcMultiplyPart(), and tcSet().
Referenced by powerOf5(), and tcFullMultiply().
tcIncrement()
integerPart APInt::tcIncrement (integerPart * dst, unsigned int parts) static
Increment a bignum in-place. Return the carry flag.
Definition at line 2886 of file APInt.cpp.
Referenced by tcNegate().
tcIsZero()
bool APInt::tcIsZero (const integerPart * src, unsigned int parts) static
Returns true if a bignum is zero, false otherwise.
Definition at line 2385 of file APInt.cpp.
tcLSB()
unsigned int APInt::tcLSB (const integerPart * parts, unsigned int n) static
Returns the bit number of the least or most significant set bit of a number. If the input number has no bits set -1U is returned.
Definition at line 2422 of file APInt.cpp.
References llvm::integerPartWidth.
Referenced by lostFractionThroughTruncation().
tcMSB()
unsigned int APInt::tcMSB (const integerPart * parts, unsigned int n) static
Definition at line 2440 of file APInt.cpp.
References llvm::integerPartWidth.
Referenced by tcDivide().
tcMultiply()
int APInt::tcMultiply (integerPart * , const integerPart * , const integerPart * , unsigned) static
DST = LHS * RHS, where DST has the same width as the operands and is filled with the least significant parts of the result. Returns one if overflow occurred, otherwise zero. DST must be disjoint from both operands.
Definition at line 2657 of file APInt.cpp.
References tcMultiplyPart(), and tcSet().
tcMultiplyPart()
int APInt::tcMultiplyPart (integerPart * dst, const integerPart * src, integerPart multiplier, integerPart carry, unsigned int srcParts, unsigned int dstParts, bool add) static
DST += SRC * MULTIPLIER + PART if add is true DST = SRC * MULTIPLIER + PART if add is false
Requires 0 <= DSTPARTS <= SRCPARTS + 1. If DST overlaps SRC they must start at the same point, i.e. DST == SRC.
If DSTPARTS == SRC_PARTS + 1 no overflow occurs and zero is returned. Otherwise DST is filled with the least significant DSTPARTS parts of the result, and if all of the omitted higher parts were zero return zero, otherwise overflow occurred and return one.
Definition at line 2564 of file APInt.cpp.
References add(), and llvm::integerPartWidth.
Referenced by tcFullMultiply(), and tcMultiply().
tcNegate()
void APInt::tcNegate (integerPart * dst, unsigned int parts) static
Negate a bignum in-place.
Definition at line 2546 of file APInt.cpp.
References tcComplement(), and tcIncrement().
Referenced by llvm::APFloat::convertFromSignExtendedInteger().
tcOr()
void APInt::tcOr (integerPart * dst, const integerPart * rhs, unsigned int parts) static
Definition at line 2837 of file APInt.cpp.
tcSet()
void APInt::tcSet (integerPart * dst, integerPart part, unsigned int parts) static
Sets the least significant part of a bignum to the input value, and zeroes out higher parts.
Definition at line 2362 of file APInt.cpp.
Referenced by llvm::APFloat::convert(), llvm::APFloat::next(), tcDivide(), tcFullMultiply(), and tcMultiply().
tcSetBit()
void APInt::tcSetBit (integerPart * parts, unsigned int bit) static
Set the given bit of a bignum. Zero-based.
Definition at line 2406 of file APInt.cpp.
References llvm::integerPartWidth.
Referenced by llvm::APFloat::convert(), and llvm::APFloat::next().
tcSetLeastSignificantBits()
void APInt::tcSetLeastSignificantBits (integerPart * dst, unsigned int parts, unsigned int bits) static
Set the least significant BITS and clear the rest.
Definition at line 2914 of file APInt.cpp.
References llvm::integerPartWidth.
Referenced by llvm::APFloat::convertToInteger().
tcShiftLeft()
void APInt::tcShiftLeft (integerPart * dst, unsigned int parts, unsigned int count) static
Shift a bignum left COUNT bits. Shifted in bits are zero. There are no restrictions on COUNT.
Definition at line 2761 of file APInt.cpp.
References llvm::integerPartWidth.
Referenced by llvm::APFloat::convert(), llvm::APFloat::convertToInteger(), and tcDivide().
tcShiftRight()
void APInt::tcShiftRight (integerPart * dst, unsigned int parts, unsigned int count) static
Shift a bignum right COUNT bits. Shifted in bits are zero. There are no restrictions on COUNT.
Definition at line 2795 of file APInt.cpp.
References llvm::integerPartWidth.
Referenced by shiftRight(), tcDivide(), and tcExtract().
tcSubtract()
integerPart APInt::tcSubtract (integerPart * , const integerPart * , integerPart carry, unsigned) static
DST -= RHS + CARRY where CARRY is zero or one. Returns the carry flag.
Definition at line 2521 of file APInt.cpp.
Referenced by tcDivide().
tcXor()
void APInt::tcXor (integerPart * dst, const integerPart * rhs, unsigned int parts) static
Definition at line 2847 of file APInt.cpp.
toString() [1/2]
void APInt::toString (SmallVectorImpl< char > & Str, unsigned Radix, bool Signed, bool formatAsCLiteral = false) const
Converts an APInt to a string and append it to Str. Str is commonly a SmallString.
Definition at line 2165 of file APInt.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), flipAllBits(), getBitWidth(), getNumWords(), getRawData(), getSExtValue(), getZExtValue(), I, isNegative(), llvm_unreachable, lshr(), N, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), Signed, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by print(), toString(), llvm::APSInt::toString(), llvm::APSInt::toString(), toStringSigned(), and toStringUnsigned().
toString() [2/2]
std::string APInt::toString (unsigned Radix = 10, bool Signed = true) const
Return the APInt as a std::string.
Note that this is an inefficient method. It is better to pass in a SmallVector/SmallString to the methods above to avoid thrashing the heap for the string.
toString - This returns the APInt as a std::string. Note that this is an inefficient method. It is better to pass in a SmallVector/SmallString to the methods above.
Definition at line 2287 of file APInt.cpp.
References Signed, llvm::SmallString< InternalLen >::str(), and toString().
toStringSigned()
void llvm::APInt::toStringSigned (SmallVectorImpl< char > & Str, unsigned Radix = 10) const inline
Considers the APInt to be signed and converts it into a string in the radix given. The radix can be 2, 8, 10, 16, or 36.
Definition at line 1427 of file APInt.h.
References toString().
Referenced by dump().
toStringUnsigned()
void llvm::APInt::toStringUnsigned (SmallVectorImpl< char > & Str, unsigned Radix = 10) const inline
Considers the APInt to be unsigned and converts it into a string in the radix given. The radix can be 2, 8, 10 16, or 36.
Definition at line 1421 of file APInt.h.
References toString().
Referenced by dump().
trunc()
APInt APInt::trunc (unsigned width) const
Truncate to new width.
Truncate the APInt to a specified width. It is an error to specify a width that is greater than or equal to the current width.
Definition at line 924 of file APInt.cpp.
References APInt(), getMemory(), getNumWords(), getRawData(), and pVal.
Referenced by areUsedBitsDense(), BinomialCoefficient(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), ExtractConstantBytes(), llvm::SelectionDAG::getConstant(), llvm::ExecutionEngine::getConstantValue(), GetLinearExpression(), llvm::SelectionDAG::getNode(), llvm::isBytewiseValue(), llvm::BuildVectorSDNode::isConstantSplat(), lowerMSABinaryBitImmIntr(), performShiftToAllZeros(), ProcessUMulZExtIdiom(), sextOrTrunc(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), SolveLinEquationWithOverflow(), llvm::APSInt::trunc(), llvm::ConstantRange::truncate(), and zextOrTrunc().
uadd_ov()
APInt APInt::uadd_ov (const APInt & RHS, bool & Overflow) const
Definition at line 2034 of file APInt.cpp.
References ult().
Referenced by ConstantFoldScalarCall().
udiv()
APInt APInt::udiv (const APInt & RHS) const
Unsigned division operation.
Perform an unsigned divide operation on this APInt by RHS. Both this and RHS are treated as unsigned quantities for purposes of this division.
Returns
a new APInt value containing the division result
Definition at line 1861 of file APInt.cpp.
References APInt(), getActiveBits(), pVal, ult(), and VAL.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::ExecutionEngine::getConstantValue(), magicu(), llvm::APSInt::operator/(), llvm::APSInt::operator/=(), sdiv(), SimplifyICmpInst(), sqrt(), SymbolicallyEvaluateGEP(), llvm::APIntOps::udiv(), llvm::ConstantRange::udiv(), umul_ov(), and llvm::Interpreter::visitBinaryOperator().
udivrem()
void APInt::udivrem (const APInt & LHS, const APInt & RHS, APInt & Quotient, APInt & Remainder) static
Dual division/remainder interface.
Sometimes it is convenient to divide two APInt values and obtain both the quotient and remainder. This function does both operations in the same computation making it a little more efficient. The pair of input arguments may overlap with the pair of output arguments. It is safe to call udivrem(X, Y, X, Y), for example.
Definition at line 1957 of file APInt.cpp.
References APInt(), getActiveBits(), getBitWidth(), pVal, ult(), and VAL.
Referenced by IsMultiple(), multiplicativeInverse(), sdivrem(), llvm::APFloat::toString(), and llvm::ConstantRange::truncate().
uge() [1/2]
bool llvm::APInt::uge (const APInt & RHS) const inline
Unsigned greater or equal comparison.
Regards both *this and RHS as unsigned quantities and compares them for validity of the greater-or-equal relationship.
Returns
true if *this >= RHS when both are considered unsigned.
Definition at line 1125 of file APInt.h.
References ult().
Referenced by llvm::ConstantFoldCompareInstruction(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombiner::FoldSPFofSPF(), getNaturalGEPRecursively(), IncorporateWeight(), llvm::Value::isDereferenceablePointer(), magicu(), llvm::APSInt::operator>=(), performShiftToAllZeros(), sshl_ov(), SymbolicallyEvaluateGEP(), llvm::ConstantRange::unionWith(), ushl_ov(), and llvm::InstCombiner::visitICmpInst().
uge() [2/2]
bool llvm::APInt::uge (uint64_t RHS) const inline
Unsigned greater or equal comparison.
Regards both *this as an unsigned quantity and compares it with RHS for the validity of the greater-or-equal relationship.
Returns
true if *this >= RHS when considered unsigned.
Definition at line 1133 of file APInt.h.
References APInt(), getBitWidth(), and uge().
Referenced by uge().
ugt() [1/2]
bool llvm::APInt::ugt (const APInt & RHS) const inline
Unsigned greather than comparison.
Regards both *this and RHS as unsigned quantities and compares them for the validity of the greater-than relationship.
Returns
true if *this > RHS when both are considered unsigned.
Definition at line 1093 of file APInt.h.
References eq(), and ult().
Referenced by llvm::ConstantFoldCompareInstruction(), llvm::InstCombiner::FoldAndOfICmps(), llvm::InstCombiner::FoldOrOfICmps(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombiner::FoldSPFofSPF(), getNaturalGEPRecursively(), llvm::ScalarEvolution::getSignExtendExpr(), HasSubOverflow(), llvm::APSInt::operator>(), llvm::ConstantRange::shl(), slt(), llvm::ConstantRange::unionWith(), ushl_ov(), usub_ov(), and llvm::ObjectSizeOffsetVisitor::visitCallSite().
ugt() [2/2]
bool llvm::APInt::ugt (uint64_t RHS) const inline
Unsigned greater than comparison.
Regards both *this as an unsigned quantity and compares it with RHS for the validity of the greater-than relationship.
Returns
true if *this > RHS when considered unsigned.
Definition at line 1101 of file APInt.h.
References APInt(), getBitWidth(), and ugt().
Referenced by ugt().
ule() [1/2]
bool llvm::APInt::ule (const APInt & RHS) const inline
Unsigned less or equal comparison.
Regards both *this and RHS as unsigned quantities and compares them for validity of the less-or-equal relationship.
Returns
true if *this <= RHS when both are considered unsigned.
Definition at line 1061 of file APInt.h.
References eq(), and ult().
Referenced by llvm::ConstantFoldCompareInstruction(), llvm::ConstantRange::contains(), llvm::InstCombiner::FoldOrOfICmps(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombiner::FoldSPFofSPF(), llvm::ConstantRange::intersectWith(), llvm::APSInt::operator<=(), sqrt(), llvm::ConstantRange::truncate(), llvm::ConstantRange::unionWith(), and llvm::InstCombiner::visitICmpInst().
ule() [2/2]
bool llvm::APInt::ule (uint64_t RHS) const inline
Unsigned less or equal comparison.
Regards both *this as an unsigned quantity and compares it with RHS for the validity of the less-or-equal relationship.
Returns
true if *this <= RHS when considered unsigned.
Definition at line 1069 of file APInt.h.
References APInt(), getBitWidth(), and ule().
Referenced by ule().
ult() [1/2]
bool APInt::ult (const APInt & RHS) const
Unsigned less than comparison.
Regards both *this and RHS as unsigned quantities and compares them for the validity of the less-than relationship.
Returns
true if *this < RHS when both are considered unsigned.
Definition at line 520 of file APInt.cpp.
References getActiveBits(), pVal, and VAL.
Referenced by CanEvaluateShifted(), computePointerICmp(), llvm::ConstantFoldCompareInstruction(), ConstantIntSortPredicate(), llvm::InstCombiner::FoldOrOfICmps(), llvm::SelectionDAG::FoldSetCC(), llvm::InstCombiner::FoldSPFofSPF(), llvm::getObjectSize(), HasAddOverflow(), IncorporateWeight(), llvm::ConstantRange::intersectWith(), magicu(), multiplicativeInverse(), llvm::APSInt::operator<(), SimplifyICmpInst(), slt(), sqrt(), llvm::ConstantRange::truncate(), uadd_ov(), udiv(), udivrem(), uge(), ugt(), ule(), llvm::ConstantRange::unionWith(), urem(), and llvm::InstCombiner::visitICmpInst().
ult() [2/2]
bool llvm::APInt::ult (uint64_t RHS) const inline
Unsigned less than comparison.
Regards both *this as an unsigned quantity and compares it with RHS for the validity of the less-than relationship.
Returns
true if *this < RHS when considered unsigned.
Definition at line 1037 of file APInt.h.
References APInt(), getBitWidth(), and ult().
Referenced by ult().
umul_ov()
APInt APInt::umul_ov (const APInt & RHS, bool & Overflow) const
Definition at line 2069 of file APInt.cpp.
References udiv().
Referenced by llvm::computeOverflowForUnsignedMul(), ConstantFoldScalarCall(), MultiplyOverflows(), and SimplifyDiv().
urem()
APInt APInt::urem (const APInt & RHS) const
Unsigned remainder operation.
Perform an unsigned remainder operation on this APInt with RHS being the divisor. Both this and RHS are treated as unsigned quantities for purposes of this operation. Note that this is a true remainder operation and not a modulo operation because the sign follows the sign of the dividend which is *this.
Returns
a new APInt value containing the remainder result
Definition at line 1909 of file APInt.cpp.
References APInt(), getActiveBits(), pVal, ult(), and VAL.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::ExecutionEngine::getConstantValue(), llvm::ScalarEvolution::getUDivExpr(), magicu(), llvm::APSInt::operator%(), llvm::APSInt::operator%=(), srem(), llvm::APIntOps::urem(), and llvm::Interpreter::visitBinaryOperator().
ushl_ov()
APInt APInt::ushl_ov (const APInt & Amt, bool & Overflow) const
Definition at line 2092 of file APInt.cpp.
References APInt(), countLeadingZeros(), getBitWidth(), uge(), and ugt().
Referenced by llvm::InstCombiner::visitUDiv().
usub_ov()
APInt APInt::usub_ov (const APInt & RHS, bool & Overflow) const
Definition at line 2047 of file APInt.cpp.
References ugt().
Referenced by ConstantFoldScalarCall().
Xor()
APInt LLVM_ATTRIBUTE_UNUSED_RESULT llvm::APInt::Xor (const APInt & RHS) const inline
Bitwise XOR function.
Performs a bitwise XOR operation on *this and RHS. This is implemented through the usage of operator^.
Returns
An APInt value representing the bitwise XOR of *this and RHS.
Definition at line 820 of file APInt.h.
References LLVM_ATTRIBUTE_UNUSED_RESULT, and operator^().
zext()
APInt APInt::zext (unsigned width) const
Zero extend to a new width.
This operation zero extends the APInt to a new width. The high order bits are filled with 0 bits. It is an error to specify a width that is less than or equal to the current width.
Definition at line 988 of file APInt.cpp.
References APInt(), getMemory(), getNumWords(), getRawData(), pVal, and VAL.
Referenced by BinomialCoefficient(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::APSInt::extend(), llvm::InstCombiner::FoldAndOfICmps(), gcd(), llvm::StringRef::getAsInteger(), llvm::SelectionDAG::getConstant(), llvm::ExecutionEngine::getConstantValue(), GetLinearExpression(), llvm::ConstantRange::getSetSize(), insertInteger(), isSameValue(), llvm::ConstantRange::multiply(), ProcessUMulZExtIdiom(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::ConstantRange::truncate(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), WidenMaskArithmetic(), llvm::ConstantRange::zeroExtend(), zextOrSelf(), and zextOrTrunc().
zextOrSelf()
APInt APInt::zextOrSelf (unsigned width) const
Zero extend or truncate to width.
Make this APInt have the bit width given by width. The value is zero extended, or left alone to make it that width.
Definition at line 1023 of file APInt.cpp.
References zext().
Referenced by llvm::ObjectSizeOffsetVisitor::visitCallSite().
zextOrTrunc()
APInt APInt::zextOrTrunc (unsigned width) const
Zero extend or truncate to width.
Make this APInt have the bit width given by width. The value is zero extended, truncated, or left alone to make it that width.
Definition at line 1007 of file APInt.cpp.
References trunc(), and zext().
Referenced by computeKnownBits(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::Interpreter::exitCalled(), llvm::APSInt::extOrTrunc(), llvm::ExecutionEngine::getConstantValue(), llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), llvm::SelectionDAG::getNode(), isBitfieldDstMask(), llvm::BuildVectorSDNode::isConstantSplat(), resolveBuildVector(), ShrinkDemandedConstant(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), SymbolicallyEvaluateBinop(), and SymbolicallyEvaluateGEP().
Friends And Related Symbol Documentation
DenseMapAPIntKeyInfo
friend struct DenseMapAPIntKeyInfo friend
Definition at line 94 of file APInt.h.
References DenseMapAPIntKeyInfo, and pVal.
Referenced by DenseMapAPIntKeyInfo.
hash_value
hash_code hash_value (const APInt & Arg) friend
Overload to compute a hash_code for an APInt value.
Member Data Documentation
pVal
uint64_t* llvm::APInt::pVal
Used to store the >64 bits integer value.
Definition at line 82 of file APInt.h.
Referenced by ashr(), bitsToDouble(), bitsToFloat(), byteSwap(), clearAllBits(), clearBit(), countLeadingOnes(), countTrailingZeros(), DenseMapAPIntKeyInfo, flipAllBits(), getRawData(), getSExtValue(), getZExtValue(), llvm::hash_value(), lshr(), operator!(), operator&=(), operator*=(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator=(), operator=(), operator[](), operator^=(), operator|=(), operator|=(), Profile(), roundToDouble(), setAllBits(), setBit(), sext(), sqrt(), trunc(), udiv(), udivrem(), ult(), urem(), zext(), and ~APInt().
VAL
uint64_t llvm::APInt::VAL
Used to store the <= 64 bits integer value.
Definition at line 81 of file APInt.h.
Referenced by APInt(), APInt(), APInt(), APInt(), APInt(), APInt(), ashr(), bitsToDouble(), bitsToFloat(), byteSwap(), clearAllBits(), clearBit(), countLeadingOnes(), countLeadingZeros(), countPopulation(), countTrailingOnes(), countTrailingZeros(), flipAllBits(), getRawData(), getSExtValue(), getZExtValue(), llvm::hash_value(), isAllOnesValue(), isMaxSignedValue(), isMinSignedValue(), isPowerOf2(), lshr(), nearestLogBase2(), operator!(), operator&(), operator&=(), operator*(), operator*=(), operator+(), operator++(), operator+=(), operator-(), operator--(), operator-=(), operator=(), operator=(), operator=(), operator==(), operator==(), operator[](), operator^(), operator^=(), operator|(), operator|=(), operator|=(), Profile(), setAllBits(), setBit(), sext(), shl(), slt(), sqrt(), udiv(), udivrem(), ult(), urem(), and zext().
The documentation for this class was generated from the following files:
APInt.h
APInt.cpp