LLVM: llvm::SwitchInst::CaseIt Class Reference
LLVM API Documentation
llvm::SwitchInst::CaseIt Class Reference
#include <Instructions.h>
Public Member Functions
CaseIt (const ParentTy &Src)
CaseIt (SwitchInst *SI, unsigned CaseNum)
void setValue (ConstantInt *V)
Sets the new value for current case.
void setSuccessor (BasicBlock *S)
Sets the new successor for current case.
Public Member Functions inherited from llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >
CaseIteratorT (SwitchInst *SI, unsigned CaseNum)
ConstantInt * getCaseValue ()
Resolves case value for current case.
BasicBlock * getCaseSuccessor ()
Resolves successor for current case.
unsigned getCaseIndex () const
Returns number of current case.
unsigned getSuccessorIndex () const
Returns TerminatorInst's successor index for current case successor.
Self operator++ ()
Self operator++ (int)
Self operator-- ()
Self operator-- (int)
bool operator== (const Self &RHS) const
bool operator!= (const Self &RHS) const
Self & operator* ()
Additional Inherited Members
Public Types inherited from llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >
typedef CaseIteratorT< SwitchInst, ConstantInt, BasicBlock > Self
Static Public Member Functions inherited from llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >
static Self fromSuccessorIndex (SwitchInst *SI, unsigned SuccessorIndex)
Protected Attributes inherited from llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >
SwitchInst * SI
unsigned Index
Detailed Description
Definition at line 2692 of file Instructions.h.
Constructor & Destructor Documentation
CaseIt() [1/2]
llvm::SwitchInst::CaseIt::CaseIt (const ParentTy & Src) inline
Definition at line 2698 of file Instructions.h.
CaseIt() [2/2]
llvm::SwitchInst::CaseIt::CaseIt (SwitchInst * SI, unsigned CaseNum) inline
Definition at line 2699 of file Instructions.h.
References llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::SI.
Member Function Documentation
setSuccessor()
void llvm::SwitchInst::CaseIt::setSuccessor (BasicBlock * S) inline
Sets the new successor for current case.
Definition at line 2708 of file Instructions.h.
References llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::getSuccessorIndex(), and llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::SI.
Referenced by llvm::SwitchInst::addCase().
setValue()
void llvm::SwitchInst::CaseIt::setValue (ConstantInt * V) inline
Sets the new value for current case.
Definition at line 2702 of file Instructions.h.
References llvm::SwitchInst::getNumCases(), llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::Index, and llvm::SwitchInst::CaseIteratorT< SwitchInst, ConstantInt, BasicBlock >::SI.
Referenced by llvm::SwitchInst::addCase().
The documentation for this class was generated from the following file:
Instructions.h