LLVM: llvm::IRBuilderDefaultInserter< preserveNames > Class Template Reference
LLVM API Documentation
llvm::IRBuilderDefaultInserter< preserveNames > Class Template Reference
This provides the default implementation of the IRBuilder 'InsertHelper' method that is called whenever an instruction is created by IRBuilder and needs to be inserted.
#include <IRBuilder.h>
Protected Member Functions
void InsertHelper (Instruction *I, const Twine &Name, BasicBlock *BB, BasicBlock::iterator InsertPt) const
Detailed Description
template<bool preserveNames = true>
class llvm::IRBuilderDefaultInserter< preserveNames >
This provides the default implementation of the IRBuilder 'InsertHelper' method that is called whenever an instruction is created by IRBuilder and needs to be inserted.
By default, this inserts the instruction at the insertion point.
Definition at line 39 of file IRBuilder.h.
Member Function Documentation
InsertHelper()
template<bool preserveNames = true> void llvm::IRBuilderDefaultInserter< preserveNames >::InsertHelper (Instruction * I, const Twine & Name, BasicBlock * BB, BasicBlock::iterator InsertPt) const inline protected
Definition at line 41 of file IRBuilder.h.
References llvm::BasicBlock::getInstList(), I, llvm::iplist< NodeTy, Traits >::insert(), and Name.
Referenced by llvm::IRBuilder< true, TargetFolder >::Insert(), and llvm::InstCombineIRInserter::InsertHelper().
The documentation for this class was generated from the following file:
IRBuilder.h