LLVM: llvm::InterferenceCache::Cursor Class Reference
LLVM API Documentation
llvm::InterferenceCache::Cursor Class Reference
Cursor - The primary query interface for the block interference cache.
#include <InterferenceCache.h>
Public Member Functions
Cursor ()
Cursor - Create a dangling cursor.
~Cursor ()
Cursor (const Cursor &O)
Cursor & operator= (const Cursor &O)
void setPhysReg (InterferenceCache &Cache, unsigned PhysReg)
setPhysReg - Point this cursor to PhysReg's interference.
void moveToBlock (unsigned MBBNum)
moveTo - Move cursor to basic block MBBNum.
bool hasInterference ()
hasInterference - Return true if the current block has any interference.
SlotIndex first ()
SlotIndex last ()
Detailed Description
Cursor - The primary query interface for the block interference cache.
Definition at line 171 of file InterferenceCache.h.
Constructor & Destructor Documentation
Cursor() [1/2]
llvm::InterferenceCache::Cursor::Cursor () inline
Cursor - Create a dangling cursor.
Definition at line 189 of file InterferenceCache.h.
Referenced by Cursor(), and operator=().
~Cursor()
llvm::InterferenceCache::Cursor::~Cursor () inline
Definition at line 190 of file InterferenceCache.h.
Cursor() [2/2]
llvm::InterferenceCache::Cursor::Cursor (const Cursor & O) inline
Definition at line 192 of file InterferenceCache.h.
References Cursor().
Member Function Documentation
first()
SlotIndex llvm::InterferenceCache::Cursor::first () inline
first - Return the starting index of the first interfering range in the current block.
Definition at line 222 of file InterferenceCache.h.
hasInterference()
bool llvm::InterferenceCache::Cursor::hasInterference () inline
hasInterference - Return true if the current block has any interference.
Definition at line 216 of file InterferenceCache.h.
last()
SlotIndex llvm::InterferenceCache::Cursor::last () inline
last - Return the ending index of the last interfering range in the current block.
Definition at line 228 of file InterferenceCache.h.
moveToBlock()
void llvm::InterferenceCache::Cursor::moveToBlock (unsigned MBBNum) inline
moveTo - Move cursor to basic block MBBNum.
Definition at line 211 of file InterferenceCache.h.
operator=()
Cursor & llvm::InterferenceCache::Cursor::operator= (const Cursor & O) inline
Definition at line 196 of file InterferenceCache.h.
References Cursor().
setPhysReg()
void llvm::InterferenceCache::Cursor::setPhysReg (InterferenceCache & Cache, unsigned PhysReg) inline
setPhysReg - Point this cursor to PhysReg's interference.
Definition at line 202 of file InterferenceCache.h.
References llvm::InterferenceCache::InterferenceCache().
The documentation for this class was generated from the following files:
InterferenceCache.h
InterferenceCache.cpp