LLVM: llvm::TargetLoweringObjectFileMachO Class Reference
LLVM API Documentation
llvm::TargetLoweringObjectFileMachO Class Reference
#include <TargetLoweringObjectFileImpl.h>
Public Member Functions
virtual ~TargetLoweringObjectFileMachO ()
StringRef getDepLibFromLinkerOpt (StringRef LinkerOption) const override
void emitModuleFlags (MCStreamer &Streamer, ArrayRef< Module::ModuleFlagEntry > ModuleFlags, Mangler &Mang, const TargetMachine &TM) const override
Emit the module flags that specify the garbage collection information.
const MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
const MCSection * getExplicitSectionGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const override
const MCSection * getSectionForConstant (SectionKind Kind, const Constant *C) const override
const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const override
The mach-o version of this method defaults to returning a stub reference.
MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, Mangler &Mang, const TargetMachine &TM, MachineModuleInfo *MMI) const override
Public Member Functions inherited from llvm::TargetLoweringObjectFile
MCContext & getContext () const
TargetLoweringObjectFile ()
virtual ~TargetLoweringObjectFile ()
virtual void Initialize (MCContext &ctx, const TargetMachine &TM)
virtual void emitPersonalityValue (MCStreamer &Streamer, const TargetMachine &TM, const MCSymbol *Sym) const
const MCSection * SectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler &Mang, const TargetMachine &TM) const
const MCSection * SectionForGlobal (const GlobalValue *GV, Mangler &Mang, const TargetMachine &TM) const
virtual const MCSection * getSpecialCasedSectionGlobals (const GlobalValue *GV, SectionKind Kind, Mangler &Mang) const
Allow the target to completely override section assignment of a global.
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix, Mangler &Mang, const TargetMachine &TM) const
const MCExpr * getTTypeReference (const MCSymbolRefExpr *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual const MCSection * getStaticCtorSection (unsigned Priority, const MCSymbol *KeySym) const
virtual const MCSection * getStaticDtorSection (unsigned Priority, const MCSymbol *KeySym) const
virtual const MCExpr * getDebugThreadLocalSymbol (const MCSymbol *Sym) const
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
virtual const MCExpr * getExecutableRelativeSymbol (const ConstantExpr *CE, Mangler &Mang, const TargetMachine &TM) const
Public Member Functions inherited from llvm::MCObjectFileInfo
void InitMCObjectFileInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, MCContext &ctx)
bool getSupportsWeakOmittedEHFrame () const
bool getSupportsCompactUnwindWithoutEHFrame () const
bool getCommDirectiveSupportsAlignment () const
unsigned getPersonalityEncoding () const
unsigned getLSDAEncoding () const
unsigned getFDEEncoding () const
unsigned getTTypeEncoding () const
unsigned getCompactUnwindDwarfEHFrameOnly () const
const MCSection * getTextSection () const
const MCSection * getDataSection () const
const MCSection * getBSSSection () const
const MCSection * getLSDASection () const
const MCSection * getCompactUnwindSection () const
const MCSection * getDwarfAbbrevSection () const
const MCSection * getDwarfInfoSection () const
const MCSection * getDwarfLineSection () const
const MCSection * getDwarfFrameSection () const
const MCSection * getDwarfPubNamesSection () const
const MCSection * getDwarfPubTypesSection () const
const MCSection * getDwarfGnuPubNamesSection () const
const MCSection * getDwarfGnuPubTypesSection () const
const MCSection * getDwarfDebugInlineSection () const
const MCSection * getDwarfStrSection () const
const MCSection * getDwarfLocSection () const
const MCSection * getDwarfARangesSection () const
const MCSection * getDwarfRangesSection () const
const MCSection * getDwarfMacroInfoSection () const
const MCSection * getDwarfAccelNamesSection () const
const MCSection * getDwarfAccelObjCSection () const
const MCSection * getDwarfAccelNamespaceSection () const
const MCSection * getDwarfAccelTypesSection () const
const MCSection * getDwarfInfoDWOSection () const
const MCSection * getDwarfTypesSection (uint64_t Hash) const
const MCSection * getDwarfTypesDWOSection () const
const MCSection * getDwarfAbbrevDWOSection () const
const MCSection * getDwarfStrDWOSection () const
const MCSection * getDwarfLineDWOSection () const
const MCSection * getDwarfLocDWOSection () const
const MCSection * getDwarfStrOffDWOSection () const
const MCSection * getDwarfAddrSection () const
const MCSection * getCOFFDebugSymbolsSection () const
const MCSection * getTLSExtraDataSection () const
const MCSection * getTLSDataSection () const
const MCSection * getTLSBSSSection () const
const MCSection * getStackMapSection () const
const MCSection * getDataRelSection () const
const MCSection * getDataRelLocalSection () const
const MCSection * getDataRelROSection () const
const MCSection * getDataRelROLocalSection () const
const MCSection * getMergeableConst4Section () const
const MCSection * getMergeableConst8Section () const
const MCSection * getMergeableConst16Section () const
const MCSection * getTLSTLVSection () const
const MCSection * getTLSThreadInitSection () const
const MCSection * getCStringSection () const
const MCSection * getUStringSection () const
const MCSection * getTextCoalSection () const
const MCSection * getConstTextCoalSection () const
const MCSection * getConstDataSection () const
const MCSection * getDataCoalSection () const
const MCSection * getDataCommonSection () const
const MCSection * getDataBSSSection () const
const MCSection * getFourByteConstantSection () const
const MCSection * getEightByteConstantSection () const
const MCSection * getSixteenByteConstantSection () const
const MCSection * getLazySymbolPointerSection () const
const MCSection * getNonLazySymbolPointerSection () const
const MCSection * getDrectveSection () const
const MCSection * getPDataSection () const
const MCSection * getXDataSection () const
const MCSection * getEHFrameSection ()
Environment getObjectFileType () const
Reloc::Model getRelocM () const
const Triple & getTargetTriple () const
Additional Inherited Members
Public Types inherited from llvm::MCObjectFileInfo
enum Environment { IsMachO , IsELF , IsCOFF }
Static Public Member Functions inherited from llvm::TargetLoweringObjectFile
static SectionKind getKindForGlobal (const GlobalValue *GV, const TargetMachine &TM)
Protected Attributes inherited from llvm::MCObjectFileInfo
bool CommDirectiveSupportsAlignment
bool SupportsWeakOmittedEHFrame
bool SupportsCompactUnwindWithoutEHFrame
unsigned PersonalityEncoding
unsigned LSDAEncoding
unsigned FDECFIEncoding
unsigned TTypeEncoding
unsigned EHSectionType
Section flags for eh_frame.
unsigned EHSectionFlags
unsigned CompactUnwindDwarfEHFrameOnly
const MCSection * TextSection
const MCSection * DataSection
const MCSection * BSSSection
BSSSection - Section that is default initialized to zero.
const MCSection * ReadOnlySection
const MCSection * StaticCtorSection
const MCSection * StaticDtorSection
const MCSection * LSDASection
const MCSection * CompactUnwindSection
const MCSection * DwarfAbbrevSection
const MCSection * DwarfInfoSection
const MCSection * DwarfLineSection
const MCSection * DwarfFrameSection
const MCSection * DwarfPubTypesSection
const MCSection * DwarfDebugInlineSection
const MCSection * DwarfStrSection
const MCSection * DwarfLocSection
const MCSection * DwarfARangesSection
const MCSection * DwarfRangesSection
const MCSection * DwarfMacroInfoSection
const MCSection * DwarfPubNamesSection
const MCSection * DwarfAccelNamesSection
const MCSection * DwarfAccelObjCSection
const MCSection * DwarfAccelNamespaceSection
const MCSection * DwarfAccelTypesSection
const MCSection * DwarfInfoDWOSection
These are used for the Fission separate debug information files.
const MCSection * DwarfTypesDWOSection
const MCSection * DwarfAbbrevDWOSection
const MCSection * DwarfStrDWOSection
const MCSection * DwarfLineDWOSection
const MCSection * DwarfLocDWOSection
const MCSection * DwarfStrOffDWOSection
const MCSection * DwarfAddrSection
const MCSection * DwarfGnuPubNamesSection
Sections for newer gnu pubnames and pubtypes.
const MCSection * DwarfGnuPubTypesSection
const MCSection * COFFDebugSymbolsSection
const MCSection * TLSExtraDataSection
const MCSection * TLSDataSection
const MCSection * TLSBSSSection
const MCSection * StackMapSection
StackMap section.
const MCSection * EHFrameSection
const MCSection * DataRelSection
const MCSection * DataRelLocalSection
const MCSection * DataRelROSection
const MCSection * DataRelROLocalSection
const MCSection * MergeableConst4Section
const MCSection * MergeableConst8Section
const MCSection * MergeableConst16Section
const MCSection * TLSTLVSection
const MCSection * TLSThreadInitSection
const MCSection * CStringSection
const MCSection * UStringSection
const MCSection * TextCoalSection
const MCSection * ConstTextCoalSection
const MCSection * ConstDataSection
const MCSection * DataCoalSection
const MCSection * DataCommonSection
const MCSection * DataBSSSection
const MCSection * FourByteConstantSection
const MCSection * EightByteConstantSection
const MCSection * SixteenByteConstantSection
const MCSection * LazySymbolPointerSection
const MCSection * NonLazySymbolPointerSection
const MCSection * DrectveSection
const MCSection * PDataSection
const MCSection * XDataSection
Detailed Description
Definition at line 79 of file TargetLoweringObjectFileImpl.h.
Constructor & Destructor Documentation
~TargetLoweringObjectFileMachO()
virtual llvm::TargetLoweringObjectFileMachO::~TargetLoweringObjectFileMachO () inline virtual
Definition at line 81 of file TargetLoweringObjectFileImpl.h.
Member Function Documentation
emitModuleFlags()
void TargetLoweringObjectFileMachO::emitModuleFlags (MCStreamer & Streamer, ArrayRef< Module::ModuleFlagEntry > ModuleFlags, Mangler & Mang, const TargetMachine & TM) const override virtual
Emit the module flags that specify the garbage collection information.
emitModuleFlags - Perform code emission for module flags.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 449 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::ArrayRef< T >::begin(), llvm::Module::ModuleFlagEntry::Behavior, llvm::cast(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitLinkerOptions(), llvm::StringRef::empty(), llvm::ArrayRef< T >::end(), llvm::mdconst::extract(), llvm::TargetLoweringObjectFile::getContext(), llvm::SectionKind::getDataNoRel(), llvm::MCContext::getMachOSection(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDString::getString(), llvm::Module::ModuleFlagEntry::Key, llvm::MCSectionMachO::ParseSectionSpecifier(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::report_fatal_error(), llvm::Module::Require, llvm::MCStreamer::SwitchSection(), and llvm::Module::ModuleFlagEntry::Val.
getCFIPersonalitySymbol()
MCSymbol * TargetLoweringObjectFileMachO::getCFIPersonalitySymbol (const GlobalValue * GV, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI) const override virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Reimplemented in llvm::X86_64MachoTargetObjectFile.
Definition at line 694 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), and llvm::GlobalValue::hasLocalLinkage().
getDepLibFromLinkerOpt()
StringRef TargetLoweringObjectFileMachO::getDepLibFromLinkerOpt (StringRef LinkerOption) const override virtual
Extract the dependent library name from a linker option string. Returns StringRef() if the option does not specify a library.
getDepLibFromLinkerOpt - Extract the dependent library name from a linker option string. Returns StringRef() if the option does not specify a library.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 440 of file TargetLoweringObjectFileImpl.cpp.
References llvm::StringRef::startswith(), and llvm::StringRef::substr().
getExplicitSectionGlobal()
const MCSection * TargetLoweringObjectFileMachO::getExplicitSectionGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const override virtual
Targets should implement this method to assign a section to globals with an explicit section specfied. The implementation of this method can assume that GV->hasSection() is true.
Implements llvm::TargetLoweringObjectFile.
Definition at line 534 of file TargetLoweringObjectFileImpl.cpp.
References checkMachOComdat(), llvm::TargetLoweringObjectFile::getContext(), llvm::MCContext::getMachOSection(), llvm::Value::getName(), llvm::GlobalValue::getSection(), llvm::MCSectionMachO::getStubSize(), llvm::MCSectionMachO::getTypeAndAttributes(), llvm::MCSectionMachO::ParseSectionSpecifier(), and llvm::report_fatal_error().
getSectionForConstant()
const MCSection * TargetLoweringObjectFileMachO::getSectionForConstant (SectionKind Kind, const Constant * C) const override virtual
Given a constant with the SectionKind, return a section that it should be placed in.
getSectionForConstant - Given a mergable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 646 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCObjectFileInfo::ConstDataSection, llvm::MCObjectFileInfo::EightByteConstantSection, llvm::MCObjectFileInfo::FourByteConstantSection, llvm::MCObjectFileInfo::ReadOnlySection, and llvm::MCObjectFileInfo::SixteenByteConstantSection.
getTTypeGlobalReference()
const MCExpr * TargetLoweringObjectFileMachO::getTTypeGlobalReference (const GlobalValue * GV, unsigned Encoding, Mangler & Mang, const TargetMachine & TM, MachineModuleInfo * MMI, MCStreamer & Streamer) const override virtual
The mach-o version of this method defaults to returning a stub reference.
Reimplemented from llvm::TargetLoweringObjectFile.
Reimplemented in llvm::X86_64MachoTargetObjectFile.
Definition at line 662 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::dwarf::DW_EH_PE_indirect, llvm::TargetLoweringObjectFile::getContext(), llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::MachineModuleInfoMachO::getHiddenGVStubEntry(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::GlobalValue::hasHiddenVisibility(), and llvm::GlobalValue::hasLocalLinkage().
Referenced by llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), and llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference().
SelectSectionForGlobal()
const MCSection * TargetLoweringObjectFileMachO::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler & Mang, const TargetMachine & TM) const override virtual
Implements llvm::TargetLoweringObjectFile.
Definition at line 576 of file TargetLoweringObjectFileImpl.cpp.
References llvm::cast(), checkMachOComdat(), llvm::MCObjectFileInfo::ConstDataSection, llvm::MCObjectFileInfo::ConstTextCoalSection, llvm::MCObjectFileInfo::CStringSection, llvm::MCObjectFileInfo::DataBSSSection, llvm::MCObjectFileInfo::DataCoalSection, llvm::MCObjectFileInfo::DataCommonSection, llvm::MCObjectFileInfo::DataSection, llvm::MCObjectFileInfo::EightByteConstantSection, llvm::MCObjectFileInfo::FourByteConstantSection, llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasPrivateLinkage(), llvm::GlobalValue::isWeakForLinker(), llvm::MCObjectFileInfo::ReadOnlySection, llvm::MCObjectFileInfo::SixteenByteConstantSection, llvm::MCObjectFileInfo::TextCoalSection, llvm::MCObjectFileInfo::TextSection, llvm::MCObjectFileInfo::TLSBSSSection, llvm::MCObjectFileInfo::TLSDataSection, and llvm::MCObjectFileInfo::UStringSection.
The documentation for this class was generated from the following files:
TargetLoweringObjectFileImpl.h
TargetLoweringObjectFileImpl.cpp