LLVM: llvm::GlobalValue Class Reference
LLVM API Documentation
llvm::GlobalValue Class Reference abstract
#include <GlobalValue.h>
Public Types
enum LinkageTypes {
ExternalLinkage = 0 , AvailableExternallyLinkage , LinkOnceAnyLinkage , LinkOnceODRLinkage ,
WeakAnyLinkage , WeakODRLinkage , AppendingLinkage , InternalLinkage ,
PrivateLinkage , ExternalWeakLinkage , CommonLinkage
}
An enumeration for the kinds of linkage for global values.
enum VisibilityTypes { DefaultVisibility = 0 , HiddenVisibility , ProtectedVisibility }
An enumeration for the kinds of visibility of global values.
enum DLLStorageClassTypes { DefaultStorageClass = 0 , DLLImportStorageClass = 1 , DLLExportStorageClass = 2 }
Storage classes of global values for PE targets.
enum ThreadLocalMode {
NotThreadLocal = 0 , GeneralDynamicTLSModel , LocalDynamicTLSModel , InitialExecTLSModel ,
LocalExecTLSModel
}
Public Types inherited from llvm::Constant
enum PossibleRelocationsTy { NoRelocation = 0 , LocalRelocation = 1 , GlobalRelocations = 2 }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range< op_iterator > op_range
typedef iterator_range< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal , BasicBlockVal , FunctionVal , GlobalAliasVal ,
GlobalVariableVal , UndefValueVal , BlockAddressVal , ConstantExprVal ,
ConstantAggregateZeroVal , ConstantDataArrayVal , ConstantDataVectorVal , ConstantIntVal ,
ConstantFPVal , ConstantArrayVal , ConstantStructVal , ConstantVectorVal ,
ConstantPointerNullVal , MetadataAsValueVal , InlineAsmVal , InstructionVal ,
ConstantFirstVal = FunctionVal , ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl< const User > const_user_iterator
Public Member Functions
~GlobalValue ()
unsigned getAlignment () const
bool hasUnnamedAddr () const
void setUnnamedAddr (bool Val)
bool hasComdat () const
Comdat * getComdat ()
const Comdat * getComdat () const
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
bool isThreadLocal () const
If the value is "Thread Local", its value isn't shared by the threads.
void setThreadLocal (bool Val)
void setThreadLocalMode (ThreadLocalMode Val)
ThreadLocalMode getThreadLocalMode () const
DLLStorageClassTypes getDLLStorageClass () const
bool hasDLLImportStorageClass () const
bool hasDLLExportStorageClass () const
void setDLLStorageClass (DLLStorageClassTypes C)
bool hasSection () const
const char * getSection () const
PointerType * getType () const
Global values are always pointers.
bool hasExternalLinkage () const
bool hasAvailableExternallyLinkage () const
bool hasLinkOnceLinkage () const
bool hasLinkOnceODRLinkage () const
bool hasWeakLinkage () const
bool hasWeakAnyLinkage () const
bool hasWeakODRLinkage () const
bool hasAppendingLinkage () const
bool hasInternalLinkage () const
bool hasPrivateLinkage () const
bool hasLocalLinkage () const
bool hasExternalWeakLinkage () const
bool hasCommonLinkage () const
void setLinkage (LinkageTypes LT)
LinkageTypes getLinkage () const
bool isDiscardableIfUnused () const
bool mayBeOverridden () const
bool isWeakForLinker () const
virtual void copyAttributesFrom (const GlobalValue *Src)
void destroyConstant () override
Override from Constant class.
bool isDeclaration () const
bool isDeclarationForLinker () const
virtual void removeFromParent ()=0
virtual void eraseFromParent ()=0
This method unlinks 'this' from the containing module and deletes it.
Module * getParent ()
Get the module that this global value is contained inside of...
const Module * getParent () const
const DataLayout * getDataLayout () const
Materialization
Materialization is used to construct functions only as they're needed. This is useful to reduce memory usage in LLVM or parsing work done by the BitcodeReader to load the Module.
bool isMaterializable () const
bool isDematerializable () const
std::error_code materialize ()
void Dematerialize ()
Public Member Functions inherited from llvm::Constant
bool isNullValue () const
bool isOneValue () const
Returns true if the value is one.
bool isAllOnesValue () const
bool isNegativeZeroValue () const
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool canTrap () const
bool isThreadDependent () const
isThreadDependent - Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
PossibleRelocationsTy getRelocationInfo () const
Constant * getAggregateElement (unsigned Elt) const
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
const APInt & getUniqueInteger () const
virtual void replaceUsesOfWithOnConstant (Value *, Value *, Use *)
void removeDeadConstantUsers () const
Constant * stripPointerCasts ()
const Constant * stripPointerCasts () const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Static Public Member Functions
static LinkageTypes getLinkOnceLinkage (bool ODR)
static LinkageTypes getWeakLinkage (bool ODR)
static bool isExternalLinkage (LinkageTypes Linkage)
static bool isAvailableExternallyLinkage (LinkageTypes Linkage)
static bool isLinkOnceODRLinkage (LinkageTypes Linkage)
static bool isLinkOnceLinkage (LinkageTypes Linkage)
static bool isWeakAnyLinkage (LinkageTypes Linkage)
static bool isWeakODRLinkage (LinkageTypes Linkage)
static bool isWeakLinkage (LinkageTypes Linkage)
static bool isAppendingLinkage (LinkageTypes Linkage)
static bool isInternalLinkage (LinkageTypes Linkage)
static bool isPrivateLinkage (LinkageTypes Linkage)
static bool isLocalLinkage (LinkageTypes Linkage)
static bool isExternalWeakLinkage (LinkageTypes Linkage)
static bool isCommonLinkage (LinkageTypes Linkage)
static bool isDiscardableIfUnused (LinkageTypes Linkage)
static bool mayBeOverridden (LinkageTypes Linkage)
static bool isWeakForLinker (LinkageTypes Linkage)
static StringRef getRealLinkageName (StringRef Name)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
static Constant * getAllOnesValue (Type *Ty)
Get the all ones value.
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
GlobalValue (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name)
unsigned getGlobalValueSubClassData () const
void setGlobalValueSubClassData (unsigned V)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
void destroyConstantImpl ()
void replaceUsesOfWithOnConstantImpl (Constant *Replacement)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes
LinkageTypes Linkage: 5
unsigned Visibility: 2
unsigned UnnamedAddr: 1
unsigned DllStorageClass: 2
unsigned ThreadLocal: 3
Module * Parent
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Static Protected Attributes
static const unsigned GlobalValueSubClassDataBits = 19
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Detailed Description
Definition at line 31 of file GlobalValue.h.
Member Enumeration Documentation
DLLStorageClassTypes
enum llvm::GlobalValue::DLLStorageClassTypes
Storage classes of global values for PE targets.
Enumerator
DefaultStorageClass
DLLImportStorageClass
Function to be imported from DLL.
DLLExportStorageClass
Function to be accessible from DLL.
Definition at line 57 of file GlobalValue.h.
LinkageTypes
enum llvm::GlobalValue::LinkageTypes
An enumeration for the kinds of linkage for global values.
Enumerator
ExternalLinkage
Externally visible function.
AvailableExternallyLinkage
Available for inspection, not emission.
LinkOnceAnyLinkage
Keep one copy of function when linking (inline)
LinkOnceODRLinkage
Same, but only replaced by something equivalent.
WeakAnyLinkage
Keep one copy of named function when linking (weak)
WeakODRLinkage
Same, but only replaced by something equivalent.
AppendingLinkage
Special purpose, only applies to global arrays.
InternalLinkage
Rename collisions when linking (static functions).
PrivateLinkage
Like Internal, but omit from symbol table.
ExternalWeakLinkage
ExternalWeak linkage description.
CommonLinkage
Tentative definitions.
Definition at line 35 of file GlobalValue.h.
ThreadLocalMode
enum llvm::GlobalValue::ThreadLocalMode
Enumerator
NotThreadLocal
GeneralDynamicTLSModel
LocalDynamicTLSModel
InitialExecTLSModel
LocalExecTLSModel
Definition at line 99 of file GlobalValue.h.
VisibilityTypes
enum llvm::GlobalValue::VisibilityTypes
An enumeration for the kinds of visibility of global values.
Enumerator
DefaultVisibility
The GV is visible.
HiddenVisibility
The GV is hidden.
ProtectedVisibility
The GV is protected.
Definition at line 50 of file GlobalValue.h.
Constructor & Destructor Documentation
GlobalValue()
llvm::GlobalValue::GlobalValue (Type * Ty, ValueTy VTy, Use * Ops, unsigned NumOps, LinkageTypes Linkage, const Twine & Name) inline protected
Definition at line 64 of file GlobalValue.h.
References DefaultStorageClass, DefaultVisibility, DllStorageClass, Linkage, Name, NotThreadLocal, Parent, llvm::Value::setName(), ThreadLocal, UnnamedAddr, and Visibility.
~GlobalValue()
llvm::GlobalValue::~GlobalValue () inline
Definition at line 107 of file GlobalValue.h.
References llvm::Constant::removeDeadConstantUsers().
Member Function Documentation
classof()
bool llvm::GlobalValue::classof (const Value * V) inline static
Definition at line 352 of file GlobalValue.h.
References llvm::Value::FunctionVal, llvm::Value::GlobalAliasVal, and llvm::Value::GlobalVariableVal.
copyAttributesFrom()
void GlobalValue::copyAttributesFrom (const GlobalValue * Src) virtual
Copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
copyAttributesFrom - copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Reimplemented in llvm::Function, llvm::GlobalObject, and llvm::GlobalVariable.
Definition at line 57 of file Globals.cpp.
References getDLLStorageClass(), getVisibility(), hasUnnamedAddr(), setDLLStorageClass(), setUnnamedAddr(), and setVisibility().
Referenced by llvm::GlobalObject::copyAttributesFrom(), and copyGVAttributes().
Dematerialize()
void GlobalValue::Dematerialize ()
If this GlobalValue is read in, and if the GVMaterializer supports it, release the memory for the function, and set it up to be materialized lazily. If !isDematerializable(), this method is a noop.
Definition at line 41 of file Globals.cpp.
References llvm::Module::Dematerialize(), and getParent().
destroyConstant()
void GlobalValue::destroyConstant () override virtual
Override from Constant class.
Override destroyConstant to make sure it doesn't get called on GlobalValue's because they shouldn't be treated like other constants.
Reimplemented from llvm::Constant.
Definition at line 51 of file Globals.cpp.
References llvm_unreachable.
eraseFromParent()
virtual void llvm::GlobalValue::eraseFromParent () pure virtual
This method unlinks 'this' from the containing module and deletes it.
Implemented in llvm::Function, llvm::GlobalAlias, and llvm::GlobalVariable.
getAlignment()
unsigned GlobalValue::getAlignment () const
Definition at line 63 of file Globals.cpp.
References llvm::cast(), and llvm::dyn_cast().
Referenced by llvm::ConstantFoldBinaryInstruction(), getGVAlignmentLog2(), and llvm::SystemZSubtarget::isPC32DBLSymbol().
getComdat() [1/2]
Comdat * GlobalValue::getComdat ()
Definition at line 116 of file Globals.cpp.
References llvm::cast(), llvm::dyn_cast(), and getComdat().
Referenced by checkMachOComdat(), getComdat(), getComdat(), getComdatGVForCOFF(), getELFComdat(), getSelectionForCOFF(), and hasComdat().
getComdat() [2/2]
const Comdat * llvm::GlobalValue::getComdat () const inline
Definition at line 118 of file GlobalValue.h.
References getComdat().
getDataLayout()
const DataLayout * GlobalValue::getDataLayout () const
Definition at line 45 of file Globals.cpp.
References llvm::Module::getDataLayout(), and getParent().
Referenced by llvm::BasicBlock::getDataLayout(), and llvm::InlineCostAnalysis::getInlineCost().
getDLLStorageClass()
DLLStorageClassTypes llvm::GlobalValue::getDLLStorageClass () const inline
Definition at line 147 of file GlobalValue.h.
References DllStorageClass.
Referenced by copyAttributesFrom(), getEncodedDLLStorageClass(), llvm::AssemblyWriter::printAlias(), and llvm::AssemblyWriter::printGlobal().
getGlobalValueSubClassData()
unsigned llvm::GlobalValue::getGlobalValueSubClassData () const inline protected
Definition at line 89 of file GlobalValue.h.
Referenced by llvm::GlobalObject::getAlignment(), llvm::GlobalObject::getGlobalObjectSubClassData(), llvm::GlobalObject::setAlignment(), and llvm::GlobalObject::setGlobalObjectSubClassData().
getLinkage()
LinkageTypes llvm::GlobalValue::getLinkage () const inline
Definition at line 273 of file GlobalValue.h.
References Linkage.
Referenced by copyFunctionProto(), copyGlobalAliasProto(), copyGlobalVariableProto(), llvm::GlobalAlias::create(), getEncodedLinkage(), makeVisible(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), and upgradeGlobalArray().
getLinkOnceLinkage()
LinkageTypes llvm::GlobalValue::getLinkOnceLinkage (bool ODR) inline static
Definition at line 172 of file GlobalValue.h.
References LinkOnceAnyLinkage, and LinkOnceODRLinkage.
getParent() [1/2]
Module * llvm::GlobalValue::getParent () inline
Get the module that this global value is contained inside of...
Definition at line 346 of file GlobalValue.h.
References Parent.
Referenced by callIntrinsic(), changeToUnreachable(), CloneDebugInfoMetadata(), llvm::GlobalAlias::create(), createFree(), createMalloc(), Dematerialize(), llvm::RegionBase< RegionTraits< MachineFunction > >::dump(), llvm::EmitBinaryFloatFnCall(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), llvm::EmitUnaryFloatFnCall(), llvm::Function::eraseFromParent(), llvm::GlobalAlias::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::CodeExtractor::extractCodeRegion(), llvm::findAllNVVMAnnotation(), llvm::findOneNVVMAnnotation(), forceRenaming(), GenerateARCBBEntranceAnnotation(), GenerateARCBBTerminatorAnnotation(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getCaller(), getComdatGVForCOFF(), getDataLayout(), llvm::Trace::getModule(), getModuleFromVal(), getParent(), llvm::SparcTargetLowering::getSRetArgSize(), llvm::GlobalVariable::GlobalVariable(), hasReturnsTwiceAttr(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::InlineFunction(), insertSinCosCall(), isDematerializable(), llvm::isImageReadOnly(), llvm::isImageReadWrite(), llvm::isImageWriteOnly(), llvm::isSampler(), LLVMGetNextGlobal(), LLVMGetPreviousGlobal(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::ARMTargetLowering::makeDMB(), materialize(), OptimizeGlobalAddressOfMalloc(), PerformHeapAllocSRoA(), llvm::AssemblyWriter::printGlobal(), promoteSingleBlockAlloca(), llvm::Function::removeFromParent(), llvm::GlobalAlias::removeFromParent(), llvm::GlobalVariable::removeFromParent(), ReplaceCallWith(), rewriteSingleStoreAlloca(), llvm::StackProtector::runOnFunction(), SRAGlobal(), SwitchToLookupTable(), TryToShrinkGlobalToBoolean(), upgradeGlobalArray(), usedInOneFunc(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitFPTrunc().
getParent() [2/2]
const Module * llvm::GlobalValue::getParent () const inline
Definition at line 347 of file GlobalValue.h.
References Parent.
getRealLinkageName()
StringRef llvm::GlobalValue::getRealLinkageName (StringRef Name) inline static
If special LLVM prefix that is used to inform the asm printer to not emit usual symbol prefix before the symbol name is used then return linkage name after skipping this special LLVM prefix.
Definition at line 290 of file GlobalValue.h.
References Name.
Referenced by llvm::DwarfUnit::applySubprogramDefinitionAttributes(), and llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE().
getSection()
const char * GlobalValue::getSection () const
Definition at line 106 of file Globals.cpp.
References llvm::cast(), and llvm::dyn_cast().
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), and hasSection().
getThreadLocalMode()
ThreadLocalMode llvm::GlobalValue::getThreadLocalMode () const inline
Definition at line 143 of file GlobalValue.h.
References ThreadLocal.
Referenced by llvm::GlobalVariable::copyAttributesFrom(), copyGlobalVariableProto(), getEncodedThreadLocalMode(), getSelectedTLSModel(), isThreadLocal(), OptimizeGlobalAddressOfMalloc(), PerformHeapAllocSRoA(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printGlobal(), SRAGlobal(), TryToShrinkGlobalToBoolean(), and upgradeGlobalArray().
getType()
PointerType * llvm::GlobalValue::getType () const inline
Global values are always pointers.
Definition at line 168 of file GlobalValue.h.
References llvm::cast(), and llvm::Value::getType().
Referenced by canDemoteGlobalVar(), copyGlobalAliasProto(), copyGlobalVariableProto(), llvm::GlobalAlias::create(), llvm::BlockAddress::destroyConstant(), llvm::ExecutionEngine::emitGlobals(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::ExecutionEngine::EmitGlobalVariable(), llvm::GlobalAddressSDNode::getAddressSpace(), llvm::Function::getContext(), llvm::Function::getFunctionType(), llvm::SelectionDAG::getGlobalAddress(), llvm::Module::getOrInsertGlobal(), llvm::DataLayout::getPreferredAlignment(), llvm::SelectionDAG::InferPtrAlignment(), IsConstantOffsetFromGlobal(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl(), isLeakCheckerRoot(), IsSmallObject(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), OptimizeGlobalAddressOfMalloc(), PerformHeapAllocSRoA(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::GlobalAlias::setAliasee(), llvm::GlobalVariable::setInitializer(), SRAGlobal(), TryToShrinkGlobalToBoolean(), upgradeGlobalArray(), and llvm::ObjectSizeOffsetVisitor::visitGlobalVariable().
getVisibility()
VisibilityTypes llvm::GlobalValue::getVisibility () const inline
Definition at line 122 of file GlobalValue.h.
References Visibility.
Referenced by copyAttributesFrom(), llvm::AsmPrinter::EmitGlobalVariable(), getEncodedVisibility(), llvm::AssemblyWriter::printAlias(), and llvm::AssemblyWriter::printGlobal().
getWeakLinkage()
LinkageTypes llvm::GlobalValue::getWeakLinkage (bool ODR) inline static
Definition at line 175 of file GlobalValue.h.
References WeakAnyLinkage, and WeakODRLinkage.
hasAppendingLinkage()
bool llvm::GlobalValue::hasAppendingLinkage () const inline
Definition at line 261 of file GlobalValue.h.
References isAppendingLinkage(), and Linkage.
Referenced by llvm::ExecutionEngine::emitGlobals(), and llvm::AsmPrinter::EmitSpecialLLVMGlobal().
hasAvailableExternallyLinkage()
bool llvm::GlobalValue::hasAvailableExternallyLinkage () const inline
Definition at line 245 of file GlobalValue.h.
References isAvailableExternallyLinkage(), and Linkage.
Referenced by llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::TargetLoweringObjectFile::getKindForGlobal(), isDeclarationForLinker(), llvm::Function::isDefTriviallyDead(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), and shouldInternalize().
hasComdat()
bool llvm::GlobalValue::hasComdat () const inline
Definition at line 116 of file GlobalValue.h.
References getComdat().
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
hasCommonLinkage()
bool llvm::GlobalValue::hasCommonLinkage () const inline
Definition at line 266 of file GlobalValue.h.
References isCommonLinkage(), and Linkage.
Referenced by llvm::X86Subtarget::ClassifyGlobalReference(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::object::IRObjectFile::getSymbolFlags(), llvm::ARMSubtarget::GVIsIndirectSymbol(), llvm::PPCSubtarget::hasLazyResolverStub(), and llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl().
hasDefaultVisibility()
bool llvm::GlobalValue::hasDefaultVisibility () const inline
Definition at line 123 of file GlobalValue.h.
References DefaultVisibility, and Visibility.
Referenced by bindsLocally(), llvm::AArch64Subtarget::ClassifyGlobalReference(), and llvm::X86Subtarget::ClassifyGlobalReference().
hasDLLExportStorageClass()
bool llvm::GlobalValue::hasDLLExportStorageClass () const inline
Definition at line 153 of file GlobalValue.h.
References DLLExportStorageClass, and DllStorageClass.
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile(), and shouldInternalize().
hasDLLImportStorageClass()
bool llvm::GlobalValue::hasDLLImportStorageClass () const inline
Definition at line 150 of file GlobalValue.h.
References DLLImportStorageClass, and DllStorageClass.
Referenced by llvm::X86Subtarget::ClassifyGlobalReference(), and isSimpleEnoughValueToCommitHelper().
hasExternalLinkage()
bool llvm::GlobalValue::hasExternalLinkage () const inline
Definition at line 244 of file GlobalValue.h.
References isExternalLinkage(), and Linkage.
Referenced by llvm::ExecutionEngine::emitGlobals(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl(), llvm::AssemblyWriter::printGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
hasExternalWeakLinkage()
bool llvm::GlobalValue::hasExternalWeakLinkage () const inline
Definition at line 265 of file GlobalValue.h.
References isExternalWeakLinkage(), and Linkage.
Referenced by llvm::ExecutionEngine::emitGlobals().
hasHiddenVisibility()
bool llvm::GlobalValue::hasHiddenVisibility () const inline
Definition at line 124 of file GlobalValue.h.
References HiddenVisibility, and Visibility.
Referenced by llvm::X86Subtarget::ClassifyGlobalReference(), llvm::TargetMachine::getTLSModel(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::ARMSubtarget::GVIsIndirectSymbol(), and llvm::PPCSubtarget::hasLazyResolverStub().
hasInternalLinkage()
bool llvm::GlobalValue::hasInternalLinkage () const inline
Definition at line 262 of file GlobalValue.h.
References isInternalLinkage(), and Linkage.
Referenced by canDemoteGlobalVar(), GetSymbolFromOperand(), and printSymbolOperand().
hasLinkOnceLinkage()
bool llvm::GlobalValue::hasLinkOnceLinkage () const inline
Definition at line 248 of file GlobalValue.h.
References isLinkOnceLinkage(), and Linkage.
Referenced by llvm::object::IRObjectFile::getSymbolFlags(), llvm::PPCSubtarget::hasLazyResolverStub(), llvm::Function::isDefTriviallyDead(), and makeVisible().
hasLinkOnceODRLinkage()
bool llvm::GlobalValue::hasLinkOnceODRLinkage () const inline
Definition at line 251 of file GlobalValue.h.
References isLinkOnceODRLinkage(), and Linkage.
Referenced by llvm::canBeOmittedFromSymbolTable().
hasLocalLinkage()
bool llvm::GlobalValue::hasLocalLinkage () const inline
Definition at line 264 of file GlobalValue.h.
References isLocalLinkage(), and Linkage.
Referenced by bindsLocally(), llvm::AArch64Subtarget::ClassifyGlobalReference(), llvm::X86Subtarget::ClassifyGlobalReference(), llvm::ExecutionEngine::emitGlobals(), forceRenaming(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::object::IRObjectFile::getSymbolFlags(), llvm::TargetMachine::getTLSModel(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::ARMSubtarget::GVIsIndirectSymbol(), IsBetterCanonical(), llvm::Function::isDefTriviallyDead(), llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl(), makeVisible(), mayHaveOtherReferences(), llvm::Inliner::runOnSCC(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), setVisibility(), shouldInternalize(), and SRAGlobal().
hasPrivateLinkage()
bool llvm::GlobalValue::hasPrivateLinkage () const inline
Definition at line 263 of file GlobalValue.h.
References isPrivateLinkage(), and Linkage.
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::Mangler::getNameWithPrefix(), llvm::TargetMachine::getNameWithPrefix(), llvm::object::IRObjectFile::getSymbolFlags(), isLeakCheckerRoot(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
hasProtectedVisibility()
bool llvm::GlobalValue::hasProtectedVisibility () const inline
Definition at line 125 of file GlobalValue.h.
References ProtectedVisibility, and Visibility.
hasSection()
bool llvm::GlobalValue::hasSection () const inline
Definition at line 158 of file GlobalValue.h.
References llvm::StringRef::empty(), and getSection().
Referenced by getGVAlignmentLog2(), and llvm::TargetLoweringObjectFile::SectionForGlobal().
hasUnnamedAddr()
bool llvm::GlobalValue::hasUnnamedAddr () const inline
Definition at line 113 of file GlobalValue.h.
References UnnamedAddr.
Referenced by llvm::canBeOmittedFromSymbolTable(), copyAttributesFrom(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::AssemblyWriter::printAlias(), and llvm::AssemblyWriter::printGlobal().
hasWeakAnyLinkage()
bool llvm::GlobalValue::hasWeakAnyLinkage () const inline
Definition at line 255 of file GlobalValue.h.
References isWeakAnyLinkage(), and Linkage.
hasWeakLinkage()
bool llvm::GlobalValue::hasWeakLinkage () const inline
Definition at line 252 of file GlobalValue.h.
References isWeakLinkage(), and Linkage.
Referenced by llvm::object::IRObjectFile::getSymbolFlags(), and llvm::PPCSubtarget::hasLazyResolverStub().
hasWeakODRLinkage()
bool llvm::GlobalValue::hasWeakODRLinkage () const inline
Definition at line 258 of file GlobalValue.h.
References isWeakODRLinkage(), and Linkage.
isAppendingLinkage()
bool llvm::GlobalValue::isAppendingLinkage (LinkageTypes Linkage) inline static
Definition at line 200 of file GlobalValue.h.
References AppendingLinkage, and Linkage.
Referenced by hasAppendingLinkage().
isAvailableExternallyLinkage()
bool llvm::GlobalValue::isAvailableExternallyLinkage (LinkageTypes Linkage) inline static
Definition at line 182 of file GlobalValue.h.
References AvailableExternallyLinkage, and Linkage.
Referenced by hasAvailableExternallyLinkage().
isCommonLinkage()
bool llvm::GlobalValue::isCommonLinkage (LinkageTypes Linkage) inline static
Definition at line 215 of file GlobalValue.h.
References CommonLinkage, and Linkage.
Referenced by hasCommonLinkage().
isDeclaration()
bool GlobalValue::isDeclaration () const
Return true if the primary definition of this global value is outside of the current translation unit.
Definition at line 128 of file Globals.cpp.
References llvm::dyn_cast(), F, and llvm::isa().
Referenced by assureFPCallStub(), cxxDtorIsEmpty(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ExecutionEngine::emitGlobals(), llvm::AsmPrinter::EmitGlobalVariable(), getCalledFunction(), llvm::Inliner::getInlineThreshold(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::TargetMachine::getTLSModel(), llvm::GlobalVariable::hasInitializer(), llvm::PPCSubtarget::hasLazyResolverStub(), llvm::InlineFunction(), isDeclarationForLinker(), llvm::isFreeCall(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl(), llvm::TargetLowering::isOffsetFoldingLegal(), isReportingError(), llvm::Inliner::runOnSCC(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), and shouldInternalize().
isDeclarationForLinker()
bool llvm::GlobalValue::isDeclarationForLinker () const inline
Definition at line 331 of file GlobalValue.h.
References hasAvailableExternallyLinkage(), and isDeclaration().
Referenced by llvm::AArch64Subtarget::ClassifyGlobalReference(), llvm::X86Subtarget::ClassifyGlobalReference(), llvm::object::IRObjectFile::getSymbolFlags(), and llvm::ARMSubtarget::GVIsIndirectSymbol().
isDematerializable()
bool GlobalValue::isDematerializable () const
Returns true if this function was loaded from a GVMaterializer that's still attached to its Module and that knows how to dematerialize the function.
Definition at line 35 of file Globals.cpp.
References getParent(), and llvm::Module::isDematerializable().
isDiscardableIfUnused() [1/2]
bool llvm::GlobalValue::isDiscardableIfUnused () const inline
Definition at line 275 of file GlobalValue.h.
References isDiscardableIfUnused(), and Linkage.
Referenced by isDiscardableIfUnused().
isDiscardableIfUnused() [2/2]
bool llvm::GlobalValue::isDiscardableIfUnused (LinkageTypes Linkage) inline static
Whether the definition of this global may be discarded if it is not used in its compilation unit.
Definition at line 221 of file GlobalValue.h.
References isLinkOnceLinkage(), isLocalLinkage(), and Linkage.
Referenced by makeVisible().
isExternalLinkage()
bool llvm::GlobalValue::isExternalLinkage (LinkageTypes Linkage) inline static
Definition at line 179 of file GlobalValue.h.
References ExternalLinkage, and Linkage.
Referenced by hasExternalLinkage(), and llvm::GlobalAlias::isValidLinkage().
isExternalWeakLinkage()
bool llvm::GlobalValue::isExternalWeakLinkage (LinkageTypes Linkage) inline static
Definition at line 212 of file GlobalValue.h.
References ExternalWeakLinkage, and Linkage.
Referenced by hasExternalWeakLinkage().
isInternalLinkage()
bool llvm::GlobalValue::isInternalLinkage (LinkageTypes Linkage) inline static
Definition at line 203 of file GlobalValue.h.
References InternalLinkage, and Linkage.
Referenced by hasInternalLinkage(), and isLocalLinkage().
isLinkOnceLinkage()
bool llvm::GlobalValue::isLinkOnceLinkage (LinkageTypes Linkage) inline static
Definition at line 188 of file GlobalValue.h.
References Linkage, LinkOnceAnyLinkage, and LinkOnceODRLinkage.
Referenced by hasLinkOnceLinkage(), isDiscardableIfUnused(), and llvm::GlobalAlias::isValidLinkage().
isLinkOnceODRLinkage()
bool llvm::GlobalValue::isLinkOnceODRLinkage (LinkageTypes Linkage) inline static
Definition at line 185 of file GlobalValue.h.
References Linkage, and LinkOnceODRLinkage.
Referenced by hasLinkOnceODRLinkage().
isLocalLinkage()
bool llvm::GlobalValue::isLocalLinkage (LinkageTypes Linkage) inline static
Definition at line 209 of file GlobalValue.h.
References isInternalLinkage(), isPrivateLinkage(), and Linkage.
Referenced by hasLocalLinkage(), isDiscardableIfUnused(), llvm::GlobalAlias::isValidLinkage(), isValidVisibilityForLinkage(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), and setLinkage().
isMaterializable()
bool GlobalValue::isMaterializable () const
If this function's Module is being lazily streamed in functions from disk or some other source, this method can be used to check to see if the function has been read in yet or not.
Definition at line 30 of file Globals.cpp.
References llvm::dyn_cast(), and F.
Referenced by llvm::AssemblyWriter::printAlias(), and llvm::AssemblyWriter::printGlobal().
isPrivateLinkage()
bool llvm::GlobalValue::isPrivateLinkage (LinkageTypes Linkage) inline static
Definition at line 206 of file GlobalValue.h.
References Linkage, and PrivateLinkage.
Referenced by hasPrivateLinkage(), and isLocalLinkage().
isThreadLocal()
bool llvm::GlobalValue::isThreadLocal () const inline
If the value is "Thread Local", its value isn't shared by the threads.
Definition at line 135 of file GlobalValue.h.
References getThreadLocalMode(), and NotThreadLocal.
Referenced by llvm::ExecutionEngine::EmitGlobalVariable(), llvm::SelectionDAG::getGlobalAddress(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), and isSimpleEnoughValueToCommitHelper().
isWeakAnyLinkage()
bool llvm::GlobalValue::isWeakAnyLinkage (LinkageTypes Linkage) inline static
Definition at line 191 of file GlobalValue.h.
References Linkage, and WeakAnyLinkage.
Referenced by hasWeakAnyLinkage(), and isWeakLinkage().
isWeakForLinker() [1/2]
bool llvm::GlobalValue::isWeakForLinker () const inline
Definition at line 281 of file GlobalValue.h.
References isWeakForLinker(), and Linkage.
Referenced by llvm::GlobalVariable::hasUniqueInitializer(), and isWeakForLinker().
isWeakForLinker() [2/2]
bool llvm::GlobalValue::isWeakForLinker (LinkageTypes Linkage) inline static
Whether the definition of this global may be replaced at link time. NB: Using this method outside of the code generators is almost always a mistake: when working at the IR level use mayBeOverridden instead as it knows about ODR semantics.
Definition at line 237 of file GlobalValue.h.
References AvailableExternallyLinkage, CommonLinkage, ExternalWeakLinkage, Linkage, LinkOnceAnyLinkage, LinkOnceODRLinkage, WeakAnyLinkage, and WeakODRLinkage.
Referenced by llvm::AArch64Subtarget::ClassifyGlobalReference(), llvm::X86Subtarget::ClassifyGlobalReference(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), getSelectionForCOFF(), llvm::ARMSubtarget::GVIsIndirectSymbol(), llvm::TargetLowering::isOffsetFoldingLegal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
isWeakLinkage()
bool llvm::GlobalValue::isWeakLinkage (LinkageTypes Linkage) inline static
Definition at line 197 of file GlobalValue.h.
References isWeakAnyLinkage(), isWeakODRLinkage(), and Linkage.
Referenced by hasWeakLinkage(), and llvm::GlobalAlias::isValidLinkage().
isWeakODRLinkage()
bool llvm::GlobalValue::isWeakODRLinkage (LinkageTypes Linkage) inline static
Definition at line 194 of file GlobalValue.h.
References Linkage, and WeakODRLinkage.
Referenced by hasWeakODRLinkage(), and isWeakLinkage().
materialize()
std::error_code GlobalValue::materialize ()
Make sure this GlobalValue is fully read. If the module is corrupt, this returns true and fills in the optional string with information about the problem. If successful, this returns false.
Definition at line 38 of file Globals.cpp.
References getParent(), and llvm::Module::materialize().
mayBeOverridden() [1/2]
bool llvm::GlobalValue::mayBeOverridden () const inline
Definition at line 279 of file GlobalValue.h.
References Linkage, and mayBeOverridden().
Referenced by llvm::GlobalVariable::hasDefinitiveInitializer(), and mayBeOverridden().
mayBeOverridden() [2/2]
bool llvm::GlobalValue::mayBeOverridden (LinkageTypes Linkage) inline static
Whether the definition of this global may be replaced by something non-equivalent at link time. For example, if a function has weak linkage then the code defining it may be replaced by different code.
Definition at line 228 of file GlobalValue.h.
References CommonLinkage, ExternalWeakLinkage, Linkage, LinkOnceAnyLinkage, and WeakAnyLinkage.
Referenced by llvm::InlineCostAnalysis::getInlineCost(), and llvm::ObjectSizeOffsetVisitor::visitGlobalAlias().
removeFromParent()
virtual void llvm::GlobalValue::removeFromParent () pure virtual
This method unlinks 'this' from the containing module, but does not delete it.
Implemented in llvm::Function, llvm::GlobalAlias, and llvm::GlobalVariable.
setDLLStorageClass()
void llvm::GlobalValue::setDLLStorageClass (DLLStorageClassTypes C) inline
Definition at line 156 of file GlobalValue.h.
References DllStorageClass.
Referenced by copyAttributesFrom(), and UpgradeDLLImportExportLinkage().
setGlobalValueSubClassData()
void llvm::GlobalValue::setGlobalValueSubClassData (unsigned V) inline protected
Definition at line 92 of file GlobalValue.h.
Referenced by llvm::GlobalObject::GlobalObject(), llvm::GlobalObject::setAlignment(), and llvm::GlobalObject::setGlobalObjectSubClassData().
setLinkage()
void llvm::GlobalValue::setLinkage (LinkageTypes LT) inline
Definition at line 268 of file GlobalValue.h.
References DefaultVisibility, isLocalLinkage(), Linkage, and Visibility.
Referenced by llvm::Function::deleteBody(), LLVMSetLinkage(), and makeVisible().
setThreadLocal()
void llvm::GlobalValue::setThreadLocal (bool Val) inline
Definition at line 136 of file GlobalValue.h.
References GeneralDynamicTLSModel, NotThreadLocal, and setThreadLocalMode().
setThreadLocalMode()
void llvm::GlobalValue::setThreadLocalMode (ThreadLocalMode Val) inline
Definition at line 139 of file GlobalValue.h.
References llvm::Value::FunctionVal, llvm::Value::getValueID(), NotThreadLocal, and ThreadLocal.
Referenced by llvm::GlobalVariable::copyAttributesFrom(), llvm::GlobalVariable::GlobalVariable(), llvm::GlobalVariable::GlobalVariable(), LLVMSetThreadLocalMode(), and setThreadLocal().
setUnnamedAddr()
void llvm::GlobalValue::setUnnamedAddr (bool Val) inline
Definition at line 114 of file GlobalValue.h.
References UnnamedAddr.
Referenced by copyAttributesFrom(), llvm::IRBuilderBase::CreateGlobalString(), and createPrivateGlobalForString().
setVisibility()
void llvm::GlobalValue::setVisibility (VisibilityTypes V) inline
Definition at line 128 of file GlobalValue.h.
References DefaultVisibility, hasLocalLinkage(), and Visibility.
Referenced by copyAttributesFrom(), and makeVisible().
Member Data Documentation
DllStorageClass
unsigned llvm::GlobalValue::DllStorageClass protected
Definition at line 78 of file GlobalValue.h.
Referenced by getDLLStorageClass(), GlobalValue(), hasDLLExportStorageClass(), hasDLLImportStorageClass(), and setDLLStorageClass().
GlobalValueSubClassDataBits
const unsigned llvm::GlobalValue::GlobalValueSubClassDataBits = 19 static protected
Definition at line 88 of file GlobalValue.h.
Linkage
LinkageTypes llvm::GlobalValue::Linkage protected
Definition at line 75 of file GlobalValue.h.
Referenced by llvm::Function::Create(), llvm::GlobalAlias::create(), llvm::GlobalAlias::create(), getLinkage(), llvm::GlobalObject::GlobalObject(), GlobalValue(), hasAppendingLinkage(), hasAvailableExternallyLinkage(), hasCommonLinkage(), hasExternalLinkage(), hasExternalWeakLinkage(), hasInternalLinkage(), hasLinkOnceLinkage(), hasLinkOnceODRLinkage(), hasLocalLinkage(), hasPrivateLinkage(), hasWeakAnyLinkage(), hasWeakLinkage(), hasWeakODRLinkage(), isAppendingLinkage(), isAvailableExternallyLinkage(), isCommonLinkage(), isDiscardableIfUnused(), isDiscardableIfUnused(), isExternalLinkage(), isExternalWeakLinkage(), isInternalLinkage(), isLinkOnceLinkage(), isLinkOnceODRLinkage(), isLocalLinkage(), isPrivateLinkage(), isWeakAnyLinkage(), isWeakForLinker(), isWeakForLinker(), isWeakLinkage(), isWeakODRLinkage(), mayBeOverridden(), mayBeOverridden(), and setLinkage().
Parent
Module* llvm::GlobalValue::Parent protected
Definition at line 97 of file GlobalValue.h.
Referenced by llvm::GlobalAlias::create(), getParent(), getParent(), and GlobalValue().
ThreadLocal
unsigned llvm::GlobalValue::ThreadLocal protected
Definition at line 80 of file GlobalValue.h.
Referenced by getThreadLocalMode(), GlobalValue(), and setThreadLocalMode().
UnnamedAddr
unsigned llvm::GlobalValue::UnnamedAddr protected
Definition at line 77 of file GlobalValue.h.
Referenced by GlobalValue(), hasUnnamedAddr(), and setUnnamedAddr().
Visibility
unsigned llvm::GlobalValue::Visibility protected
Definition at line 76 of file GlobalValue.h.
Referenced by getVisibility(), GlobalValue(), hasDefaultVisibility(), hasHiddenVisibility(), hasProtectedVisibility(), setLinkage(), and setVisibility().
The documentation for this class was generated from the following files:
GlobalValue.h
Globals.cpp