LLVM: llvm::hash_code Class Reference
LLVM API Documentation
llvm::hash_code Class Reference
An opaque object representing a hash code.
#include <Hashing.h>
Public Member Functions
hash_code ()
Default construct a hash_code. Note that this leaves the value uninitialized.
hash_code (size_t value)
Form a hash code directly from a numerical value.
operator size_t () const
Convert the hash code to its numerical value for use.
Friends
bool operator== (const hash_code &lhs, const hash_code &rhs)
bool operator!= (const hash_code &lhs, const hash_code &rhs)
size_t hash_value (const hash_code &code)
Allow a hash_code to be directly run through hash_value.
Detailed Description
An opaque object representing a hash code.
This object represents the result of hashing some entity. It is intended to be used to implement hashtables or other hashing-based data structures. While it wraps and exposes a numeric value, this value should not be trusted to be stable or predictable across processes or executions.
In order to obtain the hash_code for an object 'x':
using llvm::hash_value;
llvm::hash_code code = hash_value(x);
Definition at line 78 of file Hashing.h.
Constructor & Destructor Documentation
hash_code() [1/2]
llvm::hash_code::hash_code () inline
Default construct a hash_code. Note that this leaves the value uninitialized.
Definition at line 84 of file Hashing.h.
Referenced by hash_value, operator!=, and operator==.
hash_code() [2/2]
llvm::hash_code::hash_code (size_t value) inline
Form a hash code directly from a numerical value.
Definition at line 87 of file Hashing.h.
Member Function Documentation
operator size_t()
llvm::hash_code::operator size_t () const inline
Convert the hash code to its numerical value for use.
Definition at line 90 of file Hashing.h.
Friends And Related Symbol Documentation
hash_value
size_t hash_value (const hash_code & code) friend
Allow a hash_code to be directly run through hash_value.
Definition at line 100 of file Hashing.h.
References hash_code().
operator!=
bool operator!= (const hash_code & lhs, const hash_code & rhs) friend
Definition at line 95 of file Hashing.h.
References hash_code().
operator==
bool operator== (const hash_code & lhs, const hash_code & rhs) friend
Definition at line 92 of file Hashing.h.
References hash_code().
The documentation for this class was generated from the following file:
Hashing.h