LLVM: llvm::coverage::ObjectFileCoverageMappingReader Class Reference
LLVM API Documentation
llvm::coverage::ObjectFileCoverageMappingReader Class Reference
Reader for the coverage mapping data that is emitted by the frontend and stored in an object file.
#include <CoverageMappingReader.h>
Classes
struct ProfileMappingRecord
Public Member Functions
ObjectFileCoverageMappingReader (StringRef FileName)
ObjectFileCoverageMappingReader (std::unique_ptr< MemoryBuffer > &ObjectBuffer, sys::fs::file_magic Type=sys::fs::file_magic::unknown)
std::error_code readHeader ()
std::error_code readNextRecord (CoverageMappingRecord &Record)
CoverageMappingIterator begin ()
Iterator over profile data.
CoverageMappingIterator end ()
bool isEOF ()
Return true if the reader has finished reading the profile data.
bool hasError ()
Return true if the reader encountered an error reading profiling data.
std::error_code getError ()
Get the current error code.
Detailed Description
Reader for the coverage mapping data that is emitted by the frontend and stored in an object file.
Definition at line 141 of file CoverageMappingReader.h.
Constructor & Destructor Documentation
ObjectFileCoverageMappingReader() [1/2]
ObjectFileCoverageMappingReader::ObjectFileCoverageMappingReader (StringRef FileName)
Definition at line 297 of file CoverageMappingReader.cpp.
References llvm::object::ObjectFile::createObjectFile().
ObjectFileCoverageMappingReader() [2/2]
ObjectFileCoverageMappingReader::ObjectFileCoverageMappingReader (std::unique_ptr< MemoryBuffer > & ObjectBuffer, sys::fs::file_magic Type = sys::fs::file_magic::unknown)
Definition at line 459 of file CoverageMappingReader.cpp.
References readCoverageMappingData(), and TestingFormatMagic.
Member Function Documentation
begin()
CoverageMappingIterator llvm::coverage::ObjectFileCoverageMappingReader::begin () inline
Iterator over profile data.
Definition at line 193 of file CoverageMappingReader.h.
end()
CoverageMappingIterator llvm::coverage::ObjectFileCoverageMappingReader::end () inline
Definition at line 194 of file CoverageMappingReader.h.
getError()
std::error_code llvm::coverage::ObjectFileCoverageMappingReader::getError () inline
Get the current error code.
Definition at line 202 of file CoverageMappingReader.h.
Referenced by readHeader().
hasError()
bool llvm::coverage::ObjectFileCoverageMappingReader::hasError () inline
Return true if the reader encountered an error reading profiling data.
Definition at line 200 of file CoverageMappingReader.h.
References isEOF().
isEOF()
bool llvm::coverage::ObjectFileCoverageMappingReader::isEOF () inline
Return true if the reader has finished reading the profile data.
Definition at line 197 of file CoverageMappingReader.h.
References llvm::eof.
Referenced by hasError().
readHeader()
std::error_code ObjectFileCoverageMappingReader::readHeader ()
Definition at line 487 of file CoverageMappingReader.cpp.
References llvm::bad_header, llvm::object::ObjectFile::getBytesInAddress(), getError(), llvm::malformed, Name, readCoverageMappingData(), llvm::object::ObjectFile::sections(), and llvm::object::success.
Referenced by llvm::coverage::CoverageMapping::load().
readNextRecord()
std::error_code ObjectFileCoverageMappingReader::readNextRecord (CoverageMappingRecord & Record)
Definition at line 536 of file CoverageMappingReader.cpp.
References llvm::eof, llvm::makeArrayRef(), llvm::coverage::RawCoverageMappingReader::read(), and llvm::object::success.
The documentation for this class was generated from the following files:
CoverageMappingReader.h
CoverageMappingReader.cpp