LLVM: llvm::DWARFDebugLocDWO Class Reference
LLVM API Documentation
llvm::DWARFDebugLocDWO Class Reference
#include <DWARFDebugLoc.h>
Public Member Functions
void parse (DataExtractor data)
void dump (raw_ostream &OS) const
Detailed Description
Definition at line 59 of file DWARFDebugLoc.h.
Member Function Documentation
dump()
void DWARFDebugLocDWO::dump (raw_ostream & OS) const
Definition at line 112 of file DWARFDebugLoc.cpp.
References llvm::format(), and llvm::raw_ostream::indent().
Referenced by llvm::DWARFContext::dump().
parse()
void DWARFDebugLocDWO::parse (DataExtractor data)
Definition at line 79 of file DWARFDebugLoc.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::StringRef::begin(), llvm::dwarf::DW_LLE_end_of_list_entry, llvm::dwarf::DW_LLE_start_length_entry, llvm::StringRef::end(), llvm::errs(), llvm::DataExtractor::getData(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getULEB128(), llvm::DataExtractor::isValidOffset(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::StringRef::size(), and llvm::StringRef::substr().
The documentation for this class was generated from the following files:
DWARFDebugLoc.h
DWARFDebugLoc.cpp