LLVM: llvm::AttributeSet Class Reference
LLVM API Documentation
llvm::AttributeSet Class Reference
This class holds the attributes for a function, its return value, and its parameters. You access the attributes for each of them via an index into the AttributeSet object. The function attributes are at index ‘AttributeSet::FunctionIndex’, the return value is at index / ‘AttributeSet::ReturnIndex’, and the attributes for the parameters start at index ‘1’.
#include <Attributes.h>
Public Types
enum AttrIndex : unsigned { ReturnIndex = 0U , FunctionIndex = ~0U }
typedef ArrayRef< Attribute >::iterator iterator
Public Member Functions
AttributeSet ()
AttributeSet addAttribute (LLVMContext &C, unsigned Index, Attribute::AttrKind Attr) const
Add an attribute to the attribute set at the given index. Since attribute sets are immutable, this returns a new set.
AttributeSet addAttribute (LLVMContext &C, unsigned Index, StringRef Kind) const
Add an attribute to the attribute set at the given index. Since attribute sets are immutable, this returns a new set.
AttributeSet addAttribute (LLVMContext &C, unsigned Index, StringRef Kind, StringRef Value) const
AttributeSet addAttributes (LLVMContext &C, unsigned Index, AttributeSet Attrs) const
Add attributes to the attribute set at the given index. Since attribute sets are immutable, this returns a new set.
AttributeSet removeAttribute (LLVMContext &C, unsigned Index, Attribute::AttrKind Attr) const
Remove the specified attribute at the specified index from this attribute list. Since attribute lists are immutable, this returns the new list.
AttributeSet removeAttributes (LLVMContext &C, unsigned Index, AttributeSet Attrs) const
Remove the specified attributes at the specified index from this attribute list. Since attribute lists are immutable, this returns the new list.
LLVMContext & getContext () const
Retrieve the LLVM context.
AttributeSet getParamAttributes (unsigned Index) const
The attributes for the specified index are returned.
AttributeSet getRetAttributes () const
The attributes for the ret value are returned.
AttributeSet getFnAttributes () const
The function attributes are returned.
bool hasAttribute (unsigned Index, Attribute::AttrKind Kind) const
Return true if the attribute exists at the given index.
bool hasAttribute (unsigned Index, StringRef Kind) const
Return true if the attribute exists at the given index.
bool hasAttributes (unsigned Index) const
Return true if attribute exists at the given index.
bool hasAttrSomewhere (Attribute::AttrKind Attr) const
Return true if the specified attribute is set for at least one parameter or for the return value.
Attribute getAttribute (unsigned Index, Attribute::AttrKind Kind) const
Return the attribute object that exists at the given index.
Attribute getAttribute (unsigned Index, StringRef Kind) const
Return the attribute object that exists at the given index.
unsigned getParamAlignment (unsigned Index) const
Return the alignment for the specified function parameter.
unsigned getStackAlignment (unsigned Index) const
Get the stack alignment.
uint64_t getDereferenceableBytes (unsigned Index) const
Get the number of dereferenceable bytes (or zero if unknown).
std::string getAsString (unsigned Index, bool InAttrGrp=false) const
Return the attributes at the index as a string.
iterator begin (unsigned Slot) const
iterator end (unsigned Slot) const
bool operator== (const AttributeSet &RHS) const
operator==/!= - Provide equality predicates.
bool operator!= (const AttributeSet &RHS) const
uint64_t Raw (unsigned Index) const
void * getRawPointer () const
Return a raw pointer that uniquely identifies this attribute list.
bool isEmpty () const
Return true if there are no attributes.
unsigned getNumSlots () const
Return the number of slots used in this attribute list. This is the number of arguments that have an attribute set on them (including the function itself).
unsigned getSlotIndex (unsigned Slot) const
Return the index for the given slot.
AttributeSet getSlotAttributes (unsigned Slot) const
Return the attributes at the given slot.
void dump () const
Static Public Member Functions
static AttributeSet get (LLVMContext &C, ArrayRef< AttributeSet > Attrs)
Return an AttributeSet with the specified parameters in it.
static AttributeSet get (LLVMContext &C, unsigned Index, ArrayRef< Attribute::AttrKind > Kind)
static AttributeSet get (LLVMContext &C, unsigned Index, const AttrBuilder &B)
Friends
class AttrBuilder
class AttributeSetImpl
template<typename Ty>
struct DenseMapInfo
Detailed Description
This class holds the attributes for a function, its return value, and its parameters. You access the attributes for each of them via an index into the AttributeSet object. The function attributes are at index ‘AttributeSet::FunctionIndex’, the return value is at index / ‘AttributeSet::ReturnIndex’, and the attributes for the parameters start at index ‘1’.
Definition at line 212 of file Attributes.h.
Member Typedef Documentation
iterator
typedef ArrayRef<Attribute>::iterator llvm::AttributeSet::iterator
Definition at line 332 of file Attributes.h.
Member Enumeration Documentation
AttrIndex
enum llvm::AttributeSet::AttrIndex : unsigned
Enumerator
ReturnIndex
FunctionIndex
Definition at line 214 of file Attributes.h.
Constructor & Destructor Documentation
AttributeSet()
llvm::AttributeSet::AttributeSet () inline
Definition at line 244 of file Attributes.h.
Referenced by get(), get(), getFnAttributes(), getParamAttributes(), getRetAttributes(), and removeAttributes().
Member Function Documentation
addAttribute() [1/3]
AttributeSet AttributeSet::addAttribute (LLVMContext & C, unsigned Index, Attribute::AttrKind Attr) const
Add an attribute to the attribute set at the given index. Since attribute sets are immutable, this returns a new set.
Definition at line 718 of file Attributes.cpp.
References addAttributes(), and hasAttribute().
Referenced by llvm::CallInst::addAttribute(), llvm::Function::addAttribute(), and llvm::InvokeInst::addAttribute().
addAttribute() [2/3]
AttributeSet AttributeSet::addAttribute (LLVMContext & C, unsigned Index, StringRef Kind) const
Add an attribute to the attribute set at the given index. Since attribute sets are immutable, this returns a new set.
Definition at line 724 of file Attributes.cpp.
References llvm::AttrBuilder::addAttribute(), and addAttributes().
addAttribute() [3/3]
AttributeSet AttributeSet::addAttribute (LLVMContext & C, unsigned Index, StringRef Kind, StringRef Value) const
Definition at line 731 of file Attributes.cpp.
References llvm::AttrBuilder::addAttribute(), and addAttributes().
addAttributes()
AttributeSet AttributeSet::addAttributes (LLVMContext & C, unsigned Index, AttributeSet Attrs) const
Add attributes to the attribute set at the given index. Since attribute sets are immutable, this returns a new set.
Definition at line 738 of file Attributes.cpp.
References llvm::AttrBuilder::addAttribute(), AttrBuilder, llvm::AttributeSetImpl::begin(), llvm::AttributeSetImpl::end(), llvm::AttributeSetImpl::getNumAttributes(), getParamAlignment(), getSlotAttributes(), getSlotIndex(), I, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by addAttribute(), addAttribute(), addAttribute(), llvm::Function::addAttributes(), llvm::CloneFunctionInto(), and LLVMAddFunctionAttr().
begin()
AttributeSet::iterator AttributeSet::begin (unsigned Slot) const
Definition at line 946 of file Attributes.cpp.
References llvm::ArrayRef< T >::begin().
Referenced by llvm::AssemblyWriter::printFunction(), and WriteAttributeGroupTable().
dump()
void AttributeSet::dump () const
Definition at line 986 of file Attributes.cpp.
References llvm::dbgs(), getAsString(), getNumSlots(), and getSlotIndex().
end()
AttributeSet::iterator AttributeSet::end (unsigned Slot) const
Definition at line 952 of file Attributes.cpp.
References llvm::ArrayRef< T >::end().
Referenced by llvm::AssemblyWriter::printFunction(), and WriteAttributeGroupTable().
get() [1/3]
AttributeSet AttributeSet::get (LLVMContext & C, ArrayRef< AttributeSet > Attrs) static
Return an AttributeSet with the specified parameters in it.
Definition at line 687 of file Attributes.cpp.
References llvm::SmallVectorImpl< T >::append(), AttributeSet(), AttributeSetImpl, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ArrayRef< T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::AttributeSetImpl::getNumAttributes(), I, llvm::SmallVectorImpl< T >::insert(), and llvm::ArrayRef< T >::size().
get() [2/3]
AttributeSet AttributeSet::get (LLVMContext & C, unsigned Index, ArrayRef< Attribute::AttrKind > Kind) static
Definition at line 678 of file Attributes.cpp.
References llvm::Attribute::get(), I, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
get() [3/3]
AttributeSet AttributeSet::get (LLVMContext & C, unsigned Index, const AttrBuilder & B) static
Definition at line 644 of file Attributes.cpp.
References llvm::Attribute::Alignment, AttrBuilder, AttributeSet(), llvm::AttrBuilder::contains(), llvm::Attribute::Dereferenceable, llvm::Attribute::EndAttrKinds, llvm::Attribute::get(), llvm::AttrBuilder::getAlignment(), llvm::AttrBuilder::getDereferenceableBytes(), llvm::AttrBuilder::getStackAlignment(), llvm::Attribute::getWithDereferenceableBytes(), llvm::AttrBuilder::hasAttributes(), llvm::Attribute::None, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::Attribute::StackAlignment, and llvm::AttrBuilder::td_attrs().
getAsString()
std::string AttributeSet::getAsString (unsigned Index, bool InAttrGrp = false) const
Return the attributes at the index as a string.
Definition at line 928 of file Attributes.cpp.
References llvm::AttributeSetNode::getAsString().
Referenced by dump(), llvm::AssemblyWriter::printArgument(), llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printInstruction(), and llvm::AssemblyWriter::writeParamOperand().
getAttribute() [1/2]
Attribute AttributeSet::getAttribute (unsigned Index, Attribute::AttrKind Kind) const
Return the attribute object that exists at the given index.
Definition at line 901 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttribute().
Referenced by llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), and llvm::StackProtector::runOnFunction().
getAttribute() [2/2]
Attribute AttributeSet::getAttribute (unsigned Index, StringRef Kind) const
Return the attribute object that exists at the given index.
Definition at line 907 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttribute().
getContext()
LLVMContext & AttributeSet::getContext () const
Retrieve the LLVM context.
Definition at line 842 of file Attributes.cpp.
getDereferenceableBytes()
uint64_t AttributeSet::getDereferenceableBytes (unsigned Index) const
Get the number of dereferenceable bytes (or zero if unknown).
Definition at line 923 of file Attributes.cpp.
References llvm::AttributeSetNode::getDereferenceableBytes().
getFnAttributes()
AttributeSet AttributeSet::getFnAttributes () const
The function attributes are returned.
Definition at line 863 of file Attributes.cpp.
References AttributeSet(), FunctionIndex, and hasAttributes().
Referenced by llvm::CloneFunctionInto(), llvm::AssemblyWriter::printFunction(), and llvm::AssemblyWriter::printInstruction().
getNumSlots()
unsigned AttributeSet::getNumSlots () const
Return the number of slots used in this attribute list. This is the number of arguments that have an attribute set on them (including the function itself).
Definition at line 965 of file Attributes.cpp.
Referenced by llvm::Argument::addAttr(), llvm::CloneFunctionInto(), dump(), isEmpty(), llvm::AssemblyWriter::printFunction(), llvm::Argument::removeAttr(), StripNest(), and WriteAttributeGroupTable().
getParamAlignment()
unsigned AttributeSet::getParamAlignment (unsigned Index) const
Return the alignment for the specified function parameter.
Definition at line 913 of file Attributes.cpp.
References llvm::AttributeSetNode::getAlignment().
Referenced by addAttributes(), and getParameterABIAttributes().
getParamAttributes()
AttributeSet AttributeSet::getParamAttributes (unsigned Index) const
The attributes for the specified index are returned.
Definition at line 846 of file Attributes.cpp.
References AttributeSet(), and hasAttributes().
Referenced by llvm::CloneFunctionInto().
getRawPointer()
void * llvm::AttributeSet::getRawPointer () const inline
Return a raw pointer that uniquely identifies this attribute list.
Definition at line 353 of file Attributes.h.
getRetAttributes()
AttributeSet AttributeSet::getRetAttributes () const
The attributes for the ret value are returned.
Definition at line 854 of file Attributes.cpp.
References AttributeSet(), hasAttributes(), and ReturnIndex.
Referenced by llvm::CloneFunctionInto().
getSlotAttributes()
AttributeSet AttributeSet::getSlotAttributes (unsigned Slot) const
Return the attributes at the given slot.
Definition at line 975 of file Attributes.cpp.
Referenced by addAttributes(), removeAttributes(), StripNest(), and WriteAttributeGroupTable().
getSlotIndex()
unsigned AttributeSet::getSlotIndex (unsigned Slot) const
Return the index for the given slot.
Definition at line 969 of file Attributes.cpp.
Referenced by llvm::Argument::addAttr(), addAttributes(), dump(), llvm::AssemblyWriter::printFunction(), llvm::Argument::removeAttr(), removeAttributes(), StripNest(), and WriteAttributeGroupTable().
getStackAlignment()
unsigned AttributeSet::getStackAlignment (unsigned Index) const
Get the stack alignment.
Definition at line 918 of file Attributes.cpp.
References llvm::AttributeSetNode::getStackAlignment().
hasAttribute() [1/2]
bool AttributeSet::hasAttribute (unsigned Index, Attribute::AttrKind Kind) const
Return true if the attribute exists at the given index.
Definition at line 872 of file Attributes.cpp.
References llvm::AttributeSetNode::hasAttribute().
Referenced by addAttribute(), AdjustCallerSSPLevel(), llvm::AArch64FrameLowering::canUseRedZone(), checkNumAlignedDPRCS2Regs(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), llvm::X86FrameLowering::emitPrologue(), llvm::Inliner::getInlineThreshold(), getParameterABIAttributes(), llvm::GetReturnInfo(), llvm::Argument::hasByValOrInAllocaAttr(), llvm::TargetLowering::isInTailCallPosition(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::PPCFrameLowering::needsFP(), performSTORECombine(), removeAttribute(), removeAttributes(), StripNest(), llvm::tryFoldSPUpdateIntoPushPop(), and llvm::ARMSubtarget::useMovt().
hasAttribute() [2/2]
bool AttributeSet::hasAttribute (unsigned Index, StringRef Kind) const
Return true if the attribute exists at the given index.
Definition at line 877 of file Attributes.cpp.
References llvm::AttributeSetNode::hasAttribute().
hasAttributes()
bool AttributeSet::hasAttributes (unsigned Index) const
Return true if attribute exists at the given index.
Definition at line 882 of file Attributes.cpp.
References llvm::AttributeSetNode::hasAttributes().
Referenced by getFnAttributes(), getParamAttributes(), getRetAttributes(), llvm::AssemblyWriter::printArgument(), llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printInstruction(), and llvm::AssemblyWriter::writeParamOperand().
hasAttrSomewhere()
bool AttributeSet::hasAttrSomewhere (Attribute::AttrKind Attr) const
Return true if the specified attribute is set for at least one parameter or for the return value.
Definition at line 889 of file Attributes.cpp.
References I.
Referenced by llvm::XCoreFrameLowering::emitPrologue().
isEmpty()
bool llvm::AttributeSet::isEmpty () const inline
Return true if there are no attributes.
Definition at line 358 of file Attributes.h.
References getNumSlots().
Referenced by llvm::ValueEnumerator::getAttributeGroupID(), and llvm::ValueEnumerator::getAttributeID().
operator!=()
bool llvm::AttributeSet::operator!= (const AttributeSet & RHS) const inline
Definition at line 341 of file Attributes.h.
operator==()
bool llvm::AttributeSet::operator== (const AttributeSet & RHS) const inline
operator==/!= - Provide equality predicates.
Definition at line 338 of file Attributes.h.
Raw()
uint64_t AttributeSet::Raw (unsigned Index) const
Definition at line 981 of file Attributes.cpp.
Referenced by LLVMGetFunctionAttr().
removeAttribute()
AttributeSet AttributeSet::removeAttribute (LLVMContext & C, unsigned Index, Attribute::AttrKind Attr) const
Remove the specified attribute at the specified index from this attribute list. Since attribute lists are immutable, this returns the new list.
Definition at line 787 of file Attributes.cpp.
References hasAttribute(), and removeAttributes().
Referenced by StripNest().
removeAttributes()
AttributeSet AttributeSet::removeAttributes (LLVMContext & C, unsigned Index, AttributeSet Attrs) const
Remove the specified attributes at the specified index from this attribute list. Since attribute lists are immutable, this returns the new list.
Definition at line 793 of file Attributes.cpp.
References llvm::Attribute::Alignment, AttrBuilder, AttributeSet(), llvm::AttributeSetImpl::getNumAttributes(), getSlotAttributes(), llvm::AttributeSetImpl::getSlotAttributes(), getSlotIndex(), hasAttribute(), I, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::AttrBuilder::removeAttributes().
Referenced by LLVMRemoveFunctionAttr(), removeAttribute(), llvm::CallInst::removeAttribute(), llvm::InvokeInst::removeAttribute(), and llvm::Function::removeAttributes().
Friends And Related Symbol Documentation
AttrBuilder
friend class AttrBuilder friend
Definition at line 219 of file Attributes.h.
References AttrBuilder.
Referenced by addAttributes(), AttrBuilder, get(), and removeAttributes().
AttributeSetImpl
friend class AttributeSetImpl friend
Definition at line 220 of file Attributes.h.
References AttributeSetImpl.
Referenced by AttributeSetImpl, DenseMapInfo, and get().
DenseMapInfo
template<typename Ty> friend struct DenseMapInfo friend
Definition at line 221 of file Attributes.h.
References AttributeSetImpl, and DenseMapInfo.
Referenced by DenseMapInfo.
The documentation for this class was generated from the following files:
Attributes.h
Attributes.cpp