LLVM: llvm::opt::OptSpecifier Class Reference
LLVM API Documentation
llvm::opt::OptSpecifier Class Reference
OptSpecifier - Wrapper class for abstracting references to option IDs.
#include <OptSpecifier.h>
Public Member Functions
OptSpecifier ()
OptSpecifier (unsigned _ID)
OptSpecifier (const Option *Opt)
bool isValid () const
unsigned getID () const
bool operator== (OptSpecifier Opt) const
bool operator!= (OptSpecifier Opt) const
Detailed Description
OptSpecifier - Wrapper class for abstracting references to option IDs.
Definition at line 20 of file OptSpecifier.h.
Constructor & Destructor Documentation
OptSpecifier() [1/3]
llvm::opt::OptSpecifier::OptSpecifier () inline
Definition at line 27 of file OptSpecifier.h.
OptSpecifier() [2/3]
llvm::opt::OptSpecifier::OptSpecifier (unsigned _ID) inline
Definition at line 28 of file OptSpecifier.h.
OptSpecifier() [3/3]
OptSpecifier::OptSpecifier (const Option * Opt)
Definition at line 85 of file OptTable.cpp.
References getID().
Member Function Documentation
getID()
unsigned llvm::opt::OptSpecifier::getID () const inline
Definition at line 33 of file OptSpecifier.h.
Referenced by llvm::opt::OptTable::getOption(), llvm::opt::Option::matches(), operator==(), and OptSpecifier().
isValid()
bool llvm::opt::OptSpecifier::isValid () const inline
Definition at line 31 of file OptSpecifier.h.
operator!=()
bool llvm::opt::OptSpecifier::operator!= (OptSpecifier Opt) const inline
Definition at line 36 of file OptSpecifier.h.
operator==()
bool llvm::opt::OptSpecifier::operator== (OptSpecifier Opt) const inline
Definition at line 35 of file OptSpecifier.h.
References getID().
The documentation for this class was generated from the following files:
OptSpecifier.h
OptTable.cpp