LLVM: llvm::object::ELFFile< ELFT >::Elf_Sym_Iter Class Reference
LLVM API Documentation
llvm::object::ELFFile< ELFT >::Elf_Sym_Iter Class Reference
#include <ELF.h>
Public Types
typedef ptrdiff_t difference_type
typedef const Elf_Sym value_type
typedef std::random_access_iterator_tag iterator_category
typedef value_type & reference
typedef value_type * pointer
Public Member Functions
Elf_Sym_Iter ()
Default construct iterator.
Elf_Sym_Iter (uintX_t EntSize, const char *Start, bool IsDynamic)
reference operator* ()
pointer operator-> ()
bool operator== (const Elf_Sym_Iter &Other)
bool operator!= (const Elf_Sym_Iter &Other)
Elf_Sym_Iter & operator++ ()
Elf_Sym_Iter operator++ (int)
Elf_Sym_Iter operator+ (difference_type Dist)
Elf_Sym_Iter & operator= (const Elf_Sym_Iter &Other)
difference_type operator- (const Elf_Sym_Iter &Other) const
const char * get () const
bool isDynamic () const
uintX_t getEntSize () const
Detailed Description
template<class ELFT>
class llvm::object::ELFFile< ELFT >::Elf_Sym_Iter
Definition at line 155 of file Object/ELF.h.
Member Typedef Documentation
difference_type
template<class ELFT> typedef ptrdiff_t llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::difference_type
Definition at line 157 of file Object/ELF.h.
iterator_category
template<class ELFT> typedef std::random_access_iterator_tag llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::iterator_category
Definition at line 159 of file Object/ELF.h.
pointer
template<class ELFT> typedef value_type* llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::pointer
Definition at line 161 of file Object/ELF.h.
reference
template<class ELFT> typedef value_type& llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::reference
Definition at line 160 of file Object/ELF.h.
value_type
template<class ELFT> typedef const Elf_Sym llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::value_type
Definition at line 158 of file Object/ELF.h.
Constructor & Destructor Documentation
Elf_Sym_Iter() [1/2]
template<class ELFT> llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::Elf_Sym_Iter () inline
Default construct iterator.
Definition at line 164 of file Object/ELF.h.
Referenced by operator!=(), operator+(), operator++(), operator++(), operator-(), operator=(), and operator==().
Elf_Sym_Iter() [2/2]
template<class ELFT> llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::Elf_Sym_Iter (uintX_t EntSize, const char * Start, bool IsDynamic) inline
Definition at line 165 of file Object/ELF.h.
Member Function Documentation
get()
template<class ELFT> const char * llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::get () const inline
Definition at line 218 of file Object/ELF.h.
Referenced by llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >::toDRI().
getEntSize()
template<class ELFT> uintX_t llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::getEntSize () const inline
Definition at line 222 of file Object/ELF.h.
isDynamic()
template<class ELFT> bool llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::isDynamic () const inline
Definition at line 220 of file Object/ELF.h.
Referenced by llvm::object::ELFFile< ELFT >::getSymbolName(), and llvm::object::ELFObjectFile< ELFType< support::little, 2, false > >::toDRI().
operator!=()
template<class ELFT> bool llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator!= (const Elf_Sym_Iter & Other) inline
Definition at line 184 of file Object/ELF.h.
References Elf_Sym_Iter().
operator*()
template<class ELFT> reference llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator* () inline
Definition at line 168 of file Object/ELF.h.
operator+()
template<class ELFT> Elf_Sym_Iter llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator+ (difference_type Dist) inline
Definition at line 199 of file Object/ELF.h.
References Elf_Sym_Iter().
operator++() [1/2]
template<class ELFT> Elf_Sym_Iter & llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator++ () inline
Definition at line 186 of file Object/ELF.h.
References Elf_Sym_Iter().
operator++() [2/2]
template<class ELFT> Elf_Sym_Iter llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator++ (int) inline
Definition at line 193 of file Object/ELF.h.
References Elf_Sym_Iter().
operator-()
template<class ELFT> difference_type llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator- (const Elf_Sym_Iter & Other) const inline
Definition at line 212 of file Object/ELF.h.
References Elf_Sym_Iter().
operator->()
template<class ELFT> pointer llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator-> () inline
Definition at line 174 of file Object/ELF.h.
operator=()
template<class ELFT> Elf_Sym_Iter & llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator= (const Elf_Sym_Iter & Other) inline
Definition at line 206 of file Object/ELF.h.
References Elf_Sym_Iter().
operator==()
template<class ELFT> bool llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::operator== (const Elf_Sym_Iter & Other) inline
Definition at line 180 of file Object/ELF.h.
References Elf_Sym_Iter().
The documentation for this class was generated from the following file:
Object/ELF.h