LLVM: llvm::BlockFrequency Class Reference
LLVM API Documentation
llvm::BlockFrequency Class Reference
#include <BlockFrequency.h>
Public Member Functions
BlockFrequency (uint64_t Freq=0)
uint64_t getFrequency () const
Returns the frequency as a fixpoint number scaled by the entry frequency.
BlockFrequency & operator*= (const BranchProbability &Prob)
Multiplies with a branch probability. The computation will never overflow.
const BlockFrequency operator* (const BranchProbability &Prob) const
BlockFrequency & operator/= (const BranchProbability &Prob)
Divide by a non-zero branch probability using saturating arithmetic.
BlockFrequency operator/ (const BranchProbability &Prob) const
BlockFrequency & operator+= (const BlockFrequency &Freq)
Adds another block frequency using saturating arithmetic.
const BlockFrequency operator+ (const BlockFrequency &Freq) const
BlockFrequency & operator>>= (const unsigned count)
Shift block frequency to the right by count digits saturating to 1.
bool operator< (const BlockFrequency &RHS) const
bool operator<= (const BlockFrequency &RHS) const
bool operator> (const BlockFrequency &RHS) const
bool operator>= (const BlockFrequency &RHS) const
Static Public Member Functions
static uint64_t getMaxFrequency ()
Returns the maximum possible frequency, the saturation value.
Detailed Description
Definition at line 25 of file BlockFrequency.h.
Constructor & Destructor Documentation
BlockFrequency()
llvm::BlockFrequency::BlockFrequency (uint64_t Freq = 0) inline
Definition at line 29 of file BlockFrequency.h.
Referenced by operator*(), operator*=(), operator+(), operator+=(), operator/(), operator/=(), operator<(), operator<=(), operator>(), operator>=(), and operator>>=().
Member Function Documentation
getFrequency()
uint64_t llvm::BlockFrequency::getFrequency () const inline
Returns the frequency as a fixpoint number scaled by the entry frequency.
Definition at line 36 of file BlockFrequency.h.
Referenced by llvm::DOTGraphTraits< BlockFrequencyInfo * >::getNodeLabel(), llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getNodeLabel(), llvm::LiveIntervals::getSpillWeight(), and llvm::BlockFrequencyInfoImplBase::printBlockFreq().
getMaxFrequency()
uint64_t llvm::BlockFrequency::getMaxFrequency () inline static
Returns the maximum possible frequency, the saturation value.
Definition at line 32 of file BlockFrequency.h.
Referenced by llvm::SpillPlacement::Node::addBias().
operator*()
const BlockFrequency BlockFrequency::operator* (const BranchProbability & Prob) const
Definition at line 27 of file BlockFrequency.cpp.
References BlockFrequency().
operator*=()
BlockFrequency & BlockFrequency::operator*= (const BranchProbability & Prob)
Multiplies with a branch probability. The computation will never overflow.
Definition at line 21 of file BlockFrequency.cpp.
References BlockFrequency(), and llvm::BranchProbability::scale().
operator+()
const BlockFrequency BlockFrequency::operator+ (const BlockFrequency & Freq) const
Definition at line 56 of file BlockFrequency.cpp.
References BlockFrequency().
operator+=()
BlockFrequency & BlockFrequency::operator+= (const BlockFrequency & Freq)
Adds another block frequency using saturating arithmetic.
Definition at line 44 of file BlockFrequency.cpp.
References BlockFrequency().
operator/()
BlockFrequency BlockFrequency::operator/ (const BranchProbability & Prob) const
Definition at line 38 of file BlockFrequency.cpp.
References BlockFrequency().
operator/=()
BlockFrequency & BlockFrequency::operator/= (const BranchProbability & Prob)
Divide by a non-zero branch probability using saturating arithmetic.
Definition at line 33 of file BlockFrequency.cpp.
References BlockFrequency(), and llvm::BranchProbability::scaleByInverse().
operator<()
bool llvm::BlockFrequency::operator< (const BlockFrequency & RHS) const inline
Definition at line 55 of file BlockFrequency.h.
References BlockFrequency().
operator<=()
bool llvm::BlockFrequency::operator<= (const BlockFrequency & RHS) const inline
Definition at line 59 of file BlockFrequency.h.
References BlockFrequency().
operator>()
bool llvm::BlockFrequency::operator> (const BlockFrequency & RHS) const inline
Definition at line 63 of file BlockFrequency.h.
References BlockFrequency().
operator>=()
bool llvm::BlockFrequency::operator>= (const BlockFrequency & RHS) const inline
Definition at line 67 of file BlockFrequency.h.
References BlockFrequency().
operator>>=()
BlockFrequency & BlockFrequency::operator>>= (const unsigned count)
Shift block frequency to the right by count digits saturating to 1.
Definition at line 62 of file BlockFrequency.cpp.
References BlockFrequency().
The documentation for this class was generated from the following files:
BlockFrequency.h
BlockFrequency.cpp