LLVM: llvm::RawInstrProfReader< IntPtrT > Class Template Reference
LLVM API Documentation
llvm::RawInstrProfReader< IntPtrT > Class Template Reference
#include <InstrProfReader.h>
Public Member Functions
RawInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer)
std::error_code readHeader () override
Read the header. Required before reading first record.
std::error_code readNextRecord (InstrProfRecord &Record) override
Read a single record.
Public Member Functions inherited from llvm::InstrProfReader
InstrProfReader ()
virtual ~InstrProfReader ()
InstrProfIterator begin ()
Iterator over profile data.
InstrProfIterator end ()
bool isEOF ()
Return true if the reader has finished reading the profile data.
bool hasError ()
Return true if the reader encountered an error reading profiling data.
std::error_code getError ()
Get the current error code.
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &DataBuffer)
Static Public Member Functions inherited from llvm::InstrProfReader
static ErrorOr< std::unique_ptr< InstrProfReader > > create (std::string Path)
Additional Inherited Members
Protected Member Functions inherited from llvm::InstrProfReader
std::error_code error (std::error_code EC)
Set the current std::error_code and return same.
std::error_code success ()
Clear the current error code and return a successful one.
Detailed Description
template<class IntPtrT>
class llvm::RawInstrProfReader< IntPtrT >
Reader for the raw instrprof binary format from runtime.
This format is a raw memory dump of the instrumentation-baed profiling data from the runtime. It has no index.
Templated on the unsigned type whose size matches pointers on the platform that wrote the profile.
Definition at line 138 of file InstrProfReader.h.
Constructor & Destructor Documentation
RawInstrProfReader()
template<class IntPtrT> llvm::RawInstrProfReader< IntPtrT >::RawInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer) inline
Definition at line 174 of file InstrProfReader.h.
Member Function Documentation
hasFormat()
template<class IntPtrT> bool RawInstrProfReader::hasFormat (const MemoryBuffer & DataBuffer) static
Definition at line 162 of file InstrProfReader.cpp.
References getRawMagic(), llvm::sys::getSwappedBytes(), and Magic.
Referenced by readHeader().
readHeader()
template<class IntPtrT> std::error_code RawInstrProfReader::readHeader () override virtual
Read the header. Required before reading first record.
Implements llvm::InstrProfReader.
Definition at line 172 of file InstrProfReader.cpp.
References llvm::bad_header, llvm::bad_magic, llvm::InstrProfReader::error(), getRawMagic(), hasFormat(), and readHeader().
Referenced by readHeader().
readNextRecord()
template<class IntPtrT> std::error_code RawInstrProfReader::readNextRecord (InstrProfRecord & Record) override virtual
Read a single record.
Implements llvm::InstrProfReader.
Definition at line 246 of file InstrProfReader.cpp.
References llvm::StringRef::data(), llvm::InstrProfReader::error(), getName(), llvm::makeArrayRef(), llvm::malformed, llvm::StringRef::size(), and llvm::object::success.
The documentation for this class was generated from the following files:
InstrProfReader.h
InstrProfReader.cpp