LLVM: llvm::LiveIntervalUnion::Query Class Reference
LLVM API Documentation
llvm::LiveIntervalUnion::Query Class Reference
#include <LiveIntervalUnion.h>
Public Member Functions
Query ()
Query (LiveInterval *VReg, LiveIntervalUnion *LIU)
void clear ()
void init (unsigned UTag, LiveInterval *VReg, LiveIntervalUnion *LIU)
LiveInterval & virtReg () const
bool checkInterference ()
unsigned collectInterferingVRegs (unsigned MaxInterferingRegs=UINT_MAX)
bool isSeenInterference (LiveInterval *VReg) const
NDEBUG.
bool seenAllInterferences () const
bool seenUnspillableVReg () const
const SmallVectorImpl< LiveInterval * > & interferingVRegs () const
Detailed Description
Query interferences between a single live virtual register and a live interval union.
Definition at line 111 of file LiveIntervalUnion.h.
Constructor & Destructor Documentation
Query() [1/2]
llvm::LiveIntervalUnion::Query::Query () inline
Definition at line 123 of file LiveIntervalUnion.h.
Query() [2/2]
llvm::LiveIntervalUnion::Query::Query (LiveInterval * VReg, LiveIntervalUnion * LIU) inline
Definition at line 125 of file LiveIntervalUnion.h.
References llvm::LiveIntervalUnion::LiveIntervalUnion().
Member Function Documentation
checkInterference()
bool llvm::LiveIntervalUnion::Query::checkInterference () inline
Definition at line 161 of file LiveIntervalUnion.h.
References collectInterferingVRegs().
clear()
void llvm::LiveIntervalUnion::Query::clear () inline
Definition at line 130 of file LiveIntervalUnion.h.
Referenced by init().
collectInterferingVRegs()
unsigned LiveIntervalUnion::Query::collectInterferingVRegs (unsigned MaxInterferingRegs = UINT_MAX)
Definition at line 119 of file LiveIntervalUnion.cpp.
References isSeenInterference(), and llvm::LiveRange::size().
Referenced by checkInterference().
init()
void llvm::LiveIntervalUnion::Query::init (unsigned UTag, LiveInterval * VReg, LiveIntervalUnion * LIU) inline
Definition at line 141 of file LiveIntervalUnion.h.
References llvm::LiveIntervalUnion::changedSince(), clear(), llvm::LiveIntervalUnion::getTag(), and llvm::LiveIntervalUnion::LiveIntervalUnion().
Referenced by llvm::LiveRegMatrix::query().
interferingVRegs()
const SmallVectorImpl< LiveInterval * > & llvm::LiveIntervalUnion::Query::interferingVRegs () const inline
Definition at line 177 of file LiveIntervalUnion.h.
isSeenInterference()
bool LiveIntervalUnion::Query::isSeenInterference (LiveInterval * VReg) const
NDEBUG.
Definition at line 104 of file LiveIntervalUnion.cpp.
References I.
Referenced by collectInterferingVRegs().
seenAllInterferences()
bool llvm::LiveIntervalUnion::Query::seenAllInterferences () const inline
Definition at line 171 of file LiveIntervalUnion.h.
seenUnspillableVReg()
bool llvm::LiveIntervalUnion::Query::seenUnspillableVReg () const inline
Definition at line 174 of file LiveIntervalUnion.h.
virtReg()
LiveInterval & llvm::LiveIntervalUnion::Query::virtReg () const inline
Definition at line 155 of file LiveIntervalUnion.h.
The documentation for this class was generated from the following files:
LiveIntervalUnion.h
LiveIntervalUnion.cpp