LLVM: llvm::MipsSETargetLowering Class Reference
LLVM API Documentation
llvm::MipsSETargetLowering Class Reference
#include <MipsSEISelLowering.h>
Public Member Functions
MipsSETargetLowering (const MipsTargetMachine &TM, const MipsSubtarget &STI)
void addMSAIntType (MVT::SimpleValueType Ty, const TargetRegisterClass *RC)
Enable MSA support for the given integer type and Register class.
void addMSAFloatType (MVT::SimpleValueType Ty, const TargetRegisterClass *RC)
Enable MSA support for the given floating-point type and Register class.
bool allowsMisalignedMemoryAccesses (EVT VT, unsigned AS=0, unsigned Align=1, bool *Fast=nullptr) const override
Determine if the target supports unaligned memory accesses.
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *MBB) const override
bool isShuffleMaskLegal (const SmallVectorImpl< int > &Mask, EVT VT) const override
const TargetRegisterClass * getRepRegClassFor (MVT VT) const override
Public Member Functions inherited from llvm::MipsTargetLowering
MipsTargetLowering (const MipsTargetMachine &TM, const MipsSubtarget &STI)
FastISel * createFastISel (FunctionLoweringInfo &funcInfo, const TargetLibraryInfo *libInfo) const override
MVT getScalarShiftAmountTy (EVT LHSTy) const override
void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
LowerOperation - Provide custom lowering hooks for some operations.
void ReplaceNodeResults (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
const char * getTargetNodeName (unsigned Opcode) const override
getTargetNodeName - This method returns the name of a target specific
EVT getSetCCResultType (LLVMContext &Context, EVT VT) const override
getSetCCResultType - get the ISD::SETCC result ValueType
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *MBB) const override
void HandleByVal (CCState *, unsigned &, unsigned) const override
Target-specific cleanup for formal ByVal parameters.
unsigned getRegisterByName (const char *RegName, EVT VT) const override
Public Member Functions inherited from llvm::TargetLowering
TargetLowering (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
virtual bool getPreIndexedAddressParts (SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
virtual bool getPostIndexedAddressParts (SDNode *, SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
virtual const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *, const MachineBasicBlock *, unsigned, MCContext &) const
virtual SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const
Returns relocation base for the given PIC jumptable.
virtual const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const
bool isInTailCallPosition (SelectionDAG &DAG, SDNode *Node, SDValue &Chain) const
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, SDLoc DL) const
std::pair< SDValue, SDValue > makeLibCall (SelectionDAG &DAG, RTLIB::Libcall LC, EVT RetVT, const SDValue *Ops, unsigned NumOps, bool isSigned, SDLoc dl, bool doesNotReturn=false, bool isReturnValueUsed=true) const
Returns a pair of (return value, chain).
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedMask, APInt &KnownZero, APInt &KnownOne, TargetLoweringOpt &TLO, unsigned Depth=0) const
virtual void computeKnownBitsForTargetNode (const SDValue Op, APInt &KnownZero, APInt &KnownOne, const SelectionDAG &DAG, unsigned Depth=0) const
virtual unsigned ComputeNumSignBitsForTargetNode (SDValue Op, const SelectionDAG &DAG, unsigned Depth=0) const
bool isConstTrueVal (const SDNode *N) const
bool isConstFalseVal (const SDNode *N) const
SDValue SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo &DCI, SDLoc dl) const
virtual bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const
virtual bool isDesirableToCommuteWithShift (const SDNode *N) const
Return true if it is profitable to move a following shift through this.
virtual bool isTypeDesirableForOp (unsigned, EVT VT) const
virtual bool isDesirableToTransformToIntegerOp (unsigned, EVT) const
virtual bool IsDesirableToPromoteOp (SDValue, EVT &) const
std::pair< SDValue, SDValue > LowerCallTo (CallLoweringInfo &CLI) const
virtual bool isUsedByReturnOnly (SDNode *, SDValue &) const
virtual bool mayBeEmittedAsTailCall (CallInst *) const
virtual const char * getClearCacheBuiltinName () const
virtual EVT getTypeForExtArgOrReturn (LLVMContext &Context, EVT VT, ISD::NodeType) const
virtual bool functionArgumentNeedsConsecutiveRegisters (Type *Ty, CallingConv::ID CallConv, bool isVarArg) const
virtual const MCPhysReg * getScratchRegisters (CallingConv::ID CC) const
virtual SDValue prepareVolatileOrAtomicLoad (SDValue Chain, SDLoc DL, SelectionDAG &DAG) const
bool verifyReturnAddressArgumentIsConstant (SDValue Op, SelectionDAG &DAG) const
virtual bool ExpandInlineAsm (CallInst *) const
virtual AsmOperandInfoVector ParseConstraints (ImmutableCallSite CS) const
virtual ConstraintWeight getMultipleConstraintMatchWeight (AsmOperandInfo &info, int maIndex) const
virtual void ComputeConstraintToUse (AsmOperandInfo &OpInfo, SDValue Op, SelectionDAG *DAG=nullptr) const
virtual const char * LowerXConstraint (EVT ConstraintVT) const
SDValue BuildExactSDIV (SDValue Op1, SDValue Op2, SDLoc dl, SelectionDAG &DAG) const
Given an exact SDIV by a constant, create a multiplication with the multiplicative inverse of the constant.
SDValue BuildSDIV (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, bool IsAfterLegalization, std::vector< SDNode * > *Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
SDValue BuildUDIV (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, bool IsAfterLegalization, std::vector< SDNode * > *Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
virtual SDValue BuildSDIVPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, std::vector< SDNode * > *Created) const
virtual bool combineRepeatedFPDivisors (unsigned NumUsers) const
virtual SDValue getRsqrtEstimate (SDValue Operand, DAGCombinerInfo &DCI, unsigned &RefinementSteps, bool &UseOneConstNR) const
virtual SDValue getRecipEstimate (SDValue Operand, DAGCombinerInfo &DCI, unsigned &RefinementSteps) const
bool expandMUL (SDNode *N, SDValue &Lo, SDValue &Hi, EVT HiLoVT, SelectionDAG &DAG, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
bool expandFP_TO_SINT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
virtual void AdjustInstrPostInstrSelection (MachineInstr *MI, SDNode *Node) const
virtual bool useLoadStackGuardNode () const
Public Member Functions inherited from llvm::TargetLoweringBase
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
virtual ~TargetLoweringBase ()
const TargetMachine & getTargetMachine () const
const DataLayout * getDataLayout () const
const TargetLoweringObjectFile & getObjFileLowering () const
bool isBigEndian () const
bool isLittleEndian () const
virtual MVT getPointerTy (uint32_t=0) const
unsigned getPointerSizeInBits (uint32_t AS=0) const
unsigned getPointerTypeSizeInBits (Type *Ty) const
EVT getShiftAmountTy (EVT LHSTy) const
virtual MVT getVectorIdxTy () const
bool isSelectExpensive () const
Return true if the select operation is expensive for this target.
virtual bool isSelectSupported (SelectSupportKind) const
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (EVT VT) const
Return the preferred vector type legalization action.
virtual bool shouldExpandBuildVectorWithShuffles (EVT, unsigned DefinedValues) const
bool isIntDivCheap () const
bool isFsqrtCheap () const
Return true if sqrt(x) is as cheap or cheaper than 1 / rsqrt(x)
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
bool isPow2SDivCheap () const
Return true if pow2 sdiv is cheaper than a chain of sra/srl/add/sra.
bool isJumpExpensive () const
bool isPredictableSelectExpensive () const
virtual bool isLoadBitCastBeneficial (EVT, EVT) const
virtual bool isCheapToSpeculateCttz () const
Return true if it is cheap to speculate a call to intrinsic cttz.
virtual bool isCheapToSpeculateCtlz () const
Return true if it is cheap to speculate a call to intrinsic ctlz.
bool isMaskAndBranchFoldingLegal () const
Return if the target supports combining a chain like:
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
bool hasFloatingPointExceptions () const
Return true if target supports floating point exceptions.
virtual bool enableAggressiveFMAFusion (EVT VT) const
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
BooleanContent getBooleanContents (EVT Type) const
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual Sched::Preference getSchedulingPreference (SDNode *) const
virtual const TargetRegisterClass * getRegClassFor (MVT VT) const
virtual uint8_t getRepRegClassCostFor (MVT VT) const
bool isTypeLegal (EVT VT) const
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
LegalizeTypeAction getTypeAction (MVT VT) const
EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
virtual bool getTgtMemIntrinsic (IntrinsicInfo &, const CallInst &, unsigned) const
virtual bool canOpTrap (unsigned Op, EVT VT) const
virtual bool isVectorClearMaskLegal (const SmallVectorImpl< int > &, EVT) const
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT) const
bool isOperationLegalOrPromote (unsigned Op, EVT VT) const
bool isOperationExpand (unsigned Op, EVT VT) const
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
EVT getValueType (Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
virtual unsigned getByValTypeAlignment (Type *Ty) const
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
unsigned getNumRegisters (LLVMContext &Context, EVT VT) const
virtual bool ShouldShrinkFPConstant (EVT) const
virtual bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const
bool hasBigEndianPartOrdering (EVT VT) const
bool hasTargetDAGCombine (ISD::NodeType NT) const
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool isSafeMemOpType (MVT) const
bool usesUnderscoreSetJmp () const
Determine if we should use _setjmp or setjmp to implement llvm.setjmp.
bool usesUnderscoreLongJmp () const
Determine if we should use _longjmp or longjmp to implement llvm.longjmp.
int getMinimumJumpTableEntries () const
unsigned getStackPointerRegisterToSaveRestore () const
unsigned getExceptionPointerRegister () const
unsigned getExceptionSelectorRegister () const
unsigned getJumpBufSize () const
unsigned getJumpBufAlignment () const
unsigned getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
unsigned getMinFunctionAlignment () const
Return the minimum function alignment.
unsigned getPrefFunctionAlignment () const
Return the preferred function alignment.
virtual unsigned getPrefLoopAlignment (MachineLoop *ML=nullptr) const
Return the preferred loop alignment.
bool getInsertFencesForAtomic () const
virtual bool getStackCookieLocation (unsigned &, unsigned &) const
virtual unsigned getMaximalGlobalOffset () const
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast between SrcAS and DestAS is a noop.
virtual bool shouldExpandAtomicStoreInIR (StoreInst *SI) const
virtual bool shouldExpandAtomicLoadInIR (LoadInst *LI) const
virtual bool shouldExpandAtomicRMWInIR (AtomicRMWInst *RMWI) const
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
virtual void resetOperationActions ()
Reset the operation actions based on target options.
virtual bool GetAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value * > &, Type *&) const
virtual int getScalingFactorCost (const AddrMode &AM, Type *Ty) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
virtual bool isLegalICmpImmediate (int64_t) const
virtual bool isLegalAddImmediate (int64_t) const
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
virtual bool isTruncateFree (Type *, Type *) const
virtual bool allowTruncateForTailCall (Type *, Type *) const
virtual bool isTruncateFree (EVT, EVT) const
virtual bool isZExtFree (Type *, Type *) const
virtual bool isZExtFree (EVT, EVT) const
virtual bool hasPairedLoad (Type *, unsigned &) const
virtual bool hasPairedLoad (EVT, unsigned &) const
virtual bool isZExtFree (SDValue Val, EVT VT2) const
virtual bool isFPExtFree (EVT VT) const
virtual bool isFNegFree (EVT VT) const
virtual bool isFAbsFree (EVT VT) const
virtual bool isFMAFasterThanFMulAndFAdd (EVT) const
virtual bool isNarrowingProfitable (EVT, EVT) const
virtual bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const
Return true if it is beneficial to convert a load of a constant to just the constant itself. On some targets it might be more efficient to use a combination of arithmetic instructions to materialize the constant instead of loading it from a constant pool.
virtual bool isExtractSubvectorCheap (EVT ResVT, unsigned Index) const
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
LegalizeKind getTypeConversion (LLVMContext &Context, EVT VT) const
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
std::pair< unsigned, MVT > getTypeLegalizationCost (Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
virtual bool hasLoadLinkedStoreConditional () const
virtual Value * emitLoadLinked (IRBuilder<> &Builder, Value *Addr, AtomicOrdering Ord) const
virtual Value * emitStoreConditional (IRBuilder<> &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const
virtual Instruction * emitLeadingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const
virtual Instruction * emitTrailingFence (IRBuilder<> &Builder, AtomicOrdering Ord, bool IsStore, bool IsLoad) const
Additional Inherited Members
Public Types inherited from llvm::TargetLowering
enum ConstraintType {
C_Register , C_RegisterClass , C_Memory , C_Other ,
C_Unknown
}
enum ConstraintWeight {
CW_Invalid = -1 , CW_Okay = 0 , CW_Good = 1 , CW_Better = 2 ,
CW_Best = 3 , CW_SpecificReg = CW_Okay , CW_Register = CW_Good , CW_Memory = CW_Better ,
CW_Constant = CW_Best , CW_Default = CW_Okay
}
typedef std::vector< ArgListEntry > ArgListTy
typedef std::vector< AsmOperandInfo > AsmOperandInfoVector
Public Types inherited from llvm::TargetLoweringBase
enum LegalizeAction { Legal , Promote , Expand , Custom }
enum LegalizeTypeAction {
TypeLegal , TypePromoteInteger , TypeExpandInteger , TypeSoftenFloat ,
TypeExpandFloat , TypeScalarizeVector , TypeSplitVector , TypeWidenVector
}
enum BooleanContent { UndefinedBooleanContent , ZeroOrOneBooleanContent , ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect , ScalarCondVectorVal , VectorMaskSelect }
Enum that describes what type of support for selects the target has.
typedef std::pair< LegalizeTypeAction, EVT > LegalizeKind
Static Public Member Functions inherited from llvm::MipsTargetLowering
static const MipsTargetLowering * create (const MipsTargetMachine &TM, const MipsSubtarget &STI)
Static Public Member Functions inherited from llvm::TargetLoweringBase
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions inherited from llvm::MipsTargetLowering
SDValue getGlobalReg (SelectionDAG &DAG, EVT Ty) const
template<class NodeTy>
SDValue getAddrLocal (NodeTy *N, SDLoc DL, EVT Ty, SelectionDAG &DAG, bool IsN32OrN64) const
template<class NodeTy>
SDValue getAddrGlobal (NodeTy *N, SDLoc DL, EVT Ty, SelectionDAG &DAG, unsigned Flag, SDValue Chain, const MachinePointerInfo &PtrInfo) const
template<class NodeTy>
SDValue getAddrGlobalLargeGOT (NodeTy *N, SDLoc DL, EVT Ty, SelectionDAG &DAG, unsigned HiFlag, unsigned LoFlag, SDValue Chain, const MachinePointerInfo &PtrInfo) const
template<class NodeTy>
SDValue getAddrNonPIC (NodeTy *N, SDLoc DL, EVT Ty, SelectionDAG &DAG) const
template<class NodeTy>
SDValue getAddrGPRel (NodeTy *N, SDLoc DL, EVT Ty, SelectionDAG &DAG) const
SDValue lowerLOAD (SDValue Op, SelectionDAG &DAG) const
SDValue lowerSTORE (SDValue Op, SelectionDAG &DAG) const
Protected Member Functions inherited from llvm::TargetLoweringBase
void initActions ()
Initialize all of the actions to default values.
void setBooleanContents (BooleanContent Ty)
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
void setBooleanVectorContents (BooleanContent Ty)
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setUseUnderscoreSetJmp (bool Val)
void setUseUnderscoreLongJmp (bool Val)
void setMinimumJumpTableEntries (int Val)
void setStackPointerRegisterToSaveRestore (unsigned R)
void setExceptionPointerRegister (unsigned R)
void setExceptionSelectorRegister (unsigned R)
void setSelectIsExpensive (bool isExpensive=true)
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
void setHasExtractBitsInsn (bool hasExtractInsn=true)
void setJumpIsExpensive (bool isExpensive=true)
void setIntDivIsCheap (bool isCheap=true)
void setFsqrtIsCheap (bool isCheap=true)
void setHasFloatingPointExceptions (bool FPExceptions=true)
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void setPow2SDivIsCheap (bool isCheap=true)
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
void clearRegisterClasses ()
Remove all register classes.
void clearOperationActions ()
Remove all operation actions.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (MVT VT) const
void computeRegisterProperties ()
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
void setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action)
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
void setTargetDAGCombine (ISD::NodeType NT)
void setJumpBufSize (unsigned Size)
Set the target's required jmp_buf buffer size (in bytes); default is 200.
void setJumpBufAlignment (unsigned Align)
void setMinFunctionAlignment (unsigned Align)
Set the target's minimum function alignment (in log2(bytes))
void setPrefFunctionAlignment (unsigned Align)
void setPrefLoopAlignment (unsigned Align)
void setMinStackArgumentAlignment (unsigned Align)
Set the minimum stack alignment of an argument (in log2(bytes)).
void setInsertFencesForAtomic (bool fence)
bool isLegalRC (const TargetRegisterClass *RC) const
MachineBasicBlock * emitPatchPoint (MachineInstr *MI, MachineBasicBlock *MBB) const
Protected Attributes inherited from llvm::MipsTargetLowering
const MipsSubtarget & Subtarget
Protected Attributes inherited from llvm::TargetLoweringBase
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
unsigned MaxStoresPerMemcpy
Specify maximum bytes of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
unsigned MaxStoresPerMemmove
Specify maximum bytes of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
bool PredictableSelectIsExpensive
bool MaskAndBranchFoldingIsLegal
bool EnableExtLdPromotion
Detailed Description
Definition at line 21 of file MipsSEISelLowering.h.
Constructor & Destructor Documentation
MipsSETargetLowering()
MipsSETargetLowering::MipsSETargetLowering (const MipsTargetMachine & TM, const MipsSubtarget & STI) explicit
Definition at line 38 of file MipsSEISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDE, addMSAFloatType(), addMSAIntType(), llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::AND, llvm::array_lengthof(), llvm::ISD::ATOMIC_FENCE, llvm::ISD::BITCAST, llvm::ISD::BRCOND, llvm::ISD::BUILTIN_OP_END, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::TargetLoweringBase::Custom, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLoweringBase::Legal, llvm::ISD::LOAD, llvm::MipsTargetLowering::MipsTargetLowering(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, NoDPLoadStore, llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::TargetLoweringBase::setCondCodeAction(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::ISD::SMUL_LOHI, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::SUBE, llvm::MipsTargetLowering::Subtarget, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UMUL_LOHI, llvm::ISD::UREM, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i16, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v4i8, llvm::MVT::v8f16, llvm::MVT::v8i16, llvm::MVT::vector_valuetypes(), llvm::ISD::VSELECT, llvm::ISD::XOR, and llvm::ISD::ZEXTLOAD.
Member Function Documentation
addMSAFloatType()
void MipsSETargetLowering::addMSAFloatType (MVT::SimpleValueType Ty, const TargetRegisterClass * RC)
Enable MSA support for the given floating-point type and Register class.
Definition at line 294 of file MipsSEISelLowering.cpp.
References llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::TargetLoweringBase::Custom, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FEXP2, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FRINT, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::INSERT_VECTOR_ELT, llvm::TargetLoweringBase::Legal, llvm::ISD::LOAD, llvm::ISD::SETCC, llvm::TargetLoweringBase::setCondCodeAction(), llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::TargetLoweringBase::setOperationAction(), llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::STORE, llvm::MVT::v8f16, and llvm::ISD::VSELECT.
Referenced by MipsSETargetLowering().
addMSAIntType()
void MipsSETargetLowering::addMSAIntType (MVT::SimpleValueType Ty, const TargetRegisterClass * RC)
Enable MSA support for the given integer type and Register class.
Definition at line 245 of file MipsSEISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::AND, llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::ISD::CTLZ, llvm::ISD::CTPOP, llvm::TargetLoweringBase::Custom, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::INSERT_VECTOR_ELT, llvm::TargetLoweringBase::Legal, llvm::ISD::LOAD, llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::SDIV, llvm::ISD::SETCC, llvm::TargetLoweringBase::setCondCodeAction(), llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETNE, llvm::TargetLoweringBase::setOperationAction(), llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SHL, llvm::ISD::SINT_TO_FP, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::UDIV, llvm::ISD::UINT_TO_FP, llvm::ISD::UREM, llvm::MVT::v2i64, llvm::MVT::v4i32, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, and llvm::ISD::XOR.
Referenced by MipsSETargetLowering().
allowsMisalignedMemoryAccesses()
bool MipsSETargetLowering::allowsMisalignedMemoryAccesses (EVT , unsigned AddrSpace = 0, unsigned Align = 1, bool * = nullptr) const override virtual
Determine if the target supports unaligned memory accesses.
This function returns true if the target allows unaligned memory accesses of the specified type in the given address space. If true, it also returns whether the unaligned memory access is "fast" in the last argument by reference. This is used, for example, in situations where an array copy/move/set is converted to a sequence of store operations. Its use helps to ensure that such replacements don't generate code that causes an alignment error (trap) on the target machine.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 333 of file MipsSEISelLowering.cpp.
References llvm::EVT::getSimpleVT(), llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::SimpleTy, and llvm::MipsTargetLowering::Subtarget.
EmitInstrWithCustomInserter()
MachineBasicBlock * MipsSETargetLowering::EmitInstrWithCustomInserter (MachineInstr * MI, MachineBasicBlock * MBB) const override virtual
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag. These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow.
Reimplemented from llvm::TargetLowering.
Definition at line 1112 of file MipsSEISelLowering.cpp.
References llvm::MipsTargetLowering::EmitInstrWithCustomInserter().
getRepRegClassFor()
const TargetRegisterClass * MipsSETargetLowering::getRepRegClassFor (MVT VT) const override virtual
Return the 'representative' register class for the specified value type.
The 'representative' register class is the largest legal super-reg register class for the register class of the value type. For example, on i386 the rep register class for i8, i16, and i32 are GR32; while the rep register class is GR64 on x86_64.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 237 of file MipsSEISelLowering.cpp.
References llvm::TargetLoweringBase::getRepRegClassFor(), llvm::MipsTargetLowering::Subtarget, and llvm::MVT::Untyped.
isShuffleMaskLegal()
bool llvm::MipsSETargetLowering::isShuffleMaskLegal (const SmallVectorImpl< int > & , EVT) const inline override virtual
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks. By default, if a target supports the VECTOR_SHUFFLE node, all mask values are assumed to be legal.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 46 of file MipsSEISelLowering.h.
LowerOperation()
SDValue MipsSETargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const override virtual
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal. If the target has no operations that require custom lowering, it need not implement this. The default implementation of this aborts.
Reimplemented from llvm::TargetLowering.
Definition at line 360 of file MipsSEISelLowering.cpp.
References llvm::ISD::BUILD_VECTOR, llvm::MipsISD::DivRem, llvm::MipsISD::DivRemU, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SDValue::getOpcode(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::LOAD, llvm::MipsTargetLowering::LowerOperation(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::MipsISD::Mult, llvm::MipsISD::Multu, llvm::ISD::SDIVREM, llvm::ISD::SMUL_LOHI, llvm::ISD::STORE, llvm::ISD::UDIVREM, llvm::ISD::UMUL_LOHI, and llvm::ISD::VECTOR_SHUFFLE.
PerformDAGCombine()
SDValue MipsSETargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const override virtual
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::TargetLowering.
Definition at line 1066 of file MipsSEISelLowering.cpp.
References llvm::ISD::ADDE, llvm::ISD::AND, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dbgs(), DEBUG, llvm::SDValue::getNode(), llvm::ISD::MUL, N, llvm::ISD::OR, performADDECombine(), performANDCombine(), llvm::MipsTargetLowering::PerformDAGCombine(), performMULCombine(), performORCombine(), performSETCCCombine(), performSHLCombine(), performSRACombine(), performSRLCombine(), performSUBECombine(), performVSELECTCombine(), performXORCombine(), llvm::SDNode::printrWithDepth(), llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUBE, llvm::MipsTargetLowering::Subtarget, llvm::ISD::VSELECT, and llvm::ISD::XOR.
The documentation for this class was generated from the following files:
MipsSEISelLowering.h
MipsSEISelLowering.cpp