LLVM: llvm::AliasSet Class Reference
LLVM API Documentation
llvm::AliasSet Class Reference
#include <AliasSetTracker.h>
Classes
class iterator
Define an iterator for alias sets... this is just a forward iterator.
Public Member Functions
bool isRef () const
Accessors...
bool isMod () const
bool isMustAlias () const
bool isMayAlias () const
bool isVolatile () const
bool isForwardingAliasSet () const
void mergeSetIn (AliasSet &AS, AliasSetTracker &AST)
iterator begin () const
iterator end () const
bool empty () const
void print (raw_ostream &OS) const
void dump () const
bool aliasesPointer (const Value *Ptr, uint64_t Size, const AAMDNodes &AAInfo, AliasAnalysis &AA) const
bool aliasesUnknownInst (Instruction *Inst, AliasAnalysis &AA) const
Public Member Functions inherited from llvm::ilist_node< AliasSet >
AliasSet * getPrevNode ()
Get the previous node, or 0 for the list head.
AliasSet * getNextNode ()
Get the next node, or 0 for the list tail.
Friends
class AliasSetTracker
struct ilist_sentinel_traits< AliasSet >
Additional Inherited Members
Protected Member Functions inherited from llvm::ilist_node< AliasSet >
ilist_node ()
Detailed Description
Definition at line 36 of file AliasSetTracker.h.
Member Function Documentation
aliasesPointer()
bool AliasSet::aliasesPointer (const Value * Ptr, uint64_t Size, const AAMDNodes & AAInfo, AliasAnalysis & AA) const
aliasesPointer - Return true if the specified pointer "may" (or must) alias one of the members in the set.
Definition at line 149 of file AliasSetTracker.cpp.
References llvm::AliasAnalysis::alias(), begin(), end(), llvm::AliasAnalysis::getModRefInfo(), I, and llvm::AliasAnalysis::NoModRef.
aliasesUnknownInst()
bool AliasSet::aliasesUnknownInst (Instruction * Inst, AliasAnalysis & AA) const
Definition at line 185 of file AliasSetTracker.cpp.
References begin(), end(), llvm::AliasAnalysis::getModRefInfo(), I, llvm::Instruction::mayReadOrWriteMemory(), and llvm::AliasAnalysis::NoModRef.
begin()
iterator llvm::AliasSet::begin () const inline
Definition at line 176 of file AliasSetTracker.h.
Referenced by llvm::AliasSetTracker::add(), aliasesPointer(), aliasesUnknownInst(), and print().
dump()
void AliasSet::dump () const
Definition at line 622 of file AliasSetTracker.cpp.
References llvm::dbgs(), and print().
empty()
bool llvm::AliasSet::empty () const inline
Definition at line 178 of file AliasSetTracker.h.
Referenced by print(), and llvm::AliasSetTracker::remove().
end()
iterator llvm::AliasSet::end () const inline
Definition at line 177 of file AliasSetTracker.h.
Referenced by llvm::AliasSetTracker::add(), aliasesPointer(), aliasesUnknownInst(), and print().
isForwardingAliasSet()
bool llvm::AliasSet::isForwardingAliasSet () const inline
isForwardingAliasSet - Return true if this alias set should be ignored as part of the AliasSetTracker object.
Definition at line 167 of file AliasSetTracker.h.
isMayAlias()
bool llvm::AliasSet::isMayAlias () const inline
Definition at line 159 of file AliasSetTracker.h.
isMod()
bool llvm::AliasSet::isMod () const inline
Definition at line 157 of file AliasSetTracker.h.
isMustAlias()
bool llvm::AliasSet::isMustAlias () const inline
Definition at line 158 of file AliasSetTracker.h.
isRef()
bool llvm::AliasSet::isRef () const inline
Accessors...
Definition at line 156 of file AliasSetTracker.h.
isVolatile()
bool llvm::AliasSet::isVolatile () const inline
Definition at line 163 of file AliasSetTracker.h.
Referenced by llvm::AliasSetTracker::add(), and print().
mergeSetIn()
void AliasSet::mergeSetIn (AliasSet & AS, AliasSetTracker & AST)
mergeSetIn - Merge the specified alias set into this alias set...
mergeSetIn - Merge the specified alias set into this alias set.
Definition at line 30 of file AliasSetTracker.cpp.
References llvm::AliasAnalysis::alias(), AliasSetTracker, llvm::AliasSetTracker::getAliasAnalysis(), llvm::AliasAnalysis::MustAlias, and std::swap().
print()
void AliasSet::print (raw_ostream & OS) const
Definition at line 580 of file AliasSetTracker.cpp.
References begin(), empty(), end(), I, isVolatile(), and llvm_unreachable.
Referenced by dump(), and llvm::operator<<().
Friends And Related Symbol Documentation
AliasSetTracker
friend class AliasSetTracker friend
Definition at line 37 of file AliasSetTracker.h.
References AliasSetTracker.
Referenced by AliasSetTracker, and mergeSetIn().
ilist_sentinel_traits< AliasSet >
friend struct ilist_sentinel_traits< AliasSet > friend
Definition at line 181 of file AliasSetTracker.h.
The documentation for this class was generated from the following files:
AliasSetTracker.h
AliasSetTracker.cpp