LLVM: llvm::OnDiskIterableChainedHashTable< Info >::data_iterator Class Reference
LLVM API Documentation
llvm::OnDiskIterableChainedHashTable< Info >::data_iterator Class Reference
Iterates over all the entries in the table, returning the data.
#include <OnDiskHashTable.h>
Public Types
typedef data_type value_type
Public Member Functions
data_iterator (const unsigned char *const Ptr, offset_type NumEntries, Info *InfoObj)
data_iterator ()
bool operator== (const data_iterator &X) const
bool operator!= (const data_iterator &X) const
data_iterator & operator++ ()
data_iterator operator++ (int)
value_type operator* () const
Detailed Description
template<typename Info>
class llvm::OnDiskIterableChainedHashTable< Info >::data_iterator
Iterates over all the entries in the table, returning the data.
Definition at line 467 of file OnDiskHashTable.h.
Member Typedef Documentation
value_type
template<typename Info> typedef data_type llvm::OnDiskIterableChainedHashTable< Info >::data_iterator::value_type
Definition at line 474 of file OnDiskHashTable.h.
Constructor & Destructor Documentation
data_iterator() [1/2]
template<typename Info> llvm::OnDiskIterableChainedHashTable< Info >::data_iterator::data_iterator (const unsigned char *const Ptr, offset_type NumEntries, Info * InfoObj) inline
Definition at line 476 of file OnDiskHashTable.h.
Referenced by operator!=(), operator++(), operator++(), and operator==().
data_iterator() [2/2]
template<typename Info> llvm::OnDiskIterableChainedHashTable< Info >::data_iterator::data_iterator () inline
Definition at line 480 of file OnDiskHashTable.h.
Member Function Documentation
operator!=()
template<typename Info> bool llvm::OnDiskIterableChainedHashTable< Info >::data_iterator::operator!= (const data_iterator & X) const inline
Definition at line 487 of file OnDiskHashTable.h.
References data_iterator(), and llvm::X.
operator*()
template<typename Info> value_type llvm::OnDiskIterableChainedHashTable< Info >::data_iterator::operator* () const inline
Definition at line 514 of file OnDiskHashTable.h.
operator++() [1/2]
template<typename Info> data_iterator & llvm::OnDiskIterableChainedHashTable< Info >::data_iterator::operator++ () inline
Definition at line 491 of file OnDiskHashTable.h.
References data_iterator(), and llvm::support::endian::readNext().
operator++() [2/2]
template<typename Info> data_iterator llvm::OnDiskIterableChainedHashTable< Info >::data_iterator::operator++ (int) inline
Definition at line 510 of file OnDiskHashTable.h.
References data_iterator().
operator==()
template<typename Info> bool llvm::OnDiskIterableChainedHashTable< Info >::data_iterator::operator== (const data_iterator & X) const inline
Definition at line 484 of file OnDiskHashTable.h.
References data_iterator(), and llvm::X.
The documentation for this class was generated from the following file:
OnDiskHashTable.h