LLVM: llvm::object::MachORebaseEntry Class Reference
LLVM API Documentation
llvm::object::MachORebaseEntry Class Reference
#include <MachO.h>
Public Member Functions
MachORebaseEntry (ArrayRef< uint8_t > opcodes, bool is64Bit)
uint32_t segmentIndex () const
uint64_t segmentOffset () const
StringRef typeName () const
bool operator== (const MachORebaseEntry &) const
void moveNext ()
Friends
class MachOObjectFile
Detailed Description
MachORebaseEntry encapsulates the current state in the decompression of
rebasing opcodes. This allows you to iterate through the compressed table of rebasing using: for (const llvm::object::MachORebaseEntry &Entry : Obj->rebaseTable()) { }
Definition at line 108 of file Object/MachO.h.
Constructor & Destructor Documentation
MachORebaseEntry()
MachORebaseEntry::MachORebaseEntry (ArrayRef< uint8_t > opcodes, bool is64Bit)
Definition at line 1663 of file MachOObjectFile.cpp.
References is64Bit().
Referenced by operator==().
Member Function Documentation
moveNext()
void MachORebaseEntry::moveNext ()
Definition at line 1679 of file MachOObjectFile.cpp.
References llvm::dbgs(), DEBUG_WITH_TYPE, llvm::format(), llvm::MachO::REBASE_IMMEDIATE_MASK, llvm::MachO::REBASE_OPCODE_ADD_ADDR_IMM_SCALED, llvm::MachO::REBASE_OPCODE_ADD_ADDR_ULEB, llvm::MachO::REBASE_OPCODE_DO_REBASE_ADD_ADDR_ULEB, llvm::MachO::REBASE_OPCODE_DO_REBASE_IMM_TIMES, llvm::MachO::REBASE_OPCODE_DO_REBASE_ULEB_TIMES, llvm::MachO::REBASE_OPCODE_DO_REBASE_ULEB_TIMES_SKIPPING_ULEB, llvm::MachO::REBASE_OPCODE_DONE, llvm::MachO::REBASE_OPCODE_MASK, llvm::MachO::REBASE_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB, and llvm::MachO::REBASE_OPCODE_SET_TYPE_IMM.
operator==()
bool MachORebaseEntry::operator== (const MachORebaseEntry & Other) const
Definition at line 1811 of file MachOObjectFile.cpp.
References MachORebaseEntry().
segmentIndex()
uint32_t MachORebaseEntry::segmentIndex () const
Definition at line 1795 of file MachOObjectFile.cpp.
segmentOffset()
uint64_t MachORebaseEntry::segmentOffset () const
Definition at line 1797 of file MachOObjectFile.cpp.
typeName()
StringRef MachORebaseEntry::typeName () const
Definition at line 1799 of file MachOObjectFile.cpp.
References llvm::MachO::REBASE_TYPE_POINTER, llvm::MachO::REBASE_TYPE_TEXT_ABSOLUTE32, and llvm::MachO::REBASE_TYPE_TEXT_PCREL32.
Friends And Related Symbol Documentation
MachOObjectFile
friend class MachOObjectFile friend
Definition at line 121 of file Object/MachO.h.
References MachOObjectFile.
Referenced by MachOObjectFile.
The documentation for this class was generated from the following files:
Object/MachO.h
MachOObjectFile.cpp