LLVM: llvm::MachineModuleInfoImpl Class Reference
LLVM API Documentation
llvm::MachineModuleInfoImpl Class Reference
#include <MachineModuleInfo.h>
Public Types
typedef PointerIntPair< MCSymbol *, 1, bool > StubValueTy
typedef std::vector< std::pair< MCSymbol *, StubValueTy > > SymbolListTy
Public Member Functions
virtual ~MachineModuleInfoImpl ()
Static Protected Member Functions
static SymbolListTy GetSortedStubs (const DenseMap< MCSymbol *, StubValueTy > &)
Detailed Description
MachineModuleInfoImpl - This class can be derived from and used by targets to hold private target-specific information for each Module. Objects of type are accessed/created with MMI::getInfo and destroyed when the MachineModuleInfo is destroyed.
Definition at line 83 of file MachineModuleInfo.h.
Member Typedef Documentation
StubValueTy
typedef PointerIntPair<MCSymbol*, 1, bool> llvm::MachineModuleInfoImpl::StubValueTy
Definition at line 85 of file MachineModuleInfo.h.
SymbolListTy
typedef std::vector<std::pair<MCSymbol*, StubValueTy> > llvm::MachineModuleInfoImpl::SymbolListTy
Definition at line 87 of file MachineModuleInfo.h.
Constructor & Destructor Documentation
~MachineModuleInfoImpl()
virtual llvm::MachineModuleInfoImpl::~MachineModuleInfoImpl () virtual
Member Function Documentation
GetSortedStubs()
MachineModuleInfoImpl::SymbolListTy MachineModuleInfoImpl::GetSortedStubs (const DenseMap< MCSymbol *, StubValueTy > & Map) static protected
GetSortedStubs - Return the entries from a DenseMap in a deterministic sorted orer.
Definition at line 37 of file MachineModuleInfoImpls.cpp.
References SortSymbolPair().
Referenced by llvm::MachineModuleInfoMachO::GetFnStubList(), llvm::MachineModuleInfoELF::GetGVStubList(), llvm::MachineModuleInfoMachO::GetGVStubList(), and llvm::MachineModuleInfoMachO::GetHiddenGVStubList().
The documentation for this class was generated from the following files:
MachineModuleInfo.h
MachineModuleInfoImpls.cpp