LLVM: llvm::DIType Class Reference
LLVM API Documentation
llvm::DIType Class Reference
#include <DebugInfo.h>
Public Member Functions
DIType (const MDNode *N=nullptr)
operator DITypeRef () const
bool Verify () const
DIScopeRef getContext () const
StringRef getName () const
unsigned getLineNumber () const
uint64_t getSizeInBits () const
uint64_t getAlignInBits () const
uint64_t getOffsetInBits () const
unsigned getFlags () const
bool isPrivate () const
bool isProtected () const
bool isPublic () const
bool isForwardDecl () const
bool isAppleBlockExtension () const
bool isBlockByrefStruct () const
bool isVirtual () const
bool isArtificial () const
bool isObjectPointer () const
bool isObjcClassComplete () const
bool isVector () const
bool isStaticMember () const
bool isLValueReference () const
bool isRValueReference () const
bool isValid () const
Public Member Functions inherited from llvm::DIScope
DIScope (const MDNode *N=nullptr)
DIScopeRef getContext () const
Get the parent scope.
StringRef getName () const
Get the scope name.
StringRef getFilename () const
StringRef getDirectory () const
DIScopeRef getRef () const
Generate a reference to this DIScope.
Public Member Functions inherited from llvm::DIDescriptor
DIDescriptor (const MDNode *N=nullptr)
bool Verify () const
MDNode * get () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
StringRef getHeader () const
size_t getNumHeaderFields () const
StringRef getHeaderField (unsigned Index) const
template<class T>
T getHeaderFieldAs (unsigned Index) const
uint16_t getTag () const
bool isDerivedType () const
bool isCompositeType () const
bool isSubroutineType () const
bool isBasicType () const
bool isVariable () const
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
bool isCompileUnit () const
bool isNameSpace () const
bool isLexicalBlockFile () const
bool isLexicalBlock () const
bool isSubrange () const
bool isEnumerator () const
bool isType () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
bool isImportedEntity () const
bool isExpression () const
void print (raw_ostream &OS) const
void dump () const
void replaceAllUsesWith (LLVMContext &VMContext, DIDescriptor D)
Replace all uses of debug info referenced by this descriptor.
void replaceAllUsesWith (MDNode *D)
Protected Member Functions
void printInternal (raw_ostream &OS) const
Protected Member Functions inherited from llvm::DIScope
void printInternal (raw_ostream &OS) const
Protected Member Functions inherited from llvm::DIDescriptor
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy>
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
template<>
DITypeRef getFieldAs (unsigned Elt) const
Friends
class DIDescriptor
Additional Inherited Members
Public Types inherited from llvm::DIDescriptor
enum {
FlagAccessibility = 1 << 0 | 1 << 1 , FlagPrivate = 1 , FlagProtected = 2 , FlagPublic = 3 ,
FlagFwdDecl = 1 << 2 , FlagAppleBlock = 1 << 3 , FlagBlockByrefStruct = 1 << 4 , FlagVirtual = 1 << 5 ,
FlagArtificial = 1 << 6 , FlagExplicit = 1 << 7 , FlagPrototyped = 1 << 8 , FlagObjcClassComplete = 1 << 9 ,
FlagObjectPointer = 1 << 10 , FlagVector = 1 << 11 , FlagStaticMember = 1 << 12 , FlagIndirectVariable = 1 << 13 ,
FlagLValueReference = 1 << 14 , FlagRValueReference = 1 << 15
}
Accessibility flags.
Protected Attributes inherited from llvm::DIDescriptor
const MDNode * DbgNode
Detailed Description
\briefThis is a wrapper for a type.
FIXME: Types should be factored much better so that CV qualifiers and others do not require a huge and empty descriptor full of zeros.
Definition at line 389 of file DebugInfo.h.
Constructor & Destructor Documentation
DIType()
llvm::DIType::DIType (const MDNode * N = nullptr) inline explicit
Definition at line 395 of file DebugInfo.h.
References llvm::DIScope::DIScope(), and N.
Referenced by llvm::DIBasicType::DIBasicType(), and llvm::DIDerivedType::DIDerivedType().
Member Function Documentation
getAlignInBits()
uint64_t llvm::DIType::getAlignInBits () const inline
Definition at line 412 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
Referenced by printInternal().
getContext()
DIScopeRef llvm::DIType::getContext () const inline
Definition at line 404 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
Referenced by llvm::DwarfUnit::createTypeDIE(), llvm::DIScope::getContext(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), and llvm::DwarfUnit::getOrCreateTypeDIE().
getFlags()
unsigned llvm::DIType::getFlags () const inline
Definition at line 420 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
Referenced by isAppleBlockExtension(), isArtificial(), isBlockByrefStruct(), isForwardDecl(), isLValueReference(), isObjcClassComplete(), isObjectPointer(), isPrivate(), isProtected(), isPublic(), isRValueReference(), isStaticMember(), isVector(), and isVirtual().
getLineNumber()
unsigned llvm::DIType::getLineNumber () const inline
Definition at line 406 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
Referenced by llvm::DwarfUnit::addSourceLine(), and printInternal().
getName()
StringRef llvm::DIType::getName () const inline
Definition at line 405 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
Referenced by llvm::DwarfUnit::addBlockByrefAddress(), llvm::DwarfCompileUnit::addGlobalType(), llvm::DwarfUnit::constructTypeDIE(), llvm::DIScope::getName(), llvm::DwarfUnit::getOrCreateStaticMemberDIE(), llvm::DbgVariable::getType(), isUnsignedDIType(), and printInternal().
getOffsetInBits()
uint64_t llvm::DIType::getOffsetInBits () const inline
Definition at line 417 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
Referenced by llvm::DwarfUnit::addBlockByrefAddress(), and printInternal().
getSizeInBits()
uint64_t llvm::DIType::getSizeInBits () const inline
Definition at line 409 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
Referenced by llvm::DwarfUnit::constructTypeDIE(), getBaseTypeSize(), llvm::DIVariable::getSizeInBits(), and printInternal().
isAppleBlockExtension()
bool llvm::DIType::isAppleBlockExtension () const inline
Definition at line 431 of file DebugInfo.h.
References llvm::DIDescriptor::FlagAppleBlock, and getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isArtificial()
bool llvm::DIType::isArtificial () const inline
Definition at line 438 of file DebugInfo.h.
References llvm::DIDescriptor::FlagArtificial, and getFlags().
Referenced by llvm::DwarfUnit::constructSubprogramArguments(), llvm::DIBuilder::createArtificialType(), and printInternal().
isBlockByrefStruct()
bool llvm::DIType::isBlockByrefStruct () const inline
Definition at line 434 of file DebugInfo.h.
References llvm::DIDescriptor::FlagBlockByrefStruct, and getFlags().
isForwardDecl()
bool llvm::DIType::isForwardDecl () const inline
Definition at line 430 of file DebugInfo.h.
References llvm::DIDescriptor::FlagFwdDecl, and getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE(), llvm::generateDITypeIdentifierMap(), llvm::DwarfUnit::getOrCreateTypeDIE(), and printInternal().
isLValueReference()
bool llvm::DIType::isLValueReference () const inline
Definition at line 445 of file DebugInfo.h.
References llvm::DIDescriptor::FlagLValueReference, and getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE(), printInternal(), and llvm::DICompositeType::Verify().
isObjcClassComplete()
bool llvm::DIType::isObjcClassComplete () const inline
Definition at line 440 of file DebugInfo.h.
References llvm::DIDescriptor::FlagObjcClassComplete, and getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE().
isObjectPointer()
bool llvm::DIType::isObjectPointer () const inline
Definition at line 439 of file DebugInfo.h.
References llvm::DIDescriptor::FlagObjectPointer, and getFlags().
Referenced by llvm::DIBuilder::createObjectPointerType().
isPrivate()
bool llvm::DIType::isPrivate () const inline
Definition at line 421 of file DebugInfo.h.
References llvm::DIDescriptor::FlagAccessibility, llvm::DIDescriptor::FlagPrivate, and getFlags().
Referenced by llvm::DwarfUnit::getOrCreateStaticMemberDIE(), and printInternal().
isProtected()
bool llvm::DIType::isProtected () const inline
Definition at line 424 of file DebugInfo.h.
References llvm::DIDescriptor::FlagAccessibility, llvm::DIDescriptor::FlagProtected, and getFlags().
Referenced by llvm::DwarfUnit::getOrCreateStaticMemberDIE(), and printInternal().
isPublic()
bool llvm::DIType::isPublic () const inline
Definition at line 427 of file DebugInfo.h.
References llvm::DIDescriptor::FlagAccessibility, llvm::DIDescriptor::FlagPublic, and getFlags().
Referenced by llvm::DwarfUnit::getOrCreateStaticMemberDIE(), and printInternal().
isRValueReference()
bool llvm::DIType::isRValueReference () const inline
Definition at line 448 of file DebugInfo.h.
References llvm::DIDescriptor::FlagRValueReference, and getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE(), printInternal(), and llvm::DICompositeType::Verify().
isStaticMember()
bool llvm::DIType::isStaticMember () const inline
Definition at line 444 of file DebugInfo.h.
References llvm::DIDescriptor::FlagStaticMember, and getFlags().
Referenced by llvm::DwarfUnit::constructTypeDIE(), llvm::DIDerivedType::getConstant(), and printInternal().
isValid()
bool llvm::DIType::isValid () const inline
Definition at line 451 of file DebugInfo.h.
References llvm::DIDescriptor::DbgNode, and llvm::DIDescriptor::isType().
Referenced by getBaseTypeSize().
isVector()
bool llvm::DIType::isVector () const inline
Definition at line 443 of file DebugInfo.h.
References llvm::DIDescriptor::FlagVector, and getFlags().
Referenced by printInternal().
isVirtual()
bool llvm::DIType::isVirtual () const inline
Definition at line 437 of file DebugInfo.h.
References llvm::DIDescriptor::FlagVirtual, and getFlags().
operator DITypeRef()
llvm::DIType::operator DITypeRef () const inline
Definition at line 396 of file DebugInfo.h.
References llvm::DIScope::getRef(), and llvm::DIDescriptor::isType().
printInternal()
void DIType::printInternal (raw_ostream & OS) const protected
Definition at line 1257 of file DebugInfo.cpp.
References llvm::dwarf::AttributeEncodingString(), llvm::DIDescriptor::DbgNode, llvm::dwarf::DW_TAG_class_type, llvm::dwarf::DW_TAG_enumeration_type, llvm::dwarf::DW_TAG_structure_type, llvm::dwarf::DW_TAG_union_type, llvm::StringRef::empty(), getAlignInBits(), getLineNumber(), getName(), getOffsetInBits(), getSizeInBits(), llvm::DIDescriptor::getTag(), isArtificial(), llvm::DIDescriptor::isBasicType(), isForwardDecl(), isLValueReference(), isPrivate(), isProtected(), isPublic(), isRValueReference(), isStaticMember(), and isVector().
Referenced by llvm::DIDescriptor::print().
Verify()
bool DIType::Verify () const
Definition at line 423 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, llvm::dwarf::DW_TAG_array_type, llvm::dwarf::DW_TAG_const_type, llvm::dwarf::DW_TAG_enumeration_type, llvm::dwarf::DW_TAG_friend, llvm::dwarf::DW_TAG_inheritance, llvm::dwarf::DW_TAG_pointer_type, llvm::dwarf::DW_TAG_ptr_to_member_type, llvm::dwarf::DW_TAG_reference_type, llvm::dwarf::DW_TAG_restrict_type, llvm::dwarf::DW_TAG_rvalue_reference_type, llvm::dwarf::DW_TAG_subroutine_type, llvm::dwarf::DW_TAG_volatile_type, fieldIsScopeRef(), llvm::DIScope::getFilename(), llvm::DIDescriptor::getTag(), llvm::DIDescriptor::isBasicType(), llvm::DIDescriptor::isCompositeType(), llvm::DIDescriptor::isDerivedType(), llvm::DIDescriptor::isType(), llvm::DIBasicType::Verify(), llvm::DICompositeType::Verify(), and llvm::DIDerivedType::Verify().
Friends And Related Symbol Documentation
DIDescriptor
friend class DIDescriptor friend
Definition at line 391 of file DebugInfo.h.
References DIDescriptor.
Referenced by DIDescriptor.
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp