LLVM: llvm::ConstantDataSequential Class Reference
LLVM API Documentation
llvm::ConstantDataSequential Class Reference
#include <Constants.h>
Public Member Functions
uint64_t getElementAsInteger (unsigned i) const
APFloat getElementAsAPFloat (unsigned i) const
float getElementAsFloat (unsigned i) const
double getElementAsDouble (unsigned i) const
Constant * getElementAsConstant (unsigned i) const
SequentialType * getType () const
Type * getElementType () const
getElementType - Return the element type of the array/vector.
unsigned getNumElements () const
getNumElements - Return the number of elements in the array or vector.
uint64_t getElementByteSize () const
getElementByteSize - Return the size in bytes of the elements in the data.
bool isString () const
isString - This method returns true if this is an array of i8.
bool isCString () const
StringRef getAsString () const
StringRef getAsCString () const
StringRef getRawDataValues () const
void destroyConstant () override
Public Member Functions inherited from llvm::Constant
bool isNullValue () const
bool isOneValue () const
Returns true if the value is one.
bool isAllOnesValue () const
bool isNegativeZeroValue () const
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool canTrap () const
bool isThreadDependent () const
isThreadDependent - Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
PossibleRelocationsTy getRelocationInfo () const
Constant * getAggregateElement (unsigned Elt) const
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
const APInt & getUniqueInteger () const
virtual void replaceUsesOfWithOnConstant (Value *, Value *, Use *)
void removeDeadConstantUsers () const
Constant * stripPointerCasts ()
const Constant * stripPointerCasts () const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Static Public Member Functions
static bool isElementTypeCompatible (const Type *Ty)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
static Constant * getAllOnesValue (Type *Ty)
Get the all ones value.
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
ConstantDataSequential (Type *ty, ValueTy VT, const char *Data)
~ConstantDataSequential ()
void * operator new (size_t s)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
void destroyConstantImpl ()
void replaceUsesOfWithOnConstantImpl (Constant *Replacement)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions
static Constant * getImpl (StringRef Bytes, Type *Ty)
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Friends
class LLVMContextImpl
Additional Inherited Members
Public Types inherited from llvm::Constant
enum PossibleRelocationsTy { NoRelocation = 0 , LocalRelocation = 1 , GlobalRelocations = 2 }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range< op_iterator > op_range
typedef iterator_range< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal , BasicBlockVal , FunctionVal , GlobalAliasVal ,
GlobalVariableVal , UndefValueVal , BlockAddressVal , ConstantExprVal ,
ConstantAggregateZeroVal , ConstantDataArrayVal , ConstantDataVectorVal , ConstantIntVal ,
ConstantFPVal , ConstantArrayVal , ConstantStructVal , ConstantVectorVal ,
ConstantPointerNullVal , MetadataAsValueVal , InlineAsmVal , InstructionVal ,
ConstantFirstVal = FunctionVal , ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl< const User > const_user_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Detailed Description
ConstantDataSequential - A vector or array constant whose element type is a simple 1/2/4/8-byte integer or float/double, and whose elements are just simple data values (i.e. ConstantInt/ConstantFP). This Constant node has no operands because it stores all of the elements of the constant as densely packed data, instead of as Value*'s.
This is the common base class of ConstantDataArray and ConstantDataVector.
Definition at line 534 of file Constants.h.
Constructor & Destructor Documentation
ConstantDataSequential()
llvm::ConstantDataSequential::ConstantDataSequential (Type * ty, ValueTy VT, const char * Data) inline explicit protected
Definition at line 548 of file Constants.h.
~ConstantDataSequential()
llvm::ConstantDataSequential::~ConstantDataSequential () inline protected
Definition at line 550 of file Constants.h.
Member Function Documentation
classof()
bool llvm::ConstantDataSequential::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 641 of file Constants.h.
References llvm::Value::ConstantDataArrayVal, and llvm::Value::ConstantDataVectorVal.
destroyConstant()
void ConstantDataSequential::destroyConstant () override virtual
destroyConstant - Called if some element of this constant is no longer valid. At this point only other constants may be on the use_list for this constant. Any constants on our Use list must also be destroy'd. The implementation must be sure to remove the constant from the list of available cached constants. Implementations should call destroyConstantImpl as the last thing they do, to destroy all users and delete this.
Reimplemented from llvm::Constant.
Definition at line 2476 of file Constants.cpp.
References llvm::LLVMContextImpl::CDSConstants, llvm::Constant::destroyConstantImpl(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::Type::getContext(), llvm::Value::getContext(), getRawDataValues(), getType(), and llvm::LLVMContext::pImpl.
getAsCString()
StringRef llvm::ConstantDataSequential::getAsCString () const inline
getAsCString - If this array is isCString(), then this method returns the array (without the trailing null byte) as a StringRef. Otherwise, it asserts out.
Definition at line 626 of file Constants.h.
References getAsString(), isCString(), llvm::StringRef::size(), and llvm::StringRef::substr().
getAsString()
StringRef llvm::ConstantDataSequential::getAsString () const inline
getAsString - If this array is isString(), then this method returns the array as a StringRef. Otherwise, it asserts out.
Definition at line 617 of file Constants.h.
References getRawDataValues(), and isString().
Referenced by emitGlobalConstantDataSequential(), getAsCString(), llvm::getConstantStringInfo(), and isCString().
getElementAsAPFloat()
APFloat ConstantDataSequential::getElementAsAPFloat (unsigned Elt) const
getElementAsAPFloat - If this is a sequential container of floating point type, return the specified element as an APFloat.
Definition at line 2663 of file Constants.cpp.
References llvm::Type::DoubleTyID, llvm::Type::FloatTyID, getElementType(), getTypeID(), and llvm_unreachable.
Referenced by getElementAsConstant().
getElementAsConstant()
Constant * ConstantDataSequential::getElementAsConstant (unsigned Elt) const
getElementAsConstant - Return a Constant for a specified index's element. Note that this has to compute a new constant to return, so it isn't as efficient as getElementAsInteger/Float/Double.
Definition at line 2702 of file Constants.cpp.
References llvm::ConstantFP::get(), llvm::ConstantInt::get(), llvm::Value::getContext(), getElementAsAPFloat(), getElementAsInteger(), and getElementType().
Referenced by getLogBase2Vector(), and llvm::ConstantDataVector::getSplatValue().
getElementAsDouble()
double ConstantDataSequential::getElementAsDouble (unsigned Elt) const
getElementAsDouble - If this is an sequential container of doubles, return the specified element as a double.
getElementAsDouble - If this is an sequential container of doubles, return the specified element as a float.
Definition at line 2691 of file Constants.cpp.
References getElementType().
Referenced by emitGlobalConstantDataSequential(), and llvm::ExecutionEngine::getConstantValue().
getElementAsFloat()
float ConstantDataSequential::getElementAsFloat (unsigned Elt) const
getElementAsFloat - If this is an sequential container of floats, return the specified element as a float.
Definition at line 2682 of file Constants.cpp.
References getElementType().
Referenced by emitGlobalConstantDataSequential(), and llvm::ExecutionEngine::getConstantValue().
getElementAsInteger()
uint64_t ConstantDataSequential::getElementAsInteger (unsigned Elt) const
getElementAsInteger - If this is a sequential container of integers (of any size), return the specified element in the low bits of a uint64_t.
Definition at line 2641 of file Constants.cpp.
References getElementType(), llvm::isa(), and llvm_unreachable.
Referenced by emitGlobalConstantDataSequential(), FoldBitCast(), llvm::ExecutionEngine::getConstantValue(), getElementAsConstant(), and WriteConstants().
getElementByteSize()
uint64_t ConstantDataSequential::getElementByteSize () const
getElementByteSize - Return the size in bytes of the elements in the data.
getElementByteSize - Return the size (in bytes) of each element in the array/vector. The size of the elements is known to be a multiple of one byte.
Definition at line 2421 of file Constants.cpp.
References getElementType(), and llvm::Type::getPrimitiveSizeInBits().
Referenced by emitGlobalConstantDataSequential(), getRawDataValues(), and llvm::ConstantDataVector::getSplatValue().
getElementType()
Type * ConstantDataSequential::getElementType () const
getElementType - Return the element type of the array/vector.
Definition at line 2385 of file Constants.cpp.
References llvm::SequentialType::getElementType(), and getType().
Referenced by emitGlobalConstantDataSequential(), llvm::ExecutionEngine::getConstantValue(), getElementAsAPFloat(), getElementAsConstant(), getElementAsDouble(), getElementAsFloat(), getElementAsInteger(), getElementByteSize(), and isString().
getImpl()
Constant * ConstantDataSequential::getImpl (StringRef Elements, Type * Ty) static protected
getImpl - This is the underlying implementation of all of the ConstantDataSequential::get methods. They all thunk down to here, providing the correct element type. We take the bytes in as a StringRef because we want an underlying "char*" to avoid TBAA type punning violations.
StringMap bucket, linked up by their Next pointers. Walk the list.
Definition at line 2444 of file Constants.cpp.
References llvm::LLVMContextImpl::CDSConstants, llvm::ConstantAggregateZero::get(), llvm::Type::getContext(), llvm::Type::getSequentialElementType(), llvm::isa(), isAllZeros(), isElementTypeCompatible(), and llvm::LLVMContext::pImpl.
Referenced by llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), and llvm::ConstantDataVector::get().
getNumElements()
unsigned ConstantDataSequential::getNumElements () const
getNumElements - Return the number of elements in the array or vector.
Definition at line 2413 of file Constants.cpp.
References llvm::dyn_cast(), getType(), and llvm::Type::getVectorNumElements().
Referenced by emitGlobalConstantDataSequential(), llvm::ExecutionEngine::getConstantValue(), getLogBase2Vector(), getRawDataValues(), llvm::ConstantDataVector::getSplatValue(), and WriteConstants().
getRawDataValues()
StringRef ConstantDataSequential::getRawDataValues () const
getRawDataValues - Return the raw, underlying, bytes of this data. Note that this is an extremely tricky thing to work with, as it exposes the host endianness of the data elements.
Definition at line 2389 of file Constants.cpp.
References getElementByteSize(), and getNumElements().
Referenced by destroyConstant(), getAsString(), and llvm::ConstantDataVector::getSplatValue().
getType()
SequentialType * llvm::ConstantDataSequential::getType () const inline
getType - Specialize the getType() method to always return a SequentialType, which reduces the amount of casting needed in parts of the compiler.
Definition at line 591 of file Constants.h.
References llvm::cast(), and llvm::Value::getType().
Referenced by destroyConstant(), emitGlobalConstantDataSequential(), getElementType(), getNumElements(), and isString().
isCString()
bool ConstantDataSequential::isCString () const
isCString - This method returns true if the array "isString", ends with a nul byte, and does not contains any other nul bytes.
Definition at line 2716 of file Constants.cpp.
References llvm::StringRef::back(), llvm::StringRef::drop_back(), llvm::StringRef::find(), getAsString(), isString(), and llvm::StringRef::npos.
Referenced by getAsCString(), and WriteConstants().
isElementTypeCompatible()
bool ConstantDataSequential::isElementTypeCompatible (const Type * Ty) static
isElementTypeCompatible - Return true if a ConstantDataSequential can be formed with a vector or array of the specified element type. ConstantDataArray only works with normal float and int types that are stored densely in memory, not with things like i42 or x86_f80.
Definition at line 2397 of file Constants.cpp.
References llvm::dyn_cast(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), and IT.
Referenced by getImpl(), llvm::ConstantDataVector::getSplat(), and llvm::ConstantVector::getSplat().
isString()
bool ConstantDataSequential::isString () const
isString - This method returns true if this is an array of i8.
Definition at line 2710 of file Constants.cpp.
References getElementType(), getType(), llvm::isa(), and llvm::Type::isIntegerTy().
Referenced by emitGlobalConstantDataSequential(), getAsString(), llvm::getConstantStringInfo(), and isCString().
operator new()
void * llvm::ConstantDataSequential::operator new (size_t s) inline protected
Definition at line 556 of file Constants.h.
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 535 of file Constants.h.
References LLVM_DELETED_FUNCTION, and LLVMContextImpl.
Referenced by LLVMContextImpl.
The documentation for this class was generated from the following files:
Constants.h
Constants.cpp