LLVM: llvm::BitstreamCursor Class Reference
LLVM API Documentation
llvm::BitstreamCursor Class Reference
#include <BitstreamReader.h>
Public Types
enum { AF_DontPopBlockAtEnd = 1 , AF_DontAutoprocessAbbrevs = 2 }
Flags that modify the behavior of advance().
Public Member Functions
BitstreamCursor ()
BitstreamCursor (BitstreamReader &R)
void init (BitstreamReader *R)
void freeState ()
bool canSkipToPos (size_t pos) const
bool AtEndOfStream ()
unsigned getAbbrevIDWidth () const
Return the number of bits used to encode an abbrev #.
uint64_t GetCurrentBitNo () const
Return the bit # of the bit we are reading.
BitstreamReader * getBitStreamReader ()
const BitstreamReader * getBitStreamReader () const
BitstreamEntry advance (unsigned Flags=0)
Advance the current bitstream, returning the next entry in the stream.
BitstreamEntry advanceSkippingSubblocks (unsigned Flags=0)
void JumpToBit (uint64_t BitNo)
Reset the stream to the specified bit number.
void fillCurWord ()
word_t Read (unsigned NumBits)
uint32_t ReadVBR (unsigned NumBits)
uint64_t ReadVBR64 (unsigned NumBits)
unsigned ReadCode ()
unsigned ReadSubBlockID ()
Having read the ENTER_SUBBLOCK code, read the BlockID for the block.
bool SkipBlock ()
bool EnterSubBlock (unsigned BlockID, unsigned *NumWordsP=nullptr)
bool ReadBlockEnd ()
const BitCodeAbbrev * getAbbrev (unsigned AbbrevID)
Return the abbreviation for the specified AbbrevId.
void skipRecord (unsigned AbbrevID)
Read the current record and discard it.
unsigned readRecord (unsigned AbbrevID, SmallVectorImpl< uint64_t > &Vals, StringRef *Blob=nullptr)
void ReadAbbrevRecord ()
bool ReadBlockInfoBlock ()
Friends
class Deserializer
Detailed Description
This represents a position within a bitcode file. There may be multiple independent cursors reading within one bitstream, each maintaining their own local state.
Unlike iterators, BitstreamCursors are heavy-weight objects that should not be passed by value.
Definition at line 166 of file BitstreamReader.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Flags that modify the behavior of advance().
Enumerator
AF_DontPopBlockAtEnd
If this flag is used, the advance() method does not automatically pop the block scope when the end of a block is reached.
AF_DontAutoprocessAbbrevs
If this flag is used, abbrev entries are returned just like normal records.
Definition at line 251 of file BitstreamReader.h.
Constructor & Destructor Documentation
BitstreamCursor() [1/2]
llvm::BitstreamCursor::BitstreamCursor () inline
Definition at line 204 of file BitstreamReader.h.
References init().
BitstreamCursor() [2/2]
llvm::BitstreamCursor::BitstreamCursor (BitstreamReader & R) inline explicit
Definition at line 206 of file BitstreamReader.h.
References init().
Member Function Documentation
advance()
BitstreamEntry llvm::BitstreamCursor::advance (unsigned Flags = 0) inline
Advance the current bitstream, returning the next entry in the stream.
Definition at line 262 of file BitstreamReader.h.
References AF_DontAutoprocessAbbrevs, AF_DontPopBlockAtEnd, llvm::bitc::DEFINE_ABBREV, llvm::bitc::END_BLOCK, llvm::bitc::ENTER_SUBBLOCK, llvm::BitstreamEntry::getEndBlock(), llvm::BitstreamEntry::getError(), llvm::BitstreamEntry::getRecord(), llvm::BitstreamEntry::getSubBlock(), ReadAbbrevRecord(), ReadBlockEnd(), ReadCode(), and ReadSubBlockID().
Referenced by advanceSkippingSubblocks().
advanceSkippingSubblocks()
BitstreamEntry llvm::BitstreamCursor::advanceSkippingSubblocks (unsigned Flags = 0) inline
This is a convenience function for clients that don't expect any subblocks. This just skips over them automatically.
Definition at line 289 of file BitstreamReader.h.
References advance(), llvm::BitstreamEntry::getError(), llvm::BitstreamEntry::Kind, SkipBlock(), and llvm::BitstreamEntry::SubBlock.
Referenced by ReadBlockInfoBlock().
AtEndOfStream()
bool llvm::BitstreamCursor::AtEndOfStream () inline
Definition at line 226 of file BitstreamReader.h.
References fillCurWord().
Referenced by EnterSubBlock(), and SkipBlock().
canSkipToPos()
bool llvm::BitstreamCursor::canSkipToPos (size_t pos) const inline
Definition at line 220 of file BitstreamReader.h.
Referenced by JumpToBit(), readRecord(), SkipBlock(), and skipRecord().
EnterSubBlock()
bool BitstreamCursor::EnterSubBlock (unsigned BlockID, unsigned * NumWordsP = nullptr)
Having read the ENTER_SUBBLOCK abbrevid, enter the block, and return true if the block has an error.
EnterSubBlock - Having read the ENTER_SUBBLOCK abbrevid, enter the block, and return true if the block has an error.
Definition at line 28 of file BitstreamReader.cpp.
References AtEndOfStream(), llvm::bitc::BlockSizeWidth, llvm::bitc::CodeLenWidth, Read(), and ReadVBR().
Referenced by ReadBlockInfoBlock().
fillCurWord()
void llvm::BitstreamCursor::fillCurWord () inline
Definition at line 317 of file BitstreamReader.h.
References llvm::support::endian::read().
Referenced by AtEndOfStream(), and Read().
freeState()
void BitstreamCursor::freeState ()
Definition at line 18 of file BitstreamReader.cpp.
Referenced by init().
getAbbrev()
const BitCodeAbbrev * llvm::BitstreamCursor::getAbbrev (unsigned AbbrevID) inline
Return the abbreviation for the specified AbbrevId.
Definition at line 495 of file BitstreamReader.h.
References llvm::bitc::FIRST_APPLICATION_ABBREV.
Referenced by readRecord(), and skipRecord().
getAbbrevIDWidth()
unsigned llvm::BitstreamCursor::getAbbrevIDWidth () const inline
Return the number of bits used to encode an abbrev #.
Definition at line 236 of file BitstreamReader.h.
getBitStreamReader() [1/2]
BitstreamReader * llvm::BitstreamCursor::getBitStreamReader () inline
Definition at line 243 of file BitstreamReader.h.
getBitStreamReader() [2/2]
const BitstreamReader * llvm::BitstreamCursor::getBitStreamReader () const inline
Definition at line 246 of file BitstreamReader.h.
GetCurrentBitNo()
uint64_t llvm::BitstreamCursor::GetCurrentBitNo () const inline
Return the bit # of the bit we are reading.
Definition at line 239 of file BitstreamReader.h.
Referenced by readRecord(), SkipBlock(), and skipRecord().
init()
void llvm::BitstreamCursor::init (BitstreamReader * R) inline
Definition at line 208 of file BitstreamReader.h.
References freeState().
Referenced by BitstreamCursor(), and BitstreamCursor().
JumpToBit()
void llvm::BitstreamCursor::JumpToBit (uint64_t BitNo) inline
Reset the stream to the specified bit number.
Definition at line 303 of file BitstreamReader.h.
References canSkipToPos(), and Read().
Referenced by readRecord(), SkipBlock(), and skipRecord().
Read()
word_t llvm::BitstreamCursor::Read (unsigned NumBits) inline
Definition at line 339 of file BitstreamReader.h.
References fillCurWord(), and R2.
Referenced by EnterSubBlock(), JumpToBit(), readAbbreviatedField(), ReadAbbrevRecord(), ReadCode(), ReadVBR(), ReadVBR64(), skipAbbreviatedField(), and SkipBlock().
ReadAbbrevRecord()
void BitstreamCursor::ReadAbbrevRecord ()
Definition at line 240 of file BitstreamReader.cpp.
References llvm::BitCodeAbbrev::Add(), llvm::BitCodeAbbrevOp::Fixed, llvm::BitCodeAbbrevOp::hasEncodingData(), Read(), ReadVBR(), ReadVBR64(), true, and llvm::BitCodeAbbrevOp::VBR.
Referenced by advance(), and ReadBlockInfoBlock().
ReadBlockEnd()
bool llvm::BitstreamCursor::ReadBlockEnd () inline
Definition at line 468 of file BitstreamReader.h.
Referenced by advance().
ReadBlockInfoBlock()
bool BitstreamCursor::ReadBlockInfoBlock ()
Definition at line 270 of file BitstreamReader.cpp.
References llvm::BitstreamReader::BlockInfo::Abbrevs, advanceSkippingSubblocks(), AF_DontAutoprocessAbbrevs, llvm::bitc::BLOCKINFO_BLOCK_ID, llvm::bitc::BLOCKINFO_CODE_BLOCKNAME, llvm::bitc::BLOCKINFO_CODE_SETBID, llvm::bitc::BLOCKINFO_CODE_SETRECORDNAME, llvm::bitc::DEFINE_ABBREV, llvm::BitstreamEntry::EndBlock, EnterSubBlock(), llvm::BitstreamEntry::Error, llvm::BitstreamEntry::ID, llvm::BitstreamEntry::Kind, llvm::BitstreamReader::BlockInfo::Name, Name, ReadAbbrevRecord(), readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamReader::BlockInfo::RecordNames, SkipBlock(), and llvm::BitstreamEntry::SubBlock.
ReadCode()
unsigned llvm::BitstreamCursor::ReadCode () inline
Definition at line 432 of file BitstreamReader.h.
References Read().
Referenced by advance().
readRecord()
unsigned BitstreamCursor::readRecord (unsigned AbbrevID, SmallVectorImpl< uint64_t > & Vals, StringRef * Blob = nullptr)
Definition at line 154 of file BitstreamReader.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::BitCodeAbbrevOp::Array, llvm::BitCodeAbbrevOp::Blob, canSkipToPos(), getAbbrev(), GetCurrentBitNo(), llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrevOp::getLiteralValue(), llvm::BitCodeAbbrev::getNumOperandInfos(), llvm::BitCodeAbbrev::getOperandInfo(), llvm::BitCodeAbbrevOp::isLiteral(), JumpToBit(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), readAbbreviatedField(), ReadVBR(), ReadVBR64(), and llvm::bitc::UNABBREV_RECORD.
Referenced by ReadBlockInfoBlock().
ReadSubBlockID()
unsigned llvm::BitstreamCursor::ReadSubBlockID () inline
Having read the ENTER_SUBBLOCK code, read the BlockID for the block.
Definition at line 441 of file BitstreamReader.h.
References llvm::bitc::BlockIDWidth, and ReadVBR().
Referenced by advance().
ReadVBR()
uint32_t llvm::BitstreamCursor::ReadVBR (unsigned NumBits) inline
Definition at line 379 of file BitstreamReader.h.
References Read().
Referenced by EnterSubBlock(), ReadAbbrevRecord(), readRecord(), ReadSubBlockID(), SkipBlock(), and skipRecord().
ReadVBR64()
uint64_t llvm::BitstreamCursor::ReadVBR64 (unsigned NumBits) inline
Definition at line 399 of file BitstreamReader.h.
References Read().
Referenced by readAbbreviatedField(), ReadAbbrevRecord(), readRecord(), skipAbbreviatedField(), and skipRecord().
SkipBlock()
bool llvm::BitstreamCursor::SkipBlock () inline
Having read the ENTER_SUBBLOCK abbrevid and a BlockID, skip over the body of this block. If the block record is malformed, return true.
Definition at line 447 of file BitstreamReader.h.
References AtEndOfStream(), llvm::bitc::BlockSizeWidth, canSkipToPos(), llvm::bitc::CodeLenWidth, GetCurrentBitNo(), JumpToBit(), Read(), and ReadVBR().
Referenced by advanceSkippingSubblocks(), and ReadBlockInfoBlock().
skipRecord()
void BitstreamCursor::skipRecord (unsigned AbbrevID)
Read the current record and discard it.
skipRecord - Read the current record and discard it.
Definition at line 96 of file BitstreamReader.cpp.
References llvm::BitCodeAbbrevOp::Array, llvm::BitCodeAbbrevOp::Blob, canSkipToPos(), getAbbrev(), GetCurrentBitNo(), llvm::BitCodeAbbrevOp::getEncoding(), llvm::BitCodeAbbrev::getNumOperandInfos(), llvm::BitCodeAbbrev::getOperandInfo(), llvm::BitCodeAbbrevOp::isLiteral(), JumpToBit(), ReadVBR(), ReadVBR64(), skipAbbreviatedField(), and llvm::bitc::UNABBREV_RECORD.
Friends And Related Symbol Documentation
Deserializer
friend class Deserializer friend
Definition at line 167 of file BitstreamReader.h.
References Deserializer.
Referenced by Deserializer.
The documentation for this class was generated from the following files:
BitstreamReader.h
BitstreamReader.cpp