LLVM: llvm::SCEVCommutativeExpr Class Reference
LLVM API Documentation
llvm::SCEVCommutativeExpr Class Reference
#include <ScalarEvolutionExpressions.h>
Public Member Functions
void setNoWrapFlags (NoWrapFlags Flags)
Set flags for a non-recurrence without clearing previously set flags.
Public Member Functions inherited from llvm::SCEVNAryExpr
size_t getNumOperands () const
const SCEV * getOperand (unsigned i) const
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
Type * getType () const
NoWrapFlags getNoWrapFlags (NoWrapFlags Mask=NoWrapMask) const
Public Member Functions inherited from llvm::SCEV
SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy)
unsigned getSCEVType () const
Type * getType () const
bool isZero () const
bool isOne () const
bool isAllOnesValue () const
bool isNonConstantNegative () const
void print (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::SCEVNAryExpr
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
SCEVCommutativeExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const *O, size_t N)
Protected Member Functions inherited from llvm::SCEVNAryExpr
SCEVNAryExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const *O, size_t N)
Additional Inherited Members
Public Types inherited from llvm::SCEVNAryExpr
typedef const SCEV *const * op_iterator
typedef iterator_range< op_iterator > op_range
Public Types inherited from llvm::SCEV
enum NoWrapFlags {
FlagAnyWrap = 0 , FlagNW = (1 << 0) , FlagNUW = (1 << 1) , FlagNSW = (1 << 2) ,
NoWrapMask = (1 << 3) -1
}
Protected Attributes inherited from llvm::SCEVNAryExpr
const SCEV *const * Operands
size_t NumOperands
Protected Attributes inherited from llvm::SCEV
unsigned short SubclassData
Detailed Description
SCEVCommutativeExpr - This node is the base class for n'ary commutative operators.
Definition at line 182 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVCommutativeExpr()
llvm::SCEVCommutativeExpr::SCEVCommutativeExpr (const FoldingSetNodeIDRef ID, enum SCEVTypes T, const SCEV *const * O, size_t N) inline protected
Definition at line 184 of file ScalarEvolutionExpressions.h.
References N, llvm::SCEVNAryExpr::SCEVNAryExpr(), and T.
Referenced by llvm::SCEVAddExpr::ScalarEvolution, llvm::SCEVMulExpr::ScalarEvolution, llvm::SCEVSMaxExpr::ScalarEvolution, and llvm::SCEVUMaxExpr::ScalarEvolution.
Member Function Documentation
classof()
bool llvm::SCEVCommutativeExpr::classof (const SCEV * S) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 190 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), llvm::scAddExpr, llvm::scMulExpr, llvm::scSMaxExpr, and llvm::scUMaxExpr.
setNoWrapFlags()
void llvm::SCEVCommutativeExpr::setNoWrapFlags (NoWrapFlags Flags) inline
Set flags for a non-recurrence without clearing previously set flags.
Definition at line 198 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::SubclassData.
Referenced by llvm::ScalarEvolution::getAddExpr(), and llvm::ScalarEvolution::getMulExpr().
The documentation for this class was generated from the following file:
ScalarEvolutionExpressions.h