LLVM: llvm::yaml::AliasNode Class Reference
LLVM API Documentation
llvm::yaml::AliasNode Class Reference
Represents an alias to a Node with an anchor.
#include <YAMLParser.h>
Public Member Functions
AliasNode (std::unique_ptr< Document > &D, StringRef Val)
StringRef getName () const
Node * getTarget ()
Public Member Functions inherited from llvm::yaml::Node
Node (unsigned int Type, std::unique_ptr< Document > &, StringRef Anchor, StringRef Tag)
StringRef getAnchor () const
Get the value of the anchor attached to this node. If it does not have one, getAnchor().size() will be 0.
StringRef getRawTag () const
Get the tag as it was written in the document. This does not perform tag resolution.
std::string getVerbatimTag () const
Get the verbatium tag for a given Node. This performs tag resoluton and substitution.
SMRange getSourceRange () const
void setSourceRange (SMRange SR)
Token & peekNext ()
Token getNext ()
Node * parseBlockNode ()
BumpPtrAllocator & getAllocator ()
void setError (const Twine &Message, Token &Location) const
bool failed () const
virtual void skip ()
unsigned int getType () const
void * operator new (size_t Size, BumpPtrAllocator &Alloc, size_t Alignment=16) throw ()
void operator delete (void *Ptr, BumpPtrAllocator &Alloc, size_t Size) throw ()
Static Public Member Functions
static bool classof (const Node *N)
Additional Inherited Members
Public Types inherited from llvm::yaml::Node
enum NodeKind {
NK_Null , NK_Scalar , NK_KeyValue , NK_Mapping ,
NK_Sequence , NK_Alias
}
Protected Member Functions inherited from llvm::yaml::Node
void operator delete (void *) throw ()
virtual ~Node ()
Protected Attributes inherited from llvm::yaml::Node
std::unique_ptr< Document > & Doc
SMRange SourceRange
Detailed Description
Represents an alias to a Node with an anchor.
Example: *AnchorName
Definition at line 443 of file YAMLParser.h.
Constructor & Destructor Documentation
AliasNode()
llvm::yaml::AliasNode::AliasNode (std::unique_ptr< Document > & D, StringRef Val) inline
Definition at line 447 of file YAMLParser.h.
References llvm::yaml::Node::NK_Alias, and llvm::yaml::Node::Node().
Member Function Documentation
classof()
bool llvm::yaml::AliasNode::classof (const Node * N) inline static
Definition at line 453 of file YAMLParser.h.
References N, llvm::yaml::Node::NK_Alias, and llvm::yaml::Node::Node().
getName()
StringRef llvm::yaml::AliasNode::getName () const inline
Definition at line 450 of file YAMLParser.h.
getTarget()
Node * llvm::yaml::AliasNode::getTarget ()
References llvm::yaml::Node::Node().
The documentation for this class was generated from the following files:
YAMLParser.h
YAMLParser.cpp