LLVM: llvm::sys::path::const_iterator Class Reference
LLVM API Documentation
llvm::sys::path::const_iterator Class Reference
Path iterator.
#include <Path.h>
Public Member Functions
reference operator* () const
pointer operator-> () const
const_iterator & operator++ ()
const_iterator & operator++ (int)
bool operator== (const const_iterator &RHS) const
bool operator!= (const const_iterator &RHS) const
ptrdiff_t operator- (const const_iterator &RHS) const
Difference in bytes between this and RHS.
Friends
const_iterator begin (StringRef path)
Get begin iterator over path.
const_iterator end (StringRef path)
Get end iterator over path.
Detailed Description
Path iterator.
This is an input iterator that iterates over the individual components in path. The traversal order is as follows:
The root-name element, if present.
The root-directory element, if present.
Each successive filename element, if present.
Dot, if one or more trailing non-root slash characters are present. Traversing backwards is possible with reverse_iterator
Iteration examples. Each component is separated by ',':
/          => /
/foo       => /,foo
foo/       => foo,.
/foo/bar   => /,foo,bar
../        => ..,.
C:\foo\bar => C:,/,foo,bar
Definition at line 50 of file Path.h.
Member Function Documentation
operator!=()
bool llvm::sys::path::const_iterator::operator!= (const const_iterator & RHS) const inline
Definition at line 66 of file Path.h.
operator*()
reference llvm::sys::path::const_iterator::operator* () const inline
Definition at line 61 of file Path.h.
operator++() [1/2]
const_iterator & llvm::sys::path::const_iterator::operator++ ()
Definition at line 255 of file Path.cpp.
References llvm::sys::path::is_separator().
operator++() [2/2]
const_iterator & llvm::sys::path::const_iterator::operator++ (int)
operator-()
ptrdiff_t llvm::sys::path::const_iterator::operator- (const const_iterator & RHS) const
Difference in bytes between this and RHS.
Definition at line 312 of file Path.cpp.
operator->()
pointer llvm::sys::path::const_iterator::operator-> () const inline
Definition at line 62 of file Path.h.
operator==()
bool llvm::sys::path::const_iterator::operator== (const const_iterator & RHS) const
Definition at line 308 of file Path.cpp.
References llvm::StringRef::begin().
Friends And Related Symbol Documentation
begin
const_iterator begin (StringRef path) friend
Get begin iterator over path.
Parameters
path Input path.
Returns
Iterator initialized with the first component of path.
Definition at line 240 of file Path.cpp.
Referenced by llvm::DWARFDebugAranges::findAddress().
end
const_iterator end (StringRef path) friend
Get end iterator over path.
Parameters
path Input path.
Returns
Iterator initialized to the end of path.
Definition at line 248 of file Path.cpp.
Referenced by llvm::opt::OptTable::PrintHelp().
The documentation for this class was generated from the following files:
Path.h
Path.cpp