LLVM: llvm::MCExpr Class Reference
LLVM API Documentation
llvm::MCExpr Class Reference
#include <MCExpr.h>
Public Types
enum ExprKind {
Binary , Constant , SymbolRef , Unary ,
Target
}
Public Member Functions
Accessors
ExprKind getKind () const
Utility Methods
void print (raw_ostream &OS) const
void dump () const
Expression Evaluation
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
bool EvaluateAsAbsolute (int64_t &Res) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
int64_t evaluateKnownAbsolute (const MCAsmLayout &Layout) const
bool EvaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
bool EvaluateAsValue (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
const MCSection * FindAssociatedSection () const
Protected Member Functions
MCExpr (ExprKind _Kind)
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet, bool ForceVarExpansion) const
Detailed Description
MCExpr - Base class for the full range of assembler expressions which are needed for parsing.
Definition at line 34 of file MCExpr.h.
Member Enumeration Documentation
ExprKind
enum llvm::MCExpr::ExprKind
Enumerator
Binary
Binary expressions.
Constant
Constant expressions.
SymbolRef
References to labels and assigned expressions.
Unary
Unary expressions.
Target
Target specific expression.
Definition at line 36 of file MCExpr.h.
Constructor & Destructor Documentation
MCExpr()
llvm::MCExpr::MCExpr (ExprKind _Kind) inline explicit protected
Definition at line 59 of file MCExpr.h.
Member Function Documentation
dump()
void MCExpr::dump () const
Definition at line 125 of file MCExpr.cpp.
References llvm::dbgs(), and print().
EvaluateAsAbsolute() [1/4]
bool MCExpr::EvaluateAsAbsolute (int64_t & Res) const
Definition at line 388 of file MCExpr.cpp.
EvaluateAsAbsolute() [2/4]
bool MCExpr::EvaluateAsAbsolute (int64_t & Res, const MCAsmLayout & Layout) const
Definition at line 392 of file MCExpr.cpp.
References llvm::MCAsmLayout::getAssembler().
EvaluateAsAbsolute() [3/4]
bool MCExpr::EvaluateAsAbsolute (int64_t & Res, const MCAsmLayout & Layout, const SectionAddrMap & Addrs) const
EvaluateAsAbsolute - Try to evaluate the expression to an absolute value.
Parameters
Res - The absolute value, if evaluation succeeds.
Layout - The assembler layout object to use for evaluating symbol values. If not given, then only non-symbolic expressions will be evaluated.
Returns
- True on success.
Definition at line 397 of file MCExpr.cpp.
References llvm::MCAsmLayout::getAssembler().
Referenced by llvm::AArch64InstPrinter::printAlignedLabel(), llvm::X86ATTInstPrinter::printPCRelImm(), and llvm::X86IntelInstPrinter::printPCRelImm().
EvaluateAsAbsolute() [4/4]
bool MCExpr::EvaluateAsAbsolute (int64_t & Res, const MCAssembler & Asm) const
Definition at line 403 of file MCExpr.cpp.
EvaluateAsRelocatable()
bool MCExpr::EvaluateAsRelocatable (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const
EvaluateAsRelocatable - Try to evaluate the expression to a relocatable value, i.e. an expression of the fixed form (a - b + constant).
Parameters
Res - The relocatable value, if evaluation succeeds.
Layout - The assembler layout object to use for evaluating values.
Fixup - The Fixup object if available.
Returns
- True on success.
Definition at line 585 of file MCExpr.cpp.
References EvaluateAsRelocatableImpl(), and llvm::MCAsmLayout::getAssembler().
Referenced by evaluate(), llvm::PPCMCExpr::EvaluateAsConstant(), llvm::AArch64MCExpr::EvaluateAsRelocatableImpl(), llvm::MipsMCExpr::EvaluateAsRelocatableImpl(), llvm::PPCMCExpr::EvaluateAsRelocatableImpl(), llvm::SparcMCExpr::EvaluateAsRelocatableImpl(), llvm::MachObjectWriter::getSymbolAddress(), and llvm::MachObjectWriter::markAbsoluteVariableSymbols().
EvaluateAsRelocatableImpl()
bool MCExpr::EvaluateAsRelocatableImpl (MCValue & Res, const MCAssembler * Asm, const MCAsmLayout * Layout, const MCFixup * Fixup, const SectionAddrMap * Addrs, bool InSet, bool ForceVarExpansion) const protected
-(a - b + const) ==> (b - a - const)
Definition at line 600 of file MCExpr.cpp.
References llvm::MCBinaryExpr::Add, llvm::MCBinaryExpr::And, Binary, llvm::cast(), Constant, llvm::MCBinaryExpr::Div, llvm::MCBinaryExpr::EQ, EvaluateAsRelocatableImpl(), EvaluateSymbolicAdd(), llvm::MCValue::get(), llvm::MCValue::getConstant(), getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getOpcode(), llvm::MCUnaryExpr::getOpcode(), llvm::MCBinaryExpr::getRHS(), llvm::MCUnaryExpr::getSubExpr(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbol::getVariableValue(), llvm::MCBinaryExpr::GT, llvm::MCBinaryExpr::GTE, llvm::MCSymbolRefExpr::hasSubsectionsViaSymbols(), llvm::MCValue::isAbsolute(), llvm::MCSymbol::isVariable(), llvm::MCBinaryExpr::LAnd, llvm_unreachable, llvm::MCUnaryExpr::LNot, llvm::MCBinaryExpr::LOr, llvm::MCBinaryExpr::LT, llvm::MCBinaryExpr::LTE, llvm::MCUnaryExpr::Minus, llvm::MCBinaryExpr::Mod, llvm::MCBinaryExpr::Mul, llvm::MCBinaryExpr::NE, llvm::MCUnaryExpr::Not, llvm::MCBinaryExpr::Or, llvm::MCUnaryExpr::Plus, llvm::MCBinaryExpr::Shl, llvm::MCBinaryExpr::Shr, llvm::MCBinaryExpr::Sub, SymbolRef, Target, Unary, llvm::MCSymbolRefExpr::VK_None, and llvm::MCBinaryExpr::Xor.
Referenced by EvaluateAsRelocatable(), EvaluateAsRelocatableImpl(), and EvaluateAsValue().
EvaluateAsValue()
bool MCExpr::EvaluateAsValue (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
This is a more aggressive variant of EvaluateAsRelocatable. The intended use is for when relocations are not available, like the symbol value in the symbol table.
Definition at line 593 of file MCExpr.cpp.
References EvaluateAsRelocatableImpl(), and llvm::MCAsmLayout::getAssembler().
Referenced by evaluate(), llvm::MCAsmLayout::getBaseSymbol(), and getSymbolOffsetImpl().
evaluateKnownAbsolute()
int64_t MCExpr::evaluateKnownAbsolute (const MCAsmLayout & Layout) const
Definition at line 407 of file MCExpr.cpp.
References llvm::MCAsmLayout::getAssembler().
FindAssociatedSection()
const MCSection * MCExpr::FindAssociatedSection () const
FindAssociatedSection - Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Definition at line 752 of file MCExpr.cpp.
References Binary, llvm::cast(), Constant, FindAssociatedSection(), getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbol::getSection(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbol::isDefined(), llvm_unreachable, SymbolRef, Target, and Unary.
Referenced by llvm::ARMMCExpr::FindAssociatedSection(), FindAssociatedSection(), llvm::MipsMCExpr::FindAssociatedSection(), llvm::PPCMCExpr::FindAssociatedSection(), and llvm::SparcMCExpr::FindAssociatedSection().
getKind()
ExprKind llvm::MCExpr::getKind () const inline
Definition at line 71 of file MCExpr.h.
Referenced by llvm::AArch64MCExpr::classof(), llvm::ARMMCExpr::classof(), llvm::MCBinaryExpr::classof(), llvm::MCConstantExpr::classof(), llvm::MCSymbolRefExpr::classof(), llvm::MCTargetExpr::classof(), llvm::MCUnaryExpr::classof(), llvm::MipsMCExpr::classof(), llvm::NVPTXFloatMCExpr::classof(), llvm::PPCMCExpr::classof(), llvm::SparcMCExpr::classof(), EvaluateAsRelocatableImpl(), EvaluateCRExpr(), FindAssociatedSection(), fixELFSymbolsInTLSFixupsImpl(), fixELFSymbolsInTLSFixupsImpl(), getAccessVariant(), hasGOTReference(), HasSecRelSymbolRef(), print(), llvm::ARMInstPrinter::printOperand(), StartsWithGlobalOffsetTable(), and llvm::MCStreamer::visitUsedExpr().
print()
void MCExpr::print (raw_ostream & OS) const
Definition at line 33 of file MCExpr.cpp.
References llvm::MCBinaryExpr::Add, llvm::MCBinaryExpr::And, Binary, llvm::cast(), Constant, llvm::MCBinaryExpr::Div, llvm::dyn_cast(), llvm::MCBinaryExpr::EQ, getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCSymbol::getName(), llvm::MCBinaryExpr::getOpcode(), llvm::MCUnaryExpr::getOpcode(), llvm::MCBinaryExpr::getRHS(), llvm::MCUnaryExpr::getSubExpr(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCBinaryExpr::GT, llvm::MCBinaryExpr::GTE, llvm::isa(), llvm::MCBinaryExpr::LAnd, llvm_unreachable, llvm::MCUnaryExpr::LNot, llvm::MCBinaryExpr::LOr, llvm::MCBinaryExpr::LT, llvm::MCBinaryExpr::LTE, llvm::MCUnaryExpr::Minus, llvm::MCBinaryExpr::Mod, llvm::MCBinaryExpr::Mul, llvm::MCBinaryExpr::NE, llvm::MCUnaryExpr::Not, llvm::MCBinaryExpr::Or, llvm::MCUnaryExpr::Plus, llvm::MCSymbolRefExpr::printVariantKind(), llvm::MCBinaryExpr::Shl, llvm::MCBinaryExpr::Shr, llvm::MCBinaryExpr::Sub, SymbolRef, Target, Unary, llvm::MCSymbolRefExpr::VK_None, and llvm::MCBinaryExpr::Xor.
Referenced by dump(), llvm::operator<<(), llvm::MCValue::print(), llvm::PPCMCExpr::PrintImpl(), and llvm::SparcInstPrinter::printOperand().
The documentation for this class was generated from the following files:
MCExpr.h
MCExpr.cpp