LLVM: llvm::VarListElementInit Class Reference
LLVM API Documentation
llvm::VarListElementInit Class Reference
#include <Record.h>
Public Member Functions
Init * convertInitializerTo (RecTy *Ty) const override
TypedInit * getVariable () const
unsigned getElementNum () const
Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const override
std::string getAsString () const override
getAsString - Convert this value to a string form.
Init * resolveReferences (Record &R, const RecordVal *RV) const override
Init * getBit (unsigned Bit) const override
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const override
Init * convertInitListSlice (const std::vector< unsigned > &Elements) const override
RecTy * getFieldType (const std::string &FieldName) const override
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static VarListElementInit * get (TypedInit *T, unsigned E)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit , IK_FirstTypedInit , IK_BitsInit , IK_DagInit ,
IK_DefInit , IK_FieldInit , IK_IntInit , IK_ListInit ,
IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit , IK_UnOpInit ,
IK_LastOpInit , IK_StringInit , IK_VarInit , IK_VarListElementInit ,
IK_LastTypedInit , IK_UnsetInit , IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
VarListElementInit - List[4] - Represent access to one element of a var or field.
Definition at line 1141 of file Record.h.
Member Function Documentation
classof()
bool llvm::VarListElementInit::classof (const Init * I) inline static
Definition at line 1157 of file Record.h.
References I, and llvm::Init::IK_VarListElementInit.
convertInitializerTo()
Init * llvm::VarListElementInit::convertInitializerTo (RecTy * Ty) const inline override virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 1162 of file Record.h.
get()
VarListElementInit * VarListElementInit::get (TypedInit * T, unsigned E) static
Definition at line 1437 of file Record.cpp.
References I.
Referenced by llvm::TypedInit::convertInitListSlice(), llvm::OpInit::resolveListElementReference(), and llvm::VarInit::resolveListElementReference().
getAsString()
std::string VarListElementInit::getAsString () const override virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 1451 of file Record.cpp.
References llvm::utostr().
getBit()
Init * VarListElementInit::getBit (unsigned Bit) const override virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1463 of file Record.cpp.
References llvm::BitRecTy::get(), llvm::VarBitInit::get(), and llvm::TypedInit::getType().
getElementNum()
unsigned llvm::VarListElementInit::getElementNum () const inline
Definition at line 1167 of file Record.h.
Referenced by resolveReferences().
getVariable()
TypedInit * llvm::VarListElementInit::getVariable () const inline
Definition at line 1166 of file Record.h.
Referenced by resolveReferences().
resolveListElementReference()
Init * VarListElementInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const override virtual
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences. If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 1469 of file Record.cpp.
References llvm::dyn_cast().
Referenced by resolveReferences().
resolveReferences()
Init * VarListElementInit::resolveReferences (Record & R, const RecordVal * RV) const override virtual
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1456 of file Record.cpp.
References getElementNum(), getVariable(), I, and resolveListElementReference().
The documentation for this class was generated from the following files:
Record.h
Record.cpp