LLVM: llvm::ModuleAnalysisManagerFunctionProxy Class Reference
LLVM API Documentation
llvm::ModuleAnalysisManagerFunctionProxy Class Reference
A function analysis which acts as a proxy for a module analysis manager.
#include <PassManager.h>
Classes
class Result
Result proxy object for ModuleAnalysisManagerFunctionProxy.
Public Member Functions
ModuleAnalysisManagerFunctionProxy (const ModuleAnalysisManager &MAM)
ModuleAnalysisManagerFunctionProxy (const ModuleAnalysisManagerFunctionProxy &Arg)
ModuleAnalysisManagerFunctionProxy (ModuleAnalysisManagerFunctionProxy &&Arg)
ModuleAnalysisManagerFunctionProxy & operator= (ModuleAnalysisManagerFunctionProxy RHS)
Result run (Function &)
Run the analysis pass and create our proxy result object. Nothing to see here, it just forwards the MAM reference into the result.
Static Public Member Functions
static void * ID ()
static StringRef name ()
Detailed Description
A function analysis which acts as a proxy for a module analysis manager.
This primarily provides an accessor to a parent module analysis manager to function passes. Only the const interface of the module analysis manager is provided to indicate that once inside of a function analysis pass you cannot request a module analysis to actually run. Instead, the user must rely on the getCachedResult API.
This proxy doesn't manage the invalidation in any way. That is handled by the recursive return path of each layer of the pass manager and the returned PreservedAnalysis set.
Definition at line 681 of file IR/PassManager.h.
Constructor & Destructor Documentation
ModuleAnalysisManagerFunctionProxy() [1/3]
llvm::ModuleAnalysisManagerFunctionProxy::ModuleAnalysisManagerFunctionProxy (const ModuleAnalysisManager & MAM) inline
Definition at line 709 of file IR/PassManager.h.
Referenced by ModuleAnalysisManagerFunctionProxy(), ModuleAnalysisManagerFunctionProxy(), and operator=().
ModuleAnalysisManagerFunctionProxy() [2/3]
llvm::ModuleAnalysisManagerFunctionProxy::ModuleAnalysisManagerFunctionProxy (const ModuleAnalysisManagerFunctionProxy & Arg) inline
Definition at line 713 of file IR/PassManager.h.
References ModuleAnalysisManagerFunctionProxy().
ModuleAnalysisManagerFunctionProxy() [3/3]
llvm::ModuleAnalysisManagerFunctionProxy::ModuleAnalysisManagerFunctionProxy (ModuleAnalysisManagerFunctionProxy && Arg) inline
Definition at line 716 of file IR/PassManager.h.
References ModuleAnalysisManagerFunctionProxy().
Member Function Documentation
ID()
void * llvm::ModuleAnalysisManagerFunctionProxy::ID () inline static
Definition at line 705 of file IR/PassManager.h.
name()
StringRef llvm::ModuleAnalysisManagerFunctionProxy::name () inline static
Definition at line 707 of file IR/PassManager.h.
operator=()
ModuleAnalysisManagerFunctionProxy & llvm::ModuleAnalysisManagerFunctionProxy::operator= (ModuleAnalysisManagerFunctionProxy RHS) inline
Definition at line 719 of file IR/PassManager.h.
References ModuleAnalysisManagerFunctionProxy(), and std::swap().
run()
Result llvm::ModuleAnalysisManagerFunctionProxy::run (Function &) inline
Run the analysis pass and create our proxy result object. Nothing to see here, it just forwards the MAM reference into the result.
Definition at line 727 of file IR/PassManager.h.
The documentation for this class was generated from the following files:
IR/PassManager.h
PassManager.cpp