LLVM: llvm::ThumbTargetMachine Class Reference
LLVM API Documentation
llvm::ThumbTargetMachine Class Reference
#include <ARMTargetMachine.h>
Public Member Functions
ThumbTargetMachine (const Target &T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool isLittle)
Public Member Functions inherited from llvm::ARMBaseTargetMachine
ARMBaseTargetMachine (const Target &T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool isLittle)
~ARMBaseTargetMachine () override
const ARMSubtarget * getSubtargetImpl () const override
const ARMSubtarget * getSubtargetImpl (const Function &F) const override
void addAnalysisPasses (PassManagerBase &PM) override
Register ARM analysis passes with a pass manager.
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
TargetLoweringObjectFile * getObjFileLowering () const override
Public Member Functions inherited from llvm::LLVMTargetMachine
void addAnalysisPasses (PassManagerBase &PM) override
Register analysis passes for this target with a pass manager.
bool addPassesToEmitFile (PassManagerBase &PM, formatted_raw_ostream &Out, CodeGenFileType FileType, bool DisableVerify=true, AnalysisID StartAfter=nullptr, AnalysisID StopAfter=nullptr) override
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_ostream &OS, bool DisableVerify=true) override
Public Member Functions inherited from llvm::TargetMachine
virtual ~TargetMachine ()
const Target & getTarget () const
StringRef getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
template<typename STC>
const STC & getSubtarget () const
template<typename STC>
const STC & getSubtarget (const Function *) const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
CodeModel::Model getCodeModel () const
TLSModel::Model getTLSModel (const GlobalValue *GV) const
CodeGenOpt::Level getOptLevel () const
void setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
void setFastISel (bool Enable)
bool shouldPrintMachineCode () const
bool getAsmVerbosityDefault () const
void setAsmVerbosityDefault (bool)
bool getDataSections () const
bool getFunctionSections () const
void setDataSections (bool)
setDataSections - Set if the data are emit into separate sections.
void setFunctionSections (bool)
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV, Mangler &Mang) const
Additional Inherited Members
Public Types inherited from llvm::ARMBaseTargetMachine
enum ARMABI { ARM_ABI_UNKNOWN , ARM_ABI_APCS , ARM_ABI_AAPCS }
Public Types inherited from llvm::TargetMachine
enum CodeGenFileType { CGFT_AssemblyFile , CGFT_ObjectFile , CGFT_Null }
Public Attributes inherited from llvm::ARMBaseTargetMachine
enum llvm::ARMBaseTargetMachine::ARMABI TargetABI
Public Attributes inherited from llvm::TargetMachine
TargetOptions Options
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::ARMBaseTargetMachine
std::unique_ptr< TargetLoweringObjectFile > TLOF
ARMSubtarget Subtarget
bool isLittle
StringMap< std::unique_ptr< ARMSubtarget > > SubtargetMap
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
TheTarget - The Target that this machine was created for.
std::string TargetTriple
std::string TargetCPU
std::string TargetFS
MCCodeGenInfo * CodeGenInfo
const MCAsmInfo * AsmInfo
unsigned RequireStructuredCFG: 1
Detailed Description
ThumbTargetMachine - Thumb target machine. Due to the way architectures are handled, this represents both Thumb-1 and Thumb-2.
Definition at line 96 of file ARMTargetMachine.h.
Constructor & Destructor Documentation
ThumbTargetMachine()
ThumbTargetMachine::ThumbTargetMachine (const Target & T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool isLittle)
Definition at line 207 of file ARMTargetMachine.cpp.
References llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::ARMBaseTargetMachine::isLittle, and llvm::TargetMachine::Options.
Referenced by llvm::ThumbBETargetMachine::ThumbBETargetMachine(), and llvm::ThumbLETargetMachine::ThumbLETargetMachine().
The documentation for this class was generated from the following files:
ARMTargetMachine.h
ARMTargetMachine.cpp