LLVM: llvm::ForwardControlFlowIntegrity Class Reference
LLVM API Documentation
llvm::ForwardControlFlowIntegrity Class Reference
#include <ForwardControlFlowIntegrity.h>
Public Member Functions
ForwardControlFlowIntegrity ()
ForwardControlFlowIntegrity (JumpTable::JumpTableType JTT, CFIntegrity CFIType, bool CFIEnforcing, std::string CFIFuncName)
~ForwardControlFlowIntegrity () override
bool runOnModule (Module &M) override
const char * getPassName () const override
void getAnalysisUsage (AnalysisUsage &AU) const override
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
ForwardControlFlowIntegrity uses the information from JumpInstrTableInfo to prepend checks to indirect calls to make sure that these calls target valid locations.
Definition at line 36 of file ForwardControlFlowIntegrity.h.
Constructor & Destructor Documentation
ForwardControlFlowIntegrity() [1/2]
ForwardControlFlowIntegrity::ForwardControlFlowIntegrity ()
Definition at line 85 of file ForwardControlFlowIntegrity.cpp.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::initializeForwardControlFlowIntegrityPass(), llvm::ModulePass::ModulePass(), and llvm::Sub.
ForwardControlFlowIntegrity() [2/2]
ForwardControlFlowIntegrity::ForwardControlFlowIntegrity (JumpTable::JumpTableType JTT, CFIntegrity CFIType, bool CFIEnforcing, std::string CFIFuncName)
Definition at line 91 of file ForwardControlFlowIntegrity.cpp.
References llvm::PassRegistry::getPassRegistry(), ID, llvm::initializeForwardControlFlowIntegrityPass(), and llvm::ModulePass::ModulePass().
~ForwardControlFlowIntegrity()
ForwardControlFlowIntegrity::~ForwardControlFlowIntegrity () override
Definition at line 99 of file ForwardControlFlowIntegrity.cpp.
Member Function Documentation
getAnalysisUsage()
void ForwardControlFlowIntegrity::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 101 of file ForwardControlFlowIntegrity.cpp.
References llvm::AnalysisUsage::addRequired().
getPassName()
const char * llvm::ForwardControlFlowIntegrity::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 49 of file ForwardControlFlowIntegrity.h.
runOnModule()
bool ForwardControlFlowIntegrity::runOnModule (Module & M) override virtual
Runs the CFI pass on a given module. This works best if the module in question is the result of link-time optimization (see lib/LTO).
Implements llvm::ModulePass.
Definition at line 174 of file ForwardControlFlowIntegrity.cpp.
References llvm::Function::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::JumpInstrTableInfo::entryByteAlignment(), llvm::ConstantInt::get(), llvm::Pass::getAnalysis(), llvm::ConstantExpr::getBitCast(), llvm::Module::getContext(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), llvm::JumpInstrTableInfo::getTables(), llvm::Log2_64(), and llvm::NextPowerOf2().
Member Data Documentation
ID
char ForwardControlFlowIntegrity::ID = 0 static
Definition at line 38 of file ForwardControlFlowIntegrity.h.
Referenced by ForwardControlFlowIntegrity(), ForwardControlFlowIntegrity(), and STATISTIC().
The documentation for this class was generated from the following files:
ForwardControlFlowIntegrity.h
ForwardControlFlowIntegrity.cpp