LLVM: llvm::BitstreamReader Class Reference
LLVM API Documentation
llvm::BitstreamReader Class Reference
#include <BitstreamReader.h>
Classes
struct BlockInfo
Public Member Functions
BitstreamReader ()
BitstreamReader (const unsigned char *Start, const unsigned char *End)
BitstreamReader (std::unique_ptr< MemoryObject > BitcodeBytes)
BitstreamReader (BitstreamReader &&Other)
BitstreamReader & operator= (BitstreamReader &&Other)
void init (const unsigned char *Start, const unsigned char *End)
MemoryObject & getBitcodeBytes ()
void CollectBlockInfoNames ()
This is called by clients that want block/record name information.
bool isIgnoringBlockInfoNames ()
bool hasBlockInfoRecords () const
const BlockInfo * getBlockInfo (unsigned BlockID) const
BlockInfo & getOrCreateBlockInfo (unsigned BlockID)
void takeBlockInfo (BitstreamReader &&Other)
Detailed Description
This class is used to read from an LLVM bitcode stream, maintaining information that is global to decoding the entire file. While a file is being read, multiple cursors can be independently advanced or skipped around within the file. These are represented by the BitstreamCursor class.
Definition at line 33 of file BitstreamReader.h.
Constructor & Destructor Documentation
BitstreamReader() [1/4]
llvm::BitstreamReader::BitstreamReader () inline
Definition at line 56 of file BitstreamReader.h.
References true.
BitstreamReader() [2/4]
llvm::BitstreamReader::BitstreamReader (const unsigned char * Start, const unsigned char * End) inline
Definition at line 59 of file BitstreamReader.h.
References init(), and true.
BitstreamReader() [3/4]
llvm::BitstreamReader::BitstreamReader (std::unique_ptr< MemoryObject > BitcodeBytes) inline
Definition at line 64 of file BitstreamReader.h.
References true.
BitstreamReader() [4/4]
llvm::BitstreamReader::BitstreamReader (BitstreamReader && Other) inline
Definition at line 67 of file BitstreamReader.h.
Member Function Documentation
CollectBlockInfoNames()
void llvm::BitstreamReader::CollectBlockInfoNames () inline
This is called by clients that want block/record name information.
Definition at line 87 of file BitstreamReader.h.
getBitcodeBytes()
MemoryObject & llvm::BitstreamReader::getBitcodeBytes () inline
Definition at line 84 of file BitstreamReader.h.
getBlockInfo()
const BlockInfo * llvm::BitstreamReader::getBlockInfo (unsigned BlockID) const inline
If there is block info for the specified ID, return it, otherwise return null.
Definition at line 101 of file BitstreamReader.h.
Referenced by getOrCreateBlockInfo().
getOrCreateBlockInfo()
BlockInfo & llvm::BitstreamReader::getOrCreateBlockInfo (unsigned BlockID) inline
Definition at line 113 of file BitstreamReader.h.
References llvm::BitstreamReader::BlockInfo::BlockID, and getBlockInfo().
hasBlockInfoRecords()
bool llvm::BitstreamReader::hasBlockInfoRecords () const inline
Return true if we've already read and processed the block info block for this Bitstream. We only process it for the first cursor that walks over it.
Definition at line 97 of file BitstreamReader.h.
Referenced by takeBlockInfo().
init()
void llvm::BitstreamReader::init (const unsigned char * Start, const unsigned char * End) inline
Definition at line 79 of file BitstreamReader.h.
References llvm::getNonStreamedMemoryObject().
Referenced by BitstreamReader().
isIgnoringBlockInfoNames()
bool llvm::BitstreamReader::isIgnoringBlockInfoNames () inline
Definition at line 88 of file BitstreamReader.h.
operator=()
BitstreamReader & llvm::BitstreamReader::operator= (BitstreamReader && Other) inline
Definition at line 71 of file BitstreamReader.h.
References std::swap().
takeBlockInfo()
void llvm::BitstreamReader::takeBlockInfo (BitstreamReader && Other) inline
Takes block info from the other bitstream reader.
This is a "take" operation because BlockInfo records are non-trivial, and indeed rather expensive.
Definition at line 127 of file BitstreamReader.h.
References hasBlockInfoRecords().
The documentation for this class was generated from the following file:
BitstreamReader.h