LLVM: llvm::Value Class Reference
LLVM API Documentation
llvm::Value Class Reference
LLVM Value Representation.
#include <Value.h>
Public Types
enum ValueTy {
ArgumentVal , BasicBlockVal , FunctionVal , GlobalAliasVal ,
GlobalVariableVal , UndefValueVal , BlockAddressVal , ConstantExprVal ,
ConstantAggregateZeroVal , ConstantDataArrayVal , ConstantDataVectorVal , ConstantIntVal ,
ConstantFPVal , ConstantArrayVal , ConstantStructVal , ConstantVectorVal ,
ConstantPointerNullVal , MetadataAsValueVal , InlineAsmVal , InstructionVal ,
ConstantFirstVal = FunctionVal , ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl< const User > const_user_iterator
Public Member Functions
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Static Public Attributes
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Protected Member Functions
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Friends
class ValueAsMetadata
class ValueHandleBase
Detailed Description
LLVM Value Representation.
This is a very important LLVM class. It is the base class of all values computed by a program that may be used as operands to other values. Value is the super class of other important classes such as Instruction and Function. All Values have a Type. Type is not a subclass of Value. Some values can have a name and they belong to some Module. Setting the name on the Value automatically updates the module's symbol table.
Every value has a "use list" that keeps track of which other Values are using this Value. A Value can also have an arbitrary number of ValueHandle objects that watch it and listen to RAUW and Destroy events. See llvm/IR/ValueHandle.h for details.
Definition at line 68 of file Value.h.
Member Typedef Documentation
const_use_iterator
typedef use_iterator_impl<const Use> llvm::Value::const_use_iterator
Definition at line 277 of file Value.h.
const_user_iterator
typedef user_iterator_impl<const User> llvm::Value::const_user_iterator
Definition at line 292 of file Value.h.
use_iterator
typedef use_iterator_impl<Use> llvm::Value::use_iterator
Definition at line 276 of file Value.h.
user_iterator
typedef user_iterator_impl<User> llvm::Value::user_iterator
Definition at line 291 of file Value.h.
Member Enumeration Documentation
ValueTy
enum llvm::Value::ValueTy
Concrete subclass of this.
An enumeration for keeping track of the concrete subclass of Value that is actually instantiated. Values of this enumeration are kept in the Value classes SubclassID field. They are used for concrete type identification.
Enumerator
ArgumentVal
BasicBlockVal
FunctionVal
GlobalAliasVal
GlobalVariableVal
UndefValueVal
BlockAddressVal
ConstantExprVal
ConstantAggregateZeroVal
ConstantDataArrayVal
ConstantDataVectorVal
ConstantIntVal
ConstantFPVal
ConstantArrayVal
ConstantStructVal
ConstantVectorVal
ConstantPointerNullVal
MetadataAsValueVal
InlineAsmVal
InstructionVal
ConstantFirstVal
ConstantLastVal
Definition at line 342 of file Value.h.
Constructor & Destructor Documentation
Value()
Value::Value (Type * Ty, unsigned scid) protected
Definition at line 45 of file Value.cpp.
References BasicBlockVal, checkType(), ConstantLastVal, if(), NumOperands, and SubclassOptionalData.
Referenced by ValuesOverlap().
~Value()
Value::~Value () virtual
Definition at line 60 of file Value.cpp.
References llvm::dbgs(), getName(), llvm::ValueAsMetadata::handleDeletion(), I, isUsedByMetadata(), use_begin(), use_empty(), use_end(), and llvm::ValueHandleBase::ValueIsDeleted().
Member Function Documentation
addUse()
void llvm::Value::addUse (Use & U) inline
This method should only be used by the Use class.
Definition at line 334 of file Value.h.
Referenced by llvm::Use::swap().
clearSubclassOptionalData()
void llvm::Value::clearSubclassOptionalData () inline
Clear the optional flags contained in this value.
Definition at line 393 of file Value.h.
References SubclassOptionalData.
DoPHITranslation() [1/2]
Value * Value::DoPHITranslation (const BasicBlock * CurBB, const BasicBlock * PredBB)
Translate PHI node to its predecessor from the given basic block.
If this value is a PHI node with CurBB as its parent, return the value in the PHI node corresponding to PredBB. If not, return ourself. This is useful if you want to know the value something has in a predecessor block.
Definition at line 606 of file Value.cpp.
References llvm::dyn_cast(), llvm::PHINode::getIncomingValueForBlock(), and llvm::Instruction::getParent().
Referenced by DoPHITranslation().
DoPHITranslation() [2/2]
const Value * llvm::Value::DoPHITranslation (const BasicBlock * CurBB, const BasicBlock * PredBB) const inline
Definition at line 478 of file Value.h.
References DoPHITranslation().
dump()
void Value::dump () const
Support for debugging, callable in GDB: V->dump()
Definition at line 2659 of file AsmWriter.cpp.
References llvm::dbgs(), and print().
Referenced by checkInterfaceFunction(), checkInterfaceFunction(), llvm::dumpBlock(), and tryPromoteAllocaToVector().
getContext()
LLVMContext & Value::getContext () const
All values hold a context through their type.
Definition at line 614 of file Value.cpp.
Referenced by llvm::CallInst::addAttribute(), llvm::InvokeInst::addAttribute(), AddWithOverflow(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), AnalyzeLoadFromClobberingMemInst(), AppendMDNodeToInstForPtr(), AppendMDNodeToSourcePtr(), llvm::SelectInst::areInvalidOperands(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), BitCastConstantVector(), calculateVectorIndex(), llvm::FenceInst::clone_impl(), llvm::UnreachableInst::clone_impl(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstruction(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::ARMConstantPoolConstant::Create(), CreatePrologue(), llvm::ConstantAggregateZero::destroyConstant(), llvm::ConstantDataSequential::destroyConstant(), llvm::ConstantPointerNull::destroyConstant(), llvm::UndefValue::destroyConstant(), llvm::Instruction::dropUnknownMetadata(), extractMDNode(), FitsInFPType(), llvm::FoldBranchToCommonDest(), genLoopLimit(), llvm::ConstantExpr::get(), llvm::MCAsmLayout::getBaseSymbol(), getEdgeValueLocal(), llvm::ConstantDataSequential::getElementAsConstant(), llvm::ConstantExpr::getExtractElement(), llvm::ConstantExpr::getExtractValue(), llvm::ConstantExpr::getFCmp(), getFCmpValue(), llvm::ConstantExpr::getICmp(), llvm::ConstantExpr::getInsertElement(), llvm::ConstantExpr::getInsertValue(), GetMemInstValueForLoad(), llvm::getObjectSize(), GetShiftedValue(), llvm::ConstantStruct::getTypeForElements(), IdxCompare(), llvm::InlineFunction(), llvm::CastInst::isNoopCast(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::MergeBasicBlockIntoOnlyPred(), OptimizeGlobalAddressOfMalloc(), OptimizeNoopCopyExpression(), PerformHeapAllocSRoA(), ProcessUGT_ADDCST_ADD(), llvm::CallInst::removeAttribute(), llvm::InvokeInst::removeAttribute(), ReplaceFPIntrinsicWithCall(), llvm::BlockAddress::replaceUsesOfWithOnConstant(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::ConstantVector::replaceUsesOfWithOnConstant(), ScalarizeMaskedLoad(), ScalarizeMaskedStore(), llvm::Instruction::setMetadata(), llvm::Instruction::setMetadata(), setName(), SimplifyCondBranchToCondBranch(), SimplifyICmpInst(), SimplifyTerminatorOnSelect(), llvm::SplitCriticalEdge(), SRAGlobal(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), llvm::StoreInst::StoreInst(), SubWithOverflow(), SymbolicallyEvaluateGEP(), TryToShrinkGlobalToBoolean(), upgradeGlobalArray(), llvm::UpgradeIntrinsicCall(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFree(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitIntToPtr(), llvm::InstCombiner::visitPtrToInt(), and llvm::InstCombiner::visitShuffleVectorInst().
getName()
StringRef Value::getName () const
Return a constant reference to the value's name.
This is cheap and guaranteed to return the same reference as long as the value is not modified.
Definition at line 159 of file Value.cpp.
References llvm::StringMapEntry< ValueTy >::getKey(), and getValueName().
Referenced by AddAliasScopeMetadata(), llvm::ExecutionEngine::addGlobalMapping(), AppendMDNodeToSourcePtr(), CanPropagatePredecessorsForPHIs(), llvm::CloneBasicBlock(), CloneLoopBlocks(), combineLoadToNewType(), ConstructSSAForLoadSet(), copyFunctionProto(), copyGlobalAliasProto(), copyGlobalVariableProto(), copyGVAttributes(), llvm::dumpBlock(), llvm::EmitGEPOffset(), llvm::ExecutionEngine::emitGlobals(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::ExtractTypeInfo(), llvm::InstCombiner::FoldAndOfICmps(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::InstCombiner::FoldICmpShrCst(), FoldOperationIntoSelectOperand(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldShiftByConstant(), FoldTwoEntryPHINode(), forceRenaming(), GenerateARCAnnotation(), GenerateARCBBEntranceAnnotation(), GenerateARCBBTerminatorAnnotation(), generateUnsignedDivisionCode(), getAllocationData(), llvm::bfi_detail::getBlockName(), llvm::DOTGraphTraits< const Function * >::getCompleteNodeLabel(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::MachineBasicBlock::getFullName(), GetHeapSROAValue(), llvm::InlineCostAnalysis::getInlineCost(), llvm::MachineFunction::getName(), llvm::Mangler::getNameWithPrefix(), llvm::DOTGraphTraits< BlockFrequencyInfo * >::getNodeLabel(), llvm::getSamplerName(), llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel(), llvm::getSurfaceName(), llvm::object::IRObjectFile::getSymbolFlags(), llvm::getTextureName(), HandleByValArgument(), HandleCallsInBlockInlinedThroughInvoke(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), INITIALIZE_TM_PASS(), llvm::InlineFunction(), llvm::InsertPreheaderForLoop(), insertUniqueBackedgeBlock(), llvm::isFreeCall(), llvm::Function::isIntrinsic(), isMemsetPattern16(), isReportingError(), llvm::AMDGPUMCInstLower::lower(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::maybePrintComdat(), llvm::FortifiedLibCallSimplifier::optimizeCall(), llvm::LibCallSimplifier::optimizeCall(), OptimizeGlobalAddressOfMalloc(), PerformHeapAllocSRoA(), llvm::SparseSolver::Print(), llvm::FileInfo::print(), llvm::SDNode::print_details(), llvm::AssemblyWriter::printBasicBlock(), llvm::BranchProbabilityInfo::printEdgeProbability(), llvm::object::IRObjectFile::printSymbolName(), processInstruction(), ProcessUGT_ADDCST_ADD(), llvm::LazyCallGraph::SCC::removeInterSCCEdge(), ReplaceCallWith(), ReplaceUsesOfMallocWithGlobal(), rewriteLoopExitBlock(), RewriteUsesOfClonedInstructions(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::Inliner::runOnSCC(), llvm::BranchProbabilityInfo::setEdgeWeight(), setName(), shouldInternalize(), SimplifyCondBranchToCondBranch(), simplifyOneLoop(), SinkThenElseCodeToEnd(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), speculateSelectInstLoads(), SpeculativelyExecuteBB(), llvm::SplitBlock(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), SRAGlobal(), tryFactorization(), tryToMakeAllocaBePromotable(), TryToOptimizeStoreOfMallocToGlobal(), TryToShrinkGlobalToBoolean(), llvm::UnrollLoop(), UpdatePHINodes(), llvm::UpgradeIntrinsicCall(), usedInGlobalVarDef(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInstWithCastAndCast(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSelectInst(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitZExt(), and ~Value().
getNumUses()
unsigned Value::getNumUses () const
This method computes the number of uses of this Value.
This is a linear time operation. Use hasOneUse, hasNUses, or hasNUsesOrMore to check for specific values.
Definition at line 133 of file Value.cpp.
References use_begin(), and use_end().
getRawSubclassOptionalData()
unsigned llvm::Value::getRawSubclassOptionalData () const inline
Return the raw optional flags value contained in this value.
This should only be used when testing two Values for equivalence.
Definition at line 388 of file Value.h.
References SubclassOptionalData.
getSubclassDataFromValue()
unsigned short llvm::Value::getSubclassDataFromValue () const inline protected
Definition at line 531 of file Value.h.
Referenced by llvm::Function::getCallingConv(), llvm::ConstantExpr::getOpcode(), llvm::Instruction::getSubclassDataFromInstruction(), llvm::BasicBlock::hasAddressTaken(), llvm::Function::hasPrefixData(), llvm::Function::hasPrologueData(), llvm::Function::setCallingConv(), llvm::Instruction::setInstructionSubclassData(), llvm::Function::setPrefixData(), llvm::Function::setPrologueData(), and llvm::Instruction::SymbolTableListTraits< Instruction, BasicBlock >.
getType()
Type * llvm::Value::getType () const inline
All values are typed, get the type of this value.
Definition at line 222 of file Value.h.
Referenced by llvm::AliasSetTracker::add(), llvm::AliasSetTracker::add(), llvm::PHINode::addIncoming(), AddWithOverflow(), AnalyzeLoadFromClobberingLoad(), AnalyzeLoadFromClobberingMemInst(), AnalyzeLoadFromClobberingStore(), appendToGlobalArray(), AppendTypeSuffix(), llvm::SelectInst::areInvalidOperands(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), llvm::AtomicRMWInst::AtomicRMWInst(), llvm::AtomicRMWInst::AtomicRMWInst(), llvm::BinaryConstantExpr::BinaryConstantExpr(), BitCastConstantVector(), BuildConstantFromSCEV(), buildMultiplyTree(), BuildSubAggregate(), CanCoerceMustAliasedValueToLoad(), llvm::FastISel::canFoldAddIntoGEP(), CanShareConstantPoolEntry(), llvm::CastInst::castIsValid(), llvm::CastToCStr(), llvm::AddrSpaceCastInst::clone_impl(), llvm::BitCastInst::clone_impl(), llvm::FPExtInst::clone_impl(), llvm::FPToSIInst::clone_impl(), llvm::FPToUIInst::clone_impl(), llvm::FPTruncInst::clone_impl(), llvm::IntToPtrInst::clone_impl(), llvm::PtrToIntInst::clone_impl(), llvm::SExtInst::clone_impl(), llvm::SIToFPInst::clone_impl(), llvm::TruncInst::clone_impl(), llvm::UIToFPInst::clone_impl(), llvm::VAArgInst::clone_impl(), llvm::ZExtInst::clone_impl(), llvm::CloneAndPruneFunctionInto(), CloneLoopBlocks(), CoerceAvailableValueToLoadType(), CollectShuffleElements(), CollectSingleShuffleElements(), collectUsesWithPtrTypes(), combineStoreToValueType(), llvm::InstCombiner::commonCastTransforms(), llvm::InstCombiner::commonPointerCastTransforms(), computeKnownBits(), llvm::computeOverflowForUnsignedMul(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), computePointerICmp(), ConnectProlog(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldExtractElementInstruction(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantFoldInstOperands(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), ConstructSSAForLoadSet(), convertMemSetToLoop(), ConvertShiftToMul(), convertTransferToLoop(), llvm::BinaryOperator::Create(), CreateAdd(), llvm::IRBuilder< true, TargetFolder >::CreateAlignmentAssumption(), llvm::IRBuilder< true, TargetFolder >::CreateAnd(), llvm::IRBuilder< true, TargetFolder >::CreateAnd(), createAndInstr(), llvm::IRBuilder< true, TargetFolder >::CreateAShr(), llvm::IRBuilder< true, TargetFolder >::CreateAShr(), llvm::IRBuilderBase::CreateAssumption(), llvm::CastInst::CreateBitOrPointerCast(), llvm::IRBuilder< true, TargetFolder >::CreateExtractInteger(), llvm::IRBuilderBase::CreateGCStatepoint(), llvm::IRBuilderBase::CreateGlobalString(), llvm::IRBuilder< true, TargetFolder >::CreateIsNotNull(), llvm::IRBuilder< true, TargetFolder >::CreateIsNull(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::IRBuilder< true, TargetFolder >::CreateLShr(), llvm::IRBuilder< true, TargetFolder >::CreateLShr(), createMalloc(), llvm::IRBuilderBase::CreateMaskedLoad(), llvm::IRBuilderBase::CreateMaskedStore(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), CreateMul(), CreateNeg(), llvm::IRBuilder< true, TargetFolder >::CreateOr(), llvm::IRBuilder< true, TargetFolder >::CreateOr(), llvm::InstCombiner::CreateOverflowTuple(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast(), llvm::CastInst::CreatePointerCast(), llvm::CastInst::CreatePointerCast(), createPrivateGlobalForString(), createPrivateNonConstGlobalForString(), llvm::IRBuilder< true, TargetFolder >::CreatePtrDiff(), llvm::CastInst::CreateSExtOrBitCast(), llvm::CastInst::CreateSExtOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateShl(), llvm::IRBuilder< true, TargetFolder >::CreateShl(), llvm::CastInst::CreateTruncOrBitCast(), llvm::CastInst::CreateTruncOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateXor(), llvm::IRBuilder< true, TargetFolder >::CreateXor(), llvm::CastInst::CreateZExtOrBitCast(), llvm::CastInst::CreateZExtOrBitCast(), CvtFDivConstToReciprocal(), DecomposeGEPExpression(), DecomposeSimpleLinearExpr(), DeleteInstructionInBlock(), llvm::ConstantAggregateZero::destroyConstant(), llvm::ConstantExpr::destroyConstant(), llvm::UndefValue::destroyConstant(), llvm::InstCombiner::DoOneIteration(), EliminateDeadSwitchCases(), llvm::EmitBinaryFloatFnCall(), llvm::EmitGEPOffset(), llvm::AsmPrinter::EmitGlobalConstant(), emitGlobalConstantFP(), emitGlobalConstantImpl(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::EmitStrNCpy(), llvm::EmitUnaryFloatFnCall(), llvm::ARMAsmPrinter::EmitXXStructor(), evaluateFCmpRelation(), EvaluateGEPOffsetExpression(), evaluateICmpRelation(), EvaluateStoreInto(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::X86TargetLowering::ExpandInlineAsm(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), ExtractConstantBytes(), llvm::ExtractElementConstantExpr::ExtractElementConstantExpr(), llvm::FCmpInst::FCmpInst(), llvm::FCmpInst::FCmpInst(), llvm::FCmpInst::FCmpInst(), llvm::FindAvailableLoadedValue(), findCommonType(), FindLIVLoopCondition(), FindLoopCounter(), fixupFPReturnAndCall(), llvm::InstCombiner::FoldAndOfFCmps(), llvm::InstCombiner::FoldAndOfICmps(), FoldBitCast(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), foldConstantCastPair(), llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::InstCombiner::FoldGEPICmp(), llvm::InstCombiner::FoldICmpShrCst(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmpsHelper(), llvm::InstCombiner::FoldOrOfFCmps(), FoldReinterpretLoadFromConstPtr(), llvm::InstCombiner::FoldSelectOpOp(), llvm::InstCombiner::FoldShiftByConstant(), FoldTwoEntryPHINode(), foldUDivPow2Cst(), generateSignedDivisionCode(), generateSignedRemainderCode(), generateUnsignedDivisionCode(), genLoopLimit(), llvm::gep_type_begin(), llvm::gep_type_begin(), llvm::ConstantExpr::get(), getAccessType(), llvm::IntToPtrInst::getAddressSpace(), llvm::MachinePointerInfo::getAddrSpace(), getAdjustedAlignment(), getAdjustedPtr(), llvm::Constant::getAggregateElement(), getAISize(), llvm::MemIntrinsic::getAlignmentType(), llvm::ConstantExpr::getAsInstruction(), getBinOpsForFactorization(), llvm::CastInst::getCastOpcode(), getCodeAddrSpace(), llvm::ConstantExpr::getCompare(), GetCompareTy(), llvm::ExecutionEngine::getConstantValue(), llvm::BasicBlock::getContext(), llvm::Argument::getDereferenceableBytes(), llvm::MemIntrinsic::getDestAddressSpace(), llvm::CastInst::getDestTy(), getEdgeValueLocal(), llvm::ConstantAggregateZero::getElementValue(), llvm::ConstantAggregateZero::getElementValue(), llvm::UndefValue::getElementValue(), llvm::UndefValue::getElementValue(), llvm::ConstantExpr::getExtractElement(), llvm::ConstantExpr::getExtractValue(), llvm::ConstantExpr::getFCmp(), llvm::objcarc::GetFunctionClass(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getICmp(), llvm::getICmpValue(), llvm::ConstantExpr::getInsertElement(), llvm::ConstantExpr::getInsertValue(), llvm::SCEVExpander::getIVIncOperand(), GetLinearExpression(), llvm::MemoryDependenceAnalysis::getLoadLoadClobberFullWidthSize(), GetLoadValueForLoad(), llvm::AliasAnalysis::getLocation(), llvm::AliasAnalysis::getLocation(), llvm::AliasAnalysis::getLocation(), getLogBase2Vector(), llvm::getMallocType(), GetMemInstValueForLoad(), llvm::getMergedGlobalExpr(), llvm::AliasAnalysis::getModRefInfo(), llvm::AliasAnalysis::getModRefInfo(), getNaturalGEPWithOffset(), getNaturalGEPWithType(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), getNoopInput(), llvm::ConstantAggregateZero::getNumElements(), llvm::UndefValue::getNumElements(), llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(), llvm::Argument::getParamAlignment(), llvm::AtomicCmpXchgInst::getPointerAddressSpace(), llvm::AtomicRMWInst::getPointerAddressSpace(), llvm::LoadInst::getPointerAddressSpace(), llvm::PtrToIntInst::getPointerAddressSpace(), llvm::StoreInst::getPointerAddressSpace(), llvm::GetPointerBaseWithConstantOffset(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), llvm::GEPOperator::getPointerOperandType(), llvm::GetElementPtrInst::getPointerOperandType(), llvm::PtrToIntOperator::getPointerOperandType(), llvm::FastISel::getRegForGEPIndex(), llvm::ConstantExpr::getSelect(), llvm::ConstantAggregateZero::getSequentialElement(), llvm::UndefValue::getSequentialElement(), GetShiftedValue(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::ConstantExpr::getShuffleVector(), llvm::ARMTargetLowering::getSingleConstraintMatchWeight(), llvm::PPCTargetLowering::getSingleConstraintMatchWeight(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::TargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::MemTransferInst::getSourceAddressSpace(), llvm::Constant::getSplatValue(), GetStoreValueForLoad(), getStrideFromPointer(), llvm::ConstantAggregateZero::getStructElement(), llvm::UndefValue::getStructElement(), llvm::AllocaInst::getType(), llvm::ConstantArray::getType(), llvm::ConstantDataArray::getType(), llvm::ConstantDataSequential::getType(), llvm::ConstantDataVector::getType(), llvm::ConstantInt::getType(), llvm::ConstantPointerNull::getType(), llvm::ConstantStruct::getType(), llvm::ConstantVector::getType(), llvm::GetElementPtrInst::getType(), llvm::GlobalValue::getType(), llvm::InlineAsm::getType(), llvm::InsertElementInst::getType(), llvm::SCEVUnknown::getType(), llvm::ShuffleVectorInst::getType(), getUnderlyingObjects(), getUniqueCastUse(), getValueAsDouble(), llvm::ExtractElementInst::getVectorOperandType(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getWithOperands(), llvm::ConstantExpr::getWithOperands(), llvm::GlobalVariable::GlobalVariable(), llvm::GlobalVariable::GlobalVariable(), HandleByValArgument(), HandleByValArgumentInit(), llvm::ValueAsMetadata::handleRAUW(), llvm::Argument::hasByValAttr(), llvm::Argument::hasByValOrInAllocaAttr(), llvm::PHINode::hasConstantValue(), llvm::Argument::hasInAllocaAttr(), llvm::Argument::hasNestAttr(), llvm::Argument::hasNoAliasAttr(), llvm::Argument::hasNoCaptureAttr(), llvm::Argument::hasNonNullAttr(), hasSameExtUse(), llvm::Argument::hasStructRetAttr(), HoistThenElseCodeToIf(), llvm::ICmpInst::ICmpInst(), llvm::ICmpInst::ICmpInst(), llvm::ICmpInst::ICmpInst(), IdxCompare(), llvm::BinaryOperator::init(), INITIALIZE_TM_PASS(), llvm::InlineFunction(), llvm::InsertElementConstantExpr::InsertElementConstantExpr(), insertFastDiv(), insertInteger(), insertSinCosCall(), insertUniqueBackedgeBlock(), insertVector(), llvm::MemoryDependenceAnalysis::invalidateCachedPointerInfo(), llvm::LandingPadInst::isCatch(), isCompatibleIVType(), llvm::MipsTargetObjectFile::IsConstantInSmallSection(), IsConstantOffsetFromGlobal(), isDereferenceablePointer(), isEliminableCastPair(), llvm::LandingPadInst::isFilter(), isGEPKnownNonNull(), isHighCostExpansion(), llvm::Instruction::isIdenticalToWhenDefined(), llvm::isImageOrSamplerVal(), llvm::CastInst::isIntegerCast(), isIntegerWideningViableForSlice(), llvm::CastInst::isLosslessCast(), llvm::Constant::isNegativeZeroValue(), llvm::CastInst::isNoopCast(), llvm::CastInst::isNoopCast(), llvm::objcarc::IsPotentialRetainableObjPtr(), isSafeToEliminateVarargsCast(), llvm::isSafeToLoadUnconditionally(), llvm::Instruction::isSameOperationAs(), isStridedPtr(), llvm::ExtractElementInst::isValidOperands(), llvm::InsertElementInst::isValidOperands(), llvm::ShuffleVectorInst::isValidOperands(), isVectorPromotionViable(), isVectorPromotionViableForSlice(), LLVMConstRealGetDouble(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), LowerAtomicCmpXchgInst(), lowerCallFromStatepoint(), llvm::AsmPrinter::lowerConstant(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerNegateToMultiply(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::MachineMemOperand::MachineMemOperand(), matchPairwiseReduction(), matchPairwiseReductionAtLevel(), MatchSelectFromAndOr(), matchVectorSplittingReduction(), llvm::MergeBasicBlockIntoOnlyPred(), OptimizeAwayTrappingUsesOfValue(), OptimizeExtractBits(), OptimizeGlobalAddressOfMalloc(), OptimizeIntegerToVectorInsertions(), OptimizeIntToFloatBitCast(), OptimizeNoopCopyExpression(), OptimizeOnceStoredGlobal(), OptimizeVectorResize(), llvm::TargetLowering::ParseConstraints(), PerformHeapAllocSRoA(), llvm::AssemblyWriter::printArgument(), printAsOperand(), llvm::AssemblyWriter::printInstruction(), processInstruction(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), promoteSingleBlockAlloca(), llvm::AliasSetTracker::remove(), llvm::PHINode::removeIncomingValue(), llvm::MemoryDependenceAnalysis::removeInstruction(), replaceAllUsesWith(), llvm::SCEVExpander::replaceCongruentIVs(), ReplaceFPIntrinsicWithCall(), replaceSymbolicStrideSCEV(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), replaceUsesOutsideBlock(), llvm::returnTypeIsEligibleForTailCall(), reuseTableCompare(), RewriteHeapSROALoadUser(), rewriteSingleStoreAlloca(), RewriteUsesOfClonedInstructions(), llvm::LoadAndStorePromoter::run(), llvm::NVPTXLowerAggrCopies::runOnFunction(), ScalarizeMaskedLoad(), ScalarizeMaskedStore(), llvm::SelectConstantExpr::SelectConstantExpr(), llvm::FastISel::selectExtractValue(), llvm::FastISel::selectIntrinsicCall(), llvm::GlobalAlias::setAliasee(), llvm::MemIntrinsic::setDest(), llvm::GlobalVariable::setInitializer(), llvm::MemIntrinsic::setLength(), setName(), llvm::MemTransferInst::setSource(), llvm::MemSetInst::setValue(), shorter_filter(), shouldConvert(), llvm::AArch64TargetLowering::shouldExpandAtomicLoadInIR(), llvm::ARMTargetLowering::shouldExpandAtomicLoadInIR(), llvm::AArch64TargetLowering::shouldExpandAtomicRMWInIR(), llvm::ARMTargetLowering::shouldExpandAtomicRMWInIR(), llvm::ShuffleVectorConstantExpr::ShuffleVectorConstantExpr(), SimplifyAddInst(), SimplifyAndInst(), SimplifyAndOfICmps(), SimplifyAShrInst(), SimplifyBinOp(), SimplifyBranchOnICmpChain(), SimplifyDiv(), SimplifyFAddInst(), SimplifyFSubInst(), SimplifyGEPInst(), SimplifyICmpInst(), SimplifyInsertValueInst(), SimplifyMulInst(), simplifyOneLoop(), SimplifyOrInst(), SimplifyOrOfICmps(), SimplifyPHINode(), SimplifyRem(), SimplifyRightShift(), SimplifySelectInst(), SimplifyShift(), SimplifyShlInst(), SimplifySubInst(), simplifyUnsignedRangeCheck(), SimplifyXorInst(), SinkCast(), SinkShiftAndTruncate(), SinkThenElseCodeToEnd(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), llvm::SplitLandingPadPredecessors(), stripAndAccumulateInBoundsConstantOffsets(), StripPtrCastKeepAS(), SubWithOverflow(), swapMayExposeCSEOpportunities(), SymbolicallyEvaluateBinop(), SymbolicallyEvaluateGEP(), ThreadCmpOverSelect(), truncateIVUse(), tryToMakeAllocaBePromotable(), TryToOptimizeStoreOfMallocToGlobal(), TryToShrinkGlobalToBoolean(), TurnSwitchRangeIntoICmp(), underlyingObjectsAlias(), UpdatePHINodes(), llvm::UpgradeIntrinsicCall(), valueHasFloatPrecision(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::InstCombiner::visitAddrSpaceCast(), llvm::InstCombiner::visitAllocaInst(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::Interpreter::visitExtractValueInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFPToSI(), llvm::InstCombiner::visitFPToUI(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithCastAndCast(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitInsertElementInst(), llvm::Interpreter::visitInsertValueInst(), llvm::InstCombiner::visitIntToPtr(), visitIVCast(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitPtrToInt(), llvm::InstCombiner::visitReturnInst(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitSwitchInst(), llvm::Interpreter::visitSwitchInst(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), llvm::WriteConstantInternal(), WriteInstruction(), llvm::AssemblyWriter::writeOperand(), llvm::AssemblyWriter::writeParamOperand(), and llvm::BasicBlock::~BasicBlock().
getValueID()
unsigned llvm::Value::getValueID () const inline
Return an ID for the concrete type of this object.
This is used to implement the classof checks. This should not be used for any other purpose, as the values may change as LLVM evolves. Also, note that for instructions, the Instruction's opcode is added to InstructionVal. So this means three things:
there is no value with code InstructionVal (no opcode==0).
there are more possible values for the value type than in ValueTy enum.
the InstructionVal enumerator must be the highest valued enumerator in
the ValueTy enum.
Definition at line 381 of file Value.h.
Referenced by llvm::isa_impl< Argument, Value >::doit(), llvm::isa_impl< BasicBlock, Value >::doit(), llvm::isa_impl< Constant, Value >::doit(), llvm::isa_impl< Function, Value >::doit(), llvm::isa_impl< GlobalAlias, Value >::doit(), llvm::isa_impl< GlobalVariable, Value >::doit(), llvm::isa_impl< InlineAsm, Value >::doit(), llvm::isa_impl< Instruction, Value >::doit(), llvm::Instruction::getOpcode(), and llvm::GlobalValue::setThreadLocalMode().
getValueName()
ValueName * llvm::Value::getValueName () const inline
Definition at line 229 of file Value.h.
Referenced by llvm::Function::getIntrinsicID(), getName(), hasName(), setName(), takeName(), and llvm::Function::~Function().
hasName()
bool llvm::Value::hasName () const inline
Definition at line 228 of file Value.h.
References getValueName().
Referenced by llvm::CloneBasicBlock(), llvm::ExecutionEngine::emitGlobals(), FoldBlockIntoPredecessor(), llvm::Mangler::getNameWithPrefix(), llvm::getSamplerName(), llvm::getSurfaceName(), llvm::getTextureName(), llvm::MergeBlockIntoPredecessor(), llvm::SparseSolver::Print(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printArgument(), printAsOperand(), llvm::AssemblyWriter::printBasicBlock(), setName(), takeName(), and llvm::TryToSimplifyUncondBranchFromEmptyBlock().
hasNUses()
bool Value::hasNUses (unsigned N) const
Return true if this Value has exactly N users.
Definition at line 95 of file Value.cpp.
References N, use_begin(), and use_end().
hasNUsesOrMore()
bool Value::hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
This is logically equivalent to getNumUses() >= N.
Definition at line 103 of file Value.cpp.
References N, use_begin(), and use_end().
Referenced by ProcessUMulZExtIdiom(), llvm::BasicBlock::removePredecessor(), and SRAGlobal().
hasOneUse()
bool llvm::Value::hasOneUse () const inline
Return true if there is exactly one user of this value.
This is specialized because it is a common request and does not require traversing the whole use list.
Definition at line 310 of file Value.h.
References I, use_begin(), and use_end().
Referenced by checkForNegativeOperand(), combineLoadToOperationType(), DeadPHICycle(), detectLog2OfHalf(), FindInitTrampolineFromAlloca(), llvm::SelectionDAGBuilder::FindMergedConditions(), FindSingleUseIdentifiedObject(), llvm::InstCombiner::FoldAndOfICmps(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::InstCombiner::foldFMulConst(), llvm::InstCombiner::FoldGEPICmp(), llvm::InstCombiner::FoldICmpShrCst(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldShiftByConstant(), hasNonFlagsUse(), hasUseOtherThanLLVMUsed(), LinearizeExprTree(), ProcessUGT_ADDCST_ADD(), shouldMergeGEPs(), llvm::InstCombiner::SimplifyDivRemOfSelect(), SinkThenElseCodeToEnd(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), tryFactorization(), llvm::FastISel::tryToFoldLoad(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitBranchInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
hasSameSubclassOptionalData()
bool llvm::Value::hasSameSubclassOptionalData (const Value * V) const inline
Check the optional flags for equality.
Definition at line 398 of file Value.h.
References SubclassOptionalData.
hasValueHandle()
bool llvm::Value::hasValueHandle () const inline
Return true if there is a value handle associated with this value.
Definition at line 408 of file Value.h.
Referenced by llvm::SSAUpdater::RewriteUse().
intersectOptionalDataWith()
void llvm::Value::intersectOptionalDataWith (const Value * V) inline
Clear any optional flags not set in the given Value.
Definition at line 403 of file Value.h.
References SubclassOptionalData.
Referenced by HoistThenElseCodeToIf(), and SinkThenElseCodeToEnd().
isDereferenceablePointer()
bool Value::isDereferenceablePointer (const DataLayout * DL = nullptr) const
Check if this is always a dereferenceable pointer.
Test if this value is always a pointer to allocated and suitably aligned memory for a simple load or store.
Definition at line 580 of file Value.cpp.
References llvm::dyn_cast(), llvm::APInt::getBitWidth(), llvm::APInt::getBoolValue(), llvm::Type::getPointerElementType(), getType(), llvm::DataLayout::getTypeStoreSize(), llvm::DataLayout::getTypeStoreSizeInBits(), llvm::APInt::isNonNegative(), llvm::Type::isSized(), stripAndAccumulateInBoundsConstantOffsets(), and llvm::APInt::uge().
Referenced by AllCallersPassInValidPointerForArgument(), isSafePHIToSpeculate(), isSafePHIToSpeculate(), isSafeSelectToSpeculate(), and llvm::isSafeToSpeculativelyExecute().
isUsedByMetadata()
bool llvm::Value::isUsedByMetadata () const inline
Return true if there is metadata referencing this value.
Definition at line 411 of file Value.h.
Referenced by replaceAllUsesWith(), and ~Value().
isUsedInBasicBlock()
bool Value::isUsedInBasicBlock (const BasicBlock * BB) const
Check if this value is used in the specified basic block.
Definition at line 112 of file Value.cpp.
References llvm::BasicBlock::begin(), llvm::dyn_cast(), llvm::BasicBlock::end(), user_begin(), and user_end().
mutateType()
void llvm::Value::mutateType (Type * Ty) inline
Mutate the type of this Value to be of the specified type.
Note that this is an extremely dangerous operation which can create completely invalid IR very easily. It is strongly recommended that you recreate IR objects with the right types instead of mutating them in place.
Definition at line 495 of file Value.h.
print()
void Value::print (raw_ostream & O) const
Implement operator<< on Value.
Definition at line 2575 of file AsmWriter.cpp.
References llvm::cast(), llvm::dyn_cast(), F, getModuleFromVal(), I, llvm::isa(), llvm_unreachable, llvm::TypePrinting::print(), llvm::AssemblyWriter::printAlias(), printAsOperand(), llvm::AssemblyWriter::printBasicBlock(), llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printGlobal(), llvm::AssemblyWriter::printInstruction(), and llvm::WriteConstantInternal().
Referenced by dump().
printAsOperand()
void Value::printAsOperand (raw_ostream & O, bool PrintType = true, const Module * M = nullptr) const
Print the name of this Value out to the specified raw_ostream.
This is useful when you just want to print 'int reg126', not the instruction that generated it. If you specify a Module for context, then even constanst get pretty-printed; for example, the type of a null pointer is printed symbolically.
Definition at line 2609 of file AsmWriter.cpp.
References getModuleFromVal(), getType(), hasName(), llvm::TypePrinting::incorporateTypes(), llvm::isa(), llvm::TypePrinting::print(), and llvm::WriteAsOperandInternal().
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::DOTGraphTraits< const Function * >::getCompleteNodeLabel(), llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel(), llvm::MachineOperand::print(), llvm::SCEV::print(), print(), PrintLoopInfo(), PrintModRefResults(), and PrintResults().
replaceAllUsesWith()
void Value::replaceAllUsesWith (Value * V)
Change all uses of this to point to a new Value.
Go through the uses list for this definition and make each use point to "V" instead of "this". After this completes, 'this's use list is guaranteed to be empty.
Definition at line 319 of file Value.cpp.
References llvm::cast(), contains(), llvm::dyn_cast(), getType(), llvm::ValueAsMetadata::handleRAUW(), llvm::isa(), isUsedByMetadata(), llvm::Use::set(), use_empty(), and llvm::ValueHandleBase::ValueIsRAUWd().
Referenced by AddReachableCodeToWorklist(), changeToCall(), checkCSEInPredecessor(), llvm::CloneAndPruneFunctionInto(), ConvertShiftToMul(), DeleteInstructionInBlock(), llvm::InstCombiner::DoOneIteration(), llvm::objcarc::EraseInstruction(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandDivisionUpTo64Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), llvm::expandRemainderUpTo64Bits(), findPHIToPartitionLoops(), FoldBlockIntoPredecessor(), FoldTwoEntryPHINode(), GetLoadValueForLoad(), HandleCallsInBlockInlinedThroughInvoke(), HoistThenElseCodeToIf(), InlineCallIfPossible(), llvm::InlineFunction(), insertFastDiv(), insertUniqueBackedgeBlock(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerNegateToMultiply(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeEmptyReturnBlocks(), llvm::LibCallSimplifier::optimizeCall(), OptimizeGlobalAddressOfMalloc(), promoteSingleBlockAlloca(), llvm::PHINode::removeIncomingValue(), llvm::BasicBlock::removePredecessor(), ReplaceCallWith(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::Constant::replaceUsesOfWithOnConstantImpl(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), reuseTableCompare(), rewriteSingleStoreAlloca(), llvm::LoadAndStorePromoter::run(), ScalarizeMaskedLoad(), simplifyOneLoop(), SinkThenElseCodeToEnd(), speculatePHINodeLoads(), speculateSelectInstLoads(), llvm::SplitLandingPadPredecessors(), SRAGlobal(), tryPromoteAllocaToVector(), tryToMakeAllocaBePromotable(), TryToOptimizeStoreOfMallocToGlobal(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::UnrollLoop(), llvm::UpgradeIntrinsicCall(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::BasicBlock::~BasicBlock().
replaceUsesOutsideBlock()
void Value::replaceUsesOutsideBlock (Value * V, BasicBlock * BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block. 'This's use list is expected to have at least one element. Unlike replaceAllUsesWith this function does not support basic block values or constant users.
Definition at line 352 of file Value.cpp.
References contains(), llvm::dyn_cast(), getType(), use_begin(), and use_end().
reverseUseList()
void Value::reverseUseList ()
Reverse the use-list.
Definition at line 616 of file Value.cpp.
References llvm::Registry< T, U >::Head.
setName()
void Value::setName (const Twine & Name)
Change the name of the value.
Choose a new unique name if the provided name is taken.
Parameters
Name The new name; or "" if the value's name should be removed.
Definition at line 168 of file Value.cpp.
References llvm::StringMapEntry< Value * >::Create(), llvm::dyn_cast(), llvm::StringRef::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), F, llvm::StringRef::find_first_of(), getContext(), getName(), getSymTab(), getType(), getValueName(), hasName(), llvm::LLVMContextImpl::IntrinsicIDCache, llvm::Twine::isTriviallyEmpty(), llvm::StringRef::npos, llvm::LLVMContext::pImpl, llvm::StringMapEntry< ValueTy >::setValue(), setValueName(), and llvm::Twine::toStringRef().
Referenced by llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::Argument::Argument(), llvm::BinaryOperator::BinaryOperator(), llvm::BinaryOperator::BinaryOperator(), llvm::CastInst::CastInst(), llvm::CastInst::CastInst(), llvm::CloneBasicBlock(), llvm::CmpInst::CmpInst(), llvm::CmpInst::CmpInst(), llvm::IRBuilderBase::CreateGlobalString(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), forceRenaming(), generateUnsignedDivisionCode(), llvm::GlobalValue::GlobalValue(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::LoadInst::LoadInst(), llvm::IntrinsicLowering::LowerIntrinsicCall(), ReplaceCallWith(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::SplitLandingPadPredecessors(), SwitchToLookupTable(), llvm::UpgradeIntrinsicCall(), llvm::VAArgInst::VAArgInst(), and llvm::VAArgInst::VAArgInst().
setValueName()
void llvm::Value::setValueName (ValueName * VN) inline
Definition at line 230 of file Value.h.
Referenced by setName(), and takeName().
setValueSubclassData()
void llvm::Value::setValueSubclassData (unsigned short D) inline protected
Definition at line 532 of file Value.h.
sortUseList()
template<class Compare> void llvm::Value::sortUseList (Compare Cmp)
Sort the use-list.
Sorts the Value's use-list by Cmp using a stable mergesort. Cmp is expected to compare two Use references.
Definition at line 546 of file Value.h.
References I.
stripAndAccumulateInBoundsConstantOffsets() [1/2]
Value * Value::stripAndAccumulateInBoundsConstantOffsets (const DataLayout & DL, APInt & Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
Stores the resulting constant offset stripped into the APInt provided. The provided APInt will be extended or truncated as needed to be the correct bitwidth for an offset of this pointer type.
If this is called on a non-pointer value, it returns 'this'.
Definition at line 438 of file Value.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::APInt::getBitWidth(), llvm::Operator::getOpcode(), llvm::DataLayout::getPointerSizeInBits(), getType(), and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by llvm::GlobalAlias::getBaseObject(), isDereferenceablePointer(), and stripAndAccumulateInBoundsConstantOffsets().
stripAndAccumulateInBoundsConstantOffsets() [2/2]
const Value * llvm::Value::stripAndAccumulateInBoundsConstantOffsets (const DataLayout & DL, APInt & Offset) const inline
Definition at line 449 of file Value.h.
References stripAndAccumulateInBoundsConstantOffsets().
stripInBoundsConstantOffsets() [1/2]
Value * Value::stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
Returns the original pointer value. If this is called on a non-pointer value, it returns 'this'.
Definition at line 434 of file Value.cpp.
Referenced by stripInBoundsConstantOffsets().
stripInBoundsConstantOffsets() [2/2]
const Value * llvm::Value::stripInBoundsConstantOffsets () const inline
Definition at line 436 of file Value.h.
References stripInBoundsConstantOffsets().
stripInBoundsOffsets() [1/2]
Value * Value::stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
Returns the original pointer value. If this is called on a non-pointer value, it returns 'this'.
Definition at line 475 of file Value.cpp.
Referenced by llvm::GlobalAlias::getBaseObject(), and stripInBoundsOffsets().
stripInBoundsOffsets() [2/2]
const Value * llvm::Value::stripInBoundsOffsets () const inline
Definition at line 460 of file Value.h.
References stripInBoundsOffsets().
stripPointerCasts() [1/2]
Value * Value::stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
Returns the original uncasted value. If this is called on a non-pointer value, it returns 'this'.
Definition at line 426 of file Value.cpp.
Referenced by llvm::AddLandingPadInfo(), llvm::MachineModuleInfo::AnalyzeModule(), computePointerICmp(), llvm::EmitBinaryFloatFnCall(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::EmitStrCpy(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitUnaryFloatFnCall(), llvm::FindAvailableLoadedValue(), FindInitTrampoline(), FindInitTrampolineFromAlloca(), findUsedValues(), findUsedValues(), llvm::InstCombiner::FoldGEPICmp(), llvm::MemIntrinsic::getDest(), getKnownConstant(), llvm::InstrProfIncrementInst::getName(), llvm::MemTransferInst::getSource(), isOverwrite(), IsPointerOffset(), llvm::isSafeToLoadUnconditionally(), OptimizeOnceStoredGlobal(), RecognizePersonality(), llvm::BlockAddress::replaceUsesOfWithOnConstant(), llvm::skipPointerTransfer(), llvm::Constant::stripPointerCasts(), stripPointerCasts(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::InstCombiner::visitLandingPadInst().
stripPointerCasts() [2/2]
const Value * llvm::Value::stripPointerCasts () const inline
Definition at line 418 of file Value.h.
References stripPointerCasts().
stripPointerCastsNoFollowAliases() [1/2]
Value * Value::stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
Returns the original uncasted value. If this is called on a non-pointer value, it returns 'this'.
Definition at line 430 of file Value.cpp.
Referenced by llvm::collectUsedGlobalVariables(), FindUsedValues(), and stripPointerCastsNoFollowAliases().
stripPointerCastsNoFollowAliases() [2/2]
const Value * llvm::Value::stripPointerCastsNoFollowAliases () const inline
Definition at line 427 of file Value.h.
References stripPointerCastsNoFollowAliases().
takeName()
void Value::takeName (Value * V)
Transfer the name from V to this value.
After taking V's name, sets V's name to empty.
Note
It is an error to call V->takeName(V).
Definition at line 224 of file Value.cpp.
References getSymTab(), getValueName(), hasName(), llvm::StringMapEntry< ValueTy >::setValue(), and setValueName().
Referenced by BreakUpSubtract(), changeToCall(), llvm::InstCombiner::commonPointerCastTransforms(), ConvertShiftToMul(), llvm::InstCombiner::CreateOverflowTuple(), llvm::FoldBranchToCommonDest(), llvm::InstCombiner::FoldSelectIntoOp(), llvm::InstCombiner::FoldShiftByConstant(), forceRenaming(), GetLoadValueForLoad(), HoistThenElseCodeToIf(), LowerNegateToMultiply(), llvm::MergeBlockIntoPredecessor(), tryFactorization(), tryToMakeAllocaBePromotable(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), upgradeGlobalArray(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitTrunc(), and llvm::InstCombiner::visitXor().
use_begin() [1/2]
use_iterator llvm::Value::use_begin () inline
Definition at line 278 of file Value.h.
Referenced by getNumUses(), hasNonFlagsUse(), hasNUses(), hasNUsesOrMore(), hasOneUse(), OptimizeGlobalAddressOfMalloc(), ReplaceUsesOfMallocWithGlobal(), replaceUsesOutsideBlock(), RewriteUsesOfClonedInstructions(), uses(), uses(), and ~Value().
use_begin() [2/2]
const_use_iterator llvm::Value::use_begin () const inline
Definition at line 279 of file Value.h.
use_empty()
bool llvm::Value::use_empty () const inline
Definition at line 274 of file Value.h.
Referenced by AddReachableCodeToWorklist(), combineLoadToOperationType(), DeadPHICycle(), DeleteDeadInstruction(), deleteDeadInstruction(), DeleteInstructionInBlock(), llvm::Constant::destroyConstantImpl(), llvm::AsmPrinter::doFinalization(), llvm::InstCombiner::DoOneIteration(), llvm::objcarc::EraseInstruction(), hasAddressTakenAndUsed(), hasSameExtUse(), hasUseOtherThanLLVMUsed(), llvm::InlineFunction(), LinearizeExprTree(), llvm::IntrinsicLowering::LowerIntrinsicCall(), OptimizeAwayTrappingUsesOfLoads(), OptimizeCmpExpression(), OptimizeExtractBits(), OptimizeGlobalAddressOfMalloc(), llvm::AssemblyWriter::printBasicBlock(), promoteSingleBlockAlloca(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), replaceAllUsesWith(), ReplaceCallWith(), ReplaceUsesOfMallocWithGlobal(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), RewriteUsesOfClonedInstructions(), llvm::LoadAndStorePromoter::run(), llvm::Inliner::runOnSCC(), SinkCast(), SinkThenElseCodeToEnd(), speculatePHINodeLoads(), SRAGlobal(), tryToMakeAllocaBePromotable(), TryToShrinkGlobalToBoolean(), upgradeGlobalArray(), llvm::InstCombiner::visitCallInst(), llvm::PtrUseVisitor< SliceBuilder >::visitGetElementPtrInst(), llvm::BasicBlock::~BasicBlock(), and ~Value().
use_end() [1/2]
use_iterator llvm::Value::use_end () inline
Definition at line 280 of file Value.h.
Referenced by getNumUses(), hasNUses(), hasNUsesOrMore(), hasOneUse(), replaceUsesOutsideBlock(), RewriteUsesOfClonedInstructions(), uses(), uses(), and ~Value().
use_end() [2/2]
const_use_iterator llvm::Value::use_end () const inline
Definition at line 281 of file Value.h.
user_back() [1/2]
User * llvm::Value::user_back () inline
Definition at line 297 of file Value.h.
References user_begin().
Referenced by llvm::Constant::destroyConstantImpl(), FindInitTrampolineFromAlloca(), OptimizeGlobalAddressOfMalloc(), llvm::NVPTXLowerAggrCopies::runOnFunction(), SRAGlobal(), TryToShrinkGlobalToBoolean(), llvm::InstCombiner::visitInsertValueInst(), and llvm::BasicBlock::~BasicBlock().
user_back() [2/2]
const User * llvm::Value::user_back () const inline
Definition at line 298 of file Value.h.
References user_begin().
user_begin() [1/2]
user_iterator llvm::Value::user_begin () inline
Definition at line 293 of file Value.h.
Referenced by CleanupPointerRootUsers(), llvm::getMallocType(), hasSameExtUse(), isUsedInBasicBlock(), OptimizeAwayTrappingUsesOfLoads(), OptimizeCmpExpression(), OptimizeExtractBits(), PerformHeapAllocSRoA(), promoteSingleBlockAlloca(), llvm::Constant::removeDeadConstantUsers(), removeLifetimeIntrinsicUsers(), ReplaceUsesOfMallocWithGlobal(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), RewriteHeapSROALoadUser(), rewriteSingleStoreAlloca(), llvm::NVPTXLowerAggrCopies::runOnFunction(), SinkCast(), SinkShiftAndTruncate(), llvm::Instruction::user_back(), llvm::Instruction::user_back(), user_back(), user_back(), users(), and users().
user_begin() [2/2]
const_user_iterator llvm::Value::user_begin () const inline
Definition at line 294 of file Value.h.
user_empty()
bool llvm::Value::user_empty () const inline
Definition at line 289 of file Value.h.
user_end() [1/2]
user_iterator llvm::Value::user_end () inline
Definition at line 295 of file Value.h.
Referenced by CleanupPointerRootUsers(), llvm::getMallocType(), isUsedInBasicBlock(), OptimizeAwayTrappingUsesOfLoads(), OptimizeCmpExpression(), OptimizeExtractBits(), PerformHeapAllocSRoA(), promoteSingleBlockAlloca(), llvm::Constant::removeDeadConstantUsers(), removeLifetimeIntrinsicUsers(), RewriteHeapSROALoadUser(), rewriteSingleStoreAlloca(), SinkCast(), SinkShiftAndTruncate(), users(), and users().
user_end() [2/2]
const_user_iterator llvm::Value::user_end () const inline
Definition at line 296 of file Value.h.
users() [1/2]
iterator_range< user_iterator > llvm::Value::users () inline
Definition at line 299 of file Value.h.
References user_begin(), and user_end().
Referenced by AllCallersPassInValidPointerForArgument(), AllGlobalLoadUsesSimpleEnoughForHeapSRA(), AllUsesOfLoadedValueWillTrapIfNull(), AllUsesOfValueWillTrapIfNull(), AlmostDeadIV(), BlockIsSimpleEnoughToThreadThrough(), collectUsesWithPtrTypes(), llvm::InstCombiner::dominatesAllUses(), llvm::FindAllocaDbgDeclare(), FindInitTrampolineFromAlloca(), llvm::CodeExtractor::findInputsOutputs(), FindSingleUseIdentifiedObject(), getPreferredExtendForValue(), getUniqueCastUse(), GlobalUsersSafeToSRA(), hasLifetimeMarkers(), hasOutsideLoopUser(), hasSameExtUse(), llvm::isAllocaPromotable(), isAllocSiteRemovable(), llvm::Constant::isConstantUsed(), isHighCostExpansion(), isOnlyUsedInEqualityComparison(), IsOnlyUsedInZeroEqualityComparison(), isOnlyUsedInZeroEqualityComparison(), isSafeAndProfitableToSinkLoad(), isSafePHIToSpeculate(), isSafePHIToSpeculate(), isSafeSROAElementUse(), isUsedByLifetimeMarker(), IsUserOfGlobalSafeForSRA(), LoadUsesSimpleEnoughForHeapSRA(), llvm::LowerDbgDeclare(), NegateValue(), OnlyUsedBy(), llvm::onlyUsedByLifetimeMarkers(), ProcessUGT_ADDCST_ADD(), ProcessUMulZExtIdiom(), promoteSingleBlockAlloca(), rewriteNonInstructionUses(), shouldSpeculateInstrs(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), swapMayExposeCSEOpportunities(), tryPromoteAllocaToVector(), tryToMakeAllocaBePromotable(), TryToShrinkGlobalToBoolean(), usedInOneFunc(), and ValueIsOnlyUsedLocallyOrStoredToOneGlobal().
users() [2/2]
iterator_range< const_user_iterator > llvm::Value::users () const inline
Definition at line 302 of file Value.h.
References user_begin(), and user_end().
uses() [1/2]
iterator_range< use_iterator > llvm::Value::uses () inline
Definition at line 282 of file Value.h.
References use_begin(), and use_end().
Referenced by AddressIsTaken(), analyzeGlobalAux(), FindPhiPredForUseInBlock(), llvm::Function::hasAddressTaken(), llvm::Instruction::isUsedOutsideOfBlock(), llvm::PointerMayBeCaptured(), predictValueUseListOrderImpl(), predictValueUseListOrderImpl(), llvm::ValueEnumerator::print(), and processInstruction().
uses() [2/2]
iterator_range< const_use_iterator > llvm::Value::uses () const inline
Definition at line 285 of file Value.h.
References use_begin(), and use_end().
Friends And Related Symbol Documentation
ValueAsMetadata
friend class ValueAsMetadata friend
Definition at line 72 of file Value.h.
References ValueAsMetadata.
Referenced by ValueAsMetadata.
ValueHandleBase
friend class ValueHandleBase friend
Definition at line 73 of file Value.h.
References ValueHandleBase.
Referenced by ValueHandleBase.
Member Data Documentation
MaximumAlignment
const unsigned llvm::Value::MaximumAlignment = 1u << 29 static
The maximum alignment for instructions.
This is the greatest alignment value supported by load, store, and alloca instructions, and global values.
Definition at line 487 of file Value.h.
Referenced by llvm::getOrEnforceKnownAlignment(), and WriteInstruction().
NumOperands
unsigned llvm::Value::NumOperands protected
The number of operands in the subclass.
This member is defined by this class, but not used for anything. Subclasses can use it to store their number of operands, if they have any.
This is stored here to save space in User on 64-bit hosts. Since most instances of Value have operands, 32-bit hosts aren't significantly affected.
Definition at line 104 of file Value.h.
Referenced by llvm::SwitchInst::addCase(), llvm::LandingPadInst::addClause(), llvm::IndirectBrInst::addDestination(), llvm::PHINode::addIncoming(), llvm::User::dropHungoffUses(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::User::getOperandUse(), llvm::User::getOperandUse(), llvm::User::op_end(), llvm::User::op_end(), llvm::User::operator delete(), llvm::User::operator new(), llvm::SwitchInst::removeCase(), llvm::IndirectBrInst::removeDestination(), llvm::PHINode::removeIncomingValue(), llvm::GlobalVariable::setInitializer(), llvm::User::setOperand(), llvm::User::User(), Value(), llvm::GlobalVariable::~GlobalVariable(), and llvm::User::~User().
SubclassOptionalData
unsigned char llvm::Value::SubclassOptionalData protected
Hold subclass data that can be dropped.
This member is similar to SubclassData, however it is for holding information which may be used to aid optimization, but which may be cleared to zero without affecting conservative interpretation.
Definition at line 84 of file Value.h.
Referenced by llvm::BinaryConstantExpr::BinaryConstantExpr(), clearSubclassOptionalData(), llvm::Instruction::clone(), llvm::GEPOperator::ConstantExpr, llvm::OverflowingBinaryOperator::ConstantExpr, llvm::PossiblyExactOperator::ConstantExpr, llvm::GetElementPtrConstantExpr::Create(), llvm::ConstantExpr::getAsInstruction(), llvm::FPMathOperator::getFastMathFlags(), getRawSubclassOptionalData(), llvm::ConstantExpr::getWithOperands(), llvm::FPMathOperator::hasAllowReciprocal(), llvm::FPMathOperator::hasNoInfs(), llvm::FPMathOperator::hasNoNaNs(), llvm::OverflowingBinaryOperator::hasNoSignedWrap(), llvm::FPMathOperator::hasNoSignedZeros(), llvm::OverflowingBinaryOperator::hasNoUnsignedWrap(), hasSameSubclassOptionalData(), llvm::FPMathOperator::hasUnsafeAlgebra(), llvm::FPMathOperator::Instruction, intersectOptionalDataWith(), llvm::PossiblyExactOperator::isExact(), llvm::Instruction::isIdenticalTo(), llvm::GEPOperator::isInBounds(), and Value().
The documentation for this class was generated from the following files:
Value.h
AsmWriter.cpp
Value.cpp