LLVM: llvm::ARMConstantPoolValue Class Reference
LLVM API Documentation
llvm::ARMConstantPoolValue Class Reference
#include <ARMConstantPoolValue.h>
Public Member Functions
virtual ~ARMConstantPoolValue ()
ARMCP::ARMCPModifier getModifier () const
const char * getModifierText () const
bool hasModifier () const
bool mustAddCurrentAddress () const
unsigned getLabelId () const
unsigned char getPCAdjustment () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isLSDA () const
bool isMachineBasicBlock () const
unsigned getRelocationInfo () const override
int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
virtual bool hasSameValue (ARMConstantPoolValue *ACPV)
bool equals (const ARMConstantPoolValue *A) const
void print (raw_ostream &O) const override
print - Implement operator<<
void print (raw_ostream *O) const
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()
Type * getType () const
Protected Member Functions
ARMConstantPoolValue (Type *Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
ARMConstantPoolValue (LLVMContext &C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
template<typename Derived>
int getExistingMachineCPValueImpl (MachineConstantPool *CP, unsigned Alignment)
Detailed Description
ARMConstantPoolValue - ARM specific constantpool value. This is used to represent PC-relative displacement between the address of the load instruction and the constant being loaded, i.e. (&GV-(LPIC+8)).
Definition at line 52 of file ARMConstantPoolValue.h.
Constructor & Destructor Documentation
ARMConstantPoolValue() [1/2]
ARMConstantPoolValue::ARMConstantPoolValue (Type * Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress) protected
Definition at line 29 of file ARMConstantPoolValue.cpp.
References llvm::MachineConstantPoolValue::MachineConstantPoolValue().
Referenced by llvm::ARMConstantPoolConstant::classof(), llvm::ARMConstantPoolMBB::classof(), llvm::ARMConstantPoolSymbol::classof(), equals(), getExistingMachineCPValueImpl(), llvm::ARMConstantPoolConstant::hasSameValue(), llvm::ARMConstantPoolMBB::hasSameValue(), llvm::ARMConstantPoolSymbol::hasSameValue(), and hasSameValue().
ARMConstantPoolValue() [2/2]
ARMConstantPoolValue::ARMConstantPoolValue (LLVMContext & C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress) protected
Definition at line 38 of file ARMConstantPoolValue.cpp.
References llvm::MachineConstantPoolValue::MachineConstantPoolValue().
~ARMConstantPoolValue()
ARMConstantPoolValue::~ARMConstantPoolValue () virtual
Definition at line 47 of file ARMConstantPoolValue.cpp.
Member Function Documentation
addSelectionDAGCSEId()
void ARMConstantPoolValue::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 69 of file ARMConstantPoolValue.cpp.
Referenced by llvm::ARMConstantPoolConstant::addSelectionDAGCSEId(), llvm::ARMConstantPoolMBB::addSelectionDAGCSEId(), and llvm::ARMConstantPoolSymbol::addSelectionDAGCSEId().
dump()
void ARMConstantPoolValue::dump () const
Definition at line 89 of file ARMConstantPoolValue.cpp.
References llvm::errs().
equals()
bool llvm::ARMConstantPoolValue::equals (const ARMConstantPoolValue * A) const inline
Definition at line 117 of file ARMConstantPoolValue.h.
References ARMConstantPoolValue().
Referenced by llvm::ARMConstantPoolConstant::equals(), llvm::ARMConstantPoolMBB::equals(), llvm::ARMConstantPoolSymbol::equals(), and getExistingMachineCPValueImpl().
getExistingMachineCPValue()
int ARMConstantPoolValue::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 63 of file ARMConstantPoolValue.cpp.
References llvm_unreachable.
getExistingMachineCPValueImpl()
template<typename Derived> int llvm::ARMConstantPoolValue::getExistingMachineCPValueImpl (MachineConstantPool * CP, unsigned Alignment) inline protected
Definition at line 70 of file ARMConstantPoolValue.h.
References ARMConstantPoolValue(), llvm::cast(), llvm::dyn_cast(), equals(), and llvm::MachineConstantPool::getConstants().
Referenced by llvm::ARMConstantPoolConstant::getExistingMachineCPValue(), llvm::ARMConstantPoolMBB::getExistingMachineCPValue(), and llvm::ARMConstantPoolSymbol::getExistingMachineCPValue().
getLabelId()
unsigned llvm::ARMConstantPoolValue::getLabelId () const inline
Definition at line 97 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
getModifier()
ARMCP::ARMCPModifier llvm::ARMConstantPoolValue::getModifier () const inline
Definition at line 91 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
getModifierText()
const char * ARMConstantPoolValue::getModifierText () const
Definition at line 49 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::GOT, llvm::ARMCP::GOTOFF, llvm::ARMCP::GOTTPOFF, llvm_unreachable, llvm::ARMCP::no_modifier, llvm::ARMCP::TLSGD, and llvm::ARMCP::TPOFF.
Referenced by print().
getPCAdjustment()
unsigned char llvm::ARMConstantPoolValue::getPCAdjustment () const inline
Definition at line 98 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
getRelocationInfo()
unsigned llvm::ARMConstantPoolValue::getRelocationInfo () const inline override virtual
getRelocationInfo - This method classifies the entry according to whether or not it may generate a relocation entry. This must be conservative, so if it might codegen to a relocatable entry, it should say so. The return values are the same as Constant::getRelocationInfo().
Implements llvm::MachineConstantPoolValue.
Definition at line 106 of file ARMConstantPoolValue.h.
hasModifier()
bool llvm::ARMConstantPoolValue::hasModifier () const inline
Definition at line 93 of file ARMConstantPoolValue.h.
References llvm::ARMCP::no_modifier.
hasSameValue()
bool ARMConstantPoolValue::hasSameValue (ARMConstantPoolValue * ACPV) virtual
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
Reimplemented in llvm::ARMConstantPoolConstant, llvm::ARMConstantPoolMBB, and llvm::ARMConstantPoolSymbol.
Definition at line 75 of file ARMConstantPoolValue.cpp.
References ARMConstantPoolValue(), llvm::ARMCP::CPExtSymbol, and llvm::ARMCP::CPValue.
Referenced by llvm::ARMConstantPoolConstant::hasSameValue(), llvm::ARMConstantPoolMBB::hasSameValue(), llvm::ARMConstantPoolSymbol::hasSameValue(), and llvm::ARMBaseInstrInfo::produceSameValue().
isBlockAddress()
bool llvm::ARMConstantPoolValue::isBlockAddress () const inline
Definition at line 102 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPBlockAddress.
Referenced by llvm::ARMConstantPoolConstant::classof(), duplicateCPV(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
isExtSymbol()
bool llvm::ARMConstantPoolValue::isExtSymbol () const inline
Definition at line 101 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPExtSymbol.
Referenced by llvm::ARMConstantPoolSymbol::classof(), duplicateCPV(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
isGlobalValue()
bool llvm::ARMConstantPoolValue::isGlobalValue () const inline
Definition at line 100 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPValue.
Referenced by llvm::ARMConstantPoolConstant::classof(), duplicateCPV(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
isLSDA()
bool llvm::ARMConstantPoolValue::isLSDA () const inline
Definition at line 103 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPLSDA.
Referenced by llvm::ARMConstantPoolConstant::classof(), duplicateCPV(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
isMachineBasicBlock()
bool llvm::ARMConstantPoolValue::isMachineBasicBlock () const inline
Definition at line 104 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPMachineBasicBlock.
Referenced by llvm::ARMConstantPoolMBB::classof(), duplicateCPV(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
mustAddCurrentAddress()
bool llvm::ARMConstantPoolValue::mustAddCurrentAddress () const inline
Definition at line 95 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
print() [1/2]
void ARMConstantPoolValue::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 93 of file ARMConstantPoolValue.cpp.
References getModifierText().
Referenced by llvm::ARMConstantPoolConstant::print(), llvm::ARMConstantPoolMBB::print(), and llvm::ARMConstantPoolSymbol::print().
print() [2/2]
void llvm::ARMConstantPoolValue::print (raw_ostream * O) const inline
Definition at line 124 of file ARMConstantPoolValue.h.
References print().
Referenced by print().
The documentation for this class was generated from the following files:
ARMConstantPoolValue.h
ARMConstantPoolValue.cpp