LLVM: llvm::BitVector Class Reference
LLVM API Documentation
llvm::BitVector Class Reference
#include <BitVector.h>
Classes
class reference
Public Types
typedef unsigned size_type
Public Member Functions
BitVector ()
BitVector default ctor - Creates an empty bitvector.
BitVector (unsigned s, bool t=false)
BitVector (const BitVector &RHS)
BitVector copy ctor.
BitVector (BitVector &&RHS)
~BitVector ()
bool empty () const
empty - Tests whether there are no bits in this bitvector.
size_type size () const
size - Returns the number of bits in this bitvector.
size_type count () const
count - Returns the number of bits which are set.
bool any () const
any - Returns true if any bit is set.
bool all () const
all - Returns true if all bits are set.
bool none () const
none - Returns true if none of the bits are set.
int find_first () const
int find_next (unsigned Prev) const
void clear ()
clear - Clear all bits.
void resize (unsigned N, bool t=false)
resize - Grow or shrink the bitvector.
void reserve (unsigned N)
BitVector & set ()
BitVector & set (unsigned Idx)
BitVector & set (unsigned I, unsigned E)
set - Efficiently set a range of bits in [I, E)
BitVector & reset ()
BitVector & reset (unsigned Idx)
BitVector & reset (unsigned I, unsigned E)
reset - Efficiently reset a range of bits in [I, E)
BitVector & flip ()
BitVector & flip (unsigned Idx)
reference operator[] (unsigned Idx)
bool operator[] (unsigned Idx) const
bool test (unsigned Idx) const
bool anyCommon (const BitVector &RHS) const
Test if any common bits are set.
bool operator== (const BitVector &RHS) const
bool operator!= (const BitVector &RHS) const
BitVector & operator&= (const BitVector &RHS)
Intersection, union, disjoint union.
BitVector & reset (const BitVector &RHS)
reset - Reset bits that are set in RHS. Same as *this &= ~RHS.
bool test (const BitVector &RHS) const
BitVector & operator|= (const BitVector &RHS)
BitVector & operator^= (const BitVector &RHS)
const BitVector & operator= (const BitVector &RHS)
const BitVector & operator= (BitVector &&RHS)
void swap (BitVector &RHS)
void setBitsInMask (const uint32_t *Mask, unsigned MaskWords=~0u)
void clearBitsInMask (const uint32_t *Mask, unsigned MaskWords=~0u)
void setBitsNotInMask (const uint32_t *Mask, unsigned MaskWords=~0u)
void clearBitsNotInMask (const uint32_t *Mask, unsigned MaskWords=~0u)
Detailed Description
Definition at line 27 of file BitVector.h.
Member Typedef Documentation
size_type
typedef unsigned llvm::BitVector::size_type
Definition at line 37 of file BitVector.h.
Constructor & Destructor Documentation
BitVector() [1/4]
llvm::BitVector::BitVector () inline
BitVector default ctor - Creates an empty bitvector.
Definition at line 75 of file BitVector.h.
Referenced by anyCommon(), BitVector(), BitVector(), flip(), flip(), operator!=(), operator&=(), operator=(), operator=(), operator==(), operator^=(), operator|=(), reset(), reset(), reset(), reset(), set(), set(), set(), swap(), and test().
BitVector() [2/4]
llvm::BitVector::BitVector (unsigned s, bool t = false) inline explicit
BitVector ctor - Creates a bitvector of specified number of bits. All bits are initialized to the specified value.
Definition at line 81 of file BitVector.h.
BitVector() [3/4]
llvm::BitVector::BitVector (const BitVector & RHS) inline
BitVector copy ctor.
Definition at line 90 of file BitVector.h.
References BitVector(), and size().
BitVector() [4/4]
llvm::BitVector::BitVector (BitVector && RHS) inline
Definition at line 102 of file BitVector.h.
References BitVector().
~BitVector()
llvm::BitVector::~BitVector () inline
Definition at line 107 of file BitVector.h.
Member Function Documentation
all()
bool llvm::BitVector::all () const inline
all - Returns true if all bits are set.
Definition at line 139 of file BitVector.h.
any()
bool llvm::BitVector::any () const inline
any - Returns true if any bit is set.
Definition at line 131 of file BitVector.h.
References size().
Referenced by none(), and llvm::RegScavenger::scavengeRegister().
anyCommon()
bool llvm::BitVector::anyCommon (const BitVector & RHS) const inline
Test if any common bits are set.
Definition at line 344 of file BitVector.h.
References BitVector(), and size().
clear()
void llvm::BitVector::clear () inline
clear - Clear all bits.
Definition at line 204 of file BitVector.h.
Referenced by llvm::LiveIntervals::checkRegMaskInterference(), llvm::CriticalAntiDepBreaker::FinishBlock(), llvm::BuildVectorSDNode::getSplatValue(), and llvm::SpillPlacement::prepare().
clearBitsInMask()
void llvm::BitVector::clearBitsInMask (const uint32_t * Mask, unsigned MaskWords = ~0u) inline
clearBitsInMask - Clear any bits in this vector that are set in Mask. Don't resize. This computes "*this &= ~Mask".
Definition at line 504 of file BitVector.h.
clearBitsNotInMask()
void llvm::BitVector::clearBitsNotInMask (const uint32_t * Mask, unsigned MaskWords = ~0u) inline
clearBitsNotInMask - Clear a bit in this vector for every '0' bit in Mask. Don't resize. This computes "*this &= Mask".
Definition at line 516 of file BitVector.h.
Referenced by llvm::LiveIntervals::checkRegMaskInterference().
count()
size_type llvm::BitVector::count () const inline
count - Returns the number of bits which are set.
Definition at line 118 of file BitVector.h.
References llvm::CountPopulation_32(), llvm::CountPopulation_64(), llvm_unreachable, and size().
Referenced by LowerVectorBroadcast().
empty()
bool llvm::BitVector::empty () const inline
empty - Tests whether there are no bits in this bitvector.
Definition at line 112 of file BitVector.h.
find_first()
int llvm::BitVector::find_first () const inline
find_first - Returns the index of the first set bit, -1 if none of the bits are set.
Definition at line 158 of file BitVector.h.
References llvm::countTrailingZeros(), llvm_unreachable, and size().
Referenced by llvm::TargetLoweringBase::findRepresentativeClass(), llvm::RegScavenger::initRegState(), and llvm::Mips16InstrInfo::loadImmediate().
find_next()
int llvm::BitVector::find_next (unsigned Prev) const inline
find_next - Returns the index of the next set bit following the "Prev" bit. Returns -1 if the next set bit is not found.
Definition at line 172 of file BitVector.h.
References llvm::countTrailingZeros(), llvm_unreachable, and size().
Referenced by llvm::TargetLoweringBase::findRepresentativeClass(), and llvm::RegScavenger::initRegState().
flip() [1/2]
BitVector & llvm::BitVector::flip () inline
Definition at line 315 of file BitVector.h.
References BitVector(), and size().
Referenced by llvm::TargetRegisterInfo::getAllocatableSet().
flip() [2/2]
BitVector & llvm::BitVector::flip (unsigned Idx) inline
Definition at line 322 of file BitVector.h.
References BitVector().
none()
bool llvm::BitVector::none () const inline
none - Returns true if none of the bits are set.
Definition at line 152 of file BitVector.h.
References any().
Referenced by llvm::SelectionDAG::getVectorShuffle(), llvm::TargetLowering::isConstFalseVal(), isConstOrConstSplat(), isConstOrConstSplatFP(), and llvm::TargetLowering::isConstTrueVal().
operator!=()
bool llvm::BitVector::operator!= (const BitVector & RHS) const inline
Definition at line 375 of file BitVector.h.
References BitVector().
operator&=()
BitVector & llvm::BitVector::operator&= (const BitVector & RHS) inline
Intersection, union, disjoint union.
Definition at line 380 of file BitVector.h.
References BitVector(), and size().
operator=() [1/2]
const BitVector & llvm::BitVector::operator= (BitVector && RHS) inline
Definition at line 465 of file BitVector.h.
References BitVector().
operator=() [2/2]
const BitVector & llvm::BitVector::operator= (const BitVector & RHS) inline
Definition at line 440 of file BitVector.h.
References BitVector(), and size().
operator==()
bool llvm::BitVector::operator== (const BitVector & RHS) const inline
Definition at line 354 of file BitVector.h.
References BitVector(), and size().
operator[]() [1/2]
reference llvm::BitVector::operator[] (unsigned Idx) inline
Definition at line 328 of file BitVector.h.
operator[]() [2/2]
bool llvm::BitVector::operator[] (unsigned Idx) const inline
Definition at line 333 of file BitVector.h.
operator^=()
BitVector & llvm::BitVector::operator^= (const BitVector & RHS) inline
Definition at line 431 of file BitVector.h.
References BitVector(), resize(), and size().
operator|=()
BitVector & llvm::BitVector::operator|= (const BitVector & RHS) inline
Definition at line 423 of file BitVector.h.
References BitVector(), resize(), and size().
reserve()
void llvm::BitVector::reserve (unsigned N) inline
Definition at line 229 of file BitVector.h.
References N.
Referenced by llvm::SmallBitVector::reserve().
reset() [1/4]
BitVector & llvm::BitVector::reset () inline
Definition at line 276 of file BitVector.h.
References BitVector().
Referenced by llvm::ScheduleDAGInstrs::fixupKills(), llvm::MachineFrameInfo::getPristineRegs(), llvm::Mips16InstrInfo::loadImmediate(), and llvm::RegScavenger::scavengeRegister().
reset() [2/4]
BitVector & llvm::BitVector::reset (const BitVector & RHS) inline
reset - Reset bits that are set in RHS. Same as *this &= ~RHS.
Definition at line 397 of file BitVector.h.
References BitVector(), and size().
reset() [3/4]
BitVector & llvm::BitVector::reset (unsigned I, unsigned E) inline
reset - Efficiently reset a range of bits in [I, E)
Definition at line 287 of file BitVector.h.
References BitVector(), I, llvm::RoundUpToAlignment(), and size().
reset() [4/4]
BitVector & llvm::BitVector::reset (unsigned Idx) inline
Definition at line 281 of file BitVector.h.
References BitVector().
resize()
void llvm::BitVector::resize (unsigned N, bool t = false) inline
resize - Grow or shrink the bitvector.
Definition at line 209 of file BitVector.h.
References N.
Referenced by llvm::LiveIntervals::checkRegMaskInterference(), llvm::BuildVectorSDNode::getSplatValue(), initReachingDef(), operator^=(), and operator|=().
set() [1/3]
BitVector & llvm::BitVector::set () inline
Definition at line 235 of file BitVector.h.
References BitVector().
Referenced by collectChangingRegs(), llvm::ScheduleDAGInstrs::fixupKills(), getAllocatableSetForRC(), llvm::MachineFrameInfo::getPristineRegs(), llvm::RegScavenger::getRegsAvailable(), llvm::AArch64RegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::getReservedRegs(), llvm::HexagonRegisterInfo::getReservedRegs(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::MSP430RegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::R600RegisterInfo::getReservedRegs(), llvm::SIRegisterInfo::getReservedRegs(), llvm::SparcRegisterInfo::getReservedRegs(), llvm::SystemZRegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::XCoreRegisterInfo::getReservedRegs(), initReachingDef(), llvm::SITargetLowering::LowerFormalArguments(), llvm::BranchFolder::OptimizeFunction(), llvm::optimizeGlobalCtorsList(), llvm::SmallBitVector::reserve(), llvm::R600InstrInfo::reserveIndirectRegisters(), llvm::SIInstrInfo::reserveIndirectRegisters(), and trackRegDefsUses().
set() [2/3]
BitVector & llvm::BitVector::set (unsigned I, unsigned E) inline
set - Efficiently set a range of bits in [I, E)
Definition at line 248 of file BitVector.h.
References BitVector(), I, llvm::RoundUpToAlignment(), and size().
set() [3/3]
BitVector & llvm::BitVector::set (unsigned Idx) inline
Definition at line 241 of file BitVector.h.
References BitVector().
setBitsInMask()
void llvm::BitVector::setBitsInMask (const uint32_t * Mask, unsigned MaskWords = ~0u) inline
setBitsInMask - Add '1' bits from Mask to this vector. Don't resize. This computes "*this |= Mask".
Definition at line 498 of file BitVector.h.
Referenced by llvm::TargetLoweringBase::findRepresentativeClass().
setBitsNotInMask()
void llvm::BitVector::setBitsNotInMask (const uint32_t * Mask, unsigned MaskWords = ~0u) inline
setBitsNotInMask - Add a bit to this vector for every '0' bit in Mask. Don't resize. This computes "*this |= ~Mask".
Definition at line 510 of file BitVector.h.
Referenced by trackRegDefsUses().
size()
size_type llvm::BitVector::size () const inline
size - Returns the number of bits in this bitvector.
Definition at line 115 of file BitVector.h.
Referenced by any(), anyCommon(), BitVector(), count(), find_first(), find_next(), flip(), operator&=(), operator=(), operator==(), operator^=(), operator|=(), llvm::BranchFolder::OptimizeFunction(), reset(), reset(), llvm::RegisterClassInfo::runOnMachineFunction(), set(), and test().
swap()
void llvm::BitVector::swap (BitVector & RHS) inline
Definition at line 478 of file BitVector.h.
References BitVector(), and std::swap().
Referenced by std::swap().
test() [1/2]
bool llvm::BitVector::test (const BitVector & RHS) const inline
test - Check if (This - RHS) is zero. This is the same as reset(RHS) and any().
Definition at line 408 of file BitVector.h.
References BitVector(), and size().
test() [2/2]
bool llvm::BitVector::test (unsigned Idx) const inline
Definition at line 339 of file BitVector.h.
Referenced by addLiveInRegs(), llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), llvm::calculateDbgValueHistory(), llvm::ScheduleDAGInstrs::fixupKills(), llvm::ARMBaseRegisterInfo::getReservedRegs(), initReachingDef(), llvm::MachineRegisterInfo::isReserved(), llvm::BranchFolder::OptimizeFunction(), llvm::AggressiveAntiDepBreaker::StartBlock(), and llvm::CriticalAntiDepBreaker::StartBlock().
The documentation for this class was generated from the following file:
BitVector.h