LLVM: llvm::MipsTargetStreamer Class Reference
LLVM API Documentation
llvm::MipsTargetStreamer Class Reference
#include <MipsTargetStreamer.h>
Public Member Functions
MipsTargetStreamer (MCStreamer &S)
virtual void emitDirectiveSetMicroMips ()
virtual void emitDirectiveSetNoMicroMips ()
virtual void emitDirectiveSetMips16 ()
virtual void emitDirectiveSetNoMips16 ()
virtual void emitDirectiveSetReorder ()
virtual void emitDirectiveSetNoReorder ()
virtual void emitDirectiveSetMacro ()
virtual void emitDirectiveSetNoMacro ()
virtual void emitDirectiveSetMsa ()
virtual void emitDirectiveSetNoMsa ()
virtual void emitDirectiveSetAt ()
virtual void emitDirectiveSetNoAt ()
virtual void emitDirectiveEnd (StringRef Name)
virtual void emitDirectiveEnt (const MCSymbol &Symbol)
virtual void emitDirectiveAbiCalls ()
virtual void emitDirectiveNaN2008 ()
virtual void emitDirectiveNaNLegacy ()
virtual void emitDirectiveOptionPic0 ()
virtual void emitDirectiveOptionPic2 ()
virtual void emitFrame (unsigned StackReg, unsigned StackSize, unsigned ReturnReg)
virtual void emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff)
virtual void emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff)
virtual void emitDirectiveSetArch (StringRef Arch)
virtual void emitDirectiveSetMips0 ()
virtual void emitDirectiveSetMips1 ()
virtual void emitDirectiveSetMips2 ()
virtual void emitDirectiveSetMips3 ()
virtual void emitDirectiveSetMips4 ()
virtual void emitDirectiveSetMips5 ()
virtual void emitDirectiveSetMips32 ()
virtual void emitDirectiveSetMips32R2 ()
virtual void emitDirectiveSetMips32R6 ()
virtual void emitDirectiveSetMips64 ()
virtual void emitDirectiveSetMips64R2 ()
virtual void emitDirectiveSetMips64R6 ()
virtual void emitDirectiveSetDsp ()
virtual void emitDirectiveSetNoDsp ()
virtual void emitDirectiveSetPop ()
virtual void emitDirectiveSetPush ()
virtual void emitDirectiveCpLoad (unsigned RegNo)
virtual void emitDirectiveCpsetup (unsigned RegNo, int RegOrOffset, const MCSymbol &Sym, bool IsReg)
virtual void emitDirectiveModuleFP (MipsABIFlagsSection::FpABIKind Value, bool Is32BitABI)
void emitDirectiveModuleFP ()
virtual void emitDirectiveModuleOddSPReg (bool Enabled, bool IsO32ABI)
virtual void emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value)
virtual void emitMipsAbiFlags ()
void forbidModuleDirective ()
bool isModuleDirectiveAllowed ()
template<class PredicateLibrary>
void updateABIInfo (const PredicateLibrary &P)
MipsABIFlagsSection & getABIFlagsSection ()
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
const MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void finish ()
Protected Attributes
MipsABIFlagsSection ABIFlagsSection
bool GPRInfoSet
unsigned GPRBitMask
int GPROffset
bool FPRInfoSet
unsigned FPRBitMask
int FPROffset
bool FrameInfoSet
int FrameOffset
unsigned FrameReg
unsigned ReturnReg
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 22 of file MipsTargetStreamer.h.
Constructor & Destructor Documentation
MipsTargetStreamer()
MipsTargetStreamer::MipsTargetStreamer (MCStreamer & S)
Definition at line 31 of file MipsTargetStreamer.cpp.
References FPRInfoSet, FrameInfoSet, GPRInfoSet, llvm::MCTargetStreamer::MCTargetStreamer(), and true.
Referenced by llvm::MipsTargetAsmStreamer::MipsTargetAsmStreamer(), and llvm::MipsTargetELFStreamer::MipsTargetELFStreamer().
Member Function Documentation
emitDirectiveAbiCalls()
void MipsTargetStreamer::emitDirectiveAbiCalls () virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 49 of file MipsTargetStreamer.cpp.
emitDirectiveCpLoad()
void MipsTargetStreamer::emitDirectiveCpLoad (unsigned RegNo) virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 78 of file MipsTargetStreamer.cpp.
emitDirectiveCpsetup()
void MipsTargetStreamer::emitDirectiveCpsetup (unsigned RegNo, int RegOrOffset, const MCSymbol & Sym, bool IsReg) virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 79 of file MipsTargetStreamer.cpp.
emitDirectiveEnd()
void MipsTargetStreamer::emitDirectiveEnd (StringRef Name) virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 47 of file MipsTargetStreamer.cpp.
References Name.
Referenced by llvm::MipsAsmPrinter::EmitFunctionBodyEnd().
emitDirectiveEnt()
void MipsTargetStreamer::emitDirectiveEnt (const MCSymbol & Symbol) virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 48 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel().
emitDirectiveModuleFP() [1/2]
void llvm::MipsTargetStreamer::emitDirectiveModuleFP () inline
Emit a '.module fp=value' directive using the current values of the .MIPS.abiflags section.
Definition at line 83 of file MipsTargetStreamer.h.
References ABIFlagsSection, and emitDirectiveModuleFP().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveModuleFP(), and emitDirectiveModuleFP().
emitDirectiveModuleFP() [2/2]
virtual void llvm::MipsTargetStreamer::emitDirectiveModuleFP (MipsABIFlagsSection::FpABIKind Value, bool Is32BitABI) inline virtual
Emit a '.module fp=value' directive using the given values. Updates the .MIPS.abiflags section
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 76 of file MipsTargetStreamer.h.
References ABIFlagsSection.
emitDirectiveModuleOddSPReg()
void MipsTargetStreamer::emitDirectiveModuleOddSPReg (bool Enabled, bool IsO32ABI) virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 82 of file MipsTargetStreamer.cpp.
References Enabled, and llvm::report_fatal_error().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveModuleOddSPReg(), and llvm::MipsTargetELFStreamer::emitDirectiveModuleOddSPReg().
emitDirectiveNaN2008()
void MipsTargetStreamer::emitDirectiveNaN2008 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 50 of file MipsTargetStreamer.cpp.
emitDirectiveNaNLegacy()
void MipsTargetStreamer::emitDirectiveNaNLegacy () virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 51 of file MipsTargetStreamer.cpp.
emitDirectiveOptionPic0()
void MipsTargetStreamer::emitDirectiveOptionPic0 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 52 of file MipsTargetStreamer.cpp.
emitDirectiveOptionPic2()
void MipsTargetStreamer::emitDirectiveOptionPic2 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 53 of file MipsTargetStreamer.cpp.
emitDirectiveSetArch()
void MipsTargetStreamer::emitDirectiveSetArch (StringRef Arch) virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 59 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetArch().
emitDirectiveSetAt()
void MipsTargetStreamer::emitDirectiveSetAt () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 45 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetAt(), and llvm::MipsAsmPrinter::EmitFunctionBodyEnd().
emitDirectiveSetDsp()
void MipsTargetStreamer::emitDirectiveSetDsp () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 76 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetDsp().
emitDirectiveSetFp()
virtual void llvm::MipsTargetStreamer::emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value) inline virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 89 of file MipsTargetStreamer.h.
emitDirectiveSetMacro()
void MipsTargetStreamer::emitDirectiveSetMacro () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 41 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMacro(), and llvm::MipsAsmPrinter::EmitFunctionBodyEnd().
emitDirectiveSetMicroMips()
void MipsTargetStreamer::emitDirectiveSetMicroMips () virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 35 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel().
emitDirectiveSetMips0()
void MipsTargetStreamer::emitDirectiveSetMips0 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 62 of file MipsTargetStreamer.cpp.
emitDirectiveSetMips1()
void MipsTargetStreamer::emitDirectiveSetMips1 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 63 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips1().
emitDirectiveSetMips16()
void MipsTargetStreamer::emitDirectiveSetMips16 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 37 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel().
emitDirectiveSetMips2()
void MipsTargetStreamer::emitDirectiveSetMips2 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 64 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips2().
emitDirectiveSetMips3()
void MipsTargetStreamer::emitDirectiveSetMips3 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 65 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips3().
emitDirectiveSetMips32()
void MipsTargetStreamer::emitDirectiveSetMips32 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 68 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips32().
emitDirectiveSetMips32R2()
void MipsTargetStreamer::emitDirectiveSetMips32R2 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 69 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips32R2().
emitDirectiveSetMips32R6()
void MipsTargetStreamer::emitDirectiveSetMips32R6 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 70 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips32R6().
emitDirectiveSetMips4()
void MipsTargetStreamer::emitDirectiveSetMips4 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 66 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips4().
emitDirectiveSetMips5()
void MipsTargetStreamer::emitDirectiveSetMips5 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 67 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips5().
emitDirectiveSetMips64()
void MipsTargetStreamer::emitDirectiveSetMips64 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 71 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips64().
emitDirectiveSetMips64R2()
void MipsTargetStreamer::emitDirectiveSetMips64R2 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 72 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips64R2().
emitDirectiveSetMips64R6()
void MipsTargetStreamer::emitDirectiveSetMips64R6 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 73 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMips64R6().
emitDirectiveSetMsa()
void MipsTargetStreamer::emitDirectiveSetMsa () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 43 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetMsa().
emitDirectiveSetNoAt()
void MipsTargetStreamer::emitDirectiveSetNoAt () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 46 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoAt(), and llvm::MipsAsmPrinter::EmitFunctionBodyStart().
emitDirectiveSetNoDsp()
void MipsTargetStreamer::emitDirectiveSetNoDsp () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 77 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoDsp().
emitDirectiveSetNoMacro()
void MipsTargetStreamer::emitDirectiveSetNoMacro () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 42 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoMacro(), and llvm::MipsAsmPrinter::EmitFunctionBodyStart().
emitDirectiveSetNoMicroMips()
void MipsTargetStreamer::emitDirectiveSetNoMicroMips () virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 36 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionEntryLabel().
emitDirectiveSetNoMips16()
void MipsTargetStreamer::emitDirectiveSetNoMips16 () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 38 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoMips16(), and llvm::MipsAsmPrinter::EmitFunctionEntryLabel().
emitDirectiveSetNoMsa()
void MipsTargetStreamer::emitDirectiveSetNoMsa () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 44 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetNoMsa().
emitDirectiveSetNoReorder()
void MipsTargetStreamer::emitDirectiveSetNoReorder () virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 40 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::EmitFunctionBodyStart().
emitDirectiveSetPop()
void MipsTargetStreamer::emitDirectiveSetPop () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 74 of file MipsTargetStreamer.cpp.
emitDirectiveSetPush()
void MipsTargetStreamer::emitDirectiveSetPush () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 75 of file MipsTargetStreamer.cpp.
emitDirectiveSetReorder()
void MipsTargetStreamer::emitDirectiveSetReorder () virtual
Reimplemented in llvm::MipsTargetAsmStreamer.
Definition at line 39 of file MipsTargetStreamer.cpp.
References forbidModuleDirective().
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveSetReorder(), and llvm::MipsAsmPrinter::EmitFunctionBodyEnd().
emitFMask()
void MipsTargetStreamer::emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 57 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::printSavedRegsBitmask().
emitFrame()
void MipsTargetStreamer::emitFrame (unsigned StackReg, unsigned StackSize, unsigned ReturnReg) virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 54 of file MipsTargetStreamer.cpp.
References ReturnReg.
emitMask()
void MipsTargetStreamer::emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 56 of file MipsTargetStreamer.cpp.
Referenced by llvm::MipsAsmPrinter::printSavedRegsBitmask().
emitMipsAbiFlags()
virtual void llvm::MipsTargetStreamer::emitMipsAbiFlags () inline virtual
Reimplemented in llvm::MipsTargetAsmStreamer, and llvm::MipsTargetELFStreamer.
Definition at line 90 of file MipsTargetStreamer.h.
forbidModuleDirective()
void llvm::MipsTargetStreamer::forbidModuleDirective () inline
Definition at line 91 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveCpLoad(), llvm::MipsTargetELFStreamer::emitDirectiveCpLoad(), llvm::MipsTargetAsmStreamer::emitDirectiveCpsetup(), llvm::MipsTargetELFStreamer::emitDirectiveCpsetup(), emitDirectiveSetArch(), emitDirectiveSetAt(), emitDirectiveSetDsp(), emitDirectiveSetMacro(), llvm::MipsTargetAsmStreamer::emitDirectiveSetMicroMips(), llvm::MipsTargetELFStreamer::emitDirectiveSetMicroMips(), emitDirectiveSetMips1(), llvm::MipsTargetAsmStreamer::emitDirectiveSetMips16(), llvm::MipsTargetELFStreamer::emitDirectiveSetMips16(), emitDirectiveSetMips2(), emitDirectiveSetMips3(), emitDirectiveSetMips32(), emitDirectiveSetMips32R2(), emitDirectiveSetMips32R6(), emitDirectiveSetMips4(), emitDirectiveSetMips5(), emitDirectiveSetMips64(), emitDirectiveSetMips64R2(), emitDirectiveSetMips64R6(), emitDirectiveSetMsa(), emitDirectiveSetNoAt(), emitDirectiveSetNoDsp(), emitDirectiveSetNoMacro(), llvm::MipsTargetAsmStreamer::emitDirectiveSetNoMicroMips(), llvm::MipsTargetELFStreamer::emitDirectiveSetNoMicroMips(), emitDirectiveSetNoMips16(), emitDirectiveSetNoMsa(), llvm::MipsTargetAsmStreamer::emitDirectiveSetNoReorder(), llvm::MipsTargetELFStreamer::emitDirectiveSetNoReorder(), emitDirectiveSetReorder(), and llvm::MipsAsmPrinter::EmitInstruction().
getABIFlagsSection()
MipsABIFlagsSection & llvm::MipsTargetStreamer::getABIFlagsSection () inline
Definition at line 101 of file MipsTargetStreamer.h.
References ABIFlagsSection.
isModuleDirectiveAllowed()
bool llvm::MipsTargetStreamer::isModuleDirectiveAllowed () inline
Definition at line 92 of file MipsTargetStreamer.h.
updateABIInfo()
template<class PredicateLibrary> void llvm::MipsTargetStreamer::updateABIInfo (const PredicateLibrary & P) inline
Definition at line 97 of file MipsTargetStreamer.h.
References ABIFlagsSection, and P.
Member Data Documentation
ABIFlagsSection
MipsABIFlagsSection llvm::MipsTargetStreamer::ABIFlagsSection protected
Definition at line 104 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveModuleFP(), emitDirectiveModuleFP(), emitDirectiveModuleFP(), llvm::MipsTargetELFStreamer::emitDirectiveModuleOddSPReg(), llvm::MipsTargetAsmStreamer::emitDirectiveSetFp(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), getABIFlagsSection(), and updateABIInfo().
FPRBitMask
unsigned llvm::MipsTargetStreamer::FPRBitMask protected
Definition at line 111 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitFMask().
FPRInfoSet
bool llvm::MipsTargetStreamer::FPRInfoSet protected
Definition at line 110 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitDirectiveEnt(), llvm::MipsTargetELFStreamer::emitFMask(), and MipsTargetStreamer().
FPROffset
int llvm::MipsTargetStreamer::FPROffset protected
Definition at line 112 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitFMask().
FrameInfoSet
bool llvm::MipsTargetStreamer::FrameInfoSet protected
Definition at line 114 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitDirectiveEnt(), llvm::MipsTargetELFStreamer::emitFrame(), and MipsTargetStreamer().
FrameOffset
int llvm::MipsTargetStreamer::FrameOffset protected
Definition at line 115 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitFrame().
FrameReg
unsigned llvm::MipsTargetStreamer::FrameReg protected
Definition at line 116 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitFrame().
GPRBitMask
unsigned llvm::MipsTargetStreamer::GPRBitMask protected
Definition at line 107 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitMask().
GPRInfoSet
bool llvm::MipsTargetStreamer::GPRInfoSet protected
Definition at line 106 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetELFStreamer::emitDirectiveEnt(), llvm::MipsTargetELFStreamer::emitMask(), and MipsTargetStreamer().
GPROffset
int llvm::MipsTargetStreamer::GPROffset protected
Definition at line 108 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), and llvm::MipsTargetELFStreamer::emitMask().
ReturnReg
unsigned llvm::MipsTargetStreamer::ReturnReg protected
Definition at line 117 of file MipsTargetStreamer.h.
Referenced by llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MipsTargetAsmStreamer::emitFrame(), llvm::MipsTargetELFStreamer::emitFrame(), and emitFrame().
The documentation for this class was generated from the following files:
MipsTargetStreamer.h
MipsTargetStreamer.cpp