LLVM: llvm::MipsDAGToDAGISel Class Reference
LLVM API Documentation
llvm::MipsDAGToDAGISel Class Reference abstract
#include <MipsISelDAGToDAG.h>
Public Member Functions
MipsDAGToDAGISel (MipsTargetMachine &TM)
const char * getPassName () const override
bool runOnMachineFunction (MachineFunction &MF) override
Public Member Functions inherited from llvm::SelectionDAGISel
SelectionDAGISel (TargetMachine &tm, CodeGenOpt::Level OL=CodeGenOpt::Default)
virtual ~SelectionDAGISel ()
const TargetLowering * getTargetLowering () const
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnMachineFunction (MachineFunction &MF) override
virtual void EmitFunctionEntryCode ()
virtual void PreprocessISelDAG ()
virtual void PostprocessISelDAG ()
virtual bool IsProfitableToFold (SDValue N, SDNode *U, SDNode *Root) const
bool CheckAndMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
bool CheckOrMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
virtual bool CheckPatternPredicate (unsigned PredNo) const
virtual bool CheckNodePredicate (SDNode *N, unsigned PredNo) const
virtual bool CheckComplexPattern (SDNode *Root, SDNode *Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > &Result)
virtual SDValue RunSDNodeXForm (SDValue V, unsigned XFormNo)
SDNode * SelectCodeCommon (SDNode *NodeToMatch, const unsigned char *MatcherTable, unsigned TableSize)
virtual bool ComplexPatternFuncMutatesDAG () const
Return true if complex patterns for this target can mutate the DAG.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Protected Member Functions
SDNode * getGlobalBaseReg ()
Protected Member Functions inherited from llvm::SelectionDAGISel
void ReplaceUses (SDValue F, SDValue T)
void ReplaceUses (const SDValue *F, const SDValue *T, unsigned Num)
void ReplaceUses (SDNode *F, SDNode *T)
void SelectInlineAsmMemoryOperands (std::vector< SDValue > &Ops)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Protected Attributes
const MipsSubtarget * Subtarget
Protected Attributes inherited from llvm::SelectionDAGISel
unsigned DAGSize
Additional Inherited Members
Public Types inherited from llvm::SelectionDAGISel
enum BuiltinOpcodes {
OPC_Scope , OPC_RecordNode , OPC_RecordChild0 , OPC_RecordChild1 ,
OPC_RecordChild2 , OPC_RecordChild3 , OPC_RecordChild4 , OPC_RecordChild5 ,
OPC_RecordChild6 , OPC_RecordChild7 , OPC_RecordMemRef , OPC_CaptureGlueInput ,
OPC_MoveChild , OPC_MoveParent , OPC_CheckSame , OPC_CheckChild0Same ,
OPC_CheckChild1Same , OPC_CheckChild2Same , OPC_CheckChild3Same , OPC_CheckPatternPredicate ,
OPC_CheckPredicate , OPC_CheckOpcode , OPC_SwitchOpcode , OPC_CheckType ,
OPC_SwitchType , OPC_CheckChild0Type , OPC_CheckChild1Type , OPC_CheckChild2Type ,
OPC_CheckChild3Type , OPC_CheckChild4Type , OPC_CheckChild5Type , OPC_CheckChild6Type ,
OPC_CheckChild7Type , OPC_CheckInteger , OPC_CheckChild0Integer , OPC_CheckChild1Integer ,
OPC_CheckChild2Integer , OPC_CheckChild3Integer , OPC_CheckChild4Integer , OPC_CheckCondCode ,
OPC_CheckValueType , OPC_CheckComplexPat , OPC_CheckAndImm , OPC_CheckOrImm ,
OPC_CheckFoldableChainNode , OPC_EmitInteger , OPC_EmitRegister , OPC_EmitRegister2 ,
OPC_EmitConvertToTarget , OPC_EmitMergeInputChains , OPC_EmitMergeInputChains1_0 , OPC_EmitMergeInputChains1_1 ,
OPC_EmitCopyToReg , OPC_EmitNodeXForm , OPC_EmitNode , OPC_MorphNodeTo ,
OPC_MarkGlueResults , OPC_CompleteMatch
}
enum {
OPFL_None = 0 , OPFL_Chain = 1 , OPFL_GlueInput = 2 , OPFL_GlueOutput = 4 ,
OPFL_MemRefs = 8 , OPFL_Variadic0 = 1<<4 , OPFL_Variadic1 = 2<<4 , OPFL_Variadic2 = 3<<4 ,
OPFL_Variadic3 = 4<<4 , OPFL_Variadic4 = 5<<4 , OPFL_Variadic5 = 6<<4 , OPFL_Variadic6 = 7<<4 ,
OPFL_VariadicInfo = OPFL_Variadic6
}
Static Public Member Functions inherited from llvm::SelectionDAGISel
static bool IsLegalToFold (SDValue N, SDNode *U, SDNode *Root, CodeGenOpt::Level OptLevel, bool IgnoreChains=false)
static int getNumFixedFromVariadicInfo (unsigned Flags)
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::SelectionDAGISel
TargetMachine & TM
const TargetLibraryInfo * LibInfo
FunctionLoweringInfo * FuncInfo
MachineFunction * MF
MachineRegisterInfo * RegInfo
SelectionDAG * CurDAG
SelectionDAGBuilder * SDB
AliasAnalysis * AA
GCFunctionInfo * GFI
CodeGenOpt::Level OptLevel
const TargetInstrInfo * TII
const TargetLowering * TLI
Static Public Attributes inherited from llvm::SelectionDAGISel
static char ID = 0
Detailed Description
Definition at line 32 of file MipsISelDAGToDAG.h.
Constructor & Destructor Documentation
MipsDAGToDAGISel()
llvm::MipsDAGToDAGISel::MipsDAGToDAGISel (MipsTargetMachine & TM) inline explicit
Definition at line 34 of file MipsISelDAGToDAG.h.
References llvm::SelectionDAGISel::SelectionDAGISel(), Subtarget, and llvm::SelectionDAGISel::TM.
Referenced by llvm::Mips16DAGToDAGISel::Mips16DAGToDAGISel(), and llvm::MipsSEDAGToDAGISel::MipsSEDAGToDAGISel().
Member Function Documentation
getGlobalBaseReg()
SDNode * MipsDAGToDAGISel::getGlobalBaseReg () protected
getGlobalBaseReg - Output the instructions required to put the GOT address into a register.
Definition at line 60 of file MipsISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::CurDAG, getGlobalBaseReg(), llvm::SelectionDAGISel::getTargetLowering(), and llvm::SelectionDAGISel::MF.
Referenced by getGlobalBaseReg().
getPassName()
const char * llvm::MipsDAGToDAGISel::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 38 of file MipsISelDAGToDAG.h.
runOnMachineFunction()
bool MipsDAGToDAGISel::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 49 of file MipsISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::MF, llvm::SelectionDAGISel::runOnMachineFunction(), Subtarget, and llvm::SelectionDAGISel::TM.
Member Data Documentation
Subtarget
const MipsSubtarget* llvm::MipsDAGToDAGISel::Subtarget protected
Keep a pointer to the MipsSubtarget around so that we can make the right decision when generating code for different targets.
Definition at line 49 of file MipsISelDAGToDAG.h.
Referenced by MipsDAGToDAGISel(), and runOnMachineFunction().
The documentation for this class was generated from the following files:
MipsISelDAGToDAG.h
MipsISelDAGToDAG.cpp