LLVM: llvm::sampleprof::SampleProfileWriter Class Reference
LLVM API Documentation
llvm::sampleprof::SampleProfileWriter Class Reference abstract
Sample-based profile writer. Base class.
#include <SampleProfWriter.h>
Public Member Functions
SampleProfileWriter (StringRef Filename, std::error_code &EC, sys::fs::OpenFlags Flags)
virtual ~SampleProfileWriter ()
virtual bool write (StringRef FName, const FunctionSamples &S)=0
Write sample profiles in S for function FName.
bool write (const Function &F, const FunctionSamples &S)
Write sample profiles in S for function F.
bool write (const Module &M, StringMap< FunctionSamples > &P)
Write all the sample profiles for all the functions in M.
bool write (StringMap< FunctionSamples > &ProfileMap)
Write all the sample profiles in the given map of samples.
Static Public Member Functions
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (StringRef Filename, SampleProfileFormat Format)
Profile writer factory. Create a new writer based on the value of Format.
Protected Attributes
raw_fd_ostream OS
Output stream where to emit the profile to.
Detailed Description
Sample-based profile writer. Base class.
Definition at line 31 of file SampleProfWriter.h.
Constructor & Destructor Documentation
SampleProfileWriter()
llvm::sampleprof::SampleProfileWriter::SampleProfileWriter (StringRef Filename, std::error_code & EC, sys::fs::OpenFlags Flags) inline
Definition at line 33 of file SampleProfWriter.h.
References OS.
Referenced by llvm::sampleprof::SampleProfileWriterBinary::SampleProfileWriterBinary(), and llvm::sampleprof::SampleProfileWriterText::SampleProfileWriterText().
~SampleProfileWriter()
virtual llvm::sampleprof::SampleProfileWriter::~SampleProfileWriter () inline virtual
Definition at line 36 of file SampleProfWriter.h.
Member Function Documentation
create()
ErrorOr< std::unique_ptr< SampleProfileWriter > > SampleProfileWriter::create (StringRef Filename, SampleProfileFormat Format) static
Profile writer factory. Create a new writer based on the value of Format.
Create a sample profile writer based on the specified format.
Parameters
Filename The file to create.
Writer The writer to instantiate according to the specified format.
Format Encoding format for the profile file.
Returns
an error code indicating the status of the created writer.
Definition at line 111 of file SampleProfWriter.cpp.
References llvm::sampleprof::SPF_Binary, llvm::sampleprof::SPF_Text, and llvm::unrecognized_format.
write() [1/4]
bool llvm::sampleprof::SampleProfileWriter::write (const Function & F, const FunctionSamples & S) inline
Write sample profiles in S for function F.
Definition at line 44 of file SampleProfWriter.h.
References F, and write().
write() [2/4]
bool llvm::sampleprof::SampleProfileWriter::write (const Module & M, StringMap< FunctionSamples > & P) inline
Write all the sample profiles for all the functions in M.
Returns
true if the file was updated successfully. False, otherwise.
Definition at line 51 of file SampleProfWriter.h.
References F, Name, P, and write().
write() [3/4]
bool llvm::sampleprof::SampleProfileWriter::write (StringMap< FunctionSamples > & ProfileMap) inline
Write all the sample profiles in the given map of samples.
Returns
true if the file was updated successfully. False, otherwise.
Definition at line 63 of file SampleProfWriter.h.
References I, and write().
write() [4/4]
virtual bool llvm::sampleprof::SampleProfileWriter::write (StringRef FName, const FunctionSamples & S) pure virtual
Write sample profiles in S for function FName.
Returns
true if the file was updated successfully. False, otherwise.
Implemented in llvm::sampleprof::SampleProfileWriterBinary, and llvm::sampleprof::SampleProfileWriterText.
Referenced by write(), write(), write(), llvm::sampleprof::SampleProfileWriterBinary::write(), and llvm::sampleprof::SampleProfileWriterText::write().
Member Data Documentation
OS
raw_fd_ostream llvm::sampleprof::SampleProfileWriter::OS protected
Output stream where to emit the profile to.
Definition at line 80 of file SampleProfWriter.h.
Referenced by SampleProfileWriter(), llvm::sampleprof::SampleProfileWriterBinary::SampleProfileWriterBinary(), llvm::sampleprof::SampleProfileWriterBinary::write(), and llvm::sampleprof::SampleProfileWriterText::write().
The documentation for this class was generated from the following files:
SampleProfWriter.h
SampleProfWriter.cpp