LLVM: llvm::CrashRecoveryContextDeleteCleanup< T > Class Template Reference
LLVM API Documentation
llvm::CrashRecoveryContextDeleteCleanup< T > Class Template Reference
#include <CrashRecoveryContext.h>
Public Member Functions
CrashRecoveryContextDeleteCleanup (CrashRecoveryContext *context, T *resource)
void recoverResources () override
Public Member Functions inherited from llvm::CrashRecoveryContextCleanup
virtual ~CrashRecoveryContextCleanup ()
CrashRecoveryContext * getContext () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDeleteCleanup< T >, T >
static CrashRecoveryContextDeleteCleanup< T > * create (T *x)
Public Attributes inherited from llvm::CrashRecoveryContextCleanup
bool cleanupFired
Protected Member Functions inherited from llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDeleteCleanup< T >, T >
CrashRecoveryContextCleanupBase (CrashRecoveryContext *context, T *resource)
Protected Member Functions inherited from llvm::CrashRecoveryContextCleanup
CrashRecoveryContextCleanup (CrashRecoveryContext *context)
Protected Attributes inherited from llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDeleteCleanup< T >, T >
T * resource
Protected Attributes inherited from llvm::CrashRecoveryContextCleanup
CrashRecoveryContext * context
Detailed Description
template<typename T>
class llvm::CrashRecoveryContextDeleteCleanup< T >
Definition at line 161 of file CrashRecoveryContext.h.
Constructor & Destructor Documentation
CrashRecoveryContextDeleteCleanup()
template<typename T> llvm::CrashRecoveryContextDeleteCleanup< T >::CrashRecoveryContextDeleteCleanup (CrashRecoveryContext * context, T * resource) inline
Definition at line 164 of file CrashRecoveryContext.h.
References llvm::CrashRecoveryContextCleanup::context, llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDeleteCleanup< T >, T >::CrashRecoveryContextCleanupBase(), CrashRecoveryContextDeleteCleanup(), llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDeleteCleanup< T >, T >::resource, and T.
Referenced by CrashRecoveryContextDeleteCleanup().
Member Function Documentation
recoverResources()
template<typename T> void llvm::CrashRecoveryContextDeleteCleanup< T >::recoverResources () inline override virtual
Implements llvm::CrashRecoveryContextCleanup.
Definition at line 168 of file CrashRecoveryContext.h.
References llvm::CrashRecoveryContextCleanupBase< CrashRecoveryContextDeleteCleanup< T >, T >::resource.
The documentation for this class was generated from the following file:
CrashRecoveryContext.h