LLVM: llvm::coverage::CoverageData Class Reference
LLVM API Documentation
llvm::coverage::CoverageData Class Reference
Coverage information to be processed or displayed.
#include <CoverageMapping.h>
Public Member Functions
CoverageData ()
CoverageData (StringRef Filename)
CoverageData (CoverageData &&RHS)
StringRef getFilename ()
Get the name of the file this data covers.
std::vector< CoverageSegment >::iterator begin ()
std::vector< CoverageSegment >::iterator end ()
bool empty ()
std::vector< ExpansionRecord > getExpansions ()
Expansions that can be further processed.
Friends
class CoverageMapping
Detailed Description
Coverage information to be processed or displayed.
This represents the coverage of an entire file, expansion, or function. It provides a sequence of CoverageSegments to iterate through, as well as the list of expansions that can be further processed.
Definition at line 327 of file CoverageMapping.h.
Constructor & Destructor Documentation
CoverageData() [1/3]
llvm::coverage::CoverageData::CoverageData () inline
Definition at line 334 of file CoverageMapping.h.
Referenced by CoverageData().
CoverageData() [2/3]
llvm::coverage::CoverageData::CoverageData (StringRef Filename) inline
Definition at line 336 of file CoverageMapping.h.
CoverageData() [3/3]
llvm::coverage::CoverageData::CoverageData (CoverageData && RHS) inline
Definition at line 338 of file CoverageMapping.h.
References CoverageData().
Member Function Documentation
begin()
std::vector< CoverageSegment >::iterator llvm::coverage::CoverageData::begin () inline
Definition at line 345 of file CoverageMapping.h.
References llvm::iplist< NodeTy, Traits >::begin().
empty()
bool llvm::coverage::CoverageData::empty () inline
Definition at line 347 of file CoverageMapping.h.
end()
std::vector< CoverageSegment >::iterator llvm::coverage::CoverageData::end () inline
Definition at line 346 of file CoverageMapping.h.
References llvm::iplist< NodeTy, Traits >::end().
getExpansions()
std::vector< ExpansionRecord > llvm::coverage::CoverageData::getExpansions () inline
Expansions that can be further processed.
Definition at line 350 of file CoverageMapping.h.
getFilename()
StringRef llvm::coverage::CoverageData::getFilename () inline
Get the name of the file this data covers.
Definition at line 343 of file CoverageMapping.h.
Friends And Related Symbol Documentation
CoverageMapping
friend class CoverageMapping friend
Definition at line 331 of file CoverageMapping.h.
References CoverageMapping.
Referenced by CoverageMapping.
The documentation for this class was generated from the following file:
CoverageMapping.h