LLVM: llvm::DIEDelta Class Reference
LLVM API Documentation
llvm::DIEDelta Class Reference
#include <DIE.h>
Public Member Functions
DIEDelta (const MCSymbol *Hi, const MCSymbol *Lo)
void EmitValue (AsmPrinter *AP, dwarf::Form Form) const override
unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const override
void print (raw_ostream &O) const override
Public Member Functions inherited from llvm::DIEValue
Type getType () const
void dump () const
Static Public Member Functions
static bool classof (const DIEValue *D)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum Type {
isInteger , isString , isExpr , isLabel ,
isDelta , isEntry , isTypeSignature , isBlock ,
isLoc , isLocList
}
Protected Member Functions inherited from llvm::DIEValue
DIEValue (Type T)
virtual ~DIEValue ()
Protected Attributes inherited from llvm::DIEValue
Type Ty
Detailed Description
DIEDelta - A simple label difference DIE.
Definition at line 355 of file DIE.h.
Constructor & Destructor Documentation
DIEDelta()
llvm::DIEDelta::DIEDelta (const MCSymbol * Hi, const MCSymbol * Lo) inline
Definition at line 360 of file DIE.h.
References llvm::DIEValue::DIEValue(), and llvm::DIEValue::isDelta.
Member Function Documentation
classof()
bool llvm::DIEDelta::classof (const DIEValue * D) inline static
Definition at line 372 of file DIE.h.
References llvm::DIEValue::DIEValue(), llvm::DIEValue::getType(), and llvm::DIEValue::isDelta.
EmitValue()
void DIEDelta::EmitValue (AsmPrinter * AP, dwarf::Form Form) const override virtual
EmitValue - Emit delta value.
Implements llvm::DIEValue.
Definition at line 329 of file DIE.cpp.
References llvm::AsmPrinter::EmitLabelDifference(), and SizeOf().
print()
void DIEDelta::print (raw_ostream & O) const override virtual
Implements llvm::DIEValue.
Definition at line 343 of file DIE.cpp.
SizeOf()
unsigned DIEDelta::SizeOf (AsmPrinter * AP, dwarf::Form Form) const override virtual
SizeOf - Determine size of delta value in bytes.
Implements llvm::DIEValue.
Definition at line 335 of file DIE.cpp.
References llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_sec_offset, llvm::dwarf::DW_FORM_strp, llvm::AsmPrinter::getDataLayout(), and llvm::DataLayout::getPointerSize().
Referenced by EmitValue().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp