LLVM: llvm::DataLayout Class Reference
LLVM API Documentation
llvm::DataLayout Class Reference
A parsed version of the target data layout string in and methods for querying it.
#include <DataLayout.h>
Public Member Functions
DataLayout (StringRef LayoutDescription)
Constructs a DataLayout from a specification string. See reset().
DataLayout (const Module *M)
Initialize target data from properties stored in the module.
void init (const Module *M)
DataLayout (const DataLayout &DL)
DataLayout & operator= (const DataLayout &DL)
bool operator== (const DataLayout &Other) const
bool operator!= (const DataLayout &Other) const
~DataLayout ()
void reset (StringRef LayoutDescription)
Parse a data layout string (with fallback to default values).
bool isLittleEndian () const
Layout endianness...
bool isBigEndian () const
std::string getStringRepresentation () const
Returns the string representation of the DataLayout.
bool isLegalInteger (unsigned Width) const
Returns true if the specified type is known to be a native integer type supported by the CPU.
bool isIllegalInteger (unsigned Width) const
bool exceedsNaturalStackAlignment (unsigned Align) const
Returns true if the given alignment exceeds the natural stack alignment.
unsigned getStackAlignment () const
bool hasMicrosoftFastStdCallMangling () const
bool hasLinkerPrivateGlobalPrefix () const
const char * getLinkerPrivateGlobalPrefix () const
char getGlobalPrefix () const
const char * getPrivateGlobalPrefix () const
bool fitsInLegalInteger (unsigned Width) const
Returns true if the specified type fits in a native integer type supported by the CPU.
unsigned getPointerABIAlignment (unsigned AS=0) const
unsigned getPointerPrefAlignment (unsigned AS=0) const
unsigned getPointerSize (unsigned AS=0) const
unsigned getPointerSizeInBits (unsigned AS=0) const
unsigned getPointerTypeSizeInBits (Type *) const
unsigned getPointerTypeSize (Type *Ty) const
uint64_t getTypeSizeInBits (Type *Ty) const
Returns the number of bits necessary to hold the specified type.
uint64_t getTypeStoreSize (Type *Ty) const
Returns the maximum number of bytes that may be overwritten by storing the specified type.
uint64_t getTypeStoreSizeInBits (Type *Ty) const
Returns the maximum number of bits that may be overwritten by storing the specified type; always a multiple of 8.
uint64_t getTypeAllocSize (Type *Ty) const
Returns the offset in bytes between successive objects of the specified type, including alignment padding.
uint64_t getTypeAllocSizeInBits (Type *Ty) const
Returns the offset in bits between successive objects of the specified type, including alignment padding; always a multiple of 8.
unsigned getABITypeAlignment (Type *Ty) const
Returns the minimum ABI-required alignment for the specified type.
unsigned getABIIntegerTypeAlignment (unsigned BitWidth) const
Returns the minimum ABI-required alignment for an integer type of the specified bitwidth.
unsigned getPrefTypeAlignment (Type *Ty) const
Returns the preferred stack/global alignment for the specified type.
unsigned getPreferredTypeAlignmentShift (Type *Ty) const
Returns the preferred alignment for the specified type, returned as log2 of the value (a shift amount).
IntegerType * getIntPtrType (LLVMContext &C, unsigned AddressSpace=0) const
Returns an integer type with size at least as big as that of a pointer in the given address space.
Type * getIntPtrType (Type *) const
Returns an integer (vector of integer) type with size at least as big as that of a pointer of the given pointer (vector of pointer) type.
Type * getSmallestLegalIntType (LLVMContext &C, unsigned Width=0) const
Returns the smallest integer type with size at least as big as Width bits.
Type * getLargestLegalIntType (LLVMContext &C) const
Returns the largest legal integer type, or null if none are set.
unsigned getLargestLegalIntTypeSize () const
Returns the size of largest legal integer type size, or 0 if none are set.
uint64_t getIndexedOffset (Type *Ty, ArrayRef< Value * > Indices) const
Returns the offset from the beginning of the type for the specified indices.
const StructLayout * getStructLayout (StructType *Ty) const
Returns a StructLayout object, indicating the alignment of the struct, its size, and the offsets of its fields.
unsigned getPreferredAlignment (const GlobalVariable *GV) const
Returns the preferred alignment of the specified global.
unsigned getPreferredAlignmentLog (const GlobalVariable *GV) const
Returns the preferred alignment of the specified global, returned in log form.
Static Public Member Functions
static const char * getManglingComponent (const Triple &T)
Detailed Description
A parsed version of the target data layout string in and methods for querying it.
The target data layout string is specified by the target - a frontend generating LLVM IR is required to generate the right target data for the target being codegen'd to.
Definition at line 99 of file DataLayout.h.
Constructor & Destructor Documentation
DataLayout() [1/3]
llvm::DataLayout::DataLayout (StringRef LayoutDescription) inline explicit
Constructs a DataLayout from a specification string. See reset().
Definition at line 170 of file DataLayout.h.
References reset().
Referenced by DataLayout(), init(), operator!=(), operator=(), and operator==().
DataLayout() [2/3]
DataLayout::DataLayout (const Module * M) explicit
Initialize target data from properties stored in the module.
Definition at line 366 of file DataLayout.cpp.
References init().
DataLayout() [3/3]
llvm::DataLayout::DataLayout (const DataLayout & DL) inline
Definition at line 179 of file DataLayout.h.
References DataLayout().
~DataLayout()
DataLayout::~DataLayout ()
Definition at line 517 of file DataLayout.cpp.
References clear().
Member Function Documentation
exceedsNaturalStackAlignment()
bool llvm::DataLayout::exceedsNaturalStackAlignment (unsigned Align) const inline
Returns true if the given alignment exceeds the natural stack alignment.
Definition at line 227 of file DataLayout.h.
References Align.
Referenced by enforceKnownAlignment(), and getMemcpyLoadsAndStores().
fitsInLegalInteger()
bool llvm::DataLayout::fitsInLegalInteger (unsigned Width) const inline
Returns true if the specified type fits in a native integer type supported by the CPU.
For example, if the CPU only supports i32 as a native integer type, then i27 fits in a legal integer type but i45 does not.
Definition at line 280 of file DataLayout.h.
Referenced by SwitchToLookupTable().
getABIIntegerTypeAlignment()
unsigned DataLayout::getABIIntegerTypeAlignment (unsigned BitWidth) const
Returns the minimum ABI-required alignment for an integer type of the specified bitwidth.
getABIIntegerTypeAlignment - Return the minimum ABI-required alignment for an integer type of the specified bitwidth.
Definition at line 712 of file DataLayout.cpp.
References llvm::INTEGER_ALIGN.
Referenced by llvm::MachineJumpTableInfo::getEntryAlignment().
getABITypeAlignment()
unsigned DataLayout::getABITypeAlignment (Type * Ty) const
Returns the minimum ABI-required alignment for the specified type.
Definition at line 706 of file DataLayout.cpp.
Referenced by computeKnownBits(), getAdjustedAlignment(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getPreferredAlignment(), llvm::NVPTXTargetLowering::getPrototype(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), getTypeAllocSize(), InlineCallIfPossible(), isDereferenceablePointer(), LLVMABIAlignmentOfType(), LLVMCallFrameAlignmentOfType(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::PPCTargetLowering::PerformDAGCombine(), SRAGlobal(), and XFormVExtractWithShuffleIntoLoad().
getGlobalPrefix()
char llvm::DataLayout::getGlobalPrefix () const inline
Definition at line 245 of file DataLayout.h.
References llvm_unreachable.
getIndexedOffset()
uint64_t DataLayout::getIndexedOffset (Type * Ty, ArrayRef< Value * > Indices) const
Returns the offset from the beginning of the type for the specified indices.
This is used to implement getelementptr.
Definition at line 753 of file DataLayout.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::gep_type_begin(), llvm::Type::getContext(), llvm::StructLayout::getElementOffset(), llvm::Type::getInt32Ty(), getStructLayout(), getTypeAllocSize(), llvm::Type::isPointerTy(), and llvm::ArrayRef< T >::size().
Referenced by SymbolicallyEvaluateGEP().
getIntPtrType() [1/2]
IntegerType * DataLayout::getIntPtrType (LLVMContext & C, unsigned AddressSpace = 0) const
Returns an integer type with size at least as big as that of a pointer in the given address space.
Definition at line 726 of file DataLayout.cpp.
References llvm::IntegerType::get(), and getPointerSizeInBits().
Referenced by CastGEPIndices(), checkStringCopyLibFuncSignature(), CoerceAvailableValueToLoadType(), llvm::ConstantFoldCompareInstOperands(), convertPointerToIntegerType(), convertValue(), llvm::EmitFWrite(), llvm::EmitGEPOffset(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNLen(), llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), EvaluateGEPOffsetExpression(), GetConstantInt(), llvm::IRBuilderBase::getIntPtrTy(), GetStoreValueForLoad(), isEliminableCastPair(), llvm::CastInst::isNoopCast(), llvm::AsmPrinter::lowerConstant(), PerformHeapAllocSRoA(), ReadDataFromGlobal(), SimplifyBranchOnICmpChain(), stripAndComputeConstantOffsets(), SymbolicallyEvaluateGEP(), and TryToOptimizeStoreOfMallocToGlobal().
getIntPtrType() [2/2]
Type * DataLayout::getIntPtrType (Type * Ty) const
Returns an integer (vector of integer) type with size at least as big as that of a pointer of the given pointer (vector of pointer) type.
Definition at line 731 of file DataLayout.cpp.
References llvm::dyn_cast(), llvm::IntegerType::get(), llvm::VectorType::get(), llvm::Type::getContext(), getPointerTypeSizeInBits(), and llvm::Type::isPtrOrPtrVectorTy().
getLargestLegalIntType()
Type * llvm::DataLayout::getLargestLegalIntType (LLVMContext & C) const inline
Returns the largest legal integer type, or null if none are set.
Definition at line 408 of file DataLayout.h.
References llvm::Type::getIntNTy(), and getLargestLegalIntTypeSize().
getLargestLegalIntTypeSize()
unsigned DataLayout::getLargestLegalIntTypeSize () const
Returns the size of largest legal integer type size, or 0 if none are set.
Definition at line 748 of file DataLayout.cpp.
Referenced by getLargestLegalIntType().
getLinkerPrivateGlobalPrefix()
const char * llvm::DataLayout::getLinkerPrivateGlobalPrefix () const inline
Definition at line 239 of file DataLayout.h.
References getPrivateGlobalPrefix().
Referenced by llvm::MachineFunction::getJTISymbol(), and getNameWithPrefixx().
getManglingComponent()
const char * DataLayout::getManglingComponent (const Triple & T) static
Definition at line 155 of file DataLayout.cpp.
References llvm::Triple::x86.
Referenced by computeDataLayout(), computeDataLayout(), and getDataLayoutString().
getPointerABIAlignment()
unsigned DataLayout::getPointerABIAlignment (unsigned AS = 0) const
Layout pointer alignment FIXME: The defaults need to be removed once all of the backends/clients are updated.
Definition at line 607 of file DataLayout.cpp.
References I.
Referenced by llvm::MachineJumpTableInfo::getEntryAlignment().
getPointerPrefAlignment()
unsigned DataLayout::getPointerPrefAlignment (unsigned AS = 0) const
Return target's alignment for stack-based pointers FIXME: The defaults need to be removed once all of the backends/clients are updated.
Definition at line 616 of file DataLayout.cpp.
References I.
Referenced by FindOptimalMemOpLowering(), and getOpenCLAlignment().
getPointerSize()
unsigned DataLayout::getPointerSize (unsigned AS = 0) const
Layout pointer size FIXME: The defaults need to be removed once all of the backends/clients are updated.
Definition at line 625 of file DataLayout.cpp.
References I.
Referenced by addByteCountSuffix(), llvm::AsmPrinter::doFinalization(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::AArch64FrameLowering::emitPrologue(), llvm::MachineJumpTableInfo::getEntrySize(), getPointerSizeInBits(), llvm::DIEEntry::getRefAddrSize(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), isTargetNullPtr(), LLVMPointerSize(), LLVMPointerSizeForAS(), llvm::DIEDelta::SizeOf(), llvm::DIEExpr::SizeOf(), llvm::DIEInteger::SizeOf(), llvm::DIELabel::SizeOf(), and llvm::DIELocList::SizeOf().
getPointerSizeInBits()
unsigned llvm::DataLayout::getPointerSizeInBits (unsigned AS = 0) const inline
Layout pointer size, in bits FIXME: The defaults need to be removed once all of the backends/clients are updated.
Definition at line 305 of file DataLayout.h.
References getPointerSize().
Referenced by llvm::GEPOperator::accumulateConstantOffset(), DecomposeGEPExpression(), getIntPtrType(), getTypeSizeInBits(), llvm::TargetLowering::ParseConstraints(), SimplifyGEPInst(), and llvm::Value::stripAndAccumulateInBoundsConstantOffsets().
getPointerTypeSize()
unsigned llvm::DataLayout::getPointerTypeSize (Type * Ty) const inline
Definition at line 316 of file DataLayout.h.
References getPointerTypeSizeInBits().
Referenced by llvm::AsmPrinter::EmitGlobalVariable().
getPointerTypeSizeInBits()
unsigned DataLayout::getPointerTypeSizeInBits (Type * Ty) const
Layout pointer size, in bits, based on the type. If this function is called with a pointer type, then the type size of the pointer is returned. If this function is called with a vector of pointers, then the type size of the pointer is returned. This should only be called with a pointer or vector of pointers.
Definition at line 634 of file DataLayout.cpp.
References llvm::Type::getScalarType(), getTypeSizeInBits(), llvm::Type::isPointerTy(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by llvm::ConstantFoldInstOperands(), getBitWidth(), getIntPtrType(), getNaturalGEPWithType(), llvm::getOrEnforceKnownAlignment(), llvm::GetPointerBaseWithConstantOffset(), getPointerTypeSize(), llvm::CastInst::isBitOrNoopPointerCastable(), IsConstantOffsetFromGlobal(), and llvm::AsmPrinter::lowerConstant().
getPreferredAlignment()
unsigned DataLayout::getPreferredAlignment (const GlobalVariable * GV) const
Returns the preferred alignment of the specified global.
This includes an explicitly requested alignment (if the global has one).
getPreferredAlignment - Return the preferred alignment of the specified global. This includes an explicitly requested alignment (if the global has one).
Definition at line 793 of file DataLayout.cpp.
References getABITypeAlignment(), llvm::GlobalObject::getAlignment(), llvm::SequentialType::getElementType(), getPrefTypeAlignment(), llvm::GlobalValue::getType(), getTypeSizeInBits(), and llvm::GlobalVariable::hasInitializer().
Referenced by computeKnownBits(), getPreferredAlignmentLog(), and LLVMPreferredAlignmentOfGlobal().
getPreferredAlignmentLog()
unsigned DataLayout::getPreferredAlignmentLog (const GlobalVariable * GV) const
Returns the preferred alignment of the specified global, returned in log form.
This includes an explicitly requested alignment (if the global has one).
getPreferredAlignmentLog - Return the preferred alignment of the specified global, returned in log form. This includes an explicitly requested alignment (if the global has one).
Definition at line 817 of file DataLayout.cpp.
References getPreferredAlignment(), and llvm::Log2_32().
Referenced by getGVAlignmentLog2().
getPreferredTypeAlignmentShift()
unsigned DataLayout::getPreferredTypeAlignmentShift (Type * Ty) const
Returns the preferred alignment for the specified type, returned as log2 of the value (a shift amount).
Definition at line 720 of file DataLayout.cpp.
References Align, getPrefTypeAlignment(), and llvm::Log2_32().
getPrefTypeAlignment()
unsigned DataLayout::getPrefTypeAlignment (Type * Ty) const
Returns the preferred stack/global alignment for the specified type.
This is always at least as good as the ABI alignment.
Definition at line 716 of file DataLayout.cpp.
Referenced by llvm::SelectionDAG::CreateStackTemporary(), getOpenCLAlignment(), getPreferredAlignment(), getPreferredTypeAlignmentShift(), HandleByValArgument(), llvm::isSafeToLoadUnconditionally(), LLVMPreferredAlignmentOfType(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), ReplaceLoadVector(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getPrivateGlobalPrefix()
const char * llvm::DataLayout::getPrivateGlobalPrefix () const inline
Definition at line 258 of file DataLayout.h.
References llvm_unreachable.
Referenced by llvm::ARMAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::MachineFunction::getJTISymbol(), llvm::AsmPrinter::GetJTSetSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), getLinkerPrivateGlobalPrefix(), getNameWithPrefixx(), llvm::MachineFunction::getPICBaseSymbol(), llvm::PPCFunctionInfo::getPICOffsetSymbol(), GetSymbolFromOperand(), llvm::AsmPrinter::GetTempSymbol(), llvm::AsmPrinter::GetTempSymbol(), llvm::MipsAsmPrinter::printOperand(), and llvm::AsmPrinter::PrintSpecial().
getSmallestLegalIntType()
Type * DataLayout::getSmallestLegalIntType (LLVMContext & C, unsigned Width = 0) const
Returns the smallest integer type with size at least as big as Width bits.
Definition at line 741 of file DataLayout.cpp.
References llvm::Type::getIntNTy().
getStackAlignment()
unsigned llvm::DataLayout::getStackAlignment () const inline
Definition at line 231 of file DataLayout.h.
getStringRepresentation()
std::string DataLayout::getStringRepresentation () const
Returns the string representation of the DataLayout.
This representation is in the same format accepted by the string constructor above.
Definition at line 544 of file DataLayout.cpp.
References DefaultAlignments, and llvm::raw_string_ostream::str().
Referenced by LLVMCopyStringRepOfTargetData(), operator==(), and llvm::Module::setDataLayout().
getStructLayout()
const StructLayout * DataLayout::getStructLayout (StructType * Ty) const
Returns a StructLayout object, indicating the alignment of the struct, its size, and the offsets of its fields.
Note that this information is lazily cached.
Definition at line 521 of file DataLayout.cpp.
References llvm::StructType::getNumElements().
Referenced by llvm::GEPOperator::accumulateConstantOffset(), computeArraySize(), computeKnownBits(), llvm::ComputeValueVTs(), DecomposeGEPExpression(), llvm::EmitGEPOffset(), emitGlobalConstantStruct(), EvaluateGEPOffsetExpression(), getIndexedOffset(), getNaturalGEPRecursively(), GetOffsetFromIndex(), getTypePartition(), getTypeSizeInBits(), HasPadding(), llvm::ExecutionEngine::InitializeMemory(), isGEPKnownNonNull(), LLVMElementAtOffset(), LLVMOffsetOfElement(), PerformHeapAllocSRoA(), ReadDataFromGlobal(), SRAGlobal(), stripAggregateTypeWrapping(), SymbolicallyEvaluateGEP(), and TryToOptimizeStoreOfMallocToGlobal().
getTypeAllocSize()
uint64_t llvm::DataLayout::getTypeAllocSize (Type * Ty) const inline
Returns the offset in bytes between successive objects of the specified type, including alignment padding.
This is the amount that alloca reserves for this type. For example, returns 12 or 16 for x86_fp80, depending on alignment.
Definition at line 364 of file DataLayout.h.
References getABITypeAlignment(), getTypeStoreSize(), and llvm::RoundUpToAlignment().
Referenced by llvm::GEPOperator::accumulateConstantOffset(), addByteCountSuffix(), computeArraySize(), computeKnownBits(), llvm::ComputeValueVTs(), DecomposeGEPExpression(), llvm::EmitGEPOffset(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::ExecutionEngine::EmitGlobalVariable(), EvaluateGEPOffsetExpression(), FoldReinterpretLoadFromConstPtr(), getGEPInductionOperand(), getIndexedOffset(), getNaturalGEPRecursively(), getNaturalGEPWithOffset(), GetOffsetFromIndex(), llvm::NVPTXTargetLowering::getPrototype(), llvm::MachineConstantPoolEntry::getSectionKind(), llvm::SparcTargetLowering::getSRetArgSize(), getStrideFromPointer(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), getTypeAllocSizeInBits(), getTypePartition(), INITIALIZE_TM_PASS(), llvm::ExecutionEngine::InitializeMemory(), llvm::InlineFunction(), isGEPKnownNonNull(), llvm::XCoreTargetLowering::isLegalAddressingMode(), isSafeToEliminateVarargsCast(), IsSmallObject(), isStridedPtr(), LLVMABISizeOfType(), llvm::NVPTXTargetLowering::LowerCall(), llvm::AsmPrinter::lowerConstant(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::NVPTXTargetLowering::LowerReturn(), PerformHeapAllocSRoA(), ReadDataFromGlobal(), SimplifyGEPInst(), SRAGlobal(), stripAggregateTypeWrapping(), SymbolicallyEvaluateGEP(), and TryToOptimizeStoreOfMallocToGlobal().
getTypeAllocSizeInBits()
uint64_t llvm::DataLayout::getTypeAllocSizeInBits (Type * Ty) const inline
Returns the offset in bits between successive objects of the specified type, including alignment padding; always a multiple of 8.
This is the amount that alloca reserves for this type. For example, returns 96 or 128 for x86_fp80, depending on alignment.
Definition at line 374 of file DataLayout.h.
References getTypeAllocSize().
Referenced by FoldBitCast(), FoldReinterpretLoadFromConstPtr(), getTypeSizeInBits(), HasPadding(), llvm::NVPTXTargetLowering::LowerCall(), llvm::AsmPrinter::lowerConstant(), and llvm::NVPTXTargetLowering::LowerReturn().
getTypeSizeInBits()
uint64_t llvm::DataLayout::getTypeSizeInBits (Type * Ty) const inline
Returns the number of bits necessary to hold the specified type.
Size examples:
Type SizeInBits StoreSizeInBits AllocSizeInBits[*]
i1 1 8 8 i8 8 8 8 i19 19 24 32 i32 32 32 32 i100 100 104 128 i128 128 128 128 Float 32 32 32 Double 64 64 64 X86_FP80 80 80 96
[*] The alloc size depends on the alignment, and thus on the target. These values are for x86-32 linux.
For example, returns 36 for i36 and 80 for x86_fp80. The type passed must have a size (Type::isSized() must return true).
Definition at line 499 of file DataLayout.h.
References llvm::Type::ArrayTyID, llvm::cast(), llvm::Type::DoubleTyID, llvm::Type::FloatTyID, llvm::Type::FP128TyID, llvm::SequentialType::getElementType(), llvm::Type::getIntegerBitWidth(), llvm::ArrayType::getNumElements(), llvm::VectorType::getNumElements(), llvm::Type::getPointerAddressSpace(), getPointerSizeInBits(), llvm::StructLayout::getSizeInBits(), getStructLayout(), getTypeAllocSizeInBits(), llvm::Type::getTypeID(), getTypeSizeInBits(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, llvm::Type::isSized(), llvm::Type::LabelTyID, llvm_unreachable, llvm::Type::PointerTyID, llvm::Type::PPC_FP128TyID, llvm::Type::StructTyID, llvm::Type::VectorTyID, llvm::Type::X86_FP80TyID, and llvm::Type::X86_MMXTyID.
Referenced by AnalyzeLoadFromClobberingLoad(), AnalyzeLoadFromClobberingStore(), AnalyzeLoadFromClobberingWrite(), CanCoerceMustAliasedValueToLoad(), canConvertValue(), CoerceAvailableValueToLoadType(), computeKnownBits(), ComputeNumSignBits(), ConstantFoldLoadThroughBitcast(), FoldBitCast(), GetMemInstValueForLoad(), getMemSetPatternValue(), getNaturalGEPRecursively(), getPointerTypeSizeInBits(), getPreferredAlignment(), GetStoreValueForLoad(), getTypeSizeInBits(), getTypeStoreSize(), HasPadding(), isIntegerWideningViable(), llvm::AArch64TargetLowering::isLegalAddressingMode(), isSimpleEnoughValueToCommitHelper(), isVectorPromotionViable(), LLVMSizeOfTypeInBits(), llvm::TargetLowering::ParseConstraints(), SimplifyICmpInst(), stripAggregateTypeWrapping(), SymbolicallyEvaluateBinop(), and SymbolicallyEvaluateGEP().
getTypeStoreSize()
uint64_t llvm::DataLayout::getTypeStoreSize (Type * Ty) const inline
Returns the maximum number of bytes that may be overwritten by storing the specified type.
For example, returns 5 for i36 and 10 for x86_fp80.
Definition at line 347 of file DataLayout.h.
References getTypeSizeInBits().
Referenced by AnalyzeLoadFromClobberingLoad(), CanShareConstantPoolEntry(), llvm::IRBuilder< true, TargetFolder >::CreateExtractInteger(), emitGlobalConstantFP(), extractInteger(), llvm::FindAvailableLoadedValue(), GetLoadValueForLoad(), getTypeAllocSize(), getTypeStoreSizeInBits(), HandleByValArgumentInit(), insertInteger(), isDereferenceablePointer(), llvm::Value::isDereferenceablePointer(), isIntegerWideningViableForSlice(), llvm::isSafeToLoadUnconditionally(), LLVMStoreSizeOfType(), llvm::ExecutionEngine::LoadValueFromMemory(), llvm::NVPTXLowerAggrCopies::runOnFunction(), and llvm::ExecutionEngine::StoreValueToMemory().
getTypeStoreSizeInBits()
uint64_t llvm::DataLayout::getTypeStoreSizeInBits (Type * Ty) const inline
Returns the maximum number of bits that may be overwritten by storing the specified type; always a multiple of 8.
For example, returns 40 for i36 and 80 for x86_fp80.
Definition at line 355 of file DataLayout.h.
References getTypeStoreSize().
Referenced by llvm::Value::isDereferenceablePointer(), isIntegerWideningViable(), and isIntegerWideningViableForSlice().
hasLinkerPrivateGlobalPrefix()
bool llvm::DataLayout::hasLinkerPrivateGlobalPrefix () const inline
Definition at line 237 of file DataLayout.h.
Referenced by llvm::AsmPrinter::EmitJumpTableInfo().
hasMicrosoftFastStdCallMangling()
bool llvm::DataLayout::hasMicrosoftFastStdCallMangling () const inline
Definition at line 233 of file DataLayout.h.
init()
void DataLayout::init (const Module * M)
Definition at line 370 of file DataLayout.cpp.
References DataLayout(), llvm::Module::getDataLayout(), and reset().
Referenced by DataLayout().
isBigEndian()
bool llvm::DataLayout::isBigEndian () const inline
Definition at line 202 of file DataLayout.h.
Referenced by CoerceAvailableValueToLoadType(), CollectInsertionElements(), llvm::IRBuilder< true, TargetFolder >::CreateExtractInteger(), emitGlobalConstantFP(), emitGlobalConstantLargeInt(), extractInteger(), GetLoadValueForLoad(), getMemSetPatternValue(), insertInteger(), operator=(), and OptimizeIntToFloatBitCast().
isIllegalInteger()
bool llvm::DataLayout::isIllegalInteger (unsigned Width) const inline
Definition at line 224 of file DataLayout.h.
References isLegalInteger().
isLegalInteger()
bool llvm::DataLayout::isLegalInteger (unsigned Width) const inline
Returns true if the specified type is known to be a native integer type supported by the CPU.
For example, i64 is not native on most 32-bit CPUs and i37 is not native on any known one. This returns false if the integer width is not legal.
The width is specified in bits.
Definition at line 217 of file DataLayout.h.
Referenced by FindLoopCounter(), isIllegalInteger(), isIntegerWideningViable(), and visitIVCast().
isLittleEndian()
bool llvm::DataLayout::isLittleEndian () const inline
Layout endianness...
Definition at line 201 of file DataLayout.h.
Referenced by llvm::ConstantFoldLoadFromConstPtr(), FoldBitCast(), FoldReinterpretLoadFromConstPtr(), GetStoreValueForLoad(), llvm::PPC::getVSPLTImmediate(), llvm::PPC::isVMRGHShuffleMask(), llvm::PPC::isVMRGLShuffleMask(), llvm::PPC::isVPKUHUMShuffleMask(), llvm::PPC::isVPKUWUMShuffleMask(), LLVMByteOrder(), and ReadDataFromGlobal().
operator!=()
bool llvm::DataLayout::operator!= (const DataLayout & Other) const inline
Definition at line 193 of file DataLayout.h.
References DataLayout().
operator=()
DataLayout & llvm::DataLayout::operator= (const DataLayout & DL) inline
Definition at line 181 of file DataLayout.h.
References clear(), DataLayout(), and isBigEndian().
operator==()
bool DataLayout::operator== (const DataLayout & Other) const
Definition at line 378 of file DataLayout.cpp.
References DataLayout(), and getStringRepresentation().
reset()
void DataLayout::reset (StringRef LayoutDescription)
Parse a data layout string (with fallback to default values).
Definition at line 178 of file DataLayout.cpp.
References clear(), and DefaultAlignments.
Referenced by DataLayout(), init(), and llvm::object::IRObjectFile::IRObjectFile().
The documentation for this class was generated from the following files:
DataLayout.h
DataLayout.cpp