LLVM: llvm::object::MachOUniversalBinary::object_iterator Class Reference
LLVM API Documentation
llvm::object::MachOUniversalBinary::object_iterator Class Reference
#include <MachOUniversal.h>
Public Member Functions
object_iterator (const ObjectForArch &Obj)
const ObjectForArch * operator-> () const
bool operator== (const object_iterator &Other) const
bool operator!= (const object_iterator &Other) const
object_iterator & operator++ ()
Detailed Description
Definition at line 68 of file MachOUniversal.h.
Constructor & Destructor Documentation
object_iterator()
llvm::object::MachOUniversalBinary::object_iterator::object_iterator (const ObjectForArch & Obj) inline
Definition at line 71 of file MachOUniversal.h.
Referenced by operator!=(), operator++(), and operator==().
Member Function Documentation
operator!=()
bool llvm::object::MachOUniversalBinary::object_iterator::operator!= (const object_iterator & Other) const inline
Definition at line 79 of file MachOUniversal.h.
References object_iterator().
operator++()
object_iterator & llvm::object::MachOUniversalBinary::object_iterator::operator++ () inline
Definition at line 83 of file MachOUniversal.h.
References object_iterator().
operator->()
const ObjectForArch * llvm::object::MachOUniversalBinary::object_iterator::operator-> () const inline
Definition at line 72 of file MachOUniversal.h.
operator==()
bool llvm::object::MachOUniversalBinary::object_iterator::operator== (const object_iterator & Other) const inline
Definition at line 76 of file MachOUniversal.h.
References object_iterator().
The documentation for this class was generated from the following file:
MachOUniversal.h