LLVM: llvm::TrackingMDRef Class Reference
LLVM API Documentation
llvm::TrackingMDRef Class Reference
Tracking metadata reference.
#include <TrackingMDRef.h>
Public Member Functions
TrackingMDRef ()
TrackingMDRef (Metadata *MD)
TrackingMDRef (TrackingMDRef &&X)
TrackingMDRef (const TrackingMDRef &X)
TrackingMDRef & operator= (TrackingMDRef &&X)
TrackingMDRef & operator= (const TrackingMDRef &X)
~TrackingMDRef ()
Metadata * get () const
operator Metadata * () const
Metadata * operator-> () const
Metadata & operator* () const
void reset ()
void reset (Metadata *MD)
bool hasTrivialDestructor () const
Check whether this has a trivial destructor.
bool operator== (const TrackingMDRef &X) const
bool operator!= (const TrackingMDRef &X) const
Detailed Description
Tracking metadata reference.
This class behaves like TrackingVH, but for metadata.
Definition at line 29 of file TrackingMDRef.h.
Constructor & Destructor Documentation
TrackingMDRef() [1/4]
llvm::TrackingMDRef::TrackingMDRef () inline
Definition at line 33 of file TrackingMDRef.h.
Referenced by operator!=(), operator=(), operator=(), operator==(), TrackingMDRef(), and TrackingMDRef().
TrackingMDRef() [2/4]
llvm::TrackingMDRef::TrackingMDRef (Metadata * MD) inline explicit
Definition at line 34 of file TrackingMDRef.h.
TrackingMDRef() [3/4]
llvm::TrackingMDRef::TrackingMDRef (TrackingMDRef && X) inline
Definition at line 36 of file TrackingMDRef.h.
References TrackingMDRef(), and llvm::X.
TrackingMDRef() [4/4]
llvm::TrackingMDRef::TrackingMDRef (const TrackingMDRef & X) inline
Definition at line 37 of file TrackingMDRef.h.
References TrackingMDRef(), and llvm::X.
~TrackingMDRef()
llvm::TrackingMDRef::~TrackingMDRef () inline
Definition at line 56 of file TrackingMDRef.h.
Member Function Documentation
get()
Metadata * llvm::TrackingMDRef::get () const inline
Definition at line 58 of file TrackingMDRef.h.
Referenced by llvm::BitcodeReaderMDValueList::AssignValue(), llvm::simplify_type< const TrackingMDRef >::getSimplifiedValue(), llvm::simplify_type< TrackingMDRef >::getSimplifiedValue(), operator Metadata *(), operator*(), and operator->().
hasTrivialDestructor()
bool llvm::TrackingMDRef::hasTrivialDestructor () const inline
Check whether this has a trivial destructor.
If MD isn't replaceable, the destructor will be a no-op.
Definition at line 76 of file TrackingMDRef.h.
References llvm::MetadataTracking::isReplaceable().
operator Metadata *()
llvm::TrackingMDRef::operator Metadata * () const inline
Definition at line 59 of file TrackingMDRef.h.
References get().
operator!=()
bool llvm::TrackingMDRef::operator!= (const TrackingMDRef & X) const inline
Definition at line 81 of file TrackingMDRef.h.
References TrackingMDRef(), and llvm::X.
operator*()
Metadata & llvm::TrackingMDRef::operator* () const inline
Definition at line 61 of file TrackingMDRef.h.
References get().
operator->()
Metadata * llvm::TrackingMDRef::operator-> () const inline
Definition at line 60 of file TrackingMDRef.h.
References get().
operator=() [1/2]
TrackingMDRef & llvm::TrackingMDRef::operator= (const TrackingMDRef & X) inline
Definition at line 47 of file TrackingMDRef.h.
References TrackingMDRef(), and llvm::X.
operator=() [2/2]
TrackingMDRef & llvm::TrackingMDRef::operator= (TrackingMDRef && X) inline
Definition at line 38 of file TrackingMDRef.h.
References TrackingMDRef(), and llvm::X.
operator==()
bool llvm::TrackingMDRef::operator== (const TrackingMDRef & X) const inline
Definition at line 80 of file TrackingMDRef.h.
References TrackingMDRef(), and llvm::X.
reset() [1/2]
void llvm::TrackingMDRef::reset () inline
Definition at line 63 of file TrackingMDRef.h.
Referenced by llvm::BitcodeReaderMDValueList::AssignValue().
reset() [2/2]
void llvm::TrackingMDRef::reset (Metadata * MD) inline
Definition at line 67 of file TrackingMDRef.h.
The documentation for this class was generated from the following file:
TrackingMDRef.h