LLVM: llvm::MDTuple Class Reference
LLVM API Documentation
llvm::MDTuple Class Reference
Tuple of metadata.
#include <Metadata.h>
Public Member Functions
unsigned getHash () const
Get the hash, if any.
Public Member Functions inherited from llvm::UniquableMDNode
bool isResolved () const
Check whether any operands are forward declarations.
void resolveCycles ()
Resolve cycles.
Public Member Functions inherited from llvm::MDNode
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isDistinct () const
Check if node is distinct.
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void print (raw_ostream &OS) const
void printAsOperand (raw_ostream &OS, bool PrintType=true, const Module *M=nullptr) const
Static Public Member Functions
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
Return a distinct node.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::UniquableMDNode
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDNode * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDNode * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDNode * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDNodeFwdDecl * getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
Return a temporary MDNode.
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static AAMDNodes getMostGenericAA (const AAMDNodes &A, const AAMDNodes &B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
Friends
class LLVMContextImpl
class UniquableMDNode
Additional Inherited Members
Public Types inherited from llvm::MDNode
typedef const MDOperand * op_iterator
typedef iterator_range< op_iterator > op_range
Public Types inherited from llvm::Metadata
enum MetadataKind {
MDTupleKind , MDLocationKind , MDNodeFwdDeclKind , ConstantAsMetadataKind ,
LocalAsMetadataKind , MDStringKind
}
Protected Member Functions inherited from llvm::UniquableMDNode
UniquableMDNode (LLVMContext &C, unsigned ID, ArrayRef< Metadata * > Vals, bool AllowRAUW)
Create a new node.
~UniquableMDNode ()
void storeDistinctInContext ()
Protected Member Functions inherited from llvm::MDNode
void * operator new (size_t Size, unsigned NumOps)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
MDNode (LLVMContext &Context, unsigned ID, ArrayRef< Metadata * > MDs)
~MDNode ()
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID)
~Metadata ()
bool isStoredDistinctInContext () const
Store this in a big non-uniqued untyped bucket.
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Protected Attributes inherited from llvm::MDNode
unsigned MDNodeSubclassData
Protected Attributes inherited from llvm::Metadata
bool IsDistinctInContext: 1
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned short SubclassData16
unsigned SubclassData32
Detailed Description
Tuple of metadata.
This is the simple MDNode arbitrary tuple. Nodes are uniqued by default based on their operands.
Definition at line 778 of file Metadata.h.
Member Function Documentation
classof()
bool llvm::MDTuple::classof (const Metadata * MD) inline static
Definition at line 808 of file Metadata.h.
References llvm::Metadata::getMetadataID(), and llvm::Metadata::MDTupleKind.
get()
MDTuple * llvm::MDTuple::get (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 796 of file Metadata.h.
Referenced by cloneMDTuple(), and llvm::MDNode::get().
getDistinct()
MDTuple * MDTuple::getDistinct (LLVMContext & Context, ArrayRef< Metadata * > MDs) static
Return a distinct node.
Return a distinct node – i.e., a node that is not uniqued.
Definition at line 627 of file Metadata.cpp.
References N, and llvm::ArrayRef< T >::size().
Referenced by llvm::MDNode::getDistinct(), and mapDistinctNode().
getHash()
unsigned llvm::MDTuple::getHash () const inline
Get the hash, if any.
Definition at line 794 of file Metadata.h.
References llvm::MDNode::MDNodeSubclassData.
Referenced by llvm::MDTupleInfo::KeyTy::operator==().
getIfExists()
MDTuple * llvm::MDTuple::getIfExists (LLVMContext & Context, ArrayRef< Metadata * > MDs) inline static
Definition at line 799 of file Metadata.h.
Referenced by llvm::MDNode::getIfExists().
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 779 of file Metadata.h.
References LLVMContextImpl.
Referenced by LLVMContextImpl.
UniquableMDNode
friend class UniquableMDNode friend
Definition at line 780 of file Metadata.h.
References llvm::Metadata::MDTupleKind, and UniquableMDNode.
Referenced by UniquableMDNode.
The documentation for this class was generated from the following files:
Metadata.h
Metadata.cpp