LLVM: llvm::Init Class Reference
LLVM API Documentation
llvm::Init Class Reference abstract
#include <Record.h>
Public Member Functions
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsString () const =0
getAsString - Convert this value to a string form.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * convertInitializerTo (RecTy *Ty) const =0
virtual Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const
virtual Init * convertInitListSlice (const std::vector< unsigned > &Elements) const
virtual RecTy * getFieldType (const std::string &FieldName) const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * resolveReferences (Record &R, const RecordVal *RV) const
virtual Init * getBit (unsigned Bit) const =0
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Protected Types
enum InitKind {
IK_BitInit , IK_FirstTypedInit , IK_BitsInit , IK_DagInit ,
IK_DefInit , IK_FieldInit , IK_IntInit , IK_ListInit ,
IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit , IK_UnOpInit ,
IK_LastOpInit , IK_StringInit , IK_VarInit , IK_VarListElementInit ,
IK_LastTypedInit , IK_UnsetInit , IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions
Init (InitKind K)
Detailed Description
Definition at line 418 of file Record.h.
Member Enumeration Documentation
InitKind
enum llvm::Init::InitKind protected
Discriminator enum (for isa<>, dyn_cast<>, et al.)
This enum is laid out by a preorder traversal of the inheritance hierarchy, and does not contain an entry for abstract classes, as per the recommendation in docs/HowToSetUpLLVMStyleRTTI.rst.
We also explicitly include "first" and "last" values for each interior node of the inheritance tree, to make it easier to read the corresponding classof().
We could pack these a bit tighter by not having the IK_FirstXXXInit and IK_LastXXXInit be their own values, but that would degrade readability for really no benefit.
Enumerator
IK_BitInit
IK_FirstTypedInit
IK_BitsInit
IK_DagInit
IK_DefInit
IK_FieldInit
IK_IntInit
IK_ListInit
IK_FirstOpInit
IK_BinOpInit
IK_TernOpInit
IK_UnOpInit
IK_LastOpInit
IK_StringInit
IK_VarInit
IK_VarListElementInit
IK_LastTypedInit
IK_UnsetInit
IK_VarBitInit
Definition at line 433 of file Record.h.
Constructor & Destructor Documentation
Init()
llvm::Init::Init (InitKind K) inline explicit protected
Definition at line 465 of file Record.h.
~Init()
virtual llvm::Init::~Init () inline virtual
Definition at line 468 of file Record.h.
Member Function Documentation
convertInitializerBitRange()
virtual Init * llvm::Init::convertInitializerBitRange (const std::vector< unsigned > & Bits) const inline virtual
convertInitializerBitRange - This method is used to implement the bitrange selection operator. Given an initializer, it selects the specified bits out, returning them as a new init of bits type. If it is not legal to use the bit subscript operator on this initializer, return null.
Reimplemented in llvm::BitsInit, llvm::IntInit, and llvm::TypedInit.
Definition at line 501 of file Record.h.
convertInitializerTo()
virtual Init * llvm::Init::convertInitializerTo (RecTy * Ty) const pure virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implemented in llvm::BitInit, llvm::BitsInit, llvm::DagInit, llvm::DefInit, llvm::FieldInit, llvm::IntInit, llvm::ListInit, llvm::OpInit, llvm::StringInit, llvm::UnsetInit, llvm::VarBitInit, llvm::VarInit, and llvm::VarListElementInit.
Referenced by llvm::DagRecTy::convertValue(), llvm::DagRecTy::convertValue(), llvm::ListRecTy::convertValue(), llvm::StringRecTy::convertValue(), llvm::StringRecTy::convertValue(), and llvm::TernOpInit::resolveReferences().
convertInitListSlice()
virtual Init * llvm::Init::convertInitListSlice (const std::vector< unsigned > & Elements) const inline virtual
convertInitListSlice - This method is used to implement the list slice selection operator. Given an initializer, it selects the specified list elements, returning them as a new init of list type. If it is not legal to take a slice of this, return null.
Reimplemented in llvm::ListInit, and llvm::TypedInit.
Definition at line 511 of file Record.h.
dump()
void Init::dump () const
dump - Debugging method that may be called through a debugger, just invokes print on stderr.
Definition at line 442 of file Record.cpp.
References llvm::errs(), and print().
Referenced by llvm::ExecutionEngine::InitializeMemory().
getAsString()
virtual std::string llvm::Init::getAsString () const pure virtual
getAsString - Convert this value to a string form.
Implemented in llvm::BinOpInit, llvm::BitInit, llvm::BitsInit, llvm::DagInit, llvm::DefInit, llvm::FieldInit, llvm::IntInit, llvm::ListInit, llvm::StringInit, llvm::TernOpInit, llvm::UnOpInit, llvm::UnsetInit, llvm::VarBitInit, llvm::VarInit, and llvm::VarListElementInit.
Referenced by llvm::SetTheory::evaluate(), EvaluateOperation(), ForeachHelper(), llvm::ListRecTy::getAsString(), getAsUnquotedString(), and print().
getAsUnquotedString()
virtual std::string llvm::Init::getAsUnquotedString () const inline virtual
getAsUnquotedString - Convert this value to a string form, without adding quote markers. This primaruly affects StringInits where we will not surround the string value with quotes.
Reimplemented in llvm::StringInit.
Definition at line 483 of file Record.h.
References getAsString().
Referenced by llvm::Record::getNameInitAsString(), llvm::RecordVal::getNameInitAsString(), llvm::VarInit::getNameInitAsString(), and llvm::Record::resolveReferencesTo().
getBit()
virtual Init * llvm::Init::getBit (unsigned Bit) const pure virtual
getBit - This method is used to return the initializer for the specified bit.
Implemented in llvm::BitInit, llvm::BitsInit, llvm::DagInit, llvm::DefInit, llvm::FieldInit, llvm::IntInit, llvm::ListInit, llvm::OpInit, llvm::StringInit, llvm::UnsetInit, llvm::VarBitInit, llvm::VarInit, and llvm::VarListElementInit.
Referenced by llvm::BitsInit::resolveReferences().
getBitNum()
virtual unsigned llvm::Init::getBitNum () const inline virtual
getBitNum - This method is used to retrieve the bit number of a bit reference. For non-VarBitInit, it simply returns 0.
Reimplemented in llvm::VarBitInit.
Definition at line 551 of file Record.h.
Referenced by llvm::BitsInit::resolveReferences().
getBitVar()
virtual Init * llvm::Init::getBitVar () const inline virtual
getBitVar - This method is used to retrieve the initializer for bit reference. For non-VarBitInit, it simply returns itself.
Reimplemented in llvm::VarBitInit.
Definition at line 547 of file Record.h.
Referenced by llvm::BitsInit::resolveReferences().
getFieldInit()
virtual Init * llvm::Init::getFieldInit (Record & R, const RecordVal * RV, const std::string & FieldName) const inline virtual
getFieldInit - This method complements getFieldType to return the initializer for the specified field. If getFieldType returns non-null this method should return non-null, otherwise it returns null.
Reimplemented in llvm::DefInit, and llvm::VarInit.
Definition at line 527 of file Record.h.
Referenced by llvm::VarInit::getFieldInit(), llvm::FieldInit::resolveListElementReference(), and llvm::FieldInit::resolveReferences().
getFieldType()
virtual RecTy * llvm::Init::getFieldType (const std::string & FieldName) const inline virtual
getFieldType - This method is used to implement the FieldInit class. Implementors of this method should return the type of the named field if they are of record type.
Reimplemented in llvm::DefInit, llvm::TypedInit, and llvm::VarInit.
Definition at line 519 of file Record.h.
getKind()
InitKind llvm::Init::getKind () const inline
Definition at line 462 of file Record.h.
isComplete()
virtual bool llvm::Init::isComplete () const inline virtual
isComplete - This virtual method should be overridden by values that may not be completely specified yet.
Reimplemented in llvm::BitsInit, llvm::TernOpInit, and llvm::UnsetInit.
Definition at line 472 of file Record.h.
Referenced by llvm::FieldInit::resolveReferences().
print()
void llvm::Init::print (raw_ostream & OS) const inline
print - Print out this value.
Definition at line 475 of file Record.h.
References getAsString().
Referenced by dump().
resolveReferences()
virtual Init * llvm::Init::resolveReferences (Record & R, const RecordVal * RV) const inline virtual
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented in llvm::BinOpInit, llvm::BitsInit, llvm::DagInit, llvm::FieldInit, llvm::ListInit, llvm::TernOpInit, llvm::UnOpInit, llvm::VarBitInit, llvm::VarInit, and llvm::VarListElementInit.
Definition at line 537 of file Record.h.
Referenced by llvm::OpInit::resolveListElementReference(), llvm::BinOpInit::resolveReferences(), llvm::BitsInit::resolveReferences(), llvm::DagInit::resolveReferences(), llvm::FieldInit::resolveReferences(), llvm::ListInit::resolveReferences(), llvm::TernOpInit::resolveReferences(), llvm::UnOpInit::resolveReferences(), and llvm::Record::resolveReferencesTo().
The documentation for this class was generated from the following files:
Record.h
Record.cpp