LLVM: llvm::yaml::Node Class Reference
LLVM API Documentation
llvm::yaml::Node Class Reference
Abstract base class for all Nodes.
#include <YAMLParser.h>
Public Types
enum NodeKind {
NK_Null , NK_Scalar , NK_KeyValue , NK_Mapping ,
NK_Sequence , NK_Alias
}
Public Member Functions
Node (unsigned int Type, std::unique_ptr< Document > &, StringRef Anchor, StringRef Tag)
StringRef getAnchor () const
Get the value of the anchor attached to this node. If it does not have one, getAnchor().size() will be 0.
StringRef getRawTag () const
Get the tag as it was written in the document. This does not perform tag resolution.
std::string getVerbatimTag () const
Get the verbatium tag for a given Node. This performs tag resoluton and substitution.
SMRange getSourceRange () const
void setSourceRange (SMRange SR)
Token & peekNext ()
Token getNext ()
Node * parseBlockNode ()
BumpPtrAllocator & getAllocator ()
void setError (const Twine &Message, Token &Location) const
bool failed () const
virtual void skip ()
unsigned int getType () const
void * operator new (size_t Size, BumpPtrAllocator &Alloc, size_t Alignment=16) throw ()
void operator delete (void *Ptr, BumpPtrAllocator &Alloc, size_t Size) throw ()
Protected Member Functions
void operator delete (void *) throw ()
virtual ~Node ()
Protected Attributes
std::unique_ptr< Document > & Doc
SMRange SourceRange
Detailed Description
Abstract base class for all Nodes.
Definition at line 104 of file YAMLParser.h.
Member Enumeration Documentation
NodeKind
enum llvm::yaml::Node::NodeKind
Enumerator
NK_Null
NK_Scalar
NK_KeyValue
NK_Mapping
NK_Sequence
NK_Alias
Definition at line 108 of file YAMLParser.h.
Constructor & Destructor Documentation
Node()
Node::Node (unsigned int Type, std::unique_ptr< Document > & D, StringRef Anchor, StringRef Tag)
Definition at line 1559 of file YAMLParser.cpp.
References Doc, llvm::SMLoc::getFromPointer(), peekNext(), and SourceRange.
Referenced by llvm::yaml::AliasNode::AliasNode(), llvm::yaml::MappingNode::basic_collection_iterator< MappingNode, KeyValueNode >, llvm::yaml::SequenceNode::basic_collection_iterator< SequenceNode, Node >, llvm::yaml::AliasNode::classof(), llvm::yaml::KeyValueNode::classof(), llvm::yaml::MappingNode::classof(), llvm::yaml::NullNode::classof(), llvm::yaml::ScalarNode::classof(), llvm::yaml::SequenceNode::classof(), llvm::yaml::KeyValueNode::getKey(), llvm::yaml::AliasNode::getTarget(), llvm::yaml::KeyValueNode::getValue(), llvm::yaml::KeyValueNode::KeyValueNode(), llvm::yaml::NullNode::NullNode(), parseBlockNode(), and llvm::yaml::ScalarNode::ScalarNode().
~Node()
virtual llvm::yaml::Node::~Node () inline protected virtual
Definition at line 162 of file YAMLParser.h.
Member Function Documentation
failed()
bool Node::failed () const
Definition at line 1630 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::KeyValueNode::getValue(), and llvm::yaml::SequenceNode::increment().
getAllocator()
BumpPtrAllocator & Node::getAllocator ()
Definition at line 1622 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::KeyValueNode::getKey(), and llvm::yaml::KeyValueNode::getValue().
getAnchor()
StringRef llvm::yaml::Node::getAnchor () const inline
Get the value of the anchor attached to this node. If it does not have one, getAnchor().size() will be 0.
Definition at line 122 of file YAMLParser.h.
getNext()
Token Node::getNext ()
Definition at line 1614 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::KeyValueNode::getKey(), llvm::yaml::KeyValueNode::getValue(), and llvm::yaml::SequenceNode::increment().
getRawTag()
StringRef llvm::yaml::Node::getRawTag () const inline
Get the tag as it was written in the document. This does not perform tag resolution.
Definition at line 126 of file YAMLParser.h.
Referenced by getVerbatimTag().
getSourceRange()
SMRange llvm::yaml::Node::getSourceRange () const inline
Definition at line 132 of file YAMLParser.h.
References SourceRange.
getType()
unsigned int llvm::yaml::Node::getType () const inline
Definition at line 145 of file YAMLParser.h.
Referenced by getVerbatimTag().
getVerbatimTag()
std::string Node::getVerbatimTag () const
Get the verbatium tag for a given Node. This performs tag resoluton and substitution.
Definition at line 1566 of file YAMLParser.cpp.
References Doc, llvm::StringRef::empty(), llvm::StringRef::find_last_of(), getRawTag(), getType(), llvm::yaml::Token::Kind, NK_Mapping, NK_Null, NK_Scalar, NK_Sequence, setError(), llvm::StringRef::startswith(), llvm::StringRef::substr(), and llvm::yaml::Token::TK_Tag.
operator delete() [1/2]
void llvm::yaml::Node::operator delete (void *) throw () inline protected
Definition at line 160 of file YAMLParser.h.
operator delete() [2/2]
void llvm::yaml::Node::operator delete (void * Ptr, BumpPtrAllocator & Alloc, size_t Size) throw () inline
Definition at line 152 of file YAMLParser.h.
operator new()
void * llvm::yaml::Node::operator new (size_t Size, BumpPtrAllocator & Alloc, size_t Alignment = 16) throw () inline
Definition at line 147 of file YAMLParser.h.
parseBlockNode()
Node * Node::parseBlockNode ()
Definition at line 1618 of file YAMLParser.cpp.
References Doc, and Node().
Referenced by llvm::yaml::KeyValueNode::getKey(), llvm::yaml::KeyValueNode::getValue(), and llvm::yaml::SequenceNode::increment().
peekNext()
Token & Node::peekNext ()
Definition at line 1610 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::KeyValueNode::getKey(), llvm::yaml::KeyValueNode::getValue(), llvm::yaml::SequenceNode::increment(), and Node().
setError()
void Node::setError (const Twine & Message, Token & Location) const
Definition at line 1626 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::KeyValueNode::getValue(), getVerbatimTag(), and llvm::yaml::SequenceNode::increment().
setSourceRange()
void llvm::yaml::Node::setSourceRange (SMRange SR) inline
Definition at line 133 of file YAMLParser.h.
References SourceRange.
skip()
virtual void llvm::yaml::Node::skip () inline virtual
Reimplemented in llvm::yaml::KeyValueNode, llvm::yaml::MappingNode, and llvm::yaml::SequenceNode.
Definition at line 143 of file YAMLParser.h.
Referenced by llvm::yaml::KeyValueNode::getValue(), and llvm::yaml::KeyValueNode::skip().
Member Data Documentation
Doc
std::unique_ptr<Document>& llvm::yaml::Node::Doc protected
Definition at line 157 of file YAMLParser.h.
Referenced by failed(), getAllocator(), llvm::yaml::KeyValueNode::getKey(), getNext(), llvm::yaml::KeyValueNode::getValue(), getVerbatimTag(), Node(), parseBlockNode(), peekNext(), and setError().
SourceRange
SMRange llvm::yaml::Node::SourceRange protected
Definition at line 158 of file YAMLParser.h.
Referenced by getSourceRange(), Node(), llvm::yaml::ScalarNode::ScalarNode(), and setSourceRange().
The documentation for this class was generated from the following files:
YAMLParser.h
YAMLParser.cpp