LLVM: llvm::UniquableMDNode Class Reference
LLVM API Documentation
llvm::UniquableMDNode Class Reference
Uniquable metadata node.
#include <Metadata.h>
Public Member Functions
bool isResolved () const
Check whether any operands are forward declarations.
void resolveCycles ()
Resolve cycles.
Public Member Functions inherited from llvm::MDNode
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isDistinct () const
Check if node is distinct.
op_iterator op_begin () const
op_iterator op_end () const
op_range operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void print (raw_ostream &OS) const
void printAsOperand (raw_ostream &OS, bool PrintType=true, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDNode * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDNode * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDNode * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDNodeFwdDecl * getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
Return a temporary MDNode.
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static AAMDNodes getMostGenericAA (const AAMDNodes &A, const AAMDNodes &B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
Protected Member Functions
UniquableMDNode (LLVMContext &C, unsigned ID, ArrayRef< Metadata * > Vals, bool AllowRAUW)
Create a new node.
~UniquableMDNode ()
void storeDistinctInContext ()
Protected Member Functions inherited from llvm::MDNode
void * operator new (size_t Size, unsigned NumOps)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
MDNode (LLVMContext &Context, unsigned ID, ArrayRef< Metadata * > MDs)
~MDNode ()
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID)
~Metadata ()
bool isStoredDistinctInContext () const
Store this in a big non-uniqued untyped bucket.
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Friends
class ReplaceableMetadataImpl
class MDNode
class LLVMContextImpl
Additional Inherited Members
Public Types inherited from llvm::MDNode
typedef const MDOperand * op_iterator
typedef iterator_range< op_iterator > op_range
Public Types inherited from llvm::Metadata
enum MetadataKind {
MDTupleKind , MDLocationKind , MDNodeFwdDeclKind , ConstantAsMetadataKind ,
LocalAsMetadataKind , MDStringKind
}
Protected Attributes inherited from llvm::MDNode
unsigned MDNodeSubclassData
Protected Attributes inherited from llvm::Metadata
bool IsDistinctInContext: 1
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned short SubclassData16
unsigned SubclassData32
Detailed Description
Uniquable metadata node.
A uniquable metadata node. This contains the basic functionality for implementing sub-types of MDNode that can be uniqued like constants.
There is limited support for RAUW at construction time. At construction time, if any operands are an instance of MDNodeFwdDecl (or another unresolved UniquableMDNode, which indicates an MDNodeFwdDecl in its path), the node itself will be unresolved. As soon as all operands become resolved, it will drop RAUW support permanently.
If an unresolved node is part of a cycle, resolveCycles() needs to be called on some member of the cycle when each MDNodeFwdDecl has been removed.
Definition at line 715 of file Metadata.h.
Constructor & Destructor Documentation
UniquableMDNode()
UniquableMDNode::UniquableMDNode (LLVMContext & C, unsigned ID, ArrayRef< Metadata * > Vals, bool AllowRAUW) protected
Create a new node.
If AllowRAUW, then if any operands are unresolved support RAUW. RAUW will be dropped once all operands have been resolved (or if resolveCycles() is called).
Definition at line 417 of file Metadata.cpp.
References isOperandUnresolved(), MDNode, llvm::MDNode::operands(), ReplaceableMetadataImpl, and llvm::Metadata::SubclassData32.
~UniquableMDNode()
llvm::UniquableMDNode::~UniquableMDNode () inline protected
Definition at line 734 of file Metadata.h.
Member Function Documentation
classof()
bool llvm::UniquableMDNode::classof (const Metadata * MD) inline static
Definition at line 739 of file Metadata.h.
References llvm::Metadata::getMetadataID(), llvm::Metadata::MDLocationKind, and llvm::Metadata::MDTupleKind.
isResolved()
bool llvm::UniquableMDNode::isResolved () const inline
Check whether any operands are forward declarations.
Returns true as long as any operands (or their operands, etc.) are MDNodeFwdDecl.
As forward declarations are resolved, their containers should get resolved automatically. However, if this (or one of its operands) is involved in a cycle, resolveCycles() needs to be called explicitly.
Definition at line 752 of file Metadata.h.
Referenced by MapMetadataImpl(), and resolveCycles().
resolveCycles()
void UniquableMDNode::resolveCycles ()
Resolve cycles.
Once all forward declarations have been resolved, force cycles to be resolved.
Precondition
No operands (or operands' operands, etc.) are MDNodeFwdDecl.
Definition at line 465 of file Metadata.cpp.
References llvm::dyn_cast(), llvm::isa(), isResolved(), N, and llvm::MDNode::operands().
storeDistinctInContext()
void UniquableMDNode::storeDistinctInContext () protected
Definition at line 742 of file Metadata.cpp.
References llvm::LLVMContextImpl::DistinctMDNodes, llvm::dyn_cast(), llvm::MDNode::getContext(), llvm::Metadata::IsDistinctInContext, and llvm::LLVMContext::pImpl.
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 718 of file Metadata.h.
References LLVMContextImpl.
Referenced by LLVMContextImpl.
MDNode
friend class MDNode friend
Definition at line 717 of file Metadata.h.
References MDNode.
Referenced by MDNode, and UniquableMDNode().
ReplaceableMetadataImpl
friend class ReplaceableMetadataImpl friend
Definition at line 716 of file Metadata.h.
References ReplaceableMetadataImpl.
Referenced by ReplaceableMetadataImpl, and UniquableMDNode().
The documentation for this class was generated from the following files:
Metadata.h
Metadata.cpp