LLVM: llvm::HexagonFrameLowering Class Reference
LLVM API Documentation
llvm::HexagonFrameLowering Class Reference
#include <HexagonFrameLowering.h>
Public Member Functions
HexagonFrameLowering ()
void emitPrologue (MachineFunction &MF) const override
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const override
int getFrameIndexOffset (const MachineFunction &MF, int FI) const override
bool hasFP (const MachineFunction &MF) const override
bool hasTailCall (MachineBasicBlock &MBB) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
unsigned getStackAlignment () const
unsigned getTransientStackAlignment () const
bool isStackRealignable () const
int getOffsetOfLocalArea () const
virtual bool isFPCloseToIncomingSP () const
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
virtual bool targetHandlesStackFrameRounding () const
virtual void adjustForSegmentedStacks (MachineFunction &MF) const
virtual void adjustForHiPEPrologue (MachineFunction &MF) const
virtual void adjustForFrameAllocatePrologue (MachineFunction &MF) const
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
virtual int getFrameIndexReferenceFromSP (const MachineFunction &MF, int FI, unsigned &FrameReg) const
virtual void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS=nullptr) const
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Detailed Description
Definition at line 18 of file HexagonFrameLowering.h.
Constructor & Destructor Documentation
HexagonFrameLowering()
llvm::HexagonFrameLowering::HexagonFrameLowering () inline explicit
Definition at line 23 of file HexagonFrameLowering.h.
References llvm::TargetFrameLowering::StackGrowsDown, and llvm::TargetFrameLowering::TargetFrameLowering().
Member Function Documentation
eliminateCallFramePseudoInstr()
void HexagonFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them). It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 331 of file HexagonFrameLowering.cpp.
References llvm::MachineBasicBlock::erase(), I, and llvm_unreachable.
emitEpilogue()
void HexagonFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 148 of file HexagonFrameLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineInstr::copyImplicitOps(), DisableDeallocRet, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::getDebugLoc(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::TargetMachine::getOptLevel(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), hasFP(), llvm::HexagonSubtarget::hasV4TOps(), I, llvm::MachineOperand::isReg(), llvm::CodeGenOpt::None, and TII.
emitPrologue()
void HexagonFrameLowering::emitPrologue (MachineFunction & MF) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 79 of file HexagonFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::front(), llvm::HexagonMachineFunctionInfo::getAllocaAdjustInsts(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::HexagonRegisterInfo::getStackRegister(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), hasFP(), HEXAGON_RESERVED_REG_1, llvm::MachineOperand::isImm(), llvm::MachineOperand::setImm(), and TII.
getFrameIndexOffset()
int HexagonFrameLowering::getFrameIndexOffset (const MachineFunction & MF, int FI) const override virtual
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index.
getFrameIndexOffset - Returns the displacement from the frame register to the stack frame of the specified index. This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 346 of file HexagonFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::getObjectOffset().
hasFP()
bool HexagonFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register. For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 206 of file HexagonFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFrameInfo::hasCalls(), and llvm::HexagonMachineFunctionInfo::hasClobberLR().
Referenced by emitEpilogue(), and emitPrologue().
hasTailCall()
bool HexagonFrameLowering::hasTailCall (MachineBasicBlock & MBB) const
Definition at line 141 of file HexagonFrameLowering.cpp.
References llvm::MachineBasicBlock::getLastNonDebugInstr(), and llvm::MachineInstr::getOpcode().
restoreCalleeSavedRegisters()
bool HexagonFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 279 of file HexagonFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), getReg(), llvm::MachineFunction::getSubtarget(), TII, and uniqueSuperReg().
spillCalleeSavedRegisters()
bool HexagonFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 225 of file HexagonFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), getReg(), llvm::MachineFunction::getSubtarget(), TII, and uniqueSuperReg().
The documentation for this class was generated from the following files:
HexagonFrameLowering.h
HexagonFrameLowering.cpp