LLVM: llvm::GlobalObject Class Reference
LLVM API Documentation
llvm::GlobalObject Class Reference
#include <GlobalObject.h>
Public Member Functions
unsigned getAlignment () const
void setAlignment (unsigned Align)
unsigned getGlobalObjectSubClassData () const
void setGlobalObjectSubClassData (unsigned Val)
bool hasSection () const
const char * getSection () const
void setSection (StringRef S)
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
void setComdat (Comdat *C)
void copyAttributesFrom (const GlobalValue *Src) override
Public Member Functions inherited from llvm::GlobalValue
~GlobalValue ()
unsigned getAlignment () const
bool hasUnnamedAddr () const
void setUnnamedAddr (bool Val)
bool hasComdat () const
Comdat * getComdat ()
const Comdat * getComdat () const
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
bool isThreadLocal () const
If the value is "Thread Local", its value isn't shared by the threads.
void setThreadLocal (bool Val)
void setThreadLocalMode (ThreadLocalMode Val)
ThreadLocalMode getThreadLocalMode () const
DLLStorageClassTypes getDLLStorageClass () const
bool hasDLLImportStorageClass () const
bool hasDLLExportStorageClass () const
void setDLLStorageClass (DLLStorageClassTypes C)
bool hasSection () const
const char * getSection () const
PointerType * getType () const
Global values are always pointers.
bool hasExternalLinkage () const
bool hasAvailableExternallyLinkage () const
bool hasLinkOnceLinkage () const
bool hasLinkOnceODRLinkage () const
bool hasWeakLinkage () const
bool hasWeakAnyLinkage () const
bool hasWeakODRLinkage () const
bool hasAppendingLinkage () const
bool hasInternalLinkage () const
bool hasPrivateLinkage () const
bool hasLocalLinkage () const
bool hasExternalWeakLinkage () const
bool hasCommonLinkage () const
void setLinkage (LinkageTypes LT)
LinkageTypes getLinkage () const
bool isDiscardableIfUnused () const
bool mayBeOverridden () const
bool isWeakForLinker () const
void destroyConstant () override
Override from Constant class.
bool isDeclaration () const
bool isDeclarationForLinker () const
virtual void removeFromParent ()=0
virtual void eraseFromParent ()=0
This method unlinks 'this' from the containing module and deletes it.
Module * getParent ()
Get the module that this global value is contained inside of...
const Module * getParent () const
const DataLayout * getDataLayout () const
bool isMaterializable () const
bool isDematerializable () const
std::error_code materialize ()
void Dematerialize ()
Public Member Functions inherited from llvm::Constant
bool isNullValue () const
bool isOneValue () const
Returns true if the value is one.
bool isAllOnesValue () const
bool isNegativeZeroValue () const
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool canTrap () const
bool isThreadDependent () const
isThreadDependent - Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
PossibleRelocationsTy getRelocationInfo () const
Constant * getAggregateElement (unsigned Elt) const
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
const APInt & getUniqueInteger () const
virtual void replaceUsesOfWithOnConstant (Value *, Value *, Use *)
void removeDeadConstantUsers () const
Constant * stripPointerCasts ()
const Constant * stripPointerCasts () const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Static Public Member Functions
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::GlobalValue
static LinkageTypes getLinkOnceLinkage (bool ODR)
static LinkageTypes getWeakLinkage (bool ODR)
static bool isExternalLinkage (LinkageTypes Linkage)
static bool isAvailableExternallyLinkage (LinkageTypes Linkage)
static bool isLinkOnceODRLinkage (LinkageTypes Linkage)
static bool isLinkOnceLinkage (LinkageTypes Linkage)
static bool isWeakAnyLinkage (LinkageTypes Linkage)
static bool isWeakODRLinkage (LinkageTypes Linkage)
static bool isWeakLinkage (LinkageTypes Linkage)
static bool isAppendingLinkage (LinkageTypes Linkage)
static bool isInternalLinkage (LinkageTypes Linkage)
static bool isPrivateLinkage (LinkageTypes Linkage)
static bool isLocalLinkage (LinkageTypes Linkage)
static bool isExternalWeakLinkage (LinkageTypes Linkage)
static bool isCommonLinkage (LinkageTypes Linkage)
static bool isDiscardableIfUnused (LinkageTypes Linkage)
static bool mayBeOverridden (LinkageTypes Linkage)
static bool isWeakForLinker (LinkageTypes Linkage)
static StringRef getRealLinkageName (StringRef Name)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
static Constant * getAllOnesValue (Type *Ty)
Get the all ones value.
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
GlobalObject (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name)
Protected Member Functions inherited from llvm::GlobalValue
GlobalValue (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name)
unsigned getGlobalValueSubClassData () const
void setGlobalValueSubClassData (unsigned V)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
void destroyConstantImpl ()
void replaceUsesOfWithOnConstantImpl (Constant *Replacement)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes
std::string Section
Comdat * ObjComdat
Protected Attributes inherited from llvm::GlobalValue
LinkageTypes Linkage: 5
unsigned Visibility: 2
unsigned UnnamedAddr: 1
unsigned DllStorageClass: 2
unsigned ThreadLocal: 3
Module * Parent
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Static Protected Attributes
static const unsigned AlignmentBits = 5
static const unsigned GlobalObjectSubClassDataBits
Static Protected Attributes inherited from llvm::GlobalValue
static const unsigned GlobalValueSubClassDataBits = 19
Additional Inherited Members
Public Types inherited from llvm::GlobalValue
enum LinkageTypes {
ExternalLinkage = 0 , AvailableExternallyLinkage , LinkOnceAnyLinkage , LinkOnceODRLinkage ,
WeakAnyLinkage , WeakODRLinkage , AppendingLinkage , InternalLinkage ,
PrivateLinkage , ExternalWeakLinkage , CommonLinkage
}
An enumeration for the kinds of linkage for global values.
enum VisibilityTypes { DefaultVisibility = 0 , HiddenVisibility , ProtectedVisibility }
An enumeration for the kinds of visibility of global values.
enum DLLStorageClassTypes { DefaultStorageClass = 0 , DLLImportStorageClass = 1 , DLLExportStorageClass = 2 }
Storage classes of global values for PE targets.
enum ThreadLocalMode {
NotThreadLocal = 0 , GeneralDynamicTLSModel , LocalDynamicTLSModel , InitialExecTLSModel ,
LocalExecTLSModel
}
Public Types inherited from llvm::Constant
enum PossibleRelocationsTy { NoRelocation = 0 , LocalRelocation = 1 , GlobalRelocations = 2 }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range< op_iterator > op_range
typedef iterator_range< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal , BasicBlockVal , FunctionVal , GlobalAliasVal ,
GlobalVariableVal , UndefValueVal , BlockAddressVal , ConstantExprVal ,
ConstantAggregateZeroVal , ConstantDataArrayVal , ConstantDataVectorVal , ConstantIntVal ,
ConstantFPVal , ConstantArrayVal , ConstantStructVal , ConstantVectorVal ,
ConstantPointerNullVal , MetadataAsValueVal , InlineAsmVal , InstructionVal ,
ConstantFirstVal = FunctionVal , ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl< const User > const_user_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Detailed Description
Definition at line 26 of file GlobalObject.h.
Constructor & Destructor Documentation
GlobalObject()
llvm::GlobalObject::GlobalObject (Type * Ty, ValueTy VTy, Use * Ops, unsigned NumOps, LinkageTypes Linkage, const Twine & Name) inline protected
Definition at line 30 of file GlobalObject.h.
References llvm::GlobalValue::Linkage, Name, ObjComdat, and llvm::GlobalValue::setGlobalValueSubClassData().
Member Function Documentation
classof()
bool llvm::GlobalObject::classof (const Value * V) inline static
Definition at line 68 of file GlobalObject.h.
References llvm::Value::FunctionVal, and llvm::Value::GlobalVariableVal.
copyAttributesFrom()
void GlobalObject::copyAttributesFrom (const GlobalValue * Src) override virtual
Copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
copyAttributesFrom - copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Reimplemented from llvm::GlobalValue.
Reimplemented in llvm::GlobalVariable.
Definition at line 99 of file Globals.cpp.
References llvm::cast(), llvm::GlobalValue::copyAttributesFrom(), setAlignment(), and setSection().
Referenced by llvm::Function::copyAttributesFrom(), and llvm::GlobalVariable::copyAttributesFrom().
getAlignment()
unsigned llvm::GlobalObject::getAlignment () const inline
Definition at line 46 of file GlobalObject.h.
References llvm::GlobalValue::getGlobalValueSubClassData().
Referenced by llvm::DataLayout::getPreferredAlignment(), llvm::AssemblyWriter::printGlobal(), setAlignment(), SRAGlobal(), and llvm::ObjectSizeOffsetVisitor::visitGlobalVariable().
getComdat() [1/2]
Comdat * llvm::GlobalObject::getComdat () inline
Definition at line 62 of file GlobalObject.h.
References ObjComdat.
getComdat() [2/2]
const Comdat * llvm::GlobalObject::getComdat () const inline
Definition at line 61 of file GlobalObject.h.
References ObjComdat.
Referenced by hasComdat(), llvm::maybePrintComdat(), and llvm::SymbolRewriter::rewriteComdat().
getGlobalObjectSubClassData()
unsigned GlobalObject::getGlobalObjectSubClassData () const
Definition at line 87 of file Globals.cpp.
References AlignmentBits, and llvm::GlobalValue::getGlobalValueSubClassData().
Referenced by llvm::Function::isMaterializable(), and setGlobalObjectSubClassData().
getSection()
const char * llvm::GlobalObject::getSection () const inline
Definition at line 57 of file GlobalObject.h.
References Section.
Referenced by llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::WinEH::getUnwindInfoSection(), hasSection(), and llvm::AssemblyWriter::printGlobal().
hasComdat()
bool llvm::GlobalObject::hasComdat () const inline
Definition at line 60 of file GlobalObject.h.
References getComdat().
hasSection()
bool llvm::GlobalObject::hasSection () const inline
Definition at line 56 of file GlobalObject.h.
References llvm::StringRef::empty(), and getSection().
Referenced by isSuitableForBSS(), and llvm::AssemblyWriter::printGlobal().
setAlignment()
void GlobalObject::setAlignment (unsigned Align)
Definition at line 77 of file Globals.cpp.
References Align, getAlignment(), llvm::GlobalValue::getGlobalValueSubClassData(), llvm::Log2_32(), and llvm::GlobalValue::setGlobalValueSubClassData().
Referenced by copyAttributesFrom(), createPrivateGlobalForString(), and SRAGlobal().
setComdat()
void llvm::GlobalObject::setComdat (Comdat * C) inline
Definition at line 63 of file GlobalObject.h.
References ObjComdat.
Referenced by llvm::SymbolRewriter::rewriteComdat().
setGlobalObjectSubClassData()
void GlobalObject::setGlobalObjectSubClassData (unsigned Val)
Definition at line 92 of file Globals.cpp.
References AlignmentBits, getGlobalObjectSubClassData(), llvm::GlobalValue::getGlobalValueSubClassData(), and llvm::GlobalValue::setGlobalValueSubClassData().
Referenced by llvm::Function::setIsMaterializable().
setSection()
void GlobalObject::setSection (StringRef S)
Definition at line 126 of file Globals.cpp.
References Section.
Referenced by assureFPCallStub(), copyAttributesFrom(), createFPFnStub(), and llvm::JumpInstrTables::insertEntry().
Member Data Documentation
AlignmentBits
const unsigned llvm::GlobalObject::AlignmentBits = 5 static protected
Definition at line 38 of file GlobalObject.h.
Referenced by getGlobalObjectSubClassData(), and setGlobalObjectSubClassData().
GlobalObjectSubClassDataBits
const unsigned llvm::GlobalObject::GlobalObjectSubClassDataBits static protected
Initial value:
=
      GlobalValueSubClassDataBits - AlignmentBits
Definition at line 39 of file GlobalObject.h.
ObjComdat
Comdat* llvm::GlobalObject::ObjComdat protected
Definition at line 37 of file GlobalObject.h.
Referenced by getComdat(), getComdat(), GlobalObject(), and setComdat().
Section
std::string llvm::GlobalObject::Section protected
Definition at line 36 of file GlobalObject.h.
Referenced by getSection(), and setSection().
The documentation for this class was generated from the following files:
GlobalObject.h
Globals.cpp