LLVM: llvm::ConstantSDNode Class Reference
LLVM API Documentation
llvm::ConstantSDNode Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
const ConstantInt * getConstantIntValue () const
const APInt & getAPIntValue () const
uint64_t getZExtValue () const
int64_t getSExtValue () const
bool isOne () const
bool isNullValue () const
bool isAllOnesValue () const
bool isOpaque () const
Public Member Functions inherited from llvm::SDNode
unsigned getOpcode () const
bool isTargetOpcode () const
bool isTargetMemoryOpcode () const
bool isMemIntrinsic () const
bool isMachineOpcode () const
unsigned getMachineOpcode () const
bool getHasDebugValue () const
getHasDebugValue - get this bit.
void setHasDebugValue (bool b)
setHasDebugValue - set this bit.
bool use_empty () const
bool hasOneUse () const
size_t use_size () const
int getNodeId () const
void setNodeId (int Id)
setNodeId - Set unique node id.
unsigned getIROrder () const
void setIROrder (unsigned Order)
const DebugLoc getDebugLoc () const
getDebugLoc - Return the source location info.
void setDebugLoc (const DebugLoc dl)
use_iterator use_begin () const
iterator_range< use_iterator > uses ()
iterator_range< use_iterator > uses () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
bool hasAnyUseOfValue (unsigned Value) const
bool isOnlyUserOf (SDNode *N) const
bool isOperandOf (SDNode *N) const
bool isPredecessorOf (const SDNode *N) const
bool hasPredecessor (const SDNode *N) const
bool hasPredecessorHelper (const SDNode *N, SmallPtrSetImpl< const SDNode * > &Visited, SmallVectorImpl< const SDNode * > &Worklist) const
unsigned getNumOperands () const
uint64_t getConstantOperandVal (unsigned Num) const
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< SDUse > ops () const
SDVTList getVTList () const
SDNode * getGluedNode () const
const SDNode * getGluedMachineNode () const
SDNode * getGluedUser () const
unsigned getNumValues () const
EVT getValueType (unsigned ResNo) const
MVT getSimpleValueType (unsigned ResNo) const
unsigned getValueSizeInBits (unsigned ResNo) const
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=nullptr) const
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printr (raw_ostream &OS, const SelectionDAG *G=nullptr) const
void printrFull (raw_ostream &O, const SelectionDAG *G=nullptr) const
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=nullptr, unsigned depth=100) const
void dump () const
dump - Dump this node, for debugging.
void dumpr () const
dumpr - Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
void dumpr (const SelectionDAG *G) const
void dumprFull (const SelectionDAG *G=nullptr) const
void dumprWithDepth (const SelectionDAG *G=nullptr, unsigned depth=100) const
void Profile (FoldingSetNodeID &ID) const
void addUse (SDUse &U)
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node< SDNode >
SDNode * getPrevNode ()
Get the previous node, or 0 for the list head.
SDNode * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::SDNode
static use_iterator use_end ()
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Friends
class SelectionDAG
Additional Inherited Members
Public Types inherited from llvm::SDNode
typedef SDUse * op_iterator
typedef const EVT * value_iterator
Protected Member Functions inherited from llvm::SDNode
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs, ArrayRef< SDValue > Ops)
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs)
void InitOperands (SDUse *Ops, const SDValue &Op0)
InitOperands - Initialize the operands list of this with 1 operand.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1)
InitOperands - Initialize the operands list of this with 2 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2)
InitOperands - Initialize the operands list of this with 3 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2, const SDValue &Op3)
InitOperands - Initialize the operands list of this with 4 operands.
void InitOperands (SDUse *Ops, const SDValue *Vals, unsigned N)
InitOperands - Initialize the operands list of this with N operands.
void DropOperands ()
Protected Member Functions inherited from llvm::ilist_node< SDNode >
ilist_node ()
Static Protected Member Functions inherited from llvm::SDNode
static SDVTList getSDVTList (EVT VT)
Protected Attributes inherited from llvm::SDNode
uint16_t SubclassData: 14
Detailed Description
Definition at line 1376 of file SelectionDAGNodes.h.
Member Function Documentation
classof()
bool llvm::ConstantSDNode::classof (const SDNode * N) inline static
Definition at line 1397 of file SelectionDAGNodes.h.
References llvm::ISD::Constant, N, llvm::SDNode::SDNode(), and llvm::ISD::TargetConstant.
getAPIntValue()
const APInt & llvm::ConstantSDNode::getAPIntValue () const inline
Definition at line 1387 of file SelectionDAGNodes.h.
Referenced by ChangeVSETULTtoVSETULE(), llvm::SelectionDAGISel::CheckAndMask(), llvm::SelectionDAGISel::CheckOrMask(), llvm::SelectionDAG::getNode(), getTargetVShiftByConstNode(), llvm::TargetLowering::isConstFalseVal(), llvm::TargetLowering::isConstTrueVal(), isXor1OfSetCC(), LowerShift(), matchRotateSub(), performANDCombine(), PerformINTRINSIC_WO_CHAINCombine(), PerformORCombine(), PerformSHLCombine(), TryMULWIDECombine(), and tryToFoldExtendOfConstant().
getConstantIntValue()
const ConstantInt * llvm::ConstantSDNode::getConstantIntValue () const inline
Definition at line 1386 of file SelectionDAGNodes.h.
getSExtValue()
int64_t llvm::ConstantSDNode::getSExtValue () const inline
Definition at line 1389 of file SelectionDAGNodes.h.
Referenced by canFoldInAddressingMode(), checkHighLaneIndex(), createCMovFP(), getAtomicLoadArithTargetConstant(), getGatherNode(), getPrefetchNode(), getScatterNode(), isExtendedBUILD_VECTOR(), llvm::isPositiveHalfWord(), llvm::PPCTargetLowering::LowerAsmOperandForConstraint(), PerformOrCombine(), performORCombine(), and performSELECTCombine().
getZExtValue()
uint64_t llvm::ConstantSDNode::getZExtValue () const inline
Definition at line 1388 of file SelectionDAGNodes.h.
Referenced by AddCombineToVPADDL(), adjustForTestUnderMask(), llvm::SIInstrInfo::areLoadsFromSameBasePtr(), checkBoolTestSetCCCombine(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::ComputeNumSignBitsForTargetNode(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), FoldOperand(), getExtendTypeForNode(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), isAllConstantBuildVector(), isBSwapHWordElement(), isLegalMUBUFImmOffset(), LowerATOMIC_FENCE(), PerformANDCombine(), PerformAndCombine(), performANDCombine(), PerformBFICombine(), performCMovFPCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), PerformORCombine(), performORCombine(), performSELECTCombine(), performSRACombine(), llvm::TargetLowering::SimplifyDemandedBits(), tryCombineCRC32(), tryCombineToBSL(), and tryLowerToSLI().
isAllOnesValue()
bool llvm::ConstantSDNode::isAllOnesValue () const inline
Definition at line 1393 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::getNode(), llvm::TargetLowering::isConstTrueVal(), and LowerXOR().
isNullValue()
bool llvm::ConstantSDNode::isNullValue () const inline
Definition at line 1392 of file SelectionDAGNodes.h.
Referenced by llvm::AMDGPUTargetLowering::ComputeNumSignBitsForTargetNode(), ConvertSelectToConcatVector(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAG::getNode(), llvm::TargetLowering::isConstFalseVal(), isExtendedBUILD_VECTOR(), isSetCC(), isTruncateOf(), and LowerXOR().
isOne()
bool llvm::ConstantSDNode::isOne () const inline
Definition at line 1391 of file SelectionDAGNodes.h.
Referenced by llvm::TargetLowering::isConstTrueVal(), and isSetCC().
isOpaque()
bool llvm::ConstantSDNode::isOpaque () const inline
Definition at line 1395 of file SelectionDAGNodes.h.
References llvm::SDNode::SubclassData.
Referenced by ChangeVSETULTtoVSETULE(), llvm::SelectionDAG::FoldConstantArithmetic(), and SelectionDAG.
Friends And Related Symbol Documentation
SelectionDAG
friend class SelectionDAG friend
Definition at line 1378 of file SelectionDAGNodes.h.
References llvm::SDNode::getSDVTList(), isOpaque(), llvm::SDNode::SDNode(), SelectionDAG, and llvm::SDNode::SubclassData.
Referenced by SelectionDAG.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h