LLVM: llvm::ForwardDominanceFrontierBase< BlockT > Class Template Reference
LLVM API Documentation
llvm::ForwardDominanceFrontierBase< BlockT > Class Template Reference
#include <DominanceFrontier.h>
Public Types
typedef DominatorTreeBase< BlockT > DomTreeT
typedef DomTreeNodeBase< BlockT > DomTreeNodeT
typedef DominanceFrontierBase< BlockT >::DomSetType DomSetType
Public Types inherited from llvm::DominanceFrontierBase< BlockT >
typedef std::set< BlockT * > DomSetType
typedef std::map< BlockT *, DomSetType > DomSetMapType
typedef DomSetMapType::iterator iterator
typedef DomSetMapType::const_iterator const_iterator
Public Member Functions
ForwardDominanceFrontierBase ()
void analyze (DomTreeT &DT)
const DomSetType & calculate (const DomTreeT &DT, const DomTreeNodeT *Node)
Public Member Functions inherited from llvm::DominanceFrontierBase< BlockT >
DominanceFrontierBase (bool isPostDom)
const std::vector< BlockT * > & getRoots () const
BlockT * getRoot () const
bool isPostDominator () const
void releaseMemory ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator find (BlockT *B)
const_iterator find (BlockT *B) const
iterator addBasicBlock (BlockT *BB, const DomSetType &frontier)
void removeBlock (BlockT *BB)
removeBlock - Remove basic block BB's frontier.
void addToFrontier (iterator I, BlockT *Node)
void removeFromFrontier (iterator I, BlockT *Node)
bool compareDomSet (DomSetType &DS1, const DomSetType &DS2) const
bool compare (DominanceFrontierBase< BlockT > &Other) const
void print (raw_ostream &OS) const
void dump () const
dump - Dump the dominance frontier to dbgs().
Additional Inherited Members
Protected Types inherited from llvm::DominanceFrontierBase< BlockT >
typedef GraphTraits< BlockT * > BlockTraits
Protected Attributes inherited from llvm::DominanceFrontierBase< BlockT >
DomSetMapType Frontiers
std::vector< BlockT * > Roots
const bool IsPostDominators
Detailed Description
template<class BlockT>
class llvm::ForwardDominanceFrontierBase< BlockT >
DominanceFrontier Class - Concrete subclass of DominanceFrontierBase that is used to compute a forward dominator frontiers.
Definition at line 115 of file DominanceFrontier.h.
Member Typedef Documentation
DomSetType
template<class BlockT> typedef DominanceFrontierBase<BlockT>::DomSetType llvm::ForwardDominanceFrontierBase< BlockT >::DomSetType
Definition at line 122 of file DominanceFrontier.h.
DomTreeNodeT
template<class BlockT> typedef DomTreeNodeBase<BlockT> llvm::ForwardDominanceFrontierBase< BlockT >::DomTreeNodeT
Definition at line 121 of file DominanceFrontier.h.
DomTreeT
template<class BlockT> typedef DominatorTreeBase<BlockT> llvm::ForwardDominanceFrontierBase< BlockT >::DomTreeT
Definition at line 120 of file DominanceFrontier.h.
Constructor & Destructor Documentation
ForwardDominanceFrontierBase()
template<class BlockT> llvm::ForwardDominanceFrontierBase< BlockT >::ForwardDominanceFrontierBase () inline
Definition at line 124 of file DominanceFrontier.h.
References llvm::DominanceFrontierBase< BlockT >::DominanceFrontierBase().
Member Function Documentation
analyze()
template<class BlockT> void llvm::ForwardDominanceFrontierBase< BlockT >::analyze (DomTreeT & DT) inline
Definition at line 126 of file DominanceFrontier.h.
References calculate(), llvm::DominatorBase< NodeT >::getRoots(), and llvm::DominanceFrontierBase< BlockT >::Roots.
calculate()
template<class BlockT> const ForwardDominanceFrontierBase< BlockT >::DomSetType & llvm::ForwardDominanceFrontierBase< BlockT >::calculate (const DomTreeT & DT, const DomTreeNodeT * Node)
Definition at line 153 of file DominanceFrontierImpl.h.
References llvm::DomTreeNodeBase< NodeT >::begin(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::DomTreeNodeBase< NodeT >::end(), llvm::DominanceFrontierBase< BlockT >::Frontiers, llvm::DomTreeNodeBase< NodeT >::getBlock(), llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::DominatorTreeBase< NodeT >::properlyDominates().
Referenced by analyze().
The documentation for this class was generated from the following files:
DominanceFrontier.h
DominanceFrontierImpl.h