LLVM: llvm::ModuleAnalysisManagerCGSCCProxy Class Reference
LLVM API Documentation
llvm::ModuleAnalysisManagerCGSCCProxy Class Reference
A CGSCC analysis which acts as a proxy for a module analysis manager.
#include <CGSCCPassManager.h>
Classes
class Result
Result proxy object for ModuleAnalysisManagerCGSCCProxy.
Public Member Functions
ModuleAnalysisManagerCGSCCProxy (const ModuleAnalysisManager &MAM)
ModuleAnalysisManagerCGSCCProxy (const ModuleAnalysisManagerCGSCCProxy &Arg)
ModuleAnalysisManagerCGSCCProxy (ModuleAnalysisManagerCGSCCProxy &&Arg)
ModuleAnalysisManagerCGSCCProxy & operator= (ModuleAnalysisManagerCGSCCProxy RHS)
Result run (LazyCallGraph::SCC &)
Run the analysis pass and create our proxy result object. Nothing to see here, it just forwards the MAM reference into the result.
Static Public Member Functions
static void * ID ()
static StringRef name ()
Detailed Description
A CGSCC analysis which acts as a proxy for a module analysis manager.
This primarily provides an accessor to a parent module analysis manager to CGSCC passes. Only the const interface of the module analysis manager is provided to indicate that once inside of a CGSCC analysis pass you cannot request a module analysis to actually run. Instead, the user must rely on the getCachedResult API.
This proxy doesn't manage the invalidation in any way. That is handled by the recursive return path of each layer of the pass manager and the returned PreservedAnalysis set.
Definition at line 133 of file CGSCCPassManager.h.
Constructor & Destructor Documentation
ModuleAnalysisManagerCGSCCProxy() [1/3]
llvm::ModuleAnalysisManagerCGSCCProxy::ModuleAnalysisManagerCGSCCProxy (const ModuleAnalysisManager & MAM) inline
Definition at line 161 of file CGSCCPassManager.h.
Referenced by ModuleAnalysisManagerCGSCCProxy(), ModuleAnalysisManagerCGSCCProxy(), and operator=().
ModuleAnalysisManagerCGSCCProxy() [2/3]
llvm::ModuleAnalysisManagerCGSCCProxy::ModuleAnalysisManagerCGSCCProxy (const ModuleAnalysisManagerCGSCCProxy & Arg) inline
Definition at line 165 of file CGSCCPassManager.h.
References ModuleAnalysisManagerCGSCCProxy().
ModuleAnalysisManagerCGSCCProxy() [3/3]
llvm::ModuleAnalysisManagerCGSCCProxy::ModuleAnalysisManagerCGSCCProxy (ModuleAnalysisManagerCGSCCProxy && Arg) inline
Definition at line 167 of file CGSCCPassManager.h.
References ModuleAnalysisManagerCGSCCProxy().
Member Function Documentation
ID()
void * llvm::ModuleAnalysisManagerCGSCCProxy::ID () inline static
Definition at line 157 of file CGSCCPassManager.h.
name()
StringRef llvm::ModuleAnalysisManagerCGSCCProxy::name () inline static
Definition at line 159 of file CGSCCPassManager.h.
operator=()
ModuleAnalysisManagerCGSCCProxy & llvm::ModuleAnalysisManagerCGSCCProxy::operator= (ModuleAnalysisManagerCGSCCProxy RHS) inline
Definition at line 170 of file CGSCCPassManager.h.
References ModuleAnalysisManagerCGSCCProxy(), and std::swap().
run()
Result llvm::ModuleAnalysisManagerCGSCCProxy::run (LazyCallGraph::SCC &) inline
Run the analysis pass and create our proxy result object. Nothing to see here, it just forwards the MAM reference into the result.
Definition at line 178 of file CGSCCPassManager.h.
The documentation for this class was generated from the following files:
CGSCCPassManager.h
CGSCCPassManager.cpp