LLVM: llvm::legacy::PassManager Class Reference
LLVM API Documentation
llvm::legacy::PassManager Class Reference
PassManager manages ModulePassManagers.
#include <LegacyPassManager.h>
Public Member Functions
PassManager ()
Create new pass manager.
~PassManager ()
void add (Pass *P) override
bool run (Module &M)
Public Member Functions inherited from llvm::legacy::PassManagerBase
virtual ~PassManagerBase ()
Detailed Description
PassManager manages ModulePassManagers.
Definition at line 49 of file LegacyPassManager.h.
Constructor & Destructor Documentation
PassManager()
PassManager::PassManager ()
Create new pass manager.
Definition at line 1739 of file LegacyPassManager.cpp.
~PassManager()
PassManager::~PassManager ()
Definition at line 1745 of file LegacyPassManager.cpp.
Member Function Documentation
add()
void PassManager::add (Pass * P) override virtual
Add a pass to the queue of passes to run. This passes ownership of the Pass to the PassManager. When the PassManager is destroyed, the pass will be destroyed as well, so there is no need to delete the pass. This may even destroy the pass right away if it is found to be redundant. This implies that all passes MUST be allocated with 'new'.
Implements llvm::legacy::PassManagerBase.
Definition at line 1749 of file LegacyPassManager.cpp.
References P.
Referenced by llvm::MCJIT::emitObject(), and llvm::lintModule().
run()
bool PassManager::run (Module & M)
run - Execute all of the passes scheduled for execution. Keep track of whether any of the passes modifies the module, and if so, return true.
Definition at line 1755 of file LegacyPassManager.cpp.
Referenced by llvm::MCJIT::emitObject(), and llvm::lintModule().
The documentation for this class was generated from the following files:
LegacyPassManager.h
LegacyPassManager.cpp