LLVM: llvm::MipsTargetELFStreamer Class Reference
LLVM API Documentation
llvm::MipsTargetELFStreamer Class Reference
#include <MipsTargetStreamer.h>
Public Member Functions
bool isMicroMipsEnabled () const
MCELFStreamer & getStreamer ()
MipsTargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
void emitLabel (MCSymbol *Symbol) override
void emitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
void finish () override
void emitDirectiveSetMicroMips () override
void emitDirectiveSetNoMicroMips () override
void emitDirectiveSetMips16 () override
void emitDirectiveSetNoReorder () override
void emitDirectiveEnd (StringRef Name) override
void emitDirectiveEnt (const MCSymbol &Symbol) override
void emitDirectiveAbiCalls () override
void emitDirectiveNaN2008 () override
void emitDirectiveNaNLegacy () override
void emitDirectiveOptionPic0 () override
void emitDirectiveOptionPic2 () override
void emitFrame (unsigned StackReg, unsigned StackSize, unsigned ReturnReg) override
void emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) override
void emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) override
void emitDirectiveCpLoad (unsigned RegNo) override
void emitDirectiveCpsetup (unsigned RegNo, int RegOrOffset, const MCSymbol &Sym, bool IsReg) override
void emitDirectiveModuleOddSPReg (bool Enabled, bool IsO32ABI) override
void emitMipsAbiFlags () override
Public Member Functions inherited from llvm::MipsTargetStreamer
MipsTargetStreamer (MCStreamer &S)
virtual void emitDirectiveSetNoMips16 ()
virtual void emitDirectiveSetReorder ()
virtual void emitDirectiveSetMacro ()
virtual void emitDirectiveSetNoMacro ()
virtual void emitDirectiveSetMsa ()
virtual void emitDirectiveSetNoMsa ()
virtual void emitDirectiveSetAt ()
virtual void emitDirectiveSetNoAt ()
virtual void emitDirectiveSetArch (StringRef Arch)
virtual void emitDirectiveSetMips0 ()
virtual void emitDirectiveSetMips1 ()
virtual void emitDirectiveSetMips2 ()
virtual void emitDirectiveSetMips3 ()
virtual void emitDirectiveSetMips4 ()
virtual void emitDirectiveSetMips5 ()
virtual void emitDirectiveSetMips32 ()
virtual void emitDirectiveSetMips32R2 ()
virtual void emitDirectiveSetMips32R6 ()
virtual void emitDirectiveSetMips64 ()
virtual void emitDirectiveSetMips64R2 ()
virtual void emitDirectiveSetMips64R6 ()
virtual void emitDirectiveSetDsp ()
virtual void emitDirectiveSetNoDsp ()
virtual void emitDirectiveSetPop ()
virtual void emitDirectiveSetPush ()
virtual void emitDirectiveModuleFP (MipsABIFlagsSection::FpABIKind Value, bool Is32BitABI)
void emitDirectiveModuleFP ()
virtual void emitDirectiveSetFp (MipsABIFlagsSection::FpABIKind Value)
void forbidModuleDirective ()
bool isModuleDirectiveAllowed ()
template<class PredicateLibrary>
void updateABIInfo (const PredicateLibrary &P)
MipsABIFlagsSection & getABIFlagsSection ()
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
const MCStreamer & getStreamer ()
Protected Member Functions
bool isO32 () const
bool isN32 () const
bool isN64 () const
Additional Inherited Members
Protected Attributes inherited from llvm::MipsTargetStreamer
MipsABIFlagsSection ABIFlagsSection
bool GPRInfoSet
unsigned GPRBitMask
int GPROffset
bool FPRInfoSet
unsigned FPRBitMask
int FPROffset
bool FrameInfoSet
int FrameOffset
unsigned FrameReg
unsigned ReturnReg
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 187 of file MipsTargetStreamer.h.
Constructor & Destructor Documentation
MipsTargetELFStreamer()
MipsTargetELFStreamer::MipsTargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 334 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_32BITMODE, llvm::ELF::EF_MIPS_ABI2, llvm::ELF::EF_MIPS_ABI_O32, llvm::ELF::EF_MIPS_ARCH_1, llvm::ELF::EF_MIPS_ARCH_2, llvm::ELF::EF_MIPS_ARCH_3, llvm::ELF::EF_MIPS_ARCH_32, llvm::ELF::EF_MIPS_ARCH_32R2, llvm::ELF::EF_MIPS_ARCH_32R6, llvm::ELF::EF_MIPS_ARCH_4, llvm::ELF::EF_MIPS_ARCH_5, llvm::ELF::EF_MIPS_ARCH_64, llvm::ELF::EF_MIPS_ARCH_64R2, llvm::ELF::EF_MIPS_ARCH_64R6, llvm::ELF::EF_MIPS_CPIC, llvm::ELF::EF_MIPS_NAN2008, llvm::ELF::EF_MIPS_PIC, Features, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), getStreamer(), llvm::MipsTargetStreamer::MipsTargetStreamer(), llvm::Reloc::PIC_, llvm::MCAssembler::setELFHeaderEFlags(), T, and true.
Member Function Documentation
emitAssignment()
void MipsTargetELFStreamer::emitAssignment (MCSymbol * Symbol, const MCExpr * Value) override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 436 of file MipsTargetStreamer.cpp.
References llvm::MCObjectStreamer::getOrCreateSymbolData(), llvm::MCELF::getOther(), getStreamer(), llvm::MCELF::GetType(), llvm::MCELF::setOther(), llvm::ELF::STO_MIPS_MICROMIPS, llvm::ELF::STT_FUNC, and llvm::MCExpr::SymbolRef.
emitDirectiveAbiCalls()
void MipsTargetELFStreamer::emitDirectiveAbiCalls () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 533 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_CPIC, llvm::ELF::EF_MIPS_PIC, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveCpLoad()
void MipsTargetELFStreamer::emitDirectiveCpLoad (unsigned RegNo) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 600 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCInst::clear(), llvm::MCSymbolRefExpr::Create(), llvm::MCOperand::CreateExpr(), llvm::MCOperand::CreateReg(), llvm::MCObjectStreamer::EmitInstruction(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::GetOrCreateSymbol(), llvm::MCAssembler::getOrCreateSymbolData(), getStreamer(), isN32(), isN64(), llvm::MCInst::setOpcode(), llvm::MCSymbolRefExpr::VK_Mips_ABS_HI, and llvm::MCSymbolRefExpr::VK_Mips_ABS_LO.
emitDirectiveCpsetup()
void MipsTargetELFStreamer::emitDirectiveCpsetup (unsigned RegNo, int RegOrOffset, const MCSymbol & Sym, bool IsReg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 651 of file MipsTargetStreamer.cpp.
References llvm::MCInst::addOperand(), llvm::MCInst::clear(), llvm::MCSymbolRefExpr::Create(), llvm::MCOperand::CreateExpr(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MCObjectStreamer::EmitInstruction(), llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCSymbol::getName(), getStreamer(), isN32(), isN64(), llvm::MCInst::setOpcode(), llvm::MCSymbolRefExpr::VK_Mips_GPOFF_HI, and llvm::MCSymbolRefExpr::VK_Mips_GPOFF_LO.
emitDirectiveEnd()
void MipsTargetELFStreamer::emitDirectiveEnd (StringRef Name) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 491 of file MipsTargetStreamer.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitValueImpl(), llvm::MipsTargetStreamer::FPRBitMask, llvm::MipsTargetStreamer::FPRInfoSet, llvm::MipsTargetStreamer::FPROffset, llvm::MipsTargetStreamer::FrameInfoSet, llvm::MipsTargetStreamer::FrameOffset, llvm::MipsTargetStreamer::FrameReg, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getELFSection(), llvm::SectionKind::getMetadata(), llvm::MCAssembler::getOrCreateSectionData(), getStreamer(), llvm::MipsTargetStreamer::GPRBitMask, llvm::MipsTargetStreamer::GPRInfoSet, llvm::MipsTargetStreamer::GPROffset, Name, llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), llvm::MipsTargetStreamer::ReturnReg, llvm::MCSectionData::setAlignment(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_PROGBITS, llvm::ELF::SHT_REL, llvm::MCStreamer::SwitchSection(), and llvm::MCSymbolRefExpr::VK_None.
emitDirectiveEnt()
void MipsTargetELFStreamer::emitDirectiveEnt (const MCSymbol & Symbol) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 529 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::FPRInfoSet, llvm::MipsTargetStreamer::FrameInfoSet, and llvm::MipsTargetStreamer::GPRInfoSet.
emitDirectiveModuleOddSPReg()
void MipsTargetELFStreamer::emitDirectiveModuleOddSPReg (bool Enabled, bool IsO32ABI) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 722 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABIFlagsSection, llvm::MipsTargetStreamer::emitDirectiveModuleOddSPReg(), and Enabled.
emitDirectiveNaN2008()
void MipsTargetELFStreamer::emitDirectiveNaN2008 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 540 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_NAN2008, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveNaNLegacy()
void MipsTargetELFStreamer::emitDirectiveNaNLegacy () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 547 of file MipsTargetStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveOptionPic0()
void MipsTargetELFStreamer::emitDirectiveOptionPic0 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 554 of file MipsTargetStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveOptionPic2()
void MipsTargetELFStreamer::emitDirectiveOptionPic2 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 563 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_CPIC, llvm::ELF::EF_MIPS_PIC, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveSetMicroMips()
void MipsTargetELFStreamer::emitDirectiveSetMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 460 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_MICROMIPS, llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveSetMips16()
void MipsTargetELFStreamer::emitDirectiveSetMips16 () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 475 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_ARCH_ASE_M16, llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitDirectiveSetNoMicroMips()
void MipsTargetELFStreamer::emitDirectiveSetNoMicroMips () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 470 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::forbidModuleDirective().
emitDirectiveSetNoReorder()
void MipsTargetELFStreamer::emitDirectiveSetNoReorder () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 483 of file MipsTargetStreamer.cpp.
References llvm::ELF::EF_MIPS_NOREORDER, llvm::MipsTargetStreamer::forbidModuleDirective(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), getStreamer(), and llvm::MCAssembler::setELFHeaderEFlags().
emitFMask()
void MipsTargetELFStreamer::emitFMask (unsigned FPUBitmask, int FPUTopSavedRegOff) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 593 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::FPRBitMask, llvm::MipsTargetStreamer::FPRInfoSet, and llvm::MipsTargetStreamer::FPROffset.
emitFrame()
void MipsTargetELFStreamer::emitFrame (unsigned StackReg, unsigned StackSize, unsigned ReturnReg) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 575 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::FrameInfoSet, llvm::MipsTargetStreamer::FrameOffset, llvm::MipsTargetStreamer::FrameReg, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCContext::getRegisterInfo(), getStreamer(), and llvm::MipsTargetStreamer::ReturnReg.
emitLabel()
void MipsTargetELFStreamer::emitLabel (MCSymbol * Symbol) override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 397 of file MipsTargetStreamer.cpp.
References llvm::MCObjectStreamer::getOrCreateSymbolData(), getStreamer(), llvm::MCELF::GetType(), isMicroMipsEnabled(), llvm::MCELF::setOther(), llvm::ELF::STO_MIPS_MICROMIPS, and llvm::ELF::STT_FUNC.
emitMask()
void MipsTargetELFStreamer::emitMask (unsigned CPUBitmask, int CPUTopSavedRegOff) override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 586 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::GPRBitMask, llvm::MipsTargetStreamer::GPRInfoSet, and llvm::MipsTargetStreamer::GPROffset.
emitMipsAbiFlags()
void MipsTargetELFStreamer::emitMipsAbiFlags () override virtual
Reimplemented from llvm::MipsTargetStreamer.
Definition at line 708 of file MipsTargetStreamer.cpp.
References llvm::MipsTargetStreamer::ABIFlagsSection, llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getELFSection(), llvm::SectionKind::getMetadata(), llvm::MCAssembler::getOrCreateSectionData(), getStreamer(), llvm::MCSectionData::setAlignment(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_MIPS_ABIFLAGS, and llvm::MCStreamer::SwitchSection().
Referenced by finish().
finish()
void MipsTargetELFStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 411 of file MipsTargetStreamer.cpp.
References emitMipsAbiFlags(), llvm::MipsELFStreamer::EmitMipsOptionRecords(), llvm::MCSectionData::getAlignment(), llvm::MCObjectStreamer::getAssembler(), llvm::MCObjectFileInfo::getBSSSection(), llvm::MCAssembler::getContext(), llvm::MCObjectFileInfo::getDataSection(), llvm::MCContext::getObjectFileInfo(), llvm::MCAssembler::getOrCreateSectionData(), getStreamer(), llvm::MCObjectFileInfo::getTextSection(), llvm::MCSectionData::setAlignment(), and llvm::MCTargetStreamer::Streamer.
getStreamer()
MCELFStreamer & MipsTargetELFStreamer::getStreamer ()
Definition at line 456 of file MipsTargetStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
Referenced by emitAssignment(), emitDirectiveAbiCalls(), emitDirectiveCpLoad(), emitDirectiveCpsetup(), emitDirectiveEnd(), emitDirectiveNaN2008(), emitDirectiveNaNLegacy(), emitDirectiveOptionPic0(), emitDirectiveOptionPic2(), emitDirectiveSetMicroMips(), emitDirectiveSetMips16(), emitDirectiveSetNoReorder(), emitFrame(), emitLabel(), emitMipsAbiFlags(), finish(), and MipsTargetELFStreamer().
isMicroMipsEnabled()
bool llvm::MipsTargetELFStreamer::isMicroMipsEnabled () const inline
Definition at line 193 of file MipsTargetStreamer.h.
Referenced by llvm::MipsELFStreamer::EmitInstruction(), and emitLabel().
isN32()
bool llvm::MipsTargetELFStreamer::isN32 () const inline protected
Definition at line 230 of file MipsTargetStreamer.h.
Referenced by emitDirectiveCpLoad(), and emitDirectiveCpsetup().
isN64()
bool llvm::MipsTargetELFStreamer::isN64 () const inline protected
Definition at line 231 of file MipsTargetStreamer.h.
Referenced by emitDirectiveCpLoad(), and emitDirectiveCpsetup().
isO32()
bool llvm::MipsTargetELFStreamer::isO32 () const inline protected
Definition at line 229 of file MipsTargetStreamer.h.
The documentation for this class was generated from the following files:
MipsTargetStreamer.h
MipsTargetStreamer.cpp