LLVM: llvm::MCEncodedFragmentWithFixups Class Reference
LLVM API Documentation
llvm::MCEncodedFragmentWithFixups Class Reference abstract
#include <MCAssembler.h>
Public Types
typedef SmallVectorImpl< MCFixup >::const_iterator const_fixup_iterator
typedef SmallVectorImpl< MCFixup >::iterator fixup_iterator
Public Types inherited from llvm::MCFragment
enum FragmentType {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Relaxable , FT_Org , FT_Dwarf , FT_DwarfFrame ,
FT_LEB
}
Public Member Functions
MCEncodedFragmentWithFixups (MCFragment::FragmentType FType, MCSectionData *SD=nullptr)
virtual ~MCEncodedFragmentWithFixups ()
virtual SmallVectorImpl< MCFixup > & getFixups ()=0
virtual const SmallVectorImpl< MCFixup > & getFixups () const =0
virtual fixup_iterator fixup_begin ()=0
virtual const_fixup_iterator fixup_begin () const =0
virtual fixup_iterator fixup_end ()=0
virtual const_fixup_iterator fixup_end () const =0
Public Member Functions inherited from llvm::MCEncodedFragment
MCEncodedFragment (MCFragment::FragmentType FType, MCSectionData *SD=nullptr)
virtual ~MCEncodedFragment ()
virtual SmallVectorImpl< char > & getContents ()=0
virtual const SmallVectorImpl< char > & getContents () const =0
uint8_t getBundlePadding () const override
Get the padding size that must be inserted before this fragment. Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
void setBundlePadding (uint8_t N) override
Set the padding size for this fragment. By default it's a no-op, and only some fragments have a meaningful implementation.
Public Member Functions inherited from llvm::MCFragment
MCFragment ()
virtual ~MCFragment ()
FragmentType getKind () const
MCSectionData * getParent () const
void setParent (MCSectionData *Value)
MCSymbolData * getAtom () const
void setAtom (MCSymbolData *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
virtual bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
virtual bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
virtual void setAlignToBundleEnd (bool V)
void dump ()
Public Member Functions inherited from llvm::ilist_node< MCFragment >
MCFragment * getPrevNode ()
Get the previous node, or 0 for the list head.
MCFragment * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const MCFragment *F)
Static Public Member Functions inherited from llvm::MCEncodedFragment
static bool classof (const MCFragment *F)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType _Kind, MCSectionData *_Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node< MCFragment >
ilist_node ()
Detailed Description
Interface implemented by fragments that contain encoded instructions and/or data and also have fixups registered.
Definition at line 174 of file MCAssembler.h.
Member Typedef Documentation
const_fixup_iterator
typedef SmallVectorImpl<MCFixup>::const_iterator llvm::MCEncodedFragmentWithFixups::const_fixup_iterator
Definition at line 186 of file MCAssembler.h.
fixup_iterator
typedef SmallVectorImpl<MCFixup>::iterator llvm::MCEncodedFragmentWithFixups::fixup_iterator
Definition at line 187 of file MCAssembler.h.
Constructor & Destructor Documentation
MCEncodedFragmentWithFixups()
llvm::MCEncodedFragmentWithFixups::MCEncodedFragmentWithFixups (MCFragment::FragmentType FType, MCSectionData * SD = nullptr) inline
Definition at line 178 of file MCAssembler.h.
References llvm::MCEncodedFragment::MCEncodedFragment().
Referenced by llvm::MCDataFragment::MCDataFragment(), and llvm::MCRelaxableFragment::MCRelaxableFragment().
~MCEncodedFragmentWithFixups()
MCEncodedFragmentWithFixups::~MCEncodedFragmentWithFixups () virtual
Definition at line 284 of file MCAssembler.cpp.
Member Function Documentation
classof()
bool llvm::MCEncodedFragmentWithFixups::classof (const MCFragment * F) inline static
Definition at line 197 of file MCAssembler.h.
References F, llvm::MCFragment::FT_Data, and llvm::MCFragment::FT_Relaxable.
fixup_begin() [1/2]
virtual const_fixup_iterator llvm::MCEncodedFragmentWithFixups::fixup_begin () const pure virtual
Implemented in llvm::MCDataFragment, and llvm::MCRelaxableFragment.
fixup_begin() [2/2]
virtual fixup_iterator llvm::MCEncodedFragmentWithFixups::fixup_begin () pure virtual
Implemented in llvm::MCDataFragment, and llvm::MCRelaxableFragment.
fixup_end() [1/2]
virtual const_fixup_iterator llvm::MCEncodedFragmentWithFixups::fixup_end () const pure virtual
Implemented in llvm::MCDataFragment, and llvm::MCRelaxableFragment.
fixup_end() [2/2]
virtual fixup_iterator llvm::MCEncodedFragmentWithFixups::fixup_end () pure virtual
Implemented in llvm::MCDataFragment, and llvm::MCRelaxableFragment.
getFixups() [1/2]
virtual const SmallVectorImpl< MCFixup > & llvm::MCEncodedFragmentWithFixups::getFixups () const pure virtual
Implemented in llvm::MCDataFragment, and llvm::MCRelaxableFragment.
getFixups() [2/2]
virtual SmallVectorImpl< MCFixup > & llvm::MCEncodedFragmentWithFixups::getFixups () pure virtual
Implemented in llvm::MCDataFragment, and llvm::MCRelaxableFragment.
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp