LLVM: llvm::Statistic Class Reference
LLVM API Documentation
llvm::Statistic Class Reference
#include <Statistic.h>
Public Member Functions
llvm::sys::cas_flag getValue () const
const char * getName () const
const char * getDesc () const
void construct (const char *name, const char *desc)
construct - This should only be called for non-global statistics.
operator unsigned () const
const Statistic & operator= (unsigned Val)
const Statistic & operator++ ()
unsigned operator++ (int)
const Statistic & operator-- ()
unsigned operator-- (int)
const Statistic & operator+= (const unsigned &V)
const Statistic & operator-= (const unsigned &V)
const Statistic & operator*= (const unsigned &V)
const Statistic & operator/= (const unsigned &V)
Public Attributes
const char * Name
const char * Desc
volatile llvm::sys::cas_flag Value
bool Initialized
Protected Member Functions
Statistic & init ()
void RegisterStatistic ()
Detailed Description
Definition at line 35 of file Statistic.h.
Member Function Documentation
construct()
void llvm::Statistic::construct (const char * name, const char * desc) inline
construct - This should only be called for non-global statistics.
Definition at line 47 of file Statistic.h.
References Desc, Initialized, Name, and Value.
getDesc()
const char * llvm::Statistic::getDesc () const inline
Definition at line 44 of file Statistic.h.
References Desc.
getName()
const char * llvm::Statistic::getName () const inline
Definition at line 43 of file Statistic.h.
References Name.
getValue()
llvm::sys::cas_flag llvm::Statistic::getValue () const inline
Definition at line 42 of file Statistic.h.
References Value.
init()
Statistic & llvm::Statistic::init () inline protected
Definition at line 152 of file Statistic.h.
References Initialized, llvm::sys::MemoryFence(), RegisterStatistic(), and TsanHappensAfter.
Referenced by operator*=(), operator++(), operator++(), operator+=(), operator--(), operator--(), operator-=(), operator/=(), and operator=().
operator unsigned()
llvm::Statistic::operator unsigned () const inline
Definition at line 53 of file Statistic.h.
References Value.
operator*=()
const Statistic & llvm::Statistic::operator*= (const unsigned & V) inline
Definition at line 101 of file Statistic.h.
References llvm::sys::AtomicMul(), init(), and Value.
operator++() [1/2]
const Statistic & llvm::Statistic::operator++ () inline
Definition at line 61 of file Statistic.h.
References llvm::sys::AtomicIncrement(), init(), and Value.
operator++() [2/2]
unsigned llvm::Statistic::operator++ (int) inline
Definition at line 70 of file Statistic.h.
References llvm::sys::AtomicIncrement(), init(), and Value.
operator+=()
const Statistic & llvm::Statistic::operator+= (const unsigned & V) inline
Definition at line 89 of file Statistic.h.
References llvm::sys::AtomicAdd(), init(), and Value.
operator--() [1/2]
const Statistic & llvm::Statistic::operator-- () inline
Definition at line 77 of file Statistic.h.
References llvm::sys::AtomicDecrement(), init(), and Value.
operator--() [2/2]
unsigned llvm::Statistic::operator-- (int) inline
Definition at line 82 of file Statistic.h.
References llvm::sys::AtomicDecrement(), init(), and Value.
operator-=()
const Statistic & llvm::Statistic::operator-= (const unsigned & V) inline
Definition at line 95 of file Statistic.h.
References llvm::sys::AtomicAdd(), init(), and Value.
operator/=()
const Statistic & llvm::Statistic::operator/= (const unsigned & V) inline
Definition at line 106 of file Statistic.h.
References llvm::sys::AtomicDiv(), init(), and Value.
operator=()
const Statistic & llvm::Statistic::operator= (unsigned Val) inline
Definition at line 56 of file Statistic.h.
References init(), and Value.
RegisterStatistic()
void Statistic::RegisterStatistic () protected
RegisterStatistic - The first time a statistic is bumped, this method is called.
Definition at line 70 of file Statistic.cpp.
References Enabled, Initialized, llvm::sys::MemoryFence(), StatInfo, StatLock, TsanHappensBefore, TsanIgnoreWritesBegin, and TsanIgnoreWritesEnd.
Referenced by init().
Member Data Documentation
Desc
const char* llvm::Statistic::Desc
Definition at line 38 of file Statistic.h.
Referenced by construct(), and getDesc().
Initialized
bool llvm::Statistic::Initialized
Definition at line 40 of file Statistic.h.
Referenced by construct(), init(), and RegisterStatistic().
Name
const char* llvm::Statistic::Name
Definition at line 37 of file Statistic.h.
Referenced by construct(), and getName().
Value
volatile llvm::sys::cas_flag llvm::Statistic::Value
Definition at line 39 of file Statistic.h.
Referenced by construct(), getValue(), operator unsigned(), operator*=(), operator++(), operator++(), operator+=(), operator--(), operator--(), operator-=(), operator/=(), and operator=().
The documentation for this class was generated from the following files:
Statistic.h
Statistic.cpp