LLVM: llvm::DIVariable Class Reference
LLVM API Documentation
llvm::DIVariable Class Reference
This is a wrapper for a variable (e.g. parameter, local, global etc).
#include <DebugInfo.h>
Public Member Functions
DIVariable (const MDNode *N=nullptr)
StringRef getName () const
unsigned getLineNumber () const
unsigned getArgNumber () const
DIScope getContext () const
DIFile getFile () const
DITypeRef getType () const
bool isArtificial () const
Return true if this variable is marked as "artificial".
bool isObjectPointer () const
bool isIndirect () const
Return true if this variable is represented as a pointer.
MDNode * getInlinedAt () const
If this variable is inlined then return inline location.
bool Verify () const
bool isBlockByrefVariable (const DITypeIdentifierMap &Map) const
Check if this is a "__block" variable (Apple Blocks).
bool isInlinedFnArgument (const Function *CurFn)
Check if this is an inlined function argument.
unsigned getSizeInBits (const DITypeIdentifierMap &Map)
Return the size reported by the variable's type.
void printExtendedName (raw_ostream &OS) const
Public Member Functions inherited from llvm::DIDescriptor
DIDescriptor (const MDNode *N=nullptr)
bool Verify () const
MDNode * get () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
StringRef getHeader () const
size_t getNumHeaderFields () const
StringRef getHeaderField (unsigned Index) const
template<class T>
T getHeaderFieldAs (unsigned Index) const
uint16_t getTag () const
bool isDerivedType () const
bool isCompositeType () const
bool isSubroutineType () const
bool isBasicType () const
bool isVariable () const
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
bool isCompileUnit () const
bool isNameSpace () const
bool isLexicalBlockFile () const
bool isLexicalBlock () const
bool isSubrange () const
bool isEnumerator () const
bool isType () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
bool isImportedEntity () const
bool isExpression () const
void print (raw_ostream &OS) const
void dump () const
void replaceAllUsesWith (LLVMContext &VMContext, DIDescriptor D)
Replace all uses of debug info referenced by this descriptor.
void replaceAllUsesWith (MDNode *D)
Friends
class DIDescriptor
Additional Inherited Members
Public Types inherited from llvm::DIDescriptor
enum {
FlagAccessibility = 1 << 0 | 1 << 1 , FlagPrivate = 1 , FlagProtected = 2 , FlagPublic = 3 ,
FlagFwdDecl = 1 << 2 , FlagAppleBlock = 1 << 3 , FlagBlockByrefStruct = 1 << 4 , FlagVirtual = 1 << 5 ,
FlagArtificial = 1 << 6 , FlagExplicit = 1 << 7 , FlagPrototyped = 1 << 8 , FlagObjcClassComplete = 1 << 9 ,
FlagObjectPointer = 1 << 10 , FlagVector = 1 << 11 , FlagStaticMember = 1 << 12 , FlagIndirectVariable = 1 << 13 ,
FlagLValueReference = 1 << 14 , FlagRValueReference = 1 << 15
}
Accessibility flags.
Protected Member Functions inherited from llvm::DIDescriptor
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy>
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
template<>
DITypeRef getFieldAs (unsigned Elt) const
Protected Attributes inherited from llvm::DIDescriptor
const MDNode * DbgNode
Detailed Description
This is a wrapper for a variable (e.g. parameter, local, global etc).
Definition at line 792 of file DebugInfo.h.
Constructor & Destructor Documentation
DIVariable()
llvm::DIVariable::DIVariable (const MDNode * N = nullptr) inline explicit
Definition at line 797 of file DebugInfo.h.
References DIDescriptor, and N.
Member Function Documentation
getArgNumber()
unsigned llvm::DIVariable::getArgNumber () const inline
Definition at line 804 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
Referenced by llvm::DwarfFile::addScopeVariable().
getContext()
DIScope llvm::DIVariable::getContext () const inline
Definition at line 806 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::endFunction(), and isInlinedFnArgument().
getFile()
DIFile llvm::DIVariable::getFile () const inline
Definition at line 807 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
getInlinedAt()
MDNode * DIVariable::getInlinedAt () const
If this variable is inlined then return inline location.
Definition at line 126 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, DIVariableInlinedAtIndex, and getNodeField().
Referenced by llvm::MachineInstr::print(), printExtendedName(), and Verify().
getLineNumber()
unsigned llvm::DIVariable::getLineNumber () const inline
Definition at line 800 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderFieldAs().
Referenced by llvm::MachineInstr::print(), and printExtendedName().
getName()
StringRef llvm::DIVariable::getName () const inline
Definition at line 799 of file DebugInfo.h.
References llvm::DIDescriptor::getHeaderField().
Referenced by llvm::MachineInstr::print(), and printExtendedName().
getSizeInBits()
unsigned DIVariable::getSizeInBits (const DITypeIdentifierMap & Map)
Return the size reported by the variable's type.
Definition at line 131 of file DebugInfo.cpp.
References llvm::DIType::getSizeInBits(), getType(), llvm::DIDerivedType::getTypeDerivedFrom(), llvm::DIDescriptor::isDerivedType(), and llvm::DIRef< T >::resolve().
Referenced by llvm::DwarfDebug::emitLocPieces().
getType()
DITypeRef llvm::DIVariable::getType () const inline
Definition at line 808 of file DebugInfo.h.
References llvm::DIDescriptor::getFieldAs().
Referenced by llvm::DwarfDebug::emitDebugLocValue(), getSizeInBits(), and isBlockByrefVariable().
isArtificial()
bool llvm::DIVariable::isArtificial () const inline
Return true if this variable is marked as "artificial".
Definition at line 811 of file DebugInfo.h.
References llvm::DIDescriptor::FlagArtificial, and llvm::DIDescriptor::getHeaderFieldAs().
isBlockByrefVariable()
bool llvm::DIVariable::isBlockByrefVariable (const DITypeIdentifierMap & Map) const inline
Check if this is a "__block" variable (Apple Blocks).
Definition at line 830 of file DebugInfo.h.
References getType().
isIndirect()
bool llvm::DIVariable::isIndirect () const inline
Return true if this variable is represented as a pointer.
Definition at line 820 of file DebugInfo.h.
References llvm::DIDescriptor::FlagIndirectVariable, and llvm::DIDescriptor::getHeaderFieldAs().
Referenced by llvm::DwarfCompileUnit::addComplexAddress(), llvm::DwarfCompileUnit::addVariableAddress(), llvm::DwarfDebug::emitDebugLocValue(), and llvm::DwarfDebug::emitLocPieces().
isInlinedFnArgument()
bool DIVariable::isInlinedFnArgument (const Function * CurFn)
Check if this is an inlined function argument.
Definition at line 701 of file DebugInfo.cpp.
References llvm::DISubprogram::describes(), getContext(), and llvm::DIDescriptor::isSubprogram().
isObjectPointer()
bool llvm::DIVariable::isObjectPointer () const inline
Definition at line 815 of file DebugInfo.h.
References llvm::DIDescriptor::FlagObjectPointer, and llvm::DIDescriptor::getHeaderFieldAs().
printExtendedName()
void DIVariable::printExtendedName (raw_ostream & OS) const
Definition at line 1433 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, llvm::StringRef::empty(), llvm::DebugLoc::getFromDILocation(), getInlinedAt(), getLineNumber(), getName(), llvm::DebugLoc::isUnknown(), and printDebugLoc().
Verify()
bool DIVariable::Verify () const
Definition at line 565 of file DebugInfo.cpp.
References llvm::DIDescriptor::DbgNode, fieldIsMDNode(), fieldIsTypeRef(), getInlinedAt(), llvm::DIDescriptor::getNumHeaderFields(), and llvm::DIDescriptor::isVariable().
Referenced by llvm::cleanseInlinedVariable(), llvm::createInlinedVariable(), llvm::MachineInstr::getDebugVariable(), and llvm::DIDescriptor::Verify().
Friends And Related Symbol Documentation
DIDescriptor
friend class DIDescriptor friend
Definition at line 793 of file DebugInfo.h.
References DIDescriptor.
Referenced by DIDescriptor, and DIVariable().
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp