LLVM: llvm::SCEV Class Reference
LLVM API Documentation
llvm::SCEV Class Reference
#include <ScalarEvolution.h>
Public Types
enum NoWrapFlags {
FlagAnyWrap = 0 , FlagNW = (1 << 0) , FlagNUW = (1 << 1) , FlagNSW = (1 << 2) ,
NoWrapMask = (1 << 3) -1
}
Public Member Functions
SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy)
unsigned getSCEVType () const
Type * getType () const
bool isZero () const
bool isOne () const
bool isAllOnesValue () const
bool isNonConstantNegative () const
void print (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Protected Attributes
unsigned short SubclassData
Friends
struct FoldingSetTrait< SCEV >
Detailed Description
SCEV - This class represents an analyzed expression in the program. These are opaque objects that the client is not allowed to do much with directly.
Definition at line 58 of file ScalarEvolution.h.
Member Enumeration Documentation
NoWrapFlags
enum llvm::SCEV::NoWrapFlags
NoWrapFlags are bitfield indices into SubclassData.
Add and Mul expressions may have no-unsigned-wrap <NUW> or no-signed-wrap <NSW> properties, which are derived from the IR operator. NSW is a misnomer that we use to mean no signed overflow or underflow.
AddRec expression may have a no-self-wraparound <NW> property if the result can never reach the start value. This property is independent of the actual start value and step direction. Self-wraparound is defined purely in terms of the recurrence's loop, step size, and bitwidth. Formally, a recurrence with no self-wraparound satisfies: abs(step) * max-iteration(loop) <= unsigned-max(bitwidth).
Note that NUW and NSW are also valid properties of a recurrence, and either implies NW. For convenience, NW will be set for a recurrence whenever either NUW or NSW are set.
Enumerator
FlagAnyWrap
FlagNW
FlagNUW
FlagNSW
NoWrapMask
Definition at line 95 of file ScalarEvolution.h.
Constructor & Destructor Documentation
SCEV()
llvm::SCEV::SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy) inline explicit
Definition at line 101 of file ScalarEvolution.h.
References SubclassData.
Member Function Documentation
dump()
void SCEV::dump () const
dump - This method is used for debugging.
Definition at line 136 of file ScalarEvolution.cpp.
References llvm::dbgs(), and print().
getSCEVType()
unsigned llvm::SCEV::getSCEVType () const inline
Definition at line 104 of file ScalarEvolution.h.
Referenced by llvm::SCEVAddExpr::classof(), llvm::SCEVAddRecExpr::classof(), llvm::SCEVCastExpr::classof(), llvm::SCEVCommutativeExpr::classof(), llvm::SCEVConstant::classof(), llvm::SCEVCouldNotCompute::classof(), llvm::SCEVMulExpr::classof(), llvm::SCEVNAryExpr::classof(), llvm::SCEVSignExtendExpr::classof(), llvm::SCEVSMaxExpr::classof(), llvm::SCEVTruncateExpr::classof(), llvm::SCEVUDivExpr::classof(), llvm::SCEVUMaxExpr::classof(), llvm::SCEVUnknown::classof(), llvm::SCEVZeroExtendExpr::classof(), getExprBase(), getType(), GroupByComplexity(), isHighCostExpansion(), print(), llvm::SCEVVisitor< SC, RetVal >::visit(), and llvm::SCEVTraversal< SV >::visitAll().
getType()
Type * SCEV::getType () const
getType - Return the LLVM type of this SCEV expression.
Definition at line 252 of file ScalarEvolution.cpp.
References llvm::cast(), getSCEVType(), llvm_unreachable, llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scCouldNotCompute, llvm::scMulExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUnknown, and llvm::scZeroExtend.
Referenced by BinomialCoefficient(), BuildConstantFromSCEV(), DoInitialMatch(), FactorOutConstant(), FindLoopCounter(), genLoopLimit(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAnyExtendExpr(), getExactSDiv(), llvm::ScalarEvolution::getMinusSCEV(), getNewAlignment(), getOverflowLimitForStep(), llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), llvm::ScalarEvolution::getTruncateExpr(), llvm::SCEVAddExpr::getType(), llvm::SCEVNAryExpr::getType(), llvm::SCEVUDivExpr::getType(), llvm::ScalarEvolution::getUDivExpr(), llvm::ScalarEvolution::getUMaxFromMismatchedTypes(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), llvm::ScalarEvolution::getUnsignedRange(), llvm::ScalarEvolution::getZeroExtendExpr(), isHighCostExpansion(), print(), llvm::ScalarEvolution::SimplifyICmpOperands(), and llvm::UnrollRuntimeLoopProlog().
isAllOnesValue()
bool SCEV::isAllOnesValue () const
isAllOnesValue - Return true if the expression is a constant all-ones value.
Definition at line 289 of file ScalarEvolution.cpp.
References llvm::dyn_cast().
isNonConstantNegative()
bool SCEV::isNonConstantNegative () const
isNonConstantNegative - Return true if the specified scev is negated, but not a constant.
Definition at line 297 of file ScalarEvolution.cpp.
References llvm::dyn_cast(), and llvm::SCEVNAryExpr::getOperand().
isOne()
bool SCEV::isOne () const
isOne - Return true if the expression is a constant one.
Definition at line 283 of file ScalarEvolution.cpp.
References llvm::dyn_cast().
Referenced by FindLoopCounter(), and genLoopLimit().
isZero()
bool SCEV::isZero () const
isZero - Return true if the expression is a constant zero.
Definition at line 277 of file ScalarEvolution.cpp.
References llvm::dyn_cast().
Referenced by canExpandBackedgeTakenCount(), CollectSubexprs(), FactorOutConstant(), findArrayDimensionsRec(), FindLoopCounter(), genLoopLimit(), isAlwaysFoldable(), SimplifyAddOperands(), and SplitAddRecs().
print()
void SCEV::print (raw_ostream & OS) const
print - Print out the internal representation of this scalar to the specified stream. This should really only be used for debugging purposes.
Definition at line 142 of file ScalarEvolution.cpp.
References llvm::cast(), FlagNSW, FlagNUW, FlagNW, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::SCEVUDivExpr::getLHS(), llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVCastExpr::getOperand(), llvm::SCEVNAryExpr::getOperand(), llvm::SCEVUDivExpr::getRHS(), getSCEVType(), getType(), llvm::SCEVCastExpr::getType(), I, llvm_unreachable, llvm::SCEVNAryExpr::op_begin(), llvm::SCEVNAryExpr::op_end(), llvm::Value::printAsOperand(), llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scCouldNotCompute, llvm::scMulExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUnknown, and llvm::scZeroExtend.
Referenced by dump(), FoldingSetTrait< SCEV >, getLoopBackedgeTakenCounts(), and llvm::ScalarEvolution::print().
Friends And Related Symbol Documentation
FoldingSetTrait< SCEV >
friend struct FoldingSetTrait< SCEV > friend
Definition at line 154 of file ScalarEvolution.h.
References print().
Member Data Documentation
SubclassData
unsigned short llvm::SCEV::SubclassData protected
SubclassData - This field is initialized to zero and may be used in subclasses to store miscellaneous information.
Definition at line 71 of file ScalarEvolution.h.
Referenced by llvm::SCEVNAryExpr::getNoWrapFlags(), SCEV(), llvm::SCEVAddRecExpr::setNoWrapFlags(), and llvm::SCEVCommutativeExpr::setNoWrapFlags().
The documentation for this class was generated from the following files:
ScalarEvolution.h
ScalarEvolution.cpp