LLVM: llvm::FPTruncInst Class Reference
LLVM API Documentation
llvm::FPTruncInst Class Reference
This class represents a truncation of floating point types.
#include <Instructions.h>
Public Member Functions
FPTruncInst (Value *S, Type *Ty, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Constructor with insert-before-instruction semantics.
FPTruncInst (Value *S, Type *Ty, const Twine &NameStr, BasicBlock *InsertAtEnd)
Constructor with insert-before-instruction semantics.
Public Member Functions inherited from llvm::CastInst
bool isIntegerCast () const
Determine if this is an integer-only cast.
bool isLosslessCast () const
Determine if this is a lossless cast.
bool isNoopCast (Type *IntPtrTy) const
Determine if this cast is a no-op cast.
bool isNoopCast (const DataLayout *DL) const
Determine if this cast is a no-op cast.
Instruction::CastOps getOpcode () const
Return the opcode of this CastInst.
Type * getSrcTy () const
Return the source type, as a convenience.
Type * getDestTy () const
Return the destination type, as a convenience.
Public Member Functions inherited from llvm::UnaryInstruction
void * operator new (size_t s)
~UnaryInstruction ()
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Public Member Functions inherited from llvm::Instruction
~Instruction ()
Instruction * user_back ()
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const DataLayout * getDataLayout () const
void removeFromParent ()
void eraseFromParent ()
void insertBefore (Instruction *InsertPos)
void insertAfter (Instruction *InsertPos)
void moveBefore (Instruction *MovePos)
unsigned getOpcode () const
getOpcode() returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isBinaryOp () const
bool isShift ()
bool isCast () const
bool isLogicalShift () const
bool isArithmeticShift () const
isArithmeticShift - Return true if this is an arithmetic shift right.
bool hasMetadata () const
bool hasMetadataOtherThanDebugLoc () const
MDNode * getMetadata (unsigned KindID) const
MDNode * getMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void getAAMetadata (AAMDNodes &N, bool Merge=false) const
void setMetadata (unsigned KindID, MDNode *Node)
void setMetadata (StringRef Kind, MDNode *Node)
void dropUnknownMetadata (ArrayRef< unsigned > KnownIDs)
Drop unknown metadata. Passes are required to drop metadata they don't understand. This is a convenience method for passes to do so.
void dropUnknownMetadata ()
void dropUnknownMetadata (unsigned ID1)
void dropUnknownMetadata (unsigned ID1, unsigned ID2)
void setAAMetadata (const AAMDNodes &N)
void setDebugLoc (const DebugLoc &Loc)
setDebugLoc - Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
getDebugLoc - Return the debug location for this node as a DebugLoc.
void setHasUnsafeAlgebra (bool B)
void setHasNoNaNs (bool B)
void setHasNoInfs (bool B)
void setHasNoSignedZeros (bool B)
void setHasAllowReciprocal (bool B)
void setFastMathFlags (FastMathFlags FMF)
void copyFastMathFlags (FastMathFlags FMF)
bool hasUnsafeAlgebra () const
Determine whether the unsafe-algebra flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
FastMathFlags getFastMathFlags () const
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool isAtomic () const
bool mayThrow () const
bool mayReturn () const
bool mayHaveSideEffects () const
Instruction * clone () const
bool isIdenticalTo (const Instruction *I) const
bool isIdenticalToWhenDefined (const Instruction *I) const
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
Determine if one instruction is the same operation as another.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *, unsigned)
Placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
Placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O) const
Implement operator<< on Value.
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
void intersectOptionalDataWith (const Value *V)
Clear any optional flags not set in the given Value.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
Value * stripPointerCasts ()
Strip off pointer casts, all-zero GEPs, and aliases.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strip off pointer casts and all-zero GEPs.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strip off pointer casts and all-constant inbounds GEPs.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Accumulate offsets from stripInBoundsConstantOffsets().
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strip off pointer casts and inbounds GEPs.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer (const DataLayout *DL=nullptr) const
Check if this is always a dereferenceable pointer.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
Translate PHI node to its predecessor from the given basic block.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare>
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
Public Member Functions inherited from llvm::ilist_node< Instruction >
Instruction * getPrevNode ()
Get the previous node, or 0 for the list head.
Instruction * getNextNode ()
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::CastInst
static CastInst * Create (Instruction::CastOps, Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Construct any of the CastInst subclasses.
static CastInst * Create (Instruction::CastOps, Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Construct any of the CastInst subclasses.
static CastInst * CreateZExtOrBitCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a ZExt or BitCast cast instruction.
static CastInst * CreateZExtOrBitCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a ZExt or BitCast cast instruction.
static CastInst * CreateSExtOrBitCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a SExt or BitCast cast instruction.
static CastInst * CreateSExtOrBitCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a SExt or BitCast cast instruction.
static CastInst * CreatePointerCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a BitCast AddrSpaceCast, or a PtrToInt cast instruction.
static CastInst * CreatePointerCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a BitCast, AddrSpaceCast or a PtrToInt cast instruction.
static CastInst * CreatePointerBitCastOrAddrSpaceCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a BitCast or an AddrSpaceCast cast instruction.
static CastInst * CreatePointerBitCastOrAddrSpaceCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=0)
Create a BitCast or an AddrSpaceCast cast instruction.
static CastInst * CreateBitOrPointerCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=0)
Create a BitCast, a PtrToInt, or an IntToPTr cast instruction.
static CastInst * CreateIntegerCast (Value *S, Type *Ty, bool isSigned, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a ZExt, BitCast, or Trunc for int -> int casts.
static CastInst * CreateIntegerCast (Value *S, Type *Ty, bool isSigned, const Twine &Name, BasicBlock *InsertAtEnd)
Create a ZExt, BitCast, or Trunc for int -> int casts.
static CastInst * CreateFPCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create an FPExt, BitCast, or FPTrunc for fp -> fp casts.
static CastInst * CreateFPCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create an FPExt, BitCast, or FPTrunc for fp -> fp casts.
static CastInst * CreateTruncOrBitCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a Trunc or BitCast cast instruction.
static CastInst * CreateTruncOrBitCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a Trunc or BitCast cast instruction.
static bool isCastable (Type *SrcTy, Type *DestTy)
Check whether it is valid to call getCastOpcode for these types.
static bool isBitCastable (Type *SrcTy, Type *DestTy)
Check whether a bitcast between these types is valid.
static bool isBitOrNoopPointerCastable (Type *SrcTy, Type *DestTy, const DataLayout *Layout=0)
Check whether a bitcast, inttoptr, or ptrtoint cast between these types is valid and a no-op.
static Instruction::CastOps getCastOpcode (const Value *Val, bool SrcIsSigned, Type *Ty, bool DstIsSigned)
Infer the opcode for cast operand and type.
static bool isNoopCast (Instruction::CastOps Opcode, Type *SrcTy, Type *DstTy, Type *IntPtrTy)
Determine if the described cast is a no-op cast.
static unsigned isEliminableCastPair (Instruction::CastOps firstOpcode, Instruction::CastOps secondOpcode, Type *SrcTy, Type *MidTy, Type *DstTy, Type *SrcIntPtrTy, Type *MidIntPtrTy, Type *DstIntPtrTy)
Determine if a cast pair is eliminable.
static bool castIsValid (Instruction::CastOps op, Value *S, Type *DstTy)
Determine if a cast is valid without creating one.
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::UnaryInstruction
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isBinaryOp (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isAssociative (unsigned op)
static bool isCommutative (unsigned op)
static bool isIdempotent (unsigned op)
static bool isNilpotent (unsigned op)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
FPTruncInst * clone_impl () const override
Clone an identical FPTruncInst.
Protected Member Functions inherited from llvm::CastInst
CastInst (Type *Ty, unsigned iType, Value *S, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Constructor with insert-before-instruction semantics for subclasses.
CastInst (Type *Ty, unsigned iType, Value *S, const Twine &NameStr, BasicBlock *InsertAtEnd)
Constructor with insert-at-end-of-block semantics for subclasses.
Protected Member Functions inherited from llvm::UnaryInstruction
UnaryInstruction (Type *Ty, unsigned iType, Value *V, Instruction *IB=nullptr)
UnaryInstruction (Type *Ty, unsigned iType, Value *V, BasicBlock *IAE)
Protected Member Functions inherited from llvm::Instruction
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< Instruction >
ilist_node ()
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0 , CompareUsingScalarTypes = 1<<1 }
enum TermOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum OtherOps
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
typedef iterator_range< op_iterator > op_range
typedef iterator_range< const_op_iterator > const_op_range
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal , BasicBlockVal , FunctionVal , GlobalAliasVal ,
GlobalVariableVal , UndefValueVal , BlockAddressVal , ConstantExprVal ,
ConstantAggregateZeroVal , ConstantDataArrayVal , ConstantDataVectorVal , ConstantIntVal ,
ConstantFPVal , ConstantArrayVal , ConstantStructVal , ConstantVectorVal ,
ConstantPointerNullVal , MetadataAsValueVal , InlineAsmVal , InstructionVal ,
ConstantFirstVal = FunctionVal , ConstantLastVal = ConstantPointerNullVal
}
Concrete subclass of this.
typedef use_iterator_impl< Use > use_iterator
typedef use_iterator_impl< const Use > const_use_iterator
typedef user_iterator_impl< User > user_iterator
typedef user_iterator_impl< const User > const_user_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
The maximum alignment for instructions.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U>
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
This is a pointer to the array of Uses for this User.
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumOperands
The number of operands in the subclass.
Detailed Description
This class represents a truncation of floating point types.
Definition at line 3439 of file Instructions.h.
Constructor & Destructor Documentation
FPTruncInst() [1/2]
FPTruncInst::FPTruncInst (Value * S, Type * Ty, const Twine & NameStr = "", Instruction * InsertBefore = nullptr)
Constructor with insert-before-instruction semantics.
Parameters
S The value to be truncated
Ty The type to truncate to
NameStr A name for the new instruction
InsertBefore Where to insert the new instruction
Definition at line 3004 of file Instructions.cpp.
References llvm::CastInst::CastInst(), llvm::CastInst::castIsValid(), llvm::CastInst::getOpcode(), and Name.
Referenced by clone_impl().
FPTruncInst() [2/2]
FPTruncInst::FPTruncInst (Value * S, Type * Ty, const Twine & NameStr, BasicBlock * InsertAtEnd)
Constructor with insert-before-instruction semantics.
Parameters
S The value to be truncated
Ty The type to truncate to
NameStr A name for the new instruction
InsertAtEnd The block to insert the instruction into
Definition at line 3010 of file Instructions.cpp.
References llvm::CastInst::CastInst(), llvm::CastInst::castIsValid(), llvm::CastInst::getOpcode(), and Name.
Member Function Documentation
classof() [1/2]
bool llvm::FPTruncInst::classof (const Instruction * I) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 3462 of file Instructions.h.
References I.
Referenced by classof().
classof() [2/2]
bool llvm::FPTruncInst::classof (const Value * V) inline static
Definition at line 3465 of file Instructions.h.
References llvm::cast(), classof(), and llvm::isa().
clone_impl()
FPTruncInst * FPTruncInst::clone_impl () const override protected virtual
Clone an identical FPTruncInst.
Implements llvm::Instruction.
Definition at line 3709 of file Instructions.cpp.
References FPTruncInst(), llvm::User::getOperand(), and llvm::Value::getType().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp