LLVM: llvm::StringRecTy Class Reference
LLVM API Documentation
llvm::StringRecTy Class Reference
#include <Record.h>
Public Member Functions
Init * convertValue (UnsetInit *UI) override
Init * convertValue (BitInit *BI) override
Init * convertValue (BitsInit *BI) override
Init * convertValue (IntInit *II) override
Init * convertValue (StringInit *SI) override
Init * convertValue (ListInit *LI) override
Init * convertValue (UnOpInit *BO) override
Init * convertValue (BinOpInit *BO) override
Init * convertValue (TernOpInit *BO) override
Init * convertValue (VarBitInit *VB) override
Init * convertValue (DefInit *DI) override
Init * convertValue (DagInit *DI) override
Init * convertValue (TypedInit *TI) override
Init * convertValue (VarInit *VI) override
Init * convertValue (FieldInit *FI) override
std::string getAsString () const override
bool typeIsConvertibleTo (const RecTy *RHS) const override
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
virtual bool baseClassOf (const RecTy *) const
Static Public Member Functions
static bool classof (const RecTy *RT)
static StringRecTy * get ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind , BitsRecTyKind , IntRecTyKind , StringRecTyKind ,
ListRecTyKind , DagRecTyKind , RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
StringRecTy - 'string' - Represent an string value
Definition at line 256 of file Record.h.
Member Function Documentation
classof()
bool llvm::StringRecTy::classof (const RecTy * RT) inline static
Definition at line 261 of file Record.h.
References llvm::RecTy::getRecTyKind(), llvm::RecTy::RecTy(), and llvm::RecTy::StringRecTyKind.
convertValue() [1/15]
Init * StringRecTy::convertValue (BinOpInit * BO) override virtual
Reimplemented from llvm::RecTy.
Definition at line 263 of file Record.cpp.
References llvm::Init::convertInitializerTo(), convertValue(), llvm::BinOpInit::get(), llvm::BinOpInit::getLHS(), llvm::BinOpInit::getOpcode(), llvm::BinOpInit::getRHS(), and llvm::BinOpInit::STRCONCAT.
convertValue() [2/15]
Init * llvm::StringRecTy::convertValue (BitInit * BI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 268 of file Record.h.
convertValue() [3/15]
Init * llvm::StringRecTy::convertValue (BitsInit * BI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 269 of file Record.h.
convertValue() [4/15]
Init * llvm::StringRecTy::convertValue (DagInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 279 of file Record.h.
convertValue() [5/15]
Init * llvm::StringRecTy::convertValue (DefInit * DI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 278 of file Record.h.
convertValue() [6/15]
Init * llvm::StringRecTy::convertValue (FieldInit * FI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 282 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [7/15]
Init * llvm::StringRecTy::convertValue (IntInit * II) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 270 of file Record.h.
convertValue() [8/15]
Init * llvm::StringRecTy::convertValue (ListInit * LI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 272 of file Record.h.
convertValue() [9/15]
Init * llvm::StringRecTy::convertValue (StringInit * SI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 271 of file Record.h.
convertValue() [10/15]
Init * llvm::StringRecTy::convertValue (TernOpInit * BO) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 275 of file Record.h.
References llvm::RecTy::convertValue().
convertValue() [11/15]
Init * StringRecTy::convertValue (TypedInit * TI) override virtual
Reimplemented from llvm::RecTy.
Definition at line 277 of file Record.cpp.
References llvm::TypedInit::getType(), and llvm::isa().
convertValue() [12/15]
Init * StringRecTy::convertValue (UnOpInit * BO) override virtual
Reimplemented from llvm::RecTy.
Definition at line 251 of file Record.cpp.
References llvm::UnOpInit::CAST, llvm::Init::convertInitializerTo(), convertValue(), llvm::UnOpInit::get(), llvm::UnOpInit::getOpcode(), and llvm::UnOpInit::getOperand().
convertValue() [13/15]
Init * llvm::StringRecTy::convertValue (UnsetInit * UI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 267 of file Record.h.
Referenced by convertValue(), and convertValue().
convertValue() [14/15]
Init * llvm::StringRecTy::convertValue (VarBitInit * VB) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 277 of file Record.h.
convertValue() [15/15]
Init * llvm::StringRecTy::convertValue (VarInit * VI) inline override virtual
Reimplemented from llvm::RecTy.
Definition at line 281 of file Record.h.
References llvm::RecTy::convertValue(), and VI.
get()
StringRecTy * llvm::StringRecTy::get () inline static
Definition at line 265 of file Record.h.
getAsString()
std::string llvm::StringRecTy::getAsString () const inline override virtual
Implements llvm::RecTy.
Definition at line 284 of file Record.h.
typeIsConvertibleTo()
bool llvm::StringRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline override virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 286 of file Record.h.
References llvm::RecTy::baseClassOf(), and llvm::RecTy::RecTy().
The documentation for this class was generated from the following files:
Record.h
Record.cpp