LLVM: llvm::AllocaHolder Class Reference
LLVM API Documentation
llvm::AllocaHolder Class Reference
#include <Interpreter.h>
Public Member Functions
AllocaHolder ()
AllocaHolder (AllocaHolder &&RHS)
AllocaHolder & operator= (AllocaHolder &&RHS)
~AllocaHolder ()
void add (void *Mem)
Detailed Description
Definition at line 39 of file lib/ExecutionEngine/Interpreter/Interpreter.h.
Constructor & Destructor Documentation
AllocaHolder() [1/2]
llvm::AllocaHolder::AllocaHolder () inline
Definition at line 43 of file lib/ExecutionEngine/Interpreter/Interpreter.h.
Referenced by AllocaHolder(), and operator=().
AllocaHolder() [2/2]
llvm::AllocaHolder::AllocaHolder (AllocaHolder && RHS) inline
Definition at line 46 of file lib/ExecutionEngine/Interpreter/Interpreter.h.
References AllocaHolder().
~AllocaHolder()
llvm::AllocaHolder::~AllocaHolder () inline
Definition at line 52 of file lib/ExecutionEngine/Interpreter/Interpreter.h.
References Allocation.
Member Function Documentation
add()
void llvm::AllocaHolder::add (void * Mem) inline
Definition at line 57 of file lib/ExecutionEngine/Interpreter/Interpreter.h.
operator=()
AllocaHolder & llvm::AllocaHolder::operator= (AllocaHolder && RHS) inline
Definition at line 47 of file lib/ExecutionEngine/Interpreter/Interpreter.h.
References AllocaHolder().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Interpreter/Interpreter.h