LLVM: llvm::MachineFrameInfo Class Reference
LLVM API Documentation
llvm::MachineFrameInfo Class Reference
Abstract Stack Frame Information.
#include <MachineFrameInfo.h>
Public Member Functions
MachineFrameInfo (unsigned StackAlign, bool isStackRealign, bool RealignOpt)
bool hasStackObjects () const
bool hasVarSizedObjects () const
int getStackProtectorIndex () const
void setStackProtectorIndex (int I)
int getFunctionContextIndex () const
void setFunctionContextIndex (int I)
bool isFrameAddressTaken () const
void setFrameAddressIsTaken (bool T)
bool isReturnAddressTaken () const
void setReturnAddressIsTaken (bool s)
bool hasStackMap () const
void setHasStackMap (bool s=true)
bool hasPatchPoint () const
void setHasPatchPoint (bool s=true)
int getObjectIndexBegin () const
int getObjectIndexEnd () const
unsigned getNumFixedObjects () const
getNumFixedObjects - Return the number of fixed objects.
unsigned getNumObjects () const
void mapLocalFrameObject (int ObjectIndex, int64_t Offset)
mapLocalFrameObject - Map a frame index into the local object block
std::pair< int, int64_t > getLocalFrameObjectMap (int i)
getLocalFrameObjectMap - Get the local offset mapping for a for an object
int64_t getLocalFrameObjectCount ()
void setLocalFrameSize (int64_t sz)
setLocalFrameSize - Set the size of the local object blob.
int64_t getLocalFrameSize () const
getLocalFrameSize - Get the size of the local object blob.
void setLocalFrameMaxAlign (unsigned Align)
unsigned getLocalFrameMaxAlign () const
bool getUseLocalStackAllocationBlock ()
void setUseLocalStackAllocationBlock (bool v)
bool isObjectPreAllocated (int ObjectIdx) const
int64_t getObjectSize (int ObjectIdx) const
void setObjectSize (int ObjectIdx, int64_t Size)
setObjectSize - Change the size of the specified stack object.
unsigned getObjectAlignment (int ObjectIdx) const
getObjectAlignment - Return the alignment of the specified stack object.
void setObjectAlignment (int ObjectIdx, unsigned Align)
setObjectAlignment - Change the alignment of the specified stack object.
const AllocaInst * getObjectAllocation (int ObjectIdx) const
int64_t getObjectOffset (int ObjectIdx) const
void setObjectOffset (int ObjectIdx, int64_t SPOffset)
uint64_t getStackSize () const
void setStackSize (uint64_t Size)
unsigned estimateStackSize (const MachineFunction &MF) const
Estimate and return the size of the stack frame.
int getOffsetAdjustment () const
void setOffsetAdjustment (int Adj)
unsigned getMaxAlignment () const
void ensureMaxAlignment (unsigned Align)
bool adjustsStack () const
void setAdjustsStack (bool V)
bool hasCalls () const
hasCalls - Return true if the current function has any function calls.
void setHasCalls (bool V)
bool hasInlineAsmWithSPAdjust () const
Returns true if the function contains any stack-adjusting inline assembly.
void setHasInlineAsmWithSPAdjust (bool B)
bool hasVAStart () const
Returns true if the function calls the llvm.va_start intrinsic.
void setHasVAStart (bool B)
bool hasMustTailInVarArgFunc () const
Returns true if the function is variadic and contains a musttail call.
void setHasMustTailInVarArgFunc (bool B)
unsigned getMaxCallFrameSize () const
void setMaxCallFrameSize (unsigned S)
int CreateFixedObject (uint64_t Size, int64_t SPOffset, bool Immutable, bool isAliased=false)
int CreateFixedSpillStackObject (uint64_t Size, int64_t SPOffset)
int CreateFrameAllocation (uint64_t Size)
bool isFixedObjectIndex (int ObjectIdx) const
bool isAliasedObjectIndex (int ObjectIdx) const
bool isImmutableObjectIndex (int ObjectIdx) const
bool isSpillSlotObjectIndex (int ObjectIdx) const
bool isDeadObjectIndex (int ObjectIdx) const
int CreateStackObject (uint64_t Size, unsigned Alignment, bool isSS, const AllocaInst *Alloca=nullptr)
int CreateSpillStackObject (uint64_t Size, unsigned Alignment)
void RemoveStackObject (int ObjectIdx)
int CreateVariableSizedObject (unsigned Alignment, const AllocaInst *Alloca)
const std::vector< CalleeSavedInfo > & getCalleeSavedInfo () const
void setCalleeSavedInfo (const std::vector< CalleeSavedInfo > &CSI)
bool isCalleeSavedInfoValid () const
isCalleeSavedInfoValid - Has the callee saved info been calculated yet?
void setCalleeSavedInfoValid (bool v)
BitVector getPristineRegs (const MachineBasicBlock *MBB) const
void print (const MachineFunction &MF, raw_ostream &OS) const
void dump (const MachineFunction &MF) const
dump - Print the function to stderr.
Detailed Description
Abstract Stack Frame Information.
The MachineFrameInfo class represents an abstract stack frame until prolog/epilog code is inserted. This class is key to allowing stack frame representation optimizations, such as frame pointer elimination. It also allows more mundane (but still important) optimizations, such as reordering of abstract objects on the stack frame.
To support this, the class assigns unique integer identifiers to stack objects requested clients. These identifiers are negative integers for fixed stack objects (such as arguments passed on the stack) or nonnegative for objects that may be reordered. Instructions which refer to stack objects use a special MO_FrameIndex operand to represent these frame indexes.
Because this class keeps track of all references to the stack frame, it knows when a variable sized object is allocated on the stack. This is the sole condition which prevents frame pointer elimination, which is an important optimization on register-poor architectures. Because original variable sized alloca's in the source program are the only source of variable sized stack objects, it is safe to decide whether there will be any variable sized objects before all stack objects are known (for example, register allocator spill code never needs variable sized objects).
When prolog/epilog code emission is performed, the final stack frame is built and the machine instructions are modified to refer to the actual stack offsets of the object, eliminating all MO_FrameIndex operands from the program.
Definition at line 80 of file MachineFrameInfo.h.
Constructor & Destructor Documentation
MachineFrameInfo()
llvm::MachineFrameInfo::MachineFrameInfo (unsigned StackAlign, bool isStackRealign, bool RealignOpt) inline explicit
Definition at line 250 of file MachineFrameInfo.h.
Member Function Documentation
adjustsStack()
bool llvm::MachineFrameInfo::adjustsStack () const inline
AdjustsStack - Return true if this function adjusts the stack – e.g., when calling another function. This is only valid during and after prolog/epilog code insertion.
Definition at line 480 of file MachineFrameInfo.h.
Referenced by llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), estimateStackSize(), and llvm::MipsFrameLowering::estimateStackSize().
CreateFixedObject()
int MachineFrameInfo::CreateFixedObject (uint64_t Size, int64_t SPOffset, bool Immutable, bool isAliased = false)
CreateFixedObject - Create a new object at a fixed location on the stack. All fixed objects should be created before other objects are created for efficiency. By default, fixed objects are not pointed to by LLVM IR values. This returns an index with a negative value.
CreateFixedObject - Create a new object at a fixed location on the stack. All fixed objects should be created before other objects are created for efficiency. By default, fixed objects are immutable. This returns an index with a negative value.
Definition at line 559 of file MachineFunction.cpp.
References Align, clampStackAlignment(), and llvm::MinAlign().
Referenced by CalculateTailCallArgDest(), llvm::XCoreFunctionInfo::createLRSpillSlot(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::MSP430TargetLowering::getReturnAddressFrameIndex(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::MSP430FrameLowering::processFunctionBeforeFrameFinalized().
CreateFixedSpillStackObject()
int MachineFrameInfo::CreateFixedSpillStackObject (uint64_t Size, int64_t SPOffset)
CreateFixedSpillStackObject - Create a spill slot at a fixed location on the stack. Returns an index with a negative value.
Definition at line 577 of file MachineFunction.cpp.
References Align, clampStackAlignment(), and llvm::MinAlign().
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots().
CreateFrameAllocation()
int MachineFrameInfo::CreateFrameAllocation (uint64_t Size)
Allocates memory at a fixed, target-specific offset from the frame pointer. Marks the function as having its frame address taken.
Definition at line 590 of file MachineFunction.cpp.
References CreateStackObject(), llvm::RoundUpToAlignment(), and setFrameAddressIsTaken().
CreateSpillStackObject()
int MachineFrameInfo::CreateSpillStackObject (uint64_t Size, unsigned Alignment)
CreateSpillStackObject - Create a new statically sized stack object that represents a spill slot, returning a nonnegative identifier to represent it.
Definition at line 529 of file MachineFunction.cpp.
References clampStackAlignment(), CreateStackObject(), and ensureMaxAlignment().
CreateStackObject()
int MachineFrameInfo::CreateStackObject (uint64_t Size, unsigned Alignment, bool isSS, const AllocaInst * Alloca = nullptr)
CreateStackObject - Create a new statically sized stack object, returning a nonnegative identifier to represent it.
Definition at line 512 of file MachineFunction.cpp.
References clampStackAlignment(), and ensureMaxAlignment().
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::X86TargetLowering::BuildFILD(), llvm::XCoreFunctionInfo::createEHSpillSlot(), llvm::XCoreFunctionInfo::createFPSpillSlot(), CreateFrameAllocation(), llvm::XCoreFunctionInfo::createLRSpillSlot(), CreateSpillStackObject(), llvm::SelectionDAG::CreateStackTemporary(), llvm::SelectionDAG::CreateStackTemporary(), llvm::SparcTargetLowering::LowerCall_32(), llvm::TargetLowering::LowerCallTo(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::XCoreFrameLowering::processFunctionBeforeFrameFinalized().
CreateVariableSizedObject()
int MachineFrameInfo::CreateVariableSizedObject (unsigned Alignment, const AllocaInst * Alloca)
CreateVariableSizedObject - Notify the MachineFrameInfo object that a variable sized object has been created. This must be created whenever a variable sized object is created, whether or not the index returned is actually used.
Definition at line 544 of file MachineFunction.cpp.
References clampStackAlignment(), and ensureMaxAlignment().
dump()
void MachineFrameInfo::dump (const MachineFunction & MF) const
dump - Print the function to stderr.
Definition at line 714 of file MachineFunction.cpp.
References llvm::dbgs(), and print().
ensureMaxAlignment()
void MachineFrameInfo::ensureMaxAlignment (unsigned Align)
ensureMaxAlignment - Make sure the function is at least Align bytes aligned.
Definition at line 491 of file MachineFunction.cpp.
References Align.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), CreateSpillStackObject(), CreateStackObject(), CreateVariableSizedObject(), and setObjectAlignment().
estimateStackSize()
unsigned MachineFrameInfo::estimateStackSize (const MachineFunction & MF) const
Estimate and return the size of the stack frame.
Definition at line 628 of file MachineFunction.cpp.
References adjustsStack(), Align, llvm::TargetSubtargetInfo::getFrameLowering(), getMaxAlignment(), getMaxCallFrameSize(), getObjectAlignment(), getObjectIndexBegin(), getObjectIndexEnd(), getObjectOffset(), getObjectSize(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::getTransientStackAlignment(), llvm::TargetFrameLowering::hasReservedCallFrame(), hasVarSizedObjects(), isDeadObjectIndex(), and llvm::TargetRegisterInfo::needsStackRealignment().
Referenced by llvm::PPCFrameLowering::determineFrameLayout(), llvm::XCoreFunctionInfo::isLargeFrame(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized().
getCalleeSavedInfo()
const std::vector< CalleeSavedInfo > & llvm::MachineFrameInfo::getCalleeSavedInfo () const inline
getCalleeSavedInfo - Returns a reference to call saved info vector for the current function.
Definition at line 589 of file MachineFrameInfo.h.
Referenced by llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), getPristineRegs(), llvm::Mips16InstrInfo::makeFrame(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::Mips16InstrInfo::restoreFrame().
getFunctionContextIndex()
int llvm::MachineFrameInfo::getFunctionContextIndex () const inline
getFunctionContextIndex/setFunctionContextIndex - Return the index for the function context object. This object is used for SjLj exceptions.
Definition at line 293 of file MachineFrameInfo.h.
getLocalFrameMaxAlign()
unsigned llvm::MachineFrameInfo::getLocalFrameMaxAlign () const inline
getLocalFrameMaxAlign - Return the required alignment of the local object blob.
Definition at line 364 of file MachineFrameInfo.h.
Referenced by llvm::ARMBaseRegisterInfo::needsFrameBaseReg().
getLocalFrameObjectCount()
int64_t llvm::MachineFrameInfo::getLocalFrameObjectCount () inline
getLocalFrameObjectCount - Return the number of objects allocated into the local object block.
Definition at line 350 of file MachineFrameInfo.h.
getLocalFrameObjectMap()
std::pair< int, int64_t > llvm::MachineFrameInfo::getLocalFrameObjectMap (int i) inline
getLocalFrameObjectMap - Get the local offset mapping for a for an object
Definition at line 342 of file MachineFrameInfo.h.
getLocalFrameSize()
int64_t llvm::MachineFrameInfo::getLocalFrameSize () const inline
getLocalFrameSize - Get the size of the local object blob.
Definition at line 356 of file MachineFrameInfo.h.
Referenced by llvm::AArch64RegisterInfo::hasBasePointer(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), and llvm::ARMBaseRegisterInfo::needsFrameBaseReg().
getMaxAlignment()
unsigned llvm::MachineFrameInfo::getMaxAlignment () const inline
getMaxAlignment - Return the alignment in bytes that this function must be aligned to, which is greater than the default stack alignment provided by the target.
Definition at line 471 of file MachineFrameInfo.h.
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::PPCFrameLowering::determineFrameLayout(), emitAlignedDPRCS2Spills(), llvm::X86FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), estimateStackSize(), llvm::MipsFrameLowering::estimateStackSize(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::PPCRegisterInfo::needsStackRealignment(), and llvm::X86RegisterInfo::needsStackRealignment().
getMaxCallFrameSize()
unsigned llvm::MachineFrameInfo::getMaxCallFrameSize () const inline
getMaxCallFrameSize - Return the maximum size of a call frame that must be allocated for an outgoing function call. This is only available if CallFrameSetup/Destroy pseudo instructions are used by the target, and then only during or after prolog/epilog code insertion.
Definition at line 504 of file MachineFrameInfo.h.
Referenced by llvm::PPCFrameLowering::determineFrameLayout(), llvm::HexagonFrameLowering::emitPrologue(), estimateStackSize(), llvm::MipsFrameLowering::estimateStackSize(), llvm::ARMFrameLowering::hasReservedCallFrame(), llvm::Mips16FrameLowering::hasReservedCallFrame(), llvm::MipsSEFrameLowering::hasReservedCallFrame(), llvm::Thumb1FrameLowering::hasReservedCallFrame(), and llvm::PPCRegisterInfo::lowerDynamicAlloc().
getNumFixedObjects()
unsigned llvm::MachineFrameInfo::getNumFixedObjects () const inline
getNumFixedObjects - Return the number of fixed objects.
Definition at line 329 of file MachineFrameInfo.h.
getNumObjects()
unsigned llvm::MachineFrameInfo::getNumObjects () const inline
getNumObjects - Return the number of objects.
Definition at line 333 of file MachineFrameInfo.h.
Referenced by llvm::AMDGPUFrameLowering::getFrameIndexOffset(), llvm::AMDGPUInstrInfo::getIndirectIndexBegin(), and llvm::AMDGPUInstrInfo::getIndirectIndexEnd().
getObjectAlignment()
unsigned llvm::MachineFrameInfo::getObjectAlignment (int ObjectIdx) const inline
getObjectAlignment - Return the alignment of the specified stack object.
Definition at line 402 of file MachineFrameInfo.h.
Referenced by llvm::addFrameReference(), llvm::addFrameReference(), AdjustStackOffset(), AdjustStackOffset(), llvm::TargetLoweringBase::emitPatchPoint(), estimateStackSize(), estimateStackSize(), fixupFuncForFI(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::X86InstrInfo::foldMemoryOperandImpl(), getFrameIndexMMO(), llvm::AMDGPUFrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffset(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), llvm::MipsInstrInfo::GetMemOperand(), getMemsetStores(), llvm::SelectionDAG::InferPtrAlignment(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), and llvm::XCoreInstrInfo::storeRegToStackSlot().
getObjectAllocation()
const AllocaInst * llvm::MachineFrameInfo::getObjectAllocation (int ObjectIdx) const inline
getObjectAllocation - Return the underlying Alloca of the specified stack object if it exists. Returns 0 if none exists.
Definition at line 418 of file MachineFrameInfo.h.
getObjectIndexBegin()
int llvm::MachineFrameInfo::getObjectIndexBegin () const inline
getObjectIndexBegin - Return the minimum frame object index.
Definition at line 322 of file MachineFrameInfo.h.
Referenced by estimateStackSize(), estimateStackSize(), llvm::MipsFrameLowering::estimateStackSize(), llvm::AMDGPUFrameLowering::getFrameIndexOffset(), and llvm::MSP430FrameLowering::processFunctionBeforeFrameFinalized().
getObjectIndexEnd()
int llvm::MachineFrameInfo::getObjectIndexEnd () const inline
getObjectIndexEnd - Return one past the maximum frame object index.
Definition at line 326 of file MachineFrameInfo.h.
Referenced by estimateStackSize(), estimateStackSize(), and llvm::MipsFrameLowering::estimateStackSize().
getObjectOffset()
int64_t llvm::MachineFrameInfo::getObjectOffset (int ObjectIdx) const inline
getObjectOffset - Return the assigned stack offset of the specified object from the incoming stack pointer.
Definition at line 427 of file MachineFrameInfo.h.
References isDeadObjectIndex().
Referenced by llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::NVPTXRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::PPCFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::ARMFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), estimateStackSize(), estimateStackSize(), llvm::MipsFrameLowering::estimateStackSize(), llvm::TargetInstrInfo::foldMemoryOperand(), GetEHSpillList(), llvm::HexagonFrameLowering::getFrameIndexOffset(), llvm::SystemZFrameLowering::getFrameIndexOffset(), llvm::TargetFrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffsetFromSP(), llvm::SIMachineFunctionInfo::getSpilledReg(), GetSpillList(), llvm::SelectionDAG::isConsecutiveLoad(), isConsecutiveLSLoc(), MatchingStackOffset(), MatchingStackOffset(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
getObjectSize()
int64_t llvm::MachineFrameInfo::getObjectSize (int ObjectIdx) const inline
getObjectSize - Return the size of the specified object.
Definition at line 388 of file MachineFrameInfo.h.
Referenced by llvm::addFrameReference(), llvm::addFrameReference(), AdjustStackOffset(), AdjustStackOffset(), estimateStackSize(), estimateStackSize(), llvm::MipsFrameLowering::estimateStackSize(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), getFrameIndexMMO(), llvm::AMDGPUFrameLowering::getFrameIndexOffset(), llvm::MipsInstrInfo::GetMemOperand(), llvm::SelectionDAG::isConsecutiveLoad(), isConsecutiveLSLoc(), llvm::SystemZInstrInfo::isStackSlotCopy(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), MatchingStackOffset(), MatchingStackOffset(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), and llvm::XCoreInstrInfo::storeRegToStackSlot().
getOffsetAdjustment()
int llvm::MachineFrameInfo::getOffsetAdjustment () const inline
getOffsetAdjustment - Return the correction for frame offsets.
Definition at line 461 of file MachineFrameInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::getFrameIndexOffset(), and llvm::TargetFrameLowering::getFrameIndexOffset().
getPristineRegs()
BitVector MachineFrameInfo::getPristineRegs (const MachineBasicBlock * MBB) const
getPristineRegs - Return a set of physical registers that are pristine on entry to the MBB.
Pristine registers hold a value that is useless to the current function, but that must be preserved - they are callee saved registers that have not been saved yet.
Before the PrologueEpilogueInserter has placed the CSR spill code, this method always returns an empty set.
Definition at line 599 of file MachineFunction.cpp.
References llvm::MachineFunction::front(), getCalleeSavedInfo(), llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getTarget(), I, isCalleeSavedInfoValid(), llvm::BitVector::reset(), and llvm::BitVector::set().
Referenced by llvm::AggressiveAntiDepBreaker::StartBlock(), and llvm::CriticalAntiDepBreaker::StartBlock().
getStackProtectorIndex()
int llvm::MachineFrameInfo::getStackProtectorIndex () const inline
getStackProtectorIndex/setStackProtectorIndex - Return the index for the stack protector object.
Definition at line 288 of file MachineFrameInfo.h.
Referenced by llvm::SelectionDAGBuilder::visitSPDescriptorParent(), and WindowsRequiresStackProbe().
getStackSize()
uint64_t llvm::MachineFrameInfo::getStackSize () const inline
getStackSize - Return the number of bytes that must be allocated to hold all of the fixed size frame objects. This is only valid after Prolog/Epilog code insertion has finalized the stack frame layout.
Definition at line 450 of file MachineFrameInfo.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::MipsRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::getAllocatedStackSize(), llvm::TargetFrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexOffsetFromSP(), llvm::HexagonFrameLowering::hasFP(), llvm::PPCFrameLowering::hasFP(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), and llvm::PEI::runOnMachineFunction().
getUseLocalStackAllocationBlock()
bool llvm::MachineFrameInfo::getUseLocalStackAllocationBlock () inline
getUseLocalStackAllocationBlock - Get whether the local allocation blob should be allocated together or let PEI allocate the locals in it directly.
Definition at line 369 of file MachineFrameInfo.h.
hasCalls()
bool llvm::MachineFrameInfo::hasCalls () const inline
hasCalls - Return true if the current function has any function calls.
Definition at line 484 of file MachineFrameInfo.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::AArch64FrameLowering::canUseRedZone(), llvm::TargetOptions::DisableFramePointerElim(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::getAllocatedStackSize(), llvm::AArch64FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::HexagonFrameLowering::hasFP(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::SelectionDAGISel::runOnMachineFunction().
hasInlineAsmWithSPAdjust()
bool llvm::MachineFrameInfo::hasInlineAsmWithSPAdjust () const inline
Returns true if the function contains any stack-adjusting inline assembly.
Definition at line 488 of file MachineFrameInfo.h.
Referenced by llvm::X86RegisterInfo::hasBasePointer(), and llvm::X86FrameLowering::hasFP().
hasMustTailInVarArgFunc()
bool llvm::MachineFrameInfo::hasMustTailInVarArgFunc () const inline
Returns true if the function is variadic and contains a musttail call.
Definition at line 496 of file MachineFrameInfo.h.
hasPatchPoint()
bool llvm::MachineFrameInfo::hasPatchPoint () const inline
hasPatchPoint - This method may be called any time after instruction selection is complete to determine if there is a call to builtin @llvm.experimental.patchpoint.
Definition at line 317 of file MachineFrameInfo.h.
Referenced by llvm::AArch64FrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), and llvm::PPCFrameLowering::needsFP().
hasStackMap()
bool llvm::MachineFrameInfo::hasStackMap () const inline
hasStackMap - This method may be called any time after instruction selection is complete to determine if there is a call to builtin @llvm.experimental.stackmap.
Definition at line 311 of file MachineFrameInfo.h.
Referenced by llvm::AArch64FrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), and llvm::PPCFrameLowering::needsFP().
hasStackObjects()
bool llvm::MachineFrameInfo::hasStackObjects () const inline
hasStackObjects - Return true if there are any stack objects in this function.
Definition at line 277 of file MachineFrameInfo.h.
Referenced by llvm::NVPTXFrameLowering::emitPrologue(), and llvm::SIRegisterInfo::requiresRegisterScavenging().
hasVarSizedObjects()
bool llvm::MachineFrameInfo::hasVarSizedObjects () const inline
hasVarSizedObjects - This method may be called any time after instruction selection is complete to determine if the stack frame for this function contains any variable sized objects.
Definition at line 283 of file MachineFrameInfo.h.
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::X86RegisterInfo::canRealignStack(), llvm::ARMFrameLowering::canSimplifyCallFramePseudos(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), estimateStackSize(), llvm::SystemZFrameLowering::getAllocatedStackSize(), llvm::AMDGPUInstrInfo::getIndirectIndexEnd(), llvm::AArch64RegisterInfo::hasBasePointer(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::X86RegisterInfo::hasBasePointer(), llvm::AArch64FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::MipsFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::SystemZFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasReservedCallFrame(), llvm::ARMFrameLowering::hasReservedCallFrame(), llvm::Mips16FrameLowering::hasReservedCallFrame(), llvm::MipsSEFrameLowering::hasReservedCallFrame(), llvm::MSP430FrameLowering::hasReservedCallFrame(), llvm::SparcFrameLowering::hasReservedCallFrame(), llvm::Thumb1FrameLowering::hasReservedCallFrame(), llvm::X86FrameLowering::hasReservedCallFrame(), llvm::PPCFrameLowering::needsFP(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::AArch64FrameLowering::resolveFrameIndexReference(), and llvm::AArch64RegisterInfo::useFPForScavengingIndex().
hasVAStart()
bool llvm::MachineFrameInfo::hasVAStart () const inline
Returns true if the function calls the llvm.va_start intrinsic.
Definition at line 492 of file MachineFrameInfo.h.
isAliasedObjectIndex()
bool llvm::MachineFrameInfo::isAliasedObjectIndex (int ObjectIdx) const inline
isAliasedObjectIndex - Returns true if the specified index corresponds to an object that might be pointed to by an LLVM IR value.
Definition at line 531 of file MachineFrameInfo.h.
Referenced by llvm::FixedStackPseudoSourceValue::isAliased().
isCalleeSavedInfoValid()
bool llvm::MachineFrameInfo::isCalleeSavedInfoValid () const inline
isCalleeSavedInfoValid - Has the callee saved info been calculated yet?
Definition at line 600 of file MachineFrameInfo.h.
Referenced by getPristineRegs().
isDeadObjectIndex()
bool llvm::MachineFrameInfo::isDeadObjectIndex (int ObjectIdx) const inline
isDeadObjectIndex - Returns true if the specified index corresponds to a dead object.
Definition at line 555 of file MachineFrameInfo.h.
Referenced by estimateStackSize(), estimateStackSize(), getObjectOffset(), and setObjectOffset().
isFixedObjectIndex()
bool llvm::MachineFrameInfo::isFixedObjectIndex (int ObjectIdx) const inline
isFixedObjectIndex - Returns true if the specified index corresponds to a fixed stack object.
Definition at line 525 of file MachineFrameInfo.h.
Referenced by getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), LowerAsSplatVectorLoad(), MatchingStackOffset(), MatchingStackOffset(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
isFrameAddressTaken()
bool llvm::MachineFrameInfo::isFrameAddressTaken () const inline
isFrameAddressTaken - This method may be called any time after instruction selection is complete to determine if there is a call to @llvm.frameaddress in this function.
Definition at line 299 of file MachineFrameInfo.h.
Referenced by llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), llvm::PPCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::MipsFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), and llvm::X86FrameLowering::hasFP().
isImmutableObjectIndex()
bool llvm::MachineFrameInfo::isImmutableObjectIndex (int ObjectIdx) const inline
isImmutableObjectIndex - Returns true if the specified index corresponds to an immutable object.
Definition at line 539 of file MachineFrameInfo.h.
Referenced by llvm::FixedStackPseudoSourceValue::isConstant().
isObjectPreAllocated()
bool llvm::MachineFrameInfo::isObjectPreAllocated (int ObjectIdx) const inline
isObjectPreAllocated - Return true if the object was pre-allocated into the local block.
Definition at line 380 of file MachineFrameInfo.h.
isReturnAddressTaken()
bool llvm::MachineFrameInfo::isReturnAddressTaken () const inline
isReturnAddressTaken - This method may be called any time after instruction selection is complete to determine if there is a call to @llvm.returnaddress in this function.
Definition at line 305 of file MachineFrameInfo.h.
Referenced by llvm::Mips16FrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), and llvm::Thumb1FrameLowering::spillCalleeSavedRegisters().
isSpillSlotObjectIndex()
bool llvm::MachineFrameInfo::isSpillSlotObjectIndex (int ObjectIdx) const inline
isSpillSlotObjectIndex - Returns true if the specified index corresponds to a spill slot..
Definition at line 547 of file MachineFrameInfo.h.
Referenced by emitComments(), and llvm::FixedStackPseudoSourceValue::mayAlias().
mapLocalFrameObject()
void llvm::MachineFrameInfo::mapLocalFrameObject (int ObjectIndex, int64_t Offset) inline
mapLocalFrameObject - Map a frame index into the local object block
Definition at line 336 of file MachineFrameInfo.h.
print()
void MachineFrameInfo::print (const MachineFunction & MF, raw_ostream & OS) const
print - Used by the MachineFunction printer to print information about stack objects. Implemented in MachineFunction.cpp
Definition at line 677 of file MachineFunction.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), and llvm::MachineFunction::getSubtarget().
Referenced by dump().
RemoveStackObject()
void llvm::MachineFrameInfo::RemoveStackObject (int ObjectIdx) inline
RemoveStackObject - Remove or mark dead a statically sized stack object.
Definition at line 575 of file MachineFrameInfo.h.
setAdjustsStack()
void llvm::MachineFrameInfo::setAdjustsStack (bool V) inline
Definition at line 481 of file MachineFrameInfo.h.
Referenced by GetTLSADDR().
setCalleeSavedInfo()
void llvm::MachineFrameInfo::setCalleeSavedInfo (const std::vector< CalleeSavedInfo > & CSI) inline
setCalleeSavedInfo - Used by prolog/epilog inserter to set the function's callee saved information.
Definition at line 595 of file MachineFrameInfo.h.
setCalleeSavedInfoValid()
void llvm::MachineFrameInfo::setCalleeSavedInfoValid (bool v) inline
Definition at line 602 of file MachineFrameInfo.h.
setFrameAddressIsTaken()
void llvm::MachineFrameInfo::setFrameAddressIsTaken (bool T) inline
Definition at line 300 of file MachineFrameInfo.h.
References T.
Referenced by CreateFrameAllocation(), getFRAMEADDR(), llvm::HexagonTargetLowering::LowerFRAMEADDR(), llvm::MSP430TargetLowering::LowerFRAMEADDR(), and LowerVASTART().
setFunctionContextIndex()
void llvm::MachineFrameInfo::setFunctionContextIndex (int I) inline
Definition at line 294 of file MachineFrameInfo.h.
References I.
setHasCalls()
void llvm::MachineFrameInfo::setHasCalls (bool V) inline
Definition at line 485 of file MachineFrameInfo.h.
Referenced by GetTLSADDR(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::makeAddress(), and llvm::SelectionDAGISel::runOnMachineFunction().
setHasInlineAsmWithSPAdjust()
void llvm::MachineFrameInfo::setHasInlineAsmWithSPAdjust (bool B) inline
Definition at line 489 of file MachineFrameInfo.h.
setHasMustTailInVarArgFunc()
void llvm::MachineFrameInfo::setHasMustTailInVarArgFunc (bool B) inline
Definition at line 497 of file MachineFrameInfo.h.
setHasPatchPoint()
void llvm::MachineFrameInfo::setHasPatchPoint (bool s = true) inline
Definition at line 318 of file MachineFrameInfo.h.
setHasStackMap()
void llvm::MachineFrameInfo::setHasStackMap (bool s = true) inline
Definition at line 312 of file MachineFrameInfo.h.
setHasVAStart()
void llvm::MachineFrameInfo::setHasVAStart (bool B) inline
Definition at line 493 of file MachineFrameInfo.h.
setLocalFrameMaxAlign()
void llvm::MachineFrameInfo::setLocalFrameMaxAlign (unsigned Align) inline
setLocalFrameMaxAlign - Required alignment of the local object blob, which is the strictest alignment of any object in it.
Definition at line 360 of file MachineFrameInfo.h.
References Align.
setLocalFrameSize()
void llvm::MachineFrameInfo::setLocalFrameSize (int64_t sz) inline
setLocalFrameSize - Set the size of the local object blob.
Definition at line 353 of file MachineFrameInfo.h.
setMaxCallFrameSize()
void llvm::MachineFrameInfo::setMaxCallFrameSize (unsigned S) inline
Definition at line 505 of file MachineFrameInfo.h.
Referenced by llvm::PPCFrameLowering::determineFrameLayout().
setObjectAlignment()
void llvm::MachineFrameInfo::setObjectAlignment (int ObjectIdx, unsigned Align) inline
setObjectAlignment - Change the alignment of the specified stack object.
Definition at line 409 of file MachineFrameInfo.h.
References Align, and ensureMaxAlignment().
Referenced by emitAlignedDPRCS2Spills(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), and LowerAsSplatVectorLoad().
setObjectOffset()
void llvm::MachineFrameInfo::setObjectOffset (int ObjectIdx, int64_t SPOffset) inline
setObjectOffset - Set the stack frame offset of the specified object. The offset is relative to the stack pointer on entry to the function.
Definition at line 438 of file MachineFrameInfo.h.
References isDeadObjectIndex().
Referenced by AdjustStackOffset(), AdjustStackOffset(), and llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized().
setObjectSize()
void llvm::MachineFrameInfo::setObjectSize (int ObjectIdx, int64_t Size) inline
setObjectSize - Change the size of the specified stack object.
Definition at line 395 of file MachineFrameInfo.h.
setOffsetAdjustment()
void llvm::MachineFrameInfo::setOffsetAdjustment (int Adj) inline
setOffsetAdjustment - Set the correction for frame offsets.
Definition at line 465 of file MachineFrameInfo.h.
Referenced by llvm::ARMFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), and llvm::X86FrameLowering::emitPrologue().
setReturnAddressIsTaken()
void llvm::MachineFrameInfo::setReturnAddressIsTaken (bool s) inline
Definition at line 306 of file MachineFrameInfo.h.
Referenced by llvm::HexagonTargetLowering::LowerRETURNADDR(), llvm::MSP430TargetLowering::LowerRETURNADDR(), and LowerRETURNADDR().
setStackProtectorIndex()
void llvm::MachineFrameInfo::setStackProtectorIndex (int I) inline
Definition at line 289 of file MachineFrameInfo.h.
References I.
setStackSize()
void llvm::MachineFrameInfo::setStackSize (uint64_t Size) inline
setStackSize - Set the size of the stack...
Definition at line 454 of file MachineFrameInfo.h.
Referenced by llvm::PPCFrameLowering::determineFrameLayout(), llvm::Thumb1FrameLowering::emitPrologue(), and llvm::X86FrameLowering::emitPrologue().
setUseLocalStackAllocationBlock()
void llvm::MachineFrameInfo::setUseLocalStackAllocationBlock (bool v) inline
setUseLocalStackAllocationBlock - Set whether the local allocation blob should be allocated together or let PEI allocate the locals in it directly.
Definition at line 374 of file MachineFrameInfo.h.
The documentation for this class was generated from the following files:
MachineFrameInfo.h
MachineFunction.cpp