LLVM: llvm::RegisterRegAlloc Class Reference
LLVM API Documentation
llvm::RegisterRegAlloc Class Reference
#include <RegAllocRegistry.h>
Public Types
typedef FunctionPass *(* FunctionPassCtor) ()
Public Member Functions
RegisterRegAlloc (const char *N, const char *D, FunctionPassCtor C)
~RegisterRegAlloc ()
RegisterRegAlloc * getNext () const
Public Member Functions inherited from llvm::MachinePassRegistryNode
MachinePassRegistryNode (const char *N, const char *D, MachinePassCtor C)
MachinePassRegistryNode * getNext () const
MachinePassRegistryNode ** getNextAddress ()
const char * getName () const
const char * getDescription () const
MachinePassCtor getCtor () const
void setNext (MachinePassRegistryNode *N)
Static Public Member Functions
static RegisterRegAlloc * getList ()
static FunctionPassCtor getDefault ()
static void setDefault (FunctionPassCtor C)
static void setListener (MachinePassRegistryListener *L)
Static Public Attributes
static MachinePassRegistry Registry
RegisterRegAlloc's global Registry tracks allocator registration.
Detailed Description
RegisterRegAlloc class - Track the registration of register allocators.
Definition at line 27 of file RegAllocRegistry.h.
Member Typedef Documentation
FunctionPassCtor
typedef FunctionPass *(* llvm::RegisterRegAlloc::FunctionPassCtor) ()
Definition at line 31 of file RegAllocRegistry.h.
Constructor & Destructor Documentation
RegisterRegAlloc()
llvm::RegisterRegAlloc::RegisterRegAlloc (const char * N, const char * D, FunctionPassCtor C) inline
Definition at line 35 of file RegAllocRegistry.h.
References llvm::MachinePassRegistryNode::MachinePassRegistryNode(), N, and Registry.
Referenced by getList(), and getNext().
~RegisterRegAlloc()
llvm::RegisterRegAlloc::~RegisterRegAlloc () inline
Definition at line 40 of file RegAllocRegistry.h.
References Registry.
Member Function Documentation
getDefault()
FunctionPassCtor llvm::RegisterRegAlloc::getDefault () inline static
Definition at line 51 of file RegAllocRegistry.h.
References Registry.
Referenced by llvm::TargetPassConfig::createRegAllocPass().
getList()
RegisterRegAlloc * llvm::RegisterRegAlloc::getList () inline static
Definition at line 48 of file RegAllocRegistry.h.
References RegisterRegAlloc(), and Registry.
getNext()
RegisterRegAlloc * llvm::RegisterRegAlloc::getNext () const inline
Definition at line 45 of file RegAllocRegistry.h.
References llvm::MachinePassRegistryNode::getNext(), and RegisterRegAlloc().
setDefault()
void llvm::RegisterRegAlloc::setDefault (FunctionPassCtor C) inline static
Definition at line 54 of file RegAllocRegistry.h.
References Registry.
Referenced by llvm::TargetPassConfig::createRegAllocPass().
setListener()
void llvm::RegisterRegAlloc::setListener (MachinePassRegistryListener * L) inline static
Definition at line 57 of file RegAllocRegistry.h.
References Registry.
Member Data Documentation
Registry
MachinePassRegistry RegisterRegAlloc::Registry static
RegisterRegAlloc's global Registry tracks allocator registration.
Definition at line 33 of file RegAllocRegistry.h.
Referenced by getDefault(), getList(), RegisterRegAlloc(), setDefault(), setListener(), and ~RegisterRegAlloc().
The documentation for this class was generated from the following files:
RegAllocRegistry.h
Passes.cpp