LLVM: CloneFunction.cpp File Reference
LLVM API Documentation
CloneFunction.cpp File Reference
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
#include <map>
Functions
static MDNode * FindSubprogram (const Function *F, DebugInfoFinder &Finder)
static void AddOperand (DICompileUnit CU, DIArray SPs, Metadata *NewSP)
static void CloneDebugInfoMetadata (Function *NewFunc, const Function *OldFunc, ValueToValueMapTy &VMap)
Function Documentation
AddOperand()
void AddOperand (DICompileUnit CU, DIArray SPs, Metadata * NewSP) static
Definition at line 167 of file CloneFunction.cpp.
References llvm::MDNode::get(), I, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorImpl< T >::reserve().
Referenced by CloneDebugInfoMetadata().
CloneDebugInfoMetadata()
void CloneDebugInfoMetadata (Function * NewFunc, const Function * OldFunc, ValueToValueMapTy & VMap) static
Definition at line 178 of file CloneFunction.cpp.
References AddOperand(), llvm::DebugInfoFinder::compile_units(), FindSubprogram(), llvm::DITypedArray< T >::getElement(), llvm::DITypedArray< T >::getNumElements(), llvm::GlobalValue::getParent(), llvm::MapMetadata(), and llvm::DebugInfoFinder::processModule().
Referenced by llvm::CloneFunction().
FindSubprogram()
MDNode * FindSubprogram (const Function * F, DebugInfoFinder & Finder) static
Definition at line 158 of file CloneFunction.cpp.
References F, and llvm::DebugInfoFinder::subprograms().
Referenced by CloneDebugInfoMetadata().