LLVM: CodeGenPrepare.cpp File Reference
LLVM API Documentation
CodeGenPrepare.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/IR/ValueMap.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/BuildLibCalls.h"
#include "llvm/Transforms/Utils/BypassSlowDivision.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/SimplifyLibCalls.h"
Macros
#define DEBUG_TYPE "codegenprepare"
Functions
STATISTIC (NumBlocksElim, "Number of blocks eliminated")
STATISTIC (NumPHIsElim, "Number of trivial PHIs eliminated")
STATISTIC (NumGEPsElim, "Number of GEPs converted to casts")
STATISTIC (NumCmpUses, "Number of uses of Cmp expressions replaced with uses of " "sunken Cmps")
STATISTIC (NumCastUses, "Number of uses of Cast expressions replaced with uses " "of sunken Casts")
STATISTIC (NumMemoryInsts, "Number of memory instructions whose address " "computations were sunk")
STATISTIC (NumExtsMoved, "Number of [s|z]ext instructions combined with loads")
STATISTIC (NumExtUses, "Number of uses of [s|z]ext instructions optimized")
STATISTIC (NumRetsDup, "Number of return instructions duplicated")
STATISTIC (NumDbgValueMoved, "Number of debug value instructions moved")
STATISTIC (NumSelectsExpanded, "Number of selects turned into branches")
STATISTIC (NumAndCmpsMoved, "Number of and/cmp's pushed into branches")
STATISTIC (NumStoreExtractExposed, "Number of store(extractelement) exposed")
INITIALIZE_TM_PASS (CodeGenPrepare, "codegenprepare", "Optimize for code generation", false, false) FunctionPass *llvm
static bool SinkCast (CastInst *CI)
SinkCast - Sink the specified cast instruction into its user blocks.
static bool OptimizeNoopCopyExpression (CastInst *CI, const TargetLowering &TLI)
static bool OptimizeCmpExpression (CmpInst *CI)
static bool isExtractBitsCandidateUse (Instruction *User)
static bool SinkShiftAndTruncate (BinaryOperator *ShiftI, Instruction *User, ConstantInt *CI, DenseMap< BasicBlock *, BinaryOperator * > &InsertedShifts, const TargetLowering &TLI)
static bool OptimizeExtractBits (BinaryOperator *ShiftI, ConstantInt *CI, const TargetLowering &TLI)
static void ScalarizeMaskedLoad (CallInst *CI)
static void ScalarizeMaskedStore (CallInst *CI)
static bool IsNonLocalValue (Value *V, BasicBlock *BB)
static bool hasSameExtUse (Instruction *Inst, const TargetLowering &TLI)
Check if all the uses of Inst are equivalent (or free) zero or sign extensions.
Variables
static cl::opt< bool > DisableBranchOpts ("disable-cgp-branch-opts", cl::Hidden, cl::init(false), cl::desc("Disable branch optimizations in CodeGenPrepare"))
static cl::opt< bool > DisableSelectToBranch ("disable-cgp-select2branch", cl::Hidden, cl::init(false), cl::desc("Disable select to branch conversion."))
static cl::opt< bool > AddrSinkUsingGEPs ("addr-sink-using-gep", cl::Hidden, cl::init(false), cl::desc("Address sinking in CGP using GEPs."))
static cl::opt< bool > EnableAndCmpSinking ("enable-andcmp-sinking", cl::Hidden, cl::init(true), cl::desc("Enable sinkinig and/cmp into branches."))
static cl::opt< bool > DisableStoreExtract ("disable-cgp-store-extract", cl::Hidden, cl::init(false), cl::desc("Disable store(extract) optimizations in CodeGenPrepare"))
static cl::opt< bool > StressStoreExtract ("stress-cgp-store-extract", cl::Hidden, cl::init(false), cl::desc("Stress test store(extract) optimizations in CodeGenPrepare"))
static cl::opt< bool > DisableExtLdPromotion ("disable-cgp-ext-ld-promotion", cl::Hidden, cl::init(false), cl::desc("Disable ext(promotable(ld)) -> promoted(ext(ld)) optimization in " "CodeGenPrepare"))
static cl::opt< bool > StressExtLdPromotion ("stress-cgp-ext-ld-promotion", cl::Hidden, cl::init(false), cl::desc("Stress test ext(promotable(ld)) -> promoted(ext(ld)) " "optimization in CodeGenPrepare"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "codegenprepare"
Definition at line 52 of file CodeGenPrepare.cpp.
Function Documentation
hasSameExtUse()
bool hasSameExtUse (Instruction * Inst, const TargetLowering & TLI) static
Check if all the uses of Inst are equivalent (or free) zero or sign extensions.
Definition at line 3238 of file CodeGenPrepare.cpp.
References llvm::cast(), llvm::Type::getIntegerBitWidth(), llvm::Type::getScalarType(), llvm::Value::getType(), llvm::isa(), llvm::TargetLoweringBase::isZExtFree(), llvm::Value::use_empty(), llvm::Value::user_begin(), and llvm::Value::users().
INITIALIZE_TM_PASS()
INITIALIZE_TM_PASS (CodeGenPrepare , "codegenprepare" , "Optimize for code generation" , false , false)
Definition at line 190 of file CodeGenPrepare.cpp.
References const, and llvm::createCodeGenPreparePass().
isExtractBitsCandidateUse()
bool isExtractBitsCandidateUse (Instruction * User) static
isExtractBitsCandidateUse - Check if the candidates could be combined with shift instruction, which includes:
Truncate instruction
And instruction and the imm is a mask of the low bits: imm & (imm+1) == 0
Definition at line 672 of file CodeGenPrepare.cpp.
References llvm::cast(), llvm::User::getOperand(), and llvm::isa().
Referenced by OptimizeExtractBits().
IsNonLocalValue()
bool IsNonLocalValue (Value * V, BasicBlock * BB) static
IsNonLocalValue - Return true if the specified values are defined in a different basic block than BB.
Definition at line 2861 of file CodeGenPrepare.cpp.
References llvm::dyn_cast(), and I.
OptimizeCmpExpression()
bool OptimizeCmpExpression (CmpInst * CI) static
OptimizeCmpExpression - sink the given CmpInst into user blocks to reduce the number of virtual registers that must be created and coalesced. This is a clear win except on targets with multiple condition code registers (PowerPC), where it might lose; some adjustment may be wanted there.
Return true if any changes are made.
InsertedCmp - Only insert a cmp in each block once.
Definition at line 618 of file CodeGenPrepare.cpp.
References llvm::cast(), llvm::CmpInst::Create(), llvm::Instruction::eraseFromParent(), llvm::BasicBlock::getFirstInsertionPt(), llvm::CmpInst::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::CmpInst::getPredicate(), llvm::isa(), llvm::Value::use_empty(), llvm::Value::user_begin(), and llvm::Value::user_end().
OptimizeExtractBits()
bool OptimizeExtractBits (BinaryOperator * ShiftI, ConstantInt * CI, const TargetLowering & TLI) static
OptimizeExtractBits - sink the shift right instruction into user blocks if the uses could potentially be combined with this shift instruction and generate BitExtract instruction. It will only be applied if the architecture supports BitExtract instruction. Here is an example: BB1: x.extract.shift = lshr i64 arg1, 32 BB2: x.extract.trunc = trunc i64 x.extract.shift to i16 ==>
BB2: x.extract.shift.1 = lshr i64 arg1, 32 x.extract.trunc = trunc i64 x.extract.shift.1 to i16
CodeGen will recoginze the pattern in BB2 and generate BitExtract instruction. Return true if any changes are made.
Only insert instructions in each block once.
Definition at line 774 of file CodeGenPrepare.cpp.
References llvm::cast(), llvm::Instruction::eraseFromParent(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::TargetLoweringBase::getValueType(), llvm::isa(), isExtractBitsCandidateUse(), llvm::TargetLoweringBase::isTypeLegal(), SinkShiftAndTruncate(), llvm::Value::use_empty(), llvm::Value::user_begin(), and llvm::Value::user_end().
OptimizeNoopCopyExpression()
bool OptimizeNoopCopyExpression (CastInst * CI, const TargetLowering & TLI) static
OptimizeNoopCopyExpression - If the specified cast instruction is a noop copy (e.g. it's casting from one pointer type to another, i32->i8 on PPC), sink it into user blocks to reduce the number of virtual registers that must be created and coalesced.
Return true if any changes are made.
Definition at line 582 of file CodeGenPrepare.cpp.
References llvm::EVT::bitsLT(), llvm::Value::getContext(), llvm::User::getOperand(), llvm::Value::getType(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::TargetLoweringBase::getValueType(), llvm::EVT::isInteger(), SinkCast(), and llvm::TargetLoweringBase::TypePromoteInteger.
ScalarizeMaskedLoad()
void ScalarizeMaskedLoad (CallInst * CI) static
Definition at line 886 of file CodeGenPrepare.cpp.
References llvm::PHINode::addIncoming(), llvm::cast(), llvm::BranchInst::Create(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateExtractElement(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmp(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInsertElement(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateLoad(), llvm::IRBuilder< preserveNames, T, Inserter >::CreatePHI(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSelect(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::CallInst::getArgOperand(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::IRBuilderBase::getInt32(), llvm::Instruction::getParent(), llvm::Type::getPointerTo(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::Value::replaceAllUsesWith(), llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::BasicBlock::splitBasicBlock().
ScalarizeMaskedStore()
void ScalarizeMaskedStore (CallInst * CI) static
Definition at line 997 of file CodeGenPrepare.cpp.
References llvm::cast(), llvm::BranchInst::Create(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateExtractElement(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmp(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateStore(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::ConstantInt::get(), llvm::CallInst::getArgOperand(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::IRBuilderBase::getInt32(), llvm::Instruction::getParent(), llvm::Type::getPointerTo(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::IRBuilderBase::SetCurrentDebugLocation(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::BasicBlock::splitBasicBlock().
SinkCast()
bool SinkCast (CastInst * CI) static
SinkCast - Sink the specified cast instruction into its user blocks.
InsertedCasts - Only insert a cast in each block once.
Definition at line 525 of file CodeGenPrepare.cpp.
References llvm::cast(), llvm::CastInst::Create(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingBlock(), llvm::CastInst::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::Value::use_empty(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by OptimizeNoopCopyExpression().
SinkShiftAndTruncate()
bool SinkShiftAndTruncate (BinaryOperator * ShiftI, Instruction * User, ConstantInt * CI, DenseMap< BasicBlock *, BinaryOperator * > & InsertedShifts, const TargetLowering & TLI) static
SinkShiftAndTruncate - sink both shift and truncate instruction to the use of truncate's BB.
Definition at line 689 of file CodeGenPrepare.cpp.
References llvm::cast(), llvm::CastInst::Create(), llvm::dyn_cast(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BinaryOperator::getOpcode(), llvm::CastInst::getOpcode(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::isa(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by OptimizeExtractBits().
STATISTIC() [1/13]
STATISTIC (NumAndCmpsMoved , "Number of and/cmp's pushed into branches")
STATISTIC() [2/13]
STATISTIC (NumBlocksElim , "Number of blocks eliminated")
STATISTIC() [3/13]
STATISTIC (NumCastUses , "Number of uses of Cast expressions replaced with uses " "of sunken Casts")
STATISTIC() [4/13]
STATISTIC (NumCmpUses , "Number of uses of Cmp expressions replaced with uses of " "sunken Cmps")
STATISTIC() [5/13]
STATISTIC (NumDbgValueMoved , "Number of debug value instructions moved")
STATISTIC() [6/13]
STATISTIC (NumExtsMoved , "Number of ext instructions combined with loads" [s|z])
STATISTIC() [7/13]
STATISTIC (NumExtUses , "Number of uses of ext instructions optimized" [s|z])
STATISTIC() [8/13]
STATISTIC (NumGEPsElim , "Number of GEPs converted to casts")
STATISTIC() [9/13]
STATISTIC (NumMemoryInsts , "Number of memory instructions whose address " "computations were sunk")
STATISTIC() [10/13]
STATISTIC (NumPHIsElim , "Number of trivial PHIs eliminated")
STATISTIC() [11/13]
STATISTIC (NumRetsDup , "Number of return instructions duplicated")
STATISTIC() [12/13]
STATISTIC (NumSelectsExpanded , "Number of selects turned into branches")
STATISTIC() [13/13]
STATISTIC (NumStoreExtractExposed , "Number of store(extractelement) exposed")
Variable Documentation
AddrSinkUsingGEPs
cl::opt< bool > AddrSinkUsingGEPs("addr-sink-using-gep", cl::Hidden, cl::init(false), cl::desc("Address sinking in CGP using GEPs.")) ("addr-sink-using-gep" , cl::Hidden , cl::init(false) , cl::desc("Address sinking in CGP using GEPs.")) static
DisableBranchOpts
cl::opt< bool > DisableBranchOpts("disable-cgp-branch-opts", cl::Hidden, cl::init(false), cl::desc("Disable branch optimizations in CodeGenPrepare")) ("disable-cgp-branch-opts" , cl::Hidden , cl::init(false) , cl::desc("Disable branch optimizations in CodeGenPrepare")) static
DisableExtLdPromotion
cl::opt< bool > DisableExtLdPromotion("disable-cgp-ext-ld-promotion", cl::Hidden, cl::init(false), cl::desc("Disable ext(promotable(ld)) -> promoted(ext(ld)) optimization in " "CodeGenPrepare")) ("disable-cgp-ext-ld-promotion" , cl::Hidden , cl::init(false) , cl::desc("Disable ext(promotable(ld)) -> promoted(ext(ld)) optimization in " "CodeGenPrepare")) static
DisableSelectToBranch
cl::opt< bool > DisableSelectToBranch("disable-cgp-select2branch", cl::Hidden, cl::init(false), cl::desc("Disable select to branch conversion.")) ("disable-cgp-select2branch" , cl::Hidden , cl::init(false) , cl::desc("Disable select to branch conversion.")) static
DisableStoreExtract
cl::opt< bool > DisableStoreExtract("disable-cgp-store-extract", cl::Hidden, cl::init(false), cl::desc("Disable store(extract) optimizations in CodeGenPrepare")) ("disable-cgp-store-extract" , cl::Hidden , cl::init(false) , cl::desc("Disable store(extract) optimizations in CodeGenPrepare")) static
EnableAndCmpSinking
cl::opt< bool > EnableAndCmpSinking("enable-andcmp-sinking", cl::Hidden, cl::init(true), cl::desc("Enable sinkinig and/cmp into branches.")) ("enable-andcmp-sinking" , cl::Hidden , cl::init(true) , cl::desc("Enable sinkinig and/cmp into branches.")) static
StressExtLdPromotion
cl::opt< bool > StressExtLdPromotion("stress-cgp-ext-ld-promotion", cl::Hidden, cl::init(false), cl::desc("Stress test ext(promotable(ld)) -> promoted(ext(ld)) " "optimization in CodeGenPrepare")) ("stress-cgp-ext-ld-promotion" , cl::Hidden , cl::init(false) , cl::desc("Stress test ext(promotable(ld)) -> promoted(ext(ld)) " "optimization in CodeGenPrepare")) static
StressStoreExtract
cl::opt< bool > StressStoreExtract("stress-cgp-store-extract", cl::Hidden, cl::init(false), cl::desc("Stress test store(extract) optimizations in CodeGenPrepare")) ("stress-cgp-store-extract" , cl::Hidden , cl::init(false) , cl::desc("Stress test store(extract) optimizations in CodeGenPrepare")) static