LLVM: CodeMetrics.cpp File Reference
LLVM API Documentation
CodeMetrics.cpp File Reference
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "code-metrics"
Functions
static void completeEphemeralValues (SmallVector< const Value *, 16 > &WorkSet, SmallPtrSetImpl< const Value * > &EphValues)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "code-metrics"
Definition at line 25 of file CodeMetrics.cpp.
Function Documentation
completeEphemeralValues()
void completeEphemeralValues (SmallVector< const Value *, 16 > & WorkSet, SmallPtrSetImpl< const Value * > & EphValues) static
Definition at line 29 of file CodeMetrics.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::SmallVectorTemplateCommon< T, typename >::front(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isSafeToSpeculativelyExecute(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::CodeMetrics::collectEphemeralValues(), and llvm::CodeMetrics::collectEphemeralValues().