LLVM: CommandFlags.h File Reference
LLVM API Documentation
CommandFlags.h File Reference
#include "llvm/MC/MCTargetOptionsCommandFlags.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <string>
Functions
cl::opt< std::string > MArch ("march", cl::desc("Architecture to generate code for (see --version)"))
cl::opt< std::string > MCPU ("mcpu", cl::desc("Target a specific cpu type (-mcpu=help for details)"), cl::value_desc("cpu-name"), cl::init(""))
cl::list< std::string > MAttrs ("mattr", cl::CommaSeparated, cl::desc("Target specific attributes (-mattr=help for details)"), cl::value_desc("a1,+a2,-a3,..."))
cl::opt< Reloc::Model > RelocModel ("relocation-model", cl::desc("Choose relocation model"), cl::init(Reloc::Default), cl::values(clEnumValN(Reloc::Default, "default", "Target default relocation model"), clEnumValN(Reloc::Static, "static", "Non-relocatable code"), clEnumValN(Reloc::PIC_, "pic", "Fully relocatable, position independent code"), clEnumValN(Reloc::DynamicNoPIC, "dynamic-no-pic", "Relocatable external references, non-relocatable code"), clEnumValEnd))
cl::opt< ThreadModel::Model > TMModel ("thread-model", cl::desc("Choose threading model"), cl::init(ThreadModel::POSIX), cl::values(clEnumValN(ThreadModel::POSIX, "posix", "POSIX thread model"), clEnumValN(ThreadModel::Single, "single", "Single thread model"), clEnumValEnd))
cl::opt< llvm::CodeModel::Model > CMModel ("code-model", cl::desc("Choose code model"), cl::init(CodeModel::Default), cl::values(clEnumValN(CodeModel::Default, "default", "Target default code model"), clEnumValN(CodeModel::Small, "small", "Small code model"), clEnumValN(CodeModel::Kernel, "kernel", "Kernel code model"), clEnumValN(CodeModel::Medium, "medium", "Medium code model"), clEnumValN(CodeModel::Large, "large", "Large code model"), clEnumValEnd))
cl::opt< TargetMachine::CodeGenFileType > FileType ("filetype", cl::init(TargetMachine::CGFT_AssemblyFile), cl::desc("Choose a file type (not all types are supported by all targets):"), cl::values(clEnumValN(TargetMachine::CGFT_AssemblyFile, "asm", "Emit an assembly ('.s') file"), clEnumValN(TargetMachine::CGFT_ObjectFile, "obj", "Emit a native object ('.o') file"), clEnumValN(TargetMachine::CGFT_Null, "null", "Emit nothing, for performance testing"), clEnumValEnd))
cl::opt< bool > EnableFPMAD ("enable-fp-mad", cl::desc("Enable less precise MAD instructions to be generated"), cl::init(false))
cl::opt< bool > DisableFPElim ("disable-fp-elim", cl::desc("Disable frame pointer elimination optimization"), cl::init(false))
cl::opt< bool > EnableUnsafeFPMath ("enable-unsafe-fp-math", cl::desc("Enable optimizations that may decrease FP precision"), cl::init(false))
cl::opt< bool > EnableNoInfsFPMath ("enable-no-infs-fp-math", cl::desc("Enable FP math optimizations that assume no +-Infs"), cl::init(false))
cl::opt< bool > EnableNoNaNsFPMath ("enable-no-nans-fp-math", cl::desc("Enable FP math optimizations that assume no NaNs"), cl::init(false))
cl::opt< bool > EnableHonorSignDependentRoundingFPMath ("enable-sign-dependent-rounding-fp-math", cl::Hidden, cl::desc("Force codegen to assume rounding mode can change dynamically"), cl::init(false))
cl::opt< bool > GenerateSoftFloatCalls ("soft-float", cl::desc("Generate software floating point library calls"), cl::init(false))
cl::opt< llvm::FloatABI::ABIType > FloatABIForCalls ("float-abi", cl::desc("Choose float ABI type"), cl::init(FloatABI::Default), cl::values(clEnumValN(FloatABI::Default, "default", "Target default float ABI type"), clEnumValN(FloatABI::Soft, "soft", "Soft float ABI (implied by -soft-float)"), clEnumValN(FloatABI::Hard, "hard", "Hard float ABI (uses FP registers)"), clEnumValEnd))
cl::opt< llvm::FPOpFusion::FPOpFusionMode > FuseFPOps ("fp-contract", cl::desc("Enable aggressive formation of fused FP ops"), cl::init(FPOpFusion::Standard), cl::values(clEnumValN(FPOpFusion::Fast, "fast", "Fuse FP ops whenever profitable"), clEnumValN(FPOpFusion::Standard, "on", "Only fuse 'blessed' FP ops."), clEnumValN(FPOpFusion::Strict, "off", "Only fuse FP ops when the result won't be effected."), clEnumValEnd))
cl::opt< bool > DontPlaceZerosInBSS ("nozero-initialized-in-bss", cl::desc("Don't place zero-initialized symbols into bss section"), cl::init(false))
cl::opt< bool > EnableGuaranteedTailCallOpt ("tailcallopt", cl::desc("Turn fastcc calls into tail calls by (potentially) changing ABI."), cl::init(false))
cl::opt< bool > DisableTailCalls ("disable-tail-calls", cl::desc("Never emit tail calls"), cl::init(false))
cl::opt< unsigned > OverrideStackAlignment ("stack-alignment", cl::desc("Override default stack alignment"), cl::init(0))
cl::opt< std::string > TrapFuncName ("trap-func", cl::Hidden, cl::desc("Emit a call to trap function rather than a trap instruction"), cl::init(""))
cl::opt< bool > EnablePIE ("enable-pie", cl::desc("Assume the creation of a position independent executable."), cl::init(false))
cl::opt< bool > UseCtors ("use-ctors", cl::desc("Use .ctors instead of .init_array."), cl::init(false))
cl::opt< std::string > StopAfter ("stop-after", cl::desc("Stop compilation after a specific pass"), cl::value_desc("pass-name"), cl::init(""))
cl::opt< std::string > StartAfter ("start-after", cl::desc("Resume compilation after a specific pass"), cl::value_desc("pass-name"), cl::init(""))
cl::opt< bool > DataSections ("data-sections", cl::desc("Emit data into separate sections"), cl::init(false))
cl::opt< bool > FunctionSections ("function-sections", cl::desc("Emit functions into separate sections"), cl::init(false))
cl::opt< llvm::JumpTable::JumpTableType > JTableType ("jump-table-type", cl::desc("Choose the type of Jump-Instruction Table for jumptable."), cl::init(JumpTable::Single), cl::values(clEnumValN(JumpTable::Single, "single", "Create a single table for all jumptable functions"), clEnumValN(JumpTable::Arity, "arity", "Create one table per number of parameters."), clEnumValN(JumpTable::Simplified, "simplified", "Create one table per simplified function type."), clEnumValN(JumpTable::Full, "full", "Create one table per unique function type."), clEnumValEnd))
cl::opt< bool > FCFI ("fcfi", cl::desc("Apply forward-edge control-flow integrity"), cl::init(false))
cl::opt< llvm::CFIntegrity > CFIType ("cfi-type", cl::desc("Choose the type of Control-Flow Integrity check to add"), cl::init(CFIntegrity::Sub), cl::values(clEnumValN(CFIntegrity::Sub, "sub", "Subtract the pointer from the table base, then mask."), clEnumValN(CFIntegrity::Ror, "ror", "Use rotate to check the offset from a table base."), clEnumValN(CFIntegrity::Add, "add", "Mask out the high bits and add to an aligned base."), clEnumValEnd))
cl::opt< bool > CFIEnforcing ("cfi-enforcing", cl::desc("Enforce CFI or pass the violation to a function."), cl::init(false))
cl::opt< std::string > CFIFuncName ("cfi-func-name", cl::desc("The name of the CFI function to call"), cl::init(""))
static TargetOptions InitTargetOptionsFromCodeGenFlags ()
Function Documentation
CFIEnforcing()
cl::opt< bool > CFIEnforcing ("cfi-enforcing" , cl::desc("Enforce CFI or pass the violation to a function.") , cl::init(false))
References llvm::cl::init().
Referenced by llvm::createForwardControlFlowIntegrityPass(), InitTargetOptionsFromCodeGenFlags(), and llvm::operator==().
CFIFuncName()
cl::opt< std::string > CFIFuncName ("cfi-func-name" , cl::desc("The name of the CFI function to call") , cl::init(""))
References llvm::cl::init().
Referenced by llvm::createForwardControlFlowIntegrityPass(), InitTargetOptionsFromCodeGenFlags(), and llvm::operator==().
CFIType()
cl::opt< llvm::CFIntegrity > CFIType ("cfi-type" , cl::desc("Choose the type of Control-Flow Integrity check to add") , cl::init(CFIntegrity::Sub) , cl::values(clEnumValN(CFIntegrity::Sub, "sub", "Subtract the pointer from the table base, then mask."), clEnumValN(CFIntegrity::Ror, "ror", "Use rotate to check the offset from a table base."), clEnumValN(CFIntegrity::Add, "add", "Mask out the high bits and add to an aligned base."), clEnumValEnd))
References llvm::Add, clEnumValEnd, llvm::cl::init(), llvm::Ror, llvm::Sub, and llvm::cl::values().
Referenced by llvm::createForwardControlFlowIntegrityPass(), InitTargetOptionsFromCodeGenFlags(), and llvm::operator==().
CMModel()
cl::opt< llvm::CodeModel::Model > CMModel ("code-model" , cl::desc("Choose code model") , cl::init(CodeModel::Default) , cl::values(clEnumValN(CodeModel::Default, "default", "Target default code model"), clEnumValN(CodeModel::Small, "small", "Small code model"), clEnumValN(CodeModel::Kernel, "kernel", "Kernel code model"), clEnumValN(CodeModel::Medium, "medium", "Medium code model"), clEnumValN(CodeModel::Large, "large", "Large code model"), clEnumValEnd))
References clEnumValEnd, llvm::CodeModel::Default, llvm::cl::init(), llvm::CodeModel::Kernel, llvm::CodeModel::Large, llvm::CodeModel::Medium, llvm::CodeModel::Small, and llvm::cl::values().
DataSections()
cl::opt< bool > DataSections ("data-sections" , cl::desc("Emit data into separate sections") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
DisableFPElim()
cl::opt< bool > DisableFPElim ("disable-fp-elim" , cl::desc("Disable frame pointer elimination optimization") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
DisableTailCalls()
cl::opt< bool > DisableTailCalls ("disable-tail-calls" , cl::desc("Never emit tail calls") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags(), llvm::operator==(), and llvm::TargetMachine::resetTargetOptions().
DontPlaceZerosInBSS()
cl::opt< bool > DontPlaceZerosInBSS ("nozero-initialized-in-bss" , cl::desc("Don't place zero-initialized symbols into bss section") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
EnableFPMAD()
cl::opt< bool > EnableFPMAD ("enable-fp-mad" , cl::desc("Enable less precise MAD instructions to be generated") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
EnableGuaranteedTailCallOpt()
cl::opt< bool > EnableGuaranteedTailCallOpt ("tailcallopt" , cl::desc("Turn fastcc calls into tail calls by (potentially) changing ABI.") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
EnableHonorSignDependentRoundingFPMath()
cl::opt< bool > EnableHonorSignDependentRoundingFPMath ("enable-sign-dependent-rounding-fp-math" , cl::Hidden , cl::desc("Force codegen to assume rounding mode can change dynamically") , cl::init(false))
References llvm::cl::Hidden, and llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
EnableNoInfsFPMath()
cl::opt< bool > EnableNoInfsFPMath ("enable-no-infs-fp-math" , cl::desc("Enable FP math optimizations that assume no +-Infs") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
EnableNoNaNsFPMath()
cl::opt< bool > EnableNoNaNsFPMath ("enable-no-nans-fp-math" , cl::desc("Enable FP math optimizations that assume no NaNs") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
EnablePIE()
cl::opt< bool > EnablePIE ("enable-pie" , cl::desc("Assume the creation of a position independent executable.") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
EnableUnsafeFPMath()
cl::opt< bool > EnableUnsafeFPMath ("enable-unsafe-fp-math" , cl::desc("Enable optimizations that may decrease FP precision") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
FCFI()
cl::opt< bool > FCFI ("fcfi" , cl::desc("Apply forward-edge control-flow integrity") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags(), and llvm::operator==().
FileType()
cl::opt< TargetMachine::CodeGenFileType > FileType ("filetype" , cl::init(TargetMachine::CGFT_AssemblyFile) , cl::desc("Choose a file type (not all types are supported by all targets):") , cl::values(clEnumValN(TargetMachine::CGFT_AssemblyFile, "asm", "Emit an assembly ('.s') file"), clEnumValN(TargetMachine::CGFT_ObjectFile, "obj", "Emit a native object ('.o') file"), clEnumValN(TargetMachine::CGFT_Null, "null", "Emit nothing, for performance testing"), clEnumValEnd))
References llvm::TargetMachine::CGFT_AssemblyFile, llvm::TargetMachine::CGFT_Null, llvm::TargetMachine::CGFT_ObjectFile, clEnumValEnd, llvm::cl::init(), and llvm::cl::values().
Referenced by llvm::CPPTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitFile().
FloatABIForCalls()
cl::opt< llvm::FloatABI::ABIType > FloatABIForCalls ("float-abi" , cl::desc("Choose float ABI type") , cl::init(FloatABI::Default) , cl::values(clEnumValN(FloatABI::Default, "default", "Target default float ABI type"), clEnumValN(FloatABI::Soft, "soft", "Soft float ABI (implied by -soft-float)"), clEnumValN(FloatABI::Hard, "hard", "Hard float ABI (uses FP registers)"), clEnumValEnd))
References clEnumValEnd, llvm::FloatABI::Default, llvm::FloatABI::Hard, llvm::cl::init(), llvm::FloatABI::Soft, and llvm::cl::values().
Referenced by InitTargetOptionsFromCodeGenFlags().
FunctionSections()
cl::opt< bool > FunctionSections ("function-sections" , cl::desc("Emit functions into separate sections") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
FuseFPOps()
cl::opt< llvm::FPOpFusion::FPOpFusionMode > FuseFPOps ("fp-contract" , cl::desc("Enable aggressive formation of fused FP ops") , cl::init(FPOpFusion::Standard) , cl::values(clEnumValN(FPOpFusion::Fast, "fast", "Fuse FP ops whenever profitable"), clEnumValN(FPOpFusion::Standard, "on", "Only fuse 'blessed' FP ops."), clEnumValN(FPOpFusion::Strict, "off", "Only fuse FP ops when the result won't be effected."), clEnumValEnd))
References clEnumValEnd, llvm::FPOpFusion::Fast, llvm::cl::init(), llvm::FPOpFusion::Standard, llvm::FPOpFusion::Strict, and llvm::cl::values().
Referenced by InitTargetOptionsFromCodeGenFlags().
GenerateSoftFloatCalls()
cl::opt< bool > GenerateSoftFloatCalls ("soft-float" , cl::desc("Generate software floating point library calls") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
InitTargetOptionsFromCodeGenFlags()
TargetOptions InitTargetOptionsFromCodeGenFlags () inline static
Definition at line 265 of file CommandFlags.h.
References llvm::TargetOptions::AllowFPOpFusion, CFIEnforcing(), llvm::TargetOptions::CFIEnforcing, CFIFuncName(), llvm::TargetOptions::CFIFuncName, CFIType(), llvm::TargetOptions::CFIType, DataSections(), llvm::TargetOptions::DataSections, llvm::FloatABI::Default, DisableFPElim(), DisableTailCalls(), llvm::TargetOptions::DisableTailCalls, DontPlaceZerosInBSS(), EnableFPMAD(), EnableGuaranteedTailCallOpt(), EnableHonorSignDependentRoundingFPMath(), EnableNoInfsFPMath(), EnableNoNaNsFPMath(), EnablePIE(), EnableUnsafeFPMath(), FCFI(), llvm::TargetOptions::FCFI, FloatABIForCalls(), llvm::TargetOptions::FloatABIType, FunctionSections(), llvm::TargetOptions::FunctionSections, FuseFPOps(), GenerateSoftFloatCalls(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::TargetOptions::HonorSignDependentRoundingFPMathOption, InitMCTargetOptionsFromFlags(), JTableType(), llvm::TargetOptions::JTType, llvm::TargetOptions::LessPreciseFPMADOption, llvm::TargetOptions::MCOptions, llvm::TargetOptions::NoFramePointerElim, llvm::TargetOptions::NoInfsFPMath, llvm::TargetOptions::NoNaNsFPMath, llvm::TargetOptions::NoZerosInBSS, OverrideStackAlignment(), llvm::TargetOptions::PositionIndependentExecutable, llvm::TargetOptions::StackAlignmentOverride, llvm::TargetOptions::ThreadModel, TMModel(), llvm::TargetOptions::TrapFuncName, TrapFuncName(), llvm::TargetOptions::UnsafeFPMath, UseCtors(), llvm::TargetOptions::UseInitArray, and llvm::TargetOptions::UseSoftFloat.
JTableType()
cl::opt< llvm::JumpTable::JumpTableType > JTableType ("jump-table-type" , cl::desc("Choose the type of Jump-Instruction Table for jumptable.") , cl::init(JumpTable::Single) , cl::values(clEnumValN(JumpTable::Single, "single", "Create a single table for all jumptable functions"), clEnumValN(JumpTable::Arity, "arity", "Create one table per number of parameters."), clEnumValN(JumpTable::Simplified, "simplified", "Create one table per simplified function type."), clEnumValN(JumpTable::Full, "full", "Create one table per unique function type."), clEnumValEnd))
References llvm::JumpTable::Arity, clEnumValEnd, llvm::JumpTable::Full, llvm::cl::init(), llvm::JumpTable::Simplified, llvm::JumpTable::Single, and llvm::cl::values().
Referenced by InitTargetOptionsFromCodeGenFlags().
MArch()
cl::opt< std::string > MArch ("march" , cl::desc("Architecture to generate code for (see --version)"))
Referenced by llvm::Triple::getARMCPUForArch().
MAttrs()
cl::list< std::string > MAttrs ("mattr" , cl::CommaSeparated , cl::desc("Target specific attributes (-mattr=help for details)") , cl::value_desc("a1,+a2,-a3,..."))
References llvm::cl::CommaSeparated.
MCPU()
cl::opt< std::string > MCPU ("mcpu" , cl::desc("Target a specific cpu type (-mcpu=help for details)") , cl::value_desc("cpu-name") , cl::init(""))
References llvm::cl::init().
OverrideStackAlignment()
cl::opt< unsigned > OverrideStackAlignment ("stack-alignment" , cl::desc("Override default stack alignment") , cl::init(0))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().
RelocModel()
cl::opt< Reloc::Model > RelocModel ("relocation-model" , cl::desc("Choose relocation model") , cl::init(Reloc::Default) , cl::values(clEnumValN(Reloc::Default, "default", "Target default relocation model"), clEnumValN(Reloc::Static, "static", "Non-relocatable code"), clEnumValN(Reloc::PIC_, "pic", "Fully relocatable, position independent code"), clEnumValN(Reloc::DynamicNoPIC, "dynamic-no-pic", "Relocatable external references, non-relocatable code"), clEnumValEnd))
References clEnumValEnd, llvm::Reloc::Default, llvm::Reloc::DynamicNoPIC, llvm::cl::init(), llvm::Reloc::PIC_, llvm::Reloc::Static, and llvm::cl::values().
StartAfter()
cl::opt< std::string > StartAfter ("start-after" , cl::desc("Resume compilation after a specific pass") , cl::value_desc("pass-name") , cl::init(""))
References llvm::cl::init().
Referenced by llvm::CPPTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitFile(), and addPassesToGenerateCode().
StopAfter()
cl::opt< std::string > StopAfter ("stop-after" , cl::desc("Stop compilation after a specific pass") , cl::value_desc("pass-name") , cl::init(""))
References llvm::cl::init().
Referenced by llvm::CPPTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitFile(), and addPassesToGenerateCode().
TMModel()
cl::opt< ThreadModel::Model > TMModel ("thread-model" , cl::desc("Choose threading model") , cl::init(ThreadModel::POSIX) , cl::values(clEnumValN(ThreadModel::POSIX, "posix", "POSIX thread model"), clEnumValN(ThreadModel::Single, "single", "Single thread model"), clEnumValEnd))
References clEnumValEnd, llvm::cl::init(), llvm::ThreadModel::POSIX, llvm::ThreadModel::Single, and llvm::cl::values().
Referenced by InitTargetOptionsFromCodeGenFlags().
TrapFuncName()
cl::opt< std::string > TrapFuncName ("trap-func" , cl::Hidden , cl::desc("Emit a call to trap function rather than a trap instruction") , cl::init(""))
References llvm::cl::Hidden, and llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags(), and llvm::operator==().
UseCtors()
cl::opt< bool > UseCtors ("use-ctors" , cl::desc("Use .ctors instead of .init_array.") , cl::init(false))
References llvm::cl::init().
Referenced by InitTargetOptionsFromCodeGenFlags().