LLVM: ConstantMerge.cpp File Reference
LLVM API Documentation
ConstantMerge.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/Pass.h"
Macros
#define DEBUG_TYPE "constmerge"
Functions
STATISTIC (NumMerged, "Number of global constants merged")
INITIALIZE_PASS (ConstantMerge, "constmerge", "Merge Duplicate Global Constants", false, false) ModulePass *llvm
static void FindUsedValues (GlobalVariable *LLVMUsed, SmallPtrSetImpl< const GlobalValue * > &UsedValues)
Find values that are marked as llvm.used.
static bool IsBetterCanonical (const GlobalVariable &A, const GlobalVariable &B)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "constmerge"
Definition at line 33 of file ConstantMerge.cpp.
Function Documentation
FindUsedValues()
void FindUsedValues (GlobalVariable * LLVMUsed, SmallPtrSetImpl< const GlobalValue * > & UsedValues) static
Find values that are marked as llvm.used.
Definition at line 68 of file ConstantMerge.cpp.
References llvm::cast(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::Value::stripPointerCastsNoFollowAliases().
INITIALIZE_PASS()
INITIALIZE_PASS (ConstantMerge , "constmerge" , "Merge Duplicate Global Constants" , false , false)
Definition at line 60 of file ConstantMerge.cpp.
References llvm::createConstantMergePass().
IsBetterCanonical()
bool IsBetterCanonical (const GlobalVariable & A, const GlobalVariable & B) static
Definition at line 81 of file ConstantMerge.cpp.
References llvm::GlobalValue::hasLocalLinkage().
STATISTIC()
STATISTIC (NumMerged , "Number of global constants merged")
References llvm::PassRegistry::getPassRegistry().