LLVM: Core.cpp File Reference
LLVM API Documentation
Core.cpp File Reference
#include "llvm-c/Core.h"
#include "llvm/Bitcode/ReaderWriter.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/DiagnosticPrinter.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/PassManager.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdlib>
#include <cstring>
#include <system_error>
#include "llvm/IR/Instruction.def"
Macros
#define DEBUG_TYPE "ir"
#define LLVM_DEFINE_VALUE_CAST(name)
#define HANDLE_INST(num, opc, clas)
#define HANDLE_INST(num, opc, clas)
Functions
void LLVMInitializeCore (LLVMPassRegistryRef R)
void LLVMShutdown ()
char * LLVMCreateMessage (const char *Message)
void LLVMDisposeMessage (char *Message)
LLVMContextRef LLVMContextCreate ()
LLVMContextRef LLVMGetGlobalContext ()
void LLVMContextSetDiagnosticHandler (LLVMContextRef C, LLVMDiagnosticHandler Handler, void *DiagnosticContext)
void LLVMContextSetYieldCallback (LLVMContextRef C, LLVMYieldCallback Callback, void *OpaqueHandle)
void LLVMContextDispose (LLVMContextRef C)
unsigned LLVMGetMDKindIDInContext (LLVMContextRef C, const char *Name, unsigned SLen)
unsigned LLVMGetMDKindID (const char *Name, unsigned SLen)
char * LLVMGetDiagInfoDescription (LLVMDiagnosticInfoRef DI)
LLVMDiagnosticSeverity LLVMGetDiagInfoSeverity (LLVMDiagnosticInfoRef DI)
LLVMModuleRef LLVMModuleCreateWithName (const char *ModuleID)
LLVMModuleRef LLVMModuleCreateWithNameInContext (const char *ModuleID, LLVMContextRef C)
void LLVMDisposeModule (LLVMModuleRef M)
const char * LLVMGetDataLayout (LLVMModuleRef M)
void LLVMSetDataLayout (LLVMModuleRef M, const char *Triple)
const char * LLVMGetTarget (LLVMModuleRef M)
void LLVMSetTarget (LLVMModuleRef M, const char *Triple)
void LLVMDumpModule (LLVMModuleRef M)
LLVMBool LLVMPrintModuleToFile (LLVMModuleRef M, const char *Filename, char **ErrorMessage)
char * LLVMPrintModuleToString (LLVMModuleRef M)
void LLVMSetModuleInlineAsm (LLVMModuleRef M, const char *Asm)
LLVMContextRef LLVMGetModuleContext (LLVMModuleRef M)
LLVMTypeKind LLVMGetTypeKind (LLVMTypeRef Ty)
LLVMBool LLVMTypeIsSized (LLVMTypeRef Ty)
LLVMContextRef LLVMGetTypeContext (LLVMTypeRef Ty)
void LLVMDumpType (LLVMTypeRef Ty)
char * LLVMPrintTypeToString (LLVMTypeRef Ty)
LLVMTypeRef LLVMInt1TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt8TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt16TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt32TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMInt64TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMIntTypeInContext (LLVMContextRef C, unsigned NumBits)
LLVMTypeRef LLVMInt1Type (void)
LLVMTypeRef LLVMInt8Type (void)
LLVMTypeRef LLVMInt16Type (void)
LLVMTypeRef LLVMInt32Type (void)
LLVMTypeRef LLVMInt64Type (void)
LLVMTypeRef LLVMIntType (unsigned NumBits)
unsigned LLVMGetIntTypeWidth (LLVMTypeRef IntegerTy)
LLVMTypeRef LLVMHalfTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMFloatTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMDoubleTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMX86FP80TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMFP128TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMPPCFP128TypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMX86MMXTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMHalfType (void)
LLVMTypeRef LLVMFloatType (void)
LLVMTypeRef LLVMDoubleType (void)
LLVMTypeRef LLVMX86FP80Type (void)
LLVMTypeRef LLVMFP128Type (void)
LLVMTypeRef LLVMPPCFP128Type (void)
LLVMTypeRef LLVMX86MMXType (void)
LLVMTypeRef LLVMFunctionType (LLVMTypeRef ReturnType, LLVMTypeRef *ParamTypes, unsigned ParamCount, LLVMBool IsVarArg)
LLVMBool LLVMIsFunctionVarArg (LLVMTypeRef FunctionTy)
LLVMTypeRef LLVMGetReturnType (LLVMTypeRef FunctionTy)
unsigned LLVMCountParamTypes (LLVMTypeRef FunctionTy)
void LLVMGetParamTypes (LLVMTypeRef FunctionTy, LLVMTypeRef *Dest)
LLVMTypeRef LLVMStructTypeInContext (LLVMContextRef C, LLVMTypeRef *ElementTypes, unsigned ElementCount, LLVMBool Packed)
LLVMTypeRef LLVMStructType (LLVMTypeRef *ElementTypes, unsigned ElementCount, LLVMBool Packed)
LLVMTypeRef LLVMStructCreateNamed (LLVMContextRef C, const char *Name)
const char * LLVMGetStructName (LLVMTypeRef Ty)
void LLVMStructSetBody (LLVMTypeRef StructTy, LLVMTypeRef *ElementTypes, unsigned ElementCount, LLVMBool Packed)
unsigned LLVMCountStructElementTypes (LLVMTypeRef StructTy)
void LLVMGetStructElementTypes (LLVMTypeRef StructTy, LLVMTypeRef *Dest)
LLVMBool LLVMIsPackedStruct (LLVMTypeRef StructTy)
LLVMBool LLVMIsOpaqueStruct (LLVMTypeRef StructTy)
LLVMTypeRef LLVMGetTypeByName (LLVMModuleRef M, const char *Name)
LLVMTypeRef LLVMArrayType (LLVMTypeRef ElementType, unsigned ElementCount)
LLVMTypeRef LLVMPointerType (LLVMTypeRef ElementType, unsigned AddressSpace)
LLVMTypeRef LLVMVectorType (LLVMTypeRef ElementType, unsigned ElementCount)
LLVMTypeRef LLVMGetElementType (LLVMTypeRef Ty)
unsigned LLVMGetArrayLength (LLVMTypeRef ArrayTy)
unsigned LLVMGetPointerAddressSpace (LLVMTypeRef PointerTy)
unsigned LLVMGetVectorSize (LLVMTypeRef VectorTy)
LLVMTypeRef LLVMVoidTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMLabelTypeInContext (LLVMContextRef C)
LLVMTypeRef LLVMVoidType (void)
LLVMTypeRef LLVMLabelType (void)
LLVMTypeRef LLVMTypeOf (LLVMValueRef Val)
const char * LLVMGetValueName (LLVMValueRef Val)
void LLVMSetValueName (LLVMValueRef Val, const char *Name)
void LLVMDumpValue (LLVMValueRef Val)
char * LLVMPrintValueToString (LLVMValueRef Val)
void LLVMReplaceAllUsesWith (LLVMValueRef OldVal, LLVMValueRef NewVal)
int LLVMHasMetadata (LLVMValueRef Inst)
LLVMValueRef LLVMGetMetadata (LLVMValueRef Inst, unsigned KindID)
static MDNode * extractMDNode (MetadataAsValue *MAV)
void LLVMSetMetadata (LLVMValueRef Inst, unsigned KindID, LLVMValueRef Val)
LLVMValueRef LLVMIsAMDNode (LLVMValueRef Val)
LLVMValueRef LLVMIsAMDString (LLVMValueRef Val)
LLVMUseRef LLVMGetFirstUse (LLVMValueRef Val)
LLVMUseRef LLVMGetNextUse (LLVMUseRef U)
LLVMValueRef LLVMGetUser (LLVMUseRef U)
LLVMValueRef LLVMGetUsedValue (LLVMUseRef U)
static LLVMValueRef getMDNodeOperandImpl (LLVMContext &Context, const MDNode *N, unsigned Index)
LLVMValueRef LLVMGetOperand (LLVMValueRef Val, unsigned Index)
LLVMUseRef LLVMGetOperandUse (LLVMValueRef Val, unsigned Index)
void LLVMSetOperand (LLVMValueRef Val, unsigned Index, LLVMValueRef Op)
int LLVMGetNumOperands (LLVMValueRef Val)
LLVMValueRef LLVMConstNull (LLVMTypeRef Ty)
LLVMValueRef LLVMConstAllOnes (LLVMTypeRef Ty)
LLVMValueRef LLVMGetUndef (LLVMTypeRef Ty)
LLVMBool LLVMIsConstant (LLVMValueRef Ty)
LLVMBool LLVMIsNull (LLVMValueRef Val)
LLVMBool LLVMIsUndef (LLVMValueRef Val)
LLVMValueRef LLVMConstPointerNull (LLVMTypeRef Ty)
LLVMValueRef LLVMMDStringInContext (LLVMContextRef C, const char *Str, unsigned SLen)
LLVMValueRef LLVMMDString (const char *Str, unsigned SLen)
LLVMValueRef LLVMMDNodeInContext (LLVMContextRef C, LLVMValueRef *Vals, unsigned Count)
LLVMValueRef LLVMMDNode (LLVMValueRef *Vals, unsigned Count)
const char * LLVMGetMDString (LLVMValueRef V, unsigned *Len)
unsigned LLVMGetMDNodeNumOperands (LLVMValueRef V)
void LLVMGetMDNodeOperands (LLVMValueRef V, LLVMValueRef *Dest)
unsigned LLVMGetNamedMetadataNumOperands (LLVMModuleRef M, const char *name)
void LLVMGetNamedMetadataOperands (LLVMModuleRef M, const char *name, LLVMValueRef *Dest)
void LLVMAddNamedMetadataOperand (LLVMModuleRef M, const char *name, LLVMValueRef Val)
LLVMValueRef LLVMConstInt (LLVMTypeRef IntTy, unsigned long long N, LLVMBool SignExtend)
LLVMValueRef LLVMConstIntOfArbitraryPrecision (LLVMTypeRef IntTy, unsigned NumWords, const uint64_t Words[])
LLVMValueRef LLVMConstIntOfString (LLVMTypeRef IntTy, const char Str[], uint8_t Radix)
LLVMValueRef LLVMConstIntOfStringAndSize (LLVMTypeRef IntTy, const char Str[], unsigned SLen, uint8_t Radix)
LLVMValueRef LLVMConstReal (LLVMTypeRef RealTy, double N)
LLVMValueRef LLVMConstRealOfString (LLVMTypeRef RealTy, const char *Text)
LLVMValueRef LLVMConstRealOfStringAndSize (LLVMTypeRef RealTy, const char Str[], unsigned SLen)
unsigned long long LLVMConstIntGetZExtValue (LLVMValueRef ConstantVal)
long long LLVMConstIntGetSExtValue (LLVMValueRef ConstantVal)
double LLVMConstRealGetDouble (LLVMValueRef ConstantVal, LLVMBool *LosesInfo)
LLVMValueRef LLVMConstStringInContext (LLVMContextRef C, const char *Str, unsigned Length, LLVMBool DontNullTerminate)
LLVMValueRef LLVMConstStructInContext (LLVMContextRef C, LLVMValueRef *ConstantVals, unsigned Count, LLVMBool Packed)
LLVMValueRef LLVMConstString (const char *Str, unsigned Length, LLVMBool DontNullTerminate)
LLVMValueRef LLVMGetElementAsConstant (LLVMValueRef c, unsigned idx)
LLVMBool LLVMIsConstantString (LLVMValueRef c)
const char * LLVMGetAsString (LLVMValueRef c, size_t *Length)
LLVMValueRef LLVMConstArray (LLVMTypeRef ElementTy, LLVMValueRef *ConstantVals, unsigned Length)
LLVMValueRef LLVMConstStruct (LLVMValueRef *ConstantVals, unsigned Count, LLVMBool Packed)
LLVMValueRef LLVMConstNamedStruct (LLVMTypeRef StructTy, LLVMValueRef *ConstantVals, unsigned Count)
LLVMValueRef LLVMConstVector (LLVMValueRef *ScalarConstantVals, unsigned Size)
static LLVMOpcode map_to_llvmopcode (int opcode)
static int map_from_llvmopcode (LLVMOpcode code)
LLVMOpcode LLVMGetConstOpcode (LLVMValueRef ConstantVal)
LLVMValueRef LLVMAlignOf (LLVMTypeRef Ty)
LLVMValueRef LLVMSizeOf (LLVMTypeRef Ty)
LLVMValueRef LLVMConstNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstNSWNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstNUWNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstFNeg (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstNot (LLVMValueRef ConstantVal)
LLVMValueRef LLVMConstAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNSWAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNUWAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFAdd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNSWSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNUWSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFSub (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNSWMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstNUWMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFMul (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstUDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstSDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstExactSDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFDiv (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstURem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstSRem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFRem (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstAnd (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstOr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstXor (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstICmp (LLVMIntPredicate Predicate, LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstFCmp (LLVMRealPredicate Predicate, LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstShl (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstLShr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstAShr (LLVMValueRef LHSConstant, LLVMValueRef RHSConstant)
LLVMValueRef LLVMConstGEP (LLVMValueRef ConstantVal, LLVMValueRef *ConstantIndices, unsigned NumIndices)
LLVMValueRef LLVMConstInBoundsGEP (LLVMValueRef ConstantVal, LLVMValueRef *ConstantIndices, unsigned NumIndices)
LLVMValueRef LLVMConstTrunc (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstZExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPTrunc (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPExt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstUIToFP (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSIToFP (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPToUI (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstFPToSI (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstPtrToInt (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstIntToPtr (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstAddrSpaceCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstZExtOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSExtOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstTruncOrBitCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstPointerCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstIntCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType, LLVMBool isSigned)
LLVMValueRef LLVMConstFPCast (LLVMValueRef ConstantVal, LLVMTypeRef ToType)
LLVMValueRef LLVMConstSelect (LLVMValueRef ConstantCondition, LLVMValueRef ConstantIfTrue, LLVMValueRef ConstantIfFalse)
LLVMValueRef LLVMConstExtractElement (LLVMValueRef VectorConstant, LLVMValueRef IndexConstant)
LLVMValueRef LLVMConstInsertElement (LLVMValueRef VectorConstant, LLVMValueRef ElementValueConstant, LLVMValueRef IndexConstant)
LLVMValueRef LLVMConstShuffleVector (LLVMValueRef VectorAConstant, LLVMValueRef VectorBConstant, LLVMValueRef MaskConstant)
LLVMValueRef LLVMConstExtractValue (LLVMValueRef AggConstant, unsigned *IdxList, unsigned NumIdx)
LLVMValueRef LLVMConstInsertValue (LLVMValueRef AggConstant, LLVMValueRef ElementValueConstant, unsigned *IdxList, unsigned NumIdx)
LLVMValueRef LLVMConstInlineAsm (LLVMTypeRef Ty, const char *AsmString, const char *Constraints, LLVMBool HasSideEffects, LLVMBool IsAlignStack)
LLVMValueRef LLVMBlockAddress (LLVMValueRef F, LLVMBasicBlockRef BB)
LLVMModuleRef LLVMGetGlobalParent (LLVMValueRef Global)
LLVMBool LLVMIsDeclaration (LLVMValueRef Global)
LLVMLinkage LLVMGetLinkage (LLVMValueRef Global)
void LLVMSetLinkage (LLVMValueRef Global, LLVMLinkage Linkage)
const char * LLVMGetSection (LLVMValueRef Global)
void LLVMSetSection (LLVMValueRef Global, const char *Section)
LLVMVisibility LLVMGetVisibility (LLVMValueRef Global)
void LLVMSetVisibility (LLVMValueRef Global, LLVMVisibility Viz)
LLVMDLLStorageClass LLVMGetDLLStorageClass (LLVMValueRef Global)
void LLVMSetDLLStorageClass (LLVMValueRef Global, LLVMDLLStorageClass Class)
LLVMBool LLVMHasUnnamedAddr (LLVMValueRef Global)
void LLVMSetUnnamedAddr (LLVMValueRef Global, LLVMBool HasUnnamedAddr)
unsigned LLVMGetAlignment (LLVMValueRef V)
void LLVMSetAlignment (LLVMValueRef V, unsigned Bytes)
LLVMValueRef LLVMAddGlobal (LLVMModuleRef M, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMAddGlobalInAddressSpace (LLVMModuleRef M, LLVMTypeRef Ty, const char *Name, unsigned AddressSpace)
LLVMValueRef LLVMGetNamedGlobal (LLVMModuleRef M, const char *Name)
LLVMValueRef LLVMGetFirstGlobal (LLVMModuleRef M)
LLVMValueRef LLVMGetLastGlobal (LLVMModuleRef M)
LLVMValueRef LLVMGetNextGlobal (LLVMValueRef GlobalVar)
LLVMValueRef LLVMGetPreviousGlobal (LLVMValueRef GlobalVar)
void LLVMDeleteGlobal (LLVMValueRef GlobalVar)
LLVMValueRef LLVMGetInitializer (LLVMValueRef GlobalVar)
void LLVMSetInitializer (LLVMValueRef GlobalVar, LLVMValueRef ConstantVal)
LLVMBool LLVMIsThreadLocal (LLVMValueRef GlobalVar)
void LLVMSetThreadLocal (LLVMValueRef GlobalVar, LLVMBool IsThreadLocal)
LLVMBool LLVMIsGlobalConstant (LLVMValueRef GlobalVar)
void LLVMSetGlobalConstant (LLVMValueRef GlobalVar, LLVMBool IsConstant)
LLVMThreadLocalMode LLVMGetThreadLocalMode (LLVMValueRef GlobalVar)
void LLVMSetThreadLocalMode (LLVMValueRef GlobalVar, LLVMThreadLocalMode Mode)
LLVMBool LLVMIsExternallyInitialized (LLVMValueRef GlobalVar)
void LLVMSetExternallyInitialized (LLVMValueRef GlobalVar, LLVMBool IsExtInit)
LLVMValueRef LLVMAddAlias (LLVMModuleRef M, LLVMTypeRef Ty, LLVMValueRef Aliasee, const char *Name)
LLVMValueRef LLVMAddFunction (LLVMModuleRef M, const char *Name, LLVMTypeRef FunctionTy)
LLVMValueRef LLVMGetNamedFunction (LLVMModuleRef M, const char *Name)
LLVMValueRef LLVMGetFirstFunction (LLVMModuleRef M)
LLVMValueRef LLVMGetLastFunction (LLVMModuleRef M)
LLVMValueRef LLVMGetNextFunction (LLVMValueRef Fn)
LLVMValueRef LLVMGetPreviousFunction (LLVMValueRef Fn)
void LLVMDeleteFunction (LLVMValueRef Fn)
unsigned LLVMGetIntrinsicID (LLVMValueRef Fn)
unsigned LLVMGetFunctionCallConv (LLVMValueRef Fn)
void LLVMSetFunctionCallConv (LLVMValueRef Fn, unsigned CC)
const char * LLVMGetGC (LLVMValueRef Fn)
void LLVMSetGC (LLVMValueRef Fn, const char *GC)
void LLVMAddFunctionAttr (LLVMValueRef Fn, LLVMAttribute PA)
void LLVMAddTargetDependentFunctionAttr (LLVMValueRef Fn, const char *A, const char *V)
void LLVMRemoveFunctionAttr (LLVMValueRef Fn, LLVMAttribute PA)
LLVMAttribute LLVMGetFunctionAttr (LLVMValueRef Fn)
unsigned LLVMCountParams (LLVMValueRef FnRef)
void LLVMGetParams (LLVMValueRef FnRef, LLVMValueRef *ParamRefs)
LLVMValueRef LLVMGetParam (LLVMValueRef FnRef, unsigned index)
LLVMValueRef LLVMGetParamParent (LLVMValueRef V)
LLVMValueRef LLVMGetFirstParam (LLVMValueRef Fn)
LLVMValueRef LLVMGetLastParam (LLVMValueRef Fn)
LLVMValueRef LLVMGetNextParam (LLVMValueRef Arg)
LLVMValueRef LLVMGetPreviousParam (LLVMValueRef Arg)
void LLVMAddAttribute (LLVMValueRef Arg, LLVMAttribute PA)
void LLVMRemoveAttribute (LLVMValueRef Arg, LLVMAttribute PA)
LLVMAttribute LLVMGetAttribute (LLVMValueRef Arg)
void LLVMSetParamAlignment (LLVMValueRef Arg, unsigned align)
LLVMValueRef LLVMBasicBlockAsValue (LLVMBasicBlockRef BB)
LLVMBool LLVMValueIsBasicBlock (LLVMValueRef Val)
LLVMBasicBlockRef LLVMValueAsBasicBlock (LLVMValueRef Val)
LLVMValueRef LLVMGetBasicBlockParent (LLVMBasicBlockRef BB)
LLVMValueRef LLVMGetBasicBlockTerminator (LLVMBasicBlockRef BB)
unsigned LLVMCountBasicBlocks (LLVMValueRef FnRef)
void LLVMGetBasicBlocks (LLVMValueRef FnRef, LLVMBasicBlockRef *BasicBlocksRefs)
LLVMBasicBlockRef LLVMGetEntryBasicBlock (LLVMValueRef Fn)
LLVMBasicBlockRef LLVMGetFirstBasicBlock (LLVMValueRef Fn)
LLVMBasicBlockRef LLVMGetLastBasicBlock (LLVMValueRef Fn)
LLVMBasicBlockRef LLVMGetNextBasicBlock (LLVMBasicBlockRef BB)
LLVMBasicBlockRef LLVMGetPreviousBasicBlock (LLVMBasicBlockRef BB)
LLVMBasicBlockRef LLVMAppendBasicBlockInContext (LLVMContextRef C, LLVMValueRef FnRef, const char *Name)
LLVMBasicBlockRef LLVMAppendBasicBlock (LLVMValueRef FnRef, const char *Name)
LLVMBasicBlockRef LLVMInsertBasicBlockInContext (LLVMContextRef C, LLVMBasicBlockRef BBRef, const char *Name)
LLVMBasicBlockRef LLVMInsertBasicBlock (LLVMBasicBlockRef BBRef, const char *Name)
void LLVMDeleteBasicBlock (LLVMBasicBlockRef BBRef)
void LLVMRemoveBasicBlockFromParent (LLVMBasicBlockRef BBRef)
void LLVMMoveBasicBlockBefore (LLVMBasicBlockRef BB, LLVMBasicBlockRef MovePos)
void LLVMMoveBasicBlockAfter (LLVMBasicBlockRef BB, LLVMBasicBlockRef MovePos)
LLVMBasicBlockRef LLVMGetInstructionParent (LLVMValueRef Inst)
LLVMValueRef LLVMGetFirstInstruction (LLVMBasicBlockRef BB)
LLVMValueRef LLVMGetLastInstruction (LLVMBasicBlockRef BB)
LLVMValueRef LLVMGetNextInstruction (LLVMValueRef Inst)
LLVMValueRef LLVMGetPreviousInstruction (LLVMValueRef Inst)
void LLVMInstructionEraseFromParent (LLVMValueRef Inst)
LLVMIntPredicate LLVMGetICmpPredicate (LLVMValueRef Inst)
LLVMRealPredicate LLVMGetFCmpPredicate (LLVMValueRef Inst)
LLVMOpcode LLVMGetInstructionOpcode (LLVMValueRef Inst)
LLVMValueRef LLVMInstructionClone (LLVMValueRef Inst)
unsigned LLVMGetInstructionCallConv (LLVMValueRef Instr)
void LLVMSetInstructionCallConv (LLVMValueRef Instr, unsigned CC)
void LLVMAddInstrAttribute (LLVMValueRef Instr, unsigned index, LLVMAttribute PA)
void LLVMRemoveInstrAttribute (LLVMValueRef Instr, unsigned index, LLVMAttribute PA)
void LLVMSetInstrParamAlignment (LLVMValueRef Instr, unsigned index, unsigned align)
LLVMBool LLVMIsTailCall (LLVMValueRef Call)
void LLVMSetTailCall (LLVMValueRef Call, LLVMBool isTailCall)
unsigned LLVMGetNumSuccessors (LLVMValueRef Term)
LLVMBasicBlockRef LLVMGetSuccessor (LLVMValueRef Term, unsigned i)
void LLVMSetSuccessor (LLVMValueRef Term, unsigned i, LLVMBasicBlockRef block)
LLVMBool LLVMIsConditional (LLVMValueRef Branch)
LLVMValueRef LLVMGetCondition (LLVMValueRef Branch)
void LLVMSetCondition (LLVMValueRef Branch, LLVMValueRef Cond)
LLVMBasicBlockRef LLVMGetSwitchDefaultDest (LLVMValueRef Switch)
void LLVMAddIncoming (LLVMValueRef PhiNode, LLVMValueRef *IncomingValues, LLVMBasicBlockRef *IncomingBlocks, unsigned Count)
unsigned LLVMCountIncoming (LLVMValueRef PhiNode)
LLVMValueRef LLVMGetIncomingValue (LLVMValueRef PhiNode, unsigned Index)
LLVMBasicBlockRef LLVMGetIncomingBlock (LLVMValueRef PhiNode, unsigned Index)
LLVMBuilderRef LLVMCreateBuilderInContext (LLVMContextRef C)
LLVMBuilderRef LLVMCreateBuilder (void)
void LLVMPositionBuilder (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Instr)
void LLVMPositionBuilderBefore (LLVMBuilderRef Builder, LLVMValueRef Instr)
void LLVMPositionBuilderAtEnd (LLVMBuilderRef Builder, LLVMBasicBlockRef Block)
LLVMBasicBlockRef LLVMGetInsertBlock (LLVMBuilderRef Builder)
void LLVMClearInsertionPosition (LLVMBuilderRef Builder)
void LLVMInsertIntoBuilder (LLVMBuilderRef Builder, LLVMValueRef Instr)
void LLVMInsertIntoBuilderWithName (LLVMBuilderRef Builder, LLVMValueRef Instr, const char *Name)
void LLVMDisposeBuilder (LLVMBuilderRef Builder)
void LLVMSetCurrentDebugLocation (LLVMBuilderRef Builder, LLVMValueRef L)
LLVMValueRef LLVMGetCurrentDebugLocation (LLVMBuilderRef Builder)
void LLVMSetInstDebugLocation (LLVMBuilderRef Builder, LLVMValueRef Inst)
LLVMValueRef LLVMBuildRetVoid (LLVMBuilderRef B)
LLVMValueRef LLVMBuildRet (LLVMBuilderRef B, LLVMValueRef V)
LLVMValueRef LLVMBuildAggregateRet (LLVMBuilderRef B, LLVMValueRef *RetVals, unsigned N)
LLVMValueRef LLVMBuildBr (LLVMBuilderRef B, LLVMBasicBlockRef Dest)
LLVMValueRef LLVMBuildCondBr (LLVMBuilderRef B, LLVMValueRef If, LLVMBasicBlockRef Then, LLVMBasicBlockRef Else)
LLVMValueRef LLVMBuildSwitch (LLVMBuilderRef B, LLVMValueRef V, LLVMBasicBlockRef Else, unsigned NumCases)
LLVMValueRef LLVMBuildIndirectBr (LLVMBuilderRef B, LLVMValueRef Addr, unsigned NumDests)
LLVMValueRef LLVMBuildInvoke (LLVMBuilderRef B, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char *Name)
LLVMValueRef LLVMBuildLandingPad (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PersFn, unsigned NumClauses, const char *Name)
LLVMValueRef LLVMBuildResume (LLVMBuilderRef B, LLVMValueRef Exn)
LLVMValueRef LLVMBuildUnreachable (LLVMBuilderRef B)
void LLVMAddCase (LLVMValueRef Switch, LLVMValueRef OnVal, LLVMBasicBlockRef Dest)
void LLVMAddDestination (LLVMValueRef IndirectBr, LLVMBasicBlockRef Dest)
void LLVMAddClause (LLVMValueRef LandingPad, LLVMValueRef ClauseVal)
void LLVMSetCleanup (LLVMValueRef LandingPad, LLVMBool Val)
LLVMValueRef LLVMBuildAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildUDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildExactSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildURem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildShl (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildLShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildAShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildAnd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildOr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildXor (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildBinOp (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNSWNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNUWNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildFNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNot (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildArrayMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildArrayAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildFree (LLVMBuilderRef B, LLVMValueRef PointerVal)
LLVMValueRef LLVMBuildLoad (LLVMBuilderRef B, LLVMValueRef PointerVal, const char *Name)
LLVMValueRef LLVMBuildStore (LLVMBuilderRef B, LLVMValueRef Val, LLVMValueRef PointerVal)
static AtomicOrdering mapFromLLVMOrdering (LLVMAtomicOrdering Ordering)
LLVMValueRef LLVMBuildFence (LLVMBuilderRef B, LLVMAtomicOrdering Ordering, LLVMBool isSingleThread, const char *Name)
LLVMValueRef LLVMBuildGEP (LLVMBuilderRef B, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVMValueRef LLVMBuildInBoundsGEP (LLVMBuilderRef B, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVMValueRef LLVMBuildStructGEP (LLVMBuilderRef B, LLVMValueRef Pointer, unsigned Idx, const char *Name)
LLVMValueRef LLVMBuildGlobalString (LLVMBuilderRef B, const char *Str, const char *Name)
LLVMValueRef LLVMBuildGlobalStringPtr (LLVMBuilderRef B, const char *Str, const char *Name)
LLVMBool LLVMGetVolatile (LLVMValueRef MemAccessInst)
void LLVMSetVolatile (LLVMValueRef MemAccessInst, LLVMBool isVolatile)
LLVMValueRef LLVMBuildTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildZExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPToUI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPToSI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildUIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildPtrToInt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildIntToPtr (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildAddrSpaceCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildZExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildTruncOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildCast (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildPointerCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildIntCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildICmp (LLVMBuilderRef B, LLVMIntPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFCmp (LLVMBuilderRef B, LLVMRealPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildPhi (LLVMBuilderRef B, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildCall (LLVMBuilderRef B, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVMValueRef LLVMBuildSelect (LLVMBuilderRef B, LLVMValueRef If, LLVMValueRef Then, LLVMValueRef Else, const char *Name)
LLVMValueRef LLVMBuildVAArg (LLVMBuilderRef B, LLVMValueRef List, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildExtractElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef Index, const char *Name)
LLVMValueRef LLVMBuildInsertElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef EltVal, LLVMValueRef Index, const char *Name)
LLVMValueRef LLVMBuildShuffleVector (LLVMBuilderRef B, LLVMValueRef V1, LLVMValueRef V2, LLVMValueRef Mask, const char *Name)
LLVMValueRef LLVMBuildExtractValue (LLVMBuilderRef B, LLVMValueRef AggVal, unsigned Index, const char *Name)
LLVMValueRef LLVMBuildInsertValue (LLVMBuilderRef B, LLVMValueRef AggVal, LLVMValueRef EltVal, unsigned Index, const char *Name)
LLVMValueRef LLVMBuildIsNull (LLVMBuilderRef B, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildIsNotNull (LLVMBuilderRef B, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildPtrDiff (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildAtomicRMW (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, LLVMBool singleThread)
LLVMModuleProviderRef LLVMCreateModuleProviderForExistingModule (LLVMModuleRef M)
void LLVMDisposeModuleProvider (LLVMModuleProviderRef MP)
LLVMBool LLVMCreateMemoryBufferWithContentsOfFile (const char *Path, LLVMMemoryBufferRef *OutMemBuf, char **OutMessage)
LLVMBool LLVMCreateMemoryBufferWithSTDIN (LLVMMemoryBufferRef *OutMemBuf, char **OutMessage)
LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRange (const char *InputData, size_t InputDataLength, const char *BufferName, LLVMBool RequiresNullTerminator)
LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRangeCopy (const char *InputData, size_t InputDataLength, const char *BufferName)
const char * LLVMGetBufferStart (LLVMMemoryBufferRef MemBuf)
size_t LLVMGetBufferSize (LLVMMemoryBufferRef MemBuf)
void LLVMDisposeMemoryBuffer (LLVMMemoryBufferRef MemBuf)
LLVMPassRegistryRef LLVMGetGlobalPassRegistry (void)
LLVMPassManagerRef LLVMCreatePassManager ()
LLVMPassManagerRef LLVMCreateFunctionPassManagerForModule (LLVMModuleRef M)
LLVMPassManagerRef LLVMCreateFunctionPassManager (LLVMModuleProviderRef P)
LLVMBool LLVMRunPassManager (LLVMPassManagerRef PM, LLVMModuleRef M)
LLVMBool LLVMInitializeFunctionPassManager (LLVMPassManagerRef FPM)
LLVMBool LLVMRunFunctionPassManager (LLVMPassManagerRef FPM, LLVMValueRef F)
LLVMBool LLVMFinalizeFunctionPassManager (LLVMPassManagerRef FPM)
void LLVMDisposePassManager (LLVMPassManagerRef PM)
LLVMBool LLVMStartMultithreaded ()
void LLVMStopMultithreaded ()
LLVMBool LLVMIsMultithreaded ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ir"
Definition at line 45 of file Core.cpp.
HANDLE_INST [1/2]
#define HANDLE_INST (num, opc, clas)
Value:
case num: return LLVM##opc;
HANDLE_INST [2/2]
#define HANDLE_INST (num, opc, clas)
Value:
case LLVM##opc: return num;
LLVM_DEFINE_VALUE_CAST
#define LLVM_DEFINE_VALUE_CAST (name)
Value:
  LLVMValueRef LLVMIsA##name(LLVMValueRef Val) {                           \
    return wrap(static_cast<Value*>(dyn_cast_or_null<name>(unwrap(Val)))); \
  }
Definition at line 588 of file Core.cpp.
Function Documentation
extractMDNode()
MDNode * extractMDNode (MetadataAsValue * MAV) static
Definition at line 569 of file Core.cpp.
References llvm::dyn_cast(), llvm::MDNode::get(), llvm::Value::getContext(), llvm::MetadataAsValue::getMetadata(), llvm::isa(), and N.
Referenced by LLVMAddNamedMetadataOperand(), and LLVMSetMetadata().
getMDNodeOperandImpl()
LLVMValueRef getMDNodeOperandImpl (LLVMContext & Context, const MDNode * N, unsigned Index) static
Definition at line 636 of file Core.cpp.
References llvm::dyn_cast(), llvm::MetadataAsValue::get(), N, and llvm::wrap().
Referenced by LLVMGetMDNodeOperands(), and LLVMGetOperand().
LLVMConstIntOfString()
LLVMValueRef LLVMConstIntOfString (LLVMTypeRef IntTy, const char Str[], uint8_t Radix)
Definition at line 831 of file Core.cpp.
References llvm::ConstantInt::get(), llvm::unwrap(), and llvm::wrap().
LLVMConstIntOfStringAndSize()
LLVMValueRef LLVMConstIntOfStringAndSize (LLVMTypeRef IntTy, const char Str[], unsigned SLen, uint8_t Radix)
Definition at line 837 of file Core.cpp.
References llvm::ConstantInt::get(), llvm::unwrap(), and llvm::wrap().
LLVMConstRealOfStringAndSize()
LLVMValueRef LLVMConstRealOfStringAndSize (LLVMTypeRef RealTy, const char Str[], unsigned SLen)
Definition at line 851 of file Core.cpp.
References llvm::ConstantFP::get(), llvm::unwrap(), and llvm::wrap().
map_from_llvmopcode()
int map_from_llvmopcode (LLVMOpcode code) static
Definition at line 961 of file Core.cpp.
References llvm_unreachable.
Referenced by LLVMBuildBinOp(), and LLVMBuildCast().
map_to_llvmopcode()
LLVMOpcode map_to_llvmopcode (int opcode) static
Definition at line 951 of file Core.cpp.
References llvm_unreachable.
Referenced by LLVMGetConstOpcode(), and LLVMGetInstructionOpcode().
mapFromLLVMOrdering()
AtomicOrdering mapFromLLVMOrdering (LLVMAtomicOrdering Ordering) static
Definition at line 2482 of file Core.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm_unreachable, LLVMAtomicOrderingAcquire, LLVMAtomicOrderingAcquireRelease, LLVMAtomicOrderingMonotonic, LLVMAtomicOrderingNotAtomic, LLVMAtomicOrderingRelease, LLVMAtomicOrderingSequentiallyConsistent, LLVMAtomicOrderingUnordered, llvm::Monotonic, llvm::NotAtomic, llvm::Release, llvm::SequentiallyConsistent, and llvm::Unordered.
Referenced by LLVMBuildAtomicRMW(), and LLVMBuildFence().