LLVM: CostModel.cpp File Reference
LLVM API Documentation
CostModel.cpp File Reference
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define CM_NAME "cost-model"
#define DEBUG_TYPE CM_NAME
Functions
static bool isReverseVectorMask (SmallVectorImpl< int > &Mask)
static bool isAlternateVectorMask (SmallVectorImpl< int > &Mask)
static TargetTransformInfo::OperandValueKind getOperandInfo (Value *V)
static bool matchPairwiseShuffleMask (ShuffleVectorInst *SI, bool IsLeft, unsigned Level)
static bool matchPairwiseReductionAtLevel (const BinaryOperator *BinOp, unsigned Level, unsigned NumLevels)
static bool matchPairwiseReduction (const ExtractElementInst *ReduxRoot, unsigned &Opcode, Type *&Ty)
static std::pair< Value *, ShuffleVectorInst * > getShuffleAndOtherOprd (BinaryOperator *B)
static bool matchVectorSplittingReduction (const ExtractElementInst *ReduxRoot, unsigned &Opcode, Type *&Ty)
Variables
static cl::opt< bool > EnableReduxCost ("costmodel-reduxcost", cl::init(false), cl::Hidden, cl::desc("Recognize reduction patterns."))
static const char cm_name [] = "Cost Model Analysis"
Macro Definition Documentation
CM_NAME
#define CM_NAME "cost-model"
Definition at line 33 of file CostModel.cpp.
DEBUG_TYPE
#define DEBUG_TYPE CM_NAME
Definition at line 34 of file CostModel.cpp.
Function Documentation
getOperandInfo()
TargetTransformInfo::OperandValueKind getOperandInfo (Value * V) static
Definition at line 123 of file CostModel.cpp.
References llvm::cast(), llvm::isa(), llvm::TargetTransformInfo::OK_AnyValue, llvm::TargetTransformInfo::OK_NonUniformConstantValue, and llvm::TargetTransformInfo::OK_UniformConstantValue.
getShuffleAndOtherOprd()
std::pair< Value *, ShuffleVectorInst * > getShuffleAndOtherOprd (BinaryOperator * B) static
Definition at line 291 of file CostModel.cpp.
References llvm::dyn_cast(), and llvm::User::getOperand().
Referenced by matchVectorSplittingReduction().
isAlternateVectorMask()
bool isAlternateVectorMask (SmallVectorImpl< int > & Mask) static
Definition at line 98 of file CostModel.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
isReverseVectorMask()
bool isReverseVectorMask (SmallVectorImpl< int > & Mask) static
Definition at line 91 of file CostModel.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
matchPairwiseReduction()
bool matchPairwiseReduction (const ExtractElementInst * ReduxRoot, unsigned & Opcode, Type *& Ty) static
Definition at line 241 of file CostModel.cpp.
References llvm::dyn_cast(), EnableReduxCost, llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::ConstantInt::getZExtValue(), llvm::isPowerOf2_32(), llvm::Log2_32(), and matchPairwiseReductionAtLevel().
matchPairwiseReductionAtLevel()
bool matchPairwiseReductionAtLevel (const BinaryOperator * BinOp, unsigned Level, unsigned NumLevels) static
Definition at line 160 of file CostModel.cpp.
References llvm::dyn_cast(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::isVectorTy(), matchPairwiseReductionAtLevel(), and matchPairwiseShuffleMask().
Referenced by matchPairwiseReduction(), and matchPairwiseReductionAtLevel().
matchPairwiseShuffleMask()
bool matchPairwiseShuffleMask (ShuffleVectorInst * SI, bool IsLeft, unsigned Level) static
Definition at line 137 of file CostModel.cpp.
Referenced by matchPairwiseReductionAtLevel().
matchVectorSplittingReduction()
bool matchVectorSplittingReduction (const ExtractElementInst * ReduxRoot, unsigned & Opcode, Type *& Ty) static
Definition at line 304 of file CostModel.cpp.
References llvm::dyn_cast(), EnableReduxCost, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), getShuffleAndOtherOprd(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::ConstantInt::getZExtValue(), and llvm::isPowerOf2_32().
Variable Documentation
cm_name
const char cm_name[] = "Cost Model Analysis" static
Definition at line 70 of file CostModel.cpp.
EnableReduxCost
cl::opt< bool > EnableReduxCost("costmodel-reduxcost", cl::init(false), cl::Hidden, cl::desc("Recognize reduction patterns.")) ("costmodel-reduxcost" , cl::init(false) , cl::Hidden , cl::desc("Recognize reduction patterns.")) static
Referenced by matchPairwiseReduction(), and matchVectorSplittingReduction().