LLVM: CoverageMappingReader.cpp File Reference
LLVM API Documentation
CoverageMappingReader.cpp File Reference
#include "llvm/ProfileData/CoverageMappingReader.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/LEB128.h"
Macros
#define DEBUG_TYPE "coverage-mapping"
Functions
template<typename T>
std::error_code readCoverageMappingData (SectionData &ProfileNames, StringRef Data, std::vector< ObjectFileCoverageMappingReader::ProfileMappingRecord > &Records, std::vector< StringRef > &Filenames)
static std::error_code decodeTestingFormat (StringRef Data, SectionData &ProfileNames, StringRef &CoverageMapping)
Variables
static const unsigned EncodingExpansionRegionBit
static const char * TestingFormatMagic = "llvmcovmtestdata"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coverage-mapping"
Definition at line 25 of file CoverageMappingReader.cpp.
Function Documentation
decodeTestingFormat()
std::error_code decodeTestingFormat (StringRef Data, SectionData & ProfileNames, StringRef & CoverageMapping) static
Definition at line 432 of file CoverageMappingReader.cpp.
References llvm::StringRef::data(), llvm::decodeULEB128(), llvm::malformed, N, llvm::StringRef::size(), llvm::StringRef::substr(), llvm::success, TestingFormatMagic, and llvm::truncated.
readCoverageMappingData()
template<typename T> std::error_code readCoverageMappingData (SectionData & ProfileNames, StringRef Data, std::vector< ObjectFileCoverageMappingReader::ProfileMappingRecord > & Records, std::vector< StringRef > & Filenames)
Definition at line 353 of file CoverageMappingReader.cpp.
References llvm::coverage::CoverageMappingVersion1, llvm::StringRef::data(), llvm::StringRef::empty(), I, llvm::DenseSet< ValueT, ValueInfoT >::insert(), llvm::malformed, llvm::coverage::RawCoverageFilenamesReader::read(), llvm::StringRef::size(), llvm::StringRef::substr(), llvm::success, and llvm::unsupported_version.
Referenced by llvm::coverage::ObjectFileCoverageMappingReader::ObjectFileCoverageMappingReader(), and llvm::coverage::ObjectFileCoverageMappingReader::readHeader().
Variable Documentation
EncodingExpansionRegionBit
const unsigned EncodingExpansionRegionBit static
Initial value:
= 1
                                                   << Counter::EncodingTagBits
Definition at line 125 of file CoverageMappingReader.cpp.
TestingFormatMagic
const char* TestingFormatMagic = "llvmcovmtestdata" static
Definition at line 430 of file CoverageMappingReader.cpp.
Referenced by decodeTestingFormat(), and llvm::coverage::ObjectFileCoverageMappingReader::ObjectFileCoverageMappingReader().