LLVM: CppBackendTargetInfo.cpp File Reference
LLVM API Documentation
CppBackendTargetInfo.cpp File Reference
#include "CPPTargetMachine.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/TargetRegistry.h"
Functions
static bool CppBackend_TripleMatchQuality (Triple::ArchType Arch)
void LLVMInitializeCppBackendTargetInfo ()
void LLVMInitializeCppBackendTargetMC ()
Function Documentation
CppBackend_TripleMatchQuality()
bool CppBackend_TripleMatchQuality (Triple::ArchType Arch) static
Definition at line 17 of file CppBackendTargetInfo.cpp.
Referenced by LLVMInitializeCppBackendTargetInfo().
LLVMInitializeCppBackendTargetInfo()
void LLVMInitializeCppBackendTargetInfo ()
Definition at line 23 of file CppBackendTargetInfo.cpp.
References CppBackend_TripleMatchQuality(), llvm::TargetRegistry::RegisterTarget(), and llvm::TheCppBackendTarget.
LLVMInitializeCppBackendTargetMC()
void LLVMInitializeCppBackendTargetMC ()
Definition at line 29 of file CppBackendTargetInfo.cpp.