LLVM: CrashRecoveryContext.cpp File Reference
LLVM API Documentation
CrashRecoveryContext.cpp File Reference
#include "llvm/Support/CrashRecoveryContext.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Config/config.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/ThreadLocal.h"
#include <cstdio>
#include <setjmp.h>
#include <signal.h>
Functions
static void CrashRecoverySignalHandler (int Signal)
static void setThreadBackgroundPriority ()
static bool hasThreadBackgroundPriority ()
static void RunSafelyOnThread_Dispatch (void *UserData)
Variables
static ManagedStatic< sys::Mutex > gCrashRecoveryContextMutex
static bool gCrashRecoveryEnabled = false
static ManagedStatic< sys::ThreadLocal< const CrashRecoveryContextCleanup > > tlIsRecoveringFromCrash
static const int Signals []
static const unsigned NumSignals = sizeof(Signals) / sizeof(Signals[0])
static struct sigaction PrevActions [NumSignals]
Function Documentation
CrashRecoverySignalHandler()
void CrashRecoverySignalHandler (int Signal) static
Definition at line 240 of file CrashRecoveryContext.cpp.
References llvm::CrashRecoveryContext::Disable().
Referenced by llvm::CrashRecoveryContext::Enable().
hasThreadBackgroundPriority()
bool hasThreadBackgroundPriority () static
Definition at line 342 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::RunSafelyOnThread().
RunSafelyOnThread_Dispatch()
void RunSafelyOnThread_Dispatch (void * UserData) static
Definition at line 359 of file CrashRecoveryContext.cpp.
References setThreadBackgroundPriority().
Referenced by llvm::CrashRecoveryContext::RunSafelyOnThread().
setThreadBackgroundPriority()
void setThreadBackgroundPriority () static
Definition at line 336 of file CrashRecoveryContext.cpp.
Referenced by RunSafelyOnThread_Dispatch().
Variable Documentation
gCrashRecoveryContextMutex
ManagedStatic<sys::Mutex> gCrashRecoveryContextMutex static
Definition at line 67 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::Disable(), and llvm::CrashRecoveryContext::Enable().
gCrashRecoveryEnabled
bool gCrashRecoveryEnabled = false static
Definition at line 68 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::Disable(), llvm::CrashRecoveryContext::Enable(), llvm::CrashRecoveryContext::GetCurrent(), and llvm::CrashRecoveryContext::RunSafely().
NumSignals
const unsigned NumSignals = sizeof(Signals) / sizeof(Signals[0]) static
Definition at line 237 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::Disable(), and llvm::CrashRecoveryContext::Enable().
PrevActions
struct sigaction PrevActions[NumSignals] static
Definition at line 238 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::Disable(), and llvm::CrashRecoveryContext::Enable().
Signals
const int Signals[] static
Initial value:
=
    { SIGABRT, SIGBUS, SIGFPE, SIGILL, SIGSEGV, SIGTRAP }
Definition at line 235 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::Disable(), and llvm::CrashRecoveryContext::Enable().
tlIsRecoveringFromCrash
ManagedStatic<sys::ThreadLocal<const CrashRecoveryContextCleanup> > tlIsRecoveringFromCrash static
Definition at line 71 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::isRecoveringFromCrash(), and llvm::CrashRecoveryContext::~CrashRecoveryContext().