LLVM: DataExtractor.cpp File Reference
LLVM API Documentation
DataExtractor.cpp File Reference
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/SwapByteOrder.h"
Functions
template<typename T>
static T getU (uint32_t *offset_ptr, const DataExtractor *de, bool isLittleEndian, const char *Data)
template<typename T>
static T * getUs (uint32_t *offset_ptr, T *dst, uint32_t count, const DataExtractor *de, bool isLittleEndian, const char *Data)
Function Documentation
getU()
template<typename T> T getU (uint32_t * offset_ptr, const DataExtractor * de, bool isLittleEndian, const char * Data) static
Definition at line 17 of file DataExtractor.cpp.
References llvm::sys::IsLittleEndianHost, llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::sys::swapByteOrder(), and T.
Referenced by llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), getUs(), and llvm::ScaledNumbers::multiply64().
getUs()
template<typename T> T * getUs (uint32_t * offset_ptr, T * dst, uint32_t count, const DataExtractor * de, bool isLittleEndian, const char * Data) static
Definition at line 33 of file DataExtractor.cpp.
References getU(), llvm::DataExtractor::isValidOffsetForDataOfSize(), and T.
Referenced by llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), and llvm::DataExtractor::getU8().