LLVM: DelaySlotFiller.cpp File Reference
LLVM API Documentation
DelaySlotFiller.cpp File Reference
#include "Sparc.h"
#include "SparcSubtarget.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "delay-slot-filler"
Functions
STATISTIC (FilledSlots, "Number of delay slots filled")
static bool combineRestoreADD (MachineBasicBlock::iterator RestoreMI, MachineBasicBlock::iterator AddMI, const TargetInstrInfo *TII)
static bool combineRestoreOR (MachineBasicBlock::iterator RestoreMI, MachineBasicBlock::iterator OrMI, const TargetInstrInfo *TII)
static bool combineRestoreSETHIi (MachineBasicBlock::iterator RestoreMI, MachineBasicBlock::iterator SetHiMI, const TargetInstrInfo *TII)
Variables
static cl::opt< bool > DisableDelaySlotFiller ("disable-sparc-delay-filler", cl::init(false), cl::desc("Disable the Sparc delay slot filler."), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "delay-slot-filler"
Definition at line 29 of file DelaySlotFiller.cpp.
Function Documentation
combineRestoreADD()
bool combineRestoreADD (MachineBasicBlock::iterator RestoreMI, MachineBasicBlock::iterator AddMI, const TargetInstrInfo * TII) static
Definition at line 361 of file DelaySlotFiller.cpp.
References llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setReg(), and TII.
combineRestoreOR()
bool combineRestoreOR (MachineBasicBlock::iterator RestoreMI, MachineBasicBlock::iterator OrMI, const TargetInstrInfo * TII) static
Definition at line 388 of file DelaySlotFiller.cpp.
References llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isImm(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setReg(), and TII.
combineRestoreSETHIi()
bool combineRestoreSETHIi (MachineBasicBlock::iterator RestoreMI, MachineBasicBlock::iterator SetHiMI, const TargetInstrInfo * TII) static
Definition at line 427 of file DelaySlotFiller.cpp.
References llvm::MachineOperand::ChangeToImmediate(), llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isImm(), llvm::isInt(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setReg(), and TII.
STATISTIC()
STATISTIC (FilledSlots , "Number of delay slots filled")
Variable Documentation
DisableDelaySlotFiller
cl::opt< bool > DisableDelaySlotFiller("disable-sparc-delay-filler", cl::init(false), cl::desc("Disable the Sparc delay slot filler."), cl::Hidden) ("disable-sparc-delay-filler" , cl::init(false) , cl::desc("Disable the Sparc delay slot filler.") , cl::Hidden) static