LLVM: DomPrinter.cpp File Reference
LLVM API Documentation
DomPrinter.cpp File Reference
#include "llvm/Analysis/DomPrinter.h"
#include "llvm/Analysis/DOTGraphTraitsPass.h"
#include "llvm/Analysis/PostDominators.h"
Classes
struct llvm::DOTGraphTraits< DomTreeNode * >
struct llvm::DOTGraphTraits< DominatorTree * >
struct llvm::DOTGraphTraits< PostDominatorTree * >
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Functions
INITIALIZE_PASS(DomViewer, "view-dom", "View dominance tree of function", false, false) char DomOnlyViewer INITIALIZE_PASS(DomOnlyViewer, "view-dom-only", "View dominance tree of function (with no function bodies)", false, false) char PostDomViewer INITIALIZE_PASS(PostDomViewer, "view-postdom", "View postdominance tree of function", false, false) char PostDomOnlyViewer INITIALIZE_PASS (PostDomOnlyViewer, "view-postdom-only", "View postdominance tree of function " "(with no function bodies)", false, false) namespace
INITIALIZE_PASS(DomPrinter, "dot-dom", "Print dominance tree of function to 'dot' file", false, false) char DomOnlyPrinter INITIALIZE_PASS(DomOnlyPrinter, "dot-dom-only", "Print dominance tree of function to 'dot' file " "(with no function bodies)", false, false) char PostDomPrinter INITIALIZE_PASS(PostDomPrinter, "dot-postdom", "Print postdominance tree of function to 'dot' file", false, false) char PostDomOnlyPrinter INITIALIZE_PASS (PostDomOnlyPrinter, "dot-postdom-only", "Print postdominance tree of function to 'dot' file " "(with no function bodies)", false, false) FunctionPass *llvm
Function Documentation
INITIALIZE_PASS() [1/2]
INITIALIZE_PASS(DomPrinter, "dot-dom", "Print dominance tree of function to 'dot' file", false, false) char DomOnlyPrinter INITIALIZE_PASS(DomOnlyPrinter, "dot-dom-only", "Print dominance tree of function to 'dot' file " "(with no function bodies)", false, false) char PostDomPrinter INITIALIZE_PASS(PostDomPrinter, "dot-postdom", "Print postdominance tree of function to 'dot' file", false, false) char PostDomOnlyPrinter INITIALIZE_PASS (PostDomOnlyPrinter , "dot-postdom-only" , "Print postdominance tree of function to 'dot' file " "(with no function bodies)" , false , false)
Definition at line 215 of file DomPrinter.cpp.
References llvm::createDomPrinterPass(), and INITIALIZE_PASS.
INITIALIZE_PASS() [2/2]
INITIALIZE_PASS(DomViewer, "view-dom", "View dominance tree of function", false, false) char DomOnlyViewer INITIALIZE_PASS(DomOnlyViewer, "view-dom-only", "View dominance tree of function (with no function bodies)", false, false) char PostDomViewer INITIALIZE_PASS(PostDomViewer, "view-postdom", "View postdominance tree of function", false, false) char PostDomOnlyViewer INITIALIZE_PASS (PostDomOnlyViewer , "view-postdom-only" , "View postdominance tree of function " "(with no function bodies)" , false , false)
Definition at line 147 of file DomPrinter.cpp.
References llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::DOTGraphTraitsPrinter(), llvm::PassRegistry::getPassRegistry(), INITIALIZE_PASS, llvm::initializeDomOnlyPrinterPass(), llvm::initializeDomPrinterPass(), llvm::initializePostDomOnlyPrinterPass(), and llvm::initializePostDomPrinterPass().