LLVM: ELFAsmParser.cpp File Reference
LLVM API Documentation
ELFAsmParser.cpp File Reference
#include "llvm/MC/MCParser/MCAsmParserExtension.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ELF.h"
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Functions
static SectionKind computeSectionKind (unsigned Flags, unsigned ElemSize)
static unsigned parseSectionFlags (StringRef flagsStr, bool *UseLastGroup)
static MCSymbolAttr MCAttrForString (StringRef Type)
MCAsmParserExtension * llvm::createELFAsmParser ()
Function Documentation
computeSectionKind()
SectionKind computeSectionKind (unsigned Flags, unsigned ElemSize) static
Definition at line 272 of file ELFAsmParser.cpp.
References llvm::SectionKind::getDataRel(), llvm::SectionKind::getMergeable1ByteCString(), llvm::SectionKind::getMergeable2ByteCString(), llvm::SectionKind::getMergeable4ByteCString(), llvm::SectionKind::getMergeableConst16(), llvm::SectionKind::getMergeableConst4(), llvm::SectionKind::getMergeableConst8(), llvm::SectionKind::getText(), llvm::SectionKind::getThreadData(), llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, and llvm::ELF::SHF_TLS.
MCAttrForString()
MCSymbolAttr MCAttrForString (StringRef Type) static
Definition at line 578 of file ELFAsmParser.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Cases(), llvm::StringSwitch< T, R >::Default(), llvm::MCSA_ELF_TypeCommon, llvm::MCSA_ELF_TypeFunction, llvm::MCSA_ELF_TypeGnuUniqueObject, llvm::MCSA_ELF_TypeIndFunction, llvm::MCSA_ELF_TypeNoType, llvm::MCSA_ELF_TypeObject, llvm::MCSA_ELF_TypeTLS, and llvm::MCSA_Invalid.
parseSectionFlags()
unsigned parseSectionFlags (StringRef flagsStr, bool * UseLastGroup) static
Definition at line 306 of file ELFAsmParser.cpp.
References llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXCLUDE, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHF_TLS, llvm::ELF::SHF_WRITE, llvm::StringRef::size(), llvm::ELF::XCORE_SHF_CP_SECTION, and llvm::ELF::XCORE_SHF_DP_SECTION.