LLVM: FastISel.cpp File Reference
LLVM API Documentation
FastISel.cpp File Reference
#include "llvm/CodeGen/Analysis.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/CodeGen/FastISel.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Macros
#define DEBUG_TYPE "isel"
Functions
STATISTIC (NumFastIselSuccessIndependent, "Number of insts selected by " "target-independent selector")
STATISTIC (NumFastIselSuccessTarget, "Number of insts selected by " "target-specific selector")
STATISTIC (NumFastIselDead, "Number of dead insts removed on failure")
static AttributeSet getReturnAttrs (FastISel::CallLoweringInfo &CLI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "isel"
Definition at line 71 of file FastISel.cpp.
Function Documentation
getReturnAttrs()
AttributeSet getReturnAttrs (FastISel::CallLoweringInfo & CLI) static
Returns an AttributeSet representing the attributes applied to the return value of the given call.
Definition at line 840 of file FastISel.cpp.
References llvm::Type::getContext(), llvm::Attribute::InReg, llvm::FastISel::CallLoweringInfo::IsInReg, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::FastISel::CallLoweringInfo::RetSExt, llvm::FastISel::CallLoweringInfo::RetTy, llvm::AttributeSet::ReturnIndex, llvm::FastISel::CallLoweringInfo::RetZExt, llvm::Attribute::SExt, and llvm::Attribute::ZExt.
Referenced by llvm::TargetLowering::LowerCallTo(), and llvm::FastISel::lowerCallTo().
STATISTIC() [1/3]
STATISTIC (NumFastIselDead , "Number of dead insts removed on failure")
STATISTIC() [2/3]
STATISTIC (NumFastIselSuccessIndependent , "Number of insts selected by " "target-independent selector")
STATISTIC() [3/3]
STATISTIC (NumFastIselSuccessTarget , "Number of insts selected by " "target-specific selector")