LLVM: ForwardControlFlowIntegrity.cpp File Reference
LLVM API Documentation
ForwardControlFlowIntegrity.cpp File Reference
A pass that instruments code with fast checks for indirect calls and hooks for a function to check violations.
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/JumpInstrTableInfo.h"
#include "llvm/CodeGen/ForwardControlFlowIntegrity.h"
#include "llvm/CodeGen/JumpInstrTables.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "cfi"
Functions
STATISTIC (NumCFIIndirectCalls, "Number of indirect call sites rewritten by the CFI pass")
INITIALIZE_PASS_BEGIN (ForwardControlFlowIntegrity, "forward-cfi", "Control-Flow Integrity", true, true) INITIALIZE_PASS_DEPENDENCY(JumpInstrTableInfo)
INITIALIZE_PASS_DEPENDENCY (JumpInstrTables)
INITIALIZE_PASS_END (ForwardControlFlowIntegrity, "forward-cfi", "Control-Flow Integrity", true, true) ModulePass *llvm
static bool isIndirectCall (CallSite &CS)
Variables
static const char cfi_failure_func_name [] = "__llvm_cfi_pointer_warning"
Detailed Description
A pass that instruments code with fast checks for indirect calls and hooks for a function to check violations.
Definition in file ForwardControlFlowIntegrity.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "cfi"
Definition at line 14 of file ForwardControlFlowIntegrity.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ForwardControlFlowIntegrity , "forward-cfi" , "Control-Flow Integrity" , true , true)
References INITIALIZE_PASS_DEPENDENCY.
INITIALIZE_PASS_DEPENDENCY()
INITIALIZE_PASS_DEPENDENCY (JumpInstrTables)
References INITIALIZE_PASS_DEPENDENCY.
INITIALIZE_PASS_END()
INITIALIZE_PASS_END (ForwardControlFlowIntegrity , "forward-cfi" , "Control-Flow Integrity" , true , true)
Definition at line 51 of file ForwardControlFlowIntegrity.cpp.
References llvm::createForwardControlFlowIntegrityPass(), INITIALIZE_PASS_END, and true.
isIndirectCall()
bool isIndirectCall (CallSite & CS) static
Definition at line 67 of file ForwardControlFlowIntegrity.cpp.
References llvm::dyn_cast(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), and llvm::isa().
STATISTIC()
STATISTIC (NumCFIIndirectCalls , "Number of indirect call sites rewritten by the CFI pass")
References llvm::ForwardControlFlowIntegrity::ID.
Variable Documentation
cfi_failure_func_name
const char cfi_failure_func_name[] = "__llvm_cfi_pointer_warning" static
Definition at line 83 of file ForwardControlFlowIntegrity.cpp.