LLVM: GCOVProfiling.cpp File Reference
LLVM API Documentation
GCOVProfiling.cpp File Reference
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/UniqueVector.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <algorithm>
#include <memory>
#include <string>
#include <utility>
Macros
#define DEBUG_TYPE "insert-gcov-profiling"
Functions
INITIALIZE_PASS (GCOVProfiler, "insert-gcov-profiling", "Insert instrumentation for GCOV profiling", false, false) ModulePass *llvm
static StringRef getFunctionName (DISubprogram SP)
static bool functionHasLines (Function *F)
Variables
static cl::opt< std::string > DefaultGCOVVersion ("default-gcov-version", cl::init("402*"), cl::Hidden, cl::ValueRequired)
static cl::opt< bool > DefaultExitBlockBeforeBody ("gcov-exit-block-before-body", cl::init(false), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "insert-gcov-profiling"
Definition at line 45 of file GCOVProfiling.cpp.
Function Documentation
functionHasLines()
bool functionHasLines (Function * F) static
Definition at line 462 of file GCOVProfiling.cpp.
References llvm::BasicBlock::begin(), llvm::BasicBlock::end(), F, llvm::DebugLoc::getLine(), I, llvm::isa(), and llvm::DebugLoc::isUnknown().
getFunctionName()
StringRef getFunctionName (DISubprogram SP) static
Definition at line 156 of file GCOVProfiling.cpp.
INITIALIZE_PASS()
INITIALIZE_PASS (GCOVProfiler , "insert-gcov-profiling" , "Insert instrumentation for GCOV profiling" , false , false)
Definition at line 149 of file GCOVProfiling.cpp.
References const, and llvm::createGCOVProfilerPass().
Variable Documentation
DefaultExitBlockBeforeBody
cl::opt< bool > DefaultExitBlockBeforeBody("gcov-exit-block-before-body", cl::init(false), cl::Hidden) ("gcov-exit-block-before-body" , cl::init(false) , cl::Hidden) static
DefaultGCOVVersion
cl::opt< std::string > DefaultGCOVVersion("default-gcov-version", cl::init("402*"), cl::Hidden, cl::ValueRequired) ("default-gcov-version" , cl::init("402*") , cl::Hidden , cl::ValueRequired) static
Referenced by llvm::GCOVOptions::getDefault().