LLVM: GCOV.cpp File Reference
LLVM API Documentation
GCOV.cpp File Reference
#include "llvm/Support/GCOV.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MemoryObject.h"
#include "llvm/Support/Path.h"
#include <algorithm>
#include <system_error>
Classes
struct formatBranchInfo
Functions
static uint32_t safeDiv (uint64_t Numerator, uint64_t Divisor)
static uint32_t branchDiv (uint64_t Numerator, uint64_t Divisor)
static raw_ostream & operator<< (raw_ostream &OS, const formatBranchInfo &FBI)
static std::string mangleCoveragePath (StringRef Filename, bool PreservePaths)
Function Documentation
branchDiv()
uint32_t branchDiv (uint64_t Numerator, uint64_t Divisor) static
Definition at line 400 of file GCOV.cpp.
Referenced by formatBranchInfo::print().
mangleCoveragePath()
std::string mangleCoveragePath (StringRef Filename, bool PreservePaths) static
Convert a path to a gcov filename. If PreservePaths is true, this translates "/" to "#", ".." to "^", and drops ".", to match gcov.
Definition at line 468 of file GCOV.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::StringRef::begin(), llvm::StringRef::end(), llvm::sys::path::filename(), I, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallString< InternalLen >::str(), and llvm::StringRef::str().
operator<<()
raw_ostream & operator<< (raw_ostream & OS, const formatBranchInfo & FBI) static
Definition at line 433 of file GCOV.cpp.
References formatBranchInfo::print().
safeDiv()
uint32_t safeDiv (uint64_t Numerator, uint64_t Divisor) static
Definition at line 391 of file GCOV.cpp.