LLVM: GlobalDCE.cpp File Reference
LLVM API Documentation
GlobalDCE.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Transforms/Utils/CtorUtils.h"
#include "llvm/Transforms/Utils/GlobalStatus.h"
#include "llvm/Pass.h"
Macros
#define DEBUG_TYPE "globaldce"
Functions
STATISTIC (NumAliases, "Number of global aliases removed")
STATISTIC (NumFunctions, "Number of functions removed")
STATISTIC (NumVariables, "Number of global variables removed")
static bool isEmptyFunction (Function *F)
Returns true if F contains only a single "ret" instruction.
INITIALIZE_PASS (GlobalDCE, "globaldce", "Dead Global Elimination", false, false) ModulePass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "globaldce"
Definition at line 29 of file GlobalDCE.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (GlobalDCE , "globaldce" , "Dead Global Elimination" , false , false)
Definition at line 70 of file GlobalDCE.cpp.
References llvm::createGlobalDCEPass().
isEmptyFunction()
bool isEmptyFunction (Function * F) static
Returns true if F contains only a single "ret" instruction.
Definition at line 61 of file GlobalDCE.cpp.
References llvm::cast(), F, llvm::BasicBlock::front(), llvm::ReturnInst::getReturnValue(), llvm::isa(), and llvm::BasicBlock::size().
STATISTIC() [1/3]
STATISTIC (NumAliases , "Number of global aliases removed")
STATISTIC() [2/3]
STATISTIC (NumFunctions , "Number of functions removed")
STATISTIC() [3/3]
STATISTIC (NumVariables , "Number of global variables removed")
References llvm::PassRegistry::getPassRegistry().