LLVM: GlobalOpt.cpp File Reference
LLVM API Documentation
GlobalOpt.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/Utils/CtorUtils.h"
#include "llvm/Transforms/Utils/GlobalStatus.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <algorithm>
#include <deque>
Macros
#define DEBUG_TYPE "globalopt"
Functions
STATISTIC (NumMarked, "Number of globals marked constant")
STATISTIC (NumUnnamed, "Number of globals marked unnamed_addr")
STATISTIC (NumSRA, "Number of aggregate globals broken into scalars")
STATISTIC (NumHeapSRA, "Number of heap objects SRA'd")
STATISTIC (NumSubstitute,"Number of globals with initializers stored into them")
STATISTIC (NumDeleted, "Number of globals deleted")
STATISTIC (NumFnDeleted, "Number of functions deleted")
STATISTIC (NumGlobUses, "Number of global uses devirtualized")
STATISTIC (NumLocalized, "Number of globals localized")
STATISTIC (NumShrunkToBool, "Number of global vars shrunk to booleans")
STATISTIC (NumFastCallFns, "Number of functions converted to fastcc")
STATISTIC (NumCtorsEvaluated, "Number of static ctors evaluated")
STATISTIC (NumNestRemoved, "Number of nest attributes removed")
STATISTIC (NumAliasesResolved, "Number of global aliases resolved")
STATISTIC (NumAliasesRemoved, "Number of global aliases eliminated")
STATISTIC (NumCXXDtorsRemoved, "Number of global C++ destructors removed")
INITIALIZE_PASS_BEGIN (GlobalOpt, "globalopt", "Global Variable Optimizer", false, false) INITIALIZE_PASS_END(GlobalOpt
static bool isLeakCheckerRoot (GlobalVariable *GV)
static bool IsSafeComputationToRemove (Value *V, const TargetLibraryInfo *TLI)
static bool CleanupPointerRootUsers (GlobalVariable *GV, const TargetLibraryInfo *TLI)
static bool CleanupConstantGlobalUsers (Value *V, Constant *Init, const DataLayout *DL, TargetLibraryInfo *TLI)
static bool isSafeSROAElementUse (Value *V)
static bool IsUserOfGlobalSafeForSRA (User *U, GlobalValue *GV)
static bool GlobalUsersSafeToSRA (GlobalValue *GV)
static GlobalVariable * SRAGlobal (GlobalVariable *GV, const DataLayout &DL)
static bool AllUsesOfValueWillTrapIfNull (const Value *V, SmallPtrSetImpl< const PHINode * > &PHIs)
static bool AllUsesOfLoadedValueWillTrapIfNull (const GlobalVariable *GV)
static bool OptimizeAwayTrappingUsesOfValue (Value *V, Constant *NewV)
static bool OptimizeAwayTrappingUsesOfLoads (GlobalVariable *GV, Constant *LV, const DataLayout *DL, TargetLibraryInfo *TLI)
static void ConstantPropUsersOf (Value *V, const DataLayout *DL, TargetLibraryInfo *TLI)
static GlobalVariable * OptimizeGlobalAddressOfMalloc (GlobalVariable *GV, CallInst *CI, Type *AllocTy, ConstantInt *NElements, const DataLayout *DL, TargetLibraryInfo *TLI)
static bool ValueIsOnlyUsedLocallyOrStoredToOneGlobal (const Instruction *V, const GlobalVariable *GV, SmallPtrSetImpl< const PHINode * > &PHIs)
static void ReplaceUsesOfMallocWithGlobal (Instruction *Alloc, GlobalVariable *GV)
static bool LoadUsesSimpleEnoughForHeapSRA (const Value *V, SmallPtrSetImpl< const PHINode * > &LoadUsingPHIs, SmallPtrSetImpl< const PHINode * > &LoadUsingPHIsPerLoad)
static bool AllGlobalLoadUsesSimpleEnoughForHeapSRA (const GlobalVariable *GV, Instruction *StoredVal)
static Value * GetHeapSROAValue (Value *V, unsigned FieldNo, DenseMap< Value *, std::vector< Value * > > &InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > &PHIsToRewrite)
static void RewriteHeapSROALoadUser (Instruction *LoadUser, DenseMap< Value *, std::vector< Value * > > &InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > &PHIsToRewrite)
static void RewriteUsesOfLoadForHeapSRoA (LoadInst *Load, DenseMap< Value *, std::vector< Value * > > &InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > &PHIsToRewrite)
static GlobalVariable * PerformHeapAllocSRoA (GlobalVariable *GV, CallInst *CI, Value *NElems, const DataLayout *DL, const TargetLibraryInfo *TLI)
static bool TryToOptimizeStoreOfMallocToGlobal (GlobalVariable *GV, CallInst *CI, Type *AllocTy, AtomicOrdering Ordering, Module::global_iterator &GVI, const DataLayout *DL, TargetLibraryInfo *TLI)
static bool OptimizeOnceStoredGlobal (GlobalVariable *GV, Value *StoredOnceVal, AtomicOrdering Ordering, Module::global_iterator &GVI, const DataLayout *DL, TargetLibraryInfo *TLI)
static bool TryToShrinkGlobalToBoolean (GlobalVariable *GV, Constant *OtherVal)
static void ChangeCalleesToFastCall (Function *F)
static AttributeSet StripNest (LLVMContext &C, const AttributeSet &Attrs)
static void RemoveNestAttribute (Function *F)
static bool isProfitableToMakeFastCC (Function *F)
static bool isSimpleEnoughValueToCommit (Constant *C, SmallPtrSetImpl< Constant * > &SimpleConstants, const DataLayout *DL)
static bool isSimpleEnoughValueToCommitHelper (Constant *C, SmallPtrSetImpl< Constant * > &SimpleConstants, const DataLayout *DL)
static bool isSimpleEnoughPointerToCommit (Constant *C)
static Constant * EvaluateStoreInto (Constant *Init, Constant *Val, ConstantExpr *Addr, unsigned OpNo)
static void CommitValueTo (Constant *Val, Constant *Addr)
static bool EvaluateStaticConstructor (Function *F, const DataLayout *DL, const TargetLibraryInfo *TLI)
static int compareNames (Constant *const *A, Constant *const *B)
static void setUsedInitializer (GlobalVariable &V, const SmallPtrSet< GlobalValue *, 8 > &Init)
static bool hasUseOtherThanLLVMUsed (GlobalAlias &GA, const LLVMUsed &U)
static bool hasMoreThanOneUseOtherThanLLVMUsed (GlobalValue &V, const LLVMUsed &U)
static bool mayHaveOtherReferences (GlobalAlias &GA, const LLVMUsed &U)
static bool hasUsesToReplace (GlobalAlias &GA, const LLVMUsed &U, bool &RenameTarget)
static Function * FindCXAAtExit (Module &M, TargetLibraryInfo *TLI)
static bool cxxDtorIsEmpty (const Function &Fn, SmallPtrSet< const Function *, 8 > &CalledFunctions)
Variables
globalopt
Global Variable Optimizer
Global Variable false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "globalopt"
Definition at line 49 of file GlobalOpt.cpp.
Function Documentation
AllGlobalLoadUsesSimpleEnoughForHeapSRA()
bool AllGlobalLoadUsesSimpleEnoughForHeapSRA (const GlobalVariable * GV, Instruction * StoredVal) static
AllGlobalLoadUsesSimpleEnoughForHeapSRA - If all users of values loaded from GV are simple enough to perform HeapSRA, return true.
Definition at line 1102 of file GlobalOpt.cpp.
References llvm::SmallPtrSetImplBase::clear(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dyn_cast(), LoadUsesSimpleEnoughForHeapSRA(), and llvm::Value::users().
Referenced by TryToOptimizeStoreOfMallocToGlobal().
AllUsesOfLoadedValueWillTrapIfNull()
bool AllUsesOfLoadedValueWillTrapIfNull (const GlobalVariable * GV) static
AllUsesOfLoadedValueWillTrapIfNull - Return true if all uses of any loads from GV will trap if the loaded value is null. Note that this also permits comparisons of the loaded value against null, as a special case.
Definition at line 658 of file GlobalOpt.cpp.
References AllUsesOfValueWillTrapIfNull(), llvm::dyn_cast(), llvm::isa(), and llvm::Value::users().
Referenced by TryToOptimizeStoreOfMallocToGlobal().
AllUsesOfValueWillTrapIfNull()
bool AllUsesOfValueWillTrapIfNull (const Value * V, SmallPtrSetImpl< const PHINode * > & PHIs) static
AllUsesOfValueWillTrapIfNull - Return true if all users of the specified value will trap if the value is dynamically null. PHIs keeps track of any phi nodes we've seen to avoid reprocessing them.
Definition at line 615 of file GlobalOpt.cpp.
References AllUsesOfValueWillTrapIfNull(), llvm::dyn_cast(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), and llvm::Value::users().
Referenced by AllUsesOfLoadedValueWillTrapIfNull(), and AllUsesOfValueWillTrapIfNull().
ChangeCalleesToFastCall()
void ChangeCalleesToFastCall (Function * F) static
ChangeCalleesToFastCall - Walk all of the direct calls of the specified function, changing them to FastCC.
Definition at line 1862 of file GlobalOpt.cpp.
References llvm::cast(), F, llvm::CallingConv::Fast, llvm::isa(), and llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setCallingConv().
CleanupConstantGlobalUsers()
bool CleanupConstantGlobalUsers (Value * V, Constant * Init, const DataLayout * DL, TargetLibraryInfo * TLI) static
CleanupConstantGlobalUsers - We just marked GV constant. Loop over all users of the global, cleaning up the obvious ones. This is largely just a quick scan over the use list to clean up the easy and obvious cruft. This returns true if it made a change.
Definition at line 271 of file GlobalOpt.cpp.
References llvm::cast(), Changed, CleanupConstantGlobalUsers(), llvm::ConstantFoldInstruction(), llvm::ConstantFoldLoadThroughGEPConstantExpr(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::SmallVectorBase::empty(), llvm::Constant::getNullValue(), llvm::isa(), llvm::isSafeToDestroyConstant(), and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by CleanupConstantGlobalUsers(), and OptimizeAwayTrappingUsesOfLoads().
CleanupPointerRootUsers()
bool CleanupPointerRootUsers (GlobalVariable * GV, const TargetLibraryInfo * TLI) static
CleanupPointerRootUsers - This GV is a pointer root. Loop over all users of the global and clean up any that obviously don't assign the global a value that isn't dynamically allocated.
Definition at line 184 of file GlobalOpt.cpp.
References Changed, CleanupPointerRootUsers(), llvm::dyn_cast(), I, llvm::isa(), llvm::isAllocationFn(), llvm::GlobalVariable::isConstant(), IsSafeComputationToRemove(), llvm::isSafeToDestroyConstant(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by CleanupPointerRootUsers(), and OptimizeAwayTrappingUsesOfLoads().
CommitValueTo()
void CommitValueTo (Constant * Val, Constant * Addr) static
CommitValueTo - We have decided that Addr (which satisfies the predicate isSimpleEnoughPointerToCommit) should get Val as its value. Make it happen.
Definition at line 2157 of file GlobalOpt.cpp.
References llvm::cast(), llvm::dyn_cast(), EvaluateStoreInto(), llvm::GlobalVariable::getInitializer(), llvm::GlobalVariable::hasInitializer(), and llvm::GlobalVariable::setInitializer().
Referenced by EvaluateStaticConstructor().
compareNames()
int compareNames (Constant *const * A, Constant *const * B) static
Definition at line 2718 of file GlobalOpt.cpp.
Referenced by setUsedInitializer().
ConstantPropUsersOf()
void ConstantPropUsersOf (Value * V, const DataLayout * DL, TargetLibraryInfo * TLI) static
ConstantPropUsersOf - Walk the use list of V, constant folding all of the instructions that are foldable.
Definition at line 805 of file GlobalOpt.cpp.
References llvm::ConstantFoldInstruction(), llvm::dyn_cast(), and I.
Referenced by OptimizeGlobalAddressOfMalloc().
cxxDtorIsEmpty()
bool cxxDtorIsEmpty (const Function & Fn, SmallPtrSet< const Function *, 8 > & CalledFunctions) static
cxxDtorIsEmpty - Returns whether the given function is an empty C++ destructor and can therefore be eliminated. Note that we assume that other optimization passes have already simplified the code so we only look for a function with a single basic block, where the only allowed instructions are 'ret', 'call' to an empty C++ dtor and other side-effect free instructions.
Definition at line 2953 of file GlobalOpt.cpp.
References llvm::BasicBlock::begin(), llvm::Function::begin(), cxxDtorIsEmpty(), llvm::dyn_cast(), llvm::BasicBlock::end(), llvm::Function::end(), llvm::Function::getEntryBlock(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), and llvm::GlobalValue::isDeclaration().
Referenced by cxxDtorIsEmpty().
EvaluateStaticConstructor()
bool EvaluateStaticConstructor (Function * F, const DataLayout * DL, const TargetLibraryInfo * TLI) static
EvaluateStaticConstructor - Evaluate static constructors in the function, if we can. Return true if we can, false otherwise.
Definition at line 2692 of file GlobalOpt.cpp.
References CommitValueTo(), llvm::dbgs(), DEBUG, llvm::Eval(), F, I, and llvm::GlobalVariable::setConstant().
EvaluateStoreInto()
Constant * EvaluateStoreInto (Constant * Init, Constant * Val, ConstantExpr * Addr, unsigned OpNo) static
EvaluateStoreInto - Evaluate a piece of a constantexpr store into a global initializer. This returns 'Init' modified to reflect 'Val' stored into it. At this point, the GEP operands of Addr [0, OpNo) have been stepped into.
Definition at line 2109 of file GlobalOpt.cpp.
References llvm::cast(), llvm::dyn_cast(), EvaluateStoreInto(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::ConstantInt::getZExtValue(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by CommitValueTo(), and EvaluateStoreInto().
FindCXAAtExit()
Function * FindCXAAtExit (Module & M, TargetLibraryInfo * TLI) static
Definition at line 2924 of file GlobalOpt.cpp.
References llvm::LibFunc::cxa_atexit, llvm::Module::getFunction(), llvm::Function::getFunctionType(), llvm::TargetLibraryInfo::getName(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::FunctionType::getReturnType(), llvm::TargetLibraryInfo::has(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
GetHeapSROAValue()
Value * GetHeapSROAValue (Value * V, unsigned FieldNo, DenseMap< Value *, std::vector< Value * > > & InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > & PHIsToRewrite) static
Definition at line 1148 of file GlobalOpt.cpp.
References llvm::cast(), llvm::PHINode::Create(), llvm::dyn_cast(), llvm::PointerType::get(), llvm::PointerType::getAddressSpace(), llvm::SequentialType::getElementType(), GetHeapSROAValue(), llvm::Value::getName(), and llvm_unreachable.
Referenced by GetHeapSROAValue(), PerformHeapAllocSRoA(), and RewriteHeapSROALoadUser().
GlobalUsersSafeToSRA()
bool GlobalUsersSafeToSRA (GlobalValue * GV) static
GlobalUsersSafeToSRA - Look at all uses of the global and decide whether it is safe for us to perform this transformation.
Definition at line 459 of file GlobalOpt.cpp.
References IsUserOfGlobalSafeForSRA(), and llvm::Value::users().
Referenced by SRAGlobal().
hasMoreThanOneUseOtherThanLLVMUsed()
bool hasMoreThanOneUseOtherThanLLVMUsed (GlobalValue & V, const LLVMUsed & U) static
Definition at line 2813 of file GlobalOpt.cpp.
References N.
Referenced by hasUsesToReplace().
hasUseOtherThanLLVMUsed()
bool hasUseOtherThanLLVMUsed (GlobalAlias & GA, const LLVMUsed & U) static
Definition at line 2797 of file GlobalOpt.cpp.
References llvm::Value::hasOneUse(), and llvm::Value::use_empty().
Referenced by hasUsesToReplace().
hasUsesToReplace()
bool hasUsesToReplace (GlobalAlias & GA, const LLVMUsed & U, bool & RenameTarget) static
Definition at line 2831 of file GlobalOpt.cpp.
References llvm::cast(), llvm::GlobalAlias::getAliasee(), hasMoreThanOneUseOtherThanLLVMUsed(), hasUseOtherThanLLVMUsed(), mayHaveOtherReferences(), and llvm::Constant::stripPointerCasts().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (GlobalOpt , "globalopt" , "Global Variable Optimizer" , false , false)
References INITIALIZE_PASS_DEPENDENCY.
isLeakCheckerRoot()
bool isLeakCheckerRoot (GlobalVariable * GV) static
isLeakCheckerRoot - Is this global variable possibly used by a leak checker as a root? If so, we might not really want to eliminate the stores to it.
Definition at line 106 of file GlobalOpt.cpp.
References llvm::Type::ArrayTyID, llvm::cast(), llvm::StructType::element_begin(), llvm::StructType::element_end(), llvm::SmallVectorBase::empty(), llvm::SequentialType::getElementType(), llvm::GlobalValue::getType(), llvm::Type::getTypeID(), llvm::GlobalValue::hasPrivateLinkage(), I, llvm::isa(), llvm::StructType::isOpaque(), llvm::Type::PointerTyID, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::Type::StructTyID, and llvm::Type::VectorTyID.
Referenced by OptimizeAwayTrappingUsesOfLoads().
isProfitableToMakeFastCC()
bool isProfitableToMakeFastCC (Function * F) static
Return true if this is a calling convention that we'd like to change. The idea here is that we don't want to mess with the convention if the user explicitly requested something with performance implications like coldcc, GHC, or anyregcc.
Definition at line 1898 of file GlobalOpt.cpp.
References llvm::CallingConv::C, F, and llvm::CallingConv::X86_ThisCall.
IsSafeComputationToRemove()
bool IsSafeComputationToRemove (Value * V, const TargetLibraryInfo * TLI) static
Given a value that is stored to a global but never read, determine whether it's safe to remove the store and the chain of computation that feeds the store.
Definition at line 154 of file GlobalOpt.cpp.
References llvm::cast(), llvm::dyn_cast(), I, llvm::isa(), and llvm::isAllocationFn().
Referenced by CleanupPointerRootUsers().
isSafeSROAElementUse()
bool isSafeSROAElementUse (Value * V) static
isSafeSROAElementUse - Return true if the specified instruction is a safe user of a derived expression from a global that we want to SROA.
Definition at line 359 of file GlobalOpt.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::User::getNumOperands(), llvm::User::getOperand(), I, llvm::isa(), isSafeSROAElementUse(), llvm::isSafeToDestroyConstant(), and llvm::Value::users().
Referenced by isSafeSROAElementUse(), and IsUserOfGlobalSafeForSRA().
isSimpleEnoughPointerToCommit()
bool isSimpleEnoughPointerToCommit (Constant * C) static
isSimpleEnoughPointerToCommit - Return true if this constant is simple enough for us to understand. In particular, if it is a cast to anything other than from one pointer type to another pointer type, we punt. We basically just support direct accesses to globals and GEP's of globals. This should be kept up to date with CommitValueTo.
Definition at line 2060 of file GlobalOpt.cpp.
References llvm::cast(), llvm::ConstantFoldLoadThroughGEPConstantExpr(), llvm::dyn_cast(), llvm::GlobalVariable::getInitializer(), llvm::GlobalVariable::hasUniqueInitializer(), llvm::isa(), and llvm::ConstantInt::isZero().
isSimpleEnoughValueToCommit()
bool isSimpleEnoughValueToCommit (Constant * C, SmallPtrSetImpl< Constant * > & SimpleConstants, const DataLayout * DL) inline static
Definition at line 2044 of file GlobalOpt.cpp.
References llvm::SmallPtrSetImpl< PtrType >::insert(), and isSimpleEnoughValueToCommitHelper().
Referenced by isSimpleEnoughValueToCommitHelper().
isSimpleEnoughValueToCommitHelper()
bool isSimpleEnoughValueToCommitHelper (Constant * C, SmallPtrSetImpl< Constant * > & SimpleConstants, const DataLayout * DL) static
isSimpleEnoughValueToCommit - Return true if the specified constant can be handled by the code generator. We don't want to generate something like: void *X = &X/42; because the code generator doesn't have a relocation that can handle that.
This function should be called if C was not found (but just got inserted) in SimpleConstants to avoid having to rescan the same constants all the time.
Definition at line 1986 of file GlobalOpt.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::DataLayout::getTypeSizeInBits(), llvm::GlobalValue::hasDLLImportStorageClass(), llvm::isa(), isSimpleEnoughValueToCommit(), and llvm::GlobalValue::isThreadLocal().
Referenced by isSimpleEnoughValueToCommit().
IsUserOfGlobalSafeForSRA()
bool IsUserOfGlobalSafeForSRA (User * U, GlobalValue * GV) static
IsUserOfGlobalSafeForSRA - U is a direct user of the specified global value. Look at it and its uses and decide whether it is safe to SROA this global.
Definition at line 392 of file GlobalOpt.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::gep_type_begin(), llvm::gep_type_end(), llvm::generic_gep_type_iterator< ItTy >::getOperand(), llvm::ConstantInt::getZExtValue(), llvm::isa(), isSafeSROAElementUse(), and llvm::Value::users().
Referenced by GlobalUsersSafeToSRA().
LoadUsesSimpleEnoughForHeapSRA()
bool LoadUsesSimpleEnoughForHeapSRA (const Value * V, SmallPtrSetImpl< const PHINode * > & LoadUsingPHIs, SmallPtrSetImpl< const PHINode * > & LoadUsingPHIsPerLoad) static
LoadUsesSimpleEnoughForHeapSRA - Verify that all uses of V (a load, or a phi of a load) are simple enough to perform heap SRA on. This permits GEP's that index through the array and struct field, icmps of null, and PHIs.
Definition at line 1050 of file GlobalOpt.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), LoadUsesSimpleEnoughForHeapSRA(), and llvm::Value::users().
Referenced by AllGlobalLoadUsesSimpleEnoughForHeapSRA(), and LoadUsesSimpleEnoughForHeapSRA().
mayHaveOtherReferences()
bool mayHaveOtherReferences (GlobalAlias & GA, const LLVMUsed & U) static
Definition at line 2824 of file GlobalOpt.cpp.
References llvm::GlobalValue::hasLocalLinkage().
Referenced by hasUsesToReplace().
OptimizeAwayTrappingUsesOfLoads()
bool OptimizeAwayTrappingUsesOfLoads (GlobalVariable * GV, Constant * LV, const DataLayout * DL, TargetLibraryInfo * TLI) static
OptimizeAwayTrappingUsesOfLoads - The specified global has only one non-null value stored into it. If there are uses of the loaded value that would trap if the loaded value is dynamically null, then we know that they cannot be reachable with a null optimize away the load.
Definition at line 741 of file GlobalOpt.cpp.
References Changed, CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::GlobalVariable::eraseFromParent(), llvm::User::getOperand(), llvm::isa(), isLeakCheckerRoot(), OptimizeAwayTrappingUsesOfValue(), llvm::Value::use_empty(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by OptimizeOnceStoredGlobal().
OptimizeAwayTrappingUsesOfValue()
bool OptimizeAwayTrappingUsesOfValue (Value * V, Constant * NewV) static
Definition at line 674 of file GlobalOpt.cpp.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_size(), llvm::cast(), Changed, llvm::dyn_cast(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), llvm::ConstantExpr::getCast(), llvm::ConstantExpr::getGetElementPtr(), llvm::Value::getType(), I, llvm::isa(), OptimizeAwayTrappingUsesOfValue(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setArgument(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setCalledFunction(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by OptimizeAwayTrappingUsesOfLoads(), and OptimizeAwayTrappingUsesOfValue().
OptimizeGlobalAddressOfMalloc()
GlobalVariable * OptimizeGlobalAddressOfMalloc (GlobalVariable * GV, CallInst * CI, Type * AllocTy, ConstantInt * NElements, const DataLayout * DL, TargetLibraryInfo * TLI) static
OptimizeGlobalAddressOfMalloc - This function takes the specified global variable, and transforms the program as if it always contained the result of the specified malloc. Because it is always the result of the specified malloc, there is no reason to actually DO the malloc. Instead, turn the malloc into a global, and any loads of GV as uses of the new global.
Definition at line 825 of file GlobalOpt.cpp.
References llvm::cast(), ConstantPropUsersOf(), llvm::BinaryOperator::CreateNot(), DEBUG, llvm::dyn_cast(), llvm::GlobalVariable::eraseFromParent(), llvm::Instruction::eraseFromParent(), llvm::errs(), llvm::ArrayType::get(), llvm::UndefValue::get(), llvm::ConstantExpr::getBitCast(), llvm::Value::getContext(), llvm::SequentialType::getElementType(), llvm::ConstantInt::getFalse(), llvm::Module::getGlobalList(), llvm::Type::getInt1Ty(), llvm::Value::getName(), llvm::LoadInst::getOrdering(), llvm::GlobalValue::getParent(), llvm::CmpInst::getPredicate(), llvm::LoadInst::getSynchScope(), llvm::GlobalValue::getThreadLocalMode(), llvm::ConstantInt::getTrue(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::Use::getUser(), llvm::ConstantInt::getZExtValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::iplist< NodeTy, Traits >::insert(), llvm::GlobalValue::InternalLinkage, llvm::LoadInst::isUnordered(), llvm_unreachable, llvm::Value::replaceAllUsesWith(), llvm::User::replaceUsesOfWith(), llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Instruction::user_back(), and llvm::Value::user_back().
Referenced by TryToOptimizeStoreOfMallocToGlobal().
OptimizeOnceStoredGlobal()
bool OptimizeOnceStoredGlobal (GlobalVariable * GV, Value * StoredOnceVal, AtomicOrdering Ordering, Module::global_iterator & GVI, const DataLayout * DL, TargetLibraryInfo * TLI) static
Definition at line 1563 of file GlobalOpt.cpp.
References llvm::dyn_cast(), llvm::extractMallocCall(), llvm::ConstantExpr::getBitCast(), llvm::GlobalVariable::getInitializer(), llvm::getMallocAllocatedType(), llvm::Value::getType(), llvm::Constant::isNullValue(), llvm::Type::isPointerTy(), OptimizeAwayTrappingUsesOfLoads(), llvm::Value::stripPointerCasts(), and TryToOptimizeStoreOfMallocToGlobal().
PerformHeapAllocSRoA()
GlobalVariable * PerformHeapAllocSRoA (GlobalVariable * GV, CallInst * CI, Value * NElems, const DataLayout * DL, const TargetLibraryInfo * TLI) static
PerformHeapAllocSRoA - CI is an allocation of an array of structures. Break it up into multiple allocations of arrays of the fields.
InsertedScalarizedLoads - As we process loads, if we can't immediately update all uses of the load, keep track of what scalarized loads are inserted for a given load.
Definition at line 1273 of file GlobalOpt.cpp.
References llvm::PHINode::addIncoming(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::cast(), llvm::BasicBlock::Create(), llvm::BranchInst::Create(), llvm::CallInst::CreateFree(), llvm::CallInst::CreateMalloc(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::GlobalVariable::eraseFromParent(), llvm::Instruction::eraseFromParent(), llvm::ConstantInt::get(), llvm::PointerType::get(), llvm::CallInst::getArgOperand(), llvm::BasicBlock::getContext(), llvm::Value::getContext(), llvm::SequentialType::getElementType(), llvm::StructType::getElementType(), GetHeapSROAValue(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::DataLayout::getIntPtrType(), llvm::getMallocAllocatedType(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::StructType::getNumElements(), llvm::PHINode::getNumIncomingValues(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Instruction::getParent(), llvm::Type::getPointerAddressSpace(), llvm::StructLayout::getSizeInBytes(), llvm::DataLayout::getStructLayout(), llvm::BasicBlock::getTerminator(), llvm::GlobalValue::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SLT, llvm::GlobalValue::InternalLinkage, llvm::isa(), ReplaceUsesOfMallocWithGlobal(), RewriteUsesOfLoadForHeapSRoA(), llvm::BasicBlock::splitBasicBlock(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by TryToOptimizeStoreOfMallocToGlobal().
RemoveNestAttribute()
void RemoveNestAttribute (Function * F) static
Definition at line 1884 of file GlobalOpt.cpp.
References llvm::cast(), F, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getAttributes(), llvm::isa(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setAttributes(), and StripNest().
ReplaceUsesOfMallocWithGlobal()
void ReplaceUsesOfMallocWithGlobal (Instruction * Alloc, GlobalVariable * GV) static
ReplaceUsesOfMallocWithGlobal - The Alloc pointer is stored into GV somewhere. Transform all uses of the allocation into loads from the global and uses of the resultant pointer. Further, delete the store into GV. This assumes that these value pass the 'ValueIsOnlyUsedLocallyOrStoredToOneGlobal' predicate.
Definition at line 1007 of file GlobalOpt.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::Value::getName(), llvm::isa(), ReplaceUsesOfMallocWithGlobal(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::user_begin().
Referenced by PerformHeapAllocSRoA(), and ReplaceUsesOfMallocWithGlobal().
RewriteHeapSROALoadUser()
void RewriteHeapSROALoadUser (Instruction * LoadUser, DenseMap< Value *, std::vector< Value * > > & InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > & PHIsToRewrite) static
RewriteHeapSROALoadUser - Given a load instruction and a value derived from the load, rewrite the derived value to use the HeapSRoA'd load.
Definition at line 1193 of file GlobalOpt.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::cast(), llvm::GetElementPtrInst::Create(), llvm::dyn_cast(), GetHeapSROAValue(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::isa(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), RewriteHeapSROALoadUser(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by RewriteHeapSROALoadUser(), and RewriteUsesOfLoadForHeapSRoA().
RewriteUsesOfLoadForHeapSRoA()
void RewriteUsesOfLoadForHeapSRoA (LoadInst * Load, DenseMap< Value *, std::vector< Value * > > & InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > & PHIsToRewrite) static
RewriteUsesOfLoadForHeapSRoA - We are performing Heap SRoA on a global. Ptr is a value loaded from the global. Eliminate all uses of Ptr, making them use FieldGlobals instead. All uses of loaded values satisfy AllGlobalLoadUsesSimpleEnoughForHeapSRA.
Definition at line 1257 of file GlobalOpt.cpp.
References llvm::cast(), and RewriteHeapSROALoadUser().
Referenced by PerformHeapAllocSRoA().
setUsedInitializer()
void setUsedInitializer (GlobalVariable & V, const SmallPtrSet< GlobalValue *, 8 > & Init) static
Definition at line 2722 of file GlobalOpt.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::array_pod_sort(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), compareNames(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::Type::getInt8PtrTy(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
SRAGlobal()
GlobalVariable * SRAGlobal (GlobalVariable * GV, const DataLayout & DL) static
SRAGlobal - Perform scalar replacement of aggregates on the specified global variable. This opens the door for other optimizations by exposing the behavior of the program in a more fine-grained way. We have determined that this transformation is safe already. We return the first global variable we insert so that the caller can reprocess it.
Definition at line 473 of file GlobalOpt.cpp.
References llvm::cast(), llvm::GetElementPtrInst::Create(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::iplist< NodeTy, Traits >::erase(), llvm::DataLayout::getABITypeAlignment(), llvm::PointerType::getAddressSpace(), llvm::GlobalObject::getAlignment(), llvm::Value::getContext(), llvm::StructLayout::getElementOffset(), llvm::ConstantExpr::getGetElementPtr(), llvm::Module::getGlobalList(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::GlobalValue::getParent(), llvm::DataLayout::getStructLayout(), llvm::GlobalValue::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::DataLayout::getTypeAllocSize(), GlobalUsersSafeToSRA(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasNUsesOrMore(), llvm::iplist< NodeTy, Traits >::insert(), llvm::GlobalValue::InternalLinkage, llvm::isa(), llvm::GlobalVariable::isConstant(), llvm::MinAlign(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::GlobalObject::setAlignment(), llvm::Value::use_empty(), and llvm::Value::user_back().
STATISTIC() [1/16]
STATISTIC (NumAliasesRemoved , "Number of global aliases eliminated")
STATISTIC() [2/16]
STATISTIC (NumAliasesResolved , "Number of global aliases resolved")
STATISTIC() [3/16]
STATISTIC (NumCtorsEvaluated , "Number of static ctors evaluated")
STATISTIC() [4/16]
STATISTIC (NumCXXDtorsRemoved , "Number of global C++ destructors removed")
STATISTIC() [5/16]
STATISTIC (NumDeleted , "Number of globals deleted")
STATISTIC() [6/16]
STATISTIC (NumFastCallFns , "Number of functions converted to fastcc")
STATISTIC() [7/16]
STATISTIC (NumFnDeleted , "Number of functions deleted")
STATISTIC() [8/16]
STATISTIC (NumGlobUses , "Number of global uses devirtualized")
STATISTIC() [9/16]
STATISTIC (NumHeapSRA , "Number of heap objects SRA'd")
STATISTIC() [10/16]
STATISTIC (NumLocalized , "Number of globals localized")
STATISTIC() [11/16]
STATISTIC (NumMarked , "Number of globals marked constant")
STATISTIC() [12/16]
STATISTIC (NumNestRemoved , "Number of nest attributes removed")
STATISTIC() [13/16]
STATISTIC (NumShrunkToBool , "Number of global vars shrunk to booleans")
STATISTIC() [14/16]
STATISTIC (NumSRA , "Number of aggregate globals broken into scalars")
STATISTIC() [15/16]
STATISTIC (NumSubstitute , "Number of globals with initializers stored into them")
STATISTIC() [16/16]
STATISTIC (NumUnnamed , "Number of globals marked unnamed_addr")
StripNest()
AttributeSet StripNest (LLVMContext & C, const AttributeSet & Attrs) static
Definition at line 1871 of file GlobalOpt.cpp.
References llvm::AttributeSet::getNumSlots(), llvm::AttributeSet::getSlotAttributes(), llvm::AttributeSet::getSlotIndex(), llvm::AttributeSet::hasAttribute(), llvm::Attribute::Nest, and llvm::AttributeSet::removeAttribute().
Referenced by RemoveNestAttribute().
TryToOptimizeStoreOfMallocToGlobal()
bool TryToOptimizeStoreOfMallocToGlobal (GlobalVariable * GV, CallInst * CI, Type * AllocTy, AtomicOrdering Ordering, Module::global_iterator & GVI, const DataLayout * DL, TargetLibraryInfo * TLI) static
TryToOptimizeStoreOfMallocToGlobal - This function is called when we see a pointer global variable with a single value stored it that is a malloc or cast of malloc.
Definition at line 1462 of file GlobalOpt.cpp.
References AllGlobalLoadUsesSimpleEnoughForHeapSRA(), AllUsesOfLoadedValueWillTrapIfNull(), llvm::cast(), llvm::CallInst::CreateMalloc(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::ConstantInt::get(), llvm::CallInst::getArgOperand(), llvm::DataLayout::getIntPtrType(), llvm::getMallocAllocatedType(), llvm::getMallocArraySize(), llvm::Value::getName(), llvm::StructType::getNumElements(), llvm::StructLayout::getSizeInBytes(), llvm::DataLayout::getStructLayout(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::Type::isSized(), llvm::NotAtomic, OptimizeGlobalAddressOfMalloc(), PerformHeapAllocSRoA(), llvm::Value::replaceAllUsesWith(), and ValueIsOnlyUsedLocallyOrStoredToOneGlobal().
Referenced by OptimizeOnceStoredGlobal().
TryToShrinkGlobalToBoolean()
bool TryToShrinkGlobalToBoolean (GlobalVariable * GV, Constant * OtherVal) static
TryToShrinkGlobalToBoolean - At this point, we have learned that the only two values ever stored into GV are its initializer and OtherVal. See if we can shrink the global into a boolean and select between the two values whenever it is used. This exposes the values to other scalar optimizations.
Definition at line 1600 of file GlobalOpt.cpp.
References llvm::cast(), llvm::SelectInst::Create(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::GlobalVariable::eraseFromParent(), llvm::Instruction::eraseFromParent(), llvm::ConstantInt::get(), llvm::PointerType::getAddressSpace(), llvm::Value::getContext(), llvm::SequentialType::getElementType(), llvm::ConstantInt::getFalse(), llvm::Module::getGlobalList(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt1Ty(), llvm::Value::getName(), llvm::User::getOperand(), llvm::LoadInst::getOrdering(), llvm::GlobalValue::getParent(), llvm::LoadInst::getSynchScope(), llvm::GlobalValue::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::iplist< NodeTy, Traits >::insert(), llvm::GlobalValue::InternalLinkage, llvm::isa(), llvm::Type::isFloatingPointTy(), llvm::Constant::isNullValue(), llvm::Type::isPointerTy(), llvm::Type::isVectorTy(), llvm::Value::replaceAllUsesWith(), llvm::Value::takeName(), llvm::Value::use_empty(), llvm::Value::user_back(), and llvm::Value::users().
ValueIsOnlyUsedLocallyOrStoredToOneGlobal()
bool ValueIsOnlyUsedLocallyOrStoredToOneGlobal (const Instruction * V, const GlobalVariable * GV, SmallPtrSetImpl< const PHINode * > & PHIs) static
ValueIsOnlyUsedLocallyOrStoredToOneGlobal - Scan the use-list of V checking to make sure that there are no complex uses of V. We permit simple things like dereferencing the pointer, but not storing through the address, unless it is to the specified global.
Definition at line 959 of file GlobalOpt.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::User::getNumOperands(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::Value::users(), and ValueIsOnlyUsedLocallyOrStoredToOneGlobal().
Referenced by TryToOptimizeStoreOfMallocToGlobal(), and ValueIsOnlyUsedLocallyOrStoredToOneGlobal().
Variable Documentation
false
Global Variable false
Definition at line 100 of file GlobalOpt.cpp.
globalopt
globalopt
Definition at line 99 of file GlobalOpt.cpp.
Optimizer
Global Variable Optimizer
Definition at line 100 of file GlobalOpt.cpp.