LLVM: GraphWriter.cpp File Reference
LLVM API Documentation
GraphWriter.cpp File Reference
#include "llvm/Support/GraphWriter.h"
#include "llvm/Config/config.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
Classes
struct GraphSession
Functions
static bool ExecGraphViewer (StringRef ExecPath, std::vector< const char * > &args, StringRef Filename, bool wait, std::string &ErrMsg)
static const char * getProgramName (GraphProgram::Name program)
Variables
static cl::opt< bool > ViewBackground ("view-background", cl::Hidden, cl::desc("Execute graph viewer in the background. Creates tmp file litter."))
Function Documentation
ExecGraphViewer()
bool ExecGraphViewer (StringRef ExecPath, std::vector< const char * > & args, StringRef Filename, bool wait, std::string & ErrMsg) static
Definition at line 82 of file GraphWriter.cpp.
References llvm::errs(), llvm::sys::ExecuteAndWait(), llvm::sys::ExecuteNoWait(), llvm::sys::fs::remove(), and llvm::StringRef::str().
Referenced by llvm::DisplayGraph().
getProgramName()
const char * getProgramName (GraphProgram::Name program) static
Definition at line 118 of file GraphWriter.cpp.
References llvm::GraphProgram::CIRCO, llvm::GraphProgram::DOT, llvm::GraphProgram::FDP, llvm_unreachable, llvm::GraphProgram::NEATO, and llvm::GraphProgram::TWOPI.
Referenced by llvm::DisplayGraph().
Variable Documentation
ViewBackground
cl::opt< bool > ViewBackground("view-background", cl::Hidden, cl::desc("Execute graph viewer in the background. Creates tmp file litter.")) ("view-background" , cl::Hidden , cl::desc("Execute graph viewer in the background. Creates tmp file litter.")) static
Referenced by llvm::DisplayGraph().