LLVM: ARC Optimization.
LLVM API Documentation
ARC Optimization.
Macros
#define ARC_ANNOTATIONS
#define ANNOTATE_BOTTOMUP(inst, ptr, old, new)
#define ANNOTATE_TOPDOWN(inst, ptr, old, new)
#define ANNOTATE_BB(_states, _bb, _name, _type, _direction)
#define ANNOTATE_BOTTOMUP_BBSTART(_states, _basicblock)
#define ANNOTATE_BOTTOMUP_BBEND(_states, _basicblock)
#define ANNOTATE_TOPDOWN_BBSTART(_states, _basicblock)
#define ANNOTATE_TOPDOWN_BBEND(_states, _basicblock)
Functions
STATISTIC (NumNoops, "Number of no-op objc calls eliminated")
STATISTIC (NumPartialNoops, "Number of partially no-op objc calls eliminated")
STATISTIC (NumAutoreleases,"Number of autoreleases converted to releases")
STATISTIC (NumRets, "Number of return value forwarding " "retain+autoreleases eliminated")
STATISTIC (NumRRs, "Number of retain+release paths eliminated")
STATISTIC (NumPeeps, "Number of calls peephole-optimized")
STATISTIC (NumRetainsBeforeOpt, "Number of retains before optimization")
STATISTIC (NumReleasesBeforeOpt, "Number of releases before optimization")
STATISTIC (NumRetainsAfterOpt, "Number of retains after optimization")
STATISTIC (NumReleasesAfterOpt, "Number of releases after optimization")
static Sequence MergeSeqs (Sequence A, Sequence B, bool TopDown)
static MDString * AppendMDNodeToSourcePtr (unsigned NodeId, Value *Ptr)
static std::string SequenceToString (Sequence A)
static MDString * SequenceToMDString (LLVMContext &Context, Sequence A)
static void AppendMDNodeToInstForPtr (unsigned NodeId, Instruction *Inst, Value *Ptr, MDString *PtrSourceMDNodeID, Sequence OldSeq, Sequence NewSeq)
static void GenerateARCBBEntranceAnnotation (const char *Name, BasicBlock *BB, Value *Ptr, Sequence Seq)
static void GenerateARCBBTerminatorAnnotation (const char *Name, BasicBlock *BB, Value *Ptr, Sequence Seq)
static void GenerateARCAnnotation (unsigned InstMDId, unsigned PtrMDId, Instruction *Inst, Value *Ptr, Sequence OldSeq, Sequence NewSeq)
INITIALIZE_PASS_BEGIN (ObjCARCOpt, "objc-arc", "ObjC ARC optimization", false, false) INITIALIZE_PASS_END(ObjCARCOpt
static void CheckForUseCFGHazard (const Sequence SuccSSeq, const bool SuccSRRIKnownSafe, PtrState &S, bool &SomeSuccHasSame, bool &AllSuccsHaveSame, bool &NotAllSeqEqualButKnownSafe, bool &ShouldContinue)
static void CheckForCanReleaseCFGHazard (const Sequence SuccSSeq, const bool SuccSRRIKnownSafe, PtrState &S, bool &SomeSuccHasSame, bool &AllSuccsHaveSame, bool &NotAllSeqEqualButKnownSafe)
static void ComputePostOrders (Function &F, SmallVectorImpl< BasicBlock * > &PostOrder, SmallVectorImpl< BasicBlock * > &ReverseCFGPostOrder, unsigned NoObjCARCExceptionsMDKind, DenseMap< const BasicBlock *, BBState > &BBStates)
static bool HasSafePathToPredecessorCall (const Value *Arg, Instruction *Retain, SmallPtrSetImpl< Instruction * > &DepInsts, SmallPtrSetImpl< const BasicBlock * > &Visited, ProvenanceAnalysis &PA)
static CallInst * FindPredecessorRetainWithSafePath (const Value *Arg, BasicBlock *BB, Instruction *Autorelease, SmallPtrSetImpl< Instruction * > &DepInsts, SmallPtrSetImpl< const BasicBlock * > &Visited, ProvenanceAnalysis &PA)
DependingInstructions clear ()
if (!Autorelease) continue
DEBUG (dbgs()<< "Erasing: "<< *Retain<< "\nErasing: "<< *Autorelease<< "\n")
EraseInstruction (Retain)
EraseInstruction (Autorelease)
Pass * llvm::createObjCARCOptPass ()
Variables
static cl::opt< bool > EnableARCAnnotations ("enable-objc-arc-annotations", cl::init(false), cl::desc("Enable emission of arc data flow analysis " "annotations"))
Enable/disable ARC sequence annotations.
static cl::opt< bool > DisableCheckForCFGHazards ("disable-objc-arc-checkforcfghazards", cl::init(false), cl::desc("Disable check for cfg hazards when " "annotating"))
static cl::opt< std::string > ARCAnnotationTargetIdentifier ("objc-arc-annotation-target-identifier", cl::init(""), cl::desc("filter out all data flow annotations " "but those that apply to the given " "target llvm identifier."))
objc arc
objc ObjC ARC optimization
objc ObjC ARC false
CallInst * Autorelease
CallInst * Retain
bool HasSafePathToCall
Changed = true
NumRets
static char ObjCARCOpt::ID = 0
Detailed Description
Macro Definition Documentation
ANNOTATE_BB
#define ANNOTATE_BB (_states, _bb, _name, _type, _direction)
Value:
  do {                                                                        \
    if (EnableARCAnnotations) {                                               \
      for(BBState::ptr_const_iterator I = (_states)._direction##_ptr_begin(), \
          E = (_states)._direction##_ptr_end(); I != E; ++I) {                \
        Value *Ptr = const_cast<Value*>(I->first);                            \
        Sequence Seq = I->second.GetSeq();                                    \
        GenerateARCBB ## _type ## Annotation(_name, (_bb), Ptr, Seq);         \
      }                                                                       \
    }                                                                         \
  } while (0)
Definition at line 1027 of file ObjCARCOpts.cpp.
ANNOTATE_BOTTOMUP
#define ANNOTATE_BOTTOMUP (inst, ptr, old, new)
Value:
  GenerateARCAnnotation(ARCAnnotationBottomUpMDKind,                    \
                        ARCAnnotationProvenanceSourceMDKind, (inst),    \
                        const_cast<Value*>(ptr), (old), (new))
Use this macro to annotate a sequence state change when processing instructions bottom up,
Definition at line 1016 of file ObjCARCOpts.cpp.
ANNOTATE_BOTTOMUP_BBEND
#define ANNOTATE_BOTTOMUP_BBEND (_states, _basicblock)
Value:
    ANNOTATE_BB(_states, _basicblock, "llvm.arc.annotation.bottomup.bbend",   \
                Terminator, bottom_up)
Definition at line 1042 of file ObjCARCOpts.cpp.
ANNOTATE_BOTTOMUP_BBSTART
#define ANNOTATE_BOTTOMUP_BBSTART (_states, _basicblock)
Value:
    ANNOTATE_BB(_states, _basicblock, "llvm.arc.annotation.bottomup.bbstart", \
                Entrance, bottom_up)
Definition at line 1039 of file ObjCARCOpts.cpp.
ANNOTATE_TOPDOWN
#define ANNOTATE_TOPDOWN (inst, ptr, old, new)
Value:
  GenerateARCAnnotation(ARCAnnotationTopDownMDKind,                     \
                        ARCAnnotationProvenanceSourceMDKind, (inst),    \
                        const_cast<Value*>(ptr), (old), (new))
Use this macro to annotate a sequence state change when processing instructions top down.
Definition at line 1022 of file ObjCARCOpts.cpp.
ANNOTATE_TOPDOWN_BBEND
#define ANNOTATE_TOPDOWN_BBEND (_states, _basicblock)
Value:
    ANNOTATE_BB(_states, _basicblock, "llvm.arc.annotation.topdown.bbend",    \
                Terminator, top_down)
Definition at line 1048 of file ObjCARCOpts.cpp.
ANNOTATE_TOPDOWN_BBSTART
#define ANNOTATE_TOPDOWN_BBSTART (_states, _basicblock)
Value:
    ANNOTATE_BB(_states, _basicblock, "llvm.arc.annotation.topdown.bbstart",  \
                Entrance, top_down)
Definition at line 1045 of file ObjCARCOpts.cpp.
ARC_ANNOTATIONS
#define ARC_ANNOTATIONS
Definition at line 789 of file ObjCARCOpts.cpp.
Function Documentation
AppendMDNodeToInstForPtr()
void AppendMDNodeToInstForPtr (unsigned NodeId, Instruction * Inst, Value * Ptr, MDString * PtrSourceMDNodeID, Sequence OldSeq, Sequence NewSeq) static
A simple function to generate a MDNode which describes the change in state for Value *Ptr caused by Instruction *Inst.
Definition at line 876 of file ObjCARCOpts.cpp.
References llvm::MDNode::get(), llvm::Value::getContext(), SequenceToMDString(), and llvm::Instruction::setMetadata().
Referenced by GenerateARCAnnotation().
AppendMDNodeToSourcePtr()
MDString * AppendMDNodeToSourcePtr (unsigned NodeId, Value * Ptr) static
This function appends a unique ARCAnnotationProvenanceSourceMDKind id to an instruction so that we can track backwards when post processing via the llvm arc annotation processor tool. If the function is an
Definition at line 818 of file ObjCARCOpts.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::MDNode::get(), llvm::MDString::get(), llvm::Value::getContext(), llvm::Instruction::getMetadata(), llvm::Value::getName(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::Instruction::setMetadata(), and llvm::raw_string_ostream::str().
Referenced by GenerateARCAnnotation().
CheckForCanReleaseCFGHazard()
void CheckForCanReleaseCFGHazard (const Sequence SuccSSeq, const bool SuccSRRIKnownSafe, PtrState & S, bool & SomeSuccHasSame, bool & AllSuccsHaveSame, bool & NotAllSeqEqualButKnownSafe) static
If we have a Top Down pointer in the S_CanRelease state, make sure that there are no CFG hazards by checking the states of various bottom up pointers.
Definition at line 1586 of file ObjCARCOpts.cpp.
References llvm_unreachable.
CheckForUseCFGHazard()
void CheckForUseCFGHazard (const Sequence SuccSSeq, const bool SuccSRRIKnownSafe, PtrState & S, bool & SomeSuccHasSame, bool & AllSuccsHaveSame, bool & NotAllSeqEqualButKnownSafe, bool & ShouldContinue) static
If we have a top down pointer in the S_Use state, make sure that there are no CFG hazards by checking the states of various bottom up pointers.
Definition at line 1548 of file ObjCARCOpts.cpp.
References llvm_unreachable.
clear()
Visited clear ()
Referenced by llvm::SmallVectorImpl< PointerUnion< Function *, Node * > >::assign(), llvm::DWARFAbbreviationDeclaration::DWARFAbbreviationDeclaration(), llvm::DWARFAbbreviationDeclarationSet::DWARFAbbreviationDeclarationSet(), llvm::DWARFDebugAbbrev::DWARFDebugAbbrev(), llvm::WinCodeViewLineTables::endModule(), llvm::DWARFAbbreviationDeclaration::extract(), llvm::DWARFAbbreviationDeclarationSet::extract(), llvm::DWARFDebugAbbrev::extract(), llvm::DWARFDebugAranges::generate(), llvm::InterferenceCache::init(), llvm::DWARFDebugLine::LineTable::LineTable(), llvm::DataLayout::operator=(), llvm::DWARFDebugLine::LineTable::parse(), llvm::DWARFDebugLine::Prologue::parse(), llvm::DataLayout::reset(), llvm::DataLayout::~DataLayout(), and llvm::IntervalMap< SlotIndex, LiveInterval * >::~IntervalMap().
ComputePostOrders()
void ComputePostOrders (Function & F, SmallVectorImpl< BasicBlock * > & PostOrder, SmallVectorImpl< BasicBlock * > & ReverseCFGPostOrder, unsigned NoObjCARCExceptionsMDKind, DenseMap< const BasicBlock *, BBState > & BBStates) static
The visited set, for doing DFS walks.
Definition at line 2166 of file ObjCARCOpts.cpp.
References llvm::BasicBlock::back(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::cast(), llvm::SmallPtrSetImplBase::clear(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallVectorBase::empty(), llvm::SmallPtrSetImpl< PtrType >::erase(), F, I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::pred_begin(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
createObjCARCOptPass()
objc ObjC ARC false Pass * llvm::createObjCARCOptPass ()
Definition at line 1177 of file ObjCARCOpts.cpp.
References createObjCARCOptPass().
Referenced by createObjCARCOptPass().
DEBUG()
DEBUG (dbgs()<< "Erasing: "<< *Retain<< "\nErasing: "<< *Autorelease<< "\n")
References Autorelease, and Retain.
EraseInstruction() [1/2]
EraseInstruction (Autorelease)
References Autorelease.
EraseInstruction() [2/2]
EraseInstruction (Retain)
References Retain.
FindPredecessorRetainWithSafePath()
CallInst * FindPredecessorRetainWithSafePath (const Value * Arg, BasicBlock * BB, Instruction * Autorelease, SmallPtrSetImpl< Instruction * > & DepInsts, SmallPtrSetImpl< const BasicBlock * > & Visited, ProvenanceAnalysis & PA) static
Find a dependent retain that precedes the given autorelease for which there is nothing in between the two instructions that can affect the ref count of Arg.
Definition at line 2847 of file ObjCARCOpts.cpp.
References Autorelease, llvm::SmallPtrSetImpl< PtrType >::begin(), llvm::objcarc::CanChangeRetainCount, llvm::dyn_cast_or_null(), llvm::objcarc::FindDependencies(), llvm::objcarc::GetBasicInstructionClass(), llvm::objcarc::GetObjCArg(), llvm::objcarc::IsRetain(), Retain, and llvm::SmallPtrSetImplBase::size().
GenerateARCAnnotation()
void GenerateARCAnnotation (unsigned InstMDId, unsigned PtrMDId, Instruction * Inst, Value * Ptr, Sequence OldSeq, Sequence NewSeq) static
Adds a source annotation to pointer and a state change annotation to Inst referencing the source annotation and the old/new state of pointer.
Definition at line 976 of file ObjCARCOpts.cpp.
References AppendMDNodeToInstForPtr(), AppendMDNodeToSourcePtr(), ARCAnnotationTargetIdentifier, EnableARCAnnotations, llvm::StringRef::equals(), and llvm::Value::getName().
GenerateARCBBEntranceAnnotation()
void GenerateARCBBEntranceAnnotation (const char * Name, BasicBlock * BB, Value * Ptr, Sequence Seq) static
Add to the beginning of the basic block llvm.ptr.annotations which show the state of a pointer at the entrance to a basic block.
Definition at line 893 of file ObjCARCOpts.cpp.
References ARCAnnotationTargetIdentifier, llvm::cast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall2(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateGlobalStringPtr(), llvm::StringRef::equals(), llvm::FunctionType::get(), llvm::Module::getContext(), llvm::BasicBlock::getFirstInsertionPt(), llvm::Module::getGlobalVariable(), llvm::Type::getInt8Ty(), llvm::Value::getName(), llvm::Module::getOrInsertFunction(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), llvm::GlobalValue::InternalLinkage, Name, and SequenceToString().
GenerateARCBBTerminatorAnnotation()
void GenerateARCBBTerminatorAnnotation (const char * Name, BasicBlock * BB, Value * Ptr, Sequence Seq) static
Add to the end of the basic block llvm.ptr.annotations which show the state of the pointer at the bottom of the basic block.
Definition at line 935 of file ObjCARCOpts.cpp.
References ARCAnnotationTargetIdentifier, llvm::cast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall2(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateGlobalStringPtr(), llvm::BasicBlock::end(), llvm::StringRef::equals(), llvm::FunctionType::get(), llvm::Module::getContext(), llvm::Module::getGlobalVariable(), llvm::Type::getInt8Ty(), llvm::Value::getName(), llvm::Module::getOrInsertFunction(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), llvm::GlobalValue::InternalLinkage, Name, and SequenceToString().
HasSafePathToPredecessorCall()
bool HasSafePathToPredecessorCall (const Value * Arg, Instruction * Retain, SmallPtrSetImpl< Instruction * > & DepInsts, SmallPtrSetImpl< const BasicBlock * > & Visited, ProvenanceAnalysis & PA) static
Check if there is a dependent call earlier that does not have anything in between the Retain and the call that can affect the reference count of their shared pointer argument. Note that Retain need not be in BB.
Definition at line 2819 of file ObjCARCOpts.cpp.
References llvm::SmallPtrSetImpl< PtrType >::begin(), llvm::Call, llvm::objcarc::CanChangeRetainCount, llvm::dyn_cast_or_null(), llvm::objcarc::FindDependencies(), llvm::objcarc::GetBasicInstructionClass(), llvm::objcarc::IC_Call, llvm::objcarc::IC_CallOrUser, Retain, and llvm::SmallPtrSetImplBase::size().
if()
if (! Autorelease)
References Autorelease.
Referenced by llvm::object::Archive::Archive(), llvm::ARMBaseRegisterInfo::ARMBaseRegisterInfo(), canBeFeederToNewValueJump(), llvm::GenericScheduler::checkAcyclicLatency(), llvm::DWARFContextInMemory::DWARFContextInMemory(), llvm::object::ELFFile< ELFT >::ELFFile(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::object::IRObjectFile::IRObjectFile(), isMoveInstr(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), LoopIsOuterMostWithPredecessor(), llvm::MCAsmLayout::MCAsmLayout(), predictValueUseListOrderImpl(), predictValueUseListOrderImpl(), llvm::VLIWMachineScheduler::schedule(), llvm::GenericSchedulerBase::setPolicy(), llvm::Value::Value(), llvm::ValueEnumerator::ValueEnumerator(), llvm::X86Subtarget::X86Subtarget(), and llvm::X86TargetMachine::X86TargetMachine().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (ObjCARCOpt , "objc-arc" , "ObjC ARC optimization" , false , false)
References INITIALIZE_PASS_DEPENDENCY, and INITIALIZE_PASS_END.
MergeSeqs()
Sequence MergeSeqs (Sequence A, Sequence B, bool TopDown) static
Definition at line 310 of file ObjCARCOpts.cpp.
References std::swap().
SequenceToMDString()
MDString * SequenceToMDString (LLVMContext & Context, Sequence A) static
Helper function to change a Sequence into a String object using our overload for raw_ostream so we only have printing code in one location.
Definition at line 869 of file ObjCARCOpts.cpp.
References llvm::MDString::get(), and SequenceToString().
Referenced by AppendMDNodeToInstForPtr().
SequenceToString()
std::string SequenceToString (Sequence A) static
Definition at line 860 of file ObjCARCOpts.cpp.
References llvm::raw_string_ostream::str().
Referenced by GenerateARCBBEntranceAnnotation(), GenerateARCBBTerminatorAnnotation(), and SequenceToMDString().
STATISTIC() [1/10]
STATISTIC (NumAutoreleases , "Number of autoreleases converted to releases")
STATISTIC() [2/10]
STATISTIC (NumNoops , "Number of no-op objc calls eliminated")
STATISTIC() [3/10]
STATISTIC (NumPartialNoops , "Number of partially no-op objc calls eliminated")
STATISTIC() [4/10]
STATISTIC (NumPeeps , "Number of calls peephole-optimized")
STATISTIC() [5/10]
STATISTIC (NumReleasesAfterOpt , "Number of releases after optimization")
STATISTIC() [6/10]
STATISTIC (NumReleasesBeforeOpt , "Number of releases before optimization")
STATISTIC() [7/10]
STATISTIC (NumRetainsAfterOpt , "Number of retains after optimization")
STATISTIC() [8/10]
STATISTIC (NumRetainsBeforeOpt , "Number of retains before optimization")
STATISTIC() [9/10]
STATISTIC (NumRets , "Number of return value forwarding " "retain+autoreleases eliminated")
References NumRets.
STATISTIC() [10/10]
STATISTIC (NumRRs , "Number of retain+release paths eliminated")
Variable Documentation
arc
objc arc
Definition at line 1175 of file ObjCARCOpts.cpp.
ARCAnnotationTargetIdentifier
cl::opt< std::string > ARCAnnotationTargetIdentifier("objc-arc-annotation-target-identifier", cl::init(""), cl::desc("filter out all data flow annotations " "but those that apply to the given " "target llvm identifier.")) ("objc-arc-annotation-target-identifier" , cl::init("") , cl::desc("filter out all data flow annotations " "but those that apply to the given " "target llvm identifier.")) static
Referenced by GenerateARCAnnotation(), GenerateARCBBEntranceAnnotation(), and GenerateARCBBTerminatorAnnotation().
Autorelease
CallInst* Autorelease
Initial value:
=
      FindPredecessorAutoreleaseWithSafePath(Arg, BB, Ret,
                                             DependingInstructions, Visited,
                                             PA)
Look for an `‘autorelease’' instruction dependent on Arg such that there are / no instructions dependent on Arg that need a positive ref count in between / the autorelease and the ret. static CallInst * FindPredecessorAutoreleaseWithSafePath(const Value *Arg, BasicBlock *BB, ReturnInst *Ret, SmallPtrSetImpl<Instruction *> &DepInsts, SmallPtrSetImpl<const BasicBlock *> &V, ProvenanceAnalysis &PA) { FindDependencies(NeedsPositiveRetainCount, Arg, BB, Ret, DepInsts, V, PA); if (DepInsts.size() != 1) return nullptr;
CallInst *Autorelease = dyn_cast_or_null<CallInst>(*DepInsts.begin()); if (!Autorelease) return nullptr; InstructionClass AutoreleaseClass = GetBasicInstructionClass(Autorelease); if (!IsAutorelease(AutoreleaseClass)) return nullptr; if (GetObjCArg(Autorelease) != Arg) return nullptr;
return Autorelease; }
/ Look for this pattern: /
///    %call = call i8* @something(...)
///    %2 = call i8* @objc_retain(i8* %call)
///    %3 = call i8* @objc_autorelease(i8* %2)
///    ret i8* %3
///
/ And delete the retain and autorelease. void ObjCARCOpt::OptimizeReturns(Function &F) { if (!F.getReturnType()->isPointerTy()) return;
DEBUG(dbgs() << "\n== ObjCARCOpt::OptimizeReturns ==\n");
SmallPtrSet<Instruction *, 4> DependingInstructions; SmallPtrSet<const BasicBlock *, 4> Visited; for (Function::iterator FI = F.begin(), FE = F.end(); FI != FE; ++FI) { BasicBlock *BB = FI; ReturnInst *Ret = dyn_cast<ReturnInst>(&BB->back());
DEBUG(dbgs() << "Visiting: " << *Ret << "\n");
if (!Ret) continue;
const Value *Arg = StripPointerCastsAndObjCCalls(Ret->getOperand(0));
Look for an `‘autorelease’' instruction that is a predecessor of Ret and
Definition at line 2927 of file ObjCARCOpts.cpp.
Referenced by DEBUG(), EraseInstruction(), FindPredecessorRetainWithSafePath(), if(), and STATISTIC().
Changed
Changed = true
Definition at line 2958 of file ObjCARCOpts.cpp.
Referenced by CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), llvm::MachineBasicBlock::CorrectExtraCFGEdges(), llvm::DeleteDeadPHIs(), DeleteTriviallyDeadInstructions(), llvm::DependenceAnalysis::depends(), llvm::FPPassManager::doFinalization(), llvm::legacy::FunctionPassManagerImpl::doFinalization(), llvm::FPPassManager::doInitialization(), llvm::legacy::FunctionPassManagerImpl::doInitialization(), llvm::EliminateDuplicatePHINodes(), llvm::finalizeBundles(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), FindLIVLoopCondition(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), llvm::formLCSSA(), llvm::formLCSSARecursively(), ForwardSwitchConditionToPHI(), llvm::DependenceAnalysis::getSplitIteration(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::SpillPlacement::iterate(), iterativelyFlattenCFG(), iterativelySimplifyCFG(), LinearizeExprTree(), llvm::Loop::makeLoopInvariant(), llvm::Loop::makeLoopInvariant(), markAliveBlocks(), mergeEmptyReturnBlocks(), OptimizeAwayTrappingUsesOfLoads(), OptimizeAwayTrappingUsesOfValue(), llvm::SymbolRewriter::ExplicitRewriteDescriptor< DT, ValueType, Get >::performOnModule(), llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator >::performOnModule(), llvm::removeUnreachableBlocks(), llvm::BitsInit::resolveReferences(), llvm::ListInit::resolveReferences(), llvm::DAGTypeLegalizer::run(), llvm::legacy::FunctionPassManagerImpl::run(), llvm::legacy::PassManagerImpl::run(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::RGPassManager::runOnFunction(), llvm::FPPassManager::runOnModule(), llvm::Inliner::runOnSCC(), llvm::set_union(), llvm::ScalarEvolution::SimplifyICmpOperands(), llvm::simplifyLoop(), llvm::simplifyLoopIVs(), simplifyOneLoop(), SinkThenElseCodeToEnd(), STATISTIC(), STATISTIC(), STATISTIC(), llvm::StripDebugInfo(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
DisableCheckForCFGHazards
cl::opt< bool > DisableCheckForCFGHazards("disable-objc-arc-checkforcfghazards", cl::init(false), cl::desc("Disable check for cfg hazards when " "annotating")) ("disable-objc-arc-checkforcfghazards" , cl::init(false) , cl::desc("Disable check for cfg hazards when " "annotating")) static
EnableARCAnnotations
cl::opt< bool > EnableARCAnnotations("enable-objc-arc-annotations", cl::init(false), cl::desc("Enable emission of arc data flow analysis " "annotations")) ("enable-objc-arc-annotations" , cl::init(false) , cl::desc("Enable emission of arc data flow analysis " "annotations")) static
Enable/disable ARC sequence annotations.
Referenced by GenerateARCAnnotation().
false
objc ObjC ARC false
Definition at line 1175 of file ObjCARCOpts.cpp.
HasSafePathToCall
bool HasSafePathToCall
Initial value:
= HasSafePathToPredecessorCall(Arg, Retain,
                                                          DependingInstructions,
                                                          Visited, PA)
Definition at line 2948 of file ObjCARCOpts.cpp.
ID
char ObjCARCOpt::ID = 0 static
Definition at line 1163 of file ObjCARCOpts.cpp.
NumRets
NumRets
Definition at line 2959 of file ObjCARCOpts.cpp.
Referenced by STATISTIC().
optimization
objc ObjC ARC optimization
Definition at line 1175 of file ObjCARCOpts.cpp.
Retain
CallInst* Retain
Initial value:
=
      FindPredecessorRetainWithSafePath(Arg, BB, Autorelease,
                                        DependingInstructions, Visited, PA)
Definition at line 2937 of file ObjCARCOpts.cpp.
Referenced by DEBUG(), EraseInstruction(), FindPredecessorRetainWithSafePath(), llvm::generateDITypeIdentifierMap(), HasSafePathToPredecessorCall(), and STATISTIC().