LLVM: Instruction Builders
LLVM API Documentation
Instruction Builders
LLVM-C: C interface to LLVM
Functions
LLVMBuilderRef LLVMCreateBuilderInContext (LLVMContextRef C)
LLVMBuilderRef LLVMCreateBuilder (void)
void LLVMPositionBuilder (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Instr)
void LLVMPositionBuilderBefore (LLVMBuilderRef Builder, LLVMValueRef Instr)
void LLVMPositionBuilderAtEnd (LLVMBuilderRef Builder, LLVMBasicBlockRef Block)
LLVMBasicBlockRef LLVMGetInsertBlock (LLVMBuilderRef Builder)
void LLVMClearInsertionPosition (LLVMBuilderRef Builder)
void LLVMInsertIntoBuilder (LLVMBuilderRef Builder, LLVMValueRef Instr)
void LLVMInsertIntoBuilderWithName (LLVMBuilderRef Builder, LLVMValueRef Instr, const char *Name)
void LLVMDisposeBuilder (LLVMBuilderRef Builder)
void LLVMSetCurrentDebugLocation (LLVMBuilderRef Builder, LLVMValueRef L)
LLVMValueRef LLVMGetCurrentDebugLocation (LLVMBuilderRef Builder)
void LLVMSetInstDebugLocation (LLVMBuilderRef Builder, LLVMValueRef Inst)
LLVMValueRef LLVMBuildRetVoid (LLVMBuilderRef)
LLVMValueRef LLVMBuildRet (LLVMBuilderRef, LLVMValueRef V)
LLVMValueRef LLVMBuildAggregateRet (LLVMBuilderRef, LLVMValueRef *RetVals, unsigned N)
LLVMValueRef LLVMBuildBr (LLVMBuilderRef, LLVMBasicBlockRef Dest)
LLVMValueRef LLVMBuildCondBr (LLVMBuilderRef, LLVMValueRef If, LLVMBasicBlockRef Then, LLVMBasicBlockRef Else)
LLVMValueRef LLVMBuildSwitch (LLVMBuilderRef, LLVMValueRef V, LLVMBasicBlockRef Else, unsigned NumCases)
LLVMValueRef LLVMBuildIndirectBr (LLVMBuilderRef B, LLVMValueRef Addr, unsigned NumDests)
LLVMValueRef LLVMBuildInvoke (LLVMBuilderRef, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char *Name)
LLVMValueRef LLVMBuildLandingPad (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PersFn, unsigned NumClauses, const char *Name)
LLVMValueRef LLVMBuildResume (LLVMBuilderRef B, LLVMValueRef Exn)
LLVMValueRef LLVMBuildUnreachable (LLVMBuilderRef)
void LLVMAddCase (LLVMValueRef Switch, LLVMValueRef OnVal, LLVMBasicBlockRef Dest)
void LLVMAddDestination (LLVMValueRef IndirectBr, LLVMBasicBlockRef Dest)
void LLVMAddClause (LLVMValueRef LandingPad, LLVMValueRef ClauseVal)
void LLVMSetCleanup (LLVMValueRef LandingPad, LLVMBool Val)
LLVMValueRef LLVMBuildAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildUDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildExactSDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildURem (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSRem (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFRem (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildShl (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildLShr (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildAShr (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildAnd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildOr (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildXor (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildBinOp (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNeg (LLVMBuilderRef, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNSWNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNUWNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildFNeg (LLVMBuilderRef, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNot (LLVMBuilderRef, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildMalloc (LLVMBuilderRef, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildArrayMalloc (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildAlloca (LLVMBuilderRef, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildArrayAlloca (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildFree (LLVMBuilderRef, LLVMValueRef PointerVal)
LLVMValueRef LLVMBuildLoad (LLVMBuilderRef, LLVMValueRef PointerVal, const char *Name)
LLVMValueRef LLVMBuildStore (LLVMBuilderRef, LLVMValueRef Val, LLVMValueRef Ptr)
LLVMValueRef LLVMBuildGEP (LLVMBuilderRef B, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVMValueRef LLVMBuildInBoundsGEP (LLVMBuilderRef B, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVMValueRef LLVMBuildStructGEP (LLVMBuilderRef B, LLVMValueRef Pointer, unsigned Idx, const char *Name)
LLVMValueRef LLVMBuildGlobalString (LLVMBuilderRef B, const char *Str, const char *Name)
LLVMValueRef LLVMBuildGlobalStringPtr (LLVMBuilderRef B, const char *Str, const char *Name)
LLVMBool LLVMGetVolatile (LLVMValueRef MemoryAccessInst)
void LLVMSetVolatile (LLVMValueRef MemoryAccessInst, LLVMBool IsVolatile)
LLVMValueRef LLVMBuildTrunc (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildZExt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSExt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPToUI (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPToSI (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildUIToFP (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSIToFP (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPTrunc (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPExt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildPtrToInt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildIntToPtr (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildAddrSpaceCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildZExtOrBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSExtOrBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildTruncOrBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildCast (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildPointerCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildIntCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildICmp (LLVMBuilderRef, LLVMIntPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFCmp (LLVMBuilderRef, LLVMRealPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildPhi (LLVMBuilderRef, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildCall (LLVMBuilderRef, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVMValueRef LLVMBuildSelect (LLVMBuilderRef, LLVMValueRef If, LLVMValueRef Then, LLVMValueRef Else, const char *Name)
LLVMValueRef LLVMBuildVAArg (LLVMBuilderRef, LLVMValueRef List, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildExtractElement (LLVMBuilderRef, LLVMValueRef VecVal, LLVMValueRef Index, const char *Name)
LLVMValueRef LLVMBuildInsertElement (LLVMBuilderRef, LLVMValueRef VecVal, LLVMValueRef EltVal, LLVMValueRef Index, const char *Name)
LLVMValueRef LLVMBuildShuffleVector (LLVMBuilderRef, LLVMValueRef V1, LLVMValueRef V2, LLVMValueRef Mask, const char *Name)
LLVMValueRef LLVMBuildExtractValue (LLVMBuilderRef, LLVMValueRef AggVal, unsigned Index, const char *Name)
LLVMValueRef LLVMBuildInsertValue (LLVMBuilderRef, LLVMValueRef AggVal, LLVMValueRef EltVal, unsigned Index, const char *Name)
LLVMValueRef LLVMBuildIsNull (LLVMBuilderRef, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildIsNotNull (LLVMBuilderRef, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildPtrDiff (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFence (LLVMBuilderRef B, LLVMAtomicOrdering ordering, LLVMBool singleThread, const char *Name)
LLVMValueRef LLVMBuildAtomicRMW (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, LLVMBool singleThread)
Detailed Description
An instruction builder represents a point within a basic block and is the exclusive means of building instructions using the C interface.
Function Documentation
LLVMAddCase()
void LLVMAddCase (LLVMValueRef Switch, LLVMValueRef OnVal, LLVMBasicBlockRef Dest)
Definition at line 2258 of file Core.cpp.
References llvm::unwrap().
LLVMAddClause()
void LLVMAddClause (LLVMValueRef LandingPad, LLVMValueRef ClauseVal)
Definition at line 2267 of file Core.cpp.
References llvm::cast(), and llvm::unwrap().
LLVMAddDestination()
void LLVMAddDestination (LLVMValueRef IndirectBr, LLVMBasicBlockRef Dest)
Definition at line 2263 of file Core.cpp.
References llvm::unwrap().
LLVMBuildAdd()
LLVMValueRef LLVMBuildAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2278 of file Core.cpp.
References CreateAdd(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildAddrSpaceCast()
LLVMValueRef LLVMBuildAddrSpaceCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2610 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildAggregateRet()
LLVMValueRef LLVMBuildAggregateRet (LLVMBuilderRef B, LLVMValueRef * RetVals, unsigned N)
Definition at line 2209 of file Core.cpp.
References N, llvm::unwrap(), and llvm::wrap().
LLVMBuildAlloca()
LLVMValueRef LLVMBuildAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 2456 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildAnd()
LLVMValueRef LLVMBuildAnd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2388 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildArrayAlloca()
LLVMValueRef LLVMBuildArrayAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char * Name)
Definition at line 2461 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildArrayMalloc()
LLVMValueRef LLVMBuildArrayMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char * Name)
Definition at line 2445 of file Core.cpp.
References llvm::CallInst::CreateMalloc(), llvm::Type::getInt32Ty(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantExpr::getTruncOrBitCast(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildAShr()
LLVMValueRef LLVMBuildAShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2383 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildAtomicRMW()
LLVMValueRef LLVMBuildAtomicRMW (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, LLVMBool singleThread)
Definition at line 2744 of file Core.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::CrossThread, LLVMAtomicRMWBinOpAdd, LLVMAtomicRMWBinOpAnd, LLVMAtomicRMWBinOpMax, LLVMAtomicRMWBinOpMin, LLVMAtomicRMWBinOpNand, LLVMAtomicRMWBinOpOr, LLVMAtomicRMWBinOpSub, LLVMAtomicRMWBinOpUMax, LLVMAtomicRMWBinOpUMin, LLVMAtomicRMWBinOpXchg, LLVMAtomicRMWBinOpXor, mapFromLLVMOrdering(), llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::SingleThread, llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::unwrap(), llvm::wrap(), llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
LLVMBuildBinOp()
LLVMValueRef LLVMBuildBinOp (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2403 of file Core.cpp.
References map_from_llvmopcode(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildBitCast()
LLVMValueRef LLVMBuildBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2605 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildBr()
LLVMValueRef LLVMBuildBr (LLVMBuilderRef B, LLVMBasicBlockRef Dest)
Definition at line 2214 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildCall()
LLVMValueRef LLVMBuildCall (LLVMBuilderRef B, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 2677 of file Core.cpp.
References llvm::makeArrayRef(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildCast()
LLVMValueRef LLVMBuildCast (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2633 of file Core.cpp.
References map_from_llvmopcode(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildCondBr()
LLVMValueRef LLVMBuildCondBr (LLVMBuilderRef B, LLVMValueRef If, LLVMBasicBlockRef Then, LLVMBasicBlockRef Else)
Definition at line 2218 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildExactSDiv()
LLVMValueRef LLVMBuildExactSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2348 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildExtractElement()
LLVMValueRef LLVMBuildExtractElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef Index, const char * Name)
Definition at line 2697 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildExtractValue()
LLVMValueRef LLVMBuildExtractValue (LLVMBuilderRef B, LLVMValueRef AggVal, unsigned Index, const char * Name)
Definition at line 2717 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFAdd()
LLVMValueRef LLVMBuildFAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2293 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFCmp()
LLVMValueRef LLVMBuildFCmp (LLVMBuilderRef B, LLVMRealPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2664 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFDiv()
LLVMValueRef LLVMBuildFDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2353 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFence()
LLVMValueRef LLVMBuildFence (LLVMBuilderRef B, LLVMAtomicOrdering ordering, LLVMBool singleThread, const char * Name)
Definition at line 2497 of file Core.cpp.
References llvm::CrossThread, mapFromLLVMOrdering(), Name, llvm::SingleThread, llvm::unwrap(), and llvm::wrap().
LLVMBuildFMul()
LLVMValueRef LLVMBuildFMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2333 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFNeg()
LLVMValueRef LLVMBuildFNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 2424 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFPCast()
LLVMValueRef LLVMBuildFPCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2650 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFPExt()
LLVMValueRef LLVMBuildFPExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2590 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFPToSI()
LLVMValueRef LLVMBuildFPToSI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2570 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFPToUI()
LLVMValueRef LLVMBuildFPToUI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2565 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFPTrunc()
LLVMValueRef LLVMBuildFPTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2585 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFree()
LLVMValueRef LLVMBuildFree (LLVMBuilderRef B, LLVMValueRef PointerVal)
Definition at line 2466 of file Core.cpp.
References llvm::CallInst::CreateFree(), llvm::unwrap(), and llvm::wrap().
LLVMBuildFRem()
LLVMValueRef LLVMBuildFRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2368 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFSub()
LLVMValueRef LLVMBuildFSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2313 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildGEP()
LLVMValueRef LLVMBuildGEP (LLVMBuilderRef B, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name)
Definition at line 2505 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildGlobalString()
LLVMValueRef LLVMBuildGlobalString (LLVMBuilderRef B, const char * Str, const char * Name)
Definition at line 2524 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildGlobalStringPtr()
LLVMValueRef LLVMBuildGlobalStringPtr (LLVMBuilderRef B, const char * Str, const char * Name)
Definition at line 2529 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildICmp()
LLVMValueRef LLVMBuildICmp (LLVMBuilderRef B, LLVMIntPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2657 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildInBoundsGEP()
LLVMValueRef LLVMBuildInBoundsGEP (LLVMBuilderRef B, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name)
Definition at line 2512 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildIndirectBr()
LLVMValueRef LLVMBuildIndirectBr (LLVMBuilderRef B, LLVMValueRef Addr, unsigned NumDests)
Definition at line 2228 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildInsertElement()
LLVMValueRef LLVMBuildInsertElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef EltVal, LLVMValueRef Index, const char * Name)
Definition at line 2703 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildInsertValue()
LLVMValueRef LLVMBuildInsertValue (LLVMBuilderRef B, LLVMValueRef AggVal, LLVMValueRef EltVal, unsigned Index, const char * Name)
Definition at line 2722 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildIntCast()
LLVMValueRef LLVMBuildIntCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2644 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildIntToPtr()
LLVMValueRef LLVMBuildIntToPtr (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2600 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildInvoke()
LLVMValueRef LLVMBuildInvoke (LLVMBuilderRef B, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char * Name)
Definition at line 2233 of file Core.cpp.
References llvm::makeArrayRef(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildIsNotNull()
LLVMValueRef LLVMBuildIsNotNull (LLVMBuilderRef B, LLVMValueRef Val, const char * Name)
Definition at line 2734 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildIsNull()
LLVMValueRef LLVMBuildIsNull (LLVMBuilderRef B, LLVMValueRef Val, const char * Name)
Definition at line 2729 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildLandingPad()
LLVMValueRef LLVMBuildLandingPad (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PersFn, unsigned NumClauses, const char * Name)
Definition at line 2242 of file Core.cpp.
References llvm::cast(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildLoad()
LLVMValueRef LLVMBuildLoad (LLVMBuilderRef B, LLVMValueRef PointerVal, const char * Name)
Definition at line 2472 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildLShr()
LLVMValueRef LLVMBuildLShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2378 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildMalloc()
LLVMValueRef LLVMBuildMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 2434 of file Core.cpp.
References llvm::CallInst::CreateMalloc(), llvm::Type::getInt32Ty(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantExpr::getTruncOrBitCast(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildMul()
LLVMValueRef LLVMBuildMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2318 of file Core.cpp.
References CreateMul(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNeg()
LLVMValueRef LLVMBuildNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 2410 of file Core.cpp.
References CreateNeg(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNot()
LLVMValueRef LLVMBuildNot (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 2428 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWAdd()
LLVMValueRef LLVMBuildNSWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2283 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWMul()
LLVMValueRef LLVMBuildNSWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2323 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWNeg()
LLVMValueRef LLVMBuildNSWNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 2414 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWSub()
LLVMValueRef LLVMBuildNSWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2303 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWAdd()
LLVMValueRef LLVMBuildNUWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2288 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWMul()
LLVMValueRef LLVMBuildNUWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2328 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWNeg()
LLVMValueRef LLVMBuildNUWNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 2419 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWSub()
LLVMValueRef LLVMBuildNUWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2308 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildOr()
LLVMValueRef LLVMBuildOr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2393 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildPhi()
LLVMValueRef LLVMBuildPhi (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 2673 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildPointerCast()
LLVMValueRef LLVMBuildPointerCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2639 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildPtrDiff()
LLVMValueRef LLVMBuildPtrDiff (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2739 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildPtrToInt()
LLVMValueRef LLVMBuildPtrToInt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2595 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildResume()
LLVMValueRef LLVMBuildResume (LLVMBuilderRef B, LLVMValueRef Exn)
Definition at line 2250 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildRet()
LLVMValueRef LLVMBuildRet (LLVMBuilderRef B, LLVMValueRef V)
Definition at line 2205 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildRetVoid()
LLVMValueRef LLVMBuildRetVoid (LLVMBuilderRef B)
Definition at line 2201 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildSDiv()
LLVMValueRef LLVMBuildSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2343 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSelect()
LLVMValueRef LLVMBuildSelect (LLVMBuilderRef B, LLVMValueRef If, LLVMValueRef Then, LLVMValueRef Else, const char * Name)
Definition at line 2685 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSExt()
LLVMValueRef LLVMBuildSExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2560 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSExtOrBitCast()
LLVMValueRef LLVMBuildSExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2621 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildShl()
LLVMValueRef LLVMBuildShl (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2373 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildShuffleVector()
LLVMValueRef LLVMBuildShuffleVector (LLVMBuilderRef B, LLVMValueRef V1, LLVMValueRef V2, LLVMValueRef Mask, const char * Name)
Definition at line 2710 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSIToFP()
LLVMValueRef LLVMBuildSIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2580 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSRem()
LLVMValueRef LLVMBuildSRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2363 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildStore()
LLVMValueRef LLVMBuildStore (LLVMBuilderRef B, LLVMValueRef Val, LLVMValueRef Ptr)
Definition at line 2477 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildStructGEP()
LLVMValueRef LLVMBuildStructGEP (LLVMBuilderRef B, LLVMValueRef Pointer, unsigned Idx, const char * Name)
Definition at line 2519 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSub()
LLVMValueRef LLVMBuildSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2298 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSwitch()
LLVMValueRef LLVMBuildSwitch (LLVMBuilderRef B, LLVMValueRef V, LLVMBasicBlockRef Else, unsigned NumCases)
Definition at line 2223 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildTrunc()
LLVMValueRef LLVMBuildTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2550 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildTruncOrBitCast()
LLVMValueRef LLVMBuildTruncOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2627 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildUDiv()
LLVMValueRef LLVMBuildUDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2338 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildUIToFP()
LLVMValueRef LLVMBuildUIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2575 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildUnreachable()
LLVMValueRef LLVMBuildUnreachable (LLVMBuilderRef B)
Definition at line 2254 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuildURem()
LLVMValueRef LLVMBuildURem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2358 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildVAArg()
LLVMValueRef LLVMBuildVAArg (LLVMBuilderRef B, LLVMValueRef List, LLVMTypeRef Ty, const char * Name)
Definition at line 2692 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildXor()
LLVMValueRef LLVMBuildXor (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 2398 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildZExt()
LLVMValueRef LLVMBuildZExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2555 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildZExtOrBitCast()
LLVMValueRef LLVMBuildZExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 2615 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMClearInsertionPosition()
void LLVMClearInsertionPosition (LLVMBuilderRef Builder)
Definition at line 2162 of file Core.cpp.
References llvm::unwrap().
LLVMCreateBuilder()
LLVMBuilderRef LLVMCreateBuilder (void)
Definition at line 2137 of file Core.cpp.
References LLVMCreateBuilderInContext(), and LLVMGetGlobalContext().
LLVMCreateBuilderInContext()
LLVMBuilderRef LLVMCreateBuilderInContext (LLVMContextRef C)
Definition at line 2133 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
Referenced by LLVMCreateBuilder().
LLVMDisposeBuilder()
void LLVMDisposeBuilder (LLVMBuilderRef Builder)
Definition at line 2175 of file Core.cpp.
References llvm::unwrap().
LLVMGetCurrentDebugLocation()
LLVMValueRef LLVMGetCurrentDebugLocation (LLVMBuilderRef Builder)
Definition at line 2187 of file Core.cpp.
References llvm::MetadataAsValue::get(), llvm::unwrap(), and llvm::wrap().
LLVMGetInsertBlock()
LLVMBasicBlockRef LLVMGetInsertBlock (LLVMBuilderRef Builder)
Definition at line 2158 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetVolatile()
LLVMBool LLVMGetVolatile (LLVMValueRef MemoryAccessInst)
Definition at line 2534 of file Core.cpp.
References llvm::cast(), llvm::dyn_cast(), P, and llvm::unwrap().
LLVMInsertIntoBuilder()
void LLVMInsertIntoBuilder (LLVMBuilderRef Builder, LLVMValueRef Instr)
Definition at line 2166 of file Core.cpp.
References llvm::unwrap().
LLVMInsertIntoBuilderWithName()
void LLVMInsertIntoBuilderWithName (LLVMBuilderRef Builder, LLVMValueRef Instr, const char * Name)
Definition at line 2170 of file Core.cpp.
References Name, and llvm::unwrap().
LLVMPositionBuilder()
void LLVMPositionBuilder (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Instr)
Definition at line 2141 of file Core.cpp.
References llvm::BasicBlock::end(), I, and llvm::unwrap().
LLVMPositionBuilderAtEnd()
void LLVMPositionBuilderAtEnd (LLVMBuilderRef Builder, LLVMBasicBlockRef Block)
Definition at line 2153 of file Core.cpp.
References llvm::unwrap().
LLVMPositionBuilderBefore()
void LLVMPositionBuilderBefore (LLVMBuilderRef Builder, LLVMValueRef Instr)
Definition at line 2148 of file Core.cpp.
References I, and llvm::unwrap().
LLVMSetCleanup()
void LLVMSetCleanup (LLVMValueRef LandingPad, LLVMBool Val)
Definition at line 2272 of file Core.cpp.
References llvm::unwrap().
LLVMSetCurrentDebugLocation()
void LLVMSetCurrentDebugLocation (LLVMBuilderRef Builder, LLVMValueRef L)
Definition at line 2181 of file Core.cpp.
References llvm::cast(), llvm::DebugLoc::getFromDILocation(), and llvm::unwrap().
LLVMSetInstDebugLocation()
void LLVMSetInstDebugLocation (LLVMBuilderRef Builder, LLVMValueRef Inst)
Definition at line 2194 of file Core.cpp.
References llvm::unwrap().
LLVMSetVolatile()
void LLVMSetVolatile (LLVMValueRef MemoryAccessInst, LLVMBool IsVolatile)
Definition at line 2541 of file Core.cpp.
References llvm::cast(), llvm::dyn_cast(), P, and llvm::unwrap().