LLVM: Analysis
LLVM API Documentation
Analysis
LLVM-C: C interface to LLVM
Enumerations
enum LLVMVerifierFailureAction { LLVMAbortProcessAction , LLVMPrintMessageAction , LLVMReturnStatusAction }
Functions
LLVMBool LLVMVerifyModule (LLVMModuleRef M, LLVMVerifierFailureAction Action, char **OutMessage)
LLVMBool LLVMVerifyFunction (LLVMValueRef Fn, LLVMVerifierFailureAction Action)
void LLVMViewFunctionCFG (LLVMValueRef Fn)
void LLVMViewFunctionCFGOnly (LLVMValueRef Fn)
Detailed Description
Enumeration Type Documentation
LLVMVerifierFailureAction
enum LLVMVerifierFailureAction
Enumerator
LLVMAbortProcessAction
LLVMPrintMessageAction
LLVMReturnStatusAction
Definition at line 35 of file llvm-c/Analysis.h.
Function Documentation
LLVMVerifyFunction()
LLVMBool LLVMVerifyFunction (LLVMValueRef Fn, LLVMVerifierFailureAction Action)
Definition at line 98 of file Analysis/Analysis.cpp.
References llvm::errs(), LLVMAbortProcessAction, LLVMReturnStatusAction, llvm::report_fatal_error(), llvm::unwrap(), and llvm::verifyFunction().
LLVMVerifyModule()
LLVMBool LLVMVerifyModule (LLVMModuleRef M, LLVMVerifierFailureAction Action, char ** OutMessage)
Definition at line 77 of file Analysis/Analysis.cpp.
References llvm::errs(), LLVMAbortProcessAction, LLVMReturnStatusAction, llvm::report_fatal_error(), llvm::raw_string_ostream::str(), llvm::unwrap(), and llvm::verifyModule().
LLVMViewFunctionCFG()
void LLVMViewFunctionCFG (LLVMValueRef Fn)
Definition at line 109 of file Analysis/Analysis.cpp.
References F, and llvm::unwrap().
LLVMViewFunctionCFGOnly()
void LLVMViewFunctionCFGOnly (LLVMValueRef Fn)
Definition at line 114 of file Analysis/Analysis.cpp.
References F, and llvm::unwrap().