LLVM: Metadata
LLVM API Documentation
Metadata
LLVM-C: C interface to LLVM » Core
Functions
LLVMValueRef LLVMMDStringInContext (LLVMContextRef C, const char *Str, unsigned SLen)
LLVMValueRef LLVMMDString (const char *Str, unsigned SLen)
LLVMValueRef LLVMMDNodeInContext (LLVMContextRef C, LLVMValueRef *Vals, unsigned Count)
LLVMValueRef LLVMMDNode (LLVMValueRef *Vals, unsigned Count)
const char * LLVMGetMDString (LLVMValueRef V, unsigned *Len)
unsigned LLVMGetMDNodeNumOperands (LLVMValueRef V)
void LLVMGetMDNodeOperands (LLVMValueRef V, LLVMValueRef *Dest)
Detailed Description
Function Documentation
LLVMGetMDNodeNumOperands()
unsigned LLVMGetMDNodeNumOperands (LLVMValueRef V)
Obtain the number of operands from an MDNode value.
Parameters
V MDNode to get number of operands from.
Returns
Number of operands of the MDNode.
Definition at line 764 of file Core.cpp.
References llvm::cast(), llvm::isa(), and llvm::unwrap().
Referenced by LLVMGetNumOperands().
LLVMGetMDNodeOperands()
void LLVMGetMDNodeOperands (LLVMValueRef V, LLVMValueRef * Dest)
Obtain the given MDNode's operands.
The passed LLVMValueRef pointer should point to enough memory to hold all of the operands of the given MDNode (see LLVMGetMDNodeNumOperands) as LLVMValueRefs. This memory will be populated with the LLVMValueRefs of the MDNode's operands.
Parameters
V MDNode to get the operands from.
Dest Destination array for operands.
Definition at line 772 of file Core.cpp.
References llvm::cast(), llvm::dyn_cast(), getMDNodeOperandImpl(), N, llvm::unwrap(), and llvm::wrap().
LLVMGetMDString()
const char * LLVMGetMDString (LLVMValueRef V, unsigned * Len)
Obtain the underlying string from a MDString value.
Parameters
V Instance to obtain string from.
Len Memory address which will hold length of returned string.
Returns
String data in MDString.
Definition at line 754 of file Core.cpp.
References llvm::dyn_cast(), and llvm::unwrap().
LLVMMDNode()
LLVMValueRef LLVMMDNode (LLVMValueRef * Vals, unsigned Count)
Obtain a MDNode value from the global context.
Definition at line 750 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMMDNodeInContext().
LLVMMDNodeInContext()
LLVMValueRef LLVMMDNodeInContext (LLVMContextRef C, LLVMValueRef * Vals, unsigned Count)
Obtain a MDNode value from a context.
The returned value corresponds to the llvm::MDNode class.
Definition at line 723 of file Core.cpp.
References llvm::dyn_cast(), llvm::ConstantAsMetadata::get(), llvm::LocalAsMetadata::get(), llvm::MDNode::get(), llvm::MetadataAsValue::get(), llvm::isa(), llvm::makeArrayRef(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMMDNode().
LLVMMDString()
LLVMValueRef LLVMMDString (const char * Str, unsigned SLen)
Obtain a MDString value from the global context.
Definition at line 719 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMMDStringInContext().
LLVMMDStringInContext()
LLVMValueRef LLVMMDStringInContext (LLVMContextRef C, const char * Str, unsigned SLen)
Obtain a MDString value from a context.
The returned instance corresponds to the llvm::MDString class.
The instance is specified by string data of a specified length. The string content is copied, so the backing memory can be freed after this function returns.
Definition at line 712 of file Core.cpp.
References llvm::MDString::get(), llvm::MetadataAsValue::get(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMMDString().