LLVM: Utility declarations/definitions specific to ARC.
LLVM API Documentation
Utility declarations/definitions specific to ARC.
Functions
static const Value * FindSingleUseIdentifiedObject (const Value *Arg)
This is similar to StripPointerCastsAndObjCCalls but it stops as soon as it finds a value with multiple uses.
static bool AreAnyUnderlyingObjectsAnAlloca (const Value *V)
Detailed Description
Function Documentation
AreAnyUnderlyingObjectsAnAlloca()
bool AreAnyUnderlyingObjectsAnAlloca (const Value * V) inline static
This is a wrapper around getUnderlyingObjCPtr along the lines of GetUnderlyingObjects except that it returns early when it sees the first alloca.
Definition at line 180 of file ObjCARCOpts.cpp.
References llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::objcarc::GetUnderlyingObjCPtr(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), P, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
FindSingleUseIdentifiedObject()
const Value * FindSingleUseIdentifiedObject (const Value * Arg) static
This is similar to StripPointerCastsAndObjCCalls but it stops as soon as it finds a value with multiple uses.
Definition at line 149 of file ObjCARCOpts.cpp.
References llvm::cast(), llvm::dyn_cast(), FindSingleUseIdentifiedObject(), llvm::objcarc::GetBasicInstructionClass(), llvm::Value::hasOneUse(), llvm::objcarc::IsForwarding(), llvm::objcarc::IsObjCIdentifiedObject(), llvm::objcarc::StripPointerCastsAndObjCCalls(), and llvm::Value::users().
Referenced by FindSingleUseIdentifiedObject().