LLVM: Vectorization transformations
LLVM API Documentation
Vectorization transformations
LLVM-C: C interface to LLVM » Transforms
Functions
void LLVMAddBBVectorizePass (LLVMPassManagerRef PM)
void LLVMAddLoopVectorizePass (LLVMPassManagerRef PM)
void LLVMAddSLPVectorizePass (LLVMPassManagerRef PM)
Detailed Description
Function Documentation
LLVMAddBBVectorizePass()
void LLVMAddBBVectorizePass (LLVMPassManagerRef PM)
See llvm::createBBVectorizePass function.
Definition at line 38 of file Vectorize.cpp.
References llvm::createBBVectorizePass(), and llvm::unwrap().
LLVMAddLoopVectorizePass()
void LLVMAddLoopVectorizePass (LLVMPassManagerRef PM)
See llvm::createLoopVectorizePass function.
Definition at line 42 of file Vectorize.cpp.
References llvm::createLoopVectorizePass(), and llvm::unwrap().
LLVMAddSLPVectorizePass()
void LLVMAddSLPVectorizePass (LLVMPassManagerRef PM)
See llvm::createSLPVectorizerPass function.
Definition at line 46 of file Vectorize.cpp.
References llvm::createSLPVectorizerPass(), and llvm::unwrap().