LLVM: Global Aliases
LLVM API Documentation
Global Aliases
LLVM-C: C interface to LLVM » Core » Values » Constants
Functions
LLVMValueRef LLVMAddAlias (LLVMModuleRef M, LLVMTypeRef Ty, LLVMValueRef Aliasee, const char *Name)
Detailed Description
This group contains function that operate on global alias values.
See also
llvm::GlobalAlias
Function Documentation
LLVMAddAlias()
LLVMValueRef LLVMAddAlias (LLVMModuleRef M, LLVMTypeRef Ty, LLVMValueRef Aliasee, const char * Name)
Definition at line 1628 of file Core.cpp.
References llvm::cast(), llvm::GlobalAlias::create(), llvm::GlobalValue::ExternalLinkage, Name, llvm::unwrap(), and llvm::wrap().