LLVM: Execution Engine
LLVM API Documentation
Execution Engine
LLVM-C: C interface to LLVM
Classes
struct LLVMMCJITCompilerOptions
Typedefs
typedef struct LLVMOpaqueGenericValue * LLVMGenericValueRef
typedef struct LLVMOpaqueExecutionEngine * LLVMExecutionEngineRef
typedef struct LLVMOpaqueMCJITMemoryManager * LLVMMCJITMemoryManagerRef
typedef uint8_t *(* LLVMMemoryManagerAllocateCodeSectionCallback) (void *Opaque, uintptr_t Size, unsigned Alignment, unsigned SectionID, const char *SectionName)
typedef uint8_t *(* LLVMMemoryManagerAllocateDataSectionCallback) (void *Opaque, uintptr_t Size, unsigned Alignment, unsigned SectionID, const char *SectionName, LLVMBool IsReadOnly)
typedef LLVMBool(* LLVMMemoryManagerFinalizeMemoryCallback) (void *Opaque, char **ErrMsg)
typedef void(* LLVMMemoryManagerDestroyCallback) (void *Opaque)
Functions
void LLVMLinkInMCJIT (void)
void LLVMLinkInInterpreter (void)
LLVMGenericValueRef LLVMCreateGenericValueOfInt (LLVMTypeRef Ty, unsigned long long N, LLVMBool IsSigned)
LLVMGenericValueRef LLVMCreateGenericValueOfPointer (void *P)
LLVMGenericValueRef LLVMCreateGenericValueOfFloat (LLVMTypeRef Ty, double N)
unsigned LLVMGenericValueIntWidth (LLVMGenericValueRef GenValRef)
unsigned long long LLVMGenericValueToInt (LLVMGenericValueRef GenVal, LLVMBool IsSigned)
void * LLVMGenericValueToPointer (LLVMGenericValueRef GenVal)
double LLVMGenericValueToFloat (LLVMTypeRef TyRef, LLVMGenericValueRef GenVal)
void LLVMDisposeGenericValue (LLVMGenericValueRef GenVal)
LLVMBool LLVMCreateExecutionEngineForModule (LLVMExecutionEngineRef *OutEE, LLVMModuleRef M, char **OutError)
LLVMBool LLVMCreateInterpreterForModule (LLVMExecutionEngineRef *OutInterp, LLVMModuleRef M, char **OutError)
LLVMBool LLVMCreateJITCompilerForModule (LLVMExecutionEngineRef *OutJIT, LLVMModuleRef M, unsigned OptLevel, char **OutError)
void LLVMInitializeMCJITCompilerOptions (struct LLVMMCJITCompilerOptions *Options, size_t SizeOfOptions)
LLVMBool LLVMCreateMCJITCompilerForModule (LLVMExecutionEngineRef *OutJIT, LLVMModuleRef M, struct LLVMMCJITCompilerOptions *Options, size_t SizeOfOptions, char **OutError)
LLVMBool LLVMCreateExecutionEngine (LLVMExecutionEngineRef *OutEE, LLVMModuleProviderRef MP, char **OutError)
LLVMBool LLVMCreateInterpreter (LLVMExecutionEngineRef *OutInterp, LLVMModuleProviderRef MP, char **OutError)
LLVMBool LLVMCreateJITCompiler (LLVMExecutionEngineRef *OutJIT, LLVMModuleProviderRef MP, unsigned OptLevel, char **OutError)
void LLVMDisposeExecutionEngine (LLVMExecutionEngineRef EE)
void LLVMRunStaticConstructors (LLVMExecutionEngineRef EE)
void LLVMRunStaticDestructors (LLVMExecutionEngineRef EE)
int LLVMRunFunctionAsMain (LLVMExecutionEngineRef EE, LLVMValueRef F, unsigned ArgC, const char *const *ArgV, const char *const *EnvP)
LLVMGenericValueRef LLVMRunFunction (LLVMExecutionEngineRef EE, LLVMValueRef F, unsigned NumArgs, LLVMGenericValueRef *Args)
void LLVMFreeMachineCodeForFunction (LLVMExecutionEngineRef EE, LLVMValueRef F)
void LLVMAddModule (LLVMExecutionEngineRef EE, LLVMModuleRef M)
void LLVMAddModuleProvider (LLVMExecutionEngineRef EE, LLVMModuleProviderRef MP)
LLVMBool LLVMRemoveModule (LLVMExecutionEngineRef EE, LLVMModuleRef M, LLVMModuleRef *OutMod, char **OutError)
LLVMBool LLVMRemoveModuleProvider (LLVMExecutionEngineRef EE, LLVMModuleProviderRef MP, LLVMModuleRef *OutMod, char **OutError)
LLVMBool LLVMFindFunction (LLVMExecutionEngineRef EE, const char *Name, LLVMValueRef *OutFn)
void * LLVMRecompileAndRelinkFunction (LLVMExecutionEngineRef EE, LLVMValueRef Fn)
LLVMTargetDataRef LLVMGetExecutionEngineTargetData (LLVMExecutionEngineRef EE)
LLVMTargetMachineRef LLVMGetExecutionEngineTargetMachine (LLVMExecutionEngineRef EE)
void LLVMAddGlobalMapping (LLVMExecutionEngineRef EE, LLVMValueRef Global, void *Addr)
void * LLVMGetPointerToGlobal (LLVMExecutionEngineRef EE, LLVMValueRef Global)
uint64_t LLVMGetGlobalValueAddress (LLVMExecutionEngineRef EE, const char *Name)
uint64_t LLVMGetFunctionAddress (LLVMExecutionEngineRef EE, const char *Name)
LLVMMCJITMemoryManagerRef LLVMCreateSimpleMCJITMemoryManager (void *Opaque, LLVMMemoryManagerAllocateCodeSectionCallback AllocateCodeSection, LLVMMemoryManagerAllocateDataSectionCallback AllocateDataSection, LLVMMemoryManagerFinalizeMemoryCallback FinalizeMemory, LLVMMemoryManagerDestroyCallback Destroy)
void LLVMDisposeMCJITMemoryManager (LLVMMCJITMemoryManagerRef MM)
Detailed Description
Typedef Documentation
LLVMExecutionEngineRef
typedef struct LLVMOpaqueExecutionEngine* LLVMExecutionEngineRef
Definition at line 41 of file llvm-c/ExecutionEngine.h.
LLVMGenericValueRef
typedef struct LLVMOpaqueGenericValue* LLVMGenericValueRef
Definition at line 40 of file llvm-c/ExecutionEngine.h.
LLVMMCJITMemoryManagerRef
typedef struct LLVMOpaqueMCJITMemoryManager* LLVMMCJITMemoryManagerRef
Definition at line 42 of file llvm-c/ExecutionEngine.h.
LLVMMemoryManagerAllocateCodeSectionCallback
typedef uint8_t *(* LLVMMemoryManagerAllocateCodeSectionCallback) (void *Opaque, uintptr_t Size, unsigned Alignment, unsigned SectionID, const char *SectionName)
Definition at line 179 of file llvm-c/ExecutionEngine.h.
LLVMMemoryManagerAllocateDataSectionCallback
typedef uint8_t *(* LLVMMemoryManagerAllocateDataSectionCallback) (void *Opaque, uintptr_t Size, unsigned Alignment, unsigned SectionID, const char *SectionName, LLVMBool IsReadOnly)
Definition at line 182 of file llvm-c/ExecutionEngine.h.
LLVMMemoryManagerDestroyCallback
typedef void(* LLVMMemoryManagerDestroyCallback) (void *Opaque)
Definition at line 187 of file llvm-c/ExecutionEngine.h.
LLVMMemoryManagerFinalizeMemoryCallback
typedef LLVMBool(* LLVMMemoryManagerFinalizeMemoryCallback) (void *Opaque, char **ErrMsg)
Definition at line 185 of file llvm-c/ExecutionEngine.h.
Function Documentation
LLVMAddGlobalMapping()
void LLVMAddGlobalMapping (LLVMExecutionEngineRef EE, LLVMValueRef Global, void * Addr)
Definition at line 320 of file ExecutionEngineBindings.cpp.
References llvm::unwrap().
LLVMAddModule()
void LLVMAddModule (LLVMExecutionEngineRef EE, LLVMModuleRef M)
Definition at line 272 of file ExecutionEngineBindings.cpp.
References llvm::unwrap().
Referenced by LLVMAddModuleProvider().
LLVMAddModuleProvider()
void LLVMAddModuleProvider (LLVMExecutionEngineRef EE, LLVMModuleProviderRef MP)
Deprecated: Use LLVMAddModule instead.
Definition at line 276 of file ExecutionEngineBindings.cpp.
References LLVMAddModule().
LLVMCreateExecutionEngine()
LLVMBool LLVMCreateExecutionEngine (LLVMExecutionEngineRef * OutEE, LLVMModuleProviderRef MP, char ** OutError)
Deprecated: Use LLVMCreateExecutionEngineForModule instead.
Definition at line 201 of file ExecutionEngineBindings.cpp.
References LLVMCreateExecutionEngineForModule().
LLVMCreateExecutionEngineForModule()
LLVMBool LLVMCreateExecutionEngineForModule (LLVMExecutionEngineRef * OutEE, LLVMModuleRef M, char ** OutError)
Definition at line 101 of file ExecutionEngineBindings.cpp.
References llvm::EngineBuilder::create(), llvm::EngineKind::Either, Error(), llvm::EngineBuilder::setEngineKind(), llvm::EngineBuilder::setErrorStr(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMCreateExecutionEngine().
LLVMCreateGenericValueOfFloat()
LLVMGenericValueRef LLVMCreateGenericValueOfFloat (LLVMTypeRef Ty, double N)
Definition at line 52 of file ExecutionEngineBindings.cpp.
References llvm::Type::DoubleTyID, llvm::GenericValue::DoubleVal, llvm::Type::FloatTyID, llvm::GenericValue::FloatVal, getTypeID(), llvm_unreachable, N, llvm::unwrap(), and llvm::wrap().
LLVMCreateGenericValueOfInt()
LLVMGenericValueRef LLVMCreateGenericValueOfInt (LLVMTypeRef Ty, unsigned long long N, LLVMBool IsSigned)
Definition at line 38 of file ExecutionEngineBindings.cpp.
References getBitWidth(), llvm::GenericValue::IntVal, N, llvm::unwrap(), and llvm::wrap().
LLVMCreateGenericValueOfPointer()
LLVMGenericValueRef LLVMCreateGenericValueOfPointer (void * P)
Definition at line 46 of file ExecutionEngineBindings.cpp.
References P, llvm::GenericValue::PointerVal, and llvm::wrap().
LLVMCreateInterpreter()
LLVMBool LLVMCreateInterpreter (LLVMExecutionEngineRef * OutInterp, LLVMModuleProviderRef MP, char ** OutError)
Deprecated: Use LLVMCreateInterpreterForModule instead.
Definition at line 210 of file ExecutionEngineBindings.cpp.
References LLVMCreateInterpreterForModule().
LLVMCreateInterpreterForModule()
LLVMBool LLVMCreateInterpreterForModule (LLVMExecutionEngineRef * OutInterp, LLVMModuleRef M, char ** OutError)
Definition at line 116 of file ExecutionEngineBindings.cpp.
References llvm::EngineBuilder::create(), Error(), llvm::EngineKind::Interpreter, llvm::EngineBuilder::setEngineKind(), llvm::EngineBuilder::setErrorStr(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMCreateInterpreter().
LLVMCreateJITCompiler()
LLVMBool LLVMCreateJITCompiler (LLVMExecutionEngineRef * OutJIT, LLVMModuleProviderRef MP, unsigned OptLevel, char ** OutError)
Deprecated: Use LLVMCreateJITCompilerForModule instead.
Definition at line 219 of file ExecutionEngineBindings.cpp.
References LLVMCreateJITCompilerForModule().
LLVMCreateJITCompilerForModule()
LLVMBool LLVMCreateJITCompilerForModule (LLVMExecutionEngineRef * OutJIT, LLVMModuleRef M, unsigned OptLevel, char ** OutError)
Definition at line 131 of file ExecutionEngineBindings.cpp.
References llvm::EngineBuilder::create(), Error(), llvm::EngineKind::JIT, llvm::EngineBuilder::setEngineKind(), llvm::EngineBuilder::setErrorStr(), llvm::EngineBuilder::setOptLevel(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMCreateJITCompiler().
LLVMCreateMCJITCompilerForModule()
LLVMBool LLVMCreateMCJITCompilerForModule (LLVMExecutionEngineRef * OutJIT, LLVMModuleRef M, struct LLVMMCJITCompilerOptions * Options, size_t SizeOfOptions, char ** OutError)
Create an MCJIT execution engine for a module, with the given options. It is the responsibility of the caller to ensure that all fields in Options up to the given SizeOfOptions are initialized. It is correct to pass a smaller value of SizeOfOptions that omits some fields. The canonical way of using this is:
LLVMMCJITCompilerOptions options; LLVMInitializeMCJITCompilerOptions(&options, sizeof(options)); ... fill in those options you care about LLVMCreateMCJITCompilerForModule(&jit, mod, &options, sizeof(options), &error);
Note that this is also correct, though possibly suboptimal:
LLVMCreateMCJITCompilerForModule(&jit, mod, 0, 0, &error);
Definition at line 158 of file ExecutionEngineBindings.cpp.
References LLVMMCJITCompilerOptions::CodeModel, llvm::EngineBuilder::create(), llvm::TargetOptions::EnableFastISel, LLVMMCJITCompilerOptions::EnableFastISel, Error(), llvm::EngineKind::JIT, LLVMInitializeMCJITCompilerOptions(), LLVMMCJITCompilerOptions::MCJMM, llvm::TargetOptions::NoFramePointerElim, LLVMMCJITCompilerOptions::NoFramePointerElim, LLVMMCJITCompilerOptions::OptLevel, llvm::EngineBuilder::setCodeModel(), llvm::EngineBuilder::setEngineKind(), llvm::EngineBuilder::setErrorStr(), llvm::EngineBuilder::setMCJITMemoryManager(), llvm::EngineBuilder::setOptLevel(), llvm::EngineBuilder::setTargetOptions(), llvm::unwrap(), and llvm::wrap().
LLVMCreateSimpleMCJITMemoryManager()
LLVMMCJITMemoryManagerRef LLVMCreateSimpleMCJITMemoryManager (void * Opaque, LLVMMemoryManagerAllocateCodeSectionCallback AllocateCodeSection, LLVMMemoryManagerAllocateDataSectionCallback AllocateDataSection, LLVMMemoryManagerFinalizeMemoryCallback FinalizeMemory, LLVMMemoryManagerDestroyCallback Destroy)
Create a simple custom MCJIT memory manager. This memory manager can intercept allocations in a module-oblivious way. This will return NULL if any of the passed functions are NULL.
Parameters
Opaque An opaque client object to pass back to the callbacks.
AllocateCodeSection Allocate a block of memory for executable code.
AllocateDataSection Allocate a block of memory for data.
FinalizeMemory Set page permissions and flush cache. Return 0 on success, 1 on error.
Definition at line 419 of file ExecutionEngineBindings.cpp.
References functions, and llvm::wrap().
LLVMDisposeExecutionEngine()
void LLVMDisposeExecutionEngine (LLVMExecutionEngineRef EE)
Definition at line 230 of file ExecutionEngineBindings.cpp.
References llvm::unwrap().
LLVMDisposeGenericValue()
void LLVMDisposeGenericValue (LLVMGenericValueRef GenVal)
Definition at line 95 of file ExecutionEngineBindings.cpp.
References llvm::unwrap().
LLVMDisposeMCJITMemoryManager()
void LLVMDisposeMCJITMemoryManager (LLVMMCJITMemoryManagerRef MM)
Definition at line 438 of file ExecutionEngineBindings.cpp.
References llvm::unwrap().
LLVMFindFunction()
LLVMBool LLVMFindFunction (LLVMExecutionEngineRef EE, const char * Name, LLVMValueRef * OutFn)
Definition at line 297 of file ExecutionEngineBindings.cpp.
References F, Name, llvm::unwrap(), and llvm::wrap().
LLVMFreeMachineCodeForFunction()
void LLVMFreeMachineCodeForFunction (LLVMExecutionEngineRef EE, LLVMValueRef F)
Definition at line 269 of file ExecutionEngineBindings.cpp.
References F.
LLVMGenericValueIntWidth()
unsigned LLVMGenericValueIntWidth (LLVMGenericValueRef GenValRef)
Definition at line 67 of file ExecutionEngineBindings.cpp.
References llvm::unwrap().
LLVMGenericValueToFloat()
double LLVMGenericValueToFloat (LLVMTypeRef TyRef, LLVMGenericValueRef GenVal)
Definition at line 84 of file ExecutionEngineBindings.cpp.
References llvm::Type::DoubleTyID, llvm::Type::FloatTyID, getTypeID(), llvm_unreachable, and llvm::unwrap().
LLVMGenericValueToInt()
unsigned long long LLVMGenericValueToInt (LLVMGenericValueRef GenVal, LLVMBool IsSigned)
Definition at line 71 of file ExecutionEngineBindings.cpp.
References llvm::APInt::getSExtValue(), llvm::APInt::getZExtValue(), llvm::GenericValue::IntVal, and llvm::unwrap().
LLVMGenericValueToPointer()
void * LLVMGenericValueToPointer (LLVMGenericValueRef GenVal)
Definition at line 80 of file ExecutionEngineBindings.cpp.
References llvm::unwrap().
LLVMGetExecutionEngineTargetData()
LLVMTargetDataRef LLVMGetExecutionEngineTargetData (LLVMExecutionEngineRef EE)
Definition at line 311 of file ExecutionEngineBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetExecutionEngineTargetMachine()
LLVMTargetMachineRef LLVMGetExecutionEngineTargetMachine (LLVMExecutionEngineRef EE)
Definition at line 316 of file ExecutionEngineBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetFunctionAddress()
uint64_t LLVMGetFunctionAddress (LLVMExecutionEngineRef EE, const char * Name)
Definition at line 335 of file ExecutionEngineBindings.cpp.
References Name, and llvm::unwrap().
LLVMGetGlobalValueAddress()
uint64_t LLVMGetGlobalValueAddress (LLVMExecutionEngineRef EE, const char * Name)
Definition at line 331 of file ExecutionEngineBindings.cpp.
References Name, and llvm::unwrap().
LLVMGetPointerToGlobal()
void * LLVMGetPointerToGlobal (LLVMExecutionEngineRef EE, LLVMValueRef Global)
Definition at line 325 of file ExecutionEngineBindings.cpp.
References llvm::unwrap().
LLVMInitializeMCJITCompilerOptions()
void LLVMInitializeMCJITCompilerOptions (struct LLVMMCJITCompilerOptions * Options, size_t SizeOfOptions)
Definition at line 148 of file ExecutionEngineBindings.cpp.
References LLVMMCJITCompilerOptions::CodeModel, and LLVMCodeModelJITDefault.
Referenced by LLVMCreateMCJITCompilerForModule().
LLVMLinkInInterpreter()
void LLVMLinkInInterpreter (void)
Definition at line 31 of file Interpreter.cpp.
LLVMLinkInMCJIT()
void LLVMLinkInMCJIT (void)
Definition at line 43 of file MCJIT.cpp.
LLVMRecompileAndRelinkFunction()
void * LLVMRecompileAndRelinkFunction (LLVMExecutionEngineRef EE, LLVMValueRef Fn)
Definition at line 306 of file ExecutionEngineBindings.cpp.
LLVMRemoveModule()
LLVMBool LLVMRemoveModule (LLVMExecutionEngineRef EE, LLVMModuleRef M, LLVMModuleRef * OutMod, char ** OutError)
Definition at line 281 of file ExecutionEngineBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
Referenced by LLVMRemoveModuleProvider().
LLVMRemoveModuleProvider()
LLVMBool LLVMRemoveModuleProvider (LLVMExecutionEngineRef EE, LLVMModuleProviderRef MP, LLVMModuleRef * OutMod, char ** OutError)
Deprecated: Use LLVMRemoveModule instead.
Definition at line 289 of file ExecutionEngineBindings.cpp.
References LLVMRemoveModule().
LLVMRunFunction()
LLVMGenericValueRef LLVMRunFunction (LLVMExecutionEngineRef EE, LLVMValueRef F, unsigned NumArgs, LLVMGenericValueRef * Args)
Definition at line 254 of file ExecutionEngineBindings.cpp.
References F, I, llvm::unwrap(), and llvm::wrap().
LLVMRunFunctionAsMain()
int LLVMRunFunctionAsMain (LLVMExecutionEngineRef EE, LLVMValueRef F, unsigned ArgC, const char *const * ArgV, const char *const * EnvP)
Definition at line 242 of file ExecutionEngineBindings.cpp.
References F, I, and llvm::unwrap().
LLVMRunStaticConstructors()
void LLVMRunStaticConstructors (LLVMExecutionEngineRef EE)
Definition at line 234 of file ExecutionEngineBindings.cpp.
References llvm::unwrap().
LLVMRunStaticDestructors()
void LLVMRunStaticDestructors (LLVMExecutionEngineRef EE)
Definition at line 238 of file ExecutionEngineBindings.cpp.
References llvm::unwrap().