LLVM: Global Values
LLVM API Documentation
Global Values
LLVM-C: C interface to LLVM » Core » Values » Constants
Topics
Values with alignment
Functions
LLVMModuleRef LLVMGetGlobalParent (LLVMValueRef Global)
LLVMBool LLVMIsDeclaration (LLVMValueRef Global)
LLVMLinkage LLVMGetLinkage (LLVMValueRef Global)
void LLVMSetLinkage (LLVMValueRef Global, LLVMLinkage Linkage)
const char * LLVMGetSection (LLVMValueRef Global)
void LLVMSetSection (LLVMValueRef Global, const char *Section)
LLVMVisibility LLVMGetVisibility (LLVMValueRef Global)
void LLVMSetVisibility (LLVMValueRef Global, LLVMVisibility Viz)
LLVMDLLStorageClass LLVMGetDLLStorageClass (LLVMValueRef Global)
void LLVMSetDLLStorageClass (LLVMValueRef Global, LLVMDLLStorageClass Class)
LLVMBool LLVMHasUnnamedAddr (LLVMValueRef Global)
void LLVMSetUnnamedAddr (LLVMValueRef Global, LLVMBool HasUnnamedAddr)
unsigned LLVMGetAlignment (LLVMValueRef V)
void LLVMSetAlignment (LLVMValueRef V, unsigned Bytes)
Detailed Description
This group contains functions that operate on global values. Functions in this group relate to functions in the llvm::GlobalValue class tree.
See also
llvm::GlobalValue
Function Documentation
LLVMGetAlignment()
unsigned LLVMGetAlignment (LLVMValueRef V)
Obtain the preferred alignment of the value.
See also
llvm::AllocaInst::getAlignment()
llvm::LoadInst::getAlignment()
llvm::StoreInst::getAlignment()
llvm::GlobalValue::getAlignment()
Definition at line 1465 of file Core.cpp.
References llvm::dyn_cast(), llvm_unreachable, P, and llvm::unwrap().
LLVMGetDLLStorageClass()
LLVMDLLStorageClass LLVMGetDLLStorageClass (LLVMValueRef Global)
Definition at line 1445 of file Core.cpp.
References llvm::unwrap().
LLVMGetGlobalParent()
LLVMModuleRef LLVMGetGlobalParent (LLVMValueRef Global)
Definition at line 1328 of file Core.cpp.
References getParent(), llvm::unwrap(), and llvm::wrap().
LLVMGetLinkage()
LLVMLinkage LLVMGetLinkage (LLVMValueRef Global)
Definition at line 1336 of file Core.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, LLVMAppendingLinkage, LLVMAvailableExternallyLinkage, LLVMCommonLinkage, LLVMExternalLinkage, LLVMExternalWeakLinkage, LLVMInternalLinkage, LLVMLinkOnceAnyLinkage, LLVMLinkOnceODRLinkage, LLVMPrivateLinkage, LLVMWeakAnyLinkage, LLVMWeakODRLinkage, llvm::GlobalValue::PrivateLinkage, llvm::unwrap(), llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
LLVMGetSection()
const char * LLVMGetSection (LLVMValueRef Global)
Definition at line 1427 of file Core.cpp.
References llvm::unwrap().
LLVMGetVisibility()
LLVMVisibility LLVMGetVisibility (LLVMValueRef Global)
Definition at line 1435 of file Core.cpp.
References llvm::unwrap().
LLVMHasUnnamedAddr()
LLVMBool LLVMHasUnnamedAddr (LLVMValueRef Global)
Definition at line 1455 of file Core.cpp.
References llvm::unwrap().
LLVMIsDeclaration()
LLVMBool LLVMIsDeclaration (LLVMValueRef Global)
Definition at line 1332 of file Core.cpp.
References llvm::unwrap().
LLVMSetAlignment()
void LLVMSetAlignment (LLVMValueRef V, unsigned Bytes)
Set the preferred alignment of the value.
See also
llvm::AllocaInst::setAlignment()
llvm::LoadInst::setAlignment()
llvm::StoreInst::setAlignment()
llvm::GlobalValue::setAlignment()
Definition at line 1480 of file Core.cpp.
References llvm::dyn_cast(), llvm_unreachable, P, and llvm::unwrap().
LLVMSetDLLStorageClass()
void LLVMSetDLLStorageClass (LLVMValueRef Global, LLVMDLLStorageClass Class)
Definition at line 1450 of file Core.cpp.
References llvm::unwrap().
LLVMSetLinkage()
void LLVMSetLinkage (LLVMValueRef Global, LLVMLinkage Linkage)
Definition at line 1365 of file Core.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, DEBUG, llvm::errs(), llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, LLVMAppendingLinkage, LLVMAvailableExternallyLinkage, LLVMCommonLinkage, LLVMDLLExportLinkage, LLVMDLLImportLinkage, LLVMExternalLinkage, LLVMExternalWeakLinkage, LLVMGhostLinkage, LLVMInternalLinkage, LLVMLinkerPrivateLinkage, LLVMLinkerPrivateWeakLinkage, LLVMLinkOnceAnyLinkage, LLVMLinkOnceODRAutoHideLinkage, LLVMLinkOnceODRLinkage, LLVMPrivateLinkage, LLVMWeakAnyLinkage, LLVMWeakODRLinkage, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::setLinkage(), llvm::unwrap(), llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
LLVMSetSection()
void LLVMSetSection (LLVMValueRef Global, const char * Section)
Definition at line 1431 of file Core.cpp.
References llvm::unwrap().
LLVMSetUnnamedAddr()
void LLVMSetUnnamedAddr (LLVMValueRef Global, LLVMBool HasUnnamedAddr)
Definition at line 1459 of file Core.cpp.
References llvm::unwrap().
LLVMSetVisibility()
void LLVMSetVisibility (LLVMValueRef Global, LLVMVisibility Viz)
Definition at line 1440 of file Core.cpp.
References llvm::unwrap().