LLVM: General APIs
LLVM API Documentation
General APIs
LLVM-C: C interface to LLVM » Core » Values
Macros
#define LLVM_DECLARE_VALUE_CAST(name)
Functions
LLVMTypeRef LLVMTypeOf (LLVMValueRef Val)
const char * LLVMGetValueName (LLVMValueRef Val)
void LLVMSetValueName (LLVMValueRef Val, const char *Name)
void LLVMDumpValue (LLVMValueRef Val)
char * LLVMPrintValueToString (LLVMValueRef Val)
void LLVMReplaceAllUsesWith (LLVMValueRef OldVal, LLVMValueRef NewVal)
LLVMBool LLVMIsConstant (LLVMValueRef Val)
LLVMBool LLVMIsUndef (LLVMValueRef Val)
LLVMValueRef LLVMIsAMDNode (LLVMValueRef Val)
LLVMValueRef LLVMIsAMDString (LLVMValueRef Val)
Detailed Description
Functions in this section work on all LLVMValueRef instances, regardless of their sub-type. They correspond to functions available on llvm::Value.
Macro Definition Documentation
LLVM_DECLARE_VALUE_CAST
#define LLVM_DECLARE_VALUE_CAST (name)
Value:
  LLVMValueRef LLVMIsA##name(LLVMValueRef Val);
Convert value instances between types.
Internally, an LLVMValueRef is "pinned" to a specific type. This series of functions allows you to cast an instance to a specific type.
If the cast is not valid for the specified type, NULL is returned.
See also
llvm::dyn_cast_or_null<>
Definition at line 1304 of file Core.h.
Function Documentation
LLVMDumpValue()
void LLVMDumpValue (LLVMValueRef Val)
Dump a representation of a value to stderr.
See also
llvm::Value::dump()
Definition at line 532 of file Core.cpp.
References llvm::unwrap().
LLVMGetValueName()
const char * LLVMGetValueName (LLVMValueRef Val)
Obtain the string name of a value.
See also
llvm::Value::getName()
Definition at line 524 of file Core.cpp.
References llvm::unwrap().
LLVMIsAMDNode()
LLVMValueRef LLVMIsAMDNode (LLVMValueRef Val)
Definition at line 595 of file Core.cpp.
References llvm::dyn_cast_or_null(), llvm::isa(), LLVMIsAMDNode(), and llvm::unwrap().
Referenced by LLVMIsAMDNode().
LLVMIsAMDString()
LLVMValueRef LLVMIsAMDString (LLVMValueRef Val)
Definition at line 603 of file Core.cpp.
References llvm::dyn_cast_or_null(), llvm::isa(), and llvm::unwrap().
LLVMIsConstant()
LLVMBool LLVMIsConstant (LLVMValueRef Val)
Determine whether the specified constant instance is constant.
Definition at line 691 of file Core.cpp.
References llvm::isa(), and llvm::unwrap().
LLVMIsUndef()
LLVMBool LLVMIsUndef (LLVMValueRef Val)
Determine whether a value instance is undefined.
Definition at line 701 of file Core.cpp.
References llvm::isa(), and llvm::unwrap().
LLVMPrintValueToString()
char * LLVMPrintValueToString (LLVMValueRef Val)
Return a string representation of the value. Use LLVMDisposeMessage to free the string.
See also
llvm::Value::print()
Definition at line 536 of file Core.cpp.
References llvm::raw_ostream::flush(), and llvm::unwrap().
LLVMReplaceAllUsesWith()
void LLVMReplaceAllUsesWith (LLVMValueRef OldVal, LLVMValueRef NewVal)
Replace all uses of a value with another one.
See also
llvm::Value::replaceAllUsesWith()
Definition at line 550 of file Core.cpp.
References llvm::unwrap().
LLVMSetValueName()
void LLVMSetValueName (LLVMValueRef Val, const char * Name)
Set the string name of a value.
See also
llvm::Value::setName()
Definition at line 528 of file Core.cpp.
References Name, and llvm::unwrap().
LLVMTypeOf()
LLVMTypeRef LLVMTypeOf (LLVMValueRef Val)
Obtain the type of a value.
See also
llvm::Value::getType()
Definition at line 520 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().