LLVM: HexagonTargetObjectFile.cpp File Reference
LLVM API Documentation
HexagonTargetObjectFile.cpp File Reference
#include "HexagonTargetObjectFile.h"
#include "HexagonSubtarget.h"
#include "HexagonTargetMachine.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/MC/MCContext.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ELF.h"
Functions
static bool IsInSmallSection (uint64_t Size)
Variables
static cl::opt< int > SmallDataThreshold ("hexagon-small-data-threshold", cl::init(8), cl::Hidden, cl::desc("The maximum size of an object in the sdata section"))
Function Documentation
IsInSmallSection()
bool IsInSmallSection (uint64_t Size) static
Definition at line 47 of file HexagonTargetObjectFile.cpp.
References SmallDataThreshold.
Referenced by llvm::MipsTargetObjectFile::IsConstantInSmallSection(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), and llvm::MipsTargetObjectFile::IsGlobalInSmallSectionImpl().
Variable Documentation
SmallDataThreshold
cl::opt< int > SmallDataThreshold("hexagon-small-data-threshold", cl::init(8), cl::Hidden, cl::desc("The maximum size of an object in the sdata section")) ("hexagon-small-data-threshold" , cl::init(8) , cl::Hidden , cl::desc("The maximum size of an object in the sdata section")) static
Referenced by IsInSmallSection(), and llvm::HexagonTargetObjectFile::IsSmallDataEnabled().