LLVM: HexagonCFGOptimizer.cpp File Reference
LLVM API Documentation
HexagonCFGOptimizer.cpp File Reference
#include "Hexagon.h"
#include "HexagonMachineFunctionInfo.h"
#include "HexagonSubtarget.h"
#include "HexagonTargetMachine.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "hexagon_cfg"
Functions
void llvm::initializeHexagonCFGOptimizerPass (PassRegistry &)
static void initializePassOnce (PassRegistry &Registry)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon_cfg"
Definition at line 28 of file HexagonCFGOptimizer.cpp.
Function Documentation
initializePassOnce()
void initializePassOnce (PassRegistry & Registry) static
Definition at line 241 of file HexagonCFGOptimizer.cpp.
Referenced by llvm::initializeHexagonCFGOptimizerPass(), llvm::initializeHexagonDAGToDAGISelPass(), llvm::initializeHexagonExpandPredSpillCodePass(), llvm::initializeHexagonSplitTFRCondSetsPass(), and llvm::initializePPCDAGToDAGISelPass().