LLVM: HexagonInstPrinter.cpp File Reference
LLVM API Documentation
HexagonInstPrinter.cpp File Reference
#include "HexagonAsmPrinter.h"
#include "Hexagon.h"
#include "HexagonInstPrinter.h"
#include "MCTargetDesc/HexagonMCInst.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/Support/raw_ostream.h"
#include "HexagonGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
#define GET_INSTRUCTION_NAME
Functions
static int getMinValue (uint64_t TSFlags)
static int getMaxValue (uint64_t TSFlags)
static bool isExtended (uint64_t TSFlags)
static bool isExtendable (uint64_t TSFlags) LLVM_ATTRIBUTE_UNUSED
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 26 of file HexagonInstPrinter.cpp.
GET_INSTRUCTION_NAME
#define GET_INSTRUCTION_NAME
Definition at line 28 of file HexagonInstPrinter.cpp.
Function Documentation
getMaxValue()
int getMaxValue (uint64_t TSFlags) static
Definition at line 48 of file HexagonInstPrinter.cpp.
References llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, llvm::HexagonII::ExtentSignedMask, and llvm::HexagonII::ExtentSignedPos.
Referenced by llvm::HexagonInstPrinter::printExtOperand().
getMinValue()
int getMinValue (uint64_t TSFlags) static
Definition at line 34 of file HexagonInstPrinter.cpp.
References llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, llvm::HexagonII::ExtentSignedMask, and llvm::HexagonII::ExtentSignedPos.
Referenced by llvm::HexagonInstPrinter::printExtOperand().
isExtendable()
bool isExtendable (uint64_t TSFlags) static
Definition at line 68 of file HexagonInstPrinter.cpp.
References llvm::HexagonII::ExtendableMask, and llvm::HexagonII::ExtendablePos.
Referenced by llvm::HexagonInstPrinter::printExtOperand().
isExtended()
bool isExtended (uint64_t TSFlags) static
Definition at line 61 of file HexagonInstPrinter.cpp.
References llvm::HexagonII::ExtendedMask, and llvm::HexagonII::ExtendedPos.
Referenced by llvm::HexagonInstPrinter::printExtOperand().