LLVM: HexagonDisassembler.cpp File Reference
LLVM API Documentation
HexagonDisassembler.cpp File Reference
#include "MCTargetDesc/HexagonBaseInfo.h"
#include "MCTargetDesc/HexagonMCInst.h"
#include "MCTargetDesc/HexagonMCTargetDesc.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include <array>
#include <vector>
#include "HexagonGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "hexagon-disassembler"
Functions
static DecodeStatus DecodeModRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCtrRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRegisterClass (MCInst &Inst, unsigned RegNo, const uint16_t Table[], size_t Size)
static DecodeStatus DecodeIntRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t, void const *Decoder)
static DecodeStatus DecodeDoubleRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t, const void *Decoder)
static DecodeStatus DecodePredRegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t, void const *Decoder)
static MCDisassembler * createHexagonDisassembler (Target const &T, MCSubtargetInfo const &STI, MCContext &Ctx)
void LLVMInitializeHexagonDisassembler ()
Variables
static const uint16_t IntRegDecoderTable []
static const uint16_t PredRegDecoderTable []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon-disassembler"
Definition at line 31 of file HexagonDisassembler.cpp.
Function Documentation
createHexagonDisassembler()
MCDisassembler * createHexagonDisassembler (Target const & T, MCSubtargetInfo const & STI, MCContext & Ctx) static
Definition at line 152 of file HexagonDisassembler.cpp.
References T.
Referenced by LLVMInitializeHexagonDisassembler().
DecodeCtrRegsRegisterClass()
DecodeStatus DecodeCtrRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 88 of file HexagonDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, Register, and llvm::MCDisassembler::Success.
DecodeDoubleRegsRegisterClass()
DecodeStatus DecodeDoubleRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t , const void * Decoder) static
Definition at line 125 of file HexagonDisassembler.cpp.
References DecodeRegisterClass().
DecodeIntRegsRegisterClass()
DecodeStatus DecodeIntRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t , void const * Decoder) static
Definition at line 77 of file HexagonDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, IntRegDecoderTable, Register, and llvm::MCDisassembler::Success.
Referenced by DecodeJMPL(), DecodeLoadInt(), DecodeMem(), DecodeReturn(), DecodeStoreInt(), and DecodeSWAP().
DecodeModRegsRegisterClass()
DecodeStatus DecodeModRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 108 of file HexagonDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, Register, and llvm::MCDisassembler::Success.
DecodePredRegsRegisterClass()
DecodeStatus DecodePredRegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t , void const * Decoder) static
Definition at line 139 of file HexagonDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, PredRegDecoderTable, Register, and llvm::MCDisassembler::Success.
DecodeRegisterClass()
DecodeStatus DecodeRegisterClass (MCInst & Inst, unsigned RegNo, const uint16_t Table[], size_t Size) static
Definition at line 67 of file HexagonDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by DecodeDoubleRegsRegisterClass().
LLVMInitializeHexagonDisassembler()
void LLVMInitializeHexagonDisassembler ()
Definition at line 158 of file HexagonDisassembler.cpp.
References createHexagonDisassembler(), llvm::TargetRegistry::RegisterMCDisassembler(), and llvm::TheHexagonTarget.
Variable Documentation
IntRegDecoderTable
const uint16_t IntRegDecoderTable[] static
Initial value:
= {
  Hexagon::R0, Hexagon::R1, Hexagon::R2, Hexagon::R3, Hexagon::R4,
  Hexagon::R5, Hexagon::R6, Hexagon::R7, Hexagon::R8, Hexagon::R9,
  Hexagon::R10, Hexagon::R11, Hexagon::R12, Hexagon::R13, Hexagon::R14,
  Hexagon::R15, Hexagon::R16, Hexagon::R17, Hexagon::R18, Hexagon::R19,
  Hexagon::R20, Hexagon::R21, Hexagon::R22, Hexagon::R23, Hexagon::R24,
  Hexagon::R25, Hexagon::R26, Hexagon::R27, Hexagon::R28, Hexagon::R29,
  Hexagon::R30, Hexagon::R31 }
Definition at line 55 of file HexagonDisassembler.cpp.
Referenced by DecodeI64RegsRegisterClass(), DecodeIntRegsRegisterClass(), and DecodeIntRegsRegisterClass().
PredRegDecoderTable
const uint16_t PredRegDecoderTable[] static
Initial value:
= { Hexagon::P0, Hexagon::P1,
Hexagon::P2, Hexagon::P3 }
Definition at line 64 of file HexagonDisassembler.cpp.
Referenced by DecodePredRegsRegisterClass().