LLVM: HexagonSubtarget.cpp File Reference
LLVM API Documentation
HexagonSubtarget.cpp File Reference
#include "HexagonSubtarget.h"
#include "Hexagon.h"
#include "HexagonRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "HexagonGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "hexagon-subtarget"
#define GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_TARGET_DESC
Variables
static cl::opt< bool > EnableV3 ("enable-hexagon-v3", cl::Hidden, cl::desc("Enable Hexagon V3 instructions."))
static cl::opt< bool > EnableMemOps ("enable-hexagon-memops", cl::Hidden, cl::ZeroOrMore, cl::ValueDisallowed, cl::init(true), cl::desc("Generate V4 MEMOP in code generation for Hexagon target"))
static cl::opt< bool > DisableMemOps ("disable-hexagon-memops", cl::Hidden, cl::ZeroOrMore, cl::ValueDisallowed, cl::init(false), cl::desc("Do not generate V4 MEMOP in code generation for Hexagon target"))
static cl::opt< bool > EnableIEEERndNear ("enable-hexagon-ieee-rnd-near", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Generate non-chopped conversion from fp to int."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon-subtarget"
Definition at line 21 of file HexagonSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 23 of file HexagonSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 24 of file HexagonSubtarget.cpp.
Variable Documentation
DisableMemOps
cl::opt< bool > DisableMemOps("disable-hexagon-memops", cl::Hidden, cl::ZeroOrMore, cl::ValueDisallowed, cl::init(false), cl::desc("Do not generate V4 MEMOP in code generation for Hexagon target")) ("disable-hexagon-memops" , cl::Hidden , cl::ZeroOrMore , cl::ValueDisallowed , cl::init(false) , cl::desc("Do not generate V4 MEMOP in code generation for Hexagon target")) static
Referenced by llvm::HexagonSubtarget::HexagonSubtarget().
EnableIEEERndNear
cl::opt< bool > EnableIEEERndNear("enable-hexagon-ieee-rnd-near", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Generate non-chopped conversion from fp to int.")) ("enable-hexagon-ieee-rnd-near" , cl::Hidden , cl::ZeroOrMore , cl::init(false) , cl::desc("Generate non-chopped conversion from fp to int.")) static
Referenced by llvm::HexagonSubtarget::HexagonSubtarget().
EnableMemOps
cl::opt< bool > EnableMemOps("enable-hexagon-memops", cl::Hidden, cl::ZeroOrMore, cl::ValueDisallowed, cl::init(true), cl::desc("Generate V4 MEMOP in code generation for Hexagon target")) ("enable-hexagon-memops" , cl::Hidden , cl::ZeroOrMore , cl::ValueDisallowed , cl::init(true) , cl::desc("Generate V4 MEMOP in code generation for Hexagon target")) static
Referenced by llvm::HexagonSubtarget::HexagonSubtarget().
EnableV3
cl::opt< bool > EnableV3("enable-hexagon-v3", cl::Hidden, cl::desc("Enable Hexagon V3 instructions.")) ("enable-hexagon-v3" , cl::Hidden , cl::desc("Enable Hexagon V3 instructions.")) static
Referenced by llvm::HexagonSubtarget::initializeSubtargetDependencies().