LLVM: HexagonFrameLowering.cpp File Reference
LLVM API Documentation
HexagonFrameLowering.cpp File Reference
#include "HexagonFrameLowering.h"
#include "Hexagon.h"
#include "HexagonInstrInfo.h"
#include "HexagonMachineFunctionInfo.h"
#include "HexagonRegisterInfo.h"
#include "HexagonSubtarget.h"
#include "HexagonTargetMachine.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
Functions
static unsigned uniqueSuperReg (unsigned Reg, const TargetRegisterInfo *TRI)
Variables
static cl::opt< bool > DisableDeallocRet ("disable-hexagon-dealloc-ret", cl::Hidden, cl::desc("Disable Dealloc Return for Hexagon target"))
Function Documentation
uniqueSuperReg()
unsigned uniqueSuperReg (unsigned Reg, const TargetRegisterInfo * TRI) inline static
Definition at line 215 of file HexagonFrameLowering.cpp.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by llvm::HexagonFrameLowering::restoreCalleeSavedRegisters(), and llvm::HexagonFrameLowering::spillCalleeSavedRegisters().
Variable Documentation
DisableDeallocRet
cl::opt< bool > DisableDeallocRet("disable-hexagon-dealloc-ret", cl::Hidden, cl::desc("Disable Dealloc Return for Hexagon target")) ("disable-hexagon-dealloc-ret" , cl::Hidden , cl::desc("Disable Dealloc Return for Hexagon target")) static
Referenced by llvm::HexagonFrameLowering::emitEpilogue().