LLVM: HexagonMCInst.h File Reference
LLVM API Documentation
HexagonMCInst.h File Reference
#include "HexagonTargetMachine.h"
#include "llvm/MC/MCInst.h"
#include <memory>
Classes
class llvm::HexagonMCInst
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Functions
void LLVMInitializeHexagonTargetMC ()
Function Documentation
LLVMInitializeHexagonTargetMC()
void LLVMInitializeHexagonTargetMC ()
Definition at line 108 of file HexagonMCTargetDesc.cpp.
References llvm::createHexagonAsmBackend(), createHexagonMCAsmInfo(), llvm::createHexagonMCCodeEmitter(), createHexagonMCCodeGenInfo(), createHexagonMCInstPrinter(), createHexagonMCInstrInfo(), createHexagonMCRegisterInfo(), createHexagonMCSubtargetInfo(), createMCStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCCodeGenInfo(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCObjectStreamer(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TheHexagonTarget, and llvm::X.