LLVM: InstCombineAddSub.cpp File Reference
LLVM API Documentation
InstCombineAddSub.cpp File Reference
#include "InstCombine.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/PatternMatch.h"
Macros
#define DEBUG_TYPE "instcombine"
Functions
static bool checkRippleForAdd (const APInt &Op0KnownZero, const APInt &Op1KnownZero)
static Value * checkForNegativeOperand (BinaryOperator &I, InstCombiner::BuilderTy *Builder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instcombine"
Definition at line 23 of file InstCombineAddSub.cpp.
Function Documentation
checkForNegativeOperand()
Value * checkForNegativeOperand (BinaryOperator & I, InstCombiner::BuilderTy * Builder) static
Definition at line 992 of file InstCombineAddSub.cpp.
References llvm::APInt::countTrailingZeros(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAnd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateOr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSub(), llvm::Value::hasOneUse(), I, llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::match(), std::swap(), llvm::X, and Y.
Referenced by llvm::InstCombiner::visitAdd().
checkRippleForAdd()
bool checkRippleForAdd (const APInt & Op0KnownZero, const APInt & Op1KnownZero) static
Definition at line 868 of file InstCombineAddSub.cpp.
References llvm::APInt::clearBit(), llvm::APInt::countLeadingZeros(), llvm::APInt::countPopulation(), and llvm::APInt::getBitWidth().