LLVM: InstructionSimplify.cpp File Reference
LLVM API Documentation
InstructionSimplify.cpp File Reference
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/ValueHandle.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "instsimplify"
Enumerations
enum { RecursionLimit = 3 }
Functions
STATISTIC (NumExpand, "Number of expansions")
STATISTIC (NumReassoc, "Number of reassociations")
static Value * SimplifyAndInst (Value *, Value *, const Query &, unsigned)
static Value * SimplifyBinOp (unsigned, Value *, Value *, const Query &, unsigned)
static Value * SimplifyCmpInst (unsigned, Value *, Value *, const Query &, unsigned)
static Value * SimplifyOrInst (Value *, Value *, const Query &, unsigned)
static Value * SimplifyXorInst (Value *, Value *, const Query &, unsigned)
static Value * SimplifyTruncInst (Value *, Type *, const Query &, unsigned)
static Constant * getFalse (Type *Ty)
static Constant * getTrue (Type *Ty)
static bool isSameCompare (Value *V, CmpInst::Predicate Pred, Value *LHS, Value *RHS)
isSameCompare - Is V equivalent to the comparison "LHS Pred RHS"?
static bool ValueDominatesPHI (Value *V, PHINode *P, const DominatorTree *DT)
ValueDominatesPHI - Does the given value dominate the specified phi node?
static Value * ExpandBinOp (unsigned Opcode, Value *LHS, Value *RHS, unsigned OpcToExpand, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyAssociativeBinOp (unsigned Opc, Value *LHS, Value *RHS, const Query &Q, unsigned MaxRecurse)
static Value * ThreadBinOpOverSelect (unsigned Opcode, Value *LHS, Value *RHS, const Query &Q, unsigned MaxRecurse)
static Value * ThreadCmpOverSelect (CmpInst::Predicate Pred, Value *LHS, Value *RHS, const Query &Q, unsigned MaxRecurse)
static Value * ThreadBinOpOverPHI (unsigned Opcode, Value *LHS, Value *RHS, const Query &Q, unsigned MaxRecurse)
static Value * ThreadCmpOverPHI (CmpInst::Predicate Pred, Value *LHS, Value *RHS, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyAddInst (Value *Op0, Value *Op1, bool isNSW, bool isNUW, const Query &Q, unsigned MaxRecurse)
static Constant * stripAndComputeConstantOffsets (const DataLayout *DL, Value *&V, bool AllowNonInbounds=false)
Compute the base pointer and cumulative constant offsets for V.
static Constant * computePointerDifference (const DataLayout *DL, Value *LHS, Value *RHS)
Compute the constant difference between two pointer values. If the difference is not a constant, returns zero.
static Value * SimplifySubInst (Value *Op0, Value *Op1, bool isNSW, bool isNUW, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyFAddInst (Value *Op0, Value *Op1, FastMathFlags FMF, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyFSubInst (Value *Op0, Value *Op1, FastMathFlags FMF, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyFMulInst (Value *Op0, Value *Op1, FastMathFlags FMF, const Query &Q, unsigned MaxRecurse)
Given the operands for an FMul, see if we can fold the result.
static Value * SimplifyMulInst (Value *Op0, Value *Op1, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyDiv (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, const Query &Q, unsigned MaxRecurse)
static Value * SimplifySDivInst (Value *Op0, Value *Op1, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyUDivInst (Value *Op0, Value *Op1, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyFDivInst (Value *Op0, Value *Op1, const Query &Q, unsigned)
static Value * SimplifyRem (Instruction::BinaryOps Opcode, Value *Op0, Value *Op1, const Query &Q, unsigned MaxRecurse)
static Value * SimplifySRemInst (Value *Op0, Value *Op1, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyURemInst (Value *Op0, Value *Op1, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyFRemInst (Value *Op0, Value *Op1, const Query &, unsigned)
static bool isUndefShift (Value *Amount)
isUndefShift - Returns true if a shift by Amount always yields undef.
static Value * SimplifyShift (unsigned Opcode, Value *Op0, Value *Op1, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyRightShift (unsigned Opcode, Value *Op0, Value *Op1, bool isExact, const Query &Q, unsigned MaxRecurse)
Given operands for an Shl, LShr or AShr, see if we can fold the result. If not, this returns null.
static Value * SimplifyShlInst (Value *Op0, Value *Op1, bool isNSW, bool isNUW, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyLShrInst (Value *Op0, Value *Op1, bool isExact, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyAShrInst (Value *Op0, Value *Op1, bool isExact, const Query &Q, unsigned MaxRecurse)
static Value * simplifyUnsignedRangeCheck (ICmpInst *ZeroICmp, ICmpInst *UnsignedICmp, bool IsAnd)
static Value * SimplifyAndOfICmps (ICmpInst *Op0, ICmpInst *Op1)
static Value * SimplifyOrOfICmps (ICmpInst *Op0, ICmpInst *Op1)
static Type * GetCompareTy (Value *Op)
static Value * ExtractEquivalentCondition (Value *V, CmpInst::Predicate Pred, Value *LHS, Value *RHS)
static Constant * computePointerICmp (const DataLayout *DL, const TargetLibraryInfo *TLI, CmpInst::Predicate Pred, Value *LHS, Value *RHS)
static Value * SimplifyICmpInst (unsigned Predicate, Value *LHS, Value *RHS, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyFCmpInst (unsigned Predicate, Value *LHS, Value *RHS, const Query &Q, unsigned MaxRecurse)
static Value * SimplifySelectInst (Value *CondVal, Value *TrueVal, Value *FalseVal, const Query &Q, unsigned MaxRecurse)
static Value * SimplifyGEPInst (ArrayRef< Value * > Ops, const Query &Q, unsigned)
static Value * SimplifyInsertValueInst (Value *Agg, Value *Val, ArrayRef< unsigned > Idxs, const Query &Q, unsigned)
static Value * SimplifyPHINode (PHINode *PN, const Query &Q)
SimplifyPHINode - See if we can fold the given phi. If not, returns null.
static bool IsIdempotent (Intrinsic::ID ID)
template<typename IterTy>
static Value * SimplifyIntrinsic (Intrinsic::ID IID, IterTy ArgBegin, IterTy ArgEnd, const Query &Q, unsigned MaxRecurse)
template<typename IterTy>
static Value * SimplifyCall (Value *V, IterTy ArgBegin, IterTy ArgEnd, const Query &Q, unsigned MaxRecurse)
static bool replaceAndRecursivelySimplifyImpl (Instruction *I, Value *SimpleV, const DataLayout *DL, const TargetLibraryInfo *TLI, const DominatorTree *DT, AssumptionCache *AC)
Implementation of recursive simplification through an instructions uses.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instsimplify"
Definition at line 39 of file InstructionSimplify.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RecursionLimit
Definition at line 41 of file InstructionSimplify.cpp.
Function Documentation
computePointerDifference()
Constant * computePointerDifference (const DataLayout * DL, Value * LHS, Value * RHS) static
Compute the constant difference between two pointer values. If the difference is not a constant, returns zero.
Definition at line 647 of file InstructionSimplify.cpp.
References llvm::ConstantExpr::getSub(), and stripAndComputeConstantOffsets().
Referenced by SimplifySubInst().
computePointerICmp()
Constant * computePointerICmp (const DataLayout * DL, const TargetLibraryInfo * TLI, CmpInst::Predicate Pred, Value * LHS, Value * RHS) static
Definition at line 1935 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::ConstantExpr::getAdd(), GetCompareTy(), llvm::ConstantExpr::getICmp(), llvm::getObjectSize(), llvm::ICmpInst::getSignedPredicate(), llvm::Value::getType(), llvm::GetUnderlyingObjects(), llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::isa(), llvm::isKnownNonNull(), llvm::APInt::isNegative(), llvm::Constant::isNullValue(), llvm::CmpInst::isTrueWhenEqual(), stripAndComputeConstantOffsets(), llvm::Value::stripPointerCasts(), and llvm::APInt::ult().
Referenced by SimplifyICmpInst().
ExpandBinOp()
Value * ExpandBinOp (unsigned Opcode, Value * LHS, Value * RHS, unsigned OpcToExpand, const Query & Q, unsigned MaxRecurse) static
ExpandBinOp - Simplify "A op (B op' C)" by distributing op over op', turning it into "(A op B) op' (A op C)". Here "op" is given by Opcode and "op'" is given by OpcodeToExpand, while "A" corresponds to LHS and "B op' C" to RHS. Also performs the transform "(A op' B) op C" -> "(A op C) op' (B op C)". Returns the simplified value, or null if no simplification was performed.
Definition at line 136 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::Instruction::isCommutative(), and llvm::SimplifyBinOp().
Referenced by SimplifyAndInst(), SimplifyMulInst(), and SimplifyOrInst().
ExtractEquivalentCondition()
Value * ExtractEquivalentCondition (Value * V, CmpInst::Predicate Pred, Value * LHS, Value * RHS) static
ExtractEquivalentCondition - Rummage around inside V looking for something equivalent to the comparison "LHS Pred RHS". Return such a value if found, otherwise return null. Helper function for analyzing max/min idioms.
Definition at line 1890 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), and llvm::CmpInst::getSwappedPredicate().
Referenced by SimplifyICmpInst().
GetCompareTy()
Type * GetCompareTy (Value * Op) static
Definition at line 1883 of file InstructionSimplify.cpp.
References llvm::Value::getType(), and llvm::CmpInst::makeCmpResultType().
Referenced by computePointerICmp(), SimplifyFCmpInst(), and SimplifyICmpInst().
getFalse()
Constant * getFalse (Type * Ty) static
getFalse - For a boolean type, or a vector of boolean type, return false, or a vector with every element false, as appropriate for the type.
Definition at line 72 of file InstructionSimplify.cpp.
References llvm::Constant::getNullValue(), llvm::Type::getScalarType(), and llvm::Type::isIntegerTy().
Referenced by SimplifyAndOfICmps(), SimplifyICmpInst(), simplifyUnsignedRangeCheck(), and ThreadCmpOverSelect().
getTrue()
Constant * getTrue (Type * Ty) static
getTrue - For a boolean type, or a vector of boolean type, return true, or a vector with every element true, as appropriate for the type.
Definition at line 80 of file InstructionSimplify.cpp.
References llvm::Constant::getAllOnesValue(), llvm::Type::getScalarType(), and llvm::Type::isIntegerTy().
Referenced by SimplifyICmpInst(), SimplifyOrOfICmps(), simplifyUnsignedRangeCheck(), and ThreadCmpOverSelect().
IsIdempotent()
bool IsIdempotent (Intrinsic::ID ID) static
Definition at line 3479 of file InstructionSimplify.cpp.
References llvm::Intrinsic::ceil, llvm::Intrinsic::fabs, llvm::Intrinsic::floor, llvm::Intrinsic::nearbyint, llvm::Intrinsic::rint, llvm::Intrinsic::round, and llvm::Intrinsic::trunc.
Referenced by SimplifyIntrinsic().
isSameCompare()
bool isSameCompare (Value * V, CmpInst::Predicate Pred, Value * LHS, Value * RHS) static
isSameCompare - Is V equivalent to the comparison "LHS Pred RHS"?
Definition at line 87 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), and llvm::CmpInst::getSwappedPredicate().
Referenced by ThreadCmpOverSelect().
isUndefShift()
bool isUndefShift (Value * Amount) static
isUndefShift - Returns true if a shift by Amount always yields undef.
Definition at line 1259 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), I, llvm::isa(), and isUndefShift().
Referenced by isUndefShift(), and SimplifyShift().
replaceAndRecursivelySimplifyImpl()
bool replaceAndRecursivelySimplifyImpl (Instruction * I, Value * SimpleV, const DataLayout * DL, const TargetLibraryInfo * TLI, const DominatorTree * DT, AssumptionCache * AC) static
Implementation of recursive simplification through an instructions uses.
This is the common implementation of the recursive simplification routines. If we have a pre-simplified value in 'SimpleV', that is forcibly used to replace the instruction 'I'. Otherwise, we simply add 'I' to the list of instructions to process and attempt to simplify it using InstructionSimplify.
This routine returns 'true' only when it simplifies something. The passed in simplified value does not count toward this.
Definition at line 3712 of file InstructionSimplify.cpp.
References llvm::cast(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::SimplifyInstruction(), and llvm::SetVector< T, Vector, Set >::size().
Referenced by llvm::recursivelySimplifyInstruction(), and llvm::replaceAndRecursivelySimplify().
SimplifyAddInst()
Value * SimplifyAddInst (Value * Op0, Value * Op1, bool isNSW, bool isNUW, const Query & Q, unsigned MaxRecurse) static
SimplifyAddInst - Given operands for an Add, see if we can fold the result. If not, this returns null.
i1 add -> xor.
Definition at line 528 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), llvm::Constant::getAllOnesValue(), llvm::Value::getType(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), SimplifyAssociativeBinOp(), llvm::SimplifyXorInst(), std::swap(), and Y.
SimplifyAndInst()
Value * SimplifyAndInst (Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifyAndInst - Given operands for an And, see if we can fold the result. If not, this returns null.
Definition at line 1535 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), ExpandBinOp(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::isa(), llvm::isKnownToBeAPowerOfTwo(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), SimplifyAndOfICmps(), SimplifyAssociativeBinOp(), std::swap(), ThreadBinOpOverPHI(), and ThreadBinOpOverSelect().
SimplifyAndOfICmps()
Value * SimplifyAndOfICmps (ICmpInst * Op0, ICmpInst * Op1) static
Definition at line 1483 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::APInt::getBoolValue(), getFalse(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::APInt::isStrictlyPositive(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), simplifyUnsignedRangeCheck(), and llvm::X.
Referenced by SimplifyAndInst().
SimplifyAShrInst()
Value * SimplifyAShrInst (Value * Op0, Value * Op1, bool isExact, const Query & Q, unsigned MaxRecurse) static
SimplifyAShrInst - Given operands for an AShr, see if we can fold the result. If not, this returns null.
Definition at line 1408 of file InstructionSimplify.cpp.
References llvm::ComputeNumSignBits(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), SimplifyRightShift(), and llvm::X.
SimplifyAssociativeBinOp()
Value * SimplifyAssociativeBinOp (unsigned Opc, Value * LHS, Value * RHS, const Query & Q, unsigned MaxRecurse) static
SimplifyAssociativeBinOp - Generic simplifications for associative binary operations. Returns the simpler value, or null if none was found.
Definition at line 195 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), and llvm::SimplifyBinOp().
Referenced by SimplifyAddInst(), SimplifyAndInst(), SimplifyBinOp(), SimplifyMulInst(), SimplifyOrInst(), and SimplifyXorInst().
SimplifyBinOp()
Value * SimplifyBinOp (unsigned Opcode, Value * LHS, Value * RHS, const Query & Q, unsigned MaxRecurse) static
SimplifyBinOp - Given operands for a BinaryOperator, see if we can fold the result. If not, this returns null.
Definition at line 3391 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), llvm::Value::getType(), llvm::isa(), llvm::Instruction::isAssociative(), llvm::SimplifyAddInst(), llvm::SimplifyAndInst(), llvm::SimplifyAShrInst(), SimplifyAssociativeBinOp(), llvm::SimplifyFAddInst(), llvm::SimplifyFDivInst(), llvm::SimplifyFMulInst(), llvm::SimplifyFRemInst(), llvm::SimplifyFSubInst(), llvm::SimplifyLShrInst(), llvm::SimplifyMulInst(), llvm::SimplifyOrInst(), llvm::SimplifySDivInst(), llvm::SimplifyShlInst(), llvm::SimplifySRemInst(), llvm::SimplifySubInst(), llvm::SimplifyUDivInst(), llvm::SimplifyURemInst(), llvm::SimplifyXorInst(), ThreadBinOpOverPHI(), and ThreadBinOpOverSelect().
SimplifyCall()
template<typename IterTy> Value * SimplifyCall (Value * V, IterTy ArgBegin, IterTy ArgEnd, const Query & Q, unsigned MaxRecurse) static
Definition at line 3512 of file InstructionSimplify.cpp.
References llvm::canConstantFoldCallTo(), llvm::cast(), llvm::ConstantFoldCall(), llvm::dyn_cast(), F, llvm::UndefValue::get(), llvm::FunctionType::getReturnType(), I, llvm::isa(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and SimplifyIntrinsic().
SimplifyCmpInst()
Value * SimplifyCmpInst (unsigned Predicate, Value * LHS, Value * RHS, const Query & Q, unsigned MaxRecurse) static
SimplifyCmpInst - Given operands for a CmpInst, see if we can fold the result.
Definition at line 3464 of file InstructionSimplify.cpp.
References llvm::CmpInst::isIntPredicate(), llvm::SimplifyFCmpInst(), and llvm::SimplifyICmpInst().
SimplifyDiv()
Value * SimplifyDiv (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifyDiv - Given operands for an SDiv or UDiv, see if we can fold the result. If not, this returns null.
Definition at line 999 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::OverflowingBinaryOperator::hasNoSignedWrap(), llvm::OverflowingBinaryOperator::hasNoUnsignedWrap(), llvm::isa(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), std::swap(), ThreadBinOpOverPHI(), ThreadBinOpOverSelect(), llvm::APInt::umul_ov(), llvm::X, and Y.
Referenced by SimplifySDivInst(), and SimplifyUDivInst().
SimplifyFAddInst()
Value * SimplifyFAddInst (Value * Op0, Value * Op1, FastMathFlags FMF, const Query & Q, unsigned MaxRecurse) static
Given operands for an FAdd, see if we can fold the result. If not, this returns null.
Definition at line 793 of file InstructionSimplify.cpp.
References llvm::CannotBeNegativeZero(), llvm::cast(), llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Instruction::hasNoInfs(), llvm::Instruction::hasNoNaNs(), llvm::PatternMatch::m_AnyZero(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_NegZero(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::FastMathFlags::noInfs(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), and std::swap().
SimplifyFCmpInst()
Value * SimplifyFCmpInst (unsigned Predicate, Value * LHS, Value * RHS, const Query & Q, unsigned MaxRecurse) static
SimplifyFCmpInst - Given operands for an FCmpInst, see if we can fold the result. If not, this returns null.
Definition at line 3021 of file InstructionSimplify.cpp.
References llvm::ConstantFoldCompareInstOperands(), llvm::dyn_cast(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_ULE, llvm::ConstantInt::get(), llvm::UndefValue::get(), GetCompareTy(), llvm::ConstantInt::getFalse(), llvm::CmpInst::getSwappedPredicate(), llvm::ConstantInt::getTrue(), llvm::isa(), llvm::CmpInst::isFalseWhenEqual(), llvm::CmpInst::isFPPredicate(), llvm::CmpInst::isOrdered(), llvm::CmpInst::isTrueWhenEqual(), llvm::CmpInst::isUnordered(), std::swap(), ThreadCmpOverPHI(), and ThreadCmpOverSelect().
SimplifyFDivInst()
Value * SimplifyFDivInst (Value * Op0, Value * Op1, const Query & Q, unsigned) static
Definition at line 1119 of file InstructionSimplify.cpp.
References llvm::PatternMatch::m_Undef(), and llvm::PatternMatch::match().
SimplifyFMulInst()
Value * SimplifyFMulInst (Value * Op0, Value * Op1, FastMathFlags FMF, const Query & Q, unsigned MaxRecurse) static
Given the operands for an FMul, see if we can fold the result.
Definition at line 871 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), llvm::PatternMatch::m_AnyZero(), llvm::PatternMatch::m_FPOne(), llvm::PatternMatch::match(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), and std::swap().
SimplifyFRemInst()
Value * SimplifyFRemInst (Value * Op0, Value * Op1, const Query & , unsigned) static
Definition at line 1237 of file InstructionSimplify.cpp.
References llvm::PatternMatch::m_Undef(), and llvm::PatternMatch::match().
SimplifyFSubInst()
Value * SimplifyFSubInst (Value * Op0, Value * Op1, FastMathFlags FMF, const Query & Q, unsigned MaxRecurse) static
Given operands for an FSub, see if we can fold the result. If not, this returns null.
Definition at line 835 of file InstructionSimplify.cpp.
References llvm::CannotBeNegativeZero(), llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::PatternMatch::m_AnyZero(), llvm::PatternMatch::m_FSub(), llvm::PatternMatch::m_NegZero(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::FastMathFlags::noInfs(), llvm::FastMathFlags::noNaNs(), llvm::FastMathFlags::noSignedZeros(), and llvm::X.
SimplifyGEPInst()
Value * SimplifyGEPInst (ArrayRef< Value * > Ops, const Query & Q, unsigned) static
SimplifyGEPInst - Given operands for an GetElementPtrInst, see if we can fold the result. If not, this returns null.
Definition at line 3214 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::PointerType::get(), llvm::UndefValue::get(), llvm::VectorType::get(), llvm::PointerType::getAddressSpace(), llvm::SequentialType::getElementType(), llvm::ConstantExpr::getGetElementPtr(), llvm::GetElementPtrInst::getIndexedType(), llvm::Constant::getNullValue(), llvm::DataLayout::getPointerSizeInBits(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::isa(), llvm::Type::isSized(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), P, llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::slice().
SimplifyICmpInst()
Value * SimplifyICmpInst (unsigned Predicate, Value * LHS, Value * RHS, const Query & Q, unsigned MaxRecurse) static
SimplifyICmpInst - Given operands for an ICmpInst, see if we can fold the result. If not, this returns null.
Definition at line 2107 of file InstructionSimplify.cpp.
References llvm::APInt::abs(), llvm::APInt::ashr(), llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::cast(), llvm::computeKnownBits(), computePointerICmp(), llvm::ComputeSignBit(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantRange::contains(), llvm::APInt::countLeadingOnes(), llvm::APInt::countLeadingZeros(), llvm::APInt::countTrailingZeros(), llvm::dyn_cast(), ExtractEquivalentCondition(), llvm::ConstantInt::get(), llvm::APInt::getAllOnesValue(), llvm::ConstantExpr::getCast(), GetCompareTy(), llvm::Value::getContext(), getFalse(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getICmp(), llvm::ConstantExpr::getIntToPtr(), llvm::CmpInst::getInversePredicate(), llvm::Constant::getNullValue(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarType(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::ICmpInst::getSignedPredicate(), llvm::CmpInst::getSwappedPredicate(), getTrue(), llvm::ConstantInt::getTrue(), llvm::ConstantExpr::getTrunc(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), llvm::ICmpInst::getUnsignedPredicate(), llvm::ConstantInt::getValue(), llvm::BinaryOperator::hasNoSignedWrap(), llvm::BinaryOperator::hasNoUnsignedWrap(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ConstantRange::inverse(), llvm::isa(), llvm::APInt::isAllOnesValue(), llvm::ConstantRange::isEmptySet(), llvm::ICmpInst::isEquality(), llvm::ICmpInst::isEquality(), llvm::BinaryOperator::isExact(), llvm::ConstantRange::isFullSet(), llvm::Type::isIntegerTy(), llvm::CmpInst::isIntPredicate(), llvm::isKnownNonZero(), llvm::Constant::isMinSignedValue(), llvm::ConstantInt::isNegative(), llvm::Type::isPointerTy(), llvm::APInt::isPowerOf2(), llvm::APInt::isSignBit(), llvm::CmpInst::isSigned(), llvm::CmpInst::isTrueWhenEqual(), llvm::CmpInst::isUnsigned(), llvm::ConstantInt::isZero(), llvm_unreachable, llvm::APInt::lshr(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_AShr(), llvm::PatternMatch::m_CombineOr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_LShr(), llvm::PatternMatch::m_Neg(), llvm::PatternMatch::m_NSWShl(), llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_SDiv(), llvm::PatternMatch::m_Shl(), llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_SMin(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_UDiv(), llvm::PatternMatch::m_UMax(), llvm::PatternMatch::m_UMin(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::m_ZExt(), llvm::ICmpInst::makeConstantRange(), llvm::PatternMatch::match(), P, llvm::APInt::sdiv(), llvm::APInt::sgt(), llvm::APInt::shl(), llvm::SimplifyICmpInst(), std::swap(), ThreadCmpOverPHI(), ThreadCmpOverSelect(), llvm::APInt::udiv(), llvm::APInt::ult(), and Y.
SimplifyInsertValueInst()
Value * SimplifyInsertValueInst (Value * Agg, Value * Val, ArrayRef< unsigned > Idxs, const Query & Q, unsigned) static
SimplifyInsertValueInst - Given operands for an InsertValueInst, see if we can fold the result. If not, this returns null.
Definition at line 3303 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInsertValueInstruction(), llvm::dyn_cast(), llvm::Value::getType(), llvm::PatternMatch::m_Undef(), and llvm::PatternMatch::match().
SimplifyIntrinsic()
template<typename IterTy> Value * SimplifyIntrinsic (Intrinsic::ID IID, IterTy ArgBegin, IterTy ArgEnd, const Query & Q, unsigned MaxRecurse) static
Definition at line 3496 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), and IsIdempotent().
Referenced by SimplifyCall().
SimplifyLShrInst()
Value * SimplifyLShrInst (Value * Op0, Value * Op1, bool isExact, const Query & Q, unsigned MaxRecurse) static
SimplifyLShrInst - Given operands for an LShr, see if we can fold the result. If not, this returns null.
Definition at line 1383 of file InstructionSimplify.cpp.
References llvm::PatternMatch::m_NUWShl(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), SimplifyRightShift(), and llvm::X.
SimplifyMulInst()
Value * SimplifyMulInst (Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifyMulInst - Given operands for a Mul, see if we can fold the result. If not, this returns null.
Definition at line 899 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), ExpandBinOp(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::isa(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_IDiv(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::SimplifyAndInst(), SimplifyAssociativeBinOp(), std::swap(), ThreadBinOpOverPHI(), ThreadBinOpOverSelect(), and llvm::X.
SimplifyOrInst()
Value * SimplifyOrInst (Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifyOrInst - Given operands for an Or, see if we can fold the result. If not, this returns null.
Definition at line 1692 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), ExpandBinOp(), llvm::Constant::getAllOnesValue(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::isa(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::MaskedValueIsZero(), llvm::PatternMatch::match(), SimplifyAssociativeBinOp(), SimplifyOrOfICmps(), std::swap(), ThreadBinOpOverPHI(), and ThreadBinOpOverSelect().
SimplifyOrOfICmps()
Value * SimplifyOrOfICmps (ICmpInst * Op0, ICmpInst * Op1) static
Definition at line 1640 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::APInt::getBoolValue(), llvm::User::getOperand(), getTrue(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::APInt::isStrictlyPositive(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), simplifyUnsignedRangeCheck(), and llvm::X.
Referenced by SimplifyOrInst().
SimplifyPHINode()
Value * SimplifyPHINode (PHINode * PN, const Query & Q) static
SimplifyPHINode - See if we can fold the given phi. If not, returns null.
Definition at line 3339 of file InstructionSimplify.cpp.
References llvm::UndefValue::get(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::Value::getType(), llvm::isa(), and ValueDominatesPHI().
Referenced by llvm::SimplifyInstruction().
SimplifyRem()
Value * SimplifyRem (Instruction::BinaryOps Opcode, Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifyRem - Given operands for an SRem or URem, see if we can fold the result. If not, this returns null.
Definition at line 1142 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), llvm::UndefValue::get(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::isa(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_SRem(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_URem(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), ThreadBinOpOverPHI(), and ThreadBinOpOverSelect().
Referenced by SimplifySRemInst(), and SimplifyURemInst().
SimplifyRightShift()
Value * SimplifyRightShift (unsigned Opcode, Value * Op0, Value * Op1, bool isExact, const Query & Q, unsigned MaxRecurse) static
Given operands for an Shl, LShr or AShr, see if we can fold the result. If not, this returns null.
Definition at line 1325 of file InstructionSimplify.cpp.
References llvm::computeKnownBits(), llvm::Constant::getNullValue(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::match(), and SimplifyShift().
Referenced by SimplifyAShrInst(), and SimplifyLShrInst().
SimplifySDivInst()
Value * SimplifySDivInst (Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifySDivInst - Given operands for an SDiv, see if we can fold the result. If not, this returns null.
Definition at line 1085 of file InstructionSimplify.cpp.
References SimplifyDiv().
SimplifySelectInst()
Value * SimplifySelectInst (Value * CondVal, Value * TrueVal, Value * FalseVal, const Query & Q, unsigned MaxRecurse) static
SimplifySelectInst - Given operands for a SelectInst, see if we can fold the result. If not, this returns null.
Definition at line 3119 of file InstructionSimplify.cpp.
References llvm::dyn_cast(), llvm::Type::getScalarSizeInBits(), llvm::APInt::getSignBit(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::isa(), llvm::ICmpInst::isEquality(), llvm::PatternMatch::m_AllOnes(), llvm::PatternMatch::m_And(), llvm::PatternMatch::m_APInt(), llvm::PatternMatch::m_Or(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::X, and Y.
SimplifyShift()
Value * SimplifyShift (unsigned Opcode, Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifyShift - Given operands for an Shl, LShr or AShr, see if we can fold the result. If not, this returns null.
Definition at line 1287 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), llvm::UndefValue::get(), llvm::Value::getType(), llvm::isa(), isUndefShift(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), ThreadBinOpOverPHI(), and ThreadBinOpOverSelect().
Referenced by SimplifyRightShift(), and SimplifyShlInst().
SimplifyShlInst()
Value * SimplifyShlInst (Value * Op0, Value * Op1, bool isNSW, bool isNUW, const Query & Q, unsigned MaxRecurse) static
SimplifyShlInst - Given operands for an Shl, see if we can fold the result. If not, this returns null.
Definition at line 1356 of file InstructionSimplify.cpp.
References llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::PatternMatch::m_Exact(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), SimplifyShift(), and llvm::X.
SimplifySRemInst()
Value * SimplifySRemInst (Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifySRemInst - Given operands for an SRem, see if we can fold the result. If not, this returns null.
Definition at line 1203 of file InstructionSimplify.cpp.
References SimplifyRem().
SimplifySubInst()
Value * SimplifySubInst (Value * Op0, Value * Op1, bool isNSW, bool isNUW, const Query & Q, unsigned MaxRecurse) static
SimplifySubInst - Given operands for a Sub, see if we can fold the result. If not, this returns null.
Definition at line 666 of file InstructionSimplify.cpp.
References computePointerDifference(), llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), llvm::UndefValue::get(), llvm::ConstantExpr::getIntegerCast(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::Type::isIntegerTy(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_Trunc(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::SimplifyBinOp(), llvm::SimplifyTruncInst(), llvm::SimplifyXorInst(), llvm::X, and Y.
SimplifyTruncInst()
Value * SimplifyTruncInst (Value * Op, Type * Ty, const Query & Q, unsigned) static
Definition at line 3372 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInstOperands(), and llvm::dyn_cast().
SimplifyUDivInst()
Value * SimplifyUDivInst (Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifyUDivInst - Given operands for a UDiv, see if we can fold the result. If not, this returns null.
Definition at line 1103 of file InstructionSimplify.cpp.
References SimplifyDiv().
simplifyUnsignedRangeCheck()
Value * simplifyUnsignedRangeCheck (ICmpInst * ZeroICmp, ICmpInst * UnsignedICmp, bool IsAnd) static
Definition at line 1440 of file InstructionSimplify.cpp.
References getFalse(), llvm::CmpInst::getSwappedPredicate(), getTrue(), llvm::Value::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, llvm::ICmpInst::isEquality(), llvm::CmpInst::isUnsigned(), llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::X, and Y.
Referenced by SimplifyAndOfICmps(), and SimplifyOrOfICmps().
SimplifyURemInst()
Value * SimplifyURemInst (Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifyURemInst - Given operands for a URem, see if we can fold the result. If not, this returns null.
Definition at line 1221 of file InstructionSimplify.cpp.
References SimplifyRem().
SimplifyXorInst()
Value * SimplifyXorInst (Value * Op0, Value * Op1, const Query & Q, unsigned MaxRecurse) static
SimplifyXorInst - Given operands for a Xor, see if we can fold the result. If not, this returns null.
Definition at line 1828 of file InstructionSimplify.cpp.
References llvm::ConstantFoldInstOperands(), llvm::dyn_cast(), llvm::Constant::getAllOnesValue(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::PatternMatch::m_Not(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Undef(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), SimplifyAssociativeBinOp(), and std::swap().
STATISTIC() [1/2]
STATISTIC (NumExpand , "Number of expansions")
STATISTIC() [2/2]
STATISTIC (NumReassoc , "Number of reassociations")
stripAndComputeConstantOffsets()
Constant * stripAndComputeConstantOffsets (const DataLayout * DL, Value *& V, bool AllowNonInbounds = false) static
Compute the base pointer and cumulative constant offsets for V.
This strips all constant offsets off of V, leaving it the base pointer, and accumulates the total constant offset applied in the returned constant. It returns 0 if V is not a pointer, and returns the constant '0' if there are no constant offsets applied.
This is very similar to GetPointerBaseWithConstantOffset except it doesn't follow non-inbounds geps. This allows it to remain usable for icmp ult/etc. folding.
Definition at line 602 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::IntegerType::get(), llvm::Type::getIntegerBitWidth(), llvm::DataLayout::getIntPtrType(), llvm::APInt::getNullValue(), llvm::Operator::getOpcode(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), and llvm::SmallPtrSetImpl< PtrType >::insert().
Referenced by computePointerDifference(), and computePointerICmp().
ThreadBinOpOverPHI()
Value * ThreadBinOpOverPHI (unsigned Opcode, Value * LHS, Value * RHS, const Query & Q, unsigned MaxRecurse) static
ThreadBinOpOverPHI - In the case of a binary operation with an operand that is a PHI instruction, try to simplify the binop by seeing whether evaluating it on the incoming phi values yields the same result for every value. If so returns the common value, otherwise returns null.
Definition at line 448 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::isa(), llvm::SimplifyBinOp(), and ValueDominatesPHI().
Referenced by SimplifyAndInst(), SimplifyBinOp(), SimplifyDiv(), SimplifyMulInst(), SimplifyOrInst(), SimplifyRem(), and SimplifyShift().
ThreadBinOpOverSelect()
Value * ThreadBinOpOverSelect (unsigned Opcode, Value * LHS, Value * RHS, const Query & Q, unsigned MaxRecurse) static
ThreadBinOpOverSelect - In the case of a binary operation with a select instruction as an operand, try to simplify the binop by seeing whether evaluating it on both branches of the select results in the same value. Returns the common value if so, otherwise returns null.
Definition at line 294 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::isa(), and llvm::SimplifyBinOp().
Referenced by SimplifyAndInst(), SimplifyBinOp(), SimplifyDiv(), SimplifyMulInst(), SimplifyOrInst(), SimplifyRem(), and SimplifyShift().
ThreadCmpOverPHI()
Value * ThreadCmpOverPHI (CmpInst::Predicate Pred, Value * LHS, Value * RHS, const Query & Q, unsigned MaxRecurse) static
ThreadCmpOverPHI - In the case of a comparison with a PHI instruction, try try to simplify the comparison by seeing whether comparing with all of the incoming phi values yields the same result every time. If so returns the common result, otherwise returns null.
Definition at line 491 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::CmpInst::getSwappedPredicate(), llvm::isa(), llvm::SimplifyCmpInst(), std::swap(), and ValueDominatesPHI().
Referenced by SimplifyFCmpInst(), and SimplifyICmpInst().
ThreadCmpOverSelect()
Value * ThreadCmpOverSelect (CmpInst::Predicate Pred, Value * LHS, Value * RHS, const Query & Q, unsigned MaxRecurse) static
ThreadCmpOverSelect - In the case of a comparison with a select instruction, try to simplify the comparison by seeing whether both branches of the select result in the same value. Returns the common value if so, otherwise returns null.
Definition at line 366 of file InstructionSimplify.cpp.
References llvm::cast(), llvm::Constant::getAllOnesValue(), getFalse(), llvm::CmpInst::getSwappedPredicate(), getTrue(), llvm::Value::getType(), llvm::isa(), isSameCompare(), llvm::Type::isVectorTy(), llvm::PatternMatch::m_One(), llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::SimplifyAndInst(), llvm::SimplifyCmpInst(), llvm::SimplifyOrInst(), llvm::SimplifyXorInst(), and std::swap().
Referenced by SimplifyFCmpInst(), and SimplifyICmpInst().
ValueDominatesPHI()
bool ValueDominatesPHI (Value * V, PHINode * P, const DominatorTree * DT) static
ValueDominatesPHI - Does the given value dominate the specified phi node?
Definition at line 101 of file InstructionSimplify.cpp.
References llvm::DominatorTree::dominates(), llvm::dyn_cast(), I, llvm::isa(), llvm::DominatorTree::isReachableFromEntry(), and P.
Referenced by SimplifyPHINode(), ThreadBinOpOverPHI(), and ThreadCmpOverPHI().