LLVM: Instructions.cpp File Reference
LLVM API Documentation
Instructions.cpp File Reference
#include "llvm/IR/Instructions.h"
#include "LLVMContextImpl.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
Functions
static bool IsConstantOne (Value *val)
IsConstantOne - Return true only if val is constant int 1.
static Instruction * createMalloc (Instruction *InsertBefore, BasicBlock *InsertAtEnd, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize, Function *MallocF, const Twine &Name)
static Instruction * createFree (Value *Source, Instruction *InsertBefore, BasicBlock *InsertAtEnd)
static Value * getAISize (LLVMContext &Context, Value *Amt)
template<typename IndexTy>
static Type * getIndexedTypeInternal (Type *Ptr, ArrayRef< IndexTy > IdxList)
static bool isConstantAllOnes (const Value *V)
Function Documentation
createFree()
Instruction * createFree (Value * Source, Instruction * InsertBefore, BasicBlock * InsertAtEnd) static
Definition at line 482 of file Instructions.cpp.
References llvm::CallInst::Create(), llvm::dyn_cast(), F, llvm::Module::getContext(), llvm::Type::getInt8PtrTy(), llvm::Module::getOrInsertFunction(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Instruction::getParent(), llvm::Type::getVoidTy(), llvm::CallInst::setCallingConv(), and llvm::CallInst::setTailCall().
Referenced by llvm::CallInst::CreateFree(), and llvm::CallInst::CreateFree().
createMalloc()
Instruction * createMalloc (Instruction * InsertBefore, BasicBlock * InsertAtEnd, Type * IntPtrTy, Type * AllocTy, Value * AllocSize, Value * ArraySize, Function * MallocF, const Twine & Name) static
Definition at line 372 of file Instructions.cpp.
References llvm::cast(), llvm::CallInst::Create(), llvm::CastInst::CreateIntegerCast(), llvm::dyn_cast(), F, llvm::ConstantInt::get(), llvm::BasicBlock::getContext(), llvm::BasicBlock::getInstList(), llvm::Type::getInt8PtrTy(), llvm::ConstantExpr::getIntegerCast(), llvm::ConstantExpr::getMul(), llvm::Module::getOrInsertFunction(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::PointerType::getUnqual(), IsConstantOne(), llvm::Type::isVoidTy(), Name, llvm::iplist< NodeTy, Traits >::push_back(), llvm::CallInst::setCallingConv(), and llvm::CallInst::setTailCall().
Referenced by llvm::CallInst::CreateMalloc(), and llvm::CallInst::CreateMalloc().
getAISize()
Value * getAISize (LLVMContext & Context, Value * Amt) static
Definition at line 820 of file Instructions.cpp.
References llvm::ConstantInt::get(), llvm::Type::getInt32Ty(), llvm::Value::getType(), llvm::isa(), and llvm::Type::isIntegerTy().
Referenced by llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), llvm::AllocaInst::AllocaInst(), and llvm::AllocaInst::AllocaInst().
getIndexedTypeInternal()
template<typename IndexTy> Type * getIndexedTypeInternal (Type * Ptr, ArrayRef< IndexTy > IdxList) static
getIndexedType - Returns the type of the element that would be accessed with a gep instruction with the specified parameters.
The Idxs pointer should point to a continuous piece of memory containing the indices, either as Value* or uint64_t.
A null type is returned if the indices are invalid for the specified pointer type.
Definition at line 1370 of file Instructions.cpp.
References llvm::dyn_cast(), llvm::ArrayRef< T >::empty(), llvm::SequentialType::getElementType(), llvm::Type::getScalarType(), llvm::CompositeType::getTypeAtIndex(), llvm::CompositeType::indexValid(), llvm::Type::isPointerTy(), llvm::Type::isSized(), and llvm::ArrayRef< T >::size().
Referenced by llvm::GetElementPtrInst::getIndexedType(), llvm::GetElementPtrInst::getIndexedType(), and llvm::GetElementPtrInst::getIndexedType().
isConstantAllOnes()
bool isConstantAllOnes (const Value * V) inline static
Definition at line 1930 of file Instructions.cpp.
References llvm::dyn_cast().
Referenced by llvm::BinaryOperator::getNotArgument(), and llvm::BinaryOperator::isNot().
IsConstantOne()
bool IsConstantOne (Value * val) static
IsConstantOne - Return true only if val is constant int 1.
Definition at line 366 of file Instructions.cpp.
References llvm::dyn_cast(), and llvm::ConstantInt::isOne().
Referenced by createMalloc().