LLVM: InstrProfiling.cpp File Reference
LLVM API Documentation
InstrProfiling.cpp File Reference
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/ADT/Triple.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
Macros
#define DEBUG_TYPE "instrprof"
Functions
INITIALIZE_PASS (InstrProfiling, "instrprof", "Frontend instrumentation-based coverage lowering.", false, false) ModulePass *llvm
static std::string getVarName (InstrProfIncrementInst *Inc, StringRef VarName)
Get the name of a profiling variable for a particular function.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "instrprof"
Definition at line 26 of file InstrProfiling.cpp.
Function Documentation
getVarName()
std::string getVarName (InstrProfIncrementInst * Inc, StringRef VarName) static
Get the name of a profiling variable for a particular function.
Definition at line 185 of file InstrProfiling.cpp.
References llvm::cast(), llvm::GlobalVariable::getInitializer(), llvm::InstrProfIncrementInst::getName(), and Name.
INITIALIZE_PASS()
INITIALIZE_PASS (InstrProfiling , "instrprof" , "Frontend instrumentation-based coverage lowering." , false , false)
Definition at line 107 of file InstrProfiling.cpp.
References const, and llvm::createInstrProfilingPass().