LLVM: IRBuilder.cpp File Reference
LLVM API Documentation
IRBuilder.cpp File Reference
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
Functions
static CallInst * createCallHelper (Value *Callee, ArrayRef< Value * > Ops, IRBuilderBase *Builder, const Twine &Name="")
Function Documentation
createCallHelper()
CallInst * createCallHelper (Value * Callee, ArrayRef< Value * > Ops, IRBuilderBase * Builder, const Twine & Name = "") static
Definition at line 55 of file IRBuilder.cpp.
References llvm::CallInst::Create(), llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::GetInsertPoint(), llvm::BasicBlock::getInstList(), llvm::iplist< NodeTy, Traits >::insert(), Name, and llvm::IRBuilderBase::SetInstDebugLocation().
Referenced by llvm::IRBuilderBase::CreateAssumption(), llvm::IRBuilderBase::CreateGCRelocate(), llvm::IRBuilderBase::CreateGCResult(), llvm::IRBuilderBase::CreateGCStatepoint(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), and llvm::IRBuilderBase::CreateMemSet().