LLVM: IRObjectFile.cpp File Reference
LLVM API Documentation
IRObjectFile.cpp File Reference
#include "llvm/Object/IRObjectFile.h"
#include "RecordStreamer.h"
#include "llvm/Bitcode/ReaderWriter.h"
#include "llvm/IR/GVMaterializer.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCTargetAsmParser.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
Functions
static GlobalValue * getGV (DataRefImpl &Symb)
static uintptr_t skipEmpty (Module::const_alias_iterator I, const Module &M)
static uintptr_t skipEmpty (Module::const_global_iterator I, const Module &M)
static uintptr_t skipEmpty (Module::const_iterator I, const Module &M)
static unsigned getAsmSymIndex (DataRefImpl Symb)
Function Documentation
getAsmSymIndex()
unsigned getAsmSymIndex (DataRefImpl Symb) static
Definition at line 147 of file IRObjectFile.cpp.
References llvm::object::DataRefImpl::p.
Referenced by llvm::object::IRObjectFile::getSymbolFlags(), llvm::object::IRObjectFile::moveSymbolNext(), and llvm::object::IRObjectFile::printSymbolName().
getGV()
GlobalValue * getGV (DataRefImpl & Symb) static
Definition at line 119 of file IRObjectFile.cpp.
References llvm::object::DataRefImpl::p.
Referenced by duplicateCPV(), llvm::object::IRObjectFile::getSymbolFlags(), llvm::object::IRObjectFile::getSymbolGV(), llvm::object::IRObjectFile::moveSymbolNext(), and llvm::object::IRObjectFile::printSymbolName().
skipEmpty() [1/3]
uintptr_t skipEmpty (Module::const_alias_iterator I, const Module & M) static
Definition at line 126 of file IRObjectFile.cpp.
References llvm::Module::alias_end(), and I.
Referenced by llvm::object::IRObjectFile::moveSymbolNext(), skipEmpty(), skipEmpty(), and llvm::object::IRObjectFile::symbol_begin_impl().
skipEmpty() [2/3]
uintptr_t skipEmpty (Module::const_global_iterator I, const Module & M) static
Definition at line 133 of file IRObjectFile.cpp.
References llvm::Module::alias_begin(), llvm::Module::global_end(), I, and skipEmpty().
skipEmpty() [3/3]
uintptr_t skipEmpty (Module::const_iterator I, const Module & M) static
Definition at line 140 of file IRObjectFile.cpp.
References llvm::Module::end(), llvm::Module::global_begin(), I, and skipEmpty().