LLVM: LazyValueInfo.cpp File Reference
LLVM API Documentation
LazyValueInfo.cpp File Reference
#include "llvm/Analysis/LazyValueInfo.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include <map>
#include <stack>
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "lazy-value-info"
Functions
INITIALIZE_PASS_BEGIN (LazyValueInfo, "lazy-value-info", "Lazy Value Information Analysis", false, true) INITIALIZE_PASS_END(LazyValueInfo
FunctionPass * llvm::createLazyValueInfoPass ()
raw_ostream & llvm::operator<< (raw_ostream &OS, const LVILatticeVal &Val) LLVM_ATTRIBUTE_USED
static bool InstructionDereferencesPointer (Instruction *I, Value *Ptr)
static bool getValueFromFromCondition (Value *Val, ICmpInst *ICI, LVILatticeVal &Result, bool isTrueDest=true)
static bool getEdgeValueLocal (Value *Val, BasicBlock *BBFrom, BasicBlock *BBTo, LVILatticeVal &Result)
Compute the value of Val on the edge BBFrom -> BBTo. Returns false if Val is not constrained on the edge.
static LazyValueInfoCache & getCache (void *&PImpl, AssumptionCache *AC, const DataLayout *DL=nullptr, DominatorTree *DT=nullptr)
This lazily constructs the LazyValueInfoCache.
static LazyValueInfo::Tristate getPredicateResult (unsigned Pred, Constant *C, LVILatticeVal &Result, const DataLayout *DL, TargetLibraryInfo *TLI)
Variables
lazy value info
lazy value Lazy Value Information Analysis
lazy value Lazy Value Information false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lazy-value-info"
Definition at line 38 of file LazyValueInfo.cpp.
Function Documentation
getCache()
LazyValueInfoCache & getCache (void *& PImpl, AssumptionCache * AC, const DataLayout * DL = nullptr, DominatorTree * DT = nullptr) static
This lazily constructs the LazyValueInfoCache.
Definition at line 1106 of file LazyValueInfo.cpp.
Referenced by llvm::LazyValueInfo::eraseBlock(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), llvm::SourceMgr::getLineAndColumn(), llvm::LazyValueInfo::getPredicateAt(), llvm::LazyValueInfo::getPredicateOnEdge(), llvm::LazyValueInfo::releaseMemory(), llvm::LazyValueInfo::runOnFunction(), llvm::LazyValueInfo::threadEdge(), and llvm::SourceMgr::~SourceMgr().
getEdgeValueLocal()
bool getEdgeValueLocal (Value * Val, BasicBlock * BBFrom, BasicBlock * BBTo, LVILatticeVal & Result) static
Compute the value of Val on the edge BBFrom -> BBTo. Returns false if Val is not constrained on the edge.
Definition at line 881 of file LazyValueInfo.cpp.
References llvm::ConstantRange::difference(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::Value::getContext(), llvm::Type::getInt1Ty(), llvm::Type::getIntegerBitWidth(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), getValueFromFromCondition(), and llvm::ConstantRange::unionWith().
getPredicateResult()
LazyValueInfo::Tristate getPredicateResult (unsigned Pred, Constant * C, LVILatticeVal & Result, const DataLayout * DL, TargetLibraryInfo * TLI) static
Definition at line 1181 of file LazyValueInfo.cpp.
References llvm::ConstantFoldCompareInstOperands(), llvm::ConstantRange::contains(), llvm::dyn_cast(), llvm::LazyValueInfo::False, llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::ConstantRange::inverse(), llvm::Constant::isNullValue(), llvm::ConstantRange::isSingleElement(), llvm::ICmpInst::makeConstantRange(), llvm::LazyValueInfo::True, and llvm::LazyValueInfo::Unknown.
Referenced by llvm::LazyValueInfo::getPredicateAt(), and llvm::LazyValueInfo::getPredicateOnEdge().
getValueFromFromCondition()
bool getValueFromFromCondition (Value * Val, ICmpInst * ICI, LVILatticeVal & Result, bool isTrueDest = true) static
Definition at line 838 of file LazyValueInfo.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_ULT, llvm::ConstantRange::inverse(), llvm::isa(), llvm::ICmpInst::isEquality(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Specific(), llvm::ConstantRange::makeICmpRegion(), llvm::PatternMatch::match(), and llvm::ConstantRange::subtract().
Referenced by getEdgeValueLocal().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LazyValueInfo , "lazy-value-info" , "Lazy Value Information Analysis" , false , true)
References INITIALIZE_PASS_DEPENDENCY.
InstructionDereferencesPointer()
bool InstructionDereferencesPointer (Instruction * I, Value * Ptr) static
Definition at line 579 of file LazyValueInfo.cpp.
References llvm::dyn_cast(), llvm::GetUnderlyingObject(), I, and llvm::ConstantInt::isZero().
Variable Documentation
Analysis
lazy value Lazy Value Information Analysis
Definition at line 46 of file LazyValueInfo.cpp.
false
lazy value Lazy Value Information false
Definition at line 46 of file LazyValueInfo.cpp.
info
lazy value info
Definition at line 45 of file LazyValueInfo.cpp.
Referenced by llvm::EmitRuntimeFunction(), llvm::EmitUnwindInfo(), llvm::Win64EH::UnwindEmitter::EmitUnwindInfo(), llvm::CCState::getInRegsParamInfo(), llvm::TargetLowering::getMultipleConstraintMatchWeight(), llvm::ARMTargetLowering::getSingleConstraintMatchWeight(), llvm::PPCTargetLowering::getSingleConstraintMatchWeight(), llvm::SparcTargetLowering::getSingleConstraintMatchWeight(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::TargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::opt::Option::Option(), and llvm::MachO::swapStruct().