LLVM: LineEditor.cpp File Reference
LLVM API Documentation
LineEditor.cpp File Reference
#include "llvm/LineEditor/LineEditor.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Config/config.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <stdio.h>
#include <histedit.h>
Classes
struct llvm::LineEditor::InternalData
Functions
static const char * ElGetPromptFn (EditLine *EL)
static unsigned char ElCompletionFn (EditLine *EL, int ch)
Function Documentation
ElCompletionFn()
unsigned char ElCompletionFn (EditLine * EL, int ch) static
Definition at line 120 of file LineEditor.cpp.
References llvm::LineEditor::CompletionAction::AK_Insert, llvm::LineEditor::CompletionAction::AK_ShowCompletions, llvm::LineEditor::CompletionAction::Completions, llvm::LineEditor::InternalData::ContinuationOutput, llvm::LineEditor::getCompletionAction(), llvm::LineEditor::getPrompt(), I, llvm::LineEditor::CompletionAction::Kind, llvm::LineEditor::InternalData::LE, llvm::LineEditor::InternalData::Out, llvm::LineEditor::InternalData::PrevCount, and llvm::LineEditor::CompletionAction::Text.
Referenced by llvm::LineEditor::LineEditor().
ElGetPromptFn()
const char * ElGetPromptFn (EditLine * EL) static
Definition at line 109 of file LineEditor.cpp.
References llvm::LineEditor::getPrompt(), and llvm::LineEditor::InternalData::LE.
Referenced by llvm::LineEditor::LineEditor().