LLVM: LiveDebugVariables.cpp File Reference
LLVM API Documentation
LiveDebugVariables.cpp File Reference
#include "LiveDebugVariables.h"
#include "llvm/ADT/IntervalMap.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LexicalScopes.h"
#include "llvm/CodeGen/LiveIntervalAnalysis.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include <memory>
Macros
#define DEBUG_TYPE "livedebug"
Typedefs
typedef IntervalMap< SlotIndex, unsigned, 4 > LocMap
LocMap - Map of where a user value is live, and its location.
Functions
STATISTIC (NumInsertedDebugValues, "Number of DBG_VALUEs inserted")
INITIALIZE_PASS_BEGIN (LiveDebugVariables, "livedebugvars", "Debug Variable Analysis", false, false) INITIALIZE_PASS_END(LiveDebugVariables
static void removeDebugValues (MachineFunction &mf)
static MachineBasicBlock::iterator findInsertLocation (MachineBasicBlock *MBB, SlotIndex Idx, LiveIntervals &LIS)
Variables
static cl::opt< bool > EnableLDV ("live-debug-variables", cl::init(true), cl::desc("Enable the live debug variables pass"), cl::Hidden)
livedebugvars
Debug Variable Analysis
Debug Variable false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "livedebug"
Definition at line 47 of file LiveDebugVariables.cpp.
Typedef Documentation
LocMap
typedef IntervalMap<SlotIndex, unsigned, 4> LocMap
LocMap - Map of where a user value is live, and its location.
Definition at line 75 of file LiveDebugVariables.cpp.
Function Documentation
findInsertLocation()
MachineBasicBlock::iterator findInsertLocation (MachineBasicBlock * MBB, SlotIndex Idx, LiveIntervals & LIS) static
findInsertLocation - Find an iterator for inserting a DBG_VALUE instruction.
Definition at line 923 of file LiveDebugVariables.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SlotIndex::getBaseIndex(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::LiveIntervals::getMBBStartIdx(), llvm::SlotIndex::getPrevIndex(), I, and llvm::MachineBasicBlock::SkipPHIsAndLabels().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (LiveDebugVariables , "livedebugvars" , "Debug Variable Analysis" , false , false)
References INITIALIZE_PASS_DEPENDENCY.
removeDebugValues()
void removeDebugValues (MachineFunction & mf) static
Definition at line 719 of file LiveDebugVariables.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), and llvm::MachineBasicBlock::erase().
STATISTIC()
STATISTIC (NumInsertedDebugValues , "Number of DBG_VALUEs inserted")
References llvm::LiveDebugVariables::ID.
Variable Documentation
Analysis
Debug Variable Analysis
Definition at line 61 of file LiveDebugVariables.cpp.
EnableLDV
cl::opt< bool > EnableLDV("live-debug-variables", cl::init(true), cl::desc("Enable the live debug variables pass"), cl::Hidden) ("live-debug-variables" , cl::init(true) , cl::desc("Enable the live debug variables pass") , cl::Hidden) static
false
Debug Variable false
Definition at line 61 of file LiveDebugVariables.cpp.
livedebugvars
livedebugvars
Definition at line 60 of file LiveDebugVariables.cpp.