LLVM: Linker.h File Reference
LLVM API Documentation
Linker.h File Reference
#include "llvm-c/Core.h"
Enumerations
enum LLVMLinkerMode { LLVMLinkerDestroySource = 0 , LLVMLinkerPreserveSource = 1 }
Functions
LLVMBool LLVMLinkModules (LLVMModuleRef Dest, LLVMModuleRef Src, LLVMLinkerMode Mode, char **OutMessage)
Enumeration Type Documentation
LLVMLinkerMode
enum LLVMLinkerMode
Enumerator
LLVMLinkerDestroySource
LLVMLinkerPreserveSource
Definition at line 25 of file llvm-c/Linker.h.
Function Documentation
LLVMLinkModules()
LLVMBool LLVMLinkModules (LLVMModuleRef Dest, LLVMModuleRef Src, LLVMLinkerMode Mode, char ** OutMessage)
Definition at line 1751 of file LinkModules.cpp.
References llvm::Linker::LinkModules(), llvm::DiagnosticInfo::print(), and llvm::unwrap().