LLVM: LoopUnrollRuntime.cpp File Reference
LLVM API Documentation
LoopUnrollRuntime.cpp File Reference
#include "llvm/Transforms/Utils/UnrollLoop.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpander.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Metadata.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "loop-unroll"
Functions
STATISTIC (NumRuntimeUnrolled, "Number of loops unrolled with run-time trip counts")
static void ConnectProlog (Loop *L, Value *BECount, unsigned Count, BasicBlock *LastPrologBB, BasicBlock *PrologEnd, BasicBlock *OrigPH, BasicBlock *NewPH, ValueToValueMapTy &VMap, Pass *P)
static void CloneLoopBlocks (Loop *L, Value *NewIter, const bool UnrollProlog, BasicBlock *InsertTop, BasicBlock *InsertBot, std::vector< BasicBlock * > &NewBlocks, LoopBlocksDFS &LoopBlocks, ValueToValueMapTy &VMap, LoopInfo *LI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-unroll"
Definition at line 40 of file LoopUnrollRuntime.cpp.
Function Documentation
CloneLoopBlocks()
void CloneLoopBlocks (Loop * L, Value * NewIter, const bool UnrollProlog, BasicBlock * InsertTop, BasicBlock * InsertBot, std::vector< BasicBlock * > & NewBlocks, LoopBlocksDFS & LoopBlocks, ValueToValueMapTy & VMap, LoopInfo * LI) static
Create a clone of the blocks in a loop and connect them together. If UnrollProlog is true, loop structure will not be cloned, otherwise a new loop will be created including all cloned blocks, and the iterator of it switches to count NewIter down to 0.
Definition at line 142 of file LoopUnrollRuntime.cpp.
References llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::PHINode::addIncoming(), llvm::LoopInfo::addTopLevelLoop(), llvm::BasicBlock::begin(), llvm::LoopBlocksDFS::beginRPO(), llvm::cast(), llvm::CloneBasicBlock(), llvm::BranchInst::Create(), llvm::PHINode::Create(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateIsNotNull(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSub(), llvm::dyn_cast(), llvm::LoopBlocksDFS::endRPO(), llvm::ValueMap< KeyT, ValueT, Config >::erase(), llvm::Instruction::eraseFromParent(), F, llvm::ConstantInt::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::LoopInfo::getBase(), llvm::PHINode::getBasicBlockIndex(), llvm::BasicBlock::getContext(), llvm::BasicBlock::getFirstNonPHI(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getIncomingValueForBlock(), llvm::Loop::getLoopID(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::Value::getName(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::BasicBlock::getParent(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::MDString::getString(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), I, llvm::isa(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::MDNode::replaceOperandWith(), llvm::PHINode::setIncomingBlock(), llvm::PHINode::setIncomingValue(), llvm::Loop::setLoopID(), llvm::TerminatorInst::setSuccessor(), and llvm::StringRef::startswith().
Referenced by llvm::UnrollRuntimeLoopProlog().
ConnectProlog()
void ConnectProlog (Loop * L, Value * BECount, unsigned Count, BasicBlock * LastPrologBB, BasicBlock * PrologEnd, BasicBlock * OrigPH, BasicBlock * NewPH, ValueToValueMapTy & VMap, Pass * P) static
Connect the unrolling prolog code to the original loop. The unrolling prolog code contains code to execute the 'extra' iterations if the run-time trip count modulo the unroll count is non-zero.
This function performs the following:
Create PHI nodes at prolog end block to combine values that exit the prolog code and jump around the prolog.
Add a PHI operand to a PHI node at the loop exit block for values that exit the prolog and go around the loop.
Branch around the original loop if the trip count is less than the unroll factor.
Definition at line 58 of file LoopUnrollRuntime.cpp.
References llvm::PHINode::addIncoming(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::BranchInst::Create(), llvm::PHINode::Create(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::ConstantInt::get(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::Constant::getNullValue(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Loop::getUniqueExitBlock(), I, llvm::CmpInst::ICMP_ULT, llvm::BasicBlock::isLandingPad(), P, llvm::pred_begin(), llvm::pred_end(), llvm::SplitBlockPredecessors(), llvm::SplitLandingPadPredecessors(), llvm::succ_begin(), and llvm::succ_end().
Referenced by llvm::UnrollRuntimeLoopProlog().
STATISTIC()
STATISTIC (NumRuntimeUnrolled , "Number of loops unrolled with run-time trip counts")