LLVM: LoopPass.cpp File Reference
LLVM API Documentation
LoopPass.cpp File Reference
#include "llvm/Analysis/LoopPass.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Timer.h"
Macros
#define DEBUG_TYPE "loop-pass-manager"
Functions
static void addLoopIntoQueue (Loop *L, std::deque< Loop * > &LQ)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-pass-manager"
Definition at line 23 of file LoopPass.cpp.
Function Documentation
addLoopIntoQueue()
void addLoopIntoQueue (Loop * L, std::deque< Loop * > & LQ) static
Definition at line 180 of file LoopPass.cpp.
References addLoopIntoQueue(), I, llvm::LoopBase< BlockT, LoopT >::rbegin(), and llvm::LoopBase< BlockT, LoopT >::rend().
Referenced by addLoopIntoQueue(), and llvm::LPPassManager::runOnFunction().