LLVM: LoopRerollPass.cpp File Reference
LLVM API Documentation
LoopRerollPass.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AliasSetTracker.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpander.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
Macros
#define DEBUG_TYPE "loop-reroll"
Functions
STATISTIC (NumRerolledLoops, "Number of rerolled loops")
static bool hasUsesOutsideLoop (Instruction *I, Loop *L)
static bool isSimpleLoadStore (Instruction *I)
Variables
static cl::opt< unsigned > MaxInc ("max-reroll-increment", cl::init(2048), cl::Hidden, cl::desc("The maximum increment for loop rerolling"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-reroll"
Definition at line 38 of file LoopRerollPass.cpp.
Function Documentation
hasUsesOutsideLoop()
bool hasUsesOutsideLoop (Instruction * I, Loop * L) static
Definition at line 355 of file LoopRerollPass.cpp.
References llvm::cast(), llvm::LoopBase< BlockT, LoopT >::contains(), and I.
isSimpleLoadStore()
bool isSimpleLoadStore (Instruction * I) static
Definition at line 517 of file LoopRerollPass.cpp.
References llvm::dyn_cast(), and I.
STATISTIC()
STATISTIC (NumRerolledLoops , "Number of rerolled loops")
Variable Documentation
MaxInc
cl::opt< unsigned > MaxInc("max-reroll-increment", cl::init(2048), cl::Hidden, cl::desc("The maximum increment for loop rerolling")) ("max-reroll-increment" , cl::init(2048) , cl::Hidden , cl::desc("The maximum increment for loop rerolling")) static