LLVM: MachineSink.cpp File Reference
LLVM API Documentation
MachineSink.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachinePostDominators.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Macros
#define DEBUG_TYPE "machine-sink"
Functions
STATISTIC (NumSunk, "Number of machine instructions sunk")
STATISTIC (NumSplit, "Number of critical edges split")
STATISTIC (NumCoalesces, "Number of copies coalesced")
INITIALIZE_PASS_BEGIN (MachineSinking, "machine-sink", "Machine code sinking", false, false) INITIALIZE_PASS_END(MachineSinking
static bool AvoidsSinking (MachineInstr *MI, MachineRegisterInfo *MRI)
static void collectDebugValues (MachineInstr *MI, SmallVectorImpl< MachineInstr * > &DbgValues)
Variables
static cl::opt< bool > SplitEdges ("machine-sink-split", cl::desc("Split critical edges during machine sinking"), cl::init(true), cl::Hidden)
static cl::opt< bool > UseBlockFreqInfo ("machine-sink-bfi", cl::desc("Use block frequency info to find successors to sink"), cl::init(true), cl::Hidden)
machine sink
machine Machine code sinking
machine Machine code false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-sink"
Definition at line 37 of file MachineSink.cpp.
Function Documentation
AvoidsSinking()
bool AvoidsSinking (MachineInstr * MI, MachineRegisterInfo * MRI) static
Definition at line 452 of file MachineSink.cpp.
collectDebugValues()
void collectDebugValues (MachineInstr * MI, SmallVectorImpl< MachineInstr * > & DbgValues) static
collectDebgValues - Scan instructions following MI and collect any matching DBG_VALUEs.
Definition at line 458 of file MachineSink.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isReg(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (MachineSinking , "machine-sink" , "Machine code sinking" , false , false)
References INITIALIZE_AG_DEPENDENCY, and INITIALIZE_PASS_DEPENDENCY.
STATISTIC() [1/3]
STATISTIC (NumCoalesces , "Number of copies coalesced")
References llvm::PassRegistry::getPassRegistry(), and TII.
STATISTIC() [2/3]
STATISTIC (NumSplit , "Number of critical edges split")
STATISTIC() [3/3]
STATISTIC (NumSunk , "Number of machine instructions sunk")
Variable Documentation
false
machine Machine code false
Definition at line 143 of file MachineSink.cpp.
sink
void LICM::sink
sink - When an instruction is found to only be used outside of the loop, this function moves it to the exit blocks and patches up SSA form as needed. This method is guaranteed to remove the original instruction from its position, and may either delete it or move it to outside of the loop.
Definition at line 142 of file MachineSink.cpp.
sinking
machine Machine code sinking
Definition at line 143 of file MachineSink.cpp.
SplitEdges
cl::opt< bool > SplitEdges("machine-sink-split", cl::desc("Split critical edges during machine sinking"), cl::init(true), cl::Hidden) ("machine-sink-split" , cl::desc("Split critical edges during machine sinking") , cl::init(true) , cl::Hidden) static
UseBlockFreqInfo
cl::opt< bool > UseBlockFreqInfo("machine-sink-bfi", cl::desc("Use block frequency info to find successors to sink"), cl::init(true), cl::Hidden) ("machine-sink-bfi" , cl::desc("Use block frequency info to find successors to sink") , cl::init(true) , cl::Hidden) static