LLVM: MachOObjectFile.cpp File Reference
LLVM API Documentation
MachOObjectFile.cpp File Reference
#include "llvm/Object/MachO.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MachO.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"
#include <cctype>
#include <cstring>
#include <limits>
Functions
template<typename T>
static T getStruct (const MachOObjectFile *O, const char *P)
static uint32_t getSegmentLoadCommandNumSections (const MachOObjectFile *O, const MachOObjectFile::LoadCommandInfo &L)
static bool isPageZeroSegment (const MachOObjectFile *O, const MachOObjectFile::LoadCommandInfo &L)
static const char * getSectionPtr (const MachOObjectFile *O, MachOObjectFile::LoadCommandInfo L, unsigned Sec)
static const char * getPtr (const MachOObjectFile *O, size_t Offset)
static MachO::nlist_base getSymbolTableEntryBase (const MachOObjectFile *O, DataRefImpl DRI)
static StringRef parseSegmentOrSectionName (const char *P)
template<class T>
static void advance (T &it, size_t Val)
static unsigned getCPUType (const MachOObjectFile *O)
static void printRelocationTargetName (const MachOObjectFile *O, const MachO::any_relocation_info &RE, raw_string_ostream &fmt)
static uint32_t getPlainRelocationAddress (const MachO::any_relocation_info &RE)
static unsigned getScatteredRelocationAddress (const MachO::any_relocation_info &RE)
static bool getPlainRelocationPCRel (const MachOObjectFile *O, const MachO::any_relocation_info &RE)
static bool getScatteredRelocationPCRel (const MachOObjectFile *O, const MachO::any_relocation_info &RE)
static unsigned getPlainRelocationLength (const MachOObjectFile *O, const MachO::any_relocation_info &RE)
static unsigned getScatteredRelocationLength (const MachO::any_relocation_info &RE)
static unsigned getPlainRelocationType (const MachOObjectFile *O, const MachO::any_relocation_info &RE)
static uint32_t getSectionFlags (const MachOObjectFile *O, DataRefImpl Sec)
Function Documentation
advance()
template<class T> void advance (T & it, size_t Val) static
Definition at line 107 of file MachOObjectFile.cpp.
References T.
Referenced by llvm::IntervalMapOverlaps< MapA, MapB >::advanceTo(), llvm::IntervalMapOverlaps< MapA, MapB >::IntervalMapOverlaps(), llvm::MachineRegisterInfo::defusechain_instr_iterator< true, true, false, false, true, false >::operator++(), llvm::MachineRegisterInfo::defusechain_iterator< true, true, false, true, false, false >::operator++(), printRelocationTargetName(), llvm::IntervalMapOverlaps< MapA, MapB >::skipA(), and llvm::IntervalMapOverlaps< MapA, MapB >::skipB().
getCPUType()
unsigned getCPUType (const MachOObjectFile * O) static
Definition at line 112 of file MachOObjectFile.cpp.
References llvm::MachO::mach_header::cputype, and llvm::object::MachOObjectFile::getHeader().
Referenced by llvm::object::MachOObjectFile::getArch(), llvm::object::MachOObjectFile::getFileFormatName(), and llvm::object::MachOObjectFile::isRelocationScattered().
getPlainRelocationAddress()
uint32_t getPlainRelocationAddress (const MachO::any_relocation_info & RE) static
Definition at line 181 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationAddress(), and llvm::object::MachOObjectFile::isRelocationScattered().
getPlainRelocationLength()
unsigned getPlainRelocationLength (const MachOObjectFile * O, const MachO::any_relocation_info & RE) static
Definition at line 203 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationLength().
getPlainRelocationPCRel()
bool getPlainRelocationPCRel (const MachOObjectFile * O, const MachO::any_relocation_info & RE) static
Definition at line 190 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationPCRel().
getPlainRelocationType()
unsigned getPlainRelocationType (const MachOObjectFile * O, const MachO::any_relocation_info & RE) static
Definition at line 215 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationType().
getPtr()
const char * getPtr (const MachOObjectFile * O, size_t Offset) static
Definition at line 87 of file MachOObjectFile.cpp.
References llvm::StringRef::data(), llvm::object::Binary::getData(), and llvm::StringRef::substr().
Referenced by llvm::object::MachOObjectFile::begin_dices(), llvm::object::MachOObjectFile::end_dices(), llvm::object::MachOObjectFile::getDataInCodeTableEntry(), llvm::object::MachOObjectFile::getDyldInfoBindOpcodes(), llvm::object::MachOObjectFile::getDyldInfoExportsTrie(), llvm::object::MachOObjectFile::getDyldInfoLazyBindOpcodes(), llvm::object::MachOObjectFile::getDyldInfoRebaseOpcodes(), llvm::object::MachOObjectFile::getDyldInfoWeakBindOpcodes(), llvm::object::MachOObjectFile::getFirstLoadCommandInfo(), llvm::object::MachOObjectFile::getHeader(), llvm::object::MachOObjectFile::getHeader64(), llvm::object::MachOObjectFile::getIndirectSymbolTableEntry(), llvm::object::MachOObjectFile::getRelocation(), llvm::object::MachOObjectFile::getRelocationSymbol(), llvm::object::MachOObjectFile::getSymbolByIndex(), and llvm::object::MachOObjectFile::symbol_end_impl().
getScatteredRelocationAddress()
unsigned getScatteredRelocationAddress (const MachO::any_relocation_info & RE) static
Definition at line 186 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationAddress().
getScatteredRelocationLength()
unsigned getScatteredRelocationLength (const MachO::any_relocation_info & RE) static
Definition at line 211 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationLength().
getScatteredRelocationPCRel()
bool getScatteredRelocationPCRel (const MachOObjectFile * O, const MachO::any_relocation_info & RE) static
Definition at line 198 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationPCRel().
getSectionFlags()
uint32_t getSectionFlags (const MachOObjectFile * O, DataRefImpl Sec) static
Definition at line 222 of file MachOObjectFile.cpp.
References llvm::MachO::section::flags, llvm::MachO::section_64::flags, llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection64(), and llvm::object::MachOObjectFile::is64Bit().
Referenced by llvm::object::MachOObjectFile::getSectionType(), llvm::object::MachOObjectFile::isSectionBSS(), llvm::object::MachOObjectFile::isSectionData(), and llvm::object::MachOObjectFile::isSectionText().
getSectionPtr()
const char * getSectionPtr (const MachOObjectFile * O, MachOObjectFile::LoadCommandInfo L, unsigned Sec) static
Definition at line 73 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::is64Bit(), and llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
Referenced by llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection64(), and llvm::object::MachOObjectFile::MachOObjectFile().
getSegmentLoadCommandNumSections()
uint32_t getSegmentLoadCommandNumSections (const MachOObjectFile * O, const MachOObjectFile::LoadCommandInfo & L) static
Definition at line 51 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::getSegment64LoadCommand(), llvm::object::MachOObjectFile::getSegmentLoadCommand(), llvm::object::MachOObjectFile::is64Bit(), llvm::MachO::segment_command::nsects, and llvm::MachO::segment_command_64::nsects.
Referenced by llvm::object::MachOObjectFile::MachOObjectFile().
getStruct()
template<typename T> T getStruct (const MachOObjectFile * O, const char * P) static
Definition at line 42 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), llvm::sys::IsLittleEndianHost, P, llvm::MachO::swapStruct(), and T.
Referenced by llvm::object::MachOObjectFile::getDataInCodeLoadCommand(), llvm::object::MachOObjectFile::getDataInCodeTableEntry(), llvm::object::MachOObjectFile::getDice(), llvm::object::MachOObjectFile::getDyldInfoBindOpcodes(), llvm::object::MachOObjectFile::getDyldInfoExportsTrie(), llvm::object::MachOObjectFile::getDyldInfoLazyBindOpcodes(), llvm::object::MachOObjectFile::getDyldInfoLoadCommand(), llvm::object::MachOObjectFile::getDyldInfoRebaseOpcodes(), llvm::object::MachOObjectFile::getDyldInfoWeakBindOpcodes(), llvm::object::MachOObjectFile::getDylibIDLoadCommand(), llvm::object::MachOObjectFile::getDylinkerCommand(), llvm::object::MachOObjectFile::getDysymtabLoadCommand(), llvm::object::MachOObjectFile::getEncryptionInfoCommand(), llvm::object::MachOObjectFile::getEncryptionInfoCommand64(), llvm::object::MachOObjectFile::getEntryPointCommand(), llvm::object::MachOObjectFile::getFirstLoadCommandInfo(), llvm::object::MachOObjectFile::getHeader(), llvm::object::MachOObjectFile::getHeader64(), llvm::object::MachOObjectFile::getIndirectSymbolTableEntry(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::object::MachOObjectFile::getLinkeditDataLoadCommand(), llvm::object::MachOObjectFile::getLinkerOptionLoadCommand(), llvm::object::MachOObjectFile::getNextLoadCommandInfo(), llvm::object::MachOObjectFile::getRelocation(), llvm::object::MachOObjectFile::getRoutinesCommand(), llvm::object::MachOObjectFile::getRoutinesCommand64(), llvm::object::MachOObjectFile::getRpathCommand(), llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection64(), llvm::object::MachOObjectFile::getSection64(), llvm::object::MachOObjectFile::getSegment64LoadCommand(), llvm::object::MachOObjectFile::getSegmentLoadCommand(), llvm::object::MachOObjectFile::getSourceVersionCommand(), llvm::object::MachOObjectFile::getSubClientCommand(), llvm::object::MachOObjectFile::getSubFrameworkCommand(), llvm::object::MachOObjectFile::getSubLibraryCommand(), llvm::object::MachOObjectFile::getSubUmbrellaCommand(), llvm::object::MachOObjectFile::getSymbol64TableEntry(), llvm::object::MachOObjectFile::getSymbolTableEntry(), getSymbolTableEntryBase(), llvm::object::MachOObjectFile::getSymtabLoadCommand(), llvm::object::MachOObjectFile::getThreadCommand(), llvm::object::MachOObjectFile::getUuidCommand(), and llvm::object::MachOObjectFile::getVersionMinLoadCommand().
getSymbolTableEntryBase()
MachO::nlist_base getSymbolTableEntryBase (const MachOObjectFile * O, DataRefImpl DRI) static
Definition at line 92 of file MachOObjectFile.cpp.
References getStruct(), P, and llvm::object::DataRefImpl::p.
Referenced by llvm::object::MachOObjectFile::getSymbolAlignment(), llvm::object::MachOObjectFile::getSymbolFlags(), llvm::object::MachOObjectFile::getSymbolName(), llvm::object::MachOObjectFile::getSymbolSection(), llvm::object::MachOObjectFile::getSymbolSize(), and llvm::object::MachOObjectFile::getSymbolType().
isPageZeroSegment()
bool isPageZeroSegment (const MachOObjectFile * O, const MachOObjectFile::LoadCommandInfo & L) static
Definition at line 61 of file MachOObjectFile.cpp.
References llvm::StringRef::equals(), llvm::object::MachOObjectFile::getSegment64LoadCommand(), llvm::object::MachOObjectFile::getSegmentLoadCommand(), llvm::object::MachOObjectFile::is64Bit(), llvm::MachO::segment_command::segname, and llvm::MachO::segment_command_64::segname.
Referenced by llvm::object::MachOObjectFile::MachOObjectFile().
parseSegmentOrSectionName()
StringRef parseSegmentOrSectionName (const char * P) static
Definition at line 97 of file MachOObjectFile.cpp.
References P.
Referenced by llvm::object::MachOObjectFile::getSectionFinalSegmentName(), and llvm::object::MachOObjectFile::getSectionName().
printRelocationTargetName()
void printRelocationTargetName (const MachOObjectFile * O, const MachO::any_relocation_info & RE, raw_string_ostream & fmt) static
Definition at line 116 of file MachOObjectFile.cpp.
References advance(), llvm::format(), llvm::object::MachOObjectFile::getPlainRelocationExternal(), llvm::object::MachOObjectFile::getPlainRelocationSymbolNum(), llvm::object::MachOObjectFile::isRelocationScattered(), Name, llvm::report_fatal_error(), llvm::object::MachOObjectFile::section_begin(), llvm::object::ObjectFile::sections(), llvm::object::SymbolicFile::symbol_begin(), and llvm::object::ObjectFile::symbols().
Referenced by llvm::object::MachOObjectFile::getRelocationValueString().