LLVM: MCDwarf.cpp File Reference
LLVM API Documentation
MCDwarf.cpp File Reference
#include "llvm/MC/MCDwarf.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/config.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct llvm::DenseMapInfo< CIEKey >
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define SPECIAL_ADDR(op)
#define MAX_SPECIAL_ADDR_DELTA SPECIAL_ADDR(255)
#define DWARF2_LINE_OPCODE_BASE 13
#define DWARF2_LINE_BASE -5
#define DWARF2_LINE_RANGE 14
Functions
static uint64_t ScaleAddrDelta (MCContext &Context, uint64_t AddrDelta)
static const MCExpr * MakeStartMinusEndExpr (const MCStreamer &MCOS, const MCSymbol &Start, const MCSymbol &End, int IntVal)
static void EmitDwarfLineTable (MCObjectStreamer *MCOS, const MCSection *Section, const MCLineSection::MCLineEntryCollection &LineEntries)
static const MCExpr * forceExpAbs (MCStreamer &OS, const MCExpr *Expr)
static void emitAbsValue (MCStreamer &OS, const MCExpr *Value, unsigned Size)
static void EmitAbbrev (MCStreamer *MCOS, uint64_t Name, uint64_t Form)
static void EmitGenDwarfAbbrev (MCStreamer *MCOS)
static void EmitGenDwarfAranges (MCStreamer *MCOS, const MCSymbol *InfoSectionSymbol)
static void EmitGenDwarfInfo (MCStreamer *MCOS, const MCSymbol *AbbrevSectionSymbol, const MCSymbol *LineSectionSymbol, const MCSymbol *RangesSectionSymbol)
static void EmitGenDwarfRanges (MCStreamer *MCOS)
static int getDataAlignmentFactor (MCStreamer &streamer)
static unsigned getSizeForEncoding (MCStreamer &streamer, unsigned symbolEncoding)
static void emitFDESymbol (MCObjectStreamer &streamer, const MCSymbol &symbol, unsigned symbolEncoding, bool isEH)
static void EmitPersonality (MCStreamer &streamer, const MCSymbol &symbol, unsigned symbolEncoding)
static void emitEncodingByte (MCObjectStreamer &Streamer, unsigned Encoding)
Macro Definition Documentation
DWARF2_LINE_BASE
#define DWARF2_LINE_BASE -5
Definition at line 46 of file MCDwarf.cpp.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), and llvm::MCDwarfLineAddr::Encode().
DWARF2_LINE_OPCODE_BASE
#define DWARF2_LINE_OPCODE_BASE 13
Definition at line 42 of file MCDwarf.cpp.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), and llvm::MCDwarfLineAddr::Encode().
DWARF2_LINE_RANGE
#define DWARF2_LINE_RANGE 14
Definition at line 49 of file MCDwarf.cpp.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), and llvm::MCDwarfLineAddr::Encode().
MAX_SPECIAL_ADDR_DELTA
#define MAX_SPECIAL_ADDR_DELTA SPECIAL_ADDR(255)
Definition at line 37 of file MCDwarf.cpp.
Referenced by llvm::MCDwarfLineAddr::Encode().
SPECIAL_ADDR
#define SPECIAL_ADDR (op)
Value:
(((op) - DWARF2_LINE_OPCODE_BASE)/DWARF2_LINE_RANGE)
Definition at line 34 of file MCDwarf.cpp.
Function Documentation
EmitAbbrev()
void EmitAbbrev (MCStreamer * MCOS, uint64_t Name, uint64_t Form) static
Definition at line 511 of file MCDwarf.cpp.
References llvm::MCStreamer::EmitULEB128IntValue(), and Name.
Referenced by EmitGenDwarfAbbrev().
emitAbsValue()
void emitAbsValue (MCStreamer & OS, const MCExpr * Value, unsigned Size) static
Definition at line 261 of file MCDwarf.cpp.
References llvm::MCStreamer::EmitValue(), and forceExpAbs().
Referenced by llvm::MCDwarfLineTableHeader::Emit(), emitFDESymbol(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), and EmitGenDwarfRanges().
EmitDwarfLineTable()
void EmitDwarfLineTable (MCObjectStreamer * MCOS, const MCSection * Section, const MCLineSection::MCLineEntryCollection & LineEntries) inline static
Definition at line 118 of file MCDwarf.cpp.
References llvm::MCContext::CreateTempSymbol(), llvm::dwarf::DW_LNE_set_discriminator, llvm::dwarf::DW_LNS_extended_op, llvm::dwarf::DW_LNS_negate_stmt, llvm::dwarf::DW_LNS_set_basic_block, llvm::dwarf::DW_LNS_set_column, llvm::dwarf::DW_LNS_set_epilogue_begin, llvm::dwarf::DW_LNS_set_file, llvm::dwarf::DW_LNS_set_isa, llvm::dwarf::DW_LNS_set_prologue_end, DWARF2_FLAG_BASIC_BLOCK, DWARF2_FLAG_EPILOGUE_BEGIN, DWARF2_FLAG_IS_STMT, DWARF2_FLAG_PROLOGUE_END, DWARF2_LINE_DEFAULT_IS_STMT, llvm::MCObjectStreamer::EmitDwarfAdvanceLineAddr(), llvm::MCStreamer::EmitIntValue(), llvm::MCObjectStreamer::EmitLabel(), llvm::MCStreamer::EmitULEB128IntValue(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfLineSection(), llvm::MCContext::getObjectFileInfo(), llvm::MCAsmInfo::getPointerSize(), llvm::getULEB128Size(), and llvm::MCStreamer::SwitchSection().
Referenced by llvm::MCDwarfLineTable::EmitCU().
emitEncodingByte()
void emitEncodingByte (MCObjectStreamer & Streamer, unsigned Encoding) static
Definition at line 1041 of file MCDwarf.cpp.
References llvm::MCStreamer::EmitIntValue().
emitFDESymbol()
void emitFDESymbol (MCObjectStreamer & streamer, const MCSymbol & symbol, unsigned symbolEncoding, bool isEH) static
Definition at line 982 of file MCDwarf.cpp.
References llvm::MCAsmInfo::doDwarfFDESymbolsUseAbsDiff(), emitAbsValue(), llvm::MCStreamer::EmitValue(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCAsmInfo::getExprForFDESymbol(), and getSizeForEncoding().
EmitGenDwarfAbbrev()
void EmitGenDwarfAbbrev (MCStreamer * MCOS) static
Definition at line 518 of file MCDwarf.cpp.
References llvm::dwarf::DW_AT_APPLE_flags, llvm::dwarf::DW_AT_comp_dir, llvm::dwarf::DW_AT_decl_file, llvm::dwarf::DW_AT_decl_line, llvm::dwarf::DW_AT_high_pc, llvm::dwarf::DW_AT_language, llvm::dwarf::DW_AT_low_pc, llvm::dwarf::DW_AT_name, llvm::dwarf::DW_AT_producer, llvm::dwarf::DW_AT_prototyped, llvm::dwarf::DW_AT_ranges, llvm::dwarf::DW_AT_stmt_list, llvm::dwarf::DW_CHILDREN_no, llvm::dwarf::DW_CHILDREN_yes, llvm::dwarf::DW_FORM_addr, llvm::dwarf::DW_FORM_data2, llvm::dwarf::DW_FORM_data4, llvm::dwarf::DW_FORM_flag, llvm::dwarf::DW_FORM_string, llvm::dwarf::DW_TAG_compile_unit, llvm::dwarf::DW_TAG_label, llvm::dwarf::DW_TAG_unspecified_parameters, EmitAbbrev(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitULEB128IntValue(), llvm::StringRef::empty(), llvm::MCContext::getCompilationDir(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfAbbrevSection(), llvm::MCContext::getDwarfDebugFlags(), llvm::MCContext::getDwarfVersion(), llvm::MCContext::getGenDwarfSectionSyms(), llvm::MCContext::getObjectFileInfo(), and llvm::MCStreamer::SwitchSection().
Referenced by llvm::MCGenDwarfInfo::Emit().
EmitGenDwarfAranges()
void EmitGenDwarfAranges (MCStreamer * MCOS, const MCSymbol * InfoSectionSymbol) static
Definition at line 569 of file MCDwarf.cpp.
References llvm::MCSymbolRefExpr::Create(), emitAbsValue(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitValue(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfARangesSection(), llvm::MCContext::getGenDwarfSectionSyms(), llvm::MCContext::getObjectFileInfo(), llvm::MCAsmInfo::getPointerSize(), MakeStartMinusEndExpr(), llvm::MCAsmInfo::needsDwarfSectionOffsetDirective(), llvm::MCStreamer::SwitchSection(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCGenDwarfInfo::Emit().
EmitGenDwarfInfo()
void EmitGenDwarfInfo (MCStreamer * MCOS, const MCSymbol * AbbrevSectionSymbol, const MCSymbol * LineSectionSymbol, const MCSymbol * RangesSectionSymbol) static
Definition at line 641 of file MCDwarf.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCContext::CreateTempSymbol(), llvm::dwarf::DW_LANG_Mips_Assembler, emitAbsValue(), llvm::MCStreamer::EmitBytes(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitULEB128IntValue(), llvm::MCStreamer::EmitValue(), llvm::StringRef::empty(), llvm::sys::path::get_separator(), llvm::MCContext::getAsmInfo(), llvm::MCContext::getCompilationDir(), llvm::MCStreamer::getContext(), llvm::MCContext::getDwarfDebugFlags(), llvm::MCContext::getDwarfDebugProducer(), llvm::MCObjectFileInfo::getDwarfInfoSection(), llvm::MCContext::getDwarfVersion(), llvm::MCContext::getGenDwarfSectionSyms(), llvm::MCContext::getMCDwarfDirs(), llvm::MCContext::getMCDwarfFiles(), llvm::MCContext::getMCGenDwarfLabelEntries(), llvm::MCContext::getObjectFileInfo(), llvm::MCAsmInfo::getPointerSize(), MakeStartMinusEndExpr(), Name, llvm::MCAsmInfo::needsDwarfSectionOffsetDirective(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::MCStreamer::SwitchSection(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCGenDwarfInfo::Emit().
EmitGenDwarfRanges()
void EmitGenDwarfRanges (MCStreamer * MCOS) static
Definition at line 805 of file MCDwarf.cpp.
References llvm::MCSymbolRefExpr::Create(), emitAbsValue(), llvm::MCStreamer::EmitFill(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitValue(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCObjectFileInfo::getDwarfRangesSection(), llvm::MCContext::getGenDwarfSectionSyms(), llvm::MCContext::getObjectFileInfo(), llvm::MCAsmInfo::getPointerSize(), MakeStartMinusEndExpr(), llvm::MCStreamer::SwitchSection(), and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCGenDwarfInfo::Emit().
EmitPersonality()
void EmitPersonality (MCStreamer & streamer, const MCSymbol & symbol, unsigned symbolEncoding) static
Definition at line 996 of file MCDwarf.cpp.
References llvm::MCStreamer::EmitValue(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCAsmInfo::getExprForPersonalitySymbol(), and getSizeForEncoding().
forceExpAbs()
const MCExpr * forceExpAbs (MCStreamer & OS, const MCExpr * Expr) static
Definition at line 250 of file MCDwarf.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCContext::CreateTempSymbol(), llvm::MCStreamer::EmitAssignment(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCAsmInfo::hasAggressiveSymbolFolding(), and llvm::isa().
Referenced by emitAbsValue().
getDataAlignmentFactor()
int getDataAlignmentFactor (MCStreamer & streamer) static
Definition at line 951 of file MCDwarf.cpp.
References llvm::MCContext::getAsmInfo(), llvm::MCAsmInfo::getCalleeSaveStackSlotSize(), llvm::MCStreamer::getContext(), and llvm::MCAsmInfo::isStackGrowthDirectionUp().
getSizeForEncoding()
unsigned getSizeForEncoding (MCStreamer & streamer, unsigned symbolEncoding) static
Definition at line 961 of file MCDwarf.cpp.
References llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_sdata2, llvm::dwarf::DW_EH_PE_sdata4, llvm::dwarf::DW_EH_PE_sdata8, llvm::dwarf::DW_EH_PE_signed, llvm::dwarf::DW_EH_PE_udata2, llvm::dwarf::DW_EH_PE_udata4, llvm::dwarf::DW_EH_PE_udata8, llvm::format(), llvm::MCContext::getAsmInfo(), llvm::MCStreamer::getContext(), llvm::MCAsmInfo::getPointerSize(), and llvm_unreachable.
Referenced by emitFDESymbol(), and EmitPersonality().
MakeStartMinusEndExpr()
const MCExpr * MakeStartMinusEndExpr (const MCStreamer & MCOS, const MCSymbol & Start, const MCSymbol & End, int IntVal) inline static
Definition at line 95 of file MCDwarf.cpp.
References llvm::MCBinaryExpr::Create(), llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCStreamer::getContext(), llvm::MCBinaryExpr::Sub, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MCDwarfLineTableHeader::Emit(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), and EmitGenDwarfRanges().
ScaleAddrDelta()
uint64_t ScaleAddrDelta (MCContext & Context, uint64_t AddrDelta) inline static
Definition at line 51 of file MCDwarf.cpp.
References llvm::MCContext::getAsmInfo(), and llvm::MCAsmInfo::getMinInstAlignment().
Referenced by llvm::MCDwarfLineAddr::Encode(), and llvm::MCDwarfFrameEmitter::EncodeAdvanceLoc().