LLVM: MCSymbol.cpp File Reference
LLVM API Documentation
MCSymbol.cpp File Reference
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Functions
static bool isAcceptableChar (char C)
static bool NameNeedsQuoting (StringRef Str)
Function Documentation
isAcceptableChar()
bool isAcceptableChar (char C) static
Definition at line 20 of file MCSymbol.cpp.
Referenced by NameNeedsQuoting().
NameNeedsQuoting()
bool NameNeedsQuoting (StringRef Str) static
NameNeedsQuoting - Return true if the identifier Str needs quotes to be syntactically correct.
Definition at line 31 of file MCSymbol.cpp.
References llvm::StringRef::empty(), isAcceptableChar(), and llvm::StringRef::size().
Referenced by llvm::MCSymbol::print().