LLVM: MCTargetOptionsCommandFlags.h File Reference
LLVM API Documentation
MCTargetOptionsCommandFlags.h File Reference
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/Support/CommandLine.h"
Functions
cl::opt< MCTargetOptions::AsmInstrumentation > AsmInstrumentation ("asm-instrumentation", cl::desc("Instrumentation of inline assembly and " "assembly source files"), cl::init(MCTargetOptions::AsmInstrumentationNone), cl::values(clEnumValN(MCTargetOptions::AsmInstrumentationNone, "none", "no instrumentation at all"), clEnumValN(MCTargetOptions::AsmInstrumentationAddress, "address", "instrument instructions with memory arguments"), clEnumValEnd))
cl::opt< bool > RelaxAll ("mc-relax-all", cl::desc("When used with filetype=obj, " "relax all fixups in the emitted object file"))
cl::opt< int > DwarfVersion ("dwarf-version", cl::desc("Dwarf version"), cl::init(0))
cl::opt< bool > ShowMCInst ("asm-show-inst", cl::desc("Emit internal instruction representation to " "assembly file"))
cl::opt< std::string > ABIName ("target-abi", cl::Hidden, cl::desc("The name of the ABI to be targeted from the backend."), cl::init(""))
static MCTargetOptions InitMCTargetOptionsFromFlags ()
Function Documentation
ABIName()
cl::opt< std::string > ABIName ("target-abi" , cl::Hidden , cl::desc("The name of the ABI to be targeted from the backend.") , cl::init(""))
References llvm::cl::Hidden, and llvm::cl::init().
Referenced by InitMCTargetOptionsFromFlags(), and llvm::operator==().
AsmInstrumentation()
cl::opt< MCTargetOptions::AsmInstrumentation > AsmInstrumentation ("asm-instrumentation" , cl::desc("Instrumentation of inline assembly and " "assembly source files") , cl::init(MCTargetOptions::AsmInstrumentationNone) , cl::values(clEnumValN(MCTargetOptions::AsmInstrumentationNone, "none", "no instrumentation at all"), clEnumValN(MCTargetOptions::AsmInstrumentationAddress, "address", "instrument instructions with memory arguments"), clEnumValEnd))
References llvm::MCTargetOptions::AsmInstrumentationAddress, llvm::MCTargetOptions::AsmInstrumentationNone, clEnumValEnd, llvm::cl::init(), and llvm::cl::values().
Referenced by InitMCTargetOptionsFromFlags().
DwarfVersion()
cl::opt< int > DwarfVersion ("dwarf-version" , cl::desc("Dwarf version") , cl::init(0))
References llvm::cl::init().
Referenced by llvm::DIELoc::BestForm(), InitMCTargetOptionsFromFlags(), and llvm::operator==().
InitMCTargetOptionsFromFlags()
MCTargetOptions InitMCTargetOptionsFromFlags () inline static
Definition at line 48 of file MCTargetOptionsCommandFlags.h.
References ABIName(), llvm::MCTargetOptions::ABIName, AsmInstrumentation(), llvm::MCTargetOptions::AsmInstrumentationAddress, DwarfVersion(), llvm::MCTargetOptions::DwarfVersion, llvm::MCTargetOptions::MCRelaxAll, RelaxAll(), llvm::MCTargetOptions::SanitizeAddress, llvm::MCTargetOptions::ShowMCInst, and ShowMCInst().
Referenced by InitTargetOptionsFromCodeGenFlags().
RelaxAll()
cl::opt< bool > RelaxAll ("mc-relax-all" , cl::desc("When used with filetype=obj, " "relax all fixups in the emitted object file"))
Referenced by llvm::createAArch64ELFStreamer(), llvm::createARMELFStreamer(), llvm::createELFStreamer(), createHexagonELFStreamer(), llvm::createMachOStreamer(), llvm::Target::createMCObjectStreamer(), createMCStreamer(), createMCStreamer(), createMCStreamer(), createMCStreamer(), createMCStreamer(), createMCStreamer(), createMCStreamer(), createMCStreamer(), llvm::createMipsELFStreamer(), llvm::createMipsNaClELFStreamer(), createSystemZMCObjectStreamer(), llvm::createX86WinCOFFStreamer(), and InitMCTargetOptionsFromFlags().
ShowMCInst()
cl::opt< bool > ShowMCInst ("asm-show-inst" , cl::desc("Emit internal instruction representation to " "assembly file"))
Referenced by InitMCTargetOptionsFromFlags(), and llvm::operator==().