LLVM: Metadata.cpp File Reference
LLVM API Documentation
Metadata.cpp File Reference
#include "llvm/IR/Metadata.h"
#include "LLVMContextImpl.h"
#include "SymbolTableListTraitsImpl.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/IR/Metadata.def"
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define HANDLE_METADATA_LEAF(CLASS)
#define HANDLE_UNIQUABLE_LEAF(CLASS)
#define HANDLE_UNIQUABLE_LEAF(CLASS)
#define HANDLE_UNIQUABLE_LEAF(CLASS)
Functions
static Metadata * canonicalizeMetadataForValue (LLVMContext &Context, Metadata *MD)
Canonicalize metadata arguments to intrinsics.
static Function * getLocalFunction (Value *V)
static bool isOperandUnresolved (Metadata *Op)
static const Metadata * llvm::get_hashable_data (const MDOperand &X)
Make MDOperand transparent for hashing.
static void adjustLine (unsigned &Line)
static void adjustColumn (unsigned &Column)
static MDNode * getOrSelfReference (LLVMContext &Context, ArrayRef< Metadata * > Ops)
Get a node, or a self-reference that looks like it.
static bool isContiguous (const ConstantRange &A, const ConstantRange &B)
static bool canBeMerged (const ConstantRange &A, const ConstantRange &B)
static bool tryMergeRange (SmallVectorImpl< ConstantInt * > &EndPoints, ConstantInt *Low, ConstantInt *High)
static void addRange (SmallVectorImpl< ConstantInt * > &EndPoints, ConstantInt *Low, ConstantInt *High)
static SmallVector< TrackingMDRef, 4 > & getNMDOps (void *Operands)
Macro Definition Documentation
HANDLE_METADATA_LEAF
#define HANDLE_METADATA_LEAF (CLASS)
Value:
  case Metadata::CLASS##Kind:                                                  \
    cast<CLASS>(OwnerMD)->handleChangedOperand(Pair.first, MD);                \
    continue;
HANDLE_UNIQUABLE_LEAF [1/3]
#define HANDLE_UNIQUABLE_LEAF (CLASS)
Value:
  case CLASS##Kind:                                                            \
    delete cast<CLASS>(this);                                                  \
    break;
HANDLE_UNIQUABLE_LEAF [2/3]
#define HANDLE_UNIQUABLE_LEAF (CLASS)
Value:
  case CLASS##Kind:                                                            \
    return cast<CLASS>(this)->uniquifyImpl();
HANDLE_UNIQUABLE_LEAF [3/3]
#define HANDLE_UNIQUABLE_LEAF (CLASS)
Value:
  case CLASS##Kind:                                                            \
    cast<CLASS>(this)->eraseFromStoreImpl();                                   \
    break;
Function Documentation
addRange()
void addRange (SmallVectorImpl< ConstantInt * > & EndPoints, ConstantInt * Low, ConstantInt * High) static
Definition at line 889 of file Metadata.cpp.
References llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and tryMergeRange().
Referenced by llvm::MDNode::getMostGenericRange().
adjustColumn()
void adjustColumn (unsigned & Column) static
Definition at line 678 of file Metadata.cpp.
Referenced by llvm::MDLocation::getDistinct().
adjustLine()
void adjustLine (unsigned & Line) static
Definition at line 672 of file Metadata.cpp.
Referenced by llvm::MDLocation::getDistinct().
canBeMerged()
bool canBeMerged (const ConstantRange & A, const ConstantRange & B) static
Definition at line 866 of file Metadata.cpp.
References isContiguous().
Referenced by tryMergeRange().
canonicalizeMetadataForValue()
Metadata * canonicalizeMetadataForValue (LLVMContext & Context, Metadata * MD) static
Canonicalize metadata arguments to intrinsics.
To support bitcode upgrades (and assembly semantic sugar) for MetadataAsValue, we need to canonicalize certain metadata.
nullptr is replaced by an empty MDNode.
An MDNode with a single null operand is replaced by an empty MDNode.
An MDNode whose only operand is a ConstantAsMetadata gets skipped.
This maintains readability of bitcode from when metadata was a type of value, and these bridges were unnecessary.
Definition at line 51 of file Metadata.cpp.
References llvm::dyn_cast(), llvm::MDNode::get(), N, and llvm::None.
Referenced by llvm::MetadataAsValue::get(), and llvm::MetadataAsValue::getIfExists().
getLocalFunction()
Function * getLocalFunction (Value * V) static
Definition at line 240 of file Metadata.cpp.
References llvm::cast(), llvm::dyn_cast(), and getParent().
Referenced by llvm::ValueAsMetadata::handleRAUW().
getNMDOps()
SmallVector< TrackingMDRef, 4 > & getNMDOps (void * Operands) static
Definition at line 975 of file Metadata.cpp.
References Operands.
Referenced by llvm::NamedMDNode::addOperand(), llvm::NamedMDNode::dropAllReferences(), llvm::NamedMDNode::getNumOperands(), llvm::NamedMDNode::getOperand(), llvm::NamedMDNode::setOperand(), and llvm::NamedMDNode::~NamedMDNode().
getOrSelfReference()
MDNode * getOrSelfReference (LLVMContext & Context, ArrayRef< Metadata * > Ops) static
Get a node, or a self-reference that looks like it.
Special handling for finding self-references, for use by MDNode::concatenate() and MDNode::intersect() to maintain behaviour from when self-referencing nodes were still uniqued. If the first operand has the same operands as Ops, return the first operand instead.
Definition at line 777 of file Metadata.cpp.
References llvm::dyn_cast_or_null(), llvm::ArrayRef< T >::empty(), llvm::MDNode::get(), I, N, and llvm::ArrayRef< T >::size().
Referenced by llvm::MDNode::concatenate(), llvm::MDNode::getMostGenericAliasScope(), and llvm::MDNode::intersect().
isContiguous()
bool isContiguous (const ConstantRange & A, const ConstantRange & B) static
Definition at line 862 of file Metadata.cpp.
References llvm::ConstantRange::getLower(), and llvm::ConstantRange::getUpper().
Referenced by canBeMerged().
isOperandUnresolved()
bool isOperandUnresolved (Metadata * Op) static
Definition at line 411 of file Metadata.cpp.
References llvm::dyn_cast_or_null(), and N.
Referenced by llvm::UniquableMDNode::UniquableMDNode().
tryMergeRange()
bool tryMergeRange (SmallVectorImpl< ConstantInt * > & EndPoints, ConstantInt * Low, ConstantInt * High) static
Definition at line 870 of file Metadata.cpp.
References canBeMerged(), llvm::cast(), llvm::ConstantInt::get(), llvm::ConstantRange::getLower(), llvm::ConstantInt::getType(), llvm::ConstantRange::getUpper(), llvm::ConstantInt::getValue(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::ConstantRange::unionWith().
Referenced by addRange(), and llvm::MDNode::getMostGenericRange().