LLVM: MipsCCState.cpp File Reference
LLVM API Documentation
MipsCCState.cpp File Reference
#include "MipsCCState.h"
#include "MipsSubtarget.h"
#include "llvm/IR/Module.h"
Functions
static bool isF128SoftLibCall (const char *CallSym)
This function returns true if CallSym is a long double emulation routine.
static bool originalTypeIsF128 (const Type *Ty, const SDNode *CallNode)
Function Documentation
isF128SoftLibCall()
bool isF128SoftLibCall (const char * CallSym) static
This function returns true if CallSym is a long double emulation routine.
Definition at line 17 of file MipsCCState.cpp.
References llvm::array_lengthof(), and I.
Referenced by originalTypeIsF128().
originalTypeIsF128()
bool originalTypeIsF128 (const Type * Ty, const SDNode * CallNode) static
This function returns true if Ty is fp128, {f128} or i128 which was originally a fp128.
Definition at line 47 of file MipsCCState.cpp.
References llvm::dyn_cast_or_null(), llvm::Type::getStructElementType(), llvm::Type::getStructNumElements(), llvm::ExternalSymbolSDNode::getSymbol(), isF128SoftLibCall(), llvm::Type::isFP128Ty(), llvm::Type::isIntegerTy(), and llvm::Type::isStructTy().