LLVM: MipsMCCodeEmitter.cpp File Reference
LLVM API Documentation
MipsMCCodeEmitter.cpp File Reference
#include "MipsMCCodeEmitter.h"
#include "MCTargetDesc/MipsFixupKinds.h"
#include "MCTargetDesc/MipsMCExpr.h"
#include "MCTargetDesc/MipsMCTargetDesc.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/raw_ostream.h"
#include "MipsGenInstrInfo.inc"
#include "MipsGenMCCodeEmitter.inc"
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "mccodeemitter"
#define GET_INSTRMAP_INFO
Functions
MCCodeEmitter * llvm::createMipsMCCodeEmitterEB (const MCInstrInfo &MCII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI, MCContext &Ctx)
MCCodeEmitter * llvm::createMipsMCCodeEmitterEL (const MCInstrInfo &MCII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI, MCContext &Ctx)
static void LowerLargeShift (MCInst &Inst)
static void LowerDextDins (MCInst &InstIn)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mccodeemitter"
Definition at line 29 of file MipsMCCodeEmitter.cpp.
GET_INSTRMAP_INFO
#define GET_INSTRMAP_INFO
Definition at line 31 of file MipsMCCodeEmitter.cpp.
Function Documentation
LowerDextDins()
void LowerDextDins (MCInst & InstIn) static
Definition at line 86 of file MipsMCCodeEmitter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), llvm::MCOperand::setImm(), and llvm::MCInst::setOpcode().
LowerLargeShift()
void LowerLargeShift (MCInst & Inst) static
Definition at line 53 of file MipsMCCodeEmitter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), llvm_unreachable, llvm::MCOperand::setImm(), and llvm::MCInst::setOpcode().