LLVM: MipsSubtarget.cpp File Reference
LLVM API Documentation
MipsSubtarget.cpp File Reference
#include "MipsMachineFunction.h"
#include "Mips.h"
#include "MipsRegisterInfo.h"
#include "MipsSubtarget.h"
#include "MipsTargetMachine.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "MipsGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "mips-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Functions
static StringRef selectMipsCPU (Triple TT, StringRef CPU)
static std::string computeDataLayout (const MipsSubtarget &ST)
Variables
static cl::opt< bool > Mixed16_32 ("mips-mixed-16-32", cl::init(false), cl::desc("Allow for a mixture of Mips16 " "and Mips32 code in a single source file"), cl::Hidden)
static cl::opt< bool > Mips_Os16 ("mips-os16", cl::init(false), cl::desc("Compile all functions that don' use " "floating point as Mips 16"), cl::Hidden)
static cl::opt< bool > Mips16HardFloat ("mips16-hard-float", cl::NotHidden, cl::desc("MIPS: mips16 hard float enable."), cl::init(false))
static cl::opt< bool > Mips16ConstantIslands ("mips16-constant-islands", cl::NotHidden, cl::desc("MIPS: mips16 constant islands enable."), cl::init(true))
static cl::opt< bool > GPOpt ("mgpopt", cl::Hidden, cl::desc("MIPS: Enable gp-relative addressing of small data items"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-subtarget"
Definition at line 28 of file MipsSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 31 of file MipsSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 30 of file MipsSubtarget.cpp.
Function Documentation
computeDataLayout()
std::string computeDataLayout (const MipsSubtarget & ST) static
Definition at line 79 of file MipsSubtarget.cpp.
selectMipsCPU()
StringRef selectMipsCPU (Triple TT, StringRef CPU) static
Select the Mips CPU for the given triple and cpu name. FIXME: Merge with the copy in MipsMCTargetDesc.cpp
Definition at line 67 of file MipsSubtarget.cpp.
References llvm::StringRef::empty(), llvm::Triple::getArch(), llvm::Triple::mips, and llvm::Triple::mipsel.
Variable Documentation
GPOpt
cl::opt< bool > GPOpt("mgpopt", cl::Hidden, cl::desc("MIPS: Enable gp-relative addressing of small data items")) ("mgpopt" , cl::Hidden , cl::desc("MIPS: Enable gp-relative addressing of small data items")) static
Referenced by llvm::MipsSubtarget::MipsSubtarget().
Mips16ConstantIslands
cl::opt< bool > Mips16ConstantIslands("mips16-constant-islands", cl::NotHidden, cl::desc("MIPS: mips16 constant islands enable."), cl::init(true)) ("mips16-constant-islands" , cl::NotHidden , cl::desc("MIPS: mips16 constant islands enable.") , cl::init(true)) static
Referenced by llvm::MipsSubtarget::useConstantIslands().
Mips16HardFloat
cl::opt< bool > Mips16HardFloat("mips16-hard-float", cl::NotHidden, cl::desc("MIPS: mips16 hard float enable."), cl::init(false)) ("mips16-hard-float" , cl::NotHidden , cl::desc("MIPS: mips16 hard float enable.") , cl::init(false)) static
Referenced by llvm::createMips16HardFloat().
Mips_Os16
cl::opt< bool > Mips_Os16("mips-os16", cl::init(false), cl::desc("Compile all functions that don' use " "floating point as Mips 16"), cl::Hidden) ("mips-os16" , cl::init(false) , cl::desc("Compile all functions that don' use " "floating point as Mips 16") , cl::Hidden) static
Referenced by llvm::MipsSubtarget::MipsSubtarget().
Mixed16_32
cl::opt< bool > Mixed16_32("mips-mixed-16-32", cl::init(false), cl::desc("Allow for a mixture of Mips16 " "and Mips32 code in a single source file"), cl::Hidden) ("mips-mixed-16-32" , cl::init(false) , cl::desc("Allow for a mixture of Mips16 " "and Mips32 code in a single source file") , cl::Hidden) static
Referenced by llvm::MipsSubtarget::MipsSubtarget().