LLVM: Mips16InstrInfo.cpp File Reference
LLVM API Documentation
Mips16InstrInfo.cpp File Reference
#include "Mips16InstrInfo.h"
#include "InstPrinter/MipsInstPrinter.h"
#include "MipsMachineFunction.h"
#include "MipsTargetMachine.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include <cctype>
Macros
#define DEBUG_TYPE "mips16-instrinfo"
Functions
static void addSaveRestoreRegs (MachineInstrBuilder &MIB, const std::vector< CalleeSavedInfo > &CSI, unsigned Flags=0)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips16-instrinfo"
Definition at line 32 of file Mips16InstrInfo.cpp.
Function Documentation
addSaveRestoreRegs()
void addSaveRestoreRegs (MachineInstrBuilder & MIB, const std::vector< CalleeSavedInfo > & CSI, unsigned Flags = 0) static
Definition at line 171 of file Mips16InstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), and llvm_unreachable.
Referenced by llvm::Mips16InstrInfo::makeFrame(), and llvm::Mips16InstrInfo::restoreFrame().