LLVM: MipsLongBranch.cpp File Reference
LLVM API Documentation
MipsLongBranch.cpp File Reference
#include "Mips.h"
#include "MCTargetDesc/MipsBaseInfo.h"
#include "MCTargetDesc/MipsMCNaCl.h"
#include "MipsMachineFunction.h"
#include "MipsTargetMachine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "mips-long-branch"
Functions
STATISTIC (LongBranches, "Number of long branches.")
static MachineBasicBlock * getTargetMBB (const MachineInstr &Br)
static ReverseIter getNonDebugInstr (ReverseIter B, ReverseIter E)
static void emitGPDisp (MachineFunction &F, const MipsInstrInfo *TII)
Variables
static cl::opt< bool > SkipLongBranch ("skip-mips-long-branch", cl::init(false), cl::desc("MIPS: Skip long branch pass."), cl::Hidden)
static cl::opt< bool > ForceLongBranch ("force-mips-long-branch", cl::init(false), cl::desc("MIPS: Expand all branches to long format."), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-long-branch"
Definition at line 33 of file MipsLongBranch.cpp.
Function Documentation
emitGPDisp()
void emitGPDisp (MachineFunction & F, const MipsInstrInfo * TII) static
Definition at line 443 of file MipsLongBranch.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), F, llvm::MachineBasicBlock::findDebugLoc(), I, llvm::MipsII::MO_ABS_HI, llvm::MipsII::MO_ABS_LO, llvm::MachineBasicBlock::removeLiveIn(), and TII.
getNonDebugInstr()
ReverseIter getNonDebugInstr (ReverseIter B, ReverseIter E) static
Definition at line 118 of file MipsLongBranch.cpp.
getTargetMBB()
MachineBasicBlock * getTargetMBB (const MachineInstr & Br) static
Iterate over list of Br's operands and search for a MachineBasicBlock operand.
Definition at line 105 of file MipsLongBranch.cpp.
References llvm::MachineInstr::getDesc(), llvm::MachineOperand::getMBB(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOperand(), I, llvm::MachineOperand::isMBB(), and llvm_unreachable.
STATISTIC()
STATISTIC (LongBranches , "Number of long branches.")
Variable Documentation
ForceLongBranch
cl::opt< bool > ForceLongBranch("force-mips-long-branch", cl::init(false), cl::desc("MIPS: Expand all branches to long format."), cl::Hidden) ("force-mips-long-branch" , cl::init(false) , cl::desc("MIPS: Expand all branches to long format.") , cl::Hidden) static
SkipLongBranch
cl::opt< bool > SkipLongBranch("skip-mips-long-branch", cl::init(false), cl::desc("MIPS: Skip long branch pass."), cl::Hidden) ("skip-mips-long-branch" , cl::init(false) , cl::desc("MIPS: Skip long branch pass.") , cl::Hidden) static