LLVM: MipsDisassembler.cpp File Reference
LLVM API Documentation
MipsDisassembler.cpp File Reference
#include "Mips.h"
#include "MipsRegisterInfo.h"
#include "MipsSubtarget.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDisassembler.h"
#include "llvm/MC/MCFixedLenDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TargetRegistry.h"
#include "MipsGenDisassemblerTables.inc"
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "mips-disassembler"
Functions
static DecodeStatus DecodeGPR64RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCPU16RegsRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRMM16RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPRMM16ZeroRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeGPR32RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodePtrRegisterClass (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDSPRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFGR64RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFGR32RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCCRRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFCCRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFGRCCRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeHWRegsRegisterClass (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAFGR64RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeACC64DSPRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeHI32DSPRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLO32DSPRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMSA128BRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMSA128HRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMSA128WRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMSA128DRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMSACtrlRegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCOP2RegisterClass (MCInst &Inst, unsigned RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeBranchTarget (MCInst &Inst, unsigned Offset, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeJumpTarget (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeBranchTarget21 (MCInst &Inst, unsigned Offset, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeBranchTarget26 (MCInst &Inst, unsigned Offset, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeBranchTarget7MM (MCInst &Inst, unsigned Offset, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeBranchTargetMM (MCInst &Inst, unsigned Offset, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeJumpTargetMM (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMem (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCacheOp (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCacheOpR6 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeCacheOpMM (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSyncI (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMSA128Mem (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMemMMImm4 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMemMMSPImm5Lsl2 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMemMMImm12 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeMemMMImm16 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFMem (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFMem2 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFMem3 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeFMemCop2R6 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSpecial3LlSc (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeAddiur2Simm7 (MCInst &Inst, unsigned Value, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeUImm6Lsl2 (MCInst &Inst, unsigned Value, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLiSimm7 (MCInst &Inst, unsigned Value, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSimm4 (MCInst &Inst, unsigned Value, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSimm16 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeLSAImm (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeInsSize (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeExtSize (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSimm19Lsl2 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSimm18Lsl3 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeSimm9SP (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeANDI16Imm (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeUImm5lsl2 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
template<typename InsnType>
static DecodeStatus DecodeINSVE_DF (MCInst &MI, InsnType insn, uint64_t Address, const void *Decoder)
template<typename InsnType>
static DecodeStatus DecodeAddiGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const void *Decoder)
template<typename InsnType>
static DecodeStatus DecodeDaddiGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const void *Decoder)
template<typename InsnType>
static DecodeStatus DecodeBlezlGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const void *Decoder)
template<typename InsnType>
static DecodeStatus DecodeBgtzlGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const void *Decoder)
template<typename InsnType>
static DecodeStatus DecodeBgtzGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const void *Decoder)
template<typename InsnType>
static DecodeStatus DecodeBlezGroupBranch (MCInst &MI, InsnType insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRegListOperand (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeRegListOperand16 (MCInst &Inst, unsigned Insn, uint64_t Address, const void *Decoder)
static MCDisassembler * createMipsDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
static MCDisassembler * createMipselDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
static MCDisassembler * createMips64Disassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
static MCDisassembler * createMips64elDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
void LLVMInitializeMipsDisassembler ()
static unsigned getReg (const void *D, unsigned RC, unsigned RegNo)
static DecodeStatus readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn, bool IsBigEndian)
static DecodeStatus readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t &Size, uint32_t &Insn, bool IsBigEndian, bool IsMicroMips)
Variables
Target llvm::TheMipselTarget
Target llvm::TheMipsTarget
Target llvm::TheMips64Target
Target llvm::TheMips64elTarget
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips-disassembler"
Definition at line 27 of file MipsDisassembler.cpp.
Function Documentation
createMips64Disassembler()
MCDisassembler * createMips64Disassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 441 of file MipsDisassembler.cpp.
References T.
Referenced by LLVMInitializeMipsDisassembler().
createMips64elDisassembler()
MCDisassembler * createMips64elDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 448 of file MipsDisassembler.cpp.
References T.
Referenced by LLVMInitializeMipsDisassembler().
createMipsDisassembler()
MCDisassembler * createMipsDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 427 of file MipsDisassembler.cpp.
References T.
Referenced by LLVMInitializeMipsDisassembler().
createMipselDisassembler()
MCDisassembler * createMipselDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 434 of file MipsDisassembler.cpp.
References T.
Referenced by LLVMInitializeMipsDisassembler().
DecodeACC64DSPRegisterClass()
DecodeStatus DecodeACC64DSPRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1446 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeAddiGroupBranch()
template<typename InsnType> DecodeStatus DecodeAddiGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const void * Decoder) static
Definition at line 522 of file MipsDisassembler.cpp.
References llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeAddiur2Simm7()
DecodeStatus DecodeAddiur2Simm7 (MCInst & Inst, unsigned Value, uint64_t Address, const void * Decoder) static
Definition at line 1620 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), and llvm::MCDisassembler::Success.
DecodeAFGR64RegisterClass()
DecodeStatus DecodeAFGR64RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1433 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeANDI16Imm()
DecodeStatus DecodeANDI16Imm (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1723 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), and llvm::MCDisassembler::Success.
DecodeBgtzGroupBranch()
template<typename InsnType> DecodeStatus DecodeBgtzGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const void * Decoder) static
Definition at line 687 of file MipsDisassembler.cpp.
References llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeBgtzlGroupBranch()
template<typename InsnType> DecodeStatus DecodeBgtzlGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const void * Decoder) static
Definition at line 643 of file MipsDisassembler.cpp.
References llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeBlezGroupBranch()
template<typename InsnType> DecodeStatus DecodeBlezGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const void * Decoder) static
Definition at line 736 of file MipsDisassembler.cpp.
References llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeBlezlGroupBranch()
template<typename InsnType> DecodeStatus DecodeBlezlGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const void * Decoder) static
Definition at line 600 of file MipsDisassembler.cpp.
References llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeBranchTarget()
DecodeStatus DecodeBranchTarget (MCInst & Inst, unsigned Offset, uint64_t Address, const void * Decoder) static
Definition at line 1554 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeBranchTarget21()
DecodeStatus DecodeBranchTarget21 (MCInst & Inst, unsigned Offset, uint64_t Address, const void * Decoder) static
Definition at line 1573 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeBranchTarget26()
DecodeStatus DecodeBranchTarget26 (MCInst & Inst, unsigned Offset, uint64_t Address, const void * Decoder) static
Definition at line 1583 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeBranchTarget7MM()
DecodeStatus DecodeBranchTarget7MM (MCInst & Inst, unsigned Offset, uint64_t Address, const void * Decoder) static
Definition at line 1593 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeBranchTargetMM()
DecodeStatus DecodeBranchTargetMM (MCInst & Inst, unsigned Offset, uint64_t Address, const void * Decoder) static
Definition at line 1602 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeCacheOp()
DecodeStatus DecodeCacheOp (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1096 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), Hint(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeCacheOpMM()
DecodeStatus DecodeCacheOpMM (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1113 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), Hint(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeCacheOpR6()
DecodeStatus DecodeCacheOpR6 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1130 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), Hint(), and llvm::MCDisassembler::Success.
DecodeCCRRegisterClass()
DecodeStatus DecodeCCRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1040 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeCOP2RegisterClass()
DecodeStatus DecodeCOP2RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1542 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeCPU16RegsRegisterClass()
DecodeStatus DecodeCPU16RegsRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 944 of file MipsDisassembler.cpp.
References llvm::MCDisassembler::Fail.
DecodeDaddiGroupBranch()
template<typename InsnType> DecodeStatus DecodeDaddiGroupBranch (MCInst & MI, InsnType insn, uint64_t Address, const void * Decoder) static
Definition at line 561 of file MipsDisassembler.cpp.
References llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeDSPRRegisterClass()
DecodeStatus DecodeDSPRRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1009 of file MipsDisassembler.cpp.
References DecodeGPR32RegisterClass().
DecodeExtSize()
DecodeStatus DecodeExtSize (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1688 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeFCCRegisterClass()
DecodeStatus DecodeFCCRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1051 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeFGR32RegisterClass()
DecodeStatus DecodeFGR32RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1028 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeFGR64RegisterClass()
DecodeStatus DecodeFGR64RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1016 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeFGRCCRegisterClass()
DecodeStatus DecodeFGRCCRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1062 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeFMem()
DecodeStatus DecodeFMem (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1329 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeFMem2()
DecodeStatus DecodeFMem2 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1347 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeFMem3()
DecodeStatus DecodeFMem3 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1365 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeFMemCop2R6()
DecodeStatus DecodeFMemCop2R6 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1383 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeGPR32RegisterClass()
DecodeStatus DecodeGPR32RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 988 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeGPR64RegisterClass()
DecodeStatus DecodeGPR64RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 953 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeGPRMM16RegisterClass()
DecodeStatus DecodeGPRMM16RegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 966 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeMemMMImm4().
DecodeGPRMM16ZeroRegisterClass()
DecodeStatus DecodeGPRMM16ZeroRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 977 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeMemMMImm4().
DecodeHI32DSPRegisterClass()
DecodeStatus DecodeHI32DSPRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1458 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeHWRegsRegisterClass()
DecodeStatus DecodeHWRegsRegisterClass (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1422 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeInsSize()
DecodeStatus DecodeInsSize (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1677 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeINSVE_DF()
template<typename InsnType> DecodeStatus DecodeINSVE_DF (MCInst & MI, InsnType insn, uint64_t Address, const void * Decoder) static
INSVE_[BHWD] have an implicit operand that the generated decoder doesn't handle.
Definition at line 476 of file MipsDisassembler.cpp.
References llvm::MCOperand::CreateImm(), DecodeMSA128BRegisterClass(), DecodeMSA128DRegisterClass(), DecodeMSA128HRegisterClass(), DecodeMSA128WRegisterClass(), llvm::MCDisassembler::Fail, llvm_unreachable, and llvm::MCDisassembler::Success.
DecodeJumpTarget()
DecodeStatus DecodeJumpTarget (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1563 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), and llvm::MCDisassembler::Success.
DecodeJumpTargetMM()
DecodeStatus DecodeJumpTargetMM (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1611 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), and llvm::MCDisassembler::Success.
DecodeLiSimm7()
DecodeStatus DecodeLiSimm7 (MCInst & Inst, unsigned Value, uint64_t Address, const void * Decoder) static
Definition at line 1641 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), and llvm::MCDisassembler::Success.
DecodeLO32DSPRegisterClass()
DecodeStatus DecodeLO32DSPRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1470 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodeLSAImm()
DecodeStatus DecodeLSAImm (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1668 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), and llvm::MCDisassembler::Success.
DecodeMem()
DecodeStatus DecodeMem (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1073 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MCInst::getOpcode(), getReg(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
Referenced by DecodeLoadDFP(), DecodeLoadFP(), DecodeLoadInt(), DecodeLoadQFP(), DecodeStoreDFP(), DecodeStoreFP(), DecodeStoreInt(), and DecodeStoreQFP().
DecodeMemMMImm12()
DecodeStatus DecodeMemMMImm12 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1276 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), DecodeRegListOperand(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), getReg(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeMemMMImm16()
DecodeStatus DecodeMemMMImm16 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1311 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeMemMMImm4()
DecodeStatus DecodeMemMMImm4 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1208 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), DecodeGPRMM16RegisterClass(), DecodeGPRMM16ZeroRegisterClass(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), and llvm::MCDisassembler::Success.
DecodeMemMMSPImm5Lsl2()
DecodeStatus DecodeMemMMSPImm5Lsl2 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1260 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), and llvm::MCDisassembler::Success.
DecodeMSA128BRegisterClass()
DecodeStatus DecodeMSA128BRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1482 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeINSVE_DF().
DecodeMSA128DRegisterClass()
DecodeStatus DecodeMSA128DRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1518 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeINSVE_DF().
DecodeMSA128HRegisterClass()
DecodeStatus DecodeMSA128HRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1494 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeINSVE_DF().
DecodeMSA128Mem()
DecodeStatus DecodeMSA128Mem (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1162 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, llvm::MCInst::getOpcode(), getReg(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeMSA128WRegisterClass()
DecodeStatus DecodeMSA128WRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1506 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
Referenced by DecodeINSVE_DF().
DecodeMSACtrlRegisterClass()
DecodeStatus DecodeMSACtrlRegisterClass (MCInst & Inst, unsigned RegNo, uint64_t Address, const void * Decoder) static
Definition at line 1530 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, getReg(), and llvm::MCDisassembler::Success.
DecodePtrRegisterClass()
DecodeStatus DecodePtrRegisterClass (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 999 of file MipsDisassembler.cpp.
References DecodeGPR32RegisterClass(), and DecodeGPR64RegisterClass().
DecodeRegListOperand()
DecodeStatus DecodeRegListOperand (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1739 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeRegListOperand16()
DecodeStatus DecodeRegListOperand16 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1762 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeSimm16()
DecodeStatus DecodeSimm16 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1660 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeSimm18Lsl3()
DecodeStatus DecodeSimm18Lsl3 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1703 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeSimm19Lsl2()
DecodeStatus DecodeSimm19Lsl2 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1697 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeSimm4()
DecodeStatus DecodeSimm4 (MCInst & Inst, unsigned Value, uint64_t Address, const void * Decoder) static
Definition at line 1652 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeSimm9SP()
DecodeStatus DecodeSimm9SP (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1709 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeSpecial3LlSc()
DecodeStatus DecodeSpecial3LlSc (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1400 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MCInst::getOpcode(), getReg(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeSyncI()
DecodeStatus DecodeSyncI (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1147 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), getReg(), llvm::SignExtend32(), and llvm::MCDisassembler::Success.
DecodeUImm5lsl2()
DecodeStatus DecodeUImm5lsl2 (MCInst & Inst, unsigned Insn, uint64_t Address, const void * Decoder) static
Definition at line 1733 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), and llvm::MCDisassembler::Success.
DecodeUImm6Lsl2()
DecodeStatus DecodeUImm6Lsl2 (MCInst & Inst, unsigned Value, uint64_t Address, const void * Decoder) static
Definition at line 1633 of file MipsDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateImm(), and llvm::MCDisassembler::Success.
getReg()
unsigned getReg (const void * D, unsigned RC, unsigned RegNo) static
Definition at line 469 of file MipsDisassembler.cpp.
References llvm::MCRegisterInfo::getRegClass().
Referenced by AddNodeIDCustom(), llvm::PPCInstrInfo::canInsertSelect(), DecodeACC64DSPRegisterClass(), DecodeAddiGroupBranch(), DecodeAFGR64RegisterClass(), DecodeBgtzGroupBranch(), DecodeBgtzlGroupBranch(), DecodeBlezGroupBranch(), DecodeBlezlGroupBranch(), DecodeCacheOp(), DecodeCacheOpMM(), DecodeCacheOpR6(), DecodeCCRRegisterClass(), DecodeCOP2RegisterClass(), DecodeDaddiGroupBranch(), DecodeFCCRegisterClass(), DecodeFGR32RegisterClass(), DecodeFGR64RegisterClass(), DecodeFGRCCRegisterClass(), DecodeFMem(), DecodeFMem2(), DecodeFMem3(), DecodeFMemCop2R6(), DecodeGPR32RegisterClass(), DecodeGPR64RegisterClass(), DecodeGPRMM16RegisterClass(), DecodeGPRMM16ZeroRegisterClass(), DecodeHI32DSPRegisterClass(), DecodeLO32DSPRegisterClass(), DecodeMem(), DecodeMemMMImm12(), DecodeMemMMImm16(), DecodeMemMMSPImm5Lsl2(), DecodeMSA128BRegisterClass(), DecodeMSA128DRegisterClass(), DecodeMSA128HRegisterClass(), DecodeMSA128Mem(), DecodeMSA128WRegisterClass(), DecodeMSACtrlRegisterClass(), DecodeSpecial3LlSc(), DecodeSyncI(), emitAlignedDPRCS2Restores(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::HexagonInstrInfo::InsertBranch(), llvm::NVPTXInstrInfo::InsertBranch(), llvm::PPCInstrInfo::InsertBranch(), llvm::XCoreInstrInfo::InsertBranch(), llvm::AArch64InstrInfo::insertSelect(), llvm::PPCInstrInfo::insertSelect(), llvm::MachineInstr::isConstantValuePHI(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::ARMBaseInstrInfo::PredicateInstruction(), llvm::PPCInstrInfo::PredicateInstruction(), llvm::R600InstrInfo::PredicateInstruction(), llvm::TargetInstrInfo::PredicateInstruction(), llvm::ARMInstPrinter::printModImmOperand(), llvm::HexagonFrameLowering::restoreCalleeSavedRegisters(), llvm::PPCInstrInfo::ReverseBranchCondition(), llvm::HexagonFrameLowering::spillCalleeSavedRegisters(), and llvm::PPCInstrInfo::SubsumesPredicate().
LLVMInitializeMipsDisassembler()
void LLVMInitializeMipsDisassembler ()
Definition at line 455 of file MipsDisassembler.cpp.
References createMips64Disassembler(), createMips64elDisassembler(), createMipsDisassembler(), createMipselDisassembler(), llvm::TargetRegistry::RegisterMCDisassembler(), llvm::TheMips64elTarget, llvm::TheMips64Target, llvm::TheMipselTarget, and llvm::TheMipsTarget.
readInstruction16()
DecodeStatus readInstruction16 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn, bool IsBigEndian) static
Read two bytes from the ArrayRef and return 16 bit halfword sorted according to the given endianess.
Definition at line 779 of file MipsDisassembler.cpp.
References llvm::MCDisassembler::Fail, llvm::ArrayRef< T >::size(), and llvm::MCDisassembler::Success.
readInstruction32()
DecodeStatus readInstruction32 (ArrayRef< uint8_t > Bytes, uint64_t Address, uint64_t & Size, uint32_t & Insn, bool IsBigEndian, bool IsMicroMips) static
Read four bytes from the ArrayRef and return 32 bit word sorted according to the given endianess
Definition at line 799 of file MipsDisassembler.cpp.
References llvm::MCDisassembler::Fail, llvm::ArrayRef< T >::size(), and llvm::MCDisassembler::Success.