LLVM: ModuleUtils.cpp File Reference
LLVM API Documentation
ModuleUtils.cpp File Reference
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Module.h"
Functions
static void appendToGlobalArray (const char *Array, Module &M, Function *F, int Priority)
Function Documentation
appendToGlobalArray()
void appendToGlobalArray (const char * Array, Module & M, Function * F, int Priority) static
Definition at line 23 of file ModuleUtils.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::cast(), F, llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::FunctionType::get(), llvm::StructType::get(), llvm::Module::getContext(), llvm::SequentialType::getElementType(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::Module::getNamedGlobal(), llvm::Constant::getNullValue(), llvm::StructType::getNumElements(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::IRBuilderBase::getVoidTy(), llvm::makeArrayRef(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::appendToGlobalCtors(), and llvm::appendToGlobalDtors().