LLVM: MSP430MCTargetDesc.cpp File Reference
LLVM API Documentation
MSP430MCTargetDesc.cpp File Reference
#include "MSP430MCTargetDesc.h"
#include "InstPrinter/MSP430InstPrinter.h"
#include "MSP430MCAsmInfo.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/TargetRegistry.h"
#include "MSP430GenInstrInfo.inc"
#include "MSP430GenSubtargetInfo.inc"
#include "MSP430GenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createMSP430MCInstrInfo ()
static MCRegisterInfo * createMSP430MCRegisterInfo (StringRef TT)
static MCSubtargetInfo * createMSP430MCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
static MCCodeGenInfo * createMSP430MCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCInstPrinter * createMSP430MCInstPrinter (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
void LLVMInitializeMSP430TargetMC ()
Macro Definition Documentation
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 25 of file MSP430MCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 31 of file MSP430MCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 28 of file MSP430MCTargetDesc.cpp.
Function Documentation
createMSP430MCCodeGenInfo()
MCCodeGenInfo * createMSP430MCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 53 of file MSP430MCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeMSP430TargetMC().
createMSP430MCInstPrinter()
MCInstPrinter * createMSP430MCInstPrinter (const Target & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) static
Definition at line 61 of file MSP430MCTargetDesc.cpp.
References T.
Referenced by LLVMInitializeMSP430TargetMC().
createMSP430MCInstrInfo()
MCInstrInfo * createMSP430MCInstrInfo () static
Definition at line 34 of file MSP430MCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeMSP430TargetMC().
createMSP430MCRegisterInfo()
MCRegisterInfo * createMSP430MCRegisterInfo (StringRef TT) static
Definition at line 40 of file MSP430MCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeMSP430TargetMC().
createMSP430MCSubtargetInfo()
MCSubtargetInfo * createMSP430MCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS) static
Definition at line 46 of file MSP430MCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeMSP430TargetMC().
LLVMInitializeMSP430TargetMC()
void LLVMInitializeMSP430TargetMC ()
Definition at line 72 of file MSP430MCTargetDesc.cpp.
References createMSP430MCCodeGenInfo(), createMSP430MCInstPrinter(), createMSP430MCInstrInfo(), createMSP430MCRegisterInfo(), createMSP430MCSubtargetInfo(), llvm::TargetRegistry::RegisterMCCodeGenInfo(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TheMSP430Target, and llvm::X.