LLVM: llvm::AttributeFuncs Namespace Reference
LLVM API Documentation
llvm::AttributeFuncs Namespace Reference
Functions
AttributeSet typeIncompatible (Type *Ty, uint64_t Index)
Which attributes cannot be applied to a type.
Function Documentation
typeIncompatible()
AttributeSet llvm::AttributeFuncs::typeIncompatible (Type * Ty, uint64_t Index)
Which attributes cannot be applied to a type.
Definition at line 1241 of file Attributes.cpp.
References llvm::AttrBuilder::addAttribute(), llvm::AttrBuilder::addDereferenceableAttr(), llvm::Attribute::ByVal, llvm::Type::getContext(), llvm::Attribute::InAlloca, llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::Attribute::Nest, llvm::Attribute::NoAlias, llvm::Attribute::NoCapture, llvm::Attribute::NonNull, llvm::Attribute::ReadNone, llvm::Attribute::ReadOnly, llvm::Attribute::SExt, llvm::Attribute::StructRet, and llvm::Attribute::ZExt.