LLVM: llvm::support::endian Namespace Reference
LLVM API Documentation
llvm::support::endian Namespace Reference
Classes
struct Writer
Adapter to write values to a stream in a particular byte order.
Functions
template<typename value_type, endianness endian>
value_type byte_swap (value_type value)
Swap the bytes of value to match the given endianness.
template<typename value_type, endianness endian, std::size_t alignment>
value_type read (const void *memory)
Read a value of a particular endianness from memory.
template<typename value_type, endianness endian, std::size_t alignment>
value_type readNext (const unsigned char *&memory)
template<typename value_type, endianness endian, std::size_t alignment>
void write (void *memory, value_type value)
Write a value to memory with a particular endianness.
Function Documentation
byte_swap()
template<typename value_type, endianness endian> value_type llvm::support::endian::byte_swap (value_type value) inline
Swap the bytes of value to match the given endianness.
Definition at line 39 of file Endian.h.
References llvm::support::big, llvm::sys::IsBigEndianHost, llvm::support::native, and llvm::sys::swapByteOrder().
Referenced by read(), write(), and llvm::support::endian::Writer< endian >::write().
read()
template<typename value_type, endianness endian, std::size_t alignment> value_type llvm::support::endian::read (const void * memory) inline
Read a value of a particular endianness from memory.
Definition at line 49 of file Endian.h.
References byte_swap(), LLVM_ASSUME_ALIGNED, and llvm::support::detail::PickAlignment< T, alignment >::value.
Referenced by llvm::BitstreamCursor::fillCurWord(), llvm::IndexedInstrProf::MD5Hash(), llvm::support::detail::packed_endian_specific_integral< int16_t, little, unaligned >::operator int16_t(), llvm::support::detail::packed_endian_specific_integral< int16_t, little, unaligned >::ref::operator int16_t(), and readNext().
readNext()
template<typename value_type, endianness endian, std::size_t alignment> value_type llvm::support::endian::readNext (const unsigned char *& memory) inline
Read a value of a particular endianness from a buffer, and increment the buffer past that value.
Definition at line 62 of file Endian.h.
References read().
Referenced by llvm::OnDiskChainedHashTable< Info >::Create(), llvm::OnDiskIterableChainedHashTable< InstrProfLookupTrait >::Create(), llvm::OnDiskChainedHashTable< Info >::find(), llvm::OnDiskIterableChainedHashTable< Info >::data_iterator::operator++(), and llvm::OnDiskIterableChainedHashTable< Info >::key_iterator::operator++().
write()
template<typename value_type, endianness endian, std::size_t alignment> void llvm::support::endian::write (void * memory, value_type value) inline
Write a value to memory with a particular endianness.
Definition at line 72 of file Endian.h.
References byte_swap(), LLVM_ASSUME_ALIGNED, and llvm::support::detail::PickAlignment< T, alignment >::value.
Referenced by llvm::StringTableBuilder::finalize(), llvm::support::detail::packed_endian_specific_integral< value_type, endian, alignment >::ref::operator=(), llvm::support::detail::packed_endian_specific_integral< uint16_t, target_endianness, MaximumAlignment< uint16_t, max_alignment >::value >::operator=(), and write_uint32_le().