LLVM: llvm::yaml Namespace Reference
LLVM API Documentation
llvm::yaml Namespace Reference
Classes
class AliasNode
Represents an alias to a Node with an anchor.
class basic_collection_iterator
This is an iterator abstraction over YAML collections shared by both sequences and maps.
class BinaryRef
Specialized YAMLIO scalar type for representing a binary blob.
class Document
A YAML Stream is a sequence of Documents. A document contains a root node.
class document_iterator
Iterator abstraction for Documents over a Stream.
struct DocumentListTraits
struct has_DocumentListTraits
class has_FlowTraits
struct has_FlowTraits< T, true >
struct has_MappingTraits
struct has_MappingValidateTraits
struct has_ScalarBitSetTraits
struct has_ScalarEnumerationTraits
struct has_ScalarTraits
struct has_SequenceMethodTraits
struct has_SequenceTraits
class Input
class IO
class KeyValueNode
A key and value pair. While not technically a Node under the YAML representation graph, it is easier to treat them this way.
class MappingNode
Represents a YAML map created from either a block map for a flow map.
struct MappingNormalization
struct MappingNormalizationHeap
struct MappingTraits
struct MappingTraits< COFF::AuxiliarybfAndefSymbol >
struct MappingTraits< COFF::AuxiliaryCLRToken >
struct MappingTraits< COFF::AuxiliaryFunctionDefinition >
struct MappingTraits< COFF::AuxiliarySectionDefinition >
struct MappingTraits< COFF::AuxiliaryWeakExternal >
struct MappingTraits< COFF::DataDirectory >
struct MappingTraits< COFF::header >
struct MappingTraits< COFFYAML::Object >
struct MappingTraits< COFFYAML::PEHeader >
struct MappingTraits< COFFYAML::Relocation >
struct MappingTraits< COFFYAML::Section >
struct MappingTraits< COFFYAML::Symbol >
struct MappingTraits< ELFYAML::FileHeader >
struct MappingTraits< ELFYAML::LocalGlobalWeakSymbols >
struct MappingTraits< ELFYAML::Object >
struct MappingTraits< ELFYAML::Relocation >
struct MappingTraits< ELFYAML::Symbol >
struct MappingTraits< std::unique_ptr< ELFYAML::Section > >
struct MissingTrait
struct missingTraits
class Node
Abstract base class for all Nodes.
class NullNode
A null value.
class Output
struct SameType
struct ScalarBitSetTraits
struct ScalarBitSetTraits< COFF::Characteristics >
struct ScalarBitSetTraits< COFF::DLLCharacteristics >
struct ScalarBitSetTraits< COFF::SectionCharacteristics >
struct ScalarBitSetTraits< ELFYAML::ELF_EF >
struct ScalarBitSetTraits< ELFYAML::ELF_SHF >
struct ScalarBitSetTraits< ELFYAML::ELF_STO >
struct ScalarEnumerationTraits
struct ScalarEnumerationTraits< COFF::MachineTypes >
struct ScalarEnumerationTraits< COFF::RelocationTypeAMD64 >
struct ScalarEnumerationTraits< COFF::RelocationTypeI386 >
struct ScalarEnumerationTraits< COFF::SymbolBaseType >
struct ScalarEnumerationTraits< COFF::SymbolComplexType >
struct ScalarEnumerationTraits< COFF::SymbolStorageClass >
struct ScalarEnumerationTraits< COFF::WindowsSubsystem >
struct ScalarEnumerationTraits< COFFYAML::AuxSymbolType >
struct ScalarEnumerationTraits< COFFYAML::COMDATType >
struct ScalarEnumerationTraits< COFFYAML::WeakExternalCharacteristics >
struct ScalarEnumerationTraits< ELFYAML::ELF_ELFCLASS >
struct ScalarEnumerationTraits< ELFYAML::ELF_ELFDATA >
struct ScalarEnumerationTraits< ELFYAML::ELF_ELFOSABI >
struct ScalarEnumerationTraits< ELFYAML::ELF_EM >
struct ScalarEnumerationTraits< ELFYAML::ELF_ET >
struct ScalarEnumerationTraits< ELFYAML::ELF_REL >
struct ScalarEnumerationTraits< ELFYAML::ELF_SHT >
struct ScalarEnumerationTraits< ELFYAML::ELF_STT >
struct ScalarEnumerationTraits< ELFYAML::ELF_STV >
class ScalarNode
A scalar node is an opaque datum that can be presented as a series of zero or more Unicode scalar values.
struct ScalarTraits
struct ScalarTraits< BinaryRef >
struct ScalarTraits< bool >
struct ScalarTraits< double >
struct ScalarTraits< float >
struct ScalarTraits< Hex16 >
struct ScalarTraits< Hex32 >
struct ScalarTraits< Hex64 >
struct ScalarTraits< Hex8 >
struct ScalarTraits< int16_t >
struct ScalarTraits< int32_t >
struct ScalarTraits< int64_t >
struct ScalarTraits< int8_t >
struct ScalarTraits< std::string >
struct ScalarTraits< StringRef >
struct ScalarTraits< uint16_t >
struct ScalarTraits< uint32_t >
struct ScalarTraits< uint64_t >
struct ScalarTraits< uint8_t >
class Scanner
Scans YAML tokens from a MemoryBuffer.
class SequenceNode
Represents a YAML sequence created from either a block sequence for a flow sequence.
struct SequenceTraits
class Stream
This class represents a YAML stream potentially containing multiple documents.
struct Token
Token - A single YAML token.
struct unvalidatedMappingTraits
struct validatedMappingTraits
Functions
bool operator== (const BinaryRef &LHS, const BinaryRef &RHS)
bool dumpTokens (StringRef Input, raw_ostream &)
Dump all the tokens in this stream to OS.
bool scanTokens (StringRef Input)
Scans all tokens in input without outputting anything. This is used for benchmarking the tokenizer.
std::string escape (StringRef Input)
Escape Input for a double quoted scalar.
template<class CollectionType>
CollectionType::iterator begin (CollectionType &C)
template<class CollectionType>
void skip (CollectionType &C)
bool isNumber (StringRef S)
bool isNumeric (StringRef S)
bool isNull (StringRef S)
bool isBool (StringRef S)
bool needsQuotes (StringRef S)
template<typename T>
std::enable_if< has_ScalarEnumerationTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T>
std::enable_if< has_ScalarBitSetTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T>
std::enable_if< has_ScalarTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T>
std::enable_if< validatedMappingTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T>
std::enable_if< unvalidatedMappingTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T>
std::enable_if< missingTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T>
std::enable_if< has_SequenceTraits< T >::value, void >::type yamlize (IO &io, T &Seq, bool)
template<typename T>
std::enable_if< has_DocumentListTraits< T >::value, Input & >::type operator>> (Input &yin, T &docList)
template<typename T>
std::enable_if< has_MappingTraits< T >::value, Input & >::type operator>> (Input &yin, T &docMap)
template<typename T>
std::enable_if< has_SequenceTraits< T >::value, Input & >::type operator>> (Input &yin, T &docSeq)
template<typename T>
std::enable_if< missingTraits< T >::value, Input & >::type operator>> (Input &yin, T &docSeq)
template<typename T>
std::enable_if< has_DocumentListTraits< T >::value, Output & >::type operator<< (Output &yout, T &docList)
template<typename T>
std::enable_if< has_MappingTraits< T >::value, Output & >::type operator<< (Output &yout, T &map)
template<typename T>
std::enable_if< has_SequenceTraits< T >::value, Output & >::type operator<< (Output &yout, T &seq)
template<typename T>
std::enable_if< missingTraits< T >::value, Output & >::type operator<< (Output &yout, T &seq)
static void commonSectionMapping (IO &IO, ELFYAML::Section &Section)
static void sectionMapping (IO &IO, ELFYAML::RawContentSection &Section)
static void sectionMapping (IO &IO, ELFYAML::RelocationSection &Section)
Function Documentation
begin()
template<class CollectionType> CollectionType::iterator llvm::yaml::begin (CollectionType & C)
Definition at line 319 of file YAMLParser.h.
Referenced by llvm::yaml::MappingNode::begin(), llvm::yaml::SequenceNode::begin(), and skip().
commonSectionMapping()
void llvm::yaml::commonSectionMapping (IO & IO, ELFYAML::Section & Section) static
Definition at line 491 of file ELFYAML.cpp.
References commonSectionMapping(), llvm::yaml::IO::mapOptional(), and llvm::yaml::IO::mapRequired().
Referenced by commonSectionMapping(), sectionMapping(), and sectionMapping().
dumpTokens()
bool llvm::yaml::dumpTokens (StringRef Input, raw_ostream & OS)
Dump all the tokens in this stream to OS.
Returns
true if there was an error, false otherwise.
Definition at line 547 of file YAMLParser.cpp.
References llvm::yaml::Scanner::getNext(), llvm::yaml::Token::TK_Alias, llvm::yaml::Token::TK_Anchor, llvm::yaml::Token::TK_BlockEnd, llvm::yaml::Token::TK_BlockEntry, llvm::yaml::Token::TK_BlockMappingStart, llvm::yaml::Token::TK_BlockSequenceStart, llvm::yaml::Token::TK_DocumentEnd, llvm::yaml::Token::TK_DocumentStart, llvm::yaml::Token::TK_Error, llvm::yaml::Token::TK_FlowEntry, llvm::yaml::Token::TK_FlowMappingEnd, llvm::yaml::Token::TK_FlowMappingStart, llvm::yaml::Token::TK_FlowSequenceEnd, llvm::yaml::Token::TK_FlowSequenceStart, llvm::yaml::Token::TK_Key, llvm::yaml::Token::TK_Scalar, llvm::yaml::Token::TK_StreamEnd, llvm::yaml::Token::TK_StreamStart, llvm::yaml::Token::TK_Tag, llvm::yaml::Token::TK_TagDirective, llvm::yaml::Token::TK_Value, and llvm::yaml::Token::TK_VersionDirective.
escape()
std::string llvm::yaml::escape (StringRef Input)
Escape Input for a double quoted scalar.
Definition at line 641 of file YAMLParser.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), decodeUTF8(), encodeUTF8(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::utohexstr().
isBool()
bool llvm::yaml::isBool (StringRef S) inline
Definition at line 374 of file YAMLTraits.h.
References llvm::StringRef::equals().
Referenced by needsQuotes().
isNull()
bool llvm::yaml::isNull (StringRef S) inline
Definition at line 369 of file YAMLTraits.h.
References llvm::StringRef::equals().
Referenced by needsQuotes().
isNumber()
bool llvm::yaml::isNumber (StringRef S) inline
Definition at line 327 of file YAMLTraits.h.
References llvm::StringRef::drop_front(), llvm::StringRef::equals(), llvm::StringRef::find_first_not_of(), llvm::Regex::match(), llvm::StringRef::npos, and llvm::StringRef::startswith().
Referenced by isNumeric().
isNumeric()
bool llvm::yaml::isNumeric (StringRef S) inline
Definition at line 356 of file YAMLTraits.h.
References llvm::StringRef::drop_front(), llvm::StringRef::equals(), llvm::StringRef::front(), and isNumber().
Referenced by needsQuotes().
needsQuotes()
bool llvm::yaml::needsQuotes (StringRef S) inline
Definition at line 379 of file YAMLTraits.h.
References llvm::StringRef::back(), llvm::StringRef::empty(), llvm::StringRef::find_first_not_of(), llvm::StringRef::front(), isBool(), isNull(), isNumeric(), and llvm::StringRef::npos.
Referenced by llvm::yaml::ScalarTraits< BinaryRef >::mustQuote(), llvm::yaml::ScalarTraits< std::string >::mustQuote(), and llvm::yaml::ScalarTraits< StringRef >::mustQuote().
operator<<() [1/4]
template<typename T> std::enable_if< has_DocumentListTraits< T >::value, Output & >::type llvm::yaml::operator<< (Output & yout, T & docList) inline
Definition at line 1179 of file YAMLTraits.h.
References llvm::yaml::Output::beginDocuments(), llvm::yaml::Output::endDocuments(), llvm::yaml::Output::postflightDocument(), llvm::yaml::Output::preflightDocument(), T, and yamlize().
operator<<() [2/4]
template<typename T> std::enable_if< has_MappingTraits< T >::value, Output & >::type llvm::yaml::operator<< (Output & yout, T & map) inline
Definition at line 1196 of file YAMLTraits.h.
References llvm::yaml::Output::beginDocuments(), llvm::yaml::Output::endDocuments(), llvm::yaml::Output::postflightDocument(), llvm::yaml::Output::preflightDocument(), T, and yamlize().
operator<<() [3/4]
template<typename T> std::enable_if< has_SequenceTraits< T >::value, Output & >::type llvm::yaml::operator<< (Output & yout, T & seq) inline
Definition at line 1210 of file YAMLTraits.h.
References llvm::yaml::Output::beginDocuments(), llvm::yaml::Output::endDocuments(), llvm::yaml::Output::postflightDocument(), llvm::yaml::Output::preflightDocument(), T, and yamlize().
operator<<() [4/4]
template<typename T> std::enable_if< missingTraits< T >::value, Output & >::type llvm::yaml::operator<< (Output & yout, T & seq) inline
Definition at line 1224 of file YAMLTraits.h.
References T.
operator==()
bool llvm::yaml::operator== (const BinaryRef & LHS, const BinaryRef & RHS) inline
Definition at line 79 of file YAML.h.
operator>>() [1/4]
template<typename T> std::enable_if< has_DocumentListTraits< T >::value, Input & >::type llvm::yaml::operator>> (Input & yin, T & docList) inline
Definition at line 1133 of file YAMLTraits.h.
References llvm::yaml::Input::error(), llvm::yaml::Input::nextDocument(), llvm::yaml::Input::setCurrentDocument(), T, and yamlize().
operator>>() [2/4]
template<typename T> std::enable_if< has_MappingTraits< T >::value, Input & >::type llvm::yaml::operator>> (Input & yin, T & docMap) inline
Definition at line 1149 of file YAMLTraits.h.
References llvm::yaml::Input::setCurrentDocument(), T, and yamlize().
operator>>() [3/4]
template<typename T> std::enable_if< has_SequenceTraits< T >::value, Input & >::type llvm::yaml::operator>> (Input & yin, T & docSeq) inline
Definition at line 1160 of file YAMLTraits.h.
References llvm::yaml::Input::setCurrentDocument(), T, and yamlize().
operator>>() [4/4]
template<typename T> std::enable_if< missingTraits< T >::value, Input & >::type llvm::yaml::operator>> (Input & yin, T & docSeq) inline
Definition at line 1170 of file YAMLTraits.h.
References T.
scanTokens()
bool llvm::yaml::scanTokens (StringRef Input)
Scans all tokens in input without outputting anything. This is used for benchmarking the tokenizer.
Returns
true if there was an error, false otherwise.
Definition at line 628 of file YAMLParser.cpp.
References llvm::yaml::Scanner::getNext(), llvm::yaml::Token::TK_Error, and llvm::yaml::Token::TK_StreamEnd.
sectionMapping() [1/2]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::RawContentSection & Section) static
Definition at line 500 of file ELFYAML.cpp.
References commonSectionMapping(), llvm::yaml::IO::mapOptional(), and sectionMapping().
Referenced by llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Section > >::mapping(), sectionMapping(), and sectionMapping().
sectionMapping() [2/2]
void llvm::yaml::sectionMapping (IO & IO, ELFYAML::RelocationSection & Section) static
Definition at line 506 of file ELFYAML.cpp.
References commonSectionMapping(), llvm::yaml::IO::mapOptional(), and sectionMapping().
skip()
template<class CollectionType> void llvm::yaml::skip (CollectionType & C)
Definition at line 327 of file YAMLParser.h.
References begin().
Referenced by llvm::yaml::MappingNode::skip(), and llvm::yaml::SequenceNode::skip().
yamlize() [1/7]
template<typename T> std::enable_if< has_SequenceTraits< T >::value, void >::type llvm::yaml::yamlize (IO & io, T & Seq, bool)
Definition at line 668 of file YAMLTraits.h.
References llvm::yaml::IO::beginFlowSequence(), llvm::yaml::IO::beginSequence(), llvm::yaml::IO::endFlowSequence(), llvm::yaml::IO::endSequence(), llvm::yaml::IO::outputting(), llvm::yaml::IO::postflightElement(), llvm::yaml::IO::postflightFlowElement(), llvm::yaml::IO::preflightElement(), llvm::yaml::IO::preflightFlowElement(), T, and yamlize().
yamlize() [2/7]
template<typename T> std::enable_if< has_ScalarEnumerationTraits< T >::value, void >::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 592 of file YAMLTraits.h.
References llvm::yaml::IO::beginEnumScalar(), llvm::yaml::IO::endEnumScalar(), and T.
Referenced by operator<<(), operator<<(), operator<<(), operator>>(), operator>>(), operator>>(), and yamlize().
yamlize() [3/7]
template<typename T> std::enable_if< has_ScalarBitSetTraits< T >::value, void >::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 600 of file YAMLTraits.h.
References llvm::yaml::IO::beginBitSetScalar(), llvm::yaml::IO::endBitSetScalar(), and T.
yamlize() [4/7]
template<typename T> std::enable_if< has_ScalarTraits< T >::value, void >::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 613 of file YAMLTraits.h.
References llvm::StringRef::empty(), llvm::yaml::IO::getContext(), llvm::yaml::IO::outputting(), llvm::yaml::IO::scalarString(), llvm::yaml::IO::setError(), llvm::raw_string_ostream::str(), and T.
yamlize() [5/7]
template<typename T> std::enable_if< validatedMappingTraits< T >::value, void >::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 634 of file YAMLTraits.h.
References llvm::yaml::IO::beginMapping(), llvm::StringRef::empty(), llvm::yaml::IO::endMapping(), llvm::errs(), llvm::yaml::IO::outputting(), llvm::yaml::IO::setError(), and T.
yamlize() [6/7]
template<typename T> std::enable_if< unvalidatedMappingTraits< T >::value, void >::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 654 of file YAMLTraits.h.
References llvm::yaml::IO::beginMapping(), llvm::yaml::IO::endMapping(), and T.
yamlize() [7/7]
template<typename T> std::enable_if< missingTraits< T >::value, void >::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 662 of file YAMLTraits.h.
References T.