LLVM: llvm::IndexedInstrProf Namespace Reference
LLVM API Documentation
llvm::IndexedInstrProf Namespace Reference
Enumerations
enum class HashT : uint32_t { MD5 , Last = MD5 }
Functions
static uint64_t MD5Hash (StringRef Str)
static uint64_t ComputeHash (HashT Type, StringRef K)
Variables
const uint64_t Magic = 0x8169666f72706cff
const uint64_t Version = 2
const HashT HashType = HashT::MD5
Enumeration Type Documentation
HashT
enum class llvm::IndexedInstrProf::HashT : uint32_t strong
Enumerator
MD5
Last
Definition at line 24 of file InstrProfIndexed.h.
Function Documentation
ComputeHash()
uint64_t llvm::IndexedInstrProf::ComputeHash (HashT Type, StringRef K) inline static
Definition at line 41 of file InstrProfIndexed.h.
References llvm_unreachable, MD5, and MD5Hash().
Referenced by llvm::InstrProfLookupTrait::ComputeHash().
MD5Hash()
uint64_t llvm::IndexedInstrProf::MD5Hash (StringRef Str) inline static
Definition at line 30 of file InstrProfIndexed.h.
References llvm::MD5::final(), MD5, llvm::support::endian::read(), and llvm::MD5::update().
Referenced by ComputeHash().
Variable Documentation
HashType
const HashT llvm::IndexedInstrProf::HashType = HashT::MD5
Definition at line 51 of file InstrProfIndexed.h.
Referenced by llvm::InstrProfWriter::write().
Magic
const uint64_t llvm::IndexedInstrProf::Magic = 0x8169666f72706cff
Definition at line 49 of file InstrProfIndexed.h.
Referenced by llvm::IndexedInstrProfReader::hasFormat(), llvm::IndexedInstrProfReader::readHeader(), and llvm::InstrProfWriter::write().
Version
const uint64_t llvm::IndexedInstrProf::Version = 2
Definition at line 50 of file InstrProfIndexed.h.
Referenced by llvm::IndexedInstrProfReader::readHeader(), and llvm::InstrProfWriter::write().