LLVM: llvm::AMDGPU Namespace Reference
LLVM API Documentation
llvm::AMDGPU Namespace Reference
Enumerations
enum TargetIndex {
TI_CONSTDATA_START , TI_SCRATCH_RSRC_DWORD0 , TI_SCRATCH_RSRC_DWORD1 , TI_SCRATCH_RSRC_DWORD2 ,
TI_SCRATCH_RSRC_DWORD3
}
enum Fixups {
fixup_si_sopp_br = FirstTargetFixupKind , fixup_si_rodata , fixup_si_end_of_text , LastTargetFixupKind ,
NumTargetFixupKinds = LastTargetFixupKind - FirstTargetFixupKind
}
enum OperandType { OPERAND_REG_IMM32 = llvm::MCOI::OPERAND_FIRST_TARGET , OPERAND_REG_INLINE_C }
Functions
static int getMCOpcode (uint16_t Opcode, unsigned Gen)
int16_t getNamedOperandIdx (uint16_t Opcode, uint16_t NamedIndex)
int getLDSNoRetOp (uint16_t Opcode)
int getVOPe64 (uint16_t Opcode)
int getVOPe32 (uint16_t Opcode)
int getCommuteRev (uint16_t Opcode)
int getCommuteOrig (uint16_t Opcode)
int getAddr64Inst (uint16_t Opcode)
int getAtomicRetOp (uint16_t Opcode)
int getAtomicNoRetOp (uint16_t Opcode)
Variables
const uint64_t RSRC_DATA_FORMAT = 0xf00000000000LL
const uint64_t RSRC_TID_ENABLE = 1LL << 55
Enumeration Type Documentation
Fixups
enum llvm::AMDGPU::Fixups
Enumerator
fixup_si_sopp_br
16-bit PC relative fixup for SOPP branch instructions.
fixup_si_rodata
fixup for global addresses with constant initializers
fixup_si_end_of_text
fixup for offset from instruction to end of text section
LastTargetFixupKind
NumTargetFixupKinds
Definition at line 17 of file AMDGPUFixupKinds.h.
OperandType
enum llvm::AMDGPU::OperandType
Enumerator
OPERAND_REG_IMM32
Operand with register or 32-bit immediate.
OPERAND_REG_INLINE_C
Operand with register or inline constant.
Definition at line 46 of file SIDefines.h.
TargetIndex
enum llvm::AMDGPU::TargetIndex
Enumerator
TI_CONSTDATA_START
TI_SCRATCH_RSRC_DWORD0
TI_SCRATCH_RSRC_DWORD1
TI_SCRATCH_RSRC_DWORD2
TI_SCRATCH_RSRC_DWORD3
Definition at line 83 of file AMDGPU.h.
Function Documentation
getAddr64Inst()
int llvm::AMDGPU::getAddr64Inst (uint16_t Opcode)
Referenced by llvm::SIInstrInfo::legalizeOperands().
getAtomicNoRetOp()
int llvm::AMDGPU::getAtomicNoRetOp (uint16_t Opcode)
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection().
getAtomicRetOp()
int llvm::AMDGPU::getAtomicRetOp (uint16_t Opcode)
getCommuteOrig()
int llvm::AMDGPU::getCommuteOrig (uint16_t Opcode)
Referenced by llvm::SIInstrInfo::commuteOpcode().
getCommuteRev()
int llvm::AMDGPU::getCommuteRev (uint16_t Opcode)
Referenced by llvm::SIInstrInfo::commuteOpcode().
getLDSNoRetOp()
int llvm::AMDGPU::getLDSNoRetOp (uint16_t Opcode)
Referenced by llvm::R600TargetLowering::EmitInstrWithCustomInserter().
getMCOpcode()
int llvm::AMDGPU::getMCOpcode (uint16_t Opcode, unsigned Gen) static
Definition at line 344 of file AMDGPUInstrInfo.cpp.
Referenced by llvm::AMDGPUInstrInfo::pseudoToMCOpcode().
getNamedOperandIdx()
int16_t llvm::AMDGPU::getNamedOperandIdx (uint16_t Opcode, uint16_t NamedIndex)
Referenced by llvm::SIInstrInfo::areLoadsFromSameBasePtr(), llvm::SIInstrInfo::commuteInstruction(), llvm::AMDGPUInstrInfo::expandPostRAPseudo(), llvm::SIInstrInfo::findCommutedOpIndices(), llvm::SIInstrInfo::getLdStBaseRegImmOfs(), llvm::SIInstrInfo::getNamedOperand(), llvm::R600InstrInfo::getOperandIdx(), llvm::SIInstrInfo::hasModifiers(), llvm::SIInstrInfo::legalizeOperands(), nodesHaveSameOperandValue(), and llvm::SIInstrInfo::verifyInstruction().
getVOPe32()
int llvm::AMDGPU::getVOPe32 (uint16_t Opcode)
Referenced by llvm::SIInstrInfo::hasVALU32BitEncoding().
getVOPe64()
int llvm::AMDGPU::getVOPe64 (uint16_t Opcode)
Variable Documentation
RSRC_DATA_FORMAT
const uint64_t llvm::AMDGPU::RSRC_DATA_FORMAT = 0xf00000000000LL
Definition at line 360 of file SIInstrInfo.h.
Referenced by llvm::SIInstrInfo::getDefaultRsrcDataFormat().
RSRC_TID_ENABLE
const uint64_t llvm::AMDGPU::RSRC_TID_ENABLE = 1LL << 55
Definition at line 361 of file SIInstrInfo.h.
Referenced by llvm::SITargetLowering::buildScratchRSRC().