LLVM: llvm::cl Namespace Reference
LLVM API Documentation
llvm::cl Namespace Reference
Classes
class alias
struct aliasopt
struct applicator
struct applicator< char[n]>
struct applicator< const char * >
struct applicator< const char[n]>
struct applicator< FormattingFlags >
struct applicator< MiscFlags >
struct applicator< NumOccurrencesFlag >
struct applicator< OptionHidden >
struct applicator< ValueExpected >
class basic_parser
class basic_parser_impl
class bits
class bits_storage
class bits_storage< DataType, bool >
struct cat
struct desc
struct extrahelp
class generic_parser_base
struct GenericOptionValue
struct initializer
class list
class list_storage
class list_storage< DataType, bool >
struct LocationClass
struct multi_val
class opt
class opt_storage
class opt_storage< DataType, false, false >
class opt_storage< DataType, false, true >
class Option
class OptionCategory
struct OptionDiffPrinter
struct OptionDiffPrinter< DT, DT >
struct OptionValue
struct OptionValue< cl::boolOrDefault >
struct OptionValue< std::string >
struct OptionValueBase
struct OptionValueBase< DataType, false >
class OptionValueCopy
class parser
class parser< bool >
class parser< boolOrDefault >
class parser< char >
class parser< double >
class parser< float >
class parser< int >
class parser< std::string >
class parser< unsigned >
class parser< unsigned long long >
class StringSaver
Saves strings in the inheritor's stable storage and returns a stable raw character pointer.
struct value_desc
class ValuesClass
Typedefs
typedef void(* TokenizerCallback) (StringRef Source, StringSaver &Saver, SmallVectorImpl< const char * > &NewArgv, bool MarkEOLs)
String tokenization function type. Should be compatible with either Windows or Unix command line tokenizers.
Enumerations
enum NumOccurrencesFlag {
Optional = 0x00 , ZeroOrMore = 0x01 , Required = 0x02 , OneOrMore = 0x03 ,
ConsumeAfter = 0x04
}
enum ValueExpected { ValueOptional = 0x01 , ValueRequired = 0x02 , ValueDisallowed = 0x03 }
enum OptionHidden { NotHidden = 0x00 , Hidden = 0x01 , ReallyHidden = 0x02 }
enum FormattingFlags { NormalFormatting = 0x00 , Positional = 0x01 , Prefix = 0x02 , Grouping = 0x03 }
enum MiscFlags { CommaSeparated = 0x01 , PositionalEatsArgs = 0x02 , Sink = 0x04 }
enum boolOrDefault { BOU_UNSET , BOU_TRUE , BOU_FALSE }
Functions
void ParseCommandLineOptions (int argc, const char *const *argv, const char *Overview=nullptr)
void ParseEnvironmentOptions (const char *progName, const char *envvar, const char *Overview=nullptr)
void SetVersionPrinter (void(*func)())
void AddExtraVersionPrinter (void(*func)())
void PrintOptionValues ()
void MarkOptionsChanged ()
template<class Ty>
initializer< Ty > init (const Ty &Val)
template<class Ty>
LocationClass< Ty > location (Ty &L)
template<class DataType>
ValuesClass< DataType > LLVM_END_WITH_NULL values (const char *Arg, DataType Val, const char *Desc,...)
EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< bool >)
EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< boolOrDefault >)
EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< int >)
EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< unsigned >)
EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< unsigned long long >)
EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< double >)
EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< float >)
EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< std::string >)
EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< char >)
template<class ParserClass, class DT>
void printOptionDiff (const Option &O, const generic_parser_base &P, const DT &V, const OptionValue< DT > &Default, size_t GlobalWidth)
template<class ParserClass, class ValDT>
void printOptionDiff (const Option &O, const basic_parser< typename ParserClass::parser_data_type > &P, const ValDT &V, const OptionValue< ValDT > &Default, size_t GlobalWidth)
template<class Mod, class Opt>
void apply (const Mod &M, Opt *O)
EXTERN_TEMPLATE_INSTANTIATION (class opt< unsigned >)
EXTERN_TEMPLATE_INSTANTIATION (class opt< int >)
EXTERN_TEMPLATE_INSTANTIATION (class opt< std::string >)
EXTERN_TEMPLATE_INSTANTIATION (class opt< char >)
EXTERN_TEMPLATE_INSTANTIATION (class opt< bool >)
void PrintVersionMessage ()
Utility function for printing version number.
void PrintHelpMessage (bool Hidden=false, bool Categorized=false)
void getRegisteredOptions (StringMap< Option * > &Map)
Use this to get a StringMap to all registered named options (e.g. -help). Note Map Should be an empty StringMap.
void TokenizeGNUCommandLine (StringRef Source, StringSaver &Saver, SmallVectorImpl< const char * > &NewArgv, bool MarkEOLs=false)
Tokenizes a command line that can contain escapes and quotes.
void TokenizeWindowsCommandLine (StringRef Source, StringSaver &Saver, SmallVectorImpl< const char * > &NewArgv, bool MarkEOLs=false)
Tokenizes a Windows command line which may contain quotes and escaped quotes.
bool ExpandResponseFiles (StringSaver &Saver, TokenizerCallback Tokenizer, SmallVectorImpl< const char * > &Argv, bool MarkEOLs=false)
Expand response files on a command line recursively using the given StringSaver and tokenization strategy. Argv should contain the command line before expansion and will be modified in place. If requested, Argv will also be populated with nullptrs indicating where each response file line ends, which is useful for the "/link" argument that needs to consume all remaining arguments only until the next end of line, when in a response file.
TEMPLATE_INSTANTIATION (class basic_parser< bool >)
TEMPLATE_INSTANTIATION (class basic_parser< boolOrDefault >)
TEMPLATE_INSTANTIATION (class basic_parser< int >)
TEMPLATE_INSTANTIATION (class basic_parser< unsigned >)
TEMPLATE_INSTANTIATION (class basic_parser< unsigned long long >)
TEMPLATE_INSTANTIATION (class basic_parser< double >)
TEMPLATE_INSTANTIATION (class basic_parser< float >)
TEMPLATE_INSTANTIATION (class basic_parser< std::string >)
TEMPLATE_INSTANTIATION (class basic_parser< char >)
TEMPLATE_INSTANTIATION (class opt< unsigned >)
TEMPLATE_INSTANTIATION (class opt< int >)
TEMPLATE_INSTANTIATION (class opt< std::string >)
TEMPLATE_INSTANTIATION (class opt< char >)
TEMPLATE_INSTANTIATION (class opt< bool >)
Variables
OptionCategory GeneralCategory
Detailed Description
cl Namespace - This namespace contains all of the command line option processing machinery. It is intentionally a short name to make qualified usage concise.
Typedef Documentation
TokenizerCallback
typedef void(* llvm::cl::TokenizerCallback) (StringRef Source, StringSaver &Saver, SmallVectorImpl< const char * > &NewArgv, bool MarkEOLs)
String tokenization function type. Should be compatible with either Windows or Unix command line tokenizers.
Definition at line 1870 of file CommandLine.h.
Enumeration Type Documentation
boolOrDefault
enum llvm::cl::boolOrDefault
Enumerator
BOU_UNSET
BOU_TRUE
BOU_FALSE
Definition at line 428 of file CommandLine.h.
FormattingFlags
enum llvm::cl::FormattingFlags
Enumerator
NormalFormatting
Positional
Prefix
Grouping
Definition at line 126 of file CommandLine.h.
MiscFlags
enum llvm::cl::MiscFlags
Enumerator
CommaSeparated
PositionalEatsArgs
Sink
Definition at line 133 of file CommandLine.h.
NumOccurrencesFlag
enum llvm::cl::NumOccurrencesFlag
Enumerator
Optional
ZeroOrMore
Required
OneOrMore
ConsumeAfter
Definition at line 82 of file CommandLine.h.
OptionHidden
enum llvm::cl::OptionHidden
Enumerator
NotHidden
Hidden
ReallyHidden
Definition at line 105 of file CommandLine.h.
ValueExpected
enum llvm::cl::ValueExpected
Enumerator
ValueOptional
ValueRequired
ValueDisallowed
Definition at line 98 of file CommandLine.h.
Function Documentation
AddExtraVersionPrinter()
void llvm::cl::AddExtraVersionPrinter (void(* func)())
===------------------------------------------------------------------—===// AddExtraVersionPrinter - Add an extra printer to use in addition to the default one. This can be called multiple times, and each time it adds a new function to the list which will be called after the basic LLVM version printing is complete. Each can then add additional information specific to the tool.
Definition at line 1819 of file CommandLine.cpp.
References ExtraVersionPrinters.
apply()
template<class Mod, class Opt> void llvm::cl::apply (const Mod & M, Opt * O)
Definition at line 1019 of file CommandLine.h.
References llvm::cl::applicator< Mod >::opt().
Referenced by llvm::cl::alias::alias(), llvm::cl::alias::alias(), llvm::cl::alias::alias(), llvm::cl::alias::alias(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::bits< DataType, Storage, ParserClass >::bits(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::list< DataType, Storage, ParserClass >::list(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt(), and llvm::cl::opt< DataType, ExternalStorage, ParserClass >::opt().
ExpandResponseFiles()
bool llvm::cl::ExpandResponseFiles (StringSaver & Saver, TokenizerCallback Tokenizer, SmallVectorImpl< const char * > & Argv, bool MarkEOLs = false)
Expand response files on a command line recursively using the given StringSaver and tokenization strategy. Argv should contain the command line before expansion and will be modified in place. If requested, Argv will also be populated with nullptrs indicating where each response file line ends, which is useful for the "/link" argument that needs to consume all remaining arguments only until the next end of line, when in a response file.
Expand response files on a command line recursively using the given StringSaver and tokenization strategy.
Parameters
[in] Saver Delegates back to the caller for saving parsed strings.
[in] Tokenizer Tokenization strategy. Typically Unix or Windows.
[in,out] Argv Command line into which to expand response files.
[in] MarkEOLs Mark end of lines and the end of the response file with nullptrs in the Argv vector.
Returns
true if all @files were expanded successfully or there were none.
Definition at line 686 of file CommandLine.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), ExpandResponseFile(), I, llvm::SmallVectorImpl< T >::insert(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by ParseCommandLineOptions().
EXTERN_TEMPLATE_INSTANTIATION() [1/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< bool >)
EXTERN_TEMPLATE_INSTANTIATION() [2/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< boolOrDefault >)
EXTERN_TEMPLATE_INSTANTIATION() [3/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< char >)
EXTERN_TEMPLATE_INSTANTIATION() [4/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< double >)
EXTERN_TEMPLATE_INSTANTIATION() [5/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< float >)
EXTERN_TEMPLATE_INSTANTIATION() [6/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< int >)
EXTERN_TEMPLATE_INSTANTIATION() [7/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< std::string >)
EXTERN_TEMPLATE_INSTANTIATION() [8/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< unsigned >)
EXTERN_TEMPLATE_INSTANTIATION() [9/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class basic_parser< unsigned long long >)
EXTERN_TEMPLATE_INSTANTIATION() [10/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class opt< bool >)
EXTERN_TEMPLATE_INSTANTIATION() [11/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class opt< char >)
EXTERN_TEMPLATE_INSTANTIATION() [12/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class opt< int >)
EXTERN_TEMPLATE_INSTANTIATION() [13/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class opt< std::string >)
EXTERN_TEMPLATE_INSTANTIATION() [14/14]
llvm::cl::EXTERN_TEMPLATE_INSTANTIATION (class opt< unsigned >)
getRegisteredOptions()
void llvm::cl::getRegisteredOptions (StringMap< Option * > & Map)
Use this to get a StringMap to all registered named options (e.g. -help). Note Map Should be an empty StringMap.
Parameters
[out] Map will be filled with mappings where the key is the Option argument string (e.g. "help") and value is the corresponding Option*.
Access to unnamed arguments (i.e. positional) are not provided because it is expected that the client already has access to these.
Typical usage:
main(int argc,char* argv[]) {
StringMap<llvm::cl::Option*> opts;
llvm::cl::getRegisteredOptions(opts);
assert(opts.count("help") == 1)
opts["help"]->setDescription("Show alphabetical help information")
// More code
llvm::cl::ParseCommandLineOptions(argc,argv);
//More code
}
This interface is useful for modifying options in libraries that are out of the control of the client. The options should be modified before calling llvm::cl::ParseCommandLineOptions().
Definition at line 1826 of file CommandLine.cpp.
References GetOptionInfo(), and llvm::StringMapImpl::size().
init()
template<class Ty> initializer< Ty > llvm::cl::init (const Ty & Val)
Definition at line 314 of file CommandLine.h.
Referenced by ABIName(), AsmInstrumentation(), CFIEnforcing(), CFIFuncName(), CFIType(), CMModel(), DataSections(), DisableFPElim(), DisableTailCalls(), DontPlaceZerosInBSS(), DwarfVersion(), EnableFPMAD(), EnableGuaranteedTailCallOpt(), EnableHonorSignDependentRoundingFPMath(), EnableNoInfsFPMath(), EnableNoNaNsFPMath(), EnablePIE(), EnableUnsafeFPMath(), FCFI(), FileType(), FloatABIForCalls(), FunctionSections(), FuseFPOps(), GenerateSoftFloatCalls(), JTableType(), MCPU(), OverrideStackAlignment(), llvm::OptionRegistry::registerOption(), RelocModel(), StartAfter(), STATISTIC(), StopAfter(), TMModel(), TrapFuncName(), and UseCtors().
location()
template<class Ty> LocationClass< Ty > llvm::cl::location (Ty & L)
Definition at line 329 of file CommandLine.h.
MarkOptionsChanged()
void llvm::cl::MarkOptionsChanged ()
Definition at line 101 of file CommandLine.cpp.
References OptionListChanged.
Referenced by llvm::cl::Option::addArgument(), llvm::cl::parser< DataType >::addLiteralOption(), and llvm::cl::Option::removeArgument().
ParseCommandLineOptions()
void llvm::cl::ParseCommandLineOptions (int argc, const char *const * argv, const char * Overview = nullptr)
Definition at line 778 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::StringMap< ValueTy, AllocatorTy >::clear(), ConsumeAfter, llvm::StringRef::data(), llvm::dbgs(), DEBUG, EatsUnboundedNumberOfValues(), llvm::SmallVectorBase::empty(), llvm::StringMapImpl::empty(), llvm::StringRef::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::cl::Option::error(), llvm::errs(), ExpandResponseFiles(), llvm::sys::path::filename(), llvm::cl::Option::getFormattingFlag(), llvm::cl::Option::getMiscFlags(), GetOptionInfo(), HandlePrefixedOrGroupedOption(), I, llvm_unreachable, LookupNearestOption(), LookupOption(), MoreHelp, OneOrMore, Optional, OptionListChanged, Positional, PositionalEatsArgs, ProgramName, ProgramOverview, ProvideOption(), ProvidePositionalOption(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), Required, RequiresValue(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::StringRef::size(), llvm::StringRef::substr(), TokenizeGNUCommandLine(), and ZeroOrMore.
Referenced by LLVMParseCommandLineOptions(), llvm::LTOCodeGenerator::parseCodeGenDebugOptions(), and ParseEnvironmentOptions().
ParseEnvironmentOptions()
void llvm::cl::ParseEnvironmentOptions (const char * progName, const char * envVar, const char * Overview = nullptr)
ParseEnvironmentOptions - An alternative entry point to the CommandLine library, which allows you to read the program's name from the caller (as PROGNAME) and its command-line arguments from an environment variable (whose name is given in ENVVAR).
Definition at line 754 of file CommandLine.cpp.
References ParseCommandLineOptions(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and TokenizeGNUCommandLine().
PrintHelpMessage()
void llvm::cl::PrintHelpMessage (bool Hidden = false, bool Categorized = false)
This function just prints the help message, exactly the same way as if the -help or -help-hidden option had been given on the command line.
NOTE: THIS FUNCTION TERMINATES THE PROGRAM!
Parameters
Hidden if true will print hidden options
Categorized if true print options in categories
Definition at line 1796 of file CommandLine.cpp.
References CategorizedHiddenPrinter(), CategorizedNormalPrinter(), Hidden, UncategorizedHiddenPrinter(), and UncategorizedNormalPrinter().
printOptionDiff() [1/2]
template<class ParserClass, class ValDT> void llvm::cl::printOptionDiff (const Option & O, const basic_parser< typename ParserClass::parser_data_type > & P, const ValDT & V, const OptionValue< ValDT > & Default, size_t GlobalWidth)
Definition at line 963 of file CommandLine.h.
References Default, P, and llvm::cl::OptionDiffPrinter< ParserDT, ValDT >::print().
printOptionDiff() [2/2]
template<class ParserClass, class DT> void llvm::cl::printOptionDiff (const Option & O, const generic_parser_base & P, const DT & V, const OptionValue< DT > & Default, size_t GlobalWidth)
Definition at line 936 of file CommandLine.h.
References Default, and P.
PrintOptionValues()
void llvm::cl::PrintOptionValues ()
Definition at line 1708 of file CommandLine.cpp.
References GetOptionInfo(), PrintAllOptions, PrintOptions, llvm::SmallVectorTemplateCommon< T, typename >::size(), and sortOpts().
PrintVersionMessage()
void llvm::cl::PrintVersionMessage ()
Utility function for printing version number.
Definition at line 1815 of file CommandLine.cpp.
References VersionPrinterInstance.
SetVersionPrinter()
void llvm::cl::SetVersionPrinter (void(* func)())
===------------------------------------------------------------------—===// SetVersionPrinter - Override the default (LLVM specific) version printer used to print out the version when –version is given on the command line. This allows other systems using the CommandLine utilities to print their own version string.
Definition at line 1817 of file CommandLine.cpp.
References OverrideVersionPrinter.
TEMPLATE_INSTANTIATION() [1/14]
llvm::cl::TEMPLATE_INSTANTIATION (class basic_parser< bool >)
TEMPLATE_INSTANTIATION() [2/14]
llvm::cl::TEMPLATE_INSTANTIATION (class basic_parser< boolOrDefault >)
TEMPLATE_INSTANTIATION() [3/14]
llvm::cl::TEMPLATE_INSTANTIATION (class basic_parser< char >)
TEMPLATE_INSTANTIATION() [4/14]
llvm::cl::TEMPLATE_INSTANTIATION (class basic_parser< double >)
TEMPLATE_INSTANTIATION() [5/14]
llvm::cl::TEMPLATE_INSTANTIATION (class basic_parser< float >)
TEMPLATE_INSTANTIATION() [6/14]
llvm::cl::TEMPLATE_INSTANTIATION (class basic_parser< int >)
TEMPLATE_INSTANTIATION() [7/14]
llvm::cl::TEMPLATE_INSTANTIATION (class basic_parser< std::string >)
TEMPLATE_INSTANTIATION() [8/14]
llvm::cl::TEMPLATE_INSTANTIATION (class basic_parser< unsigned >)
TEMPLATE_INSTANTIATION() [9/14]
llvm::cl::TEMPLATE_INSTANTIATION (class basic_parser< unsigned long long >)
TEMPLATE_INSTANTIATION() [10/14]
llvm::cl::TEMPLATE_INSTANTIATION (class opt< bool >)
TEMPLATE_INSTANTIATION() [11/14]
llvm::cl::TEMPLATE_INSTANTIATION (class opt< char >)
TEMPLATE_INSTANTIATION() [12/14]
llvm::cl::TEMPLATE_INSTANTIATION (class opt< int >)
TEMPLATE_INSTANTIATION() [13/14]
llvm::cl::TEMPLATE_INSTANTIATION (class opt< std::string >)
TEMPLATE_INSTANTIATION() [14/14]
llvm::cl::TEMPLATE_INSTANTIATION (class opt< unsigned >)
TokenizeGNUCommandLine()
void llvm::cl::TokenizeGNUCommandLine (StringRef Source, StringSaver & Saver, SmallVectorImpl< const char * > & NewArgv, bool MarkEOLs = false)
Tokenizes a command line that can contain escapes and quotes.
The quoting rules match those used by GCC and other tools that use libiberty's buildargv() or expandargv() utilities, and do not match bash. They differ from buildargv() on treatment of backslashes that do not escape a special character to make it possible to accept most Windows file paths.
Parameters
[in] Source The string to be split on whitespace with quotes.
[in] Saver Delegates back to the caller for saving parsed strings.
[in] MarkEOLs true if tokenizing a response file and you want end of lines and end of the response file to be marked with a nullptr string.
[out] NewArgv All parsed strings are appended to NewArgv.
Definition at line 482 of file CommandLine.cpp.
References llvm::SmallString< InternalLen >::c_str(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorBase::empty(), I, isGNUSpecial(), isQuote(), isWhitespace(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::cl::StringSaver::SaveString(), and llvm::StringRef::size().
Referenced by ParseCommandLineOptions(), and ParseEnvironmentOptions().
TokenizeWindowsCommandLine()
void llvm::cl::TokenizeWindowsCommandLine (StringRef Source, StringSaver & Saver, SmallVectorImpl< const char * > & NewArgv, bool MarkEOLs = false)
Tokenizes a Windows command line which may contain quotes and escaped quotes.
See MSDN docs for CommandLineToArgvW for information on the quoting rules. http://msdn.microsoft.com/en-us/library/windows/desktop/17w5ykft(v=vs.85).aspx
Parameters
[in] Source The string to be split on whitespace with quotes.
[in] Saver Delegates back to the caller for saving parsed strings.
[in] MarkEOLs true if tokenizing a response file and you want end of lines and end of the response file to be marked with a nullptr string.
[out] NewArgv All parsed strings are appended to NewArgv.
Definition at line 580 of file CommandLine.cpp.
References llvm::SmallString< InternalLen >::c_str(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorBase::empty(), I, INIT, isWhitespace(), parseBackslash(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::cl::StringSaver::SaveString(), and llvm::StringRef::size().
values()
template<class DataType> ValuesClass< DataType > LLVM_END_WITH_NULL llvm::cl::values (const char * Arg, DataType Val, const char * Desc, ...)
Definition at line 503 of file CommandLine.h.
Referenced by AsmInstrumentation(), CFIType(), CMModel(), FileType(), FloatABIForCalls(), FuseFPOps(), JTableType(), RelocModel(), and TMModel().
Variable Documentation
GeneralCategory
OptionCategory llvm::cl::GeneralCategory extern
Referenced by llvm::cl::Option::Option().