LLVM: llvm::sampleprof Namespace Reference
LLVM API Documentation
llvm::sampleprof Namespace Reference
Classes
class FunctionSamples
Representation of the samples collected for a function.
struct LineLocation
Represents the relative location of an instruction.
class SampleProfileReader
Sample-based profile reader.
class SampleProfileReaderBinary
class SampleProfileReaderText
class SampleProfileWriter
Sample-based profile writer. Base class.
class SampleProfileWriterBinary
Sample-based profile writer (binary format).
class SampleProfileWriterText
Sample-based profile writer (text format).
class SampleRecord
Representation of a single sample record.
Typedefs
typedef DenseMap< LineLocation, SampleRecord > BodySampleMap
Enumerations
enum SampleProfileFormat { SPF_None = 0 , SPF_Text , SPF_Binary , SPF_GCC }
Functions
static uint64_t SPMagic ()
static uint64_t SPVersion ()
Typedef Documentation
BodySampleMap
typedef DenseMap<LineLocation, SampleRecord> llvm::sampleprof::BodySampleMap
Definition at line 160 of file SampleProf.h.
Enumeration Type Documentation
SampleProfileFormat
enum llvm::sampleprof::SampleProfileFormat
Enumerator
SPF_None
SPF_Text
SPF_Binary
SPF_GCC
Definition at line 28 of file SampleProfWriter.h.
Function Documentation
SPMagic()
uint64_t llvm::sampleprof::SPMagic () inline static
Definition at line 53 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileReaderBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderBinary::readHeader(), and llvm::sampleprof::SampleProfileWriterBinary::SampleProfileWriterBinary().
SPVersion()
uint64_t llvm::sampleprof::SPVersion () inline static
Definition at line 60 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileReaderBinary::readHeader(), and llvm::sampleprof::SampleProfileWriterBinary::SampleProfileWriterBinary().