LLVM: llvm::PatternMatch Namespace Reference
LLVM API Documentation
llvm::PatternMatch Namespace Reference
Classes
struct AnyBinaryOp_match
struct api_pred_ty
This helper class is used to match scalar and vector constants that satisfy a specified predicate, and bind them to an APInt.
struct apint_match
struct Argument_match
struct BinaryOp_match
struct bind_const_intval_ty
struct bind_ty
struct BinOp2_match
struct br_match
struct brc_match
struct CastClass_match
struct class_match
struct CmpClass_match
struct constantint_match
struct cst_pred_ty
This helper class is used to match scalar and vector constants that satisfy a specified predicate.
struct Exact_match
struct fneg_match
struct IntrinsicID_match
Intrinsic matchers.
struct is_all_ones
struct is_maxsignedvalue
struct is_one
struct is_power2
struct is_sign_bit
struct m_Intrinsic_Ty
struct m_Intrinsic_Ty< T0 >
struct m_Intrinsic_Ty< T0, T1 >
struct m_Intrinsic_Ty< T0, T1, T2 >
struct m_Intrinsic_Ty< T0, T1, T2, T3 >
struct match_combine_and
struct match_combine_or
Matching combinators.
struct match_neg_zero
struct match_zero
struct MaxMin_match
struct neg_match
struct not_match
struct ofmax_pred_ty
Helper class for identifying ordered max predicates.
struct ofmin_pred_ty
Helper class for identifying ordered min predicates.
struct OneUse_match
struct OverflowingBinaryOp_match
struct SelectClass_match
struct smax_pred_ty
Helper class for identifying signed max predicates.
struct smin_pred_ty
Helper class for identifying signed min predicates.
struct specific_fpval
Match a specified floating point value or vector of all elements of that value.
struct specific_intval
Match a specified integer value or vector of all elements of that.
struct specificval_ty
Match a specified Value*.
struct ufmax_pred_ty
Helper class for identifying unordered max predicates.
struct ufmin_pred_ty
Helper class for identifying unordered min predicates.
struct umax_pred_ty
Helper class for identifying unsigned max predicates.
struct umin_pred_ty
Helper class for identifying unsigned min predicates.
Functions
template<typename Val, typename Pattern>
bool match (Val *V, const Pattern &P)
template<typename T>
OneUse_match< T > m_OneUse (const T &SubPattern)
class_match< Value > m_Value ()
Match an arbitrary value and ignore it.
class_match< BinaryOperator > m_BinOp ()
Match an arbitrary binary operation and ignore it.
class_match< CmpInst > m_Cmp ()
Matches any compare instruction and ignore it.
class_match< ConstantInt > m_ConstantInt ()
Match an arbitrary ConstantInt and ignore it.
class_match< UndefValue > m_Undef ()
Match an arbitrary undef constant.
class_match< Constant > m_Constant ()
Match an arbitrary Constant and ignore it.
template<typename LTy, typename RTy>
match_combine_or< LTy, RTy > m_CombineOr (const LTy &L, const RTy &R)
Combine two pattern matchers matching L || R.
template<typename LTy, typename RTy>
match_combine_and< LTy, RTy > m_CombineAnd (const LTy &L, const RTy &R)
Combine two pattern matchers matching L && R.
match_zero m_Zero ()
Match an arbitrary zero/null constant. This includes zero_initializer for vectors and ConstantPointerNull for pointers.
match_neg_zero m_NegZero ()
Match an arbitrary zero/null constant. This includes zero_initializer for vectors and ConstantPointerNull for pointers. For floating point constants, this will match negative zero but not positive zero.
match_combine_or< match_zero, match_neg_zero > m_AnyZero ()
Match an arbitrary zero/null constant. This includes zero_initializer for vectors and ConstantPointerNull for pointers. For floating point constants, this will match negative zero and positive zero
apint_match m_APInt (const APInt *&Res)
Match a ConstantInt or splatted ConstantVector, binding the specified pointer to the contained APInt.
template<int64_t Val>
constantint_match< Val > m_ConstantInt ()
Match a ConstantInt with a specific value.
cst_pred_ty< is_one > m_One ()
Match an integer 1 or a vector with all elements equal to 1.
api_pred_ty< is_one > m_One (const APInt *&V)
cst_pred_ty< is_all_ones > m_AllOnes ()
Match an integer or vector with all bits set to true.
api_pred_ty< is_all_ones > m_AllOnes (const APInt *&V)
cst_pred_ty< is_sign_bit > m_SignBit ()
Match an integer or vector with only the sign bit(s) set.
api_pred_ty< is_sign_bit > m_SignBit (const APInt *&V)
cst_pred_ty< is_power2 > m_Power2 ()
Match an integer or vector power of 2.
api_pred_ty< is_power2 > m_Power2 (const APInt *&V)
cst_pred_ty< is_maxsignedvalue > m_MaxSignedValue ()
api_pred_ty< is_maxsignedvalue > m_MaxSignedValue (const APInt *&V)
bind_ty< Value > m_Value (Value *&V)
Match a value, capturing it if we match.
bind_ty< BinaryOperator > m_BinOp (BinaryOperator *&I)
Match a binary operator, capturing it if we match.
bind_ty< ConstantInt > m_ConstantInt (ConstantInt *&CI)
Match a ConstantInt, capturing the value if we match.
bind_ty< Constant > m_Constant (Constant *&C)
Match a Constant, capturing the value if we match.
bind_ty< ConstantFP > m_ConstantFP (ConstantFP *&C)
Match a ConstantFP, capturing the value if we match.
specificval_ty m_Specific (const Value *V)
Match if we have a specific specified value.
specific_fpval m_SpecificFP (double V)
Match a specific floating point value or vector with all elements equal to the value.
specific_fpval m_FPOne ()
Match a float 1.0 or vector with all elements equal to 1.0.
specific_intval m_SpecificInt (uint64_t V)
Match a specific integer value or vector with all elements equal to the value.
bind_const_intval_ty m_ConstantInt (uint64_t &V)
Match a ConstantInt and bind to its value. This does not match ConstantInts wider than 64-bits.
template<typename LHS, typename RHS>
AnyBinaryOp_match< LHS, RHS > m_BinOp (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Add > m_Add (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FAdd > m_FAdd (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Sub > m_Sub (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FSub > m_FSub (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Mul > m_Mul (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FMul > m_FMul (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::UDiv > m_UDiv (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::SDiv > m_SDiv (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FDiv > m_FDiv (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::URem > m_URem (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::SRem > m_SRem (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::FRem > m_FRem (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::And > m_And (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Or > m_Or (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Xor > m_Xor (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::Shl > m_Shl (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::LShr > m_LShr (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinaryOp_match< LHS, RHS, Instruction::AShr > m_AShr (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoSignedWrap > m_NSWAdd (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Sub, OverflowingBinaryOperator::NoSignedWrap > m_NSWSub (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Mul, OverflowingBinaryOperator::NoSignedWrap > m_NSWMul (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Shl, OverflowingBinaryOperator::NoSignedWrap > m_NSWShl (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoUnsignedWrap > m_NUWAdd (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Sub, OverflowingBinaryOperator::NoUnsignedWrap > m_NUWSub (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Mul, OverflowingBinaryOperator::NoUnsignedWrap > m_NUWMul (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
OverflowingBinaryOp_match< LHS, RHS, Instruction::Shl, OverflowingBinaryOperator::NoUnsignedWrap > m_NUWShl (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
BinOp2_match< LHS, RHS, Instruction::LShr, Instruction::AShr > m_Shr (const LHS &L, const RHS &R)
Matches LShr or AShr.
template<typename LHS, typename RHS>
BinOp2_match< LHS, RHS, Instruction::LShr, Instruction::Shl > m_LogicalShift (const LHS &L, const RHS &R)
Matches LShr or Shl.
template<typename LHS, typename RHS>
BinOp2_match< LHS, RHS, Instruction::SDiv, Instruction::UDiv > m_IDiv (const LHS &L, const RHS &R)
Matches UDiv and SDiv.
template<typename T>
Exact_match< T > m_Exact (const T &SubPattern)
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, CmpInst, CmpInst::Predicate > m_Cmp (CmpInst::Predicate &Pred, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, ICmpInst, ICmpInst::Predicate > m_ICmp (ICmpInst::Predicate &Pred, const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
CmpClass_match< LHS, RHS, FCmpInst, FCmpInst::Predicate > m_FCmp (FCmpInst::Predicate &Pred, const LHS &L, const RHS &R)
template<typename Cond, typename LHS, typename RHS>
SelectClass_match< Cond, LHS, RHS > m_Select (const Cond &C, const LHS &L, const RHS &R)
template<int64_t L, int64_t R, typename Cond>
SelectClass_match< Cond, constantint_match< L >, constantint_match< R > > m_SelectCst (const Cond &C)
This matches a select of two constants, e.g.: m_SelectCst<-1, 0>(m_Value(V))
template<typename OpTy>
CastClass_match< OpTy, Instruction::BitCast > m_BitCast (const OpTy &Op)
Matches BitCast.
template<typename OpTy>
CastClass_match< OpTy, Instruction::PtrToInt > m_PtrToInt (const OpTy &Op)
Matches PtrToInt.
template<typename OpTy>
CastClass_match< OpTy, Instruction::Trunc > m_Trunc (const OpTy &Op)
Matches Trunc.
template<typename OpTy>
CastClass_match< OpTy, Instruction::SExt > m_SExt (const OpTy &Op)
Matches SExt.
template<typename OpTy>
CastClass_match< OpTy, Instruction::ZExt > m_ZExt (const OpTy &Op)
Matches ZExt.
template<typename OpTy>
CastClass_match< OpTy, Instruction::UIToFP > m_UIToFP (const OpTy &Op)
Matches UIToFP.
template<typename OpTy>
CastClass_match< OpTy, Instruction::SIToFP > m_SIToFP (const OpTy &Op)
Matches SIToFP.
template<typename LHS>
not_match< LHS > m_Not (const LHS &L)
template<typename LHS>
neg_match< LHS > m_Neg (const LHS &L)
Match an integer negate.
template<typename LHS>
fneg_match< LHS > m_FNeg (const LHS &L)
Match a floating point negate.
br_match m_UnconditionalBr (BasicBlock *&Succ)
template<typename Cond_t>
brc_match< Cond_t > m_Br (const Cond_t &C, BasicBlock *&T, BasicBlock *&F)
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, smax_pred_ty > m_SMax (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, smin_pred_ty > m_SMin (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, umax_pred_ty > m_UMax (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
MaxMin_match< ICmpInst, LHS, RHS, umin_pred_ty > m_UMin (const LHS &L, const RHS &R)
template<typename LHS, typename RHS>
MaxMin_match< FCmpInst, LHS, RHS, ofmax_pred_ty > m_OrdFMax (const LHS &L, const RHS &R)
Match an 'ordered' floating point maximum function. Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'maximum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(ogt/ge, L, R), L, R) semantics matched by this predicate.
template<typename LHS, typename RHS>
MaxMin_match< FCmpInst, LHS, RHS, ofmin_pred_ty > m_OrdFMin (const LHS &L, const RHS &R)
Match an 'ordered' floating point minimum function. Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'minimum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(olt/le, L, R), L, R) semantics matched by this predicate.
template<typename LHS, typename RHS>
MaxMin_match< FCmpInst, LHS, RHS, ufmax_pred_ty > m_UnordFMax (const LHS &L, const RHS &R)
Match an 'unordered' floating point maximum function. Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'maximum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(ugt/ge, L, R), L, R) semantics matched by this predicate.
template<typename LHS, typename RHS>
MaxMin_match< FCmpInst, LHS, RHS, ufmin_pred_ty > m_UnordFMin (const LHS &L, const RHS &R)
Match an 'unordered' floating point minimum function. Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'minimum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(ult/le, L, R), L, R) semantics matched by this predicate.
template<unsigned OpI, typename Opnd_t>
Argument_match< Opnd_t > m_Argument (const Opnd_t &Op)
Match an argument.
template<Intrinsic::ID IntrID>
IntrinsicID_match m_Intrinsic ()
Match intrinsic calls like this: m_Intrinsic<Intrinsic::fabs>(m_Value(X))
template<Intrinsic::ID IntrID, typename T0>
m_Intrinsic_Ty< T0 >::Ty m_Intrinsic (const T0 &Op0)
template<Intrinsic::ID IntrID, typename T0, typename T1>
m_Intrinsic_Ty< T0, T1 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1)
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2>
m_Intrinsic_Ty< T0, T1, T2 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1, const T2 &Op2)
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2, typename T3>
m_Intrinsic_Ty< T0, T1, T2, T3 >::Ty m_Intrinsic (const T0 &Op0, const T1 &Op1, const T2 &Op2, const T3 &Op3)
template<typename Opnd0>
m_Intrinsic_Ty< Opnd0 >::Ty m_BSwap (const Opnd0 &Op0)
template<typename Opnd0, typename Opnd1>
m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty m_FMin (const Opnd0 &Op0, const Opnd1 &Op1)
template<typename Opnd0, typename Opnd1>
m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty m_FMax (const Opnd0 &Op0, const Opnd1 &Op1)
Function Documentation
m_Add()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Add > llvm::PatternMatch::m_Add (const LHS & L, const RHS & R) inline
Definition at line 431 of file PatternMatch.h.
Referenced by checkForNegativeOperand(), FindScalarElement(), llvm::InstCombiner::FoldOrOfICmps(), getValueFromFromCondition(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), SimplifyAndOfICmps(), SimplifyOrInst(), SimplifyOrOfICmps(), SimplifySubInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), and llvm::InstCombiner::visitSub().
m_AllOnes() [1/2]
cst_pred_ty< is_all_ones > llvm::PatternMatch::m_AllOnes () inline
Match an integer or vector with all bits set to true.
Definition at line 252 of file PatternMatch.h.
Referenced by SimplifyAndInst(), SimplifyAShrInst(), SimplifyOrInst(), SimplifySelectInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSelectInstWithICmp(), and llvm::InstCombiner::visitSub().
m_AllOnes() [2/2]
api_pred_ty< is_all_ones > llvm::PatternMatch::m_AllOnes (const APInt *& V) inline
Definition at line 255 of file PatternMatch.h.
m_And()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::And > llvm::PatternMatch::m_And (const LHS & L, const RHS & R) inline
Definition at line 503 of file PatternMatch.h.
Referenced by checkForNegativeOperand(), llvm::InstCombiner::FoldAndOfICmps(), foldLogOpOfMaskedICmpsHelper(), llvm::InstCombiner::FoldOrWithConstants(), foldSelectICmpAnd(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldShiftByConstant(), llvm::InstCombiner::FoldXorWithConstants(), isKnownToBeAPowerOfTwo(), m_c_And(), ProcessUMulZExtIdiom(), SimplifyICmpInst(), SimplifyOrInst(), SimplifySelectInst(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
m_AnyZero()
match_combine_or< match_zero, match_neg_zero > llvm::PatternMatch::m_AnyZero () inline
Match an arbitrary zero/null constant. This includes zero_initializer for vectors and ConstantPointerNull for pointers. For floating point constants, this will match negative zero and positive zero
Definition at line 156 of file PatternMatch.h.
References m_CombineOr(), m_NegZero(), and m_Zero().
Referenced by SimplifyFAddInst(), SimplifyFMulInst(), SimplifyFSubInst(), and llvm::InstCombiner::visitFAdd().
m_APInt()
apint_match llvm::PatternMatch::m_APInt (const APInt *& Res) inline
Match a ConstantInt or splatted ConstantVector, binding the specified pointer to the contained APInt.
Definition at line 180 of file PatternMatch.h.
Referenced by checkForNegativeOperand(), llvm::InstCombiner::commonIDivTransforms(), ComputeNumSignBits(), llvm::ConstantFoldBinaryInstruction(), getLogBase2Vector(), llvm::isSafeToSpeculativelyExecute(), SimplifyICmpInst(), SimplifySelectInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSRem(), and llvm::InstCombiner::visitUDiv().
m_Argument()
template<unsigned OpI, typename Opnd_t> Argument_match< Opnd_t > llvm::PatternMatch::m_Argument (const Opnd_t & Op) inline
Match an argument.
Definition at line 1134 of file PatternMatch.h.
Referenced by m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), and m_Intrinsic().
m_AShr()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::AShr > llvm::PatternMatch::m_AShr (const LHS & L, const RHS & R) inline
Definition at line 533 of file PatternMatch.h.
Referenced by computeKnownBitsFromAssume(), SimplifyGEPInst(), SimplifyICmpInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitSExt(), and llvm::InstCombiner::visitSub().
m_BinOp() [1/3]
class_match< BinaryOperator > llvm::PatternMatch::m_BinOp () inline
Match an arbitrary binary operation and ignore it.
Definition at line 67 of file PatternMatch.h.
m_BinOp() [2/3]
bind_ty< BinaryOperator > llvm::PatternMatch::m_BinOp (BinaryOperator *& I) inline
Match a binary operator, capturing it if we match.
Definition at line 299 of file PatternMatch.h.
References I.
m_BinOp() [3/3]
template<typename LHS, typename RHS> AnyBinaryOp_match< LHS, RHS > llvm::PatternMatch::m_BinOp (const LHS & L, const RHS & R) inline
Definition at line 403 of file PatternMatch.h.
m_BitCast()
template<typename OpTy> CastClass_match< OpTy, Instruction::BitCast > llvm::PatternMatch::m_BitCast (const OpTy & Op) inline
Matches BitCast.
Definition at line 786 of file PatternMatch.h.
Referenced by computeKnownBitsFromAssume(), and OptimizeIntToFloatBitCast().
m_Br()
template<typename Cond_t> brc_match< Cond_t > llvm::PatternMatch::m_Br (const Cond_t & C, BasicBlock *& T, BasicBlock *& F) inline
Definition at line 939 of file PatternMatch.h.
References F, and T.
Referenced by tryToMoveFreeBeforeNullTest(), and llvm::InstCombiner::visitBranchInst().
m_BSwap()
template<typename Opnd0> m_Intrinsic_Ty< Opnd0 >::Ty llvm::PatternMatch::m_BSwap (const Opnd0 & Op0) inline
Definition at line 1210 of file PatternMatch.h.
References m_Intrinsic().
Referenced by llvm::InstCombiner::visitCallInst().
m_Cmp() [1/2]
class_match< CmpInst > llvm::PatternMatch::m_Cmp () inline
Matches any compare instruction and ignore it.
Definition at line 72 of file PatternMatch.h.
m_Cmp() [2/2]
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, CmpInst, CmpInst::Predicate > llvm::PatternMatch::m_Cmp (CmpInst::Predicate & Pred, const LHS & L, const RHS & R) inline
Definition at line 717 of file PatternMatch.h.
m_CombineAnd()
template<typename LTy, typename RTy> match_combine_and< LTy, RTy > llvm::PatternMatch::m_CombineAnd (const LTy & L, const RTy & R) inline
Combine two pattern matchers matching L && R.
Definition at line 123 of file PatternMatch.h.
Referenced by m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), and m_Intrinsic().
m_CombineOr()
template<typename LTy, typename RTy> match_combine_or< LTy, RTy > llvm::PatternMatch::m_CombineOr (const LTy & L, const RTy & R) inline
Combine two pattern matchers matching L || R.
Definition at line 117 of file PatternMatch.h.
Referenced by computeKnownBitsFromAssume(), m_AnyZero(), m_c_And(), m_c_ICmp(), m_c_Or(), m_c_Xor(), and SimplifyICmpInst().
m_Constant() [1/2]
class_match< Constant > llvm::PatternMatch::m_Constant () inline
Match an arbitrary Constant and ignore it.
Definition at line 83 of file PatternMatch.h.
Referenced by FindScalarElement(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitZExt().
m_Constant() [2/2]
bind_ty< Constant > llvm::PatternMatch::m_Constant (Constant *& C) inline
Match a Constant, capturing the value if we match.
Definition at line 305 of file PatternMatch.h.
m_ConstantFP()
bind_ty< ConstantFP > llvm::PatternMatch::m_ConstantFP (ConstantFP *& C) inline
Match a ConstantFP, capturing the value if we match.
Definition at line 308 of file PatternMatch.h.
m_ConstantInt() [1/4]
class_match< ConstantInt > llvm::PatternMatch::m_ConstantInt () inline
Match an arbitrary ConstantInt and ignore it.
Definition at line 75 of file PatternMatch.h.
Referenced by CanEvaluateShifted(), computeKnownBitsFromAssume(), llvm::InstCombiner::FoldAndOfICmps(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldOrWithConstants(), foldSelectICmpAnd(), llvm::InstCombiner::FoldShiftByConstant(), llvm::InstCombiner::FoldXorWithConstants(), getValueFromFromCondition(), m_SelectCst(), OptimizeIntToFloatBitCast(), ProcessUMulZExtIdiom(), SimplifyAndOfICmps(), SimplifyDiv(), SimplifyGEPInst(), SimplifyICmpInst(), SimplifyOrOfICmps(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitTrunc().
m_ConstantInt() [2/4]
template<int64_t Val> constantint_match< Val > llvm::PatternMatch::m_ConstantInt () inline
Match a ConstantInt with a specific value.
Definition at line 198 of file PatternMatch.h.
m_ConstantInt() [3/4]
bind_ty< ConstantInt > llvm::PatternMatch::m_ConstantInt (ConstantInt *& CI) inline
Match a ConstantInt, capturing the value if we match.
Definition at line 302 of file PatternMatch.h.
m_ConstantInt() [4/4]
bind_const_intval_ty llvm::PatternMatch::m_ConstantInt (uint64_t & V) inline
Match a ConstantInt and bind to its value. This does not match ConstantInts wider than 64-bits.
Definition at line 384 of file PatternMatch.h.
m_Exact()
template<typename T> Exact_match< T > llvm::PatternMatch::m_Exact (const T & SubPattern) inline
Definition at line 688 of file PatternMatch.h.
References T.
Referenced by isKnownNonZero(), isKnownToBeAPowerOfTwo(), SimplifyMulInst(), SimplifyShlInst(), and llvm::InstCombiner::visitUDiv().
m_FAdd()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FAdd > llvm::PatternMatch::m_FAdd (const LHS & L, const RHS & R) inline
Definition at line 437 of file PatternMatch.h.
m_FCmp()
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, FCmpInst, FCmpInst::Predicate > llvm::PatternMatch::m_FCmp (FCmpInst::Predicate & Pred, const LHS & L, const RHS & R) inline
Definition at line 729 of file PatternMatch.h.
Referenced by llvm::InstCombiner::visitBranchInst().
m_FDiv()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FDiv > llvm::PatternMatch::m_FDiv (const LHS & L, const RHS & R) inline
Definition at line 479 of file PatternMatch.h.
Referenced by llvm::InstCombiner::visitFDiv().
m_FMax()
template<typename Opnd0, typename Opnd1> m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty llvm::PatternMatch::m_FMax (const Opnd0 & Op0, const Opnd1 & Op1) inline
Definition at line 1221 of file PatternMatch.h.
References m_Intrinsic().
Referenced by llvm::InstCombiner::visitCallInst().
m_FMin()
template<typename Opnd0, typename Opnd1> m_Intrinsic_Ty< Opnd0, Opnd1 >::Ty llvm::PatternMatch::m_FMin (const Opnd0 & Op0, const Opnd1 & Op1) inline
Definition at line 1215 of file PatternMatch.h.
References m_Intrinsic().
Referenced by llvm::InstCombiner::visitCallInst().
m_FMul()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FMul > llvm::PatternMatch::m_FMul (const LHS & L, const RHS & R) inline
Definition at line 461 of file PatternMatch.h.
Referenced by llvm::InstCombiner::visitFDiv(), and llvm::InstCombiner::visitFMul().
m_FNeg()
template<typename LHS> fneg_match< LHS > llvm::PatternMatch::m_FNeg (const LHS & L) inline
Match a floating point negate.
Definition at line 897 of file PatternMatch.h.
Referenced by llvm::InstCombiner::visitFCmpInst().
m_FPOne()
specific_fpval llvm::PatternMatch::m_FPOne () inline
Match a float 1.0 or vector with all elements equal to 1.0.
Definition at line 343 of file PatternMatch.h.
References m_SpecificFP().
Referenced by SimplifyFMulInst().
m_FRem()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FRem > llvm::PatternMatch::m_FRem (const LHS & L, const RHS & R) inline
Definition at line 497 of file PatternMatch.h.
m_FSub()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::FSub > llvm::PatternMatch::m_FSub (const LHS & L, const RHS & R) inline
Definition at line 449 of file PatternMatch.h.
Referenced by SimplifyFAddInst(), and SimplifyFSubInst().
m_ICmp()
template<typename LHS, typename RHS> CmpClass_match< LHS, RHS, ICmpInst, ICmpInst::Predicate > llvm::PatternMatch::m_ICmp (ICmpInst::Predicate & Pred, const LHS & L, const RHS & R) inline
Definition at line 723 of file PatternMatch.h.
Referenced by computeKnownBitsFromAssume(), m_c_ICmp(), SimplifyAndOfICmps(), SimplifyOrOfICmps(), simplifyUnsignedRangeCheck(), tryToMoveFreeBeforeNullTest(), and llvm::InstCombiner::visitBranchInst().
m_IDiv()
template<typename LHS, typename RHS> BinOp2_match< LHS, RHS, Instruction::SDiv, Instruction::UDiv > llvm::PatternMatch::m_IDiv (const LHS & L, const RHS & R) inline
Matches UDiv and SDiv.
Definition at line 669 of file PatternMatch.h.
Referenced by isKnownNonZero(), and SimplifyMulInst().
m_Intrinsic() [1/5]
template<Intrinsic::ID IntrID> IntrinsicID_match llvm::PatternMatch::m_Intrinsic () inline
Match intrinsic calls like this: m_Intrinsic<Intrinsic::fabs>(m_Value(X))
Definition at line 1180 of file PatternMatch.h.
Referenced by llvm::InstCombineIRInserter::InsertHelper(), m_BSwap(), m_FMax(), m_FMin(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), m_Intrinsic(), llvm::AssumptionCache::registerAssumption(), and llvm::AssumptionCacheTracker::verifyAnalysis().
m_Intrinsic() [2/5]
template<Intrinsic::ID IntrID, typename T0> m_Intrinsic_Ty< T0 >::Ty llvm::PatternMatch::m_Intrinsic (const T0 & Op0) inline
Definition at line 1185 of file PatternMatch.h.
References m_Argument(), m_CombineAnd(), and m_Intrinsic().
m_Intrinsic() [3/5]
template<Intrinsic::ID IntrID, typename T0, typename T1> m_Intrinsic_Ty< T0, T1 >::Ty llvm::PatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1) inline
Definition at line 1190 of file PatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), and T1.
m_Intrinsic() [4/5]
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2> m_Intrinsic_Ty< T0, T1, T2 >::Ty llvm::PatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1, const T2 & Op2) inline
Definition at line 1197 of file PatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), and T1.
m_Intrinsic() [5/5]
template<Intrinsic::ID IntrID, typename T0, typename T1, typename T2, typename T3> m_Intrinsic_Ty< T0, T1, T2, T3 >::Ty llvm::PatternMatch::m_Intrinsic (const T0 & Op0, const T1 & Op1, const T2 & Op2, const T3 & Op3) inline
Definition at line 1204 of file PatternMatch.h.
References m_Argument(), m_CombineAnd(), m_Intrinsic(), and T1.
m_LogicalShift()
template<typename LHS, typename RHS> BinOp2_match< LHS, RHS, Instruction::LShr, Instruction::Shl > llvm::PatternMatch::m_LogicalShift (const LHS & L, const RHS & R) inline
Matches LShr or Shl.
Definition at line 662 of file PatternMatch.h.
Referenced by llvm::InstCombiner::visitOr().
m_LShr()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::LShr > llvm::PatternMatch::m_LShr (const LHS & L, const RHS & R) inline
Definition at line 527 of file PatternMatch.h.
Referenced by CanEvaluateShifted(), computeKnownBitsFromAssume(), isKnownToBeAPowerOfTwo(), OptimizeIntToFloatBitCast(), SimplifyICmpInst(), simplifyValueKnownNonZero(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), and llvm::InstCombiner::visitUDiv().
m_MaxSignedValue() [1/2]
cst_pred_ty< is_maxsignedvalue > llvm::PatternMatch::m_MaxSignedValue () inline
Definition at line 279 of file PatternMatch.h.
m_MaxSignedValue() [2/2]
api_pred_ty< is_maxsignedvalue > llvm::PatternMatch::m_MaxSignedValue (const APInt *& V) inline
Definition at line 280 of file PatternMatch.h.
m_Mul()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Mul > llvm::PatternMatch::m_Mul (const LHS & L, const RHS & R) inline
Definition at line 455 of file PatternMatch.h.
Referenced by isKnownNonZero(), SimplifyDiv(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), and llvm::InstCombiner::visitSub().
m_Neg()
template<typename LHS> neg_match< LHS > llvm::PatternMatch::m_Neg (const LHS & L) inline
Match an integer negate.
Definition at line 874 of file PatternMatch.h.
Referenced by isKnownToBeAPowerOfTwo(), MatchSelectPattern(), SimplifyAndInst(), SimplifyICmpInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), and llvm::InstCombiner::visitSub().
m_NegZero()
match_neg_zero llvm::PatternMatch::m_NegZero () inline
Match an arbitrary zero/null constant. This includes zero_initializer for vectors and ConstantPointerNull for pointers. For floating point constants, this will match negative zero but not positive zero.
Definition at line 151 of file PatternMatch.h.
Referenced by m_AnyZero(), SimplifyFAddInst(), and SimplifyFSubInst().
m_Not()
template<typename LHS> not_match< LHS > llvm::PatternMatch::m_Not (const LHS & L) inline
Definition at line 851 of file PatternMatch.h.
Referenced by computeKnownBitsFromAssume(), MatchSelectFromAndOr(), SimplifyAddInst(), SimplifyAndInst(), SimplifyOrInst(), SimplifyXorInst(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitBranchInst(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSelectInst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
m_NSWAdd()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoSignedWrap > llvm::PatternMatch::m_NSWAdd (const LHS & L, const RHS & R) inline
Definition at line 566 of file PatternMatch.h.
References llvm::OverflowingBinaryOperator::NoSignedWrap.
m_NSWMul()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Mul, OverflowingBinaryOperator::NoSignedWrap > llvm::PatternMatch::m_NSWMul (const LHS & L, const RHS & R) inline
Definition at line 582 of file PatternMatch.h.
References llvm::OverflowingBinaryOperator::NoSignedWrap.
Referenced by llvm::InstCombiner::commonIDivTransforms().
m_NSWShl()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Shl, OverflowingBinaryOperator::NoSignedWrap > llvm::PatternMatch::m_NSWShl (const LHS & L, const RHS & R) inline
Definition at line 590 of file PatternMatch.h.
References llvm::OverflowingBinaryOperator::NoSignedWrap.
Referenced by llvm::InstCombiner::commonIDivTransforms(), SimplifyAShrInst(), and SimplifyICmpInst().
m_NSWSub()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Sub, OverflowingBinaryOperator::NoSignedWrap > llvm::PatternMatch::m_NSWSub (const LHS & L, const RHS & R) inline
Definition at line 574 of file PatternMatch.h.
References llvm::OverflowingBinaryOperator::NoSignedWrap.
Referenced by llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), and llvm::InstCombiner::visitSDiv().
m_NUWAdd()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Add, OverflowingBinaryOperator::NoUnsignedWrap > llvm::PatternMatch::m_NUWAdd (const LHS & L, const RHS & R) inline
Definition at line 599 of file PatternMatch.h.
References llvm::OverflowingBinaryOperator::NoUnsignedWrap.
m_NUWMul()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Mul, OverflowingBinaryOperator::NoUnsignedWrap > llvm::PatternMatch::m_NUWMul (const LHS & L, const RHS & R) inline
Definition at line 615 of file PatternMatch.h.
References llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by llvm::InstCombiner::commonIDivTransforms().
m_NUWShl()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Shl, OverflowingBinaryOperator::NoUnsignedWrap > llvm::PatternMatch::m_NUWShl (const LHS & L, const RHS & R) inline
Definition at line 623 of file PatternMatch.h.
References llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by llvm::InstCombiner::commonIDivTransforms(), SimplifyICmpInst(), and SimplifyLShrInst().
m_NUWSub()
template<typename LHS, typename RHS> OverflowingBinaryOp_match< LHS, RHS, Instruction::Sub, OverflowingBinaryOperator::NoUnsignedWrap > llvm::PatternMatch::m_NUWSub (const LHS & L, const RHS & R) inline
Definition at line 607 of file PatternMatch.h.
References llvm::OverflowingBinaryOperator::NoUnsignedWrap.
m_One() [1/2]
cst_pred_ty< is_one > llvm::PatternMatch::m_One () inline
Match an integer 1 or a vector with all elements equal to 1.
Definition at line 244 of file PatternMatch.h.
Referenced by checkForNegativeOperand(), llvm::ConstantFoldBinaryInstruction(), isKnownToBeAPowerOfTwo(), SimplifyDiv(), SimplifyICmpInst(), SimplifyMulInst(), SimplifyRem(), simplifyValueKnownNonZero(), ThreadCmpOverSelect(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitMul(), and llvm::InstCombiner::visitURem().
m_One() [2/2]
api_pred_ty< is_one > llvm::PatternMatch::m_One (const APInt *& V) inline
Definition at line 245 of file PatternMatch.h.
m_OneUse()
template<typename T> OneUse_match< T > llvm::PatternMatch::m_OneUse (const T & SubPattern) inline
Definition at line 55 of file PatternMatch.h.
References T.
Referenced by llvm::InstCombiner::FoldShiftByConstant(), simplifyValueKnownNonZero(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitShl(), and llvm::InstCombiner::visitZExt().
m_Or()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Or > llvm::PatternMatch::m_Or (const LHS & L, const RHS & R) inline
Definition at line 509 of file PatternMatch.h.
Referenced by checkForNegativeOperand(), foldSelectICmpAndOr(), isKnownNonZero(), m_c_Or(), SimplifyAndInst(), SimplifyICmpInst(), SimplifySelectInst(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
m_OrdFMax()
template<typename LHS, typename RHS> MaxMin_match< FCmpInst, LHS, RHS, ofmax_pred_ty > llvm::PatternMatch::m_OrdFMax (const LHS & L, const RHS & R) inline
Match an 'ordered' floating point maximum function. Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'maximum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(ogt/ge, L, R), L, R) semantics matched by this predicate.
                    max(L, R)  iff L and R are not NaN
m_OrdFMax(L, R) = R iff L or R are NaN
Definition at line 1071 of file PatternMatch.h.
m_OrdFMin()
template<typename LHS, typename RHS> MaxMin_match< FCmpInst, LHS, RHS, ofmin_pred_ty > llvm::PatternMatch::m_OrdFMin (const LHS & L, const RHS & R) inline
Match an 'ordered' floating point minimum function. Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'minimum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(olt/le, L, R), L, R) semantics matched by this predicate.
                    max(L, R)  iff L and R are not NaN
m_OrdFMin(L, R) = R iff L or R are NaN
Definition at line 1086 of file PatternMatch.h.
m_Power2() [1/2]
cst_pred_ty< is_power2 > llvm::PatternMatch::m_Power2 () inline
Match an integer or vector power of 2.
Definition at line 272 of file PatternMatch.h.
Referenced by llvm::InstCombiner::commonShiftTransforms(), foldSelectICmpAndOr(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitSelectInstWithICmp(), and visitUDivOperand().
m_Power2() [2/2]
api_pred_ty< is_power2 > llvm::PatternMatch::m_Power2 (const APInt *& V) inline
Definition at line 273 of file PatternMatch.h.
m_PtrToInt()
template<typename OpTy> CastClass_match< OpTy, Instruction::PtrToInt > llvm::PatternMatch::m_PtrToInt (const OpTy & Op) inline
Matches PtrToInt.
Definition at line 792 of file PatternMatch.h.
Referenced by computeKnownBitsFromAssume(), SimplifyGEPInst(), SimplifySubInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), and llvm::InstCombiner::visitSub().
m_SDiv()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::SDiv > llvm::PatternMatch::m_SDiv (const LHS & L, const RHS & R) inline
Definition at line 473 of file PatternMatch.h.
Referenced by llvm::InstCombiner::commonIDivTransforms(), SimplifyGEPInst(), SimplifyICmpInst(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::InstCombiner::visitSub().
m_Select()
template<typename Cond, typename LHS, typename RHS> SelectClass_match< Cond, LHS, RHS > llvm::PatternMatch::m_Select (const Cond & C, const LHS & L, const RHS & R) inline
Definition at line 755 of file PatternMatch.h.
Referenced by m_SelectCst(), llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitICmpInst(), and llvm::InstCombiner::visitOr().
m_SelectCst()
template<int64_t L, int64_t R, typename Cond> SelectClass_match< Cond, constantint_match< L >, constantint_match< R > > llvm::PatternMatch::m_SelectCst (const Cond & C) inline
This matches a select of two constants, e.g.: m_SelectCst<-1, 0>(m_Value(V))
Definition at line 764 of file PatternMatch.h.
References m_ConstantInt(), and m_Select().
m_SExt()
template<typename OpTy> CastClass_match< OpTy, Instruction::SExt > llvm::PatternMatch::m_SExt (const OpTy & Op) inline
Matches SExt.
Definition at line 804 of file PatternMatch.h.
Referenced by MatchSelectFromAndOr(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSelectInstWithICmp(), and llvm::InstCombiner::visitSub().
m_Shl()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Shl > llvm::PatternMatch::m_Shl (const LHS & L, const RHS & R) inline
Definition at line 521 of file PatternMatch.h.
Referenced by CanEvaluateShifted(), computeKnownBitsFromAssume(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), SimplifyICmpInst(), simplifyValueKnownNonZero(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitSub(), and visitUDivOperand().
m_Shr()
template<typename LHS, typename RHS> BinOp2_match< LHS, RHS, Instruction::LShr, Instruction::AShr > llvm::PatternMatch::m_Shr (const LHS & L, const RHS & R) inline
Matches LShr or AShr.
Definition at line 655 of file PatternMatch.h.
Referenced by llvm::InstCombiner::FoldShiftByConstant(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), and SimplifyShlInst().
m_SignBit() [1/2]
cst_pred_ty< is_sign_bit > llvm::PatternMatch::m_SignBit () inline
Match an integer or vector with only the sign bit(s) set.
Definition at line 262 of file PatternMatch.h.
Referenced by isKnownToBeAPowerOfTwo().
m_SignBit() [2/2]
api_pred_ty< is_sign_bit > llvm::PatternMatch::m_SignBit (const APInt *& V) inline
Definition at line 265 of file PatternMatch.h.
m_SIToFP()
template<typename OpTy> CastClass_match< OpTy, Instruction::SIToFP > llvm::PatternMatch::m_SIToFP (const OpTy & Op) inline
Matches SIToFP.
Definition at line 822 of file PatternMatch.h.
m_SMax()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, smax_pred_ty > llvm::PatternMatch::m_SMax (const LHS & L, const RHS & R) inline
Definition at line 1038 of file PatternMatch.h.
Referenced by SimplifyICmpInst().
m_SMin()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, smin_pred_ty > llvm::PatternMatch::m_SMin (const LHS & L, const RHS & R) inline
Definition at line 1044 of file PatternMatch.h.
Referenced by SimplifyICmpInst().
m_Specific()
specificval_ty llvm::PatternMatch::m_Specific (const Value * V) inline
Match if we have a specific specified value.
Definition at line 319 of file PatternMatch.h.
Referenced by llvm::InstCombiner::commonIDivTransforms(), computeKnownBitsFromAssume(), llvm::InstCombiner::FoldAndOfICmps(), llvm::InstCombiner::FoldOrOfICmps(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldShiftByConstant(), getValueFromFromCondition(), isKnownToBeAPowerOfTwo(), MatchSelectFromAndOr(), MatchSelectPattern(), SimplifyAddInst(), SimplifyAndInst(), SimplifyAndOfICmps(), SimplifyAShrInst(), SimplifyDiv(), SimplifyFAddInst(), SimplifyGEPInst(), SimplifyICmpInst(), SimplifyLShrInst(), SimplifyMulInst(), SimplifyOrInst(), SimplifyOrOfICmps(), SimplifyRem(), SimplifySelectInst(), SimplifyShlInst(), simplifyUnsignedRangeCheck(), SimplifyXorInst(), tryToMoveFreeBeforeNullTest(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSelectInst(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
m_SpecificFP()
specific_fpval llvm::PatternMatch::m_SpecificFP (double V) inline
Match a specific floating point value or vector with all elements equal to the value.
Definition at line 340 of file PatternMatch.h.
Referenced by detectLog2OfHalf(), m_FPOne(), and llvm::InstCombiner::visitFMul().
m_SpecificInt()
specific_intval llvm::PatternMatch::m_SpecificInt (uint64_t V) inline
Match a specific integer value or vector with all elements equal to the value.
Definition at line 380 of file PatternMatch.h.
Referenced by SimplifyGEPInst().
m_SRem()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::SRem > llvm::PatternMatch::m_SRem (const LHS & L, const RHS & R) inline
Definition at line 491 of file PatternMatch.h.
Referenced by llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonShiftTransforms(), SimplifyDiv(), SimplifyICmpInst(), and SimplifyRem().
m_Sub()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Sub > llvm::PatternMatch::m_Sub (const LHS & L, const RHS & R) inline
Definition at line 443 of file PatternMatch.h.
Referenced by llvm::InstCombiner::commonIDivTransforms(), SimplifyAddInst(), SimplifyGEPInst(), SimplifySubInst(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), and llvm::InstCombiner::visitSub().
m_Trunc()
template<typename OpTy> CastClass_match< OpTy, Instruction::Trunc > llvm::PatternMatch::m_Trunc (const OpTy & Op) inline
Matches Trunc.
Definition at line 798 of file PatternMatch.h.
Referenced by llvm::InstCombiner::FoldAndOfICmps(), OptimizeIntToFloatBitCast(), SimplifySubInst(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitZExt().
m_UDiv()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::UDiv > llvm::PatternMatch::m_UDiv (const LHS & L, const RHS & R) inline
Definition at line 467 of file PatternMatch.h.
Referenced by llvm::InstCombiner::commonIDivTransforms(), isKnownToBeAPowerOfTwo(), SimplifyDiv(), and SimplifyICmpInst().
m_UIToFP()
template<typename OpTy> CastClass_match< OpTy, Instruction::UIToFP > llvm::PatternMatch::m_UIToFP (const OpTy & Op) inline
Matches UIToFP.
Definition at line 816 of file PatternMatch.h.
m_UMax()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, umax_pred_ty > llvm::PatternMatch::m_UMax (const LHS & L, const RHS & R) inline
Definition at line 1050 of file PatternMatch.h.
Referenced by SimplifyICmpInst().
m_UMin()
template<typename LHS, typename RHS> MaxMin_match< ICmpInst, LHS, RHS, umin_pred_ty > llvm::PatternMatch::m_UMin (const LHS & L, const RHS & R) inline
Definition at line 1056 of file PatternMatch.h.
Referenced by SimplifyICmpInst().
m_UnconditionalBr()
br_match llvm::PatternMatch::m_UnconditionalBr (BasicBlock *& Succ) inline
Definition at line 919 of file PatternMatch.h.
Referenced by tryToMoveFreeBeforeNullTest().
m_Undef()
class_match< UndefValue > llvm::PatternMatch::m_Undef () inline
Match an arbitrary undef constant.
Definition at line 80 of file PatternMatch.h.
Referenced by llvm::ConstantFoldBinaryInstruction(), SimplifyAddInst(), SimplifyAndInst(), SimplifyDiv(), SimplifyFDivInst(), SimplifyFRemInst(), SimplifyInsertValueInst(), SimplifyMulInst(), SimplifyOrInst(), SimplifyRem(), SimplifyRightShift(), SimplifyShlInst(), SimplifySubInst(), and SimplifyXorInst().
m_UnordFMax()
template<typename LHS, typename RHS> MaxMin_match< FCmpInst, LHS, RHS, ufmax_pred_ty > llvm::PatternMatch::m_UnordFMax (const LHS & L, const RHS & R) inline
Match an 'unordered' floating point maximum function. Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'maximum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(ugt/ge, L, R), L, R) semantics matched by this predicate.
                    max(L, R)  iff L and R are not NaN
m_UnordFMin(L, R) = L iff L or R are NaN
Definition at line 1102 of file PatternMatch.h.
m_UnordFMin()
template<typename LHS, typename RHS> MaxMin_match< FCmpInst, LHS, RHS, ufmin_pred_ty > llvm::PatternMatch::m_UnordFMin (const LHS & L, const RHS & R) inline
Match an 'unordered' floating point minimum function. Floating point has one special value 'NaN'. Therefore, there is no total order. However, if we can ignore the 'NaN' value (for example, because of a 'no-nans-float-math' flag) a combination of a fcmp and select has 'minimum' semantics. In the presence of 'NaN' we have to preserve the original select(fcmp(ult/le, L, R), L, R) semantics matched by this predicate.
                     max(L, R)  iff L and R are not NaN
m_UnordFMin(L, R) = L iff L or R are NaN
Definition at line 1117 of file PatternMatch.h.
m_URem()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::URem > llvm::PatternMatch::m_URem (const LHS & L, const RHS & R) inline
Definition at line 485 of file PatternMatch.h.
Referenced by llvm::InstCombiner::commonIDivTransforms(), SimplifyDiv(), SimplifyICmpInst(), and SimplifyRem().
m_Value() [1/2]
class_match< Value > llvm::PatternMatch::m_Value () inline
Match an arbitrary value and ignore it.
Definition at line 64 of file PatternMatch.h.
Referenced by CanEvaluateShifted(), checkForNegativeOperand(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonShiftTransforms(), computeKnownBitsFromAssume(), FindScalarElement(), llvm::InstCombiner::FoldAndOfICmps(), foldLogOpOfMaskedICmpsHelper(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldOrWithConstants(), foldSelectICmpAnd(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldShiftByConstant(), llvm::InstCombiner::FoldXorWithConstants(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), MatchSelectFromAndOr(), OptimizeIntToFloatBitCast(), ProcessUMulZExtIdiom(), SimplifyAddInst(), SimplifyAndInst(), SimplifyAndOfICmps(), SimplifyAShrInst(), SimplifyDiv(), SimplifyFSubInst(), SimplifyGEPInst(), SimplifyICmpInst(), SimplifyLShrInst(), SimplifyMulInst(), SimplifyOrInst(), SimplifyOrOfICmps(), SimplifyRem(), SimplifySelectInst(), SimplifyShlInst(), SimplifySubInst(), simplifyUnsignedRangeCheck(), simplifyValueKnownNonZero(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitBranchInst(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitUDiv(), visitUDivOperand(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
m_Value() [2/2]
bind_ty< Value > llvm::PatternMatch::m_Value (Value *& V) inline
Match a value, capturing it if we match.
Definition at line 296 of file PatternMatch.h.
m_Xor()
template<typename LHS, typename RHS> BinaryOp_match< LHS, RHS, Instruction::Xor > llvm::PatternMatch::m_Xor (const LHS & L, const RHS & R) inline
Definition at line 515 of file PatternMatch.h.
Referenced by checkForNegativeOperand(), m_c_Xor(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
m_Zero()
match_zero llvm::PatternMatch::m_Zero () inline
Match an arbitrary zero/null constant. This includes zero_initializer for vectors and ConstantPointerNull for pointers.
Definition at line 137 of file PatternMatch.h.
Referenced by llvm::ConstantFoldBinaryInstruction(), foldSelectICmpAnd(), foldSelectICmpAndOr(), getGEPInductionOperand(), m_AnyZero(), SimplifyAddInst(), SimplifyAndInst(), SimplifyDiv(), SimplifyFAddInst(), SimplifyFSubInst(), SimplifyGEPInst(), SimplifyICmpInst(), SimplifyMulInst(), SimplifyOrInst(), SimplifyRem(), SimplifySelectInst(), SimplifyShift(), SimplifySubInst(), simplifyUnsignedRangeCheck(), SimplifyXorInst(), ThreadCmpOverSelect(), tryToMoveFreeBeforeNullTest(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSelectInstWithICmp(), and llvm::InstCombiner::visitSub().
m_ZExt()
template<typename OpTy> CastClass_match< OpTy, Instruction::ZExt > llvm::PatternMatch::m_ZExt (const OpTy & Op) inline
Matches ZExt.
Definition at line 810 of file PatternMatch.h.
Referenced by SimplifyICmpInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), and visitUDivOperand().
match()
template<typename Val, typename Pattern> bool llvm::PatternMatch::match (Val * V, const Pattern & P)
Definition at line 41 of file PatternMatch.h.
References match(), and P.
Referenced by CanEvaluateShifted(), checkForNegativeOperand(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonShiftTransforms(), computeKnownBitsFromAssume(), ComputeNumSignBits(), llvm::ConstantFoldBinaryInstruction(), detectLog2OfHalf(), FindScalarElement(), llvm::InstCombiner::FoldAndOfICmps(), foldLogOpOfMaskedICmpsHelper(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldOrWithConstants(), foldSelectICmpAnd(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldShiftByConstant(), llvm::InstCombiner::FoldXorWithConstants(), getGEPInductionOperand(), getLogBase2Vector(), getValueFromFromCondition(), llvm::InstCombineIRInserter::InsertHelper(), isKnownNonZero(), isKnownToBeAPowerOfTwo(), llvm::isSafeToSpeculativelyExecute(), match(), MatchSelectFromAndOr(), MatchSelectPattern(), OptimizeIntToFloatBitCast(), ProcessUMulZExtIdiom(), llvm::AssumptionCache::registerAssumption(), SimplifyAddInst(), SimplifyAndInst(), SimplifyAndOfICmps(), SimplifyAShrInst(), SimplifyDiv(), SimplifyFAddInst(), SimplifyFDivInst(), SimplifyFMulInst(), SimplifyFRemInst(), SimplifyFSubInst(), SimplifyGEPInst(), SimplifyICmpInst(), SimplifyInsertValueInst(), SimplifyLShrInst(), SimplifyMulInst(), SimplifyOrInst(), SimplifyOrOfICmps(), SimplifyRem(), SimplifyRightShift(), SimplifySelectInst(), SimplifyShift(), SimplifyShlInst(), SimplifySubInst(), simplifyUnsignedRangeCheck(), simplifyValueKnownNonZero(), SimplifyXorInst(), ThreadCmpOverSelect(), tryToMoveFreeBeforeNullTest(), llvm::AssumptionCacheTracker::verifyAnalysis(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitBranchInst(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSelectInst(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShl(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitUDiv(), visitUDivOperand(), llvm::InstCombiner::visitURem(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().