LLVM: llvm::SymbolRewriter Namespace Reference
LLVM API Documentation
llvm::SymbolRewriter Namespace Reference
Classes
class ExplicitRewriteDescriptor
class PatternRewriteDescriptor
class RewriteDescriptor
class RewriteMapParser
Typedefs
typedef iplist< RewriteDescriptor > RewriteDescriptorList
typedef ExplicitRewriteDescriptor< RewriteDescriptor::Type::Function, llvm::Function, &llvm::Module::getFunction > ExplicitRewriteFunctionDescriptor
typedef ExplicitRewriteDescriptor< RewriteDescriptor::Type::GlobalVariable, llvm::GlobalVariable, &llvm::Module::getGlobalVariable > ExplicitRewriteGlobalVariableDescriptor
typedef ExplicitRewriteDescriptor< RewriteDescriptor::Type::NamedAlias, llvm::GlobalAlias, &llvm::Module::getNamedAlias > ExplicitRewriteNamedAliasDescriptor
typedef PatternRewriteDescriptor< RewriteDescriptor::Type::Function, llvm::Function, &llvm::Module::getFunction, &llvm::Module::functions > PatternRewriteFunctionDescriptor
typedef PatternRewriteDescriptor< RewriteDescriptor::Type::GlobalVariable, llvm::GlobalVariable, &llvm::Module::getGlobalVariable, &llvm::Module::globals > PatternRewriteGlobalVariableDescriptor
typedef PatternRewriteDescriptor< RewriteDescriptor::Type::NamedAlias, llvm::GlobalAlias, &llvm::Module::getNamedAlias, &llvm::Module::aliases > PatternRewriteNamedAliasDescriptor
Functions
void rewriteComdat (Module &M, GlobalObject *GO, const std::string &Source, const std::string &Target)
Typedef Documentation
ExplicitRewriteFunctionDescriptor
typedef ExplicitRewriteDescriptor<RewriteDescriptor::Type::Function, llvm::Function, &llvm::Module::getFunction> llvm::SymbolRewriter::ExplicitRewriteFunctionDescriptor
Represents a rewrite for an explicitly named (function) symbol. Both the source function name and target function name of the transformation are explicitly spelt out.
Definition at line 186 of file SymbolRewriter.cpp.
ExplicitRewriteGlobalVariableDescriptor
typedef ExplicitRewriteDescriptor<RewriteDescriptor::Type::GlobalVariable, llvm::GlobalVariable, &llvm::Module::getGlobalVariable> llvm::SymbolRewriter::ExplicitRewriteGlobalVariableDescriptor
Represents a rewrite for an explicitly named (global variable) symbol. Both the source variable name and target variable name are spelt out. This applies only to module level variables.
Definition at line 194 of file SymbolRewriter.cpp.
ExplicitRewriteNamedAliasDescriptor
typedef ExplicitRewriteDescriptor<RewriteDescriptor::Type::NamedAlias, llvm::GlobalAlias, &llvm::Module::getNamedAlias> llvm::SymbolRewriter::ExplicitRewriteNamedAliasDescriptor
Represents a rewrite for an explicitly named global alias. Both the source and target name are explicitly spelt out.
Definition at line 201 of file SymbolRewriter.cpp.
PatternRewriteFunctionDescriptor
typedef PatternRewriteDescriptor<RewriteDescriptor::Type::Function, llvm::Function, &llvm::Module::getFunction, &llvm::Module::functions> llvm::SymbolRewriter::PatternRewriteFunctionDescriptor
Represents a rewrite for a regular expression based pattern for functions. A pattern for the function name is provided and a transformation for that pattern to determine the target function name create the rewrite rule.
Definition at line 209 of file SymbolRewriter.cpp.
PatternRewriteGlobalVariableDescriptor
typedef PatternRewriteDescriptor<RewriteDescriptor::Type::GlobalVariable, llvm::GlobalVariable, &llvm::Module::getGlobalVariable, &llvm::Module::globals> llvm::SymbolRewriter::PatternRewriteGlobalVariableDescriptor
Represents a rewrite for a global variable based upon a matching pattern. Each global variable matching the provided pattern will be transformed as described in the transformation pattern for the target. Applies only to module level variables.
Definition at line 219 of file SymbolRewriter.cpp.
PatternRewriteNamedAliasDescriptor
typedef PatternRewriteDescriptor<RewriteDescriptor::Type::NamedAlias, llvm::GlobalAlias, &llvm::Module::getNamedAlias, &llvm::Module::aliases> llvm::SymbolRewriter::PatternRewriteNamedAliasDescriptor
PatternRewriteNamedAliasDescriptor - represents a rewrite for global aliases which match a given pattern. The provided transformation will be applied to each of the matching names.
Definition at line 228 of file SymbolRewriter.cpp.
RewriteDescriptorList
typedef iplist<RewriteDescriptor> llvm::SymbolRewriter::RewriteDescriptorList
Definition at line 89 of file SymbolRewriter.h.
Function Documentation
rewriteComdat()
void llvm::SymbolRewriter::rewriteComdat (Module & M, GlobalObject * GO, const std::string & Source, const std::string & Target)
Definition at line 82 of file SymbolRewriter.cpp.
References llvm::GlobalObject::getComdat(), llvm::Module::getComdatSymbolTable(), llvm::Module::getOrInsertComdat(), and llvm::GlobalObject::setComdat().
Referenced by llvm::SymbolRewriter::ExplicitRewriteDescriptor< DT, ValueType, Get >::performOnModule(), and llvm::SymbolRewriter::PatternRewriteDescriptor< DT, ValueType, Get, Iterator >::performOnModule().