LLVM: llvm::object Namespace Reference
LLVM API Documentation
llvm::object Namespace Reference
Classes
class Archive
struct ArchiveMemberHeader
class BaseRelocRef
class BasicSymbolRef
class Binary
struct coff_aux_bf_and_ef_symbol
struct coff_aux_clr_token
struct coff_aux_function_definition
struct coff_aux_section_definition
struct coff_aux_weak_external
struct coff_base_reloc_block_entry
struct coff_base_reloc_block_header
struct coff_bigobj_file_header
struct coff_file_header
struct coff_load_configuration32
struct coff_relocation
struct coff_runtime_function_x64
struct coff_section
struct coff_symbol
class COFFObjectFile
class COFFSymbolRef
class content_iterator
struct data_directory
union DataRefImpl
struct delay_import_directory_table_entry
class DelayImportDirectoryEntryRef
class DiceRef
struct dos_header
The DOS compatible header at the front of all PE/COFF executables.
struct Elf_Dyn_Base
struct Elf_Dyn_Base< ELFType< TargetEndianness, MaxAlign, false > >
struct Elf_Dyn_Base< ELFType< TargetEndianness, MaxAlign, true > >
struct Elf_Dyn_Impl
Elf_Dyn_Impl: This inherits from Elf_Dyn_Base, adding getters and setters.
struct Elf_Ehdr_Impl
struct Elf_Phdr_Impl
struct Elf_Phdr_Impl< ELFType< TargetEndianness, MaxAlign, false > >
struct Elf_Phdr_Impl< ELFType< TargetEndianness, MaxAlign, true > >
struct Elf_Rel_Base
struct Elf_Rel_Base< ELFType< TargetEndianness, MaxAlign, false >, false >
struct Elf_Rel_Base< ELFType< TargetEndianness, MaxAlign, false >, true >
struct Elf_Rel_Base< ELFType< TargetEndianness, MaxAlign, true >, false >
struct Elf_Rel_Base< ELFType< TargetEndianness, MaxAlign, true >, true >
struct Elf_Rel_Impl
struct Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, false >, isRela >
struct Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, true >, isRela >
struct Elf_Shdr_Base
struct Elf_Shdr_Base< ELFType< TargetEndianness, MaxAlign, false > >
struct Elf_Shdr_Base< ELFType< TargetEndianness, MaxAlign, true > >
struct Elf_Shdr_Impl
struct Elf_Sym_Base
struct Elf_Sym_Base< ELFType< TargetEndianness, MaxAlign, false > >
struct Elf_Sym_Base< ELFType< TargetEndianness, MaxAlign, true > >
struct Elf_Sym_Impl
struct Elf_Verdaux_Impl
struct Elf_Verdef_Impl
struct Elf_Vernaux_Impl
struct Elf_Verneed_Impl
struct Elf_Versym_Impl
struct ELFDataTypeTypedefHelper
struct ELFDataTypeTypedefHelper< ELFType< TargetEndianness, MaxAlign, false > >
ELF 32bit types.
struct ELFDataTypeTypedefHelper< ELFType< TargetEndianness, MaxAlign, true > >
ELF 64bit types.
struct ELFDataTypeTypedefHelperCommon
class ELFFile
class ELFObjectFile
class ELFObjectFileBase
struct ELFType
union export_address_table_entry
struct export_directory_table_entry
class ExportDirectoryEntryRef
class ExportEntry
struct import_directory_table_entry
struct import_lookup_table_entry
class ImportDirectoryEntryRef
class ImportedSymbolRef
class IRObjectFile
class MachOBindEntry
class MachOObjectFile
class MachORebaseEntry
class MachOUniversalBinary
struct MaximumAlignment
class ObjectFile
class OwningBinary
struct pe32_header
The 32-bit PE header that follows the COFF header.
struct pe32plus_header
The 64-bit PE header that follows the COFF header.
class RelocationRef
struct RelocToApply
class RelocVisitor
Base class for object file relocation visitors.
class SectionRef
struct StringTableOffset
class symbol_iterator
class SymbolicFile
class SymbolRef
Typedefs
typedef content_iterator< ImportDirectoryEntryRef > import_directory_iterator
typedef content_iterator< DelayImportDirectoryEntryRef > delay_import_directory_iterator
typedef content_iterator< ExportDirectoryEntryRef > export_directory_iterator
typedef content_iterator< ImportedSymbolRef > imported_symbol_iterator
typedef content_iterator< BaseRelocRef > base_reloc_iterator
typedef import_lookup_table_entry< support::little32_t > import_lookup_table_entry32
typedef import_lookup_table_entry< support::little64_t > import_lookup_table_entry64
typedef support::ulittle32_t export_name_pointer_table_entry
typedef support::ulittle16_t export_ordinal_table_entry
typedef coff_symbol< support::ulittle16_t > coff_symbol16
typedef coff_symbol< support::ulittle32_t > coff_symbol32
typedef ELFFile< ELFType< support::little, 2, false > > ELF32LEFile
typedef ELFFile< ELFType< support::little, 2, true > > ELF64LEFile
typedef ELFFile< ELFType< support::big, 2, false > > ELF32BEFile
typedef ELFFile< ELFType< support::big, 2, true > > ELF64BEFile
typedef ELFObjectFile< ELFType< support::little, 2, false > > ELF32LEObjectFile
typedef ELFObjectFile< ELFType< support::little, 2, true > > ELF64LEObjectFile
typedef ELFObjectFile< ELFType< support::big, 2, false > > ELF32BEObjectFile
typedef ELFObjectFile< ELFType< support::big, 2, true > > ELF64BEObjectFile
typedef content_iterator< DiceRef > dice_iterator
typedef content_iterator< ExportEntry > export_iterator
typedef content_iterator< MachORebaseEntry > rebase_iterator
typedef content_iterator< MachOBindEntry > bind_iterator
typedef content_iterator< RelocationRef > relocation_iterator
typedef content_iterator< SectionRef > section_iterator
typedef content_iterator< BasicSymbolRef > basic_symbol_iterator
Enumerations
enum class object_error {
success = 0 , arch_not_found , invalid_file_type , parse_failed ,
unexpected_eof , bitcode_section_not_found
}
enum endianness
Functions
ErrorOr< std::unique_ptr< Binary > > createBinary (MemoryBufferRef Source, LLVMContext *Context=nullptr)
Create a Binary from Source, autodetecting the file type.
ErrorOr< OwningBinary< Binary > > createBinary (StringRef Path)
StringRef getELFRelocationTypeName (uint32_t Machine, uint32_t Type)
std::pair< unsigned char, unsigned char > getElfArchType (StringRef Object)
static unsigned elf_hash (StringRef &symbolName)
std::error_code getELFRelocationAddend (const RelocationRef R, int64_t &Addend)
std::pair< symbol_iterator, symbol_iterator > getELFDynamicSymbolIterators (const SymbolicFile *Obj)
std::error_code GetELFSymbolVersion (const ObjectFile *Obj, const SymbolRef &Sym, StringRef &Version, bool &IsDefault)
const std::error_category & object_category ()
std::error_code make_error_code (object_error e)
bool operator== (const DataRefImpl &a, const DataRefImpl &b)
bool operator!= (const DataRefImpl &a, const DataRefImpl &b)
bool operator< (const DataRefImpl &a, const DataRefImpl &b)
Variables
const uint64_t UnknownAddressOrSize = ~0ULL
Typedef Documentation
base_reloc_iterator
typedef content_iterator<BaseRelocRef> llvm::object::base_reloc_iterator
Definition at line 37 of file Object/COFF.h.
basic_symbol_iterator
typedef content_iterator<BasicSymbolRef> llvm::object::basic_symbol_iterator
Definition at line 112 of file SymbolicFile.h.
bind_iterator
typedef content_iterator<MachOBindEntry> llvm::object::bind_iterator
Definition at line 185 of file Object/MachO.h.
coff_symbol16
typedef coff_symbol<support::ulittle16_t> llvm::object::coff_symbol16
Definition at line 249 of file Object/COFF.h.
coff_symbol32
typedef coff_symbol<support::ulittle32_t> llvm::object::coff_symbol32
Definition at line 250 of file Object/COFF.h.
delay_import_directory_iterator
typedef content_iterator<DelayImportDirectoryEntryRef> llvm::object::delay_import_directory_iterator
Definition at line 34 of file Object/COFF.h.
dice_iterator
typedef content_iterator<DiceRef> llvm::object::dice_iterator
Definition at line 50 of file Object/MachO.h.
ELF32BEFile
typedef ELFFile<ELFType<support::big, 2, false> > llvm::object::ELF32BEFile
Definition at line 430 of file Object/ELF.h.
ELF32BEObjectFile
typedef ELFObjectFile<ELFType<support::big, 2, false> > llvm::object::ELF32BEObjectFile
Definition at line 235 of file ELFObjectFile.h.
ELF32LEFile
typedef ELFFile<ELFType<support::little, 2, false> > llvm::object::ELF32LEFile
Definition at line 428 of file Object/ELF.h.
ELF32LEObjectFile
typedef ELFObjectFile<ELFType<support::little, 2, false> > llvm::object::ELF32LEObjectFile
Definition at line 233 of file ELFObjectFile.h.
ELF64BEFile
typedef ELFFile<ELFType<support::big, 2, true> > llvm::object::ELF64BEFile
Definition at line 431 of file Object/ELF.h.
ELF64BEObjectFile
typedef ELFObjectFile<ELFType<support::big, 2, true> > llvm::object::ELF64BEObjectFile
Definition at line 236 of file ELFObjectFile.h.
ELF64LEFile
typedef ELFFile<ELFType<support::little, 2, true> > llvm::object::ELF64LEFile
Definition at line 429 of file Object/ELF.h.
ELF64LEObjectFile
typedef ELFObjectFile<ELFType<support::little, 2, true> > llvm::object::ELF64LEObjectFile
Definition at line 234 of file ELFObjectFile.h.
export_directory_iterator
typedef content_iterator<ExportDirectoryEntryRef> llvm::object::export_directory_iterator
Definition at line 35 of file Object/COFF.h.
export_iterator
typedef content_iterator<ExportEntry> llvm::object::export_iterator
Definition at line 101 of file Object/MachO.h.
export_name_pointer_table_entry
typedef support::ulittle32_t llvm::object::export_name_pointer_table_entry
Definition at line 225 of file Object/COFF.h.
export_ordinal_table_entry
typedef support::ulittle16_t llvm::object::export_ordinal_table_entry
Definition at line 226 of file Object/COFF.h.
import_directory_iterator
typedef content_iterator<ImportDirectoryEntryRef> llvm::object::import_directory_iterator
Definition at line 32 of file Object/COFF.h.
import_lookup_table_entry32
typedef import_lookup_table_entry<support::little32_t> llvm::object::import_lookup_table_entry32
Definition at line 190 of file Object/COFF.h.
import_lookup_table_entry64
typedef import_lookup_table_entry<support::little64_t> llvm::object::import_lookup_table_entry64
Definition at line 192 of file Object/COFF.h.
imported_symbol_iterator
typedef content_iterator<ImportedSymbolRef> llvm::object::imported_symbol_iterator
Definition at line 36 of file Object/COFF.h.
rebase_iterator
typedef content_iterator<MachORebaseEntry> llvm::object::rebase_iterator
Definition at line 137 of file Object/MachO.h.
relocation_iterator
typedef content_iterator<RelocationRef> llvm::object::relocation_iterator
Definition at line 75 of file ObjectFile.h.
section_iterator
typedef content_iterator<SectionRef> llvm::object::section_iterator
Definition at line 80 of file ObjectFile.h.
Enumeration Type Documentation
endianness
enum llvm::support::endianness
Definition at line 23 of file Endian.h.
object_error
enum class llvm::object::object_error strong
Enumerator
success
arch_not_found
invalid_file_type
parse_failed
unexpected_eof
bitcode_section_not_found
Definition at line 24 of file Object/Error.h.
Function Documentation
createBinary() [1/2]
ErrorOr< std::unique_ptr< Binary > > llvm::object::createBinary (MemoryBufferRef Source, LLVMContext * Context = nullptr)
Create a Binary from Source, autodetecting the file type.
Parameters
Source The data to create the Binary from.
Definition at line 39 of file Binary.cpp.
References llvm::sys::fs::file_magic::archive, llvm::sys::fs::file_magic::bitcode, llvm::sys::fs::file_magic::coff_import_library, llvm::sys::fs::file_magic::coff_object, llvm::object::Archive::create(), llvm::object::MachOUniversalBinary::create(), llvm::object::SymbolicFile::createSymbolicFile(), llvm::sys::fs::file_magic::elf, llvm::sys::fs::file_magic::elf_core, llvm::sys::fs::file_magic::elf_executable, llvm::sys::fs::file_magic::elf_relocatable, llvm::sys::fs::file_magic::elf_shared_object, llvm::MemoryBufferRef::getBuffer(), llvm::sys::fs::identify_magic(), invalid_file_type, llvm_unreachable, llvm::sys::fs::file_magic::macho_bundle, llvm::sys::fs::file_magic::macho_core, llvm::sys::fs::file_magic::macho_dsym_companion, llvm::sys::fs::file_magic::macho_dynamic_linker, llvm::sys::fs::file_magic::macho_dynamically_linked_shared_lib, llvm::sys::fs::file_magic::macho_dynamically_linked_shared_lib_stub, llvm::sys::fs::file_magic::macho_executable, llvm::sys::fs::file_magic::macho_fixed_virtual_memory_shared_lib, llvm::sys::fs::file_magic::macho_object, llvm::sys::fs::file_magic::macho_preload_executable, llvm::sys::fs::file_magic::macho_universal_binary, llvm::sys::fs::file_magic::pecoff_executable, llvm::sys::fs::file_magic::unknown, and llvm::sys::fs::file_magic::windows_resource.
Referenced by createBinary(), and llvm::object::Archive::Child::getAsBinary().
createBinary() [2/2]
ErrorOr< OwningBinary< Binary > > llvm::object::createBinary (StringRef Path)
Definition at line 76 of file Binary.cpp.
References createBinary(), llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), and llvm::MemoryBuffer::getFileOrSTDIN().
elf_hash()
unsigned llvm::object::elf_hash (StringRef & symbolName) inline static
This function returns the hash value for a symbol in the .dynsym section Name of the API remains consistent as specified in the libelf REF : http://www.sco.com/developers/gabi/latest/ch5.dynamic.html#hash
Definition at line 1001 of file Object/ELF.h.
References llvm::StringRef::size().
getElfArchType()
std::pair< unsigned char, unsigned char > llvm::object::getElfArchType (StringRef Object) inline
Definition at line 43 of file Object/ELF.h.
References llvm::ELF::EI_CLASS, llvm::ELF::EI_DATA, llvm::ELF::EI_NIDENT, llvm::ELF::ELFCLASSNONE, llvm::ELF::ELFDATANONE, and llvm::StringRef::size().
Referenced by llvm::object::ObjectFile::createELFObjectFile().
getELFDynamicSymbolIterators()
std::pair< symbol_iterator, symbol_iterator > llvm::object::getELFDynamicSymbolIterators (const SymbolicFile * Obj) inline
Definition at line 938 of file ELFObjectFile.h.
References llvm::cast().
getELFRelocationAddend()
std::error_code llvm::object::getELFRelocationAddend (const RelocationRef R, int64_t & Addend) inline
Definition at line 930 of file ELFObjectFile.h.
References llvm::cast(), llvm::object::RelocationRef::getObjectFile(), and llvm::object::RelocationRef::getRawDataRefImpl().
Referenced by llvm::RuntimeDyldELF::processRelocationRef().
getELFRelocationTypeName()
StringRef llvm::object::getELFRelocationTypeName (uint32_t Machine, uint32_t Type)
Definition at line 19 of file ELF.cpp.
References llvm::ELF::EM_386, llvm::ELF::EM_AARCH64, llvm::ELF::EM_ARM, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_MIPS, llvm::ELF::EM_PPC, llvm::ELF::EM_PPC64, llvm::ELF::EM_S390, llvm::ELF::EM_SPARC, llvm::ELF::EM_SPARC32PLUS, llvm::ELF::EM_SPARCV9, and llvm::ELF::EM_X86_64.
Referenced by llvm::object::ELFFile< ELFT >::getRelocationTypeName(), and llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName().
GetELFSymbolVersion()
std::error_code llvm::object::GetELFSymbolVersion (const ObjectFile * Obj, const SymbolRef & Sym, StringRef & Version, bool & IsDefault) inline
Definition at line 942 of file ELFObjectFile.h.
References llvm::cast().
make_error_code()
std::error_code llvm::object::make_error_code (object_error e) inline
Definition at line 33 of file Object/Error.h.
References object_category().
object_category()
const std::error_category & llvm::object::object_category ()
Definition at line 54 of file Object/Error.cpp.
References error_category.
Referenced by make_error_code().
operator!=()
bool llvm::object::operator!= (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 38 of file SymbolicFile.h.
References operator==().
operator<()
bool llvm::object::operator< (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 42 of file SymbolicFile.h.
operator==()
bool llvm::object::operator== (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 32 of file SymbolicFile.h.
Referenced by operator!=().
Variable Documentation
UnknownAddressOrSize
const uint64_t llvm::object::UnknownAddressOrSize = ~0ULL
Definition at line 114 of file SymbolicFile.h.
Referenced by llvm::getOffset(), llvm::object::COFFObjectFile::getSymbolAddress(), llvm::object::ELFObjectFile< ELFT >::getSymbolAddress(), llvm::object::MachOObjectFile::getSymbolAddress(), llvm::object::MachOObjectFile::getSymbolFlags(), llvm::object::COFFObjectFile::getSymbolSize(), and llvm::object::MachOObjectFile::getSymbolSize().