LLVM: llvm::mdconst Namespace Reference
LLVM API Documentation
llvm::mdconst Namespace Reference
Transitional API for extracting constants from Metadata.
Namespaces
namespace detail
Functions
template<class X, class Y>
std::enable_if< detail::IsValidPointer< X, Y >::value, bool >::type hasa (Y &&MD)
Check whether Metadata has a Value.
template<class X, class Y>
std::enable_if< detail::IsValidReference< X, Y & >::value, bool >::type hasa (Y &MD)
template<class X, class Y>
std::enable_if< detail::IsValidPointer< X, Y >::value, X * >::type extract (Y &&MD)
Extract a Value from Metadata.
template<class X, class Y>
std::enable_if< detail::IsValidReference< X, Y & >::value, X * >::type extract (Y &MD)
template<class X, class Y>
std::enable_if< detail::IsValidPointer< X, Y >::value, X * >::type extract_or_null (Y &&MD)
Extract a Value from Metadata, allowing null.
template<class X, class Y>
std::enable_if< detail::IsValidPointer< X, Y >::value, X * >::type dyn_extract (Y &&MD)
Extract a Value from Metadata, if any.
template<class X, class Y>
std::enable_if< detail::IsValidPointer< X, Y >::value, X * >::type dyn_extract_or_null (Y &&MD)
Extract a Value from Metadata, if any, allowing null.
Detailed Description
Transitional API for extracting constants from Metadata.
This namespace contains transitional functions for metadata that points to Constants.
In prehistory – when metadata was a subclass of Value – MDNode operands could refer to any Value. There's was a lot of code like this:
MDNode *N = ...;
auto *CI = dyn_cast<ConstantInt>(N->getOperand(2));
Now that Value and Metadata are in separate hierarchies, maintaining the semantics for isa(), cast(), dyn_cast() (etc.) requires three steps: cast in the Metadata hierarchy, extraction of the Value, and cast in the Value hierarchy. Besides creating boiler-plate, this requires subtle control flow changes.
The end-goal is to create a new type of metadata, called (e.g.) MDInt, so that metadata can refer to numbers without traversing a bridge to the Value hierarchy. In this final state, the code above would look like this:
MDNode *N = ...;
auto *MI = dyn_cast<MDInt>(N->getOperand(2));
The API in this namespace supports the transition. MDInt doesn't exist yet, and even once it does, changing each metadata schema to use it is its own mini-project. In the meantime this API prevents us from introducing complex and bug-prone control flow that will disappear in the end. In particular, the above code looks like this:
MDNode *N = ...;
auto *CI = mdconst::dyn_extract<ConstantInt>(N->getOperand(2));
The full set of provided functions includes:
mdconst::hasa <=> isa mdconst::extract <=> cast mdconst::extract_or_null <=> cast_or_null mdconst::dyn_extract <=> dyn_cast mdconst::dyn_extract_or_null <=> dyn_cast_or_null
The target of the cast must be a subclass of Constant.
Function Documentation
dyn_extract()
template<class X, class Y> std::enable_if< detail::IsValidPointer< X, Y >::value, X * >::type llvm::mdconst::dyn_extract (Y && MD) inline
Extract a Value from Metadata, if any.
As an analogue to dyn_cast_or_null(), extract the Value subclass X from MD, return null if MD doesn't contain a Value or if the Value it does contain is of the wrong subclass.
Definition at line 415 of file Metadata.h.
References llvm::dyn_cast(), and Y.
Referenced by cacheAnnotationFromMD(), llvm::ConstantFoldTerminator(), llvm::MachineInstr::emitError(), ExtractBranchMetadata(), llvm::getAlign(), llvm::Module::isValidModFlagBehavior(), and srcMgrDiagHandler().
dyn_extract_or_null()
template<class X, class Y> std::enable_if< detail::IsValidPointer< X, Y >::value, X * >::type llvm::mdconst::dyn_extract_or_null (Y && MD) inline
Extract a Value from Metadata, if any, allowing null.
As an analogue to dyn_cast_or_null(), extract the Value subclass X from MD, return null if MD doesn't contain a Value or if the Value it does contain is of the wrong subclass, allowing MD to be null.
Definition at line 428 of file Metadata.h.
References llvm::dyn_cast(), llvm::dyn_cast_or_null(), and Y.
Referenced by cacheAnnotationFromMD().
extract() [1/2]
template<class X, class Y> std::enable_if< detail::IsValidPointer< X, Y >::value, X * >::type llvm::mdconst::extract (Y && MD) inline
Extract a Value from Metadata.
As an analogue to cast(), extract the Value subclass X from MD.
Definition at line 386 of file Metadata.h.
References llvm::cast(), and Y.
Referenced by llvm::computeKnownBitsFromRangeMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), GetBranchWeights(), llvm::FPMathOperator::getFPAccuracy(), llvm::MDNode::getMostGenericFPMath(), llvm::MDNode::getMostGenericRange(), GetRangeFromMetadata(), rangeMetadataExcludesValue(), and UnrollCountPragmaValue().
extract() [2/2]
template<class X, class Y> std::enable_if< detail::IsValidReference< X, Y & >::value, X * >::type llvm::mdconst::extract (Y & MD) inline
Definition at line 392 of file Metadata.h.
References extract, and Y.
extract_or_null()
template<class X, class Y> std::enable_if< detail::IsValidPointer< X, Y >::value, X * >::type llvm::mdconst::extract_or_null (Y && MD) inline
Extract a Value from Metadata, allowing null.
As an analogue to cast_or_null(), extract the Value subclass X from MD, allowing MD to be null.
Definition at line 402 of file Metadata.h.
References llvm::cast(), llvm::cast_or_null(), and Y.
Referenced by llvm::getDebugMetadataVersionFromModule().
hasa() [1/2]
template<class X, class Y> std::enable_if< detail::IsValidPointer< X, Y >::value, bool >::type llvm::mdconst::hasa (Y && MD) inline
Check whether Metadata has a Value.
As an analogue to isa(), check whether MD has an Value inside of type X.
Definition at line 368 of file Metadata.h.
References llvm::dyn_cast(), llvm::isa(), and Y.
Referenced by llvm::Module::addModuleFlag(), hasa(), and VerifySubsetOf().
hasa() [2/2]
template<class X, class Y> std::enable_if< detail::IsValidReference< X, Y & >::value, bool >::type llvm::mdconst::hasa (Y & MD) inline
Definition at line 377 of file Metadata.h.
References hasa(), and Y.