LLVM: llvm::ARM_MC Namespace Reference
LLVM API Documentation
llvm::ARM_MC Namespace Reference
Functions
std::string ParseARMTriple (StringRef TT, StringRef CPU)
MCSubtargetInfo * createARMMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
Function Documentation
createARMMCSubtargetInfo()
MCSubtargetInfo * llvm::ARM_MC::createARMMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
createARMMCSubtargetInfo - Create a ARM MCSubtargetInfo instance. This is exposed so Asm parser, etc. do not need to go through TargetRegistry.
Definition at line 239 of file ARMMCTargetDesc.cpp.
References llvm::StringRef::empty(), ParseARMTriple(), llvm::StringRef::str(), and llvm::X.
Referenced by LLVMInitializeARMTargetMC().
ParseARMTriple()
std::string llvm::ARM_MC::ParseARMTriple (StringRef TT, StringRef CPU)
Definition at line 134 of file ARMMCTargetDesc.cpp.
References llvm::Triple::ARMSubArch_v4t, llvm::Triple::ARMSubArch_v5, llvm::Triple::ARMSubArch_v5te, llvm::Triple::ARMSubArch_v6, llvm::Triple::ARMSubArch_v6m, llvm::Triple::ARMSubArch_v6t2, llvm::Triple::ARMSubArch_v7, llvm::Triple::ARMSubArch_v7em, llvm::Triple::ARMSubArch_v7m, llvm::Triple::ARMSubArch_v7s, llvm::Triple::ARMSubArch_v8, llvm::StringRef::empty(), llvm::Triple::getArch(), llvm::Triple::getSubArch(), llvm::Triple::isOSNaCl(), isThumb(), llvm_unreachable, llvm::Triple::NoSubArch, llvm::Triple::thumb, and llvm::Triple::thumbeb.
Referenced by createARMMCSubtargetInfo().