LLVM: NVPTXLowerAggrCopies.cpp File Reference
LLVM API Documentation
NVPTXLowerAggrCopies.cpp File Reference
#include "NVPTXLowerAggrCopies.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Functions
FunctionPass * llvm::createLowerAggrCopies ()
static void convertTransferToLoop (Instruction *splitAt, Value *srcAddr, Value *dstAddr, Value *len, bool srcVolatile, bool dstVolatile, LLVMContext &Context, Function &F)
static void convertMemSetToLoop (Instruction *splitAt, Value *dstAddr, Value *len, Value *val, LLVMContext &Context, Function &F)
Function Documentation
convertMemSetToLoop()
void convertMemSetToLoop (Instruction * splitAt, Value * dstAddr, Value * len, Value * val, LLVMContext & Context, Function & F) static
Definition at line 74 of file NVPTXLowerAggrCopies.cpp.
References llvm::PHINode::addIncoming(), llvm::BasicBlock::Create(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAdd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCondBr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateGEP(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpULT(), llvm::IRBuilder< preserveNames, T, Inserter >::CreatePHI(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateStore(), llvm::dyn_cast(), F, llvm::ConstantInt::get(), llvm::PointerType::get(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::TerminatorInst::setSuccessor(), and llvm::BasicBlock::splitBasicBlock().
Referenced by llvm::NVPTXLowerAggrCopies::runOnFunction().
convertTransferToLoop()
void convertTransferToLoop (Instruction * splitAt, Value * srcAddr, Value * dstAddr, Value * len, bool srcVolatile, bool dstVolatile, LLVMContext & Context, Function & F) static
Definition at line 33 of file NVPTXLowerAggrCopies.cpp.
References llvm::PHINode::addIncoming(), llvm::BasicBlock::Create(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAdd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCondBr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateGEP(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpULT(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateLoad(), llvm::IRBuilder< preserveNames, T, Inserter >::CreatePHI(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateStore(), llvm::dyn_cast(), F, llvm::ConstantInt::get(), llvm::Type::getInt8PtrTy(), llvm::Instruction::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::TerminatorInst::setSuccessor(), and llvm::BasicBlock::splitBasicBlock().
Referenced by llvm::NVPTXLowerAggrCopies::runOnFunction().