LLVM: NVPTXTargetMachine.cpp File Reference
LLVM API Documentation
NVPTXTargetMachine.cpp File Reference
#include "NVPTXTargetMachine.h"
#include "MCTargetDesc/NVPTXMCAsmInfo.h"
#include "NVPTX.h"
#include "NVPTXAllocaHoisting.h"
#include "NVPTXLowerAggrCopies.h"
#include "NVPTXTargetObjectFile.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunctionAnalysis.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/Verifier.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include "llvm/Transforms/Scalar.h"
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Functions
void llvm::initializeNVVMReflectPass (PassRegistry &)
void llvm::initializeGenericToNVVMPass (PassRegistry &)
void llvm::initializeNVPTXAssignValidGlobalNamesPass (PassRegistry &)
void llvm::initializeNVPTXFavorNonGenericAddrSpacesPass (PassRegistry &)
void llvm::initializeNVPTXLowerStructArgsPass (PassRegistry &)
void LLVMInitializeNVPTXTarget ()
Function Documentation
LLVMInitializeNVPTXTarget()
void LLVMInitializeNVPTXTarget ()
Definition at line 57 of file NVPTXTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::initializeGenericToNVVMPass(), llvm::initializeNVPTXAssignValidGlobalNamesPass(), llvm::initializeNVPTXFavorNonGenericAddrSpacesPass(), llvm::initializeNVPTXLowerStructArgsPass(), llvm::initializeNVVMReflectPass(), llvm::TheNVPTXTarget32, llvm::TheNVPTXTarget64, llvm::X, and Y.