LLVM: NVPTXAsmPrinter.cpp File Reference
LLVM API Documentation
NVPTXAsmPrinter.cpp File Reference
#include "NVPTXAsmPrinter.h"
#include "InstPrinter/NVPTXInstPrinter.h"
#include "MCTargetDesc/NVPTXMCAsmInfo.h"
#include "NVPTX.h"
#include "NVPTXInstrInfo.h"
#include "NVPTXMCExpr.h"
#include "NVPTXMachineFunctionInfo.h"
#include "NVPTXRegisterInfo.h"
#include "NVPTXTargetMachine.h"
#include "NVPTXUtilities.h"
#include "cl_common_defines.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/TimeValue.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include <sstream>
Macros
#define DEPOTNAME "__local_depot"
Functions
static bool usedInGlobalVarDef (const Constant *C)
static bool usedInOneFunc (const User *U, Function const *&oneFunc)
static bool canDemoteGlobalVar (const GlobalVariable *gv, Function const *&f)
static bool useFuncSeen (const Constant *C, llvm::DenseMap< const Function *, bool > &seenMap)
static unsigned int getOpenCLAlignment (const DataLayout *TD, Type *Ty)
void LLVMInitializeNVPTXBackendAsmPrinter ()
void LLVMInitializeNVPTXAsmPrinter ()
Variables
static cl::opt< bool > EmitLineNumbers ("nvptx-emit-line-numbers", cl::Hidden, cl::desc("NVPTX Specific: Emit Line numbers even without -G"), cl::init(true))
static cl::opt< bool > InterleaveSrc ("nvptx-emit-src", cl::ZeroOrMore, cl::Hidden, cl::desc("NVPTX Specific: Emit source line in ptx file"), cl::init(false))
Macro Definition Documentation
DEPOTNAME
#define DEPOTNAME "__local_depot"
Definition at line 51 of file NVPTXAsmPrinter.cpp.
Function Documentation
canDemoteGlobalVar()
bool canDemoteGlobalVar (const GlobalVariable * gv, Function const *& f) static
Definition at line 654 of file NVPTXAsmPrinter.cpp.
References llvm::ADDRESS_SPACE_SHARED, llvm::PointerType::getAddressSpace(), llvm::GlobalValue::getType(), llvm::GlobalValue::hasInternalLinkage(), and usedInOneFunc().
getOpenCLAlignment()
unsigned int getOpenCLAlignment (const DataLayout * TD, Type * Ty) static
Definition at line 1342 of file NVPTXAsmPrinter.cpp.
References llvm::dyn_cast(), llvm::SequentialType::getElementType(), llvm::StructType::getElementType(), llvm::StructType::getNumElements(), getOpenCLAlignment(), llvm::DataLayout::getPointerPrefAlignment(), llvm::DataLayout::getPrefTypeAlignment(), and llvm::Type::isSingleValueType().
Referenced by getOpenCLAlignment().
LLVMInitializeNVPTXAsmPrinter()
void LLVMInitializeNVPTXAsmPrinter ()
Definition at line 2116 of file NVPTXAsmPrinter.cpp.
References llvm::TheNVPTXTarget32, llvm::TheNVPTXTarget64, llvm::X, and Y.
LLVMInitializeNVPTXBackendAsmPrinter()
void LLVMInitializeNVPTXBackendAsmPrinter ()
Definition at line 2072 of file NVPTXAsmPrinter.cpp.
References llvm::TheNVPTXTarget32, llvm::TheNVPTXTarget64, llvm::X, and Y.
usedInGlobalVarDef()
bool usedInGlobalVarDef (const Constant * C) static
Definition at line 605 of file NVPTXAsmPrinter.cpp.
References llvm::dyn_cast(), llvm::Value::getName(), llvm::StringRef::str(), and usedInGlobalVarDef().
Referenced by usedInGlobalVarDef().
usedInOneFunc()
bool usedInOneFunc (const User * U, Function const *& oneFunc) static
Definition at line 623 of file NVPTXAsmPrinter.cpp.
References llvm::dyn_cast(), llvm::GlobalValue::getParent(), usedInOneFunc(), and llvm::Value::users().
Referenced by canDemoteGlobalVar(), and usedInOneFunc().
useFuncSeen()
bool useFuncSeen (const Constant * C, llvm::DenseMap< const Function *, bool > & seenMap) static
Definition at line 672 of file NVPTXAsmPrinter.cpp.
References llvm::dyn_cast(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::BasicBlock::getParent(), I, and useFuncSeen().
Referenced by useFuncSeen().
Variable Documentation
EmitLineNumbers
cl::opt< bool > EmitLineNumbers("nvptx-emit-line-numbers", cl::Hidden, cl::desc("NVPTX Specific: Emit Line numbers even without -G"), cl::init(true)) ("nvptx-emit-line-numbers" , cl::Hidden , cl::desc("NVPTX Specific: Emit Line numbers even without -G") , cl::init(true)) static
Referenced by llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc().
InterleaveSrc
cl::opt< bool > InterleaveSrc("nvptx-emit-src", cl::ZeroOrMore, cl::Hidden, cl::desc("NVPTX Specific: Emit source line in ptx file"), cl::init(false)) ("nvptx-emit-src" , cl::ZeroOrMore , cl::Hidden , cl::desc("NVPTX Specific: Emit source line in ptx file") , cl::init(false)) static
Referenced by llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc().