LLVM: NVPTXMCTargetDesc.cpp File Reference
LLVM API Documentation
NVPTXMCTargetDesc.cpp File Reference
#include "NVPTXMCTargetDesc.h"
#include "InstPrinter/NVPTXInstPrinter.h"
#include "NVPTXMCAsmInfo.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/TargetRegistry.h"
#include "NVPTXGenInstrInfo.inc"
#include "NVPTXGenSubtargetInfo.inc"
#include "NVPTXGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createNVPTXMCInstrInfo ()
static MCRegisterInfo * createNVPTXMCRegisterInfo (StringRef TT)
static MCSubtargetInfo * createNVPTXMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
static MCCodeGenInfo * createNVPTXMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCInstPrinter * createNVPTXMCInstPrinter (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
void LLVMInitializeNVPTXTargetMC ()
Macro Definition Documentation
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 25 of file NVPTXMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 31 of file NVPTXMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 28 of file NVPTXMCTargetDesc.cpp.
Function Documentation
createNVPTXMCCodeGenInfo()
MCCodeGenInfo * createNVPTXMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 54 of file NVPTXMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCInstPrinter()
MCInstPrinter * createNVPTXMCInstPrinter (const Target & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) static
Definition at line 61 of file NVPTXMCTargetDesc.cpp.
References T.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCInstrInfo()
MCInstrInfo * createNVPTXMCInstrInfo () static
Definition at line 34 of file NVPTXMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCRegisterInfo()
MCRegisterInfo * createNVPTXMCRegisterInfo (StringRef TT) static
Definition at line 40 of file NVPTXMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeNVPTXTargetMC().
createNVPTXMCSubtargetInfo()
MCSubtargetInfo * createNVPTXMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS) static
Definition at line 48 of file NVPTXMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeNVPTXTargetMC().
LLVMInitializeNVPTXTargetMC()
void LLVMInitializeNVPTXTargetMC ()
Definition at line 73 of file NVPTXMCTargetDesc.cpp.
References createNVPTXMCCodeGenInfo(), createNVPTXMCInstPrinter(), createNVPTXMCInstrInfo(), createNVPTXMCRegisterInfo(), createNVPTXMCSubtargetInfo(), llvm::TargetRegistry::RegisterMCCodeGenInfo(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TheNVPTXTarget32, llvm::TheNVPTXTarget64, llvm::X, and Y.