LLVM: OcamlGCPrinter.cpp File Reference
LLVM API Documentation
OcamlGCPrinter.cpp File Reference
#include "llvm/CodeGen/GCs.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/GCMetadataPrinter.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include <cctype>
Functions
static GCMetadataPrinterRegistry::Add< OcamlGCMetadataPrinter > Y ("ocaml", "ocaml 3.10-compatible collector")
static void EmitCamlGlobal (const Module &M, AsmPrinter &AP, const char *Id)
Function Documentation
EmitCamlGlobal()
void EmitCamlGlobal (const Module & M, AsmPrinter & AP, const char * Id) static
Definition at line 50 of file OcamlGCPrinter.cpp.
References llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::Module::getModuleIdentifier(), llvm::Mangler::getNameWithPrefix(), llvm::MCContext::GetOrCreateSymbol(), llvm::AsmPrinter::Mang, llvm::MCSA_Global, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
Y()
GCMetadataPrinterRegistry::Add< OcamlGCMetadataPrinter > Y ("ocaml" , "ocaml 3.10-compatible collector") static