LLVM: PassManagerBuilder.cpp File Reference
LLVM API Documentation
PassManagerBuilder.cpp File Reference
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm-c/Transforms/PassManagerBuilder.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Verifier.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Vectorize.h"
Functions
PassManagerBuilder * unwrap (LLVMPassManagerBuilderRef P)
LLVMPassManagerBuilderRef wrap (PassManagerBuilder *P)
LLVMPassManagerBuilderRef LLVMPassManagerBuilderCreate ()
void LLVMPassManagerBuilderDispose (LLVMPassManagerBuilderRef PMB)
void LLVMPassManagerBuilderSetOptLevel (LLVMPassManagerBuilderRef PMB, unsigned OptLevel)
void LLVMPassManagerBuilderSetSizeLevel (LLVMPassManagerBuilderRef PMB, unsigned SizeLevel)
void LLVMPassManagerBuilderSetDisableUnitAtATime (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
void LLVMPassManagerBuilderSetDisableUnrollLoops (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
void LLVMPassManagerBuilderSetDisableSimplifyLibCalls (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
void LLVMPassManagerBuilderUseInlinerWithThreshold (LLVMPassManagerBuilderRef PMB, unsigned Threshold)
void LLVMPassManagerBuilderPopulateFunctionPassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM)
void LLVMPassManagerBuilderPopulateModulePassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM)
void LLVMPassManagerBuilderPopulateLTOPassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM, LLVMBool Internalize, LLVMBool RunInliner)
Variables
static cl::opt< bool > RunLoopVectorization ("vectorize-loops", cl::Hidden, cl::desc("Run the Loop vectorization passes"))
static cl::opt< bool > RunSLPVectorization ("vectorize-slp", cl::Hidden, cl::desc("Run the SLP vectorization passes"))
static cl::opt< bool > RunBBVectorization ("vectorize-slp-aggressive", cl::Hidden, cl::desc("Run the BB vectorization passes"))
static cl::opt< bool > UseGVNAfterVectorization ("use-gvn-after-vectorization", cl::init(false), cl::Hidden, cl::desc("Run GVN instead of Early CSE after vectorization passes"))
static cl::opt< bool > ExtraVectorizerPasses ("extra-vectorizer-passes", cl::init(false), cl::Hidden, cl::desc("Run cleanup optimization passes after vectorization."))
static cl::opt< bool > UseNewSROA ("use-new-sroa", cl::init(true), cl::Hidden, cl::desc("Enable the new, experimental SROA pass"))
static cl::opt< bool > RunLoopRerolling ("reroll-loops", cl::Hidden, cl::desc("Run the loop rerolling pass"))
static cl::opt< bool > RunLoadCombine ("combine-loads", cl::init(false), cl::Hidden, cl::desc("Run the load combining pass"))
static cl::opt< bool > RunSLPAfterLoopVectorization ("run-slp-after-loop-vectorization", cl::init(true), cl::Hidden, cl::desc("Run the SLP vectorizer (and BB vectorizer) after the Loop " "vectorizer instead of before"))
static cl::opt< bool > UseCFLAA ("use-cfl-aa", cl::init(false), cl::Hidden, cl::desc("Enable the new, experimental CFL alias analysis"))
static cl::opt< bool > EnableMLSM ("mlsm", cl::init(true), cl::Hidden, cl::desc("Enable motion of merged load and store"))
static ManagedStatic< SmallVector< std::pair< PassManagerBuilder::ExtensionPointTy, PassManagerBuilder::ExtensionFn >, 8 > > GlobalExtensions
Set of global extensions, automatically added as part of the standard set.
Function Documentation
unwrap()
PassManagerBuilder * unwrap (LLVMPassManagerBuilderRef P) inline
Definition at line 508 of file PassManagerBuilder.cpp.
References P.
wrap()
LLVMPassManagerBuilderRef wrap (PassManagerBuilder * P) inline
Definition at line 512 of file PassManagerBuilder.cpp.
References P.
Variable Documentation
EnableMLSM
cl::opt< bool > EnableMLSM("mlsm", cl::init(true), cl::Hidden, cl::desc("Enable motion of merged load and store")) ("mlsm" , cl::init(true) , cl::Hidden , cl::desc("Enable motion of merged load and store")) static
Referenced by llvm::PassManagerBuilder::populateModulePassManager().
ExtraVectorizerPasses
cl::opt< bool > ExtraVectorizerPasses("extra-vectorizer-passes", cl::init(false), cl::Hidden, cl::desc("Run cleanup optimization passes after vectorization.")) ("extra-vectorizer-passes" , cl::init(false) , cl::Hidden , cl::desc("Run cleanup optimization passes after vectorization.")) static
Referenced by llvm::PassManagerBuilder::populateModulePassManager().
GlobalExtensions
ManagedStatic<SmallVector<std::pair<PassManagerBuilder::ExtensionPointTy, PassManagerBuilder::ExtensionFn>, 8> > GlobalExtensions static
Set of global extensions, automatically added as part of the standard set.
Definition at line 108 of file PassManagerBuilder.cpp.
Referenced by llvm::PassManagerBuilder::addGlobalExtension(), and llvm::PassManagerBuilder::populateModulePassManager().
RunBBVectorization
cl::opt< bool > RunBBVectorization("vectorize-slp-aggressive", cl::Hidden, cl::desc("Run the BB vectorization passes")) ("vectorize-slp-aggressive" , cl::Hidden , cl::desc("Run the BB vectorization passes")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
RunLoadCombine
cl::opt< bool > RunLoadCombine("combine-loads", cl::init(false), cl::Hidden, cl::desc("Run the load combining pass")) ("combine-loads" , cl::init(false) , cl::Hidden , cl::desc("Run the load combining pass")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
RunLoopRerolling
cl::opt< bool > RunLoopRerolling("reroll-loops", cl::Hidden, cl::desc("Run the loop rerolling pass")) ("reroll-loops" , cl::Hidden , cl::desc("Run the loop rerolling pass")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
RunLoopVectorization
cl::opt< bool > RunLoopVectorization("vectorize-loops", cl::Hidden, cl::desc("Run the Loop vectorization passes")) ("vectorize-loops" , cl::Hidden , cl::desc("Run the Loop vectorization passes")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
RunSLPAfterLoopVectorization
cl::opt< bool > RunSLPAfterLoopVectorization("run-slp-after-loop-vectorization", cl::init(true), cl::Hidden, cl::desc("Run the SLP vectorizer (and BB vectorizer) after the Loop " "vectorizer instead of before")) ("run-slp-after-loop-vectorization" , cl::init(true) , cl::Hidden , cl::desc("Run the SLP vectorizer (and BB vectorizer) after the Loop " "vectorizer instead of before")) static
Referenced by llvm::PassManagerBuilder::populateModulePassManager().
RunSLPVectorization
cl::opt< bool > RunSLPVectorization("vectorize-slp", cl::Hidden, cl::desc("Run the SLP vectorization passes")) ("vectorize-slp" , cl::Hidden , cl::desc("Run the SLP vectorization passes")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
UseCFLAA
cl::opt< bool > UseCFLAA("use-cfl-aa", cl::init(false), cl::Hidden, cl::desc("Enable the new, experimental CFL alias analysis")) ("use-cfl-aa" , cl::init(false) , cl::Hidden , cl::desc("Enable the new, experimental CFL alias analysis")) static
UseGVNAfterVectorization
cl::opt< bool > UseGVNAfterVectorization("use-gvn-after-vectorization", cl::init(false), cl::Hidden, cl::desc("Run GVN instead of Early CSE after vectorization passes")) ("use-gvn-after-vectorization" , cl::init(false) , cl::Hidden , cl::desc("Run GVN instead of Early CSE after vectorization passes")) static
Referenced by llvm::PassManagerBuilder::populateModulePassManager().
UseNewSROA
cl::opt< bool > UseNewSROA("use-new-sroa", cl::init(true), cl::Hidden, cl::desc("Enable the new, experimental SROA pass")) ("use-new-sroa" , cl::init(true) , cl::Hidden , cl::desc("Enable the new, experimental SROA pass")) static
Referenced by llvm::PassManagerBuilder::populateFunctionPassManager(), and llvm::PassManagerBuilder::populateModulePassManager().