LLVM: PeepholeOptimizer.cpp File Reference
LLVM API Documentation
PeepholeOptimizer.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include <utility>
Macros
#define DEBUG_TYPE "peephole-opt"
Functions
STATISTIC (NumReuse, "Number of extension results reused")
STATISTIC (NumCmps, "Number of compares eliminated")
STATISTIC (NumImmFold, "Number of move immediate folded")
STATISTIC (NumLoadFold, "Number of loads folded")
STATISTIC (NumSelects, "Number of selects optimized")
STATISTIC (NumUncoalescableCopies, "Number of uncoalescable copies optimized")
STATISTIC (NumRewrittenCopies, "Number of copies rewritten")
INITIALIZE_PASS_BEGIN (PeepholeOptimizer, "peephole-opts", "Peephole Optimizations", false, false) INITIALIZE_PASS_END(PeepholeOptimizer
static bool shareSameRegisterFile (const TargetRegisterInfo &TRI, const TargetRegisterClass *DefRC, unsigned DefSubReg, const TargetRegisterClass *SrcRC, unsigned SrcSubReg)
Check if the registers defined by the pair (RegisterClass, SubReg) share the same register file.
static CopyRewriter * getCopyRewriter (MachineInstr &MI, const TargetInstrInfo &TII)
Get the appropriated CopyRewriter for MI.
Variables
static cl::opt< bool > Aggressive ("aggressive-ext-opt", cl::Hidden, cl::desc("Aggressive extension optimization"))
static cl::opt< bool > DisablePeephole ("disable-peephole", cl::Hidden, cl::init(false), cl::desc("Disable the peephole optimizer"))
static cl::opt< bool > DisableAdvCopyOpt ("disable-adv-copy-opt", cl::Hidden, cl::init(false), cl::desc("Disable advanced copy optimization"))
peephole opts
peephole Peephole Optimizations
peephole Peephole false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "peephole-opt"
Definition at line 85 of file PeepholeOptimizer.cpp.
Function Documentation
getCopyRewriter()
CopyRewriter * getCopyRewriter (MachineInstr & MI, const TargetInstrInfo & TII) static
Get the appropriated CopyRewriter for MI.
Returns
A pointer to a dynamically allocated CopyRewriter or nullptr if no rewriter works for MI.
Definition at line 852 of file PeepholeOptimizer.cpp.
References llvm::TargetOpcode::COPY, llvm::TargetOpcode::EXTRACT_SUBREG, llvm::TargetOpcode::INSERT_SUBREG, llvm_unreachable, llvm::TargetOpcode::REG_SEQUENCE, and TII.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (PeepholeOptimizer , "peephole-opts" , "Peephole Optimizations" , false , false)
References INITIALIZE_PASS_DEPENDENCY.
shareSameRegisterFile()
bool shareSameRegisterFile (const TargetRegisterInfo & TRI, const TargetRegisterClass * DefRC, unsigned DefSubReg, const TargetRegisterClass * SrcRC, unsigned SrcSubReg) static
Check if the registers defined by the pair (RegisterClass, SubReg) share the same register file.
Definition at line 511 of file PeepholeOptimizer.cpp.
References llvm::TargetRegisterInfo::getCommonSubClass(), llvm::TargetRegisterInfo::getCommonSuperRegClass(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), and std::swap().
STATISTIC() [1/7]
STATISTIC (NumCmps , "Number of compares eliminated")
STATISTIC() [2/7]
STATISTIC (NumImmFold , "Number of move immediate folded")
STATISTIC() [3/7]
STATISTIC (NumLoadFold , "Number of loads folded")
STATISTIC() [4/7]
STATISTIC (NumReuse , "Number of extension results reused")
STATISTIC() [5/7]
STATISTIC (NumRewrittenCopies , "Number of copies rewritten")
References llvm::PassRegistry::getPassRegistry(), and TII.
STATISTIC() [6/7]
STATISTIC (NumSelects , "Number of selects optimized")
STATISTIC() [7/7]
STATISTIC (NumUncoalescableCopies , "Number of uncoalescable copies optimized")
Variable Documentation
Aggressive
cl::opt< bool > Aggressive("aggressive-ext-opt", cl::Hidden, cl::desc("Aggressive extension optimization")) ("aggressive-ext-opt" , cl::Hidden , cl::desc("Aggressive extension optimization")) static
DisableAdvCopyOpt
cl::opt< bool > DisableAdvCopyOpt("disable-adv-copy-opt", cl::Hidden, cl::init(false), cl::desc("Disable advanced copy optimization")) ("disable-adv-copy-opt" , cl::Hidden , cl::init(false) , cl::desc("Disable advanced copy optimization")) static
DisablePeephole
cl::opt< bool > DisablePeephole("disable-peephole", cl::Hidden, cl::init(false), cl::desc("Disable the peephole optimizer")) ("disable-peephole" , cl::Hidden , cl::init(false) , cl::desc("Disable the peephole optimizer")) static
false
peephole Peephole false
Definition at line 303 of file PeepholeOptimizer.cpp.
Optimizations
peephole Peephole Optimizations
Definition at line 303 of file PeepholeOptimizer.cpp.
opts
peephole opts
Definition at line 302 of file PeepholeOptimizer.cpp.