LLVM: PPCAsmParser.cpp File Reference
LLVM API Documentation
PPCAsmParser.cpp File Reference
#include "MCTargetDesc/PPCMCTargetDesc.h"
#include "MCTargetDesc/PPCMCExpr.h"
#include "PPCTargetStreamer.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCTargetAsmParser.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "PPCGenAsmMatcher.inc"
Macros
#define GET_REGISTER_MATCHER
#define GET_MATCHER_IMPLEMENTATION
Auto-generated Match Functions
{
#define GET_ASSEMBLER_HEADER
Functions
static int64_t EvaluateCRExpr (const MCExpr *E)
static void addNegOperand (MCInst &Inst, MCOperand &Op, MCContext &Ctx)
void LLVMInitializePowerPCAsmParser ()
Force static initialization.
Variables
static const MCPhysReg RRegs [32]
static const MCPhysReg RRegsNoR0 [32]
static const MCPhysReg XRegs [32]
static const MCPhysReg XRegsNoX0 [32]
static const MCPhysReg FRegs [32]
static const MCPhysReg VRegs [32]
static const MCPhysReg VSRegs [64]
static const MCPhysReg VSFRegs [64]
static const MCPhysReg CRBITRegs [32]
static const MCPhysReg CRRegs [8]
Macro Definition Documentation
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 257 of file PPCAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 1740 of file PPCAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 1739 of file PPCAsmParser.cpp.
Function Documentation
addNegOperand()
void addNegOperand (MCInst & Inst, MCOperand & Op, MCContext & Ctx) static
Definition at line 750 of file PPCAsmParser.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateExpr(), llvm::MCOperand::CreateImm(), llvm::MCUnaryExpr::CreateMinus(), llvm::MCBinaryExpr::CreateSub(), llvm::dyn_cast(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::isImm(), llvm::MCUnaryExpr::Minus, and llvm::MCBinaryExpr::Sub.
EvaluateCRExpr()
int64_t EvaluateCRExpr (const MCExpr * E) static
Definition at line 154 of file PPCAsmParser.cpp.
References llvm::MCBinaryExpr::Add, llvm::MCExpr::Binary, llvm::cast(), llvm::MCExpr::Constant, EvaluateCRExpr(), llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCSymbol::getName(), llvm::MCBinaryExpr::getOpcode(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbolRefExpr::getSymbol(), llvm_unreachable, llvm::MCBinaryExpr::Mul, Name, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.
Referenced by EvaluateCRExpr().
LLVMInitializePowerPCAsmParser()
void LLVMInitializePowerPCAsmParser ()
Force static initialization.
Definition at line 1733 of file PPCAsmParser.cpp.
References llvm::ThePPC32Target, llvm::ThePPC64LETarget, and llvm::ThePPC64Target.
Variable Documentation
CRBITRegs
const MCPhysReg CRBITRegs[32] static
Initial value:
= {
  PPC::CR0LT, PPC::CR0GT, PPC::CR0EQ, PPC::CR0UN,
  PPC::CR1LT, PPC::CR1GT, PPC::CR1EQ, PPC::CR1UN,
  PPC::CR2LT, PPC::CR2GT, PPC::CR2EQ, PPC::CR2UN,
  PPC::CR3LT, PPC::CR3GT, PPC::CR3EQ, PPC::CR3UN,
  PPC::CR4LT, PPC::CR4GT, PPC::CR4EQ, PPC::CR4UN,
  PPC::CR5LT, PPC::CR5GT, PPC::CR5EQ, PPC::CR5UN,
  PPC::CR6LT, PPC::CR6GT, PPC::CR6EQ, PPC::CR6UN,
  PPC::CR7LT, PPC::CR7GT, PPC::CR7EQ, PPC::CR7UN
}
Definition at line 135 of file PPCAsmParser.cpp.
Referenced by DecodeCRBITRCRegisterClass().
CRRegs
const MCPhysReg CRRegs[8] static
Initial value:
= {
  PPC::CR0, PPC::CR1, PPC::CR2, PPC::CR3,
  PPC::CR4, PPC::CR5, PPC::CR6, PPC::CR7
}
Definition at line 145 of file PPCAsmParser.cpp.
Referenced by decodeCRBitMOperand(), and DecodeCRRCRegisterClass().
FRegs
const MCPhysReg FRegs[32] static
Initial value:
= {
  PPC::F0,  PPC::F1,  PPC::F2,  PPC::F3,
  PPC::F4,  PPC::F5,  PPC::F6,  PPC::F7,
  PPC::F8,  PPC::F9,  PPC::F10, PPC::F11,
  PPC::F12, PPC::F13, PPC::F14, PPC::F15,
  PPC::F16, PPC::F17, PPC::F18, PPC::F19,
  PPC::F20, PPC::F21, PPC::F22, PPC::F23,
  PPC::F24, PPC::F25, PPC::F26, PPC::F27,
  PPC::F28, PPC::F29, PPC::F30, PPC::F31
}
Definition at line 77 of file PPCAsmParser.cpp.
Referenced by DecodeF4RCRegisterClass(), and DecodeF8RCRegisterClass().
RRegs
const MCPhysReg RRegs[32] static
Initial value:
= {
  PPC::R0,  PPC::R1,  PPC::R2,  PPC::R3,
  PPC::R4,  PPC::R5,  PPC::R6,  PPC::R7,
  PPC::R8,  PPC::R9,  PPC::R10, PPC::R11,
  PPC::R12, PPC::R13, PPC::R14, PPC::R15,
  PPC::R16, PPC::R17, PPC::R18, PPC::R19,
  PPC::R20, PPC::R21, PPC::R22, PPC::R23,
  PPC::R24, PPC::R25, PPC::R26, PPC::R27,
  PPC::R28, PPC::R29, PPC::R30, PPC::R31
}
Definition at line 35 of file PPCAsmParser.cpp.
RRegsNoR0
const MCPhysReg RRegsNoR0[32] static
Initial value:
= {
  PPC::ZERO,
            PPC::R1,  PPC::R2,  PPC::R3,
  PPC::R4,  PPC::R5,  PPC::R6,  PPC::R7,
  PPC::R8,  PPC::R9,  PPC::R10, PPC::R11,
  PPC::R12, PPC::R13, PPC::R14, PPC::R15,
  PPC::R16, PPC::R17, PPC::R18, PPC::R19,
  PPC::R20, PPC::R21, PPC::R22, PPC::R23,
  PPC::R24, PPC::R25, PPC::R26, PPC::R27,
  PPC::R28, PPC::R29, PPC::R30, PPC::R31
}
Definition at line 45 of file PPCAsmParser.cpp.
VRegs
const MCPhysReg VRegs[32] static
Initial value:
= {
  PPC::V0,  PPC::V1,  PPC::V2,  PPC::V3,
  PPC::V4,  PPC::V5,  PPC::V6,  PPC::V7,
  PPC::V8,  PPC::V9,  PPC::V10, PPC::V11,
  PPC::V12, PPC::V13, PPC::V14, PPC::V15,
  PPC::V16, PPC::V17, PPC::V18, PPC::V19,
  PPC::V20, PPC::V21, PPC::V22, PPC::V23,
  PPC::V24, PPC::V25, PPC::V26, PPC::V27,
  PPC::V28, PPC::V29, PPC::V30, PPC::V31
}
Definition at line 87 of file PPCAsmParser.cpp.
Referenced by DecodeVRRCRegisterClass(), and llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized().
VSFRegs
const MCPhysReg VSFRegs[64] static
Initial value:
= {
  PPC::F0,  PPC::F1,  PPC::F2,  PPC::F3,
  PPC::F4,  PPC::F5,  PPC::F6,  PPC::F7,
  PPC::F8,  PPC::F9,  PPC::F10, PPC::F11,
  PPC::F12, PPC::F13, PPC::F14, PPC::F15,
  PPC::F16, PPC::F17, PPC::F18, PPC::F19,
  PPC::F20, PPC::F21, PPC::F22, PPC::F23,
  PPC::F24, PPC::F25, PPC::F26, PPC::F27,
  PPC::F28, PPC::F29, PPC::F30, PPC::F31,
  PPC::VF0,  PPC::VF1,  PPC::VF2,  PPC::VF3,
  PPC::VF4,  PPC::VF5,  PPC::VF6,  PPC::VF7,
  PPC::VF8,  PPC::VF9,  PPC::VF10, PPC::VF11,
  PPC::VF12, PPC::VF13, PPC::VF14, PPC::VF15,
  PPC::VF16, PPC::VF17, PPC::VF18, PPC::VF19,
  PPC::VF20, PPC::VF21, PPC::VF22, PPC::VF23,
  PPC::VF24, PPC::VF25, PPC::VF26, PPC::VF27,
  PPC::VF28, PPC::VF29, PPC::VF30, PPC::VF31
}
Definition at line 116 of file PPCAsmParser.cpp.
Referenced by DecodeVSFRCRegisterClass().
VSRegs
const MCPhysReg VSRegs[64] static
Initial value:
= {
  PPC::VSL0,  PPC::VSL1,  PPC::VSL2,  PPC::VSL3,
  PPC::VSL4,  PPC::VSL5,  PPC::VSL6,  PPC::VSL7,
  PPC::VSL8,  PPC::VSL9,  PPC::VSL10, PPC::VSL11,
  PPC::VSL12, PPC::VSL13, PPC::VSL14, PPC::VSL15,
  PPC::VSL16, PPC::VSL17, PPC::VSL18, PPC::VSL19,
  PPC::VSL20, PPC::VSL21, PPC::VSL22, PPC::VSL23,
  PPC::VSL24, PPC::VSL25, PPC::VSL26, PPC::VSL27,
  PPC::VSL28, PPC::VSL29, PPC::VSL30, PPC::VSL31,
  PPC::VSH0,  PPC::VSH1,  PPC::VSH2,  PPC::VSH3,
  PPC::VSH4,  PPC::VSH5,  PPC::VSH6,  PPC::VSH7,
  PPC::VSH8,  PPC::VSH9,  PPC::VSH10, PPC::VSH11,
  PPC::VSH12, PPC::VSH13, PPC::VSH14, PPC::VSH15,
  PPC::VSH16, PPC::VSH17, PPC::VSH18, PPC::VSH19,
  PPC::VSH20, PPC::VSH21, PPC::VSH22, PPC::VSH23,
  PPC::VSH24, PPC::VSH25, PPC::VSH26, PPC::VSH27,
  PPC::VSH28, PPC::VSH29, PPC::VSH30, PPC::VSH31
}
Definition at line 97 of file PPCAsmParser.cpp.
Referenced by DecodeVSRCRegisterClass().
XRegs
const MCPhysReg XRegs[32] static
Initial value:
= {
  PPC::X0,  PPC::X1,  PPC::X2,  PPC::X3,
  PPC::X4,  PPC::X5,  PPC::X6,  PPC::X7,
  PPC::X8,  PPC::X9,  PPC::X10, PPC::X11,
  PPC::X12, PPC::X13, PPC::X14, PPC::X15,
  PPC::X16, PPC::X17, PPC::X18, PPC::X19,
  PPC::X20, PPC::X21, PPC::X22, PPC::X23,
  PPC::X24, PPC::X25, PPC::X26, PPC::X27,
  PPC::X28, PPC::X29, PPC::X30, PPC::X31
}
Definition at line 56 of file PPCAsmParser.cpp.
XRegsNoX0
const MCPhysReg XRegsNoX0[32] static
Initial value:
= {
  PPC::ZERO8,
            PPC::X1,  PPC::X2,  PPC::X3,
  PPC::X4,  PPC::X5,  PPC::X6,  PPC::X7,
  PPC::X8,  PPC::X9,  PPC::X10, PPC::X11,
  PPC::X12, PPC::X13, PPC::X14, PPC::X15,
  PPC::X16, PPC::X17, PPC::X18, PPC::X19,
  PPC::X20, PPC::X21, PPC::X22, PPC::X23,
  PPC::X24, PPC::X25, PPC::X26, PPC::X27,
  PPC::X28, PPC::X29, PPC::X30, PPC::X31
}
Definition at line 66 of file PPCAsmParser.cpp.