LLVM: PPCCTRLoops.cpp File Reference
LLVM API Documentation
PPCCTRLoops.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "PPC.h"
#include "PPCTargetMachine.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/ScalarEvolutionExpander.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/PassSupport.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include <algorithm>
#include <vector>
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "ctrloops"
Functions
STATISTIC (NumCTRLoops, "Number of loops converted to CTR loops")
void llvm::initializePPCCTRLoopsPass (PassRegistry &)
void llvm::initializePPCCTRLoopsVerifyPass (PassRegistry &)
INITIALIZE_PASS_BEGIN (PPCCTRLoops, "ppc-ctr-loops", "PowerPC CTR Loops", false, false) INITIALIZE_PASS_END(PPCCTRLoops
INITIALIZE_PASS_BEGIN (PPCCTRLoopsVerify, "ppc-ctr-loops-verify", "PowerPC CTR Loops Verify", false, false) INITIALIZE_PASS_END(PPCCTRLoopsVerify
static bool isLargeIntegerTy (bool Is32Bit, Type *Ty)
static bool memAddrUsesCTR (const PPCTargetMachine *TM, const llvm::Value *MemAddr)
static bool clobbersCTR (const MachineInstr *MI)
static bool verifyCTRBranch (MachineBasicBlock *MBB, MachineBasicBlock::iterator I)
Variables
static cl::opt< int > CTRLoopLimit ("ppc-max-ctrloop", cl::Hidden, cl::init(-1))
ppc ctr loops
ppc ctr PowerPC CTR Loops
ppc ctr PowerPC CTR false
ppc ctr loops verify
ppc ctr loops PowerPC CTR Loops Verify
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ctrloops"
Definition at line 62 of file PPCCTRLoops.cpp.
Function Documentation
clobbersCTR()
bool clobbersCTR (const MachineInstr * MI) static
Definition at line 572 of file PPCCTRLoops.cpp.
References llvm::MachineOperand::clobbersPhysReg(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), and llvm::MachineOperand::isRegMask().
Referenced by verifyCTRBranch().
INITIALIZE_PASS_BEGIN() [1/2]
INITIALIZE_PASS_BEGIN (PPCCTRLoops , "ppc-ctr-loops" , "PowerPC CTR Loops" , false , false)
References INITIALIZE_PASS_DEPENDENCY.
INITIALIZE_PASS_BEGIN() [2/2]
INITIALIZE_PASS_BEGIN (PPCCTRLoopsVerify , "ppc-ctr-loops-verify" , "PowerPC CTR Loops Verify" , false , false)
References INITIALIZE_PASS_DEPENDENCY.
isLargeIntegerTy()
bool isLargeIntegerTy (bool Is32Bit, Type * Ty) static
Definition at line 190 of file PPCCTRLoops.cpp.
References llvm::dyn_cast().
memAddrUsesCTR()
bool memAddrUsesCTR (const PPCTargetMachine * TM, const llvm::Value * MemAddr) static
Definition at line 199 of file PPCCTRLoops.cpp.
References llvm::dyn_cast(), llvm::TLSModel::GeneralDynamic, and llvm::TLSModel::LocalDynamic.
STATISTIC()
STATISTIC (NumCTRLoops , "Number of loops converted to CTR loops")
verifyCTRBranch()
bool verifyCTRBranch (MachineBasicBlock * MBB, MachineBasicBlock::iterator I) static
Definition at line 587 of file PPCCTRLoops.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), clobbersCTR(), llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getFullName(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), I, llvm::SmallSet< T, N, C >::insert(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Variable Documentation
CTRLoopLimit
cl::opt< int > CTRLoopLimit("ppc-max-ctrloop", cl::Hidden, cl::init(-1)) ("ppc-max-ctrloop" , cl::Hidden , cl::init(-1)) static
false
ppc ctr loops PowerPC CTR Loops false
Definition at line 152 of file PPCCTRLoops.cpp.
Loops
ppc ctr PowerPC CTR Loops
Definition at line 151 of file PPCCTRLoops.cpp.
loops
ppc ctr loops
Definition at line 151 of file PPCCTRLoops.cpp.
Verify
ppc ctr loops PowerPC CTR Loops Verify
Definition at line 163 of file PPCCTRLoops.cpp.
Referenced by llvm::BuildMI(), llvm::BuildMI(), llvm::cleanseInlinedVariable(), llvm::createInlinedVariable(), llvm::EngineBuilder::setVerifyModules(), llvm::ExecutionEngine::setVerifyModules(), and llvm::DebugLocEntry::Value::Value().
verify
ppc ctr loops verify
Definition at line 162 of file PPCCTRLoops.cpp.