LLVM: PPCInstrInfo.cpp File Reference
LLVM API Documentation
PPCInstrInfo.cpp File Reference
#include "PPCInstrInfo.h"
#include "MCTargetDesc/PPCPredicates.h"
#include "PPC.h"
#include "PPCHazardRecognizers.h"
#include "PPCInstrBuilder.h"
#include "PPCMachineFunctionInfo.h"
#include "PPCTargetMachine.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LiveIntervalAnalysis.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/CodeGen/SlotIndexes.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "PPCGenInstrInfo.inc"
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "ppc-instr-info"
#define GET_INSTRMAP_INFO
#define GET_INSTRINFO_CTOR_DTOR
#define DEBUG_TYPE "ppc-vsx-fma-mutate"
#define DEBUG_TYPE "ppc-vsx-copy"
#define DEBUG_TYPE "ppc-vsx-copy-cleanup"
#define DEBUG_TYPE "ppc-early-ret"
Functions
static bool MBBDefinesCTR (MachineBasicBlock &MBB)
INITIALIZE_PASS_BEGIN (PPCVSXFMAMutate, DEBUG_TYPE, "PowerPC VSX FMA Mutation", false, false) INITIALIZE_PASS_END(PPCVSXFMAMutate
void llvm::initializePPCVSXCopyPass (PassRegistry &)
void llvm::initializePPCVSXCopyCleanupPass (PassRegistry &)
STATISTIC (NumBCLR, "Number of early conditional returns")
STATISTIC (NumBLR, "Number of early returns")
void llvm::initializePPCEarlyReturnPass (PassRegistry &)
Variables
static cl::opt< bool > DisableCTRLoopAnal ("disable-ppc-ctrloop-analysis", cl::Hidden, cl::desc("Disable analysis for CTR loops"))
static cl::opt< bool > DisableCmpOpt ("disable-ppc-cmp-opt", cl::desc("Disable compare instruction optimization"), cl::Hidden)
static cl::opt< bool > DisableVSXFMAMutate ("disable-ppc-vsx-fma-mutation", cl::desc("Disable VSX FMA instruction mutation"), cl::Hidden)
static cl::opt< bool > VSXSelfCopyCrash ("crash-on-ppc-vsx-self-copy", cl::desc("Causes the backend to crash instead of generating a nop VSX copy"), cl::Hidden)
DEBUG_TYPE
PowerPC VSX FMA Mutation
PowerPC VSX FMA false
Macro Definition Documentation
DEBUG_TYPE [1/5]
#define DEBUG_TYPE "ppc-instr-info"
Definition at line 42 of file PPCInstrInfo.cpp.
DEBUG_TYPE [2/5]
#define DEBUG_TYPE "ppc-vsx-fma-mutate"
Definition at line 42 of file PPCInstrInfo.cpp.
DEBUG_TYPE [3/5]
#define DEBUG_TYPE "ppc-vsx-copy"
Definition at line 42 of file PPCInstrInfo.cpp.
DEBUG_TYPE [4/5]
#define DEBUG_TYPE "ppc-vsx-copy-cleanup"
Definition at line 42 of file PPCInstrInfo.cpp.
DEBUG_TYPE [5/5]
#define DEBUG_TYPE "ppc-early-ret"
Definition at line 42 of file PPCInstrInfo.cpp.
GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 45 of file PPCInstrInfo.cpp.
GET_INSTRMAP_INFO
#define GET_INSTRMAP_INFO
Definition at line 44 of file PPCInstrInfo.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (PPCVSXFMAMutate , DEBUG_TYPE , "PowerPC VSX FMA Mutation" , false , false)
References DEBUG_TYPE, and INITIALIZE_PASS_DEPENDENCY.
MBBDefinesCTR()
bool MBBDefinesCTR (MachineBasicBlock & MBB) static
Definition at line 1068 of file PPCInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), and I.
Referenced by llvm::PPCInstrInfo::isProfitableToIfCvt().
STATISTIC() [1/2]
STATISTIC (NumBCLR , "Number of early conditional returns")
STATISTIC() [2/2]
STATISTIC (NumBLR , "Number of early returns")
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 1892 of file PPCInstrInfo.cpp.
DisableCmpOpt
cl::opt< bool > DisableCmpOpt("disable-ppc-cmp-opt", cl::desc("Disable compare instruction optimization"), cl::Hidden) ("disable-ppc-cmp-opt" , cl::desc("Disable compare instruction optimization") , cl::Hidden) static
Referenced by llvm::PPCInstrInfo::optimizeCompareInstr().
DisableCTRLoopAnal
cl::opt< bool > DisableCTRLoopAnal("disable-ppc-ctrloop-analysis", cl::Hidden, cl::desc("Disable analysis for CTR loops")) ("disable-ppc-ctrloop-analysis" , cl::Hidden , cl::desc("Disable analysis for CTR loops")) static
Referenced by llvm::PPCInstrInfo::AnalyzeBranch().
DisableVSXFMAMutate
cl::opt< bool > DisableVSXFMAMutate("disable-ppc-vsx-fma-mutation", cl::desc("Disable VSX FMA instruction mutation"), cl::Hidden) ("disable-ppc-vsx-fma-mutation" , cl::desc("Disable VSX FMA instruction mutation") , cl::Hidden) static
false
PowerPC VSX FMA false
Definition at line 1893 of file PPCInstrInfo.cpp.
Mutation
PowerPC VSX FMA Mutation
Definition at line 1893 of file PPCInstrInfo.cpp.
Referenced by llvm::ScheduleDAGMI::addMutation().
VSXSelfCopyCrash
cl::opt< bool > VSXSelfCopyCrash("crash-on-ppc-vsx-self-copy", cl::desc("Causes the backend to crash instead of generating a nop VSX copy"), cl::Hidden) ("crash-on-ppc-vsx-self-copy" , cl::desc("Causes the backend to crash instead of generating a nop VSX copy") , cl::Hidden) static
Referenced by llvm::PPCInstrInfo::copyPhysReg().