LLVM: PPCISelDAGToDAG.cpp File Reference
LLVM API Documentation
PPCISelDAGToDAG.cpp File Reference
#include "PPC.h"
#include "MCTargetDesc/PPCPredicates.h"
#include "PPCMachineFunctionInfo.h"
#include "PPCTargetMachine.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetOptions.h"
#include "PPCGenDAGISel.inc"
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "ppc-codegen"
Functions
void llvm::initializePPCDAGToDAGISelPass (PassRegistry &)
static bool isIntS16Immediate (SDNode *N, short &Imm)
static bool isIntS16Immediate (SDValue Op, short &Imm)
static bool isInt32Immediate (SDNode *N, unsigned &Imm)
static bool isInt64Immediate (SDNode *N, uint64_t &Imm)
static bool isInt32Immediate (SDValue N, unsigned &Imm)
static bool isOpcWithIntImmediate (SDNode *N, unsigned Opc, unsigned &Imm)
static unsigned SelectInt64CountDirect (int64_t Imm)
static uint64_t Rot64 (uint64_t Imm, unsigned R)
static unsigned SelectInt64Count (int64_t Imm)
static SDNode * SelectInt64Direct (SelectionDAG *CurDAG, SDLoc dl, int64_t Imm)
static SDNode * SelectInt64 (SelectionDAG *CurDAG, SDLoc dl, int64_t Imm)
static SDNode * SelectInt64 (SelectionDAG *CurDAG, SDNode *N)
static PPC::Predicate getPredicateForSetCC (ISD::CondCode CC)
static unsigned getCRIdxForSetCC (ISD::CondCode CC, bool &Invert)
static unsigned int getVCmpInst (MVT VecVT, ISD::CondCode CC, bool HasVSX, bool &Swap, bool &Negate)
static bool PeepholePPC64ZExtGather (SDValue Op32, SmallPtrSetImpl< SDNode * > &ToPromote)
static void initializePassOnce (PassRegistry &Registry)
Variables
cl::opt< bool > ANDIGlueBug ("expose-ppc-andi-glue-bug", cl::desc("expose the ANDI glue bug on PPC"), cl::Hidden)
cl::opt< bool > UseBitPermRewriter ("ppc-use-bit-perm-rewriter", cl::init(true), cl::desc("use aggressive ppc isel for bit permutations"), cl::Hidden)
cl::opt< bool > BPermRewriterNoMasking ("ppc-bit-perm-rewriter-stress-rotates", cl::desc("stress rotate selection in aggressive ppc isel for " "bit permutations"), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ppc-codegen"
Definition at line 39 of file PPCISelDAGToDAG.cpp.
Function Documentation
getCRIdxForSetCC()
unsigned getCRIdxForSetCC (ISD::CondCode CC, bool & Invert) static
getCRIdxForSetCC - Return the index of the condition register field associated with the SetCC condition, and whether or not the field is treated as inverted. That is, lt = 0; ge = 0 inverted.
Definition at line 2073 of file PPCISelDAGToDAG.cpp.
References llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, and llvm::ISD::SETUO.
getPredicateForSetCC()
PPC::Predicate getPredicateForSetCC (ISD::CondCode CC) static
Definition at line 2042 of file PPCISelDAGToDAG.cpp.
References llvm_unreachable, llvm::PPC::PRED_EQ, llvm::PPC::PRED_GE, llvm::PPC::PRED_GT, llvm::PPC::PRED_LE, llvm::PPC::PRED_LT, llvm::PPC::PRED_NE, llvm::PPC::PRED_NU, llvm::PPC::PRED_UN, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, and llvm::ISD::SETUO.
getVCmpInst()
unsigned int getVCmpInst (MVT VecVT, ISD::CondCode CC, bool HasVSX, bool & Swap, bool & Negate) static
Definition at line 2105 of file PPCISelDAGToDAG.cpp.
References llvm::MVT::isFloatingPoint(), llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v4f32, llvm::MVT::v4i32, and llvm::MVT::v8i16.
initializePassOnce()
void initializePassOnce (PassRegistry & Registry) static
Definition at line 4233 of file PPCISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::ID, and Name.
isInt32Immediate() [1/2]
bool isInt32Immediate (SDNode * N, unsigned & Imm) static
isInt32Immediate - This method tests to see if the node is a 32-bit constant operand. If so Imm will receive the 32-bit value.
Definition at line 358 of file PPCISelDAGToDAG.cpp.
References llvm::cast(), llvm::ISD::Constant, llvm::MVT::i32, and N.
isInt32Immediate() [2/2]
bool isInt32Immediate (SDValue N, unsigned & Imm) static
Definition at line 378 of file PPCISelDAGToDAG.cpp.
References isInt32Immediate(), and N.
isInt64Immediate()
bool isInt64Immediate (SDNode * N, uint64_t & Imm) static
isInt64Immediate - This method tests to see if the node is a 64-bit constant operand. If so Imm will receive the 64-bit value.
Definition at line 368 of file PPCISelDAGToDAG.cpp.
References llvm::cast(), llvm::ISD::Constant, llvm::MVT::i64, and N.
isIntS16Immediate() [1/2]
bool isIntS16Immediate (SDNode * N, short & Imm) static
isIntS16Immediate - This method tests to see if the node is either a 32-bit or 64-bit immediate, and if the value can be accurately represented as a sign extension from a 16-bit value. If so, this returns true and the immediate.
Definition at line 340 of file PPCISelDAGToDAG.cpp.
References llvm::cast(), llvm::ISD::Constant, llvm::MVT::i32, and N.
Referenced by isIntS16Immediate(), isIntS16Immediate(), llvm::PPCTargetLowering::SelectAddressRegImm(), and llvm::PPCTargetLowering::SelectAddressRegReg().
isIntS16Immediate() [2/2]
bool isIntS16Immediate (SDValue Op, short & Imm) static
Definition at line 351 of file PPCISelDAGToDAG.cpp.
References llvm::SDValue::getNode(), and isIntS16Immediate().
isOpcWithIntImmediate()
bool isOpcWithIntImmediate (SDNode * N, unsigned Opc, unsigned & Imm) static
Definition at line 386 of file PPCISelDAGToDAG.cpp.
References isInt32Immediate(), and N.
PeepholePPC64ZExtGather()
bool PeepholePPC64ZExtGather (SDValue Op32, SmallPtrSetImpl< SDNode * > & ToPromote) static
Definition at line 3768 of file PPCISelDAGToDAG.cpp.
References llvm::SmallPtrSetImpl< PtrType >::begin(), llvm::SmallPtrSetImpl< PtrType >::end(), llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getMachineOpcode(), llvm::SDValue::getNode(), llvm::SDValue::getOperand(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SDValue::isMachineOpcode(), llvm::isUInt(), and PeepholePPC64ZExtGather().
Referenced by PeepholePPC64ZExtGather().
Rot64()
uint64_t Rot64 (uint64_t Imm, unsigned R) static
Definition at line 607 of file PPCISelDAGToDAG.cpp.
Referenced by SelectInt64(), and SelectInt64Count().
SelectInt64() [1/2]
SDNode * SelectInt64 (SelectionDAG * CurDAG, SDLoc dl, int64_t Imm) static
Definition at line 712 of file PPCISelDAGToDAG.cpp.
References llvm::findLastSet(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, llvm::MVT::i64, Rot64(), SelectInt64CountDirect(), and SelectInt64Direct().
Referenced by SelectInt64().
SelectInt64() [2/2]
SDNode * SelectInt64 (SelectionDAG * CurDAG, SDNode * N) static
Definition at line 769 of file PPCISelDAGToDAG.cpp.
References llvm::cast(), N, and SelectInt64().
SelectInt64Count()
unsigned SelectInt64Count (int64_t Imm) static
Definition at line 611 of file PPCISelDAGToDAG.cpp.
References llvm::findLastSet(), Rot64(), and SelectInt64CountDirect().
SelectInt64CountDirect()
unsigned SelectInt64CountDirect (int64_t Imm) static
Definition at line 549 of file PPCISelDAGToDAG.cpp.
References llvm::countTrailingZeros(), and llvm::isInt().
Referenced by SelectInt64(), and SelectInt64Count().
SelectInt64Direct()
SDNode * SelectInt64Direct (SelectionDAG * CurDAG, SDLoc dl, int64_t Imm) static
Definition at line 638 of file PPCISelDAGToDAG.cpp.
References llvm::countTrailingZeros(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i32, llvm::MVT::i64, and llvm::isInt().
Referenced by SelectInt64().
Variable Documentation
ANDIGlueBug
cl::opt< bool > ANDIGlueBug("expose-ppc-andi-glue-bug", cl::desc("expose the ANDI glue bug on PPC"), cl::Hidden) ("expose-ppc-andi-glue-bug" , cl::desc("expose the ANDI glue bug on PPC") , cl::Hidden)
Referenced by llvm::PPCTargetLowering::PPCTargetLowering().
BPermRewriterNoMasking
cl::opt< bool > BPermRewriterNoMasking("ppc-bit-perm-rewriter-stress-rotates", cl::desc("stress rotate selection in aggressive ppc isel for " "bit permutations"), cl::Hidden) ("ppc-bit-perm-rewriter-stress-rotates" , cl::desc("stress rotate selection in aggressive ppc isel for " "bit permutations") , cl::Hidden)
UseBitPermRewriter
cl::opt< bool > UseBitPermRewriter("ppc-use-bit-perm-rewriter", cl::init(true), cl::desc("use aggressive ppc isel for bit permutations"), cl::Hidden) ("ppc-use-bit-perm-rewriter" , cl::init(true) , cl::desc("use aggressive ppc isel for bit permutations") , cl::Hidden)