LLVM: PPCSubtarget.cpp File Reference
LLVM API Documentation
PPCSubtarget.cpp File Reference
#include "PPCSubtarget.h"
#include "PPC.h"
#include "PPCRegisterInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineScheduler.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetMachine.h"
#include <cstdlib>
#include "PPCGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "ppc-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Functions
static std::string getDataLayoutString (const Triple &T)
Return the datalayout string of a subtarget.
static bool needsAggressiveScheduling (unsigned Directive)
Variables
static cl::opt< bool > UseSubRegLiveness ("ppc-track-subreg-liveness", cl::desc("Enable subregister liveness tracking for PPC"), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ppc-subtarget"
Definition at line 30 of file PPCSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 33 of file PPCSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 32 of file PPCSubtarget.cpp.
Function Documentation
getDataLayoutString()
std::string getDataLayoutString (const Triple & T) static
Return the datalayout string of a subtarget.
Definition at line 40 of file PPCSubtarget.cpp.
References llvm::DataLayout::getManglingComponent(), is64Bit(), llvm::Triple::Lv2, llvm::Triple::ppc64, llvm::Triple::ppc64le, and T.
Referenced by llvm::PPCSubtarget::PPCSubtarget().
needsAggressiveScheduling()
bool needsAggressiveScheduling (unsigned Directive) static
Definition at line 189 of file PPCSubtarget.cpp.
References llvm::PPC::DIR_440, llvm::PPC::DIR_A2, llvm::PPC::DIR_E500mc, llvm::PPC::DIR_E5500, llvm::PPC::DIR_PWR7, and llvm::PPC::DIR_PWR8.
Referenced by llvm::PPCSubtarget::enableMachineScheduler(), llvm::PPCSubtarget::overrideSchedPolicy(), and llvm::PPCSubtarget::useAA().
Variable Documentation
UseSubRegLiveness
cl::opt< bool > UseSubRegLiveness("ppc-track-subreg-liveness", cl::desc("Enable subregister liveness tracking for PPC"), cl::Hidden) ("ppc-track-subreg-liveness" , cl::desc("Enable subregister liveness tracking for PPC") , cl::Hidden) static
Referenced by llvm::PPCSubtarget::enableSubRegLiveness().