LLVM: PrettyStackTrace.cpp File Reference
LLVM API Documentation
PrettyStackTrace.cpp File Reference
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm-c/Core.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Config/config.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/ThreadLocal.h"
#include "llvm/Support/Watchdog.h"
#include "llvm/Support/raw_ostream.h"
Functions
static unsigned PrintStack (const PrettyStackTraceEntry *Entry, raw_ostream &OS)
static void PrintCurStackTrace (raw_ostream &OS)
PrintCurStackTrace - Print the current stack trace to the specified stream.
static void CrashHandler (void *)
static bool RegisterCrashPrinter ()
void LLVMEnablePrettyStackTrace ()
Variables
static ManagedStatic< sys::ThreadLocal< const PrettyStackTraceEntry > > PrettyStackTraceHead
Function Documentation
CrashHandler()
void CrashHandler (void *) static
CrashHandler - This callback is run if a fatal signal is delivered to the process, it prints the pretty stack trace.
Definition at line 76 of file PrettyStackTrace.cpp.
References llvm::SmallVectorBase::empty(), llvm::errs(), PrintCurStackTrace(), and llvm::SmallString< InternalLen >::str().
Referenced by RegisterCrashPrinter().
PrintCurStackTrace()
void PrintCurStackTrace (raw_ostream & OS) static
PrintCurStackTrace - Print the current stack trace to the specified stream.
Definition at line 47 of file PrettyStackTrace.cpp.
References llvm::raw_ostream::flush(), PrettyStackTraceHead, and PrintStack().
Referenced by CrashHandler().
PrintStack()
unsigned PrintStack (const PrettyStackTraceEntry * Entry, raw_ostream & OS) static
Definition at line 33 of file PrettyStackTrace.cpp.
References llvm::PrettyStackTraceEntry::getNextEntry(), llvm::PrettyStackTraceEntry::print(), and PrintStack().
Referenced by PrintCurStackTrace(), and PrintStack().
RegisterCrashPrinter()
bool RegisterCrashPrinter () static
Definition at line 138 of file PrettyStackTrace.cpp.
References llvm::sys::AddSignalHandler(), and CrashHandler().
Referenced by llvm::EnablePrettyStackTrace().
Variable Documentation
PrettyStackTraceHead
ManagedStatic<sys::ThreadLocal<const PrettyStackTraceEntry> > PrettyStackTraceHead static
Definition at line 31 of file PrettyStackTrace.cpp.
Referenced by llvm::PrettyStackTraceEntry::PrettyStackTraceEntry(), PrintCurStackTrace(), and llvm::PrettyStackTraceEntry::~PrettyStackTraceEntry().