LLVM: RegAllocPBQP.cpp File Reference
LLVM API Documentation
RegAllocPBQP.cpp File Reference
#include "llvm/CodeGen/RegAllocPBQP.h"
#include "RegisterCoalescer.h"
#include "Spiller.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/CalcSpillWeights.h"
#include "llvm/CodeGen/LiveIntervalAnalysis.h"
#include "llvm/CodeGen/LiveRangeEdit.h"
#include "llvm/CodeGen/LiveStackAnalysis.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegAllocRegistry.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include <limits>
#include <memory>
#include <queue>
#include <set>
#include <sstream>
#include <vector>
Macros
#define DEBUG_TYPE "regalloc"
Functions
static bool isACalleeSavedRegister (unsigned reg, const TargetRegisterInfo &TRI, const MachineFunction &MF)
static float normalizePBQPSpillWeight (float UseDefFreq, unsigned Size, unsigned NumInstr)
Variables
static RegisterRegAlloc RegisterPBQPRepAlloc ("pbqp", "PBQP register allocator", createDefaultPBQPRegisterAllocator)
static cl::opt< bool > PBQPCoalescing ("pbqp-coalescing", cl::desc("Attempt coalescing during PBQP register allocation."), cl::init(false), cl::Hidden)
static cl::opt< bool > PBQPDumpGraphs ("pbqp-dump-graphs", cl::desc("Dump graphs for each function/round in the compilation unit."), cl::init(false), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "regalloc"
Definition at line 62 of file RegAllocPBQP.cpp.
Function Documentation
isACalleeSavedRegister()
bool isACalleeSavedRegister (unsigned reg, const TargetRegisterInfo & TRI, const MachineFunction & MF) static
Definition at line 482 of file RegAllocPBQP.cpp.
References llvm::TargetRegisterInfo::getCalleeSavedRegs(), and llvm::TargetRegisterInfo::regsOverlap().
normalizePBQPSpillWeight()
float normalizePBQPSpillWeight (float UseDefFreq, unsigned Size, unsigned NumInstr) inline static
Definition at line 629 of file RegAllocPBQP.cpp.
References llvm::normalizeSpillWeight().
Variable Documentation
PBQPCoalescing
cl::opt< bool > PBQPCoalescing("pbqp-coalescing", cl::desc("Attempt coalescing during PBQP register allocation."), cl::init(false), cl::Hidden) ("pbqp-coalescing" , cl::desc("Attempt coalescing during PBQP register allocation.") , cl::init(false) , cl::Hidden) static
PBQPDumpGraphs
cl::opt< bool > PBQPDumpGraphs("pbqp-dump-graphs", cl::desc("Dump graphs for each function/round in the compilation unit."), cl::init(false), cl::Hidden) ("pbqp-dump-graphs" , cl::desc("Dump graphs for each function/round in the compilation unit.") , cl::init(false) , cl::Hidden) static
RegisterPBQPRepAlloc
RegisterRegAlloc RegisterPBQPRepAlloc("pbqp", "PBQP register allocator", createDefaultPBQPRegisterAllocator) ("pbqp" , "PBQP register allocator" , createDefaultPBQPRegisterAllocator) static