LLVM: RegionPrinter.cpp File Reference
LLVM API Documentation
RegionPrinter.cpp File Reference
#include "llvm/Analysis/Passes.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/DOTGraphTraitsPass.h"
#include "llvm/Analysis/RegionInfo.h"
#include "llvm/Analysis/RegionIterator.h"
#include "llvm/Analysis/RegionPrinter.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct llvm::DOTGraphTraits< RegionNode * >
struct llvm::DOTGraphTraits< RegionInfoPass * >
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Functions
INITIALIZE_PASS (RegionPrinter, "dot-regions", "Print regions of function to 'dot' file", true, true) INITIALIZE_PASS(RegionViewer
view View regions of true INITIALIZE_PASS (RegionOnlyViewer, "view-regions-only", "View regions of function (with no function bodies)", true, true) namespace
INITIALIZE_PASS (RegionOnlyPrinter, "dot-regions-only", "Print regions of function to 'dot' file " "(with no function bodies)", true, true) FunctionPass *llvm
Variables
static cl::opt< bool > onlySimpleRegions ("only-simple-regions", cl::desc("Show only simple regions in the graphviz viewer"), cl::Hidden, cl::init(false))
onlySimpleRegion - Show only the simple regions in the RegionViewer.
view regions
view View regions of function
view View regions of true
Function Documentation
INITIALIZE_PASS() [1/3]
INITIALIZE_PASS (RegionOnlyPrinter , "dot-regions-only" , "Print regions of function to 'dot' file " "(with no function bodies)" , true , true)
Definition at line 200 of file RegionPrinter.cpp.
References llvm::createRegionViewerPass().
INITIALIZE_PASS() [2/3]
view View regions of true INITIALIZE_PASS (RegionOnlyViewer , "view-regions-only" , "View regions of function (with no function bodies)" , true , true)
Definition at line 182 of file RegionPrinter.cpp.
References llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::DOTGraphTraitsPrinter(), llvm::PassRegistry::getPassRegistry(), INITIALIZE_PASS, llvm::initializeRegionOnlyPrinterPass(), and true.
INITIALIZE_PASS() [3/3]
INITIALIZE_PASS (RegionPrinter , "dot-regions" , "Print regions of function to 'dot' file" , true , true)
Variable Documentation
function
view View regions of function
Definition at line 179 of file RegionPrinter.cpp.
onlySimpleRegions
cl::opt< bool > onlySimpleRegions("only-simple-regions", cl::desc("Show only simple regions in the graphviz viewer"), cl::Hidden, cl::init(false)) ("only-simple-regions" , cl::desc("Show only simple regions in the graphviz viewer") , cl::Hidden , cl::init(false)) static
onlySimpleRegion - Show only the simple regions in the RegionViewer.
Referenced by llvm::DOTGraphTraits< RegionInfoPass * >::printRegionCluster().
regions
view regions
Definition at line 179 of file RegionPrinter.cpp.
true
view View regions of true
Definition at line 180 of file RegionPrinter.cpp.