LLVM: SanitizerCoverage.cpp File Reference
LLVM API Documentation
SanitizerCoverage.cpp File Reference
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
Macros
#define DEBUG_TYPE "sancov"
Functions
static Function * checkInterfaceFunction (Constant *FuncOrBitcast)
INITIALIZE_PASS (SanitizerCoverageModule, "sancov", "SanitizerCoverage: TODO." "ModulePass", false, false) ModulePass *llvm
Variables
static const char *const kSanCovModuleInitName = "__sanitizer_cov_module_init"
static const char *const kSanCovName = "__sanitizer_cov"
static const char *const kSanCovIndirCallName = "__sanitizer_cov_indir_call16"
static const char *const kSanCovTraceEnter = "__sanitizer_cov_trace_func_enter"
static const char *const kSanCovTraceBB = "__sanitizer_cov_trace_basic_block"
static const char *const kSanCovModuleCtorName = "sancov.module_ctor"
static const uint64_t kSanCtorAndDtorPriority = 1
static cl::opt< int > ClCoverageLevel ("sanitizer-coverage-level", cl::desc("Sanitizer Coverage. 0: none, 1: entry block, 2: all blocks, " "3: all blocks and critical edges, " "4: above plus indirect calls"), cl::Hidden, cl::init(0))
static cl::opt< int > ClCoverageBlockThreshold ("sanitizer-coverage-block-threshold", cl::desc("Add coverage instrumentation only to the entry block if there " "are more than this number of blocks."), cl::Hidden, cl::init(1500))
static cl::opt< bool > ClExperimentalTracing ("sanitizer-coverage-experimental-tracing", cl::desc("Experimental basic-block tracing: insert " "callbacks at every basic block"), cl::Hidden, cl::init(false))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "sancov"
Definition at line 54 of file SanitizerCoverage.cpp.
Function Documentation
checkInterfaceFunction()
Function * checkInterfaceFunction (Constant * FuncOrBitcast) static
Definition at line 121 of file SanitizerCoverage.cpp.
References llvm::dyn_cast(), F, and llvm::report_fatal_error().
INITIALIZE_PASS()
INITIALIZE_PASS (SanitizerCoverageModule , "sancov" , "SanitizerCoverage: TODO." "ModulePass" , false , false)
Definition at line 309 of file SanitizerCoverage.cpp.
References llvm::createSanitizerCoverageModulePass().
Variable Documentation
ClCoverageBlockThreshold
cl::opt< int > ClCoverageBlockThreshold("sanitizer-coverage-block-threshold", cl::desc("Add coverage instrumentation only to the entry block if there " "are more than this number of blocks."), cl::Hidden, cl::init(1500)) ("sanitizer-coverage-block-threshold" , cl::desc("Add coverage instrumentation only to the entry block if there " "are more than this number of blocks.") , cl::Hidden , cl::init(1500)) static
ClCoverageLevel
cl::opt< int > ClCoverageLevel("sanitizer-coverage-level", cl::desc("Sanitizer Coverage. 0: none, 1: entry block, 2: all blocks, " "3: all blocks and critical edges, " "4: above plus indirect calls"), cl::Hidden, cl::init(0)) ("sanitizer-coverage-level" , cl::desc("Sanitizer Coverage. 0: none, 1: entry block, 2: all blocks, " "3: all blocks and critical edges, " "4: above plus indirect calls") , cl::Hidden , cl::init(0)) static
ClExperimentalTracing
cl::opt< bool > ClExperimentalTracing("sanitizer-coverage-experimental-tracing", cl::desc("Experimental basic-block tracing: insert " "callbacks at every basic block"), cl::Hidden, cl::init(false)) ("sanitizer-coverage-experimental-tracing" , cl::desc("Experimental basic-block tracing: insert " "callbacks at every basic block") , cl::Hidden , cl::init(false)) static
kSanCovIndirCallName
const char* const kSanCovIndirCallName = "__sanitizer_cov_indir_call16" static
Definition at line 58 of file SanitizerCoverage.cpp.
kSanCovModuleCtorName
const char* const kSanCovModuleCtorName = "sancov.module_ctor" static
Definition at line 61 of file SanitizerCoverage.cpp.
kSanCovModuleInitName
const char* const kSanCovModuleInitName = "__sanitizer_cov_module_init" static
Definition at line 56 of file SanitizerCoverage.cpp.
kSanCovName
const char* const kSanCovName = "__sanitizer_cov" static
Definition at line 57 of file SanitizerCoverage.cpp.
kSanCovTraceBB
const char* const kSanCovTraceBB = "__sanitizer_cov_trace_basic_block" static
Definition at line 60 of file SanitizerCoverage.cpp.
kSanCovTraceEnter
const char* const kSanCovTraceEnter = "__sanitizer_cov_trace_func_enter" static
Definition at line 59 of file SanitizerCoverage.cpp.
kSanCtorAndDtorPriority
const uint64_t kSanCtorAndDtorPriority = 1 static
Definition at line 62 of file SanitizerCoverage.cpp.