LLVM: SCCP.cpp File Reference
LLVM API Documentation
SCCP.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/IR/CallSite.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "sccp"
Functions
STATISTIC (NumInstRemoved, "Number of instructions removed")
STATISTIC (NumDeadBlocks, "Number of basic blocks unreachable")
STATISTIC (IPNumInstRemoved, "Number of instructions removed by IPSCCP")
STATISTIC (IPNumArgsElimed,"Number of arguments constant propagated by IPSCCP")
STATISTIC (IPNumGlobalConst, "Number of globals found to be constant by IPSCCP")
INITIALIZE_PASS (SCCP, "sccp", "Sparse Conditional Constant Propagation", false, false) FunctionPass *llvm
static void DeleteInstructionInBlock (BasicBlock *BB)
INITIALIZE_PASS_BEGIN (IPSCCP, "ipsccp", "Interprocedural Sparse Conditional Constant Propagation", false, false) INITIALIZE_PASS_END(IPSCCP
static bool AddressIsTaken (const GlobalValue *GV)
Variables
ipsccp
Interprocedural Sparse Conditional Constant Propagation
Interprocedural Sparse Conditional Constant false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "sccp"
Definition at line 44 of file SCCP.cpp.
Function Documentation
AddressIsTaken()
bool AddressIsTaken (const GlobalValue * GV) static
Definition at line 1665 of file SCCP.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::isa(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCallee(), llvm::Constant::removeDeadConstantUsers(), and llvm::Value::uses().
DeleteInstructionInBlock()
void DeleteInstructionInBlock (BasicBlock * BB) static
Definition at line 1530 of file SCCP.cpp.
References llvm::BasicBlock::begin(), llvm::dbgs(), DEBUG, llvm::iplist< NodeTy, Traits >::erase(), llvm::UndefValue::get(), llvm::BasicBlock::getInstList(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), I, llvm::isa(), llvm::Value::replaceAllUsesWith(), and llvm::Value::use_empty().
INITIALIZE_PASS()
INITIALIZE_PASS (SCCP , "sccp" , "Sparse Conditional Constant Propagation" , false , false)
Definition at line 1522 of file SCCP.cpp.
References llvm::createSCCPPass().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (IPSCCP , "ipsccp" , "Interprocedural Sparse Conditional Constant Propagation" , false , false)
References INITIALIZE_PASS_DEPENDENCY.
STATISTIC() [1/5]
STATISTIC (IPNumArgsElimed , "Number of arguments constant propagated by IPSCCP")
STATISTIC() [2/5]
STATISTIC (IPNumGlobalConst , "Number of globals found to be constant by IPSCCP")
STATISTIC() [3/5]
STATISTIC (IPNumInstRemoved , "Number of instructions removed by IPSCCP")
STATISTIC() [4/5]
STATISTIC (NumDeadBlocks , "Number of basic blocks unreachable")
STATISTIC() [5/5]
STATISTIC (NumInstRemoved , "Number of instructions removed")
Variable Documentation
false
Interprocedural Sparse Conditional Constant false
Definition at line 1657 of file SCCP.cpp.
ipsccp
ipsccp
Definition at line 1655 of file SCCP.cpp.
Propagation
Interprocedural Sparse Conditional Constant Propagation
Definition at line 1656 of file SCCP.cpp.