LLVM: SelectionDAGISel.cpp File Reference
LLVM API Documentation
SelectionDAGISel.cpp File Reference
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "ScheduleDAGSDNodes.h"
#include "SelectionDAGBuilder.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/CodeGen/FastISel.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/GCMetadata.h"
#include "llvm/CodeGen/GCStrategy.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/ScheduleHazardRecognizer.h"
#include "llvm/CodeGen/SchedulerRegistry.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <algorithm>
Classes
class llvm::OptLevelChanger
This class is used by SelectionDAGISel to temporarily override the optimization level on a per-function basis.
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "isel"
Enumerations
enum ChainResult { CR_Simple , CR_InducesCycle , CR_LeadsToInteriorNode }
Functions
STATISTIC (NumFastIselFailures, "Number of instructions fast isel failed on")
STATISTIC (NumFastIselSuccess, "Number of instructions fast isel selected")
STATISTIC (NumFastIselBlocks, "Number of blocks selected entirely by fast isel")
STATISTIC (NumDAGBlocks, "Number of blocks selected using DAG")
STATISTIC (NumDAGIselRetries,"Number of times dag isel has to try another path")
STATISTIC (NumEntryBlocks, "Number of entry blocks encountered")
STATISTIC (NumFastIselFailLowerArguments, "Number of entry blocks where fast isel failed to lower arguments")
STATISTIC (NumFastIselFailRet,"Fast isel fails on Ret")
STATISTIC (NumFastIselFailBr,"Fast isel fails on Br")
STATISTIC (NumFastIselFailSwitch,"Fast isel fails on Switch")
STATISTIC (NumFastIselFailIndirectBr,"Fast isel fails on IndirectBr")
STATISTIC (NumFastIselFailInvoke,"Fast isel fails on Invoke")
STATISTIC (NumFastIselFailResume,"Fast isel fails on Resume")
STATISTIC (NumFastIselFailUnreachable,"Fast isel fails on Unreachable")
STATISTIC (NumFastIselFailAdd,"Fast isel fails on Add")
STATISTIC (NumFastIselFailFAdd,"Fast isel fails on FAdd")
STATISTIC (NumFastIselFailSub,"Fast isel fails on Sub")
STATISTIC (NumFastIselFailFSub,"Fast isel fails on FSub")
STATISTIC (NumFastIselFailMul,"Fast isel fails on Mul")
STATISTIC (NumFastIselFailFMul,"Fast isel fails on FMul")
STATISTIC (NumFastIselFailUDiv,"Fast isel fails on UDiv")
STATISTIC (NumFastIselFailSDiv,"Fast isel fails on SDiv")
STATISTIC (NumFastIselFailFDiv,"Fast isel fails on FDiv")
STATISTIC (NumFastIselFailURem,"Fast isel fails on URem")
STATISTIC (NumFastIselFailSRem,"Fast isel fails on SRem")
STATISTIC (NumFastIselFailFRem,"Fast isel fails on FRem")
STATISTIC (NumFastIselFailAnd,"Fast isel fails on And")
STATISTIC (NumFastIselFailOr,"Fast isel fails on Or")
STATISTIC (NumFastIselFailXor,"Fast isel fails on Xor")
STATISTIC (NumFastIselFailAlloca,"Fast isel fails on Alloca")
STATISTIC (NumFastIselFailLoad,"Fast isel fails on Load")
STATISTIC (NumFastIselFailStore,"Fast isel fails on Store")
STATISTIC (NumFastIselFailAtomicCmpXchg,"Fast isel fails on AtomicCmpXchg")
STATISTIC (NumFastIselFailAtomicRMW,"Fast isel fails on AtomicRWM")
STATISTIC (NumFastIselFailFence,"Fast isel fails on Frence")
STATISTIC (NumFastIselFailGetElementPtr,"Fast isel fails on GetElementPtr")
STATISTIC (NumFastIselFailTrunc,"Fast isel fails on Trunc")
STATISTIC (NumFastIselFailZExt,"Fast isel fails on ZExt")
STATISTIC (NumFastIselFailSExt,"Fast isel fails on SExt")
STATISTIC (NumFastIselFailFPTrunc,"Fast isel fails on FPTrunc")
STATISTIC (NumFastIselFailFPExt,"Fast isel fails on FPExt")
STATISTIC (NumFastIselFailFPToUI,"Fast isel fails on FPToUI")
STATISTIC (NumFastIselFailFPToSI,"Fast isel fails on FPToSI")
STATISTIC (NumFastIselFailUIToFP,"Fast isel fails on UIToFP")
STATISTIC (NumFastIselFailSIToFP,"Fast isel fails on SIToFP")
STATISTIC (NumFastIselFailIntToPtr,"Fast isel fails on IntToPtr")
STATISTIC (NumFastIselFailPtrToInt,"Fast isel fails on PtrToInt")
STATISTIC (NumFastIselFailBitCast,"Fast isel fails on BitCast")
STATISTIC (NumFastIselFailICmp,"Fast isel fails on ICmp")
STATISTIC (NumFastIselFailFCmp,"Fast isel fails on FCmp")
STATISTIC (NumFastIselFailPHI,"Fast isel fails on PHI")
STATISTIC (NumFastIselFailSelect,"Fast isel fails on Select")
STATISTIC (NumFastIselFailCall,"Fast isel fails on Call")
STATISTIC (NumFastIselFailShl,"Fast isel fails on Shl")
STATISTIC (NumFastIselFailLShr,"Fast isel fails on LShr")
STATISTIC (NumFastIselFailAShr,"Fast isel fails on AShr")
STATISTIC (NumFastIselFailVAArg,"Fast isel fails on VAArg")
STATISTIC (NumFastIselFailExtractElement,"Fast isel fails on ExtractElement")
STATISTIC (NumFastIselFailInsertElement,"Fast isel fails on InsertElement")
STATISTIC (NumFastIselFailShuffleVector,"Fast isel fails on ShuffleVector")
STATISTIC (NumFastIselFailExtractValue,"Fast isel fails on ExtractValue")
STATISTIC (NumFastIselFailInsertValue,"Fast isel fails on InsertValue")
STATISTIC (NumFastIselFailLandingPad,"Fast isel fails on LandingPad")
STATISTIC (NumFastIselFailIntrinsicCall, "Fast isel fails on Intrinsic call")
STATISTIC (NumFastIselFailSAddWithOverflow, "Fast isel fails on sadd.with.overflow")
STATISTIC (NumFastIselFailUAddWithOverflow, "Fast isel fails on uadd.with.overflow")
STATISTIC (NumFastIselFailSSubWithOverflow, "Fast isel fails on ssub.with.overflow")
STATISTIC (NumFastIselFailUSubWithOverflow, "Fast isel fails on usub.with.overflow")
STATISTIC (NumFastIselFailSMulWithOverflow, "Fast isel fails on smul.with.overflow")
STATISTIC (NumFastIselFailUMulWithOverflow, "Fast isel fails on umul.with.overflow")
STATISTIC (NumFastIselFailFrameaddress, "Fast isel fails on Frameaddress")
STATISTIC (NumFastIselFailSqrt, "Fast isel fails on sqrt call")
STATISTIC (NumFastIselFailStackMap, "Fast isel fails on StackMap call")
STATISTIC (NumFastIselFailPatchPoint, "Fast isel fails on PatchPoint call")
ScheduleDAGSDNodes * llvm::createDefaultScheduler (SelectionDAGISel *IS, CodeGenOpt::Level OptLevel)
static void SplitCriticalSideEffectEdges (Function &Fn, Pass *SDISel)
static bool isFoldedOrDeadInstruction (const Instruction *I, FunctionLoweringInfo *FuncInfo)
static void collectFailStats (const Instruction *I)
static bool MIIsInTerminatorSequence (const MachineInstr *MI)
static MachineBasicBlock::iterator FindSplitPointForStackProtector (MachineBasicBlock *BB, DebugLoc DL)
static SDNode * findGlueUse (SDNode *N)
static bool findNonImmUse (SDNode *Use, SDNode *Def, SDNode *ImmedUse, SDNode *Root, SmallPtrSetImpl< SDNode * > &Visited, bool IgnoreChains)
static LLVM_ATTRIBUTE_ALWAYS_INLINE uint64_t GetVBR (uint64_t Val, const unsigned char *MatcherTable, unsigned &Idx)
GetVBR - decode a vbr encoding whose top bit is set.
static ChainResult WalkChainUsers (const SDNode *ChainedNode, SmallVectorImpl< SDNode * > &ChainedNodesInPattern, SmallVectorImpl< SDNode * > &InteriorChainedNodes)
static SDValue HandleMergeInputChains (SmallVectorImpl< SDNode * > &ChainNodesMatched, SelectionDAG *CurDAG)
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckSame (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDValue N, const SmallVectorImpl< std::pair< SDValue, SDNode * > > &RecordedNodes)
CheckSame - Implements OP_CheckSame.
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckChildSame (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDValue N, const SmallVectorImpl< std::pair< SDValue, SDNode * > > &RecordedNodes, unsigned ChildNo)
CheckChildSame - Implements OP_CheckChildXSame.
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckPatternPredicate (const unsigned char *MatcherTable, unsigned &MatcherIndex, const SelectionDAGISel &SDISel)
CheckPatternPredicate - Implements OP_CheckPatternPredicate.
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckNodePredicate (const unsigned char *MatcherTable, unsigned &MatcherIndex, const SelectionDAGISel &SDISel, SDNode *N)
CheckNodePredicate - Implements OP_CheckNodePredicate.
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckOpcode (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDNode *N)
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckType (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDValue N, const TargetLowering *TLI)
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckChildType (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDValue N, const TargetLowering *TLI, unsigned ChildNo)
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckCondCode (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDValue N)
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckValueType (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDValue N, const TargetLowering *TLI)
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckInteger (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDValue N)
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckChildInteger (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDValue N, unsigned ChildNo)
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckAndImm (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDValue N, const SelectionDAGISel &SDISel)
static LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckOrImm (const unsigned char *MatcherTable, unsigned &MatcherIndex, SDValue N, const SelectionDAGISel &SDISel)
static unsigned IsPredicateKnownToFail (const unsigned char *Table, unsigned Index, SDValue N, bool &Result, const SelectionDAGISel &SDISel, SmallVectorImpl< std::pair< SDValue, SDNode * > > &RecordedNodes)
Variables
static cl::opt< bool > EnableFastISelVerbose2 ("fast-isel-verbose2", cl::Hidden, cl::desc("Enable extra verbose messages in the \"fast\" " "instruction selector"))
static cl::opt< bool > EnableFastISelVerbose ("fast-isel-verbose", cl::Hidden, cl::desc("Enable verbose messages in the \"fast\" " "instruction selector"))
static cl::opt< bool > EnableFastISelAbort ("fast-isel-abort", cl::Hidden, cl::desc("Enable abort calls when \"fast\" instruction selection " "fails to lower an instruction"))
static cl::opt< bool > EnableFastISelAbortArgs ("fast-isel-abort-args", cl::Hidden, cl::desc("Enable abort calls when \"fast\" instruction selection " "fails to lower a formal argument"))
static cl::opt< bool > UseMBPI ("use-mbpi", cl::desc("use Machine Branch Probability Info"), cl::init(true), cl::Hidden)
static cl::opt< std::string > FilterDAGBasicBlockName ("filter-view-dags", cl::Hidden, cl::desc("Only display the basic block whose name " "matches this for all view-*-dags options"))
static cl::opt< bool > ViewDAGCombine1 ("view-dag-combine1-dags", cl::Hidden, cl::desc("Pop up a window to show dags before the first " "dag combine pass"))
static cl::opt< bool > ViewLegalizeTypesDAGs ("view-legalize-types-dags", cl::Hidden, cl::desc("Pop up a window to show dags before legalize types"))
static cl::opt< bool > ViewLegalizeDAGs ("view-legalize-dags", cl::Hidden, cl::desc("Pop up a window to show dags before legalize"))
static cl::opt< bool > ViewDAGCombine2 ("view-dag-combine2-dags", cl::Hidden, cl::desc("Pop up a window to show dags before the second " "dag combine pass"))
static cl::opt< bool > ViewDAGCombineLT ("view-dag-combine-lt-dags", cl::Hidden, cl::desc("Pop up a window to show dags before the post legalize types" " dag combine pass"))
static cl::opt< bool > ViewISelDAGs ("view-isel-dags", cl::Hidden, cl::desc("Pop up a window to show isel dags as they are selected"))
static cl::opt< bool > ViewSchedDAGs ("view-sched-dags", cl::Hidden, cl::desc("Pop up a window to show sched dags as they are processed"))
static cl::opt< bool > ViewSUnitDAGs ("view-sunit-dags", cl::Hidden, cl::desc("Pop up a window to show SUnit dags after they are processed"))
static cl::opt< RegisterScheduler::FunctionPassCtor, false, RegisterPassParser< RegisterScheduler > > ISHeuristic ("pre-RA-sched", cl::init(&createDefaultScheduler), cl::Hidden, cl::desc("Instruction schedulers available (before register" " allocation):"))
static RegisterScheduler defaultListDAGScheduler ("default", "Best scheduler for the target", createDefaultScheduler)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "isel"
Definition at line 60 of file SelectionDAGISel.cpp.
Enumeration Type Documentation
ChainResult
enum ChainResult
Enumerator
CR_Simple
CR_InducesCycle
CR_LeadsToInteriorNode
Definition at line 1992 of file SelectionDAGISel.cpp.
Function Documentation
CheckAndImm()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckAndImm (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDValue N, const SelectionDAGISel & SDISel) static
Definition at line 2330 of file SelectionDAGISel.cpp.
References llvm::ISD::AND, llvm::SelectionDAGISel::CheckAndMask(), llvm::dyn_cast(), GetVBR(), and N.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
CheckChildInteger()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckChildInteger (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDValue N, unsigned ChildNo) static
Definition at line 2322 of file SelectionDAGISel.cpp.
References N.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
CheckChildSame()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckChildSame (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDValue N, const SmallVectorImpl< std::pair< SDValue, SDNode * > > & RecordedNodes, unsigned ChildNo) static
CheckChildSame - Implements OP_CheckChildXSame.
Definition at line 2242 of file SelectionDAGISel.cpp.
References N.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
CheckChildType()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckChildType (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDValue N, const TargetLowering * TLI, unsigned ChildNo) static
Definition at line 2285 of file SelectionDAGISel.cpp.
References N.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
CheckCondCode()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckCondCode (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDValue N) static
Definition at line 2293 of file SelectionDAGISel.cpp.
References llvm::cast(), and N.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
CheckInteger()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckInteger (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDValue N) static
Definition at line 2311 of file SelectionDAGISel.cpp.
References llvm::dyn_cast(), GetVBR(), and N.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
CheckNodePredicate()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckNodePredicate (const unsigned char * MatcherTable, unsigned & MatcherIndex, const SelectionDAGISel & SDISel, SDNode * N) static
CheckNodePredicate - Implements OP_CheckNodePredicate.
Definition at line 2261 of file SelectionDAGISel.cpp.
References llvm::SelectionDAGISel::CheckNodePredicate(), and N.
Referenced by IsPredicateKnownToFail().
CheckOpcode()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckOpcode (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDNode * N) static
Definition at line 2267 of file SelectionDAGISel.cpp.
References N.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
CheckOrImm()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckOrImm (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDValue N, const SelectionDAGISel & SDISel) static
Definition at line 2343 of file SelectionDAGISel.cpp.
References llvm::SelectionDAGISel::CheckOrMask(), llvm::dyn_cast(), GetVBR(), N, and llvm::ISD::OR.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
CheckPatternPredicate()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckPatternPredicate (const unsigned char * MatcherTable, unsigned & MatcherIndex, const SelectionDAGISel & SDISel) static
CheckPatternPredicate - Implements OP_CheckPatternPredicate.
Definition at line 2254 of file SelectionDAGISel.cpp.
References llvm::SelectionDAGISel::CheckPatternPredicate().
Referenced by IsPredicateKnownToFail().
CheckSame()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckSame (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDValue N, const SmallVectorImpl< std::pair< SDValue, SDNode * > > & RecordedNodes) static
CheckSame - Implements OP_CheckSame.
Definition at line 2231 of file SelectionDAGISel.cpp.
References N.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
CheckType()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckType (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDValue N, const TargetLowering * TLI) static
Definition at line 2275 of file SelectionDAGISel.cpp.
References llvm::TargetLoweringBase::getPointerTy(), llvm::MVT::iPTR, and N.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
CheckValueType()
LLVM_ATTRIBUTE_ALWAYS_INLINE bool CheckValueType (const unsigned char * MatcherTable, unsigned & MatcherIndex, SDValue N, const TargetLowering * TLI) static
Definition at line 2300 of file SelectionDAGISel.cpp.
References llvm::cast(), llvm::TargetLoweringBase::getPointerTy(), llvm::MVT::iPTR, and N.
Referenced by IsPredicateKnownToFail(), and llvm::SelectionDAGISel::SelectCodeCommon().
collectFailStats()
void collectFailStats (const Instruction * I) static
Definition at line 948 of file SelectionDAGISel.cpp.
References llvm::dyn_cast(), llvm::Intrinsic::experimental_patchpoint_i64, llvm::Intrinsic::experimental_patchpoint_void, llvm::Intrinsic::experimental_stackmap, llvm::Intrinsic::frameaddress, I, llvm::Intrinsic::sadd_with_overflow, llvm::Intrinsic::smul_with_overflow, llvm::Intrinsic::sqrt, llvm::Intrinsic::ssub_with_overflow, llvm::Intrinsic::uadd_with_overflow, llvm::Intrinsic::umul_with_overflow, and llvm::Intrinsic::usub_with_overflow.
findGlueUse()
SDNode * findGlueUse (SDNode * N) static
findGlueUse - Return use of MVT::Glue value produced by the specified SDNode.
Definition at line 1730 of file SelectionDAGISel.cpp.
References llvm::Use::getUser(), I, and N.
Referenced by llvm::SelectionDAGISel::IsLegalToFold().
findNonImmUse()
bool findNonImmUse (SDNode * Use, SDNode * Def, SDNode * ImmedUse, SDNode * Root, SmallPtrSetImpl< SDNode * > & Visited, bool IgnoreChains) static
findNonImmUse - Return true if "Use" is a non-immediate use of "Def". This function recursively traverses up the operand chain, ignoring certain nodes.
Definition at line 1743 of file SelectionDAGISel.cpp.
References findNonImmUse(), llvm::SmallPtrSetImpl< PtrType >::insert(), N, and llvm::MVT::Other.
Referenced by findNonImmUse(), and llvm::SelectionDAGISel::IsLegalToFold().
FindSplitPointForStackProtector()
MachineBasicBlock::iterator FindSplitPointForStackProtector (MachineBasicBlock * BB, DebugLoc DL) static
Find the split point at which to splice the end of BB into its success stack protector check machine basic block.
On many platforms, due to ABI constraints, terminators, even before register allocation, use physical registers. This creates an issue for us since physical registers at this point can not travel across basic blocks. Luckily, selectiondag always moves physical registers into vregs when they enter functions and moves them through a sequence of copies back into the physical registers right before the terminator creating a `‘Terminator Sequence’'. This function is searching for the beginning of the terminator sequence so that we can ensure that we splice off not just the terminator, but additionally the copies that move the vregs into the physical registers.
Definition at line 1327 of file SelectionDAGISel.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::getFirstTerminator(), and MIIsInTerminatorSequence().
GetVBR()
LLVM_ATTRIBUTE_ALWAYS_INLINE uint64_t GetVBR (uint64_t Val, const unsigned char * MatcherTable, unsigned & Idx) static
GetVBR - decode a vbr encoding whose top bit is set.
Definition at line 1905 of file SelectionDAGISel.cpp.
Referenced by CheckAndImm(), CheckInteger(), CheckOrImm(), and llvm::SelectionDAGISel::SelectCodeCommon().
HandleMergeInputChains()
SDValue HandleMergeInputChains (SmallVectorImpl< SDNode * > & ChainNodesMatched, SelectionDAG * CurDAG) static
HandleMergeInputChains - This implements the OPC_EmitMergeInputChains operation for when the pattern matched at least one node with a chains. The input vector contains a list of all of the chained nodes that we match. We must determine if this is a valid thing to cover (i.e. matching it won't induce cycles in the DAG) and if so, creating a TokenFactor node. that will be used as the input node chain for the generated nodes.
Definition at line 2126 of file SelectionDAGISel.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), CR_InducesCycle, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), N, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::ISD::TokenFactor, and WalkChainUsers().
Referenced by llvm::SelectionDAGISel::SelectCodeCommon().
isFoldedOrDeadInstruction()
bool isFoldedOrDeadInstruction (const Instruction * I, FunctionLoweringInfo * FuncInfo) static
isFoldedOrDeadInstruction - Return true if the specified instruction is side-effect free and is either dead or folded into a generated instruction. Return false if it needs to be emitted.
Definition at line 934 of file SelectionDAGISel.cpp.
References I, llvm::isa(), and llvm::FunctionLoweringInfo::isExportedInst().
IsPredicateKnownToFail()
unsigned IsPredicateKnownToFail (const unsigned char * Table, unsigned Index, SDValue N, bool & Result, const SelectionDAGISel & SDISel, SmallVectorImpl< std::pair< SDValue, SDNode * > > & RecordedNodes) static
IsPredicateKnownToFail - If we know how and can do so without pushing a scope, evaluate the current node. If the current predicate is known to fail, set Result=true and return anything. If the current predicate is known to pass, set Result=false and return the MatcherIndex to continue with. If the current predicate is unknown, set Result=false and return the MatcherIndex to continue with.
Definition at line 2361 of file SelectionDAGISel.cpp.
References CheckAndImm(), CheckChildInteger(), CheckChildSame(), CheckChildType(), CheckCondCode(), CheckInteger(), CheckNodePredicate(), CheckOpcode(), CheckOrImm(), CheckPatternPredicate(), CheckSame(), CheckType(), CheckValueType(), N, llvm::SelectionDAGISel::OPC_CheckAndImm, llvm::SelectionDAGISel::OPC_CheckChild0Integer, llvm::SelectionDAGISel::OPC_CheckChild0Same, llvm::SelectionDAGISel::OPC_CheckChild0Type, llvm::SelectionDAGISel::OPC_CheckChild1Integer, llvm::SelectionDAGISel::OPC_CheckChild1Same, llvm::SelectionDAGISel::OPC_CheckChild1Type, llvm::SelectionDAGISel::OPC_CheckChild2Integer, llvm::SelectionDAGISel::OPC_CheckChild2Same, llvm::SelectionDAGISel::OPC_CheckChild2Type, llvm::SelectionDAGISel::OPC_CheckChild3Integer, llvm::SelectionDAGISel::OPC_CheckChild3Same, llvm::SelectionDAGISel::OPC_CheckChild3Type, llvm::SelectionDAGISel::OPC_CheckChild4Integer, llvm::SelectionDAGISel::OPC_CheckChild4Type, llvm::SelectionDAGISel::OPC_CheckChild5Type, llvm::SelectionDAGISel::OPC_CheckChild6Type, llvm::SelectionDAGISel::OPC_CheckChild7Type, llvm::SelectionDAGISel::OPC_CheckCondCode, llvm::SelectionDAGISel::OPC_CheckInteger, llvm::SelectionDAGISel::OPC_CheckOpcode, llvm::SelectionDAGISel::OPC_CheckOrImm, llvm::SelectionDAGISel::OPC_CheckPatternPredicate, llvm::SelectionDAGISel::OPC_CheckPredicate, llvm::SelectionDAGISel::OPC_CheckSame, llvm::SelectionDAGISel::OPC_CheckType, llvm::SelectionDAGISel::OPC_CheckValueType, and llvm::SelectionDAGISel::TLI.
Referenced by llvm::SelectionDAGISel::SelectCodeCommon().
MIIsInTerminatorSequence()
bool MIIsInTerminatorSequence (const MachineInstr * MI) static
Given that the input MI is before a partial terminator sequence TSeq, return true if M + TSeq also a partial terminator sequence.
A Terminator sequence is a sequence of MachineInstrs which at this point in lowering copy vregs into physical registers, which are then passed into terminator instructors so we can satisfy ABI constraints. A partial terminator sequence is an improper subset of a terminator sequence (i.e. it may be the whole terminator sequence).
Definition at line 1271 of file SelectionDAGISel.cpp.
References llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), llvm::TargetRegisterInfo::isPhysicalRegister(), and llvm::MachineOperand::isReg().
Referenced by FindSplitPointForStackProtector().
SplitCriticalSideEffectEdges()
void SplitCriticalSideEffectEdges (Function & Fn, Pass * SDISel) static
SplitCriticalSideEffectEdges - Look for critical edges with a PHI value that may trap on it. In this case we have to split the edge so that the path through the predecessor block that doesn't go to the phi block doesn't execute the possibly trapping instruction.
This is required for correctness, so it must be done at -O0.
Definition at line 379 of file SelectionDAGISel.cpp.
References llvm::Function::begin(), llvm::dyn_cast(), llvm::Function::end(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::TerminatorInst::getNumSuccessors(), llvm::GetSuccessorNumber(), llvm::BasicBlock::getTerminator(), I, and llvm::SplitCriticalEdge().
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
STATISTIC() [1/74]
STATISTIC (NumDAGBlocks , "Number of blocks selected using DAG")
STATISTIC() [2/74]
STATISTIC (NumDAGIselRetries , "Number of times dag isel has to try another path")
STATISTIC() [3/74]
STATISTIC (NumEntryBlocks , "Number of entry blocks encountered")
STATISTIC() [4/74]
STATISTIC (NumFastIselBlocks , "Number of blocks selected entirely by fast isel")
STATISTIC() [5/74]
STATISTIC (NumFastIselFailAdd , "Fast isel fails on Add")
STATISTIC() [6/74]
STATISTIC (NumFastIselFailAlloca , "Fast isel fails on Alloca")
STATISTIC() [7/74]
STATISTIC (NumFastIselFailAnd , "Fast isel fails on And")
STATISTIC() [8/74]
STATISTIC (NumFastIselFailAShr , "Fast isel fails on AShr")
STATISTIC() [9/74]
STATISTIC (NumFastIselFailAtomicCmpXchg , "Fast isel fails on AtomicCmpXchg")
STATISTIC() [10/74]
STATISTIC (NumFastIselFailAtomicRMW , "Fast isel fails on AtomicRWM")
STATISTIC() [11/74]
STATISTIC (NumFastIselFailBitCast , "Fast isel fails on BitCast")
STATISTIC() [12/74]
STATISTIC (NumFastIselFailBr , "Fast isel fails on Br")
STATISTIC() [13/74]
STATISTIC (NumFastIselFailCall , "Fast isel fails on Call")
STATISTIC() [14/74]
STATISTIC (NumFastIselFailExtractElement , "Fast isel fails on ExtractElement")
STATISTIC() [15/74]
STATISTIC (NumFastIselFailExtractValue , "Fast isel fails on ExtractValue")
STATISTIC() [16/74]
STATISTIC (NumFastIselFailFAdd , "Fast isel fails on FAdd")
STATISTIC() [17/74]
STATISTIC (NumFastIselFailFCmp , "Fast isel fails on FCmp")
STATISTIC() [18/74]
STATISTIC (NumFastIselFailFDiv , "Fast isel fails on FDiv")
STATISTIC() [19/74]
STATISTIC (NumFastIselFailFence , "Fast isel fails on Frence")
STATISTIC() [20/74]
STATISTIC (NumFastIselFailFMul , "Fast isel fails on FMul")
STATISTIC() [21/74]
STATISTIC (NumFastIselFailFPExt , "Fast isel fails on FPExt")
STATISTIC() [22/74]
STATISTIC (NumFastIselFailFPToSI , "Fast isel fails on FPToSI")
STATISTIC() [23/74]
STATISTIC (NumFastIselFailFPToUI , "Fast isel fails on FPToUI")
STATISTIC() [24/74]
STATISTIC (NumFastIselFailFPTrunc , "Fast isel fails on FPTrunc")
STATISTIC() [25/74]
STATISTIC (NumFastIselFailFrameaddress , "Fast isel fails on Frameaddress")
STATISTIC() [26/74]
STATISTIC (NumFastIselFailFRem , "Fast isel fails on FRem")
STATISTIC() [27/74]
STATISTIC (NumFastIselFailFSub , "Fast isel fails on FSub")
STATISTIC() [28/74]
STATISTIC (NumFastIselFailGetElementPtr , "Fast isel fails on GetElementPtr")
STATISTIC() [29/74]
STATISTIC (NumFastIselFailICmp , "Fast isel fails on ICmp")
STATISTIC() [30/74]
STATISTIC (NumFastIselFailIndirectBr , "Fast isel fails on IndirectBr")
STATISTIC() [31/74]
STATISTIC (NumFastIselFailInsertElement , "Fast isel fails on InsertElement")
STATISTIC() [32/74]
STATISTIC (NumFastIselFailInsertValue , "Fast isel fails on InsertValue")
STATISTIC() [33/74]
STATISTIC (NumFastIselFailIntrinsicCall , "Fast isel fails on Intrinsic call")
STATISTIC() [34/74]
STATISTIC (NumFastIselFailIntToPtr , "Fast isel fails on IntToPtr")
STATISTIC() [35/74]
STATISTIC (NumFastIselFailInvoke , "Fast isel fails on Invoke")
STATISTIC() [36/74]
STATISTIC (NumFastIselFailLandingPad , "Fast isel fails on LandingPad")
STATISTIC() [37/74]
STATISTIC (NumFastIselFailLoad , "Fast isel fails on Load")
STATISTIC() [38/74]
STATISTIC (NumFastIselFailLowerArguments , "Number of entry blocks where fast isel failed to lower arguments")
STATISTIC() [39/74]
STATISTIC (NumFastIselFailLShr , "Fast isel fails on LShr")
STATISTIC() [40/74]
STATISTIC (NumFastIselFailMul , "Fast isel fails on Mul")
STATISTIC() [41/74]
STATISTIC (NumFastIselFailOr , "Fast isel fails on Or")
STATISTIC() [42/74]
STATISTIC (NumFastIselFailPatchPoint , "Fast isel fails on PatchPoint call")
STATISTIC() [43/74]
STATISTIC (NumFastIselFailPHI , "Fast isel fails on PHI")
STATISTIC() [44/74]
STATISTIC (NumFastIselFailPtrToInt , "Fast isel fails on PtrToInt")
STATISTIC() [45/74]
STATISTIC (NumFastIselFailResume , "Fast isel fails on Resume")
STATISTIC() [46/74]
STATISTIC (NumFastIselFailRet , "Fast isel fails on Ret")
STATISTIC() [47/74]
STATISTIC (NumFastIselFailSAddWithOverflow , "Fast isel fails on sadd.with.overflow")
STATISTIC() [48/74]
STATISTIC (NumFastIselFailSDiv , "Fast isel fails on SDiv")
STATISTIC() [49/74]
STATISTIC (NumFastIselFailSelect , "Fast isel fails on Select")
STATISTIC() [50/74]
STATISTIC (NumFastIselFailSExt , "Fast isel fails on SExt")
STATISTIC() [51/74]
STATISTIC (NumFastIselFailShl , "Fast isel fails on Shl")
STATISTIC() [52/74]
STATISTIC (NumFastIselFailShuffleVector , "Fast isel fails on ShuffleVector")
STATISTIC() [53/74]
STATISTIC (NumFastIselFailSIToFP , "Fast isel fails on SIToFP")
STATISTIC() [54/74]
STATISTIC (NumFastIselFailSMulWithOverflow , "Fast isel fails on smul.with.overflow")
STATISTIC() [55/74]
STATISTIC (NumFastIselFailSqrt , "Fast isel fails on sqrt call")
STATISTIC() [56/74]
STATISTIC (NumFastIselFailSRem , "Fast isel fails on SRem")
STATISTIC() [57/74]
STATISTIC (NumFastIselFailSSubWithOverflow , "Fast isel fails on ssub.with.overflow")
STATISTIC() [58/74]
STATISTIC (NumFastIselFailStackMap , "Fast isel fails on StackMap call")
STATISTIC() [59/74]
STATISTIC (NumFastIselFailStore , "Fast isel fails on Store")
STATISTIC() [60/74]
STATISTIC (NumFastIselFailSub , "Fast isel fails on Sub")
STATISTIC() [61/74]
STATISTIC (NumFastIselFailSwitch , "Fast isel fails on Switch")
STATISTIC() [62/74]
STATISTIC (NumFastIselFailTrunc , "Fast isel fails on Trunc")
STATISTIC() [63/74]
STATISTIC (NumFastIselFailUAddWithOverflow , "Fast isel fails on uadd.with.overflow")
STATISTIC() [64/74]
STATISTIC (NumFastIselFailUDiv , "Fast isel fails on UDiv")
STATISTIC() [65/74]
STATISTIC (NumFastIselFailUIToFP , "Fast isel fails on UIToFP")
STATISTIC() [66/74]
STATISTIC (NumFastIselFailUMulWithOverflow , "Fast isel fails on umul.with.overflow")
STATISTIC() [67/74]
STATISTIC (NumFastIselFailUnreachable , "Fast isel fails on Unreachable")
STATISTIC() [68/74]
STATISTIC (NumFastIselFailURem , "Fast isel fails on URem")
STATISTIC() [69/74]
STATISTIC (NumFastIselFailures , "Number of instructions fast isel failed on")
STATISTIC() [70/74]
STATISTIC (NumFastIselFailUSubWithOverflow , "Fast isel fails on usub.with.overflow")
STATISTIC() [71/74]
STATISTIC (NumFastIselFailVAArg , "Fast isel fails on VAArg")
STATISTIC() [72/74]
STATISTIC (NumFastIselFailXor , "Fast isel fails on Xor")
STATISTIC() [73/74]
STATISTIC (NumFastIselFailZExt , "Fast isel fails on ZExt")
STATISTIC() [74/74]
STATISTIC (NumFastIselSuccess , "Number of instructions fast isel selected")
WalkChainUsers()
ChainResult WalkChainUsers (const SDNode * ChainedNode, SmallVectorImpl< SDNode * > & ChainedNodesInPattern, SmallVectorImpl< SDNode * > & InteriorChainedNodes) static
WalkChainUsers - Walk down the users of the specified chained node that is part of the pattern we're matching, looking at all of the users we find. This determines whether something is an interior node, whether we have a non-pattern node in between two pattern nodes (which prevent folding because it would induce a cycle) and whether we have a TokenFactor node sandwiched between pattern nodes (in which case the TF becomes part of the pattern).
The walk we do here is guaranteed to be small because we quickly get down to already selected nodes "below" us.
Definition at line 2008 of file SelectionDAGISel.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, CR_InducesCycle, CR_LeadsToInteriorNode, CR_Simple, llvm::ISD::EH_LABEL, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::ISD::HANDLENODE, llvm::ISD::INLINEASM, llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::ISD::TokenFactor, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), and WalkChainUsers().
Referenced by HandleMergeInputChains(), and WalkChainUsers().
Variable Documentation
defaultListDAGScheduler
RegisterScheduler defaultListDAGScheduler("default", "Best scheduler for the target", createDefaultScheduler) ("default" , "Best scheduler for the target" , createDefaultScheduler) static
EnableFastISelAbort
cl::opt< bool > EnableFastISelAbort("fast-isel-abort", cl::Hidden, cl::desc("Enable abort calls when \"fast\" instruction selection " "fails to lower an instruction")) ("fast-isel-abort" , cl::Hidden , cl::desc("Enable abort calls when \"fast\" instruction selection " "fails to lower an instruction")) static
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
EnableFastISelAbortArgs
cl::opt< bool > EnableFastISelAbortArgs("fast-isel-abort-args", cl::Hidden, cl::desc("Enable abort calls when \"fast\" instruction selection " "fails to lower a formal argument")) ("fast-isel-abort-args" , cl::Hidden , cl::desc("Enable abort calls when \"fast\" instruction selection " "fails to lower a formal argument")) static
EnableFastISelVerbose
cl::opt< bool > EnableFastISelVerbose("fast-isel-verbose", cl::Hidden, cl::desc("Enable verbose messages in the \"fast\" " "instruction selector")) ("fast-isel-verbose" , cl::Hidden , cl::desc("Enable verbose messages in the \"fast\" " "instruction selector")) static
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
EnableFastISelVerbose2
cl::opt< bool > EnableFastISelVerbose2("fast-isel-verbose2", cl::Hidden, cl::desc("Enable extra verbose messages in the \"fast\" " "instruction selector")) ("fast-isel-verbose2" , cl::Hidden , cl::desc("Enable extra verbose messages in the \"fast\" " "instruction selector")) static
FilterDAGBasicBlockName
cl::opt< std::string > FilterDAGBasicBlockName("filter-view-dags", cl::Hidden, cl::desc("Only display the basic block whose name " "matches this for all view-*-dags options")) ("filter-view-dags" , cl::Hidden , cl::desc("Only display the basic block whose name " "matches this for all view-*-dags options")) static
ISHeuristic
cl::opt< RegisterScheduler::FunctionPassCtor, false, RegisterPassParser< RegisterScheduler > > ISHeuristic("pre-RA-sched", cl::init(&createDefaultScheduler), cl::Hidden, cl::desc("Instruction schedulers available (before register" " allocation):")) ("pre-RA-sched" , cl::init & createDefaultScheduler, cl::Hidden , cl::desc("Instruction schedulers available (before register" " allocation):")) static
ISHeuristic command line option for instruction schedulers.
UseMBPI
cl::opt< bool > UseMBPI("use-mbpi", cl::desc("use Machine Branch Probability Info"), cl::init(true), cl::Hidden) ("use-mbpi" , cl::desc("use Machine Branch Probability Info") , cl::init(true) , cl::Hidden) static
Referenced by llvm::SelectionDAGISel::getAnalysisUsage(), and llvm::SelectionDAGISel::runOnMachineFunction().
ViewDAGCombine1
cl::opt< bool > ViewDAGCombine1("view-dag-combine1-dags", cl::Hidden, cl::desc("Pop up a window to show dags before the first " "dag combine pass")) ("view-dag-combine1-dags" , cl::Hidden , cl::desc("Pop up a window to show dags before the first " "dag combine pass")) static
ViewDAGCombine2
cl::opt< bool > ViewDAGCombine2("view-dag-combine2-dags", cl::Hidden, cl::desc("Pop up a window to show dags before the second " "dag combine pass")) ("view-dag-combine2-dags" , cl::Hidden , cl::desc("Pop up a window to show dags before the second " "dag combine pass")) static
ViewDAGCombineLT
cl::opt< bool > ViewDAGCombineLT("view-dag-combine-lt-dags", cl::Hidden, cl::desc("Pop up a window to show dags before the post legalize types" " dag combine pass")) ("view-dag-combine-lt-dags" , cl::Hidden , cl::desc("Pop up a window to show dags before the post legalize types" " dag combine pass")) static
ViewISelDAGs
cl::opt< bool > ViewISelDAGs("view-isel-dags", cl::Hidden, cl::desc("Pop up a window to show isel dags as they are selected")) ("view-isel-dags" , cl::Hidden , cl::desc("Pop up a window to show isel dags as they are selected")) static
ViewLegalizeDAGs
cl::opt< bool > ViewLegalizeDAGs("view-legalize-dags", cl::Hidden, cl::desc("Pop up a window to show dags before legalize")) ("view-legalize-dags" , cl::Hidden , cl::desc("Pop up a window to show dags before legalize")) static
ViewLegalizeTypesDAGs
cl::opt< bool > ViewLegalizeTypesDAGs("view-legalize-types-dags", cl::Hidden, cl::desc("Pop up a window to show dags before legalize types")) ("view-legalize-types-dags" , cl::Hidden , cl::desc("Pop up a window to show dags before legalize types")) static
ViewSchedDAGs
cl::opt< bool > ViewSchedDAGs("view-sched-dags", cl::Hidden, cl::desc("Pop up a window to show sched dags as they are processed")) ("view-sched-dags" , cl::Hidden , cl::desc("Pop up a window to show sched dags as they are processed")) static
ViewSUnitDAGs
cl::opt< bool > ViewSUnitDAGs("view-sunit-dags", cl::Hidden, cl::desc("Pop up a window to show SUnit dags after they are processed")) ("view-sunit-dags" , cl::Hidden , cl::desc("Pop up a window to show SUnit dags after they are processed")) static