LLVM: SIISelLowering.cpp File Reference
LLVM API Documentation
SIISelLowering.cpp File Reference
Custom DAG lowering for SI.
#include "SIISelLowering.h"
#include "AMDGPU.h"
#include "AMDGPUIntrinsicInfo.h"
#include "AMDGPUSubtarget.h"
#include "SIInstrInfo.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/IR/Function.h"
#include "llvm/ADT/SmallString.h"
Functions
static SDNode * findUser (SDValue Value, unsigned Opcode)
Helper function for LowerBRCOND.
static unsigned minMaxOpcToMin3Max3Opc (unsigned Opc)
static bool isVSrc (unsigned RegClass)
Test if RegClass is one of the VSrc classes.
static unsigned SubIdx2Lane (unsigned Idx)
Helper function for adjustWritemask.
static SDValue buildSMovImm32 (SelectionDAG &DAG, SDLoc DL, uint64_t Val)
Detailed Description
Custom DAG lowering for SI.
Definition in file SIISelLowering.cpp.
Function Documentation
buildSMovImm32()
SDValue buildSMovImm32 (SelectionDAG & DAG, SDLoc DL, uint64_t Val) static
Definition at line 2042 of file SIISelLowering.cpp.
References llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), and llvm::MVT::i32.
Referenced by llvm::SITargetLowering::buildRSRC(), and llvm::SITargetLowering::wrapAddr64Rsrc().
findUser()
SDNode * findUser (SDValue Value, unsigned Opcode) static
Helper function for LowerBRCOND.
Definition at line 705 of file SIISelLowering.cpp.
References I, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
isVSrc()
bool isVSrc (unsigned RegClass) static
Test if RegClass is one of the VSrc classes.
Definition at line 1764 of file SIISelLowering.cpp.
minMaxOpcToMin3Max3Opc()
unsigned minMaxOpcToMin3Max3Opc (unsigned Opc) static
Definition at line 1490 of file SIISelLowering.cpp.
References llvm::AMDGPUISD::FMAX3, llvm::ISD::FMAXNUM, llvm::AMDGPUISD::FMIN3, llvm::ISD::FMINNUM, llvm_unreachable, llvm::AMDGPUISD::SMAX, llvm::AMDGPUISD::SMAX3, llvm::AMDGPUISD::SMIN, llvm::AMDGPUISD::SMIN3, llvm::AMDGPUISD::UMAX, llvm::AMDGPUISD::UMAX3, llvm::AMDGPUISD::UMIN, and llvm::AMDGPUISD::UMIN3.
SubIdx2Lane()
unsigned SubIdx2Lane (unsigned Idx) static
Helper function for adjustWritemask.
Definition at line 1869 of file SIISelLowering.cpp.