LLVM: SparcMCTargetDesc.cpp File Reference
LLVM API Documentation
SparcMCTargetDesc.cpp File Reference
#include "SparcMCTargetDesc.h"
#include "InstPrinter/SparcInstPrinter.h"
#include "SparcMCAsmInfo.h"
#include "SparcTargetStreamer.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "SparcGenInstrInfo.inc"
#include "SparcGenSubtargetInfo.inc"
#include "SparcGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCAsmInfo * createSparcMCAsmInfo (const MCRegisterInfo &MRI, StringRef TT)
static MCAsmInfo * createSparcV9MCAsmInfo (const MCRegisterInfo &MRI, StringRef TT)
static MCInstrInfo * createSparcMCInstrInfo ()
static MCRegisterInfo * createSparcMCRegisterInfo (StringRef TT)
static MCSubtargetInfo * createSparcMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
static MCCodeGenInfo * createSparcMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCCodeGenInfo * createSparcV9MCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCStreamer * createMCStreamer (const Target &T, StringRef TT, MCContext &Context, MCAsmBackend &MAB, raw_ostream &OS, MCCodeEmitter *Emitter, const MCSubtargetInfo &STI, bool RelaxAll)
static MCStreamer * createMCAsmStreamer (MCContext &Ctx, formatted_raw_ostream &OS, bool isVerboseAsm, bool useDwarfDirectory, MCInstPrinter *InstPrint, MCCodeEmitter *CE, MCAsmBackend *TAB, bool ShowInst)
static MCInstPrinter * createSparcMCInstPrinter (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
void LLVMInitializeSparcTargetMC ()
Macro Definition Documentation
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 27 of file SparcMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 33 of file SparcMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 30 of file SparcMCTargetDesc.cpp.
Function Documentation
createMCAsmStreamer()
MCStreamer * createMCAsmStreamer (MCContext & Ctx, formatted_raw_ostream & OS, bool isVerboseAsm, bool useDwarfDirectory, MCInstPrinter * InstPrint, MCCodeEmitter * CE, MCAsmBackend * TAB, bool ShowInst) static
Definition at line 135 of file SparcMCTargetDesc.cpp.
References llvm::createAsmStreamer().
createMCStreamer()
MCStreamer * createMCStreamer (const Target & T, StringRef TT, MCContext & Context, MCAsmBackend & MAB, raw_ostream & OS, MCCodeEmitter * Emitter, const MCSubtargetInfo & STI, bool RelaxAll) static
Definition at line 125 of file SparcMCTargetDesc.cpp.
References llvm::createELFStreamer(), RelaxAll(), and T.
createSparcMCAsmInfo()
MCAsmInfo * createSparcMCAsmInfo (const MCRegisterInfo & MRI, StringRef TT) static
Definition at line 36 of file SparcMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::createDefCfa(), and llvm::MCRegisterInfo::getDwarfRegNum().
Referenced by LLVMInitializeSparcTargetMC().
createSparcMCCodeGenInfo()
MCCodeGenInfo * createSparcMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 87 of file SparcMCTargetDesc.cpp.
References llvm::CodeModel::Default, llvm::CodeModel::JITDefault, llvm::CodeModel::Small, and llvm::X.
Referenced by LLVMInitializeSparcTargetMC().
createSparcMCInstPrinter()
MCInstPrinter * createSparcMCInstPrinter (const Target & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) static
Definition at line 146 of file SparcMCTargetDesc.cpp.
References T.
Referenced by LLVMInitializeSparcTargetMC().
createSparcMCInstrInfo()
MCInstrInfo * createSparcMCInstrInfo () static
Definition at line 54 of file SparcMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeSparcTargetMC().
createSparcMCRegisterInfo()
MCRegisterInfo * createSparcMCRegisterInfo (StringRef TT) static
Definition at line 60 of file SparcMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeSparcTargetMC().
createSparcMCSubtargetInfo()
MCSubtargetInfo * createSparcMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS) static
Definition at line 66 of file SparcMCTargetDesc.cpp.
References llvm::StringRef::empty(), llvm::Triple::getArch(), llvm::Triple::sparcv9, and llvm::X.
Referenced by LLVMInitializeSparcTargetMC().
createSparcV9MCAsmInfo()
MCAsmInfo * createSparcV9MCAsmInfo (const MCRegisterInfo & MRI, StringRef TT) static
Definition at line 45 of file SparcMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::createDefCfa(), and llvm::MCRegisterInfo::getDwarfRegNum().
Referenced by LLVMInitializeSparcTargetMC().
createSparcV9MCCodeGenInfo()
MCCodeGenInfo * createSparcV9MCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 104 of file SparcMCTargetDesc.cpp.
References llvm::CodeModel::Default, llvm::CodeModel::JITDefault, llvm::CodeModel::Large, llvm::CodeModel::Medium, llvm::Reloc::PIC_, llvm::CodeModel::Small, and llvm::X.
Referenced by LLVMInitializeSparcTargetMC().
LLVMInitializeSparcTargetMC()
void LLVMInitializeSparcTargetMC ()
Definition at line 155 of file SparcMCTargetDesc.cpp.
References llvm::createMCAsmStreamer(), createMCStreamer(), llvm::createSparcAsmBackend(), createSparcMCAsmInfo(), llvm::createSparcMCCodeEmitter(), createSparcMCCodeGenInfo(), createSparcMCInstPrinter(), createSparcMCInstrInfo(), createSparcMCRegisterInfo(), createSparcMCSubtargetInfo(), createSparcV9MCAsmInfo(), createSparcV9MCCodeGenInfo(), llvm::TargetRegistry::RegisterAsmStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCCodeGenInfo(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCObjectStreamer(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TheSparcTarget, llvm::TheSparcV9Target, llvm::X, and Y.