LLVM: StackMaps.cpp File Reference
LLVM API Documentation
StackMaps.cpp File Reference
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOpcodes.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include <iterator>
Macros
#define DEBUG_TYPE "stackmaps"
Functions
static unsigned getDwarfRegNum (unsigned Reg, const TargetRegisterInfo *TRI)
Go up the super-register chain until we hit a valid dwarf register number.
Variables
static cl::opt< int > StackMapVersion ("stackmap-version", cl::init(1), cl::desc("Specify the stackmap encoding version (default = 1)"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "stackmaps"
Definition at line 32 of file StackMaps.cpp.
Function Documentation
getDwarfRegNum()
unsigned getDwarfRegNum (unsigned Reg, const TargetRegisterInfo * TRI) static
Go up the super-register chain until we hit a valid dwarf register number.
Definition at line 142 of file StackMaps.cpp.
References llvm::MCRegisterInfo::getDwarfRegNum(), and llvm::MCRegisterInfo::DiffListIterator::isValid().
Variable Documentation
StackMapVersion
cl::opt< int > StackMapVersion("stackmap-version", cl::init(1), cl::desc("Specify the stackmap encoding version (default = 1)")) ("stackmap-version" , cl::init(1) , cl::desc("Specify the stackmap encoding version (default = 1)")) static
Referenced by llvm::StackMaps::StackMaps().