LLVM: Statistic.cpp File Reference
LLVM API Documentation
Statistic.cpp File Reference
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstring>
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Functions
raw_ostream * llvm::CreateInfoOutputFile ()
Variables
static cl::opt< bool > Enabled ("stats", cl::desc("Enable statistics output from program (available with Asserts)"))
static ManagedStatic< StatisticInfo > StatInfo
static ManagedStatic< sys::SmartMutex< true > > StatLock
Variable Documentation
Enabled
cl::opt< bool > Enabled("stats", cl::desc("Enable statistics output from program (available with Asserts)")) ("stats" , cl::desc("Enable statistics output from program (available with Asserts)")) static
-stats - Command line option to cause transformations to emit stats about what they did.
Referenced by llvm::AreStatisticsEnabled(), llvm::MipsTargetAsmStreamer::emitDirectiveModuleOddSPReg(), llvm::MipsTargetELFStreamer::emitDirectiveModuleOddSPReg(), llvm::MipsTargetStreamer::emitDirectiveModuleOddSPReg(), llvm::EnableStatistics(), llvm::NamedRegionTimer::NamedRegionTimer(), llvm::NamedRegionTimer::NamedRegionTimer(), llvm::PrintStatistics(), and llvm::Statistic::RegisterStatistic().
StatInfo
ManagedStatic<StatisticInfo> StatInfo static
Definition at line 65 of file Statistic.cpp.
Referenced by llvm::PrintStatistics(), llvm::PrintStatistics(), and llvm::Statistic::RegisterStatistic().
StatLock
ManagedStatic<sys::SmartMutex<true> > StatLock static
Definition at line 66 of file Statistic.cpp.
Referenced by llvm::Statistic::RegisterStatistic().