LLVM: StatepointLowering.cpp File Reference
LLVM API Documentation
StatepointLowering.cpp File Reference
#include "StatepointLowering.h"
#include "SelectionDAGBuilder.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/GCStrategy.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Statepoint.h"
#include "llvm/Target/TargetLowering.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "statepoint-lowering"
Functions
STATISTIC (NumSlotsAllocatedForStatepoints, "Number of stack slots allocated for statepoints")
STATISTIC (NumOfStatepoints, "Number of statepoint nodes encountered")
STATISTIC (StatepointMaxSlotsRequired, "Maximum number of stack slots required for a singe statepoint")
static void reservePreviousStackSlotForValue (SDValue Incoming, SelectionDAGBuilder &Builder)
static void removeDuplicatesGCPtrs (SmallVectorImpl< const Value * > &Bases, SmallVectorImpl< const Value * > &Ptrs, SmallVectorImpl< const Value * > &Relocs, SelectionDAGBuilder &Builder)
static SDNode * lowerCallFromStatepoint (const CallInst &CI, SelectionDAGBuilder &Builder)
static void getIncomingStatepointGCValues (SmallVectorImpl< const Value * > &Bases, SmallVectorImpl< const Value * > &Ptrs, SmallVectorImpl< const Value * > &Relocs, ImmutableCallSite Statepoint, SelectionDAGBuilder &Builder)
static std::pair< SDValue, SDValue > spillIncomingStatepointValue (SDValue Incoming, SDValue Chain, SelectionDAGBuilder &Builder)
static void lowerIncomingStatepointValue (SDValue Incoming, SmallVectorImpl< SDValue > &Ops, SelectionDAGBuilder &Builder)
static void lowerStatepointMetaArgs (SmallVectorImpl< SDValue > &Ops, ImmutableStatepoint Statepoint, SelectionDAGBuilder &Builder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "statepoint-lowering"
Definition at line 32 of file StatepointLowering.cpp.
Function Documentation
getIncomingStatepointGCValues()
void getIncomingStatepointGCValues (SmallVectorImpl< const Value * > & Bases, SmallVectorImpl< const Value * > & Ptrs, SmallVectorImpl< const Value * > & Relocs, ImmutableCallSite Statepoint, SelectionDAGBuilder & Builder) static
Callect all gc pointers coming into statepoint intrinsic, clean them up, and return two arrays: Bases - base pointers incoming to this statepoint Ptrs - derived pointers incoming to this statepoint Relocs - the gc_relocate corresponding to each base/ptr pair Elements of this arrays should be in one-to-one correspondence with each other i.e Bases[i], Ptrs[i] are from the same gcrelocate call
Definition at line 304 of file StatepointLowering.cpp.
References llvm::GCRelocateOperands::basePtr(), llvm::cast(), llvm::GCRelocateOperands::derivedPtr(), llvm::isGCRelocate(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), removeDuplicatesGCPtrs(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by lowerStatepointMetaArgs().
lowerCallFromStatepoint()
SDNode * lowerCallFromStatepoint (const CallInst & CI, SelectionDAGBuilder & Builder) static
Extract call from statepoint, lower it and return pointer to the call node. Also update NodeMap so that getValue(statepoint) will reference lowered call result
Definition at line 225 of file StatepointLowering.cpp.
References llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::actualCallee(), llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::call_args_begin(), llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::call_args_end(), llvm::ISD::CALLSEQ_END, llvm::CallInst::Create(), llvm::SelectionDAGBuilder::DAG, llvm::dyn_cast(), llvm::Intrinsic::experimental_gc_statepoint, llvm::CallInst::getAttributes(), llvm::CallInst::getCallingConv(), llvm::SDNode::getGluedNode(), llvm::SelectionDAG::getIntPtrConstant(), getIntrinsicID(), llvm::SDNode::getOpcode(), llvm::SelectionDAG::getRoot(), llvm::Value::getType(), llvm::SelectionDAGBuilder::getValue(), llvm::CallInst::isTailCall(), llvm::Type::isVoidTy(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::SelectionDAGBuilder::removeValue(), llvm::CallInst::setAttributes(), llvm::CallInst::setCallingConv(), llvm::CallInst::setTailCall(), and llvm::SelectionDAGBuilder::setValue().
lowerIncomingStatepointValue()
void lowerIncomingStatepointValue (SDValue Incoming, SmallVectorImpl< SDValue > & Ops, SelectionDAGBuilder & Builder) static
Lower a single value incoming to a statepoint node. This value can be either a deopt value or a gc value, the handling is the same. We special case constants and allocas, then fall back to spilling if required.
Definition at line 369 of file StatepointLowering.cpp.
References llvm::StackMaps::ConstantOp, llvm::SelectionDAGBuilder::DAG, llvm::dyn_cast(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAGBuilder::getRoot(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MVT::i64, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SelectionDAG::setRoot(), and spillIncomingStatepointValue().
Referenced by lowerStatepointMetaArgs().
lowerStatepointMetaArgs()
void lowerStatepointMetaArgs (SmallVectorImpl< SDValue > & Ops, ImmutableStatepoint Statepoint, SelectionDAGBuilder & Builder) static
Lower deopt state and gc pointer arguments of the statepoint. The actual lowering is described in lowerIncomingStatepointValue. This function is responsible for lowering everything in the right position and playing some tricks to avoid redundant stack manipulation where possible. On completion, 'Ops' will contain ready to use operands for machine code statepoint. The chain nodes will have already been created and the DAG root will be set to the last value spilled (if any were).
Definition at line 410 of file StatepointLowering.cpp.
References llvm::StackMaps::ConstantOp, llvm::SelectionDAGBuilder::DAG, llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::getCallSite(), getIncomingStatepointGCValues(), llvm::GCFunctionInfo::getStrategy(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAGBuilder::getValue(), llvm::SelectionDAGBuilder::GFI, I, llvm::MVT::i64, llvm::GCStrategy::isGCManagedPointer(), lowerIncomingStatepointValue(), llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::numTotalVMSArgs(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), reservePreviousStackSlotForValue(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::vm_state_begin(), and llvm::StatepointBase< InstructionTy, ValueTy, CallSiteTy >::vm_state_end().
removeDuplicatesGCPtrs()
void removeDuplicatesGCPtrs (SmallVectorImpl< const Value * > & Bases, SmallVectorImpl< const Value * > & Ptrs, SmallVectorImpl< const Value * > & Relocs, SelectionDAGBuilder & Builder) static
Remove any duplicate (as SDValues) from the derived pointer pairs. This is not required for correctness. It's purpose is to reduce the size of StackMap section. It has no effect on the number of spill slots required or the actual lowering.
Definition at line 193 of file StatepointLowering.cpp.
References llvm::SmallSet< T, N, C >::count(), llvm::SelectionDAGBuilder::getValue(), llvm::SmallSet< T, N, C >::insert(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by getIncomingStatepointGCValues().
reservePreviousStackSlotForValue()
void reservePreviousStackSlotForValue (SDValue Incoming, SelectionDAGBuilder & Builder) static
Try to find existing copies of the incoming values in stack slots used for statepoint spilling. If we can find a spill slot for the incoming value, mark that slot as allocated, and reuse the same slot for this safepoint. This helps to avoid series of loads and stores that only serve to resuffle values on the stack between calls.
Definition at line 114 of file StatepointLowering.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SelectionDAGBuilder::DAG, llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SelectionDAGBuilder::FuncInfo, llvm::StatepointLoweringState::getLocation(), llvm::SDValue::getNode(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::SDValue::getValueType(), llvm::isa(), llvm::StatepointLoweringState::isStackSlotAllocated(), llvm::StatepointLoweringState::reserveStackSlot(), llvm::StatepointLoweringState::setLocation(), llvm::SelectionDAGBuilder::StatepointLowering, and llvm::FunctionLoweringInfo::StatepointStackSlots.
Referenced by lowerStatepointMetaArgs().
spillIncomingStatepointValue()
std::pair< SDValue, SDValue > spillIncomingStatepointValue (SDValue Incoming, SDValue Chain, SelectionDAGBuilder & Builder) static
Spill a value incoming to the statepoint. It might be either part of vmstate or gcstate. In both cases unconditionally spill it on the stack unless it is a null constant. Return pair with first element being frame index containing saved value and second element with outgoing chain from the emitted store
Definition at line 339 of file StatepointLowering.cpp.
References llvm::StatepointLoweringState::allocateStackSlot(), llvm::cast(), llvm::SelectionDAGBuilder::DAG, llvm::SelectionDAGBuilder::getCurSDLoc(), llvm::MachinePointerInfo::getFixedStack(), llvm::StatepointLoweringState::getLocation(), llvm::SDValue::getNode(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::SDValue::getValueType(), llvm::isa(), llvm::StatepointLoweringState::setLocation(), and llvm::SelectionDAGBuilder::StatepointLowering.
Referenced by lowerIncomingStatepointValue().
STATISTIC() [1/3]
STATISTIC (NumOfStatepoints , "Number of statepoint nodes encountered")
STATISTIC() [2/3]
STATISTIC (NumSlotsAllocatedForStatepoints , "Number of stack slots allocated for statepoints")
STATISTIC() [3/3]
STATISTIC (StatepointMaxSlotsRequired , "Maximum number of stack slots required for a singe statepoint")