LLVM: llvm::Linker::StructTypeKeyInfo Struct Reference
LLVM API Documentation
llvm::Linker::StructTypeKeyInfo Struct Reference
#include <Linker.h>
Classes
struct KeyTy
Static Public Member Functions
static StructType * getEmptyKey ()
static StructType * getTombstoneKey ()
static unsigned getHashValue (const KeyTy &Key)
static unsigned getHashValue (const StructType *ST)
static bool isEqual (const KeyTy &LHS, const StructType *RHS)
static bool isEqual (const StructType *LHS, const StructType *RHS)
Detailed Description
Definition at line 29 of file llvm/Linker/Linker.h.
Member Function Documentation
getEmptyKey()
StructType * Linker::StructTypeKeyInfo::getEmptyKey () static
Definition at line 1625 of file LinkModules.cpp.
Referenced by isEqual(), and isEqual().
getHashValue() [1/2]
unsigned Linker::StructTypeKeyInfo::getHashValue (const KeyTy & Key) static
Definition at line 1633 of file LinkModules.cpp.
References llvm::Linker::StructTypeKeyInfo::KeyTy::ETypes, llvm::hash_combine(), llvm::hash_combine_range(), and llvm::Linker::StructTypeKeyInfo::KeyTy::IsPacked.
Referenced by getHashValue().
getHashValue() [2/2]
unsigned Linker::StructTypeKeyInfo::getHashValue (const StructType * ST) static
Definition at line 1638 of file LinkModules.cpp.
References getHashValue().
getTombstoneKey()
StructType * Linker::StructTypeKeyInfo::getTombstoneKey () static
Definition at line 1629 of file LinkModules.cpp.
Referenced by isEqual(), and isEqual().
isEqual() [1/2]
bool Linker::StructTypeKeyInfo::isEqual (const KeyTy & LHS, const StructType * RHS) static
Definition at line 1642 of file LinkModules.cpp.
References getEmptyKey(), and getTombstoneKey().
isEqual() [2/2]
bool Linker::StructTypeKeyInfo::isEqual (const StructType * LHS, const StructType * RHS) static
Definition at line 1649 of file LinkModules.cpp.
References getEmptyKey(), and getTombstoneKey().
The documentation for this struct was generated from the following files:
llvm/Linker/Linker.h
LinkModules.cpp