LLVM: llvm::Inliner Struct Reference
LLVM API Documentation
llvm::Inliner Struct Reference abstract
#include <InlinerPass.h>
Public Member Functions
Inliner (char &ID)
Inliner (char &ID, int Threshold, bool InsertLifetime)
void getAnalysisUsage (AnalysisUsage &Info) const override
bool runOnSCC (CallGraphSCC &SCC) override
bool doFinalization (CallGraph &CG) override
unsigned getInlineThreshold () const
unsigned getInlineThreshold (CallSite CS) const
virtual InlineCost getInlineCost (CallSite CS)=0
bool removeDeadFunctions (CallGraph &CG, bool AlwaysInlineOnly=false)
virtual bool doFinalization (Module &)
Public Member Functions inherited from llvm::CallGraphSCCPass
CallGraphSCCPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
virtual bool doInitialization (CallGraph &CG)
void assignPassManager (PMStack &PMS, PassManagerType PMT) override
Assign pass manager to manager this pass.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
virtual bool doInitialization (Module &)
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Inliner - This class contains all of the helper code which is used to perform the inlining operations that do not depend on the policy.
Definition at line 32 of file InlinerPass.h.
Constructor & Destructor Documentation
Inliner() [1/2]
Inliner::Inliner (char & ID) explicit
Definition at line 67 of file Inliner.cpp.
References llvm::CallGraphSCCPass::CallGraphSCCPass(), InlineLimit, and true.
Inliner() [2/2]
Inliner::Inliner (char & ID, int Threshold, bool InsertLifetime) explicit
Definition at line 70 of file Inliner.cpp.
References llvm::CallGraphSCCPass::CallGraphSCCPass(), InlineLimit, and Threshold.
Member Function Documentation
doFinalization() [1/2]
bool Inliner::doFinalization (CallGraph & CG) override virtual
doFinalization - This method is called after the SCC's of the program has been processed, allowing the pass to do final cleanup as necessary.
Reimplemented from llvm::CallGraphSCCPass.
Definition at line 641 of file Inliner.cpp.
References removeDeadFunctions().
doFinalization() [2/2]
virtual bool llvm::Pass::doFinalization (Module &) inline virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::CallGraphSCCPass.
Definition at line 116 of file Pass.h.
getAnalysisUsage()
void Inliner::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - For this class, we declare that we require and preserve the call graph. If the derived class implements this method, it should always explicitly call the implementation here.
Reimplemented from llvm::CallGraphSCCPass.
Definition at line 78 of file Inliner.cpp.
References llvm::AnalysisUsage::addRequired(), and llvm::CallGraphSCCPass::getAnalysisUsage().
getInlineCost()
virtual InlineCost llvm::Inliner::getInlineCost (CallSite CS) pure virtual
getInlineCost - This method must be implemented by the subclass to determine the cost of inlining the specified call site. If the cost returned is greater than the current inline threshold, the call site is not inlined.
getInlineThreshold() [1/2]
unsigned llvm::Inliner::getInlineThreshold () const inline
This method returns the value specified by the -inline-threshold value, specified on the command line. This is typically not directly needed.
Definition at line 53 of file InlinerPass.h.
getInlineThreshold() [2/2]
unsigned Inliner::getInlineThreshold (CallSite CS) const
Calculate the inline threshold for given Caller. This threshold is lower if the caller is marked with OptimizeForSize and -inline-threshold is not given on the comand line. It is higher if the callee is marked with the inlinehint attribute.
Definition at line 268 of file Inliner.cpp.
References llvm::Attribute::Cold, ColdThreshold, llvm::AttributeSet::FunctionIndex, llvm::Function::getAttributes(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCaller(), llvm::AttributeSet::hasAttribute(), HintThreshold, llvm::Attribute::InlineHint, InlineLimit, llvm::GlobalValue::isDeclaration(), llvm::Attribute::MinSize, llvm::Attribute::OptimizeForSize, and OptSizeThreshold.
removeDeadFunctions()
bool Inliner::removeDeadFunctions (CallGraph & CG, bool AlwaysInlineOnly = false)
removeDeadFunctions - Remove dead functions.
This also includes a hack in the form of the 'AlwaysInlineOnly' flag which restricts it to deleting functions with an 'AlwaysInline' attribute. This is useful for the InlineAlways pass that only wants to deal with that subset of the functions.
removeDeadFunctions - Remove dead functions that are not included in DNR (Do Not Remove) list.
Definition at line 647 of file Inliner.cpp.
References llvm::Attribute::AlwaysInline, llvm::array_pod_sort(), llvm::CallGraph::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::empty(), llvm::CallGraph::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), F, llvm::AttributeSet::FunctionIndex, llvm::CallGraph::getExternalCallingNode(), llvm::CallGraphNode::getFunction(), I, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::CallGraphNode::removeAllCalledFunctions(), llvm::CallGraphNode::removeAnyCallEdgeTo(), and llvm::CallGraph::removeFunctionFromModule().
Referenced by doFinalization().
runOnSCC()
bool Inliner::runOnSCC (CallGraphSCC & SCC) override virtual
runOnSCC - This method should be implemented by the subclass to perform whatever action is necessary for the specified SCC. Note that non-recursive (or only self-recursive) functions will have an SCC size of 1, where recursive portions of the call graph will have SCC size > 1.
SCC passes that add or delete functions to the SCC are required to update the SCC list, otherwise stale pointers may be dereferenced.
Implements llvm::CallGraphSCCPass.
Definition at line 444 of file Inliner.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::CallGraphSCC::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::cast(), Changed, llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), DEBUG, DEBUG_TYPE, llvm::emitOptimizationRemark(), llvm::emitOptimizationRemarkMissed(), llvm::SmallVectorBase::empty(), llvm::CallGraphSCC::end(), llvm::SmallVectorImpl< T >::erase(), llvm::Instruction::eraseFromParent(), F, llvm::Pass::getAnalysis(), llvm::Pass::getAnalysisIfAvailable(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCaller(), llvm::Function::getContext(), llvm::DataLayoutPass::getDataLayout(), llvm::Instruction::getDebugLoc(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::Value::getName(), llvm::GlobalValue::hasLocalLinkage(), I, InlineCallIfPossible(), llvm::InlineFunctionInfo::InlinedCalls, InlineHistoryIncludes(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::GlobalValue::isDeclaration(), llvm::isInstructionTriviallyDead(), llvm::CallGraphSCC::isSingular(), llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::CallGraphNode::removeAllCalledFunctions(), llvm::CallGraph::removeFunctionFromModule(), llvm::SmallVectorTemplateCommon< T, typename >::size(), std::swap(), and llvm::Value::use_empty().
The documentation for this struct was generated from the following files:
InlinerPass.h
Inliner.cpp