LLVM: llvm::SystemZRegisterInfo Struct Reference
LLVM API Documentation
llvm::SystemZRegisterInfo Struct Reference
#include <SystemZRegisterInfo.h>
Public Member Functions
SystemZRegisterInfo ()
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool requiresFrameIndexScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF=nullptr) const override
const uint32_t * getCallPreservedMask (CallingConv::ID CC) const override
BitVector getReservedRegs (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS) const override
unsigned getFrameRegister (const MachineFunction &MF) const override
Detailed Description
Definition at line 32 of file SystemZRegisterInfo.h.
Constructor & Destructor Documentation
SystemZRegisterInfo()
SystemZRegisterInfo::SystemZRegisterInfo ()
Definition at line 22 of file SystemZRegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void SystemZRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS) const override
Definition at line 57 of file SystemZRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::TargetFrameLowering::getFrameIndexOffset(), llvm::TargetSubtargetInfo::getFrameLowering(), getFrameRegister(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::SystemZII::HasIndex, llvm::RegState::Kill, and TII.
getCalleeSavedRegs()
const MCPhysReg * SystemZRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = nullptr) const override
Definition at line 26 of file SystemZRegisterInfo.cpp.
getCallPreservedMask()
const uint32_t * SystemZRegisterInfo::getCallPreservedMask (CallingConv::ID CC) const override
Definition at line 31 of file SystemZRegisterInfo.cpp.
getFrameRegister()
unsigned SystemZRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 136 of file SystemZRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), and llvm::TargetFrameLowering::hasFP().
Referenced by eliminateFrameIndex().
getReservedRegs()
BitVector SystemZRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 36 of file SystemZRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), and llvm::BitVector::set().
requiresFrameIndexScavenging()
bool llvm::SystemZRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline override
Definition at line 40 of file SystemZRegisterInfo.h.
requiresRegisterScavenging()
bool llvm::SystemZRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline override
Definition at line 37 of file SystemZRegisterInfo.h.
trackLivenessAfterRegAlloc()
bool llvm::SystemZRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const inline override
Definition at line 43 of file SystemZRegisterInfo.h.
The documentation for this struct was generated from the following files:
SystemZRegisterInfo.h
SystemZRegisterInfo.cpp