LLVM: llvm::ELF::Elf32_Sym Struct Reference
LLVM API Documentation
llvm::ELF::Elf32_Sym Struct Reference
#include <ELF.h>
Public Member Functions
unsigned char getBinding () const
unsigned char getType () const
void setBinding (unsigned char b)
void setType (unsigned char t)
void setBindingAndType (unsigned char b, unsigned char t)
Public Attributes
Elf32_Word st_name
Elf32_Addr st_value
Elf32_Word st_size
unsigned char st_info
unsigned char st_other
Elf32_Half st_shndx
Detailed Description
Definition at line 714 of file Support/ELF.h.
Member Function Documentation
getBinding()
unsigned char llvm::ELF::Elf32_Sym::getBinding () const inline
Definition at line 724 of file Support/ELF.h.
References st_info.
Referenced by setType().
getType()
unsigned char llvm::ELF::Elf32_Sym::getType () const inline
Definition at line 725 of file Support/ELF.h.
References st_info.
Referenced by setBinding().
setBinding()
void llvm::ELF::Elf32_Sym::setBinding (unsigned char b) inline
Definition at line 726 of file Support/ELF.h.
References getType(), and setBindingAndType().
setBindingAndType()
void llvm::ELF::Elf32_Sym::setBindingAndType (unsigned char b, unsigned char t) inline
Definition at line 728 of file Support/ELF.h.
References st_info.
Referenced by setBinding(), and setType().
setType()
void llvm::ELF::Elf32_Sym::setType (unsigned char t) inline
Definition at line 727 of file Support/ELF.h.
References getBinding(), and setBindingAndType().
Member Data Documentation
st_info
unsigned char llvm::ELF::Elf32_Sym::st_info
Definition at line 718 of file Support/ELF.h.
Referenced by getBinding(), getType(), and setBindingAndType().
st_name
Elf32_Word llvm::ELF::Elf32_Sym::st_name
Definition at line 715 of file Support/ELF.h.
st_other
unsigned char llvm::ELF::Elf32_Sym::st_other
Definition at line 719 of file Support/ELF.h.
st_shndx
Elf32_Half llvm::ELF::Elf32_Sym::st_shndx
Definition at line 720 of file Support/ELF.h.
st_size
Elf32_Word llvm::ELF::Elf32_Sym::st_size
Definition at line 717 of file Support/ELF.h.
st_value
Elf32_Addr llvm::ELF::Elf32_Sym::st_value
Definition at line 716 of file Support/ELF.h.
The documentation for this struct was generated from the following file:
Support/ELF.h