LLVM: llvm::MachinePointerInfo Struct Reference
LLVM API Documentation
llvm::MachinePointerInfo Struct Reference
#include <MachineMemOperand.h>
Public Member Functions
MachinePointerInfo (const Value *v=nullptr, int64_t offset=0)
MachinePointerInfo (const PseudoSourceValue *v, int64_t offset=0)
MachinePointerInfo getWithOffset (int64_t O) const
unsigned getAddrSpace () const
Static Public Member Functions
static MachinePointerInfo getConstantPool ()
static MachinePointerInfo getFixedStack (int FI, int64_t offset=0)
static MachinePointerInfo getJumpTable ()
static MachinePointerInfo getGOT ()
static MachinePointerInfo getStack (int64_t Offset)
getStack - stack pointer relative access.
Public Attributes
PointerUnion< const Value *, const PseudoSourceValue * > V
int64_t Offset
Offset - This is an offset from the base Value*.
Detailed Description
MachinePointerInfo - This class contains a discriminated union of information about pointers in memory operands, relating them back to LLVM IR or to virtual locations (such as frame indices) that are exposed during codegen.
Definition at line 35 of file MachineMemOperand.h.
Constructor & Destructor Documentation
MachinePointerInfo() [1/2]
llvm::MachinePointerInfo::MachinePointerInfo (const Value * v = nullptr, int64_t offset = 0) inline explicit
Definition at line 44 of file MachineMemOperand.h.
References Offset, and V.
Referenced by getConstantPool(), getFixedStack(), getGOT(), getJumpTable(), getStack(), and getWithOffset().
MachinePointerInfo() [2/2]
llvm::MachinePointerInfo::MachinePointerInfo (const PseudoSourceValue * v, int64_t offset = 0) inline explicit
Definition at line 47 of file MachineMemOperand.h.
References Offset, and V.
Member Function Documentation
getAddrSpace()
unsigned MachinePointerInfo::getAddrSpace () const
getAddrSpace - Return the LLVM IR address space number that this pointer points into.
Definition at line 421 of file MachineInstr.cpp.
References llvm::cast(), llvm::Value::getType(), and V.
Referenced by AddNodeIDCustom(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::MemSDNode::getAddressSpace(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getStore(), and llvm::SelectionDAG::getTruncStore().
getConstantPool()
MachinePointerInfo MachinePointerInfo::getConstantPool () static
getConstantPool - Return a MachinePointerInfo record that refers to the constant pool.
Definition at line 428 of file MachineInstr.cpp.
References llvm::PseudoSourceValue::getConstantPool(), and MachinePointerInfo().
Referenced by LowerFABSorFNEG(), LowerFCOPYSIGN(), LowerSIGN_EXTEND_AVX512(), LowerVectorBroadcast(), and LowerZERO_EXTEND_AVX512().
getFixedStack()
MachinePointerInfo MachinePointerInfo::getFixedStack (int FI, int64_t offset = 0) static
getFixedStack - Return a MachinePointerInfo record that refers to the the specified FrameIndex.
Definition at line 434 of file MachineInstr.cpp.
References llvm::PseudoSourceValue::getFixedStack(), and MachinePointerInfo().
Referenced by llvm::addFrameReference(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLoweringBase::emitPatchPoint(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::TargetInstrInfo::foldMemoryOperand(), getFrameIndexMMO(), llvm::MipsInstrInfo::GetMemOperand(), InferPointerInfo(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::SystemZTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), spillIncomingStatepointValue(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), StoreTailCallArgumentsToStackSlot(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getGOT()
MachinePointerInfo MachinePointerInfo::getGOT () static
getGOT - Return a MachinePointerInfo record that refers to a GOT entry.
Definition at line 442 of file MachineInstr.cpp.
References llvm::PseudoSourceValue::getGOT(), and MachinePointerInfo().
Referenced by expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::MipsTargetLowering::getAddrLocal(), LowerToTLSExecModel(), and llvm::SparcTargetLowering::makeAddress().
getJumpTable()
MachinePointerInfo MachinePointerInfo::getJumpTable () static
getJumpTable - Return a MachinePointerInfo record that refers to a jump table entry.
Definition at line 438 of file MachineInstr.cpp.
References llvm::PseudoSourceValue::getJumpTable(), and MachinePointerInfo().
getStack()
MachinePointerInfo MachinePointerInfo::getStack (int64_t Offset) static
getStack - stack pointer relative access.
Definition at line 446 of file MachineInstr.cpp.
References llvm::PseudoSourceValue::getStack(), MachinePointerInfo(), and Offset.
getWithOffset()
MachinePointerInfo llvm::MachinePointerInfo::getWithOffset (int64_t O) const inline
Definition at line 51 of file MachineMemOperand.h.
References MachinePointerInfo(), Offset, and V.
Referenced by llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), PerformSTORECombine(), llvm::AMDGPUTargetLowering::ScalarizeVectorLoad(), llvm::AMDGPUTargetLowering::ScalarizeVectorStore(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
Member Data Documentation
Offset
int64_t llvm::MachinePointerInfo::Offset
Offset - This is an offset from the base Value*.
Definition at line 42 of file MachineMemOperand.h.
Referenced by getStack(), getWithOffset(), MachinePointerInfo(), and MachinePointerInfo().
V
PointerUnion<const Value *, const PseudoSourceValue *> llvm::MachinePointerInfo::V
V - This is the IR pointer value for the access, or it is null if unknown. If this is null, then the access is to a pointer in the default address space.
Definition at line 39 of file MachineMemOperand.h.
Referenced by getAddrSpace(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), getWithOffset(), MachinePointerInfo(), and MachinePointerInfo().
The documentation for this struct was generated from the following files:
MachineMemOperand.h
MachineInstr.cpp