LLVM: llvm::LeakDetectorImpl< T > Struct Template Reference
LLVM API Documentation
llvm::LeakDetectorImpl< T > Struct Template Reference
#include <LeaksContext.h>
Public Member Functions
LeakDetectorImpl (const char *const name="")
void clear ()
void setName (const char *n)
void addGarbage (const T *o)
void removeGarbage (const T *o)
bool hasGarbage (const std::string &Message)
Detailed Description
template<typename T>
struct llvm::LeakDetectorImpl< T >
Definition at line 40 of file LeaksContext.h.
Constructor & Destructor Documentation
LeakDetectorImpl()
template<typename T> llvm::LeakDetectorImpl< T >::LeakDetectorImpl (const char *const name = "") inline explicit
Definition at line 41 of file LeaksContext.h.
Member Function Documentation
addGarbage()
template<typename T> void llvm::LeakDetectorImpl< T >::addGarbage (const T * o) inline
Definition at line 58 of file LeaksContext.h.
References T.
Referenced by hasGarbage().
clear()
template<typename T> void llvm::LeakDetectorImpl< T >::clear () inline
Definition at line 44 of file LeaksContext.h.
hasGarbage()
template<typename T> bool llvm::LeakDetectorImpl< T >::hasGarbage (const std::string & Message) inline
Definition at line 74 of file LeaksContext.h.
References addGarbage(), llvm::errs(), I, and llvm::PrinterTrait< T >::print().
removeGarbage()
template<typename T> void llvm::LeakDetectorImpl< T >::removeGarbage (const T * o) inline
Definition at line 67 of file LeaksContext.h.
References T.
setName()
template<typename T> void llvm::LeakDetectorImpl< T >::setName (const char * n) inline
Definition at line 49 of file LeaksContext.h.
The documentation for this struct was generated from the following file:
LeaksContext.h