LLVM: llvm::GraphTraits< const CallGraphNode * > Struct Reference
LLVM API Documentation
llvm::GraphTraits< const CallGraphNode * > Struct Reference
#include <CallGraph.h>
Public Types
typedef const CallGraphNode NodeType
typedef CallGraphNode::CallRecord CGNPairTy
typedef std::pointer_to_unary_function< CGNPairTy, const CallGraphNode * > CGNDerefFun
typedef mapped_iterator< NodeType::const_iterator, CGNDerefFun > ChildIteratorType
Static Public Member Functions
static NodeType * getEntryNode (const CallGraphNode *CGN)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
static const CallGraphNode * CGNDeref (CGNPairTy P)
Detailed Description
Definition at line 418 of file CallGraph.h.
Member Typedef Documentation
CGNDerefFun
typedef std::pointer_to_unary_function<CGNPairTy, const CallGraphNode *> llvm::GraphTraits< const CallGraphNode * >::CGNDerefFun
Definition at line 423 of file CallGraph.h.
CGNPairTy
typedef CallGraphNode::CallRecord llvm::GraphTraits< const CallGraphNode * >::CGNPairTy
Definition at line 421 of file CallGraph.h.
ChildIteratorType
typedef mapped_iterator<NodeType::const_iterator, CGNDerefFun> llvm::GraphTraits< const CallGraphNode * >::ChildIteratorType
Definition at line 428 of file CallGraph.h.
NodeType
typedef const CallGraphNode llvm::GraphTraits< const CallGraphNode * >::NodeType
Definition at line 419 of file CallGraph.h.
Member Function Documentation
CGNDeref()
const CallGraphNode * llvm::GraphTraits< const CallGraphNode * >::CGNDeref (CGNPairTy P) inline static
Definition at line 437 of file CallGraph.h.
References P.
Referenced by child_begin(), and child_end().
child_begin()
ChildIteratorType llvm::GraphTraits< const CallGraphNode * >::child_begin (NodeType * N) inline static
Definition at line 430 of file CallGraph.h.
References CGNDeref(), llvm::map_iterator(), and N.
child_end()
ChildIteratorType llvm::GraphTraits< const CallGraphNode * >::child_end (NodeType * N) inline static
Definition at line 433 of file CallGraph.h.
References CGNDeref(), llvm::map_iterator(), and N.
getEntryNode()
NodeType * llvm::GraphTraits< const CallGraphNode * >::getEntryNode (const CallGraphNode * CGN) inline static
Definition at line 425 of file CallGraph.h.
The documentation for this struct was generated from the following file:
CallGraph.h