LLVM: llvm::LessRecordRegister Struct Reference
LLVM API Documentation
llvm::LessRecordRegister Struct Reference
#include <Record.h>
Classes
struct RecordParts
Public Member Functions
bool operator() (const Record *Rec1, const Record *Rec2) const
Static Public Member Functions
static size_t min (size_t a, size_t b)
static bool ascii_isdigit (char x)
Detailed Description
Definition at line 1743 of file Record.h.
Member Function Documentation
ascii_isdigit()
bool llvm::LessRecordRegister::ascii_isdigit (char x) inline static
Definition at line 1745 of file Record.h.
Referenced by llvm::LessRecordRegister::RecordParts::RecordParts().
min()
size_t llvm::LessRecordRegister::min (size_t a, size_t b) inline static
Definition at line 1744 of file Record.h.
operator()()
bool llvm::LessRecordRegister::operator() (const Record * Rec1, const Record * Rec2) const inline
Definition at line 1779 of file Record.h.
References llvm::Record::getName(), llvm::LessRecordRegister::RecordParts::getPart(), I, and llvm::LessRecordRegister::RecordParts::size().
The documentation for this struct was generated from the following file:
Record.h