LLVM: llvm::COFF::ImportLookupTableEntry32 Struct Reference
LLVM API Documentation
llvm::COFF::ImportLookupTableEntry32 Struct Reference
The PE32 Import Lookup Table.
#include <COFF.h>
Public Member Functions
bool isOrdinal () const
Is this entry specified by ordinal, or name?
uint16_t getOrdinal () const
Get the ordinal value of this entry. isOrdinal must be true.
void setOrdinal (uint16_t o)
Set the ordinal value and set isOrdinal to true.
uint32_t getHintNameRVA () const
Get the Hint/Name entry RVA. isOrdinal must be false.
void setHintNameRVA (uint32_t rva)
Set the Hint/Name entry RVA and set isOrdinal to false.
Public Attributes
uint32_t data
Detailed Description
The PE32 Import Lookup Table.
There is an array of these for each imported DLL. It represents either the ordinal to import from the target DLL, or a name to lookup and import from the target DLL.
This also happens to be the same format used by the Import Address Table when it is initially written out to the image.
Definition at line 438 of file Support/COFF.h.
Member Function Documentation
getHintNameRVA()
uint32_t llvm::COFF::ImportLookupTableEntry32::getHintNameRVA () const inline
Get the Hint/Name entry RVA. isOrdinal must be false.
Definition at line 457 of file Support/COFF.h.
References data, and isOrdinal().
getOrdinal()
uint16_t llvm::COFF::ImportLookupTableEntry32::getOrdinal () const inline
Get the ordinal value of this entry. isOrdinal must be true.
Definition at line 445 of file Support/COFF.h.
References data, and isOrdinal().
isOrdinal()
bool llvm::COFF::ImportLookupTableEntry32::isOrdinal () const inline
Is this entry specified by ordinal, or name?
Definition at line 442 of file Support/COFF.h.
References data.
Referenced by getHintNameRVA(), and getOrdinal().
setHintNameRVA()
void llvm::COFF::ImportLookupTableEntry32::setHintNameRVA (uint32_t rva) inline
Set the Hint/Name entry RVA and set isOrdinal to false.
Definition at line 463 of file Support/COFF.h.
References data.
setOrdinal()
void llvm::COFF::ImportLookupTableEntry32::setOrdinal (uint16_t o) inline
Set the ordinal value and set isOrdinal to true.
Definition at line 451 of file Support/COFF.h.
References data.
Member Data Documentation
data
uint32_t llvm::COFF::ImportLookupTableEntry32::data
Definition at line 439 of file Support/COFF.h.
Referenced by getHintNameRVA(), getOrdinal(), isOrdinal(), setHintNameRVA(), and setOrdinal().
The documentation for this struct was generated from the following file:
Support/COFF.h