LLVM: llvm::HexagonRegisterInfo Struct Reference
LLVM API Documentation
llvm::HexagonRegisterInfo Struct Reference
#include <HexagonRegisterInfo.h>
Public Member Functions
HexagonRegisterInfo (HexagonSubtarget &st)
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF=nullptr) const override
Code Generation virtual methods...
const TargetRegisterClass *const * getCalleeSavedRegClasses (const MachineFunction *MF=nullptr) const
BitVector getReservedRegs (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
void determineFrameLayout (MachineFunction &MF) const
bool requiresRegisterScavenging (const MachineFunction &MF) const override
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const override
unsigned getRARegister () const
unsigned getFrameRegister (const MachineFunction &MF) const override
unsigned getFrameRegister () const
unsigned getStackRegister () const
Public Attributes
HexagonSubtarget & Subtarget
Detailed Description
Definition at line 45 of file HexagonRegisterInfo.h.
Constructor & Destructor Documentation
HexagonRegisterInfo()
HexagonRegisterInfo::HexagonRegisterInfo (HexagonSubtarget & st)
Definition at line 41 of file HexagonRegisterInfo.cpp.
References Subtarget.
Member Function Documentation
determineFrameLayout()
void llvm::HexagonRegisterInfo::determineFrameLayout (MachineFunction & MF) const
determineFrameLayout - Determine the size of the frame and maximum call frame size.
eliminateFrameIndex()
void HexagonRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 118 of file HexagonRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), getFrameRegister(), llvm::MachineFrameInfo::getObjectOffset(), getStackRegister(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasFP(), llvm::MachineFrameInfo::hasVarSizedObjects(), HEXAGON_RESERVED_REG_1, Hexagon_WordSize, llvm_unreachable, Subtarget, and TII.
getCalleeSavedRegClasses()
const TargetRegisterClass *const * HexagonRegisterInfo::getCalleeSavedRegClasses (const MachineFunction * MF = nullptr) const
Definition at line 90 of file HexagonRegisterInfo.cpp.
References llvm_unreachable, Subtarget, llvm::HexagonSubtarget::V1, llvm::HexagonSubtarget::V2, llvm::HexagonSubtarget::V3, llvm::HexagonSubtarget::V4, and llvm::HexagonSubtarget::V5.
getCalleeSavedRegs()
const MCPhysReg * HexagonRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = nullptr) const override
Code Generation virtual methods...
Definition at line 47 of file HexagonRegisterInfo.cpp.
References llvm_unreachable, Subtarget, llvm::HexagonSubtarget::V1, llvm::HexagonSubtarget::V2, llvm::HexagonSubtarget::V3, llvm::HexagonSubtarget::V4, and llvm::HexagonSubtarget::V5.
getFrameRegister() [1/2]
unsigned HexagonRegisterInfo::getFrameRegister () const
Definition at line 288 of file HexagonRegisterInfo.cpp.
Referenced by eliminateFrameIndex().
getFrameRegister() [2/2]
unsigned HexagonRegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 278 of file HexagonRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getSubtarget(), and llvm::TargetFrameLowering::hasFP().
Referenced by llvm::HexagonTargetLowering::LowerFRAMEADDR().
getRARegister()
unsigned HexagonRegisterInfo::getRARegister () const
Definition at line 274 of file HexagonRegisterInfo.cpp.
Referenced by llvm::HexagonTargetLowering::LowerINLINEASM().
getReservedRegs()
BitVector HexagonRegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 71 of file HexagonRegisterInfo.cpp.
References HEXAGON_RESERVED_REG_1, HEXAGON_RESERVED_REG_2, and llvm::BitVector::set().
getStackRegister()
unsigned HexagonRegisterInfo::getStackRegister () const
Definition at line 292 of file HexagonRegisterInfo.cpp.
Referenced by eliminateFrameIndex(), llvm::HexagonFrameLowering::emitPrologue(), llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::HexagonTargetLowering::LowerCall(), and llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC().
requiresRegisterScavenging()
bool llvm::HexagonRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline override
requiresRegisterScavenging - returns true since we may need scavenging for a temporary register when generating hardware loop instructions.
Definition at line 69 of file HexagonRegisterInfo.h.
trackLivenessAfterRegAlloc()
bool llvm::HexagonRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const inline override
Definition at line 73 of file HexagonRegisterInfo.h.
Member Data Documentation
Subtarget
HexagonSubtarget& llvm::HexagonRegisterInfo::Subtarget
Definition at line 46 of file HexagonRegisterInfo.h.
Referenced by areCombinableOperations(), eliminateFrameIndex(), getCalleeSavedRegClasses(), getCalleeSavedRegs(), HexagonRegisterInfo(), llvm::HexagonInstrInfo::isConditionalLoad(), llvm::HexagonInstrInfo::isConditionalStore(), and llvm::HexagonInstrInfo::mayBeNewStore().
The documentation for this struct was generated from the following files:
HexagonRegisterInfo.h
HexagonRegisterInfo.cpp