LLVM: llvm::GraphTraits< MachineRegionInfo * > Struct Reference
LLVM API Documentation
llvm::GraphTraits< MachineRegionInfo * > Struct Reference
#include <MachineRegionInfo.h>
Public Types
typedef df_iterator< NodeType *, SmallPtrSet< NodeType *, 8 >, false, GraphTraits< FlatIt< NodeType * > > > nodes_iterator
typedef MachineRegionInfo *::UnknownGraphTypeError NodeType
Public Types inherited from llvm::GraphTraits< FlatIt< MachineRegionNode * > >
typedef FlatIt< MachineRegionNode * >::UnknownGraphTypeError NodeType
Static Public Member Functions
static NodeType * getEntryNode (MachineRegionInfo *RI)
static nodes_iterator nodes_begin (MachineRegionInfo *RI)
static nodes_iterator nodes_end (MachineRegionInfo *RI)
Detailed Description
Definition at line 145 of file MachineRegionInfo.h.
Member Typedef Documentation
nodes_iterator
typedef df_iterator<NodeType*, SmallPtrSet<NodeType*, 8>, false, GraphTraits<FlatIt<NodeType*> > > llvm::GraphTraits< MachineRegionInfo * >::nodes_iterator
Definition at line 148 of file MachineRegionInfo.h.
NodeType
typedef MachineRegionInfo *::UnknownGraphTypeError llvm::GraphTraits< MachineRegionInfo * >::NodeType
Definition at line 60 of file GraphTraits.h.
Member Function Documentation
getEntryNode()
NodeType * llvm::GraphTraits< MachineRegionInfo * >::getEntryNode (MachineRegionInfo * RI) inline static
Definition at line 150 of file MachineRegionInfo.h.
References getEntryNode(), and llvm::RegionInfoBase< Tr >::getTopLevelRegion().
Referenced by getEntryNode(), nodes_begin(), and nodes_end().
nodes_begin()
nodes_iterator llvm::GraphTraits< MachineRegionInfo * >::nodes_begin (MachineRegionInfo * RI) inline static
Definition at line 153 of file MachineRegionInfo.h.
References llvm::df_iterator< NodeType *, SmallPtrSet< NodeType *, 8 >, false, GraphTraits< FlatIt< NodeType * > > >::begin(), and getEntryNode().
nodes_end()
nodes_iterator llvm::GraphTraits< MachineRegionInfo * >::nodes_end (MachineRegionInfo * RI) inline static
Definition at line 156 of file MachineRegionInfo.h.
References llvm::df_iterator< NodeType *, SmallPtrSet< NodeType *, 8 >, false, GraphTraits< FlatIt< NodeType * > > >::end(), and getEntryNode().
The documentation for this struct was generated from the following file:
MachineRegionInfo.h