LLVM: llvm::BlockFrequencyInfoImplBase::BlockNode Struct Reference
LLVM API Documentation
llvm::BlockFrequencyInfoImplBase::BlockNode Struct Reference
Representative of a block.
#include <BlockFrequencyInfoImpl.h>
Public Types
typedef uint32_t IndexType
Public Member Functions
bool operator== (const BlockNode &X) const
bool operator!= (const BlockNode &X) const
bool operator<= (const BlockNode &X) const
bool operator>= (const BlockNode &X) const
bool operator< (const BlockNode &X) const
bool operator> (const BlockNode &X) const
BlockNode ()
BlockNode (IndexType Index)
bool isValid () const
Static Public Member Functions
static size_t getMaxIndex ()
Public Attributes
IndexType Index
Detailed Description
Representative of a block.
This is a simple wrapper around an index into the reverse-post-order traversal of the blocks.
Unlike a block pointer, its order has meaning (location in the topological sort) and it's class is the same regardless of block type.
Definition at line 168 of file BlockFrequencyInfoImpl.h.
Member Typedef Documentation
IndexType
typedef uint32_t llvm::BlockFrequencyInfoImplBase::BlockNode::IndexType
Definition at line 169 of file BlockFrequencyInfoImpl.h.
Constructor & Destructor Documentation
BlockNode() [1/2]
llvm::BlockFrequencyInfoImplBase::BlockNode::BlockNode () inline
Definition at line 179 of file BlockFrequencyInfoImpl.h.
References Index.
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
BlockNode() [2/2]
llvm::BlockFrequencyInfoImplBase::BlockNode::BlockNode (IndexType Index) inline
Definition at line 180 of file BlockFrequencyInfoImpl.h.
References Index.
Member Function Documentation
getMaxIndex()
size_t llvm::BlockFrequencyInfoImplBase::BlockNode::getMaxIndex () inline static
Definition at line 183 of file BlockFrequencyInfoImpl.h.
Referenced by isValid().
isValid()
bool llvm::BlockFrequencyInfoImplBase::BlockNode::isValid () const inline
Definition at line 182 of file BlockFrequencyInfoImpl.h.
References getMaxIndex(), and Index.
Referenced by llvm::BlockFrequencyInfoImplBase::getBlockFreq(), and llvm::BlockFrequencyInfoImplBase::getFloatingBlockFreq().
operator!=()
bool llvm::BlockFrequencyInfoImplBase::BlockNode::operator!= (const BlockNode & X) const inline
Definition at line 173 of file BlockFrequencyInfoImpl.h.
References BlockNode(), Index, and llvm::X.
operator<()
bool llvm::BlockFrequencyInfoImplBase::BlockNode::operator< (const BlockNode & X) const inline
Definition at line 176 of file BlockFrequencyInfoImpl.h.
References BlockNode(), Index, and llvm::X.
operator<=()
bool llvm::BlockFrequencyInfoImplBase::BlockNode::operator<= (const BlockNode & X) const inline
Definition at line 174 of file BlockFrequencyInfoImpl.h.
References BlockNode(), Index, and llvm::X.
operator==()
bool llvm::BlockFrequencyInfoImplBase::BlockNode::operator== (const BlockNode & X) const inline
Definition at line 172 of file BlockFrequencyInfoImpl.h.
References BlockNode(), Index, and llvm::X.
operator>()
bool llvm::BlockFrequencyInfoImplBase::BlockNode::operator> (const BlockNode & X) const inline
Definition at line 177 of file BlockFrequencyInfoImpl.h.
References BlockNode(), Index, and llvm::X.
operator>=()
bool llvm::BlockFrequencyInfoImplBase::BlockNode::operator>= (const BlockNode & X) const inline
Definition at line 175 of file BlockFrequencyInfoImpl.h.
References BlockNode(), Index, and llvm::X.
Member Data Documentation
Index
IndexType llvm::BlockFrequencyInfoImplBase::BlockNode::Index
Definition at line 170 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::bfi_detail::IrreducibleGraph::addEdge(), llvm::bfi_detail::IrreducibleGraph::addEdges(), llvm::bfi_detail::IrreducibleGraph::addNode(), llvm::BlockFrequencyInfoImplBase::addToDist(), BlockNode(), BlockNode(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::BlockFrequencyInfoImplBase::getBlockFreq(), llvm::BlockFrequencyInfoImplBase::getFloatingBlockFreq(), isValid(), operator!=(), llvm::bfi_detail::BlockEdgesAdder< BT >::operator()(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and llvm::BlockFrequencyInfoImplBase::packageLoop().
The documentation for this struct was generated from the following file:
BlockFrequencyInfoImpl.h