LLVM: llvm::GenericSchedulerBase::SchedResourceDelta Struct Reference
LLVM API Documentation
llvm::GenericSchedulerBase::SchedResourceDelta Struct Reference
Status of an instruction's critical resource consumption.
#include <MachineScheduler.h>
Public Member Functions
SchedResourceDelta ()
bool operator== (const SchedResourceDelta &RHS) const
bool operator!= (const SchedResourceDelta &RHS) const
Public Attributes
unsigned CritResources
unsigned DemandedResources
Detailed Description
Status of an instruction's critical resource consumption.
Definition at line 765 of file MachineScheduler.h.
Constructor & Destructor Documentation
SchedResourceDelta()
llvm::GenericSchedulerBase::SchedResourceDelta::SchedResourceDelta () inline
Definition at line 772 of file MachineScheduler.h.
References CritResources, and DemandedResources.
Referenced by operator!=(), and operator==().
Member Function Documentation
operator!=()
bool llvm::GenericSchedulerBase::SchedResourceDelta::operator!= (const SchedResourceDelta & RHS) const inline
Definition at line 778 of file MachineScheduler.h.
References operator==(), and SchedResourceDelta().
operator==()
bool llvm::GenericSchedulerBase::SchedResourceDelta::operator== (const SchedResourceDelta & RHS) const inline
Definition at line 774 of file MachineScheduler.h.
References CritResources, DemandedResources, and SchedResourceDelta().
Referenced by operator!=().
Member Data Documentation
CritResources
unsigned llvm::GenericSchedulerBase::SchedResourceDelta::CritResources
Definition at line 767 of file MachineScheduler.h.
Referenced by operator==(), SchedResourceDelta(), llvm::GenericScheduler::tryCandidate(), and llvm::PostGenericScheduler::tryCandidate().
DemandedResources
unsigned llvm::GenericSchedulerBase::SchedResourceDelta::DemandedResources
Definition at line 770 of file MachineScheduler.h.
Referenced by operator==(), SchedResourceDelta(), llvm::GenericScheduler::tryCandidate(), and llvm::PostGenericScheduler::tryCandidate().
The documentation for this struct was generated from the following file:
MachineScheduler.h