LLVM: llvm::SCEVParameterRewriter Struct Reference
LLVM API Documentation
llvm::SCEVParameterRewriter Struct Reference
#include <ScalarEvolutionExpressions.h>
Public Member Functions
SCEVParameterRewriter (ScalarEvolution &S, ValueToValueMap &M, bool C)
const SCEV * visitConstant (const SCEVConstant *Constant)
const SCEV * visitTruncateExpr (const SCEVTruncateExpr *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitAddExpr (const SCEVAddExpr *Expr)
const SCEV * visitMulExpr (const SCEVMulExpr *Expr)
const SCEV * visitUDivExpr (const SCEVUDivExpr *Expr)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitSMaxExpr (const SCEVSMaxExpr *Expr)
const SCEV * visitUMaxExpr (const SCEVUMaxExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *Expr)
Public Member Functions inherited from llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >
const SCEV * visit (const SCEV *S)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *S)
Static Public Member Functions
static const SCEV * rewrite (const SCEV *Scev, ScalarEvolution &SE, ValueToValueMap &Map, bool InterpretConsts=false)
Detailed Description
The SCEVParameterRewriter takes a scalar evolution expression and updates the SCEVUnknown components following the Map (Value -> Value).
Definition at line 638 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVParameterRewriter()
llvm::SCEVParameterRewriter::SCEVParameterRewriter (ScalarEvolution & S, ValueToValueMap & M, bool C) inline
Definition at line 648 of file ScalarEvolutionExpressions.h.
Referenced by rewrite().
Member Function Documentation
rewrite()
const SCEV * llvm::SCEVParameterRewriter::rewrite (const SCEV * Scev, ScalarEvolution & SE, ValueToValueMap & Map, bool InterpretConsts = false) inline static
Definition at line 641 of file ScalarEvolutionExpressions.h.
References Rewriter, and SCEVParameterRewriter().
Referenced by replaceSymbolicStrideSCEV().
visitAddExpr()
const SCEV * llvm::SCEVParameterRewriter::visitAddExpr (const SCEVAddExpr * Expr) inline
Definition at line 670 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), Operands, and llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >::visit().
visitAddRecExpr()
const SCEV * llvm::SCEVParameterRewriter::visitAddRecExpr (const SCEVAddRecExpr * Expr) inline
Definition at line 688 of file ScalarEvolutionExpressions.h.
References llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), Operands, and llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >::visit().
visitConstant()
const SCEV * llvm::SCEVParameterRewriter::visitConstant (const SCEVConstant * Constant) inline
Definition at line 651 of file ScalarEvolutionExpressions.h.
visitCouldNotCompute()
const SCEV * llvm::SCEVParameterRewriter::visitCouldNotCompute (const SCEVCouldNotCompute * Expr) inline
Definition at line 721 of file ScalarEvolutionExpressions.h.
visitMulExpr()
const SCEV * llvm::SCEVParameterRewriter::visitMulExpr (const SCEVMulExpr * Expr) inline
Definition at line 677 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), Operands, and llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >::visit().
visitSignExtendExpr()
const SCEV * llvm::SCEVParameterRewriter::visitSignExtendExpr (const SCEVSignExtendExpr * Expr) inline
Definition at line 665 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), llvm::SCEVCastExpr::getType(), and llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >::visit().
visitSMaxExpr()
const SCEV * llvm::SCEVParameterRewriter::visitSMaxExpr (const SCEVSMaxExpr * Expr) inline
Definition at line 696 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), Operands, and llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >::visit().
visitTruncateExpr()
const SCEV * llvm::SCEVParameterRewriter::visitTruncateExpr (const SCEVTruncateExpr * Expr) inline
Definition at line 655 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), llvm::SCEVCastExpr::getType(), and llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >::visit().
visitUDivExpr()
const SCEV * llvm::SCEVParameterRewriter::visitUDivExpr (const SCEVUDivExpr * Expr) inline
Definition at line 684 of file ScalarEvolutionExpressions.h.
References llvm::SCEVUDivExpr::getLHS(), llvm::SCEVUDivExpr::getRHS(), and llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >::visit().
visitUMaxExpr()
const SCEV * llvm::SCEVParameterRewriter::visitUMaxExpr (const SCEVUMaxExpr * Expr) inline
Definition at line 703 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), Operands, and llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >::visit().
visitUnknown()
const SCEV * llvm::SCEVParameterRewriter::visitUnknown (const SCEVUnknown * Expr) inline
Definition at line 710 of file ScalarEvolutionExpressions.h.
References llvm::cast(), llvm::SCEVUnknown::getValue(), and llvm::isa().
visitZeroExtendExpr()
const SCEV * llvm::SCEVParameterRewriter::visitZeroExtendExpr (const SCEVZeroExtendExpr * Expr) inline
Definition at line 660 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), llvm::SCEVCastExpr::getType(), and llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >::visit().
The documentation for this struct was generated from the following file:
ScalarEvolutionExpressions.h