LLVM: llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true > Struct Template Reference
LLVM API Documentation
llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true > Struct Template Reference
Specialization of AnalysisResultModel which delegates invalidate handling to ResultT.
#include <PassManagerInternal.h>
Public Member Functions
AnalysisResultModel (ResultT Result)
AnalysisResultModel (const AnalysisResultModel &Arg)
AnalysisResultModel (AnalysisResultModel &&Arg)
AnalysisResultModel & operator= (AnalysisResultModel RHS)
bool invalidate (IRUnitT &IR, const PreservedAnalysesT &PA) override
The model delegates to the ResultT method.
Public Member Functions inherited from llvm::detail::AnalysisResultConcept< IRUnitT >
virtual ~AnalysisResultConcept ()
virtual bool invalidate (IRUnitT &IR, const PreservedAnalyses &PA)=0
Method to try and mark a result as invalid.
Public Attributes
ResultT Result
Friends
void swap (AnalysisResultModel &LHS, AnalysisResultModel &RHS)
Detailed Description
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT>
struct llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true >
Specialization of AnalysisResultModel which delegates invalidate handling to ResultT.
Definition at line 218 of file PassManagerInternal.h.
Constructor & Destructor Documentation
AnalysisResultModel() [1/3]
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true >::AnalysisResultModel (ResultT Result) inline explicit
Definition at line 220 of file PassManagerInternal.h.
References Result.
Referenced by AnalysisResultModel(), AnalysisResultModel(), operator=(), and swap.
AnalysisResultModel() [2/3]
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true >::AnalysisResultModel (const AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true > & Arg) inline
Definition at line 223 of file PassManagerInternal.h.
References AnalysisResultModel(), and Result.
AnalysisResultModel() [3/3]
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true >::AnalysisResultModel (AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true > && Arg) inline
Definition at line 224 of file PassManagerInternal.h.
References AnalysisResultModel(), and Result.
Member Function Documentation
invalidate()
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> bool llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true >::invalidate (IRUnitT & IR, const PreservedAnalysesT & PA) inline override
The model delegates to the ResultT method.
Definition at line 236 of file PassManagerInternal.h.
References IR, and Result.
operator=()
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> AnalysisResultModel & llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true >::operator= (AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true > RHS) inline
Definition at line 230 of file PassManagerInternal.h.
References AnalysisResultModel(), and swap.
Friends And Related Symbol Documentation
swap
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> void swap (AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true > & LHS, AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true > & RHS) friend
Definition at line 226 of file PassManagerInternal.h.
References AnalysisResultModel(), swap, and std::swap().
Referenced by operator=(), and swap.
Member Data Documentation
Result
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> ResultT llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, true >::Result
Definition at line 240 of file PassManagerInternal.h.
Referenced by AnalysisResultModel(), AnalysisResultModel(), AnalysisResultModel(), and invalidate().
The documentation for this struct was generated from the following file:
PassManagerInternal.h