LLVM: llvm::GraphTraits< const CallGraph * > Struct Reference
LLVM API Documentation
llvm::GraphTraits< const CallGraph * > Struct Reference
#include <CallGraph.h>
Public Types
typedef std::pair< const Function *, const CallGraphNode * > PairTy
typedef std::pointer_to_unary_function< PairTy, const CallGraphNode & > DerefFun
typedef mapped_iterator< CallGraph::const_iterator, DerefFun > nodes_iterator
typedef const CallGraph *::UnknownGraphTypeError NodeType
Public Types inherited from llvm::GraphTraits< const CallGraphNode * >
typedef const CallGraphNode NodeType
typedef CallGraphNode::CallRecord CGNPairTy
typedef std::pointer_to_unary_function< CGNPairTy, const CallGraphNode * > CGNDerefFun
typedef mapped_iterator< NodeType::const_iterator, CGNDerefFun > ChildIteratorType
Static Public Member Functions
static NodeType * getEntryNode (const CallGraph *CGN)
static nodes_iterator nodes_begin (const CallGraph *CG)
static nodes_iterator nodes_end (const CallGraph *CG)
static const CallGraphNode & CGdereference (PairTy P)
Static Public Member Functions inherited from llvm::GraphTraits< const CallGraphNode * >
static NodeType * getEntryNode (const CallGraphNode *CGN)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
static const CallGraphNode * CGNDeref (CGNPairTy P)
Detailed Description
Definition at line 461 of file CallGraph.h.
Member Typedef Documentation
DerefFun
typedef std::pointer_to_unary_function<PairTy, const CallGraphNode &> llvm::GraphTraits< const CallGraph * >::DerefFun
Definition at line 468 of file CallGraph.h.
nodes_iterator
typedef mapped_iterator<CallGraph::const_iterator, DerefFun> llvm::GraphTraits< const CallGraph * >::nodes_iterator
Definition at line 471 of file CallGraph.h.
NodeType
typedef const CallGraph *::UnknownGraphTypeError llvm::GraphTraits< const CallGraph * >::NodeType
Definition at line 60 of file GraphTraits.h.
PairTy
typedef std::pair<const Function *, const CallGraphNode *> llvm::GraphTraits< const CallGraph * >::PairTy
Definition at line 466 of file CallGraph.h.
Member Function Documentation
CGdereference()
const CallGraphNode & llvm::GraphTraits< const CallGraph * >::CGdereference (PairTy P) inline static
Definition at line 479 of file CallGraph.h.
References P.
Referenced by nodes_begin(), and nodes_end().
getEntryNode()
NodeType * llvm::GraphTraits< const CallGraph * >::getEntryNode (const CallGraph * CGN) inline static
Definition at line 463 of file CallGraph.h.
References llvm::CallGraph::getExternalCallingNode().
nodes_begin()
nodes_iterator llvm::GraphTraits< const CallGraph * >::nodes_begin (const CallGraph * CG) inline static
Definition at line 472 of file CallGraph.h.
References llvm::CallGraph::begin(), CGdereference(), and llvm::map_iterator().
nodes_end()
nodes_iterator llvm::GraphTraits< const CallGraph * >::nodes_end (const CallGraph * CG) inline static
Definition at line 475 of file CallGraph.h.
References CGdereference(), llvm::CallGraph::end(), and llvm::map_iterator().
The documentation for this struct was generated from the following file:
CallGraph.h