LLVM: llvm::TargetLowering::DAGCombinerInfo Struct Reference
LLVM API Documentation
llvm::TargetLowering::DAGCombinerInfo Struct Reference
#include <TargetLowering.h>
Public Member Functions
DAGCombinerInfo (SelectionDAG &dag, CombineLevel level, bool cl, void *dc)
bool isBeforeLegalize () const
bool isBeforeLegalizeOps () const
bool isAfterLegalizeVectorOps () const
CombineLevel getDAGCombineLevel ()
bool isCalledByLegalizer () const
void AddToWorklist (SDNode *N)
void RemoveFromWorklist (SDNode *N)
SDValue CombineTo (SDNode *N, const std::vector< SDValue > &To, bool AddTo=true)
SDValue CombineTo (SDNode *N, SDValue Res, bool AddTo=true)
SDValue CombineTo (SDNode *N, SDValue Res0, SDValue Res1, bool AddTo=true)
void CommitTargetLoweringOpt (const TargetLoweringOpt &TLO)
Public Attributes
void * DC
CombineLevel Level
bool CalledByLegalizer
SelectionDAG & DAG
Detailed Description
Definition at line 2154 of file TargetLowering.h.
Constructor & Destructor Documentation
DAGCombinerInfo()
llvm::TargetLowering::DAGCombinerInfo::DAGCombinerInfo (SelectionDAG & dag, CombineLevel level, bool cl, void * dc) inline
Definition at line 2161 of file TargetLowering.h.
References CalledByLegalizer, DAG, DC, and Level.
Member Function Documentation
AddToWorklist()
void TargetLowering::DAGCombinerInfo::AddToWorklist (SDNode * N)
Definition at line 440 of file DAGCombiner.cpp.
References DC, and N.
Referenced by combineX86ShuffleChain(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), PerformARMBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformInsertEltCombine(), PerformSELECTCombine(), PerformSTORECombine(), PerformTargetShuffleCombine(), and llvm::TargetLowering::SimplifySetCC().
CombineTo() [1/3]
SDValue TargetLowering::DAGCombinerInfo::CombineTo (SDNode * N, const std::vector< SDValue > & To, bool AddTo = true)
Definition at line 448 of file DAGCombiner.cpp.
References DC, and N.
Referenced by CombineBaseUpdate(), combineRedundantHalfShuffle(), CombineVLDDUP(), combineX86ShuffleChain(), PerformADCCombine(), PerformANDCombine(), performBRCONDCombine(), PerformCMOVCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformLOADCombine(), PerformMLOADCombine(), PerformMULCombine(), PerformMulCombine(), performNEONPostLDSTCombine(), PerformORCombine(), performPostLD1Combine(), PerformShuffleCombine256(), PerformTargetShuffleCombine(), and PerformVMOVRRDCombine().
CombineTo() [2/3]
SDValue TargetLowering::DAGCombinerInfo::CombineTo (SDNode * N, SDValue Res, bool AddTo = true)
Definition at line 453 of file DAGCombiner.cpp.
References DC, and N.
CombineTo() [3/3]
SDValue TargetLowering::DAGCombinerInfo::CombineTo (SDNode * N, SDValue Res0, SDValue Res1, bool AddTo = true)
Definition at line 459 of file DAGCombiner.cpp.
References DC, and N.
CommitTargetLoweringOpt()
void TargetLowering::DAGCombinerInfo::CommitTargetLoweringOpt (const TargetLoweringOpt & TLO)
Definition at line 464 of file DAGCombiner.cpp.
References DC.
Referenced by PerformBTCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), PerformSELECTCombine(), and simplifyI24().
getDAGCombineLevel()
CombineLevel llvm::TargetLowering::DAGCombinerInfo::getDAGCombineLevel () inline
Definition at line 2169 of file TargetLowering.h.
References Level.
Referenced by llvm::AMDGPUTargetLowering::CombineFMinMaxLegacy(), and llvm::SITargetLowering::PerformDAGCombine().
isAfterLegalizeVectorOps()
bool llvm::TargetLowering::DAGCombinerInfo::isAfterLegalizeVectorOps () const inline
Definition at line 2166 of file TargetLowering.h.
References llvm::AfterLegalizeDAG, and Level.
isBeforeLegalize()
bool llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize () const inline
Definition at line 2164 of file TargetLowering.h.
References llvm::BeforeLegalizeTypes, and Level.
Referenced by AddCombineTo64bitMLAL(), AddCombineToVPADDL(), CombineBaseUpdate(), performADDECombine(), PerformBTCombine(), PerformCMOVCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), PerformMULCombine(), PerformMulCombine(), performNEONPostLDSTCombine(), PerformSELECTCombine(), PerformShuffleCombine(), performSTORECombine(), performSUBECombine(), and llvm::TargetLowering::SimplifySetCC().
isBeforeLegalizeOps()
bool llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps () const inline
Definition at line 2165 of file TargetLowering.h.
References llvm::AfterLegalizeVectorOps, and Level.
Referenced by performADDCombine(), performAddSubLongCombine(), PerformAndCombine(), performANDCombine(), performBitcastCombine(), PerformBTCombine(), PerformCMOVCombine(), performCMovFPCombine(), performConcatVectorsCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), performDivRemCombine(), performExtendCombine(), PerformLOADCombine(), performMulCombine(), PerformOrCombine(), performORCombine(), performPostLD1Combine(), PerformSELECTCombine(), performSELECTCombine(), PerformSExtCombine(), PerformShuffleCombine(), PerformXorCombine(), performXorCombine(), llvm::TargetLowering::SimplifySetCC(), tryCombineFixedPointConvert(), tryCombineLongOpWithDup(), and XFormVExtractWithShuffleIntoLoad().
isCalledByLegalizer()
bool llvm::TargetLowering::DAGCombinerInfo::isCalledByLegalizer () const inline
Definition at line 2170 of file TargetLowering.h.
References CalledByLegalizer.
Referenced by CombineBaseUpdate(), llvm::AMDGPUTargetLowering::CombineFMinMaxLegacy(), PerformMULCombine(), PerformMulCombine(), performNEONPostLDSTCombine(), and llvm::TargetLowering::SimplifySetCC().
RemoveFromWorklist()
void TargetLowering::DAGCombinerInfo::RemoveFromWorklist (SDNode * N)
Definition at line 444 of file DAGCombiner.cpp.
References DC, and N.
Member Data Documentation
CalledByLegalizer
bool llvm::TargetLowering::DAGCombinerInfo::CalledByLegalizer
Definition at line 2157 of file TargetLowering.h.
Referenced by DAGCombinerInfo(), and isCalledByLegalizer().
DAG
SelectionDAG& llvm::TargetLowering::DAGCombinerInfo::DAG
Definition at line 2159 of file TargetLowering.h.
Referenced by AddCombineTo64bitMLAL(), AddCombineToVPADDL(), CombineBaseUpdate(), llvm::AMDGPUTargetLowering::CombineFMinMaxLegacy(), combineSelectAndUse(), CombineVLDDUP(), DAGCombinerInfo(), llvm::PPCTargetLowering::expandVSXLoadForLE(), llvm::PPCTargetLowering::expandVSXStoreForLE(), llvm::AMDGPUTargetLowering::getRecipEstimate(), llvm::AMDGPUTargetLowering::getRsqrtEstimate(), PerformADDCombineWithOperands(), PerformANDCombine(), PerformANDCombine(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), PerformBUILD_VECTORCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformDAGCombine(), llvm::MipsSETargetLowering::PerformDAGCombine(), llvm::MipsTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::SystemZTargetLowering::PerformDAGCombine(), llvm::X86TargetLowering::PerformDAGCombine(), PerformInsertEltCombine(), performIntrinsicCombine(), PerformMULCombine(), PerformORCombine(), performORCombine(), performPostLD1Combine(), PerformSTORECombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPLANECombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), PerformXORCombine(), simplifyI24(), llvm::TargetLowering::SimplifySetCC(), tryCombineToBSL(), tryCombineToEXTR(), and TryMULWIDECombine().
DC
void* llvm::TargetLowering::DAGCombinerInfo::DC
Definition at line 2155 of file TargetLowering.h.
Referenced by AddToWorklist(), CombineTo(), CombineTo(), CombineTo(), CommitTargetLoweringOpt(), DAGCombinerInfo(), and RemoveFromWorklist().
Level
CombineLevel llvm::TargetLowering::DAGCombinerInfo::Level
Definition at line 2156 of file TargetLowering.h.
Referenced by DAGCombinerInfo(), getDAGCombineLevel(), isAfterLegalizeVectorOps(), isBeforeLegalize(), and isBeforeLegalizeOps().
The documentation for this struct was generated from the following files:
TargetLowering.h
DAGCombiner.cpp