LLVM: llvm::MipsABIFlagsSection Struct Reference
LLVM API Documentation
llvm::MipsABIFlagsSection Struct Reference
#include <MipsABIFlagsSection.h>
Public Types
enum AFL_REG { AFL_REG_NONE = 0x00 , AFL_REG_32 = 0x01 , AFL_REG_64 = 0x02 , AFL_REG_128 = 0x03 }
enum AFL_ASE {
AFL_ASE_DSP = 0x00000001 , AFL_ASE_DSPR2 = 0x00000002 , AFL_ASE_EVA = 0x00000004 , AFL_ASE_MCU = 0x00000008 ,
AFL_ASE_MDMX = 0x00000010 , AFL_ASE_MIPS3D = 0x00000020 , AFL_ASE_MT = 0x00000040 , AFL_ASE_SMARTMIPS = 0x00000080 ,
AFL_ASE_VIRT = 0x00000100 , AFL_ASE_MSA = 0x00000200 , AFL_ASE_MIPS16 = 0x00000400 , AFL_ASE_MICROMIPS = 0x00000800 ,
AFL_ASE_XPA = 0x00001000
}
enum AFL_EXT {
AFL_EXT_XLR = 1 , AFL_EXT_OCTEON2 = 2 , AFL_EXT_OCTEONP = 3 , AFL_EXT_LOONGSON_3A = 4 ,
AFL_EXT_OCTEON = 5 , AFL_EXT_5900 = 6 , AFL_EXT_4650 = 7 , AFL_EXT_4010 = 8 ,
AFL_EXT_4100 = 9 , AFL_EXT_3900 = 10 , AFL_EXT_10000 = 11 , AFL_EXT_SB1 = 12 ,
AFL_EXT_4111 = 13 , AFL_EXT_4120 = 14 , AFL_EXT_5400 = 15 , AFL_EXT_5500 = 16 ,
AFL_EXT_LOONGSON_2E = 17 , AFL_EXT_LOONGSON_2F = 18
}
enum Val_GNU_MIPS_ABI {
Val_GNU_MIPS_ABI_FP_ANY = 0 , Val_GNU_MIPS_ABI_FP_DOUBLE = 1 , Val_GNU_MIPS_ABI_FP_XX = 5 , Val_GNU_MIPS_ABI_FP_64 = 6 ,
Val_GNU_MIPS_ABI_FP_64A = 7
}
enum AFL_FLAGS1 { AFL_FLAGS1_ODDSPREG = 1 }
enum class FpABIKind { ANY , XX , S32 , S64 }
Public Member Functions
MipsABIFlagsSection ()
uint16_t getVersionValue ()
uint8_t getISALevelValue ()
uint8_t getISARevisionValue ()
uint8_t getGPRSizeValue ()
uint8_t getCPR1SizeValue ()
uint8_t getCPR2SizeValue ()
uint8_t getFpABIValue ()
uint32_t getISAExtensionSetValue ()
uint32_t getASESetValue ()
uint32_t getFlags1Value ()
uint32_t getFlags2Value ()
FpABIKind getFpABI ()
void setFpABI (FpABIKind Value, bool IsABI32Bit)
StringRef getFpABIString (FpABIKind Value)
template<class PredicateLibrary>
void setISALevelAndRevisionFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary>
void setGPRSizeFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary>
void setCPR1SizeFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary>
void setASESetFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary>
void setFpAbiFromPredicates (const PredicateLibrary &P)
template<class PredicateLibrary>
void setAllFromPredicates (const PredicateLibrary &P)
Public Attributes
uint16_t Version
uint8_t ISALevel
uint8_t ISARevision
AFL_REG GPRSize
AFL_REG CPR1Size
AFL_REG CPR2Size
uint32_t ISAExtensionSet
uint32_t ASESet
bool OddSPReg
bool Is32BitABI
Protected Attributes
FpABIKind FpABI
Detailed Description
Definition at line 19 of file MipsABIFlagsSection.h.
Member Enumeration Documentation
AFL_ASE
enum llvm::MipsABIFlagsSection::AFL_ASE
Enumerator
AFL_ASE_DSP
AFL_ASE_DSPR2
AFL_ASE_EVA
AFL_ASE_MCU
AFL_ASE_MDMX
AFL_ASE_MIPS3D
AFL_ASE_MT
AFL_ASE_SMARTMIPS
AFL_ASE_VIRT
AFL_ASE_MSA
AFL_ASE_MIPS16
AFL_ASE_MICROMIPS
AFL_ASE_XPA
Definition at line 29 of file MipsABIFlagsSection.h.
AFL_EXT
enum llvm::MipsABIFlagsSection::AFL_EXT
Enumerator
AFL_EXT_XLR
AFL_EXT_OCTEON2
AFL_EXT_OCTEONP
AFL_EXT_LOONGSON_3A
AFL_EXT_OCTEON
AFL_EXT_5900
AFL_EXT_4650
AFL_EXT_4010
AFL_EXT_4100
AFL_EXT_3900
AFL_EXT_10000
AFL_EXT_SB1
AFL_EXT_4111
AFL_EXT_4120
AFL_EXT_5400
AFL_EXT_5500
AFL_EXT_LOONGSON_2E
AFL_EXT_LOONGSON_2F
Definition at line 46 of file MipsABIFlagsSection.h.
AFL_FLAGS1
enum llvm::MipsABIFlagsSection::AFL_FLAGS1
Enumerator
AFL_FLAGS1_ODDSPREG
Definition at line 76 of file MipsABIFlagsSection.h.
AFL_REG
enum llvm::MipsABIFlagsSection::AFL_REG
Enumerator
AFL_REG_NONE
AFL_REG_32
AFL_REG_64
AFL_REG_128
Definition at line 21 of file MipsABIFlagsSection.h.
FpABIKind
enum class llvm::MipsABIFlagsSection::FpABIKind strong
Enumerator
ANY
XX
S32
S64
Definition at line 81 of file MipsABIFlagsSection.h.
Val_GNU_MIPS_ABI
enum llvm::MipsABIFlagsSection::Val_GNU_MIPS_ABI
Enumerator
Val_GNU_MIPS_ABI_FP_ANY
Val_GNU_MIPS_ABI_FP_DOUBLE
Val_GNU_MIPS_ABI_FP_XX
Val_GNU_MIPS_ABI_FP_64
Val_GNU_MIPS_ABI_FP_64A
Definition at line 68 of file MipsABIFlagsSection.h.
Constructor & Destructor Documentation
MipsABIFlagsSection()
llvm::MipsABIFlagsSection::MipsABIFlagsSection () inline
Definition at line 109 of file MipsABIFlagsSection.h.
References AFL_REG_NONE, ANY, ASESet, CPR1Size, CPR2Size, FpABI, GPRSize, Is32BitABI, ISAExtensionSet, ISALevel, ISARevision, OddSPReg, and Version.
Member Function Documentation
getASESetValue()
uint32_t llvm::MipsABIFlagsSection::getASESetValue () inline
Definition at line 122 of file MipsABIFlagsSection.h.
References ASESet.
Referenced by llvm::operator<<().
getCPR1SizeValue()
uint8_t MipsABIFlagsSection::getCPR1SizeValue ()
Definition at line 44 of file MipsABIFlagsSection.cpp.
References AFL_REG_32, CPR1Size, FpABI, and XX.
Referenced by llvm::operator<<().
getCPR2SizeValue()
uint8_t llvm::MipsABIFlagsSection::getCPR2SizeValue () inline
Definition at line 119 of file MipsABIFlagsSection.h.
References CPR2Size.
Referenced by llvm::operator<<().
getFlags1Value()
uint32_t llvm::MipsABIFlagsSection::getFlags1Value () inline
Definition at line 124 of file MipsABIFlagsSection.h.
References AFL_FLAGS1_ODDSPREG, and OddSPReg.
Referenced by llvm::operator<<().
getFlags2Value()
uint32_t llvm::MipsABIFlagsSection::getFlags2Value () inline
Definition at line 133 of file MipsABIFlagsSection.h.
Referenced by llvm::operator<<().
getFpABI()
FpABIKind llvm::MipsABIFlagsSection::getFpABI () inline
Definition at line 135 of file MipsABIFlagsSection.h.
References FpABI.
getFpABIString()
StringRef MipsABIFlagsSection::getFpABIString (FpABIKind Value)
Definition at line 31 of file MipsABIFlagsSection.cpp.
References llvm_unreachable, S32, S64, and XX.
getFpABIValue()
uint8_t MipsABIFlagsSection::getFpABIValue ()
Definition at line 14 of file MipsABIFlagsSection.cpp.
References ANY, FpABI, Is32BitABI, llvm_unreachable, OddSPReg, S32, S64, Val_GNU_MIPS_ABI_FP_64, Val_GNU_MIPS_ABI_FP_64A, Val_GNU_MIPS_ABI_FP_ANY, Val_GNU_MIPS_ABI_FP_DOUBLE, Val_GNU_MIPS_ABI_FP_XX, and XX.
Referenced by llvm::operator<<().
getGPRSizeValue()
uint8_t llvm::MipsABIFlagsSection::getGPRSizeValue () inline
Definition at line 117 of file MipsABIFlagsSection.h.
References GPRSize.
Referenced by llvm::operator<<().
getISAExtensionSetValue()
uint32_t llvm::MipsABIFlagsSection::getISAExtensionSetValue () inline
Definition at line 121 of file MipsABIFlagsSection.h.
References ISAExtensionSet.
Referenced by llvm::operator<<().
getISALevelValue()
uint8_t llvm::MipsABIFlagsSection::getISALevelValue () inline
Definition at line 115 of file MipsABIFlagsSection.h.
References ISALevel.
Referenced by llvm::operator<<().
getISARevisionValue()
uint8_t llvm::MipsABIFlagsSection::getISARevisionValue () inline
Definition at line 116 of file MipsABIFlagsSection.h.
References ISARevision.
Referenced by llvm::operator<<().
getVersionValue()
uint16_t llvm::MipsABIFlagsSection::getVersionValue () inline
Definition at line 114 of file MipsABIFlagsSection.h.
References Version.
Referenced by llvm::operator<<().
setAllFromPredicates()
template<class PredicateLibrary> void llvm::MipsABIFlagsSection::setAllFromPredicates (const PredicateLibrary & P) inline
Definition at line 225 of file MipsABIFlagsSection.h.
References OddSPReg, P, setASESetFromPredicates(), setCPR1SizeFromPredicates(), setFpAbiFromPredicates(), setGPRSizeFromPredicates(), and setISALevelAndRevisionFromPredicates().
setASESetFromPredicates()
template<class PredicateLibrary> void llvm::MipsABIFlagsSection::setASESetFromPredicates (const PredicateLibrary & P) inline
Definition at line 193 of file MipsABIFlagsSection.h.
References AFL_ASE_DSP, AFL_ASE_DSPR2, AFL_ASE_MICROMIPS, AFL_ASE_MIPS16, AFL_ASE_MSA, ASESet, and P.
Referenced by setAllFromPredicates().
setCPR1SizeFromPredicates()
template<class PredicateLibrary> void llvm::MipsABIFlagsSection::setCPR1SizeFromPredicates (const PredicateLibrary & P) inline
Definition at line 183 of file MipsABIFlagsSection.h.
References AFL_REG_128, AFL_REG_32, AFL_REG_64, AFL_REG_NONE, CPR1Size, and P.
Referenced by setAllFromPredicates().
setFpABI()
void llvm::MipsABIFlagsSection::setFpABI (FpABIKind Value, bool IsABI32Bit) inline
Definition at line 136 of file MipsABIFlagsSection.h.
References FpABI, and Is32BitABI.
setFpAbiFromPredicates()
template<class PredicateLibrary> void llvm::MipsABIFlagsSection::setFpAbiFromPredicates (const PredicateLibrary & P) inline
Definition at line 208 of file MipsABIFlagsSection.h.
References ANY, FpABI, Is32BitABI, P, S32, S64, and XX.
Referenced by setAllFromPredicates().
setGPRSizeFromPredicates()
template<class PredicateLibrary> void llvm::MipsABIFlagsSection::setGPRSizeFromPredicates (const PredicateLibrary & P) inline
Definition at line 178 of file MipsABIFlagsSection.h.
References AFL_REG_32, AFL_REG_64, GPRSize, and P.
Referenced by setAllFromPredicates().
setISALevelAndRevisionFromPredicates()
template<class PredicateLibrary> void llvm::MipsABIFlagsSection::setISALevelAndRevisionFromPredicates (const PredicateLibrary & P) inline
Definition at line 143 of file MipsABIFlagsSection.h.
References ISALevel, ISARevision, llvm_unreachable, and P.
Referenced by setAllFromPredicates().
Member Data Documentation
ASESet
uint32_t llvm::MipsABIFlagsSection::ASESet
Definition at line 98 of file MipsABIFlagsSection.h.
Referenced by getASESetValue(), MipsABIFlagsSection(), and setASESetFromPredicates().
CPR1Size
AFL_REG llvm::MipsABIFlagsSection::CPR1Size
Definition at line 92 of file MipsABIFlagsSection.h.
Referenced by getCPR1SizeValue(), MipsABIFlagsSection(), and setCPR1SizeFromPredicates().
CPR2Size
AFL_REG llvm::MipsABIFlagsSection::CPR2Size
Definition at line 94 of file MipsABIFlagsSection.h.
Referenced by getCPR2SizeValue(), and MipsABIFlagsSection().
FpABI
FpABIKind llvm::MipsABIFlagsSection::FpABI protected
Definition at line 106 of file MipsABIFlagsSection.h.
Referenced by getCPR1SizeValue(), getFpABI(), getFpABIValue(), MipsABIFlagsSection(), setFpABI(), and setFpAbiFromPredicates().
GPRSize
AFL_REG llvm::MipsABIFlagsSection::GPRSize
Definition at line 90 of file MipsABIFlagsSection.h.
Referenced by getGPRSizeValue(), MipsABIFlagsSection(), and setGPRSizeFromPredicates().
Is32BitABI
bool llvm::MipsABIFlagsSection::Is32BitABI
Definition at line 102 of file MipsABIFlagsSection.h.
Referenced by getFpABIValue(), MipsABIFlagsSection(), setFpABI(), and setFpAbiFromPredicates().
ISAExtensionSet
uint32_t llvm::MipsABIFlagsSection::ISAExtensionSet
Definition at line 96 of file MipsABIFlagsSection.h.
Referenced by getISAExtensionSetValue(), and MipsABIFlagsSection().
ISALevel
uint8_t llvm::MipsABIFlagsSection::ISALevel
Definition at line 86 of file MipsABIFlagsSection.h.
Referenced by getISALevelValue(), MipsABIFlagsSection(), and setISALevelAndRevisionFromPredicates().
ISARevision
uint8_t llvm::MipsABIFlagsSection::ISARevision
Definition at line 88 of file MipsABIFlagsSection.h.
Referenced by getISARevisionValue(), MipsABIFlagsSection(), and setISALevelAndRevisionFromPredicates().
OddSPReg
bool llvm::MipsABIFlagsSection::OddSPReg
Definition at line 100 of file MipsABIFlagsSection.h.
Referenced by getFlags1Value(), getFpABIValue(), MipsABIFlagsSection(), and setAllFromPredicates().
Version
uint16_t llvm::MipsABIFlagsSection::Version
Definition at line 84 of file MipsABIFlagsSection.h.
Referenced by getVersionValue(), and MipsABIFlagsSection().
The documentation for this struct was generated from the following files:
MipsABIFlagsSection.h
MipsABIFlagsSection.cpp