LLVM: llvm::detail::AnalysisPassModel< IRUnitT, PassT, false > Struct Template Reference
LLVM API Documentation
llvm::detail::AnalysisPassModel< IRUnitT, PassT, false > Struct Template Reference
Specialization of AnalysisPassModel which does not pass an AnalysisManager to PassT's run method.
#include <PassManagerInternal.h>
Public Types
typedef AnalysisResultModel< IRUnitT, PassT, typename PassT::Result > ResultModelT
Public Member Functions
AnalysisPassModel (PassT Pass)
AnalysisPassModel (const AnalysisPassModel &Arg)
AnalysisPassModel (AnalysisPassModel &&Arg)
AnalysisPassModel & operator= (AnalysisPassModel RHS)
std::unique_ptr< AnalysisResultConcept< IRUnitT > > run (IRUnitT &IR, AnalysisManager< IRUnitT > *) override
The model delegates to the PassT::run method.
StringRef name () override
The model delegates to a static PassT::name method.
Public Member Functions inherited from llvm::detail::AnalysisPassConcept< IRUnitT >
virtual ~AnalysisPassConcept ()
Public Attributes
PassT Pass
Friends
void swap (AnalysisPassModel &LHS, AnalysisPassModel &RHS)
Detailed Description
template<typename IRUnitT, typename PassT>
struct llvm::detail::AnalysisPassModel< IRUnitT, PassT, false >
Specialization of AnalysisPassModel which does not pass an AnalysisManager to PassT's run method.
Definition at line 311 of file PassManagerInternal.h.
Member Typedef Documentation
ResultModelT
template<typename IRUnitT, typename PassT> typedef AnalysisResultModel<IRUnitT, PassT, typename PassT::Result> llvm::detail::AnalysisPassModel< IRUnitT, PassT, false >::ResultModelT
Definition at line 328 of file PassManagerInternal.h.
Constructor & Destructor Documentation
AnalysisPassModel() [1/3]
template<typename IRUnitT, typename PassT> llvm::detail::AnalysisPassModel< IRUnitT, PassT, false >::AnalysisPassModel (PassT Pass) inline explicit
Definition at line 312 of file PassManagerInternal.h.
References Pass.
Referenced by AnalysisPassModel(), AnalysisPassModel(), operator=(), and swap.
AnalysisPassModel() [2/3]
template<typename IRUnitT, typename PassT> llvm::detail::AnalysisPassModel< IRUnitT, PassT, false >::AnalysisPassModel (const AnalysisPassModel< IRUnitT, PassT, false > & Arg) inline
Definition at line 315 of file PassManagerInternal.h.
References AnalysisPassModel(), and Pass.
AnalysisPassModel() [3/3]
template<typename IRUnitT, typename PassT> llvm::detail::AnalysisPassModel< IRUnitT, PassT, false >::AnalysisPassModel (AnalysisPassModel< IRUnitT, PassT, false > && Arg) inline
Definition at line 316 of file PassManagerInternal.h.
References AnalysisPassModel(), and Pass.
Member Function Documentation
name()
template<typename IRUnitT, typename PassT> StringRef llvm::detail::AnalysisPassModel< IRUnitT, PassT, false >::name () inline override virtual
The model delegates to a static PassT::name method.
The returned string ref must point to constant immutable data!
Implements llvm::detail::AnalysisPassConcept< IRUnitT >.
Definition at line 341 of file PassManagerInternal.h.
operator=()
template<typename IRUnitT, typename PassT> AnalysisPassModel & llvm::detail::AnalysisPassModel< IRUnitT, PassT, false >::operator= (AnalysisPassModel< IRUnitT, PassT, false > RHS) inline
Definition at line 321 of file PassManagerInternal.h.
References AnalysisPassModel(), and swap.
run()
template<typename IRUnitT, typename PassT> std::unique_ptr< AnalysisResultConcept< IRUnitT > > llvm::detail::AnalysisPassModel< IRUnitT, PassT, false >::run (IRUnitT & IR, AnalysisManager< IRUnitT > *) inline override virtual
The model delegates to the PassT::run method.
The return is wrapped in an AnalysisResultModel.
Implements llvm::detail::AnalysisPassConcept< IRUnitT >.
Definition at line 334 of file PassManagerInternal.h.
References IR, llvm::make_unique(), and Pass.
Friends And Related Symbol Documentation
swap
template<typename IRUnitT, typename PassT> void swap (AnalysisPassModel< IRUnitT, PassT, false > & LHS, AnalysisPassModel< IRUnitT, PassT, false > & RHS) friend
Definition at line 317 of file PassManagerInternal.h.
References AnalysisPassModel(), swap, and std::swap().
Referenced by operator=(), and swap.
Member Data Documentation
Pass
template<typename IRUnitT, typename PassT> PassT llvm::detail::AnalysisPassModel< IRUnitT, PassT, false >::Pass
Definition at line 343 of file PassManagerInternal.h.
Referenced by AnalysisPassModel(), AnalysisPassModel(), AnalysisPassModel(), and run().
The documentation for this struct was generated from the following file:
PassManagerInternal.h