LLVM: llvm::ExecutionEngineState::AddressMapConfig Struct Reference
LLVM API Documentation
llvm::ExecutionEngineState::AddressMapConfig Struct Reference
#include <ExecutionEngine.h>
Public Types
typedef ExecutionEngineState * ExtraData
Public Types inherited from llvm::ValueMapConfig< const GlobalValue * >
enum
typedef sys::Mutex mutex_type
Static Public Member Functions
static sys::Mutex * getMutex (ExecutionEngineState *EES)
static void onDelete (ExecutionEngineState *EES, const GlobalValue *Old)
static void onRAUW (ExecutionEngineState *, const GlobalValue *, const GlobalValue *)
Static Public Member Functions inherited from llvm::ValueMapConfig< const GlobalValue * >
static void onRAUW (const ExtraDataT &, const GlobalValue *, const GlobalValue *)
static void onDelete (const ExtraDataT &, const GlobalValue *)
static mutex_type * getMutex (const ExtraDataT &)
Detailed Description
Definition at line 60 of file llvm/ExecutionEngine/ExecutionEngine.h.
Member Typedef Documentation
ExtraData
typedef ExecutionEngineState* llvm::ExecutionEngineState::AddressMapConfig::ExtraData
Definition at line 61 of file llvm/ExecutionEngine/ExecutionEngine.h.
Member Function Documentation
getMutex()
sys::Mutex * ExecutionEngineState::AddressMapConfig::getMutex (ExecutionEngineState * EES) static
Definition at line 1279 of file ExecutionEngine.cpp.
References llvm::ExecutionEngineState::ExecutionEngineState(), and llvm::ExecutionEngine::lock.
onDelete()
void ExecutionEngineState::AddressMapConfig::onDelete (ExecutionEngineState * EES, const GlobalValue * Old) static
Definition at line 1283 of file ExecutionEngine.cpp.
References llvm::ExecutionEngineState::ExecutionEngineState(), and llvm::ValueMap< KeyT, ValueT, Config >::lookup().
onRAUW()
void ExecutionEngineState::AddressMapConfig::onRAUW (ExecutionEngineState * , const GlobalValue * , const GlobalValue *) static
Definition at line 1289 of file ExecutionEngine.cpp.
References llvm::ExecutionEngineState::ExecutionEngineState(), and llvm_unreachable.
The documentation for this struct was generated from the following files:
llvm/ExecutionEngine/ExecutionEngine.h
ExecutionEngine.cpp