LLVM: llvm::GraphTraits< RegionInfoPass * > Struct Reference
LLVM API Documentation
llvm::GraphTraits< RegionInfoPass * > Struct Reference
#include <RegionIterator.h>
Public Types
typedef df_iterator< NodeType *, SmallPtrSet< NodeType *, 8 >, false, GraphTraits< FlatIt< NodeType * > > > nodes_iterator
typedef RegionInfoPass *::UnknownGraphTypeError NodeType
Public Types inherited from llvm::GraphTraits< RegionInfo * >
typedef df_iterator< NodeType *, SmallPtrSet< NodeType *, 8 >, false, GraphTraits< FlatIt< NodeType * > > > nodes_iterator
typedef RegionInfo *::UnknownGraphTypeError NodeType
Public Types inherited from llvm::GraphTraits< FlatIt< RegionNode * > >
typedef FlatIt< RegionNode * >::UnknownGraphTypeError NodeType
Static Public Member Functions
static NodeType * getEntryNode (RegionInfoPass *RI)
static nodes_iterator nodes_begin (RegionInfoPass *RI)
static nodes_iterator nodes_end (RegionInfoPass *RI)
Static Public Member Functions inherited from llvm::GraphTraits< RegionInfo * >
static NodeType * getEntryNode (RegionInfo *RI)
static nodes_iterator nodes_begin (RegionInfo *RI)
static nodes_iterator nodes_end (RegionInfo *RI)
Detailed Description
Definition at line 347 of file RegionIterator.h.
Member Typedef Documentation
nodes_iterator
typedef df_iterator<NodeType*, SmallPtrSet<NodeType*, 8>, false, GraphTraits<FlatIt<NodeType*> > > llvm::GraphTraits< RegionInfoPass * >::nodes_iterator
Definition at line 350 of file RegionIterator.h.
NodeType
typedef RegionInfoPass *::UnknownGraphTypeError llvm::GraphTraits< RegionInfoPass * >::NodeType
Definition at line 60 of file GraphTraits.h.
Member Function Documentation
getEntryNode()
NodeType * llvm::GraphTraits< RegionInfoPass * >::getEntryNode (RegionInfoPass * RI) inline static
Definition at line 352 of file RegionIterator.h.
References llvm::RegionInfoPass::getRegionInfo().
nodes_begin()
nodes_iterator llvm::GraphTraits< RegionInfoPass * >::nodes_begin (RegionInfoPass * RI) inline static
Definition at line 355 of file RegionIterator.h.
References llvm::RegionInfoPass::getRegionInfo().
nodes_end()
nodes_iterator llvm::GraphTraits< RegionInfoPass * >::nodes_end (RegionInfoPass * RI) inline static
Definition at line 358 of file RegionIterator.h.
References llvm::RegionInfoPass::getRegionInfo().
The documentation for this struct was generated from the following file:
RegionIterator.h