LLVM: llvm::AArch64NamedImmMapper Struct Reference
LLVM API Documentation
llvm::AArch64NamedImmMapper Struct Reference
#include <AArch64BaseInfo.h>
Classes
struct Mapping
Public Member Functions
template<int N>
AArch64NamedImmMapper (const Mapping(&Pairs)[N], uint32_t TooBigImm)
StringRef toString (uint32_t Value, bool &Valid) const
uint32_t fromString (StringRef Name, bool &Valid) const
bool validImm (uint32_t Value) const
Protected Attributes
const Mapping * Pairs
size_t NumPairs
uint32_t TooBigImm
Detailed Description
Instances of this class can perform bidirectional mapping from random identifier strings to operand encodings. For example "MSR" takes a named system-register which must be encoded somehow and decoded for printing. This central location means that the information for those transformations is not duplicated and remains in sync.
FIXME: currently the algorithm is a completely unoptimised linear search. Obviously this could be improved, but we would probably want to work out just how often these instructions are emitted before working on it. It might even be optimal to just reorder the tables for the common instructions rather than changing the algorithm.
Definition at line 279 of file AArch64BaseInfo.h.
Constructor & Destructor Documentation
AArch64NamedImmMapper()
template<int N> llvm::AArch64NamedImmMapper::AArch64NamedImmMapper (const Mapping(&) Pairs[N], uint32_t TooBigImm) inline
Definition at line 286 of file AArch64BaseInfo.h.
References N, NumPairs, Pairs, and TooBigImm.
Referenced by llvm::AArch64AT::ATMapper::ATMapper(), llvm::AArch64DB::DBarrierMapper::DBarrierMapper(), llvm::AArch64DC::DCMapper::DCMapper(), llvm::AArch64IC::ICMapper::ICMapper(), llvm::AArch64ISB::ISBMapper::ISBMapper(), llvm::AArch64PRFM::PRFMMapper::PRFMMapper(), llvm::AArch64PState::PStateMapper::PStateMapper(), and llvm::AArch64TLBI::TLBIMapper::TLBIMapper().
Member Function Documentation
fromString()
uint32_t AArch64NamedImmMapper::fromString (StringRef Name, bool & Valid) const
Definition at line 33 of file AArch64BaseInfo.cpp.
References Name, NumPairs, and Pairs.
toString()
StringRef AArch64NamedImmMapper::toString (uint32_t Value, bool & Valid) const
Definition at line 21 of file AArch64BaseInfo.cpp.
References NumPairs, and Pairs.
Referenced by DecodeSystemPStateInstruction(), llvm::AArch64InstPrinter::printBarrierOption(), llvm::AArch64InstPrinter::printPrefetchOp(), and llvm::AArch64InstPrinter::printSystemPStateField().
validImm()
bool AArch64NamedImmMapper::validImm (uint32_t Value) const
Many of the instructions allow an alternative assembly form consisting of a simple immediate. Currently the only valid forms are ranges [0, N) where N being 0 indicates no immediate syntax-form is allowed.
Definition at line 46 of file AArch64BaseInfo.cpp.
References TooBigImm.
Member Data Documentation
NumPairs
size_t llvm::AArch64NamedImmMapper::NumPairs protected
Definition at line 298 of file AArch64BaseInfo.h.
Referenced by AArch64NamedImmMapper(), fromString(), and toString().
Pairs
const Mapping* llvm::AArch64NamedImmMapper::Pairs protected
Definition at line 297 of file AArch64BaseInfo.h.
Referenced by AArch64NamedImmMapper(), fromString(), and toString().
TooBigImm
uint32_t llvm::AArch64NamedImmMapper::TooBigImm protected
Definition at line 299 of file AArch64BaseInfo.h.
Referenced by AArch64NamedImmMapper(), and validImm().
The documentation for this struct was generated from the following files:
AArch64BaseInfo.h
AArch64BaseInfo.cpp