LLVM: llvm::MachinePostDominatorTree Struct Reference
LLVM API Documentation
llvm::MachinePostDominatorTree Struct Reference
#include <MachinePostDominators.h>
Public Member Functions
MachinePostDominatorTree ()
~MachinePostDominatorTree ()
FunctionPass * createMachinePostDominatorTreePass ()
const std::vector< MachineBasicBlock * > & getRoots () const
MachineDomTreeNode * getRootNode () const
MachineDomTreeNode * operator[] (MachineBasicBlock *BB) const
MachineDomTreeNode * getNode (MachineBasicBlock *BB) const
bool dominates (const MachineDomTreeNode *A, const MachineDomTreeNode *B) const
bool dominates (const MachineBasicBlock *A, const MachineBasicBlock *B) const
bool properlyDominates (const MachineDomTreeNode *A, const MachineDomTreeNode *B) const
bool properlyDominates (const MachineBasicBlock *A, const MachineBasicBlock *B) const
MachineBasicBlock * findNearestCommonDominator (MachineBasicBlock *A, MachineBasicBlock *B)
bool runOnMachineFunction (MachineFunction &MF) override
void getAnalysisUsage (AnalysisUsage &AU) const override
void print (llvm::raw_ostream &OS, const Module *M=nullptr) const override
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
PostDominatorTree Class - Concrete subclass of DominatorTree that is used to compute the post-dominator tree.
Definition at line 27 of file MachinePostDominators.h.
Constructor & Destructor Documentation
MachinePostDominatorTree()
llvm::MachinePostDominatorTree::MachinePostDominatorTree ()
Referenced by createMachinePostDominatorTreePass().
~MachinePostDominatorTree()
MachinePostDominatorTree::~MachinePostDominatorTree ()
Definition at line 42 of file MachinePostDominators.cpp.
Member Function Documentation
createMachinePostDominatorTreePass()
FunctionPass * MachinePostDominatorTree::createMachinePostDominatorTreePass ()
Definition at line 32 of file MachinePostDominators.cpp.
References MachinePostDominatorTree().
dominates() [1/2]
bool llvm::MachinePostDominatorTree::dominates (const MachineBasicBlock * A, const MachineBasicBlock * B) const inline
Definition at line 61 of file MachinePostDominators.h.
dominates() [2/2]
bool llvm::MachinePostDominatorTree::dominates (const MachineDomTreeNode * A, const MachineDomTreeNode * B) const inline
Definition at line 56 of file MachinePostDominators.h.
findNearestCommonDominator()
MachineBasicBlock * llvm::MachinePostDominatorTree::findNearestCommonDominator (MachineBasicBlock * A, MachineBasicBlock * B) inline
Definition at line 75 of file MachinePostDominators.h.
getAnalysisUsage()
void MachinePostDominatorTree::getAnalysisUsage (AnalysisUsage & AU) const override virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 47 of file MachinePostDominators.cpp.
References llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
getNode()
MachineDomTreeNode * llvm::MachinePostDominatorTree::getNode (MachineBasicBlock * BB) const inline
Definition at line 52 of file MachinePostDominators.h.
getRootNode()
MachineDomTreeNode * llvm::MachinePostDominatorTree::getRootNode () const inline
Definition at line 44 of file MachinePostDominators.h.
getRoots()
const std::vector< MachineBasicBlock * > & llvm::MachinePostDominatorTree::getRoots () const inline
Definition at line 40 of file MachinePostDominators.h.
operator[]()
MachineDomTreeNode * llvm::MachinePostDominatorTree::operator[] (MachineBasicBlock * BB) const inline
Definition at line 48 of file MachinePostDominators.h.
print()
void MachinePostDominatorTree::print (llvm::raw_ostream & O, const Module * M = nullptr) const override virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 53 of file MachinePostDominators.cpp.
properlyDominates() [1/2]
bool llvm::MachinePostDominatorTree::properlyDominates (const MachineBasicBlock * A, const MachineBasicBlock * B) const inline
Definition at line 70 of file MachinePostDominators.h.
properlyDominates() [2/2]
bool llvm::MachinePostDominatorTree::properlyDominates (const MachineDomTreeNode * A, const MachineDomTreeNode * B) const inline
Definition at line 65 of file MachinePostDominators.h.
runOnMachineFunction()
bool MachinePostDominatorTree::runOnMachineFunction (MachineFunction & MF) override virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 37 of file MachinePostDominators.cpp.
References F.
Member Data Documentation
ID
char MachinePostDominatorTree::ID = 0 static
Definition at line 32 of file MachinePostDominators.h.
The documentation for this struct was generated from the following files:
MachinePostDominators.h
MachinePostDominators.cpp