LLVM: llvm::ELFYAML::Section Struct Reference
LLVM API Documentation
llvm::ELFYAML::Section Struct Reference
#include <ELFYAML.h>
Public Types
enum class SectionKind { RawContent , Relocation }
Public Member Functions
Section (SectionKind Kind)
virtual ~Section ()
Public Attributes
SectionKind Kind
StringRef Name
ELF_SHT Type
ELF_SHF Flags
llvm::yaml::Hex64 Address
StringRef Link
llvm::yaml::Hex64 AddressAlign
Detailed Description
Definition at line 74 of file ELFYAML.h.
Member Enumeration Documentation
SectionKind
enum class llvm::ELFYAML::Section::SectionKind strong
Enumerator
RawContent
Relocation
Definition at line 75 of file ELFYAML.h.
Constructor & Destructor Documentation
Section()
llvm::ELFYAML::Section::Section (SectionKind Kind) inline
Definition at line 83 of file ELFYAML.h.
References Kind.
Referenced by llvm::ELFYAML::RawContentSection::classof(), llvm::ELFYAML::RelocationSection::classof(), llvm::ELFYAML::RawContentSection::RawContentSection(), and llvm::ELFYAML::RelocationSection::RelocationSection().
~Section()
llvm::ELFYAML::Section::~Section () virtual
Definition at line 19 of file ELFYAML.cpp.
Member Data Documentation
Address
llvm::yaml::Hex64 llvm::ELFYAML::Section::Address
Definition at line 80 of file ELFYAML.h.
AddressAlign
llvm::yaml::Hex64 llvm::ELFYAML::Section::AddressAlign
Definition at line 82 of file ELFYAML.h.
Flags
ELF_SHF llvm::ELFYAML::Section::Flags
Definition at line 79 of file ELFYAML.h.
Kind
SectionKind llvm::ELFYAML::Section::Kind
Definition at line 76 of file ELFYAML.h.
Referenced by llvm::ELFYAML::RawContentSection::classof(), llvm::ELFYAML::RelocationSection::classof(), and Section().
Link
StringRef llvm::ELFYAML::Section::Link
Definition at line 81 of file ELFYAML.h.
Name
StringRef llvm::ELFYAML::Section::Name
Definition at line 77 of file ELFYAML.h.
Type
ELF_SHT llvm::ELFYAML::Section::Type
Definition at line 78 of file ELFYAML.h.
The documentation for this struct was generated from the following files:
ELFYAML.h
ELFYAML.cpp