LLVM: llvm::MDLocationInfo Struct Reference
LLVM API Documentation
llvm::MDLocationInfo Struct Reference
DenseMapInfo for MDLocation.
#include <LLVMContextImpl.h>
Classes
struct KeyTy
Static Public Member Functions
static MDLocation * getEmptyKey ()
static MDLocation * getTombstoneKey ()
static unsigned getHashValue (const KeyTy &Key)
static unsigned getHashValue (const MDLocation *U)
static bool isEqual (const KeyTy &LHS, const MDLocation *RHS)
static bool isEqual (const MDLocation *LHS, const MDLocation *RHS)
Detailed Description
DenseMapInfo for MDLocation.
Definition at line 219 of file LLVMContextImpl.h.
Member Function Documentation
getEmptyKey()
MDLocation * llvm::MDLocationInfo::getEmptyKey () inline static
Definition at line 240 of file LLVMContextImpl.h.
Referenced by llvm::MDLocationInfo::KeyTy::operator==().
getHashValue() [1/2]
unsigned llvm::MDLocationInfo::getHashValue (const KeyTy & Key) inline static
Definition at line 246 of file LLVMContextImpl.h.
References llvm::MDLocationInfo::KeyTy::Column, llvm::hash_combine(), llvm::MDLocationInfo::KeyTy::InlinedAt, llvm::MDLocationInfo::KeyTy::Line, and llvm::MDLocationInfo::KeyTy::Scope.
Referenced by getHashValue().
getHashValue() [2/2]
unsigned llvm::MDLocationInfo::getHashValue (const MDLocation * U) inline static
Definition at line 249 of file LLVMContextImpl.h.
References getHashValue().
getTombstoneKey()
MDLocation * llvm::MDLocationInfo::getTombstoneKey () inline static
Definition at line 243 of file LLVMContextImpl.h.
Referenced by llvm::MDLocationInfo::KeyTy::operator==().
isEqual() [1/2]
bool llvm::MDLocationInfo::isEqual (const KeyTy & LHS, const MDLocation * RHS) inline static
Definition at line 252 of file LLVMContextImpl.h.
isEqual() [2/2]
bool llvm::MDLocationInfo::isEqual (const MDLocation * LHS, const MDLocation * RHS) inline static
Definition at line 255 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h