LLVM: llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Section > > Struct Reference
LLVM API Documentation
llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Section > > Struct Reference
#include <ELFYAML.h>
Static Public Member Functions
static void mapping (IO &IO, std::unique_ptr< ELFYAML::Section > &Section)
static StringRef validate (IO &io, std::unique_ptr< ELFYAML::Section > &Section)
Detailed Description
Definition at line 208 of file ELFYAML.h.
Member Function Documentation
mapping()
void llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Section > >::mapping (IO & IO, std::unique_ptr< ELFYAML::Section > & Section) static
Definition at line 512 of file ELFYAML.cpp.
References llvm::cast(), mapping(), llvm::yaml::IO::mapRequired(), llvm::yaml::IO::outputting(), llvm::yaml::sectionMapping(), llvm::ELF::SHT_REL, and llvm::ELF::SHT_RELA.
Referenced by mapping().
validate()
StringRef llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Section > >::validate (IO & io, std::unique_ptr< ELFYAML::Section > & Section) static
Definition at line 534 of file ELFYAML.cpp.
References llvm::dyn_cast(), and validate().
Referenced by validate().
The documentation for this struct was generated from the following files:
ELFYAML.h
ELFYAML.cpp