LLVM: llvm::AMDGPURegisterInfo Struct Reference
LLVM API Documentation
llvm::AMDGPURegisterInfo Struct Reference
#include <AMDGPURegisterInfo.h>
Public Member Functions
AMDGPURegisterInfo (const AMDGPUSubtarget &st)
BitVector getReservedRegs (const MachineFunction &MF) const override
virtual const TargetRegisterClass * getCFGStructurizerRegClass (MVT VT) const
virtual unsigned getHWRegIndex (unsigned Reg) const
unsigned getSubRegFromChannel (unsigned Channel) const
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS) const override
unsigned getFrameRegister (const MachineFunction &MF) const override
unsigned getIndirectSubReg (unsigned IndirectIndex) const
Public Attributes
const AMDGPUSubtarget & ST
Static Public Attributes
static const MCPhysReg CalleeSavedReg = AMDGPU::NoRegister
Detailed Description
Definition at line 31 of file AMDGPURegisterInfo.h.
Constructor & Destructor Documentation
AMDGPURegisterInfo()
AMDGPURegisterInfo::AMDGPURegisterInfo (const AMDGPUSubtarget & st)
Definition at line 20 of file AMDGPURegisterInfo.cpp.
References ST.
Referenced by llvm::R600RegisterInfo::R600RegisterInfo(), and llvm::SIRegisterInfo::SIRegisterInfo().
Member Function Documentation
eliminateFrameIndex()
void AMDGPURegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS) const override
Definition at line 37 of file AMDGPURegisterInfo.cpp.
References llvm_unreachable.
getCalleeSavedRegs()
const MCPhysReg * AMDGPURegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Definition at line 33 of file AMDGPURegisterInfo.cpp.
References CalleeSavedReg.
getCFGStructurizerRegClass()
virtual const TargetRegisterClass * llvm::AMDGPURegisterInfo::getCFGStructurizerRegClass (MVT VT) const inline virtual
Reimplemented in llvm::R600RegisterInfo, and llvm::SIRegisterInfo.
Definition at line 41 of file AMDGPURegisterInfo.h.
getFrameRegister()
unsigned AMDGPURegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 44 of file AMDGPURegisterInfo.cpp.
getHWRegIndex()
virtual unsigned llvm::AMDGPURegisterInfo::getHWRegIndex (unsigned Reg) const inline virtual
Reimplemented in llvm::R600RegisterInfo, and llvm::SIRegisterInfo.
Definition at line 45 of file AMDGPURegisterInfo.h.
getIndirectSubReg()
unsigned AMDGPURegisterInfo::getIndirectSubReg (unsigned IndirectIndex) const
Definition at line 60 of file AMDGPURegisterInfo.cpp.
References getSubRegFromChannel().
getReservedRegs()
BitVector llvm::AMDGPURegisterInfo::getReservedRegs (const MachineFunction & MF) const inline override
Definition at line 37 of file AMDGPURegisterInfo.h.
getSubRegFromChannel()
unsigned AMDGPURegisterInfo::getSubRegFromChannel (unsigned Channel) const
Returns
the sub reg enum value for the given Channel (e.g. getSubRegFromChannel(0) -> AMDGPU::sub0)
Definition at line 48 of file AMDGPURegisterInfo.cpp.
References llvm::array_lengthof().
Referenced by getIndirectSubReg().
Member Data Documentation
CalleeSavedReg
const MCPhysReg AMDGPURegisterInfo::CalleeSavedReg = AMDGPU::NoRegister static
Definition at line 32 of file AMDGPURegisterInfo.h.
Referenced by getCalleeSavedRegs().
ST
const AMDGPUSubtarget& llvm::AMDGPURegisterInfo::ST
Definition at line 33 of file AMDGPURegisterInfo.h.
Referenced by AMDGPURegisterInfo(), llvm::SIRegisterInfo::eliminateFrameIndex(), llvm::SIRegisterInfo::getRegPressureSetLimit(), llvm::R600RegisterInfo::getReservedRegs(), and llvm::SIRegisterInfo::getReservedRegs().
The documentation for this struct was generated from the following files:
AMDGPURegisterInfo.h
AMDGPURegisterInfo.cpp