LLVM: llvm::ELF::Elf32_Rela Struct Reference
LLVM API Documentation
llvm::ELF::Elf32_Rela Struct Reference
#include <ELF.h>
Public Member Functions
Elf32_Word getSymbol () const
unsigned char getType () const
void setSymbol (Elf32_Word s)
void setType (unsigned char t)
void setSymbolAndType (Elf32_Word s, unsigned char t)
Public Attributes
Elf32_Addr r_offset
Elf32_Word r_info
Elf32_Sword r_addend
Detailed Description
Definition at line 815 of file Support/ELF.h.
Member Function Documentation
getSymbol()
Elf32_Word llvm::ELF::Elf32_Rela::getSymbol () const inline
Definition at line 822 of file Support/ELF.h.
References r_info.
Referenced by setType().
getType()
unsigned char llvm::ELF::Elf32_Rela::getType () const inline
Definition at line 823 of file Support/ELF.h.
References r_info.
Referenced by setSymbol().
setSymbol()
void llvm::ELF::Elf32_Rela::setSymbol (Elf32_Word s) inline
Definition at line 824 of file Support/ELF.h.
References getType(), and setSymbolAndType().
setSymbolAndType()
void llvm::ELF::Elf32_Rela::setSymbolAndType (Elf32_Word s, unsigned char t) inline
Definition at line 826 of file Support/ELF.h.
References r_info.
Referenced by setSymbol(), and setType().
setType()
void llvm::ELF::Elf32_Rela::setType (unsigned char t) inline
Definition at line 825 of file Support/ELF.h.
References getSymbol(), and setSymbolAndType().
Member Data Documentation
r_addend
Elf32_Sword llvm::ELF::Elf32_Rela::r_addend
Definition at line 818 of file Support/ELF.h.
r_info
Elf32_Word llvm::ELF::Elf32_Rela::r_info
Definition at line 817 of file Support/ELF.h.
Referenced by getSymbol(), getType(), and setSymbolAndType().
r_offset
Elf32_Addr llvm::ELF::Elf32_Rela::r_offset
Definition at line 816 of file Support/ELF.h.
The documentation for this struct was generated from the following file:
Support/ELF.h