LLVM: llvm::NVPTXLowerAggrCopies Struct Reference
LLVM API Documentation
llvm::NVPTXLowerAggrCopies Struct Reference
#include <NVPTXLowerAggrCopies.h>
Public Member Functions
NVPTXLowerAggrCopies ()
void getAnalysisUsage (AnalysisUsage &AU) const override
bool runOnFunction (Function &F) override
const char * getPassName () const override
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
static const unsigned MaxAggrCopySize = 128
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
Definition at line 26 of file NVPTXLowerAggrCopies.h.
Constructor & Destructor Documentation
NVPTXLowerAggrCopies()
llvm::NVPTXLowerAggrCopies::NVPTXLowerAggrCopies () inline
Definition at line 29 of file NVPTXLowerAggrCopies.h.
References llvm::FunctionPass::FunctionPass(), and ID.
Member Function Documentation
getAnalysisUsage()
void llvm::NVPTXLowerAggrCopies::getAnalysisUsage (AnalysisUsage &) const inline override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 31 of file NVPTXLowerAggrCopies.h.
References llvm::AnalysisUsage::addPreserved(), and llvm::AnalysisUsage::addRequired().
getPassName()
const char * llvm::NVPTXLowerAggrCopies::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 41 of file NVPTXLowerAggrCopies.h.
runOnFunction()
bool NVPTXLowerAggrCopies::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 102 of file NVPTXLowerAggrCopies.cpp.
References convertMemSetToLoop(), convertTransferToLoop(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), F, llvm::ConstantInt::get(), llvm::Pass::getAnalysis(), llvm::MemIntrinsic::getDest(), llvm::Type::getInt32Ty(), llvm::MemIntrinsic::getLength(), llvm::User::getOperand(), llvm::MemTransferInst::getSource(), llvm::Value::getType(), llvm::DataLayout::getTypeStoreSize(), llvm::MemSetInst::getValue(), llvm::LoadInst::isVolatile(), llvm::StoreInst::isVolatile(), MaxAggrCopySize, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Value::user_back(), and llvm::Value::user_begin().
Member Data Documentation
ID
char NVPTXLowerAggrCopies::ID = 0 static
Definition at line 27 of file NVPTXLowerAggrCopies.h.
Referenced by NVPTXLowerAggrCopies().
MaxAggrCopySize
const unsigned llvm::NVPTXLowerAggrCopies::MaxAggrCopySize = 128 static
Definition at line 39 of file NVPTXLowerAggrCopies.h.
Referenced by runOnFunction().
The documentation for this struct was generated from the following files:
NVPTXLowerAggrCopies.h
NVPTXLowerAggrCopies.cpp