LLVM: llvm::Linker::IdentifiedStructTypeSet Struct Reference
LLVM API Documentation
llvm::Linker::IdentifiedStructTypeSet Struct Reference
#include <Linker.h>
Public Member Functions
void addNonOpaque (StructType *Ty)
void addOpaque (StructType *Ty)
StructType * findNonOpaque (ArrayRef< Type * > ETypes, bool IsPacked)
bool hasType (StructType *Ty)
Public Attributes
OpaqueStructTypeSet OpaqueStructTypes
NonOpaqueStructTypeSet NonOpaqueStructTypes
Detailed Description
Definition at line 49 of file llvm/Linker/Linker.h.
Member Function Documentation
addNonOpaque()
void Linker::IdentifiedStructTypeSet::addNonOpaque (StructType * Ty)
Definition at line 1660 of file LinkModules.cpp.
References llvm::StructType::isOpaque(), and NonOpaqueStructTypes.
addOpaque()
void Linker::IdentifiedStructTypeSet::addOpaque (StructType * Ty)
Definition at line 1665 of file LinkModules.cpp.
References llvm::StructType::isOpaque(), and OpaqueStructTypes.
findNonOpaque()
StructType * Linker::IdentifiedStructTypeSet::findNonOpaque (ArrayRef< Type * > ETypes, bool IsPacked)
Definition at line 1671 of file LinkModules.cpp.
References I, and NonOpaqueStructTypes.
hasType()
bool Linker::IdentifiedStructTypeSet::hasType (StructType * Ty)
Definition at line 1680 of file LinkModules.cpp.
References I, llvm::StructType::isOpaque(), NonOpaqueStructTypes, and OpaqueStructTypes.
Member Data Documentation
NonOpaqueStructTypes
NonOpaqueStructTypeSet llvm::Linker::IdentifiedStructTypeSet::NonOpaqueStructTypes
Definition at line 54 of file llvm/Linker/Linker.h.
Referenced by addNonOpaque(), findNonOpaque(), and hasType().
OpaqueStructTypes
OpaqueStructTypeSet llvm::Linker::IdentifiedStructTypeSet::OpaqueStructTypes
Definition at line 51 of file llvm/Linker/Linker.h.
Referenced by addOpaque(), and hasType().
The documentation for this struct was generated from the following files:
llvm/Linker/Linker.h
LinkModules.cpp