LLVM: llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, false >, isRela > Struct Template Reference
LLVM API Documentation
llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, false >, isRela > Struct Template Reference
#include <ELFTypes.h>
Public Member Functions
uint32_t getSymbol (bool isMips64EL) const
unsigned char getType (bool isMips64EL) const
void setSymbol (uint32_t s)
void setType (unsigned char t)
void setSymbolAndType (uint32_t s, unsigned char t)
Detailed Description
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela>
struct llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, false >, isRela >
Definition at line 391 of file ELFTypes.h.
Member Function Documentation
getSymbol()
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela> uint32_t llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, false >, isRela >::getSymbol (bool isMips64EL) const inline
Definition at line 398 of file ELFTypes.h.
References getSymbol().
Referenced by getSymbol(), and setType().
getType()
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela> unsigned char llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, false >, isRela >::getType (bool isMips64EL) const inline
Definition at line 401 of file ELFTypes.h.
Referenced by setSymbol().
setSymbol()
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, false >, isRela >::setSymbol (uint32_t s) inline
Definition at line 404 of file ELFTypes.h.
References getType(), and setSymbolAndType().
setSymbolAndType()
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, false >, isRela >::setSymbolAndType (uint32_t s, unsigned char t) inline
Definition at line 406 of file ELFTypes.h.
Referenced by setSymbol(), and setType().
setType()
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, false >, isRela >::setType (unsigned char t) inline
Definition at line 405 of file ELFTypes.h.
References getSymbol(), and setSymbolAndType().
The documentation for this struct was generated from the following file:
ELFTypes.h