LLVM: GraphSession Struct Reference
LLVM API Documentation
GraphSession Struct Reference
Public Member Functions
bool TryFindProgram (StringRef Names, std::string &ProgramPath)
Public Attributes
std::string LogBuffer
Detailed Description
Definition at line 101 of file GraphWriter.cpp.
Member Function Documentation
TryFindProgram()
bool GraphSession::TryFindProgram (StringRef Names, std::string & ProgramPath) inline
Definition at line 103 of file GraphWriter.cpp.
References llvm::sys::findProgramByName(), LogBuffer, Name, P, and llvm::StringRef::split().
Referenced by llvm::DisplayGraph().
Member Data Documentation
LogBuffer
std::string GraphSession::LogBuffer
Definition at line 102 of file GraphWriter.cpp.
Referenced by llvm::DisplayGraph(), and TryFindProgram().
The documentation for this struct was generated from the following file:
GraphWriter.cpp