LLVM: llvm::ELF::Elf64_Sym Struct Reference
LLVM API Documentation
llvm::ELF::Elf64_Sym Struct Reference
#include <ELF.h>
Public Member Functions
unsigned char getBinding () const
unsigned char getType () const
void setBinding (unsigned char b)
void setType (unsigned char t)
void setBindingAndType (unsigned char b, unsigned char t)
Public Attributes
Elf64_Word st_name
unsigned char st_info
unsigned char st_other
Elf64_Half st_shndx
Elf64_Addr st_value
Elf64_Xword st_size
Detailed Description
Definition at line 734 of file Support/ELF.h.
Member Function Documentation
getBinding()
unsigned char llvm::ELF::Elf64_Sym::getBinding () const inline
Definition at line 744 of file Support/ELF.h.
References st_info.
Referenced by setType().
getType()
unsigned char llvm::ELF::Elf64_Sym::getType () const inline
Definition at line 745 of file Support/ELF.h.
References st_info.
Referenced by setBinding().
setBinding()
void llvm::ELF::Elf64_Sym::setBinding (unsigned char b) inline
Definition at line 746 of file Support/ELF.h.
References getType(), and setBindingAndType().
setBindingAndType()
void llvm::ELF::Elf64_Sym::setBindingAndType (unsigned char b, unsigned char t) inline
Definition at line 748 of file Support/ELF.h.
References st_info.
Referenced by setBinding(), and setType().
setType()
void llvm::ELF::Elf64_Sym::setType (unsigned char t) inline
Definition at line 747 of file Support/ELF.h.
References getBinding(), and setBindingAndType().
Member Data Documentation
st_info
unsigned char llvm::ELF::Elf64_Sym::st_info
Definition at line 736 of file Support/ELF.h.
Referenced by getBinding(), getType(), and setBindingAndType().
st_name
Elf64_Word llvm::ELF::Elf64_Sym::st_name
Definition at line 735 of file Support/ELF.h.
st_other
unsigned char llvm::ELF::Elf64_Sym::st_other
Definition at line 737 of file Support/ELF.h.
st_shndx
Elf64_Half llvm::ELF::Elf64_Sym::st_shndx
Definition at line 738 of file Support/ELF.h.
st_size
Elf64_Xword llvm::ELF::Elf64_Sym::st_size
Definition at line 740 of file Support/ELF.h.
st_value
Elf64_Addr llvm::ELF::Elf64_Sym::st_value
Definition at line 739 of file Support/ELF.h.
The documentation for this struct was generated from the following file:
Support/ELF.h