LLVM: llvm::StackMaps::LiveOutReg Struct Reference
LLVM API Documentation
llvm::StackMaps::LiveOutReg Struct Reference
#include <StackMaps.h>
Public Member Functions
LiveOutReg ()
LiveOutReg (unsigned short Reg, unsigned short RegNo, unsigned short Size)
void MarkInvalid ()
bool operator< (const LiveOutReg &LO) const
Static Public Member Functions
static bool IsInvalid (const LiveOutReg &LO)
Public Attributes
unsigned short Reg
unsigned short RegNo
unsigned short Size
Detailed Description
Definition at line 144 of file StackMaps.h.
Constructor & Destructor Documentation
LiveOutReg() [1/2]
llvm::StackMaps::LiveOutReg::LiveOutReg () inline
Definition at line 149 of file StackMaps.h.
References Reg, RegNo, and Size.
Referenced by IsInvalid(), and operator<().
LiveOutReg() [2/2]
llvm::StackMaps::LiveOutReg::LiveOutReg (unsigned short Reg, unsigned short RegNo, unsigned short Size) inline
Definition at line 150 of file StackMaps.h.
References Reg, RegNo, and Size.
Member Function Documentation
IsInvalid()
bool llvm::StackMaps::LiveOutReg::IsInvalid (const LiveOutReg & LO) inline static
Definition at line 157 of file StackMaps.h.
References LiveOutReg().
MarkInvalid()
void llvm::StackMaps::LiveOutReg::MarkInvalid () inline
Definition at line 153 of file StackMaps.h.
References Reg.
operator<()
bool llvm::StackMaps::LiveOutReg::operator< (const LiveOutReg & LO) const inline
Definition at line 156 of file StackMaps.h.
References LiveOutReg(), and RegNo.
Member Data Documentation
Reg
unsigned short llvm::StackMaps::LiveOutReg::Reg
Definition at line 145 of file StackMaps.h.
Referenced by LiveOutReg(), LiveOutReg(), and MarkInvalid().
RegNo
unsigned short llvm::StackMaps::LiveOutReg::RegNo
Definition at line 146 of file StackMaps.h.
Referenced by LiveOutReg(), LiveOutReg(), and operator<().
Size
unsigned short llvm::StackMaps::LiveOutReg::Size
Definition at line 147 of file StackMaps.h.
Referenced by LiveOutReg(), and LiveOutReg().
The documentation for this struct was generated from the following file:
StackMaps.h