LLVM: llvm::GraphTraits< CallGraph * > Struct Reference
LLVM API Documentation
llvm::GraphTraits< CallGraph * > Struct Reference
#include <CallGraph.h>
Public Types
typedef std::pair< const Function *, CallGraphNode * > PairTy
typedef std::pointer_to_unary_function< PairTy, CallGraphNode & > DerefFun
typedef mapped_iterator< CallGraph::iterator, DerefFun > nodes_iterator
typedef CallGraph *::UnknownGraphTypeError NodeType
Public Types inherited from llvm::GraphTraits< CallGraphNode * >
typedef CallGraphNode NodeType
typedef CallGraphNode::CallRecord CGNPairTy
typedef std::pointer_to_unary_function< CGNPairTy, CallGraphNode * > CGNDerefFun
typedef mapped_iterator< NodeType::iterator, CGNDerefFun > ChildIteratorType
Static Public Member Functions
static NodeType * getEntryNode (CallGraph *CGN)
static nodes_iterator nodes_begin (CallGraph *CG)
static nodes_iterator nodes_end (CallGraph *CG)
static CallGraphNode & CGdereference (PairTy P)
Static Public Member Functions inherited from llvm::GraphTraits< CallGraphNode * >
static NodeType * getEntryNode (CallGraphNode *CGN)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
static CallGraphNode * CGNDeref (CGNPairTy P)
Detailed Description
Definition at line 441 of file CallGraph.h.
Member Typedef Documentation
DerefFun
typedef std::pointer_to_unary_function<PairTy, CallGraphNode &> llvm::GraphTraits< CallGraph * >::DerefFun
Definition at line 446 of file CallGraph.h.
nodes_iterator
typedef mapped_iterator<CallGraph::iterator, DerefFun> llvm::GraphTraits< CallGraph * >::nodes_iterator
Definition at line 449 of file CallGraph.h.
NodeType
typedef CallGraph *::UnknownGraphTypeError llvm::GraphTraits< CallGraph * >::NodeType
Definition at line 60 of file GraphTraits.h.
PairTy
typedef std::pair<const Function *, CallGraphNode *> llvm::GraphTraits< CallGraph * >::PairTy
Definition at line 445 of file CallGraph.h.
Member Function Documentation
CGdereference()
CallGraphNode & llvm::GraphTraits< CallGraph * >::CGdereference (PairTy P) inline static
Definition at line 457 of file CallGraph.h.
References P.
Referenced by nodes_begin(), and nodes_end().
getEntryNode()
NodeType * llvm::GraphTraits< CallGraph * >::getEntryNode (CallGraph * CGN) inline static
Definition at line 442 of file CallGraph.h.
References llvm::CallGraph::getExternalCallingNode().
nodes_begin()
nodes_iterator llvm::GraphTraits< CallGraph * >::nodes_begin (CallGraph * CG) inline static
Definition at line 450 of file CallGraph.h.
References llvm::CallGraph::begin(), CGdereference(), and llvm::map_iterator().
nodes_end()
nodes_iterator llvm::GraphTraits< CallGraph * >::nodes_end (CallGraph * CG) inline static
Definition at line 453 of file CallGraph.h.
References CGdereference(), llvm::CallGraph::end(), and llvm::map_iterator().
The documentation for this struct was generated from the following file:
CallGraph.h