LLVM: BaseIndexOffset Struct Reference
LLVM API Documentation
BaseIndexOffset Struct Reference
Public Member Functions
BaseIndexOffset ()
BaseIndexOffset (SDValue Base, SDValue Index, int64_t Offset, bool IsIndexSignExt)
bool equalBaseIndex (const BaseIndexOffset &Other)
Static Public Member Functions
static BaseIndexOffset match (SDValue Ptr)
Parses tree in Ptr for base, index, offset addresses.
Public Attributes
SDValue Base
SDValue Index
int64_t Offset
bool IsIndexSignExt
Detailed Description
Helper struct to parse and store a memory address as base + index + offset. We ignore sign extensions when it is safe to do so. The following two expressions are not equivalent. To differentiate we need to store whether there was a sign extension involved in the index computation. (load (i64 add (i64 copyfromreg c) (i64 signextend (add (i8 load index) (i8 1)))) vs
(load (i64 add (i64 copyfromreg c) (i64 signextend (i32 add (i32 signextend (i8 load index)) (i32 1)))))
Definition at line 9615 of file DAGCombiner.cpp.
Constructor & Destructor Documentation
BaseIndexOffset() [1/2]
BaseIndexOffset::BaseIndexOffset () inline
Definition at line 9621 of file DAGCombiner.cpp.
References IsIndexSignExt, and Offset.
Referenced by equalBaseIndex(), and match().
BaseIndexOffset() [2/2]
BaseIndexOffset::BaseIndexOffset (SDValue Base, SDValue Index, int64_t Offset, bool IsIndexSignExt) inline
Definition at line 9623 of file DAGCombiner.cpp.
References Base, Index, IsIndexSignExt, and Offset.
Member Function Documentation
equalBaseIndex()
bool BaseIndexOffset::equalBaseIndex (const BaseIndexOffset & Other) inline
Definition at line 9627 of file DAGCombiner.cpp.
References Base, BaseIndexOffset(), Index, and IsIndexSignExt.
match()
BaseIndexOffset BaseIndexOffset::match (SDValue Ptr) inline static
Parses tree in Ptr for base, index, offset addresses.
Definition at line 9633 of file DAGCombiner.cpp.
References llvm::ISD::ADD, Base, BaseIndexOffset(), llvm::cast(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), Index, llvm::isa(), IsIndexSignExt, llvm::ISD::MUL, Offset, and llvm::ISD::SIGN_EXTEND.
Member Data Documentation
Base
SDValue BaseIndexOffset::Base
Definition at line 9616 of file DAGCombiner.cpp.
Referenced by BaseIndexOffset(), equalBaseIndex(), and match().
Index
SDValue BaseIndexOffset::Index
Definition at line 9617 of file DAGCombiner.cpp.
Referenced by BaseIndexOffset(), equalBaseIndex(), and match().
IsIndexSignExt
bool BaseIndexOffset::IsIndexSignExt
Definition at line 9619 of file DAGCombiner.cpp.
Referenced by BaseIndexOffset(), BaseIndexOffset(), equalBaseIndex(), and match().
Offset
int64_t BaseIndexOffset::Offset
Definition at line 9618 of file DAGCombiner.cpp.
Referenced by BaseIndexOffset(), BaseIndexOffset(), and match().
The documentation for this struct was generated from the following file:
DAGCombiner.cpp