LLVM: llvm::GraphTraits< MachineRegionInfoPass * > Struct Reference
LLVM API Documentation
llvm::GraphTraits< MachineRegionInfoPass * > Struct Reference
#include <MachineRegionInfo.h>
Public Types
typedef df_iterator< NodeType *, SmallPtrSet< NodeType *, 8 >, false, GraphTraits< FlatIt< NodeType * > > > nodes_iterator
typedef MachineRegionInfoPass *::UnknownGraphTypeError NodeType
Public Types inherited from llvm::GraphTraits< MachineRegionInfo * >
typedef df_iterator< NodeType *, SmallPtrSet< NodeType *, 8 >, false, GraphTraits< FlatIt< NodeType * > > > nodes_iterator
typedef MachineRegionInfo *::UnknownGraphTypeError NodeType
Public Types inherited from llvm::GraphTraits< FlatIt< MachineRegionNode * > >
typedef FlatIt< MachineRegionNode * >::UnknownGraphTypeError NodeType
Static Public Member Functions
static NodeType * getEntryNode (MachineRegionInfoPass *RI)
static nodes_iterator nodes_begin (MachineRegionInfoPass *RI)
static nodes_iterator nodes_end (MachineRegionInfoPass *RI)
Static Public Member Functions inherited from llvm::GraphTraits< MachineRegionInfo * >
static NodeType * getEntryNode (MachineRegionInfo *RI)
static nodes_iterator nodes_begin (MachineRegionInfo *RI)
static nodes_iterator nodes_end (MachineRegionInfo *RI)
Detailed Description
Definition at line 161 of file MachineRegionInfo.h.
Member Typedef Documentation
nodes_iterator
typedef df_iterator<NodeType*, SmallPtrSet<NodeType*, 8>, false, GraphTraits<FlatIt<NodeType*> > > llvm::GraphTraits< MachineRegionInfoPass * >::nodes_iterator
Definition at line 164 of file MachineRegionInfo.h.
NodeType
typedef MachineRegionInfoPass *::UnknownGraphTypeError llvm::GraphTraits< MachineRegionInfoPass * >::NodeType
Definition at line 60 of file GraphTraits.h.
Member Function Documentation
getEntryNode()
NodeType * llvm::GraphTraits< MachineRegionInfoPass * >::getEntryNode (MachineRegionInfoPass * RI) inline static
Definition at line 166 of file MachineRegionInfo.h.
References llvm::MachineRegionInfoPass::getRegionInfo().
nodes_begin()
nodes_iterator llvm::GraphTraits< MachineRegionInfoPass * >::nodes_begin (MachineRegionInfoPass * RI) inline static
Definition at line 169 of file MachineRegionInfo.h.
References llvm::MachineRegionInfoPass::getRegionInfo().
nodes_end()
nodes_iterator llvm::GraphTraits< MachineRegionInfoPass * >::nodes_end (MachineRegionInfoPass * RI) inline static
Definition at line 172 of file MachineRegionInfo.h.
References llvm::MachineRegionInfoPass::getRegionInfo().
The documentation for this struct was generated from the following file:
MachineRegionInfo.h