LLVM: llvm::ilist_nextprev_traits< NodeTy > Struct Template Reference
LLVM API Documentation
llvm::ilist_nextprev_traits< NodeTy > Struct Template Reference
#include <ilist.h>
Static Public Member Functions
static NodeTy * getPrev (NodeTy *N)
static NodeTy * getNext (NodeTy *N)
static const NodeTy * getPrev (const NodeTy *N)
static const NodeTy * getNext (const NodeTy *N)
static void setPrev (NodeTy *N, NodeTy *Prev)
static void setNext (NodeTy *N, NodeTy *Next)
Detailed Description
template<typename NodeTy>
struct llvm::ilist_nextprev_traits< NodeTy >
ilist_nextprev_traits - A fragment for template traits for intrusive list that provides default next/prev implementations for common operations.
Definition at line 56 of file ilist.h.
Member Function Documentation
getNext() [1/2]
template<typename NodeTy> const NodeTy * llvm::ilist_nextprev_traits< NodeTy >::getNext (const NodeTy * N) inline static
Definition at line 60 of file ilist.h.
References N.
getNext() [2/2]
template<typename NodeTy> NodeTy * llvm::ilist_nextprev_traits< NodeTy >::getNext (NodeTy * N) inline static
Definition at line 58 of file ilist.h.
References N.
Referenced by llvm::ilist_iterator< const NodeTy >::operator++(), and llvm::size_type< NodeTy >::remove().
getPrev() [1/2]
template<typename NodeTy> const NodeTy * llvm::ilist_nextprev_traits< NodeTy >::getPrev (const NodeTy * N) inline static
Definition at line 59 of file ilist.h.
References N.
getPrev() [2/2]
template<typename NodeTy> NodeTy * llvm::ilist_nextprev_traits< NodeTy >::getPrev (NodeTy * N) inline static
Definition at line 57 of file ilist.h.
References N.
Referenced by llvm::size_type< NodeTy >::back(), llvm::size_type< NodeTy >::back(), llvm::ilist_sentinel_traits< NodeTy >::ensureHead(), llvm::size_type< NodeTy >::insert(), llvm::ilist_iterator< const NodeTy >::operator--(), and llvm::size_type< NodeTy >::remove().
setNext()
template<typename NodeTy> void llvm::ilist_nextprev_traits< NodeTy >::setNext (NodeTy * N, NodeTy * Next) inline static
Definition at line 63 of file ilist.h.
References N.
Referenced by llvm::ilist_sentinel_traits< NodeTy >::ensureHead(), llvm::size_type< NodeTy >::insert(), and llvm::size_type< NodeTy >::remove().
setPrev()
template<typename NodeTy> void llvm::ilist_nextprev_traits< NodeTy >::setPrev (NodeTy * N, NodeTy * Prev) inline static
Definition at line 62 of file ilist.h.
References N.
Referenced by llvm::size_type< NodeTy >::clearAndLeakNodesUnsafely(), llvm::size_type< NodeTy >::insert(), llvm::ilist_sentinel_traits< NodeTy >::noteHead(), and llvm::size_type< NodeTy >::remove().
The documentation for this struct was generated from the following file:
ilist.h