LLVM: llvm::GraphTraits< CallGraphNode * > Struct Reference
LLVM API Documentation
llvm::GraphTraits< CallGraphNode * > Struct Reference
#include <CallGraph.h>
Public Types
typedef CallGraphNode NodeType
typedef CallGraphNode::CallRecord CGNPairTy
typedef std::pointer_to_unary_function< CGNPairTy, CallGraphNode * > CGNDerefFun
typedef mapped_iterator< NodeType::iterator, CGNDerefFun > ChildIteratorType
Static Public Member Functions
static NodeType * getEntryNode (CallGraphNode *CGN)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
static CallGraphNode * CGNDeref (CGNPairTy P)
Detailed Description
Definition at line 397 of file CallGraph.h.
Member Typedef Documentation
CGNDerefFun
typedef std::pointer_to_unary_function<CGNPairTy, CallGraphNode *> llvm::GraphTraits< CallGraphNode * >::CGNDerefFun
Definition at line 402 of file CallGraph.h.
CGNPairTy
typedef CallGraphNode::CallRecord llvm::GraphTraits< CallGraphNode * >::CGNPairTy
Definition at line 400 of file CallGraph.h.
ChildIteratorType
typedef mapped_iterator<NodeType::iterator, CGNDerefFun> llvm::GraphTraits< CallGraphNode * >::ChildIteratorType
Definition at line 406 of file CallGraph.h.
NodeType
typedef CallGraphNode llvm::GraphTraits< CallGraphNode * >::NodeType
Definition at line 398 of file CallGraph.h.
Member Function Documentation
CGNDeref()
CallGraphNode * llvm::GraphTraits< CallGraphNode * >::CGNDeref (CGNPairTy P) inline static
Definition at line 415 of file CallGraph.h.
References P.
Referenced by child_begin(), and child_end().
child_begin()
ChildIteratorType llvm::GraphTraits< CallGraphNode * >::child_begin (NodeType * N) inline static
Definition at line 408 of file CallGraph.h.
References CGNDeref(), llvm::map_iterator(), and N.
child_end()
ChildIteratorType llvm::GraphTraits< CallGraphNode * >::child_end (NodeType * N) inline static
Definition at line 411 of file CallGraph.h.
References CGNDeref(), llvm::map_iterator(), and N.
getEntryNode()
NodeType * llvm::GraphTraits< CallGraphNode * >::getEntryNode (CallGraphNode * CGN) inline static
Definition at line 404 of file CallGraph.h.
The documentation for this struct was generated from the following file:
CallGraph.h