LLVM: llvm::ELF::Elf32_Rel Struct Reference
LLVM API Documentation
llvm::ELF::Elf32_Rel Struct Reference
#include <ELF.h>
Public Member Functions
Elf32_Word getSymbol () const
unsigned char getType () const
void setSymbol (Elf32_Word s)
void setType (unsigned char t)
void setSymbolAndType (Elf32_Word s, unsigned char t)
Public Attributes
Elf32_Addr r_offset
Elf32_Word r_info
Detailed Description
Definition at line 799 of file Support/ELF.h.
Member Function Documentation
getSymbol()
Elf32_Word llvm::ELF::Elf32_Rel::getSymbol () const inline
Definition at line 805 of file Support/ELF.h.
References r_info.
Referenced by setType().
getType()
unsigned char llvm::ELF::Elf32_Rel::getType () const inline
Definition at line 806 of file Support/ELF.h.
References r_info.
Referenced by setSymbol().
setSymbol()
void llvm::ELF::Elf32_Rel::setSymbol (Elf32_Word s) inline
Definition at line 807 of file Support/ELF.h.
References getType(), and setSymbolAndType().
setSymbolAndType()
void llvm::ELF::Elf32_Rel::setSymbolAndType (Elf32_Word s, unsigned char t) inline
Definition at line 809 of file Support/ELF.h.
References r_info.
Referenced by setSymbol(), and setType().
setType()
void llvm::ELF::Elf32_Rel::setType (unsigned char t) inline
Definition at line 808 of file Support/ELF.h.
References getSymbol(), and setSymbolAndType().
Member Data Documentation
r_info
Elf32_Word llvm::ELF::Elf32_Rel::r_info
Definition at line 801 of file Support/ELF.h.
Referenced by getSymbol(), getType(), and setSymbolAndType().
r_offset
Elf32_Addr llvm::ELF::Elf32_Rel::r_offset
Definition at line 800 of file Support/ELF.h.
The documentation for this struct was generated from the following file:
Support/ELF.h