LLVM: llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, true >, isRela > Struct Template Reference
LLVM API Documentation
llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, true >, isRela > Struct Template Reference
#include <ELFTypes.h>
Public Member Functions
uint32_t getSymbol (bool isMips64EL) const
uint32_t getType (bool isMips64EL) const
void setSymbol (uint32_t s)
void setType (uint32_t t)
void setSymbolAndType (uint32_t s, uint32_t t)
Detailed Description
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela>
struct llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, true >, isRela >
Definition at line 370 of file ELFTypes.h.
Member Function Documentation
getSymbol()
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela> uint32_t llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, true >, isRela >::getSymbol (bool isMips64EL) const inline
Definition at line 377 of file ELFTypes.h.
References getSymbol().
Referenced by getSymbol(), and setType().
getType()
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela> uint32_t llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, true >, isRela >::getType (bool isMips64EL) const inline
Definition at line 380 of file ELFTypes.h.
Referenced by setSymbol().
setSymbol()
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, true >, isRela >::setSymbol (uint32_t s) inline
Definition at line 383 of file ELFTypes.h.
References getType(), and setSymbolAndType().
setSymbolAndType()
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, true >, isRela >::setSymbolAndType (uint32_t s, uint32_t t) inline
Definition at line 385 of file ELFTypes.h.
Referenced by setSymbol(), and setType().
setType()
template<endianness TargetEndianness, std::size_t MaxAlign, bool isRela> void llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, true >, isRela >::setType (uint32_t t) inline
Definition at line 384 of file ELFTypes.h.
References getSymbol(), and setSymbolAndType().
The documentation for this struct was generated from the following file:
ELFTypes.h