LLVM: llvm::DOTGraphTraits< ScheduleDAGMI * > Struct Reference
LLVM API Documentation
llvm::DOTGraphTraits< ScheduleDAGMI * > Struct Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType>
std::string getNodeLabel (const void *, const GraphType &)
Static Public Member Functions
static std::string getGraphName (const ScheduleDAG *G)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const SUnit *Node)
static bool hasNodeAddressLabel (const SUnit *Node, const ScheduleDAG *Graph)
static std::string getEdgeAttributes (const SUnit *Node, SUnitIterator EI, const ScheduleDAG *Graph)
static std::string getNodeLabel (const SUnit *SU, const ScheduleDAG *G)
static std::string getNodeDescription (const SUnit *SU, const ScheduleDAG *G)
static std::string getNodeAttributes (const SUnit *N, const ScheduleDAG *G)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType>
static std::string getGraphName (const GraphType &)
template<typename GraphType>
static std::string getGraphProperties (const GraphType &)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const void *)
template<typename GraphType>
static bool hasNodeAddressLabel (const void *, const GraphType &)
template<typename GraphType>
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType>
static std::string getNodeAttributes (const void *, const GraphType &)
template<typename EdgeIter, typename GraphType>
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
template<typename EdgeIter>
static std::string getEdgeSourceLabel (const void *, EdgeIter)
template<typename EdgeIter>
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
template<typename EdgeIter>
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
static bool hasEdgeDestLabels ()
static unsigned numEdgeDestLabels (const void *)
static std::string getEdgeDestLabel (const void *, unsigned)
template<typename GraphType, typename GraphWriter>
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
Definition at line 3232 of file MachineScheduler.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< ScheduleDAGMI * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 3234 of file MachineScheduler.cpp.
References llvm::DefaultDOTGraphTraits::DefaultDOTGraphTraits(), and llvm::DefaultDOTGraphTraits::isSimple().
Member Function Documentation
getEdgeAttributes()
std::string llvm::DOTGraphTraits< ScheduleDAGMI * >::getEdgeAttributes (const SUnit * Node, SUnitIterator EI, const ScheduleDAG * Graph) inline static
If you want to override the dot attributes printed for a particular edge, override this method.
Definition at line 3255 of file MachineScheduler.cpp.
References llvm::SUnitIterator::isArtificialDep(), and llvm::SUnitIterator::isCtrlDep().
getGraphName()
std::string llvm::DOTGraphTraits< ScheduleDAGMI * >::getGraphName (const ScheduleDAG * G) inline static
Definition at line 3236 of file MachineScheduler.cpp.
References G.
getNodeAttributes()
std::string llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeAttributes (const SUnit * N, const ScheduleDAG * G) inline static
Definition at line 3280 of file MachineScheduler.cpp.
References G, llvm::DOT::getColorString(), llvm::SchedDFSResult::getSubtreeID(), llvm::ScheduleDAGMI::hasVRegLiveness(), and N.
getNodeDescription()
std::string llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeDescription (const SUnit * SU, const ScheduleDAG * G) inline static
Definition at line 3276 of file MachineScheduler.cpp.
References G.
getNodeLabel()
std::string llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeLabel (const SUnit * SU, const ScheduleDAG * G) inline static
Definition at line 3265 of file MachineScheduler.cpp.
References G, llvm::SchedDFSResult::getNumInstrs(), llvm::ScheduleDAGMI::hasVRegLiveness(), llvm::SUnit::NodeNum, and llvm::raw_string_ostream::str().
hasNodeAddressLabel()
bool llvm::DOTGraphTraits< ScheduleDAGMI * >::hasNodeAddressLabel (const SUnit * Node, const ScheduleDAG * Graph) inline static
Definition at line 3248 of file MachineScheduler.cpp.
isNodeHidden()
bool llvm::DOTGraphTraits< ScheduleDAGMI * >::isNodeHidden (const SUnit * Node) inline static
Definition at line 3244 of file MachineScheduler.cpp.
References llvm::SUnit::Preds, and llvm::SUnit::Succs.
renderGraphFromBottomUp()
bool llvm::DOTGraphTraits< ScheduleDAGMI * >::renderGraphFromBottomUp () inline static
Definition at line 3240 of file MachineScheduler.cpp.
The documentation for this struct was generated from the following file:
MachineScheduler.cpp