LLVM: llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false > Struct Template Reference
LLVM API Documentation
llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false > Struct Template Reference
Specialization of AnalysisResultModel which provides the default invalidate functionality.
#include <PassManagerInternal.h>
Public Member Functions
AnalysisResultModel (ResultT Result)
AnalysisResultModel (const AnalysisResultModel &Arg)
AnalysisResultModel (AnalysisResultModel &&Arg)
AnalysisResultModel & operator= (AnalysisResultModel RHS)
bool invalidate (IRUnitT &, const PreservedAnalysesT &PA) override
The model bases invalidation solely on being in the preserved set.
Public Member Functions inherited from llvm::detail::AnalysisResultConcept< IRUnitT >
virtual ~AnalysisResultConcept ()
virtual bool invalidate (IRUnitT &IR, const PreservedAnalyses &PA)=0
Method to try and mark a result as invalid.
Public Attributes
ResultT Result
Friends
void swap (AnalysisResultModel &LHS, AnalysisResultModel &RHS)
Detailed Description
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT>
struct llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false >
Specialization of AnalysisResultModel which provides the default invalidate functionality.
Definition at line 185 of file PassManagerInternal.h.
Constructor & Destructor Documentation
AnalysisResultModel() [1/3]
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false >::AnalysisResultModel (ResultT Result) inline explicit
Definition at line 187 of file PassManagerInternal.h.
References Result.
Referenced by AnalysisResultModel(), AnalysisResultModel(), operator=(), and swap.
AnalysisResultModel() [2/3]
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false >::AnalysisResultModel (const AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false > & Arg) inline
Definition at line 190 of file PassManagerInternal.h.
References AnalysisResultModel(), and Result.
AnalysisResultModel() [3/3]
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false >::AnalysisResultModel (AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false > && Arg) inline
Definition at line 191 of file PassManagerInternal.h.
References AnalysisResultModel(), and Result.
Member Function Documentation
invalidate()
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> bool llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false >::invalidate (IRUnitT & , const PreservedAnalysesT & PA) inline override
The model bases invalidation solely on being in the preserved set.
Definition at line 207 of file PassManagerInternal.h.
operator=()
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> AnalysisResultModel & llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false >::operator= (AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false > RHS) inline
Definition at line 197 of file PassManagerInternal.h.
References AnalysisResultModel(), and swap.
Friends And Related Symbol Documentation
swap
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> void swap (AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false > & LHS, AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false > & RHS) friend
Definition at line 193 of file PassManagerInternal.h.
References AnalysisResultModel(), swap, and std::swap().
Referenced by operator=(), and swap.
Member Data Documentation
Result
template<typename IRUnitT, typename PassT, typename ResultT, typename PreservedAnalysesT> ResultT llvm::detail::AnalysisResultModel< IRUnitT, PassT, ResultT, PreservedAnalysesT, false >::Result
Definition at line 211 of file PassManagerInternal.h.
Referenced by AnalysisResultModel(), AnalysisResultModel(), and AnalysisResultModel().
The documentation for this struct was generated from the following file:
PassManagerInternal.h