LLVM: llvm::ELF::Elf64_Rela Struct Reference
LLVM API Documentation
llvm::ELF::Elf64_Rela Struct Reference
#include <ELF.h>
Public Member Functions
Elf64_Word getSymbol () const
Elf64_Word getType () const
void setSymbol (Elf64_Word s)
void setType (Elf64_Word t)
void setSymbolAndType (Elf64_Word s, Elf64_Word t)
Public Attributes
Elf64_Addr r_offset
Elf64_Xword r_info
Elf64_Sxword r_addend
Detailed Description
Definition at line 850 of file Support/ELF.h.
Member Function Documentation
getSymbol()
Elf64_Word llvm::ELF::Elf64_Rela::getSymbol () const inline
Definition at line 857 of file Support/ELF.h.
References r_info.
Referenced by setType().
getType()
Elf64_Word llvm::ELF::Elf64_Rela::getType () const inline
Definition at line 858 of file Support/ELF.h.
References r_info.
Referenced by setSymbol().
setSymbol()
void llvm::ELF::Elf64_Rela::setSymbol (Elf64_Word s) inline
Definition at line 861 of file Support/ELF.h.
References getType(), and setSymbolAndType().
setSymbolAndType()
void llvm::ELF::Elf64_Rela::setSymbolAndType (Elf64_Word s, Elf64_Word t) inline
Definition at line 863 of file Support/ELF.h.
References r_info.
Referenced by setSymbol(), and setType().
setType()
void llvm::ELF::Elf64_Rela::setType (Elf64_Word t) inline
Definition at line 862 of file Support/ELF.h.
References getSymbol(), and setSymbolAndType().
Member Data Documentation
r_addend
Elf64_Sxword llvm::ELF::Elf64_Rela::r_addend
Definition at line 853 of file Support/ELF.h.
r_info
Elf64_Xword llvm::ELF::Elf64_Rela::r_info
Definition at line 852 of file Support/ELF.h.
Referenced by getSymbol(), getType(), and setSymbolAndType().
r_offset
Elf64_Addr llvm::ELF::Elf64_Rela::r_offset
Definition at line 851 of file Support/ELF.h.
The documentation for this struct was generated from the following file:
Support/ELF.h