LLVM: llvm::MDTupleInfo::KeyTy Struct Reference
LLVM API Documentation
llvm::MDTupleInfo::KeyTy Struct Reference
#include <LLVMContextImpl.h>
Public Member Functions
KeyTy (ArrayRef< Metadata * > Ops)
KeyTy (MDTuple *N)
bool operator== (const MDTuple *RHS) const
Static Public Member Functions
template<class T>
static bool compareOps (ArrayRef< T > Ops, const MDTuple *RHS)
Public Attributes
ArrayRef< Metadata * > RawOps
ArrayRef< MDOperand > Ops
unsigned Hash
Detailed Description
Definition at line 174 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
KeyTy() [1/2]
llvm::MDTupleInfo::KeyTy::KeyTy (ArrayRef< Metadata * > Ops) inline
Definition at line 179 of file LLVMContextImpl.h.
References Hash, llvm::hash_combine_range(), Ops, and RawOps.
KeyTy() [2/2]
llvm::MDTupleInfo::KeyTy::KeyTy (MDTuple * N) inline
Definition at line 182 of file LLVMContextImpl.h.
References getHash(), Hash, N, and Ops.
Member Function Documentation
compareOps()
template<class T> bool llvm::MDTupleInfo::KeyTy::compareOps (ArrayRef< T > Ops, const MDTuple * RHS) inline static
Definition at line 194 of file LLVMContextImpl.h.
References llvm::MDNode::getNumOperands(), llvm::MDNode::op_begin(), and Ops.
Referenced by operator==().
operator==()
bool llvm::MDTupleInfo::KeyTy::operator== (const MDTuple * RHS) const inline
Definition at line 185 of file LLVMContextImpl.h.
References compareOps(), llvm::MDTupleInfo::getEmptyKey(), llvm::MDTuple::getHash(), llvm::MDTupleInfo::getTombstoneKey(), Hash, Ops, and RawOps.
Member Data Documentation
Hash
unsigned llvm::MDTupleInfo::KeyTy::Hash
Definition at line 177 of file LLVMContextImpl.h.
Referenced by llvm::MDTupleInfo::getHashValue(), KeyTy(), KeyTy(), and operator==().
Ops
ArrayRef<MDOperand> llvm::MDTupleInfo::KeyTy::Ops
Definition at line 176 of file LLVMContextImpl.h.
Referenced by compareOps(), KeyTy(), KeyTy(), and operator==().
RawOps
ArrayRef<Metadata *> llvm::MDTupleInfo::KeyTy::RawOps
Definition at line 175 of file LLVMContextImpl.h.
Referenced by KeyTy(), and operator==().
The documentation for this struct was generated from the following file:
LLVMContextImpl.h