LLVM: llvm::DOTGraphTraits< RegionInfoPass * > Struct Reference
LLVM API Documentation
llvm::DOTGraphTraits< RegionInfoPass * > Struct Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (RegionNode *Node, RegionInfoPass *G)
std::string getEdgeAttributes (RegionNode *srcNode, GraphTraits< RegionInfo * >::ChildIteratorType CI, RegionInfoPass *G)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType>
std::string getNodeLabel (const void *, const GraphType &)
Public Member Functions inherited from llvm::DOTGraphTraits< RegionNode * >
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (RegionNode *Node, RegionNode *Graph)
Static Public Member Functions
static std::string getGraphName (RegionInfoPass *DT)
static void printRegionCluster (const Region &R, GraphWriter< RegionInfoPass * > &GW, unsigned depth=0)
static void addCustomGraphFeatures (const RegionInfoPass *RIP, GraphWriter< RegionInfoPass * > &GW)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType>
static std::string getGraphName (const GraphType &)
template<typename GraphType>
static std::string getGraphProperties (const GraphType &)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const void *)
template<typename GraphType>
static bool hasNodeAddressLabel (const void *, const GraphType &)
template<typename GraphType>
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType>
static std::string getNodeAttributes (const void *, const GraphType &)
template<typename EdgeIter, typename GraphType>
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
template<typename EdgeIter>
static std::string getEdgeSourceLabel (const void *, EdgeIter)
template<typename EdgeIter>
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
template<typename EdgeIter>
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
static bool hasEdgeDestLabels ()
static unsigned numEdgeDestLabels (const void *)
static std::string getEdgeDestLabel (const void *, unsigned)
template<typename GraphType, typename GraphWriter>
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
Definition at line 59 of file RegionPrinter.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< RegionInfoPass * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 61 of file RegionPrinter.cpp.
References DOTGraphTraits(), and llvm::DefaultDOTGraphTraits::isSimple().
Referenced by DOTGraphTraits().
Member Function Documentation
addCustomGraphFeatures()
void llvm::DOTGraphTraits< RegionInfoPass * >::addCustomGraphFeatures (const RegionInfoPass * RIP, GraphWriter< RegionInfoPass * > & GW) inline static
Definition at line 135 of file RegionPrinter.cpp.
References llvm::GraphWriter< GraphType >::getOStream(), llvm::RegionInfoPass::getRegionInfo(), llvm::RegionInfoBase< Tr >::getTopLevelRegion(), and printRegionCluster().
getEdgeAttributes()
std::string llvm::DOTGraphTraits< RegionInfoPass * >::getEdgeAttributes (RegionNode * srcNode, GraphTraits< RegionInfo * >::ChildIteratorType CI, RegionInfoPass * G) inline
Definition at line 74 of file RegionPrinter.cpp.
References G, llvm::RegionNodeBase< Tr >::getNodeAs(), llvm::RegionInfoBase< Tr >::getRegionFor(), and llvm::RegionNodeBase< Tr >::isSubRegion().
getGraphName()
std::string llvm::DOTGraphTraits< RegionInfoPass * >::getGraphName (RegionInfoPass * DT) inline static
Definition at line 64 of file RegionPrinter.cpp.
getNodeLabel()
std::string llvm::DOTGraphTraits< RegionInfoPass * >::getNodeLabel (RegionNode * Node, RegionInfoPass * G) inline
Definition at line 68 of file RegionPrinter.cpp.
References G, llvm::DefaultDOTGraphTraits::getNodeLabel(), and llvm::RegionInfoBase< Tr >::getTopLevelRegion().
printRegionCluster()
void llvm::DOTGraphTraits< RegionInfoPass * >::printRegionCluster (const Region & R, GraphWriter< RegionInfoPass * > & GW, unsigned depth = 0) inline static
Definition at line 102 of file RegionPrinter.cpp.
References llvm::RegionBase< Tr >::begin(), llvm::RegionBase< Tr >::blocks(), llvm::RegionBase< Tr >::end(), llvm::RegionBase< Tr >::getDepth(), llvm::GraphWriter< GraphType >::getOStream(), llvm::RegionInfoBase< Tr >::getRegionFor(), llvm::RegionBase< Tr >::getRegionInfo(), llvm::RegionInfoBase< Tr >::getTopLevelRegion(), llvm::raw_ostream::indent(), llvm::RegionBase< Tr >::isSimple(), onlySimpleRegions, and printRegionCluster().
Referenced by addCustomGraphFeatures(), and printRegionCluster().
The documentation for this struct was generated from the following file:
RegionPrinter.cpp