LLVM: llvm::AnonStructTypeKeyInfo::KeyTy Struct Reference
LLVM API Documentation
llvm::AnonStructTypeKeyInfo::KeyTy Struct Reference
#include <LLVMContextImpl.h>
Public Member Functions
KeyTy (const ArrayRef< Type * > &E, bool P)
KeyTy (const StructType *ST)
bool operator== (const KeyTy &that) const
bool operator!= (const KeyTy &that) const
Public Attributes
ArrayRef< Type * > ETypes
bool isPacked
Detailed Description
Definition at line 79 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
KeyTy() [1/2]
llvm::AnonStructTypeKeyInfo::KeyTy::KeyTy (const ArrayRef< Type * > & E, bool P) inline
Definition at line 82 of file LLVMContextImpl.h.
References ETypes, isPacked, and P.
Referenced by operator!=(), and operator==().
KeyTy() [2/2]
llvm::AnonStructTypeKeyInfo::KeyTy::KeyTy (const StructType * ST) inline
Definition at line 84 of file LLVMContextImpl.h.
References ETypes, and isPacked.
Member Function Documentation
operator!=()
bool llvm::AnonStructTypeKeyInfo::KeyTy::operator!= (const KeyTy & that) const inline
Definition at line 93 of file LLVMContextImpl.h.
References KeyTy(), and operator==().
operator==()
bool llvm::AnonStructTypeKeyInfo::KeyTy::operator== (const KeyTy & that) const inline
Definition at line 86 of file LLVMContextImpl.h.
References ETypes, isPacked, and KeyTy().
Referenced by operator!=().
Member Data Documentation
ETypes
ArrayRef<Type*> llvm::AnonStructTypeKeyInfo::KeyTy::ETypes
Definition at line 80 of file LLVMContextImpl.h.
Referenced by llvm::AnonStructTypeKeyInfo::getHashValue(), KeyTy(), KeyTy(), and operator==().
isPacked
bool llvm::AnonStructTypeKeyInfo::KeyTy::isPacked
Definition at line 81 of file LLVMContextImpl.h.
Referenced by llvm::AnonStructTypeKeyInfo::getHashValue(), KeyTy(), KeyTy(), and operator==().
The documentation for this struct was generated from the following file:
LLVMContextImpl.h