LLVM: llvm::GraphTraits< RegionInfo * > Struct Reference
LLVM API Documentation
llvm::GraphTraits< RegionInfo * > Struct Reference
#include <RegionIterator.h>
Public Types
typedef df_iterator< NodeType *, SmallPtrSet< NodeType *, 8 >, false, GraphTraits< FlatIt< NodeType * > > > nodes_iterator
typedef RegionInfo *::UnknownGraphTypeError NodeType
Public Types inherited from llvm::GraphTraits< FlatIt< RegionNode * > >
typedef FlatIt< RegionNode * >::UnknownGraphTypeError NodeType
Static Public Member Functions
static NodeType * getEntryNode (RegionInfo *RI)
static nodes_iterator nodes_begin (RegionInfo *RI)
static nodes_iterator nodes_end (RegionInfo *RI)
Detailed Description
Definition at line 331 of file RegionIterator.h.
Member Typedef Documentation
nodes_iterator
typedef df_iterator<NodeType*, SmallPtrSet<NodeType*, 8>, false, GraphTraits<FlatIt<NodeType*> > > llvm::GraphTraits< RegionInfo * >::nodes_iterator
Definition at line 334 of file RegionIterator.h.
NodeType
typedef RegionInfo *::UnknownGraphTypeError llvm::GraphTraits< RegionInfo * >::NodeType
Definition at line 60 of file GraphTraits.h.
Member Function Documentation
getEntryNode()
NodeType * llvm::GraphTraits< RegionInfo * >::getEntryNode (RegionInfo * RI) inline static
Definition at line 336 of file RegionIterator.h.
References getEntryNode(), and llvm::RegionInfoBase< Tr >::getTopLevelRegion().
Referenced by getEntryNode(), nodes_begin(), and nodes_end().
nodes_begin()
nodes_iterator llvm::GraphTraits< RegionInfo * >::nodes_begin (RegionInfo * RI) inline static
Definition at line 339 of file RegionIterator.h.
References llvm::df_iterator< NodeType *, SmallPtrSet< NodeType *, 8 >, false, GraphTraits< FlatIt< NodeType * > > >::begin(), and getEntryNode().
nodes_end()
nodes_iterator llvm::GraphTraits< RegionInfo * >::nodes_end (RegionInfo * RI) inline static
Definition at line 342 of file RegionIterator.h.
References llvm::df_iterator< NodeType *, SmallPtrSet< NodeType *, 8 >, false, GraphTraits< FlatIt< NodeType * > > >::end(), and getEntryNode().
The documentation for this struct was generated from the following file:
RegionIterator.h