LLVM: llvm::Linker::StructTypeKeyInfo::KeyTy Struct Reference
LLVM API Documentation
llvm::Linker::StructTypeKeyInfo::KeyTy Struct Reference
#include <Linker.h>
Public Member Functions
KeyTy (ArrayRef< Type * > E, bool P)
KeyTy (const StructType *ST)
bool operator== (const KeyTy &that) const
bool operator!= (const KeyTy &that) const
Public Attributes
ArrayRef< Type * > ETypes
bool IsPacked
Detailed Description
Definition at line 30 of file llvm/Linker/Linker.h.
Constructor & Destructor Documentation
KeyTy() [1/2]
Linker::StructTypeKeyInfo::KeyTy::KeyTy (ArrayRef< Type * > E, bool P)
Definition at line 1607 of file LinkModules.cpp.
References ETypes, IsPacked, and P.
Referenced by operator!=(), and operator==().
KeyTy() [2/2]
Linker::StructTypeKeyInfo::KeyTy::KeyTy (const StructType * ST)
Definition at line 1610 of file LinkModules.cpp.
References ETypes, and IsPacked.
Member Function Documentation
operator!=()
bool Linker::StructTypeKeyInfo::KeyTy::operator!= (const KeyTy & that) const
Definition at line 1621 of file LinkModules.cpp.
References KeyTy(), and llvm::operator==().
operator==()
bool Linker::StructTypeKeyInfo::KeyTy::operator== (const KeyTy & that) const
Definition at line 1613 of file LinkModules.cpp.
References ETypes, IsPacked, and KeyTy().
Member Data Documentation
ETypes
ArrayRef<Type *> llvm::Linker::StructTypeKeyInfo::KeyTy::ETypes
Definition at line 31 of file llvm/Linker/Linker.h.
Referenced by llvm::Linker::StructTypeKeyInfo::getHashValue(), KeyTy(), KeyTy(), and operator==().
IsPacked
bool llvm::Linker::StructTypeKeyInfo::KeyTy::IsPacked
Definition at line 32 of file llvm/Linker/Linker.h.
Referenced by llvm::Linker::StructTypeKeyInfo::getHashValue(), KeyTy(), KeyTy(), and operator==().
The documentation for this struct was generated from the following files:
llvm/Linker/Linker.h
LinkModules.cpp