LLVM: llvm::ELF::Elf64_Rel Struct Reference
LLVM API Documentation
llvm::ELF::Elf64_Rel Struct Reference
#include <ELF.h>
Public Member Functions
Elf64_Word getSymbol () const
Elf64_Word getType () const
void setSymbol (Elf64_Word s)
void setType (Elf64_Word t)
void setSymbolAndType (Elf64_Word s, Elf64_Word t)
Public Attributes
Elf64_Addr r_offset
Elf64_Xword r_info
Detailed Description
Definition at line 832 of file Support/ELF.h.
Member Function Documentation
getSymbol()
Elf64_Word llvm::ELF::Elf64_Rel::getSymbol () const inline
Definition at line 838 of file Support/ELF.h.
References r_info.
Referenced by setType().
getType()
Elf64_Word llvm::ELF::Elf64_Rel::getType () const inline
Definition at line 839 of file Support/ELF.h.
References r_info.
Referenced by setSymbol().
setSymbol()
void llvm::ELF::Elf64_Rel::setSymbol (Elf64_Word s) inline
Definition at line 842 of file Support/ELF.h.
References getType(), and setSymbolAndType().
setSymbolAndType()
void llvm::ELF::Elf64_Rel::setSymbolAndType (Elf64_Word s, Elf64_Word t) inline
Definition at line 844 of file Support/ELF.h.
References r_info.
Referenced by setSymbol(), and setType().
setType()
void llvm::ELF::Elf64_Rel::setType (Elf64_Word t) inline
Definition at line 843 of file Support/ELF.h.
References getSymbol(), and setSymbolAndType().
Member Data Documentation
r_info
Elf64_Xword llvm::ELF::Elf64_Rel::r_info
Definition at line 834 of file Support/ELF.h.
Referenced by getSymbol(), getType(), and setSymbolAndType().
r_offset
Elf64_Addr llvm::ELF::Elf64_Rel::r_offset
Definition at line 833 of file Support/ELF.h.
The documentation for this struct was generated from the following file:
Support/ELF.h