LLVM: llvm::LTOCodeGenerator Struct Reference
LLVM API Documentation
llvm::LTOCodeGenerator Struct Reference
#include <LTOCodeGenerator.h>
Public Member Functions
LTOCodeGenerator ()
LTOCodeGenerator (std::unique_ptr< LLVMContext > Context)
~LTOCodeGenerator ()
bool addModule (struct LTOModule *)
void setTargetOptions (TargetOptions options)
void setDebugInfo (lto_debug_model)
void setCodePICModel (lto_codegen_model)
void setCpu (const char *mCpu)
void setAttr (const char *mAttr)
void addMustPreserveSymbol (const char *sym)
void setCodeGenDebugOptions (const char *opts)
void parseCodeGenDebugOptions ()
bool writeMergedModules (const char *path, std::string &errMsg)
bool compile_to_file (const char **name, bool disableOpt, bool disableInline, bool disableGVNLoadPRE, bool disableVectorization, std::string &errMsg)
const void * compile (size_t *length, bool disableOpt, bool disableInline, bool disableGVNLoadPRE, bool disableVectorization, std::string &errMsg)
void setDiagnosticHandler (lto_diagnostic_handler_t, void *)
LLVMContext & getContext ()
Static Public Member Functions
static const char * getVersionString ()
Detailed Description
C++ class which implements the opaque lto_code_gen_t type.
Definition at line 60 of file LTOCodeGenerator.h.
Constructor & Destructor Documentation
LTOCodeGenerator() [1/2]
LTOCodeGenerator::LTOCodeGenerator ()
Definition at line 66 of file LTOCodeGenerator.cpp.
References llvm::getGlobalContext().
LTOCodeGenerator() [2/2]
LTOCodeGenerator::LTOCodeGenerator (std::unique_ptr< LLVMContext > Context)
Definition at line 71 of file LTOCodeGenerator.cpp.
~LTOCodeGenerator()
LTOCodeGenerator::~LTOCodeGenerator ()
Definition at line 88 of file LTOCodeGenerator.cpp.
References I.
Member Function Documentation
addModule()
bool LTOCodeGenerator::addModule (struct LTOModule * mod)
Definition at line 130 of file LTOCodeGenerator.cpp.
References llvm::LTOModule::getAsmUndefinedRefs(), llvm::Module::getContext(), and llvm::LTOModule::getModule().
addMustPreserveSymbol()
void llvm::LTOCodeGenerator::addMustPreserveSymbol (const char * sym) inline
Definition at line 77 of file LTOCodeGenerator.h.
compile()
const void * LTOCodeGenerator::compile (size_t * length, bool disableOpt, bool disableInline, bool disableGVNLoadPRE, bool disableVectorization, std::string & errMsg)
Definition at line 244 of file LTOCodeGenerator.cpp.
References compile_to_file(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFile(), and llvm::sys::fs::remove().
compile_to_file()
bool LTOCodeGenerator::compile_to_file (const char ** name, bool disableOpt, bool disableInline, bool disableGVNLoadPRE, bool disableVectorization, std::string & errMsg)
Definition at line 204 of file LTOCodeGenerator.cpp.
References llvm::SmallString< InternalLen >::c_str(), llvm::raw_fd_ostream::clear_error(), llvm::raw_fd_ostream::close(), llvm::sys::fs::createTemporaryFile(), llvm::raw_fd_ostream::has_error(), llvm::tool_output_file::keep(), llvm::tool_output_file::os(), and llvm::sys::fs::remove().
Referenced by compile().
getContext()
LLVMContext & llvm::LTOCodeGenerator::getContext () inline
Definition at line 122 of file LTOCodeGenerator.h.
getVersionString()
const char * LTOCodeGenerator::getVersionString () static
Definition at line 58 of file LTOCodeGenerator.cpp.
parseCodeGenDebugOptions()
void LTOCodeGenerator::parseCodeGenDebugOptions ()
Definition at line 533 of file LTOCodeGenerator.cpp.
References llvm::cl::ParseCommandLineOptions().
setAttr()
void llvm::LTOCodeGenerator::setAttr (const char * mAttr) inline
Definition at line 75 of file LTOCodeGenerator.h.
setCodeGenDebugOptions()
void LTOCodeGenerator::setCodeGenDebugOptions (const char * options)
setCodeGenDebugOptions - Set codegen debugging options to aid in debugging LTO problems.
Definition at line 522 of file LTOCodeGenerator.cpp.
References llvm::getToken().
setCodePICModel()
void LTOCodeGenerator::setCodePICModel (lto_codegen_model model)
Definition at line 160 of file LTOCodeGenerator.cpp.
References llvm_unreachable, LTO_CODEGEN_PIC_MODEL_DEFAULT, LTO_CODEGEN_PIC_MODEL_DYNAMIC, LTO_CODEGEN_PIC_MODEL_DYNAMIC_NO_PIC, and LTO_CODEGEN_PIC_MODEL_STATIC.
setCpu()
void llvm::LTOCodeGenerator::setCpu (const char * mCpu) inline
Definition at line 74 of file LTOCodeGenerator.h.
setDebugInfo()
void LTOCodeGenerator::setDebugInfo (lto_debug_model debug)
Definition at line 147 of file LTOCodeGenerator.cpp.
References debug, llvm_unreachable, LTO_DEBUG_MODEL_DWARF, and LTO_DEBUG_MODEL_NONE.
setDiagnosticHandler()
void LTOCodeGenerator::setDiagnosticHandler (lto_diagnostic_handler_t DiagHandler, void * Ctxt)
Definition at line 576 of file LTOCodeGenerator.cpp.
setTargetOptions()
void LTOCodeGenerator::setTargetOptions (TargetOptions options)
Definition at line 143 of file LTOCodeGenerator.cpp.
writeMergedModules()
bool LTOCodeGenerator::writeMergedModules (const char * path, std::string & errMsg)
Definition at line 172 of file LTOCodeGenerator.cpp.
References llvm::raw_fd_ostream::clear_error(), llvm::raw_fd_ostream::close(), llvm::sys::fs::F_None, llvm::raw_fd_ostream::has_error(), llvm::tool_output_file::keep(), llvm::tool_output_file::os(), and llvm::WriteBitcodeToFile().
The documentation for this struct was generated from the following files:
LTOCodeGenerator.h
LTOCodeGenerator.cpp