LLVM: llvm::MachineFunctionAnalysis Struct Reference
LLVM API Documentation
llvm::MachineFunctionAnalysis Struct Reference
#include <MachineFunctionAnalysis.h>
Public Member Functions
MachineFunctionAnalysis (const TargetMachine &tm)
~MachineFunctionAnalysis ()
MachineFunction & getMF () const
const char * getPassName () const override
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType>
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType>
AnalysisType & getAnalysis () const
template<typename AnalysisType>
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType>
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipOptnoneFunction (const Function &F) const
Detailed Description
MachineFunctionAnalysis - This class is a Pass that manages a MachineFunction object.
Definition at line 26 of file MachineFunctionAnalysis.h.
Constructor & Destructor Documentation
MachineFunctionAnalysis()
MachineFunctionAnalysis::MachineFunctionAnalysis (const TargetMachine & tm) explicit
Definition at line 22 of file MachineFunctionAnalysis.cpp.
References llvm::FunctionPass::FunctionPass(), llvm::PassRegistry::getPassRegistry(), ID, and llvm::initializeMachineModuleInfoPass().
~MachineFunctionAnalysis()
MachineFunctionAnalysis::~MachineFunctionAnalysis ()
Definition at line 27 of file MachineFunctionAnalysis.cpp.
References llvm::Pass::releaseMemory().
Member Function Documentation
getMF()
MachineFunction & llvm::MachineFunctionAnalysis::getMF () const inline
Definition at line 36 of file MachineFunctionAnalysis.h.
getPassName()
const char * llvm::MachineFunctionAnalysis::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 38 of file MachineFunctionAnalysis.h.
Member Data Documentation
ID
char MachineFunctionAnalysis::ID = 0 static
Definition at line 32 of file MachineFunctionAnalysis.h.
Referenced by MachineFunctionAnalysis().
The documentation for this struct was generated from the following files:
MachineFunctionAnalysis.h
MachineFunctionAnalysis.cpp