LLVM: llvm::TargetLowering::CallLoweringInfo Struct Reference
LLVM API Documentation
llvm::TargetLowering::CallLoweringInfo Struct Reference
#include <TargetLowering.h>
Public Member Functions
CallLoweringInfo (SelectionDAG &DAG)
CallLoweringInfo & setDebugLoc (SDLoc dl)
CallLoweringInfo & setChain (SDValue InChain)
CallLoweringInfo & setCallee (CallingConv::ID CC, Type *ResultType, SDValue Target, ArgListTy &&ArgsList, unsigned FixedArgs=-1)
CallLoweringInfo & setCallee (Type *ResultType, FunctionType *FTy, SDValue Target, ArgListTy &&ArgsList, ImmutableCallSite &Call)
CallLoweringInfo & setInRegister (bool Value=true)
CallLoweringInfo & setNoReturn (bool Value=true)
CallLoweringInfo & setVarArg (bool Value=true)
CallLoweringInfo & setTailCall (bool Value=true)
CallLoweringInfo & setDiscardResult (bool Value=true)
CallLoweringInfo & setSExtResult (bool Value=true)
CallLoweringInfo & setZExtResult (bool Value=true)
CallLoweringInfo & setIsPatchPoint (bool Value=true)
ArgListTy & getArgs ()
Public Attributes
SDValue Chain
Type * RetTy
bool RetSExt: 1
bool RetZExt: 1
bool IsVarArg: 1
bool IsInReg: 1
bool DoesNotReturn: 1
bool IsReturnValueUsed: 1
bool IsTailCall
unsigned NumFixedArgs
CallingConv::ID CallConv
SDValue Callee
ArgListTy Args
SelectionDAG & DAG
SDLoc DL
ImmutableCallSite * CS
bool IsPatchPoint
SmallVector< ISD::OutputArg, 32 > Outs
SmallVector< SDValue, 32 > OutVals
SmallVector< ISD::InputArg, 32 > Ins
Detailed Description
This structure contains all information that is necessary for lowering calls. It is passed to TLI::LowerCallTo when the SelectionDAG builder needs to lower a call, and targets will see this struct in their LowerCall implementation.
Definition at line 2293 of file TargetLowering.h.
Constructor & Destructor Documentation
CallLoweringInfo()
llvm::TargetLowering::CallLoweringInfo::CallLoweringInfo (SelectionDAG & DAG) inline
Definition at line 2319 of file TargetLowering.h.
References CallConv, CS, DAG, DoesNotReturn, IsInReg, IsPatchPoint, IsReturnValueUsed, IsTailCall, IsVarArg, NumFixedArgs, RetSExt, RetTy, RetZExt, and true.
Referenced by setCallee(), setCallee(), setChain(), setDebugLoc(), setDiscardResult(), setInRegister(), setIsPatchPoint(), setNoReturn(), setSExtResult(), setTailCall(), setVarArg(), and setZExtResult().
Member Function Documentation
getArgs()
ArgListTy & llvm::TargetLowering::CallLoweringInfo::getArgs () inline
Definition at line 2410 of file TargetLowering.h.
References Args.
Referenced by llvm::NVPTXTargetLowering::LowerCall(), and llvm::TargetLowering::LowerCallTo().
setCallee() [1/2]
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setCallee (CallingConv::ID CC, Type * ResultType, SDValue Target, ArgListTy && ArgsList, unsigned FixedArgs = -1) inline
Definition at line 2335 of file TargetLowering.h.
References Args, CallConv, Callee, CallLoweringInfo(), NumFixedArgs, and RetTy.
Referenced by llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAGBuilder::lowerCallOperands(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerFSINCOS(), and llvm::TargetLowering::makeLibCall().
setCallee() [2/2]
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setCallee (Type * ResultType, FunctionType * FTy, SDValue Target, ArgListTy && ArgsList, ImmutableCallSite & Call) inline
Definition at line 2347 of file TargetLowering.h.
References Args, llvm::Call, CallConv, Callee, CallLoweringInfo(), CS, DoesNotReturn, llvm::FunctionType::getNumParams(), llvm::Attribute::InReg, IsInReg, IsReturnValueUsed, IsVarArg, llvm::FunctionType::isVarArg(), NumFixedArgs, RetSExt, RetTy, RetZExt, llvm::Attribute::SExt, and llvm::Attribute::ZExt.
setChain()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setChain (SDValue InChain) inline
Definition at line 2330 of file TargetLowering.h.
References CallLoweringInfo(), and Chain.
Referenced by llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAGBuilder::lowerCallOperands(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerFSINCOS(), and llvm::TargetLowering::makeLibCall().
setDebugLoc()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setDebugLoc (SDLoc dl) inline
Definition at line 2325 of file TargetLowering.h.
References CallLoweringInfo(), and DL.
Referenced by llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAGBuilder::lowerCallOperands(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), LowerFSINCOS(), and llvm::TargetLowering::makeLibCall().
setDiscardResult()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setDiscardResult (bool Value = true) inline
Definition at line 2390 of file TargetLowering.h.
References CallLoweringInfo(), and IsReturnValueUsed.
Referenced by llvm::XCoreSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAGBuilder::lowerCallOperands(), and llvm::TargetLowering::makeLibCall().
setInRegister()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setInRegister (bool Value = true) inline
Definition at line 2370 of file TargetLowering.h.
References CallLoweringInfo(), and IsInReg.
setIsPatchPoint()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setIsPatchPoint (bool Value = true) inline
Definition at line 2405 of file TargetLowering.h.
References CallLoweringInfo(), and IsPatchPoint.
Referenced by llvm::SelectionDAGBuilder::lowerCallOperands().
setNoReturn()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setNoReturn (bool Value = true) inline
Definition at line 2375 of file TargetLowering.h.
References CallLoweringInfo(), and DoesNotReturn.
Referenced by llvm::TargetLowering::makeLibCall().
setSExtResult()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setSExtResult (bool Value = true) inline
Definition at line 2395 of file TargetLowering.h.
References CallLoweringInfo(), and RetSExt.
Referenced by llvm::TargetLowering::makeLibCall().
setTailCall()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setTailCall (bool Value = true) inline
Definition at line 2385 of file TargetLowering.h.
References CallLoweringInfo(), and IsTailCall.
Referenced by llvm::SelectionDAGBuilder::LowerCallTo().
setVarArg()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setVarArg (bool Value = true) inline
Definition at line 2380 of file TargetLowering.h.
References CallLoweringInfo(), and IsVarArg.
setZExtResult()
CallLoweringInfo & llvm::TargetLowering::CallLoweringInfo::setZExtResult (bool Value = true) inline
Definition at line 2400 of file TargetLowering.h.
References CallLoweringInfo(), and RetZExt.
Referenced by llvm::TargetLowering::makeLibCall().
Member Data Documentation
Args
ArgListTy llvm::TargetLowering::CallLoweringInfo::Args
Definition at line 2310 of file TargetLowering.h.
Referenced by getArgs(), setCallee(), and setCallee().
CallConv
CallingConv::ID llvm::TargetLowering::CallLoweringInfo::CallConv
Definition at line 2308 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setCallee().
Callee
SDValue llvm::TargetLowering::CallLoweringInfo::Callee
Definition at line 2309 of file TargetLowering.h.
Referenced by llvm::MipsTargetLowering::getOpndList(), llvm::AMDGPUTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), setCallee(), and setCallee().
Chain
SDValue llvm::TargetLowering::CallLoweringInfo::Chain
Definition at line 2294 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and setChain().
CS
ImmutableCallSite* llvm::TargetLowering::CallLoweringInfo::CS
Definition at line 2313 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and setCallee().
DAG
SelectionDAG& llvm::TargetLowering::CallLoweringInfo::DAG
Definition at line 2311 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::MipsTargetLowering::getOpndList(), llvm::AMDGPUTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::TargetLowering::LowerCallTo().
DL
SDLoc llvm::TargetLowering::CallLoweringInfo::DL
Definition at line 2312 of file TargetLowering.h.
Referenced by llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and setDebugLoc().
DoesNotReturn
bool llvm::TargetLowering::CallLoweringInfo::DoesNotReturn
Definition at line 2300 of file TargetLowering.h.
Referenced by CallLoweringInfo(), setCallee(), and setNoReturn().
Ins
SmallVector<ISD::InputArg, 32> llvm::TargetLowering::CallLoweringInfo::Ins
Definition at line 2317 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::TargetLowering::LowerCallTo().
IsInReg
bool llvm::TargetLowering::CallLoweringInfo::IsInReg
Definition at line 2299 of file TargetLowering.h.
Referenced by CallLoweringInfo(), getReturnAttrs(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setInRegister().
IsPatchPoint
bool llvm::TargetLowering::CallLoweringInfo::IsPatchPoint
Definition at line 2314 of file TargetLowering.h.
Referenced by CallLoweringInfo(), and setIsPatchPoint().
IsReturnValueUsed
bool llvm::TargetLowering::CallLoweringInfo::IsReturnValueUsed
Definition at line 2301 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setDiscardResult().
IsTailCall
bool llvm::TargetLowering::CallLoweringInfo::IsTailCall
Definition at line 2305 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), and setTailCall().
IsVarArg
bool llvm::TargetLowering::CallLoweringInfo::IsVarArg
Definition at line 2298 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::HexagonTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setVarArg().
NumFixedArgs
unsigned llvm::TargetLowering::CallLoweringInfo::NumFixedArgs
Definition at line 2307 of file TargetLowering.h.
Referenced by CallLoweringInfo(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setCallee().
Outs
SmallVector<ISD::OutputArg, 32> llvm::TargetLowering::CallLoweringInfo::Outs
Definition at line 2315 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::TargetLowering::LowerCallTo().
OutVals
SmallVector<SDValue, 32> llvm::TargetLowering::CallLoweringInfo::OutVals
Definition at line 2316 of file TargetLowering.h.
Referenced by llvm::HexagonTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::TargetLowering::LowerCallTo().
RetSExt
bool llvm::TargetLowering::CallLoweringInfo::RetSExt
Definition at line 2296 of file TargetLowering.h.
Referenced by CallLoweringInfo(), getReturnAttrs(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setSExtResult().
RetTy
Type* llvm::TargetLowering::CallLoweringInfo::RetTy
Definition at line 2295 of file TargetLowering.h.
Referenced by CallLoweringInfo(), getReturnAttrs(), llvm::NVPTXTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setCallee().
RetZExt
bool llvm::TargetLowering::CallLoweringInfo::RetZExt
Definition at line 2297 of file TargetLowering.h.
Referenced by CallLoweringInfo(), getReturnAttrs(), llvm::TargetLowering::LowerCallTo(), setCallee(), and setZExtResult().
The documentation for this struct was generated from the following file:
TargetLowering.h