LLVM: llvm::coverage::CounterMappingRegion Struct Reference
LLVM API Documentation
llvm::coverage::CounterMappingRegion Struct Reference
A Counter mapping region associates a source range with a specific counter.
#include <CoverageMapping.h>
Public Types
enum RegionKind { CodeRegion , ExpansionRegion , SkippedRegion }
Public Member Functions
CounterMappingRegion (Counter Count, unsigned FileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd, bool HasCodeBefore=false, RegionKind Kind=CodeRegion)
std::pair< unsigned, unsigned > startLoc () const
std::pair< unsigned, unsigned > endLoc () const
bool operator< (const CounterMappingRegion &Other) const
bool contains (const CounterMappingRegion &Other) const
Public Attributes
Counter Count
unsigned FileID
unsigned ExpandedFileID
unsigned LineStart
unsigned ColumnStart
unsigned LineEnd
unsigned ColumnEnd
RegionKind Kind
bool HasCodeBefore
A flag that is set to true when there is already code before this region on the same line. This is useful to accurately compute the execution counts for a line.
Static Public Attributes
static const unsigned EncodingHasCodeBeforeBits = 1
Detailed Description
A Counter mapping region associates a source range with a specific counter.
Definition at line 141 of file CoverageMapping.h.
Member Enumeration Documentation
RegionKind
enum llvm::coverage::CounterMappingRegion::RegionKind
Enumerator
CodeRegion
A CodeRegion associates some code with a counter.
ExpansionRegion
An ExpansionRegion represents a file expansion region that associates a source range with the expansion of a virtual source file, such as for a macro instantiation or #include file.
SkippedRegion
A SkippedRegion represents a source range with code that was skipped by a preprocessor or similar means.
Definition at line 142 of file CoverageMapping.h.
Constructor & Destructor Documentation
CounterMappingRegion()
llvm::coverage::CounterMappingRegion::CounterMappingRegion (Counter Count, unsigned FileID, unsigned LineStart, unsigned ColumnStart, unsigned LineEnd, unsigned ColumnEnd, bool HasCodeBefore = false, RegionKind Kind = CodeRegion) inline
Definition at line 167 of file CoverageMapping.h.
References CodeRegion, ColumnEnd, ColumnStart, Count, ExpandedFileID, FileID, HasCodeBefore, Kind, LineEnd, and LineStart.
Referenced by contains(), llvm::coverage::CountedRegion::CountedRegion(), and operator<().
Member Function Documentation
contains()
bool llvm::coverage::CounterMappingRegion::contains (const CounterMappingRegion & Other) const inline
Definition at line 189 of file CoverageMapping.h.
References CounterMappingRegion(), endLoc(), FileID, and startLoc().
endLoc()
std::pair< unsigned, unsigned > llvm::coverage::CounterMappingRegion::endLoc () const inline
Definition at line 179 of file CoverageMapping.h.
References ColumnEnd, and LineEnd.
Referenced by contains(), and sortNestedRegions().
operator<()
bool llvm::coverage::CounterMappingRegion::operator< (const CounterMappingRegion & Other) const inline
Definition at line 183 of file CoverageMapping.h.
References CounterMappingRegion(), FileID, and startLoc().
startLoc()
std::pair< unsigned, unsigned > llvm::coverage::CounterMappingRegion::startLoc () const inline
Definition at line 175 of file CoverageMapping.h.
References ColumnStart, and LineStart.
Referenced by contains(), operator<(), and sortNestedRegions().
Member Data Documentation
ColumnEnd
unsigned llvm::coverage::CounterMappingRegion::ColumnEnd
Definition at line 160 of file CoverageMapping.h.
Referenced by CounterMappingRegion(), and endLoc().
ColumnStart
unsigned llvm::coverage::CounterMappingRegion::ColumnStart
Definition at line 160 of file CoverageMapping.h.
Referenced by CounterMappingRegion(), and startLoc().
Count
Counter llvm::coverage::CounterMappingRegion::Count
Definition at line 158 of file CoverageMapping.h.
Referenced by CounterMappingRegion().
EncodingHasCodeBeforeBits
const unsigned llvm::coverage::CounterMappingRegion::EncodingHasCodeBeforeBits = 1 static
Definition at line 156 of file CoverageMapping.h.
Referenced by llvm::coverage::CoverageMappingWriter::write().
ExpandedFileID
unsigned llvm::coverage::CounterMappingRegion::ExpandedFileID
Definition at line 159 of file CoverageMapping.h.
Referenced by CounterMappingRegion().
FileID
unsigned llvm::coverage::CounterMappingRegion::FileID
Definition at line 159 of file CoverageMapping.h.
Referenced by contains(), CounterMappingRegion(), isExpansion(), and operator<().
HasCodeBefore
bool llvm::coverage::CounterMappingRegion::HasCodeBefore
A flag that is set to true when there is already code before this region on the same line. This is useful to accurately compute the execution counts for a line.
Definition at line 165 of file CoverageMapping.h.
Referenced by CounterMappingRegion().
Kind
RegionKind llvm::coverage::CounterMappingRegion::Kind
Definition at line 161 of file CoverageMapping.h.
Referenced by CounterMappingRegion(), and isExpansion().
LineEnd
unsigned llvm::coverage::CounterMappingRegion::LineEnd
Definition at line 160 of file CoverageMapping.h.
Referenced by CounterMappingRegion(), and endLoc().
LineStart
unsigned llvm::coverage::CounterMappingRegion::LineStart
Definition at line 160 of file CoverageMapping.h.
Referenced by CounterMappingRegion(), and startLoc().
The documentation for this struct was generated from the following file:
CoverageMapping.h