LLVM: llvm::detail::PassModel< IRUnitT, PassT, PreservedAnalysesT, false > Struct Template Reference
LLVM API Documentation
llvm::detail::PassModel< IRUnitT, PassT, PreservedAnalysesT, false > Struct Template Reference
Specialization of PassModel for passes that accept an analyis manager.
#include <PassManagerInternal.h>
Public Member Functions
PassModel (PassT Pass)
PassModel (const PassModel &Arg)
PassModel (PassModel &&Arg)
PassModel & operator= (PassModel RHS)
PreservedAnalysesT run (IRUnitT &IR, AnalysisManager< IRUnitT > *AM) override
The polymorphic API which runs the pass over a given IR entity.
StringRef name () override
Polymorphic method to access the name of a pass.
Public Member Functions inherited from llvm::detail::PassConcept< IRUnitT >
virtual ~PassConcept ()
Public Attributes
PassT Pass
Friends
void swap (PassModel &LHS, PassModel &RHS)
Detailed Description
template<typename IRUnitT, typename PassT, typename PreservedAnalysesT>
struct llvm::detail::PassModel< IRUnitT, PassT, PreservedAnalysesT, false >
Specialization of PassModel for passes that accept an analyis manager.
Definition at line 108 of file PassManagerInternal.h.
Constructor & Destructor Documentation
PassModel() [1/3]
template<typename IRUnitT, typename PassT, typename PreservedAnalysesT> llvm::detail::PassModel< IRUnitT, PassT, PreservedAnalysesT, false >::PassModel (PassT Pass) inline explicit
Definition at line 110 of file PassManagerInternal.h.
References Pass.
Referenced by operator=(), PassModel(), PassModel(), and swap.
PassModel() [2/3]
template<typename IRUnitT, typename PassT, typename PreservedAnalysesT> llvm::detail::PassModel< IRUnitT, PassT, PreservedAnalysesT, false >::PassModel (const PassModel< IRUnitT, PassT, PreservedAnalysesT, false > & Arg) inline
Definition at line 113 of file PassManagerInternal.h.
References Pass, and PassModel().
PassModel() [3/3]
template<typename IRUnitT, typename PassT, typename PreservedAnalysesT> llvm::detail::PassModel< IRUnitT, PassT, PreservedAnalysesT, false >::PassModel (PassModel< IRUnitT, PassT, PreservedAnalysesT, false > && Arg) inline
Definition at line 114 of file PassManagerInternal.h.
References Pass, and PassModel().
Member Function Documentation
name()
template<typename IRUnitT, typename PassT, typename PreservedAnalysesT> StringRef llvm::detail::PassModel< IRUnitT, PassT, PreservedAnalysesT, false >::name () inline override virtual
Polymorphic method to access the name of a pass.
Implements llvm::detail::PassConcept< IRUnitT >.
Definition at line 127 of file PassManagerInternal.h.
operator=()
template<typename IRUnitT, typename PassT, typename PreservedAnalysesT> PassModel & llvm::detail::PassModel< IRUnitT, PassT, PreservedAnalysesT, false >::operator= (PassModel< IRUnitT, PassT, PreservedAnalysesT, false > RHS) inline
Definition at line 119 of file PassManagerInternal.h.
References PassModel(), and swap.
run()
template<typename IRUnitT, typename PassT, typename PreservedAnalysesT> PreservedAnalysesT llvm::detail::PassModel< IRUnitT, PassT, PreservedAnalysesT, false >::run (IRUnitT & IR, AnalysisManager< IRUnitT > * AM) inline override virtual
The polymorphic API which runs the pass over a given IR entity.
Note that actual pass object can omit the analysis manager argument if desired. Also that the analysis manager may be null if there is no analysis manager in the pass pipeline.
Implements llvm::detail::PassConcept< IRUnitT >.
Definition at line 124 of file PassManagerInternal.h.
References IR, and Pass.
Friends And Related Symbol Documentation
swap
template<typename IRUnitT, typename PassT, typename PreservedAnalysesT> void swap (PassModel< IRUnitT, PassT, PreservedAnalysesT, false > & LHS, PassModel< IRUnitT, PassT, PreservedAnalysesT, false > & RHS) friend
Definition at line 115 of file PassManagerInternal.h.
References PassModel(), swap, and std::swap().
Referenced by operator=(), and swap.
Member Data Documentation
Pass
template<typename IRUnitT, typename PassT, typename PreservedAnalysesT> PassT llvm::detail::PassModel< IRUnitT, PassT, PreservedAnalysesT, false >::Pass
Definition at line 128 of file PassManagerInternal.h.
Referenced by PassModel(), PassModel(), PassModel(), and run().
The documentation for this struct was generated from the following file:
PassManagerInternal.h