LLVM: llvm::DOTGraphTraits< MachineBlockFrequencyInfo * > Struct Reference
LLVM API Documentation
llvm::DOTGraphTraits< MachineBlockFrequencyInfo * > Struct Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (const MachineBasicBlock *Node, const MachineBlockFrequencyInfo *Graph)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType>
std::string getNodeLabel (const void *, const GraphType &)
Static Public Member Functions
static std::string getGraphName (const MachineBlockFrequencyInfo *G)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType>
static std::string getGraphName (const GraphType &)
template<typename GraphType>
static std::string getGraphProperties (const GraphType &)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const void *)
template<typename GraphType>
static bool hasNodeAddressLabel (const void *, const GraphType &)
template<typename GraphType>
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType>
static std::string getNodeAttributes (const void *, const GraphType &)
template<typename EdgeIter, typename GraphType>
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
template<typename EdgeIter>
static std::string getEdgeSourceLabel (const void *, EdgeIter)
template<typename EdgeIter>
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
template<typename EdgeIter>
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
static bool hasEdgeDestLabels ()
static unsigned numEdgeDestLabels (const void *)
static std::string getEdgeDestLabel (const void *, unsigned)
template<typename GraphType, typename GraphWriter>
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
Definition at line 81 of file MachineBlockFrequencyInfo.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::DOTGraphTraits (bool isSimple = false) inline explicit
Definition at line 83 of file MachineBlockFrequencyInfo.cpp.
References llvm::DefaultDOTGraphTraits::DefaultDOTGraphTraits(), and llvm::DefaultDOTGraphTraits::isSimple().
Member Function Documentation
getGraphName()
std::string llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getGraphName (const MachineBlockFrequencyInfo * G) inline static
Definition at line 86 of file MachineBlockFrequencyInfo.cpp.
References G.
getNodeLabel()
std::string llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getNodeLabel (const MachineBasicBlock * Node, const MachineBlockFrequencyInfo * Graph) inline
Definition at line 90 of file MachineBlockFrequencyInfo.cpp.
References llvm::MachineBlockFrequencyInfo::getBlockFreq(), llvm::BlockFrequency::getFrequency(), llvm::MachineBasicBlock::getName(), GVDT_Fraction, GVDT_Integer, GVDT_None, llvm_unreachable, llvm::MachineBlockFrequencyInfo::printBlockFreq(), llvm::StringRef::str(), and ViewMachineBlockFreqPropagationDAG.
The documentation for this struct was generated from the following file:
MachineBlockFrequencyInfo.cpp