LLVM: llvm::object::ArchiveMemberHeader Struct Reference
LLVM API Documentation
llvm::object::ArchiveMemberHeader Struct Reference
#include <Archive.h>
Public Member Functions
llvm::StringRef getName () const
Get the name without looking up long names.
uint32_t getSize () const
Members are not larger than 4GB.
sys::fs::perms getAccessMode () const
sys::TimeValue getLastModified () const
unsigned getUID () const
unsigned getGID () const
Public Attributes
char Name [16]
char LastModified [12]
char UID [6]
char GID [6]
char AccessMode [8]
char Size [10]
Size of data, not including header or padding.
char Terminator [2]
Detailed Description
Definition at line 27 of file Archive.h.
Member Function Documentation
getAccessMode()
sys::fs::perms ArchiveMemberHeader::getAccessMode () const
Definition at line 51 of file Archive.cpp.
References AccessMode, and llvm_unreachable.
getGID()
unsigned ArchiveMemberHeader::getGID () const
Definition at line 76 of file Archive.cpp.
References GID, and llvm_unreachable.
getLastModified()
sys::TimeValue ArchiveMemberHeader::getLastModified () const
Definition at line 58 of file Archive.cpp.
References LastModified, and llvm_unreachable.
getName()
StringRef ArchiveMemberHeader::getName () const
Get the name without looking up long names.
Definition at line 29 of file Archive.cpp.
References llvm::StringRef::find(), Name, and llvm::StringRef::npos.
Referenced by llvm::object::Archive::Child::Child().
getSize()
uint32_t ArchiveMemberHeader::getSize () const
Members are not larger than 4GB.
Definition at line 44 of file Archive.cpp.
References llvm_unreachable, and Size.
Referenced by llvm::object::Archive::Child::Child().
getUID()
unsigned ArchiveMemberHeader::getUID () const
Definition at line 69 of file Archive.cpp.
References llvm_unreachable, and UID.
Member Data Documentation
AccessMode
char llvm::object::ArchiveMemberHeader::AccessMode[8]
Definition at line 32 of file Archive.h.
Referenced by getAccessMode().
GID
char llvm::object::ArchiveMemberHeader::GID[6]
Definition at line 31 of file Archive.h.
Referenced by getGID().
LastModified
char llvm::object::ArchiveMemberHeader::LastModified[12]
Definition at line 29 of file Archive.h.
Referenced by getLastModified().
Name
char llvm::object::ArchiveMemberHeader::Name[16]
Definition at line 28 of file Archive.h.
Referenced by getName().
Size
char llvm::object::ArchiveMemberHeader::Size[10]
Size of data, not including header or padding.
Definition at line 33 of file Archive.h.
Referenced by getSize().
Terminator
char llvm::object::ArchiveMemberHeader::Terminator[2]
Definition at line 34 of file Archive.h.
UID
char llvm::object::ArchiveMemberHeader::UID[6]
Definition at line 30 of file Archive.h.
Referenced by getUID().
The documentation for this struct was generated from the following files:
Archive.h
Archive.cpp