LLVM: llvm::GraphTraits< DominatorTree * > Struct Reference
LLVM API Documentation
llvm::GraphTraits< DominatorTree * > Struct Reference
#include <Dominators.h>
Public Types
typedef DominatorTree *::UnknownGraphTypeError NodeType
Public Types inherited from llvm::GraphTraits< DomTreeNode * >
typedef DomTreeNode NodeType
typedef NodeType::iterator ChildIteratorType
typedef df_iterator< DomTreeNode * > nodes_iterator
Static Public Member Functions
static NodeType * getEntryNode (DominatorTree *DT)
static nodes_iterator nodes_begin (DominatorTree *N)
static nodes_iterator nodes_end (DominatorTree *N)
Static Public Member Functions inherited from llvm::GraphTraits< DomTreeNode * >
static NodeType * getEntryNode (NodeType *N)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
static nodes_iterator nodes_begin (DomTreeNode *N)
static nodes_iterator nodes_end (DomTreeNode *N)
Detailed Description
Definition at line 154 of file Dominators.h.
Member Typedef Documentation
NodeType
typedef DominatorTree *::UnknownGraphTypeError llvm::GraphTraits< DominatorTree * >::NodeType
Definition at line 60 of file GraphTraits.h.
Member Function Documentation
getEntryNode()
NodeType * llvm::GraphTraits< DominatorTree * >::getEntryNode (DominatorTree * DT) inline static
Definition at line 156 of file Dominators.h.
References llvm::DominatorTreeBase< NodeT >::getRootNode().
Referenced by nodes_begin(), and nodes_end().
nodes_begin()
nodes_iterator llvm::GraphTraits< DominatorTree * >::nodes_begin (DominatorTree * N) inline static
Definition at line 160 of file Dominators.h.
References llvm::df_begin(), getEntryNode(), and N.
nodes_end()
nodes_iterator llvm::GraphTraits< DominatorTree * >::nodes_end (DominatorTree * N) inline static
Definition at line 164 of file Dominators.h.
References llvm::df_end(), getEntryNode(), and N.
The documentation for this struct was generated from the following file:
Dominators.h