LLVM: llvm::FunctionTypeKeyInfo::KeyTy Struct Reference
LLVM API Documentation
llvm::FunctionTypeKeyInfo::KeyTy Struct Reference
#include <LLVMContextImpl.h>
Public Member Functions
KeyTy (const Type *R, const ArrayRef< Type * > &P, bool V)
KeyTy (const FunctionType *FT)
bool operator== (const KeyTy &that) const
bool operator!= (const KeyTy &that) const
Public Attributes
const Type * ReturnType
ArrayRef< Type * > Params
bool isVarArg
Detailed Description
Definition at line 122 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
KeyTy() [1/2]
llvm::FunctionTypeKeyInfo::KeyTy::KeyTy (const Type * R, const ArrayRef< Type * > & P, bool V) inline
Definition at line 126 of file LLVMContextImpl.h.
References isVarArg, P, Params, and ReturnType.
Referenced by operator!=(), and operator==().
KeyTy() [2/2]
llvm::FunctionTypeKeyInfo::KeyTy::KeyTy (const FunctionType * FT) inline
Definition at line 128 of file LLVMContextImpl.h.
References isVarArg, Params, and ReturnType.
Member Function Documentation
operator!=()
bool llvm::FunctionTypeKeyInfo::KeyTy::operator!= (const KeyTy & that) const inline
Definition at line 140 of file LLVMContextImpl.h.
References KeyTy(), and operator==().
operator==()
bool llvm::FunctionTypeKeyInfo::KeyTy::operator== (const KeyTy & that) const inline
Definition at line 131 of file LLVMContextImpl.h.
References isVarArg, KeyTy(), Params, and ReturnType.
Referenced by operator!=().
Member Data Documentation
isVarArg
bool llvm::FunctionTypeKeyInfo::KeyTy::isVarArg
Definition at line 125 of file LLVMContextImpl.h.
Referenced by llvm::FunctionTypeKeyInfo::getHashValue(), KeyTy(), KeyTy(), and operator==().
Params
ArrayRef<Type*> llvm::FunctionTypeKeyInfo::KeyTy::Params
Definition at line 124 of file LLVMContextImpl.h.
Referenced by llvm::FunctionTypeKeyInfo::getHashValue(), KeyTy(), KeyTy(), and operator==().
ReturnType
const Type* llvm::FunctionTypeKeyInfo::KeyTy::ReturnType
Definition at line 123 of file LLVMContextImpl.h.
Referenced by llvm::FunctionTypeKeyInfo::getHashValue(), KeyTy(), KeyTy(), and operator==().
The documentation for this struct was generated from the following file:
LLVMContextImpl.h