LLVM: llvm::DOTGraphTraits< const Function * > Struct Reference
LLVM API Documentation
llvm::DOTGraphTraits< const Function * > Struct Reference
#include <CFGPrinter.h>
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (const BasicBlock *Node, const Function *Graph)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType>
std::string getNodeLabel (const void *, const GraphType &)
Static Public Member Functions
static std::string getGraphName (const Function *F)
static std::string getSimpleNodeLabel (const BasicBlock *Node, const Function *)
static std::string getCompleteNodeLabel (const BasicBlock *Node, const Function *)
static std::string getEdgeSourceLabel (const BasicBlock *Node, succ_const_iterator I)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType>
static std::string getGraphName (const GraphType &)
template<typename GraphType>
static std::string getGraphProperties (const GraphType &)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const void *)
template<typename GraphType>
static bool hasNodeAddressLabel (const void *, const GraphType &)
template<typename GraphType>
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType>
static std::string getNodeAttributes (const void *, const GraphType &)
template<typename EdgeIter, typename GraphType>
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
template<typename EdgeIter>
static std::string getEdgeSourceLabel (const void *, EdgeIter)
template<typename EdgeIter>
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
template<typename EdgeIter>
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
static bool hasEdgeDestLabels ()
static unsigned numEdgeDestLabels (const void *)
static std::string getEdgeDestLabel (const void *, unsigned)
template<typename GraphType, typename GraphWriter>
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
Definition at line 26 of file CFGPrinter.h.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< const Function * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 28 of file CFGPrinter.h.
References llvm::DefaultDOTGraphTraits::DefaultDOTGraphTraits(), and llvm::DefaultDOTGraphTraits::isSimple().
Member Function Documentation
getCompleteNodeLabel()
std::string llvm::DOTGraphTraits< const Function * >::getCompleteNodeLabel (const BasicBlock * Node, const Function *) inline static
Definition at line 46 of file CFGPrinter.h.
References llvm::StringRef::empty(), llvm::Value::getName(), llvm::Value::printAsOperand(), and llvm::raw_string_ostream::str().
Referenced by getNodeLabel().
getEdgeSourceLabel()
std::string llvm::DOTGraphTraits< const Function * >::getEdgeSourceLabel (const BasicBlock * Node, succ_const_iterator I) inline static
Definition at line 99 of file CFGPrinter.h.
References llvm::dyn_cast(), llvm::SwitchInst::CaseIteratorT< const SwitchInst, const ConstantInt, const BasicBlock >::fromSuccessorIndex(), llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::getCaseValue(), llvm::BasicBlock::getTerminator(), llvm::ConstantInt::getValue(), I, llvm::raw_string_ostream::str(), and llvm::succ_begin().
getGraphName()
std::string llvm::DOTGraphTraits< const Function * >::getGraphName (const Function * F) inline static
Definition at line 30 of file CFGPrinter.h.
References F.
getNodeLabel()
std::string llvm::DOTGraphTraits< const Function * >::getNodeLabel (const BasicBlock * Node, const Function * Graph) inline
Definition at line 91 of file CFGPrinter.h.
References getCompleteNodeLabel(), getSimpleNodeLabel(), and llvm::DefaultDOTGraphTraits::isSimple().
getSimpleNodeLabel()
std::string llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel (const BasicBlock * Node, const Function *) inline static
Definition at line 34 of file CFGPrinter.h.
References llvm::StringRef::empty(), llvm::Value::getName(), llvm::Value::printAsOperand(), llvm::raw_string_ostream::str(), and llvm::StringRef::str().
Referenced by getNodeLabel().
The documentation for this struct was generated from the following file:
CFGPrinter.h