LLVM: llvm::DOTGraphTraits< PostDominatorTree * > Struct Reference
LLVM API Documentation
llvm::DOTGraphTraits< PostDominatorTree * > Struct Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (DomTreeNode *Node, PostDominatorTree *G)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType>
std::string getNodeLabel (const void *, const GraphType &)
Public Member Functions inherited from llvm::DOTGraphTraits< DomTreeNode * >
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (DomTreeNode *Node, DomTreeNode *Graph)
Static Public Member Functions
static std::string getGraphName (PostDominatorTree *DT)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType>
static std::string getGraphName (const GraphType &)
template<typename GraphType>
static std::string getGraphProperties (const GraphType &)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const void *)
template<typename GraphType>
static bool hasNodeAddressLabel (const void *, const GraphType &)
template<typename GraphType>
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType>
static std::string getNodeAttributes (const void *, const GraphType &)
template<typename EdgeIter, typename GraphType>
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
template<typename EdgeIter>
static std::string getEdgeSourceLabel (const void *, EdgeIter)
template<typename EdgeIter>
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
template<typename EdgeIter>
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
static bool hasEdgeDestLabels ()
static unsigned numEdgeDestLabels (const void *)
static std::string getEdgeDestLabel (const void *, unsigned)
template<typename GraphType, typename GraphWriter>
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
Definition at line 67 of file DomPrinter.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< PostDominatorTree * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 70 of file DomPrinter.cpp.
References DOTGraphTraits(), and llvm::DefaultDOTGraphTraits::isSimple().
Referenced by DOTGraphTraits().
Member Function Documentation
getGraphName()
std::string llvm::DOTGraphTraits< PostDominatorTree * >::getGraphName (PostDominatorTree * DT) inline static
Definition at line 73 of file DomPrinter.cpp.
getNodeLabel()
std::string llvm::DOTGraphTraits< PostDominatorTree * >::getNodeLabel (DomTreeNode * Node, PostDominatorTree * G) inline
Definition at line 77 of file DomPrinter.cpp.
References G, and llvm::DefaultDOTGraphTraits::getNodeLabel().
The documentation for this struct was generated from the following file:
DomPrinter.cpp