LLVM: llvm::RegisterAnalysisGroup< Interface, Default > Struct Template Reference
LLVM API Documentation
llvm::RegisterAnalysisGroup< Interface, Default > Struct Template Reference
#include <PassSupport.h>
Public Member Functions
RegisterAnalysisGroup (PassInfo &RPB)
RegisterAnalysisGroup (const char *Name)
Public Member Functions inherited from llvm::RegisterAGBase
RegisterAGBase (const char *Name, const void *InterfaceID, const void *PassID=nullptr, bool isDefault=false)
Public Member Functions inherited from llvm::PassInfo
PassInfo (const char *name, const char *arg, const void *pi, NormalCtor_t normal, bool isCFGOnly, bool is_analysis, TargetMachineCtor_t machine=nullptr)
PassInfo (const char *name, const void *pi)
const char * getPassName () const
const char * getPassArgument () const
const void * getTypeInfo () const
bool isPassID (const void *IDPtr) const
Return true if this PassID implements the specified ID pointer.
bool isAnalysisGroup () const
bool isAnalysis () const
bool isCFGOnlyPass () const
NormalCtor_t getNormalCtor () const
void setNormalCtor (NormalCtor_t Ctor)
TargetMachineCtor_t getTargetMachineCtor () const
void setTargetMachineCtor (TargetMachineCtor_t Ctor)
Pass * createPass () const
createPass() - Use this method to create an instance of this pass.
void addInterfaceImplemented (const PassInfo *ItfPI)
const std::vector< const PassInfo * > & getInterfacesImplemented () const
Additional Inherited Members
Public Types inherited from llvm::PassInfo
typedef Pass *(* NormalCtor_t) ()
typedef Pass *(* TargetMachineCtor_t) (TargetMachine *)
Detailed Description
template<typename Interface, bool Default = false>
struct llvm::RegisterAnalysisGroup< Interface, Default >
Definition at line 160 of file PassSupport.h.
Constructor & Destructor Documentation
RegisterAnalysisGroup() [1/2]
template<typename Interface, bool Default = false> llvm::RegisterAnalysisGroup< Interface, Default >::RegisterAnalysisGroup (PassInfo & RPB) inline explicit
Definition at line 161 of file PassSupport.h.
References Default, llvm::PassInfo::getPassName(), llvm::PassInfo::getTypeInfo(), and llvm::RegisterAGBase::RegisterAGBase().
RegisterAnalysisGroup() [2/2]
template<typename Interface, bool Default = false> llvm::RegisterAnalysisGroup< Interface, Default >::RegisterAnalysisGroup (const char * Name) inline explicit
Definition at line 167 of file PassSupport.h.
References Name, and llvm::RegisterAGBase::RegisterAGBase().
The documentation for this struct was generated from the following file:
PassSupport.h