LLVM: llvm::TargetLowering::TargetLoweringOpt Struct Reference
LLVM API Documentation
llvm::TargetLowering::TargetLoweringOpt Struct Reference
#include <TargetLowering.h>
Public Member Functions
TargetLoweringOpt (SelectionDAG &InDAG, bool LT, bool LO)
bool LegalTypes () const
bool LegalOperations () const
bool CombineTo (SDValue O, SDValue N)
bool ShrinkDemandedConstant (SDValue Op, const APInt &Demanded)
bool ShrinkDemandedOp (SDValue Op, unsigned BitWidth, const APInt &Demanded, SDLoc dl)
Public Attributes
SelectionDAG & DAG
bool LegalTys
bool LegalOps
SDValue Old
SDValue New
Detailed Description
A convenience struct that encapsulates a DAG, and two SDValues for returning information from TargetLowering to its clients that want to combine.
Definition at line 2096 of file TargetLowering.h.
Constructor & Destructor Documentation
TargetLoweringOpt()
llvm::TargetLowering::TargetLoweringOpt::TargetLoweringOpt (SelectionDAG & InDAG, bool LT, bool LO) inline explicit
Definition at line 2103 of file TargetLowering.h.
References DAG, LegalOps, and LegalTys.
Member Function Documentation
CombineTo()
bool llvm::TargetLowering::TargetLoweringOpt::CombineTo (SDValue O, SDValue N) inline
Definition at line 2110 of file TargetLowering.h.
References N, New, and Old.
Referenced by ShrinkDemandedConstant(), ShrinkDemandedOp(), and llvm::TargetLowering::SimplifyDemandedBits().
LegalOperations()
bool llvm::TargetLowering::TargetLoweringOpt::LegalOperations () const inline
Definition at line 2108 of file TargetLowering.h.
References LegalOps.
Referenced by llvm::TargetLowering::SimplifyDemandedBits().
LegalTypes()
bool llvm::TargetLowering::TargetLoweringOpt::LegalTypes () const inline
Definition at line 2107 of file TargetLowering.h.
References LegalTys.
Referenced by llvm::TargetLowering::SimplifyDemandedBits().
ShrinkDemandedConstant()
bool TargetLowering::TargetLoweringOpt::ShrinkDemandedConstant (SDValue Op, const APInt & Demanded)
Check to see if the specified operand of the specified instruction is a constant integer. If so, check to see if there are any bits set in the constant that are not demanded. If so, shrink the constant and return true.
ShrinkDemandedConstant - Check to see if the specified operand of the specified instruction is a constant integer. If so, check to see if there are any bits set in the constant that are not demanded. If so, shrink the constant and return true.
Definition at line 283 of file TargetLowering.cpp.
References llvm::ISD::AND, CombineTo(), DAG, llvm::dyn_cast(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), New, llvm::ISD::OR, and llvm::ISD::XOR.
Referenced by PerformBTCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), PerformSELECTCombine(), and llvm::TargetLowering::SimplifyDemandedBits().
ShrinkDemandedOp()
bool TargetLowering::TargetLoweringOpt::ShrinkDemandedOp (SDValue Op, unsigned BitWidth, const APInt & Demanded, SDLoc dl)
Convert x+y to (VT)((SmallVT)x+(SmallVT)y) if the casts are free. This uses isZExtFree and ZERO_EXTEND for the widening cast, but it could be generalized for targets with other types of implicit widening casts.
ShrinkDemandedOp - Convert x+y to (VT)((SmallVT)x+(SmallVT)y) if the casts are free. This uses isZExtFree and ZERO_EXTEND for the widening cast, but it could be generalized for targets with other types of implicit widening casts.
Definition at line 322 of file TargetLowering.cpp.
References llvm::ISD::ANY_EXTEND, CombineTo(), llvm::APInt::countLeadingZeros(), DAG, llvm::EVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SDValue::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::hasOneUse(), llvm::isPowerOf2_32(), llvm::TargetLoweringBase::isTruncateFree(), llvm::EVT::isVector(), llvm::TargetLoweringBase::isZExtFree(), llvm::NextPowerOf2(), llvm::ISD::TRUNCATE, llvm::X, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::TargetLowering::SimplifyDemandedBits().
Member Data Documentation
DAG
SelectionDAG& llvm::TargetLowering::TargetLoweringOpt::DAG
Definition at line 2097 of file TargetLowering.h.
Referenced by ShrinkDemandedConstant(), ShrinkDemandedOp(), llvm::TargetLowering::SimplifyDemandedBits(), and TargetLoweringOpt().
LegalOps
bool llvm::TargetLowering::TargetLoweringOpt::LegalOps
Definition at line 2099 of file TargetLowering.h.
Referenced by LegalOperations(), and TargetLoweringOpt().
LegalTys
bool llvm::TargetLowering::TargetLoweringOpt::LegalTys
Definition at line 2098 of file TargetLowering.h.
Referenced by LegalTypes(), and TargetLoweringOpt().
New
SDValue llvm::TargetLowering::TargetLoweringOpt::New
Definition at line 2101 of file TargetLowering.h.
Referenced by CombineTo(), PerformSELECTCombine(), and ShrinkDemandedConstant().
Old
SDValue llvm::TargetLowering::TargetLoweringOpt::Old
Definition at line 2100 of file TargetLowering.h.
Referenced by CombineTo(), and PerformSELECTCombine().
The documentation for this struct was generated from the following files:
TargetLowering.h
TargetLowering.cpp