LLVM: llvm::object::Elf_Dyn_Impl< ELFT > Struct Template Reference
LLVM API Documentation
llvm::object::Elf_Dyn_Impl< ELFT > Struct Template Reference
Elf_Dyn_Impl: This inherits from Elf_Dyn_Base, adding getters and setters.
#include <ELFTypes.h>
Public Member Functions
int64_t getTag () const
uint64_t getVal () const
uint64_t getPtr () const
Detailed Description
template<class ELFT>
struct llvm::object::Elf_Dyn_Impl< ELFT >
Elf_Dyn_Impl: This inherits from Elf_Dyn_Base, adding getters and setters.
Definition at line 284 of file ELFTypes.h.
Member Function Documentation
getPtr()
template<class ELFT> uint64_t llvm::object::Elf_Dyn_Impl< ELFT >::getPtr () const inline
Definition at line 289 of file ELFTypes.h.
getTag()
template<class ELFT> int64_t llvm::object::Elf_Dyn_Impl< ELFT >::getTag () const inline
Definition at line 287 of file ELFTypes.h.
Referenced by llvm::object::ELFFile< ELFT >::end_dynamic_table(), and llvm::object::ELFObjectFile< ELFT >::getLoadName().
getVal()
template<class ELFT> uint64_t llvm::object::Elf_Dyn_Impl< ELFT >::getVal () const inline
Definition at line 288 of file ELFTypes.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::getLoadName().
The documentation for this struct was generated from the following file:
ELFTypes.h