LLVM: llvm::ilist_traits< Argument > Struct Reference
LLVM API Documentation
llvm::ilist_traits< Argument > Struct Reference
#include <Function.h>
Public Member Functions
Argument * createSentinel () const
Argument * provideInitialHead () const
Argument * ensureHead (Argument *) const
Public Member Functions inherited from llvm::ilist_node_traits< Argument >
void addNodeToList (Argument *)
void removeNodeFromList (Argument *)
void transferNodesFromList (ilist_node_traits &, ilist_iterator< Argument >, ilist_iterator< Argument >)
Public Member Functions inherited from llvm::SymbolTableListTraits< Argument, Function >
SymbolTableListTraits ()
Function * getListOwner ()
void addNodeToList (Argument *V)
void removeNodeFromList (Argument *V)
void transferNodesFromList (ilist_traits< Argument > &L2, ilist_iterator< Argument > first, ilist_iterator< Argument > last)
void setSymTabObject (TPtr *, TPtr)
Static Public Member Functions
static void destroySentinel (Argument *)
static void noteHead (Argument *, Argument *)
static ValueSymbolTable * getSymTab (Function *ItemParent)
Static Public Member Functions inherited from llvm::ilist_nextprev_traits< Argument >
static Argument * getPrev (Argument *N)
static Argument * getNext (Argument *N)
static void setPrev (Argument *N, Argument *Prev)
static void setNext (Argument *N, Argument *Next)
Static Public Member Functions inherited from llvm::ilist_sentinel_traits< Argument >
static Argument * createSentinel ()
createSentinel - create the dynamic sentinel
static void destroySentinel (Argument *N)
destroySentinel - deallocate the dynamic sentinel
static Argument * provideInitialHead ()
static Argument * ensureHead (Argument *&Head)
static void noteHead (Argument *NewHead, Argument *Sentinel)
noteHead - stash the sentinel into its default location
Static Public Member Functions inherited from llvm::ilist_node_traits< Argument >
static Argument * createNode (const Argument &V)
static void deleteNode (Argument *V)
Static Public Member Functions inherited from llvm::SymbolTableListTraits< Argument, Function >
static iplist< Argument > & getList (Function *Par)
static ValueSymbolTable * getSymTab (Function *Par)
static ValueSymbolTable * toPtr (ValueSymbolTable *P)
Detailed Description
Definition at line 54 of file Function.h.
Member Function Documentation
createSentinel()
Argument * llvm::ilist_traits< Argument >::createSentinel () const inline
Definition at line 57 of file Function.h.
destroySentinel()
void llvm::ilist_traits< Argument >::destroySentinel (Argument *) inline static
Definition at line 60 of file Function.h.
ensureHead()
Argument * llvm::ilist_traits< Argument >::ensureHead (Argument *) const inline
Definition at line 63 of file Function.h.
References llvm::ilist_sentinel_traits< NodeTy >::createSentinel().
getSymTab()
ValueSymbolTable * llvm::ilist_traits< Argument >::getSymTab (Function * ItemParent) inline static
Definition at line 531 of file Function.h.
References F.
Referenced by llvm::SymbolTableListTraits< Argument, Function >::setSymTabObject().
noteHead()
void llvm::ilist_traits< Argument >::noteHead (Argument * , Argument *) inline static
Definition at line 64 of file Function.h.
provideInitialHead()
Argument * llvm::ilist_traits< Argument >::provideInitialHead () const inline
Definition at line 62 of file Function.h.
References llvm::ilist_sentinel_traits< NodeTy >::createSentinel().
The documentation for this struct was generated from the following file:
Function.h