LLVM: llvm::cl::OptionValue< cl::boolOrDefault > Struct Reference
LLVM API Documentation
llvm::cl::OptionValue< cl::boolOrDefault > Struct Reference
#include <CommandLine.h>
Public Types
typedef cl::boolOrDefault WrapperType
Public Types inherited from llvm::cl::OptionValueBase< DataType, isClass >
typedef OptionValue< DataType > WrapperType
Public Member Functions
OptionValue ()
OptionValue (const cl::boolOrDefault &V)
OptionValue< cl::boolOrDefault > & operator= (const cl::boolOrDefault &V)
Public Member Functions inherited from llvm::cl::OptionValueBase< DataType, isClass >
bool hasValue () const
const DataType & getValue () const
template<class DT>
void setValue (const DT &)
bool compare (const DataType &) const
bool compare (const GenericOptionValue &) const override
Public Member Functions inherited from llvm::cl::GenericOptionValue
virtual ~GenericOptionValue ()
Public Member Functions inherited from llvm::cl::OptionValueCopy< cl::boolOrDefault >
OptionValueCopy ()
bool hasValue () const
const cl::boolOrDefault & getValue () const
void setValue (const cl::boolOrDefault &V)
bool compare (const cl::boolOrDefault &V) const
Detailed Description
Definition at line 430 of file CommandLine.h.
Member Typedef Documentation
WrapperType
typedef cl::boolOrDefault llvm::cl::OptionValue< cl::boolOrDefault >::WrapperType
Definition at line 431 of file CommandLine.h.
Constructor & Destructor Documentation
OptionValue() [1/2]
llvm::cl::OptionValue< cl::boolOrDefault >::OptionValue () inline
Definition at line 433 of file CommandLine.h.
Referenced by operator=().
OptionValue() [2/2]
llvm::cl::OptionValue< cl::boolOrDefault >::OptionValue (const cl::boolOrDefault & V) inline
Definition at line 435 of file CommandLine.h.
References llvm::cl::OptionValueBase< DataType, std::is_class< DataType >::value >::setValue().
Member Function Documentation
operator=()
OptionValue< cl::boolOrDefault > & llvm::cl::OptionValue< cl::boolOrDefault >::operator= (const cl::boolOrDefault & V) inline
Definition at line 436 of file CommandLine.h.
References OptionValue(), and llvm::cl::OptionValueBase< DataType, std::is_class< DataType >::value >::setValue().
The documentation for this struct was generated from the following file:
CommandLine.h