LLVM: SystemZSubtarget.cpp File Reference
LLVM API Documentation
SystemZSubtarget.cpp File Reference
#include "SystemZSubtarget.h"
#include "MCTargetDesc/SystemZMCTargetDesc.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/Support/Host.h"
#include "SystemZGenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "systemz-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Functions
static bool bindsLocally (const GlobalValue *GV, Reloc::Model RM)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "systemz-subtarget"
Definition at line 17 of file SystemZSubtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 20 of file SystemZSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 19 of file SystemZSubtarget.cpp.
Function Documentation
bindsLocally()
bool bindsLocally (const GlobalValue * GV, Reloc::Model RM) static
Definition at line 56 of file SystemZSubtarget.cpp.
References llvm::GlobalValue::hasDefaultVisibility(), llvm::GlobalValue::hasLocalLinkage(), and llvm::Reloc::Static.
Referenced by llvm::SystemZSubtarget::isPC32DBLSymbol().