LLVM: SystemZMCTargetDesc.cpp File Reference
LLVM API Documentation
SystemZMCTargetDesc.cpp File Reference
#include "SystemZMCTargetDesc.h"
#include "InstPrinter/SystemZInstPrinter.h"
#include "SystemZMCAsmInfo.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/TargetRegistry.h"
#include "SystemZGenInstrInfo.inc"
#include "SystemZGenSubtargetInfo.inc"
#include "SystemZGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCAsmInfo * createSystemZMCAsmInfo (const MCRegisterInfo &MRI, StringRef TT)
static MCInstrInfo * createSystemZMCInstrInfo ()
static MCRegisterInfo * createSystemZMCRegisterInfo (StringRef TT)
static MCSubtargetInfo * createSystemZMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
static MCCodeGenInfo * createSystemZMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCInstPrinter * createSystemZMCInstPrinter (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
static MCStreamer * createSystemZMCObjectStreamer (const Target &T, StringRef TT, MCContext &Ctx, MCAsmBackend &MAB, raw_ostream &OS, MCCodeEmitter *Emitter, const MCSubtargetInfo &STI, bool RelaxAll)
void LLVMInitializeSystemZTargetMC ()
Macro Definition Documentation
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 21 of file SystemZMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 27 of file SystemZMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 24 of file SystemZMCTargetDesc.cpp.
Function Documentation
createSystemZMCAsmInfo()
MCAsmInfo * createSystemZMCAsmInfo (const MCRegisterInfo & MRI, StringRef TT) static
Definition at line 97 of file SystemZMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::SystemZMC::CFAOffsetFromInitialSP, llvm::MCCFIInstruction::createDefCfa(), and llvm::MCRegisterInfo::getDwarfRegNum().
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCCodeGenInfo()
MCCodeGenInfo * createSystemZMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 128 of file SystemZMCTargetDesc.cpp.
References llvm::CodeModel::Default, llvm::Reloc::Default, llvm::Reloc::DynamicNoPIC, llvm::CodeModel::JITDefault, llvm::CodeModel::Medium, llvm::Reloc::PIC_, llvm::CodeModel::Small, llvm::Reloc::Static, and llvm::X.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCInstPrinter()
MCInstPrinter * createSystemZMCInstPrinter (const Target & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) static
Definition at line 175 of file SystemZMCTargetDesc.cpp.
References T.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCInstrInfo()
MCInstrInfo * createSystemZMCInstrInfo () static
Definition at line 108 of file SystemZMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCObjectStreamer()
MCStreamer * createSystemZMCObjectStreamer (const Target & T, StringRef TT, MCContext & Ctx, MCAsmBackend & MAB, raw_ostream & OS, MCCodeEmitter * Emitter, const MCSubtargetInfo & STI, bool RelaxAll) static
Definition at line 185 of file SystemZMCTargetDesc.cpp.
References llvm::createELFStreamer(), RelaxAll(), and T.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCRegisterInfo()
MCRegisterInfo * createSystemZMCRegisterInfo (StringRef TT) static
Definition at line 114 of file SystemZMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeSystemZTargetMC().
createSystemZMCSubtargetInfo()
MCSubtargetInfo * createSystemZMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS) static
Definition at line 120 of file SystemZMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializeSystemZTargetMC().
LLVMInitializeSystemZTargetMC()
void LLVMInitializeSystemZTargetMC ()
Definition at line 192 of file SystemZMCTargetDesc.cpp.
References llvm::createSystemZMCAsmBackend(), createSystemZMCAsmInfo(), llvm::createSystemZMCCodeEmitter(), createSystemZMCCodeGenInfo(), createSystemZMCInstPrinter(), createSystemZMCInstrInfo(), createSystemZMCObjectStreamer(), createSystemZMCRegisterInfo(), createSystemZMCSubtargetInfo(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCAsmInfo(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCCodeGenInfo(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCObjectStreamer(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), and llvm::TheSystemZTarget.