LLVM: TargetMachine.cpp File Reference
LLVM API Documentation
TargetMachine.cpp File Reference
#include "llvm/Target/TargetMachine.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Mangler.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCTargetOptions.h"
#include "llvm/MC/SectionKind.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Macros
#define RESET_OPTION(X, Y)
Functions
static TLSModel::Model getSelectedTLSModel (const GlobalValue *GV)
Get the IR-specified TLS model for Var.
static bool canUsePrivateLabel (const MCAsmInfo &AsmInfo, const MCSection &Section)
Macro Definition Documentation
RESET_OPTION
#define RESET_OPTION (X, Y)
Value:
  do {                                                                         \
    if (F.hasFnAttribute(Y))                                                  \
      Options.X = (F.getAttributes()                                          \
                       .getAttribute(AttributeSet::FunctionIndex, Y)           \
                       .getValueAsString() == "true");                         \
  } while (0)
Referenced by llvm::TargetMachine::resetTargetOptions().
Function Documentation
canUsePrivateLabel()
bool canUsePrivateLabel (const MCAsmInfo & AsmInfo, const MCSection & Section) static
Definition at line 173 of file TargetMachine.cpp.
References llvm::cast(), llvm::MCSectionMachO::hasAttribute(), llvm::MCAsmInfo::isSectionAtomizableBySymbols(), and llvm::MachO::S_ATTR_NO_DEAD_STRIP.
Referenced by llvm::TargetMachine::getNameWithPrefix().
getSelectedTLSModel()
TLSModel::Model getSelectedTLSModel (const GlobalValue * GV) static
Get the IR-specified TLS model for Var.
Definition at line 89 of file TargetMachine.cpp.
References llvm::TLSModel::GeneralDynamic, llvm::GlobalValue::GeneralDynamicTLSModel, llvm::GlobalValue::getThreadLocalMode(), llvm::TLSModel::InitialExec, llvm::GlobalValue::InitialExecTLSModel, llvm_unreachable, llvm::TLSModel::LocalDynamic, llvm::GlobalValue::LocalDynamicTLSModel, llvm::TLSModel::LocalExec, llvm::GlobalValue::LocalExecTLSModel, and llvm::GlobalValue::NotThreadLocal.
Referenced by llvm::TargetMachine::getTLSModel().