LLVM: ThreadSanitizer.cpp File Reference
LLVM API Documentation
ThreadSanitizer.cpp File Reference
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
Macros
#define DEBUG_TYPE "tsan"
Functions
STATISTIC (NumInstrumentedReads, "Number of instrumented reads")
STATISTIC (NumInstrumentedWrites, "Number of instrumented writes")
STATISTIC (NumOmittedReadsBeforeWrite, "Number of reads ignored due to following writes")
STATISTIC (NumAccessesWithBadSize, "Number of accesses with bad size")
STATISTIC (NumInstrumentedVtableWrites, "Number of vtable ptr writes")
STATISTIC (NumInstrumentedVtableReads, "Number of vtable ptr reads")
STATISTIC (NumOmittedReadsFromConstantGlobals, "Number of reads from constant globals")
STATISTIC (NumOmittedReadsFromVtable, "Number of vtable reads")
INITIALIZE_PASS (ThreadSanitizer, "tsan", "ThreadSanitizer: detects data races.", false, false) const char *ThreadSanitizer
static Function * checkInterfaceFunction (Constant *FuncOrBitcast)
static bool isVtableAccess (Instruction *I)
static bool isAtomic (Instruction *I)
static ConstantInt * createOrdering (IRBuilder<> *IRB, AtomicOrdering ord)
Variables
static cl::opt< bool > ClInstrumentMemoryAccesses ("tsan-instrument-memory-accesses", cl::init(true), cl::desc("Instrument memory accesses"), cl::Hidden)
static cl::opt< bool > ClInstrumentFuncEntryExit ("tsan-instrument-func-entry-exit", cl::init(true), cl::desc("Instrument function entry and exit"), cl::Hidden)
static cl::opt< bool > ClInstrumentAtomics ("tsan-instrument-atomics", cl::init(true), cl::desc("Instrument atomics"), cl::Hidden)
static cl::opt< bool > ClInstrumentMemIntrinsics ("tsan-instrument-memintrinsics", cl::init(true), cl::desc("Instrument memintrinsics (memset/memcpy/memmove)"), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "tsan"
Definition at line 46 of file ThreadSanitizer.cpp.
Function Documentation
checkInterfaceFunction()
Function * checkInterfaceFunction (Constant * FuncOrBitcast) static
Definition at line 127 of file ThreadSanitizer.cpp.
References llvm::Value::dump(), llvm::dyn_cast(), F, and llvm::report_fatal_error().
createOrdering()
ConstantInt * createOrdering (IRBuilder<> * IRB, AtomicOrdering ord) static
Definition at line 422 of file ThreadSanitizer.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::IRBuilderBase::getInt32(), llvm_unreachable, llvm::Monotonic, llvm::NotAtomic, llvm::Release, llvm::SequentiallyConsistent, and llvm::Unordered.
INITIALIZE_PASS()
INITIALIZE_PASS (ThreadSanitizer , "tsan" , "ThreadSanitizer: detects data races." , false , false) const
Definition at line 115 of file ThreadSanitizer.cpp.
References const.
isAtomic()
bool isAtomic (Instruction * I) static
Definition at line 299 of file ThreadSanitizer.cpp.
References llvm::CrossThread, llvm::dyn_cast(), I, and llvm::isa().
Referenced by llvm::AssemblyWriter::printInstruction(), and WriteInstruction().
isVtableAccess()
bool isVtableAccess (Instruction * I) static
Definition at line 233 of file ThreadSanitizer.cpp.
References I, and llvm::LLVMContext::MD_tbaa.
STATISTIC() [1/8]
STATISTIC (NumAccessesWithBadSize , "Number of accesses with bad size")
STATISTIC() [2/8]
STATISTIC (NumInstrumentedReads , "Number of instrumented reads")
STATISTIC() [3/8]
STATISTIC (NumInstrumentedVtableReads , "Number of vtable ptr reads")
STATISTIC() [4/8]
STATISTIC (NumInstrumentedVtableWrites , "Number of vtable ptr writes")
STATISTIC() [5/8]
STATISTIC (NumInstrumentedWrites , "Number of instrumented writes")
STATISTIC() [6/8]
STATISTIC (NumOmittedReadsBeforeWrite , "Number of reads ignored due to following writes")
STATISTIC() [7/8]
STATISTIC (NumOmittedReadsFromConstantGlobals , "Number of reads from constant globals")
STATISTIC() [8/8]
STATISTIC (NumOmittedReadsFromVtable , "Number of vtable reads")
Variable Documentation
ClInstrumentAtomics
cl::opt< bool > ClInstrumentAtomics("tsan-instrument-atomics", cl::init(true), cl::desc("Instrument atomics"), cl::Hidden) ("tsan-instrument-atomics" , cl::init(true) , cl::desc("Instrument atomics") , cl::Hidden) static
ClInstrumentFuncEntryExit
cl::opt< bool > ClInstrumentFuncEntryExit("tsan-instrument-func-entry-exit", cl::init(true), cl::desc("Instrument function entry and exit"), cl::Hidden) ("tsan-instrument-func-entry-exit" , cl::init(true) , cl::desc("Instrument function entry and exit") , cl::Hidden) static
ClInstrumentMemIntrinsics
cl::opt< bool > ClInstrumentMemIntrinsics("tsan-instrument-memintrinsics", cl::init(true), cl::desc("Instrument memintrinsics (memset/memcpy/memmove)"), cl::Hidden) ("tsan-instrument-memintrinsics" , cl::init(true) , cl::desc("Instrument memintrinsics (memset/memcpy/memmove)") , cl::Hidden) static
ClInstrumentMemoryAccesses
cl::opt< bool > ClInstrumentMemoryAccesses("tsan-instrument-memory-accesses", cl::init(true), cl::desc("Instrument memory accesses"), cl::Hidden) ("tsan-instrument-memory-accesses" , cl::init(true) , cl::desc("Instrument memory accesses") , cl::Hidden) static