LLVM: Timer.cpp File Reference
LLVM API Documentation
Timer.cpp File Reference
#include "llvm/Support/Timer.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/MutexGuard.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/raw_ostream.h"
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Functions
raw_ostream * llvm::CreateInfoOutputFile ()
static std::string & getLibSupportInfoOutputFilename ()
static TimerGroup * getDefaultTimerGroup ()
static size_t getMemUsage ()
static void printVal (double Val, double Total, raw_ostream &OS)
static Timer & getNamedRegionTimer (StringRef Name)
Variables
static ManagedStatic< std::string > LibSupportInfoOutputFilename
static ManagedStatic< sys::SmartMutex< true > > TimerLock
static TimerGroup * DefaultTimerGroup = nullptr
static ManagedStatic< std::vector< Timer * > > ActiveTimers
static ManagedStatic< Name2TimerMap > NamedTimers
static ManagedStatic< Name2PairMap > NamedGroupedTimers
static TimerGroup * TimerGroupList = nullptr
Function Documentation
getDefaultTimerGroup()
TimerGroup * getDefaultTimerGroup () static
Definition at line 83 of file Timer.cpp.
References DefaultTimerGroup, Lock, llvm::sys::MemoryFence(), and TimerLock.
Referenced by llvm::Timer::init().
getLibSupportInfoOutputFilename()
std::string & getLibSupportInfoOutputFilename () static
Definition at line 39 of file Timer.cpp.
References LibSupportInfoOutputFilename.
Referenced by llvm::CreateInfoOutputFile().
getMemUsage()
size_t getMemUsage () inline static
Definition at line 124 of file Timer.cpp.
References llvm::sys::Process::GetMallocUsage().
Referenced by llvm::TimeRecord::getCurrentTime().
getNamedRegionTimer()
Timer & getNamedRegionTimer (StringRef Name) static
Definition at line 228 of file Timer.cpp.
References Name, T, and TimerLock.
Referenced by llvm::NamedRegionTimer::NamedRegionTimer().
printVal()
void printVal (double Val, double Total, raw_ostream & OS) static
Definition at line 168 of file Timer.cpp.
References llvm::format().
Referenced by llvm::TimeRecord::print().
Variable Documentation
ActiveTimers
ManagedStatic<std::vector<Timer*> > ActiveTimers static
Definition at line 147 of file Timer.cpp.
Referenced by llvm::Timer::startTimer(), and llvm::Timer::stopTimer().
DefaultTimerGroup
TimerGroup* DefaultTimerGroup = nullptr static
Definition at line 82 of file Timer.cpp.
Referenced by getDefaultTimerGroup().
LibSupportInfoOutputFilename
ManagedStatic<std::string> LibSupportInfoOutputFilename static
Definition at line 38 of file Timer.cpp.
Referenced by getLibSupportInfoOutputFilename().
NamedGroupedTimers
ManagedStatic<Name2PairMap> NamedGroupedTimers static
Definition at line 226 of file Timer.cpp.
Referenced by llvm::NamedRegionTimer::NamedRegionTimer().
NamedTimers
ManagedStatic<Name2TimerMap> NamedTimers static
Definition at line 225 of file Timer.cpp.
TimerGroupList
TimerGroup* TimerGroupList = nullptr static
TimerGroupList - This is the global list of TimerGroups, maintained by the TimerGroup ctor/dtor and is protected by the TimerLock lock.
Definition at line 251 of file Timer.cpp.
Referenced by llvm::TimerGroup::printAll(), and llvm::TimerGroup::TimerGroup().
TimerLock
ManagedStatic<sys::SmartMutex<true> > TimerLock static
Definition at line 43 of file Timer.cpp.
Referenced by getDefaultTimerGroup(), getNamedRegionTimer(), llvm::TimerGroup::print(), llvm::TimerGroup::printAll(), llvm::TimerGroup::TimerGroup(), and llvm::TimerGroup::~TimerGroup().