LLVM: UseListOrder.cpp File Reference
LLVM API Documentation
UseListOrder.cpp File Reference
#include "llvm/IR/UseListOrder.h"
#include "llvm/Support/CommandLine.h"
Variables
static cl::opt< bool > PreserveBitcodeUseListOrder ("preserve-bc-use-list-order", cl::desc("Experimental support to preserve bitcode use-list order."), cl::init(false), cl::Hidden)
static cl::opt< bool > PreserveAssemblyUseListOrder ("preserve-ll-use-list-order", cl::desc("Experimental support to preserve assembly use-list order."), cl::init(false), cl::Hidden)
Variable Documentation
PreserveAssemblyUseListOrder
cl::opt< bool > PreserveAssemblyUseListOrder("preserve-ll-use-list-order", cl::desc("Experimental support to preserve assembly use-list order."), cl::init(false), cl::Hidden) ("preserve-ll-use-list-order" , cl::desc("Experimental support to preserve assembly use-list order.") , cl::init(false) , cl::Hidden) static
Referenced by llvm::setPreserveAssemblyUseListOrder(), and llvm::shouldPreserveAssemblyUseListOrder().
PreserveBitcodeUseListOrder
cl::opt< bool > PreserveBitcodeUseListOrder("preserve-bc-use-list-order", cl::desc("Experimental support to preserve bitcode use-list order."), cl::init(false), cl::Hidden) ("preserve-bc-use-list-order" , cl::desc("Experimental support to preserve bitcode use-list order.") , cl::init(false) , cl::Hidden) static
Referenced by llvm::setPreserveBitcodeUseListOrder(), and llvm::shouldPreserveBitcodeUseListOrder().