LLVM: ValueMapper.cpp File Reference
LLVM API Documentation
ValueMapper.cpp File Reference
#include "llvm/Transforms/Utils/ValueMapper.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Metadata.def"
Macros
#define HANDLE_UNIQUABLE_LEAF(CLASS)
Functions
static Metadata * mapToMetadata (ValueToValueMapTy &VM, const Metadata *Key, Metadata *Val)
static Metadata * mapToSelf (ValueToValueMapTy &VM, const Metadata *MD)
static Metadata * MapMetadataImpl (const Metadata *MD, SmallVectorImpl< UniquableMDNode * > &Cycles, ValueToValueMapTy &VM, RemapFlags Flags, ValueMapTypeRemapper *TypeMapper, ValueMaterializer *Materializer)
static Metadata * mapMetadataOp (Metadata *Op, SmallVectorImpl< UniquableMDNode * > &Cycles, ValueToValueMapTy &VM, RemapFlags Flags, ValueMapTypeRemapper *TypeMapper, ValueMaterializer *Materializer)
static Metadata * cloneMDTuple (const MDTuple *Node, SmallVectorImpl< UniquableMDNode * > &Cycles, ValueToValueMapTy &VM, RemapFlags Flags, ValueMapTypeRemapper *TypeMapper, ValueMaterializer *Materializer, bool IsDistinct)
static Metadata * cloneMDLocation (const MDLocation *Node, SmallVectorImpl< UniquableMDNode * > &Cycles, ValueToValueMapTy &VM, RemapFlags Flags, ValueMapTypeRemapper *TypeMapper, ValueMaterializer *Materializer, bool IsDistinct)
static Metadata * cloneMDNode (const UniquableMDNode *Node, SmallVectorImpl< UniquableMDNode * > &Cycles, ValueToValueMapTy &VM, RemapFlags Flags, ValueMapTypeRemapper *TypeMapper, ValueMaterializer *Materializer, bool IsDistinct)
static void trackCyclesUnderDistinct (const UniquableMDNode *Node, SmallVectorImpl< UniquableMDNode * > &Cycles)
static Metadata * mapDistinctNode (const UniquableMDNode *Node, SmallVectorImpl< UniquableMDNode * > &Cycles, ValueToValueMapTy &VM, RemapFlags Flags, ValueMapTypeRemapper *TypeMapper, ValueMaterializer *Materializer)
Map a distinct MDNode.
static bool shouldRemapUniquedNode (const UniquableMDNode *Node, SmallVectorImpl< UniquableMDNode * > &Cycles, ValueToValueMapTy &VM, RemapFlags Flags, ValueMapTypeRemapper *TypeMapper, ValueMaterializer *Materializer)
Check whether a uniqued node needs to be remapped.
static Metadata * mapUniquedNode (const UniquableMDNode *Node, SmallVectorImpl< UniquableMDNode * > &Cycles, ValueToValueMapTy &VM, RemapFlags Flags, ValueMapTypeRemapper *TypeMapper, ValueMaterializer *Materializer)
Map a uniqued MDNode.
Macro Definition Documentation
HANDLE_UNIQUABLE_LEAF
#define HANDLE_UNIQUABLE_LEAF (CLASS)
Value:
  case Metadata::CLASS##Kind:                                                  \
    return clone##CLASS(cast<CLASS>(Node), Cycles, VM, Flags, TypeMapper,      \
                        Materializer, IsDistinct);
Function Documentation
cloneMDLocation()
Metadata * cloneMDLocation (const MDLocation * Node, SmallVectorImpl< UniquableMDNode * > & Cycles, ValueToValueMapTy & VM, RemapFlags Flags, ValueMapTypeRemapper * TypeMapper, ValueMaterializer * Materializer, bool IsDistinct) static
Definition at line 204 of file ValueMapper.cpp.
References llvm::MDLocation::get(), llvm::MDLocation::getColumn(), llvm::MDNode::getContext(), llvm::MDLocation::getDistinct(), llvm::MDLocation::getInlinedAt(), llvm::MDLocation::getLine(), llvm::MDLocation::getScope(), and mapMetadataOp().
cloneMDNode()
Metadata * cloneMDNode (const UniquableMDNode * Node, SmallVectorImpl< UniquableMDNode * > & Cycles, ValueToValueMapTy & VM, RemapFlags Flags, ValueMapTypeRemapper * TypeMapper, ValueMaterializer * Materializer, bool IsDistinct) static
Definition at line 218 of file ValueMapper.cpp.
References llvm::Metadata::getMetadataID(), and llvm_unreachable.
Referenced by mapDistinctNode(), and mapUniquedNode().
cloneMDTuple()
Metadata * cloneMDTuple (const MDTuple * Node, SmallVectorImpl< UniquableMDNode * > & Cycles, ValueToValueMapTy & VM, RemapFlags Flags, ValueMapTypeRemapper * TypeMapper, ValueMaterializer * Materializer, bool IsDistinct) static
Definition at line 185 of file ValueMapper.cpp.
References llvm::MDTuple::get(), llvm::MDNode::getContext(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), I, mapMetadataOp(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorImpl< T >::reserve().
mapDistinctNode()
Metadata * mapDistinctNode (const UniquableMDNode * Node, SmallVectorImpl< UniquableMDNode * > & Cycles, ValueToValueMapTy & VM, RemapFlags Flags, ValueMapTypeRemapper * TypeMapper, ValueMaterializer * Materializer) static
Map a distinct MDNode.
Distinct nodes are not uniqued, so they must always recreated.
Definition at line 247 of file ValueMapper.cpp.
References llvm::cast(), cloneMDNode(), llvm::MDNode::getContext(), llvm::MDTuple::getDistinct(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::MDNode::getTemporary(), I, llvm::isa(), llvm::MDNode::isDistinct(), mapMetadataOp(), mapToMetadata(), llvm::None, llvm::MDNode::replaceOperandWith(), and trackCyclesUnderDistinct().
Referenced by MapMetadataImpl().
MapMetadataImpl()
Metadata * MapMetadataImpl (const Metadata * MD, SmallVectorImpl< UniquableMDNode * > & Cycles, ValueToValueMapTy & VM, RemapFlags Flags, ValueMapTypeRemapper * TypeMapper, ValueMaterializer * Materializer) static
Definition at line 334 of file ValueMapper.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::ValueAsMetadata::get(), llvm::isa(), llvm::MDNode::isDistinct(), llvm::UniquableMDNode::isResolved(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), mapDistinctNode(), mapToMetadata(), mapToSelf(), mapUniquedNode(), llvm::MapValue(), llvm::ValueMap< KeyT, ValueT, Config >::MD(), llvm::RF_IgnoreMissingEntries, and llvm::RF_NoModuleLevelChanges.
Referenced by llvm::MapMetadata(), and mapMetadataOp().
mapMetadataOp()
Metadata * mapMetadataOp (Metadata * Op, SmallVectorImpl< UniquableMDNode * > & Cycles, ValueToValueMapTy & VM, RemapFlags Flags, ValueMapTypeRemapper * TypeMapper, ValueMaterializer * Materializer) static
Definition at line 163 of file ValueMapper.cpp.
References MapMetadataImpl(), and llvm::RF_IgnoreMissingEntries.
Referenced by cloneMDLocation(), cloneMDTuple(), mapDistinctNode(), and shouldRemapUniquedNode().
mapToMetadata()
Metadata * mapToMetadata (ValueToValueMapTy & VM, const Metadata * Key, Metadata * Val) static
Definition at line 147 of file ValueMapper.cpp.
References llvm::ValueMap< KeyT, ValueT, Config >::MD().
Referenced by mapDistinctNode(), MapMetadataImpl(), mapToSelf(), and mapUniquedNode().
mapToSelf()
Metadata * mapToSelf (ValueToValueMapTy & VM, const Metadata * MD) static
Definition at line 153 of file ValueMapper.cpp.
References mapToMetadata().
Referenced by MapMetadataImpl(), and mapUniquedNode().
mapUniquedNode()
Metadata * mapUniquedNode (const UniquableMDNode * Node, SmallVectorImpl< UniquableMDNode * > & Cycles, ValueToValueMapTy & VM, RemapFlags Flags, ValueMapTypeRemapper * TypeMapper, ValueMaterializer * Materializer) static
Map a uniqued MDNode.
Uniqued nodes may not need to be recreated (they may map to themselves).
Definition at line 305 of file ValueMapper.cpp.
References cloneMDNode(), llvm::MDNode::deleteTemporary(), llvm::MDNode::getContext(), llvm::MDNode::getTemporary(), llvm::MDNode::isDistinct(), mapToMetadata(), mapToSelf(), llvm::None, and shouldRemapUniquedNode().
Referenced by MapMetadataImpl().
shouldRemapUniquedNode()
bool shouldRemapUniquedNode (const UniquableMDNode * Node, SmallVectorImpl< UniquableMDNode * > & Cycles, ValueToValueMapTy & VM, RemapFlags Flags, ValueMapTypeRemapper * TypeMapper, ValueMaterializer * Materializer) static
Check whether a uniqued node needs to be remapped.
Check whether a uniqued node needs to be remapped (due to any operands changing).
Definition at line 288 of file ValueMapper.cpp.
References llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), I, and mapMetadataOp().
Referenced by mapUniquedNode().
trackCyclesUnderDistinct()
void trackCyclesUnderDistinct (const UniquableMDNode * Node, SmallVectorImpl< UniquableMDNode * > & Cycles) static
Definition at line 235 of file ValueMapper.cpp.
References llvm::dyn_cast_or_null(), N, llvm::MDNode::operands(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by mapDistinctNode().