LLVM: WinCOFFObjectWriter.cpp File Reference
LLVM API Documentation
WinCOFFObjectWriter.cpp File Reference
#include "llvm/MC/MCWinCOFFObjectWriter.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/StringTableBuilder.h"
#include "llvm/Support/COFF.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TimeValue.h"
#include <cstdio>
Namespaces
namespace llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "WinCOFFObjectWriter"
Functions
static void write_uint32_le (void *Data, uint32_t Value)
static uint64_t getSymbolValue (const MCSymbolData &Data, const MCAsmLayout &Layout)
static void encodeBase64StringEntry (char *Buffer, uint64_t Value)
MCObjectWriter * llvm::createWinCOFFObjectWriter (MCWinCOFFObjectTargetWriter *MOTW, raw_ostream &OS)
Construct a new Win COFF writer instance.
Variables
static const unsigned Max6DecimalOffset = 999999
static const unsigned Max7DecimalOffset = 9999999
static const uint64_t MaxBase64Offset = 0xFFFFFFFFFULL
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "WinCOFFObjectWriter"
Definition at line 39 of file WinCOFFObjectWriter.cpp.
Function Documentation
encodeBase64StringEntry()
void encodeBase64StringEntry (char * Buffer, uint64_t Value) static
Definition at line 449 of file WinCOFFObjectWriter.cpp.
References Max7DecimalOffset, and MaxBase64Offset.
getSymbolValue()
uint64_t getSymbolValue (const MCSymbolData & Data, const MCAsmLayout & Layout) static
Definition at line 350 of file WinCOFFObjectWriter.cpp.
References llvm::MCSymbolData::getCommonSize(), llvm::MCAsmLayout::getSymbolOffset(), llvm::MCSymbolData::isCommon(), and llvm::MCSymbolData::isExternal().
write_uint32_le()
void write_uint32_le (void * Data, uint32_t Value) inline static
Definition at line 187 of file WinCOFFObjectWriter.cpp.
References llvm::support::endian::write().
Variable Documentation
Max6DecimalOffset
const unsigned Max6DecimalOffset = 999999 static
Definition at line 442 of file WinCOFFObjectWriter.cpp.
Max7DecimalOffset
const unsigned Max7DecimalOffset = 9999999 static
Definition at line 443 of file WinCOFFObjectWriter.cpp.
Referenced by encodeBase64StringEntry().
MaxBase64Offset
const uint64_t MaxBase64Offset = 0xFFFFFFFFFULL static
Definition at line 444 of file WinCOFFObjectWriter.cpp.
Referenced by encodeBase64StringEntry().