LLVM: X86ATTInstPrinter.cpp File Reference
LLVM API Documentation
X86ATTInstPrinter.cpp File Reference
#include "X86ATTInstPrinter.h"
#include "MCTargetDesc/X86BaseInfo.h"
#include "MCTargetDesc/X86MCTargetDesc.h"
#include "X86InstComments.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormattedStream.h"
#include <map>
#include "X86GenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
#define PRINT_ALIAS_INSTR
Functions
static void printSSEAVXCC (int64_t Imm, raw_ostream &O)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 30 of file X86ATTInstPrinter.cpp.
PRINT_ALIAS_INSTR
#define PRINT_ALIAS_INSTR
Definition at line 33 of file X86ATTInstPrinter.cpp.
Function Documentation
printSSEAVXCC()
void printSSEAVXCC (int64_t Imm, raw_ostream & O) static
Definition at line 75 of file X86ATTInstPrinter.cpp.
References llvm_unreachable.
Referenced by llvm::X86ATTInstPrinter::printAVXCC(), llvm::X86IntelInstPrinter::printAVXCC(), llvm::X86ATTInstPrinter::printSSECC(), and llvm::X86IntelInstPrinter::printSSECC().