LLVM: X86FrameLowering.cpp File Reference
LLVM API Documentation
X86FrameLowering.cpp File Reference
#include "X86FrameLowering.h"
#include "X86InstrBuilder.h"
#include "X86InstrInfo.h"
#include "X86MachineFunctionInfo.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Support/Debug.h"
#include <cstdlib>
Functions
static unsigned getSUBriOpcode (unsigned IsLP64, int64_t Imm)
static unsigned getADDriOpcode (unsigned IsLP64, int64_t Imm)
static unsigned getANDriOpcode (bool IsLP64, int64_t Imm)
static unsigned getPUSHiOpcode (bool IsLP64, MachineOperand MO)
static unsigned getLEArOpcode (unsigned IsLP64)
static unsigned findDeadCallerSavedReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, const TargetRegisterInfo &TRI, bool Is64Bit)
static void emitSPUpdate (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, unsigned StackPtr, int64_t NumBytes, bool Is64BitTarget, bool Is64BitStackPtr, bool UseLEA, const TargetInstrInfo &TII, const TargetRegisterInfo &TRI)
static void mergeSPUpdatesUp (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, unsigned StackPtr, uint64_t *NumBytes=nullptr)
mergeSPUpdatesUp - Merge two stack-manipulating instructions upper iterator.
static void mergeSPUpdatesDown (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, unsigned StackPtr, uint64_t *NumBytes=nullptr)
static int mergeSPUpdates (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, unsigned StackPtr, bool doMergeWithPrevious)
static bool isEAXLiveIn (MachineFunction &MF)
static bool usesTheStack (const MachineFunction &MF)
static bool HasNestArgument (const MachineFunction *MF)
static unsigned GetScratchRegister (bool Is64Bit, bool IsLP64, const MachineFunction &MF, bool Primary)
Variables
cl::opt< bool > ForceStackAlign
static const uint64_t kSplitStackAvailable = 256
Function Documentation
emitSPUpdate()
void emitSPUpdate (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, unsigned StackPtr, int64_t NumBytes, bool Is64BitTarget, bool Is64BitStackPtr, bool UseLEA, const TargetInstrInfo & TII, const TargetRegisterInfo & TRI) static
emitSPUpdate - Emit a series of instructions to increment / decrement the stack pointer by a constant value.
Definition at line 172 of file X86FrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::addRegOffset(), llvm::BuildMI(), findDeadCallerSavedReg(), llvm::MachineBasicBlock::findDebugLoc(), llvm::MachineInstr::FrameSetup, getADDriOpcode(), llvm::getDefRegState(), getLEArOpcode(), getSUBriOpcode(), llvm::getUndefRegState(), and TII.
findDeadCallerSavedReg()
unsigned findDeadCallerSavedReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, const TargetRegisterInfo & TRI, bool Is64Bit) static
findDeadCallerSavedReg - Return a caller-saved register that isn't live when it reaches the "return" instruction. We can then pop a stack object to this register without worry about clobbering it.
Definition at line 113 of file X86FrameLowering.cpp.
References llvm::MachineModuleInfo::callsEHReturn(), llvm::SmallSet< T, N, C >::count(), F, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getMMI(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), and llvm::MCRegAliasIterator::isValid().
Referenced by emitSPUpdate().
getADDriOpcode()
unsigned getADDriOpcode (unsigned IsLP64, int64_t Imm) static
Definition at line 73 of file X86FrameLowering.cpp.
References llvm::isInt().
Referenced by llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), and emitSPUpdate().
getANDriOpcode()
unsigned getANDriOpcode (bool IsLP64, int64_t Imm) static
Definition at line 85 of file X86FrameLowering.cpp.
References llvm::isInt().
Referenced by llvm::X86FrameLowering::emitPrologue().
getLEArOpcode()
unsigned getLEArOpcode (unsigned IsLP64) static
Definition at line 106 of file X86FrameLowering.cpp.
Referenced by llvm::X86FrameLowering::emitEpilogue(), and emitSPUpdate().
getPUSHiOpcode()
unsigned getPUSHiOpcode (bool IsLP64, MachineOperand MO) static
Definition at line 96 of file X86FrameLowering.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::isImm(), and llvm::isInt().
GetScratchRegister()
unsigned GetScratchRegister (bool Is64Bit, bool IsLP64, const MachineFunction & MF, bool Primary) static
GetScratchRegister - Get a temp register for performing work in the segmented stack and the Erlang/HiPE stack prologue. Depending on platform and the properties of the function either one or two registers will be needed. Set primary to true for the first register, false for the second.
Definition at line 1465 of file X86FrameLowering.cpp.
References llvm::CallingConv::Fast, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), HasNestArgument(), llvm::CallingConv::HiPE, llvm::report_fatal_error(), and llvm::CallingConv::X86_FastCall.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), and llvm::X86FrameLowering::adjustForSegmentedStacks().
getSUBriOpcode()
unsigned getSUBriOpcode (unsigned IsLP64, int64_t Imm) static
Definition at line 61 of file X86FrameLowering.cpp.
References llvm::isInt().
Referenced by llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::emitPrologue(), and emitSPUpdate().
HasNestArgument()
bool HasNestArgument (const MachineFunction * MF) static
Definition at line 1450 of file X86FrameLowering.cpp.
References F, llvm::MachineFunction::getFunction(), and I.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), and GetScratchRegister().
isEAXLiveIn()
bool isEAXLiveIn (MachineFunction & MF) static
Definition at line 319 of file X86FrameLowering.cpp.
References llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::livein_begin(), and llvm::MachineRegisterInfo::livein_end().
Referenced by llvm::X86FrameLowering::emitPrologue().
mergeSPUpdates()
int mergeSPUpdates (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, unsigned StackPtr, bool doMergeWithPrevious) static
mergeSPUpdates - Checks the instruction before/after the passed instruction. If it is an ADD/SUB/LEA instruction it is deleted argument and the stack adjustment is returned as a positive value for ADD/LEA and a negative for SUB.
Definition at line 288 of file X86FrameLowering.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by llvm::X86FrameLowering::emitEpilogue(), and llvm::X86FrameLowering::emitPrologue().
mergeSPUpdatesDown()
void mergeSPUpdatesDown (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, unsigned StackPtr, uint64_t * NumBytes = nullptr) static
mergeSPUpdatesDown - Merge two stack-manipulating instructions lower iterator.
Definition at line 255 of file X86FrameLowering.cpp.
References llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by llvm::X86FrameLowering::emitPrologue().
mergeSPUpdatesUp()
void mergeSPUpdatesUp (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, unsigned StackPtr, uint64_t * NumBytes = nullptr) static
mergeSPUpdatesUp - Merge two stack-manipulating instructions upper iterator.
Definition at line 230 of file X86FrameLowering.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::erase(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by llvm::X86FrameLowering::emitEpilogue().
usesTheStack()
bool usesTheStack (const MachineFunction & MF) static
usesTheStack - This function checks if any of the users of EFLAGS copies the EFLAGS. We know that the code that lowers COPY of EFLAGS has to use the stack, and if we don't adjust the stack we clobber the first frame index. See X86InstrInfo::copyPhysReg.
Definition at line 366 of file X86FrameLowering.cpp.
References llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::reg_instr_begin(), and llvm::MachineRegisterInfo::reg_instr_end().
Referenced by llvm::X86FrameLowering::emitPrologue().
Variable Documentation
ForceStackAlign
cl::opt<bool> ForceStackAlign extern
Referenced by llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), and llvm::X86RegisterInfo::needsStackRealignment().
kSplitStackAvailable
const uint64_t kSplitStackAvailable = 256 static
Definition at line 1499 of file X86FrameLowering.cpp.