LLVM: X86ISelDAGToDAG.cpp File Reference
LLVM API Documentation
X86ISelDAGToDAG.cpp File Reference
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86MachineFunctionInfo.h"
#include "X86RegisterInfo.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <stdint.h>
#include "X86GenDAGISel.inc"
Macros
#define DEBUG_TYPE "x86-isel"
Enumerations
enum AtomicOpc {
ADD , SUB , INC , DEC ,
OR , AND , XOR , AtomicOpcEnd
}
enum AtomicSz {
ConstantI8 , I8 , SextConstantI16 , ConstantI16 ,
I16 , SextConstantI32 , ConstantI32 , I32 ,
SextConstantI64 , ConstantI64 , I64 , AtomicSzEnd
}
Functions
STATISTIC (NumLoadMoved, "Number of loads moved below TokenFactor")
static void MoveBelowOrigChain (SelectionDAG *CurDAG, SDValue Load, SDValue Call, SDValue OrigChain)
static bool isCalleeLoad (SDValue Callee, SDValue &Chain, bool HasCallSeq)
static bool isDispSafeForFrameIndex (int64_t Val)
static void InsertDAGNode (SelectionDAG &DAG, SDValue Pos, SDValue N)
static bool FoldMaskAndShiftToExtract (SelectionDAG &DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode &AM)
static bool FoldMaskedShiftToScaledMask (SelectionDAG &DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode &AM)
static bool FoldMaskAndShiftToScale (SelectionDAG &DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode &AM)
static SDValue getAtomicLoadArithTargetConstant (SelectionDAG *CurDAG, SDLoc dl, enum AtomicOpc &Op, MVT NVT, SDValue Val, const X86Subtarget *Subtarget)
static bool HasNoSignedComparisonUses (SDNode *N)
static bool isLoadIncOrDecStore (StoreSDNode *StoreNode, unsigned Opc, SDValue StoredVal, SelectionDAG *CurDAG, LoadSDNode *&LoadNode, SDValue &InputChain)
static unsigned getFusedLdStOpcode (EVT &LdVT, unsigned Opc)
Variables
static const uint16_t AtomicOpcTbl [AtomicOpcEnd][AtomicSzEnd]
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-isel"
Definition at line 40 of file X86ISelDAGToDAG.cpp.
Enumeration Type Documentation
AtomicOpc
enum AtomicOpc
Atomic opcode table
Enumerator
ADD
SUB
INC
DEC
OR
AND
XOR
AtomicOpcEnd
Definition at line 1580 of file X86ISelDAGToDAG.cpp.
AtomicSz
enum AtomicSz
Enumerator
ConstantI8
I8
SextConstantI16
ConstantI16
I16
SextConstantI32
ConstantI32
I32
SextConstantI64
ConstantI64
I64
AtomicSzEnd
Definition at line 1591 of file X86ISelDAGToDAG.cpp.
Function Documentation
FoldMaskAndShiftToExtract()
bool FoldMaskAndShiftToExtract (SelectionDAG & DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode & AM) static
Definition at line 790 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::AND, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::hasOneUse(), llvm::MVT::i8, InsertDAGNode(), llvm::isa(), N, llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::SHL, llvm::ISD::SRL, and llvm::X.
FoldMaskAndShiftToScale()
bool FoldMaskAndShiftToScale (SelectionDAG & DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode & AM) static
Definition at line 900 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::ANY_EXTEND, llvm::SelectionDAG::computeKnownBits(), llvm::countLeadingZeros(), llvm::CountTrailingOnes_64(), llvm::countTrailingZeros(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::APInt::getHighBitsSet(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::hasOneUse(), llvm::MVT::i8, InsertDAGNode(), llvm::isa(), N, llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::SHL, llvm::ISD::SRL, llvm::X, and llvm::ISD::ZERO_EXTEND.
FoldMaskedShiftToScaledMask()
bool FoldMaskedShiftToScaledMask (SelectionDAG & DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode & AM) static
Definition at line 833 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::AND, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::hasOneUse(), InsertDAGNode(), llvm::isa(), N, llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::SHL, and llvm::X.
getAtomicLoadArithTargetConstant()
SDValue getAtomicLoadArithTargetConstant (SelectionDAG * CurDAG, SDLoc dl, enum AtomicOpc & Op, MVT NVT, SDValue Val, const X86Subtarget * Subtarget) static
Definition at line 1706 of file X86ISelDAGToDAG.cpp.
References ADD, DEC, llvm::dyn_cast(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ConstantSDNode::getSExtValue(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SDValue::hasOneUse(), llvm::MVT::i16, INC, llvm::X86::isZeroNode(), llvm::X86Subtarget::slowIncDec(), llvm::ISD::SUB, SUB, and llvm::ISD::TRUNCATE.
getFusedLdStOpcode()
unsigned getFusedLdStOpcode (EVT & LdVT, unsigned Opc) static
getFusedLdStOpcode - Get the appropriate X86 opcode for an in memory increment or decrement. Opc should be X86ISD::DEC or X86ISD::INC.
Definition at line 2017 of file X86ISelDAGToDAG.cpp.
References llvm::X86ISD::DEC, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86ISD::INC, and llvm_unreachable.
HasNoSignedComparisonUses()
bool HasNoSignedComparisonUses (SDNode * N) static
HasNoSignedComparisonUses - Test whether the given X86ISD::CMP node has any uses which require the SF or OF bits to be accurate.
Definition at line 1869 of file X86ISelDAGToDAG.cpp.
References llvm::cast(), llvm::ISD::CopyToReg, N, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
InsertDAGNode()
void InsertDAGNode (SelectionDAG & DAG, SDValue Pos, SDValue N) static
Definition at line 778 of file X86ISelDAGToDAG.cpp.
References llvm::SDValue::getNode(), llvm::SDNode::getNodeId(), N, and llvm::SelectionDAG::RepositionNode().
Referenced by FoldMaskAndShiftToExtract(), FoldMaskAndShiftToScale(), and FoldMaskedShiftToScaledMask().
isCalleeLoad()
bool isCalleeLoad (SDValue Callee, SDValue & Chain, bool HasCallSeq) static
isCalleeLoad - Return true if call address is a load and it can be moved below CALLSEQ_START and the chains leading up to the call. Return the CALLSEQ_START by reference as a second output. In the case of a tail call, there isn't a callseq node between the call chain and the load.
Definition at line 417 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::CALLSEQ_START, llvm::cast(), llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::SDValue::getValue(), llvm::SDValue::hasOneUse(), llvm::isa(), llvm::SDValue::isOperandOf(), llvm::ISD::NON_EXTLOAD, llvm::ISD::TokenFactor, and llvm::ISD::UNINDEXED.
isDispSafeForFrameIndex()
bool isDispSafeForFrameIndex (int64_t Val) static
Definition at line 592 of file X86ISelDAGToDAG.cpp.
References llvm::isInt().
isLoadIncOrDecStore()
bool isLoadIncOrDecStore (StoreSDNode * StoreNode, unsigned Opc, SDValue StoredVal, SelectionDAG * CurDAG, LoadSDNode *& LoadNode, SDValue & InputChain) static
isLoadIncOrDecStore - Check whether or not the chain ending in StoreNode is suitable for doing the {load; increment or decrement; store} to modify transformation.
Definition at line 1932 of file X86ISelDAGToDAG.cpp.
References llvm::cast(), llvm::X86ISD::DEC, llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNodeId(), llvm::LoadSDNode::getOffset(), llvm::StoreSDNode::getOffset(), llvm::SDNode::getOperand(), llvm::SDValue::getOperand(), llvm::SDValue::getResNo(), llvm::SDNode::hasNUsesOfValue(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86ISD::INC, llvm::MemSDNode::isNonTemporal(), llvm::ISD::isNormalLoad(), llvm::ISD::isNormalStore(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::ISD::TokenFactor, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
MoveBelowOrigChain()
void MoveBelowOrigChain (SelectionDAG * CurDAG, SDValue Load, SDValue Call, SDValue OrigChain) static
MoveBelowCallOrigChain - Replace the original chain operand of the call with load's chain operand and move load below the call's chain operand.
Definition at line 379 of file X86ISelDAGToDAG.cpp.
References llvm::Call, llvm::SmallVectorImpl< T >::clear(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOperand(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::ISD::TokenFactor, and llvm::SelectionDAG::UpdateNodeOperands().
STATISTIC()
STATISTIC (NumLoadMoved , "Number of loads moved below TokenFactor")
Variable Documentation
AtomicOpcTbl
const uint16_t AtomicOpcTbl[AtomicOpcEnd][AtomicSzEnd] static
Definition at line 1606 of file X86ISelDAGToDAG.cpp.