LLVM: X86MCAsmInfo.cpp File Reference
LLVM API Documentation
X86MCAsmInfo.cpp File Reference
#include "X86MCAsmInfo.h"
#include "llvm/ADT/Triple.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ELF.h"
Enumerations
enum AsmWriterFlavorTy { ATT = 0 , Intel = 1 }
Variables
static cl::opt< AsmWriterFlavorTy > AsmWriterFlavor ("x86-asm-syntax", cl::init(ATT), cl::desc("Choose style of code to emit from X86 backend:"), cl::values(clEnumValN(ATT, "att", "Emit AT&T-style assembly"), clEnumValN(Intel, "intel", "Emit Intel-style assembly"), clEnumValEnd))
static cl::opt< bool > MarkedJTDataRegions ("mark-data-regions", cl::init(false), cl::desc("Mark code section jump table data regions."), cl::Hidden)
Enumeration Type Documentation
AsmWriterFlavorTy
enum AsmWriterFlavorTy
Enumerator
ATT
Intel
Definition at line 24 of file X86MCAsmInfo.cpp.
Variable Documentation
AsmWriterFlavor
cl::opt< AsmWriterFlavorTy > AsmWriterFlavor("x86-asm-syntax", cl::init(ATT), cl::desc("Choose style of code to emit from X86 backend:"), cl::values(clEnumValN(ATT, "att", "Emit AT&T-style assembly"), clEnumValN(Intel, "intel", "Emit Intel-style assembly"), clEnumValEnd)) ("x86-asm-syntax" , cl::init(ATT) , cl::desc("Choose style of code to emit from X86 backend:") , cl::values(clEnumValN(ATT, "att", "Emit AT&T-style assembly"), clEnumValN(Intel, "intel", "Emit Intel-style assembly"), clEnumValEnd)) static
Referenced by llvm::X86ELFMCAsmInfo::X86ELFMCAsmInfo(), llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin(), llvm::X86MCAsmInfoGNUCOFF::X86MCAsmInfoGNUCOFF(), and llvm::X86MCAsmInfoMicrosoft::X86MCAsmInfoMicrosoft().
MarkedJTDataRegions
cl::opt< bool > MarkedJTDataRegions("mark-data-regions", cl::init(false), cl::desc("Mark code section jump table data regions."), cl::Hidden) ("mark-data-regions" , cl::init(false) , cl::desc("Mark code section jump table data regions.") , cl::Hidden) static
Referenced by llvm::X86MCAsmInfoDarwin::X86MCAsmInfoDarwin().