LLVM: X86Subtarget.cpp File Reference
LLVM API Documentation
X86Subtarget.cpp File Reference
#include "X86Subtarget.h"
#include "X86InstrInfo.h"
#include "X86TargetMachine.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "X86GenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Functions
static std::string computeDataLayout (const Triple &TT)
Variables
static cl::opt< bool > X86EarlyIfConv ("x86-early-ifcvt", cl::Hidden, cl::desc("Enable early if-conversion on X86"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "subtarget"
Definition at line 34 of file X86Subtarget.cpp.
GET_SUBTARGETINFO_CTOR
#define GET_SUBTARGETINFO_CTOR
Definition at line 37 of file X86Subtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 36 of file X86Subtarget.cpp.
Function Documentation
computeDataLayout()
std::string computeDataLayout (const Triple & TT) static
Definition at line 285 of file X86Subtarget.cpp.
References llvm::Triple::getEnvironment(), llvm::DataLayout::getManglingComponent(), llvm::Triple::GNUX32, llvm::Triple::isArch64Bit(), llvm::Triple::isOSDarwin(), llvm::Triple::isOSNaCl(), and llvm::Triple::isOSWindows().
Variable Documentation
X86EarlyIfConv
cl::opt< bool > X86EarlyIfConv("x86-early-ifcvt", cl::Hidden, cl::desc("Enable early if-conversion on X86")) ("x86-early-ifcvt" , cl::Hidden , cl::desc("Enable early if-conversion on X86")) static
Referenced by llvm::X86Subtarget::enableEarlyIfConversion().