LLVM: X86TargetMachine.cpp File Reference
LLVM API Documentation
X86TargetMachine.cpp File Reference
#include "X86TargetMachine.h"
#include "X86.h"
#include "X86TargetObjectFile.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Function.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetOptions.h"
Functions
void LLVMInitializeX86Target ()
static std::unique_ptr< TargetLoweringObjectFile > createTLOF (const Triple &TT)
Variables
static cl::opt< bool > UseVZeroUpper ("x86-use-vzeroupper", cl::Hidden, cl::desc("Minimize AVX to SSE transition penalty"), cl::init(true))
Function Documentation
createTLOF()
std::unique_ptr< TargetLoweringObjectFile > createTLOF (const Triple & TT) static
Definition at line 32 of file X86TargetMachine.cpp.
References llvm::Triple::getArch(), llvm::Triple::isKnownWindowsMSVCEnvironment(), llvm::Triple::isOSBinFormatCOFF(), llvm::Triple::isOSBinFormatELF(), llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSLinux(), llvm_unreachable, llvm::make_unique(), and llvm::Triple::x86_64.
LLVMInitializeX86Target()
void LLVMInitializeX86Target ()
Definition at line 26 of file X86TargetMachine.cpp.
References llvm::TheX86_32Target, llvm::TheX86_64Target, llvm::X, and Y.
Variable Documentation
UseVZeroUpper
cl::opt< bool > UseVZeroUpper("x86-use-vzeroupper", cl::Hidden, cl::desc("Minimize AVX to SSE transition penalty"), cl::init(true)) ("x86-use-vzeroupper" , cl::Hidden , cl::desc("Minimize AVX to SSE transition penalty") , cl::init(true)) static