LLVM: XCoreFrameLowering.cpp File Reference
LLVM API Documentation
XCoreFrameLowering.cpp File Reference
#include "XCoreFrameLowering.h"
#include "XCore.h"
#include "XCoreInstrInfo.h"
#include "XCoreMachineFunctionInfo.h"
#include "XCoreSubtarget.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetOptions.h"
#include <algorithm>
Functions
static bool isImmU6 (unsigned val)
static bool isImmU16 (unsigned val)
static bool CompareSSIOffset (const StackSlotInfo &a, const StackSlotInfo &b)
static void EmitDefCfaRegister (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo &TII, MachineModuleInfo *MMI, unsigned DRegNum)
static void EmitDefCfaOffset (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo &TII, MachineModuleInfo *MMI, int Offset)
static void EmitCfiOffset (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo &TII, MachineModuleInfo *MMI, unsigned DRegNum, int Offset)
static void IfNeededExtSP (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo &TII, MachineModuleInfo *MMI, int OffsetFromTop, int &Adjusted, int FrameSize, bool emitFrameMoves)
static void IfNeededLDAWSP (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo &TII, int OffsetFromTop, int &RemainingAdj)
static void GetSpillList (SmallVectorImpl< StackSlotInfo > &SpillList, MachineFrameInfo *MFI, XCoreFunctionInfo *XFI, bool fetchLR, bool fetchFP)
static void GetEHSpillList (SmallVectorImpl< StackSlotInfo > &SpillList, MachineFrameInfo *MFI, XCoreFunctionInfo *XFI, const TargetLowering *TL)
static MachineMemOperand * getFrameIndexMMO (MachineBasicBlock &MBB, int FrameIndex, unsigned flags)
static void RestoreSpillList (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo &TII, int &RemainingAdj, SmallVectorImpl< StackSlotInfo > &SpillList)
Variables
static const unsigned FramePtr = XCore::R10
static const int MaxImmU16 = (1<<16) - 1
Function Documentation
CompareSSIOffset()
bool CompareSSIOffset (const StackSlotInfo & a, const StackSlotInfo & b) static
Definition at line 57 of file XCoreFrameLowering.cpp.
Referenced by GetEHSpillList(), and GetSpillList().
EmitCfiOffset()
void EmitCfiOffset (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo & TII, MachineModuleInfo * MMI, unsigned DRegNum, int Offset) static
Definition at line 82 of file XCoreFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineModuleInfo::addFrameInst(), llvm::BuildMI(), llvm::TargetOpcode::CFI_INSTRUCTION, llvm::MCCFIInstruction::createOffset(), and TII.
Referenced by llvm::XCoreFrameLowering::emitPrologue().
EmitDefCfaOffset()
void EmitDefCfaOffset (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo & TII, MachineModuleInfo * MMI, int Offset) static
Definition at line 72 of file XCoreFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineModuleInfo::addFrameInst(), llvm::BuildMI(), llvm::TargetOpcode::CFI_INSTRUCTION, llvm::MCCFIInstruction::createDefCfaOffset(), and TII.
Referenced by llvm::XCoreFrameLowering::emitPrologue(), and IfNeededExtSP().
EmitDefCfaRegister()
void EmitDefCfaRegister (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo & TII, MachineModuleInfo * MMI, unsigned DRegNum) static
Definition at line 62 of file XCoreFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineModuleInfo::addFrameInst(), llvm::BuildMI(), llvm::TargetOpcode::CFI_INSTRUCTION, llvm::MCCFIInstruction::createDefCfaRegister(), and TII.
Referenced by llvm::XCoreFrameLowering::emitPrologue().
GetEHSpillList()
void GetEHSpillList (SmallVectorImpl< StackSlotInfo > & SpillList, MachineFrameInfo * MFI, XCoreFunctionInfo * XFI, const TargetLowering * TL) static
Creates an ordered list of EH info register 'spills'. These slots are only used by the unwinder and calls to llvm.eh.return(). Registers are ordered according to their frame offset. As offsets are negative, the largest offsets will be first.
Definition at line 161 of file XCoreFrameLowering.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), CompareSSIOffset(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::XCoreFunctionInfo::getEHSpillSlot(), llvm::TargetLoweringBase::getExceptionPointerRegister(), llvm::TargetLoweringBase::getExceptionSelectorRegister(), llvm::MachineFrameInfo::getObjectOffset(), llvm::XCoreFunctionInfo::hasEHSpillSlot(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::XCoreFrameLowering::emitEpilogue(), and llvm::XCoreFrameLowering::emitPrologue().
getFrameIndexMMO()
MachineMemOperand * getFrameIndexMMO (MachineBasicBlock & MBB, int FrameIndex, unsigned flags) static
Definition at line 177 of file XCoreFrameLowering.cpp.
References llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), and llvm::MachineBasicBlock::getParent().
Referenced by llvm::XCoreFrameLowering::emitPrologue(), and RestoreSpillList().
GetSpillList()
void GetSpillList (SmallVectorImpl< StackSlotInfo > & SpillList, MachineFrameInfo * MFI, XCoreFunctionInfo * XFI, bool fetchLR, bool fetchFP) static
Creates an ordered list of registers that are spilled during the emitPrologue/emitEpilogue. Registers are ordered according to their frame offset. As offsets are negative, the largest offsets will be first.
Definition at line 139 of file XCoreFrameLowering.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), CompareSSIOffset(), llvm::SmallVectorTemplateCommon< T, typename >::end(), FramePtr, llvm::XCoreFunctionInfo::getFPSpillSlot(), llvm::XCoreFunctionInfo::getLRSpillSlot(), llvm::MachineFrameInfo::getObjectOffset(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::XCoreFrameLowering::emitEpilogue(), and llvm::XCoreFrameLowering::emitPrologue().
IfNeededExtSP()
void IfNeededExtSP (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo & TII, MachineModuleInfo * MMI, int OffsetFromTop, int & Adjusted, int FrameSize, bool emitFrameMoves) static
The SP register is moved in steps of 'MaxImmU16' towards the bottom of the frame. During these steps, it may be necessary to spill registers. IfNeededExtSP emits the necessary EXTSP instructions to move the SP only as far as to make 'OffsetFromBottom' reachable using an STWSP_lru6.
Parameters
OffsetFromTop the spill offset from the top of the frame.
[in,out] Adjusted the current SP offset from the top of the frame.
Definition at line 98 of file XCoreFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), EmitDefCfaOffset(), isImmU6(), MaxImmU16, and TII.
Referenced by llvm::XCoreFrameLowering::emitPrologue().
IfNeededLDAWSP()
void IfNeededLDAWSP (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo & TII, int OffsetFromTop, int & RemainingAdj) static
The SP register is moved in steps of 'MaxImmU16' towards the top of the frame. During these steps, it may be necessary to re-load registers. IfNeededLDAWSP emits the necessary LDAWSP instructions to move the SP only as far as to make 'OffsetFromTop' reachable using an LDAWSP_lru6.
Parameters
OffsetFromTop the spill offset from the top of the frame.
[in,out] RemainingAdj the current SP offset from the top of the frame.
Definition at line 122 of file XCoreFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), isImmU6(), MaxImmU16, and TII.
Referenced by llvm::XCoreFrameLowering::emitEpilogue(), and RestoreSpillList().
isImmU16()
bool isImmU16 (unsigned val) inline static
Definition at line 43 of file XCoreFrameLowering.cpp.
Referenced by llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), and llvm::XCoreInstrInfo::loadImmediate().
isImmU6()
bool isImmU6 (unsigned val) inline static
Definition at line 39 of file XCoreFrameLowering.cpp.
Referenced by llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitPrologue(), IfNeededExtSP(), IfNeededLDAWSP(), InsertSPImmInst(), llvm::XCoreInstrInfo::loadImmediate(), and RestoreSpillList().
RestoreSpillList()
void RestoreSpillList (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc dl, const TargetInstrInfo & TII, int & RemainingAdj, SmallVectorImpl< StackSlotInfo > & SpillList) static
Restore clobbered registers with their spill slot value. The SP will be adjusted at the same time, thus the SpillList must be ordered with the largest (negative) offsets first.
Definition at line 192 of file XCoreFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), getFrameIndexMMO(), IfNeededLDAWSP(), isImmU6(), llvm::MachineMemOperand::MOLoad, llvm::SmallVectorTemplateCommon< T, typename >::size(), and TII.
Referenced by llvm::XCoreFrameLowering::emitEpilogue().
Variable Documentation
FramePtr
const unsigned FramePtr = XCore::R10 static
Definition at line 35 of file XCoreFrameLowering.cpp.
Referenced by llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::AArch64FrameLowering::emitCalleeSavedFrameMoves(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), GetSpillList(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), and replaceFI().
MaxImmU16
const int MaxImmU16 = (1<<16) - 1 static
Definition at line 36 of file XCoreFrameLowering.cpp.
Referenced by llvm::XCoreFrameLowering::emitPrologue(), IfNeededExtSP(), and IfNeededLDAWSP().